### ISSUE TITLE
PER PARTITION LIMIT return empty pages

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#10008]
While looking at failing test in java-driver-matrix run into a test [`should_select_with_per_partition_limit`](https://github.com/scylladb/java-driver/blob/4.x/integration-tests/src/test/java/com/datastax/oss/driver/mapper/SelectOtherClausesIT.java#L99)

which assume that `SELECT * FROM simple PER PARTITION LIMIT 5` we should get only one page back.

This is a python reproduction of the same thing in dtest, we get one page with the expected results, and a next page with empty results:
```python
import pytest

from dtest_class import Tester, create_ks
from tools.paging import PageFetcher


class TestJavaFailure(Tester):
    @pytest.mark.single_node
    def test_should_select_with_per_partition_limit(self):
        cluster = self.cluster
        cluster.populate(1).start(wait_for_binary_proto=True, wait_other_notice=True)
        node1 = cluster.nodelist()[0]
        session = self.patient_cql_connection(node1)

        create_ks(session, 'ks1', 1)

        session.execute("CREATE TABLE simple (k int, cc int, v int, PRIMARY KEY (k, cc))")

        for k in range(2):
            for cc in range(10):
                session.execute(f"INSERT INTO simple (k, cc, v) VALUES ({k}, {cc}, 1)")

        future = session.execute_async("SELECT * FROM simple PER PARTITION LIMIT 5")

        pf = PageFetcher(future)
        assert pf.pagecount() == 1
        assert not pf.has_more_pages, "we should be getting only one page"
```

**Comment by avikivity** [comment]
The test has wrong expectations. It is [legal](https://github.com/apache/cassandra/blob/trunk/doc/native_protocol_v4.spec#L1034) to return pages that are smaller than the ones requested, and Scylla takes advantage of this.

**Comment by nyh** [comment]
@fruch said the last page is empty (though the test code doesn't seem to check specifically that problem). I agree that there is nothing inherently wrong with the last page (or any page) being empty, and there are some good reasons why this can happen (i.e., if the first page was completely filled, and Scylla can't know that the next page will contain nothing), isn't it still curious why it happens in this specific case?

**Comment by avikivity** [comment]
I reproduced it, and I agree it's odd.

It probably has very little impact. Full scans typically iterate through many pages, and an extra one at the end won't make a difference. Still, it would be good to understand it.

**Comment by fruch** [comment]
> @fruch said the last page is empty (though the test code doesn't seem to check specifically that problem). I agree that there is nothing inherently wrong with the last page (or any page) being empty, and there are some good reasons why this can happen (i.e., if the first page was completely filled, and Scylla can't know that the next page will contain nothing), isn't it still curious why it happens in this specific case?

this assert is failing, assuming we only get one page, and not get indication there's more page to read.
```python
assert not pf.has_more_pages
```

**Comment by avikivity** [comment]
Why do you assert it? There's nothing that guarantees the number of pages in a result.

**Comment by fruch** [comment]
It's one of the java driver integration tests assertions
https://github.com/scylladb/java-driver/blob/4.x/integration-tests/src/test/java/com/datastax/oss/driver/mapper/SelectOtherClausesIT.java#L99

I've just duplicate in python to verify it's actually Scylla behavior. (and not the java driver)

Anyhow, needed a confirmation that is the expected result, need we can skip that test.

**Comment by avikivity** [comment]
It's not expected or unexpected, Scylla has freedom to return any number of pages.
