### ISSUE TITLE
Docker build based on local build is failing

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10018]
When I follow the instructions for building a docker image from a compiled Scylla (`dist/docker/debian/README.md`), and reach running `./dist/docker/debian/build_docker.sh --mode dev`, I get the error:

```
error adding content to container "ubuntu-working-container-8": checking on sources under "/": copier: stat: "/home/nyh/scylla/tools/java/build/debian/scylla-tools_5.0.dev-0.20220201.630d0afbe-1_all.deb": no such file or directory
```

Looking at `tools/java/build/debian/` I see various `scylla-tools_*` files, but all are 4.6 and 4.7, not 5.0. The last one is `scylla-tools-core_4.7.dev-0.20220105.0bd67a523-1_all.deb` built (or retrieved?) just now.

**Comment by nyh** [comment]
The problem is that we have

build/SCYLLA-VERSION-FILE:5.0.dev

but

tools/java/build/SCYLLA-VERSION-FILE:4.7.dev
tools/jmx/build/SCYLLA-VERSION-FILE:4.7.dev
tools/python3/build/SCYLLA-VERSION-FILE:4.7.dev

I am guessing that pulling the source from scratch would solve this inconsistency, but I want it to be handled automatically so not every developer will face this problem, so I want to figure out why these files aren't being rebuilt.

**Comment by nyh** [comment]
This is related to commit d72465531eb0948b8d9ab48aef205afb71d2446b by @avikivity. One of the build-reloc.sh calls was fixed in that commit, but others were missed. I'll try to provide a followup patch using the same solution.

**Comment by nyh** [comment]
It turns out that @avikivity change in commit d724655 was correct - the correct version is picked up when building the relocatable package. But the problem was that the relocatable package was not rebuilt if this version changed - as it did today from 4.7 to 5.0. I sent a patch to the mailing list, titled "build: rebuild relocatable packages if version changed".

**Comment by avikivity** [comment]
Not backporting. Older versions are built in a clean directory, and only incremental builds are vulnerable.
