### ISSUE TITLE
Messaging service tries to stream mutation to a node that was removed from gossiper

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#1001]
Run two nodes, populate with data, add one more node and kill it when streaming starts. After 30000ms gossiper prints:
  [shard 0] gossip - FatClient 127.0.0.3 has been silent for 30000ms, removing from gossip

After that 

curl -X GET "http://`hostname`:10000/failure_detector/endpoints/states/127.0.0.3";echo

reports "unknown endpoint" (it was endpoint in BOOT state before).

But streaming tries to continue anyway and prints:
 [shard 0] messaging_service - Retry verb=17 to 127.0.0.3:0, retry=9: rpc::closed_error (connection is closed)

**Comment by gleb-cloudius** [comment]
@asias can you look please?

**Comment by asias** [comment]
ok. will do.  What exact cmd you used to populate data and kill the node will helpful.

**Comment by gleb-cloudius** [comment]
On Tue, Mar 08, 2016 at 12:56:19AM -0800, Asias He wrote:
> ok. will do.  What exact cmd you used to populate data and kill the node will helpful.
> 
I populate it with:

cassandra-stress write n=100000 cl=ONE no-warmup -mode native cql3 -node
127.0.0.1 -rate threads=150 -schema replication\(strategy=org.apache.cassandra.locator.SimpleStrategy,factor=1\)
-pop seq=1..100000

I kill a node with ^C.

--
			Gleb.

**Comment by asias** [comment]
Patch sent
