### ISSUE TITLE
Docker image fails to run Alternator with HTTPS

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10025]
The following commands
```
docker pull scylladb/scylla-nightly:latest
docker run --name scylla -d -p 8443:8443 scylladb/scylla-nightly:latest --alternator-https-port=8443 --alternator-write-isolation=always
```
Currently results in `docker logs scylla` (my docker is moby-engine-20.10.12-1.fc34.x86_64):
```
or::server>::~sharded() [Service = alternator::server]: Assertion `_instances.empty()' failed.
Aborting on shard 0.
```

I get the same problem when I build my own docker image from latest master and run it with podman (using the instructions in `dist/docker/debian/README.md`).

If I try to run the same thing with `--alternator-http-port`, it works.

Scylla prints in in the log its command line, and it appears correct:
```
command used: "/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info
--network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.2
--rpc-address 172.17.0.2 --seed-provider-parameters seeds=172.17.0.2
--alternator-address 172.17.0.2 --alternator-https-port 8443 --alternator-write-isolation always
--blocked-reactor-notify-ms 999999999"
```

When I try to run exactly the same command outside docker (with changed IP address and --workdir), it works...

I'm surprised that commit 79776ff2ffab287180cd7baa397668b52f96256d didn't fix the assertion error. If there's a problem starting Alternator for some reason, I would have liked to see a real error message, not an assertion failure - and that commit should have fixed it.

**Comment by nyh** [comment]
This bug still exists in today's latest nightly. 
Backtrace:
```
scylla: ./seastar/include/seastar/core/sharded.hh:563: seastar::sharded<alternator::server>::~sharded() [Service = alternator::server]: Assertion `_instances.empty()' failed.
Aborting on shard 0.
Backtrace:
  0x4592ac8
  0x45c3652
  0x7f5fb26f3a1f
  /opt/scylladb/libreloc/libc.so.6+0x3d2a1
  /opt/scylladb/libreloc/libc.so.6+0x268a3
  /opt/scylladb/libreloc/libc.so.6+0x26788
  /opt/scylladb/libreloc/libc.so.6+0x35a15
  0x1073e77
  0x103c235
  0x103c225
  0x103c215
  0x103c0f3
  0x4813721
```

Decoding this backtrace doesn't add too much information:
```
~sharded at ././seastar/include/seastar/core/sharded.hh:563
 (inlined by) ~controller at ././alternator/controller.hh:49
 (inlined by) operator() at ./main.cc:1486
```

**Comment by nyh** [comment]
I was able to reproduce this exact crash when outside of docker with the command line
```
./build/dev/scylla --workdir /tmp/x --network-stack posix --developer-mode=1 --overprovisioned --listen-address 127.0.0.3 --rpc-address 127.0.0.3 --seed-provider-parameters seeds=127.0.0.3 --alternator-address 127.0.0.3 --alternator-https-port 8443 --alternator-write-isolation always --blocked-reactor-notify-ms 999999999
```
But the bug is only reproduced when I remove the SSL configuration files conf/scylla.crt and conf/scylla.key.

We actually documented the need for these files in https://hub.docker.com/r/scylladb/scylla/ and in docs/alternator/getting-started.md:
> Note that the --alternator-https-port option also requires that files /etc/scylla/scylla.crt and /etc/scylla/scylla.key be inserted into the image. These files contain an SSL certificate and key, respectively.

So the fact it doesn't work is not a bug.

HOWEVER, what **is** a bug is that Scylla needs to fail gracefully with an understandable error message in this case - not with a bizarre crash.

**Comment by nyh** [comment]
This problem is less minor than we hoped. Users are seeing crashes on various simple Alternator configuration mistakes (e.g., see https://github.com/scylladb/scylladb/issues/11520 discovered by @fee-mendes), and not knowing what to do because we given them a core dump instead clear information on what the mistake is.

This fix is already in 5.1, but not in 5.0 which was used in  https://github.com/scylladb/scylladb/issues/11520.

**Comment by nyh** [comment]
Backported to 5.0 (f0c521efdfe4b238fa94ad89d9a462f4803c2595).
Already in 5.1 and later.

**Comment by avikivity** [comment]
@nyh if you backport something, remove the "Backport candidate" label so it doesn't need to be evaluated again.

**Comment by nyh** [comment]
I saw that you already removed this label in July 5 so didn't remove it myself - but didn't realize something added the label back in July 21. I have no idea what added this label a second time. A bug?
