### ISSUE TITLE
If there are multiple values for a key, CQL silently chooses last value

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10037]
This is Scylla's version of https://issues.apache.org/jira/browse/CASSANDRA-13369, which Cassandra fixed in their version 3.11 (Cassandra commit 1a83efe2047d0138725d5e102cc40774f3b14641).

If the user attempts a CQL command such as
```
ALTER KEYSPACE ksname WITH replication = {'class' : 'NetworkTopologyStrategy', 'dc1' : 2, 'dc1': 3 }
```
The options are read in the CQL parser into a map (by the `convert_property_map()` function in `Cql.g`) and the second definition of the property `dc1` silently overrides the first one. The user gets neither a warning that this happened, nor an error.

In Cassandra, this was fixed in the aforementioned commit to produce a `SyntaxException` error.

This issue can be reproduced by the translated Cassandra unit test:
`cassandra_tests/validation/operations/alter_test.py`::`testAlterKeyspaceWithMultipleInstancesOfSameDCThrowsSyntaxException`

**Comment by avikivity** [comment]
Not backporting, it is a minor problem and doesn't affect correct inputs.
