### ISSUE TITLE
system.config table is not usable for inquiring experimental_features setting

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10047]
I wanted to inquire whether a certain experimental feature is enabled using the new `system.config` table, but unfortunately the row for `experimental_features` is:

```
name='experimental_features', source='cli', type='experimental features', value='["\x01","\r","\x06","\r"]
```

I don't know what these nonsense strings are, the "\x01" (byte value 1) may be an enum, but the "\r" (byte value 13) is strange. Maybe it's just a bug? What I would have liked to see is one of the names from db::experimental_features_t::map() (we can assume that all interesting features have just one name there - if there's more than one it doesn't matter which we'll find).

I don't know if this bug is specific to `experimental_features` or other special types of options have a similar bug.

CC @xemul

**Comment by nyh** [comment]
Update: I added another experimental feature, and the value got appended with an extra "\x04","\r". So I guess that 0x4 is the feature's number (not useful, but at least not random), and the "\r" is something we get after each option for no good reason :-)

**Comment by nyh** [comment]
We have in config.cc:
```c++
template <>
const config_type config_type_for<std::vector<enum_option<db::experimental_features_t>>> = config_type(
        "experimental features", value_to_json<std::vector<sstring>>);
```
I can't make much sense of all of this, but I found this scary cast in config_file.hh:
```c++
    std::function<json::json_return_type (const void*)> make_to_json(json::json_return_type (*func)(const NativeType&)) {
        return [func] (const void* value) {
            return func(*static_cast<const NativeType*>(value));
        };
```
All of this looks very wrong, but I don't know yet how to fix it.

**Comment by xemul** [comment]
> By the way I still don't understand if there's the opposite conversion somewhere... 

@nyh, here:
```
template<typename T>
bool utils::config_file::named_value<T>::set_value(sstring value, config_source src) {
    if (_liveness != liveness::LiveUpdate) {
        return false;
    }

    (*this)(boost::lexical_cast<T>(value), src);
    return true;
}
```

**Comment by avikivity** [comment]
Backported to 5.0. This is new to 5.0 so no further backports needed.
