### ISSUE TITLE
Quadratic behavior and compaction inefficiency when populating table on refresh or boot

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#10046]
Turns out that table population may face quadratic behavior and compaction inefficiency because of eager compaction.

The strategy may perform a N * log N operation on every step, which results in (N - 1) * N * log N

Compaction eagerness results in compaction inefficiency because it doesn't allow for the most efficient jobs out of the available candidates.

**Comment by raphaelsc** [comment]
Boot is actually not affected, as pointed out by @bhalevy, because auto compaction is temporarily disabled, so triggering compaction is a no op.

**Comment by avikivity** [comment]
Performance only, not backporting.
