### ISSUE TITLE
attempted to get a stream from a generation error on enabling cdc

### ISSUE THREAD

**Issue by justinvj15** [scylladb/scylla#10058]
I am trying to enable cdc on a few of the existing tables after doing alter table and enabling cdc getting the below error

`"com.datastax.oss.driver.api.core.servererrors.ServerError: cdc: attempted to get a stream from a generation that we know about, but weren't able to retrieve (generation timestamp: 2020/08/26 12:00:56, write timestamp: 2022/02/10 06:35:03). Make sure that the replicas which contain this generation's data are alive and reachable from this node.`. 

I have checked the scylla node system time and the application pods system time, all are in sync. Does anyone know what is the issue?. This is the first time cdc is enabled on the tables. A very old timestamp 2020/08/26 12:00:56 appears in the error. not sure from where it is coming from

*Installation details*
Scylla version (or git commit hash): 4.5.3-0.20211223.c8f14886d open source version
Cluster size: 3 node cluster
OS (RHEL/CentOS/Ubuntu/AWS AMI): ubuntu

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): VM
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by slivne** [comment]
@haaawk - CDC question

**Comment by kbr-** [comment]
@justinvj15 can you rolling-restart your nodes, check if the problem still happens, and post the logs from your nodes (after they finish restarting)?

**Comment by haaawk** [comment]
maybe an easier way would be to just run nodetool checkAndRepairCdcStreams? What do you think @kbr- ?

**Comment by kbr-** [comment]
Yes, if restarting doesn't work.

During restart the node will try to fetch the generation data again. If it fails, we will see in the logs why it failed (what kind of error occurred during the read), so it will give us a hint to the root cause of the problem.

**Comment by justinvj15** [comment]
This issue is fixed after running the checkAndRepairCdcStreams cmd after enabling cdc. we were initially on 4.1 and we did the rolling upgrade one version at a time(4.1 -> 4.2 -> 4.3 -> 4.4 -> 4.5) to reach to 4.5 version. 

below was the error we saw in logs

`Feb 10 06:59:05 scylla-2 scylla[13479]: [shard 0] cdc - Could not retrieve CDC streams with timestamp {2020/08/26 12:00:56} upon gossip event. Reason "std::runtime_error (Could not find CDC generation with timestamp 2020/08/26 12:00:56 in distributed system tables (current time: 2022/02/10 06:59:05), even though some node gossiped about it.)". Action: not retrying.`

thank you so much for your support

**Comment by kbr-** [comment]
So it looks like the CDC streams were missing from the `system_distributed` tables for some reason. I wonder what was the case. Perhaps the cluster was bootstrapped incorrectly (e.g. concurrently instead of sequentially, or ring_delay was too small, or wait_for_gossip_to_settle was disabled), and the data was not streamed properly?

This could also happen if you had `experimental` flag enabled in 4.2/4.1, then when upgrading to 4.3 the node tried to fetch the generation data from new tables introduced in 4.3 but the data was stored in old experimental tables pre-4.3 hence it couldn't be found.

Anyway, glad the problem was fixed.

**Comment by debojitkakoti** [comment]
@kbr- I can add few details for the same cluster where we experienced the error.
Cluster was always restarted sequentially on each upgrade process from 4.1 -> 4.2 -> 4.3 -> 4.4 -> 4.5 as mentioned in the upgrade documentation.
`wait_for_gossip_to_settle` is not configured explicitly ( Is it configured in scylla.yaml ?)
experimental flag was not enabled in 4.1 .
CDC feature is not being used in any other version along the upgrade process, it's used after cluster is upgraded successfully to 4.5 and running stable.

**Comment by justinvj15** [comment]
system_distributed.cdc_generation_timestamps table was empty after we enabled cdc after reaching the 4.5 version. once we ran checkAndRepairCdcStreams it created records and errors disappeared.

**Comment by kbr-** [comment]
@debojitkakoti or @justinvj15 if you have some time, could you perform the following query with CL=ALL (e.g. using `cqlsh`) and show the output?
```
select time from system_distributed.cdc_generation_descriptions ;
```

Also, could you show the output of
```
describe keyspace system_distributed
```
?
