### ISSUE TITLE
nodetool cleanup takes much longer (x10) on 4.6.rc5

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#10060]
while running 1TB job for 4.6.rc5, we saw that 2 nemesis are taking too long, and to compare, we ran the same job (with same SCT version) to compare the duration of these same nemesis.

for nemesis `run_unique_sequence` (that does few actions as a sequence of disruptions) we had:
* for 4.5.0 - 6.5 hours ([monitor here](http://54.75.54.147:3000/d/manager-2-5/longevity-1tb-7days-reproducer-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1644432499403&to=1644457910042)) - if terminated, [snapshot here](https://snapshots.raintank.io/dashboard/snapshot/WHm4qkZE7rCQRoFJKMB20THS1e5MCfIQ)
* for 4.6.rc5 - 15 hours ([monitor here](http://54.171.240.245:3000/d/manager-2-5/longevity-1tb-7days-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1644258896354&to=1644296187304)) - if terminated, [snapshot here](https://snapshots.raintank.io/dashboard/snapshot/m24DLEWnprM4tAgvL3WoL7phPEn46k62)

for nemesis `remove_node_than_add_node` we had:
* for 4.5.0 - 7 hours ([monitor here](http://54.75.54.147:3000/d/manager-2-5/longevity-1tb-7days-reproducer-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1644458717472&to=1644486340657)) - if terminated, [snapshot here](https://snapshots.raintank.io/dashboard/snapshot/5qnO4miRlR7NH6bKfMGS3c4wYmM0SwQj)
* for 4.6.rc5 - 22 hours ([monitor here](http://54.171.240.245:3000/d/manager-2-5/longevity-1tb-7days-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1644296923214&to=1644379714136)) - if terminated, [snapshot here](https://snapshots.raintank.io/dashboard/snapshot/BMuitL4YEsHHg6S26l3bzU6LpUTEGaYT?orgId=2)

logs for 4.6.rc5 can be found here:
job is still running, SCT runner has the logs in here - 34.245.57.209:/home/ubuntu/sct-results/latest

logs for 4.5.0 can be found here:
job is still running, SCT runner has the logs in here - 34.254.230.28:/home/ubuntu/sct-results/latest

**Comment by fgelcer** [comment]
logs will be added here, once they are collected

**Comment by slivne** [comment]
@fgelcer something is not correct with the links - all of them are the same - please provide correct links

```
http://54.75.54.147:3000/d/manager-2-5/longevity-1tb-7days-reproducer-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1644432577745&to=1644457655521
http://54.75.54.147:3000/d/manager-2-5/longevity-1tb-7days-reproducer-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1644432577745&to=1644457655521
http://54.75.54.147:3000/d/manager-2-5/longevity-1tb-7days-reproducer-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1644432577745&to=1644457655521
http://54.75.54.147:3000/d/manager-2-5/longevity-1tb-7days-reproducer-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1644432577745&to=1644457655521

```

**Comment by roydahan** [comment]
I'm fixing the links now

**Comment by slivne** [comment]
4.5.0
- ~2:15 - ~6:00 - remove node (~4 hours)
- ~6:00 - ~7:00 - add node (~1 hour)
4.6.0
- ~5:20 - ~8:00 - remove node (~3 hours)
- ~8:00 - ~4:00 - add node (~20 hours)

So add node takes much much longer

- yet are the graphs are not correct - e.g. checking when the nodes start servig cql traffic will tell us when the new node started to serve traffic
4.5 we have
![Screenshot from 2022-02-10 22-19-04](https://user-images.githubusercontent.com/3465480/153490024-25d844b9-0961-4fe4-9acc-109552cde0f9.png)

4.6 we have

![Screenshot from 2022-02-10 22-19-20](https://user-images.githubusercontent.com/3465480/153490166-daf0336f-41e7-4959-90d6-4927660c0764.png)

so we start to read after ~1 hour

bootstrap is ~8:00 - ~9:00

What we may be seeing is the cleanup after we added the node - if we are doing one

![Screenshot from 2022-02-10 22-24-03](https://user-images.githubusercontent.com/3465480/153490453-7e207c66-ed1b-4ddc-a9ba-0d7e6c3fa1d8.png)


@roydahan / @fgelcer are we doing cleanup in the remove_node_nemesis in both runs ?

@raphaelsc / @bhalevy have we moved nodetool cleanup to the "streaming" (aka maintenance) scheduling group ?

**Comment by fgelcer** [comment]
@slivne , AFAICT we don't run cleanup during `nodetool removenode`:
```
        def remove_node():
            # nodetool removenode 'host_id'
            rnd_node = random.choice([n for n in self.cluster.nodes if n is not self.target_node])
            self.log.info("Running removenode command on {}, Removing node with the following host_id: {}"
                          .format(rnd_node.ip_address, host_id))
            res = rnd_node.run_nodetool("removenode {}".format(host_id), ignore_status=True, verbose=True)
            return res.exit_status
```

should we keep the 4.5 cluster running, or can i terminate it (and leave only the monitor alive)?

**Comment by slivne** [comment]
I wnat to understand whats going on don;t terminate just yet

**Comment by slivne** [comment]
the question is if you added cleanup after add node not after remove node

are both tests using the same sct branch ?

which branch is used for 4.6 ?

**Comment by fgelcer** [comment]
> the question is if you added cleanup after add node not after remove node
> 

these are the steps the test is running:
```
1. Terminate node
2. Run full repair
3. Nodetool removenode
4. Add new node
```

> are both tests using the same sct branch ?
> 
> which branch is used for 4.6 ?

yes, both tests are running from very same SCT `branch-4.6`

**Comment by slivne** [comment]
@fgelcer / @roydahan it will help if you can upload the 4.6 logs so raphael can extract info about the compaction / cleanup relation

**Comment by fgelcer** [comment]
> @fgelcer / @roydahan it will help if you can upload the 4.6 logs so raphael can extract info about the compaction / cleanup relation

the cluster is right now live and running, and the way to collect its logs is to kill it... so right now, @raphaelsc can connect to the real running cluster and get any information he needs from there, but if the test ends before that, the logs will be uploaded and i will share them once it happens...

**Comment by slivne** [comment]
Well don't kill anything :)

To help @raphaelsc can you please post the cluster nodes info so he can try to login and extract what he needs

**Comment by fgelcer** [comment]
@raphaelsc , nodes are as in the following list:
4.5.0 nodes:
3.250.222.255
54.216.121.15
34.252.111.16
54.216.68.79

4.6.rc5 nodes:
3.250.33.83
3.250.22.225
34.242.90.171
54.77.136.6

just be aware that, at any moment, nodes can be terminated (and will be replaced by new nodes), or the test can fail and stop... in case of test failure, logs will be uploaded to S3 and can be found here:
[4.5.0 job](https://jenkins.scylladb.com/view/scylla-4.6/job/scylla-4.6/job/SCT-Reproducers/job/longevity-1tb-7days-reproducer-test/4/)
[4.6.rc5 job](https://jenkins.scylladb.com/view/scylla-4.6/job/scylla-4.6/job/longevity/view/Long%20Longevities/job/longevity-1tb-7days-test/7/)

**Comment by raphaelsc** [comment]
There are two things I will proceed with the investigation of:

1) The effect of streaming class (this is theoretically clear, but I'd like to understand better the practical effects)
2) The effect of this patch 40a6049ac285f1a317c6c804c09ae7363cd73ffb, which may be causing a significant delay between the compaction of each sstable being cleaned up, making the operation time much higher.

**Comment by slivne** [comment]
@bhalevy / @raphaelsc - for 4.6 we need to revert the move of clenaup to a different scheduling group we need to get the release out - you can try and resolve this - but it can't block 4.6.

I am not sure where this change was done - so please send either a revert of a patch that will place cleanup back in regular compaction and we will continue following that.

Please create a separate issue to track this - so the revert will close this issue for 4.6

**Comment by raphaelsc** [comment]
@slivne That's commit 4c05e5f966d691594a604cf076113efc7f42b1af. To be honest, I don't have complete understanding of the problem yet, but it's clear that moving to maintenance group only caused a regression (comparing cleanup progress rate between the two versions for example). I am proceeding with the revert now, so we can get 4.6 out, then I'll proceed with post-mortem analysis. Thanks.

**Comment by slivne** [comment]
thanks

**Comment by avikivity** [comment]
Backported to 4.6, 5.0, only vulnerable releases.

**Comment by bhalevy** [comment]
@raphaelsc @slivne I think that the main problem might be 40a6049ac285f1a317c6c804c09ae7363cd73ffb, rather than using maintenance scheduling group.

With this change rewrite_sstables acquires the compacting_state write lock for each sstable, so it would block behind regular compaction jobs.  The reason for taking this lock was to serialize other "maintenance" compaction jobs.

I think that after 6737c880458c216c9ab933b0348b9f78fe79c648 rewrite_sstables can just acquire the read lock and let regular compaction run non-interfered in the background.

That said, i'm not sure why the maintenance semaphore is acquired for each sstable rather than once for the whole rewrite_sstables task.

Also, to reduce compaction write amplification on the output sstables cleanup generates, maybe rewrite_sstables should add the output sstables in batches, maybe based on the buckets structure of the input sstables, i.e. work on one bucket at a time and add all the generated output sstables at once when done.  This requires more research though.

**Comment by fgelcer** [comment]
running with version `4.6.0-0.20220306.2f2d22a86 with build-id d487cdea729e95d8caebe2e9e2ae8698f35f19ee`

[monitor is here](http://44.203.25.122:3000/d/manager-2-5/longevity-1tb-7days-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1646934681491&to=1647200052920)

we see that nemesis `run_unique_sequence` (1st run of it) took ~10 hours - [monitor](http://44.203.25.122:3000/d/manager-2-5/longevity-1tb-7days-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1646960322735&to=1646998939066) ([snapshot](https://snapshots-origin.grafana.net/dashboard/snapshot/fr75yB9H1x5UUqXWbW2gIlw6y576FRsw))
the 2nd run of `run_unique_sequence` took ~7.5 hours - [monitor](http://44.203.25.122:3000/d/manager-2-5/longevity-1tb-7days-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1647126369861&to=1647155363961) ([snapshot](https://snapshots.raintank.io/dashboard/snapshot/ey09lkecITdDZuQQ6eI87SCL66mXANo4))

nemesis `remove_node_than_add_node` took ~19 hours - [monitor](http://44.203.25.122:3000/d/manager-2-5/longevity-1tb-7days-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1646998717505&to=1647070822110) ([snapshot](https://snapshots-origin.grafana.net/dashboard/snapshot/Dc2pDxdwqrJn6kDfDjtm9RUsEhcitulA?orgId=2))

@roydahan FYI

**Comment by roydahan** [comment]
Please add what is the expected time (took on 4.5) and how long each cleanup took.

**Comment by bhalevy** [comment]
Do we have SCT results for master with https://github.com/scylladb/scylla/issues/10175 fixed?

**Comment by fgelcer** [comment]
as reported in the issue description, for 4.5 `run_unique_sequence` took 6.5 hours and `remove_node_than_add_node` took 7 hours.

cleanup runs took the following times in `4.5.0-0.20211006.47be33a10 with build-id cae2146dc91480331365938fddb866fe4ecc0c56`:
during `remove_node_than_add_node` (took in total `7h13m9s`):
```
duration=36m45s
duration=15s
duration=33m45s
duration=18
duration=34m30s
duration=18s
duration=28m16s
duration=16s
```
during `run_unique_sequence` i don't see in the logs any `nodetool` command running

cleanup runs took the following times in `4.6.0-0.20220306.2f2d22a86 with build-id d487cdea729e95d8caebe2e9e2ae8698f35f19ee`:
during `remove_node_than_add_node` (took in total `19h20m34s`):
```
duration=3h41m42s
duration=20s
duration=3h1m22s
duration=17s
duration=4h20m50s
duration=17s
duration=5h16m53s
duration=14s
```

also here, during `run_unique_sequence` i can't see any cleanup running

logs will be listed below, by version

4.5.0
https://cloudius-jenkins-test.s3.amazonaws.com/ca90c7a1-f8f5-4f07-8bf0-7b77aa8e99a9/20220214_111759/sct-ca90c7a1.log.tar.gz
https://cloudius-jenkins-test.s3.amazonaws.com/ca90c7a1-f8f5-4f07-8bf0-7b77aa8e99a9/20220214_111759/events-ca90c7a1.log.tar.gz
https://cloudius-jenkins-test.s3.amazonaws.com/ca90c7a1-f8f5-4f07-8bf0-7b77aa8e99a9/20220214_111759/db-cluster-ca90c7a1.tar.gz


4.6.0
https://cloudius-jenkins-test.s3.amazonaws.com/c9f2cf14-a7bb-4c8f-b777-e35993610e3f/20220313_192720/sct-runner-c9f2cf14.tar.gz
https://cloudius-jenkins-test.s3.amazonaws.com/c9f2cf14-a7bb-4c8f-b777-e35993610e3f/20220313_192720/db-cluster-c9f2cf14.tar.gz

**Comment by fgelcer** [comment]
> Do we have SCT results for master with #10175 fixed?

running on master [here](https://jenkins.scylladb.com/view/master/job/scylla-master/job/longevity/job/longevity-1tb-7days/3/)

**Comment by slivne** [comment]
@fgelcer need input on the status following the run

**Comment by fgelcer** [comment]
> @fgelcer need input on the status following the run

@slivne , last run failed while starting c-s commands with error:
```
******************** Profile ********************
  Keyspace Name: mview
  Keyspace CQL: 
***

CREATE KEYSPACE mview WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 3};
***

  Table Name: users
  Table CQL: 
***

CREATE TABLE users (
  username text,
  first_name text,
  last_name text,
  password text,
  email text,
  last_access timeuuid,
  PRIMARY KEY(username)
);
***

  Extra Schema Definitions: [CREATE MATERIALIZED VIEW mview.users_by_first_name AS SELECT * FROM mview.users WHERE first_name IS NOT NULL and username IS NOT NULL PRIMARY KEY (first_name, username);, CREATE MATERIALIZED VIEW mview.users_by_last_name AS SELECT * FROM mview.users WHERE last_name IS NOT NULL and username IS NOT NULL PRIMARY KEY (last_name, username);]
  Generator Configs:
    password: Size: Fixed:  key=80;
    last_name: Size: Uniform:  min=1,max=32;
    first_name: Size: Fixed:  key=16;
    email: Size: Uniform:  min=16,max=50;
    username: Size: Uniform:  min=10,max=30;
  Query Definitions:
    read1: CQL:select * from mview.users where username = ? LIMIT 10;Fields:samerow;
    read2: CQL:select * from mview.users_by_first_name where username = ? and first_name = ? LIMIT 1;Fields:samerow;
    read3: CQL:select * from mview.users_by_last_name where username = ? and last_name = ? LIMIT 1;Fields:samerow;
  Token Range Queries:
  Insert Settings:
    partitions: fixed(1)
    batchtype: UNLOGGED
===== Using optimized driver!!! =====
Connected to cluster: longevity-tls-1tb-7d-master-db-cluster-79292eed, max pending requests per connection null, max connections per host 8
Datatacenter: eu-west; Host: /10.0.1.46; Rack: 1a
Datatacenter: eu-west; Host: /10.0.2.71; Rack: 1a
Datatacenter: eu-west; Host: /10.0.3.42; Rack: 1a
Datatacenter: eu-west; Host: /10.0.1.186; Rack: 1a
WARN  16:47:15,230 No schema agreement from live replicas after 10 s. The schema may not be up to date on some nodes.
com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.2.71:9042] Timed out waiting for server response
        at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:43)
        at com.datastax.driver.core.exceptions.OperationTimedOutException.copy(OperationTimedOutException.java:25)
        at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:35)
        at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:293)
        at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:58)
        at org.apache.cassandra.stress.util.JavaDriverClient.execute(JavaDriverClient.java:190)
        at org.apache.cassandra.stress.StressProfile.maybeCreateSchema(StressProfile.java:247)
        at org.apache.cassandra.stress.StressProfile.newGenerator(StressProfile.java:730)
        at org.apache.cassandra.stress.StressProfile.printSettings(StressProfile.java:131)
        at org.apache.cassandra.stress.settings.StressSettings.printSettings(StressSettings.java:383)
        at org.apache.cassandra.stress.Stress.run(Stress.java:95)
        at org.apache.cassandra.stress.Stress.main(Stress.java:62)
Caused by: com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.2.71:9042] Timed out waiting for server response
        at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onTimeout(RequestHandler.java:1020)
        at com.datastax.driver.core.Connection$ResponseHandler$1.run(Connection.java:1721)
        at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
        at com.datastax.shaded.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
        at com.datastax.shaded.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
        at com.datastax.shaded.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

it could be, like we saw in other occasions, nodes being under attack (port scans), like these:
```
[shard 0] rpc - client 80.82.77.33:53844: wrong protocol magic: 474554202f204854
[shard 0] rpc - client 80.82.77.33:53844: server connection dropped: connection is closed
[shard 2] rpc - client 80.82.77.33:54014: wrong protocol magic: 474554202f204854
[shard 2] rpc - client 80.82.77.33:54014: server connection dropped: connection is closed
[shard 10] rpc - client 80.82.77.33:54162: wrong protocol magic: 474554202f204854
[shard 10] rpc - client 80.82.77.33:54162: server connection dropped: connection is closed
[shard 6] rpc - client 80.82.77.33:54256: server connection dropped: connection is closed
[shard 8] rpc - client 80.82.77.33:54342: server connection dropped: sendmsg: Broken pipe
[shard 10] rpc - client 80.82.77.33:54372: server connection dropped: sendmsg: Broken pipe
[shard 10] rpc - client 80.82.77.33:54400: server connection dropped: sendmsg: Broken pipe
[shard 6] rpc - client 80.82.77.33:54452: server connection dropped: sendmsg: Broken pipe
[shard 0] rpc - client 80.82.77.33:54516: server connection dropped: sendmsg: Broken pipe
[shard 4] rpc - client 80.82.77.33:54576: server connection dropped: A packet with illegal or unsupported version was received.
[shard 12] rpc - client 80.82.77.33:54682: server connection dropped: sendmsg: Broken pipe
[shard 12] rpc - client 80.82.77.33:54724: server connection dropped: sendmsg: Broken pipe
[shard 6] rpc - client 80.82.77.33:54760: server connection dropped: No supported cipher suites have been found.
[shard 10] rpc - client 80.82.77.33:54778: server connection dropped: sendmsg: Broken pipe
[shard 12] rpc - client 80.82.77.33:54878: server connection dropped: A packet with illegal or unsupported version was received.
[shard 10] rpc - client 80.82.77.33:54932: server connection dropped: A packet with illegal or unsupported version was received.
[shard 4] rpc - client 80.82.77.33:55010: server connection dropped: A packet with illegal or unsupported version was received.
[shard 10] rpc - client 80.82.77.33:55058: server connection dropped: A packet with illegal or unsupported version was received.
[shard 0] rpc - client 80.82.77.33:55132: unexpected eof during negotiation frame
[shard 0] rpc - client 80.82.77.33:55132: server connection dropped: connection is closed
[shard 10] rpc - client 80.82.77.33:55226: unexpected eof during negotiation frame
[shard 10] rpc - client 80.82.77.33:55226: server connection dropped: connection is closed
[shard 12] rpc - client 80.82.77.33:55340: unexpected eof during negotiation frame
[shard 12] rpc - client 80.82.77.33:55340: server connection dropped: connection is closed
[shard 4] rpc - client 80.82.77.33:55402: server connection dropped: An unexpected TLS packet was received.
[shard 2] rpc - client 80.82.77.33:58550: unexpected eof during negotiation frame
[shard 2] rpc - client 80.82.77.33:58550: server connection dropped: connection is closed
[shard 4] rpc - client 80.82.77.33:58636: server connection dropped: No supported cipher suites have been found.
[shard 2] rpc - client 35.233.62.116:60118: wrong protocol magic: 474554202f204854
[shard 2] rpc - client 35.233.62.116:60118: server connection dropped: connection is closed
```

i didn't find anything at the exact same time c-s failed..
it failed once prepare load finished, and the main load was starting (3 out of the 4 c-s load started, and the 3rd one failed with critical event, and stopped the test).

i will re-run the test now

**Comment by fgelcer** [comment]
monitor alive [here](http://3.250.15.17:3000/d/ks-master/longevity-1tb-7days-scylla-per-server-metrics-nemesis-master?orgId=1&from=1647811536294&to=1647865187131)

**Comment by fgelcer** [comment]
build is `Scylla version 5.1.dev-0.20220317.c45050895403 with build-id 076f513b6143670def988c7626389b270411f8f7`
@bhalevy @slivne , the last build ran with the following times:

nemesis `RemoveNodeThenAddNode` (`remove_node_than_add_node`)
```
4h8m32s
3h49m8s
```

it is better than the run on 4.5
