### ISSUE TITLE
large data handler uses sstable full path to both record and delete records

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10075]
In some cases sstable are created in one directory (e.g. staging)
but are moved to a different directory (e.g. the table base directory)
before they are deleted.  In this case the large_data_handler will not find
the original path in the corresponding system.large* table and will fail
to delete to respective records for the sstable.

This is not too bad as the records are TTL'ed and they will eventually expire after 30 days.

However, this can be easily fixed by storing only the path basename rather than the full path since it uniquely identifies the sstable in the table, regardless of the directory it's current stored in.

**Comment by avikivity** [comment]
Minor, not backporting.
