### ISSUE TITLE
Support Ubuntu 16.04 LTS “Xenial Xerus”

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#1007]
It will release April 21st 2016(final beta is in March 24th), and should supported on our GA.
There is daily build, we can try our .deb package on it
http://cdimage.ubuntu.com/daily-live/current/

**Comment by slivne** [comment]
This is not for GA ... we do not have time to get this in and I doubt
adoption of users will be that fast - we can and should do 15.10 or 16.04
for 1.1

**Comment by syuu1228** [comment]
It was duplicated with https://github.com/scylladb/scylla/issues/609

**Comment by tzach** [comment]
@syuu1228 
are Ubuntu 15.10 (#609) and Ubuntu 16.04 the same?
Will use the same packages?

**Comment by syuu1228** [comment]
No.

**Comment by tzach** [comment]
Thanks
Reopening for 16.04 than

**Comment by tzach** [comment]
@slivne do we have packages for Ubuntu 16.04 as part of our nightly build?

**Comment by syuu1228** [comment]
Nightly build is added for 16.04
https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/xenial/master/8/scylla.list

**Comment by dorlaor** [comment]
Awesome! Can you please give it a test drive?

**Comment by slivne** [comment]
released
