### ISSUE TITLE
Conditional UPDATE fails to apply when IF includes both static and non-static columns.

### ISSUE THREAD

**Issue by aohotnik** [scylladb/scylla#10081]
*Installation details*
Scylla version 4.5.3, 4.6.rc5, 5.0rc1
Cluster size: 1
OS: Ubuntu
Platform: docker
Hardware: sockets=1 cores=6/12 hyperthreading=Y memory=16GB
Disks: SSD, 1

Problem: When IF clause for UPDATE statement includes both static and non-static columns, query fails to apply. Attached text file with script to reproduce.

CREATE TABLE condupdate.queues (
    event timeuuid,
    queue text,
    seqnumb bigint,
    seqnext bigint static,
    PRIMARY KEY((queue), event)
);

UPDATE condupdate.queues SET seqnext=2,seqnumb=1 WHERE queue='testqueue' AND event=now() IF seqnext = null and seqnumb=null;
UPDATE condupdate.queues SET seqnext=3,seqnumb=2 WHERE queue='testqueue' AND event=now() IF seqnext = 2 and seqnumb=null;
 [applied] | seqnext | seqnumb
-----------+---------+---------
     True |    null |    null
     False |       2 |    null <--- all returned values match conditions, but query is not applied.

Other observations: Success of first update appears misleading, it breaks in the following scenario:

TRUNCATE condupdate.queues;
INSERT INTO condupdate.queues(queue, seqnext) values('testqueue', 1) IF NOT EXISTS;
 [applied] | queue | event | seqnext | seqnumb
-----------+-------+-------+---------+---------
      True |  null |  null |    null |    null

UPDATE condupdate.queues SET seqnext=2,seqnumb=1 WHERE queue='testqueue' AND event=now() IF seqnext = 1 and seqnumb=null;
 [applied] | seqnext | seqnumb
-----------+---------+---------
     False |       1 |    null

This hints that whenever both static and normal columns are combined, current static column value is not "visible" during evaluation leading to it being observed as always equal to null. Proof:

TRUNCATE condupdate.queues;
UPDATE condupdate.queues SET seqnext=2,seqnumb=1 WHERE queue='testqueue' AND event=now() IF seqnext = null and seqnumb=null;
UPDATE condupdate.queues SET seqnext=3,seqnumb=2 WHERE queue='testqueue' AND event=now() IF seqnext = null  and seqnumb=null;
 [applied] | seqnext | seqnumb
-----------+---------+---------
      True |    null |    null
      True |       2 |    null

[reproduce.txt](https://github.com/scylladb/scylla/files/8068361/reproduce.txt)

**Comment by nyh** [comment]
@alecco created (ported from Cassandra) some LWT unit tests in `test/cql/cassandra_cql_test.cql`, and it also includes tests that have static columns (including setting them), but perhaps something in your test (like the combination of static and regular columns) is missing in those tests.

I'll try to reproduce your scenario with a test in test/cql-pytest.py. The advantage of cql-pytest is that it allows us to run the same test against Cassandra, to make sure the behavior we have is really wrong (of course Cassandra also has bugs, but often we have different bugs ;-)).

**Comment by nyh** [comment]
Trying to reproduce your second example, I discovered that while
```
UPDATE condupdate.queues SET seqnext=2,seqnumb=1 WHERE queue='testqueue' AND event=now() IF seqnext = 1 and seqnumb=null;
```
is broken (returns applied=False despite the condition matching), if I replace the null at the end with something non-null and if the clustering row exists and matches - then the condition does work.

So I think the underlying bug is as follows:

When the WHERE in the LWT update doesn't match any existing clustering row, the implementation doesn't read any existing row so we forget to read the static columns as well - and then the condition involving the static column fails.

I'm still cleaning up and documented my cql-pytest reproducer, and will send it when I'm done.

**Comment by nyh** [comment]
A minimal test that passes on Cassandra but fails on Scylla:
```python
    p = unique_key_int()
    # Insert into partition p just the static column - and no clustering rows.
    cql.execute(f'INSERT INTO {table1}(p, s) values ({p}, 1)')
    # Now, do an update with WHERE p={p} AND c=1. This clustering row does
    # *not* exist, so we expect to see r=null - and s=1 from before
    r = list(cql.execute(f'UPDATE {table1} SET s=2,r=1 WHERE p={p} AND c=1 IF s=1 and r=null'))
    assert r[0].applied == True
```

By the way, if I replace the `IF s=1 and r=null` above with `IF s=1`, it works! I think the code has a special path for the case where the condition has only static columns, in which case no clustering row needs to be read (and in fact the WHERE may not even specify the clustering key) - so the bug only happens when this special path doesn't happen, and Scylla wants to read the clustering row but doesn't find a matching one.

**Comment by nyh** [comment]
I sent a patch with a testg/cql-pytest reproducer for this bug: `test_lwt.py::test_lwt_missing_row_with_static`.

**Comment by kostja** [comment]
The statement is ambiguous. WHERE clause restricts the clustering key with 1. There is no row matching clustering key 1. IF clause is evaluated after the row is found. So Scylla, if there is no match in WHERE clause, returns an empty row. Cassandra returns a empty row with static columns set.

**Comment by kostja** [comment]
In other words,  AND c=1 is clearly not true for the data in the table, so it's unclear why the expectation is that the update should be applied.

**Comment by kostja** [comment]
It is not a regression, LWT didn't work till 4.0, the code works as intended (check cas_request::find_old_row()). I guess it's possible to incarnate static cells for the row returned and return them, instead of returning a fully empty row.

**Comment by aohotnik** [comment]
@kostja @nyh Please note that your comments diverted to WHERE close, while my problem arises when using IF for static and normal columns during UPDATE in a use case, when row is not existing yet and WHERE include values for primary key that was supposed to be upserted after execution. Query also returns correct value of static column when not applied and those values match condition. My expectation was that new row is inserted if IF conditions evaluate to true.

**Comment by kostja** [comment]
@nyh you can modify a non-existing row (or actually upsert it), but you expect to be able to read it and check its columns.

IF clause in your example evaluates row cells. If the row doesn't exist, there are no row cells. If the row does exist, then IF EXISTS for it should return TRUE, which would obviously be counter the expectation.

**Comment by nyh** [comment]
> @nyh you can modify a non-existing row (or actually upsert it), but you expect to be able to read it and check its columns.

Please note that the UPDATE may **write** to the static column as well - and of course that modifies the shared static column of the entire partition regardless of the chosen row. So, if the update can write to the static column, it should also be able to read from it.

I want to add that arguably we could have decided that we don't allow to read a static column in a "IF", and make such attempt into an error. But if the static column of the given partition has the value 1, and we evaluate it as "null" - I think this is just doesn't make sense.

**Comment by aohotnik** [comment]
@nyh Could you please advice on this, I have found another issue with same schema. This time with SELECT statement. I can create another issue, but if it is WAD that would be unnecessary.

Script attached. If you initialize static column with INSERT as in the script, the result will be row containing a row with nulls (static column wasn't part of select). If you skip INSERT however, the result will be empty. I'm not sure how to reason about expectation here, since presence of row is strange considering condition in where didn't not evaluate to TRUE.

[select.txt](https://github.com/scylladb/scylla/files/8081261/select.txt)

**Comment by avikivity** [comment]
Reading/writing a static column makes sense - it allows to have mutual exclusion on the entire partition. Likely this is what @aohotnik is using it for.

**Comment by kostja** [comment]
We do allow reading and writing the static column. The question is whether we consider a row existing or not when WHERE clause restricts the non-existing clustering key.
The way to access the static cell (in all cases) is to restrict the partition key.

**Comment by nyh** [comment]
> We do allow reading and writing the static column. The question is whether we consider a row existing or not when WHERE clause restricts the non-existing clustering key. The way to access the static cell (in all cases) is to restrict the partition key.

But @kostja, the syntax of causing an UPDATE to **write** to a specific row is to specify the clustering key in the WHERE. So you don't have the luxury of putting only the partition key in the WHERE, if the goal of your update is to write to a row depending on the value of a static column.
