### ISSUE TITLE
Column family loading is fragile

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1008]
Currently we scan the directory, filter directories against column families that exist, and make directories when they don't exist.

It would be a lot simpler to iterate over column families and check/create directories for them.

**Comment by slivne** [comment]
@avikivity is there a case in which the current schem fails

I am in favor of making things simple yet need to understand if this is
causing us to miss items / crash - in which case this is a showstopper if
not we will defer it to 1.1

**Comment by avikivity** [comment]
Definitely not for 1.0.

**Comment by penberg** [comment]
Isn't this what commit https://github.com/scylladb/scylla/commit/8260b8fc6f11390c4fa391b404cc1599bae6dbb3 does?

@glommer

**Comment by glommer** [comment]
Yes it is.

**Comment by penberg** [comment]
@avikivity Please close.

**Comment by tgrabiec** [comment]
@penberg I think 8260b8f doesn't do what @avikivity suggests. That commit adds directory touching, but this issue is about getting rid of directory scanning.

**Comment by avikivity** [comment]
@tgrabiec correct.

**Comment by haaawk** [comment]
Is this what you have in mind Avi?
https://github.com/haaawk/scylla/commit/aaa19a775c8d0c9fde1ff8a34c67e7d7d9560b19?diff=unified

**Comment by avikivity** [comment]
@haaawk yes, but please post patches to the list for open review.

**Comment by haaawk** [comment]
Sure. I just wanted to double check and it was easier to paste a link.
