### ISSUE TITLE
Bad write amplification while Cleanup Compaction is running

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#10097]
Problem statement
-----------------

When cleanup is executed, it marks all files being cleaned up as compacting,
then for each file:
    1) it will perform a single-file compaction removing the non-owned parts
    2) replace that input file with the output one in the sstable set

The problem with making output files available one at a time is that regular
compaction efficiency decreases because it may end up compacting fewer files
than it would otherwise.

That can be easily seen with tiered strategy (includes ICS), where there are
file stored across multiple tiers. As cleanup produces output files (one at a
time) and new files are flushed, regular compaction will only be able to
include those that cleanup finished rewriting. As more files become available,
regular compaction may have to perform another round. That increases write
amplification because the same data may be recompacted more times.

This also affects leveled strategy because it's fooled into thinking that the
layout goal is far from being reached. So it may start compacting more
aggressively to make sure that levels are balanced.

***
As cleanup fights for resources with regular compaction, the increased write
amplification is bad for everybody. Write throughput is decreased, cleanup
operation time becomes higher, and consequently elasticity is reduced.
***

Proposed solution
-----------------

As described above, the problem happens because output files are made available
incrementally. That's probably in an attempt to make the space requirement
the size of the largest file. But, the problem can be fixed by replacing the
input by output incrementally (as-is today), but only making them available
to regular in a criteria according to the compaction strategy used.

The compaction strategy will drive the "cleanup groups", where each cleanup
group will still have files cleaned up separately, as-is today, but all files
in a cleanup group will be available for regular compaction at once.

For LCS, a cleanup group is a level L.
For STCS and ICS, a group is a tier T.
For TWCS, a group is a window W.

We'll start with the smallest window/tier/level/whatever, to increase chances
of cleaning up success once it reaches biggest files.

With LCS for example, we'll start cleaning up the first group, which may be
level 0, and once clean up is done rewriting that level, one file at a time,
then all files in that group is made available for regular.

It may also be interesting to restrict LCS to tiered mode while clean up is
running. So LCS' terrible WA won't affect elasticity of its users.

**Comment by bhalevy** [comment]
Super, thanks!

**Comment by bhalevy** [comment]
To summarize a verbal discussion: we agreed that a good strategy to take will be to move cleanup away from using `rewrite_sstables` that compacts sstables one at a time towards a compaction type derived from regular compaction, driven by `compact_sstables`.  That will allow it to be bucket aware and do the cleanup in bucket order (smallest to largest), replacing the sstables in a batch after each bucket is done.

**Comment by avikivity** [comment]
Performance only, not backporting.
