### ISSUE TITLE
Possible bug with prepared statements interaction with ALTER TYPE

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10095]
This is a Gedankenbug - based on thinking about a certain scenario during a chat with @eliransin on an actual user bug that may or may not be related to the following analysis. I have not reproduced it yet.

Consider that you have a table with a UDT column, one server node (for simplicity) S, and two clients - C1 and C2 - who use the same CQL statement that updates this UDT column. Both clients C1 and C2 will **prepare** this statement on this node and will then use the prepared statement repeatedly.

As explained in https://cassandra.apache.org/_/native_protocol.html section 4.2.5.4 (Messages/Responses/Result/Prepared), as each client prepares the statement, each gets a short `id`, and additionally `metadata` which tells the client exactly which parameters (bind variables) it will have to supply each time it executes this prepared statement. (by the way, we can have a similar discussion on selects and `result_metadata`, instead of updates and bind variables).

The theorized bug depends on the fact that Scylla chooses the prepared-statement `id`  based exclusively on the **statement's text**. In particular both clients C1 and C2 will get back the same id (and also the same metadata) when preparing this statement.

At this point, imagine that we invoke an ALTER TYPE to change the UDT (e.g., add another field to the UDT). The server will rightly _invalidate_ the prepared statements that use this UDT.

Now, C1 who is blissfully unaware of this change will try to execute the prepared statement with the saved id `id`. Because the server S had already invalidated it, it won't find it, so it will ask C1 to re-prepare the statement, and C1 will do exactly that. Because the statement's text has not changed, C1 will received the **same `id`** for the prepared statement. The `metadata` will be different, though - the UDT now has one additional field, so the client needs to supply it in the bind variable.

Now, C2 wakes up and also sends a prepared statement with the saved id `id`. Because this is exactly the same `id` that C1 used before and after the type change, the server will **not** say this prepared statement is missing - it isn't, it was just recreated during C1's request! So the server will be happy to oblige running the prepared statement... But C2 was using the wrong (older) metadata, so will be be missing some of the data in the execution - and the theory is that this execution will fail in a weird way.

If this theory is correct, the client C2 will never recover from this error. Even a server reboot may or may not be enough, depending if C2 notices it and drops its prepared statements, and depending on who tries to prepare the statement again.

If this is a real bug, I think a solution can be to include in the prepared statement id calculation not just the text of the statement, but also a hash of the `metadata` (or just the definition of UDTs listed in it). While at it, we also need to include the `result_metadata`  in this hash calculation - before of the SELECT-side variant of this bug (this is a known, and fixed, bug in Cassandra: https://issues.apache.org/jira/browse/CASSANDRA-10786).

**Comment by tgrabiec** [comment]
I think it's fine that C2 sends a value which conforms to the older schema (i.e. sends fewer fields). Old values can always be read using newer schema, so the server can interpret such a value correctly. That's what happens when you read old sstables, or process requests which are concurrent with the alter (there is no global barrier which stops old requests).

**Comment by nyh** [comment]
But unless I'm missing something, C2 doesn't tell the server it is using an older schema - it's just when it writes out the list of bound variable values, one will be missing, and the server will be confused when it tries to read. I think this is why the "metadata" thing exists in the prepared statements in the first place - it tells the client which variables it needs to fill, regardless of what it thinks the schema is.

Again, I'm not sure this is a real bug. I'll try to reproduce it later and see how things behave in practice (it should be easy to reproduce because it doesn't depend on accurate timings and just one server node is enough).

**Comment by nyh** [comment]
> At least it applies for `SELECT *` (which is a bad idea for non-interactive use). Perhaps we should hash the schema into the prepared statement.

I opened a separate issue about that - #10096.
This issue was supposed to be about bind variables, not the result. I agree they are similar issues though.

**Comment by nyh** [comment]
Unfortunately (or fortunately?) I can't reproduce any problem here...
It seems C2 continues to send the old UDT defintion, which has one less component, and the server simply accepts it, and just writes a null in the extra component that C2 didn't send.
I can't reproduce any strange error or anything which appears incorrect.
I'm not sure my test is correct, though, because I use the Python driver which is a bit too high-level to understand exactly what it does regarding prepared-statement ids and reprepares.

Unless I come up with more ideas soon, I'll have to close this issue as a not-a-bug...

**Comment by nyh** [comment]
I'm closing this issue as can't prove it really exists...
