### ISSUE TITLE
Backup/Restore/Snapshot

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#101]
http://docs.datastax.com/en/cassandra/2.1/cassandra/operations/ops_backup_restore_c.html

**Comment by tzach** [comment]
@slivne I believe we can can close this

**Comment by slivne** [comment]
incremental backups are not avilable

**Comment by yanana** [comment]
Is there any update on the issue?

**Comment by tzach** [comment]
Closing this issue, as backup and restore are working for some time now.
A new issue to capture inc backup #1582
