### ISSUE TITLE
Add metrics that shows live and unrachable nodes

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#10102]
It will be useful to be able to tell what is the status that each node sees, for example, in a split-brain situation
each node will only see part of the cluster nodes, even thogh the monitoring for example will be able to see all the nodes.

It could be expensive to report each of the possible node-to-node connetion as it's quadratice in nature.
Instead, each node would report only the number of live and unreachable nodes.
This can be reported once per node (not per shard) and can be added easility to the gossiper.

**Comment by avikivity** [comment]
Not a bug, not backporting.
