### ISSUE TITLE
compaction_manager tasks cannot be stopped while sleeping for retry.

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10112]
[As of 8eb5d6ed31fac0a7c90600011b44858394acd260, ](https://github.com/scylladb/scylla/blob/8eb5d6ed31fac0a7c90600011b44858394acd260/compaction/compaction_manager.cc#L624-L628)

calls the non-abortable version of `exponential_backoff_retry`.

Instead, it should use https://github.com/scylladb/scylla/blob/8eb5d6ed31fac0a7c90600011b44858394acd260/utils/exponential_backoff_retry.hh#L30
with an `abort_source` (I believe we can put it in compaction_data) to be used in https://github.com/scylladb/scylla/blob/8eb5d6ed31fac0a7c90600011b44858394acd260/compaction/compaction_manager.cc#L394

**Comment by bhalevy** [comment]
This issue is manifested when scrub stops ongoing compactions.
If there are in an infinite retry loop, as in #9983, scrub may wait for a very long time until the retry sleep wakes up and the task finds out it's stopped.

**Comment by avikivity** [comment]
Relatively minor, not backporting/
