### ISSUE TITLE
Wrong validation of blobs in INSERT JSON

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylla#10114]
Scylla version (or git commit hash): f292d3d679e4f4715c437a976f585a7e3043b20b

When inserting into a `blob` column with `INSERT JSON` statement, the value of a blob is supposed to be a string starting with `0x`. However, the current validation is incorrect in some cases:

```
CREATE TABLE t(pk int primary key, v blob);
INSERT INTO t JSON '{"pk": 1, "v": "1234"}';
cqlsh:ks> SELECT * FROM t;

 pk | v
----+------
  1 | 0x34

(1 rows)
```

which results in adding a shorter blob, instead of an error (which works by accident in this case):
```
cqlsh:ks> INSERT INTO t JSON '{"pk": 1, "v": ""}';
ServerError: marshaling error: Blob JSON strings must start with 0x
```

**Comment by avikivity** [comment]
Backported to 5.0 (5.1 has it).
