### ISSUE TITLE
[AMI 0.18] Scylla dumps core on short run of CorruptThenRepairMonkey

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#1012]
I ended up hitting this while developing a new feature of the cluster test suite. After less than an hour of a CorruptThenRepairMonkey nemesis running, scylla dumped core.

Scylla package versions:

    scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
    scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
    scylla-boost-system-1.58.0-11.el7.centos.x86_64
    scylla-boost-test-1.58.0-11.el7.centos.x86_64
    scylla-boost-thread-1.58.0-11.el7.centos.x86_64
    scylla-env-1.0-1.el7.centos.noarch
    scylla-gdb-7.10.1-30.el7.centos.x86_64
    scylla-jmx-0.18-20160216.4b88457.el7.centos.noarch
    scylla-server-0.18-20160216.b532919.el7.centos.x86_64
    scylla-server-debuginfo-0.18-20160216.b532919.el7.centos.x86_64
    scylla-tools-0.17-20160216.afadea3.el7.centos.noarch

Where the core dump is stored:

http://scylladb-users-upload.s3.amazonaws.com/core.scylla.994.45417023a16144ccaa809055e945503e.2670.1457472115000000/core.scylla.994.45417023a16144ccaa809055e945503e.2670.1457472115000000.xz

What the nemesis does
---------------------

1. Destroy user data by running the script

    #!/bin/bash

    DELETE_COUNT=5

    ls /var/lib/scylla|sort -R |tail -$DELETE_COUNT |while read file; do
        rm -rf $file
    done

in one of the nodes

2. Run

    sudo pkill -9 scylla

On that same node.

3. Wait until DB services are down (Port 9042 not occupied)

4. Due to a scylla bug, we are restarting the scylla service in the test itself

    sudo systemctl restart scylla-server.service

5. Wait until DB services are up (Port 9042 occupied)

6. Run the following nodetool command in the target node:

    nodetool -h localhost repair

**Comment by slivne** [comment]
@lmr can you please extract a backtrace maybe its a known issue

**Comment by lmr** [comment]
I think we are doing something wrong with the AMI setup, for I couldn't actually get a backtrace using our custom scylla GDB version:

    $ /opt/scylladb/bin/gdb --core core.scylla.994.45417023a16144ccaa809055e945503e.2670.1457472115000000 
    GNU gdb (GDB) Red Hat Enterprise Linux 7.10.1-30.el7.centos
    Copyright (C) 2015 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-redhat-linux-gnu".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
    For help, type "help".
    Type "apropos word" to search for commands related to "word".
    [New LWP 2670]
    [New LWP 2673]
    [New LWP 2674]
    Reading symbols from /usr/bin/scylla...Reading symbols from /usr/lib/debug/usr/bin/scylla.debug...../../gdb/cp-support.c:1595: demangler-warning: unable to demangle '_ZN8futurizeI13frozen_schemaE5applyIRZN7seastar7shardedIN7service13storage_proxyEE9invoke_onIZZNS6_22init_messaging_serviceEvENKUljN5utils4UUIDEE8_clEjSA_EUlOT_E_6futureIJS0_EEEET0_jSD_EUlvE_JEEESG_SD_DpOT0_' (demangler failed with signal 11)
    Unable to dump core, use `ulimit -c unlimited' before executing GDB next time.
    ../../gdb/cp-support.c:1608: demangler-warning: unable to demangle '_ZN8futurizeI13frozen_schemaE5applyIRZN7seastar7shardedIN7service13storage_proxyEE9invoke_onIZZNS6_22init_messaging_serviceEvENKUljN5utils4UUIDEE8_clEjSA_EUlOT_E_6futureIJS0_EEEET0_jSD_EUlvE_JEEESG_SD_DpOT0_' (demangler failed with signal 11)
    A problem internal to GDB has been detected,
    further debugging may prove unreliable.

**Comment by gleb-cloudius** [comment]
On Thu, Mar 10, 2016 at 05:45:56AM -0800, Lucas Meneghel Rodrigues wrote:
> I think we are doing something wrong with the AMI setup, for I couldn't actually get a backtrace using our custom scylla GDB version:
> 
Just press 'n' when it asks you if you want to exit.

>     $ /opt/scylladb/bin/gdb --core core.scylla.994.45417023a16144ccaa809055e945503e.2670.1457472115000000 
>     GNU gdb (GDB) Red Hat Enterprise Linux 7.10.1-30.el7.centos
>     Copyright (C) 2015 Free Software Foundation, Inc.
>     License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
>     This is free software: you are free to change and redistribute it.
>     There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
>     and "show warranty" for details.
>     This GDB was configured as "x86_64-redhat-linux-gnu".
>     Type "show configuration" for configuration details.
>     For bug reporting instructions, please see:
>     <http://www.gnu.org/software/gdb/bugs/>.
>     Find the GDB manual and other documentation resources online at:
>     <http://www.gnu.org/software/gdb/documentation/>.
>     For help, type "help".
>     Type "apropos word" to search for commands related to "word".
>     [New LWP 2670]
>     [New LWP 2673]
>     [New LWP 2674]
>     Reading symbols from /usr/bin/scylla...Reading symbols from /usr/lib/debug/usr/bin/scylla.debug...../../gdb/cp-support.c:1595: demangler-warning: unable to demangle '_ZN8futurizeI13frozen_schemaE5applyIRZN7seastar7shardedIN7service13storage_proxyEE9invoke_onIZZNS6_22init_messaging_serviceEvENKUljN5utils4UUIDEE8_clEjSA_EUlOT_E_6futureIJS0_EEEET0_jSD_EUlvE_JEEESG_SD_DpOT0_' (demangler failed with signal 11)
>     Unable to dump core, use `ulimit -c unlimited' before executing GDB next time.
>     ../../gdb/cp-support.c:1608: demangler-warning: unable to demangle '_ZN8futurizeI13frozen_schemaE5applyIRZN7seastar7shardedIN7service13storage_proxyEE9invoke_onIZZNS6_22init_messaging_serviceEvENKUljN5utils4UUIDEE8_clEjSA_EUlOT_E_6futureIJS0_EEEET0_jSD_EUlvE_JEEESG_SD_DpOT0_' (demangler failed with signal 11)
>     A problem internal to GDB has been detected,
>     further debugging may prove unreliable.
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/scylladb/scylla/issues/1012#issuecomment-194845569

--
			Gleb.

**Comment by lmr** [comment]
What's worse, `sudo coredumpctl info`  shows no core dump.

**Comment by lmr** [comment]
@gleb-cloudius, I just tried it, it hangs and I don't get any output anymore.

**Comment by gleb-cloudius** [comment]
On Thu, Mar 10, 2016 at 05:47:19AM -0800, Lucas Meneghel Rodrigues wrote:
> What's worse, `sudo coredumpctl info`  shows no core dump.
> 
We disable systemd coredump handling IIRC, so this is normal.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Thu, Mar 10, 2016 at 05:47:55AM -0800, Lucas Meneghel Rodrigues wrote:
> @gleb-cloudius, I just tried it, it hangs and I don't get any output anymore.
> 
That's something new.

--
			Gleb.

**Comment by tgrabiec** [comment]
@lmr Maybe it's just slow, how long did you wait? On my system it takes gdb a while to read scylla object with debug symbols.

**Comment by lmr** [comment]
I can't reproduce this on the latest 1.0-rc1 AMI, so I'm closing this.
