### ISSUE TITLE
forward_service: retry a failed forwarder call

### ISSUE THREAD

**Issue by havaker** [scylladb/scylla#10131]
`forward_service` is a service that coordinates execution of `count(*)` queries. It does so by:

-  splitting given query into smaller sub-queries
-  forwarding so created sub-queries to a group of chosen coordinators (in a parallel fashion)

In case of failed forwarding, whole `count(*)` query fails, leaving the user with an error. Even though forwarding is only done to coordinators that are marked as alive, an unexpected failure may occur because of e.g. link failure or gossiper reacting slowly (as in #10083 ).

Failing whole `count(*)` query could be prevented by implementing retries in a `forward_service` coordination layer - resending sub-queries to another vnodes owner.

**Comment by avikivity** [comment]
Not a regression (and count(*) is vulnerable to transient failures regardless), not backporting.
