### ISSUE TITLE
compare_atomic_cell_for_merge doesn't compare tll if expiry is the same

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10156]
Unlike `atomic_cell_or_collection::equals`, compare_atomic_cell_for_merge will return `std::strong_ordering::equal` if two cells are equal in every way except their ttl:s.

This is the current expectation of this unit test as of b1e45e440140215576ed58d0e0ef28e2a510e09f
https://github.com/scylladb/scylla/blob/c9e06f1246cceaedfc16454cd6a97e2f7c200a74/test/boost/mutation_test.cc#L713-L716

The problem with that is that the cells' hashes are different and this will cause repair to keep trying to repair discrepancies caused by the ttl being different.

This may be triggered by e.g. the spark migrator that computes the ttl based on the expiry time by subtracting the expiry time from the current time to produce a respective ttl.

If the call is migrated multiple times at different times, it will generate cells that the same expiry (by design) but have different ttl values.

**Comment by avikivity** [comment]
Backported to 4.5, 4.6, 5.0.
