### ISSUE TITLE
dist:ubuntu warnings + stdout are not written to syslog they are written to /var/log/upstart/scylla-server.log

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1015]
on 0.18 / 0.18.1

**Comment by syuu1228** [comment]
This is correct behavior on Ubuntu + Upstart environment, just like we have to use journalctl instead of /var/log/messages on Fedora/CentOS.
Even we changed the configuration, users may try to find log in /var/log/upstart/<service name>.log and never realize we actually change it.
So I don't think this is bug.

**Comment by slivne** [comment]
Well its strange

we are writing some items to syslog and some items to upstart

Could it be that we have stderr setup incorrectly to write to upstart
instead of syslog ?

**Comment by syuu1228** [comment]
We can see syslog output on /var/log/syslog with latest master, this can be close.
#1094 can be close too.

**Comment by slivne** [comment]
@syuu1228 
is this fixed ?
can you provide a reference to the code fix ?

**Comment by syuu1228** [comment]
@slivne At least init script never changed for this. I'm bit wondering we really couldn't get syslog on 0.18, but if really not, probably there was bug on logging framework or init script, and it's fixed at some point.

I compared init script between master vs branch-0.18, there's no difference around logging settings.

**Comment by tzach** [comment]
@slivne @syuu1228 is this issue still relevant?

**Comment by syuu1228** [comment]
I clould not reproduce this at least on two month ago, and it is only on
14.04, not happens on 16.04.

**Comment by slivne** [comment]
we are writing to upstart/scylla-server.log and to syslog (different logs) - @syuu1228  - there is no workaround for this ? 

I got used to this (e.g. check both for anything) - not sure all users will

**Comment by avikivity** [comment]
seastar now supports the logger, so we can convert seastar prints to logs.

**Comment by tzach** [comment]
> seastar now supports the logger, so we can convert seastar prints to logs.

@syuu1228 can you use addition to fix the issue?

**Comment by syuu1228** [comment]
Okay, just for Ubuntu 14.04 is enough?

2016年7月10日日曜日、Tzach Livyatan<notifications@github.com>さんは書きました:

**Comment by tzach** [comment]
@syuu1228 yes, as far as I know this issue is only relevant for Ubuntu 14.04

**Comment by syuu1228** [comment]
Avi, I think you are talking about register_logger that accept custom
logger class, but should we re-implement logger that outputs log message to
file, by copying existing one that outputs to stdout?
It will be duplication of the code.

**Comment by avikivity** [comment]
No, the `logger` class was moved from Scylla to seastar, so now we can convert all `print()` and `fprint()` calls in seastar to calls to the logger.

**Comment by tzach** [comment]
@syuu1228 is this issue still valid?

**Comment by tzach** [comment]
@slivne I suggest closing this issue. No point investing in Ubuntu 14 logs at this point.

**Comment by tzach** [comment]
closing this issue, as it is limited to Ubuntu 14 and not critical for Scylla operation.
