### ISSUE TITLE
AMI 0.18: Streaming errors on short cassandra-stress runs (small node size)

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#1016]
While waiting for 0.19 AMIs to become available, I was finishing up some new testcase features. As I re-ran some of our nemesis code using very short c-s runs (15 minutes), I found the sequence of errors that follows. Some important info:

1) The nemesis is CorruptThenRepairMonkey (more on what it does later).
2) 6 nodes t2.micro (I know it's not the recommended size, I'm posting this in case people consider remotely useful understanding what's going on).

Cassandra-stress starts to output values around 15:27:45. At 15:28:44, after destroying user data and re-starting scylla on the target node, we request a nodetool repair:

    15:28:44 DEBUG| Remote [centos@54.183.157.12]: Running 'nodetool -h localhost repair'

After about 10 seconds, we can see the streaming messages popping out:

    15:28:53 DEBUG| [54.183.157.12] [stdout] Mar 09 18:28:53 ip-172-31-19-66 scylla[2607]:  [shard 0] repair - starting user-requested repair for keyspace keyspace1, repair id 1, options {incremental=false, parallelism=0, primaryRange=false}

About 20 seconds later, we start seeing error messages from the repair:

    15:29:14 DEBUG| [54.183.157.12] [stdout] Mar 09 18:29:14 ip-172-31-19-66 scylla[2607]:  [shard 0] storage_proxy - exception during mutation write to 172.31.19.66: std::bad_alloc (std::bad_alloc)
    15:29:14 DEBUG| [54.183.157.12] [stdout] Mar 09 18:29:14 ip-172-31-19-66 scylla[2607]:  [shard 0] storage_proxy - MUTATION verb handler: std::bad_alloc (std::bad_alloc)
    15:29:14 DEBUG| [54.183.157.12] [stdout] Mar 09 18:29:14 ip-172-31-19-66 scylla[2607]:  [shard 0] storage_proxy - exception during mutation write to 172.31.19.66: std::bad_alloc (std::bad_alloc)
    15:29:14 DEBUG| [54.183.157.12] [stdout] Mar 09 18:29:14 ip-172-31-19-66 scylla[2607]:  [shard 0] storage_proxy - MUTATION verb handler: std::bad_alloc (std::bad_alloc)
    15:29:14 DEBUG| [54.183.157.12] [stdout] Mar 09 18:29:14 ip-172-31-19-66 scylla[2607]:  [shard 0] storage_proxy - exception during mutation write to 172.31.19.66: std::bad_alloc (std::bad_alloc)
    15:29:14 DEBUG| [54.183.157.12] [stdout] Mar 09 18:29:14 ip-172-31-19-66 scylla[2607]:  [shard 0] stream_session - [Stream #c7662740-e624-11e5-9e66-000000000000] stream_transfer_task: Fail to send outgoing_file_message to 172.31.19.67:0: std::bad_alloc (std::bad_alloc)
    15:29:14 DEBUG| [54.183.157.12] [stdout] Mar 09 18:29:14 ip-172-31-19-66 scylla[2607]:  [shard 0] stream_session - [Stream #c7662740-e624-11e5-9e66-000000000000] Streaming error occurred
    15:29:14 DEBUG| [54.183.157.12] [stdout] Mar 09 18:29:14 ip-172-31-19-66 scylla[2607]:  [shard 0] stream_session - [Stream #c7662740-e624-11e5-9e66-000000000000] Session with 172.31.19.67 is complete, state=FAILED

We keep on seeing failures like this one, until the repair command finally finishes:

    15:39:45 ERROR| sdcm.nemesis.CorruptThenRepairMonkey: nodetool command 'nodetool -h localhost repair' failed on node Node lmr-scylla-db-node-173711d7-4 [54.183.157.12 | 172.31.19.66] (seed: False): Command: /bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-master6wi3Rv/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpumKYKc -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/lmr-longevity-test-00a16d88.pem 54.183.157.12 "nodetool -h localhost repair"
    Exit status: 2
    Duration: 660.332917929
    Stdout:
    [2016-03-09 18:28:53,595] Starting repair command #1, repairing 1 ranges for keyspace keyspace1 (parallelism=SEQUENTIAL, full=true)
    [2016-03-09 18:39:44,747] Repair session 1 failed
    [2016-03-09 18:39:44,756] Repair session 1 finished
    [2016-03-09 18:39:44,872] Starting repair command #2, repairing 1 ranges for keyspace system (parallelism=SEQUENTIAL, full=true)
    [2016-03-09 18:39:44,977] Repair session 2 finished

    Stderr:
    error: nodetool failed, check server logs
    -- StackTrace --
    java.lang.RuntimeException: nodetool failed, check server logs
	    at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:290)
	    at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:202)
	
That's the issue description as I found it. Below you'll find the nemesis action description.

Corrupt then rebuild monkey
===========================

What the nemesis does
---------------------

1. Destroy user data by running the script

    #!/bin/bash

    DELETE_COUNT=5

    ls /var/lib/scylla|sort -R |tail -$DELETE_COUNT |while read file; do
        rm -rf $file
    done

in one of the nodes

2. Run

    sudo pkill -9 scylla

On that same node.

3. Wait until DB services are down (Port 9042 not occupied)

4. Due to a scylla bug, we are restarting the scylla service in the test itself

    sudo systemctl restart scylla-server.service

5. Wait until DB services are up (Port 9042 occupied)

6. Run the following nodetool command in the target node:

    nodetool -h localhost repair

**Comment by asias** [comment]
it is t2.micro. it looks like a low on memory issue.

**Comment by slivne** [comment]
lets retest this when glaibers code  related to repair is merged

**Comment by lmr** [comment]
This issue does not reproduce under the latest 1.0-rc1 to date (ami-c25e51a8), I'm closing this bug.
