### ISSUE TITLE
Scrub (skip and segregate modes) can extend range tombstone changes, deleting data

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#10168]
Scrub doesn't close active range tombstones when splitting partitions around ooo fragments, or when skipping the rest of a bad partition, therefore extending any active range tombstone to the end of the stream and making the stream invalid at the same time.
Found by code inspection.

**Comment by denesb** [comment]
Affected: master and possibly 5.0

**Comment by denesb** [comment]
The situation is worse than I initially thought. Consider mode=segregate and a partition with reordered fragments such as this:
`cr{0}, rtc{before(1), t=1}, cr{1}, cr{3}, cr{4}, cr{5}, cr{2}, rtc{after(2), t=null}`

If you order the fragments, you can see that the range tombstone covers the range: `[1, 2]`. But with the segregate algorithm works by injecting a partition start and end at the first ooo fragment, so we'd get the following two partitions:
`cr{0}, rtc{before(1), t=1}, cr{1}, cr{3}, cr{4}, cr{5}`
`cr{2}, rtc{after(2), t=null}`

The problem is that the v2 format mandates partition range tombstones to be closed when the partition ends. So at ck 5 we need to end the currently active range tombstone. But if we inject a range tombstone change `rtc{after(5), t=null}` to this effect, we extend the range tombstone beyond its original range, deleting additional data.

The solution I see is that scrub accumulates all range tombstone changes in memory when reading a partition and writes them into a separate partition (with the same key of course). This also means mode=skip can't possibly work anymore, unless we similarly extract all range tombstone changes to the side.

**Comment by denesb** [comment]
CC @bhalevy

**Comment by bhalevy** [comment]
@denesb I don't think we can fix any random permutation of rows and ranges tombstones in a lossless way.

> The solution I see is that scrub accumulates all range tombstone changes in memory when reading a partition and writes them into a separate partition (with the same key of course). This also means mode=skip can't possibly work anymore, unless we similarly extract all range tombstone changes to the side.

Even if we do that, theoretically with *random* corruption the range tombstone changes could be mis-ordered or there could be missing start or end change.

I think we could implement skip by truncating the sstable (and the writer state) back to the last known-to-be-good offset.
We could then skip partitions that are corrupt in a non-repairable way.

**Comment by denesb** [comment]
> @denesb I don't think we can fix any random permutation of rows and ranges tombstones in a lossless way.
> 
> > The solution I see is that scrub accumulates all range tombstone changes in memory when reading a partition and writes them into a separate partition (with the same key of course). This also means mode=skip can't possibly work anymore, unless we similarly extract all range tombstone changes to the side.
> 
> Even if we do that, theoretically with _random_ corruption the range tombstone changes could be mis-ordered or there could be missing start or end change.
> 
> I think we could implement skip by truncating the sstable (and the writer state) back to the last known-to-be-good offset. We could then skip partitions that are corrupt in a non-repairable way.

Scrub doesn't and cannot fix random corruptions. Segregate mode fixes reordered fragments and the invariant is that fragments weren't lost. This is why scrub cannot be run blindly: the sstables have to be examined first do find the nature of the corruption and to confirm that scrub can indeed help.
With this in mind, the above method could work for sstables containing reordered fragments.
As for random corruption and arbitrary amount of missing fragments: I think there is no solution, such sstables have to be dropped entirely. There is no way to determine what is the "last good state". But this is another discussion.

**Comment by bhalevy** [comment]
I'm afraid that the example above is unrealistic.
Have we seen fragments shuffled this way?
I don't think it's a good idea to over-complicate scrub for scenarios we cannot even explain.

**Comment by denesb** [comment]
I have only seen such examples in testing, after adding range tombstones to the test data. In our real-world experience so far we haven't seen something like that yet. But that is only because the tables we've worked with didn't have range tombstones. But what says that all tables are like that? Range tombstones are not very rare. At the very least we should abort scrub on seeing the first range tombstone, regardless of mode. The current code just doesn't handle them.

**Comment by bhalevy** [comment]
The out-of-order rows we've encountered were the result of missing partition-end on sstables that were sealed prematurely or due to out-of-order partitions.  I believe that in all cases the resulting partition had partial runs of ordered clustering rows, which scrub can segregate into separate partitions.

> At the very least we should abort scrub on seeing the first range tombstone, regardless of mode. The current code just doesn't handle them.

Doing this to coarsely will disable scrubbing in many valid cases as well.
How about aborting scrub (in segregate mode) if it encounters the end of the partition or out-of-order row with an open range tombstone?
Why not trust a properly closed range tombstone?

**Comment by denesb** [comment]
> The out-of-order rows we've encountered were the result of missing partition-end on sstables that were sealed prematurely or due to out-of-order partitions. I believe that in all cases the resulting partition had partial runs of ordered clustering rows, which scrub can segregate into separate partitions.

The was more broad than that. In the case of the infamous fragment reordering bug, one could get fragments reordered withing a partition, not just across partitions (resulting in out-of-order partitions).
> 
> Doing this to coarsely will disable scrubbing in many valid cases as well. How about aborting scrub (in segregate mode) if it encounters the end of the partition or out-of-order row with an open range tombstone? Why not trust a properly closed range tombstone?

The problem is, there is no way to tell whether a range tombstone was properly closed. You might have seen an out-of-order closing bound, extending the range tombstone's effect substantially. Maybe we can relax the abort condition to seeing the first OOO fragment when there is an active range tombstone change.

**Comment by bhalevy** [comment]
> In the case of the infamous fragment reordering bug, one could get fragments reordered withing a partition, not just across partitions (resulting in out-of-order partitions).

How? repair rpc messages, that were reordered, contain complete `repair_row_on_wire` instances.

@asias, can row level repair corrupt range tombstones in case its rpc messages get reordered?

> Maybe we can relax the abort condition to seeing the first OOO fragment when there is an active range tombstone change.

That's what I meant too.

**Comment by denesb** [comment]
> > In the case of the infamous fragment reordering bug, one could get fragments reordered withing a partition, not just across partitions (resulting in out-of-order partitions).
> 
> How? repair rpc messages, that were reordered, contain complete `repair_row_on_wire` instances.
> 
> @asias, can row level repair corrupt range tombstones in case its rpc messages get reordered?

No, each message contained a single `frozen_mutation_fragment`, with the partition-key attached. If two messages from the same partition are reordered, you get just reordered rows (or range tombstones). If the two messages are from different partitions, you also get out-of-order partitions.
Note that `frozen_mutation_fragment` contains either a row or a range tombstone, so message reordering didn't affect range tombstone bounds. The v1 format was also more resilient against corrupting individual range tombstones when compacting. But with v2, we have to be very careful, as we now store less information in the stream, making it more difficult to sort out the pre-corruption state.

**Comment by avikivity** [comment]
Backported to 5.0. Older releases not affected.
