### ISSUE TITLE
key_view::tri_compare() incorrect when one or both of the keys is empty

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10176]
The method `key_view::tri_compare()` takes two keys, converts them to byte views ("legacy_form") and calls `lexicographical_tri_compare()` on the result. But `lexicographical_tri_compare()` is not passed byte arrays - it is passed begin and end iterators. Taking `v.begin()` for an empty byte array is invalid! `lexicographical_tri_compare()` compares at least the first byte of this invalid position, and the result is more-or-less random.

This bug can be seen after fixing #9375 which allows empty-string partition keys in materialized views. When looking up a partition with an empty-string key, the index code tries to compare the empty key looked up to the empty key stored in the index file, and the result instead of being `equal` ends up (randomly) `gt`, and the partition can't be found.

Besides fixing `key_view::tri_compare()` we should audit the code whether any other code calls `lexicographical_tri_compare()` or `lexicographical_compare()` passing some `v.begin()` without verifying first that v isn't empty. Better yet, following `std::ranges::lexicographical_compare()` we should have a version of these functions taking a **range**, not iterators, with the following conventions: (see https://en.cppreference.com/w/cpp/algorithm/ranges/lexicographical_compare):

* An empty range is lexicographically less than any non-empty range.
* Two empty ranges are lexicographically equal.

**Comment by psarna** [comment]
To be precise, it's illegal to **dereference** a `begin()` on an empty array/vector or any other data structure, but it's absolutely fine to call it. For arrays, vectors and generally all standard containers it's explicitly specified that `begin()` on an empty array is equal to `end()`, which is enough for loops. Did this problem occur in practice? I didn't follow all the referenced issues.

Ref:
https://en.cppreference.com/w/cpp/container/array/begin
https://en.cppreference.com/w/cpp/container/vector/begin
(etc.)

**Comment by nyh** [comment]
Wow, you are absolutely right! Thanks for waking me up ;-) I've been so enamored with the new std::ranges thing that I forgot an empty vector is indeed very much possible to do with begin() and end() and the bug can't be what I though it is. 

So `key_view::tri_compare()` is correct, and the function it calls - lexicographical_tri_compare(), in types.hh, so see that both strings are empty so each first is equal to last, and not do anything. So the bug has to be something else than this,  so I'm closing this issue. 

There still has to be a bug in lexicographical_tri_compare() because my high-level test fails and after hours of debugging I found that it's because lexicographical_tri_compare() returns "gt" for two empty strings - and if I add the special checks for empty strings, it works... Very weird.

**Comment by nyh** [comment]
Opened a new issue #10178 with a C++ unit test showing the low-level bug (I also have my original high-level reproducer in CQL), and will now get to the bottom of it.
