### ISSUE TITLE
sstables::key_view::tri_compare() incorrect when both keys are empty

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10178]
The method `sstables::key_view::tri_compare(const schema& s, partition_key_view other)` fails to return `equal` as expected when given two **empty** keys, and instead returns `less`.

The following unit test reproduces this bug:
```c++
BOOST_AUTO_TEST_CASE(test_empty_key_view_comparison) {
    auto s_ptr = schema_builder("", "")
            .with_column("p", bytes_type, column_kind::partition_key)
            .build();
    const schema& s = *s_ptr;

    sstables::key empty_sstable_key = sstables::key::from_deeply_exploded(s, {data_value(bytes(""))});
    sstables::key_view empty_sstable_key_view = empty_sstable_key;
    partition_key empty_partition_key = partition_key::from_deeply_exploded(s, {data_value(bytes(""))});
    partition_key_view empty_partition_key_view = empty_partition_key;

    BOOST_CHECK_EQUAL(std::strong_ordering::equal,
        empty_sstable_key_view.tri_compare(s, empty_partition_key_view));
```

This bug will cause user-visible bugs after fixing https://github.com/scylladb/scylla/issues/9375 which allows empty-string partition keys in materialized views. When looking up a partition with an empty-string key, the index code tries to compare the empty key looked up to the empty key stored in the index file, and because the result isn't `equal`, the partition can't be found.

Interestingly, while we return incorrect results when comparing two empty keys, we do return the correct results when just one of the keys is empty (the correct result is that the empty key should be less than the non-empty key).

**Comment by nyh** [comment]
The underlying bug is in `legacy_compound_view<>` - when this view is empty, it doesn't return `begin() == end()` as required. Here is a reproducing test:

```c++
    partition_key empty_partition_key = partition_key::from_deeply_exploded(s, {data_value(bytes(""))});
    partition_key_view empty_partition_key_view = empty_partition_key;
    auto lf = empty_partition_key_view.legacy_form(s);
    BOOST_CHECK_EQUAL(0, lf.size());
    BOOST_CHECK(lf.begin() == lf.end());
```

The first check passes (lf is empty) but the second fails (lf.begin() is not the same as lf.end()).

**Comment by avikivity** [comment]
Harmless in existing branches, so not backporting.
