### ISSUE TITLE
Clustering Key with DESC direction cannot be queried by "LIKE" operator

### ISSUE THREAD

**Issue by sarismet** [scylladb/scylla#10183]
I have a table such that 

CREATE TABLE ks.user_table (
    app text,
    date_daily timestamp,
    aid text,
    date timestamp,
    device text,
    event text,
    event_name text,
    PRIMARY KEY ((app_id, date_daily), aid, date)
) WITH CLUSTERING ORDER BY (aid DESC, date DESC);

When I run a query "select * from ks.user_table where app_id = 'app1' and date_daily='2022-03-03' and aid LIKE '%'"; I responses that InvalidRequest: Error from server: code=2200 [Invalid query] message="LIKE is allowed only on string types, which aid is not". @psarna  said that "it's because of DESC - Scylla incorrectly assumes that a string column with reversed order is also a string". When we changed the direction of aid to ASC, the problem vanished.

**Comment by avikivity** [comment]
Backported to 4.6, 5.0.
