### ISSUE TITLE
Scylla 0.19 iotune take a long time and than crash

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1019]
Running 0.91 AMI on t2.micro iotune runs for a long time, than crash

```
$ sudo coredumpctl info 1894 
           PID: 1894 (iotune)
           UID: 0 (root)
           GID: 0 (root)
        Signal: 6 (ABRT)
     Timestamp: Thu 2016-03-10 15:31:07 UTC (8min ago)
  Command Line: iotune --evaluation-directory /var/lib/scylla --format envfile --options-file /etc/scylla.d/io.conf
    Executable: /usr/bin/iotune
 Control Group: /system.slice/scylla-io-setup.service
          Unit: scylla-io-setup.service
         Slice: system.slice
       Boot ID: 3d1ecd5cb08645fbba1562edd6002233
    Machine ID: 8ea3e6ea03b64d018847fcdf669935d4
      Hostname: ip-172-31-0-91
       Message: Process 1894 (iotune) of user 0 dumped core.
```

**Comment by slivne** [comment]
ami ami-f90a0e93

**Comment by lmr** [comment]
It's a known issue, and the fix by @glommer didn't make into 0.19, as @slivne mentioned.

**Comment by lmr** [comment]
https://github.com/scylladb/scylla/issues/986. After re-visiting the issue, I'm not so sure @glommer's patches were actually merged onto master.

**Comment by lmr** [comment]
nitpick: 'runs for a long time, then crashes'.

**Comment by tzach** [comment]
> Didn't we decide to preload the iotune results on the difference EC2
instances?

If we can, we should. The long boot time, even if it works, is bad UX

**Comment by tzach** [comment]
The reason might be iotune require 10GB to run
We need to either relax that for smaller storage machines.
@avikivity @glommer , thoughts?

**Comment by glommer** [comment]
@avikivity claims that smaller files may lead us to be tricked by disk caches.

But I do believe we can run smaller files.

**Comment by slivne** [comment]
@lmr please retest with new ami (post 0.19 - I should have one tomorrow)

**Comment by slivne** [comment]
ami scylla_2016-03-16T08-25-42Z (ami-8d4343e7)) - based on scylla-server-666.development-20160315.e228ef1.el7.centos.x86_64 does not have the fix for io_tune to abort on low disk it should be in the next one

in any case it dependns on fixing #1047

**Comment by tzach** [comment]
1.0 works fine on t2.micro, so the original problem is not relevant anymore
iotune may crash on other setups, we will open a new case once it does.
