### ISSUE TITLE
Scylla may pick existing SSTable generation for SSTable being moved from staging dir

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#10198]
Scylla optimistically assumes that main directory isn't using the generation used by one of the SSTables in the staging directory.

Then when moving SSTables from staging into main dir, the procedure will fail with:

`2022-03-08T08:48:03+00:00 stop-compaction-ls-db-node-2f2c651b-1 ! WARNING |  [shard 0] view_update_generator - Moving some sstable from staging failed: sstables::malformed_sstable_exception (Error while linking SSTable: /var/lib/scylla/data/keyspace1/standard1-cf7a42b09eb811ec851306c1a00cfe0b/staging/md-82-big-TOC.txt to /var/lib/scylla/data/keyspace1/standard1-cf7a42b09eb811ec851306c1a00cfe0b/md-82-big-TOC.txt: File exists in sstable /var/lib/scylla/data/keyspace1/standard1-cf7a42b09eb811ec851306c1a00cfe0b/staging). Ignoring...`

In the test ran by @soyacz:
1) generation 82 was picked for SSTable in staging dir.
2) Node restarted, reshape ran on behalf of main dir only. Staging had reshape aborted.
3) Main dir created a new file with generation 82
4) View update completes, tries to move file with gen 82 to main dir and fails.

**Comment by raphaelsc** [comment]
We could patch table::move_sstables_from_staging() as follow:

```
diff --git a/replica/table.cc b/replica/table.cc
index 3213f267a9..9bf4806098 100644
--- a/replica/table.cc
+++ b/replica/table.cc
@@ -2342,7 +2342,7 @@ future<> table::move_sstables_from_staging(std::vector<sstables::shared_sstable>
     for (auto sst : sstables) {
         dirs_to_sync.emplace(sst->get_dir());
         try {
-            co_await sst->move_to_new_dir(dir(), sst->generation(), false);
+            co_await sst->move_to_new_dir(dir(), calculate_generation_for_new_table(), false);
             _sstables_staging.erase(sst->generation());
             // Maintenance SSTables being moved from staging shouldn't be added to tracker because they're off-strategy
             if (main_sstables->contains(sst)) {
```


but I don't think it will fix the root cause.

**Comment by bhalevy** [comment]
Duplicate of #10218 probably

**Comment by bhalevy** [comment]
with reshape happening in staging too early the base table hadn't finished scanning all sstables to figure out the highest generation

**Comment by raphaelsc** [comment]
> with reshape happening in staging too early the base table hadn't finished scanning all sstables to figure out the highest generation

That's very likely #10218. Match the scenario. I am closing this one, if we see it again, which is unlikely, we can open another one.
