### ISSUE TITLE
cql-pytest could determine scylla-path and workdir without cooperation from "run"

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10209]
In commit afab1a97c645ef626a16e4957662c17bcd14adf3, @denesb added two options to the cql-pytest tests: `--scylla-path` specifies where the Scylla executable is, and `--workdir` specifies Scylla's working directory (where it saves the sstables, for example). Knowing these things were needed for `test/cql-pytest/test_tools.py`, which wants to run tools included in the Scylla executable (so needs to know where it is), and use them to inspect sstables (so needs to know where those are).

The problem with these options is that they require whoever runs the test to pass them to pytest. The aforementioned commit modified `test/cql-pytest/run` to pass these options, but if someone runs tests manually with `pytest`, or through @kostja's future run-less `test.py`, these options are not available and the test_tools.py tests get skipped.

I think we can - and should - get rid of both options, and automatically determine both pieces of information from within the test code, _without_ any cooperation from the test runner:

1. The "scylla-path" can be determined similar to how `test/cql-pytest/test_logs.py` find the log file: We can find the local Scylla process (the local process listening to our CQL connection), and then in /proc/<pid>/exe find this process's executable.
2. The "workdir" can be determined by querying Scylla for its configuration (see example in `check_pre_raft()` in `test/cql-pytest/conftest.py`) for the "workdir" or "data_file_directories" configuration.

This is not a high-priority task, because the current code works fine, but I think the result will be a cleaner separation between the tests and the Scylla runner, which ideally should be completely separate (you should be able to run tests against any invocation of Scylla, not just Scylla invoked by the test/cql-pytest/run script).

**Comment by denesb** [comment]
Thanks for creating an issue for this, I almost forgot about this (even though I promised to do it as a follow-up to https://github.com/scylladb/scylla/pull/10074).

**Comment by denesb** [comment]
Note that the `workdir` can be easily extracted from `system.config` virtual table. The challenge is only finding the process and determining whether it is a local one or not.

**Comment by nyh** [comment]
> Note that the `workdir` can be easily extracted from `system.config` virtual table. 

Indeed, this is what I said above.

> The challenge is only finding the process and determining whether it is a local one or not.

Yes, and as I said, I just solved this challenge in my test_logs.py patch. I used `lsof` to find a local process which listens to the address/port pair (which the test knows). It works very well. If I can't find such a local process it means there isn't one.

**Comment by nyh** [comment]
@denesb sent a patch titled "[PATCH] test/cql-pytest: implement test_tools.py without run-script cooperation". Please review it.
