### ISSUE TITLE
Exception (re)thrown in result_try handler can be accidentally caught by a different handler in the same result_try

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla#10211]
The `result_try` and `result_futurize_try` functions are supposed to simulate the behavior of `try`/`catch` blocks and should handle both exceptions and failed results in the same way.

Consider this `result_try` block:

```c++
return utils::result_try([&] {
    throw std::logic_error("something bad happened");
},  utils::result_catch<std::logic_error>(const auto& ex, auto&& handle) {
    // 1
    // The method below will rethrow the exception
    // As a result, it should propagate exception outside the `result_try` block
    return handle.into_result();
}), utils::result_catch_dots([&] {
    // 2
});
```

To properly simulate a `try`/`catch` block, if the exception is rethrown (or a completely new exception is thrown) in a `catch` handler, it should not be handled by any other `catch` handlers in the block but instead propagated outside the `try`/`catch` block. However, in the example above, the exception rethrown in `1` will be caught by `2`, which is incorrect.

The problem is present since https://github.com/scylladb/scylla/pull/10045.

**Comment by avikivity** [comment]
No branch is vulnerable.
