### ISSUE TITLE
Allow declaring reducer function for user-defined aggregates

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#10224]
As part of https://github.com/scylladb/scylla/issues/10215, we should have a way of dclaring an additional, optional function for user-defined aggregates. The function, with working name REDUCEFUNC, should be able to merge partial results, which can in particular come from distributing the aggregation to multiple sub-coordinators.

Proposed syntax:
CREATE [OR REPLACE] AGGREGATE [IF NOT EXISTS]
keyspace_name.aggregate_name ( cql_type )
SFUNC udf_name
STYPE cql_type
**[REDUCEFUNC udf_name]**
FINALFUNC udf_name
INITCOND [value]

Example for implementing a custom `avg` function. The state is kept as a tuple of two ints - one accumulates the current sum of values, the other accumulates their count.
1. state transition: (tuple<int, int>, int) -> tuple<int, int>
    this function takes the current state and a new value, and returns a new state
2. finalfunc: tuple<int, int> -> double
    this function produces the actual average by dividing the sum with the count
3. reducefunc: (tuple<int, int>, tuple<int, int>) -> tuple<int, int>
    this function merges two partial states and produces a new valid state; in this example, it simply adds the sums and the counts and returns a new tuple

With all functions being defined, it should be possible to distribute the computations by gathering partial results from sub-coordinators, then applying the reduce function to get a single result, and finally call the function that produces the actual average.

**Comment by psarna** [comment]
Schema info about aggregates is kept in this schema table:
```cql
cassandra@cqlsh> select * from system_schema.aggregates  ;

 keyspace_name | aggregate_name | argument_types | final_func | initcond | return_type | state_func | state_type
---------------+----------------+----------------+------------+----------+-------------+------------+------------
```
We should consider, in terms of backward compatibility, whether it's better to just append a new column (`reduce_func`) to this table, or to create a new table, (`system_schema.reducers`?) and keep the additional info is there. The first option looks much simpler at first glance, but it's actually quite complicated since we need to ensure that schema digests remain unchanged until the whole cluster, before this reducers were added. Therefore, it's probably simpler to just add a new schema table and keep the additional info in there. The additional perk for the second solution is that the original `aggregates` table remains fully compatible with C*.

**Comment by avikivity** [comment]
We can't add a table every time we add a column. However, non-Cassandra columns shouldn't be added to Cassandra tables.

**Comment by psarna** [comment]
Right, "reducers" is too specific a name. We do need something like scylla_aggregates though.

**Comment by psarna** [comment]
Our aggregations are not really compatible with Cassandra at all, because we support different default sets of languages. But we keep the `system_schema.*` tables in a fully compatible form, in order to make it easy to migrate and make sure that all the C* tools still continue working as expected. For that reason we also have `system_schema.scylla_tables`. See Tomek's commit message from 2017 for the original rationale:
```
commit cdf5b675227f81c8a0c2dbdae740162490e19ea8
Author: Tomasz Grabiec <tgrabiec@scylladb.com>
Date:   Mon Jul 10 17:20:18 2017 +0200

    schema_tables: Introduce system_schema.scylla_tables
    
    It will be used to store Scylla spcific table metadata.  We cannot
    store it in the standard "tables" table for compatibility reasons -
    Cassandra will fail to read schema if it encounteres columns it is not
    expecting.

```

**Comment by psarna** [comment]
@nyh side note though: technically, Cassandra supports any language, because their UDF system is pluggable. So as long as you load a custom .jar file that you trust, you can support any language you want.

**Comment by avikivity** [comment]
Not a bug, not backporting.
