### ISSUE TITLE
Scylla Docker 4.6 failed to start by default

### ISSUE THREAD

**Issue by kokizzu** [scylladb/scylla#10239]
- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.6
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

detail here: https://github.com/scylladb/scylla-doc-issues/issues/843

**Comment by nyh** [comment]
This looks like a duplicate of #10237. I'll close this one and comment there.
