### ISSUE TITLE
Scylla Docker 4.5 doesn't have pidof

### ISSUE THREAD

**Issue by kokizzu** [scylladb/scylla#10238]
- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.5
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

command from this page:
https://university.scylladb.com/courses/scylla-essentials-overview/lessons/architecture/topic/shard/
```
./usr/lib/scylla/seastar-cpu-map.sh -n scylla
bash: pidof: command not found
```

**Comment by avikivity** [comment]
Backported to 5.0, 4.6. 4.5.
