### ISSUE TITLE
"dnf upgrade" on Fedora 22 is still getting 0.18

### ISSUE THREAD

**Issue by dmarti** [scylladb/scylla#1023]
What I did: run a dnf upgrade on Fedora 22 and check scylla-server version

What I expected to see: version 0.19

What I got: version 0.18

```
$ sudo dnf upgrade && dnf info scylla-server
Last metadata expiration check performed 2:20:06 ago on Thu Mar 10 09:02:29 2016.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check performed 13 days, 1:10:16 ago on Fri Feb 26 10:12:21 2016.
Installed Packages
Name        : scylla-server
Arch        : x86_64
Epoch       : 0
Version     : 0.18
Release     : 20160215.b532919.fc22
Size        : 26 M
Repo        : @System
From repo   : scylla
Summary     : Scylla is a highly scalable, eventually consistent, distributed, partitioned row DB.
URL         : http://www.scylladb.com/
License     : AGPLv3
Description : 
```

**Comment by lmr** [comment]
@dmarti I think cleaning the dnf cache should solve this -> `dnf clean all` before the commands you mentioned.

**Comment by dmarti** [comment]
Working now, thank you.

**Comment by tzach** [comment]
@dmarti worth while to to add to the upgrade doc section

**Comment by avikivity** [comment]
It should work without any `dnf clean all`.

**Comment by penberg** [comment]
@avikivity @slivne Any updates on this? Perhaps we did not upload some RPM metadata to the S3 repository?

**Comment by tzach** [comment]
@penberg if this was the case dnf clean would not help
Maybe its a dnf "feature"

http://dnf.readthedocs.org/en/latest/user_faq.html#why-do-i-get-different-results-with-dnf-upgrade-vs-yum-update
http://dnf.readthedocs.org/en/latest/user_faq.html#is-it-possible-to-force-dnf-to-get-the-latest-metadata-on-dnf-upgrade
