### ISSUE TITLE
Coredump during memory stress

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#10247]
## Installation details

Kernel Version: 5.13.0-1017-aws

Scylla version (or git commit hash): `5.0~rc2-20220316.839d9ef41` with build-id `1319e7e64335b7e5c7531f773e92ef997b6c51ba`

Cluster size: 4 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- longevity-lwt-24h-5-0-db-node-3da79032-6 (34.241.84.194 | 10.0.0.89) (shards: 8)
- longevity-lwt-24h-5-0-db-node-3da79032-5 (34.248.100.108 | 10.0.1.130) (shards: 8)
- longevity-lwt-24h-5-0-db-node-3da79032-4 (34.254.180.245 | 10.0.2.99) (shards: 8)
- longevity-lwt-24h-5-0-db-node-3da79032-3 (54.247.3.221 | 10.0.1.179) (shards: 8)
- longevity-lwt-24h-5-0-db-node-3da79032-2 (34.243.197.145 | 10.0.1.121) (shards: 8)
- longevity-lwt-24h-5-0-db-node-3da79032-1 (3.250.124.90 | 10.0.1.25) (shards: 8)

OS / Image: `ami-07df681f83cd78172` (aws: eu-west-1)

Test: `longevity-lwt-24h-test`

Test id: `3da79032-61fa-482b-bef3-8c3710d36b5d`

Test name: `longevity/longevity-lwt-24h-test`

Test config file(s):

- [longevity-lwt-basic-24h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/234f79a81bc97d0e44c3ab51441017b646fdf393/test-cases/longevity/longevity-lwt-basic-24h.yaml)

Coredump during memory stress nemesis (run stress-ng to preempt allocated memory of scylla process)
```
2022-03-17 18:28:05.388: (CoreDumpEvent Severity.ERROR) period_type=one-time event_id=80f24685-ac86-4e4b-a490-4e948cd9eade node=Node longevity-lwt-24h-5-0-db-node-3da79032-4 [34.254.180.245 | 10.0.2.99] (seed: False)
```

Coredump
```
2022-03-17 18:29:32.601 <2022-03-17 18:27:41.000>: (CoreDumpEvent Severity.ERROR) period_type=one-time event_id=00015051-1386-4eaa-8af2-45ad8a43b118 node=Node longevity-lwt-24h-5-0-db-node-3da79032-4 [34.254.180.245 | 10.0.2.99] (seed: False)
corefile_url=https://storage.cloud.google.com/upload.scylladb.com/core.fwupd.0.4c916af2b95a4ae38b34affb6238a7bb.17716.1647541661000000000000/core.fwupd.0.4c916af2b95a4ae38b34affb6238a7bb.17716.1647541661000000000000.gz
backtrace=           PID: 17716 (fwupd)
UID: 0 (root)
GID: 0 (root)
Signal: 11 (SEGV)
Timestamp: Thu 2022-03-17 18:27:41 UTC (58s ago)
Command Line: /usr/libexec/fwupd/fwupd
Executable: /usr/libexec/fwupd/fwupd
Control Group: /system.slice/fwupd.service
Unit: fwupd.service
Slice: system.slice
Boot ID: 4c916af2b95a4ae38b34affb6238a7bb
Machine ID: 6e0c2587b29e47e9a1ba4dacef523868
Hostname: longevity-lwt-24h-5-0-db-node-3da79032-4
Storage: /var/lib/systemd/coredump/core.fwupd.0.4c916af2b95a4ae38b34affb6238a7bb.17716.1647541661000000000000
Message: Process 17716 (fwupd) of user 0 dumped core.
Stack trace of thread 17716:
#0  0x000055d55506c10d main (fwupd + 0x1410d)
#1  0x00007f59f6a5e0b3 __libc_start_main (libc.so.6 + 0x240b3)
#2  0x000055d55506c40e _start (fwupd + 0x1440e)
Stack trace of thread 17717:
#0  0x00007f59f6b4c9cf __poll (libc.so.6 + 0x1129cf)
#1  0x00007f59f6e2e36e n/a (libglib-2.0.so.0 + 0x5236e)
#2  0x00007f59f6e2e4a3 g_main_context_iteration (libglib-2.0.so.0 + 0x524a3)
#3  0x00007f59f6e2e4f1 n/a (libglib-2.0.so.0 + 0x524f1)
#4  0x00007f59f6e57ad1 n/a (libglib-2.0.so.0 + 0x7bad1)
#5  0x00007f59f6c34609 start_thread (libpthread.so.0 + 0x8609)
#6  0x00007f59f6b59163 __clone (libc.so.6 + 0x11f163)
```

download_instructions
```
gsutil cp gs://upload.scylladb.com/core.fwupd.0.4c916af2b95a4ae38b34affb6238a7bb.17716.1647541661000000000000/core.fwupd.0.4c916af2b95a4ae38b34affb6238a7bb.17716.1647541661000000000000.gz .
gunzip /var/lib/systemd/coredump/core.fwupd.0.4c916af2b95a4ae38b34affb6238a7bb.17716.1647541661000000000000.gz
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 3da79032-61fa-482b-bef3-8c3710d36b5d`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=3da79032-61fa-482b-bef3-8c3710d36b5d)
- Show all stored logs command: `$ hydra investigate show-logs 3da79032-61fa-482b-bef3-8c3710d36b5d`

## Logs:
https://cloudius-jenkins-test.s3.amazonaws.com/3da79032-61fa-482b-bef3-8c3710d36b5d/20220318_170529/db-cluster-3da79032.tar.gz

Console output:
https://s3.console.aws.amazon.com/s3/object/cloudius-jenkins-test?region=us-east-1&prefix=3da79032-61fa-482b-bef3-8c3710d36b5d/20220318_170529/5.0_lwt_24h_console_output.tar.gz

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-lwt-24h-test/2/)

**Comment by roydahan** [comment]
fwupd issue, not scylla.
