### ISSUE TITLE
Scylla Docker 4.6.0 does not log to stdout

### ISSUE THREAD

**Issue by rueian** [scylladb/scylla#10242]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

## problem

Scylla Docker 4.6.0 use this command option `--log-to-syslog 1 --log-to-stdout 0` and all logs are written to `/var/log/syslog`

I think logs are supposed to be written to stdout or stderr

## reproduce

run `docker run --rm -it scylladb/scylla:4.6.0`, and will see this:

<img width="1692" alt="image" src="https://user-images.githubusercontent.com/2727535/159010257-651ef4fb-2727-4c27-a083-4206f8619d3e.png">

**Comment by slivne** [comment]
fix in 4.6.3
