### ISSUE TITLE
Discrepancy between two copies of host_id during replace_node

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla#10243]
Commit 3fef60407535a2ee0416fe08f4a7a5fdbf8f274b made a copy of `system_keyspace::local_cache::host_id` value on `db::config`. This should be problematic in case of replace-node -- the copying of the value from system keyspace cache happens in main.cc _before_ `storage_service::init_server` which, in turn, would go ahead and update the system keyspace's value in `storage_service::prepare_replacement_info` leaving its `db::config` copy in the old value.

cc @bhalevy @cmm

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
