### ISSUE TITLE
doc: refer to http://backtrace.scylladb.com/

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10252]
To help developers find http://backtrace.scylladb.com/, refer to it in the documentation.

First docs that come into mind are:
https://github.com/scylladb/scylla/blob/master/HACKING.md and possibly https://github.com/scylladb/scylla/blob/master/docs/guides/debugging.md

We could also add a pointer for the server's documentation (See https://github.com/scylladb/scylla_s3_reloc_server/issues/14)

**Comment by avikivity** [comment]
Not a bug, not backporting.
