### ISSUE TITLE
Test for developer-mode in scylla_io_setup does not cove all options of setting the flag

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1026]
current code

```
is_developer_mode() {
    echo $SCYLLA_ARGS|egrep -c "\-\-developer-mode(\s+|=)1"
}

```

need to support
--developer-mode true
--developer-mode 1
--developer-mode=true
--developer-mode=1

(if all of this are legal)

current check does not allign with the instruction of how to setup developer-mode - in our website we have --developer-mode trye

**Comment by penberg** [comment]
I sent a patch for this to the mailing list.
