### ISSUE TITLE
Timeouts during disrupt_nodetool_enospc nemesis "Operation timed out for scylla_bench.test_counters - received only 1 responses from 2 CL=QUORUM"

### ISSUE THREAD

**Issue by rayakurl** [scylladb/scylla#10262]
Kernel version: `5.13.0-1017-aws`

Scylla version (or git commit hash): `5.0.rc2-0.20220316.839d9ef41 with build-id 1319e7e64335b7e5c7531f773e92ef997b6c51ba`

Cluster size: 4 nodes (i3.2xlarge)

Scylla running with shards number (live nodes):
   longevity-counters-3h-5-0-db-node-10727333-1 (3.215.134.98 | 10.0.2.50): 8 shards
   longevity-counters-3h-5-0-db-node-10727333-4 (44.200.227.114 | 10.0.0.243): 8 shards
   longevity-counters-3h-5-0-db-node-10727333-5 (44.200.154.238 | 10.0.1.63): 8 shards
   longevity-counters-3h-5-0-db-node-10727333-6 (44.193.73.219 | 10.0.0.151): 8 shards
Scylla running with shards number (terminated nodes):

   longevity-counters-3h-5-0-db-node-10727333-3 (3.237.66.84 | 10.0.1.13): 8 shards
   longevity-counters-3h-5-0-db-node-10727333-2 (18.209.237.118 | 10.0.2.52): 8 shards

OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0338c83239d0ab168` (aws: us-east-1)

Test: `longevity-counters-3h-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-counters-3h.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/2ccd716c88eceaae14a141a8a4d6a8f3496df03e/test-cases/longevity/longevity-counters-3h.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/2ccd716c88eceaae14a141a8a4d6a8f3496df03e/test-cases/longevity/longevity-counters-3h.yaml&source=gmail-html&ust=1648115154021000&usg=AOvVaw2hyQ136hUHigkuZ1l57yFU))

**Issue description**

====================================
During disrupt_nodetool_enospc nemesis (which allocates 90% of space under var/lib/scylla/ on a longevity-counters-3h-5-0-db-node-10727333-4), there were lots of scylla-bench failures due to only 1 node replying instead of 2:

2022/03/20 16:29:54 Operation timed out for scylla_bench.test_counters - received only 1 responses from 2 CL=QUORUM. 1h44m25.4s 7388 7388 0 11ms 9.2ms 5.6ms 4.1ms 3.5ms 1.9ms 2.2ms
2022/03/20 16:29:54 Operation timed out for scylla_bench.test_counters - received only 1 responses from 2 CL=QUORUM. 2022/03/20 16:29:54 Operation timed out for scylla_bench.test_counters - received only 1 responses from 2 CL=QUORUM. 2022/03/20 16:29:54 Operation timed out for scylla_bench.test_counters - received only 1 responses from 2 CL=QUORUM. 2022/03/20 16:29:54 Operation timed out for scylla_bench.test_counters - received only 1 responses from 2 CL=QUORUM. 2022/03/20 16:29:54 Operation timed out for scylla_bench.test_counters - received only 1 responses from 2 CL=QUORUM. 1h44m28s 6652 6652 9 9.4ms 7.9ms 5.9ms 4.1ms 3.4ms 1.9ms 2.2ms
2022/03/20 16:29:54 Operation timed out for scylla_bench.test_counters - received only 1 responses from 2 CL=QUORUM. 2022/03/20 16:29:54

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 10727333-6f9e-4a26-a66f-896da86a52e7`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=branch-5.0&test_id=10727333-6f9e-4a26-a66f-896da86a52e7](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dbranch-5.0%26test_id%3D10727333-6f9e-4a26-a66f-896da86a52e7&source=gmail-html&ust=1648115154022000&usg=AOvVaw3ZVXr6YHKgaYLQqEIFnzjw))
Show all stored logs command: `$ hydra investigate show-logs 10727333-6f9e-4a26-a66f-896da86a52e7`

Test id: `10727333-6f9e-4a26-a66f-896da86a52e7`

Logs:
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_174924/grafana-screenshot-longevity-counters-3h-test-scylla-per-server-metrics-nemesis-20220320_175110-longevity-counters-3h-5-0-monitor-node-10727333-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_174924/grafana-screenshot-longevity-counters-3h-test-scylla-per-server-metrics-nemesis-20220320_175110-longevity-counters-3h-5-0-monitor-node-10727333-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_174924/grafana-screenshot-longevity-counters-3h-test-scylla-per-server-metrics-nemesis-20220320_175110-longevity-counters-3h-5-0-monitor-node-10727333-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_174924/grafana-screenshot-longevity-counters-3h-test-scylla-per-server-metrics-nemesis-20220320_175110-longevity-counters-3h-5-0-monitor-node-10727333-1.png)&source=gmail-html&ust=1648115154022000&usg=AOvVaw0G_ANaA5qPchHv6hw9G76C)
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_174924/grafana-screenshot-overview-20220320_174924-longevity-counters-3h-5-0-monitor-node-10727333-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_174924/grafana-screenshot-overview-20220320_174924-longevity-counters-3h-5-0-monitor-node-10727333-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_174924/grafana-screenshot-overview-20220320_174924-longevity-counters-3h-5-0-monitor-node-10727333-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_174924/grafana-screenshot-overview-20220320_174924-longevity-counters-3h-5-0-monitor-node-10727333-1.png)&source=gmail-html&ust=1648115154022000&usg=AOvVaw37YRI6uu4NPWLSDhOJe1Q-)
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/db-cluster-10727333.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/db-cluster-10727333.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/db-cluster-10727333.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/db-cluster-10727333.tar.gz)&source=gmail-html&ust=1648115154022000&usg=AOvVaw3V8S21y5T3_hh1q1lb0jWR)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/loader-set-10727333.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/loader-set-10727333.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/loader-set-10727333.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/loader-set-10727333.tar.gz)&source=gmail-html&ust=1648115154022000&usg=AOvVaw3CsXtC4pS1pK22U1RT4CqR)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/monitor-set-10727333.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/monitor-set-10727333.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/monitor-set-10727333.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/monitor-set-10727333.tar.gz)&source=gmail-html&ust=1648115154022000&usg=AOvVaw23H8xvRA2tNzLj666yKsLR)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/sct-runner-10727333.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/sct-runner-10727333.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/sct-runner-10727333.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/10727333-6f9e-4a26-a66f-896da86a52e7/20220320_180308/sct-runner-10727333.tar.gz)&source=gmail-html&ust=1648115154022000&usg=AOvVaw1DQ9ZzPmXCw6B62sNK4Yet)

[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-counters-3h-test/2/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-counters-3h-test/2/&source=gmail-html&ust=1648115154022000&usg=AOvVaw1bU96xtcT62fsVbWrFGbyA))

**Comment by rayakurl** [comment]
This issue reproduced 2/2 times during the same job run: 
https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-counters-3h-test/

**Comment by slivne** [comment]
Not able to restore monitoring https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/126/console - the same as #10257 - please fix so we can have a look.

**Comment by slivne** [comment]
We do have something strange more then one node had a drop in cpu load

![Screenshot from 2022-04-03 21-04-04](https://user-images.githubusercontent.com/3465480/161442698-1fb65d61-4613-49e1-8469-8cc903e6a150.png)


Trying to extract information of which operation failed 

we have a metric ```scylla_transport_cql_errors_total```

![Screenshot from 2022-04-03 21-29-11](https://user-images.githubusercontent.com/3465480/161442709-553c3ede-aa0f-4c2c-a78f-06f121ab1cf6.png)

or by intsance and type

![Screenshot from 2022-04-03 21-31-03](https://user-images.githubusercontent.com/3465480/161442779-be35a899-aa76-4201-b6cb-b0ddf11456bd.png)



lets check which value matches the number of errors

```
[shlomi@shlomi-scylladb-com i_10262]$ grep "16:[23]" loader-set-10727333/longevity-counters-3h-5-0-loader-node-10727333-1/scylla-bench*.log   | cut -f2- -d':' | cut -f3- -d' ' | sort | uniq -c
      1 Cannot achieve consistency level for cl QUORUM. Requires 2, alive 1
     57 EOF
    175 gocql: no response received from cassandra within timeout period
      2 Operation failed for scylla_bench.test_counters - received 0 responses and 1 failures from 2 CL=QUORUM.
     23 Operation failed for scylla_bench.test_counters - received 1 responses and 1 failures from 2 CL=QUORUM.
     15 Operation timed out for scylla_bench.test_counters - received only 0 responses from 2 CL=QUORUM.
    105 Operation timed out for scylla_bench.test_counters - received only 1 responses from 2 CL=QUORUM.
      2 writev tcp 10.0.2.27:51285->10.0.0.243:9042: writev: broken pipe
```

The only ting that stand out as matches is 

```
    105 Operation timed out for scylla_bench.test_counters - received only 1 responses from 2 CL=QUORUM.
```

that is exactly the read timeout - but I am not sure that makes sense.

The only reason we will get read timeouts is if there is no speculative retry setup 

But there seems to be something setup not sure if this is the only table need the schema

![Screenshot from 2022-04-03 21-48-35](https://user-images.githubusercontent.com/3465480/161443399-95807500-88b6-45d3-9c0d-8b2ca001ad1a.png)


To make it clear there is no problem of CPU being maxed out

![Screenshot from 2022-04-03 21-48-57](https://user-images.githubusercontent.com/3465480/161443405-53e17229-4803-4abb-8380-6ba4070b260f.png)

**Comment by slivne** [comment]
Another theory I had was that the read_timeout maybe returned by the node that ran out of disk space  -but thats not what's happening the error is comming back from the other nodes - so why are they getting a read timeout there are supposed to be 3 replicas and one of them goes down the rest should be able to handle the read and write traffic easily with failing over to another replica (instead of the one that failed) if they have speculative retry set.

**Comment by slivne** [comment]
I don't think we should block the release on this - but it may be  a regression and I want to validate if its or its not.

**Comment by jul-stas** [comment]
IIUC the counter read and regular read start differing deep in the internals, where cells are accessed - I don't see anything on the coordinator/replica level. (@psarna can you too have a look?)

I'll make an experiment to be sure, but counters code has not been modified for a very long time, so a new bug is unlikely.

**Comment by slivne** [comment]
@jul-stas ^^

**Comment by psarna** [comment]
@slivne there was still no response to your previous question set, particularly:
> we need the schema - just to double check that there is indeed speculaive retry setup for the table used in the load.

Neither Juliusz nor I found anything in the code that makes counter reads unique wrt. timeouts. Lack of retrying could explain the issue, but it's still not clear why it's counters that would time out more often than other things. Or maybe it's just a coincidence and some counter data landed on a hot shard.

**Comment by roydahan** [comment]
This timeout isn't unique to counters, we get it for every workload in scylla_bench.
AFAIK, scylla_bench doesn't have a retry mechanism and it just throw this message and move to the next key.

**Comment by DoronArazii** [comment]
@rayakurl can you please provide the schema?
@psarna needs that to keep evaluating this issue

**Comment by roydahan** [comment]
To make my previous comment clearer, if this issue is about the "operation timeout" error we get from scylla_bench, it's not a real issue.
Regardless of counters, we get this error from every workload of scylla_bench because the tool doesn't do retries.

**Comment by DoronArazii** [comment]
@psarna any news for this issue?

**Comment by psarna** [comment]
@DoronArazii Roy stated above, that operation timeouts are expected, and it's not a real issue. So I guess it should be closed
