### ISSUE TITLE
Incompatible change of supervisor service name inside Scylla container image

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla#10269]
Container image of scylla consist of several processes running in parallel, hence a supervisor is used.  
In cb190481863cdd4d90e8aae1e1b0f976a4a7f9c3 name of Scylla service in supervisor configuration changed from `scylla` to `scylla-server`. This change is backward incompatible and breaks Scylla Operator deployments. 
Operator is using this name inside a PreStop hook, to gracefully shutdown scylla on every restart. 

https://github.com/scylladb/scylla-operator/blob/44dcc72c09e65ff82dea5db44e62439304d0e636/pkg/controller/sidecar/sync.go#L46

https://github.com/scylladb/scylla-operator/blob/18f9c04f0a1aa0ea54714a21492f808f7ff5903e/pkg/controller/scyllacluster/resource.go#L412

*Installation details*
Scylla version (or git commit hash): 4.6.0
OS (RHEL/CentOS/Ubuntu/AWS AMI): Container image

**Comment by zimnx** [comment]
@syuu1228 would you mind taking a look?

**Comment by avikivity** [comment]
Backported to 4.6, 5.0
