### ISSUE TITLE
Boto3 prints Alternator's error codes strangely - are we formatting them wrong?

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10278]
I ran some buggy DynamoDB request:
```
    ret=test_table_s.update_item(Key={'p': p}, ReturnValues='ALL_NEW',
        UpdateExpression='ADD n :inc',
        ExpressionAttributeValues={':inc': '1'})
 ```
The request is incorrect, of course, because :inc should have been an integer, not a string as I wrote it.
The Alternator client reports the error in the following manner:

> E           botocore.exceptions.ClientError: An error occurred (400) when calling the UpdateItem operation: {"__type":"com.amazonaws.dynamodb.v20120810#ValidationException","message":"Incorrect operand type for operator or function. Expected N: {"S":"1"}"}

But when running against Amazon DynamoDB, the error is reported differently:

> E           botocore.exceptions.ClientError: An error occurred (ValidationException) when calling the UpdateItem operation: Invalid UpdateExpression: Incorrect operand type for operator or function; operator: ADD, operand type: STRING, typeSet: ALLOWED_FOR_ADD_OPERAND

The question is what causes boto3 to be confused (?) by Alternator's error and not understand that this is a ValidationException. Are we doing something wrong in the format of the error message?

Nobody has complained about this so far, and it probably won't break most code (it's still a ClientError, and there is still the word ValidationException somewhere in the message), but I want to understand what is causing this difference.

**Comment by nyh** [comment]
Scylla returns the error JSON
```
{'Message': '{"__type":"com.amazonaws.dynamodb.v20120810#ValidationException","message":"An operand in the update expression has an incorrect data type: {"S":"1"}"}', 'Code': '400'}
```
Whereas DynamoDB returns:
```
{'Message': 'Invalid UpdateExpression: Incorrect operand type for operator or function; operator: ADD, operand type: STRING, typeSet: ALLOWED_FOR_ADD_OPERAND', 'Code': 'ValidationException'},
```

Scylla's response format is completely broken:
1. Instead of a user-readable message along in "Message", we put a JSON in it!
2. For "Code" we used the number 400 (!) instead of the string 'ValidationException'. 400 is the HTTP error code, it shouldn't be printed inside the JSON!
3. The "__type" is an alternative to "Code" - clients should understand both, supposedly __type is for x-amz-json-1.0 whereas Code is for x-amz-json-1.1, although clearly this is no longer true (DynamoDB today uses x-amz-json-1.0 but sends only Code, not __type). We can, and probably should, send both, although I don't think we need to send "__type" if DynamoDB doesn't. In "__type", whatever we put before the "#" is ignored. I guess the string 'com.amazonaws.dynamodb.v20120810' we copied from some old version of DynamoDB, and we can continue to use it.

I don't understand how we never noticed this before :-(

**Comment by nyh** [comment]
The plot thickens... Scylla doesn't actually return the strange JSON I showed above. Apparently that's how boto3 misrepresents it... What Scylla returns in the response body is (according to Wireshark):

{"__type":"com.amazonaws.dynamodb.v20120810#ValidationException","message":"An operand in the update expression has an incorrect data type: {"S":"1"}"}

There is node "Code" or similar junk. I need to write a better test, that bypasses boto3, to see what's really going on...

**Comment by nyh** [comment]
I turns out that this is **not** a general bug, but a specific bug in the specific error message in this case. The problem that the message contains invalid JSON that boto3 cannot parse - because the double quotes were not escaped...

This led boto3 to decide that since it can't parse the JSON, it should silently use the broken-json as a string message, and wrap it into its own structure with an invented a "code".

**Comment by avikivity** [comment]
Minor, not backporting.
