### ISSUE TITLE
ServiceLevel: incorrect error message when using day/month values for timeout

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla#10286]
scylla-version: 5.1.dev
scylla-release: 0.20220316.2e7009f42773
docker-image-name: scylla-nightly:5.1.dev-0.20220316.2e7009f42773
unified-pack-url-x86_64: downloads.scylladb.com/unstable/scylla/master/relocatable/2022-03-16T04:02:25Z/scylla-x86_64-unified-package-5.1.dev.0.20220316.2e7009f42773.tar.gz

The CQL command for creating a new ServiceLevel accepts values that are larger than the declared valid range ("28h" > "24h" limit).

Steps to reproduce:

1) Create a cluster with 1 node.
2) Attempt to create a ServiceLevel with a timeout value larger than 24h (e.g. "28h").

Expected behavior: an InvalidRequest ezception should be raised with a message "Timeout values cannot be longer than 24h".
Actual behavior: no exception is raised

Jenkins job with test run: https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/maciej/job/mc-dtest-parallel/18/testReport/sla_per_user_test

**Comment by psarna** [comment]
I think this is a non-issue. There's nothing substantially wrong with specifying a timeout of 10 years, except that the code, for internal reasons, is much easier if we refuse to parse days, months, years, etc, and only allow units lower or equal to hours.

So if somebody really wants a week-long timeout, it's absolutely fine to set the timeout to 168 hours, they just won't be able to specify it to "7 days".

So what's ultimately wrong here is the error message, it incorrectly says "Timeout values cannot be expressed in days/months".
In contrast, `USING TIMEOUT` already noticed this issue and the error message was fixed:
```
cassandra@cqlsh> select * from system_schema.tables using timeout 3d;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Timeout values cannot be expressed in days/months"
```

... so we should just do the same here.

**Comment by KnifeyMoloko** [comment]
Thanks for the clarification @psarna . I'll adjust the new ServiceLevel tests to check for the correct error message when using days/months.

**Comment by avikivity** [comment]
Minor, but may as well backport. Backported to 4.6, 5.0. 5.1 already had it.
