### ISSUE TITLE
scylla-server has dependency to OpenJDK7 which conflicts in softwares who use JDK8

### ISSUE THREAD

**Issue by indykish** [scylladb/scylla#1029]
### Why does `scylla-server` need Open JDK ? 

I see scylla-jmx (JMX an instrumentation for the JVM) will need Java. 

Since `scylla-server` is native and why is it dependent on  scylla-jmx.

Should `scylla-jmx` if it collects metrics be an optional package ?

### In ubuntu 14.04, OpenJDK 7 is available, but it has reached EndOfLife.

We use another server that is written in scala using OpenJDK8. We are unable to install both scylla an our server along side. This is common for organizations to have as they have their own apps written in xyz JDK.

Is it needed for scylla-server to be dependent on OpenJDK ?

Discussion thread. https://mail.google.com/mail/u/0/#inbox/15368ceb64f7eb9d

As per `Dan Marti`
    It will be better to depend on `java-runtime-headless`
    https://fedorahosted.org/released/javapackages/doc/#_core_java_packages

**Comment by indykish** [comment]
What % of users(administrators) will use `nodetool` in cassandra land ? 

Do you plan on making the scylla-server point to `java-runtime-headless`

**Comment by penberg** [comment]
@indykish Are you using Ubuntu or Fedora? AFAICT, our RPMS are already OK -- they depend on ``java-headless``. Ubuntu, on the other hand, currently requires Java 7, and I sent a patch to hopefully fix that up.

**Comment by indykish** [comment]
@penberg  ubuntu 14. 

Thanks for the fix.

**Comment by penberg** [comment]
Fixed by https://github.com/scylladb/scylla-jmx/commit/d7e3dae3232856edb15d06c04a1d695b54bc7d05
