### ISSUE TITLE
Incorrect results returned with IN clause in a partition and index restriction

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylla#10300]
*Installation details*
Scylla version (or git commit hash): `4.6.0-0.20220306.2f2d22a86`
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker image `963dd3bf6aa7`

# Description
When specifying an IN clause restriction within the partition key **AND** restricting an indexed column, Scylla will throw a misleading error claiming that:
```cql
cqlsh> SELECT * FROM ks.foo WHERE pk IN (0, 1) AND val=False;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Select on indexed columns and with IN clause for the PRIMARY KEY are not supported"
```

Notably, the misleading error message has been updated in https://github.com/scylladb/scylla/pull/10299/commits/86c388540f619220b3200c05ef02883bb6c7126b to reflect the fact that this query requires `ALLOW FILTERING`, which in turn should be executed as a normal query (Scylla should retrieve the partition key first, then filter the results based on the non-key column restriction and send the results back to the user). 

This is - unfortunately - not what is seen. Adding `ALLOW FILTERING` to the query makes Scylla **ignore the PARTITION KEY restriction** and act only on the indexed column, therefore returning an incorrect result set:

```cql
cqlsh> SELECT * FROM ks.foo WHERE pk IN (0, 1) AND val=False ALLOW FILTERING;

 pk | ck | val
----+----+-------
  1 |  1 | False
  1 |  3 | False
  0 |  1 | False
  0 |  3 | False
  2 |  1 | False
  2 |  3 | False

(6 rows)
cqlsh> 
```

Note that pk=2 was returned, but our query hasn't requested it.

# Reproducer
```cql
CREATE TABLE ks.foo (pk int, ck int, val boolean, PRIMARY KEY(pk, ck));
CREATE INDEX on ks.foo(val);
INSERT INTO ks.foo (pk, ck, val) VALUES (0, 0, True);
INSERT INTO ks.foo (pk, ck, val) VALUES (0, 1, False);
INSERT INTO ks.foo (pk, ck, val) VALUES (0, 2, True);
INSERT INTO ks.foo (pk, ck, val) VALUES (0, 3, False);
INSERT INTO ks.foo (pk, ck, val) VALUES (1, 0, True);
INSERT INTO ks.foo (pk, ck, val) VALUES (1, 1, False);
INSERT INTO ks.foo (pk, ck, val) VALUES (1, 2, True);
INSERT INTO ks.foo (pk, ck, val) VALUES (1, 3, False);
INSERT INTO ks.foo (pk, ck, val) VALUES (2, 0, True);
INSERT INTO ks.foo (pk, ck, val) VALUES (2, 1, False);
INSERT INTO ks.foo (pk, ck, val) VALUES (2, 2, True);
INSERT INTO ks.foo (pk, ck, val) VALUES (2, 3, False);
SELECT * FROM ks.foo WHERE pk IN (0, 1) AND val=False; -- Trigger the error claiming that the statement is unsupported
SELECT * FROM ks.foo WHERE pk IN (0, 1) AND val=False ALLOW FILTERING; -- Returns an incorrect result set
```

@psarna

**Comment by psarna** [comment]
Changed my mind and fixed it right away, along with a regression test, here you go: https://github.com/scylladb/scylla/pull/10302

**Comment by avikivity** [comment]
Backported to 4.5, 4.6, 5.0.

**Comment by avikivity** [comment]
Dequeued 4.5 backport, @psarna please help.

**Comment by psarna** [comment]
Ah, the code before expressions :( I'll prepare something today

**Comment by psarna** [comment]
Queued to 4.5
