### ISSUE TITLE
mutation::consume doesn't emit a closing range_tombstone_change if the highest tombstone is open ended

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10316]
As of 5.1.dev 9c96a3714349568597ce1718a9351114f26be413,
https://github.com/scylladb/scylla/blob/9c96a3714349568597ce1718a9351114f26be413/mutation.hh#L297-L299

will fail to emit a closing range_tombstone_change if the highest tombstone is open ended
since `range_tombstone_change_generator::flush` does not do it by default.

This is reproducible with 028b2a8cdfdc12721b2be23d175cbc756d2507de without 5a09e5234ef4e1ee673bc7fca481defbbb2c0384

**Comment by bhalevy** [comment]
The issue is currently confined to master.
5.0 and 4.6 do not have this issue

**Comment by bhalevy** [comment]
Although 4.6 and 5.0 aren't currently exposed to this bug
since they don't have fcda35d08ee53cb9afad99ddba6c8957b3ab7ec3,
I do suggest backporting 0a3aba36e6e4b78ef6e7bb2f5ee204aa2cccfe1c
for safety reasons with the improved random_range_tombstone test lib function
and for making further backports of changes on these paths easier.

Note that even without 002be743f661fd2f5370a92936ef0cb627260721 the closing range_tombstone_change will be generated by either `range_tombstone_change_generator::flush` or by the caller (`upgrading_consumer`), but not both, since the callers emit it only if `rt_gen.flush` passed a live tombstone to the callback, and that doesn't happen when it emits the last closing range_tombstone_change with the fix.

**Comment by avikivity** [comment]
@tgrabiec please evaluate @bhalevy's comment and backport if you agree.

**Comment by tgrabiec** [comment]
I agree to backport. But merge conflicts present. @bhalevy Please provide a backport.

**Comment by bhalevy** [comment]
The backport is harder than I expected.
b3e2bbe5bd16cc5c64b4a8fd5e62123d5b73b128 introduced new range_tombstone kinds to mutation_source_test and tests fail with it (also with the rest of the patches).  I'm working on figuring out where the problem is and if anything else is required to be backported, as this may have exposed pre-existing issues in 5.0.

**Comment by avikivity** [comment]
Queued for 5.0

**Comment by avikivity** [comment]
@bhalevy let's restart the 5.0 backport.

**Comment by mykaul** [comment]
Seem to have been backported to 5.0 already, removing backport label.
