### ISSUE TITLE
Incorrect locale value in docker build script

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla#10310]
The commit scylladb/scylla@546e4adf9e1d560cbb99932925b13e30200c0d3a added default locale settings,
and it contains an invalid value on this line: https://github.com/scylladb/scylla/blob/546e4adf9e1d560cbb99932925b13e30200c0d3a/dist/docker/debian/build_docker.sh#L94

`en_US.UTF_8` is not a valid locale, it should be `en_US.UTF-8` instead

This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5.0~rc2-20220322.f3564db94
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Latest Docker nightly

**Comment by avikivity** [comment]
Backported to 5.0, older releases not vulnerable.
