### ISSUE TITLE
range_tombstone_list: insert_from: incorrect range_tombstone applied to reverter in non-overlapping case

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10326]
https://github.com/scylladb/scylla/blob/fe2fa3f20df3dc4eb6b7275cf224befaffb4773a/range_tombstone_list.cc#L108
This looks like a typo introduced in fe2fa3f20df3dc4eb6b7275cf224befaffb4773a
which loses the end position of the range tombstone.

**Comment by bhalevy** [comment]
Fixed by 2d800576178dde6795b66dc443883297ab1af5a5

**Comment by bhalevy** [comment]
Requires backport to 5.0

@slivne can you please add a `backport 5.0` label?

**Comment by avikivity** [comment]
Backported to 5.0.
