### ISSUE TITLE
FINALFUNC and INITCOND should be optional for user-defined aggregates

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#10324]
Contrary to what I once found on a (deprecated) docs page, final function and initial condition for user-defined aggregates are after all optional. The semantics are as follows:
 - default initcond is `null`
 - default finalfunc is simply not called if not needed, and the final state is returned instead (so you can think of a default finalfunc as identity)

Source: https://cassandra.apache.org/doc/latest/cassandra/cql/functions.html#user-defined-aggregates-functions

In Scylla, we currently require both parameters - and we shoudn't do that.

**Comment by avikivity** [comment]
Not a regression, so not backporting.
