### ISSUE TITLE
Alternator - empty AttributesToGet should be forbidden

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10332]
In DynamoDB one can retrieve only a subset of the attributes using the `AttributesToGet` or `ProjectionExpression` paramters to read requests. Neither allows an **empty** list of attributes - if you don't want any attributes, you should use `Select=COUNT` instead.

Currently we correctly refuse an empty `ProjectionExpression` - and have a test for it in `test_projection_expression.py`::`test_projection_expression_toplevel_syntax`.

However, Alternator is missing the same empty-forbidding logic for `AttributesToGet`. An empty `AttributesToGet` is currently allowed, and basically says "retrieve everything", which is sort of unexpected.

Here is a reproducing test (for GetItem):

```python
# Verify that it is forbidden to ask for an empty AttributesToGet
def test_getitem_attributes_to_get_empty(dynamodb, test_table):
    p = random_string()
    c = random_string()
    with pytest.raises(ClientError, match='ValidationException'):
        test_table.get_item(Key={'p': p, 'c': c}, AttributesToGet=[], ConsistentRead=True)
```

**Comment by avikivity** [comment]
Backported to 4.6, 5.0.

**Comment by avikivity** [comment]
Removing the backport candidate label again, @benipeled
