### ISSUE TITLE
Data is not transferred on bootstrap when replacing node in muli-dc setup

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla#10338]
*Installation details*
Scylla version (or git commit hash): Scylla version 5.1.dev-0.20220316.2e7009f42773 with build-id 870b0196c7e95fa7ff9460ff81ceb1dec1984b61
Cluster size: [2, 2]
dtest

Having 2 DC's, when replacing node in dc2 data is not transferred during node bootstrap (RBNO enabled, but it behaves the same for streaming). In logs we can see:
```
INFO  2022-04-01 16:04:38,176 [shard 0] repair - replace_with_repair: started with keyspace=ks, source_dc=1, nr_ranges=0, ignore_nodes=[]                                                                                                    │
INFO  2022-04-01 16:04:38,176 [shard 0] repair - replace_with_repair: finished with keyspace=ks, source_dc=1, nr_ranges=0   
```

Looks `source_dc` is not a valid name of any dc and no data transfer is initiated.

This was found when adding new test: https://github.com/scylladb/scylla-dtest/pull/2676/files

**Comment by slivne** [comment]
@soyacz to try and reproduce

Can you pleas provide the full schema

and also provide the nodetool status

if there is a dtest reproducing this (can you please reference it - even if its a pull request)

**Comment by asias** [comment]
I already looked at this issue and asked @soyacz  to create this issue. The snitch returned wrong dc name. 

```

static sstring get_local_dc() {
    return locator::i_endpoint_snitch::get_local_snitch_ptr()->get_datacenter(
            utils::fb_utilities::get_broadcast_address());
}

```

**Comment by soyacz** [comment]
It's not an issue - problem was with test - `dc=1` for the new node, but should be `dc="dc2"`.
We use by-index dc reference in SCT, in dtest it's by-name.
