### ISSUE TITLE
enterprise 2021.1 - scylla_raid_setup: failed due to the "mdmonitor.service: Failed with result 'protocol'" 

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla#10350]
## Installation details

Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade-2022-1-centos-8-db-node-7b8524d0-0-4 (34.138.102.92 | 10.142.0.166) (shards: 8)
- rolling-upgrade-2022-1-centos-8-db-node-7b8524d0-0-3 (34.74.134.182 | 10.142.0.138) (shards: 8)
- rolling-upgrade-2022-1-centos-8-db-node-7b8524d0-0-2 (34.139.7.240 | 10.142.0.112) (shards: 8)
- rolling-upgrade-2022-1-centos-8-db-node-7b8524d0-0-1 (34.73.247.104 | 10.142.0.106) (shards: 8)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-stream-8` (gce: eu-west-1)

Test: `rolling-upgrade-centos8-test`

Test id: `7b8524d0-0928-4df4-af53-fba82ba513e6`

Test name: `rolling-upgrade/rolling-upgrade-centos8-test`

Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/30eac57a39e2a0884e2d8f82dec1d9023d9e4ec9/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

>>>>>>>
Looks https://github.com/scylladb/scylla/issues/9540 is back.
It happens in 2021.1 on GCE.

```
2022-04-07 19:40:55.512: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=23a0c34e-b0f3-4d11-9924-bd56c7aa6b8c, source=UpgradeTest.SetUp()
exception=[Node rolling-upgrade-2022-1-centos-8-db-node-7b8524d0-0-1 [34.73.247.104 | 10.142.0.106] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1,/dev/nvme0n2,/dev/nvme0n3 --no-io-setup  --swap-directory / '
Exit code: 1
Stdout:
=                       reflink=1    bigtime=0 inobtcount=0
data     =                       bsize=4096   blocks=294812928, imaxpct=5
=                       sunit=256    swidth=768 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=143951, version=2
=                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
/dev/md0 will be used to setup a RAID
Creating RAID0 for scylla using 3 disk(s): /dev/nvme0n1,/dev/nvme0n2,/dev/nvme0n3
RAID setup failed.
Stderr:
Job for mdmonitor.service failed because a timeout was exceeded.
See "systemctl status mdmonitor.service" and "journalctl -xe" for details.
Traceback (most recent call last):
File "/opt/scylladb/scripts/libexec/scylla_raid_setup", line 205, in <module>
md_service.start()
File "/opt/scylladb/scripts/scylla_util.py", line 775, in start
return run('systemctl {} start {}'.format(self.ctlparam, self._unit), shell=True, check=True)
File "/opt/scylladb/python3/lib64/python3.8/subprocess.py", line 516, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'systemctl  start mdmonitor.service' returned non-zero exit status 1.
Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 3495, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4199, in node_setup
self._scylla_post_install(node, install_scylla, nic_devname)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 4275, in _scylla_post_install
node.scylla_setup(disks, devname)
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 113, in inner
res = func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2233, in scylla_setup
self.remoter.run('sudo /usr/lib/scylla/scylla_setup --nic {} --disks {} --no-io-setup {}'
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run
result = _run()
File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 64, in inner
return func(*args, **kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run
return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1,/dev/nvme0n2,/dev/nvme0n3 --no-io-setup  --swap-directory / '
Exit code: 1
Stdout:
=                       reflink=1    bigtime=0 inobtcount=0
data     =                       bsize=4096   blocks=294812928, imaxpct=5
=                       sunit=256    swidth=768 blks
naming   =version 2              bsize=4096   ascii-ci=0, ftype=1
log      =internal log           bsize=4096   blocks=143951, version=2
=                       sectsz=4096  sunit=1 blks, lazy-count=1
realtime =none                   extsz=4096   blocks=0, rtextents=0
/dev/md0 will be used to setup a RAID
Creating RAID0 for scylla using 3 disk(s): /dev/nvme0n1,/dev/nvme0n2,/dev/nvme0n3
RAID setup failed.
Stderr:
Job for mdmonitor.service failed because a timeout was exceeded.
See "systemctl status mdmonitor.service" and "journalctl -xe" for details.
Traceback (most recent call last):
File "/opt/scylladb/scripts/libexec/scylla_raid_setup", line 205, in <module>
md_service.start()
File "/opt/scylladb/scripts/scylla_util.py", line 775, in start
return run('systemctl {} start {}'.format(self.ctlparam, self._unit), shell=True, check=True)
File "/opt/scylladb/python3/lib64/python3.8/subprocess.py", line 516, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'systemctl  start mdmonitor.service' returned non-zero exit status 1.
                                            
```

<<<<<<<

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7b8524d0-0928-4df4-af53-fba82ba513e6`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7b8524d0-0928-4df4-af53-fba82ba513e6)
- Show all stored logs command: `$ hydra investigate show-logs 7b8524d0-0928-4df4-af53-fba82ba513e6`

## Logs:
- **db-cluster-7b8524d0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b8524d0-0928-4df4-af53-fba82ba513e6/20220407_194220/db-cluster-7b8524d0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b8524d0-0928-4df4-af53-fba82ba513e6/20220407_194220/db-cluster-7b8524d0.tar.gz)
- **monitor-set-7b8524d0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b8524d0-0928-4df4-af53-fba82ba513e6/20220407_194220/monitor-set-7b8524d0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b8524d0-0928-4df4-af53-fba82ba513e6/20220407_194220/monitor-set-7b8524d0.tar.gz)
- **loader-set-7b8524d0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b8524d0-0928-4df4-af53-fba82ba513e6/20220407_194220/loader-set-7b8524d0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b8524d0-0928-4df4-af53-fba82ba513e6/20220407_194220/loader-set-7b8524d0.tar.gz)
- **sct-runner-7b8524d0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7b8524d0-0928-4df4-af53-fba82ba513e6/20220407_194220/sct-runner-7b8524d0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7b8524d0-0928-4df4-af53-fba82ba513e6/20220407_194220/sct-runner-7b8524d0.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/rolling-upgrade/job/rolling-upgrade-centos8-test/4/)

**Comment by fgelcer** [comment]
wrong repo
