### ISSUE TITLE
Null or UNSET_VALUE subscript should generate an invalid request error

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10361]
If a user tries the to use "NULL" as a map index, e.g., `e` is a map column and one does
```
SELECT * FROM tag WHERE e[null] = 2 ALLOW FILTERING
```
Cassandra yields a InvalidRequest with the message "Unsupported null map value for column e", but Scylla currently yields an internal Server Error, with the message "std::get: wrong index for variant".

Reproduced by cql-pytest `test_null.py`::`test_map_subscript_null`, and also by translated Cassandra unit test `cassandra_tests/validation/operations/select_test.py`::`testFilteringWithoutIndicesWithCollections`

CC @cvybhu

**Comment by nyh** [comment]
I said above that Scylla *currently yields an internal Server Error, with the message "std::get: wrong index for variant"* but now that I ran the same reproducer again it doesn't generate any error and just silently matches nothing, and in #10399 it seems that we got a crash. So maybe there's some undefined behavior in the code that gets invoked.

**Comment by nyh** [comment]
By the way, we have exactly the same bug for UNSET_VALUE. I'll fix it too. And add a test for the subscript feature - that we didn't have.

**Comment by nyh** [comment]
I figured out why sometimes `test_null.py::test_map_subscript_null` got that internal error and sometimes it just silently returns nothing. That wasn't an undefined behavior but rather a question of whether the table had any data. When running  `test_null.py::test_map_subscript_null` alone, we have a filter on an empty table, so the filter is never called and the result is empty. When running the entire `test_null.py`, the test table is not empty and the filter needs to run - and its bugs are exposed.

One thing this suggests is that we need to recognize the null or unset_value in the expression as being wrong before we actually try to run this expression. It's not enough to recognize it when _running_ the filter... That makes things more difficult...

**Comment by nyh** [comment]
@cvybhu I just realized that the question of **when** to do the null check (there is no doubt it's needed and missing today, though...) is somewhat dependent on what we want to allow our expressions to support:
1. If subscripts are always constant, we can and should check it for being null before filtering out any data - and in particular recognize the error even if the result set is empty. Cassandra does this today - scanning an empty table with "WHERE m[null] = 3" prints an error.
2. If the subscripts could be expressions on their own, we can't check their nullness without data. For example if we were to support "WHERE m[a] = 3" where a is another column's value, we can't check if a is null before we know what a's value is for this specific row.

**Comment by nyh** [comment]
By the way, another non-crashing error we see in test_map_subscript_null when run with a non-empty table (i.e., when the full test file is run) instead of the usual ""std::get: wrong index for variant":
```
E   cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.17.230.140:9042 datacenter1>: <Error from server: code=0000 [Server error] message="marshaling error: read_simple_bytes - not enough bytes (requested 1610612784, got 40) Backtrace: 0x273729e 0x2737790 0x2737a98 0x159a53f 0x159a294 0x157b9b3 0x157b944 0x158ce2f 0x158febb 0x1561b5f 0x157a658 0x13533de 0x1353129 0x1352593 0x135224e 0x134f9bf 0x1345da1 0x1720cc5 0x1721238 0x1472b48 0x1472a30 0x1e01e72 0x1e016b0 0x1e01224 0x1e00572 0x1e00373 0x1e00219 0x1e000e8 0x1dfda77 0x1dfd8e2 0x25ff634 0x26008a7 0x2618ed5 0x25d88fd /lib64/libpthread.so.0+0x92a4 /lib64/libc.so.6+0x100322
```

**Comment by nyh** [comment]
Update:

After pull request https://github.com/scylladb/scylla/pull/10401, the weird errors mentioned above that can happen during expression evaluation ("std::get: wrong index for variant" or "marshaling error", or even crash of #10399) are gone, but we remain with the issue that a null or UNSET_VALUE subscript is silently ignored (the filter returns no rows) instead of causing an error. That pull request adds another test reproducing this bug - `test_filtering.py::test_filtering_with_subscript`.

As noted in comments in #10399, the current CQL expression implementation binds the expression during each valuation in a loop. Instead, we need a separate "bind" step that replaces bind markers by their constant values, and at that step we can also do various query validations - like forbidding null or unset_value in a subscript. Later we can evaluate the already-bound expression multiple times in a loop (and if the table is empty, this evaluation won't happen at all - but we will have done the validation already in the bind step).

By the way, Alternator expressions (alternator/expressions.*) have exactly the two-step process I described above: We start with a parsed expression, and then call a _resolve_ function (e.g., `resolve_update_expression()`) which does the Alternator equivalent of binds, and also validation. A filtering loop does the resolving once - and then evaluation multiple times (if needed).

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
