### ISSUE TITLE
db-node fails to boot after changing inter node compression to dc

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#10369]
## Installation details

Kernel Version: 5.11.0-1022-aws

Scylla version (or git commit hash): `4.7.dev-20220407.3e21fea2b` with build-id `d7c55eaaa9df57f9f445c73c5e983cae6ea272c3`

Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-master-db-node-b3620c0e-7 (34.245.201.23 | 10.0.0.175) (shards: 16)
- longevity-100gb-4h-master-db-node-b3620c0e-6 (34.244.177.105 | 10.0.3.82) (shards: 14)
- longevity-100gb-4h-master-db-node-b3620c0e-5 (34.249.73.247 | 10.0.3.25) (shards: 14)
- longevity-100gb-4h-master-db-node-b3620c0e-4 (54.246.30.55 | 10.0.0.64) (shards: 14)
- longevity-100gb-4h-master-db-node-b3620c0e-3 (34.247.191.182 | 10.0.2.202) (shards: 14)
- longevity-100gb-4h-master-db-node-b3620c0e-2 (18.203.111.131 | 10.0.3.165) (shards: 14)
- longevity-100gb-4h-master-db-node-b3620c0e-1 (52.214.162.91 | 10.0.2.72) (shards: 14)

OS / Image: `ami-06940ae9efa1017bb` (aws: eu-west-1)

Test: `longevity-100gb-4h-test`

Test id: `b3620c0e-dbb7-455a-9ab9-ea5585f4d963`

Test name: `longevity/longevity-100gb-4h-test`

Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/f3bc0a8d076b3829fdfb3178ba6203ee0c44ed34/test-cases/longevity/longevity-100gb-4h.yaml)

## Issue description

>>>>>>>

scenario: rolling change inter-node compression started on cluster nodes.
Then it changed node-3 which failed to boot up afterwards.
```
yarongilor@yaron-pc:~/Downloads/logs/sct-runner-b3620c0e$ egrep -i ' inter node compression to |Restarting node ' sct.log 
< t:2022-04-10 06:38:23,255 f:nemesis.py      l:700  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Changing Node longevity-100gb-4h-master-db-node-b3620c0e-2 [18.203.111.131 | 10.0.3.165] (seed: True) inter node compression to dc
< t:2022-04-10 06:38:33,466 f:nemesis.py      l:703  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Restarting node Node longevity-100gb-4h-master-db-node-b3620c0e-2 [18.203.111.131 | 10.0.3.165] (seed: True)
< t:2022-04-10 06:41:00,216 f:nemesis.py      l:700  c:sdcm.nemesis         p:DEBUG > sdcm.nemesis.SisyphusMonkey: Changing Node longevity-100gb-4h-master-db-node-b3620c0e-3 [34.247.191.182 | 10.0.2.202] (seed: True) inter node compression to dc
< t:2022-04-10 06:41:10,046 f:nemesis.py      l:703  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Restarting node Node longevity-100gb-4h-master-db-node-b3620c0e-3 [34.247.191.182 | 10.0.2.202] (seed: True)

```
SCT nemesis error details:
```


disrupt_rolling_config_change_internode_compression | longevity-100gb-4h-master-db-node-b3620c0e-2 | Failed | 2022-04-10 06:38:12 | 2022-04-10 07:02:42
-- | -- | -- | -- | --
Nemesis InformationClass: SisyphusName: disrupt_rolling_config_change_internode_compressionStatus: FailedDuration: 24 minutes, 30 secondsFailure reasonTraceback (most recent call last):   File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 61, in wait_for     res = retry(func, **kwargs)   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 404, in __call__     do = self.iter(retry_state=retry_state)   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 360, in iter     raise retry_exc.reraise()   File "/usr/local/lib/python3.10/site-packages/tenacity/__init__.py", line 194, in reraise     raise self tenacity.RetryError: RetryError[<Future at 0x7f27847f4040 state=finished returned bool>]  The above exception was the direct cause of the following exception:  Traceback (most recent call last):   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 3307, in wrapper     result = method(*args, **kwargs)   File "/home/ubuntu/scylla-cluster-tests/sdcm/nemesis.py", line 704, in disrupt_rolling_config_change_internode_compression     node.restart_scylla_server()   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2466, in restart_scylla_server     self.wait_db_up(timeout=timeout)   File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 1324, in wait_db_up     wait.wait_for(func=self.db_up, step=60, text=text, timeout=timeout, throw_exc=True)   File "/home/ubuntu/scylla-cluster-tests/sdcm/wait.py", line 72, in wait_for     raise RetryError(err) from ex tenacity.RetryError: RetryError[Wait for: Node longevity-100gb-4h-master-db-node-b3620c0e-3 [34.247.191.182 \| 10.0.2.202] (seed: True): Waiting for DB services to be up: timeout - 500 seconds - expired]


```

<<<<<<<

Restore Monitor Stack command: `$ hydra investigate show-monitor b3620c0e-dbb7-455a-9ab9-ea5585f4d963`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=master&test_id=b3620c0e-dbb7-455a-9ab9-ea5585f4d963](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dmaster%26test_id%3Db3620c0e-dbb7-455a-9ab9-ea5585f4d963&source=gmail-html&ust=1649949414720000&usg=AOvVaw2Ou4o6r7ScDJvEU4GCEGVq))
Show all stored logs command: `$ hydra investigate show-logs b3620c0e-dbb7-455a-9ab9-ea5585f4d963`

Test id: `b3620c0e-dbb7-455a-9ab9-ea5585f4d963`

Logs:
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_070357/grafana-screenshot-longevity-100gb-4h-test-scylla-per-server-metrics-nemesis-20220410_070627-longevity-100gb-4h-master-monitor-node-b3620c0e-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_070357/grafana-screenshot-longevity-100gb-4h-test-scylla-per-server-metrics-nemesis-20220410_070627-longevity-100gb-4h-master-monitor-node-b3620c0e-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_070357/grafana-screenshot-longevity-100gb-4h-test-scylla-per-server-metrics-nemesis-20220410_070627-longevity-100gb-4h-master-monitor-node-b3620c0e-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_070357/grafana-screenshot-longevity-100gb-4h-test-scylla-per-server-metrics-nemesis-20220410_070627-longevity-100gb-4h-master-monitor-node-b3620c0e-1.png)&source=gmail-html&ust=1649949414720000&usg=AOvVaw10RxcyhSDqppXYCuxlVIr0)
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_070357/grafana-screenshot-overview-20220410_070357-longevity-100gb-4h-master-monitor-node-b3620c0e-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_070357/grafana-screenshot-overview-20220410_070357-longevity-100gb-4h-master-monitor-node-b3620c0e-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_070357/grafana-screenshot-overview-20220410_070357-longevity-100gb-4h-master-monitor-node-b3620c0e-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_070357/grafana-screenshot-overview-20220410_070357-longevity-100gb-4h-master-monitor-node-b3620c0e-1.png)&source=gmail-html&ust=1649949414720000&usg=AOvVaw3BcqXJEzdsGFal8pTnNL_d)
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/db-cluster-b3620c0e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/db-cluster-b3620c0e.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/db-cluster-b3620c0e.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/db-cluster-b3620c0e.tar.gz)&source=gmail-html&ust=1649949414720000&usg=AOvVaw268ZmxBOSdBTKoLitbDJWs)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/loader-set-b3620c0e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/loader-set-b3620c0e.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/loader-set-b3620c0e.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/loader-set-b3620c0e.tar.gz)&source=gmail-html&ust=1649949414721000&usg=AOvVaw3pdi344Be6OqCP9MmuAj7u)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/monitor-set-b3620c0e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/monitor-set-b3620c0e.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/monitor-set-b3620c0e.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/monitor-set-b3620c0e.tar.gz)&source=gmail-html&ust=1649949414721000&usg=AOvVaw2DEfPQpzGItpanaa4_SeST)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/sct-runner-b3620c0e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/sct-runner-b3620c0e.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/sct-runner-b3620c0e.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/b3620c0e-dbb7-455a-9ab9-ea5585f4d963/20220410_071807/sct-runner-b3620c0e.tar.gz)&source=gmail-html&ust=1649949414721000&usg=AOvVaw3J_URlf7EYJKrJRUma2RTD)

[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-100gb-4h-test/452/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-100gb-4h-test/452/&source=gmail-html&ust=1649949414721000&usg=AOvVaw3kYVFvRLvVHr4jh8OVObUJ))

**Comment by slivne** [comment]
This is an issue of a 3 month old master - the same as https://github.com/scylladb/scylla/issues/10370

Please check why we have such a run closing as not fixed

**Comment by fgelcer** [comment]
> This is an issue of a 3 month old master - the same as #10370
> 
> Please check why we have such a run closing as not fixed

https://github.com/scylladb/scylla-pkg/issues/2856
