### ISSUE TITLE
Binary values of parameters with `type = 'restriction mode'` in table system.config

### ISSUE THREAD

**Issue by ilya-rarov** [scylladb/scylla#10373]
*Installation details*
Scylla version:  `5.0.rc2-0.20220316.839d9ef41`, build-id: `1319e7e64335b7e5c7531f773e92ef997b6c51ba`

There is a new virtual table `system.config` introduced in commit https://github.com/scylladb/scylla/commit/f74b25892828d03b0322d39ff32e92767f8051a7

There are a few parameters there that have `type = 'restriction mode'`. The values for those parameters are binary and they are not quite human-readable. For instance:
- `strict_allow_filtering`
```
cqlsh> select * from system.config where name = 'strict_allow_filtering';

 name                   | source  | type             | value
------------------------+---------+------------------+--------
 strict_allow_filtering | default | restriction mode | "\x02"

(1 rows)
```
- `restrict_dtcs`
```
(1 rows)
cqlsh> select * from system.config where name = 'restrict_dtcs';

 name          | source  | type             | value
---------------+---------+------------------+--------
 restrict_dtcs | default | restriction mode | "\x02"
```
- `restrict_replication_simplestrategy` by default has empty value which probably means `false`. But after update it turns into binary as well
```
cqlsh> select * from system.config where name = 'restrict_replication_simplestrategy';

 name                                | source  | type             | value
-------------------------------------+---------+------------------+-------
 restrict_replication_simplestrategy | default | restriction mode |    ""

(1 rows)
cqlsh> update system.config set value = 'warn' where name = 'restrict_replication_simplestrategy';
cqlsh> select * from system.config where name = 'restrict_replication_simplestrategy';

 name                                | source | type             | value
-------------------------------------+--------+------------------+--------
 restrict_replication_simplestrategy |    cql | restriction mode | "\x02"

(1 rows)
```

This issue was probably solved here: https://github.com/scylladb/scylla/issues/10047 (although, personally for me it looks a bit confusing that the values `false` are prelaced in table with `0` and `true` - with `1`, whereas the value `warn` stays as is). For instance in `5.1.dev-0.20220303.0544973b15dd` I have a different output:
```
cqlsh> select * from system.config where name = 'restrict_dtcs';

 name          | source  | type             | value
---------------+---------+------------------+--------
 restrict_dtcs | default | restriction mode | "warn"

(1 rows)
cqlsh> select * from system.config where name = 'restrict_replication_simplestrategy';

 name                                | source  | type             | value
-------------------------------------+---------+------------------+-------
 restrict_replication_simplestrategy | default | restriction mode |   "0"

(1 rows)
cqlsh> select * from system.config where name = 'strict_allow_filtering';

 name                   | source  | type             | value
------------------------+---------+------------------+--------
 strict_allow_filtering | default | restriction mode | "warn"

```
I think the fix for https://github.com/scylladb/scylla/issues/10047 should be backported to 5.0.

**Comment by avikivity** [comment]
@ilya-rarov is this a duplicate of #10047? If so, don't open a new issue when an existing one can be extended.

**Comment by ilya-rarov** [comment]
@avikivity since the fix for https://github.com/scylladb/scylla/issues/10047 highly probably solves this issue too, I think, yes, it can be considered as a dup. Closing this issue
