### ISSUE TITLE
raft: entry forwarding on non-voter may hang

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#10379]
A non-voter server may become a candidate when it considers the leader dead. It will immediately revert to follower state (because it's a non-voter) but the damage is done - it no longer knows who the leader is.

If the leader has no entries to send, because the logs are synced, the non-voter will not re-learn about the leader - there are no append_entries calls coming from the leader.

Trying to forward an entry from the non-voter at this point (by calling `add_entry` or `modify_config`, or even `read_barrier`) will hang, possibly indefinitely (until something happens in the cluster).

This has been observed in a real scenario, after recent changes on the `master` branch which moved `join_group0()` call earlier in the startup procedure, before `gossiper` is started:
1. Node A starts a cluster and becomes the leader of group 0.
2. Node B starts joining the cluster. It successfully joins group 0 as a non-voter.
3. Node B immediately considers node A dead, because `gossiper` is not started at this point yet, and `gossiper` is used for failure detection (the current implementation of `raft::failure_detector::is_alive` uses `gossiper::is_alive`).
4. Node B becomes a candidate, forgetting who the leader is.
5. Node B eventually tries to become a voter by calling `raft::server::modify_config`. The call blocks on `wait_for_leader`.
6. The bootstrap procedure is stuck.

The new failure detector (currently in review on mailing list) would "fix" the problem, because node B would immediately consider node A to be alive. But this depends on timing and while it may work in practice, it doesn't work in theory (it's incorrect).

A possible fix is for non-voters to not become candidate, instead of becoming candidate and them immediately returning to be follower as it happens now, OR remembering the old leader before becoming a candidate, and restoring it when returning to be a follower.

But one may consider this not to be a complete solution. One may argue that even if a server forgets the leader, forwarding should still be available; it could, for example, try to forward the entry to a random server in the cluster, probing for who the leader is instead of passively waiting.

**Comment by kbr-** [comment]
cc @kostja @gleb-cloudius

**Comment by avikivity** [comment]
Raft is experimental, not backporting.
