### ISSUE TITLE
scripts: not able to get perftune.py error message when capture_output=True

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#10390]
We currently does not able to get any error message from subprocess when we specified capture_output=True on subprocess.run().
This is because CalledProcessError does not print stdout/stderr when it raised, and we don't catch the exception, we just let python to cause Traceback.
Result of that, we only able to know exit status and failed command but not able to get stdout/stderr, like this:
```
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_sysconfig_setup", line 73, in <module>
    res = run('{} --tune net --nic {} --get-cpu-mask'.format(perftune_base_command(), ifname), shell=True, check=True, capture_output=True, encoding='utf-8').stdout
  File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/opt/scylladb/scripts/perftune.py --tune disks --dir /var/lib/scylla/data --dir /var/lib/scylla/commitlog --dir /var/lib/scylla/hints --dir /var/lib/scylla/view_hints --tune net --nic eth0 --get-cpu-mask' returned non-zero exit status 1.
```

This is problematic especially working on perftune.py bug, since the script should caused Traceback but we never able to see it (we suffer such problem on #10367).

To resolve this, I guess we should add wrapper function for capture output, and print stdout/stderr with error message inside the function.

**Comment by mykaul** [comment]
If it should **not** be backported to 5.0, I think we can remove the 'backport candidate' label from it.
