### ISSUE TITLE
streaming: Allow drop table during streaming

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#10395]
Currently, if a table is dropped during streaming, the streaming would
fail with no_such_column_family error.

Since the table is dropped anyway, it makes more sense to ignore the
streaming result of the dropped table, whether it is successful or
failed.

This allows users to drop tables during node operations, e.g., bootstrap
or decommission a node.

This is especially useful for the cloud users where it is hard to
coordinate between a node operation by admin and user cql change.

**Comment by avikivity** [comment]
Although important, it's not a regression and it is possible to recover (by redoing the operation). So not backporting.
