### ISSUE TITLE
[Fedora RPM] Failure to start scylla service

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#1040]
The daily RPM smoke test failed - after installing the RPM, starting the scylla service failed because `scylla-io-setup.service` timed out.

    14:13:38 process          L0275 INFO | Running 'systemctl start scylla-server.service'
    14:43:39 process          L0362 DEBUG| [stderr] A dependency job for scylla-server.service failed. See 'journalctl -xe' for details.
    14:43:39 service          L0369 DEBUG| Command: systemctl start scylla-server.service
    Exit status: 1
    Duration: 1800.20963311
    Stdout:

    Stderr:
    A dependency job for scylla-server.service failed. See 'journalctl -xe' for details.

The trimmed output of 'journalctl -xe' is:

    15:13:50 process          L0275 INFO | Running 'journalctl -xe'
    15:13:50 process          L0362 DEBUG| [stdout] -- Logs begin at Mon 2016-03-07 10:14:37 EST, end at Mon 2016-03-14 15:13:50 EDT. --
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:06:13 atest-guest collectd[12600]: Available write targets: [none]
    ... LOTS OF IDENTICAL MESSAGES FROM COLLECTD ...
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:12:09 atest-guest dnf[13883]: cachedir: /var/cache/dnf
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:12:10 atest-guest dnf[13883]: Loaded plugins: builddep, config-manager, copr, playground, debuginfo-install, download, generate_completion_cache, needs-restarting, noroot, protected_packages, Query, reposync
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:12:11 atest-guest dnf[13883]: DNF version: 1.1.6
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:12:11 atest-guest dnf[13883]: Making cache files for all metadata files.
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:12:11 atest-guest dnf[13883]: scylla: will expire after 167951 seconds.
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:12:11 atest-guest dnf[13883]: fedora: will expire after 167952 seconds.
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:12:11 atest-guest dnf[13883]: updates: will expire after 16794 seconds.
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:12:11 atest-guest dnf[13883]: scylla-generic: will expire after 168125 seconds.
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:12:13 atest-guest collectd[12600]: Available write targets: [none]
    ... LOTS OF IDENTICAL MESSAGES FROM COLLECTD ...
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:12:29 atest-guest dnf[13883]: repo: using cache for: scylla-generic
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:12:29 atest-guest dnf[13883]: not found updateinfo for: Scylla for Fedora
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:12:29 atest-guest dnf[13883]: Metadata cache created.
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:12:30 atest-guest systemd[1]: Started dnf makecache.
    ....
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:13:39 atest-guest systemd[1]: scylla-io-setup.service start operation timed out. Terminating.
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:13:39 atest-guest systemd[1]: Failed to start Scylla IO Setup.
    15:13:50 process          L0362 DEBUG| [stdout] -- Subject: Unit scylla-io-setup.service has failed
    15:13:50 process          L0362 DEBUG| [stdout] -- Defined-By: systemd
    15:13:50 process          L0362 DEBUG| [stdout] -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    15:13:50 process          L0362 DEBUG| [stdout] -- 
    15:13:50 process          L0362 DEBUG| [stdout] -- Unit scylla-io-setup.service has failed.
    15:13:50 process          L0362 DEBUG| [stdout] -- 
    15:13:50 process          L0362 DEBUG| [stdout] -- The result is failed.
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:13:39 atest-guest systemd[1]: Dependency failed for Scylla Server.
    15:13:50 process          L0362 DEBUG| [stdout] -- Subject: Unit scylla-server.service has failed
    15:13:50 process          L0362 DEBUG| [stdout] -- Defined-By: systemd
    15:13:50 process          L0362 DEBUG| [stdout] -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    15:13:50 process          L0362 DEBUG| [stdout] -- 
    15:13:50 process          L0362 DEBUG| [stdout] -- Unit scylla-server.service has failed.
    15:13:50 process          L0362 DEBUG| [stdout] -- 
    15:13:50 process          L0362 DEBUG| [stdout] -- The result is dependency.
    15:13:50 process          L0362 DEBUG| [stdout] Mar 14 15:13:39 atest-guest systemd[1]: Dependency failed for Scylla JMX.
    15:13:50 process          L0362 DEBUG| [stdout] -- Subject: Unit scylla-jmx.service has failed
    15:13:50 process          L0362 DEBUG| [stdout] -- Defined-By: systemd
    15:13:50 process          L0362 DEBUG| [stdout] -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    15:13:50 process          L0362 DEBUG| [stdout] -- 
    15:13:50 process          L0362 DEBUG| [stdout] -- Unit scylla-jmx.service has failed.
    15:13:50 process          L0362 DEBUG| [stdout] -- 
    15:13:50 process          L0362 DEBUG| [stdout] -- The result is dependency.

We really have a huge amount of the same message from collectd. I'm guessing we are not configuring collectd correctly in our service files.

So, the conclusion here is that scylla-io-setup.service is not finishing up in the allocated time, causing the startup to fail. Curiously, the next test tries to start the service once again, and this time the service startup works and the rest of the test finishes up with PASS. I'll start to add the logs of scylla-io-setup.service to the logs of our artifact tests and cluster tests.

**Comment by lmr** [comment]
I started to look at the scylla-io-setup.service file:

https://github.com/scylladb/scylla/blob/master/dist/redhat/systemd/scylla-io-setup.service

And indeed we have a timeout of 1800 seconds here. Looking at the script executed by this service:

https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_io_setup

I notice it grabs information from a certain IP address, 169.254.169.254. I can't ping this machine from my laptop, so I'm roughly guessing this is only accessible from AWS or something.

@syuu1228 and @slivne, from what I gather so far this setup is not generic enough to cover use cases other than AMIs. We also need to review the explicit timeout put on the service - slower machines such as test VMs might not be able to honor the 1800 second time out.

@glommer, I'm copying you so you're aware of the issue.

**Comment by slivne** [comment]
1. Do we have enough disk space on the vm to run iotune the current code
needs 10 gb

2.
On Mar 14, 2016 11:55 PM, "Lucas Meneghel Rodrigues" <
notifications@github.com> wrote:
>
> I started to look at the scylla-io-setup.service file:
>
>
https://github.com/scylladb/scylla/blob/master/dist/redhat/systemd/scylla-io-setup.service
>
> And indeed we have a timeout of 1800 seconds here. Looking at the script
executed by this service:
>
>
https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_io_setup
>
> I notice it grabs information from a certain IP address, 169.254.169.254.
I can't ping this machine from my laptop, so I'm roughly guessing this is
only accessible from AWS or something.

Thats an aws service that provides instance information yet i yhink we havr
atest before running this trying to detect if we are on aws takuya ?

if there is no result then it will run iotune ...

If at all the linit for 30 minutes is to large we need to finish this in 5
minutes max (and preferably in 2 if possible)

Any new user testing us out and trying to start scylla on a vm will not
wait 30 minutes

>
> @syuu1228 and @slivne, from what I gather so far this setup is not
generic enough to cover use cases other than AMIs. We also need to review
the explicit timeout put on the service - slower machines such as test VMs
might not be able to honor the 1800 second time out.

**Comment by slivne** [comment]
Lucas

the sanity test from a day or two before on head did pass (
http://jenkins.cloudius-systems.com:8080/job/scylla-rpm-test/150/parameters/)
what is the difference ?

**Comment by avikivity** [comment]
The test should complete within a few minutes, regardless of disk speed.  It is probably hung.

Can you rerun iotune manually on the same machine?

**Comment by slivne** [comment]
In previous runs it passed - we need to understand what happend

and we need to limit iotune to X minutes (X should 4 to 5 minutes probably
not more then that)

**Comment by avikivity** [comment]
For some reason the test runs on a VM image that is hosted on NFS (`/home/f22-64.qcow2`).  If the NFS server is heavily loaded, we won't get reasonable results.

Need to run the test on local storage.

**Comment by slivne** [comment]
It is on /home because he ran out of local disk space on muninn ... ok will
try to clear some old "OSV" items of its local disks.

**Comment by slivne** [comment]
Luca muninn does not seem to have an additional local disk  - huginn has
how hard would it be to seitch to it ?

**Comment by lmr** [comment]
@avikivity the VM is on an image hosted on NFS because that was the only place I could find disk space (all the images had to be resized to accomodate the new iotune disk requirements, making muninn to run out of space).

**Comment by lmr** [comment]
@slivne I guess we can move to huginn, I need to do all libvirt setup shenanigans, change the job configuration and re-test. I think it should take 2-3 hours on a rough estimate.

**Comment by avikivity** [comment]
Please relocate the tests to huginn which has a 1TB disk.  Also, we can mount the data directory from a separate, transient volume, no need to keep it in the image.

**Comment by lmr** [comment]
I'm closing this as we traced the issue back to a slow root disk over NFS.
