### ISSUE TITLE
Data management tool? 

### ISSUE THREAD

**Issue by delgec** [scylladb/scylla#10400]
Hello everyone

Is there a data management tool? I looked the DataGrip and DBeaver but I didn't find it. 

Are you using any data management tool?

Thanks

**Comment by nyh** [comment]
Please use the Scylla developers mailing list (scylladb-dev at googlegroups.com) or Scylla's user slack channel, or stackoverflow for questions. or discussions This is a bug tracker, for reporting bugs or features that you know that are missing.
