### ISSUE TITLE
Scylla 4.6 size_tiered_compaction_strategy estimated_remaining_tasks remains above 0

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10418]
Seen since https://jenkins.scylladb.com/job/scylla-4.6/job/dtest-release/41/testReport/junit/resharding_test/ReshardingTombstones_with_TimeWindowCompactionStrategy/disable_tombstone_removal_during_reshard_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-4.6/dtest-release/scylla-dtest/resharding_test.py", line 274, in disable_tombstone_removal_during_reshard_test
    node1.wait_for_compactions()
  File "/jenkins/workspace/scylla-4.6/dtest-release/scylla-ccm/ccmlib/node.py", line 761, in wait_for_compactions
    raise TimeoutError(f"Waiting for compactions timed out after {idle_timeout} seconds with {pending_tasks} pending tasks remaining.")
ccmlib.node.TimeoutError: Waiting for compactions timed out after 300 seconds with 1 pending tasks remaining.
```

Before that the test passed regularly but in 1 hour so I suspect this is a false positive...

**Comment by slivne** [comment]
I don't really understand is this only in 4.6 branch ? 
- if the bug is in master we merge first to master and then backport
- the patch should have a clear note which are the effected branches.

**Comment by slivne** [comment]
@bhalevy ^^

**Comment by bhalevy** [comment]
I'm not sure exactly how, but the problem isn't manifested by this dtest in 5.0 or master, only in 4.6.
I presume it's related to the change in compaction_manager to use table state rather than table&, but I couldn't isolate the exact change or set of changes that fixed the symptom in 5.0.

That said, the fix makes sense and applies to master so it better be fixed there and backported, even if it's not strictly needed in master (5.1) or 5.0, so I it isn't worth the effort to understand which patches exactly cover up for this, since we can just apply this patch safely on master and older branches.

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please backport 01f41630a50ea7abaf59b7445c5a597dbe665e0b to 5.0 and 4.6

**Comment by bhalevy** [comment]
@scylladb/scylla-maint ping

**Comment by bhalevy** [comment]
> @scylladb/scylla-maint please backport [01f4163](https://github.com/scylladb/scylla/commit/01f41630a50ea7abaf59b7445c5a597dbe665e0b) to 5.0 and 4.6

@scylladb/scylla-maint ping

**Comment by denesb** [comment]
Backported to 4.6 and 5.0.

**Comment by bhalevy** [comment]
Issue can be closed now that the backport is done.
