### ISSUE TITLE
scylla_prepare fails when SET_NIC_AND_DISKS != "yes" and other tuning options are involved

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylla#10412]
**Installation details**
Scylla version (or git commit hash): 4.6.2-0.20220405.eb372d7f0
Cluster size: 1
OS: Ubuntu 20.04

**Description**
It looks like that we reference the `nic` variable within [scylla_prepare](https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_prepare#L71) even when `SET_NIC_AND_DISKS` is different than `yes`, which - in turn - cause such weird failures upon execution:

```shell
# grep SET_NIC /etc/default/scylla-server
SET_NIC_AND_DISKS="no"
# sudo /opt/scylladb/scripts/scylla_prepare 
Exception occurred while creating perftune.yaml: local variable 'nic' referenced before assignment
To fix the error, please re-run scylla_setup.
```

The only way to get the exception is by having other relevant tuning options turned on, such as `SET_CLOCKSOURCE` or `DISABLE_WRITEBACK_CACHE` enabled.

A possible solution, rather than calling `--tune net`  just to determine the CPU mode (which doesn't make any sense), would be to call perftune with the `--tune system`, which would result into the same effect (eg: Retrieving perftune's expected cpumask for each mode).

**Comment by fee-mendes** [comment]
cc @syuu1228

**Comment by avikivity** [comment]
@syuu1228 does 5.0 need this? It doesn't backport cleanly.

I see it was reported for 4.6, so probably yes.

**Comment by avikivity** [comment]
@syuu1228 ping
