### ISSUE TITLE
52747 "Too many in flight hints" cassandra-stress errors

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#10429]
## Installation details

Kernel Version: 5.13.0-1017-aws
Scylla version (or git commit hash): `5.0~rc2-20220316.839d9ef41` with build-id `1319e7e64335b7e5c7531f773e92ef997b6c51ba`
Cluster size: 5 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-mv-si-4d-5-0-db-node-1bb24db5-9 (13.53.124.99 | 10.0.1.97) (shards: 14)
- longevity-mv-si-4d-5-0-db-node-1bb24db5-8 (13.53.182.167 | 10.0.3.104) (shards: 16)
- longevity-mv-si-4d-5-0-db-node-1bb24db5-7 (13.49.57.218 | 10.0.0.91) (shards: 16)
- longevity-mv-si-4d-5-0-db-node-1bb24db5-6 (13.48.48.253 | 10.0.2.228) (shards: 16)
- longevity-mv-si-4d-5-0-db-node-1bb24db5-5 (13.51.13.220 | 10.0.0.252) (shards: 14)
- longevity-mv-si-4d-5-0-db-node-1bb24db5-4 (13.51.6.96 | 10.0.2.220) (shards: 14)
- longevity-mv-si-4d-5-0-db-node-1bb24db5-3 (13.53.127.249 | 10.0.1.79) (shards: 14)
- longevity-mv-si-4d-5-0-db-node-1bb24db5-2 (13.48.70.136 | 10.0.3.116) (shards: 14)
- longevity-mv-si-4d-5-0-db-node-1bb24db5-12 (13.49.76.247 | 10.0.1.6) (shards: 16)
- longevity-mv-si-4d-5-0-db-node-1bb24db5-11 (13.49.225.200 | 10.0.1.230) (shards: 16)
- longevity-mv-si-4d-5-0-db-node-1bb24db5-10 (16.171.60.60 | 10.0.0.215) (shards: 14)
- longevity-mv-si-4d-5-0-db-node-1bb24db5-1 (13.48.45.91 | 10.0.3.173) (shards: 14)

OS / Image: `ami-088d9111d729684f8` (aws: eu-north-1)

Test: `longevity-mv-si-4days-test`
Test id: `1bb24db5-ff03-42fb-b3c5-595d885b91f2`
Test name: `scylla-5.0/longevity/longevity-mv-si-4days-test`
Test config file(s):

- [longevity-mv-si-4days.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/234f79a81bc97d0e44c3ab51441017b646fdf393/test-cases/longevity/longevity-mv-si-4days.yaml)

## Issue description

First time "Too many in flight hints" received when Scylla was restarted with resharding on the one node. 
```
[2022-03-18T04:50:17.407Z] < t:2022-03-18 04:50:16,271 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-03-18 04:50:16.269: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=50b9b257-484a-4f68-bddc-c4861a5837b9: nemesis_name=RestartWithResharding target_node=Node longevity-mv-si-4d-5-0-db-node-1bb24db5-9 [13.53.124.99 | 10.0.1.97] (seed: False)
[2022-03-18T04:52:53.504Z] < t:2022-03-18 04:52:53,098 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-03-18 04:52:53.096: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=be1a98f5-e445-4057-b3c7-c7cc19d969b5: type=TooManyHintsInFlight regex=Too many hints in flight|Too many in flight hints line_number=47064 node=Node longevity-mv-si-4d-5-0-loader-node-1bb24db5-2 [16.170.223.89 | 10.0.1.162] (seed: False)
[2022-03-18T04:52:53.504Z] < t:2022-03-18 04:52:53,098 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > com.datastax.driver.core.exceptions.OverloadedException: Queried host (10.0.3.116/10.0.3.116:9042) was overloaded: Too many in flight hints: 10495797
```

Next time it happened during `RepairStreamingErr` when node was restarted and running repair:
```
[2022-03-18T06:29:51.528Z] < t:2022-03-18 06:29:51,071 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-03-18 06:29:51.067: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=dc8ef00e-33e7-429e-9f3d-ac08f43b2330: nemesis_name=RepairStreamingErr target_node=Node longevity-mv-si-4d-5-0-db-node-1bb24db5-2 [13.48.70.136 | 10.0.3.116] (seed: False)
[2022-03-18T06:37:58.288Z] < t:2022-03-18 06:37:56,060 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-03-18 06:37:56.058: (CassandraStressLogEvent Severity.ERROR) period_type=one-time even
t_id=1612c80a-64eb-4bf0-8dfd-775e806e1b7c: type=TooManyHintsInFlight regex=Too many hints in flight|Too many in flight hints line_number=129799 node=Node longevity-mv-si-4d-5-0-loader-node-1bb24db5-1 [13.53.152.
88 | 10.0.0.151] (seed: False)
```

Another example: when new node is added and full scan on the view was started
```
[2022-03-19T02:23:29.910Z] < t:2022-03-19 02:23:29,655 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-03-19 02:23:29.650: (DisruptionEvent Severity.NORMAL) period_type=begin event_id=54381dd6-0d1d-4b00-9931-d08cfae0da57: nemesis_name=TerminateAndReplaceNode target_node=Node longevity-mv-si-4d-5-0-db-node-1bb24db5-6 [13.48.48.253 | 10.0.2.228] (seed: False)
[2022-03-19T02:28:47.009Z] < t:2022-03-19 02:28:46,868 f:nemesis.py      l:899  c:sdcm.nemesis         p:INFO  > sdcm.nemesis.SisyphusMonkey: Adding new node to cluster...
[2022-03-19T02:31:21.431Z] < t:2022-03-19 02:31:19,796 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-03-19 02:31:19.794: (FullScanEvent Severity.NORMAL) period_type=begin event_id=4b21be9b-a42f-421a-a87e-7d16781073c3 node=longevity-mv-si-4d-5-0-db-node-1bb24db5-3 select_from=sec_index.users_first_name_ind_index
[2022-03-19T02:31:42.107Z] < t:2022-03-19 02:31:39,085 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-03-19 02:31:39.083: (CassandraStressLogEvent Severity.ERROR) period_type=one-time event_id=cf5919ff-e387-45f9-ab56-2730c51dc041: type=TooManyHintsInFlight regex=Too many hints in flight|Too many in flight hints line_number=632354 node=Node longevity-mv-si-4d-5-0-loader-node-1bb24db5-2 [16.170.223.89 | 10.0.1.162] (seed: False)
```

There are 52747 errors.

- Restore Monitor Stack command: `$ hydra investigate show-monitor 1bb24db5-ff03-42fb-b3c5-595d885b91f2`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=1bb24db5-ff03-42fb-b3c5-595d885b91f2)
- Show all stored logs command: `$ hydra investigate show-logs 1bb24db5-ff03-42fb-b3c5-595d885b91f2`

## Logs:
The logs were not collected.
Console output:
https://s3.console.aws.amazon.com/s3/object/cloudius-jenkins-test?region=us-east-1&prefix=1bb24db5-ff03-42fb-b3c5-595d885b91f2/mv_si_4d_console_output.tar.gz

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-mv-si-4days-test/2/)

**Comment by slivne** [comment]
@piodul / @psarna 
I know we worked to improve hinted handoff replay - and I think its actually supposed to be better - need to validate this in this run and see that we see what we expect a 1M hints maybe ok if we are writing 10M op/sec - I doubt that).

@avelanarius 
We have constant issue with c-s and hints - and my concern is that this is also causing issue to customers we need to figure out best practices for customers (given that hinted handoff is actually working ok)

**Comment by juliayakovlev** [comment]
Reproduced in `2022.1.rc3`

19131 errors from cassndra-stress:
```
java.io.IOException: Operation x10 on key(s) [4b503239363830334e30]: Error executing: (OverloadedException): Queried host (10.0.1.153/10.0.1.153:9042) was overloaded: Too many in flight hints: 10485768
```


## Installation details

Kernel Version: 5.13.0-1021-aws
Scylla version (or git commit hash): `2022.1~rc3-20220406.5cc3b678c` with build-id `48dfae0735cd8efc4ae2f5c777beaee2a1e89f4a`
Cluster size: 3 nodes (i3.2xlarge)

Scylla Nodes used in this run:
- system-sla-2022-1-db-node-d1c7104e-3 (18.203.127.238 | 10.0.3.67) (shards: 8)
- system-sla-2022-1-db-node-d1c7104e-2 (34.250.44.179 | 10.0.1.153) (shards: 8)
- system-sla-2022-1-db-node-d1c7104e-1 (3.250.24.206 | 10.0.2.220) (shards: 8)


OS / Image: `ami-071c70d20f0fdbb2c` (aws: eu-west-1)

Test: `features-sla-read-throughput-1to5-ratio-test`
Test id: `d1c7104e-e3dc-4d89-8a5e-df8a9d98164a`
Test name: `enterprise-2022.1/SCT_Enterprise_Features/Workload_Prioritization/features-sla-read-throughput-1to5-ratio-test`
Test config file(s):

- [system-sla-test.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/26669988977199aa81816c32f017be68c3fc0dea/test-cases/features/system-sla-test.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor d1c7104e-e3dc-4d89-8a5e-df8a9d98164a`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d1c7104e-e3dc-4d89-8a5e-df8a9d98164a)
- Show all stored logs command: `$ hydra investigate show-logs d1c7104e-e3dc-4d89-8a5e-df8a9d98164a`

## Logs:
- **db-cluster-d1c7104e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/db-cluster-d1c7104e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/db-cluster-d1c7104e.tar.gz)
- **monitor-set-d1c7104e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/monitor-set-d1c7104e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/monitor-set-d1c7104e.tar.gz)
- **loader-set-d1c7104e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/loader-set-d1c7104e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/loader-set-d1c7104e.tar.gz)
- **sct-runner-d1c7104e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/sct-runner-d1c7104e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/sct-runner-d1c7104e.tar.gz)
- **parallel-timelines-report-d1c7104e.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/parallel-timelines-report-d1c7104e.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d1c7104e-e3dc-4d89-8a5e-df8a9d98164a/20220427_180518/parallel-timelines-report-d1c7104e.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/SCT_Enterprise_Features/job/Workload_Prioritization/job/features-sla-read-throughput-1to5-ratio-test/2/)
                            rc3

**Comment by roydahan** [comment]
@slivne why is it target to 5.1?

**Comment by slivne** [comment]
According to @roydahan this is a regression compared to 4.6 https://github.com/scylladb/scylla/issues/10146 (maybe a duplicate)

**Comment by slivne** [comment]
@piodul / @psarna - @eliransin is doing a bisect so we should have some answer as to what maybe causing this.

**Comment by soyacz** [comment]
Same happened on another run during remove_node_then_add_node.
In this nemesis we do:
```
1. Terminate node
2. Run full repair
3. Nodetool removenode
4. Add new node
5. Run nodetool cleanup (on each node) for each keyspace
```
On step 2 - full repair - it failed with errors:
```
< t:2022-05-03 18:21:29,020 f:base.py         l:146  c:RemoteLibSSH2CmdRunner p:ERROR > Error executing command: "/usr/bin/nodetool  repair "; Exit status: 2
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > sdcm.nemesis.SisyphusMonkey: failed to execute repair command on node Node longevity-100gb-4h-5-0-db-node-f1efb1f7-4 [44.204.114.198 | 10.0.3.245] (seed: False) due to the following error: Encountered a bad command exit code!
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > 
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > Command: '/usr/bin/nodetool  repair '
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > 
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > Exit code: 2
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > 
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > Stdout:
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > 
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > [2022-05-03 18:16:21,871] Starting repair command #1, repairing 1 ranges for keyspace system_traces (parallelism=SEQUENTIAL, full=true)
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > [2022-05-03 18:21:24,010] Repair session 1 failed
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > [2022-05-03 18:21:24,012] Repair session 1 finished
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > 
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > Stderr:
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > 
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > error: Repair job has failed with the error message: [2022-05-03 18:21:24,010] Repair session 1 failed
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > -- StackTrace --
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > java.lang.RuntimeException: Repair job has failed with the error message: [2022-05-03 18:21:24,010] Repair session 1 failed
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > 	at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > 	at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > 	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > 	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > 	at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > 	at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
< t:2022-05-03 18:21:29,021 f:nemesis.py      l:2529 c:sdcm.nemesis         p:ERROR > 
```
I saw in logs there are leftovers from previous truncate_large_partitions nemesis (which already should be truncated...) - so in this case we work also with large partitions.

Later in logs problems with too many inflight hints can be found.
## Installation details

Kernel Version: 5.13.0-1022-aws
Scylla version (or git commit hash): `5.0~rc3-20220503.3e98e17d1` with build-id `9bb31d710ed5084b792891adbae7c4144484501f`
Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-100gb-4h-5-0-db-node-f1efb1f7-7 (3.239.45.150 | 10.0.2.236) (shards: 14)
- longevity-100gb-4h-5-0-db-node-f1efb1f7-6 (3.233.222.200 | 10.0.0.237) (shards: 14)
- longevity-100gb-4h-5-0-db-node-f1efb1f7-5 (44.197.123.91 | 10.0.2.51) (shards: 14)
- longevity-100gb-4h-5-0-db-node-f1efb1f7-4 (44.204.114.198 | 10.0.3.245) (shards: 14)
- longevity-100gb-4h-5-0-db-node-f1efb1f7-3 (54.144.175.241 | 10.0.3.131) (shards: 14)
- longevity-100gb-4h-5-0-db-node-f1efb1f7-2 (3.235.1.198 | 10.0.3.155) (shards: 14)
- longevity-100gb-4h-5-0-db-node-f1efb1f7-1 (44.202.200.63 | 10.0.3.85) (shards: 14)


OS / Image: `ami-086343078ffe88520` (aws: us-east-1)

Test: `longevity-100gb-4h-test`
Test id: `f1efb1f7-5c18-4182-9211-599c0204a6d7`
Test name: `scylla-5.0/longevity/longevity-100gb-4h-test`
Test config file(s):

- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/62186fccc8ee0c02ba7e1ce6a10f12b8e358eabb/test-cases/longevity/longevity-100gb-4h.yaml)

## Issue description


- Restore Monitor Stack command: `$ hydra investigate show-monitor f1efb1f7-5c18-4182-9211-599c0204a6d7`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=f1efb1f7-5c18-4182-9211-599c0204a6d7)
- Show all stored logs command: `$ hydra investigate show-logs f1efb1f7-5c18-4182-9211-599c0204a6d7`

## Logs:
- **db-cluster-f1efb1f7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f1efb1f7-5c18-4182-9211-599c0204a6d7/20220503_204803/db-cluster-f1efb1f7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f1efb1f7-5c18-4182-9211-599c0204a6d7/20220503_204803/db-cluster-f1efb1f7.tar.gz)
- **monitor-set-f1efb1f7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f1efb1f7-5c18-4182-9211-599c0204a6d7/20220503_204803/monitor-set-f1efb1f7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f1efb1f7-5c18-4182-9211-599c0204a6d7/20220503_204803/monitor-set-f1efb1f7.tar.gz)
- **loader-set-f1efb1f7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f1efb1f7-5c18-4182-9211-599c0204a6d7/20220503_204803/loader-set-f1efb1f7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f1efb1f7-5c18-4182-9211-599c0204a6d7/20220503_204803/loader-set-f1efb1f7.tar.gz)
- **sct-runner-f1efb1f7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f1efb1f7-5c18-4182-9211-599c0204a6d7/20220503_204803/sct-runner-f1efb1f7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f1efb1f7-5c18-4182-9211-599c0204a6d7/20220503_204803/sct-runner-f1efb1f7.tar.gz)
- **parallel-timelines-report-f1efb1f7.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/f1efb1f7-5c18-4182-9211-599c0204a6d7/20220503_204803/parallel-timelines-report-f1efb1f7.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/f1efb1f7-5c18-4182-9211-599c0204a6d7/20220503_204803/parallel-timelines-report-f1efb1f7.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-100gb-4h-test/7/)

**Comment by DoronArazii** [comment]
@piodul @psarna 
Any progress with this issue?

**Comment by slivne** [comment]
This is probably the same as #10146

**Comment by slivne** [comment]
Dont do anything - we reverted the patches that caused the degradation  following that we will know if there is still and issue with MV/SI

**Comment by slivne** [comment]
@roydahan please ack that we are rerunning this test

**Comment by fgelcer** [comment]
> @roydahan please ack that we are rerunning this test

[last run](https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-100gb-4h-test/9/) with 5.0.rc5 passed without this issue

**Comment by slivne** [comment]
THANKS !!!!! - closing the issue
