### ISSUE TITLE
nodetool status return wrong value

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#1042]
On a single node testing, nodetool status has the following errors:
1. ignore the keyspace name:
2. the load is wrong, in the example the directory size is 178MB but the load report 1.73 TB
$ nodetool status keyspace1
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens  Owns    Host ID                               Rack
UN  10.102.137.189  1.73 TB    256     ?       2a2d4642-a824-4a93-8ed7-7520bfb08259  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
[centos@ip-10-102-137-189 cassandra]$ df -k
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/xvda1      10474496   2476100   7998396  24% /
devtmpfs        15341792         0  15341792   0% /dev
tmpfs           15220428         0  15220428   0% /dev/shm
tmpfs           15220428     16648  15203780   1% /run
tmpfs           15220428         0  15220428   0% /sys/fs/cgroup
/dev/md0       319548928 178635172 140913756  56% /var/lib/scylla
tmpfs            3044088         0   3044088   0% /run/user/1000

**Comment by amnonh** [comment]
I believe the root cause of the load issue is the migration.

Can it be that when moving Cassandra files each shared get the entire file as its own? and then the load is counted as multiplication between the file size and the number of shared.

After all the files where compacted the load is correct

**Comment by slivne** [comment]
there are indications this happens even if there are no shared sstables ...

**Comment by amnonh** [comment]
Is this only during migration phase?

**Comment by slivne** [comment]
no migration - there are no "shared sstables" any more - as far as I can
tell - so each shard owns its own sstables.

**Comment by slivne** [comment]
copying info from #1252 

On a 5 node cluster, the Space used (total) says it is 31GB while the cluster's load is 11GB from nodetool status.

Data is written with
cassandra-stress write cl=QUORUM duration=%sm "
"-schema 'replication(factor=3)' -port jmx=6868 "
"-mode cql3 native -rate threads=%s "
"-pop seq=1..10000000 -node %s

$ nodetool status
UN 172.30.0.42 3.22 GB 256 ? 08ae6f65-c339-420a-b1f4-5e5ee0d69ff4 rack1
UN 172.30.0.43 3.39 GB 256 ? dbc2bff3-af30-4a8c-b32f-c7becb347993 rack1
UN 172.30.0.136 1.91 GB 256 ? 8580213c-5a3a-4083-8109-9a625cade68b rack1
UN 172.30.0.41 2.81 GB 256 ? e21b68bd-1b9b-40c4-b832-7c4754c3858a rack1

$ nodetool cfstats keyspace1
Space used (live): 2 048 938 195
Space used (total): 31 997 017 045

$ pwd
/var/lib/scylla/data

$ sudo du -h keyspace1/
2.1G keyspace1/standard1-6ab64560164a11e6a4d0000000000001
2.1G keyspace1/

**Comment by amnonh** [comment]
The logic of total_disk_space_used in column_family stats is wrong, the counter is always being incremented, so it would grow indefinitely.

**Comment by tzach** [comment]
@nirmaayan do the customer still have this issue?
