### ISSUE TITLE
Truncating a table during memtable flush might trigger an assert failure in ~flush_memory_accounter

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10423]
While investigating #10421 and trying to reproduce it with a unit test I hit this issue where
https://github.com/scylladb/scylla/blob/bcd35af7cf93eac9664a044816847521cfddb0ac/replica/memtable.cc#L546-L548
is triggered when truncating a table while there are memtable flushes in the background.

**Comment by avikivity** [comment]
Backported to 4.5, 4.6, 5.0.
