### ISSUE TITLE
nodetool complains about malformed ipv6 addresses

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#10442]
[CASSANDRA-17581](https://issues.apache.org/jira/browse/CASSANDRA-17581)

**Comment by slivne** [comment]
@avikivity please backport - we are seeing users complaining

**Comment by avikivity** [comment]
Backported to 5.0, 4.6, 4.5.

**Comment by slivne** [comment]
for those that are not able to upgrade or hit this on older scylla releases - the workaround is to downgrade the java version
