### ISSUE TITLE
rpc_keepalive parameter is ignored

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1044]
config has an `rpc_keepalive` parameter, but we ignore it.

Since the default is true, we may as well respect it.

@gleb-cloudius

**Comment by gleb-cloudius** [comment]
On Tue, Mar 15, 2016 at 02:07:41AM -0700, Avi Kivity wrote:
> config has an `rpc_keepalive` parameter, but we ignore it.
> 
> Since the default is true, we may as well respect it.
> 
Is this parameter about inter node communication or thrift rpc?

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Tue, Mar 15, 2016 at 11:09:14AM +0200, Gleb Natapov wrote:
> On Tue, Mar 15, 2016 at 02:07:41AM -0700, Avi Kivity wrote:
> > config has an `rpc_keepalive` parameter, but we ignore it.
> > 
> > Since the default is true, we may as well respect it.
> > 
> Is this parameter about inter node communication or thrift rpc?
> 
Answering my own question looks like it is about client connection.

--
			Gleb.

**Comment by avikivity** [comment]
Right, so this is invalid.

**Comment by gleb-cloudius** [comment]
On Tue, Mar 15, 2016 at 02:13:21AM -0700, Avi Kivity wrote:
> Right, so this is invalid.
> 
We can still honor it for client connections.

--
			Gleb.

**Comment by avikivity** [comment]
We don't suppor thrift now.

**Comment by gleb-cloudius** [comment]
On Tue, Mar 15, 2016 at 02:17:42AM -0700, Avi Kivity wrote:
> We don't suppor thrift now.
> 
This is for both:

rpc_keepalive 
    (Default: true) Enable or disable keepalive on client connections (RPC or native). 

Never underestimate how confusing Cassandra naming can be.

--
			Gleb.

**Comment by avikivity** [comment]
It would make more sense for the client to enable keepalive than the server, too.

**Comment by gleb-cloudius** [comment]
On Tue, Mar 15, 2016 at 02:21:51AM -0700, Avi Kivity wrote:
> It would make more sense for the client to enable keepalive than the server, too.
> 
Totally agree.

--
			Gleb.
