### ISSUE TITLE
database::drop_column_family(): has a window where new queries can be created for the dropped cf

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#10450]
When such an entry expire, it will cause a crash because destroying the reader objects requires the table object to be around (which obviously isn't after the drop).
https://github.com/scylladb/scylla/blob/333fdcb3f544a6fc2ef3066e2ddbf1bde18cb7a1/replica/database.cc#L930-L936

Even though all querier cache entries related to the to-be-dropped table are removed by `database::remove()`, a read running concurrent to `database::drop_column_family()` can create a new querier, when said method yields to wait for ongoing operations.

**Comment by avikivity** [comment]
Backported to 4.5, 4.6, 5.0.
