### ISSUE TITLE
Off-by-one in formula used by LCS reshape to calculate ideal output level

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#10458]
LCS reshape uses the following formula to calculate target level for a given input set:

```
log base 10 (input_set_size / max_fragment_size)

where max_fragment_size == 160M by default

```

`input_set_size / max_fragment_size` calculates the # of fragments, but it can be missing the last fragment, if not filled up to max_fragment_size, therefore off-by-one.

It's unlikely to happen in real world, but it can happen under the following conditions:

1) input set for reshape has total size of 1650M.
2) 50M is missed from calculation, which should add to total # of fragments.
3) reshape decides the output should be placed in level 1 (because log base 10 of 10 == 1), but level 1 can only store 10 ^ 1 * 160M = 1600M.

Problem only happens when input size is exceeding level capacity by less than max_fragment_size. In example above, input size exceed level 1 capacity by 50M. Had it exceeded by 170M, level 2 would be correctly picked instead. With levels growing exponentially larger, this problem is less likely to happen on higher levels.

We're going to reuse the formula for LCS major (which currently picks the max seen level, therefore a fragile approach which can cause needless writeamp), making it even more important to have this fixed.

**Comment by avikivity** [comment]
Seems minor, not backporting.

**Comment by raphaelsc** [comment]
> Seems minor, not backporting.

Minor, indeed.
