### ISSUE TITLE
sstables mutation_reader constructors are too complicated

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#1048]
As most overly complicated things, it was also wrong. We have merged a fix for now in the form of 6a3872b35598321006c60151609b8213ec01eee5 for a SIGSEGV described in #1036, but the result is still not looking as good as it could.

We had a discussion about possible ways to start in the path of the right fix in [this thread](https://groups.google.com/d/msg/scylladb-dev/EkFM-mh7ppY/Qwb6NlD8DAAJ) in our mailing list.

**Comment by avikivity** [comment]
@glommer is this issue still valid?

**Comment by avikivity** [comment]
Improved by 6024ef5dad40a37afc11733832e465fe769dd45c.
