### ISSUE TITLE
compaction failed: invalid_mutation_fragment_stream

### ISSUE THREAD

**Issue by Cary4** [scylladb/scylla#10495]
*Installation details*
Scylla version: 4.4.8-0.20211215.9af2e5ead-4.5.5-0.20220328.c789a1819
Cluster size: 16
OS: Ubuntu-20.04

# Datacenter: Data LA.
Hardware details.
Platform: physical
Hardware: sockets=2 cores=24 hyperthreading=48 memory=128GB
Disks: 4 1TB SSD per node
# Datacenter: Data GC.
Hardware details.
Platform: VM
Hardware: sockets=1 cores=16 hyperthreading=32 memory=96GB
Disks: 16TB 375GB SSD
# Datacenter: Config LA.
Hardware details.
Platform: physical
Hardware: sockets=2 cores=16 hyperthreading=32 memory=64GB
Disks: 4 1TB SSD per node
# Datacenter: Config GC.
Hardware details.
Platform: VM
Hardware: sockets=1 cores=16 hyperthreading=32 memory=64GB
Disks: 2TB SSD

We are upgrading our Ubuntu-20.04 ScyllaDB-4.4.8 cluster.  We upgraded our LA config datacenter to 4.5.5 and started seeing failed compaction messages in the log:

scylla:  [shard 3] compaction_manager - compaction failed: invalid_mutation_fragment_stream ([validator 0x60200d85cb00 for sstable writer /var/lib/scylla/data/table_data/dnc_log-9d3fd5c0f1d311e8b2d6000000000003/md-49893-big-Data.db (table_data.dnc_log 9d3fd5c0-f1d3-11e8-b2d6-000000000003)] Unexpected token: previous -8029356301296426508, current -8029440654773605982): retrying

We then rolled back to 4.4.8 and ran a repair+compaction+cleanup on the whole cluster. After that we were able to update the GC and LA config datacenter to 4.5.5, but when we attempted to update the LA data datacenter we ran into the same issue.

From reading through these issues below:
https://github.com/scylladb/scylla/issues/9983
https://github.com/scylladb/scylla/issues/7552

It appears that [ef97adc](https://github.com/scylladb/scylla/commit/ef97adc72a0d5e8877885810b1a7e0fcbb11dc29) enabled unconditional token order validation, and that may be what is causing this issue.
```
Datacenter: gc-central1-config
==============================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns     Rack
UN  IP            1.07 TB    256          ?        rack3
UN  IP            1.13 TB    256          ?        rack1
UN  IP            1.25 TB    256          ?        rack2
Datacenter: gc-central1-data
============================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns     Rack
UN  IP            1.84 TB    256          ?        rack3
UN  IP            1.84 TB    256          ?        rack1
UN  IP            1.84 TB    256          ?        rack2
Datacenter: la1-config
======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns     Rack
UN  IP            1021.59 GB  256          ?       rack1
UN  IP            1.12 TB    256          ?        rack3
UN  IP            1.15 TB    256          ?        rack2
Datacenter: la1-data
====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns     Rack
UN  IP            1.2 TB     256          ?        rack3
UN  IP            1.23 TB    256          ?        rack2
UN  IP            1.24 TB    256          ?        rack3
UN  IP            799.35 GB  256          ?        rack1
UN  IP            848.44 GB  256          ?        rack1
UN  IP            1.21 TB    256          ?        rack2
UN  IP            839.22 GB  256          ?        rack1
```

**Comment by slivne** [comment]
We had an issue related to running repair in a mixed SMP count cluster (that you have also referenced) and I expect you probably hit that issue - did you run the cluster with version 4.2 / 4.3 and if so which patch releases ?

to fix this we need to scrub the sstables

**Comment by Cary4** [comment]
4.2.1-> 4.3.0 -> 4.3.2.
 Is there a process we should follow when scrubbing the sstables?

**Comment by slivne** [comment]
@bhalevy assigning this to you - need help on the documentation on how to scrub (without upgrading sstable version)

**Comment by bhalevy** [comment]
> @bhalevy assigning this to you - need help on the documentation on how to scrub (without upgrading sstable version)

@slivne what do you mean "without upgrading sstable version"?

It'd be best if the cluster is upgraded to 4.6 to use the latest released scrub code.

auto-compaction can be disabled to attenuate the annoying compaction error messages.
Then scrub can be run as follow, in VALIDATE mode, to detect which of the sstables is corrupt,
and/or in SEGREGATE mode to fix those out-of-order errors by segregating the out-of-order partitions/rows into new, valid sstables.

For example:
```
$ curl -X GET http://localhost:10000/storage_service/keyspace_scrub/<keyspace>?scrub_mode=VALIDATE
$ curl -X GET http://localhost:10000/storage_service/keyspace_scrub/<keyspace>?scrub_mode=SEGREGATE
```

After scrub runs in SEGREGATE mode, auto-compaction can be re-enabled in the keyspace.

**Comment by bhalevy** [comment]
> We disabled auto compaction on the tables causing problems, then updated from 4.4 to 4.5 then finally to 4.6 and then ran the the validate and segregate commands. Everything is working as expected now. Thank you for the assistance. :-)

@Cary4 glad we could help!

**Comment by d-mankowski-synerise** [comment]
We encountered the same issue and I can't find any information what is `nodetool scrub's` impact on node's/cluster's performance - maybe it would be a good idea to run `nodetool drain` first?

@bhalevy  - could you clarify that?
Thanks in advance!

**Comment by denesb** [comment]
> We encountered the same issue and I can't find any information what is `nodetool scrub`'s impact on node's/cluster's performance - maybe it would be a good idea to run `nodetool drain` first?
> 
> @bhalevy - could you clarify that? Thanks in advance!

You don't need to drain, but you do need to disable compaction before starting scrub (and re-enable afterwards).
Scrub is a kind of compaction and so its impact is similar to that of a regular compaction. It compacts all sstables one-by-one so it will be longer than a regular compaction (more akin to a major compaction).

**Comment by bhalevy** [comment]
> It compacts all sstables one-by-one so it will be longer than a regular compaction (more akin to a major compaction).

I'd say it's more similar to cleanup compaction that rewrites the sstables one at a time.
major compaction is doing more work as it iteratively compacts all sstables (or all at once if it can).

Note that is scrub is run first in VALIDATE mode, it'd move all the invalid sstables to the quarantine sub-directory,
to prevent compaction from further spreading the corruption around to new sstables.

Then, if scrub is invoked with `scrub_mode=SEGREGATE&quarantine_mode=ONLY`, it will only scrub the quarantined sstables (this is not the default - which is `INCLUDE` that scrubs everything), so the amount of data that will be rewritten is considerably reduced.

**Comment by d-mankowski-synerise** [comment]
Thank you for the explanation!

We had "quite" a lot of C++ exceptions when `nodetool scrub -m SEGREGATE` was running on the first node:

<img width="967" alt="image" src="https://user-images.githubusercontent.com/101267779/181506176-87a96d57-d9fc-4765-82a7-f139eea95a5c.png">

So, just in case, I wanted to drain the next node, but it turns out that scrub doesn't do anything then (drain -> disable compaction -> validate -> segregate), that is, both validate and segregate  took less than a minute on 800GB keyspace without printing any logs (and after restarting scylla, segregate took about an hour). Anyway, next nodes went fine, thanks again
