### ISSUE TITLE
seal_active_memtable may spin forever

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10498]
`table::seal_active_memtable` contains has a retry loop, in https://github.com/scylladb/scylla/blob/eeec502aee7a693ccaf84bbf4a4313350c1a26bd/replica/table.cc#L602-L614

The loop might spin forever if there is a "poison pill" in the memtable that would cause memtable flush to fail to write it into a sstable, and we currently have no way to recover from that.

For example, https://github.com/scylladb/scylla/issues/9853 causes 
```
table - failed to write sstable /var/lib/scylla/data/ks/cf-<uuid>/md-xyz-big-Data.db: std::runtime_error (last key of summary of /var/lib/scylla/data/ks/cf-<uuid>/md-xyz-big-Data.db is empty)
```
at https://github.com/scylladb/scylla/blob/eeec502aee7a693ccaf84bbf4a4313350c1a26bd/replica/table.cc#L721
which is swallowed there.

**Comment by bhalevy** [comment]
One option is to abort if we suspect that the write error is unrecoverable (*), since the commitlog replay already has logic to skip invalid records, and the core dump will contain a copy of the memtable for postmortem analysis.

(*) Or the other way around, ignore only errors such as std::bad_alloc, and isolate on any other error.

Alternatively, we may want to isolate the node if we suspect that the write error is unrecoverable
but I'm not sure what that would buy us. Also, issues like https://github.com/scylladb/scylla/issues/9853 might cause multiple nodes to get isolated and therefore will hamper the cluster availability.

**Comment by avikivity** [comment]
In these crazy situations it's better to lose availability than risk data loss.

**Comment by tgrabiec** [comment]
Related issue: https://github.com/scylladb/scylla/issues/4344

**Comment by avikivity** [comment]
@bhalevy tending not to backport. How common is the problem?

**Comment by bhalevy** [comment]
> @bhalevy tending not to backport. How common is the problem?

This is quite rare and usually restarting the node works around the issue,
unless the "poison pill" is restored from the commitlog.  That could happen in theory but I don't recall hitting it in practice.
In this case, we either have a deeper issue we need to solve, or the offending commitlog needs to be deleted too, risking some limited data loss.

That said, fixing this issue won't help the "poison pill" in commitlog case either.

**Comment by avikivity** [comment]
Not backporting per above.
