### ISSUE TITLE
3rd party utilities https://github.com/scylladb/scylla/wiki/3rd-party-utilities

### ISSUE THREAD

**Issue by scorpnode** [scylladb/scylla#1049]
Just a quick question..will the pliugin below and its search function work? Jiust since i noted secondary index isnt fully supported yet?

cassandra-lucene-index a plugin for Apache Cassandra that extends its index functionality to provide near real time search such as ElasticSearch or Solr

Thanks Brian

**Comment by tzach** [comment]
Thanks for pointing this out.
The list is for Cassandra tools, most was not yet tested with Scylla, just added some wording at the start to clarify this. Next we need to organize this list for supported / non  supported tools.

In particular, sec index are not supported yet, you can follow it here #401

**Comment by tzach** [comment]
I updated the [3rd party wiki page](https://github.com/scylladb/scylla/wiki/3rd-party-utilities), for project which are:
* known to work with Scylla
* known not to work with Scylla yet
* not tested with Scylla yet

comments are welcome
