### ISSUE TITLE
table::snapshot might hang if a shard hits an error

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10500]
We've seen snapshot hanging due to https://github.com/scylladb/scylla/issues/10498
Where one of the shards waits at https://github.com/scylladb/scylla/blob/eeec502aee7a693ccaf84bbf4a4313350c1a26bd/replica/table.cc#L1412
or, for that matter, at https://github.com/scylladb/scylla/blob/eeec502aee7a693ccaf84bbf4a4313350c1a26bd/replica/table.cc#L1390

while another shard if hanging, calling `flush` at https://github.com/scylladb/scylla/blob/eeec502aee7a693ccaf84bbf4a4313350c1a26bd/replica/table.cc#L1351-L1352

If flush returns an error future, or the following throws std::bad_alloc:
https://github.com/scylladb/scylla/blob/eeec502aee7a693ccaf84bbf4a4313350c1a26bd/replica/table.cc#L1372

or

https://github.com/scylladb/scylla/blob/eeec502aee7a693ccaf84bbf4a4313350c1a26bd/replica/table.cc#L1382

Synchronization won't work, and other shards will wait forever since the shard that hit the error will never signal the needed semaphore:

https://github.com/scylladb/scylla/blob/eeec502aee7a693ccaf84bbf4a4313350c1a26bd/replica/table.cc#L1386

or possibly to https://github.com/scylladb/scylla/blob/eeec502aee7a693ccaf84bbf4a4313350c1a26bd/replica/table.cc#L1404

**Comment by avikivity** [comment]
@bhalevy how do we evaluate this for a backport? It's a large change for a rare event, but the consequences are bad.

**Comment by bhalevy** [comment]
> @bhalevy how do we evaluate this for a backport? It's a large change for a rare event, but the consequences are bad.

We have suspected cases of hung snapshot operations in the field, but they are hard to tell due to lack of log error messages and/or a core dump.

The baseline of branch 5.0 is very similar to master so I think it shouldn't be too hard to backport it there in while.

For earlier branches I can prepare a simplified version that would just catch and handle errors in table::snapshot, if needed, even without turning it into a coroutine.

**Comment by avikivity** [comment]
The question is not if it's hard to backport or not, it's what the fallout will be.

**Comment by bhalevy** [comment]
With the simplified version I think the risk will be minimal since the change would be localized to table::snapshot which is well tested (for the good path) in dtests, and the gains would significant, preventing the silent hanging of snapshot operations.

**Comment by avikivity** [comment]
Well, let's see a patch. And it's better to start with the simplified version and apply refactoring later.

**Comment by avikivity** [comment]
Feels like it deserves a backport but it's quite a large change.

**Comment by bhalevy** [comment]
@avikivity according to https://github.com/scylladb/scylla-enterprise/pull/2238#issuecomment-1156203171
> Dequeued, branch is frozen for security fix

Can we re-queue it?
Or should it go through branch 5.0 instead?

**Comment by bhalevy** [comment]
Backport to 5.0/2022.1 and 2021.1 were done, removed label.
