### ISSUE TITLE
ReadTimeout when using local secondary index

### ISSUE THREAD

**Issue by cjbottaro** [scylladb/scylla#10514]
`scylladb/scylla:4.6.3` running on a Core i3-8100 machine as a "single node cluster".

```
CREATE TABLE sb.jobs (
    queue_id int,
    updated_at timeuuid,
    ...
    PRIMARY KEY (queue_id, updated_at)
) WITH CLUSTERING ORDER BY (updated_at ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 3600
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
CREATE INDEX jobs_state_idx ON sb.jobs ({"pk":["queue_id"],"ck":["state"]});
CREATE INDEX jobs_stream_seq_idx ON sb.jobs ({"pk":["queue_id"],"ck":["stream_seq"]});
CREATE INDEX jobs_indexed_idx ON sb.jobs ({"pk":["queue_id"],"ck":["indexed"]});
CREATE INDEX jobs_jid_idx ON sb.jobs (jid);
```

The table is tiny; 8322 rows, but many (millions) rows have been deleted. Notice the very low `gc_grace_seconds`, in combination with manual major compactions to purge tombstones. The sstable is only 796kB.

```
INFO  2022-05-07 17:57:30,190 [shard 3] compaction - [Compact sb.jobs 297aa110-ce2f-11ec-9fa0-ee98432f6b90] Compacted 2 sstables to [/var/lib/scylla/data/sb/jobs-bf189af0c77311ec9fa0ee98432f6b90/md-2395-big-Data.db:level=0]. 12MB to 796kB (~6% of original) in 543ms = 1MB/s. ~256 total partitions merged to 1.
```

The use of _any_ of the local secondary indices consistently fails...
```
select * from jobs where queue_id = 10 and indexed = false limit 10;

ReadTimeout: Error from server: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for sb.jobs_indexed_idx_index - received only 0 responses from 1 CL=ONE." info={'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}
```

The global secondary index works fine.

Let me know if there is any other info I should be providing. Thank you.

**Comment by nyh** [comment]
Hi @cjbottaro, you indicated that you did major compaction and the sstables are only 796k, but is this for the **base table** ("jobs") or the index view ("jobs_indexed_idx_index", or something like that)?

Every time you deleted items from the base table, they would also be deleted from the materialized-view that holds the index. I'm worried that this view does not have the same gc_grace_seconds configured (gc_grace_seconds is per-table, not per-keyspace - see also #3283), and you haven't done any special compactions to it. Can you please check whether this table still has millions of tombstones?

An interesting question is why only local secondary indexes cause this problem, not global secondary indexes. Perhaps (and I'm just guessing) that in the specific global secondary index you tried, your millions of deleted rows were spread across millions of partitions and any query just picks up a few of them, while with a local secondary index, you actually have a million deleted rows all matching the same key so Scylla has to read all of them just to see almost all of them are deleted?

P.S. @psarna I'm not familiar with this local secondary index syntax, I thought it was `CREATE INDEX ON table ((pk),v)`. If this alternative syntax is correct, is it documented anywhere?

**Comment by psarna** [comment]
@nyh it's just an inconsistency between what was used to create an index and what's presented when you issue a DESCRIBE statement via cqlsh. Once we implement server-side describe we could also fix that, but right now cqlsh would just show the local index target in its serialized form - in json.

**Comment by cjbottaro** [comment]
@nyh Yeah, that was my suspicion also. I wanted to set `gc_grace_seconds` on the index's materialized view and trigger a manual compaction it, but you get a CQL error when trying to issue the `alter table` command.

And yes, the syntax is `CREATE INDEX ON table ((pk),v)`, what was pasted above came from `desc table` output.

I forgot I opened this issue and already deleted the Scylla cluster this happened on, so I can't provide anymore info. Ugh, sorry about that.

**Comment by slivne** [comment]
closing the issue - since everything was handled

@cjbottaro if anything is left to be done - please comment and we can revisit
