### ISSUE TITLE
scylla_sysconfig_setup: does not able to handle >=32 CPUs cpuset correctly

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#10523]
Seems like 59adf05951c9acfef4e27141d041a606a938291f has a bug, regex pattern does not able to handle >=32 CPUs cpuset.
Result of that, it generates incorrect cpuset.conf like this:
```
$ sudo /opt/scylladb/scripts/perftune.py --tune net --nic eth0 --get-cpu-mask
0xfffffffe,0xfffffffe
$ sudo /opt/scylladb/scripts/scylla_sysconfig_setup --nic eth0 --setup-nic-and-disks
0xfffffffe,
$ cat /etc/scylla.d/cpuset.conf 
# DO NO EDIT
# This file should be automatically configure by scylla_cpuset_setup
#
# CPUSET="--cpuset 0 --smp 1"
CPUSET="--cpuset 1-31 "
```
It is ignoring first `0xfffffffe,` and handle the string as perftune warning message.

**Comment by slivne** [comment]
@avikivity backport ping

**Comment by slivne** [comment]
@avikivity ping

**Comment by avikivity** [comment]
This regex pattern isn't in 5.0. Is the bug present in 5.0? If so it needs a different fix.

**Comment by avikivity** [comment]
I backported the previous patch too.

**Comment by avikivity** [comment]
Maybe it's better to have a --quiet option to supress warnings so we don't have to parse the output.

**Comment by slivne** [comment]
@syuu1228 ^^
