### ISSUE TITLE
snapshot-ctl: take_column_family_snapshot makes assumptions about the table name

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10526]
https://github.com/scylladb/scylla/blob/9623589c773d85eb27243f76b67c745f5b891dbb/db/snapshot-ctl.cc#L96-L98

throws an error if the table has a dot in its name.

@nyh:
> Why does a dot in the table name indicate a secondary index???
> This looks like a mistake - see discussion of this "dot is a secondary index" thing in https://github.com/scylladb/scylla/issues/6521#issuecomment-766344771
> Note that Alternator tables may have a dot in their name. This sort of weird logic will break operations on them.

**Comment by avikivity** [comment]
@bhalevy @nyh does this deserve a backport?

**Comment by bhalevy** [comment]
> @bhalevy @nyh does this deserve a backport?

I think it is.
It could badly impact backups with Alternator.

**Comment by bhalevy** [comment]
and is low risk...

**Comment by avikivity** [comment]
In 5.0 as part of the much larger 32423ebc38e09b7e58a6eebe1a829e63cd42d455.

**Comment by avikivity** [comment]
Backported to 4.6 too.
