### ISSUE TITLE
default AMI disk size is not enough when extra ephemeral disks are not attached

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#1053]
When I launched AMI instance without ephemeral disks (used c4 instance), got following messages: 
```
 what():  iotune requires at least 10.00 GB available. Filesystem contains only 8.38 GB available
```

So probably we need to extend default disk size to at least 12GB.

**Comment by slivne** [comment]
we need to test t2.micro itfi its working without attached disk anything else should work without attached disks

**Comment by tzach** [comment]
t2.micro do work
@syuu1228 is this issue still open?

**Comment by syuu1228** [comment]
@tzach Looks like working finely on 10GB root disk with scylla-1.0 AMI.
