### ISSUE TITLE
hints_manager - Exception when draining 10.0.2.80: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/view_hints/12/10.0.2.80]

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylla#10552]
Got #5087 again on 2022.1rc3:

```
2022-05-01 14:36:52.385 <2022-05-01 14:36:47.000>: (DatabaseLogEvent Severity.ERROR) period_type=one-time event_id=9b486877-800f-4176-b32a-dcad62d9db49: type=DATABASE_ERROR regex=Exception  line_number=367368 node=longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-11
2022-05-01T14:36:47+00:00 longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-11 !     ERR |  [shard 12] hints_manager - Exception when draining 10.0.2.80: std::filesystem::__cxx11::filesystem_error (error system:39, filesystem error: remove failed: Directory not empty [/var/lib/scylla/view_hints/12/10.0.2.80])
```

## Installation details

Kernel Version: 5.13.0-1021-aws
Scylla version (or git commit hash): `2022.1~rc3-20220406.5cc3b678c` with build-id `48dfae0735cd8efc4ae2f5c777beaee2a1e89f4a`
Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-9 (54.229.119.180 | 10.0.3.188) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-8 (52.212.30.67 | 10.0.0.210) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-7 (52.213.1.118 | 10.0.1.95) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-6 (34.245.204.111 | 10.0.2.238) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-5 (34.246.250.133 | 10.0.1.22) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-4 (3.250.105.37 | 10.0.0.249) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-36 (52.18.10.41 | 10.0.0.41) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-35 (54.246.213.205 | 10.0.2.152) (shards: 16)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-34 (3.250.220.204 | 10.0.3.2) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-33 (54.171.106.191 | 10.0.0.10) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-32 (34.245.23.199 | 10.0.0.176) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-31 (34.253.205.11 | 10.0.3.63) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-30 (52.214.105.120 | 10.0.0.93) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-3 (3.250.26.107 | 10.0.1.216) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-29 (54.171.18.48 | 10.0.0.234) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-28 (34.241.159.155 | 10.0.1.245) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-27 (52.31.36.8 | 10.0.1.28) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-26 (54.171.163.160 | 10.0.0.241) (shards: 16)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-25 (34.241.35.50 | 10.0.2.161) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-24 (54.75.100.174 | 10.0.3.108) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-23 (52.209.6.133 | 10.0.3.95) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-22 (54.155.103.122 | 10.0.3.233) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-21 (63.32.45.6 | 10.0.0.210) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-20 (34.244.145.186 | 10.0.1.236) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-2 (3.250.79.168 | 10.0.1.25) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-19 (34.240.133.141 | 10.0.2.232) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-18 (3.250.123.195 | 10.0.3.75) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-17 (34.244.150.95 | 10.0.2.41) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-16 (54.75.59.22 | 10.0.2.114) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-15 (52.212.90.162 | 10.0.3.0) (shards: 16)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-14 (63.35.201.79 | 10.0.2.218) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-13 (52.213.168.12 | 10.0.2.80) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-12 (52.16.30.108 | 10.0.0.206) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-11 (3.250.146.18 | 10.0.0.75) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-10 (3.248.196.89 | 10.0.0.147) (shards: 14)
- longevity-tls-50gb-3d-2022-1-db-node-d42bf9f0-1 (34.240.32.204 | 10.0.3.104) (shards: 14)

OS / Image: `ami-071c70d20f0fdbb2c` (aws: eu-west-1)

Test: `EaR-longevity-kmip-50gb-4d-test`
Test id: `d42bf9f0-1497-4970-9c2b-c2de37571cc6`
Test name: `enterprise-2022.1/SCT_Enterprise_Features/EncryptionAtRest/EaR-longevity-kmip-50gb-4d-test`
Test config file(s):

- [longevity-50GB-3days-authorization-and-tls-ssl.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/819fb47d993a559a2437813022484d433e20c63f/test-cases/longevity/longevity-50GB-3days-authorization-and-tls-ssl.yaml)

- Restore Monitor Stack command: `$ hydra investigate show-monitor d42bf9f0-1497-4970-9c2b-c2de37571cc6`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d42bf9f0-1497-4970-9c2b-c2de37571cc6)
- Show all stored logs command: `$ hydra investigate show-logs d42bf9f0-1497-4970-9c2b-c2de37571cc6`

## Logs:
- **db-cluster-d42bf9f0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/db-cluster-d42bf9f0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/db-cluster-d42bf9f0.tar.gz)
- **monitor-set-d42bf9f0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/monitor-set-d42bf9f0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/monitor-set-d42bf9f0.tar.gz)
- **loader-set-d42bf9f0.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/loader-set-d42bf9f0.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/loader-set-d42bf9f0.tar.gz)
- **normal-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/normal-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/normal-d42bf9f0.log.tar.gz)
- **summary-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/summary-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/summary-d42bf9f0.log.tar.gz)
- **events-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/events-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/events-d42bf9f0.log.tar.gz)
- **output-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/output-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/output-d42bf9f0.log.tar.gz)
- **debug-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/debug-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/debug-d42bf9f0.log.tar.gz)
- **sct-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/sct-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/sct-d42bf9f0.log.tar.gz)
- **error-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/error-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/error-d42bf9f0.log.tar.gz)
- **critical-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/critical-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/critical-d42bf9f0.log.tar.gz)
- **raw_events-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/raw_events-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/raw_events-d42bf9f0.log.tar.gz)
- **warning-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/warning-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/warning-d42bf9f0.log.tar.gz)
- **email_data-d42bf9f0.json.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/email_data-d42bf9f0.json.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/email_data-d42bf9f0.json.tar.gz)
- **argus-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/argus-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/argus-d42bf9f0.log.tar.gz)
- **left_processes-d42bf9f0.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/left_processes-d42bf9f0.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d42bf9f0-1497-4970-9c2b-c2de37571cc6/20220503_141859/left_processes-d42bf9f0.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/SCT_Enterprise_Features/job/EncryptionAtRest/job/EaR-longevity-kmip-50gb-4d-test/3/)

**Comment by psarna** [comment]
It's a non-fatal error which indicates that a hint got stored during drain, right before we try to remove the hints directory as part of the draining process. I don't really see any mechanisms for preventing such a thing, so maybe it's just a race that has been there for a very long time? The error most likely comes from here:
https://github.com/scylladb/scylla/blob/8a6f8c622d71f5e5956fcf2b4683b64bcba66dd6/db/hints/manager.cc#L723

And I suspect that the flow was something like that:
1. store_hint is called, we're not draining yet, so we pass this check successfully: https://github.com/scylladb/scylla/blob/8a6f8c622d71f5e5956fcf2b4683b64bcba66dd6/db/hints/manager.cc#L362-L366 and start an async job of storing a hint
2. We start draining and yield right before calling `remove_file` from above
3. We successfully finish storing a hint started in (1.), and thus `remove_file` fails, because it expected an empty directory

@piodul after you're done with your high priority items, please verify if this scenario makes sense

**Comment by piodul** [comment]
Closing - the test run was using scylla-enterprise, not scylla open source.
