### ISSUE TITLE
Add unit tests for bloom filter efficacy

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1055]
Create an sstable with N random keys, try to read M random non-existing keys, see the false positive ratio.

**Comment by slivne** [comment]
there is a known issue with false positives ....

https://issues.apache.org/jira/browse/CASSANDRA-8413

**Comment by avikivity** [comment]
We should gain the fix when we update our sstable format to 2.2+.

**Comment by Jadw1** [comment]
I did some draft version of the test and I want to specify some things.
[DRAFT VERSION](https://gist.github.com/Jadw1/ac4ecfc0f0419e35b9bc4e543c0ec7fb)

My questions are:
- Is it ok to do it as `cql-pytest`?
- What are we exactly expecting from the test? To assert if false-positive ratio is within some range (if so, what range)?
- Should I do major compaction to simplify the experimental setup?
- Anything else that I'm missing?

**Comment by avikivity** [comment]
> @avikivity I got assigned to this issue, so I did some draft version of the test and I want to specify some things. [DRAFT VERSION](https://gist.github.com/Jadw1/ac4ecfc0f0419e35b9bc4e543c0ec7fb)
> 
> My questions are:
> 
> * Is it ok to do it as `cql-pytest`?

I guess, as long as it doesn't take too long. Otherwise we can try direct API use of the bloom filters.

> * What are we exactly expecting from the test? To assert if false-positive ratio is within some range (if so, what range)?

Say create a filter with 0.01 false positive probability and see that it's within 0.008-0.012. Just random numbers, we can adjust if math says that's not reasonable.

> * Should I do major compaction to simplify the experimental setup?

If it helps.

> * Anything else that I'm missing?

The test should complete quickly.

**Comment by Jadw1** [comment]
Also, how big M and N should be? Now with `M=10k` and `N=5k` it takes about 2.5sec to complete.

**Comment by avikivity** [comment]
> Also, how big M and N should be? 

I don't have any intuition. Enough to get stable results.

> Now with `M=10k` and `N=5k` it takes about 2.5sec to complete.

How about debug mode?

**Comment by nyh** [comment]
> Also, how big M and N should be? Now with `M=10k` and `N=5k` it takes about 2.5sec to complete.

2.5 seconds for a single cql-pytest is not good (it would probably be the slowest one). But not the end of the world if there is no other alternative. Another question is what takes 2.5 seconds - unlike other tests which need to sleep for 2 seconds which is bad but not terrible - this test actually loops for 2.5 seconds. So the debug build will be much slower (you can test and see) :-(

You should consider whether you really need to many partitions to test what you want to test - or maybe by choosing a different false-positive probability you can demonstrate the same problem (?) also with a smaller test.

**Comment by avikivity** [comment]
Not a bug, not backporting.
