### ISSUE TITLE
The promoted index is copied needlessly when writing sstables

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10569]
https://github.com/scylladb/scylla/blob/768b5f3f29e527e1497f75064bab3f76f9290aba/sstables/mx/writer.cc#L1300-L1301

call

https://github.com/scylladb/scylla/blob/768b5f3f29e527e1497f75064bab3f76f9290aba/sstables/writer.hh#L301

which causes `blocks` to get copied needlessly, and potentially causing OOM when the promoted index is extremely large,
as seen in 2021.1.5-0.20210818.fc817c0cd:
```
(gdb) bt
#0  0x00007f4010dfb2a2 in raise () from /opt/scylladb/libreloc/libc.so.6
#1  0x00007f4010de4950 in abort () from /opt/scylladb/libreloc/libc.so.6
#2  0x0000000002d88201 in seastar::memory::on_allocation_failure (size=<optimized out>) at ./seastar/src/core/memory.cc:1578
#3  0x0000000002d8ab9d in seastar::memory::allocate (size=<optimized out>) at ./seastar/src/core/memory.cc:1272
#4  malloc (n=<optimized out>) at ./seastar/src/core/memory.cc:1608
#5  0x0000000000ec71de in bytes_ostream::alloc_new (this=0x600024d1fb50, size=131056) at ./bytes_ostream.hh:146
#6  0x00000000013376ad in bytes_ostream::write (v=..., this=0x600024d1fb50) at ./bytes_ostream.hh:247
#7  bytes_ostream::append (o=..., this=0x600024d1fb50) at ./bytes_ostream.hh:320
#8  bytes_ostream::bytes_ostream (o=..., this=0x600024d1fb50) at ./bytes_ostream.hh:189
#9  sstables::mc::writer::write_promoted_index (this=0x6000166ae300) at sstables/mx/writer.cc:1304
#10 0x0000000001345c49 in sstables::mc::writer::consume_end_of_partition (this=0x6000166ae300) at sstables/mx/writer.cc:1360
#11 0x000000000122e5d9 in flat_mutation_reader::impl::consumer_adapter<sstables::sstable_writer>::consume (pe=..., this=0x600024d1fdb0) at ./flat_mutation_reader.hh:218

(gdb) fr 8
#8  bytes_ostream::bytes_ostream (o=..., this=0x600024d1fb50) at ./bytes_ostream.hh:189
189             append(o);
(gdb) p o
$1 = (const bytes_ostream &) @0x6000166ae900: {
  _begin = std::unique_ptr<bytes_ostream::chunk> = {
    get() = 0x60002ab3b200
  },
  _current = 0x600108600000,
  _size = 3766412860,
  _initial_chunk_size = 512
}
```

**Comment by bhalevy** [comment]
The unneeded copy was introduced in [0d8463a](https://github.com/scylladb/scylla-enterprise/commit/0d8463aba580cb3c84cb9cafa825e0e2eb16ebc1)

**Comment by bhalevy** [comment]
> The unneeded copy was introduced in https://github.com/scylladb/scylla/commit/0d8463aba580cb3c84cb9cafa825e0e2eb16ebc1

@scylladb/scylla-maint this has been there forever, I suggest we backport the fix to 5.0 / 2022.1 and possibly to 4.6 (as it's low risk) and 2021.1.

**Comment by avikivity** [comment]
Performance only, not backporting.

**Comment by bhalevy** [comment]
> Performance only, not backporting.

@avikivity it's not performance only, this has contributed to running OOM in the field with a huge partition.

**Comment by avikivity** [comment]
It only changes the threshold. If the promoted index has size X, the patch reduces consumption from 2X to X. So making the partition twice as large will fail after the patch.

So, it doesn't materially change things, just moves the failure point around.

**Comment by bhalevy** [comment]
Agreed, it's a mitigation.
Still, I think the benefits of 8a6f8c622d71f5e5956fcf2b4683b64bcba66dd6 outweigh its risks, but it's up to you of course.
