### ISSUE TITLE
Short-circuit sstable read if index indicates no data

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1056]
If the sstable index indicates there is no data to read, we can return an empty_reader instead of a real sstable reader, which is more expensive.

**Comment by benoit-canet** [comment]
@avikivity Are those _get_data_source the place too look at ? https://github.com/scylladb/scylla/blob/f3c8cbbac5a36f73a8262cb8a06ae145a8a84cc3/sstables/partition.cc#L1028

**Comment by avikivity** [comment]
Yes.

**Comment by benoit-canet** [comment]
@avikivity: Is this bug suposed to be easy, media or hard ? I picked it up at random a while ago and have all the pain in the world to fix it.
