### ISSUE TITLE
raft: follower may mark obsolete entries committed while handling `read_quorum`

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#10578]
`fsm::step`:
```cpp
    } else if constexpr (std::is_same_v<Message, read_quorum>) {
        logger.trace("[{}] receive read_quorum from {} for read id {}", _my_id, from, msg.id);
        advance_commit_idx(msg.leader_commit_idx);
        send_to(from, read_quorum_reply{_current_term, _commit_idx, msg.id});
    }
```

the `advance_commit_idx` call is not correct because our log may be outdated. Similar to #9965.
Example trace leading to inconsistency attached (using https://github.com/scylladb/scylla/pull/10561):
[read-barrier-inconsistency-1.txt](https://github.com/scylladb/scylla/files/8701509/read-barrier-inconsistency-1.txt)

cc @gleb-cloudius @kostja

**Comment by avikivity** [comment]
Raft is experimental, not backporting.

**Comment by gleb-cloudius** [comment]
On Mon, May 16, 2022 at 08:53:32AM -0700, Kamil Braun wrote:
> The leader could send the term of `msg.leader_commit_idx` and the follower would only call `advance_commit_idx` if there's a match, or something.
The whole leader_commit_idx is an optimization and not really necessary for read barrier to work.
I think setting it to min(matched_idx, _commit_idx) when sending should
fix it.

Something like this:

diff --git a/raft/fsm.cc b/raft/fsm.cc
index e013746924..aed89ba3d0 100644
--- a/raft/fsm.cc
+++ b/raft/fsm.cc
@@ -1021,7 +1021,7 @@ void fsm::broadcast_read_quorum(read_id id) {
             if (p.id == _my_id) {
                 handle_read_quorum_reply(_my_id, read_quorum_reply{_current_term, _commit_idx, id});
             } else {
-                send_to(p.id, read_quorum{_current_term, _commit_idx, id});
+                send_to(p.id, read_quorum{std::min(p.match_idx, _current_term), _commit_idx, id});
             }
         }
     }

--
			Gleb.
