### ISSUE TITLE
cql: Remove support for null inside lists of IN values

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylla#10579]
Currently we support queries like:
```cql
SELECT * FROM ks.tab WHERE p IN (1, 2, null, 4);
```
Nothing can be equal to null so this is equivalent to:
```cql
SELECT * FROM ks.tab WHERE p IN (1, 2, 4);
```

Cassandra doesn't support it at all.
```cql
> SELECT * FROM ks.tab WHERE p IN (1, 2, null, 4)
Error: DbError(Invalid, "Invalid null value in condition for column p")

> SELECT * FROM ks.tab WHERE p IN (1, 2, ?, 4) # ? is NULL
Error: DbError(Invalid, "Invalid null value in condition for column p")

> SELECT * FROM ks.tab WHERE p IN ? # ? is (1, 2, null, 4)
Error: DbError(Invalid, "Invalid null value in condition for column p")
```
It makes little sense to send a null inside list of IN values and supporting it is a bit cumbersome.

Supporting it causes trouble because internally the values are represented as a list, not a tuple, and lists can't contain nulls.
Because of that code requires exceptions because in this single case there can be a null inside of a collection.

Changing this wouldn't require much work.
We would only need to remove `evaluate_IN_list` and modify [some tests](https://github.com/scylladb/scylla/blob/a2b9a17927d851b368d3ef8e869a295c8bd2e86b/test/boost/restrictions_test.cc#L660).

**Comment by avikivity** [comment]
Not a bug, not backporting.
