### ISSUE TITLE
Call to service::get_local_storage_service().effective_ownership fails

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#1057]
A call to service::get_local_storage_service().effective_ownership("keyspace1") fails with:
Attempt to access value of a disengaged optional object

How to reproduce:
Create a cluster and keyspace1 (run a small load) call:

http://127.0.0.1:10000/storage_service/ownership/keyspace1
Attempt to access value of a disengaged optional object
This effect
nodetool status keyspace1

**Comment by penberg** [comment]
I am not able to reproduce:

```
[penberg@nero scylla]$ curl http://127.0.0.1:10000/storage_service/ownership/keyspace1
[{"value": "0.531671584", "key": "127.0.0.1"},{"value": "0.468328476", "key": "127.0.0.2"}]
```

@amnonh Please tell me more about your setup. How many nodes? What does "a small load" mean exactly? Are you able to reproduce all the time?

**Comment by amnonh** [comment]
I did the following:
1. Started a single node cluster.
2. Create a keyspace with:
./tools/bin/cassandra-stress write n=1  -mode native cql3  -rate threads=1
 -pop seq=1..3000000 -node 127.0.0.1

$ curl http://127.0.0.1:10000/storage_service/ownership/keyspace1
{"message": "Attempt to access value of a disengaged optional object",
"code": 500}

**Comment by penberg** [comment]
I am not able to reproduce the issue nor am I able to find anything that could cause the issue by auditing the code.

**Comment by amnonh** [comment]
I'll try again with master

**Comment by amnonh** [comment]
Hail the self-fixing-software god.
Problem is gone I verified that the test that was failing, now passes

**Comment by slivne** [comment]
@amnonh I think we can remove the skip from the tests - you had marked with that and test they are passing.

there are two in nodetool_additional_test

**Comment by amnonh** [comment]
Didn't I sent a patch that removes it?
