### ISSUE TITLE
Listen address and RPC address options don't support interface names

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#1058]
The `listen_address` and `rpc_address` configuration options don't support interface names (e.g. eth0) although comments in `scylla.yaml` say that they do.

**Comment by avikivity** [comment]
Shouldn't be hard to fix by using the nice socket ioctls from sockios.h.

We should also add support for setting subnets there, e.g. `listen_address: 10.1.0.0/16`, telling the code to bind to any interface that is covered by those subnets.  The advantage is that a single setting works for the entire cluster, avoiding differences in interface naming and addresses.

**Comment by slivne** [comment]
For GA I suggest we update the comments if at all

**Comment by glommer** [comment]
Looks like duplicate of #456 to me.

**Comment by amnonh** [comment]
Isn't it solved by feffc2bbe1a219b31787e9ca275e00ab3cf8cbbf

**Comment by avikivity** [comment]
no
