### ISSUE TITLE
LCS controller returns high backlog even though space amplification goal is achieved

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#10583]
LCS targets a space amplification of 1.1

To achieve that, it needs to achieve the layout where for every level L, L is fan_out times larger than L-1.

If level 3 = 1000G, level 2 = 100G, level 1 = 10G, level 0 = 1G, that should
return zero backlog as space amplification is (1000+100+10+1)/1000 = ~1.1

But today, LCS returns high backlog even though the space amplification goal was achieved.

Therefore,LCS and co-existing tables can run with much more shares than needed, causing higher latency and reduced throughput.

**Comment by raphaelsc** [comment]
![Screenshot from 2022-05-14 22-58-23](https://user-images.githubusercontent.com/1409139/168713675-d5987d09-7011-417c-9f91-70831c069382.png)

**Comment by avikivity** [comment]
Major change, not backporting.
