### ISSUE TITLE
cql: Add proper validation for nulls inside collections send as bound values

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylla#10580]
Let's say we have a query like:
```cql
INSERT INTO ks.t (list_column) VALUES (?);
```
And the driver sends a list with null inside as the bound value, something like `[1, 2, null, 4]`.

In such case we should throw `invalid_request_exception` because `nulls` are not allowed inside collections.

Currently when a query like this gets executed Scylla throws an ugly error like this:
```
Error: DbError(Invalid, "Exception while binding value of type org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.Int32Type): marshaling error: read_simple_bytes - not enough bytes (requested 18446744073709551615, got 8) Backtrace: 0x4161c3e 0x4162130 0x4162438 0x119407c 0x1193d14 0x2049411 0x2046c76 0x1c69189 0x1ca6d01 0x1c68d48 0x1c3a241 0x1dc5b92 0x1dc63ca 0x1d9c3a6 0x1d990e5 0x1da1c51 0x1d9e96e 0x1dac377 0x1dac3bc 0x1da96d4 0x3d86635 0x3dd0cc4 0x3dd20b7 0x3dd12fc 0x3d7aaae 0x3d79e26 0xf41135 /opt/scylladb/libreloc/libc.so.6+0x27b74 0xf3e2ed\n   --------\n   seastar::lambda_task<seastar::execution_stage::flush()::$_5>")
```

This is because [validation code](https://github.com/scylladb/scylla/blob/a2b9a17927d851b368d3ef8e869a295c8bd2e86b/types.cc#L1423) reads size of the next element, interprets it as an unsigned integer and tries to read this much.
In case of `null` element the size is `-1`, which when converted to unsigned `size_t` gives 18446744073709551615 and it fails to read this much.

To fix this null checks could be added to `validate_aux`.

There might be some exception for lists of IN values, but support for nulls there might get removed (see #10579)

**Comment by avikivity** [comment]
Choosing not to backport, it won't affect users under normal operation.
