### ISSUE TITLE
Get rid of downgrade_to_v1

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10586]
This is an umbrella task for getting rid of `downgrade_to_v1`

At this it is still used by repair, streaming, and load_and_stream, plus unit test.

**Comment by bhalevy** [comment]
It looks like we can move the `downgrade_to_v1` logic into a class wrapping the v2 reader
and expose just a few methods: `schema()`, `future<mutation_fragment_opt> get()` (or a call operator), and `close()`.

It also need to satisfy the `peek()` use case in `streaming_info::send_mutation_fragments` that only checks if there's another mutation fragment queue. So we need some `future<bool>` method.

**Comment by bhalevy** [comment]
@denesb / @cmm I presume no backport is needed.  please confirm

**Comment by cmm** [comment]
where could this be back-ported, in theory? (I wonder what is the logic that causes the "back-port candidate" label to be put on stuff?  I thought it was a totally manual thing...)

**Comment by bhalevy** [comment]
On the contrary, as printed above:
> [scylladb-promoter](https://github.com/scylladb-promoter) added the [Backport candidate](https://github.com/scylladb/scylla/labels/Backport%20candidate) label

it just adds it when the issue's fix gets merged.

The removal of the label is indeed totally manual.

Anyhow, in theory, we started the conversion to f_m_r_v2 in the 4.6 timeframe.
And we need to decide how complete we want the conversion to be in 5.0 and 2022.1 that is based on it.
If there wasn't a long-term enterprise branch based on 5.0 there wouldn't be any question and we wouldn't backport this.
The question is if this fixes any bug or performance regression, and what the risk is in backporting the fix.

**Comment by denesb** [comment]
I don't think this is backport material. This could improve performance and certainly improves code maintanability but these are not backport criteria usually.
