### ISSUE TITLE
SELECT TOKEN(v) fails with ServerError when v=NULL

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylla#10594]
```
CREATE KEYSPACE reproducer WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
CREATE TABLE reproducer.t(pk int PRIMARY KEY, v int);
INSERT INTO reproducer.t (pk) VALUES (1);
SELECT TOKEN(v) FROM reproducer.t;
```

fails with 
```
ServerError: attempted to create key component from empty optional
```

on Scylla (as of ca322fb7c2786bfa39c833ee30f464d0ea011a36).

Meanwhile, on Cassandra 3.11.8 (and Cassandra 2.2.0), it just returns `NULL`:
```
cqlsh> SELECT token(v) FROM reproducer.t;

 system.token(v)
-----------------
            null

(1 rows)
```

**Comment by avikivity** [comment]
Returning NULL here seems sensible (any expression involving NULL should return NULL, except for IS [NOT] NULL)

**Comment by kbr-** [comment]
https://github.com/deexie is working on this task (I'll assign her when she's invited to the github org)

**Comment by avikivity** [comment]
Minor compatibility issue (exception vs null on invalid input), not backporting.
