### ISSUE TITLE
raft: cluster may become permanently leaderless after a leader reconfigures itself to be a non-voter

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#10618]
The following scenario may cause the cluster to get stuck:
1. One node in the config, A. Second node outside config, B.
2. Network partition between A and B.
3. A appends a joint configuration entry `{(A, voter)} -> {(A, non-voter), (B, voter)}`.
4. Eventually A gives up leadership, becomes a candidate.
5. Network partition resolves.
6. The cluster is stuck. A is the only node who can become leader at this point, but due to a bug, it never does.

Note that A becomes a candidate. However, there is a bug which prevents it from becoming a leader: namely, A does not vote for itself. In order to become a leader in this joint configuration, A must obtain votes from both itself and B. It does obtain vote from B, but not from itself.

Attaching trace from nemesis test.
[non-voter-reconfig-stuck.txt](https://github.com/scylladb/scylla/files/8740061/non-voter-reconfig-stuck.txt)
I added some comments in key places (the comments start with `---`).

My understanding is that the bug is in `fsm::become_candidate`:
```cpp
    // Replicate RequestVote
    for (const auto& server : voters) {
        if (server.id == _my_id) {
            // Vote for self.
            votes.register_vote(server.id, true);
            if (!is_prevote) {
                // Only record real votes
                _voted_for = _my_id;
            }
            // Already signaled _sm_events in update_current_term()
            continue;
        }
        logger.trace("{} [term: {}, index: {}, last log term: {}{}{}] sent vote request to {}",
            _my_id, term, _log.last_idx(), _log.last_term(), is_prevote ? ", prevote" : "",
            is_leadership_transfer ? ", force" : "", server.id);

        send_to(server.id, vote_request{term, _log.last_idx(), _log.last_term(), is_prevote, is_leadership_transfer});
    }
    if (votes.tally_votes() == vote_result::WON) {
        // A single node cluster.
        if (is_prevote) {
            logger.trace("become_candidate[{}] won prevote", _my_id);
            become_candidate(false);
        } else {
            logger.trace("become_candidate[{}] won vote", _my_id);
            become_leader();
        }
    }
```

The problem is that the `voters` vector does not contain `A`, because `A` is only a voter in the previous configuration, not the current one. So in the loop over `voters`, A does not vote for self. The correct thing would be to iterate for *all* voters, not only voters in the current configuration.

`voters` is defined as:
```cpp
    auto& votes = candidate_state().votes;
    const auto& voters = votes.voters();
```

`candidate_state().votes.voters()` is constructed from configurations as follows:
```cpp
votes::votes(configuration configuration)
        :_voters(configuration.current)
        , _current(configuration.current) {

    if (configuration.is_joint()) {
        _previous.emplace(configuration.previous);
        _voters.insert(configuration.previous.begin(), configuration.previous.end());
    }
    // Filter out non voting members
    std::erase_if(_voters, [] (const server_address& s) { return !s.can_vote; });
}
```

The definition is quite weird: a server is considered a "voter" (a member of `voters()`) if either:
- it is a voter in the current configuration,
- or it is not present in the current configuration and it is a voter in the previous configuration.

We probably want to have a second set, e.g. `joint_voters()`, which contains both voters from the current and previous configuration, and use that set in the loop above. Or we could try changing the definition of `voters()`, but there is a second usage of `voters()` inside `become_candidate` and it may become affected. Needs further investigation.

cc @kostja @gleb-cloudius

**Comment by gleb-cloudius** [comment]
On Fri, May 20, 2022 at 05:18:47AM -0700, Kamil Braun wrote:
> The following scenario may cause the cluster to get stuck:
> 1. One node in the config, A. Second node outside config, B.
> 2. Network partition between A and B.
> 3. A appends a joint configuration entry `{(A, voter)} -> {(A, non-voter), (B, voter)}`.
> 4. Eventually A gives up leadership, becomes a candidate.
I do not see why. It cannot commit joint entry and thus is should
remain a voter and a leader.

> 5. Network partition resolves.
> 6. The cluster is stuck. A is the only node who can become leader at this point, but due to a bug, it never does.
> 

--
			Gleb.

**Comment by gleb-cloudius** [comment]
> On Fri, May 20, 2022 at 05:18:47AM -0700, Kamil Braun wrote: The following scenario may cause the cluster to get stuck: 1. One node in the config, A. Second node outside config, B. 2. Network partition between A and B. 3. A appends a joint configuration entry `{(A, voter)} -> {(A, non-voter), (B, voter)}`. 4. Eventually A gives up leadership, becomes a candidate.
> I do not see why. It cannot commit joint entry and thus it should remain a voter and a leader.

Ah, because there is no alive quorum any longer.

**Comment by gleb-cloudius** [comment]
> ```c++
> votes::votes(configuration configuration)
>         :_voters(configuration.current)
>         , _current(configuration.current) {
> 
>     if (configuration.is_joint()) {
>         _previous.emplace(configuration.previous);
>         _voters.insert(configuration.previous.begin(), configuration.previous.end());
>     }
>     // Filter out non voting members
>     std::erase_if(_voters, [] (const server_address& s) { return !s.can_vote; });
> }
> ```
> 
> The definition is quite weird: a server is considered a "voter" (a member of `voters()`) if either:
> 
>     * it is a voter in the current configuration,
> 
>     * or it is not present in the current configuration and it is a voter in the previous configuration.
>
I do not think it is even well defined what the function does since `unordered_set::insert(iter, iter)` says it is not defined what happens if there are duplicates.


`configuration::can_vote` has right definition of a voter and this function should follow it as well.

> 
> We probably want to have a second set, e.g. `joint_voters()`, which contains both voters from the current and previous configuration, and use that set in the loop above. Or we could try changing the definition of `voters()`, but there is a second usage of `voters()` inside `become_candidate` and it may become affected. Needs further investigation.

A node can become a vote as long as joint is not committed yet. It may need to commit the joint after all. The code in `become_candidate` may enter the `if (!voters.contains(server_address{_my_id}))` in joint config which may be harmless, but unnecessary,

**Comment by avikivity** [comment]
Raft, still experimental in 5.0, not backporting.
