### ISSUE TITLE
Warnings : Aggregation query used without partition key

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#10626]
Apache Cassandra issue a warning on select which generate a full scan.
For example:

```
cqlsh:mykeyspace>  select count (*) from heartrate_v10;

 count
-------
    15

(1 rows)

Warnings :
Aggregation query used without partition key
```

**Comment by avikivity** [comment]
I think we shouldn't warn here. Instead we have automatic parallelization of such queries.

**Comment by tzach** [comment]
Even with parallelization its a full scan.
In other cases Scylla/Cassandra require a ALLOW FILTERING directive to allow a full scan.

**Comment by avikivity** [comment]
Yes but what's the point? Require the users to add ALLOW FILTERING? They will thank you for it.

**Comment by tzach** [comment]
The point is protecting the user from an accidental full scan

**Comment by avikivity** [comment]
The warning doesn't protect anything.
