### ISSUE TITLE
Handle physical devices under virtual bridge

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#1063]
posix_net_conf.sh is not able to properly configure the relevant physical networking interface(s) when a virtual bridge name is provides as a networking interface parameter.

This is mostly relevant for VM setups but not only them

**Comment by avikivity** [comment]
Bridges are usually on the host, not the guest.

**Comment by vladzcloudius** [comment]
On 03/20/2016 11:21 AM, Avi Kivity wrote:
>
> Bridges are usually on the host, not the guest.
>

Indeed. This in particular means that IRQ configuration has to be 
performed (if at all) on the host as well.

**Comment by vladzcloudius** [comment]
@avi By the way, as far as I remember IRQ configuration is a privileged task and thus not allowed from inside the Guest, is it?

**Comment by avikivity** [comment]
Guest IRQs are managed inside the guest, host IRQs are managed on the host (and are invisible to the guest).

For a normal bridge on the host, the guest won't see it at all, it only has to manage the guest IRQs on the virtio (or whatever) device.

**Comment by vladzcloudius** [comment]
On 03/20/2016 12:51 PM, Avi Kivity wrote:
>
> Guest IRQs are managed inside the guest, host IRQs are managed on the 
> host (and are invisible to the guest).
>
> For a normal bridge on the host, the guest won't see it at all, it 
> only has to manage the guest IRQs on the virtio (or whatever) device.
>

Thanks for clarification and like I assumed this strengthens my previous 
point: in case of a normal bridge the posix_net_conf.sh has to be 
invoked on a host to achieve its goal.

**Comment by avikivity** [comment]
No, you can't and shouldn't touch the host at all.

Run `posix_net_conf.sh` on the guest to configure the guest IRQs.

**Comment by vladzcloudius** [comment]
The point of this github issue is all about configuration of physical interfaces when they are used with virtual bridges. This use case is used but not limited to VM configurations. I've just mentioned it as an example. The configuration inside the VM is a different matter not related to virtual bridges.

But to address your comment (let's discuss the mode when all IRQs are bound to CPU0 to make it simple): if u haven't ensured that the physical NIC's IRQs on the host are not going to be handled on the same CPUs that will be used for scylla's cores inside the VM it doesn't matter what u are going to configure inside the VM - the main target of the posix_net_conf.sh is not going to be achieved. And one way to achieve this goal is to run posix_net_conf.sh on the host and then exclude CPU0 from the cpu set assigned to the VM.

**Comment by avikivity** [comment]
Let's not confuse users with host configuration.  It's very rare that the user is in control of the host.

**Comment by vladzcloudius** [comment]
On 03/20/2016 02:14 PM, Avi Kivity wrote:
>
> Let's not confuse users with host configuration. It's very rare that 
> the user is in control of the host.
>

This issue is all about physical NICs configuration with 
/posix_net_cont.sh/ script when it's given a virtual bridge interface as 
a network interface. Just like with bonding case this networking 
configuration scenario has its challenges that have to be addressed. 
This github issue has nothing to do with running ScyllaDB inside the VM.

If you think that there is a place for a separate discussion of a VM 
specific networking configuration in the context of /posix_net_conf.sh/ 
I suggest we open a different github issue and discuss the things there. 
I personally don't see anything special that has to be added to the 
above script for the VM case. But maybe I'm missing something...

**Comment by avikivity** [comment]
The case where we have a bridge inside the VM, or a bridge on the physical host that is also running Scylla (or another seastar application) will be very rare in production.

I suggest in that case we do nothing.

**Comment by vladzcloudius** [comment]
On 03/20/2016 03:12 PM, Avi Kivity wrote:
>
> The case where we have a bridge inside the VM, or a bridge on the 
> physical host that is also running Scylla (or another seastar 
> application) will be very rare in production.
>
> I suggest in that case we do nothing.
>

No objections on my side. I'll print an error message from 
/posix_net_conf.sh/ if it detects this situation then.

**Comment by avikivity** [comment]
On 03/20/2016 03:24 PM, vladzcloudius wrote:
>
>
> On 03/20/2016 03:12 PM, Avi Kivity wrote:
> >
> > The case where we have a bridge inside the VM, or a bridge on the
> > physical host that is also running Scylla (or another seastar
> > application) will be very rare in production.
> >
> > I suggest in that case we do nothing.
> >
>
> No objections on my side. I'll print an error message from
> /posix_net_conf.sh/ if it detects this situation then.
>

Not an error (but an informative message).

**Comment by vladzcloudius** [comment]
On 03/20/2016 03:27 PM, Avi Kivity wrote:
>
>
> On 03/20/2016 03:24 PM, vladzcloudius wrote:
> >
> >
> > On 03/20/2016 03:12 PM, Avi Kivity wrote:
> > >
> > > The case where we have a bridge inside the VM, or a bridge on the
> > > physical host that is also running Scylla (or another seastar
> > > application) will be very rare in production.
> > >
> > > I suggest in that case we do nothing.
> > >
> >
> > No objections on my side. I'll print an error message from
> > /posix_net_conf.sh/ if it detects this situation then.
> >
>
> Not an error (but an informative message).

Right. Good point.

**Comment by avikivity** [comment]
@vladzcloudius is this fixed?

**Comment by vladzcloudius** [comment]
@avikivity Yes, the error message is printed.
