### ISSUE TITLE
Failure to apply a failed batchlog is silent

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10636]
@slivne wrote:
> @cmm - we need to add some logging when we fail to apply a failed batchlog, can you please send a patch for that for upstream and then we will do backports.

This is already fixed by https://github.com/scylladb/scylla/pull/10556
so I'm opening this issue for backporting purposes.

Cc @cmm please make sure to open an issue in the future, if a backport is requried.

**Comment by bhalevy** [comment]
Fixed by ab149c845773029c093fb2ff066e5e5883887024

**Comment by avikivity** [comment]
I'm considering for backport, but also wondering if this can create logspam.

@bhalevy under what conditions can this happen? Should it be rate limited?

Losing a warning is fine, since we keep the data.

**Comment by bhalevy** [comment]
> I'm considering for backport, but also wondering if this can create logspam.
> 
> @bhalevy under what conditions can this happen? Should it be rate limited?

It could happen for any reason the batch query failed, except for `no_such_keyspace`.

Since the batchlog `replay_interval` is 60 seconds by default I don't think it merits rate limiting.

> 
> Losing a warning is fine, since we keep the data.

**Comment by bhalevy** [comment]
@avikivity / @scylladb/scylla-maint ping backport

**Comment by denesb** [comment]
> Fixed by [ab149c8](https://github.com/scylladb/scylladb/commit/ab149c845773029c093fb2ff066e5e5883887024)

This commit seems to not exist anymore (maybe we force-pushed next).
The actual fix is: https://github.com/scylladb/scylladb/commit/00ed4ac74c1ac86c0328ad5851fb5155e5b9b228.

**Comment by denesb** [comment]
Backported to 4.6 and 5.0.

**Comment by denesb** [comment]
And to 2021.1.
