### ISSUE TITLE
Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1064]
While testing one standalone instance of Scylla 0.19 AMI with c-s I'm getting 
```
Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
```
On the client, while running s tress with a customize profile
```
cassandra-stress user profile=cust_s/case2.yaml ops\(insert=1\) -node 172.31.30.148 -rate threads=1000
```
Both loader and db server instance type: c3.4xlarge
server  IO parameters: `SCYLLA_IO="--num-io-queues 8 --max-io-requests 32"`

I do not see errors in Scylla log.

**Comment by gleb-cloudius** [comment]
On Sun, Mar 20, 2016 at 04:07:02AM -0700, Tzach Livyatan wrote:
> While testing one standalone instance of Scylla 0.19 AMI with c-s I'm getting 
> ```
> Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
> ```
> On the client, while running s tress with a customize profile
> ```
> cassandra-stress user profile=cust_s/case2.yaml ops\(insert=1\) -node 172.31.30.148 -rate threads=1000
> ```
What's in the cust_s/case2.yaml and how many client have you ran in
parallel.

In general the error means that you asked for to much for the node. The
solution is usually to reduce parallelism.

> Both loader and db server instance type: c3.4xlarge
> server  IO parameters: `SCYLLA_IO="--num-io-queues 8 --max-io-requests 32"`
> 
> I do not see errors in Scylla log.
> 

--
			Gleb.

**Comment by tzach** [comment]
> What's in the cust_s/case2.yaml and how many client have you ran in
parallel.

I'm using one loader node
case2.yaml is a private user profile
https://github.com/cloudius-systems/urchin-qa-internal/blob/master/cust_s/case2.yaml

> In general the error means that you asked for to much for the node. The
solution is usually to reduce parallelism.

Shouldn't the back pressure take care of that?

BTW, the problem is not consistent. Not always happened.

**Comment by gleb-cloudius** [comment]
On Sun, Mar 20, 2016 at 04:17:34AM -0700, Tzach Livyatan wrote:
> > What's in the cust_s/case2.yaml and how many client have you ran in
> parallel.
> 
> I'm using one loader node
Number of loaders does not define parallelism.

> case2.yaml is a private user profile
> https://github.com/cloudius-systems/urchin-qa-internal/blob/master/cust_s/case2.yaml
> 
Do I read it correctly that
insert:
  partitions: fixed(1)
  select:    fixed(1)/1000
  batchtype: UNLOGGED

means that you will send unlogged batch of 1000 queries? It means that
effective parallelism is
1000*1000 = 10000000

> > In general the error means that you asked for to much for the node. The
> solution is usually to reduce parallelism.
> 
> Shouldn't the back pressure take care of that?

Back pressure works per client connection. If we hit disk limit before
connections started to feel back pressure we will see timeout.

--
			Gleb.

**Comment by tzach** [comment]
@gleb-cloudius good point
Maybe I misused the batch ratio

"select distribution ratio -  The ratio of rows each partition should insert as a proportion of the total possible rows for the partition (as defined by the clustering distribution columns). default FIXED(1)/1"
http://www.datastax.com/dev/blog/improved-cassandra-2-1-stress-tool-benchmark-any-schema

Does  `select:    fixed(1)/1000` mean 1000 row in each batch, or inserting ~1000 rows (eventually) for each partition?

**Comment by gleb-cloudius** [comment]
On Sun, Mar 20, 2016 at 04:35:48AM -0700, Tzach Livyatan wrote:
> @gleb-cloudius good point
> Maybe I misused the batch ratio
> 
> "select distribution ratio -  The ratio of rows each partition should insert as a proportion of the total possible rows for the partition (as defined by the clustering distribution columns). default FIXED(1)/1"
> http://www.datastax.com/dev/blog/improved-cassandra-2-1-stress-tool-benchmark-any-schema
> 
> Does  `select:    fixed(1)/1000` mean 1000 row in each batch, or inserting ~1000 rows (eventually) for each partition?
> 
Well, as far as I understand this means one thousands of all raws in a
partition should be updated by a batch. Since you have only one row per
partition I have no idea what this does in your case.

--
			Gleb.

**Comment by slivne** [comment]
@tzach , @gleb-cloudius can we close this ?

**Comment by tzach** [comment]
Clearly my original cassandra-stress profile did not make sense.
Not sure its related to the problem, so I'm closing this and will try to reproduce a simpler, sane, example.
