### ISSUE TITLE
dist: io_tune packaging

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1065]
**Standard installation**

- iotune will NOT be a part of scylla service - remove the scylla.io.service
- User will have to run it manually - using a script call scylla_io_tune_setup (that will do the exact same thing the service does today.
- if they wont, and do not use --developer-mode, scylla init will fail will a proper error - scylla will not start (in the same manner it does not start if you run scylla on non XFS FS)

**AMI**

- For c3,m3,i2 we will use the evaluation formula we have (that takes the number of disks , cores etc.)
- For other instances we will set --developer-mode. if the user logins into the instance - he will get a developer-mode warning 
- No iotune on AWS

**Comment by dorlaor** [comment]
On Sun, Mar 20, 2016 at 5:59 PM, slivne <notifications@github.com> wrote:

> *Standard installation*
>
>    - iotune will NOT be a part of scylla service - remove the
>    scylla.io.service
>    - User will have to run it manually - using a script call
>    scylla_io_tune_setup (that will do the exact same thing the service does
>    today.
>
>
It should be fine (and easier) to run the iotune service instead of playing
with scripts.

**Comment by slivne** [comment]
On Sun, Mar 20, 2016 at 6:03 PM, Dor Laor <notifications@github.com> wrote:

> On Sun, Mar 20, 2016 at 5:59 PM, slivne <notifications@github.com> wrote:
>
> > *Standard installation*
> >
> > - iotune will NOT be a part of scylla service - remove the
> > scylla.io.service
> > - User will have to run it manually - using a script call
> > scylla_io_tune_setup (that will do the exact same thing the service does
> > today.
> >
> >
> It should be fine (and easier) to run the iotune service instead of playing
> with scripts.
>

Service is not interactive .., - yes I'll allow tzach to provide his view
on this

**Comment by tzach** [comment]
> It should be fine (and easier) to run the iotune service instead of playing
with scripts.

What the advantage of running a stand alone program as a service?
The disadvantage, as mentioned, is poor feedback to user.
Note that we have other install time scripts, like `scylla_raid_setup` , `scylla_ntp_setup` etc
None is running as service. Why is iotune different?

**Comment by avikivity** [comment]
Under systemd services can provide feedback.

**Comment by tzach** [comment]
> Under systemd services can provide feedback

It can, but I still do not get why it is better than just running the script directly.
If we can have a service provide a "progress bar" like feedback, I do not object to it.

**Comment by slivne** [comment]
The agreement is to have (currently for 1.0) scylla_io_setup script that will run io_tune in the same manner that we do that in the scylla.io-service

scylla-io.service will be removed.

**Comment by slivne** [comment]
@benoit-canet lets start by sending a cript that will do this

next step is to remove the io service and the depdency that others have on it - in some cases (such as the ami) you will need to change the code so that the dependency is on scylla-service

As we are changing this some items will become obsolete #1060, #1062 - maybe others as well
