### ISSUE TITLE
init - Unexpected error shutting down database: seastar::named_semaphore_aborted (Semaphore aborted: off-strategy compaction): aborting

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla#10666]
When stopping scylla this error propagates up to the database::stop() [like this](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/14/artifact/logs-full.debug.029/1653301262444_alternator_stream_tests.py%3A%3ATestAlternatorStreams%3A%3Atest_updated_shards_during_add_decommission_node/node6.log).
Sometimes it seems to reincarnate as [cross shard barrier exception](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-daily-debug/14/artifact/logs-full.debug.034/1653302563787_alternator_stream_tests.py%3A%3ATestAlternatorStreams%3A%3Atest_sequence_numbers_during_add_decommission_node/node8.log) in case parallel stopping of database decides to pick the barrier exception from some other shard.

The `offstrategy_compaction_task::do_run()` throws this exception on semaphore abort and `compaction_manager::stop_tasks` doesn't handle it?

@raphaelsc , @bhalevy

**Comment by bhalevy** [comment]
@raphaelsc I think we should treat semaphore aborted errors in all compaction_manager tasks in a similar way and turn them into `compaction_stopped_exception`.

**Comment by raphaelsc** [comment]
> @raphaelsc I think we should treat semaphore aborted errors in all compaction_manager tasks in a similar way and turn them into `compaction_stopped_exception`.

Makes sense. Will proceed with a fix soon. thanks everyone

**Comment by bhalevy** [comment]
This is still happening since 8f39547d89991dc251256fc9a57b3eeea5175e2b
built the exception handling on `semaphore_aborted` while `named_semaphore_aborted`
is not derived from it (by mistake).

I'll send a patch to seastar to fix that.
