### ISSUE TITLE
Files created by Scylla ignore XFS project inheritance bit

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla#10667]
Cross-isssue of already fixed issue from seaster to track down the backports in Scylla.
Seastar issue: https://github.com/scylladb/seastar/issues/1057
Fixed by https://github.com/scylladb/seastar/commit/a7145145b42617dfc1e973cf2d1849eec2212be4

Please backport it to 5.x

**Comment by avikivity** [comment]
Somewhat problematic as it's not a regression.

**Comment by avikivity** [comment]
Backported.
