### ISSUE TITLE
storage_service::restore_replica_count is not being waited on

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10672]
In `storage_service::handle_state_removing`:

https://github.com/scylladb/scylla/blob/19316dee94bf9cef6bcf2ae5f82078da9d78434a/service/storage_service.cc#L1108-L1111

I'm not sure why we're not co_awaiting it.

**Comment by asias** [comment]
This is on purpose.  restore_replica_count can last for hours to stream data. We can not block the gossip on_change callback for this long.

**Comment by bhalevy** [comment]
> This is on purpose. restore_replica_count can last for hours to stream data. We can not block the gossip on_change callback for this long.

So it needs to be tracked, aborted on shutdown, and stop() should wait on its future until it resolves.

**Comment by asias** [comment]
restore_replica_count is not used in new node_ops_cmd based node ops anymore. The code has to be there for a while to support older version without node_ops_cmd though.

I am not sure what is the best infrastructure to track this.

**Comment by bhalevy** [comment]
> I am not sure what is the best infrastructure to track this.

a gate maybe?

**Comment by avikivity** [comment]
Don't know if we want to backport this or not. Can the gate block shutdown?

**Comment by bhalevy** [comment]
> Don't know if we want to backport this or not. Can the gate block shutdown?

Yes, it should.  That's the reason we take it here, so table.stop() will wait on it.

**Comment by avikivity** [comment]
I meant, can it block shutdown indefinitely? So users will experience a node not shutting down on command?

**Comment by bhalevy** [comment]
> I meant, can it block shutdown indefinitely? So users will experience a node not shutting down on command?

`restore_replica_count` can take a long time since its calls removenode.
I see it subscribes to the storage_service::_abort_source when using streaming, but not when using `removenode_with_repair`, but it should do so.

**Comment by bhalevy** [comment]
#12429 was merged

**Comment by avikivity** [comment]
I still don't understand if we need to backport this.

**Comment by bhalevy** [comment]
We haven't observed this issue in the field so the need for backport is questionable.
If we do decide to backport, we'd obviously need cb0b728ed1af10b38bdb5a596bfd4547b8ec163e which is low risk.
We should also consider backporting https://github.com/scylladb/scylladb/issues/12429 on top of it so not to block for too long on shutdown and repair-based removenode is enabled.

**Comment by denesb** [comment]
Already in all live versions, removing label.
