### ISSUE TITLE
unable to replace node with dead node[unrecognised option '--ignore-dead-nodes']

### ISSUE THREAD

**Issue by JerryKwan** [scylladb/scylla#10683]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Name        : scylla
Arch        : x86_64
Version     : 4.6.3
Release     : 0.20220414.8bf149fdd

Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.9
Platform (physical/VM/cloud instance type/docker): Physical

There are 3 nodes, n1 (10.255.1xx.1), n2 (10.255.1xx.2), and n3(10.255.1xx.3)
n2 and n3 are down, when trying to start n2 with replace the old n2 by adding "replace_address_first_boot: 10.255.1xx.2" in /etc/scylla/scylla.yaml, and run 'systemctl start scylla-server', some error like this
```
 [shard 0] init - Startup failed: std::runtime_error (replace[81c8f690-dfc2-4fec-a661-4f39d9032b4e]: Nodes={10.255.1xx.3} needed for replace operation are down. It is highly recommended to fix the down nodes and try again. To proceed with best-effort mode which might cause data inconsistency, add --ignore-dead-nodes <list_of_dead_nodes>. E.g., scylla --ignore-dead-nodes 127.0.0.1,127.0.0.2)
```

But when trying to run scylla as this 
```
/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --ignore-dead-nodes 10.255.1xx.3
```
It prompts “error: unrecognised option '--ignore-dead-nodes'”
How should we solve the problem and complete replace the old one?

**Comment by asias** [comment]
The feature ignore dead node for replace is not included in 4.6.3. 

```
 ignore_dead_nodes_for_replace(this, "ignore_dead_nodes_for_replace", value_status::Used, "", "List dead nodes to ingore for replace operation. E.g., scylla --ignore-dead-nodes-for-replace 127.0.0.1,127.0.0.2")
```

**Comment by asias** [comment]
In your case, try to fix node n2 and n3 if possible. It is not recommend to use `--ignore-dead-nodes-for-replace` if the node can be fixed.

**Comment by asias** [comment]
In recent scylla master, one would see:

```
            auto msg = format("replace[{}]: Nodes={} needed for replace operation are down. It is highly recommended to fix the down nodes and try again. To proceed with best-effort mode which might cause data inconsistency, add --ignore-dead-nodes-for-replace <list_of_dead_nodes>. E.g., scylla --ignore-dead-nodes-for-replace 127.0.0.1,127.0.0.2", uuid, nodes_down);

```

**Comment by JerryKwan** [comment]
@asias Yes, the latest version 5.x has this, but the problem is there is no option like this with version 4.6.3 although the error message prompted it has

**Comment by asias** [comment]
> @asias Yes, the latest version 5.x has this, but the problem is there is no option like this with version 4.6.3 although the error message prompted it has

Yes, I understand this. The core infrastructure for the new replace ops that shows the log is introduced before the ignore dead node option. 

We may have a backport for the 4.6.x release.

**Comment by JerryKwan** [comment]
@asias Is there any ETA for version 5.0 for production use?

**Comment by asias** [comment]
It is on the corner. It is now scylla-5.0.rc6. 

Even if with 5.0, I still recommend to fix the dead node instead of replace it directly in case more than one nodes are down.

**Comment by JerryKwan** [comment]
It's ideal to fix the deal node. but sometimes it's not available. Considering this scenarios, the disk is broken / with bad sectors.
The point is I am not sure how to recover the system with version 4.6.3. The only option is to re-install the system on the dead nodes?

**Comment by asias** [comment]
> It's ideal to fix the deal node. but sometimes it's not available. Considering this scenarios, the disk is broken / with bad sectors. The point is I am not sure how to recover the system with version 4.6.3. The only option is to re-install the system on the dead nodes?

On 4.6.3, you can try remove the dead node (node2, node3) on node1 with removenode by:

$ curl -X POST "http://127.0.0.1:10000/storage_service/remove_node/?host_id=7bd303e9-4c7b-4915-84f6-343d0dbd0002&ignore_nodes=127.0.0.2,127.0.0.3"

$ curl -X POST "http://127.0.0.1:10000/storage_service/remove_node/?host_id=7bd303e9-4c7b-4915-84f6-343d0dbd0003&ignore_nodes=127.0.0.2,127.0.0.3"

n1:
ip 127.0.0.1
host_id 7bd303e9-4c7b-4915-84f6-343d0dbd0001

n2:
ip 127.0.0.2
host_id 7bd303e9-4c7b-4915-84f6-343d0dbd0002

n3:
ip 127.0.0.3
host_id 7bd303e9-4c7b-4915-84f6-343d0dbd0003

**Comment by asias** [comment]
> @asias Thank you for the instructions, It works for me. BTW, where is the document about this APIs? Seems like it is more powerful than nodetool commands

E.g., https://github.com/scylladb/scylla/blob/master/api/api-doc/storage_service.json#L1227

The nodetool from 5.0 has the --ignore-dead-nodes support. 

 nodetool removenode --ignore-dead-nodes <list_of_dead_nodes_to_ignore> <host_id>

**Comment by JerryKwan** [comment]
@asias Thank you for helping on this. 
we can mark this issue as closed
