### ISSUE TITLE
Add PreparedStatementsRatio metric

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1068]
Cassandra have PreparedStatementsRatio[1] gauge return the ratio between
regularStatementsExecuted and preparedStatementsExecuted

This is usrful metric to have and build alert on.
If the ratio change in favor of the first

[1] https://github.com/apache/cassandra/blob/cassandra-2.1/src/java/org/apache/cassandra/metrics/CQLMetrics.java#L50

**Comment by slivne** [comment]
@vladzcloudius as I asked you to add some stats - this is probably directly related - lets handle it as well

**Comment by vladzcloudius** [comment]
@tzach According to the referenced source the ratio is between prepared statements executed and total executed. In other words it's a portion of prepared statements in all executed statements.
