### ISSUE TITLE
Add collectd metrics

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#1069]
Currently we use too few metrics and it's desirable to enable more plugins.
The current config file is under dist/common/collectd.d/scylla.conf and looks like this:

```
LoadPlugin network
LoadPlugin unixsock
<Plugin network>
        Listen "127.0.0.1" "25826"
</Plugin>
<Plugin unixsock>
        SocketFile "/var/run/collectd-unixsock"
        SocketPerms "0666"
</Plugin>
```

Let's add ethstat, disk stat, cpu stat and many more.
Let's also have a 1-3sec Interval (global config) updates.

**Comment by avikivity** [comment]
1-3 sec intervals generate an enormous load on the collection servers when you have many cores, it needs to be less frequent.

**Comment by tgrabiec** [comment]
Maybe we should have levels for counters like we have for logging? SMP queue counters for example send a lot of data on large machines, we have a counter for each core pair, but they are not important for basic monitoring.

**Comment by dorlaor** [comment]
I agree, better control them through our configuration file.
As for the 1-3 sec I asked for, it's not for scylla config but for the
collectd
itself. It has a global 'Interval' parameter which defaults to 10sec.

**Comment by avikivity** [comment]
The ability to play with individual counters as well as with the rate through the API can help a lot, up the frequency while actively looking, drop it back for normal operation.  

We can default the smp counters to off (and instead provide a per-shard counter for smp, instead of per-queue, avoiding quadratic explosion).

**Comment by slivne** [comment]
in prometheus we support more metrics with node-explorer
