### ISSUE TITLE
Unrecognized files in table data directory triggers assert failure

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#10697]
Putting any file unrecognizable to scylla as a valid sstable component will trigger an assert failure as follows:
```
INFO  2022-05-30 17:36:23,088 [shard 0] database - Populating Keyspace ks1                                                                                                                                                                                    
INFO  2022-05-30 17:36:23,088 [shard 0] database - Keyspace ks1: Reading CF table1 id=0a75f5b0-e024-11ec-96c6-c7dc2b0ff2ed version=21acc750-47d1-3167-a77d-ec3c544d1525                                                                                       terminate called after throwing an instance of 'seastar::internal::backtraced<std::runtime_error>'                                                                                                                                                            
  what():  directory_lister not closed when destroyed Backtrace: 0x3443cce 0x34441c0 0x34444c8 0x120c902 0x32f08f3 0x32f0794 0x32f0604 0x20b2a05 0x153b40e 0x3315ba4 0x3316e97 0x33161c9 0x32cdd4f 0x32cd23e 0xf1eb7e 0xf1dae0 /lib64/libc.so.6+0x4043f /lib64
/libc.so.6+0x404ef 0xf1d3e4
```
Reproducer: creating an empty `out.json` file in `/var/lib/scylla/data/system/large_rows-*/`.

@bhalevy

**Comment by bhalevy** [comment]
We aren't supposed to start if there are files we don't recognize in the data directory,
but the assertion is not elegant and can probably be avoided.

**Comment by denesb** [comment]
Agree. The assertion (or rather `std::terminate`) is probably called because there is an exception in a `noexcept` context. This should be avoided as the resulting message is scary and it is not at all clear what the problem was. I was copying an unclean data dir and was expecting problems related to this so removing these extra files was the first thing I tried and the error gone away.
We should print a clear message with the file we choked on, then do a clean shutdown instead.

**Comment by avikivity** [comment]
Should we backport this?

Pro: looks like a safe backport and prevents a crash
Con: no one ever complained, not a regression

@bhalevy

**Comment by bhalevy** [comment]
> Should we backport this?
> 
> Pro: looks like a safe backport and prevents a crash Con: no one ever complained, not a regression
> 
> @bhalevy

The scenario in this issue doesn't happen under normal circumnstances. It takes a human error to hit it, so I it doesn't warrant a backport.

**Comment by avikivity** [comment]
Ok, not backporting.
