### ISSUE TITLE
YCSB got an overload exception (Too many in flight hints) during adding a new node

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#10702]
## Installation details

Kernel Version: 5.13.0-1022-aws
Scylla version (or git commit hash): `5.0~rc5-20220515.9da666e77` with build-id `5992da65161c733b3f85b8c93bbbb5151d4d321c`
Cluster size: 6 nodes (i3.4xlarge)

Scylla Nodes used in this run:
- alternator-3h-multidc-5-0-db-node-a8368f72-7 (3.250.194.158 | 3.250.194.158) (shards: 14)
- alternator-3h-multidc-5-0-db-node-a8368f72-6 (3.237.51.133 | 3.237.51.133) (shards: 14)
- alternator-3h-multidc-5-0-db-node-a8368f72-5 (34.232.48.183 | 34.232.48.183) (shards: 14)
- alternator-3h-multidc-5-0-db-node-a8368f72-4 (3.238.195.237 | 3.238.195.237) (shards: 14)
- alternator-3h-multidc-5-0-db-node-a8368f72-3 (34.243.207.223 | 34.243.207.223) (shards: 14)
- alternator-3h-multidc-5-0-db-node-a8368f72-2 (54.170.183.99 | 54.170.183.99) (shards: 14)
- alternator-3h-multidc-5-0-db-node-a8368f72-1 (34.247.184.71 | 34.247.184.71) (shards: 14)

OS / Image: `ami-028dc71f18948aff6 ami-03731266bb9dfb68f` (aws: eu-west-1)

Test: `longevity-alternator-3h-multidc-test`
Test id: `a8368f72-24b1-493e-bce8-edca6b9886ee`
Test name: `scylla-5.0/longevity/longevity-alternator-3h-multidc-test`
Test config file(s):

- [longevity-alternator-3h-multidc.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/36019f38f4ec4a78f8cf40d2b58f887ab5c21c13/test-cases/longevity/longevity-alternator-3h-multidc.yaml)

## Issue description

**>>>>>>>**
Scenario:
1. Running YCSB Alternator load on multi-dc cluster (LWT + a non LWT tables)
2. Run a nemesis of disrupt_remove_node_then_add_node: remove a node, then add a new node and initialize it (repair-based).
3. The issue happens at 11:30, while running a repair on a newly added node after we removed a terminated node.
4. YCSB got an error of overload with "Too many in flight hints"
5. The same scenario runs fine in scylla 4.6 and issue is not reproduced (node is added successfully during stress).
error:
```

2022-05-22 11:31:26.749: (YcsbStressEvent Severity.ERROR) period_type=not-set event_id=c497cbdf-5c2d-4b12-8bc4-268867ebd96b: type=error node=Node alternator-3h-multidc-5-0-loader-node-a8368f72-2 [34.247.167.126 | 10.0.1.196] (seed: False)
stress_cmd=bin/ycsb run dynamodb -P workloads/workloadc -threads 20 -p readproportion=0.5 -p updateproportion=0.5 -p recordcount=6990500 -p fieldcount=10 -p fieldlength=512 -p operationcount=200200300 -p dataintegrity=true -p table=usertable_no_lwt -p maxexecutiontime=10800 -s  -P /tmp/dynamodb.properties
errors:
9856294 [Thread-9] ERROR site.ycsb.db.DynamoDBClient  -com.amazonaws.services.dynamodbv2.model.InternalServerErrorException: Internal server error: exceptions::overloaded_exception (Too many in flight hints: 10485768) (Service: AmazonDynamoDBv2; Status Code: 500; Error Code: InternalServerError; Request ID: null; Proxy: null)
```

running nemesis details:
```


disrupt_remove_node_then_add_node | alternator-3h-multidc-5-0-db-node-a8368f72-2 | Succeeded | 2022-05-22 11:00:53 | 2022-05-22 12:09:53
-- | -- | -- | -- | --
Nemesis InformationClass: SisyphusName: disrupt_remove_node_then_add_nodeStatus: SucceededDuration: 1 hour, 9 minutesTarget InformationName: alternator-3h-multidc-5-0-db-node-a8368f72-2Public IP: 54.170.183.99Private IP: 54.170.183.99State: terminatedShards: 14

```

**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor a8368f72-24b1-493e-bce8-edca6b9886ee`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a8368f72-24b1-493e-bce8-edca6b9886ee)
- Show all stored logs command: `$ hydra investigate show-logs a8368f72-24b1-493e-bce8-edca6b9886ee`

## Logs:
- **db-cluster-a8368f72.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/db-cluster-a8368f72.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/db-cluster-a8368f72.tar.gz)
- **monitor-set-a8368f72.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/monitor-set-a8368f72.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/monitor-set-a8368f72.tar.gz)
- **loader-set-a8368f72.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/loader-set-a8368f72.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/loader-set-a8368f72.tar.gz)
- **sct-runner-a8368f72.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/sct-runner-a8368f72.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/sct-runner-a8368f72.tar.gz)
- **parallel-timelines-report-a8368f72.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/parallel-timelines-report-a8368f72.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a8368f72-24b1-493e-bce8-edca6b9886ee/20220522_123616/parallel-timelines-report-a8368f72.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-alternator-3h-multidc-test/4/)

**Comment by yarongilor** [comment]
A comparison test using same SCT branch-5.0 with scylla 4.6 passed ok with the following details:

> So we need a run with branch-5.0 and use Scylla 4.6.0 to compare.

The error is not reproduced. didn't get any overload exception and RemoveNodeThenAddNode nemesis passed ok.

![Screenshot from 2022-05-26 12-47-45](https://user-images.githubusercontent.com/9427929/170463747-91f6f6be-85ed-45b3-98b0-4704d6fe040c.png)

*Installation details*
Kernel version: `5.11.0-1022-aws`
Scylla version (or git commit hash): `4.6.3-0.20220414.8bf149fdd with build-id 8d16d8972498cc769071ff25309b009eb77bf77a`
Cluster size: 3 3 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   alternator-3h-multidc-5-0-db-node-d4203c75-1 (54.154.40.142 | 10.0.1.212): 14 shards
   alternator-3h-multidc-5-0-db-node-d4203c75-2 (18.203.231.76 | 10.0.1.160): 14 shards
   alternator-3h-multidc-5-0-db-node-d4203c75-4 (34.205.26.21 | 10.0.3.32): 14 shards
   alternator-3h-multidc-5-0-db-node-d4203c75-5 (3.234.154.167 | 10.0.2.50): 14 shards
   alternator-3h-multidc-5-0-db-node-d4203c75-6 (3.228.14.212 | 10.0.3.24): 14 shards
   alternator-3h-multidc-5-0-db-node-d4203c75-7 (34.249.100.41 | 10.0.3.63): 14 shards
Scylla running with shards number (terminated nodes):
   alternator-3h-multidc-5-0-db-node-d4203c75-3 (54.216.119.238 | 10.0.3.52): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-03d8b6dcd63bd4e24 ami-09c658571b2d46d18` (aws: eu-west-1 us-east-1)


Test: `longevity-alternator-3h-multidc-test_repro`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-alternator-3h-multidc.yaml]([https://github.com/scylladb/scylla-cluster-tests/blob/8584390cb25ea782b18acef4a6d77099be58b0bc/test-cases/longevity/longevity-alternator-3h-multidc.yaml](https://www.google.com/url?q=https://github.com/scylladb/scylla-cluster-tests/blob/8584390cb25ea782b18acef4a6d77099be58b0bc/test-cases/longevity/longevity-alternator-3h-multidc.yaml&source=gmail-html&ust=1653644328414000&usg=AOvVaw3ZzTgdUbhhlESKQsb3Cb_B))


**Issue description**

====================================

PUT ISSUE DESCRIPTION HERE


====================================






Restore Monitor Stack command: `$ hydra investigate show-monitor d4203c75-a33d-4a28-b1f4-d5922483925e`
Restore monitor on AWS instance using [Jenkins job]([https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch=branch-5.0&test_id=d4203c75-a33d-4a28-b1f4-d5922483925e](https://www.google.com/url?q=https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?sct_branch%3Dbranch-5.0%26test_id%3Dd4203c75-a33d-4a28-b1f4-d5922483925e&source=gmail-html&ust=1653644328414000&usg=AOvVaw3X6kkLZYzjvOA99qGwrIMe))
Show all stored logs command: `$ hydra investigate show-logs d4203c75-a33d-4a28-b1f4-d5922483925e`

Test id: `d4203c75-a33d-4a28-b1f4-d5922483925e`


Logs:
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-alternator-20220525_214439-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-alternator-20220525_214439-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-alternator-20220525_214439-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-alternator-20220525_214439-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png)&source=gmail-html&ust=1653644328414000&usg=AOvVaw1I6yp_Z8OWJ7jZlmcvLgcD)
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-longevity-alternator-3h-multidc-test_repro-scylla-per-server-metrics-nemesis-20220525_214132-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-longevity-alternator-3h-multidc-test_repro-scylla-per-server-metrics-nemesis-20220525_214132-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-longevity-alternator-3h-multidc-test_repro-scylla-per-server-metrics-nemesis-20220525_214132-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-longevity-alternator-3h-multidc-test_repro-scylla-per-server-metrics-nemesis-20220525_214132-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png)&source=gmail-html&ust=1653644328414000&usg=AOvVaw3XxilJa2ZaSGI_eBRMsnnV)
grafana - [[https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-overview-20220525_213857-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-overview-20220525_213857-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-overview-20220525_213857-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_213857/grafana-screenshot-overview-20220525_213857-alternator-3h-multidc-5-0-monitor-node-d4203c75-1.png)&source=gmail-html&ust=1653644328414000&usg=AOvVaw2ohtwmCM8LkbhktbkQ7zBM)
db-cluster - [[https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/db-cluster-d4203c75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/db-cluster-d4203c75.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/db-cluster-d4203c75.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/db-cluster-d4203c75.tar.gz)&source=gmail-html&ust=1653644328414000&usg=AOvVaw1QBKFn57uINfm3lJYrtu8V)
loader-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/loader-set-d4203c75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/loader-set-d4203c75.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/loader-set-d4203c75.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/loader-set-d4203c75.tar.gz)&source=gmail-html&ust=1653644328415000&usg=AOvVaw31rexAIX70-MIz6UQaxCVG)
monitor-set - [[https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/monitor-set-d4203c75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/monitor-set-d4203c75.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/monitor-set-d4203c75.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/monitor-set-d4203c75.tar.gz)&source=gmail-html&ust=1653644328415000&usg=AOvVaw19YSw46sNdOIiAriWh0QpB)
sct - [[https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/sct-runner-d4203c75.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/sct-runner-d4203c75.tar.gz)](https://www.google.com/url?q=https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/sct-runner-d4203c75.tar.gz%255D(https://cloudius-jenkins-test.s3.amazonaws.com/d4203c75-a33d-4a28-b1f4-d5922483925e/20220525_220823/sct-runner-d4203c75.tar.gz)&source=gmail-html&ust=1653644328415000&usg=AOvVaw3TMuTWkDh-u9k3SKd0FV8p)


[Jenkins job URL]([https://jenkins.scylladb.com/job/scylla-5.0/job/SCT_Reproducers/job/longevity-alternator-3h-multidc-test_repro/2/](https://www.google.com/url?q=https://jenkins.scylladb.com/job/scylla-5.0/job/SCT_Reproducers/job/longevity-alternator-3h-multidc-test_repro/2/&source=gmail-html&ust=1653644328415000&usg=AOvVaw2RQYJyxVsK4TvmFlUe_Cb1))

**Comment by slivne** [comment]
@slivne check if its the same issue we had with the gemini issue https://github.com/scylladb/scylla/issues/10652

**Comment by slivne** [comment]
I don't think the analysis of the test is correct

![Screenshot from 2022-06-12 23-36-59](https://user-images.githubusercontent.com/3465480/173252688-94e44ed9-cb9d-4fea-93ab-a6bbdb35acdd.png)

the load stopped prior to 11:48

![Screenshot from 2022-06-12 23-34-24](https://user-images.githubusercontent.com/3465480/173252613-473151b1-c442-440a-8202-a419262bbde8.png)

the removenode was executed at 11:49 
the add ndoe was executed at 11:49:45

You can see the test ended prior to the removenode and add node being executed

![Screenshot from 2022-06-12 23-34-45](https://user-images.githubusercontent.com/3465480/173252657-04d7bcc9-a53c-44d5-8fdb-74071ff36bf8.png)

**Comment by slivne** [comment]
Yet its clear that the duration that this nemesis is running is longer then what we had in 4.6 it took less then an hour on 4.6 and here it takes 1.5+ hours till it fails so something maybe wrong

Looking at advanced dashboard commitlog is working hard

![Screenshot from 2022-06-12 23-41-45](https://user-images.githubusercontent.com/3465480/173252850-98a020b4-9c50-4831-a491-5744908206c4.png)

![Screenshot from 2022-06-12 23-42-00](https://user-images.githubusercontent.com/3465480/173252846-3ed34bc9-9fbc-4b96-ace6-9c7ed8b55c68.png)


Trying to compare that to 4.6.3 run

**Comment by slivne** [comment]
The advanced i/o dashboard of 4.6 looks simillar

![Screenshot from 2022-06-12 23-58-56](https://user-images.githubusercontent.com/3465480/173253384-c6f8b8e3-00ba-4b58-8439-8cbc8713ef4d.png)
![Screenshot from 2022-06-12 23-58-47](https://user-images.githubusercontent.com/3465480/173253386-fb773534-c5f0-42ff-9e3b-6d24793428bf.png)

**Comment by slivne** [comment]
checking hints

per second the amount of hints accumulated seems the same

5.0
![Screenshot from 2022-06-13 00-00-31](https://user-images.githubusercontent.com/3465480/173253492-f0518703-5e92-4aee-a190-979fd1327d3b.png)

4.6

![Screenshot from 2022-06-13 00-00-06](https://user-images.githubusercontent.com/3465480/173253494-77202f7a-1c10-4c03-bf33-b87148a984ab.png)

**Comment by slivne** [comment]
hints comparison

5.0
![Screenshot from 2022-06-13 00-24-02](https://user-images.githubusercontent.com/3465480/173254327-0c5945e7-1bc4-4063-93a0-61f187d361ac.png)

4.6

![Screenshot from 2022-06-13 00-25-09](https://user-images.githubusercontent.com/3465480/173254330-62593464-2cc0-4a33-bed3-71e4d91254a8.png)

so indeed we accumulated more hints - but I am not sure this explains anything

**Comment by slivne** [comment]
To summarize

in 5.0 we accumulated 15M hints over an hour
in 4.6 we accumulated 7.5M hints over 30 minutes 

So yes we have more hints - but it does not clarify the why - I couldn't prove its related to #10704 but maybe it is does - we can see huge I/O operations in commitlog and the fix is related to that (increasing the buffer size and aligning with what commitlog actually uses 128K not less).

So lets wait for 5.0.rc8 and run again

**Comment by roydahan** [comment]
@yarongilor please re-run with RC8.

**Comment by yarongilor** [comment]
Not reproduced in RC8. Test passed in:
https://jenkins.scylladb.com/job/scylla-5.0/job/longevity/job/longevity-alternator-3h-multidc-test/5/
