### ISSUE TITLE
'nodetool refresh' fails with 'No such file or directory' error

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#1073]
scylla HEAD: 6d031b4c6b40048e81379e4cb6f140a42e582425
seastar HEAD: c193821f9a061c80fbb0c2ae12061f022f3321ab

Setup: 
AWS instance: c3.8xlarge
OS: Ubuntu 14.04 with 3.19.0-56-generic kernel
scylla packages: 
```
$ dpkg-query -l "*scylla*"
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                        Version                    Architecture               Description
+++-===========================================-==========================-==========================-============================================================================================
ii  scylla-jmx                                  0.19-20160308.ac51e7f-ubun all                        Scylla JMX server binaries
ii  scylla-server                               0.19-20160308.4e3b98f-ubun amd64                      Scylla database server binaries
ii  scylla-server-build-deps                    0.18.1-20160320.bf71575-ub all                        build-dependencies for scylla-server
ii  scylla-tools                                0.19-20160308.0bd0b18-ubun all                        Scylla database tools
```

Note: make sure to change the NOFILE rlimit to 200000. Otherwise you'll hit `Too many files` error.

Steps to reproduce:
1. Clean the previous data: `sudo rm -rf /var/lib/scylla/data/* /var/lib/scylla/commitlog/*`
2. Start a scylla server: `sudo ./build/release/scylla --developer-mode 1` (I didn't configure XFS and this is the only reason for a `developer mode`).
3. Run `cassandra-stress` for 30 seconds: `cassandra-stress "write" "no-warmup" "duration=30s" "-rate" "threads=500" "-mode" "native" "cql3" "-node" 127.0.0.1`
4. Restart the server.
5. Start the jmx: `sudo /usr/lib/scylla/jmx/scylla-jmx -l /usr/lib/scylla/jmx`
6. Run a refresh command: `nodetool -h 127.0.0.1 refresh -- keyspace1 standard1`

The output is:
```
$ nodetool -h 127.0.0.1 refresh -- keyspace1 standard1
error: No such file or directory
-- StackTrace --
java.lang.RuntimeException: No such file or directory
        at com.scylladb.jmx.api.APIClient.getException(APIClient.java:115)
        at com.scylladb.jmx.api.APIClient.post(APIClient.java:102)
        at org.apache.cassandra.service.StorageService.loadNewSSTables(StorageService.java:1123)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:75)
        at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:279)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
        at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
        at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
        at com.sun.jmx.mbeanserver.PerInterface.invoke(PerInterface.java:138)
        at com.sun.jmx.mbeanserver.MBeanSupport.invoke(MBeanSupport.java:252)
        at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
        at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
        at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1488)
        at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:97)
        at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1329)
        at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1421)
        at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:849)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:322)
        at sun.rmi.transport.Transport$2.run(Transport.java:202)
        at sun.rmi.transport.Transport$2.run(Transport.java:199)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.Transport.serviceCall(Transport.java:198)
        at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:567)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.access$400(TCPTransport.java:619)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:684)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler$1.run(TCPTransport.java:681)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:681)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```
Scylla doesn't print any error however:
```
INFO  2016-03-21 14:52:32,477 [shard 16] storage_service - CF keyspace1.standard1 at shard 16 had SSTables writes disabled for 236974 usec
INFO  2016-03-21 14:52:32,477 [shard 18] storage_service - CF keyspace1.standard1 at shard 18 had SSTables writes disabled for 236978 usec
INFO  2016-03-21 14:52:32,477 [shard 20] storage_service - CF keyspace1.standard1 at shard 20 had SSTables writes disabled for 236983 usec
INFO  2016-03-21 14:52:32,477 [shard 11] storage_service - CF keyspace1.standard1 at shard 11 had SSTables writes disabled for 236966 usec
INFO  2016-03-21 14:52:32,477 [shard 21] storage_service - CF keyspace1.standard1 at shard 21 had SSTables writes disabled for 236988 usec
INFO  2016-03-21 14:52:32,477 [shard 15] storage_service - CF keyspace1.standard1 at shard 15 had SSTables writes disabled for 236972 usec
INFO  2016-03-21 14:52:32,477 [shard 22] storage_service - CF keyspace1.standard1 at shard 22 had SSTables writes disabled for 236998 usec
INFO  2016-03-21 14:52:32,477 [shard 27] storage_service - CF keyspace1.standard1 at shard 27 had SSTables writes disabled for 236991 usec
INFO  2016-03-21 14:52:32,477 [shard 29] storage_service - CF keyspace1.standard1 at shard 29 had SSTables writes disabled for 236995 usec
INFO  2016-03-21 14:52:32,477 [shard 31] storage_service - CF keyspace1.standard1 at shard 31 had SSTables writes disabled for 236994 usec
INFO  2016-03-21 14:52:32,477 [shard 25] storage_service - CF keyspace1.standard1 at shard 25 had SSTables writes disabled for 236997 usec
INFO  2016-03-21 14:52:32,477 [shard 12] storage_service - CF keyspace1.standard1 at shard 12 had SSTables writes disabled for 236966 usec
INFO  2016-03-21 14:52:32,477 [shard 24] storage_service - CF keyspace1.standard1 at shard 24 had SSTables writes disabled for 236986 usec
INFO  2016-03-21 14:52:32,477 [shard 23] storage_service - CF keyspace1.standard1 at shard 23 had SSTables writes disabled for 236992 usec
INFO  2016-03-21 14:52:32,477 [shard 30] storage_service - CF keyspace1.standard1 at shard 30 had SSTables writes disabled for 236994 usec
INFO  2016-03-21 14:52:32,477 [shard 19] storage_service - CF keyspace1.standard1 at shard 19 had SSTables writes disabled for 236985 usec
INFO  2016-03-21 14:52:32,479 [shard 14] storage_service - CF keyspace1.standard1 at shard 14 had SSTables writes disabled for 238655 usec
INFO  2016-03-21 14:52:35,241 [shard 9] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:35,393 [shard 14] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:35,407 [shard 11] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:35,520 [shard 28] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:35,711 [shard 13] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:35,733 [shard 7] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:35,947 [shard 8] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:36,190 [shard 10] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:36,344 [shard 3] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:36,344 [shard 6] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:36,572 [shard 5] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:36,586 [shard 22] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:36,594 [shard 12] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:36,716 [shard 15] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:36,717 [shard 4] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:36,753 [shard 21] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:36,765 [shard 2] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:36,770 [shard 20] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:36,774 [shard 0] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:36,780 [shard 16] storage_service - Done loading new SSTables for keyspace1.standard1
INFO  2016-03-21 14:52:36,780 [shard 1] storage_service - Done loading new SSTables for keyspace1.standard1
```

We may see that shard 17 for example didn't print the `Done` message, so probably there were some  problems on that shard.

**Comment by raphaelsc** [comment]
@vladzcloudius, @glommer 

I added some logs, and I found that Scylla is potentially deleting an existing SSTable that it tries to load with refresh.

Let me use generation 4 as an example. At boot stage, generation 4 is marked for deletion by shards 1, 2 and 3, meaning that it belongs to shard 0 (log message says which shard(s) a generation belongs to).
```
[shard 1] database - Marking /data/data/keyspace1/standard1-c36709d0efbf11e5b5c4000000000001/keyspace1-standard1-ka-4-Data.db for deletion, shards[0-0]
[shard 2] database - Marking /data/data/keyspace1/standard1-c36709d0efbf11e5b5c4000000000001/keyspace1-standard1-ka-4-Data.db for deletion, shards[0-0]
[shard 3] database - Marking /data/data/keyspace1/standard1-c36709d0efbf11e5b5c4000000000001/keyspace1-standard1-ka-4-Data.db for deletion, shards[0-0]
```

Now when refresh is called, generation 4 somehow belongs to shard 1 and is marked for deletion by shards 0, 2 and 3. When generation 4 is marked for deletion by shard 0, it will be deleted as soon as the SSTable object is destroyed. That's because all shards now agree on deletion of generation 4.

Look at the following log messages (see that generation 4 now belongs to shard 1):
```
[shard 0] database - Marking /data/data/keyspace1/standard1-c36709d0efbf11e5b5c4000000000001/keyspace1-standard1-ka-4-Data.db for deletion, shards[1-1]
[shard 0] sstable - Deleting sstable with: /data/data/keyspace1/standard1-c36709d0efbf11e5b5c4000000000001/keyspace1-standard1-ka-4-TOC.txt
```

It's completely strange that at different points the same generation is said to belong to different shards. That would definitely fool our mechanism for deletion of generations.
To determine which shard(s) a sstable belongs to, the following code is used:
```
static bool belongs_to_current_shard(const schema& s, const partition_key& first, const partition_key& last) {
    auto key_shard = [&s] (const partition_key& pk) {
        auto token = dht::global_partitioner().get_token(s, pk);
        return dht::shard_of(token);
    };
    auto s1 = key_shard(first);
    auto s2 = key_shard(last);
    auto me = engine().cpu_id();
    return (s1 <= me) && (me <= s2);
}
```
My current hypothesis is that some relevant initialization happens after SSTable loading, so SSTable X will belong to different shards at different points. I need to check this. It could be a regression, but I really don't know yet. A lot of re-ordering was done in the initialization code recently, so regression is a good guess.

The root of 'No such file or directory' is the following: Generation 4 was deleted, so other shard found it deleted when trying to load some information.

There is another problem with refresh in that it incorrectly determines what's a new SSTable. I found that column_family::disable_sstable_write() incorrectly relies on ordering of column_family::_sstables to get highest generation (I need to double check this). The column family standard1 has generations from 1 to 14, but refresh was thinking that generations from 3 on belong to new sstables, look:
```
[shard 0] storage_service - Loading new sstables with generation numbers larger or equal than 3
```
To solve this specific problem, we could iterate through the map and obtain the highest generation. The operation is O(n), but it's only done once, and it's not that performance sensitive anyway.

**Comment by raphaelsc** [comment]
Using AWS, I verified that the problem is not a regression caused by recent changes on initialization code. I tested it up to Scylla 0.16, and the problem still happens.

**Comment by raphaelsc** [comment]
I found the actual problem. It's a problem with reshuffle which sets a new generation for all sstables in a column family, and thus, _shards_agreeing_to_remove_sstable becomes outdated. sstable::set_generation() needs to update _shards_agreeing_to_remove_sstable. However, that only happens because we are re-using an existing generation given that column_family::disable_sstable_write() isn't returning maximum seen sstable. Fixing that would fix this issue, I think. I will write a patch tomorrow and confirm that the issue is indeed fixed.

**Comment by vladzcloudius** [comment]
On Mar 22, 2016 8:59 AM, "Raphael Carvalho" <notifications@github.com>
wrote:
>
> I found the actual problem. It's a problem with reshuffle which sets a
new generation for all sstables in a column family, and thus,
_shards_agreeing_to_remove_sstable becomes outdated.
sstable::set_generation() needs to update
_shards_agreeing_to_remove_sstable. However, that only happens because we
are re-using an existing generation given that
column_family::disable_sstable_write() isn't returning maximum seen
sstable. Fixing that would fix this issue, I think. I will write a patch
tomorrow and confirm that the issue is indeed fixed.

Good catch, Raph!
The reasoning above correlates very well with what i saw yesterday: the
initial generations were 32-63 and after reshuffling they were 1-32 and
there were some strange things around generation 32.

**Comment by slivne** [comment]
Can yoy pleade ypdate the issue

On the daily we agreed that refresh shpukd not touch old files only new
found files

**Comment by vladzcloudius** [comment]
On Mar 22, 2016 20:16, "slivne" <notifications@github.com> wrote:
>
> Can yoy pleade ypdate the issue

Raphael is working on a fix and hopefully the series would hit the mailing
list today.

A summary of today's progress:
1) We've found a bug in the function that calculates the max generation
number. Fixing this would resolve #1073 and would prevent scylla from
touching the existing sstables but would not address the case when the
newly added sstable has a lower generation number than the lowest
generation number of the existing sstables. The current code would just
ignore this new sstable.
2) We've come up to the laconic solution of the problem above.

>
> On the daily we agreed that refresh shpukd not touch old files only new
> found files
>
> On Mar 22, 2016 10:00 AM, "vladzcloudius" <notifications@github.com>
wrote:
>
> > On Mar 22, 2016 8:59 AM, "Raphael Carvalho" <notifications@github.com>
> > wrote:
> > >
> > > I found the actual problem. It's a problem with reshuffle which sets a
> > new generation for all sstables in a column family, and thus,
> > _shards_agreeing_to_remove_sstable becomes outdated.
> > sstable::set_generation() needs to update
> > _shards_agreeing_to_remove_sstable. However, that only happens because
we

**Comment by raphaelsc** [comment]
I am about to cook a patch to fix refresh. The first problem is that column_family::disable_sstable_write() was incorrectly using end() method to get last element of _sstables, but instead it was reading garbage. Fix to this problem is about using rbegin() instead.

The second problem is that we were passing maximum generation to reshuffle_sstables, so sstable with maximum generation would be said to be a new sstable. Instead, we should pass maximum generation + 1, which will be used as starting point to new sstables. 
We will not longer say that a sstable is a new sstable if its generation is greater or equal than maximum generation (because new sstables could have smaller generations). Instead, we will say that a sstable is new if it's not contained in column_family::_sstables (map containing all live sstables).
