### ISSUE TITLE
repair_additional_test.py:RepairAdditionalTest.repair_option_pr_test is failing 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1074]
this test started to fail in 

http://jenkins.cloudius-systems.com:8080/job/urchin-dtest/label=monster,mode=release,smp=1/798/testReport/junit/repair_additional_test/RepairAdditionalTest/repair_option_pr_test/

e52b869b250305d02c4d7e168dcdb69632633713

it passed in 

http://jenkins.cloudius-systems.com:8080/job/urchin-dtest/label=monster,mode=release,smp=1/797/

based on head

4cc589872d0ab629be4440e9dc1e2e1b2faf4604

**Comment by slivne** [comment]
following glauber's repair/streaming patches does not reproduce on 6fe88a663f6bdbc5d7a617ae3f29e06b0256c301

(3 out of 3 passed)

**Comment by nyh** [comment]
@slivne can you please clarify - you closed this issue, and after closing it, assigned it to me - why?

After recent changes to streaming and before the spree of fixing what broke, several of the repair tests failed, and this was probably one of them. I don't think we need to pay special attention to this one in particular.

**Comment by slivne** [comment]
@nyh - by mistake - nothing todo with this bug
