### ISSUE TITLE
Alternator: BatchGetItem should refuse a duplicate key

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10757]
The `BatchWriteItem` documentation explicitly states that it is forbidden for the same item to appear more than once in the same batch.
We knew about this restriction, implemented it and have tests for it.

It turns out that although the `BatchGetItem` documentation does mention that is also has this restriction, in fact it does: Requesting the same item multiple times in the same `BatchGetItem` is not only wasteful, it is outright forbidden by DynamoDB.

Alternator should have the same check.

This is a low-priority issue because not implementing it just means we allow something which isn't allowed in DynamoDB.

**Comment by avikivity** [comment]
Since we don't behave incorrectly on legal requests, not backporting.
