### ISSUE TITLE
Scylla setup failed due to error systemctl is-active systemd-timesyncd

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#10751]
## Installation details

Cluster size: 1 nodes (n1-standard-2)

Scylla Nodes used in this run:
- artifacts-ubuntu1804-jenkins-db-node-d946dd88-0-1 (34.138.95.216 | 10.142.15.205) (shards: -1)

OS / Image: `https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-1804-lts` (gce: us-east1)

Test: `artifacts-ubuntu1804-test`
Test id: `d946dd88-b1f9-4423-9e54-05484ec2a0fb`
Test name: `scylla-master/artifacts/artifacts-ubuntu1804-test`
Test config file(s):

- [ubuntu1804.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/8e98d69f2cdccd20c16a9e1add9c6ce6f9227e52/test-cases/artifacts/ubuntu1804.yaml)

## Issue description

scylla setup failed with next error:
```
2022-06-07 13:38:02.443: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=6197d933-93b3-47f5-8d5e-a1014715ce9a, source=ArtifactsTest.SetUp()
exception=[Node artifacts-ubuntu1804-jenkins-db-node-d946dd88-0-1 [34.138.95.216 | 10.142.15.205] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic ens5 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
Exit code: 1
Stdout:
This is a supported kernel version.
Command 'systemctl  is-active systemd-timesyncd' returned non-zero exit status: 3
----------  stdout  ----------
inactive
------------------------------
----------  stderr  ----------
------------------------------
Debug log created: /var/tmp/scylla_ntp_setup-8784-debug.log
NTP setup failed.
Stderr:
Traceback (most recent call last):
File "/opt/scylladb/scripts/libexec/scylla_ntp_setup", line 56, in <module>
if systemd_unit('systemd-timesyncd').is_active() == 'active':
File "/opt/scylladb/scripts/scylla_util.py", line 398, in is_active
return out('systemctl {} is-active {}'.format(self.ctlparam, self._unit))
File "/opt/scylladb/scripts/scylla_util.py", line 51, in out
res.check_returncode()
File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 460, in check_returncode
raise CalledProcessError(self.returncode, self.args, self.stdout,
subprocess.CalledProcessError: Command 'systemctl  is-active systemd-timesyncd' returned non-zero exit status 3.
```

ntp_log: 
[ntp.log](https://github.com/scylladb/scylla-machine-image/files/8853926/ntp.log)

- Restore Monitor Stack command: `$ hydra investigate show-monitor d946dd88-b1f9-4423-9e54-05484ec2a0fb`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=d946dd88-b1f9-4423-9e54-05484ec2a0fb)
- Show all stored logs command: `$ hydra investigate show-logs d946dd88-b1f9-4423-9e54-05484ec2a0fb`

## Logs:
- **db-cluster-d946dd88.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d946dd88-b1f9-4423-9e54-05484ec2a0fb/20220607_133906/db-cluster-d946dd88.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d946dd88-b1f9-4423-9e54-05484ec2a0fb/20220607_133906/db-cluster-d946dd88.tar.gz)
- **sct-runner-d946dd88.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/d946dd88-b1f9-4423-9e54-05484ec2a0fb/20220607_133906/sct-runner-d946dd88.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/d946dd88-b1f9-4423-9e54-05484ec2a0fb/20220607_133906/sct-runner-d946dd88.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-ubuntu1804-test/543/)

**Comment by syuu1228** [comment]
Duplicated with #10455, the patch is at #10467 but not merged yet

**Comment by slivne** [comment]
closing as#10467 was merged
