### ISSUE TITLE
Alternator: BatchGetItem shouldn't parallelize reads from the same partition

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10753]
Currently, Alternator's implementation of `BatchGetItem` performs all the requested reads in parallel. This can be a problem for different reasons (see #5944), but this issue is about optimizing one specific use case: If the batch contains many requests to different items **in the same partition**, it is inefficient to start all these reads in parallel, considering that a lot of the work (finding the right now, shard, and then partition) is the same for all those reads.

Instead we should merge the different reads that go into the same partition into one read operation with a list of clustering keys in one partition (like a CQL "IN" request).

**Comment by nyh** [comment]
@eliransin @slivne @avikivity I need advice regarding backporting this patch - yes or no.

This is a performance improvement, not a bug fix. It **may** provide a noticeable improvement for a specific work load (Alternator BatchGetItem of many items from the same partition) and may potentially help a specific user's use case - but everything here is qualified by "may". On the other hand it's a pretty intrusive change to BatchGetItem and might have introduced new bugs (obviously I created tests, but it's always possible I missed something).

**Comment by avikivity** [comment]
Best not to backport performance fixes that are not regressions. While some users will appreciate the performance improvement, even a small risk of a bug isn't worth it.

**Comment by avikivity** [comment]
Performance only, not backporting.
