### ISSUE TITLE
Scylla housekeeping script is missing execute bit on OEL81 installs

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla#10752]
## Installation details

Cluster size: 1 nodes (i3.large)

Scylla Nodes used in this run:
- artifacts-oel81-jenkins-db-node-8fe853ce-1 (54.75.115.47 | 10.0.3.183) (shards: -1)

OS / Image: `ami-0e883e67243efea62` (aws: eu-west-1)

Test: `artifacts-oel81-test`
Test id: `8fe853ce-faac-4e23-9ce4-0a7a49751f49`
Test name: `scylla-master/artifacts-offline-install/artifacts-oel81-test`
Test config file(s):

- [oel81.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/5c1a8968e7a2c1bbbca61fa40c6da380a40cd939/test-cases/artifacts/oel81.yaml)

## Issue description

```
2022-06-07 04:19:21.369: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=d8afe90d-1fbf-4c36-a210-06a4fa7bd229, source=ArtifactsTest.SetUp()
exception=[Node artifacts-oel81-jenkins-db-node-8fe853ce-1 [54.75.115.47 | 10.0.3.183] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic ens3 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory /  --no-verify-package '
Exit code: 1
Stdout:
This is a supported kernel version.
[1;31mntp setup is disabled by default, since the installation is offline mode.[0m
Command '/opt/scylladb/scripts/scylla-housekeeping --uuid-file /var/lib/scylla-housekeeping/housekeeping.uuid --repo-files '/etc/yum.repos.d/scylla*.repo' version --version 5.1.dev-0.20220607.605ee74c39b2 --mode i' returned non-zero exit status: 126
----------  stdout  ----------
------------------------------
----------  stderr  ----------
/bin/sh: /opt/scylladb/scripts/scylla-housekeeping: Permission denied
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor 8fe853ce-faac-4e23-9ce4-0a7a49751f49`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=8fe853ce-faac-4e23-9ce4-0a7a49751f49)
- Show all stored logs command: `$ hydra investigate show-logs 8fe853ce-faac-4e23-9ce4-0a7a49751f49`

## Logs:
- **db-cluster-8fe853ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8fe853ce-faac-4e23-9ce4-0a7a49751f49/20220607_042024/db-cluster-8fe853ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8fe853ce-faac-4e23-9ce4-0a7a49751f49/20220607_042024/db-cluster-8fe853ce.tar.gz)
- **sct-runner-8fe853ce.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/8fe853ce-faac-4e23-9ce4-0a7a49751f49/20220607_042024/sct-runner-8fe853ce.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/8fe853ce-faac-4e23-9ce4-0a7a49751f49/20220607_042024/sct-runner-8fe853ce.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-oel81-test/15/)

**Comment by syuu1228** [comment]
But I guess housekeeping does not work correctly on offline-package at all, since it requires yum or apt repository.

**Comment by avikivity** [comment]
Backported to 5.0. @syuu1228 please advise about backport to 4.6.

**Comment by avikivity** [comment]
@syuu1228 ping2

**Comment by avikivity** [comment]
4.6 is EOL, so no need to backport it there any more.
