### ISSUE TITLE
cq-pytest test_secondary_index.py::test_filter_and_limit[False] fails with older Cassandra drivers

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10763]
@gleb-cloudius and @kostja report that `./test.py --mode dev test_secondary_index` consistently fails on **certain installations** with older versions of the Cassandra driver - it fails on `test_secondary_index.py::test_filter_and_limit[False]`, reporting:

```
            # to fetch the 3 results in tiny one-result pages instead of one page.
            s = cql.prepare(f'SELECT pk FROM {table} WHERE x = 1 AND y = 0 LIMIT 3 ALLOW FILTERING')
            s.fetch_size = 1
>           assert sorted(cql.execute(s)) == [(0,), (2,), (4,)]
E           assert [] == [(0,), (2,), (4,)]
E             Right contains 3 more items, first extra item: (0,)
E             Use -v to get the full diff
test/cql-pytest/test_secondary_index.py:399: AssertionError
```

In this test we do filtering (the "False" parameter says without an index) and retrieve the result in one-item pages. Scylla may, and apparently does, in this case return some _empty_ pages, which exposes a known bug in the Cassandra driver which was fixed last year in https://github.com/datastax/python-driver/commit/1d9077d3f4c937929acc14f45c7693e76dde39a9 and reached the Datastax driver version 3.25.1.

We had exactly the same problem in issue #8203, and the test for it - which requires the fix driver - see `test_filtering.py::test_filtering_contiguous_nonmatching_partition_range` - skips the test if the driver is buggy:

```python
    # Verify that the Python driver is recent enough to contain the fix for
    # the driver bug that caused this issue. If it's too old, this test cannot
    # succeed, and we just skip it. Scylla drivers 3.24.5 or newer contain
    # this fix, Datastax drivers 3.25.1 or newer contain it. The fix was
    # introduced in the following commits:
    # https://github.com/scylladb/python-driver/commit/6ed53d9f7004177e18d9f2ea000a7d159ff9278e,
    # https://github.com/datastax/python-driver/commit/1d9077d3f4c937929acc14f45c7693e76dde39a9
    scylla_driver = 'Scylla' in DRIVER_NAME
    driver_version = tuple(int(x) for x in DRIVER_VERSION.split('.'))
    if (scylla_driver and driver_version < (3, 24, 5) or
            not scylla_driver and driver_version <= (3, 25, 0)):
        pytest.skip("Python driver too old to run this test")
```

We should do the same in the test which is failing now.

**Comment by avikivity** [comment]
Test-only, not backporting. Tests should be stable in the frozen toolchain environment.
