### ISSUE TITLE
Nodetool SCRUB failing when running on keyspaces with mv, indexes

### ISSUE THREAD

**Issue by KnifeyMoloko** [scylladb/scylla#10760]
## Installation details

Kernel Version: 5.13.0-1025-aws
Scylla version (or git commit hash): `5.1.dev-20220603.72f629c2b6e8` with build-id `638f7f8a174b83ff26c780b3d7f258217c663339`
Cluster size: 3 nodes (i3.large)

Scylla Nodes used in this run:
- gemini-with-nemesis-3h-normal-maste-oracle-db-node-ad392830-1 (3.237.95.19 | 10.0.1.215) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-ad392830-4 (3.231.215.131 | 10.0.3.123) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-ad392830-3 (3.235.52.95 | 10.0.3.220) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-ad392830-2 (3.237.50.216 | 10.0.1.0) (shards: 2)
- gemini-with-nemesis-3h-normal-maste-db-node-ad392830-1 (44.203.23.172 | 10.0.1.133) (shards: 2)

OS / Image: `ami-0b85f1962845e8501` (aws: us-east-1)

Test: `gemini-3h-with-nemesis-test`
Test id: `ad392830-eb8b-433b-9285-4535b69c1ee0`
Test name: `scylla-master/gemini-/gemini-3h-with-nemesis-test`
Test config file(s):

- [gemini-3h-with-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/a53b3070cef02c729648aad9c88c951e11318523/test-cases/gemini/gemini-3h-with-nemesis.yaml)

## Issue description

**>>>>>>>**
While running `CorruptThenScrub` nemesis we attempt a SCRUB compaction using `nodetool scrub --skip-corrupted ks1` . This triggered the following error:

```
< t:2022-06-05 06:45:18,104 f:remote_base.py  l:520  c:RemoteLibSSH2CmdRunner p:DEBUG > Running command "/usr/bin/nodetool  scrub --skip-corrupted ks1"...
< t:2022-06-05 06:45:18,106 f:file_logger.py  l:101  c:sdcm.sct_events.file_logger p:INFO  > 2022-06-05 06:45:18.104: (NodetoolEvent Severity.NORMAL) period_type=begin event_id=9f44c7c8-db17-4333-ba70-df36125709a1: nodetool_command=scrub node=gemini-with-nemesis-3h-normal-maste-db-node-ad392830-3
< t:2022-06-05 06:45:19,309 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 022-06-05T06:45:19+00:00 gemini-with-nemesis-3h-normal-maste-db-node-ad392830-2   !NOTICE | sudo[9504]: scyllaadm : TTY=unknown ; PWD=/home/scyllaadm ; USER=root ; COMMAND=/usr/bin/coredumpctl --no-pager --no-legend
< t:2022-06-05 06:45:19,309 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-06-05T06:45:19+00:00 gemini-with-nemesis-3h-normal-maste-db-node-ad392830-2     !INFO | sudo[9504]: pam_unix(sudo:session): session opened for user root by (uid=0)
< t:2022-06-05 06:45:19,309 f:db_log_reader.py l:113  c:sdcm.db_log_reader   p:DEBUG > 2022-06-05T06:45:19+00:00 gemini-with-nemesis-3h-normal-maste-db-node-ad392830-2     !INFO | sudo[9504]: pam_unix(sudo:session): session closed for user root
< t:2022-06-05 06:45:19,610 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > error: Scylla API server HTTP GET to URL '/storage_service/keyspace_scrub/ks1' failed: std::invalid_argument (Do not take a snapshot of a materialized view or a secondary index by itself. Run snapshot on the base table instead.)

Traceback (most recent call last):
  File "/home/ubuntu/scylla-cluster-tests/sdcm/cluster.py", line 2644, in run_nodetool
    result = self.remoter.run(cmd, timeout=timeout, ignore_status=ignore_status, verbose=verbose)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 613, in run 
    result = _run()
  File "/home/ubuntu/scylla-cluster-tests/sdcm/utils/decorators.py", line 67, in inner
    return func(*args, **kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in _run
    return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
    result = connection.run(**command_kwargs)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 620, in run 
    return self._complete_run(channel, exception, timeout_reached, timeout, result, warn, stdout, stderr)
  File "/home/ubuntu/scylla-cluster-tests/sdcm/remote/libssh2_client/__init__.py", line 654, in _complete_run
    raise UnexpectedExit(result)
sdcm.remote.libssh2_client.exceptions.UnexpectedExit: Encountered a bad command exit code!

Command: '/usr/bin/nodetool  scrub --skip-corrupted ks1'

Exit code: 2

Stdout:



Stderr:

    at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
    at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
    at java.security.AccessController.doPrivileged(Native Method)
    at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
2022-06-05 06:45:42.631: (DisruptionEvent Severity.ERROR) period_type=end event_id=7f3e4f6e-281f-488b-ac34-eea1b92c197e duration=26s: nemesis_name=CorruptThenScrub target_node=Node gemini-with-nemesis-3h-normal-maste-db-node-ad392830-3 [3.235.52.95 | 10.0.3.220] (seed: False) errors=Encountered a bad command exit code!

Command: '/usr/bin/nodetool  scrub --skip-corrupted ks1'

Exit code: 2

Stdout:

```

Keyspace `ks1` does indeed include indexes and materialized views. Should we not use SCRUB on such keyspaces?

**<<<<<<<**

- Restore Monitor Stack command: `$ hydra investigate show-monitor ad392830-eb8b-433b-9285-4535b69c1ee0`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=ad392830-eb8b-433b-9285-4535b69c1ee0)
- Show all stored logs command: `$ hydra investigate show-logs ad392830-eb8b-433b-9285-4535b69c1ee0`

## Logs:
- **db-cluster-ad392830.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad392830-eb8b-433b-9285-4535b69c1ee0/20220605_072710/db-cluster-ad392830.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad392830-eb8b-433b-9285-4535b69c1ee0/20220605_072710/db-cluster-ad392830.tar.gz)
- **monitor-set-ad392830.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad392830-eb8b-433b-9285-4535b69c1ee0/20220605_072710/monitor-set-ad392830.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad392830-eb8b-433b-9285-4535b69c1ee0/20220605_072710/monitor-set-ad392830.tar.gz)
- **loader-set-ad392830.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad392830-eb8b-433b-9285-4535b69c1ee0/20220605_072710/loader-set-ad392830.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad392830-eb8b-433b-9285-4535b69c1ee0/20220605_072710/loader-set-ad392830.tar.gz)
- **sct-runner-ad392830.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad392830-eb8b-433b-9285-4535b69c1ee0/20220605_072710/sct-runner-ad392830.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad392830-eb8b-433b-9285-4535b69c1ee0/20220605_072710/sct-runner-ad392830.tar.gz)
- **parallel-timelines-report-ad392830.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/ad392830-eb8b-433b-9285-4535b69c1ee0/20220605_072710/parallel-timelines-report-ad392830.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/ad392830-eb8b-433b-9285-4535b69c1ee0/20220605_072710/parallel-timelines-report-ad392830.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/gemini-/job/gemini-3h-with-nemesis-test/321/)

**Comment by bhalevy** [comment]
@cmm please look into this.

The error seems to come from auto-snapshot before scrub:

> < t:2022-06-05 06:45:19,610 f:base.py         l:228  c:RemoteLibSSH2CmdRunner p:DEBUG > error: Scylla API server HTTP GET to URL '/storage_service/keyspace_scrub/ks1' failed: std::invalid_argument (Do not take a snapshot of a materialized view or a secondary index by itself. Run snapshot on the base table instead.)

We do want to fail it if the snapshot is requested by the user using the api layer (modulo a "force" option we can add). But in any case, let's allow it if the snapshot is generated internally, as in this case.

/cc @denesb

**Comment by bhalevy** [comment]
Adding `Backport candidate` label.

@cmm, not that aab4cd8 used `Closes` rather `Fixes` to reference this issue, so it was closed without adding the above label (as it's not considered fixed).  Please use Fixes next time, and reserves Closes to auto-closing PRs.

**Comment by avikivity** [comment]
Backported to 5.0. 5.1 has it already. 4.6 left broken, it required adjustment and the bug is not sufficiently important to bother.
