### ISSUE TITLE
AMI sanity: scylla-io-setup failing

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#1077]
Running the AMI tests, I've noticed that they can't get past the scylla-io-setup stage. The relevant journalctl logs show:

    Mar 21 20:38:04 ip-172-30-0-108 scylla_io_setup[2017]: Dload  Upload   Total   Spent    Left  Speed
    Mar 21 20:38:04 ip-172-30-0-108 scylla_io_setup[2017]: [155B blob data]
    Mar 21 20:38:04 ip-172-30-0-108 scylla_io_setup[2017]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    Mar 21 20:38:04 ip-172-30-0-108 scylla_io_setup[2017]: Dload  Upload   Total   Spent    Left  Speed
    Mar 21 20:38:04 ip-172-30-0-108 scylla_io_setup[2017]: [155B blob data]
    Mar 21 20:38:04 ip-172-30-0-108 scylla_io_setup[2017]: % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
    Mar 21 20:38:04 ip-172-30-0-108 scylla_io_setup[2017]: Dload  Upload   Total   Spent    Left  Speed
    Mar 21 20:38:04 ip-172-30-0-108 scylla_io_setup[2017]: [155B blob data]
    Mar 21 20:38:04 ip-172-30-0-108 scylla_io_setup[2017]: /usr/lib/scylla/scylla_io_setup: line 37: [: too many arguments
    Mar 21 20:38:04 ip-172-30-0-108 scylla_io_setup[2017]: /usr/lib/scylla/scylla_io_setup: line 45: 128/--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=1
    Mar 21 20:38:04 ip-172-30-0-108 systemd[1]: scylla-io-setup.service: main process exited, code=exited, status=1/FAILURE
    Mar 21 20:38:04 ip-172-30-0-108 systemd[1]: Failed to start Scylla IO Setup.
    -- Subject: Unit scylla-io-setup.service has failed
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit scylla-io-setup.service has failed.
    -- 
    -- The result is failed.
    Mar 21 20:38:04 ip-172-30-0-108 systemd[1]: Dependency failed for Scylla Server.
    -- Subject: Unit scylla-server.service has failed
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit scylla-server.service has failed.
    -- 
    -- The result is dependency.
    Mar 21 20:38:04 ip-172-30-0-108 systemd[1]: Dependency failed for Scylla JMX.
    -- Subject: Unit scylla-jmx.service has failed
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit scylla-jmx.service has failed.

**Comment by lmr** [comment]
AMI ID: ami-e3787a89

**Comment by lmr** [comment]
I've looked at the script and apart from the fact it's probing number of shards and things like that, I couldn' t figure out where is the actual failure so far.

**Comment by slivne** [comment]
which head ?

**Comment by slivne** [comment]
what instance type mayge its 1060

you need to have --smp & --cpuset in SCYLLA_ARGS

benoit sent patches to fix this on the list

**Comment by lmr** [comment]
m3.medium, which was the default the AMI job was using

**Comment by lmr** [comment]
I'm re-trying with c3.xlarge

**Comment by slivne** [comment]
you need at least 8 cpus to have this working so it must be atleast
c3.2xlarge (yet there there is another issue on the list ...)

try c3.4xlarge or c3.8x

**Comment by slivne** [comment]
sorry my mistake the issue of c3.2x is #996 and it shoudl be fixed you can
try that as well

**Comment by lmr** [comment]
c3.2xlarge is working so far, c-s is running

**Comment by lmr** [comment]
OK, the c3.2xlarge size did work. I've edited the jenkins job to use only this size for now.

Down the road we'll have to revisit this to actually get all desired sizes working.
