### ISSUE TITLE
CQL: extend support for STRING_LITERAL to support 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1078]
We currently do not support in Cql.g

```
// FIXME:
#if 0
      /* pg-style string literal */
      (
        '\$' '\$'
        ( /* collect all input until '$$' is reached again */
          {  (input.size() - input.index() > 1)
               && !"$$".equals(input.substring(input.index(), input.index() + 1)) }?
             => c=. { txt.appendCodePoint(c); }
        )*
        '\$' '\$'
      )
      |
#endif
```

add support for it.

**Comment by penberg** [comment]
@slivne Btw, this is a CQL (the language) 3.3.0 feature that appeared in Cassandra 2.2.

**Comment by duarten** [comment]
scylla: https://groups.google.com/d/msg/scylladb-dev/6NczQR_Lh40/soqdMqhHEAAJ
scylla-tools-java: https://groups.google.com/d/msg/scylladb-dev/6NczQR_Lh40/KxhEPKtHEAAJ

**Comment by duarten** [comment]
@avikivity Did you see https://groups.google.com/d/msg/scylladb-dev/6NczQR_Lh40/KxhEPKtHEAAJ? Gmail/google groups lumped the patches together in the same thread.

**Comment by avikivity** [comment]
@duarten v3 was applied, anything else?

**Comment by duarten** [comment]
@avikivity The patch for scylla-tools-java.

**Comment by avikivity** [comment]
Saw it and forgot.  Thanks for the reminder.
