### ISSUE TITLE
Jenkins: cql-pytest failures are reported inconveniently

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10785]
When a cql-pytest fails in Jenkins, here is what the test failure looks like today:

https://jenkins.scylladb.com/job/releng/job/Scylla-CI/778/testReport/junit/(root)/non-boost%20tests/test_allow_filtering_release_2019/

> Test pytest --dc_rf=1 --host=127.142.99.1 -o junit_family=xunit2 --junit-xml=/jenkins/workspace/releng/Scylla-CI/scylla/testlog/release/xml/test_allow_filtering.2019.xunit.xml test/cql-pytest/test_allow_filtering.py failed, check the log at /jenkins/workspace/releng/Scylla-CI/scylla/testlog/release/test_allow_filtering.2019.log

That's the whole report. This really frustrates me. Finding this file test_allow_filtering.2019.log takes a lot of effort and many of clicks (and it's not even the right path, the "release" directory was renamed "x86_64_release"). After all the effort, you find this file: https://jenkins.scylladb.com/job/releng/job/Scylla-CI/778/artifact/testlog/x86_64_release/test_allow_filtering.2019.log - this is its full content:

```
=== TEST.PY STARTING TEST #2019 ===
export UBSAN_OPTIONS='halt_on_error=1:abort_on_error=1:suppressions=/jenkins/workspace/releng/Scylla-CI/scylla/ubsan-suppressions.supp'
export ASAN_OPTIONS='disable_coredump=0:abort_on_error=1:detect_stack_use_after_return=1'
pytest --dc_rf=1 --host=127.142.99.1 -o junit_family=xunit2 --junit-xml=/jenkins/workspace/releng/Scylla-CI/scylla/testlog/release/xml/test_allow_filtering.2019.xunit.xml test/cql-pytest/test_allow_filtering.py
=== TEST.PY TEST OUTPUT ===
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --dc_rf=1
  inifile: /jenkins/workspace/releng/Scylla-CI/scylla/test/cql-pytest/pytest.ini
  rootdir: /jenkins/workspace/releng/Scylla-CI/scylla/test/cql-pytest

=== TEST.PY SUMMARY START ===
Test exited with code 4

=== TEST.PY SUMMARY END ===
```

So much clearer, so much more useful! (in the above-linked CI run, 66 tests got broken by a test.py change that led it to send this non-existent "--dc_rf" flag.)
And this is **exactly** what we had in the past, before it was changed, intentionally :-(

@kostja I know you did this deliberately, but I urge you to rethink. I think you made a mistake, and made something which used to take one second (follow a link in the Jenkins UI) into a frustrating chore.

I'm opening this issue because I think it's important that we give this specific request serious thought - and not just dismiss it during a review that involved 10 other threads.

**Comment by kostja** [comment]
On the same token: gleb asked to add -s to pytests, so that debug prints work in it.

**Comment by kostja** [comment]
On the same token: gleb asked to include pytest output to xml output.

**Comment by nyh** [comment]
> So you want me to copy the log of the test into hte output as well?

Yes, sorry, I think I understand what happened now, and you're right that it's not exactly the same as usual failures - in this case, it's not that pytest generated a lot of interesting failure output - it simply didn't work. So maybe the title of my issue isn't fair because this isn't really the most typical cql-pytest failure. I'll think how to change it.

In any case my main point is that any time you can think of a file that contains useful messages for debugging failures - instead of giving the (inaccurate) path of that file and tell the user to go click 10 times to find it - it will be better to include the content of the file. Unless this file is shared by a gazillion tests and then it would be a waste to insert a gazillion copies of it into many result files.

> I can do it. You asked me to include server log and I added. Generally, there are 3 logs you should be looking at when there is a test failure: harness, pytest, and server. I could of course assemble them all in one place - xml output.

Right. I think this would be most convenient especially if you already know how to cut the "relevant" pieces of the server log so in case of multiple failures we won't have many copies of the same huge server log, but rather different pieces in different xml outputs.

**Comment by kostja** [comment]
Maybe then I can remove printing the log to console output? It really clutters it into a mess when startup fails.

**Comment by nyh** [comment]
@kostja  if Scylla boot fails, and we need to debug it, ins't the only useful data we have to debug it is the startup log?
I think you can remove the log from the console output if you are sure that you put it - or at least the important parts from it - in a specific failure log. If you don't do that in every case, then having it somewhere is still important.

**Comment by avikivity** [comment]
Not a bug, not backporting.

**Comment by avikivity** [comment]
Removing backport candidate label again, @benipeled
