### ISSUE TITLE
DTETS  test_paged_count_with_limit (paging_additional_test.TestAggregatePaging) failing in debug

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1079]
```
======================================================================
ERROR: test_paged_count_with_limit (paging_additional_test.TestAggregatePaging)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/paging_additional_test.py", line 40, in test_paged_count_with_limit
    pf = PageFetcher(future).request_all()
  File "/home/shlomi/urchin-dtest/paging_test.py", line 59, in __init__
    self.wait(seconds=30)
  File "/home/shlomi/urchin-dtest/paging_test.py", line 124, in wait
    (self.requested_pages, self.retrieved_pages, self.retrieved_empty_pages))
RuntimeError: Requested pages were not delivered before timeout.Requested: 1; retrieved: 0; empty retreived: 0
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/shlomi/.dtest/dtest-uCV6fG
--------------------- >> end captured logging << ---------------------

```

from @elcallio that did an initial anbalysis of this

To recapitulate:
The dtest creates X thousand rows of data, then reads it using 10,20,50,100 etc page sizes.
However, for some reason, the paged query generated (query_pagers.cc), with modified ranges and
limit, still returns ~all rows (or at least ~2000) _per iteration_. The resulting amount of processing is
why we time out.
From what I could tell, we seem to fail the tests in storage_proxy::reconcile. For some reason it believes
the query result is incomplete, and does additional re-queries.
I think Pawel was the last to modify the logic here, though I am not sure the problem does not show
earlier.

**Comment by pdziepak** [comment]
@elcallio I am not sure why you have come to a conclusion that storage_proxy::reconcile is the culprit. The test times out when executing a query with page size 10 and limit 1000 (at least on my machine). I've added additional logging to the storage proxy and the output doesn't suggest any problems there.
```diff
diff --git a/service/storage_proxy.cc b/service/storage_proxy.cc
index 8d05c0c..b6a2112 100644
--- a/service/storage_proxy.cc
+++ b/service/storage_proxy.cc
@@ -1891,11 +1891,18 @@ class abstract_read_executor : public enable_shared_from_this<abstract_read_exec
             try {
                 f.get();
                 auto rr_opt = data_resolver->resolve(_schema, *cmd, original_row_limit()); // reconciliation happens here
-
+                if (!rr_opt) {
+                    logger.warn("NOT ENOUGH INFORMATION");
+                } else if (!(data_resolver->max_live_count() < cmd->row_limit || rr_opt->row_count() >= original_row_limit())) {
+                    logger.warn("NEED MORE ROWS {} {} {} {}", data_resolver->max_live_count(), cmd->row_limit, rr_opt->row_count(), original_row_limit());
+                } else {
+                    logger.warn("OK {} {} {} {}", data_resolver->max_live_count(), cmd->row_limit, rr_opt->row_count(), original_row_limit());
+                }
                 // We generate a retry if at least one node reply with count live columns but after merge we have less
                 // than the total number of column we are interested in (which may be < count on a retry).
                 // So in particular, if no host returned count live columns, we know it's not a short read.
                 if (rr_opt && (data_resolver->max_live_count() < cmd->row_limit || rr_opt->row_count() >= original_row_limit())) {
+                    logger.warn("RETURNED {} ROWS\n", rr_opt->row_count());
                     auto result = ::make_foreign(::make_lw_shared(to_data_query_result(std::move(*rr_opt), _schema, _cmd->slice)));
                     // wait for write to complete before returning result to prevent multiple concurrent read requests to
                     // trigger repair multiple times and to prevent quorum read to return an old value, even after a quorum
```
output (it looks similar on all nodes):
```
...
WARN  2016-03-22 13:24:56,961 [shard 0] storage_proxy - OK 10 10 10 10
WARN  2016-03-22 13:24:56,961 [shard 0] storage_proxy - RETURNED 10 ROWS

WARN  2016-03-22 13:24:56,963 [shard 0] storage_proxy - OK 2 10 2 10
WARN  2016-03-22 13:24:56,963 [shard 0] storage_proxy - RETURNED 2 ROWS

WARN  2016-03-22 13:24:56,966 [shard 0] storage_proxy - OK 8 10 8 10
WARN  2016-03-22 13:24:56,966 [shard 0] storage_proxy - RETURNED 8 ROWS

WARN  2016-03-22 13:24:56,970 [shard 0] storage_proxy - OK 10 10 10 10
WARN  2016-03-22 13:24:56,970 [shard 0] storage_proxy - RETURNED 10 ROWS
```
So, the paging codes asks for min(limit, page size) rows and that's what storage proxy returns without any retries or limit increases.

Sadly, this doesn't bring us closer to discovering the reason for these time outs, but storage proxy looks innocent (besides, I still get time outs with 77dbe3c12fccf5f7f58b46b31794d94e073be3c9 reverted).

**Comment by elcallio** [comment]
Yes, I also got the same basic result without 77dbe3c, which is why I said that I don't think it is your change per sé that is guilty. 
But when I added similar printouts, I got the !rr_opt result, which in turn lead to repeated reconciles. So it is weird that you get a different result now.

**Comment by pdziepak** [comment]
That !rr_opt is strange, I am not able to reproduce it. Did you get it in that dtest or in some other test case?

As for the time outs, both storage proxy and paging code seems to be working correctly and the only issue is that since the query in that test uses an aggregate function the client doesn't get any reply until the CQL code on coordinator receives all data (even though paging is used internally to get that data from the replicas). Combine that with debug builds being very slow and time outs don't seem so surprising any more.

**Comment by slivne** [comment]
we split the case up so that we will run a few cases on debug and all the cases on release

cloudius-systems/urch-dtest@57576665be2ca74cb40d4e6a6659cc5e437e1a7d
