### ISSUE TITLE
memtable test failed_flush_prevents_writes: Assertion `eventually_true([&t]() { return t.active_memtable().empty(); })' failed

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10793]
This is frequently seen in CI, e.g. https://jenkins.scylladb.com/job/releng/job/Scylla-CI/804/artifact/testlog/x86_64_debug/memtable_test.3.log
```
INFO  2022-06-13 22:04:38,293 [shard 0] schema_tables - Schema version changed to 78b5a366-d726-3212-a352-3dfdc091b7fa
ERROR 2022-06-13 22:04:38,413 [shard 0] database - Flush failed due to low memory. Retrying again in 100ms
memtable_test: test/boost/memtable_test.cc:933: auto failed_flush_prevents_writes::run_test_case()::(anonymous class)::operator()(cql_test_env &) const: Assertion `eventually_true([&t]() { return t.active_memtable().empty(); })' failed.
Aborting on shard 0.
Backtrace:
  0x112868d0
  0x17ca56cd
  0x17ca52cc
  0x17b06ab4
  0x17b3260e
  0x17c138fc
  0x17c13b4d
  0x17c1397a
  0x7f033739ba1f
  /lib64/libc.so.6+0x3d2a1
  /lib64/libc.so.6+0x268a3
  /lib64/libc.so.6+0x26788
  /lib64/libc.so.6+0x35a15
  0x1136b53a
  0x1136aa10
  0x1136a9bc
  0x1136a87c
  0x167a0566
  0x164fe2cb
  0x164fe288
  0x164fe268
  0x164fe248
  0x164fe21c
  0x164fe1a0
  0x164fe07e
  0x164fdf42
  0x11583faf
  0x17fa0229
```

As discussed in https://github.com/scylladb/scylla/pull/10691, the condition the test checks is wrong since it examines the active memtable after the error injection is disabled rather than the flushed one that is no longer active.

This will be fixed by #10691 but I'm opening this issue so others can find it.

**Comment by nyh** [comment]
@bhalevy please comment here about whether the fix in #10691 (which appears to include 50 patches!) will require backporting, or it fixes a recent regression and won't need backporting.

**Comment by bhalevy** [comment]
The particular fix to this issue is in https://github.com/scylladb/scylla/pull/10691/commits/c954629cf1133d7d8b4573d40414b2899665d32c

The test was introduced in f6d9d6175fad11bc1dbf0aa06e587953c0ba8dad and is present in branch-5.0.
We also need to backport 0e78ad50ea52f3aecb6380527da4152eeab0881e to branch-5.0. I don't know if it is associated with an GH issue or not. (@mikolajsieluzycki / @tgrabiec do you know?)

**Comment by tgrabiec** [comment]
On Tue, Jun 14, 2022 at 1:09 PM Benny Halevy ***@***.***>
wrote:

> The particular fix to this issue is in c954629
> <https://github.com/scylladb/scylla/commit/c954629cf1133d7d8b4573d40414b2899665d32c>
>
> The test was introduced in f6d9d61
> <https://github.com/scylladb/scylla/commit/f6d9d6175fad11bc1dbf0aa06e587953c0ba8dad>
> and is present in branch-5.0.
> We also need to backport 0e78ad5
> <https://github.com/scylladb/scylla/commit/0e78ad50ea52f3aecb6380527da4152eeab0881e>
> to branch-5.0. I don't know if it is associated with an GH issue or not. (
> @mikolajsieluzycki <https://github.com/mikolajsieluzycki> / @tgrabiec
> <https://github.com/tgrabiec> do you know?)
>

Not that I know of.

**Comment by mikolajsieluzycki** [comment]
Same

**Comment by avikivity** [comment]
Test only, not backporting.
