### ISSUE TITLE
Dynamic collectd rate

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1080]
Usually, send metrics every 10 seconds to reduce load and cpu consumption.

When scyllatop is active, increase rate to 3 seconds, drop it when scyllatop exits.

**Comment by tzach** [comment]
@avikivity @amnonh is this relevant with Scylla native prometheus API?

**Comment by avikivity** [comment]
It's relevant, but if #1541 is implemented, this is no longer needed.

**Comment by avikivity** [comment]
Obsoleted by #1541.
