### ISSUE TITLE
scylla_setup fails with "TypeError: out() got an unexpected keyword argument 'user'"

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#10804]
## Installation details
Cluster size: 1 nodes (n1-standard-2)

Scylla Nodes used in this run:
- artifacts-ubuntu2004-jenkins-db-node-cb8c797b-0-1 (35.231.159.22 | 10.142.0.3) (shards: -1)

OS / Image: `https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts` (gce: us-east1)

Test: `artifacts-ubuntu2004-test`
Test id: `cb8c797b-273d-411e-9150-295b0e7c445c`
Test name: `scylla-master/artifacts-offline-install/artifacts-ubuntu2004-test`
Test config file(s):

- [ubuntu2004.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/71b60cc7e96dac76147d255d81ceaf64cca87cb9/test-cases/artifacts/ubuntu2004.yaml)

## Issue description

scylla_setup fails when calling housekeeping
```
File "/opt/scylladb/scripts/libexec/scylla_setup", line 377, in <module>
new_version=out('{}/scylla-housekeeping --uuid-file /var/lib/scylla-housekeeping/housekeeping.uuid --repo-files \'/etc/apt/sources.list.d/scylla*.list\' version --version {} --mode i'.format(scriptsdir(), cur_version), user='scylla', group='scylla', timeout=HOUSEKEEPING_TIMEOUT)
TypeError: out() got an unexpected keyword argument 'user'
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor cb8c797b-273d-411e-9150-295b0e7c445c`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=cb8c797b-273d-411e-9150-295b0e7c445c)
- Show all stored logs command: `$ hydra investigate show-logs cb8c797b-273d-411e-9150-295b0e7c445c`

## Logs:
- **db-cluster-cb8c797b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cb8c797b-273d-411e-9150-295b0e7c445c/20220615_042041/db-cluster-cb8c797b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cb8c797b-273d-411e-9150-295b0e7c445c/20220615_042041/db-cluster-cb8c797b.tar.gz)
- **sct-runner-cb8c797b.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/cb8c797b-273d-411e-9150-295b0e7c445c/20220615_042041/sct-runner-cb8c797b.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/cb8c797b-273d-411e-9150-295b0e7c445c/20220615_042041/sct-runner-cb8c797b.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-ubuntu2004-test/420/)

**Comment by fruch** [comment]
@syuu1228 
seems like in https://github.com/scylladb/scylla/pull/10467, the user/pass arguments were removed, while still being in use.

**Comment by slivne** [comment]
@fruch did you send a fix - if so please hack @syuu1228 review them

**Comment by fruch** [comment]
> @fruch did you send a fix - if so please hack @syuu1228 review them

@syuu1228, it's #10818

@avikivity already merged it to next

**Comment by fruch** [comment]
also I'm working on adding unit tests to cover those scripts in #10809.

**Comment by avikivity** [comment]
I'm guessing this was a transient bug that never appeared on a release branch. Not backporting.
