### ISSUE TITLE
failed_flush_prevents_writes test may fail due to background merging

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10801]
This was previously fixed by 0e78ad50ea52f3aecb6380527da4152eeab0881e
that got reverted as part of 5129280f45358962f61a411bd1cf2e73d5c542fe.

I'm opening this issue for resubmitting the patch and for backporting purposes
as the above fix is required in addition to 5bd2e0ccce128d726c4737a996d793666c54f6d1
to make the test pass reliably.

See https://github.com/scylladb/scylla/issues/10793

/Cc @tgrabiec @mikolajsieluzycki

**Comment by bhalevy** [comment]
Introduced by f6d9d6175fa
Requires backport to 5.0

**Comment by avikivity** [comment]
Backported to 5.0.

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
