### ISSUE TITLE
Test returned error during rolling upgrade from 2021.1 to 2022.1

### ISSUE THREAD

**Issue by k0machi** [scylladb/scylla#10825]
## Installation details

Kernel Version: 3.10.0-1160.62.1.el7.x86_64
Scylla version (or git commit hash): `2021.1.11-20220516.8e6c9917c` with build-id `3a8b554df0eaa5f122e8ea7e17d81804efd85b4e`
Cluster size: 4 nodes (n1-highmem-8)

Scylla Nodes used in this run:
- rolling-upgrade--centos-db-node-7dcece35-0-4 (34.139.158.9 | 10.142.0.49) (shards: 8)
- rolling-upgrade--centos-db-node-7dcece35-0-3 (34.74.254.106 | 10.142.0.46) (shards: 8)
- rolling-upgrade--centos-db-node-7dcece35-0-2 (34.74.118.10 | 10.142.0.44) (shards: 8)
- rolling-upgrade--centos-db-node-7dcece35-0-1 (34.138.95.216 | 10.142.0.43) (shards: 8)

OS / Image: `https://www.googleapis.com/compute/v1/projects/centos-cloud/global/images/family/centos-7` (gce: us-east1)

Test: `rolling-upgrade-centos7-ldap-authorization-test`
Test id: `7dcece35-1b14-4a6d-9234-5e459d0c7648`
Test name: `enterprise-2022.1/rolling-upgrade/rolling-upgrade-centos7-ldap-authorization-test`
Test config file(s):

- [rolling-upgrade.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/53b43cd9ccbb77f4d152bf46102abf603d9ca62a/test-cases/upgrades/rolling-upgrade.yaml)

## Issue description

```log
2022-06-09 04:01:21.632: (TestFrameworkEvent Severity.ERROR) period_type=one-time event_id=380fb525-4ead-4387-bf83-146b0c49b198, source=UpgradeTest.test_rolling_upgrade (upgrade_test.UpgradeTest)() message=Traceback (most recent call last):
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 629, in test_rolling_upgrade
self.fill_and_verify_db_data('after rollback the second node')
File "/home/ubuntu/scylla-cluster-tests/upgrade_test.py", line 464, in fill_and_verify_db_data
self.verify_db_data()
File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3362, in verify_db_data
self.run_db_queries(session, session.default_fetch_size)
File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3296, in run_db_queries
self._run_db_queries(item, session)
File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3256, in _run_db_queries
raise ex
File "/home/ubuntu/scylla-cluster-tests/sdcm/fill_db_data.py", line 3253, in _run_db_queries
self.assertEqual([list(row) for row in res], item['results'][i])
AssertionError: Lists differ: [[0, 1, 42, 1]] != [[0, None, 42, None]]
First differing element 0:
[0, 1, 42, 1]
[0, None, 42, None]
- [[0, 1, 42, 1]]
+ [[0, None, 42, None]]
```

This happens when testing mixed cluster mode - node 2 is rolled back, after both node 1 and 2 are upgraded to 2022.1.

- Restore Monitor Stack command: `$ hydra investigate show-monitor 7dcece35-1b14-4a6d-9234-5e459d0c7648`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=7dcece35-1b14-4a6d-9234-5e459d0c7648)
- Show all stored logs command: `$ hydra investigate show-logs 7dcece35-1b14-4a6d-9234-5e459d0c7648`

## Logs:
- **db-cluster-7dcece35.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7dcece35-1b14-4a6d-9234-5e459d0c7648/20220609_041040/db-cluster-7dcece35.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7dcece35-1b14-4a6d-9234-5e459d0c7648/20220609_041040/db-cluster-7dcece35.tar.gz)
- **monitor-set-7dcece35.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7dcece35-1b14-4a6d-9234-5e459d0c7648/20220609_041040/monitor-set-7dcece35.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7dcece35-1b14-4a6d-9234-5e459d0c7648/20220609_041040/monitor-set-7dcece35.tar.gz)
- **loader-set-7dcece35.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7dcece35-1b14-4a6d-9234-5e459d0c7648/20220609_041040/loader-set-7dcece35.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7dcece35-1b14-4a6d-9234-5e459d0c7648/20220609_041040/loader-set-7dcece35.tar.gz)
- **sct-runner-7dcece35.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/7dcece35-1b14-4a6d-9234-5e459d0c7648/20220609_041040/sct-runner-7dcece35.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/7dcece35-1b14-4a6d-9234-5e459d0c7648/20220609_041040/sct-runner-7dcece35.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/enterprise-2022.1/job/rolling-upgrade/job/rolling-upgrade-centos7-ldap-authorization-test/2/)

**Comment by bhalevy** [comment]
Cc @eliransin

**Comment by slivne** [comment]
A known issue - its a duplicate @fgelcer - please reference

**Comment by fgelcer** [comment]
dup of https://github.com/scylladb/scylla-enterprise/issues/2278
issue was moved to https://github.com/scylladb/scylla-cluster-tests/issues/4866
