### ISSUE TITLE
Alternative to nodetool refresh

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1084]
nodetool refresh is dangerous, since the user may overwrite an existing sstable, or Scylla may attempt to overwrite a user sstable (it won't, because `O_EXCL`), or something.

We can have an `ingest` subdirectory and have refresh look at that.

In fact we can just extend refresh to look at `ingest` in addition to the regular directory; and just recommend that users use `ingest` exclusively.  Scylla will then allocate a generation for the new sstables, and move+rename them into place without conflict.

**Comment by tzach** [comment]
:+1:
Copy new files to the active sstable dir is just dangerous

**Comment by slivne** [comment]
duplicate of #487
