### ISSUE TITLE
Materialized views with filters on regular columns do not work when static base columns are present

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#10851]
The exact source of this problem is still unbeknownst to me, but the following reproducer triggers a storage proxy error:

```cql
DROP KEYSPACE test;
CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}; use test;
CREATE TABLE t(
    p int,
    c int,
    v int,
    s int static,
    primary key (p,c)
);
CREATE MATERIALIZED VIEW mv AS
    SELECT p,c,v FROM t
    WHERE p IS NOT NULL AND c IS NOT NULL AND v = 44
    PRIMARY KEY (p,c,v);
INSERT INTO t(p,c,v) VALUES (42,43,44);
```

Error:
```
WriteFailure: Error from server: code=1500 [Replica(s) failed to execute write] message="Operation failed for test.t - received 0 responses and 1 failures from 1 CL=ONE." info={'consistency': 'ONE', 'required_responses': 1, 'received_responses': 0, 'failures': 1}
```

Log entry from the node:
```
ERROR 2022-06-22 09:03:31,271 [shard 1] storage_proxy - exception during mutation write to 127.0.0.1: std::out_of_range (deserialization buffer underflow)
```

The key parts of this reproducer seem to be that:
* there exists a static column in the base table
* there's a filter on a base regular column in the materialized view: `v = 44`

**Comment by psarna** [comment]
I also confirm that on Scylla 4.6.3 docker image, instead of a write failure we experience a node crash with segmentation fault.

**Comment by psarna** [comment]
Interesting. I built 4.6.3, and I see in the frame that the immediate cause of a segfault is that a null pointer is passed to is_satisfied_by.... 
```gdb
#3  0x0000000001d4ed88 in cql3::expr::is_satisfied_by (restr=..., partition_key=std::vector of length 1, capacity 1 = {...}, clustering_key=std::vector of length 1, capacity 1 = {...}, 
    static_row=..., row=0x0, row@entry=0x7fffdb031950, selection=..., options=...) at cql3/expr/expression.cc:665
```

What's even more interesting is that this parameter is passed by taking an address of a variable, which is a reference, so it must have gotten optimized out to a nullptr somehow:
```cpp
    bool check_if_matches(const clustering_key& key, const query::result_row_view& static_row, const query::result_row_view& row) const {
        std::vector<bytes> ck = key.explode();
        return boost::algorithm::all_of(
            _view.select_statement().get_restrictions()->get_non_pk_restriction() | boost::adaptors::map_values,
            [&] (auto&& r) {
                return cql3::expr::is_satisfied_by(
                        r->expression, _pk, ck, static_row, &row, *_selection, cql3::query_options({ })); // <---- &row here is the parameter that shows as nullptr in gdb
            }
        );
    }```

**Comment by psarna** [comment]
Static row is also botched:
```gdb
(gdb) p static_row
$3 = (const query::result_row_view &) <error reading variable: Cannot access memory at address 0x1>
```

**Comment by psarna** [comment]
I see in the code that in order to get rid of an old is_satisfied_by abstraction (https://github.com/scylladb/scylla/commit/d6b0a8338a07b3d439a7b27334dc71f4ac4fad62), this code path was rewritten with a trick, which creates a "data_query_result_builder" from given mutation, and uses it to check if restrictions match. But, this query result builder visitor also has mechanisms for accepting static rows, which we ignore here, because views do not currently care about static rows at all (interestingly, looks related to https://github.com/scylladb/scylla/issues/2963, which we also happened to considering lately, although 100% independently). So perhaps when coding this visitor I broke an undocumented assumption, that a static row **must** be consumed if there exists a static column in the schema? I'll try to verify by adding a mock empty "static row" and seeing what happens.

**Comment by psarna** [comment]
I can confirm that the following diff fixes or hides the issue:
```diff
diff --git a/db/view/view.cc b/db/view/view.cc
index d62316e9a..776ae06e0 100644
--- a/db/view/view.cc
+++ b/db/view/view.cc
@@ -431,6 +431,10 @@ bool matches_view_filter(const schema& base, const view_info& view, const partit
     data_query_result_builder builder(base, slice);
     builder.consume_new_partition(dht::decorate_key(base, key));
     builder.consume(clustering_row(base, update), row_tombstone{}, update.is_live(base, tombstone{}, now));
+    if (base.static_columns_count() > 0) {
+        vlogger.warn("Consuming a dummy static row");
+        builder.consume(static_row{}, tombstone{}, true);
+    }
     builder.consume_end_of_partition();
     auto result = builder.consume_end_of_stream();
     view_filter_checking_visitor visitor(base, view);
```
now to figure out why.

**Comment by nyh** [comment]
Here's a cql-pytest reproducer based on your exact example:
```python
def test_mv_filter_10851(cql, test_keyspace):
    schema = 'p int, c int, v int, s int static, primary key (p, c)'
    with new_test_table(cql, test_keyspace, schema) as table:
        with new_materialized_view(cql, table, select='p, c, v', pk='p, c, v', where='p is not null and c is not null and v = 44') as mv:
            cql.execute(f"INSERT INTO {table} (p,c,v) VALUES (42,43,44)")
```

As you saw, the INSERT operation fails, with:
> Operation failed for cql_test_1655893300743.cql_test_1655893300752 - received 0 responses and 1 failures from 1 CL=LOCAL_QUORUM.

and the cause of this failure is written in the log:
> ERROR 2022-06-22 13:21:40,765 [shard 0] storage_proxy - exception during mutation write to 127.6.64.37: std::out_of_range (deserialization buffer underflow)

Interestingly, the "SELECT p, v, c" is important in the sense that it was important not to select the static column - a "SELECT *" would simply be refused in the CREATE MATERIALIZED VIEW: 
> Unable to include static column 'ColumnDefinition{name=s, type=org.apache.cassandra.db.marshal.Int32Type, kind=STATIC, componentIndex=null, droppedAt=-9223372036854775808}' which would be included by Materialized View SELECT * statement

(by the way, this error message is unnecessarily ugly, we should print the column name - not the other crap, I'll prepare a patch for this unrelated issue).

As another comment, this use case simply doesn't work in Cassandra, it's a Scylla extension. Cassandra doesn't allow the "v = 44" restriction, and fails the CREATE MATERIALIZED VIEW with:
> Non-primary key columns can only be restricted with 'IS NOT NULL' (got: v restricted illegally)

**Comment by psarna** [comment]
Yeah, I have a more or less identical pytest too, right now I'm investigating why exactly providing a dummy static row fixes the issue (I have an educated guess that the builder assumes it exists if the schema definition suggests it does, but I need to verify it), and then I'll post a patch with both the fix and the regression test.

**Comment by psarna** [comment]
There are at least two places in the code which assume that static rows exist if they are present in the schema and we returned rows:

https://github.com/scylladb/scylla/blob/e499f455936e4f15b47f484fe1f55b981602a6dc/mutation_partition.cc#L1956-L1982
https://github.com/scylladb/scylla/blob/e499f455936e4f15b47f484fe1f55b981602a6dc/mutation_partition.cc#L2271

This assumption was broken by my hacky use of the query builder, which was used on synthetic data, hence the failures. I'll send a patch with a test soon.

**Comment by psarna** [comment]
edit: I can see that while adding a static row fixed a segfault, the results are still botched. Namely, the filter is not correctly applied:
```cql
CREATE MATERIALIZED VIEW mv AS SELECT p,c,v FROM t WHERE p IS NOT NULL AND c IS NOT NULL AND v = 44 PRIMARY KEY (p,c,v);
INSERT INTO t(p,c,v) VALUES (42,43,44);
INSERT INTO t(p,c,v) VALUES (42,42,42);
INSERT INTO t(p,c,v) VALUES (1,2,3);
SELECT * FROM mv;

 p  | c  | v
----+----+----
 42 | 42 | 42
 42 | 43 | 44
  1 |  2 |  3

(3 rows)
```

So something is still definitely wrong.

**Comment by psarna** [comment]
It looks like consuming the dummy static row only hid the original issue (still investigating), by violating another assumption that you need to consume a static row first, and only then a regular row. When I used the correct order, the original problem still occurs, so I need to keep looking for the root cause. Now that I think of it, perhaps I shouldn't ask for a wildcard selection, but instead only for key and regular columns. Will verify.

**Comment by avikivity** [comment]
Backported to 4.6, 5.0.
