### ISSUE TITLE
create_lots_of_tables_concurrently_test dtest hangs with --smp=2

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1088]
Not always happens, but happens most of the time.

The hang usually happens inside table merging, which doesn't complete and blocks all further schema change operations, because it runs under global lock.

The hang is directly caused by `invoke_on_all()` not completing, for example this one in `merge_tables`:
```
        return proxy.local().get_db().invoke_on_all([&created, &dropped, &altered, &tsf] (database& db) {
```

The continuation is invoked on local shard, but is never invoked on the remote shard.

Doesn't always happen in this particular `invoke_on_all`.

Also happens with `--poll-mode`.

**Comment by tgrabiec** [comment]
It's a deadlock. 

The `smp_message_queue` limits the number of not completed fibers that can be submitted to another core. This can lead to deadlock if completion of those tasks depends on completion of the task on current core, which needs to submit something to another core to complete.

That's the case for schema merging, where schema change tasks block on the merge lock and merging itself needs to invoke operations on other shards to release the lock.

The following patch, which allows unbounded amount of submitted tasks, fixes the test.

```
diff --git a/core/reactor.cc b/core/reactor.cc
index 5515523..d870242 100644
--- a/core/reactor.cc
+++ b/core/reactor.cc
@@ -1983,7 +1983,7 @@ smp_message_queue::smp_message_queue(reactor* from, reactor* to)
 }
 
 void smp_message_queue::move_pending() {
-    auto queue_room = queue_length - _current_queue_length;
+    auto queue_room = _pending.write_available();
     auto nr = std::min(queue_room, _tx.a.pending_fifo.size());
     if (!nr) {
         return;
```

@avikivity @gleb-cloudius comments?

**Comment by avikivity** [comment]
A complete fix would assign each local procedure call a level, and reserve some execution slots for each level.  Level assignment can be explicit (a parameter to submit_to), or implicit by inheriting the current level from the fiber and increasing it while we're in a submit_to().

Since that is a huge change, we'll be forced to do something like your patch.  It's risky in that many shards can push data to a single shard, so that even though the per-shard limit is respected at the tcp connection level, it is exceeded at the target shard.

Another direction is to eliminate submit_to() nesting: instead of running the code on shard 0, run it on the current shard.

    submit_to(0, acquire_the_lock)
    do_the_op
    submit_to(all, broadcast_results)
    submit_to(0, drop_the_lock)

although, if acquire_the_lock blocks, it may block a broadcast_results.

**Comment by avikivity** [comment]
Maybe we can change lock acquisition to be non-blocking with exponential backoff.  This should remove all dependencies:

    while (!submit_to(0, try_lock))
         sleep(exponential_backoff)
    submit_to(all, broadcast_results)
    submit_to(0, drop_the_lock)

**Comment by avikivity** [comment]
I see that it already runs on the current shard (not shard 0), so maybe it's enough to replace the lock acquisition with exponential backoff.  I'll try it.

**Comment by avikivity** [comment]
@gleb-cloudius says that we should assign a limiter at the receive side of submit_to, and have a separate limiter per message type.

**Comment by avikivity** [comment]
My suggestion:

1. apply my fix to master and 1.0 (non-blocking lock)
2. add server-side submit_to() concurrency limiters based on resource use (similar to rpc memory limiters).  These limiters would be applied for every local procedure call (master only)
3. undo 1 on master

A limiter might look like

    return db.invoke_on(shard_of(...), [] (database& db) {
         return with_semphore(db._limit_sem, 1, [] {
              return db.apply(m);
         });
    });

But maybe we can fold it into the invoke_on API:

    return db.invoke_on(shard_of(...), &database::_limit_sem, 1, [] (database& db) {
        return db.apply(m);
    });

to make the limits more declarative.

(even better would be to associate the limit with the verb, maybe a class sharded::action that is initialized with a pointer-to-member-function and a pointer-to-member-semaphore and is passed as a parameter to invoke_on)

**Comment by nyh** [comment]
On Thu, Mar 24, 2016 at 6:05 PM, Tomasz Grabiec <notifications@github.com>
wrote:

> It's a deadlock.
>
> The smp_message_queue limits the number of not completed fibers that can
> be submitted to another core. This can lead to deadlock if completion of
> those tasks depends on completion of the task on current core, which needs
> to submit something to another core to complete.
>
I think we need to rethink whether there is a theoretical justification to
having a limited queue size, or we *have* to use an unlimited queue.

Having a limited queue size is useful when you want to put "flow control"
on a single fiber: A single fiber which continues to additional requests to
a remote core will at some point block until previous requests have been
fullfilled.

HOWEVER, since a core might be running many independent fibers - an
unlimited number of them - I don't understand why it is fine to limit the
total number of outstanding request. Hanging one fiber just because a
different fiber is hung can lead to deadlocks (as you noticed) as well as
idle time.

I think dropping the limit is a good start, but perhaps we also need a
per-fiber limit? Although since fibers are so simple anyway, it might make
sense to ask the fiber to take care of its own limit (e.g., using a
semaphore, or never sending a new request until the previous one completed).

**Comment by avikivity** [comment]
That's what @gleb-cloudius says, and I agree.

I'm just worried about the transition (dropping the client-side limit without instating a server-side limit) because it can cause a shard to be overwhelmed, where before it would be protected by the client-side limits of callers.

**Comment by tgrabiec** [comment]
27 mar 2016 2:07 PM "Avi Kivity" <notifications@github.com> napisał(a):
>
> That's what @gleb-cloudius says, and I agree.

I agree as well.

I think we should not limit at submit_to level using single limit for all
kinds of invocations. We should have separate limits for different things,
but that must be determined on higher level of abstraction.

Some submissions don't have to be limited at all, for example memory
release from foreign_ptr. It's even better if it isn't.

I share the concerns about stability problems my patch could cause without
extra measures.

>
> I'm just worried about the transition (dropping the client-side limit
without instating a server-side limit) because it can cause a shard to be
overwhelmed, where before it would be protected by the client-side limits
of callers.

For the apply path, it is already throttled by commitlog and memtable on
the target shard, so extra concurrency limit is probably  not necessary
there.

Same for schema merge, concurrency is already limited on the client shard
to 1 by that global lock. On server side we have the memory based limiter
in cql server.

We might need to limit reads.

**Comment by avikivity** [comment]
Even on writes, is the limit applied before allocating extra resources, or not?

Since we pass a `frozen_mutation` by reference, we might be lucky and O(mutation) memory use might be only after we pass another controller.

**Comment by avikivity** [comment]
Filed #1105 for the long-term fix

**Comment by avikivity** [comment]
Tried this:

```
diff --git a/db/schema_tables.cc b/db/schema_tables.cc
index 67aea03..53a23f6 100644
--- a/db/schema_tables.cc
+++ b/db/schema_tables.cc
@@ -68,6 +68,7 @@
 #include "utils/joinpoint.hh"
 
 using namespace db::system_keyspace;
+using namespace std::chrono_literals;
 
 /** system.schema_* tables used to store keyspace/table/type attributes prior to C* 3.0 */
 namespace db {
@@ -492,7 +493,34 @@ read_schema_partition_for_table(distributed<service::storage_proxy>& proxy, cons
 static semaphore the_merge_lock;
 
 future<> merge_lock() {
-    return smp::submit_to(0, [] { return the_merge_lock.wait(); });
+    // ref:  #1088
+    // to avoid deadlocks, we don't want long-standing calls to the shard 0
+    // as they can cause a deadlock:
+    //
+    //   fiber1                fiber2
+    //   merge_lock()                         (succeeds)
+    //                         merge_lock()   (waits)
+    //   invoke_on_all()                      (waits on merge_lock to relinquish smp::submit_to slot)
+    //
+    // so we issue the lock calls with a timeout; the slot will be relinquished, and invoke_on_all()
+    // can complete
+    return do_with(50us, [] (auto& timeout) {
+        return repeat([&timeout] () mutable {
+            return smp::submit_to(0, [] {
+                return the_merge_lock.try_wait();
+            }).then([&timeout] (bool result) {
+                if (result) {
+                    return make_ready_future<stop_iteration>(stop_iteration::yes);
+                } else {
+                    auto to = timeout;
+                    timeout *= 2;
+                    return sleep(to).then([] {
+                        return make_ready_future<stop_iteration>(stop_iteration::no);
+                    });
+                }
+            });
+        });
+    });
 }
```

But it appears to still hang.

**Comment by avikivity** [comment]
Looks like many concurrent callers lock-steped the exponential backoff, causing very long delays.

Randomizing the delay works better.

**Comment by penberg** [comment]
@avikivity Not backported to 1.0?

**Comment by avikivity** [comment]
Cook for a few days?

It's not a bug that users are likely to trigger.
