### ISSUE TITLE
Dropping a table leaves behind an empty subdirectory tree

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10896]
When auto-snapshotting is enabled, DROPing a table leaves the deleted table's sstable directory behind. I consider this a mistake (see #7123 for my alternative proposal), but for now it is well-known and documented.

However, when auto-snapshotting is disabled, users probably expect the delete table's directory to be deleted entirely. Currently, this does not happen: The deleted table's directory is left behind, with empty "staging" and "upload" subdirectories, and that's it.

The negative implications of this issue is that it somewhat slows down access to this directory such as creating a new table in that keyspace. Linux is fairly efficient with large directories, though, so it will not be a huge difference - and indeed in https://github.com/scylladb/scylla/issues/7620#issuecomment-1167271218 I measured it makes only a small (but measurable) difference.
But I think it will be nicer if we clean this up anyway. There is no reason to leave behind a directory with just empty subdirectories. We can try to unlink() those subdirectories and then the top-level directory (if it doesn't succeed, because there are some files left, then only then we should leave the parent directories behind). 

CC @bhalevy

**Comment by fee-mendes** [comment]
> The negative implications of this issue is that it somewhat slows down access to this directory such as creating a new table in that keyspace.

It is not only that. It is worth to mention that `auto_snapshot` does not prevent snapshots from being created, therefore, it also doesn't prevent backups table from being taken. In other words, leaving an empty subdirectory tree behind after every `DROP TABLE` statement basically creates a mess if - for example - one decides to eventually restore from a given backup. The only way to know which "empty directory" is the "effective one" is to actually query the `system_schema` tables.

Another common frustrating scenario is when you want to run `sstabledump`, or any other relevant tool which requires access to the SSTables, depending on how many CREATE/DROP ever existed, it is again a boring task for find the correct `cf-uuid` directory.
