### ISSUE TITLE
[1.0-rc1] Error messages for badly configured scylla.yaml are not very helpful

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#1089]
As suggested by @vladzcloudius, I'm opening this issue.

I did start a scylla cluster node and noticed that scylla wasn't starting on the nodes. I kept getting messages like:

    17:28:12 remote           L0182 DEBUG| [54.152.24.83] [stdout] Mar 23 17:28:12 ip-172-30-0-250 scylla[2142]: Exiting on unhandled exception of type 'std::system_error': Error system:99 (Cannot assign requested address)

Later on, we realized this happened due to a mistake of mine, scylla.yaml was generated on another machine, so the rpc addresses were off. This would've been easier to figure out if the above message contained the IP/port that scylla attempted to assign.

**Comment by penberg** [comment]
Fixed by https://github.com/scylladb/scylla/commit/613e7d8618d4efd4a071798837d95120d60d1850
