### ISSUE TITLE
docker image doesn't run jmx

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#1090]
sudo docker pull scylladb/scylla

sudo docker run -p $(hostname -i):9042:9042 -i -t scylladb/scylla
```
Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Detected lcore 2 as core 2 on socket 0
EAL: Detected lcore 3 as core 3 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 4 lcore(s)
EAL: VFIO modules not all loaded, skip VFIO support...
EAL: Setting up physically contiguous memory...
EAL: TSC frequency is ~3200114 KHz
EAL: Master lcore 0 is ready (tid=3d56c600;cpuset=[0])
EAL: lcore 2 is ready (tid=3059e700;cpuset=[2])
EAL: lcore 3 is ready (tid=2fd9d700;cpuset=[3])
EAL: lcore 1 is ready (tid=30d9f700;cpuset=[1])
Scylla version 0.19-20160310.7c12687 starting ...
Scylla API server listening on 127.0.0.1:10000 ...
```

Both netstat and nodetool cannot reach port 7199

**Comment by slivne** [comment]
@penberg I know you have looked at this in the past and sorting this out was not simple ... (e.g. getting systemd working on docker) 

Can you add the info here so we can continue

**Comment by ycui1984** [comment]
there is a fix on ubuntu platform  @slivne @dorlaor @penberg 
https://github.com/scylladb/scylla/pull/988

**Comment by dorlaor** [comment]
@ycui1984, can you please translate your pull request to patches and send them on the list?
Thanks for bringing it to the surface again

**Comment by ycui1984** [comment]
@dorlaor   I have send the patch to scylla-dev
https://groups.google.com/forum/#!topic/scylladb-dev/nwY21LrJDt4

**Comment by penberg** [comment]
Fixed by https://github.com/scylladb/scylla/commit/144d1e32165e541cf3ee0cbcc3f457e5a08d4979
