### ISSUE TITLE
Reads of recent writes coming from memtable may temporarily miss some of the deletions under rare usage patterns

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#10913]
There is a bug introduced in e74c3c885eac50adeb2285999b5d919da2a763ac (4.6.0) which makes memtable reader skip one a range tombstone for a certain pattern of deletions and under certain sequence of events.

For the problem to trigger, there have to be multiple MVCC versions (at least 2) which contain deletions of the following form:

[a, c] @ t0
[a, b) @ t1, [b, d] @ t2

c > b

The proper sequence for such versions is (assuming d > c): 

[a, b) @ t1, 
[b, d] @ t2

Due to the bug, the reader will produce:

[a, b) @ t1, 
[b, c] @ t0

The reader also needs to be preempted right before processing `[b, d] @ t2` and iterators need to get invalidated so that `lsa_partition_reader::do_refresh_state()` is called and it skips over `[b, d] @ t2`. Otherwise, the reader will emit `[b, d] @ t2` later. If it emits the proper range tombstone, it's possible that it will violate fragment order in the stream if `_rt_stream` accumulated remainders (possible with 3 MVCC versions).

The problem goes away once MVCC versions merge.

**Comment by bhalevy** [comment]
@tgrabiec how does this issue relate to https://github.com/scylladb/scylla/issues/10830?

**Comment by tgrabiec** [comment]
In #10830 we observe a failure in `test_reverse_reader_reads_in_native_reverse_order`, which is about discrepancy between data returned by reversed reader and forward reader with reversed result (which should be the same). The reversed reader hits this bug, whereas the forward reader doesn't, and that's because in reverse the positions of range tombstones are aligned differently. The reverse reader is missing a range tombstone and the row has more live cells than it should.

**Comment by avikivity** [comment]
Backported to 4.6, 5.0.
