### ISSUE TITLE
Scylla starts even though scylla_io_setup has not been run

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1091]
## Installation details
Scylla version (or git commit hash): 1.0-rc1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

Scylla starts even though scylla_io_setup has not been run.

**Comment by slivne** [comment]
@avikivity  is there additional info on how to reproduce ? or any ubuntu 14.04 (with kernel upgraded) without --developer-mode set will reproduce this ?

**Comment by syuu1228** [comment]
@avikivity @slivne After implemented https://github.com/scylladb/scylla/issues/1065, we able to run scylla without running iotune.
Should we prevent it? I think it can be implement on scylla_prepare.

**Comment by syuu1228** [comment]
Seems https://github.com/scylladb/scylla/commit/e750a943000716939bba71c565414eed8b917c68 solve  the problem?

**Comment by syuu1228** [comment]
Please close this, since latest master can cause error when io parameters not assigned.
