### ISSUE TITLE
test/cql-pytest/test_tools.py some tests use the wrong schema file

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10926]
While debugging issue #10924 I noticed an even bigger bug, which will be this issue. Both bugs will probably be fixed together.

The bug is that the `scylla_sstable` fixture in `test/cql-pytest/test_tools.py` is called multiple times for different parameterization, but each time, it writes to the **same** schema file, and returns it.

As far as I understand, the first test that uses this fixture is `test_scylla_sstable_dump` and it causes all instances of `scylla_sstable` to be run once.

The next test that uses this fixture is `test_scylla_sstable_dump_merge`, and that uses the already existing module-scoped fixtures. So all of them use the same schema file - the last one written by the last `scylla_sstable` fixture instantiated!

Unless I'm missing something, I'm worried that this bug didn't cause this test to fail - it means that the test is not actually sensitive to what the schema file contains. So why do we need this file at all?

CC @denesb

**Comment by denesb** [comment]
The test definitely cares about the content of this file, using the wrong schema file should cause the scylla executable invoked to exit with an error.

**Comment by denesb** [comment]
Note that `test_scylla_sstable_dump_merge` depends on the `scylla_sstable` fixture, which itself is parametrized with different schemas, the test generating the schema file for each separate parameter.

**Comment by nyh** [comment]
> Note that `test_scylla_sstable_dump_merge` depends on the `scylla_sstable` fixture, which itself is parametrized with different schemas, the test generating the schema file for each separate parameter.

But the problem is that the earlier `test_scylla_sstable_dump` test also uses the same fixtures, so it instantiates all the different versions, and when the tests for `test_scylla_sstable_dump_merge` start, the fixture is not created again! I added printouts and this is what I see. Am I missing something?

**Comment by denesb** [comment]
To be honest I'm not sure myself how this worked. I know however that using the wrong `schema.cql` with an sstable produces very loud errors, scylla shutting down with an exception. The schema doesn't even have to be very wrong, even a missing field in a UDT or a changed type on a field will produce errors.

**Comment by nyh** [comment]
I think it was a false alarm, but I don't understand how. I added:
```
print(f"NYH running {args}. schema_file={schema_file} content={open(schema_file,mode='r').read()}")
```
And somehow, although all the test share the same file name, it has different content. Somehow the fixture code which re-writes this file was run every time. I still don't understand how, but apparently it's not a bug, so I'm closing this issue.
