### ISSUE TITLE
scylla_io_setup should be available on /usr/bin

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1092]
Since scylla_io_setup is now a user command, it should be on $PATH.

**Comment by slivne** [comment]
Avi we have many setup scripts why is this different

**Comment by avikivity** [comment]
Anything the user needs to run should be on /usr/bin.

Internal scripts should be in /usr/lib (or /usr/libexec)

**Comment by nyh** [comment]
On Thu, Mar 24, 2016 at 6:44 PM, Avi Kivity <notifications@github.com>
wrote:

> Anything the user needs to run should be on /usr/bin.
>
> Internal scripts should be in /usr/lib (or /usr/libexec)
>

The traditional location for scripts that only a superuser would run is
"/usr/sbin".

**Comment by syuu1228** [comment]
Probably all of scylla_*setup scripts should move to /usr/sbin, since it's requires root permission, and user need to run. scylla_prepare, scylla_stop and /usr/lib/scylla/scylla-ami can stay there, since it's internal.

**Comment by penberg** [comment]
The commit was reverted in https://github.com/scylladb/scylla/commit/227daecba613d0bd7deb0d84faea8bf5fae0b99b, reopening.

**Comment by syuu1228** [comment]
Shouldn't we create symlink on /usr/sbin for these scripts?
