### ISSUE TITLE
test/cql-pytest/test_tools.py leave behind files in /tmp

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10924]
Running `test/cql-pytest/run test_tools.py` leaves behind a directory `/tmp/pytest-of-nyh` (where, of course, "nyh" is my username). The only file in this directory is `pytest-0/schema.cql`.

It's better that tests do not generate **any** temporary files at all, but if they must, they need to take better care to remove the temporary file, or place it in the temporary directory which is already created and deleted by `run`.

Noticed by @kostja and @benipeled

**Comment by mykaul** [comment]
@nyh - should it be backported, or can we remove now the 'backport candidate' label?

**Comment by nyh** [comment]
This patch is already in next-5.2 and next-5.1. 
It's not in next-5.0 but test_tools.py didn't exist in that branch, so it didn't exist then.
So nothing left to backport and I'll remove the label.
