### ISSUE TITLE
scylla-server.service on GCE with non-ephemeral disks failing with `seastar - IO-group limits are too low`

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#10927]
## Installation details

Cluster size: 1 nodes (n1-standard-2)

Scylla Nodes used in this run:
- artifacts-gce-image-pd-jenkins-db-node-48085607-0-1 (34.139.16.230 | 10.142.0.32) (shards: -1)

OS / Image: `https://www.googleapis.com/compute/v1/projects/scylla-images/global/images/1014752328245719176` (gce: us-east1)

Test: `artifacts-gce-image-persistent-disk-test`
Test id: `48085607-d374-4beb-a59c-2af18ff56097`
Test name: `scylla-5.0/artifacts/artifacts-gce-image-persistent-disk-test`
Test config file(s):

- [gce-image-persistent-disk.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/3c6df1333f4a3d05bd3bdc8b1f5ccf65a3087a7a/test-cases/artifacts/gce-image-persistent-disk.yaml)

## Issue description

```
Jun 29 00:19:21 artifacts-gce-image-pd-jenkins-db-node-48085607-0-1 scylla[6916]: Scylla version 5.0.0-0.20220628.c9e79cb4a with build-id daef393310f38c086a6e5070c8f2013684973a48 starting ...
Jun 29 00:19:21 artifacts-gce-image-pd-jenkins-db-node-48085607-0-1 scylla[6916]: command used: "/usr/bin/scylla --blocked-reactor-notify-ms 100 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --abort-on-ebadf 1 --enable-sstable-key-validation 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-1 --lock-memory=1"
Jun 29 00:19:21 artifacts-gce-image-pd-jenkins-db-node-48085607-0-1 scylla[6916]: parsed command line options: [blocked-reactor-notify-ms, (positional) 100, abort-on-lsa-bad-alloc: 1, abort-on-seastar-bad-alloc, abort-on-internal-error: 1, abort-on-ebadf: 1, enable-sstable-key-validation: 1, log-to-syslog, (positional) 1, log-to-stdout, (positional) 0, default-log-level, (positional) info, network-stack, (positional) posix, io-properties-file: /etc/scylla.d/io_properties.yaml, cpuset, (positional) 0-1, lock-memory: 1]
Jun 29 00:19:21 artifacts-gce-image-pd-jenkins-db-node-48085607-0-1 scylla[6916]:  [shard 1] seastar - Created fair group io-queue-2064, capacity rate 19:31466, limit 13257966, rate 16777216 (factor 1), threshold 4419322
Jun 29 00:19:21 artifacts-gce-image-pd-jenkins-db-node-48085607-0-1 scylla[6916]:  [shard 1] seastar - IO-group limits are too low
Jun 29 00:20:28 artifacts-gce-image-pd-jenkins-db-node-48085607-0-1 systemd[1]: scylla-server.service: Main process exited, code=exited, status=1/FAILURE
Jun 29 00:20:28 artifacts-gce-image-pd-jenkins-db-node-48085607-0-1 systemd[1]: scylla-server.service: Failed with result 'exit-code'.
Jun 29 00:20:28 artifacts-gce-image-pd-jenkins-db-node-48085607-0-1 systemd[1]: Failed to start Scylla Server.
Jun 29 00:20:28 artifacts-gce-image-pd-jenkins-db-node-48085607-0-1 systemd[1]: Dependency failed for Scylla JMX.
Jun 29 00:20:28 artifacts-gce-image-pd-jenkins-db-node-48085607-0-1 systemd[1]: scylla-jmx.service: Job scylla-jmx.service/start failed with result 'dependency'.
```

refs: #9828
since it was fixed now we are seeing, this current failure.

- Restore Monitor Stack command: `$ hydra investigate show-monitor 48085607-d374-4beb-a59c-2af18ff56097`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=48085607-d374-4beb-a59c-2af18ff56097)
- Show all stored logs command: `$ hydra investigate show-logs 48085607-d374-4beb-a59c-2af18ff56097`

## Logs:
- **db-cluster-48085607.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/48085607-d374-4beb-a59c-2af18ff56097/20220629_002158/db-cluster-48085607.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/48085607-d374-4beb-a59c-2af18ff56097/20220629_002158/db-cluster-48085607.tar.gz)
- **sct-runner-48085607.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/48085607-d374-4beb-a59c-2af18ff56097/20220629_002158/sct-runner-48085607.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/48085607-d374-4beb-a59c-2af18ff56097/20220629_002158/sct-runner-48085607.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.0/job/artifacts/job/artifacts-gce-image-persistent-disk-test/9/)

**Comment by jehanjazz-1** [comment]
Tried to install scylla on a VM (Debian 10) and encountered a similar issue.
Will rolling back to 4.6 help here?

**Comment by xemul** [comment]
https://github.com/scylladb/seastar/issues/1135

**Comment by avikivity** [comment]
@roydahan please advise when latency/throughput regression tests have run with this, so we can consider a backport to 5.0.

**Comment by roydahan** [comment]
Throughput & latency tests looks quite similar to last week results.

**Comment by xemul** [comment]
(couldn't run "classical" merge CI -- dev-headers fails on 5.0 and now it's fatal for CI jobs)

**Comment by fgelcer** [comment]
i have it reproduced with `5.0.0-0.20220706.1ad59d6a7 with build-id 271eb4ed645d5b1c4564acca7fe5f8f400245726`, but this time there is a `Segmentation fault on shard 1.`:

```
[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:750
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:780
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:792
 (inlined by) seastar::sigsegv_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3668
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3654
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3650
?? ??:0
std::vector<unsigned int, std::allocator<unsigned int> >::operator[](unsigned long) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/stl_vector.h:1046
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4065
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4123
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_100>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:291
std::function<void ()>::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:560
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:60
/data/scylla-s3-reloc.cache/by-build-id/271eb4ed645d5b1c4564acca7fe5f8f400245726/extracted/scylla/libexec/scylladb/libreloc/libpthread.so.0 0x9298 
/data/scylla-s3-reloc.cache/by-build-id/271eb4ed645d5b1c4564acca7fe5f8f400245726/extracted/scylla/libexec/scylladb/libreloc/libc.so.6 0x100352 
```

**Comment by xemul** [comment]
`1ad59d6a7`? its seastar doesn't have the scylladb/scylla-seastar@9a7ba6d57ec79862cbb3d0d0905efa9af179a0ba fix

The crashing place is

```c++
    auto alloc_io_queues = [&ioq_topology, &disk_config] (shard_id shard) {
        for (auto& topo : ioq_topology) {
            auto& io_info = topo.second;
            auto group_idx = io_info.shard_to_group[shard]; <<<<<<<<<<<<<<<<< HERE
            std::shared_ptr<io_group> group;

```

@fgelcer , would you open an issue, please?

**Comment by fgelcer** [comment]
> `1ad59d6a7`? its seastar doesn't have the [scylladb/scylla-seastar@9a7ba6d](https://github.com/scylladb/scylla-seastar/commit/9a7ba6d57ec79862cbb3d0d0905efa9af179a0ba) fix
> 
> The crashing place is
> 
> ```c++
>     auto alloc_io_queues = [&ioq_topology, &disk_config] (shard_id shard) {
>         for (auto& topo : ioq_topology) {
>             auto& io_info = topo.second;
>             auto group_idx = io_info.shard_to_group[shard]; <<<<<<<<<<<<<<<<< HERE
>             std::shared_ptr<io_group> group;
> ```
> 
> @fgelcer , would you open an issue, please?

just did here --> https://github.com/scylladb/scylla/issues/11121
