### ISSUE TITLE
/usr/lib/scylla/scylla_io_setup fails with rpm on rackspace

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#1093]
## Installation details
Scylla version (or git commit hash): RC1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL

## Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker): Rackspace compute optimize 15 GB RAM
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

While testing the RC1 rpm on rackspace.

 yum remove -y abrt
yum install epel-release
wget -O /etc/yum.repos.d/scylla.repo https://s3.amazonaws.com/downloads.scylladb.com/rpm/unstable/centos/branch-1.0/2/scylla.repo
yum install scylla-server scylla-jmx scylla-tools

# journalctl
mars 24 16:07:41 benoit-test3 yum[10815]: Installed: scylla-server-1.0.rc1-20160324.c6c176b.el7.centos.x86_64
mars 24 16:07:42 benoit-test3 yum[10815]: Installed: scylla-tools-1.0.rc1-20160324.a41e7e8.el7.centos.noarch
mars 24 16:07:42 benoit-test3 useradd[10934]: failed adding user 'scylla', exit code: 9
mars 24 16:07:43 benoit-test3 yum[10815]: Installed: scylla-jmx-1.0.rc1-20160324.4628683.el7.centos.noarch
mars 24 16:07:43 benoit-test3 systemd[1]: Started Collectd statistics daemon.
mars 24 16:07:43 benoit-test3 systemd[1]: Starting Collectd statistics daemon...

[root@benoit-test3 ~]# /usr/lib/scylla/scylla_io_setup
/usr/lib/scylla/scylla_io_setup: ligne 43 : [: no : nombre entier attendu comme expression
File system on /var/lib/scylla is not qualified for seastar AIO; see http://www.scylladb.com/kb/kb-fs-not-qualified-aio/ for details
/var/lib/scylla did not pass validation tests, it may not be on XFS and/or has limited disk space.
This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is required.
 To override this error, see the developer_mode configuration option.
[root@benoit-test3 ~]# 

"nombre entier attendu comme expression" is the french for "Integer number expected as expression"

**Comment by slivne** [comment]
Thanks bemoit

This wss fixed by a followup patch i sent that was merged this morning by pekka and is not padt og the rpm bit is part of the ami

It also means that all the rest installer testers did not run this script

So thia can be retested on the next rpms (tomorrow)  and then closed

**Comment by slivne** [comment]
on branch-1.0 this is fixed

8422a42381eefad48cacf73add7077d992865dbd
