### ISSUE TITLE
no logs can be found on syslog

### ISSUE THREAD

**Issue by ycui1984** [scylladb/scylla#1094]
## Installation details
Scylla version (or git commit hash): 0.19
Cluster size: 3 nodes in each datacenter (6 nodes total)
OS (Ubuntu):

no logs can be found in syslog, we use the default logging method which prints to syslog, but there is not

## Hardware details (for performance issues)
Platform (physical):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by ycui1984** [comment]
there is some info in dmesg, but not enough to tell me the whole story.

**Comment by syuu1228** [comment]
This seems same issues as https://github.com/scylladb/scylla/issues/1015

**Comment by slivne** [comment]
@ycui1984 is this still an issue for you: did you check /var/log/upstart/scylla-server.log ?

**Comment by ycui1984** [comment]
@slivne thanks for asking, we upgraded the cluster. Right now it seems good.
