### ISSUE TITLE
ENOSPC issue

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#1096]
## Installation details
Scylla version (or git commit hash): rc1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos rackspace

## Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker): compute 15GB
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

I created a huge file on disk leaving only 3MB of disk space _before_ starting scylla and c-s.
c-s failed soon and I removed the big file. c-s cannot be run again: it complains about missing replicas.

**Comment by dorlaor** [comment]
On Thu, Mar 24, 2016 at 9:45 PM, Benoît Canet <notifications@github.com>
wrote:

> Installation details
>
> Scylla version (or git commit hash): rc1
> Cluster size: 1
> OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos rackspace
> Hardware details (for performance issues)
>
> Platform (physical/VM/cloud instance type/docker): compute 15GB
> Hardware: sockets= cores= hyperthreading= memory=
> Disks: (SSD/HDD, count)
>
> I created a huge file on disk leaving only 3MB of disk space *before*
> starting scylla and c-s.
> c-s failed soon and I removed the big file. c-s cannot be run again: it
> complains about missing replicas.
>

Benoit, you're missing lots of details - what's the cluster size, what's
the RF and the CL.
Exact log msg of c-s, that cluster status (nodetool status), etc

**Comment by benoit-canet** [comment]
never succeded to reproduce it and @raphaelsc does not see how it could happen.
