### ISSUE TITLE
what's the largest number of tables of scylladb?

### ISSUE THREAD

**Issue by hiqsociety** [scylladb/scylla#10988]
i was going to create user specific tables but then i was wondering is it possible to create 100 billion tables or better with a few tables and more rows. which is more advisable?

**Comment by nyh** [comment]
This is a bug tracker, please ask questions on our mailing list (scylladb-dev at googlegroups.com) or on stackoverflow, where many more people can offer responses or later re-use the answer.

Anyway the answer is NO, you cannot create 100 billion tables, and you should create a few tables with billions of partitions in each.

There are several reasons for this but the most obvious reason is that each table takes constantly up some memory in each shard to remember its metadata, so a 100 billion tables will mean you'll surely run out of memory. Contrast this with a single table with 100 billion rows, where most of these rows will be on disk, not in memory, and even when some of these rows will be in memory (the row cache), different nodes will cache different rows so if you increase your number of nodes, the size of the useful  cache will also grow (this is different from the 100-billion-table case, where the *same* list of 100 billion tables needs to be repeated on each new node, so adding more nodes doesn't help).
