### ISSUE TITLE
compaction_manager should bypass can_register_compaction if descriptor has_only_fully_expired

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#10989]
If the compaction_descriptor returned by `time_window_compaction_strategy::get_sstables_for_compaction`
is marked with `has_only_fully_expired::yes` it should always be compacted since `time_window_compaction_strategy::get_sstables_for_compaction` is not idempotent.
It sets `_last_expired_check` and if compaction is postponed and retried before `expired_sstable_check_frequency` has passed, it will not look for those fully-expires sstables again.  Plus, compacting them is the cheapest possible as it does not require reading anything, just deleting the input sstables, so there's no reason not postpone it.

**Comment by avikivity** [comment]
Performance only, not backporting.
