### ISSUE TITLE
ninja dev-headers check is currently failing

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#10995]
Our "dev-headers" target helps us confirm that each header includes whatever other headers it needs (unlike the old C tradition of being forced to include some header before including the header you really need).

Because we haven't checked this in a while, we have now several headers that aren't self-sufficient:

1. `utils/sequenced_set.hh`: uses `size_t` instead `std::size_t`
2. `sstables/downsampling.hh`: uses std::array but doesn't know of its subscript operator.
3. `db/per_partition_rate_limit_extension.hh`: missing `db::per_partition_rate_limit_options _per_partition_rate_limit_options` when including `schema.hh`

For the future we should have our CI check dev-headers every time - see https://github.com/scylladb/scylla-pkg/issues/2813

**Comment by xemul** [comment]
> utils/sequenced_set.hh: uses size_t instead std::size_t

WHAT? Since then had it become the mandatory part of std::

**Comment by avikivity** [comment]
It depends if you include <cstdint> or <something_else>. The C things don't need std::.

**Comment by avikivity** [comment]
Not user-facing, not backporting.
