### ISSUE TITLE
Unable to connect with Cassandra 2.1.0 cqlsh

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#11]
When I try connect with `cqlsh` from Cassandra 2.1.0, I get the following error:

```
[penberg@nero apache-cassandra-2.1.0]$ ./bin/cqlsh 127.0.0.1
Connection error: ('Unable to connect to any servers', {'127.0.0.1': KeyError('column_aliases',)})
```

Cassandra 2.1.7 works OK.

**Comment by locked** [comment]
It seems the issue is back, at least on commit 7eb0da3ed8e2e8ea7054c89724ce812d3e86fd14, and with cqlsh from Cassandra 2.1.11, I got:

Connection error: ('Unable to connect to any servers', {'127.0.0.1': ProtocolError("cql_version '3.2.1' is not supported by remote (w/ native protocol). Supported versions: [u'3.2.0']",)})

**Comment by avikivity** [comment]
Try cqlsh from 2.1.9.  Seems like cqlsh is very picky for some reason.

**Comment by slivne** [comment]
In cassandra-2.1.10 the cql binary version has been updated from 3.2.0 to
3.2.1

https://git1-us-west.apache.org/repos/asf?p=cassandra.git;a=blob_plain;f=NEWS.txt;hb=refs/tags/cassandra-2.1.10
,

(git commit 4e3555c1d99b6a3273262443befffe73f86c203d)

You can force cqlsh to use a specific cql version using the flag cqlsh
--cqlversion="3.2.0".

Please note that scylla is distributed with a scylla-tools that provides a
compatible cqlsh/nodetool/cassandra-stress that work with scylla version
you are installing.

While you can use cqlsh from a cassandra distribution, you will not be able
to use the cassandra-stress for cassandra 2.1.X as it requires usage of
thrift and scylla currently only provides cql3 interface.

**Comment by locked** [comment]
Thank you, yes it works with 2.1.8, just thought Scylladb aimed to support cqlsh included in all 2.1.* releases, so I reported it.

**Comment by avikivity** [comment]
Indeed we do, so thanks for the report.  We're approaching it incrementally, so some features may be late to the party.

**Comment by penberg** [comment]
C* 2.1.10 has the following commit:

https://github.com/apache/cassandra/commit/4e3555c1d99b6a3273262443befffe73f86c203d

which introduces a "TRUCATE TABLE X" alias for "TRUNCATE X" and bumps up CQL language version from 3.2.0 to 3.2.1.

That's easy to add to Scylla but will cause a new problem: older ``cqlsh`` versions will refuse to connect because of the CQL language version mismatch. C* has the same issue with older clients.
