### ISSUE TITLE
scylla-service silently failed on Ubuntu

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1103]
Reproduce on Ubuntu 14.0 AMI (ami-5189a661 on west-2)
```
$ sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/ubuntu/scylla.list
$ sudo apt-get update
$ sudo apt-get install scylla-server scylla-jmx scylla-tools
$ sudo service scylla-server start
scylla-server stop/waiting
```
Scylla do not start, and do not return any error to the terminal.

In this case, Scylla service did not start because data dir is not XFS, from `/var/log/syslog`
```
[shard 0] init - /var/lib/scylla/commitlog is not on XFS. This is a non-supported setup, and performance is expected to be very bad.#012For better performance, placing your data on XFS-formatted directories is required. To override this error, see the developer_mode configuration option.
```

This is similar to https://github.com/scylladb/scylla/issues/743 on CentOS

**Comment by slivne** [comment]
judgin by the repo this was run against 0.19 not toward 1.0

**Comment by tzach** [comment]
@slivne correct, I followed the instruction in the site, and the public repo (0.19)

**Comment by slivne** [comment]
@tzach the version you used is 0.19 ...

Can you try rc1

**Comment by tzach** [comment]
Reproduce the same problem for RC1, using the same Ubuntu AMI
```
$ sudo wget -O /etc/apt/sources.list.d/scylla.list https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/ubuntu/branch-1.0/7/scylla.list
$ sudo apt-get update
$ sudo apt-get install scylla-server scylla-jmx scylla-tools
$ sudo service scylla-server start
scylla-server stop/waiting
```

Same XFS error in /var/log/syslog

**Comment by syuu1228** [comment]
I think this is Upstart specification, it does not have same behaviour as systemd.
You need to see /var/log/syslog, or /var/log/upstart/scylla-server.log.
It's not limited to scylla, all Upstart jobs.
Possible solution is switch to 16.04LTS, it is using systemd.

**Comment by tzach** [comment]
@syuu1228 this give bad UX for ubuntu users.
Any way to have a bypass for Upstart?

**Comment by syuu1228** [comment]
@tzach Use systemd. New 16.04LTS will release in later on this month, we can switch to it.

**Comment by tzach** [comment]
Closing as the problem is lack of feature in 14.04 Upstart
Systemd will solve this, like so many other problem
