### ISSUE TITLE
storage_service/keyspaces?type=user returns non-user keyspaces

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#11042]
Currently, we get the list of keyspace for the `user` option with https://github.com/scylladb/scylla/blob/98aa3ec99b9b16dc60bace1aa8982e8a7d58514f/api/storage_service.cc#L797-L798

This `get_non_system_keyspaces` function name is misleading since it returns several keyspaces that aren't considered "system" by our internal definitions, but they are certainly not user keyspace.

For example:
```
$ scylla-api-client storage_service/keyspaces --type user
["system_traces","system_auth","system_distributed","system_distributed_everywhere"]
```

Instead, we need to filter all keyspaces that are `!is_internal_keyspace`, based on https://github.com/scylladb/scylla/blob/98aa3ec99b9b16dc60bace1aa8982e8a7d58514f/replica/distributed_loader.cc#L54-L56

**Comment by bhalevy** [comment]
Cc @amnonh 

@Deexie when fixing please add a rest_api test that can create a keyspace and makes sure it is included in the list returned with the `user` option, while non of the other keyspace names returned there begin with "system".
I believe this user keyspace should be returned with all options (default (i.e. no option given), `user`, `non_local_strategy`, and `all`)

**Comment by avikivity** [comment]
Minor, not backporting.
