### ISSUE TITLE
Scylla allows selecting by NULL static column, but doesn't return anything

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla#11070]
Master: 0a71151bc4aed36850e04ac4c3a890fe00e05630

Consider the following sequence of CQL commands:

```cql
cqlsh> create table ks.tbl (pk int, ck int, s int static, v int, primary key (pk, ck));
cqlsh> insert into ks.tbl (pk, ck, v) values (1, 2, 3);
cqlsh> select * from ks.tbl where s = NULL ALLOW FILTERING;
```

When run on Cassandra, the last query fails with the following error:

```
InvalidRequest: Error from server: code=2200 [Invalid query] message="Unsupported null value for column s"
```

Meanwhile, Scylla behaves differently and accepts the last query but doesn't return anything:

```

 pk | ck | s | v
----+----+---+---

---MORE---
(0 rows)
```

...even though the partition in the table has the static column set to NULL:

```cql
cqlsh> select * from ks.tbl;

 pk | ck | s    | v
----+----+------+---
  1 |  2 | null | 3
```

**Comment by avikivity** [comment]
`NULL = NULL` should evaluate to `false`, so Scylla behavior is correct.

To look for NULL cells, implement `IS NULL` and query `SELECT * FROM ks.tbl WHERE s IS NULL ALLOW FILTERING AND WRITE EVERYTHING IN CAPITAL LETTERS`

**Comment by avikivity** [comment]
(and also note: LWT `IF` conditions evaluate `col = NULL` as TRUE if col is NULL; I consider it a bug in Scylla and Cassandra).

**Comment by piodul** [comment]
Oh, right, comparing with NULL works differently... Still, there is a difference in behavior between C* and Scylla. Should we disallow such queries, or it's OK as it is now and the issue can be closed?

**Comment by avikivity** [comment]
It's okay to have extensions, so long as they are reasonable (= follow the spirit of CQL/SQL).
