### ISSUE TITLE
try_flush_memtable_to_sstable consumer does not close reader on failure

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#11075]
Currently https://github.com/scylladb/scylla/blob/d40106d3a9879aad04823fb06ea4f3cada797785/replica/table.cc#L656
doesn't close the reader passed to it if exception is thrown.

Even if `write_memtable_to_sstable` fails in https://github.com/scylladb/scylla/blob/d40106d3a9879aad04823fb06ea4f3cada797785/replica/table.cc#L668
the reader must be closed since moving it to `write_memtable_to_sstable` may have not been performed.

**Comment by avikivity** [comment]
Not backporting, it's in 5.1 and doesn't appear to hit users.
