### ISSUE TITLE
[1.0 rc1] nodetool statusbinary is not working 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1108]
## Installation details
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

## Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by penberg** [comment]
Fixed by https://github.com/scylladb/scylla-tools-java/commit/01ce9cf3d71d6c1e43061d868bf8df58e1992ee6
