### ISSUE TITLE
scylla_setup causes 'Unsupported bootloader' on Fedora 22 AMI

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#1109]
On Fedora-22 official AMI, I've got following error:
```
Do you want to setup bootloader options?
yes/no: yes
Unsupported bootloader
```
This is because Fedora-22 AMI uses extlinux, and scylla_booparam_setup doesn't supported it.
This is unusual configuration, so we probably won't get this error on another environment, but need to fix.
We actually supported extlinux at once, but we dropped it when we switched base AMI to CentOS:
https://github.com/scylladb/scylla/commit/b3c85aea89ce0ca807e1a484fb51c7f6f433cfdf#diff-ad351f01e6867ddf23195c4f077fbcbdL25
It was wrong, we need to support it again.

**Comment by dorlaor** [comment]
IMHO it doesn't worth to have a Fedora rpm and it's only worth
to maintain the source code build on Fedora. Most users use either Ubuntu
or Centos while
Fedora is purely for developers. We can't keep up with the fast pace
releases too
