### ISSUE TITLE
scylla_raid_setup misinterprets blank input as '/dev/'

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#1110]
It seems regression after merged https://github.com/scylladb/scylla/commit/6edd909b00dcd0f608b4809a6d4bce565b0a954c
```
Please select disks from following list:
xvda xvdb xvdc
type 'done' to finish selection. selected:
> xvdb
xvda xvdb xvdc
type 'done' to finish selection. selected: /dev/xvdb
>
xvda xvdb xvdc
type 'done' to finish selection. selected: /dev/xvdb,/dev/
```

**Comment by syuu1228** [comment]
Note: not affected on branch-1.0

**Comment by syuu1228** [comment]
My previous note was wrong.
It occurs on branch-1.0.
https://github.com/scylladb/scylla/blob/branch-1.0/dist/common/scripts/scylla_setup#L171

**Comment by slivne** [comment]
@syuu1228 is this only when working in interactive mode ?

**Comment by syuu1228** [comment]
@slivne only on interactive mode. But it was also missing device existence check, implemented at https://github.com/scylladb/scylla/commit/c1277bacb4dcce70f10422dc87f63a4921eeecc2
