### ISSUE TITLE
Change the commitlog naming so it won't match origin

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#1112]
sstables2json may write commitlog files and thus may confuse Scylla.
It's totally bogus that it writes any commitlog and thus we like to stay on
the safe side and change our commitlog naming scheme.

**Comment by avikivity** [comment]
This is problematic, because a migrated commitlog directory will be ignored, and the user will experience data loss.

**Comment by nyh** [comment]
On Mon, Mar 28, 2016 at 1:52 PM, Avi Kivity <notifications@github.com>
wrote:

> This is problematic, because a migrated commitlog directory will be
> ignored, and the user will experience data loss.
>
We could explicitly check (based on filename) for the existance of such
Cassandra commitlogs on startup, and add a clear and explicit message in
that case suggesting what to do. It's better than failing in the middle of
the boot process with some exception from the middle of the file parsing
code. Also checking for file names or directory names is more bulletproof
than trying to check if this is a Cassandra or Scylla commitlog based on
its actual content.

I think in the long run, the fix suggested in this issue would be the best
fix... But the other proposals will work too (if implemented), so I guess
it's ok that you closed this issue.

**Comment by avikivity** [comment]
This can work, but if we change the names of commitlog segments generated by offline tools (sstable2json) and keep Scylla names the same.

So, copying a commitlog file from Cassandra will prevent Scylla from starting up (and losing data), while running sstable2json will generate commitlog segments that Scylla will ignore.
