### ISSUE TITLE
mutation_compactor: consumer's wish to stop is ignored in consume(range_tombstone_change)

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#11138]
Introduced by ad435dcf570c1e8b3bbdee001fb5b712df565fc6, so is broken ever since the compactor supports v2 output.
No known adverse affects, besides mutation reads stopping a little later than desired (on the next non-range-tombstone-change fragment) and hence consuming more memory than the limit set for them.

**Comment by avikivity** [comment]
No significant impact per report, not backporting.
