### ISSUE TITLE
Consumer receives out of order mutation fragments when consuming a reversed mutation

### ISSUE THREAD

**Issue by mikolajsieluzycki** [scylladb/scylla#11147]
Reversing a mutation which has interleaved range tombstones and clustering rows, where the last clustering row is dummy, produces out of order mutation fragments.

The function `consume_clustering_fragments` that orders them, reverses the clustering rows, making the last dummy one the first one to compare. Due to how positions are compared, all range tombstones are ordered first, then the dummy clustering row is skipped and clustering rows are consumed without properly interleaving them with range tombstones.

**Comment by bhalevy** [comment]
This may need backport to 5.0

**Comment by denesb** [comment]
I don't think we need to backport to 5.0. Only unit-tests are affected in said release.

**Comment by avikivity** [comment]
Not backporting per above.
