### ISSUE TITLE
enable tcp_synchookies

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#1118]
Scylla may open a lot of connections simultaneously which may overflow Linux's syn backlog. tcp_synchookies eliminate sync backlog entirely and handle large number of simultaneous connection much better.

**Comment by nyh** [comment]
What is this issue about? Enabling the Linux option tcp_syncookies (sic) in the AMI? Adding this feature in the native stack? Recommending it in a document? All of the above?

By the way, on my Fedora 23, by default:
```
 cat /proc/sys/net/ipv4/tcp_syncookies
1
```

**Comment by gleb-cloudius** [comment]
On Mon, Mar 28, 2016 at 01:51:46AM -0700, nyh wrote:
> What is this issue about? Enabling the Linux option tcp_syncookies (sic) in the AMI? Adding this feature in the native stack? Recommending it in a document? All of the above?
> 
Wherever it is appropriate to do so. My guess is in our setup script.

> By the way, on my Fedora 23, by default:
> ```
>  cat /proc/sys/net/ipv4/tcp_syncookies
> 1
> ```
> 
It is disabled on (at least some) Ubuntus.

--
			Gleb.

**Comment by syuu1228** [comment]
I checked Ubuntu 14.04LTS and 15.10, both are net.ipv4.tcp_syncookies = 1.
Also compared AMI and local VM, no difference.
So I'm not sure our supported Ubuntu version disables it (looks like not).

How about to add sanity check for this? Even we don't know which environment disables it, we can notice it should be enable.

**Comment by avikivity** [comment]
It is enabled by default on CentoOS and Fedora as well.  Looks like a kernel default, so we don't need to touch it.

    net/ipv4/tcp_minisocks.c:int sysctl_tcp_syncookies __read_mostly = 1;

**Comment by gleb-cloudius** [comment]
On Sun, Apr 03, 2016 at 12:12:46AM -0700, Avi Kivity wrote:
> It is enabled by default on CentoOS and Fedora as well.  Looks like a kernel default, so we don't need to touch it.
> 
>     net/ipv4/tcp_minisocks.c:int sysctl_tcp_syncookies __read_mostly = 1;
> 
> 
On Ubuntu 14 is was disable, so we need to make sure it is on instead of
relaying on a default that may or may not be used.

--
			Gleb.

**Comment by avikivity** [comment]
Just checked a local 14.04 VM and it was enabled.

**Comment by gleb-cloudius** [comment]
On Sun, Apr 03, 2016 at 12:26:41AM -0700, Avi Kivity wrote:
> Just checked a local 14.04 VM and it was enabled.
> 
May be it was local config on the machine I saw it on. But we better make
sure for important setting they are what we want them to be.

--
			Gleb.
