### ISSUE TITLE
NIC interrupts routed to cpu0 kill performance

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1126]
*Installation details*
Scylla version (or git commit hash): 1.0-rc2
Cluster size: 9
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): Rackspace physical 20 core
Hardware: sockets=2 cores=20 hyperthreading=y memory=128GB

All NIC interrupts are routed to cpu0 by default, killing its performance.

Running

    /usr/lib/scylla/posix_net_conf.sh eth0 -mq
    /usr/lib/scylla/posix_net_conf.sh eth1 -mq

fixes things, but that is not something that a user would guess.

**Comment by avikivity** [comment]
We actually have code for this in `scylla_prepare`, but:

 - `IF_NAME` is set incorrectly
 - `SET_NIC` is `no`
 - the script doesn't use `-mq`

**Comment by syuu1228** [comment]
I think we should config it by scylla_setup script.
When we need to use posix_net_conf.sh? Any machines which has cpus >= 8?

**Comment by avikivity** [comment]
With -mq it can be used for any size (without reserving cpu0 for interrupts), as long as the NIC supports multiqueue.

**Comment by slivne** [comment]
Check #1063 and #891 they are directly related to this and vlad i think has
made some progress

**Comment by avikivity** [comment]
Fixed by 0c7f9917dc2243ee3cc38bc94f289745dd103877.
