### ISSUE TITLE
[AMI 1.0-rc1 m3.medium] - Longevity Tests - stop_start_monkey - cassandra-stress does not survive

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#1130]
## Installation details
Scylla version (or git commit hash): 1.0-rc1
Cluster size: m3.medium
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

## Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker): AWS
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

Running the latest AMI for 1.0-rc1, m3.medium instance, using our StopStart monkey, cassandra-stress survives for about 15 minutes:

    17:53:53 remote           L0773 DEBUG| Remote [centos@52.53.230.49]: Running 'cassandra-stress write cl=QUORUM duration=1440m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=1000 -node 172.31.28.230'
    ...
    18:07:05 remote           L0182 DEBUG| [52.53.230.49] [stdout] java.io.IOException: Operation x10 on key(s) [37504f4c373230373031]: Error executing: (WriteTimeoutException): Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)

As a reference, the same test with larger instance types, such as c3.large, c3.2xlarge are passing. Likely the instances don't have enough resources to handle competently the above cassandra-stress workload.

**Comment by slivne** [comment]
@lmr asside from the timeout is there another issue ...

seeing some timeouts while some of the load is passing (e.g. printout of stats lines from c-s with some ops passing) may be ok

If c-s prints 0 completed operations then that is probably not ok as well.

another method to validate this is ok is to try and run this toward a cassandra cluster using the same instance type - if it "works" on c* then we certainly need to keep digging.

if we reduce the load concurrency (less threads) will it work ?

**Comment by lmr** [comment]
If less threads are used, my guess is that the test will pass.

**Comment by lmr** [comment]
This issue is caused by an insufficient amount of resources to handle the c-s command thrown at the cluster. I'm closing this, as currently there's no reasonable solution for it.
