### ISSUE TITLE
nodetool snapshot does not support -kc tag

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#1133]
nodetool snapshot should support the -kc tag which allows passing a list of keyspace.column_family.
Currently when passing the -kc tag, no snapshot is being created.

## Installation details
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

## Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by amnonh** [comment]
@slivne assign it to me, I think it will be easier to implement inside the jmx

**Comment by slivne** [comment]
@amnonh I think there is a test in nodetool_additional_tests that is marked skip because of this issue - we can now test that it passes and remove the skip.

**Comment by amnonh** [comment]
I though that I did

**Comment by slivne** [comment]
at least head does not have it ... is it a pending pull request

**Comment by amnonh** [comment]
I'll look for it
