### ISSUE TITLE
removenode status and force not supported

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#1135]
Affected nodetool command
nodetool removenode force
nodetool removenode status
## Installation details
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

## Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by asias** [comment]
I am implementing the missing 

storage_service::get_removal_status (nodetool removenode status)
storage_service::force_remove_completion (nodetool removenode force).

@amnonh Can you please update the api/api-doc/storage_service.json to add these two apis and update nodetool to wire them up?

**Comment by amnonh** [comment]
They are already in the json file under:
GET:/storage_service/removal_status
POST:/storage_service/force_remove_completion

**Comment by asias** [comment]
On Mon, Apr 11, 2016 at 3:26 PM, Amnon Heiman <notifications@github.com>
wrote:

> They are already in the json file under:
> GET:/storage_service/removal_status
> POST:/storage_service/force_remove_completion
>

Great! I will wire them up. Thanks.



> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/1135#issuecomment-208199349>
>



-- 
Asias

**Comment by asias** [comment]
Patches are sent on list.

**Comment by slivne** [comment]
@asias do we have a dtest for this ?

**Comment by asias** [comment]
We only have 'nodetool removenode' in update_cluster_layout_tests.py . I think we need them in nodetool_additional_test.py. @amnonh
