### ISSUE TITLE
nodetool disablebinary

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1137]
Disables the native transport
Similar to
http://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsDisableBinary.html

**Comment by amnonh** [comment]
This is supported, please close

**Comment by tzach** [comment]
I'm happy to

**Comment by slivne** [comment]
@amnonh do we have a dtest for this ?

**Comment by amnonh** [comment]
yes the binary_test
