### ISSUE TITLE
nodetool decommission not completing 

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#1140]
## Installation details
Scylla version (or git commit hash):ami-438f8629
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

## Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker): C3.4xlarge
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count) SSD, 1 root + 2 data

 cassandra-stress write n=1000000000 -rate threads=700 -node 10.35.212.14 is started on a loader node.

then nodetool decommission is started on one of the db node.

nodetool decommission does not stop and some transiant error are seen on the cassandra stress output:

com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)
total,     400875073,   88470,   88470,   88470,     7.9,     7.5,    14.7,    20.9,    28.3,    35.2, 3738.4,  0.00679,      0,      0,       0,       0,       0,       0
total,     401163127,   84497,   84497,   84497,     8.3,     7.3,    15.8,    22.7,    60.2,  2454.8, 3741.8,  0.00679,      0,      0,       0,       0,       0,       0
total,     401257208,   90176,   90176,   90176,     7.7,     6.9,    15.5,    23.1,    88.3,   118.2, 3742.8,  0.00679,      0,      0,       0,       0,       0,       0
total,     401350730,   90298,   90298,   90298,     7.7,     7.1,    15.8,    21.7,    29.3,    43.9, 3743.8,  0.00679,      0,      0,       0,       0,       0,       0
total,     401444452,   90756,   90756,   90756,     7.7,     6.8,    16.0,    22.0,    30.1,    38.8, 3744.9,  0.00679,      0,      0,       0,       0,       0,       0
total,     401539097,   92071,   92071,   92071,     7.6,     6.5,    16.5,    22.5,    30.4,    42.1, 3745.9,  0.00679,      0,      0,       0,       0,       0,       0
total,     401632808,   91120,   91120,   91120,     7.7,     6.8,    16.1,    21.6,    28.6,    37.4, 3746.9,  0.00678,      0,      0,       0,       0,       0,       0
total,     401725406,   89943,   89943,   89943,     7.8,     6.7,    16.7,    22.1,    30.2,    41.1, 3748.0,  0.00678,      0,      0,       0,       0,       0,       0
total,     401819424,   90878,   90878,   90878,     7.6,     6.5,    16.3,    21.9,    29.4,    38.0, 3749.0,  0.00678,      0,      0,       0,       0,

**Comment by benoit-canet** [comment]
from a cqlsh describe schema replication factor is 1.

**Comment by benoit-canet** [comment]
[centos@ip-10-137-133-165 ~]$ nodetool gossipinfo
/10.137.133.165
  generation:1459255077
  heartbeat:5772
  NET_VERSION:0
  DC:datacenter1
  RACK:rack1
  HOST_ID:25f1aeb5-865c-4be7-bbb0-671c3cbd6965
  RELEASE_VERSION:2.1.8
  STATUS:LEAVING,941992870314431344
  LOAD:5.01487e+10
  SCHEMA:b656e4a0-f72c-3bad-ab23-8da25b1151cb
  RPC_ADDRESS:10.137.133.165
/10.35.212.14
  generation:1459253555
  heartbeat:7293
  NET_VERSION:0
  DC:datacenter1
  RACK:rack1
  HOST_ID:180af6b1-7f13-46f8-aee6-0611be321311
  RELEASE_VERSION:2.1.8
  STATUS:NORMAL,9206905351275354475
  LOAD:7.66394e+10
  SCHEMA:b656e4a0-f72c-3bad-ab23-8da25b1151cb
  RPC_ADDRESS:10.35.212.14
/10.47.197.90
  generation:1459253553
  heartbeat:7333
  NET_VERSION:0
  DC:datacenter1
  RACK:rack1
  HOST_ID:6dfe0406-2f3d-4ba6-b105-fe55244484b8
  RELEASE_VERSION:2.1.8
  STATUS:NORMAL,9140169773223873421
  LOAD:8.37762e+10
  SCHEMA:b656e4a0-f72c-3bad-ab23-8da25b1151cb
  RPC_ADDRESS:10.47.197.90

**Comment by slivne** [comment]
@benoit-canet can you please provide a scenario that reproduces this consistently (if not ocnsistent 1 out of 2) and then we will be work on this.

Once you do provide a scenario I'll ask @asias to take over and reproduce on his own - and teach us  how to analyze this cases.

**Comment by asias** [comment]
@benoit-canet can you please provided the complete logs of each node. It is hard to tell what is going without looking at it.

**Comment by benoit-canet** [comment]
Create a 3 node cluster of c3.4xlarge with AMI ami-438f8629.

Use:

    --clustername test-cluster
    --totalnodes 3

Use an all open security group.

**Comment by asias** [comment]
@benoit-canet why do you mention nodetool removenode here? Don't you want to test decommission. Wait for the decommission to complete, it might take a long time due to the load is running and a lot of data is in the cluster already which we need to stream in the decommission process.

**Comment by benoit-canet** [comment]
@asias: sorry I edited the wrong bug comment and mixed it up. It's fixed now.

**Comment by slivne** [comment]
@benoit-canet thanks for proviidng a scenario that reproduces

**Comment by asias** [comment]
I think this is related to the hang in issue #1144

**Comment by lmr** [comment]
@benoit-canet I'm still having trouble to reproduce this problem. I tried with the GA AMI, and here's what I've got:

    Cluster lmr-scylla-db-cluster-371e2c04 (AMI: ami-7251bb12 Type: c3.4xlarge)

    20:17:13 wait             L0044 DEBUG| Waiting until cfstat 'Space used (total)' reaches value '6442450944' (412.481284857 s)
    ...
    21:05:11 cluster          L0539 DEBUG| Cluster lmr-scylla-db-cluster-371e2c04 (AMI: ami-7251bb12 Type: c3.4xlarge): Done waiting on cfstats: [6756848835, 12843621861, 10708174597, 10378248968, 12925770656, 16343612171]

    04:16:47 nemesis          L0074 INFO | sdcm.nemesis.DecommissionMonkey: Report
    04:16:47 nemesis          L0075 INFO | sdcm.nemesis.DecommissionMonkey: DB Version:
    04:16:47 nemesis          L0077 INFO | sdcm.nemesis.DecommissionMonkey: scylla-boost-date-time-1.58.0-11.el7.centos.x86_64
    04:16:47 nemesis          L0077 INFO | sdcm.nemesis.DecommissionMonkey: scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
    04:16:47 nemesis          L0077 INFO | sdcm.nemesis.DecommissionMonkey: scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
    04:16:47 nemesis          L0077 INFO | sdcm.nemesis.DecommissionMonkey: scylla-boost-system-1.58.0-11.el7.centos.x86_64
    04:16:47 nemesis          L0077 INFO | sdcm.nemesis.DecommissionMonkey: scylla-boost-test-1.58.0-11.el7.centos.x86_64
    04:16:47 nemesis          L0077 INFO | sdcm.nemesis.DecommissionMonkey: scylla-boost-thread-1.58.0-11.el7.centos.x86_64
    04:16:47 nemesis          L0077 INFO | sdcm.nemesis.DecommissionMonkey: scylla-env-1.0-1.el7.centos.noarch
    04:16:47 nemesis          L0077 INFO | sdcm.nemesis.DecommissionMonkey: scylla-gdb-7.10.1-30.el7.centos.x86_64
    04:16:47 nemesis          L0077 INFO | sdcm.nemesis.DecommissionMonkey: scylla-jmx-1.0.0-20160331.295f925.el7.centos.noarch
    04:16:47 nemesis          L0077 INFO | sdcm.nemesis.DecommissionMonkey: scylla-server-1.0.0-20160331.9fae641.el7.centos.x86_64
    04:16:47 nemesis          L0077 INFO | sdcm.nemesis.DecommissionMonkey: scylla-tools-1.0.0-20160331.46507fa.el7.centos.noarch
    04:16:47 nemesis          L0078 INFO | sdcm.nemesis.DecommissionMonkey: Interval: 300 s
    04:16:47 nemesis          L0079 INFO | sdcm.nemesis.DecommissionMonkey: Average duration: 346 s
    04:16:47 nemesis          L0080 INFO | sdcm.nemesis.DecommissionMonkey: Total execution time: 29186 s
    04:16:47 nemesis          L0081 INFO | sdcm.nemesis.DecommissionMonkey: Times executed: 40
    04:16:47 nemesis          L0082 INFO | sdcm.nemesis.DecommissionMonkey: Unhandled exceptions: 0

So the test suite waited until all nodes had at least 6GB (6x1024^3 B) then started decommission monkeys. After that we executed decommission monkey for 40 times, and the decomission/new node addition averaged about 5 minutes each.

**Comment by penberg** [comment]
Isn't this fixed by https://github.com/scylladb/scylla/commit/45527fcffa6cf7aee80da3e37d3713ff3ce5f72f like #1144 is?

**Comment by benoit-canet** [comment]
Fixed with 1.1 AMI (ami-1b5eb276)
