### ISSUE TITLE
add node failing on EC2

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#1143]
# Installation details

Scylla version (or git commit hash):ami-438f8629
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

## Hardware details (for performance issues)

Platform (physical/VM/cloud instance type/docker): C3.4xlarge
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count) SSD, 1 root + 2 data

**Comment by dorlaor** [comment]
What about the logs? How did the operation fail?..

**Comment by slivne** [comment]
@benoit-canet is this a dup of #1144 with less info

**Comment by benoit-canet** [comment]
yes
