### ISSUE TITLE
CQL base SSTable Loader

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1145]
Cassandra sstable loader is using internal interfaces which make it error prone and hard to use.
A better SSTable Loader will use the native, well define CQL interface.

**Comment by tzach** [comment]
duplicate #514 ?

**Comment by penberg** [comment]
Yes, it's a duplicate, and we already have this implemented: https://github.com/scylladb/scylla-tools-java/commit/da4585a429b4f314aa2e29867a58147415cfae06
