### ISSUE TITLE
Add support for SUPPORTED_FEATURES

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1152]
There is a need to have an ability to detect whether a features is
supported by entire cluster. The way to do it is to advertise feature
availability over gossip and then each node will be able to check if all
other nodes have a feature in question.

The idea is to have new application state SUPPORTED_FEATURES that will contain
set of strings, each string holding feature name.

**Comment by penberg** [comment]
Fixed by https://github.com/scylladb/scylla/commit/47a904c0f6b0f032c2a750b25217b840b3694d3b
