### ISSUE TITLE
Write range tombstones to sstables like Cassandra does

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#1153]
Cassandra and Scylla hold internally the list of range tombstones differently: Scylla holds overlapping tombstones of whole clustering rows of various levels, while Cassandra keeps a list of non-overlapping ranges (see RangeTombstoneList.java) which might not be whole rows.

As an example, the following two deletions of whole rows of two levels:
```
create table tab (pk text, ck1 text, ck2 text, data text, primary key(pk, ck1, ck2));
delete from tab where pk = 'pk' and ck1 = 'aaa';
delete from tab where pk = 'pk' and ck1 = 'aaa' and ck2 = 'bbb';
```

Are written by Cassandra to the sstable as *three* range tombstones:
```
{"key": "pk",
  "cells": [["aaa:_","aaa:bbb:_",1459334681228103,"t",1459334681],
               ["aaa:bbb:_","aaa:bbb:!",1459334681244989,"t",1459334681],
               ["aaa:bbb:!","aaa:!",1459334681228103,"t",1459334681]]}
              ]
```

In commit 99ecda3c9657eb882c064e177a537dce05bf5b87 we fixed Scylla's **read** side, so we can read from Cassandra's sstable a list of non-overlapping and not-whole-row range tombstones, and convert them into Scylla's overlapping whole-row tombstones.

Now, we also need to do this in the sstable **write** side (sstable::write_clustered_row() and sstable::do_write_components()): Instead of writing the overlapping range tombstones, we need to split them up as Cassandra does and write the split up ones to the sstable. 

The worry is that if we don't do this, "reverse migration" (from ScyllaDB back to Cassandra) will be broken.

**Comment by slivne** [comment]
@duarten as its only a little delta over #1155 and you know how todo it already - then we can handle it - if its more we will postpone it

**Comment by tgrabiec** [comment]
I don't think there is a requirement for range tombstones in sstables to be non-overlapping.

I've noticed that sstable writer in C* has code which assumes that overlapping range tombstones may occur in the input stream. 

I did the following experiment to verify that C* generates such sstables:

  1) `delete from tab where pk = 'pk' and ck1 = 'aaa';`
  2) `nodetool flush`

```
$ sstable2json data/data/ks1/tab-5f11649037c111e6b771d5ed4b22c0da/ks1-tab-ka-1-Data.db
[
{"key": "pk",
 "cells": [["aaa:_","aaa:!",1466521438582994,"t",1466521438]]}
]
```

  3) `delete from tab where pk = 'pk' and ck1 = 'aaa' and ck2 = 'bbb';`
  4) `nodetool flush`

```
$ sstable2json data/data/ks1/tab-5f11649037c111e6b771d5ed4b22c0da/ks1-tab-ka-2-Data.db
[
{"key": "pk",
 "cells": [["aaa:bbb:_","aaa:bbb:!",1466521488671859,"t",1466521488]]}
]
```

  5) `nodetool compact`

```
$ sstable2json data/data/ks1/tab-5f11649037c111e6b771d5ed4b22c0da/ks1-tab-ka-3-Data.db 
[
{"key": "pk",
 "cells": [["aaa:_","aaa:!",1466521438582994,"t",1466521438],
           ["aaa:bbb:_","aaa:bbb:!",1466521488671859,"t",1466521488]]}
]
```

As you can see, the third sstable, which is a result of compacting two previous sstables, has overlapping range tombstones. The fact that the sstable flushed from a single memtable has non overlapping tombstones is the result of implementation detail of how range tombstones are kept in memory.

So I think this is not a bug and we should be prepared to handle overlapping tombstones.

**Comment by duarten** [comment]
Can this one be closed then?

**Comment by pdziepak** [comment]
Yes, it's not an issue.
