### ISSUE TITLE
In internal representation, hold generic range tombstones

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#1155]
Cassandra and Scylla hold internally the list of range tombstones differently: Scylla holds overlapping tombstones of *whole* clustering rows of various levels, while Cassandra keeps a list of non-overlapping ranges (see RangeTombstoneList.java) which might not be whole rows.

This difference complicates the sstable reading and writing code, which needs to convert the two types of lists back and forth (see commit  99ecda3c9657eb882c064e177a537dce05bf5b87 and the still-open issue #1153 ). Moreover, Scylla's approach has two additional downsides:

1. Scylla only supports whole-row deletions, so in the future we will not be able to support commands to delete parts of rows, like "DELETE WHERE ck1 < 7" - which Cassandra 3 already supports (Cassandra 2 didn't, by the way).
2. Our lookup for the tombstones can be slower (in Cassandra's non-overlapping tombstones, only one lookup is needed).

So this issue asks that we switch our internal representation from whole-row tombstones (held in the clustered_rows and for larger deletions, row_tombstones) to a non-overlapping list of generic range tombstones.

**Comment by nyh** [comment]
@avikivity wrote the following in the mailing list:

> To support range tombstones efficiently, I think we should store them as a disjoint set of range.  For example, if the input is
>    [-inf, 8) -> ts1, [4] -> ts2, [7, 9] -> ts3
> where ts1 < ts2 < ts3, we should store them internally as
>     [-inf, 4) -> ts1, [4] -> ts2, (4, 7) -> ts1, [7, 9] -> ts3
> This allows a single lookup to provide all deletion information, instead of (clustering key size) lookups that we have now, that don't support range tombstones.
> When serializing the internal representation to an sstable, we might try to minimize the number of ranges, but it's probably not worth it. [NYH: we shouldn't, since Cassandra also puts disjoint ranges in the ssable]
>
> There is the question of how to transfer mutations with such tombstones to an old node.  We could have code to convert from the old format to the new format, and refuse (fail) if the old format is unable to represent the tombstones.

**Comment by slivne** [comment]
we will need to update sstableloader once this is done to support uploading of such tombstones (if they have been created in the past with thrift)

**Comment by nyh** [comment]
http://www.datastax.com/2015/12/storage-engine-30 contains an interesting discussion on Cassandra 3.0's new sstable format, and among other things it states that in Cassandra 3.0, they added in addition to the general range tombstones, also the notion of deletion of rows and collections (like we currently have in Scylla); They claim (I don't know on what basis) that keeping the deleted rows instead of range tombstones is not only more efficient in the sstable, it's also more efficient for handling (I supposed, in query time). This seems to contradict @avikivity's observation above that keeping a list of disjoint range tombstones is more efficient.

**Comment by duarten** [comment]
I checked the new 3.0 format, which for the particular case of collections, is represented by ComplexColumnData.java. These are serialized to range tombstones when using the legacy format, but in the new format they're a "complex deletion", which has its own serialized representation (and doesn't include the deleted cells). I didn't dig too deep, but it seems a complex column can have a complex deletion and live cells with a bigger timestamp.

**Comment by duarten** [comment]
Only thing missing for this is to implement apply_reversibly for the range_tombstone_list, which is going to be more work than I anticipated: when applying a range_tomstone_list onto another, inserting a missing range might mean splitting or joining overlapping ranges, so it's much harder to keep track of what exactly needs to be done to revert the application. I guess I might try to just copy the target of apply() so I can replace the modified range_tombstone_list upon revert(); unoptimized but should work.
