### ISSUE TITLE
nodetool COMPACT can hurt Scylla if misused

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1156]
When user issues 'nodetool COMPACT', column_family::compact_all_sstables() is called to compact all sstables of a given column family. It doesn't go through compaction manager.
If the user issues N 'nodetool COMPACT' in a small interval, there will possibly be N fibers compacting all sstables of the same column family in parallel. That could definitely hurt the overall system performance. A possible fix is about allowing _only one_ column_family::compact_all_sstables() to proceed _per_ column family. For a second request, we should probably throw an exception or something. A long term fix is probably about making it go through compaction manager.

**Comment by nyh** [comment]
Please check what Cassandra does in case a second "notetool compact" is attempted in parallel. Does it print an error? Wait for the ongoing compaction to finish? Or what?

**Comment by raphaelsc** [comment]
@tzach, @slivne: Could you please add bug tag to this issue and assign it to me? I am really afraid of 'nodetool COMPACT' if user issues it more than once. Because it doesn't go through compaction manager, it may end up compacting sstables that are already being compacted. So system's performance would drop considerably!

**Comment by slivne** [comment]
could it also cause data being duplicated

Lets say the scylla is compacting A,B --> C

The user issues the nodetool COMPACT: A,B --> D

both compactions finish we have C,D ?

can this happen ?

**Comment by raphaelsc** [comment]
On Fri, Jun 3, 2016 at 12:16 AM, Shlomi Livne <notifications@github.com>
wrote:

> could it also cause data being duplicated
>
> Lets say the scylla is compacting A,B --> C
>
> The user issues the nodetool COMPACT: A,B --> D
>
> both compactions finish we have C,D ?
>
> can this happen ?
>

Correct! I edited my sentence afterwards and mentioned it :-) That's
something we probably want fixed in either 1.2 or 1.3, right? ATM,
user-initiated compaction may be very bad for system performance.


>
>
>
> On Fri, Jun 3, 2016 at 1:39 AM, Raphael Carvalho <notifications@github.com
> >
> wrote:
>
> > @tzach <https://github.com/tzach>, @slivne <https://github.com/slivne>:
> > Could you please add bug tag to this issue and assign it to me? I am
> really
> > afraid of 'nodetool COMPACT' if user issues it more than once. Because it
> > doesn't go through compaction manager, it may end up compacting sstables
> > that are already being compacted. So system's performance would drop
> > considerably!
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/scylladb/scylla/issues/1156#issuecomment-223443716>,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ADThCDCTckD29LUDtb5Wu3NcnSdqlH-Pks5qH1uYgaJpZM4H8pGP
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/scylladb/scylla/issues/1156#issuecomment-223481191>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABWAcym21LjgbhuuK8tWQ19xmdfBARO6ks5qH5yhgaJpZM4H8pGP>
> .
>



-- 
Raphael S. Carvalho

**Comment by tzach** [comment]
might be relevant: Add "Major" Compaction to LCS https://issues.apache.org/jira/browse/CASSANDRA-7272
