### ISSUE TITLE
CQL: "contains" restriction is not implemented

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1158]
Scylla version (or git commit hash): 0f5ca342b8a5242b1bbf4b77f47bdc32b52e812b

```
CREATE TABLE lmr_test_keyspace.foo (
    id int PRIMARY KEY,
    foo map<text, int>
);

select * from foo where foo contains 'kittens';
ServerError: <ErrorMessage code=0000 [Server error] message="virtual shared_ptr<cql3::restrictions::restriction> cql3::single_column_relation::new_contains_restriction(database&, schema_ptr, shared_ptr<cql3::variable_specifications>, bool) not implemented">
cqlsh:lmr_test_keyspace>
```

**Comment by duarten** [comment]
Doesn't this require secondary indexes?

**Comment by duarten** [comment]
To answer my own question, it requires SI for normal columns but not for clustering ones.

**Comment by duarten** [comment]
Although.. I tried it with C* 2.1.13 and:

cqlsh:ks> create table cf (p int, c frozen<set<text>>, primary key (p, c));
cqlsh:ks> select * from cf where p = 1 and c contains 'something';
InvalidRequest: code=2200 [Invalid query] message="Cannot restrict column "c" by a CONTAINS relation without a secondary index"

This happens regardless of collection type (and matches what I saw in the code). Maybe I'm missing something?
