### ISSUE TITLE
swagger ui does not contain system (logger) info

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1160]

**Comment by tzach** [comment]
@slivne do you want the Swagger to include metrics from collectd?

**Comment by slivne** [comment]
I want to be able to set the logger level

**Comment by amnonh** [comment]
@slivne Are you sure?
The logger works both via the API and the nodetool.
Maybe there's something funny with the swagger UI, the logger is placed under system.

What version are you using?

**Comment by avikivity** [comment]
1.0.0.

It works, but there it is not visible under ui/.
