### ISSUE TITLE
Provide packages for SLES 11

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1162]

**Comment by avikivity** [comment]
On 04/04/2016 09:13 AM, Tzach Livyatan wrote:
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/scylladb/scylla/issues/1162>
>

Better to target SLES 12, which has systemd.

**Comment by syuu1228** [comment]
I guess we can share dist/redhat/ with SLES, by using dist tag on our .spec file.
https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto#Detect_a_distribution_flavor_for_special_code

**Comment by tzach** [comment]
> Better to target SLES 12, which has systemd.

Open an issue for it as well, lets see if it get any traction
#1163

**Comment by glommer** [comment]
It there still a justification to keep this bug open?
This is extremely unlikely to happen and not even worth it.

**Comment by avikivity** [comment]
Our 3.1 packages are likely to work on SLES 12.
