### ISSUE TITLE
[AMI 1.0 GA i2.4xlarge] Sometimes a node may not rejoin the cluster if its AWS instance is stopped/started

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#1169]
## Installation details
Scylla version (or git commit hash): [AMI 1.0 GA]
Cluster size: 6 i2.4xlarge nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

## Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker): AWS

This is actually the first time I have seen this - I've executed this particular nemesis other times and this didn't happen. During longevity testing, after stopping/starting one of the cluster nodes, scylla server will fail to start, scylla log error follows:

    Apr 07 18:02:34 ip-172-30-0-196.ec2.internal scylla[5041]: Exiting on unhandled exception of type 'std::runtime_error': A node with address 172.30.0.196 already exists, cancelling join. Use cassandra.replace_address if you want to replace this node.

I'm not sure what triggered this particular error.

**Comment by tzach** [comment]
Stop should not be supported #1229
