### ISSUE TITLE
New API command for triggering regular compaction

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1172]
Currently, our compaction API bypasses compaction manager and selects all sstables of a column family for compaction. So it would be interesting to provide an API that triggers regular compaction.

**Comment by dorlaor** [comment]
Let's try to push it to 1.1 since it can be very handy tool

**Comment by avikivity** [comment]
Not sure what it means, standard compaction is auto-triggered based on sstable counts. When would a manual trigger accomplish something, when the auto trigger would not?

**Comment by raphaelsc** [comment]
@avikivity I can only think of one case: After scylla boots and before it has any load. That's because we only triggers compaction after a memtable flush. If we implement this behavior ' standard compaction is auto-triggered based on sstable counts.', then it's indeed possible that this request doesn't make sense. I think that we could also trigger compaction whenever a new sstable is added to column family.

**Comment by avikivity** [comment]
Yes, we should trigger compaction on boot too.

**Comment by tzach** [comment]
@dorlaor why is it urgent to 1.0?

**Comment by dorlaor** [comment]
@tzach do you mean for 1.1?
It should be very good for debug and trace and should be relatively
trivial to implement

**Comment by raphaelsc** [comment]
@dorlaor: As Avi said, there should always be a regular compaction scheduled for a column family that needs it. Maybe, this command could be about prioritizing the schedule or something, like: Try to run a regular compaction for a given cf now!

**Comment by dorlaor** [comment]
On Mon, Apr 18, 2016 at 9:13 PM, Raphael Carvalho <notifications@github.com>
wrote:

> @dorlaor <https://github.com/dorlaor>: As Avi said, there should always
> be a regular compaction scheduled for a column family that needs it. Maybe,
> this command could be about prioritizing the schedule or something, like:
> Try to run a regular compaction for a given cf now!
>
Raphael, you're welcomed to offer any other solution you'll find as a
better alternative

**Comment by raphaelsc** [comment]
@dorlaor I am thinking about fixing what Avi noticed first, which is: We should trigger compaction on boot. BTW, I am working on compaction manager to allow compaction on each level of a column family, so there will always be a compaction running, if needed, for a column family. Because of that, this command may not be needed.

**Comment by slivne** [comment]
If we are triggering on boot and running compaction till we have nothing else todo - I do not see why we need the api - is there a need for it if we do this changes ?

**Comment by slivne** [comment]
@dorlaor / @avikivity  if there is still a need please reopen - as explained above I don't think this is needed anymore

**Comment by dorlaor** [comment]
I'm ok w/ it
