### ISSUE TITLE
scyllatop.py: cuts the source Node name in the metrics and ignores metrics coming from different Nodes

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#1173]
## Installation details
Scylla version (or git commit hash): HEAD 9b9827843649d4c2a585aee524926a800d962c42
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora23

## Description
scyllatop.py cuts the source Node name in the metrics representation. This makes it impossible to filter the metrics coming from a specific Node.
For example if we have a Node with a name `node1` it's commitlog flush events counter has a name `node1/commitlog-0/total_operations-flush` but scyllatop would only use the suffix of the metric's name for the output and would use only one of the counters if there are more than one Node that reports it:

`commitlog-0/total_operations-flush`

In our example if there are other Nodes that report `commitlog-0/total_operations-flush` metric (e.g. node2, node3, etc.) their counters would be ignored and there is no way to see them using scyllatop.py.

**Comment by haarcuba** [comment]
submitted a patch to the dev mailing list. Please review, @vladzcloudius
