### ISSUE TITLE
long query does not stop even after client's timeout/disconnect

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#1175]
## Installation details

Scylla version (or git commit hash):
9b9827843649d4c2a585aee524926a800d962c42
Cluster size:
3
- Populate cluster with 1000000 keys.
- Connect with cqlsh and run "select count(*) from table;"

if tracing is enabled it can be seen that query continue to run even after cqlsh reports timeout. Even closing cql connection by exiting cqlsh does not abort the query.

**Comment by tzach** [comment]
If there is a "bad" query, Scylla should handle it correctly (or drop it), even if the client did not disconnect.
If Scylla handles all queries correctly, keeping a few extra ones should not matter.

**Comment by vladzcloudius** [comment]
@slivne @eliransin FYI

**Comment by bhalevy** [comment]
f8e0517 causes over 20 failures in dtest and I'm afraid it might wreck havoc also in SCT, so I suggest we revert it until we're ready for it or find a better solution.

I see that DSE have a long aggregated_request_timeout_in_ms (defaults to 120 seconds) but I'm puzzled by their lousy documentation:
https://docs.datastax.com/en/dse/6.0/dse-dev/datastax_enterprise/config/configCassandra_yaml.html
FWIW the document says: "This timeout does not apply to aggregated queries such as SELECT, COUNT(*), MIN(x), and so on."
but if it doesn't what timeout does?
also, without applying to these, it's exactly like range_request_timeout_in_ms. Verbatim.

Quickly browsing the Java code, it looks like these timeout are at the rpc level, not at the aggregate level.
For example, see https://github.com/apache/cassandra/blob/c26269bc54115958cb2d32c13cf99131ef118592/src/java/org/apache/cassandra/service/reads/ReadCallback.java#L99-L101

`command.getTimeout()` will be one of e.g. `read_request_timeout_in_ms` or `range_request_timeout_in_ms`

Those end up in https://github.com/apache/cassandra/blob/c26269bc54115958cb2d32c13cf99131ef118592/src/java/org/apache/cassandra/config/DatabaseDescriptor.java#L1592-L1595
and friends

/cc @tgrabiec

**Comment by avikivity** [comment]
Can we adjust dtest to start scylla with higher timeouts? dtest really has no right to expect that an aggregate query will not honor read_request_timeout_ms.

Cassandra 4.0's NEWS.txt says:

```
    - Request timeouts in cassandra.yaml (read_request_timeout_in_ms, etc) now apply to the
      "full" request time on the coordinator.  Previously, they only covered the time from
      when the coordinator sent a message to a replica until the time that the replica
      responded.  Additionally, the previous behavior was to reset the timeout when performing
      a read repair, making a second read to fix a short read, and when subranges were read
      as part of a range scan or secondary index query.  In 3.10 and higher, the timeout
      is no longer reset for these "subqueries".  The entire request must complete within
      the specified timeout.  As a consequence, your timeouts may need to be adjusted
      to account for this.  See CASSANDRA-12256 for more details.
```

**Comment by bhalevy** [comment]
> Can we adjust dtest to start scylla with higher timeouts? dtest really has no right to expect that an aggregate query will not honor read_request_timeout_ms.
> 
> Cassandra 4.0's NEWS.txt says:
> 
> ```
>     - Request timeouts in cassandra.yaml (read_request_timeout_in_ms, etc) now apply to the
>       "full" request time on the coordinator.  Previously, they only covered the time from
>       when the coordinator sent a message to a replica until the time that the replica
>       responded.  Additionally, the previous behavior was to reset the timeout when performing
>       a read repair, making a second read to fix a short read, and when subranges were read
>       as part of a range scan or secondary index query.  In 3.10 and higher, the timeout
>       is no longer reset for these "subqueries".  The entire request must complete within
>       the specified timeout.  As a consequence, your timeouts may need to be adjusted
>       to account for this.  See CASSANDRA-12256 for more details.
> ```

It's trivial to increase the default timeouts in dtest.
I'm more worried about real life applications.
@roydahan how are the client timeouts configured in SCT?
@haaawk what are the default timeouts that the Java dtiver uses?

**Comment by avikivity** [comment]
We can add a tunable `honor_read_timeouts_in_aggregation_queries`. But I think that aggregation queries are rare enough that we can require the users to increase server timeouts in case they use them.

**Comment by roydahan** [comment]
> > Can we adjust dtest to start scylla with higher timeouts? dtest really has no right to expect that an aggregate query will not honor read_request_timeout_ms.
> > Cassandra 4.0's NEWS.txt says:
> > ```
> >     - Request timeouts in cassandra.yaml (read_request_timeout_in_ms, etc) now apply to the
> >       "full" request time on the coordinator.  Previously, they only covered the time from
> >       when the coordinator sent a message to a replica until the time that the replica
> >       responded.  Additionally, the previous behavior was to reset the timeout when performing
> >       a read repair, making a second read to fix a short read, and when subranges were read
> >       as part of a range scan or secondary index query.  In 3.10 and higher, the timeout
> >       is no longer reset for these "subqueries".  The entire request must complete within
> >       the specified timeout.  As a consequence, your timeouts may need to be adjusted
> >       to account for this.  See CASSANDRA-12256 for more details.
> > ```
> 
> It's trivial to increase the default timeouts in dtest.
> I'm more worried about real life applications.
> @roydahan how are the client timeouts configured in SCT?
@juliayakovlev can you please check and comment back?
> @haaawk what are the default timeouts that the Java dtiver uses?

**Comment by bhalevy** [comment]
https://github.com/scylladb/scylla-dtest/pull/1790 adjusts `range_request_timeout_in_ms` from the test side before issuing long-running select queries.

**Comment by juliayakovlev** [comment]
> > > Can we adjust dtest to start scylla with higher timeouts? dtest really has no right to expect that an aggregate query will not honor read_request_timeout_ms.
> > > Cassandra 4.0's NEWS.txt says:
> > > ```
> > >     - Request timeouts in cassandra.yaml (read_request_timeout_in_ms, etc) now apply to the
> > >       "full" request time on the coordinator.  Previously, they only covered the time from
> > >       when the coordinator sent a message to a replica until the time that the replica
> > >       responded.  Additionally, the previous behavior was to reset the timeout when performing
> > >       a read repair, making a second read to fix a short read, and when subranges were read
> > >       as part of a range scan or secondary index query.  In 3.10 and higher, the timeout
> > >       is no longer reset for these "subqueries".  The entire request must complete within
> > >       the specified timeout.  As a consequence, your timeouts may need to be adjusted
> > >       to account for this.  See CASSANDRA-12256 for more details.
> > > ```
> > 
> > 
> > It's trivial to increase the default timeouts in dtest.
> > I'm more worried about real life applications.
> > @roydahan how are the client timeouts configured in SCT?
> > @juliayakovlev can you please check and reply here?

@roydahan I will check

> > @haaawk what are the default timeouts that the Java dtiver uses?

**Comment by psarna** [comment]
> > > Can we adjust dtest to start scylla with higher timeouts? dtest really has no right to expect that an aggregate query will not honor read_request_timeout_ms.
> > > Cassandra 4.0's NEWS.txt says:
> > > ```
> > >     - Request timeouts in cassandra.yaml (read_request_timeout_in_ms, etc) now apply to the
> > >       "full" request time on the coordinator.  Previously, they only covered the time from
> > >       when the coordinator sent a message to a replica until the time that the replica
> > >       responded.  Additionally, the previous behavior was to reset the timeout when performing
> > >       a read repair, making a second read to fix a short read, and when subranges were read
> > >       as part of a range scan or secondary index query.  In 3.10 and higher, the timeout
> > >       is no longer reset for these "subqueries".  The entire request must complete within
> > >       the specified timeout.  As a consequence, your timeouts may need to be adjusted
> > >       to account for this.  See CASSANDRA-12256 for more details.
> > > ```
> > 
> > 
> > It's trivial to increase the default timeouts in dtest.
> > I'm more worried about real life applications.
> > @roydahan how are the client timeouts configured in SCT?
> > @juliayakovlev can you please check and reply here?
> > @haaawk what are the default timeouts that the Java dtiver uses?

This seems to be the default socket configuration for the Java driver:
```java
public class SocketOptions {

  /**
   * The default connection timeout in milliseconds if none is set explicitly using {@link
   * #setConnectTimeoutMillis}.
   *
   * <p>That default is of 5 seconds.
   */
  public static final int DEFAULT_CONNECT_TIMEOUT_MILLIS = 5000;

  /**
   * The default read timeout in milliseconds if none is set explicitly using {@link
   * #setReadTimeoutMillis}.
   *
   * <p>That default is of 12 seconds so as to be slightly bigger that the default Cassandra
   * timeout.
   *
   * @see #getReadTimeoutMillis for more details on this timeout.
   */
  public static final int DEFAULT_READ_TIMEOUT_MILLIS = 12000;
```
, so it will time out after receiving nothing from the socket for more than 12s.

**Comment by avikivity** [comment]
Was there any fallout from this with dtest?

**Comment by roydahan** [comment]
> Was there any fallout from this with dtest?

What do you mean?
If tests started failing due to this change?
