### ISSUE TITLE
pre-filter sstables during query

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1176]
Right now for a single row query we create a reader for each sstable, run them all, and merge the results.

If most sstables return an empty mutation (due to: filter, summary, or pkey range), this was wasted work.

**Comment by nyh** [comment]
Probably a duplicate of issue #1056 ?

**Comment by nyh** [comment]
(although not an exact duplicate, because we can also avoid the merging of those empty sstable readers)
