### ISSUE TITLE
Incorrect leveled sstable size when compression is enabled

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1177]
Scylla version (or git commit hash): 1.0.0

I see leveled sstables that are 48MB in size, instead of 160MB.  Probably we are measuring the uncompressed size instead of the compressed size.

**Comment by nyh** [comment]
Looking at the compaction code, and in sstable::do_write_components(), it indeed uses sstable::data_size() which checks the amount of data (uncompressed), and uses file_write::offset() which is the offset into the uncompressed data.

We can change it to measure the compressed size, and I guess it makes more sense that if you set a "160MB" limit, you'll see 160MB files. But the current approach also makes sense...  it ensures that on different settings on compression, we still have the same number of sstables - they are just each smaller if compressed.

**Comment by avikivity** [comment]
Origin measures the compressed size, so so should we.
