### ISSUE TITLE
Partition range queries involve disk IO even though data is fully cached

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1179]
Sstable indexes are scanned for keys to see if sstables contain keys which are not in cache. Could be fixed by storing partition contiguity information in cache.

**Comment by haaawk** [comment]
This should be fixed by https://github.com/scylladb/scylla/commit/136b8148d250b0dba566a88fb07be5e3510b4e4c

**Comment by slivne** [comment]
@piotr - did the series with continuous flag address this ?

**Comment by haaawk** [comment]
Yes

**Comment by penberg** [comment]
@haaawk @slivne Please add pointers to the commit(s) that fixed the issue here for future reference.

**Comment by haaawk** [comment]
It was fixed by https://github.com/scylladb/scylla/commit/9b011bff18c079a625f3c3e8c403f05831181718
