### ISSUE TITLE
More efficient sstable lookup when using leveled compaction strategy

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#1185]
With leveled compaction strategy, we can have thousands of small sstables. When searching for a specific partition key on a cache miss, we know we don't need to search in all sstables, because in each level the key ranges of different sstables are disjoint, so we know that at most one sstable from each level may contain a given partition key.

If we have 1000 sstables, it's very important not to read from them all looking for a single partition. So the existing code starts with checking the (in-memory) bloom filters. This eliminates most, but _not_ all, of the sstables - in one test we were left with 20 false positives. Commit 715794cce6e090bbd1e145b8731a1ac27bbeef04 then added code to check each sstable's key range (also in-memory) which will eliminate all remaining candidates except one.

While the existing code will indeed read from at most a single sstable (per level), it does quite a bit of work to reach there - in the above example querying 1,000 bloom filters and comparing our key to 20 key ranges. Instead, we could have kept some data structure (interval map, etc.) where a single lookup of a key (per level) could find the single candidate sstable. For N sstables, this lookup will probably be O(ln N) (I can't think of an O(1) algorithm...), better than the O(N) bloom filter lookups we have now, and probably with much lower constants as well.

This lookup will only be relevant to leveled compaction. In the mailing list, @avikivity suggested we could add a method compaction_strategy::select_sstables(decorated_key). @raphaelsc  suggested we can make the new map a feature of sstable "levels" and not a specific compaction strategy: Require that any compaction strategy which happens to use the "level" field must comply with the requirement that all sstables in the same level have disjoint key ranges.

**Comment by benoit-canet** [comment]
@nyh: bloom filters could be interleaved for faster scanning but this would
be more complicated to manipulate.

**Comment by nyh** [comment]
On Wed, Apr 13, 2016 at 5:09 PM, Benoît Canet <notifications@github.com>
wrote:

> @nyh: bloom filters could be interleaved for faster scanning but this would
> be more complicated to manipulate.
>

What do you mean Bloom filters could be "interleaved"?

**Comment by haaawk** [comment]
Why should we restrict usage of interval tree just to leveled compaction? Wouldn't it also work for other compaction strategies? I know that leveled compaction has this nice guarantee that a key will be in at most <number of levels> + <number of sstables in level 0> sstables but in practice I wouldn't expect a key to be in every sstable even when using other compaction strategies.

**Comment by avikivity** [comment]
In other compaction strategies the key range spanned by the sstable would be the entire node's or shard's range.  It's true that a particular key will be in just a few sstables, but only LCS groups keys by their token.

**Comment by haaawk** [comment]
That was what I was missing. Thanks Avi.

**Comment by svdasar** [comment]
First of all, the bloom filter search is very fast as it is done in memory. For example, for a large table that has billion rows/node, on a 12 core machine with bloom filter false positive ratio of 0.01, we see  < 5 micro seconds per each sstable.

Second, based on cql trace, I suspect that bloom filter search is done on every sstable for the level compaction.  Perhaps it is stopping the search after it finds the required cells of the partition from the top levels (level 0->1->2->3...) as level compaction guarantees latest values in the top levels.  It cannot do this for STCS. On the other hand for STCS, it is dealing with less than 20 sstables for a large node.

**Comment by nyh** [comment]
@svdasar (name? :-)), if one bloom filter search takes 5 microsecond (which sounds pretty high, actually), then a thousand of them take a whopping 5 milliseconds - and this is what this issue is trying to lower.

Of course, this issue is only relevant when we have a very large number of sstables, and the only compaction strategy that currently makes that possible is leveled compaction strategy: E.g., if you have 160 GB of data, you'll have about 1000 sstables of 160 MB each.

Finally, I don't think your comments about searching only in top level is correct: I don't think LCS makes any such guarantee. It often happens - because overwritten data causes a "ripple" of small compactions which soon causes the old and new data to be compacted together - but there is nothing that guarantees when this will actually happens. The Cassandra documentation suggests that in "90%" of the single partition reads will only need to read one sstable. But there is no real explanation for this "90%" figure, and there's also the other 10%.
