### ISSUE TITLE
column_family sstable statistics incorrect with shared sstables

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1186]
Scylla version (or git commit hash): 1.0.0

If an sstable is shared across multiple shards, then it is counted multiple times in the disk usage statistics.

**Comment by tzach** [comment]
@avikivity what are disk usage statistics?
Existing collectd counters?

**Comment by tzach** [comment]
@avikivity ping

**Comment by raphaelsc** [comment]
@slivne: @duarten  fixed this, I don't remember the commit hash though

**Comment by glommer** [comment]
@slivne @avikivity Raphael claims this is fixed. Please close.

**Comment by duarten** [comment]
Fixed in d53f96e0dac9a39bb954d14024d89b6520aaa5e6.
