### ISSUE TITLE
scylla_setup should be in the path

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1187]
## Installation details
Scylla version (or git commit hash): 1.0.1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

The first action after installing Scylla, should be running `scylla_setup`
To make it easier, scylla_setup should be in the path
currenty at `/usr/lib/scylla/scylla_setup`

**Comment by slivne** [comment]
@syuu1228  I think we added links to /usr/sbin - so  in master this is already fixed - no ?

**Comment by syuu1228** [comment]
@slivne @tzach /usr/sbin symlink does not merged to branch-1.0.
To enable it, following commit are needed:
https://github.com/scylladb/scylla/commit/58fb7000b13166d0b8fce30fe52bfbf268cb4e8a
https://github.com/scylladb/scylla/commit/cad5edc53b23e0388f4d696506b728de8753ccfa

**Comment by slivne** [comment]
It will not be in 1.0  shpuld be in 1.1

**Comment by syuu1228** [comment]
@slivne @tzach when we create branch-1.1 from master, it will be automatically included commits I mentioned above.
So this issue can be close now.
