### ISSUE TITLE
scylla_setup - allow skip at every phase

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1188]
## Installation details
Scylla version (or git commit hash): 1.0.1

In many cases, users will rerun scylla_setup.
If they do, we should allow them to skip steps they already did.
For example, I want to leave NTP setting as is:
```
Do you want to setup NTP?
yes/no: 
``` 

can be
```
yes/no/skip: 
```

**Comment by slivne** [comment]
what does "no" vs "skip" mean ?

**Comment by tzach** [comment]
No might mean to disable NTP, skip to keep it as is.
If there is no difference, no need to add skip, but better explain these options.

**Comment by slivne** [comment]
no in my view means don't do anything - @tzach what would make this clearer 
"Do you want to setup NTP?"

would that make it better

"Do you want to update NTP configuration?"

**Comment by tzach** [comment]
Yes, "Do you want to update NTP configuration?" is much clearer

**Comment by syuu1228** [comment]
@tzach use --no-XXX-setup argument.
Please close this issue now.

**Comment by syuu1228** [comment]
Ah okay, so we just need to update interactive prompt message.

**Comment by benoit-canet** [comment]
@tzach How do you rephrase "Do you want to disable SELinux?": the result risk to look weird.

The user having plenty of idle processing power at hand why not simply instruct him at the begining of the script that he can skip
any of the action by simply answering "no" ?

A simple message like:

    Any of the following action can be skipped by answering 'no'. In doubt answer 'no'.

@tzach What do you think of this ?

**Comment by tzach** [comment]
@benoit-canet , I'm good with general instruction at the top, maybe more like:
```
Skip any of the following steps by answering 'no'
```

Not sure about the "In doubt" part. The default should be yes, not no

**Comment by benoit-canet** [comment]
@tzach on the list
