### ISSUE TITLE
Setup RAID return unclear error message

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1189]
## Installation details
Scylla version (or git commit hash): 1.0.1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 14.04, on EC2 i2.xlarge

When using scylla_setup, on i2.xlarge server, I try to set RAID0 on xvda and xvdb.
This can not work, since xvda1 hold the OS.
It would be nice if the script can return a better error message

```
sudo /usr/lib/scylla/scylla_setup
...

Do you want to setup RAID?
yes/no: yes
Please select disks from following list: 
xvda xvdb
type 'done' to finish selection. selected: 
> xvda
xvda xvdb
type 'done' to finish selection. selected: /dev/xvda
> xvdb
xvda xvdb
type 'done' to finish selection. selected: /dev/xvda,/dev/xvdb
> done

Creating RAID0 for scylla using 2 disk(s): /dev/xvda /dev/xvdb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
xfsprogs is already the newest version.
mdadm is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 67 not upgraded.
mdadm: super1.x cannot open /dev/xvda: Device or resource busy
mdadm: ddf: Cannot use /dev/xvda: Device or resource busy
mdadm: Cannot use /dev/xvda: It is busy
mdadm: cannot open /dev/xvda: Device or resource busy
```

```
$ sudo lsblk -o NAME,FSTYPE,SIZE,MOUNTPOINT,LABEL
NAME    FSTYPE   SIZE MOUNTPOINT LABEL
xvda               8G            
└─xvda1 ext4       8G /          cloudimg-rootfs
xvdb           745.2G            
```

**Comment by syuu1228** [comment]
Maybe we can skip showing busy devices on the list, by looking on mountpoint.

**Comment by tzach** [comment]
@syuu1228 make sense.

**Comment by benoit-canet** [comment]
I will implement @syuu1228 's idea. It cleaner to treat the issue upstream.

**Comment by tzach** [comment]
@benoit-canet any updates?

**Comment by benoit-canet** [comment]
@tzach patch on the list since april 18

**Comment by tzach** [comment]
@benoit-canet any progress?

**Comment by benoit-canet** [comment]
I had iterated on it but forgot to reposted it. It's done now.

**Comment by benoit-canet** [comment]
hmm I broke something

**Comment by benoit-canet** [comment]
@avikivity my patch is broken please revert.

**Comment by penberg** [comment]
We did not revert the commit because @benoit-canet fixed the issue in https://github.com/scylladb/scylla/commit/c133748a2428123f52322fc35aa15ad253f65552
