### ISSUE TITLE
scylla_io_setup writes only max-io-requests, not num-io-queues

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1190]
## Installation details
Scylla version (or git commit hash): 1.0.1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI):Ubuntu on i2.xlarge

When running sudo /usr/lib/scylla/scylla_setup, which call scylla-io-setup

```
Do you want to setup IO configuration?
yes/no: yes
Generating evaluation file sized 10GB...10GB written in 22 seconds
Refining search for maximum. So far, 64260 IOPS
Maximum throughput: 64260 IOPS
Recommended --max-io-requests: 33
Written the above values to /etc/scylla.d/io.conf
Setting parameters on /etc/default/scylla-server
ubuntu@ip-10-236-29-92:~$ cat /etc/scylla.d/io.conf
SEASTAR_IO="--max-io-requests=33"
```

Only max-io-requests is written, not  num-io-queues.
@glommer bug or feature?

**Comment by syuu1228** [comment]
I got same result on Windows VM (Hyper-V) with Ubuntu 14.10.

**Comment by tzach** [comment]
@glommer bug or feature?

**Comment by glommer** [comment]
This is not a bug.

**Comment by tzach** [comment]
Thanks @glommer . 
Can you explain the logic? is scylla using 1 as default?

**Comment by glommer** [comment]
On Thu, Apr 14, 2016 at 2:13 PM, Tzach Livyatan <notifications@github.com>
wrote:

> Thanks @glommer <https://github.com/glommer> .
> Can you explain the logic? is scylla using 1 as default?
>

nr_cpus, not 1.

if your max-nr-requests is enough to have at least 4 requests per shard,
then we don't touch
num-io-queues

**Comment by tzach** [comment]
Thanks @glommer
