### ISSUE TITLE
scylla_setup, does not update SET_NIC in /etc/sysconfig/scylla-server to yes

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1192]
## Installation details
Scylla version (or git commit hash): 1.0.1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.2 on i2.xlarge

Looking at /etc/sysconfig/scylla-server after running scylla_setup, I see `SET_NIC=no` :

```
# setup NIC's interrupts, RPS, XPS (posix)
SET_NIC=no
```

When using Scylla AMI I see
```
# setup NIC's interrupts, RPS, XPS (posix)
SET_NIC=yes
```

Bug?

This is what I run:

```
$ sudo /usr/lib/scylla/scylla_setup

...
Please select NIC from following list: 
eth0  lo
> eth0
Do you want to setup IO configuration?
yes/no: yes
Generating evaluation file sized 10GB...10GB written in 11 seconds
Refining search for maximum. So far, 128380 IOPS
Maximum throughput: 128380 IOPS
Recommended --max-io-requests: 66
Written the above values to /etc/scylla.d/io.conf
Setting parameters on /etc/sysconfig/scylla-server
```

**Comment by syuu1228** [comment]
As I described on https://github.com/scylladb/scylla/issues/1193, this not a bug.
Please provide information to improve the implementation.

**Comment by tzach** [comment]
Thanks @syuu1228 
What is the affect of setting / not setting the NIC?
If we can not decide for the user, should we make it part of the set up interactive question?

**Comment by tzach** [comment]
If the user choose interface (e.g. eth0 or bond0) SET_NIC should be set to yes
@vladzcloudius has entrenched posix_net_conf  to support setting MQ/SQ base on interrupts.

**Comment by syuu1228** [comment]
@tzach Again, I need to know more information to improve the script.
https://github.com/scylladb/scylla/issues/1193#issuecomment-209996744

Do we really should enable SET_NIC even nr_cpus <8 ?
Should we always do --cpuset and --smp to exclude cpu0, or it's only when machine has enough cpus?
etc.

**Comment by slivne** [comment]
For the AMI the conditions should stay as is - no change

For non AMI cases we should SET_NIC if the user decided to set the NIC (the
script is updated to know on its own to set mq/sq based on the amount of
queues) - we should not change the cpuset and smp for non AMI cases.

**Comment by tzach** [comment]
@syuu1228 any updates?
