### ISSUE TITLE
scylla_setup does not set cpuset and smp options in /etc/sysconfig/scylla-server

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1193]
## Installation details
Scylla version (or git commit hash): 1.0.1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.2 on on EC2 i2.xlarge

after running scylla_setup, I have the following on `/etc/sysconfig/scylla-server`
```
# scylla arguments (for posix mode)
SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix"
```

with Scylla AMI
```
# scylla arguments (for posix mode)
SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --cpuset 1-7 
 --smp 7"
```

Note *cpuset* and *smp* options was not set by scylla_setup

**Comment by syuu1228** [comment]
Currently we only enables cpuset/smp options and SET_NIC on official AMI, so it's not bug, feature limitation of current implementation.
To implement it, we need following information:
 - When should we enable cpuset/smp options with SET_NIC. All environments when cpus >= 8, or only on AWS, etc.
 - cpuset configuration should always exclude cpu0, or it depends on environment
 - other conditions (bonding etc?)
 - multiqueue
 - how to cooperate with updated posix_net_conf.sh

**Comment by slivne** [comment]
@tzach scylla_Setup does support setting the NIC now - yet the ``--smp, --cpuset`` are not set - the question is what do you want us todo here

the decision to use one core for networking is something that we can do on the AMI - not sure we can take the same decision if its not the AMI
