### ISSUE TITLE
Scylla can freeze if many column families are written to simultaneously

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#1195]
## Installation details
Scylla version (or git commit hash): 1.0.1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): any

Although I haven't (yet) reproduced this yet, it can be easily seen that if a database has many column families that are being written to at the same time, it can potentially freeze.

This happens because the throttling code does not generate any I/O, and only wait for an external process to do so. This works well if a single CF is being written to, because memtable_space_total is never bigger than a single memtable. So, if a memtable is using enough space to cause throttling, it is surely using enough space to have caused a flush.

However, that is not true if more than one CF is under load. It's easy to see that imagining an extreme scenario, where memtable_space_total == max_memtable_size:

CF1 has a memtable with memtable_space_total / 2
CF2 has a memtable with memtable_space_total / 2 + epsilon

In this case, we'll throttle. But because no memtable is itself over the limit, we'll never release any memory.

**Comment by tzach** [comment]
@glommer how many CF would you need to encounter this issue?

**Comment by glommer** [comment]
Need : 2.

But the more you have, the more likely.

And it doesn't matter how many CF you have, but how many CF are being
written to at the same time.

**Comment by tzach** [comment]
@glommer looks like its a likely scenario
we should add a test to capture this

**Comment by glommer** [comment]
It is not that likely under writes because throttling itself is not that
likely.

Streaming makes it a bit more likely.

I intend to fix soon

**Comment by tgrabiec** [comment]
If more than `1/cleanup_threshold` (by default 1/0.11 ~= 9) memtables are written to, deadlock is very likely up to guaranteed because, assuming they accumulate writes evenly, no memtable will cross the flush threshold before we hit the limit of dirty memory. They don't have to be written to at the same time, but may just have accumulated unflushed writes at the same time.

**Comment by glommer** [comment]
How to easily reproduce this bug:

Start scylla with

```
--smp 1 --memtable-cleanup-threshold=0.55 --memtable-total-space-in-mb=100
```
This will set the maximum size of a all memtables in the database to 100MB. Also, each memtable individually will be 55MB.

Then run two separate stress commands:

```
cassandra-stress write duration=10m -rate threads=1 -node 127.0.0.1 -schema keyspace="ks1"
cassandra-stress write duration=10m -rate threads=1 -node 127.0.0.1 -schema keyspace="ks2"
```
Assuming the two clients write at the same speed, each CF will be at 50MB more or less at the same time. They will then start throttling, without any of them having enough memory to trigger a flush.

This is 100 % reproducible to me.

**Comment by dorlaor** [comment]
Cheers Glauber!
