### ISSUE TITLE
Duplicate key in truncated_at coulumn in system.local table prevents c# cassandra driver working.

### ISSUE THREAD

**Issue by davebown** [scylladb/scylla#1196]
## Installation details
Scylla version (or git commit hash): 1.0.0
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

When establishing a session with Scylla/Cassandra the datastax c# cassandra driver executes the query SELECT * FROM system.local WHERE key='local'.

It appears that one of the coulmns in the result set truncated_at can contain a duplicate key in the raw results streamed back from Scylla. In my case there were two instances of a key with the value dc545090-f8f4-11e5-94f1-000000000000. 

Booting up a scylla with a clear data directory and connecting with the c# driver works and creating a workspace works fine but after dropping the key space a duplicate value appears. This causes the c# driver to fall over because it stores the result of the map column in a Dictionary which cannot have duplicate key values so throws an exception.

**Comment by benoit-canet** [comment]
@davebown Do you have a C#/Mono reproducer test for this ?

If you answer fast I will take yours if not I will create one.

**Comment by benoit-canet** [comment]
@davebown being more pythonic I tried to write a python reproducer:


from cassandra.cluster import Cluster

    cluster = Cluster()
    session = cluster.connect()
    
    session.execute("""create keyspace ks with replication = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };""")
    
    session.execute("""CREATE TABLE ks.users ( user_name varchar PRIMARY KEY, password varchar, );""")
    
    session.execute("""INSERT INTO ks.users (user_name, password) VALUES('frodo', 'Frodo');""")
    
    res = session.execute("""SELECT * FROM system.local WHERE key='local'""")
    for i in res:
        print i

    session.execute("""DROP KEYSPACE ks;""")
    
    res = session.execute("""SELECT * FROM system.local WHERE key='local'""")
    for i in res:
        print i

It's gives the following comparison in attachement:
[result.txt](https://github.com/scylladb/scylla/files/224148/result.txt)

So far nothing no double entry in it.

@davebown Does my code look similar enough to yours ?

**Comment by davebown** [comment]
I will try and provide you a c# example that does this.

It maybe the case that the python driver handles the problem.

It will take me a day or so as I'm tied up for a bit.

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Mon, Apr 18, 2016 at 9:02 AM -0700, "Benoît Canet" <notifications@github.com<mailto:notifications@github.com>> wrote:


@davebown<https://github.com/davebown> being more pythonic I tried to write a python reproducer:

from cassandra.cluster import Cluster

cluster = Cluster()
session = cluster.connect()

session.execute("""create keyspace ks with replication = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };""")

session.execute("""CREATE TABLE ks.users ( user_name varchar PRIMARY KEY, password varchar, );""")

session.execute("""INSERT INTO ks.users (user_name, password) VALUES('frodo', 'Frodo');""")

res = session.execute("""SELECT * FROM system.local WHERE key='local'""")
for i in res:
    print i

session.execute("""DROP KEYSPACE ks;""")

res = session.execute("""SELECT * FROM system.local WHERE key='local'""")
for i in res:
    print i


It's gives the following comparison in attachement:
result.txt<https://github.com/scylladb/scylla/files/224148/result.txt>

So far nothing no double entry in it.

@davebown<https://github.com/davebown> Does my code look similar enough to yours ?

-

**Comment by benoit-canet** [comment]
Thanks

**Comment by tzach** [comment]
@davebown did you had time to look into it? thanks

**Comment by benoit-canet** [comment]
@davebown ping ? We are still willing to help you solve this issue but need a c# reproducer since it's not our bread and butter.

**Comment by davebown** [comment]
I understand that, I will sort, should have some spare time next week. I have just been travelling on business and haven't found the time.
_____________________________

**Comment by benoit-canet** [comment]
@slivne : what do we do of this ? The user seems to have disapeared in the wild.

**Comment by davebown** [comment]
Hi, I'm really sorry the project we were considering using Scylla for has been cancelled and I'm now working on other things so I'm not likely to be able to find the time or resources (the vms have been deleted) to sort this. Really sorry, obviously I would think there are other .NET houses out there that would like to use Scylla and it looks to be a very promising technology.

**Comment by benoit-canet** [comment]
Hi Dave,

Don't worry it happen.

Thanks for keeping us updated.

Best regards

Benoît

**Comment by josephblodgett** [comment]
Hi @benoit-canet, 

I hit this issue as well.  I was able to repro it only via cqlsh - so that should be a lot easier to diagnose.  

I believe the magic happens on sudo systemctl restart scylla-server

```
cqlsh> CREATE KEYSPACE testing WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
cqlsh> create table if not exists testing.t (v int, primary key (v));
cqlsh> insert into testing.t (v) values (1);
cqlsh> drop keyspace testing;
cqlsh> CREATE KEYSPACE testing WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
cqlsh> create table if not exists testing.t (v int, primary key (v));
cqlsh> insert into testing.t (v) values (1);
cqlsh> insert into testing.t (v) values (1);
cqlsh> drop table testing.t;
cqlsh> insert into testing.t (v) values (1);
InvalidRequest: code=2200 [Invalid query] message="unconfigured table t"
cqlsh> create table if not exists testing.t (v int, primary key (v));
cqlsh> insert into testing.t (v) values (1);
cqlsh> create table if not exists testing.t (v int, primary key (v));
cqlsh> insert into testing.t (v) values (1);
cqlsh> drop table testing.t;
cqlsh> create table if not exists testing.t (v int, primary key (v));
cqlsh> insert into testing.t (v) values (1);
cqlsh> drop table testing.t;
cqlsh> exit

*no duplicates in truncated_at

[root@ip-#-#-#-# centos]# sudo systemctl restart scylla-server
[root@ip-#-#-#-# centos]# sudo systemctl restart scylla-server
[root@ip-#-#-#-# centos]# cqlsh
Connected to ####.
[cqlsh 5.0.1 | Cassandra 2.1.8 | CQL spec 3.2.0 | Native protocol v3]
Use HELP for help.
cqlsh> select truncated_at from system.local;

*duplicates in truncated_at 
```

**Comment by josephblodgett** [comment]
@davebown Thank you very much for all of your initial comments, saved me a lot of time

**Comment by pdziepak** [comment]
Having duplicated elements in a collection looks awfully similar to #1607. However, the code inserting `truncated_at` entries (`save_truncation_records()` in `db/system_keyspace.cc`) looks correct since it adds only a single element. Perhaps we are violating ordering requirements somewhere else as well.

**Comment by dorlaor** [comment]
@elcallio we have a customer hitting this.

**Comment by elcallio** [comment]
So, this will also yield weird results:

```
CREATE KEYSPACE testing WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
create table if not exists testing.kokos (v int, m map<UUID, int>, primary key (v));
update testing.koko set m=m+{c512ba10-7a50-11e6-ac4d-000000000003:3} where v=1;
update testing.kokos set m=m+{c512ba10-7a50-11e6-ac4d-000000000003:2} where v=1;
```

Now:
`select * from testing.kokos ;`

```
v | m
---+------------------------------------------------------------------------------------
 1 | {ad4d3770-7a50-11e6-ac4d-000000000003: 3, c512ba10-7a50-11e6-ac4d-000000000003: 2}
```

restart scylla (or just flush to sstables), then

`update testing.kokos set m=m+{ad4d3770-7a50-11e6-ac4d-000000000003:3} where v=1;`

```
cqlsh> select * from testing.kokos ;

 v | m
---+-----------------------------------------------------------------------------------------------------------------------------
 1 | {ad4d3770-7a50-11e6-ac4d-000000000003: 3, ad4d3770-7a50-11e6-ac4d-000000000003: 3, c512ba10-7a50-11e6-ac4d-000000000003: 2}
```

I.e. for this simple map UUID->int, we get duplicated elements when selecting from both sstable and memtable. Flushing again makes the issue go away. 

Note: This does _not_ seem to happen with a simple int:int map. 

I think @tgrabiec might be better suited to answer what is going on here.

**Comment by tgrabiec** [comment]
@elcallio Which version did you reproduce it with? Does it reproduce every time? I am not able to reproduce using 1.3 AMI nor with master locally. 

Did you perform any other steps in addition to what was mentioned in your comment?

**Comment by pdziepak** [comment]
I think the problem may be `timeuuid_type_impl::compare_bytes`. It is comparing signed bytes so (after reordering) value 0x101 is going to be considered larger than 0x1ff.

**Comment by tgrabiec** [comment]
After trying some random things I managed to reproduce with 1.3 AMI. The problem persists after restart. Attached are the sstables:
[kokos.zip](https://github.com/scylladb/scylla/files/475003/kokos.zip)

**Comment by tgrabiec** [comment]
The problem is in `uuid_type_impl::less`:

```
         if (v1 == 1) {
             auto c1 = timeuuid_type_impl::compare_bytes(b1, b2);
             auto c2 = timeuuid_type_impl::compare_bytes(b2, b1);
             // Require strict ordering
             if (c1 != c2) {
                 return c1;
             }
         }
         return less_unsigned(b1, b2);
```

`timeuuid_type_impl::compare_bytes` is a "trichotomic" comparator (-1, 0, 1), while `less()` is a "less" comparator (false, true). The code incorrectly returns `c1` instead of `c1 < 0` which breaks the ordering. Refs #1449.

Changing to this fixes the problem:
```patch
@@ -773,12 +775,7 @@ struct uuid_type_impl : concrete_type<utils::UUID> {
         }
 
         if (v1 == 1) {
-            auto c1 = timeuuid_type_impl::compare_bytes(b1, b2);
-            auto c2 = timeuuid_type_impl::compare_bytes(b2, b1);
-            // Require strict ordering
-            if (c1 != c2) {
-                return c1;
-            }
+            return timeuuid_type_impl::compare_bytes(b1, b2) < 0;
         }
         return less_unsigned(b1, b2);
     }
```

It seems to be always broken since 99489ff58.

**Comment by tgrabiec** [comment]
@pdziepak I didn't get what is the issue with signedness, can you give an example?

**Comment by pdziepak** [comment]
Apparently, it was just me making noise. In `timeuuid_type_impl::compare_bytes` signed char gets promoted to int and then has bits 8 and higher zeroed so the actual value that is compared is unsigned (as long as sizeof(int) > 1).
