### ISSUE TITLE
Add Scylla installation packages for Debian 8

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1200]

**Comment by Freeaqingme** [comment]
I second this issue. We're a Debian (besides FreeBSD and OpenSolaris) shop, and although I'd really like to give Scylla a try I wonder whether just that would be enough to compel to also add Ubuntu into the mix.

Building packages myself brought no joy yet...

**Comment by syuu1228** [comment]
Tested to build all three packages(scylla-server, scylla-jmx, scylla-tools), all able to build finely on Debian 8.4.

**Comment by syuu1228** [comment]
Ah, I forgot to mention about important thing.
scylla-server compilation will fail because of bug of seastar with g++-4.9, there is a patch for it named "[PATCH] Add <atomic> header for g++-4.9 of Ubuntu 14.04" but looks like not yet applied.

**Comment by h0rn3t** [comment]
Why still no support Debian 8 or compatible DEB packages  ?:(((

**Comment by Ku6ep** [comment]
Please, please, please add support for Debian 8!!!

**Comment by penberg** [comment]
@h0rn3t The main reason is that Scylla relies on C++11/14 features heavily and Debian 8 only has GCC 4.9, which only implements those features partially. We actually build our own GCC for CentOS and RHEL packages.

**Comment by tzach** [comment]
Debian packages are now available http://docs.scylladb.com/getting-started/debian8/
