### ISSUE TITLE
Query across few nodes generates too many range_slice_read_executor:s

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#1204]
Using a 3-node ccm scylla cluster:
`create keyspace ks WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };`
`create table ks.cf (key varchar PRIMARY KEY, messages set<text>);`
`<generate ~10 partitions of ~1000 cql rows each>`
`select * from ks.cf limit 10;`

With trace log and some extra logging in storage_proxy:

TRACE 2016-04-19 16:17:51,326 [shard 0] storage_proxy - query ks.cf cmd=read_command{cf_id=8f308700-063e-11e6-b931-000000000000, version=2abb3923-7d1f-3ace-aaf6-05a5f0a97e0f, slice={regular_cols=[0], static_cols=[], rows=[(-inf, +inf)], options=3, cql_format=3}, limit=50, timestamp=1461082671}, ranges={(-inf, +inf)}, id=25
TRACE 2016-04-19 16:17:51,326 [shard 0] storage_proxy - PK range (-inf, +inf) -> {(-inf, {-9223362678047650380, end}], ({-9223362678047650380, end}, {-9218145415891786592, end}], ({-9218145415891786592, end}, {-9190427855178266204, end}], ({-9190427855178266204, end}, {-9142773239562955358, end}], ({-9142773239562955358, end}, {-9091900798531148569, end}], ({-9091900798531148569, end}, {-9090376616527049148, end}], ({-9090376616527049148, end}, {-9082355951444659322, end}], ({-9082355951444659322, end}, {-9074752996675399332, end}], ({-9074752996675399332, end}, {-9024892423497106119, end}], ({-9024892423497106119, end}, {-9022849173453479362, end}], ({-9022849173453479362, end}, {-9016930760989662468, end}], ({-9016930760989662468, end}, {-8994751904594828620, end}], ({-8994751904594828620, end}, {-8960152047314116400, end}], ({-8960152047314116400, end}, {-8862967820552843242, en

.....

593453025169, end}, {9197448242467372996, end}], ({9197448242467372996, end}, +inf)}
TRACE 2016-04-19 16:17:51,327 [shard 0] storage_proxy - query of (-inf, {-9223362678047650380, end}]/{(-inf, {-9223362678047650380, end}], ({-9223362678047650380, end}, {-9218145415891786592, end}], ({-9218145415891786592, end}, {-9190427855178266204, end}], ({-9190427855178266204, end}, {-9142773
..... etc

TRACE 2016-04-19 16:17:51,327 [shard 0] storage_proxy - creating range read executor with targets {127.0.0.3}
TRACE 2016-04-19 16:17:51,327 [shard 0] storage_proxy - creating range read executor with targets {127.0.0.2}
TRACE 2016-04-19 16:17:51,327 [shard 0] storage_proxy - creating range read executor with targets {127.0.0.1}
TRACE 2016-04-19 16:17:51,327 [shard 0] storage_proxy - creating range read executor with targets {127.0.0.2}
TRACE 2016-04-19 16:17:51,327 [shard 0] storage_proxy - creating range read executor with targets {127.0.0.3}
TRACE 2016-04-19 16:17:51,327 [shard 0] storage_proxy - creating range read executor with targets {127.0.0.1}
TRACE 2016-04-19 16:17:51,327 [shard 0] storage_proxy - creating range read executor with targets {127.0.0.2}
TRACE 2016-04-19 16:17:51,327 [shard 0] storage_proxy - creating range read executor with targets {127.0.0.1}

.... and so on for ~536 lines
TRACE 2016-04-19 16:17:51,357 [shard 0] storage_proxy - query_result id=25, size=25671

Since each range_slice_read_executor (afaict) acquires the full limit, we end up with quite a few result rows beyond the desired three. 

This same behaviour kills the efficiency of paging as well, once we're beyond a single node, since it relies on limit + range modification to acquire the desired number of rows. 

[storage_proxy.log.patch.txt](https://github.com/scylladb/scylla/files/226345/storage_proxy.log.patch.txt)

**Comment by elcallio** [comment]
Sorry, typo in original post. Replication factor 1.

**Comment by slivne** [comment]
@elcallio is it replication_factor 3 or replication factor 1 - in both you had replication factor 1
