### ISSUE TITLE
Scylla may deadlock after compacting shared sstables

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1205]
Scylla version (or git commit hash): master (f8d8dbdeb7918ef9f2743b014ea6d7bade16f3fd)

Suppose that on one shard we compact a lot of shared sstables and start background delete_atomically() from rebuild_sstable_list(), but other shards still keep hold to them because compaction was not triggered on those shards for this sstable. Maybe they received less writes. do_delete_atomically() won't resolve until all shards want to delete the sstable. So we end up with more than 128 unresolved submissions to shard 0 from delete_atomically(). This will block new submissions from shard 1 to shard 0. For example, it may prevent queries from completing if they were initiated on shard 1 and need data owned by shard 0.

One problem is that we have this limit for pending across shard submissions. We already decided we want to get rid of it because it can lead to deadlocks or performance problems (see #1088). Here for example it results in queries being blocked by pending unrelated operations (sstable deletion).

Second problem is that forward progress of delete_atomically() doesn't seem to be guaranteed. While compaction doesn't wait for those deletions, it runs them under a gate and column_family::stop() will hang, blocking shutdown or table drop. Those submissions may also accumulate with time taking memory.

**Comment by penberg** [comment]
``git bisect`` points to this commit:

```
3798d04ae8785e1d44208d4b16be1365d01100bf is the first bad commit
commit 3798d04ae8785e1d44208d4b16be1365d01100bf
Author: Avi Kivity <avi@scylladb.com>
Date:   Wed Apr 13 16:28:09 2016 +0300

    sstables: convert sstable::mark_for_deletion() to atomic deletion
infrastructure

    All deletions must go through the same data structure, or some atomic
    deletions will never be satisified.

:040000 040000 664db223fa693e8b859c5140d8e39314cddfb621
335c865942d04009213d487adfbae293d8a8585d M sstables
```

**Comment by slivne** [comment]
Tomek I think you are correct and this is happening in Pekka's case - even though the files are not shared. 

In Pekka's test - there is a creation of CF for every test - so it ends up with many sstables.

Currently, when we boot each shard tries to load all sstables (and all files on disk are considered shared) - every sstable that does not be long to it is "marked for deletion"

```
future<sstables::entry_descriptor> column_family::probe_file(sstring sstdir, sstring fname) {
.
.
.
        if (!belongs_to_current_shard(*_schema, std::move(r))) {
            dblog.debug("sstable {} not relevant for this shard, ignoring",
                    sstables::sstable::filename(sstdir, _schema->ks_name(), _schema->cf_name(), comps.version, comps.generation, comps.format,
                            sstables::sstable::component_type::Data));
            sstable::mark_sstable_for_deletion(_schema->ks_name(), _schema->cf_name(), sstdir, comps.generation, comps.version, comps.format);
            return make_ready_future<>();
        }
```
this leads to calling delete_atomcally which will not be called on the shard that the sstable belongs to and we are stuck

sample file from log file
```
DEBUG 2016-04-23 18:48:21,190 [shard 0] sstable - Reading TOC file /home/shlomi/.ccm/scylla-1/node1/data/cql_test_keyspace/table_1461424888641-c5a86dd0096711e68bfd000000000001/cql_test_keyspace-table_1461424888641-ka-2-TOC.txt 
DEBUG 2016-04-23 18:48:21,190 [shard 0] sstable - Reading Summary.db file /home/shlomi/.ccm/scylla-1/node1/data/cql_test_keyspace/table_1461424888641-c5a86dd0096711e68bfd000000000001/cql_test_keyspace-table_1461424888641-ka-2-Summary.db 
DEBUG 2016-04-23 18:48:21,190 [shard 0] sstable - Reading Statistics.db file /home/shlomi/.ccm/scylla-1/node1/data/cql_test_keyspace/table_1461424888641-c5a86dd0096711e68bfd000000000001/cql_test_keyspace-table_1461424888641-ka-2-Statistics.db 
DEBUG 2016-04-23 18:48:21,191 [shard 0] sstable - Reading CompressionInfo.db file /home/shlomi/.ccm/scylla-1/node1/data/cql_test_keyspace/table_1461424888641-c5a86dd0096711e68bfd000000000001/cql_test_keyspace-table_1461424888641-ka-2-CompressionInfo.db 
DEBUG 2016-04-23 18:48:21,191 [shard 0] sstable - Reading Filter.db file /home/shlomi/.ccm/scylla-1/node1/data/cql_test_keyspace/table_1461424888641-c5a86dd0096711e68bfd000000000001/cql_test_keyspace-table_1461424888641-ka-2-Filter.db 
DEBUG 2016-04-23 18:48:21,746 [shard 1] sstable - Reading TOC file /home/shlomi/.ccm/scylla-1/node1/data/cql_test_keyspace/table_1461424888641-c5a86dd0096711e68bfd000000000001/cql_test_keyspace-table_1461424888641-ka-2-TOC.txt 
DEBUG 2016-04-23 18:48:21,746 [shard 1] sstable - Reading Summary.db file /home/shlomi/.ccm/scylla-1/node1/data/cql_test_keyspace/table_1461424888641-c5a86dd0096711e68bfd000000000001/cql_test_keyspace-table_1461424888641-ka-2-Summary.db 
DEBUG 2016-04-23 18:48:21,746 [shard 1] database - sstable /home/shlomi/.ccm/scylla-1/node1/data/cql_test_keyspace/table_1461424888641-c5a86dd0096711e68bfd000000000001/cql_test_keyspace-table_1461424888641-ka-2-Data.db not relevant for this shard, ignoring
DEBUG 2016-04-23 18:48:21,754 [shard 0] sstable-deletion - shard 1 atomically deleting {/home/shlomi/.ccm/scylla-1/node1/data/cql_test_keyspace/table_1461424888641-c5a86dd0096711e68bfd000000000001/cql_test_keyspace-table_1461424888641-ka-2-TOC.txt(shared)}
DEBUG 2016-04-23 18:48:21,755 [shard 0] sstable-deletion - new atomic set: {/home/shlomi/.ccm/scylla-1/node1/data/cql_test_keyspace/table_1461424888641-c5a86dd0096711e68bfd000000000001/cql_test_keyspace-table_1461424888641-ka-2-TOC.txt}
```

@avikivity ?

**Comment by avikivity** [comment]
@tgrabiec, see `cancel_atomic_deletions()`.  It is called during shutdown to make sure that it completes.

It is true that deletion requests accumulate in memory, but they are O(number of sstables in memory), so they can't overflow memory by themselves (we assume that we have enough memory for all sstables).

**Comment by penberg** [comment]
The "smp: allow more than 128 in-flight" patch from @avikivity to Seastar fixes the problem for me.
