### ISSUE TITLE
.deb build issue on ubuntu 14.04

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#1206]
## Installation details
Scylla version (or git commit hash): 7f85373e15071a3fd9075544b1a1cc51d864ee6b
Cluster size: unrelevant
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS ubuntu AMI

## Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker): C3.8xlarge
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

With this commit and a packaging patch on top of it  ./dist/ubuntu/build_deb.sh gives:

	    [179/374] CXX build/release/seastar/tests/test_runner.o
	    FAILED: g++-5 -MMD -MT build/release/database.o -MF build/release/database.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I/mnt/scylla/seastar -I/mnt/scylla/seastar/build/release/gen      -march=nehalem -DHAVE_DPDK -I/mnt/scylla/seastar/build/dpdk/include -march=corei7 -    DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2 -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof -Wno-overloaded-virtual -DHAVE_HWLOC - DHAVE_NUMA  -O2 -I/usr/include/jsoncpp -Wno-maybe-uninitialized  -I. -I build/release/gen -I seastar -I seastar/build/release/gen -c -o build/release/database.o database.cc
	     In file included from /usr/include/boost/range/join.hpp:15:0,
			 from ./schema.hh:26,
			 from ./keys.hh:24,
			 from dht/i_partitioner.hh:46,
			 from database.hh:25,
			 from database.cc:23:
	     /usr/include/boost/range/detail/join_iterator.hpp: In instantiation of ‘Reference     boost::range_detail::join_iterator_union<Iterator1, Iterator2, Reference>::dereference(unsigned int)   const [with Iterator1 = __gnu_cxx::__normal_iterator<const lw_shared_ptr<sstables::sstable>*,   std::vector<lw_shared_ptr<sstables::sstable> > >; Iterator2 =    boost::transform_iterator<boost::range_detail::select_second_mutable<std::map<long int,    lw_shared_ptr<sstables::sstable> > >, std::_Rb_tree_iterator<std::pair<const long int,    lw_shared_ptr<sstables::sstable> > >, boost::use_default, boost::use_default>; Reference =   lw_shared_ptr<sstables::sstable>&]’:
	     /usr/include/boost/range/detail/join_iterator.hpp:244:42:   required from ‘typename    boost::range_detail::join_iterator<Iterator1, Iterator2, ValueType, Reference, Traversal>::reference boost::range_detail::join_iterator<Iterator1, Iterator2, ValueType, Reference, Traversal>::dereference() const [with Iterator1 = __gnu_cxx::__normal_iterator<const lw_shared_ptr<sstables::sstable>*,  std::vector<lw_shared_ptr<sstables::sstable> > >; Iterator2 = boost::transform_iterator<boost::range_detail::select_second_mutable<std::map<long int,  lw_shared_ptr<sstables::sstable> > >, std::_Rb_tree_iterator<std::pair<const long int, lw_shared_ptr<sstables::sstable> > >, boost::use_default, boost::use_default>; ValueType = lw_shared_ptr<sstables::sstable>; Reference = lw_shared_ptr<sstables::sstable>&; Traversal = boost::bidirectional_traversal_tag; typename boost::range_detail::join_iterator<Iterator1, Iterator2, ValueType, Reference, Traversal>::reference = lw_shared_ptr<sstables::sstable>&]’
	      /usr/include/boost/iterator/iterator_facade.hpp:514:32:   required from ‘static typename Facade::reference boost::iterator_core_access::dereference(const Facade&) [with Facade = boost::range_detail::join_iterator<__gnu_cxx::__normal_iterator<const lw_shared_ptr<sstables::sstable>*, std::vector<lw_shared_ptr<sstables::sstable> > >, boost::transform_iterator<boost::range_detail::select_second_mutable<std::map<long int, lw_shared_ptr<sstables::sstable> > >, std::_Rb_tree_iterator<std::pair<const long int, lw_shared_ptr<sstables::sstable> > >, boost::use_default, boost::use_default>, lw_shared_ptr<sstables::sstable>, lw_shared_ptr<sstables::sstable>&, boost::bidirectional_traversal_tag>; typename Facade::reference = lw_shared_ptr<sstables::sstable>&]’
	     /usr/include/boost/iterator/iterator_facade.hpp:639:51:   required from ‘boost::iterator_facade<I, V, TC, R, D>::reference boost::iterator_facade<I, V, TC, R, D>::operator*() const [with Derived = boost::range_detail::join_iterator<__gnu_cxx::__normal_iterator<const lw_shared_ptr<sstables::sstable>*, std::vector<lw_shared_ptr<sstables::sstable> > >, boost::transform_iterator<boost::range_detail::select_second_mutable<std::map<long int, lw_shared_ptr<sstables::sstable> > >, std::_Rb_tree_iterator<std::pair<const long int, lw_shared_ptr<sstables::sstable> > >, boost::use_default, boost::use_default>, lw_shared_ptr<sstables::sstable>, lw_shared_ptr<sstables::sstable>&, boost::bidirectional_traversal_tag>; Value = lw_shared_ptr<sstables::sstable>; CategoryOrTraversal = boost::bidirectional_traversal_tag; Reference = lw_shared_ptr<sstables::sstable>&; Difference = long int; boost::iterator_facade<I, V, TC, R, D>::reference = lw_shared_ptr<sstables::sstable>&]’
	database.cc:847:82:   required from here
	     /usr/include/boost/range/detail/join_iterator.hpp:74:37: error: binding ‘const lw_shared_ptr<sstables::sstable>’ to reference of type ‘lw_shared_ptr<sstables::sstable>&’ discards qualifiers
		 return selected ? *m_it2 : *m_it1;
					     ^ 
	     FAILED: g++-5 -MMD -MT build/release/sstables/sstables.o -MF build/release/sstables/sstables.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I/mnt/scylla/seastar -I/mnt/scylla/seastar/build/release/gen  -march=nehalem -DHAVE_DPDK -I/mnt/scylla/seastar/build/dpdk/include -march=corei7 -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG      _SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2 -Wno-  error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof -Wno-overloaded-virtual -DHAVE_HWLOC -DHAVE_NUMA  -O2 -I/usr/include/jsoncpp -Wno-maybe-uninitialized  -I. -I build/release/gen -I seastar      -I seastar/build/release/gen -c -o build/release/sstables/sstables.o sstables/sstables.cc
	     sstables/sstables.cc: In function ‘future<> s stables::do_delete_atomically(std::vector<sstables::sstable_to_delete>, unsigned int)’:
	     sstables/sstables.cc:2077:61: error: no matching function for call to ‘   insert(sstables::sstables_to_delete_atomically_type&, sstables::sstables_to_delete_atomically_type&)’
		      boost::insert(merged_set->names, old_set->names);
								     ^
	      In file included from sstables/sstables.cc:48:0:
	      /usr/include/boost/range/algorithm_ext/insert.hpp:26:19: note: candidate: template<class Container,    class Range> Container& boost::range::insert(Container&, typename Container::iterator, const Range&)
	      inline Container& insert( Container& on,
			   ^
	     /usr/include/boost/range/algorithm_ext/insert.hpp:26:19: note:   template argument   deduction/substitution failed:
	     sstables/sstables.cc:2077:61: note:   candidate expects 3 arguments, 2 provided
		      boost::insert(merged_set->names, old_set->names);

I am trying without the patch

**Comment by benoit-canet** [comment]
The faultly line is in
commit 2ba584db8d9a1ad7df7669f37df1f81cd71e8b35
Author: Avi Kivity <avi@scylladb.com>
Date:   Wed Apr 13 15:23:29 2016 +0300

    sstables: add delete_atomically(), for atomically deleting multiple sstables
    
    When we compact a set of sstables, we have to remove the set atomically,
    otherwise we can resurrect data if the following happens:
    
     insert data to sstable A
     insert tombstone to sstable B
     compact A+B -> C (removing both data and tombstone)
     delete B only
     read data from A
    
    Since an sstable may be shared by multiple shard, and each shard performs
    compaction at a different time, we need to defer deletion of an sstable
    set until all shards agree that the set can be deleted.
    
    An additional atomicity issue exists because posix does not provide a way
    to atomically delete multiple files.  This issue is not addressed by this
    patch.

diff --git a/sstables/sstables.cc b/sstables/sstables.cc

**Comment by penberg** [comment]
It's a Boost version issue. There are patches  on the mailing list from @elcallio that are supposed fix them.

**Comment by tzach** [comment]
@benoit-canet can we close this?
