### ISSUE TITLE
Improve 99.9 latency by OS configuration

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#1210]
Avi recommends to check the effect of tuning /proc/sys/kernel/sched_latency_ns and sched_min_granularity_ns.

**Comment by slivne** [comment]
related to #1218

**Comment by tzach** [comment]
Is this still an issue once #1218 is closed?

**Comment by tgrabiec** [comment]
I think this is closed by e515933c70a11404f9f26472f562ec5c44c82c12
