### ISSUE TITLE
nodetool refresh - should we invalidate the cache

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1212]
version 1.0

nodetool refresh loads sstable onto a running system.
partitions that are cached bypass searching in sstables - thus they will miss any data existing in the "loaded" sstables.

we need to invalidate the cache when we upload new sstables.

**Comment by amnonh** [comment]
if that cache would support it, we can enable the nodetool invalidaterowcache
command

**Comment by tgrabiec** [comment]
@amnonh user of the database should not need to care about our internal caching, implementation of refresh should take care of syncing the cache.

**Comment by amnonh** [comment]
My comment wassn't instead of the refresh implementation. but if we add the invalidation functionality, we can enable the nodetool command

**Comment by raphaelsc** [comment]
@tgrabiec the easier way to go is to remove all entries from the cache that belong to column family being refreshed. Does the cache provide an API for that? Thanks.
