### ISSUE TITLE
Push wraparound logic out of range<> template

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1213]
Scylla version (or git commit hash): c6b5890eb277d9097ce092edbd4aeb300225622f

Range wraparound is confusing, it should be pushed out of `range<>` and moved to the point where we convert ring positions to a range list.

**Comment by duarten** [comment]
With `nonwrapping_range<>`, is the issue still relevant?

**Comment by avikivity** [comment]
It's there in a different form, #3035. Closing in favor of that.
