### ISSUE TITLE
Ubuntu 14.04 installation - repository path 

### ISSUE THREAD

**Issue by rachlenko** [scylladb/scylla#1214]
## Installation details
Scylla version (
    'scylla-jmx' => '1.0.1-20160413.955dc16-ubuntu1',
    'scylla-server' => '1.0.1-20160413.8d1374e-ubuntu1',
    'scylla-server-dbg' => '1.0.1-20160413.8d1374e-ubuntu1',
    'scylla-tools' => '1.0.1-20160413.f2b4291-ubuntu1'
):
Cluster size:3 nodes
OS (Ubuntu 14.04):

## Hardware details (for performance issues)
Platform (/VM/):
Hardware: 1= 1= N= 2=
Disks: (HDD, 1)

Hi ,
I am testing the public cookbook of scylla-db with last chef version(12). 
I'll be happy if you can upload described version to the public repository 
http://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu

and change if possible, the [scylladb/multiverse] to standard just [multiverse]

then cookbook procedure will follow ubuntu standards for 3rd party application : 

apt_repository "scylladb-repository" do
  distribution 'trusty'
  arch 'amd64'
 --   components ['scylladb/multiverse']
 ++ components ['multiverse']
  uri 'http://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu'
end

**Comment by tzach** [comment]
@rachlenko the new Ubuntu repos are:
Ubuntu 14.04 `https://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu/scylla-1.2-trusty.list`
Ubuntu 16.04 `https://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu/scylla-1.2-xenial.list`

Which are similar to Datastax repo `http://debian.datastax.com/community/`
and Apache Cassandra repo is `http://dl.bintray.com/apache/cassandra/`
as far as I can see there is no `multiverse` in either.
What am I'm missing?

**Comment by slivne** [comment]
We are using the last part as a version specifier - e.g.

for 1.1 it is scylladb-1.1/multiverse
for 1.2 it is scylladb-1.2/multiverse

the multiverse was added to try and not mislead on scylladb licensing (https://help.ubuntu.com/community/Repositories/Ubuntu)

**Comment by tzach** [comment]
Look like the current path do work. I'm closing this issue till we get more evidence there is an issue.
