### ISSUE TITLE
TLS rpc/client fail to send all data on large packets

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#1219]
TLS implementation in seastar has/had a bug in sink::put path that would fail to properly process large packets needed to be broken up, resulting in only the first ~16k or so of each net::packet sent would actually get transmitted. End result in scylla was that slightly largish RPC messages for example would be truncated, resulting in exceptions and/or time outs. 

seastar issue is fixed by commit dab58e4562fbdc6efd47ff16121af785b46f3f76

**Comment by tzach** [comment]
@elcallio can we close?

**Comment by elcallio** [comment]
I think so. Not sure if the seastar version for 1.1 is updated though...

**Comment by slivne** [comment]
1.1 is updated
