### ISSUE TITLE
Disable smp queue collectd counters by default

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1221]
We saw that riemann from scylla-monitoring can get overloaded when serving a 3-node cluster with collectd period of 1s. As a result, samples are dropped on their way to graphite. 

To remedy the problem we can keep only essential metrics turned on by default, and let others be switched on selectively at run-time using RESTful API when needed. This is #461.

Our core-to-core queue counters are first candidates for disabling by default. They consume significant portion of bandwidth but are not needed for general monitoring. We could provide high-level aggregates enabled by default.

**Comment by avikivity** [comment]
For the long term, we should consider providing a [pcp](http://pcp.io) interface in addition to collectd.  pcp is a pull interface instead of push, allowing the client to specify what to pull, instead of pushing everything and needing tricks like this to shut down less interesting metrics.

**Comment by amnonh** [comment]
I'm looking at implementing it, I see three options:
1. add some flag to the collectd, which would mark a specific metric is disable by default
2. add a call in main to disable specific metric
3. add some kind of configuration.

Note, that not all metrics are available when the system starts, so disabling should be done when the metric is already created.

**Comment by slivne** [comment]
commit 0d4d9c5aa86d271afe3fde46c9476155a7a74950
Author: Amnon Heiman <amnon@scylladb.com>
Date:   Sun Jul 17 18:17:06 2016 +0300

    reactor: Register the smp metrics disabled
    
    Typically the smp metrics should be disabled, they cause too much
    traffic to the collectd server and gives little value.
    
    This patch register those metrics as disabled, if needed they can be
    enabled at run time via the API.
    
    Signed-off-by: Amnon Heiman <amnon@scylladb.com>
    Message-Id: <1468768626-19888-3-git-send-email-amnon@scylladb.com>
