### ISSUE TITLE
performance degradation when growing cluster

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#1223]
What we did in the test:
 1) Start a 3 nodes cluster
 2) Start cassandra-stress on the loader node
 3) Add a new node
 4) Keep repeating 3) until we get to the target number of 5 nodes

Loader node: 'cassandra-stress write cl=QUORUM duration=20m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=1000 -node 172.30.0.123'
DB nodes: from 3 nodes to 5 nodes
Scylla commit: 4ed702f0dae7317b1bb5c8b31aea0df6613bafd0
Instances: c3.large

Results: Check the svg graph in the attached zip file for the ops/latency number for c-s output during the test, we have huge drop when nodes are added.

[job-2016-04-21T06.05-b67d72b.zip](https://github.com/scylladb/scylla/files/240140/job-2016-04-21T06.05-b67d72b.zip)

**Comment by slivne** [comment]
just to make it clearer - can you specify some numbers e.g. throughput dropped to Y% latency increased by X%

**Comment by asias** [comment]
The graph has more details. In general, the throughput drops from 35K to 10K, the latency is spiky, 99% lat goes up 3s from ~100ms, during the adding node operation period.

**Comment by lmr** [comment]
![node hj-test-long-scylla-loader-node-e3cf000f-1 52 201 218 19 172 30 0 237 seed none -lat svg](https://cloud.githubusercontent.com/assets/296807/15017666/ddc084ba-11ec-11e6-87a2-fdc0e75f1d60.png)

**Comment by lmr** [comment]
![node hj-test-long-scylla-loader-node-e3cf000f-1 52 201 218 19 172 30 0 237 seed none -ops svg](https://cloud.githubusercontent.com/assets/296807/15017688/f94c7360-11ec-11e6-9f4d-f38827a1a470.png)

**Comment by lmr** [comment]
@slivne, I've converted the svgs to png (since github does not support embedding svg) and here you go, the graphs from @asias run.

**Comment by lmr** [comment]
One update that I found while investigating #1270 - we are faring much better on node additions, see image attached

![ops](https://cloud.githubusercontent.com/assets/296807/15409010/4784a694-1de9-11e6-8290-055a7c09995f.png)

There's still a drop, but much smaller. This represents 2 nodes being added to a 3 node cluster.

**Comment by lmr** [comment]
Oh yeah, this is ac8f65c1 on `us_east_1`, basically built from current scylla master, 6ec0000.

**Comment by dorlaor** [comment]
That's much better. We should still strive to get the graph flat instead of
oscillating at +-15k even before the node addition. Also why there is a
quick but huge drop? It happens twice, weird.

What's the gauge load before you add the node? What's the bottle neck to
the performance here?

**Comment by lmr** [comment]
@dorlaor it happens twice because there are 2 node additions. The load is 

    "cassandra-stress write cl=QUORUM duration=%sm "
    "-schema 'replication(factor=3)' -port jmx=6868 "
    "-mode cql3 native -rate threads=%s "
    "-pop seq=1..100000 -node %s"

with 1000 threads, instance size c3.xlarge. The test waits until there's at least 6GB of data [1] stored on existing nodes before adding the new node.

[1] Empyrical value found out by Asias when he was working on #1140.

**Comment by lmr** [comment]
I also forgot to attach the latency graph. It's much better and there's barely any disturbance to the general latency trends.

![lat svg](https://cloud.githubusercontent.com/assets/296807/15410553/c2cc507a-1df0-11e6-89a3-206a73d8d856.png)

**Comment by asias** [comment]
@lmr, Good! I am wondering when adding node operation started (the event marking feature you worked on will help). One thing to note, I used  c3.large instead of c3.xlarge in my run.

**Comment by avikivity** [comment]
What is the duration of the two spikes?

**Comment by lmr** [comment]
@avi, ~30 seconds for the 1st spike, ~40 seconds for the 2nd spike, which is better than the previous result (which I can't find right now, but by looking at the graphs is ~100 seconds.

So I guess I might have been deceived by the scale of the graphs when estimating that we are faring 'much better', sorry about that.

**Comment by lmr** [comment]
@asias, funny thing, I noticed that the grow cluster test growing operation is not actually implemented as a nemesis, so the event marking won't work there as is (that's why the graph here has no marks). I have to massage the code to fix this.

**Comment by lmr** [comment]
Now the shrink cluster test was implemented as a nemesis, so event marking worked perfectly here on the #1140 investigation. See attached graphs, please keep in mind that these were generated with the latest 1.0.X AMI:

![lat svg](https://cloud.githubusercontent.com/assets/296807/15435813/e323d4a2-1e94-11e6-8623-696605295c09.png)

![ops svg](https://cloud.githubusercontent.com/assets/296807/15435820/eb450606-1e94-11e6-862c-b2818f3fe766.png)

You can clearly see the correspondence between nemesis operation (decommission) and performance and latency spikes.

**Comment by dorlaor** [comment]
It seems as if Asias fix isn't effective here (although the claimed commit
hash it older).
@asias ^

**Comment by lmr** [comment]
The last graphs are from 1.0.X, so @asias fix is not present. I just pasted the results here to show how the nemesis event marking is working.

**Comment by lmr** [comment]
In any case, the results I gathered here show a sizeable reduction of the performance drop window (from > 100s to ~ 30s). Now it all boils down to what is the end goal here (10s? 5s? no drop at all?).

**Comment by dorlaor** [comment]
On Fri, May 20, 2016 at 9:32 PM, Lucas Meneghel Rodrigues <
notifications@github.com> wrote:

> In any case, the results I gathered here show a sizeable reduction of the
> performance drop window (from > 100s to ~ 30s). Now it all boils down to
> what is the end goal here (10s? 5s? no drop at all?).
>

The end goal is no drop and no latency spike. It's of course a function of
the load.
My question before about the load wasn't about the client loader but the
load we measure
on our shards.

**Comment by avikivity** [comment]
How is the load generated?  Fixed rate or all out?

**Comment by avikivity** [comment]
I would guess all out, since it climbs after the nodes are added.  We should also test with a fixed (low) rate (since streaming out the data does generate an additional load).

What we see here is that the extra work takes its toll, and since the cluster is not I/O bound, nothing is keeping the extra load in check.

**Comment by asias** [comment]
@avikivity The load is generated with:

```
  0         return ("cassandra-stress write cl=QUORUM duration=%sm "
  1                 "-schema 'replication(factor=3)' -port jmx=6868 "
  2                 "-mode cql3 native -rate threads=%s "
  3                 "-pop seq=1..10000000 -node %s" % (duration, threads, ip))
```

**Comment by dorlaor** [comment]
On Mon, May 23, 2016 at 5:41 AM, Asias He <notifications@github.com> wrote:

> @avikivity <https://github.com/avikivity> The load is generated with:
>
>   0         return ("cassandra-stress write cl=QUORUM duration=%sm "
>   1                 "-schema 'replication(factor=3)' -port jmx=6868 "
>   2                 "-mode cql3 native -rate threads=%s "
>
>
We would like to specifically add a req/sec to limit the maximum throughput
in order to
know we're not saturated.

-rate limit=%s/s threads=%s

**Comment by asias** [comment]
@dorlaor it is hard to figure out a req/sec for every test, but in this specific setup. we can cap the req/sec to 50K with c3.xlarge, leaving some room for the extra traffic for the joining node.

**Comment by avikivity** [comment]
The idea is to see the impact with a low load first, even 10k/s is enough.

Once low load is not impacted significantly, we can try to improve full loads.

**Comment by asias** [comment]
On Mon, May 23, 2016 at 3:01 PM, Avi Kivity <notifications@github.com>
wrote:

> The idea is to see the impact with a low load first, even 10k/s is enough.
>
> Once low load is not impacted significantly, we can try to improve full
> loads.
>

I did a simple test locally.

1. start 1 node
2. generate some data
taskset -c 7 cassandra-stress write duration=5m cl=ONE -schema
'replication(factor=1)' -pop seq=1..10000  -rate threads=200 limit=10000/s
-node 127.0.0.1  -log file=c-s.log
3. start another node

The cql/sec is fat 10k, no drop is seen.



-- 
Asias

**Comment by avikivity** [comment]
Good, so the degradation probably comes from cpu consumption by the streaming code and/or compaction of streamed sstables.

**Comment by asias** [comment]
Since we are adding node, existing node will only "send" data, so compaction will only have impact on the new node.

**Comment by dorlaor** [comment]
10k/s is too low since the drop reduced performance to 10k/s.
How about 30k/s

**Comment by asias** [comment]
With 20K, very small drop is seen.
With 30K, the drop is seen.

[20Kand30K.zip](https://github.com/scylladb/scylla/files/277006/20Kand30K.zip)

**Comment by asias** [comment]
I tried starting 2 nodes locally, then running c-s without limit, it can only get 26 to 30K. So, 30k is already beyond max capacity in my setup.

**Comment by asias** [comment]
"
Oh yeah, this is ac8f65c1 on us_east_1, basically built from current scylla master, 6ec0000.
"


@lmr Like I mentioned in https://github.com/scylladb/scylla/issues/1270

scylla_2016-05-19T02-20-18Z (ami-ac8f65c1) is a 1.0.3 branch ami, not the latest scylla master, which contains my fix (089734474bc49de43ae250b28ed2ed2c67fd8235 token_metadata: Speed up pending_endpoints_for)

**Comment by asias** [comment]
growing from 3 nodes to 4 nodes with scylla master commit:

ami: ami-2bbb4c46
scylla commit: commit 94e7e61cd035d2dc93b9bbbf88d719a08ece488f
type: c3.xlarge

```
        return ("cassandra-stress write cl=QUORUM duration=%sm "
                "-schema 'replication(factor=3)' -port jmx=6868 "
                "-mode cql3 native -rate threads=%s limit=50000/s "
                "-pop seq=1..100000 -node %s" % (duration, threads, ip))
```

![node asias-test-long-scylla-loader-node-443e009b-1 54 165 65 52 172 30 0 127 seed none -ops](https://cloud.githubusercontent.com/assets/320076/15467905/87b60d2a-2113-11e6-8ad6-b0863a5c5f3e.png)
![node asias-test-long-scylla-loader-node-443e009b-1 54 165 65 52 172 30 0 127 seed none -lat](https://cloud.githubusercontent.com/assets/320076/15467906/880ff830-2113-11e6-89b5-b11ec5675f4e.png)

**Comment by dorlaor** [comment]
That's much more like it!
Can you measure it with higher limit and w/o a limit?

**Comment by avikivity** [comment]
The dotted lines indicate where a node is added?

**Comment by asias** [comment]
@avikivity yes, blue dot line == start of adding node , red dot line == end of adding node
@dorlaor yup, I am running without limit atm.

**Comment by asias** [comment]
growing from 3 nodes to 4 nodes with scylla master commit:

ami: ami-2bbb4c46
scylla commit: commit 94e7e61
type: c3.xlarge
without rate limit:

```
        return ("cassandra-stress write cl=QUORUM duration=%sm "
                "-schema 'replication(factor=3)' -port jmx=6868 "
                "-mode cql3 native -rate threads=%s "
                "-pop seq=1..100000 -node %s" % (duration, threads, ip))
```



![node asias-test-long-scylla-loader-node-fa8a930b-1 52 207 210 242 172 30 0 147 seed none -ops](https://cloud.githubusercontent.com/assets/320076/15469540/73e131a8-211d-11e6-9f3c-bbf397b396ee.png)

![node asias-test-long-scylla-loader-node-fa8a930b-1 52 207 210 242 172 30 0 147 seed none -lat](https://cloud.githubusercontent.com/assets/320076/15469539/7386de1a-211d-11e6-93e1-c9562d9944cc.png)

**Comment by dorlaor** [comment]
There are some nasty, unexplained drops even before the cluster growth.
We'll need to get an explanation for them. Could be that test on physical
nodes
will help to isolate.

I expected to see a larger gain when the 4th node is insync, could be that
your loaders
are capped?

**Comment by asias** [comment]
growing from 3 nodes to 4 nodes with scylla master commit:

ami: ami-2bbb4c46
scylla commit: commit 94e7e61
type: c3.xlarge
with rate limit: 70K
```
        return ("cassandra-stress write cl=QUORUM duration=%sm "
                "-schema 'replication(factor=3)' -port jmx=6868 "
                "-mode cql3 native -rate threads=%s limit=70000/s "
                "-pop seq=1..100000 -node %s" % (duration, threads, ip))
```
![node asias-test-long-scylla-loader-node-0c446448-1 54 87 130 166 172 30 0 38 seed none -ops](https://cloud.githubusercontent.com/assets/320076/15470268/387cdb62-2122-11e6-9d7f-9beae2779d77.png)
![node asias-test-long-scylla-loader-node-0c446448-1 54 87 130 166 172 30 0 38 seed none -lat](https://cloud.githubusercontent.com/assets/320076/15470270/3f2cb8ba-2122-11e6-98ff-0615cb87e73a.png)

**Comment by asias** [comment]
There is only one loader instance with one c-s process currently. It could be that the loader does not saturate the cluster. But let's focus on the main issue here.

**Comment by belliottsmith** [comment]
It is very unlikely the cassandra-stress client is your bottleneck with those settings.

**Comment by dorlaor** [comment]
I expected to see throughput increase from 3 nodes to 4 nodes. The only
explanation is a bottleneck somewhere. It could be that the bottleneck isn't
the client's cpu but the #connections. You can run multiple loader
processes.

Another thing is to capture the load-gauge on the Scylla cores (scyllatop)

**Comment by belliottsmith** [comment]
But the work is rate limited?

**Comment by dorlaor** [comment]
On Tue, May 24, 2016 at 12:57 AM, Benedict Elliott Smith <
notifications@github.com> wrote:

> But the work is rate limited?
>

You're right about the last sample. There were too many before..
Right before the last one there was an unbounded one which seems to increase
throughput a little bit although the entire things was relatively noisy.

**Comment by belliottsmith** [comment]
Ah, and actually I misread your EC2 instance.  It's entirely possible cassandra-stress is your bottleneck with only a c3.xlarge.  I never ran it with such modest hardware.  I would still be a little surprised, as it has to do really very little work for this workload, and on my local laptop I could produce 100k/s from cassandra-stress to a Cassandra instance running on the same laptop; a c3.xlarge should be able to do as much or more when only running cassandra-stress.  The network does introduce a different aspect, but NIC-offload should probably reduce the overhead, not increase.

Certainly there are no connection limits; there will only be 2 per Scylla node.

It is possible there is something funky with your AMI.

**Comment by asias** [comment]
This commit helped the performance:

```
commit 089734474bc49de43ae250b28ed2ed2c67fd8235
Author: Asias He <asias@scylladb.com>
Date:   Tue May 17 17:31:55 2016 +0800

    token_metadata: Speed up pending_endpoints_for

    pending_endpoints_for is called frequently by
    storage_proxy::create_write_response_handler when doing cql query.

    Before this patch, each call to pending_endpoints_for involves
    converting a multimap (std::unordered_multimap<range<token>,
    inet_address>>) to map (std::unordered_map<range<token>,
    std::unordered_set<inet_address>>).

    To speed up the token to pending endpoint mapping search, a interval map
    is introduced. It is faster than searching the map linearly and can
    avoid caching the token/pending endpoint mapping.

    With this patch, the operations per second drop during adding node
    period gets much better.

    Before:
    45K to 10K

    After:
    45k to 38K

    (The number is measured with the streaming code skipping to send data to
    rule out the streaming factor.)

    Refs: #1223
```
