### ISSUE TITLE
performance degradation when shrinking cluster

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#1224]
What we did in the test:
1) Start a 5 node cluster
2) Start cassandra-stress on the loader node
3) Decommission a node
4) Keep repeating 3) until we get to the target number of 3 nodes

Loader node: 'cassandra-stress write cl=QUORUM duration=16m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=1000 -node 172.30.0.171'
DB nodes: from 5 nodes to 3 nodes
Scylla commit: 4ed702f0dae7317b1bb5c8b31aea0df6613bafd0
Instances: c3.large
Results: Check the svg graph in the attached zip file for the ops/latency number for c-s output during the test, we have huge drop when nodes are decommissioned.

[job-2016-04-26T04.32-e4732fb.zip](https://github.com/scylladb/scylla/files/240143/job-2016-04-26T04.32-e4732fb.zip)

**Comment by nosideeffects** [comment]
Just to clarify - do you mean per-node throughput drops?

**Comment by asias** [comment]
@nosideeffects Yes, the drop is due the extra streaming work during the decommission operation period.  Of course when the cluster shrinks from 5 nodes to 3 nodes, the total ops would go down since there are less nodes in the cluster. The ops goes this way:  5 nodes 35K -> decommission in flight 10K -> 4 nodes 30K -> decommission in flight 10K -> 3 nodes 25K.

**Comment by avikivity** [comment]
Is it due to cpu or I/O load?

One way to check is to restrict I/O (maybe by using --max-io-requests=1), so we're I/O bound.  In that case the I/O scheduler should prevent streaming from overwhelming I/O.

**Comment by lmr** [comment]
![node hj-test-long-scylla-loader-node-882dc319-1 52 91 98 68 172 30 0 103 seed none -lat svg](https://cloud.githubusercontent.com/assets/296807/15030236/806289c2-1227-11e6-9b87-ea88493d65b3.png)

**Comment by lmr** [comment]
![node hj-test-long-scylla-loader-node-882dc319-1 52 91 98 68 172 30 0 103 seed none -ops svg](https://cloud.githubusercontent.com/assets/296807/15030242/87561df2-1227-11e6-868c-a4d753151a02.png)

**Comment by lmr** [comment]
I've saved the generated svgs into pngs and put them here for easy reference. The graphs show the drop in performance and the latency peaks quite nicely.

**Comment by tzach** [comment]
@asias did your patch solve the issue?

**Comment by asias** [comment]
yes, it does.

**Comment by tzach** [comment]
@asias, great!
Which commit and is it in 1.2?

**Comment by asias** [comment]
On Tue, Jun 7, 2016 at 7:44 PM, Tzach Livyatan <notifications@github.com>
wrote:

> @asias <https://github.com/asias>, great!
> Which commit and is it in 1.2?
>
Yup, it is in 1.2.

commit 089734474bc49de43ae250b28ed2ed2c67fd8235
Author: Asias He <asias@scylladb.com>
Date:   Tue May 17 17:31:55 2016 +0800

    token_metadata: Speed up pending_endpoints_for


> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scylladb/scylla/issues/1224#issuecomment-224256107>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AATiTNKaytayANEB02irVIW8gyESX25Iks5qJVmjgaJpZM4IRtgr>
> .
>



-- 
Asias
