### ISSUE TITLE
Implement estimate_result_rows_per_range to have better performance for range queries

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#1230]
Scylla version (or git commit hash): ae95ce1bd73d6f9d4a6c5fa3aac51d89b48a337c

Currently we assumes 1 row per range, if there are more we will bring to much data, if less we will have to request several times.

**Comment by avikivity** [comment]
I don't trust the estimator with small tables. In particular, it estimates partitions, not rows or bytes. We need to fetch 1 MB, not a specific number of rows.

**Comment by avikivity** [comment]
Will `concurrency_factor *= 2;` in the recursive call (do we not have `repeat_until_value()`) fix this?

**Comment by gleb-cloudius** [comment]
On Tue, Sep 12, 2017 at 03:46:55PM +0000, Avi Kivity wrote:
> Will `concurrency_factor *= 2;` in the recursive call (do we not have `repeat_until_value()`) fix this?
> 
I think it would (if you prefer it over estimate_result_rows_per_range
implementation). It can overshoot considerably though, no?

--
			Gleb.

**Comment by avikivity** [comment]
Worst case is by a factor of two if the distribution is uniform.

If it is not uniform, then the worst case is nr_nodes * page_size of data.

Of course, non-uniform distribution breaks estimation too.
