### ISSUE TITLE
Scylla Docker to support versions

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1233]
Docker images support versions
for example

```
docker run grafana/grafana:2.6.0
```
Scylla docker image should support the same

**Comment by penberg** [comment]
So did you try it out? What's the problem. We tag our Docker images https://hub.docker.com/r/scylladb/scylla/tags/ so it should work already.

**Comment by tzach** [comment]
It work perfectly
Had a docker issue on my machine.
