### ISSUE TITLE
DTEST repair_additional_test.py:RepairAdditionalTest.repair_kill_2_test failing (regression)

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1236]
export SCYLLA_EXT_OPTS="--smp 1" ; reset ; pkill -9 scylla; pkill -9 java; rm -Rf ~/.dtest/*; export CASSANDRA_DIR=~/scylla; REUSE_CLUSTER=false KEEP_TEST_DIR=true DEBUG=true PRINT_DEBUG=true nosetests -v -s repair_additional_test.py:RepairAdditionalTest.repair_kill_2_test

the test passes with head

commit 122330a5ebffd07eecef18447bc0f49585751ace
Author: Takuya ASADA <syuu@scylladb.com>
Date:   Thu Apr 14 19:32:34 2016 +0000

    dist/common/scripts: add interactive prompt for package installation check, also check scylla-tools installed
    
    Currently scylla_setup is unusable when user does not want to install scylla-jmx because it checks package unconditionally, but some users (or developers) does not want to install it, so let's ask to skip check or not on interactive prompt.
    
    Also, scylla-tools package should installed for most of the case, added check code for the package.
    
    Signed-off-by: Takuya ASADA <syuu@scylladb.com>
    Message-Id: <1460662354-10221-1-git-send-email-syuu@scylladb.com>

does not pass with

commit dc69999fd8955b96d0fe9dceafec3e8d12a27cee
Author: Avi Kivity <avi@scylladb.com>
Date:   Mon May 2 11:10:33 2016 +0300

    Merge seastar upstream
    
    * seastar dab58e4...e536555 (5):
      > rpc: introduce outgoing packet queue
      > Add condition variable implementation.
      > future-utils: support futures with multiple values in map_reduce
      > tests: rpc: stop client and server
      > tls_test: Add test for large-ish buffer send/recieve

the test itself kills a node while repair is running.

**Comment by gleb-cloudius** [comment]
Master node does not move repair into FAILED state after slave node is killed.
