### ISSUE TITLE
can not run nodetool - output is "Cassandra 2.0 and later require Java 7u25 or later - jdk 101"

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1237]
Running nodetool on machine with jdk 101 or later failes

same as https://issues.apache.org/jira/browse/CASSANDRA-11661

**Comment by slivne** [comment]
this was fixed in 2.1 https://github.com/apache/cassandra/commit/5202147d9f4077afe6ac185654fa153c7fbd6f95 we need to backport this

**Comment by slivne** [comment]
we can not release 1.0.3 / 1.1 without fixing this - our sanity testers fail

**Comment by avikivity** [comment]
Fixed by https://github.com/scylladb/scylla-tools-java/commit/d3b08e43051a50dab4d5f4bcdbe9a78ce6f3ad74
