### ISSUE TITLE
Cannot rejoin node after decommissioning - cassandra.override_decommission=true does not work

### ISSUE THREAD

**Issue by Freeaqingme** [scylladb/scylla#1240]
## Installation details
Scylla version (or git commit hash): 666.development-20160504.f1cd52f-ubuntu1
Cluster size: ~5 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Linux node2 4.4.0-21-generic #37~14.04.1-Ubuntu SMP Wed Apr 20 16:33:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

I ran '''nodetool decommission''', but then wanted it to join the node again. In my logs:
```
May  9 00:09:13 node3.nl scylla[2546]:  [shard 0] storage_service - Loading persisted ring state
May  9 00:09:13 node3.nl scylla[2546]:  [shard 0] storage_service - This node was decommissioned and will not rejoin the ring unless cassandra.override_decommission=true has been set,or all existing data is removed and the node is bootstrapped again
```

Adding this line to the config, scylla.yaml, but nothing changes:
```
cassandra.override_decommission: true
```

(I will just destroy all data, but figured it could be worth mentioning)

**Comment by penberg** [comment]
Ping @asias

**Comment by asias** [comment]
We should put 

    override_decommission: true

instead of 
  
   cassandra.override_decommission: true
   
in the scylla.yaml.

db/config.hh:722:    val(override_decommission, bool, false, Used, "Set true to force a decommissioned node to join the cluster") \

**Comment by slivne** [comment]
@asias

is the log correct

May  9 00:09:13 node3.nl scylla[2546]:  [shard 0] storage_service -
This node was decommissioned and will not rejoin the ring unless
cassandra.override_decommission=true has been set,or all existing data
is removed and the node is bootstrapped again

it instructted in setting the cassandra.override_decommission - will
this work in the command line ?

**Comment by asias** [comment]
The current log is following Cassandra.

I think we should make it "override_decommission=true" in the log. 

The command line usage is:

--override-decommission false/true

**Comment by slivne** [comment]
@asias thanks ... lets open a bug for this - and verify if we have other
cases
doing a simple grep shows others

```
./dht/byte_ordered_partitioner.cc
            throw std::runtime_error(sprint("A node required to move the
data consistently is down (%s).  If you wish to move the data from a
potentially inconsistent replica, restart the node with
-Dcassandra.consistent.rangemovement=false", source_ip));
            auto msg = sstring("This node was decommissioned and will not
rejoin the ring unless cassandra.override_decommission=true has been set,"
         throw std::runtime_error("Replace method removed; use
cassandra.replace_address instead");
                throw std::runtime_error("Other
bootstrapping/leaving/moving nodes detected, cannot bootstrap while
cassandra.consistent.rangemovement is true");
                    "Use cassandra.replace_address if you want to replace
this node.", addr));
                            throw std::runtime_error("Other
bootstrapping/leaving/moving nodes detected, cannot bootstrap while
cassandra.consistent.rangemovement is true (check_for_endpoint_collision)");
                        throw std::runtime_error(sprint("A node required to
move the data consistently is down (%s).  If you wish to move the data from
a potentially inconsistent replica, restart the node with
-Dcassandra.consistent.rangemovement=false", source_ip));
./service/storage_service.cc
                logger.warn("Gossip not settled but startup forced by
cassandra.skip_wait_for_gossip_to_settle.", total_polls);
./gms/gossiper.cc
```

I guess there may be others

**Comment by asias** [comment]
Btw, I think we should be less strict about the '-'  and '_' when parsing
the command option. E.g., --override-decommission
and --override_decommission should both work.

On Mon, May 9, 2016 at 2:48 PM, Shlomi Livne <notifications@github.com>
wrote:

> @asias thanks ... lets open a bug for this - and verify if we have other
> cases
> doing a simple grep shows others
>
> ```
> ./dht/byte_ordered_partitioner.cc
> throw std::runtime_error(sprint("A node required to move the
> data consistently is down (%s). If you wish to move the data from a
> potentially inconsistent replica, restart the node with
> -Dcassandra.consistent.rangemovement=false", source_ip));
> auto msg = sstring("This node was decommissioned and will not
> rejoin the ring unless cassandra.override_decommission=true has been set,"
> throw std::runtime_error("Replace method removed; use
> cassandra.replace_address instead");
> throw std::runtime_error("Other
> bootstrapping/leaving/moving nodes detected, cannot bootstrap while
> cassandra.consistent.rangemovement is true");
> "Use cassandra.replace_address if you want to replace
> this node.", addr));
> throw std::runtime_error("Other
> bootstrapping/leaving/moving nodes detected, cannot bootstrap while
> cassandra.consistent.rangemovement is true
> (check_for_endpoint_collision)");
> throw std::runtime_error(sprint("A node required to
> move the data consistently is down (%s). If you wish to move the data from
> a potentially inconsistent replica, restart the node with
> -Dcassandra.consistent.rangemovement=false", source_ip));
> ./service/storage_service.cc
> logger.warn("Gossip not settled but startup forced by
> cassandra.skip_wait_for_gossip_to_settle.", total_polls);
> ./gms/gossiper.cc
> ```
>
> I guess there may be others
>
> On Mon, May 9, 2016 at 9:41 AM, Asias He <notifications@github.com> wrote:
>
> > The current log is following Cassandra.
> >
> > I think we should make it "override_decommission=true" in the log.
> >
> > The command line usage is:
> >
> > --override-decommission false/true
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/scylladb/scylla/issues/1240#issuecomment-217787149>
>
> >
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/1240#issuecomment-217788042>
>



-- 
Asias

**Comment by Freeaqingme** [comment]
> Btw, I think we should be less strict about the '-'  and '_' when parsing the command option. E.g., --override-decommission and --override_decommission should both work.

Why? Personally I can imagine people are more likely to get confused by this; "I'm see both getting used. Which one is right?"

Personally, I'd say we should just have one option, but you could git style perhaps?
```
git statuss
git: 'statuss' is not a git command. See 'git --help'.

Did you mean this?
	status
```

**Comment by asias** [comment]
Because in scylla.yaml the syntax is:

override_decommission: true

However, in the scylla cmd line, the syntax is:

--override-decommission true

I meant to make the cmd line usage accept syntax in scylla.yaml.

**Comment by tzach** [comment]
> I think we should be less strict about the '-'  and '_' when parsing

I agree with @Freeaqingme on this point
We should have one format for the cmd line. Supporting two syntaxes is harder to maintain.

In YAML it is more natural to use '_' and ':' 
In cmd it is more natural to use '-' and space

As long as it well documented I do not think its an issue.

**Comment by slivne** [comment]
@asias is there anything left to fix for this - or can we close it ?

**Comment by asias** [comment]
First, override_decommission option works in Scylla. However, Scylla prints the same log as Cassandra does:

"This node was decommissioned and will not rejoin the ring unless cassandra.override_decommission=true has been set"

So, user tries to specify cassandra.override_decommission=true option in scylla.yaml which should be "override_decommission: true". 

If it is fine to break the log compatibility with c*, e.g., dtest check specific logs, I can cook a patch to modify the scylla log to print the correct option for scylla.yaml.

**Comment by penberg** [comment]
@asias It's obviously fine to fix our logging to match our behavior :wink:. So please send a patch.

**Comment by asias** [comment]
Ok. Makes sense. We can adapt dtest if needed.
