### ISSUE TITLE
repair: need a method to monitor progress

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1244]
nodetool netstats does provide some information that repair is progressing but it is not providing any info on how much is left to be completed

**Comment by dorlaor** [comment]
A good estimate will use the information about the keyspaces/tables,
calculate
the size of the sstables (it's an estimate since we send just the new data)
and
rate of the recent repaired segments. Something like:
  - repaired 100GB out of 1TB (10%)
  - 3600 seconds left

**Comment by slivne** [comment]
in progress

**Comment by asias** [comment]
Current repair reports in the log X out of Y ranges are being repaired. It is not perfect but it indeed shows the progress.

e.g.,

INFO  2018-01-22 09:21:53,563 [shard 0] repair - Repair 20 out of 256 ranges, id=1, shard=0, keyspace=ks3, table={mytable, standard1}, range=(-inf, -5452223567049118319]

**Comment by tzach** [comment]
Dup with #2456
