### ISSUE TITLE
scylla_io_setup uses hardcoded evaluation directory

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla#1246]
The RHEL install has a script with iotune command list hardcoded to /var/lib/scylla.

I have my scylla home at /scylladb which fails even when properly set in /etc/sysconfig/scylla-server.

Perhaps SCYLLA_HOME can be used as it is injected from sysconfig already?

**Comment by dahankzter** [comment]
After switching to /scylladb in the script it works fine.

'Written the above values to /etc/scylla.d/io.conf'

**Comment by slivne** [comment]
Henrik thanks

We are working to fix this https://github.com/scylladb/scylla/issues/1167

**Comment by dahankzter** [comment]
There are other places as well for example the systemd service scripts:

[Unit]
Description=Scylla Server

[Service]
Type=notify
LimitMEMLOCK=infinity
LimitNOFILE=200000
LimitAS=infinity
LimitNPROC=8096
WorkingDirectory=/var/lib/scylla
Environment="HOME=/var/lib/scylla"
EnvironmentFile=/etc/sysconfig/scylla-server
EnvironmentFile=/etc/scylla.d/*.conf
ExecStartPre=/usr/bin/sudo -E /usr/lib/scylla/scylla_prepare
ExecStart=/usr/bin/scylla $SCYLLA_ARGS $SEASTAR_IO $DEV_MODE
ExecStopPost=/usr/bin/sudo -E /usr/lib/scylla/scylla_stop
TimeoutStartSec=900
KillMode=process
Restart=on-abnormal
User=scylla

[Install]
WantedBy=multi-user.target
/usr/lib/systemd/system/scylla-server.service (END)

**Comment by syuu1228** [comment]
This is duplicated with https://github.com/scylladb/scylla/issues/1167, and it fixed.
Hardcoded systemd unit file also fixed at https://github.com/scylladb/scylla/commit/8503600e30b6b0a1b592e9954b961db2bcf8686e.
So this can be close.

**Comment by dahankzter** [comment]
Will this go out as an update on the stable releases? Specifically the RHEL
repo?

**Comment by slivne** [comment]
it is part of 1.2 - also available in 1.2.rc1
