### ISSUE TITLE
Install on RHEL with scylla uid < 1000 fails

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla#1248]
## Installation details

Scylla version (or git commit hash): Latest from the RHEL repo

Apparently there is some sort of problem with uids < 1000.
Perhaps it is our setup but I think it is vanilla RHEL 7.

**Comment by avikivity** [comment]
Can you elaborate? service uids are usually < 1000.

**Comment by dahankzter** [comment]
Hmm yes my install had 996 but then I got an error in journalct:

pam_succeed_if(su-l:auth): requirement "uid >= 1000" not met by user "root"

Changing uid to 1001 made that particular permission error go away.

I try to start the service like this:

sudo systemctl start scylla-server.service

**Comment by avikivity** [comment]
The problem is that we went through pam here.  I wonder what that was.

@syuu1228

**Comment by dahankzter** [comment]
I am about to install in our production setup soon. I will try to record any problems in some more details this time. There was as I remember some hard coded paths as well aside from the permissions.

**Comment by syuu1228** [comment]
I tried to install scylla-server-1.0.3 on RHEL7/EC2, uid of scylla was 995, but never get pam error, able to start scylla without error.

**Comment by dahankzter** [comment]
Ah ok. Ill speak with Ops and check if they have some special policies etc.
I know they have custom sudo policy in place.

Just to make sure. That RHEL is the latest stable vanilla config?

**Comment by syuu1228** [comment]
@dahankzter It was latest, but it's on EC2 official image, so it may customized little bit to running on EC2.
I think they won't change pam setting since it's not related to EC2, but to make sure scylla can run vanilla RHEL7, we should try RHEL7 on local instances too.

**Comment by slivne** [comment]
@dahankzter any update on this ?

**Comment by dahankzter** [comment]
No I am afraid not. Ill make it a priority to ask about it. Sorry for the
delay. It still happened on the prod server installs.

tis 7 juni 2016 kl 11:49 skrev Shlomi Livne <notifications@github.com>:

**Comment by slivne** [comment]
@syuu1228 can you please check what other products do to overcome this - do they specify that the installed user id should be higher than 1000

**Comment by dahankzter** [comment]
I am happy to report that this no longer happens on our RHEL 7.3 with Scylla 1.5.
Close?
