### ISSUE TITLE
Auth fail for start script on RHEL tries to preserve environment when executing pre/post scripts

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla#1249]
## Installation details
Scylla version (or git commit hash): Latest from the RHEL repo

Start script uses 'sudo -E ....' which seems to not be allowed on RHEL 7.

**Comment by dahankzter** [comment]
Just removing 'sudo -E ' makes it start for me but I have no idea of the implications

**Comment by syuu1228** [comment]
I had a patch to removing "sudo -E", re-sent on mailing list ([PATCH scylla v4] dist: drop 'sudo -E' and SETENV for security reason, source envfile from scripts).
