### ISSUE TITLE
Reduce latency of LOCAL_* read repair

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1250]
*Installation details*
Scylla version (or git commit hash): 28cc6f97af255be303197ccef210a90d9b0a0861

A read repair of a LOCAL_QUORUM (or similar) query can result in a global latency being injected into the query; given that the user specified LOCAL, they probably don't do this.

We can probably do better, by applying the following algorithm:

- when a digest mismatch is detected, send read queries to ALL
- when responses from LOCAL_ALL arrive, merge the results and write back to LOCAL_ALL
- when the LOCAL_ALL write returns, return a result (continuing with ALL - LOCAL_ALL repair asynchronously)
- when all responses from ALL arrive, merge the results and write back to (ALL - LOCAL_ALL)

(I used LOCAL_ALL here for: all replicas in the local data center)

Note: under load, we may have to convert the asynchronous portion to be synchronous.

I think this maintains read monotonicity.

**Comment by avikivity** [comment]
@gleb-cloudius, @tgrabiec

**Comment by slivne** [comment]
- when all responses from ALL arrive, merge the results and write back
   to (ALL - LOCAL_ALL)

wouldn't it make more sense to write the merged result back to ALL (the
result of LOCAL_ALL may not be the "correct" one)

**Comment by gleb-cloudius** [comment]
On Mon, May 09, 2016 at 05:00:45AM -0700, Avi Kivity wrote:
> *Installation details*
> Scylla version (or git commit hash): 28cc6f97af255be303197ccef210a90d9b0a0861
> 
> A read repair of a LOCAL_QUORUM (or similar) query can result in a global latency being injected into the query; given that the user specified LOCAL, they probably don't do this.
> 
> We can probably do better, by applying the following algorithm:
> 
> - when a digest mismatch is detected, send read queries to ALL
> - when responses from LOCAL arrive, merge the results and write back to LOCAL_ALL
How do you know the result is up-to-date? The new data can be in other
dc.

> - when the LOCAL_ALL write returns, return a result (continuing with ALL - LOCAL_ALL repair asynchronously)
> - when all responses from ALL arrive, merge the results and write back to (ALL - LOCAL_ALL)
> 
> Note: under load, we may have to convert the asynchronous portion to be synchronous.
> 
> I think this maintains read monotonicity.
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/scylladb/scylla/issues/1250

--
			Gleb.

**Comment by avikivity** [comment]
Right.  Maybe do it conditionally.

Updated algorithm:

- when a digest mismatch is detected, send read queries to (ALL - nodes_that_have_already_returned_a_response)
- when responses from LOCAL_ALL arrive, merge the results and write back to LOCAL_ALL
- when the LOCAL_ALL write returns, return a result (continuing with ALL - LOCAL_ALL repair asynchronously)
- when all responses from ALL arrive, merge the results and write back to ALL (if the responses from (ALL - LOCAL_ALL) did not change the result, can write back to (ALL - LOCAL_ALL)

Note: we can send just the mutation diff; if the diff is null, no need to send anything.

**Comment by avikivity** [comment]
@gleb-cloudius you don't know, but you also don't know it if read repair did not happen. Doing it asynchronously doesn't change any guarantees.

The algorithm tries to keep latency to local-dc, but retain monotonic read guarantees.

**Comment by gleb-cloudius** [comment]
On Mon, May 09, 2016 at 05:11:00AM -0700, Avi Kivity wrote:
> @gleb-cloudius you don't know, but you also don't know it if read repair did not happen. Doing it asynchronously doesn't change any guarantees.
> 
It does if you expect read monolicity cross DC.

> The algorithm tries to keep latency to local-dc, but retain monotonic read guarantees.
> 
It fail to do so cross DC. If you do not interested in later why not
configure only local-dc and set cross dc chance to none or very small
one?

--
			Gleb.

**Comment by avikivity** [comment]
We are interested in cross-DC repair, otherwise data centers would drift apart (at least until the next full repair).  The question is whether cross-DC read monotonicity id a requirement or not.

**Comment by gleb-cloudius** [comment]
On Mon, May 09, 2016 at 06:11:00AM -0700, Avi Kivity wrote:
> We are interested in cross-DC repair, otherwise data centers would drift apart (at least until the next full repair).
You can still enable it, but with less probability than local repair.
Or we can add some kind of corss DC repair that runs in a background and
does not affect latencies of individual reads directly.

> The question is whether cross-DC read monotonicity id a requirement or not.
> 
Just like local read monotonicity it was never a part of C* concept and
was added at some later point and is an implementation detail now that
some users may rely on without even realizing. We will never know.

I do not think this is the only question though. Implementing the
algorithm you propose means that reconciliation will have to be done
twice and write to local DC will happen twice (if data happen to be
different, but lets assume it is since otherwise repair does not take
much time as it is), so it adds quite an overhead.

--
			Gleb.

**Comment by avikivity** [comment]
The probability of read repair needing to do *any* work is low, so the extra overhead won't impact throughput significantly.

**Comment by gleb-cloudius** [comment]
On Thu, May 19, 2016 at 06:51:29AM -0700, Avi Kivity wrote:
> The probability of read repair needing to do *any* work is low, so the extra overhead won't impact throughput significantly.
> 
Then we wouldn't have seen the problem in the fist place, but we do see
that repair happens.

--
			Gleb.

**Comment by avikivity** [comment]
The problem is not throughput, but latency.  If just 1% of reads need read repair, then 99th percentile latency will be huge, but throughput will be reduced by less than 1%.

**Comment by gleb-cloudius** [comment]
On Thu, May 19, 2016 at 07:44:08AM -0700, Avi Kivity wrote:
> The problem is not throughput, but latency.  If just 1% of reads need read repair, then 99th percentile latency will be huge, but throughput will be reduced by less than 1%.
> 
Depending on how loaded servers are. We account for background activity
and stop moving requests into background if there is to much of it.
Multiplying background work may cause latencies to grow for unrelated
requests.

Anyway I have much better and simple idea to fix the problem we see:
if non matching data is newer than write_timeout do local only repair
instead of global one. This will eliminate global repairs due to read
after write.

--
			Gleb.

**Comment by avikivity** [comment]
Your idea is good and will fix most of the problems.  There may yet by high latencies due to genuine inconsistencies, but those may be too rare to matter.

We can start with your idea and reevaluate the need for a more complete solution later.

**Comment by slivne** [comment]
@gleb-cloudius - how can you know of _if non matching data is newer than write_timeout do local only repair_ ? will you submit a read and then based on the response not wait for the answers or will you wait for the local dc answers check the timestamp and only then submit the request to the other DCs ?

**Comment by gleb-cloudius** [comment]
On Sat, May 21, 2016 at 09:54:43PM -0700, Shlomi Livne wrote:
> @gleb-cloudius - how can you know of _if non matching data is newer than write_timeout do local only repair_ ? will you submit a read and then based on the response not wait for the answers or will you wait for the local dc answers check the timestamp and only then submit the request to the other DCs ?
> 
I will do a good approximation of it. I will calculate latest timestamp
of a data included in digest and if digest does not match and latest
timestamp is newer then write_timeout and CL=LOCAL_ then I will repair
only locally.

--
			Gleb.

**Comment by tzach** [comment]
@gleb-cloudius whats the status of this issue?

**Comment by gleb-cloudius** [comment]
On Tue, Jun 07, 2016 at 01:33:14AM -0700, Tzach Livyatan wrote:
> @gleb-cloudius whats the status of this issue?
> 
The solution I proposed is committed.

--
			Gleb.
