### ISSUE TITLE
Read timeout - need advice

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla#1251]
## Installation details
Scylla version (or git commit hash): Latest from RHEL repo

select count(*) from IdMap where opid=10305;

This yields:
OperationTimedOut: errors={}, last_host=.......

There can be up to maybe a milion of these and perhaps not weird at all since a count really need to count things. However we see this from application code as well that uses where clauses and seemingly correct indexes.

The problem is I have not a clue even where to start reading about this type of problems.
Any help would be appreciated.

**Comment by avikivity** [comment]
This type of query is not well supported by Scylla (and Cassandra).  Since the table is distributed across many nodes, there is no central place to keep a count of all partitions.  The only fix is to adjust the query timeout (and note, that such a query will result in a lot of I/O).

Well supported queries are those that select a single partition or a small number of partitions:

    SELECT * FROM tab WHERE id = ?

    SELECT * FROM tab WHERE id IN ?

**Comment by dahankzter** [comment]
Yes that was a bad example and not something our code uses but something I
just used in cqlsh. We do basically only queries of the kind you listed. I
don't have access to the logs currently.

The load on Scylla doesn't seem extreme.
Any idea of how check further? I would prefer not to throttle at the client
side. There are only two nodes in the cluster and the data is literally 3
fields two longs and one string.

Thx,

**Comment by avikivity** [comment]
Do you mean that single-partition queries time out?

**Comment by dahankzter** [comment]
Now that you mention it I am unsure if it wasn't the writes that timed out.
I'll read through the app logs again to make sure.
Does scylladb log this? It should be possible to see in journalctl right or
is there a log level that needs setting?

**Comment by avikivity** [comment]
Latencies are not logged, but `nodetool cfhistograms` measures both read and write latencies.

**Comment by dahankzter** [comment]
Actually the timeouts seems to be on write rather than reads.

**Comment by dahankzter** [comment]
Nodetool actually shows high read latencies:

nodetool -p 7199 cfhistograms idmapservice idmap
idmapservice/idmap histograms
Percentile  SSTables     Write Latency      Read Latency    Partition Size        Cell Count
                              (micros)          (micros)           (bytes)
50%             0.00              5.00             29.00             73457              2299
75%             0.00             20.00        4055269.00           2346799             61214
95%             0.00             29.00       12108970.00          12108970            315852
98%             0.00             29.00       25109160.00          12108970            315852
99%             0.00             29.00       25109160.00          12108970            315852
Min             0.00              2.00              3.00              2300                61
Max             0.00             50.00       25109160.00          12108970            315852

I am not fully understanding what is really measured here. Is it the time last byte written or some query execution time? We have queries that returns a large data set but I didn't expect it to render the server non-responsive.

Can you give me a hint as to what to check? 

Iperf reveals 9.73 Gbits/sec between the peers and dd gives: 10737418240 bytes (11 GB) copied, 13.303 s, 807 MB/s.
Other than that I am not sure how what to check?
Any ideas where to look or what config to experiment with? Anything else I can measure?

Servers are modest 6 cores on some fairly new vmware setup with 16 Gb ram of which Scylla grabs most of it right away.

I ran the script to generate settings at /etc/scylla.d/io.conf and it gives:
SEASTAR_IO="--max-io-requests=99"

High or?

**Comment by dahankzter** [comment]
So I made a change in our table structure and I see this:

> nodetool -p 7199 cfhistograms idmapservice idmap
idmapservice/idmap histograms
Percentile  SSTables     Write Latency      Read Latency    Partition Size        Cell Count
                              (micros)          (micros)           (bytes)
50%             0.00             24.00             35.00               179                 4
75%             0.00             29.00             42.00               258                 6
95%             0.00             50.00             72.00               446                10
98%             0.00             60.00            103.00               446                10
99%             0.00             72.00            124.00               446                10
Min             0.00              2.00              3.00                87                 2
Max             0.00            924.00           9887.00               535                12

But I cannot really explain why it is so much better, perhaps you can?

I had the table like this:

`create table T (
   k1 bigint,
   k2 varchar,
   data bigint,
   PRIMARY KEY(k1,k2)
)`

Which I then changed to 


`create table T (
   k1 bigint,
   k2 varchar,
   data bigint,
   PRIMARY KEY(k2,k1)
)`

Essentially switching the partition key if I understand it correctly?
The k1 field is a field that we search on to generate quite large lists like:
`select * from T where k1=12313`

Can this explain the behaviour or am seeing something else?

**Comment by avikivity** [comment]
If k1 has low cardinality and k2 has high cardinality (few distinct k1 values, many distinct k2 values) then this can be explained.  Is this the case?

**Comment by dahankzter** [comment]
Few distinct k1 and ~2 million distinct k2

**Comment by dahankzter** [comment]
It worked better but I decided to simply create new column families as needed for the low cardinality fields. This allows us to completely skip any filtering at the mental code cost of having to create the needed tables on the fly. Not hard but still a little fiddling.

Will this cause any other by me unknown issues down the line?

**Comment by avikivity** [comment]
If the number of new tables is unbounded, performance will drop over time.  What is the expected number of new tables?

**Comment by dahankzter** [comment]
They are manually manageable in number. I just created them on the fly to
avoid the manual maintenance.
Perhaps a couple of dozen or so, is that manageable?

**Comment by avikivity** [comment]
That should not be a problem.

**Comment by dahankzter** [comment]
Thank you!
