### ISSUE TITLE
prevent old version node to join a new version cluster

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#1253]
Take RANGE_TOMBSTONES for example:

old version: node1, node2, node3
 -> upgrade 
all new version: node1, node2, node3

Now all the node see the RANGE_TOMBSTONES bits and start sending new formats

Somehow, the admin added a new node4 with old version (or restarted
node3 with a old scylla binary)

mixed old and new version: node1, node2, node3, node4

**Comment by asias** [comment]
some ideas:

We can do the checking:

When a node starts up, in gossip shadow round, it can get all the
supported features of existing nodes.
if there are features this node does not know this node should stop joining.

For the existing node, when it sees a the join node, if the joining
node has less features than itself, the existing node should not
adding the new node to the pending node list.

**Comment by tzach** [comment]
@asias any progress on this?

**Comment by asias** [comment]
@tzach I haven't started to work on this item. Duarte's [PATCH scylla v9 00/18] Store range tombstones in internal representation series is not merged yet and it is not in 1.2 yet, of course. It is the first user of the gossip features. @slivne please decide if I should work on this item now.

**Comment by slivne** [comment]
@asias - is there anything else pending for you to respond on the add/node decomission node performance case - if not lets work on this.

**Comment by tgrabiec** [comment]
@asias Duarte's series was merged a few days ago - 57413618e80e2c9b59184756be1f2c3ccc87bf14

**Comment by asias** [comment]
@tgrabiec thanks. so it is merged in master and it is not in 1.2 branch.

**Comment by tzach** [comment]
@tgrabiec  @slivne can we close this?

**Comment by asias** [comment]
The patch set for this issue is not merged yet.

[PATCH scylla 0/2] Prevent old node to join new cluster

On Tue, Jun 21, 2016 at 10:45 PM, Tzach Livyatan <notifications@github.com>
wrote:

> @tgrabiec <https://github.com/tgrabiec> @slivne
> <https://github.com/slivne> can we close this?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/scylladb/scylla/issues/1253#issuecomment-227462856>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AATiTEhsaIFf4jljHaOIvnsd4wYNW12Hks5qN_kjgaJpZM4Ia4iW>
> .
>



-- 
Asias
