### ISSUE TITLE
alter table changes are not reflected immediatly

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1255]
## Installation details
Scylla version (or git commit hash): 1.0.3

1. create a cluster of 3 nodes
2. enable --experimental 1
3. populate data with c-s (rf=3 cl=all
4. run a read workload with cl=one
5. check that read_reapir attempts is incremented 
```
curl -X GET --header "Accept: application/json" "http://127.0.0.1:10000/storage_proxy/read_repair_attempted"
sleep 10
curl -X GET --header "Accept: application/json" "http://127.0.0.1:10000/storage_proxy/read_repair_attempted"
```
6. alter table changing the read_repair_chance and dclocal_read_repair_chance to 0.0
7. check that read_repair attempts is still incremented

**Comment by slivne** [comment]
to work around this a restart can be done

**Comment by avikivity** [comment]
We are probably caching the schema_ptr in the prepared statement

**Comment by penberg** [comment]
@avikivity Prepared statements should be invalidated when a column family is changed as per ``query_processor::migration_subscriber::on_update_column_family``.

**Comment by avikivity** [comment]
Which say

```
void query_processor::migration_subscriber::on_update_column_family(const sstring& ks_name, const sstring& cf_name, bool columns_changed)
{
    if (columns_changed) {
        log.info("Column definitions for {}.{} changed, invalidating related prepared statements", ks_name, cf_name);
        remove_invalid_prepared_statements(ks_name, cf_name);
    }
}
```

but `!columns_changed`, so nothing was done.  Only the read repair parameters were changed.

**Comment by penberg** [comment]
@avikivity Aah, right you are. Ping @tgrabiec

**Comment by avikivity** [comment]
I think the fix is simple, change the conditional to always run, and drop all prepared statements unconditionally.  It's safer than filtering for what needs to change and missing some of them.

The client will re-prepare any valid statements.

**Comment by tgrabiec** [comment]
We inherited the check from Cassandra. I agree it's safer to always invalidate.
