### ISSUE TITLE
CREATE TABLE with min_threshold does not work

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#1257]
```
CREATE KEYSPACE ks1 WITH replication={ 'class' : 'SimpleStrategy', 'replication_factor' : 1 };

CREATE TABLE ks1.cf1 (a int PRIMARY KEY, b int) WITH compaction = { 'class' : 'SizeTieredCompactionStrategy', 'min_threshold' : 7 };

SELECT columnfamily_name, min_compaction_threshold FROM system.schema_columnfamilies WHERE keyspace_name='ks1' ;

columnfamily_name | min_compaction_threshold
-------------------+--------------------------
               cf1 |                        4

```
Somehow we loose the min threshold value. Looking at the code seems ok, but obviously not...

**Comment by horschi** [comment]
min_threshold still does not seem to work. I can see it changing in the schema works fine, but compactions do not seem to honor the threshold at all.

**Comment by glommer** [comment]
That is expected.

Since Scylla 2.3 Compactions are calculated automatically and this
parameter is ignored.

We have added a flag to honor to legacy behavior if you so want,  but by
default it will not

**Comment by horschi** [comment]
@glommer : I could only find "compaction_static_shares" in the 2.2 changelog (https://www.scylladb.com/2018/07/09/scylla-release-2-2/, size tiered was changed in ver 2.2), which seems to be doing something else.

Scylla seems to be compacting a lot, it would be nice if the min_threshold setting could be adjusted.

**Comment by glommer** [comment]
Option should be compaction_enforce_min_threshold

**Comment by horschi** [comment]
@glommer the setting make scylla compact like expected. With it enabled I do not see timeouts in test environment (single shard scylla on a small VM).
