### ISSUE TITLE
scylla dumped core 

### ISSUE THREAD

**Issue by psuriset** [scylladb/scylla#1266]
## Installation details
Scylla version (or git commit hash):

scylla-server-1.0.3-20160506.6c4d722.el7.centos.x86_64

Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):
rhel
## Hardware details (for performance issues)
VM
Platform (physical/VM/cloud instance type/docker):
VM
Hardware: sockets= cores= hyperthreading= memory=

4 vcpu, 4G mem

Disks: (SSD/HDD, count)
HDD 

Fails to start scylladb. It dumps core 

- Unit scylla-server.service has begun starting up.
May 17 05:26:07 virbr0-32-87 sudo[4092]:   scylla : TTY=unknown ; PWD=/var/lib/scylla ; USER=root ; COMMAND=/usr/lib/scylla/scylla_prepare
May 17 05:26:07 virbr0-32-87 scylla[4095]: scylla: core/resource.cc:317: resource::resources resource::allocate(resource::configuration): Assertion `!remain' failed.
May 17 05:26:10 virbr0-32-87 systemd-coredump[4097]: Process 4095 (scylla) of user 993 dumped core.
                                                     
                                                     Stack trace of thread 4095:
                                                     #0  0x00007f65601f25f7 raise (libc.so.6)
                                                     #1  0x00007f65601f3ce8 abort (libc.so.6)
                                                     #2  0x00007f65601eb566 __assert_fail_base (libc.so.6)
                                                     #3  0x00007f65601eb612 __assert_fail (libc.so.6)
                                                     #4  0x000000000054a237 n/a (scylla)
                                                     #5  0x0000000000516d7c n/a (scylla)
                                                     #6  0x000000000056bf9c n/a (scylla)
                                                     #7  0x0000000000470538 n/a (scylla)
                                                     #8  0x00007f65601deb15 __libc_start_main (libc.so.6)
                                                     #9  0x00000000004c7005 n/a (scylla)
-- Subject: Process 4095 (scylla) dumped core
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 4095 (scylla) crashed and dumped core.
-- 
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.
May 17 05:26:10 virbr0-32-87 systemd[1]: scylla-server.service: main process exited, code=dumped, status=6/ABRT
May 17 05:26:10 virbr0-32-87 sudo[4098]:   scylla : TTY=unknown ; PWD=/var/lib/scylla ; USER=root ; COMMAND=/usr/lib/scylla/scylla_stop
May 17 05:26:10 virbr0-32-87 systemd[1]: Failed to start Scylla Server.
-- Subject: Unit scylla-server.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit scylla-server.service has failed.
--

**Comment by avikivity** [comment]
What hypervisor are you using?

You can add "--memory 3G" to `SCYLLA_ARGS` in `/etc/sysconfig/scylla-server` as a workaround (looks like scylla was not able to determine how much memory you have for some reason).

**Comment by avikivity** [comment]
```
0x54a237 is in resource::allocate(resource::configuration) (core/resource.cc:317).
312	                obj = hwloc_get_next_obj_by_depth(topology, depth, obj);
313	            } while (!obj);
314	            if (obj == node)
315	                break;
316	        }
317	        assert(!remain);
318	        ret.cpus.push_back(std::move(this_cpu));
319	    }
320	
321	    ret.io_queues = allocate_io_queues(topology, c, ret.cpus);
```

**Comment by avikivity** [comment]
Please provide the output of `hwloc-ls` on your VM.

**Comment by psuriset** [comment]
Socket L#0 + L2 L#0 (4096KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0 + PU L#0 (P#0)
  Socket L#1 + L2 L#1 (4096KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1 + PU L#1 (P#1)
  Socket L#2 + L2 L#2 (4096KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2 + PU L#2 (P#2)
  Socket L#3 + L2 L#3 (4096KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3 + PU L#3 (P#3)
  HostBridge L#0
    PCI 8086:7010
    PCI 1af4:1000
    PCI 1af4:1001
    PCI 1af4:1001

**Comment by psuriset** [comment]
Am using KVM

**Comment by psuriset** [comment]
Adding --memory 3G not helping. 

journalctl -xe
                                                      #11 0x00007fd8978aeb15 __libc_start_main (libc.so.6)
                                                      #12 0x00000000004c7005 n/a (scylla)
-- Subject: Process 14199 (scylla) dumped core
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: man:core(5)
-- 
-- Process 14199 (scylla) crashed and dumped core.
-- 
-- This usually indicates a programming error in the crashing program and
-- should be reported to its vendor as a bug.
May 17 06:24:14 virbr0-32-87 systemd[1]: scylla-server.service: main process exited, code=dumped, status=6/ABRT
May 17 06:24:14 virbr0-32-87 sudo[14203]:   scylla : TTY=unknown ; PWD=/var/lib/scylla ; USER=root ; COMMAND=/usr/lib/scylla/scylla_stop
May 17 06:24:14 virbr0-32-87 systemd[1]: Failed to start Scylla Server.
-- Subject: Unit scylla-server.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit scylla-server.service has failed.

**Comment by psuriset** [comment]
SCYLLA_ARGS="--log-to-syslog 1  --memory 3G --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix"

**Comment by psuriset** [comment]
i have plans to feed collectd to corbon -> grafana -> graphite,  Once i start benchmark.
 Plan is to run benchmark on multi vm concurrently

**Comment by avikivity** [comment]
Seems like there is no `Machine` entry in your hwloc-ls output.

**Comment by avikivity** [comment]
@psuriset can you confirm there is no `Machine` entry?

Can you upload the core somewhere?

**Comment by tzach** [comment]
@psuriset any update on this issue?
Can you reproduce and [upload the core dump to s3](https://github.com/scylladb/scylla/wiki/How-to-report-a-Scylla-problem#core-dump) ?

**Comment by psuriset** [comment]
@tzach 

my VM had less memory. We can close this issue . 
Thanks
