### ISSUE TITLE
Two Scylla docker instances - dev and production

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1267]
Current [Scylla Docker](http://www.scylladb.com/doc/getting-started/#docker) use developer mode option to bypass perfomance requirment like XFS.
This makes sense for quick evaluation, but will fail users who look to use Scylla Docker image on production. 
A better offer will be to offer two images:
1. scylladb/scylla-dev with developer mode
2. scylladb/scylla without developer mode

**Comment by penberg** [comment]
How are we better off? The current Docker image works just fine for production if you configure your environment correctly, and if you don't, the proposed new image will not start up. So what's the upside here?

**Comment by tzach** [comment]
Same for Scylla itself, which works fine with developer-mode if you configure your environment correctly.
This method forces you to configure your environment correctly if you want to work in production.

We expose the fact you are in developer mode more clearly, so users won't assume they are production ready by mistake.

**Comment by slivne** [comment]
@tzach , @dorlaor , @avikivity  - please provide your requirements here on what you expect the user experience to be.

**Comment by tzach** [comment]
> please provide your requirements here on what you expect the user experience to be.

I did, on the original request!

Another alternative is to use the exact same semantic as Scylla is self:
have one production ready docker image, a --developer-mode parameter allow it to run on sub optimal env.

**Comment by dorlaor** [comment]
What ever solution we pick it needs to satisfy these conflicting
requirements:

a. Work out of the box.
    Scylla docker image should just work, no matter if it's no xfs and
whatever the
    environment is (indicates --developer mode should be used).
    Need to be able to run several local docker images as a cluster

b. Fastest & production ready
    threads should be pinned to the host cpu, the right amount of threads,
memory should be used,
    XFS should be enforced and a direct volume should be exposed to the
docker image for
    persistency, etc. It's also need to allow a scylla.yaml copy

The implementor can choose to do it in a single or multiple docker images.
Up to you

**Comment by benoit-canet** [comment]
I am not under the impression that we can pass an xfs volume to docker directly.

What I think is that the user could have his XFS volume mounted on the host and let docker mount-bind it
in the container fs hierarchy.

See "Mount a host directory as a data volume" in https://docs.docker.com/engine/userguide/containers/dockervolumes/

It would be less instamagic and require to mount the volume on the host but it seems well supported by docker and bind mounts does not imply bad performance impact.

What do you think about this ?

**Comment by avikivity** [comment]
That was the intent.

**Comment by benoit-canet** [comment]
So what is the need for something special in the image since this bind stuff works on the docker command line ? --cpuset seems also to work on the docket command line.

Why not simply write a "High performance docker" howto ?

**Comment by avikivity** [comment]
It's getting the defaults right. 

I think we can drop `--smp 1` since we don't poll now; and add `VOLUME` statements to the docker file.

If that works, then the only difference become `--developer-mode`.

**Comment by penberg** [comment]
We have not used ``--smp 1`` since December as you can see from commit https://github.com/scylladb/scylla/commit/ba09c545fcae8eae480eec1116f089e076cf51f8
