### ISSUE TITLE
Match Java driver 3.0.x

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1268]
Scylla [currently supports Java Driver 2.1 ](http://www.scylladb.com/doc/cassandra-compatibility/)
With more users are moving to Java Driver 3.0, which support Cassandra 2.2 and 3.0, and is not binary compatible with the driver’s 2.1 branch, it will be usefull to have Scylla support for Java Driver 3.0.x
More on the new features of 3.0.x updates [here](http://datastax.github.io/java-driver/upgrade_guide/)

**Comment by penberg** [comment]
Binary incompatibility means that they broke the driver API but under the hood it's still the same old CQL binary protocol, so Scylla should just work with the 3.0 driver.

**Comment by penberg** [comment]
I tested Scylla 1.0 with the following example application from the 3.0 driver git tree and it works fine:

https://github.com/datastax/java-driver/tree/3.0/driver-examples/stress

**Comment by tzach** [comment]
Thanks @penberg good news
I updated the driver Wiki with this new info
https://github.com/scylladb/scylla/wiki/Driver-Status
