### ISSUE TITLE
Repair - should repair try and fix remote replica

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#127]
if we have several neighbors, perhaps we need to request ranges from all of them and only later transfer ranges to all of them? Otherwise, we won't necessarily fully repair the other ndoes, just this one? What does Cassandra do here?

**Comment by slivne** [comment]
@nyh - I think we tested this and the answer is yes we do this

**Comment by nyh** [comment]
Yes, we tested that repair repairs the remote replica as well. However, I'm not sure the existing test covers exactly your original question in the top of this issue: >2 replicas, some new data on one, some new data on another, etc., and eventually after repair all nodes should have all the new data.

This case *should* work (the code handles it), but I don't think the test covers it yet.

**Comment by slivne** [comment]
@nyh - lets add a test for this and close it once we have a test

**Comment by nyh** [comment]
I think we do already have a passing dtest for this:
```
    def repair_disjoint_data_test(self, more_options=[]):
        """
        On each of three replicas, insert completely different data.
        Confirm that repairing a single of these nodes brings all the data 
        to all three replicas.
        """
```
