### ISSUE TITLE
 storage_proxy - exception during mutation write to ip: std::bad_alloc

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#1270]
```
test cmd: avocado run grow_cluster_test.py:GrowClusterTest.test_grow_3_to_5 --multiplex data_dir/scylla.yaml --filter-only /run/regions/us_east_1 /run/databases/scylla

ami: ami-06c02b6b
scylla: scylla-server.x86_64 0:666.development-20160518.6ec0000.el7.centos
scylla commit: 6ec0000
scylla-longevity-tests: 8a1b6bafde0d9bdb00a2dd86e53784a59f979948

scylla[2151]:   [shard 1] storage_proxy - exception during mutation write to 172.30.0.243: std::bad_alloc (std::bad_alloc)
2016-05-18 07:04:08,636 remote           L0182 DEBUG| [54.85.99.95] [stdout] May 18 07:04:07 ip-172-30-0-243 scylla[2151]:  [shard 1] storage_proxy - exception during mutation write to 172.30.0.243: std::bad_alloc (std::bad_alloc)
2016-05-18 07:04:08,637 remote           L0182 DEBUG| [54.85.99.95] [stdout] May 18 07:04:07 ip-172-30-0-243 scylla[2151]:  [shard 1] storage_proxy - exception during mutation write to 172.30.0.243: std::bad_alloc (std::bad_alloc)
2016-05-18 07:04:08,637 remote           L0182 DEBUG| [54.85.99.95] [stdout] May 18 07:04:07 ip-172-30-0-243 scylla[2151]:  [shard 1] storage_proxy - exception during mutation write to 172.30.0.243: std::bad_alloc (std::bad_alloc)
2016-05-18 07:04:08,637 remote           L0182 DEBUG| [54.85.99.95] [stdout] May 18 07:04:07 ip-172-30-0-243 scylla[2151]:  [shard 1] storage_proxy - exception during mutation write to 172.30.0.243: std::bad_alloc (std::bad_alloc)

```

**Comment by slivne** [comment]
@asias is the longevity test of the head repo or is it your branch ?

**Comment by slivne** [comment]
@lmr can you please try and verify you can reproduce this with the ami asias provided, once you do - I need you to check if this reproduces with the 1.1 ami

**Comment by lmr** [comment]
I looked on all amazon areas we use, I can't seem to find `ami-06c02b6b`. Maybe some typo?

**Comment by asias** [comment]
On May 19, 2016 22:48, "Lucas Meneghel Rodrigues" <notifications@github.com>
wrote:
>
> I looked on all amazon areas we use, I can't seem to find ami-06c02b6b.
Maybe some typo?

It is buit by takuya. Probably it is deleted by him.

**Comment by lmr** [comment]
OK, I'm using the last AMI made by scylla-ami, which is `ac8f65c1`.

**Comment by lmr** [comment]
Latest commit there: Commit eb9ac9ab91ce77573485586cdedcc7ca925efba8 by Avi Kivity
gms: Optimize gossiper::is_alive

**Comment by lmr** [comment]
So here are my findings:

1) So far I've been unable to reproduce this using `ac8f65c1`, which contains 6ec0000 mentioned by @asias, using instance size `c3.xlarge`.
2) First I used the current cassandra-stress load settings present on current upstream scylla-longevity-tests. That took a long time to complete, but eventually (4 hours) completed fine. Then I used a 10x smaller data set, that completed much quicker (1:20 hours), and also completed fine. I looked for `std::bad_alloc` and could not find it

So @slivne, I guess I can try other c-s params or instance sizes, but this issue that @asias saw may prove difficult to reproduce.

**Comment by lmr** [comment]
And `ac8f65c1` is on `us_east_1`, just for the record.

**Comment by asias** [comment]
On May 20, 2016 04:07, "Lucas Meneghel Rodrigues" <notifications@github.com>
wrote:
>
> So here are my findings:
>
> 1) So far I've been unable to reproduce this using ac8f65c1, which
contains 6ec0000 mentioned by @asias, using instance size c3.xlarge.
> 2) First I used the current cassandra-stress load settings present on
current upstream scylla-longevity-tests. That took a long time to complete,
but eventually (4 hours) completed fine. Then I used a 10x smaller data
set, that completed much quicker (1:20 hours), and also completed fine. I
looked for std::bad_alloc and could not find it
>
> So @slivne, I guess I can try other c-s params or instance sizes, but
this issue that @asias saw may prove difficult to reproduce.

I used c3.large instance which is the default one in the test suit.

**Comment by slivne** [comment]
@asias is this reproducible ?

**Comment by asias** [comment]
@slivne I did see the std::bad_alloc issue more than once with c3.large instance last week. Since @lmr was using c3.xlarge, it might be related to the instance type.

**Comment by slivne** [comment]
@lmr can you please try with c3.large

**Comment by asias** [comment]
@lmr The ami you mentioned is a 1.0.X branch, not the scylla master branch.

1.0.3 scylla_2016-05-19T02-20-18Z (ami-ac8f65c1)
```
[centos@ip-172-30-0-254 ~]$ rpm -qa|grep scylla
scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
scylla-server-1.0.3-20160506.6c4d722.el7.centos.x86_64
scylla-boost-system-1.58.0-11.el7.centos.x86_64
scylla-boost-thread-1.58.0-11.el7.centos.x86_64
scylla-boost-test-1.58.0-11.el7.centos.x86_64
scylla-boost-date-time-1.58.0-11.el7.centos.x86_64
scylla-jmx-1.0.3-20160506.4fdec13.el7.centos.noarch
scylla-server-debuginfo-1.0.3-20160506.6c4d722.el7.centos.x86_64
scylla-gdb-7.10.1-30.el7.centos.x86_64
scylla-env-1.0-1.el7.centos.noarch
scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
scylla-tools-1.0.3-20160506.da9e2d3.el7.centos.noarch
```

**Comment by lmr** [comment]
@asias, OK, so my mistake, I have used the wrong AMI. Now I'm using `ami-2bbb4c46`, with the reduced data size `seq=1..100000`, and could not trigger the bug:

12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: Report
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: DB Version:
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: scylla-boost-date-time-1.58.0-11.el7.centos.x86_64
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: scylla-boost-system-1.58.0-11.el7.centos.x86_64
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: scylla-boost-test-1.58.0-11.el7.centos.x86_64
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: scylla-boost-thread-1.58.0-11.el7.centos.x86_64
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: scylla-conf-666.development-20160522.94e7e61.el7.centos.x86_64
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: scylla-env-1.0-1.el7.centos.noarch
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: scylla-gdb-7.10.1-30.el7.centos.x86_64
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: scylla-jmx-666.development-20160522.f671046.el7.centos.noarch
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: scylla-server-666.development-20160522.94e7e61.el7.centos.x86_64
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: scylla-tools-0.10-20160522.01681e0.el7.centos.noarch
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: Interval: 600 s
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: Average duration: 267 s
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: Total execution time: 1194 s
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: Times executed: 2
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: Unhandled exceptions: 0
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: Operation log:
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: {'duration': 275, 'start': 1464015204, 'operation': 'Add new node to Cluster lmr-scylla-db-cluster-7dd41cdf (AMI: ami-2bbb4c46 Type: c3.xlarge)', 'end': 1464015479}
    12:08:18 INFO | grow_cluster_test.GrowClusterMonkey: {'duration': 259, 'start': 1464015659, 'operation': 'Add new node to Cluster lmr-scylla-db-cluster-7dd41cdf (AMI: ami-2bbb4c46 Type: c3.xlarge)', 'end': 1464015919}

**Comment by lmr** [comment]
I'm going to try now with 10x more data (`seq=1..1000000`)

**Comment by lmr** [comment]
@asias and @slivne, no luck so far, even with `c3.large` and the master based AMI, I don't see the exception messages, the 2 nodes are added successfully, and c-s holds up fine.

    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: Report
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: DB Version:
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: scylla-boost-date-time-1.58.0-11.el7.centos.x86_64
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: scylla-boost-system-1.58.0-11.el7.centos.x86_64
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: scylla-boost-test-1.58.0-11.el7.centos.x86_64
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: scylla-boost-thread-1.58.0-11.el7.centos.x86_64
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: scylla-conf-666.development-20160522.94e7e61.el7.centos.x86_64
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: scylla-env-1.0-1.el7.centos.noarch
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: scylla-gdb-7.10.1-30.el7.centos.x86_64
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: scylla-jmx-666.development-20160522.f671046.el7.centos.noarch
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: scylla-server-666.development-20160522.94e7e61.el7.centos.x86_64
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: scylla-tools-0.10-20160522.01681e0.el7.centos.noarch
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: Interval: 600 s
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: Average duration: 340 s
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: Total execution time: 1339 s
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: Times executed: 2
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: Unhandled exceptions: 0
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: Operation log:
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: {'duration': 357, 'start': 1464025316, 'operation': 'Add new node to Cluster lmr-scylla-db-cluster-603688ad (AMI: ami-2bbb4c46 Type: c3.large)', 'end': 1464025674}
    14:59:16 INFO | grow_cluster_test.GrowClusterMonkey: {'duration': 323, 'start': 1464025854, 'operation': 'Add new node to Cluster lmr-scylla-db-cluster-603688ad (AMI: ami-2bbb4c46 Type: c3.large)', 'end': 1464026177}

**Comment by lmr** [comment]
@asias, given that I'm trying to get this reproduced to no avail so far, it'd be good to know if this generated a core dump, if so, the test suite should have uploaded core dumps to the scylladb-users-upload.s3.amazonaws.com bucket automatically and the logs should tell what is the exact URL.

**Comment by asias** [comment]
@lmr just sent you the longevity test log.

**Comment by slivne** [comment]
@asias can you attach it to the issue (all the logs)

**Comment by asias** [comment]
With the following setup, it seems it is quite easy to reproduce the std::bad_alloc.


$ avocado run grow_cluster_test.py:GrowClusterTest.test_grow_3_to_4 --multiplex data_dir/scylla.hj.yaml --filter-only /run/regions/us_east_1 /run/databases/scylla

logevity config:
```
space_node_threshold: 100000000
instance_type_db: 'c3.xlarge'
instance_type_loader: 'c3.xlarge'
ami_id_db_scylla: 'ami-2bbb4c46'
```

Scylla version:
```
centos@ip-172-30-0-223 ~]$ rpm -qa|grep scylla
scylla-boost-thread-1.58.0-11.el7.centos.x86_64
scylla-boost-date-time-1.58.0-11.el7.centos.x86_64
scylla-boost-system-1.58.0-11.el7.centos.x86_64
scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
scylla-server-666.development-20160522.94e7e61.el7.centos.x86_64
scylla-jmx-666.development-20160522.f671046.el7.centos.noarch
scylla-gdb-7.10.1-30.el7.centos.x86_64
scylla-env-1.0-1.el7.centos.noarch
scylla-conf-666.development-20160522.94e7e61.el7.centos.x86_64
scylla-boost-test-1.58.0-11.el7.centos.x86_64
scylla-tools-0.10-20160522.01681e0.el7.centos.noarch
```

Limit c-s to 25K:
```

        return ("cassandra-stress write cl=QUORUM duration=%sm "
                "-schema 'replication(factor=3)' -port jmx=6868 "
                "-mode cql3 native -rate threads=%s limit=25000/s "
                "-pop seq=1..1000000 -node %s" % (duration, threads, ip))
```
Limit disk read/write bandwidth to 25M
```
--- a/sdcm/cluster.py
+++ b/sdcm/cluster.py
@@ -667,6 +667,8 @@ class ScyllaCluster(Cluster):

         def node_setup(node):
             node.wait_ssh_up(verbose=verbose)
+            node.remoter.run('sudo systemctl set-property scylla-server.service BlockIOReadBandwidth="/dev/md0 25M"')
+            node.remoter.run('sudo systemctl set-property scylla-server.service BlockIOWriteBandwidth="/dev/md0 25M"')
             node.wait_db_up(verbose=verbose)
             node.remoter.run('sudo yum install -y scylla-gdb',
                              verbose=verbose, ignore_status=True)
```

I saw:

2016-05-31 02:56:43,433 remote           L0192 DEBUG| [52.207.214.191] [stdout] May 31 02:56:42 ip-172-30-0-224 scylla[2194]:  [shard 3] storage_proxy - Failed to apply mutation from 172.30.0.225#2: std::bad_alloc (std::bad_alloc)
2016-05-31 02:56:43,434 remote           L0192 DEBUG| [52.207.214.191] [stdout] May 31 02:56:42 ip-172-30-0-224 scylla[2194]:  [shard 3] storage_proxy - Failed to apply mutation from 172.30.0.225#2: std::bad_alloc (std::bad_alloc)

2016-05-31 03:09:33,374 remote           L0192 DEBUG| [52.207.214.191] [stdout] May 31 03:09:32 ip-172-30-0-224 scylla[2194]:  [shard 3] stream_session - [Stream #ce6bb4f0-26da-11e6-b1ec-000000000001] stream_transfer_task: Fail to send to 172.30.0.25:0: std::bad_alloc (std::bad_alloc)

[centos@ip-172-30-0-224 ~]$ free -m
              total        used        free      shared  buff/cache   available
Mem:           7062        5344        1325          24         392        1489
Swap:             0           0           0

[centos@ip-172-30-0-224 ~]$ top
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
 2194 scylla    20   0 16.000t 4.888g  20352 R 395.3 70.9 144:23.65 scylla

**Comment by lmr** [comment]
OK, I'll try this setup then!

**Comment by asias** [comment]
I've figured out a way to reproduce std::bad_alloc locally. I am working on a patch.

**Comment by lmr** [comment]
Curiously, I'm helping Amnon on #1306, and only now I can see the error messages referred on this issue:

    2016-06-06 13:09:55,487 remote           L0192 DEBUG| [54.208.140.176] [stdout] Jun 06 16:09:50 ip-172-30-0-42 scylla[5166]:  [shard 1] storage_proxy - exception during mutation write to 172.30.0.42: std::bad_alloc (std::bad_alloc)

This was observed on a 1.2 RC1 AMI, `ami-b3fd01de`, `c3.xlarge` node instances.

**Comment by penberg** [comment]
That's because commit https://github.com/scylladb/scylla/commit/c70faa4f23c9e3c757915dec968a90c9e1c8a899 that fixes the issue does not appear in 1.2 RC1, but only in the upcoming RC2.

**Comment by dobbs90001** [comment]
I am still getting these with on AWS with a cluster of (4) i3.xlarge running 1.6.3 AMI (ami-247ee844).
I have 
in io.conf
SEASTAR_IO="--max-io-requests=32"

Apr 24 00:46:23 ip-10-49-10-245 scylla[13614]:  [shard 3] storage_proxy - exception during mutation write to 10.49.10.245: std::bad_alloc (std::bad_alloc)

This is causing the entire cluster to stop responding until it clears.  Running 2:1 r/w, its not dumping core.  Any suggestions?
=============================================

[root@ip-10-49-10-245 system_traces]# rpm -qa|grep scylla
scylla-conf-1.6.3-20170405.5ab8601.el7.centos.x86_64
scylla-kernel-conf-1.6.3-20170405.5ab8601.el7.centos.x86_64
scylla-debuginfo-1.6.3-20170405.5ab8601.el7.centos.x86_64
scylla-tools-1.6.3-20170405.40a41d7.el7.centos.noarch
scylla-jmx-1.6.3-20170405.35d354c.el7.centos.noarch
scylla-1.6.3-20170405.5ab8601.el7.centos.x86_64
scylla-server-1.6.3-20170405.5ab8601.el7.centos.x86_64

**Comment by avikivity** [comment]
@dobbs90001 can you provide more information about your workload, and some logs?

Interesting information:
 - schema
 - nodetool cfstats
 - typical cql row size, and number of cql rows per partition

**Comment by dobbs90001** [comment]
We are testing scylladb right now with the Flink datarunner.  We are loading data at the moment.  

I see we are using one large partition, but still are below the 2B row limit mark.  We are going to try partitioning by date as well.

[syslog.txt](https://github.com/scylladb/scylla/files/952525/syslog.txt)
[scylla.yaml.txt](https://github.com/scylladb/scylla/files/952526/scylla.yaml.txt)
[nodetool.txt](https://github.com/scylladb/scylla/files/952510/nodetool.txt)
[schema.txt](https://github.com/scylladb/scylla/files/952511/schema.txt)

**Comment by avikivity** [comment]
@dobbs90001 what Scylla version?

**Comment by dobbs90001** [comment]
EC2  with (4) i3.xlarge running 1.6.3 AMI (ami-247ee844).

**Comment by avikivity** [comment]
@dobbs90001 does decreasing the page size in the driver help?

**Comment by dobbs90001** [comment]
We are actually doing a 50/50 ratio of inserts and upserts, with next to no read queries.

We have fiddled with the page size but it hasn't really fixed the problem.

We are pushing 1M inserts / 1M upserts a minute with the 4 unit cluster.

**Comment by dobbs90001** [comment]
Restarting with 

Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 0] storage_proxy - Failed to apply mutation from 10.49.10.22#2: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 0] storage_proxy - Failed to apply mutation from 10.49.10.83#2: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 1] storage_proxy - Failed to apply mutation from 10.49.10.245#3: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 1] storage_proxy - Failed to apply mutation from 10.49.10.245#3: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 0] storage_proxy - Failed to apply mutation from 10.49.10.83#2: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 0] storage_proxy - Failed to apply mutation from 10.49.11.49#1: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 0] storage_proxy - Failed to apply mutation from 10.49.10.83#2: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 0] storage_proxy - Failed to apply mutation from 10.49.10.83#2: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 0] storage_proxy - Failed to apply mutation from 10.49.10.22#0: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 1] storage_proxy - Failed to apply mutation from 10.49.10.31#0: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 1] storage_proxy - Failed to apply mutation from 10.49.10.31#0: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 1] storage_proxy - Failed to apply mutation from 10.49.10.31#0: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 1] storage_proxy - Failed to apply mutation from 10.49.10.31#0: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 1] storage_proxy - Failed to apply mutation from 10.49.10.245#3: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 0] storage_proxy - Failed to apply mutation from 10.49.10.22#0: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 0] storage_proxy - Failed to apply mutation from 10.49.11.49#1: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 0] storage_proxy - Failed to apply mutation from 10.49.10.31#1: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 0] storage_proxy - Failed to apply mutation from 10.49.10.31#1: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 1] storage_proxy - Failed to apply mutation from 10.49.10.245#3: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 1] storage_proxy - Failed to apply mutation from 10.49.10.245#3: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 0] storage_proxy - Failed to apply mutation from 10.49.11.49#1: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 1] storage_proxy - Failed to apply mutation from 10.49.11.49#0: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 1] storage_proxy - Failed to apply mutation from 10.49.11.49#0: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 2] storage_proxy - Failed to apply mutation from 10.49.11.49#2: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 2] storage_proxy - Failed to apply mutation from 10.49.10.83#0: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:45 ip-10-49-11-40 scylla[12595]:  [shard 2] storage_proxy - Failed to apply mutation from 10.49.10.83#0: std::bad_alloc (std::bad_alloc)
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: Aborting on shard 0.
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: Backtrace:
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: 0x00000000004e043a
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: 0x00000000004e0543
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: 0x00007f3c8507d0ff
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: 0x00007f3c84ce15f6
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: 0x00007f3c84ce2ce7
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: 0x0000000000502e97
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: 0x0000000000503007
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: 0x00000000004dead4
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: 0x000000000052b515
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: 0x00000000005ad08c
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: 0x0000000000473bbd
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: 0x00007f3c84ccdb14
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: 0x00000000004ddd3e
Apr 25 22:26:46 ip-10-49-11-40 scylla[12595]: 0xffffffffffffffff
Apr 25 22:29:33 ip-10-49-11-40 scylla[13675]: Scylla version 1.6.3-20170405.5ab8601 starting ...

Here is stacktrace
print_backtrace_safe at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:2475
 (inlined by) print_with_backtrace at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:3323
sigabrt_action at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:3331
 (inlined by) operator() at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:3303
 (inlined by) _FUN at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:3299
?? ??:0
?? ??:0
?? ??:0
then<smp_message_queue::process_incoming()::<lambda(smp_message_queue::work_item*)>::<lambda()>, future<> > at /usr/src/debug/scylla-1.6.3/seastar/core/future.hh:879
 (inlined by) operator() at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:2961
 (inlined by) process_queue<2ul, smp_message_queue::process_incoming()::<lambda(smp_message_queue::work_item*)> > at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:2932
smp_message_queue::process_incoming() at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:2962
 (inlined by) smp::poll_queues() at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:3562
reactor::poll_once() at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:2674
 (inlined by) operator() at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:2575
 (inlined by) _M_invoke at /opt/scylladb/include/c++/5.3.1/functional:1857
std::function<bool ()>::operator()() const at /opt/scylladb/include/c++/5.3.1/functional:2271
 (inlined by) reactor::run() at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:2598
app_template::run_deprecated(int, char**, std::function<void ()>&&) at /usr/src/debug/scylla-1.6.3/seastar/core/app-template.cc:131
main at /usr/src/debug/scylla-1.6.3/main.cc:696
?? ??:0
_start at ??:?
?? ??:0

**Comment by dobbs90001** [comment]
Second stacktrace (different)

print_backtrace_safe at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:2475
 (inlined by) print_with_backtrace at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:3323
sigabrt_action at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:3331
 (inlined by) operator() at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:3303
 (inlined by) _FUN at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:3299
?? ??:0
?? ??:0
?? ??:0
then_wrapped<do_until_continued(StopCondition&&, AsyncAction&&, promise<>) [with AsyncAction = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda()> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>; StopCondition = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda()> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>&]::<lambda(std::result_of_t<rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda()> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>()>)>, future<> > at /usr/src/debug/scylla-1.6.3/seastar/core/future.hh:917
 (inlined by) do_until_continued<rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda()> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>, rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda()> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>&> at /usr/src/debug/scylla-1.6.3/seastar/core/future-util.hh:152
operator() at /usr/src/debug/scylla-1.6.3/seastar/core/future-util.hh:155
 (inlined by) do_void_futurize_apply<do_until_continued(StopCondition&&, AsyncAction&&, promise<>) [with AsyncAction = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda()> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>; StopCondition = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda()> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>&]::<lambda(std::result_of_t<rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda()> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>()>)>, future<> > at /usr/src/debug/scylla-1.6.3/seastar/core/future.hh:1212
apply<do_until_continued(StopCondition&&, AsyncAction&&, promise<>) [with AsyncAction = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda()> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>; StopCondition = rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda()> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>&]::<lambda(std::result_of_t<rpc::protocol<Serializer, MsgType>::server::connection::process()::<lambda()> mutable [with Serializer = net::serializer; MsgType = net::messaging_verb]::<lambda()>()>)>, future<> > at /usr/src/debug/scylla-1.6.3/seastar/core/future.hh:1260
 (inlined by) operator()<future_state<> > at /usr/src/debug/scylla-1.6.3/seastar/core/future.hh:911
 (inlined by) run at /usr/src/debug/scylla-1.6.3/seastar/core/future.hh:390
reactor::run_tasks(circular_buffer<std::unique_ptr<task, std::default_delete<task> >, std::allocator<std::unique_ptr<task, std::default_delete<task> > > >&) at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:2126
reactor::run() at /usr/src/debug/scylla-1.6.3/seastar/core/reactor.cc:2581
app_template::run_deprecated(int, char**, std::function<void ()>&&) at /usr/src/debug/scylla-1.6.3/seastar/core/app-template.cc:131
main at /usr/src/debug/scylla-1.6.3/main.cc:696
?? ??:0
_start at ??:?
?? ??:0
