### ISSUE TITLE
Support Cassandra 3.0 disk storage format

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1271]
Cassandra 3.0 [introduce new storage format](http://www.datastax.com/2015/12/storage-engine-30) with reduce space.
Scylla will have similar benefits from the new format

**Comment by tzach** [comment]
related Cassandra issue: [New sstable format with support for columnar layout](https://issues.apache.org/jira/browse/CASSANDRA-7447)

**Comment by duarten** [comment]
Closing as duplicate of #1969.
