### ISSUE TITLE
managed_bytes: Assertion `size_src == 0 &    & size_dst == 0' failed

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#1272]
Scylla commit: 6ec0000df83b4968f51c15fc1ca9a6ec72bc097b

1) Start 3 nodes

build/release/scylla --developer-mode true --auto-bootstrap false  --smp 1 -m 1024M --listen-address 127.0.0.{1..3}

2) Run c-s:
$ cassandra-stress write duration=15m cl=TWO -schema 'replication(factor=3)' -pop seq=1..1000000  -rate threads=200 limit=10000/s -node 127.0.0.1  -log file=c-s.log

3) Add 4th node to the cluster
./build/release/scylla --developer-mode true --auto-bootstrap true --smp 1 -m 1024M --listen-address 127.0.0.4

On node 2 I saw: 

scylla: ./utils/managed_bytes.hh:244: managed_bytes::managed_bytes(const managed_bytes&): Assertion `size_src == 0 &    & size_dst == 0' failed.

**Comment by avikivity** [comment]
The only way I can see this happening is if lsa compaction took place concurrently with this.

@asias do you have a core?

@tgrabiec

**Comment by asias** [comment]
@avikivity unfortunately, no core file. The instance was terminated.

**Comment by avikivity** [comment]
We need an auto-upload service to upload cores from our AMIs to S3.

**Comment by asias** [comment]
@avikivity actually, this one is not on aws. it is a local run. I will provide a core file if I can reproduce.

**Comment by asias** [comment]
I haven't managed to reproduce this again so far.

**Comment by tzach** [comment]
@asias if we can not reproduce, please close this issue

**Comment by asias** [comment]
I can not reproduce it any more.
