### ISSUE TITLE
High lsa reclaim latency

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1274]
*Installation details*
Scylla version (or git commit hash): 4eff07d773da5f2924165550f3a400163696c823

I routinely see lsa reclaim talking 6-9 milliseconds.  We should reclaim fewer segments (perhaps, reclaim until the seastar preemption timer expires).  We may need information from seastar about the requested object size to make this work better during synchronous reclaim.

It might also be a good idea to compact lsa memory during idle time.

**Comment by slivne** [comment]
@haaawk will provide the patch for idle time compaction (it was his interview task)

**Comment by tzach** [comment]
@avikivity can we close?
https://github.com/scylladb/scylla/commit/136b8148d250b0dba566a88fb07be5e3510b4e4c takes care of the idle time memory defragmentation

**Comment by slivne** [comment]
We have another patch on the list from @tgrabiec to change the current reclaming of 10 segments to less - yet its not yet merged - we need to merge it to close this
