### ISSUE TITLE
Slow startup with a large number of sstables

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1275]
_Installation details_
Scylla version (or git commit hash): 4eff07d773da5f2924165550f3a400163696c823

We currently scan sstables from all shards, opening each and discarding it if it is unneeded.  We end up opening thousands of sstables; furthermore we do this sequentially.

Potential fix:
1. Scan the directory only on shard 0, distributing the work to all shards (per sstable)
2. For each sstable, do a minimal probe to see which shards need to open it, then tell those shards to do so.
3. Do all that in parallel.

**Comment by slivne** [comment]
this conflicts with #1951 
The solution in #1951 is different - closing this issue
