### ISSUE TITLE
Bad division of work across shards if a low number of vnode is used

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1277]
_Installation details_
Scylla version (or git commit hash): 4eff07d773da5f2924165550f3a400163696c823

Sharding and vnodes both rely on the high-order bits of the token (in order to make partition range scans efficient).  If we have many shards, and a similar number of vnodes, then the same bits are used, causing shards and vnodes to alias.  As a result, a small number of shards serve most of the node's partition, severely reducing maximum throughput.

A fix would be to use (say) bits 48-55 for sharding.  This would require that sstables carry additional information about the token ranges they carry (the first/last partition key no longer helps to determine to which shard an sstable belongs).

**Comment by avikivity** [comment]
Possibly better algorithm: look at token ranges owned by node and divide those equally between the shards.  When nodes are added or removed, adjust the boundaries between the ranges (moving data between shards, and sharing sstables as needed).

**Comment by avikivity** [comment]
The second algorithm doesn't require sstable changes.

**Comment by dorlaor** [comment]
On Thu, May 19, 2016 at 6:01 PM, Avi Kivity <notifications@github.com>
wrote:

> Possibly better algorithm: look at token ranges owned by node and divide
> those equally between the shards. When nodes are added or removed, adjust
> the boundaries between the ranges (moving data between shards, and sharing
> sstables as needed).
>
+1
This will allow us on power save to reduce the number of active shards

**Comment by gleb-cloudius** [comment]
On Thu, May 19, 2016 at 08:01:25AM -0700, Avi Kivity wrote:
> Possibly better algorithm: look at token ranges owned by node and divide those equally between the shards.
Does this mean that shard_of() will have to do a look up in some kind of
table?

--
			Gleb.

**Comment by avikivity** [comment]
Yes, bsearch() in a vector if we want it to be fast.

**Comment by avikivity** [comment]
Another option is to precompute a perfect hash table, then it's O(1).

**Comment by avikivity** [comment]
A perfect hash is probably impossible from uint64_t -> shard_id

**Comment by avikivity** [comment]
We can look at the high-order 16 bits of the token, then compare it to 16 elements of the vector using an AVX2 instruction (256 bit vectors), so we can do it in a linear loop with no branches, number of iterations = shard count / 16, so really low.

**Comment by avikivity** [comment]
Using `VPCMPGTW` instruction, then `PMOVMSKB`, then `POPCNT`, add the results across the entire table, divide by 2 -> shard id.  Should be just a few cycles.

**Comment by slivne** [comment]
Internal thread "Imbalance due to sharding and possible solutions"

**Comment by avikivity** [comment]
See also: https://issues.apache.org/jira/browse/CASSANDRA-7032

With @nyh auto-reshard we can more easily move sstables between shards. Moving memtables and cache is harder though.

**Comment by dorlaor** [comment]
On Tue, Jun 14, 2016 at 3:12 PM, Avi Kivity <notifications@github.com>
wrote:

> See also: https://issues.apache.org/jira/browse/CASSANDRA-7032
>
> With @nyh <https://github.com/nyh> auto-reshard we can more easily move
> sstables between shards. Moving memtables and cache is harder though.
>

How about this auto-re-shard implementation - We add a layer for disk
accesses. It means that our cpu/mem-based shards
can divide a disk-shard between them. Disk accesses will still be done by
the original shard and thus no change of format
is needed. It's like the disk access takes a bit longer, done by the remote
shard.

It can allow us to slim a shard up to a single partition in cpu/ram. In the
background we may be able to split/unite the
sstable but it will be orthogonal and in the background.

**Comment by avikivity** [comment]
Accessing the sstable using the "wrong" shard brings the imbalance problem back (and sharing an sstable is easy).  But the real problem is memtable/cache imbalance.

With something similar to 7032 we can remove (in an existing cluster) each node and rejoin it in turn.  That will rebalance the cluster, at the cost of a lot of streaming.

**Comment by dorlaor** [comment]
On Tue, Jun 14, 2016 at 3:52 PM, Avi Kivity <notifications@github.com>
wrote:

> Accessing the sstable using the "wrong" shard brings the imbalance problem
> back (and sharing an sstable is easy). But the real problem is
> memtable/cache imbalance.
>

Doesn't cache imbalance is good?  I mean, we shouldn't allocate equal
cache/ram per shard. What we like to have
is balanced access, meaning that similar % of accesses get cached across
all shards.

Shard that owns a hot but small partition shouldn't have lots of mem and
the opposite.

**Comment by avikivity** [comment]
On Jun 14, 2016 15:58, "Dor Laor" <notifications@github.com> wrote:
>
> On Tue, Jun 14, 2016 at 3:52 PM, Avi Kivity <notifications@github.com>
> wrote:
>
> > Accessing the sstable using the "wrong" shard brings the imbalance
problem
> > back (and sharing an sstable is easy). But the real problem is
> > memtable/cache imbalance.
> >
>
> Doesn't cache imbalance is good? I mean, we shouldn't allocate equal
> cache/ram per shard. What we like to have
> is balanced access, meaning that similar % of accesses get cached across
> all shards.

Allocation is static, we don't move memory between shards. It has to be
equal, so the ratio between cpu and memory is constant.

>
> Shard that owns a hot but small partition shouldn't have lots of mem and
> the opposite.

'hot' changes from moment to moment, here we're assuming equal distribution
of partitions among tokens and accesses among partitions.

>
>
> > With something similar to 7032 we can remove (in an existing cluster)
each
> > node and rejoin it in turn. That will rebalance the cluster, at the
cost of
> > a lot of streaming.
>
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/scylladb/scylla/issues/1277#issuecomment-225871228>,
> > or mute the thread
> > <
https://github.com/notifications/unsubscribe/ABp6Rd01LCd7NAOsE3NuQ64K_LnY5h9iks5qLqP0gaJpZM4IiRyA
