### ISSUE TITLE
Docker image for version 1.1 (Docker is a second-class citizen?)

### ISSUE THREAD

**Issue by bkeroackdsc** [scylladb/scylla#1278]
The latest Docker image available on Docker Hub is 1.0.3. Please build and push an image for 1.1.x.

EDIT: and it turns out that the Docker build instructions just use whatever package is in the yum repository (rather than the binary that was built locally) so it's not useful in this circumstance. Perhaps this can be fixed at some point as well?

**Comment by penberg** [comment]
@bkeroackdsc, Docker image for Scylla 1.1.0 is now uploaded to Docker Hub.

**Comment by bkeroackdsc** [comment]
@penberg Thank you!
