### ISSUE TITLE
Repair - if there are adjacent ranges - should they be merged

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#128]
Consider the case of RF=3 and a cluster of 3 nodes - should we split the range - or should we simply do a single range repair, what does Origin do ?

In general - should adjacent ranges that are alllocated on same replicas be merged for repair execution

**Comment by glommer** [comment]
We have improved our repair a lot since then and now it is row based. We have also concluded that shard aware repairs works better in any case, so ranges should not ever be merged or we can merge shards together.

I am closing this and if there is any reason not to, please reopen.
