### ISSUE TITLE
Expose prometheus metric directly

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1280]
[Prometheus](https://prometheus.io) is a popular metric collection tool, often use with Grafana.
Prometheus pull metrics fro "exporters" which provide a simple, text base, web service to read data from.
Scylla already works with [collectd_exporter](https://github.com/prometheus/collectd_exporter) but it requires and additional process.
Using Seastar HTTP server, it should be possible to have an exporter plugin which will provide the same metrics directly, without the additional agent.

**Comment by amnonh** [comment]
Just to clarify.
A collectd agent works by pushing the data to a server periodically. Are you talking about a similar mechanism (and then it may, or may not be tied to the http server) or do you think about a mechanism that pulls the system periodically

**Comment by avikivity** [comment]
Prometheus polls the monitored service for data.

**Comment by amnonh** [comment]
So can we just use the collectd API?

**Comment by avikivity** [comment]
No. It's a different API.

**Comment by amnonh** [comment]
So it's better to add the API definition (if there's one) to the issue

**Comment by avikivity** [comment]
https://prometheus.io/docs/instrumenting/exposition_formats/

**Comment by dahankzter** [comment]
It is an extremely simple api and prometheus is popular and gaining more
traction.
We are using it for some services and it's non intrusive manner makes us
want to switch over older systems too where it is possible to do so.

**Comment by avikivity** [comment]
@dahankzter you convinced me :)

**Comment by dahankzter** [comment]
Glad to help! 😉

**Comment by amnonh** [comment]
what version are we talking about? 0.2 and 0.3 that are JSON based marked as deprecated. 0.4 is line based. There is also an alternative for using protocol-buffer format.

**Comment by avikivity** [comment]
0.4 protobuf

**Comment by tzach** [comment]
Current collectd_exporter expose metrics from both Scylla and the OS (via collectd).
This feature request takes care of the first, but not solve the second

**Comment by amnonh** [comment]
it's somewhere in the middle of the work. I'll get back to it depending on its priority

**Comment by slivne** [comment]
we support exporting the metrics to promethues from seastar directly scylladb/seastar@64ae228eabe8257995935b1be8262807f514ce44

exporting of node metrics will be done via installation of node_exporter.
