### ISSUE TITLE
Upgrade from 1.0.3 to 1.1.0 breaks due to missing I/O scheduler options

### ISSUE THREAD

**Issue by bkeroackdsc** [scylladb/scylla#1282]
Upgrading from 1.0.3 to 1.1.0 has issues regarding configuration incompatibility.

Dropping in 1.1.0 with the same configuration that worked in 1.0.3 fails with: "Bad I/O Scheduler configuration". No I/O scheduler options are documented in the included ``scylla.yaml``. After trial and error and looking at the source code and output of``scylla --help``, I was able to find the following two options: ``--max-io-requests`` and ``--num-io-queues``. 

On these particular machines (EC2 instances), the magic values apparently are ``512`` and ``4``, respectively. However I suspect that changing instance size (number of cores) will require changing these.

- ``--max-io-requests``/``--num-io-queues`` options should be documented in the example ``scylla.yaml``
- On startup, 1.1.0 should be more forgiving of new options not present in older configuration to minimize upgrade pain (emitting prominent warnings). Additionally the release notes should warn about new required configuration parameters.
- Preferably Scylla should calculate reasonable defaults for these on startup so administrators don't have to manually calculate them for each hardware setup (``scylla_io_setup`` is not helpful here when we're doing automated cluster spinup).

**Comment by dorlaor** [comment]
On Mon, May 23, 2016 at 8:24 PM, Benjamen Keroack <notifications@github.com>
wrote:

> Upgrading from 1.0.3 to 1.1.0 has issues regarding configuration
> incompatibility.
>
> Dropping in 1.1.0 with the same configuration that worked in 1.0.3 fails
> with: "Bad I/O Scheduler configuration". No I/O scheduler options are
> documented in the included scylla.yaml. After trial and error and looking
> at the source code and output ofscylla --help, I was able to find the
> following two options: --max-io-requests and --num-io-queues.
>
> On these particular machines (EC2 instances), the magic values apparently
> are 512 and 4, respectively. However I suspect that changing instance
> size (number of cores) will require changing these.
>
>    - --max-io-requests/--num-io-queues options should be documented in
>    the example scylla.yaml
>
> They are external to the yaml file. However it may worth to point them out
in the comments
or in general point out all the related config flag outside the scope of
the yaml file.


>
>    -
>    - On startup, 1.1.0 should be more forgiving of new options not
>    present in older configuration to minimize upgrade pain (emitting prominent
>    warnings). Additionally the release notes should warn about new required
>    configuration parameters.
>
> Aparently this is the main fault - we wanted to force new users who don't
tend to read documentation to use scylla_io_setup but failed to think on
the upgrade path.
It's a good lesson. @slivne, we need to fix it in 1.1.1 in the upgrade path


>
>    - Preferably Scylla should calculate reasonable defaults for these on
>    startup so administrators don't have to manually calculate them for each
>    hardware setup (scylla_io_setup is not helpful here when we're doing
>    automated cluster spinup).
>
> The AMIs should have them out of the box. However, it may be only in new
AMIs while the
upgraded AMIs didn't get a mechanism for it. It's the same issue as one
above.

**Comment by avikivity** [comment]
The upgrade guide doesn't mention scylla_io_setup at all

**Comment by avikivity** [comment]
Scratch that, scylla_io_setup was present in 1.0 and so it should already have been configured.

**Comment by avikivity** [comment]
@bkeroackdsc what OS are you running?

**Comment by avikivity** [comment]
(the parameters in questions should have been written by `scylla_io_setup` to `/etc/scylla.d/io.conf`)

**Comment by slivne** [comment]
@bkeroackdsc <https://github.com/bkeroackdsc>

- are you using scylla ami - and if so can you provide the id of the ami ?
- if not can you provide the base ami id (if its public) and the instance
type you are using.
- if the ami is not public can you provide the base ami you used to create
your public ami - and the OS info (as @avikivity has requested)

**Comment by bkeroackdsc** [comment]
I wasn't aware of io.conf. Is that documented somewhere?

@slivne I'm not using an AMI. I'm using the docker image at ``scylladb/scylla:1.1.0`` running on CoreOS (our infra stack is standardized on CoreOS). I'm explicitly overriding the included scylla.yaml (disabling developer mode). Instance type is m4.xlarge with two separate gp2 EBS volumes formatted with XFS for data and commitlog. I'm not using i2.* instances deliberately so the data persists across reboots.

**Comment by avikivity** [comment]
It's somewhat self-documented in `/etc/scylla.d/io.conf`; it's just a way to inject extra command line options.  It is prepared by `scylla_io_setup`, and you should not have been able to run 1.0 without it.

Note that EBS volumes have rather high latency.

**Comment by slivne** [comment]
We are enhancing the docker support to provide production/developer-mode setting. 

We will also test going forward docker upgrades of docker.
