### ISSUE TITLE
Support CQL 3.3 data types

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1284]
CQL 3.3 added the following data types:
Date, Time,  Tinyint and Smallint

https://cassandra.apache.org/doc/cql3/CQL-2.2.html#a3.3.0

**Comment by penberg** [comment]
Btw, we already support date and time.

**Comment by pdziepak** [comment]
I don't think so. We do support `timestamp` (in both its incarnations `org.apache.cassandra.db.marshal.TimestampType` and `org.apache.cassandra.db.marshal.DateType`) but not the new types `date` and `time`.

**Comment by penberg** [comment]
@pdziepak Right you are.

**Comment by AndreiDev** [comment]
@pdziepa @penberg hi guys! Any updates on this issue? timeline?

**Comment by penberg** [comment]
@AndreiDev I have work-in-progress patches but no ETA for them unfortunately.
