### ISSUE TITLE
CQL Performance

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#129]
Avi: 

One thing I can see is that cqlb reads and writes are slow due to many small allocations.

Things we can do to optimize this:
- read string_views instead of strings.  To do this we will need to hold on to the temporary_buffer<> holding the request, so the data doesn't disappear
- recycle request objects.  This eliminates allocating and expanding vector<>s and map<>s holding those string_views.
- fix seastar output_stream::flush() not to push data all the way to the stack
- cache things like the keyspace and column_family in the modification_statement (or whatever).  This is a little hard because there's one of those per shard, but nothing prevents prepare_statement() from calling sharded::map() to pre-fill the cache.

**Comment by glommer** [comment]
Unassigned bug from 2015, unclear from description if still valid.

**Comment by nyh** [comment]
Removing backport-candidate tag which seems to have been added here by mistake, and also closing this issue which contains a list of unrelated suggestions some of which we already did, some not. If we still want any of these suggestions we should open a separate issue for each with a clear explanation of why it is a good idea.
