### ISSUE TITLE
Readings timeout

### ISSUE THREAD

**Issue by hypnofrogme** [scylladb/scylla#1290]
## Installation details
Scylla version 1.1
Cluster size: 3 nodes
OS Ubuntu

## Hardware details (for performance issues)
Platform (physical/VM/cloud instance type/docker):
Hardware: 64 GB RAM, 12 cores
Disks:  SSD

Hi, 

We try to insert and to read from db, but seems to be when we write we can't read anything at the same time.
How could we fix it?
Just add one more node and read from there, or there something else?

**Comment by tgrabiec** [comment]
@hypnofrogme Read and write can happen concurrently in Scylla DB. Can you say more about how you test and what makes you think that writes and reads don't happen at the same time?

**Comment by tzach** [comment]
@hypnofrogme can you please provide more data?
In particular, if you are using 1.3 RC, you can use [CQL trace](http://www.scylladb.com/2016/08/04/cql-tracing/) to trace both requests.

**Comment by slivne** [comment]
I am closing this for now - there is no additional info 

@hypnofrogme if there is additional info you can share (even if you have overcome the issue on your own) that would be appreciated.
