### ISSUE TITLE
Scylla Call Home 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1294]
Allow Scylla users to share usage metrics and system info with ScyllaDB team.
The reported information will include software versions and system information, never the stored data

Add a question as part of scylla_setup:
`Do you agree to share operational info with ScyllaDB? [y/n]: y`

If the answer is yes:
`Do you agree to share your email, attaching it to your reports? 
click enter to keep your information anonymized:`

scylla_setup will store the response for Scylla to use

**Comment by avikivity** [comment]
The question should explain a lot more about what is shared and what is not shared.

**Comment by amnonh** [comment]
On Sun, May 29, 2016 at 11:50 AM, Avi Kivity <notifications@github.com>
wrote:

> The question should explain a lot more about what is shared and what is
> not shared.
>
Or explain in general and add a link to a detail explenation (which will be
easier to maintain)

**Comment by raphaelsc** [comment]
We need to provide a way for this question to be automatically answered. For example, when cluster is created and user may not even log in to all node machines.

**Comment by tzach** [comment]
@raphaelsc a good point, which applies to scylla_setup on general, not only to this feature. If one automate scylla_setup, he can provide a value for the each question. If one skip scylla_setup, the default will be used.

**Comment by amnonh** [comment]
I suggest that we'll add a script that would be able to report both for local and remote and call-home is one option.

This way we can use the same script to print warnings for system configuration. Putting it in a single script allows us to direct users to download it directly.

**Comment by tzach** [comment]
@amnonh configuration management goes beyond the scope of this feature, and more into #1302

**Comment by amnonh** [comment]
Not talking about configuration management.
In general we're talking about gathering information and send it.

It will be used on installation, but also when trying to help a customer.
So it will be possible to get the report as a file.

We can add different reports to the same tool plus add some intelligence to
look for interesting things in the reports output

**Comment by tzach** [comment]
@slivne I think we can close this issue
