### ISSUE TITLE
Add documentation to Scylla docker image

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1298]
Docker hub page can include documentation.
A good example is [Cassandra docker hub page](https://hub.docker.com/_/cassandra/) which includes instructions how to run a Cassandra cluster and other relevant docs.
[Scylla page](https://hub.docker.com/u/scylladb/) should include similar instructions, updated for Scylla.

**Comment by benoit-canet** [comment]
@tzach: I plan to add a "seeds" and a "broadcast_address" variable to make clustering possible with our docker image. Is that ok for you to implement only this tiny subset ?

Meanwhile could you share privatelly with me the informations required to modify this documentation page ?

**Comment by benoit-canet** [comment]
I don't know where this document must go right now.
So here it is in the PR

**Comment by benoit-canet** [comment]
@tzach Documentation on the scylladb-dev list with associated patches. I kept it minimal.

**Comment by slivne** [comment]
@tzach can you please review so we can close this

**Comment by tzach** [comment]
Thanks @benoit-canet its a good start

Comparing to what [other](https://hub.docker.com/_/cassandra/) are doing, we should do much more:
- How to use this image
- Setup a cluster 
- Connect from CQLSh
and more

This task is overlapping with Scylla documentation more than dev, so maybe @dmarti can help us on this one.

**Comment by benoit-canet** [comment]
@tzach: are you sure you are reviewing "[PATCH] docker: Add docker page
documentation." ?

**Comment by tzach** [comment]
@penberg can you please review and apply the updates?
https://groups.google.com/forum/#!searchin/scylladb-dev/%5BPATCH%5D$20docker$3A$20Add$20docker$20page$20documentation/scylladb-dev/g8W0XEPnzEU/Sinr-l5xBAAJ

**Comment by penberg** [comment]
@tzach We have the following documentation now:

https://github.com/scylladb/scylla/blob/master/docs/docker-hub.md

I will update Docker Hub once we release 1.3.

**Comment by tzach** [comment]
Close with @penberg docker hub doc
