### ISSUE TITLE
Error in log- Compaction found an exception when reading sstable

### ISSUE THREAD

**Issue by PriyaGheewala** [scylladb/scylla#1307]
While running scyllaDB we are seeing couple of failures and it happens quite often. We are reading the data and pushing it to scylla on a regular speed, around 271 million entries in a day.While referring the log file of scylla, we are seeing following exceptions.
Is this a normal behavior of scylla? It seems like data loss to us.Please let us know do we need to do something to resolve this issues.

The logs of the scylla is as follows.
Jun 02 00:00:29 afea-sandbox-2.adnear.net scylla[29322]:  [shard 14] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 02 00:00:29 afea-sandbox-2.adnear.net scylla[29322]:  [shard 37] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 02 00:00:29 afea-sandbox-2.adnear.net scylla[29322]:  [shard 13] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 02 00:00:29 afea-sandbox-2.adnear.net scylla[29322]:  [shard 33] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 02 00:00:29 afea-sandbox-2.adnear.net scylla[29322]:  [shard 39] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 02 00:00:29 afea-sandbox-2.adnear.net scylla[29322]:  [shard 32] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 02 00:00:29 afea-sandbox-2.adnear.net scylla[29322]:  [shard 0] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 02 00:00:29 afea-sandbox-2.adnear.net scylla[29322]:  [shard 35] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 02 00:00:29 afea-sandbox-2.adnear.net scylla[29322]:  [shard 20] compaction - Compaction found an exception when reading sstable /disk1/scylladata/data/allsparkdataexporttest/gbr_2016_06_01-54617d4027c311e681b2000000000003/allsparkdataexporttest-gbr_2016_06_01-ka-3180-Data.db : std::bad_alloc (std::bad_alloc)
Jun 02 00:00:30 afea-sandbox-2.adnear.net scylla[29322]:  [shard 20] compaction_manager - compaction failed: read exception: std::bad_alloc (std::bad_alloc)

*Installation details*
Scylla version (or git commit hash):1.1
Cluster size:1
OS (RHEL/CentOS/Ubuntu/AWS AMI):CentOs 7

*Hardware details (for performance issues)*   :        
Platform (physical/VM/cloud instance type/docker): Physical
Hardware: sockets= cores= hyperthreading= memory=32 GB
processor	: 39
vendor_id	: GenuineIntel
cpu family	: 6
model		: 62
model name	: Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz

Disks: (SSD/HDD, count): 2X SSD

**Comment by avikivity** [comment]
Hello, what is probably happening is that you have too many logical processors for your memory.  You have 32GB and 40 logical cores, leaving around 700MB per logical core.

You can improve this by adding `--smp 20`  to `/etc/sysconfig/scylla-server` and restarting the node, or by adding more memory.  Look at the Memory Requirements section in the [admin guide](http://www.scylladb.com/doc/admin/)

Another possibility is that you are using wide partitions -- a large number of cql rows per partition.  Please post the output of `nodetool cfstats`  for the column family experiencing the problem.

Those logs don't indicate data loss, but may indicate degraded service.

**Comment by PriyaGheewala** [comment]
Hi,
while running scylladb it went down with following exception

Jun 05 05:23:27 sandbox-2[5317]:  [shard 2] sstable - Exception when deleting sstable file: std::runtime_error (Atomic sstable deletions cancelled; not deleting {/disk1/scylladata/data/datatest/tbl1-56a811e027c311e68d8d000000000005/datatest-tbl1-ka-7055-TOC.txt})
Jun 05 05:23:27 sandbox-2[5317]:  [shard 17] sstable - Exception when deleting sstable file: std::runtime_error (Atomic sstable deletions cancelled; not deleting {/disk1/scylladata/data/datatest/tbl2-55d09da027c311e68a67000000000004/datatest-tbl2-ka-5174-TOC.txt})
Jun 05 05:23:27 sandbox-2[5317]:  [shard 15] sstable - Exception when deleting sstable file: std::runtime_error (Atomic sstable deletions cancelled; not deleting {/disk1/scylladata/data/datatest/tbl2-55d09da027c311e68a67000000000004/datatest-tbl2-ka-5174-TOC.txt})
Jun 05 05:23:27 sandbox-2[5317]:  [shard 13] sstable - Exception when deleting sstable file: std::runtime_error (Atomic sstable deletions cancelled; not deleting {/disk1/scylladata/data/datatest/tbl-56a811e027c311e68d8d000000000005/datatest-tbl-ka-7334-TOC.txt})
Jun 05 05:23:30 sandbox-2[5317]:  [shard 0] compaction_manager - Stopped


When we tried adding --smp 20 to /etc/sysconfig/scylla-server we could not restart the scylla.
 we are seeing following log messages.

● scylla-server.service - Scylla Server
   Loaded: loaded (/usr/lib/systemd/system/scylla-server.service; enabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Mon 2016-06-06 11:19:57 IST; 6min ago
  Process: 7127 ExecStopPost=/usr/bin/sudo -E /usr/lib/scylla/scylla_stop (code=exited, status=0/SUCCESS)
  Process: 7124 ExecStart=/usr/bin/scylla $SCYLLA_ARGS $SEASTAR_IO $DEV_MODE (code=dumped, signal=ABRT)
  Process: 7120 ExecStartPre=/usr/bin/sudo -E /usr/lib/scylla/scylla_prepare (code=exited, status=0/SUCCESS)
 Main PID: 7124 (code=dumped, signal=ABRT)

Jun 06 11:19:57sandbox-2 systemd[1]: Failed to start Scylla Server.
Jun 06 11:19:57sandbox-2 systemd[1]: Unit scylla-server.service entered failed state.
Jun 06 11:19:57 sandbox-2 systemd[1]: scylla-server.service failed.
Jun 06 11:19:57 sandbox-2 systemd[1]: scylla-server.service holdoff time over, scheduling restart.
Jun 06 11:19:57 sandbox-2 systemd[1]: start request repeated too quickly for scylla-server.service
Jun 06 11:19:57 sandbox-2 systemd[1]: Failed to start Scylla Server.
Jun 06 11:19:57 sandbox-2 systemd[1]: Unit scylla-server.service entered failed state.
Jun 06 11:19:57 sandbox-2 systemd[1]: scylla-server.service failed.

**Comment by penberg** [comment]
Looks like Scylla crashed at startup after the failure:

```
Process: 7124 ExecStart=/usr/bin/scylla $SCYLLA_ARGS $SEASTAR_IO $DEV_MODE (code=dumped, signal=ABRT)
Main PID: 7124 (code=dumped, signal=ABRT)
```

Are you able to share the core dump with us as per these instructions?

https://github.com/scylladb/scylla/wiki/How-to-report-a-Scylla-problem

**Comment by PriyaGheewala** [comment]
@penberg ,
We have shared the core dump as per the instructions.
The UUID  is e6ddc364-bb93-4367-8a6b-a2d02a159339.
Please let me know if anything else needs to be done.

**Comment by avikivity** [comment]
It might be the boost::program_options::variable_map getting destroyed. main.cc::597 is the last line of main(), indicating we were on the way out.

**Comment by avikivity** [comment]
@PriyaGheewala please upload the core file, and also report the output of `nodetool cfstats` as requested earlier.

**Comment by PriyaGheewala** [comment]
@avikivity 
We are not able to connect to scylla so I can't send you the output of nodetool cfstats.
Here is the link to coredump file:  [https://www.dropbox.com/s/c4rjr3o8f2gwsfh/coredump.txt?dl=0]

**Comment by PriyaGheewala** [comment]
@avikivity 
We reinstalled scyllaDB and started pushing data again but it stopped in 2 days.

Link of log file : [https://www.dropbox.com/s/7cwy182vuz8hphj/ScyllaLogs.txt?dl=0]

Here is the link of nodetool cfstats output file: [https://www.dropbox.com/s/l4d59ssgvuo9oyo/nodetoolcfstats.txt?dl=0]

**Comment by penberg** [comment]
@avikivity @gleb-cloudius @slivne I think someone is already chasing a ``bad_alloc`` from ``storage_proxy`` problem but I was not able to find a Github issue about it:

```
Jun 14 17:40:05 afea-sandbox-2.adnear.net scylla[24333]:  [shard 9] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 14 17:40:05 afea-sandbox-2.adnear.net scylla[24333]:  [shard 11] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 14 17:40:05 afea-sandbox-2.adnear.net scylla[24333]:  [shard 4] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 14 17:40:05 afea-sandbox-2.adnear.net scylla[24333]:  [shard 9] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 14 17:40:05 afea-sandbox-2.adnear.net scylla[24333]:  [shard 8] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 14 17:40:05 afea-sandbox-2.adnear.net scylla[24333]:  [shard 12] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 14 17:40:05 afea-sandbox-2.adnear.net scylla[24333]:  [shard 12] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 14 17:40:05 afea-sandbox-2.adnear.net scylla[24333]:  [shard 7] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
Jun 14 17:40:07 afea-sandbox-2.adnear.net scylla[24333]:  [shard 10] compaction - Compacting [/disk1/scylladata/data/allsparkdataexporttest/chn_2016_06_14-fc37a36031c211e6b82a00000000001e/allsparkdataexporttest-chn_2016_06_14-ka-2610-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/chn_2016_06_14-fc37a36031c211e6b82a00000000001e/allsparkdataexporttest-chn_2016_06_14-ka-2650-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/chn_2016_06_14-fc37a36031c211e6b82a00000000001e/allsparkdataexporttest-chn_2016_06_14-ka-2690-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/chn_2016_06_14-fc37a36031c211e6b82a00000000001e/allsparkdataexporttest-chn_2016_06_14-ka-2730-Data.db:level=0, ]
Jun 14 17:40:07 afea-sandbox-2.adnear.net scylla[24333]:  [shard 10] compaction - Compacting [/disk1/scylladata/data/allsparkdataexporttest/ind_2016_06_14-fc12411031c211e6b89000000000001d/allsparkdataexporttest-ind_2016_06_14-ka-1650-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/ind_2016_06_14-fc12411031c211e6b89000000000001d/allsparkdataexporttest-ind_2016_06_14-ka-1690-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/ind_2016_06_14-fc12411031c211e6b89000000000001d/allsparkdataexporttest-ind_2016_06_14-ka-1730-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/ind_2016_06_14-fc12411031c211e6b89000000000001d/allsparkdataexporttest-ind_2016_06_14-ka-1770-Data.db:level=0, ]
Jun 14 17:40:07 afea-sandbox-2.adnear.net scylla[24333]:  [shard 10] compaction - Compacted 4 sstables to [/disk1/scylladata/data/allsparkdataexporttest/chn_2016_06_14-fc37a36031c211e6b82a00000000001e/allsparkdataexporttest-chn_2016_06_14-ka-2770-Data.db:level=0, ]. 31018 bytes to 29994 (~96% of original) in 201ms = 0.142311MB/s. ~1024 total partitions merged to 8.
Jun 14 17:40:07 afea-sandbox-2.adnear.net scylla[24333]:  [shard 10] compaction - Compacted 4 sstables to [/disk1/scylladata/data/allsparkdataexporttest/ind_2016_06_14-fc12411031c211e6b89000000000001d/allsparkdataexporttest-ind_2016_06_14-ka-1810-Data.db:level=0, ]. 4332 bytes to 4252 (~98% of original) in 196ms = 0.0206889MB/s. ~1024 total partitions merged to 4.
Jun 14 17:40:07 afea-sandbox-2.adnear.net scylla[24333]:  [shard 10] compaction - Compacted 4 sstables to [/disk1/scylladata/data/allsparkdataexporttest/chn_2016_06_14-fc37a36031c211e6b82a00000000001e/allsparkdataexporttest-chn_2016_06_14-ka-2770-Data.db:level=0, ]. 31018 bytes to 29994 (~96% of original) in 201ms = 0.142311MB/s. ~1024 total partitions merged to 8.
Jun 14 17:40:07 afea-sandbox-2.adnear.net scylla[24333]:  [shard 10] compaction - Compacted 4 sstables to [/disk1/scylladata/data/allsparkdataexporttest/ind_2016_06_14-fc12411031c211e6b89000000000001d/allsparkdataexporttest-ind_2016_06_14-ka-1810-Data.db:level=0, ]. 4332 bytes to 4252 (~98% of original) in 196ms = 0.0206889MB/s. ~1024 total partitions merged to 4.
Jun 14 17:40:07 afea-sandbox-2.adnear.net scylla[24333]:  [shard 10] compaction - Compacting [/disk1/scylladata/data/allsparkdataexporttest/jpn_2016_06_14-f00a92a031c211e6b89000000000001d/allsparkdataexporttest-jpn_2016_06_14-ka-2690-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/jpn_2016_06_14-f00a92a031c211e6b89000000000001d/allsparkdataexporttest-jpn_2016_06_14-ka-2730-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/jpn_2016_06_14-f00a92a031c211e6b89000000000001d/allsparkdataexporttest-jpn_2016_06_14-ka-2770-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/jpn_2016_06_14-f00a92a031c211e6b89000000000001d/allsparkdataexporttest-jpn_2016_06_14-ka-2810-Data.db:level=0, ]
Jun 14 17:40:08 afea-sandbox-2.adnear.net scylla[24333]:  [shard 10] compaction - Compacted 4 sstables to [/disk1/scylladata/data/allsparkdataexporttest/jpn_2016_06_14-f00a92a031c211e6b89000000000001d/allsparkdataexporttest-jpn_2016_06_14-ka-2850-Data.db:level=0, ]. 24942256 bytes to 24941136 (~99% of original) in 981ms = 24.2464MB/s. ~1024 total partitions merged to 21.
Jun 14 17:40:09 afea-sandbox-2.adnear.net scylla[24333]:  [shard 19] compaction - Compacting [/disk1/scylladata/data/allsparkdataexporttest/idn_2016_06_14-fac43d4031c211e6b89000000000001d/allsparkdataexporttest-idn_2016_06_14-ka-6619-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/idn_2016_06_14-fac43d4031c211e6b89000000000001d/allsparkdataexporttest-idn_2016_06_14-ka-6659-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/idn_2016_06_14-fac43d4031c211e6b89000000000001d/allsparkdataexporttest-idn_2016_06_14-ka-6699-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/idn_2016_06_14-fac43d4031c211e6b89000000000001d/allsparkdataexporttest-idn_2016_06_14-ka-6739-Data.db:level=0, ]
Jun 14 17:40:09 afea-sandbox-2.adnear.net scylla[24333]:  [shard 19] compaction - Compacting [/disk1/scylladata/data/allsparkdataexporttest/sgp_2016_06_14-f94bf52031c211e6ae37000000000018/allsparkdataexporttest-sgp_2016_06_14-ka-6619-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/sgp_2016_06_14-f94bf52031c211e6ae37000000000018/allsparkdataexporttest-sgp_2016_06_14-ka-6659-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/sgp_2016_06_14-f94bf52031c211e6ae37000000000018/allsparkdataexporttest-sgp_2016_06_14-ka-6699-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/sgp_2016_06_14-f94bf52031c211e6ae37000000000018/allsparkdataexporttest-sgp_2016_06_14-ka-6739-Data.db:level=0, ]
Jun 14 17:40:11 afea-sandbox-2.adnear.net scylla[24333]:  [shard 8] storage_proxy - exception during mutation write to 10.57.200.134: std::bad_alloc (std::bad_alloc)
```

**Comment by gleb-cloudius** [comment]
On Wed, Jun 15, 2016 at 11:47:04PM -0700, Pekka Enberg wrote:
> @avikivity @gleb-cloudius @slivne I think someone is already chasing a ``bad_alloc`` from ``storage_proxy`` problem but I was not able to find a Github issue about it:
> 
``storage_proxy`` is a messenger. The problem is in the layer below.
Asias had a fix for one that happens because of streaming.

--
			Gleb.

**Comment by penberg** [comment]
Ah, indeed. @PriyaGheewala which exact version are you running (your report just says 1.1)? I strongly suggest you upgrade to 1.1.2 which has a fix for the problem you are likely hitting:

https://github.com/scylladb/scylla/commit/52c9723e04aa976743cc8f17000eb96ff03f7ca1

**Comment by tzach** [comment]
Hi @PriyaGheewala did you had a chance to test a later version of Scylla (1.1.2 or 1.2)?

**Comment by PriyaGheewala** [comment]
@penberg  @tzach 
we are using version 1.2
Please find the log file at : [https://www.dropbox.com/s/tuq8xhqvqmvmcmt/logs.txt?dl=0] and
nodetoolcfstats report at:  [https://www.dropbox.com/s/l4d59ssgvuo9oyo/nodetoolcfstats.txt?dl=0]

**Comment by PriyaGheewala** [comment]
@penberg 

We restarted scyllaDB. Please find the latest nodetool cfstats report at [https://www.dropbox.com/s/e9tb8ygsp7jp4kx/20June.txt?dl=0]

**Comment by penberg** [comment]
AFAICT, we now ran out of memory while compacting:

```
Jun 18 09:30:02 afea-sandbox-2.adnear.net scylla[32656]:  [shard 33] compaction - Compacting [/disk1/scylladata/data/allsparkdataexporttest/aus-fc7c7900338d11e6a8a5000000000008/allsparkdataexporttest-aus-ka-1553-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/aus-fc7c7900338d11e6a8a5000000000008/allsparkdataexporttest-aus-ka-3033-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/aus-fc7c7900338d11e6a8a5000000000008/allsparkdataexporttest-aus-ka-8113-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/aus-fc7c7900338d11e6a8a5000000000008/allsparkdataexporttest-aus-ka-17513-Data.db:level=0, /disk1/scylladata/data/allsparkdataexporttest/aus-fc7c7900338d11e6a8a5000000000008/allsparkdataexporttest-aus-ka-28673-Data.db:level=0, ]
Jun 18 09:30:26 afea-sandbox-2.adnear.net scylla[32656]:  [shard 33] compaction_manager - compaction failed: read exception: std::bad_alloc (std::bad_alloc)
```

The sstable is only 11 GiB in size:

```
		Table: aus
		SSTable count: 210
		Space used (live): 11965541814
		Space used (total): 11965541814
		Space used by snapshots (total): 0
		Off heap memory used (total): 175911104
		SSTable Compression Ratio: 0.508312
		Number of keys (estimate): 2615
		Memtable cell count: 437
		Memtable data size: 144636692
		Memtable off heap memory used: 170655744
		Memtable switch count: 0
		Local read count: 0
		Local read latency: NaN ms
		Local write count: 422506
		Local write latency: 0.061 ms
		Pending flushes: 0
		Bloom filter false positives: 0
		Bloom filter false ratio: 0.00000
		Bloom filter space used: 20128
		Bloom filter off heap memory used: 5243360
		Index summary off heap memory used: 12000
		Compression metadata off heap memory used: 0
		Compacted partition minimum bytes: 51
		Compacted partition maximum bytes: 155469300
		Compacted partition mean bytes: 9930703
		Average live cells per slice (last five minutes): 0.0
		Maximum live cells per slice (last five minutes): 0.0
		Average tombstones per slice (last five minutes): 0.0
		Maximum tombstones per slice (last five minutes): 0.0
```

@raphaelsc @nyh @avikivity, is this an artifact of parallel compaction between shards?

**Comment by avikivity** [comment]
There is a 155MB partition in there, and the shard size is only 800MB (32 GB / 40 lcore).

Our current large partition support is not stellar (slated to be much improved in 1.3), and 800 MB/shard is too low.  Try running with --smp 20 (or even --smp 10) to increase memory per shard.  Even better, install more memory.  32 GB is too low for such a powerful machine.

**Comment by jarek2ch** [comment]
cqlsh:elcar_gps> drop table frames;
ServerError: <ErrorMessage code=0000 [Server error] message="std::bad_alloc">

[cqlsh 5.0.1 | Cassandra 2.1.8 | CQL spec 3.2.0 | Native protocol v3]
