### ISSUE TITLE
Improve cleanup on error

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1309]
If we have an error while writing an sstable, we should mark it for deletion, otherwise if the error keeps repeating we'll fill the disk with partially written sstables.

Cleanup should consider the temporary-TOC as well.

**Comment by tgrabiec** [comment]
@raphaelsc Was this fixed already?

**Comment by raphaelsc** [comment]
@tgrabiec yes, after b7e1575ad4a253f6da54525babf1408e6589a97f

**Comment by raphaelsc** [comment]
@slivne: please close this
