### ISSUE TITLE
Node does not shut down communications when out of disk space

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1311]
*Installation details*
Scylla version (or git commit hash): 1.1

**Comment by benoit-canet** [comment]
Yes Avi,

I made an exception for ENOSPC since I though that Raphael was working
for a way for Scylla to back off write on ENOSPC.

Was I wrong ?

Best regards

Benoît

**Comment by avikivity** [comment]
So it appears, we should have caught ENOSPC and removed it when whatever Raphael was doing was complete.

**Comment by benoit-canet** [comment]
I refreshed my memory. Later on you instructed we to shutdown only on EIO.

**Comment by avikivity** [comment]
You should have ignored me, it was a really bad idea.

Did we not discuss ENOSPC?

**Comment by avikivity** [comment]
Here's what I said at one time:

> We need separate treatment for: 
>
>     ENOSPC (can't write any more, but can read) 
>     EIO on sstable write (we may recover if we retry) 
>     EIO on sstable read (may want to start repair) 
>     EIO on commitlog write (bad) 
>     ENOTDIR/EPERM/ENOENT etc (indicating bad configuration probably) 
> 
> Maybe we won't have separate treatment now, but by having multiple 
> signals, we can be prepared. 

Looks like we aren't prepared.

**Comment by benoit-canet** [comment]
We have:

I though you wanted to discriminate by source of the exception so I did

extern thread_local disk_error_signal_type commit_error;
extern thread_local disk_error_signal_type sstable_read_error;
extern thread_local disk_error_signal_type sstable_write_error;
extern thread_local disk_error_signal_type general_disk_error;

to discriminate from the source of the exception.

We could discriminate futher by signal in service/storage_service.(hh/cc)
with some switch/cases.

At least even I did it wrong I tried to prepare ourselves for this.

**Comment by avikivity** [comment]
Yeah it's my fault, I didn't explain myself clearly, and in any case I should have caught EIO-only on review.

**Comment by slivne** [comment]
requires backport for 1.2, 1.1
