### ISSUE TITLE
nodetool cleanup - rewrites files even when there is no update to be done 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1316]
Scylla version (or git commit hash): 1.1

on cassandra
```
ccm create cas-1  --vnodes -n 1 --install-dir=~/scylla-tools-java
ccm start
ccm node1 stress write n=600000 -mode cql3 native -schema compaction\(strategy=LeveledCompactionStrategy\) keyspace=keyspace2 -pop seq=1..100000000000
check the files in the data/keyspace2
ccm node1 nodetool cleanup
check the files in the data/keyspace2
```

how I tested this on scylla
```
ccm create scylla-1 --scylla --vnodes -n 1 --install-dir=~/scylla
ccm start
ccm node1 stress write n=600000 -mode cql3 native -schema compaction\(strategy=LeveledCompactionStrategy\) keyspace=keyspace2 -pop seq=1..100000000000
check the files in the data/keyspace2
ccm node1 nodetool cleanup
check the files 
```
logs
s. ~606464 total partitions merged to 602080.
INFO  2016-06-06 09:11:34,057 [shard 0] compaction - Cleaning [/home/shlomi/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000/keyspace2-standard1-ka-35-Data.db:level=1, ]
INFO  2016-06-06 09:11:34,057 [shard 0] compaction - Cleaning [/home/shlomi/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000/keyspace2-standard1-ka-36-Data.db:level=1, ]
INFO  2016-06-06 09:11:34,262 [shard 0] compaction - Cleaned 1 sstables to [/home/shlomi/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000/keyspace2-standard1-ka-38-Data.db:level=0, ]. 1412306 bytes to 1412306 (~100% of original) in 204ms = 6.60235MB/s. ~5248 total partitions merged to 5026.
INFO  2016-06-06 09:11:41,548 [shard 0] compaction - Cleaned 1 sstables to [/home/shlomi/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000/keyspace2-standard1-ka-37-Data.db:level=0, ]. 167772174 bytes to 167772174 (~100% of original) in 7491ms = 21.359MB/s. ~597248 total partitions merged to 597054.
```
```
shlomi@localhost~/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000$ ls
keyspace2-standard1-ka-35-CRC.db       keyspace2-standard1-ka-35-Index.db       keyspace2-standard1-ka-36-CRC.db       keyspace2-standard1-ka-36-Index.db
keyspace2-standard1-ka-35-Data.db      keyspace2-standard1-ka-35-Statistics.db  keyspace2-standard1-ka-36-Data.db      keyspace2-standard1-ka-36-Statistics.db
keyspace2-standard1-ka-35-Digest.sha1  keyspace2-standard1-ka-35-Summary.db     keyspace2-standard1-ka-36-Digest.sha1  keyspace2-standard1-ka-36-Summary.db
keyspace2-standard1-ka-35-Filter.db    keyspace2-standard1-ka-35-TOC.txt        keyspace2-standard1-ka-36-Filter.db    keyspace2-standard1-ka-36-TOC.txt
shlomi@localhost~/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000$ ccm node1 cleanup

shlomi@localhost~/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000$ ls
keyspace2-standard1-ka-37-CRC.db       keyspace2-standard1-ka-37-Index.db       keyspace2-standard1-ka-38-CRC.db       keyspace2-standard1-ka-38-Index.db
keyspace2-standard1-ka-37-Data.db      keyspace2-standard1-ka-37-Statistics.db  keyspace2-standard1-ka-38-Data.db      keyspace2-standard1-ka-38-Statistics.db
keyspace2-standard1-ka-37-Digest.sha1  keyspace2-standard1-ka-37-Summary.db     keyspace2-standard1-ka-38-Digest.sha1  keyspace2-standard1-ka-38-Summary.db
keyspace2-standard1-ka-37-Filter.db    keyspace2-standard1-ka-37-TOC.txt        keyspace2-standard1-ka-38-Filter.db    keyspace2-standard1-ka-38-TOC.txt
shlomi@localhost~/.ccm/scylla-1/node1/data/keyspace2/standard1-55a657002bad11e68cf3000000000000$ 
```

**Comment by raphaelsc** [comment]
That's also covered by https://github.com/scylladb/scylla/issues/828

**Comment by slivne** [comment]
moved info to #828 - closing
