### ISSUE TITLE
delete_atomically() is not enough, and at the same time, too much :-)

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#1318]
This issue is about the same scenario as in #1314.

The delete_atomically() code ensures that when compaction cannot delete an sstable because it is shared by multiple shards, we also won't delete the other sstables compacted with it. The reason we need to do this is that these other sstables might contain tombstones covering data in the shared sstable, and if the the shared sstable is ever "resurrected" on reboot, we need to keep the tombstones as well.

Shlomi noted that the logic of deleting all the compacted sstables together is not actually enough, because we also need to delay the deletion of the *resulting* sstable, and all other sstables it is compacted with... The issue is that even after 10 generations of compactions, we still cannot delete tombstones because we still have the risk these are new tombstones that cover old data from the yet-undeleted sstable that might be resurrected on reboot. So we need to extended the delayed deletion logic to "infect" with a delay more than the original list of sstables compacted together.

But delaying deletion of entire sstables is not a great idea because it increases the disk space usage. This will be even worse if the fix from the above paragraph is done - every time we run compactions, both the old and new sstables will not be deleted, just for the off chance it might contain some tombstone we cannot yet GC. So I think we should consider switching to a more direct approach:

We can simply disable GC of old tombstones while there are any shared sstables in the system (and issue #1314 will reduce the time that is the case).

The downside of this approach will be that even when we finally get rid of the shared sstables, the avoided GC will not happen until the next compaction touches each sstable. We could fix this downside by keeping the supposed-to-be-GC'ed tombstone in separate sstables (which can be deleted en-mass when the shared sstables are gone), but this will complicate the code and I don't think that the benefit is worth it.

**Comment by avikivity** [comment]
Can you explain why we need to delay the deletion of the result sstables(s) too?

**Comment by slivne** [comment]
Sure ....

Here is a sample

2 shard system

start with sstable A shared - every other sstable not shared

Core 0   A , B, C  -- Compacted --> D (we do not delete A,B,C as A is
shared)
(holds key1)
Core 1   A

Core 0   D, E, F
(deletes key 1)
Core 1 A

grace period passes

Core 0 D,E,F -- Compacted --> G (we delete D,E,F - and remove tombstones
that exist in E,F)
(tombstone for key 1 is removed and key 1 data is removed)
Core 1 A
Shutdown

Reboot

Core 0 A, B, C, G
(key 1 is back to life - as it is from A,B,C and the tombstone covering it
is not in G)

**Comment by avikivity** [comment]
I see.  I guess we have to initiate a clean operation on all shared sstables when we start up.  We might even make those operations take precedence over regular compaction, and so compaction will only ever see unshared sstables.

It will make sstable loading more painful, but better than holding on to data files indefinitely.

**Comment by slivne** [comment]
Nadav's Idea of not GCing tombstones is one that can help and not stop
compactions while the cleanup / splitting to shards is still ongoing - in
this manner - some shards that have no shared files / finished processing
shared files can continue and compact regular files without causing an
issue.

**Comment by slivne** [comment]
we split shared ssatbles on boot ....
