### ISSUE TITLE
error: option '--logger-log-level' cannot be specified more than once

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#1320]
When adding multiple  --logger-log-level options to scylla, e.g.,

    scylla --logger-log-level storage_proxy=debug --logger-log-level storage_service=debug

I got

    error: option '--logger-log-level' cannot be specified more than once

This worked well in the past, I used it a lot in my scripts and it broke recently.

scylla commit: e25380347aac293f48502f46b8a27ece2896ead1

**Comment by asias** [comment]
@gleb-cloudius I saw you changed db/config.* recently. I can not revert and verify because scylla does not compile without them. Can you please take a look?

commit 9132604a90184fff2112c7cd1fe0492dfd1c8cc3
commit 1476becd28e2342e79ad4a49aa0402883118390d

**Comment by gleb-cloudius** [comment]
On Mon, Jun 06, 2016 at 04:13:59PM -0700, Asias He wrote:
> @gleb-cloudius I saw you changed db/config.* recently. I can not revert and verify because scylla does not compile without them. Can you please take a look?
> 
> commit 9132604a90184fff2112c7cd1fe0492dfd1c8cc3
> commit 1476becd28e2342e79ad4a49aa0402883118390d
> 
I can confirm that those patches are the problem.
You can revert seastar commit 61e15d611fe4eb3cff302211e922cd482c258829 
in addition for code to compile and work meanwhile.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
@elcallio can you look into it too? I am not sure what kind of magic is going on there.

**Comment by gleb-cloudius** [comment]
I've send a patch to fix this.

--
			Gleb.
