### ISSUE TITLE
Reduce bloom filter overhead during compaction

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1322]
Consulting bloom filters may take most of compaction's CPU time:

![compaction-profile](https://cloud.githubusercontent.com/assets/283695/15865643/dd882c32-2cdb-11e6-9575-42bd739d3e2c.png)

Compaction currently consults bloom filters of every sstable which is not being compacted, for every compacted partition. We could order sstables by key intervals and consult only those whose key interval overlaps with current key. This should reduce the overhead in workloads which generate sstables with mostly disjoint key ranges, for instance time series.

Another potential for optimization is to calculate key hash only once instead of for every sstable.

We could also try to calculate hashes in bloom_filter::indexes() lazily instead of up front into a vector, hoping to miss before exhausting all possible hashes.

**Comment by avikivity** [comment]
Wow.  I think sstable selection should be done by the compaction strategy; in non-leveled compaction strategies the extra checks will always fail and just waste cpu time.

If we calculate all the hashes up front, then we don't need the third optimization.

Another little optimization is to replace % by a 128-bit multiply + shift (see `shard_of()`) in case the `DIV` instruction is prominent.

**Comment by tgrabiec** [comment]
@avikivity Good points. I'm not sure though why you think we don't need the third optimization, can you elaborate?

**Comment by avikivity** [comment]
If you caclulate the hashes up-front you can reuse them across sstables, so instead of (number of sstables) * (number of hashes per table) you have max(number of hashes per table).

This is assuming the calculations can be reused, don't know if there are sstable-specific parameters.

**Comment by nyh** [comment]
This issue is closely related to issue #1185, which run into the same need in a different part of the code.

In the case here, in compaction, the code tries to make a correct decision of when we can delete expired tombstones: We cannot delete an expired tombstone if it is possible that one of the tables NOT being compacted might contain data for this key. So we currently check the bloom filter for all these sstables, but just like in issue #1185, we can avoid most of these filter lookups by using an interval map of the key ranges in each sstable. Alternatively, instead of a completely general interval map, the compaction strategy (e.g., LCS) can maintain a short vector of "levels", where each level contains a list of sstables with *disjoint* ranges. 

For the specific issue here, I don't think this "level" idea will buy any extra performance (both the interval map and the level array are O(logN)). I think the "level" idea will just add complications beyond the more "naive" interval map implementation?

**Comment by avikivity** [comment]
For leveled compaction reducing the number of sstables consulted will be an even bigger win, but for the other compaction strategies it won't help.

**Comment by slivne** [comment]
Tomek - what did your data look like - did you have tombstones at all -
maybe there is a bug and we do not understand it - nadav's explenation of
why we need to do it is in case we have tombstones - yet with default c-s
we do not generate tombstones - and even if your data did have tombstones
we need only past gc period if we want to gc the tombstone.

We may have an issue with range tombstones - that requires us to check
every element in the range to know if we can gc the range tombstone - maybe
that is the issueyou tackled in tour sample

**Comment by tgrabiec** [comment]
2016-06-07 22:58 GMT+02:00 Avi Kivity <notifications@github.com>:

> If you caclulate the hashes up-front you can reuse them across sstables,
> so instead of (number of sstables) * (number of hashes per table) you have
> max(number of hashes per table).
>
> This is assuming the calculations can be reused, don't know if there are
> sstable-specific parameters.
>

We can reuse murmur hash of the key, but I think we cannot in most cases
reuse calculated bloom filter indexes because each filter may have
different bitsize on which bloom hash functions depend.

**Comment by tgrabiec** [comment]
2016-06-07 23:46 GMT+02:00 Shlomi Livne <notifications@github.com>:

> Tomek - what did your data look like - did you have tombstones at all -
> maybe there is a bug and we do not understand it - nadav's explenation of
> why we need to do it is in case we have tombstones - yet with default c-s
> we do not generate tombstones - and even if your data did have tombstones
> we need only past gc period if we want to gc the tombstone.
>

I've ran plain "cassandra-stress write n=<large-number>", so no tombstones.

The bloom filters are consulted before mutations are merged/compacted
unconditionally to calculate max_purgeable_timestamp.

**Comment by slivne** [comment]
On Wed, Jun 8, 2016 at 10:11 AM, Tomasz Grabiec <notifications@github.com>
wrote:

> 2016-06-07 23:46 GMT+02:00 Shlomi Livne <notifications@github.com>:
>
> > Tomek - what did your data look like - did you have tombstones at all -
> > maybe there is a bug and we do not understand it - nadav's explenation of
> > why we need to do it is in case we have tombstones - yet with default c-s
> > we do not generate tombstones - and even if your data did have tombstones
> > we need only past gc period if we want to gc the tombstone.
> >
>
> I've ran plain "cassandra-stress write n=<large-number>", so no tombstones.
>
> The bloom filters are consulted before mutations are merged/compacted
> unconditionally to calculate max_purgeable_timestamp.
>

Ok I am lost - is there any other reason to compute the
max_purgable_timestamp of a key in the non comapcted sstables - other then
to not remove a a tombstone to be gc'd ?

It seems that currently we are computing this max_purgable_timestamp for
each patitionkey to be compacted ahead of time

                auto max_purgeable = get_max_purgeable_timestamp(_schema,
_not_compacted_sstables, m->decorated_key());
                m->partition().compact_for_compaction(*_schema,
max_purgeable, _now);


- so can we change the code and defer it to a point in which we actually
need it.

**Comment by nyh** [comment]
@slivne excellent point! If the max_purgable is expensive to calculate (in parallel, we can make it less expensive, and we should, but it will never be free), we should only calculate it when absolutely needed, i.e. when all of the following conditions hold:

  1. We found a tombstone, and
  2. The tombstone is expired (older than the gc period)

The combination of both conditions should be very rare: Some use cases (like Tomek's) don't actually have any tombstones, and others that do have tombstones will usually not see them expired (for most of their lifetime they won't be expired, and when they do expire compaction will often succeed to remove them so the next compaction won't see them again).

So calculating max_purgeable only when actually needed could be a big win - independent of speeding up its calculation.

**Comment by tgrabiec** [comment]
2016-06-08 9:43 GMT+02:00 Shlomi Livne <notifications@github.com>:

> On Wed, Jun 8, 2016 at 10:11 AM, Tomasz Grabiec <notifications@github.com>
> wrote:
>
> > 2016-06-07 23:46 GMT+02:00 Shlomi Livne <notifications@github.com>:
> >
> > > Tomek - what did your data look like - did you have tombstones at all -
> > > maybe there is a bug and we do not understand it - nadav's explenation
> of
> > > why we need to do it is in case we have tombstones - yet with default
> c-s
> > > we do not generate tombstones - and even if your data did have
> tombstones
> > > we need only past gc period if we want to gc the tombstone.
> > >
> >
> > I've ran plain "cassandra-stress write n=<large-number>", so no
> tombstones.
> >
> > The bloom filters are consulted before mutations are merged/compacted
> > unconditionally to calculate max_purgeable_timestamp.
> >
>
> Ok I am lost - is there any other reason to compute the
> max_purgable_timestamp of a key in the non comapcted sstables - other then
> to not remove a a tombstone to be gc'd ?
>
> It seems that currently we are computing this max_purgable_timestamp for
> each patitionkey to be compacted ahead of time
>
> auto max_purgeable = get_max_purgeable_timestamp(_schema,
> _not_compacted_sstables, m->decorated_key());
> m->partition().compact_for_compaction(*_schema,
> max_purgeable, _now);
>
>
> - so can we change the code and defer it to a point in which we actually
> need it.


Yes, we could calculate it lazily.

**Comment by avikivity** [comment]
Much better than micro-optimizing stuff.

**Comment by avikivity** [comment]
Much better than micro-optimizing stuff.

**Comment by avikivity** [comment]
(that's not to say I'm against micro-optimizing, in fact it's my favorite pastime)

**Comment by tgrabiec** [comment]
I think we still need this optimization for the sake of workloads in which tombstones are prevalent. In time series use case it could be that after a while every partition will have some tombstones and some gc-able tombstones.

**Comment by avikivity** [comment]
Makes sense.  But that's a second-order optimization, let's avoid the lookup when unneeded first.

**Comment by tgrabiec** [comment]
Bloom filter lookup has similar effect on cache update after memtable flush:

![bloom_filter_impact_on_cache_update](https://cloud.githubusercontent.com/assets/283695/16011183/a2e4199e-3184-11e6-95de-90c8501e29d6.png)

**Comment by slivne** [comment]
bloom filter should only be checked if we are trying to remove a tombstone there is no reason to check a bloom filter if tombstones are not being removed.

**Comment by slivne** [comment]
@tgrabiec , @raphaelsc - do we have all your changes in - for this - is there anything missing here.

**Comment by tgrabiec** [comment]
@slivne The only optimization which is in is the one to avoid accessing bloom filters when there are no GC-able tombstones. Notably, the interval_set optimization is not it. New version of the patch is expected.

**Comment by slivne** [comment]
@raphaelsc what is the status of this item ?

**Comment by raphaelsc** [comment]
On Tue, Sep 20, 2016 at 6:14 PM, Shlomi Livne <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> what is the status of this item
> ?
>
I delayed it to work on clustering key filter, but i should move back to it
tomorrow.

**Comment by slivne** [comment]
@raphaelsc ping
