### ISSUE TITLE
repair: delay streamed information from being visible

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1323]
@pdziepak  wrote:

As discussed on Today's daily call streaming introduces another opportunity to break isolation guarantees.

The particular problem is as follows:
Node A is streaming fragmented mutations to node B. B accumulates data in streaming memtable (which is not visible to writes). Then, at some point that memtable gets flushed and the resulting sstable is made visible. It is possible that the resulting sstable will contain only part of some mutation M while the rest of it is still on its way from A to B. Consequently, reads on node B may see a partial write.

This appears to be a problem only during repair, because streaming related to joining and decommissioning a node is done while the receiver node is not yet serving read requests for the streamed range.

My proposal to this solution is to delay making sstables visible until the streaming is complete (or sooner if we are able to track whether making a particular group of sstables will make partial mutations visible).

Answering the question I wasn't able to answer during the daily call: it appears that, despite quite different way of implementing streaming (sstables instead of mutations), C* also delays making streamed data visible until the task is complete [1].

[1] https://github.com/apache/cassandra/blob/849a438690aa97a361227781108cc90355dcbcd9/src/java/org/apache/cassandra/streaming/StreamReceiveTask.java#L141

**Comment by nyh** [comment]
I think there's a bug in this solution:

You are trying to ensure that a large mutation you read from the source machine is not visible on the target machine until it is all streamed. 
However, on the target machine, the large mutation is now split across two sstables.
So if the target machine later streams this data to a third machine, it now thinks it is streaming two separate mutations, and no longer guarantees the atomicity.

So the proposed fix does not solve the whole problem.

By the way, please also consider what happens in case of reboot after an sstable with a partial mutation was written. So these partial sstables need to be not only "invisible", they also need to be temporarily marked delete-on-reboot.

**Comment by pdziepak** [comment]
Scylla streams using a mutation_reader that combines all possible (and currently visible) sources of mutations. Their exact location of partition is not relevant as all its parts will get merged before it is ready to be send. So, no, having the same partition in two separate sstable won't make streaming consider it as two different partitions.

As for marking sstables for delete: yes, that's going to be needed to ensure that the won't become visible until the streaming is complete.

**Comment by tgrabiec** [comment]
2016-06-08 11:42 GMT+02:00 Shlomi Livne <notifications@github.com>:

> @pdziepak <https://github.com/pdziepak> wrote:
>
> As discussed on Today's daily call streaming introduces another
> opportunity to break isolation guarantees.
>
> The particular problem is as follows:
> Node A is streaming fragmented mutations to node B. B accumulates data in
> streaming memtable (which is not visible to writes). Then, at some point
> that memtable gets flushed and the resulting sstable is made visible. It is
> possible that the resulting sstable will contain only part of some mutation
> M while the rest of it is still on its way from A to B. Consequently, reads
> on node B may see a partial write.
>

Let's clarify that this is not a problem with current implementation of
streaming, which will stream and apply whole partitions. It will become a
problem once we stream and apply partial mutations, to support large
partitions.

**Comment by slivne** [comment]
Well it is potentially a problem for us and cassandra for batch statements that include more then one CF.

According to Pawel/Calle a batch statement that holds two updates in the same keyspace for 2 CFs using the same partition key will be merged to a single mutation (at least in C*).

As repair fixes deltas - it should keep this gurantee. 

If in repair both CFs are repaired and sstables are made available as they are written (even using whole partitions) - it can break the batch statement gurantee.

**Comment by slivne** [comment]
@pdziepak - do we nowneed to solve this (now that we stream mutation parts ?)

**Comment by pdziepak** [comment]
The problem with fragmented partitions was solved before it was actually introduced in the series that adapted streaming for `streamed_mutations` (i.e. de429d6a53963bf7e7d0bd7da121b4da46fc122f ). Verb `STREAM_MUTATION` has now an additional flag that, when set indicated that only a fragment of partition is sent and it mustn't be made visible until the streaming plan completes (this is at the cost of streaming write coalescing).

As for batch updates of partitions with the same partition key and in the same keyspace but in different CFs – well, we don't support that at all and there are much bigger problems with implementing that than preserving isolation while repairing, so it definitely deserves its own github issues. However, if we ever add support for that at least part of the solution for streamed mutations could be reused.

**Comment by slivne** [comment]
great :)

Q: 
> streaming plan completes 
Is that in partition level ? 

e.g. do we need to complete streaming all the partitions to make anything visible - in that case it means that we must hold all the sstables we are flushing too (and their maybe multiple ones based on the partition size and strategy) as temporary sstables - so that if we crash we will not boot and think we have data we can use - is that how is done ?

**Comment by pdziepak** [comment]
When mutation is sent with `fragmented` flag set it goes to memtable that is private for that streaming plan and when such memtable is flushed the resulting sstable won't be made visible until the streaming plan is completed (the sstable also is left unsealed until end of streaming plan so that it will be removed if the node crashes).
