### ISSUE TITLE
Backup procedure not working

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla#1337]
Scylla version (or git commit hash): 1.0
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL 7

I am trying to update Scylla to 1.1 but I am getting stumped on the backup.
Running snapshot gets me this:

```bash
nodetool snapshot
Requested creating snapshot(s) for [all keyspaces] with snapshot name [1465800864452]
Snapshot directory: 1465800864452
```

I cannot find such a directory anywhere so I am not sure what todo actually.
It is a test system so the data can be lost but this is sort of a trial run for the prod systems so I would like to establish the proper steps beforehand.

There are no coredumps reported and running with sudo doesn't make any difference.

Any ideas what to try or check?

**Comment by dahankzter** [comment]
I went ahead with the upgrade anyway and that seems tentatively to have worked fine as per the instructions.

**Comment by avikivity** [comment]
You'd find the snapshot directory in /var/lib/scylla/data/[keyspace]/[column-family]/snapshots/[snapshot-name] (one directory per column family).

**Comment by avikivity** [comment]
btw, congrats on the 1337 issue #.

**Comment by dahankzter** [comment]
Ahh now I see them, great! Thx!

Epic issue number indeed! :)

**Comment by avikivity** [comment]
@dmarti @tzach upgrade guide should be upgraded to better explain the location of the directories that need to be backed up.

Also need to document that the directories need to be removed, or the node will run out of space.

May need to add a `nodetool removesnapshot` command to assist in this.

**Comment by dahankzter** [comment]
That would be great since they have very complicated paths and in our case we generate a set of tables. Not many but still enough to force me to scroll in my normal terminal. :)

Perhaps something like
```bash
nodetool removesnapshot --prune
``` 
To remove all but the latest snapshot for all snapshots available.

**Comment by slivne** [comment]
create an issue for the enhamcenet request - closing this issue

**Comment by avikivity** [comment]
(closed by mistake -- the referenced commit does not fix the issue)

**Comment by slivne** [comment]
scylladb/www.scylladb.com#223
