### ISSUE TITLE
'sleep_aborted' error during Scylla shutdown

### ISSUE THREAD

**Issue by soyacz** [scylladb/scylla#13374]
## Issue description

- [ ] This issue is a regression.
- [X] It is unknown if this issue is a regression.

When stopping Scylla error messages `seastar::sleep_aborted` as an `!ERR` are appearing:
```
2023-03-09T15:01:24+00:00 longevity-5gb-1h-SoftRebootNodeMonk-db-node-45a5e563-1     !INFO | scylla[620]:  [shard 1] view - Draining view builder
2023-03-09T15:01:24+00:00 longevity-5gb-1h-SoftRebootNodeMonk-db-node-45a5e563-1      !ERR | scylla[620]:  [shard 0] view - start failed: seastar::sleep_aborted (Sleep is aborted)
2023-03-09T15:01:24+00:00 longevity-5gb-1h-SoftRebootNodeMonk-db-node-45a5e563-1      !ERR | scylla[620]:  [shard 1] view - start failed: seastar::sleep_aborted (Sleep is aborted)
2023-03-09T15:01:24+00:00 longevity-5gb-1h-SoftRebootNodeMonk-db-node-45a5e563-1  !WARNING | scylla[620]:  [shard 0] gossip - failure_detector_loop: Got error in the loop, live_nodes=[10.4.2.106, 10.4.1.224]: seastar::sleep_aborted (Sleep is aborted)
2023-03-09T15:01:24+00:00 longevity-5gb-1h-SoftRebootNodeMonk-db-node-45a5e563-1     !INFO | scylla[620]:  [shard 0] gossip - failure_detector_loop: Finished main loop
```
If this is not an error, remove it from logs or reduce severity.

## Impact

Fails SCT test and need to manually mark as passed if this is only error.

## How frequently does it reproduce?

1 out of 4 Scylla restarts in this test.

## Installation details

Kernel Version: 5.15.0-1030-aws
Scylla version (or git commit hash): `5.2.0~rc2-20230228.908a82bea064` with build-id `c5e4affd90a7c49c0dcf1a00c3b8bc72a367aba2`

Cluster size: 3 nodes (i4i.large)

Scylla Nodes used in this run:
- longevity-5gb-1h-SoftRebootNodeMonk-db-node-45a5e563-3 (34.244.151.205 | 10.4.2.106) (shards: 2)
- longevity-5gb-1h-SoftRebootNodeMonk-db-node-45a5e563-2 (34.253.184.100 | 10.4.1.224) (shards: 2)
- longevity-5gb-1h-SoftRebootNodeMonk-db-node-45a5e563-1 (52.215.89.35 | 10.4.2.235) (shards: 2)

OS / Image: `ami-07af3b969c1f912b8` (aws: eu-west-1)

Test: `longevity-5gb-1h-SoftRebootNodeMonkey-aws-test`
Test id: `45a5e563-c60d-4871-9b28-d5eed3f3c379`
Test name: `scylla-5.2/nemesis/longevity-5gb-1h-SoftRebootNodeMonkey-aws-test`
Test config file(s):

- [longevity-5gb-1h-SoftRebootNodeMonkey.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d26a40cc4d0a2135cd3363409b1df667ddc9b33b/test-cases/nemesis/longevity-5gb-1h-SoftRebootNodeMonkey.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor 45a5e563-c60d-4871-9b28-d5eed3f3c379`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=45a5e563-c60d-4871-9b28-d5eed3f3c379)
- Show all stored logs command: `$ hydra investigate show-logs 45a5e563-c60d-4871-9b28-d5eed3f3c379`

## Logs:
- **db-cluster-45a5e563.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/45a5e563-c60d-4871-9b28-d5eed3f3c379/20230309_154225/db-cluster-45a5e563.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/45a5e563-c60d-4871-9b28-d5eed3f3c379/20230309_154225/db-cluster-45a5e563.tar.gz)
- **sct-runner-45a5e563.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/45a5e563-c60d-4871-9b28-d5eed3f3c379/20230309_154225/sct-runner-45a5e563.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/45a5e563-c60d-4871-9b28-d5eed3f3c379/20230309_154225/sct-runner-45a5e563.tar.gz)
- **monitor-set-45a5e563.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/45a5e563-c60d-4871-9b28-d5eed3f3c379/20230309_154225/monitor-set-45a5e563.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/45a5e563-c60d-4871-9b28-d5eed3f3c379/20230309_154225/monitor-set-45a5e563.tar.gz)
- **loader-set-45a5e563.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/45a5e563-c60d-4871-9b28-d5eed3f3c379/20230309_154225/loader-set-45a5e563.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/45a5e563-c60d-4871-9b28-d5eed3f3c379/20230309_154225/loader-set-45a5e563.tar.gz)
- **parallel-timelines-report-45a5e563.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/45a5e563-c60d-4871-9b28-d5eed3f3c379/20230309_154225/parallel-timelines-report-45a5e563.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/45a5e563-c60d-4871-9b28-d5eed3f3c379/20230309_154225/parallel-timelines-report-45a5e563.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.2/job/nemesis/job/longevity-5gb-1h-SoftRebootNodeMonkey-aws-test/6/)
</details>

**Comment by mykaul** [comment]
Isn't this a Seastar issue?

**Comment by bhalevy** [comment]
> Isn't this a Seastar issue?

How come?
The error is logged by the scylla view builder which needs to vet about the exception it got from the aborted sleep.
Seastar api contract is to generate this exception. It can't decide for the user if it's cobsidered an error or not.

**Comment by soyacz** [comment]
we can tune SCT to ignore these errors, but if this is not actual error, better to remove it/reduce severity in db logs to not scare users.

**Comment by mykaul** [comment]
> > Isn't this a Seastar issue?
> 
> How come? The error is logged by the scylla view builder which needs to vet about the exception it got from the aborted sleep. Seastar api contract is to generate this exception. It can't decide for the user if it's cobsidered an error or not.

In the sense that an aborted sleep might not be an error.

**Comment by bhalevy** [comment]
> > > Isn't this a Seastar issue?
> > 
> > 
> > How come? The error is logged by the scylla view builder which needs to vet about the exception it got from the aborted sleep. Seastar api contract is to generate this exception. It can't decide for the user if it's cobsidered an error or not.
> 
> In the sense that an aborted sleep might not be an error.

That's up to the caller to decide.

If the seastar api supported returning this as a non-error status we could have avoided the error condition, but sleep abortable is defined to return valueless `future<>` so the abort status is conveyed as an error.

In hindsight maybe we should provide a `sleep_until` primitive that checks any condition variable using a functor and return `future<bool>` saying if the condition predicate returned true or false if the timeout expired.
Then, abort_source could be used just to signal the condition variable and the predicate can just check if abort was requested.

Cc @avikivity @nyh @gleb-cloudius

**Comment by avikivity** [comment]
Backported to 5.1, 5.2.
