### ISSUE TITLE
Cannot downgrade package with apt-get on ubuntu

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1343]
Seems like the `Packages` file only contains the latest version, so it is impossible to downgrade.

**Comment by benoit-canet** [comment]
We would have trouble downgrading with the scylla-conf/scylla.yaml split
anyway.

I solved this by doing remove/install in the procedures.

**Comment by avikivity** [comment]
I'm talking about a patch level downgrade (1.1.2->1.1.1)

**Comment by avikivity** [comment]
Issue also applied to rpm.  On a 1.2.1 installation, I can't do `yum downgrade scylla-server-1.2.0`.

**Comment by tzach** [comment]
@syuu1228 is this issue still valid?

**Comment by slivne** [comment]
the repo file holds all versions - this should be working now - please note that we do not support full cluster downgrade only a rollback durring an upgrade.

**Comment by amoskong** [comment]
@slivne 
I manually checked both centos and ubuntu, we can find all history release there:
- 1.0.0 ~ 2.0.1 are all contained in branch-x.y repo
- 0.9 ~ 1.0.x are all contained in branch-1.0 repo

So we don't need to back up the packages for rollback in maintainance release upgrading.
I will test and upgrade the docs.

**Comment by slivne** [comment]
The issue is not only to find the artifacts but also to be able to use the
commands - directly and not a "hack" to access packages

**Comment by amoskong** [comment]
For CentOS:
- `sudo yum downgrade scylla-2.0.1` , doesn't work (created issue #3050)
- `sudo yum downgrade scylla\*-2.0.1`, works well.
- `sudo yum upgrade scylla-2.0.1`, works well.
- `sudo yum upgrade scylla\*-2.0.1` (issue #3050)

For Ubuntu 16:
- `sudo apt-get dist-upgrade scylla=2.0.2\*`, works well.
- `sudo apt-get downgrade scylla=2.0.1`, Failed: no `downgrade` sudcmd
- `sudo apt-get install scylla=2.0.0`, Failed, E: Version '2.0.0' for 'scylla' was not found
- `sudo apt-get install scylla=2.0.1\* scylla-server=2.0.1\* scylla-jmx=2.0.1\* scylla-tools=2.0.1\* scylla-tools-core=2.0.1\* scylla-kernel-conf=2.0.1\*  scylla-conf=2.0.1\*`, works well.
- `sudo apt-get install scylla=2.0.1\*`, Failed, only one scylla package was downgraded (create issue #3052)

**Comment by amoskong** [comment]
Related https://github.com/scylladb/scylla/issues/3047

What's the right way to process the conf files?   scylla-kernel-conf, scylla-conf

> @benoit-canet commented on Jun 14, 2016
> 
> We would have trouble downgrading with the scylla-conf/scylla.yaml splitanyway.I solved this by > doing remove/install in the procedures.

**Comment by slivne** [comment]
@syuu1228 can you please help here - it should be possible to downgrade somehow
