### ISSUE TITLE
Schedule fstrim

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1347]
Scylla doc recommended running `fstrim` regularly by adding it to cron 
http://www.scylladb.com/doc/admin/#schedule-fstrim

It should be part of scylla_setup

**Comment by tzach** [comment]
@avikivity ?

**Comment by avikivity** [comment]
yes?

**Comment by slivne** [comment]
lets add this to the houskeeping - lets check what happens when this is run (how does it affect scylla performance)
