### ISSUE TITLE
ScyllaDB increasing system load

### ISSUE THREAD

**Issue by PriyaGheewala** [scylladb/scylla#1351]
ScyllaDB is increasing system load very high (up to 80 on a 40 core machine).Even though we are not performing any operations. Nothing is being inserted to scyllaDB and we are even not able to read the data from scyllaDB.

Installation details
Scylla version (or git commit hash):1.1
Cluster size:1
OS (RHEL/CentOS/Ubuntu/AWS AMI):CentOs 7

Hardware details (for performance issues) :

Platform (physical/VM/cloud instance type/docker): Physical
Hardware: sockets= cores= hyperthreading= memory=32 GB
processor : 39
vendor_id : GenuineIntel
cpu family : 6
model : 62
model name : Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz

Disks: (SSD/HDD, count): 2X SSD

Please let me know if you need any other information.

**Comment by avikivity** [comment]
A load of 80 on 20c/40t is strange.  It should never be much higher than 40.

Is there anything in dmesg or the system log?

If there is nothing interesting, please run the following sequence:

    echo 9 > /proc/sysrq-trigger
    echo 255 > /proc/sys/kernel/sysrq 
    echo w > /proc/sysrq-trigger 
    dmesg > dmesg.txt

and attach `dmesg.txt`.

**Comment by tzach** [comment]
@PriyaGheewala did you had a chance to capture the info @avikivity suggested?
