### ISSUE TITLE
Node running out of disk space does not disconnect from the cluster

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1353]
Scylla version: 1.1.3-rc1

the node does close down the cql connection

```
Data.db:level=1, /var/lib/scylla/data/keyspace1/standard1-620372d0338c11e68b39000000000001/keyspace1-standard1-ka-274-Data.db:level=0, ]
Jun 16 06:56:13 ip-10-37-213-60 scylla[19227]:  [shard 0] storage_service - Shutting down communications due to I/O errors until operator intervention
Jun 16 06:56:13 ip-10-37-213-60 scylla[19227]:  [shard 0] database - failed to write sstable: storage_io_error (Storage io error errno: 28)
Jun 16 06:56:13 ip-10-37-213-60 scylla[19227]:  [shard 0] compaction - Compaction found an exception when writing sstable /var/lib/scylla/data/keyspace1/standard1-620372d0338c11e68b39000000000001/keyspace1-standard1-ka-748-Data.db : storage_io_error (Storage io error errno: 28)
Jun 16 06:56:13 ip-10-37-213-60 scylla[19227]:  [shard 0] compaction_manager - compaction failed: read exception: seastar::broken_pipe_exception (Broken pipe), write_exception: storage_io_error (Storage io error errno: 28)
Jun 16 06:56:13 ip-10-37-213-60 scylla[19227]:  [shard 0] compaction_manager - compaction task handler sleeping for 5 seconds
Jun 16 06:56:14 ip-10-37-213-60 scylla[19227]:  [shard 0] storage_service - CQL server stopped
```

the node does not close down communication with other nodes

```
on the other node in the cluster

ubuntu@ip-10-63-76-132:~$ nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens  Owns    Host ID                               Rack
UN  10.37.213.60  69.09 GB   256     ?       7ed5a3cd-1ea5-4280-b108-f3c88fafda6a  rack1
UN  10.63.76.132  74.33 GB   256     ?       5816f8fd-d595-42b4-82c6-e02ebf5cc1fd  rack1
```

how to reproduce

create a cluster of 2 servers
one of them with a smaller disk
run a load using

``` cassandra-stress write n=50000000 -mode cql3 native -schema compaction\(strategy=LeveledCompactionStrategy\) compression=LZ4Compressor "replication(factor=2)" -col size=FIXED\(2048\) n=FIXED\(5\) -pop seq=1..10000000 -node `hostname -i`
```

when the node with the lower disk space runs out of disk - try to connect with cql - its not possible

check with netstat that connection to other nodes is down 

check with nodetool status that other nodes think the node is down

```
ubuntu@ip-10-37-213-60:~$ netstat -a -n | grep 7000
tcp        0      0 10.37.213.60:7000       0.0.0.0:*               LISTEN     
tcp        0      0 10.37.213.60:7000       10.63.76.132:48245      ESTABLISHED
tcp        0      0 10.37.213.60:7000       10.63.76.132:45150      ESTABLISHED
tcp        0      0 10.37.213.60:40047      10.63.76.132:7000       ESTABLISHED
tcp        0      0 10.37.213.60:39236      10.63.76.132:7000       ESTABLISHED
tcp        0      0 10.37.213.60:7000       10.63.76.132:48610      ESTABLISHED
tcp        0      0 10.37.213.60:7000       10.63.76.132:58978      ESTABLISHED
tcp        0      0 10.37.213.60:41012      10.63.76.132:7000       ESTABLISHED
tcp        0      0 10.37.213.60:7000       10.63.76.132:52343      ESTABLISHED
tcp        0      0 10.37.213.60:7000       10.63.76.132:43436      ESTABLISHED
tcp        0      0 10.37.213.60:7000       10.63.76.132:56520      ESTABLISHED
tcp        0      0 10.37.213.60:7000       10.63.76.132:59013      ESTABLISHED
tcp        0      0 10.37.213.60:38189      10.63.76.132:7000       ESTABLISHED
tcp        0      0 10.37.213.60:7000       10.63.76.132:50757      ESTABLISHED
tcp        0      0 10.37.213.60:60218      10.63.76.132:7000       ESTABLISHED
tcp        0      0 10.37.213.60:7000       10.63.76.132:51041      ESTABLISHED
tcp        0      0 10.37.213.60:7000       10.63.76.132:33913      ESTABLISHED
tcp        0      0 10.37.213.60:7000       10.63.76.132:60524      ESTABLISHED
ubuntu@ip-10-37-213-60:~$ 
```

**Comment by penberg** [comment]
Port 7000 is the inter-node RPC protocol, not CQL protocol. I don't see "messaging_service stopped" in the logs so I guess we fail to do that when we run out of disk space. Ping @asias @gleb-cloudius

**Comment by slivne** [comment]
I know that 7000 is the inter comm and it alignes with nodetool reporting all are up and happy

**Comment by gleb-cloudius** [comment]
On Thu, Jun 16, 2016 at 12:11:23AM -0700, Pekka Enberg wrote:
> Port 7000 is the inter-node RPC protocol, not CQL protocol. I don't see "messaging_service stopped" in the logs so I guess we fail to do that when we run out of disk space. Ping @asias @gleb-cloudius 
> 
I have no idea what node does when it runs out of disk space, but it is
definitely not messaging service responsibility to handle it in any
special way. Whoever handles the error does a bad job of it. Does it
call drain_on_shutdown()?

--
			Gleb.

**Comment by penberg** [comment]
@slivne So what do you mean by "the node does close down the cql connection"? AFAICT, there's no connection to CQL here.

**Comment by penberg** [comment]
@gleb-cloudius It does this:

```
void storage_service::do_isolate_on_error(disk_error type)
{
    auto& cfg = _db.local().get_config();
    bool must_isolate = cfg.disk_failure_policy() == "stop";

    if (type == disk_error::commit) {
        must_isolate = cfg.commit_failure_policy() == "stop";
    }

    if (must_isolate && !isolated.exchange(true)) {
        logger.warn("Shutting down communications due to I/O errors until operator intervention");
        // isolated protect us against multiple stops
        service::get_storage_service().invoke_on_all([] (service::storage_service& s) { s.stop_native_transport(); });
    }
}
```

**Comment by gleb-cloudius** [comment]
do_isolate_on_error() only calls s.stop_native_transport() (no thrift
stopping, no messaging service stopping). The result is unsurprising.

--
			Gleb.

**Comment by penberg** [comment]
@gleb-cloudius Is ``drain_on_shutdown()`` the right thing to here, though? Remember, it's a out of disk space error that we're hitting here (or some other I/O issue).

**Comment by gleb-cloudius** [comment]
On Thu, Jun 16, 2016 at 12:26:41AM -0700, Pekka Enberg wrote:
> @gleb-cloudius Is ``drain_on_shutdown()`` the right thing to here, though? Remember, it's a out of disk space error that we're hitting here (or some other I/O issue).
> 
Not really, ``drain_on_shutdown()`` does IO too AFAIK. We can provide it
a flag that disables IO part, or split to two function.

--
			Gleb.

**Comment by penberg** [comment]
@gleb-cloudius @slivne I sent an RFC to the mailing list to implement the latter proposal from Gleb.
