### ISSUE TITLE
nodetool drain does not close intra node communication

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1355]
1. ccm create scylla-3 --scylla --vnodes -n 3 ...
2. ccm start
3. ccm node1 stress write duration=1h -mode cql3 native -schema "replication(factor=3)"

in another window

1. ccm node3 nodetool drain
2. ccm node2 nodetool status 

node3 is down

```
shlomi@localhost~/urchin-ccm (branch-1.2)$ ccm node2 nodetool status

Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens  Owns    Host ID                               Rack
UN  127.0.0.1  157.63 MB  256     ?       1344f4f4-a549-4ab4-85c5-191fded8ea34  rack1
UN  127.0.0.2  175.03 MB  256     ?       00f5235b-b2b8-471f-8ee2-8f7da89cdb38  rack1
DN  127.0.0.3  148.17 KB  256     ?       0a42b575-7c03-4e23-802b-60c5aed605c5  rack1
```

yet the rpc connections are still open

```
 netstat -n | grep 7000
tcp        0      0 127.0.0.1:38419         127.0.0.3:7000          ESTABLISHED
tcp     7870      0 127.0.0.3:7000          127.0.0.1:38419         ESTABLISHED
tcp        0      0 127.0.0.1:33517         127.0.0.2:7000          ESTABLISHED
tcp        0      0 127.0.0.2:41544         127.0.0.3:7000          ESTABLISHED
tcp     1120      0 127.0.0.2:7000          127.0.0.1:33517         ESTABLISHED
tcp        0      0 127.0.0.2:7000          127.0.0.1:58129         ESTABLISHED
tcp        0      0 127.0.0.1:7000          127.0.0.2:32964         ESTABLISHED
tcp        0      0 127.0.0.1:7000          127.0.0.2:49185         ESTABLISHED
tcp        0      0 127.0.0.2:49185         127.0.0.1:7000          ESTABLISHED
tcp        0      0 127.0.0.1:58129         127.0.0.2:7000          ESTABLISHED
tcp     8680      0 127.0.0.3:7000          127.0.0.2:41544         ESTABLISHED
tcp        0      0 127.0.0.2:32964         127.0.0.1:7000          ESTABLISHED
```

this does not align with 

https://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsDrain.html

> Flushes all memtables from the node to SSTables on disk. Cassandra stops listening for connections from the client and other nodes. You need to restart Cassandra after running nodetool drain. You typically use this command before upgrading a node to a new version of Cassandra. To simply flush memtables to disk, use nodetool flush.

**Comment by slivne** [comment]
if we are only having the port open and not accepting connections then this is not a high prio item

**Comment by gleb-cloudius** [comment]
On Thu, Jun 16, 2016 at 04:14:17AM -0700, Shlomi Livne wrote:
> if we are only having the port open and not accepting connections then this is not a high prio item
> 
Yes, this should be the case, but the patch to close the port is in seastar already anyway.

--
			Gleb.

**Comment by slivne** [comment]
@gleb-cloudius  is seastar merged upstream - can we close this issue

**Comment by gleb-cloudius** [comment]
On Wed, Jun 22, 2016 at 06:59:06AM -0700, Shlomi Livne wrote:
> @gleb-cloudius  is seastar merged upstream - can we close this issue
> 
If "nodetool drain" calls drain_on_shutdown() then yes.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Wed, Jun 22, 2016 at 05:01:32PM +0300, Gleb Natapov wrote:
> On Wed, Jun 22, 2016 at 06:59:06AM -0700, Shlomi Livne wrote:
> > @gleb-cloudius  is seastar merged upstream - can we close this issue
> > 
> If "nodetool drain" calls drain_on_shutdown() then yes.
> 
It does not, but it calls ss.do_stop_ms() which closes the port, so we
can close this.

--
			Gleb.
