### ISSUE TITLE
Support ByteOrderedPartitioner

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#1356]
Scylla version (or git commit hash): 1.2 release

We're missing two functions (byte_ordered_partitioner::describe_ownership() and byte_ordered_partitioner::midpoint()) which are required in order to be able to create cluster with this partitioner (Pawel indicated that it was originally written just to pass some of the single node cql dtests).

**Comment by ddorian** [comment]
Might want to merge with https://github.com/scylladb/scylla/issues/984 ?
Though that issue is supposed to be with automatic-range-splitting like bigtable/hbase/etc. While the byteordered partitioner implemented in cassandra kinda sucks compared to that feature-request.

**Comment by dorlaor** [comment]
We got a request from a user asking for the exact compatible byte-ordered partitions from C*.
I guess this is where we'll start, later on we should optimize them further.

**Comment by asias** [comment]
Fixed by 9c27b5c46ed892ff1526c3bc1e61fdb46d158feb.

Duplication of  #1378
