### ISSUE TITLE
Scylla reports CQL 3.2.0 version to drivers

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#1358]
*Installation details*
Scylla version (or git commit hash): master

Scylla supports CQL 3.2.1 but reports 3.2.0 to the drivers. This means that upstream 'cqlsh' from Cassandra 2.1.14, for example, doesn't work.

**Comment by slivne** [comment]
there is no goal to support cassandra 2.1.14

users should ONLY use the tools provided by scylla (cqlsh,
cassandra-stress, nodetool) - the fact that a user may connect with cqlsh
from 2.1.14 - does that mean he will be able to use nodetool or
cassandra-stress (the answer is no in both cases).

We can decide to broadacst support for CQL3.2.1 - but cqlsh has nothing
todo with it.
