### ISSUE TITLE
Support Cassandra lightweight transactions (LWT)

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1359]
Lightweight transactions (LWT), aka compare and set transactions, ensure transaction isolation beyond eventual consistency. LWT are useful in cases where two or more clients needs to create the same entity, resulting in one, and only one, entity.

https://docs.datastax.com/en/cassandra/2.1/cassandra/dml/dml_ltwt_transaction_c.html

**Comment by bobymicroby** [comment]
Hi @tzach , Do you think there are any chances this is coming before 2.0 ?

**Comment by npenkov** [comment]
+1

**Comment by kant111** [comment]
https://issues.apache.org/jira/browse/CASSANDRA-6246 . I hope ScyllaDB implements this or better!

**Comment by tzach** [comment]
C* 3.6 added CAS info to `Nodetool proxyhistograms`
https://issues.apache.org/jira/browse/CASSANDRA-11507

**Comment by p2k** [comment]
I'd literally do anything to get this one working. If you could tell me how to start and in which direction you'd like this to go, I'd give my programming skills a try. It might take me weeks or months, but I want this so much I don't care ❤️

**Comment by ssboisen** [comment]
Any update on the progress on this issue? I just saw your progress on materialized views preview in 2.0, are we lucky enough to be getting LWT too? 😏

**Comment by tzach** [comment]
@ssboisen not in 2.0, we plan to have experimental LWT at 2.3

**Comment by ssboisen** [comment]
@tzach alright, thank you for replying :-) I'm very much looking forward to that, at Lix our datamodel rely heavily on LWTs as we use an event based architecture were we use cassandra to guarantee consistency of total order of the events inside a partition so we can't move to scylla before LWTs :)

**Comment by dnrusakov** [comment]
+ 1

**Comment by mrusme** [comment]
Is this available in [2.3-rc1](
https://github.com/scylladb/scylla/releases/tag/scylla-2.3.rc1) as an experimental feature? Apparently @kong relies on this feature for a couple of things and [does not work](https://github.com/Kong/kong/issues/3695) without it.

**Comment by duarten** [comment]
It is not, the feature is still in the design stage.

**Comment by guodaxia103** [comment]
Looking forward to this feature

**Comment by appurist** [comment]
I ran into this overnight, was a bit surprised to find that an `IF NOT EXISTS` triggered the `Not implemented: LWT` error.  In hindsight I think I understand how complex it is to resolve this without incurring large performance penalties.  Still, penalty or not, this is a fairly significant Cassandra incompatibility that should be resolved as soon as possible, perhaps just with a large performance impact warning, or with significant restrictions (e.g. verified only on the node with the matching partition key). 

I believe I can work around this limitation (drop all my `IF NOT EXISTS`) but in cases where I need to know to continue, it will be much less efficient to pre-query the current status at my end than at the Scylla server end. Please implement at least `IF NOT EXISTS` on `INSERT` as soon as possible.

**Comment by ayZagen** [comment]
It would be great to have this in ScyllaDb

**Comment by dorlaor** [comment]
The prior msg said that once 3.0 ships we can focus on LWT and that's what
we do.
3.0 is complete and just in the last cycles of QA and we'll double down on
LWT asap

**Comment by WayneWang12** [comment]
I'm using Lagom in my application. I thought I can change my backend to Syclla which may improve application's performance. However I get across this problem. It says:
```
Caused by: com.datastax.driver.core.exceptions.ServerError: An unexpected error occurred server side on /127.0.0.1: Not implemented: LWT
```

Looking forward this feature.

**Comment by dorlaor** [comment]
We finally started coding it, after finalizing the design. Estimations
(positive) are around 3-4 months

**Comment by sumannewton** [comment]
Is LWT available in latest Scylla version -3.0.3? Or is it still in the implementation phase?

**Comment by tzach** [comment]
> Is LWT available in latest Scylla version -3.0.3? Or is it still in the implementation phase?

LWT still in an implementation phase, and patch release does *not* include new features.
You can follow this issue to see when commits are merged to master branch, a prerequisite for a release.

**Comment by JasonZhang95** [comment]
Hope LWT feature will be implemented soon !

**Comment by NicolasRouquette** [comment]
Like @WayneWang12 I ran into the same `Not Implemented: LWT` error with my Lagom application.
I am particularly interested in Scyllab because it could be more cost-effective to deploy in the cloud as an event persistence database than Cassandra.

**Comment by dorlaor** [comment]
The first patches were sent in the last week, but it will take time to
complete the feature and get to GA level.
Thanks for your interest, it's top priority!

**Comment by rhessing** [comment]
Hi @dorlaor thank you for making this a top priority, could you please share the repo with me for the current status?

**Comment by dorlaor** [comment]
Development is slow but progressing, 4 days ago a major patch was send to
scylladb-dev mailing list (it's public) about the raft interfaces and
we just hired a very experienced additional programmer to help out

**Comment by combinio** [comment]
Howdy! :) Since we discovered Scylla, we'd love to move on, but LWT is I believe the most basic module. My question is, are there any news when we can expect CAS implemented (approximately)? I.e. in a month, in 6 months, a year etc.? :)

**Comment by dorlaor** [comment]
We've done progress and also have another key person on the job, I think that by the Scylla summit (November) we'll have a beta+ release (without over promising)

**Comment by combinio** [comment]
@dorlaor , thank You for quick reply. Can't wait for it! :heart: You're doing GREAT JOB! :wink:

**Comment by hdzh** [comment]
@tzach @dorlaor or anyone, what the status of LWT development? Any release date?

**Comment by tzach** [comment]
> @tzach @dorlaor or anyone, what's the status of LWT development? Any release date?

Its under active development by @kostja team
The plan is to share early access in the new 2 months or so, and have it as a part of a later offical release.

**Comment by hdzh** [comment]
Thanks @tzach. Any timeline to get LWT in Alternator too?

**Comment by dorlaor** [comment]
To be more accurate, some of the patches got committed yesterday, some on our way in.
https://github.com/scylladb/scylla/commit/c6b66d197bfb1114542749d7a1062eea756d44e7

**Comment by tzach** [comment]
@hdzh once LWT is merged, we can better evlaute the work for Alternator. 
Follow #5054 for updates.

**Comment by kostja** [comment]
Merged to master. The follow up master ticket to track performance optimizations, enhancements, and testing is #5202 . The feature is still experimental and will be available under --experimental switch.

**Comment by slivne** [comment]
Once it moves out of experimental we can close the issue - till then it needs to remain openned

**Comment by tzach** [comment]
Experimental flag removed in
https://github.com/scylladb/scylla/commit/9948f548a582422876a133b23c9cf86efb823d40
