### ISSUE TITLE
Scriptled failed while installing Scylla 1.2 on RHEL

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#1360]
*Installation details*
Scylla version (or git commit hash): 1.2
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL 7.2 / AWS

I saw the following error when running ``yum install scylla``:

```
/var/tmp/rpm-tmp.nMvFkI: line 1: fg: no job control
warning: %post(scylla-kernel-conf-1.2.0-20160614.c384b23.el7.centos.x86_64)
scriptlet failed, exit status 1
Non-fatal POSTIN scriptlet failure in rpm package
scylla-kernel-conf-1.2.0-20160614.c384b23.el7.centos.x86_64
```

**Comment by lmr** [comment]
One thing that occurs to me is that, unless the yum install command returns !=0 here, the automated test won't know  that we have something wrong, unless we scour the install command output looking for failures (pattern matching).

**Comment by lmr** [comment]
I have a Pull Request for scylla-artifact-tests that should make this type of bug detectable through automated testing, see

https://github.com/scylladb/scylla-artifact-tests/pull/25

**Comment by avikivity** [comment]
Very surprising bug.  The scriptlet is trivial.

**Comment by avikivity** [comment]
Guess: %sysctl_apply does not exist on 7.0, where we build, but does exist on 7.2, where we run.

**Comment by avikivity** [comment]
On 7.2:

```
[root@885d03ec2cf5 /]# grep -r -A2  sysctl_apply /usr/lib/rpm/
/usr/lib/rpm/macros.d/macros.systemd:%sysctl_apply() \
/usr/lib/rpm/macros.d/macros.systemd-/usr/lib/systemd/systemd-sysctl %{?*} >/dev/null 2>&1 || : \
/usr/lib/rpm/macros.d/macros.systemd-%{nil}
```

**Comment by avikivity** [comment]
Confirmed, we should either build on 7.2 (losing the ability to install on 7.0) or stop using %sysctl_apply.
