### ISSUE TITLE
Allow reads from incomplete SSTables

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#1365]
We currently can only read from an SSTable if it is completely sealed.

There is pressing need to change that so we can behave better under memory pressure conditions. However, there are also other important improvements that could be unlocked by having this functionality.

@avikivity describes one of them in #1363, and we could also delete compaction sstables sooner if they were already fully consumed, even if there resulting SSTable is not yet ready.

Things that can prove challenging for this implementation:
- write-behind: We are currently disabling seastar's write behind, but we would like to eventually enable it. It may prove challenging to do it if we are reading from incomplete SSTables, since we can only read from it if we are sure data has hit the disk. That gets more complex with write behind and may need additional Seastar infrastructure
- cache management: we currently update the cache only when the SSTable is fully written to. At that moment we know that the memtable is no longer used and can just merge the memtable's region into the cache's, which makes moving data into the cache cheaper. We can't do that if the memtable is not yet ready to go.
- deleted data: for the standard memtable write case, if we fail to write, the data is still in the commitlog, so it's fine to crash. If we really want to use this for compaction, that is trickier: the new SSTables may not be readable after a reboot because not all components may be available. Some components can be reconstructed from a Data + Index file (we already do that with the Summary), others are trickier.

**Comment by raphaelsc** [comment]
@glommer: we discarded this completely right? if so @slivne this can be closed

**Comment by glommer** [comment]
This will certainly not happen in the current file format, and the memory management routines we have now - which were one of the  main reasons for me to propose this are good enough now

**Comment by avikivity** [comment]
We won't do this. Incremental compaction strategy (enterprise only) offers the advantages (and even some more, such as incremental deletion of the compaction source data) in an easier way.
