### ISSUE TITLE
Selecting the same column twice will trigger an assert

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#1367]
_Installation details_
Scylla version (or git commit hash): master

Selecting the same column twice in a CQL query will result in an assert being triggered. For example, `select r1, r1 from cf where p1 = 'key1' and c1 = 1`. This results in:

Assertion `row.size() == _metadata->value_count()` failed in cql3::result_set::add_row.

We probably need to map a column to the multiple positions it can appear on in the query.

Note that the same thing happens if we specify the same restriction multiple times, like: `select r1 from cf where p1 = 'key1' and c1 = 1 and c1 = 1`.

**Comment by duarten** [comment]
@tzach I think this should be labeled as bug, right?

**Comment by tzach** [comment]
> I think this should be labeled as bug, right?

yes it is

**Comment by lmr** [comment]
I added a test in dtest to make sure once this bug is fixed, we don't recur into it.

**Comment by GpStore** [comment]
I know the latest 1.4.1 has fixed the bug, my env is 1.4 now,  do you suggest I upgrade the version 1.4 to 1.4.1? if yes, where to got the rpms of 1.4.1, and what is your suggestion on upgrading standard of scylla , all the new versions i need to upgrade it in my env ? thanks！

**Comment by penberg** [comment]
@GpStore Yes, you should upgrade to 1.4.1. The same upgrade procedure from 1.3 to 1.4 applies here:

http://www.scylladb.com/doc/upgrade-from-1.3-to-1.4-rpm/

**Comment by GpStore** [comment]
do you mean:

   sudo yum update scylla\* -y

can get the latest 1.4.1 rpms？

**Comment by penberg** [comment]
@GpStore Yes, assuming that you installed Scylla from our RPM repository.
