### ISSUE TITLE
Compaction - additional management to assure better compaction scheduling

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#137]
Currently there is no item limiting or scheduling compaction according to expected benefit and resource  need 

extracted from "[PATCH urchin v2] db: introduce compaction manager"
.
.
.
from Nadav:

It's not just an issue of "major" vs "minor" compaction (if anybody is even using "major" compaction). Even a "minor" compaction can involve, when you're unlucky enough, very big sstables and take a long time.

So it might make sense to start a small compaction even though big compactions are already running, and then throttle the different compactions (run a bit from this, a bit from that) - the small compaction will quickly finish and leave the long compaction to continue running alone.

**Comment by raphaelsc** [comment]
@slivne we need to remember to close this after @glommer's patchset is in

**Comment by glommer** [comment]
All glommer's patchset are in.
