### ISSUE TITLE
Too many timeout issues in version 1.2

### ISSUE THREAD

**Issue by PriyaGheewala** [scylladb/scylla#1370]
Hi,
we are getting too many timeout issues in scyllaDB version 1.2

Installation details
Scylla version (or git commit hash):1.2
Cluster size:1
OS (RHEL/CentOS/Ubuntu/AWS AMI):CentOs 7

Hardware details (for performance issues) :

Platform (physical/VM/cloud instance type/docker): Physical
Hardware: sockets= cores= hyperthreading= memory=32 GB
processor : 39
vendor_id : GenuineIntel
cpu family : 6
model : 62
model name : Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz

Disks: (SSD/HDD, count): 2X SSD

**Comment by avikivity** [comment]
Can you describe your schema and load?  In particular, whether you are querying large partitions, and whether you are timing out on reads or writes.

How many ops/sec are you pusing?

**Comment by PriyaGheewala** [comment]
@avikivity 

We are using scylla for storing a lot of users' information based on some tags. Currently we are not reading from scylla. We are just writing data to scylla for now.

we are pushing around 19K records/sec

**Comment by avikivity** [comment]
What is the size of each write?

Please attach the output of 'vmstat 1' during the load.

**Comment by PriyaGheewala** [comment]
The size of each write is just a few bytes.
The output of vmstat 1 is as follows:

procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
20  0 1029836 22415892      0 4902224    0    0    24   117    0    0  7  2 91  0  0
26  0 1029836 22404068      0 4913404    0    0     0   208 149223 941405 33 14 53  0  0
 9  0 1029836 22396096      0 4925064    0    0     0    72 154893 956265 34 14 52  0  0
19  0 1029836 22385100      0 4937172    0    0     0    48 149051 955109 33 14 53  0  0
25  0 1029836 22371528      0 4947772    0    0     0   166 137658 871663 34 12 54  0  0
22  0 1029836 22462420      0 4856248    0    0     0   132 142751 905034 32 13 55  0  0
19  0 1029836 22450848      0 4867148    0    0     0   115 147472 931947 33 14 54  0  0
25  0 1029836 22439304      0 4877596    0    0     0   111 147982 942536 33 14 53  0  0
18  0 1029836 22434304      0 4888896    0    0     0   195 147547 930884 33 14 53  0  0
15  0 1029836 22425048      0 4899868    0    0     0     0 147918 938612 33 14 53  0  0
20  0 1029836 22410256      0 4910760    0    0     0 102820 142989 882461 33 13 54  0  0
 1  0 1029836 22400544      0 4921832    0    0     0    97 146253 909665 33 13 54  0  0
21  0 1029836 22393972      0 4932316    0    0     0    77 143173 874823 32 13 55  0  0
19  0 1029836 22384272      0 4942872    0    0     0   139 151909 937524 33 14 53  0  0
19  0 1029836 22375048      0 4954448    0    0     0   173 149080 938167 33 14 53  0  0
18  0 1029836 22364068      0 4967140    0    0     0    40 149353 948095 34 14 52  0  0
17  0 1029836 22453564      0 4874692    0    0     0   179 145897 931248 33 13 54  0  0
18  0 1029836 22443236      0 4885868    0    0     0   104 150392 942998 33 14 52  0  0
23  0 1029836 22432088      0 4896420    0    0     0   110 151882 964156 34 14 51  0  0
25  0 1029836 22424636      0 4907832    0    0     0   105 138607 877496 34 12 54  0  0
23  0 1029836 22408472      0 4918196    0    0     0 103072 150916 939966 34 14 52  0  0
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
17  0 1029836 22398776      0 4930388    0    0     0     0 146547 926077 33 14 53  0  0
22  0 1029836 22390356      0 4940652    0    0     0   164 152588 942819 34 14 53  0  0
37  0 1029836 22377620      0 4952652    0    0     0   136 147128 941483 33 13 53  0  0
16  0 1029836 22461452      0 4860192    0    0     0    85 147398 928065 33 14 53  0  0
19  0 1029836 22457200      0 4871128    0    0     0   212 150156 940477 34 14 52  0  0
24  0 1029836 22330836      0 4882432    0    0     0   177 140849 831090 37 13 50  0  0
28  0 1029836 22146240      0 4892648    0    0     0     0 159265 826736 42 14 44  0  0
46  0 1029836 21826480      0 4902628    0    0     0   748 168670 766182 45 13 42  0  0
34  0 1029836 21776260      0 4912824    0    0     0   128 155022 904747 37 14 49  0  0
27  0 1029836 21698700      0 4923440    0    0     0 102664 166762 754978 48 13 39  0  0
45  0 1029836 21106372      0 4933108    0    0     0   563 168970 613063 61 13 26  0  0
27  0 1029836 20717388      0 4944896    0    0     0  3037 171917 797156 49 14 36  0  0
17  0 1029836 22341688      0 4958956    0    0     0    47 156711 920187 34 16 49  0  0
18  0 1029836 22346224      0 4961912    0    0     0   150 150436 951246 33 14 53  0  0
22  0 1029836 22438500      0 4870492    0    0     0   195 131955 815461 31 12 57  0  0
24  0 1029836 22427508      0 4880000    0    0     0    93 152889 960918 34 14 52  0  0
10  0 1029836 22419012      0 4891948    0    0     0    99 150199 948729 33 14 53  0  0

**Comment by PriyaGheewala** [comment]
It seems that scyllaDB is hitting the max no of open files limit. Currently our max no. of open files limit is 3 lacs.

**Comment by avikivity** [comment]
You should have messages in the logs about this.

Scylla adjusts the maximum number of open files, see `LimitNOFILE` in `/usr/lib/systemd/system/scylla-server.service`.  Is this the limit you are hitting or another one?

**Comment by PriyaGheewala** [comment]
@avikivity 

LimitNOFILE in /usr/lib/systemd/system/scylla-server.service is 2 lacs. 

It's just our guess. We are not sure about it whether it's the actual reason of the issue.

**Comment by avikivity** [comment]
Is there anything in the logs?  From vmstat output it appears that the disk is idle.

**Comment by PriyaGheewala** [comment]
@avikivity 

We have restarted the scylla. It generally happens after a day or two. So we will get back to you with logs once we face that issue again.

**Comment by penberg** [comment]
@avikivity Perhaps we leak file descriptors? That would explain why we hit the limit after few days?

**Comment by avikivity** [comment]
@penberg there is no actual indication of a problem with hitting the limit

@PriyaGheewala if there is nothing in the logs, please try the following, when the problem reappears:

    debuginfo-install scylla-server
    yum install perf
    perf record -a sleep 10
    perf report

**Comment by tzach** [comment]
@PriyaGheewala did you encountered this issue again?

**Comment by PriyaGheewala** [comment]
@tzach 
We did not encounter it again

**Comment by tzach** [comment]
Thanks @PriyaGheewala 
Closing this issue until we have more evidence its indeed a Scylla issue

**Comment by PriyaGheewala** [comment]
@avikivity  @tzach 

Hi, we are facing this issue again. 

Link to perf report : [https://www.dropbox.com/s/kacoy0n63z9do85/perf_report.txt?dl=0]

**Comment by tzach** [comment]
@PriyaGheewala Thanks for letting us know
Is this report is for 1.2 or a later 1.2.x version?

**Comment by PriyaGheewala** [comment]
@tzach 
It is for 1.2

**Comment by avikivity** [comment]
@PriyaGheewala please attach perf.data instead.  The report you attached lacks symbolic debug information.

Also, what do the logs say at this time?
