### ISSUE TITLE
Out of order flushing of memtables may lead to data not being replayed after unclean shutdown

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1373]
@elcallio explains in #1364:

> 
> For the commit log, in runtime, it is ok that flushes finish out-of-order, as long as the actual reporting to the CL is done (via the flush-queue in database.cc) in order. This is required to prevent deleting a segment that contains unflushed data.
> 
> However, there is a big issue with writing sstables out-of-order, and that is replay. Each sstable contains its high replay position mark. Replay looks at existing sstables and checks this, and assumes that if an sstable exists with mark A, then all data before A was also persisted. 
> Now, obviously, if we write out of order, finish a later sstable on disk first (so it exists and is complete), but fail to complete one with lower RP data, then this will break down. 
> Origin forces actual write order (somewhat implicitly, through the use of execution workers) for sstables (per CF). 
> We could of course just say "crash and replay is rare", and ignore the sstable positions, which might make replay take longer, but perhaps not overtly so... 
> Also worth noting is that it seems recent changes to the sstable compaction or whatnot (at start?) does not propagate the replay position marker, thus causing us to pick up "zero" markers -> must replay everything anyway.

**Comment by tzach** [comment]
@glommer is this still valid? Does Scylla allow parallel mem table flush of the same CF from a single shard? (not including repair /  streaming mem table)

**Comment by glommer** [comment]
We still flush 4 sstables in parallel and they can finish out of order.

It is really trivia ll to fix that - we have all the infrastructure already. That is part of a series of mine that will come right after The Wall patches. I am currently testing it in different scenarios.
