### ISSUE TITLE
Create an official Docker image 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1374]
Docker hub has a notion of official images.
It will be useful to provide such an official image for Scylla, similar to other DBs.

https://docs.docker.com/docker-hub/official_repos/#how-do-i-create-a-new-official-repository

**Comment by penberg** [comment]
@tzach Is this really 1.4 material?

**Comment by tzach** [comment]
@penberg not anymore :)
Current Scylla docker is already useful without the formal stamp

**Comment by penberg** [comment]
@tzach Exactly. Once the image is more mature, we certainly should try to move it to Docker library.

**Comment by tzach** [comment]
> @tzach Exactly. Once the image is more mature, we certainly should try to move it to Docker library.

@penberg how hard it is to do so?

**Comment by penberg** [comment]
@tzach It's a small matter of submitting a PR against their repositories and addressing all the review comments. :wink: So in short: I have no idea.

That said, I don't think our Docker image is really robust enough for that yet. For example, the default Docker configuration takes over the whole machine (see #1848 and #1849, for example).

**Comment by glommer** [comment]
@tzach we have an official docker image. Please close.
