### ISSUE TITLE
Scyllatop - unable to scroll down / up 

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#1375]
Scylla version 1.2
Running on AWS
It's not possible to scroll down / up when using scyllatop

**Comment by haarcuba** [comment]
solved by commit 26c0d86401db3b30277fb69136a3d3e05a90dad7

**Comment by penberg** [comment]
@tzach Why did you reopen the issue?

**Comment by tzach** [comment]
Allow me and @nirmaayan to test it

**Comment by nirmaayan** [comment]
@slivne 
Solved on 1.3
Scroll down with the mouse doesn't cause scyllatop to crash
You can only scroll with the keyboard
