### ISSUE TITLE
exceptional future ignored of type 'std::bad_alloc': std::bad_alloc

### ISSUE THREAD

**Issue by jarek2ch** [scylladb/scylla#1382]
Scylla version (or git commit hash): scylla-server-1.2.0-20160614.c384b23.el7.centos.x86_64
Cluster size: 1 node
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentoOS

​_Hardware details (for performance issues)_​          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): phisical
Hardware: sockets=1 cores=4 hyperthreading=yes memory=8G
Disks: HDD x8

**Output from nodetool:**

Keyspace: elcar_gps
        Read Count: 0
        Read Latency: NaN ms.
        Write Count: 0
        Write Latency: NaN ms.
        Pending Flushes: 0
                Table: frames
                SSTable count: 2152
                Space used (live): 387578962783
                Space used (total): 387578962783
                Space used by snapshots (total): 0
                Off heap memory used (total): 1051292
                SSTable Compression Ratio: 0.226302
                Number of keys (estimate): 631664
                Memtable cell count: 0
                Memtable data size: 0
                Memtable off heap memory used: 0
                Memtable switch count: 0
                Local read count: 0
                Local read latency: NaN ms
                Local write count: 0
                Local write latency: NaN ms
                Pending flushes: 0
                Bloom filter false positives: 0
                Bloom filter false ratio: 0.00000
                Bloom filter space used: 9008
                Bloom filter off heap memory used: 1048672
                Index summary off heap memory used: 2620
                Compression metadata off heap memory used: 0
                Compacted partition minimum bytes: 9888
                Compacted partition maximum bytes: 223875792
                Compacted partition mean bytes: 2970818
                Average live cells per slice (last five minutes): 0.0
                Maximum live cells per slice (last five minutes): 0.0
                Average tombstones per slice (last five minutes): 0.0
                Maximum tombstones per slice (last five minutes): 0.0

**Table sturcture (about 150mln rows):**

CREATE TABLE elcar_gps.frames (
    vehicle_id int,
    gps_time timestamp,
    frame_no int,
    ablue int,
    abs boolean,
    accumulator_low_voltage boolean,
    analog_input float,
    analog_input_no int,
    analog_input_work_type float,
    arpm int,
    attack boolean,
    authorized boolean,
    axle1_load float,
    axle2_load float,
    axle3_load float,
    axle4_load float,
    axle5_load float,
    axle6_load float,
    belts int,
    break_blocks_lamp boolean,
    calc_fuel1 float,
    calc_fuel2 float,
    calcfilling float,
    checkup_distance float,
    combo_sensorbin int,
    coolant_low_level boolean,
    cover1_memory boolean,
    cover1_opened boolean,
    cover2_memory boolean,
    cover2_opened boolean,
    cruise_control int,
    device_id int,
    device_low_voltage boolean,
    device_power_cutoff boolean,
    device_voltage float,
    diff_fuel float,
    diff_time text,
    digital_input boolean,
    digital_input_no int,
    digital_input_work_type int,
    distance float,
    door_b boolean,
    door_fl boolean,
    door_fr boolean,
    door_h boolean,
    door_rl boolean,
    door_rr boolean,
    drive_type int,
    driver_key int,
    emergency_airbag_malfunction boolean,
    engine boolean,
    engine_check boolean,
    engine_load float,
    engine_oil_level double,
    engine_oil_pressure double,
    engine_rpm int,
    engine_temp float,
    engine_work_time text,
    esp boolean,
    fuel float,
    fuel1 float,
    fuel2 float,
    fuel_per_hour float,
    fuel_used float,
    gear int,
    gprs boolean,
    gps_dir int,
    gps_error boolean,
    gps_jammed boolean,
    gps_point text,
    gps_sat_num int,
    gps_sat_stat int,
    gps_speed int,
    gsm_operator int,
    gsm_range int,
    hand_break boolean,
    handbrake_while_driving boolean,
    hazard_lights int,
    high_engine_temperature boolean,
    id bigint,
    ignition boolean,
    loop_break boolean,
    low_engine_oil boolean,
    low_oil_presure boolean,
    manual_gearbox boolean,
    max_speed boolean,
    milf int,
    min_speed boolean,
    moto_hours int,
    odometer int,
    oil_pressure_lamp boolean,
    outdoor_temp float,
    pto boolean,
    reset_reason int,
    retarder int,
    rfid02 boolean,
    rfid03 boolean,
    rfid03_card_id bigint,
    rfid03_card_no int,
    rfid03_cover1_memory boolean,
    rfid03_cover1_opened boolean,
    rfid03_cover2_memory boolean,
    rfid03_cover2_opened boolean,
    rfid03_error_code int,
    rfid03_improper_card boolean,
    rfid03_learn boolean,
    rfid03_loop_break boolean,
    rfid03_mother_card boolean,
    rfid03_no_connection boolean,
    rfid03_not_written boolean,
    rfid03_number_match_error boolean,
    rfid03_reader_serial int,
    rfid03_sabotage boolean,
    rfid03_sabotage_code int,
    rfid03_sn_match_error boolean,
    rfid03_temp float,
    rfid03_test boolean,
    rfid1 boolean,
    rfid2 boolean,
    rfid2_card_id bigint,
    rfid2_card_no int,
    rfid2_cover1_memory boolean,
    rfid2_cover1_opened boolean,
    rfid2_cover2_memory boolean,
    rfid2_cover2_opened boolean,
    rfid2_error_code int,
    rfid2_improper_card boolean,
    rfid2_learn boolean,
    rfid2_loop_break boolean,
    rfid2_mother_card boolean,
    rfid2_no_connection boolean,
    rfid2_not_written boolean,
    rfid2_number_match_error boolean,
    rfid2_reader_serial int,
    rfid2_sabotage boolean,
    rfid2_sabotage_code int,
    rfid2_sn_match_error boolean,
    rfid2_temp float,
    rfid2_test boolean,
    rfid3 boolean,
    rfid4 boolean,
    rfid4_card_id bigint,
    rfid4_card_no int,
    rfid4_cover1_memory boolean,
    rfid4_cover1_opened boolean,
    rfid4_cover2_memory boolean,
    rfid4_cover2_opened boolean,
    rfid4_error_code int,
    rfid4_improper_card boolean,
    rfid4_learn boolean,
    rfid4_loop_break boolean,
    rfid4_mother_card boolean,
    rfid4_no_connection boolean,
    rfid4_not_written boolean,
    rfid4_number_match_error boolean,
    rfid4_reader_serial int,
    rfid4_sabotage boolean,
    rfid4_sabotage_code int,
    rfid4_sn_match_error boolean,
    rfid4_temp float,
    rfid4_test boolean,
    rfid5 boolean,
    rfid5_card_id bigint,
    rfid5_card_no int,
    rfid5_cover1_memory boolean,
    rfid5_cover1_opened boolean,
    rfid5_cover2_memory boolean,
    rfid5_cover2_opened boolean,
    rfid5_error_code int,
    rfid5_improper_card boolean,
    rfid5_learn boolean,
    rfid5_loop_break boolean,
    rfid5_mother_card boolean,
    rfid5_no_connection boolean,
    rfid5_not_written boolean,
    rfid5_number_match_error boolean,
    rfid5_reader_serial int,
    rfid5_sabotage boolean,
    rfid5_sabotage_code int,
    rfid5_sn_match_error boolean,
    rfid5_temp float,
    rfid5_test boolean,
    rfid_reader_no_connection boolean,
    roaming boolean,
    sc_gps_antena boolean,
    tacho_direction int,
    tacho_drv1_card int,
    tacho_drv1_id bigint,
    tacho_drv1_state int,
    tacho_drv1_time int,
    tacho_drv2_card int,
    tacho_drv2_id bigint,
    tacho_drv2_state int,
    tacho_drv2_time int,
    tacho_handling int,
    tacho_motion int,
    tacho_overspeed int,
    tacho_performance int,
    tacho_system_event int,
    tamper boolean,
    temp1 float,
    temp2 float,
    temp3 float,
    temp4 float,
    throttle_pedal float,
    unit boolean,
    vehicle_battery_not_charging boolean,
    webasto int,
    webasto_temp float,
    wiper int,
    PRIMARY KEY (vehicle_id, gps_time, frame_no)
) WITH read_repair_chance = 0.0
   AND dclocal_read_repair_chance = 0.1
   AND gc_grace_seconds = 864000
   AND bloom_filter_fp_chance = 0.01
   AND caching = { 'keys' : 'ALL', 'rows_per_partition' : 'ALL' }
   AND comment = ''
   AND compaction = { 'class' : 'SizeTieredCompactionStrategy' }
   AND compression = { 'sstable_compression' :
'org.apache.cassandra.io.compress.LZ4Compressor' }
   AND default_time_to_live = 0
   AND speculative_retry = '99.0PERCENTILE'
   AND min_index_interval = 128
   AND max_index_interval = 2048;

**The problem is no query results, and errors:**

cqlsh:elcar_gps> select \* from frames;
OperationTimedOut: errors={}, last_host=192.168.20.11
cqlsh:elcar_gps>

Jun 23 09:01:05 combo-db-prd scylla: WARNING: exceptional future ignored
of type 'std::bad_alloc': std::bad_alloc
Jun 23 09:01:05 combo-db-prd scylla: WARNING: exceptional future ignored
of type 'std::bad_alloc': std::bad_alloc
Jun 23 09:01:05 combo-db-prd scylla: WARNING: exceptional future ignored
of type 'std::bad_alloc': std::bad_alloc
Jun 23 09:01:05 combo-db-prd scylla: WARNING: exceptional future ignored
of type 'std::bad_alloc': std::bad_alloc
Jun 23 09:01:05 combo-db-prd scylla[3727]: [shard 2] storage_proxy -
Exception when communicating with 192.168.20.11: std::bad_alloc
Jun 23 09:02:26 combo-db-prd scylla: WARNING: exceptional future ignored
of type 'std::bad_alloc': std::bad_alloc
Jun 23 09:02:35 combo-db-prd scylla: WARNING: exceptional future ignored
of type 'std::bad_alloc': std::bad_alloc
Jun 23 09:02:35 combo-db-prd scylla: WARNING: exceptional future ignored
of type 'std::bad_alloc': std::bad_alloc
Jun 23 09:02:35 combo-db-prd scylla: WARNING: exceptional future ignored
of type 'std::bad_alloc': std::bad_alloc
Jun 23 09:02:35 combo-db-prd scylla: WARNING: exceptional future ignored
of type 'std::bad_alloc': std::bad_alloc
Jun 23 09:02:35 combo-db-prd scylla: WARNING: exceptional future ignored
of type 'std::bad_alloc': std::bad_alloc
Jun 23 09:02:35 combo-db-prd scylla: WARNING: exceptional future ignored
of type 'std::bad_alloc': std::bad_alloc
Jun 23 09:02:35 combo-db-prd scylla[3727]: [shard 2] storage_proxy -
Exception when communicating with 192.168.20.11: std::bad_alloc

**Comment by avikivity** [comment]
Thanks for the detailed report.

The cause is here:
```
Compacted partition maximum bytes: 223875792
```

You have one partition (a `verhicle_id`) which is about 100X larger than the average.  Can you remodel your data in a way that avoids this huge partition?

Scylla 1.2 has to read the entire partition into memory, and this is slow.  Scylla 1.3 will be able to read just part of the partition, but it will still be slow, especially on HDD.  I recommend remodelling your data in a way that doesn't generate such large partitions.

**Comment by jarek2ch** [comment]
Hi Avi,

you mean to partition by vehicle_id and e.g. year-month to make partition smaller?


reagrds
Jarosław Chochowski

W dniu 2016-06-23 o 15:51, Avi Kivity pisze:

**Comment by avikivity** [comment]
That should work if the number of records per month is limited.

**Comment by tzach** [comment]
@jarek2ch wide partition was greatly improved in Scylla 1.3
Can you please retest with Scylla 1.3?

**Comment by slivne** [comment]
@jarek2ch losing the issue - if there are still issues after upgrading to 1.3 - please post them and we can reopen / create a new issue
