### ISSUE TITLE
Mapreduce select count(*)

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#1385]
Instead of sequential scan, let the coordinator mapreduce the entire range

**Comment by avikivity** [comment]
The other aggregates can benefit just as well (avg() would need to returns its state instead of the final value).

**Comment by duarten** [comment]
A potential complication is that for CL > 1, different replicas for the same range may have different rows which need to be merged. We would need to send back a digest to the coordinator along with the reduced result, so it knows to do a full, reconciling query.
