### ISSUE TITLE
Recompile prepared statements after schema change

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#139]
Currently prepared statements hold on to schema_ptrs and in the future perhaps to more internal objects.  After a `DROP KEYSPACE` or `ALTER TABLE`, these are no longer valid and need to be updated.

A simple change is to recompile the prepared statements during the update (and drop statements that no longer compile).

We may also want to block the update while statements (prepared or not) are executing on the table being modified, using e.g. `seastar::gate`.

@penberg

**Comment by slivne** [comment]
support for drop table / drop keyspace was added

support for alter table / alter keyspace is still waiting till they are impld

**Comment by penberg** [comment]
@tgrabiec We discussed this and IIRC we can let the driver do the recompilation and simply invalidate the affected statements, right?

**Comment by tgrabiec** [comment]
@penberg I think so, yes. Cassandra 2.1.8 is invalidating prepared statements if column definitions are affected.
