### ISSUE TITLE
ami: disk interrupts not distributed

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1390]
_Installation details_
Scylla version (or git commit hash): 1.2
OS (RHEL/CentOS/Ubuntu/AWS AMI): AMI

Networking + disk interrupts are too much for one core, we should distribute disk interrupts on the processing cores.

**Comment by slivne** [comment]
What instance type 8 colres and up we reserve cpu 0 for net interrupts

I think glauber once mentioned that we have traffic on the hyperthread
maybe thats the issue

If not should we distribute to all cores or should we do it to cores with
io queues

**Comment by avikivity** [comment]
It's not enough, I saw cp0 0 at 100%.  If we clear the hyperthread, and distribute disk interrupts it may be okay.

**Comment by slivne** [comment]
what is the reproducer for this ?

**Comment by avikivity** [comment]
1. Run AMI

2. `cat /proc/interrupts`

3. Observe 8 disk interrupts all cpu0.

**Comment by tzach** [comment]
@avikivity @slivne 
Is this still valid after #1406 fix https://github.com/scylladb/scylla/commit/f4746d2a4623aae251afc6743c308b4bee5ebbd3 ?

**Comment by slivne** [comment]
lets test and see if this is still an issue or not 

lets use the case of 3 i2.8x with 14 loaders

**Comment by glommer** [comment]
@vladzcloudius anything else to be done here ?

**Comment by vladzcloudius** [comment]
@glommer Nope.
