### ISSUE TITLE
Scylla gets swapped out if user runs some process, with horrible results

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1393]
_Installation details_
Scylla version (or git commit hash): 1.1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 14.04

If a user runs some administrative task that requires a lot of memory, the kernel might swap out Scylla.  This later results in Scylla being very unresponsive as it pages itself back in.

**Comment by avikivity** [comment]
Possible fix: `mlock(MLOCK_ALL)`; systemd `LimitMEMLOCK`; systemd `OOMScoreAdjust=-1000`.

**Comment by nyh** [comment]
We could have scylla mlockall() itself, but the result could, instead of swapping, that either scylla or the other process gets killed. not sure which is worse...

**Comment by nyh** [comment]
Ultimately, Seastar cannot gracefully share a machine with anything else (except with some sort of static division for memory and cores up-front), and the user will have to be aware of this, and not run anything else substantial on the same machine.

**Comment by avikivity** [comment]
Scylla is the most important process on the machine.  Anything is better than Scylla getting swapped out or killed.  If you want some other process to run and consume memory, run with `--memory something`.

The danger is that Scylla will develop a memory leak outside its arena.  But even in that case, is it better to allow it to leak into swap, or OOM early?

**Comment by avikivity** [comment]
Maybe we should add a question in `scylla_setup`, "Will Scylla be the only service on this host? Y/n".  If the user answers yes, we set --lock-memory 1.  If the user answers no, we ask further questions about how much memory and lcores to allocate to Scylla, and whether to mlock or not.

@tzach @syuu1228

**Comment by dorlaor** [comment]
Let's grab our share of memory regardless.
Even when someone has a parallel service, we should lock the portion of the
memory we're given.

The other alternative is to cancel swap but I think locking is better

**Comment by avikivity** [comment]
In a shared scenario, we should ask,  It gives more flexibility.  We can still default to yes, but allow no for setups where Scylla isn't the main tenant.

The usual scenario is that Scylla is the only tenant, next is main tenant among several, but secondary tenant is also possible.

**Comment by avikivity** [comment]
btw, disabling swap is not a good option, because if something goes wrong it forces the kernel to kill something.

**Comment by syuu1228** [comment]
When you also install scylla-jmx on same host, can you use --lock-memory 1
or not?
Because scylla_setup let users to instal jmx now.

**Comment by avikivity** [comment]
scylla-jmx has restricted memory requirements, it doesn't count as a separate tenant.

**Comment by slivne** [comment]
to support cases in which the user wants to limit the memory amount we can add a /etc/scylla.d/memory.conf that will allow a user to limit the amount of memoy

**Comment by dorlaor** [comment]
Let's do it and also enable it by default for new installations.

**Comment by penberg** [comment]
Let's give it some testing first. I suspect it will make Scylla server startup (much?) slower on machines with lots of RAM.
