### ISSUE TITLE
sudo errors in systemctl start scylla-server

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1399]
*Installation details*
Scylla version (or git commit hash): 1.2?
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL 7.2

See report in https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/scylladb-users/cy2Z4yEKdxg/MniRz3N8AQAJ

**Comment by penberg** [comment]
Didn't we fix this with commit 1d5f7be44733740b1fdd9d097bfd7ff22c519d1e?
