### ISSUE TITLE
Coredump wasn't generate when scylla crash

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#1401]
*Installation details*
Scylla version (or git commit hash): 1.2
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos 7.2 - AMS AMI i2.8xlarge
Disks: (SSD/HDD, count) SSD

No coredump created when scylla crash
Working with grafana monitor
Steps to reproduce:

1. 1. Create setup using 1.2 AMI 
2. 2. Edit  /etc/scylla.d/cpuset.conf with CPUSET="--cpuset 1-15,17-31 --smp 30 "
3. 3. Edit  /etc/scylla.d/io.conf with SEASTAR_IO="--num-io-queues 30 --max-io-requests 240"
4. Populate the cluster using ansible script ./ec2-stress.sh 1 -e "server=Scylla" -e "stress_options='-errors ignore -schema \"replication(factor=3)\" keyspace=\"mykeyspace\"'" -e "load_name=scylla_write" -e "threads=2500" -e "command_options='cl=QUORUM n=1000000000 -mode native cql3 -pop seq=1..1000000000'"
 _This step will create 1TB~ of data before compaction_
5. Start read command ./ec2-stress.sh 1 -e "command=read" -e "server=Scylla" -e "stress_options='-errors ignore -schema \"replication(factor=3)\" keyspace=\"mykeyspace\"'" -e "load_name=scylla_read_command" -e "threads=2500" -e "command_options='n=500000000 duration=15m cl=QUORUM -mode native cql3 -pop dist=gauss(1..50000000,25000000,2500000)'" 
6. Couple of minutes after the command is executed 2 nodes crashed.
7. Verify coredumps with coredumpctl command and see that there are coredump created.
8. Due to another bug with the AMI ([#1388](https://github.com/scylladb/scylla/issues/1388)) - edit the coredump location with sudo scylla_coredump_setup --dump-to-raiddir
9. Restart scylla service 
10. When using top I saw that the coredumps created
11. Verify cores are under /usr/lib/scylla/coredumps with ls -a shows coredumps how ever when the creation was ended there was no curedump in the folder.
12. Using scylla abrt command didn't generate the core either

**Comment by benoit-canet** [comment]
The core is probably too big for the free disk space and hence systemd
remove it.

**Comment by nirmaayan** [comment]
Core size was 73GB (verify with du -sh) there was about 3TB free space

**Comment by slivne** [comment]
We will fix the AMI - yet to let you work on the issue you have please do the following

1. Install instance from AMI
2. edit scylla_coredump_setup and 
```
sudo vi `which scylla_coredump_setup`
```
3. change ```Compress=yes``` to be ```Compress=no```
4. run scylla_coredump_setup
5. send ABRT signal and test that it works ```pkill -ABRT scylla```
6. ls -la /var/lib/scylla/coredump (once the dump completes the file name will change from .#core ... to be core)
7. run coredumpctl
8. run comredumpctl info <id>

We have setup coredump to compress the file - this happens after the original dump was created and I that the compression may not be ending (in any case it takes ages to compress the 244G core you are getting using a single core)

**Comment by nirmaayan** [comment]
@slivne Coredump was created /var/lib/scylla/coredump - size of the core is 320MB

**Comment by nirmaayan** [comment]
Coredump was created /var/lib/scylla/coredump - size of the core is 220GB
Trying to verify it on cluster with data

**Comment by slivne** [comment]
@avikivity creating the coredump takes 1-2 minutes, compressing it takes ages - can we remove compression.

Compression is running after scylla has restarted and actually will cause issues with bandwidth to the disk (especially if there are consecutive failures and for each we are compressing very long)

**Comment by slivne** [comment]
after 4 hours the coredump is still being zipped and no sign of the end

```
230784328 -rw-r----- 1 root   root   236323147776 Jun 29 10:48 .#core.scylla.994.550b2974a85242a685bbc1e21207d1f8.2674.1467197088000000cfe2c57d6ff6148c
        4 drwxr-xr-x 2 scylla scylla         4096 Jun 29 10:48 .
    29696 -rw-r----- 1 root   root       28262400 Jun 29 14:32 .#core.scylla.994.550b2974a85242a685bbc1e21207d1f8.2674.1467197088000000.xzc20d1fee8647f14e
```

Can we stop the compression.

**Comment by slivne** [comment]
@avikivity ping

**Comment by nyh** [comment]
While from what you're describing, we need to disable compression, it appears (but please correct me if I'm wrong) that this compression is a system-wide setting in systemd (see https://www.freedesktop.org/software/systemd/man/coredump.conf.html) so it would not be "playing nice" if scylla disabled it. Although it wouldn't be the first time we do this, if we do. Technically, doing this is easy - we just need to write a new file in /usr/lib/systemd/coredump.conf.d/*.conf (see the coredump.conf(5) manual page).

By the way, it's curious why creating the core dump takes 2 minutes but compressing it takes more than 4 hours. Compression isn't usually that slow (although "xz" compression may be slow - I don't know what speed setting they used). In your listing, it seems, if I understand correctly, that it only managed to compress 28 megabytes in 4 hours, which doesn't make any sense - I am guessing the compression program crashed.... Do you actually see it running? Perhaps we restarted Scylla which used up all the machine's memory, which caused the compression background running in the background to be killed on OOM?

**Comment by tzach** [comment]
@avikivity @slivne any update on this issue? was the AMI fixed?

**Comment by slivne** [comment]
So we will disable compression

**Comment by syuu1228** [comment]
Fixed at https://github.com/scylladb/scylla/commit/89b790358ec46664cb4fc928b68b5101166688e1

**Comment by tzach** [comment]
@nirmaayan can you please validate?

**Comment by nirmaayan** [comment]
@slivne can you please assign it to me till I'll reproduce it

**Comment by nirmaayan** [comment]
solved 
Still need to run: sudo scylla_coredump_setup --dump-to-raiddir

**Comment by slivne** [comment]
is that with rc3 or rc2 ?

**Comment by nirmaayan** [comment]
Last reproduce was with RC2

**Comment by slivne** [comment]
lets test this with rc3 - we just release it - it should be resolved.

**Comment by nirmaayan** [comment]
Solved in rc3
using abrt command
