### ISSUE TITLE
self-documentation metrics

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1410]
Currently, there is no easy way to get all available metrics from ScyllaDB.
It will be useful for users to extract all the metrics, each with a description, directly from Scylla.

Preparing such a list at compile time will make it easier to follow metrics updates from one release to the other.

**Comment by nirmaayan** [comment]
@tzach I started to document the metrics, we need it to be "human readable" format

**Comment by slivne** [comment]
@amnonh , @vladzcloudius - do all the metrics have documentation -?

@amnonh - how can we retrieve the description ?

**Comment by amnonh** [comment]
Merge my patches so I can resend my prometheus 0.4 text representation
(next version will contain help)

**Comment by vladzcloudius** [comment]
@slivne As far as I know all metrics have been transferred to the new API.

**Comment by slivne** [comment]
@amnonh is that merged (to master / 1.7) - if its not in 1.7 - I'll push it to 1.8 and then you can test

**Comment by amnonh** [comment]
On Tue, Mar 14, 2017 at 12:07 PM, Shlomi Livne <notifications@github.com>
wrote:

> @amnonh <https://github.com/amnonh> is that merged (to master / 1.7) - if
> its not in 1.7 - I'll push it to 1.8 and then you can test
>
Not merge to neither

**Comment by tzach** [comment]
@slivne @amnonh will this be on 2.0 ?

**Comment by slivne** [comment]
accessing http://127.0.0.1:9180/metrics from a browser provides the help text as well as the current metrics value

**Comment by tzach** [comment]
@slivne @amnonh 
> accessing http://127.0.0.1:9180/metrics from a browser provides the help text as well as the current metrics value

This gives me unreadable text, full of strange characters and "where did the description disappear" messages

```
�
!scylla_thrift_current_connections$where did the description disappear?"@

typegauge

instancee2d95285cb12


shard0		�
-scylla_tracing_keyspace_helper_tracing_errors$where did the description disappear?"A

typederive

instancee2d95285cb12


shard0		�
%scylla_streaming_total_outgoing_bytes$where did the description disappear?"A

typederive

instancee2d95285cb12
```

**Comment by tzach** [comment]
Oops, I was testing with 1.7
Scylla 2.0 rc works fine
```
# TYPE scylla_batchlog_manager_total_write_replay_attempts counter
scylla_batchlog_manager_total_write_replay_attempts{instance="some-scylla",shard="0",type="derive"} 0
# HELP scylla_cache_active_reads number of currently active reads
# TYPE scylla_cache_active_reads gauge
scylla_cache_active_reads{instance="some-scylla",shard="0",type="gauge"} 0.000000
# HELP scylla_cache_bytes_total total size of memory for the cache
# TYPE scylla_cache_bytes_total gauge
scylla_cache_bytes_total{instance="some-scylla",shard="0",type="gauge"} 5505024.000000
# HELP scylla_cache_bytes_used current bytes used by the cache out of the total size of memory
# TYPE scylla_cache_bytes_used gauge
scylla_cache_bytes_used{instance="some-scylla",shard="0",type="gauge"} 141681.000000
# HELP scylla_cache_concurrent_misses_same_key total number of operation with misses same key
# TYPE scylla_cache_concurrent_misses_same_key counter
scylla_cache_concurrent_misses_same_key{instance="some-scylla",shard="0",type="derive"} 0
# HELP scylla_cache_mispopulations number of entries not inserted by reads
# TYPE scylla_cache_mispopulations counter
scylla_cache_mispopulations{instance="some-scylla",shard="0",type="derive"} 89
# HELP scylla_cache_partition_evictions total number of evicted partitions
# TYPE scylla_cache_partition_evictions counter
```
