### ISSUE TITLE
GDB unable to read scylla core file

### ISSUE THREAD

**Issue by s905060** [scylladb/scylla#1412]
Scylla version (or git commit hash): 1.2.0-20160613.c384b23-ubuntu1
Cluster size: 30
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 14.04.4 LTS
Platform (physical/VM/cloud instance type/docker): Bare-Metal

```
dpkg --list | grep scylla
ii  scylla                               1.2.0-20160613.c384b23-ubuntu1      amd64        Scylla database metapackage
ii  scylla-conf                          1.2.0-20160613.c384b23-ubuntu1      amd64        Scylla database main configuration file
ii  scylla-jmx                           1.2.0-20160613.a69d6a9-ubuntu1      all          Scylla JMX server binaries
ii  scylla-kernel-conf                   1.2.0-20160613.c384b23-ubuntu1      amd64        Scylla kernel tuning configuration
ii  scylla-server                        1.2.0-20160613.c384b23-ubuntu1      amd64        Scylla database server binaries
ii  scylla-server-dbg                    1.2.0-20160613.c384b23-ubuntu1      amd64        debugging symbols for scylla-server
ii  scylla-tools                         1.2.0-20160613.cfd4575-ubuntu1      all          Scylla database tools
```

Command:

```
$sudo gdb /usr/bin/scylla --core /var/lib/scylla/coredump/core.scylla-2016-06-29-19:20:53-52135
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/scylla...Reading symbols from /usr/lib/debug/.build-id/3e/d71af55c5afdcda80f06964c1e42333f67f27d.debug...
```

Nothing happened.

Any advices would be appreciated. Thank you.

**Comment by avikivity** [comment]
Use `scylla-gdb` from http://downloads.scylladb.com/rpm/3rdparty/centos/7/x86_64/; the binary is in `/opt/scylla/bin`.  When it starts up, it asks a question, just say no and it will allow you to debug,

**Comment by dorlaor** [comment]
On Mon, Jul 4, 2016 at 8:35 AM, Avi Kivity <notifications@github.com> wrote:

> Use scylla-gdb from
> http://downloads.scylladb.com/rpm/3rdparty/centos/7/x86_64/; the binary
> is in /opt/scylla/bin. When it starts up, it asks a question, just say no
> and it will allow you to debug,
>

@avikivity, the reporter uses Ubuntu, not centos

**Comment by avikivity** [comment]
The Ubuntu packages can be found in http://downloads.scylladb.com.s3.amazonaws.com/deb/3rdparty/trusty/pool/scylladb/multiverse/s/scylla-gdb/; thanks @dorlaor for noticing.

**Comment by slivne** [comment]
@s905060 any update ?

**Comment by s905060** [comment]
I have installed the scylla-gdb package but didn't run the gdb command, we use backtrace.io instead.

**Comment by dorlaor** [comment]
On Fri, Aug 19, 2016 at 2:52 PM, Cheng-Hsiu (Jash) Lee <
notifications@github.com> wrote:

> I have installed the scylla-gdb package but didn't run the gdb command, we
> use backtrace.io instead.
>

Interesting. We're using 'avikivity' ;)

**Comment by tzach** [comment]
> I have installed the scylla-gdb package but didn't run the gdb command, we use backtrace.io instead.

@s905060 is it working?

**Comment by slivne** [comment]
@s905060 closing this issue as there is not additional data - if you have additional data we can reopen.
