### ISSUE TITLE
Wrong repository used in AMI

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1414]
*Installation details*
Scylla version (or git commit hash): 1.2
OS (RHEL/CentOS/Ubuntu/AWS AMI): AMI

```
$ cat /etc/yum.repos.d/scylla.repo 
[scylla]
name=Scylla for Centos $releasever - $basearch
baseurl=https://s3.amazonaws.com/downloads.scylladb.com/rpm/centos/$releasever/$basearch/
enabled=1
gpgcheck=0

[scylla-generic]
name=Scylla for centos $releasever
baseurl=https://s3.amazonaws.com/downloads.scylladb.com/rpm/centos/$releasever/noarch/
enabled=1
gpgcheck=0

[scylla-3rdparty]
name=Scylla 3rdParty for Centos $releasever - $basearch
baseurl=https://s3.amazonaws.com/downloads.scylladb.com/rpm/3rdparty/centos/$releasever/$basearch/
enabled=1
gpgcheck=0

[scylla-3rdparty-generic]
name=Scylla 3rdParty for Centos $releasever
baseurl=https://s3.amazonaws.com/downloads.scylladb.com/rpm/3rdparty/centos/$releasever/noarch/
enabled=1
gpgcheck=0
```

This means that users won't receive upgrades.

**Comment by avikivity** [comment]
Also, AMI should install the `scylla` package.

**Comment by slivne** [comment]
The decision about AMI was there will not be an upgrade for AMI.

**Comment by avikivity** [comment]
And the way to achieve this is by installing the wrong repository?

What about patch updates?  The AMI has 1.2.0, with no way to upgrade to 1.2.1.

**Comment by avikivity** [comment]
Or install `scylla-debuginfo`.

**Comment by slivne** [comment]
1. no thats not the way

2. the bad repo needs to be removed

3.  the decision was there will not be an upgrade - we create a new ami for
each release so there is an ami for 1.2.0 and an ami for 1.2.1

4. the other items - additional packages etc need to be fixed.

**Comment by avikivity** [comment]
But the user can't upgrade to AMI 1.2.1 because the data will be lost.

**Comment by slivne** [comment]
So we need to change the requirements and enhance the current AMI.

Do we also want to allow upgrade from 1.2 --> 1.3 ?

I don't see any difference between an upgrade of 1.2 --> 1.3 to an upgrade
between 1.2.0 --> 1.2.1


I think we need some info on how many people use the AMI for production -
the AMI is not setup for production it is setup to be able to test scylla
fast.

The AMI does not support multi-dc deployment

**Comment by tzach** [comment]
> I think we need some info on how many people use the AMI for production -
> the AMI is not setup for production it is setup to be able to test scylla
> fast.

There is not disclaimer about using Scylla AMI on production. On the contrary, Scylla AMI should be production ready.

I agree with @slivne we need to change the requirements, having the same UX for AMI as users who install from repo, including upgrade support.
