### ISSUE TITLE
Install and run node_exporter as part of Scylla install

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1416]
Scylla version (or git commit hash): 1.2
OS (RHEL/CentOS/Ubuntu/AWS AMI): ALL

To allow [scylla monitoring](https://github.com/scylladb/scylla-grafana-monitoring) to work out of the box, Scylla needs to install and run collectd (#1415) and  collectd_exporter by default, including the right collcted [configuration](https://github.com/scylladb/scylla/wiki/Monitor-Scylla-with-Prometheus-and-Grafana#collectd_exporter)

**Comment by tzach** [comment]
Users need to jump through hoops to enable monitoring.
I'm open for other suggestions to make it easier for them. Making collectd_exporter install part of the scylla_setup script, with default Y seems like a good compromise.

**Comment by slivne** [comment]
I think that creating a dependency in scylla on collectd_exporter is
something we should not have

Installing collectd_exporter via scylla_setup (or other script) seems like
a good compromise - it will mean that we will pull it based on user request
- need to check licensing.

**Comment by tzach** [comment]
collectd_exporter does not include a license
https://github.com/prometheus/collectd_exporter

Prometheus itself is Apache 2
https://github.com/prometheus/docs#license

**Comment by slivne** [comment]
On Sun, Jul 3, 2016 at 8:28 PM, Tzach Livyatan <notifications@github.com>
wrote:

> collectd_exporter does not include a license
> https://github.com/prometheus/collectd_exporter
>

here is the license -
https://github.com/prometheus/collectd_exporter/blob/master/LICENSE

its also Apache V2

**Comment by tzach** [comment]
collectd_exporter needs to run as a service

**Comment by tzach** [comment]
@slivne on second thought, download from the web will not work on a server which does not have external connectivity. Why not include the exporter on the scylla_tool rpm/deb?
we can still enable the service as part of scylla_setup.

**Comment by tzach** [comment]
As Scylla expose metrics both from collectd_exporter and directly #1280 , each will need to use a different port, and the monitoring server like [scylla-grafana-monitoring](https://github.com/scylladb/scylla-grafana-monitoring) will need to monitor both

**Comment by slivne** [comment]
We enhanced seastar to support exporting info to prometheus

We need to export the node information (disk,network,cpu,memory etc.) and this will be done by installing the node_exporter

**Comment by slivne** [comment]
@amnonh is this on the list already ?

**Comment by amnonh** [comment]
I've sent a series a few minutes ago, you probably didn't see it yet
