### ISSUE TITLE
scyllatop exit with ^C leave terminal in non working state 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1417]
*Installation details*
Scylla version (or git commit hash): 1.2
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.2

When one exists scyllatop by pressing ^C terminal state in raw mode.
Need to type 'reset\n", to get it back to normal.

**Comment by haarcuba** [comment]
submitted patch

**Comment by penberg** [comment]
@tzach Why did you reopen the issue?

**Comment by nirmaayan** [comment]
@slivne @tzach 
Closed in 1.3
