### ISSUE TITLE
debug builds: warn that -m parameters is not applied

### ISSUE THREAD

**Issue by gusev-p** [scylladb/scylla#14186]
Debug builds use `ASAN` allocator and ignore this parameter. Currently there are no clear signs that it's not applied, which causes misunderstanding and wasted time. For example, it took some time to get why [this test](https://github.com/scylladb/scylladb/blob/5acb137c2e9b14d15e8147d8c071671446873e09/test/cql-pytest/test_shedding.py#L76) test was failing in debug builds. It made some assumptions about available memory, which break in debug builds. Recently, @alecco stumbled upon the same problem.

**Comment by denesb** [comment]
This should be opened in the seastar repo. And the best way to make sure it is fixed is if you send a patch yourself.

**Comment by gusev-p** [comment]
In this insane github UIs I can't just transfer an issue I've just created, I need some additional rights(

**Comment by gusev-p** [comment]
https://github.com/scylladb/seastar/issues/1691

**Comment by mykaul** [comment]
> In this insane github UIs I can't just transfer an issue I've just created, I need some additional rights(

Next time, I may be able to help.
