### ISSUE TITLE
data_resource hash slowing down everything on large machines

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1419]
*Installation details*
Scylla version (or git commit hash): 1.2

```
 namespace std {
 template <>
 struct hash<auth::data_resource> {
     size_t operator()(const auth::data_resource & v) const {
         return std::hash<sstring>()(v.name());
    }
 };
```

`data_resource::name`  uses `sprint()`, which in turn needs the locale, which takes a global lock.

**Comment by nyh** [comment]
We use sprint() in dozens of places, most of which look slow-path, but maybe not all are... 
Should we perhaps fix sprint() not to use the locale?

**Comment by slivne** [comment]
This is only true if the the authorizer in the scylla.yaml was modified to
be "org.apache.cassandra.auth.CassandraAuthorizer" (or CassandraAuthorizer)

if the configuration is using the AllowAllAuthorizer (the default) then
there should not be any effect on performance.

**Comment by scorpnode** [comment]
can someone help with issue #1421 please

**Comment by avikivity** [comment]
No, I think it happens in any case.

**Comment by gleb-cloudius** [comment]
On Sun, Jul 03, 2016 at 10:37:31PM -0700, Avi Kivity wrote:
> No, I think it happens in any case.
> 
So is this a reason for alleged performance degradation between 1.0 and
1.1?

--
			Gleb.

**Comment by avikivity** [comment]
Possibly
