### ISSUE TITLE
Failed to install scylla-kernel-conf on upgrade to Scylla 1.2 Ubuntu 14.04

### ISSUE THREAD

**Issue by scorpnode** [scylladb/scylla#1420]
Setting up scylla-kernel-conf (1.2.1-20160623.c56fc99-ubuntu1) ...
sysctl: cannot stat /proc/sys/kernel/sched_tunable_scaling: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_min_granularity_ns: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_wakeup_granularity_ns: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_latency_ns: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_autogroup_enabled: No such file or directory
dpkg: error processing package scylla-kernel-conf (--configure):
 subprocess installed post-installation script returned error exit status 255
dpkg: dependency problems prevent configuration of scylla:
 scylla depends on scylla-kernel-conf; however:
  Package scylla-kernel-conf is not configured yet.

dpkg: error processing package scylla (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 scylla-kernel-conf
 scylla
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by hasmikhail** [comment]
were you able to fix this?

**Comment by hasmikhail** [comment]
i was able to run the scylla docker on a kernel that does not support CFS modules (i.e. it does not have the above paths).

are they required for scylla?  is it possible to fix the scylla-kernel-conf command?   @tzach 

thanks in advance.

**Comment by tzach** [comment]
@penberg can you help?

**Comment by hasmikhail** [comment]
i'm seeing it with scylla-1.3 fwiw

**Comment by penberg** [comment]
Sorry, I don't understand what you are trying to do here @hasmikhail. Are you trying to install that package in a Docker container? That's not going to work because `proc` filesystem settings are host-wide, not specific to the container.

**Comment by hasmikhail** [comment]
i was trying to install scylla 1.3 via yum, but i ran into the dpkg issue.   i checked on my system, and it is true that /proc/sys/kernel does not have those features.

however, i was able to run scylla 1.3 on the same machine through docker, which also did have those features.  

so, it appears that the scylla-kernel-conf configuration script is perhaps incorrectly checking the dependencies.

**Comment by hasmikhail** [comment]
@penberg this issue was closed by original author, but it is still happening for me.  would you prefer it's tracked in an open issue?

**Comment by slivne** [comment]
@penberg  any update ?

**Comment by slivne** [comment]
@penberg ping

**Comment by penberg** [comment]
No updates.

**Comment by slivne** [comment]
@penberg ping

**Comment by penberg** [comment]
I'm not sure there's any action required here. The `scylla-kernel-conf` kernel requires procfs to be present to be able to fiddle with kernel configuration. And you probably need procfs anyway for other things to function correctly as well.

However, if someone *really* wants to avoid the package, they can avoid the super-package and install `scylla-server`, `scylla-jmx`, and `scylla-tools` packages directly.

**Comment by slivne** [comment]
thanks
