### ISSUE TITLE
Multicolumn Slice ranges bug

### ISSUE THREAD

**Issue by scorpnode** [scylladb/scylla#1422]
nstallation details
Scylla version 1.2.1:
Cluster size:1
OS Ubuntu:14.04
Total rows in keyspace.table=3
Still showing results cqlsh> SELECT \* FROM keyspace.table WHERE uid ='111' AND (due, entry_time) > (1467571452,1467571902);

uid | due | entry_time | action_type | eid
-----------------+------------+------------+-------------+-----------
111 | 1700000000 | 1467571893 | 1 | axc
111 | 1700000000 | 1467571902 | 1 | xds
111 | 1700000000 | 1467571906 | 1 | axd

another weird behaviour
cqlsh> SELECT \* FROM keyspace.table WHERE uid ='111' AND (due, entry_time) > (1700000000,1467571902);

uid | due | entry_time | action_type | eid
-----------------+------------+------------+-------------+-----------
111 | 1700000000 | 1467571906 | 1 | axd

**Comment by avikivity** [comment]
This seems like the correct behavior. Why do you think it is wrong?

**Comment by scorpnode** [comment]
SELECT * FROM keyspace.table WHERE uid ='111' AND (due, entry_time) > (1467571452,1467571902);

uid | due | entry_time | action_type | eid
-----------------+------------+------------+-------------+-----------
111 | 1700000000 | 1467571893 | 1 | axc
111 | 1700000000 | 1467571902 | 1 | xds
111 | 1700000000 | 1467571906 | 1 | axd

Im, hoping to retrieve only 
uid | due | entry_time | action_type | eid
-----------------+------------+------------+-------------+-----------
111 | 1700000000 | 1467571906 | 1 | axd

**Comment by avikivity** [comment]
It's not ignored, it's using lexicographic (tuple) comparison.

It will return any row with due > 1467571452, or any row with due == 1467571452 and entry_time > 1467571902.  Not where both keys are greater than the respective constants.

**Comment by scorpnode** [comment]
Seriously this is really buggy looks like i broke it


cqlsh> INSERT INTO b4_1.e_timeline1 (uid, due,entry_time) VALUES ('11',10,1) ;
cqlsh> INSERT INTO b4_1.e_timeline1 (uid, due,entry_time) VALUES ('11',11,2) ;
cqlsh> INSERT INTO b4_1.e_timeline1 (uid, due,entry_time) VALUES ('11',12,3) ;
cqlsh> SELECT * FROM b4_1.e_timeline1 WHERE uid='11' AND (due,entry_time) >(9,2);

(0 rows)
cqlsh> SELECT * FROM b4_1.e_timeline1  ;

 uid | due | entry_time | action_type | eid
-----+-----+------------+-------------+------
  11 |  12 |          3 |        null | null
  11 |  11 |          2 |        null | null
  11 |  10 |          1 |        null | null

(3 rows)
cqlsh> SELECT * FROM b4_1.e_timeline1 WHERE uid='11' AND (due,entry_time) >(9,2) AND (due,entry_time) <(15,15);
OperationTimedOut: errors={}, last_host=127.0.0.1
cqlsh> SELECT * FROM b4_1.e_timeline1  ;
OperationTimedOut: errors={}, last_host=127.0.0.1
cqlsh> quit
root@scw-b4:/home/scorpnode/work# cqlsh
Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})

**Comment by gleb-cloudius** [comment]
On Mon, Jul 04, 2016 at 06:50:44AM -0700, scorpnode wrote:
> Seriously this is really buggy looks like i broke it
> 
> 
> cqlsh> INSERT INTO b4_1.e_timeline1 (uid, due,entry_time) VALUES ('11',10,1) ;
> cqlsh> INSERT INTO b4_1.e_timeline1 (uid, due,entry_time) VALUES ('11',11,2) ;
> cqlsh> INSERT INTO b4_1.e_timeline1 (uid, due,entry_time) VALUES ('11',12,3) ;
> cqlsh> SELECT * FROM b4_1.e_timeline1 WHERE uid='11' AND (due,entry_time) >(9,2);
> 
> (0 rows)
> cqlsh> SELECT * FROM b4_1.e_timeline1  ;
> 
>  uid | due | entry_time | action_type | eid
> -----+-----+------------+-------------+------
>   11 |  12 |          3 |        null | null
>   11 |  11 |          2 |        null | null
>   11 |  10 |          1 |        null | null
> 
> (3 rows)
> cqlsh> SELECT * FROM b4_1.e_timeline1 WHERE uid='11' AND (due,entry_time) >(9,2) AND (due,entry_time) <(15,15);
> OperationTimedOut: errors={}, last_host=127.0.0.1
> cqlsh> SELECT * FROM b4_1.e_timeline1  ;
> OperationTimedOut: errors={}, last_host=127.0.0.1
> cqlsh> quit
> root@scw-b4:/home/scorpnode/work# cqlsh
> Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to [('127.0.0.1', 9042)]. Last error: Connection refused")})
> 
Looks like scylla crashed. Do you see core around or something in the
logs?

--
			Gleb.

**Comment by scorpnode** [comment]
scylla didnt crash because i could still start stop it. Just wouldnt connect

**Comment by gleb-cloudius** [comment]
On Mon, Jul 04, 2016 at 08:46:41AM -0700, scorpnode wrote:
> scylla didnt crash because i could still start stop it. Just wouldnt connect
> 
I am not to familiar with upstart that is used in Ubuntu, but in systemd
capable systems you can still "stop" a service that crashed. Can you check
status of scylla service with upstart after connection no longer works?
(also upstart may try to restart crashed server for you, but in this
case you should be able to connect after some time).

--
			Gleb.

**Comment by scorpnode** [comment]
I think regardless, there is definitely a bug. you can try the same thing i did above to replicate the error.

**Comment by slivne** [comment]
@scorpnode can you please provide the schema to simplify reproducing this locally.

**Comment by scorpnode** [comment]
CREATE TABLE keyspace.table (
    uid text,
    due int,
    entry_time int,
    action_type int,
    eid text,
    PRIMARY KEY (uid, due, entry_time)
) WITH CLUSTERING ORDER BY (due ASC, entry_time ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

**Comment by slivne** [comment]
@scorpnode thanks

I have collected the info from all the thread and was able to run the following:

```
create KEYSPACE k WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1} ;

CREATE TABLE k.t (
uid text,
due int,
entry_time int,
action_type int,
eid text,
PRIMARY KEY (uid, due, entry_time)
) WITH CLUSTERING ORDER BY (due ASC, entry_time ASC)
AND bloom_filter_fp_chance = 0.01
AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
AND comment = ''
AND compaction = {'class': 'SizeTieredCompactionStrategy'}
AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
AND dclocal_read_repair_chance = 0.1
AND default_time_to_live = 0
AND gc_grace_seconds = 864000
AND max_index_interval = 2048
AND memtable_flush_period_in_ms = 0
AND min_index_interval = 128
AND read_repair_chance = 0.0
AND speculative_retry = '99.0PERCENTILE';


INSERT INTO k.t (uid, due,entry_time) VALUES ('11',10,1) ; 
INSERT INTO k.t (uid, due,entry_time) VALUES ('11',11,2) ; 
INSERT INTO k.t (uid, due,entry_time) VALUES ('11',12,3) ; 
SELECT * FROM k.t WHERE uid='11' AND (due,entry_time) >(9,2); 
SELECT * FROM k.t ;
SELECT * FROM k.t WHERE uid='11' AND (due,entry_time) >(9,2) AND (due,entry_time) <(15,15);
```

I received the following results

```

 uid | due | entry_time | action_type | eid
-----+-----+------------+-------------+------
  11 |  10 |          1 |        null | null
  11 |  11 |          2 |        null | null
  11 |  12 |          3 |        null | null

(3 rows)

 uid | due | entry_time | action_type | eid
-----+-----+------------+-------------+------
  11 |  10 |          1 |        null | null
  11 |  11 |          2 |        null | null
  11 |  12 |          3 |        null | null

(3 rows)

 uid | due | entry_time | action_type | eid
-----+-----+------------+-------------+------
  11 |  10 |          1 |        null | null
  11 |  11 |          2 |        null | null
  11 |  12 |          3 |        null | null

(3 rows)
```

I ran it locally (5 times) all succeeded - will try to run it on an ubuntu server 

Is this reproducible on your setup ?

can you please share the complete /var/log/syslog

**Comment by tzach** [comment]
@scorpnode can you please provide /var/log/syslog ?

**Comment by slivne** [comment]
@scorpnode if there is additional info - please post it and we will reopen.
