### ISSUE TITLE
Provide a way to build private RPMs

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1423]
Instead of generating the version-release from scratch, I want to provide my own release, e.g. avi.bug1419 (to get 1.2.2-avi.bug1419)

**Comment by syuu1228** [comment]
Maybe we can add --release <custom_release> on dist/redhat/build_rpm.sh to overwrite $SCYLLA_RELEASE. Same on dist/ubuntu/build_deb.sh

**Comment by avikivity** [comment]
It's now possible via SCYLLA-VERSION-GEN SCYLLA_BUILD field.
