### ISSUE TITLE
Scylla metrics - no SSTable count

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#1424]
We need to add sstable count metrics
This metric is missing and we need to have the option to see it.

**Comment by slivne** [comment]
What are you looking for - there is a nodetool cfstats that provides the number of sstables for each keyspace ?

**Comment by nirmaayan** [comment]
I want to track the metric / grafana or other monitor
nodetool command isn't enough

**Comment by amnonh** [comment]
On Tue, Jul 5, 2016 at 5:45 PM, Shlomi Livne <notifications@github.com>
wrote:

> What are you looking for - there is a nodetool cfstats that provides the
> number of sstables for each keyspace ?
>
Not in collectd

**Comment by nirmaayan** [comment]
The motivation is to be able to track the growth of the SSTables. 
Running nodetool cfstats is an option but it want show the growth over time. 
This is for testing purposes

**Comment by tzach** [comment]
+1

**Comment by slivne** [comment]
If its not in collectd then there is an api for it via rest ....

**Comment by tzach** [comment]
@slivne REST API is a good solution for tools like nodetool.
Monitoring is base on collectd metric stream

**Comment by nirmaayan** [comment]
This metric is needed to monitor the growth of the SSTable.
For example if I have cluster with keyspace as mykespace and standard1 as my table I want to be able to track the growth (and decrease) of the SSTable count.
It also important for customers since it's not relevant to monitor specific node in large clusters.

**Comment by slivne** [comment]
@benoit-canet is the sstable-count from cfstats exported to prometheus ?

**Comment by benoit-canet** [comment]
From database.cc

            ms::make_gauge("live_sstable", ms::description("Live
sstable count"), _stats.live_sstable_count)(cf)(ks),


2017-08-02 17:43 GMT+02:00 Shlomi Livne <notifications@github.com>:

**Comment by bhalevy** [comment]
Can be closed with 292c08f598e9ae9d49d95f034a5d8ce195ff1e41
