### ISSUE TITLE
Don't able to build on Fedora 24

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#1433]
Since Fedora 24 switches gcc to 6, we have number of issues to build scylla.
I saw at least following build error:
- Compile error with newly added warnings
  - Compile error with 'Werror=misleading-indentation' on seastar/dpdk
  - Compile error with '-Werror=shift-negative-value' on seastar/dpdk
- f24 package version of Boost fails to compile https://svn.boost.org/trac/boost/ticket/12181

**Comment by avikivity** [comment]
f24-updates contains a fix for boost

**Comment by syuu1228** [comment]
@avikivity I see some build error from -Werror on seastar/dpdk, should we fix on seastar/dpdk or sync with more recent version of dpdk (if they fix it on latest tree)

**Comment by avikivity** [comment]
Dpdk update is needed in any case

**Comment by avikivity** [comment]
Probably fixed (and Fedora 24 is EOL soon)
