### ISSUE TITLE
Awkward upgrade procedure with remove/install

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1434]
*Installation details*
Scylla version (or git commit hash): 1.2->1.2

Upgrade should be done with `yum update` or `apt-get upgrade`, not remove/install.

**Comment by slivne** [comment]
@kongove 

according to the ubuntu upgrade guide we need todo 

```
Update the Scylla deb repo to 1.3
 Install

sudo apt-get update
sudo apt-get upgrade scylla

Answer ‘y’

sudo apt-get install scylla

```

why do we need todo install ?

**Comment by kongove** [comment]
We should remove the 'install' command, just sent a pull request to solve it: https://github.com/scylladb/www.scylladb.com/pull/192

**Comment by penberg** [comment]
The pull request was merged so I'm closing this issue.
