### ISSUE TITLE
CQL filter error: WHERE a=1 AND b in (1,2) AND c=3;

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1437]
_Installation details_
Scylla version (or git commit hash): 1.2
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS (Scylla AMI ami-31b97c51)

```
CREATE KEYSPACE mykeyspace WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
use mykeyspace;
CREATE TABLE test (a int, b int, c int, d int, PRIMARY KEY ((A), B, C));
insert into test (a,b,c,d) values (1,1,1,100);
insert into test (a,b,c,d) values (1,1,2,200);
insert into test (a,b,c,d) values (1,1,3,300);
insert into test (a,b,c,d) values (1,2,1,300);
insert into test (a,b,c,d) values (1,3,1,1300);
insert into test (a,b,c,d) values (1,3,2,1400);

select * from test where a=1 and b in (1,2) and c=3;
```

Results:
- Scylla 1.2: `InvalidRequest: code=2200 [Invalid query] message="Clustering column "c" cannot be restricted by an IN relation"`
- Cassandra 2.1.8 and 2.1.14: `InvalidRequest: code=2200 [Invalid query] message="Clustering column "b" cannot be restricted by an IN relation"`
  cannot be restricted by an IN relation"
- Cassandra 2.2.5: 

```
a | b | c | d
---+---+---+-----
 1 | 1 | 3 | 300
```

Scylla does support Cassandra 2.2 IN on clustering key, but not the addition 'c=1' part.
The same goes for  `select * from test where a=1 and b in (1,2) and c<3;`

**Comment by slivne** [comment]
@tzach can we push this out ?

**Comment by tzach** [comment]
@slivne @pdziepak is this part of 1.4?

**Comment by penberg** [comment]
@slivne @tzach Scylla 1.7 claims Cassandra 2.2 compatibility to drivers so we probably need to fix this for the release.

**Comment by slivne** [comment]
ref  2.2 has two different items 

Support IN clause on any clustering column https://issues.apache.org/jira/browse/CASSANDRA-4762,
Support IN clause on any partition key column https://issues.apache.org/jira/browse/CASSANDRA-7855

**Comment by tzach** [comment]
opened a dedicated issue to follow C* 7855
https://github.com/scylladb/scylla/issues/2473

**Comment by guxg** [comment]
We tried to migrate from Cassandra 3.10 to Scylla, but fall back again. 
The reason is we use IN features which is not compatible with Cassandra 3.10.
Please push this.
