### ISSUE TITLE
Streaming: mutation fragmentation inhibits write coalescing

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#1440]
Streaming splits mutations into 128 kB fragments. That size was chosen because the fragments need to be a continuous blocks of memory and being smaller than LSA size (256 kB) they won't cause excessive pressure on memory reclaimer.

However, if a mutation gets fragmented the receiving side of streaming cannot coalesce writes from multiple streaming plans and each one has to use their own memtables. This may cause receiver to write large number of small sstables.

The best solution to this problem seems to be avoiding linearization of fragmented mutations so that fragments can be much larger than 128 kB and still not cause too much pressure on memory allocators. With larger fragments the situation when streaming writes are not coalesced will be less likely and even if it happens the minimal size of sstables is going to be larger.

**Comment by avikivity** [comment]
Fixed by rpc streaming (ddfb4590ce48555a4bb048de82daefbfb9d38a5f).
