### ISSUE TITLE
Report a performance issue

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1441]
https://github.com/scylladb/scylla/issues/1348 is focused on collecting static data and crash aftermath like coredump. In addition, customer face performance issue, which is harder to identify, and require a different set of information.
Such a script will be used on _runtime_ and collect information from:
- sar -P ALL to see there isn't a single core that slows the rest
- iostat -x 1 To observe the disk utilization
- scyllatop collect reactor load and other relevant Scylla metrics

**Comment by dorlaor** [comment]
Get wild. We need network, interrupts, disk, cpu, perf record, scyllatop 10 sec dump and more

**Comment by dorlaor** [comment]
It's not about reporting, but about creating a report

**Comment by dorlaor** [comment]
Background: Many users are struggling to achieve good performance with scylla.
When we ask them for details, they always give 20% data from what requested..

I though to do 2 things for it:
1. Document on our website how to collect the entire data
2. Script the above

Beyond the commands that Tzach added, we need to grab perf record data on few cpus, feel
free to add more, including network and disk rates. Let's keep all in text form without
relaying on collectd/graphana. If Scyllatop can be used to retrieve 10 sec run, it would be
good to script it too.
Let's get it in our release (plus the website).

**Comment by tzach** [comment]
Let's start with a Wiki on "How to report a performance issue" and do the scripts later. This has become a repeated question, and the sooner we have a wiki to point to the better.

**Comment by amnonh** [comment]
In parallel, let's push scylla_housekeeping that was design to upload such
a report

**Comment by dorlaor** [comment]
+1 but it may need a --perf mode

**Comment by tzach** [comment]
I took a stab at performance report Wiki
https://github.com/scylladb/scylla/wiki/How-to-report-a-Scylla-perfromance-problem
Comment, updates are welcome

**Comment by raphaelsc** [comment]
On Sun, Jul 24, 2016 at 2:40 PM, Tzach Livyatan <notifications@github.com>
wrote:

> I took a stab at performance report Wiki
>
> https://github.com/scylladb/scylla/wiki/How-to-report-a-Scylla-perfromance-problem
>

typo on the title.

**Comment by dorlaor** [comment]
It's a good start. I like it to be on the mail site and not just the wiki.
In addition, it would be nice to place example output of each of the tools.
I'm missing the 'perf record', 'perf replay' on few selected CPUs.
Can you script it all as well?

**Comment by amnonh** [comment]
On Sun, Jul 24, 2016 at 11:36 PM, Dor Laor <notifications@github.com> wrote:

> It's a good start. I like it to be on the mail site and not just the wiki.
> In addition, it would be nice to place example output of each of the tools.
> I'm missing the 'perf record', 'perf replay' on few selected CPUs.
> Can you script it all as well?
>
If it can be run from the command line, I don't see why not

**Comment by tzach** [comment]
Added a perf example in the wiki
Is there's a way to display meaningful function names?

**Comment by tgrabiec** [comment]
2016-07-25 9:05 GMT+02:00 Tzach Livyatan <notifications@github.com>:

> Added a perf example in the wiki
> Is there's a way to display meaningful function names?
>

Do you have scylla-server-dgb installed?

**Comment by tgrabiec** [comment]
2016-07-24 19:40 GMT+02:00 Tzach Livyatan <notifications@github.com>:

> I took a stab at performance report Wiki
>
> https://github.com/scylladb/scylla/wiki/How-to-report-a-Scylla-perfromance-problem
> Comment, updates are welcome
>


The following should allow us to reproduce your benchmark or to get close
> to it.


This information is relevant not only for benchmarks. Perhaps we should
rename the "Stress" section to "Clients" section, and also request:
  - which driver version are the clients using
  - what type of queries are they using
  - what's the schema

**Comment by dorlaor** [comment]
Tzach, please move it to www. and github since it's easier to add comments.

Add a request to install our debug-info so the symbols from perf will be
significant.
The perf doesn't need to use the call graph. It's enough just to know what
are
the most active functions (w/o any parameter).

script, script.

**Comment by tgrabiec** [comment]
2016-07-25 9:37 GMT+02:00 Dor Laor <notifications@github.com>:

> Tzach, please move it to www. and github since it's easier to add comments.
>
> Add a request to install our debug-info so the symbols from perf will be
> significant.
> The perf doesn't need to use the call graph. It's enough just to know what
> are
> the most active functions (w/o any parameter).
>

It's not always enough to know the most active functions. For instance,
excessive copies may yield high time in memmove, but knowing that is not
enough to know where the problem is coming from. Callgraphs carry much more
information.

**Comment by tzach** [comment]
I failed to install debug info package on Scylla AMI, 
If anyone did it, please let me know how. 
#1496

**Comment by tgrabiec** [comment]
2016-07-25 10:23 GMT+02:00 Tzach Livyatan <notifications@github.com>:

> I failed to install debug info package on Scylla AMI,
> If anyone did it, please let me know how.
>

What was the error?

**Comment by tzach** [comment]
I had two  problems:
1. scylla repo is not available by default on AMI
2. `sudo yum clean all` was required

I add solution for both to the wiki

**Comment by glommer** [comment]
@tzach can this be closed? We have the health check script now and instructions in the website.

Those can always be improved but we should maybe be opening specific bugs for that if needed.
