### ISSUE TITLE
Implement thrift describe_splits verbs

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#1445]
*Installation details*
Scylla version (or git commit hash): master

Currently we don't support the describe_splits or describe_splits_ex verbs. This is an experimental API that splits the token ring such that each slice has a specified number of keys and returns an estimate of how many rows it contains. Some applications depend on it, like Presto (#1139).

Supporting it involves populating the size_estimates system table, which would expose this functionality to CQL3 clients as well (#352).

**Comment by duarten** [comment]
Here's how the Spark connector uses that system table: https://github.com/datastax/spark-cassandra-connector/blob/master/spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/partitioner/DataSizeEstimates.scala

**Comment by pdziepak** [comment]
It is a duplicate of #352.

**Comment by duarten** [comment]
Changed the description to be about the thrift verbs are referenced #352.

**Comment by slivne** [comment]
@duarten : as this is only thrift - are these verbs used by any application ?

**Comment by duarten** [comment]
@slivne Presto seems to rely on this verb.

**Comment by slivne** [comment]
thanks

**Comment by duarten** [comment]
Fixed by df346d8b4920dcc28fa978ffd94dd8de8271b78d.
