### ISSUE TITLE
thrift: Fully implement get_range_slices verb

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#1447]
*Installation details*
Scylla version (or git commit hash): master

In origin, empty partitions are returned as part of the KeySlice, for which the key will be filled in but the columns vector will be empty. Since in our case we don't return empty partitions, i.e., partitions for which a filter selected no rows, we don't know which partition keys in the specified range we should return back to the client. 

We should (optionally) send back empty partitions so that our behavior can match that of Origin.

**Comment by duarten** [comment]
Interestingly, it seems some Thrift users work around this: https://github.com/thinkaurelius/titan/blob/ee226e52415b8bf43b700afac75fa5b9767993a5/titan-cassandra/src/main/java/com/thinkaurelius/titan/diskstorage/cassandra/thrift/CassandraThriftKeyColumnValueStore.java#L341

**Comment by slivne** [comment]
closing for now - if we need it lets reopen

**Comment by tgrabiec** [comment]
I don't think this should be closed. The problem stated in the report still exists.

**Comment by penberg** [comment]
@slivne What's the rationale for "wontfix" tag?

**Comment by duarten** [comment]
@penberg While we don't behave exactly as Cassandra does, it's not clear their behavior is intended; it's certainly not very useful. For example, TitanDb works around it, as does [Astyanax](https://github.com/Netflix/astyanax/blob/4324ba7d133983ef93c5e7311bd5346adcc0bdf4/astyanax-thrift/src/main/java/com/netflix/astyanax/thrift/ThriftAllRowsImpl.java#L123).

**Comment by penberg** [comment]
@duarten OK, thanks for the explanation!
