### ISSUE TITLE
Flaky basic_date_tiered_strategy_test

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#1448]
*Installation details*
Scylla version (or git commit hash): master (73a70e6)
Fedora 24 (4.6.3-300.fc24.x86_64)
gcc (GCC) 6.1.1 20160621 (Red Hat 6.1.1-3)
boost-1.60.0-6.fc24.x86_64

This basic_date_tiered_strategy_test case in sstable_test is occasionally failing with: 

> tests/sstable_datafile_test.cc(2794): fatal error: in "basic_date_tiered_strategy_test": critical check sstables.size() == 4 has failed

**Comment by penberg** [comment]
@raphaelsc

**Comment by raphaelsc** [comment]
@penberg, @duarten  I will take a look into it. Thanks for sharing the details.
