### ISSUE TITLE
stream session fails but repair succeeds 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1452]
version 1.2.1

I have ran a test and in the tests had logs

```
2016-07-12 01:59:07,880 remote           L0192 DEBUG| [107.21.154.34] [stdout] Jul 11 22:59:07 ip-172-30-0-76 scylla[2471]:  [shard 0] stream_session - [Stream #419403c1-47b9-11e6-b83a-000000000000] Session with 172.30.0.77 is complete, state=FAILED
2016-07-12 01:59:07,880 remote           L0192 DEBUG| [107.21.154.34] [stdout] Jul 11 22:59:07 ip-172-30-0-76 scylla[2471]:  [shard 0] stream_session - [Stream #419403c1-47b9-11e6-b83a-000000000000] bytes_sent = 0, bytes_received = 22280364
2016-07-12 01:59:07,880 remote           L0192 DEBUG| [107.21.154.34] [stdout] Jul 11 22:59:07 ip-172-30-0-76 scylla[2471]:  [shard 0] stream_session - [Stream #419403c1-47b9-11e6-b83a-000000000000] Stream failed, peers={172.30.0.77, 172.30.0.78}
```

multiple times - repair continued to run

at the end I had 

```
2016-07-12 02:09:43,181 remote           L0192 DEBUG| [107.21.154.34] [stdout] Jul 11 23:09:41 ip-172-30-0-76 scylla[2471]:  [shard 0] repair - repair 2 completed sucessfully
```

are we supposed to abort if stream / part of the repair fails in the middle or continue - 

are we supposed to provide a failed result.
- we have tests (repair_kill_2_test) in which we kill a node during repair and then the repair fails - but in this case the issue is different

**Comment by tzach** [comment]
@slivne can we fix this in time for 1.3?

**Comment by slivne** [comment]
nope

**Comment by slivne** [comment]
@asias ping

**Comment by asias** [comment]
I think the problem is fixed in 1.4. If we fail to checksum a range or the stream_plan is failed, we won't log the repair as successfully. 

```
  0         }).then([id, &failed_ranges] {
  1             if (failed_ranges.empty()) {
  2                 logger.info("repair {} completed sucessfully", id);
  3                 repair_tracker.done(id, true);
  4             } else {
  5                 for (auto& frange: failed_ranges) {
  6                     logger.debug("repair cf {} range {} failed", frange.cf, frange.range);
  7                 }
  8                 logger.info("repair {} failed - {} ranges failed", id, failed_ranges.size());
  9                 repair_tracker.done(id, false);
 10             }
 11         }).handle_exception([id] (std::exception_ptr eptr) {
 12             logger.info("repair {} failed - {}", id, eptr);
 13             repair_tracker.done(id, false);
 14         });
```

**Comment by slivne** [comment]
@asias will repair be aborted - on first issue occurence or will it continue to make progress ?

**Comment by slivne** [comment]
@asias ping can you please answer the above question

**Comment by slivne** [comment]
@asias ping

**Comment by asias** [comment]
1. There are multiple checksum operations which can fail. This error will not abort the repair process. The error will be logged and we will not display "repair X completed sucessfully".

2. After the checksum phase, there will be two stream_plans, one for out traffic, one for in traffic. Any of them fail. The repair will fail.

**Comment by slivne** [comment]
Repair will not succeed in case of a streaming session failure
Repair will not be stopped on first occurrence of a failure and will continue.
Currently the information on which parts have success and which have not is only avilable via logs 
Need to decide if we are looking to utilize this information and return it to the user - this allows to execute following repairs on failed ranges (instead of resubmitting thefull failed repair).
