### ISSUE TITLE
IDL compiler support to generate verbs

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#1456]
_Installation details_
Scylla version (or git commit hash): HEAD

Currently to add or modify a verb one needs to write c++ code, but all the code is essentially the same.
We need a way to generate it from IDL instead.

**Comment by gleb-cloudius** [comment]
@amnonh

**Comment by amnonh** [comment]
@slivne please assign to me

**Comment by ManManson** [comment]
Solved in https://github.com/scylladb/scylla/commit/0ea79559a669259405265194aa33c1b8f7456ecc, closing.
