### ISSUE TITLE
Improve sstable reader cost estimation

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1458]
_Installation details_
Scylla version (or git commit hash): 23edc1861a127fd35a9131679781d79a7b3bd177

We currently treat all reads as costing 1 and allow 100 concurrent reads to run, but some reads will access dozens of sstables, and some only one.  Need to take that into consideration.

**Comment by raphaelsc** [comment]
@denesb is this still relevant?

**Comment by denesb** [comment]
Yes, in fact we have a duplicate issue for this, https://github.com/scylladb/scylla/issues/4295. I think we should close this as the latter has more details.
