### ISSUE TITLE
No nodetool status  indication when a node is down due to a storage error or nodetool drain

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1460]
*Installation details*
Scylla version (or git commit hash): 1.2.1

If a node is partially down due to `nodetool drain` or an I/O error, then `nodetool status` should indicate it.

**Comment by slivne** [comment]
@avikivity I think it does indicate it ..

Running ```nodetool status``` will indicate the node is down.

Running ```nodetool status``` on the local node - should show all the cluster down. 

Or are you expecting something else ?

**Comment by avikivity** [comment]
You are right, at least about drain.
