### ISSUE TITLE
Investigate consensus protocol for schema updates

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1461]
Instead of relying on the client to wait for schema propagation, use a consensus protocol to guarantee propagation

**Comment by tzach** [comment]
@avikivity @tgrabiec lets update this issue with latest progress and plans

**Comment by tzach** [comment]
@eliransin FYI

**Comment by avikivity** [comment]
Closing as too vague.

**Comment by tzach** [comment]
@avikivity can you please open a more precise issue

**Comment by avikivity** [comment]
I prefer not to. These issues hang around for years and no one comes up with a patch to close them. They don't contribute anything.
