### ISSUE TITLE
repair is not able to complete

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1466]
*Installation details*
Scylla version (or git commit hash): 1.2.1
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-dd46ffca
instance type i2.8xlarge

test ran with 4 loaders running on c3.xlarge each running

```
cassandra-stress write cl=QUORUM duration=240m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=200 limit=5000/s -pop seq=1..100000000 -node 172.30.0.12 -col 'size=FIXED(10240) n=FIXED(1)
```

 the test:

  1. pre populates the cluster with 100 GB on each node
  1. remove the data from one of the nodes
  1. restarts the node
  1. runs repair (while the write workload continues)

after ~20 minutes that the repair is running we get

```
  0,       0,       0,       0,       0
2016-07-17 12:09:22,474 remote           L0192 DEBUG| [52.90.79.61] [stdout] Jul 17 09:09:22 ip-172-30-0-12 scylla[8272]:  [shard 29] storage_proxy - exception during mutation write to 172.30.0.12: std::bad_alloc (std::bad_alloc)
2016-07-17 12:09:22,475 remote           L0192 DEBUG| [52.90.79.61] [stdout] Jul 17 09:09:22 ip-172-30-0-12 scylla[8272]:  [shard 28] storage_proxy - exception during mutation write to 172.30.0.12: std::bad_alloc (std::bad_alloc)
2016-07-17 12:09:22,476 remote           L0192 DEBUG| [52.90.79.61] [stdout] Jul 17 09:09:22 ip-172-30-0-12 scylla[8272]:  [shard 25] storage_proxy - exception during mutation write to 172.30.0.12: std::bad_alloc (std::bad_alloc)
2016-07-17 12:09:22,664 remote           L0192 DEBUG| [54.86.45.173] [stdout] total,      21188090,    4971,    4971,    4971,     4.3,     1.5,    14.2,    18.7,   243.8,   250.5, 4237.5,  0.00032,      0,      0,       0,       0,       0,       0
2016-07-17 12:09:22,773 remote           L0192 DEBUG| [54.172.123.116] [stdout] Jul 17 09:09:22 ip-172-30-0-13 scylla[2753]:  [shard 3] stream_session - [Stream #25aefc21-4bfe-11e6-bd88-00000000001e] stream_transfer_task: Fail to send STREAM_MUTATION to 172.30.0.12:0: std::runtime_error (std::bad_alloc)
```

and the repair at the end fails

There is very little drop in c-s performance over the repair period aside from when repair has just started - that actually is related to the node booting up ... (so the std::bad_alloc does not collide with that)

to reproduce

```
avocado run maintenance_test.py:MaintainanceTest.test_repair --multiplex tests/repair.ec2_i2-8x.cpu_25.data_100G.profile_write.yaml --filter-only /run/regions/us_east_1 /run/databases/cassandra
```
(depends on a pull request https://github.com/scylladb/scylla-cluster-tests/pull/134)

![node shlomi-scylla-loader-node-457644eb-4 54 172 56 164 172 30 0 32 seed none -lat](https://cloud.githubusercontent.com/assets/3465480/16920351/05c325bc-4d16-11e6-9022-77cc53c6d529.png)

![node shlomi-scylla-loader-node-457644eb-4 54 172 56 164 172 30 0 32 seed none -ops](https://cloud.githubusercontent.com/assets/3465480/16920352/05c3dde0-4d16-11e6-9fa5-ccdd798aabe7.png)

![node shlomi-scylla-loader-node-457644eb-3 52 91 187 6 172 30 0 33 seed none -lat](https://cloud.githubusercontent.com/assets/3465480/16920353/05c78724-4d16-11e6-89af-738438130df4.png)

![node shlomi-scylla-loader-node-457644eb-3 52 91 187 6 172 30 0 33 seed none -ops](https://cloud.githubusercontent.com/assets/3465480/16920354/05e1aaf0-4d16-11e6-8e68-b9503d53e0d6.png)

![node shlomi-scylla-loader-node-457644eb-2 52 90 30 131 172 30 0 38 seed none -lat](https://cloud.githubusercontent.com/assets/3465480/16920356/05e8c074-4d16-11e6-86e3-507c4b25d6b5.png)

![node shlomi-scylla-loader-node-457644eb-2 52 90 30 131 172 30 0 38 seed none -ops](https://cloud.githubusercontent.com/assets/3465480/16920355/05e8590e-4d16-11e6-8dda-d989c34e0946.png)

![node shlomi-scylla-loader-node-457644eb-1 54 86 45 173 172 30 0 39 seed none -lat](https://cloud.githubusercontent.com/assets/3465480/16920357/0605cbba-4d16-11e6-8d00-9410f7d798a5.png)

![node shlomi-scylla-loader-node-457644eb-1 54 86 45 173 172 30 0 39 seed none -ops](https://cloud.githubusercontent.com/assets/3465480/16920358/06098002-4d16-11e6-9425-daa1f66d8b2b.png)

**Comment by dorlaor** [comment]
Need to figure out why there wasn't enough memory for the repair on such
large node.
One observation about the graphs, the max latency dominates the diagram and
we cannot
see the other percentiles.

**Comment by lmr** [comment]
@dorlaor I've sent a Pull Request that separates the latency diagrams, making more clear the behavior of each latency curve.

**Comment by slivne** [comment]
with AMI of 1.3 -rc2+ the repair completes (using the same test and the same amount of data)

there is still an issue with latencies going up (and I do not have @lmr fix for splitting the graphs)



![node shlomi-scylla-loader-node-858fd150-4 54 85 102 59 172 30 0 14 seed none -lat](https://cloud.githubusercontent.com/assets/3465480/17515655/59a96f5a-5e42-11e6-9cbe-3cbe28fe11b6.png)
![node shlomi-scylla-loader-node-858fd150-4 54 85 102 59 172 30 0 14 seed none -ops](https://cloud.githubusercontent.com/assets/3465480/17515659/59ad0868-5e42-11e6-9585-f5d22c3fe2f6.png)
![node shlomi-scylla-loader-node-858fd150-3 54 165 141 159 172 30 0 254 seed none -lat](https://cloud.githubusercontent.com/assets/3465480/17515656/59aa1856-5e42-11e6-8a83-8500e2541b1c.png)
![node shlomi-scylla-loader-node-858fd150-3 54 165 141 159 172 30 0 254 seed none -ops](https://cloud.githubusercontent.com/assets/3465480/17515658/59ac3a78-5e42-11e6-8291-fd07709edc44.png)
![node shlomi-scylla-loader-node-858fd150-2 54 205 158 44 172 30 0 253 seed none -lat](https://cloud.githubusercontent.com/assets/3465480/17515657/59abdf4c-5e42-11e6-9d10-74c9cd862823.png)
![node shlomi-scylla-loader-node-858fd150-2 54 205 158 44 172 30 0 253 seed none -ops](https://cloud.githubusercontent.com/assets/3465480/17515660/59ad4f8a-5e42-11e6-9e56-508b8c72ec6e.png)
![node shlomi-scylla-loader-node-858fd150-1 52 91 18 213 172 30 0 252 seed none -lat](https://cloud.githubusercontent.com/assets/3465480/17515662/59ca3a96-5e42-11e6-91b1-3678a24867fe.png)
![node shlomi-scylla-loader-node-858fd150-1 52 91 18 213 172 30 0 252 seed none -ops](https://cloud.githubusercontent.com/assets/3465480/17515661/59c970d4-5e42-11e6-9b96-72501ee1712c.png)

**Comment by tzach** [comment]
@slivne the latency increase deserves its own issue

**Comment by slivne** [comment]
Yes it does but its another issue
