### ISSUE TITLE
add a way that will cause a core creation when std::bad_alloc is thrown to be able to debug this cases 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1468]
When running tests we reach a state there are std::bad_alloc - but scylla keeps on running.

During testing it would be good to enable a flag that will cause a core creation and allow us to debug this case.

**Comment by tzach** [comment]
fix with https://github.com/scylladb/seastar/commit/5b1051ce0de5b772f22444abe6a1d97076b49b1f
