### ISSUE TITLE
Key cache

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#1469]
Currently, every time we read a partition (or a slice of one) that is not available in our row cache, we need to read the index file to find where in the sstable data file the data lives. This is especially bad when paging through a very large partition - because a very large partition is never cached and because the amount of data to read from the index also becomes large (the index segment becomes large when promoted indices are included in the index).

The solution is to add a **key cache**, as Cassandra also has (see [this blog entry](http://www.datastax.com/dev/blog/maximizing-cache-benefit-with-cassandra)) - for keys we didn't cache their full partition, we can cache instead their index entry.

When caching the index entry with a promoted index in it, it might be worth our while to also build a list of blocks in the promoted index. With this list, we can do a binary search instead of linear search in the promoted index. For super-huge partitions, this might make a difference.

**Comment by glommer** [comment]
@nyh not sure if this should still be open. We have no plans of implementing a key cache.

Instead, we now:
- cache negatives
- will cache the promoted index (there is an issue about that)
- can cache individual rows.

Anything else still needed after the above that justifies a separate bug ?

**Comment by nyh** [comment]
@glommer, one might argue that "caching the promoted index" **is** a key cache :-)

In other words, since each sstable has a separate promoted index for a partition, a "promoted index" cache will need to remember which sstable had a match for this partition and which didn't, and parts of what the promoted index content was. If the promoted index is empty, we choose to the byte range of the entire partition at which point this becomes a key cache par excellence. I don't know if we plan to do this. It could be an optional feature (with the part about caching per-sstable misses and promoted index in large partitions not being optional).

**Comment by nyh** [comment]
This appears to be a duplicate of #194

**Comment by nyh** [comment]
I want to point out for posterity that a key cache - remembering index data for specific keys - may be relevant to large-partition workloads, but for workloads with small partitions - perhaps even no clustering keys, it is not helpful. In that case, it will be much more helpful to cache index-file blocks - possibly containing multiple keys - and not individual keys. This is #363. And if we do this, we probably don't need to do anything special for a key cache, and this issue can indeed be closed as @glommer suggested above.

**Comment by nyh** [comment]
Closing this issue as both a duplicate of #194, and also mostly solved by @tgrabiec 's recent patches caching index entries.
