### ISSUE TITLE
sstableloader - add rate limitting

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1471]

**Comment by tzach** [comment]
@elcallio ping

**Comment by elcallio** [comment]
Patch was sent 2 weeks ago or more. And pinged.

**Comment by slivne** [comment]
Doesn't scylladb/scylla-tools-java@0f6d40ff364de8fa2f8a94b1351b6e1df307dcc1 fix this ?

**Comment by penberg** [comment]
Yes, it does.
