### ISSUE TITLE
Scylla top output left on screen when using ^z

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#1472]
*Installation details*
Scylla version (or git commit hash):  1.3
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos 1.3 - AWS

scyllatop output left on the screen after execute ^x command
This is minor issue - clear command makes it usable again

![screenshot at 2016-07-20 13 02 45](https://cloud.githubusercontent.com/assets/18263247/16982796/8f993168-4e7a-11e6-88ae-aba157178e59.png)

**Comment by haarcuba** [comment]
a simple CTRL-L or "clear" command will clear the screen.
IMHO it's not worth tampering with code for this.

**Comment by nirmaayan** [comment]
Agreed that it's a minor issue but it can be annoying to users @tzach please advise for the priority

**Comment by tzach** [comment]
Agree with both of you
