### ISSUE TITLE
debuginfo integration in ubuntu 14.04 is broken

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1473]
_Installation details_
Scylla version (or git commit hash): 1.3

In ununtu 14.04 it appears that debug information is stored in a parallel tree under /usr/lib/debug; so debug info for /usr/bin/top is stored in /usr/lib/debug/usr/bin/top.  However, we use the .build-id hierarchy which only works on Fedora/RHEL.

**Comment by tgrabiec** [comment]
gdb can be convinced to read .build-id by setting `debug-file-directory`:
```
set debug-file-directory /usr/lib/debug
core scylla.core
file /usr/bin/scylla
sharedlibrary
```

**Comment by avikivity** [comment]
Good to know, I was using symbol-file.  But for native ubuntu packages, it works out of the box, so it should for us too.

**Comment by avikivity** [comment]
Ubuntu 14.04 is no longer supported.
