### ISSUE TITLE
CQL tracing - add "Sending message to" trace point

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1481]
*Installation details*
Scylla version (or git commit hash): 1.3 RC

Scylla `SELECT` trace example
```
 activity                                           | timestamp                  | source       | source_elapsed
----------------------------------------------------+----------------------------+--------------+----------------
               select * from users WHERE user_id=2; | 2016-07-21 10:18:48.846000 | 172.16.0.194 |              0
                           Done reading options [0] | 2016-07-21 10:18:48.847000 | 172.16.0.194 |             16
                            Parsing a statement [0] | 2016-07-21 10:18:48.847000 | 172.16.0.194 |             19
                         Processing a statement [0] | 2016-07-21 10:18:48.847000 | 172.16.0.194 |            109
           Done processing - preparing a result [0] | 2016-07-21 10:18:48.847000 | 172.16.0.194 |           1224
 read_data: message received from /172.16.0.194 [0] | 2016-07-21 10:18:48.853000 | 172.16.0.193 |             --
                     read_data handling is done [0] | 2016-07-21 10:18:48.853000 | 172.16.0.193 |             59
                                   Request complete | 2016-07-21 10:18:48.847242 | 172.16.0.194 |           1242
```

Execution path jumped from 193 to 194 and back. It will be useful to have  `Sending message to /172.16.0.193`  and `Message received from /172.16.0.194` trace points.
In particular in the face of network errors.

**Comment by tzach** [comment]
@vladzcloudius what does the `--` on  source_elapsed stands for? (line 6)

**Comment by dorlaor** [comment]
It will be nice to align the text to the left.

**Comment by tzach** [comment]
@dorlaor I suspect its CQLsh blame. Cassandra trace looks the same.

**Comment by dorlaor** [comment]
Agree but we can extract the #char per line and produce the buffer in a way
which will fix it.
I don't mind to fix cqlsh too

**Comment by vladzcloudius** [comment]
@dorlaor @tzach Tzach is right - the formatting is done by cqlsh.

About the actual issue - it's strange we don't have the "sending" message in a READ flow. 
I'll fix it right now.

**Comment by tzach** [comment]
@vladzcloudius what about the `--` on line 6, is it a bug?

**Comment by vladzcloudius** [comment]
@tzach No, again - this is a way cqlsh represents zero. Namely by '--' they mean to say "no time elapsed yet"
