### ISSUE TITLE
system_traces.sessions table does not have TTL

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1482]
*Installation details*
Scylla version (or git commit hash): Scylla 1.3 RC

Tracing tables should have time to live (TTL), so traces will not be accumulated forever.
Scylla table `system_traces.sessions` have `default_time_to_live = 0`
Cassandra table `system_traces.sessions` have `default_time_to_live = 86400`

**Comment by tzach** [comment]
same for `system_traces.events`

**Comment by vladzcloudius** [comment]
@tzach We always explicitly set TTL for each and every entry in both tables. Why a deafult_time_to_live value is so important?

**Comment by penberg** [comment]
@vladzcloudius What do we set the TTL to? How is it configured? What is the default TTL?

**Comment by vladzcloudius** [comment]
There is no such thing as a default TTL here.
For each QUERY (or NONE) typed trace it's 1 day, for each REPAIR (not yet instrumented) it's 7 days.
It's not configurable.

**Comment by vladzcloudius** [comment]
@penberg I see that C* seems to enable overriding these via .yaml

**Comment by tzach** [comment]
> We always explicitly set TTL for each and every entry in both tables. 

In that case, I agree it's not as urgent. From a user perspective, who does not read the code, having the TTL in the table is clearer.

**Comment by vladzcloudius** [comment]
On 07/21/2016 02:50 PM, Tzach Livyatan wrote:
>
>     We always explicitly set TTL for each and every entry in both tables.
>
> In that case, I agree it's not as urgent. From a user perspective, who 
> does not read the code, having the TTL in the table is clearer.
>

I've sent a patch that fixes that to the list
