### ISSUE TITLE
Install Scylla without Root or Sudo privileges 

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla#1485]
Customers may request an option to install Scylla using a "regular" user who do not have sudo rights.
The installation process should be able to install and configure all Scylla package under the unprivileged customer user.

**Comment by dorlaor** [comment]
We need to make sure that we have an option that:
 - Doesn't force a user creation
 - Use a different ROOT location for /etc, /var,..
 - Doesn't try to change filesystem, raid, irq configuratoin
 - etc

**Comment by avikivity** [comment]
It is not possible in general.  Setting up RAID, formatting XFS partitions, setting up services are all privileged operations.

At best we can offer a way to start scylla up, in a similar way to what developers do.

**Comment by dorlaor** [comment]
@avikivity the idea is that when we run with the user credentials we won't create RAID at all, nor format, etc. If someone has everything laid out by the admin, it's not a must to be root

**Comment by tzach** [comment]
@dorlaor @eyalgutkind is Docker a valid alternative in this case?

**Comment by dorlaor** [comment]
@tzach, no! Why add a ton of complexity just because tiny permission issue

**Comment by kientt86** [comment]
Anyone know if this issue is still active? When we can run scylladb without root access?

**Comment by dorlaor** [comment]
More users asked for this. Here is an outline of the solution:

I think it makes sense we'll address this requirement.
We need to split the Scylla functionality into two:

 1. Binaries and installation in non root area
     One should be able to run it manually with this non privileged install

 2. Operations that do require root mode
     This part promotes the installation to a root mode, mainly
     about mount points, raid creation, daemon configuration.

In general, one can extract the binaries from the rpm w/o being root.
The complexity is how to modify the scripts to run appropriately.

**Comment by tzach** [comment]
Is the non-root option for production or evaluation?
I'm guessing the first, as you will need a daemon, and probably RAID and XSF for production.
If this is the case, we can rephrase the requirement to: run without root on dev mode.

**Comment by dorlaor** [comment]
It's a production environment too.
Do note that it's not that no one runs the root-based operations. It's
mainly
a responsibility of another person who prepares the image

**Comment by thaylongs** [comment]
Hi, there is any update about it? Because I would like run the Scylla in the cluster of my university and I haven't access to the root user.

**Comment by dorlaor** [comment]
@eyalgutkind we have a doc for this, can you share the instructions and potentially move them to the docs section (@tzach )

**Comment by dorlaor** [comment]
We need root primarily to configure Linux appropriately and to register it
as a service (systemd capabilities can be an alternative).
Better just run the install and bypass some of the scripts, send a report
or a patch and we'll integrate it.

**Comment by avikivity** [comment]
This is now supported (with degraded performance) from scylla-package.tar.gz.

**Comment by yarix** [comment]
i don't have experience with scylla installer but, i'd except to have 2 separate users for installation and running.
The user that installs Scylla should probably have root/sudo but, the user scylladb run with, shouldn't have root access.

**Comment by sev3ryn** [comment]
@avikivity is there docker image for that?  I'm trying run Scylla for testing purposes on Kubernetes with runAsNonRoot security enforcement 

The error I'm getting is 
```
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '1'],)
Requires root permission.
```

**Comment by avikivity** [comment]
There is a docker image in https://hub.docker.com/r/scylladb/scylla. I don't know if it is compatible with runAsNonRoot.

**Comment by avikivity** [comment]
Please file a new issue about docker. This issue is about ordinary installations.
