### ISSUE TITLE
ubuntu-14.04: Kernel panic after installed scylla from officinal repo

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla#1486]
*Installation details*
Scylla version (or git commit hash): 1.2
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): ubuntu-14.04
kernel version: 3.13.0-91-generic x86_64

- Ubuntu Server 14.04 LTS (HVM), SSD Volume Type - ami-2d39803a
- Ubuntu/images/ebs-ssd/ubuntu-trusty-14.04-amd64-server-20160627 (ami-c93a83de)

*Hardware details (for performance issues)*
- c3.large

ISSUE description:
Install scylla by officinal apt source, then the machine panic. If I don't install scylla, the machine is fine. Unfortunately I didn't successfully setup kdump to get the crash core.

![crash-ubuntu-14 04](https://cloud.githubusercontent.com/assets/309708/17026628/4822e42c-4f93-11e6-9b4c-ed5907a9f6ab.jpeg)

[ubuntu_cmdline.log.txt](https://github.com/scylladb/scylla/files/376266/ubuntu_cmdline.log.txt)

**Comment by dorlaor** [comment]
AFAIK we are asking for a 4.2 kernel

On Thu, Jul 21, 2016 at 5:40 PM, Amos Jianjun Kong <notifications@github.com

**Comment by avikivity** [comment]
@dorlaor 3.15 is the first kernel that has good support for appending XFS AIO, so we ask for at least that
@kongove looks like just a kernel bug, it's probably not even from the scylla process.

Next time please use the "get system log" feature, not a screenshot.  In any case there's nothing we can do about it.

**Comment by kongove** [comment]
- http://www.scylladb.com/doc/getting-started-ubuntu/
- http://www.scylladb.com/doc/faq/#check-and-update-ubuntu-1404-kernel

In above two pages, we suggested users that 'Running Scylla on Ubuntu 14.04 requires kernel 3.15 or later'. But 3.16.0-76-generic still doesn't work. Should we suggest higher version of kernel for ubuntu 14.04 users?

kernel version: 3.16.0-76-generic, Panic:
[ubuntu-14.04-with3.16kernel.panic.txt](https://github.com/scylladb/scylla/files/376465/ubuntu-14.04-with3.16kernel.panic.txt)

Kernel version: 4.4.0-28-generic, work well.

kernel version: 3.13.0-91-generic, Panic:
[ubuntu-system-log(dmesg).txt](https://github.com/scylladb/scylla/files/376316/ubuntu-system-log.dmesg.txt)

**Comment by avikivity** [comment]
Were both of these crashes on the same instance (not instance type -- same VM)?

Those were crashes in the scheduler, unrelated to Scylla.  Maybe you got a bad VM.
