### ISSUE TITLE
Trying to add a new node, slow progress

### ISSUE THREAD

**Issue by Freeaqingme** [scylladb/scylla#1489]
*Installation details*
Scylla version (or git commit hash): 1.2.1-20160623.c56fc
Cluster size: 3 -> 4 nodes
OS: Ubuntu (3 nodes 14.04, 1 16.04)

I have 3 nodes, db0-db2 running off HDD's. Pursuing #1211 (will follow up on that shortly) I decided to move everything to SSD's. As such, I added a 4th node (db3). Db0-2 had about 500 Gb of data. Once I added db3 it went pretty smoothly, but eventually it stalled.

Realizing it could help if I ran 'nodetool repair' I ran that a couple of times (it runs about 12 hours, then panics - will report that separately). This reduced data to 309-372G per node. Before I had never ran the repair command, if this should be done regularly, perhaps we should document that?

Now I'm still trying to add the new node. It syncs some data, and then it stops again:

> Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 0] stream_session - [Stream #86a80680-4f77-11e6-ad27-000000000000] The session 0x60008372d800 is idle for 600 seconds, the peer 149.X.Y.135 is probably gone, close it
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 0] stream_session - [Stream #86a80680-4f77-11e6-ad27-000000000000] The session 0x60008372d800 is idle for 600 seconds, the peer 149.X.Y.135 is probably gone, close it
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 0] stream_session - [Stream #86a80680-4f77-11e6-ad27-000000000000] Streaming error occurred
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 0] stream_session - [Stream #86a80680-4f77-11e6-ad27-000000000000] Streaming error occurred
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 0] stream_session - [Stream #86a80680-4f77-11e6-ad27-000000000000] Session with 149.X.Y.135 is complete, state=FAILED
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 0] stream_session - [Stream #86a80680-4f77-11e6-ad27-000000000000] Session with 149.X.Y.135 is complete, state=FAILED
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 0] stream_session - [Stream #86a80680-4f77-11e6-ad27-000000000000] bytes_sent = 0, bytes_received = 3725806308
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 0] stream_session - [Stream #86a80680-4f77-11e6-ad27-000000000000] bytes_sent = 0, bytes_received = 3725806308
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 0] stream_session - [Stream #86a80680-4f77-11e6-ad27-000000000000] Stream failed, peers={149.X.Y.132, 149.X.Y.135, 149.X.Y.136}
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 0] stream_session - [Stream #86a80680-4f77-11e6-ad27-000000000000] Stream failed, peers={149.X.Y.132, 149.X.Y.135, 149.X.Y.136}
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]: Exiting on unhandled exception of type 'std::runtime_error': Error during boostrap: streaming::stream_exception (Stream failed)
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]: Exiting on unhandled exception of type 'std::runtime_error': Error during boostrap: streaming::stream_exception (Stream failed)
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 0] compaction_manager - Asked to stop
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 0] compaction_manager - Asked to stop
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 1] compaction_manager - Asked to stop
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 1] compaction_manager - Asked to stop
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 1] compaction_manager - Stopped
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 1] compaction_manager - Stopped
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 3] compaction_manager - Asked to stop
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 2] compaction_manager - Asked to stop
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 2] compaction_manager - Stopped
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 3] compaction_manager - Asked to stop
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 2] compaction_manager - Asked to stop
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 2] compaction_manager - Stopped
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 0] compaction_manager - Stopped
Jul 21 21:28:47 db3.scylla.example.com scylla[19007]:  [shard 0] compaction_manager - Stopped
Jul 21 21:28:48 db3.scylla.example.com scylla[19007]:  [shard 3] compaction_manager - compaction info: Compaction for kairosdb/data_points was stopped due to shutdown.
Jul 21 21:28:48 db3.scylla.example.com scylla[19007]:  [shard 3] compaction_manager - compaction info: Compaction for kairosdb/data_points was stopped due to shutdown.
Jul 21 21:28:48 db3.scylla.example.com scylla[19007]:  [shard 3] compaction_manager - compaction info: Compaction for kairosdb/data_points was stopped due to shutdown.
Jul 21 21:28:48 db3.scylla.example.com scylla[19007]:  [shard 3] compaction_manager - Stopped
Jul 21 21:28:48 db3.scylla.example.com scylla[19007]:  [shard 3] compaction_manager - compaction info: Compaction for kairosdb/data_points was stopped due to shutdown.
Jul 21 21:28:48 db3.scylla.example.com scylla[19007]:  [shard 3] compaction_manager - Stopped

Except for the exception, this could all very well be a typical case of pebkac, but what do I know :D

> root@db3:~# nodetool status
Datacenter: Present
================================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address          Load       Tokens  Owns    Host ID                               Rack
UJ  149.X.Y.65   0 bytes    256     ?       02de6397-1231-4e22-b028-9e7797c6ee28  16
UN  149.X.Y.135  ?          256     ?       baee8572-d933-4878-a905-3cc788faee88  16
UN  149.X.Y.132  ?          256     ?       e4f5762d-ac35-4158-b7cb-50d8e7400832  16
UN  149.X.Y.136  ?          256     ?       ea82c60b-5ef7-43ca-b8e8-a5dae6b90fea  16
>
>Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
> root@db3:~# nodetool status kairosdb
Datacenter: Present
================================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address          Load       Tokens  Owns (effective)  Host ID                               Rack
UJ  149.X.Y.65   0 bytes    256     ?                 02de6397-1231-4e22-b028-9e7797c6ee28  16
UN  149.X.Y.135  ?          256     100.0%            baee8572-d933-4878-a905-3cc788faee88  16
UN  149.X.Y.132  ?          256     100.0%            e4f5762d-ac35-4158-b7cb-50d8e7400832  16
UN  149.X.Y.136  ?          256     100.0%            ea82c60b-5ef7-43ca-b8e8-a5dae6b90fea  16
root@db3:~# 

> root@db1:~# nodetool status
Datacenter: Present
================================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address          Load       Tokens  Owns    Host ID                               Rack
UN  149.X.Y.136  333.51 GB  256     ?       ea82c60b-5ef7-43ca-b8e8-a5dae6b90fea  16
UJ  149.X.Y.65   ?          256     ?       02de6397-1231-4e22-b028-9e7797c6ee28  16
UN  149.X.Y.132  344.16 GB  256     ?       e4f5762d-ac35-4158-b7cb-50d8e7400832  16
UN  149.X.Y.135  305.69 GB  256     ?       baee8572-d933-4878-a905-3cc788faee88  16
>
> Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
root@db1:~# nodetool status kairosdb
Datacenter: Present
================================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address          Load       Tokens  Owns (effective)  Host ID                               Rack
UN  149.X.Y.136  333.51 GB  256     100.0%            ea82c60b-5ef7-43ca-b8e8-a5dae6b90fea  16
UJ  149.X.Y.65   ?          256     ?                 02de6397-1231-4e22-b028-9e7797c6ee28  16
UN  149.X.Y.132  344.16 GB  256     100.0%            e4f5762d-ac35-4158-b7cb-50d8e7400832  16
UN  149.X.Y.135  305.69 GB  256     100.0%            baee8572-d933-4878-a905-3cc788faee88  16
root@db1:~#

**Comment by penberg** [comment]
Ping @asias

**Comment by asias** [comment]
@Freeaqingme First, you do not have to run repair before you add DB3 node.  Even if you failed to add node3, you will be safe with data on existing DB0 to DB2 without repairing. Can you provide The log of DB0 to DB2? Do you have read/write cql load running when you adding DB3 node?

The log

"Jul 21 21:28:47 db3.scylla.example.com scylla[19007]: [shard 0] stream_session - [Stream #86a80680-4f77-11e6-ad27-000000000000] The session 0x60008372d800 is idle for 600 seconds, the peer 149.X.Y.135 is probably gone, close it"

suggests there is problem streaming from node 149.x.y.135. It can be node 149.x.y.135 is down or it freezes. 

I see you were using 1.2.X based branch (1.2.1-20160623.c56fc). We just released 1.2.2 release. Mind to upgrade and try?

**Comment by avikivity** [comment]
@asias is there a streaming related fix in 1.2.2?

@Freeaqingme are there any logs from the peer (149.x.y.135)?

**Comment by asias** [comment]
@avikivity There is no direct streaming related fix in 1.2.2.  My guess is node 149.x.y.135 hangs for some reason.  This one: 5ee6a00 (db: don't over-allocate memory for mutation_reader) looks related to streaming.  Is there anything in the seastar side in 1.2.2 release?

**Comment by avikivity** [comment]
@asias unlikely

**Comment by avikivity** [comment]
https://github.com/scylladb/scylla/commit/5ee6a00b0ffca8e1601e5e8675ef287ec6ee6f23 is not related directly to streaming, just to regular reads.  How many ranges are read in parallel?

**Comment by Freeaqingme** [comment]
I've stopped investing time in Scylla because in its current stage it proved too burdensome for us to get everything running smoothly. As such, I'm closing this issue.
