### ISSUE TITLE
scylla crashes when c-s is run when tracing of all requests is enabled

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#1491]
*Installation details*
Scylla version (or git commit hash):  e1480cd00de63c152510cbd7e397227e9ab36281
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04

*How to reproduce*
1) Enable traces for all Nodes:
Run for each Node
`curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" "http://<address>:10000/storage_service/trace_probability?probability=1"`
2) Run a c-s write test:
`./tools/bin/cassandra-stress write n=1000000 -rate threads=500`
3) Witness the SIGSEG in full glory! ;)

**Comment by vladzcloudius** [comment]
The root cause are the following lines from `cql_server::connection::process_prepare`:
```
return _server._query_processor.local().prepare(query, cs, false).then([this, stream, &cs] (auto msg) {
            tracing::trace(cs.get_trace_state(), "Done preparing on a local shard - preparing a result. ID is [{}]", seastar::value_of([&msg] {
                return messages::result_message::prepared::cql::get_id(std::move(msg));
            }));
            return this->make_result(stream, msg);
        });
```
I wonder how this even compiles - references may not be std::move()ed.

**Comment by gleb-cloudius** [comment]
On Fri, Jul 22, 2016 at 06:12:04AM -0700, vladzcloudius wrote:
> The root cause are the following lines from `cql_server::connection::process_prepare`:
> ```
> return _server._query_processor.local().prepare(query, cs, false).then([this, stream, &cs] (auto msg) {
>             tracing::trace(cs.get_trace_state(), "Done preparing on a local shard - preparing a result. ID is [{}]", seastar::value_of([&msg] {
>                 return messages::result_message::prepared::cql::get_id(std::move(msg));
>             }));
>             return this->make_result(stream, msg);
>         });
> ```
> I wonder how this even compiles - references may not be std::move()ed.
> 
This is const ref. It is copied instead.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Fri, Jul 22, 2016 at 05:04:51PM +0300, Gleb Natapov wrote:
> On Fri, Jul 22, 2016 at 06:12:04AM -0700, vladzcloudius wrote:
> > The root cause are the following lines from `cql_server::connection::process_prepare`:
> > ```
> > return _server._query_processor.local().prepare(query, cs, false).then([this, stream, &cs] (auto msg) {
> >             tracing::trace(cs.get_trace_state(), "Done preparing on a local shard - preparing a result. ID is [{}]", seastar::value_of([&msg] {
> >                 return messages::result_message::prepared::cql::get_id(std::move(msg));
> >             }));
> >             return this->make_result(stream, msg);
> >         });
> > ```
> > I wonder how this even compiles - references may not be std::move()ed.
> > 
> This is const ref. It is copied instead.
> 
Actually, not captured ref is not const, so this moves the msg.

--
			Gleb.

**Comment by vladzcloudius** [comment]
On 07/22/2016 05:05 PM, Gleb Natapov wrote:
> On Fri, Jul 22, 2016 at 06:12:04AM -0700, vladzcloudius wrote:
> > The root cause are the following lines from 
> `cql_server::connection::process_prepare`:
> > ```
> > return _server._query_processor.local().prepare(query, cs, 
> false).then([this, stream, &cs] (auto msg) {
> > tracing::trace(cs.get_trace_state(), "Done preparing on a local 
> shard - preparing a result. ID is [{}]", seastar::value_of([&msg] {
> > return messages::result_message::prepared::cql::get_id(std::move(msg));
> > }));
> > return this->make_result(stream, msg);
> > });
> > ```
> > I wonder how this even compiles - references may not be std::move()ed.
> >
> This is const ref. It is copied instead.

Right. But then my patch should have changed nothing - yet it does...
Strange...

**Comment by vladzcloudius** [comment]
On 07/22/2016 05:16 PM, Gleb Natapov wrote:
> On Fri, Jul 22, 2016 at 05:04:51PM +0300, Gleb Natapov wrote:
> > On Fri, Jul 22, 2016 at 06:12:04AM -0700, vladzcloudius wrote:
> > > The root cause are the following lines from 
> `cql_server::connection::process_prepare`:
> > > ```
> > > return _server._query_processor.local().prepare(query, cs, 
> false).then([this, stream, &cs] (auto msg) {
> > > tracing::trace(cs.get_trace_state(), "Done preparing on a local 
> shard - preparing a result. ID is [{}]", seastar::value_of([&msg] {
> > > return 
> messages::result_message::prepared::cql::get_id(std::move(msg));
> > > }));
> > > return this->make_result(stream, msg);
> > > });
> > > ```
> > > I wonder how this even compiles - references may not be std::move()ed.
> > >
> > This is const ref. It is copied instead.
> >
> Actually, not captured ref is not const, so this moves the msg.

What do u mean? It IS captured...

**Comment by vladzcloudius** [comment]
On 07/22/2016 05:23 PM, Vlad Zolotarov wrote:
>
>
>
> On 07/22/2016 05:16 PM, Gleb Natapov wrote:
>> On Fri, Jul 22, 2016 at 05:04:51PM +0300, Gleb Natapov wrote:
>> > On Fri, Jul 22, 2016 at 06:12:04AM -0700, vladzcloudius wrote:
>> > > The root cause are the following lines from 
>> `cql_server::connection::process_prepare`:
>> > > ```
>> > > return _server._query_processor.local().prepare(query, cs, 
>> false).then([this, stream, &cs] (auto msg) {
>> > > tracing::trace(cs.get_trace_state(), "Done preparing on a local 
>> shard - preparing a result. ID is [{}]", seastar::value_of([&msg] {
>> > > return 
>> messages::result_message::prepared::cql::get_id(std::move(msg));
>> > > }));
>> > > return this->make_result(stream, msg);
>> > > });
>> > > ```
>> > > I wonder how this even compiles - references may not be 
>> std::move()ed.
>> > >
>> > This is const ref. It is copied instead.
>> >
>> Actually, not captured ref is not const, so this moves the msg.
>
> What do u mean? It IS captured...

Oh, I see:

mutable 	- 	allows body to modify the parameters captured by copy, and 
to call their non-const member functions



So, it wasn't a const ref after all...
So, the fix is ok then...
