### ISSUE TITLE
Column value incorrectly identified as static with compact storage

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#1495]
*Installation details*
Scylla version (or git commit hash): 2f4cd86

Consider the following table:

```
cqlsh> create keyspace ks1 with replication = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
cqlsh> create table ks1.test(p blob, c blob, v blob, primary key (p, c)) with compact storage;
cqlsh> insert into ks1.test(p, c, v) values(0x0000000000000003, 0xfffffffffffeca, 0x);
cqlsh> select * from ks1.test;

 p                  | c                | v
--------------------+------------------+----
 0x0000000000000003 | 0xfffffffffffeca | 0x

(1 rows)
```

If we now reboot Scylla, we get the following behaviour when reading the value from its sstable:

```
cqlsh> select * from ks1.test;
ReadTimeout: code=1200 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for ks1.test - received only 0 responses from 1 CL=ONE." info={'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}
```

In Scylla's log:

```
ERROR 2016-07-24 18:29:48,569 [shard 1] storage_proxy - Exception when communicating with 127.0.0.1: Static row has clustering key information. I didn't expect that!
```

This is the relevant code:

```c++
static bool check_static(bytes_view col) {
    static bytes static_row(static_size, 0xff);
    return col.compare(0, static_size, static_row) == 0;
}

column(const schema& schema, bytes_view col)
    : is_static(check_static(col))
    , col_name(fix_static_name(col))
    , clustering(extract_clustering_key(schema))
    , collection_extra_data(is_collection(schema) ? pop_back(clustering) : bytes()) // collections are not supported with COMPACT STORAGE, so this is fine
    , cell(!schema.is_dense() ? pop_back(clustering) : (*(schema.regular_begin())).name()) // dense: cell name is not provided. It is the only regular column
    , cdef(schema.get_column_definition(cell))
{

    if (is_static) {
        for (auto& e: clustering) {
            if (e.size() != 0) {
                throw malformed_sstable_exception("Static row has clustering key information. I didn't expect that!");
            }
        }
    }
}
```

It feels like check_static should take into account a) the schema's compoundness if the schema.is_dense(), or b) the regular column information, as in:

```c++
static bool check_static(const schema& s, bytes_view col) {
    static bytes static_row(static_size, 0xff);
    return ((s.is_dense() && s.is_compound()) || (cdef && cdef.is_static())) && col.compare(0, static_size, static_row) == 0;
}
```

**Comment by slivne** [comment]
@pawel / @tgrabiec - can you please review and comment

**Comment by tgrabiec** [comment]
@duarten You're right, the code incorrectly assumes that cell names are always compound. It should check `s.thrift().has_compound_comparator`.

**Comment by tgrabiec** [comment]
We could use your new composite_view::is_static()

**Comment by duarten** [comment]
@tgrabiec Thanks! `s.thrift().has_compound_comparator()` already means the schema is dense, right? Should we also check `cdef.is_static()` like I did in the last code snippet?

**Comment by tgrabiec** [comment]
@duarten The relation between the two is: `is_dense => has_compound_comparator`. A table with compound cell names can have any denseness.

About the check to is_static() - in general the sstable would be malformed if the column was not static and would be present in the static row, so we should throw an exception. To handle schema changes, when a static column is dropped and then re-added as a regular column, we probably should first decide if the cell belongs to a dropped column by checking dropped_at field of the column_definition, and then if not dropped, proceed with it along with the checks.

**Comment by tgrabiec** [comment]
Actually, there is no implication between is_dense and has_compound_comparator, because a table can be dense and have a non-compound comparator (eg. a table with singe clustering column with compact storage).

**Comment by duarten** [comment]
@tgrabiec Thanks for the explanation! I'll prepare a patch.
