### ISSUE TITLE
HouseKeeping: ubuntu doesn't support enable/disable HouseKeeping in scylla_setup

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla#1497]
*Installation details*
Scylla version (or git commit hash): 1.3.rc1-20160721.c84e030
OS (RHEL/CentOS/Ubuntu/AWS AMI):  Ubuntu

*bug description*
HouseKeeping works in ubuntu, but after tried to 'disabled' it by running scylla_setup, it will works.
There is no any note in setup dialog about if it's supported ubuntu.

We need to support it.
@amnonh

[moving this to scylla project]

**Comment by tzach** [comment]
@amnonh ping

**Comment by kongove** [comment]
For latest RC, if '/etc/scylla.d/housekeeping.cfg' exists then skip interactive setup of housekeeping. It's unmasked (not disabled) by default.
And  latest change added support to enable/disable housekeeping from configure file.

We can close this issue.   @tzach
