### ISSUE TITLE
Off-strategy compaction suffers with 100% space overhead

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#14992]
Off-strategy compaction compacts the input disjoint set (of SSTables), produced by a repair operation, using "reshape compaction" in a single round, but it doesn't apply the incremental compaction which means that all input files are opened until the operation completion. Note it doesn't only cause disk space overhead, but also memory one as the metadata e.g. summary of a SSTable remains loaded in memory until the SSTable is closed. The overhead in memory can potentially cause pressure in the system, so memory can be aggressively reclaimed from LSA, and the system becomes unstable.

With incremental compaction, we smooth the process of integrating those new sstables, as we'll be able to remove 1G of input for each 1G of output in average, limiting the overhead to 1/N, where N is the size of input in GB.

One of the good reasons for reshaping the input set rather than forward it as is, is because we need to reduce the number of SSTables, as a high file count can produce memory issues due to minimal overhead per SSTable (includes inode metadata, etc). The system in general prefer a small number of big files.

**Comment by raphaelsc** [comment]
@bhalevy I think we need to increase priority of this one.

**Comment by bhalevy** [comment]
@avikivity what are the requirements for backporting the fix for this issue?
I know that ideally, we'd want it to be released first, but I think that in this case the fix is low-risk and high-reward so we can consider backporting it earlier.

**Comment by bhalevy** [comment]
@denesb do we use the backport labels for tracking the backports up to enterprise branches?
Otherwise, it looks like they can be cleared now.

**Comment by mykaul** [comment]
> @denesb do we use the backport labels for tracking the backports up to enterprise branches? Otherwise, it looks like they can be cleared now.

For Enterprise we'd use labels on the Enterprise issue, or a different dedicate issue on the Enterprise repo - not here.

**Comment by bhalevy** [comment]
@raphaelsc what enterprise issue tracks this problem?

**Comment by mykaul** [comment]
I think this was backported to 5.1 and 5.2 - but the labels are still here?

**Comment by raphaelsc** [comment]
> I think this was backported to 5.1 and 5.2 - but the labels are still here?

yes, backported to both already. do we have a bot automating removal for backports?

**Comment by mykaul** [comment]
> > I think this was backported to 5.1 and 5.2 - but the labels are still here?
> 
> yes, backported to both already. do we have a bot automating removal for backports?

no :(

**Comment by avikivity** [comment]
The maintainer should drop the labels after backporting.
