### ISSUE TITLE
jmx support for scylla

### ISSUE THREAD

**Issue by ycui1984** [scylladb/scylla#1500]
*Installation details*
Scylla version (or git commit hash): 1.2
Cluster size: one node
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

We want to collect metrics in a client machine using jmx (scylla node runs remotely).
The tool jconsole is used and we enable REMOTE support (set REMOTE=1 in   /usr/lib/scylla/jmx/scylla-jmx). However, when we run jconsole it seems connected, and waiting for several minutes, and then timed out. There is no data displayed during this period. 
Are there any other settings needed besides the one that I enabled?

**Comment by avikivity** [comment]
@amnonh

**Comment by amnonh** [comment]
The problem is most likely with jmx behind a nat, if you edit the scylla-jmx file add to teh exec line:
this flag:
 -Djava.rmi.server.hostname=your-external-ip

**Comment by amnonh** [comment]
I'll send a patch that enable changing by command line

**Comment by avikivity** [comment]
@ycui1984, is network address translation involved?  I think that would be the case on AWS or docker.

**Comment by ycui1984** [comment]
we did not use docker or AWS

**Comment by ycui1984** [comment]
it seems works for us when adding this. Thanks
