### ISSUE TITLE
HouseKeeping doesn't work in CentOS 7.2 (got systemd error of $SCYLLA_HOME)

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla#1501]
*Installation details*
Scylla version (or git commit hash): 1.3.rc1-20160721.c84e030
Systemd version: systemd-219-19.el7
Cluster size: single node
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.2
AMI ID: RHEL-7.2_HVM_GA-20151112-x86_64-1-Hourly2-GP2 (ami-2051294a)

We got this message, but I saw we set SCYLLA_HOME in EnvironmentFile (/etc/sysconfig/scylla-server)
```
systemd[1]: [/usr/lib/systemd/system/scylla-server.service:15] Not an absolute path, ignoring: $SCYLLA_HOME
```

```
$ systemctl|grep timer
UNIT                                             LOAD   ACTIVE SUB       DESCRIPTION
timers.target                                    loaded active active    Timers
scylla-housekeeping.timer                        loaded active elapsed   Run Scylla Housekeeping daily
systemd-tmpfiles-clean.timer                     loaded active waiting   Daily Cleanup of Temporary Directories

```

```
$ sudo service scylla-server status -l
Redirecting to /bin/systemctl status  -l scylla-server.service
● scylla-server.service - Scylla Server
   Loaded: loaded (/usr/lib/systemd/system/scylla-server.service; disabled; vendor preset: disabled)
   Active: active (running) since Mon 2016-07-25 17:57:24 EDT; 2h 23min ago
 Main PID: 2770 (scylla)
   Status: "serving"
   CGroup: /system.slice/scylla-server.service
           └─2770 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --max-io-requests=15

Jul 25 17:57:25 ip-10-138-151-110.ec2.internal scylla[2770]:  [shard 0] gossip - Checking if need_features {RANGE_TOMBSTONES} in features {LARGE_PARTITIONS, RANGE_TOMBSTONES}
Jul 25 17:57:25 ip-10-138-151-110.ec2.internal scylla[2770]:  [shard 0] gossip - Checking if need_features {LARGE_PARTITIONS} in features {LARGE_PARTITIONS, RANGE_TOMBSTONES}
Jul 25 17:57:25 ip-10-138-151-110.ec2.internal scylla[2770]:  [shard 1] gossip - Checking if need_features {RANGE_TOMBSTONES} in features {LARGE_PARTITIONS, RANGE_TOMBSTONES}
Jul 25 17:57:25 ip-10-138-151-110.ec2.internal scylla[2770]:  [shard 1] gossip - Checking if need_features {LARGE_PARTITIONS} in features {LARGE_PARTITIONS, RANGE_TOMBSTONES}
Jul 25 17:57:25 ip-10-138-151-110.ec2.internal scylla[2770]:  [shard 0] gossip - Waiting for gossip to settle before accepting client requests...
Jul 25 17:57:33 ip-10-138-151-110.ec2.internal scylla[2770]:  [shard 0] gossip - No gossip backlog; proceeding
Jul 25 17:57:33 ip-10-138-151-110.ec2.internal scylla[2770]:  [shard 0] storage_service - Starting listening for CQL clients on localhost:9042...
Jul 25 17:57:47 ip-10-138-151-110.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.service:15] Not an absolute path, ignoring: $SCYLLA_HOME
Jul 25 18:02:53 ip-10-138-151-110.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.service:15] Not an absolute path, ignoring: $SCYLLA_HOME
Jul 25 18:02:59 ip-10-138-151-110.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.service:15] Not an absolute path, ignoring: $SCYLLA_HOME
```

@amnonh Where can I found the timer log in CentOS?

**Comment by kongove** [comment]
I reinstalled scylla in a clean CentOS 7.2, the systemd error disappeared, and we can see HouseKeeping daily is started from journalctl log, but EC2 count is still not increased. 

```
Jul 25 22:00:03 ip-10-138-151-110.ec2.internal systemd[1]: Started Scylla Server.
Jul 25 22:00:03 ip-10-138-151-110.ec2.internal systemd[1]: Started Run Scylla Housekeeping daily.
Jul 25 22:00:03 ip-10-138-151-110.ec2.internal systemd[1]: Starting Run Scylla Housekeeping daily.
```

[journalctl.log.txt](https://github.com/scylladb/scylla/files/382940/journalctl.log.txt)

**Comment by kongove** [comment]
Referenced [1], I tried to manually enable and execute housekeeping service, and succeed.
```
sudo systemctl enable scylla-housekeeping.timer
sudo systemctl start scylla-housekeeping.timer
sudo systemctl enable scylla-housekeeping.service
sudo systemctl start scylla-housekeeping.service
```
Then when I restart scylla-server service, housekeeping will be exected once. It seems currently 'unmark' isn't enough to enable house-keeping (timer/service) in CentOS.

[1] https://seanmcgary.com/posts/how-to-use-systemd-timers

**Comment by kongove** [comment]
Additional setup to install requests module of python3 in CentOS 7.2, otherwise housekeeping script will fail.

```
sudo yum install python34-setuptools
easy_install-3.4 install requests
```

We can't assume user will check the log and install it by themselves, so how do we integrate this to our common setup (not scylla_setup script)?  @amnonh

**Comment by amnonh** [comment]
On Tue, Jul 26, 2016 at 7:30 AM, Amos Jianjun Kong <notifications@github.com
> wrote:

> Additional setup to install requests module of python3 in CentOS 7.2,
> otherwise housekeeping script will fail.
>
> sudo yum install python34-setuptools
> easy_install-3.4 install requests
>
> We can't assume user will check the log and install it by themselves, so
> how do we integrate this to our common setup (not scylla_setup script)?
> @amnonh <https://github.com/amnonh>
>
It should be added to the dependencies in the RPM

**Comment by slivne** [comment]
@amnonh - please send a patch

**Comment by tzach** [comment]
@amnonh ping

**Comment by amnonh** [comment]
On Sun, Aug 7, 2016 at 12:26 PM, Tzach Livyatan <notifications@github.com>
wrote:

> @amnonh <https://github.com/amnonh> ping
>
There's a patch waiting to be merged

**Comment by kongove** [comment]
@amnonh I tested with latest RC (ami-45811a52), the housekeeping doesn't work.

Instance Type: c3.large

```
[centos@ip-10-234-110-122 ~]$ rpm -qa |grep scylla
scylla-boost-thread-1.58.0-11.el7.centos.x86_64
scylla-boost-date-time-1.58.0-11.el7.centos.x86_64
scylla-jmx-1.3.rc3-20160815.ad895c2.el7.centos.noarch
scylla-boost-system-1.58.0-11.el7.centos.x86_64
scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
scylla-server-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64
scylla-tools-1.3.rc3-20160815.e7494d3.el7.centos.noarch
scylla-kernel-conf-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64
scylla-env-1.0-1.el7.centos.noarch
scylla-conf-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64
scylla-boost-test-1.58.0-11.el7.centos.x86_64
scylla-debuginfo-1.3.rc3-20160815.b2e6a52.el7.centos.x86_64
```

I restarted scylla-server many times, but the monitor count in aws wasn't increased.
I tried to manually execute the script, the count was increased.

```
/usr/lib/scylla/scylla-housekeeping -q -c /etc/scylla.d/housekeeping.cfg version
```

**Comment by kongove** [comment]
In above test, I checked the journalctl log, the housekeeping timer can be started after starting scylla-server service. But housekeeping.service can't be started (not log about housekeeping service)

```
[centos@ip-10-234-110-122 ~]$ sudo systemctl  status scylla-housekeeping.timer
● scylla-housekeeping.timer - Run Scylla Housekeeping daily
   Loaded: loaded (/usr/lib/systemd/system/scylla-housekeeping.timer; disabled; vendor preset: disabled)
   Active: active (elapsed) since Wed 2016-08-17 02:33:03 UTC; 9min ago

Aug 17 02:33:03 ip-10-234-110-122 systemd[1]: Started Run Scylla Housekeeping daily.
Aug 17 02:33:03 ip-10-234-110-122 systemd[1]: Starting Run Scylla Housekeeping daily.

[centos@ip-10-234-110-122 ~]$ sudo systemctl  status scylla-housekeeping.service
● scylla-housekeeping.service - Scylla Housekeeping
   Loaded: loaded (/usr/lib/systemd/system/scylla-housekeeping.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
```

I tried to enable it by systemctl, then housekeeping works.

```
[centos@ip-10-234-110-122 ~]$ sudo systemctl enable scylla-housekeeping.service
Created symlink from /etc/systemd/system/multi-user.target.wants/scylla-housekeeping.service to /usr/lib/systemd/system/scylla-housekeeping.service
```

Then restart scylla-server and check status of scylla-housekeeping.service
```
[centos@ip-10-234-110-122 ~]$ sudo service scylla-server restart
[centos@ip-10-234-110-122 ~]$ sudo systemctl  status scylla-housekeeping.service
● scylla-housekeeping.service - Scylla Housekeeping
   Loaded: loaded (/usr/lib/systemd/system/scylla-housekeeping.service; enabled; vendor preset: disabled)
   Active: inactive (dead) since Wed 2016-08-17 03:18:55 UTC; 1min 4s ago
  Process: 3004 ExecStart=/usr/lib/scylla/scylla-housekeeping -q -c /etc/scylla.d/housekeeping.cfg version (code=exited, status=0/SUCCESS)
 Main PID: 3004 (code=exited, status=0/SUCCESS)

Aug 17 03:18:55 ip-10-234-110-122 systemd[1]: Started Scylla Housekeeping.
Aug 17 03:18:55 ip-10-234-110-122 systemd[1]: Starting Scylla Housekeeping...
Aug 17 03:18:55 ip-10-234-110-122 scylla-housekeeping[3004]: A new version was found, current version=1.3.rc3-20160815.b2e6a52 latest version=1.3
```

**Comment by amnonh** [comment]
The housekeeping service should not be started by itself.
The timer starts it daily it runs and when its done it ends.

**Comment by kongove** [comment]
I tested with fresh installed RC ami, the timer failed to start the housekeeping.service if housekeeping.service is not enabled.

In aws monitor, there are very less access record (only once everyday from 8.8~8.16), if the house-keeping.service works well, recent new instance will have a lot access.

More suggestion:
1. we need a 'OnBootSec=0' in housekeeping.timer file to start the housekeeping.service after the timer is started.
2. enable the housekeeping.service, otherwise timer fails to start the service.

@amnonh can you help to check it?

**Comment by amnonh** [comment]
not sure how many instances are there that runs with the latest version of housekeeping.
in the long run, it doesn't really matter about running on startup.

Not sure why the housekeeping service needs enabling, I'll check that

**Comment by kongove** [comment]
Just confirmed with Amnon, we only expects the housekeeping.service to be run in next day.
So we don't need 'OnBootSec' parameter in housekeeping.timer file now. We might change this in future that depends on feature requests.

For the second question, @amnonh did you test by reducing the timer period (eg: 20s)? Then we can know if the disabled housekeeping.service would be run or not when the short timer is end. We don't need to check in the second day.

**Comment by amnonh** [comment]
On Wed, Aug 17, 2016 at 11:09 AM, Amos Jianjun Kong <
notifications@github.com> wrote:

> Just confirmed with Amnon, we only expects the housekeeping.service to be
> run in next day.
> So we don't need 'OnBootSec' parameter in housekeeping.timer file now. We
> might change this in future that depends on feature requests.
>
> For the second question, @amnonh <https://github.com/amnonh> did you test
> by reducing the timer period (eg: 20s)? Then we can know if the disabled
> housekeeping.service would be run or not when the short timer is end. We
> don't need to check in the second day.
>
When I tested it, I set the timer to somthing on the scale of minutes

**Comment by penberg** [comment]
@kongove What's the status of this issue?

**Comment by tzach** [comment]
@kongove did you validate the fix?

**Comment by kongove** [comment]
This problem isn't fixed:
```
2. enable the housekeeping.service, otherwise timer fails to start the service.
```

@amnonh is working to reproduce and fix it.

**Comment by kongove** [comment]
Update for housekeeping in CentOS 7.2

@amnonh In my original test, housekeeping service will never be run if it's not enabled.
I just found 'OnBootSec=0' solved this issue, after add this option to housekeeping.timer file,
reload daemon by 'sudo systemctl daemon-reload' and restart scylla-server, then housekeeping works.

Timer was started, but it doesn't work (repeatedly run service)
I tried to short the period to 60s, it still doesn't work.

```
[centos@ip-10-178-144-197 ~]$ systemctl status scylla-housekeeping.service
● scylla-housekeeping.service - Scylla Housekeeping
   Loaded: loaded (/usr/lib/systemd/system/scylla-housekeeping.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
[centos@ip-10-178-144-197 ~]$ systemctl status scylla-housekeeping.timer
● scylla-housekeeping.timer - Run Scylla Housekeeping daily
   Loaded: loaded (/usr/lib/systemd/system/scylla-housekeeping.timer; disabled; vendor preset: disabled)
   Active: active (elapsed) since Thu 2016-08-18 08:21:15 UTC; 48s ago

Aug 18 08:21:15 ip-10-178-144-197.ec2.internal systemd[1]: Started Run Scylla Housekeeping daily.
Aug 18 08:21:15 ip-10-178-144-197.ec2.internal systemd[1]: Starting Run Scylla Housekeeping daily.
[centos@ip-10-178-144-197 ~]$ sudo systemctl list-timers
NEXT                         LEFT       LAST PASSED UNIT                         ACTIVATES
n/a                          n/a        n/a  n/a    scylla-housekeeping.timer    scylla-housekeeping.service
Thu 2016-08-18 08:36:05 UTC  13min left n/a  n/a    systemd-tmpfiles-clean.timer systemd-tmpfiles-clean.service

2 timers listed.
```

But if I added a 'OnBootSec' parameter, timer started to work, the service also be repeated run.

```
[centos@ip-10-178-144-197 ~]$  sudo vim /usr/lib/systemd/system/scylla-housekeeping.timer
[centos@ip-10-178-144-197 ~]$ sudo systemctl daemon-reload
[centos@ip-10-178-144-197 ~]$ sudo service scylla-server restart
Redirecting to /bin/systemctl restart  scylla-server.service
[centos@ip-10-178-144-197 ~]$ systemctl status scylla-housekeeping.service
● scylla-housekeeping.service - Scylla Housekeeping
   Loaded: loaded (/usr/lib/systemd/system/scylla-housekeeping.service; disabled; vendor preset: disabled)
   Active: inactive (dead) since Thu 2016-08-18 08:23:32 UTC; 4s ago
  Process: 2040 ExecStart=/usr/lib/scylla/scylla-housekeeping -q -c /etc/scylla.d/housekeeping.cfg version (code=exited, status=0/SUCCESS)
 Main PID: 2040 (code=exited, status=0/SUCCESS)

Aug 18 08:23:31 ip-10-178-144-197.ec2.internal systemd[1]: Started Scylla Housekeeping.
Aug 18 08:23:31 ip-10-178-144-197.ec2.internal systemd[1]: Starting Scylla Housekeeping...
Aug 18 08:23:32 ip-10-178-144-197.ec2.internal scylla-housekeeping[2040]: A new version was found, current version=1.3.rc3-20160815.b2e6a52 latest...on=1.3
Hint: Some lines were ellipsized, use -l to show in full.
[centos@ip-10-178-144-197 ~]$ 
```

Conclusion: this issue was fixed by:
[PATCH] systemd: have the first housekeeping check right after start

**Comment by kongove** [comment]
@amnonh @slivne  I failed to build ami by jenkins jobs:
- job/scylla-1.3-ami/12    (ssh error)
- job/scylla-1.3-ami/13    (no available scylla package)

So I can't confirm with last RC (with my patch), and I just tested by manually adding 'OnBootSec' to housekeeping.timer file.

**Comment by kongove** [comment]
I built ami with latest code (cd9d967c4452f68d94997803c1afb6405e3b9368, contains my 'OnBootSec' patch) 
Jenkins job: job/scylla-1.3-ami/14

The housekeeping works well, create the instance, then get a version check.

@tzach let's close this issue?

**Comment by kongove** [comment]
Additional test of adjust timer period:

1. Change period in scylla-housekeeping.timer
2. reload daemon  by `sudo systemctl reload-daemon`
3. check with `systemctl list-timers`
4. check access record in aws monitor

Then the new period works.

**Comment by penberg** [comment]
I'm closing the issue.
