### ISSUE TITLE
Add perf to Scylla dependencies

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1505]
`perf` is used in [How to report a Scylla performance problem](https://github.com/scylladb/scylla/wiki/How-to-report-a-Scylla-performance-problem) guide.
We should include it in Scylla installation. The same goes for *sar*, *iostat* if not there

**Comment by tzach** [comment]
@avikivity thoughts?

**Comment by slivne** [comment]
@avikivity ping

**Comment by avikivity** [comment]
We shouldn't install packages that are not in normal use.
