### ISSUE TITLE
scyllatop - silent mode

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1506]
In some cases, a user wants to collect metrics for a few second and send the result as a file.
In such a case, it will be useful to run scyllatop in silent mode, something like
`scyllatop -silent -duration 10s > output.txt`

**Comment by avikivity** [comment]
If we use the prometheus integration, we can just fetch the endpoint URL a few times and send it raw.  This has the advantage that we can do any processing we do later, without any massaging of the data by scyllatop.

**Comment by tzach** [comment]
Yes, also a valid solution

**Comment by tzach** [comment]
If we change scyllatop to read from endpoint URL it the same feature.
For now, this simple addition to scyllatop will be helpful.
@haarcuba ?

**Comment by haarcuba** [comment]
submitted a patch.

**Comment by tzach** [comment]
@haarcuba ping

**Comment by haarcuba** [comment]
Patch is under review. I just forwarded the "ping"

**Comment by slivne** [comment]
@haarcuba ping ...

**Comment by haarcuba** [comment]
I've pinged it time and again - what more can I do?
