### ISSUE TITLE
Assertion `!(icl::is_empty(left) || icl::is_empty(right))' failed.

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1508]
*Installation details*
Scylla version (or git commit hash): efa690ce8c0268752ef773933fc5059c46120960
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 

Scylla args: sudo gdb --args ./build/release/scylla --log-to-stdout 1 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --cpuset 1-4 --smp 4 --memory 8G --options-file /etc/scylla/scylla.yaml --developer-mode 1

C-S args:   cassandra-stress write duration=5m -mode cql3 native -rate threads=500 -node 127.0.0.1 -schema compaction\(strategy=LeveledCompactionStrategy\)

scylla: /opt/scylladb/include/boost/icl/concept/interval.hpp:611: typename boost::enable_if<boost::icl::is_continuous_interval<Type>, bool>::type boost::icl::non_empty::exclusive_less(const Type&, const Type&) [with Type = boost::icl::continuous_interval<compatible_ring_position, std::less>; typename boost::enable_if<boost::icl::is_continuous_interval<Type>, bool>::type = bool]: Assertion `!(icl::is_empty(left) || icl::is_empty(right))' failed.

Running on AWS (centOS) with scylla compiled from scratch, and when tried to run gdb to get a backtrace, it exited abruptly with SIGSEGV. I will try to get more details later.

**Comment by avikivity** [comment]
Dup #1507

**Comment by avikivity** [comment]
patch on list, btw

**Comment by raphaelsc** [comment]
On Tue, Jul 26, 2016 at 5:19 PM, Avi Kivity <notifications@github.com>
wrote:

> patch on list, btw
>

Thanks. Applied it locally and the problem seems to be fixed.
