### ISSUE TITLE
HouseKeeping wrongly identifies new version by simple comparison

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla#1509]
*Installation details*
Scylla version (or git commit hash): 1.3.rc1-20160721.c84e030
Cluster size: single node
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 14.04

Current code identifies the version to be latest if it's different with local version.
It's not always correct.

Our server _should_ return latest official release version (1.2.2, it wrongly returns '1.3' right now).
But client might install 1.3-RC packages. So the local version is larger than server returned version. In this case, client will write a wrong log.

```
A new version was found, current version=1.3.rc1-20160721.c84e030 latest version=1.xx
```

```
def check_version(ar):
    current_version = get_api('/storage_service/scylla_release_version')
    latest_version = get_json_from_url(version_url)["version"]

    if current_version != latest_version:
        traceln("A new version was found, current version=", current_version, " latest version=", latest_version)
```

Suggestion: we can use parse_version to compare the versions.  @amnonh 

```
from pkg_resources import parse_version

>>> parse_version('1.3.rc1-20160721.c84e030') < parse_version('1.3')
True
>>> parse_version('1.3.rc1-20160721.c84e030') < parse_version('1.3.rc2')
True
>>> parse_version('1.3.rc1-20160721.c84e030') < parse_version('1.3.rc0')
False
>>> parse_version('1.3.rc1-20160721.c84e030') < parse_version('1.2')
False
```

**Comment by amnonh** [comment]
There is no rpm installation from pythno3 pkg_resource.

for 1.3 I'll send a patch that does a better string compare, we should see
what to do with python packages

**Comment by tzach** [comment]
@amnonh whats the status of this issue?

**Comment by amnonh** [comment]
housekeeping moved to python2 and dependencies where modified accordingly

**Comment by kongove** [comment]
The issue had been fixed, let's close this issue?
