### ISSUE TITLE
Scylla AMI: do not run in developer mode

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1511]
*Installation details*
Scylla version (or git commit hash): 1.2

Currently, scylla AMI has a limited set of predefined AMIs: 
i2 [i2.xlarge … i2.8xlarge]
m3 [m3.medium .. m3. 2xlarge]
c3 [c3.large .. c3.8xlarge]

For any other type, AMI is set with developer mode. The result is these AMI seems to be fine, and are up and running, but with no io.conf.

A better UX will be NOT to set dev mode, and add a clear warning to the existing prompt message, letting the user know he should run scylla_io_setup,. Something like:

```
  / ____|          | | |     |  __ \|  _ \ 
 | (___   ___ _   _| | | __ _| |  | | |_) |
  \___ \ / __| | | | | |/ _` | |  | |  _ < 
  ____) | (__| |_| | | | (_| | |__| | |_) |
 |_____/ \___|\__, |_|_|\__,_|_____/|____/ 
               __/ |                       
              |___/                        


Nodetool:
	nodetool help
CQL Shell:
	cqlsh
More documentation available at: 
	http://www.scylladb.com/doc/

    ScyllaDB is NOT active

** You should run scylla_io_setup ** 
```

(scylla_raid_setup do runs for all instances types)

**Comment by syuu1228** [comment]
I think more clearer way is prevent launch Scylla AMI on unsupported instance types.
To do that we will set release-AMI as 'Instance Store-Backed', which only able to launch on i2/m3/c3.
And we will have unstable-AMI as 'EBS-Backed',  which able to launch all instance types.

To implement this we need modify dist/ami to handle Instance store backed AMI, specify on an argument of the script.
Also need to change jenkins job to support two types of AMIs.
(I think we've frequently discussing same topic but postponed decision until now.)

**Comment by tzach** [comment]
@syuu1228 having two different AMI is confusing, and will lead to mistakes.
If I'm looking for ScyllaDB AMI and find two results, not sure which should I choose

> I think more clearer way is prevent launch Scylla AMI on unsupported instance types.

Can you do that?

**Comment by dorlaor** [comment]
On Jul 31, 2016 10:50 AM, "Tzach Livyatan" <notifications@github.com> wrote:
>
> @syuu1228 having two different AMI is confusing, and will lead to
mistakes.
> If I'm looking for ScyllaDB AMI and find two results, not sure which
should I choose
>>
>> I think more clearer way is prevent launch Scylla AMI on unsupported
instance types.
>
> Can you do that?

Another option is to launch it but require a standard, full configuration.
It would be like a standard vm, with our rpm pre-installed
