### ISSUE TITLE
Superblock compaction

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#152]
Compaction is able to free 32k segments, but anything above that will still be fragmented.

Since the compactor is able to move memory, we ought to be able to free as large a block as necessary.

We might do that by allocating all lsa memory up-front as a single block, and then moving segments internally to that block.  The downside is that we can only move memory from that block to the system (via `std::realloc()`), but not back.

We will need more information from seastar about free blocks remaining.

**Comment by avikivity** [comment]
@pdziepak we have this now, no?

**Comment by pdziepak** [comment]
Yes, these blocks of segments are called "zones".
