### ISSUE TITLE
nodetool compactionhistory rows_merged is empty 

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#1520]
Scylla version (or git commit hash): 1.3 RC!
Cluster size: 3
CEntos AMI

Running nodetool compactionhistory command the output is:

> id                 keyspace_name columnfamily_name compacted_at bytes_in bytes_out rows_merged
> 1753...        keyspace1          standard1                  146953422    139109      21122   

rows_merged column is empty

**Comment by tzach** [comment]
duplicate #666
