### ISSUE TITLE
Row tombstones saved differently from Cassandra

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#1525]
Scylla version (or git commit hash) :900639915d6f2e77b63d3ee40f07b58d38756534

Recently we fixed Scylla's approach to saving range tombstones - from overlapping whole-prefix tombstones we had originally, to disjoint range tombstones to match Cassandra's approach. We store these disjoint range tombstones internally in our memtables.

However, I believe that unlike Cassandra, we store "row tombstones" - tombstones specifically of one clustering row (as opposed to partial prefixes) - differently, as the tombstone of an individual deletable row. The problem is that I think this different internal representation is also leaked into the sstable output:

Consider the following CQL code which, among other somewhat irrelevant things, does two overlapping deletions: of one CQL row, and a larger prefix which includes it:

```sql
create keyspace try1 with replication = { 'class' : 'SimpleStrategy', 'replication_factor': 1 };
use try1;
create table data2 (
        pk int,
        ck1 int,
        ck2 int,
        v int,
        primary key (pk, ck1, ck2)
);
delete from data2 using timestamp 1000 where pk = 0 and ck1 = 0;
delete from data2 using timestamp 1010 where pk = 0 and ck1 = 0 and ck2 = 1;
insert into data2 (pk, ck1, ck2, v) values (0, 0, 0, 0) using timestamp 1020;
insert into data2 (pk, ck1, ck2, v) values (0, 0, 1, 1) using timestamp 1030;
insert into data2 (pk, ck1, ck2, v) values (0, 0, 2, 1) using timestamp 1035;
insert into data2 (pk, ck1, ck2, v) values (0, 1, 0, 0) using timestamp 1040;
```

This is how the resulting sstable looks like in **Cassandra** (displayed with sstable2json):

```
[
{"key": "0",
 "cells": [["0:_","0:1:_",1000,"t",1470033375],
           ["0:0:","",1020],
           ["0:0:v","0",1020],
           ["0:1:_","0:1:!",1010,"t",1470033375],
           ["0:1:","",1030],
           ["0:1:v","1",1030],
           ["0:1:!","0:!",1000,"t",1470033375],
           ["0:2:","",1035],
           ["0:2:v","1",1035],
           ["1:0:","",1040],
           ["1:0:v","0",1040]]}
]
```

Note how the two overlapping deletions with timestamp 1000 and 1010 were split into three range tombstones: [0:_, 0:1:_], [0:1:_,  0:1:!], [0:1:!, 0:!]. For the sstable2json-challenged, I'll translate it to English: The first tombstone is for the range from the start of the ck1=0 until just before ck1=0,ck2=1.  The second tombstone is the single cql row: from the beginning of ck1=0,ck2=1 until the end of that row. The third tombstone is the rest of ck1=0: From after the end of ck1=0,ck2=1, until the end of ck1=0.

With Scylla, we generate a different sstable:

```
[
{"key": "0",
 "cells": [["0:_","0:!",1000,"t",1470034202],
           ["0:0:","",1020],
           ["0:0:v","0",1020],
           ["0:1:","",1030],
           ["0:1:_","0:1:!",1010,"t",1470034202],
           ["0:1:v","1",1030],
           ["0:2:","",1035],
           ["0:2:v","1",1035],
           ["1:0:","",1040],
           ["1:0:v","0",1040]]}
]
```

The only difference is that now we have two tombstones instead of three, and these two tombstones are overlapping, not disjoint. This is how we *used* in the past to write range tombstones to sstables, but we're no longer supposed to be doing so. But we are - in the special case of single-row tombstones.

**Comment by tgrabiec** [comment]
Is the only problem here that we generate overlapping tombstones? That is legal, and C* also writes such tombstones, as I showed in this comment: https://github.com/scylladb/scylla/issues/1153#issuecomment-227471741

**Comment by nyh** [comment]
Yes, that is the only "problem".  If it's not a problem, I'm closing this issue, sorry....
It just complicates my life as I try to compare Cassandra and Scylla sstables bit for bit. I guess I should stop doing that.
