### ISSUE TITLE
transport file

### ISSUE THREAD

**Issue by simsunny22** [scylladb/scylla#1527]
dose scylla implement  transport file from one node to another node, when some node crush down.
if scylla has implement is , where it is.
thanks any way

**Comment by tzach** [comment]
@simsunny22 Scylla handles sync between nodes using repair.
Cassandra has an additional feature called handoff.  None of these features includes file transfer.

Can you please elaborate on what you are looking for and why?

**Comment by tzach** [comment]
@simsunny22 I'm closing this assuming I answered your question. Let me know if this is indeed the case.

**Comment by simsunny22** [comment]
thanks @tzach  
i just want to know scylla how implement the data transport  from one node to another.
i guess the data transport  by sstable, and i think the sstable  is file actually. 
so i ask if there is something about file transport.
but i found the /streaming folder. i read the code , and know the implement .
sorry reply too late

**Comment by avikivity** [comment]
If you have questions, ask them on the mailing list.

The issue tracker is for tracking issues.
