### ISSUE TITLE
Bug in memtable flush might result in disk exhaustion

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#1529]
When I inserted a bug (as part of the promoted index writing work) which caused sstable writing to fail with an exception, I noticed that in that case we go into an endless loop trying this write again every 10 seconds, which again and again fails for the same reason, and creates many partial (and probably corrupt) sstables.

It is arguable whether it is helpful to try the flush again endlessly, but even if we do, shouldn't we at least delete the corrupt sstables we created? Note these corrupt sstables will not cause any errors: The running Scylla will not see them (because we did not add them to the sstable list yet), and after reboot they will be deleted (because they still have their temporary TOC marker); But nevertheless,  they do take up disk space, possibly a lot (if the write failed towards the end). We can delete them immediately rather than wait for the reboot.

**Comment by tzach** [comment]
@nyh file system error handling should be according to 
```
# disk_failure_policy: stop
```
https://github.com/scylladb/scylla/blob/master/conf/scylla.yaml#L287

The node should take itself down gracefully.
If you see a different behavior its a bug

**Comment by duarten** [comment]
Fixed by b7e1575ad4a253f6da54525babf1408e6589a97f.
