### ISSUE TITLE
Improve mutation parallel sending limiter  for streaming

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#153]
Currently, we have per-shard mutation parallel sending limiter for streaming. The slow node (node in different datacenter, the node with less powerful hardware) might slow down a fast node.

Make the limiter per destination would help.

The current limiter:

stream_manager::_mutation_send_limiter

**Comment by avikivity** [comment]
Streaming was rewritten twice since the issue was opened. Closing as stale.
