### ISSUE TITLE
Support canonical seed names, not only IP addresses. (K8S petset)

### ISSUE THREAD

**Issue by Jan-M** [scylladb/scylla#1531]
Scylla version (or git commit hash): 1.3.rc2-20160728.23c340b
Cluster size: 3
Docker on GKE 1.3.3

It seems that using canonical host names for list of seeds is not supported:

```
ERROR 2016-08-01 18:21:06,258 [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Wrong format for IPv4 address cassandra-0.cassandra.zmon.svc.cluster.local. Please ensure it's in dotted-decimal format)
```

This makes it right now hard to deploy with GKE/PetSets, something that works with Cassandra.

The PetSet gives you stable host names, like cassandra-0, cassandra-1, ...

https://github.com/zalando-zmon/zmon-kubernetes/blob/master/dependencies/scylladb/petset.yaml

**Comment by Jan-M** [comment]
https://github.com/scylladb/scylla/blob/master/gms/inet_address.hh#L59

Seems there is a fixme, maybe I need to try this myself.

For my single node deployment btw KairosDB worked nicely with Scylla so far.

**Comment by penberg** [comment]
The same issue also reported here: https://github.com/scylladb/scylla/issues/1310
