### ISSUE TITLE
4k align reads issued, instead of 512 byte reads

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1532]
Seastar aligns reads to 512 bytes (if the storage device supports it), but Scylla degrades it back to 4k.  This reduces performance if we're limited by disk bandwidth, not IOPS.

**Comment by nyh** [comment]
Do you know where this 4k alignment occurs? Our sstable reads, index reads, etc., go to exact byte position ranges (which will be aligned by Seastar) and should not attempt to align anything to 4K boundaries... So I wonder where this alignment issue is coming from.

One thing to note that when sstable *compression* is enabled, we will always read entire chunks from the data file. The chunk should be roughly 2-3K (what remains from a 4K chunk of uncompressed data - 4K is our recently modified default compression chunk), and when this is aligned to 512 bytes, you may be seeing close to 4K reads. Could this be what you are seeing? Are you using compression?

**Comment by avikivity** [comment]
See patch on list

**Comment by nyh** [comment]
Hmm, I wasn't aware of this "checked-file" you just fixed... New code is entering Scylla at alarming^H^H^H^H^H^H^H^Hnice rate. Oh, well. Good you caught this.

**Comment by avikivity** [comment]
It's actually a file_impl bug that it allows this error so easily.  With virtual functions for disk_read_dma_alignment(), this would not have happened.  But we don't want virtuals there.

**Comment by nyh** [comment]
A stupid question: Why are virtual functions so bad here? The same function in "file" is already virtual. Isn't the I/O itself much more expensive than one more virtual function call?

**Comment by avikivity** [comment]
It's not virtual in file.

It's true that I/O is more expensive, but that's no reason to throw away cycles.

**Comment by benoit-canet** [comment]
modern disk and SSD are 4k internally anyway.

**Comment by avikivity** [comment]
All the disks I looked at reported 512b physical.

Transferring less data is also important.

**Comment by benoit-canet** [comment]
They lies :)

**Comment by benoit-canet** [comment]
https://www.google.fr/search?q=disk+4k+page+internally&oq=disk+4k+page+internally&aqs=chrome..69i57.4479j0j7&sourceid=chrome&ie=UTF-8#q=ssd+page+size

**Comment by benoit-canet** [comment]
it's a conspiracy: https://en.wikipedia.org/wiki/Advanced_Format

**Comment by nyh** [comment]
On Tue, Aug 2, 2016 at 1:54 PM, Benoît Canet <notifications@github.com>
wrote:

> it's a conspiracy: https://en.wikipedia.org/wiki/Advanced_Format
>

I'm not sure the above link proves anything (it is mostly about magnetic
hard disks), but I've seen in other sources that SSDs have a notion of
"page size" which is usually 4 or even 8 KB or sometimes 2 KB (but not 512
bytes), and reads can only be done in whole pages.

Often there is an emulation layer which accepts 512-byte requests, but
converts them into larger requests with some of the results being thrown
away. Whether it makes sense it use this emulation layer and send it
512-byte request, I don't know - maybe it does save a bit on PCI bandwidth.
But maybe it doesn't save anything. I don't know if what is limiting the
bandwidth is the SSD device or the PCI bandwidth. Only measurements will
tell.

**Comment by benoit-canet** [comment]
I simpy prove that the minimal read is 2k, 4k or more and 512b writes will
 be inefficient read/modify/write.

**Comment by avikivity** [comment]
We're always writing 4k, just reading 512b.
