### ISSUE TITLE
Empty mutations are not cached

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1533]
_Installation details_
Scylla version (or git commit hash):  0c1bf6c861ebfbc494cea00993d4c3cf9c63bb40

An empty mutation (due to a partition not present in any sstable) is not stored in cache, so we'll miss it again and again.

**Comment by tgrabiec** [comment]
Bloom filters were supposed to handle requests for non-existent data. Did you observe them being ineffective?

**Comment by avikivity** [comment]
No.  But it's still a good idea to catch those cases earlier, I think.

**Comment by nyh** [comment]
Also, there's some chance of false positives in a bloom filter, meaning that for a particular partition, there is a chance for the bloom filter to return "true" ("might be in sstable") while the partition is actually not in the sstable. If you have the bad luck of requesting such a partition multiple times, the bloom filter doesn't help at all.
A key cache (issue #1469), once we have it, could also be used to hold information about missing partitions.

**Comment by avikivity** [comment]
I thought the patch would b trivial, but it's not working.

```
--- a/row_cache.cc
+++ b/row_cache.cc
@@ -249,19 +249,19 @@ class single_partition_populating_reader final : public mutation_reader::impl {
             dht::decorated_key dk = sm->decorated_key();
             return try_to_read(_cache._max_cached_partition_size_in_bytes, std::move(sm)).then(
                 [this, op = std::move(op), dk = std::move(dk)]
                 (is_wide_partition wide_partition, mutation_opt&& mo) {
                     if (wide_partition == is_wide_partition::no) {
-                        if (mo) {
-                            _cache.populate(*mo);
-                            mo->upgrade(_schema);
-                            auto& ck_ranges = _ck_filtering.get_ranges(mo->key());
-                            auto filtered_partition = mutation_partition(std::move(mo->partition()), *(mo->schema()), ck_ranges);
-                            mo->partition() = std::move(filtered_partition);
-                            return make_ready_future<streamed_mutation_opt>(streamed_mutation_from_mutation(std::move(*mo)));
+                        if (!mo) {
+                            mo = mutation(std::move(dk), _schema);
                         }
-                        return make_ready_future<streamed_mutation_opt>(streamed_mutation_opt());
+                        _cache.populate(*mo);
+                        mo->upgrade(_schema);
+                        auto& ck_ranges = _ck_filtering.get_ranges(mo->key());
+                        auto filtered_partition = mutation_partition(std::move(mo->partition()), *(mo->schema()), ck_ranges);
+                        mo->partition() = std::move(filtered_partition);
+                        return make_ready_future<streamed_mutation_opt>(streamed_mutation_from_mutation(std::move(*mo)));
                     } else {
                         _cache.on_uncached_wide_partition();
                         auto reader = _underlying(_schema,
                                                   query::partition_range::make_singular(dht::ring_position(std::move(dk))),
                                                   _ck_filtering,
```

**Comment by nyh** [comment]
I think your patch is moving dk before it is used again by code below...

**Comment by nyh** [comment]
Hmm, sorry, on second read, it looks like dk is not used again... So it's something else...

**Comment by avikivity** [comment]
Moving dk probably doesn't work anyway, because the lambda is not mutable.

**Comment by avikivity** [comment]
I see the problem.

**Comment by avikivity** [comment]
It's also a little more complicated.  If we evict an empty mutation, but prev->is_contiguous, we should not clear prev->is_contiguous and instead assign prev->is_contiguous = this->is_contiguous.

@haaawk ?

**Comment by pdziepak** [comment]
We probably need another flag to indicate that this is negative entry. It turns out that Thrift is happy to return empty partition and this change has a potential of changing all `get*` verbs into `get_or_insert_empty*`

**Comment by avikivity** [comment]
It only inserts into the cache, how is that bad?

Ah, it's bad for partition scans.  So you are right.

**Comment by haaawk** [comment]
One thing missing in the patch I see is that you're changing only single_partition_populating_reader and the same change has to be applied to range_populating_reader.

**Comment by avikivity** [comment]
No, range_populating_reader will read in partitions from sstables and use the contiguous flag to indicate missing ones.

(we could insert negative entries for the beginning and end of the range, if they are inclusive, and if we get a key and not a token, but is it worth it?)

**Comment by tgrabiec** [comment]
2016-08-02 11:19 GMT+02:00 Paweł Dziepak <notifications@github.com>:

> We probably need another flag to indicate that this is negative entry. It
> turns out that Thrift is happy to return empty partition and this change
> has a potential of changing all get* verbs into get_or_insert_empty*
>

Thrift will return the partition if the partition exists in some way, eg.
has tombstones for instance. But would it return it if the partition never
existed? I didn't check, but that would be very unexpected in my opinion.
The fact that it returns deleted partitions is also dubious, I'm not sure
it's a feature rather than a bug. They changed that in CQL.

**Comment by haaawk** [comment]
We could introduce negative entries and make scanning code just ignore them.

**Comment by avikivity** [comment]
Another idea is to instantiate the entry preceding the miss and following the miss and set the contiguous bit.  We'd just instantiate the key, not the data.  This will trap other misses between these two entries.

**Comment by tgrabiec** [comment]
@avikivity How do we know the keys preceding and following the key which is queried?

**Comment by avikivity** [comment]
We read the index.  I guess we usually won't due to the bloom filter.  But maybe that works for clustering key negative entries.

**Comment by svetob** [comment]
Hi, just poking this issue a little since our tests and possibly our use case seems to run into this, causing disk throttling on AWS due to excessive IOPS on read, see discussion at https://groups.google.com/forum/#!topic/scylladb-users/O33qCifwzNA

**Comment by dorlaor** [comment]
@slivne please assign it to a person and a release since couple of users are hitting it and the performance diff is LARGE

**Comment by slivne** [comment]
This (and more) will be included in #960 @haaawk  is actively working on it

**Comment by slivne** [comment]
@tgrabiec is this covered by the row cache ?

**Comment by tgrabiec** [comment]
@slivne It's not.

**Comment by tgrabiec** [comment]
Note that it's a special case of https://github.com/scylladb/scylla/issues/2579. That's not to say we can't fix the special case first.
