### ISSUE TITLE
Mismatch between cache.misses and cache.insertions

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1534]
_Installation details_
Scylla version (or git commit hash): 1.2

Usually cache.insertions >= cache.misses (and in a read-only load, exactly equal.  In one load we're seeing insertions < misses, and concurrent parallel access to the same keys.

**Comment by tzach** [comment]
@avikivity  Do the new metric add info? is there an error in the metrics?

**Comment by avikivity** [comment]
@tgrabiec given the commit, I think we can close, no? if insertions + merges + misses_same_key = misses

**Comment by tgrabiec** [comment]
I think we can, yes.
