### ISSUE TITLE
Renaming column in compact storage table drops cells

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#1536]
*Installation details*
Scylla version (or git commit hash): 5995aeb

Reproducer:

```
cqlsh> create keyspace ks with replication = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
cqlsh> create table ks.cf(p text, c int, v blob, primary key (p, c)) with compact storage;
cqlsh> insert into ks.cf (p, c, v) values ('key1', 10, 0xffff);
cqlsh> select * from ks.cf;

 p    | c  | v
------+----+--------
 key1 | 10 | 0xffff

(1 rows)
cqlsh> alter table ks.cf rename c to pancake;
cqlsh> select * from ks.cf;

 p | pancake | v
---+---------+---

(0 rows)
```

Expected result:

```
cqlsh> select * from ks.cf;

 p    | pancake | v
------+---------+--------
 key1 |      10 | 0xffff

(1 rows)
```

I verified this works with Cassandra.

**Comment by duarten** [comment]
This only seems to happen before the values have been flushed to sstables. So, if there's a flush between writing and altering the table, it works correctly.

**Comment by raphaelsc** [comment]
On Tue, Aug 2, 2016 at 12:13 PM, Duarte Nunes <notifications@github.com>
wrote:

> This only seems to happen before the values have been flushed to sstables.
> So, if there's a flush between writing and altering the table, it works
> correctly.
>

It could be that the cell is still linked to the previous cell name, and
when cell name gets renamed, we cannot found it in memtable.

**Comment by duarten** [comment]
Yes, I think it's related to schema upgrading in memtables, although it's not yet clear to me why this happens for compact storage tables but not for normal ones.
