### ISSUE TITLE
UDT cannot work correctly when inserting data with nodejs cassandra driver

### ISSUE THREAD

**Issue by honggui** [scylladb/scylla#1539]
*Installation details*
Scylla version (or git commit hash): **1.2**

1.     sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/ubuntu/scylla-1.2-xenial.list
2.     sudo apt-get update
3.     sudo apt-get install scylla

Cluster size: **default size**
OS (RHEL/CentOS/Ubuntu/AWS AMI): **Ubuntu 16.04**
pyhthon: **2.7.12**
nodejs: **6.2.2**
cassandra-driver: **3.1.1**

**symptom**:
    When inserting data with "user defined type" field, will got the below error message:
       TypeError: value.get is not a function (the log scylladb.log is in the attached zip file [scylladb_test.zip](https://github.com/scylladb/scylla/files/398556/scylladb_test.zip) )
**Cause**:
    UDT's type.code should be 48, but it is 49 when reading it in the function FrameReader.prototype.readType, and then got the above error message

**more information**:
   

1.  In the attached zip file, there's another test application "test_cassandra_tuple.js", will get a error message with metadata.getTable. this is another issue.(the log scylladb_tuple.log is in the attached zip file [scylladb_test.zip](https://github.com/scylladb/scylla/files/398556/scylladb_test.zip) )
2.  When I run the 2 test applications with Cassandra server, they are working well. Cassandra's installation details are (the log is attached below as 
[cassandra_log.zip](https://github.com/scylladb/scylla/files/398576/cassandra_log.zip)
)  

- apt-get install openjdk-8-jre-headless
- echo "deb http://debian.datastax.com/community stable main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
- curl -L https://debian.datastax.com/debian/repo_key | sudo apt-key add -
- apt-get update
- apt-get install cassandra
- apt-get install cassandra-tools

**the test application**
[scylladb_test.zip](https://github.com/scylladb/scylla/files/398556/scylladb_test.zip)

**Comment by tzach** [comment]
@honggui thanks for reporting!
Did you try running the same insert from cqlsh?
If that works, it hints the problem is in the JS driver compatibility

**Comment by avikivity** [comment]
Looks like a dup of #1443, which was fixed in 1.2.2.

Please retest with 1.2.3.

**Comment by honggui** [comment]
@tzach cqlsh can work when inserting data. 
@avikivity yes, you are right. After update to 1.2.3, it is ok now. Thanks!
BTW, the updation commands are listed below for other reference --
1. sudo apt-get update 
2. sudo apt-get remove scylla scylla-conf scylla-jmx scylla-server scylla-tools
3. sudo apt-get install scylla
**Notes:** 
A. if not set source.list, we need run the command before the above 3 steps(sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/ubuntu/scylla-1.2-xenial.list
)
B. if I only run the above steps#1 and #3, but skip #2, the update is not right. So the step#2 seems necessary.

**Comment by honggui** [comment]
After updating to version 1.2.3, the issue was fixed. Thanks for  @avikivity 's help!
