### ISSUE TITLE
Scylla is returning inconsistent results with row cache disabled

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1544]
`cqlsh>   CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'} ; USE ks;
cqlsh:ks> CREATE COLUMNFAMILY ks.cf (p1 text, c1 text, r1 int, PRIMARY KEY (p1, c1)) WITH compaction= {'class': 'NullCompactionStrategy'};
cqlsh:ks> INSERT INTO ks.cf (p1, c1, r1) VALUES ('key1', 'a', 1);
cqlsh:ks> INSERT INTO ks.cf (p1, c1, r1) VALUES ('key1', 'b', 1);
cqlsh:ks> SELECT COUNT(*) FROM cf
      ... ;

 count
-------
     2

(1 rows)
cqlsh:ks> SELECT * FROM ks.cf WHERE p1 = 'key1' AND c1 <= 'a' AND c1 >= 'b';

 p1 | c1 | r1
----+----+----

`

Doing the same as thing as above, but issuing './bin/nodetool flush -- ks' after each INSERT, Scylla returns the following:

`
cqlsh:ks> SELECT * FROM ks.cf WHERE p1 = 'key1' AND c1 <= 'a' AND c1 >= 'b';

 p1   | c1 | r1
------+----+----
 key1 |  a |  1
 key1 |  b |  1
`

**Comment by tgrabiec** [comment]
`partition_slice_clustering_key_filter_factory::get_filter_for_sorted`, used by sstable reading code, calls `range::contains` to check if row contains the key, and the range is treated as a wrap around so it does contain it. Treating such a range as a wrap around is against CQL semantics, wrap arounds should be treated as empty ranges. 

It would be best if we don't create wrap arounds at all for clustering range, and convert ones we get from RPC in partition_slice constructor.

**Comment by tzach** [comment]
@tgrabiec is this issue a regression from 1.2?

**Comment by tgrabiec** [comment]
@tzach It's probably a regression introduced in 1.2.0
