### ISSUE TITLE
Make bytes_ostream::append() append using fragmented storage

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1546]
Currently it allocates one big chunk. If it's big, allocation may fail due to memory fragmentation or contribute to memory fragmentation.

**Comment by tzach** [comment]
@tgrabiec when is this an issue? in wide partition only? other cases?

**Comment by tgrabiec** [comment]
@tzach It's a problem not only with wide partitions. It's a problem which affects, for instance, query result processing. What's relevant is the size of query results, not partitions inside the results. Fixing append() alone won't solve the problem though, because query results need to be currently linearized anyway, because deserializers don't work with fragmented storage.
