### ISSUE TITLE
[1.3 RC2 AMI] Coredumps observed during 8 hour longevity test

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#1547]
*Installation details*
Scylla version (or git commit hash): ami-19aa3d0e (copied to us-west-2, ami-5acb023a)

    2016-08-04 09:38:27,670 nemesis          L0080 INFO | sdcm.nemesis.ChaosMonkey: Report
    2016-08-04 09:38:27,670 nemesis          L0081 INFO | sdcm.nemesis.ChaosMonkey: DB Version:
    2016-08-04 09:38:27,670 nemesis          L0083 INFO | sdcm.nemesis.ChaosMonkey: scylla-boost-date-time-1.58.0-11.el7.centos.x86_64
    2016-08-04 09:38:27,671 nemesis          L0083 INFO | sdcm.nemesis.ChaosMonkey: scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
    2016-08-04 09:38:27,671 nemesis          L0083 INFO | sdcm.nemesis.ChaosMonkey: scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
    2016-08-04 09:38:27,671 nemesis          L0083 INFO | sdcm.nemesis.ChaosMonkey: scylla-boost-system-1.58.0-11.el7.centos.x86_64
    2016-08-04 09:38:27,671 nemesis          L0083 INFO | sdcm.nemesis.ChaosMonkey: scylla-boost-test-1.58.0-11.el7.centos.x86_64
    2016-08-04 09:38:27,671 nemesis          L0083 INFO | sdcm.nemesis.ChaosMonkey: scylla-boost-thread-1.58.0-11.el7.centos.x86_64
    2016-08-04 09:38:27,671 nemesis          L0083 INFO | sdcm.nemesis.ChaosMonkey: scylla-conf-1.3.rc2-20160729.23c340b.el7.centos.x86_64
    2016-08-04 09:38:27,671 nemesis          L0083 INFO | sdcm.nemesis.ChaosMonkey: scylla-env-1.0-1.el7.centos.noarch
    2016-08-04 09:38:27,671 nemesis          L0083 INFO | sdcm.nemesis.ChaosMonkey: scylla-gdb-7.10.1-30.el7.centos.x86_64
    2016-08-04 09:38:27,671 nemesis          L0083 INFO | sdcm.nemesis.ChaosMonkey: scylla-jmx-1.3.rc2-20160729.e87c771.el7.centos.noarch
    2016-08-04 09:38:27,672 nemesis          L0083 INFO | sdcm.nemesis.ChaosMonkey: scylla-server-1.3.rc2-20160729.23c340b.el7.centos.x86_64
    2016-08-04 09:38:27,672 nemesis          L0083 INFO | sdcm.nemesis.ChaosMonkey: scylla-tools-1.3.rc2-20160729.472d2da.el7.centos.noarch
    2016-08-04 09:38:27,672 nemesis          L0084 INFO | sdcm.nemesis.ChaosMonkey: Interval: 900 s
    2016-08-04 09:38:27,672 nemesis          L0085 INFO | sdcm.nemesis.ChaosMonkey: Average duration: 1576 s
    2016-08-04 09:38:27,672 nemesis          L0086 INFO | sdcm.nemesis.ChaosMonkey: Total execution time: 29188 s
    2016-08-04 09:38:27,672 nemesis          L0087 INFO | sdcm.nemesis.ChaosMonkey: Times executed: 11
    2016-08-04 09:38:27,672 nemesis          L0088 INFO | sdcm.nemesis.ChaosMonkey: Unhandled exceptions: 0

Cluster size: Cluster scylla-1-3-rc2-scylla-db-cluster-2d0f0f18 (AMI: ami-5acb023a Type: c3.xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

Running the longevity test for 8 hours on a c3.xlarge cluster, we observed a coredump generated:

               PID: 11378 (scylla)
               UID: 994 (scylla)
               GID: 1001 (scylla)
            Signal: 6 (ABRT)
         Timestamp: Thu 2016-08-04 07:51:44 UTC (1h 28min ago)
      Command Line: /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --num-io-queues 4 --max-io-requests 32
        Executable: /usr/bin/scylla
     Control Group: /system.slice/scylla-server.service
              Unit: scylla-server.service
             Slice: system.slice
           Boot ID: 24b8143161b34f27927f2868d5a4f532
        Machine ID: 8ea3e6ea03b64d018847fcdf669935d4
          Hostname: ip-172-31-38-120
          Coredump: /var/lib/systemd/coredump/core.scylla.994.24b8143161b34f27927f2868d5a4f532.11378.1470297104000000.xz
           Message: Process 11378 (scylla) of user 994 dumped core.
                    
                    Stack trace of thread 11379:
                    #0  0x00007f6a5f0555f7 raise (libc.so.6)
                    #1  0x00007f6a5f056ce8 abort (libc.so.6)
                    #2  0x00007f6a5f04e566 __assert_fail_base (libc.so.6)
                    #3  0x00007f6a5f04e612 __assert_fail (libc.so.6)
                    #4  0x0000000000504df2 n/a (scylla)
                    #5  0x000000000051a5dc n/a (scylla)
                    #6  0x00000000004d570e n/a (scylla)
                    #7  0x000000000050326b n/a (scylla)
                    #8  0x00000000005205dd n/a (scylla)
                    #9  0x00000000005522de n/a (scylla)
                    #10 0x00007f6a5f3e8dc5 start_thread (libpthread.so.0)
                    #11 0x00007f6a5f11621d __clone (libc.so.6)
                    
                    Stack trace of thread 11383:
                    #0  0x00007f6a5f3ef22d read (libpthread.so.0)
                    #1  0x00000000004d5fbe n/a (scylla)
                    #2  0x00000000005522de n/a (scylla)
                    #3  0x00007f6a5f3e8dc5 start_thread (libpthread.so.0)
                    #4  0x00007f6a5f11621d __clone (libc.so.6)
                    
                    Stack trace of thread 11384:
                    #0  0x00007f6a5f3ef22d read (libpthread.so.0)
                    #1  0x00000000004d5fbe n/a (scylla)
                    #2  0x00000000005522de n/a (scylla)
                    #3  0x00007f6a5f3e8dc5 start_thread (libpthread.so.0)
                    #4  0x00007f6a5f11621d __clone (libc.so.6)
                    
                    Stack trace of thread 11385:
                    #0  0x00007f6a5f3ef22d read (libpthread.so.0)
                    #1  0x00000000004d5fbe n/a (scylla)
                    #2  0x00000000005522de n/a (scylla)
                    #3  0x00007f6a5f3e8dc5 start_thread (libpthread.so.0)
                    #4  0x00007f6a5f11621d __clone (libc.so.6)
                    
                    Stack trace of thread 11381:
                    #0  0x000000000054e0b2 n/a (scylla)
                    #1  0x000000000076731e n/a (scylla)
                    #2  0x00000000010ab56c n/a (scylla)
                    #3  0x00000000010bbf66 n/a (scylla)
                    #4  0x0000000001000cc3 n/a (scylla)
                    #5  0x0000000000cee447 n/a (scylla)
                    #6  0x0000000000cf05a9 n/a (scylla)
                    #7  0x0000000000d327c4 n/a (scylla)
                    #8  0x0000000000d32a04 n/a (scylla)
                    #9  0x0000000000d34c9d n/a (scylla)
                    #10 0x0000000000cfea05 n/a (scylla)
                    #11 0x0000000000d00745 n/a (scylla)
                    #12 0x0000000000b6043d n/a (scylla)
                    #13 0x0000000000b60b36 n/a (scylla)
                    #14 0x0000000000d4828d n/a (scylla)
                    #15 0x0000000000d48f0d n/a (scylla)
                    #16 0x0000000000acdbe2 n/a (scylla)
                    #17 0x0000000000ad4b88 n/a (scylla)
                    #18 0x0000000000ad54d3 n/a (scylla)
                    #19 0x0000000000ad69d0 n/a (scylla)
                    #20 0x0000000000ad8d3d n/a (scylla)
                    #21 0x0000000000ad9cab n/a (scylla)
                    #22 0x0000000000ada91e n/a (scylla)
                    #23 0x0000000000adaf0e n/a (scylla)
                    #24 0x0000000000adbb80 n/a (scylla)
                    #25 0x0000000000adbca4 n/a (scylla)
                    #26 0x00000000004d570e n/a (scylla)
                    #27 0x000000000050326b n/a (scylla)
                    #28 0x00000000005205dd n/a (scylla)
                    #29 0x00000000005522de n/a (scylla)
                    #30 0x00007f6a5f3e8dc5 start_thread (libpthread.so.0)
                    #31 0x00007f6a5f11621d __clone (libc.so.6)
                    
                    Stack trace of thread 11380:
                    #0  0x00000000005d40cb n/a (scylla)
                    #1  0x000000000101522d n/a (scylla)
                    #2  0x00000000010a8b9d n/a (scylla)
                    #3  0x00000000010b9085 n/a (scylla)
                    #4  0x00000000010b922b n/a (scylla)
                    #5  0x00000000010008bf n/a (scylla)
                    #6  0x000000000125cbee n/a (scylla)
                    #7  0x000000000125d273 n/a (scylla)
                    #8  0x000000000125d55f n/a (scylla)
                    #9  0x000000000125d6f3 n/a (scylla)
                    #10 0x00000000008fff33 n/a (scylla)
                    #11 0x00000000008f9207 n/a (scylla)
                    #12 0x00000000008f99fb n/a (scylla)
                    #13 0x00000000008fa7d1 n/a (scylla)
                    #14 0x000000000125a709 n/a (scylla)
                    #15 0x000000000125a872 n/a (scylla)
                    #16 0x000000000125aad7 n/a (scylla)
                    #17 0x000000000125173c n/a (scylla)
                    #18 0x00000000012573af n/a (scylla)
                    #19 0x00000000004d570e n/a (scylla)
                    #20 0x000000000050326b n/a (scylla)
                    #21 0x00000000005205dd n/a (scylla)
                    #22 0x00000000005522de n/a (scylla)
                    #23 0x00007f6a5f3e8dc5 start_thread (libpthread.so.0)
                    #24 0x00007f6a5f11621d __clone (libc.so.6)
                    
                    Stack trace of thread 11382:
                    #0  0x00007f6a5f3ef22d read (libpthread.so.0)
                    #1  0x00000000004d5fbe n/a (scylla)
                    #2  0x00000000005522de n/a (scylla)
                    #3  0x00007f6a5f3e8dc5 start_thread (libpthread.so.0)
                    #4  0x00007f6a5f11621d __clone (libc.so.6)
                    
                    Stack trace of thread 11378:
                    #0  0x00000000008f7363 n/a (scylla)
                    #1  0x00000000009046de n/a (scylla)
                    #2  0x00000000007ace08 n/a (scylla)
                    #3  0x000000000081a100 n/a (scylla)
                    #4  0x000000000082414e n/a (scylla)
                    #5  0x00000000008248e7 n/a (scylla)
                    #6  0x00000000004d570e n/a (scylla)
                    #7  0x000000000050326b n/a (scylla)
                    #8  0x000000000057ad05 n/a (scylla)
                    #9  0x0000000000

The coredump can be downloaded using:

    INFO | Node scylla-1-3-rc2-scylla-db-node-2d0f0f18-5 [54.187.159.38 | 172.31.38.120] (seed: None): To download it, you may use 'curl --user-agent [user-agent] scylladb-users-upload.s3.amazonaws.com/core.scylla.994.24b8143161b34f27927f2868d5a4f532.11378.1470297104000000/core.scylla.994.24b8143161b34f27927f2868d5a4f532.11378.1470297104000000.xz > core.scylla.994.24b8143161b34f27927f2868d5a4f532.11378.1470297104000000.xz'

The cassandra-stress cmd used was:

    DEBUG| Remote [centos@54.187.84.151]: Running 'cassandra-stress write cl=QUORUM duration=480m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=1000   -pop seq=1..10000000 -node 172.31.38.122'

Disruption functions executed:

    INFO | sdcm.nemesis.ChaosMonkey: Operation log:
    INFO | sdcm.nemesis.ChaosMonkey: {'duration': 149, 'start': 1470275243, 'operation': 'Drainer Node scylla-1-3-rc2-scylla-db-node-2d0f0f18-3 [54.201.40.197 | 172.31.38.118] (seed: False)', 'end': 1470275392}
    INFO | sdcm.nemesis.ChaosMonkey: {'duration': 4412, 'start': 1470276293, 'operation': 'CorruptThenRebuild Node scylla-1-3-rc2-scylla-db-node-2d0f0f18-4 [54.187.225.24 | 172.31.38.121] (seed: False)', 'end': 1470280705}
    INFO | sdcm.nemesis.ChaosMonkey: {'duration': 144, 'start': 1470281605, 'operation': 'Drainer Node scylla-1-3-rc2-scylla-db-node-2d0f0f18-4 [54.187.225.24 | 172.31.38.121] (seed: False)', 'end': 1470281749}
    INFO | sdcm.nemesis.ChaosMonkey: {'duration': 4303, 'start': 1470282649, 'operation': 'Decommission Node scylla-1-3-rc2-scylla-db-node-2d0f0f18-3 [54.201.112.215 | 172.31.38.118] (seed: False)', 'end': 1470286953}
    INFO | sdcm.nemesis.ChaosMonkey: {'duration': 488, 'start': 1470287853, 'operation': 'StopWaitStartService Node scylla-1-3-rc2-scylla-db-node-2d0f0f18-6 [54.213.247.171 | 172.31.34.19] (seed: False)', 'end': 1470288341}
    INFO | sdcm.nemesis.ChaosMonkey: {'duration': 207, 'start': 1470289241, 'operation': 'Drainer Node scylla-1-3-rc2-scylla-db-node-2d0f0f18-2 [54.186.176.59 | 172.31.38.119] (seed: False)', 'end': 1470289449}
    INFO | sdcm.nemesis.ChaosMonkey: {'duration': 4958, 'start': 1470290349, 'operation': 'Decommission Node scylla-1-3-rc2-scylla-db-node-2d0f0f18-6 [54.213.247.171 | 172.31.34.19] (seed: False)', 'end': 1470295307}
    INFO | sdcm.nemesis.ChaosMonkey: {'duration': 971, 'start': 1470296207, 'operation': 'CorruptThenRepair Node scylla-1-3-rc2-scylla-db-node-2d0f0f18-5 [54.187.159.38 | 172.31.38.120] (seed: False)', 'end': 1470297179}
    INFO | sdcm.nemesis.ChaosMonkey: {'duration': 1079, 'start': 1470298079, 'operation': 'CorruptThenRebuild Node scylla-1-3-rc2-scylla-db-node-2d0f0f18-4 [54.149.178.52 | 172.31.38.121] (seed: False)', 'end': 1470299159}
    INFO | sdcm.nemesis.ChaosMonkey: {'duration': 149, 'start': 1470300059, 'operation': 'Drainer Node scylla-1-3-rc2-scylla-db-node-2d0f0f18-2 [54.191.125.235 | 172.31.38.119] (seed: False)', 'end': 1470300209}
    INFO | sdcm.nemesis.ChaosMonkey: {'duration': 486, 'start': 1470301109, 'operation': 'StopWaitStartService Node scylla-1-3-rc2-scylla-db-node-2d0f0f18-4 [54.149.178.52 | 172.31.38.121] (seed: False)', 'end': 1470301595}

We have full logs available on .tar.bz2 format (21 MB) in case that would be interesting.

**Comment by tgrabiec** [comment]
```
sudo debuginfo-install scylla-server-1.3.rc2-20160729.23c340b.el7.centos.x86_64
Could not find debuginfo for main pkg: scylla-server-1.3.rc2-20160729.23c340b.el7.centos.x86_64
```

**Comment by tgrabiec** [comment]
debuginfo rpm from http://downloads.scylladb.com/rpm/centos/scylladb-1.3/7/x86_64/ matches

**Comment by tgrabiec** [comment]
Looks like a dup of #1537

```
(gdb) bt
#0  0x00007f6a5f0555f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f6a5f056ce8 in __GI_abort () at abort.c:90
#2  0x00007f6a5f04e566 in __assert_fail_base (fmt=0x7f6a5f19e228 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x17a26c1 "!_future && _state && !_task", file=file@entry=0x17c183b "core/future.hh", 
    line=line@entry=1092, 
    function=function@entry=0x17acf00 <promise<io_event>::get_future()::__PRETTY_FUNCTION__> "future<T ...> promise<T>::get_future() [with T = {io_event}]") at assert.c:92
#3  0x00007f6a5f04e612 in __GI___assert_fail (assertion=assertion@entry=0x17a26c1 "!_future && _state && !_task", 
    file=file@entry=0x17c183b "core/future.hh", line=line@entry=1092, 
    function=function@entry=0x17acf00 <promise<io_event>::get_future()::__PRETTY_FUNCTION__> "future<T ...> promise<T>::get_future() [with T = {io_event}]") at assert.c:101
#4  0x0000000000504df2 in promise<io_event>::get_future (this=<optimized out>) at core/future.hh:1092
#5  reactor::<lambda()>::operator() (__closure=<optimized out>) at core/reactor.cc:564
#6  apply_helper<reactor::submit_io(Func) [with Func = posix_file_impl::read_dma(uint64_t, void*, size_t, const io_priority_class&)::<lambda(iocb&)>]::<lambda()>, std::tuple<>&&, std::integer_sequence<long unsigned int> >::apply (args=<optimized out>, 
    func=<optimized out>) at core/apply.hh:34
#7  apply<reactor::submit_io(Func) [with Func = posix_file_impl::read_dma(uint64_t, void*, size_t, const io_priority_class&)::<lambda(iocb&)>]::<lambda()> > (args=<optimized out>, func=<optimized out>) at core/apply.hh:42
#8  futurize<future<io_event> >::apply<reactor::submit_io(Func) [with Func = posix_file_impl::read_dma(uint64_t, void*, size_t, const io_priority_class&)::<lambda(iocb&)>]::<lambda()> > (args=<optimized out>, func=<optimized out>) at core/future.hh:1234
#9  future<>::then<reactor::submit_io(Func) [with Func = posix_file_impl::read_dma(uint64_t, void*, size_t, const io_priority_class&)::<lambda(iocb&)>]::<lambda()>, future<io_event> > (func=<optimized out>, this=0x7f6a5aff8590) at core/future.hh:860
#10 reactor::submit_io<posix_file_impl::read_dma(uint64_t, void*, size_t, const io_priority_class&)::<lambda(iocb&)> > (
    prepare_io=..., this=0x6030000c3000) at core/reactor.cc:565
#11 io_queue::<lambda()>::<lambda()>::operator() (__closure=__closure@entry=0x6030000c3040) at core/reactor.cc:780
#12 fair_queue::<lambda()>::operator() (__closure=<optimized out>) at core/fair_queue.hh:217
#13 apply_helper<fair_queue::queue(priority_class_ptr, unsigned int, Func) [with Func = io_queue::queue_request(shard_id, const io_priority_class&, size_t, Func)::<lambda()> [with Func = posix_file_impl::read_dma(uint64_t, void*, size_t, const io_priority_class&)::<lambda(iocb&)>]::<lambda()>; futurize_t<typename std::result_of<Func()>::type> = future<io_event>; priority_class_ptr = lw_shared_ptr<priority_class>]::<lambda()>, std::tuple<>&&, std::integer_sequence<long unsigned int> >::apply (args=<optimized out>, 
    func=<optimized out>) at core/apply.hh:34
#14 apply<fair_queue::queue(priority_class_ptr, unsigned int, Func) [with Func = io_queue::queue_request(shard_id, const io_priority_class&, size_t, Func)::<lambda()> [with Func = posix_file_impl::read_dma(uint64_t, void*, size_t, const io_priority_class&)::<lambda(iocb&)>]::<lambda()>; futurize_t<typename std::result_of<Func()>::type> = future<io_event>; priority_class_ptr = lw_shared_ptr<priority_class>]::<lambda()> > (args=<optimized out>, func=<optimized out>) at core/apply.hh:42
#15 futurize<future<io_event> >::apply<fair_queue::queue(priority_class_ptr, unsigned int, Func) [with Func = io_queue::queue_reques---Type <return> to continue, or q <return> to quit---
t(shard_id, const io_priority_class&, size_t, Func)::<lambda()> [with Func = posix_file_impl::read_dma(uint64_t, void*, size_t, const io_priority_class&)::<lambda(iocb&)>]::<lambda()>; futurize_t<typename std::result_of<Func()>::type> = future<io_event>; priority_class_ptr = lw_shared_ptr<priority_class>]::<lambda()> >(<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x0, DIE 0x1f03c9>, <unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x0, DIE 0x1f03dc>) (
    func=func@entry=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x0, DIE 0x1f03c9>, args=<optimized out>)
    at core/future.hh:1234
#16 0x000000000051a5dc in future<>::<lambda(auto:1&&)>::operator()<future_state<> > (
    state=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x0, DIE 0x1ff8a3>, __closure=0x60304557f710)
    at core/future.hh:870
#17 continuation<future<T>::then(Func&&) [with Func = fair_queue::queue(priority_class_ptr, unsigned int, Func) [with Func = io_queue::queue_request(shard_id, const io_priority_class&, size_t, Func)::<lambda()> [with Func = posix_file_impl::read_dma(uint64_t, void*, size_t, const io_priority_class&)::<lambda(iocb&)>]::<lambda()>; futurize_t<typename std::result_of<Func()>::type> = future<io_event>; priority_class_ptr = lw_shared_ptr<priority_class>]::<lambda()>; Result = future<io_event>; T = {}]::<lambda(auto:1&&)> >::run(void) (this=0x60304557f700) at core/future.hh:402
#18 0x00000000004d570e in reactor::run_tasks (this=this@entry=0x6030000c3000, tasks=...) at core/reactor.cc:1522
#19 0x000000000050326b in reactor::run (this=0x6030000c3000) at core/reactor.cc:1942
#20 0x00000000005205dd in smp::<lambda()>::operator()(void) const (__closure=0x600000087540) at core/reactor.cc:2810
#21 0x00000000005522de in std::function<void ()>::operator()() const (this=<optimized out>)
    at /opt/scylladb/include/c++/5.3.1/functional:2271
#22 posix_thread::start_routine (arg=<optimized out>) at core/posix.cc:50
#23 0x00007f6a5f3e8dc5 in start_thread (arg=0x7f6a5afff700) at pthread_create.c:308
#24 0x00007f6a5f11621d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

```
