### ISSUE TITLE
scylla_setup ask if to install scylla as a service and ignore the answer on ubuntu

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#1556]
OS: Ubuntu

On ubuntu (both 14 and 16) scylla_setup check if to run scylla as a service, regardless what the answer is, it does nothing.

**Comment by kongove** [comment]
It's a issue report?  or Feature request?

**Comment by amnonh** [comment]
It's an issue report

On Mon, Aug 8, 2016 at 11:07 AM, Amos Jianjun Kong <notifications@github.com

**Comment by syuu1228** [comment]
Fixed on "[PATCH scylla] dist/common/scripts/scylla_setup: support enabling services on Ubuntu 15.10/16.04".
For 14.04, it always enabled, but not automatically starts until next boot.
