### ISSUE TITLE
Memory leak when querying a 5007 rows partition using cqlsh

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#1557]
*Installation details*
Scylla version (or git commit hash): e0a43a82c6906c12cafe8ed94f09a86580693782
Cluster size: 2
OS: Ubuntu

* Descritpion* 
When querying a relatively large partition (5007 rows) with cqlsh scylla leaks memory  quite fast.

* Steps to reproduce the original problem*
The problem was noticed when I was performing unit testing of my Tracing series (see it on a `issue-1557-big-partition-query-memory-leak` branch in a `scylladb/seastar-dev` repo).

My was went as follows:

1. Create a 2 nodes cluster with the ccm:
`ccm create scylla-2 --scylla --vnodes -n 2 --install-dir=<your scylla repo location>`
2. Bring it up:
`ccm start --jvm_arg="--memory" --jvm_arg="1G" --jvm_arg="--collectd-address" --jvm_arg="127.0.0.1:25826" --jvm_arg="--collectd" --jvm_arg="1" --jvm_arg="--smp" --jvm_arg="2" --jvm_arg="--default-log-level" --jvm_arg="info"`
3. Populate it with c-s:
`cassandra-stress write n=1000000 -rate threads=500`
4. Run `SELECT` query using a Node that doesn't own this key as a Coordinator. For me it was 127.0.0.1:
`cqlsh --cqlversion="3.2.1" 127.0.0.1 -e "TRACING ON; select \"C0\", \"C1\" from keyspace1.standard1  where key=0x12345679"' | tee -a out.txt`
Run (4) for 500 times.
5. Stop a cluster, start a cluster and start querying the created sessions:
```
# ccm stop
<At this stage a scylla from a clean master may be used>
# ccm start --jvm_arg="--memory" --jvm_arg="1G" --jvm_arg="--collectd-address" --jvm_arg="127.0.0.1:25826" --jvm_arg="--collectd" --jvm_arg="1" --jvm_arg="--smp" --jvm_arg="2" --jvm_arg="--default-log-level" --jvm_arg="info"
# for f in `grep "Tracing session" out.txt | cut -d":" -f2`; do res=`cqlsh --cqlversion="3.2.1" 127.0.0.1 -e " select * from system_traces.events  where session_id=$f" | grep rows`  ; if [[ "$res" != "(5007 rows)" ]]; then echo "Session $f is NOT ok"; else echo "Session $f is ok"; fi; done | tee out.res.txt
```
At this stage I noticed that a `collectd` `objects-malloc` metrics is constantly and quite rapidly growing on some shards (sometimes on all of them).
For the cluster configuration above running step (5) at most twice was draining the whole memory and nodes start throwing std::bad_alloc and eventually crash with SIGSEG.

**Comment by vladzcloudius** [comment]
Here is a dtest that may help debugging the issue: it reproduces the leak but it has to run for a really long time to reproduce a crash: 
[big_partitions_query.py.txt](https://github.com/scylladb/scylla/files/406626/big_partitions_query.py.txt)

I used the following command to run it:
`pkill -9 scylla; pkill -9 java; rm -Rf ~/.dtest/*; REUSE_CLUSTER=false KEEP_TEST_DIR=true DEBUG=true PRINT_DEBUG=true  nosetests -v -s big_partitions_query.py:TestBigPartition.memory_leak_during_query_test`

**Comment by vladzcloudius** [comment]
A disturbing observation: a master above with a clear data, idle - objects-malloc counter constantly grows (again - the system is IDLE).

Look at memory-1/objects-malloc on both nodes:
![memory-usage-0-master](https://cloud.githubusercontent.com/assets/6103981/17489690/05755dd0-5da8-11e6-819b-ab9e4a9706cd.png)
![memory-usage-1-master](https://cloud.githubusercontent.com/assets/6103981/17489689/05732fa6-5da8-11e6-98ea-c429d4cc9317.png)

**Comment by avikivity** [comment]
Try to paste text, not screenshots.

**Comment by haaawk** [comment]
In my case none of the nodes contain key 0x123456789 is that ok?

**Comment by vladzcloudius** [comment]
On Aug 8, 2016 11:24 PM, "Piotr Jastrzębski" <notifications@github.com>
wrote:
>
> In my case none of the nodes contain key 0x123456789 is that ok?

That's ok

**Comment by slivne** [comment]
I ran the test overnight on branch-1.3 and did not run into a crash

```
Read 5007 rows
Reading b410a4ed-5e6b-4dca-9d89-e4f6e9ef8147 partition
Read 5007 rows
Reading ebe3b1a1-37f7-4e6a-8cac-8731098302d0 partition
Read 5007 rows
ok

----------------------------------------------------------------------
Ran 1 test in 14757.071s

OK
shlomi@localhost~/urchin-dtest (branch-1.3)$ ^C
shlomi@localhost~/urchin-dtest (branch-1.3)$ cd ~/scylla
shlomi@localhost~/scylla (branch-1.3)$ git log -1
commit 8d8e997f5a3c51b7ad7ad0ea39fecfe4175168fb
Author: Avi Kivity <avi@scylladb.com>
Date:   Sun Aug 7 17:51:24 2016 +0300

    Update scylla-ami submodule
    
    * dist/ami/files/scylla-ami 863cc45...2e599a3 (1):
      > Do not set developer-mode on unsupported instance types
shlomi@localhost~/scylla (branch-1.3)$ build/release/scylla -version
error: unrecognised option '-version'

Try --help.
shlomi@localhost~/scylla (branch-1.3)$ build/release/scylla --version
1.3.rc2-20160808.8d8e997
```

@vladzcloudius was it supposed to crash ?

**Comment by vladzcloudius** [comment]
On 08/09/2016 07:03 AM, Shlomi Livne wrote:
>
> I ran the test overnight on branch-1.3 and did not run into a crash
>
> |Read 5007 rows Reading b410a4ed-5e6b-4dca-9d89-e4f6e9ef8147 partition 
> Read 5007 rows Reading ebe3b1a1-37f7-4e6a-8cac-8731098302d0 partition 
> Read 5007 rows ok 
> ---------------------------------------------------------------------- 
> Ran 1 test in 14757.071s OK shlomi@localhost~/urchin-dtest 
> (branch-1.3)$ ^C shlomi@localhost~/urchin-dtest (branch-1.3)$ cd 
> ~/scylla shlomi@localhost~/scylla (branch-1.3)$ git log -1 commit 
> 8d8e997f5a3c51b7ad7ad0ea39fecfe4175168fb Author: Avi Kivity 
> <avi@scylladb.com> Date: Sun Aug 7 17:51:24 2016 +0300 Update 
> scylla-ami submodule * dist/ami/files/scylla-ami 863cc45...2e599a3 
> (1): > Do not set developer-mode on unsupported instance types 
> shlomi@localhost~/scylla (branch-1.3)$ build/release/scylla -version 
> error: unrecognised option '-version' Try --help. 
> shlomi@localhost~/scylla (branch-1.3)$ build/release/scylla --version 
> 1.3.rc2-20160808.8d8e997 |
>
> @vladzcloudius <https://github.com/vladzcloudius> was it supposed to 
> crash ?
>

No. dtest I sent doesn't make it crash - it may only be used for 
demonstration that there is a memory leak (using collectd, just like I 
wrote in the issue).
I was only able to make the system crash with the data set created with 
my branch.
I'll generate a data set and will post it to make it easier to reproduce 
the crash.

**Comment by vladzcloudius** [comment]
Here is a simpler way to reproduce the issue:
Here are the sstables with the system_traces keyspace data (remove the .txt suffix after u download the files):
[system_traces-node1.tgz.txt](https://github.com/scylladb/scylla/files/408573/system_traces-node1.tgz.txt)
[system_traces-node2.tgz.txt](https://github.com/scylladb/scylla/files/408575/system_traces-node2.tgz.txt)

[out.tgz.txt](https://github.com/scylladb/scylla/files/408582/out.tgz.txt)


* How to use *
1) Create 2 nodes cluster: `ccm create scylla-2 --scylla --vnodes -n 2 --install-dir=<your scylla repo location>`
2) Start it with the command: `ccm start --jvm_arg="--memory" --jvm_arg="1G" --jvm_arg="--collectd-address" --jvm_arg="127.0.0.1:25826" --jvm_arg="--collectd" --jvm_arg="1" --jvm_arg="--smp" --jvm_arg="2" --jvm_arg="--default-log-level" --jvm_arg="info"`
3) Stop it: `ccm stop`
4) Copy the sstables above to the corresponding `<ccm cluster directory>/node{1,2}/data/system_trace/events-<UUID>/` and `<ccm cluster directory>/node{1,2}/data/system_trace/sessions-<UUID>/` 
5) Start the cluster with the same command as in (2) above.
6) Untgz the out.tgz.txt file (u'll get the out.txt)
6) Run:
```
for f in `grep "Tracing session" out.txt | cut -d":" -f2`; do res=`cqlsh --cqlversion="3.2.1" 127.0.0.1 -e " select * from system_traces.events  where session_id=$f" | grep rows`  ; if [[ "$res" != "(5007 rows)" ]]; then echo "Session $f is NOT ok"; else echo "Session $f is ok"; fi; done | tee out.res.txt
```
7) Run `scyllatop.py "*node*memory*"` to observe the current level of the memory.

It takes at most 2 executions of (6) to make one of the Nodes to crash.

**Comment by slivne** [comment]
@haaawk does the patch scylladb@f212a6cfcb5f08188760a3fcb24087fbd953efff also fix this ?

**Comment by haaawk** [comment]
I will have to double check but I'm afraid not.

**Comment by slivne** [comment]
split the idle case into another issue #1586
