### ISSUE TITLE
query result digest does not cover tombstones. 

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#156]

**Comment by slivne** [comment]
@gleb-cloudius - did you find a real use case in which this causes a bug (e.g. incorrect results are returned for queries ...)

**Comment by gleb-cloudius** [comment]
Incorrect result - no. But adding this later will cause protocol change between versions, better not do it knowingly.

**Comment by slivne** [comment]
@pdziepak didn't you fix this ?

**Comment by pdziepak** [comment]
Yes, I did. This is the same issue as #182.
