### ISSUE TITLE
consistently fail assert in  cql3::statements::update_statement

### ISSUE THREAD

**Issue by clockfort** [scylladb/scylla#1564]
*Installation details*
Scylla version: 1.3
Cluster size: 1
OS: CentOS

scylla[44298]: scylla: cql3/statements/update_statement.cc:71: virtual void cql3::statements/update_statement.cc:71: virtual void cql3::statements::update_statement::add_update_for_key(mutation&, const exploded_clustering_prefix&, const cql3::update_parameters&): Assertion `_column_operations.empty()' failed.

the CQL that causes this is:
"INSERT INTO keyspace.columnFamily (key1, column1, column2, value) VALUES (?, ?, ?, ?)"
with values bound as 0x000000000000007B, 0x0000000000000002, -457, and 0x000000000000007B , respectively.

the CF looks like:
```
CREATE TABLE keyspace.columnFamily (
    key1 blob,
    column1 blob,
    column2 bigint,
    value blob,
    PRIMARY KEY (key1, column1, column2)
) WITH CLUSTERING ORDER BY (column1 ASC, column2 ASC)
    AND bloom_filter_fp_chance = 0.1
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'LeveledCompactionStrategy'}
    AND compression = {'chunk_length_kb': '4', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 345600
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = 'NONE';
```

the code for this seems to indicate this should not be possible if validation is happening correctly
```
        // An empty name for the value is what we use to recognize the case where there is not column
        // outside the PK, see CreateStatement.
        if (s->regular_begin()->name().empty()) {
            // There is no column outside the PK. So no operation could have passed through validation
            assert(_column_operations.empty());
```

**Comment by duarten** [comment]
This is a duplicate of #1535. The fix will be in the next RC.

**Comment by clockfort** [comment]
So it is! Thanks.
