### ISSUE TITLE
scylltop messes the console up if it is stopped by ctrl-c

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#1565]

**Comment by gleb-cloudius** [comment]
Isn't this a dup of #1417 that suppose to be fixed?

--
			Gleb.

**Comment by slivne** [comment]
@haarcuba did we fix this already ?

**Comment by haarcuba** [comment]
I submitted a patch on another issue that will fix this one too.

**Comment by haarcuba** [comment]
solved by 624165da79935e4244bd56689a55becd93c5db9c

**Comment by asias** [comment]
Is it in 1.3 release?

**Comment by haarcuba** [comment]
no, it's on master
