### ISSUE TITLE
data returned by sstable reader with clustering filter is missing static cells

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1568]
*Installation details*
Scylla version (or git commit hash): (master) d7f8ce77223258507b8a16d21d0deb15643b6f64

Works fine with 1.2.3.

Probably introduced in 700feda0db9aa781635758f5b73487d46a692dab

```
build/release/scylla -c1 --developer-mode=1 -m1G --enable-cache=0
```

Reproducer:
1) populate
```
cqlsh -e "create keyspace ks1 WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 }"
cqlsh -e 'CREATE TABLE ks1.booba2 (pk int, ck text, s1 int static, v int, PRIMARY KEY (pk, ck)) '
cqlsh -e 'insert into ks1.booba2 (pk, s1) values (0, 7);'
python -c "for i in range(2000): print(\"insert into ks1.booba2  (pk, ck, v) values (0, 'ck_%d', %d);\" % (i, i))" | cqlsh

```
2) restart scylla

Expected result (also what we get before restart - data in memtables):
```
cqlsh> select * from ks1.booba2 where pk = 0 and ck = 'ck_45';
 pk | ck    | s1 | v
----+-------+----+----
  0 | ck_45 |  7 | 45

(1 rows)
```

After restart:
```
cqlsh> select * from ks1.booba2 where pk = 0 and ck = 'ck_45';

 pk | ck    | s1   | v
----+-------+------+----
  0 | ck_45 | null | 45

(1 rows)
```

**Comment by raphaelsc** [comment]
Worth adding a dtest for this.

**Comment by nyh** [comment]
When someone does "select * ... where pk = 0 and ck = 'ck45'"  we translate this into an sstable::read_row() call which has the "ck=ck45" filter. This bug report implies that this read_row() must read from disk not only the clustering row ck=ck45, but also the static row in the beginning of the partition. 

Tomek, I have a sacrilegious question: Is this really what we want?

If we do this, how can we ever cache the static row after we read it once from disk? If sstable::read_row() is forced to read again and again this static row every time we need to read more cql rows from the long partition, it's a real waste.

So perhaps sstable::read_row() should not change from the way I wrote it, but rather the caller needs to explicitly specify the static row as part of the filter of what we want to read? For example, this could even be in the form of another clustering key in the filter (the "static clustering key" with its special 0xffff marker and empty components) as another clustering range which we will need to read from disk.
The point is that after we read and cached this static row once, we may never need to ask to read it from disk again - and the next requests will just read from the middle of the partition as they do today.

**Comment by tgrabiec** [comment]
It makes sense to allow reading of the static row to be optional.

We won't be able to utilize this readily, we would have to adapt more than just sstable layer for that. `mutation_source` currently doesn't get enough information to decide if static row can be dropped. We could avoid reading of the static row if clustering restriction is present and no static column is selected.

Perhaps `mutation_source` is better changed to take partition_slice& (instead of only clustering_filter), from which it can deduce if the static row is needed.

Reusing clustering_ranges (and perhaps, empty clustering_key_prefix?) for that wouldn't be backwards compatible. Unless we make sstable layer assign different meaning to clustering_ranges than higher layers, but that could cause confusion, we better avoid it. It would also duplicate information which is already present in partition_slice.

**Comment by nyh** [comment]
I just sent a patch to the mailing list which fixes this bug.

Basically, read_row now has an option (true by default) whether it **also** needs to read static columns. If it notices it needs to read static columns, **and** this partition actually has some, it decides it needs to read two different disk ranges, so because the code does not support that yet, it falls back to the pre-promoted-index code of reading the entire partition.

This is not the most efficient thing we can do, but it correct in all cases, and only non-optimal when static columns are actually used (supposedly it's rare).

Supporting reading multiple non-contiguous chunks of data file is left as a FIXME - but again doesn't hurt correctness.
