### ISSUE TITLE
doc: remove the instructions to upgrade ScyllaDB and update 3rd party and OS packages in one step

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylla#15733]
The procedure is documented, for example:
https://opensource.docs.scylladb.com/stable/upgrade/upgrade-opensource/upgrade-guide-from-4.6-to-5.0/upgrade-guide-from-4.6-to-5.0-image.html#download-and-install-the-new-release
https://opensource.docs.scylladb.com/stable/upgrade/upgrade-opensource/upgrade-guide-from-5.1-to-5.2/upgrade-guide-from-5.1-to-5.2-generic.html#download-and-install-the-new-release (_EC2/GCP/Azure Ubuntu Image_ tab)

The procedure is not supported and must be removed from all versions. Source: https://github.com/scylladb/scylladb/issues/11909
Confirmed by @yaronkaikov and @tzach .

Scope:

**Open Source**
Master and backport to branch-5.2

- [x]  5.1 to 5.2

Master and backport to branch-5.2 and branch-5.1

- [x]  5.0-5.1

- [x]  4.6 - 5.0 

- [x] ScyllaDB 5.x maintenance releases

**Enterprise**
Merge and backport to branch-2023.1
- [x] 2022.x to 2023.1
- [ ] 2022.1 to 2022.2
- [x] 2021.1 to 2022.1
- [x] 2023.x.y to 2023.x.z¶
- [ ] Image 2022.x.y to 2022.x.z

**Comment by yaronkaikov** [comment]
> @yaronkaikov @scylladb/releng How does the user know which OS packages they have to update? The current documentation says: _Upgrading ScyllaDB images requires updating underlying OS packages._ _Starting with ScyllaDB 4.6, each ScyllaDB version includes a list of 3rd party and OS packages tested with the ScyllaDB release._
> 
> Where can the user find the mentioned list?

For example: 
https://s3.amazonaws.com/downloads.scylladb.com/downloads/scylla/relocatable/scylladb-5.2/metadata_x86_64-5.2.9-0.20230920.5709d0043978.txt

and 

https://s3.amazonaws.com/downloads.scylladb.com/downloads/scylla/relocatable/scylladb-5.2/metadata_aarch64-5.2.9-0.20230920.5709d0043978.txt

For both release we have 2 files (one for each arch)
