### ISSUE TITLE
branch-5.1: regenerate frozen toolchain fails at "cargo install cxxbridge-cmd"

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#15809]
To backport for #13803 on branch-5.1, I tried to regenerate frozen toolchain on branch-5.1 but it fails at "cargo install cxxbridge-cmd".
It seems like saying rustc is too old.

```
Collecting scylla-api-client
  Downloading scylla_api_client-1.0-py3-none-any.whl (23 kB)
Requirement already satisfied: requests in /usr/lib/python3.9/site-packages (from scylla-api-client) (2.25.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3.9/site-packages (from requests->scylla-api-client) (1.25.10)
Requirement already satisfied: idna<3,>=2.5 in /usr/lib/python3.9/site-packages (from requests->scylla-api-client) (2.10)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/lib/python3.9/site-packages (from requests->scylla-api-client) (4.0.0)
Installing collected packages: scylla-api-client
Successfully installed scylla-api-client-1.0
    Updating crates.io index
 Downloading crates ...
  Downloaded cxxbridge-cmd v1.0.109
  Installing cxxbridge-cmd v1.0.109
 Downloading crates ...
  Downloaded strsim v0.10.0
  Downloaded unicode-width v0.1.11
  Downloaded clap_builder v4.4.6
  Downloaded clap v4.4.6
  Downloaded codespan-reporting v0.11.1
  Downloaded termcolor v1.3.0
  Downloaded quote v1.0.33
  Downloaded proc-macro2 v1.0.69
  Downloaded unicode-ident v1.0.12
  Downloaded clap_lex v0.5.1
  Downloaded anstyle v1.0.4
  Downloaded syn v2.0.38
error: failed to compile `cxxbridge-cmd v1.0.109`, intermediate artifacts can be found at `/tmp/cargo-installSOWDQ0`

Caused by:
  package `anstyle v1.0.4` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.60.0
Error: building at STEP "RUN dnf -y update     && dnf -y install 'dnf-command(copr)'     && dnf -y install ccache     && dnf -y install devscripts debhelper fakeroot file rpm-build     && ./install-dependencies.sh && dnf clean all     && echo 'ALL ALL=(ALL:ALL) NOPASSWD: ALL' >> /etc/sudoers     && cp system-auth /etc/pam.d     && echo 'Defaults !requiretty' >> /etc/sudoers": while running runtime: exit status 101
```

**Comment by syuu1228** [comment]
@avikivity Any ideas with this?

**Comment by mykaul** [comment]
Isn't Rust for WASM, for UDF, which is still experimental? We probably should have a --skip-udf or something.
That being said, it does seem outdated. We may need to update it regardless.

**Comment by avikivity** [comment]
@wmitros could this be due to the branch not having committed Cargo.lock?

If that's the case, what should the fix be? copy 5.2's Cargo.lock and commit it?

**Comment by wmitros** [comment]
> Isn't Rust for WASM, for UDF, which is still experimental? We probably should have a --skip-udf or something. That being said, it does seem outdated. We may need to update it regardless.

Yes, Rust is mainly for Wasm UDFs, however branch 5.1 actually doesn't have them, it only has the initial patch adding the Rust build subsystem to Scylla (maybe unneccesarily)

> @wmitros could this be due to the branch not having committed Cargo.lock?
> 
> If that's the case, what should the fix be? copy 5.2's Cargo.lock and commit it?

I think if we had a problem with a missing Cargo.lock we would have a similar error message, but in this case we're having a problem with installing the Rust tool `cxxbridge` for generating Rust-C++ bindings, which does not depend on Cargo.lock. Instead we need to specify a version for `cxxbridge` that works with the rustc version that's available in the frozen toolchain of branch-5.1. I just checked that the last version that works for is `1.0.61` and we can use it just by adding `--version 1.0.61` to https://github.com/scylladb/scylladb/blob/387c567125d7d1f17000f434f36be248298df81f/install-dependencies.sh#L317
Should I prepare a patch?

**Comment by avikivity** [comment]
> 
> Should I prepare a patch?


Yes please. I'll have to regenerate the frozen toolchain for it afterwards.

**Comment by wmitros** [comment]
This should have been closed with https://github.com/scylladb/scylladb/pull/15812 but I missed the `fixes` tag
