### ISSUE TITLE
SSTable write is failing sometimes

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1581]
Scylla version (or git commit hash): 1b2ea14d0e73f24cd019d96972628e57f92b8c00
Scylla command line: sudo ./build/release/scylla --datadir /data/scylla_data/data --commitlog-directory /data/scylla_data/commitlog --log-to-stdout 1 --default-log-level info --developer-mode 1 --smp 1 --memory 4000

It's not very easy to reproduce it, but sometimes sstable write fails as follow:
"ERROR 2016-08-13 04:01:35,976 [shard 0] database - failed to write sstable /data/scylla_data2/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-1-Data.db: std::runtime_error (SSTable write failed due to existence of TOC file for generation 1 of system.local)"

That happens to me when booting Scylla. From my understanding, this problem is about Scylla trying to write a new sstable into a column family that wasn't fully populated. So it tries to use generation of a sstable that exists. 

It's also worth mentioning that when this problem happens for the first time, it will always happen at the next boots. So it may be an information from one of column families in system keyspace which triggers this problem.

**Comment by raphaelsc** [comment]
Found a good commit. I am currently doing a bisect.

**Comment by lmr** [comment]
It doesn't seem to be that hard to reproduce, though. I was running a few dtests and I see this fairly frequently.

**Comment by raphaelsc** [comment]
@avikivity: Bisect pointed to https://github.com/scylladb/seastar/commit/79dcb75c9c9010373880812259038840c5b62e87

We were apparently having a problem with properly reading a directory, so Scylla would try to write a new sstable with an existing generation because it wasn't able to find existing sstables and update known generation as a result. Also worth mentioning that user-created keyspace wasn't being loaded. So I decided to patch Seastar as follow:

```
@@ -1070,6 +1079,12 @@ make_file_impl(int fd, file_open_options options) {
         if (flags != -1 && (flags & O_ACCMODE) == O_RDONLY) {
             return make_shared<posix_file_impl>(fd, options);
         }
+        struct stat st;
+        auto ret = ::fstat(fd, &st);
+        if (ret != -1 && S_ISDIR(st.st_mode)) {
+            return make_shared<posix_file_impl>(fd, options);
+        }
+
```

The problem mentioned is apparently fixed after the change above, but reading implementation of append_challenged_posix_file_impl, I cannot understand yet why it cannot work with a directory file. 

append_challenged_posix_file_impl::_completed will apparently only be fulfilled if some of the operations registered in append_challenged_posix_file_impl::opcode is ever called. If working with a directory, append_challenged_posix_file_impl::process_queue() may not be ever called, and as a result, append_challenged_posix_file_impl::_completed will never be fulfilled and append_challenged_posix_file_impl::close() may block indefinitely. I have to confirm my theory.

**Comment by raphaelsc** [comment]
This last theory is actually not true because process_queue() is called by append_challenged_posix_file_impl::close(), which in turn will do _completed.set_value() if may_quit() returns true.

**Comment by lmr** [comment]
I've implemented a couple of persistence tests, see https://github.com/scylladb/scylla-dtest/pull/384, to try to avoid recurring into this issue. Both tests fail on master (my current head is 65aa9135a1c5792aa5211bc531cfacdc79b05abd).

**Comment by raphaelsc** [comment]
@lmr: That's very nice. Thanks for writing this dtest.

**Comment by avikivity** [comment]
@raphaelsc, very strange.  Try strace maybe.

**Comment by raphaelsc** [comment]
@avikivity Indeed. I re-read append_challenged_posix_file_impl so many times, and I wasn't able to find anything wrong with the impl. I'm now thinking that the bug is in the user, i.e. scylla.

**Comment by raphaelsc** [comment]
@avikivity If the bug is indeed in Scylla, it's also strange how your patch (https://github.com/scylladb/seastar/commit/79dcb75c9c9010373880812259038840c5b62e87) would expose it.

**Comment by avikivity** [comment]
@raphaelsc good catch.

**Comment by avikivity** [comment]
oh, there's an "if" there.  Maybe close() is not called?

**Comment by raphaelsc** [comment]
On Tue, Aug 16, 2016 at 4:12 AM, Avi Kivity <notifications@github.com>
wrote:

> oh, there's an "if" there. Maybe close() is not called?
>
Not sure. As I mentioned, problem seems to go away after patching
make_file_impl() to create posix_file_impl if fd refers to a directory
(patch can be found in this thread). That's very strange to me because your
patch 'file: emulate XFS locking' shouldn't affect file when it's a
directory.

**Comment by raphaelsc** [comment]
On Tue, Aug 16, 2016 at 4:22 AM, Raphael Carvalho <raphaelsc@scylladb.com>
wrote:

>
>
> On Tue, Aug 16, 2016 at 4:12 AM, Avi Kivity <notifications@github.com>
> wrote:
>
>> oh, there's an "if" there. Maybe close() is not called?
>>
> Not sure. As I mentioned, problem seems to go away after patching
> make_file_impl() to create posix_file_impl if fd refers to a directory
> (patch can be found in this thread). That's very strange to me because your
> patch 'file: emulate XFS locking' shouldn't affect file when it's a
> directory.
>

BTW, this problem '"ERROR 2016-08-13 04:01:35,976 [shard 0] database -
failed to write sstable
/data/scylla_data2/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-1-Data.db:
std::runtime_error (SSTable write failed due to existence of TOC file for
generation 1 of system.local)"' happens because populate() is not working
properly. Confirmed that using strace which shows that we don't see the
sstables, thus we try to create a new sstable using generation of an
existing one. I fail to understand though how 'file: emulate XFS locking'
could affect file::list_directory() when file refers to a directory.

**Comment by nyh** [comment]
Guys I'm on vacation with a dead laptop so this is the most I can get
involved but just want to point out that I reported already a week ago that
ever single run of sstable-test fails with these errors.  Maybe it's easier
to reproduce *without* xfs (I have.ext4)

**Comment by penberg** [comment]
@tzach The commit Raphael's git bisect points to is not in 1.3.

**Comment by raphaelsc** [comment]
@avikivity 

append_challenged_posix_file_impl:

[pid 30030] open("/data/test_summary/", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 6
[pid 30030] read(5,  <unfinished ...>
[pid 30029] ioctl(6, BLKGETSIZE, 0x17)  = -1 ENOTTY (Inappropriate ioctl for device)
[pid 30029] fcntl(6, F_GETFD)           = 0x1 (flags FD_CLOEXEC)
[pid 30029] ioctl(6, _IOC(_IOC_READ, 0x58, 0x1e, 0x0c), 0x7fe2b3df7f30) = 0
[pid 30029] lseek(6, 0, SEEK_END)       = 4096
[pid 30029] write(5, "\1\0\0\0\0\0\0\0", 8 <unfinished ...>
[pid 30030] <... read resumed> "\1\0\0\0\0\0\0\0", 8) = 8
[pid 30029] <... write resumed> )       = 8
[pid 30030] getdents(6, /* 0 entries */, 8192) = 0

posix_file_impl:

[pid 29351] open("/data/test_summary/", O_RDONLY|O_DIRECTORY|O_CLOEXEC) = 6
[pid 29351] read(5,  <unfinished ...>
[pid 29350] ioctl(6, BLKGETSIZE, NULL)  = -1 ENOTTY (Inappropriate ioctl for device)
[pid 29350] ioctl(6, _IOC(_IOC_READ, 0x58, 0x1e, 0x0c), 0x7f7beeff8000) = 0
[pid 29350] write(5, "\1\0\0\0\0\0\0\0", 8 <unfinished ...>
[pid 29351] <... read resumed> "\1\0\0\0\0\0\0\0", 8) = 8
[pid 29350] <... write resumed> )       = 8
[pid 29351] getdents(6, /* 10 entries */, 8192) = 504

**Comment by raphaelsc** [comment]
@avikivity We call auto r = ::lseek(fd, 0, SEEK_END);
in append_challenged_posix_file_impl's constructor haha
that would make list_directory() always return EOF for directories

**Comment by lmr** [comment]
[seastar-dev] [PATCH] core: Fix bug in make_file_impl() which affects directory scanning fixes this issue.

**Comment by penberg** [comment]
@raphaelsc @avikivity @tzach I moved the issue to 1.4 because AFAICT it only affects master, not branch-1.3.

**Comment by raphaelsc** [comment]
https://github.com/scylladb/scylla/commit/d0308ff4881e29d8ee0d2e34e2aabd2a2e4f28b3 fixed this issue.
