### ISSUE TITLE
incremental backups

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1582]
Hard-links flushed SSTable to a backups directory under the keyspace data directory, allowing storing backups offsite without transferring entire snapshots. 

see correlated C* feature:
https://docs.datastax.com/en/cassandra/2.0/cassandra/operations/ops_backup_incremental_t.html

**Comment by slivne** [comment]
@vladzcloudius don't we support thios already - creating a hard-link for each generated sstable ?

we even have a dtest for this backup_restore_tests.py:TestBackupRestore.incremental_backup_test

**Comment by vladzcloudius** [comment]
@slivne @tzach 
Yes, indeed. We support it  for quite long time already.

**Comment by slivne** [comment]
@tzach can we close this - we do support incremental backup
