### ISSUE TITLE
Scylla AMI wrong behavior when ssh to node

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#1585]
*Installation details* AWS
Scylla version (or git commit hash): ami-09a63a1e - RC2
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos t2.micro

Setup new instance (t2.micro) 
ssh to the instance - expected result is (see picture)
![bug](https://cloud.githubusercontent.com/assets/18263247/17665908/470ce354-6306-11e6-9955-6d1e5018098f.png)

Actual result is that ScyllaDB is active
On instances that we not "officially" supported in our website, initial state need to be down and ready to setup with 

> scylla_io_setup

**Comment by penberg** [comment]
I suppose this is for @syuu1228?

**Comment by syuu1228** [comment]
@penberg I think so, seems ami script bug.

**Comment by syuu1228** [comment]
This ami (ami-09a63a1e) does not included fix commit https://github.com/scylladb/scylla-ami/commit/2e599a3389053b9a41ca1f8fa66871376d3983fd
Since we updated scylla-ami submodule, latest AMI build should work w/o this problem.

**Comment by tzach** [comment]
@nirmaayan can you please test with 1.3 RC3 AMI?

**Comment by nirmaayan** [comment]
Working correctly with ami-45811a52
Checked on t2.micro
