### ISSUE TITLE
Potential memory leak on idle cluster with smp

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1586]
*Installation details*
Scylla version (or git commit hash): branch-1.3 (b2e6a52461a86782b37f106188faee977bb160d4)

Starting a single node with ccm - there is no memory leak

```
 ccm create scylla-1-idle --scylla --vnodes -n 1 --install-dir=
ccm start --jvm_arg="--collectd" --jvm_arg="1" --jvm_arg="--collectd-address" --jvm_arg="127.0.0.1:25826" --jvm_arg="--smp" --jvm_arg="2"
```

![screenshot from 2016-08-15 17-15-40](https://cloud.githubusercontent.com/assets/3465480/17667224/a97d636e-630c-11e6-9bae-1d9ad6c33284.png)
![screenshot from 2016-08-15 17-09-23](https://cloud.githubusercontent.com/assets/3465480/17667225/a98d823a-630c-11e6-97bc-5a7d45258c4b.png)

there is no increase

running a cluster
```
 ccm create scylla-2-idle --scylla --vnodes -n 2 --install-dir=
ccm start --jvm_arg="--collectd" --jvm_arg="1" --jvm_arg="--collectd-address" --jvm_arg="127.0.0.1:25826" --jvm_arg="--smp" --jvm_arg="2"
```

monitoring using 

```
scyllatop.py "*memory*object*"
```

on shard 0 there is almost no increase in allocated objects
on shard 1 there is an increase

after ~6 minutes there is an extra ~1200 objects 

![screenshot from 2016-08-15 15-49-46](https://cloud.githubusercontent.com/assets/3465480/17667163/5d932380-630c-11e6-8d03-b783f5abe5af.png)
![screenshot from 2016-08-15 15-43-18](https://cloud.githubusercontent.com/assets/3465480/17667165/5d9d562a-630c-11e6-8f3f-7dce4c3aa10c.png)

Trying to check if its related to gossiper code applied the following patch

```
shlomi@localhost~/scylla (branch-1.3)$ git diff
diff --git a/gms/gossiper.cc b/gms/gossiper.cc
index d8b18a7..c0bed43 100644
--- a/gms/gossiper.cc
+++ b/gms/gossiper.cc
@@ -723,6 +723,7 @@ int64_t gossiper::get_endpoint_downtime(inet_address ep) {
 //
 // Runs inside seastar::async context
 void gossiper::convict(inet_address endpoint, double phi) {
+    return;
     auto it = endpoint_state_map.find(endpoint);
     if (it == endpoint_state_map.end()) {
         return;
diff --git a/gms/gossiper.hh b/gms/gossiper.hh
index fa43506..33843bc 100644
--- a/gms/gossiper.hh
+++ b/gms/gossiper.hh
@@ -137,7 +137,7 @@ class gossiper : public i_failure_detection_event_listener, public seastar::asyn
         versioned_value::HIBERNATE,
         versioned_value::STATUS_BOOTSTRAPPING,
     };
-    static constexpr std::chrono::milliseconds INTERVAL{1000};
+    static constexpr std::chrono::milliseconds INTERVAL{10000};
     static constexpr std::chrono::hours A_VERY_LONG_TIME{24 * 3};
 
     /** Maximimum difference in generation and version values we are willing to accept about a peer */
shlomi@localhost~/scylla (branch-1.3)$ 
```

the rate changed to ~700 objects on a shard after 28 minutes

![screenshot from 2016-08-15 16-50-53](https://cloud.githubusercontent.com/assets/3465480/17667215/9ee88262-630c-11e6-9c04-fd123dc068f5.png)
![screenshot from 2016-08-15 16-22-06](https://cloud.githubusercontent.com/assets/3465480/17667216/9ee97ce4-630c-11e6-961b-19e607fb3dde.png)

I did try to run debug mode and see if there is any report by ASAN but did not get one.

**Comment by asias** [comment]
Start 2 nodes with the following patch

```
--- a/gms/gossiper.cc
+++ b/gms/gossiper.cc
@@ -536,6 +536,10 @@ void gossiper::do_status_check() {
 // - failure_detector
 // - on_remove callbacks, e.g, storage_service -> access token_metadata
 void gossiper::run() {
+    if (_nr_run > 30) {
+        return;
+    }
+    logger.info("_nr_run={}", _nr_run);
     timer_callback_lock().then([this, g = this->shared_from_this()] {
         return seastar::async([this, g] {
             logger.trace("=== Gossip round START");
```
which disables gossip after 30 gossip round.

After 30 runs of gossip:

we have 

node1/memory-0/objects-malloc 12658
node1/memory-1/objects-malloc  68991 
node2/memory-0/objects-malloc 12633
node2/memory-1/objects-malloc  6999

5 minutes later

node1/memory-0/objects-malloc 12658
node1/memory-1/objects-malloc  6911 
node2/memory-0/objects-malloc 12633
node2/memory-1/objects-malloc  6986

10 minutes later

node1/memory-0/objects-malloc 12658
node1/memory-1/objects-malloc  6911 
node2/memory-0/objects-malloc 12633
node2/memory-1/objects-malloc  6986

**Comment by asias** [comment]
If I apply the 

```
if (_nr_run >= 30) { do_nothing } else { do_something }
```

hack to both gossiper::send_gossip and gossiper::handle_{syn,ack,ack2}_msg, object-malloc does not grow after a while.

Applying the hack only to gossiper::handle_{syn,ack,ack2}_msg, object-malloc still grows after a while.

I suspect we might have memory leak in the ms().send_gossip_digest_syn sending or receiving code. @gleb-cloudius ?

In both cases, the hack is applied to do_status_check 
if (_nr_run < 30) {
do_status_check();
}

**Comment by avikivity** [comment]
Suggestion:

run a configuration that leaks; stop it with gdb, run "scylla memory" in gdb, let it run some more, "scylla memory" again, and compare the results.  That will tell you the size of the objects that leak.  From there you can go to the memory allocator and examine the leaked objects.

**Comment by asias** [comment]
@avikivity thanks, I will try.

**Comment by asias** [comment]
With the following seastar patch, the "leak" is gone. It turns out it is not leaking it is our metric code is wrong. There are unbalanced g_allocs and g_frees.

```
diff --git a/core/memory.cc b/core/memory.cc
index 274cde2..8260ff8 100644
--- a/core/memory.cc
+++ b/core/memory.cc
@@ -562,6 +562,7 @@ bool cpu_pages::drain_cross_cpu_freelist() {
     auto p = xcpu_freelist.exchange(nullptr, std::memory_order_acquire);
     while (p) {
         auto n = p->next;
+        ++g_frees;
         free(p);
         p = n;
     }
@@ -961,7 +962,6 @@ size_t object_size(void* ptr) {
 }

 void* allocate(size_t size) {
-    ++g_allocs;
     if (size <= sizeof(free_object)) {
         size = sizeof(free_object);
     }
@@ -974,11 +974,11 @@ void* allocate(size_t size) {
     if (!ptr) {
         on_allocation_failure(size);
     }
+    ++g_allocs;
     return ptr;
 }

 void* allocate_aligned(size_t align, size_t size) {
-    ++g_allocs;
     size = std::max(size, align);
     if (size <= sizeof(free_object)) {
         size = sizeof(free_object);
@@ -995,6 +995,7 @@ void* allocate_aligned(size_t align, size_t size) {
     if (!ptr) {
         on_allocation_failure(size);
     }
+    ++g_allocs;
     return ptr;
 }
```
