### ISSUE TITLE
Different cluster name prevent node to join the cluster - need to improve journalctl messages

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#1587]
RFE 

journalctl error messages need to be more user friendly 

Based on [Unable to add node to cluster on AWS #1584](https://github.com/scylladb/scylla/issues/1584#issuecomment-239801582)
I tried to add node to cluster, action was failed due to different cluster names /etc/scylla/scylla.yaml
There was no indication for this issue in journalctl 
Not on the single node that I want to add and not on the seed node on the cluster

**Comment by penberg** [comment]
@asias Cassandra has this warning:

```
 WARN 20:04:24,885 ClusterName mismatch from /10.44.2.58 Test !=ClusterA
```

We probably should have the same thing.

**Comment by tzach** [comment]
@asias any update?

**Comment by asias** [comment]
I will send a patch shortly.

**Comment by asias** [comment]
patch sent

 gossip: Add log when cluster or partioner mismatch
