### ISSUE TITLE
Scylla node overload under large load

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#1588]
*Installation details*
Scylla version (or git commit hash):  ami-09a63a1e RC2
Cluster size: 3  i2.8xlarge
Loaders - 14

Working with 3 node cluster on AWS with 14 loaders
After 2-3 hours one of the node fails, total operation drops 
One of the shreds reach very high operation relative to others

Debug it with Avi and we need more tools to understand what is the root cause for the problem.
Waiting for Avi to provide tool for the debug

**Comment by nirmaayan** [comment]
This problem didn't happened on 1.2.x

**Comment by vladzcloudius** [comment]
Sounds like a bisect case... 😉

**Comment by dorlaor** [comment]
Was there a core dump?

**Comment by nirmaayan** [comment]
No coredump

**Comment by tzach** [comment]
@nirmaayan please add reproduce instructions and provide core dump

**Comment by nirmaayan** [comment]
Steps to reproduce using ansible:
https://github.com/scylladb/cassandra-test-and-deploy
Cluster size: 3 i2.8xlarge
Loaders - 14 c4.large
Scylla
> ./ec2-setup-scylla.sh -e "cluster_nodes=3" -e "instance_type=i2.8xlarge" -e "prometheus_client=true"
Loader
> ./ec2-setup-loadgen.sh -e "load_nodes=14" -e "instance_type=c4.large"
Connect nodes to monitor
Run load
> ./ec2-stress.sh 1 -e "server=Scylla" -e "stress_options='-errors ignore -schema \"replication(factor=3)\" keyspace=\"mykeyspace\"'" -e "load_name=scylla_write" -e "threads=2500" -e "command_options='cl=QUORUM n=10000000000 -mode native cql3 -pop seq=1..10000000000'" 
Issue reproduce after 2-3 hours

Not using ansible 
Setup the cluster 
Run cassandra stress 
> cassandra-stress write no-warmup cl=QUORUM n=10000000000 -mode native cql3 -pop seq=1..10000000000 -node 172.30.0.11,172.30.0.8,172.30.0.9 -rate threads=2500 -errors ignore -schema replication(factor=3) keyspace=mykeyspace

**Comment by scottsauff** [comment]
I ran into a 'similar' problem.    I captured a 270 GB core dump that I need to delete in a day or two.  Anyone want anything from it?

**Comment by tzach** [comment]
Thanks
@scottsauff can you upload it to s3?
you can use the following procedure
https://github.com/scylladb/scylla/wiki/How-to-report-a-Scylla-problem#send-the-core-dump

**Comment by avikivity** [comment]
@nirmaayan did the issue reproduce after the first or second cassandra-stress command? was the second command executed on all loader nodes?

**Comment by avikivity** [comment]
We have two queues:

```
 241:   77137753          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  xen-pirq-msi-x     eth0-TxRx-0
 242:       2143   80152412          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  xen-pirq-msi-x     eth0-TxRx-1
 243:         16          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  xen-pirq-msi-x     eth0
```

**Comment by avikivity** [comment]
So cpus 0 and 1 are bound to a nic queue, but cpu 1 is also in use by scylla:

```
top - 09:48:45 up  1:29,  1 user,  load average: 34.60, 34.29, 33.61
Tasks: 594 total,   6 running, 588 sleeping,   0 stopped,   0 zombie
%Cpu0  :  6.2 us,  3.1 sy,  0.0 ni, 76.3 id,  0.0 wa,  0.0 hi, 11.3 si,  3.1 st
%Cpu1  : 71.3 us,  0.7 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi, 28.0 si,  0.0 st
%Cpu2  : 90.5 us,  9.5 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu3  : 99.3 us,  0.7 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu4  : 92.0 us,  8.0 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu5  : 90.0 us,  9.3 sy,  0.0 ni,  0.7 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
%Cpu6  : 97.3 us,  2.7 sy,  0.0 ni,  0.0 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
```

**Comment by avikivity** [comment]
@vladzcloudius looks like rps is not configured

```
$ cat /sys/devices/pci0000:00/0000:00:03.0/net/eth0/queues/rx-1/rps_cpus
00000000,00000000,00000000,00000000
$ cat /sys/devices/pci0000:00/0000:00:03.0/net/eth0/queues/rx-0/rps_cpus
00000000,00000000,00000000,00000000
```

**Comment by avikivity** [comment]
After running `posix-net-conf.sh -sq` on all nodes, softirq work was balanced and the problem with reactor 1 is gone.

**Comment by vladzcloudius** [comment]
On 08/24/2016 12:47 PM, Avi Kivity wrote:
>
> We have two queues:
>
> |241: 77137753 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
> 0 0 0 xen-pirq-msi-x eth0-TxRx-0 242: 2143 80152412 0 0 0 0 0 0 0 0 0 
> 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 xen-pirq-msi-x eth0-TxRx-1 
> 243: 16 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
> xen-pirq-msi-x eth0|

This is a bit strange - did you run posix_net_conf.sh script on this 
instance?

**Comment by vladzcloudius** [comment]
On 08/24/2016 12:50 PM, Avi Kivity wrote:
>
> @vladzcloudius <https://github.com/vladzcloudius> looks like rps is 
> not configured
>
> |$ cat 
> /sys/devices/pci0000:00/0000:00:03.0/net/eth0/queues/rx-1/rps_cpus 
> 00000000,00000000,00000000,00000000 $ cat 
> /sys/devices/pci0000:00/0000:00:03.0/net/eth0/queues/rx-0/rps_cpus 
> 00000000,00000000,00000000,00000000|

Looks like a posix_net_conf.sh wasn't executed here.

**Comment by avikivity** [comment]
@vladzcloudius I did not run anything, it's an AMI and should be preconfigured.

**Comment by vladzcloudius** [comment]
On 08/24/2016 01:07 PM, Avi Kivity wrote:
>
> After running |posix-net-conf.sh -sq| on all nodes, softirq work was 
> balanced and the problem with reactor 1 is gone.
>

And if u run the above script without an -sq parameter? It's supposed to 
deliver the same result.

**Comment by vladzcloudius** [comment]
@avikivity There is a known issue @syuu1228 is working on that API doesn't invoke the above script right if at all...

**Comment by slivne** [comment]
@nirmaayan we have fixed #1406 and the current 1.3.1 candidate ami should resolve this - can you please test this out ami-b63947a1

**Comment by nirmaayan** [comment]
@slivne using the new AMI - ami-b63947a1, Scylla is running over 4 H and there are no crashes
We can either close this issue or run another test
Checking lournalctl for all the nodes

**Comment by slivne** [comment]
thanks @nirmaayan - is the throughput graph better ....

looking at the ticker history it isnot clear to me if you had crashes or
not

**Comment by nirmaayan** [comment]
![1 3_performance](https://cloud.githubusercontent.com/assets/18263247/18713484/229a4fac-801b-11e6-9d92-6874d1e1252f.png)

**Comment by nirmaayan** [comment]
@slivne load is running over 3 hours, closing this issue
