### ISSUE TITLE
sstable column stats collection is inefficient

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#159]
As seen in profiles - we keep constructing temporary vector<bytes> with the column names, then merging them into a temporary column_stats, then merging the temporary column_stats into the table.

A better approach would be:
- keep a vector<bytes_view> in the sstable, containing the column name for the current row.  The vector is not moved, always passed as const.
- merge it just once into min/max, converting it to bytes only then (which should be very rare)

**Comment by raphaelsc** [comment]
@slivne we no longer do this, this can be closed.

**Comment by glommer** [comment]
@slivne raphael claims this can be closed but it is still open ( I have no closing permissions ).

Please close.
