### ISSUE TITLE
massive disk space increase with scylla/xfs vs cassandra/ext4

### ISSUE THREAD

**Issue by scottsauff** [scylladb/scylla#1591]
I'm seeing what appears to be a 6x increase in disk space when loading tables in Scylla/XFS compared to Cassandra on ext4.      In fact,  my 444 GB tables on Cassandra no longer fit on my 2.4 TB RAID 0 volume in Scylla.     Has anyone seen anything like this,  or have any ideas what could contribute to something like this?    In my test,  my tables use RF 3,  on three nodes, so each node holds the complete data set.  

*Installation details*
Scylla version (or git commit hash):scylla.x86_64 1.2.3-20160731.e9b7352.el7.centos
Cluster size: 3 large ram nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI):  centos-release-7-2.1511.el7.centos.2.10.x86_64

**Comment by scottsauff** [comment]
Update -My alarm was based on the load or storage as reported by node tool-status.   In a subsequent test I saw the load change as the result of a failed node - as when tokens from the failed node where being shifted to the remaining nodes.  And those nodes updated their load immediately when detecting the node failure.   

I still cannot account for all the load increase but I see its more likely related to my failure scenario than my shift to scylla and xfs.  :)

**Comment by tzach** [comment]
@scottsauff please close the issue if you are sure its not a scylla problem.
Please note there is a known issue with nodetool status, sometimes returning a wrong load #1592

**Comment by scottsauff** [comment]
Closing issue.   Moving to 1592.
