### ISSUE TITLE
Cannot connect AMI after updated to new kernel by "yum update && reboot"

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#1597]
*Installation details*
Scylla version (or git commit hash): 1.3-rc3
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-45811a52

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory= m4.x2large
Disks: (SSD/HDD, count)

Since we have kernel update from our AMI, "yum update" updates kernel. After reboot or shutdown/restart, I'm not able to connect the instance anymore.
It might be enhanced networking problem, but also there is possibility that new kernel couldn't boot up for some reason, such as bad boot loader settings.

**Comment by kongove** [comment]
You can get 'System Log' from AWS console page.
(right-click instance -> Instance Settings -> Get System Log)

Did you only update the kernel package by `# yum update kernel`? Or updated all fresh packages by `# yum update`?

I reproduced this issue after only updated the kernel package.

- Default kernel:   kernel-3.10.0-327.4.5.el7.x86_64
- Updated kernel: kernel-3.10.0-327.28.2.el7.x86_64

Attached the system log: 
   there are some error "unknown partition table"
[ami-update-kernel-die-system_log.txt](https://github.com/scylladb/scylla/files/424093/ami-update-kernel-die-system_log.txt)

**Comment by syuu1228** [comment]
@kongove When I tried to Get System Log after shutdown/restart, nothing appeared.
On your System Log, it only contains dmesg one time, maybe it doesn't able to logging beyond reboot.

It happens both on "yum update kernel" and "yum update", likely kernel update triggers this.
As you said, kernel-3.10.0-327.4.5.el7.x86_64 -> kernel-3.10.0-327.28.2.el7.x86_64 triggers.

"unknown partition table" comes from extra disks, these are unformatted so may not related with the issue.

**Comment by syuu1228** [comment]
I able to reproduce this on our base AMI image "CentOS7-Base2 (ami-f3102499)", too.
It does not enabled enhanced networking, so this is nothing related with it.
Also, this time I able to get System Log beyond reboot, which means this is not about incorrect boot loader settings, new kernel likely booted up.
https://gist.github.com/syuu1228/5d003e42ccd7a35146a1e800213b58ad

Could be NIC renaming issue? But we passed " net.ifnames=0 biosdevname=0" on grub.

CentOS official image are able to boot beyond kernel update but ours not..
Not sure what's the difference.

Until determine root of this issue, probably we should exclude kernel from yum's update.

**Comment by tzach** [comment]
> Until determine root of this issue, probably we should exclude kernel from yum's update.

@avikivity please advise

**Comment by slivne** [comment]
@syuu1228 can we change the base ami to be newer to resolve this ?

**Comment by syuu1228** [comment]
@slivne There is a script to generate base AMI from scratch (https://github.com/syuu1228/centos7-ami-builder), and it updates kernel to kernel-3.10.0-327.28.2.el7.x86_64 on AMI building time, but it also not able to boot up.

**Comment by syuu1228** [comment]
Sent "[PATCH scylla-ami 2/2] scylla_install_ami: exclude kernel from update" to exclude kernel package from yum update.

**Comment by slivne** [comment]
@syuu1228 what is the kernel version used in the centos official image ? - are we using the same kernel version ?

**Comment by syuu1228** [comment]
I found what is happening by "Get instance screenshot" feature on EC2 console.
(Didn't know the feature, looks like newly added in May)

https://i.gyazo.com/3aebfd0dbee0ce0a7ce1cab754e71dab.png
https://i.gyazo.com/627fa3873fa7f3ea874246178e0c64f2.png

So dracut gives up to boot, showing "Warning: /dev/sda1 does not exist".
Not 100% sure but likely related with #1707.

**Comment by syuu1228** [comment]
I confirmed that this can fix by replacing rootfs entry on /etc/fstab from
```
/dev/sda1 / xfs defaults,noatime 1 1
```
to
```
UUID=<uuid>  / xfs defaults,noatime 1 1
```

And very likely #1707 is duplicated issue of #1597.
Already uploaded new CentOS7 base image, will send a patch to provide new AMI ID for AMI build script.
