### ISSUE TITLE
Regression: scylla-housekeeping script failed for SSL error after switch to python2

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla#1600]
*Installation details*
Scylla version (or git commit hash):
```
ubuntu@ip-10-81-165-156:~$ dpkg -l |grep scylla
ii  scylla                               1.3~rc3-20160814.b2e6a52-ubuntu1 amd64        Scylla database metapackage
ii  scylla-conf                          1.3~rc3-20160814.b2e6a52-ubuntu1 amd64        Scylla database main configuration file
ii  scylla-jmx                           1.3~rc3-20160814.ad895c2-ubuntu1 all          Scylla JMX server binaries
ii  scylla-kernel-conf                   1.3~rc3-20160814.b2e6a52-ubuntu1 amd64        Scylla kernel tuning configuration
ii  scylla-server                        1.3~rc3-20160814.b2e6a52-ubuntu1 amd64        Scylla database server binaries
ii  scylla-tools                         1.3~rc3-20160814.e7494d3-ubuntu1 all          Scylla database tools
```
OS (RHEL/CentOS/Ubuntu/AWS AMI): 
ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20160627 (ami-2d39803a)
instance type: c3.large, not sure if it's a Python issue.

@amnonh @slivne 

Description:
housekeeping script failed to execute in current 1.3-RC, it's broken by switching to python2.
So it's a regression bug.

```
ubuntu@ip-10-81-165-156:~$ /usr/lib/scylla/scylla-housekeeping -q version
Traceback (most recent call last):
  File "/usr/lib/scylla/scylla-housekeeping", line 94, in <module>
    args.func(args)
  File "/usr/lib/scylla/scylla-housekeeping", line 71, in check_version
    latest_version = get_json_from_url(version_url + "?version=" + current_version)["version"]
  File "/usr/lib/scylla/scylla-housekeeping", line 50, in get_json_from_url
    response = urllib2.urlopen(req)
  File "/usr/lib/python2.7/urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>
```

**Comment by slivne** [comment]
@amnonh  ?

**Comment by amnonh** [comment]
Unfortunately ssl python 2.7.6  support is broken on ubuntu 14.

open ssl and simple curl do work.

It's apparently a known issue (move to python3 is an option but that would
break other dependencies)

**Comment by slivne** [comment]
@amnonh

So what do programs that are using python2 running on ubuntu 14.04 and need
ssl do ?

I assume there is a solution ...

**Comment by amnonh** [comment]
On Sun, Aug 21, 2016 at 11:05 PM, Shlomi Livne <notifications@github.com>
wrote:

> @amnonh
>
> So what do programs that are using python2 running on ubuntu 14.04 and need
> ssl do ?
>
> I assume there is a solution ...
>

There are some suggestion to fix the ssl environement, the problem is that
we do not want to run
any installation scripts, that's why we moved to python2 in the first
place, so there will be no need to run all those,
pip command for python packages that are not packaged with deb or rpm.

If I will not find a deb package that can take care of things, I'll use
curl to get the information for 1.3 and we'll reconsider what
to do in 1.4.

**Comment by slivne** [comment]
thanks

run it by @avikivity maybe he has an idea ...
