### ISSUE TITLE
systemd: housekeeping timer isn't reset at each start

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla#1601]
_Installation details_
Scylla version (or git commit hash): 1.3-rc 

```
ubuntu@ip-10-180-2-150:~$ dpkg -l |grep scylla
ii  scylla                                 1.3.0-20160820.b85164b-ubuntu1   amd64        Scylla database metapackage
ii  scylla-conf                            1.3.0-20160820.b85164b-ubuntu1   amd64        Scylla database main configuration file
ii  scylla-jmx                             1.3~rc3-20160814.ad895c2-ubuntu1 all          Scylla JMX server binaries
ii  scylla-kernel-conf                     1.3.0-20160820.b85164b-ubuntu1   amd64        Scylla kernel tuning configuration
ii  scylla-server                          1.3.0-20160820.b85164b-ubuntu1   amd64        Scylla database server binaries
ii  scylla-server-build-deps               1.3.0-20160820.b85164b-ubuntu1   all          build-dependencies for scylla-server
ii  scylla-server-dbg                      1.3.0-20160820.b85164b-ubuntu1   amd64        debugging symbols for scylla-server
ii  scylla-tools                           1.3~rc3-20160814.e7494d3-ubuntu1 all          Scylla database tools
```

OS (RHEL/CentOS/Ubuntu/AWS AMI): ubuntu/images/ebs-ssd/ubuntu-xenial-16.04-amd64-server-20160815 (ami-6f0e9578)

Description:

Current housekeeping timer is set when the timer is started in the first time, because we use 'OnBootSec'. When we restart the scylla-server, the timer will be restarted, but not reset.
So the housekeeping won't be run at each start, it's inconsistent with upstart script in Ubuntu 14.04

Current result: housekeeping timer isn't reset in start stage
Expected result: each restart of scylla-server causes a housekeeping check.

@amnonh

**Comment by kongove** [comment]
Post a patch to fix this issue:

[PATCH scylla for-1.3] systemd: reset housekeeping timer at each start

**Comment by tzach** [comment]
@amnonh can you validate?

**Comment by slivne** [comment]
@amnonh ping

**Comment by tzach** [comment]
query should run on every restart, and then each 24h.

**Comment by kongove** [comment]
On Wed, Aug 31, 2016 at 6:27 PM, Tzach Livyatan <notifications@github.com>
wrote:

> query should run on every restart, and then each 24h.
>

Then the reset is necessary.

**Comment by slivne** [comment]
@amnonh - did you fix this ?

**Comment by amnonh** [comment]
There is a series pending for housekeeping.
I'll change it after the series was merged

**Comment by kongove** [comment]
On Wed, Sep 21, 2016 at 6:30 PM, Amnon Heiman <notifications@github.com>
wrote:

> There is a series pending for housekeeping.

I'll change it after the series was merged
>

The series should be :
[PATCH scylla 1/2] scylla-housekeeping: check version during setup
[PATCH scylla 2/2] scylla_setup: Check and report the scylla version

The series check and report version during setup stage. When it's merged,
we also need to pass mode & version & uuid parameter in checking version
after setup. Then we can distinguish each instance by uuid, it's fine to
check version in start stage.

However, below patch is needed in the end.
[PATCH scylla for-1.3] systemd: reset housekeeping timer at each start

**Comment by slivne** [comment]
@amnonh ping

**Comment by amnonh** [comment]
I believe Amos had a patch for it

**Comment by slivne** [comment]
@kongove can you please resend your patch(s) ...

**Comment by kongove** [comment]
On Thu, Nov 24, 2016 at 7:18 PM, Shlomi Livne <notifications@github.com>
wrote:

> @kongove <https://github.com/kongove> can you please resend your patch(s)
> ...
>
OK.
