### ISSUE TITLE
Compilation error on Debian 8.5

### ISSUE THREAD

**Issue by adeptg** [scylladb/scylla#1602]
_Installation details_
Scylla version (or git commit hash): master (commit e60bb836888d8f485e6470ec5785b1a9a9d0444f)
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 8.5

Hi
I'm trying to build scylla on Debian 8.5. 
gdb - 7.11.1-2~bpo8+1  (from backports)
antlr3 - 3.5.2-5 (from testing. Installation was described in https://github.com/scylladb/scylla/issues/664)
thrift - 0.9.1-ubuntu1 (it was compiled and installed by scylla's build script)
g++ - 4.9.2-2

~/scylla# dist/ubuntu/build_deb.sh --dist
...
[48/400] CXX build/release/streamed_mutation.o
FAILED: g++ -MMD -MT build/release/streamed_mutation.o -MF build/release/streamed_mutation.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I/root/scylla/seastar -I/root/scylla/seastar/fmt -I/root/scylla/seastar/build/release/gen  -march=nehalem -DHAVE_DPDK -I/root/scylla/seastar/build/dpdk/include -march=corei7 -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2 -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof -Ifmt -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DNO_EXCEPTION_INTERCEPT -DHAVE_HWLOC -DHAVE_NUMA  -O2 -I/usr/include/jsoncpp  -Wno-maybe-uninitialized -DHAVE_LIBSYSTEMD=1 -I. -I build/release/gen -I seastar -I seastar/build/release/gen -c -o build/release/streamed_mutation.o streamed_mutation.cc
In file included from mutation.hh:32:0,
                 from streamed_mutation.cc:26:
streamed_mutation.hh: In instantiation of ‘decltype(auto) mutation_fragment::visit(Visitor&&) const [with Visitor = mutation_fragment::key() const::get_key_visitor]’:
streamed_mutation.cc:71:35:   required from here
streamed_mutation.hh:238:43: error: cannot pass objects of non-trivially-copyable type ‘const class static_row’ through ‘...’
             return visitor(as_static_row());
                                           ^
streamed_mutation.hh: In instantiation of ‘decltype(auto) mutation_fragment::visit(Visitor&&) const [with Visitor = mutation_fragment::bound_kind_weight() const::get_bound_kind_weight]’:
streamed_mutation.cc:81:41:   required from here
streamed_mutation.hh:238:43: error: cannot pass objects of non-trivially-copyable type ‘const class static_row’ through ‘...’
In file included from mutation.hh:31:0,
                 from streamed_mutation.cc:26:
utils/optimized_optional.hh: In instantiation of ‘optimized_optional<T>::optimized_optional(const T&) [with T = mutation_fragment]’:
streamed_mutation.cc:357:12:   required from here
utils/optimized_optional.hh:48:51: error: use of deleted function ‘mutation_fragment::mutation_fragment(const mutation_fragment&)’
     optimized_optional(const T& obj) : _object(obj) { }
                                                   ^
In file included from mutation.hh:32:0,
                 from streamed_mutation.cc:26:
streamed_mutation.hh:162:5: note: declared here
     mutation_fragment(const mutation_fragment&) = delete;
     ^
ninja: build stopped: subcommand failed.
debian/rules:4: recipe for target 'override_dh_auto_build' failed
make[1]: **\* [override_dh_auto_build] Error 1
make[1]: Leaving directory '/root/scylla'
debian/rules:19: recipe for target 'binary' failed
make: **\* [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1376:
dpkg-buildpackage -rfakeroot -D -us -uc failed

Please advise if I'm doing something wrong
Thanks in advance!

**Comment by adeptg** [comment]
If I try to build 1.3 branch (commit b85164bc1d949bf31f35a6398facd597dab5be98)

[128/397] CXX build/release/tracing/trace_state.o
FAILED: g++ -MMD -MT build/release/tracing/trace_state.o -MF build/release/tracing/trace_state.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I/root/scylla-1.3-bra/seastar -I/root/scylla-1.3-bra/seastar/fmt -I/root/scylla-1.3-bra/seastar/build/release/gen  -march=nehalem -DHAVE_DPDK -I/root/scylla-1.3-bra/seastar/build/dpdk/include -march=corei7 -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2 -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof -Ifmt -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DHAVE_HWLOC -DHAVE_NUMA  -O2 -I/usr/include/jsoncpp  -Wno-maybe-uninitialized -DHAVE_LIBSYSTEMD=1 -I. -I build/release/gen -I seastar -I seastar/build/release/gen -c -o build/release/tracing/trace_state.o tracing/trace_state.cc
tracing/trace_state.cc: In member function ‘std::unordered_map<basic_sstring<char, unsigned int, 15u>, basic_sstring<char, unsigned int, 15u> > tracing::trace_state::get_params()’:
tracing/trace_state.cc:54:17: error: converting to ‘std::unordered_map<basic_sstring<char, unsigned int, 15u>, basic_sstring<char, unsigned int, 15u> >’ from initializer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_equal&, const allocator_type&) [with _Key = basic_sstring<char, unsigned int, 15u>; _Tp = basic_sstring<char, unsigned int, 15u>; _Hash = std::hash<basic_sstring<char, unsigned int, 15u> >; _Pred = std::equal_to<basic_sstring<char, unsigned int, 15u> >; _Alloc = std::allocator<std::pair<const basic_sstring<char, unsigned int, 15u>, basic_sstring<char, unsigned int, 15u> > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long unsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<basic_sstring<char, unsigned int, 15u> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<basic_sstring<char, unsigned int, 15u> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const basic_sstring<char, unsigned int, 15u>, basic_sstring<char, unsigned int, 15u> > >]’
         return {};
                 ^
ninja: build stopped: subcommand failed.

**Comment by adeptg** [comment]
Thanks for fix! Now I have

[207/397] CXX build/release/mutation_partition.o
FAILED: g++ -MMD -MT build/release/mutation_partition.o -MF build/release/mutation_partition.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I/root/scylla-1.3-bra/seastar -I/root/scylla-1.3-bra/seastar/fmt -I/root/scylla-1.3-bra/seastar/build/release/gen  -march=nehalem -DHAVE_DPDK -I/root/scylla-1.3-bra/seastar/build/dpdk/include -march=corei7 -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2 -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof -Ifmt -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DHAVE_HWLOC -DHAVE_NUMA  -O2 -I/usr/include/jsoncpp  -Wno-maybe-uninitialized -DHAVE_LIBSYSTEMD=1 -I. -I build/release/gen -I seastar -I seastar/build/release/gen -c -o build/release/mutation_partition.o mutation_partition.cc
mutation_partition.cc: In member function ‘data_query_result query_result_builder::consume_end_of_stream()’:
mutation_partition.cc:1789:40: error: could not convert ‘{((query_result_builder*)this)->query_result_builder::_live_rows, ((query_result_builder*)this)->query_result_builder::_partitions}’ from ‘<brace-enclosed initializer list>’ to ‘data_query_result’
         return {_live_rows, _partitions};
                                        ^
mutation_partition.cc:1790:5: error: control reaches end of non-void function [-Werror=return-type]
     }
     ^
cc1plus: all warnings being treated as errors

**Comment by adeptg** [comment]
Any advice how to run it on Debian Stable will be very welcome (use clang, different gcc flags or something else). Thanks

**Comment by avikivity** [comment]
It's the same error.  Try changing

    {_live_rows, _partitions}

to 

    data_query_result{_live_rows, _partitions}

.

**Comment by syuu1228** [comment]
We also have problem to compile Seastar on Debian 8 https://github.com/scylladb/seastar/issues/171
Both problems are caused because we don't have g++-5 on Debian 8.

**Comment by avikivity** [comment]
Debian is now supported (g++5 required).
