### ISSUE TITLE
Estimation of pending compaction for leveled strategy is broken

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1603]
When asking for estimation, API return as follow: {"message": "Invalid level", "code": 500}

**Comment by tzach** [comment]
@raphaelsc @amnonh which nodetool command is affected?

**Comment by raphaelsc** [comment]
@tzach 'compactionstats'

**Comment by tzach** [comment]
@raphaelsc @amnonh which nodetool command is affected?

**Comment by raphaelsc** [comment]
On Thu, Sep 22, 2016 at 11:28 AM, Tzach Livyatan <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> @amnonh
> <https://github.com/amnonh> which nodetool command is affected?
>
@tzach nodetool compactionstats

**Comment by dorlaor** [comment]
If it's in 1.3.2 (it is), it should be reported in this issue too
