### ISSUE TITLE
Does JMX can collect real cpu metric ?

### ISSUE THREAD

**Issue by dong8801** [scylladb/scylla#1604]
_Installation details_
Scylla version (or git commit hash): all
Cluster size: all
OS (RHEL/CentOS/Ubuntu/AWS AMI): all
- Please add real CPU metric(not 100%) to JMX !!
  It will really be helpful to everyone.

**Comment by tzach** [comment]
@dong8801 Scylla do expose real load on each core with `reactor-*/gauge-load` metric.
You can view it using `scyllatop` or any monitoring server which support collectd format metrics, for example https://github.com/scylladb/scylla-grafana-monitoring.
Does this satisfy you needs?

**Comment by dorlaor** [comment]
@tzach, the user is right, we should have some representation of the load
in our api which is simpler than collectd.

**Comment by tzach** [comment]
Scylla now uses [node_exporter](https://github.com/prometheus/node_exporter) to report OS level metrics like CPU, Disk etc
More here: https://docs.scylladb.com/operating-scylla/monitoring/monitoring_stack/
@dong8801 please reopen if you have a followup question.
