### ISSUE TITLE
Possible bug with a range that has exclusive equal bounds

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1606]
@avikivity, @pdziepak, @tgrabiec: I realized that range<> will treat a range like (3, 3) as wrap around, thus will unwrap it into (-inf, 3) and (3, +inf) before doing any further comparison. 

Ranges (3, 3) and [4, 5] are currently overlapping because of that. Is this expected?
In documentation, we say the following: "Range is a wrap around if end value is smaller than the start value or they're equal and at least one bound is not inclusive." Do we really want to consider a range wrap around when start and end bounds are equal and exclusive?

**Comment by pdziepak** [comment]
As wrap around ranges go (3, 3) is a way of expressing "everything except 3", so the results you are getting are correct.

Obviously, we've gotten ourselves into quite a mess regarding wrap around ranges. I guess the best course of action would be to use wrap around ranges in as few places as possible and switch to non-wrapping ranges, which behaviour is much more intuitive, everywhere else. b1f9688432bff78ccbffe1ad02d8a9f0812b46a2 is the first step in achieving that.
