### ISSUE TITLE
partition_slice_clustering_key_filter_factory::get_ranges() is unsafe to use

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#1614]
`partition_slice_clustering_key_filter_factory::get_ranges()` returns a constant reference to a range. If it is used for reversed queries that range is stored inside the filter factory object and is generated by `get_ranges()` itself.

Piotr has noticed that it is a problem since filter factory is shared among multiple mutation readers (which continuations may be interleaved) and each one may cause `get_ranges()` do generate different range thus corrupting ranges used by the other reads.

**Comment by pdziepak** [comment]
I've assigned this bug to Piotr since he has already send a series that solves this problem.

**Comment by slivne** [comment]
is this relevant for 1.3 ?

**Comment by haaawk** [comment]
Yes.
