### ISSUE TITLE
Virtual size_estimates system table

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#1616]
_Installation details_
Scylla version (or git commit hash): 1.3

We write the `size_estimates` system table for every schema on a periodic basis, currently set to 5 minutes. This system table can be queried directly or through the Thrift `describe_splits` and `describe_splits_ex` verbs.

The Spark connector queries the system table directly, while TitanDB and Presto call the Thrift verb. 

Spark [seems](https://github.com/datastax/spark-cassandra-connector/blob/831c098974fb62989f101f254cee63a2ffb1e4f5/spark-cassandra-connector/src/main/scala/com/datastax/spark/connector/rdd/CassandraTableScanRDD.scala#L224) to fetch the size estimates when it scans a table, doing just one query for the whole set of ranges, while Presto [calls](https://github.com/prestodb/presto/blob/a1fdcc70be8a90ca64e4beb2a6717ff931b7b331/presto-cassandra/src/main/java/com/facebook/presto/cassandra/CassandraTokenSplitManager.java#L72) the `describe_splits_ex` verb for every range (the number of vnodes).

The Presto use case is particularly bad since we have to load all the size estimates for a column family only to return the estimate for a single range. 

This system table is thus a good candidate to be virtualized: we can intercept queries to it and calculate the results on the fly, only for the ranges the caller is interested in.

**Comment by slivne** [comment]
@duarten can we close this

**Comment by duarten** [comment]
@slivne Not yet, the patch still hasn't been reviewed and committed.
