### ISSUE TITLE
Support Google Cloud Engine snitch

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1619]
Support GCE snitch, like the existing EC2 snitch. 
Similar to Apache Cassandra `GoogleCloudSnitch`

**Comment by Tigraine** [comment]
Is this already available? I've installed 2.0 on my GCE instance now but the scylladb.yml doesn't reference a GoogleCloudSnitch

**Comment by manigandham** [comment]
Not yet, it would be linked to this issue or already closed.

You can see all the current snitches here: https://github.com/scylladb/scylla/tree/master/locator

**Comment by Tigraine** [comment]
Yeah I checked the locators, but it could have been in some feature branch I wasn't seeing.
