### ISSUE TITLE
add: improve documentation for Service Levels

### ISSUE THREAD

**Issue by annastuchlik** [scylladb/scylla#16231]
The information about service levels is scattered across the docs. 
We need a proper page describing the service levers concept, and ensure the information is added to the CQL reference section.

Related: https://github.com/scylladb/scylladb/pull/14431

**Comment by tzach** [comment]
Very true. There are at least two issues that make it hard to understand:
- We are using ["Workload Prioritization"](https://enterprise.docs.scylladb.com/stable/using-scylla/workload-prioritization.html) to describe an Enterprise-only feature, while the CQL commands are using "SERVICE_LEVEL"
- SERVICE_LEVEL is used both in Enterprise (for workload prio) and in Open Source, both for internal scheduling and for [Specifying Service Level Timeout](https://opensource.docs.scylladb.com/stable/using-scylla/workload-attributes.html)
