### ISSUE TITLE
Scylla docker README: --overprovisioned ENABLE or --overprovisioned ENABLE 1?

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1624]
*Installation details*

OS (RHEL/CentOS/Ubuntu/AWS AMI): Scylla Docker 1.3

From https://hub.docker.com/r/scylladb/scylla/ :

--overprovisioned ENABLE
The --overprovisioned command line option enables or disables optimizations for running Scylla in an overprovisioned environment. If no --overprovisioned option is specified, Scylla defaults to running with optimizations disabled.

For example, to enable optimizations for running in an overprovisioned environment:
```
$ docker run --name some-scylla -d scylladb/scylla --overprovisioned 1
```

Not clear which is it `1` or `ENABLE`

**Comment by penberg** [comment]
How is it not clear from the example?

**Comment by penberg** [comment]
@tzach ping! Any suggestions how to improve it?

**Comment by kongove** [comment]
'ENABLE' is a description for parameter type or content, not real
parameter, it's acceptable.

The 'issue' also exists for developer-mode:
    --developer-mode ENABLE

**Comment by tzach** [comment]
> 'ENABLE' is a description for parameter type or content, not real
parameter, it's acceptable.

Exactly, I found it confusing. Am I'm the only one?

**Comment by penberg** [comment]
@tzach Well, it doesn't confuse *me* :-)

@kongove seems to get it. What do other people think?

**Comment by penberg** [comment]
@tzach Please suggest better wording for the help text or close this issue :wink:

**Comment by tzach** [comment]
Simply using **enable** in all places, not converting it to binary.
If you want to reduce keystrokes, which do make sense, have the doc like
### --overprovisioned 1 (ENABLE)

I was under the impression the header is the actual syntax I should use.

**Comment by avikivity** [comment]
`--param PLACEHOLDER` is pretty standard.

**Comment by penberg** [comment]
@tzach If that `ENABLE` part is confusing, perhaps we should change it to something like`--overprovisioned BOOL`, and also accept `true` and `false` in addition to `1` and `0`...
