### ISSUE TITLE
Reduce collectd strings to 64byte

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#1625]
Collectd doesn't like it and complains load:

Aug 27 19:31:49 hostname collectd[51059]: network plugin: parse_part_string: Buffer too small: Output buffer holds 64 bytes, which is too small to hold the received 66 byte string.

**Comment by penberg** [comment]
For @elcallio perhaps?

**Comment by slivne** [comment]
this are all metrics @vladcloudius added and scylla generates them on the
fly.

**Comment by slivne** [comment]
its also a duplicate #1576
