### ISSUE TITLE
not support update if exists

### ISSUE THREAD

**Issue by slayercat** [scylladb/scylla#1628]
_Installation details_
Scylla version (or git commit hash):  v1.2.3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS Linux release 7.2.1511 (Core) 

Not support update if exists:
https://docs.datastax.com/en/cql/3.1/cql/cql_reference/update_r.html

say i have a table:

```
cqlsh> create table test.a(id uuid primary key, fuck int);
```

```
cqlsh> update test.a set fuck = 1 where id=uuid() if exists;
SyntaxException: <ErrorMessage code=2000 [Syntax error in CQL query] message="line 1:51 no viable alternative at input ';'">

```

**Comment by dorlaor** [comment]
IIUC it requires LWT which we don't yet support. We have an open issue
for it and it's planned for later on this year

**Comment by penberg** [comment]
Indeed, that's LWT at work, and we don't support it yet https://github.com/scylladb/scylla/issues/1359

**Comment by tzach** [comment]
@avnerbarr As mentioned above, IF EXISTS is the API for LWT #1359 which is not available yet. The issue is close since it is duplicate, not solved
