### ISSUE TITLE
Dropping index with in-flight view-updates results in write errors due to no_such_column_family errors in the logs

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#16288]
## Issue description

Dropping an index while there is an active write workload results in in-flight writes for the index failing with:
```
2023-11-30T02:45:54.927+00:00 longevity-10gb-3h-5-4-db-node-eastus-1  !WARNING | scylla[13843]:  [shard 4:stat] storage_proxy - Failed to apply mutation from 10.0.0.7#4: data_dictionary::no_such_column_family (Can't find a column family with UUID 12890cb1-8f19-11ee-b5b7-27ca175ba923)  
```

This goes on until the list of updates is drained. The errors are harmless, but they spam the log, possibly hiding other issues and generally not being helpful.
I think this error should be ignored. Although I'm not sure we can just ignore `no_such_column_family` in general, as it can hide genuine schema sync issues.

## Impact

The impact is log-spam with errors that are not interesting and are inconsequential.

## Installation details

Kernel Version: 5.15.0-1052-azure
Scylla version (or git commit hash): `5.4.0~rc3-20231129.b956646ba231` with build-id `ad7bce928b6e89f2ab6ffc2f9bbb9b985b711595`

Cluster size: 6 nodes (Standard_L8s_v3)

Scylla Nodes used in this run:
- longevity-10gb-3h-5-4-db-node-a3d54a30-eastus-7 (20.232.111.243 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-5-4-db-node-a3d54a30-eastus-6 (20.232.13.103 | 10.0.0.10) (shards: 7)
- longevity-10gb-3h-5-4-db-node-a3d54a30-eastus-5 (20.232.13.102 | 10.0.0.9) (shards: 7)
- longevity-10gb-3h-5-4-db-node-a3d54a30-eastus-4 (172.191.71.249 | 10.0.0.8) (shards: 7)
- longevity-10gb-3h-5-4-db-node-a3d54a30-eastus-3 (172.191.71.138 | 10.0.0.7) (shards: 7)
- longevity-10gb-3h-5-4-db-node-a3d54a30-eastus-2 (172.191.71.121 | 10.0.0.6) (shards: 7)
- longevity-10gb-3h-5-4-db-node-a3d54a30-eastus-1 (172.191.69.37 | 10.0.0.5) (shards: 7)

OS / Image: `/subscriptions/6c268694-47ab-43ab-b306-3c5514bc4112/resourceGroups/scylla-images/providers/Microsoft.Compute/images/scylla-5.4.0-rc3-x86_64-2023-11-29T23-46-22` (azure: undefined_region)

Test: `longevity-10gb-3h-azure-test`
Test id: `a3d54a30-8d10-4bf6-a703-69f14e72d5fa`
Test name: `scylla-5.4/longevity/longevity-10gb-3h-azure-test`
Test config file(s):

- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/cb4ee2f882eacd2c5933620963715949147cc490/test-cases/longevity/longevity-10gb-3h.yaml)

<details>
<summary>
Logs and commands
</summary>

- Restore Monitor Stack command: `$ hydra investigate show-monitor a3d54a30-8d10-4bf6-a703-69f14e72d5fa`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a3d54a30-8d10-4bf6-a703-69f14e72d5fa)
- Show all stored logs command: `$ hydra investigate show-logs a3d54a30-8d10-4bf6-a703-69f14e72d5fa`

## Logs:
- **db-cluster-a3d54a30.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a3d54a30-8d10-4bf6-a703-69f14e72d5fa/20231130_030426/db-cluster-a3d54a30.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a3d54a30-8d10-4bf6-a703-69f14e72d5fa/20231130_030426/db-cluster-a3d54a30.tar.gz)
- **sct-runner-events-a3d54a30.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a3d54a30-8d10-4bf6-a703-69f14e72d5fa/20231130_030426/sct-runner-events-a3d54a30.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a3d54a30-8d10-4bf6-a703-69f14e72d5fa/20231130_030426/sct-runner-events-a3d54a30.tar.gz)
- **sct-a3d54a30.log.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a3d54a30-8d10-4bf6-a703-69f14e72d5fa/20231130_030426/sct-a3d54a30.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a3d54a30-8d10-4bf6-a703-69f14e72d5fa/20231130_030426/sct-a3d54a30.log.tar.gz)
- **loader-set-a3d54a30.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a3d54a30-8d10-4bf6-a703-69f14e72d5fa/20231130_030426/loader-set-a3d54a30.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a3d54a30-8d10-4bf6-a703-69f14e72d5fa/20231130_030426/loader-set-a3d54a30.tar.gz)
- **monitor-set-a3d54a30.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a3d54a30-8d10-4bf6-a703-69f14e72d5fa/20231130_030426/monitor-set-a3d54a30.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a3d54a30-8d10-4bf6-a703-69f14e72d5fa/20231130_030426/monitor-set-a3d54a30.tar.gz)
- **parallel-timelines-report-a3d54a30.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/a3d54a30-8d10-4bf6-a703-69f14e72d5fa/20231130_030426/parallel-timelines-report-a3d54a30.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/a3d54a30-8d10-4bf6-a703-69f14e72d5fa/20231130_030426/parallel-timelines-report-a3d54a30.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-5.4/job/longevity/job/longevity-10gb-3h-azure-test/5/)
[Argus](https://argus.scylladb.com/test/0bd5730c-83ac-4583-814a-835ea87a9e01/runs?additionalRuns[]=a3d54a30-8d10-4bf6-a703-69f14e72d5fa)
</details>

**Comment by denesb** [comment]
@nyh I'm almost certain this is a dup, but I couldn't find any open issues.

**Comment by mykaul** [comment]
https://github.com/scylladb/scylladb/issues/12977 ?

**Comment by denesb** [comment]
> #12977 ?

Yes, closing as duplicate.
