### ISSUE TITLE
Stale results from nodetool status if the node shut itself down due to error

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1629]
_Installation details_
Scylla version (or git commit hash): 1.3

If a node shuts itself down due to I/O error (such as ENOSPC), then `nodetool status` will show the cluster status at the time the shutdown occured.

We should change the status of other nodes to "unknown" when we start up, and when we shut down gossip, so we don't provide stale information.

**Comment by slivne** [comment]
need to test for drain as well

**Comment by slivne** [comment]
@asias ping

**Comment by asias** [comment]
During start up we learn other node's status from the cluster. There is no need to change the status. 
During shutdown, the gossip service will be closed. We should warn the API which tries to query the gossip info that the data is not latest info. Btw, user can stop the gossip service with nodetool and have the cluster still running for some reason, at least Cassandra have this kind of option for user.  In this case, if we change node status while shutdown gossip service, the node will be surprised. 

How about this:
$ nodetool -h node_with_gossip_down status
WARN: gossip is down on this node, status information may be not correct. 

Also, introducing new status, we need to educate user what the new status is.

UN, N = Normal

UJ, J = Joining

UU, U = Unknow?

**Comment by slivne** [comment]
In my view it would be better if the node shows only what it is sure about
- since it is not connected to the cluster it has no idea:
- if nodes are down or up
- if the topology changed all together - there is a new node / new dc / dc
removed / nodes removed


is there any reason not to return only the node information and not provide
any info on any other node.

**Comment by slivne** [comment]
lets check what cassandra does - maybe they have a good idea ....

**Comment by kthommandra** [comment]
Often the deploy scripts (eg: ansible scripts) rely on nodetool status and port checks to check if the server came up properly. If the gossip didn't come up and nodetool status shows that everything is fine then isn't that a problem that went unnoticed.

**Comment by asias** [comment]
I tried
```
--- a/service/storage_service.cc
+++ b/service/storage_service.cc
@@ -1728,6 +1728,7 @@ future<sstring> storage_service::get_operation_mode() {
 future<bool> storage_service::is_starting() {
     return run_with_no_api_lock([] (storage_service& ss) {
         auto mode = ss._operation_mode;
+        ss.isolate_on_error();
         return mode == storage_service::mode::STARTING;
     });
 }
```

And used

```
curl -X GET --header "Accept: application/json" "http://127.0.0.1:10000/storage_service/is_starting";echo
```

to emulate io error caused node self shutdown.

From 127.0.0.1's perspective, it is still in UN status by nodetool status.
```
nodetool status
Datacenter: dc100
=================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns    Host ID                               Rack
UN  127.0.0.1  2.56 GB    32           ?       6161f193-f4bc-4d6b-9a4d-fe7ce18c0f57  rack1
Datacenter: dc200
=================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns    Host ID                               Rack
UN  127.0.0.2  2.26 GB    32           ?       97b28599-de38-4987-95b8-6b442f6e8ffb  rack1
UN  127.0.0.3  1.46 GB    32           ?       50e384e8-39ca-4e93-bdb3-2954d45c1a45  rack1
```

From other nodes' perspective node 127.0.0.1 is down:
```
$ nodetool -p 7200 status
Datacenter: dc100
=================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns    Host ID                               Rack
DN  127.0.0.1  2.56 GB    32           ?       6161f193-f4bc-4d6b-9a4d-fe7ce18c0f57  rack1
Datacenter: dc200
=================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns    Host ID                               Rack
UN  127.0.0.2  2.26 GB    32           ?       97b28599-de38-4987-95b8-6b442f6e8ffb  rack1
UN  127.0.0.3  1.46 GB    32           ?       50e384e8-39ca-4e93-bdb3-2954d45c1a45  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

Checking the gossip status:
```
$ nodetool gossipinfo
/127.0.0.3
  generation:1496965926
  heartbeat:34
  NET_VERSION:0
  HOST_ID:50e384e8-39ca-4e93-bdb3-2954d45c1a45
  X1:RANGE_TOMBSTONES,LARGE_PARTITIONS
  RACK:rack1
  RELEASE_VERSION:2.2.8
  DC:dc200
  LOAD:1.56723e+09
  STATUS:NORMAL,9190394914669086532
  SCHEMA:fa4041dd-e4d6-3d16-b72c-63775798b774
  INTERNAL_IP:127.0.0.3
  RPC_ADDRESS:127.0.0.3
/127.0.0.2
  generation:1496965922
  heartbeat:38
  NET_VERSION:0
  HOST_ID:97b28599-de38-4987-95b8-6b442f6e8ffb
  X1:RANGE_TOMBSTONES,LARGE_PARTITIONS
  RACK:rack1
  RELEASE_VERSION:2.2.8
  DC:dc200
  LOAD:2.43e+09
  STATUS:NORMAL,6105432295336637055
  SCHEMA:fa4041dd-e4d6-3d16-b72c-63775798b774
  INTERNAL_IP:127.0.0.2
  RPC_ADDRESS:127.0.0.2
/127.0.0.1
  generation:1496965919
  heartbeat:44
  NET_VERSION:0
  HOST_ID:6161f193-f4bc-4d6b-9a4d-fe7ce18c0f57
  X1:RANGE_TOMBSTONES,LARGE_PARTITIONS
  RACK:rack1
  RELEASE_VERSION:2.2.8
  DC:dc100
  LOAD:2.74621e+09
  STATUS:shutdown,true
  SCHEMA:fa4041dd-e4d6-3d16-b72c-63775798b774
  INTERNAL_IP:127.0.0.1
  RPC_ADDRESS:127.0.0.
```

Node is in shutdown status. 

So, it is the nodetool's problem. It should interpret shutdown status as a DN status and UN when node 127.0.0.1 run nodetool status against itself.  Note other nodes will see node 127.0.0.1 as DN correctly because node 127.0.0.1 stopped gossip update.

@amnonh Can you take a look at the nodetool status code?

**Comment by asias** [comment]
@amnonh ping

**Comment by amnonh** [comment]
On Fri, Jun 9, 2017 at 3:02 AM, Asias He <notifications@github.com> wrote:

> I tried
>
> --- a/service/storage_service.cc
> +++ b/service/storage_service.cc
> @@ -1728,6 +1728,7 @@ future<sstring> storage_service::get_operation_mode() {
>  future<bool> storage_service::is_starting() {
>      return run_with_no_api_lock([] (storage_service& ss) {
>          auto mode = ss._operation_mode;
> +        ss.isolate_on_error();
>          return mode == storage_service::mode::STARTING;
>      });
>  }
>
> And used
>
> curl -X GET --header "Accept: application/json" "http://127.0.0.1:10000/storage_service/is_starting";echo
>
> you should check:
curl -X GET --header "Accept: application/json" "http://127.0.0.1:10000
<http://127.0.0.1:10000/storage_service/is_starting>/gossiper/endpoint/live"
To see what the API think about the nodes.


to emulate io error caused node self shutdown.

**Comment by asias** [comment]
Patch is on list.

**Comment by nirmaayan** [comment]
@asias ping
