### ISSUE TITLE
Export latency metrics

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1630]
Expose existing latency metrics via collectd/promoters interface

**Comment by dorlaor** [comment]
Please be more specific - how do you measure latency? Would that be similar to cfstat and histograms?

**Comment by tzach** [comment]
Apache Cassandra latency metrics are a good start
```
org.apache.cassandra.metrics.ClientRequest.Read.Latency
org.apache.cassandra.metrics.ClientRequest.Write.Latency
org.apache.cassandra.metrics.ClientRequest.RangeSlice.Latency

org.apache.cassandra.metrics.ColumnFamily.system.batchlog.ReadLatency
org.apache.cassandra.metrics.ColumnFamily.system.batchlog.CoordinatorReadLatency
org.apache.cassandra.metrics.ColumnFamily.system.batchlog.CoordinatorScanLatency
```

```
 org.apache.cassandra.metrics:type=(ColumnFamily|IndexColumnFamily),keyspace=(Keyspace name),scope=(ColumnFamily Name),name=(Metric name) 

ReadLatency : Read latency statistics.
ReadTotalLatency : Total latency in micro seconds for reads.
WriteLatency : Write latency statistics.
WriteTotalLatency : Total latency in micro seconds for writes.
```

https://wiki.apache.org/cassandra/Metrics

**Comment by tzach** [comment]
@slivne is this part of 1.7? (I guess not)

**Comment by tzach** [comment]
@slivne ping

**Comment by slivne** [comment]
it will be part of 1.8 292c08f598e9ae9d49d95f034a5d8ce195ff1e41

**Comment by glommer** [comment]
That's a start, but please note that the latencies from the CF perspective are notoriously wrong - specially for writes, as they do not include throttling time or anything else that happens before the request is sent to the database layer.

We would be missing 3 throttling points, plus any other overhead. It's also per-CF - which is inconvenient for display.

Moreover, I worry about the sheer overhead of a per-CF metric bundle in a case where we have 10k CFs.

I am sorry I haven't seen this before - but I think the commit we have in 1.8 is really not the right way to do it.

**Comment by glommer** [comment]
@avikivity @amnonh @slivne @dorlaor

**Comment by dorlaor** [comment]
At least let's start with an accurate read latencies.
Regarding the amount of CFs, we can ask for explicit metrics per CF and
thus we won't generate metrics if someone didn't ask for them

**Comment by glommer** [comment]
@dorlaor that's not how prometheus work. When it pulls, it pulls everything. Even if there was a way to enable just some of them - that makes for a very inconvenient interface as far as prometheus is concerned.

The best way to handle this in my opinion is to remove this set of metrics, and add storage proxy metrics instead. They are the metrics we are interested at, from the system level perspective. The metrics already exist, all we need to do is export them.

**Comment by glommer** [comment]
Expanding on this: when @tzach said: 

> Apache Cassandra latency metrics are a good start
> 
> org.apache.cassandra.metrics.ClientRequest.Read.Latency
> org.apache.cassandra.metrics.ClientRequest.Write.Latency
> org.apache.cassandra.metrics.ClientRequest.RangeSlice.Latency
> 
> org.apache.cassandra.metrics.ColumnFamily.system.batchlog.ReadLatency
> org.apache.cassandra.metrics.ColumnFamily.system.batchlog.CoordinatorReadLatency
> org.apache.cassandra.metrics.ColumnFamily.system.batchlog.CoordinatorScanLatency

I agree with that - but the metrics that should end up exported are the "ClientRequest" ones - not ColumnFamily.

**Comment by glommer** [comment]
actually @dor, we don't even need to add the storage proxy metrics. I am checking @amnonh 's series, and it is already there:

```
Amnon Heiman (3):
  estimated_histogram: returns a metrics histogram
  storage_proxy: add read and write latency histogram <==== that is the one I am talking about
  database: add metrics registration for the coloumn family
```

That is 2cf13c26e243660fd680c08c1eff3f310eae1fa3

So to summarize, I think we should be using 2cf13c26e243660fd680c08c1eff3f310eae1fa3 instead of 292c08f, and I furthermore believe that 292c08f should be reverted, as it won't really fly with prometheus.

**Comment by amnonh** [comment]
If we remove the histogram latencies from the column family, maybe we
should keep the other metrics (at least some of them)

**Comment by glommer** [comment]
I think we should remove all metrics from the column family. They will
scale really horribly with the CF count and will be hard to aggregate.

The storage proxy ones are the ones we are looking for.
