### ISSUE TITLE
sstableloader to support Cassandra 3.0 sstable format

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1631]

**Comment by slivne** [comment]
in review

**Comment by penberg** [comment]
@elcallio @slivne Can we close this? Sstableloader has supported 3.0 sstables since https://github.com/scylladb/scylla-tools-java/commit/98725449500895e1d1dc00c2d6889503a3252a89

**Comment by roydahan** [comment]
I'm working to add the necessary dtest support for it.
If you want, we can keep it as a placeholder and close it when I merge the tests.

**Comment by penberg** [comment]
@roydahan 👍

**Comment by slivne** [comment]
scylladb/scylla-dtest@2e6681707879e3f8f2200c2d6440d75462278f85
