### ISSUE TITLE
native sstable validation yields false positive errors

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#16326]
The problem is limited to the MX-specific validator, introduced in https://github.com/scylladb/scylladb/commit/5f37d43ee627b70807bd08ca810281677ea996e8.
When validating valid sstables, the validator wrongly reports false-positive errors.

Affects 5.4 and later.

**Comment by mykaul** [comment]
https://github.com/scylladb/scylladb/pull/18404 covered 5.4, removing label.
