### ISSUE TITLE
Allow paging to reuturn less rows then requested

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1633]
- Paging allows to return less rows than a page size
- Limit does not allow to return less rows then requested (unless there are not enough) - as such the implementation needs to deal with "short reads".

Scylla current paging implementation uses limit - so it does not utilize this difference that allow to return results in case of "short reads" faster to the client.

 Additionally, limit/paging queries are currently limited by the amounts of rows that need to be returned - there is no limit on the amount of memory a result can take - we can enhance paging queries to take use this as an additional factor when deciding how many rows to return.

**Comment by duarten** [comment]
This should either be runtime configurable, or we have to ensure Thrift verbs are able to re-issue queries to gather `limit` results.

**Comment by gleb-cloudius** [comment]
On Wed, Aug 31, 2016 at 08:24:48AM -0700, Duarte Nunes wrote:
> This should either be runtime configurable, or we have to ensure Thrift verbs are able to re-issue queries to gather `limit` results.
> 
Does thrift not allow returning less rows for paged query?

--
			Gleb.

**Comment by duarten** [comment]
Nop, the protocol says very little about paging. In fact, only one verb (`get_paged_slices`) has a paging-friendly interface, and in that case the "documentation" says 

> returns a range of columns, wrapping to the next rows if necessary to collect max_results

which is a good indication for clients that they can assume there are no more rows/columns if less values than the limit are returned.

**Comment by gleb-cloudius** [comment]
On Wed, Aug 31, 2016 at 09:02:27AM -0700, Duarte Nunes wrote:
> Nop, the protocol says very little about paging. In fact, only one verb (`get_paged_slices`) has a paging-friendly interface, and in that case the "documentation" says 
> 
> > returns a range of columns, wrapping to the next rows if necessary to collect max_results
> 
> which is a good indication for clients that they can assume there are no more rows/columns if less values than the limit are returned.
> 
Then upper layers of thrift my continue using limits to emulate paging,
cql will provide an indication if limit is part of paging or not.

--
			Gleb.

**Comment by slivne** [comment]
This should help with #1545

**Comment by pdziepak** [comment]
Fixed in 57f49108322e907e0896b5b4db67ca6db7366a86.
