### ISSUE TITLE
Eviction causes latency spikes

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1634]
_Installation details_
Scylla version (or git commit hash): 6cb796f38b944caf5089d8e568131d5fca6b96d6 (master)
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora 23

On the graph below you can see that eviction spikes correlate with c-s reported latency spikes of ~130ms.

![image](https://cloud.githubusercontent.com/assets/283695/18134525/f40d6610-6f9e-11e6-9bcb-5b8d5dfbc4ae.png)

```
cassandra-stress read no-warmup duration=10m -pop dist=gauss\(1..1000000, 500000, 100000\) -rate threads=100 limit=10000/s
```

**Comment by avikivity** [comment]
I don't think eviction (by itself) is to blame.  We're freeing around 50MB here (hard to tell), this is bound to be expensive.  Why are we freeing 50MB?

**Comment by slivne** [comment]
how did you add c-s output to the graphs ?

**Comment by tgrabiec** [comment]
@slivne I wrote a script which parses c-s logs and pushes the metrics to collectd via unix socket.

**Comment by dorlaor** [comment]
Still nice to see the 99% at 1msec. However, good to fix the issue

**Comment by tzach** [comment]
> @slivne I wrote a script which parses c-s logs and pushes the metrics to collectd via unix socket.

Do share!

**Comment by tgrabiec** [comment]
High latency is caused by high reclamation latency (according to logs, 77ms). High latency is due to large amount of objects needed to be evicted (~38MB). We need to evict that much in order to bring cache region occupancy below the compaction threshold (93% -> 85%). Remainder - we don't compact regions with high occupancy because that's ineffective, we would need to copy a lot for little gain. 

Evidence:

```
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa - Compacting, requested 262144 bytes, 470024192 bytes in use, target is 469762048
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa - Occupancy of regions:
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 12: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 11: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 24: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 27: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 32: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 8: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 34: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 30: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 7: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 53: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 14: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 56: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 28: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 22: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 33: min=28.28%, 74131 / 262144 [B], avg=35.42%, 185714 / 524288 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 1: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 17: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 38: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 45: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 26: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 4: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 10: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 20: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 18: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 29: min=85.71%, 224688 / 262144 [B], avg=85.71%, 224688 / 262144 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 15: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 31: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 44: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 16: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 839: min=82.42%, 216066 / 262144 [B], avg=93.13%, 16113652 / 17301504 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 2: min=80.47%, 210944 / 262144 [B], avg=93.60%, 421282560 / 450101248 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 25: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 6: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 23: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 39: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 54: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 49: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 13: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 52: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 50: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa -  - 9: min=0.00%, 0 / 0 [B], avg=0.00%, 0 / 0 [B]
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa - Considering evictable regions.
DEBUG 2016-08-31 19:56:21,628 [shard 0] lsa - Evicting 0 bytes from region 2, occupancy=93.54%, 421283432 / 450363392 [B]
DEBUG 2016-08-31 19:56:21,705 [shard 0] lsa - Compacting after evicting 38697125 bytes
DEBUG 2016-08-31 19:56:21,705 [shard 0] lsa - Compacting segment 0x600007bc0000 from region 2, 32.15%, 84288 / 262144 [B]
DEBUG 2016-08-31 19:56:21,705 [shard 0] lsa - Evicting 0 bytes from region 2, occupancy=85.00%, 382586307 / 450101248 [B]
DEBUG 2016-08-31 19:56:21,705 [shard 0] lsa - Target met after evicting 1032 bytes
DEBUG 2016-08-31 19:56:21,705 [shard 0] lsa - Released 262144 bytes (wanted 262144), 0 during compaction, 0 from reserve
DEBUG 2016-08-31 19:56:21,705 [shard 0] lsa-timing - Reclamation cycle took 77737.2 us. Reclamation rate = 3.216 MiB/s
```

**Comment by tgrabiec** [comment]
Perhaps we could remedy this a bit by stopping eviction as soon as the sparsest segment becomes compactible.

**Comment by avikivity** [comment]
Why is the region occupancy important?  Isn't the segment occupancy of the sparsest segments the determining factor?

**Comment by avikivity** [comment]
A very large region could have very high occupancy, esp. due to background compaction, but still have some sparse segments.

**Comment by avikivity** [comment]
What we might do is have cache insertions proactively free items.

````
if std free < threshold1:
    evict items and free memory to std
else if std free < threshold2
    evict items so that lsa free >= (threshold2 - threshold1) / 2
````

so, as long as threshold1 < std free  < threshold2, we keep some memory in lsa recycled. since that memory is freed on insertion of another item, the cost of frees is distributed among many allocations, and we also don't bounce memory between lsa and std

**Comment by avikivity** [comment]
(the first branch of the if-else is part of std reclaimer, the second part is in lsa -- it's not a single if/efse)

**Comment by tgrabiec** [comment]
Yes, looking at sparsest segment and compacting incrementally should be better. That's what I also suggested in the previous comment. I have a patch which does that. Here's a preview:

![incremental eviction](https://cloud.githubusercontent.com/assets/283695/18173299/66c5dadc-7069-11e6-90bc-07edacb3f7f6.png)

The cost is spread out now, but latency is noticeably elevated. Maybe we should think about how to make eviction more localized to avoid memory random walk.

**Comment by avikivity** [comment]
I think proactive eviction will help.  In a latency sensitive load, we'll have plenty of idle time, so idle-time compaction will do the heavy lifting of compacting, all we need to do is free memory; at steady state we free one byte for every byte allocated.

**Comment by tgrabiec** [comment]
There is still some remaining problem. We can still arrive at high occupancy, e.g. when LSA has large amounts of free segments to fill up before eviction starts. That's the case when it warms up, then we reach 100% occupancy. 

When we reach this, if LRU order doesn't match allocation order, we may have to do a lot of eviction in order to bring any segment below the threshold. 

That will not be the case for write-mostly workloads, or populate-mostly workloads, for which LRU-order matches allocation order.

Solution for this would be to start evicting as soon as average utilization grows above the threshold, taking into account all the free space dedicated to LSA.

I reproduced the problem using a program which writes objects of 1 KiB in size with a 10 GiB heap and at the time when eviction starts it shuffles the LRU (but only once):

Histogram of items evicted per reclaim event shows that we evict in the worst case ~80000 objects in a single event:

```
[2..2]: 0
[3..3]: 0
[4..4]: 0
[5..5]: 0
[6..6]: 0
[7..7]: 0
[8..8]: 0
[9..10]: 0
[11..12]: 0
[13..14]: 0
[15..17]: 0
[18..20]: 0
[21..24]: 0
[25..29]: 2
[30..35]: 2
[36..42]: 5
[43..50]: 10
[51..60]: 25
[61..72]: 37
[73..86]: 92
[87..103]: 141
[104..124]: 217
[125..149]: 300
[150..179]: 437
[180..215]: 519
[216..258]: 599
[259..310]: 740
[311..372]: 341
[373..446]: 185
[447..535]: 79
[536..642]: 29
[643..770]: 18
[771..924]: 12
[925..1109]: 6
[1110..1331]: 5
[1332..1597]: 2
[1598..1916]: 4
[1917..2299]: 1
[2300..2759]: 1
[2760..3311]: 0
[3312..3973]: 1
[3974..4768]: 0
[4769..5722]: 0
[5723..6866]: 0
[6867..8239]: 0
[8240..9887]: 0
[9888..11864]: 1
[11865..14237]: 0
[14238..17084]: 0
[17085..20501]: 0
[20502..24601]: 0
[24602..29521]: 0
[29522..35425]: 0
[35426..42510]: 0
[42511..51012]: 0
[51013..61214]: 0
[61215..73457]: 0
[73458..88148]: 1
```

This is the worst case scenario which arguably may not be that easy to reach in practice (LRU typically will not be completely uniform), but seems possible for a changing workload.

Compare to a vanilla append-only workload:

```
[2..2]: 0
[3..3]: 0
[4..4]: 0
[5..5]: 0
[6..6]: 0
[7..7]: 0
[8..8]: 0
[9..10]: 0
[11..12]: 0
[13..14]: 0
[15..17]: 0
[18..20]: 0
[21..24]: 0
[25..29]: 0
[30..35]: 0
[36..42]: 0
[43..50]: 0
[51..60]: 0
[61..72]: 0
[73..86]: 1
[87..103]: 0
[104..124]: 0
[125..149]: 0
[150..179]: 0
[180..215]: 0
[216..258]: 4
[259..310]: 34851

```

**Comment by avikivity** [comment]
Perhaps we could introduce some randomization by having >1 open segments, although it's probably not good for performance.

**Comment by duarten** [comment]
We could also have a policy where after X objects are evicted, or T time has elapsed, we handpick and evict the remaining objects in the sparsest segment to make the region compactible. We would essentially be switching from an allocator-agnostic eviction policy to one that benefits the allocator.

**Comment by tgrabiec** [comment]
2017-04-24 10:24 GMT+02:00 Avi Kivity <notifications@github.com>:

> Perhaps we could introduce some randomization by having >1 open segments,
> although it's probably not good for performance.
>
How would this help?

**Comment by avikivity** [comment]
@tgrabiec half-baked thought, it wouldn't; the problem is too much randomization

**Comment by avikivity** [comment]
@duarten we can't in general evict based on address, there's no path from a leaf to an unlinkable item.

**Comment by duarten** [comment]
@avikivity True. Although if the eviction function knows the concrete type, and the managed type has the backref, all we're missing is the position of the leaf in the unlinkable item (in some cases it could be fully determined based on the types alone).

**Comment by duarten** [comment]
Oh, scratch that, we can't get the type from the address.

**Comment by avikivity** [comment]
We actually can (we have a migrate_fn_type* stored in front of every object), but that's not enough.  Even though we have a backreference, we have no idea what object type the backreference is embedded in.

Given

   void* obj;

We can determine the dynamic type of obj `Type`, and all (usually 1) pointers to obj `Type** forward_reference`, but `forward_reference` is usually a field in some other type, and we don't know what (iow we want `Type* Embedder::*forward_reference`, but we can't guess either `Embedder` or the value of the pointer-to-member).

**Comment by duarten** [comment]
Momentarily forgot about the migrators :)  We could have an eviction function per `Embedder`, but that would only work when it directly contains the managed object and not a pointer. But I think this is the common case?

**Comment by avikivity** [comment]
It doesn't help, consider

````
struct my_embedder {
    managed_bytes one;
    managed_bytes two;
    managed_bytes three;
};

struct your_embedder {
    int just_because;
    managed_bytes one;
    managed_bytes two;
};
```


Given a `blob_storage`, we can't tell if the backreference points at `my_embedder::three` or `your_embedder::one`.  We would need distinct types for each embedder and embed-position (and don't even think about `managed_vector<managed_bytes>`.

**Comment by duarten** [comment]
I was thinking we could encode the embed-position in the managed objects (stealing some bits from the backref?), but you're right, we would also need to encode the types of the embedders to be able to navigate to an unlinkable object :(

**Comment by avikivity** [comment]
@tgrabiec I believe this can be closed. Perhaps #3341 is the only remnant, and much less serious than this report.

**Comment by glommer** [comment]
#3341 has nothing to do with eviction.

**Comment by avikivity** [comment]
#3341 is a large allocation without yields, and large allocations cause eviction to free memory to satisfy the allocation.

**Comment by glommer** [comment]
No. The stalls with 3341 are dissociated with the allocation. They happen when filling an array with integers.

#3335 is more relevant

**Comment by tgrabiec** [comment]
@avikivity The remaining problem is not related to large allocations. Reclamation of a single LSA segment can take a long time if all segments are fully occupied and LRU is close to random.

**Comment by avikivity** [comment]
> No. The stalls with 3341 are dissociated with the allocation. They happen when filling an array with integers.

#3341 causes allocation, so it requires lsa eviction if memory is low. You might not have caught it under low-memory conditions, but that's just one sample.

Evicting a few megabyte's worth of memory is a lot more work than zero-filling the same amount of memory.

**Comment by avikivity** [comment]
> @avikivity The remaining problem is not related to large allocations. Reclamation of a single LSA segment can take a long time if all segments are fully occupied and LRU is close to random.

What's the amplification with truly random LRU, according to that S-curve simulation? (amplification = (items evicted) per (segment reclaimed), given some average item size).

The move to 128k segments should have helped a little.

**Comment by tgrabiec** [comment]
For current `max_used_space_for_compaction` of `85%`, in the worst case we'd need to evict 15% of shard's memory before we can start reclaiming segments by compaction.

One proposed solution was to always keep LSA occupancy not greater than 85%, at the cost of wasting some memory.

**Comment by tgrabiec** [comment]
Maybe, when reclaimer figures out that eviction is not effective, it should switch to compaction regardless of the threshold not being met, sacrificing throughput for latency.

**Comment by avikivity** [comment]
That's not a random LRU, that's an adversarial LRU. Truly random should generate outliers that we can pick off.

It may be that repeated eviction+compaction turns a random LRU into a worst-case LRU.

**Comment by avikivity** [comment]
> Maybe, when reclaimer figures out that eviction is not effective, it should switch to compaction regardless of the threshold not being met, sacrificing throughput for latency.

Maybe. There's a risk that it will dig itself into a corner, with each compaction becoming harder and harder due to more compacted-segments-per-reclaimed-segments each iteration.

**Comment by tgrabiec** [comment]
2018-04-10 9:47 GMT+02:00 Avi Kivity <notifications@github.com>:

> That's not a random LRU, that's an adversarial LRU. Truly random should
> generate outliers that we can pick off.
>

True. According to my simulartor, for 128K segments, 1GiB shard, and 1 KiB
objects, we'd have to evict 6% of shard's memory for a single segment to go
below the threshold.

**Comment by avikivity** [comment]
That's 60,000 items, certainly a stall.

Starting from fully packed? That can happen, but it's not a likely case. After you evict 6% and compact the bottom 6-7 segments you have a "residual" S-curve so you aren't starting from scratch.

However, large allocations, even if not requiring contiguous memory, will tend to pack lsa and we'll see more of these edge cases compared to interspersing allocations with normal inserts and reads that scramble the LRU.

**Comment by glommer** [comment]
>> No. The stalls with 3341 are dissociated with the allocation. They happen when filling an array with  integers.

>#3341 causes allocation, so it requires lsa eviction if memory is low. You might not have caught it under low-memory conditions, but that's just one sample.
>
> Evicting a few megabyte's worth of memory is a lot more work than zero-filling the same amount of memory.

I am not disputing that allocations can cause stalls. I am clarifying that the bug specifically deals with filling an array.

**Comment by glommer** [comment]
Would it help if we brought compact-on-idle back? One would argue at this point that maybe we are never idle, but that isn't true anymore: with the CPU scheduler, we can guarantee that we can run "idle" tasks for no more than, say, 1 % of the CPU time (unless we are really idle)

**Comment by tgrabiec** [comment]
@glommer We could use idle time to implement https://github.com/scylladb/scylla/issues/1921, which may make running into this problem less likely.

**Comment by glommer** [comment]
I am all for making the whole thing more efficient and reducing complexity. But having segment compaction happening in the request path is double nasty. It will take away vruntime from request processing, and the CPU scheduler may not schedule request processing for a long time because it just ran a lot. Except it didn't - because all that time was spent compacting segments, not running requests.

I am now wondering if, regardless of idle or not, we should move that out of the request group altogether?

**Comment by avikivity** [comment]
Compact-on-idle makes it worse, by packing segments. Sure it frees memory but that gets taken up by writes immediately. As soon as a large allocation comes by, lsa will have to work a lot harder to satisfy it.

**Comment by avikivity** [comment]
> I am now wondering if, regardless of idle or not, we should move that out of the request group altogether?


It's a synchronous operation, the scheduler doesn't know about it.

**Comment by glommer** [comment]
It doesn't, but we can teach it.

Now statements are all in their own group. We can just call compact with `with_scheduling_group(default_sg()`

**Comment by avikivity** [comment]
It's in a synchronous call, no continuations.

**Comment by dorlaor** [comment]
What's the current status? One of our users claim he hit it although I do not have any detail

**Comment by avikivity** [comment]
Things have improved a lot (you won't see 130ms latency spikes due to eviction as in the original report) but eviction can still cause latency spikes. Since the trigger is ourside eviction (large allocations), it's not possible to ever say with certainty that it's closed.

On the eviction side, a lot of work went into making it more efficient, but it's equally impossible to say that all that could been done has been done.

**Comment by tgrabiec** [comment]
The problem of stalls due to high segment occupancy and random LRU is still there, I think.

Refs https://github.com/scylladb/scylla/issues/4186

**Comment by bhalevy** [comment]
I wonder is using (linux specific) [mremap(2)](http://man7.org/linux/man-pages/man2/mremap.2.html) to swap page mappings could help optimizing eviction for large allocations by evicting sparse pages and then mapping them to a contiguous virtual address range by swapping the page mappings.

**Comment by avikivity** [comment]
@bhalevy mremap is terrible for multi-core due to TLB shootdowns, and kills our MADV_HUGEPAGE optimization

@tgrabiec perhaps we should have a separate eviction thread (and scheduling group) that tries to maintain the free list to a level seen by reclaimer calls. Its shares would increase when it is far from that level, and it will stop work when it is at that level. This will spread out the work to allocate. We could also tie it to the lsa allocation_group reserves.

**Comment by avikivity** [comment]
(reactor load 100%)

**Comment by avikivity** [comment]
This is a major change, and not a regression, so not backporting.
