### ISSUE TITLE
[1.3 AMI] Node under drain thinks it's still in the cluster

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#1637]
*Installation details*
Scylla version (or git commit hash):
Cluster info: Cluster lmr-scylla-db-cluster-0deeda83 (AMI: ami-dd46ffca Type: c3.xlarge) (latest 1.3 AMI)

When running `nodetool drain` on a node, it still thinks it's part of the cluster, but it's other peers correctly recognize it's leaving the cluster:

Here's the result on a 6 cluster node. First, the other nodes:

    21:19:51 INFO | sdcm.nemesis.DrainerMonkey: Status for regular Node lmr-scylla-db-node-0deeda83-1 [54.89.157.100 | 172.30.0.8] (seed: False): Command: /bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-masterAu0TqS/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmp9ymHTO -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/lmr-longevity-test-f9804ed0.pem 54.89.157.100 "nodetool status"
    Exit status: 0
    Duration: 5.47210288048
    Stdout:
    Datacenter: datacenter1
    =======================
    Status=Up/Down
    |/ State=Normal/Leaving/Joining/Moving
    --  Address     Load       Tokens  Owns    Host ID                               Rack
    UN  172.30.0.8  8.87 GB    256     ?       01bd32b5-222e-41a6-8a13-6fd9ae3a2db1  rack1
    UN  172.30.0.9  8.32 GB    256     ?       c7e9f0b7-d159-4ad7-9da5-5d3fd7f40998  rack1
    UN  172.30.0.6  9.05 GB    256     ?       de105f0a-cfe1-4102-8a02-63287d04e723  rack1
    UN  172.30.0.7  8.25 GB    256     ?       7eb06ec1-4501-4da9-a5fc-eb88142c6e90  rack1
    DN  172.30.0.4  8.23 GB    256     ?       9bf49e07-a8c7-4f9d-ba36-b79e366f544f  rack1
    UN  172.30.0.5  8.87 GB    256     ?       6febe041-a4ac-4594-a5a1-c8dd37166f90  rack1

    21:19:57 INFO | sdcm.nemesis.DrainerMonkey: Status for regular Node lmr-scylla-db-node-0deeda83-2 [54.152.94.244 | 172.30.0.5] (seed: True): Command: /bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-masterF3Qxa6/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpO6wUXS -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/lmr-longevity-test-f9804ed0.pem 54.152.94.244 "nodetool status"
    Exit status: 0
    Duration: 5.66918301582
    Stdout:
    Datacenter: datacenter1
    =======================
    Status=Up/Down
    |/ State=Normal/Leaving/Joining/Moving
    --  Address     Load       Tokens  Owns    Host ID                               Rack
    UN  172.30.0.8  8.87 GB    256     ?       01bd32b5-222e-41a6-8a13-6fd9ae3a2db1  rack1
    UN  172.30.0.9  8.32 GB    256     ?       c7e9f0b7-d159-4ad7-9da5-5d3fd7f40998  rack1
    UN  172.30.0.6  9.05 GB    256     ?       de105f0a-cfe1-4102-8a02-63287d04e723  rack1
    UN  172.30.0.7  8.25 GB    256     ?       7eb06ec1-4501-4da9-a5fc-eb88142c6e90  rack1
    DN  172.30.0.4  8.23 GB    256     ?       9bf49e07-a8c7-4f9d-ba36-b79e366f544f  rack1
    UN  172.30.0.5  8.87 GB    256     ?       6febe041-a4ac-4594-a5a1-c8dd37166f90  rack1

    21:20:05 INFO | sdcm.nemesis.DrainerMonkey: Status for regular Node lmr-scylla-db-node-0deeda83-4 [54.163.141.56 | 172.30.0.7] (seed: False): Command: /bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-mastertuOn_k/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpUxzIWL -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/lmr-longevity-test-f9804ed0.pem 54.163.141.56 "nodetool status"
    Exit status: 0
    Duration: 6.17845201492
    Stdout:
    Datacenter: datacenter1
    =======================
    Status=Up/Down
    |/ State=Normal/Leaving/Joining/Moving
    --  Address     Load       Tokens  Owns    Host ID                               Rack
    UN  172.30.0.8  8.87 GB    256     ?       01bd32b5-222e-41a6-8a13-6fd9ae3a2db1  rack1
    UN  172.30.0.9  8.32 GB    256     ?       c7e9f0b7-d159-4ad7-9da5-5d3fd7f40998  rack1
    UN  172.30.0.6  9.05 GB    256     ?       de105f0a-cfe1-4102-8a02-63287d04e723  rack1
    UN  172.30.0.7  8.25 GB    256     ?       7eb06ec1-4501-4da9-a5fc-eb88142c6e90  rack1
    DN  172.30.0.4  8.23 GB    256     ?       9bf49e07-a8c7-4f9d-ba36-b79e366f544f  rack1
    UN  172.30.0.5  8.87 GB    256     ?       6febe041-a4ac-4594-a5a1-c8dd37166f90  rack1

    21:20:11 INFO | sdcm.nemesis.DrainerMonkey: Status for regular Node lmr-scylla-db-node-0deeda83-5 [54.173.187.115 | 172.30.0.6] (seed: False): Command: /bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-masterheudKp/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpkDNqqX -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/lmr-longevity-test-f9804ed0.pem 54.173.187.115 "nodetool status"
    Exit status: 0
    Duration: 5.49282312393
    Stdout:
    Datacenter: datacenter1
    =======================
    Status=Up/Down
    |/ State=Normal/Leaving/Joining/Moving
    --  Address     Load       Tokens  Owns    Host ID                               Rack
    UN  172.30.0.8  8.87 GB    256     ?       01bd32b5-222e-41a6-8a13-6fd9ae3a2db1  rack1
    UN  172.30.0.9  8.6 GB     256     ?       c7e9f0b7-d159-4ad7-9da5-5d3fd7f40998  rack1
    UN  172.30.0.6  9.38 GB    256     ?       de105f0a-cfe1-4102-8a02-63287d04e723  rack1
    UN  172.30.0.7  8.53 GB    256     ?       7eb06ec1-4501-4da9-a5fc-eb88142c6e90  rack1
    DN  172.30.0.4  8.23 GB    256     ?       9bf49e07-a8c7-4f9d-ba36-b79e366f544f  rack1
    UN  172.30.0.5  9.18 GB    256     ?       6febe041-a4ac-4594-a5a1-c8dd37166f90  rack1

    21:20:17 INFO | sdcm.nemesis.DrainerMonkey: Status for regular Node lmr-scylla-db-node-0deeda83-6 [54.175.66.16 | 172.30.0.9] (seed: False): Command: /bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-master4E2Gs4/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpgGlGRo -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/lmr-longevity-test-f9804ed0.pem 54.175.66.16 "nodetool status"
    Exit status: 0
    Duration: 5.7983341217
    Stdout:
    Datacenter: datacenter1
    =======================
    Status=Up/Down
    |/ State=Normal/Leaving/Joining/Moving
    --  Address     Load       Tokens  Owns    Host ID                               Rack
    UN  172.30.0.8  8.87 GB    256     ?       01bd32b5-222e-41a6-8a13-6fd9ae3a2db1  rack1
    UN  172.30.0.9  8.6 GB     256     ?       c7e9f0b7-d159-4ad7-9da5-5d3fd7f40998  rack1
    UN  172.30.0.6  9.38 GB    256     ?       de105f0a-cfe1-4102-8a02-63287d04e723  rack1
    UN  172.30.0.7  8.53 GB    256     ?       7eb06ec1-4501-4da9-a5fc-eb88142c6e90  rack1
    DN  172.30.0.4  8.23 GB    256     ?       9bf49e07-a8c7-4f9d-ba36-b79e366f544f  rack1
    UN  172.30.0.5  9.18 GB    256     ?       6febe041-a4ac-4594-a5a1-c8dd37166f90  rack1

Then, the node under drain:

    21:19:59 INFO | sdcm.nemesis.DrainerMonkey: Status for target Node lmr-scylla-db-node-0deeda83-3 [54.174.94.75 | 172.30.0.4] (seed: False): Command: /bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-master7sbbT1/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpcYkxfJ -o BatchMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/lmr-longevity-test-f9804ed0.pem 54.174.94.75 "nodetool status"
    Exit status: 0
    Duration: 2.58793306351
    Stdout:
    Datacenter: datacenter1
    =======================
    Status=Up/Down
    |/ State=Normal/Leaving/Joining/Moving
    --  Address     Load       Tokens  Owns    Host ID                               Rack
    UN  172.30.0.8  8.87 GB    256     ?       01bd32b5-222e-41a6-8a13-6fd9ae3a2db1  rack1
    UN  172.30.0.9  8.32 GB    256     ?       c7e9f0b7-d159-4ad7-9da5-5d3fd7f40998  rack1
    UN  172.30.0.6  9.05 GB    256     ?       de105f0a-cfe1-4102-8a02-63287d04e723  rack1
    UN  172.30.0.7  8.25 GB    256     ?       7eb06ec1-4501-4da9-a5fc-eb88142c6e90  rack1
    UN  172.30.0.4  8.23 GB    256     ?       9bf49e07-a8c7-4f9d-ba36-b79e366f544f  rack1
    UN  172.30.0.5  8.87 GB    256     ?       6febe041-a4ac-4594-a5a1-c8dd37166f90  rack1

We should do better at reporting the status of the node under drain.

**Comment by slivne** [comment]
#1629 solution will also solve this
