### ISSUE TITLE
 question about commit log total size

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#1638]
_Installation details_
Scylla version (or git commit hash): 1.3
Cluster size: 3 node
OS (CentOS)
16Core / 32G memory / HDD

Hi
I have a question about commit log total size
We are testing HDD based performance
Test result said that scylldb generated more commit log than cassandra and lower performance
Scylladb met disk bottleneck  in spite of lower TPS , I guess It depends on commit log total size....  
I guess Scylladb stores more data in commit log than cassandra...
Could you explain this result?
1. test result
   
   > cassandra performance is better than scylla
   > scylladb generate more commit log than cassandra 
   > We specified lower Thread count on ScyllaDB Because of disk bottleneck.
   > We specified commitlog uncompressed mode in cassandra
   > ![image](https://cloud.githubusercontent.com/assets/10610884/18155811/19352c18-704c-11e6-931a-03366322fbdb.png)
2. Stress tool Config
   scylladb command
   cassandra-stress user cl=QUORUM duration=1m profile=/root/nmon/cqlstress-example.yaml  ops(insert=8,range1=2) -mode native cql3 -port native=50006 thrift=9165 -rate threads=50 -node ip1,ip2,ip3

cassandra command 
cassandra-stress user cl=QUORUM duration=1m profile=/root/nmon/cqlstress-example.yaml  ops(insert=8,range1=2) -mode native cql3 -port native=50006 thrift=9165 -rate threads=100 -node ip1,ip2,ip3

**Comment by dorlaor** [comment]
It could be the case that Scylla's default is not to compress the data.
In addition, we lack commit log compression which should be added

**Comment by infordb** [comment]
We Created Table with LZ4Compressor option in Scylla
And we specified commitlog uncompressed mode in cassandra
So Test environment is the same
But scylladb generate more commit log than cassandra  and cassandra performance is better than scylla on HDD 

CREATE TABLE scloud.keytest2 (
    key text PRIMARY KEY,
    column1 text,
    column2 text,
    column3 text,
    column4 text,
    column5 text,
    column6 text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

**Comment by dorlaor** [comment]
@elcallio do you have an idea? 
The performance is better since the disk is the bottleneck in this case and we
write 'too' much

**Comment by infordb** [comment]
We Wrote same data volumn
But commit log size was defferent (ScyllaDB makes much more data in commit log)
This could cause disk bottleneck...

_==> scylla 1.3 commit _log__
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-108086394588113891.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-108086394588113892.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-126100793097595875.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-126100793097595876.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-144115191607077859.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-144115191607077860.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-162129590116559843.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-162129590116559844.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-180143988626041827.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-180143988626041828.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-18014402040703971.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-18014402040703972.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-198158387135523811.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-198158387135523812.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-216172785645005795.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-216172785645005796.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-234187184154487779.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-234187184154487780.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-252201582663969763.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-252201582663969764.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-270215981173451747.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-270215981173451748.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-3531221987.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-3531221988.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-36028800550185955.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-36028800550185956.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-54043199059667939.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-54043199059667940.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-72057597569149923.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-72057597569149924.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-90071996078631907.log
-rw-r--r--. 1 scylla scylla 33554432 Sep  1 14:21 CommitLog-1-90071996078631908.log

==> cassandra 2.2.7 commit log with commit log compression
-rw-r--r--. 1 root root 5550345 Sep  1 14:50 CommitLog-5-1472708412286.log
-rw-r--r--. 1 root root 5516025 Sep  1 14:50 CommitLog-5-1472708412287.log
-rw-r--r--. 1 root root 5474783 Sep  1 14:50 CommitLog-5-1472708412288.log
-rw-r--r--. 1 root root 5385350 Sep  1 14:51 CommitLog-5-1472708412289.log
-rw-r--r--. 1 root root 5382599 Sep  1 14:51 CommitLog-5-1472708412290.log
-rw-r--r--. 1 root root 5473831 Sep  1 14:51 CommitLog-5-1472708412291.log
-rw-r--r--. 1 root root  674344 Sep  1 14:51 CommitLog-5-1472708412292.log
-rw-r--r--. 1 root root      83 Sep  1 14:51 CommitLog-5-1472708412293.log


==> cassandra 2.2.7 commit log with commit log uncompression
-rw-r--r--. 1 root      root      33554432 Sep  1 14:57 CommitLog-4-1472709294154.log
-rw-r--r--. 1 root      root      33554432 Sep  1 14:58 CommitLog-4-1472709294155.log
-rw-r--r--. 1 root      root      33554432 Sep  1 14:58 CommitLog-4-1472709294156.log
-rw-r--r--. 1 root      root      33554432 Sep  1 14:58 CommitLog-4-1472709294157.log
-rw-r--r--. 1 root      root      33554432 Sep  1 14:58 CommitLog-4-1472709294158.log
-rw-r--r--. 1 root      root      33554432 Sep  1 14:58 CommitLog-4-1472709294159.log
-rw-r--r--. 1 root      root      33554432 Sep  1 14:58 CommitLog-4-1472709294160.log
-rw-r--r--. 1 root      root      33554432 Sep  1 14:58 CommitLog-4-1472709294161.log

**Comment by dorlaor** [comment]
It's probably due to our shard per core approach where every core (hyper
thread)
has its own commitlog. How many HDDs are involved? It may be too slow for
our requirements although I'd still think we should get below C* even here.
What's the iotune results?

**Comment by tgrabiec** [comment]
To fairly compare commit log size you need to start Scylla with one shard (-c1) and write small amount of data so that segments are not discarded by memtable flushes.

Maybe sharding is invoking more disk seeks. Does running with fewer shards improve the situation?

**Comment by infordb** [comment]
2 HHDs , 
one is used as Data directory, another one is used as Commit log directory..

iotune results are
[root@stgtest05 conf]# /usr/lib/scylla/scylla_io_setup
Generating evaluation file sized 10GB...10GB written in 95 seconds
Refining search for maximum. So far, 416 IOPS
Maximum throughput: 416 IOPS
Recommended --max-io-requests: 52
Recommended --num-io-queues: 13
Written the above values to /etc/scylla.d/io.conf

**Comment by infordb** [comment]
memtable flushes did not occur during test

**Comment by avikivity** [comment]
Sharding causes seeks for sure, but on the other hand we have a lot of concurrency so a lot of back-to-back writes can be merged.

**Comment by dorlaor** [comment]
In your case it will be better to raid-0 the 2 disks and use the same dir
for commit and
data.

**Comment by elcallio** [comment]
Size difference is _probably_ due to a combination of facts. Cassandra will bulk several mutations together in a single serialized blob, whereas scylla treats each one separately. This combined with the "chunking" required by dma writes + fault tolerance in file means there can be up to 50% overhead in worst case for the scylla commit log segments.

**Comment by slivne** [comment]
@infordb - @elcallio provided an explanation - if there is a need for followup questions we can reopen the issue
