### ISSUE TITLE
File system  is not qualified for seastar AIO

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#1639]
*Installation details*
Scylla version (or git commit hash): 1.3
Cluster size: 3
OS (CentOS)

We faild iotune.
We use xfs file system and CentOS 7.2
Could you check this problem?

[root@dbtest01 ~] iotune --evaluation-directory /data1/scylla/data --format envfile --options-file /etc/scylla.d/io.conf 16
File system on /data1/scylla/data is not qualified for seastar AIO; see http://docs.scylladb.com/kb/kb-fs-not-qualified-aio/ for details

[root@dbtest01 ~]cat /etc/fstab
/dev/mapper/centos-data1 /data1                  xfs     defaults        1 2

[root@dbtest02 ~]cat /proc/version
Linux version 3.10.0-229.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.2 20140120 (Red Hat 4.8.2-16) (GCC) ) 1 SMP Fri Mar 6 11:36:42 UTC 2015
[root@dbtest01 ~] cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core) 

[root@dbtest02 ~] lsblk
NAME             MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                8:0    0 223.1G  0 disk 
├─sda1             8:1    0  1000M  0 part /boot
├─sda2             8:2    0   145G  0 part 
│ ├─centos-app1  253:0    0  48.8G  0 lvm  /app1
│ └─centos-data1 253:1    0 319.2G  0 lvm  /data1
├─sda3             8:3    0  39.1G  0 part /var
├─sda4             8:4    0     1K  0 part 
├─sda5             8:5    0  24.4G  0 part /
├─sda6             8:6    0   9.8G  0 part /home
└─sda7             8:7    0   3.9G  0 part [SWAP]
sdb                8:16   0 223.1G  0 disk 
└─sdb1             8:17   0 223.1G  0 part 
  └─centos-data1 253:1    0 319.2G  0 lvm  /data1
sr0               11:0    1  1024M  0 rom

**Comment by avikivity** [comment]
Your kernel version is too old.

Try
    yum update
    reboot

**Comment by infordb** [comment]
After updating to Linux version 3.10.0-327.el7.x86_64 
It is running well
Thank you...
