### ISSUE TITLE
Segfault during restart/startup on pretty fresh 1.3.0 cluster

### ISSUE THREAD

**Issue by Jan-M** [scylladb/scylla#1642]
This sadly does not include a lot of information. I did have to restart all nodes due to missconfig pretty much after receiving first data (~10min). First two nodes were killed and restarted without issues.

Third node I just killed the Docker container, which on restart yielded the below segfault.

To me it looks like it rand straight into compaction after starting up. I fixed this by deleting the keyspace's data folder (which is obviously bad). As you can see, it basically ran KairosDB with the Keyspace set to RF=2.

```
Sep  2 16:08:07 ip-172-31-128-11 docker/0a2f2d6f525b[828]: INFO  2016-09-02 16:08:07,735 [shard 0] compaction - Compacted 1 sstables to [/var/lib/cassandra/kairosdb10/row_key_index-6cb54fa0712111e6b4bf000000000000/kairosdb10-row_key_index-ka-124-Data.db:level=0, ]. 65554819 bytes to 8458902 (~12% of original) in 327ms = 24.6698MB/s. ~512 total partitions merged to 87.
Sep  2 16:08:07 ip-172-31-128-11 docker/0a2f2d6f525b[828]: INFO  2016-09-02 16:08:07,735 [shard 0] compaction - Compacting [/var/lib/cassandra/kairosdb10/row_key_index-6cb54fa0712111e6b4bf000000000000/kairosdb10-row_key_index-ka-106-Data.db:level=0, ]
Sep  2 16:08:07 ip-172-31-128-11 docker/0a2f2d6f525b[828]: INFO  2016-09-02 16:08:07,837 [shard 3] compaction - Compacted 1 sstables to [/var/lib/cassandra/kairosdb10/row_key_index-6cb54fa0712111e6b4bf000000000000/kairosdb10-row_key_index-ka-127-Data.db:level=0, ]. 65554819 bytes to 2495910 (~3% of original) in 211ms = 11.281MB/s. ~512 total partitions merged to 79.
Sep  2 16:08:07 ip-172-31-128-11 docker/0a2f2d6f525b[828]: INFO  2016-09-02 16:08:07,850 [shard 3] compaction - Compacting [/var/lib/cassandra/kairosdb10/row_key_index-6cb54fa0712111e6b4bf000000000000/kairosdb10-row_key_index-ka-106-Data.db:level=0, ]
Sep  2 16:08:07 ip-172-31-128-11 docker/0a2f2d6f525b[828]: INFO  2016-09-02 16:08:07,889 [shard 2] compaction - Compacted 1 sstables to [/var/lib/cassandra/kairosdb10/row_key_index-6cb54fa0712111e6b4bf000000000000/kairosdb10-row_key_index-ka-126-Data.db:level=0, ]. 65554819 bytes to 6016108 (~9% of original) in 275ms = 20.8633MB/s. ~512 total partitions merged to 89.
Sep  2 16:08:07 ip-172-31-128-11 docker/0a2f2d6f525b[828]: INFO  2016-09-02 16:08:07,907 [shard 2] compaction - Compacting [/var/lib/cassandra/kairosdb10/row_key_index-6cb54fa0712111e6b4bf000000000000/kairosdb10-row_key_index-ka-106-Data.db:level=0, ]

Sep  2 16:08:08 ip-172-31-128-11 docker/0a2f2d6f525b[828]: /start-scylla: line 92:    17 Segmentation fault      (core dumped) /usr/bin/scylla --smp $SCYLLA_SMP --memory $SCYLLA_MEMORY --log-to-syslog 0 --log-to-stdout 1 --default-log-leve
l info --options-file /etc/scylla/scylla.yaml --network-stack posix $DEV_MODE $SEASTAR_IO $CPU_SET
```

_Installation details_
Scylla version (or git commit hash): 1.3.0
Cluster size: 7 Nodes (m4.xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

_Hardware details (for performance issues)_          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): Docker on EC2
Hardware: sockets= cores= hyperthreading= memory= 4 cores / 16 GB
Disks: (SSD/HDD, count) EBS

**Comment by avikivity** [comment]
@penberg where does our docker image store core dumps?

@Jan-M compacting on startup is not abnormal, ScyllaDB compacts continuously until there is no need.

**Comment by penberg** [comment]
@avikivity I doubt the Docker image stores any coredumps. IIRC, it's systemd that handles them, no? We don't run that on the Docker images.

**Comment by penberg** [comment]
@avikivity Unless it's handled by the host, perhaps?

**Comment by avikivity** [comment]
The kernel dumps core (it said so).  The question is here.  What is /proc/sys/kernel/core_pattern?

**Comment by Jan-M** [comment]
Hi, I will take a look on the host. The Host Kernel Log contains the following line:

```
Sep  2 16:08:07 ip-172-31-128-11 kernel: [ 6403.904078] traps: scylla[10635] general protection ip:52d9ae sp:601000d7ac28 error:0 in scylla[400000+1c8f000]
```

But this is most likely not helpful either.

**Comment by avikivity** [comment]
The core is probably somewhere in the guest.  You can use `docker ps -a` to find dead containers.

Crashes immediately on startup are often due to bad permissions, see #883.

**Comment by Jan-M** [comment]
Thx for the quick reply, I have not been able to find the cure dump though. But if it is permissions I will take a look if I can reproduce and understand it.

**Comment by gleb-cloudius** [comment]
If a build I am looking at is correct the crash is in deleter::~deleter() and _impl is garbage.

**Comment by Jan-M** [comment]
From your wiki:

When Scylla fails, it should create a core dump which can later be used to debug the issue. Starting from scylla 0.14 coredumps are written to /var/lib/scylla/coredump

But probably because of 
ulimit -c => 0
Nothing was actually dumped there.

Another round of restarts now did work fine (only upvoted the issue of not compact before joining back)

**Comment by tzach** [comment]
@penberg what is the conclusion about core dumps in scylla Docker image?
Where do the live and die?

**Comment by penberg** [comment]
It's up to Docker, really.

On my machine, which has Fedora 24, coredumps are handled by host's `systemd-coredump`:

```
[penberg@nero ~]$ docker exec -it some-scylla /bin/sh
sh-4.2# ls -l /proc/sys/kernel/core_pattern                                     
-rw-r--r-- 1 root root 0 Sep 19 12:50 /proc/sys/kernel/core_pattern
sh-4.2# cat /proc/sys/kernel/core_pattern
|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %e
```

I don't have access to Ubuntu here, but this blog post claims the coredumps are _lost_ by default:

http://dmtn-004.lsst.io/en/latest/

**Comment by slivne** [comment]
closing issue as there is no additional information
