### ISSUE TITLE
build error on fedora 24: missing fmt library

### ISSUE THREAD

**Issue by fche** [scylladb/scylla#1643]
On fedora 24, the seastar submodule's prereq of the fmt library is not quite available, nor is listed in the README.md.  This results in a build failure.

FAILED: build/release/net/native-stack.o 
g++ -MMD -MT build/release/net/native-stack.o -MF build/release/net/native-stack.o.d -O2 -I build/release/gen -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE  -march=nehalem -Ifmt -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DHAVE_HWLOC -DHAVE_NUMA -c -o build/release/net/native-stack.o net/native-stack.cc
In file included from ./net/api.hh:31:0,
                 from ./core/posix.hh:44,
                 from ./core/reactor.hh:56,
                 from ./net/net.hh:25,
                 from net/native-stack.hh:25,
                 from net/native-stack.cc:22:
./core/print.hh:25:25: fatal error: fmt/ostream.h: No such file or directory
 #include <fmt/ostream.h>

FMT 3.0 is almost there: https://bodhi.fedoraproject.org/updates/FEDORA-2016-70fa132149 , for fmt 3.0.  But:

In file included from ./net/api.hh:31:0,
                 from ./core/posix.hh:44,
                 from ./core/reactor.hh:56,
                 from ./net/net.hh:25,
                 from net/native-stack.hh:25,
                 from net/native-stack.cc:22:
./core/print.hh:26:24: fatal error: fmt/printf.h: No such file or directory
 #include <fmt/printf.h>

... since this fmt-devel does not include that file at all.  Commenting out that #include seems to make the build go farther.

**Comment by nyh** [comment]
"fmt" is a git submodule.

So run "git submodule update --init --recursive" and it should pull the
required version of fmt for you into the Seastar source directory. No need
to have it installed on your Fedora.


--
Nadav Har'El
nyh@scylladb.com

**Comment by fche** [comment]
Thanks.  Following the scylladb README.md instructions, that subsubmodule didn't get pulled for me.  `git submodule update --init --recursive` is working better.
