### ISSUE TITLE
Error during startup

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#1648]
*Installation details*
Scylla version (or git commit hash):1.3
OS (CentOS 7.2)
Kernel version : Linux version 3.10.0-327.28.3.el7.x86_64

We installed scylladb 1.3 with no problems
But The following error occurred during startup
I don't know why Scylladb find the libboost_program_options.so.1.58.0
Could you check this error?

=============== /var/log/messages ==================================
Sep  5 11:49:09 nosql1 systemd: Starting Scylla Server...
Sep  5 11:49:09 nosql1 scylla_prepare: Setting a physical interface eth0...
Sep  5 11:49:09 nosql1 scylla_prepare: Restarting irqbalance: going to ban the following IRQ numbers: ls: cannot access /sys/class/net/eth0/device/msi_irqs/: No such file or directory
Sep  5 11:49:09 nosql1 scylla_prepare: cat: /sys/class/net/eth0/device/irq: No such file or directory
Sep  5 11:49:09 nosql1 scylla_prepare: ...
Sep  5 11:49:09 nosql1 scylla_prepare: Original irqbalance configuration is in /etc/sysconfig/irqbalance.scylla.orig
Sep  5 11:49:09 nosql1 systemd: Stopping irqbalance daemon...
Sep  5 11:49:09 nosql1 systemd: Started irqbalance daemon.
Sep  5 11:49:09 nosql1 systemd: Starting irqbalance daemon...
Sep  5 11:49:09 nosql1 scylla_prepare: ls: cannot access /sys/class/net/eth0/device/msi_irqs/: No such file or directory
Sep  5 11:49:09 nosql1 scylla_prepare: cat: /sys/class/net/eth0/device/irq: No such file or directory
Sep  5 11:49:09 nosql1 scylla_prepare: Setting mask 0000000e in /sys/class/net/eth0/queues/rx-0/rps_cpus
Sep  5 11:49:09 nosql1 scylla_prepare: Setting mask 0000000f in /sys/class/net/eth0/queues/tx-0/xps_cpus
**_Sep  5 11:49:09 nosql1 scylla: /usr/bin/scylla: error while loading shared libraries: libboost_program_options.so.1.58.0: cannot open shared object file: No such file or directory_**
Sep  5 11:49:09 nosql1 systemd: scylla-server.service: main process exited, code=exited, status=127/n/a
Sep  5 11:49:09 nosql1 systemd: Failed to start Scylla Server.
Sep  5 11:49:09 nosql1 systemd: Dependency failed for Scylla JMX.
Sep  5 11:49:09 nosql1 systemd: Job scylla-jmx.service/start failed with result 'dependency'.
Sep  5 11:49:09 nosql1 systemd: Dependency failed for Run Scylla Housekeeping daily.
Sep  5 11:49:09 nosql1 systemd: Job scylla-housekeeping.timer/start failed with result 'dependency'.
Sep  5 11:49:09 nosql1 systemd: Unit scylla-server.service entered failed state.
Sep  5 11:49:09 nosql1 systemd: scylla-server.service failed.

**Comment by dorlaor** [comment]
Hi,

I just tried it to verify that there isn't any problem.
It worked for me, I followed exactly the installation procedure.

Did you run yum update before/after installing Scylla?
I have this rpm: scylla-boost-program-options-1.58.0-11.el7.centos.x86_64

Dor

**Comment by infordb** [comment]
Hi
If  We upgrade 1.2 to 1.3,  ScyllDB runs well
But if we install ScyllaDB 1.3 directly,  the lib error occurs  during startup
what is difference between install and upgrade ?

**Comment by dorlaor** [comment]
On Mon, Sep 5, 2016 at 3:05 AM, infordb <notifications@github.com> wrote:

> Hi
> If We upgrade 1.2 to 1.3, ScyllDB runs well
> But if we install ScyllaDB 1.3 directly, the lib error occurs during
> startup
> what is difference between install and upgrade ?
>
I don't know, can you please test whether the rpm I mentioned exist?

**Comment by infordb** [comment]
the  rpm you mentioned existed when I installed ScyllaDB 1.3 directly,
But we got the lib error

[root@nosql1 ~]# rpm -qa | grep scylla-boost-program-options
scylla-boost-program-options-1.58.0-11.el7.centos.x86_64

**Comment by dorlaor** [comment]
Can you please verify you have the exact same version and output as I do:

[dor@centos70 ~]$ rpm -ql scylla-boost-program-options
/opt/scylladb/lib64/libboost_program_options.so.1.58.0
/opt/scylladb/share/doc/scylla-boost-program-options-1.58.0
/opt/scylladb/share/doc/scylla-boost-program-options-1.58.0/LICENSE_1_0.txt
[dor@centos70 ~]$ ldd /bin/scylla | grep boost_program
libboost_program_options.so.1.58.0 =>
/opt/scylladb/lib64/libboost_program_options.so.1.58.0 (0x00007fe045ea9000)
[dor@centos70 ~]$ which scylla
/usr/bin/scylla
[dor@centos70 ~]$ rpm -q scylla
scylla-1.3.0-20160824.ec3ace5.el7.centos.x86_64
[dor@centos70 ~]$ rpm -qa | grep scylla
scylla-boost-system-1.58.0-11.el7.centos.x86_64
scylla-boost-thread-1.58.0-11.el7.centos.x86_64
scylla-boost-test-1.58.0-11.el7.centos.x86_64
scylla-boost-date-time-1.58.0-11.el7.centos.x86_64
scylla-server-1.3.0-20160824.ec3ace5.el7.centos.x86_64
scylla-jmx-1.3.0-20160824.7d2646d.el7.centos.noarch
scylla-env-1.0-1.el7.centos.noarch
scylla-conf-1.3.0-20160824.ec3ace5.el7.centos.x86_64
scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
scylla-kernel-conf-1.3.0-20160824.ec3ace5.el7.centos.x86_64
scylla-tools-1.3.0-20160824.9a9cc39.el7.centos.noarch
scylla-1.3.0-20160824.ec3ace5.el7.centos.x86_64

**Comment by infordb** [comment]
I  checked that rpm you mentioned existed all when I installed ScyllaDB 1.3 directly,
But I didn't check  "ldd /bin/scylla | grep boost_program"
After installing ScyllaDB 1.3 through upgrade there is no problem.

**Comment by dorlaor** [comment]
Hi Junghyun,

It might have been an older or damaged 1.3 release.
May we close the issue now?

Thanks, Dor
