### ISSUE TITLE
CPU overload

### ISSUE THREAD

**Issue by jinbuhuan110** [scylladb/scylla#1650]
_Installation details_
Scylla version (or git commit hash): 1.3
Cluster size:1
OS (Ubuntu):

_Hardware details (for performance issues)_          Delete if unneeded
Platform (VM):
Hardware: cores=8 memory=16GB
Disks: (SSD, 1)

Hi,
We have a problem about scylla performance.
The load of CPU is almost 200% as soon as we start scylla with "--smp 2 -m2G", before we run any job on it.

**Comment by tzach** [comment]
@jinbuhuan110 
This was true for old versions [1] but not for 1.3
Can you please run ```ps -ef | grep scylla``` and send the result?

[1] http://www.scylladb.com/doc/faq/#i-have-an-8-core-server-and-top-shows-scylla-is-using-800-cpu-whats-up-with-that

**Comment by slivne** [comment]
any update ?
