### ISSUE TITLE
Failure after upgrade to version 1.3

### ISSUE THREAD

**Issue by PriyaGheewala** [scylladb/scylla#1652]
Hi, 
we are not able to start the scylla server after upgrading it to 1.3

Please find below the logs 

 [shard 0] seastar - Exceptional future ignored: std::out_of_range (_Map_base::at)
  [shard 0] seastar - Exceptional future ignored: std::out_of_range (_Map_base::at)
  [shard 0] seastar - Exceptional future ignored: std::out_of_range (_Map_base::at)
  [shard 0] seastar - Exceptional future ignored: std::out_of_range (_Map_base::at)
  [shard 0] seastar - Exiting on unhandled exception: exceptions::read_timeout_exception...L=ONE.)
  [shard 0] seastar - Exceptional future ignored: std::out_of_range (_Map_base::at)
  [shard 6] seastar - Exceptional future ignored: seastar::gate_closed_exception (gate closed)
  [shard 6] seastar - Exceptional future ignored: seastar::gate_closed_exception (gate closed)
  [shard 6] seastar - Exceptional future ignored: seastar::gate_closed_exception (gate closed)

Installation details
Scylla version (or git commit hash):1.3
Cluster size:1
OS (RHEL/CentOS/Ubuntu/AWS AMI):CentOs 7

Hardware details (for performance issues) :

Platform (physical/VM/cloud instance type/docker): Physical
Hardware: sockets= cores= hyperthreading= memory=32 GB
processor : 39
vendor_id : GenuineIntel
cpu family : 6
model : 62
model name : Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz

Disks: (SSD/HDD, count): 2X SSD

**Comment by PriyaGheewala** [comment]
nodetool drain gives us as follows.

error: javax.ws.rs.ProcessingException (no security manager: RMI class loader disabled)
-- StackTrace --
java.lang.ClassNotFoundException: javax.ws.rs.ProcessingException (no security manager: RMI class loader disabled)
	at sun.rmi.server.LoaderHandler.loadClass(LoaderHandler.java:396)
	at sun.rmi.server.LoaderHandler.loadClass(LoaderHandler.java:186)
	at java.rmi.server.RMIClassLoader$2.loadClass(RMIClassLoader.java:637)
	at java.rmi.server.RMIClassLoader.loadClass(RMIClassLoader.java:264)
	at sun.rmi.server.MarshalInputStream.resolveClass(MarshalInputStream.java:219)
	at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1620)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1521)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1781)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2018)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1942)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1808)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
	at sun.rmi.transport.StreamRemoteCall.executeCall(StreamRemoteCall.java:245)
	at sun.rmi.server.UnicastRef.invoke(UnicastRef.java:162)
	at com.sun.jmx.remote.internal.PRef.invoke(Unknown Source)
	at javax.management.remote.rmi.RMIConnectionImpl_Stub.invoke(Unknown Source)
	at javax.management.remote.rmi.RMIConnector$RemoteMBeanServerConnection.invoke(RMIConnector.java:1020)
	at javax.management.MBeanServerInvocationHandler.invoke(MBeanServerInvocationHandler.java:298)
	at com.sun.proxy.$Proxy6.drain(Unknown Source)
	at org.apache.cassandra.tools.NodeProbe.drain(NodeProbe.java:393)
	at org.apache.cassandra.tools.NodeTool$Drain.execute(NodeTool.java:2594)
	at org.apache.cassandra.tools.NodeTool$NodeToolCmd.run(NodeTool.java:288)
	at org.apache.cassandra.tools.NodeTool.main(NodeTool.java:202)

**Comment by PriyaGheewala** [comment]
Hi,

We tried to roll back to version 1.2 but we are not able to roll back also. after following the procedure listed in roll back doc, when we started scylla server, It's not starting. The status is inactive (dead).

Can you please help us restoring the old snapshot?

**Comment by penberg** [comment]
@PriyaGheewala Is there anything in the logs when you attempt to start 1.2 after the roll back?

**Comment by PriyaGheewala** [comment]
@penberg
Logs are as follows

Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]: EAL: PCI device 0000:06:00.1 on NUMA socket 0
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]: EAL:   probe driver: 8086:1521 rte_igb_pmd
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]: EAL:   Not managed by a supported kernel driver, skipped
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]: EAL: PCI device 0000:06:00.2 on NUMA socket 0
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]: EAL:   probe driver: 8086:1521 rte_igb_pmd
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]: EAL:   Not managed by a supported kernel driver, skipped
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]: EAL: PCI device 0000:06:00.3 on NUMA socket 0
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]: EAL:   probe driver: 8086:1521 rte_igb_pmd
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]: EAL:   Not managed by a supported kernel driver, skipped
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]: Scylla version 1.2.4-20160825.ba5d52c starting ...
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 0] config - Option partitioner is not (yet) used.
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]: Scylla API server listening on 10.57.200.134:10000 ...
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 0] database - Row: max_vector_size: 32, internal_count: 5
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 1] database - Row: max_vector_size: 32, internal_count: 5
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 3] database - Row: max_vector_size: 32, internal_count: 5
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 2] database - Row: max_vector_size: 32, internal_count: 5
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 4] database - Row: max_vector_size: 32, internal_count: 5
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 9] database - Row: max_vector_size: 32, internal_count: 5
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 6] database - Row: max_vector_size: 32, internal_count: 5
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 7] database - Row: max_vector_size: 32, internal_count: 5
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 5] database - Row: max_vector_size: 32, internal_count: 5
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 8] database - Row: max_vector_size: 32, internal_count: 5
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]: Exiting on unhandled exception of type 'std::system_error': Error system:28 (No space left on dev
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 0] compaction_manager - Asked to stop
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 0] compaction_manager - Stopped
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 3] compaction_manager - Asked to stop
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 1] compaction_manager - Asked to stop
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 3] compaction_manager - Stopped
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 4] compaction_manager - Asked to stop
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 2] compaction_manager - Asked to stop
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 1] compaction_manager - Stopped
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 4] compaction_manager - Stopped
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 2] compaction_manager - Stopped
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 6] compaction_manager - Asked to stop
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 5] compaction_manager - Asked to stop
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 9] compaction_manager - Asked to stop
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 7] compaction_manager - Asked to stop
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 8] compaction_manager - Asked to stop
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 6] compaction_manager - Stopped
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 5] compaction_manager - Stopped
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 9] compaction_manager - Stopped
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 7] compaction_manager - Stopped
Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]:  [shard 8] compaction_manager - Stopped

**Comment by rjmcguire** [comment]
How much space is still available on your drive? Have you checked?

"Sep 08 10:18:21 afea-sandbox-2.adnear.net scylla[40132]: Exiting on
> unhandled exception of type 'std::system_error': Error system:28 (No space
> left on dev"


df -i // inodes available / used
df // space available / used

**Comment by tzach** [comment]
@PriyaGheewala any update? you can try clear disk space and try again

**Comment by PriyaGheewala** [comment]
@tzach 

We deleted all our data and installed fresh version 1.3. Currently, it's working fine.
