### ISSUE TITLE
AMI does not run posix_net_conf.sh when NCPUS < 8

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#1654]
Currently, AMI setup script skips to run posix_net_conf.sh when ncpus < 8:
```
if [ $NR_CPU -lt 8 ]; then
    /usr/lib/scylla/scylla_sysconfig_setup --nic eth0 --ami
else
    NR=$((NR_CPU - 1))
    /usr/lib/scylla/scylla_sysconfig_setup --nic eth0 --setup-nic --ami
```
https://github.com/scylladb/scylla-ami/blob/master/scylla_ami_setup#L40

I think this is not correct.

I suppose it skips to run on ncpus<8 instances because excluding cpu0 on RPS/scylla degrade performance when ncpus is too small.
But there's a case we should run it.

For example, on c4.xlarge we have 2cores/4threads and ixgbevf with 2 queues, it will be detected as MQ NIC on posix_net_conf.sh.
Then we shouldn't skip running it.

**Comment by tzach** [comment]
@syuu1228 what the performance effect of this issue? 
If its minor, its not worth to handle this issue.

BTW, c4.xlarge is not one of the AMI pre set instances.

**Comment by syuu1228** [comment]
@tzach This is already fixed at https://github.com/scylladb/scylla-ami/commit/61ff5c6bbbafc65ab473761b679a968bddb6e09a

Haven't measured how big is the performance effect, but it only affects on m3.medium/m3.large/m3.xlarge/c3.large/c3.xlarge on our "supported instance type".
