### ISSUE TITLE
tracing: add prepared statement parameters

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1657]

**Comment by tgrabiec** [comment]
Prepared statements processing starts in `cql_server::connection::process_execute()`. After the call to `options.prepare()`, `options.get_values_count()` and `options.get_value_at()` can be used to access parameter values in the bind order (as appears in the statement). The values are serialized according to  the `data_type` of the parameter. 

To get the type of the parameter one can look at column specifications stored in `prepared_statement::bound_names` (`prepared->bound_names` inside `process_execute()`). The order of specifications matches the order of values inside the `query_options` object (`options`). `column_specification::type` contains the type, which can be used to convert the value to string (`abstract_type::to_string()`).

`column_specification::name` can be used to get the name associated with the marker. That not always maps to a table column. For example in case of  `select * from table limit ?` the marker will have column_specification with the name `[limit]`.

**Comment by slivne** [comment]
@vladzcloudius - did you send a patch for this ?

**Comment by vladzcloudius** [comment]
@slivne Nope.

**Comment by slivne** [comment]
fixed by 5548eb96f7ee4d9330a5a1dc3a9d6dbd49c54a9d
