### ISSUE TITLE
tracing: extract the fixed query parameters from the param map to columns 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1658]
they may conflict with parameters in the prepared statements

**Comment by vladzcloudius** [comment]
@slivne Those map values have the same keys (and values) and the in the corresponding `parameters` map in C*. We may add the corresponding columns for them but to compliant we'll have to keep them in a map too. Therefore, although I agree that it IS a bit ugly to have them in a map, it would be even uglier to have them both in a map AND in a separate column. 

In any case, I wouldn't qualify this issue as a `bug`. I think an (questionable) `enhancement`would be a more appropriate.

**Comment by slivne** [comment]
not following you why do we need to retain the parameters in the map ?

in case there are tools written for the tracing that expect it from there -
lets check if there are such tools

https://docs.datastax.com/en/latest-devcenter/devcenter/dcQueryTrace.html

thats the only one I am aware off

Can we check upstream cassandra if they added parameters and how.

**Comment by vladzcloudius** [comment]
On 09/08/2016 09:34 AM, Shlomi Livne wrote:
> not following you why do we need to retain the parameters in the map ?
>
> in case there are tools written for the tracing that expect it from 
> there -
> lets check if there are such tools

If there are or there are not they may appear in a future.
My point is - I don't think the proposed enhancement is not justified 
since it's completely cosmetic and u are not gaining a lot from it.
On the other hand we may find ourselves in problems if there are tools 
using the values from the "parameters" map.

>
> https://docs.datastax.com/en/latest-devcenter/devcenter/dcQueryTrace.html
>
> thats the only one I am aware off
>
> Can we check upstream cassandra if they added parameters and how.

Our current code is completely aligned with the upstream C*.

**Comment by vladzcloudius** [comment]
After @slivne have explained to me what were his concerns (the possible collision between the existing keys in a `parameters` map and the prepared statements variables names when where are going to be stored in a `parameters` map) i finally understood why he tagged this issue as a `bug`.
So, the easy solution would be to prepend the prepared statements variables names with some distinctive prefix (e.g. "prep_statement_param_") and the issued would be solved.

**Comment by slivne** [comment]
@vladzcloudius - ok lets use your suggestion
