### ISSUE TITLE
Repair can mess-up date-tiered compaction sstable organization

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#1660]
Date-Tiered Compaction Strategy (DTCS) maintains separate tables for different time ranges. It deliberately does not compact together old and new rows even if they are part of the same partition.

Repair breaks this division: If it discovers that some partition this node holds is not up-to-date, it streams the entire partition - both old and new rows - from the remote node to this node, and writes the result into a new memtable (and eventually sstable).

We believe that Cassandra's sstable-based streaming doesn't have this problem, because it can stream parts of each individual remote sstable to a separate local sstable. I have not verified that this is actually what is happening there, however... Cassandra is also planning to move to mutation-based streaming (and apparently have already done so for materialized views) so will suffer from the same problem. 

www.datastax.com/dev/blog/datetieredcompactionstrategy explains this:

> repair can send really old data to your node, but this is also fine, since you run DTCS on all your nodes in the cluster and repair will stream parts of SSTables, all the SSTables streamed will have short time spans, meaning DTCS will put them in the windows and compact them up if needed.

What is missing in this explanation is that each new small sstables is a subset of an original sstable, so it has a small time range and can be compacted usefully with DTCS.

https://labs.spotify.com/2014/12/18/date-tiered-compaction/ notes that repair in DTCS also has a performance problem: It creates tiny but OLD sstables, and these tiny sstables will be compacted against the normally-huge old sstables, which is very inefficient. This performance problem is beyond the scope of this issue.

**Comment by slivne** [comment]
Its not only repair its any streaming

So if we add a new node it will be an issue， decommission a node， remove
node， rebuild etc

**Comment by duarten** [comment]
The problem will be exacerbated with continuous, incremental repairs.

**Comment by hasmikhail** [comment]
feels like a big problem.

**Comment by penberg** [comment]
@asias @nyh is this also fixed by c03568d6876744461b33147bbeea977845663c17?

**Comment by asias** [comment]
No

**Comment by slivne** [comment]
nope it is not

**Comment by raphaelsc** [comment]
DTCS is deprecated, and this problem is fixed for TWCS, so closing this issue...
