### ISSUE TITLE
kworker use excessive cpu after testing scylla

### ISSUE THREAD

**Issue by euclid-geometry** [scylladb/scylla#1661]
I installed scyalla 1.3 and
started scylla with "systemctl start scylla-server" and
stopped scylla with "systemctl stop scylla-server".

But after upper test, some kworkers( kworker/u64:2,  kworker/u64:0 ) is using excessive cpu so I cannot use my host usually. ( I checked that using "top" utility. )

How can I solve this problem?

I cannot kill that processes and reboot doesn't work also.
( "kill -9 pid" doesn't work for that processes. )
---

[Additional Information]

./scylla_setup
1.  Do you want to enable ScyllaDB services?
   Answer yes to automatically start Scylla when the node boots; answer no to skip this step.
   no
2.  Do you want to disable SELinux?
   Answer yes to disable SELinux; this improves performance; answer no to keep it activated.
   yes
3.  Do you want to setup bootloader options?
   Anwser yes to enable hugepages at boot time; this improve performance. Answer no to skip this step.
   yes
4.  Do you want to setup NTP?
   Answer yes to enable time synchronization at boot time. This keeps time right on the node. Answer no to do nothing.
   yes
5.  Do you want to setup RAID and XFS?
   It is recommended to use RAID0 and XFS for Scylla data. If you select yes, you will be prompt to choose which disks to use for Scylla data. Selected disks will be formatted in the process.
   no
6.  Do you want to setup coredump?
   Answer yes to enable core dumps; this allow to do post mortem analysis of Scylla state after a crash. Answer no to do nothing.
   yes
7.  Do you want to setup sysconfig?
   Answer yes to do system wide configuration customized for Scylla. Answer no to do nothing.
   yes
8.  Please select NIC from following list:
   docker0 em1 em2 em3 em4 flannel.1 veth346ac94 veth56f1877 veth74bb940 vethf828a0c virbr0 virbr0-nic
   em1
9.  Do you want to optimize NIC queue settings?
   Answer yes to enable network card optimization; this improve performance. Answer no to skip this optimization.
   yes
   => Setting parameters on /etc/sysconfig/scylla-server
10. Do you want to setup IO configuration?
    Answer yes to let iotune study what are your disks IO profile and adapt Scylla to it. Answer no to skip this action.
    yes

ScyllaDB setup finished.
Please restart machine before using ScyllaDB, since you have changed boot parameters.

**Comment by avikivity** [comment]
Can you check what those threads are doing?

    perf top

or

    perf top -t <pid of one of these processes>

**Comment by euclid-geometry** [comment]
15.06%  [kernel]  [k] __bufio_new
   7.53%  [kernel]  [k] lower_bound
   6.74%  [kernel]  [k] mutex_lock
   6.68%  [kernel]  [k] mutex_unlock
   6.38%  [kernel]  [k] _raw_spin_lock
   3.65%  [kernel]  [k] ro_node
   3.49%  [kernel]  [k] __del_holder
   3.30%  [kernel]  [k] _raw_spin_lock_irqsave
   3.12%  [kernel]  [k] dm_btree_lookup
   2.99%  [kernel]  [k] dm_bm_read_lock
   2.94%  [kernel]  [k] __relink_lru
   2.68%  [kernel]  [k] _raw_spin_unlock_irqrestore
   2.39%  [kernel]  [k] new_read
   2.34%  [kernel]  [k] __add_holder
   2.09%  [kernel]  [k] __wake_up
   1.68%  [kernel]  [k] blk_flush_plug_list
   1.64%  [kernel]  [k] dm_bufio_release
   1.63%  [kernel]  [k] ro_step
   1.62%  [kernel]  [k] dm_block_data
   1.36%  [kernel]  [k] __flush_write_list
   1.27%  [kernel]  [k] memcpy
   1.26%  [kernel]  [k] dm_bufio_get_block_data
   1.18%  [kernel]  [k] dm_tm_read_lock
   1.16%  [kernel]  [k] dm_bm_unlock
   1.15%  [kernel]  [k] _cond_resched
   1.10%  [kernel]  [k] __wake_up_common
   1.09%  [kernel]  [k] __check_holder
   0.98%  [kernel]  [k] bl_up_read
   0.90%  [kernel]  [k] __list_add
   0.84%  [kernel]  [k] down_read
   0.83%  [kernel]  [k] dm_bm_validate_buffer.isra.2
   0.75%  [kernel]  [k] up_read
   0.74%  [kernel]  [k] dm_bufio_get_aux_data
   0.74%  [kernel]  [k] blk_start_plug
   0.73%  [kernel]  [k] __list_del_entry
   0.66%  [kernel]  [k] dm_bufio_read
   0.65%  [kernel]  [k] blk_finish_plug
   0.60%  [kernel]  [k] _raw_spin_unlock
   0.59%  [kernel]  [k] exit_ro_spine
   0.48%  [kernel]  [k] dm_thin_find_block
   0.41%  [kernel]  [k] dm_tm_unlock
   0.26%  [kernel]  [k] memmove
   0.24%  [kernel]  [k] sm_ll_lookup_bitmap
   0.14%  [kernel]  [k] dm_tm_shadow_block
   0.14%  [kernel]  [k] btree_insert_raw
   0.13%  [kernel]  [k] dm_bufio_mark_buffer_dirty
   0.13%  [kernel]  [k] dm_thin_find_mapped_range
   0.12%  [kernel]  [k] ro_pop
   0.11%  [kernel]  [k] init_ro_spine
   0.09%  [kernel]  [k] sm_lookup_bitmap
   0.09%  [kernel]  [k] dm_bm_write_lock
   0.09%  [kernel]  [k] sm_metadata_count_is_more_than_one
   0.07%  [kernel]  [k] bl_down_write
   0.07%  [kernel]  [k] sm_ll_mutate
   0.06%  [kernel]  [k] dm_btree_remove_leaves
   0.05%  [kernel]  [k] metadata_ll_load_ie

**Comment by avikivity** [comment]
It looks like a kernel bug. What kernel version are you using?

Please try

    echo 1 > /proc/sys/kernel/sysrq
    echo 9 > /proc/sysrq-trigger
    echo l > /proc/sysrq-trigger

and attach the output of `dmesg`.

**Comment by euclid-geometry** [comment]
Before test of scylla, my system has been used for 2 years and this problem doesn't happen.
Immediately after test of scylla, that problem occurred. 
So I am thinking that is due to scylla test.
Anyway thank you for your help.

---------
[1]. uname -r
3.10.0-327.4.5.el7.x86_64

[2]. output of dmesg
Output of dmesg is too long so I attach that file here.
[dmesg.txt](https://github.com/scylladb/scylla/files/481439/dmesg.txt)

**Comment by dorlaor** [comment]
On Mon, Sep 19, 2016 at 6:17 PM, euclid-geometry <notifications@github.com>
wrote:

> Before test of scylla, my system has been used for 2 years and this
> problem doesn't happen.
> Immediately after test of scylla, that problem occurred.
> So I am thinking that is due to scylla test.
>
The kernel bug was triggered due to Scylla execution


> Anyway thank you for your help.
> ------------------------------
>
> [1]. uname -r
> 3.10.0-327.4.5.el7.x86_64
>
There is a bit newer kernel from Red Hat. Still it may not be the root cause


> [2]. output of dmesg
> Output of dmesg is too long so I attach that file here.
> dmesg.txt <https://github.com/scylladb/scylla/files/481439/dmesg.txt>
>
Do you know which process is the one that SElinux keeps on reporting about?
In addition, I see an ext4 mount, Scylla prefers XFS but it still not they
problem.

**Comment by euclid-geometry** [comment]
I cannot use my system.
Is there any way to solve this problem?

Please Help!

**Comment by dorlaor** [comment]
Please check my previous comments. You're not the first nor last to hit
kworker issue:
http://askubuntu.com/questions/33640/kworker-what-is-it-and-why-is-it-hogging-so-much-cpu
It's a kernel bug and you'll have to reboot and to upgrade the system. We
haven't seen
the problem elsewhere thought.
