### ISSUE TITLE
[master] nodetool command times out

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#1665]
_Installation details_
Scylla version (or git commit hash):
scylla: c220c676c813181aa1daaa6aebdc6679b5cc1f59
scylla-jmx: c07f5c034fd306f23c793ed3475cef4559722c2c
scylla-tools-java: 1a55ef35120413341dafb92049c4007494833a11
Cluster size: CCM based cluster
OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora 24 (development machine)

Trying the latest scylla master, any nodetool commands directed to a node time out.

```
ccm node1 status
Traceback (most recent call last):
  File "/home/lmr/Code/scylla-dtest/../scylla-ccm/ccm", line 74, in <module>
    cmd.run()
  File "/home/lmr/Code/scylla-ccm/ccmlib/cmds/node_cmds.py", line 252, in run
    stdout, stderr = self.node.nodetool(self.nodetool_cmd + " " + " ".join((self.args[1:])))
  File "/home/lmr/Code/scylla-ccm/ccmlib/node.py", line 693, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
ccmlib.node.NodetoolError: Nodetool command '/home/lmr/Code/scylla/resources/cassandra/bin/nodetool -h localhost -p 7100 status' failed; exit status: 1; stderr: nodetool: Failed to connect to 'localhost:7100' - ConnectException: 'Connection refused'.
```

cqlsh works fine, though.

```
ccm node1 cqlsh
Connected to scylla-1 at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 2.1.8 | CQL spec 3.2.1 | Native protocol v3]
Use HELP for help.
cqlsh> 
```

I did get a tcpdump of the communication, you can see that attached [master-issue-jmx.pcap.zip](https://github.com/scylladb/scylla/files/470869/master-issue-jmx.pcap.zip)

**Comment by asias** [comment]
Check if the scylla-jmx server is up.  Check the jmx port, the default port is 7199. In ccm the first node is using 7100, the second is using 7200 and so on. netstat -natlp|grep 7100.

**Comment by lmr** [comment]
The processes seem to be up:

**Comment by lmr** [comment]
lmr       5817  1765  3 Sep13 pts/3    00:23:00 /home/lmr/.ccm/scylla-1/node1/bin/scylla --options-file /home/lmr/.ccm/scylla-1/node1/conf/scylla.yaml --api-address 127.0.0.1 --prometheus-address 127.0.0.1 --collectd-hostname titan.node1 --developer-mode true --smp 1 --memory 512M --default-log-level info --collectd 0 --cpuset 0
    lmr       5818  1765  0 Sep13 pts/3    00:00:00 tee -a /home/lmr/.ccm/scylla-1/node1/logs/system.log
    lmr       5836  1765  0 Sep13 pts/3    00:00:00 /bin/bash -x /home/lmr/.ccm/scylla-1/node1/bin/run_jmx.sh /home/lmr/.ccm/scylla-1/node1 --api-address 127.0.0.1 --prometheus-address 127.0.0.1 --collectd-hostname titan.node1 --developer-mode true --smp 1 --memory 512M --default-log-level info --collectd 0 --cpuset 0
    lmr       5837  5836  0 Sep13 pts/3    00:00:50 /home/lmr/.ccm/scylla-1/node1/bin//symlinks/scylla-jmx -Dapiaddress=127.0.0.1 -Djavax.management.builder.initial=com.scylladb.jmx.utils.APIBuilder -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7100 -Dcom.sun.management.jmxremote.rmi.port=7100 -Dcom.sun.management.jmxremote.local.only=false -Xmx256m -XX:+UseSerialGC -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -jar /home/lmr/.ccm/scylla-1/node1/bin//scylla-jmx-1.0.jar
    lmr       5838  5836  0 Sep13 pts/3    00:00:00 tee -a /home/lmr/.ccm/scylla-1/node1/logs/system.log.jmx

    netstat -natlp|grep 7100
    (Not all processes could be identified, non-owned process info
     will not be shown, you would have to be root to see it all.)
    tcp6       0      0 :::7100                 :::*                    LISTEN      5837/scylla-jmx

**Comment by tzach** [comment]
@lmr is this issue only happened in Fedora?

**Comment by slivne** [comment]
seems related to scylladb/scylla-jmx#34 - lets test after it is resolved.

**Comment by lmr** [comment]
https://github.com/scylladb/scylla-jmx/issues/34 was fixed, and now sct also has provisions to avoid this problem by waiting the JMX service to be available. I'm closing this issue.
