### ISSUE TITLE
run house-keeping as part of scylla-setup

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1666]
Currently house-keeping notify the user if there is a newer version when Scylla is already running.
It would be useful to do the same on setup, allowing the user to upgrade **before** starting Scylla service.

**Comment by amnonh** [comment]
This can be closed with commit 5e3ab32365f08096ad158fa4cb59494a3f401e59

**Comment by slivne** [comment]
have we changed sylla_setup to check if there is a new version ?

**Comment by amnonh** [comment]
The setup commit is https://github.com/scylladb/scylla/commit/b305d92a65613bd107ec0eadf42297b6956e22a6#diff-5e299adcf6d654cb5e82f74543585d78
