### ISSUE TITLE
Scylla aborts when quering with contradicting clustering column restrictions

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1670]
*Installation details*
Scylla version (or git commit hash): 1.2, 1.3

Already fixed in master.

Affects queries like the one below, where `k` is partition key and `ck` is a clustering column:

`SELECT * FROM test WHERE k = 0 AND ck < 1 and ck > 2`

**Comment by tgrabiec** [comment]
Fixed in master by b1f9688432bff78ccbffe1ad02d8a9f0812b46a2

**Comment by tzach** [comment]
@tgrabiec @pdziepak can we close this issue?

**Comment by tzach** [comment]
@tgrabiec is this fix part of 1.4?

**Comment by tgrabiec** [comment]
Yes
