### ISSUE TITLE
scylla_setup: RAID and XFS asks to select disks from an empty list

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1673]
*Installation details*
Scylla version (or git commit hash): 1.3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16
Tested on on Ubuntu 16 AMI, ami-746aba14, us-west-2 Oregonm with defualt storage,  m3.medium

```
Do you want to setup RAID and XFS?
It is recommended to use RAID0 and XFS for Scylla data. If you select yes, you will be prompt to choose which disks to use for Scylla data. Selected disks will be formatted in the process.
[YES/no]
Please select disks from following list: 
type 'done' to finish selection. selected: 
```

* no list to select from, no need to present the question
* should be `Please select disks from *the* following list:`

**Comment by tzach** [comment]
@syuu1228 can you please take a look?

**Comment by syuu1228** [comment]
@tzach I suppose we probably should print message something like "No free disks detected, abort RAID setup" then continue to next question, right?

**Comment by tzach** [comment]
Looks good.

**Comment by LulunaYu** [comment]
Hi @tzach What should I do if I want to set up  RAID and XFS while no free disks exists ? Thanks.

**Comment by tzach** [comment]
@LulunaYu not sure I understand. Do you mean you want to dormant an existing disk with XFS?
Note it will delete all the data from this disk
