### ISSUE TITLE
change streaming/repair to read information from on disk sstables 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1682]
scylla currently:
-  streams/repairs based on memtable/cache and sstable information. 
- ongoing writes are added to the info that will be streamed (based if they belong to partition ranges that have not been sent)

this has two drawbacks:
- there is no grantee that we will advance - ongoing writes can write a pace similar/higher then the streaming pace
- we are re sending information that was distributed already 

we will change this and send information of the persisted sstables

**Comment by tgrabiec** [comment]
If streaming/repair is assumed to send all prior writes, which I think it is, then we should also include (current) memtables. They may contain data which was written long ago and not present in sstables.

We could have a non-cache-populating readers which take a snapshot of data sources, like regular reader do, but never update that snapshot (don't see new sstables/memtables). So they see prior writes and a bounded amount of new writes (up to what memtables accumulate).

**Comment by slivne** [comment]
another option is todo "nodetool flush" and then do streaming/repair

streaming/repair can take a long time - "locking" large parts of memory
till they end may be expensive.

**Comment by tgrabiec** [comment]
Any scanning read can do this. I think we need a generic solution for this. We already have solution for this implemented - when memtable is flushed, all active readers fall back to reading from its sstable.
