### ISSUE TITLE
cqlsh: Can only select at most 100 rows when filtering by clustering key

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#1684]
*Installation details*
Scylla version (or git commit hash): 906250dcbdbbee26c5892381ace90ec4d5e6223a

Reproducer:

```
$ echo "create keyspace ks with replication = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };" | bin/cqlsh
$ echo "create table ks.cf(p text, c1 text, c2 text, v int, primary key (p, c1, c2));" |  bin/cqlsh
$ for i in `seq 1 1000`; do echo  "insert into ks.cf (p, c1, c2, v) values ('key1', 'a', '$i', 0);" ; done | bin/cqlsh
$ echo "select count(*) from ks.cf;" |  bin/cqlsh

 count
-------
  1000

(1 rows)
$ echo "select count(*) from ks.cf where c1 = 'a' allow filtering;" |  bin/cqlsh

 count
-------
   100

(1 rows)
```

Cassandra returns the correct count.

**Comment by slivne** [comment]
Is this related to another issue ?

To verify that I understand the issue we do not enforce the "100 row limit rule" when allow filtering is added

**Comment by duarten** [comment]
It's unrelated to other issues.

I'm querying a table with `allow filtering` and I'm only getting back 100 rows. Is this expected behavior? Cassandra returns everything.

**Comment by slivne** [comment]
Its a bug - yet I expect cassandra would also limit the amount of rows it
allows under allow filtering

**Comment by duarten** [comment]
It seems this happens whenever we filter a clustering key, regardless of `allow filtering`. The following doesn't return the correct result either:

```
$ echo "select count(*) from ks.cf where p = 'key1' and c1 = 'a';" |  bin/cqlsh

 count
-------
   100

(1 rows)
```

**Comment by duarten** [comment]
100 is the default `page_size` when using cqlsh, and paging is on by default. 

```
echo "paging off; select count(*) from ks.cf where p = 'key1' and c1 = 'a';" |  bin/cqlsh
Disabled Query paging.

 count
-------
  1000

(1 rows)
```
This returns the correct value. So it seems our paging support is buggy?

**Comment by slivne** [comment]
That changes the priority ....

**Comment by pdziepak** [comment]
Surprise, surprise, incorrect handling of clustering row ranges in paging code. The code assumes that ck range [a, a] is singular and contains only one row.

**Comment by duarten** [comment]
Yikes :/ I see `fetch_page()` is using `clustering_key_prefix::less_compare`.

**Comment by pdziepak** [comment]
Yes, the proper solution requires #1446 fixed. Looks like a workaround would have to do for now.
