### ISSUE TITLE
raft topology: unclean shutdown of a joining node after a failed bootstrap or replace

### ISSUE THREAD

**Issue by patjed41** [scylladb/scylla#16871]
When the bootstrap and replace topology operations fail, the topology coordinator starts the rollback, which moves the joining (or replacing) node to the `left_token_ring` state. Then, `left_token_ring` handler in `handle_node_transition` sends the `shutdown` command to the joining node. If this node is alive, it should cleanly shut down after receiving this message. However, it crashes on `auto& raft_server = _group0->group0_server();` in `storage_service::raft_topology_cmd_handler`:

```
TRACE 2024-01-18 14:58:03,761 [shard 0: gms] storage_service - raft topology: topology cmd rpc shutdown is called
ERROR 2024-01-18 14:58:03,761 [shard 0: gms] storage_service - raft topology: raft_topology_cmd failed with: service::raft_group_not_found (Raft group 96413200-b609-11ee-b6e6-bf3e92ec22a8 not found)
```

Moreover, the joining node doesn't even expect the `shutdown` command:

```cpp
case raft_topology_cmd::command::shutdown:
    if (_shutdown_request_promise) {
        std::exchange(_shutdown_request_promise, std::nullopt)->set_value();
    } else {
        slogger.warn("raft topology: got shutdown request while not decommissioning");
    }
    break;
```

The `shutdown` command was added only to shut down a decommissioning node (by setting `_shutdown_request_promise`). Later, rollback started to use the `left_token_ring` state in the case of a failed bootstrap or replace. We should adjust the `shutdown` command handler, so that a joining node shuts down cleanly.

Another issue is in `handle_node_transition`:
```cpp
case node_state::left_token_ring:
    ...
    auto str = ::format("finished decommissioning node {}", node.id);
    co_await update_topology_state(take_guard(std::move(node)), {builder.build()}, std::move(str));
```
We should use other reason than "finished decommissioning" in the case of a failed bootstrap or replace. To fix this, we need a way to distinguish a finished decommission from a failed bootstrap or replace. One way of achieving it is adding a new `node_state` for a failed bootstrap or replace.

**Comment by kbr-scylla** [comment]
cc @gleb-cloudius

**Comment by gleb-cloudius** [comment]
`raft_topology_cmd::command::shutdown` was a cosmetic issue which no longer exist in master since there is no longer shutdown rpc. I do not see `storage_service - raft topology: raft_topology_cmd failed with: service::raft_group_not_found ` happening and I do not see how it can happen since we rollback only from states at which the bootstrapping node should be the part of the cluster already.
