### ISSUE TITLE
Scylla performance versions 1.2 & 1.3

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#1687]
Scylla performance track versions 1.2 and 1.3

Steps to create the load using ansible:
https://github.com/scylladb/cassandra-test-and-deploy
Cluster size: 3 i2.8xlarge
Loaders - 14 c4.large

Scylla
./ec2-setup-scylla.sh -e "cluster_nodes=3" -e "instance_type=i2.8xlarge" -e "prometheus_client=true"
Loader
./ec2-setup-loadgen.sh -e "load_nodes=14" -e "instance_type=c4.large"

Connect nodes to monitor
Run load
./ec2-stress.sh 1 -e "server=Scylla" -e "stress_options='-errors ignore -schema \"replication(factor=3)\" keyspace=\"mykeyspace\"'" -e "load_name=scylla_write" -e "threads=2500" -e "command_options='cl=QUORUM n=10000000000 -mode native cql3 -pop seq=1..10000000000'" 
Issue reproduce after 2-3 hours

Not using ansible 
Setup the cluster 
Run cassandra stress

cassandra-stress write no-warmup cl=QUORUM n=10000000000 -mode native cql3 -pop seq=1..10000000000 -node 172.30.0.11,172.30.0.8,172.30.0.9 -rate threads=2500 -errors ignore -schema replication(factor=3) keyspace=mykeyspace

**Comment by nirmaayan** [comment]
1.2  
![load tr_write_5h](https://cloud.githubusercontent.com/assets/18263247/18737622/37711754-809c-11e6-9349-e78d2191e06e.png)

**Comment by nirmaayan** [comment]
1.3 
![1 3](https://cloud.githubusercontent.com/assets/18263247/18737793/5d48b976-809e-11e6-8a9c-4e20d0a27a98.png)

**Comment by slivne** [comment]
1.4 includes some fixes of performance regressions that were introduced in 1.3, 1.4.1/1.5 will have additional fixes that will improve the performance.

Closing this issue as we are tracking a similar test in performance regression.
