### ISSUE TITLE
Testing - Edge testing of system

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#169]
We need to  stress out the system to verify we stand out different failures

So we need to create a list of tests and start testing out what happens in edge cases (e.g. disk ran out of space, system is overloaded, etc.)

some of this will be simple to test - others may be undoable at this pint

**Comment by slivne** [comment]
@glommer - I think you at least tested some of this - can you please update the issue accordingly

**Comment by glommer** [comment]
I didn't test any of the parameters Dor mentioned in his comments. From edge conditions, what I did test was behavior under saturated disk, and didn't find any issue. @raphaelsc tested disk full conditions.

All my other tests were performance tests. For instance, I did cells per partition, but stopped at 128 cells.

**Comment by dorlaor** [comment]
On Thu, Oct 1, 2015 at 3:29 PM, Glauber Costa <notifications@github.com>
wrote:

> I didn't test any of the parameters Dor mentioned in his comments. From
> edge conditions, what I did test was behavior under saturated disk, and
> didn't find any issue. @raphaelsc <https://github.com/raphaelsc> tested
> disk full conditions.
>
> All my other tests were performance tests. For instance, I did cells per
> partition, but stopped at 128 cells.
>

We should add as many as possible to our regression suite. Either under
DTest and/or unit tests

**Comment by tzach** [comment]
Testing Scylla max capacity per node is particularly interesting.
At the least 10TB per node should be tested.

**Comment by dorlaor** [comment]
On Wed, Oct 7, 2015 at 10:54 AM, Tzach Livyatan <notifications@github.com>
wrote:

> Testing Scylla max capacity per node is particularly interesting.
> At the least 10TB per node should be tested.
>
Agreed. It deserves an independant #issue.
Also max number of nodes, let's assume no one will need more than 100 for
the near term.

**Comment by tzach** [comment]
> > On Wed, Oct 7, 2015 at 10:54 AM, Tzach Livyatan <notifications@github.com> wrote:
> > Testing Scylla max capacity per node is particularly interesting.
> > At the least 10TB per node should be tested.

> Agreed. It deserves an independant #issue.

#448 

> Also max number of nodes, let's assume no one will need more than 100 for
> the near term.

#449

**Comment by tzach** [comment]
Covered by https://github.com/cloudius-systems/scylla-dtest/issues
