### ISSUE TITLE
Leveled strategy may take more than 1ms when working with thousands of tables

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1696]
Checked that leveled strategy may hold cpu for more than 1ms if dealing with thousands of sstables, and that may result in requests being timed out. 

I found this by creating a test [1] that splits 1120 fake sstables in levels 0 to 3 (based on limit of each level), and measure the time for leveled strategy to return a list of candidates. It's always taking more than 1ms on my machine.
[1] https://gist.github.com/raphaelsc/89d502037d918b4298f9ac21cdaf9e02

This slowness happens because the strategy is creating one list for each level and checking for overlapping in levels > 0 _every time_ that it's asked to get a list of sstables to be compacted. I think that performance could be improved by checking overlap only once, for example, when loading column family. There's really no need to check overlap multiple times. New sstables are added to level 0, sstables loaded by refresh have their level changed to 0.

**Comment by avikivity** [comment]
We could specialize the data structure in sstable_set to hold a separate list for each level, for leveled compaction strategy.

**Comment by slivne** [comment]
Recreating the list every time seems to be wasteful - sstables should not change their level after creation.

I do understand that we need to select a level to compact and potentially file(s) that will be compacted into that level. In case of file from level n-1 that is compacted with files from level n 

I don't understand why we need to check overlap between levels when selecting sstables to compact ?

If I am not mistaken we have enhanced leveled to use an interval map for finding the sstables for the read path we should be able to use the same structrue or enhance it a bit and figure out which sstables should be compacted.

**Comment by raphaelsc** [comment]
On Sun, Sep 25, 2016 at 8:42 AM, Shlomi Livne <notifications@github.com>
wrote:

> Recreating the list every time seems to be wasteful - sstables should not
> change their level after creation.
>
> I do understand that we need to select a level to compact and potentially
> file(s) that will be compacted into that level. In case of file from level
> n-1 that is compacted with files from level n
>
> I don't understand why we need to check overlap between levels when
> selecting sstables to compact ?
>
It's not actually overlap between levels, but in the same level. anyway,
your complain makes sense, and that's what I want to achieve here too. I
think we only need to do that once, when initializing the strategy.


> If I am not mistaken we have enhanced leveled to use an interval map for
> finding the sstables for the read path we should be able to use the same
> structrue or enhance it a bit and figure out which sstables should be
> compacted.
>

The interval map helps quickly finding sstables in a given interval. It
will not help the strategy which needs to quickly find all L0 sstables for
example. Avi's suggestion "We could specialize the data structure in
sstable_set to hold a separate list for each level, for leveled compaction
strategy." is what we need, I think.

**Comment by slivne** [comment]
AFAIK in leveled compaction there are two types of compactions:

   1. In Level0 if theere are to many files and then we compact multiple
   files to a new Level 0 file - just much bigger (for this we simply need a
   list of all level 0 files) - there may be logic to select the files in this
   level 0 that I am missing.
   2. Other levels - we take a file from Level N and compact it into Level
   N+1 (usually 1 file from Level N compacted with 10 files from Level N+1).
   The files from Level N+1 all intersect with the range of the file of level
   N.
      1. All the files in Level N+1  do not have overlap and can be ordered
      based on their keys
      2. Once we find the first file in Level N+1 (using the minimal key of
      the file from level N) - we can add it and all the following
files till we
      reach a file that has a minimal key that is greater then the
maximal key of
      the file from Level N
      3. To find the first file in Level N+1 we can use the interval map
      that we created (given its for levels >= 1 - leveld compaction does not
      have a lot of levels)

In this manner the computation of what files to compact is not O(# of
sstables) its much less.

**Comment by raphaelsc** [comment]
On Mon, Sep 26, 2016 at 4:13 PM, Shlomi Livne <notifications@github.com>
wrote:

> AFAIK in leveled compaction there are two types of compactions:
>
> 1. In Level0 if theere are to many files and then we compact multiple
> files to a new Level 0 file - just much bigger (for this we simply need a
> list of all level 0 files) - there may be logic to select the files in this
> level 0 that I am missing.
>

A per-level list. We just compact L0 into L0 if number of sstables goes
beyond a threshold (usually 32). Otherwise, we pick N L0 sstables and
compact them into overlapping L1.


> 2. Other levels - we take a file from Level N and compact it into Level
> N+1 (usually 1 file from Level N compacted with 10 files from Level N+1).
>

No, with overlapping from level N+1.


> The files from Level N+1 all intersect with the range of the file of level
> N.
>

"The files from Level N+1", not all of them, but the ones we choose to
compact.


> 1. All the files in Level N+1 do not have overlap and can be ordered
> based on their keys
>

True.


> 2. Once we find the first file in Level N+1 (using the minimal key of
> the file from level N) - we can add it and all the following
> files till we
> reach a file that has a minimal key that is greater then the
> maximal key of
> the file from Level N


Interval map stores a set for each interval, meaning that the same sstable
may be stored in more than one set. What we could possibly do is to get all
sstables that overlap with key range of sstable(s) from level N ( we
already have code to get unique sstables that overlap with a key range ),
and later remove all sstables from the received set that don't belong to
level N+1, using std::remove_if it will be O(n), where n is size of
received set.

Or as Shlomi suggested, we could actually iterate through intervals that
overlap with a specified key range and add level N+1 sstables to an
unordered set (to avoid duplication).

@avikivity: what do you think?

**Comment by slivne** [comment]
@raphaelsc any update on this

**Comment by slivne** [comment]
@raphaelsc - we changed LCS and now have a list of L0 - is there additional work we need todo for this item (did we resolve the major issue - and now its good enough ?). 

Is there anything else we need todo here ?

**Comment by raphaelsc** [comment]
On Thu, May 4, 2017 at 7:24 AM, Shlomi Livne <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> - we changed LCS and now have a
> list of L0 - is there additional work we need todo for this item (did we
> resolve the major issue - and now its good enough ?).
>
> Is there anything else we need todo here ?
>

the problem was that we were checking for overlapping on every level every
time strategy was called, but there's still room for improvement because we
are building a list for every level from scratch, which is only a O(N)
operation. Strategy is called at interval of a compaction, so I think it
should be fine now.

**Comment by slivne** [comment]
@raphaelsc - so can I close this ?

**Comment by raphaelsc** [comment]
@slivne: i think so. I'm closing it myself.
