### ISSUE TITLE
gdb segment fault

### ISSUE THREAD

**Issue by ZoneMayor** [scylladb/scylla#1697]
*Installation details*
Scylla version (or git commit hash): 1.3.0-20160824.ec3ace5
Cluster size:1
OS (RHEL/CentOS/Ubuntu/AWS AMI):RHEL
Gcc version: 4.8.5
Gdb version: 7.6.1-80.el7
This is related to https://github.com/scylladb/scylla/issues/1589;

When I try to debug the coredump file with command:
```gdb /usr/bin/scylla core.scylla.983.8d14988b1ad14e13853c5d085ba90e0e.169476.1474687314000000```

I get following error message:
```Reading symbols from /usr/lib/debug/usr/scylla.debug```

Then I installed scylla-gdb(gdb version **7.10.1-30.el7.centos**), then I get 
```Reading symbols from /usr/bin/scylla...Reading symbols from /usr/lib/debug/usr/bin/scylla.debug...../../gdb/cp-support.c:1595: demangler-warning: unable to demangle '_ZN8futurizeI13frozen_schemaE5applyIRZN7seastar7shardedIN7service13storage_proxyEE9invoke_onIZZNS6_22init_messaging_serviceEvENKUljN5utils4UUIDEE5_clEjSA_EUlOT_E_6futureIJS0_EEEET0_jSD_EUlvE_JEEESG_SD_DpOT0_' (demangler failed with signal 11)
Attempting to dump core.
../../gdb/cp-support.c:1608: demangler-warning: unable to demangle '_ZN8futurizeI13frozen_schemaE5applyIRZN7seastar7shardedIN7service13storage_proxyEE9invoke_onIZZNS6_22init_messaging_serviceEvENKUljN5utils4UUIDEE5_clEjSA_EUlOT_E_6futureIJS0_EEEET0_jSD_EUlvE_JEEESG_SD_DpOT0_' (demangler failed with signal 11)```

It seems that this is a gdb bug;
Any ideas or culprits about this?
What is the proper version of gdb for debug?

**Comment by avikivity** [comment]
Try https://s3.amazonaws.com/scylla-gdb/scylla-gdb-7.10.1-30.el7.centos.x86_64.rpm; the binary is in /opt/scylla/bin.

**Comment by ZoneMayor** [comment]
@avikivity 
Thanks for reply;
I installed  https://s3.amazonaws.com/scylla-gdb/scylla-gdb-7.10.1-30.el7.centos.x86_64.rpm;
Try to debug the coredump with command:
```/opt/scylladb/bin/gdb /usr/bin/scylla core.scylla.983.8d14988b1ad14e13853c5d085ba90e0e.169476.1474687314000000```

But still get ```Reading symbols from /usr/bin/scylla...Reading symbols from /usr/lib/debug/usr/bin/scylla.debug...../../gdb/cp-support.c:1595: demangler-warning: unable to demangle '_ZN8futurizeI13frozen_schemaE5applyIRZN7seastar7shardedIN7service13storage_proxyEE9invoke_onIZZNS6_22init_messaging_serviceEvENKUljN5utils4UUIDEE5_clEjSA_EUlOT_E_6futureIJS0_EEEET0_jSD_EUlvE_JEEESG_SD_DpOT0_' (demangler failed with signal 11)```;

Could you give me some advice? Thanks a log.

**Comment by ZoneMayor** [comment]
I use command:
```set demangle-style none```
I can stacktrack now, will update #1589 now

**Comment by avikivity** [comment]
Ignore the warning; if gdb asks the whether to crash, say N.
