### ISSUE TITLE
add scylla_dev_mode_setup to default path 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1702]
*Installation details*
Scylla version (or git commit hash): 1.3.1

Currently, scylla_dev_mode_setup and other scripts are placed under `/usr/lib/scylla/`
while other scripts like scylla_setup are under `/usr/sbin/`
This makes scylla_dev_mode_setup out of teh default path and hard to find.
It would be better if scylla_dev_mode_setup would be in the default path

**Comment by syuu1228** [comment]
Posted "[PATCH scylla] dist/common/sbin: add scylla_cpuset_setup and scylla_dev_mode_setup to /usr/sbin" for this, please review.
