### ISSUE TITLE
Failure during compaction.

### ISSUE THREAD

**Issue by ZoneMayor** [scylladb/scylla#1706]
*Installation details*
Scylla version (or git commit hash):1.3.0
Cluster size:2
OS (RHEL/CentOS/Ubuntu/AWS AMI):CentOS7

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets= cores= hyperthreading= memory=60G
Disks: (SSD/HDD, count) SSD 1

> #0  0x00007f39eb46c5f7 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007f39eb46dce8 in __GI_abort () at abort.c:90
#2  0x00007f39eb465566 in __assert_fail_base (fmt=0x7f39eb5b5ce8 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", assertion=assertion@entry=0x17c95bd "nr_pages", file=file@entry=0x17c95ae "core/memory.cc", line=line@entry=377,
    function=function@entry=0x17c98e0 <memory::cpu_pages::free_span_no_merge(unsigned int, unsigned int)::__PRETTY_FUNCTION__> "void memory::cpu_pages::free_span_no_merge(uint32_t, uint32_t)") at assert.c:92
#3  0x00007f39eb465612 in __GI___assert_fail (assertion=assertion@entry=0x17c95bd "nr_pages", file=file@entry=0x17c95ae "core/memory.cc", line=line@entry=377,
    function=function@entry=0x17c98e0 <memory::cpu_pages::free_span_no_merge(unsigned int, unsigned int)::__PRETTY_FUNCTION__> "void memory::cpu_pages::free_span_no_merge(uint32_t, uint32_t)") at assert.c:101
#4  0x000000000055365d in memory::cpu_pages::free_span_no_merge (this=<optimized out>, span_start=<optimized out>, nr_pages=<optimized out>) at core/memory.cc:377
#5  0x0000000000929168 in standard_allocation_strategy::free (obj=0x608018fcaea8, this=0x21fcd80 <standard_allocation_strategy_instance>) at utils/allocation_strategy.hh:139
#6  allocation_strategy::destroy<blob_storage> (obj=0x608018fcaea8, this=0x21fcd80 <standard_allocation_strategy_instance>) at utils/allocation_strategy.hh:119
#7  managed_bytes::free_chain (p=0x608018fcaea8, this=<optimized out>) at utils/managed_bytes.hh:120
#8  0x00000000009299b6 in managed_bytes::~managed_bytes (this=<optimized out>, __in_chrg=<optimized out>) at utils/managed_bytes.hh:207
#9  atomic_cell_or_collection::~atomic_cell_or_collection (this=<optimized out>, __in_chrg=<optimized out>) at atomic_cell_or_collection.hh:32
#10 managed_vector<atomic_cell_or_collection, 5u, unsigned int>::pop_back (this=<optimized out>, this=<optimized out>) at utils/managed_vector.hh:213
#11 managed_vector<atomic_cell_or_collection, 5u, unsigned int>::clear (this=<optimized out>) at utils/managed_vector.hh:170
#12 managed_vector<atomic_cell_or_collection, 5u, unsigned int>::clear_and_release (this=<optimized out>) at utils/managed_vector.hh:77
#13 managed_vector<atomic_cell_or_collection, 5u, unsigned int>::~managed_vector (this=<optimized out>, __in_chrg=<optimized out>) at utils/managed_vector.hh:127
#14 row::vector_storage::~vector_storage (this=<optimized out>, __in_chrg=<optimized out>) at mutation_partition.hh:105
#15 row::~row (this=0x608005a69a20, __in_chrg=<optimized out>) at mutation_partition.cc:1314
#16 0x000000000093e0fd in deletable_row::~deletable_row (this=0x608005a69a00, __in_chrg=<optimized out>) at mutation_partition.hh:402
#17 rows_entry::~rows_entry (this=0x608005a699d0, __in_chrg=<optimized out>) at mutation_partition.hh:439
#18 0x0000000000929e0c in allocation_strategy::destroy<rows_entry> (obj=0x608005a699d0, this=<optimized out>) at utils/allocation_strategy.hh:118
#19 auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}::operator()(rows_entry*) const (obj=0x608005a699d0, __closure=<optimized out>) at utils/allocation_strategy.hh:166
#20 boost::intrusive::detail::node_disposer<auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}, boost::intrusive::mhtraits<rows_entry, boost::intrusive::set_member_hook<void, void, void, void>, &rows_entry::_link>, (boost::intrusive::algo_types)5>::operator()(boost::intrusive::rbtree_node<void*>* const&) (p=<synthetic pointer>, this=<synthetic pointer>) at /opt/scylladb/include/boost/intrusive/detail/node_cloner_disposer.hpp:109
#21 boost::intrusive::bstree_algorithms<boost::intrusive::rbtree_node_traits<void*, false> >::dispose_subtree<boost::intrusive::detail::node_disposer<auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}, boost::intrusive::mhtraits<rows_entry, boost::intrusive::set_member_hook<void, void, void, void>, &rows_entry::_link>, (boost::intrusive::algo_types)5> >(boost::intrusive::rbtree_node<void*>*, boost::intrusive::detail::node_disposer<auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}, boost::intrusive::mhtraits<rows_entry, boost::intrusive::set_member_hook<void, void, void, void>, &rows_entry::_link>, (boost::intrusive::algo_types)5>) (disposer=..., x=0x608005a699d0) at /opt/scylladb/include/boost/intrusive/bstree_algorithms.hpp:1955
#22 boost::intrusive::bstree_algorithms<boost::intrusive::rbtree_node_traits<void*, false> >::clear_and_dispose<boost::intrusive::detail::node_disposer<auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}, boost::intrusive::mhtraits<rows_entry, boost::intrusive::set_member_hook<void, void, void, void>, &rows_entry::_link>, (boost::intrusive::algo_types)5> >(boost::intrusive::rbtree_node<void*>* const&, boost::intrusive::detail::node_disposer<auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}, boost::intrusive::mhtraits<rows_entry, boost::intrusive::set_member_hook<void, void, void, void>, &rows_entry::_link>, (boost::intrusive::algo_types)5>) (disposer=..., header=<optimized out>) at /opt/scylladb/include/boost/intrusive/bstree_algorithms.hpp:614
#23 boost::intrusive::bstree_impl<boost::intrusive::mhtraits<rows_entry, boost::intrusive::set_member_hook<void, void, void, void>, &rows_entry::_link>, rows_entry::compare, unsigned long, true, (boost::intrusive::algo_types)5, void>::clear_and_dispose<auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}>(auto current_deleter<rows_entry>()::{lambda(rows_entry*)#1}) (disposer=..., this=0x608005a69968) at /opt/scylladb/include/boost/intrusive/bstree.hpp:1504
#24 mutation_partition::~mutation_partition (this=0x608005a698e8, __in_chrg=<optimized out>) at mutation_partition.cc:279
#25 0x00000000008d512d in partition_version::~partition_version (this=0x608005a698d0, __in_chrg=<optimized out>) at partition_version.cc:57
#26 0x00000000008d518f in allocation_strategy::destroy<partition_version> (obj=0x608005a698d0, this=<optimized out>) at utils/allocation_strategy.hh:118
#27 remove_or_mark_as_unique_owner (current=0x608005a698d0) at partition_version.cc:30
#28 0x00000000008d54ca in partition_snapshot::~partition_snapshot (this=0x608001226708, __in_chrg=<optimized out>) at partition_version.cc:68
#29 0x00000000008d7768 in lw_shared_ptr<partition_snapshot>::~lw_shared_ptr (this=0x6080cb8455b0, __in_chrg=<optimized out>) at /usr/src/debug/scylla-1.3.0/seastar/core/shared_ptr.hh:186
#30 partition_snapshot_reader::~partition_snapshot_reader (this=0x6080cb845500, __in_chrg=<optimized out>) at partition_version.cc:317
#31 0x00000000008d7af9 in partition_snapshot_reader::~partition_snapshot_reader (this=0x6080cb845500, __in_chrg=<optimized out>) at partition_version.cc:334
#32 0x00000000008d136e in std::default_delete<streamed_mutation::impl>::operator() (this=<optimized out>, __ptr=<optimized out>) at /opt/scylladb/include/c++/5.3.1/bits/unique_ptr.h:76
#33 std::unique_ptr<streamed_mutation::impl, std::default_delete<streamed_mutation::impl> >::~unique_ptr (this=<optimized out>, __in_chrg=<optimized out>) at /opt/scylladb/include/c++/5.3.1/bits/unique_ptr.h:236
#34 streamed_mutation::~streamed_mutation (this=<optimized out>, __in_chrg=<optimized out>) at streamed_mutation.hh:396
#35 std::_Destroy<streamed_mutation> (__pointer=<optimized out>) at /opt/scylladb/include/c++/5.3.1/bits/stl_construct.h:93
#36 std::_Destroy_aux<false>::__destroy<streamed_mutation*> (__last=<optimized out>, __first=0x608129035570) at /opt/scylladb/include/c++/5.3.1/bits/stl_construct.h:103
#37 std::_Destroy<streamed_mutation*> (__last=<optimized out>, __first=<optimized out>) at /opt/scylladb/include/c++/5.3.1/bits/stl_construct.h:126
#38 std::_Destroy<streamed_mutation*, streamed_mutation> (__last=0x608129035578, __first=<optimized out>) at /opt/scylladb/include/c++/5.3.1/bits/stl_construct.h:151
#39 std::vector<streamed_mutation, std::allocator<streamed_mutation> >::~vector (this=0x6080bfdadb70, __in_chrg=<optimized out>) at /opt/scylladb/include/c++/5.3.1/bits/stl_vector.h:424
#40 mutation_merger::~mutation_merger (this=0x6080bfdadb00, __in_chrg=<optimized out>) at streamed_mutation.cc:226
#41 mutation_merger::~mutation_merger (this=0x6080bfdadb00, __in_chrg=<optimized out>) at streamed_mutation.cc:226
#42 0x000000000094640a in std::default_delete<streamed_mutation::impl>::operator() (this=<optimized out>, __ptr=<optimized out>) at /opt/scylladb/include/c++/5.3.1/bits/unique_ptr.h:76
#43 std::unique_ptr<streamed_mutation::impl, std::default_delete<streamed_mutation::impl> >::~unique_ptr (this=0x608000a1d100, __in_chrg=<optimized out>) at /opt/scylladb/include/c++/5.3.1/bits/unique_ptr.h:236
#44 streamed_mutation::~streamed_mutation (this=0x608000a1d100, __in_chrg=<optimized out>) at streamed_mutation.hh:396
#45 std::experimental::fundamentals_v1::_Optional_base<streamed_mutation, true>::_M_destruct (this=0x608000a1d100) at /opt/scylladb/include/c++/5.3.1/experimental/optional:317
#46 std::experimental::fundamentals_v1::_Optional_base<streamed_mutation, true>::_M_reset (this=0x608000a1d100) at /opt/scylladb/include/c++/5.3.1/experimental/optional:325
#47 std::experimental::fundamentals_v1::optional<streamed_mutation>::emplace<streamed_mutation>(streamed_mutation&&) (this=0x608000a1d100) at /opt/scylladb/include/c++/5.3.1/experimental/optional:530
#48 _ZZZZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows0E27reconcilable_result_builderEEEDa15mutation_readerOT_bENKUlRS7_RT0_RT1_E_clIS6_S5_NSt12experimental15fundamentals_v18optionalI17streamed_mutationEEEEDaS9_SB_SD_ENKUlvE_clEvENKUlS7_E_clI18optimized_optionalISJ_EEEDaS7_ (smopt=..., __closure=<optimized out>) at mutation_reader.hh:270
---Type <return> to continue, or q <return> to quit---
#49 _ZN12apply_helperIZZZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows0E27reconcilable_result_builderEEEDa15mutation_readerOT_bENKUlRS8_RT0_RT1_E_clIS7_S6_NSt12experimental15fundamentals_v18optionalI17streamed_mutationEEEEDaSA_SC_SE_ENKUlvE_clEvEUlS8_E_OSt5tupleIJ18optimized_optionalISK_EEESt16integer_sequenceImJLm0EEEE5applyEOSN_SS_ (args=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x3a0f020, DIE 0x3bd603e>, func=<optimized out>)
    at /usr/src/debug/scylla-1.3.0/seastar/core/apply.hh:34
#50 _Z5applyIZZZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows0E27reconcilable_result_builderEEEDa15mutation_readerOT_bENKUlRS8_RT0_RT1_E_clIS7_S6_NSt12experimental15fundamentals_v18optionalI17streamed_mutationEEEEDaSA_SC_SE_ENKUlvE_clEvEUlS8_E_J18optimized_optionalISK_EEEDaS9_OSt5tupleIJDpT0_EE (args=<optimized out>, func=<optimized out>) at /usr/src/debug/scylla-1.3.0/seastar/core/apply.hh:42
#51 _ZN8futurizeI6futureIJ14stop_iterationEEE5applyIZZZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows0E27reconcilable_result_builderEEEDa15mutation_readerOT_bENKUlRSD_RT0_RT1_E_clISC_SB_NSt12experimental15fundamentals_v18optionalI17streamed_mutationEEEEDaSF_SH_SJ_ENKUlvE_clEvEUlSD_E_J18optimized_optionalISP_EEEES2_SE_OSt5tupleIJDpT0_EE (func=func@entry=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x3a0f020, DIE 0x3bd60d3>,
    args=args@entry=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x3a0f020, DIE 0x3bd6da9>) at /usr/src/debug/scylla-1.3.0/seastar/core/future.hh:1234
#52 0x000000000094a1a6 in _ZZN6futureIJ18optimized_optionalI17streamed_mutationEEE4thenIZZZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows0E27reconcilable_result_builderEEEDa15mutation_readerOT_bENKUlRSD_RT0_RT1_E_clISC_SB_NSt12experimental15fundamentals_v18optionalIS1_EEEEDaSF_SH_SJ_ENKUlvE_clEvEUlSD_E_S_IJ14stop_iterationEEEESG_SE_ENUlSE_E_clI12future_stateIJS2_EEEEDaSE_ (state=<unknown type in /usr/lib/debug/usr/bin/scylla.debug, CU 0x3a0f020, DIE 0x3b65c8e>,
    __closure=0x6081048959d8) at /usr/src/debug/scylla-1.3.0/seastar/core/future.hh:870
#53 _ZN12continuationIZN6futureIJ18optimized_optionalI17streamed_mutationEEE4thenIZZZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows0E27reconcilable_result_builderEEEDa15mutation_readerOT_bENKUlRSE_RT0_RT1_E_clISD_SC_NSt12experimental15fundamentals_v18optionalIS2_EEEEDaSG_SI_SK_ENKUlvE_clEvEUlSE_E_S0_IJ14stop_iterationEEEESH_SF_EUlSF_E_JS3_EE3runEv (this=0x6081048959c0) at /usr/src/debug/scylla-1.3.0/seastar/core/future.hh:402
#54 0x00000000004d589f in reactor::run_tasks (this=this@entry=0x6080000c3000, tasks=...) at core/reactor.cc:1527
#55 0x000000000050375b in reactor::run (this=0x6080000c3000) at core/reactor.cc:1947
#56 0x00000000005209ad in smp::<lambda()>::operator()(void) const (__closure=0x600000086b40) at core/reactor.cc:2818
#57 0x0000000000552b8e in std::function<void ()>::operator()() const (this=<optimized out>) at /opt/scylladb/include/c++/5.3.1/functional:2271
#58 posix_thread::start_routine (arg=<optimized out>) at core/posix.cc:50
#59 0x00007f39eb800dc5 in start_thread (arg=0x7f39e49ff700) at pthread_create.c:308
#60 0x00007f39eb52dced in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:113

**Comment by tgrabiec** [comment]
This looks like memory corruption. We fixed some bugs which could cause this on 1.3.1.

@ZoneMayor Can you retest with 1.3.1? If the problem persists, please upload the full coredump: https://github.com/scylladb/scylla/wiki/How-to-report-a-Scylla-problem

**Comment by slivne** [comment]
@ZoneMayor did the upgrade to 1.3.1 resolve the issue ?

**Comment by ZoneMayor** [comment]
@slivne Thanks a lot, already solved

**Comment by penberg** [comment]
@ZoneMayor Thanks for reporting back!
