### ISSUE TITLE
AMI creating errornous information in fstab

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla#1707]
*Installation details*
Scylla version (or git commit hash): 1.2.3 and 1.3.0 
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI (ScyllaDB 1.3 (ami-4bda0d2b)) and (ScyllaDB 1.2.3 (ami-3ebb725e))

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): I2.8xlarge
Hardware: sockets= cores= 32 hyperthreading= memory=244G
Disks: (SSD/HDD, count) SSD 800GBx8

fstab points to the boot device as /etc/sda1
while the actual boot device is on /dev/xvda1 
A customer claims that the misconfiguration causes Scylla not to reboot.

Here is the fstab and the df -T outputs of each installation.

Scylla Version 1.3
[centos@ip-172-31-46-68 ~]$ cat /etc/fstab 
/dev/sda1	   /	 xfs	defaults,noatime 1 1
none /dev/pts devpts gid=5,mode=620 0 0
none /proc proc defaults 0 0
none /sys sysfs defaults 0 0
[centos@ip-172-31-46-68 ~]$ df -T
Filesystem     Type      1K-blocks    Used  Available Use% Mounted on
/dev/xvda1     xfs        10474496 2753476    7721020  27% /
devtmpfs       devtmpfs  125850232       0  125850232   0% /dev
tmpfs          tmpfs     125728868       0  125728868   0% /dev/shm
tmpfs          tmpfs     125728868    8456  125720412   1% /run
tmpfs          tmpfs     125728868       0  125728868   0% /sys/fs/cgroup
/dev/md0       xfs      6248153088   34964 6248118124   1% /var/lib/scylla
tmpfs          tmpfs      25145776       0   25145776   0% /run/user/1000
[centos@ip-172-31-46-68 ~]$ scylla | grep version
Scylla version 1.3.0-20160820.b85164b starting ...
[centos@ip-172-31-46-68 ~]$ 

Scylla version 1.2.3
centos@ip-172-31-41-116 ~]$ cat /etc/fstab 
/dev/sda1	   /	 xfs	defaults,noatime 1 1
none /dev/pts devpts gid=5,mode=620 0 0
none /proc proc defaults 0 0
none /sys sysfs defaults 0 0
[centos@ip-172-31-41-116 ~]$ df -T
Filesystem     Type      1K-blocks    Used  Available Use% Mounted on
/dev/xvda1     xfs        10474496 1741816    8732680  17% /
devtmpfs       devtmpfs  125850232       0  125850232   0% /dev
tmpfs          tmpfs     125728868       0  125728868   0% /dev/shm
tmpfs          tmpfs     125728868    8456  125720412   1% /run
tmpfs          tmpfs     125728868       0  125728868   0% /sys/fs/cgroup
/dev/md0       xfs      6248153088   35088 6248118000   1% /var/lib/scylla
tmpfs          tmpfs      25145776       0   25145776   0% /run/user/1000
[centos@ip-172-31-41-116 ~]$ scylla | grep version
Scylla version 1.2.3-20160731.e9b7352 starting ...

**Comment by dorlaor** [comment]
@slivne can you make it 1.4.1 too?

**Comment by avikivity** [comment]
@dorlaor it's in bramch-1.4 now
