### ISSUE TITLE
'nodetool refresh' causes shutdown if files in upload directory have wrong permissions

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1709]
*Installation details*
Scylla version (or git commit hash): 1.3

It's quite expected that the user will forget to set the right permissions on files in the upload directory, issue a refresh, and end up with the node shutting down due to permissions problems.

**Comment by vladzcloudius** [comment]
The Node is being shut down because of the following registration:
```
sstable_read_error.connect([this] { isolate_on_error(); });
```

So, failure to read the sstable eventually triggers the code below:
```
if (must_isolate && !isolated.exchange(true)) {
        logger.warn("Shutting down communications due to I/O errors until operator intervention");
        // isolated protect us against multiple stops
        service::get_local_storage_service().stop_transport();
 }
```

**Comment by raphaelsc** [comment]
On Wed, Sep 28, 2016 at 10:15 AM, vladzcloudius <notifications@github.com>
wrote:

> The Node is being shut down because of the following registration:
>
> sstable_read_error.connect([this] { isolate_on_error(); });
>
> So, failure to read the sstable eventually triggers the code below:
>
> if (must_isolate && !isolated.exchange(true)) {
>         logger.warn("Shutting down communications due to I/O errors until operator intervention");
>         // isolated protect us against multiple stops
>         service::get_local_storage_service().stop_transport();
>  }
>
>
Maybe, we should whitelist the permission denied error. Look
at should_stop_on_system_error() in utils/exceptions.cc. BTW, registered
lambda is called before exception is even triggered, look at
disk-error-handler.hh

**Comment by avikivity** [comment]
Permission denied in the data directory should stop the  node, in the upload directory it should just fail the upload.

**Comment by vladzcloudius** [comment]
What is the "upload directory"? `nodetool refresh` reads newly placed sstables in the data directory: https://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsRefresh.html

**Comment by raphaelsc** [comment]
On Wed, Sep 28, 2016 at 12:12 PM, vladzcloudius <notifications@github.com>
wrote:

> What is the "upload directory"? nodetool refresh reads newly placed
> sstables in the data directory: https://docs.datastax.com/en/
> cassandra/2.1/cassandra/tools/toolsRefresh.html
>
A directory in every column family which is used to drop new sstables,
before calling refresh. Of course, you can also upload your new sstables
directly into cf.

**Comment by vladzcloudius** [comment]
And which directory is that? `nodetool refresh` doesn't get any arguments and from what I know it looks at a cf data directory. Are there any other directories it would look at?

**Comment by avikivity** [comment]
The `upload` directory under the column family directory.

**Comment by vladzcloudius** [comment]
@avi I've just found [this](https://github.com/scylladb/scylla/issues/487) and realized that we are talking about Scylla-specific feature. Ok. Then your proposal makes a lot of sense.
