### ISSUE TITLE
Leveled compaction strategy vs. large partitions

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1715]
_Installation details_
Scylla version (or git commit hash): 1.3

Leveled compaction strategies makes the assumption that sstables can be totally ordered by decorated key, but that assumption doesn't hold.  With Large partitions two sstables in the same level can have the same start and end keys.

**Comment by slivne** [comment]
in level 0 there can be an overlap

**Comment by raphaelsc** [comment]
On Thu, Sep 29, 2016 at 5:07 AM, nyh <notifications@github.com> wrote:

> The sstables in one level need to have disjoint token ranges, but if we
> want to allow partitions so huge that we want to split one to several
> sstables, we can allow the "disjointness" to be in a non-strict sense,
> i.e., if one sstable has token range a,b <http://including%20b>, another
> sstable may have b,c <http://i.e.,%20including%20b%20again>. We need to
> verify that the algorithm finding the intersecting sstables correctly
> handle this case.
>
> However, unless I'm misunderstanding sometihng, our current compaction
> code doesn't actually allow a partition to be split across several
> sstables, and each partition will be written in its entirety to a single
> sstable, even if the resulting sstable will be bigger than we hoped for?
>
exactly
