### ISSUE TITLE
Minimum/maximum tokens not handled properly in token_restriction

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#1717]
*Installation details*
Scylla version (or git commit hash): 1.4 and below

Queries like the following are not handled properly:

"SELECT * FROM ks.cf WHERE token(id) > 9207857967443869328 AND token(id) <= -9223372036854775808"

The problem is that -9223372036854775808 represents the minimum token, which isn't supposed to be a valid one. Rather, it should behave as a marker, either before all keys or after all keys. The current code just parses it and creates a token with kind::key out of it. In that particular query, the range appears as a wrap around which is invalid for CQL, so no results would be returned.

The correct behavior is to recognize the token as the special marker that it is, and parse it either as minimum_token or maximum_token.

**Comment by tgrabiec** [comment]
No results is what we should get here. The semantics of CQL restrictions are such that they select all rows for which the restrictions hold true. In this case no rows should be returned because no row has a key with token which is both greater than 9207857967443869328 and smaller than -9223372036854775808.

I have verified that C* 2.1.9 returns no rows for such queries.

**Comment by pdziepak** [comment]
Cassandra 2.1.13:

```
cqlsh:ks> select token(pk) from cf where token(pk) > 0 and token(pk) < -9223372036854775808;

 token(pk)
---------------------
 1634052884888577606
 2705480034054113608
 9010454139840013625
```

**Comment by duarten** [comment]
On Fri, Sep 30, 2016, 12:22 Tomasz Grabiec <notifications@github.com> wrote:

> No results is what we should get here. The semantics of CQL restrictions
> are such that they select all rows for which the restrictions hold true. In
> this case no rows should be returned because no row has a key with token
> which is both greater than 9207857967443869328 and smaller than
> -9223372036854775808.
>
The query means "all tokens bigger than 9207857967443869328".  I have
verified this with Cassandra 2.1.14.


I have verified that C* 2.1.9 returns no rows for such queries.

**Comment by tgrabiec** [comment]
Right, it looks like minimum token when used in upper bound means maximum token.
