### ISSUE TITLE
leveled compaction: broken token range distribution at higher levels

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1719]
uniform token range distribution across sstables in a level > 1 is broken, because we were only choosing sstable with lowest first key. Solution is to store last compacted key for each level to ensure sort of "round robin" selection of sstables. That's what C* does too, and they were affected by it as described by: https://issues.apache.org/jira/browse/CASSANDRA-6284

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
