### ISSUE TITLE
Compilation fails on CentOS7 with "libunwind.h: No such file or directory"

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#1722]
Same as #1721, probably it's missing all distribution. So same fix needed on .rpm packages.
```
In file included from core/reactor.cc:81:0:
./util/backtrace.hh:25:23: fatal error: libunwind.h: No such file or directory
compilation terminated.
ninja: build stopped: subcommand failed.
ninja: build stopped: subcommand failed.
error: Bad exit status from /var/tmp/rpm-tmp.sDOnBD (%build)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.sDOnBD (%build)
```

**Comment by penberg** [comment]
The Jenkins build still fails as follows:

```
12:05:29 Error: No Package found for libunwind-devel
```

AFAICT, that package should exist for CentOS but perhaps we need to install some other package to make it visible? epel? @tgrabiec @syuu1228

**Comment by avikivity** [comment]
The package exists on centos 7.2.  Maybe it doesn't on 7.0, which we are using.

**Comment by penberg** [comment]
Perhaps. Why are we using CentOS 7.0?

**Comment by avikivity** [comment]
An important used had a dependency on 7.0 (but no longer does).

**Comment by avikivity** [comment]
Installing on a clean 7.0 docker was able to pull libunwind-devel.

**Comment by avikivity** [comment]
Our 7.0 jenkins slave disabled updates, likely the cause of the failure.

**Comment by avikivity** [comment]
Confirmed.

**Comment by avikivity** [comment]
Triggered a new build using centos-7 with updates enabled, let's see how it goes.

**Comment by penberg** [comment]
Seems to work now, closing the issue.
