### ISSUE TITLE
[hub.docker.com/r/scylladb/scylla/] Not able to run through `docker service`, logs "invalid listen_address"

### ISSUE THREAD

**Issue by mrusme** [scylladb/scylla#1723]
_Installation details_
Scylla version (or git commit hash): 1.3.1-20160924.ff67439
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): https://hub.docker.com/r/scylladb/scylla/

It seems that the dockerized Scylla distribution does not function when ran using Docker's Swarm Mode (1.12). This is what Scylla's log output gives after launching the container on one worker node:

```
2016-10-01 07:10:06,547 INFO spawned: 'scylla' with pid 112
Scylla version 1.3.1-20160924.ff67439 starting ...
WARN  2016-10-01 07:10:06,976 [shard 0] init - Unable to check if net.ipv4.tcp_syncookies is set std::system_error (error system:2, No such file or directory)
ERROR 2016-10-01 07:10:06,979 [shard 0] init - Bad configuration: invalid 'listen_address': 10.255.0.12 172.18.0.3 10.1.0.9: std::runtime_error (Wrong format for IPv4 address 10.255.0.12 172.18.0.3 10.1.0.9. Please ensure it's in dotted-decimal format)
ERROR 2016-10-01 07:10:06,979 [shard 0] seastar - Exiting on unhandled exception: bad_configuration_error (std::exception)
2016-10-01 07:10:07,313 INFO exited: scylla (exit status 1; not expected)
2016-10-01 07:10:08,315 INFO gave up: scylla entered FATAL state, too many start retries too quickly
```

The correct listen_address for Scylla to use would have been `10.1.0.9`.

**Comment by tzach** [comment]
@mrusme thanks for reporting.
Look like Scylla is getting two IP address when expecting one.
I'm not familiar with Swarm, any idea where do this address are coming from?

**Comment by mrusme** [comment]
@tzach yes, the Container is being placed into multiple networks and therefor has multiple NICs (eth0, eth1, eth2, lo) and thereby multiple IPs. Maybe it should be possible to pass the IP Scylla should be listening on via Docker's `-e` (environment variable)?

**Comment by penberg** [comment]
@mrusme Actually, unfortunately not. We need to add a `--listen-address` command line argument similar to `--broadcast-address`.

We also need to do something about the default case where `hostname -i` returns multiple IP addresses in multi-NIC environment. Perhaps we should just pick the first one or something like that.

@avikivity @haarcuba

**Comment by mrusme** [comment]
@tzach @penberg I just opened a PR to demonstrate a possible solution of this issue [here](https://github.com/scylladb/scylla/pull/1728). I tested it locally using the documented usage commands and it seems to have worked nicely. Maybe you could give it a look and check whether this might be suitable for including into upstream.

**Comment by slivne** [comment]
@mrusme we have added the ``--listen-address`` did it resolve your issue ?

closing this issue - if it did not - we can reopen this issue

**Comment by mrusme** [comment]
@slivne yes, thanks. We continued discussing the Docker image on your mailing list: https://groups.google.com/forum/#!topic/scylladb-dev/GNBSA6Iu8HU
