### ISSUE TITLE
Service& seastar::sharded<Service>::local() [with Service = cql3::query_processor]: Assertion `local_is_initialized()' failed when scylla is interrupted under the load

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#173]
When terminating the scylla with Ctl-C under the load as described in issue #142 the above assertion is hit.

**Comment by slivne** [comment]
@vladzcloudius I am not able to reproduce this on anglerfish - are you able todo so - if not please close

**Comment by slivne** [comment]
@vladzcloudius ping

**Comment by slivne** [comment]
@vladcloudius - closing if you can reproduce please repoen
