### ISSUE TITLE
Block layer merges interfering with read-ahead

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1732]
*Installation details*
Scylla version (or git commit hash): 1.4

Read-ahead issues several (N) back-to-back 128kB reads; the block later merges them into a single N*128kB read; as a result, the first read's completion is delayed to that of the last read.

We can fix this by setting /sys/block/.../queue/nomerges = 2.

**Comment by slivne** [comment]
fixed in 1.5/master by blocktune 098d02ad1adf4e3fdbff7d68f5061778306289d0
