### ISSUE TITLE
scylla upgrade does not upgrade scylla-server package

### ISSUE THREAD

**Issue by ycui1984** [scylladb/scylla#1733]
we upgrade from 1.2 to 1.3, and run command like recommended on scylladb website. 
http://www.scylladb.com/doc/upgrade-from-1.2-to-1.3-ubuntu/
However, all packages except scylla-server is upgraded (We found this several days later by running 
dpkg -l | grep scylla )

**Comment by avikivity** [comment]
Can you provide the logs from `apt-get update`? Also from `apt-get update scylla-server`.

**Comment by slivne** [comment]
@ycui1984 any additional info - closing this - will reopen if there will be additional info
