### ISSUE TITLE
WHERE clause restrictions for SELECT statements

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#1735]
Hi

Now We can use only the last part of the partition key on in clause 
But Cassandra support   any partition key in 2.2
do you have a plan to add this function into scyllaDB ? 

<< scylladb>>
InvalidRequest: code=2200 [Invalid query] message="Partition KEY part tag cannot be restricted by IN relation (only the last part of the partition key can)"

<< cassandra >>
http://www.datastax.com/dev/blog/a-deep-look-to-the-cql-where-clause

WHERE clause restrictions for SELECT statements
Partition keys restrictions

The partition key columns support only two operators: = and IN

IN restriction

Prior to 2.2, the IN restrictions could only be applied to the last column of the partition key. So, for example, if your table was:

CREATE TABLE numberOfRequests (
    cluster text,
    date text,
    time text,
    numberOfRequests int,
    PRIMARY KEY ((cluster, date), time)
)
In 2.1, you could only use an IN operator on the date column. In 2.2 you can use the IN operator on any partition key column. By consequence, a query like:

SELECT \* FROM numberOfRequests
    WHERE cluster IN ('cluster1', 'cluster2')
    AND date = '2015-05-06'
    AND time >= '12:00'
    AND time <= '14:00';
is valid since 2.2 but is invalid in the prior releases.

**Comment by abvgedeika** [comment]
test: cql_additional_tests.py:TestCQL.composite_row_key_test
