### ISSUE TITLE
Key size too large 

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#1736]
I got an under messages form java client during write test

Do "Key size too large" mean wide row (large partition)?

at that time metric(Compacted partition maximum bytes) value is 370.14 KB

<< java client messages>>
18879 [cluster1-nio-worker-39] WARN com.datastax.driver.core.RequestHandler - /70.60.31.155:50006 replied with server error (Key size too large: 65542 > 65535), defuncting connection.
operation = 268 ,error = 0 ,time = 4 ,max timestamp = Sat Nov 05 00:58:20 KST 2016
19586 [cluster1-nio-worker-69] WARN com.datastax.driver.core.RequestHandler - /70.60.31.157:50006 replied with server error (Key size too large: 65542 > 65535), defuncting connection.
19801 [cluster1-nio-worker-79] WARN com.datastax.driver.core.RequestHandler - /70.60.31.157:50006 replied with server error (Key size too large: 65544 > 65535), defuncting connection.
operation = 286 ,error = 0 ,time = 5 ,max timestamp = Sat Nov 05 00:58:20 KST 2016
19951 [cluster1-nio-worker-41] WARN com.datastax.driver.core.RequestHandler - /70.60.31.156:50006 replied with server error (Key size too large: 65544 > 65535), defuncting connection.
19969 [cluster1-nio-worker-76] WARN com.datastax.driver.core.RequestHandler - /70.60.31.157:50006 replied with server error (Key size too large: 65542 > 65535), defuncting connection.
19974 [cluster1-nio-worker-76] WARN com.datastax.driver.core.RequestHandler - /70.60.31.158:50006 replied with server error (Key size too large: 65542 > 65535), defuncting connection.
20022 [cluster1-nio-worker-67] WARN com.datastax.driver.core.RequestHandler - /70.60.31.157:50006 replied with server error (Key size too large: 65542 > 65535), defuncting connection.
20229 [cluster1-nio-worker-5] WARN com.datastax.driver.core.RequestHandler - /70.60.31.159:50006 replied with server error (Key size too large: 65544 > 65535), defuncting connection.
20290 [cluster1-nio-worker-42] WARN com.datastax.driver.core.RequestHandler - /70.60.31.156:50006 replied with server error (Key size too large: 65542 > 65535), defuncting connection.
20468 [cluster1-nio-worker-77] WARN com.datastax.driver.core.RequestHandler - /70.60.31.158:50006 replied with server error (Key size too large: 65544 > 65535), defuncting connection.
20661 [cluster1-nio-worker-78] WARN com.datastax.driver.core.RequestHandler - /70.60.31.158:50006 replied with server error (Key size too large: 65542 > 65535), defuncting connection.
operation = 292 ,error = 0 ,time = 6 ,max timestamp = Sat Nov 05 00:58:20 KST 2016
21135 [cluster1-nio-worker-43] WARN com.datastax.driver.core.RequestHandler - /70.60.31.156:50006 replied with server error (Key size too large: 65542 > 65535), defuncting connection.
21413 [cluster1-nio-worker-66] WARN com.datastax.driver.core.RequestHandler - /70.60.31.158:50006 replied with server error (Key size too large: 65542 > 65535), defuncting connection.

[root@stgtest01 ~]# nodetool cfstats spatch -H
Keyspace: spatch
        Read Count: 0
        Read Latency: NaN ms.
        Write Count: 0
        Write Latency: NaN ms.
        Pending Flushes: 0
                Table: data_point
                SSTable count: 74
                Space used (live): 3.26 GB
                Space used (total): 3.26 GB
                Space used by snapshots (total): 0 bytes
                Off heap memory used (total): 2.01 MB
                SSTable Compression Ratio: 0.343779
                Number of keys (estimate): 111723
                Memtable cell count: 0
                Memtable data size: 0 bytes
                Memtable off heap memory used: 0 bytes
                Memtable switch count: 16
                Local read count: 0
                Local read latency: NaN ms
                Local write count: 0
                Local write latency: NaN ms
                Pending flushes: 0
                Bloom filter false positives: 0
                Bloom filter false ratio: 0.00000
                Bloom filter space used: 51.27 KB
                Bloom filter off heap memory used: 2 MB
                Index summary off heap memory used: 12.55 KB
                Compression metadata off heap memory used: 0 bytes
                Compacted partition minimum bytes: 125 bytes
                Compacted partition maximum bytes: 370.14 KB
                Compacted partition mean bytes: 51.93 KB
                Average live cells per slice (last five minutes): 0.0
                Maximum live cells per slice (last five minutes): 0.0
                Average tombstones per slice (last five minutes): 0.0
                Maximum tombstones per slice (last five minutes): 0.0

**Comment by avikivity** [comment]
No, it means that the partition key or clustering key is too large, above 64k.  Use smaller partitioning and clustering keys (for good performance, significantly smaller).

**Comment by slivne** [comment]
@infordb any additional info - I am closing this for now - if there is additional info I'll open the issue
