### ISSUE TITLE
Sstable readers created for streaming are timing out too soon

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1741]
There is a limit to concurrency of sstable readers on each shard. When this limit is exhausted (currently 100 readers) readers queue. There is a timeout after which queued readers are failed, equal to `read_request_timeout_in_ms` (5s by default). The reason we have the timeout here is primarily because the readers created for the purpose of serving a CQL request no longer need to execute after waiting longer than `read_request_timeout_in_ms`. The coordinator no longer waits for the result so there is no point in proceeding with the read.

This timeout should not apply for readers created for streaming. The streaming client currently times out after 10 minutes, so we could wait at least that long. Timing out sooner makes streaming unreliable, which under high load may prevent streaming from completing. Refs #1731.

**Comment by avikivity** [comment]
Interesting.  I guess we should make these reads bypass the timeouts.

**Comment by avikivity** [comment]
Ah, that's what you said.
