### ISSUE TITLE
docs: Issue in page OS Support by Linux Distributions and Version

### ISSUE THREAD

**Issue by noellymedina** [scylladb/scylla#17434]
I would like to report an issue in page https://enterprise.docs.scylladb.com/branch-2024.1/getting-started/os-support

### Problem
missing the OS compatibility for 2024: https://enterprise.docs.scylladb.com/stable/getting-started/os-support
![image](https://github.com/scylladb/scylladb/assets/31359297/0bc8370c-611c-4e82-afb0-0bb3bcd0f741)

###  Suggest a fix

cc. @tzach  @annastuchlik

**Comment by tzach** [comment]
@annastuchlik any update on this issue? can we push it?
