### ISSUE TITLE
Data in memtable is not considered when deciding whether expired tombstone can be discarded during sstable compaction

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1745]
This is a hypothetical scenario, which I don't think is likely, but possible.

There is no guarantee that tombstones and data they cover are received in timestamp order. So it could be that a tombstone will be flushed to an sstable while the data which is covered by it is still in memtable. Suppose there is a table which receives low load. It could happen that data sits in memtable for longer than `gc_grace_seconds`.

When sstables are compacted, expired tombstones can be dropped, if there is no data covered by it in data sources which don't take part in compaction. If there is an sstable which is not being compacted right now and may contain given key, the tombstone will not be dropped. This doesn't consider data in memtables, so compaction may discard a tombstone even though it covers data in memtable, which will result in resurrection of that data.

**Comment by tgrabiec** [comment]
Refs #3560

**Comment by slivne** [comment]
if gc_grace_seconds/2 has passed force flush ...

**Comment by bhalevy** [comment]
Cc @mikolajsieluzycki

**Comment by tgrabiec** [comment]
> if gc_grace_seconds/2 has passed force flush ...

I don't think this guarantees correctness. The memtable may receive mutations with any timestamp from the past via read repair, at any time.

**Comment by mikolajsieluzycki** [comment]
Can be closed with https://github.com/scylladb/scylla/commit/242e19195fb9874abbf98f7ca56f992c0961e128

**Comment by bhalevy** [comment]
Backport no longer required
