### ISSUE TITLE
Potential data resurrection if regular compaction races with cleanup

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#17501]
Since commit f1bbf705f9b6faa406baac04f418a93b09a53c19, many compaction types can do cleanup work, but turns out we forgot to invalidate cache on their completion.

So if a node regains ownership of token that had partition deleted in its previous owner, data can be resurrected.

Tablet is not affected, as it explicitly invalidates cache during migration cleanup stage.

Scylla 5.4 is affected.

**Comment by mykaul** [comment]
ping @scylladb/scylla-maint for backport.

**Comment by denesb** [comment]
Backported to 5.4.
