### ISSUE TITLE
Bulk copy fails - copy data from CSV to Scylla

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#1750]
_Installation details_
Scylla version (or git commit hash): 1.3
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-6c21427b

Trying to load data using CSV, operation fails 
Scenario
Create simple table:
CREATE TABLE training.test (name text PRIMARY KEY) ;

On the same instance create file with one row no headers.

> $ sudo vi load.csv

Enter value to the file 'nir'

> cqlsh 
> use training;
> cqlsh:training> COPY test FROM 'kk.csv';
> 'QueryMessage' object has no attribute 'to_binary'
> Aborting import at record #1. Previously inserted records are still present, and some records after that may be present as well

Copy fails with the error above, if any file manipulite is needed we should better instruct what need to be done.

Tested the same scenario in C\* it works

**Comment by eyalgutkind** [comment]
Scylla's Copy works only in one direction... from table to csv file.
From csv file to table, I got the same error :(
The troubling part is that cqlsh reported as if the row where imported, which is wrong.

cqlsh:uuu> create TABLE ii (name text primary key, myid int, owemoney int);
cqlsh:uuu> DESCRIBE TABLE uuu.ii

CREATE TABLE uuu.ii (
    name text PRIMARY KEY,
    myid int,
    owemoney int
) WITH bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cqlsh:uuu> INSERT INTO uuu.ii (name, myid, stuff ) VALUES ( 'Earl', 9876, 234242);
cqlsh:uuu> SELECT * FROM uuu.ii;

 name | myid | owemoney
------+------+----------
 Earl | 9876 |   234242

(1 rows)
cqlsh:uuu> COPY uuu.ii FROM 'my.csv';

'QueryMessage' object has no attribute 'to_binary'
Aborting import at record #1. Previously inserted records are still present, and some records after that may be present as well.

4 rows imported in 0.056 seconds.
cqlsh:uuu> SELECT * FROM uuu.ii
       ... ;

 name | myid | stuff
------+------+----------
 Earl | 9876 |   234242

(1 rows)
cqlsh:uuu> COPY uuu.ii TO 'my1.csv';

1 rows exported in 0.002 seconds.
[root@win-dbi ~]# cat my1.csv
Earl,9876,234242

**Comment by dorlaor** [comment]
Worth to check the scylla logs and enable tracing to figure out where is
the data

**Comment by honggui** [comment]
When will we get the fixing?

**Comment by avikivity** [comment]
@eyalgutkind can you retest? I expect it to work now.

**Comment by slivne** [comment]
I tested this on 1.7 (to be released soon) it is working

```
copy keyspace1.standard1 TO 'a.csv'  WITH HEADER=TRUE;
truncate keyspace1.standard1;
select * from keyspace1.standard1;
copy keyspace1.standard1 FROM 'a.csv'  WITH HEADER=TRUE;
select * from keyspace1.standard1;
```

**Comment by superdzen** [comment]
I tested on rpm-version scylla-enterprise-2017.1.0-20170614.9e18942.el7.centos.x86_64 + Centos 7.3 and i had the same error:

cqlsh:test> copy test.sample1 TO 'a.csv'  WITH HEADER=TRUE;

4 rows exported in 0.004 seconds.
cqlsh:test> truncate test.sample1;
cqlsh:test> select * from test.sample1;

 foo | bar | baz | faz
-----+-----+-----+-----

(0 rows)
cqlsh:test> copy test.sample1 FROM 'a.csv'  WITH HEADER=TRUE;

'QueryMessage' object has no attribute 'to_binary'
Aborting import at record # 1. Previously inserted records are still present, and some records after that may be present as well.

4 rows imported in 0.067 seconds.


TRACING ON shows the same message.

**Comment by tzach** [comment]
@superdzen node that you are using an enterprise version. This Github project is for Scylla open source.
See here[1] for more about Scylla Enterprise and how to get support for it.

[1] http://www.scylladb.com/product/scylla-enterprise/

**Comment by glommer** [comment]
@avikivity do you remember which commit supposedly fixes this ? We have a user on 1.7 hitting this same thing

**Comment by avikivity** [comment]
@glommer it was fixed in scylla-tools.

**Comment by glommer** [comment]
@skpotnuru hi

I don't understand the relationship between truncate table and this bug with the current subject. Am I missing something ? Can you please clarify ?

**Comment by skpotnuru** [comment]
My issue is different with the discussion happening here. Just I was curious know about my issue and here some people are active so I just posted it. Help me in this.

**Comment by glommer** [comment]
We are always willing to help our users, but what you are doing here is just impolite and outright confusing for people in the future searching issues for the right information.

Please don't do this.

In particular, I found a bug opened that seem to describe your issue https://github.com/scylladb/scylla/issues/3694

Move this discussion there.

**Comment by skpotnuru** [comment]
sorry for posting my issue in wrong page. I was curious to know about my issue and I found here many are discussing so I posted it without thinking anything. Anyway thank you for your response.
