### ISSUE TITLE
IO use 100% without any job

### ISSUE THREAD

**Issue by chaipugao** [scylladb/scylla#1751]
_Installation details_
Scylla version (or git commit hash): 1.3.0
Cluster size:2
OS (RHEL/CentOS/Ubuntu/AWS AMI):CentOS7

_Hardware details (for performance issues)_          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets= cores=24  hyperthreading= memory=128G
Disks: (SSD/HDD, count) SSD 1

The cpu， io station are follows，is this normal？

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          57.34    0.00   13.91    0.00    0.00   28.75

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sdb               0.00     0.00 56791.50    0.00 221848.00     0.00     7.81    23.31    0.41    0.41    0.00   0.02 100.05

**Comment by avikivity** [comment]
Under load it is normal for Scylla to consume a lot of cpu and disk bandwidth.

**Comment by avikivity** [comment]
It looks like it is under load.  Please check your application.

**Comment by slivne** [comment]
@chaipugao any additional info ?

**Comment by slivne** [comment]
@chaipugao closing this issue - we will reopen once there is additional info
