### ISSUE TITLE
question about the order of server start-up

### ISSUE THREAD

**Issue by whoops33** [scylladb/scylla#1752]
When it prints "Scylla API server listening on xxx.xxx.xxx.xxx:10000", we may think that all server is ready. However, if we connect Thrift server after Scylla API starts up immediately, then segment fault occurs as Thrift server listens on port 9161 after Scylla API server listening on 10000. So if it is better to let Scylla API server start up after all other servers start up?

**Comment by avikivity** [comment]
There should not be a segmentation fault.  Can you provide instructions on how to reproduce?  Or a core dump.

You should be able to connect to Thrift  when it says "Thrift server is listening..."; and before that there should be no harm in trying to connect.

**Comment by slivne** [comment]
@whoops33 

The reason that the API comes up before scylla has start thrift/cql server is to have management access while scylla is booting (for example - during bootup we open all sstables, replay commitlogs etc.)

can you please provide additional info

**Comment by slivne** [comment]
@whoops33 when there is additional info please post and I'll reopen
