### ISSUE TITLE
Wrong CQL error if keyspace replication strategy class is not found

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#1755]
*Installation details*
Scylla version (or git commit hash): 1.4-rc1

If an user requests a replication strategy class that is not found, Apache Cassandra responds with configuration exception:

```
[penberg@nero apache-cassandra-3.9]$ ./bin/cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.9 | CQL spec 3.4.2 | Native protocol v4]
Use HELP for help.
cqlsh>  CREATE KEYSPACE "todolist" WITH replication = {'class': 'Simple Strategy', 'replication_factor' : '1'};
ConfigurationException: Unable to find replication strategy class 'org.apache.cassandra.locator.Simple Strategy'
```
Scylla, however, responds with CQL server error, which may confuse drivers and cause them to not report the error message in readable form:

```
[penberg@nero ~]$ docker exec -it some-scylla cqlsh
Connected to Test Cluster at 172.17.0.2:9042.
[cqlsh 5.0.1 | Cassandra 2.1.8 | CQL spec 3.2.1 | Native protocol v3]
Use HELP for help.
cqlsh>  CREATE KEYSPACE "todolist" WITH replication = {'class': 'Simple Strategy', 'replication_factor' : '1'};
ServerError: <ErrorMessage code=0000 [Server error] message="unable to find class 'Simple Strategy'">
```

**Comment by Ik-williams** [comment]
cqlsh>  CREATE KEYSPACE "todolist" WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : '1'};

SimpleStrategy should be written without space

**Comment by sivanidwarampudi** [comment]
Cassandra is case sensitive so you should use SimpleStrategy instead of simplestrategy
