### ISSUE TITLE
scylla_setup: optimize NIC queue settings fails

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1757]
*Installation details*
Scylla version (or git commit hash): 1.4 RC1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): m3.xlarge

```
Answer yes to do system wide configuration customized for Scylla. Answer no to do nothing.
[YES/no]
Do you want to optimize NIC queue settings?
Answer yes to enable network card optimization; this improve performance. Answer no to skip this optimization.
[YES/no]
Setting parameters on /etc/sysconfig/scylla-server
cat: /sys/class/net/eth0/device/irq: No such file or directory
```

**Comment by syuu1228** [comment]
This is same problem with https://github.com/scylladb/seastar/issues/188, but different vNIC.
I found this on KVM with virtio-net, but looks like Xen with xen_netfront acts like same.
On such interface, it doesn't provide irq information on sysfs:
```
[centos@ip-172-30-0-172 ~]$ ls /sys/class/net/eth0/device
devtype  driver  modalias  net  nodename  power  subsystem  uevent
```
posix_net_conf.sh tries to access /sys/class/net/$iface/device/msi_irqs/ or /sys/class/net/$iface/device/irq, but both doesn't exist.

However, we have an entry on /proc/interrupts instead, probably we can use this:
```
$ cat /proc/interrupts |grep eth0
 76:       6958          0          0          0   xen-dyn-event     eth0
```
Or maybe we can force single queue mode for such vNICs. There is multiqueue mode on virtio-net though...
