### ISSUE TITLE
scylla_setup: setting hugepages not required, no need to restart after setup

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1758]
_Installation details_
Scylla version (or git commit hash): 1.4 RC1

At the end of a successful scylla_setup, I get the following message:

```
Please restart machine before using ScyllaDB, since you have changed 
boot parameters.
```

Restarting a server is not a good UX.
This is a result of /usr/lib/scylla/scylla_bootparam_setup setting up hugepages, which is currently not required.

**Comment by syuu1228** [comment]
What about SELinux

**Comment by syuu1228** [comment]
Ah, we are forgetting to ask to reboot when we executed scylla_selinux_setup, anyway.

**Comment by avikivity** [comment]
We can use "setenforce 0" to disable selinux.

**Comment by syuu1228** [comment]
It seems I forgot to remove hugepage allocation on scylla_prepare, we still able to allocate it on scylla running time, not via kernel boot parameter:
https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_prepare#L31

We also do "setenforce 0" on scylla_selinux_setup so we can run scylla withour reboot, but "setenforce 0" only switches to permissive mode, it does not disable SELinux completely, may have few performance overhead.

If it's doesn't matter, we can just drop "Please restart" message without implementing anything.
And even we can drop scripts to modify boot parameters.

**Comment by tzach** [comment]
@syuu1228  two questions for you:
- Do I need to restart with 1.5?
- Can we fix the message for 1.6?

**Comment by syuu1228** [comment]
@tzach if we care about overhead of SELinux permissive mode and want to disable it completely, we need restart.
For hugepage allocation we don't use DPDK mode by default, and we can allocate it dynamically, don't need restart.

What kind of message do you prefer?

**Comment by tzach** [comment]
> @tzach if we care about overhead of SELinux permissive mode and want to disable it completely, we need restart.

1. What the gain from disabling SELinux? restarting the server is a drag
2. Assuming we do need to disable SELinux, lets ask for restart just in case we actually did

**Comment by slivne** [comment]
@syuu1228 if selinux is already disabled - will we instruct to restart as well

**Comment by syuu1228** [comment]
@tzach @slivne How about to change scripts:
- drop scylla_bootparam_setup, since we don't need to setup hugepages on boot time
- shows up "Please restart" message when scylla_selinux_setup was executed by user
- skip running scylla_selinux_setup and skip message, when SELinux is already disabled

**Comment by tzach** [comment]
Looks good to me.

**Comment by slivne** [comment]
+1
