### ISSUE TITLE
1.4-rc2 joining an ami node into a cluster shows different dc/rack info

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1760]
_Installation details_
Scylla version (or git commit hash): 1.4-rc2 - ami ami-3caee62b

started a cluster of 3 nodes on ec2
started a write workload on the cluster

tried to add a new node
1. boot another ami node
2. shutdown scylla on it (its asingle node cluster)
3.  remove the /var/lib/scylla/data /var/lib/scylla/commitlog
4. update the /etc/scylla/scylla.yaml 
- change the cluster name
- change the seed ip used in the cluster of 3 nodes
- boot the node up

run nodetool status on the node / on the cluster

on the new node I got

```
ty[centos@ip-10-79-183-244 ~]$ nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens  Owns    Host ID                               Rack
UN  10.41.171.96   1.53 GB    256     ?       5c0169b2-f3ad-4577-8791-32388b020721  rack1
UN  10.99.184.201  1.36 GB    256     ?       82b83dbd-a43a-4d85-a1a8-7b3e4e939e96  rack1
UN  10.109.137.39  1.49 GB    256     ?       f327ec36-eec6-4df4-86e3-eb32eb67a205  rack1
Datacenter: us-east
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens  Owns    Host ID                               Rack
UN  10.79.183.244  276.66 MB  256     ?       5d5def94-2c5c-40d9-9517-96ecacb5f41d  1c

```

on the scylla cluster I got

```
[centos@ip-10-109-137-39 ~]$ nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens  Owns    Host ID                               Rack
UN  10.41.171.96   1.68 GB    256     ?       5c0169b2-f3ad-4577-8791-32388b020721  rack1
UN  10.99.184.201  773.13 MB  256     ?       82b83dbd-a43a-4d85-a1a8-7b3e4e939e96  rack1
UN  10.109.137.39  917.6 MB   256     ?       f327ec36-eec6-4df4-86e3-eb32eb67a205  rack1
UN  10.79.183.244  1.3 GB     256     ?       5d5def94-2c5c-40d9-9517-96ecacb5f41d  rack1
```

checking snitch on both clusters

on new node

```
[centos@ip-10-79-183-244 ~]$ cat /etc/scylla/scylla.yaml | grep -i endpoint_snitch
endpoint_snitch: Ec2Snitch
```

```
[centos@ip-10-109-137-39 ~]$ cat /etc/scylla/scylla.yaml | grep -i endpoint_snitch
endpoint_snitch: SimpleSnitch
```

Is this the issue ?

**Comment by slivne** [comment]
@asias is this a regression ?

**Comment by slivne** [comment]
found while trying to validate  #1467  is fixed

**Comment by asias** [comment]
Why are they using different snitch, configuration error?

**Comment by tzach** [comment]
AMI should use Ec2Snitch, not the SimpleSnitch.
This hint that problem was in the 3 cluster servers, not the one joining.

**Comment by slivne** [comment]
@asias 

1) Yes its a mistake (ami / user) - yet still strange

2) Isn't the rack:dc info distributed over gossip by nodes ?

3) does simplesnitch assume all nodes are in datacenter1:rack1 ?

it looks like a bug as well (in addition to a bad user config)  - it needs to be consistent across the cluster

**Comment by asias** [comment]
You can use nodetool gossipinfo to check what rack/dc info gossip knows. I am not sure where "nodetool status" get the rack info from. I suspect nodetool status is not getting the rack info from gossip.

All nodes will gossip its rack/dc info into the cluster. So the old nodes should have the "us-east":"1c" info for the new nodes. 

Simplesnich will always return datacenter1:rack1 when get_rack() and get_datacenter() is called
