### ISSUE TITLE
wrapping range queries can return incorrect results in extreme circumstances

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1761]
If:

 - we issue a wraparound (large, small] query via thrift
 - the results from (large, +inf) do not satisfy the page size
 - there are results from (-inf, small]

then we'd see results from (-inf, small] before (large, +inf).

**Comment by duarten** [comment]
How can this happen?

storage_proxy considers the ranges resulting from a call to unwrap() in the correct order, that is, (large, +inf) and then (-inf, small].

**Comment by avikivity** [comment]
Due to sharding.  We send the same query to all shards in parallel (this is bad, and I have a patchset that fixes it).

Suppose our ring is [-9..+9].  Suppose our partition range is (8, -7].  Suppose the limit is 1 partition.  Suppose shard 0 returns a partition with token 9 and shard 1 returns a partition with token -8.  The mutation_result_merger will pick shard 1's partition over shard 0.

**Comment by avikivity** [comment]
(so even if each shard works correctly, mutation_result_merger messes things up)

**Comment by duarten** [comment]
Ahh, I see. Thanks for the explanation!
