### ISSUE TITLE
storage_proxy metrics are confusing

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1763]
_Installation details_
Scylla version (or git commit hash): 1.4

It's hard to disentangle the replica side and coordinator side.  Let's put them under different categories (erase storage_proxy, insert coordinator/replica where appropriate).

**Comment by tzach** [comment]
@vladzcloudius ping

**Comment by vladzcloudius** [comment]
@tzach @slivne 
NP, I'll work on this today. It's not more than a few hours of work in total.

**Comment by vladzcloudius** [comment]
@tzach @slivne The patch is on the list: "service/storage_proxy: regroup collectd statistics"
