### ISSUE TITLE
repair is unsafe with concurrent tablet migration or replica set change

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#17658]
Scenario 1 (changing the replica set):

1. RF=3, tablet replicas={A, B, C}
2. CL=QUORUM write is ACKed on {A, B}
3. RF++, tablet replicas={A, B, C, D(empty)} (in group0)
3.1 Nodes B, C, D see the new metadata (group0 quorum)
3.1 Node A is still seeing old metadata
4. “nodetool repair -pr” runs on node A, sees that replicas are {A, B, C}
4.1 replica on node D is not repaired, but the tablet is marked as repaired.

Repair should invoke group0 read barrier before obtaining erm pointer so that it sees all prior metadata changes.

Keeping the erm pointer prevents later migrations from proceeding (they will be blocked in allow_write_both_read_old stage), so replica set won't change during repair.

Also, repair should wait until repaired tablets are not in transition, so that it doesn't run concurrently with migrations.

**Comment by asias** [comment]
> Scenario 1 (changing the replica set):
> 
>     1. RF=3, tablet replicas={A, B, C}
> 
>     2. CL=QUORUM write is ACKed on {A, B}
> 
>     3. RF++, tablet replicas={A, B, C, D(empty)} (in group0)
>        3.1 Nodes B, C, D see the new metadata (group0 quorum)
>        3.1 Node A is still seeing old metadata
> 
>     4. “nodetool repair -pr” runs on node A, sees that replicas are {A, B, C}
>        4.1 replica on node D is not repaired, but the tablet is marked as repaired.
> 
> 
> Repair should invoke group0 read barrier before obtaining erm pointer so that it sees all prior metadata changes.
> 
> Keeping the erm pointer prevents later migrations from proceeding (they will be blocked in allow_write_both_read_old stage), so replica set won't change during repair.
> 
> Also, repair should wait until repaired tablets are not in transition, so that it doesn't run concurrently with migrations.


Hi @tgrabiec 

1) What if the RF changes again after invoking read barrier before getting erm?

- group0 read barrier

- RF is changed to {A, B, C, D(empty), E(empty)}

- get erm

2) Will holding erm prevent RF to change?

- group0 read barrier
- get erm
- Can RF change when the erm is hold?

**Comment by asias** [comment]
> > > Scenario 1 (changing the replica set):
> > > ```
> > > 1. RF=3, tablet replicas={A, B, C}
> > > 
> > > 2. CL=QUORUM write is ACKed on {A, B}
> > > 
> > > 3. RF++, tablet replicas={A, B, C, D(empty)} (in group0)
> > >    3.1 Nodes B, C, D see the new metadata (group0 quorum)
> > >    3.1 Node A is still seeing old metadata
> > > 
> > > 4. “nodetool repair -pr” runs on node A, sees that replicas are {A, B, C}
> > >    4.1 replica on node D is not repaired, but the tablet is marked as repaired.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Repair should invoke group0 read barrier before obtaining erm pointer so that it sees all prior metadata changes.
> > > Keeping the erm pointer prevents later migrations from proceeding (they will be blocked in allow_write_both_read_old stage), so replica set won't change during repair.
> > > Also, repair should wait until repaired tablets are not in transition, so that it doesn't run concurrently with migrations.
> > 
> > 
> > Hi @tgrabiec
> > 
> > 1. What if the RF changes again after invoking read barrier before getting erm?
> > 
> > 
> > * group0 read barrier
> > * RF is changed to {A, B, C, D(empty), E(empty)}
> > * get erm
> 
> This will be handled by RF change solution. It won't allow RF to change again before previous change is finalized by repair.
> 
> See https://docs.google.com/document/d/1Oy3koTTZUo5g_UyNbEBge6PWiZp6BLN3kc_C4YQkzxw/edit#heading=h.pgfsd1sfqr1x
> 
> > 2. Will holding erm prevent RF to change?
> > 
> > 
> > * group0 read barrier
> > * get erm
> > * Can RF change when the erm is hold?
> 
> No. We could make it prevent it, but this is not sufficient to synchronize, and also not necessary.

In this case,  the RF could change after the group0 read barrier.  So with/without performing group0 read barrier, repair still could think a tablet has replicas {A, B, C} while in fact it is changed to {A, B, C, D}. Why are you suggesting performing group0 read barrier as a fix to the problem?

I think it only fixes a special case: 

- RF chagne
-  run repair
   +  take group 0 read barrrier
   +  get erm
   + run actual repair
- no more RF change during repair

**Comment by tgrabiec** [comment]
> > > > Scenario 1 (changing the replica set):
> > > > ```
> > > > 1. RF=3, tablet replicas={A, B, C}
> > > > 
> > > > 2. CL=QUORUM write is ACKed on {A, B}
> > > > 
> > > > 3. RF++, tablet replicas={A, B, C, D(empty)} (in group0)
> > > >    3.1 Nodes B, C, D see the new metadata (group0 quorum)
> > > >    3.1 Node A is still seeing old metadata
> > > > 
> > > > 4. “nodetool repair -pr” runs on node A, sees that replicas are {A, B, C}
> > > >    4.1 replica on node D is not repaired, but the tablet is marked as repaired.
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Repair should invoke group0 read barrier before obtaining erm pointer so that it sees all prior metadata changes.
> > > > Keeping the erm pointer prevents later migrations from proceeding (they will be blocked in allow_write_both_read_old stage), so replica set won't change during repair.
> > > > Also, repair should wait until repaired tablets are not in transition, so that it doesn't run concurrently with migrations.
> > > 
> > > 
> > > Hi @tgrabiec
> > > 
> > > 1. What if the RF changes again after invoking read barrier before getting erm?
> > > 
> > > 
> > > * group0 read barrier
> > > * RF is changed to {A, B, C, D(empty), E(empty)}
> > > * get erm
> > 
> > 
> > This will be handled by RF change solution. It won't allow RF to change again before previous change is finalized by repair.
> > See https://docs.google.com/document/d/1Oy3koTTZUo5g_UyNbEBge6PWiZp6BLN3kc_C4YQkzxw/edit#heading=h.pgfsd1sfqr1x
> > > 2. Will holding erm prevent RF to change?
> > > 
> > > 
> > > * group0 read barrier
> > > * get erm
> > > * Can RF change when the erm is hold?
> > 
> > 
> > No. We could make it prevent it, but this is not sufficient to synchronize, and also not necessary.
> 
> In this case, the RF could change after the group0 read barrier. So with/without performing group0 read barrier, repair still could think a tablet has replicas {A, B, C} while in fact it is changed to {A, B, C, D}. 

Yes.

> Why are you suggesting performing group0 read barrier as a fix to the problem?
> 
> I think it only fixes a special case:
> 
> * RF change
> * run repair
>   
>   * take group 0 read barrier
>   * get erm
>   * run actual repair
> * no more RF change during repair

read barrier is only one part of the solution, necessary but not sufficient. The other part is to detect RF change which could start after repair obtained erm, by checking if replicas are the same at the end of repair, and not mark the tablet as repaired in this case.

This is mentioned in the doc under "Repairing a tablet updates "unrepaired_datacenters" here: https://docs.google.com/document/d/1Oy3koTTZUo5g_UyNbEBge6PWiZp6BLN3kc_C4YQkzxw/edit#bookmark=id.szqc11g4fgos

**Comment by bhalevy** [comment]
Ref https://github.com/scylladb/scylladb/issues/17852

**Comment by tgrabiec** [comment]
Another reason why running repair concurrently with migration is not safe is that it may happen that repair was started when tablet migration was in such a stage that reads are using "old" replica selector, while writes were using "both" replica selector. Some writes could be made only to the "new" replica set and will not be observed by repair reader, while they should be because they were made before repair was started. They will not be replicated everywhere by repair so may be subject to data resurrection issues.

This particular race could be solved, e.g. by using both new and old replicas. But I think it's better to serialize repair with migration and not worry about such races.
