### ISSUE TITLE
create_view_statement: Missing properties

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#1766]
_Installation details_
Scylla version (or git commit hash): master

The `create_view_statement` is parsed as follows:

```
createViewStatement returns [::shared_ptr<create_view_statement> expr]
        [...]
        (K_WITH properties[props])?
        [...]
    ;
```

However, our `properties` differs from the `properties` in Cassandra 3.0+:

```
properties[::shared_ptr<cql3::statements::property_definitions> props]
    : property[props] (K_AND property[props])*
    ;
```

vs 

```
cfamProperty[CFProperties props]
    : property[props.properties]
    | K_COMPACT K_STORAGE { $props.setCompactStorage(); }
    | K_CLUSTERING K_ORDER K_BY '(' cfamOrdering[props] (',' cfamOrdering[props])* ')'
    ;
```

This means our `create_view_statement` is missing the compact storage and clustering key order properties. This entails re-writing it a bit, so it uses a raw_statement.

**Comment by penberg** [comment]
@duarten The parser C++ translation originates from a 2.2 development tree so it's not surprising that there are differences to 3.0 grammar.

**Comment by duarten** [comment]
@penberg Sure, this issue is just to keep track of some refactoring that needs to be done.

**Comment by duarten** [comment]
Btw, I can't create/assign labels, but we need a materialized_views one :)

**Comment by penberg** [comment]
Looks like I cannot do that either. @avikivity @slivne
