### ISSUE TITLE
Unable to locate package scylla (After ddd the Scylla APT repository)

### ISSUE THREAD

**Issue by slmcat2002** [scylladb/scylla#1772]
Scylla version (or git commit hash): 1.3
Linux ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:45:15 UTC 2015 i686 i686 i686 GNU/Linux

I had add the Scylla APT repository to system, and then run 
apt-get update
apt-get install scylla

But it sill not works :(

root@ubuntu:/# 
root@ubuntu:/# sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/ubuntu/scylla-1.3-trusty.list
--2016-10-20 09:07:20--  http://downloads.scylladb.com/deb/ubuntu/scylla-1.3-trusty.list
Resolving downloads.scylladb.com (downloads.scylladb.com)... 52.216.32.18
Connecting to downloads.scylladb.com (downloads.scylladb.com)|52.216.32.18|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 107 [application/octet-stream]
Saving to: ‘/etc/apt/sources.list.d/scylla.list’

100%[=====================================================================================================>] 107         --.-K/s   in 0s      

2016-10-20 09:07:20 (5.73 MB/s) - ‘/etc/apt/sources.list.d/scylla.list’ saved [107/107]

root@ubuntu:/# sudo apt-get update
Hit http://archive.ubuntukylin.com:10006 trusty InRelease
Hit http://archive.ubuntukylin.com:10006 trusty/main i386 Packages             
Ign http://repo.mongodb.org trusty/mongodb-org/3.2 InRelease                   
Hit http://archive.ubuntukylin.com:10006 trusty/main Translation-en            
Hit http://repo.mongodb.org trusty/mongodb-org/3.2 Release.gpg                 
Hit http://repo.mysql.com trusty InRelease                                     
Hit http://repo.mongodb.org trusty/mongodb-org/3.2 Release                     
Hit http://repo.mongodb.org trusty/mongodb-org/3.2/multiverse i386 Packages    
Hit http://security.ubuntu.com trusty-security InRelease                       
Ign http://us.archive.ubuntu.com trusty InRelease                              
Ign http://s3.amazonaws.com trusty InRelease                                   
Hit http://repo.mysql.com trusty/mysql-apt-config i386 Packages                
Hit http://security.ubuntu.com trusty-security/main Sources                    
Hit http://us.archive.ubuntu.com trusty-updates InRelease                      
Ign http://s3.amazonaws.com trusty Release.gpg                                 
Hit http://repo.mysql.com trusty/workbench-6.2 i386 Packages                   
Hit http://security.ubuntu.com trusty-security/restricted Sources              
Get:1 https://dl.bintray.com  InRelease                                        
Ign https://dl.bintray.com  InRelease                                          
Hit http://us.archive.ubuntu.com trusty-backports InRelease                    
Ign http://s3.amazonaws.com trusty Release                                     
Hit http://repo.mysql.com trusty/workbench-6.3 i386 Packages                   
Ign http://repo.mongodb.org trusty/mongodb-org/3.2/multiverse Translation-en_US
Hit https://dl.bintray.com  Release.gpg                                        
Hit http://security.ubuntu.com trusty-security/universe Sources                
Ign http://repo.mongodb.org trusty/mongodb-org/3.2/multiverse Translation-en   
Hit http://us.archive.ubuntu.com trusty Release.gpg                            
Hit http://security.ubuntu.com trusty-security/multiverse Sources              
Hit http://repo.mysql.com trusty/connector-python-2.0 i386 Packages            
Hit http://us.archive.ubuntu.com trusty-updates/main Sources                   
Hit http://security.ubuntu.com trusty-security/main i386 Packages              
Ign http://s3.amazonaws.com trusty/scylladb-1.3/multiverse amd64 Packages/DiffIndex
Hit http://repo.mysql.com trusty/connector-python-2.1 i386 Packages            
Hit http://us.archive.ubuntu.com trusty-updates/restricted Sources             
Hit http://security.ubuntu.com trusty-security/restricted i386 Packages        
Hit https://dl.bintray.com  Release                                            
Hit http://repo.mysql.com trusty/router-2.0 i386 Packages                      
Hit http://us.archive.ubuntu.com trusty-updates/universe Sources               
Hit http://security.ubuntu.com trusty-security/universe i386 Packages          
Hit http://us.archive.ubuntu.com trusty-updates/multiverse Sources             
Hit http://security.ubuntu.com trusty-security/multiverse i386 Packages        
Hit http://repo.mysql.com trusty/mysql-utilities-1.5 i386 Packages             
Hit http://us.archive.ubuntu.com trusty-updates/main i386 Packages             
Hit http://security.ubuntu.com trusty-security/main Translation-en             
Hit https://dl.bintray.com  Packages                                           
Hit http://repo.mysql.com trusty/mysql-tools i386 Packages                     
Hit http://us.archive.ubuntu.com trusty-updates/restricted i386 Packages       
Hit http://security.ubuntu.com trusty-security/multiverse Translation-en       
Hit http://security.ubuntu.com trusty-security/restricted Translation-en       
Hit http://us.archive.ubuntu.com trusty-updates/universe i386 Packages         
Hit http://security.ubuntu.com trusty-security/universe Translation-en         
Hit http://us.archive.ubuntu.com trusty-updates/multiverse i386 Packages       
Get:2 https://dl.bintray.com  Translation-en_US                                
Hit http://us.archive.ubuntu.com trusty-updates/main Translation-en            
Get:3 https://dl.bintray.com  Translation-en                                   
Hit http://us.archive.ubuntu.com trusty-updates/multiverse Translation-en      
Get:4 https://dl.bintray.com  Translation-en_US                                
Hit http://us.archive.ubuntu.com trusty-updates/restricted Translation-en      
Hit http://us.archive.ubuntu.com trusty-updates/universe Translation-en        
Get:5 https://dl.bintray.com  Translation-en                                   
Hit http://us.archive.ubuntu.com trusty-backports/main Sources                 
Get:6 https://dl.bintray.com  Translation-en_US                                
Hit http://us.archive.ubuntu.com trusty-backports/restricted Sources           
Get:7 https://dl.bintray.com  Translation-en                                   
Get:8 https://dl.bintray.com  Translation-en_US                        
Get:9 https://dl.bintray.com  Translation-en                              
Hit http://us.archive.ubuntu.com trusty-backports/universe Sources        
Get:10 https://dl.bintray.com  Translation-en_US                               
Ign https://dl.bintray.com  Translation-en_US                                  
Hit http://us.archive.ubuntu.com trusty-backports/multiverse Sources           
Get:11 https://dl.bintray.com  Translation-en                                  
Ign https://dl.bintray.com  Translation-en                                     
Hit http://us.archive.ubuntu.com trusty-backports/main i386 Packages           
Hit http://s3.amazonaws.com trusty/scylladb-1.3/multiverse amd64 Packages      
Hit http://us.archive.ubuntu.com trusty-backports/restricted i386 Packages     
Ign http://s3.amazonaws.com trusty/scylladb-1.3/multiverse Translation-en_US   
Hit http://us.archive.ubuntu.com trusty-backports/universe i386 Packages
Hit http://us.archive.ubuntu.com trusty-backports/multiverse i386 Packages     
Hit http://us.archive.ubuntu.com trusty-backports/main Translation-en          
Ign http://s3.amazonaws.com trusty/scylladb-1.3/multiverse Translation-en      
Hit http://us.archive.ubuntu.com trusty-backports/multiverse Translation-en    
Hit http://us.archive.ubuntu.com trusty-backports/restricted Translation-en    
Hit http://us.archive.ubuntu.com trusty-backports/universe Translation-en      
Hit http://us.archive.ubuntu.com trusty Release                                
Hit http://us.archive.ubuntu.com trusty/main Sources                           
Hit http://us.archive.ubuntu.com trusty/restricted Sources                     
Hit http://us.archive.ubuntu.com trusty/universe Sources                       
Hit http://us.archive.ubuntu.com trusty/multiverse Sources                     
Hit http://us.archive.ubuntu.com trusty/main i386 Packages        
Hit http://us.archive.ubuntu.com trusty/restricted i386 Packages  
Hit http://us.archive.ubuntu.com trusty/universe i386 Packages                 
Hit http://us.archive.ubuntu.com trusty/multiverse i386 Packages               
Hit http://us.archive.ubuntu.com trusty/main Translation-en                    
Hit http://us.archive.ubuntu.com trusty/multiverse Translation-en              
Hit http://us.archive.ubuntu.com trusty/restricted Translation-en              
Hit http://us.archive.ubuntu.com trusty/universe Translation-en                
Ign http://us.archive.ubuntu.com trusty/main Translation-en_US                 
Ign http://us.archive.ubuntu.com trusty/multiverse Translation-en_US           
Ign http://us.archive.ubuntu.com trusty/restricted Translation-en_US           
Ign http://us.archive.ubuntu.com trusty/universe Translation-en_US             
Ign http://repo.mysql.com trusty/connector-python-2.0 Translation-en_US        
Ign http://repo.mysql.com trusty/connector-python-2.0 Translation-en
Ign http://repo.mysql.com trusty/connector-python-2.1 Translation-en_US
Ign http://repo.mysql.com trusty/connector-python-2.1 Translation-en
Ign http://repo.mysql.com trusty/mysql-apt-config Translation-en_US
Ign http://repo.mysql.com trusty/mysql-apt-config Translation-en
Ign http://repo.mysql.com trusty/mysql-tools Translation-en_US
Ign http://repo.mysql.com trusty/mysql-tools Translation-en
Ign http://repo.mysql.com trusty/mysql-utilities-1.5 Translation-en_US
Ign http://repo.mysql.com trusty/mysql-utilities-1.5 Translation-en
Ign http://repo.mysql.com trusty/router-2.0 Translation-en_US
Ign http://repo.mysql.com trusty/router-2.0 Translation-en
Ign http://repo.mysql.com trusty/workbench-6.2 Translation-en_US
Ign http://repo.mysql.com trusty/workbench-6.2 Translation-en
Ign http://repo.mysql.com trusty/workbench-6.3 Translation-en_US
Ign http://repo.mysql.com trusty/workbench-6.3 Translation-en
Reading package lists... Done
root@ubuntu:/# sudo apt-get install scylla
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package scylla
root@ubuntu:/#

**Comment by dorlaor** [comment]
The problem is that we create the repository list by running wget and Ubuntu resolves the URL to s3:

 sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/ubuntu/scylla-1.3-xenial.list
--2016-10-20 17:39:21--  http://downloads.scylladb.com/deb/ubuntu/scylla-1.3-xenial.list
Resolving downloads.scylladb.com (downloads.scylladb.com)... 54.231.115.33
Connecting to downloads.scylladb.com (downloads.scylladb.com)|54.231.115.33|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 107 [application/octet-stream]
Saving to: ‘/etc/apt/sources.list.d/scylla.list’

/etc/apt/sources.list.d/scylla.list                   100%[======================================================================================================================>]     107  --.-KB/s    in 0s      

2016-10-20 17:39:21 (16.4 MB/s) - ‘/etc/apt/sources.list.d/scylla.list’ saved [107/107]

dor@dor-ThinkPad-T440:~$ cat /etc/apt/sources.list.d/scylla.list
deb  [arch=amd64] http://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu xenial scylladb-1.3/multiverse

**Comment by kongove** [comment]
Quoted from @slmcat2002 's description:
```
Scylla version (or git commit hash): 1.3
Linux ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:45:15 UTC 2015 i686 i686 i686 GNU/Linux
```

It's a i686 arch, but our repo is for amd64 (x86_64). Items of s3.amazonaws.com were all ignored in 'apt-get update'.

**Comment by penberg** [comment]
@slmcat2002 Looks like you have a 32-bit OS, no? We only support 64-bit at the moment.

**Comment by slmcat2002** [comment]
Ah, I changed my OS to 64-bit, and it works, thanks.
