### ISSUE TITLE
is this a bug when commitlog replay?

### ISSUE THREAD

**Issue by duanshisan** [scylladb/scylla#1775]
**when replay in function 'db::commitlog::read_log_file(...)',  if the code 'return s.produce(buf.share(0, data_size), rp);' has error, this function wait  future will be set exception() in the below code (seastar/core/stream.hh):**

template <typename... T>
inline
future<>
stream<T...>::produce(T... data) {
    auto ret = futurize<void>::apply(_sub->_next, std::move(data)...);
    if (ret.available() && !ret.failed()) {
        // Native network stack depends on stream::produce() returning
        // a ready future to push packets along without dropping.  As
        // a temporary workaround, special case a ready, unfailed future
        // and return it immediately, so that then_wrapped(), below,
        // doesn't convert a ready future to an unready one.
        return ret;
    }
    return ret.then_wrapped([this](auto&& f) {
        try {
            f.get();
        } catch (...) {
            _done.set_exception(std::current_exception());  **//set exception first**
            // FIXME: tell the producer to stop producing
            throw;
        }
    });
}

**but ,this exception be throwed again, will be catched by bellow code (db/commitlog/commitlog.cc):**

subscription<temporary_buffer<char>, db::replay_position>
db::commitlog::read_log_file(file f, commit_load_reader_func next, position_type off) {
   .....
    w->s.started().then(std::bind(&work::read_file, w.get())).then([w] {
        w->s.close();
    }).handle_exception([w](auto ep) {
        w->s.set_exception(ep);   **//here set exception again**
    });

```
return ret;
```

}

**so set exception  twice will cause error in bellow code (seastar/core/future.hh):**

void set_exception(std::exception_ptr ex) noexcept {
        assert(_state == state::future);    **//assert error**
        new (&_u.ex) std::exception_ptr(ex);
        _state = state::exception;
}

**Comment by glommer** [comment]
@duanshisan Thanks, great analysis. Will you send a patch or want one of us to fix it ?

**Comment by duanshisan** [comment]
@glommer 

Only for this commitlog replay problem, whether to do a simple modification like this:

db/commitlog/commitlog.cc

subscription<temporary_buffer<char>, db::replay_position>
hive_commitlog::read_log_file(file f, commit_load_reader_func next, position_type off) {

    struct work {
        ...
        **bool already_set_exception = false; //add a flag** 

        future<> read_entry() {
        ...
              return s.produce(buf.share(0, data_size), rp).**then_wrapped([this](auto f)mutable{
                        try{
                            f.get();
                            return make_ready_future<>();
                        }catch(...){
                            already_set_exception = true;
                            throw;
                        }
              });**
        ...
        }
    };

    auto w = make_lw_shared<work>(std::move(f), off);
    auto ret = w->s.listen(std::move(next));
    w->s.started().then(std::bind(&work::read_file, w.get())).then([w] {
        w->s.close();
    }).handle_exception([w](auto ep) {
        **if(!w->already_set_exception){
            w->s.set_exception(ep);
        }**
    });

}//end of read_log_file


**use a flag can solve this problem but looks very uncomfortable, whether have other better solution? and can we modify the promise class when set_value or set_exception don't assert directly,  instead by other better way?**

**Comment by slivne** [comment]
@elcallio @glommer can you please review

**Comment by slivne** [comment]
@elcallio @glommer ping

**Comment by elcallio** [comment]
Sorry, I did not take the comment as a patch. In general, I think we should consider making this less sensitive in types like stream etc, like at least have a stream::operator bool() -> promise not set to indicate "open". 
For this particular case I think the correct handling is a slight variant of your code, making sure exceptions generated by "produce" in the commit log reader do not propagate to the top exception handler, and for now workaround the lack of a check if a stream is open. I'll send a patch. 
Also added a test case for this.
