### ISSUE TITLE
broadcast_rpc_address should be part of the supported section in the yaml file

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla#1779]
_Installation details_
Scylla version (or git commit hash): from Scylla 1.0
Cluster size: N/A
OS (RHEL/CentOS/Ubuntu/AWS AMI): All

The following section is the unsupported section. However, the setting is impacting a multi-dc  deployment and should be set to external IP for the EC2 Multi Region snitch.

RPC address to broadcast to drivers and other Scylla nodes. This cannot
be set to 0.0.0.0. If left blank, this will be set to the value ofrpc_address. 
If rpc_address is set to 0.0.0.0, broadcast_rpc_address must
be set.
broadcast_rpc_address: 1.2.3.4

**Comment by tzach** [comment]
#803 is the super set of this issue
