### ISSUE TITLE
Upgradable AMI

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1788]
_Installation details_
Scylla version (or git commit hash): 1.3

Current AMI is preinstalled, which means it can _not_ be upgrade using the standard procedure. 
Once fix:
- We will only have one AMI per minor release (e.g. 1.3.x) .
- AMI init will check and download latest packages
- Upgrade to the next release (e.g. 1.4) will be done by the official procedure

**Comment by syuu1228** [comment]
@tzach Why it's not upgradable by standard procedure, currently? Or you just mean we should upgrade latest packages on first boot?

**Comment by tzach** [comment]
@syuu1228 last I checked, the repo is not set for AMI at all, so upgrade will not work
(for example between 1.3.2 to 1.3.3)
Second, we need to run this upgrade on boot, so users will have the latest version of 1.3 (for example)

**Comment by slivne** [comment]
The issue originated from the need to have a repo to install the inital version of scylla even before rc1 has been uploaded 

To install the intiial version we must have the repo to access the 3rdparties.

What we can do is update the repo after we finished installation of the initial version - in this manner even if the repo does not exist scylla will be installed.

**Comment by slivne** [comment]
1.5 AMI can be upgraded via the regular procedure (it installs the artifacts via the build repo and at the end places the generic repo data).

I do not think that the AMI on boot should check for release and upgrade - it will take much longer to boot an instance / cluster (we also download and install the debug version).
