### ISSUE TITLE
Lots of leaks in debug mode tests

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1792]
Does someone know what's up with debug mode tests? Look:
SUMMARY: AddressSanitizer: 5906064 byte(s) leaked in 22944 allocation(s).

Is that a problem only affecting the test itself or it may affect Scylla too?

**Comment by raphaelsc** [comment]
@pdziepak ping

**Comment by pdziepak** [comment]
I don't think we are aware of any false positives in leak detection, so otherwise successful test run should not trigger any of LeakSanitizer errors and, in fact, it doesn't seem to have any complaints about our current master.
