### ISSUE TITLE
High 99th percentile during compaction under some circumstances

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1794]
Due more aggressive read-ahead and write-behind, compaction can use the cpu for longer, delaying reads.

**Comment by avikivity** [comment]
This was tracked to two issues:

1. seastar deferring non-I/O continuations unnecessarily, allowing a compaction task to occupy the cpu; thus, a read that issues two I/Os ended up being pushed to the end of the task list 10 times instead of just two.

2. On Ubuntu kernels, the cpu timer has 4 ms resolution, which is coarser than the 2 ms task quota; thus, the task quota was ignored.

**Comment by slivne** [comment]
Fixed in master and 1.5 

Still open in 1.4
