### ISSUE TITLE
Add collectd counters for digest mismatch events

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1795]

**Comment by gleb-cloudius** [comment]
FWIW REST api expose
read_repair_repaired_background/read_repair_repaired_blocking
their sum is amount of digest mismatch. We had a plan to expose all
counters that API knows about to collectd automatically. Don't know the
status of this work.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
Fixed by 2d5a7c8058274dff515b093143a1ff45ba4b3a76

--
			Gleb.
