### ISSUE TITLE
Do not allow NetworkingTopologyStrategy with SimpleSnitch

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1799]
*Installation details*
Scylla version (or git commit hash): 1.3

NetworkingTopologyStrategy does **not** work well with SimpleSnitch
Its better to fail CREATE KEYSPACE with Replication Strategy NetworkTopologyStrategy when SimpleSnitch is used

**Comment by tzach** [comment]
@vladzcloudius thoughts ?

**Comment by gleb-cloudius** [comment]
On Sun, Oct 30, 2016 at 05:59:03AM -0700, Tzach Livyatan wrote:
> @vladzcloudius thoughts ?
> 
My though is that this is a dup of #1789

--
			Gleb.

**Comment by tzach** [comment]
> My though is that this is a dup of #1789

and only 3 days late
