### ISSUE TITLE
Apply new keyspace replicas via raft in ALTER

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla#18032]
Should be fixed by #17116 

ALTER should generate new replicas for tablets and apply the relevant mutations via raft
Then tablets rebuild plan should be applied in the background #18031

**Comment by mykaul** [comment]
@KrzaQ - what's the latest status of this item?

**Comment by ptrsmrn** [comment]
Both mentioned PRs are closed -> the change has been implemented -> closing.
