### ISSUE TITLE
only seal sstable(s) created by leveled compaction at the end 

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1807]
That's required for system not to leave behind sstables created as a result of a partial compaction. Compaction may be unfinished in event of a sudden shutdown, for example.

**Comment by avikivity** [comment]
I think there's no harm in leaving those sstables. We are resilient to violations of the LCS invariant.

So, I think we can close this.

**Comment by avikivity** [comment]
@raphaelsc do you agree we can close?

**Comment by raphaelsc** [comment]
On Sun, Apr 28, 2019 at 9:59 AM Avi Kivity <notifications@github.com> wrote:

> @raphaelsc <https://github.com/raphaelsc> do you agree we can close?
>
I think so given that invariant can be restored. It only affects a forced
exit in scylla process because sstables created for failed compaction will
be deleted.

**Comment by raphaelsc** [comment]
closing this issue
