### ISSUE TITLE
non-intrusive way for disabling automatic compaction for a cf

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#1808]
currently, it's possible to disable automatic compaction for a column family by setting its strategy to NullCompactionStrategy, but that's too intrusive. It would be nice to introduce an API that would allow user to enable/disable automatic compaction.

**Comment by slivne** [comment]
@raphaelsc 

does cassanrd have this - if so can you provide a pointer ?

whey do we need this ?

**Comment by raphaelsc** [comment]
@slivne Cassandra has this: https://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsDisableAutoCompaction.html
and 
https://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsEnableAutoCompaction.html

i think it's interesting when you want to determine that compaction is the root of a problem, and c* allows enabling/disabling automatic compaction on a per cf basis

**Comment by raphaelsc** [comment]
Closing this issue. It's already covered by #1488

**Comment by argenet** [comment]
I am wondering if we want to keep this issue open. Firstly, this is supported by Cassandra but not ScyllaDB so would be good to have it for feature parity, moreover, users are asking for it (https://stackoverflow.com/questions/47866555/how-do-i-disable-autocompaction-in-cassandra-yaml).

As mentioned by Raphael, that is also helpful for development purposes. #1488 suggests a different approach to solve this, but `nodetool` seems to be a very natural utility to do that.
