### ISSUE TITLE
CQL: Scylla incorrectly handles multi-column restrictions

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#1809]
*Installation details*
Scylla version (or git commit hash): a35136533d9fb080979f4cdacfde02935d63aad2

Repro:

```bash
echo "create keyspace ks with replication = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };" | bin/cqlsh
echo "create table ks.cf(p text, c1 text, c2 text, c3 text, v int, primary key (p, c1, c2, c3));" |  bin/cqlsh
for i in `seq 1 1000`; do echo  "insert into ks.cf (p, c1, c2, c3, v) values ('key1', '1', '$i', '$(($i * 2))', 0);" ; done | bin/cqlsh
echo "select count(*) from ks.cf where p = 'key1' and c1='1' and (c2, c3) >= ('10', '1000');" | bin/cqlsh

<stdin>:2:InvalidRequest: code=2200 [Invalid query] message="Clustering columns may not be skipped in multi-column relations. They should appear in the PRIMARY KEY order. Got (c2, c3) >= ('10', '1000')"
```

Expected result:

```bash
echo "select count(*) from ks.cf where p = 'key1' and c1='1' and (c2, c3) >= ('10', '1000');" | bin/cqlsh

 count
-------
   999

(1 rows)
```

**Comment by tzach** [comment]
> ```echo "select count(*) from ks.cf where p = 'key1' and c1='1' and (c2, c3) >= ('10', '1000');```

Is unintuitive to me. Is it equvalent to ``` p = 'key1' and c1='1' and c2 >= '10' and  c3 >= '1000'); ``` ?

**Comment by tzach** [comment]
Look similar to https://issues.apache.org/jira/browse/CASSANDRA-8613

**Comment by duarten** [comment]
Yep, I think it's equivalent to that.

**Comment by pdziepak** [comment]
Looks like a duplicate of #64.

@tzach No, it is a lexicographical ordering so an equivalent to `p = 'key1' and c1 = '1' and ((c2 = '10' and c3 >= '1000') or (c2 > '10'))`.

**Comment by duarten** [comment]
Closing this one then as a duplicate.
