### ISSUE TITLE
seastar - Exceptional future ignored: storage_io_error

### ISSUE THREAD

**Issue by GpStore** [scylladb/scylla#1810]
*Installation details*
Scylla version (or git commit hash): 
1.3.1-20160924.ff67439

Cluster size:  3nodes  hold 8T data
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7.2

Platform (physical/VM/cloud instance type/docker):physical
Hardware: sockets=1024（ulimit -n） cores=12  hyperthreading=24 memory=64G
Disks: (SSD/HDD, count)   SSD*7,SSD*7,SSD*5

issue：
[shard 4] compaction_manager - compaction failed: std::bad_alloc (std::bad_alloc)
[shard 4] storage_service - shutting down communications due to I/O errors until operator intervention
[shard 4] seastar - Exceptional future ignored: storage_io_error (Storage I/O error: 9 : bad file desciptor)

and with lots of warnings like this:
storage_proxy exception when communicating with x.x.x.x std::bad_alloc
core reason：9 bad file descriptor

when occur this error, 
the node hung up, can not process the select or insert  query.
and sometimes the node restart and the "nodetool status" command say the node has down;

could give some suggestion for this issue, and where to get more information of error context, we
find no coredump file or other stack list error log except journalctl;

thanks.

**Comment by avikivity** [comment]
Hi, this bug has been fixed in Scylla 1.4.0; please upgrade and check again.

**Comment by GpStore** [comment]
we have find another issue using 1.3 version

sstable - deleting components of sstable from sophon.sophon_object of generation 226772 that has a temporary TOC

**Comment by avikivity** [comment]
That is an informational message.  Scylla found a partially-written SSTable and is deleting it.

The SSTable was partially written because of the error (bad_alloc) during compaction; no data was lost.

**Comment by GpStore** [comment]
and warning like this is not a critical error that cause node abnormal？

[shard 4] compaction_manager - compaction failed: std::bad_alloc (std::bad_alloc)

**Comment by avikivity** [comment]
It is a severe error -- the node cannot make progress during compaction.

Can you describe you schema?  This error should not happen in 1.3.

**Comment by slivne** [comment]
@GpStore we need additional info

**Comment by slivne** [comment]
@GpStore if you will provide additional info we would work to investigate and fix this.
