### ISSUE TITLE
scylla may not restart in a big box if one column family has too many sstables

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#1812]
Running it on EC2 i2.8xlarge (30 shards used by scylla), scylla will fail to boot, yielding an exception when reading the peers table

```
[shard 0] seastar - Exiting on unhandled exception: exceptions::read_timeout_exception (Operation timed out for system.peers - received only 0...
```

The problem seem to appear because we do work in the sstable destructor that is quadratic in the number of sstables and shards. We don't wait for it, since there is no good way to wait on a destructor.

**Comment by tgrabiec** [comment]
Can you explain where the quadratic behavior comes from exactly? Do you have a flamegraph showing this?

**Comment by avikivity** [comment]
Look at `sstables::do_delete_atomically()`.  It copies the list of sstables pending deletion, which is as large as the number of sstables we have.

I'm working on a patch.

**Comment by avikivity** [comment]
(that function is linear, but is called O(nr sstables we have) times.

**Comment by tzach** [comment]
@glommer what scylla version is this?
We did many tests on EC2 i2.8xlarge, and did not saw this issue before. I guess the amount of data on disk is different. How many sstables? what was the data volume?

**Comment by glommer** [comment]
Data volume doesn't matter. Number of sstables do.

Issue start to get visible over 40k sstables in my experience.

Note that STCS will tend to generate less sstables over time for the same
amout of data. LCS makes this easier to reproduce on a real system.
