### ISSUE TITLE
Proper TLS support - require_client_auth, specific cipher_suites, and secure nodetool 

### ISSUE THREAD

**Issue by bobymicroby** [scylladb/scylla#1813]
Hi team!

Thanks for the awesome product. We started evaluating scylla as C* replacement. So far things are looking good. Only trouble is that we are forced to operate in an insecure environment, and therefore we need to be able to enforce a strong security policy. What troubles me is that :

- there is no support for **require_client_auth** ( correct me if I'm wrong, i did just a very brief digging in the source code)

- there is no support for setting a specific **cipher_suites** and disabling insecure ones ( again maybe i'm wrong, but it looks to me that option cipher_suites is never parsed anywhere in the code)  

- there is no support for **securing nodetool** like in [cassandra](https://docs.datastax.com/en/cassandra/2.1/cassandra/security/secureNodetoolSSL.html)

Regards, Bobby.

**Comment by dorlaor** [comment]
@elcallio @amnonh please follow up

**Comment by elcallio** [comment]
Hello Bobby. 
You are more or less correct on all accounts. 1 & 2 should be fairly easy to implement via our gnutls bridge. 3 should more or less just require some script changes to the scylla-jmx helper process. I'll see if and when I can get these fixed.

**Comment by bobymicroby** [comment]
@elcallio If you indeed plan to tighten up the security, I would suggest that you try to enable require_client_auth for the node-to-node comms as well. 

Thanks guys for the info, keep up the great work 👍

**Comment by dorlaor** [comment]
@bobymicroby <https://github.com/bobymicroby>, thanks, in case you can
share some of the good findings (and also,
don't shy away from sharing problems as you did), we'll be happy to hear!

**Comment by bobymicroby** [comment]
Hi @dorlaor 

Good things so far: 

- Was pretty easy to setup the cluster on CentOs
- Was pretty easy to tune to the nodes by using the provided scripts
- Performance is great ( despite the lack of resources on the nodes  )
- Having a native prometheus monitoring is really awesome !

Problems so far :

- Since we are running on a public cloud,  the lack of proper TLS for node-to-node and client-to-cluster is something that is needed badly

Will keep you posted with things we find along the way, because we have just started.

Bobby.

**Comment by elcallio** [comment]
@slivne, ff8f82f21cdaa66c92eefc92d04613de53820e76 fixes this issue, so barring testing/feedback on the options available, you can close this.
