### ISSUE TITLE
[1.5.rc1] Handling overload condition failed 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1817]
*Installation details*
Scylla version (or git commit hash): 1.5-rc1 AMI (ami-edf5d1fa)
Cluster size: 
3 - i2.2x
Loaders : 4 - c4.large
OS (RHEL/CentOS/Ubuntu/AWS AMI):

running cassandra-stress
```
cassandra-stress write no-warmup cl=QUORUM duration=60m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=1000 -errors ignore -pop seq=1..10000000 -node
```

throughput:

the performance of 1.5 is ~25K-50K for the cluster (not including the peak at the start - before compactions start)
the performance for 1.4 is 70K-120K for the cluser (not including the peak at the start - before compactions start)

cpu
1.5 - 45-80 %
1.4 - 88-99 %

1.5-rc1
[scylla-ami-1.5-rc1-write-workload.pdf](https://github.com/scylladb/scylla/files/575878/scylla-ami-1.5-rc1-write-workload.pdf)
![1 5-rc1-1](https://cloud.githubusercontent.com/assets/3465480/20065108/9c8ff3ba-a515-11e6-9fc1-3548eaca5ee8.png)
![1 5-rc1-2](https://cloud.githubusercontent.com/assets/3465480/20065107/9c8da394-a515-11e6-8375-0bf278f92ef9.png)

1.4

[scylla-ami-1.4-write-workload.pdf](https://github.com/scylladb/scylla/files/575877/scylla-ami-1.4-write-workload.pdf)

![1 4-1](https://cloud.githubusercontent.com/assets/3465480/20065109/9c93cec2-a515-11e6-9a9f-e003a19ffa71.png)
![1 4-2](https://cloud.githubusercontent.com/assets/3465480/20065110/9c964760-a515-11e6-9fd2-a3aabb75332b.png)

**Comment by slivne** [comment]
1.4 info

```
[centos@ip-172-30-0-57 ~]$ rpm -qa | grep scylla
scylla-boost-thread-1.58.0-11.el7.centos.x86_64
scylla-boost-date-time-1.58.0-11.el7.centos.x86_64
scylla-server-1.4.0-20161031.ef01285.el7.centos.x86_64
scylla-jmx-1.4.0-20161031.db6efc4.el7.centos.noarch
scylla-gdb-7.10.1-30.el7.centos.x86_64
scylla-boost-system-1.58.0-11.el7.centos.x86_64
scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
scylla-kernel-conf-1.4.0-20161031.ef01285.el7.centos.x86_64
scylla-tools-1.4.0-20161031.4888c65.el7.centos.noarch
scylla-1.4.0-20161031.ef01285.el7.centos.x86_64
scylla-env-1.0-1.el7.centos.noarch
scylla-conf-1.4.0-20161031.ef01285.el7.centos.x86_64
scylla-boost-test-1.58.0-11.el7.centos.x86_64
scylla-debuginfo-1.4.0-20161031.ef01285.el7.centos.x86_64
[centos@ip-172-30-0-57 ~]$ cat /etc/scylla.d/*
CPUSET="--cpuset 0,1,2,3,4,5,6,7 "
# DO NO EDIT
# This file should be automatically configure by scylla_dev_mode_setup
#
# DEV_MODE=--developer-mode=0
[housekeeping]
check-version: True
SEASTAR_IO="--num-io-queues 8 --max-io-requests 64"
```

1.5 info

```
[centos@ip-172-30-0-214 ~]$ rpm -qa | grep scylla
scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
scylla-1.5.rc1-20161102.08b1ff5.el7.centos.x86_64
scylla-boost-system-1.58.0-11.el7.centos.x86_64
scylla-boost-thread-1.58.0-11.el7.centos.x86_64
scylla-boost-test-1.58.0-11.el7.centos.x86_64
scylla-boost-date-time-1.58.0-11.el7.centos.x86_64
scylla-kernel-conf-1.5.rc1-20161102.08b1ff5.el7.centos.x86_64
scylla-server-1.5.rc1-20161102.08b1ff5.el7.centos.x86_64
scylla-tools-1.5.rc1-20161102.3deb48d.el7.centos.noarch
scylla-debuginfo-1.5.rc1-20161102.08b1ff5.el7.centos.x86_64
scylla-env-1.0-1.el7.centos.noarch
scylla-conf-1.5.rc1-20161102.08b1ff5.el7.centos.x86_64
scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
scylla-jmx-1.5.rc1-20161102.941f694.el7.centos.noarch
scylla-gdb-7.10.1-30.el7.centos.x86_64
[centos@ip-172-30-0-214 ~]$ cat /etc/scylla.d/*.conf
CPUSET="--cpuset 0,1,2,3,4,5,6,7 "
# DO NO EDIT
# This file should be automatically configure by scylla_dev_mode_setup
#
# DEV_MODE=--developer-mode=0
SEASTAR_IO="--num-io-queues 8 --max-io-requests 64"
```

**Comment by gleb-cloudius** [comment]
Do we have data for one node?

--
			Gleb.

**Comment by slivne** [comment]
no

**Comment by dorlaor** [comment]
Cheers for discovering it on time

**Comment by gleb-cloudius** [comment]
Looking at the graphs 1.5 has much less background writes. It may mean
that throttling kicks in much earlier. The only change I can think of
that could have make such an effect is the "commitlog: rework blocking
logic" series. AFAIR it should have improved situation with timeouts and
indeed 1.5 has less timeouts overall (but still there are timeouts).

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Mon, Nov 07, 2016 at 07:58:33PM +0200, Gleb Natapov wrote:
> AFAIR it should have improved situation with timeouts and
> indeed 1.5 has less timeouts overall (but still there are timeouts).
> 
Well actually 1.5 has more timeouts (looked at the wrong graph).

--
			Gleb.

**Comment by tgrabiec** [comment]
1.5 has more idle time, it could be 33e9c2bbdd65439f6cf1639e3deb7dea031387fe plus the fact that fdatasync has high latency.

**Comment by gleb-cloudius** [comment]
On Mon, Nov 07, 2016 at 10:59:40AM -0800, Tomasz Grabiec wrote:
> 1.5 has more idle time, it could be 33e9c2bbdd65439f6cf1639e3deb7dea031387fe plus the fact that fdatasync has high latency.
> 
Throttling will cause idle time too, but this commit is a good suspect
too.

--
			Gleb.

**Comment by glommer** [comment]
where is the prometheus db for this one? We should be looking at commitlog metrics, dirty memory metrics (not in standard dash) to figure this out.

**Comment by glommer** [comment]
![statusblock](https://cloud.githubusercontent.com/assets/331197/20225750/006ec82a-a813-11e6-9a7a-e9b6f5870969.png)

**Comment by glommer** [comment]
There is one node going through trashing here. The others seem fine.
It's trying to flush 25 memtables at the same time, which is utterly unreasonable.

I had patches for this, but never managed to get them merged due to reprioritization.

**Comment by avikivity** [comment]
25 in total is not so unreasonable. 25 per shard is. Which is it?

**Comment by glommer** [comment]
Not per shard. That's the maximum of all shards.

**Comment by avikivity** [comment]
So, there's at least one shard writing 25 sstables?

**Comment by glommer** [comment]
precisely. I've been staying away from averages when debugging timeout situations.

**Comment by glommer** [comment]
Ok. So the patches I am talking about, they were in my github tree,  branch RFC-one-mt

They need some love, but they applied verbatim so I figured I'd take them to a test drive. It basically fixes this issue.

**Comment by glommer** [comment]
![load-1817](https://cloud.githubusercontent.com/assets/331197/20227778/e7d6b01c-a81b-11e6-8477-89e95961cea1.png)

**Comment by glommer** [comment]
I'll leave it running for longer, but without those patches the node was already basically going nuts by now.

**Comment by glommer** [comment]
FWIW, in the interest of improving understanding I will revert some of the patches that we thought here could be the cause here, so we can better understand what's in play here.

**Comment by glommer** [comment]
30 min in, still extremely stable. Now let me go do some root-cause analysis.

**Comment by glommer** [comment]
Ok, 33e9c2b seems indeed be the main issue at play here.

What happens is that with just one memtable slot available for flush, we'll keep trying to flush the others, which means we'll start sealing a lot (25?) of very small memtables.

I advise against reverting 33e9c2b . It fixes a real issue. In a couple of days I can resend the patches I have used in this issue.

**Comment by glommer** [comment]
Another reason *not* to revert that patch is that I still see memtables pending growing to numbers that I consider worrisome. They're just not enough to bring doom.

**Comment by glommer** [comment]
Indeed, leaving it for longer (with 33e9c2b reverted), we see the same thing: number of memtable spike, system loses stability.

**Comment by glommer** [comment]
I have removed the commitlog patches (leaving the wall) , and the load is stable and much better than 1.4
Same thing when the commitlog patches land - not a lot of difference in this particular load, it doesn't really exercise any of those paths, really.

**Comment by gleb-cloudius** [comment]
On Fri, Nov 11, 2016 at 05:21:16PM -0800, Glauber Costa wrote:
> I have removed the commitlog patches (leaving the wall) , and the load is stable and much better than 1.4
> Same thing when the commitlog patches land - not a lot of difference in this particular load, it doesn't really exercise any of those paths, really.
> 
You mean with commitlog patches removed but your RFC-one-mt is the load
is better than 1.4?

--
			Gleb.

**Comment by glommer** [comment]
On Nov 12, 2016 1:57 AM, "Gleb Natapov" <notifications@github.com> wrote:
>
> On Fri, Nov 11, 2016 at 05:21:16PM -0800, Glauber Costa wrote:
> > I have removed the commitlog patches (leaving the wall) , and the load
is stable and much better than 1.4
> > Same thing when the commitlog patches land - not a lot of difference in
this particular load, it doesn't really exercise any of those paths, really.
> >
> You mean with commitlog patches removed but your RFC-one-mt is the load
> is better than 1.4?

Removed or not removed, they are much better than 1.4 as long as we don't
have this bug.

**Comment by roydahan** [comment]
The way I was able to reproduce it manually was running the exact command that sct runs it.
Using taskset and pinning to cpus on each loader.

```
taskset -c 0 /home/centos/run_cassandra_stress.sh
taskset -c 1 /home/centos/run_cassandra_stress.sh
```

While content of run_cassandra_stress.sh is:
`cassandra-stress write no-warmup cl=QUORUM duration=60m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=1000 -errors ignore -pop seq=1..10000000 -node xx.xx.xx.xx`

(The reproduction flow was: 
     running sct - getting bad performance.
     running manual with the same environment created by sct using only one c-s  command without pinning - getting good performance.
     running the mentioned above - getting bad performance.

**Comment by glommer** [comment]
On Thu, Dec 1, 2016 at 11:11 AM, Roy Dahan <notifications@github.com> wrote:

> The way I was able to reproduce it manually was running the exact command
> that sct runs it.
> Using taskset and pinning to cpus on each loader.
>
> taskset -c 0 /home/centos/run_cassandra_stress.sh
> taskset -c 1 /home/centos/run_cassandra_stress.sh
>
> While content of run_cassandra_stress.sh is:
> cassandra-stress write no-warmup cl=QUORUM duration=60m -schema
> 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=1000
> -errors ignore -pop seq=1..10000000 -node xx.xx.xx.xx
>
> (The reproduction flow was:
> running sct - getting bad performance.
> running manual with the same environment created by sct using only one c-s
> command without pinning - getting good performance.
> running the mentioned above - getting bad performance.
>

It seems easier to just stop pinning in sct.
Regardless of how 1.4 happened to behave here, pinning 1000 threads to a
single CPU in the client doesn't make for a really good test case.

**Comment by lmr** [comment]
@glommer, we tried to remove pinning, but I still don't get completely smooth graphs.

**Comment by slivne** [comment]
So after changing the concurrency of the load (reducing the loading threads from 8000 to 400) we get the following results (with @glommer patches)

1.5 performance is better than 1.4 by ~8%

full info can be found on jenkins: [1.5-glommer](http://jenkins.cloudius-systems.com:8080/job/scylla-ami-perf-regression/sub_test=test_write/52/artifact/latest/test-results/1-performance_regression_test.py%3APerformanceRegressionTest.test_write/amostation-jks-scylla-monitor-set-59865c70/) ,  [1.4](http://jenkins.cloudius-systems.com:8080/job/scylla-ami-perf-regression/sub_test=test_write/53/artifact/latest/test-results/1-performance_regression_test.py%3APerformanceRegressionTest.test_write/amostation-jks-scylla-monitor-set-be5baf86/)

the auto-generated screenshot of the stats:
![grafana-snapshot 1 5-glommer](https://cloud.githubusercontent.com/assets/3465480/21243200/7be04bbe-c320-11e6-8830-b664d3b3fa46.png)
![grafana-snapshot-1 4](https://cloud.githubusercontent.com/assets/3465480/21243199/7bdf676c-c320-11e6-9f85-cbd9ea959286.png)

**Comment by slivne** [comment]
Please note that we modified the concurrency based on input - we should move back to high concurrency and validate we do not have a bug/regression

**Comment by slivne** [comment]
closing this issue
