### ISSUE TITLE
Support JMX depricated metrics

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#1819]
The original decision was not to support deprecated JMX methods.

Some customers do use those metrics, we should support them using their new implementation.

**Comment by tzach** [comment]
@amnonh can you list the metrics?

**Comment by penberg** [comment]
@amnonh @tzach I sent a patch that I think covers most of them.

**Comment by amnonh** [comment]
@penberg I saw it and it looks good, I did find a few more, I'll do a second path after your patch will be merged.

**Comment by penberg** [comment]
So the commit that I did is https://github.com/scylladb/scylla-jmx/commit/9b63a35da6f6c6f8da2ca0e3808e7db0307fd393
