### ISSUE TITLE
Digest for data query result doesn't take tombstones into account

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#182]
It does on Origin, see `org.apache.cassandra.db.ColumnFamily#updateDigest`.

Currently digest is calculated from the `query::result` buffer, which doesn't include deletion information, only live data. We could accumulate the digest in the `query::result::builder` and feed tombstones into the digester while we build the result set.

**Comment by tgrabiec** [comment]
Digest calculation, in addition to tombstones, should also hash partition and clustering keys. Otherwise we may get same digest even though the result would be different after merging corresponding mutations.

**Comment by gleb-cloudius** [comment]
On Mon, Feb 22, 2016 at 01:50:46AM -0800, Tomasz Grabiec wrote:
> Digest calculation, in addition to tombstones, should also hash partition and clustering keys. Otherwise we may get same digest even though the result would be different after merging corresponding mutations.
> 
I am not sure I understand. When we do query::result queries we do not
merge anything. When we need to reconcile we ask for
reconcilable_result.

--
			Gleb.

**Comment by tgrabiec** [comment]
@gleb-cloudius 

We don't merge because it is assumed that if digests match we don't have to. If someone requested to query with given CL, it means the results should take into account all data on replicas needed to meet CL. If result could be different after merging mutations from replicas, digests should not match.

For example:

```
create table tb ( pk int, ck int, v int, primary key (pk, ck) );

node1 could have:

cell{pk=1, ck=1, v=0, timestamp=1}
cell{pk=1, ck=2, v=1, timestamp=2}

node2 could have:

tombstone{pk=1, ck=1, timestamp=2}
cell{pk=1, ck=2, v=0, timestamp=1}

```

Query `select v from tb limit 1;` would return the same on both nodes (`[0]`), so digests would match. But if you merged mutations from the two nodes, we would get `[1]`. We want digests to not match in this case. 

I think it's enough if we add to the digest tombstones affecting returned values, and key values (if not included in the results).

**Comment by gleb-cloudius** [comment]
On Tue, Feb 23, 2016 at 12:55:11AM -0800, Tomasz Grabiec wrote:
> @gleb-cloudius 
> 
> We don't merge because it is assumed that if digests match we don't have to. If someone requested to query with given CL, it means the results should take into account all data on replicas needed to meet CL. If result could be different after merging mutations from replicas, digests should not match.
> 
> For example:
> 
> ```
> create table tb ( pk int, ck int, v int, primary key (pk, ck) );
> 
> node1 could have:
> 
> cell{pk=1, ck=1, v=0, timestamp=1}
> cell{pk=1, ck=2, v=1, timestamp=2}
> 
> node2 could have:
> 
> tombstone{pk=1, ck=1, timestamp=2}
> cell{pk=1, ck=2, v=0, timestamp=1}
> 
> ```
> 
> Query `select v from tb limit 1;` would return the same on both nodes (`[0]`), so digests would match. But if you merged mutations from the two nodes, we would get `[1]`. We want digests to not match in this case. 
> 
> I think it's enough if we add to the digest tombstones affecting returned values, and key values (if not included in the results).
> 
This is interesting example you have here. It means that our current
code will return incorrect result for this case, so the bug priority should
be raced. But wouldn't including only tombstone into calculation fix
this particular example?

--
			Gleb.

**Comment by tgrabiec** [comment]
I also think we should raise priority.

Regarding tombstones being enough in this particular example - that depends how we choose which tombstones to hash. If we only include tombstones affecting data which appears in the results, then it wouldn't be enough because tombstone from node2 would not be included in the digest as it doesn't affect ck=2. The tombstone precedes live data in this case so it could be hashed by the query algorithm. But the example could be arranged in a way so that the tombstone relevant for node1 will be after all data which went into the results on node2. Since we don't know which tombstones could be relevant for other nodes, we would have to do a full scan over whole query range just to hash the tombstones. I think it's better if we only hash tombstones relevant for included data and in addition to that hash keys so that we can detect the case where different nodes will scan different sets of rows.

**Comment by gleb-cloudius** [comment]
On Tue, Feb 23, 2016 at 02:32:57AM -0800, Tomasz Grabiec wrote:
> I also think we should raise priority.
> 
> Regarding tombstones being enough in this particular example - that depends how we choose which tombstones to hash. If we only include tombstones affecting data which appears in the results, then it wouldn't be enough because tombstone from node2 would not be included in the digest as it doesn't affect ck=2. The tombstone precedes live data in this case so it could be hashed by the query algorithm. But the example could be arranged in a way so that the tombstone relevant for node1 will be after all data which went into the results on node2. Since we don't know which tombstones could be relevant for other nodes, we would have to do a full scan over whole query range just to hash the tombstones. I think it's better if we only hash tombstones relevant for included data and in addition to that hash keys so that we can detect the case where different nodes will scan different sets of rows.
> 
We should hash all tombstones that would otherwise made it into
reconcilable_result. It means all tombstones that was seen until
enough rows were collected plus all tombstones until next live row.

--
			Gleb.

**Comment by tgrabiec** [comment]
@gleb-cloudius Why is that? I think it is neither necessary nor sufficient to include the same set of tombstones in data query digest (needed to detect whether reconciliation is needed) as we do during reconciliation itself.

It is not sufficient to include just tombstones until next live row. Example. There are no tombstones until next live row (ck=3) on current node, the other node is missing ck=3 row and is returning data from ck=4, for which we have tombstones covering it but did not include them because they were past the next live row.

It is not necessary to include all tombstones until next live row to detect that reconciliation is needed. Results after merge could be different when:
  (1): the set of included rows (in terms of identity, by primary key) is different on different replicas
  (2): point (1) is false meaning we touch same rows but values in rows are different

I'm now starting to wonder whether we need to hash tombstones at all and hashing keys would not be enough. If we know we touched the same set of rows and that values are the same, tombstones could not affect the end result. There may be a tombstone on node2 covering some rows or cells from node1's result, but at the same time node2 must have values in that row which are not covered by that tombstone which means that after the merge we would get those values anyway. 

We already take care of detecting (2) by digesting data. Digesting keys would take care of (1).

**Comment by gleb-cloudius** [comment]
On Tue, Feb 23, 2016 at 04:37:01AM -0800, Tomasz Grabiec wrote:
> @gleb-cloudius Why is that? I think it is neither necessary nor sufficient to include the same set of tombstones in data query digest (needed to detect whether reconciliation is needed) as we do during reconciliation itself.
> 
> It is not sufficient to include just tombstones until next live row. Example. There are no tombstones until next live row (ck=3) on current node, the other node is missing ck=3 row and is returning data from ck=4, for which we have tombstones covering it but did not include them because they were past the next live row.
> 
Right.

> It is not necessary to include all tombstones until next live row to detect that reconciliation is needed. Results after merge could be different when:
>   (1): the set of included rows (in terms of identity, by primary key) is different on different replicas
We use non reconcilable results for singular queries only, so checking
primary key is in fact redundant.

>   (2): point (1) is false meaning we touch same rows but values in rows are different
> 
> I'm now starting to wonder whether we need to hash tombstones at all and hashing keys would not be enough. If we know we touched the same set of rows and that values are the same, tombstones could not affect the end result. There may be a tombstone on node2 covering some rows or cells from node1's result, but at the same time node2 must have values in that row which are not covered by that tombstone which means that after the merge we would get those values anyway. 
We wanted to hash tombstones not for correctness, but to repair if they
do not match. Otherwise much more heavy repair mechanism will kick in.

> 
> We already take care of detecting (2) by digesting data. Digesting keys would take care of (1).
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/scylladb/scylla/issues/182#issuecomment-187682161

--
			Gleb.
