### ISSUE TITLE
scylla_setup does not find all volumes available on the machine

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla#1820]
*Installation details*
Scylla version (or git commit hash):sudo scylla --version
1.3.4-20161103.ef4332a
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL 7.2

*Hardware details (for performance issues)*    C3.8xlarge     
Disks: (SSD/HDD, count) 2x 360GB SSD

When executing scylla_setup on the provisioned VM not all drives appear in the option to select:

Created symlink from /etc/systemd/system/multi-user.target.wants/ntpd.service to /usr/lib/systemd/system/ntpd.service.
Do you want to setup RAID and XFS?
It is recommended to use RAID0 and XFS for Scylla data. If you select yes, you will be prompt to choose which disks to use for Scylla data. Selected disks will be formatted in the process.
[YES/no]
Please select disks from following list:
**/dev/xvda1 /dev/xvdc** type 'done' to finish selection. selected:

While fdisk -l shows:

> ^C[ec2-user@ip-172-31-21-144 ~]$ sudo fdisk -l
WARNING: fdisk GPT support is currently new, and therefore in an experimental phase. Use at your own discretion.

Disk /dev/xvda: 32.2 GB, 32212254720 bytes, 62914560 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: gpt

#         Start          End    Size  Type            Name
 1         2048         4095      1M  BIOS boot parti
 2         4096     62914526     30G  Microsoft basic

Disk /dev/xvdb: 343.6 GB, 343568023552 bytes, 671031296 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

Disk /dev/xvdc: 343.6 GB, 343568023552 bytes, 671031296 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes

At this point it means that we have to move to a manual setup of scylla.

**Comment by tzach** [comment]
@syuu1228 any idea?

**Comment by syuu1228** [comment]
@eyalgutkind Could you check /dev/xvdb is already mounted or not?
scylla_setup tries to shows up only unused block devices, if it's mounted it should be ignored.

**Comment by slivne** [comment]
@tzach please create an issue with clearer instruction for users 

closing this for now
