### ISSUE TITLE
CQL server admission control should reply with Overloaded exception instead of blocking indefinitely

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#1823]
*Installation details*
Scylla version (or git commit hash):  767cfb4fe9e1fffff23f963ef856c7559336836a

Currently admission control of CQL server stops reading from a socket when resources are low. This may delay processing of a request for unspecified amount of time and as a result client will decide that the node is dead since response will not be delivered in time. The alternative is to reply with Overloaded error and allow client to choose another replica for the query.

**Comment by psarna** [comment]
This issue was addressed by (merged already) https://github.com/scylladb/scylla/pull/8680 - requests will be shed instead of being kept indefinitely, **assuming** their attached service level implies an interactive workload.

**Comment by slivne** [comment]
@psarna / @gleb-cloudius so can we close this ?

**Comment by psarna** [comment]
I think so, but I'll let the author decide

**Comment by gleb-cloudius** [comment]
> I think so, but I'll let the author decide

Look like the issue is addressed.
