### ISSUE TITLE
Scylla_setup on machine with > 34 hyper threads

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#1824]
Scylla version (or git commit hash): Scylla 1.4.1-20161107.5ef3211. 
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos 7.2

*Hardware details (for performance issues)*         72 vcpus
Platform (physical/VM/cloud instance type/docker): VM
Hardware: sockets= cores= hyperthreading= memory= hyperthreads

The main issue is an error in scylla_sysconfig_setup. The bc command has an env variable BC_LINE_LENGTH that needs to be set. It is 70 by default, which is only enough for machines with less than 34 cores.
Scylla needs to change the script to use export BC_LINE_LENGTH=0 so that bc will output in the correct, one-line format they expect for machines with a large number of cpus.

**Comment by avikivity** [comment]
Better to stop using bc, it's too baroque.  Better to use a python script.

**Comment by tedpearson** [comment]
Platform was actually hardware with 36 real cores with HT enabled... not that it makes any difference :)
