### ISSUE TITLE
Docker: expose Prometheus port by default

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1827]
*Installation details*
Scylla version (or git commit hash): 1.4.1

port 9180 should be open by default, allowing Prometheus and  https://github.com/scylladb/scylla-grafana-monitoring to use it.

**Comment by tzach** [comment]
@penberg is it docker file change?

**Comment by penberg** [comment]
@tzach Yes, something like this:

```patch
diff --git a/dist/docker/redhat/Dockerfile b/dist/docker/redhat/Dockerfile
index 6c301fa..1521f82 100644
--- a/dist/docker/redhat/Dockerfile
+++ b/dist/docker/redhat/Dockerfile
@@ -38,6 +38,6 @@ ADD commandlineparser.py /commandlineparser.py
 ADD docker-entrypoint.py /docker-entrypoint.py
 ENTRYPOINT ["/docker-entrypoint.py"]
 
-EXPOSE 10000 9042 9160 7000 7001
+EXPOSE 10000 9042 9160 7000 7001 9180
 VOLUME [ "/var/lib/scylla" ]
 RUN chown -R scylla.scylla /var/lib/scylla
```

**Comment by tzach** [comment]
Look good to me, did you test it?
(I'm asking because using all kind of -p 9180:9180 options in docker run did not work for me)

**Comment by penberg** [comment]
@tzach I did not test it, that's why it's a snippet in this Github issue and not a proper patch :-)

**Comment by penberg** [comment]
@tzach @amnonh Perhaps there's some Prometheus command line argument that we need to set to the Docker external IP address?

**Comment by amnonh** [comment]
We can set prometheus listening  ip address from the command line or
configuration, can it takes the external ip address while still be in a
container?

The prometheus and grafana can communicate while be in different containers

**Comment by penberg** [comment]
The question is: what IP address does Prometheus listener use by default?

We should set it to `_listenAddress` probably:

https://github.com/scylladb/scylla/blob/master/dist/docker/redhat/scyllasetup.py

**Comment by amnonh** [comment]
by default, it listens to 0.0.0.0

**Comment by Zikoel** [comment]
Hi, I see that the port was exposed only for redhat! The fix can be added on ubuntu too?

**Comment by tzach** [comment]
@Zikoel the official Scylla docker is CentOS base
https://hub.docker.com/r/scylladb/scylla/
But it should not matter, you can run it from whatever distro you want.  Hooray for Docker :)

**Comment by avikivity** [comment]
@tzach we have two docker images
