### ISSUE TITLE
scylla core dump gdb bt cannot show all frames

### ISSUE THREAD

**Issue by GpStore** [scylladb/scylla#1830]
*Installation details*
Scylla version (or git commit hash): 1.3.1-20160924
Cluster size:3
OS (RHEL/CentOS/Ubuntu/AWS AMI):centos 7.2.1511

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=128G
Disks: (SSD/HDD, count) SSD

yesterday, i got a core dump file in /var/lib/scylla/coredump
ant its size is 119G, for some reason i cannot upload to aws,
i try gdb analysis it with gdb /usr/bin/scylla core-scylla.986.xxxxxxx.xxx.xxx
and then input bt, but cannot get all the frames of the first thread,
only got this:

#0  in raise()
#1  in abort()
#2 in __gnu_cxx::__verbose_Terminate_handler() ()
#3 ?
#4 ?
#5 in gxx_personality_v0()
#6 ?
.....
#11 start_thread

my question is how to got all the frames info,  i install scylla use rpms in our env.
thanks.

**Comment by tzach** [comment]
@GpStore S3 have a 5GB limit per file.
You can `split` the file in to small chunks and upload.
See instruction here
https://github.com/scylladb/scylla/wiki/How-to-report-a-Scylla-problem#send-the-core-dump
