### ISSUE TITLE
Starting an AMI in developer mode

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1838]
*Installation details*
Scylla version (or git commit hash): 1.4.1
OS (RHEL/CentOS/Ubuntu/AWS AMI): AMI

Can I pass a dev-mode parameter to AMI before it starts? This would be useful for functional tests of unqualified, for performance, instance types, like t2.micro

**Comment by slivne** [comment]
@syuu1228 is this supported via user info

**Comment by tzach** [comment]
@syuu1228 ping

**Comment by slivne** [comment]
@syuu1228 ping
