### ISSUE TITLE
wrong use of non-wrapping range

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#1839]
In repair.cc, we have, since commit a3513653, the code

```c++
nonwrapping_range<dht::token> given_range_complement(tok_end, tok_start);
```

Because we don't have an intersect() method (or at least didn't have one at the time I wrote this), this code uses a subtract() of the complement of the range. The complement is defined here (tok_end, tok_start) - which is most definitely wrapped if the original range (tok_start, tok_end) was not wrapped.

So using nonwrapping_range here is wrong. I seems it still works today (because nonwrapping_range just deligates subtract() to wrapping_range) but may stop working in the future if the implementation changes, and needs to be fixed.

**Comment by penberg** [comment]
/cc @nyh @avikivity @asias 

Nadav sent patches to fix this on the mailing list but they have not been applied.

**Comment by slivne** [comment]
@asias - did you fix this in your series ?

**Comment by nyh** [comment]
Avi didn't like that my patch adds more uses for "wrapping_range" - apparently he'd like those to be phased out, not used more, even though here it would definitely be a correct use.

I can fix this code to use *two* subtractions of half-lines instead of one subtraction of a wrapping range (with the added complication that the user-specified token range might itself be wrapping). @avikivity, @penberg, would you perfer that?

**Comment by avikivity** [comment]
yes

**Comment by nyh** [comment]
Ok, I think this is a mistake, but I'll do it. 

Basically instead of just using code for wrapping ranges which we already have and already tested, now I need to re-invent the same wrapping-range support in ad-hoc code. Remember that the user-specified range may wrap (as is conventional in Cassandra), so it is a wrapping_range par excellence. I don't understand why you want to not use wrapping_range, where it makes sense.

**Comment by avikivity** [comment]
If you think it's a mistake please repost the patch and I'll have a 
second look.

**Comment by nyh** [comment]
The patch was a trivial one-liner (changing one wrongly typed "nonwrapping_range" to a "wrapping_range"), but also required a preparation patch to allow subtract(), which already internally worked on a wrapping range, to officially support one. See
https://groups.google.com/d/topic/scylladb-dev/K3gk3esU304/discussion

**Comment by avikivity** [comment]
I re-read, and I don't think it's a correct use of wrapping_range.  If you want a range's complement, say so, the trick of swapping start and end and using a wrapping range is hacky (IMO).

Moreover, you're looking for intersections there, and using complement+subtract.  It's better to just write and use intersection() instead.

**Comment by nyh** [comment]
On Mon, Jan 2, 2017 at 11:06 AM, Avi Kivity <notifications@github.com>
wrote:

> I re-read, and I don't think it's a correct use of wrapping_range. If you
> want a range's complement, say so, the trick of swapping start and end and
> using a wrapping range is hacky (IMO).
>

"incorrect" and "hacky" are not the same thing.
The complement was actually a tiny bit incorrect (the "inclusive" flag
should be reversed) but the swapping start and end was mostly right.

In this case, we truely have a wrapping range, coming from the user, so
it's not surprising that using the existing machinary for wrapping ranges
was convenient.

> Moreover, you're looking for intersections there, and using
> complement+subtract. It's better to just write and use intersection()
> instead.
>

I already have a new patch to implement intersect() using subtract() and
only non-wrapping ranges (one or two).
I'll submit it after I test it more - because it duplicates quite a bit of
pre-existing functionality, and I don't want to get it wrong.

**Comment by avikivity** [comment]
If the range started out as wrapped around from the user, then yes it's correct.  Still, I want to unwrap those as soon as possible, because they are hard to get right.

**Comment by nyh** [comment]
On Mon, Jan 2, 2017 at 1:09 PM, Nadav Har'El <nyh@scylladb.com> wrote:

>
>
> I already have a new patch to implement intersect() using subtract() and
> only non-wrapping ranges (one or two).
> I'll submit it after I test it more - because it duplicates quite a bit of
> pre-existing functionality, and I don't want to get it wrong.
>

I tried very hard to test this case, and couldn't get it to happen in
practice.

Turns out that commit 4ed049739a2778b76b420d240da890b56f5e1e34 in
scylla-jmx broke the handling of the startToken/endToken support, and it no
longer provides the startToken/endToken paramters as the code expects. I'll
need to fix that before I can test this case.

**Comment by tzach** [comment]
> Turns out that commit 4ed049739a2778b76b420d240da890b56f5e1e34 in
> scylla-jmx broke the handling of the startToken/endToken support, and it no
> longer provides the startToken/endToken paramters as the code expects. I'll
> need to fix that before I can test this case.

@elcallio is it a bug or a change of C* 3.0?

**Comment by slivne** [comment]
@elcallio , @nyh - the tests for repair are passing on 1.7 - I am not sure if there is still a bug

**Comment by nyh** [comment]
There are two issues here. First, there is code which sets a non-wrapping dht::token_range given_range_complement with a possibly-wrapping value, which works but may not work in the future. I have two different patches for that unapplied.

The second issue is that the broken code is dead code, it never gets called... It turns out that nodetool's starttoken/endtoken were never meant to support arbitrary ranges like I supported with this code - rather they are only supposed to work with a range which is part of a local range (a small range owned by a single node). So with the latest nodetool support from @elcallio the starttoken/endtoken parameters I invented were never set (the "token ranges" parameter was set instead) and the dead code is never called.

We have two options, I think:
1. remove this dead code, and live with Cassandra's very limited starttoken/endtoken support, just like they do.
2. Fix the support for Scylla's improved starttoken/endtoken feature - but it will be usable only through the REST API (the JMX will not use it). Note the fix isn't necessary for this feature to work (it already does) - just to fix the implementation not to use the wrapping non-wrapping range which can stop working in the future).

**Comment by slivne** [comment]
@nyh 

Trying to mix issue1,2: with regards to the small local range (owned by a single node) - can it be wrapped range - do we unwrap it correctly ?

**Comment by slivne** [comment]
I am in favor at this point with aligning with cassandra - if in the future we will want to expand the support we can do that. 

The tools that split the complete ring into ranges use the topology information, to tryt and make sure they know which nodes are loaded during repair / to spread the load between the nodes - as such I think it is ok to start with that. In the future we can expand that.

**Comment by nyh** [comment]
@slivne answering your question, yes, I think yes, the **live** code is correct:

Currently, the range the user gives with -st/-et is translated into the "ranges" option in our REST API (not the "startToken/endToken" options - that is the dead code and never get used). The repair.cc code which processes the "ranges" option assumes the user-given ranges are *wrapping* ranges, and unwraps them (see the ranges_opt() function in repair.cc which does this) and stores it into a `dht::token_range_vector ranges`, which is a std::vector<nonwrapping_range<token>>.

So the current code will work correctly and allow the user to use a small wrapping range. There is just some dead code (search start_token, end_token in repair/repair.cc) which will currently never get called, and can be deleted.

**Comment by slivne** [comment]
@nyh thanks

**Comment by asias** [comment]
> Currently, the range the user gives with -st/-et is translated into the "ranges" option in our REST API (not the "startToken/endToken" options - that is the dead code and never get used). 

@nyh I did not see any special translation of "-st/-et" to "ranges" in the rest api:
```
  0     ss::repair_async.set(r, [&ctx](std::unique_ptr<request> req) {
  1         static std::vector<sstring> options = {"primaryRange", "parallelism", "incremental",
  2                 "jobThreads", "ranges", "columnFamilies", "dataCenters", "hosts", "trace",
  3                 "startToken", "endToken" };
  4         std::unordered_map<sstring, sstring> options_map;
  5         for (auto o : options) {
  6             auto s = req->get_query_param(o);
  7             if (s != "") {
  8                 options_map[o] = s;
  9             }
 10         }
 11
 12         // The repair process is asynchronous: repair_start only starts it and
 13         // returns immediately, not waiting for the repair to finish. The user
 14         // then has other mechanisms to track the ongoing repair's progress,
 15         // or stop it.
 16         return repair_start(ctx.db, validate_keyspace(ctx, req->param),
 17                 options_map).then([] (int i) {
 18                     return make_ready_future<json::json_return_type>(i);
 19                 });
 20     });
```

Which code are you referring to?
