### ISSUE TITLE
Will not build on Fedora 24?

### ISSUE THREAD

**Issue by sharpe5** [scylladb/scylla#1844]
Checked out "master" a moment ago, followed the instructions to build scylla, and it gave this error:

> [42/272] CXX build/release/gen/cql3/CqlLexer.o
> FAILED: build/release/gen/cql3/CqlLexer.o 
> g++ -MMD -MT build/release/gen/cql3/CqlLexer.o -MF build/release/gen/cql3/CqlLexer.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I/home/Gravitas/scylla/seastar -I/home/Gravitas/scylla/seastar/fmt -I/home/Gravitas/scylla/seastar/build/release/gen  -march=nehalem -Ifmt -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DHAVE_HWLOC -DHAVE_NUMA  -O2 -Wno-maybe-uninitialized -DHAVE_LIBSYSTEMD=1 -I. -I build/release/gen -I seastar -I seastar/build/release/gen -c -o build/release/gen/cql3/CqlLexer.o build/release/gen/cql3/CqlLexer.cpp
> In file included from /usr/include/boost/config.hpp:61:0,
>                  from /usr/include/boost/functional/hash/hash_fwd.hpp:13,
>                  from /usr/include/boost/functional/hash/hash.hpp:19,
>                  from /usr/include/boost/functional/hash.hpp:6,
>                  from ./types.hh:25,
>                  from ./cql3/error_collector.hh:46,
>                  from build/release/gen/cql3/CqlLexer.hpp:63,
>                  from build/release/gen/cql3/CqlLexer.cpp:56:
> /usr/include/boost/multiprecision/cpp_int.hpp:193:4: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
>     BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
>     ^
> /usr/include/boost/multiprecision/cpp_int.hpp:416:4: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
>     BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
>     ^
> /usr/include/boost/multiprecision/cpp_int.hpp:568:4: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
>     BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
>     ^
> [43/272] CXX build/release/gen/Cassandra.o
> ninja: build stopped: subcommand failed.
> [Gravitas@Unknown-00-15-5d-01-41-0e scylla]$ 
> 

I tried switching to branch-1.5, and got the same error.

**Comment by avikivity** [comment]
Update your Fedora, it's some bug in boost that got fixed.

**Comment by sharpe5** [comment]
Yes, this fixed - had to do a "dnf update", then reboot into the new kernel.
