### ISSUE TITLE
Scylladb in docker uses 75% of CPU cores at idle when testing a cluster on one machine? 

### ISSUE THREAD

**Issue by sharpe5** [scylladb/scylla#1848]
## Summary

When I run _two_ instances of scylladb on the same machine using docker, the second instance uses 75% of CPU for all cores. If I run one instance of scylladb, then it works fine (at idle, it uses 0% of CPU).

## How to reproduce

I followed the instructions here to install Scylla in Docker:
https://hub.docker.com/r/scylladb/scylla/

After this command, all CPU cores are now at 0% usage:

```
// Run scylla in docker:
$ docker run --name some-scylla -d scylladb/scylla
```

After this command, all 24 CPU cores are now running at 75%:

```
// Make a cluster:
docker run --name some-scylla2 -d scylladb/scylla --seeds="$(docker inspect --format='{{ .NetworkSettings.IPAddress }}' some-scylla)"
```

Scylla does not appear to be doing anything, as the log is idle:
```
$ docker logs some-scylla | tail
```

I tried setting `--over-provisioned 1`, but it's still using up all of the CPU cores on my machine.

When I stop the second cluster instance, CPU core usage drops down to 0%:
```
$ docker stop some-scylla2
```

I am using Fedora 24 with the latest everything ("dnf update"). I am running Fedora in a virtual machine under Hyper-V.

**Comment by penberg** [comment]
@sharpe5 First and foremost, the default configuration in our Docker image makes _every instance_ Scylla utilize all your CPUs. So if you start two containers, both Scylla instances are fighting over all of your 24 CPUs. You can use the `--smp` command line option to `docker run` to limit that as outlined in the Docker image documentation. Please note that the same thing applies to your host memory so you need to partition the memory over the two containers.

The high CPU utilization while idle is caused by bad interaction with Docker's NAT networking and Scylla's polling architecture and `--overprovisioned` should help here by making the polling less aggressive. If it doesn't after you've configured CPU resource limits, please let us know and we'll have a look.

**Comment by sharpe5** [comment]
That makes sense. Tonight, I'll try limiting each instance to half the
CPUs. I'll let you know what the result is.

**Comment by sharpe5** [comment]
Success!

I used "--smp1" on the first instance, and "--smp 2" on the second instance, and everything is working 100% perfectly.

In this case "--over-provisioned 1" failed to prevent the excessive CPU usage.

Some solutions:
- Update Sylla so it doesn't have this issue?
- Update the following page to document this: https://hub.docker.com/r/scylladb/scylla/

My machine is a Dell T7500, 32GB RAM, dual-core, running Fedora 24 under Windows 10 Hyper-V.

**Comment by penberg** [comment]
@sharpe5 We would love to auto-detect this to get rid of the need for command line arguments, but unfortunately there are no APIs or OS services that we can leverage here to detect that we're running in a container. Nor does Docker really provide any resource limits either.

What kind of documentation updates do you mean? Resource limit configuration is explained on that page. Do you mean it needs to be emphasized better?

**Comment by sharpe5** [comment]
It is possible to detect that you are running in Docker, you can update the Dockerfile to pass in a command line parameter when starting scylladb. 

It is also possible for scylladb to coordinate with other nodes in the cluster using port 7000. If the hostname is the same, then this implies that the cluster is being tested on a single machine, so the scylladb inatances can chat over port 7000 to share resources.

I believe it is important to allow users to test scylladb on a single machine. I now knkw that scylladb is stable, as it has passed the exact same unit and stress tests as cassandra, and it is used by Futune 500 companies such as IBM. However, other people might write scylladb off in the testing phase, before they understand how great it is. I'll reopen this issue for now.

**Comment by slivne** [comment]
maybe the solution is different - maybe by default we should specify arguments that will allways limit and if the user wants to expand them he can.

So we could set --smp 1 and --memory 512M by default and if the user wants to change that he can specify something else.

**Comment by avikivity** [comment]
Then users will complain that Scylla is very slow even on a large machine.

**Comment by slivne** [comment]
@avikivity , @penberg - in my view its better to have a user able to run by default with docker then getting stuck - so maybe we should start docker with limited settings and warn about it and then have the user modify the settings.

**Comment by penberg** [comment]
We can certainly change the defaults to:

```patch
diff --git a/dist/docker/redhat/commandlineparser.py b/dist/docker/redhat/commandlineparser.py
index 00a7ca5..29da437 100644
--- a/dist/docker/redhat/commandlineparser.py
+++ b/dist/docker/redhat/commandlineparser.py
@@ -6,8 +6,8 @@ def parse():
     parser.add_argument('--developer-mode', default='1', choices=['0', '1'], dest='developerMode')
     parser.add_argument('--seeds', default=None, help="specify seeds - if left empty will use container's own IP")
     parser.add_argument('--cpuset', default=None, help="e.g. --cpuset 0-3 for the first four CPUs")
-    parser.add_argument('--smp', default=None, help="e.g --smp 2 to use two CPUs")
-    parser.add_argument('--memory', default=None, help="e.g. --memory 1G to use 1 GB of RAM")
+    parser.add_argument('--smp', default="2", help="e.g --smp 2 to use two CPUs")
+    parser.add_argument('--memory', default="2G", help="e.g. --memory 1G to use 1 GB of RAM")
     parser.add_argument('--overprovisioned', default='0', choices=['0', '1'], help="run in overprovisioned environment")
     parser.add_argument('--listen-address', default=None, dest='listenAddress')
     parser.add_argument('--broadcast-address', default=None, dest='broadcastAddress')
```

or to something more elaborate such as:

```patch
diff --git a/dist/docker/redhat/commandlineparser.py b/dist/docker/redhat/commandlineparser.py
index 00a7ca5..58a6743 100644
--- a/dist/docker/redhat/commandlineparser.py
+++ b/dist/docker/redhat/commandlineparser.py
@@ -1,13 +1,16 @@
+import multiprocessing
 import argparse
 
 
 def parse():
+    default_smp = max(1, multiprocessing.cpu_count() / 2)
+    default_memory = 1024*default_smp
     parser = argparse.ArgumentParser()
     parser.add_argument('--developer-mode', default='1', choices=['0', '1'], dest='developerMode')
     parser.add_argument('--seeds', default=None, help="specify seeds - if left empty will use container's own IP")
     parser.add_argument('--cpuset', default=None, help="e.g. --cpuset 0-3 for the first four CPUs")
-    parser.add_argument('--smp', default=None, help="e.g --smp 2 to use two CPUs")
-    parser.add_argument('--memory', default=None, help="e.g. --memory 1G to use 1 GB of RAM")
+    parser.add_argument('--smp', default=default_smp, help="e.g --smp 2 to use two CPUs")
+    parser.add_argument('--memory', default=default_memory, help="e.g. --memory 1G to use 1 GB of RAM")
     parser.add_argument('--overprovisioned', default='0', choices=['0', '1'], help="run in overprovisioned environment")
     parser.add_argument('--listen-address', default=None, dest='listenAddress')
     parser.add_argument('--broadcast-address', default=None, dest='broadcastAddress')
```

@avikivity, comments?

**Comment by sharpe5** [comment]
I think it's more important to have Scylla run with no issues out of the
box with Docker. That way, developers can check that (a) it works with some
sample CQL queries and perhaps (b) that its compatible witih Cassandra.

Perhaps make the final log entry something like this:
WARNING: Multiple copies of ScyllaDB detected. Each copy of ScyllaDB will
share CPU resources.

Usually, people run it first on Docker to see if it works and is
compatible, then they deploy it into production. In production, they will
probably deploy Scylla natively at this point (bypassing Docker), because
Docker has a layered filesystem which makes everything slower.

**Comment by tzach** [comment]
> I think it's more important to have Scylla run with no issues out of the
> box with Docker. That way, developers can check that (a) it works with some
> sample CQL queries and perhaps (b) that its compatible witih Cassandra.

I agree.

**Comment by slivne** [comment]
I agree with @tzach and @sharpe5 - yet currently the goal is by default to configure itself for performance not for eval - once the decision is changed we can change the default.
