### ISSUE TITLE
kernel:Disabling IRQ #61

### ISSUE THREAD

**Issue by yanglinqiang** [scylladb/scylla#1852]
*Installation details*
Scylla version (or git commit hash):1.4.0
Cluster size:3
OS (RHEL/CentOS/Ubuntu/AWS AMI):CentOS

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):physical
Hardware: sockets=2 cores=6 hyperthreading=2 memory=128
Disks: (SSD/HDD, count) (ssd,512G)

/etc/sysconfig/scylla-server file:
NETWORK_MODE=dpdk
TAP=tap0
BRIDGE=virbr0
IFNAME=eth0
SET_NIC=yes
ETHDRV=i40e
ETHPCIID=0000:01:00.0
NR_HUGEPAGES=128
USER=root
GROUP=root
SCYLLA_HOME=/var/lib/scylla
SCYLLA_CONF=/etc/scylla
SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack native --dpdk-pmd --dhcp 0 --host-ipv4-addr xxx.xxx.xxx.xxx --netmask-ipv4-addr  xxx.xxx.xxx.xxx --gw-ipv4-addr  xxx.xxx.xxx.xxx"
AMI=no

/etc/scylla/scylla.yaml
cluster_name: 'Test Cluster'
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: " xxx.xxx.xxx.xxx, xxx.xxx.xxx.xxx, xxx.xxx.xxx.xxx"
listen_address:  xxx.xxx.xxx.xxx
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
endpoint_snitch: GossipingPropertyFileSnitch
rpc_address:  xxx.xxx.xxx.xxx
rpc_port: 9160
api_port: 10000
api_address: xxx.xxx.xxx.xxx
batch_size_warn_threshold_in_kb: 5
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
api_ui_dir: /usr/lib/scylla/swagger-ui/dist/
api_doc_dir: /usr/lib/scylla/api/api-doc/

/etc/scylla/cassandra-rackdc.properties
dc=my_data_center_test
rack=my_rack_test
prefer_local=true

I get an error on server when starting node:
Message from syslog
kernel:Disabling IRQ #61

During scyllaDB running ,it shows error accidentally:  
Message from syslog
kernel:Disabling IRQ #61

Do you guys have meet this error, and what is the root cause of the issue? Is there any approach to resolve the problem.

Thanks.

Best Regards.

**Comment by avikivity** [comment]
It's a kernel message, not a Scylla issue.  What does `/proc/interrupts` say about irq 61? anything else in dmesg?

Note it might not be an error at all; do you see a problem?

**Comment by vladzcloudius** [comment]
AFAIR interrupts may be disabled when kernel detects a spurious interrupt.

**Comment by yanglinqiang** [comment]
/proc/interrupts 

X|cpu0|cpu1|cpu2~23|X|X
---|---|---|---|---|---
61:|100001|300003|0...|IR-IO-APIC-fasteoi|uio_pci_generic

If the error occurs during runtime, the CQL request for the node times out

**Comment by yanglinqiang** [comment]
Restart the service is complete, the log error "gossip - Fail to send Echo Message"

--  Address       Load       Tokens  Owns    Host ID                               Rack
UN  172.22.32.22  62.66 GB   256     ?       1a0f74b1-c63e-45a9-a87e-3c58b9fd309d  rack1
DN  172.22.32.21  51.91 GB   256     ?       4f6cb0c1-eaa7-4376-ad5e-a7ca44c00398  rack1
DN  172.22.32.20  78.98 GB   256     ?       96630dc1-f000-4b6e-8b2d-6ccee0d30d14  rack1


Finally start a node, with nodetool status observation, the first two nodes down state.

**Comment by avikivity** [comment]
Oh you are using dpdk mode.

**Comment by yanglinqiang** [comment]
yes!

**Comment by dorlaor** [comment]
Let's solve one issue at a time. First, does it all work when you use posix
networking?
I wonder why the uio_pci_generic complains but again, let's solve it one at
a time.
Which network card and actual machine is it?

**Comment by yanglinqiang** [comment]
use posix ，It works fine。

* network card ：
```
01:00.0 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GbE SFP+ (rev 01)
	Subsystem: Dell Ethernet 10G 4P X710 SFP+ rNDC
01:00.1 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GbE SFP+ (rev 01)
	Subsystem: Dell Ethernet 10G X710 rNDC
01:00.2 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GbE SFP+ (rev 01)
	Subsystem: Dell Ethernet 10G X710 rNDC
01:00.3 Ethernet controller: Intel Corporation Ethernet Controller X710 for 10GbE SFP+ (rev 01)
	Subsystem: Dell Ethernet 10G X710 rNDC
```
```
driver: i40e
version: 1.5.25
firmware-version: 5.04 0x800024d4 17.5.10
bus-info: 0000:01:00.1
supports-statistics: yes
supports-test: yes
supports-eeprom-access: yes
supports-register-dump: yes
supports-priv-flags: yes
```
* linux version:
```
Linux version 3.10.0-327.18.2.el7.x86_64 (builder@kbuilder.dev.centos.org) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu May 12 11:03:55 UTC 2016
```
* actual machine:DELL R730XD

dpdk use eth0 。

Thanks

**Comment by dorlaor** [comment]
Vlad, Takuya, do you have an idea what's wrong?
The IRQ prints are still from the kernel. It may be a problem to
use dpdk as a userspace driver for eth0 and the kernel's driver
for the other nics (not that there is another choice)

**Comment by yanglinqiang** [comment]
I guess the problem is the driver that scylla dbpk for eth0

**Comment by syuu1228** [comment]
There is no evidence for this, but seems like scylla is starting in DPDK mode finely, and IRQ 61 assigned to uio driver, maybe witch means DPDK user mode driver fails to mask interrupt for some reason, mistakenly reciving interrupt.
If it's DPDK problem, there is possibility that we can fix it by replacing DPDK to recent release, since we are using old version.

**Comment by yanglinqiang** [comment]
@syuu1228 
Thanks 

I stopped the scylla service，IRQ 61  , with the "cat / proc / interrupts" view, only IR-IO-APIC-fasteoi, there is no uio_pci_generic

My machine has a physical network adapter, there are four network port, I use two. Rather than two physical NIC, I do not know if this is the reason.

A few weeks later, I intend to use two physical NIC machines for testing.

**Comment by avikivity** [comment]
No updates, closing as stale.
