### ISSUE TITLE
node unavailable for a long time after restart

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#1856]
After a node restart, we start issuing compactions.

The problem is that the node doesn't seem to proceed to gossip or accepting requests while those are done. This can last for many minutes depending on the compaction backlog. After 15 minutes this gets even worse, since systemd will time us out and kill us.

**Comment by slivne** [comment]
Can you please provide logs

Is it compactions or replay of commitlog

**Comment by glommer** [comment]
On Thu, Nov 17, 2016 at 2:01 AM, Shlomi Livne <notifications@github.com>
wrote:

> Can you please provide logs
>
> Is it compactions or replay of commitlog
>
>
compactions. I'm not sure I still have the logs, will search

**Comment by avikivity** [comment]
We don't wait for these compactions to complete.  It must be something else.

**Comment by glommer** [comment]
On Thu, Nov 17, 2016 at 2:09 AM, Avi Kivity <notifications@github.com>
wrote:

> We don't wait for these compactions to complete. It must be something else.
>

Indeed that's my understanding from the code. Could it be that the
compactions are so CPU hungry nothing else can run?
Could this be an extension of the issue with quadratic behavior of
SSTables? We fixed that but never got to merge the code that actually
waited for those continuations. So it could be that we have so many that we
can't really make progress.

**Comment by tzach** [comment]
@tgrabiec @avikivity are we backporting this to 1.5?

**Comment by tgrabiec** [comment]
@tzach @avikivity I'm for backporting

**Comment by avikivity** [comment]
go ahead then.
