### ISSUE TITLE
In memory sstable summary generation is incorrect

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#1857]
*Installation details*
Scylla version (or git commit hash): f26c6569d2b32dcda34f8df2b647d83f92fd9ba5

If Summary file is missing Scylla generate summary in memory, but the code has a bug and instead of creating a map from keys to offsets into Index file it creates map to offsets into Data file.

**Comment by avikivity** [comment]
Fixed by ae0a2935b4183d86df96f81611ae68e79dc96845
