### ISSUE TITLE
Some sstable metadata files are read with default priority class

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1859]
*Installation details*
Scylla version (or git commit hash): 60b7d35f15c475df3eacae3afc469e56651cffc5

Some sstable metadata files are read (written?) with default priority class, this can slow down the process significantly under load.

**Comment by raphaelsc** [comment]
@avikivity... that's not important when booting cause transportation services aren't up, but it sounds important to refresh, right?! So I think import should have its own priority class with 100 shares.

**Comment by glommer** [comment]
Why do they need their own priority? We can just use the same priority
class as thr process that caused to be read / written.

**Comment by avikivity** [comment]
Well, refresh has no priority.  I think it can use compaction though.
