### ISSUE TITLE
dropped column families not visible for snapshots

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#1862]
Column Families that are dropped create a snapshot if the option for auto snapshotting is on (on by default).

nodetool clearsnapshot is the recommended procedure to clean them up, but those snapshots are not visible to listsnapshots, and consequentially cannot be deleted by clearsnapshot.

**Comment by slivne** [comment]
are we any different from cassandra in this ?

**Comment by glommer** [comment]
On Thu, Nov 24, 2016 at 9:34 AM, Shlomi Livne <notifications@github.com>
wrote:

> are we any different from cassandra in this ?
>

Yes.
The recommended procedure for them is to use nodetool to clean after a CF
drop.
That doesn't work for us because we iterate over all CFs in memory, not in
the filesystem.
So we don't see the snapshot as we have dropped the CF already.

**Comment by glommer** [comment]
Didn't @vladzcloudius fix this ?

**Comment by vladzcloudius** [comment]
@glommer I think this is a duplication of #2045 and it was fixed indeed.
