### ISSUE TITLE
Builds for Fedora 23+ are missing

### ISSUE THREAD

**Issue by caizixian** [scylladb/scylla#1875]
The current workaround is replace all $releasever with 22. And some of the packages need to be manually installed.(Newer version Fedora provides is not compatible)

Not sure why #889 is closed, but the problem still persist.

**Comment by penberg** [comment]
@caizixian We no longer provide RPMs for Fedora. In fact, we have not done so since Scylla 1.2.

/cc @tzach @slivne

**Comment by tzach** [comment]
@caizixian we are not generating Fedora packages for now.
We can revisit this in the future.

**Comment by tzach** [comment]
@caizixian are you using F23 in production? if you want to evaluate Scylla you can use [Scylla Docker](https://hub.docker.com/r/scylladb/scylla/)

**Comment by caizixian** [comment]
@tzach No. The production servers are running Ubuntu 16.04 LTS.

Will definitely try out the docker images.
