### ISSUE TITLE
problem with deletions

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#1883]
*Installation details*
Scylla version (or git commit hash): 1.4.1-20161107.5ef3211.el7.centos.x86_64
Cluster size:3

*Client Driver version*
java driver : Datastax  3.0
Cqlsh version : [cqlsh 5.0.1 | Cassandra 2.1.8 | CQL spec 3.2.1 | Native protocol v3]

There are problem with a deletion using cqlsh
We inserted data using the simple java program and deleted the data using cqlsh 
but  the data was not deleted..

![image](https://cloud.githubusercontent.com/assets/10610884/20612343/443ac34e-b2fc-11e6-8c4b-aa1e5cdad025.png)
![image](https://cloud.githubusercontent.com/assets/10610884/20612345/49584aa4-b2fc-11e6-8917-f85e21de9ba5.png)

*java code

package test;

import java.io.IOException;

import com.datastax.driver.core.BatchStatement;
import com.datastax.driver.core.BoundStatement;
import com.datastax.driver.core.Cluster;
import com.datastax.driver.core.ConsistencyLevel;
import com.datastax.driver.core.PreparedStatement;
import com.datastax.driver.core.Row;
import com.datastax.driver.core.Session;
import com.datastax.driver.core.SimpleStatement;
import com.datastax.driver.core.Statement;

public class deleteError {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		
		// connect
		Cluster cluster = Cluster.builder().addContactPoints("ip1","ip2","ip3").withPort(50006).build();
		Session session = cluster.connect("test");
		

		// insert			
		PreparedStatement statement = session.prepare("INSERT INTO keytest (key,value) VALUES (?,?);");
		statement.setConsistencyLevel(ConsistencyLevel.ONE);
		BoundStatement boundStatement = new BoundStatement(statement);
		session.execute(boundStatement.bind("key1","val1"));
		session.execute(boundStatement.bind("key2","val2"));
		
		// batch insert
		PreparedStatement insertPreparedStatement=null;
		BatchStatement batchStatement = null;
		String batch_key;

			batchStatement = new BatchStatement(BatchStatement.Type.UNLOGGED);
			insertPreparedStatement = session.prepare("insert into keytest(key,value) values(?,?)");
			insertPreparedStatement.setConsistencyLevel(ConsistencyLevel.ONE);
			
			for(int j=0;j<2;j++){
				batch_key = "batch" + j;
				batchStatement.add(insertPreparedStatement.bind(batch_key ,"batch value"));				
			}
			
		session.execute(batchStatement);
				
		
		session.close();
		cluster.close();
		
	}

}

**Comment by tgrabiec** [comment]
@infordb Do you have system clocks synchronized on all nodes, including the one on which you run cqlsh? 

If yes, is the row still present after you restart Scylla (all nodes)?

Is the row still present after you do this and then restart Scylla (all nodes) ?
```
nodetool flush test keytest
nodetool compact test keytest
```

If yes, please send the contents of your sstable:
```
sstable2json /var/lib/scylla/data/test/keytest-<uuid>/test-keytest-ka-*-Data.db
```

**Comment by infordb** [comment]
@tgrabiec  You are right  There was a time synchronization problem between the client and the server.
Client time is five minutes faster than Server time ( client means java program on my PC)
As a result, the deletion time is faster than the input time

insert time   (using java client)          : 1480382397635000  2016. 11. 29. 오전 10:19:57 GMT+9:00
deletion time (using cqlsh on server): 1480382101256303  2016. 11. 29. 오전 10:15:01 GMT+9:00

[root@dbtest02 keytest-86b1c0c0b5d011e6b560000000000002]# sstable2json test-keytest-ka-28-Data.db
[
{"key": "key1",
 "metadata": {"deletionInfo": {"markedForDeleteAt":1480382101256303,"localDeletionTime":1480382101}},
 "cells": [["","",1480382397635000],
           ["value","val1",1480382397635000]]}
]

**Comment by dorlaor** [comment]
Our recommendation is to rely on client time stamp and to make sure their
are synchronized using NTP.

**Comment by slivne** [comment]
@infordb I am closing this issue.

If there is anything else you need our help with with regards to this - please update the issue - we can reopen it in that case
