### ISSUE TITLE
scylla-housekeeping causes "ImportError: No module named pkg_resources" on startup

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#1884]
*Installation details*
Scylla version (or git commit hash):1.5-rc1
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL 7.3

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): EC2 c3.4xlarge

I installed scylla 1.5-rc1 from yum repository on RHEL 7.3 instance, I found that scylla-housekeeping doesn't able to run on it:
```
sudo /usr/lib/scylla/scylla-housekeeping 
Traceback (most recent call last):
  File "/usr/lib/scylla/scylla-housekeeping", line 33, in <module>
    from pkg_resources import parse_version
ImportError: No module named pkg_resources
```

**Comment by amnonh** [comment]
From a quick scan, seems yet another RHEL 7.3 related issue,
python-setuptools is
either not installed or broken.

**Comment by slivne** [comment]
@syuu1228 @amnonh - lets fix this
