### ISSUE TITLE
Enabling service on scylla_setup does not work correctly on RHEL

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#1888]
Related to #1887, we have similar problem on RHEL.
On scylla_setup, it tries to detect systemd based distribution by referencing $ID and $VERSION_ID, but doesn't included RHEL:
https://github.com/scylladb/scylla/blob/7829da13b4b9f4e3d7c66e2d57e4df92b85b85a5/dist/common/scripts/scylla_setup#L232

**Comment by slivne** [comment]
@syuu1228 is this still open or did you close it already ?

**Comment by slivne** [comment]
@syuu1228 ping

**Comment by syuu1228** [comment]
This issue fixed at https://github.com/scylladb/scylla/commit/7f2df8f86e0f0a2b4dbefcbda87df78cc393c7c5
