### ISSUE TITLE
Ubuntu 16.04 error

### ISSUE THREAD

**Issue by JafferWilson** [scylladb/scylla#1889]
I am not able to use the repository on my ubuntu system. Kindly, guide me whether is it possible to install Scylla on Ubuntu. Many Thankx.

**Comment by tzach** [comment]
Can you please paste your `/etc/apt/sources.list.d/scylla.list` ?

**Comment by JafferWilson** [comment]
I have found that there was some problem with my operating system. So I reinstalled it and now everything is working fine. So I am closing this. Thank you for your reply @tzach
