### ISSUE TITLE
Inform user that mkfs can take a very long time

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1896]
mkfs (in setup) can take a long time, up to 15 minutes on large RAIDs.  Tell the user to wait patiently or they'll suspect it's broken.

**Comment by avikivity** [comment]
linux-raid [complaint](http://marc.info/?l=linux-raid&m=148026030118626&w=2).

**Comment by syuu1228** [comment]
@avikivity Is there workaround for the issue?

**Comment by avikivity** [comment]
We can issue `blkdiscard` on individual RAID members, then create the RAID device, then `mkfs.xfs -K`, which won't be slow.

**Comment by tzach** [comment]
@syuu1228 can we have a progress bar, or any other indication of progress?

**Comment by syuu1228** [comment]
@tzach I tried to find a way to get a progress, but unfortunately mkfs.xfs doesn't have a way to get it.

**Comment by syuu1228** [comment]
@avikivity Can we close this issue when we merges devices_discard_performance=Y patch?
