### ISSUE TITLE
Load regression and instability  EC2 1.5-RC1

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1898]
Running 3 nodes i2.2xlarge Scylla cluster, with 4 c4.xlarge loaders result in a spiky load
![image](https://cloud.githubusercontent.com/assets/170200/20701807/962929ec-b61d-11e6-95eb-b7d04ef30ae7.png)

*Installation details*
Scylla version (or git commit hash): 1.5 RC1
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): ScyllaDB 1.5.1 (scylla_2016-11-23T19-42-06Z ami-38c2f22f), i2.2xlarge

Test:

Reproduce: (after updating AMI to 1.5 rc1)
```
./ec2-setup-scylla.sh -e "cluster_nodes=3" -e "instance_type=i2.2xlarge"
./ec2-setup-loadgen.sh -e "load_nodes=4" -e "instance_type=c4.xlarge" 
```

```
./ec2-stress.sh 1 -e "server=Scylla" -e "command=mixed" -e "populate=5000000,10000000,5000000" -e "stress_options='-errors ignore -schema \"replication(factor=3)\" keyspace=\"mykeyspace\"'" -e "load_name=scylla_mixed" -e "threads=2500" -e "command_options='duration=15m cl=QUORUM -mode native cql3'"
iteration 1
```

Prometheus data at s3:
scylladb-users-upload.s3.amazonaws.com/1339646e-3900-465f-a5b9-4ad5c846bfc0/prometheus_data.tar.gz

**Comment by tzach** [comment]
Note that this is a mix workload

**Comment by lmr** [comment]
Likely to be the same problem as #1817

**Comment by tzach** [comment]
restarted with 1.5, and the problem is solvedI see a different profile
Note the read error timeout 
![image](https://cloud.githubusercontent.com/assets/170200/21420583/36b1463a-c837-11e6-94a6-3fb53f4eb33f.png)

**Comment by tzach** [comment]
interesting, when running 15m and 1h loads, there is a similar pattern of a change after ~8m, with a short drop in throughput (and load) and a better performance after
![image](https://cloud.githubusercontent.com/assets/170200/21423454/c977ff46-c845-11e6-81d6-d5c96ff662a6.png)

I upload the prometheus data to: 
scylladb-users-upload.s3.amazonaws.com/37c6ad8d-d43e-4ac2-bea5-24a984ca3351/prometheus_data.tar.gz

**Comment by slivne** [comment]
Are we populating the data before the mixed workload

**Comment by tzach** [comment]
> Are we populating the data before the mixed workload

No. The stress command is at the original issue report above

**Comment by tzach** [comment]
One more example
![image](https://cloud.githubusercontent.com/assets/170200/21426982/a601b38a-c85a-11e6-9a4c-0c21434fa146.png)

**Comment by tgrabiec** [comment]
Before the speedup there are a lot of cache misses and sstable reads, but no cache insertions. Then after 7 minutes cache we start seeing insertions, cache is populated, and we start to see a lot of hits and little misses, that's why performance improves:

![screenshot from 2016-12-22 15-27-16](https://cloud.githubusercontent.com/assets/283695/21428615/2ed079d0-c85b-11e6-983a-766067ebf7db.png)

It looks like the table is not populated at first.

**Comment by tzach** [comment]
Good point
The table is **not** populated in advance, and its likely that after 7min the population starting to repeat itself. Any idea how to validate this theory?

**Comment by gleb-cloudius** [comment]
On Thu, Dec 22, 2016 at 06:43:46AM -0800, Tzach Livyatan wrote:
> Good point
> The table is **not** populated in advance, and its likely that after 7min the population starting to repeat itself. Any idea how to validate this theory?
> 
> 
Populate before running mixed test.

--
			Gleb.

**Comment by tzach** [comment]
I repeated the test with a write phase before the mixed phaese:

```
/ec2-stress.sh 1 -e "server=Scylla" -e "command=write" -e "populate=5000000,10000000,5000000" -e "stress_options='-errors ignore -schema \"replication(factor=3)\" keyspace=\"mykeyspace\"'" -e "load_name=scylla_mixed" -e "threads=2500" -e "command_options='duration=15m cl=QUORUM -mode native cql3'"

/ec2-stress.sh 1 -e "server=Scylla" -e "command=mixed" -e "populate=5000000,10000000,5000000" -e "stress_options='-errors ignore -schema \"replication(factor=3)\" keyspace=\"mykeyspace\"'" -e "load_name=scylla_mixed" -e "threads=2500" -e "command_options='duration=15m cl=QUORUM -mode native cql3'"

```

Results shows the load on both use cases is much more study.



![image](https://cloud.githubusercontent.com/assets/170200/21470251/c2e201e6-ca88-11e6-8665-b0d4120bddf4.png)
