### ISSUE TITLE
Add "jmx mode" to verify jmx is running finely, otherwise shut down urchin

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#190]
When "jmx mode" specified via program argument(default off), urchin waits connection from jmx.
If connection won't come in 5 sec(or 10 sec, it should able to specify in program argument), shutdown itself.
This is required for "watchdog" idea, we need to confirm both urchin and jmx is running in together.
Another case that urchin is not running but jmx is running, will handle by this feature:
https://github.com/cloudius-systems/urchin-jmx/issues/2

**Comment by slivne** [comment]
not sure it is correct todo this
