### ISSUE TITLE
How to  improve repair performance?

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#1903]
*Installation details*
Scylla version : 1.4.1
Cluster size: 2

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):physical
Hardware: sockets= cores= hyperthreading= memory= 8core / 32GB
Disks: (SSD/HDD, count) : SDD

we can not use stream_throughput_outbound_megabits_per_sec parameter
What is the way to improve repair performance?

## /var/log/messages
Nov 30 08:41:12 stgtest02 scylla: [shard 0] config - Option stream_throughput_outbound_megabits_per_sec is not (yet) used.

## ScyllaDB don't use more than 25m IO.
![image](https://cloud.githubusercontent.com/assets/10610884/20735148/9460edce-b6e1-11e6-9844-14d757793479.png)

**Comment by gleb-cloudius** [comment]
The purpose of stream_throughput_outbound_megabits_per_sec is not to
improve repair performance, but actually _limit_ amount of bandwidth it
will consume (aka making it slower). We do not support this yes, so our
repair will not limit itself, but for some unrelated reason it uses very
little bandwidth anyway, it should use much more.

--
			Gleb.

**Comment by infordb** [comment]
@gleb-cloudius  Is there no user-configurable part to improve repair performance?

**Comment by gleb-cloudius** [comment]
On Wed, Nov 30, 2016 at 06:13:24PM -0800, Junghyun Park wrote:
> @gleb-cloudius  Is there no user-configurable part to improve repair performance?
> 
No. There shouldn't be a user-configurable part to improve repair
performance. Repair should be as fast as possible, but without
saturating disk and networking. Currently we have several inefficiencies
with repair - it sends to much data and does not always utilize enough
bandwidth (depends on partition sizes and how many ranges are repaired
in parallel). We are working on fixing them.

--
			Gleb.

**Comment by asias** [comment]
We are working on patches to make the data send over network to be more compact: 1) compress the data e.g. lz4, 2) introduce frozen_streaming_mutation so we do not send the table_id and schema_version for each streaming verb, 3) batch the streaming verb to have less overhead and to get better compression result

**Comment by slivne** [comment]
@asias do you think we fixed this in 2.0/1.7.3+ - can we close this

**Comment by tzach** [comment]
@asias ping

**Comment by asias** [comment]
We ended up to add more parallelism to repair on all the shards to improve repair performance. I think we can close this issue for now.
