### ISSUE TITLE
Scylla 4.5.3 start hangs with status "loading non-system sstables"

### ISSUE THREAD

**Issue by vszakd** [scylladb/scylla#19046]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.5.3-0.20211223.c8f14886d
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 18.04.6 LTS

*Hardware details (for performance issues)*          
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets=2 cores=48 hyperthreading=y memory=128G

Hello,
After a reboot, trying to boot any node of a three nodes cluster hangs (more than 2 hours) with systemd status "loading non-system sstables".

The hosts before the restart were running correctly with no problems.

Last logs are:
```
Jun 03 11:22:36 host scylla[2315]:  [shard 0] database - Populating Keyspace system_distributed
Jun 03 11:22:36 host scylla[2315]:  [shard 0] database - Keyspace system_distributed: Reading CF view_build_status id=5582b59f-8e4e-35e1-b913-3acada51eb04 version=e61ea49b-8dbc-3f
Jun 03 11:22:36 host scylla[2315]:  [shard 0] database - Keyspace system_distributed: Reading CF cdc_streams_descriptions_v2 id=0bf73fd7-65b2-36b0-85e5-658131d5df36 version=58a18c
Jun 03 11:22:36 host scylla[2315]:  [shard 0] database - Keyspace system_distributed: Reading CF cdc_generation_timestamps id=fdf455c4-cfec-3e00-9719-d7a45436c89d version=5777e043
Jun 03 11:22:36 host scylla[2315]:  [shard 0] database - Keyspace system_distributed: Reading CF cdc_generation_descriptions id=ae653406-7b3e-34aa-af70-d5b90f837c67 version=95e9e1
Jun 03 11:22:36 host scylla[2315]:  [shard 0] database - Populating Keyspace system_auth
Jun 03 11:22:36 host scylla[2315]:  [shard 0] database - Keyspace system_auth: Reading CF roles id=5bc52802-de25-35ed-aeab-188eecebb090 version=3b1020ca-0a53-3c07-aaff-4ce4d858299
Jun 03 11:22:36 host scylla[2315]:  [shard 0] database - Keyspace system_auth: Reading CF role_members id=0ecdaa87-f8fb-3e60-88d1-74fb36fe5c0d version=dd3c0d70-d1bd-3098-a5d2-299c
```

Thanks.

**Comment by mykaul** [comment]
> Scylla version (or git commit hash): 4.5.3-0.20211223.c8f14886d

4.5.3 is a bit outdated version of Scylla - we've had multiple versions since (many!), and we support these days 5.2.x and 5.4.x (and to be honest, 6.0 is going to GA very soon).
