### ISSUE TITLE
repair issue

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#1907]
*Installation details*
Scylla version (or git commit hash): 1.4.1
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

We tested repair function..
(2node , 2 replication factor , consistency level  one)

Test Scenarios
 1. Loading 65G data on each 2 node
 2. shutdown node #2
 3. Add 65G data to node #1 
    As a result, node #1 has 130G of data and node #2 has 65G of data
 4. start node #2
 5. Run repair command on node #2

We expected about 65G of data to move from node #1 to node #2
Unlike what we thought, 
data moved in both directions and disk volume also increased beyond expectations
(node #1 has about 250G , node #2 has about 200G)
Could you describe the results of this test?

$$ reactor
![image](https://cloud.githubusercontent.com/assets/10610884/20740582/8b96d426-b707-11e6-9e03-da5185f1b51d.png)

$$ netowrk
![image](https://cloud.githubusercontent.com/assets/10610884/20740592/9e5cd02e-b707-11e6-836d-78ef6517e2c9.png)
![image](https://cloud.githubusercontent.com/assets/10610884/20740598/a705db8a-b707-11e6-92ec-2e012264656f.png)

$$ compaction
![image](https://cloud.githubusercontent.com/assets/10610884/20740609/c40f88ac-b707-11e6-90fb-6302cf5813d0.png)

$$ stream
![image](https://cloud.githubusercontent.com/assets/10610884/20740623/e3e2b44c-b707-11e6-99f3-819b2915ae08.png)

$$ disk volumn
![image](https://cloud.githubusercontent.com/assets/10610884/20740658/3d1ea37c-b708-11e6-9ec1-d39d09c0c325.png)

Loading data on November 29th
Repair performed on November 30th
The repair generated approximately 130G of data for each node
I don't understand this ...
![image](https://cloud.githubusercontent.com/assets/10610884/20873828/207badec-baef-11e6-8f34-7b781e209f40.png)

**Comment by infordb** [comment]
$$ node #1 log
Nov 30 09:09:36 stgtest01 scylla: [shard 1] stream_session - [Stream #8c7216f1-b68d-11e6-91d2-000000000000] Creating new streaming plan for repair-in, with 70.60.31.155
Nov 30 09:09:36 stgtest01 scylla: [shard 1] stream_session - [Stream #8c7216f1-b68d-11e6-91d2-000000000000] Prepare completed with 70.60.31.155. Receiving 0, sending 1
Nov 30 10:55:36 stgtest01 scylla: [shard 1] stream_session - [Stream #8c7216f1-b68d-11e6-91d2-000000000000] Session with 70.60.31.155 is complete, state=COMPLETE
Nov 30 10:55:36 stgtest01 scylla: [shard 1] stream_session - [Stream #8c7216f1-b68d-11e6-91d2-000000000000] bytes_sent = 498633445152, bytes_received = 0
Nov 30 10:55:36 stgtest01 scylla: [shard 1] stream_session - [Stream #8c7216f1-b68d-11e6-91d2-000000000000] All sessions completed, peers={70.60.31.155}
Nov 30 10:55:36 stgtest01 scylla: [shard 1] stream_session - [Stream #8c7216f0-b68d-11e6-91d2-000000000000] Creating new streaming plan for repair-out, with 70.60.31.155
Nov 30 10:55:36 stgtest01 scylla: [shard 1] stream_session - [Stream #8c7216f0-b68d-11e6-91d2-000000000000] Prepare completed with 70.60.31.155. Receiving 1, sending 0
Nov 30 13:02:34 stgtest01 scylla: [shard 1] stream_session - [Stream #8c7216f0-b68d-11e6-91d2-000000000000] Session with 70.60.31.155 is complete, state=COMPLETE
Nov 30 13:02:34 stgtest01 scylla: [shard 1] stream_session - [Stream #8c7216f0-b68d-11e6-91d2-000000000000] bytes_sent = 0, bytes_received = 498333900268
Nov 30 13:02:34 stgtest01 scylla: [shard 1] stream_session - [Stream #8c7216f0-b68d-11e6-91d2-000000000000] All sessions completed, peers={70.60.31.155}


$$ node #2 log
Nov 30 08:42:54 stgtest02 scylla: [shard 0] repair - starting user-requested repair for keyspace spatch, repair id 1, options {incremental=false, parallelism=0, primaryRange=false}
Nov 30 09:09:36 stgtest02 scylla: [shard 0] stream_session - [Stream #8c7216f1-b68d-11e6-91d2-000000000000] Executing streaming plan for repair-in
Nov 30 09:09:36 stgtest02 scylla: [shard 0] stream_session - [Stream #8c7216f1-b68d-11e6-91d2-000000000000] Starting streaming to 70.60.31.154
Nov 30 09:09:36 stgtest02 scylla: [shard 0] stream_session - [Stream #8c7216f1-b68d-11e6-91d2-000000000000] Beginning stream session with 70.60.31.154
Nov 30 09:09:36 stgtest02 scylla: [shard 0] stream_session - [Stream #8c7216f1-b68d-11e6-91d2-000000000000] Prepare completed with 70.60.31.154. Receiving 1, sending 0
Nov 30 10:55:36 stgtest02 scylla: [shard 0] stream_session - [Stream #8c7216f1-b68d-11e6-91d2-000000000000] Session with 70.60.31.154 is complete, state=COMPLETE
Nov 30 10:55:36 stgtest02 scylla: [shard 0] stream_session - [Stream #8c7216f1-b68d-11e6-91d2-000000000000] bytes_sent = 0, bytes_received = 498633445152
Nov 30 10:55:36 stgtest02 scylla: [shard 0] stream_session - [Stream #8c7216f1-b68d-11e6-91d2-000000000000] All sessions completed, peers={70.60.31.154}
Nov 30 10:55:36 stgtest02 scylla: [shard 0] stream_session - [Stream #8c7216f0-b68d-11e6-91d2-000000000000] Executing streaming plan for repair-out
Nov 30 10:55:36 stgtest02 scylla: [shard 0] stream_session - [Stream #8c7216f0-b68d-11e6-91d2-000000000000] Starting streaming to 70.60.31.154
Nov 30 10:55:36 stgtest02 scylla: [shard 0] stream_session - [Stream #8c7216f0-b68d-11e6-91d2-000000000000] Beginning stream session with 70.60.31.154
Nov 30 10:55:36 stgtest02 scylla: [shard 0] stream_session - [Stream #8c7216f0-b68d-11e6-91d2-000000000000] Prepare completed with 70.60.31.154. Receiving 0, sending 1
Nov 30 13:02:34 stgtest02 scylla: [shard 0] stream_session - [Stream #8c7216f0-b68d-11e6-91d2-000000000000] Session with 70.60.31.154 is complete, state=COMPLETE
Nov 30 13:02:34 stgtest02 scylla: [shard 0] stream_session - [Stream #8c7216f0-b68d-11e6-91d2-000000000000] bytes_sent = 498333900268, bytes_received = 0
Nov 30 13:02:34 stgtest02 scylla: [shard 0] stream_session - [Stream #8c7216f0-b68d-11e6-91d2-000000000000] All sessions completed, peers={70.60.31.154}

**Comment by asias** [comment]
Let me explain how repair works in scylla.

When repair is run on node2, node2 will do checksum for sub ranges, when a mismatch of checksum is found, node2 will fetch data from node1, and merge the data with its local version of data. After that, node2 will send the merged data back to node1. 

This is why you see data goes in two directions.

We do have optimization for the case if node2 as zero data for a sub range, data will only be fetch from node1 and no data will be sent back to node1.

We are working actively in repair and streaming to make both of them more efficient.

**Comment by asias** [comment]
@infordb In step "3) Add 65G data to node #1", did you insert data with different partition key? What happens if you run ```$nodetool cleanup``` on both nodes, will the disk usage shrink?

**Comment by infordb** [comment]
@asias  In step 3, The added 65G data has a different partitioning key. and after running $nodetool cleanup the disk usage shrank

I don't understand 2 parts..

1. 
node2 already has a partition key of 65G and does not have the added 65G partition key
If so, I think node2 has to fetch added 65G partition key from node1,
But node2 fetched all partition key of 130G from node1,

2. 
why does node2  send the merged data back to node1 ?

**Comment by asias** [comment]
@infordb For 1) It is due to the fact that checksum is calculated in the granularity of sub ranges (currently, contains 100 partitions), it is mostly certainly the 100 partitions contain both the "old" and "new"  data. So the checksum between node 1 and node2 will always be different. For 2), currently node2 does not know if node1 has the data node2 owns, so node2 has to send back the data. Imagine there are 3 nodes, node2 is the repair master,  node2 will fetch data from both node1 and node3, and merge the data from node1  and node3.

**Comment by asias** [comment]
@infordb btw, it would probably be faster if you delete all data on node2 then run repair on node2, since checksum on node2 will be empty,  so node2 will only fetch data from node1, sending of merged data back to node1 will be ignored.

**Comment by infordb** [comment]
@asias If the node is down for a long time and data inconsistency occurs
do you recommand to run nodetool repair after deleting all the data of the downed node?

**Comment by asias** [comment]
On Dec 5, 2016 18:09, "Junghyun Park" <notifications@github.com> wrote:

@asias <https://github.com/asias> If the node is down for a long time and
data inconsistency occurs
do you recommand to run nodetool repair after deleting all the data of the
downed node?


No, only if we are sure node 1 has all the data node 2 has. Anyway, it is
not recommended.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/scylladb/scylla/issues/1907#issuecomment-264814632>,
or mute
the thread

**Comment by slivne** [comment]
@asias do you think we fixed this in 2.0/1.7.3+ - can we close this

**Comment by tzach** [comment]
@asias ping

**Comment by asias** [comment]
No. Rolling repair will improve number of bytes transferred on wire.

**Comment by tzach** [comment]
@asias is rolling repair the same as inc repair or is it a different feature?

**Comment by asias** [comment]
It has nothing to do with incremental repair. It is a new internal algorithm in repair core.

**Comment by avikivity** [comment]
New repair alogorithm in place, closing.
