### ISSUE TITLE
Update to 1.4.2 adds nologin on RHEL 7

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla#1908]
*Installation details*
Scylla version (or git commit hash): 1.4.2-20161124.0d62235.el7.centos
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL

After updating today to 1.4.2 I can no longer login to the node after restart.
I keep getting 
```bash
System is booting up. See pam_nologin(8)
Connection closed by 172.27.84.175
```
when I try to login with ssh.
I was careful to just update scylla, scylla-server and scylla-jmx to avoid further systemd issues.

My guess is that nologin is added somewhere and that provokes the response from pam (or whatever is actually denying access).

Any ideas?

**Comment by avikivity** [comment]
There was no systemwide changes.

Did you restart the node, or just the Scylla services?

**Comment by dahankzter** [comment]
I restarted the the node. On the other cluster member I have waited. Nodetool reports a correctly formed cluster so it seems to be a side effect or something.

**Comment by dahankzter** [comment]
I attempted a scylla service restart on the node that is up and I get:

```bash
sudo systemctl restart scylla-server.service
[sudo] password for hejo12:
[hejo12@app91.test.content.eniro ~]$
Broadcast message from systemd-journald@app91.test.content.eniro (Thu 2016-12-01 09:40:13 CET):

systemd[1]: Caught <ABRT>, dumped core as pid 3675.


Broadcast message from systemd-journald@app91.test.content.eniro (Thu 2016-12-01 09:40:13 CET):

systemd[1]: Freezing execution.


Message from syslogd@app91 at Dec  1 09:40:13 ...
 systemd:Caught <ABRT>, dumped core as pid 3675.

Message from syslogd@app91 at Dec  1 09:40:13 ...
 systemd:Caught <ABRT>, dumped core as pid 3675.

Message from syslogd@app91 at Dec  1 09:40:13 ...
 systemd:Freezing execution.

Message from syslogd@app91 at Dec  1 09:40:13 ...
 systemd:Freezing execution.
```

**Comment by dahankzter** [comment]
The house keeping service seems to have come back which is perhaps expected.
Perhaps thats what has happened on the restarted node.

**Comment by avikivity** [comment]
This looks very much like the systemd bug that we saw on RHEL 7.3.

**Comment by avikivity** [comment]
Ah, maybe it triggers the bug.  You can try to login in rescue mode, disable that service and reboot.

**Comment by avikivity** [comment]
@syuu1228 help!

**Comment by dahankzter** [comment]
Yes I have asked ops to get vmware terminal running to see if it can be removed.

**Comment by dahankzter** [comment]
the other node restart worked fine. Only difference was removal of the housekeeping service.

**Comment by avikivity** [comment]
So it's the systemd bug, maybe there was an update to RHEL 7.2 which triggered it?

Anyway, we should release 1.4.3 shortly, it's a very dangeous bug. @slivne

**Comment by dahankzter** [comment]
It is hard to determine. I thought we were on 7.1... Ill verify it.
The other node successfully up after ops removed the housekeeping service so that was the culprit.

**Comment by avikivity** [comment]
Ref #1846

**Comment by dahankzter** [comment]
```bash
cat /etc/os-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.1 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.1"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.1 (Maipo)"
```

Kernel updated separately which brought in newer xfs utils but thats basically it.

**Comment by slivne** [comment]
there is a patch from @syuu1228 to resolve this on the mailing list

**Comment by slivne** [comment]
1.4.3 has been released to workaround the issue in systemd, you can upgrade to that. 

Closing the issue @dahankzter if there is still an issue please update and we will reopen.
