### ISSUE TITLE
Repair should checksum and stream in parallel

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#1910]
The current repair code (after refactoring by @asias) divides the large range into many small sub-ranges, calculates checksums for all these ranges, and for each range also asks the other replicas to checksum them and compares the results. Only after the comparisons for **all the sub-ranges** are done, and we built a long list of subranges that need repair - only then do we start streaming the ranges we need to stream.

I don't think we deliberately want to start streaming only after all the comparisons are in. Starting to stream in parallel with continuing to checksum can make repair faster. Perhaps more importantly, it will allow us to pick the checksum granularity to be as fine as we wish, without worrying that the list of all changes will be too long (a recent patch from @asias made the subranges larger just for reducing the length of this list - even if for other reasons we might want to have small subranges).

Before the refactoring, the repair code started to stream a subrange as soon as it was found to have differing checksums - in parallel with continuing to checksum more subranges. This was inefficient because the small stream plans were inefficient. We need something between many tiny stream plans the current single one. Namely, collect mismatched ranges in a stream plan, and every once in a while, start this stream plan. Of course, with flow control (if collected too many mismatched ranges, pause the checksumming process).

**Comment by slivne** [comment]
@asias, @nyh - didn't we change this - I think the current version checksums and streams in parallel

**Comment by nyh** [comment]
@slivne unfortunately the short answer is NO, or more accurately, not quite YES.

The long answer:

After we fill one stream plan with 10240 ranges (that amounts to about a million partitions that need to be streamed. I already said I think that this default is excessive, but that's besides the point), request_transfer_ranges() starts the actual streaming of that stream plan, and waits for it while holding the semaphore sp_parallelism_semaphore.
The next time we find a small (100-partition) range that differs, we hang waiting on sp_parallism_semaphore. The checksumming does not completely hang at this point, because we have 100 (parallelism_semaphore) fibers all doing checksumming and only one of those hung on this semaphore. But after we find 100 differing ranges, all of the available fibers hang. Remember that we collected as many as 10240 differing ranges before starting to stream - so after just 1% more are found in parallel with the streaming, we stop checksumming until the streaming is done. If the streaming process (of the little that needs to be streamed, only) is not 100 times faster than the checksumming process, they will NOT happen in parallel.


To clarify: Yes, we do need flow control for this parallelism: If the streaming part is slower than the checksumming part (e.g., because the network is slow and/or a lot of data had differences), we shouldn't continue checksumming and building a huge and growing backlog of ranges we need to stream. However, if streaming and checksumming have the same speed - e.g., it takes 10 minutes to checksum enough ranges to fill a stream plan and then another 10 minutes to run that stream plan - then we should do those two things in parallel. This is not what happens today: We start by checksumming alone for 10 minutes (with no streaming in parallel, yet), then start streaming in parallel with more checksumming, but after less than 6 seconds (1/100 of 10 minutes) we hang all checksumming fibers, and for the next almost 10 minutes, streaming will run alone. If streaming is limited by the network bandwidth, this means we don't fully utilize the disk bandwidth (which checksumming could).

@asias, I remember already saying all this (more or less) in my code review, and suggested several alternatives including setting sp_parallism_sempahore to 2 and a more advanced double-buffering technique, but you were fine with the code as is. So now it's your turn to explain it to @slivne  :-)

**Comment by asias** [comment]
Allow sp_parallism_sempahore 2 won't help much.  We will need to wait for streaming to complete anyway because we have the limit on the number of checksum mismatched ranges we can collect. For the first stream_plan we allow 10240/2 ranges, for the second stream_plan we allow 10240/2 ranges, at the point we find 10240 mismatched ranges, no matter how we "buffer", we have to stop and wait for streaming to complete. 

Note, now repair checksum runs on all shards, when one shard is not running checksum and running stream, the other shards can perfectly run checksum to utilize disk bandwidth. In this sense, we do run checksum and streaming in parallel. 

Also, I think the original bug report is for "we do checksum phase then we do on giant stream_plan".

And with rolling repair, streaming will not be used at all.

**Comment by nyh** [comment]
@asias my responses:

In your first comment about sp_parallelism_semaphore not helping, I think you are wrong, please see my explanation above why in some cases (when the streaming part is roughly the same speed as checksumming or faster) it will be helpful.

But your comment about doing the whole process on several shards and each of them being on different phases is interesting. Especially when repair is limited by disk or network bandwidth - which are both shared by all shards - it is indeed fine that one shard bangs the network only, while another shard bangs the disk. it's not perfect though, and not as smooth as we could have had with real double-buffering; For example, initially, all shards will be doing checksumming for a significant time, before they all (assuming they have roughtly the same amount of work to do) start streaming at roughly the first time. Of course, in a long repair and a lot of shards, random fluctiuations will eventually even things.

Regarding the "purpose" of this bug, there are two separate issues - one is the amount of memory used, which was already solved. The second is repair performance. As I see it, the current algorithm can at the worst case (when checksumming-alone and streaming-alone take roughly the same time) double the repair time.  We also had issue #2430 which taked about the memory use, so I thought this issue was left about the performance issue. I guess we should decide.

**Comment by asias** [comment]
Since the new row level repair is merged and we will focus on the new repair. Can we close this now? @nyh
