### ISSUE TITLE
Overhaul parallelism in repair master

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#1912]
The repair-master code running on a single host has a lot of parallelism:  We start repair of many large ranges (vnodes) in parallel, and for each of those we split them into many small ranges and checksum those in parallel. To limit this parallelism, the inner part (the checksumming of the small range) uses a semaphore, limiting the number of parallel runs of that code to parallelism=100.

The biggest drawback in this technique is that it can add a lot of latency: The checksumming calculation is CPU intensive, because after reading a buffer of partitions from disk it needs to checksum all of it (or up to 2ms, our default task quota, whichever comes first). If we allow 100 of these to run in parallel, it means we can have on the list of ready-to-run continuations as many as 100 of these continuations, so a new request that comes in may be delayed by up to 200ms before it gets a chance to run! In practice, in some tests we've seen 99%ile latencies going up to about 40ms.

This technique also does not guarantee that we use all the shards in parallel. To some degree we do - because the different large ranges try to push their small pieces of work to the semaphore in parallel one at a time - and these small pieces of work from different large ranges are likely to belong to different shards - but we don't take any steps to make the fairness of this process more explicit.

I think we should do the sharding more explicit, and lower the cpu parallelism on each shard to 1:

1. First, split the large ranges into a list of ranges belonging to shards shards, and tell each shard a list of ranges it needs to work on. (this should probably be an iterator intersecting a range with a shard - not a list, because of the recent sharding changes).
2. In each shard, do a sequential, not parallel, loop, for checksumming all its subranges. But:
  2a. To ensure that disk parallism is used, make sure that read-ahead is enabled.
  2b. As soon as calculation of the checksum on one subrange is done, continue on to the next (partitions already read-ahead); Do not wait for the remote end to finish their checksums and comparing them before continuing. However, use a semaphore to ensure we block when we have too many outstanding checksum requests to remote checksums are out there (flow control).
3. We could be even more efficient on the master if we read the large ranges sequentially from disk, and don't seek to every small range separately (we know that these ranges are consecutive anyway, in the master).

**Comment by avikivity** [comment]
@asias I'm guessing this is fixed with row-level repair.

**Comment by nyh** [comment]
Closing this issue - the row-level repair is designed completely differently, and if it has bugs, they are probably different from those of the old implementation.
