### ISSUE TITLE
Idle-time cache LRU tail repacker

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1921]
Currently, we use idle time to pack LSA segments, increasing memory efficiency.  That makes it harder, however, to find a low occupancy LSA segment to free when we do need to allocate a new segment.

We could have an idle time repacker, wither in conjunction with the current repacker or replacing it, that picks items off then end of the LRU end performs a deep copy (rather than a move).  This will get all the items at the tail of the LRU occupying a single segment.  When the time comes to reclaim memory, the LRU has an easy job: just delete items of the end, pretty soon you get an empty segment.

The reclaimer and tail repacker could communicate on the effectiveness of the scheme, with the repacker hinting how many items need to be freed, and the reclaimer responding with how empty the resulting segment was (cache hits at the tail of the LRU reduce effectiveness).

**Comment by haaawk** [comment]
Could you give a little more details @avikivity? How does it work when we have two copies of an item? Which copy is referenced from cache? Why copying gives us a guarantee that all items at the end of LRU are in the single segment?

What would a single step of a repacker do? Iterate back from the end of the LRU until it finds the first item that's on a different segment than previous items and then copy (why not move?) the item to the segment where the previous items are?

**Comment by avikivity** [comment]
The original is destroyed.  The reason we need to make a deep copy, is that eviction performs a deep free, so we want all components of the entry to be in the same segment.

We can't to a move(), because that will only move the item root; any sub-objects will remain scattered in LSA.

**Comment by haaawk** [comment]
Ok. I get it now. Thanks. And the repacker job is to take as many items from the end of the LRU as possible and pack them into a single new segment. To make it work well with eviction we would have to make sure that nothing else is allocated on this segment. Is there any mechanism to do that right now? Another thing is to make sure that when an item is touched it get's copied out from the segment.

**Comment by avikivity** [comment]
No mechanism right now.  We might have a separate open segment for repacker work.

There's no need to copy it out of the segment if it is touched.  Eviction will end up with a segment that isn't completely empty, so it will move the data out just like it does now.

**Comment by haaawk** [comment]
Ok. I see.

**Comment by tgrabiec** [comment]
I think depends on #2576. Until LRU is switched to row level, copying large partitions would be problematic.

**Comment by avikivity** [comment]
Agree (though implementation is independent). #2576 is crucial for other reasons anyway.

**Comment by tgrabiec** [comment]
The repacker should use a separate active segment, so that old items don't get mixed with the new items.

**Comment by avikivity** [comment]
Obsoleted by ca0c006b372309bc3c857242ea7a504fe453ff08. It evicts 60MB worth rather than repacking, but I think it amounts to the same thing.
