### ISSUE TITLE
column family index .db filenames with dots cause malformed_sstable_exception

### ISSUE THREAD

**Issue by vdm** [scylladb/scylla#1923]
*Installation details*
Scylla version (or git commit hash): 1.4.2-20161124.0d62235 
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos

```[shard 0] database - Exception while populating keyspace 'foo' with column family 'bar' from file '/data/foo/bar-e48164baa1df3ff18ead280b073d8387': sstables::malformed_sstable_exception (invalid version for file foo-bar.bar_id_idx-ka-58-Statistics.db. Name doesn't match any known version.)```

This column family name is `bar.bar_id_idx`, but is parsed as `bar`. If it split on hyphen character this might work. These CF files are from Cassandra 2.1.15 where they work fine.

**Comment by penberg** [comment]
I suppose the regular expression we use to detect the sstable version from filename is broken.

/cc @glommer @raphaelsc

**Comment by raphaelsc** [comment]
In C* 2.1.18, the following commands results in creation of a component without a dot between keyspace and cf names: 
cqlsh> create keyspace foo_bar with replication = {'class':'SimpleStrategy', 'replication_factor':1};
cqlsh> create TABLE foo_bar.bar_id_idx (     p1 text,     c1 int,     PRIMARY KEY (p1)   ) WITH compression = {};
cqlsh> insert into foo_bar.bar_id_idx (p1, c1) values ('key',1);

@vdm: Could you please tell me which commands you used?

I think there's also a problem with the migration. Directory foo should be foo-bar and bar-... directory should be bar_id_idx-... instead. Those should match keyspace and column family names. Were those directories generated from C*?

As @penberg observed, I think we need to modify regular expression (as follow) to allow dot as an alternative to separate keyspace and cf names. We'd also need to change sstable::filename() variants.

**Comment by vdm** [comment]
@raphaelsc The .db file in the error is for an index rather than a CF. Also, the KS and CF names are a little different.

    CREATE KEYSPACE foo WITH replication = {'class': 'NetworkTopologyStrategy', 'dc': '3'}  AND durable_writes = true;

    CREATE TABLE foo.bar (
    agentname text PRIMARY KEY,
    hostid text,
    id text,
    checkcode text
    ) WITH bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL", "rows_per_partition":"NONE"}'
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.1
    AND speculative_retry = '99.0PERCENTILE';
    CREATE INDEX bar_id_idx ON foo.bar (id);
    INSERT INTO foo.bar (agentname,hostid,id,checkcode) VALUES ('the_agent','the_host','the_id','the_checkcode');

**Comment by slivne** [comment]
@vdm we do not support secondary indexes at this time 

you can track #401
