### ISSUE TITLE
scylla_io_setup accepts ext4 filesystem for /var/lib/scylla, but scylla-server doesn't

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#1933]
On recent revision of Seastar, iotune(called from scylla_io_setup) accepts ext4 filesystem:
```
syuu@syuu-VJZ131:~$ sudo scylla_io_setup
Generating evaluation file sized 10GB...10GB written in 7 seconds
Refining search for maximum. So far, 301648 IOPS
Maximum throughput: 301648 IOPS
Recommended --max-io-requests: 75
Written the above values to /etc/scylla.d/io.conf
syuu@syuu-VJZ131:~$ mount|grep ext4
/dev/nvme0n1p5 on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
```

But Scylla doesn't:
```
scylla[647]:  [shard 0] init - /var/lib/scylla/commitlog is not on XFS. This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is required. To override this error, see the developer_mode configuration option.
scylla[647]:  [shard 0] init - /var/lib/scylla/data is not on XFS. This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is required. To override this error, see the developer_mode configuration option.
scylla[647]:  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (invalid configuration: path "/var/lib/scylla/commitlog" on unsupported filesystem)
```

If we don't want to accept ext4 filesystem at this point, we probably reject it in scylla_setup (witch calls scylla_io_setup so scylla_io_setup can do that), warn user not to use the fs for /var/lib/scylla.
Or, if we accept that, probably need to modify fs check code.

**Comment by avikivity** [comment]
We should remove the test in scylla, since we now support ext4.

**Comment by syuu1228** [comment]
Shouldn't we use same code to verify filesystem between iotune and scylla, probably by linking fsqueal.cc to scylla and use filesystem_has_good_aio_support()?

**Comment by avikivity** [comment]
It's a good idea, but running the test can fail due to other reasons (no 
write permissions in /var/lib/scylla, while /var/lib/scylla/data is 
writable).

**Comment by syuu1228** [comment]
Perhaps we can try filesystem_has_good_aio_support() both on data directory and commit directory, if the problem is only that one.
Or maybe we can just modify filesystem type check routine to accept ext4 too?

**Comment by avikivity** [comment]
On 12/14/2016 05:23 PM, Takuya ASADA wrote:
>
> Perhaps we can try filesystem_has_good_aio_support() both on data 
> directory and commit directory, if the problem is only that one.
>

I think this can work.

**Comment by tzach** [comment]
@syuu1228 putting the implementation aside, we should replace the error and exit for ext4 with a warning and let Scylla runs. Otherwise, the support work is useless.

**Comment by hawrre** [comment]
is that possible change milestone to 1.7 ? we need to deploy Scylladb in ext4. any way we can do that ?
