### ISSUE TITLE
Tracing: staring a Node while other Nodes send RPC messages requesting tracing causes an assert

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#1939]
*Installation details*
Scylla version (or git commit hash): 06c5216c9de144ceaf6d6633909675d622f80dfd
Cluster size: 2

Staring a Node while other Nodes send RPC messages requesting tracing causes a 
```
Service& seastar::sharded<Service>::local() [with Service = tracing::tracing]: Assertion  local_is_initialized()' failed.
```

assert

**Comment by slivne** [comment]
@vladzcloudius is there anything else left - can we close this ?

**Comment by vladzcloudius** [comment]
Actually it is fixed. I'm closing it.
