### ISSUE TITLE
 request scylla by api with body will cause error : "seastar - Exceptional future ignored: std::overflow_error (sstring overflow) "

### ISSUE THREAD

**Issue by duanshisan** [scylladb/scylla#1940]
Scylla version (or git commit hash): 1.5.rc2-20161213.dc08cb4
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ubuntu

I found some api method is 'POST', so do a test based on interest:

Api:  http://192.168.10.8:10000/failure_detector/phi?phi=8  -d'****'
If the requst has body will casue error: "seastar - Exceptional future ignored: std::overflow_error (sstring overflow)"，but the error is not every time,  if the request has no body everything is ok.

I see the struct of 'request' has a member ‘content’, but maybe has not be used, how can we use it to receive the request body?

**Comment by amnonh** [comment]
I'm not sure I understand the use case.

to change the failure detector phi you send a post request with the phi parameter in the query parameters like you did, without a body.

to get the phi, you call GET for the URL and get the results in the body, what is the body you are trying to add and for what purpose?

**Comment by duanshisan** [comment]
Thank you for your response, i have no purpose for this, I'm just curious if do a request accidentally took a body cause this error, because the API does not support or not need the body, whether we can ignore this error, or at least now can be ingnored?

**Comment by amnonh** [comment]
The API has limited support to a body in the request as it gets its
parameters from the query.
In your scenario, the body caused the API call to fail, but aside of that
the error can be ignored.

**Comment by duanshisan** [comment]
Thanks
