### ISSUE TITLE
Role-based access control

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#1941]
Cassandra 2.2 added [role-based access control](https://www.datastax.com/dev/blog/role-based-access-control-in-cassandra) in [CASSANDRA-7653](https://issues.apache.org/jira/browse/CASSANDRA-7653), which is currently not supported by Scylla that implements the older user-based access control model.

**Comment by hakuch** [comment]
I've written up the background context, feature description, and milestones on the [wiki](https://github.com/scylladb/scylla/wiki/Access-control-in-Scylla).

**Comment by avikivity** [comment]
Did "On the road to roles" really close this? Maybe it was badly titled.

**Comment by duarten** [comment]
@hakuch said there's still some work pending. I don't know if that is being tracked by other issues, or if this should have been a "refs".

**Comment by hakuch** [comment]
It could go either way, depending on how we interpret the issue (production ready vs in code). There's a couple of remaining issues (creating now), and dtests need to be updated.

**Comment by avikivity** [comment]
If the feature is ready to use then it's fixed (bugs notwithstanding). If more work is needed for it to be useful, then it's not fixed.

**Comment by hakuch** [comment]
That's reasonable. Let's re-open the issue for now.
