### ISSUE TITLE
Excessive I/O bandwidth when the node restart; And the I/O utils almost 100%,the node can't work

### ISSUE THREAD

**Issue by andrewrong** [scylladb/scylla#1944]
https://github.com/scylladb/scylla/issues/1925 this problem happened again, @avikivity

**Comment by avikivity** [comment]
Do you have bad_alloc again?

**Comment by andrewrong** [comment]
yes, It has the same problem and phenomenon

```

12月 19 11:36:15 scylla23 scylla[356]:  [shard 9] storage_proxy - exception during mutation write to 10.19.11.23: std::bad_alloc (std::bad_alloc)
12月 19 11:36:15 scylla23 scylla[356]:  [shard 9] storage_proxy - exception during mutation write to 10.19.11.23: std::bad_alloc (std::bad_alloc)
12月 19 11:36:15 scylla23 scylla[356]:  [shard 0] rpc - client 10.19.11.22: fail to connect: Connection refused
12月 19 11:36:15 scylla23 scylla[356]:  [shard 5] storage_proxy - exception during mutation write to 10.19.11.23: std::bad_alloc (std::bad_alloc)
12月 19 11:36:15 scylla23 scylla[356]:  [shard 2] storage_proxy - exception during mutation write to 10.19.11.23: std::bad_alloc (std::bad_alloc)
12月 19 11:36:15 scylla23 scylla[356]:  [shard 7] storage_proxy - exception during mutation write to 10.19.11.23: std::bad_alloc (std::bad_alloc)
12月 19 11:36:15 scylla23 scylla[356]:  [shard 2] storage_proxy - Failed to apply mutation from 10.19.11.24#11: std::bad_alloc (std::bad_alloc)
12月 19 11:36:15 scylla23 scylla[356]:  [shard 9] storage_proxy - exception during mutation write to 10.19.11.23: std::bad_alloc (std::bad_alloc)
12月 19 11:36:16 scylla23 scylla[356]:  [shard 17] storage_proxy - Failed to apply mutation from 10.19.11.24#9: std::bad_alloc (std::bad_alloc)
12月 19 11:36:16 scylla23 scylla[356]:  [shard 0] storage_proxy - exception during mutation write to 10.19.11.23: std::bad_alloc (std::bad_alloc)
```

![image](https://cloud.githubusercontent.com/assets/1272833/21300579/24d879be-c5e0-11e6-89aa-787b9621b507.png)

**Comment by avikivity** [comment]
Please send the output of `scyllatop -b -n 10 > metrics.txt`.

**Comment by andrewrong** [comment]
one node don't reboot, the log is `Exiting on unhandled exception: std::runtime_error (Exception while populating keyspace 'sentrydata' with column family 'datapoints' from file '/media/bigsd/data/sentrydata/datapoints-b26f28002ee011e69b50000000000001': std::bad_alloc (std::bad_alloc))`

[metrics.txt](https://github.com/scylladb/scylla/files/660753/metrics.txt)

**Comment by avikivity** [comment]
We have `non_lsa_memory_in_use` at absurd values in some shards.  How can that be?  I though all our data was managed now.

/cc @tgrabiec @pdziepak

**Comment by avikivity** [comment]
```
scylla23/lsa-10/bytes-free_space_in_zones 0.0
scylla23/lsa-10/bytes-large_objects_total_space 0.0
scylla23/lsa-10/bytes-non_lsa_used_space 2510991000.0
scylla23/lsa-10/bytes-small_objects_total_space 524288.0
scylla23/lsa-10/bytes-small_objects_used_space 5729.0
scylla23/lsa-10/bytes-total_space 524288.0
scylla23/lsa-10/bytes-used_space 5729.0
scylla23/lsa-10/objects-zones 1.0
scylla23/lsa-10/operations-segments_compacted 0.0
scylla23/lsa-10/operations-segments_migrated 0.0
scylla23/lsa-10/percent-occupancy 1.1
```

**Comment by avikivity** [comment]
Shard 15 has the smallest amount of free memory (21MB), with 2.4GB in non-lsa memory:

```
scylla23/lsa-15/bytes-free_space_in_zones 268435500.0
scylla23/lsa-15/bytes-large_objects_total_space 0.0
scylla23/lsa-15/bytes-non_lsa_used_space 2391413000.0
scylla23/lsa-15/bytes-small_objects_total_space 1572864.0
scylla23/lsa-15/bytes-small_objects_used_space 341712.0
scylla23/lsa-15/bytes-total_space 1572864.0
scylla23/lsa-15/bytes-used_space 341712.0
scylla23/lsa-15/objects-zones 2.0
scylla23/lsa-15/operations-segments_compacted 0.0
scylla23/lsa-15/operations-segments_migrated 0.0
scylla23/lsa-15/percent-occupancy 21.7
```

**Comment by avikivity** [comment]
```
scylla23/cache-15/bytes-total 524288.0
scylla23/cache-15/bytes-used 25894.0
```

**Comment by tgrabiec** [comment]
@avikivity `non_lsa_used_space` shows amount of live data allocated using standard allocator, minus memory allocated by LSA. So it includes standard allocations for sstable read buffers, etc. 2.5G doesn't sound implausible.

**Comment by avikivity** [comment]
There is 2.6GB/shard; no wonder we're out of memory.

```
scylla23/memory-15/memory-allocated_memory 2661421000.0
scylla23/memory-15/memory-free_memory 22933500.0
scylla23/memory-15/memory-total_memory 2684355000.0
```

**Comment by andrewrong** [comment]
@avikivity how to solve this problem? What is causing this problem?

**Comment by avikivity** [comment]
@andrewrong I tried to reproduce it but did not succeed.  Please generate a core dump (pkill -ABRT -x scylla) and upload it for us to analyze.

**Comment by avikivity** [comment]
@andrewrong I think the problem is that you have too much data for the node.  Scylla holds the all the Summary.db files in memory.  What is the sum of the sizes of all Summary.db files on your node?

**Comment by andrewrong** [comment]
```
cd /media/bigsd/data/sentrydata/datapoints-b26f28002ee011e69b50000000000001
ls -l | grep Summary | awk '{sum += $5}; END {print sum}'
```

the result is 456279166 Byte, this is about 450MB; 
I use your command `pkill -ABRT -x scylla`, but It is not valid, I have run `/usr/lib/scylla/scylla_coredump_setup --dump-to-raiddir --compress`; I don't know why?

**Comment by avikivity** [comment]
450 MB is not enough to cause the server to run out of memory; perhaps there are other tables?

What do you mean "not valid"?  Does it not generate a core?

**Comment by avikivity** [comment]
Please also check Filter.db and CompressionInfo.db

**Comment by andrewrong** [comment]
Filter.db: 1626089336 byte;
CompressionInfo.db: 32465845426 byte 

yes, I don't generate a core;

**Comment by avikivity** [comment]
@andrewrong CompressionInfo.db occupies 32 GB RAM; how much do you have on your servers?

to recover, boot with more RAM, and run the following CQL command:

```
ALTER TABLE sentrydata.datapoints
WITH compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor', 'chunk_length_kb': 64};
```


or disable compression entirely.

**Comment by avikivity** [comment]
You are running with around 2000:1 disk:memory ratio, this is too much for ScyllaDB.

**Comment by andrewrong** [comment]
My server have 64G memory and 64T hdd,  I give 50G memory to scylladb; I don't know the meaning for words(You are running with around 2000:1 disk:memory ratio, this is too much for ScyllaDB);
 Your means that my hdd is so bigger than my memory? 

I don't give more memory to my server, I can delete my data;  How to configure the scylladb and my server?

**Comment by andrewrong** [comment]
how to solve with this problem that  I running with around with 2000:1 disk:memory ratio? And what have the effect with the parameter `chunk_length_kb `

**Comment by avikivity** [comment]
It is okay to have more disk space than memory, but there is a limit to the ratio (size(disk) / size(memory)).  Above the limit ScyllaDB cannot function.  For you, the ration is (64T / 50G) = 1280.

You can improve things by doing the following:
 - run the ALTER TABLE command above
 - restart the node with more memory (try 55 GB)

after the node compacts some data, it will reduce the memory requirement.

**Comment by avikivity** [comment]
ScyllaDB needs 8 bytes of RAM for every (chunk_length_kb * compression_ratio) of disk space.  The default is 4k, so if your compression ration is 4:1, it needs 8 bytes for every 1kB of disk space.  By increasing chunk_size_kb, you reduce the amount of RAM needed (it only works after compaction).

**Comment by avikivity** [comment]
@andrewrong it is even better to disable compression completely (if you have enough free disk space):

```
ALTER TABLE sentrydata.datapoints
WITH compression = {'sstable_compression': ''};
```

In the long run, a server with 64TB disk needs more RAM.

**Comment by andrewrong** [comment]
@avikivity 

1. what configure is the most reasonable about the ration, I can learn it and better use scylladb;
2. the default value of chunk_length_kb in the scylladb is 4KB?
3. If I disable compression, how much several  times than before about the data size;
4. In my case, the chunk_length_kb:4K and my ratio is 1280, so it needs 8 bytes for every 4k/1280, Do i understand correctly?
5. why  the limit ScyllaDB cannot function? can you fix in the next version of scylladb ?
6. If the bug is fix, what will be happened in my case?

**Comment by avikivity** [comment]
1. Our recommendation is about 100:1, but it is not a hard limit, it can be larger or lower depending on your workload.  With a read-intensive load you need it higher, write-intensive can be lower.
 2. yes, it is 4kB, optimizing for read bandwidth.  On HDD, or if you don't to a lot of random reads, you can increase it.
 3. You can use `nodetool cfstats` to see the compression ratio
 4. Almost, we need 8 bytes for every (chunk_length_kb * compression_factor).  If the compression factor is 0.5 and chunk_length_kb is 4k, we need 8 bytes for every 2k.
 5. We plan to fix it, see #1946.
 6. It depends on how we fix it, there are several ideas.  In the best case, Scylla will work correctly with reduced read performance.

**Comment by avikivity** [comment]
@andrewrong were you able to make progress?

**Comment by andrewrong** [comment]
@avikivity 

1. I change memory limit to 55G
2. I alter table by your suggestion
3. Now the scylla still have `bad_alloc`

How to solve this problem and maintain my data; 

```
12月 21 15:59:56 scylla23 scylla[36500]:  [shard 19] compaction - Compacting [/media/bigsd/data/sentrydata/datapoints-b26f28002ee011e69b500000000...dia/bigsd
12月 21 16:00:27 scylla23 scylla[36500]:  [shard 16] compaction_manager - compaction failed: std::bad_alloc (std::bad_alloc)
12月 21 16:00:27 scylla23 scylla[36500]:  [shard 16] compaction_manager - compaction task handler sleeping for 5 seconds
12月 21 16:00:32 scylla23 scylla[36500]:  [shard 16] compaction - Compacting [/media/bigsd/data/sentrydata/datapoints-b26f28002ee011e69b500000000...dia/bigsd
12月 21 16:18:01 scylla23 scylla[36500]:  [shard 12] compaction_manager - compaction failed: std::bad_alloc (std::bad_alloc)
12月 21 16:18:01 scylla23 scylla[36500]:  [shard 12] compaction_manager - compaction task handler sleeping for 5 seconds
12月 21 16:18:06 scylla23 scylla[36500]:  [shard 12] compaction - Compacting [/media/bigsd/data/sentrydata/datapoints-b26f28002ee011e69b500000000...dia/bigsd
12月 21 16:24:42 scylla23 scylla[36500]:  [shard 8] compaction_manager - compaction failed: std::bad_alloc (std::bad_alloc)
12月 21 16:24:42 scylla23 scylla[36500]:  [shard 8] compaction_manager - compaction task handler sleeping for 5 seconds
12月 21 16:24:47 scylla23 scylla[36500]:  [shard 8] compaction - Compacting [/media/bigsd/data/sentrydata/datapoints-b26f28002ee011e69b5000000000...ia/bigsd/
Hint: Some lines were ellipsized, use -l to show in full.
```

```
CREATE TABLE sentrydata.datapoints (
    metric bigint,
    tags bigint,
    wholehour bigint,
    data map<int, frozen<tuple<double, bigint, bigint, double, double>>>,
    PRIMARY KEY ((metric, tags, wholehour))
) WITH bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

```
usr sys idl wai hiq siq| read  writ| recv  send|  in   out | int   csw
  2   1  98   0   0   0|3510k 6059k|   0     0 |1513B 2779B|7924  6140
 26   2  73   0   0   0|  70M  558M|9667B   12k|   0     0 |  54k   12k
 26   2  73   0   0   0|  72M  538M|3487B 3024B|   0     0 |  44k   14k
 26   2  73   0   0   0|  73M  554M|2784B 1322B|   0     0 |  44k   12k
 26   2  73   0   0   0|  70M  529M|1209B 1161B|   0     0 |  43k   12k
 25   2  73   0   0   0|  71M  545M|2623B 1794B|   0     0 |  47k   14k
 25   2  74   0   0   0|  71M  528M|  28k   32k|   0     0 |  47k   12k
 26   2  73   0   0   0|  70M  562M|2656B 1306B|   0     0 |  46k   14k
 26   2  73   0   0   0|  72M  561M| 948B  909B|   0     0 |  48k   15k
 25   2  73   0   0   0|  70M  528M|2279B 1067B|   0     0 |  45k   11k
 26   1  72   0   0   0|  76M  564M|1725B 1392B|   0     0 |  47k   13k
 25   2  73   0   0   0|  71M  560M|2673B 2187B|   0     0 |  47k   15k
 24   2  74   0   0   0|  73M  553M|1989B 5739B|   0     0 |  50k   12k
 26   2  73   0   0   0|  73M  562M|3373B   12k|   0     0 |  46k   13k
 25   2  73   0   0   0|  74M  543M|1110B 1200B|   0     0 |  46k   14k
 26   2  73   0   0   0|  68M  551M|2181B 1401B|   0     0 |  43k   11k
 26   2  72   0   0   0|  73M  560M| 983B 1067B|   0     0 |  42k   12k
 25   2  73   0   0   0|  75M  550M|2562B 1159B|   0     0 |  49k   16k
 25   2  73   0   0   0|  76M  594M|1459B 1339B|   0     0 |  48k   12k
 24   1  74   0   0   0|  73M  550M|2148B  785B|   0     0 |  48k   13k
 27   2  71   0   0   0|  76M  589M|1390B 1389B|   0     0 |  48k   15k
 26   2  73   0   0   0|  70M  522M|2215B 1067B|   0     0 |  46k   12k
 26   2  73   0   0   0|  72M  564M|2874B 6215B|   0     0 |  46k   12k
 25   2  73   0   0   0|  72M  534M|2419B 1339B|   0     0 |  48k   15k
 25   2  73   0   0   0|  73M  564M|2544B 2666B|   0     0 |  50k   12k
 25   2  73   0   0   0|  70M  517M|6241B   31k|   0     0 |  41k   12k
 26   2  72   0   0   0|  71M  572M|1442B 1389B|   0     0 |  47k   15k
```

**Comment by avikivity** [comment]
@andrewrong you can try `--smp 2 -m 55G`, until some sstables get rewritten with the new setting, then go back to larger `--smp` setting.  You should see the total size of `CompressionInfo.db` files decreasing.

**Comment by andrewrong** [comment]
@avikivity I try your suggestion; the total size of CompressionInfo.db still 32G

**Comment by avikivity** [comment]
Is the node starting without bad_allocs?  If so, as soon as some compactions finish, it will remove some CompressionInfo.db files.

**Comment by avikivity** [comment]
You can use `nodetool compactionstats` to see if there are compactions in progress.

**Comment by andrewrong** [comment]
@avikivity Your suggestion is valid,  the compact tasks is decreasing;  Though the size of compressionInfo.db still 32G..

```
[root@scylla23 datapoints-b26f28002ee011e69b50000000000001]# nodetool compactionstats
cp: 略过目录"/etc/scylla/cassandra/cassandra.logdir_IS_UNDEFINED"
pending tasks: 24
   compaction type     keyspace        table   completed     total   unit   progress
        COMPACTION   sentrydata   datapoints      698967   1358592   keys     51.45%
        COMPACTION   sentrydata   datapoints      897065   3341184   keys     26.85%
        COMPACTION   sentrydata   datapoints     1400239   1404928   keys     99.67%
        COMPACTION   sentrydata   datapoints     2964606   5075456   keys     58.41%
```

**Comment by avikivity** [comment]
@andrewrong you can try to see if the latest sstable has or does not have CompressionInfo.db; the files created after ALTER TABLE should not have that component.

**Comment by andrewrong** [comment]
@avikivity  Yes, you are right,  the newest compressionInfo.db is 2016.12.19 and the size of compressioninfo.db is 31G now, It shows that your suggestion works; Thank you very much;

**Comment by avikivity** [comment]
Good to hear, please let me know when the cluster is fully recovered.

**Comment by avikivity** [comment]
You can follow #1946 to see progress on fixing the underlying issues.

**Comment by andrewrong** [comment]
@avikivity Yes.

**Comment by avikivity** [comment]
@andrewrong from your earlier comment:

   		SSTable Compression Ratio: 0.157303

So compression was very effective.

You can re-enable compression with a large chunk size, for example

    ALTER TABLE sentrydata.datapoints
    WITH compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor', 'chunk_length_kb': 128};

and issue the `nodetool compact` command to recover space.  You will have CompressionInfo.db files, but they will be 32 times smaller (128/4) than the original, so they will not be problematic for the server.

**Comment by andrewrong** [comment]
@avikivity Thank you for your reply in this time; I will try it, I also guess this reason about this problem; 

Merry Christmas!
