### ISSUE TITLE
Bad handling of high disk:RAM ratios

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1946]
*Installation details*
Scylla version (or git commit hash): 1.4+

Ref: #1944 

Scylla loads CompressionInfo.db, Fillter.db, and Summary.db into RAM, but this can push out everything else.

We need better handling:
 - page these files to memory on demand?
 - limit total size in memory to X%, and mark the containing table as failed when exceeded?

**Comment by belliottsmith** [comment]
You could also try compressing the CompressionInfo.db in memory.  I discussed some simple approaches in my document on https://issues.apache.org/jira/browse/CASSANDRA-7447

Admittedly they were only ideas I riffed on and did basic simulation of; it's not guaranteed they would work, but it's pretty likely CompressionInfo.db can be made materially smaller, without a whole lot of work.

Of course, I don't mean to suggest gracefully handling overload isn't itself an important goal. Of course, it is for you to decide, but I'd suggest it may not be an optimal time investment, given the general dependency on lots of memory.  If you run out of room for bloom filters, for instance, the whole system is basically a pile of crap, so it's of limited benefit to handle *that* gracefully.  Probably logging regular warnings as memory use grows too large is more helpful to the user.

Given Filter.db should typically be much larger than Summary.db, it's likely only CompressionInfo.db that is a common problem that can be handled well.  It may be that a better storage format, permitting compression to be off by default, is a better investment (or even just porting support for 3.0 format for now?) -  and/or a more efficient in-memory representation of compression info... just a suggestion, of course.

**Comment by avikivity** [comment]
Compressing CompressionInfo is indeed easy and works well with paging, each page has the initial offset and a bunch of deltas relative to the initial offset.  We could do relative deltas but then recovering an offset is O(n) work.

Summary.db is small, but we are experimenting with reducing the sampling interval in order to reduce index reads (we can't rely), so it's growing.  Perhaps we could load small Summaries, and summarize larger summaries and page them on demand from disk.

A better storage format is indeed best.  I don't think we can get rid of compression as long as users store json blobs, but perhaps we should do cell-granularity compression instead.

**Comment by belliottsmith** [comment]
Well, actually the idea for compression I was riffing on was storing the delta from the "expected" compression offset, by assuming a uniform distribution of offsets).  It's probable this would permit smaller values, packing more values into a given page.  Probably with variable length compressed encodings of these values (at the time I was considering Golomb coding, but I think that could be improved upon), with the ability to seek to certain small intervals.  Perhaps on a per-page level fixed-width might be superior, but a fixed-width delta from the "expected" offset, calculated against just the page's full data range, is still likely better than an offset from the base I think...?

I think we chatted about compression once already before :)  I definitely agree it's going to be a necessary option, but I think 90% of users won't need or want it, so it could be disabled by default which might deprioritise this.  Only really large blobs are likely to benefit from a naive cell-level compression IMO, but it would be possible to build per-column/sstable compression dictionaries (possibly even shared between sstables) that could permit fairly efficient cell-level compression.  That's less trivial to do, of course.

**Comment by nyh** [comment]
On Tue, Dec 20, 2016 at 3:02 PM, Benedict Elliott Smith <
notifications@github.com> wrote:

> You could also try compressing the CompressionInfo.db in memory. I
> discussed some simple approaches in my document on
> https://issues.apache.org/jira/browse/CASSANDRA-7447
>

Thanks. This is a good idea, but is that the right link? I don't see there
any discussion of the CompressionInfo file?


> Given Filter.db should typically be much larger than Summary.db,


Something we could theoretically do is to make the bloom filter smaller, at
the expense of more false-positives.
This could lead to more disk accesses per read, but if our database has
multiple column families with unequal read frequency (one is read less
frequently than the others), it might make sense for the more rarely read
cf have somewhat slower reads, in exchange for getting more memory to serve
the more popular cfs.

**Comment by belliottsmith** [comment]
It's in the linked PDF, that's a quite dense discussion of my (fairly out-of-date) thoughts on storage format improvements. 

https://issues.apache.org/jira/secure/attachment/12694441/storage_format.pdf

You're right that bloom filters could also have dynamic false positive ratios, and in fact I had entirely forgotten another ticket I had filed to discuss this.  It's actually very easy to do.  With a sensibly selected mix of partitioning of hash function ranges, can likely minimise any harm to typical space requirements, while permitting very cheap tuning of this behaviour.  Including swapping which hash ranges you use if hot false-positives are detected (by, e.g., spotting that real FP is much higher than predicted)

https://issues.apache.org/jira/browse/CASSANDRA-6633

That all said, once this starts happening you're no longer honouring some user configured property, while it's definitely preferable to keeling over, it's still probably best (IMO) to do your darnedest to tell the user ASAP they need to increase their cluster size or physical memory.

**Comment by nyh** [comment]
On Tue, Dec 20, 2016 at 3:38 PM, Benedict Elliott Smith <
notifications@github.com> wrote:

> Well, actually the idea for compression I was riffing on was storing the
> delta from the "expected" compression offset, by assuming a uniform
> distribution of offsets). It's probable this would permit smaller values,
> packing more values into a given page. Probably with variable length
> compressed encodings of these values (at the time I was considering Golomb
> coding, but I think that could be improved upon), with the ability to seek
> to certain small intervals. Perhaps on a per-page level fixed-width might
> be superior, but a fixed-width delta from the "expected" offset, calculated
> against just the page's full data range, is still likely better than an
> offset from the base I think...?
>
If we're trying to achive efficient in-memory compression, not just on-disk
compression, a very important concern is how efficiently can we do
random-access in that compressed format.

Right now, in the uncompressed compressioninfo, to read data in position p
in the before-compression file, we calculates p / chunk_length as the
uncompressed chunk number, and the compressed version of this chuck is
begins in chunk_offsets[p / chunk_length] - one array lookup.

Something we could have very easily done is two have two levels of
chunk_offsets: Have an additional level of super-chunks, of say, 1024
chunks. We'll have one array of super_chunk_offset[] and an additional
array chunk_offsets[] but this time the offfset will be into the
superchunk. In other words, the compressed chunk begins at
super_chunk_offsets[p / super_chunk_length] + chunk_offsets[p /
chunk_length]. The benefit is that the chunk_offsets[] will not need 64 bit
offsets - it can easily use 32 bit offsets. So this can save half the
memory. But not more than half... By the way, the superchunk doesn't
actually need to be 1024 chunks, it can be much more (as long as each
superchunk is less than 4 GB).

If we used more refined modeling and/or encoding (as you proposed) of the
chunk offsets, I'm worried that to recover a single offset, we may need to
"unencode" an entire block, which will be significantly slower. On the
other hand, maybe the disk access will be so much slower anyway, that we
don't care?

**Comment by belliottsmith** [comment]
It is difficult to express these thoughts concisely and well over text, but I did attempt to suggest that it *may* be that it would be fine to simply pick a number of binary digits necessary to represent the maximum delta from your base value (in my supposed case, from start_of_page+i*(end_of_page-start_of_page)/N). 

The number of binary digits could be picked globally, or locally, either providing better compression than 32bits.  If locally, though, how do you know where to look?  Well, the same approach of prediction can be applied recursively - if you read the PDF I outline an approach for guaranteeing, similar to BFs, that the likelihood of picking the correct block is > some limit (probably ~95%), and in other cases you would need to consult the adjacent block, with similar probability.  At write time it is possible to shape the data to absolutely guarantee bounds.

A variable length encoding can also be supported with this approach, with image records at well defined positions for seeking, and permits tuning the tradeoff of CPU/memory bandwidth and compression, based on the frequency of the image records.  A high enough frequency likely makes the burden immeasurable, although it's possible that this frequency is high enough for the overhead of images to outweigh any benefit.  I would guess that a reasonable balance could be struck given the other costs associated with serving a query.

**Comment by avikivity** [comment]
Let's say we place each _n_ chunks together, with a int of size log2(file size) bits for the first chunk offset, and n-1 ints of size log2(chunk size) for relative chunk offsets of the other n-1 chunks:

    struct {
        uint64_t chunk0offset : log2(file size);
        uint64_t chunk_offsets[n-1] : logs2(chunk_size);
    }

The expression for the total size of the compressed info structure is:

>   ((file size / chunk size) / n) * (log2(file size) + (n-1) * log2(chunk size))

Taking the derivative wrt. n we get

> (n + ln(cn) - ln(f) - 1) * something

Setting that to zero we get

>  n + ln(cn) = ln(f) + 1

Wolfram says:

> n = W(ef/c)

(where W is Lambert's W function). So we have a way of computing the optimal n for a specific file size and chunk size.

**Comment by denesb** [comment]
@avikivity I'm admittedly rusty at calculating derivatives but I've got completely different results for the first derivative after doing it on paper :|. Anyway, won't setting the first derivative to 0 only give you the extremas of the function? You need the second to determine whether it's minima or maxima.
How do you plan on selecting the size of the ints? This can be only done compile time. Do we select them based on the possible ranges?

**Comment by avikivity** [comment]
@denesb I used an online tool, but maybe I made a mistake. In any case, we can run an exhaustive search (offline) for all files sizes (powers of two only) and all chunk sizes (powers of two), and all combinations of word lengths.

There are no 11-bit word sizes, so we'll have to use shifts. Allocate a 128k (or smaller) block, and lay out bits: occcocccocccoccc

Where o = bits used for an offset within the file, c = bits used as a relative offset to o, and in this case, we chose 1 full offset every 4 chunks.

**Comment by denesb** [comment]
According to my script, your proposed solution reduces the size of the chunk map between (25%-45%), compared to the current solution of keeping an `std::deque<uint64_t>`.
Here is all:
```
f (log2)  c (log2)   n  size                 current size           reduction (%)



      21        10   6                 28198              131072.0  21.51%


      22        10   7                 57058              262144.0  21.77%


      23        10   7                115285              524288.0  21.99%
      23        11   7                 61154              262144.0  23.33%


      24        10   8                232759             1048576.0  22.20%
      24        11   7                123477              524288.0  23.55%


      25        10   8                469613             2097152.0  22.39%
      25        11   8                249143             1048576.0  23.76%
      25        12   7                131669              524288.0  25.11%


      26        10   9                946632             4194304.0  22.57%
      26        11   8                502381             2097152.0  23.96%
      26        12   8                265527             1048576.0  25.32%


      27        10  10               1907482             8388608.0  22.74%
      27        11   9               1012168             4194304.0  24.13%
      27        12   8                535149             2097152.0  25.52%
      27        13   8                281911             1048576.0  26.89%


      28        10  10               3841179            16777216.0  22.90%
      28        11  10               2038554             8388608.0  24.30%
      28        12   9               1077704             4194304.0  25.69%
      28        13   8                567917             2097152.0  27.08%


      29        10  11               7731784            33554432.0  23.04%
      29        11  10               4103323            16777216.0  24.46%
      29        12  10               2169626             8388608.0  25.86%
      29        13   9               1143240             4194304.0  27.26%
      29        14   8                600685             2097152.0  28.64%


      30        10  12              15558574            67108864.0  23.18%
      30        11  11               8256072            33554432.0  24.61%
      30        12  10               4365467            16777216.0  26.02%
      30        13  10               2300698             8388608.0  27.43%
      30        14   9               1208776             4194304.0  28.82%


      31        10  12              31291911           134217728.0  23.31%
      31        11  12              16607150            67108864.0  24.75%
      31        12  11               8780360            33554432.0  26.17%
      31        13  10               4627611            16777216.0  27.58%
      31        14  10               2431770             8388608.0  28.99%
      31        15   9               1274312             4194304.0  30.38%


      32        10  13              62920868           268435456.0  23.44%
      32        11  12              33389063           134217728.0  24.88%
      32        12  12              17655726            67108864.0  26.31%
      32        13  11               9304648            33554432.0  27.73%
      32        14  10               4889755            16777216.0  29.15%
      32        15  10               2562842             8388608.0  30.55%


      33        10  13             126487013           536870912.0  23.56%
      33        11  13              67115172           268435456.0  25.00%
      33        12  12              35486215           134217728.0  26.44%
      33        13  12              18704302            67108864.0  27.87%
      33        14  11               9828936            33554432.0  29.29%
      33        15  10               5151899            16777216.0  30.71%
      33        16  10               2693914             8388608.0  32.11%


      34        10  14             254181673          1073741824.0  23.67%
      34        11  13             134875621           536870912.0  25.12%
      34        12  13              71309476           268435456.0  26.56%
      34        13  12              37583367           134217728.0  28.00%
      34        14  12              19752878            67108864.0  29.43%
      34        15  11              10353224            33554432.0  30.86%
      34        16  10               5414043            16777216.0  32.27%


      35        10  15             510705097          2147483648.0  23.78%
      35        11  14             270958889          1073741824.0  25.24%
      35        12  13             143264229           536870912.0  26.69%
      35        13  13              75503780           268435456.0  28.13%
      35        14  12              39680519           134217728.0  29.56%
      35        15  12              20801454            67108864.0  31.00%
      35        16  11              10877512            33554432.0  32.42%
      35        17  10               5676187            16777216.0  33.83%


      36        10  15            1025884118          4294967296.0  23.89%
      36        11  15             544259529          2147483648.0  25.34%
      36        12  14             287736105          1073741824.0  26.80%
      36        13  13             151652837           536870912.0  28.25%
      36        14  13              79698084           268435456.0  29.69%
      36        15  12              41777671           134217728.0  31.13%
      36        16  12              21850030            67108864.0  32.56%
      36        17  11              11401800            33554432.0  33.98%


      37        10  16            2060270302          8589934592.0  23.98%
      37        11  15            1092992982          4294967296.0  25.45%
      37        12  15             577813961          2147483648.0  26.91%
      37        13  14             304513321          1073741824.0  28.36%
      37        14  13             160041445           536870912.0  29.81%
      37        15  13              83892388           268435456.0  31.25%
      37        16  12              43874823           134217728.0  32.69%
      37        17  12              22898606            67108864.0  34.12%
      37        18  11              11926088            33554432.0  35.54%


      38        10  17            4137064087         17179869184.0  24.08%
      38        11  16            2194488030          8589934592.0  25.55%
      38        12  15            1160101846          4294967296.0  27.01%
      38        13  15             611368393          2147483648.0  28.47%
      38        14  14             321290537          1073741824.0  29.92%
      38        15  13             168430053           536870912.0  31.37%
      38        16  13              88086692           268435456.0  32.81%
      38        17  12              45971975           134217728.0  34.25%
      38        18  12              23947182            67108864.0  35.68%


      39        10  17            8305708816         34359738368.0  24.17%
      39        11  17            4405499543         17179869184.0  25.64%
      39        12  16            2328705758          8589934592.0  27.11%
      39        13  15            1227210710          4294967296.0  28.57%
      39        14  15             644922825          2147483648.0  30.03%
      39        15  14             338067753          1073741824.0  31.49%
      39        16  13             176818661           536870912.0  32.94%
      39        17  13              92280996           268435456.0  34.38%
      39        18  12              48069127           134217728.0  35.81%
      39        19  12              24995758            67108864.0  37.25%


      40        10  18           16672041098         68719476736.0  24.26%
      40        11  17            8842579728         34359738368.0  25.74%
      40        12  17            4673934999         17179869184.0  27.21%
      40        13  16            2462923486          8589934592.0  28.67%
      40        14  15            1294319574          4294967296.0  30.14%
      40        15  15             678477257          2147483648.0  31.59%
      40        16  14             354844969          1073741824.0  33.05%
      40        17  13             185207269           536870912.0  34.50%
      40        18  13              96475300           268435456.0  35.94%
      40        19  12              50166279           134217728.0  37.38%


      41        10  19           33462163673        137438953472.0  24.35%
      41        11  18           17745782922         68719476736.0  25.82%
      41        12  17            9379450640         34359738368.0  27.30%
      41        13  17            4942370455         17179869184.0  28.77%
      41        14  16            2597141214          8589934592.0  30.23%
      41        15  15            1361428438          4294967296.0  31.70%
      41        16  15             712031689          2147483648.0  33.16%
      41        17  14             371622185          1073741824.0  34.61%
      41        18  13             193595877           536870912.0  36.06%
      41        19  13             100669604           268435456.0  37.50%
      41        20  12              52263431           134217728.0  38.94%


      42        10  19           67150378256        274877906944.0  24.43%
      42        11  19           35609647321        137438953472.0  25.91%
      42        12  18           18819524746         68719476736.0  27.39%
      42        13  17            9916321552         34359738368.0  28.86%
      42        14  17            5210805911         17179869184.0  30.33%
      42        15  16            2731358942          8589934592.0  31.80%
      42        16  15            1428537302          4294967296.0  33.26%
      42        17  15             745586121          2147483648.0  34.72%
      42        18  14             388399401          1073741824.0  36.17%
      42        19  13             201984485           536870912.0  37.62%
      42        20  13             104863908           268435456.0  39.06%


      43        10  20          134737686515        549755813888.0  24.51%
      43        11  19           71445345552        274877906944.0  25.99%
      43        12  19           37757130969        137438953472.0  27.47%
      43        13  18           19893266570         68719476736.0  28.95%
      43        14  17           10453192464         34359738368.0  30.42%
      43        15  17            5479241367         17179869184.0  31.89%
      43        16  16            2865576670          8589934592.0  33.36%
      43        17  15            1495646166          4294967296.0  34.82%
      43        18  15             779140553          2147483648.0  36.28%
      43        19  14             405176617          1073741824.0  37.74%
      43        20  13             210373093           536870912.0  39.19%
      43        21  13             109058212           268435456.0  40.63%


      44        10  21          270328155560       1099511627776.0  24.59%
      44        11  20          143327621107        549755813888.0  26.07%
      44        12  19           75740312848        274877906944.0  27.55%
      44        13  19           39904614617        137438953472.0  29.03%
      44        14  18           20967008394         68719476736.0  30.51%
      44        15  17           10990063376         34359738368.0  31.99%
      44        16  17            5747676823         17179869184.0  33.46%
      44        17  16            2999794398          8589934592.0  34.92%
      44        18  15            1562755030          4294967296.0  36.39%
      44        19  15             812694985          2147483648.0  37.84%
      44        20  14             421953833          1073741824.0  39.30%
      44        21  13             218761701           536870912.0  40.75%


      45        10  21          542292489137       2199023255552.0  24.66%
      45        11  21          287508024744       1099511627776.0  26.15%
      45        12  20          151917555699        549755813888.0  27.63%
      45        13  19           80035280144        274877906944.0  29.12%
      45        14  19           42052098265        137438953472.0  30.60%
      45        15  18           22040750218         68719476736.0  32.07%
      45        16  17           11526934288         34359738368.0  33.55%
      45        17  17            6016112279         17179869184.0  35.02%
      45        18  16            3134012126          8589934592.0  36.48%
      45        19  15            1629863894          4294967296.0  37.95%
      45        20  15             846249417          2147483648.0  39.41%
      45        21  14             438731049          1073741824.0  40.86%
      45        22  13             227150309           536870912.0  42.31%


      46        10  22         1087762677201       4398046511104.0  24.73%
      46        11  21          576652227505       2199023255552.0  26.22%
      46        12  21          304687893928       1099511627776.0  27.71%
      46        13  20          160507490291        549755813888.0  29.20%
      46        14  19           84330247440        274877906944.0  30.68%
      46        15  19           44199581913        137438953472.0  32.16%
      46        16  18           23114492042         68719476736.0  33.64%
      46        17  17           12063805200         34359738368.0  35.11%
      46        18  17            6284547735         17179869184.0  36.58%
      46        19  16            3268229854          8589934592.0  38.05%
      46        20  15            1696972758          4294967296.0  39.51%
      46        21  15             879803849          2147483648.0  40.97%
      46        22  14             455508265          1073741824.0  42.42%


      47        10  23         2181738787019       8796093022208.0  24.80%
      47        11  22         1156482153937       4398046511104.0  26.30%
      47        12  21          611011965873       2199023255552.0  27.79%
      47        13  21          321867763112       1099511627776.0  29.27%
      47        14  20          169097424883        549755813888.0  30.76%
      47        15  19           88625214736        274877906944.0  32.24%
      47        16  19           46347065561        137438953472.0  33.72%
      47        17  18           24188233866         68719476736.0  35.20%
      47        18  17           12600676112         34359738368.0  36.67%
      47        19  17            6552983191         17179869184.0  38.14%
      47        20  16            3402447582          8589934592.0  39.61%
      47        21  15            1764081622          4294967296.0  41.07%
      47        22  15             913358281          2147483648.0  42.53%
      47        23  14             472285481          1073741824.0  43.99%


      48        10  23         4375428787383      17592186044416.0  24.87%
      48        11  23         2319177740491       8796093022208.0  26.37%
      48        12  22         1225201630673       4398046511104.0  27.86%
      48        13  21          645371704241       2199023255552.0  29.35%
      48        14  21          339047632296       1099511627776.0  30.84%
      48        15  20          177687359475        549755813888.0  32.32%
      48        16  19           92920182032        274877906944.0  33.80%
      48        17  19           48494549209        137438953472.0  35.28%
      48        18  18           25261975690         68719476736.0  36.76%
      48        19  17           13137547024         34359738368.0  38.24%
      48        20  17            6821418647         17179869184.0  39.71%
      48        21  16            3536665310          8589934592.0  41.17%
      48        22  15            1831190486          4294967296.0  42.64%
      48        23  15             946912713          2147483648.0  44.09%


      49        10  24         8774146884406      35184372088832.0  24.94%
      49        11  23         4650306694327      17592186044416.0  26.43%
      49        12  23         2456616693963       8796093022208.0  27.93%
      49        13  22         1293921107409       4398046511104.0  29.42%
      49        14  21          679731442609       2199023255552.0  30.91%
      49        15  21          356227501480       1099511627776.0  32.40%
      49        16  20          186277294067        549755813888.0  33.88%
      49        17  19           97215149328        274877906944.0  35.37%
      49        18  19           50642032857        137438953472.0  36.85%
      49        19  18           26335717514         68719476736.0  38.32%
      49        20  17           13674417936         34359738368.0  39.80%
      49        21  17            7089854103         17179869184.0  41.27%
      49        22  16            3670883038          8589934592.0  42.73%
      49        23  15            1898299350          4294967296.0  44.20%
      49        24  15             980467145          2147483648.0  45.66%


      50        10  25        17593905681364      70368744177664.0  25.00%
      50        11  24         9323902698294      35184372088832.0  26.50%
      50        12  23         4925184601271      17592186044416.0  28.00%
      50        13  23         2594055647435       8796093022208.0  29.49%
      50        14  22         1362640584145       4398046511104.0  30.98%
      50        15  21          714091180977       2199023255552.0  32.47%
      50        16  21          373407370664       1099511627776.0  33.96%
      50        17  20          194867228659        549755813888.0  35.45%
      50        18  19          101510116624        274877906944.0  36.93%
      50        19  19           52789516505        137438953472.0  38.41%
      50        20  18           27409459338         68719476736.0  39.89%
      50        21  17           14211288848         34359738368.0  41.36%
      50        22  17            7358289559         17179869184.0  42.83%
      50        23  16            3805100766          8589934592.0  44.30%
      50        24  15            1965408214          4294967296.0  45.76%
```

**Comment by avikivity** [comment]
Best reduction is 75%, no?

**Comment by avikivity** [comment]
Even more, 79%

**Comment by denesb** [comment]
The largest number I can see is 45.76%. Maybe I made a mistake at calculating the reduction.

**Comment by avikivity** [comment]
I think you're missing a (1-x). The reduction is _to_ 21% of the original size, so _by_ 79% of the original size. Maybe you meant reduction _to_.

Anyway this is better expressed as factors. A 1TB file with reasonable chunk sizes sees 3X-4X improvement.

**Comment by denesb** [comment]
Yes you are right, I calculated the reduction as new_size*100/old_size. Anyway the results are quite interesting (for me), I expected optimal n to be higher and bigger chunks sizes to perform better but it looks like the base_offset size grows faster than the number of segments shrinks.

**Comment by denesb** [comment]
s/base_offset/relative_offset/

**Comment by denesb** [comment]
I've been looking at the code and it seems like changing the members of the struct would mean changing the on-disk format as well, as the parsing/writing code is generated through describe(). Is this acceptable or do I need to write some bridge code to keep the current format?

**Comment by avikivity** [comment]
The on-disk format is set in stone.

You can override the generated parser by writing a `parse(random_access_reader&, compression&)` function (and I think you can then drop `describe_type()`.

**Comment by avikivity** [comment]
Also, you'll have to customize the writer.

You could also keep the current reader and writers, and translate the in-memory formats. Maybe that's an easier first step, but it consumes more memory.

**Comment by avikivity** [comment]
Closing this. We have decent jandling of high disk:memory ratios now, and generic "this can be improved" bugs cannot ever be closed because they don't address a specific problem.
