### ISSUE TITLE
Scylla housekeeping with systemd, should use r mode for restart and d mode for daily check

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#1953]
Version 1.6 and up

In ubuntu 14, the timer script uses r mode for checking the version during restart and d mode for checking the version once a day.

This is the better behavior and should be the same for systemd support

**Comment by slivne** [comment]
@amnonh what is r mode and what is d mode - can you provide a bit more information

**Comment by amnonh** [comment]
the housekeeping gets a mode parameter, it needs to get the right mode according to the state of the request
