### ISSUE TITLE
Scylla server allocating >16TiB of virtual space

### ISSUE THREAD

**Issue by vladpetric** [scylladb/scylla#1955]
*Installation details*
Scylla version (or git commit hash): 1.4.3-20161216.b10dcfc
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS Linux release 7.3.1611 (Core)

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets=2 cores=36 hyperthreading=72 memory=768MiB
Disks: (SSD/HDD, count) 6 HDD in hardware RAID

I am currently running Scylla as follows:

pgrep -af scylla

58534 /usr/bin/scylla --developer-mode=1 --smp=4 --memory=8G --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --max-io-requests=216 --num-io-queues=54
58551 /usr/lib/scylla/jmx/symlinks/scylla-jmx -Dcassandra.jmx.local.port=7199 -Xmx256m -XX:+UseSerialGC -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -jar /usr/lib/scylla/jmx/scylla-jmx-1.0.jar

It does seem to allocate an insane chunk of memory somewhere:

(see last line)
 cat /proc/58534/maps  | head -n12
00400000-0211d000 r-xp 00000000 fd:00 535648                             /usr/bin/scylla
0231d000-02326000 r--p 01d1d000 fd:00 535648                             /usr/bin/scylla
02326000-0232d000 rw-p 01d26000 fd:00 535648                             /usr/bin/scylla
0232d000-02411000 rw-p 00000000 00:00 0
600000000000-600080000000 rw-p 00000000 00:00 0
600080000000-601000000000 ---p 00000000 00:00 0
601000000000-601080000000 rw-p 00000000 00:00 0
601080000000-602000000000 ---p 00000000 00:00 0
602000000000-602080000000 rw-p 00000000 00:00 0
602080000000-603000000000 ---p 00000000 00:00 0
603000000000-603080000000 rw-p 00000000 00:00 0
603080000000-700000000000 ---p 00000000 00:00 0

Note that I'm not doing anything whatsoever on this server. This is a clean install, with no data.

**Comment by avikivity** [comment]
No, it is reserving 16 TiB of virtual address space, but only allocating 2 GiB per core.  Lines marked as `---p` are not backed by memory.

**Comment by vladpetric** [comment]
So you're saying that this is expected behavior? May I ask why?

**Comment by avikivity** [comment]
We do that so that we can quickly identify by inspecting a pointer's top bits whether it belongs to the arena we allocated, or not.
