### ISSUE TITLE
SSTable expiration statistics

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1960]
When we write an sstable, we can collect information about future expirations: the time when the expiration happens, the  number of bytes recovered (due to a cell being converted to a tombstone or a tombstone disappearing), and the number of tombstones removed.  To conserve space, this information would be stored in a histogram with expiration time as the key.

Compaction strategies could then consult this information when space gets low, picking the best sstable to clean when we need to recover space.  This could help reclaim large sstables with size-tiered compaction strategy, or sstables that have expiration in leveled compaction strategy, if the operator forgot to issue the `nodetool clean` command.

**Comment by raphaelsc** [comment]
There's a streaming histogram with estimated tombstone drop time in Statistics. It's used by C* for tombstone compaction IIRC. In addition to low disk space scenario, we could also run this logic when there's nothing to compact.

**Comment by avikivity** [comment]
Fixed by fc966c0c4ca4d95c267ca698344625a647b427db
