### ISSUE TITLE
Scylla setup does not list local SSD disks on Google Cloud VM, cant add manually at prompt

### ISSUE THREAD

**Issue by manigandham** [scylladb/scylla#1963]
*Installation details*
Scylla version: 1.5.0
OS: CentOS 7 on Google Cloud Engine (x86_64 built on 2016-12-12)

Disks: 
10GB SSD persistent disk for boot/OS
375GB Local SSD for data

Devices output:
```
# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0   10G  0 disk 
└─sda1   8:1    0   10G  0 part /
sdb      8:16   0  375G  0 disk 
```

Previously under version 1.3 (our current running version), `scylla_setup` would not list any devices but still allowed entry so I could still enter `/dev/sdb` and it would work.

With #1673 the setup script now skips the prompt if the list of disks is empty (or it cant find any disks), disallowing any chance for manual entry of disks that I know exist. This means I have to manually RAID/format disks separately rather than through the setup script.

```
Do you want to setup RAID and XFS?
It is recommended to use RAID0 and XFS for Scylla data. If you select yes, you will be prompt to choose which disks to use for Scylla data. Selected disks will be formatted in the process.
[YES/no]yes
No free disks detected, abort RAID/XFS setup.
```

On Google, these local SSDs are not mounted by default so they will not show up with `blkid` which is the command the `scylla_setup` is using to list the disks. Since the setup script is creating the fstab entries anyway, it doesn't seem like having mounted disks before running the setup script should be necessary.

https://cloud.google.com/compute/docs/disks/local-ssd

**Comment by manigandham** [comment]
I looked up the script and ran this again, which worked fine:

> # sudo  /usr/lib/scylla/scylla_raid_setup --disks /dev/sdb --update-fstab

**Comment by dorlaor** [comment]
Mani, so the generic scylla_setup doesn't work while the specific
raid_setup does?
Btw, better use NVMe abstraction from GCE. It's much more faster and costs
the same.

**Comment by tzach** [comment]
@syuu1228 can you please take a look?

**Comment by manigandham** [comment]
Hey @dorlaor 

The setup process works, but the interactive script just doesn't list all the devices on a fresh VM because (as far as I can tell) it uses the `blkid` command which doesn't show unmounted disks. Since it skips the prompt if it cant find any devices, I don't have a chance to enter any disks manually.

I just work around it by directly calling the scylla_raid_setup script myself.

**Comment by benoit-canet** [comment]
I was the last one touching this code.

I just sent "[PATCH] scylla_setup: Use ls to list potentials block devices"
on the list to make the code specifically look for /dev/sd* /dev/vd and
/dev/xvd*
patterns.

**Comment by benoit-canet** [comment]
Hmm this patch is wrong because of lvm :(

**Comment by benoit-canet** [comment]
Sent a better version of the patch accounting lvm's dev mapper.

**Comment by penberg** [comment]
@avikivity @slivne Backports?

**Comment by avikivity** [comment]
yes

**Comment by penberg** [comment]
How far back? 1.4?

**Comment by avikivity** [comment]
It only applies to new installs, so 1.5 is sufficient.

**Comment by KMax** [comment]
Connected 4 Local SSDs, combined them, but Scylla 3.0.2's `scylla_setup` can't see them.

`lsblk` output:

```
kolchinmax@scylladb-cluster-3:~$ lsblk
NAME    MAJ:MIN RM  SIZE RO TYPE  MOUNTPOINT
loop0     7:0    0   91M  1 loop  /snap/core/6350
loop1     7:1    0 55.7M  1 loop  /snap/google-cloud-sdk/70
sda       8:0    0   10G  0 disk  
├─sda1    8:1    0  9.9G  0 part  /
├─sda14   8:14   0    4M  0 part  
└─sda15   8:15   0  106M  0 part  /boot/efi
nvme0n1 259:0    0  375G  0 disk  
└─md0     9:0    0  1.5T  0 raid0 
nvme0n2 259:1    0  375G  0 disk  
└─md0     9:0    0  1.5T  0 raid0 
nvme0n3 259:2    0  375G  0 disk  
└─md0     9:0    0  1.5T  0 raid0 
nvme0n4 259:3    0  375G  0 disk  
└─md0     9:0    0  1.5T  0 raid0
```

`blkid` output:
```
kolchinmax@scylladb-cluster-3:~$ blkid
/dev/sda1: LABEL="cloudimg-rootfs" UUID="3efc28cb-98a4-458d-8fbe-a895461703ca" TYPE="ext4" PARTUUID="aba6e6dc-6ee2-4bfb-a038-aa5f42d89d88"
/dev/sda15: LABEL="UEFI" UUID="38A3-535D" TYPE="vfat" PARTUUID="63c0cc9e-62c5-4459-a2a4-ea00a600128a"
```
