### ISSUE TITLE
Run Scylla service as the last step of scylla_setup

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1967]
*Installation details*
Scylla version (or git commit hash): 1.5

Currently, one need to run scylla_setup, restart the server, and then run scylla as a service.
Once we remove the restart phase with #1758, the  `sudo systemctl start scylla-server`* command can be part of scylla_setup, simplify the install process for the user.

* or equivalent in each distribution

**Comment by avikivity** [comment]
A step before needs to be setup of the various parameters in `scylla.yaml`.

btw, the script is now so complicated, we better convert it to a TUI, so you can go back to a step you already did.

**Comment by avikivity** [comment]
http://urwid.org/examples/index.html

**Comment by tzach** [comment]
> A step before needs to be setup of the various parameters in scylla.yaml.

You are right, in most production system its a must, so running Scylla as part of setup does not make sense
