### ISSUE TITLE
http performance problem with the v1.0.2 on ubuntu 16.04

### ISSUE THREAD

**Issue by yijiangnan23** [scylladb/scylla#1970]
*Installation details*
Scylla version (or git commit hash):1.0.2
Cluster size:1
OS (RHEL/CentOS/Ubuntu/AWS AMI):Ubuntu

Platform (physical/VM/cloud instance type/docker):VM
Hardware: sockets= cores=4  hyperthreading= memory=8G
Disks: (SSD/HDD, count)SSD
 
we have found that : the http performance is very slow if we run the v1.0.2 on ubuntu 16.04. The result is as follows:
![default](https://cloud.githubusercontent.com/assets/8815991/21538059/dca7a72c-cdd3-11e6-9405-2cb16b18a47e.png)
but the result is very high if we run the v1.0.2 on ubuntu 14.04
![default](https://cloud.githubusercontent.com/assets/8815991/21538078/0c52a12a-cdd4-11e6-96e0-29575403c4aa.png)

Are therre some difference  between  ubuntu 14.04 and  ubuntu 16.04?

**Comment by dorlaor** [comment]
The stock Ubuntu 14.04 kernel has 250hz clock and that's the source for the
difference.
There is a 3.15 kernel you can upgrade 14.04 with which will allow 1000hz
timers, try it.

**Comment by yijiangnan23** [comment]
But our test result is that the http performance is slower when run on  ubuntu 16.04 than ubuntu 14.04 .

**Comment by slivne** [comment]
@yijiangnan23 scylla-1.0.2 did not support ubuntu 16, we started supporting it from 1.2.
can you please test it with 1.5 

can you please elaborate why you are running a load toward the admin rest api
