### ISSUE TITLE
housekeeping should provide info about patch releases as well

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1972]
currently houskeeping provides information about the latest release only, that is a user on 1.4.2 will get a notification that 1.5.0 is out. however it would also be information for the user that there is a 1.4.3 that he can upgrade to.

**Comment by amnonh** [comment]
Users who uses 1.4.2, should he get a notification that 1.4.3 is available, 1.5, or both?

**Comment by slivne** [comment]
both

**Comment by slivne** [comment]
@amnonh  is that fixed

**Comment by amnonh** [comment]
Not yet

**Comment by slivne** [comment]
@amnonh ?
