### ISSUE TITLE
rpx/xps on small aws ec2 instances

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#1973]
*Installation details*
Scylla version (or git commit hash): 1.5

on i2.2xlarge and below we do not dedicate a core for networking, so we should use rps/xps to balance networking cpu load across all cores.

**Comment by vladzcloudius** [comment]
@avikivity This is done by the posix_net_config.sh script. What is the issue exactly?

**Comment by vladzcloudius** [comment]
@avikivity @slivne ping

**Comment by slivne** [comment]
@vladzcloudius was this done in 1.5 or post 1.5 - if so we can close.

**Comment by vladzcloudius** [comment]
@slivne It's definitely done in 1.6 and 1.7. I can't find the branch-1.5 so, I can't tell what's the status of 1.5.

**Comment by slivne** [comment]
@vladzcloudius before I close - is master ok ?

**Comment by vladzcloudius** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    
    
    On 05/25/2017 06:41 AM, Shlomi Livne
      wrote:
    
    
      @vladzcloudius before I close - is
        master ok ?
    
    
    
    Should be ok - the code word is "perftune.py"
    
    
    
    
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/scylladb/scylla","title":"scylladb/scylla","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/scylladb/scylla"}},"updates":{"snippets":[{"icon":"PERSON","message":"@slivne in #1973: @vladzcloudius before I close - is master ok ?"}],"action":{"name":"View Issue","url":"https://github.com/scylladb/scylla/issues/1973#issuecomment-303980247"}}}
