### ISSUE TITLE
system_traces and system_auth tables creation may trigger issue #420

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#1976]
*Installation details*
Scylla version (or git commit hash): 1.4 (b10dcfc5f60fc65a834143f83d814e8ba6856247), master (436ce7ae4902594f74410ac6a9519f0379099c64)
Cluster size: 2+

*Description*
When a scylla cluster of 2 or more is created by simultaneous creation of all Nodes the creation of tables from `system_auth` and `system_traces` keyspaces may trigger issue #420.

The issue has been reproduced in the [dtest run](http://jenkins.cloudius-systems.com:8080/job/scylla-1.4-dtest/label=monster,mode=release,smp=1/19).

**Comment by slivne** [comment]
@vladzcloudius did 8014adc2a159a524f2cc5daf932a2992f22ebe18 resolve this issue ?

**Comment by vladzcloudius** [comment]
Yes, sir! ;)

**Comment by slivne** [comment]
so what is it ?

**Comment by vladzcloudius** [comment]
Or actually it is not. The thing is that it may still happen if a few seeder Nodes are booting up at the same time. This was actually the case in the dtest run mentioned in the initial issue post. We need to make sure that seeders are synchronizing their schemas when they boot in order to resolve this issue.

Me and @tgrabiec have described the issue to @asias on the dtest thread. Here is the Tomek's comment: "The problem is that when you start the second seed node, it will not wait for schema sync with the first one, as a non-seed would, before it completes joining and proceeds with it's own schema updates. As a result there could be two table creation statements executing concurrently in the cluster, one from the first node, and one from the second node. That will cause #420. While the proper solution to this is to serialize all schema updates across the cluster, we're not there yet. I wonder if we could do the schema sync part for all nodes, so that there are no concurrent schema changes if you start nodes one by one."

**Comment by tgrabiec** [comment]
For `system_auth` the problem should not happen because all nodes use the same table ID (`generate_legacy_id`), like Cassandra.
