### ISSUE TITLE
Update metrics names to 1.6 standard with a sed script

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#1980]
*Installation details*
Scylla version (or git commit hash): 1.6

In Scylla 1.6 metrics name are updated to a new format https://github.com/scylladb/scylla/issues/1964
While https://github.com/scylladb/scylla-grafana-monitoring users will get updated dashboards, consumers of collectd metrics or users with their own dashboards will have to do the change themselves.

To help these users, we should provide a sed script (or similar) which transform a  text base dashboard to the new metrics name.

**Comment by tzach** [comment]
@amnonh ?

**Comment by slivne** [comment]
As discussed - lets start by collecting the info and pasting the diff between 1.5 and 1.6 and then work on what extra we can do

**Comment by slivne** [comment]
closing this - we provied the info in the release notes
