### ISSUE TITLE
Scylla AMI - warn users not running in VPC as Enhanced Networking will not be enabled

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1984]
Scylla AMI supports Enhanced Networking. To utilize that - the user must select an instance that supports Enhanced Networking and use VPC. 

Scylla AMI can check the instance type and if the instance is running in VPC (using meta-data) or check the instance type using meta-data and the interfaces once the instance start and warn the user that he will not be getting the best performance

**Comment by avikivity** [comment]
Good question.  There is only so much we can do at the prompt.

We could have an API to return node notices, and display them in `nodetool status`.

**Comment by tzach** [comment]
> Does it mean we will verify it in AMI startup time? Where do we warn to user? Maybe warn it at login prompt, like EC2 instance type check?

That will be a good start, with the addition of writing to the log

**Comment by syuu1228** [comment]
@slivne To checking the instance running in VPC, we can use meta-data so we can warn if user doesn't running the instance in VPC.

About instance types, we officially supported m3.*/c3.*/i2.*, and only m3.* doesn't supported Enhanced Networking. So probably show warning message on m3.* instances?

**Comment by slivne** [comment]
@syuu1228 - ok lets start with this -

- check vpc is used based on metadata - and warn if not.
- check that driver is the correct one - and warn if not.

Please note that we may need to provide both warnings.

A user deployed us on r3 (which supports enahnced networking - yet we do
not support it out of the box).

- we do not support the instance - although the user may use it - so he may
setup the instance on his own.
- the user did not use a vpc he will not have enhanced networking - so he
need to see the warning.

**Comment by syuu1228** [comment]
@slivne sent a patch for ssh login prompt ([PATCH scylla] dist/ami/files/.bash_profile: warn user when enhanced networking is not enabled).
Should we implement warning message for other place (like tzach says to the log, or avi says to nodetool status)?

**Comment by slivne** [comment]
lets start with the log

the nodetool status - maybe a long term solutionb - yet I think we have
other issues we need to tackel so lets have something in place till we have
time todo the long term thing.
