### ISSUE TITLE
Install Scylladb on ubuntu 16.04

### ISSUE THREAD

**Issue by truyet** [scylladb/scylla#1990]
*Installation details*
Scylla version (or git commit hash):1.5
Cluster size:1
OS (RHEL/CentOS/Ubuntu/AWS AMI):Ubuntu 16.04

I want to install scyllaDB to Ubuntu 16.04 on vagrant (VirtualBox) from repository but get error:
The following packages have unmet dependencies:
 scylla : Depends: scylla-server but it is not going to be installed
          Depends: scylla-jmx but it is not going to be installed

I'm trying to install  scylla-server and scylla-jmx but they get error:
scylla-jmx : Depends: lsb-base (>= 4.1+Debian11ubuntu7) but 4.0-0ubuntu20 is to be installed
 scylla-server : Depends: libboost-date-time1.58.0 but it is not installable
                 Depends: libboost-filesystem1.58.0 but it is not installable
                 Depends: libboost-program-options1.58.0 but it is not installable
                 Depends: libboost-system1.58.0 but it is not installable
                 Depends: libboost-test1.58.0 but it is not installable
                 Depends: libboost-thread1.58.0 but it is not installable
                 Depends: libc6 (>= 2.18) but 2.15-0ubuntu10 is to be installed
                 Depends: libcrypto++9v5 but it is not installable
                 Depends: libgnutls30 (>= 3.4.6) but it is not installable
                 Depends: libgnutlsxx28 (>= 3.3.8-0) but it is not going to be installed
                 Depends: libhwloc5 (>= 1.11.2) but it is not installable
                 Depends: libjsoncpp1 but it is not installable
                 Depends: liblz4-1 (>= 0.0~r130) but it is not installable
                 Depends: libprotobuf9v5 but it is not installable
                 Depends: libsnappy1v5 but it is not installable
                 Depends: libsystemd0 but it is not installable
                 Depends: libunwind8 but it is not installable
                 Depends: libyaml-cpp0.5v5 but it is not installable
                 Depends: lsb-base (>= 4.1+Debian11ubuntu7) but 4.0-0ubuntu20 is to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by avikivity** [comment]
Do you have held packages?  See the first answer to http://askubuntu.com/questions/363200/e-unable-to-correct-problems-you-have-held-broken-packages.

**Comment by truyet** [comment]
No, I don't. I checked as same as the answer, and not found held packages ?

**Comment by dantodor** [comment]
Does it works on Ubuntu 16 or not ?
By using apt-get I'm getting same error as above, by using aptitude I'm getting this:
`The following packages have unmet dependencies:
 scylla-server : Depends: libboost-date-time1.55.0 which is a virtual package and is not provided by any available package.

                 Depends: libboost-filesystem1.55.0 which is a virtual package and is not provided by any available package.

                 Depends: libboost-program-options1.55.0 which is a virtual package and is not provided by any available package.

                 Depends: libboost-system1.55.0 which is a virtual package and is not provided by any available package.

                 Depends: libboost-thread1.55.0 which is a virtual package and is not provided by any available package.

                 Depends: libcrypto++9 which is a virtual package and is not provided by any available package.

                 Depends: libgnutls28 (>= 3.2.10-0) which is a virtual package and is not provided by any available package.

                 Depends: libjsoncpp0 (>= 0.6.0~rc2) which is a virtual package and is not provided by any available package.

                 Depends: libprotobuf8 which is a virtual package and is not provided by any available package.

                 Depends: libsnappy1 which is a virtual package and is not provided by any available package.

                 Depends: libyaml-cpp0.5 which is a virtual package and is not provided by any available package.

 scylla-tools : Depends: python-support (>= 0.90.0) which is a virtual package and is not provided by any available package.

`

Any solution ?

Thanks!

**Comment by avikivity** [comment]
@dantodor did you accidentally try to install the trusty packages on xenial?

**Comment by dantodor** [comment]
True that.. I realized after I reported, sorry for that :( .... but by using xenial I'm getting this 
`Setting up scylla-kernel-conf (1.7.0-0.20170519.25607ab-0ubuntu1) ...
sysctl: cannot stat /proc/sys/kernel/sched_tunable_scaling: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_min_granularity_ns: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_wakeup_granularity_ns: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_latency_ns: No such file or directory
sysctl: cannot stat /proc/sys/kernel/sched_autogroup_enabled: No such file or directory
sysctl: cannot stat /proc/sys/kernel/numa_balancing: No such file or directory
dpkg: error processing package scylla-kernel-conf (--configure):
 subprocess installed post-installation script returned error exit status 255
dpkg: dependency problems prevent configuration of scylla:
 scylla depends on scylla-kernel-conf; however:
  Package scylla-kernel-conf is not configured yet.

dpkg: error processing package scylla (--configure):
 dependency problems - leaving unconfigured
`

**Comment by jonathanleang** [comment]
@dantodor  did you manage to fix it ?
sysctl: cannot stat /proc/sys/kernel/sched_tunable_scaling: No such file or directory
...

**Comment by avikivity** [comment]
@jonathanleang it will be fixed in the next 1.7 release.
