### ISSUE TITLE
seastar - Exceptional future ignored: std::system_error (error system:32, Broken pipe) when using node to node encryption

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#1994]
*Installation details*
Scylla version (or git commit hash): 1444a52fae79ea43ae6e90e9d2a32173a5e52a84
"Exceptional future ignored: std::system_error (error system:32, Broken pipe)" error is printed when a node is stopped/drained

**Comment by elcallio** [comment]
This is due to a limitation/bug in the TLS layer socket shutdown. I've sent seastar patches.

**Comment by elcallio** [comment]
The corresponding fixes have been merged into seastar. This should fix this issue. Please verify and close.

**Comment by gleb-cloudius** [comment]
Verified. Would be nice to get a commit that fixed it here.

**Comment by elcallio** [comment]
Fixed by d2fc98270e809263564f6dc1d71203f14b174b95, though that is just a seastar update. Seastar commits scylladb/seastar@098db66de38dfd9857d43592379907ad0194115e and scylladb/seastar@87773a82dfaf1cc143915663c2a96424110c39aa
