### ISSUE TITLE
scylla_setup should check the networking device and warn in case its a virtual device

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#1997]
In AWS there is an option to use EnhancedNetworking - users installing scylla on their own in AWS may overlook this and run scylla with the default device.

Warn users that this is a non optimal setup (it would be better to detect that we are on AWS validate the instance type and warn).

This may be a common issue to other cloud providers that have more then one mode

rackspace -  https://support.rackspace.com/how-to/choosing-a-virtualization-mode-pv-versus-pvhvm/

**Comment by syuu1228** [comment]
@slivne Looks similar to #1984, but you are talking about installing Scylla on EC2 but not our AMI, is it correct?
In that case where should we warn to user? Maybe in scylla_setup?
Or check it in scylla_prepare, and abandon running scylla-server.service? (maybe this is not good choice)

**Comment by syuu1228** [comment]
@slivne ping

**Comment by syuu1228** [comment]
@slivne ping

**Comment by syuu1228** [comment]
@slivne ping

**Comment by slivne** [comment]
I think the correct method would be:

1. To ask the user in scyall-setup and allow him to abort 

2. We can also warn to the log in scylla-prepare that the device setup is not optimized for networking

**Comment by slivne** [comment]
@syuu1228 ping
