### ISSUE TITLE
Use continuity information to decide whether to populate cache with new entries

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#1999]
If cache is missing given key, but it has the range it falls into marked as continuous, it means sstables don't have that entry and we can insert it without asking the presence checker (bloom filter based). The latter is more expensive and gives false positives.

**Comment by slivne** [comment]
I am a bit lost

https://github.com/scylladb/scylla/blob/master/database.cc#L159

is this code obsolete ?

it seems to be called from


the code seem to check the filter which is using the sstables

1. can't we do the same here - and check the cache if it has the info /
knows there is no info ?

2.

**Comment by slivne** [comment]
On Wed, Jun 28, 2017 at 1:43 PM, Shlomi Livne <shlomi@scylladb.com> wrote:

> I am a bit lost
>
> https://github.com/scylladb/scylla/blob/master/database.cc#L159
>
> is this code obsolete ?
>
> it seems to be called from
>

https://github.com/scylladb/scylla/blob/master/database.cc#L821

**Comment by slivne** [comment]
On Wed, Jun 28, 2017 at 1:44 PM, Shlomi Livne <shlomi@scylladb.com> wrote:

>
>
> On Wed, Jun 28, 2017 at 1:43 PM, Shlomi Livne <shlomi@scylladb.com> wrote:
>
>> I am a bit lost
>>
>> https://github.com/scylladb/scylla/blob/master/database.cc#L159
>>
>> is this code obsolete ?
>>
>> it seems to be called from
>>
>
> https://github.com/scylladb/scylla/blob/master/database.cc#L821
>
>>
>>
>> the code seem to check the filter which is using the sstables
>>
>> 1. can't we do the same here - and check the cache if it has the info /
>> knows there is no info ?
>>
>

2. where is this being called from - I am a bit lost ? - do we need todo
this check twice ?

**Comment by tgrabiec** [comment]
2017-06-28 12:43 GMT+02:00 Shlomi Livne <notifications@github.com>:

> I am a bit lost
>
> https://github.com/scylladb/scylla/blob/master/database.cc#L159
>
> is this code obsolete ?
>

I don't think it is, the bloom filter based checker is still useful to
determine if we can insert a partition into a not-continuous range in
cache. Note that a range will be marked in cache as continuous only by
range scans. If there are no range scans, no range will be continuous. If
we removed this bloom-filter-based check, then update() would not be able
to insert anything.


>
> it seems to be called from
>
>
> the code seem to check the filter which is using the sstables
>
> 1. can't we do the same here - and check the cache if it has the info /
> knows there is no info ?
>

I'm not sure what you suggest.

Before the patch, we only checked bloom filter. Now, we check continuity
first, and only if the range is not continuous, we check the bloom filter.

**Comment by slivne** [comment]
My mistake you are correct.

Yet I still think we can do something better using the same (negative)
answer about partitions existing or not.

We are creating readers from sstables and for that we are checking the
bloom filters - we can try and avoid checking the bloom filters all
together (and the false negatives) if the cache indicates the partition
does not exist and we have continuity information inside the cache.

**Comment by tgrabiec** [comment]
2017-06-28 14:49 GMT+02:00 Shlomi Livne <notifications@github.com>:

> My mistake you are correct.
>
> Yet I still think we can do something better using the same (negative)
> answer about partitions existing or not.
>
> We are creating readers from sstables and for that we are checking the
> bloom filters - we can try and avoid checking the bloom filters all
> together (and the false negatives) if the cache indicates the partition
> does not exist and we have continuity information inside the cache.
>

I think we already do that what you describe, when you read through cache,
as long as the range you're currently reading is continuous, we won't even
try to create an sstable reader.
