### ISSUE TITLE
Handle unbounded number of tasks entering the system

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#2]
On a higher level, we need to ensure we don't allow an unbounded number of tasks to enter the system (admission control, we have this problem everywhere).  In the case of gossip, the proper approach is to cancel old tasks (say by killing their connections).  In other cases (main transaction processing) we need to slow/stop incoming requests until old requests have had the time to complete.  It's going to be interesting.

**Comment by slivne** [comment]
We have been handling backpressure of many cases with specific items - closing this.
