### ISSUE TITLE
write timeouts per second, but i don't know why??

### ISSUE THREAD

**Issue by andrewrong** [scylladb/scylla#2000]
*Installation details*
Scylla version (or git commit hash): 1.4.2
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos7

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): phy
Hardware: sockets= cores=32 hyperthreading= memory=64G
Disks: (SSD/HDD, count) HDD raid5 30T

scylla-service

```
SCYLLA_ARGS="--smp 25 -m50G --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix"
```

I find that the scylla have some write timeout in this monitor

![image](https://cloud.githubusercontent.com/assets/1272833/21746871/62cb6736-d58f-11e6-89f0-8249b9f31223.png)

But i don't know what causes it? 

My table:

```
CREATE TABLE mogulog.originlog (
    uuid text PRIMARY KEY,
    content text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'chunk_length_kb': '64', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

the primary key is `uuid`, the key is unique; `content` is a row of log; 

```
Keyspace: mogulog
	Read Count: 6297
	Read Latency: 0.0011978720025408924 ms.
	Write Count: 1092811598
	Write Latency: 2.5350885780039096E-5 ms.
	Pending Flushes: 0
		Table: originlog
		SSTable count: 191
		SSTables in each level: [191/4]
		Space used (live): 270062802137
		Space used (total): 270062802137
		Space used by snapshots (total): 215179956
		Off heap memory used (total): 1701089276
		SSTable Compression Ratio: 0.473532
		Number of keys (estimate): 1033053357
		Memtable cell count: 1247874
		Memtable data size: 1391051403
		Memtable off heap memory used: 1495793664
		Memtable switch count: 100
		Local read count: 6297
		Local read latency: 0.001 ms
		Local write count: 1092811598
		Local write latency: 0.000 ms
		Pending flushes: 0
		Bloom filter false positives: 8
		Bloom filter false ratio: 0.00000
		Bloom filter space used: 0
		Bloom filter off heap memory used: 162791724
		Index summary off heap memory used: 42503888
		Compression metadata off heap memory used: 0
		Compacted partition minimum bytes: 73
		Compacted partition maximum bytes: 454826
		Compacted partition mean bytes: 472
		Average live cells per slice (last five minutes): 0.0
		Maximum live cells per slice (last five minutes): 0.0
		Average tombstones per slice (last five minutes): 0.0
		Maximum tombstones per slice (last five minutes): 0.0

----------------
```

The qps :

![image](https://cloud.githubusercontent.com/assets/1272833/21746890/10063fde-d590-11e6-9c3a-dc147fbbe635.png)

Can you help me that find the reason about write timeout ？ thank you

**Comment by avikivity** [comment]
It's impossible to say just from these metrics.  However 1.5 has some improvements in this area (see http://www.scylladb.com/2016/12/15/sswc-part1/) so upgrading may help.

**Comment by tzach** [comment]
@andrewrong can you please update?
Did moving to 1.5 help?

**Comment by andrewrong** [comment]
@tzach Because I have used scylladb in my product environment，so I don't update the scylladb immediately; Today the scylladb version is 1.6, so i will update it soon; 

My problem:

my replication is two and my client consistency level is all, If i update the scylla, would cause write failure???

**Comment by avikivity** [comment]
Yes.  You should either increase the replication factor (with `ALTER TABLE`) or decrease the consistency level.  It's not just a problem with upgrades, any failure would cause this.

**Comment by slivne** [comment]
@andrewrong I am closing this issue if there is a need for additional information / help please post and we can reopen.
