### ISSUE TITLE
Spurious low memory condition

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#2002]
*Installation details*
Scylla version (or git commit hash): 38b2fa27ad1fe46506fca583b5314857af6c0f3f
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora 25

*Hardware details (for performance issues)* 16 lcore , 64 GiB ram
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets=1  cores=8 hyperthreading=yes memory=64GiB
Disks: (SSD/HDD, count) 256 GB SSD

Without developer mode scylla exit on low memory while plenty of RAM is here

    [root@localhost scylla]# free
              total        used        free      shared  buff/cache   available
    Mem:       65872992      736428    60297512        1848     4839052    64814012
    Swap:      25006076           0    25006076
    [root@localhost scylla]# cat /proc/cpuinfo |grep processor|wc
     16      48     230
    [root@localhost scylla]# ./build/release/scylla
    Scylla version 666.development-20170108.c92763c starting ...
    ERROR 2017-01-08 13:14:43,002 [shard 0] init - Only 226 MiB per shard; this is below the recommended minimum of 1 GiB/shard; terminating.Configure more memory (--memory option) or decrease shard count (--smp option).
    ERROR 2017-01-08 13:14:43,002 [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (configuration (memory per shard too low))
    [root@localhost scylla]

With developer mode scylla starts

**Comment by PDeveloper** [comment]
Is / was there any follow-up to this elsewhere?
