### ISSUE TITLE
Best Java driver

### ISSUE THREAD

**Issue by WhiteTrashLord** [scylladb/scylla#2003]
I would like to test Scylla with Java. I saw that you have this Github project:

https://github.com/scylladb/java-driver

The problem is that it wasn't updated for a long time.  Maybe you can add to the project documentation why it wasn't updated in a long time :)

Would be https://github.com/datastax/java-driver the better driver?

Or are there even better Java drivers?

**Comment by avikivity** [comment]
You should use the datastax Java driver with Scylla.
