### ISSUE TITLE
instances created from same AMI have repeated housekeeping.uuid

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla#2004]
*Installation details*
Scylla version (or git commit hash):  1.6.rc0-20170105.337d6fb
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-a3a5bfb4

Right now, we have a generated housekeeping.uuid in setup stage, so AMI already has one, the new instances won't re-generate, so they are repeated.

[private job/scylla-ami-perf-regression-dev/slave=muninn,sub_test=test_write/104/console ](http://jenkins.cloudius-systems.com/job/scylla-ami-perf-regression-dev/slave=muninn,sub_test=test_write/104/console)

**Comment by kongove** [comment]
This patch from @amnonh should already solve this issue:
[PATCH scylla v2 0/2] scylla-housekeeping create its own uuid file

**Comment by penberg** [comment]
@slivne this is fixed by commit https://github.com/scylladb/scylla/commit/8cd3d7445cc4a2eb3c674c7f369b41f9b982bf19. Closing.

**Comment by kongove** [comment]
Verified that Takuya's patch (bee7f54) fixed this issue, Unique uuid file can be generated for each AMI instance.
