### ISSUE TITLE
system keyspace should use a class of its own

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#2006]
ref #1459 , #1913 

system keyspace operations should not be blocked behind other operations.

the only exception to this maybe the batchlog

its not clear if we should provide a "fast" path for system commitlog entries.

**Comment by tgrabiec** [comment]
@slivne There is no issue #4529, which one did you mean?


Refs #1926.

**Comment by slivne** [comment]
@tgrabiec I referenced the same issue you have pointed to #1459

**Comment by avikivity** [comment]
Fixed by 0c6bbc84cd30df1c46a6cd81d87170b99d5a8144
