### ISSUE TITLE
populate non system keyspaces in parallel

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#2007]
When populating non-system keyspaces, we scan data dir and for each entry (keyspace dir) which name isn't 'system', we populate the keyspace. That's done serially.

I think it makes sense to load non system keyspaces in parallel so as to increase parallelism and reduce boot time because population is I/O intensive and barely uses CPU.

The list of non system keyspaces is available, and scanning data dir for them is uneeded. So we only need to get the list and iterate through it in parallel calling distributed_loader::populate_keyspace()

**Comment by raphaelsc** [comment]
It's worth adding that population of column families for a keyspace K is done in parallel, and in turn, loading of sstables for a column family C is also done in parallel. The question is: Is that enough to saturate really fast disks? Do we also want to populate all non system keyspaces in parallel?

**Comment by avikivity** [comment]
Queued as c04e8c37aa7b1bfcf301b06cfea6be978958e4ec

**Comment by avikivity** [comment]
Enahncement, removing backport candidate label.
