### ISSUE TITLE
bad resource usage distribution when resharding due to refresh via upload dir

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#2008]
That's because a *single* shard is used to calculate generation for new sstables in upload directory, and that will result in that single shard sharing all the resources with other shards.

For refresh without upload dir, it currently works fine because we reshuffle column family dir instead.

**Comment by raphaelsc** [comment]
@avikivity: should this be fixed for 1.6?!

**Comment by avikivity** [comment]
I disabled the new sharding algorithm for 1.6, so no. But should be fixed ASAP.
