### ISSUE TITLE
Spike occurs in only one shard

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2010]
*Installation details*
version : scylla 1.5 / SSD / cetos / 3node / 16core 48GB / bare metal server

I tested write only load ..  ( 100 batch insert)

seastar_commitlog(requests_blocked_memory,pending_allocations) graph shows a spike on just only one shard ( #15 shard in node2)

Could you explain now status of scylla and how to solve this ??

purple line is shard15

irate(seastar_commitlog{type="total_operations", metric="requests_blocked_memory"} [30s])
![image](https://cloud.githubusercontent.com/assets/10610884/21918195/2fc19ce6-d992-11e6-9058-c793d377a4c4.png)

irate(seastar_commitlog{type="queue_length",metric="pending_allocations"} [30s])
![image](https://cloud.githubusercontent.com/assets/10610884/21918200/385722b8-d992-11e6-8071-d82fd16c775f.png)

![image](https://cloud.githubusercontent.com/assets/10610884/21918299/585de5aa-d993-11e6-9893-eed5f6172a87.png)

![image](https://cloud.githubusercontent.com/assets/10610884/21918302/5ceb2204-d993-11e6-9f13-9d3aabeba1dd.png)

![image](https://cloud.githubusercontent.com/assets/10610884/21918307/609526e8-d993-11e6-8708-eb78b8501754.png)

![image](https://cloud.githubusercontent.com/assets/10610884/21918310/6432de58-d993-11e6-9b41-1461772a2b86.png)

perf top -C15
![image](https://cloud.githubusercontent.com/assets/10610884/21918314/6850ea52-d993-11e6-9f61-7e80d6ef2c53.png)

**Comment by glommer** [comment]
In my experience, the two main causes for spikes are:
1) bad sharding
2) bad data modeling.

What we need to determine here is whether all those requests are being sent to the same partition key (bad modeling), or if they are sent to a group of partition keys that all happen to shard to the same shard (bad sharding).

**Comment by infordb** [comment]
this is schema and sample data 
![image](https://cloud.githubusercontent.com/assets/10610884/22004090/2fa5858a-dc9c-11e6-9f9c-dd27ab376624.png)
 - partition_key : 1day
 - param_index : sensor_id
 one partition is 1day data of 1 sensor..

write load program put sensor data uniformly

**Comment by glommer** [comment]
Hi,

It is important to understand that Scylla always map the same partition key to the same CPU, not only the same node. This is one the things that allow us to use a lot of lockfree algorithms and a core part of our design.

So if all writes over a period of time have the same partition key + param_index, they will all be served by the same CPU - regardless of their clustering key. We have seen many users facing this problem in the past, and our recommendation has always been to increase the granularity of your partition key.

**Comment by dorlaor** [comment]
@glauber, I think Junghyun  knows that, the question if the load was even
and whether a single sensor
was mostly used or it's an even case. More data is needed to analyze it

**Comment by glommer** [comment]
@dorlaor it seems like you have just tagged a random person - my username is glommer =)

But yes - from my original answer, most of the time we have seen patterns like this, it turned out to be because only (or mostly) a single partition was getting writes. We need to first hear from them to make sure whether or not this is the case.

**Comment by infordb** [comment]
@glommer  I tested it with 30,000 param_index , and All sensors(param_index) are input simultaneously.


Below is another use case 
 - schema : partition key / column   (not using clustering key)
 - write only ( partition key is always different)
Shard8 does not process requests much, but has pending spike ..
What do I need to check to find the cause of the problem?


![image](https://cloud.githubusercontent.com/assets/10610884/22013762/09a43dbc-dcde-11e6-8bc6-c259f4321a8e.png)
![image](https://cloud.githubusercontent.com/assets/10610884/22013764/10d5b20a-dcde-11e6-910f-06d5497ae790.png)
![image](https://cloud.githubusercontent.com/assets/10610884/22013769/150f4c50-dcde-11e6-88a7-fa1a76b93192.png)

**Comment by dorlaor** [comment]
@slivne @glommer Pls assign it to someone that can help soon

**Comment by glommer** [comment]
@infordb in your first graph, can you tell us exactly which metric are you using for the  "segments migrated" graph ?

**Comment by infordb** [comment]
@glommer seastar_lsa{instance="stgtest02" , metric="segments_migrated"}

**Comment by tgrabiec** [comment]
@infordb Note that Scylla shard numbers are not the same as CPU numbers. So when you do `perf top -C15`, you don't necessarily sample shard 15. Did you check with `mpstat -P ALL 1` that it is `-C15` which is most busy?

**Comment by infordb** [comment]
@ I checked all cores with top + 1  core15 was most busy , and other cores also were busy too

**Comment by slivne** [comment]
@infordb can you download the prometheus data and upload it somewhere - this will probably help in reducing the back and force,

can you also provide the ``mpstat -P ALL 1`` info @tgrabiec requested.

**Comment by tgrabiec** [comment]
It's best to run node_exporter (https://github.com/prometheus/node_exporter), then if we get the metrics, we would also get the data mpstat would report.

**Comment by infordb** [comment]
from : 2017-01-20 13:53:00
to     : 2017-01-20 14:24:00
timezone : gmt +9


[prometheus_spike.tar.gz](https://github.com/scylladb/scylla/files/718497/prometheus_spike.tar.gz)

**Comment by tgrabiec** [comment]
Looks like all shards have more or less the same write throughput, and all commitlog IO queues do more or less the same IOPS. 

![screenshot from 2017-01-23 15-11-05](https://cloud.githubusercontent.com/assets/283695/22207387/3f334a9a-e17f-11e6-862f-dca9598e3d0c.png)

The queues for shards 15 and 8 experience much more delay (two shades of purple):

![screenshot from 2017-01-23 15-23-00](https://cloud.githubusercontent.com/assets/283695/22207537/d75a5340-e17f-11e6-9461-727a4e83d1f2.png)

Looks like the system is configured with 15 IO queues but has 16 shards (1 more). Shard 15 doesn't have its own queue but rather delegates to the queue on shard 8. This results in shard 8 having double IO load than other shards, as it has to serve load from both shard 8 and shard 15. 

@infordb What's your IO queues configuration (/etc/scylla.d/io.conf)? Can you try running with 16 IO queues to confirm that this is the problem?

**Comment by infordb** [comment]
@tgrabiec  
[root@stgtest01 ~]# cat /etc/scylla.d/io.conf
SEASTAR_IO="--max-io-requests=60 --num-io-queues=15"

I will test whth 16 io queue

**Comment by tgrabiec** [comment]
@infordb Note that the throughput seems to be the same for shards 8 and 15 despite they experiencing larger commitlog latency. I wouldn't expect throughput to improve, though it's still worth doing. The system seems CPU-bound. If improving throughput is your goal, then we should check CPU flame graphs.

**Comment by glommer** [comment]
On Tue, Jan 24, 2017 at 6:03 AM, Junghyun Park <notifications@github.com>
wrote:

> @tgrabiec <https://github.com/tgrabiec>
> [root@stgtest01 ~]# cat /etc/scylla.d/io.conf
> SEASTAR_IO="--max-io-requests=60 --num-io-queues=15"
>
> I will test whth 16 io queue
>

Note that to use 16 I/O queues, you will need at least 64 requests.

You can bump that up manually for the sake of testing.


>

**Comment by eyalgutkind** [comment]
Hi, Another data point, with similar phenomenon.
Using ScyllaDB 1.5.0 (ami-23b80f43), on three (3), c3.2xlarge using their SSD volumes. Benchmarking with Cassandra-stress. 10 loaders, each have a different range of data writes. (see command used to stress, below), we are getting similar experience:
![image](https://cloud.githubusercontent.com/assets/17868115/22717528/6833ca78-ed50-11e6-9025-896c1fd3ace1.png)

Causing write timeout on the node
![image](https://cloud.githubusercontent.com/assets/17868115/22717580/bce66832-ed50-11e6-8654-9940ac6c294f.png)

Loaders command:
 ./ec2-stress.sh 1 -e "load_name=scylla.3smlfillt2" -e "server=Scylla" -e "command=write" -e "stress_options='-schema \"replication(factor=3)\" -errors ignore'" -e "command_options='n=14000000 cl=QUORUM -mode native cql3'" -e "threads=500" -e "seq_populate=14000000" -e "clean_data=true"

Let me know if you need any additional information.

**Comment by tgrabiec** [comment]
@eyalgutkind Please [upload](https://github.com/scylladb/scylla/wiki/How-to-report-a-Scylla-problem#prometheus) the prometheus database

**Comment by avikivity** [comment]
Stale, unclear. Closing.
