### ISSUE TITLE
iotune for latency

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2013]
Currently, iotune selects for throughput by admitting requests until we're just after the throughput knee.  We could provide an alternative tuning, so it is just before the latency knee (the two knees are related, probably within a factor of two of each other).

**Comment by glommer** [comment]
@avikivity please close, as this was recently reworked. IOTune no longer works with knee-finding.

**Comment by glommer** [comment]
Now iotune is fully merged.
