### ISSUE TITLE
how to use pstack command for scylladb stack trace

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2018]
*Installation details*
Scylla version (or git commit hash): 1.6
OS (RHEL/CentOS/Ubuntu/AWS AMI):CentOS

I  tried to check stack trace of Scylladb..
But pstack command returned nothing

[root@stgtest01 ~]# ps -ef | grep scylla
scylla   23429     1 99 15:44 ?        00:00:26 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --start-rpc true --smp 16 -m 48G --max-io-requests=60 --num-io-queues=15
scylla   23484     1  7 15:44 ?        00:00:00 java -Dcassandra.jmx.local.port=7199 -Xmx256m -XX:+UseSerialGC -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -jar /usr/lib/scylla/jmx/scylla-jmx-1.0.jar
root     23515 13115  0 15:44 pts/4    00:00:00 grep --color=auto scylla

[root@stgtest01 ~]# pstack 23429
[root@stgtest01 ~]#

**Comment by tzach** [comment]
@infordb I'm not sure pstack will give you what you need.
Can you elaborate on what you are trying to find?

**Comment by infordb** [comment]
@tzach We use it to check thread stack information. I can not use pstack only with scylla.

**Comment by tzach** [comment]
@tgrabiec can you point @infordb to relevant debug info?
Not sure pstack is the right tool here
