### ISSUE TITLE
Better filtering support (without indexes)

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#2025]
*Installation details*
Scylla version (or git commit hash): 1.6

Consider the following table:

```
CREATE TABLE t (p int, c int, v int, PRIMARY KEY (p, c));
```

Trying to filter the regular columns `v` results in errors about indexes not being implemented:

```
cqlsh:ks> select * from t where c = 0 and v = 1 allow filtering;
ServerError: Not implemented: INDEXES
cqlsh:ks> select * from t where p = 0 and v = 1 allow filtering;
ServerError: Not implemented: INDEXES
cqlsh:ks> select * from t where p = 0 and c = 0 and v = 1 allow filtering;
ServerError: Not implemented: INDEXES
```

On Cassandra 3.X, however, they are supported:

```
cqlsh:ks> select * from t where c = 0 and v = 1 allow filtering;

 p | c | v
---+---+---
 0 | 0 | 1

(1 rows)
cqlsh:ks> select * from t where p = 0 and v = 1 allow filtering;

 p | c | v
---+---+---
 0 | 0 | 1

(1 rows)
cqlsh:ks> select * from t where p = 0 and c = 0 and v = 1 allow filtering;

 p | c | v
---+---+---
 0 | 0 | 1

(1 rows)
```

I don't know if this is a consequence of storage format improvements, or just plain code.

**Comment by tzach** [comment]
@duarten is it new in C* 3.x?

**Comment by duarten** [comment]
@tzach I think so, yes.

**Comment by tzach** [comment]
https://issues.apache.org/jira/browse/CASSANDRA-6377

**Comment by penberg** [comment]
As I already mentioned to @slivne privately, there are existing bugs in the CQL query path, which cause non-PK queries to fail with `No index found` error. The issue here is that the code is overly eager to think we have a backing secondary index when we really don't. `ALLOW FILTERING` doesn't work correctly either, which needs to be fixed.

**Comment by EfratSo** [comment]
Facing same problem,

`cqlsh> select item_id from items where timestamp > '2018-03-19 14:16:12+0000' allow filtering;
ServerError: Not implemented: INDEXES`

any other way to filter by time (when it's not the only key)?

**Comment by nyh** [comment]
Note that #3405 (of secondary indexing) is related to this issue. In #3405, we don't have an API to get a bunch of individual CQL rows from the table, so we use the API to read entire **partitions** instead, and end up with too many rows, which we need to filter according to the given restrictions. I.e., we need filtering of the results just like in this issue.
