### ISSUE TITLE
resharding may break LCS invariant

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#2026]
If we're resharding a L1 sstable (it remains in level 1), it may happen that an ongoing L0->L1 compaction is writing to same token range at the moment, leading to overlap in level 1. We should either limit LCS to STCS in level 0, or resharded sstable goes to level 0, or somehow lock ranges for a specific level.

**Comment by raphaelsc** [comment]
The latest idea is the hardest to implement, but it seems to be the best one.

**Comment by tzach** [comment]
@raphaelsc is the fix for this part of your resharding patch?

**Comment by raphaelsc** [comment]
@tzach yes, a fix is included
