### ISSUE TITLE
The limit in CQL query involving aggregates should apply to CQL result rather than input to the aggregate

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2028]
*Installation details*
Scylla version (or git commit hash): 1.7

Currently `select count(*) from table limit 1` will return `1`. It should return the actual number of CQL rows in the table instead.

This change of semantics was introduced in Cassandra 2.2.

**Comment by eliransin** [comment]
If limit apply to the CQL result so we ignore it altogether when we have an aggregate. right? (assuming limit 0 is illegal as enforced by scyllaDB).

**Comment by penberg** [comment]
For future reference, there's no Cassandra issue that explicitly talks about changing the behavior of `LIMIT` for aggregate queries. Instead, it's discussed in the following bug report, which is actually requesting the old behavior:

https://issues.apache.org/jira/browse/CASSANDRA-8216

It's not clear to me if they first changed the behavior unintentionally but apparently the Cassandra developers decided the new behavior was better and therefore added a small note about it in changelog:

https://github.com/apache/cassandra/blob/cassandra-2.2/NEWS.txt
