### ISSUE TITLE
Align ordering of results of CQL queries using IN restriction with Cassandra 2.2

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2029]
*Installation details*
Scylla version (or git commit hash): 1.7

Cassandra's NEWS.txt entry for 2.2 :

> The results of CQL3 queries containing an IN restriction will be ordered in the normal order and not anymore in the order in which the column values were specified in the IN restriction.

Change made as part of  https://issues.apache.org/jira/browse/CASSANDRA-7981

**Comment by slivne** [comment]
and remove duplicates ref "Duplicate rows returned when in clause has repeated values (https://issues.apache.org/jira/browse/CASSANDRA-6706) "
