### ISSUE TITLE
nodetool netstats shows error when node is joining

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla#2034]
Configuration:

- Scylla 1.5 official AMI 
- Started with a 4 nodes cluster
- Decommissioned the first node
- Wrote data to the 3 nodes cluster
```
cassandra-stress write n=1 cl=ALL -schema "replication(factor=3)" -mode native cql3 -node $SERVERS
time cassandra-stress write cl=TWO n=5000000 -mode native cql3 -rate threads=700 -node $SERVERS -pop seq=1..5000000 -col 'size=FIXED(2048) n=FIXED(5)'
```
- In the first decommissioned node
   - deleted the data & commit log folders
   - changed the default auto bootstrap back to true (it's false in AWS)
   - Started the Scylla service
- While the node was joining I ran "nodetoool netstats" from the joining node, and got the following error:
```
Mode: JOINING
Not sending any streams.
Read Repair Statistics:
Attempted: 9
Mismatch (Blocking): 0
Mismatch (Background): 0
Pool Name                    Active   Pending      Completed
nodetool: Scylla API server HTTP GET to URL '/messaging_service/messages/pending' failed: Not found
See 'nodetool help' or 'nodetool help <command>'.
```

**Comment by tzach** [comment]
@amnonh?

**Comment by amnonh** [comment]
On Mon, Jan 23, 2017 at 5:27 PM, Tzach Livyatan <notifications@github.com>
wrote:

> @amnonh <https://github.com/amnonh>?
>
Lookds like the API wasn't started yet, probably because the node was in
joining state

**Comment by noamha** [comment]
I don't know if it helps, my if I recall correctly nodetool status did fuction.

**Comment by slivne** [comment]
@noamha - if you can try and retest with latest versions - we did move many things in boot order and it may have been fixed.

**Comment by benoit-canet** [comment]
@noamha: Is it still valid ? Did you retried or can I proceed on this bug ?

**Comment by benoit-canet** [comment]
@noamha : I will try to reproduce with 2.0 AMI

**Comment by benoit-canet** [comment]
@amnonh @slivne I reproduced the case with 2.0

Initially I decommisionned the seed node so it was trying to join it self.
Then I set seed_node to another member of the live cluster. it joined at boot.

nodetool status works and nodetool netstats gives:
[root@ip-172-31-7-163 ~]# nodetool netstats
Mode: JOINING
Bootstrap 43488be0-9c64-11e7-900d-000000000000
    /172.31.7.13
        Receiving 1 files, 0 bytes total. Already received 1 files, 708982342 bytes total
            rxnofile 708982342/708982342 bytes(100%) received from idx:0/172.31.7.13
    /172.31.3.84
        Receiving 1 files, 0 bytes total. Already received 1 files, 705569194 bytes total
            rxnofile 705569194/705569194 bytes(100%) received from idx:0/172.31.3.84
    /172.31.7.124
        Receiving 1 files, 0 bytes total. Already received 1 files, 801140132 bytes total
            rxnofile 801140132/801140132 bytes(100%) received from idx:0/172.31.7.124
Read Repair Statistics:
Attempted: 8
Mismatch (Blocking): 0
Mismatch (Background): 0
Pool Name                    Active   Pending      Completed   Dropped
nodetool: Scylla API server HTTP GET to URL '/messaging_service/messages/pending' failed: Not found
See 'nodetool help' or 'nodetool help <command>'.

**Comment by benoit-canet** [comment]
This delay in messaging service init is probably at result of e6f63a50e16408fe20a643fdcee123492e92888f

**Comment by amnonh** [comment]
I've rebased and tested https://github.com/benoit-canet/scylla/commit/d782c089eb66f0c9033f53569f69c0c0dd73314e

It does not solve the issue.
nodetool netstats needs both the storage_service and messaging_service.
So just moving the messaging_service is not enough
