### ISSUE TITLE
cannot boot after "out of disk space error"

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#2038]
*Installation details*
Scylla version (or git commit hash): 8c65b98ea7821a9e62a57b0e1d50f7418a4b65f2

During compaction a node ran out of space and stopped, after restarting I get:

```
ERROR 2017-01-25 12:29:46,752 [shard 0] database - malformed sstable system-compaction_history-ka-113-TOC.txt: SSTable too big: 4096 bytes in sstable /var/lib/scylla/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/system-compaction_history-ka-113-TOC.txt. Refusing to boot
ERROR 2017-01-25 12:29:46,797 [shard 0] database - Exception while populating keyspace 'system' with column family 'compaction_history' from file '/var/lib/scylla/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca': sstables::malformed_sstable_exception (SSTable too big: 4096 bytes in sstable /var/lib/scylla/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/system-compaction_history-ka-113-TOC.txt)
ERROR 2017-01-25 12:29:46,798 [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Exception while populating keyspace 'system' with column family 'compaction_history' from file '/var/lib/scylla/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca': sstables::malformed_sstable_exception (SSTable too big: 4096 bytes in sstable /var/lib/scylla/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/system-compaction_history-ka-113-TOC.txt))
```

There is 11G of free space, so enough for strartup at least.

**Comment by avikivity** [comment]
Because we use DMA, we write 4k into the TOC, then truncate it.  Looks like that failed.

However, we should have written that 4k into a "temporary TOC", then truncated it, then renamed it.  Somehow the write worked, the truncate did not, but the rename did.

**Comment by raphaelsc** [comment]
I think the problem may be that file_data_sink_impl isn't propagating failure to flush() or close() callers. Failure is only being propagated if there's another call to put(). So basically, if only one put() is needed (files smaller than buffer size such as TOC) for user + flush() + close(), it may happen the user never sees the problem. I'll check if this is true.

**Comment by raphaelsc** [comment]
However, it still doesn't explain TOC (not temporary) which wasn't truncated to actual size. When creating a new sstable, we write TOC content into temporary TOC and truncate it before starting writing content to DATA, and only when done, we rename temporary TOC.

**Comment by avikivity** [comment]
How are flush() or close() not propagating errors?  They are very simple.

**Comment by raphaelsc** [comment]
On Tue, May 2, 2017 at 2:55 AM, Avi Kivity <notifications@github.com> wrote:

> How are flush() or close() not propagating errors? They are very simple.
>
It turns out I was wrong, but my concern was if a failure in write (write
behind enabled) would always be propagated through subsequent calls to
flush() or close(). That could have explained missing TOC for data and
index files, resulting from a sstable write which failed.

**Comment by raphaelsc** [comment]
On Tue, May 2, 2017 at 3:32 AM, Raphael S. Carvalho <raphaelsc@scylladb.com>
wrote:

>
>
> On Tue, May 2, 2017 at 2:55 AM, Avi Kivity <notifications@github.com>
> wrote:
>
>> How are flush() or close() not propagating errors? They are very simple.
>>
> It turns out I was wrong, but my concern was if a failure in write (write
> behind enabled) would always be propagated through subsequent calls to
> flush() or close(). That could have explained missing TOC for data and
> index files, resulting from a sstable write which failed.
>

It couldn't actually because there should be an empty temporary TOC, at
least.

**Comment by tzach** [comment]
@roydahan do we have out of disk space nemesis to test such use cases?

**Comment by roydahan** [comment]
Yes.

**Comment by tzach** [comment]
Thanks @roydahan 
@gleb-cloudius @raphaelsc @avikivity closing as this is an old issue that was not reproduced.

**Comment by mingfang** [comment]
I can recreate this problem 100% of the time when I mount `/var/lib/scylla` on a cephfs volume.
I have a cluster of 3 that starts up fine from scratch.
But I get this error on startup when I bounce on of the nodes.

**Comment by mcronce** [comment]
Sorry for necroposting...I'm experiencing the same as @mingfang - Scylla on cephfs reliably fails when trying to come back up from a restart.  Is there any repair procedure?
