### ISSUE TITLE
Node remains in status UL after failed decommission 

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#2042]
*Installation details*
Scylla version (or git commit hash): 1.6.rc1
Cluster size: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

In case a decommission operation failed (e.g. remote node was killed during the streaming), the decommissioned node remains in status UL and doesn't return to status UN.

(The status is the same in all nodes in the cluster)

```
[centos@ip-172-30-0-199 ~]$ nodetool --host localhost decommission
nodetool: Scylla API server HTTP POST to URL '/storage_service/decommission' failed: stream_ranges failed
See 'nodetool help' or 'nodetool help <command>'.
[centos@ip-172-30-0-199 ~]$ nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens  Owns    Host ID                               Rack
UN  172.30.0.104  3.11 GB    256     ?       39ed8e91-4172-48ca-80c4-ca26990f9a64  rack1
UL  172.30.0.199  5.33 GB    256     ?       42f45fbc-a133-4190-9198-fff0fbe5a6d9  rack1
UN  172.30.0.208  2.13 GB    256     ?       daf2c688-b844-4c89-b964-0f7fa2448103  rack1
UN  172.30.0.64   2.3 GB     256     ?       5ed4c25c-bf7f-41ad-9b40-36c306954054  rack1
DN  172.30.0.49   5.91 GB    256     ?       f2c89825-5878-45e0-9af8-4fa0590de008  rack1
```

**Comment by asias** [comment]
A reboot is needed to put the failed decommission node to be in UN again. 
It is hard to put the node automatically back into UN.

**Comment by slivne** [comment]
@asias is that true for cassandra as well ? in case of a failed decommission the node needs restarting ?

**Comment by slivne** [comment]
the answer is yes .... in cassandra a reboot is required as well.

we may need to document that / include it in FAQ - @tzach

**Comment by tzach** [comment]
Already documented http://docs.scylladb.com/operating-scylla/troubleshooting/failed_decommission/
Thanks to @nirmaayan
