### ISSUE TITLE
make compaction log less noisy

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#2043]
Nowadays, most of the Scylla system log is taken by compaction information. That makes the log files gigantic and hard to read, parse, and transfer around for remote debugging.

Compaction is a normal and expected process and we should log them somewhere else.

We need to be able to query the process of compaction, including the number of SSTables compacted and their sizes (but their names is rarely interesting), as well as the pace in which they are happening.

**Comment by glommer** [comment]
Closing this, as this is unlikely to happen. This is also how cassandra does it, and the list of files being compacted is usually very useful.

**Comment by avikivity** [comment]
Actually, I think compaction should be moved to DEBUG, and we should provide tools around the compaction_history table.
