### ISSUE TITLE
add more counters about timeouts

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#2044]
Timeouts can occur for many reasons, and right now we only log the fact that they have happened - not where exactly they have happened.

We should augment that information throughout the storage proxy code to increase our debugging capabilities.

**Comment by gleb-cloudius** [comment]
On Thu, Jan 26, 2017 at 06:46:46AM -0800, Glauber Costa wrote:
> Timeouts can occur for many reasons, and right now we only log the fact that they have happened - not where exactly they have happened.
> 
> We should augment that information throughout the storage proxy code to increase our debugging capabilities.
> 
Storage proxy code already has counters for each failed read/write from a
replica, database layer should have such counters in each place request
may timeout.

--
			Gleb.
