### ISSUE TITLE
CREATE TABLE WITH ID 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#2059]
Mirror of https://issues.apache.org/jira/browse/CASSANDRA-9179

**Comment by argenet** [comment]
For this feature/fix to work, we need to support CommitLog Archiver which is currently not there:
https://docs.datastax.com/en/cassandra/2.1/cassandra/configuration/configLogArchive_t.html

**Comment by avikivity** [comment]
It can be implemented independently, it just won't be as useful.

`archive_command` looks really nasty. We should allow specifying a commitlog archive directory and scylla will copy or rename the file according to circumstance.

**Comment by avikivity** [comment]
Note: `WITH ID` is still useful for creating internal tables.
