### ISSUE TITLE
scylla-ami-setup.service entered failed state.

### ISSUE THREAD

**Issue by susantomahato88** [scylladb/scylla#2069]
*Installation details*
Scylla version (or git commit hash):
Cluster size:Instace type c3.xlare.
OS (RHEL/CentOS/Ubuntu/AWS AMI):AWS AMI

Issue:
scylla 1.3 is not able to up after server reboot.

 scylla_ami_setup[2554]: RAID does not constructed, going to initialize...
 scylla_ami_setup[2554]: Found disk /dev/xvdd
 scylla_ami_setup[2554]: Creating RAID0 for scylla using 1 disk(s): /dev/xvdd
 scylla_ami_setup[2554]: /dev/md0 is already using
 systemd[1]: scylla-ami-setup.service: main process exited, code=exited, status=1/FAILURE
 systemd[1]: Failed to start Scylla AMI Setup.

 systemd[1]: Job scylla-housekeeping.timer/start failed with result 'dependency'.
 systemd[1]: Job scylla-server.service/start failed with result 'dependency'.
 systemd[1]: Unit scylla-ami-setup.service entered failed state.
 polkitd[2050]: Unregistered Authentication Agent for unix-process:2539:66446 (system bus name :1.33, object path /
 systemd[1]: scylla-ami-setup.service failed.

**Comment by susantomahato88** [comment]
ISSUE:
--------
After reboot scyllla_ami_setup was again want to configure RAID-0 and got failed so all process was terminated with exit 1.

FIX:
----------
On file 
/usr/lib/scylla/scylla-ami/scylla_ami_setup 

comment part of the code which again trigger RAID configuration  and rerun scylla_ami_setup.

This time scylla will be work.



if [ $RAIDCNT -ge 1 ]; then

    echo "RAID already constructed."

    if [ "`mount|grep /var/lib/scylla`" = "" ]; then

        mount -o noatime /dev/$RAIDDEV /var/lib/scylla

    fi

else

    echo "RAID does not constructed, going to initialize..."

    DISKS=""

    for i in /dev/xvd{b..z}; do

        if [ -b $i ];then

            echo "Found disk $i"

            if [ "$DISKS" = "" ]; then

                DISKS=$i

            else

                DISKS="$DISKS,$i"

            fi\

        fi

    done

   # if [ "$DISKS" != "" ]; then


    #    /usr/lib/scylla/scylla_raid_setup --disks $DISKS

    #fi

fi

**Comment by slivne** [comment]
@glommer  - I think you had a patch for that - no ?

**Comment by glommer** [comment]
He mentions scylla 1.3, which is no longer supported. I fixed similar
issues that were merged in 1.7
