### ISSUE TITLE
Houskeeping: uuidgen, is it a mandatory package, do you check its presence before try to execute it?

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla#2070]
*Installation details*
Scylla version (or git commit hash): Scylla 1.5
Cluster size: 1   node
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): Joyent Container environment

While executing scylla_setup
The script exited with the following error, can you explain the reason for prompting the error in relation to the autoboot question?

root@9bffed33-a516-4a7d-db7b-f238c4daf63b:~# sudo scylla_setup
Skip any of the following steps by answering 'no'
Do you want to run kernel version check?
Answer yes to have this script verify that the currently installed kernel is qualified to run Scylla; answer no to skip this check.
[YES/no]no
Do you verify ScyllaDB packages installed?
Answer yes to have this script check that ScyllaDB is already installed; answer no to skip this check.
[YES/no]yes
Do you want to enable ScyllaDB services?
Answer yes to automatically start Scylla when the node boots; answer no to skip this step.
[YES/no]no
/usr/sbin/scylla_setup: line 259: uuidgen: command not found

**Comment by syuu1228** [comment]
It already fixed, the patch should available on Scylla 1.6.
Could you test it again on 1.6?

The commit is: https://github.com/scylladb/scylla/commit/3b74c50546bdcad366929d517ca2acd27547057f
