### ISSUE TITLE
repair does not respect shutdown

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2076]
*Installation details*
Scylla version (or git commit hash): afe98f85721813099857eb2b64efe57a8347e271
Cluster size: 3

Start repair on one node, shutdown on another -> shutdown does not complete.

**Comment by avikivity** [comment]
Tried to reproduce, but it worked this time.

**Comment by nyh** [comment]
We have a dtest for this case, repair_additional_test.py/repair_kill_2_test. It starts a repair from one master node, and then shuts down another node. The test confirms (or at least, is supposed to confirm) that we can shut down that slave node, and that the repair fails on the master node.

By the way, https://github.com/scylladb/scylla/issues/820 is about the very long timeout, 10 minutes, until the master realizes/decides that the repair fails.

**Comment by slivne** [comment]
closing this issue - we will add such tests in the longevity in SCT
