### ISSUE TITLE
Multiple metric families with same name in prometheus

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2077]
*Installation details*
Scylla version (or git commit hash): 1.6

According to the prometheus [protocol](https://prometheus.io/docs/instrumenting/exposition_formats/#protocol-buffer-format-details), each MetricFamily must have a unique name, but this is not respected.

**Comment by amnonh** [comment]
Or they can be combined together under the same name with different labels

**Comment by ddimanss** [comment]
Now i get this error 

curl http://10.239.182.188:9180/metrics | grep scylla_stall_detector_reported
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP scylla_stall_detector_reported Total number of reported stalls, look in the traces for the exact reason
# TYPE scylla_stall_detector_reported counter
scylla_stall_detector_reported{shard="0"} 0
scylla_stall_detector_reported{shard="0"} 0
scylla_stall_detector_reported{shard="0"} 0
scylla_stall_detector_reported{shard="0"} 0
scylla_stall_detector_reported{shard="0"} 0

scylladb commit 0de3a5f3ff4b060227a7150aa90546920bc54ce6

**Comment by amnonh** [comment]
@gleb-cloudius, I see a weird issue with the registration of the stall detector metrics. I can not reproduce it locally, but I saw it happened with Scylla running in a container.

The scenario works like this: each stall_detector should be created on its own shard. As part of its constructor, it registers a single metric, and the metric layer adds a ```shard``` label to each metric.

Registration is done independently on each shard, and the metric layer will not let you register a metric twice, but the validation is per-shard, so having one metric per shard is okay. So far, nothing new and works well.

In our case, all the metrics get shard id 0.

So the metrics are on different shards (or it wouldn't have worked), but when the metric layer added them and called ```this_shard_id()``` it got 0
