### ISSUE TITLE
Support Dynamic Snitching

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#208]
In origin:
"By default, all snitches also use a dynamic snitch layer that monitors read latency and, when possible, routes requests away from poorly-performing nodes. The dynamic snitch is enabled by default and is recommended for use in most deployments."

Without  dynamic snitch, a coordinator may read from different node, instead of going to its own local storage, resulting in extra hop, slow latency.

http://www.datastax.com/dev/blog/dynamic-snitching-in-cassandra-past-present-and-future

**Comment by tzach** [comment]
Dynamic Snitching explained (from Apple Inc.: Cassandra Internals — Understanding Gossip)
https://youtu.be/FuP1Fvrv6ZQ?t=27m40s

**Comment by slivne** [comment]
I think we already have that in kb as a reference

**Comment by tzach** [comment]
@slivne can we close this?

**Comment by slivne** [comment]
Not really ... we started implemnting it and stopped as we do not think
that what origin does makes sense - @glebcloudius can you provide more
details.

**Comment by avikivity** [comment]
Won't fix - Dynamic Snitch is regarded as broken in Cassandra, and Heat Weighted Load Balancing provides similar functionality.
