### ISSUE TITLE
sstable count and size on disk reported by nodetool are too large

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2082]
`column_family::stats::live_sstable_count` et al. are incremented when new sstable is added, but not decremented when sstable is removed (e.g. by compaction).

**Comment by raphaelsc** [comment]
On Tue, Feb 14, 2017 at 1:04 PM, Tomasz Grabiec <notifications@github.com>
wrote:

> column_family::stats::live_sstable_count et al. are incremented when new
> sstable is added, but not decremented when sstable is removed (e.g. by
> compaction).
>

live_sstable_count takes into account sstables that were compacted but not
deleted yet. After compacted sstables are actually deleted, we call
rebuild_statistics again (
https://github.com/scylladb/scylla/blob/master/database.cc#L1335) which
will decrease the stat. BTW, that's possibly telling us that deletion of
compacted sstables is taking longer than expected.

**Comment by tgrabiec** [comment]
@raphaelsc Right
