### ISSUE TITLE
metrics in storage_proxy uses the same name

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#2089]
Version 1.7
When migrating the storage_proxy metrics to the new metrics API, some of the metrics were register under the same "read" name, instead of read_digest, read_request etc'

See: storage_proxy::stats::stats

**Comment by gleb-cloudius** [comment]
On Thu, Feb 16, 2017 at 01:50:36AM -0800, Amnon Heiman wrote:
> Version 1.7
> When migrating the storage_proxy metrics to the new metrics API, some of the metrics were register under the same "read" name, instead of read_digest, read_request etc'
> 
> See: storage_proxy::stats::stats
> 
That's by purpose. The type of read is in a label.

--
			Gleb.
