### ISSUE TITLE
nodetool status: "grep: /tmp/tmp.l220rPJTgI/jvm.options: No such file or directory"

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla#2096]
*Installation details*
Scylla version (or git commit hash):  1.7.rc0-0.20170207.0429e5d
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

*Description*

I login one db node of [longevity-gce-1.7 job](http://jenkins.cloudius-systems.com/job/scylla-1.7-longevity-gce/label=gce/4/console), and execute `nodetool status`, but there is an error hint in the head of output.

```
[scylla-test@longevity-1-7-gce-scylla-db-node-d9ea4a62-003 ~]$ nodetool status
grep: /tmp/tmp.bPXEfvMQdt/jvm.options: No such file or directory
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens       Owns    Host ID                               Rack
UN  10.240.0.17  3.97 GB    256          ?       e3e0dbc4-83cd-4b89-9379-a16b1264f677  rack1
UN  10.240.0.3   4.19 GB    256          ?       5d2a7674-9510-42bd-a4b8-611aa8dc4774  rack1
UN  10.240.0.36  4.72 GB    256          ?       b44270a1-e05f-4b48-aaf5-a08a1ac12e28  rack1
UN  10.240.0.29  4.13 GB    256          ?       27bf8660-3fa7-4cfd-a506-6fae97b8ef46  rack1
UN  10.240.0.30  4.37 GB    256          ?       792fdf87-3bb0-4489-8448-92432cb27065  rack1
UN  10.240.0.14  4.95 GB    256          ?       1d0b0093-d48a-427b-8ee0-c883bc7c9338  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

**Comment by syuu1228** [comment]
Looks like /tmp/tmp.bPXEfvMQdt is $TMPCONF:
https://github.com/scylladb/scylla-tools-java/blob/1a55ef35120413341dafb92049c4007494833a11/dist/common/cassandra.in.sh#L12
and you can find "grep $TMPCONF/jvm.options" on following code:
https://github.com/scylladb/scylla-tools-java/blob/98725449500895e1d1dc00c2d6889503a3252a89/conf/cassandra-env.sh#L130

Not sure why did it fail.. It just works for my Ubuntu 16.04 environment.
You can retry with:
```
sh -x `which nodetool` status
```
to see what's going on inside.

I feel the script doing weird things, but it directly delivered from upstream...

**Comment by slivne** [comment]
I think its comming from the fact that we update CASSANDRA_CONF to a temp
directory for tool execution

https://github.com/scylladb/scylla-tools-java/blob/master/dist/common/cassandra.in.sh

We copy all the cassandra.conf to that dirctory

https://github.com/scylladb/scylla-tools-java/blob/master/dist/common/cassandra.in.sh#L22

Yet it seems they have added a default jvm.options file to the conf diretory

https://github.com/scylladb/scylla-tools-java/blob/master/conf/jvm.options

and we are not copying it like logback.xml etc. to /etc/scylla/cassandra

https://github.com/scylladb/scylla-tools-java/blob/02dc5cc65ff91310d813b9455aa415bfaad2d1bf/dist/debian/debian/scylla-tools.install
https://github.com/scylladb/scylla-tools-java/blob/master/dist/redhat/scylla-tools.spec.in

So the solution should be to update the rpms and copy the jvm.options file
to /etc/scylla/cassandra like we do with the logback.xml and the other
files.

**Comment by syuu1228** [comment]
Ah okay, dist/* is inconsistent with rebased version of scylla-tools.
Will send a fix

2017年2月21日(火) 午後6:39 Shlomi Livne <notifications@github.com>:

**Comment by tzach** [comment]
@penberg I still see this issue in docker nightly

**Comment by penberg** [comment]
@tzach Our nighly build is probably broken then.
