### ISSUE TITLE
multiple data directory 

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2100]
Cassandra can use multiple directory 

data_file_directories:
- /data1/cass
- /data2/cass
- /data3/cass

this configuration don't work in scylla
if disk is full,  what should I do in RAID0 ?

**Comment by tzach** [comment]
This feature is called JBOD, on Scylla road map but not available yet #830 
The way to do so in Scylla is to use RAID0 on all three directories, as you suggested.

**Comment by infordb** [comment]
@tzach thank you I hope that the JBOT function will be applied soon.

**Comment by tzach** [comment]
Closing this issue as it duplicate #830
