### ISSUE TITLE
monitor: `Load per server` reaches to 100 after c-s client exited

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla#2102]
*Installation details*
Scylla version (or git commit hash): 1.7-rc0
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

* Description *

c-s client exited unexpectedly after longevity-test job run 9 hours. but the `Load per server` reaches to `100`, not `0`.

I met same problem (c-s exit), but the monitor displayed `0` `Load per server`.

![fireshot capture 108 - grafana - scylla per server metrics m_ - http___104 196 57 145_3000_dashboa](https://cloud.githubusercontent.com/assets/309708/23188083/fa78ec76-f852-11e6-9677-5feec4bdfdfd.png)

**Comment by kongove** [comment]
http://104.196.57.145:3000/dashboard/db/scylla-per-server-metrics-master?from=1487668182668&to=now

It's live.

**Comment by glommer** [comment]
Amos,

if you log into the node and check Linux cpu usage, what do you see ?

**Comment by tzach** [comment]
@kongove when Prometheus does not get metric, it uses the last data point for 5m. Could it be the case?

**Comment by amnonh** [comment]
Could that be duplication of:
https://github.com/scylladb/seastar/issues/248
And
https://github.com/scylladb/scylla-grafana-monitoring/issues/110

**Comment by kongove** [comment]
@glommer 

cpu usage of db node : about 1.3%
cpu usage of loader : about 0.1%
cpu usage of monitor: about 1.5% in idle, increase to 25% when I open grafana page in browser

**Comment by tgrabiec** [comment]
@kongove  Because of scylladb/seastar#248, 100% load means actually idle, so nothing suspicious here.
