### ISSUE TITLE
IndexOutOFBoundException while running sstableloader

### ISSUE THREAD

**Issue by mj-jadhav** [scylladb/scylla#2107]
*Installation details*
Scylla version (or git commit hash): 1.6.0
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS Ubuntu 14.04

Tried to run bulkload to load data from CSV using following project https://github.com/yukim/cassandra-bulkload-example/ but getting this error:
`java.lang.IndexOutOfBoundsException at java.nio.Buffer.checkIndex(Buffer.java:538) at java.nio.HeapByteBuffer.getLong(HeapByteBuffer.java:410) at org.apache.cassandra.utils.ByteBufferUtil.toLong(ByteBufferUtil.java:377) at org.apache.cassandra.serializers.TimestampSerializer.deserialize(TimestampSerializer.java:78) at org.apache.cassandra.serializers.TimestampSerializer.deserialize(TimestampSerializer.java:30) at org.apache.cassandra.db.marshal.AbstractType.compose(AbstractType.java:68) at com.scylladb.tools.SSTableToCQL$RowBuilder.addWhere(SSTableToCQL.java:239) at com.scylladb.tools.SSTableToCQL$RowBuilder.updateColumn(SSTableToCQL.java:537) at com.scylladb.tools.SSTableToCQL$RowBuilder.process(SSTableToCQL.java:456) at com.scylladb.tools.SSTableToCQL$RowBuilder.process(SSTableToCQL.java:484) at com.scylladb.tools.SSTableToCQL$RowBuilder.access$400(SSTableToCQL.java:108) at com.scylladb.tools.SSTableToCQL.process(SSTableToCQL.java:660) at com.scylladb.tools.SSTableToCQL.stream(SSTableToCQL.java:693) at com.scylladb.tools.BulkLoader.main(BulkLoader.java:586)`

**Comment by slivne** [comment]
the tool uses the internal protocol of cassandra and does not use cql/thrift protocol to insert the information. 
scylla is not compatible with cassandra in the internal protocol - as such the tool does not work.

possible alternatives are tools that use CQL to load CSV files
or use a tool that converts CSV to SSTABLE and then use scylla's sstableloader to load the information (or sstable refresh for a single node case).
