### ISSUE TITLE
Prometheus instance (host) should be set from the configuration

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#2110]
When running multiple instances locally, it is useful to be able to set the prometheus instance (host) from the configuration.

**Comment by tzach** [comment]
@amnonh, are you referring to Scylla config
 how can you do that? Prometheus is pulling from Scylla, not the other way around

**Comment by amnonh** [comment]
Promtheus uses an 'instance' label that typically mapped to the hostname,
sometimes you need to set that label yourself (running multiple instances
on the same host for example)

**Comment by slivne** [comment]
We have a --collectd-hostname, we can add a parallel one for prometheus

We do not allow changing any other prometheus  or collectd from the config
AFAIK
I don't think this is any different - we should either allow all or none
from the config.

**Comment by amnonh** [comment]
On Sun, Feb 26, 2017 at 10:38 AM, Shlomi Livne <notifications@github.com>
wrote:

> We have a --collectd-hostname, we can add a parallel one for prometheus
>
> We do not allow changing any other prometheus or collectd from the config
> AFAIK
>
See: [PATCH scylla] Add prometheus-host to the configuration

**Comment by tzach** [comment]
@amnonh FYI you can update the labels from prometheus itself

**Comment by amnonh** [comment]
On Sun, Feb 26, 2017 at 11:08 AM, Tzach Livyatan <notifications@github.com>
wrote:

> @amnonh <https://github.com/amnonh> FYI you can update the labels from
> prometheus itself
>
You missed the problem,
if you running two instances on the same host, without changing the
instance label, both scylla would use the host name and the metrics will
look the same to the prometheus serve

**Comment by tzach** [comment]
I think you can update labels base on IP by Prometheus, but it does not say your solution is not better.
