### ISSUE TITLE
Posix net script fails on Amazon EC2 i3.16xlarge boxes

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#2111]
```
[centos@ip-172-30-0-100 ~]$ sudo /usr/lib/scylla/posix_net_conf.sh eth0
Setting a physical interface eth0...
cat: /sys/class/net/eth0/device/irq: No such file or directory
cat: /sys/class/net/eth0/device/irq: No such file or directory
Setting mask fffffffe,fffffffe in /sys/class/net/eth0/queues/rx-0/rps_cpus
Setting mask ffffffff,ffffffff in /sys/class/net/eth0/queues/tx-0/xps_cpus
```

In general, this NIC is probably different than the others we have seen so far (20Gbps to begin with). The driver is being reported as
```
[centos@ip-172-30-0-100 ~]$ ethtool -i eth0
driver: vif
```

which means AFAIU SR-IOV is not being used.

**Comment by vladzcloudius** [comment]
@glommer This is not an SR-IOV device.

**Comment by vladzcloudius** [comment]
I tried to reproduce the issue and it doesn't reproduce. The strangest thing is that I **was** able to reproduce it when the issue was opened...

@slivne @glommer Guys has anything changed in the 1.6.1 AMI since then? The corresponding lines in the script remained the same...

**Comment by slivne** [comment]
@glommer provided them a custom made AMI - so maybe there is a different
version on their AMI

w

**Comment by glommer** [comment]
On Wed, Mar 1, 2017 at 10:05 AM, Shlomi Livne <notifications@github.com>
wrote:

> well you did provide them a custom made rpm ...
>
> I didn't initially. I did later to fix bugs they encountered - and are
documented in the enterprise issue tracker.

All bugs were seastar reactor issues, none having much to do with the
network script.

On Wed, Mar 1, 2017 at 5:04 PM, Glauber Costa <notifications@github.com>

**Comment by slivne** [comment]
can you point vlad to the repo so he can double check he is not looking at
a different version

**Comment by glommer** [comment]
On Wed, Mar 1, 2017 at 10:17 AM, Shlomi Livne <notifications@github.com>
wrote:

> can you point vlad to the repo so he can double check he is not looking at
> a different version
>

Vlad has never run their RPM. When he said he reproduced the bug himself,
that was on the standard 1.6.1 AMI.

In any case, the RPM they are running sits at

git@github.com:glommer/scylla-enterprise.git branch-1.6-mparticle.

**Comment by vladzcloudius** [comment]
@slivne @glommer Guys, I was using the 1.6.1 AMI from the community repository - not something custom-made by Glauber. 

The only option I see is that the AMI was updated (it sounds like it wasn't). So, frankly, I'm out of ideas.
Glauber, could you double check and close the issue if it doesn't reproduce to you as well?

**Comment by vladzcloudius** [comment]
On 03/01/2017 10:20 AM, Glauber Costa wrote:
> On Wed, Mar 1, 2017 at 10:17 AM, Shlomi Livne <notifications@github.com>
> wrote:
>
> > can you point vlad to the repo so he can double check he is not 
> looking at
> > a different version
> >
>
> Vlad has never run their RPM. When he said he reproduced the bug himself,
> that was on the standard 1.6.1 AMI.

Exactly. So, I was and am talking about the public (standard) 1.6.1 AMI.

**Comment by glommer** [comment]
On Wed, Mar 1, 2017 at 11:53 AM, vladzcloudius <notifications@github.com>
wrote:

> @slivne <https://github.com/slivne> @glommer <https://github.com/glommer>
> Guys, I was using the 1.6.1 AMI from the community repository - not
> something custom-made by Glauber.
>
> The only option I see is that the AMI was updated (it sounds like it
> wasn't). So, frankly, I'm out of ideas.
> Glauber, could you double check and close the issue if it doesn't
> reproduce to you as well?
>

Is the hardware still the same?

Maybe EC2 changed the i3 hardware.

**Comment by vladzcloudius** [comment]
I thought about that too but it seemed too unlikely.
However even if they did our behaviour should be the same - if the issue is not reproducible the ticket should be closed.

Note that the root-cause was super weird to begin with: `test -e /sys/class/net/eth0/device/irq` was returning `true` while the file didn't exist. `[ -f  /sys/class/net/eth0/device/irq ]` was working as expected. I don't remember if I tried `[ -e  /sys/class/net/eth0/device/irq ]`. 

So, theoretically, Amazon could have fixed some bug that caused `-e` not to work as expected.

**Comment by glommer** [comment]
I think we can close this regardless.
This behavior was seen with vif, and not with ENA when later on we managed to test ENA.

Our AMI will eventually enable ENA when we figure out what to do with the kernel.
