### ISSUE TITLE
show CPU usage statistics in collectd

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#2115]
Our collectd.conf file does not enable the CPU plugin. The CPU plugin is needed for us to have visibility of CPU usage in the node from the OS point of view. In particular, iowait is an incredibly important metric in the field.

**Comment by slivne** [comment]
We are recommending user to move to node_exporter base on prometheus - it
is setup via scylla_setup - why are you sing collectd ? is anything missing
from node_exporter ?

**Comment by glommer** [comment]
That is indeed for the node metrics, and has nothing to do with scylla
exporting its metrics via prometheus or collectd.

In the Scylla AMI the CPU information is present, because the cpu plugin is
turned on in the main collectd.conf (so is disk, but we put it on anyway),
but I have recently tried to debug customer data where this wasn't.

I was assuming node exporter gets this information from collectd. Wouldn't
that be the case?

**Comment by amnonh** [comment]
On Sun, Feb 26, 2017 at 4:36 PM, Glauber Costa <notifications@github.com>
wrote:

> That is indeed for the node metrics, and has nothing to do with scylla
> exporting its metrics via prometheus or collectd.
>
> In the Scylla AMI the CPU information is present, because the cpu plugin is
> turned on in the main collectd.conf (so is disk, but we put it on anyway),
> but I have recently tried to debug customer data where this wasn't.
>
> I was assuming node exporter gets this information from collectd. Wouldn't
> that be the case?
>
Not realy,
node_exporter is running without collectd, it has its own set of metrics.
See: https://github.com/prometheus/node_exporter for reference

**Comment by glommer** [comment]
I did not know that. If we're really deprecating collectd (even slowly), then I'll close this.

**Comment by tzach** [comment]
We should not deprecate collectd until:
- scyllatop will work without it
- there will be a different way to export collectd format metrics. Not all users want to use Prometheus

**Comment by amnonh** [comment]
We're not deprecating it and has no plan of doing it, only the dashboards
are aligned with Prometheus.
