### ISSUE TITLE
cannot update counters after sstable migration

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#2119]
*Installation details*
Scylla version (or git commit hash):
1.7.rc0
Cluster size:
1 node
OS (RHEL/CentOS/Ubuntu/AWS AMI):
CentOS

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

test PR and comments:
https://github.com/scylladb/scylla-dtest/pull/455/

After migration can read counters data, but cannot update:
File "cassandra/cluster.py", line 3781, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:73073)
    raise self._final_exception
ServerError: <Error from server: code=0000 [Server error] message="timedout">

**Comment by roydahan** [comment]
@tzach, need to include in 1.7 release notes that we do not support counters migration in 1.7

**Comment by tzach** [comment]
@pdziepak is it a missing feature or bug?

**Comment by pdziepak** [comment]
It is a general bug (i.e. can happen to any counter write, migration is irrelevant here) that is fixed in my "Improvements to counter implementation" series.

**Comment by tzach** [comment]
Thanks @larisau @pdziepak good pointer for the release notes.

**Comment by pdziepak** [comment]
Fixed by 25173f8095564162eb4d578c640d67c9b70fd741 in master and b6db9e3d513a6ac1910d52d6c7a4157dfc26dae7 in 1.7.

**Comment by roydahan** [comment]
@larisau, can you please remove the "require" for your test and test it with 1.7?
