### ISSUE TITLE
cql language for the internode rpc protocol

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2120]
Currently we have a lot of overhead for the internode protocol because every message describes the query in detail -- needed columns, column family, keyspace.  We could use regular prepared statements to query or update replicas instead, relying on the remote node to remember which columns we are interested in, and possibly to optimize the query ahead of time.  This would work for mutation queries and digests as well.

**Comment by gleb-cloudius** [comment]
On Tue, Feb 28, 2017 at 12:07:01AM -0800, Avi Kivity wrote:
> Currently we have a lot of overhead for the internode protocol because every message describes the query in detail -- needed columns, column family, keyspace.  We could use regular prepared statements to query or update replicas instead, relying on the remote node to remember which columns we are interested in, and possibly to optimize the query ahead of time.  This would work for mutation queries and digests as well.
> 
How is this different from #2041? Why regular prepare statement will be
more effective than regular RPC message?

--
			Gleb.

**Comment by avikivity** [comment]
It's a way of implementing it.  When posting #2041 I didn't think of actually using the regular prepared statement mechanism.

I do want to use RPC (and not the cql binary protocol).
