### ISSUE TITLE
I/O error with master on fedora25 ext4

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#2123]
*Installation details*
Scylla version (or git commit hash): c0e59644626817633fed9936cebc56999f33111f
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI):Fedora 25 server

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets= cores= hyperthreading= memory= 16 ht lcore
Disks: (SSD/HDD, count) 128 GB ext4

when launching with --developer-mode=1 I get

INFO  2017-03-01 13:02:55,135 [shard 9] database - Setting compaction strategy of system_traces.node_slow_log to SizeTieredCompactionStrategy
INFO  2017-03-01 13:02:55,135 [shard 8] database - Setting compaction strategy of system_traces.node_slow_log to SizeTieredCompactionStrategy
INFO  2017-03-01 13:02:55,228 [shard 10] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-90-Data.db:level=0, ]. 752 bytes to 188 (~25% of original) in 99ms = 0.00181102MB/s. ~1024 total partitions merged to 1.
WARN  2017-03-01 13:02:55,296 [shard 0] storage_service - Shutting down communications due to I/O errors until operator intervention
INFO  2017-03-01 13:02:55,296 [shard 0] storage_service - Stop transport: starts
INFO  2017-03-01 13:02:55,296 [shard 0] gossip - My status = 
INFO  2017-03-01 13:02:55,296 [shard 0] gossip - Announcing shutdown
WARN  2017-03-01 13:02:55,296 [shard 0] gossip - Fail to apply application_state: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_lexical_cast> > (bad lexical cast: source type value could not be interpreted as target)
WARN  2017-03-01 13:02:55,297 [shard 0] seastar - Exceptional future ignored: storage_io_error (Storage I/O error: 22: Invalid argument), backtrace: 0x493ce3, 0x493d41, 0x4f9a4a, 0xa9b12b, 0xa9b1a8, 0xa97048, 0x4908a3, 0x4de612, 0x55e7fe, 0x421477, 0x7f4dd7a4d400, 0x48c9d9
INFO  2017-03-01 13:02:55,468 [shard 0] database - Schema version changed to ee4b23bd-10ce-3727-a543-83ad118acac7
INFO  2017-03-01 13:02:55,627 [shard 5] compaction - Compacting [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-37-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-53-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-21-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-69-Data.db:level=0, ]
INFO  2017-03-01 13:02:55,630 [shard 0] storage_service - Node 127.0.0.1 state jump to normal

**Comment by benoit-canet** [comment]
reproduced on fresh GCE ubuntu 16.04 with ext4 /:

INFO  2017-03-01 12:14:24,440 [shard 18] database - Setting compaction strategy of system_traces.node_slow_log t
o SizeTieredCompactionStrategy
INFO  2017-03-01 12:14:24,453 [shard 30] database - Setting compaction strategy of system_traces.node_slow_log t
o SizeTieredCompactionStrategy
INFO  2017-03-01 12:14:24,542 [shard 20] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/schem
a_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-180-Data.db:level=0, ]. 752 bytes to 188
 (~25% of original) in 131ms = 0.00136863MB/s. ~1024 total partitions merged to 1.
WARN  2017-03-01 12:14:24,591 [shard 0] storage_service - Shutting down communications due to I/O errors until o
perator intervention
INFO  2017-03-01 12:14:24,592 [shard 0] storage_service - Stop transport: starts
INFO  2017-03-01 12:14:24,592 [shard 0] gossip - My status = 
INFO  2017-03-01 12:14:24,593 [shard 0] gossip - Announcing shutdown
WARN  2017-03-01 12:14:24,594 [shard 0] gossip - Fail to apply application_state: boost::exception_detail::clone
_impl<boost::exception_detail::error_info_injector<boost::bad_lexical_cast> > (bad lexical cast: source type val
ue could not be interpreted as target)
WARN  2017-03-01 12:14:24,604 [shard 0] seastar - Exceptional future ignored: storage_io_error (Storage I/O erro
r: 22: Invalid argument), backtrace: 0x4ec543, 0x4ec5c1, 0x555c9a, 0xc2c57b, 0xc2c5f8, 0xc28d78, 0x4e9047, 0x53a
3ca, 0x5bee8f, 0x4769b3, 0x7f502028082f, 0x4e4be8
INFO  2017-03-01 12:14:25,515 [shard 0] database - Schema version changed to d72534c0-713a-38b6-910c-cf57b2b84be
d

**Comment by avikivity** [comment]
strace will provide more information.

**Comment by benoit-canet** [comment]
This occurs only when /var/lib/scylla is ext4.

**Comment by benoit-canet** [comment]
We got an interrupted io_submit just before.

**Comment by benoit-canet** [comment]
io_submit(0x7fc288035000, 4, [{data=0x60000339fe80, pread, fildes=107, buf=0x6000004c1000, nbytes=8192, offset=101}, {data=0x600000d76c40, pread, fildes=110, buf=0x6000004bf000, nbytes=8192, offset=101}, {data=0x600000d76440, pread, fildes=108, buf=0x6000004bd000, nbytes=8192, offset=101}, {data=0x6000033b7a00, pread, fildes=109, buf=0x6000004bb000, nbytes=8192, offset=101}]) = 4
tgkill(3013, 3014, SIGRT_2)             = 0
tgkill(3013, 3015, SIGRT_2)             = 0
tgkill(3013, 3016, SIGRT_2)             = 0
tgkill(3013, 3017, SIGRT_2)             = 0
tgkill(3013, 3018, SIGRT_2)             = 0
tgkill(3013, 3019, SIGRT_2)             = 0
tgkill(3013, 3020, SIGRT_2)             = 0
tgkill(3013, 3021, SIGRT_2)             = 0
tgkill(3013, 3024, SIGRT_2)             = 0
tgkill(3013, 3025, SIGRT_2)             = 0
tgkill(3013, 3028, SIGRT_2)             = 0
tgkill(3013, 3029, SIGRT_2)             = 0
tgkill(3013, 3032, SIGRT_2)             = 0
tgkill(3013, 3033, SIGRT_2)             = 0
tgkill(3013, 3039, SIGRT_2)             = 0
epoll_pwait(23, [], 128, 0, NULL, 8)    = 0
io_getevents(0x7fc288035000, 1, 128, [{data=0x60000339fe80, obj=0x600000d75600, res=-22, res2=0}, {data=0x600000d76c40, obj=0x600000d75640, res=-22, res2=0}, {data=0x600000d76440, obj=0x600000d75680, res=-22, res2=0}, {data=0x6000033b7a00, obj=0x600000d756c0, res=-22, res2=0}], {tv_sec=0, tv_nsec=0}) = 4
tgkill(3013, 3015, SIGRT_2)             = 0
tgkill(3013, 3029, SIGRT_2)             = 0
epoll_pwait(23, [], 128, 0, NULL, 8)    = 0
stat("/etc/localtime", {st_mode=S_IFREG|0644, st_size=2971, ...}) = 0
write(1, "WARN  2017-03-01 14:05:26,079 [s"..., 133WARN  2017-03-01 14:05:26,079 [shard 0] storage_service - Shutting down communications due to I/O errors until operator intervention
) = 133


so io_getevent got -EINVAL

**Comment by benoit-canet** [comment]
I will dig in the kernel source to see why it could return -EINVAL.

**Comment by avikivity** [comment]
`offset = 101` is illegal, `offset` should be aligned on a 512 byte boundary.

**Comment by avikivity** [comment]
I am guessing there was a 101 byte file.  The code tried to read all of it, it got 101 bytes (short read before eof).  Then it read more, expecting 0, but got EINVAL.  On xfs it works.

We could fix it by replacing short read handling with `lseek(..., SEEK_END)`.  If the result matches the last offset+len, we hit eof.  If not, we hit an I/O error and need to continue the read from offset+len.

**Comment by avikivity** [comment]
btw, it works on my ext4 laptop, so something is wrong.

**Comment by benoit-canet** [comment]
What is it running ?

I tested Fedora 25 and Ubuntu 16.04.

**Comment by avikivity** [comment]
Fedora 25.

Do you have 101-byte files there?

**Comment by benoit-canet** [comment]
[root@localhost ~]# find /var/lib/scylla/ -size 101
[root@localhost ~]#

**Comment by avikivity** [comment]
then look for more clues in strace

**Comment by benoit-canet** [comment]
io_getevents(0x7fc288035000, 1, 128, [{data=0x600000d468c0, obj=0x600000d75600, res=101, res2=0}, {data=0x600000d76780, obj=0x600000d756c0, res=101, res2=0}, {data=0x6000033b7a40, obj=0x600000d75640, res=101, res2=0}, {data=0x6000033b7f80, obj=0x600000d75680, res=101, res2=0}], {tv_sec=0, tv_nsec=0}) = 4
tgkill(3013, 3029, SIGRT_2)             = 0
epoll_pwait(23, [], 128, 0, NULL, 8)    = 0
io_submit(0x7fc288035000, 4, [{data=0x60000339fe80, pread, fildes=107, buf=0x6000004c1000, nbytes=8192, offset=101}, {data=0x600000d76c40, pread, fildes=110, buf=0x6000004bf000, nbytes=8192, offset=101}, {data=0x600000d76440, pread, fildes=108, buf=0x6000004bd000, nbytes=8192, offset=101}, {data=0x6000033b7a00, pread, fildes=109, buf=0x6000004bb000, nbytes=8192, offset=101}]) = 4

res=101, res2=0}, short read

**Comment by avikivity** [comment]
well, try to find out what that file is.

**Comment by benoit-canet** [comment]
[root@localhost scylla]# ls -l /var/lib/scylla/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-74-TOC.txt.tmp
-rw-r--r--. 1 root root 101  1 mars  15:08 /var/lib/scylla/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-74-TOC.txt.tmp

**Comment by benoit-canet** [comment]
[root@localhost scylla]# cat /var/lib/scylla/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-74-TOC.txt.tmp
CompressionInfo.db
Filter.db
Data.db
Summary.db
TOC.txt
Statistics.db
Digest.sha1
Scylla.db
Index.db

**Comment by avikivity** [comment]
So its size is 101, no?

**Comment by benoit-canet** [comment]
It look pretty fucked up that something openned in O_DIRECT does a short
101 bytes read.

2017-03-01 15:18 GMT+01:00 Avi Kivity <notifications@github.com>:

**Comment by benoit-canet** [comment]
I'll implement your suggestion.

2017-03-01 15:23 GMT+01:00 Benoît Canet <benoit@scylladb.com>:

**Comment by amnonh** [comment]
for the record, I'm facing the same problem on my laptop with fedora 25
running master scylla with master seastar,
I suspect something in the last changes in seastar

**Comment by raphaelsc** [comment]
On Wed, Mar 1, 2017 at 11:25 AM, Raphael S. Carvalho <raphaelsc@scylladb.com
> wrote:

>
>
> On Wed, Mar 1, 2017 at 11:23 AM, Benoît Canet <notifications@github.com>
> wrote:
>
>> It look pretty fucked up that something openned in O_DIRECT does a short
>> 101 bytes read.
>>
>
> It seems a regression to me. sstable_test fails with lots of
> std::exception: Storage I/O error: 22: Invalid argument
>


Possibly either of:

**Comment by raphaelsc** [comment]
On Wed, Mar 1, 2017 at 11:25 AM, Raphael S. Carvalho <raphaelsc@scylladb.com
> wrote:

>
>
> On Wed, Mar 1, 2017 at 11:25 AM, Raphael S. Carvalho <
> raphaelsc@scylladb.com> wrote:
>
>>
>>
>> On Wed, Mar 1, 2017 at 11:23 AM, Benoît Canet <notifications@github.com>
>> wrote:
>>
>>> It look pretty fucked up that something openned in O_DIRECT does a short
>>> 101 bytes read.
>>>
>>
>> It seems a regression to me. sstable_test fails with lots of
>> std::exception: Storage I/O error: 22: Invalid argument
>>
>
>
> Possibly either of:
>       > core/file: Fix short-read in read_maybe_eof()
>       > core/fstream: Avoid issuing read requests beyond _remain
>


We possibly messed up with the alignment here:

-            auto end = align_up(std::min(start + _current_buffer_size,
_pos + _remain), align);
+            auto end = std::min(align_up(start + _current_buffer_size,
align), _pos + _remain);

We probably should align up (_pos + _remain) too.

**Comment by avikivity** [comment]
The code should have worked, let's find out first why it doesn't/

**Comment by raphaelsc** [comment]
On Wed, Mar 1, 2017 at 11:32 AM, Avi Kivity <notifications@github.com>
wrote:

> The code should have worked, let's find out first why it doesn't/
>

Turns out I was wrong about that specific change. We need to find out which
Seastar patch introduced the bug.

**Comment by benoit-canet** [comment]
I just upgraded my f25 this morning including new kernel before seeing this.

2017-03-01 15:35 GMT+01:00 Benoît Canet <benoit@scylladb.com>:

**Comment by benoit-canet** [comment]
trying old kernel

2017-03-01 15:37 GMT+01:00 Benoît Canet <benoit@scylladb.com>:

**Comment by benoit-canet** [comment]
no difference.

2017-03-01 15:41 GMT+01:00 Benoît Canet <benoit@scylladb.com>:

**Comment by raphaelsc** [comment]
On Wed, Mar 1, 2017 at 11:41 AM, Benoît Canet <notifications@github.com>
wrote:

> trying old kernel



Actually, I think it's not kernel related because I haven't upgraded my
kernel for a while and I also bumped into the same issue after I pulled
master.

**Comment by raphaelsc** [comment]
On Wed, Mar 1, 2017 at 11:44 AM, Raphael S. Carvalho <raphaelsc@scylladb.com
> wrote:

>
>
> On Wed, Mar 1, 2017 at 11:41 AM, Benoît Canet <notifications@github.com>
> wrote:
>
>> trying old kernel
>
>
>
> Actually, I think it's not kernel related because I haven't upgraded my
> kernel for a while and I also bumped into the same issue after I pulled
> master.
>

Patch was sent to seastar mailing list to fix it,
'core/file: properly determine EOF for file with custom impl'

The problem was exposed by 'core/file: Fix short-read in read_maybe_eof()'.
It's basically that read_maybe_eof() was relying on exception to signal
EOF, and that doesn't go well with checked_file_impl which catches
exception first and wraps it in storage_io_error, and it also asks system
for shutdown.

**Comment by slivne** [comment]
@raphaelsc can we close this ?

**Comment by raphaelsc** [comment]
On Thu, Mar 30, 2017 at 9:06 AM, Shlomi Livne <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> can we close this ?
>
I think so.
