### ISSUE TITLE
Many bad_alloc

### ISSUE THREAD

**Issue by andrewrong** [scylladb/scylla#2125]
*Installation details*
Scylla version (or git commit hash): 1.6
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos 7 

*Hardware details (for performance issues)*         
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets= cores=40 hyperthreading= memory= 64g
Disks: (SSD/HDD, count) raid5 hdd 64T

<img width="867" alt="bad_alloc" src="https://cloud.githubusercontent.com/assets/1272833/23494763/a9333b1a-ff4f-11e6-8a4d-3933b1b4a247.png">

My `/etc/sysconfig/scylla-server` is

```
# choose following mode: virtio, dpdk, posix
NETWORK_MODE=posix

# tap device name(virtio)
TAP=tap0

# bridge device name (virtio)
BRIDGE=virbr0

# ethernet device name
IFNAME=eth0

# setup NIC's interrupts, RPS, XPS (posix)
SET_NIC=no

# ethernet device driver (dpdk)
ETHDRV=

# ethernet device PCI ID (dpdk)
ETHPCIID=

# number of hugepages
NR_HUGEPAGES=64

# user for process (must be root for dpdk)
USER=scylla

# group for process
GROUP=scylla

# scylla home dir
SCYLLA_HOME=/var/lib/scylla

# scylla config dir
SCYLLA_CONF=/etc/scylla

# scylla arguments (for posix mode)
SCYLLA_ARGS="--smp 20 -m50G --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix"

## scylla arguments (for dpdk mode)
#SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack native --dpdk-pmd"

# setup as AMI instance
AMI=no
```

The problem about this bad_alloc was found when the scylladb run 10~15 days; So I change the `/etc/sysconfig/scylla-server`(`--smp 20 to --smp 5`）, so this change persisted for about a month， but the scylladb have stopped and  reboot is failure;

I have answered similar problem(https://github.com/scylladb/scylla/issues/1925 and https://github.com/scylladb/scylla/issues/1944), but I find that this problem is different, the size of  `CompressionInfo.db` is not large;

My table:

```
CREATE TABLE mogulog.originlog (
    uuid text PRIMARY KEY,
    content text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'chunk_length_kb': '64', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

This table is so simple, this is similar of k-v store;

the result of `nodetool cfstat xx.xxx`, this maybe uncorrected, because I have reboot it and the smp change `--smp 2 -m50G`

```
Keyspace: mogulog
	Read Count: 0
	Read Latency: NaN ms.
	Write Count: 50128777
	Write Latency: 1.0786977707435391E-5 ms.
	Pending Flushes: 0
		Table: originlog
		SSTable count: 133
		SSTables in each level: [106/4]
		Space used (live): 2666041899572
		Space used (total): 2670498730204
		Space used by snapshots (total): 215179956
		Off heap memory used (total): 3058390136
		SSTable Compression Ratio: 0.47262
		Number of keys (estimate): 14534345337
		Memtable cell count: 2050791
		Memtable data size: 2542202355
		Memtable off heap memory used: 2863398912
		Memtable switch count: 2
		Local read count: 0
		Local read latency: NaN ms
		Local write count: 50211456
		Local write latency: 0.000 ms
		Pending flushes: 0
		Bloom filter false positives: 0
		Bloom filter false ratio: 0.00000
		Bloom filter space used: 127262096
		Bloom filter off heap memory used: 130023448
		Index summary off heap memory used: 64967776
		Compression metadata off heap memory used: 0
		Compacted partition minimum bytes: 73
		Compacted partition maximum bytes: 545791
		Compacted partition mean bytes: 362
		Average live cells per slice (last five minutes): 0.0
		Maximum live cells per slice (last five minutes): 0.0
		Average tombstones per slice (last five minutes): 0.0
		Maximum tombstones per slice (last five minutes): 0.0

----------------
```

I hope that you help me， I have used in production with the Scylladb

**Comment by andrewrong** [comment]
@avikivity

**Comment by avikivity** [comment]
@andrewrong do you have monitoring installed?  It will help see where the problem is.

Please run this command in the data directory and report the results.  How much memory do you have per server?


    find -type f -printf '%f %s\n' | awk '{ n = split($1, a, "-"); comp[a[n]] += $2 } END { for (c in comp) print comp[c], c }'  | sort -nr

**Comment by avikivity** [comment]
Oh, I see you have 64GB.

**Comment by andrewrong** [comment]
@avikivity 

Node 1
```
2275138517639 Data.db
716291423220 Index.db
20340008224 Filter.db
4727956384 Summary.db
503958450 CompressionInfo.db
657260 Statistics.db
11042 TOC.txt
7120 CRC.db
1786 manifest.json
1186 Digest.sha1
912 Scylla.db
707 TOC.txt.tmp
```

Node 2
```
438474091225 Data.db
174689865932 Index.db
10390808464 Filter.db
1309931736 Summary.db
111095524 CompressionInfo.db
401034 Statistics.db
6735 TOC.txt
6508 CRC.db
1786 manifest.json
798 Scylla.db
729 Digest.sha1
202 TOC.txt.tmp
```

Node3
```
1892817847959 Data.db
622686969736 Index.db
16328642016 Filter.db
4154774688 Summary.db
434457326 CompressionInfo.db
742208 Statistics.db
13244 TOC.txt
6624 CRC.db
1786 manifest.json
1672 Scylla.db
1403 Digest.sha1
101 TOC.txt.tmp
```

Now `/etc/sysconfig/scylla-server`

```
# choose following mode: virtio, dpdk, posix
NETWORK_MODE=posix

# tap device name(virtio)
TAP=tap0

# bridge device name (virtio)
BRIDGE=virbr0

# ethernet device name
IFNAME=eth0

# setup NIC's interrupts, RPS, XPS (posix)
SET_NIC=no

# ethernet device driver (dpdk)
ETHDRV=

# ethernet device PCI ID (dpdk)
ETHPCIID=

# number of hugepages
NR_HUGEPAGES=64

# user for process (must be root for dpdk)
USER=scylla

# group for process
GROUP=scylla

# scylla home dir
SCYLLA_HOME=/var/lib/scylla

# scylla config dir
SCYLLA_CONF=/etc/scylla

# scylla arguments (for posix mode)
SCYLLA_ARGS="--smp 2 -m50G --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix"

## scylla arguments (for dpdk mode)
#SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack native --dpdk-pmd"

# setup as AMI instance
AMI=no
```

I update 1.6 of scylladb, but i don't update the version of monitor, I will update the monitor.

**Comment by avikivity** [comment]
@andrewrong you can see filter.db on node 1 uses 20GB.

My recommendations are:
 - start scylla without the --memory parameter so it can use more memory
 - increase bloom_filter_fp_chance (using `ALTER TABLE`)
 - wait for compaction, or force a major compaction (`nodetool compact`)
 - ultimately, install more memory in your nodes

**Comment by andrewrong** [comment]
@avikivity Do you know what cause this?  I think that my sence is simple；

**Comment by andrewrong** [comment]
@avikivity Do you have any suggestions about `increase bloom_filter_fp_chance (using ALTER TABLE)`?

**Comment by andrewrong** [comment]
my sence is store log, so my table just have two fields(uuid and content) and every row have ttl, the ttl always three、seven、ten、fifteen、thirty days; I use the default compacts(SizeTieredCompactionStrategy); I want to change this(Leveled Compaction), Do you know this change is valid?

**Comment by avikivity** [comment]
You have about 5 billion partitions.  Each partition requires many bits in the bloom filter, so the bloom filter is about 20GB.  That doesn't leave enough memory for everything else.

You can increase bloom_filter_fp_chance to 0.1, this will reduce read performance but also reduce the filter size.

I opened #2130 to automatically reduce the bloom filter size when it grows too large.

Your load is write-intensive, so I don't recommend using Leveled Compaction Strategy at all.  It's good for read intensive loads.

**Comment by andrewrong** [comment]
@avikivity  I know the reason; but I set the ttl in every row;  It should be delete when it touchs compact;

**Comment by avikivity** [comment]
It depends on the TTL and your write rate.  If the write rate is low and the TTL is short it may work.

Maybe DateTieredCompactionStrategy is a better match for your load.

Note: if your uuid column contains 16-byte UUIDs, it's better to use one of the UUID types for them, not text.

**Comment by slivne** [comment]
@andrewrong if there is a need for additional information please post and we can reopen.

**Comment by julienlau** [comment]
Thanks for the tip regarding bloom filter sizing with respect to filesize of Filter.db
