### ISSUE TITLE
Correct way backup ScyllaDB

### ISSUE THREAD

**Issue by kokizzu** [scylladb/scylla#2126]
What's the correct way to backup a scylladb so we could restore it on development environment?

Normally when using RDBMS, that we do a cold backup from replica every hour, we restore them every morning to a dev server so developers can test a newly created feature with updated data (and mess with them).

What the correct way to do this when using ScyllaDB?

related http://dba.stackexchange.com/questions/165922

**Comment by penberg** [comment]
@tzach @nirmaayan Do we have documentation on correct backup procedure? The procedures page doesn't seem to have anything on this: http://docs.scylladb.com/procedures/

**Comment by nirmaayan** [comment]
@penberg I'm working on this procedure
It takes some time since there are a lot to cover and I want our docs to be more comprehensive and detailed. 
I can estimate that it will be done during next week

**Comment by nirmaayan** [comment]
@kokizzu in Scylla you can hold a couple of copies of your data (depend on your RF), there for traditional backup isn't always needed.
In your scenario, you need to use the nodetool snapshot command (specify a keyspace that you want to backup)
For example: nodetool -h <your_ip> -p 7199 snapshot <keyspace_name>
When restoring:
First you need to delete the .db files 
By default, they are located under /var/lib/scylla/data/<keyspace_name>/<table_name>
Then copy the .db files from your last snapshot (or other one) 

Please let me know what is your cluster size and if you need any additional assistance

**Comment by nirmaayan** [comment]
I forget to mention that the backup is per node, please make sure to consider it when running the process
