### ISSUE TITLE
batch_size_fail_threshold_in_kb

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2128]
Hi
Cassandra has a batch_size_fail_threshold_in_kb parameter But Scylla is not
So, How does scylla process  any batch whose size exceeds 50KB ?

batch_size_warn_threshold_in_kb 
(Default: 5KB per batch) Causes Cassandra to log a WARN message when any batch size exceeds this value in kilobytes.
CAUTION:
Increasing this threshold can lead to node instability.
batch_size_fail_threshold_in_kb 
(Default: 50KB per batch) Cassandra fails any batch whose size exceeds this setting. The default value is 10X the value of batch_size_warn_threshold_in_kb.

**Comment by gleb-cloudius** [comment]
On Thu, Mar 02, 2017 at 02:29:24AM -0800, Junghyun Park wrote:
> Hi
> Cassandra have a batch_size_fail_threshold_in_kb parameter But Scylla is not
> So, How does scylla process  any batch whose size exceeds 50KB ?
Scylla suppose to have it. Are you sure it does not? Did it not work for
you?

--
			Gleb.

**Comment by infordb** [comment]
@gleb-cloudius Related logs
Mar  2 20:09:40 fomstap01 scylla: [shard 0] config - Unknown option batch_size_fail_threshold_in_kb ignored.

**Comment by gleb-cloudius** [comment]
On Thu, Mar 02, 2017 at 03:12:46AM -0800, Junghyun Park wrote:
> @gleb-cloudius Related logs
> Mar  2 20:09:40 fomstap01 scylla: [shard 0] config - Unknown option batch_size_fail_threshold_in_kb ignored.
> 
I confused it with batch_size_warn_threshold_in_kb. You are right. We
need to add it.

--
			Gleb.

**Comment by infordb** [comment]
@gleb-cloudius Do you mean scylla doesn't limit batch size now?

**Comment by gleb-cloudius** [comment]
On Thu, Mar 02, 2017 at 03:27:55AM -0800, Junghyun Park wrote:
> @gleb-cloudius Do you mean scylla doesn't limit batch size now?
> 
It does not.

--
			Gleb.
