### ISSUE TITLE
Adding a new node with authentication set - causes system_auth keyspace RF to be set to 1

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#2129]
*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

It seems that we create system_auth tables when a new node boots up with RF=1 and then allow it to connect to the cluster.

Somehow the schema sync code - aligns on the schema the last node has created which has RF=1.

to reproduce

1. create a cluster of 2 nodes)
2. enable auth (in scylla.yaml insert ```authenticator: PasswordAuthenticator```)
3. boot cluster
4. alter system_auth via cqlsh ```ALTER KEYSPACE "system_auth"    WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 2 };```
5. verify via ```describe KEYSPACE system_auth;```
6. add a node (with ```authenticator: PasswordAuthenticator```)
 7. run ```nodetool describecluster``` - the new node will not be synched
8. enter with cqlsh - old node/new node and run  ```describe KEYSPACE system_auth;``` - the old noewds should have RF=2 the added node RF=1
9. wait for all nodes to synch on schema ```nodetool describecluster```
10. enter with cqlsh old node/new node - ```describe KEYSPACE system_auth;```  will show RF=1

**Comment by glommer** [comment]
FYI: Another user has just reported this on our public slack.

**Comment by tgrabiec** [comment]
@slivne Schema sync works as expected, the latest change wins. Perhaps the problem is that we create the auth table before we do the sync with existing nodes?

**Comment by slivne** [comment]
@tgabriec - it could be ...

Yet that will be an issue when upgrading and there are differences in the
schema.

I know we had a discussion lately about the id generation of the auth and
traces and that you found that to make sure there is no conflict they
provide a "static" id ....

can you check what cassandra does - maybe we missed something

**Comment by tgrabiec** [comment]
@slivne I am not able to reproduce. Do you have logs for that run?

**Comment by slivne** [comment]
```
ccm create scylla-2 --scylla --vnodes -n 2 --install-dir=/home/shlomi/scylla-ccm/../scylla
 vi ~/.ccm/scylla-2/node1/conf/scylla.yaml 
 vi ~/.ccm/scylla-2/node2/conf/scylla.yaml 
 ccm node1 start --jvm_arg="--logger-log-level" --jvm_arg="migration_manager=trace" --jvm_arg="--logger-log-level" --jvm_arg="schema_tables=trace" --jvm_arg="--logger-log-level" --jvm_arg="storage_service=trace"
 ccm node2 start --jvm_arg="--logger-log-level" --jvm_arg="migration_manager=trace" --jvm_arg="--logger-log-level" --jvm_arg="schema_tables=trace" --jvm_arg="--logger-log-level" --jvm_arg="storage_service=trace"
 ccm node1 cqlsh -u cassandra -p cassandra
ALTER KEYSPACE "system_auth"    WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 2 };
describe KEYSPACE system_auth;

CREATE KEYSPACE system_auth WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '2'}  AND durable_writes = true;
.
.

 ccm add --scylla node3
 vi ~/.ccm/scylla-2/node3/conf/scylla.yaml 
 ccm node3 start --jvm_arg="--logger-log-level" --jvm_arg="migration_manager=trace" --jvm_arg="--logger-log-level" --jvm_arg="schema_tables=trace" --jvm_arg="--logger-log-level" --jvm_arg="storage_service=trace"
 ccm node1 cqlsh -u cassandra -p cassandra
describe KEYSPACE system_auth;

CREATE KEYSPACE system_auth WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '2'}  AND durable_writes = true;

.
.

 ccm node3 cqlsh -u cassandra -p cassandra
describe KEYSPACE system_auth;

CREATE KEYSPACE system_auth WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

.
.
 ccm node1 nodetool describecluster
(wait till they are in synch)
 ccm node1 cqlsh -u cassandra -p cassandra
describe KEYSPACE system_auth;

CREATE KEYSPACE system_auth WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
.
.
.

```
[all_logs.tar.gz](https://github.com/scylladb/scylla/files/821357/all_logs.tar.gz)

**Comment by tgrabiec** [comment]
@slivne In you logs on node3 I can see:

```
Bootstrap variables: 0 0 0 0
```

Which means `auto_bootstrap` is `false`, and that's the reason why node doesn't perform the schema sync.

**Comment by slivne** [comment]
ypu are right ... didn't change that in this run changing it now ... and
trying again

**Comment by slivne** [comment]
with auto_bootstrap: true - 

the issue does not occur - so it seems there is no bug ....

```
ccm create scylla-2 --scylla --vnodes -n 2 --install-dir=/home/shlomi/scylla-ccm/../scylla
echo "authenticator: PasswordAuthenticator" >> ~/.ccm/scylla-2/node1/conf/scylla.yaml 
echo "authenticator: PasswordAuthenticator" >> ~/.ccm/scylla-2/node2/conf/scylla.yaml 
ccm node1 start --jvm_arg="--logger-log-level" --jvm_arg="migration_manager=trace" --jvm_arg="--logger-log-level" --jvm_arg="schema_tables=trace" --jvm_arg="--logger-log-level" --jvm_arg="storage_service=trace"
ccm node2 start --jvm_arg="--logger-log-level" --jvm_arg="migration_manager=trace" --jvm_arg="--logger-log-level" --jvm_arg="schema_tables=trace" --jvm_arg="--logger-log-level" --jvm_arg="storage_service=trace"
ccm node1 nodetool describecluster
ccm node1 cqlsh -u cassandra -p cassandra -e "ALTER KEYSPACE system_auth    WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 2 };"
ccm node1 cqlsh -u cassandra -p cassandra -e "describe keyspace system_auth"
ccm add --scylla node3 -b
echo "authenticator: PasswordAuthenticator" >> ~/.ccm/scylla-2/node3/conf/scylla.yaml 
ccm node3 start --jvm_arg="--logger-log-level" --jvm_arg="migration_manager=trace" --jvm_arg="--logger-log-level" --jvm_arg="schema_tables=trace" --jvm_arg="--logger-log-level" --jvm_arg="storage_service=trace"
ccm node1 cqlsh -u cassandra -p cassandra -e "describe keyspace system_auth"
while true 
do 
   ccm node3 cqlsh -u cassandra -p cassandra -e "describe keyspace system_auth"
   sleep 1
done
```

yet maybe the customer also started his node in this manner (the ami by default I think has it to false)

**Comment by slivne** [comment]
the customer is using the ami 

- by default the ami sets auto_bootstrap to false.
- once the instance booted - they stopped the instance and changed the setting to be true - yet by that time it was to late.

I am checking if we have an ability in the ami to change the default bootstrap value.

**Comment by slivne** [comment]
so there is a way to start the ami tell it to have auto_bootstrap set to true

in the user data setting
```
--bootstrap
```
will change the default

https://github.com/scylladb/scylla-ami/blob/master/ds2_configure.py#L216


We need to update our documentation to reflect that

http://docs.scylladb.com/kb/add-nodes-on-ec2/ 

currently it only mentions seeds - we also need to specify bootstrap.

**Comment by glommer** [comment]
On Mon, Mar 6, 2017 at 11:30 AM, Shlomi Livne <notifications@github.com>
wrote:

> so there is a way to start the ami tell it to have auto_bootstrap set to
> true
>
> in the user data setting
>
> --bootstrap
>
> will change the default
>
> https://github.com/scylladb/scylla-ami/blob/master/ds2_configure.py#L216
>
> We need to update our documentation to reflect that
>
> http://docs.scylladb.com/kb/add-nodes-on-ec2/
>
> currently it only mentions seeds - we also need to specify bootstrap.
>

I would double check to make sure that bootstrap indeed only sets this
parameter at first boot.
If we weren't even aware of that, imagine how well tested this is?

Imagine an AMI set with this being bootstrapped every time it boots...

**Comment by tzach** [comment]
I think the right way is to use an AMI parameter for not starting Scylla.
Then you can update the bootstrap, cluster name etc without affecting the running cluster.

**Comment by tgrabiec** [comment]
2017-03-06 17:30 GMT+01:00 Shlomi Livne <notifications@github.com>:

> so there is a way to start the ami tell it to have auto_bootstrap set to
> true
>
> in the user data setting
>
> --bootstrap
>
> will change the default
>
> https://github.com/scylladb/scylla-ami/blob/master/ds2_configure.py#L216
>
> We need to update our documentation to reflect that
>
> http://docs.scylladb.com/kb/add-nodes-on-ec2/
>
> currently it only mentions seeds - we also need to specify bootstrap.
>

This procedure is missing more things, which are present in [1], like
running nodetool cleanup. Since that page is EC2-specific, it should link
to a general procedure.

[1]
https://docs.datastax.com/en/cassandra/2.1/cassandra/operations/ops_add_node_to_cluster_t.html

**Comment by tzach** [comment]
The generic add node does include cleanup
http://docs.scylladb.com/procedures/add_node_to_cluster/

KB section is out of date, and need to be revisited and moved under procedures.
https://github.com/scylladb/scylla-docs/issues/176

@nirmaayan FYI

**Comment by tgrabiec** [comment]
The problem doesn't reproduce on Cassandra 2.2, because they create default keyspace metadata with timestamp=0, so it always looses with manual changes.

Since https://issues.apache.org/jira/browse/CASSANDRA-8853

**Comment by tgrabiec** [comment]
Actually, it seems to be like that since 1.2.2 (https://issues.apache.org/jira/browse/CASSANDRA-5112)

**Comment by tgrabiec** [comment]
Before we can apply a similar solution, we have to fix `schema_tables::make_create_table_mutations()` to not generate keyspace mutations using `make_create_keyspace_mutations()`, which generates keyspace mutations with current timestamp.
