### ISSUE TITLE
Almost Fedora reladed project

### ISSUE THREAD

**Issue by CogumelosMaravilha** [scylladb/scylla#2131]
Lots of people are currently using a Debian based distro.
In my company we have around 150 AWS instances with only Debian based Linux.
Please didn't get sticked to Fedora.

**Comment by tzach** [comment]
@CogumelosMaravilha are you looking to build or run Scylla?
For the second, Scylla do have Debian packages
http://docs.scylladb.com/getting-started/debian8/

**Comment by slivne** [comment]
@CogumelosMaravilha we support Debian
