### ISSUE TITLE
Create snapshot without specify KEYSPACE cause cqlsh to disconnect

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#2133]
*Installation details*
Scylla version (or git commit hash):  1.6.1-20170218.2ea4da2
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): us-east1  ami-7ea37568

Steps to reproduce:

Create KEYSPACE
CREATE KEYSPACE nba WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : '3'};
Create TABLE and insert data:
CREATE TABLE nba.team_players (
player_name text,
player_jersy_number int,
player_position text,
team text,
height text,
age int,
PRIMARY KEY (player_name));

INSERT INTO nba.team_players (player_name, player_jersy_number, player_position, team, height, age) VALUES ('Russell Westbrook', 0, 'Guard','Oklahoma City Thunder','6-3',28);
INSERT INTO nba.team_players (player_name, player_jersy_number, player_position, team, height, age) VALUES ('Andre Roberson', 21, 'Forward','Oklahoma City Thunder','6-7',25);
INSERT INTO nba.team_players (player_name, player_jersy_number, player_position, team, height, age) VALUES ('Steven Adams', 12, 'Center','Oklahoma City Thunder','7-0',23);
INSERT INTO nba.team_players (player_name, player_jersy_number, player_position, team, height, age) VALUES ('Victor Oladipo', 5, 'Forward','Oklahoma City Thunder','6-4',24);
INSERT INTO nba.team_players (player_name, player_jersy_number, player_position, team, height, age) VALUES ('Jermi Grant', 9, 'Forward','Oklahoma City Thunder','6-9',22);
INSERT INTO nba.team_players (player_name, player_jersy_number, player_position, team, height, age) VALUES ('Enes Kanter', 11, 'Center','Oklahoma City Thunder','6-11',24);
INSERT INTO nba.team_players (player_name, player_jersy_number, player_position, team, height, age) VALUES ('Cameron Payne', 22, 'Guard','Oklahoma City Thunder','6-3',22);
INSERT INTO nba.team_players (player_name, player_jersy_number, player_position, team, height, age) VALUES ('Anthony Morrow', 2, 'Guard','Oklahoma City Thunder','6-5',31);
Run the nodetool snapshot command
not specify KEYSPACE
nodetool snapshot
Result:
[centos@ip-10-167-100-222 ~]$ nodetool snapshot
Requested creating snapshot(s) for [all keyspaces] with snapshot name [1488705641381]
nodetool: Scylla API server HTTP POST to URL '/storage_service/snapshots' failed: Storage I/O error: 1:
Operation not permitted
See 'nodetool help' or 'nodetool help '

When trying to enter to the cqlsh again we get the 
> Connection error: ('Unable to connect to any servers', {'127.0.0.1': error(111, "Tried connecting to >[('127.0.0.1', 9042)]. Last error: Connection refused")})
error message
Restart to Scylla allow to enter cqlsh again
Also there is no .db files under the snapshots

**Comment by slivne** [comment]
tried reproducing this and failing 

if you can reproduce this - share the machine and I would like to check a few things (scylla has access to the snapshots directory ...)

**Comment by nirmaayan** [comment]
@slivne can't reproduce now on 1.6.1
I'll try to continue and reproduce it

**Comment by slivne** [comment]
@nirmaayan any update if not please close
