### ISSUE TITLE
api: Add force_remove_endpoint for gossip

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#2134]
It is used to force remove a node from gossip membership if something
goes wrong or to accelerate the decommissioned node's gossip state
from the cluster.

Note: run the force_remove_endpoint api at the same time on all the
nodes in the cluster in order to prevent the removed nodes come back.
Becasue nodes without running the force_remove_endpoint api cmd can
gossip around the removed node information to other nodes in 2 *
ring_delay (2 * 30 seconds by default) time.

For instance, in a 3 nodes cluster, node 3 is decommissioned, to remove
node 3 from gossip membership prior the auto removal (3 days by
default), run the api cmd on both node 1 and node 2 at the same time.

$ curl -X POST --header "Accept: application/json"
"http://127.0.0.1:10000/gossiper/force_remove_endpoint/127.0.0.3"
$ curl -X POST --header "Accept: application/json"
"http://127.0.0.2:10000/gossiper/force_remove_endpoint/127.0.0.3"

Then run 'nodetool gossipinfo' on all the nodes to check the removed nodes
are not present.

**Comment by asias** [comment]
Patch[1] was on list but it was not merged.

[1] [PATCH scylla v1 1/1] api: Add force_remove_endpoint for gossip

**Comment by tzach** [comment]
> run the force_remove_endpoint api at the same time on all the
nodes in the cluster in order to prevent the removed nodes come back.

"Same time" is hard to do. The API itself is good, but for a large cluster we may need to extend gossip to carry the command, rather than competing with gossip propagation rate

**Comment by asias** [comment]
How hard would it be to run a single cmd on some servers with ssh or http interface at the same time? It does not require as accurate as milliseconds. Within 1 or 2 seconds should be fine.  
The api is supposed to use in case something went wrong. It is better to be designed as simple as possible.

**Comment by tzach** [comment]
I'm good with this API, agree its simple and to the point and we should add it ASAP.
I also think it won't do for a larger cluster, where SSH to many servers at the same time is error prone.

**Comment by asias** [comment]
It does not have to be ssh. It can be https access.

**Comment by asias** [comment]
What is the difference:

The "assasinate endpoint" makes a node directly to status LEFT like decommission does, but without streaming the relevant data. 

The "force_remove_endpoint" api removes gossip state of the node specified in the api from the node running the cmd.  It is much much safer than the "assasinate endpoint"  api.
