### ISSUE TITLE
scylla_io_setup script

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2135]
*Installation details*
Scylla version (or git commit hash):scylla-1.6.1-20170218.2ea4da2.el7.centos.x86_64
OS : Red Hat Enterprise Linux Server release 7.2

I got follow messages when executing scylla_io_setup script.
The num-io-queues parameter is not set and print some validation messages
Our data directory path is  /scylla , not /var/lib/scylla and use XFS file system.
Could you check this?

If The num-io-queues parameter is not set, what is default value ?  

</usr/lib/scylla>./scylla_io_setup
Generating evaluation file sized 10GB...10GB written in 11 seconds
Refining search for maximum. So far, 147188 IOPS
Maximum throughput: 147390 IOPS
Recommended --max-io-requests: 66
basic_ios::clear when writing configuration file. Please add them to your seastar command line
/var/lib/scylla did not pass validation tests, it may not be on XFS and/or has limited disk space.
This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is required.
To override this error, enable developer mode as follow:
 sudo /usr/lib/scylla/scylla_dev_mode_setup --developer-mode 1

**Comment by tzach** [comment]
@glommer can you please advise?

**Comment by glommer** [comment]
Hello

On Mon, Mar 6, 2017 at 1:35 AM, Junghyun Park <notifications@github.com>
wrote:

> *Installation details*
> Scylla version (or git commit hash):scylla-1.6.1-20170218.
> 2ea4da2.el7.centos.x86_64
> OS : Red Hat Enterprise Linux Server release 7.2
>
> I got an follow messages when executing scylla_io_setup script.
> The num-io-queues parameter is not set and print some validation messages
> Our data directory path is /scylla , not /var/lib/scylla and use XFS file
> system.
> Could you check this?
>
> If The num-io-queues parameter is not set, what is default value ?
>

The default value is the same number of shards. It is not set unless iotune
sees the need to reduce that value.


> </usr/lib/scylla>./scylla_io_setup
> Generating evaluation file sized 10GB...10GB written in 11 seconds
> Refining search for maximum. So far, 147188 IOPS
> Maximum throughput: 147390 IOPS
> Recommended --max-io-requests: 66
> basic_ios::clear when writing configuration file. Please add them to your
> seastar command line
>

That sounds to me like a permission issue. Did you run iotune as root?
It will write the file to /etc/, so you have to.

You don't need to run it again: go to /etc/scylla.d/io.conf and add:
"--max-io-requests 66"

**Comment by slivne** [comment]
@infordb if there is a need for additional clarification please post on this and we can reopen
