### ISSUE TITLE
Add Kubernetes Seed Provider integration

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2137]

**Comment by tzach** [comment]
reference: 

C* on K8S
https://github.com/kubernetes/kubernetes/blob/master/examples/storage/cassandra/README.md

K8S Seed provider
https://github.com/kubernetes/kubernetes/blob/master/examples/storage/cassandra/java/src/main/java/io/k8s/cassandra/KubernetesSeedProvider.java

**Comment by avikivity** [comment]
@tzach can we close this in favor of the operator?

**Comment by tzach** [comment]
Yes
https://github.com/scylladb/scylla-operator
