### ISSUE TITLE
scylla_setup disable SELINUX on Fedora 24 didn't work 

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla#2146]
*Installation details*
Scylla version (or git commit hash):   1.7RC1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora 24

When trying to disable SELINUX using scylla_setup, the script changed the SELINUX setting in /etc/sysconfig/selinux (which is used on CentOS/RedHat) and not in /etc/selinux/config (used by Fedora). So the disabling of SELinux didn't work.

**Comment by slivne** [comment]
although most of us developer on fedora, as of today, we do not support deploying on fedora - you can use developer-mode on fedora
