### ISSUE TITLE
nodetool cleanup does not cleanup correctly

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#2151]
1) start node1 and node3
2) inject some data
3) start another node2 with --auto-bootstrap=false
4) run nodetool rebuild on node2

UN  127.0.0.1  292.42 MB  32      ?       e4f68599-501a-48d1-a1b3-0c18950d8449  rack1
UN  127.0.0.2  270.24 MB  32      ?       397123b0-ec41-4476-8b56-e71520e083a8  rack1
UN  127.0.0.3  293.19 MB  32      ?       509e323b-9d16-410a-af24-041dbf3c3532  rack1

5) run nodetool rebuild on node2 again

UN  127.0.0.1  292.42 MB  32      ?       e4f68599-501a-48d1-a1b3-0c18950d8449  rack1
UN  127.0.0.2  494.72 MB  32      ?       397123b0-ec41-4476-8b56-e71520e083a8  rack1
UN  127.0.0.3  293.19 MB  32      ?       509e323b-9d16-410a-af24-041dbf3c3532  rack1

6) run nodetool cleanup on node2

As we can see, the size is not reduced.

UN  127.0.0.1  292.42 MB  32      ?       e4f68599-501a-48d1-a1b3-0c18950d8449  rack1
UN  127.0.0.2  494.72 MB  32      ?       397123b0-ec41-4476-8b56-e71520e083a8  rack1
UN  127.0.0.3  293.19 MB  32      ?       509e323b-9d16-410a-af24-041dbf3c3532  rack1

**Comment by tzach** [comment]
@asias maybe you have hard links from snapshot or inc backup, or the files are under compaction?

**Comment by asias** [comment]
My cluster is a total new cluster. I even run nodetool compact and wait for it to complete. The size is still not reduced on node2.

**Comment by nirmaayan** [comment]
What happens if you inject couple more GB to the cluster
What is the RF?

**Comment by asias** [comment]
I am using scylla: b8e4113dba0d04756d142de7e8d94bf8921b69c9

**Comment by asias** [comment]
```
cqlsh> DESCRIBE ks3

CREATE KEYSPACE ks3 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;

CREATE TABLE ks3.standard1 (
    key blob PRIMARY KEY,
    "C0" blob,
    "C1" blob,
    "C2" blob,
    "C3" blob,
    "C4" blob
) WITH COMPACT STORAGE
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

**Comment by tzach** [comment]
Unless I'm missing something, with replication is 3 and 3 nodes, nodetool clean should not remove any data.

**Comment by asias** [comment]
@tzach In step 5)  run nodetool rebuild on node2 again, which streamed data to node 2 again (~490MB). I would expect nodetool cleanup would reduce the size to ~270MB

**Comment by tzach** [comment]
@asias I'm missing something here.
With 3 nodes and RF=3, all nodes should have the same token ranges, so there are no token ranges to remove on cleanup.

**Comment by slivne** [comment]
cleanup does not do compaction of other files - it only reqrites the
sstables 1 by 1 and removes tokens the ndoe does not own.

**Comment by asias** [comment]
@slivne even if I run nodetool compact to trigger a compaction and waits for it complete. The size is not changed.

**Comment by asias** [comment]
@tzach the rf does not matter here,  rebuild operation will always stream data (which belongs to the local node) from peers. I run rebuild twice, it will stream twice. We will end up with sstables with the same data. I thought node cleanup would remove the duplicated data, but it is not. Since all the data do belong to local node. However, compaction is supposed to remove the duplicated sstables so we are supposed to see the reduced size report in nodetool.

**Comment by slivne** [comment]
if you check the disk usage does it align with what nodetool reports ....
we know we have an open bug on nodetool reporting incorrect sizes

**Comment by asias** [comment]
Update: the disk usage did reduce as expected after nodetool compact. The nodetool status report also reduced after a while. I saw it did not reduce, because I run the status on node1, and node1 did get the new size update yet. After I wait a while, the size all reduced as expected.
