### ISSUE TITLE
collection_type_impl: Correctly handle tombstoned collections

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#2152]
*Installation details*
Scylla version (or git commit hash): master @ aaae8db

The current implementations of `collection_type_impl::is_empty()` and `collection_type_impl::difference()` don't handle tombstoned collection cells correctly. In particular:

* `is_empty()` considers a collection cell with a tombstone (and no entries) as empty;
* `difference()` doesn't do set difference between the cells tombstones, and always returns the highests (this is incorrect, as it should only return the information in cell `a` that supersedes that in `b`, given `difference(a, b)`).

**Comment by avikivity** [comment]
Can you give an example failure scenario (in CQL terms)?

**Comment by duarten** [comment]
If we have a table with a list value, then if you update it like this:

```
insert into cf (k, listval) values (0, [1, 2, 3])
insert into cf (k, listval) values (0, []);
```
Then the difference with the existing value will be incorrect. This affects repair and view building.

**Comment by avikivity** [comment]
I'm chasing an issue where an insert (like your first line) gets duplicated and we get a list like `[1, 2, 3, 1, 2, 3]`.  Can there be a relationship with this bug?

**Comment by duarten** [comment]
I don't think so, this problem can cause the `[]` update to be lost, but I can't see how it would cause the duplication. 

Since the keys of a list are timeuuid's, can it be that that result is actually expected?

**Comment by pdziepak** [comment]
I may be wrong I think that this particular bug is only visible to users by making read repair unable to properly repair collection cells and degrading all subsequent data queries to mutation queries. In other words, from user perspective it is a performance issue, not a correctness issue.

@avikivity Is the problematic list created by CQL3 layer or some internal Scylla process? We used to have problems with internal code creating collections that didn't have their members sorted properly which broke subsequent applies.

**Comment by avikivity** [comment]
@duarten inserting a full list should insert a tombstone along with the list, no?  Not appending or prepending.

@pdziepak It seems so, normal cql shouldn't call difference(). AFAIK the problem was caused by normal cql inserts into a user table.

**Comment by duarten** [comment]
@pdziepak What prevents repair from succeeding? Depending on the direction of the difference, it would result in a false negative.

@avikivity Yes, but this problem should happen with a mutation containing nothing but the tombstone. There are mainly two problems here: `is_empty()` considering empty a collection mutation containing only a tombstone, and `difference(a, b)` incorrectly returning the tombstone of `b` if it's bigger than `a`'s. Not sure how these can result in that behavior.

**Comment by pdziepak** [comment]
Consider following operations:
```cql
INSERT INTO cf (pk, col) VALUES (0, []);
UPDATE cf SET col = col + [1] WHERE pk = 0;
```
Now, let's say that there is no previous data in that partuclar cell and node A didn't see the first operation, B has seen everything.
When such collection is queried, we will get a digest mismatch since A doesn't have a tombstone inserted by first operation, but the difference is going to be empty because it should contain only the tombstone and buggy `is_empty()` ignores those. As a result, A doesn't get the tombstone and the collection is not repaired. All subsequent queries will replicate this behaviour.
