### ISSUE TITLE
sstables: scylla_metadata component can be discarded after it has been written / after reading it and computing shards

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#2153]
*Installation details*
Scylla version (or git commit hash): 60c6b9a240de70e92d620000ba1d4f79aaec62e7

**Comment by tgrabiec** [comment]
@slivne Who can discard it? Is it just a performance issue (need to regenerate it on next boot and reshard the sstable)?

**Comment by slivne** [comment]
I meant remove the memory used by scylla_metadata we keep it in memory and
do not use it.

**Comment by raphaelsc** [comment]
we already do that, closing...
