### ISSUE TITLE
Warning: different versions of Scylla in the same cluster

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2154]
*Installation details*
Scylla version (or git commit hash): 1.6

Running multiple version of Scylla is possible, and even common (during upgrades) but not recommended and hard to debug.
It will be good to warn the user if is there are more than one version of scylla in the cluster.
Since upgrades are commons and can take time, this should be a one-time log, not an ongoing one.

**Comment by slivne** [comment]
@tzach a rolling upgrade will always have two differnt versionat the same - not clear to me how a one-time log helps here.

**Comment by tzach** [comment]
Good point. Still, we need to find a way to let the user know this is the case.
Maybe its a monitoring feature, not a a Scylla one.

**Comment by slivne** [comment]
We lately added a metric exposing the version "current_version" - it can be extracted from that.

**Comment by tzach** [comment]
Closing this for a scylla monitoring issue
https://github.com/scylladb/scylla-grafana-monitoring/issues/151
