### ISSUE TITLE
Installation error in system where cassandra is already installed

### ISSUE THREAD

**Issue by shivaachari** [scylladb/scylla#2157]
*Installation details*
Scylla version (or git commit hash): 1.6.1-20170218.2ea4da2
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubutu on Ec2

sudo apt-get install scylla
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages were automatically installed and are no longer required:
  linux-headers-4.4.0-53 linux-headers-4.4.0-53-generic linux-headers-4.4.0-59 linux-headers-4.4.0-59-generic linux-headers-4.4.0-62 linux-headers-4.4.0-62-generic linux-image-4.4.0-53-generic
  linux-image-4.4.0-59-generic linux-image-4.4.0-62-generic
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  scylla-tools
The following NEW packages will be installed:
  scylla scylla-tools
0 upgraded, 2 newly installed, 0 to remove and 78 not upgraded.
Need to get 0 B/19.2 MB of archives.
After this operation, 22.6 MB of additional disk space will be used.
Do you want to continue? [Y/n] y
WARNING: The following packages cannot be authenticated!
  scylla-tools scylla
Install these packages without verification? [y/N] y
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
(Reading database ... 213499 files and directories currently installed.)
Preparing to unpack .../scylla-tools_1.6.1-20170218.710229c-ubuntu1_all.deb ...
Unpacking scylla-tools (1.6.1-20170218.710229c-ubuntu1) ...
dpkg: error processing archive /var/cache/apt/archives/scylla-tools_1.6.1-20170218.710229c-ubuntu1_all.deb (--unpack):
 trying to overwrite '/usr/lib/python2.7/dist-packages/cassandra_pylib-0.0.0.egg-info', which is also in package cassandra 3.9
dpkg-deb: error: subprocess paste was killed by signal (Broken pipe)
Selecting previously unselected package scylla.
Preparing to unpack .../scylla_1.6.1-20170218.2ea4da2-ubuntu1_amd64.deb ...
Unpacking scylla (1.6.1-20170218.2ea4da2-ubuntu1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/scylla-tools_1.6.1-20170218.710229c-ubuntu1_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by penberg** [comment]
I don't think we support installing both side-by-side.

/cc @syuu1228 @slivne

**Comment by slivne** [comment]
We do not support installation side by side on the same host via packaging.
Cassandra and Scylla similar tools yet there are some differences in
implementation (for example sstableloader / nodetool etc.) as such only one
can be accessible in the user path.

Having said that. if cassandra is installed via an extracted tar (and not
via the rpm) then one can install scylla and have cassandra one the same
host. In this case there is no issue of conflicts.

**Comment by syuu1228** [comment]
I think it can avoid by moving python modules to nonstandard path or renaming modules, but shouldn't we add conflict with cassandra packages?

**Comment by slivne** [comment]
@syuu1228 good idea - lets add a conflict with cassandra packages

**Comment by slivne** [comment]
@syuu1228 - do we have that ?
