### ISSUE TITLE
Row tombstone list equality is too strict

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#2158]
*Installation details*
Scylla version (or git commit hash): master

Two `mutation_partition`s are equal not only if they have the same range tombstones, but also if they are split exactly the same way. This is too strict and can be relaxed.

**Comment by tgrabiec** [comment]
Can you give an example?

**Comment by duarten** [comment]
With the current code, a tombstone list such as { [2, 4] } is not equal to a tombstone list containing { [2, 3), [3, 4] }. I don't know if this problem is user-visible, as we're mostly interested in the the mutation hash;  I hit this when writing a test for difference().

**Comment by pdziepak** [comment]
We should merge such tombstones (if they have equal timestamps), otherwise comparing checksum for repair will render false positives.
