### ISSUE TITLE
streaming: Add api to terminate ongoing streaming

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#2159]
Users may want to terminate the ongoing streaming.  We can  add API to do so.  We have similar API to terminate repair. 

For example:

To terminate ongoing streaming:

 $ curl -X POST  --header "Accept: application/json"
    "http://127.0.0.2:10000/storage_service/force_terminate_streaming"

To terminate ongoing repair:
 $ curl -X POST  --header "Accept: application/json"
    "http://127.0.0.2:10000/storage_service/force_terminate_repair"

**Comment by slivne** [comment]
@asias what does force_terminate_streaming do 

I don't think we should allow killing streaming its internal we can allow killing upper layer tasks (add node, remove node, decommission node, repair, rebuild etc.) -  that can cause streaming to happen but not the streaming itself. 

Some of this are easy to stop (add node) - others we may be missing how todo that - and it may be more complex then killing the stream we may need to "fix" other items to make sure the cluster is kept consistent (token owenrship change as an example).

We should allow terminating repair - there are other procedures that can be stopped via nodetool stop (https://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsStop.html) and we can consider them.

**Comment by slivne** [comment]
related to #2105

**Comment by asias** [comment]
@slivne Allowing to stop upper layer tasks should not disallow user to stop the streaming. streaming can last very long time.  If anything went wrong, user should be able to have a way to stop the streaming. 

Currently, we need to 1) run the api to terminate repair  2) run the api to terminate streaming. 
I do not plan to modify repair code to stop streaming automatically, because we will probably not use streaming in the future in repair anyway.

**Comment by slivne** [comment]
@asias - terminating repair should stop the streaming related to it

The api should stay the same no matter what the impl is - calling terminate repair should terminate anything related to repair (even if it needs to call 5 different apis to impl that).

**Comment by asias** [comment]
In 9c8da2cc5668302ad9fe184087626da1e2285a67 (streaming: Add abort to stream_plan), we added abort support to streaming. 

Terminate repair will terminate the underlying stream plan if any.  

Other operations like bootstrap/decommission, we can not terminate them with api. 

I will close the issue for now.
