### ISSUE TITLE
Procedures: adding a data center to a cluster

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#216]
Using: 
* ALTER KEYSPACE 
Change the keyspace properties to specify the desired replication factor for the new data center.
For example, set strategy options to DC1:2, DC2:2.
* nodetool rebuild specifying the existing data center on all nodes in the new data center:
nodetool rebuild -- name_of_existing_data_center

Otherwise, requests to the new data center with LOCAL_ONE or ONE consistency levels may fail if the existing data centers are not completely in-sync.
* nodetool ring
* nodetool repair

 http://docs.datastax.com/en/cassandra/2.0/cassandra/operations/ops_add_dc_to_cluster_t.html

**Comment by slivne** [comment]
@tzach  ALTER KEYSPACE is post GA - lets update this accordingly

**Comment by tzach** [comment]
@slivne can we close this?

**Comment by slivne** [comment]
Yes - I ran the procedure manually and it works on 1.2

We are lacking a dtest - something that we should add
