### ISSUE TITLE
backtrace error when using docker nightly

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2162]
*Installation details*
Scylla version (or git commit hash): 

reproduce:
```
sudo docker run --name some-scylla -d scylladb/scylla-nightly --memory 1G --smp 1
sudo docker logs some-scylla | grep error
WARNING: unable to mbind shard memory; performance may suffer: 
Reactor stalled for 2006 ms on shard 0.
Backtrace:
  0x00000000004e46d8
  0x00000000004e49b9
  0x00007f54fe8b236f
  0x0000000000a569af
  0x0000000000a60eb1
  0x0000000000a617b7
  0x0000000000a5a277
  0x0000000000a5ae74
  0x0000000000a5c905
  0x00000000004e244f
  0x0000000000530eba
  0x00000000005b4086
  0x000000000047335d
  0x00007f54fe503b34
  0x00000000004de50e
Reactor stalled for 4058 ms on shard 0.
Backtrace:
  0x00000000004e46d8
  0x00000000004e49b9
  0x00007f54fe8b236f
  0x0000000000a569af
  0x0000000000a60eb1
  0x0000000000a617b7
  0x0000000000a5a277
  0x0000000000a5ae74
  0x0000000000a5c905
  0x00000000004e244f
  0x0000000000530eba
  0x00000000005b4086
  0x000000000047335d
  0x00007f54fe503b34
  0x00000000004de50e
```

Scylla seems to work after these messages

**Comment by penberg** [comment]
It's the new Scylla task stall detector at work. If you're running with default Docker configuration, you're likely using overlayfs or aufs, which understandably don't support AIO/DIO very well. I suppose we could just disable the detector in our Docker images.

/cc @avikivity @tgrabiec

**Comment by tzach** [comment]
@penberg I think we should. Scary stuff

**Comment by slivne** [comment]
so should we disable this when developer-mode is used (AFAIK docker by default is developer-mode)

**Comment by glommer** [comment]
The goal was exactly to have this enabled by default in developer mode, so
we - developers - can catch this.

What we can and should do for the time being is lowering the treshold at
which it triggers, so those will be printed only when serious hangs will
occur.

**Comment by tgrabiec** [comment]
4 seconds seems already serious to me.

@tzach, can you resolve the backtrace?

**Comment by tzach** [comment]
> @tzach, can you resolve the backtrace?

Maybe, if you point me to instructions

**Comment by tgrabiec** [comment]
@tzach https://github.com/scylladb/scylla/wiki/How-to-resolve-backtrace

**Comment by penberg** [comment]
We certainly don't want to disable this check for developer mode. I suppose it's time to introduce a "docker mode" and start using that instead.

**Comment by tzach** [comment]
Sorry, still too hard for me. I'm running Scylla in docker, and I'm not sure the instruction cover this case.
The probelm is easy to reprudce if someone else want to try extract the data.

**Comment by slivne** [comment]
@tzach can you retest the nightly ?

**Comment by tzach** [comment]
Same or similar problem

```
sudo docker run --name some-scylla -d scylladb/scylla-nightly --memory 1G --smp 1
9e753ec4315ff31a4776ae7cbf591926b6ee8a4bb7d41769846ea87034b61e0a
~$ sudo docker logs some-scylla | grep error
WARNING: unable to mbind shard memory; performance may suffer: 
Reactor stalled for 2038 ms on shard 0.
Backtrace:
  0x00000000004e4ae8
  0x00000000004e4dc9
  0x00007f460aa1136f
  0x0000000000a9767f
  0x0000000000aa1c79
  0x0000000000aa2237
  0x0000000000a9b057
  0x0000000000a9bcd4
  0x0000000000a9db15
  0x00000000004e287f
  0x00000000005366aa
  0x00000000005b75b2
  0x0000000000473714
  0x00007f460a662b34
  0x00000000004de93e
Reactor stalled for 4070 ms on shard 0.
Backtrace:
  0x00000000004e4ae8
  0x00000000004e4dc9
  0x00007f460aa1136f
  0x0000000000a9767f
  0x0000000000aa1c79
  0x0000000000aa2237
  0x0000000000a9b057
  0x0000000000a9bcd4
  0x0000000000a9db15
  0x00000000004e287f
  0x00000000005366aa
  0x00000000005b75b2
  0x0000000000473714
  0x00007f460a662b34
  0x00000000004de93e
```

**Comment by tgrabiec** [comment]
@tzach Can you resolve the backtrace?

**Comment by tzach** [comment]
@tgrabiec from te link you attached its look like I need the source code. Is it the case?
Can you please try on your laptop and check if you see the same?
Its 100% reproducible for me

**Comment by slivne** [comment]
So should we impl @penberg suggestion and add a "XXXX mode" that will not enable the stall detector, @tzach , @avikivity ?

**Comment by slivne** [comment]
@avikivity , @tzach - ping

**Comment by avikivity** [comment]
No more modes. `--stall-detector 0|1`. Default enabled.

Can also write `--blocked-reactor-notify-ms 999999999` and it should work now.

**Comment by avikivity** [comment]
Docker can disable the stall detector by default since it's likely to trigger there.
