### ISSUE TITLE
how to create table with DATE data type in scylla

### ISSUE THREAD

**Issue by MadMichael888** [scylladb/scylla#2166]
Hi, I read that scylla support cassandra 3.0 data types such as date. But when I connect to scylla using cqlsh, it shows:

[root@de830bc4412b /]# cqlsh
Connected to Test Cluster at 10.42.243.181:9042.
[cqlsh 5.0.1 | Cassandra 2.1.8 | CQL spec 3.2.1 | Native protocol v3]
Use HELP for help.
cqlsh>

And I cannot create a table with date type. Is there anyway to start scylla with cassandra version 3.0?

Thank you in advance.

*Installation details*
Scylla version (or git commit hash): 1.6.2
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.0.4
Docker Image: scyllaDB/scylla

**Comment by avikivity** [comment]
Please disregard the version number and just try it.  However, I think those features were added in 1.7, not 1.6.

**Comment by penberg** [comment]
@avikivity Yes, those data types are introduced in Scylla 1.7. They were added in Cassandra 2.2, not 3.0, btw.

**Comment by MadMichael888** [comment]
Got it. Thank you!
