### ISSUE TITLE
Procedure: Replacing a dead seed node

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#217]
* Promote an existing node to a seed node by adding its IP address to -seeds list and remove (demote) the IP address of the dead seed node from the cassandra.yaml file for each node in the cluster.
* Replace the dead node, as described in Replacing a dead node.

http://docs.datastax.com/en/cassandra/2.0/cassandra/operations/ops_replace_seed_node.html

**Comment by slivne** [comment]
@elcallio do we reread the scylla.yaml and update the configuration 

@asias will this work in gossip

**Comment by asias** [comment]
Seed node is mostly useful when a node boots up. Gossip does not re-read scylla.yaml when seed configuration is updated. (Neither does Cassandra). It is not needed for proper operation for the existing running node.  When a seed node is down, gossip will mark it is down as we do for other normal node. Why do we need to update seed config in scylla.yaml ? It is only useful when the node restarts.

**Comment by slivne** [comment]
If you had a single seed node in the cluster

It dies

You want to replace it - how do you do that ?
 How do old nodes non seed find the "new replacing seed node' ?

**Comment by slivne** [comment]
@asias - can you comment on the above - how do we handle the case of a single seed node - does origin reread the .yaml

**Comment by slivne** [comment]
@asias ping

**Comment by tzach** [comment]
@tzach check the same feature in Cassandra

**Comment by asias** [comment]
@slivne We already support the procedure "replacing a dead seed node" as Cassandra does.   It does not matter if it is a single seed node or not in the cluster. 

How old non-seed nodes find the new seed node? Each node's scylla.yaml file is updated to use the new seed node. When the node reboots, it knows the new seed node. As I replied in the pervious comments, both scylla and cassandra do not reread the yaml file to get new seed node (if yaml file is updated) during runtime.

**Comment by asias** [comment]
I think we should close this issue now.

**Comment by slivne** [comment]
I missed "both scylla and cassandra do not reread the yaml file to get new seed node" - closing
