### ISSUE TITLE
1.7-rc1 candidate AMI issue starting an instance not via console

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#2171]
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-6f5df479

starting an instance via the console works

starting an instance via boto api does not work
```
#!/usr/bin/python
import boto.ec2

ec2=boto.ec2.connect_to_region("us-east-1",aws_access_key_id='---', aws_secret_access_key='---')

#instance_type = ["c3.large","c3.xlarge","c3.2xlarge","c3.4xlarge","c3.8xlarge","i2.xlarge","i2.2xlarge","i2.4xlarge","i2.8xlarge"]
instance_type = ["c3.2xlarge"]

for it in instance_type:
    reservation = ec2.run_instances( image_id="ami-6f5df479", 
                                     key_name="shlomi-ec2-n-virginia", 
                                     instance_type=it,
#                                     security_groups = [ "sg-2cdea246"] )
                                     security_groups = [ "ALL!"] )

```

the issue is probably related to the updated code related to finding devices

```
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: Waiting for cloud-init to finish...
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: [INFO] No userdata found. Starting 1 node clusters, by default.
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: [INFO] Using instance type: c3.2xlarge
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: [INFO] meta-data:instance-type: c3.2xlarge
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: [INFO] meta-data:local-ipv4: 10.182.83.152
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: [INFO] meta-data:public-hostname: ec2-54-159-91-94.compute-1.amazonaws.com
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: [INFO] meta-data:ami-launch-index: 0
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: [INFO] meta-data:reservation-id: r-06134986dcad8dcf6
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: [INFO] Using cluster name: Test Cluster - No AMI Parameters
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: [INFO] Using cluster size: 1
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: [INFO] Using seed indexes: [0, 1, 1]
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: [INFO] Reflector loop...
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: [INFO] 03/16/17-21:28:41 Reflector: Received 1 of 1 responses from: [u'10.182.83.152']
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: [INFO] scylla.yaml configured.
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: /dev/xvdd is not found
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: [INFO] RAID Array containing ['xvdb', 'xvdc', 'xvdd', 'xvde', 'xvdf', 'xvdg', 'xvdh', 'xvdi'] not found. Creating...
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: Traceback (most recent call last):
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 157, in <module>
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: get_disk_bundles()
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 153, in get_disk_bundles
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: config_array(t, typemap[t], role[t], mdidx)
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: File "/usr/lib/scylla/scylla-ami/scylla_create_devices", line 58, in config_array
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: "--volume-role", role ])
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: raise CalledProcessError(retcode, cmd)
Mar 16 21:28:41 ip-10-182-83-152 scylla_ami_setup[790]: subprocess.CalledProcessError: Command '['/usr/lib/scylla/scylla_raid_setup', '--raiddev', '/dev/md0', '--disks', '/dev/xvdb,/dev/xvdc,/dev/xvdd,/dev/xvde,
Mar 16 21:28:41 ip-10-182-83-152 systemd[1]: scylla-ami-setup.service: main process exited, code=exited, status=1/FAILURE
Mar 16 21:28:41 ip-10-182-83-152 systemd[1]: Failed to start Scylla AMI Setup.
Mar 16 21:28:41 ip-10-182-83-152 systemd[1]: Dependency failed for Scylla Server.
Mar 16 21:28:41 ip-10-182-83-152 systemd[1]: Dependency failed for Scylla JMX.
Mar 16 21:28:41 ip-10-182-83-152 systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
Mar 16 21:28:41 ip-10-182-83-152 systemd[1]: Dependency failed for Run Scylla Housekeeping restart mode.
Mar 16 21:28:41 ip-10-182-83-152 systemd[1]: Job scylla-housekeeping-restart.timer/start failed with result 'dependency'.
Mar 16 21:28:41 ip-10-182-83-152 systemd[1]: Dependency failed for Run Scylla Housekeeping daily mode.
lines 1664-1714/1873 91%
```

**Comment by syuu1228** [comment]
This is because number of block devices(/dev/xvd*) and number of ephemerals on instance metadata is inconsistent.
But I have no idea how it happens..
Anyway we can check device file is actually exists, before trying to use them.

```
[centos@ip-10-65-192-114 ~]$ ls -l /dev/xvd*
brw-rw---- 1 root disk 202,  0 Mar 16 21:52 /dev/xvda
brw-rw---- 1 root disk 202,  1 Mar 16 21:52 /dev/xvda1
brw-rw---- 1 root disk 202, 16 Mar 16 21:52 /dev/xvdb
brw-rw---- 1 root disk 202, 32 Mar 16 21:52 /dev/xvdc
[centos@ip-10-65-192-114 ~]$ curl http://169.254.169.254/latest/meta-data/block-device-mapping/
ami
ephemeral0
ephemeral1
ephemeral2
ephemeral3
ephemeral4
ephemeral5
ephemeral6
ephemeral7
root[centos@ip-10-65-192-114 ~]$ curl http://169.254.169.254/latest/meta-data/block-device-mapping/ephemeral0
sdb[centos@ip-10-65-192-114 ~]$ curl http://169.254.169.254/latest/meta-data/blodevice-mapping/ephemeral1
sdc[centos@ip-10-65-192-114 ~]$ curl http://169.254.169.254/latest/meta-data/blodevice-mapping/ephemeral2
sdd[centos@ip-10-65-192-114 ~]$ curl http://169.254.169.254/latest/meta-data/blodevice-mapping/ephemeral3
sde[centos@ip-10-65-192-114 ~]$ curl http://169.254.169.254/latest/meta-data/blodevice-mapping/ephemeral4
sdf[centos@ip-10-65-192-114 ~]$ curl http://169.254.169.254/latest/meta-data/blodevice-mapping/ephemeral5
sdg[centos@ip-10-65-192-114 ~]$ curl http://169.254.169.254/latest/meta-data/blodevice-mapping/ephemeral6
sdh[centos@ip-10-65-192-114 ~]$ curl http://169.254.169.254/latest/meta-data/blodevice-mapping/ephemeral7
```

**Comment by slivne** [comment]
It may be happening because when we create the AMI we list all possible
devices (8 so far based on i2.8x)

shlomi@localhost~/scylla/dist/ami (branch-1.7)$ cat scylla.json
{
  "builders": [
    {
      "type": "amazon-ebs",
      "access_key": "{{user `access_key`}}",
      "secret_key": "{{user `secret_key`}}",
      "subnet_id": "{{user `subnet_id`}}",
      "security_group_id": "{{user `security_group_id`}}",
      "region": "{{user `region`}}",
      "associate_public_ip_address": "{{user
`associate_public_ip_address`}}",
      "source_ami": "{{user `source_ami`}}",
      "user_data_file": "user_data.txt",
      "instance_type": "{{user `instance_type`}}",
      "ssh_username": "{{user `ssh_username`}}",
      "ssh_timeout": "5m",
      "ami_name": "{{user `ami_prefix`}}scylla_{{isotime |
clean_ami_name}}",
      "enhanced_networking": true,
      "launch_block_device_mappings": [
        {
          "device_name": "/dev/sda1",
          "volume_size": 10,
          "delete_on_termination": true
        }
      ],
      "ami_block_device_mappings": [
        {
          "device_name": "/dev/sdb",
          "virtual_name": "ephemeral0"
        },
        {
          "device_name": "/dev/sdc",
          "virtual_name": "ephemeral1"
        },
        {
          "device_name": "/dev/sdd",
          "virtual_name": "ephemeral2"
        },
        {
          "device_name": "/dev/sde",
          "virtual_name": "ephemeral3"
        },
        {
          "device_name": "/dev/sdf",
          "virtual_name": "ephemeral4"
        },
        {
          "device_name": "/dev/sdg",
          "virtual_name": "ephemeral5"
        },
        {
          "device_name": "/dev/sdh",
          "virtual_name": "ephemeral6"
        },
        {
          "device_name": "/dev/sdi",
          "virtual_name": "ephemeral7"
        }
      ]
    }
  ],
  "provisioners": [
    {
      "type": "file",
      "source": "files/",
      "destination": "/home/{{user `ssh_username`}}/"
    },
    {
      "type": "file",
      "source": "../../scripts/scylla_install_pkg",
      "destination": "/home/{{user `ssh_username`}}/scylla_install_pkg"
    },
    {
      "type": "shell",
      "inline": [
         "sudo /home/{{user `ssh_username`}}/scylla-ami/scylla_install_ami
{{ user `install_args` }}"
       ]
    }
  ],
  "variables": {
    "access_key": "",
    "secret_key": "",
    "subnet_id": "",
    "security_group_id": "",
    "region": "",
    "associate_public_ip_address": "",
    "instance_type": "",
    "install_args": "",
    "ami_prefix": "",
    "source_ami": "",
    "ssh_username": ""
  }
}
shlomi@lo

**Comment by syuu1228** [comment]
Maybe that's the reason but the setting required for bigger instances, and we haven't find a way to detect attached ephemerals from metadata, I think checking device file is a only solution for now.
