### ISSUE TITLE
grafana replica read metric

### ISSUE THREAD

**Issue by ban4785** [scylladb/scylla#2178]
*Installation details*
Scylla version (or git commit hash): 1.6.1
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.2

Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets= cores= hyperthreading= memory= 12core hyperthreading, 32G Memory
Disks: (SSD/HDD, count) : 2 SSD, raid 0

i tested write only case with java app.
100 batch unlogged insert type and 
keyspace replica options =  {'class': 'SimpleStrategy', 'replication_factor': '3'};

i found that only one node show replica read & caching read in grafana.
and disk i/o was 100MB/s in write, 20~30MB in read(because compaction operation read).
i think that replica read and caching occurs only read request, but in write only case i found that metrics. 
i want to know that replica read and caching metrics. 

--grafana replica read
![writeonly](https://cloud.githubusercontent.com/assets/20348151/24128823/c3de7926-0e21-11e7-99bc-46fca4d4809d.png)

--grafana caching
![writeonly](https://cloud.githubusercontent.com/assets/20348151/24128841/e5b26800-0e21-11e7-99b1-1a98bfbec1cf.png)

--grafana disk i/o
![writeonly](https://cloud.githubusercontent.com/assets/20348151/24128859/0e778e82-0e22-11e7-916d-b3f7921d58ee.png)

**Comment by infordb** [comment]
We did the same test again.
This time a replica read occurred on node 1

![image](https://cloud.githubusercontent.com/assets/10610884/24131729/b7ef2ea0-0e33-11e7-8f27-ec4cecffd0b1.png)

**Comment by tgrabiec** [comment]
@ban4785 What kind of statements do you have in the batch exactly, do you append to list columns?

If not, can you check by looking at read counts in `nodetool cfstats` which tables are receiving reads?

**Comment by infordb** [comment]
@tgrabiec 
we don't use list columns , but use UDT column
I checked cfstats but there is no read  on all 3 node

[PROD-root]swfosldb03:/root>nodetool cfstats -H foms
Keyspace: foms
        Read Count: 0
        Read Latency: NaN ms.
        Write Count: 2326203995
        Write Latency: 5.828612636356512E-6 ms.
        Pending Flushes: 0

**Comment by ban4785** [comment]
@tgrabiec 
batch kind => batch size 100, consistency level quorum setting, unlogged batch.
table has 2 udt column and text, int type column.

i checked nodetool but non tables are receiving reads.

**Comment by tgrabiec** [comment]
I meant stats for all tables, including system tables. You can try this:

1. Save stats to a file named `s1` :
```
nodetool cfstats | egrep "(Table: |Local read count:)" | xargs -l2 echo > s1
```
2. wait a while
3. Save stats to a file named `s2`
```
nodetool cfstats | egrep "(Table: |Local read count:)" | xargs -l2 echo > s2
```
4. Calculate the diff:
```
diff -u s1 s2
```

Example output:
```patch
--- s1  2017-03-23 08:38:35.171147729 +0000
+++ s2  2017-03-23 08:39:04.207493695 +0000
@@ -6,7 +6,7 @@
 Table: compaction_history Local read count: 0
 Table: compactions_in_progress Local read count: 0
 Table: hints Local read count: 0
-Table: local Local read count: 52
+Table: local Local read count: 76
 Table: paxos Local read count: 0
 Table: peer_events Local read count: 0
 Table: peers Local read count: 0
```

**Comment by ban4785** [comment]
i,m sorry i removed sstables for another test.
i think that you guess other schema i/o.
i,ll remake this and cfstats all tables.

**Comment by slivne** [comment]
@ban4785 can you please provide the additional information

**Comment by infordb** [comment]
@tgrabiec @slivne 

We found table with read
It is system_auth.users

We use  authenticator/authorizer and default replication factor of 1 for the system_auth keyspace
so,  replica read occurred on only node 1 which manaages users table

The odd thing is, I do not know why scylla check the users table for each cql


==> we use cassandra user as superuser so, read didn't occur on permission table 
cfstats system_auth| egrep "(Table: |Local read count:)"
                Table: credentials
                Local read count: 109
                Table: permissions
                Local read count: 0
                Table: users
                Local read count: 4323383

**Comment by tgrabiec** [comment]
\cc @elcallio 

One problem is that using replication factor of 1 for system_auth is not recommended, if you loose that node, your user will not be able to log into the cluster. So use something bigger than 1, maybe even replicate to all nodes. That should also help with the cost of querying of system_auth, since such queries could be local then.

As for frequent queries of system_auth, there's something called permission cache, which is supposed to help avoiding auth queries on each CQL query. However, it doesn't keep the entries valid forever, they expire. It's controlled by the following config options (scylla.yaml):

  permissions_update_interval_in_ms 
  permissions_validity_in_ms
  permissions_cache_max_entries

Are you using defaults for these? You could try to see if bumping them up would reduce the load on system_auth.

**Comment by slivne** [comment]
The reads are from system_auth as you have pointed out.

There is another issue to improve performance of reading from system_auth.

Closing this issue
