### ISSUE TITLE
Non-stop compaction - truncate problem

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2180]
*Installation details*
Scylla version (or git commit hash):

I started scylla with replace_address
and  Even though there is no write/read load, scylla does not stop compaction on the same file

<<<< compaction log  >>>> 
Mar 20 22:20:00 fomstap02 scylla: [shard 0] compaction - Compacting [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-872-Data.db:level=0, ]
Mar 20 22:20:00 fomstap02 scylla: [shard 4] compaction - Compacting [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-876-Data.db:level=0, ]
Mar 20 22:20:00 fomstap02 scylla: [shard 6] compaction - Compacting [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-878-Data.db:level=0, ]
Mar 20 22:20:01 fomstap02 scylla: [shard 0] compaction - Compacted 1 sstables to [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-880-Data.db:level=0, ]. 202 bytes to 202 (~100% of original) in 309ms = 0.000623438MB/s. ~256 total partitions merged to 2.
Mar 20 22:20:01 fomstap02 scylla: [shard 4] compaction - Compacted 1 sstables to [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-884-Data.db:level=0, ]. 101 bytes to 101 (~100% of original) in 309ms = 0.000311719MB/s. ~256 total partitions merged to 1.
Mar 20 22:20:01 fomstap02 scylla: [shard 6] compaction - Compacted 1 sstables to [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-886-Data.db:level=0, ]. 101 bytes to 101 (~100% of original) in 317ms = 0.000303852MB/s. ~256 total partitions merged to 1.
Mar 20 22:20:04 fomstap02 scylla: [shard 0] compaction - Compacting [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-880-Data.db:level=0, ]
Mar 20 22:20:04 fomstap02 scylla: [shard 4] compaction - Compacting [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-884-Data.db:level=0, ]
Mar 20 22:20:04 fomstap02 scylla: [shard 6] compaction - Compacting [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-886-Data.db:level=0, ]
Mar 20 22:20:05 fomstap02 scylla: [shard 0] compaction - Compacted 1 sstables to [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-888-Data.db:level=0, ]. 202 bytes to 202 (~100% of original) in 298ms = 0.00064645MB/s. ~256 total partitions merged to 2.
Mar 20 22:20:05 fomstap02 scylla: [shard 4] compaction - Compacted 1 sstables to [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-892-Data.db:level=0, ]. 101 bytes to 101 (~100% of original) in 298ms = 0.000323225MB/s. ~256 total partitions merged to 1.
Mar 20 22:20:05 fomstap02 scylla: [shard 6] compaction - Compacted 1 sstables to [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-894-Data.db:level=0, ]. 101 bytes to 101 (~100% of original) in 297ms = 0.000324313MB/s. ~256 total partitions merged to 1.
Mar 20 22:20:08 fomstap02 scylla: [shard 0] compaction - Compacting [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-888-Data.db:level=0, ]
Mar 20 22:20:08 fomstap02 scylla: [shard 4] compaction - Compacting [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-892-Data.db:level=0, ]
Mar 20 22:20:08 fomstap02 scylla: [shard 6] compaction - Compacting [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-894-Data.db:level=0, ]
Mar 20 22:20:09 fomstap02 scylla: [shard 0] compaction - Compacted 1 sstables to [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-896-Data.db:level=0, ]. 202 bytes to 202 (~100% of original) in 292ms = 0.000659734MB/s. ~256 total partitions merged to 2.
Mar 20 22:20:09 fomstap02 scylla: [shard 4] compaction - Compacted 1 sstables to [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-900-Data.db:level=0, ]. 101 bytes to 101 (~100% of original) in 291ms = 0.000331MB/s. ~256 total partitions merged to 1.
Mar 20 22:20:09 fomstap02 scylla: [shard 6] compaction - Compacted 1 sstables to [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-902-Data.db:level=0, ]. 101 bytes to 101 (~100% of original) in 291ms = 0.000331MB/s. ~256 total partitions merged to 1.
Mar 20 22:20:12 fomstap02 scylla: [shard 0] compaction - Compacting [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-896-Data.db:level=0, ]
Mar 20 22:20:12 fomstap02 scylla: [shard 6] compaction - Compacting [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-902-Data.db:level=0, ]
Mar 20 22:20:12 fomstap02 scylla: [shard 4] compaction - Compacting [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-900-Data.db:level=0, ]
Mar 20 22:20:13 fomstap02 scylla: [shard 0] compaction - Compacted 1 sstables to [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-904-Data.db:level=0, ]. 202 bytes to 202 (~100% of original) in 247ms = 0.000779928MB/s. ~256 total partitions merged to 2.
Mar 20 22:20:13 fomstap02 scylla: [shard 6] compaction - Compacted 1 sstables to [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-910-Data.db:level=0, ]. 101 bytes to 101 (~100% of original) in 247ms = 0.000389964MB/s. ~256 total partitions merged to 1.
Mar 20 22:20:13 fomstap02 scylla: [shard 4] compaction - Compacted 1 sstables to [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-908-Data.db:level=0, ]. 101 bytes to 101 (~100% of original) in 246ms = 0.000391549MB/s. ~256 total partitions merged to 1.
Mar 20 22:20:16 fomstap02 scylla: [shard 0] compaction - Compacting [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-904-Data.db:level=0, ]
Mar 20 22:20:16 fomstap02 scylla: [shard 6] compaction - Compacting [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-910-Data.db:level=0, ]
Mar 20 22:20:16 fomstap02 scylla: [shard 4] compaction - Compacting [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-908-Data.db:level=0, ]
Mar 20 22:20:17 fomstap02 scylla: [shard 4] compaction - Compacted 1 sstables to [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-916-Data.db:level=0, ]. 101 bytes to 101 (~100% of original) in 255ms = 0.00037773MB/s. ~256 total partitions merged to 1.
Mar 20 22:20:17 fomstap02 scylla: [shard 6] compaction - Compacted 1 sstables to [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-918-Data.db:level=0, ]. 101 bytes to 101 (~100% of original) in 255ms = 0.00037773MB/s. ~256 total partitions merged to 1.
Mar 20 22:20:17 fomstap02 scylla: [shard 0] compaction - Compacted 1 sstables to [/home/scylla/data/test/users2-8f70cdf00d3211e7923e000000000003/test-users2-ka-912-Data.db:level=0, ]. 202 bytes to 202 (~100% of original) in 262ms = 0.000735276MB/s. ~256 total partitions merged to 2.

**Comment by raphaelsc** [comment]
On Mon, Mar 20, 2017 at 11:27 PM, Junghyun Park <notifications@github.com>
wrote:

> *Installation details*
> Scylla version (or git commit hash):
>
> I started scylla with replace_address
> and Even though there is no write/read load, scylla does not stop
> compaction on the same file
>
Hi.


Which Scylla version are you using? What's your compaction strategy? Did
you change the default settings? For example, that could have happened due
to a min threshold of 1. I think you can figure out all your strategy
settings using "./bin/cqlsh -e 'describe <keyspace>.<column family>';"

**Comment by infordb** [comment]
@raphaelsc 
version : scylla-server-1.6.2-20170310.d41ba3b.el7.centos.x86_64
using default setting
schema 
CREATE TABLE test.users2 (
    user_id bigint PRIMARY KEY,
    country text,
    name text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 500
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

**Comment by infordb** [comment]
@raphaelsc 
**I tryed truncate , but fail..**
cqlsh:test> truncate test.users2;
ProtocolException: <ErrorMessage code=000a [Protocol error] message="Error during truncate: std::runtime_error (No such file or directory)">
cqlsh:test> 

**and...  Stop transport**

[root@fomstap04 users2-8f70cdf00d3211e7923e000000000003]# nodetool statusbinary
not running

Mar 21 13:14:32 fomstap04 scylla: [shard 0] storage_service - Shutting down communications due to I/O errors until operator intervention
Mar 21 13:14:32 fomstap04 scylla: [shard 0] storage_service - Stop transport: starts
Mar 21 13:14:32 fomstap04 scylla: [shard 0] gossip - My status = NORMAL
Mar 21 13:14:32 fomstap04 scylla: [shard 0] gossip - Announcing shutdown
Mar 21 13:14:32 fomstap04 scylla: [shard 0] storage_service - Node 10.240.29.80 state jump to normal
Mar 21 13:14:32 fomstap04 scylla: [shard 0] compaction - Compacting [/home/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-160-Data.db:level=0, /home/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-152-Data.db:level=0, /home/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-144-Data.db:level=0, /home/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-136-Data.db:level=0, ]
Mar 21 13:14:33 fomstap04 scylla: [shard 0] compaction - Compacted 4 sstables to [/home/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-168-Data.db:level=0, ]. 1250 bytes to 929 (~74% of original) in 290ms = 0.00305505MB/s. ~1024 total partitions merged to 1.
Mar 21 13:14:34 fomstap04 scylla: [shard 0] storage_service - Stop transport: stop_gossiping done
Mar 21 13:14:34 fomstap04 scylla: [shard 0] storage_service - Thrift server stopped
Mar 21 13:14:34 fomstap04 scylla: [shard 0] storage_service - CQL server stopped
Mar 21 13:14:34 fomstap04 scylla: [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
Mar 21 13:14:34 fomstap04 scylla: [shard 0] storage_service - messaging_service stopped
Mar 21 13:14:34 fomstap04 scylla: [shard 0] storage_service - Stop transport: shutdown messaging_service done
Mar 21 13:14:34 fomstap04 scylla: [shard 0] storage_service - stream_manager stopped
Mar 21 13:14:34 fomstap04 scylla: [shard 0] storage_service - Stop transport: shutdown stream_manager done
Mar 21 13:14:34 fomstap04 scylla: [shard 0] storage_service - Stop transport: auth shutdown
Mar 21 13:14:34 fomstap04 scylla: [shard 0] storage_service - Stop transport: done

**Comment by infordb** [comment]
@raphaelsc 
The strange thing is that the compact.log file is created automatically 
If I delete the file, it is recreated.

drwxr-xr-x. 2 scylla scylla 4096 Mar 21 13:31 commitlog
-rw-r--r--. 1 root   root      0 Mar 21 13:32 compact.log
drwxr-xr-x. 5 scylla scylla   62 Mar 21 13:30 data

**Comment by infordb** [comment]
Someone was constantly running a compaction script.
sorry,...
I will close this issue

**Comment by raphaelsc** [comment]
On Tue, Mar 21, 2017 at 1:53 AM, Junghyun Park <notifications@github.com>
wrote:

> Someone was constantly running a compaction script.
> sorry,...
> I will close this issue
>
I'm glad you found the root of the problem. BTW, I think it's worth opening
an issue for the problem you found with truncate. Truncate should've
worked, regardless.

**Comment by infordb** [comment]
I have reopened this issue for truncate problem....

**Comment by slivne** [comment]
@raphaelsc @infordb can you please explain the scenario better - is it related to replace_address or to compaction or to both

can you please provide the fool details of the scenario so we will be able to reproduce it and fix the bug (e.g. 1 start a cluster, 2. stop a node, 3. start a new node with replace address, 4. before the node finished bootstrapping run truncate ... - as an example if this is the scenario)

**Comment by infordb** [comment]
@raphaelsc @slivne 
I used 2 nodes for this test

0. May be, Someone was constantly running a compaction script on #2 node
1. #2  node down 
2. start #2 node with replace_address option after clearing all directory (data, commitlog)
3. run  truncate test.users2; on #2 node but failed


more question...
I use default setting , so may be compaction min threshold is  4
Why does scylla perform compaction even though there is only one sstable?

**Comment by raphaelsc** [comment]
On Tue, Mar 21, 2017 at 8:44 PM, Junghyun Park <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> @slivne
> <https://github.com/slivne>
> I used 2 nodes for this test
>
>    1. May be, Someone was constantly running a compaction script on #2
>    <https://github.com/scylladb/scylla/issues/2> node
>    2. #2 <https://github.com/scylladb/scylla/issues/2> node down
>    3. start #2 <https://github.com/scylladb/scylla/issues/2> node with
>    replace_address option after clearing all directory (data, commitlog)
>    4. run truncate test.users2; on #2
>    <https://github.com/scylladb/scylla/issues/2> node but failed
>
> more question...
> I use default setting , so may be compaction min threshold is 4
> Why does scylla perform compaction even though there is only one sstable?
>

major compaction, triggered by 'nodetool compact', isn't respecting min
threshold which is probably a fault. I'll check it. Out of curiosity, why
do you need this script? Scylla will automatically compact sstables for you
based on the strategy used (size tiered is the default one).

**Comment by infordb** [comment]
@raphaelsc it is just compacting script for test, It is mistake.

**Comment by infordb** [comment]
I reopend follow issue and this will be closed 
https://github.com/scylladb/scylla/issues/2226
