### ISSUE TITLE
Upgrade from 1.3 to 1.4 doesn't work.

### ISSUE THREAD

**Issue by porunov** [scylladb/scylla#2181]
*Installation details*
Scylla version: scylla-1.3.4-20161103.ef4332a.el7.centos.x86_64
Cluster size: 1 node
OS: CentOS 7
*Hardware details (for performance issues)*          Delete if unneeded
Platform: VM

Hello,

I am running scylladb 1.3.4. I tried to update it to 1.4 but it doesn't see newer versions.
I followed this tutorial:
http://docs.scylladb.com/upgrade/upgrade-guide-from-1.3-to-1.4-rpm/

when I try to update it shows:

```
# yum update scylla\* -y
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
 * base: centos.itt-consulting.com
 * extras: centos.itt-consulting.com
 * updates: centos.itt-consulting.com
No packages marked for update

```
if I try to install scylla it shows that the latest version 1.3.4 is installed. But it isn't the latest version.

```
# yum install scylla
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
 * base: centos.itt-consulting.com
 * extras: centos.itt-consulting.com
 * updates: centos.itt-consulting.com
Package scylla-1.3.4-20161103.ef4332a.el7.centos.x86_64 already installed and latest version
Nothing to do
```

Did I miss something?

Sincerely,
Alexandr

**Comment by porunov** [comment]
Had to use clean before update
`yum clean all`

Now it works

**Comment by avikivity** [comment]
`yum clean all` should be unneeded.

I think we should change

    [scylla]

to

    [scylla-x.y]

in the `.repo` files, so that yum doesn't think it already has the repository cached when a new `.repo` is installed.

/cc @penberg @syuu1228

**Comment by syuu1228** [comment]
@slivne This is not dist/ scripts bug, since *.repo is generated on Jenkins.
Can I change the jenkins jobs to produce .repo file to follow the new rule that @avikivity suggested?

**Comment by avikivity** [comment]
@penberg already did it for on repo

**Comment by avikivity** [comment]
Fixed.
