### ISSUE TITLE
question about Partition size

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2182]
*Installation details*
Scylla version (or git commit hash):scylla-1.6.1-20170218.2ea4da2.el7.centos.x86_64

I have questions about partition size
I estimated the partition size to be about 8.4MB by the following calculation.
But, The result of cfstat is as follows, why 16.15MB
Compacted partition minimum bytes: 6.71 KB
Compacted partition maximum bytes: 34.48 MB
Compacted partition mean bytes: 16.15 MB

Could you explain the difference in partition size?

formula : one partition size = total size / total count x row count per partition x 1024
![image](https://cloud.githubusercontent.com/assets/10610884/24135946/f08b871a-0e4f-11e7-90e9-4113fb8b4972.png)

![image](https://cloud.githubusercontent.com/assets/10610884/24135956/fdb0b820-0e4f-11e7-8016-bb4a1bd303e5.png)

**Comment by avikivity** [comment]
Spaced used is after compression, so the uncompressed partition size is actually ~32MB.  But since some partitions are spread across multiple sstables, there are more, smaller partitions.

Try issuing a major compaction and looking at the results.

**Comment by infordb** [comment]
@avikivity  
Does Compacted partition mean uncompressed partition size ?

**Comment by avikivity** [comment]
Yes.

**Comment by infordb** [comment]
@avikivity 
 You recommanded that partitions will be well below the 10MB 
Does 10MB mean uncompressed size?

**Comment by avikivity** [comment]
It's yet another measurement.  Partitions in cache can be larger than in sstables (compressed or uncompressed).  This is especially true if there are many small rows (like in your case).

We plan to remove that restriction soon (1.8) and then there will be no restriction on partition sizes.

**Comment by infordb** [comment]
@avikivity 
Partitions in cache above 10MB are not stored in cache  in scylla 1.3 version or now ??
Do you mean that it is possible to cache some part of the partitions in scylladb 1.8 version 

as you know, our use case is large partition  so I'm very worried about this part.

**Comment by avikivity** [comment]
Partitions above 10MB are not cached in Scylla 1.7 and below.  They will be cached in 1.8 and above.

**Comment by infordb** [comment]
@avikivity 
Is it right below size ?
a partition in compressed sstable < a partition uncompressed sstable < a partition in cache

**Comment by avikivity** [comment]
Usually, this is the case.

**Comment by infordb** [comment]
Thanak you avi 
I will close this issue.
