### ISSUE TITLE
Add MAX_WINDOW_SIZE_SECONDS to DTCS compaction settings

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2183]
*Installation details*
Allow DTCS compaction governance based on maximum window size rather than SSTable age.
Similar to https://issues.apache.org/jira/browse/CASSANDRA-10280

**Comment by tzach** [comment]
related: Do STCS in DTCS-windows
https://issues.apache.org/jira/browse/CASSANDRA-10276

**Comment by raphaelsc** [comment]
DTCS is deprecated so let's close this
