### ISSUE TITLE
Run Scylla Docker with experimental flag enabled

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2188]
*Installation details*
Add command line option to run Scylla docker with experimental enabled.
This will allow easier evaluation of the latest and greatest experimental features in Scylla.

**Comment by tzach** [comment]
@penberg worthwhile adding the new flag to https://github.com/scylladb/scylla/blob/master/docs/docker-hub.md

**Comment by penberg** [comment]
@tzach Yes, once we have an image that has it (i.e. 1.8-rc1).

**Comment by tzach** [comment]
@penberg can we backport this to 2.0 please?
it will help testing MV

**Comment by penberg** [comment]
@tzach There's no need to backport anything. The flag is in 2.0-rc1.

**Comment by tzach** [comment]
Can you please test with Docker 2.0-rc1?
The flag did not work for me

**Comment by penberg** [comment]
In what way did it not work for you?

```console
$ docker run --name some-scylla -d scylladb/scylla:2.0-rc1 --experimental 1
$ docker logs some-scylla |grep MATERIALIZED_VIEWS
INFO  2017-08-16 06:13:34,840 [shard 0] gossip - Feature MATERIALIZED_VIEWS is enabled
```

Are you sure you're running 2.0-rc1 version, and not latest, for example, which still points to 1.7.4?

**Comment by tzach** [comment]
My bad
I used 
```
--experimental
```

not 
```
--experimental 1
```
