### ISSUE TITLE
nodetool command alias : tablestats, tablehistograms

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2189]
*Installation details*
Scylla version (or git commit hash): 1.7

in C* 3.x introduce new name to old operations:
cfstats --> tablestats
cfhistograms --> tablehistograms

https://issues.apache.org/jira/browse/CASSANDRA-8872

**Comment by amnonh** [comment]
I think @elcallio  already added them and we support both options.
Did you check?

**Comment by tzach** [comment]
> I think @elcallio already added them and we support both options. Did you check?

No, but I should have.
Tested on 1.7rc1 and it works
Thanks
