### ISSUE TITLE
Procedure: Replacing a running node

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#219]
* Start the replacement node, integrate it into the cluster, and then decommission the old node.
add node (see above)
* Using the Host ID of the original node, decommission the original node from the cluster using the nodetool decommission command.

http://docs.datastax.com/en/cassandra/2.0/cassandra/operations/ops_replace_live_node.html

**Comment by slivne** [comment]
we do support replace-address and test it
we do support decommission and test it

we need to check that decommission of a node "not in the cluster" (after it was replaced) works - lets add a dtest for it

**Comment by asias** [comment]
Looking at the operation:

http://docs.datastax.com/en/cassandra/2.0/cassandra/operations/ops_replace_live_node.html

We support "Replacing a running node".

**Comment by slivne** [comment]
I am concerned that decomissioning a running replcaed node (step 4 - in what you have sent)

_4._ Using the Host ID of the original node, decommission the original node from the cluster using the nodetool decommission command. 

may cause streaming - in any case I think we need to have a test for it. (we do have a replace_address running node test - yet it does not do decomission of the old node.

**Comment by asias** [comment]
A running replaced node is just like a normal node. What are you concerned?

Please note, we can only replace_address a dead node. 

" (we do have a replace_address running node test - yet it does not do decomission of the old node."

I do not follow.

**Comment by slivne** [comment]
ok - closing
