### ISSUE TITLE
Scylla AMI: optimal support for EC2 i3 instance type

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2196]
*Installation details*
Scylla version (or git commit hash): 1.7 

- fix io_tune for i3
- new network devide
- move to amazon linux for better driver support

**Comment by l15k4** [comment]
Hey, I'm using the experimental AMI for i3 instances for about a month in production (1.7 rc3) and it all seems to go smoothly except for this happening very often : 
```
$ java -version
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000005e0c00000, 335544320, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 335544320 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/centos/hs_err_pid6140.log
```

https://pastebin.com/raw/8AMryB9K

When I enabled remote jmx control in the scylla-jmx service, I still couldn't access it from different nodes, so I'm very often unable to operate the cluster.

**Comment by tzach** [comment]
part of 2.0
