### ISSUE TITLE
Token information is not distributed correctly in cluster when  running nodes with smp

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#22]
Running a 3 node cluster with --smp 1 (with a single seed) token agreement can be validated using

10000/ui/#!/storage_service/get_token_endpoint

Running a 3 node cluster with --smp x (x>1, and a single seed) token agreement is not reached

10000/ui/#!/storage_service/get_token_endpoint
 does not hold all node token information

**Comment by tzach** [comment]
@slivne is this issue still open?

**Comment by asias** [comment]
@slivne I think this issue is resolved for a long time.
