### ISSUE TITLE
Procedure: Decommissioning a data center

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#220]
* Make sure no clients are still writing to any nodes in the data center.
* Run a full repair with nodetool repair. This ensures that all data is propagated from the data center being decommissioned.
* Change all keyspaces so they no longer reference the data center being removed.
* Run ```nodetool decommission``` on every node in the data center being removed.

http://docs.datastax.com/en/cassandra/2.0/cassandra/operations/ops_decomission_dc_t.html

**Comment by slivne** [comment]
@tzach  ALTER is post GA - we need to move this accordingly

**Comment by slivne** [comment]
I ran the procedure manually and it works on 1.2

We are lacking a dtest - something that we should add
