### ISSUE TITLE
Allow updating individual subfields of UDT

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2201]
*Installation details*
Scylla version (or git commit hash): 1.7

Store User-defined types in a non-frozen form, allowing individual fields to be updated and deleted in UPDATE statements

https://issues.apache.org/jira/browse/CASSANDRA-7423

**Comment by tzach** [comment]
related: https://issues.apache.org/jira/browse/CASSANDRA-13247

**Comment by slivne** [comment]
@avikivity / @tzach - do you consider this "urgent" we have a gap here with UDTs

**Comment by tzach** [comment]
@slivne as urgent as other minor Cassandra compatibility issues - as urgent as users ask for it

**Comment by avikivity** [comment]
Enhancement, removing backport candidate label.

**Comment by tzach** [comment]
@kbr- 
Apache Cassandra change CQLsh as part of this change
https://github.com/thobbs/cassandra/commit/4225900ca00c6045ccc45168a4d64b737e4d36f5
Should we do the same?

**Comment by kbr-** [comment]
@tzach 
You mean in this repo? https://github.com/scylladb/scylla-tools-java/
The changes are already there.

**Comment by tzach** [comment]
> You mean in this repo? https://github.com/scylladb/scylla-tools-java/
> The changes are already there.

Yes. Can you please point to the relevant commit? thanks

**Comment by kbr-** [comment]
I'll find the relevant commits as soon as I'm back from vacation (next Tuesday).

**Comment by kbr-** [comment]
@tzach 
https://github.com/scylladb/scylla-tools-java/commit/677230df694752c7ecf6d5459eee60ad7cf45ecf
is the commit.

Note: the cqlsh changes are only for UX (autocompletion), they're not required for the feature to work.
