### ISSUE TITLE
Per-partition LIMIT clause in cql

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2202]
*Installation details*
Scylla version (or git commit hash): 1.7

examples:

```
SELECT * FROM users PARTITION LIMIT 2;
```

https://issues.apache.org/jira/browse/CASSANDRA-7017

**Comment by avikivity** [comment]
Note, the infrastructure is mostly there (imlemented for Thrift), so 
should not be a lot of work.

**Comment by dvaldivia** [comment]
Was this implemented? Trying to use `PER PARTITION LIMIT` combined with an `IN` statement yields `syntax error...`  I can see this feature in the scylla [documentation](https://docs.scylladb.com/getting-started/dml/#limiting-results) but since there's a syntax failure I wonder if it works

**Comment by dvaldivia** [comment]
same error happening on `scylladb/scylla:3.0-rc4`
