### ISSUE TITLE
Creating user-defined function (UDF)

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2204]
Cassandra 2.2 allows users to define functions that can be applied to data stored in a table as part of a query result.

using a UDF:
```
SELECT key, abs(value) FROM my_table WHERE key IN (1, 2, 3);
```

Adding, removing UDF
```
CREATE OR REPLACE FUNCTION abs (val int) ...
DROP FUNCTION [IF EXISTS] abs
```
The same functionality will be useful in Scylla, not necessarily using Java as PL

**Comment by tzach** [comment]
User-Defined Aggregate Function (UDA) is a natural followup

**Comment by tzach** [comment]
In C* , UDF is disabled by default in cassandra.yaml
https://issues.apache.org/jira/browse/CASSANDRA-9404

**Comment by tzach** [comment]
UserType, TupleType and collections in UDFs
https://issues.apache.org/jira/browse/CASSANDRA-7563

**Comment by tzach** [comment]
User permissions for UDFs
https://issues.apache.org/jira/browse/CASSANDRA-7557

**Comment by tzach** [comment]
smallint, tinyint, date + time types in UDFs
https://issues.apache.org/jira/browse/CASSANDRA-9400

**Comment by bhalevy** [comment]
@espindola

**Comment by sanxore** [comment]
I'm looking forward to this feature :)

**Comment by bhalevy** [comment]
@espindola can this issue be closed with 1fe062aed4b1ceb5a97b4333ae6c1901854a7f39?

**Comment by espindola** [comment]
I think so. We have more specific issues to track the missing bits.

**Comment by bhalevy** [comment]
Cool, closing.
