### ISSUE TITLE
Consider compacting partition on the fly

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#2208]
*Installation details*
Scylla version (or git commit hash): master

To decrease partition size in memory, we should consider compacting it on the fly, namely, using the current tombstones to remove dead cells.

**Comment by tgrabiec** [comment]
Duplicate of https://github.com/scylladb/scylla/issues/652 ?

**Comment by duarten** [comment]
Dang, I have to get better at searching for issues before creating them.
