### ISSUE TITLE
Send write to replacing node

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#2211]
When a node is started to replace a dead node in the cluster with "replace_address" option, during the time the node is streaming from other nodes, the replacing node will not get writes. 

Related:
https://issues.apache.org/jira/browse/CASSANDRA-8523
https://issues.apache.org/jira/browse/CASSANDRA-12344

replacing node not get new write is the expected behavior until cassandra-3.11. 

The patch for 8523 is:
```
commit b39d984f7bd682c7638415d65dcc4ac9bcb74e5f
Author: Paulo Motta <pauloricardomg@gmail.com>
Date:   Fri Jun 17 21:09:31 2016 -0300

    Forward writes to replacement node when replace_address != broadcast_address

    Patch by Paulo Motta; reviewed by Richard Low for CASSANDRA-8523
```

**Comment by raphaelsc** [comment]
@asias can this now be closed after patch which make replacing nodes take writes?
