### ISSUE TITLE
gauge metrics are missing

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2221]
*Installation details*
Scylla version (or git commit hash): 1.5.2
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Scylla Docker
Metrics of type gauge are not exported to Prometheus

to reproduce:
```
sudo docker run --name some-scylla -d scylladb/scylla:1.5.2 --memory 1G --smp 1
scylla-grafana-monitoring/start-all.sh -v 1.5
```
Goto http://localhost:9090/graph?g0.range_input=1h&g0.expr=seastar_reactor&g0.tab=1 and look for gauge type metrics (you wont find any)

The problem does not exist with Scylla 1.6.2

**Comment by amnonh** [comment]
I just realized that the change that collect all metrics under the same value:
Seastar prometheus: send one MetricFamily per unique metric name

Breaks the prometheus logic
