### ISSUE TITLE
Counter value may rollover if reaching its max size

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#2225]
*Installation details*
Scylla version (or git commit hash): 1.7

A counter value cannot be updated with a number bigger than 2^63-1, however, In case a counter value reaches the max size value 2^63-1 and then being updated with + 1, its value will rollover and become negative number.

For example:
CREATE KEYSPACE ks WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
CREATE TABLE ks.cf (pk INT PRIMARY KEY,cnt COUNTER);
cqlsh> UPDATE ks.cf SET cnt = cnt + 9223372036854775807 WHERE pk = 1;
cqlsh> select * from ks.cf 
   ... ;

 pk | cnt
----+---------------------
  1 | 9223372036854775807

(1 rows)
cqlsh> UPDATE ks.cf SET cnt = cnt + 1 WHERE pk = 1;
cqlsh> select * from ks.cf  ;

 pk | cnt
----+----------------------
  1 | -9223372036854775808

BTW, the same thing will happen in Cassandra.

**Comment by slivne** [comment]
@pdziepak / @avikivity / @tzach thoughts on how we should handle this

**Comment by kongove** [comment]
I just saw the problem. It's worth to verify the number before real updating counter, and raise error.

**Comment by penberg** [comment]
@kongove But you also say that Cassandra has the same behaviour, no?

**Comment by penberg** [comment]
Oh, it was @roydahan that said that. But if that's the case, why do we have a bug open about this?

**Comment by slivne** [comment]
We want to be better unless rollovwr behaviour is part ofnthe comtractbwe
qant to maintain

**Comment by pdziepak** [comment]
For a general case there is nothing we can do. Counter shards are updated independently and concurrently on all replicas and without additional coordination there is no telling whether there is overflow.

As long as we don't have counter cache we could make leaders check if the update they are applying causes overflow according to their knowledge of the counter state, but I'm not sure if this will do anything useful in real workloads.

**Comment by avikivity** [comment]
It's not a real problem. `long` variables in Java will exhibit the same behavior.
