### ISSUE TITLE
While upgrading Scylla cluster from 1.6.0 to 1.6.2, one node died (my fault) -> Replace node procedure failed (gossip issue)

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla#2229]
Hi Asias,

**I have a 3 node cluster on GCE (RHEL7.3) running version 1.6.0. I wanted to upgrade the cluster to 1.6.2, but one I node died (10.240.0.26) due to a mistake I did.**

[tomer@tomer-4cpu-15gb-rhel7-3 ~]$ nodetool status
Datacenter: datacenter1
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens  Owns    Host ID                               Rack
DN  10.240.0.26  ?          256     ?       b0a351ca-1f14-4fb2-8976-fffd9a88b452  rack1
UN  10.240.0.27  52.69 MB   256     ?       fd730e0f-78ee-4b87-8079-530552822ac8  rack1
UN  10.240.0.28  63.02 MB   256     ?       6046387e-6e1c-41b5-8a42-0060b4939aa6  rack1

**I did the following steps:**

1. Deleted the VM from GCE -> deployed a new VM on GCE (same IP: 10.240.0.26)
2. Upgraded the other 2 nodes to 1.6.2 properly -> successful
3. Performed the replace node procedure:
   - Install Scylla
   - Edit the scylla.yaml file with correct: cluster_name, seeds, listen_address, rpc_address
   - Added the following to the scylla.yaml file: replace_address: 10.240.0.26
   - Run scylla_setup script
   - Reboot node
   - After reboot - I ran: sudo systemctl start scylla-server **(no indication of an error, got prompt          back - that's also an issue)**
   - ran ps -elf | grep -i scylla and saw process is not running

**Tried it also with a new 4th VM on GCE (IP 10.240.0.29) to replace 10.240.0.26 that died, and got the same error.**

**Start Scylla failed with the following error from journalctl -xe:**
Mar 27 09:52:28 tomer-4cpu-15gb-rhel7-1 scylla[1593]:  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Cannot replace_address 10.240.0.26 because it doesn't exist in gossip)

**Did flush on all nodes "iptables -F" -> Tried to start scylla on the new node -> still same error**

**Yaml file from all nodes:**

**From the new replacement (that failed to be added) 10.240.0.26:**
[tomer@tomer-4cpu-15gb-rhel7-1 ~]$ cat /etc/scylla/scylla.yaml | grep -v "#" | grep -v "^[[:space:]]*$"
cluster_name: 'Tomer Cluster'
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "10.240.0.27,10.240.0.28"
replace_address: 10.240.0.26
listen_address: 10.240.0.26
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
endpoint_snitch: SimpleSnitch
rpc_address: 10.240.0.26
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
api_ui_dir: /usr/lib/scylla/swagger-ui/dist/
api_doc_dir: /usr/lib/scylla/api/api-doc/

**From 10.240.0.27:**
[tomer@tomer-4cpu-15gb-rhel7-2 ~]$ cat /etc/scylla/scylla.yaml | grep -v "#" | grep -v "^[[:space:]]*$"
cluster_name: 'Tomer Cluster'
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "10.240.0.27,10.240.0.28"
listen_address: 10.240.0.27
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
endpoint_snitch: SimpleSnitch
rpc_address: 10.240.0.27
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
api_ui_dir: /usr/lib/scylla/swagger-ui/dist/
api_doc_dir: /usr/lib/scylla/api/api-doc/

**From 10.240.0.28:**
[tomer@tomer-4cpu-15gb-rhel7-3 ~]$ cat /etc/scylla/scylla.yaml | grep -v "#" | grep -v "^[[:space:]]*$"
cluster_name: 'Tomer Cluster'
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "10.240.0.27,10.240.0.28"
listen_address: 10.240.0.28
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
endpoint_snitch: SimpleSnitch
rpc_address: 10.240.0.28
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
api_ui_dir: /usr/lib/scylla/swagger-ui/dist/
api_doc_dir: /usr/lib/scylla/api/api-doc/

**Added to all nodes (10.240.0.26/27/28):**
SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level trace --logger-log-level gossip=debug --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix"
Start Scylla on the replacement node (10.240.0.26) -> logs from all 3 nodes attached.

[log_for_Asias_10.240.0.26.txt](https://github.com/scylladb/scylla/files/874624/log_for_Asias_10.240.0.26.txt)
[log_for_Asias_10.240.0.27.txt](https://github.com/scylladb/scylla/files/874626/log_for_Asias_10.240.0.27.txt)
[log_for_Asias_10.240.0.28.txt](https://github.com/scylladb/scylla/files/874625/log_for_Asias_10.240.0.28.txt)

**Comment by tomer-sandler** [comment]
I deployed a new VM (10.240.0.23) from scratch, not via clone.
Installed Scylla 1.6.2
Edit the yaml file with the proper values for cluster_name, seeds, listen_address, rpc_address (including replace_address: 10.240.0.26)
Run scylla_setup
Reboot node
Start scylla fails with the same error

**Status:**
2 VMs that were upgraded successfully from 1.6.0 -> 1.6.2 (10.240.0.27/28) works.
3 VMs, 2 cloned (10.240.0.26/29) + 1 deployed from scratch (10.240.0.23) clean installed with 1.6.2 (with replace_address: 10.240.0.26) -> **FAIL** to join the cluster due to same gossip error.

**Comment by slivne** [comment]
this is not a scylla bug - it happens sometimes on gce.

**Comment by gleb-cloudius** [comment]
What happens sometimes on gce?

**Comment by slivne** [comment]
closing this issue we are testing replace node procedure - and this did not reproduce
