### ISSUE TITLE
('commit_failure_policy': 'die') node is still running with chmod 000

### ISSUE THREAD

**Issue by abvgedeika** [scylladb/scylla#2231]
*Installation details*
Scylla version (or git commit hash): https://github.com/scylladb/scylla/commit/27c42359bc72f5fbc9b6f43b817d78748a85d1b5
Cluster size: 1
OS: Ubuntu16 

steps:
1) cluster with 1 node 'commit_failure_policy': 'die'
2) set chmod 000 for commitlogs
d--------- 2 andrei andrei 4096 Mar 29 09:05 commitlogs
3) load some data

actual result: node is still alive

expected result: node shut down 
https://github.com/scylladb/scylla/blob/master/conf/scylla.yaml#L299
( die: shut down gossip and Thrift and kill the JVM, so the node can be replaced.)

test https://github.com/scylladb/scylla-dtest/blob/master/commitlog_test.py#L373
```
 def die_failure_policy_test(self):
        """ Test the die commitlog failure policy """
        self.prepare(configuration={
            'commit_failure_policy': 'die'
        })

        self._provoke_commitlog_failure()
        failure = self.node1.grep_log("\[shard 0\] commitlog - Exception in segment reservation\: "
                                      "storage_io_error \(Storage I/O error\: 13\: Permission denied\)")
        debug(failure)
        self.assertTrue(failure, "Cannot find the commitlog failure message in logs")
        self.assertFalse(self.node1.is_running(), "Node1 should not be running") #BUG!
```

it works in C*

**Comment by slivne** [comment]
@abvgedeika once #2246 is closed lets not run these tests.
