### ISSUE TITLE
duplicated fstrim cronjob

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#2233]
We introduced fstrim cronjob / system timer unit, but both Ubuntu and CentOS already has similar things.
On Ubuntu, it even enabled by default, so we may run fstrim too much, that can degrade Scylla performance.

So we should switch to distribution standard one when it's possible.
Here's a list what should we do on each distributions:
* CentOS/RHEL/Fedora
 It has fstrim.timer that can fstrim for all mounted devices, but disabled by default. Need to enable by scylla_setup.
* Ubuntu 16.04
 It has /etc/cron.d/fstrim that can fstrim for all mounted devices, enabled by default.
* Ubuntu 14.04
 It has /etc/cron.d/fstrim, but it only runs on Intel and Samsung SSD drives due to bug occurs on other SSDs (https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1259829).
 It also ignores RAID devices.
 We can run scylla_fstrim for this distribution, but maybe it's not safe when SSD is not Intel/Sumsung.
* Debian
 It does not installs fstrim script, we can use scylla_fstrim.

**Comment by syuu1228** [comment]
@avikivity What do you think about Ubuntu 14.04, should we try to fstrim unconditionally or don't do that for safety

**Comment by avikivity** [comment]
Since we expect our users to use modern enterprise drives, I think we can enable fstrim unconditionally.

If it were only 14.04 I'd say let the distribution do what it likes, but it's also debian, so we have to ship scylla_fstrim anyway.

**Comment by syuu1228** [comment]
@avikivity It's bit difficult decide, since Debian almost has its one but never enabled.
Describing Debian 8 situation more specifically, it actually has fstrim.timer / fstrim.service but it's under document directory, not installed as systemd unit.
If we decided to drop scylla_fstrim, we still can install them from scylla_setup..

```
root@ef83c5c58b84:/# dpkg -L util-linux|grep fstrim
/sbin/fstrim
/usr/share/man/man8/fstrim.8.gz
/usr/share/bash-completion/completions/fstrim
/usr/share/doc/util-linux/examples/fstrim.service
/usr/share/doc/util-linux/examples/fstrim.timer
root@ef83c5c58b84:/# 
```
