### ISSUE TITLE
CentOS .rpm build failing because rpmbuild tries to compile perftune.py as python2 script

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#2235]
Since CentOS7 / RHEL7 only supports python2, rpmbuild tries to compile all .py to .pyc using python2.
It done by brp-python-bytecompile, on %__os_install_post macro in /usr/lib/rpm/redhat/macros.
To prevent compile, we may able to redefine the macro, but it's bit dirty way.
Another workaround is renaming python3 script to without .py extension.
Currently dist/common/scripts/*.py are written in python2, not to causing this issue.

```
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
Compiling /home/syuu/scylla.27/build/rpmbuild/BUILDROOT/scylla-666.development-0.20170329.92e759a.el7.centos.x86_64/usr/lib/scylla/perftune.py ...
  File "/usr/lib/scylla/perftune.py", line 82
    print("Restarting irqbalance: going to ban the following IRQ numbers: ", end='')
                                                                                ^
SyntaxError: invalid syntax

error: Bad exit status from /var/tmp/rpm-tmp.km4Uy7 (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.km4Uy7 (%install)
```

**Comment by syuu1228** [comment]
Or, all python3 script can be name as ".py3".

**Comment by avikivity** [comment]
Better to just disable it:

https://www.redhat.com/archives/rpm-list/2007-November/msg00020.html
