### ISSUE TITLE
scylla can't start  after upgrade from 1.5 to 1.6

### ISSUE THREAD

**Issue by fooltux** [scylladb/scylla#2239]
Mar 30 20:26:35 hostname scylla: EAL: Failed to mmap 2 MB hugepages
Mar 30 20:26:35 hostname scylla: PANIC in rte_eal_init():
Mar 30 20:26:35 hostname scylla: Cannot init memory
Mar 30 20:26:35 hostname scylla: 10: [[(nil)]]
Mar 30 20:26:17 hostname scylla: EAL: Detected lcore 26 as core 5 on socket 0
Mar 30 20:26:17 hostname scylla: EAL: Detected lcore 27 as core 5 on socket 1
Mar 30 20:26:17 hostname scylla: EAL: Detected lcore 28 as core 6 on socket 0
Mar 30 20:26:17 hostname scylla: EAL: Detected lcore 29 as core 6 on socket 1
Mar 30 20:26:17 hostname scylla: EAL: Detected lcore 30 as core 7 on socket 0
Mar 30 20:26:17 hostname scylla: EAL: Detected lcore 31 as core 7 on socket 1
Mar 30 20:26:17 hostname scylla: EAL: Support maximum 128 logical core(s) by configuration.
Mar 30 20:26:17 hostname scylla: EAL: Detected 32 lcore(s)
Mar 30 20:26:17 hostname scylla: EAL: No free hugepages reported in hugepages-1048576kB
Mar 30 20:26:35 hostname systemd-coredump: Process 23108 (scylla) of user 499 dumped core.#012#012Stack trace of thread 23108:#0
12#0  0x00007fe87863c5f7 raise (libc.so.6)#012#1  0x00007fe87863de28 abort (libc.so.6)#012#2  0x000000000046ae22 n/a (scylla)#012#
3  0x00000000007693ad n/a (scylla)#012#4  0x00000000005b3f63 n/a (scylla)#012#5  0x000000000053e9eb n/a (scylla)#012#6  0x00000000
005ac8fc n/a (scylla)#012#7  0x0000000000473bfe n/a (scylla)#012#8  0x00007fe878628b15 __libc_start_main (libc.so.6)#012#9  0x0000
0000004ddd7f n/a (scylla)
Mar 30 20:26:35 hostname scylla: EAL: VFIO modules not all loaded, skip VFIO support...
Mar 30 20:26:35 hostname scylla: EAL: Setting up physically contiguous memory...
Mar 30 20:26:35 hostname scylla: EAL: map_all_hugepages(): open failed: Permission denied
Mar 30 20:26:35 hostname scylla: EAL: Failed to mmap 2 MB hugepages
Mar 30 20:26:35 hostname scylla: PANIC in rte_eal_init():
Mar 30 20:26:35 hostname scylla: Cannot init memory
Mar 30 20:26:35 hostname scylla: 10: [[(nil)]]

**Comment by gleb-cloudius** [comment]
Are you using DPDK?

**Comment by fooltux** [comment]
@gleb-cloudius  yes   I'm using DPDK

**Comment by avikivity** [comment]
Do you have hugepage reservation on your kernel command line?

Rebooting the node may help.

@syuu1228 vfio support will eliminate the need for hugetlbfs

**Comment by syuu1228** [comment]
@avikivity VFIO seems requires to enable VT-d/AMD IOMMU on the machine's firmware, what should seaster/scylla do when IOMMU doesn't enabled and DPDK mode requested?
Is it okay to cause error and refuse working? Or tries to use existing UIO driver mode?

**Comment by avikivity** [comment]
@syuu1228 see `VFIO_NOIOMMU_IOMMU` in recent kernels.  dpdk supports it.  I think it's okay to require a new kernel for dpdk, it's better than the complexity of configuring hugepages (we can provide a 4.x kernel for CentOS).

**Comment by fooltux** [comment]
@avikivity  I'm using centos 7.2 and the kernel version is 3.10.0-327.el7.x86_64

**Comment by avikivity** [comment]
Stale bug, please update if the problem still exists. Note that DPDK is not supported for production.
