### ISSUE TITLE
Add duration type

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2240]
Cassandra added `duration` type in 3.10
```
INSERT INTO RiderResults (rider, race, result) VALUES ('Christopher Froome', 'Tour de France', 89h4m48s);
INSERT INTO RiderResults (rider, race, result) VALUES ('BARDET Romain', 'Tour de France', PT89H8M53S);
INSERT INTO RiderResults (rider, race, result) VALUES ('QUINTANA Nairo', 'Tour de France', P0000-00-00T89:09:09);
```

https://issues.apache.org/jira/browse/CASSANDRA-13174

**Comment by hakuch** [comment]
I've finished porting the underlying `Duration` type, including its representation, parsing, and pretty-printing.

However, it looks like this feature was introduced in the 3.10 release, so we may want to wait before supporting the new type in CQL.

I could prepare a patch for merging the support for the underlying type and we could revisit this in the future.

Do you have any input, @tzach?

**Comment by hakuch** [comment]
For reference, the patch which adds this feature is discussed [here](https://issues.apache.org/jira/browse/CASSANDRA-11873).

**Comment by avikivity** [comment]
By itself the fact it was added to Cassandra only in 3.10 shouldn't block us.

But it looks like duration can't be represented in cql binary protocol < v5, and we only support v4 so far.

**Comment by penberg** [comment]
@avikivity CQL protocol v5 is work-in-progress, hidden behind some feature flag in the drivers. We can definitely add support for that in ScyllaDB for the duration type.

**Comment by tzach** [comment]
@hakuch what driver can work with this new type? (and v5)?

**Comment by hakuch** [comment]
@tzach, the Datastax Java driver version [3.2.0](https://www.datastax.com/dev/blog/datastax-java-driver-3-2-0-released) appears to support it (as well as additional functionality related to `duration` that we do not yet support). `cqlsh` should also support it. I'm not sure about the status of all available drivers, however.

Does that answer your question?

**Comment by tzach** [comment]
Yes it does. Thanks
