### ISSUE TITLE
Http should count errors not throwing weird log messages

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#2242]
Http should count errors when failing to read or write an http message, this should replace the behaviour of silently ignoring it or ignore the exception and end up with cryptic error message for unhandled future exception ignored.

**Comment by tzach** [comment]
Why not generating a clearer error message (with or without the counter)?

**Comment by amnonh** [comment]
On Thu, Mar 30, 2017 at 4:43 PM, Tzach Livyatan <notifications@github.com>
wrote:

> Why not generating a clearer error message (with or without the counter)?
>
There are two things that we should do anyhow,
* catch all exceptions
* count errors.

We can also generate errors, we currently do not do it on the incoming path,
this is something that we can always add, in parallel to this patch, not
sure that we need to,
we saw that it only generate noise.

**Comment by penberg** [comment]
Fixed by b8e4113dba0d04756d142de7e8d94bf8921b69c9, which contains Seastar commit https://github.com/scylladb/seastar/commit/d468ea5c627aa210b41cec522b3bc12c7cc0c3d2
