### ISSUE TITLE
storage_service api should support metrics load

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#2245]
The load attribute can be called from two APIs storage_service/load and storage_service/metric/load.
That follows C* jmx API.

currently only storage_service/load is implemented, there's no reason why not to support both.

**Comment by slivne** [comment]
@amnonh not clear why do we need 2 apis for the same thing - can you elaborate - in general there should be a single api unless there is a difference between the two.

does Cassandra have two different api's ?

**Comment by amnonh** [comment]
We have two APIs because cassandra has two.
You can see the patch I've sent for it, there are two options, one, remove one of the APIs and change the JMX accordingly, or add an implementation.

Add an implementation is simple, we can add a patch in the JMX to use a single API for both options and then remove the unused one, but we should do it in that order.
