### ISSUE TITLE
ORDER BY should allow skipping equality-restricted clustering columns

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2247]
Scylla required all clustering keys to be part of the ordering, even if they are already fixed by WHERE

Reproduce:
```
CREATE KEYSPACE mykeyspace WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
use mykeyspace ;
CREATE TABLE foo (a int, b int, c int, d int, PRIMARY KEY (a, b, c));
SELECT * FROM foo WHERE a = 0 AND b = 0 ORDER BY c ASC;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Order by currently only support the ordering of columns following their declared order in the PRIMARY KEY"
SELECT * FROM foo WHERE a = 0 AND b = 0 ORDER BY b ASC, c ASC;

 a | b | c | d
---+---+---+---

(0 rows)

```
Since b is restricted by an equality restriction, it does not have to be in the ORDER BY clause.

Cassandra correlating ticket: https://issues.apache.org/jira/browse/CASSANDRA-10271

**Comment by altanozlu** [comment]
currently i am facing this problem

**Comment by nyh** [comment]
It should be easy to write a reproducing test for this issue, but note that since Cassandra already fixed this problem a year ago, they have a unit test for it `test/unit/org/apache/cassandra/cql3/validation/operations/SelectOrderByTest.java ` (which I didn't yet translate to Python).

**Comment by nyh** [comment]
Changed label to Cassandra 4.x compatibility - as https://issues.apache.org/jira/browse/CASSANDRA-10271 says, this was deemed and "improvement" and only reach Cassandra 4.

**Comment by cvybhu** [comment]
:+1: I will take a look at it

**Comment by avikivity** [comment]
Not a regression or serious bug, not backporting.

**Comment by jmcanterafonseca-iota** [comment]
@avikivity in which version of Scylla is this fix going to appear?

**Comment by avikivity** [comment]
5.0
