### ISSUE TITLE
Missing metrics in scylla-dash-io-per-server dashboard

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2258]
*Installation details*
Scylla version (or git commit hash): 1.6.3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AMI

When looking at https://github.com/scylladb/scylla-grafana-monitoring dashboard [scylla-dash-io-per-server.1.6](https://github.com/scylladb/scylla-grafana-monitoring/blob/master/grafana/scylla-dash-io-per-server.1.6.json)
The bottom 6 dashboards have no data:
* scylla_io_queue_total_operations_streaming_write
* scylla_io_queue_derive_streaming_write
* scylla_io_queue_delay_streaming_write
* scylla_io_queue_total_operations_streaming_read
* scylla_io_queue_derive_streaming_read

The problem might not be in Scylla, rather in the sync between metrics name in Scylla and the dashboard

![screenshot from 2017-04-05 20-16-43](https://cloud.githubusercontent.com/assets/170200/24717959/ef7d11a6-1a3c-11e7-8afc-46f842699d71.png)

**Comment by tzach** [comment]
@amnonh can you please take a look?

**Comment by amnonh** [comment]
please assigned to me

**Comment by amnonh** [comment]
BTW for streaming, you only see data when there are streaming in progress

**Comment by tzach** [comment]
> BTW for streaming, you only see data when there are streaming in progress 

Make sense, maybe its not a bug at all
I will retest

**Comment by tzach** [comment]
OK, charts are active when there is streaming.
There is another general problem:  once streaming stops, the graphs continue to show the last value for 5 min.
