### ISSUE TITLE
Release process: create AMI in more regions

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2259]
Users are looking for Scylla in other regions than the default [3 US regions we use](http://www.scylladb.com/download/#EC2)
Starting with `eu-central-1`.

Need more regions? use the comments to let us know!

**Comment by l15k4** [comment]
`eu-west-1`

**Comment by penberg** [comment]
@l15k4 @tzach I added the AWS region to our AMI promotion scripts, which means that all new releases will generate that AMI. Let's keep the issue open until we have a verified, working AMI in that region.

**Comment by lukasz-golebiewski** [comment]
@penberg Were the new AMIs generated for 1.7.2?

**Comment by penberg** [comment]
@lukasz-golebiewski Yes, but please note that I have not tested it:

```
eu-west-1: ami-28628151
```

/cc @tzach

**Comment by tzach** [comment]
@lukasz-golebiewski I just tested and the Ireland AMI works like a charm and taste like Guinness
Its now part of the http://www.scylladb.com/download/amazon/ for everyone to use.

**Comment by lukasz-golebiewski** [comment]
Thanks a lot!
