### ISSUE TITLE
Reduce impact of permission checks on queries

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2262]
We've seen high load on system_auth tables in issue #2178.

There is a permission cache which helps avoiding system_auth queries, which in general are remote queries. The cache expires periodically, every 2 seconds by default. When entries expire, they are removed from the cache. Each concurrent request which finds the entry missing will issue a separate query. We could issue only one, with later requests waiting on the first one to complete.

Another problem is that refreshing is done in the foreground, it adds latency to CQL requests. It would be better to do it in the background. One solution would be to replicate system_auth tables to all nodes (#1796) and install triggers on relevant tables which would update permission cache on local node.

**Comment by slivne** [comment]
"Another problem is that refreshing is done in the foreground, it adds
latency to CQL requests. It would be better to do it in the background." So
that once 2 seconds we will reread the info and once we processed it -
replace the cache with an updated one ?

If we do that it will remove the issue of having parallel requests finding
the cache invalid and rereading the info - no ?

**Comment by avikivity** [comment]
If we have triggers, the cache won't be a cache but a copy of the data 
(that perhaps lags a bit).

**Comment by slivne** [comment]
Yet we domt have triggers and dont have them on the plan so tomek's
suggestion todo that in rhe background seems as a good solution till we do

On Apr 6, 2017 5:50 PM, "Avi Kivity" <notifications@github.com> wrote:

If we have triggers, the cache won't be a cache but a copy of the data
(that perhaps lags a bit).

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/scylladb/scylla/issues/2262#issuecomment-292198692>,
or mute
the thread

**Comment by tgrabiec** [comment]
2017-04-06 16:48 GMT+02:00 Shlomi Livne <notifications@github.com>:

> "Another problem is that refreshing is done in the foreground, it adds
> latency to CQL requests. It would be better to do it in the background." So
> that once 2 seconds we will reread the info and once we processed it -
> replace the cache with an updated one ?
>

Yes


>
> If we do that it will remove the issue of having parallel requests finding
> the cache invalid and rereading the info - no ?
>

Yes, this solution covers the first one, provided we would pre-populate the
cache and the cache would remain always valid.

**Comment by tgrabiec** [comment]
It could be a cache. A trigger could only make sure that information in
cache is in sync, but we still could have eviction policies, or simply not
populate with entries which were not there. They would be populated on
first access.

2017-04-06 16:50 GMT+02:00 Avi Kivity <notifications@github.com>:

**Comment by avikivity** [comment]
That's true.  Still, an eviction in a running load could cause tons of requests to serialize on the cache repopulation, which could result in a disk access, and a hiccup for the load.

**Comment by tgrabiec** [comment]
I was thinking about size-based eviction policy with an LRU to put a sane cap on cache size, in case permission table gets large, but not all of it is going to be needed at the same time. Maybe that's not going to be a problem in practice, and we could get away with no eviction, I'm not sure.

**Comment by tgrabiec** [comment]
There may be a problem of ensuring that nodes don't use stale permissions with the trigger solution. Replication may fail, we don't repair automatically. Maybe we should enforce CL=ALL for permission updates. Maybe that's what we should do regardless of which solution we implement.

**Comment by slivne** [comment]
If a node ia.sown cl=all will not work - we nees to be able.to update
authorization even of a mode isndown in my view

**Comment by slivne** [comment]
I am in favor of starting simple:

- use a background process timebased that refreshes the information and exchanges the cache

defer:
- triggers (once we have that we can change the impl)
- not evict / limit space

**Comment by tgrabiec** [comment]
As far as implementation effort is concerned, the internal (not CQL) support for triggers should be trivial.

Note that the "simple" option you mention has its own downside. It implies frequent full scans of system_auth from all nodes in the cluster, even when permissions don't change.

And the problem of ensuring consistency of auth changes still remains. I think that what admins could reasonably expect form auth changes is that any action which is started after permission change was ACKed will see the effects of that change. For example, if they revoke a permission for given user, that user won't be able to make any actions any more. Currently that's not the case unless you use CL=ALL. The permission refresh uses CL=LOCAL_ONE, and if permission update uses CL != ALL then it's possible that the change will be ACKed, but some replicas will keep using stale permissions for unknown period of time, if replication failed to some of the auth replicas.

> 
> If a node is down cl=all will not work - we need to be able to update
> authorization even of a mode is down in my view

We could use a special kind of CL=ALL for permissions, which unlike the regular one always tries to replicate to all live nodes. So permissions would still be changed on as many nodes as possible.

It's an administrative action, so maybe it's ok if it errors out when replication fails. When admin sees the error he can go fix the bad node and then retry.

**Comment by slivne** [comment]
> As far as implementation effort is concerned, the internal (not CQL) support for triggers should be trivial.

Ok - so I am not against that - just to confirm we need a distributed trigger, even in the case the node does not store the information in the auth sstables, so all nodes will know to refetch the info.

**Comment by slivne** [comment]
Lets start with doing the background update of the cache and differ the more optimal trigger based one.

**Comment by vladzcloudius** [comment]
Triggers may not replace the timely refresh because trigger (if it's going to be a one time event and not something that is **100% promised to eventually happen**) may get lost/fail just like a mutation write on a specific replica. However as an optimization this would do nicely indeed.

I'd like to give a short summary of the current status of this code and ask a few questions about the things are not obvious to me:
 * RF by default is 2, while recommend (here I rely on what Glauber told me) to always set it to RF=ALL. We recommend to actually set the RF to the total number of all Nodes in the cluster while we do have an `everywhere_replication_strategy`. Why don't we:
   1) Set this strategy by default.
   2) Recommend to set this strategy.

Is it because it's not tested enough? 
I'll further assume that RF=ALL
 * A default superuser ("cassandra") is created with the CL=ONE (`auth::setup()`). But then
 * CREATION/DELETION/QUERYING the users is performed with the following CL:
   * User 'cassandra': QUORUM - this is kinda strange. If one boots up a new cluster ('cassandra' will be created with CL=ONE), then creates a different superuser, deletes a 'cassandra' user and creates it again - now it will be created with the CL=QUORUM.
   * All other users: LOCAL_ONE. Why 'cassandra' is created with a ONE and others with a LOCAL_ONE?
 * Writes are performed with CL=ONE (`default_authorizer::modify()`) or with a LOCAL_ONE when we create/delete a new user different from the 'cassandra' user.
 * Reads are performed (by the cache) with CL=LOCAL_ONE (`default_authorizer::authorize()`) or with CL=QUORUM when the 'cassandra' user queries an user info about itself from the `users` CF.

So, as you may notice, most of the writes and reads are performed with an almost the lowest CL - (LOCAL_) ONE. (The lowest would be CL.ANY).

Don't you think it's a bit risky? This may easily cause some Nodes to stuck for a long time with old credentials: consider a Node that was down when the credentials were updated and then went up. Without hints it will have an old data till repair and, if memory serves me well, with RF=ALL and CL=ONE we will always read from the local store. Read repair would eventually bring the new credentials but it may take quite a long time...

Wouldn't it be safer to always perform both read and write operations above with CL=QUORUM (provides READs are performed in the background of course)?

As for a special CL=ALL like Tomek is proposing, it's also could be a problem: in the example above, the write with a CL=ALL* will succeed but then the Node will go UP again and will have old credentials, again, till repair or a read-repair. 

Reading with CL=QUORUM on the other hand will give a (relatively) strong guarantee that the new credentials will eventually (and quite quickly) make it to each Node's auth cache.

**Comment by slivne** [comment]
I don't think we should do rf=all - cassandra had that in cassandra 2.0 and
moved from it in cassandra 2.1

http://stackoverflow.com/questions/25891353/replication-factor-to-use-for-system-auth

Searching a bit it seems that one of the reasons this was changed was that
to maintain the auth was challenging - e.g. trying to repair the
system_auth with high RF is challanging.

I think one of the items that needs to be considered is when / how is the
information is fetched.

If the information is fetched when a request is received - the request is
blocked - till the information is retrieved -  you are adding latency -
running with CL=QUORUM can have a reconcillation and a write back - so the
latency will be high.

In our case the idea is to populate the cache in the background - so in
this case we can read with CL=QUORUM and if should not block the progress
of received requests (aside of adding some load) - so I think its safe to
use CL=QUORUM in our case.

**Comment by vladzcloudius** [comment]
On 04/27/2017 02:34 PM, Shlomi Livne wrote:
> I don't think we should do rf=all - cassandra had that in cassandra 
> 2.0 and
> moved from it in cassandra 2.1
>
> http://stackoverflow.com/questions/25891353/replication-factor-to-use-for-system-auth
>

I tried to read their threads too but I couldn't find where they give 
any proper reason why not to.
Here are the threads I read:

https://issues.apache.org/jira/browse/CASSANDRA-12629
https://issues.apache.org/jira/browse/CASSANDRA-826

> Searching a bit it seems that one of the reasons this was changed was that
> to maintain the auth was challenging - e.g. trying to repair the
> system_auth with high RF is challanging.

We are talking about a quite critical piece of data - users credentials. 
IMHO it doesn't matter how challenging it is in this case - the 
robustness here is above all. Besides the data is quite small so, how 
challenging it might be? ;)
And if we use CL=QUORUM the data is going to repair itself quite well 
too, so, it would become even less challenging.

**Comment by tgrabiec** [comment]
2017-04-27 20:12 GMT+02:00 vladzcloudius <notifications@github.com>:

> Triggers may not replace the timely refresh because trigger (if it's going
> to be a one time event and not something that is *100% promised to
> eventually happen*) may get lost/fail just like a mutation write on a
> specific replica. However as an optimization this would do nicely indeed.
>

An important part of that proposal was to force use of RF=ALL and CL=ALL
for updates. In such case, a successful update is guaranteed to have
replicated everywhere.

For unsuccessful update we don't have to guarantee this.


> I'd like to give a short summary of the current status of this code and
> ask a few questions about the things are not obvious to me:
>
>    - RF by default is 2, while recommend (here I rely on what Glauber
>    told me) to always set it to RF=ALL. We recommend to actually set the RF to
>    the total number of all Nodes in the cluster while we do have an
>    everywhere_replication_strategy. Why don't we:
>       1. Set this strategy by default.
>       2. Recommend to set this strategy.
>
> Is it because it's not tested enough?
> I'll further assume that RF=ALL
>
>    - A default superuser ("cassandra") is created with the CL=ONE (
>    auth::setup()). But then
>    - CREATION/DELETION/QUERYING the users is performed with the following
>    CL:
>       - User 'cassandra': QUORUM - this is kinda strange. If one boots up
>       a new cluster ('cassandra' will be created with CL=ONE), then creates a
>       different superuser, deletes a 'cassandra' user and creates it again - now
>       it will be created with the CL=QUORUM.
>       - All other users: LOCAL_ONE. Why 'cassandra' is created with a ONE
>       and others with a LOCAL_ONE?
>    - Writes are performed with CL=ONE (default_authorizer::modify()) or
>    with a LOCAL_ONE when we create/delete a new user different from the
>    'cassandra' user.
>    - Reads are performed (by the cache) with CL=LOCAL_ONE (
>    default_authorizer::authorize()) or with CL=QUORUM when the
>    'cassandra' user queries an user info about itself from the users CF.
>
> So, as you may notice, most of the writes and reads are performed with an
> almost the lowest CL - (LOCAL_) ONE. (The lowest would be CL.ANY).
>
> Don't you think it's a bit risky? This may easily cause some Nodes to
> stuck for a long time with old credentials: consider a Node that was down
> when the credentials were updated and then went up. Without hints it will
> have an old data till repair and, if memory serves me well, with RF=ALL and
> CL=ONE we will always read from the local store. Read repair would
> eventually bring the new credentials but it may take quite a long time...
>
Wouldn't it be safer to always perform both read and write operations above
> with CL=QUORUM (provides READs are performed in the background of course)?
>
> As for a special CL=ALL like Tomek is proposing, it's also could be a
> problem: in the example above, the write with a CL=ALL* will succeed but
> then the Node will go UP again and will have old credentials, again, till
> repair or a read-repair.
>
I don't understand why a write with CL=ALL would succeed and some node have
old credentials. If that node didn't acknowledge the write, a write with
CL=ALL would not succeed. If it succeeded, it means it was applied on all
nodes.

> Reading with CL=QUORUM on the other hand will give a (relatively) strong
> guarantee that the new credentials will eventually (and quite quickly) make
> it to each Node's auth cache.
>
Writing with QUORUM and reading with QUORUM (in the background) should
achieve the same guarantee of seeing the last update as writing at CL=ALL
and reading at CL=ONE would, but with different tradeoffs.

**Comment by vladzcloudius** [comment]
On 04/27/2017 02:43 PM, Tomasz Grabiec wrote:
> 2017-04-27 20:12 GMT+02:00 vladzcloudius <notifications@github.com>:
>
> > Triggers may not replace the timely refresh because trigger (if it's 
> going
> > to be a one time event and not something that is *100% promised to
> > eventually happen*) may get lost/fail just like a mutation write on a
> > specific replica. However as an optimization this would do nicely 
> indeed.
> >
>
> An important part of that proposal was to force use of RF=ALL and CL=ALL
> for updates. In such case, a successful update is guaranteed to have
> replicated everywhere.
>
> For unsuccessful update we don't have to guarantee this.

Absolutely.
However for a classic CL=ALL it may be a problem on big clusters since 
Nodes may become UP and DOWN all the time and you will never succeed to 
successfully write new credentials - with CL=QUORUM the data will go in 
a lot faster. And if we pair it with reading with CL=QUORUM it would 
provide the consistency guaranties strong enough.
For the "special" CL=ALL not paired with reading with CL=QUORUM you may 
hit the issue as I described.

>
>
> > I'd like to give a short summary of the current status of this code and
> > ask a few questions about the things are not obvious to me:
> >
> > - RF by default is 2, while recommend (here I rely on what Glauber
> > told me) to always set it to RF=ALL. We recommend to actually set 
> the RF to
> > the total number of all Nodes in the cluster while we do have an
> > everywhere_replication_strategy. Why don't we:
> > 1. Set this strategy by default.
> > 2. Recommend to set this strategy.
> >
> > Is it because it's not tested enough?
> > I'll further assume that RF=ALL
> >
> > - A default superuser ("cassandra") is created with the CL=ONE (
> > auth::setup()). But then
> > - CREATION/DELETION/QUERYING the users is performed with the following
> > CL:
> > - User 'cassandra': QUORUM - this is kinda strange. If one boots up
> > a new cluster ('cassandra' will be created with CL=ONE), then creates a
> > different superuser, deletes a 'cassandra' user and creates it again 
> - now
> > it will be created with the CL=QUORUM.
> > - All other users: LOCAL_ONE. Why 'cassandra' is created with a ONE
> > and others with a LOCAL_ONE?
> > - Writes are performed with CL=ONE (default_authorizer::modify()) or
> > with a LOCAL_ONE when we create/delete a new user different from the
> > 'cassandra' user.
> > - Reads are performed (by the cache) with CL=LOCAL_ONE (
> > default_authorizer::authorize()) or with CL=QUORUM when the
> > 'cassandra' user queries an user info about itself from the users CF.
> >
> > So, as you may notice, most of the writes and reads are performed 
> with an
> > almost the lowest CL - (LOCAL_) ONE. (The lowest would be CL.ANY).
> >
> > Don't you think it's a bit risky? This may easily cause some Nodes to
> > stuck for a long time with old credentials: consider a Node that was 
> down
> > when the credentials were updated and then went up. Without hints it 
> will
> > have an old data till repair and, if memory serves me well, with 
> RF=ALL and
> > CL=ONE we will always read from the local store. Read repair would
> > eventually bring the new credentials but it may take quite a long 
> time...
> >
> Wouldn't it be safer to always perform both read and write operations 
> above
> > with CL=QUORUM (provides READs are performed in the background of 
> course)?
> >
> > As for a special CL=ALL like Tomek is proposing, it's also could be a
> > problem: in the example above, the write with a CL=ALL* will succeed but
> > then the Node will go UP again and will have old credentials, again, 
> till
> > repair or a read-repair.
> >
> I don't understand why a write with CL=ALL would succeed and some node 
> have
> old credentials. 

Here I refer a "special" CL=ALL you proposed (I called it CL=ALL*):

Tomek wrote on Apr 12, 12:21 PM EDT:

We could use a special kind of CL=ALL for permissions, which unlike the
regular one always tries to replicate to all live nodes. So permissions
would still be changed on as many nodes as possible.


> If that node didn't acknowledge the write, a write with
> CL=ALL would not succeed. If it succeeded, it means it was applied on all
> nodes.
>
> > Reading with CL=QUORUM on the other hand will give a (relatively) strong
> > guarantee that the new credentials will eventually (and quite 
> quickly) make
> > it to each Node's auth cache.
> >
> Writing with QUORUM and reading with QUORUM (in the background) should
> achieve the same guarantee of seeing the last update as writing at CL=ALL
> and reading at CL=ONE would, but with different tradeoffs.

Exactly. The main problem with the second approach is that writing with 
CL=ALL may never succeed if one of the Nodes is DOWN (it doesn't have to 
be because it's actually down but because there is some temporary 
networking issue) and in the big cluster this may happen a lot (because 
different Nodes would toggle DOWN and UP).
Using CL=QUORUM across the board would simply make things move a lot 
faster and in particular create a nicer user experience.

**Comment by slivne** [comment]
We need to figure out how we are handling multi-dc .... e.g. we need to be
able to operate in case the cluster is disconnected from another dc.

**Comment by vladzcloudius** [comment]
On 04/27/2017 03:11 PM, Shlomi Livne wrote:
> We need to figure out how we are handling multi-dc .... e.g. we need to be
> able to operate in case the cluster is disconnected from another dc.

Are you talking about everywhere_replication_strategy? Doesn't it 
replicate everywhere - in all Nodes in all DCs?
In this case when DCs are disconnected they will continue to operate as 
if they are separate clusters and when they are re-connected back then, 
first, it's advised to run a repair on system_auth KS if there were 
changes in it during the period of disconnect. Second, reading with 
CL=QUORUM would start synchronize the data little by little...

Is that what you meant?

**Comment by slivne** [comment]
I mean that I think the queries from the system_auth should be with
LOCAL_QUORUM and the writes should also be with LOCAL_QUORUM.

We should allow reads to work if the local dc is disconnected from the
outside world.

QUORUM in Large clusters with many DCs may effectively require you to have
connectivity
 - for example: 5 DCs each  RF=3
- QUORUM requires 8 nodes (so you must have connectivity to other DCs)
- LOCAL_QUORUM requires 2 nodes (so you can operate without external
connectivity).

**Comment by vladzcloudius** [comment]
On 04/30/2017 03:45 AM, Shlomi Livne wrote:
> I mean that I think the queries from the system_auth should be with
> LOCAL_QUORUM and the writes should also be with LOCAL_QUORUM.
>
> We should allow reads to work if the local dc is disconnected from the
> outside world.
>
> QUORUM in Large clusters with many DCs may effectively require you to have
> connectivity
> - for example: 5 DCs each RF=3
> - QUORUM requires 8 nodes (so you must have connectivity to other DCs)
> - LOCAL_QUORUM requires 2 nodes (so you can operate without external
> connectivity).


Good example, thanks.
However if, we use LOCAL_XXX for reads we may still get stuck with old 
data until repair (this is true regardless the cache).

Seeing failures with QUORUM (like in your example) maybe bad but won't 
accessing the data with old permission be even worse?

**Comment by vladzcloudius** [comment]
On 05/01/2017 09:11 AM, Vlad Zolotarov wrote:
>
>
>
> On 04/30/2017 03:45 AM, Shlomi Livne wrote:
>> I mean that I think the queries from the system_auth should be with
>> LOCAL_QUORUM and the writes should also be with LOCAL_QUORUM.
>>
>> We should allow reads to work if the local dc is disconnected from the
>> outside world.
>>
>> QUORUM in Large clusters with many DCs may effectively require you to 
>> have
>> connectivity
>> - for example: 5 DCs each RF=3
>> - QUORUM requires 8 nodes (so you must have connectivity to other DCs)
>> - LOCAL_QUORUM requires 2 nodes (so you can operate without external
>> connectivity).
>
>
> Good example, thanks.
> However if, we use LOCAL_XXX for reads we may still get stuck with old 
> data until repair (this is true regardless the cache).
>
> Seeing failures with QUORUM (like in your example) maybe bad but won't 
> accessing the data with old permission be even worse?

Even if we write with QUORUM and only read with LOCAL_QUORUM we may 
still have the same problem: e.g. DC1: 8, DC2: 3, QUORUM would require 6 
Nodes and all of them could come from DC1. DC2 nodes would be stuck with 
old credentials for a long time if they read with LOCAL_QUORUM.
Your example would also brake the WR(QUORUM) + RD(LOCAL_QUORUM) strategy...

However if we get back to WRITE with CL=ALL and READ with CL=LOCAL_ONE 
then we would be guarantied to always have the newest credentials on all 
nodes once write is successful, *and *reads would not require any 
connectivity. But in this case, like it was already mentioned, writing 
would be a nightmare...

So, in any case it's a matter of a trade-off. We have to give up on 
something...
