### ISSUE TITLE
artifact-test:  IndexError in executing scylla_io_setup

### ISSUE THREAD

**Issue by kongove** [scylladb/scylla#2263]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20170407.f579e4c.el7.centos
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

- [jenkins job ](http://jenkins.cloudius-systems.com:8080/job/scylla-master-centos-rpm-test/label=muninn/147/)
- [Jenkins job log](http://jenkins.cloudius-systems.com:8080/job/scylla-master-centos-rpm-test/label=muninn/147/artifact/latest/job.log)

```
Running '/usr/lib/scylla/scylla_io_setup' on CentOS7 VM
[stderr] Traceback (most recent call last):
[stderr]   File "/usr/lib/scylla/scylla_io_setup", line 36, in <module>
[stderr]     cpudata = scylla_util.scylla_cpuinfo()
[stderr]   File "/usr/lib/scylla/scylla_util.py", line 184, in __init__
[stderr]     self.__parse_cpuset()
[stderr]   File "/usr/lib/scylla/scylla_util.py", line 157, in __parse_cpuset
[stderr]     d = grp[-1].groupdict()
[stderr] IndexError: list index out of range
```

**Comment by kongove** [comment]
If we directly execute `scylla_io_setup` after scylla installation, IndexError will occur.

```
$ cat /etc/scylla.d/cpuset.conf
# DO NO EDIT
# This file should be automatically configure by scylla_cpuset_setup
#
# CPUSET="--cpuset 0 --smp 1"
```

We can't assume there exists an effective CPUSET parameter in cpuset.conf.
The scylla_util.py script was just introduced by @glommer

**Comment by glommer** [comment]
I sent a patch for this today.

**Comment by kongove** [comment]
I just saw the patch, thanks.
[PATCH] scylla_util: handle empty cpuset.conf files

**Comment by kongove** [comment]
The problem was found in CentOS, but it's a general issue and exists in Ubuntu.
The latest artifact test of 666.development-0.20170409.b4c368a-0ubuntu1 is good. Verified the fix.
