### ISSUE TITLE
Packaging for Gentoo Linux

### ISSUE THREAD

**Issue by ultrabug** [scylladb/scylla#2264]
Hi,

I am in the process of packaging Scylla for Gentoo Linux and would like to know about your position about supporting and dealing with the packaging of scylla on Linux distributions.

Since I would love to do this right and stay in line with the scylla development and releases, it occurred to me to ask for your guidance and feedback about some points.
- Do you have a strong position in the Linux distros you support ?
- Are you open to discussion about some QA issues and respecting user specific configurations (CFLAGS, LDFLAGS...) ?

This is my work in progress (it compiles and runs okay but I have to hack some bits) : https://gitweb.gentoo.org/dev/ultrabug.git/tree/dev-db/scylla/scylla-1.6.3.ebuild

If the idea of having Scylla on a compilation based distribution is as exciting to you than it is to me, I would love to work on it with your help!

Thanks for considering this.

**Comment by avikivity** [comment]
What do you mean by "a strong position"?  We support the distributions our users and customers use. We appreciate and welcome support added by distributions to ScyllaDB. I personally favor Fedora, but perhaps that's not what you were asking.

If you have questions, requests, or patches, you're welcome to post them on the development list.  Be aware we require a CLA to be signed to accept patches.

Please package and make sure `scylla_setup` is functional.  Simply running scylla with the default configuration will not produce the best results.

**Comment by ultrabug** [comment]
Thanks for your reply @avikivity.

My question was more about guidance on how to properly package Scylla on a Linux distro and if you guys were okay to help if needed.

I take it you're pointing me to the dev ML for this then.

> Please package and make sure scylla_setup is functional. Simply running scylla with the default configuration will not produce the best results.

Thanks for the tip, that's the kind of thing I'm looking for in this issue.
