### ISSUE TITLE
Multi-host containers fails to connect

### ISSUE THREAD

**Issue by Petterhg** [scylladb/scylla#2270]
*Installation details*
Scylla version (or git commit hash): latest container
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): docker
Hardware: sockets= cores= 20 hyperthreading= memory= 128 G
Disks: 4 SSD

ISSUE:
I have 3 hosts running on my network (i.e 3 physical computers) that I want to run a scylla cluster on. So I want the load to be distributed over multiple physical hosts that each has one scylla container running on it. 
This cluster is then supposed to be accessed via 192.168.1.115, which is the ip of one of the hosts. Therefore I have the --broadcast-rpc-address=192.168.1.115. 
This is working fine and I can cqlsh from the other hosts.
The problem is connecting a new host to the cluster. On the first host I run:

`docker run -d --net=scyllanet --add-host=samael:192.168.1.115 -p 9042:9042 -p 9160:9160 -p 9180:9180 -p 9100:9100 -p 7000:7000 --name testnode1_scylla scylladb/scylla --broadcast-rpc-address 192.168.1.115 --broadcast-address 192.168.1.115`

Adding nodes on the same host is fine since the docker ip is 172.1.0.4 or something, but when trying to add another node/scylla-container from host (192.168.1.157) I cannot get it to work, i.e they are not connecting:

`docker run -d -p 9042:9042 -p 9160:9160 -p 9180:9180 -p 9100:9100 -p 7000:7000 --name testnode2 scylladb/scylla --seeds 192.168.1.115` 

Can anyone see what I am doing wrong here!?
Thankful for all advice.

**Comment by Petterhg** [comment]
# Solution
To have it working on two hosts with load balancing and gossip on the same network you do

## On host 1, with ip 192.168.1.115
`docker run -d -p 9042:9042 -p 9160:9160 -p 9180:9180 -p 9100:9100 -p 7000:7000 --name testnode1_scylla scylladb/scylla --broadcast-rpc-address 192.168.1.115 --broadcast-address 192.168.1.115 --memory 30G --smp 8`

## On host 2, ip 192.168.1.157
`docker run -d -p 9042:9042 -p 9160:9160 -p 9180:9180 -p 9100:9100 -p 7000:7000 --name testnode2_scylla scylladb/scylla --seeds 192.168.1.115 --memory 20G --smp 6 --broadcast-address 192.168.1.157`

I dont know if this was obvious or not. At least not to me.

**Comment by tzach** [comment]
@penberg worth adding to the Scylla Docker page
