### ISSUE TITLE
v1.6.1 -> SELinux mode changes back to "Enforcing" after scylla node reboot

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla#2279]
**Installation details**
Scylla version (or git commit hash): 1.6.1-20170218.2ea4da2
scylla-kernel-conf-1.6.1-20170218.2ea4da2.el7.centos.x86_64
scylla-tools-1.6.1-20170218.710229c.el7.centos.noarch
scylla-server-1.6.1-20170218.2ea4da2.el7.centos.x86_64
scylla-jmx-1.6.1-20170218.d0401e7.el7.centos.noarch
scylla-conf-1.6.1-20170218.2ea4da2.el7.centos.x86_64
scylla-1.6.3-20170405.5ab8601.el7.centos.x86_64

Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos7

**1. Scylla installed -> run scylla_setup -> YES to disable SELinux -> reboot**

**vi /etc/sysconfig/selinux**
SELINUX=disabled
SELINUXTYPE=targeted

**2. After I shutdown VM and started it next day:**
[tomer@tomer-4cpu-15gb-centos7-loader9 ~]$ sudo sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
**Current mode:                   enforcing  ==>> ????**
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28

**3. I manually change it (in selinux file it is still disabled):**
[tomer@tomer-4cpu-15gb-centos7-loader9 ~]$ sudo setenforce 0
[tomer@tomer-4cpu-15gb-centos7-loader9 ~]$ sudo sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
**Current mode:                   permissive  ==>> OK**
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28

**4. Reboot VM**

**After reboot:**
[tomer@tomer-4cpu-15gb-centos7-loader9 ~]$ sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
**Current mode:                   enforcing ==>> After boot becomes enforcing again**
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      28

**Comment by tomer-sandler** [comment]
RCA (thanks to Gleb!): /etc/sysconfig/selinux is link to /etc/selinux/config -> there the selinux was still enforcing
We should probably change the selinux value in /etc/selinux/config and that should solve the issue.

**Comment by gleb-cloudius** [comment]
out script does:

```
        sed -e "s/enforcing/disabled/" /etc/sysconfig/selinux > /tmp/selinux
        mv /tmp/selinux /etc/sysconfig/
```

but /etc/sysconfig/selinux is a softlink to /etc/selinux/config and
after our script runs this is no longer the case. Apparently nobody
looks at /etc/sysconfig/selinux.

--
			Gleb.

**Comment by amoskong** [comment]
What can we do for users who tried to disable selinux by our problem script?
The upgrade can't solve the existed problem, even resetup with write setup script (applied takuya's fix [1]).

Their softlink was rewrite, we should suggest them to recover the softlink manually in Release Note?
@slivne @tzach 

[1] [PATCH scylla] dist/common/scripts/scylla_selinux_setup: keep symlink on /etc/sysconfig/selinux

**Comment by syuu1228** [comment]
@amoskong Or maybe we can recover it by scylla package postinst script, when user tries to upgrade scylla. It feels bit dirty way though..
Even we don't recover it automatically, we still can printout warning message on the script.

**Comment by amoskong** [comment]
Maybe just warning user in upgrading scylla, user can recover manually or confirm to recover by postinst script.

**Comment by amoskong** [comment]
We need a solution for broken softlink.

'--follow-symlinks' in fixed script doesn't work in broken env, because `/etc/sysconfig/selinux` is no longer a softlink. The script still can't changed the real configure file (/etc/selinux/config)

**Comment by syuu1228** [comment]
@amoskong sent a patch named "[PATCH scylla] dist/redhat: show warning on package upgrade when /etc/sysconfig/selinux is corrupted" which shows warning message when upgrading the package, if the symlink is broken.
