### ISSUE TITLE
Support type casting in selection clause

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2280]
*Installation details*
Scylla version (or git commit hash): 1.7

reproduce
```
CREATE TABLE air_quality_data (sensor_id text,time timestamp, co_ppm int,PRIMARY KEY (sensor_id, time));
INSERT INTO air_quality_data(sensor_id, time, co_ppm) VALUES ('my_home', '2016-08-30 07:01:00', 17);
INSERT INTO air_quality_data(sensor_id, time, co_ppm) VALUES ('my_home', '2016-08-30 07:01:01', 18);
INSERT INTO air_quality_data(sensor_id, time, co_ppm) VALUES ('my_home', '2016-08-30 07:01:02', 19);
INSERT INTO air_quality_data(sensor_id, time, co_ppm) VALUES ('my_home', '2016-08-30 07:01:03', 20);
INSERT INTO air_quality_data(sensor_id, time, co_ppm) VALUES ('my_home', '2016-08-30 07:01:04', 30);
INSERT INTO air_quality_data(sensor_id, time, co_ppm) VALUES ('my_home', '2016-08-30 07:01:04', 31);
INSERT INTO air_quality_data(sensor_id, time, co_ppm) VALUES ('my_home', '2016-08-30 07:01:10', 20);

select avg(co_ppm) from air_quality_data;

 system.avg(co_ppm)
--------------------
                 20
```

The non cast avg is ~22.14

Correlating C* ticket:
https://issues.apache.org/jira/browse/CASSANDRA-10310

**Comment by hagrid-the-developer** [comment]
It seems that I misunderstood this issue (see my patch https://groups.google.com/forum/#!topic/scylladb-dev/q9PQPMowI1U ). I thought that I should automatically convert avg function to floating point and this issue is rather about adding CAST(x AS ...).

So I should add support for SELECT CAST(x AS DECIMAL) ... to the language, is it correct?

What about VARINT and DECIMAL? We can store them to table, but we cannot call aggregate functions over them and for decimal we don't even have implemented arithmetic operations. Only conversion from/to string and comparision.

**Comment by penberg** [comment]
@hagrid-the-developer Good question. I also understood the ticket as converting to floating point automatically. Did you already run @tzach's query on Apache Cassandra? That's the easiest way to verify what the desired semantics are.

**Comment by hagrid-the-developer** [comment]
I tried C* 3.6 and it indeed uses casting of columns and avg(int) -> int .

    CREATE TABLE air_quality_data (sensor_id text,time timestamp, co_ppm DECIMAL,PRIMARY KEY (sensor_id, time));
    INSERT INTO air_quality_data_decimal (sensor_id, time, co_ppm) VALUES ('my_home', '2016-08-30 07:01:00', 17);
    INSERT INTO air_quality_data_decimal(sensor_id, time, co_ppm) VALUES ('my_home', '2016-08-30 07:01:01', 18);
    select avg(co_ppm) from air_quality_data;

    system.avg(co_ppm)
    --------------------
             17

But with cast:

    select avg(CAST(co_ppm AS DOUBLE)) from air_quality_data;

    system.avg(cast(co_ppm as double))
    -------------------------------------
                 17.5

It is interesting that DECIMAL support is also limited (but better than in Scylla):

    CREATE TABLE air_quality_data_decimal (sensor_id text,time timestamp, co_ppm DECIMAL,PRIMARY KEY (sensor_id, time));
    INSERT INTO air_quality_data_decimal (sensor_id, time, co_ppm) VALUES ('my_home', '2016-08-30 07:01:00', 17);
    INSERT INTO air_quality_data_decimal(sensor_id, time, co_ppm) VALUES ('my_home', '2016-08-30 07:01:01', 18);
    select avg(co_ppm) from air_quality_data_decimal;
    system.avg(co_ppm)
    --------------------
                 18

**Comment by hagrid-the-developer** [comment]
Considering conversion between timestamp <-> date: timestamp is number of miliseconds since epoch, date is number of days since epoch. Do we want to consider leap seconds during the conversion or not?

**Comment by avikivity** [comment]
I think that `gmtime` will consider leap seconds (and that we should use leap seconds).

**Comment by hagrid-the-developer** [comment]
It seems that types.cc uses std::chrono, boost::ptime for Timerstamp and library from Howard Hinnant for Date (date.h). Leap seconds are probably covered by boost::ptime, so no need to introduced gmtime. In theory Date can handle dates [ -5877641-06-23, 5881580-07-11], but boost::ptime can handle only dates [1400-Jan-01, 9999-12-31] . So conversions Date <-> Timestamp aren't always possible. Is it a problem and what to do with too small or too larget dates? Exact calculation for historical dates is difficult and usually not needed in practice and for dates too much in the future it also doesn't make too much sense, clock correction can be introdues even by a hit of a meteor and it is possible that humanity will use different calendar in the distant future. ;-)
