### ISSUE TITLE
nodetool on empty keyspace shows incorrect info

### ISSUE THREAD

**Issue by kthommandra** [scylladb/scylla#2282]
When cfstats shows that the keyspace is empty why does `nodetool status` for that same keyspace say that the Load (size on disk) is 100+GB ?

KS1 is a newly created keyspace and is empty.

CentOS 7.2
scylla version 1.6.2-20170310.d41ba3b

# nodetool status KS1
Datacenter: DC1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens  Owns (effective)  Host ID                               Rack
UN  IP1  120.7 GB   256     33.8%             9705a681-a49c-4d80-87d8-0679ccaeeff1  R166
UN  IP2   125.95 GB  256     35.1%             c73bf55c-0977-4eb6-9e55-7ad286e9ec40  R132
UN  IP3  117.41 GB  256     32.9%             f5bbbc52-6757-485c-831a-ecf18702cf72  R189
UN  IP4   118.07 GB  256     33.0%             b2aa8b8d-2ccc-436c-ac76-dd432ab8485b  R132
UN  IP5  121.9 GB   256     34.2%             d6b400b4-3155-4db8-9075-8f4be436327c  R166
UN  IP6  126.89 GB  256     35.7%             dfe48db9-b9bf-4e81-a99f-d2d16a28c729  R189
UN  IP7  110.87 GB  256     31.3%             32d33df3-e621-4a1c-a31a-1a15c5544848  R189
UN  IP8   113.71 GB  256     31.9%             f9a4d222-8fe2-4a24-b641-6b44078b3132  R132
UN  IP9  113.56 GB  256     32.0%             f39881d5-64c9-49eb-a936-84ce4c72ac58  R166

# nodetool cfstats KS1.CF1
Keyspace: KS1
        Read Count: 0
        Read Latency: NaN ms.
        Write Count: 0
        Write Latency: NaN ms.
        Pending Flushes: 0
                Table: CF1
                SSTable count: 0
                Space used (live): 0
                Space used (total): 0
                Space used by snapshots (total): 0
                Off heap memory used (total): 0
                SSTable Compression Ratio: 0.0
                Number of keys (estimate): 0
                Memtable cell count: 0
                Memtable data size: 0
                Memtable off heap memory used: 0
                Memtable switch count: 0
                Local read count: 0
                Local read latency: NaN ms
                Local write count: 0
                Local write latency: NaN ms
                Pending flushes: 0
                Bloom filter false positives: 0
                Bloom filter false ratio: 0.00000
                Bloom filter space used: 0
                Bloom filter off heap memory used: 0
                Index summary off heap memory used: 0
                Compression metadata off heap memory used: 0
                Compacted partition minimum bytes: 0
                Compacted partition maximum bytes: 0
                Compacted partition mean bytes: 0
                Average live cells per slice (last five minutes): 0.0
                Maximum live cells per slice (last five minutes): 0.0
                Average tombstones per slice (last five minutes): 0.0
                Maximum tombstones per slice (last five minutes): 0.0

----------------
```

**Comment by tzach** [comment]
@amnonh ?

**Comment by amnonh** [comment]
Unless I'm wrong, nodetool status reports all load, not just the keyspace,
see the following answer:
http://stackoverflow.com/questions/39590657/why-does-nodetool-status-keyspace-still-show-hundreds-of-mbs-of-data-after-tru

**Comment by slivne** [comment]
@amnonh is correct - nodetool status provides the "load" of all the keyspaces on the node.

@kthommandra - I am closing this issue - we will be happy to provide additional clarification if needed.
