### ISSUE TITLE
Failed to install scylla 1.6.3 on raspbery pi / raspbian

### ISSUE THREAD

**Issue by Jsynk** [scylladb/scylla#2286]
Scylla version (or git commit hash): 
1.6
OS (RHEL/CentOS/Ubuntu/AWS AMI):
Raspbian based of Debian Jessie / Debian 8.7

Hi i tried installing scylladb according install instructions http://www.scylladb.com/download/#fndtn-Debian
and http://docs.scylladb.com/getting-started/debian8/

i executedthe following on the terminal
sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com.s3.amazonaws.com/deb/debian/scylla-1.6-jessie.list
sudo apt-get update
sudo apt-get install scylla

when i tried installing scylla i get
E: Unable to locate package scylla

would it help to add the complete logs of each command?

Any help is appreciated

**Comment by avikivity** [comment]
Scylla was not ported to ARM yet (and a 32-bit port is unlikely)

**Comment by Jsynk** [comment]
I see thanks.
I guess my dream of running scylladb on a 3 watt server has been shattered.

Also I just stumbled upon http://docs.scylladb.com/admin/ and in the 
CPU section i noticed that it said
Scylla requires modern Intel CPUs that support the SSE4.2 instruction set and will not boot without it.

Does that also mean the new cheaper amd ryzen cpu is also currently not supported?

Thanks again

**Comment by avikivity** [comment]
Ryzen supports SSE4.2 so it is supported.  The page uses "Intel" where it really means "x64".  We expect good performance on those 32-core chips.

When we support ARMv8/aarch64 (not so far in the future) you can try Scylla on a mobile-class chip.

**Comment by penberg** [comment]
Raspberry Pi 3 has a 64-bit ARM CPU.

**Comment by avikivity** [comment]
Then it should be easy to support Scylla on it, provided it implements the crc32c instruction.

@Jsynk do you know if it does?  Perhaps `/proc/cpuinfo` will tell.

**Comment by Jsynk** [comment]
Nice looking forward to testing scylladb arm support in the near future.
raspberry pi 3 raspbian - terminal > cat /proc/cpuinfo > outputted >
```
processor	: 0
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
model name	: ARMv7 Processor rev 4 (v7l)
BogoMIPS	: 38.40
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 
CPU implementer	: 0x41
CPU architecture: 7
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: BCM2709
Revision	: a02082
Serial		: 00000000fd124efc
```
crc32 seems to be listed in the features section, so far so good.

I will be prototyping/learning with Virtualbox/CentOS in the meantime.

Thanks for all the help guys.

**Comment by penberg** [comment]
@Jsynk ARMv7 is 32-bit. You're seeing that because all the official distributions for Raspberry Pi are 32-bit.
