### ISSUE TITLE
Streaming with Leveled Compaction Strategy can cause OOM

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2287]
Streaming generates many small SSTables with large token ranges.  The SSTables are small because streaming limits memtable size to reduce performance impact on normal loads; the token ranges are wide because we combine data from multiple peers (and each peer may send us multiple ranges).

The `partitioned_sstable_set` data structure used to hold SSTables with LCS is O(N^2) in space in such circumstances, and N can be several thousands per shard.  This results in millions of small allocations.

**Comment by avikivity** [comment]
Possible solutions:

 - switch to Cassandra's [OverlapIteraor](https://github.com/hobinyoon/apache-cassandra-3.0.5-src/blob/master/src/java/org/apache/cassandra/utils/OverlapIterator.java); problem is, it's O(N) for small or singular  range selects
 - store Level 0 in a bag instead of the interval map, so it doesn't trigger O(N^2) behavior
 - throttle streaming until L0 gets smaller; this has the additional benefit of limiting impact on reads (at the expense of repair speed), but is a large-impact change (it can cause streaming timeouts) and is not localized to one subsystem

**Comment by avikivity** [comment]
My preference is to start with a bag for L0, then add throttling to reduce the impact on reads.

**Comment by raphaelsc** [comment]
On Sun, Apr 16, 2017 at 6:54 AM, Avi Kivity <notifications@github.com>
wrote:

> My preference is to start with a bag for L0,
>
Like the idea. We likely include every L0 sstable for every read anyway.


> then add throttling to reduce the impact on reads.
>
BTW, LCS performs STCS in L0 when L0 has more than max_threshold sstables.
That's to reduce the impact on reads ASAP. By throttling, I suppose you
mean measuring the compaction backlog (only L0 is interesting) and tweaking
compaction i/o priority accordingly.

**Comment by avikivity** [comment]
@raphaelsc can you come up with a quick patch for that?  if not, I can do it.

When the data comes from the user, we can adjust compaction priority, but for streaming that's not a good option, because it will allow repair or rebuild to impact regular work.

**Comment by raphaelsc** [comment]
On Mon, Apr 17, 2017 at 12:41 PM, Avi Kivity <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> can you come up with a quick
> patch for that?
>

working on it

**Comment by slivne** [comment]
@avikivity  could it be that we have the files covering large range because of applying SizeTiered compaction in L0 after streaming ?

Please note that we may also need to disable STCS in L0 as we may be accumulating many files in L0 

Cassandra has a special flag to disable STCS in L0 for Leveled (https://issues.apache.org/jira/browse/CASSANDRA-6621) - we may need to impl that as well.

**Comment by avikivity** [comment]
I don't think it applies to us.  We don't stream sstables, we stream mutations, so we'll combine mutations from different ranges.

Perhaps we should stream directly to sstables (shouldn't be hard: open a writer and write to it, instead of writing to memtable) but that's a bigger change.

**Comment by tgrabiec** [comment]
@avikivity

>  switch to Cassandra's OverlapIteraor; problem is, it's O(N) for small or singular range selects

You mean O(N) in terms of space or time complexity? For which operation?

**Comment by asias** [comment]
@avikivity backport to 1.5?

**Comment by avikivity** [comment]
@tgrabiec small or singular range query.  It's O(N) in both space and time, it can't efficiently seek into a token. (sorry for delay)

In contrast partitioned_sstable_set is O(log N).

**Comment by avikivity** [comment]
@asias we'll be releasing 1.7 real soon now, and this only impacts streaming+large LCS tables.
