### ISSUE TITLE
Checking Scylla with PVS-Studio static analyzer

### ISSUE THREAD

**Issue by khandeliants** [scylladb/scylla#2288]
Hello,
I have found some weaknesses and bugs using PVS-Studio tool. PVS-Studio is a static code analyzer for C, C++ and C#: https://www.viva64.com/en/pvs-studio/

Analyzer warnings:
* [V596](https://www.viva64.com/en/w/V596/) ([CWE-390](https://cwe.mitre.org/data/definitions/390.html)) The object was created but it is not being used. The 'throw' keyword could be missing: throw runtime_error(FOO); [locator/token_metadata.cc 209](https://github.com/scylladb/scylla/blob/master/locator/token_metadata.cc#L209)
  
  _Comment_: it is necessary to add the "throw" operator.

* [V547](https://www.viva64.com/en/w/V547/) ([CWE-570](https://cwe.mitre.org/data/definitions/570.html)) Expression 'idx < 0' is always false. Unsigned type value is never < 0. [cql3/statements/alter_type_statement.cc 189](https://github.com/scylladb/scylla/blob/master/cql3/statements/alter_type_statement.cc#L189)
  
  _Comment_: judging by the code, the function `get_idx_of_field` can return a signed `-1` number of `int32_t` type, which is implicitly converted to an unsigned number (`uint32_t`) and stored in `idx`. The comparison of `idx < 0` is meaningless, it is necessary to compare `idx` with `UINT_MAX`, for example, like this:
  `if (idx == static_cast<uint32_t>(-1))`

* [V502](https://www.viva64.com/en/w/V502/) ([CWE-783](https://cwe.mitre.org/data/definitions/783.html)) Perhaps the '?:' operator works in a different way than it was expected. The '?:' operator has a lower priority than the '+' operator. [dht/byte_ordered_partitioner.cc 120](https://github.com/scylladb/scylla/blob/master/dht/byte_ordered_partitioner.cc#L120)
  
  _Comment_: the priority of operator `?:` is lower than operator `+`, respectively, `t` always reserves memory for 1 element. It is necessary to enclose the `remainder ? 1 : 0` in parentheses.

* [V746](https://www.viva64.com/en/w/V746/) Type slicing. An exception should be caught by reference rather than by value. [db/marshal/type_parser.cc 125](https://github.com/scylladb/scylla/blob/master/db/marshal/type_parser.cc#L125), [db/marshal/type_parser.cc 169](https://github.com/scylladb/scylla/blob/master/db/marshal/type_parser.cc#L169)
  
  _Comment_: it is much better and safer to catch exceptions by reference.

In addition, I suggest having a look at the emails, sent from @pvs-studio.com.

Best regards,
Phillip Khandeliants

**Comment by vladzcloudius** [comment]
V547 is fixed by e06bafdc6c5644feb6c4f5537c83ecefe736d6f1 already.

**Comment by vladzcloudius** [comment]
V502 is fixed by a496ec7f. Apparently clang caught it too.
