### ISSUE TITLE
can't login instance with ssh key at the beginning of boot

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2289]
*Installation details*
Scylla version (or git commit hash): scylla-1.7.rc2-0.20170328.9b26a57
Cluster size: 1 
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-2c3db73a

http://jenkins.cloudius-systems.com/job/scylla-1.7-ami-test-amostmp/label=muninn/3/artifact/latest/remote.log

*Problem*
Create an ami instance with AMI_ID: ami-2c3db73a, can't login guest with the SSH key.
Wait about 2 mins, the SSH key works, we can login to the instance.

Avocado log from Jenkins:
```
  transport  L1567 DEBUG| Kex agreed: diffie-hellman-group1-sha1
  transport  L1567 DEBUG| Cipher agreed: aes128-ctr
  transport  L1567 DEBUG| MAC agreed: hmac-sha2-256
  transport  L1567 DEBUG| Compression agreed: none
  transport  L1567 DEBUG| kex engine KexGroup1 specified hash_algo <built-in function openssl_sha1>
16:47:25 transport  L1567 DEBUG| Adding ssh-rsa host key for 54.86.130.211: 3ec2939eecb3998ef7a13e3177e1afcd
16:47:25 transport  L1567 DEBUG| Trying key 352182f5962a3804d9717f2884ae8328 from /var/tmp/avocado-test-26b87676.pem
transport  L1567 DEBUG| userauth is OK
transport  L1567 INFO | Authentication (publickey) failed.
transport  L1567 DEBUG| Trying SSH agent key 78755818d96f3299bad595d7cf202c3d
transport  L1567 DEBUG| userauth is OK
transport  L1567 INFO | Authentication (publickey) failed.
transport  L1567 DEBUG| Trying discovered key 675daf7fa698252ec2014a81d51d6724 in /jenkins/.ssh/id_rsa
transport  L1567 DEBUG| userauth is OK
transport  L1567 INFO | Authentication (publickey) failed.
```

cmdline log:
```
sh-4.3$ ssh -i  /var/tmp/avocado-test-26b87676.pem centos@54.86.130.211
The authenticity of host '54.86.130.211 (<no hostip for proxy command>)' can't be established.
ECDSA key fingerprint is SHA256:F5+dcMXk/TW5wGL312f+thNtndbCPd8/FSFNlOvdi4c.
ECDSA key fingerprint is MD5:1b:ea:d8:32:f5:db:6e:41:8c:e0:57:34:77:b4:59:5b.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '54.86.130.211' (ECDSA) to the list of known hosts.
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).
```

```
sh-4.3$ grep 54.86.130.211 ~/.ssh/known_hosts
54.86.130.211 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBObBNh5QmX8UQtktgeF6VxrNC0eRFzIbeDSRZ3/y0CQyyUo2aaZgbNbwGwbGcY8/BW+C/7rLosyeCJRjp7Y4XnE=
```

**Comment by slivne** [comment]
@amoskong is this a regression ? which instance type ?

**Comment by amoskong** [comment]
@sliven Not a regression,  [A old 1.7 ami test (2017-03-28)](http://jenkins.cloudius-systems.com/job/scylla-1.7-ami-test/11/) succeeded, but I can reproduce this problem with the ami-id (ami-e67dc4f0)

instance type: c3.2xlarge

**Comment by slivne** [comment]
@amoskong - did we have this issue in 1.6 / 1.5 / 1.4 ?

**Comment by slivne** [comment]
@amoskong ping

**Comment by amoskong** [comment]
I didn't reproduce this problem with 1.6, 1.5, 1.4 ami. So it's a regression.

**Comment by amoskong** [comment]
@syuu1228 Is it related with that we enabled `Enhanced Network` in AMI?

**Comment by syuu1228** [comment]
@amoskong Since you are getting "Authentication (publickey) failed", it means the instance is IP reachable, so it unlikely NIC problem. And I think we haven't change anything related Enhanced Networking on 1.7.
Copying ssh key is done by cloud-init, so I suppose it's related with cloud-init.
Currently, we only disabling "mount" option to stop mounting EBS/Ephemeral automatically: https://github.com/scylladb/scylla-ami/blob/master/scylla_install_ami#L55
I was thinking current settings works finely, but if not, we can compare cloud-init settings / systemd unit settings with Official CentOS AMI.

But I'm sure we never changed these stuff for long time, don't have an idea what is difference between 1.4-1.7rc1 and 1.7rc2.

**Comment by syuu1228** [comment]
@amoskong Hmm, couldn't reproduce this on c3.2xlarge / ami-2c3db73a.
But I think I have experienced it before (not on this AMI), maybe it sometimes happens for some reasons(or it sometimes happens on all EC2 instances).
I compared cloud-init configuration, but our settings and CentOS AMI settings is exactly same.
If you still able to reproduce it, could you compare "journalctl -xe|grep cloud-init" between OK AMI and Bad AMI?

**Comment by tzach** [comment]
@amoskong @syuu1228 I had a similar experience in past releases on EC2, so I do not think its a regression.
Recently I added a retry to the Ansible script to bypass it.
https://github.com/scylladb/cassandra-test-and-deploy/commit/fa6e4073fca74a51a5a9fe573bb27cd221974521

**Comment by amoskong** [comment]
On Wed, May 17, 2017 at 1:47 PM, Tzach Livyatan <notifications@github.com>
wrote:

> @amoskong <https://github.com/amoskong> @syuu1228
> <https://github.com/syuu1228> I had a similar experience in past releases
> on EC2, so I do not think its a regression.
> Recently I added a retry to the Ansible script to bypass it.
> scylladb/cassandra-test-and-deploy@fa6e407
> <https://github.com/scylladb/cassandra-test-and-deploy/commit/fa6e4073fca74a51a5a9fe573bb27cd221974521>
>

@Tzach What's the first time when you touched this issue with past
releases? did you see 'Authentication (publickey) failed.' error?

Why do you add the retry until one month ago?

**Comment by tzach** [comment]
Yes, from time to time.
Maybe it's more frequent, I can not tell

**Comment by amoskong** [comment]
On Wed, May 17, 2017 at 4:41 PM, Tzach Livyatan <notifications@github.com>
wrote:

> Yes, from time to time.
> Maybe it's more frequent, I can not tell
>
Thanks. So it should be not a regression. @syuu1228
<https://github.com/syuu1228>
