### ISSUE TITLE
nodetool repair

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#229]
Repairs one or more tables
http://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsRepair.html

See #79 #80 #211 #210 #212 for more details.
Each issue may be related to different milestone!
This issue capture the integration with nodetool.

Used in #216 #220 #223

**Comment by nyh** [comment]
"nodetool repair" does, mostly, work. What is this issue about?

**Comment by tzach** [comment]
> What is this issue about?

enhancement request for Implementing and testing nodetool repair.

**Comment by penberg** [comment]
Is this issue fixed by commit https://github.com/scylladb/scylla/commit/800ed6376afdf3381ca02dec572d805921bad5b7 or is there more things that need to be done?

**Comment by penberg** [comment]
@slivne @tzach Can we close this issue?
