### ISSUE TITLE
An error when compiling on Arch Linux

### ISSUE THREAD

**Issue by imriss** [scylladb/scylla#2292]
Scylla version (or git commit hash): 
commit 7e1b245887665ff0cc08bc1f4584d600d6289d89
Author: Pekka Enberg <penberg@scylladb.com>
Date:   Wed Feb 1 13:58:06 2017 +0200
    release: prepare for 1.6.0
diff --git a/SCYLLA-VERSION-GEN b/SCYLLA-VERSION-GEN
index d9105480..a7c644e1 100755
--- a/SCYLLA-VERSION-GEN
+++ b/SCYLLA-VERSION-GEN
@@ -1,6 +1,6 @@
 #!/bin/sh
-VERSION=1.6.rc2
+VERSION=1.6.0

OS (RHEL/CentOS/Ubuntu/AWS AMI): Arch Linux

*********
The error message: https://pastebin.com/vXJJe5Z2

A few lines of the log:

44/272] NINJA seastar/build/relea...e/gen/http/http_response_parser.hh
FAILED: seastar/build/release/libseastar.a seastar/build/release/apps/iotune/iotune seastar/build/release/gen/http/request_parser.hh seastar/build/release/gen/http/http_response_parser.hh 
/usr/bin/ninja -C seastar build/release/libseastar.a build/release/apps/iotune/iotune build/release/gen/http/request_parser.hh build/release/gen/http/http_response_parser.hh
ninja: Entering directory `seastar'
[1/33] RAGEL build/release/gen/http/http_response_parser.hh
[2/33] RAGEL build/release/gen/http/request_parser.hh
[3/33] CXX build/release/net/dpdk.o
[4/33] CXX build/release/http/file_handler.o
FAILED: build/release/http/file_handler.o 
g++ -MMD -MT build/release/http/file_handler.o -MF build/release/http/file_handler.o.d -O2 -I build/release/gen -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I. -U_FORTIFY_SOURCE  -march=nehalem -Ifmt -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DNO_EXCEPTION_INTERCEPT -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/release/http/file_handler.o http/file_handler.cc
In file included from ./core/iostream.hh:224:0,
                 from ./core/reactor.hh:26,
                 from http/file_handler.cc:25:
./core/iostream-impl.hh: In instantiation of ‘struct input_stream<CharType>::consume(Consumer&)::<lambda()> [with Consumer = httpd::reader; CharType = char]::<lambda(using tmp_buf = class temporary_buffer<char>)>’:
./core/iostream-impl.hh:172:14:   required from ‘input_stream<CharType>::consume(Consumer&)::<lambda()> [with Consumer = httpd::reader; CharType = char]’
./core/iostream-impl.hh:166:31:   required from ‘struct input_stream<CharType>::consume(Consumer&) [with Consumer = httpd::reader; CharType = char]::<lambda()>’
./core/iostream-impl.hh:166:18:   required from ‘future<> input_stream<CharType>::consume(Consumer&) [with Consumer = httpd::reader; CharType = char]’

...

Thanks!

**Comment by penberg** [comment]
There are ScyllaDB packages for Arch Linux now:

https://aur.archlinux.org/packages/scylla-git/

/cc @argenet

**Comment by argenet** [comment]
Thanks, Pekka. A quick comment on this. The 'scylla-git' package for Arch Linux builds a development version of ScyllaDB based on the latest revisions in the 'master' branch in Git.

A stable release package will be added for Arch Linux once Scylla 2.0 is out. There are some problems building current ScyllaDB stable release (1.7.4) for Arch since it requires older thrift package no more available from ArchLinux repositories. Given that 2.0 is right around the corner, it will be supported instead once available.

Also, please note that current Arch Linux package does not have DPDK support enabled. This is work in progress.

**Comment by imriss** [comment]
Thanks @penberg and @argenet for the link to the package and the update.

I was able to resolve the errors after I posted the question, but I forgot to update the question.

Thanks again.
