### ISSUE TITLE
i3.2xlarge AMI instance used driver 'vif', not expected 'ena'

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2293]
*Installation details*
Scylla version (or git commit hash):  1.7.rc2
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-2c3db73a

driver info of i3.2xlarge instance
```
01:56:36 INFO | Running 'ethtool -i eth0'
01:56:36 DEBUG| [stdout] driver: vif
01:56:36 DEBUG| [stdout] version: 
01:56:36 DEBUG| [stdout] firmware-version: 
01:56:36 DEBUG| [stdout] bus-info: vif-0
01:56:36 DEBUG| [stdout] supports-statistics: yes
01:56:36 DEBUG| [stdout] supports-test: no
01:56:36 DEBUG| [stdout] supports-eeprom-access: no
01:56:36 DEBUG| [stdout] supports-register-dump: no
01:56:36 DEBUG| [stdout] supports-priv-flags: no
```

Related commits:
- https://github.com/scylladb/scylla/commit/33309f66
- https://github.com/scylladb/scylla/commit/b8f40a2dffeec778549004ade9e388e7f2fd827a

@syuu1228

**Comment by glommer** [comment]
That is expected in 1.7. The AMI will not be running the amazon kernel if
we didn't backport those.

**Comment by syuu1228** [comment]
@amoskong ENA is not enabled for the release so we cannot use it, but ixgbevf should available on C3, C4, D2, I2, R3, and M4 (excluding m4.16xlarge) so you can check them.

Note: https://github.com/scylladb/scylla/commit/b8f40a2dffeec778549004ade9e388e7f2fd827a is not merged on branch-1.7, so we don't able to get the warning message.

**Comment by amoskong** [comment]
@glommer do we have plan to backport it to 1.7?

So for scylla master, the ami instance (using amazon kernel) will use ena driver, right?

**Comment by amoskong** [comment]
@syuu1228 we tested both ena and ixgbevf.

c3.2xlarge instance used ixgbevf driver as expected in job: 
http://jenkins.cloudius-systems.com/job/scylla-1.7-ami-test-amostmp/label=muninn/8/

**Comment by amoskong** [comment]
I tried to install amazon kernel to that instance, but the driver name is also 'vif'

```
[centos@ip-172-16-99-180 ~]$ uname -a
Linux ip-172-16-99-180.ec2.internal 4.4.19-29.55.amzn1.x86_64 #1 SMP Mon Aug 29 23:29:40 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
[centos@ip-172-16-99-180 ~]$ ethtool -i eth0
driver: vif
version: 
firmware-version: 
bus-info: vif-0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
[centos@ip-172-16-99-180 ~
```

**Comment by glommer** [comment]
I don't know. There are patches to the ami repo needed as well to enable it
- not just the kernel.

**Comment by syuu1228** [comment]
@amoskong @glommer It's not just amazon kernel, we need to add "EnaSupport" variable in the AMI metadata on AMI building time (or probably can add it manually after the build).
This commit enables it: https://github.com/scylladb/scylla/commit/f4502bfb79447869c7a853c711c98d749a272486

But it's not included 1.7 since we don't merge ENA/i3 things in 1.7, this commit also doesn't merged.
I just built an AMI with latest master, it has "EnaSupport" on its metadata. (1.7-rc2 AMI doesn't have)

```
[syuu@devil ~]$ aws ec2 describe-images --image-id ami-9d63fe8b|grep Ena
            "EnaSupport": true,
```

Please retry it in master, it should have different result.

**Comment by glommer** [comment]
We wont support i3 with 1.7

The changes are just too big at the time.

One avenue we are exploring is to offer an unsupported version that is
custom built.

**Comment by slivne** [comment]
@amoskong - master (1.8 ...) should have this - can you check if the nightly AMI's work on i3 and enable ena

**Comment by amoskong** [comment]
@slivne master (1.8) AMI on i3 uses 'ena' driver.

[jenkins job 121
](http://jenkins.cloudius-systems.com/job/scylla-master-ami-test/label=muninn/121/) [debug.log](http://jenkins.cloudius-systems.com/job/scylla-master-ami-test/label=muninn/121/artifact/latest/test-results/1-_home_centos_avocado_tests_jenkins_slave_workspace_scylla-master-ami-test_label_muninn_scylla-artifacts.py:ScyllaArtifactSanity.test_after_install/debug.log)
