### ISSUE TITLE
Scylla node becomes unresponsive

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#2294]
*Installation details*
Scylla version (or git commit hash): 1.7-rc2
Cluster size: 3

Glauber has noticed that under certain conditions Scylla nodes may become unresponsive (or barely responsive, serving around a fifth of the requests the other nodes can do).
Workload to reproduce:
Servers: 3x i2.8xlarge
Loaders: 10x c4.8xlarge
Load:
```bash
POP=30000000000
LOADERS=10
./ec2-stress.sh 1 -e "populate=$POP" \
    -e "command=write" -e "stress_options='-schema \"replication(factor=3)\"'" \
    -e "command_options='cl=QUORUM -mode native cql3'"  \
    -e "command_options=duration=60m" \
    -e "threads=500" \
    -e "clean_data=true" \
    -e "server=Scylla" \
    -e "seq_populate=$(($POP/$LOADERS))"
```
The problem doesn't appear in every run. Sometimes the bad node is able to recover.

**Comment by slivne** [comment]
the following patches have been applied to remove the regression in behaviour 

98d782cfe1f53873c4afae1fa0f19b5d94d8ac8d
7eedd743bf5324ab3f41da336fbce63bfee32d3f
1a77312aece718c59a618a8eca571ec96a28bda9
