### ISSUE TITLE
COPY FROM - failed to import - QueryMessage' object has no attribute 'to_binary'

### ISSUE THREAD

**Issue by tiago-msilva** [scylladb/scylla#2297]
Hi all,

ScyllaDB running from docker image scylladb/scylla
1.6.2-20170310.d41ba3b

Error in COPY FROM:
```cqlsh:test> copy info (id,data) to '/x.csv';

1 rows exported in 0.003 seconds.
cqlsh:test> copy info (id,data) from '/x.csv';

'QueryMessage' object has no attribute 'to_binary'
Aborting import at record #1. Previously inserted records are still present, and some records after that may be present as well.

1 rows imported in 0.082 seconds.```

**Comment by slivne** [comment]
@tiago-msilva can you please provide a sample schmea and sample populated data so that we can try and reproduce this (and make sure the issue is fixed).

**Comment by tiago-msilva** [comment]
Hi,

I've already had help on the Slack channel.
Just as Avi said I tried 1.7-rc2 and the issues I reported are solved.

Thanks.

I'll close this now.
