### ISSUE TITLE
COPY FROM - failed to import - Read wrong filename

### ISSUE THREAD

**Issue by tiago-msilva** [scylladb/scylla#2298]
Hi all,

ScyllaDB running from docker image scylladb/scylla
1.6.2-20170310.d41ba3b

Error in COPY FROM:
```cqlsh:test> copy info (id,data) from '/x.csv' with DELIMITER=',' ;
Can't open "/x.csv' with DELIMITER='," for reading: [Errno 2] No such file or directory: "/x.csv' with DELIMITER=',"

0 rows imported in 0.000 seconds.```

**Comment by slivne** [comment]
@tiago-msilva can you please provide a sample csv file (and a schema) so we can make sure we  resolve the issue you opened .

**Comment by tiago-msilva** [comment]
Hi,

I've already had help on the Slack channel.
Just as Avi said I tried 1.7-rc2 and the issues I reported are solved.

Thanks.

I'll close this now.
