### ISSUE TITLE
size-tiered compaction: avoid similarly-sized parallel compactions even on different shards

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#2300]
We noted in the past that it is counter-productive to do several compactions in parallel: These will compete for the same disk bandwidth (a single compaction can already do prefetching to use a lot of disk bandwidth on its own), increase memory usage, and also increase temporary disk space usage: While compaction is in progress, we use disk space for both source sstables and the new sstable. We suggested that there is one exception: When we have two compactions of wildly different sizes, we should allow them to proceed in parallel. The thinking is that a huge compaction should not delay tiny compactions (a huge compaction can take orders of magnitude more time than the tiny compaction), and possibly vice versa (we'll never find time to do a huge compaction if we always do the tiny compactions first).

It's not clear to me what happens today when we have many different column families - do we allow a single compaction (or several of different sizes) from each? Or just one? This behavior changed several times in the past so I'm no longer sure what's in the current code.

But what I'm pretty sure about is that we have a separate limit on each shard - so we can end up doing one huge compaction on each shard, in parallel. One of the things this could cause is to require a lot of free disk space during compaction. On the other hand, if we were to allow only one of those compaction to proceed in parallels, we would need only 1/N (where N=number of shards) of the temporary disk space.

So I am suggesting that perhaps the limit of one compaction per weight class should not be per shard, but rather per data directory (or per machine, if we don't have the notion of separate data directories).

However, there are two snags:
1. I'm worried that as the number of cores increase and disk hardware (and networked disks) improve, one core will no longer be enough to fully drive a disk. At that point, it will not be enough to compact on just one core.
2. I'm worried that if we keep the work of the different cpus unbalanced - one CPU does compaction while the others don't - we'll have serious load balancing issues.

Is there a way to solve both problems by having multiple shards cooperate on one compaction job? Could we possibly split every sstable to several parts (using the summary file to know where to split) and have different CPUs work on different parts of the same collection of sstables, in parallel? Sadly, this sort of design will be quite anti-Seastar-like, but I'm not sure what better to suggest?

Anybody has better ideas? Anybody think this idea is stupid and this issue should be closed?

**Comment by gleb-cloudius** [comment]
On Sun, Apr 23, 2017 at 12:34:30AM -0700, nyh wrote:
> Anybody has better ideas? Anybody think this idea is stupid and this issue should be closed?
> 
We shard CPU and memory, the problem is that we do not shard disk. Can
we assign DiskSize/ShardsNumber of disk space for each shard and make
sure that no shard uses more the that? If during compaction or regular
writes shard exceeds its limit it throw OutOfSpace exception without
waiting for error from fs.

--
			Gleb.

**Comment by nyh** [comment]
We could shard disk, but this would actually go against the idea I was trying to promote: I was trying to suggest that our (CPU) sharding can help with size-tiered-compaction's temporary disk space usage. Because even if compaction can (at worst case) require half the disk space to be free, if we only compact on one shard in parallel, we don't need half but only 1/2N. If you shard the disk space, each shard has its own separate free space, and you lose this possible advantage.

**Comment by avikivity** [comment]
Even with mediocre disks, one core is not enough to saturate them.  We really need to compact in parallel.

**Comment by nyh** [comment]
Via email @avikivity suggested a technique of splitting the sstables reminiscent of the idea I suggested above, but in a way not requiring coordination between shards:

> it's also possible to do it with the existing format by mixing some LCS into STCS.  Each output sstable is split into smaller sstables (say 2GB in size), but we keep them related.  When we compact, as soon as we generate a 2GB sstable and seal it, we can drop all input sstables that contributed to it but no longer participate in the compaction.

If we decide to go with that approach we should close this issue and open a different one just for that idea.

**Comment by avikivity** [comment]
Certainly one core (or even all cores in some installations) are not enough to keep the disk busy, so this will reduce compaction throughput significantly, in turn increasing read and space amplification.

**Comment by nyh** [comment]
Yes, you already noted this in 2017.
We keep coming back to this idea because of the temporary disk usage of STCS compactions, which can be made much lower by not doing huge compactions on all shards in parallel. I don't know if we need to do it on just one of the shards (which, as you noted, may not be powerfull enough), half of them, or not. But given that we keep thinking about this idea just in the context of preventing running out of disk, I'm closing this issue in favor of #2871 - which says that we shouldn't start additional compactions in parallel if we don't have enough empty disk space - but can still do a lot of compactions in parallel if there is plenty of disk space.
