### ISSUE TITLE
Feature request - Server side scripting - Lua perhaps

### ISSUE THREAD

**Issue by tiago-msilva** [scylladb/scylla#2304]
Hi all,

This is a feature request.
In the Slack channel @glommer already said it was planned for sometime in the future.
I would just like to add my point of view on the importance it has as a feature for the future of ScyllaDB.

Nowadays databases range from fast to ultra fast.
We have document, graph, columnar storage, K/V, column family, relational, everything.
As I see it the model that ScyllaDB chose was to use a great design (C*) and implement it in a fantastic way, using the seastar framework.
Current roadmap for ScyllaDB includes the best possible things which are to be able to fully replace Cassandra.
I totally agree with that, but...

There are some concerns for application architects, however, that may want to have you choose another database.
One such concern is data locality, how many round-trips to the DB must my application perform in order to finish one computation cycle.
Graph processing is one such example in which there is no easy modelling that transforms my computation cycles into one single DB call.
In order to do a graph traversal on a Graph where its edges or vertexes are stored on ScyllaDB a program must execute a number of reads proportional to, at least, the minimum distance of the vertexes read.
(And no, Titan:DB is not the answer here.)

If ScyllaDB had server-side scripting this would be much faster and simpler much higher data locality on the function doing the graph traversal.
Given the understanding I have on how Seastar and ScyllaDB work it would be highly effective to run lua on ScyllaDB, almost the same as running it's native code.
Lua has, on its side, its execution predictability which gets Lua as the best language this kind of _embedded_ situations.

ArangoDB's AQL, Cassandra's UDFs and many more have features that enable the database to behave well in situations where the modelling doesn't allow much room for improvement...

With this feature things like Titan:DB and spark could be replaced where the use case didn't fit the original use case for those.
Real time processing on ScyllaDB would allow for much deeper and specific use cases turning ScyllaDB in a much desirable DB for many architectures.

Just my 2 cents, hope it helped...

Thanks for an amazing product.

Tiago

**Comment by tzach** [comment]
related to #2204

**Comment by bhalevy** [comment]
@espindola

**Comment by sanxore** [comment]
I'm looking forward to this feature

**Comment by bhalevy** [comment]
@tzach what else do you see done in the context of this issue on top of #2204?
Can this one be closed as duplicate?

**Comment by tzach** [comment]
Server side side scripting can means much more then UDF (#2204).
Examples can be map/reduce like functions, off line scripting and more.

Having say that, keeping a high level issue is not useful, and we should open a feature per each of the above. @tiago-msilva feel free to reopen if you wish to comment.
