### ISSUE TITLE
lack of tombstone removal compaction

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#2306]
When disk space is low (also at some interval), compaction strategy will now choose for compaction the
sstable with the highest droppable tombstone ratio. We can determine droppable tombstone ratio for each sstable because they store a histogram with expiration time as the key.

This feature is really needed because droppable tombstones may be forgotten in the oldest sstables (as with size tiered compaction strategy), wasting disk space. So it will basically work towards reclaiming this wasted disk space.

**Comment by raphaelsc** [comment]
'[RFC 0/9] introduce tombstone removal compaction' was posted to mailing list a few months go.

**Comment by slivne** [comment]
@raphaelsc - can you reiterate on the patchset - lets advance this.

**Comment by raphaelsc** [comment]
On Thu, May 25, 2017 at 7:28 AM, Shlomi Livne <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> - can you reiterate on the
> patchset - lets advance this.
>

@slivne: sure.
