### ISSUE TITLE
UX: scylla_setup: can't auto select (disk & nic) in non-interactive mode

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2309]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20170412.0318dcc
Cluster size: 1

If we execute scylla_setup with options, it will enter  non-interactive mode.
Currently we need to assign the unused disks,  specify nic in non-interactive mode.

Expect result:
If raid setup isn't disabled and disk isn't assigned in cmdline, then always auto select unused disk.
If nic setup isn't disabled and specify nic isn't assigned in cmdline, then always auto select invalid nic.

Current scylla_setup force request disks and nic parameters in non-interactive mode:
```
if [ $INTERACTIVE -eq 0 ] && [ $RAID_SETUP -eq 1 ] && [ "$DISKS" = "" ]; then
    print_usage
fi
if [ $INTERACTIVE -eq 0 ] && [ $SYSCONFIG_SETUP -eq 1 ] && [ "$NIC" = "" ]; then
    print_usage
fi
```
@syuu1228

**Comment by tzach** [comment]
Good catch, This is important for everyone trying to automate Scylla install

**Comment by syuu1228** [comment]
> If raid setup isn't disabled and disk isn't assigned in cmdline, then
always auto select unused disk.

Automatically tuneup NIC sounds okay, but automatically format unused disk
sounds  dangerous...
I think current "print_usage && exit 1" approach is correct for this.
But if it's not easy to understand, maybe we should shows up an error
message something like "Please specify disks for RAID".

> If nic setup isn't disabled and specify nic isn't assigned in cmdline,
then always auto select invalid nic

What the method to pick default NIC from multiple network interface?
Maybe guess right one from default gateway?
But default gateway can multiple (rare case though, maybe can pick first
one)

**Comment by amoskong** [comment]
The original purpose:
- I don't want to rewrite get_unused_disks() outside scylla_setup script.
- current non-interactive mode should be smart as interactive mode (auto select uniq nic)
- re-enter interactive mode in requesting users' input (eg: has multiple nics, disks isn't assigned)

Currently Interactive mode scylla_setup only lists unused disks and users need to select by themselves. I agree with you that automatically select and format unused disk is dangerous, we can't do that.

Currently Interactive mode scylla_setup will automatically select the uniq useful nic, we need this in current non-interactive mode.

Is it possible to add an option to enable/disable additional interactive mode? Then we don't need to assign disks in cmdline and select disk in interactive mode. It might make thing complex.

- If the subsetup already been disabled in cmdline, then skip the interactive of the subsetup.
- if the subsetup is enabled by default or enabled in cmdline, and request parameter isn't assigned, then try to get the parameter by interactive. (eg: disks, nic)

**Comment by syuu1228** [comment]
@amoskong 
> Currently Interactive mode scylla_setup will automatically select the uniq useful nic, we need this in current non-interactive mode.
Ah okay, then it's very easy to implement. 
But it's the feature to skip interactive NIC selector when the environment has only one NIC, so it won't work when user has multiple NICs including virtual one(like virbr0 for libvirt).

**Comment by syuu1228** [comment]
@amoskong 
> Is it possible to add an option to enable/disable additional interactive mode? Then we don't need to assign disks in cmdline and select disk in interactive mode. It might make thing complex.

I think this is not really "non-interactive mode"...
If you feel current interactive mode is too much verbose and want to setup the environment almost automatically(means excluding RAID), maybe we can add an argument to suppress question for each setup something like "--yes".

**Comment by amoskong** [comment]
`auto select uniq nic in non-interactive mode` isn't high priority.

Current way for automation:
- select disk and pass it to scylla_setup by `--disks `
- use '--no-xxx' to skip some steps

It's acceptable/fine for me, you can close this issue.
