### ISSUE TITLE
Question about using multiple network interfaces

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2314]
ScyllaDB Version : scylla-1.6.1-20170218.2ea4da2.el7.centos.x86_64

I am setting multiple network interface.
after starting seed node, I found scylla which listen on both listen_address and broadcast_address with two network interfaces.

[PROD-root]swfosldb01:/root>netstat -nap | grep scylla | grep LISTEN
tcp        0      0 10.x.x.101:9160       0.0.0.0:*               LISTEN      31258/scylla
tcp        0      0 10.x.x.101:10000      0.0.0.0:*               LISTEN      31258/scylla
tcp        0      0 10.x.x.101:9042       0.0.0.0:*               LISTEN      31258/scylla
tcp        0      0 10.x.x.101:7000       0.0.0.0:*               LISTEN      31258/scylla
tcp        0      0 192.x.x.101:7000    0.0.0.0:*               LISTEN      31258/scylla
tcp        0      0 0.0.0.0:9180            0.0.0.0:*               LISTEN      31258/scylla
tcp6       0      0 127.0.0.1:7199          :::*                    LISTEN      31275/scylla-jmx
tcp6       0      0 127.0.0.1:50241         :::*                    LISTEN      31275/scylla-jmx

But when I started node#2, node#2 can not find seed node so starting node#2 failed
Apr 26 10:37:57 swfosldb02 scylla: [shard 0] gossip - Connect seeds again ... (255 seconds passed)
Apr 26 10:37:58 swfosldb02 scylla: [shard 0] rpc - client 10.40.74.101: fail to connect: Connection timed out

Could you check if there is a problem with my settings

10.x.x.x ==> public ip
192.x.x.x ==> private ip

<Node#1 seed>
seed_provider:
          - seeds: "10.x.x.101"
listen_address: 192.x.x.101
listen_on_broadcast_address: true
broadcast_address: 10.x.x.101
endpoint_snitch: GossipingPropertyFileSnitch
rpc_address: 10.x.x.101
api_address: 10.x.x.101
broadcast_rpc_address: 10.x.x.101

<Node#2 >
seed_provider:
          - seeds: "10.x.x.101"
listen_address: 192.x.x.102
listen_on_broadcast_address: true
broadcast_address: 10.x.x.102
endpoint_snitch: GossipingPropertyFileSnitch
rpc_address: 10.x.x.102
api_address: 10.x.x.102
broadcast_rpc_address: 10.x.x.102

<cassandra-rackdc.properties>
dc=my_data_center
rack=my_rack
prefer_local=true

**Comment by infordb** [comment]
The current situation is that node#2 is trying to connect an external network(10.x.x.101/seed) through the internal network(192.x.x.102)
so  connect fail occurs

**Comment by dorlaor** [comment]
@eyalgutkind @nirmaayan can you please check if this is a configuration problem or not?

**Comment by slivne** [comment]
@infordb 

Please explain what you are trying to achieve - what is supposed to run on either interface.

Please note that we have a guide explaining how to setup networking onAWS in cases of multi-dc networking http://docs.scylladb.com/procedures/ec2_dc/#create-a-scylla-cluster-on-ec2-single-or-multi-data-center - which may help if you are trying to achieve the same.

**Comment by infordb** [comment]
@slivne 
When there are two network interfaces in baremetal server
(One for internal  and the other for external) 
I wonder how to set the parameters below

seeds	
listen_address	     
rpc_address	         
broadcast_address	 
broadcast_rpc_address

**Comment by slivne** [comment]
@vladzcloudius can you please help here 

and we will add it to the docs

**Comment by slivne** [comment]
closing the issue since its fixed in 2.0.3
