### ISSUE TITLE
scylla_kernel_check reports Ubuntu 14.04's default kernel is "supported kernel version"

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#2317]
*Installation details*
Scylla version (or git commit hash): d4b6e430ed7b8f67a7d4ca460c9c45b3a81b289c
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-772aa961

According to our knowledge base page, Scylla requires >= 3.15 kernel but our kernel checker says we supported kernel 3.13:
```
ubuntu@ip-10-178-95-247:~$ uname -r
3.13.0-116-generic
ubuntu@ip-10-178-95-247:~$ sudo scylla_setup
Skip any of the following steps by answering 'no'
Do you want to run kernel version check?
Answer yes to have this script verify that the currently installed kernel is qualified to run Scylla; answer no to skip this check.
[YES/no]
This is a supported kernel version.
```

Since the script calling iotune --fs-check, it's probably iotune problem.

**Comment by avikivity** [comment]
Ubuntu 14.04 is no longer supported, closing.
