### ISSUE TITLE
scylla_kernel_check causes error on Joyent container

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#2318]
*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): Joyent container
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

Seems we don't have /dev/loop* inside Joyent container, we don't able to use current scylla_kernel_check script.
```
[root@387a861e-f391-47d8-d4e0-a8763dc801e4 ~]# ls /dev/loop*
ls: cannot access /dev/loop*: No such file or directory
[root@387a861e-f391-47d8-d4e0-a8763dc801e4 ~]# scylla_setup
Skip any of the following steps by answering 'no'
Do you want to run kernel version check?
Answer yes to have this script verify that the currently installed kernel is qualified to run Scylla; answer no to skip this check.
[YES/no]
mount: /var/tmp/kernel-check.img: failed to setup loop device: No such file or directory
```

**Comment by avikivity** [comment]
No real users on Joyent, closing.
