### ISSUE TITLE
nodetool clearsnapshot

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#232]
Removes one or more snapshots.
http://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsClearSnapShot.html

Used in #101

**Comment by vladzcloudius** [comment]
Check different 'nodetool clearsnapshot' options

        1. Use a single node and create a keyspace ks0 + table cf.
        2. Create a keyspace ks1 + table cf.
        3. Insert data into both tables above.
        4. Create a snapshot snapshot0.
        5. Add more data to both keyspaces and create a snapshot snapshot1.
        6. Add more data to both keyspaces and create a snapshot snapshot2.
        7. Call 'nodetool clearsnapshot -t snapshot0'.
        8. Check that
            1. snapshot0 has been deleted in both keyspaces.
            2. snapshot1 and snapshot2 are still present and haven't been touched.
        9. Call 'nodetool clearsnapshot -t snapshot1 -- ks1' and check that
            1. snapshot1 has been removed from ks1 and not from ks0.
            2. snapshot2 is still present and hasn't been touched.
        10. Call 'nodetool clearsnapshot' and check that all snapshots have been removed.

**Comment by vladzcloudius** [comment]
And a second test that verifies that `clearsnapshot` of one snapshot doesn't change the content (not just file names) of another snapshot.

1. Use a single node and create a keyspace ks + table cf.
2. Insert data into ks.cf.
3. Create a `snapshot0` and a `snapshot1` snapshots.
4. Copy files from `snapshot1` directory aside.
5. Call `nodetool clearsnapshot -t snapshot0`.
6. Check that copied aside files are identical to the corresponding files in a `snapshot1` directory.

**Comment by slivne** [comment]
@vladzcloudius are this tests passing can we close this

**Comment by vladzcloudius** [comment]
@slivne Yep. Both are passing.
