### ISSUE TITLE
Sstable reads with clustering restrictions of a large partition may miss range tombstones relevant for the range

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2326]
*Installation details*
Scylla version (or git commit hash): 1.4+

Suppose the promoted index looks like this:

block0:  start=1 end=2
block1:  start=4 end=5

start and end are cell names of the first and last cell in the block.

If there is a range tombstone covering [2,3], it will be only in block0, because it is no longer in effect when block1 starts. However, slicing the index for [3, +inf], which intersects with the tombstone, will yield block1. That's because the slicing looks for a block with an end which is greater than or equal to the start of the slice:

```
                     if (!found_range_start) {
                         if (!range_start || cmp(range_start->value(), end_ck) <= 0) {
                             range_start_pos = ie.position() + offset;
```

We should take into account that any given block may actually contain information for anything up to the start of the next block, so instead of using end_ck, effectively use next block's start_ck (exclusive).

**Comment by tgrabiec** [comment]
Refs #2213

**Comment by slivne** [comment]
backport to 1.7 and earlier supported releases
