### ISSUE TITLE
Scylla may write incorrect cell names in promoted index blocks

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2333]
*Installation details*
Scylla version (or git commit hash): 1.4+

When promoted index block starts on a range tombstone, `maybe_flush_pi_block()` is invoked like this:

```
    auto start = composite::from_clustering_element(_schema, std::move(rt.start));
    _sst.maybe_flush_pi_block(_out, start, {});
```

from_clustering_element() always creates a composite with eoc=0. But it's a range start, so eoc may be != 0. This information is lost.

Suppose rt.start is a prefix (1, eoc=1), which sorts after the key of (1, 2). It will be effectively transformed here to a cell name (1, eoc=0), which sorts before (1, 2), breaking the ordering.

**Comment by nyh** [comment]
I think you are right :-(
Seems like maybe_flush_pi_block needs to take the eoc as paramter instead of assuming it is  composite::eoc::none as it does now?
write_range_tombstone, for example, also takes the eoc in addition to the composite.
`components_writer::consume(range_tombstone&& rt)` has the necessary information, in rt.start_kind.

**Comment by tgrabiec** [comment]
That's a possible fix. Maybe it would be cleaner to create a correct `composite` object (with appropriate eoc) from the start though.

**Comment by slivne** [comment]
backport to 1.7 and earlier supported releases

**Comment by duarten** [comment]
Any pointers about how this problem might manifest in practice? Trying to write a unit test exposing it.

**Comment by tgrabiec** [comment]
@duarten I would try to trigger the problem by configuring sstable writer to generate index entry for every cell (see `test_repeated_tombstone_skipping` in sstable_datafile_test.cc) and write specific mutation fragments like in the bug description. Then I'd try to do index lookups. If order is violated, be can expect some undefined behavior.

**Comment by duarten** [comment]
@tgrabiec Thanks! I think I'll need some more pointers though, I'm not very familiar with these parts. So far I have:

```
        auto dir = make_lw_shared<tmpdir>();
        schema_builder builder("ks", "cf");
        builder.with_column("p", utf8_type, column_kind::partition_key);
        builder.with_column("c1", int32_type, column_kind::clustering_key);
        builder.with_column("c2", int32_type, column_kind::clustering_key);
        builder.with_column("v", int32_type);
        auto s = builder.build();

        auto k = partition_key::from_exploded(*s, {to_bytes("key1")});
        auto ck = clustering_key::from_exploded(*s, {int32_type->decompose(1), int32_type->decompose(2)});
        mutation m(k, s);
        auto cell = atomic_cell::make_live(1, int32_type->decompose(88), { });
        m.set_clustered_cell(ck, *s->get_column_definition("v"), std::move(cell));

        m.partition().apply_row_tombstone(*s, range_tombstone(
                clustering_key_prefix::from_exploded(*s, {int32_type->decompose(1)}),
                bound_kind::excl_start,
                clustering_key_prefix::from_exploded(*s, {int32_type->decompose(2)}),
                bound_kind::incl_end,
                {1, gc_clock::now()}));

        auto mt = make_lw_shared<memtable>(s);
        mt->apply(std::move(m));

        auto sst = make_lw_shared<sstables::sstable>(s,
                                dir->path,
                                1 /* generation */,
                                sstables::sstable::version_types::ka,
                                sstables::sstable::format_types::big);
        sstable_writer_config cfg;
        cfg.promoted_index_block_size = 1;
        sst->write_components(mt->make_reader(s), 1, s, cfg, sstable_write_permit::unconditional()).get();
        sst->load().get();
```

I'm issuing `mutation_queries` on `sst->as_mutation_source()`, but so far I'm getting back normal results.

These are the lookups I'm doing, but I'm not sure they qualify as index lookups:

```
        auto prange = dht::partition_range::make_singular(dht::global_partitioner().decorate_key(*s, k));
        query::partition_slice::option_set opts;
        opts.set(query::partition_slice::option::send_clustering_key);
        opts.set(query::partition_slice::option::send_partition_key);
        query::clustering_row_ranges ck_ranges = { query::clustering_range::make_starting_with(ck) };
        auto slice = query::partition_slice(std::move(ck_ranges), {}, {0}, opts);
        auto res = mutation_query(s, sst->as_mutation_source(), prange, slice, query::max_rows, query::max_partitions, gc_clock::now()).get0();
```

**Comment by tgrabiec** [comment]
@duarten Maybe your index lookups are just lucky, or something is masking the bug. Try enabling `trace`-level logging on `sstable` logger to see how index looks like during reading. If it's bad but your read is fine, try with more cells and tombstones.

Do you validate that you get expected (tombstoned) data back? There's `assert_that().produces()` with optional clustering range to limit scope of comparison.

**Comment by duarten** [comment]
@tgrabiec Thanks for the tips. I still haven't been able to trigger anything, but I'm slowly getting acquainted with the code. 

With a row with `ck{1:2}` and a `rt({1}, {2}])`, and  `promoted_index_size` set to 1, we'll have two promoted index blocks `[{1:2}]` and `[{1}]`. All queries I do on this return the correct results. `mp_row_consumer` might be masking some bugs.

I also think there's another issue: when we use the start bound of a range tombstone to close a promoted index block, we should invert the eoc.

**Comment by duarten** [comment]
Example trace for the description above, obtained by querying for the range `[{1:2}, 1]` in a single partition:

```
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: index_reader for /tmp/tmpdir_n73Eg0/ks-cf-ka-1-Data.db
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: advance_to({0x60100040fc70, pk{00046b657931}, w=0}), _previous_summary_idx=0, _current_summary_idx=0
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: first entry
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: advance_to_page(0)
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: page:
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable -   {key: pk{00046b657931}, token:1573573083296714675} -> 0
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008700: index_reader for /tmp/tmpdir_n73Eg0/ks-cf-ka-1-Data.db
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008700: advance_past({position: 1:ckp{000400000001000400000002}}), current data_file_pos=0
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008700: advance_to_next_partition()
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008700: advance_to_end()
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - reader 0x601000059c00: reading partition
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - reader 0x601000059c00: read from index
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - mp_row_consumer 0x601000059c10: set_up_ck_ranges(pk{00046b657931})
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - mp_row_consumer 0x601000059c10: advance_context({position: -1:ckp{000400000001}})
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: advance_to({position: -1:ckp{000400000001}}), current data_file_pos=0
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: promoted index:
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable -   {{value=00000001; eoc=0x00}, {value=00000002; eoc=0x00}, {value=; eoc=0x00}, compound=1, static=0}-{{value=00000001; eoc=0x00}, {value=00000002; eoc=0x00}, {value=76; eoc=0x00}, compound=1, static=0}: +18 len=37
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable -   {{value=00000001; eoc=0x00}, compound=1, static=0}-{{value=00000001; eoc=0x00}, compound=1, static=0}: +55 len=62
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: position in current block
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - data_consume_rows_context 0x60100007dce0: skip_to(0 -> 0, el=0)
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=0, size=119
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=7, size=99
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=15, size=80
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - mp_row_consumer 0x601000059c10: flush_if_needed({position: 0:ckp{000400000001000400000002}})
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - mp_row_consumer 0x601000059c10: advance_to({position: 0:ckp{000400000001000400000002}}) => out_of_range=0, skip_in_progress=0
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=5, size=64
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=7, size=62
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=19, size=54
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - mp_row_consumer 0x601000059c10: flush_if_needed(in_progress={mutation_fragment: clustering row {position: 0:ckp{000400000001000400000002}} {clustering_row: ck ckp{000400000001000400000002} t {row_tombstone: none} row_marker {missing row_marker} cells {row: {column: 0 01000000000000000100000058}}}}, ready=null, skip=0)
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - mp_row_consumer 0x601000059c10: flush(in_progress={mutation_fragment: clustering row {position: 0:ckp{000400000001000400000002}} {clustering_row: ck ckp{000400000001000400000002} t {row_tombstone: none} row_marker {missing row_marker} cells {row: {column: 0 01000000000000000100000058}}}}, ready=null, skip=0)
TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - mp_row_consumer 0x601000059c10: advance_to({range_tombstone: start={bound: prefix=ckp{000400000001}, kind=excl start}, end={bound: prefix=ckp{000400000002}, kind=incl end}, {tombstone: timestamp=1, deletion_time=1500897179}}) => out_of_range=1, skip_in_progress=1
```
This returns the following result:

```
{rows=1, short_read=false, [{rows=1, {ks.cf key {key: pk{00046b657931}, token:1573573083296714675} data {mutation_partition: {tombstone: none} () static cont=1 {row: } clustered {rows_entry: cont=true dummy=false ckp{000400000001000400000002} {deletable_row: {missing row_marker} {row_tombstone: none} {row: {column: 0 01000000000000000100000058}}}}}}}]}
```

**Comment by tgrabiec** [comment]
2017-07-24 17:56 GMT+02:00 Duarte Nunes <notifications@github.com>:

> Example trace for the description above, obtained by querying for the
> range [{1:2}, 1] in a single partition:
>
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: index_reader for /tmp/tmpdir_n73Eg0/ks-cf-ka-1-Data.db
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: advance_to({0x60100040fc70, pk{00046b657931}, w=0}), _previous_summary_idx=0, _current_summary_idx=0
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: first entry
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: advance_to_page(0)
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: page:
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable -   {key: pk{00046b657931}, token:1573573083296714675} -> 0
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008700: index_reader for /tmp/tmpdir_n73Eg0/ks-cf-ka-1-Data.db
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008700: advance_past({position: 1:ckp{000400000001000400000002}}), current data_file_pos=0
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008700: advance_to_next_partition()
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008700: advance_to_end()
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - reader 0x601000059c00: reading partition
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - reader 0x601000059c00: read from index
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - mp_row_consumer 0x601000059c10: set_up_ck_ranges(pk{00046b657931})
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - mp_row_consumer 0x601000059c10: advance_context({position: -1:ckp{000400000001}})
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: advance_to({position: -1:ckp{000400000001}}), current data_file_pos=0
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: promoted index:
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable -   {{value=00000001; eoc=0x00}, {value=00000002; eoc=0x00}, {value=; eoc=0x00}, compound=1, static=0}-{{value=00000001; eoc=0x00}, {value=00000002; eoc=0x00}, {value=76; eoc=0x00}, compound=1, static=0}: +18 len=37
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable -   {{value=00000001; eoc=0x00}, compound=1, static=0}-{{value=00000001; eoc=0x00}, compound=1, static=0}: +55 len=62
> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: position in current block
>
> Index lookup sees that the lower bound of the query range is smaller than
the first entry and doesn't do any lookups. Try emitting more unrelated
cells, especially a cell with a key which is smaller than the lower bound
of the query.

**Comment by tgrabiec** [comment]
2017-07-25 9:37 GMT+02:00 Tomasz Grabiec <tgrabiec@gmail.com>:

>
>
> 2017-07-24 17:56 GMT+02:00 Duarte Nunes <notifications@github.com>:
>
>> Example trace for the description above, obtained by querying for the
>> range [{1:2}, 1] in a single partition:
>>
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: index_reader for /tmp/tmpdir_n73Eg0/ks-cf-ka-1-Data.db
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: advance_to({0x60100040fc70, pk{00046b657931}, w=0}), _previous_summary_idx=0, _current_summary_idx=0
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: first entry
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: advance_to_page(0)
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: page:
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable -   {key: pk{00046b657931}, token:1573573083296714675} -> 0
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008700: index_reader for /tmp/tmpdir_n73Eg0/ks-cf-ka-1-Data.db
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008700: advance_past({position: 1:ckp{000400000001000400000002}}), current data_file_pos=0
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008700: advance_to_next_partition()
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008700: advance_to_end()
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - reader 0x601000059c00: reading partition
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - reader 0x601000059c00: read from index
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - mp_row_consumer 0x601000059c10: set_up_ck_ranges(pk{00046b657931})
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - mp_row_consumer 0x601000059c10: advance_context({position: -1:ckp{000400000001}})
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: advance_to({position: -1:ckp{000400000001}}), current data_file_pos=0
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: promoted index:
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable -   {{value=00000001; eoc=0x00}, {value=00000002; eoc=0x00}, {value=; eoc=0x00}, compound=1, static=0}-{{value=00000001; eoc=0x00}, {value=00000002; eoc=0x00}, {value=76; eoc=0x00}, compound=1, static=0}: +18 len=37
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable -   {{value=00000001; eoc=0x00}, compound=1, static=0}-{{value=00000001; eoc=0x00}, compound=1, static=0}: +55 len=62
>> TRACE 2017-07-24 13:52:59,728 [shard 0] sstable - index 0x601000008980: position in current block
>>
>> Index lookup sees that the lower bound of the query range is smaller than
> the first entry and doesn't do any lookups. Try emitting more unrelated
> cells, especially a cell with a key which is smaller than the lower bound
> of the query.
>

But to make the unit test catch all cases, perhaps what we should check is
this:

assert_that(sst->index()).has_monotonic_positions();

**Comment by duarten** [comment]
I've tried that; the issue is that the index blocks are emitted in the correct order, and that tombstones are repeated in the data file, and that `mp_row_consumer` can deal with out of order tombstones.

So, for 4 clustering keys and 1 range tombstone `(1, 2]`, we can have the following index blocks (`start` equal to `end`, although `end` never seems to be used): `{1:2}, {1:3}, {1:6}, [1, {3:9}`.

An upper bound smaller or equal than `1]` won't include the tombstone.

A lower bound equal to `{1:6}` results in the correct results being returned:

```
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable -   {{value=00000001; eoc=0x00}, {value=00000002; eoc=0x00}, {value=; eoc=0x00}, compound=1, static=0}-{{value=00000001; eoc=0x00}, {value=00000002; eoc=0x00}, {value=76; eoc=0x00}, compound=1, static=0}: +18 len=37
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable -   {{value=00000001; eoc=0x00}, {value=00000004; eoc=0x00}, {value=; eoc=0x00}, compound=1, static=0}-{{value=00000001; eoc=0x00}, {value=00000004; eoc=0x00}, {value=76; eoc=0x00}, compound=1, static=0}: +55 len=37
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable -   {{value=00000001; eoc=0x00}, {value=00000006; eoc=0x00}, {value=; eoc=0x00}, compound=1, static=0}-{{value=00000001; eoc=0x00}, {value=00000006; eoc=0x00}, {value=76; eoc=0x00}, compound=1, static=0}: +92 len=37
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable -   {{value=00000001; eoc=0x00}, compound=1, static=0}-{{value=00000001; eoc=0x00}, compound=1, static=0}: +129 len=62
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable -   {{value=00000003; eoc=0x00}, {value=00000009; eoc=0x00}, {value=; eoc=0x00}, compound=1, static=0}-{{value=00000003; eoc=0x00}, {value=00000009; eoc=0x00}, {value=76; eoc=0x00}, compound=1, static=0}: +191 len=37
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable - index 0x601000008980: skipped to cell, _current_pi_idx=2, _data_file_position=55
```

This is where I would expect things to fail, but if you notice, the upper bound is index 2, which corresponds to the `{1:6}` block, meaning we'll try to read the previous block in the datafile. Indeed we do:

```
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable - data_consume_rows_context 0x60100007dce0: skip_to(0 -> 55, el=1)
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable - mp_row_consumer 0x601000059c10: reset(1)
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=5, size=175
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=7, size=173
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=15, size=154
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable - mp_row_consumer 0x601000059c10: flush_if_needed({position: 0:ckp{000400000001000400000004}})
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable - mp_row_consumer 0x601000059c10: advance_to({position: 0:ckp{000400000001000400000004}}) => out_of_range=0, skip_in_progress=1
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=5, size=138
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=7, size=136
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=15, size=117
TRACE 2017-07-25 13:30:38,094 [shard 0] sstable - mp_row_consumer 0x601000059c10: flush_if_needed({position: 0:ckp{000400000001000400000006}})
```

This seems a bit strange to me, but `{1:4}` is ignored and we end up returning the correct results.

A lower bound smaller than `(1`, such as `{1:7}` results in:

1. With an upper bound of `1]`:

```
TRACE 2017-07-25 12:12:54,642 [shard 0] sstable - index 0x601000008980: promoted index:
TRACE 2017-07-25 12:12:54,642 [shard 0] sstable -   {{value=00000001; eoc=0x00}, {value=00000002; eoc=0x00}, {value=; eoc=0x00}, compound=1, static=0}-{{value=00000001; eoc=0x00}, {value=00000002; eoc=0x00}, {value=76; eoc=0x00}, compound=1, static=0}: +18 len=37
TRACE 2017-07-25 12:12:54,642 [shard 0] sstable -   {{value=00000001; eoc=0x00}, {value=00000004; eoc=0x00}, {value=; eoc=0x00}, compound=1, static=0}-{{value=00000001; eoc=0x00}, {value=00000004; eoc=0x00}, {value=76; eoc=0x00}, compound=1, static=0}: +55 len=37
TRACE 2017-07-25 12:12:54,642 [shard 0] sstable -   {{value=00000001; eoc=0x00}, {value=00000006; eoc=0x00}, {value=; eoc=0x00}, compound=1, static=0}-{{value=00000001; eoc=0x00}, {value=00000006; eoc=0x00}, {value=76; eoc=0x00}, compound=1, static=0}: +92 len=37
TRACE 2017-07-25 12:12:54,642 [shard 0] sstable -   {{value=00000001; eoc=0x00}, compound=1, static=0}-{{value=00000001; eoc=0x00}, compound=1, static=0}: +129 len=62
TRACE 2017-07-25 12:12:54,642 [shard 0] sstable -   {{value=00000003; eoc=0x00}, {value=00000009; eoc=0x00}, {value=; eoc=0x00}, compound=1, static=0}-{{value=00000003; eoc=0x00}, {value=00000009; eoc=0x00}, {value=76; eoc=0x00}, compound=1, static=0}: +191 len=68
TRACE 2017-07-25 12:12:54,642 [shard 0] sstable - index 0x601000008980: skipped to cell, _current_pi_idx=4, _data_file_position=129
TRACE 2017-07-25 12:12:54,642 [shard 0] sstable - data_consume_rows_context 0x60100007dce0: skip_to(0 -> 129, el=1)
TRACE 2017-07-25 12:12:54,642 [shard 0] sstable - mp_row_consumer 0x601000059c10: reset(1)
TRACE 2017-07-25 12:12:54,642 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=5, size=62
TRACE 2017-07-25 12:12:54,642 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=7, size=60
TRACE 2017-07-25 12:12:54,642 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=19, size=52
TRACE 2017-07-25 12:12:54,642 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=5, size=31
TRACE 2017-07-25 12:12:54,642 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=7, size=29
TRACE 2017-07-25 12:12:54,642 [shard 0] sstable - data_consume_row_context 0x60100007dce0: state=19, size=21
```

  The upper bound is the index 4, so we'll go to data file position corresponding to the previous 
  index, that of the tombstone. We read the tombstone, but we ignore it due to #1203.

  Btw, in the trace above, it's weird that we consume two tombstones; might be because we repeat 
  them in the data file.

2. With an upper bound of `2]`:

Similar to the above, but the tombstone is returned at the end.

3. With an upper bound of `4]`: 

Similar to the above, but the tombstone and the last row are returned.

The cases where we might skip the tombstone are handled by the fact that tombstones are repeated in the data file after an index block is written if they still cover the current key.

Unless I'm being dense and missing a way to trigger an error, I think the best is to do as you suggest and implement `has_monotonic_positions()`. In fact, this is the only way to catch the bug I think exists due to us not reversing the eoc when using the start bound of a range tombstone as the end of an index block.

**Comment by duarten** [comment]
Quick question: for a range tombstone (1, x], a promoted index of size 1 will have start == end, meaning it will have the invalid range (1, 1]. I guess we should write the end of a promoted index block with eoc::none when start == end?

**Comment by tgrabiec** [comment]
2017-07-27 1:42 GMT+02:00 Duarte Nunes <notifications@github.com>:

> Quick question: for a range tombstone (1, x], a promoted index of size 1
> will have start == end, meaning it will have the invalid range (1, 1]. I
> guess we should write the end of a promoted index block with eoc::none when
> start == end?
>

As far as I remember the promoted index entries store first and last cell
names of cells in that block, so it's expected for them to be the same if
there is a single cell. Why do you think it should be otherwise?

**Comment by duarten** [comment]
Oh, I wouldn't. I wasn't thinking of them as just cell names, but that's what they are. There's no issue.
