### ISSUE TITLE
Counter cells in static rows are not converted to shards

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#2334]
*Installation details*
Scylla version (or git commit hash): 14b9aa228537c4e4543f1195a1eb2475cdd73148

@elcallio has noticed that counter cells are not converted from counter updates to counter shards. This results in an abort when Scylla tries to access such cells later expecting them to contain shards.

For example:
```cql
> create table cf (pk int, ck int, s counter static, v counter, primary key (pk, ck));
> update cf set s=s+5, v=v+4 where pk = 0 and ck = 1;
> select * from cf;
...scylla crashes...
```

**Comment by slivne** [comment]
@tzach - should be included in 1.7 release notes
