### ISSUE TITLE
nodetool cfstats

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#234]
Provides statistics about tables.
http://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsCFstats.html

**Comment by slivne** [comment]
@amnonh - is this done - can we close the issue, please specify the commit if it is done

**Comment by amnonh** [comment]
It is done
on jmx:
a90e080ee63817083c38ecb4ce6e6b2d8a1d3020
scylla:
4ca4efbc9ce936a8adac5fdfb61d72a068ee6e21

**Comment by slivne** [comment]
are there items we are missing - or is it all complete - if there are items we are missing please open a separate bug for them
