### ISSUE TITLE
ubuntu14.04: softlink to configure file isn't recreated after raid setup

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2342]
*Installation details*
Scylla version (or git commit hash): 1.5.4-20170427.f58104c
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 14.04

CentOS and Ubuntu 16.04 is fine.
This problem isn't regression

Post script created a softlink in `/var/lib/scylla` directory by `ln -sfT /etc/scylla /var/lib/scylla/conf`.
But the softlink isn't lost after raid setup, scylla-server fails to start

Error msg in syslog:
```
May  2 11:19:38 ubuntu14 scylla:  [shard 0] init - Could not read configuration file conf/scylla.yaml: std::invalid_argument (Could not open file at conf/scylla.yaml. Make sure it exists)
May  2 11:19:38 ubuntu14 scylla:  [shard 0] seastar - Exiting on unhandled exception: std::invalid_argument (Could not open file at conf/scylla.yaml. Make sure it exists)
```

Without raid setup:
```
root@ubuntu14:/var/log# ls  /var/lib/scylla -l
total 0
drwxr-xr-x 2 scylla scylla  6 Apr 27 09:53 commitlog
lrwxrwxrwx 1 root   root   11 May  2 10:42 conf -> /etc/scylla
drwxr-xr-x 2 scylla scylla  6 Apr 27 09:53 coredump
drwxr-xr-x 2 scylla scylla  6 Apr 27 09:53 data
```

With raid setup:
```
root@ubuntu14:/var/log# ls  /var/lib/scylla -l
total 0
drwxr-xr-x 2 scylla scylla 6 May  2 10:44 commitlog
drwxr-xr-x 2 scylla scylla 6 May  2 10:44 coredump
drwxr-xr-x 2 scylla scylla 6 May  2 10:52 data
```

@syuu1228

**Comment by amoskong** [comment]
Related to issue #2236

We need to backport this commit:
https://github.com/scylladb/scylla/commit/b087616a6ce6aaff521c270f4f07bef99160fd0c

@slivne

**Comment by penberg** [comment]
Fixed by https://github.com/scylladb/scylla/commit/32cd286a5c694706010378c64ad0e03ac082a69f

**Comment by penberg** [comment]
You did all the hard work, @amoskong, thanks!
