### ISSUE TITLE
Repair - streaming reads and reads ahead are much larger than they should be (using "Fix partition estimation")

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#2349]
*Installation details*
Scylla version (or git commit hash): 66e3b73b9c7aee32a9dcbd1f3434610498155f9a
Cluster size: 4 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): AMI

Following Asias patch 66e3b73b9c7aee32a9dcbd1f3434610498155f9a using a data set of 1TB, the checksum phase takes 9 hours (vs 30 minutes before the patch).
During these 9 hours we read for checksum 17.5/13/13/13 TB, we also read ahead and discard 9/6/6/6 TB.

![screen shot 2017-05-03 at 18 08 55](https://cloud.githubusercontent.com/assets/20959584/25667268/b0093b80-302b-11e7-8497-0bf4a7a63b54.png)

During repair we found 70 differing ranges, and each one had ~40-70 partitions.

```
cqlsh> select count(*) from keyspace1.standard1 where token(key) > 6648125379883776222 and token(key) <  6648126008746594309;

 count
-------
    47

(1 rows)
cqlsh> select count(*) from keyspace1.standard1 where token(key) > -7395064366417291245 and token(key) <  -7395063693339347252;

 count
-------
    52
```

**Comment by roydahan** [comment]
@nyh , this is the issue you're currently looking into.

**Comment by slivne** [comment]
@nyh - the fix to read exact was merged - right ?

**Comment by slivne** [comment]
@nyh - ping the fix to read exact was merged can we close this

**Comment by nyh** [comment]
Indeed, my fix was already committed - see commit 3018df11b53c53122fcc334f5227b98f0cf55610 (on master, and backports have been done to some branches and are ongoing for other branches).
However, I think that @roydahan should close this bug only after verifying it actually solves the original problem he saw.

**Comment by roydahan** [comment]
verified with the same scenario using master.
Running 1TB longevity again on 1.7.2 to test with this fix.

**Comment by nyh** [comment]
@roydahan excellent! Thanks.

**Comment by slivne** [comment]
verified on 2.0
still open 1.7
