### ISSUE TITLE
coredump when metrics connect

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#2350]
*Installation details*
Scylla version: 8b0e358
Cluster size: 2 nodes
OS Centos7

Using i3 with 1.7-rc2. Booted a cluster of 2 nodes. Later in time, started the monitoring image. Up until that point everything was fine. When monitor connects, scylla backtraces.

Note the timestamps:
```
May 03 19:26:03 ip-172-30-0-186 scylla[12646]:  [shard 0] storage_service - Thrift server listening on 0.0.0.0:9160 ...
May 03 19:38:28 ip-172-30-0-186 scylla[12646]: Segmentation fault on shard 1.
May 03 19:38:28 ip-172-30-0-186 scylla[12646]: Backtrace:
May 03 19:38:28 ip-172-30-0-186 scylla[12646]: 0x00000000004e78a8
May 03 19:38:28 ip-172-30-0-186 scylla[12646]: 0x00000000004e79c5
May 03 19:38:28 ip-172-30-0-186 scylla[12646]: 0x00000000004e7a13
May 03 19:38:28 ip-172-30-0-186 scylla[12646]: 0x00007f8ec23920ff
May 03 19:40:02 ip-172-30-0-186 systemd[1]: scylla-server.service: main process exited, code=killed, status=11/SEGV
May 03 19:40:02 ip-172-30-0-186 systemd[1]: Unit scylla-server.service entered failed state.
May 03 19:40:02 ip-172-30-0-186 systemd[1]: scylla-server.service failed.
```

That is the time when monitoring connected. Happened to one of the nodes. That backtrace is not really useful. But it dumped core, so I can generate a backtrace from gdb. The backtrace is attached to this issue
[gdb.txt](https://github.com/scylladb/scylla/files/974720/gdb.txt)

**Comment by glommer** [comment]
@amnonh @slivne

**Comment by glommer** [comment]
Guys - there is something strange here. I don't know how this happened, but this is not a 1.7 AMI. It is a *MASTER* AMI. I will re-check my generation procedures. The bug is there, but the code seems significantly different - which is what tipped me that something was not right.

The rpm is:
```
scylla-server-666.development-0.20170503.8b0e358.el7.centos.x86_64
```

**Comment by tzach** [comment]
@glommer  which AMI (ami-id) are you using?

**Comment by glommer** [comment]
The AMI is custom made - but it is just master code from that HEAD I
mentioned, no extra patches.

The ID is : ami-56a3cf40 (east-1)

**Comment by slivne** [comment]
@amnonh is this resolved - there is a long list of patches related to this.

**Comment by amnonh** [comment]
On Thu, May 25, 2017 at 1:22 PM, Shlomi Livne <notifications@github.com>
wrote:

> @amnonh <https://github.com/amnonh> is this resolved - there is a long
> list of patches related to this.
>
No, but V5 was sent today

**Comment by slivne** [comment]
@amnonh - can we close this ?

**Comment by amnonh** [comment]
yes with commit
https://github.com/scylladb/seastar/commit/1a4a08c0f229d3b83141c95198f53aee64865e02#diff-64de13fa870d84e5f993cebf6bf9cc25
