### ISSUE TITLE
dependency loop: sstable <-> memtables

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2354]
One of the sstable::write_component() overloads accepts a memtable. In addition, memtable knows about sstables.

We should divorce the two completely, with no includes between the two modules.  Some other file can provide the glue logic.

Writing an sstable should only accept a mutation_reader, nothing else.

**Comment by avikivity** [comment]
btw, we should simplify the sstable writing logic. Instead of all the parameters and variants, we should have something like:

```c++
struct sstable_write_config {
    ...
};

future<shared_sstable> write_sstable(mutation_reader, sstable_write_config);
```
One of the configuration items could be an `std::function<future<> ()> can_seal` (defaults to `make_ready_future<>`) to take the place of `leave_unsealed`. `write_sstable()` writes the components, waits for `can_seal()`, and seals. No two-part protocol to follow. Of course, the caller must make the return value of `can_seal()` available at some point in time (can be an exception).

**Comment by tgrabiec** [comment]
In de70d942a914e2f8c846604124c160ca1e385dd5 the memtable -> sstable edge was removed.
