### ISSUE TITLE
CQL - incorrect returned body when enabeling compression and tracing on specific requests 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#2356]
*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by avikivity** [comment]
Are there no additional details?

**Comment by vladzcloudius** [comment]
@avi It seems that we don't compress the Tracing session ID while according to the The [CQL v3 binary protocol spec](https://git-wip-us.apache.org/repos/asf?p=cassandra.git;a=blob_plain;f=doc/native_protocol_v3.spec) (see the "Tracing Flag" description in the chapter 2.2)  it should be the "first thing in the response body" and thus should be compressed as a part of the body.

The function in question is `cql_server::response::output()`.

**Comment by vladzcloudius** [comment]
@slivne @amnonh I can't reproduce the issue: I compiled the app in the enterprise ticket but it refuses to run returning the most annoying Java runtime errors. I either need an assistance with executing this application or some other way to reproduce the issue.

**Comment by amnonh** [comment]
Please post/email as much information as you can

**Comment by vladzcloudius** [comment]
@amnonh There is a Java app in the ticket referenced about. If you could provide the instructions on how to run it I'd be very thankful.

**Comment by slivne** [comment]
@vladcloudius - I'll help you compile and run on the 1:1
