### ISSUE TITLE
`seeds` configuration unable to use comma separated list of URLs

### ISSUE THREAD

**Issue by leoromanovsky** [scylladb/scylla#2357]
*Installation details*
Scylla version (or git commit hash): 1.7
Cluster size: 9
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04

On start up:

`May  7 19:41:47 ip-10-0-18-156 scylla:  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Wrong format for IPv4 address cassandra-seed-a-scylla.foo.com. Please ensure it's in dotted-decimal format)`

This was expected behavior in Cassandra 2 and makes it simpler to replace a seed down that is terminated.

**Comment by tzach** [comment]
@elcallio as far as I can see URL resolution does not apply to seeds yet, even after your commit
https://github.com/scylladb/scylla/commit/feffc2bbe1a219b31787e9ca275e00ab3cf8cbbf is it the case?

**Comment by slivne** [comment]
DNS support in scylla will be part of 1.8 its not part of 1.7
