### ISSUE TITLE
Unknown errors occured when using set type

### ISSUE THREAD

**Issue by m0t0k1ch1** [scylladb/scylla#2358]
*Installation details*
Scylla version (or git commit hash): 1.6.4-20170425.65862c4-ubuntu1
Cluster size: 1 (for debug) 
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04 LTS

---

I used set type column for high speed processing in my C++ application.
The application was working without problems before using set type.
However, when I started using set type, sometimes I got unknown errors.

### What I did
* The tables are simple KVS or "key and set of bytes"
* Always specify the primary key when reading
* Only key-set table can be updated (including delete)
* Some threads try to read what is not stored yet

### What happens
* Failed to read data which has been stored and not deleted.

In addition, when I ran the application on Cassandra 3.0.13, no error occured.

I am looking for a condition to definitely reproduce the errors, but I can not found it yet.
My config files are https://gist.github.com/m0t0k1ch1/c5e2c92559c6af9cee234c2e52ddc1b1.

**Comment by duarten** [comment]
What errors happen? Do they manifest as errors sent to the client, or does the server crash? If so, is there a core dump? Do the server logs mention errors?

**Comment by m0t0k1ch1** [comment]
`cass_future_error_message` function of [the driver](https://github.com/datastax/cpp-driver) returns error that the data is not found. The server is not crashed.

**Comment by duarten** [comment]
Can you post the client code that is triggering the problem?

**Comment by m0t0k1ch1** [comment]
I have not identified exactly which code is causing the problem yet. Please wait for a while until I get ready to pass the code...

> I am looking for a condition to definitely reproduce the errors, but I can not found it yet.

**Comment by duarten** [comment]
@m0t0k1ch1 Any update on the issue?

**Comment by m0t0k1ch1** [comment]
Sorry. I could not found the client code to definitely reproduce the errors. There is a possibility that there was a problem in my environment. Thus, because the cause of the errors is not clear, the issue should be closed. I will report again if there is something new discovery.
