### ISSUE TITLE
Significant differences between shard performance

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#2362]
*Installation details*
Scylla version (or git commit hash): fc9db8bb033d948740888277dd15249d67b3a603 (branch-1.7)
Nodes: 3x i2.8xlarge
Loaders: 10x c4.8xlarge
Load:
```
POP=30000000000
LOADERS=10
./ec2-stress.sh 1 -e "populate=$POP" \
    -e "command=write" -e "stress_options='-schema \"replication(factor=3)\"'" \
    -e "command_options=duration=60m" \
    -e "threads=500" \
    -e "clean_data=true" \
    -e "server=Scylla" \
    -e "seq_populate=$(($POP/$LOADERS))"
```

It was noticed that in the aforementioned configuration often one or few shards are significantly slower than the others. In this particular workload this causes memtable flushes to lag behind which can cause virtual dirty to hit hard limit and in the worst case cause requests to time out. In a test with 5k partitions the slowness of the shards was even more problematic as it caused affected ones to be blocked on commitlog writes which, again, resulted in timeouts.

In case of the commitlog flushes the affected shard was flushing around ~15k partitions per second while others at the same time were doing around 40k partitions/s. While some inequalities between shards are to be expected this is definitely too much and the cause of it should be understood.

Reactor stall detector didn't report anything that could be a reason of a behaviour like that.

**Comment by slivne** [comment]
rebalance connections to shards was done 5828ddcca47b070b7c5218d475dd5375ccaf1599

**Comment by slivne** [comment]
closing old issue - open a new one if seen again
