### ISSUE TITLE
compactionhistory API implementation doesn't use paging, induces latency

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2366]
See the `get_compaction_history()` function, it should use paging (and also stream the result back to the caller rather than return a huge string).

**Comment by avikivity** [comment]
Root cause of #2361

**Comment by amnonh** [comment]
There are two alternatives: streaming on http level or paging on the API level.
I think the API level is better ie: the API would return the first n result and a token to the next n.
if possible lets keep the API stateless.

**Comment by slivne** [comment]
lets start with paging at the query level its causing a lot of grief as it
is.

So lets split this into two different patches.

**Comment by gleb-cloudius** [comment]
On Sun, May 14, 2017 at 01:52:45AM -0700, Amnon Heiman wrote:
> There are two alternatives: streaming on http level or paging on the API level.
> I think the API level is better ie: the API would return the first n result and a token to the next n.
> if possible lets keep the API stateless. 
> 
Won't changing API like this break "nodetool compactionhistory" command?

--
			Gleb.

**Comment by amnonh** [comment]
it will not break, we first add an API that support paging, then modify the JMX to use it.
the nodetool uses the jmx, as long as the jmx works the same, the nodetool is happy

**Comment by tzach** [comment]
@amn But you will break the JMX, right?

**Comment by amnonh** [comment]
It will not break the jmx, I'll add a new API first and then change the jmx to use the new one.
BTW it's @amnonh amn is someone else

**Comment by slivne** [comment]
@amnonh lets add paging to the query can you send the patch for this so we will have a solution for 1.8 

we can later work on do a better API.

**Comment by slivne** [comment]
@amnonh - I think this was fixed no ?

**Comment by amnonh** [comment]
It wasn't merged.

**Comment by slivne** [comment]
@amnonh ping

**Comment by slivne** [comment]
patch on the mailing list [PATCH scylla v5 0/3] use paging for compaction history
