### ISSUE TITLE
ScyllaDB 41hour Compaction with No load(related 2359 issue)

### ISSUE THREAD

**Issue by ban4785** [scylladb/scylla#2373]
version : scylla-1.6.1-20170218.2ea4da2.el7.centos.x86_64

#2359 
after load, ScyllaDB compacted sstables about 41hours.
below is metric info.
![41hourcompaction](https://cloud.githubusercontent.com/assets/20348151/25877995/68ac6550-3562-11e7-878f-36947779c9e8.png)

![41hourcompaction2](https://cloud.githubusercontent.com/assets/20348151/25878030/b01f74cc-3562-11e7-831a-9ff15e5d7bff.png)

**first error meesage occurs** 
May  8 14:02:36 swfosldb01 scylla: [shard 6] database - failed to write sstable /scylla/data/foms/fdc_unit_param_data2-2325ba102ba611e792a1000000000006/foms-fdc_unit_param_data2-ka-43782-Data.db: std::bad_alloc (std::bad_alloc)

**while compacting, /var/log/messages log was** 
_May  8 14:02:36 swfosldb01 scylla: [shard 0] storage_proxy - exception during mutation write to 192.168.200.101: std::bad_alloc (std::bad_alloc)
May  8 14:02:36 swfosldb01 scylla: [shard 2] storage_proxy - Failed to apply mutation from 192.168.200.103#6: std::bad_alloc (std::bad_alloc)_

**after 41hours i restart ScyllaDB, but node didn't start with messages.**

May 10 08:52:58 swfosldb02 scylla: [shard 0] storage_proxy - Exception when communicating with 192.168.200.102: std::bad_alloc
May 10 08:53:48 swfosldb02 scylla: [shard 0] seastar - Exiting on unhandled exception: exceptions::read_timeout_exception (Operation timed out for system.peers - received only 0 responses from 1 CL=ONE.)
May 10 08:53:48 swfosldb02 scylla: [shard 0] compaction_manager - Asked to stop
May 10 08:53:48 swfosldb02 scylla: [shard 1] compaction_manager - Asked to stop
May 10 08:53:48 swfosldb02 scylla: [shard 2] compaction_manager - Asked to stop
May 10 08:53:48 swfosldb02 scylla: [shard 1] compaction_manager - Stopped
May 10 08:53:48 swfosldb02 scylla: [shard 6] compaction_manager - Asked to stop
May 10 08:53:48 swfosldb02 scylla: [shard 3] compaction_manager - Asked to stop
May 10 08:53:48 swfosldb02 scylla: [shard 6] compaction_manager - Stopped
May 10 08:53:48 swfosldb02 scylla: [shard 7] compaction_manager - Asked to stop
May 10 08:53:48 swfosldb02 scylla: [shard 4] compaction_manager - Asked to stop
May 10 08:53:48 swfosldb02 scylla: [shard 3] compaction_manager - Stopped
May 10 08:53:48 swfosldb02 scylla: [shard 7] compaction_manager - Stopped
May 10 08:53:48 swfosldb02 scylla: [shard 5] compaction_manager - Asked to stop
May 10 08:53:48 swfosldb02 scylla: [shard 4] compaction_manager - Stopped
May 10 08:53:48 swfosldb02 scylla: [shard 2] compaction_manager - Stopped
May 10 08:53:48 swfosldb02 scylla: [shard 5] compaction_manager - Stopped
May 10 08:53:48 swfosldb02 scylla: [shard 0] compaction_manager - Stopped
May 10 08:53:48 swfosldb02 systemd: scylla-server.service: main process exited, code=exited, status=1/FAILURE

**Comment by tgrabiec** [comment]
The bad_alloc failures are due to #2359.

The fact that compaction backlog may grow without bound is #1369.

**Comment by slivne** [comment]
@infordb AFAIK we have fixed issues related to this workload - if this issue still exists - please post and I'll reopen and we will further investigate.
