### ISSUE TITLE
ext4 support 

### ISSUE THREAD

**Issue by hawrre** [scylladb/scylla#2381]
as in issue #1933 said, scylla now support ext4 but scylla-server prevent to use it, there any way to do this until 1.8 release ? or change milestone to 1.7 ?
thanks

**Comment by nyh** [comment]
I don't know what is the "official" recommended way, but as a quick workaround you can use "--developer-mode=1" which forgives a bunch  of undesirable configuration issues, including the filesystem type.

**Comment by dorlaor** [comment]
I think the restriction was already lifted in 1.7, you can check the RC
version

**Comment by syuu1228** [comment]
@dorlaor On Seastar level it's true, but we still have filesystem check code on Scylla-1.7, which causes an error if filesystem is ext4.
I dropped it on master so probably it will available on 1.8: https://github.com/scylladb/scylla/commit/7a59336b8aebd4751a9bf3a945b8aa31d503c114

**Comment by hawrre** [comment]
@syuu1228 it will not break any API or any (significant) change to scylla. We want use scylla production ready not by enabling developer mode. I think it will good idea to change milestone to 1.7, for many cloud provider ext4 is main and only choice.
