### ISSUE TITLE
DateTiered compaction

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2383]
I think that DTCS does not handle expired data well.
Please review the test case below
Let me know if I'm doing something wrong

1. schema
CREATE TABLE test.datetest (
    id int,
    time timestamp,
    value int,
    PRIMARY KEY (id,time)
) WITH compaction = {'class': 'DateTieredCompactionStrategy', 'timestamp_resolution':'MICROSECONDS', 'base_time_seconds':'60', 'max_sstable_age_days':'365'};

2. write shell ( Data immediately is expired after insert )

for i in {1..5000}
do
   cqlsh `hostname` -e "insert into test.datetest(id,time,value) values($i,dateof(now()),1) using ttl 1;";
   cqlsh `hostname` -e "insert into test.datetest(id,time,value) values($i,dateof(now()),1) using ttl 1;";
   cqlsh `hostname` -e "insert into test.datetest(id,time,value) values($i,dateof(now()),1) using ttl 1;";
   cqlsh `hostname` -e "insert into test.datetest(id,time,value) values($i,dateof(now()),1) using ttl 1;";
   cqlsh `hostname` -e "insert into test.datetest(id,time,value) values($i,dateof(now()),1) using ttl 1;";
   sleep 2
   nodetool flush test;
done

3.  Unexpectedly, scylla does not erase expired data well
$du -sh *
....
3.1M    /home/scylla/data/test
Tue May 16 14:38:51 KST 2017
3.2M    /home/scylla/data/test
Tue May 16 14:39:01 KST 2017
3.3M    /home/scylla/data/test
Tue May 16 14:39:11 KST 2017
3.3M    /home/scylla/data/test
Tue May 16 14:39:21 KST 2017
3.4M    /home/scylla/data/test
Tue May 16 14:39:31 KST 2017
3.4M    /home/scylla/data/test
Tue May 16 14:39:41 KST 2017
3.5M    /home/scylla/data/test

4. compaction log 
If you look at the compaction log, scylla can not reduce the file size at all.

May 16 14:48:04 fomstap04 scylla: [shard 1] compaction - Compacted 5 sstables to [/home/scylla/data/test/datetest-2ec76da039f211e7980d000000000002/test-datetest-ka-1137-Data.db:level=0, ]. 3750 bytes to 3750 (~100% of original) in 284ms = 0.0125925MB/s. ~1280 total partitions merged to 10.
May 16 14:48:08 fomstap04 scylla: [shard 2] compaction - Compacted 6 sstables to [/home/scylla/data/test/datetest-2ec76da039f211e7980d000000000002/test-datetest-ka-1402-Data.db:level=0, ]. 3750 bytes to 3750 (~100% of original) in 257ms = 0.0139155MB/s. ~1536 total partitions merged to 10.
May 16 14:48:13 fomstap04 scylla: [shard 3] compaction - Compacted 4 sstables to [/home/scylla/data/test/datetest-2ec76da039f211e7980d000000000002/test-datetest-ka-1243-Data.db:level=0, ]. 2250 bytes to 2250 (~100% of original) in 226ms = 0.00949455MB/s. ~1024 total partitions merged to 6.

**Comment by infordb** [comment]
@raphaelsc @avikivity @slivne @tzach Could you check this issue

**Comment by infordb** [comment]
@raphaelsc @avikivity @slivne @tzach 
The size of sstables has increased to 4.5M.
...
4.4M    /home/scylla/data/test
Tue May 16 18:33:41 KST 2017
4.5M    /home/scylla/data/test
Tue May 16 18:33:51 KST 2017
4.3M    /home/scylla/data/test
Tue May 16 18:34:01 KST 2017
4.4M    /home/scylla/data/test
Tue May 16 18:34:11 KST 2017
4.5M    /home/scylla/data/tes

**Comment by slivne** [comment]
I checked this locally as well with cassandra 2.1.15 

it behaves the same way

and STCS behaves he same way as well.

that is I ran you workload with STCS (on cassandra) and it also did not reduce the disk size.

the items that remain are the tombstones for each row

running sstable2json / sstabledump on the sstables provides

```
.
.
.
  {
    "partition" : {
      "key" : [ "35" ],
      "position" : 14250
    },
    "rows" : [
      {
        "type" : "row",
        "position" : 14443,
        "clustering" : [ "2017-05-16 13:17+0300" ],
        "liveness_info" : { "tstamp" : "2017-05-16T10:17:33.458615Z" },
        "cells" : [
          { "name" : "value", "deletion_info" : { "local_delete_time" : "2017-05-16T10:17:33Z" }
          }
        ]
      },
      {
        "type" : "row",
        "position" : 14443,
        "clustering" : [ "2017-05-16 13:17+0300" ],
        "liveness_info" : { "tstamp" : "2017-05-16T10:17:34.513388Z" },
        "cells" : [
          { "name" : "value", "deletion_info" : { "local_delete_time" : "2017-05-16T10:17:34Z" }
          }
        ]
      },
      {
        "type" : "row",
        "position" : 14443,
        "clustering" : [ "2017-05-16 13:17+0300" ],
        "liveness_info" : { "tstamp" : "2017-05-16T10:17:35.597970Z" },
        "cells" : [
          { "name" : "value", "deletion_info" : { "local_delete_time" : "2017-05-16T10:17:35Z" }
          }
        ]
      },
      {
        "type" : "row",
        "position" : 14514,
        "clustering" : [ "2017-05-16 13:17+0300" ],
        "liveness_info" : { "tstamp" : "2017-05-16T10:17:36.652396Z" },
        "cells" : [
          { "name" : "value", "deletion_info" : { "local_delete_time" : "2017-05-16T10:17:36Z" }
          }
        ]
      },
      {
        "type" : "row",
        "position" : 14585,
        "clustering" : [ "2017-05-16 13:17+0300" ],
        "liveness_info" : { "tstamp" : "2017-05-16T10:17:37.755935Z" },
        "cells" : [
          { "name" : "value", "deletion_info" : { "local_delete_time" : "2017-05-16T10:17:37Z" }
          }
        ]
      }
    ]
  },
.
.
.
```

**Comment by slivne** [comment]
One more comment 

I did notice that in cassandra sometimes the data is flushed with the TTL information (prior to it becoming a tombstone) 

in those cases running sstable2json/sstabledump will yield.

```
[
  {
    "partition" : {
      "key" : [ "116" ],
      "position" : 0
    },
    "rows" : [
      {
        "type" : "row",
        "position" : 221,
        "clustering" : [ "2017-05-16 16:38+0300" ],
        "liveness_info" : { "tstamp" : "2017-05-16T13:38:13.274503Z", "ttl" : 1, "expires_at" : "2017-05-16T13:38:14Z", "expired" : true },
        "cells" : [
          { "name" : "value", "value" : "1" }
        ]
      },
      {
        "type" : "row",
        "position" : 221,
        "clustering" : [ "2017-05-16 16:38+0300" ],
        "liveness_info" : { "tstamp" : "2017-05-16T13:38:13.730344Z", "ttl" : 1, "expires_at" : "2017-05-16T13:38:14Z", "expired" : true },
        "cells" : [
          { "name" : "value", "value" : "1" }
        ]
      },
      {
        "type" : "row",
        "position" : 221,
        "clustering" : [ "2017-05-16 16:38+0300" ],
        "liveness_info" : { "tstamp" : "2017-05-16T13:38:14.203813Z", "ttl" : 1, "expires_at" : "2017-05-16T13:38:15Z", "expired" : true },
        "cells" : [
          { "name" : "value", "value" : "1" }
        ]
      },
      {
        "type" : "row",
        "position" : 304,
        "clustering" : [ "2017-05-16 16:38+0300" ],
        "liveness_info" : { "tstamp" : "2017-05-16T13:38:14.617937Z", "ttl" : 1, "expires_at" : "2017-05-16T13:38:15Z", "expired" : true },
        "cells" : [
          { "name" : "value", "value" : "1" }
        ]
      },
      {
        "type" : "row",
        "position" : 387,
        "clustering" : [ "2017-05-16 16:38+0300" ],
        "liveness_info" : { "tstamp" : "2017-05-16T13:38:15.093555Z", "ttl" : 1, "expires_at" : "2017-05-16T13:38:16Z", "expired" : true },
        "cells" : [
          { "name" : "value", "value" : "1" }
        ]
      }
    ]
  }
]
```

and compacting that will produce a tombstone and some reduction in size - yet its not that data is removed any faster.

**Comment by slivne** [comment]
To be clear - the issue is the gc_period - which is set by default to be 10 days, if you change that then tombstones will be removed.

**Comment by infordb** [comment]
@slivne  sorry and thank you
I did not check the gc_period setting while changing the test schema
