### ISSUE TITLE
PHP and asynchronous scylla

### ISSUE THREAD

**Issue by sm2017** [scylladb/scylla#2385]
Hello

How can I execute commands asynchronously using PHP ?
I want to use event loop and when the result is ready , Get it with events (I don't want wait for result - non-blocking )

**Comment by avikivity** [comment]
I'm no PHP expert, but it looks like you should use the [executeAsync](http://datastax.github.io/php-driver/api/Cassandra/interface.Session/#method-executeAsync) method.
