### ISSUE TITLE
Enable read-ahead for partition index

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2388]
perf_fast_forward demonstrates that scans over small partitions with skips (sparse cache) block on index reads (blocked =~ idx miss), which likely impacts the throughput of the scan:

```
Testing scanning small partitions with skips. 
Reads whole range interleaving reads with skips according to read-skip pattern:
   read    skip      time [s]     frags     frag/s    aio      [KiB] blocked dropped  idx hit idx miss  idx blk    c hit   c miss    c ins    cpu
-> 1       0         4.592445   1000000     217749   1100     139652       7       4        0        0        0        0  1000000  1000000 100.0%
-> 1       1         5.506722    500000      90798   8905     186528    7814       0        1     7813    15625        0   500000   500000  91.2%
-> 1       8         1.937576    111112      57346   8905     186528    7814       0      869     7813    14757        0   111112   111112  74.7%
-> 1       16        1.394473     58824      42184   8905     186528    7814       0      461     7813    15165        0    58824    58824  64.4%
-> 1       32        1.137064     30304      26651   8905     186528    7814       0      238     7813    15388        0    30304    30304  55.6%
-> 1       64        1.005198     15385      15305   8905     186528    7814       0      121     7813    15505        0    15385    15385  49.0%
-> 1       256       0.409029      3892       9515   5044     163360    3953       0       13     3952     7830        0     3892     3892  52.0%
-> 1       1024      0.236789       976       4122   2082     145588     992     105        2      990     1963        0      976      976  25.5%
-> 1       4096      0.071415       245       3431    741      18024     492     248        0      247      491        0      245      245  24.1%
```

Such workloads would benefit from index read-ahead.

**Comment by pdziepak** [comment]
Strictly speaking, read-ahead is enabled for index reads, but we recreate the reader when advancing to the next index page. A solution would be to reuse the same reader and just skip to the new destination, that obviously adds a potential for overreads, but hopefully, dynamic adjustments would be able to sufficiently deal with that.

**Comment by tgrabiec** [comment]
@pdziepak Yes. When looking up the bounds for the data file, we learn about the bounds for the index, so we could feed that information back into the index reader to avoid overreads past the query range.

**Comment by avikivity** [comment]
Will this be fixed as part of #1865? /cc @denesb

**Comment by tgrabiec** [comment]
This issue seems independent of #1865. We can have reader cache, but still have slow cache population due to frequent latency-bound index reads on fast_forward_to().

**Comment by avikivity** [comment]
You're right.

/cc @argenet

**Comment by bhalevy** [comment]
@tgrabiec is this issue addressed in your WIP changes?

**Comment by tgrabiec** [comment]
@bhalevy Not in general. If the index will be cached, this problem will not appear. If the index is not cached, the behavior will be the same.
