### ISSUE TITLE
*.deb installation fails if scylla user is already present in external database (nis, ldap...)

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#2389]
*Installation details*
Scylla version (or git commit hash): 2eef7cd3952d9ea1f5b971ccca91ba07b21b2557

adduser in scylla-server.postinst fails if scylla user is present in external db and it causes installation to fail. We should check for scylla user presence before running adduser.

**Comment by amoskong** [comment]
There is a similar issue with CentOS: https://github.com/scylladb/scylla/issues/1958
It's fixed by : https://github.com/scylladb/scylla/commit/f3e45bc9ef2bc447924f9c6650454a325e2f473c

**Comment by syuu1228** [comment]
@amoskong Okay I'll take a look...

**Comment by syuu1228** [comment]
Patch is on the ml titled "[PATCH scylla] dist/debian: check scylla user/group existance before adding them", please review
