### ISSUE TITLE
scylla node cannot start with OrderPreservingPartitioner

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#2394]
dtest test case:
cqlsh_tests/cqlsh_copy_tests.py:CqlshCopyTest.test_round_trip_order_preserving

**Comment by slivne** [comment]
is it using the ByteOrderPartitioner - or something else

We support 3 murmur3,random,byte

**Comment by slivne** [comment]
we do not support OrderPreservingPartitioner
