### ISSUE TITLE
Support compressed commitlog like Origin

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#24]
http://www.datastax.com/dev/blog/updates-to-cassandras-commit-log-in-2-2

**Comment by slivne** [comment]
@avikivity, @tzach  - I asked @elcallio  to look at this while we are designing a bigger item - any comments/reservations about this feature ?

**Comment by avikivity** [comment]
I don't like it. Compression is generally slow, and commitlogs are only written, never read. Scylla is designed for high storage/memory ratios, so a lot of storage is likely available. The feature makes the wrong tradeoff - need more expensive cores to save some cheap storage.

It may make sense for network-attached disks that are bandwidth limited (like AWS EBS) or rotating disks, but people generally don't store commit logs there.

**Comment by glommer** [comment]
I agree this adds very little value. Still, in the belief that this could help with write workloads in slow disks I tried this in the past and saw very little improvements, if any.

I suggest closing this as wontfix.

**Comment by raphaelsc** [comment]
given Glauber and @avikivity comments, I am closing this issue... added wontfix tag.
