### ISSUE TITLE
nodetool help

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#240]
Present only supported operations

**Comment by tzach** [comment]
@slivne @amnonh since nodetool scope for GA is closed, can we finish this feature?

**Comment by slivne** [comment]
Yes - yet we are focused on testing existing api - instead of adding
additional ones - in any case this is simple.

**Comment by amnonh** [comment]
I suggest that we'll wait with that for the last thing before GA.
It only requires to remove the commands that we're not going to support

**Comment by tzach** [comment]
Closed with https://github.com/scylladb/scylla-tools-java/commit/04603659a383db9565b8091b2c111e5048ba30e5
