### ISSUE TITLE
collectd does not report all the metrics

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#2400]
On master, after the change in the metrics layer collectd only report part of the metrics

**Comment by gleb-cloudius** [comment]
On Sun, May 21, 2017 at 06:41:36AM -0700, Amnon Heiman wrote:
> On master, after the change in the metrics layer collectd only report part of the metrics
> 
"master" is a moving target. You should provide commit hash.

--
			Gleb.

**Comment by slivne** [comment]
@amnonh can we close this ?

**Comment by amnonh** [comment]
no, it's not merged yet, it part of the fix in the metrics layer that
passes unsafe shared_ptr

**Comment by slivne** [comment]
@amnonh was this fixed ?

**Comment by amnonh** [comment]
On Wed, Sep 13, 2017 at 3:45 PM, Shlomi Livne <notifications@github.com>
wrote:

> @amnonh <https://github.com/amnonh> was this fixed ?
>
yes with commit
https://github.com/scylladb/seastar/commit/78211d4a40f86e94bc1617db747bddb1ffcbb3ba#diff-ea3899a074615f42136fdf93df5da2c6
