### ISSUE TITLE
Scylla_raid_setup in silent mode fails to create raid with more than 1 disk

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#2402]
When using scylla_setup in silent mode and providing it with --disks parameter, the setup tries to build a raid from the list of disks (comma separated list of disks).

In case the list is bigger than 1 :), the raid creation will fail with the error:
mdadm: You haven't given enough devices (real or missing) to create this array

This is happen due to the following:
1. mdadm command to create the raid is provided with "--raid-devices=$NR_DISK".
2. NR_DISK is calculated by: NR_DISK=$((echo "$2"|grep , -o|wc -w + 1)
This calculation only works when there is one device, because in this case the phrase return "0" and we increase it by "1".
In case the list is more than 1 disk, NR_DISK will be larger by 1 and the raid command will fail because the list of disks will be less than the NR_DISK.

**Comment by syuu1228** [comment]
@roydahan Could you provide example of the parameter?
I tested following shell commands to check what is wrong on both disks = 1 and disks > 1, but it's looks correct:
```
syuu@takuya-xenial-3:~$ DSK=/dev/nvme0n2,/dev/nvmen3
syuu@takuya-xenial-3:~$ NR_DISK=$((`echo "$DSK"|grep , -o|wc -w` + 1))
syuu@takuya-xenial-3:~$ echo $NR_DISK
2
syuu@takuya-xenial-3:~$ DSK=/dev/nvme0n2
syuu@takuya-xenial-3:~$ NR_DISK=$((`echo "$DSK"|grep , -o|wc -w` + 1))
syuu@takuya-xenial-3:~$ echo $NR_DISK
1
```

**Comment by roydahan** [comment]
I need to look back for the input.
But looking at it now, I think that if you have "," in the end of the DSK list of devices, the calculation is wrong.
A possible validation could be to trim any comma in the end of the list.
