### ISSUE TITLE
sstable deletion maganger can cosume a lot of memory

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#2403]
*Installation details*
Scylla version (or git commit hash): 6ac73b57fb6f45947e465f8ebafdc3001d68680d

sstable deletion manager calls stables() function which runs remove_by_toc_name() in parallel on all sstables it wishes to delete.  remove_by_toc_name() creates seastar thread internally which takes 128k for the stack. If the set of sstables been deleted simultaneously is large this may take a lot of memory.

**Comment by raphaelsc** [comment]
we no longer have a deletion manager, and remove_by_toc_name() no longer creates a thread.
