### ISSUE TITLE
Adding node to 100-nodes cluster caused the new node crash

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#2404]
- create cluster with 100 nodes(aws m3.medium)
- start cassandra stress write
- add new node 

Cassandra stress crashes.
The new node crashes.

log from the crached node:
May 22 13:55:14 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update schema_version for 172.30.12.29: seastar::gate_closed_exception (gate closed)
May 22 13:55:14 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update schema_version for 172.30.12.29: seastar::gate_closed_exception (gate closed)
May 22 13:55:14 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update schema_version for 172.30.12.29: seastar::gate_closed_exception (gate closed)
May 22 13:55:14 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update schema_version for 172.30.12.30: seastar::gate_closed_exception (gate closed)
May 22 13:55:14 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - handle_state_normal: fail to update tokens for 172.30.12.110: seastar::gate_closed_exception (gate closed)
May 22 13:55:14 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update data_center for 172.30.12.117: seastar::gate_closed_exception (gate closed)
May 22 13:55:14 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update rack for 172.30.12.117: seastar::gate_closed_exception (gate closed)
May 22 13:55:14 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update release_version for 172.30.12.117: seastar::gate_closed_exception (gate closed)
May 22 13:55:14 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update rpc_address for 172.30.12.117: seastar::gate_closed_exception (gate closed)
May 22 13:55:14 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update host_id for 172.30.12.117: seastar::gate_closed_exception (gate closed)
May 22 13:55:14 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update schema_version for 172.30.12.29: seastar::gate_closed_exception (gate closed)
May 22 13:55:14 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update rack for 172.30.12.117: seastar::gate_closed_exception (gate closed)
May 22 13:55:14 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update release_version for 172.30.12.117: seastar::gate_closed_exception (gate closed)
May 22 13:55:14 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - handle_state_normal: fail to update tokens for 172.30.12.110: seastar::gate_closed_exception (gate closed)
May 22 13:55:15 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - handle_state_normal: fail to update tokens for 172.30.12.118: seastar::gate_closed_exception (gate closed)
May 22 13:55:15 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update rpc_address for 172.30.12.117: seastar::gate_closed_exception (gate closed)
May 22 13:55:15 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update host_id for 172.30.12.117: seastar::gate_closed_exception (gate closed)
May 22 13:55:15 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update supported_features for 172.30.12.117: seastar::gate_closed_exception (gate closed)
May 22 13:55:15 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update release_version for 172.30.12.119: seastar::gate_closed_exception (gate closed)
May 22 13:55:15 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update supported_features for 172.30.12.117: seastar::gate_closed_exception (gate closed)
May 22 13:55:15 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update rpc_address for 172.30.12.119: seastar::gate_closed_exception (gate closed)
May 22 13:55:15 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update host_id for 172.30.12.119: seastar::gate_closed_exception (gate closed)
May 22 13:55:15 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update supported_features for 172.30.12.119: seastar::gate_closed_exception (gate closed)
May 22 13:55:16 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - handle_state_normal: fail to update tokens for 172.30.12.110: seastar::gate_closed_exception (gate closed)
May 22 13:55:16 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - handle_state_normal: fail to update tokens for 172.30.12.117: seastar::gate_closed_exception (gate closed)
May 22 13:55:17 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - handle_state_normal: fail to update tokens for 172.30.12.119: seastar::gate_closed_exception (gate closed)
May 22 13:55:17 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - handle_state_normal: fail to update tokens for 172.30.12.117: seastar::gate_closed_exception (gate closed)
May 22 13:55:33 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update data_center for 172.30.12.15: seastar::gate_closed_exception (gate closed)
May 22 13:55:33 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update data_center for 172.30.12.22: seastar::gate_closed_exception (gate closed)
May 22 13:55:33 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update data_center for 172.30.12.23: seastar::gate_closed_exception (gate closed)
May 22 13:55:33 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update data_center for 172.30.12.22: seastar::gate_closed_exception (gate closed)
May 22 13:55:33 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update data_center for 172.30.12.26: seastar::gate_closed_exception (gate closed)
May 22 13:55:33 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update data_center for 172.30.12.26: seastar::gate_closed_exception (gate closed)
May 22 13:55:33 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update data_center for 172.30.12.28: seastar::gate_closed_exception (gate closed)
May 22 13:55:33 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update data_center for 172.30.12.28: seastar::gate_closed_exception (gate closed)
May 22 13:55:33 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update data_center for 172.30.12.29: seastar::gate_closed_exception (gate closed)
May 22 13:55:33 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update data_center for 172.30.12.29: seastar::gate_closed_exception (gate closed)
May 22 13:55:33 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update data_center for 172.30.12.29: seastar::gate_closed_exception (gate closed)
May 22 13:55:33 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update data_center for 172.30.12.30: seastar::gate_closed_exception (gate closed)
May 22 13:55:33 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update data_center for 172.30.12.23: seastar::gate_closed_exception (gate closed)
May 22 13:55:33 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update data_center for 172.30.12.29: seastar::gate_closed_exception (gate closed)
May 22 13:55:34 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update schema_version for 172.30.12.30: seastar::gate_closed_exception (gate closed)
May 22 13:55:34 ip-172-30-12-41 scylla[5955]:  [shard 0] storage_service - fail to update rack for 172.30.12.15: seastar::gate_closed_exception (gate closed)

log from the loader running cassandra stress:

m.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
java.io.IOException: Operation x10 on key(s) [38384f503732504d3430]: Error executing: (WriteTimeoutException): Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)

	at org.apache.cassandra.stress.Operation.error(Operation.java:135)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:113)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:98)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:106)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:258)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:321)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
java.io.IOException: Operation x10 on key(s) [353937344b504d4c3330]: Error executing: (WriteTimeoutException): Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)

	at org.apache.cassandra.stress.Operation.error(Operation.java:135)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:113)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:98)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:106)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:258)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:321)
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)
java.io.IOException: Operation x10 on key(s) [39503331314d31313130]: Error executing: (WriteTimeoutException): Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)

	at org.apache.cassandra.stress.Operation.error(Operation.java:135)

**Comment by gleb-cloudius** [comment]
On Mon, May 22, 2017 at 07:05:29AM -0700, Larisa Ustalov wrote:
> log from the crached node:
Where is the full log?

--
			Gleb.

**Comment by larisau** [comment]
[job.log.gz](https://github.com/scylladb/scylla/files/1019470/job.log.gz)

**Comment by asias** [comment]
According to the log, 54.242.65.178 is the joining node. I saw

```
2017-05-22 13:55:17,233 remote           L0197 DEBUG| [54.242.65.178] [stdout] May 22 13:55:17 err    |  [shard 0] storage_service - handle_state_normal: fail to update tokens for 172.30.12.117: seastar::gate_closed_exception
 (gate closed)


2017-05-22 13:55:33,096 remote           L0197 DEBUG| [54.242.65.178] [stdout] May 22 13:55:33 warning|  [shard 0] gossip - Fail to send EchoMessage to 172.30.12.32:0: rpc::timeout_error (rpc call timed out)
2017-05-22 13:55:33,097 remote           L0197 DEBUG| [54.242.65.178] [stdout] May 22 13:55:33 warning|  [shard 0] gossip - Fail to send EchoMessage to 172.30.12.43:0: rpc::timeout_error (rpc call timed out)

```

I did not saw the joining crashed/coredumped.

@gleb-cloudius any idea about the 'seastar::gate_closed_exception
 (gate closed)' error?

**Comment by gleb-cloudius** [comment]
On Thu, Jul 13, 2017 at 01:05:48PM +0000, Asias He wrote:
> According to the log, 54.242.65.178 is the joining node. I saw
> 
> ```
> 2017-05-22 13:55:17,233 remote           L0197 DEBUG| [54.242.65.178] [stdout] May 22 13:55:17 err    |  [shard 0] storage_service - handle_state_normal: fail to update tokens for 172.30.12.117: seastar::gate_closed_exception
>  (gate closed)
> 
> 
> 2017-05-22 13:55:33,096 remote           L0197 DEBUG| [54.242.65.178] [stdout] May 22 13:55:33 warning|  [shard 0] gossip - Fail to send EchoMessage to 172.30.12.32:0: rpc::timeout_error (rpc call timed out)
> 2017-05-22 13:55:33,097 remote           L0197 DEBUG| [54.242.65.178] [stdout] May 22 13:55:33 warning|  [shard 0] gossip - Fail to send EchoMessage to 172.30.12.43:0: rpc::timeout_error (rpc call timed out)
> 
> ```
> 
> I did not saw the joining crashed/coredumped.
> 
> @gleb-cloudius any idea about the 'seastar::gate_closed_exception
>  (gate closed)' error?
> 
Usually gate_closed_exception is a sing that a node is going down.

--
			Gleb.

**Comment by asias** [comment]
```
May 22 13:55:14 ip-172-30-12-41 scylla[5955]: [shard 0] storage_service - handle_state_normal: fail to update tokens for 172.30.12.110: seastar::gate_closed_exception (gate closed)
May 22 13:55:14 ip-172-30-12-41 scylla[5955]: [shard 0] storage_service - fail to update data_center for 172.30.12.117: seastar::gate_closed_exception (gate closed)
```
The log shows the node tries to update the system table, it is supposed to update local table only, why does it matter if a remote node is down or not.

**Comment by slivne** [comment]
@gleb-cloudius , @asias any update on this

**Comment by asias** [comment]
@gleb-cloudius can you take a look at my previous comment

**Comment by gleb-cloudius** [comment]
I do not understand it. seastar::gate_closed_exception means local node
is going down. Someone/something initiated its shutdown.

--
			Gleb.

**Comment by asias** [comment]
OK. I thought you think the error was due to PEER node down. If it is local node shutdown, it makes sense. 

But who shutdown the node?

**Comment by gleb-cloudius** [comment]
On Wed, Jul 26, 2017 at 08:05:56AM +0000, Asias He wrote:
> OK. I thought you think the error was due to PEER node down. If it is local node shutdown, it makes sense. 
> 
> But who shutdown the node?
> 
Some errors do. Or a signal. Do we have complete log for such node?

--
			Gleb.

**Comment by asias** [comment]
@larisau attached the job.log is supposed to contain the log. But it is too hard to digest because it contains everything.

**Comment by gleb-cloudius** [comment]
On Wed, Jul 26, 2017 at 08:18:13AM +0000, Asias He wrote:
> @larisau attached the job.log is supposed to contain the log. But it is too hard to digest because it contains everything. 
> 
Yes, I already complained about that.

--
			Gleb.

**Comment by asias** [comment]
IIRC, scylla-sluster-test does contain per node log in the test job result.

**Comment by slivne** [comment]
from asias : extract the log for ip-172-30-12-41

**Comment by slivne** [comment]
@asias / @gleb-cloudius  attached is the extracted info for 172.30.12.41

for reference this is what I did
``` 
 grep "\[54.242.65.178" job\(1\).log   > ip_172.30.12.41.log
```


[ip_172.30.12.41.log.gz](https://github.com/scylladb/scylla/files/1277049/ip_172.30.12.41.log.gz)

**Comment by asias** [comment]
The node shut itself down because it can not talk to any seed node. See

```
cat Unable to contact any seeds
$ cat ip_172.30.12.41.log|grep 'Unable to contact any seeds'
2017-05-22 11:05:11,615 remote           L0197 DEBUG| [54.242.65.178] [stdout] May 22 11:05:11 err    |  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Unable to contact any seeds!)
2017-05-22 11:07:56,666 remote           L0197 DEBUG| [54.242.65.178] [stdout] May 22 11:07:56 err    |  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Unable to contact any seeds!)
2017-05-22 13:10:44,875 remote           L0197 DEBUG| [54.242.65.178] [stdout] May 22 13:10:44 err    |  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Unable to contact any seeds!)
2017-05-22 13:23:48,944 remote           L0197 DEBUG| [54.242.65.178] [stdout] May 22 13:23:48 err    |  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Unable to contact any seeds!)
2017-05-22 13:54:30,161 remote           L0197 DEBUG| [54.242.65.178] [stdout] May 22 13:54:30 err    |  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Unable to contact any seeds!)
```

**Comment by slivne** [comment]
so why did it not connect to a seed node ?

**Comment by slivne** [comment]
It must have connected to the seed - or all the other nodes would have not known about that node.

**Comment by asias** [comment]
@larisau what is the snitch the cluster is using? ec2_multi_region_snitch or gossiping_property_file_snitch?

**Comment by asias** [comment]
The joining node did talk to the seed node at least once.

git grep  'Unable to contact any seeds'
service/storage_service.cc:561:         throw std::runtime_error("Unable to contact any seeds!");

This is the place we throw the exception.

At this point, the node think it can not find the seed node because it can not find it in the gossip state map.

**Comment by asias** [comment]
Will dig more.

**Comment by asias** [comment]
I have a theory why this happened. 

Attached is log for the new node up to the first time the "Unable to contact any seeds" is seen. 

[ip_172.30.12.41.log.simple.txt](https://github.com/scylladb/scylla/files/1283822/ip_172.30.12.41.log.simple.txt)

$ cat ip_172.30.12.41.log.simple.txt|grep UP|awk '{print $18}'|sort|uniq|wc -l
49

[up.txt](https://github.com/scylladb/scylla/files/1283833/up.txt)

It took 30 seconds to see only 49 nodes is UP.

This suggests we any saw 49 out of 100 nodes is UP( It is possible that the seed node is not one of the 49 seen node). This can happen if in apply_state_locally, we take long time to apply all of the 100 node's state. We have this call chain apply_state_locally -> handle_major_state_change -> mark_alive -> send_gossip_echo (returns only when remote replies, up to 3 seconds) -> real_mark_alive. 

Another thing, in apply_state_locally, we apply the state in order of ip address, the seed node is of ip 172.30.12.225. Unfortunately, it will be processed very late. The non-seed are of ip  172.30.12.4 to 172.30.12.134. 

On the other hand, in around 30 seconds, we check if seed node is in endpoint_state_map and throw exceptions.
```
2017-05-22 11:04:36,155 remote           L0197 DEBUG| [54.242.65.178] [stdout] May 22 11:04:36 info   | Scylla version 1.7.0-0.20170504.f61d9ac starting ...
2017-05-22 11:05:11,615 remote           L0197 DEBUG| [54.242.65.178] [stdout] May 22 11:05:11 err    |  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Unable to contact any seeds!)
```

The joining node did see the seed, but it hadn't manage to put the seed node's endpoint_state in endpoint_state_map in gossiper::handle_major_state_change.

**Comment by tgrabiec** [comment]
@asias Did you validate that bootstrapping 100 nodes is now more robust? I am seeing an opposite effect, the fact that `apply_state_locally` is serialized, and the fact that states are shuffled, are both making state application slower. See #2855.
