### ISSUE TITLE
do not leave behind (tmp TOC + data + index) files for sstable write which failed

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#2407]
when scylla runs out of disk space, memtable flush will try to create one sstable periodically, and for each failed sstable write, there will be left over files (tmp toc + data + index).

@gleb-cloudius that's the problem you bumped into, right?

**Comment by raphaelsc** [comment]
@gleb-cloudius to be more specific: which led you to write a patch to remove tmp toc in sequence instead.

**Comment by gleb-cloudius** [comment]
On Tue, May 23, 2017 at 04:30:48PM -0700, Raphael Carvalho wrote:
> when scylla runs out of disk space, memtable flush will try to create one sstable periodically, and for each failed sstable write, there will be left over files (tmp toc + data + index).
> 
> @gleb-cloudius that's the problem you bumped into, right?
> 
I bumped into both, this one and the one where there was no TOC at all.

--
			Gleb.
