### ISSUE TITLE
Cells should always use fragmented storage

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2409]
`managed_bytes`, which is used as a backing storage for `atomic_cell_or_collection`, stores the data fragmented only when it's governed by LSA, but not when it's governed by the standard allocator. The latter is used temporarily when writing or reading data.

That may result in bad_alloc for large-enough cells due to memory fragmentation.

Also applies for large-enough collections, even with small cells. See partition.cc:

```
auto ac = atomic_cell_or_collection::from_collection_mutation(ctype->serialize_mutation_form(cm));
```

**Comment by avikivity** [comment]
This is because we don't want to use fragmented iterators while deserializing. But we can use the same double-compile technique we use elsewhere, and compile the code twice, once for single-fragment a_c_o_c and once for fragmented a_c_o_c.

**Comment by tgrabiec** [comment]
Overlaps with #2559

**Comment by slivne** [comment]
@pdziepak is working on allowing single cells to be split

**Comment by slivne** [comment]
@pdziepak can we close this ?

**Comment by pdziepak** [comment]
Yes. Collections and counters still need to temporarily linearise the value when performing some operations on them, but `atomic_cell_or_collection` stores them fragmented.

**Comment by pdziepak** [comment]
I've opened #3601 for counters and #3602 for collections.
