### ISSUE TITLE
Error: Could not find or load main class com.scylladb.tools.SSTableExport

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2414]
*Installation details*
Scylla version (or git commit hash): 
  scylla-1.7.0-0.20170519.25607ab.el7.centos.x86_64
  scylla-1.7.1-0.20170524.230c33d.el7.centos.x86_64

[root]fomstap02:/root>sstabledump
Error: Could not find or load main class com.scylladb.tools.SSTableExport

Do I need additional settings after upgrading?

**Comment by tzach** [comment]
@syuu1228 can you please take a look?

**Comment by syuu1228** [comment]
@infordb @tzach Could you test following patch:
https://groups.google.com/forum/#!topic/scylladb-dev/g490tVH4Rkk

Does it solve the problem?

**Comment by tzach** [comment]
Solved the issue for me on scylla 1.7 AMI

**Comment by slivne** [comment]
fixed  scylladb/scylla-tools-java@33caa28a951c13dd0cc9c7ac5e51d9a75e99da54
