### ISSUE TITLE
generation of disk usage stat incorrectly uses uncompressed length of data component

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#2422]
after compaction, the stat is being incorrectly updated with sstable::data_size() which returns uncompressed length of data component.

**Comment by gleb-cloudius** [comment]
Can this be the reason for #1592?

**Comment by avikivity** [comment]
Yeeeeeeeeeeeeeeeeeees

**Comment by avikivity** [comment]
Dups #1592
