### ISSUE TITLE
compaction report of bandwidth and size should use actual size of data component

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#2423]
Uncompressed length is being used, so bandwidth is incorrect, and size report may not reflect what actually happened.

**Comment by penberg** [comment]
@avikivity @raphaelsc, fixed by https://github.com/scylladb/scylla/commit/41137c7fb611a2e4bc7c45813508d1551c7742a9, no?

**Comment by raphaelsc** [comment]
On Mon, May 29, 2017 at 2:33 AM, Pekka Enberg <notifications@github.com>
wrote:

> @avikivity <https://github.com/avikivity> @raphaelsc
> <https://github.com/raphaelsc>, fixed by 41137c7
> <https://github.com/scylladb/scylla/commit/41137c7fb611a2e4bc7c45813508d1551c7742a9>,
> no?
>
yes, let me close it. Thx.
