### ISSUE TITLE
build: confusing message on missing c-ares

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#2424]
If the c-ares submodule has not been checked out, the builder gets the seemingly-helpful error message:
```
Exception: c-ares is empty. Run "git submodule update --init".
```
However, running this command in the scylla directory doesn't do anything... The thing is that c-ares is a seastar module, and seastar is itself a submodule of scylla. So the command the user needs to run is actually:
```
git submodule update --init --recursive
```
Since this is an issue of integration of Seastar's build into Scylla's, I don't know where to fix it.
One option is to fix Seastar to add "--recursive" to the error message. If someone is building just Seastar, it will be useless, but also harmless. But it will be necessary when Seastar is built as part of a bigger project, like Scylla.

**Comment by avikivity** [comment]
We no longer bundle a c-ares submodule. Closing.
