### ISSUE TITLE
Error: scylla-server conflicts with abrt-2.1.11-45.el7.centos.x86_64

### ISSUE THREAD

**Issue by nwbrad** [scylladb/scylla#2427]
Trying to install Package scylla.x86_64 0:1.7.0-0.20170519.25607ab.el7.centos
through the normal install process: yum install scylla
release: CentOS Linux release 7.3.1611 (Core)
yum update is current as of 05/26/2017

yum install scylla aborts with:
--> Finished Dependency Resolution
Error: scylla-server conflicts with abrt-2.1.11-45.el7.centos.x86_64

**Comment by avikivity** [comment]
That's by design; abrt does conflict with scylla.  Please remove abrt before installing scylla.

**Comment by nwbrad** [comment]
Thanks for the answer.  If this is "by design" and abrt needs to be removed to successfully install ScyllaDB, then it should be documented as part of the installation process for Centos/RedHat.  Developers should not have to figure it out on their own.  I did not have similar issues with Cassandra when installing.  The install process should be as clear and simple as possible, without having to worry about getting errors, or not knowing what to do when an error occurs...

**Comment by dorlaor** [comment]
Fair point but it looks that it is documented:
http://www.scylladb.com/download/rhel_rpm/

**Comment by nwbrad** [comment]
Thanks.  My apologies.  I don’t know how I missed that.

**Comment by penberg** [comment]
I think it's easy to miss because of lack of formatting like in the other steps. /cc @tzach
