### ISSUE TITLE
Leveled strategy generating lots of 2-sstable L0 compaction which remains at L0.

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#2432]
Problem is lots of compactions of two L0 sstables which aren't promoted with a higher sstable_size_in_mb. That leads to write amplification because total size grows linearly rather than exponentially.

**Comment by slivne** [comment]
@raphaelsc did we address this ?

**Comment by raphaelsc** [comment]
On Mon, Jul 3, 2017 at 9:56 AM, Shlomi Livne <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> did we address this ?
>
patch was sent, it was reviewed, and i need to work on v2. I'll try to do
it today.
