### ISSUE TITLE
complex MV select statements doesn't work

### ISSUE THREAD

**Issue by abvgedeika** [scylladb/scylla#2434]
*Installation details*
Scylla version (or git commit hash): https://github.com/scylladb/scylla/commit/de70d942a914e2f8c846604124c160ca1e385dd5

seems like it's not implemented yet but filled to track the issue

test: TestMaterializedViews.complex_mv_select_statements_test

steps:
1) CREATE TABLE test (a int, b int, c int, d int, PRIMARY KEY (a, b, c))
2)  INSERT INTO test (a, b, c, d) VALUES (?, ?, ?, ?) :
[(0, 0, 0, 0),
(0, 0, 1, 0),
(0, 1, 0, 0),
(0, 1, 1, 0),
(1, 0, 0, 0),
(1, 0, 1, 0),
(1, 1, -1, 0),
(1, 1, 0, 0),
(1, 1, 1, 0)]
3) "CREATE MATERIALIZED VIEW mv AS SELECT * FROM test WHERE a = 1 AND b IS NOT NULL AND c = 1 PRIMARY KEY ((a, b), c)"
4) SELECT a, b, c, d FROM mv

result:
[]
expected result:
[[1, 0, 1, 0], [1, 1, 1, 0]]

**Comment by duarten** [comment]
We don't currently support creating materialized views on tables with existing data. Only new updates are processed.
