### ISSUE TITLE
Scylla failed to start on all 3 nodes, due to some node_exporter error (after clean install -> scylla_setup -> boot)

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla#2438]

**Comment by tomer-sandler** [comment]
Tzach wrote in the email thread:
I suspect its  https://github.com/prometheus/node_exporter/issues/219 solved in node_exporter 0.13.0 (we are using 0.12.0) but I'm not sure.

**Comment by tzach** [comment]
@tomer-sandler can you please print the output of
```
$ cat /proc/mdstat 
```
on this server?

**Comment by tomer-sandler** [comment]
Moving to enterprise... hence comment deleted.
