### ISSUE TITLE
gcc 6 compilation error related to -fvisibility=hidden

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#2439]
Scylla version (or git commit hash): 04da4dbf834dadbafcc62bbd82a0d738a6e8a188
OS: Ubuntu 16.04
gcc version: (Ubuntu/Linaro 6.3.0-18ubuntu2~16.04) 6.3.0 20170519
configure.py command line: `./configure.py --compiler=g++-f25 --enable-gcc6-concepts`

```
$ ll /usr/bin/g++-f25
lrwxrwxrwx 1 root root 14 Apr 14 21:01 /usr/bin/g++-f25 -> /usr/bin/g++-6
```
*The compilation command*
```
g++-6 -MD -MT build/release/gms/versioned_value.o -MF build/release/gms/versioned_value.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility-inlines-hidden -fvisibility=hidden  -pthread -I/home/vladz/work/urchin/seastar -I/home/vladz/work/urchin/seastar/fmt -I/home/vladz/work/urchin/seastar/build/release/gen  -march=nehalem -fconcepts -Ifmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -DFMT_HEADER_ONLY -DHAVE_GCC6_CONCEPTS -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT  -O2 -I/usr/include/jsoncpp -DBOOST_TEST_DYN_LINK  -Wno-maybe-uninitialized -Wno-tautological-compare -Wno-missing-braces -Wno-error=deprecated-declarations -DHAVE_LIBSYSTEMD=1 -I. -I build/release/gen -I seastar -I seastar/build/release/gen -c -o build/release/gms/versioned_value.o gms/versioned_value.cc
In file included from ./utils/exponential_backoff_retry.hh:25:0,
                 from ./sstables/compaction_manager.hh:32,
                 from ./database.hh:67,
                 from ./repair/repair.hh:31,
                 from ./message/messaging_service.hh:34,
                 from gms/versioned_value.cc:39:
/home/vladz/work/urchin/seastar/core/sleep.hh: In instantiation of ‘struct seastar::sleep(std::chrono::duration<_Rep, _Period>)::sleeper::sleeper(std::chrono::duration<_Rep, _Period>) [with Clock = std::chrono::_V2::steady_clock; Rep = long int; Period = std::ratio<1l, 1000l>]::<lambda()>’:
/home/vladz/work/urchin/seastar/core/sleep.hh:48:47:   required from ‘seastar::sleep(std::chrono::duration<_Rep, _Period>)::sleeper::sleeper(std::chrono::duration<_Rep, _Period>) [with Clock = std::chrono::_V2::steady_clock; Rep = long int; Period = std::ratio<1l, 1000l>]’
/home/vladz/work/urchin/seastar/core/sleep.hh:52:5:   required from ‘seastar::future<> seastar::sleep(std::chrono::duration<_Rep, _Period>) [with Clock = std::chrono::_V2::steady_clock; Rep = long int; Period = std::ratio<1l, 1000l>]’
./utils/exponential_backoff_retry.hh:45:36:   required from here
/home/vladz/work/urchin/seastar/core/sleep.hh:48:24: error: ‘seastar::sleep(std::chrono::duration<_Rep, _Period>)::sleeper::sleeper(std::chrono::duration<_Rep, _Period>) [with Clock = std::chrono::_V2::steady_clock; Rep = long int; Period = std::ratio<1l, 1000l>]::<lambda()>’ declared with greater visibility than the type of its field ‘seastar::sleep(std::chrono::duration<_Rep, _Period>)::sleeper::sleeper(std::chrono::duration<_Rep, _Period>) [with Clock = std::chrono::_V2::steady_clock; Rep = long int; Period = std::ratio<1l, 1000l>]::<lambda()>::<this capture>’ [-Werror=attributes]
             : tmr([this] { done.set_value(); })
                        ^
cc1plus: all warnings being treated as errors
```
Note that I added a -fvisibility-inlines-hidden but the result is the same with and without it.

The issue also reproduces with the `gcc-7 (Ubuntu 7.1.0-5ubuntu2~16.04) 7.1.0` but **does not** reproduces with `gcc (Ubuntu 5.4.1-2ubuntu1~16.04) 5.4.1 20160904`

**Comment by vladzcloudius** [comment]
So far I found 2 ways to workaround the issue in this particular compilation unit:
  1) Use -fvisibiility=default
  2) By the following patch in the sleep.hh:
```
--- a/core/sleep.hh
+++ b/core/sleep.hh
@@ -40,7 +40,7 @@ namespace seastar {
 /// \return A \ref future which becomes ready when the sleep duration elapses.
 template <typename Clock = steady_clock_type, typename Rep, typename Period>
 future<> sleep(std::chrono::duration<Rep, Period> dur) {
-    struct sleeper {
+    struct __attribute__ ((visibility ("hidden"))) sleeper {
         promise<> done;
         timer<Clock> tmr;
         sleeper(std::chrono::duration<Rep, Period> dur)
```

In a different manifestation of this issue Avi commented that this could be a compiler bug.
It quite may be since the error above implies that the visibility of a lambda itself is not covered by the -fvisibility while its member **is** covered, which indeed doesn't seem like a sane semantics.

However I wonder why we need this -fvisibility=hidden in the first place? 
According to the gcc documentation [here](https://gcc.gnu.org/wiki/Visibility) this option is mainly targeting the  DSO (Dynamic Shared Object) while scylla is not a DSO and seastar is linked statically (at least today). 
I compared the `nm -C -D`output for scylla from the 1.7 release and scylla from the master compiled with -fvisibility=default and the number of symbols in the later is actually smaller: 4800 vs 1351.

I wonder if using -fvisibility=hidden for compiling objects that would eventually be linked into `scylla` and `libseastar.a` has any effect?

**Comment by vladzcloudius** [comment]
Here is the corresponding gcc BUG report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80947

**Comment by vladzcloudius** [comment]
@nyh Could you comment on this please?
It seems that the compilation option in question has been added quite long ago by the following commit: 3578d3d01626cf113935b169debf2084bed72052 .
I wonder if there was a particular reason for that or it was added as a "nice to have" thing?

**Comment by gleb-cloudius** [comment]
On Thu, Jun 01, 2017 at 03:53:20PM -0700, vladzcloudius wrote:
> Here is the corresponding gcc BUG report: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80947
> 
The bugs says *.ii is attached, but I do not see the attachment. Or
should I login to see it?

--
			Gleb.

**Comment by vladzcloudius** [comment]
On Jun 5, 2017 3:17 AM, "Gleb Natapov" <notifications@github.com> wrote:

On Thu, Jun 01, 2017 at 03:53:20PM -0700, vladzcloudius wrote:
> Here is the corresponding gcc BUG report: https://gcc.gnu.org/bugzilla/
show_bug.cgi?id=80947
>
The bugs says *.ii is attached, but I do not see the attachment. Or
should I login to see it?



No idea. I can just send it to you if you want.


--
Gleb.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/scylladb/scylla/issues/2439#issuecomment-306120610>,
or mute
the thread

**Comment by gleb-cloudius** [comment]
On Mon, Jun 05, 2017 at 03:36:06AM -0700, vladzcloudius wrote:
> On Jun 5, 2017 3:17 AM, "Gleb Natapov" <notifications@github.com> wrote:
> 
> On Thu, Jun 01, 2017 at 03:53:20PM -0700, vladzcloudius wrote:
> > Here is the corresponding gcc BUG report: https://gcc.gnu.org/bugzilla/
> show_bug.cgi?id=80947
> >
> The bugs says *.ii is attached, but I do not see the attachment. Or
> should I login to see it?
> 
> 
> 
> No idea. I can just send it to you if you want.
> 
The important question is do GCC developers can see it. I did not, so I
thought may be you forgot to attach it, but if you see it attached this
is fine.

--
			Gleb.

**Comment by vladzcloudius** [comment]
On Jun 5, 2017 6:39 AM, "Gleb Natapov" <notifications@github.com> wrote:

On Mon, Jun 05, 2017 at 03:36:06AM -0700, vladzcloudius wrote:
> On Jun 5, 2017 3:17 AM, "Gleb Natapov" <notifications@github.com> wrote:
>
> On Thu, Jun 01, 2017 at 03:53:20PM -0700, vladzcloudius wrote:
> > Here is the corresponding gcc BUG report: https://gcc.gnu.org/bugzilla/
> show_bug.cgi?id=80947
> >
> The bugs says *.ii is attached, but I do not see the attachment. Or
> should I login to see it?
>
>
>
> No idea. I can just send it to you if you want.
>
The important question is do GCC developers can see it. I did not, so I
thought may be you forgot to attach it, but if you see it attached this
is fine.


I'll double check. Thanks.



--
Gleb.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/scylladb/scylla/issues/2439#issuecomment-306157907>,
or mute
the thread

**Comment by vladzcloudius** [comment]
@gleb-cloudius You (and everybody else) should be able to see it now. The file size exceeded the maximum value, so I had to put a link to it. Thanks for catching it.

**Comment by vladzcloudius** [comment]
@nyh ping

**Comment by nyh** [comment]
@vladzcloudius, why are you pinging me? It was @avikivity who added this "visibility hidden". He explained the rationale in commit be0ae4f5dc027cc2ebe274d34aed94fe6d7b207f:
```
With -fvisibility=hidden, all executable symbols are hidden from shared
objects, allowing more optimizations (especially with -flto). 
```

**Comment by vladzcloudius** [comment]
@nyh I though you added this option in 3578d3d. Thanks for clarification.
