### ISSUE TITLE
scylla_setup script doesn't fail nor exit when supplying non-existing disks and/or non-existing NIC

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla#2442]
**Installation details**
Scylla version (or git commit hash): 1.7 GA
OS: Debian8 -> but I don't think it's Debian specific.

when running scylla_setup in 1 single cmd with non-existing disks + NIC, the script doesn't fail, nor exit, though it prints that it could not find the device. It completes the run and even configure the io.conf.

scylla_setup --disks [non-existing disk] --nic [non-existing NIC] --setup-nic

tomer@tomer-ansible-inst-debian8:~$ sudo /usr/lib/scylla/scylla_setup --disks /dev/sdd --nic eth12 --setup-nic
Skip any of the following steps by answering 'no'
This is a supported kernel version.
Synchronizing state for collectd.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d collectd defaults
Executing /usr/sbin/update-rc.d collectd enable
Generating grub configuration file ...
Found linux image: /boot/vmlinuz-3.16.0-4-amd64
Found initrd image: /boot/initrd.img-3.16.0-4-amd64
done
Reading package lists... Done
Building dependency tree
Reading state information... Done
ntp is already the newest version.
ntpdate is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
 4 Jun 07:44:13 ntpdate[1248]: adjust time server 169.254.169.254 offset -0.000017 sec
**/dev/sdd is not found**
kernel.core_pattern = |/usr/lib/scylla/scylla_save_coredump %e %t %p
Setting parameters on /etc/default/scylla-server
Generating evaluation file sized 10GB...
 stopped early due to disk space issues. Will continue but accuracy may suffer.
8.06079GB written in 69 seconds
Refining search for maximum. So far, 1152 IOPS
Maximum throughput: 1152 IOPS
Recommended --max-io-requests: 39
Written the above values to /etc/scylla.d/io.conf
node_exporter already installed
Reading package lists... Done
Building dependency tree
Reading state information... Done
cpufrequtils is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
Synchronizing state for cpufrequtils.service with sysvinit using update-rc.d...
Executing /usr/sbin/update-rc.d cpufrequtils defaults
Executing /usr/sbin/update-rc.d cpufrequtils enable
ScyllaDB setup finished.
Please restart machine before using ScyllaDB, since you have changed
boot parameters.

**Comment by syuu1228** [comment]
Looks like duplicated with https://github.com/scylladb/scylla/issues/3433 and fix is https://github.com/scylladb/scylla/commit/300af655554e9a50bf33e8271e188d715737bc88#diff-5e299adcf6d654cb5e82f74543585d78.
