### ISSUE TITLE
Can't reconnect a former Scylla Docker container - 5c025849-a15e-4db7-92ca-65a798c7ccb3

### ISSUE THREAD

**Issue by Spirit328** [scylladb/scylla#2447]
*Installation details*
Scylla version (or git commit hash): 2.2.8
Cluster size: CentOS 7
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): VMWare with Docker 17.05.0-ce 
Hardware: sockets=? cores=? hyperthreading=?  memory= >> 100 GB  (BIG (!) HPE C7000 blades)
Disks: (SSD/HDD, count) HDD, 7
Docker Container scylladb/scylla:latest (date: today)

**What I tried:**
I brought up 20 Docker containers of scylladb/scylla:latest on my machine. They started fast and nicely and builded a cluster as requested.   _(I know there is no redundancy, it is for lab purposes only!)_
I created a keyspace and a table with some rows.  
The replication went fine and I saw the same results on any node.  

Then I killed a container (docker rm -f <container-id>).  
I tried to bring up a new one with the **same** alias and wanted it to connect into the same cluster again.  
They container came up, but was terminating itself after ~2 minutes.  
Nodetool marked the formerly started container as "DN".  No matter what I tried, it didn't change the status. Well, I didn't wait for 72 hours!

Then I killed all containers and started a new cluster with only 4 containers. Anything as before.  
After I killed the container "scylla2" via docker rm -f scylla2, it got deleted. Then I tried to start it again with:
~~~
docker run --name scylla2 -d -m 1g -d scylladb/scylla:latest --seeds="$(docker inspect --format='{{ .NetworkSettings.IPAddress }}' scylla1)"
~~~
The container came up nicely, but nodetools insists on the status "DN". (siehe the provided documentation)

I neither could change the status, nor can I remove this node from the cluster; no matter what Mr. Google sugggests.  

Is this a bug / issue or is it a "Between-screen-and-chair"-problem ?  

Cheers
Thorsten

**Comment by slivne** [comment]
In a regular (non docker) deployment the manner to replace a failed node is to use the replace_address /replace_address_first_boot  http://docs.scylladb.com/procedures/replace_dead_node/

but currently we do not support this via the command line in docker.

another alternative in testing case is to use removenode and then to add a new node - this has a higher overhead as streaming will happen twice.

if there is a need to further elaborate, additional question please post it on the issue.

I am closing it for now.
