### ISSUE TITLE
AWS: first DC name is inconsistent with config

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2460]
*Installation details*
Scylla version (or git commit hash): 1.7.0
Cluster size:    2 + 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): us-east-1: ami-40a0e756 us-west-2: ami-77e78617

Environment AWS:
   Ec2MultiRegionSnitch

Assigned datacenter name is 'us-east-1', but it's 'us-east' in result of `nodetool status`.
But second dc name is fine, assigned name is same as in nodetool result (us-west-2).

```
[node1@dc1 ~]$ cat /etc/scylla/cassandra-rackdc.properties
dc=us-east-1
rack=RACK1

[node2@dc2 ~]$ cat /etc/scylla/cassandra-rackdc.properties
dc=us-west-2
rack=RACK1
```

```
[node1@dc1 ~]$ nodetool status
Datacenter: us-east
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns    Host ID                               Rack
UN  107.23.128.5    294.19 KB  256          ?       3101b413-ea11-4544-847a-342beebddbd6  1b
UN  54.226.213.119  292.83 KB  256          ?       ddc2ad67-8435-4e88-89f7-31d6017e6be1  1b
Datacenter: us-west-2
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns    Host ID                               Rack
UN  54.187.95.105   284.06 KB  256          ?       5c789da7-5bbb-4bc3-bb3f-ab890868159b  2b
UN  54.202.89.57    266.76 KB  256          ?       e4ae79b6-945f-4b27-a729-d94b0b9d257b  2b
```

```
cqlsh> select data_center from system.peers;

 data_center
-------------
   us-west-2
   us-west-2
     us-east

(3 rows)
```

@nirmaayan

**Comment by amoskong** [comment]
The rack I set is 'RACK1', but the Rack value in result of `nodetool status` is `1b`, `2b`

**Comment by amoskong** [comment]
I used Ec2MultiRegionSnitch as suggested in http://docs.scylladb.com/procedures/create_cluster_multidc/.

Just talked with @asias , dc name and rack name will be set automatically if Ec2MultiRegionSnitch is used.

So it's not a bug.

**Comment by slivne** [comment]
@amoskong so can we close this ?

**Comment by tzach** [comment]
@amoskong ping

**Comment by amoskong** [comment]
Let's close it.
