### ISSUE TITLE
support to disable/enable part of experimental features

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2472]
*Installation details*
Scylla version (or git commit hash): master / 1.7

*Description*
Currently if we set `experimental` to true in scylla.yaml, all experimental features will be enabled.
This will might introduce more unstable factors for users.

How about add a new parameter in scylla.yaml like this:
```
# Features list: https://github.com/scylladb/scylla/wiki/Experimental-features
experimental_features: COUNTERS, EXAMPLE1, EXAMPLE2
```

By default, experimental_features: ''

**Comment by duarten** [comment]
We had a long discussion about this some time ago, and the decision we reached was that experimental features should be enabled as a whole, to ensure they also play nice together while still in development. 

/cc @penberg @nyh
