### ISSUE TITLE
bad_alloc caused by too many prepared statements

### ISSUE THREAD

**Issue by hchargois** [scylladb/scylla#2474]
*Installation details*
Scylla version (or git commit hash): 1.6.4
Cluster size: 1 instance
OS (RHEL/CentOS/Ubuntu/AWS AMI): Bug reproduced on both a Debian bare-metal install and a test docker container

I've faced a bug that caused bad_alloc errors to be logged and the cluster to become unresponsive. These are the kind of messages that I got in the logs:

    Jun  9 13:00:37 scylladata01 scylla:  [shard 9] storage_proxy - exception during mutation write to 10.10.0.21: std::bad_alloc (std::bad_alloc)
    Jun  9 13:00:38 scylladata01 scylla:  [shard 0] storage_proxy - Exception when communicating with 10.10.0.21: std::bad_alloc

I've seen a few open issues about bad_allocs, but they didn't help me resolve my problem.

I noticed that the problem occurred when a lot of prepared statements were being used. More precisely, I was using the go-cql client that always prepares the queries if it isn't in its internal cache already.

I was putting unique comments in my queries for traceability, and that meant the queries were unique and each of them was prepared by go-cql. When I removed the comment, much less distinct queries were being seen, much less prepare statements were being sent by go-cql, and poof the whole problem disappeared.

I'm sharing this so that maybe this gives you somewhere to look at to solve bad_alloc errors, since in my case I am satisfied with just being careful as to how many prepare statements I'm doing.

**Comment by penberg** [comment]
Apache Cassandra limits the amount of memory prepared statements can take up from the server to `maximum memory / 256` whereas we don't have such restriction and allow prepared statement cache to grow indefinitely.

/cc @tgrabiec @avikivity

**Comment by avikivity** [comment]
Let's limit it indeed.
