### ISSUE TITLE
Unit test failure: `commitlog_test` fails to allocate output buffer

### ISSUE THREAD

**Issue by hakuch** [scylladb/scylla#2495]
*Installation details*
Scylla version (or git commit hash): 419ad9d6cb8a8592dcf320d354a4c38b8a51ff68
Cluster size: N/A
OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora 25

The `commitlog_test` fails with the following output from the aforementioned commit on `master`:

```
$ ./test.py --mode=release
FAILED: build/release/tests/commitlog_test                                   
  with error code 201                      
=== stdout START ===
Running 14 test cases...
tests/commitlog_test.cc(325): fatal error: in "test_commitlog_reader": critical check segments.size() > 1 has failed
WARN  2017-06-16 17:10:11,549 [shard 0] commitlog - Could not allocate 16388 k bytes output buffer (16388 k required)

*** 1 failure is detected in the test module "tests/commitlog_test.cc"

=== stdout END ===
```
I'm not yet sure when this failure was introduced, but as a starting point, 15a62701f296471cdb7993ba08519d85d1606d65 tests cleanly.

**Comment by duarten** [comment]
Can you try with 3464422051efb111557b135fc53b278d86b2bc54 applied?

**Comment by hakuch** [comment]
That commit tests cleanly. Thanks!
