### ISSUE TITLE
Alter table did not work after creation of materialized view from an empty table

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#2500]
python-driver test was reproduced on scylla master.
Steps to reproduce:
1. create table
2. create materialized view
3. alter table - modify column type
The table has no data.

cqlsh> CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

cqlsh> CREATE TABLE ks.scores (
    user text,
    game text,
    year int,
    month int,
    day int,
    score text,
    PRIMARY KEY (user, game, year, month, day)
) WITH CLUSTERING ORDER BY (game ASC, year ASC, month ASC, day ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cqlsh> CREATE MATERIALIZED VIEW ks.monthlyhigh AS
    SELECT game, year, month, score, user, day
    FROM ks.scores
    WHERE game IS NOT null AND year IS NOT null AND month IS NOT null AND score IS NOT null AND user IS NOT null AND day IS NOT null
    PRIMARY KEY ((game, year, month), score, user, day)
    WITH CLUSTERING ORDER BY (score DESC, user ASC, day ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cqlsh> ALTER TABLE ks.scores **ALTER score TYPE blob**;
cqlsh> DESC ks.scores 

CREATE TABLE ks.scores (
    user text,
    game text,
    year int,
    month int,
    day int,
    **score text**,
    PRIMARY KEY (user, game, year, month, day)
) WITH......

**Comment by duarten** [comment]
The problem is that we're serializing the base table schema mutations along with the view schema mutations, which is not needed when the view is being changed as a consequence of an alter table, but needed when the view is being altered by itself.
