### ISSUE TITLE
wrong select results in case of multiple materialized views per table

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#2504]
python-driver test: 
tests.integration.standard.test_query:MaterializedViewQueryTest.test_mv_filtering
https://github.com/datastax/python-driver/blob/master/tests/integration/standard/test_query.py

how to reproduce:
1. create table
2. create 4 materialized views 
3. insert data to the table
4. select * from each mv - part of data is missing in each one

**Comment by duarten** [comment]
What fails exactly?

**Comment by larisau** [comment]
CREATE KEYSPACE materializedviewquerytest WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE materializedviewquerytest.scores (
    user text,
    game text,
    year int,
    month int,
    day int,
    score int,
    PRIMARY KEY (user, game, year, month, day)
) WITH CLUSTERING ORDER BY (game ASC, year ASC, month ASC, day ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW materializedviewquerytest.monthlyhigh AS
    SELECT *
    FROM materializedviewquerytest.scores
    WHERE game IS NOT null AND year IS NOT null AND month IS NOT null AND score IS NOT null AND user IS NOT null AND day IS NOT null
    PRIMARY KEY ((game, year, month), score, user, day)
    WITH CLUSTERING ORDER BY (score DESC, user ASC, day ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW materializedviewquerytest.dailyhigh AS
    SELECT *
    FROM materializedviewquerytest.scores
    WHERE game IS NOT null AND year IS NOT null AND month IS NOT null AND day IS NOT null AND score IS NOT null AND user IS NOT null
    PRIMARY KEY ((game, year, month, day), score, user)
    WITH CLUSTERING ORDER BY (score DESC, user ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW materializedviewquerytest.filtereduserhigh AS
    SELECT *
    FROM materializedviewquerytest.scores
    WHERE user IN ('jbellis', 'pcmanus') AND game IS NOT null AND score IS NOT null AND year IS NOT null AND day IS NOT null AND month IS NOT null
    PRIMARY KEY (game, score, user, year, month, day)
    WITH CLUSTERING ORDER BY (score DESC, user ASC, year ASC, month ASC, day ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW materializedviewquerytest.alltimehigh AS
    SELECT *
    FROM materializedviewquerytest.scores
    WHERE game IS NOT null AND score IS NOT null AND user IS NOT null AND year IS NOT null AND month IS NOT null AND day IS NOT null
    PRIMARY KEY (game, score, user, year, month, day)
    WITH CLUSTERING ORDER BY (score DESC, user ASC, year ASC, month ASC, day ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

Insert data to materializedviewquerytest.scores
cqlsh> select * from materializedviewquerytest.scores;

 user       | game     | year | month | day | score
------------+----------+------+-------+-----+-------
    pcmanus |    Chess | 2015 |     1 |  25 |  3200
    pcmanus |     Coup | 2015 |     5 |   1 |  4000
    pcmanus |     Coup | 2015 |     6 |   2 |  2000
      yukim |     Coup | 2015 |     5 |   3 |  2250
  jmckenzie |     Coup | 2015 |     6 |   9 |  2700
 iamaleksey |     Coup | 2015 |     6 |   1 |  2500
      tjake |     Coup | 2015 |     5 |   3 |   500
      tjake |     Coup | 2015 |     6 |   2 |  1000
    jbellis | Checkers | 2015 |     6 |  20 |  1200
    jbellis |    Chess | 2015 |     6 |  21 |  3500
    jbellis |     Coup | 2015 |     5 |   3 |  1750
    jbellis |     Coup | 2015 |     6 |  20 |  3500

(12 rows)
cqlsh> SELECT * FROM materializedviewquerytest.dailyhigh WHERE game='Coup' AND year=2015 AND month=6 and day=2;

 game | year | month | day | score | user
------+------+-------+-----+-------+------

(0 rows)
The last query should contain 2 rows.
cqlsh> SELECT * FROM materializedviewquerytest.dailyhigh;

 game     | year | month | day | score | user
----------+------+-------+-----+-------+------------
 Checkers | 2015 |     6 |  20 |  1200 |    jbellis
     Coup | 2015 |     6 |   9 |  2700 |  jmckenzie
     Coup | 2015 |     6 |   1 |  2500 | iamaleksey
     Coup | 2015 |     6 |  20 |  3500 |    jbellis
    Chess | 2015 |     6 |  21 |  3500 |    jbellis

(5 rows)
The above query should contain 12 rows.

**Comment by duarten** [comment]
Works for me locally, with a single node, with -smp 1 and -smp 4:

```
CREATE KEYSPACE materializedviewquerytest WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'} AND durable_writes = true;

CREATE TABLE materializedviewquerytest.scores (
user text,
game text,
year int,
month int,
day int,
score int,
PRIMARY KEY (user, game, year, month, day)
) WITH CLUSTERING ORDER BY (game ASC, year ASC, month ASC, day ASC)
AND bloom_filter_fp_chance = 0.01
AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
AND comment = ''
AND compaction = {'class': 'SizeTieredCompactionStrategy'}
AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
AND crc_check_chance = 1.0
AND dclocal_read_repair_chance = 0.1
AND default_time_to_live = 0
AND gc_grace_seconds = 864000
AND max_index_interval = 2048
AND memtable_flush_period_in_ms = 0
AND min_index_interval = 128
AND read_repair_chance = 0.0
AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW materializedviewquerytest.dailyhigh AS
SELECT *
FROM materializedviewquerytest.scores
WHERE game IS NOT null AND year IS NOT null AND month IS NOT null AND day IS NOT null AND score IS NOT null AND user IS NOT null
PRIMARY KEY ((game, year, month, day), score, user)
WITH CLUSTERING ORDER BY (score DESC, user ASC)
AND bloom_filter_fp_chance = 0.01
AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
AND comment = ''
AND compaction = {'class': 'SizeTieredCompactionStrategy'}
AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
AND crc_check_chance = 1.0
AND dclocal_read_repair_chance = 0.1
AND default_time_to_live = 0
AND gc_grace_seconds = 864000
AND max_index_interval = 2048
AND memtable_flush_period_in_ms = 0
AND min_index_interval = 128
AND read_repair_chance = 0.0
AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW materializedviewquerytest.monthlyhigh AS
SELECT *
FROM materializedviewquerytest.scores
WHERE game IS NOT null AND year IS NOT null AND month IS NOT null AND score IS NOT null AND user IS NOT null AND day IS NOT null
PRIMARY KEY ((game, year, month), score, user, day)
WITH CLUSTERING ORDER BY (score DESC, user ASC, day ASC)
AND bloom_filter_fp_chance = 0.01
AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
AND comment = ''
AND compaction = {'class': 'SizeTieredCompactionStrategy'}
AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
AND crc_check_chance = 1.0
AND dclocal_read_repair_chance = 0.1
AND default_time_to_live = 0
AND gc_grace_seconds = 864000
AND max_index_interval = 2048
AND memtable_flush_period_in_ms = 0
AND min_index_interval = 128
AND read_repair_chance = 0.0
AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW materializedviewquerytest.filtereduserhigh AS
SELECT *
FROM materializedviewquerytest.scores
WHERE user IN ('jbellis', 'pcmanus') AND game IS NOT null AND score IS NOT null AND year IS NOT null AND day IS NOT null AND month IS NOT null
PRIMARY KEY (game, score, user, year, month, day)
WITH CLUSTERING ORDER BY (score DESC, user ASC, year ASC, month ASC, day ASC)
AND bloom_filter_fp_chance = 0.01
AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
AND comment = ''
AND compaction = {'class': 'SizeTieredCompactionStrategy'}
AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
AND crc_check_chance = 1.0
AND dclocal_read_repair_chance = 0.1
AND default_time_to_live = 0
AND gc_grace_seconds = 864000
AND max_index_interval = 2048
AND memtable_flush_period_in_ms = 0
AND min_index_interval = 128
AND read_repair_chance = 0.0
AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW materializedviewquerytest.alltimehigh AS
SELECT *
FROM materializedviewquerytest.scores
WHERE game IS NOT null AND score IS NOT null AND user IS NOT null AND year IS NOT null AND month IS NOT null AND day IS NOT null
PRIMARY KEY (game, score, user, year, month, day)
WITH CLUSTERING ORDER BY (score DESC, user ASC, year ASC, month ASC, day ASC)
AND bloom_filter_fp_chance = 0.01
AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
AND comment = ''
AND compaction = {'class': 'SizeTieredCompactionStrategy'}
AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
AND crc_check_chance = 1.0
AND dclocal_read_repair_chance = 0.1
AND default_time_to_live = 0
AND gc_grace_seconds = 864000
AND max_index_interval = 2048
AND memtable_flush_period_in_ms = 0
AND min_index_interval = 128
AND read_repair_chance = 0.0
AND speculative_retry = '99.0PERCENTILE';

insert into materializedviewquerytest.scores (user, game, year, month, day, score) values ('pcmanus', 'Chess', 2015, 1, 25, 3200);

insert into materializedviewquerytest.scores (user, game, year, month, day, score) values ('pcmanus', 'Coup', 2015, 5, 1, 4000);

insert into materializedviewquerytest.scores (user, game, year, month, day, score) values ('pcmanus', 'Coup', 2015, 6, 2, 2000);

insert into materializedviewquerytest.scores (user, game, year, month, day, score) values ('yukim', 'Coup', 2015, 5, 3, 2250);

insert into materializedviewquerytest.scores (user, game, year, month, day, score) values ('jmckenzie', 'Coup', 2015, 6, 9, 2700);

insert into materializedviewquerytest.scores (user, game, year, month, day, score) values ('iamaleksey', 'Coup', 2015, 6, 1, 2500);

insert into materializedviewquerytest.scores (user, game, year, month, day, score) values ('tjake', 'Coup', 2015, 5, 3, 500);

insert into materializedviewquerytest.scores (user, game, year, month, day, score) values ('tjake', 'Coup', 2015, 6, 2, 1000);

insert into materializedviewquerytest.scores (user, game, year, month, day, score) values ('jbellis', 'Checkers', 2015, 6, 20, 1200);

insert into materializedviewquerytest.scores (user, game, year, month, day, score) values ('jbellis', 'Chess', 2015, 6, 21, 3500);

insert into materializedviewquerytest.scores (user, game, year, month, day, score) values ('jbellis', 'Coup', 2015, 5, 3, 1750);

insert into materializedviewquerytest.scores (user, game, year, month, day, score) values ('jbellis', 'Coup', 2015, 6, 20, 3500);

cqlsh>  SELECT * FROM materializedviewquerytest.dailyhigh;

 game     | year | month | day | score | user
----------+------+-------+-----+-------+------------
     Coup | 2015 |     5 |   1 |  4000 |    pcmanus
    Chess | 2015 |     1 |  25 |  3200 |    pcmanus
 Checkers | 2015 |     6 |  20 |  1200 |    jbellis
     Coup | 2015 |     6 |   9 |  2700 |  jmckenzie
     Coup | 2015 |     6 |   1 |  2500 | iamaleksey
     Coup | 2015 |     6 |  20 |  3500 |    jbellis
    Chess | 2015 |     6 |  21 |  3500 |    jbellis
     Coup | 2015 |     6 |   2 |  2000 |    pcmanus
     Coup | 2015 |     6 |   2 |  1000 |      tjake
     Coup | 2015 |     5 |   3 |  2250 |      yukim
     Coup | 2015 |     5 |   3 |  1750 |    jbellis
     Coup | 2015 |     5 |   3 |   500 |      tjake

(12 rows)
cqlsh> SELECT * FROM materializedviewquerytest.dailyhigh WHERE game='Coup' AND year=2015 AND month=6 and day=2;

 game | year | month | day | score | user
------+------+-------+-----+-------+---------
 Coup | 2015 |     6 |   2 |  2000 | pcmanus
 Coup | 2015 |     6 |   2 |  1000 |   tjake

(2 rows)
cqlsh>
```

Were you testing with more than 1 node? How much time elapsed between the last insert and the query?

**Comment by larisau** [comment]
It's 3-node cluster, the query executed immediately after the last insert.

**Comment by duarten** [comment]
Can you try with a) a 1 node cluster and b) a sleep between the last insert and the first query?

**Comment by slivne** [comment]
@duarten , @larisau any update ?

**Comment by duarten** [comment]
@slivne I was waiting for an update from @larisau. My guess is that it's an issue due to the asynchronous propagation; I can't think of any other reason for it not to work (and it does locally).
