### ISSUE TITLE
support non reserved keywords as columns (without quotes)

### ISSUE THREAD

**Issue by dduponchel** [scylladb/scylla#2507]
I'm migrating  a cassandra 2.1 cluster to scylla 1.7 but my schema has a `frozen` field which causes errors. I strongly suspect it's because `frozen` is a [non-reserved keyword](http://docs.datastax.com/en/cql/3.1/cql/cql_reference/keywords_r.html).

I'm using here VMs to reproduce the issue.

### Cassandra side

I have a cassandra 2.1.17.1439 cluster which uses a column named `frozen`. Minimalist schema:

```cql
CREATE KEYSPACE my_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

CREATE TABLE my_keyspace.my_table (
    id text,
    frozen boolean,
    PRIMARY KEY (id)
);

insert into my_keyspace.my_table (id, frozen) values ('1', false);
insert into my_keyspace.my_table (id, frozen) values ('2', true);
```

I also use the java driver (2.1, migrating to 3.2 but both give the same result) and its `QueryBuilder` to generate queries like

```cql
UPDATE my_keyspace.my_table SET frozen=true WHERE id='1';
```

### Scylla side
On scylla (1.7.1-0.20170607.dbbf99d, on debian 8), I had to change the schema:

```diff
- frozen boolean,
+ "frozen" boolean,
```

 I copied the sstables from the cassandra VM to the scylla one and used sstableloader (scylla version) to load the sstable:

```
$ sstableloader -v --nodes 10.0.1.2 ./my_keyspace/my_table-a4c097f054f711e7b1a6c508be5066c2/
CQL: 'INSERT INTO my_keyspace.my_table (frozen,id) values (?,?) USING TIMESTAMP ?;' [false, 1, 1497880828342671]
com.datastax.driver.core.exceptions.SyntaxError: line 1:34 no viable alternative at input 'frozen'
```

Same error with the update query:

```
$ cqlsh
cqlsh> UPDATE my_keyspace.my_table SET frozen=true WHERE id='1';
SyntaxException: line 1:32 no viable alternative at input 'frozen'
```

It does work with quotes (`UPDATE my_keyspace.my_table SET "frozen"=true WHERE id='1';`) but keeping the same behavior as cassandra would help (and probably fix the sstableloader issue).

**Comment by tzach** [comment]
@slivne @penberg can we backport to 1.7? looks pretty safe to me

**Comment by avikivity** [comment]
Done.
