### ISSUE TITLE
sstable statistics

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#251]
Add the following sstable statistics

sstables created/sec
sstables deleted/sec
opened for write/sec
opened for read/sec
current open for read
current open for write
bloom filter memory
mutations read/sec
bytes read/sec
mutations written/sec
bytes written/sec
single key seek/sec
range seek/sec
current ongoing reads

Note: per second statistics are just counters; the derivative wrt time is taken on the client

**Comment by tzach** [comment]
@avikivity @slivne this is not a must for GA.
If not objections, I will move to Yellowfin.

**Comment by benoit-canet** [comment]
@avikivity : I mulled about this a while in my corner but what are single key and range seek ?

**Comment by slivne** [comment]
@avikivity - should these metrics be perf cf or should they be global ?

I think we originally created this when we did first installations and wanted to align # of read bytes to # of mutations (it was very simplistic at the time single keyspace single cf)

**Comment by benoit-canet** [comment]
@tzach: Can you help us define these metrics ? We don't know if they should be per cf or global or anything ? Avi seems as puzzled as me regarding this on the mailling list.

**Comment by amnonh** [comment]
I'm looking over the metrics, derivative metrics (i.e. bytes/sec) should be calculated at the monitoring server, so the metrics should report the total (bytes, number etc')

I've looked at how other global statistics are implemented (sstable index) and can use the same approach.

The main issue is the duplications, we can have the same sstable on multiple shards, for the total number of reads/write it shouldn't be a problem, but holding statistic per sstable and remove the duplication on each metrics calculation can get expensive.

**Comment by slivne** [comment]
We reshard shared sstables - so if there is any duplication (and I am not sure there is) its temporary. Most of the counters are operations in the shard - so they will be true in any case (like the existing index page metrics).

**Comment by tgrabiec** [comment]
7322ac1 did not add all the metrics requested in the description. We're missing:

sstables created/sec
sstables deleted/sec
opened for write/sec
opened for read/sec
current open for read
current open for write
bloom filter memory

Reopening.

**Comment by bhalevy** [comment]
In addition to the list above, @tgrabiec also suggested:
> Even something as simple as sstable count and size on disk would allow us to correlate that with non-LSA memory growth.

@raphaelsc please take it from here.

Please send separate patches for the different stats as you implement and test them and not wait for everything to be accomplished.

**Comment by bhalevy** [comment]
@cmm please see https://github.com/scylladb/scylla/issues/251#issuecomment-579663680

**Comment by bhalevy** [comment]
Let's start with adding sstables created/deleted/opened stats.
Then, later on, look into bloom filter memory (see also #2465, #5266. I'd like to be able to reproduce those issues and measure the bloom filter size with this metric)

**Comment by bhalevy** [comment]
Closing this issue with https://github.com/scylladb/scylla/pull/8630
