### ISSUE TITLE
scylla_setup should verify that swap is configured on a host and highly recommend to configure it in case it isn't

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#2511]
*Installation details*
We've seen that in some cases where the scylla nodes where configured without swap at all, there were some cases we will run out of memory and scylla stops.

@avikivity and @gleb-cloudius recommended to configure swap in the system.

**Comment by dorlaor** [comment]
Swap will kill our performance so we definitely do not want Scylla to be
swapped out.
However, sometimes it is nice to allow Linux to swap other processes like
scripts and other daemons.
I think it's impossible in Linux to make a process not swappable while
other are swappable and thus we
should disable swap

**Comment by avikivity** [comment]
Low-memory machines can lose the ability to run simple administrative commands (`top`) without swap, just ran into this problem.

**Comment by tzach** [comment]
#365

**Comment by tzach** [comment]
> Low-memory machines can lose the ability to run simple administrative commands (top) without swap, just ran into this problem.

@avikivity should we add swap test to scylla_setup? only for some cases (low memory machines?)

**Comment by nyh** [comment]
@avikivity why is this specific to "low-memory machines"? Could it be that we leave a _percentage_ of memory unused, and this percentage translates to too little memory on a low-memory machine?
If that is the case perhaps we should add a larger constant (not percentage) to the amount of memory we leave free?

**Comment by slivne** [comment]
So we just ran today into this again.

So lets change scylla_setup to check if there is a swap or not and recommend a swap if one does not exist. 

@avikivity 

Should we make sure that scylla memory is non swapable (locked)

```
commit c15055cbb8fe50a3b2249febebef4fc9c6a44962
Author: Avi Kivity <avi@scylladb.com>
Date:   Sun Jun 26 18:54:47 2016 +0300

    memory: add option to mlock() all memory
    
    Seastar application rely on the reactor thread never blocking for good
    performance.  Part of this is never swapping; provide the option to mlock()
    all memory so this can be done.
    
    Note: --lock-memory 1 should only be specified on a server that is only
          running the seastar application; never on a desktop or a shared server,
          unless --memory is also specified to limit the amount of memory used
          by seastar.
    
    See scylladb/scylla#1393.
```

**Comment by slivne** [comment]
@avikivity ping

**Comment by tzach** [comment]
@avikivity @slivne can we break the memory locking and swap to two issues so we can make progress for the second, even if there is no agreement on the first?

**Comment by slivne** [comment]
@avikivity I want to try and move this forward to have it in 3.2 we can defer the decision with locking and enable/recommend swap currently

would that be an acceptable solution for 3.2 ?

**Comment by avikivity** [comment]
yes

**Comment by slivne** [comment]
Great ...

should we also set the value for ```vm.swappiness``` (the default is 60)

**Comment by avikivity** [comment]
A good value is 1.

**Comment by bhalevy** [comment]
@syuu1228 ping.  This issue has been opened for a long time with no material progress,
yet it is labeled as high priority and targeted for 3.2.

@slivne please revise the milestone and priority.

**Comment by syuu1228** [comment]
@bhalevy Okay I'll handle this very soon.

**Comment by syuu1228** [comment]
patch sent on the ml: [PATCH scylla] dist/common/scripts/scylla_setup: add swap existance check

**Comment by bhalevy** [comment]
@roydahan / @avikivity does the fix need to be backported?

**Comment by avikivity** [comment]
No. This is just a check that swap exists.

**Comment by tomer-sandler** [comment]
@avikivity @slivne @bhalevy it would make a lot of sense to have this backported to all supported OSS version (currently 3.2 + 3.1) and to 2019.1. We are seeing a lot of cases where customers hit issues due to no swap setup.
70% of our paying customer deployments are on 2019.1 +  12% are still on 2018.1
The rest are on various OSS, but we should have this in 3.2 + 3.1 for sure, and if possible in all 3.x

@vladzcloudius @eyalgutkind WDYT?

**Comment by vladzcloudius** [comment]
@tomer-sandler I agree.

**Comment by eyalgutkind** [comment]
+1 @Tomer Sandler <tomer@scylladb.com>

**Comment by tzach** [comment]
**No swap is configured, it is highly recommended to setup swap on Scylla node.**

I'm getting this warning when running on i3.large, but what should I do next? Google for swap?
And if there is a command, why not add it to the setup_script?

This is not a great UX to "highly recommended" an action and leave him to find out on his own.

**Comment by tomer-sandler** [comment]
There are our docs reference for swap - again no command/steps on how to set it up:
FAQ: https://docs.scylladb.com/faq/#do-i-need-to-configure-swap-on-a-scylla-node
KB: https://docs.scylladb.com/kb/unresponsive-nodes/

The steps on how to setup swap can be found here (We could copy-paste them to our docs, or reference this link):
https://linuxize.com/post/create-a-linux-swap-file/

@tzach @lauranovich

**Comment by dorlaor** [comment]
How about we'll get back to this and setup swap as part of scylla_setup ?

**Comment by tzach** [comment]
Thanks @tomer-sandler 
As much as I love our docs, Scylla install process should be self contained. We should not send someone to docs mid process; unless its a very rare case. This is **not** a rare case.

**Comment by tzach** [comment]
https://github.com/scylladb/scylla/issues/6539
