### ISSUE TITLE
Latency spikes during repair/streaming

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2512]
During streaming or a large repair, we observe large latency spikes (100ms) when a memtable is flushed.

**Comment by gleb-cloudius** [comment]
On Tue, Jun 20, 2017 at 02:26:00AM -0700, Avi Kivity wrote:
> During streaming or a large repair, we observe large latency spikes (100ms) when a memtable is flushed.
> 
Is this the same as #2477?

--
			Gleb.

**Comment by avikivity** [comment]
Looks very similar, was that taken during streaming/repair?

**Comment by gleb-cloudius** [comment]
On Tue, Jun 20, 2017 at 02:32:03AM -0700, Avi Kivity wrote:
> Looks very similar, was that taken during streaming/repair?
> 
Yes.

--
			Gleb.
