### ISSUE TITLE
enable counter feature in a exist cluster version1.7.1 - terrible  way!

### ISSUE THREAD

**Issue by zhshw** [scylladb/scylla#2513]
how can i enable counter feature in a exist cluster version1.7.1 ? 
https://github.com/scylladb/scylla/wiki/Experimental-features
Enable experimental features by changing scylla.yaml: 
experimental: true

I have modified one of the nodes and restarted the service.   but ...Do I have to restart all the nodes?
This way of enable counter feature  is very terrible for a exist cluster

**Comment by dorlaor** [comment]
You do need to restart all the nodes. You can however restart them in a
rolling fashion
so you won't lose availability. We discuss now whether future features
should be
protected by this flag or just to enable them by default and point to the
release
notes and the status page.

**Comment by penberg** [comment]
@zhshw Is it a production cluster? Please note that for the upcoming Scylla 2.0, counters are no longer flagged as experimental and the feature is enabled whenever your whole cluster is upgraded. If you want to use counters in production, you're strongly recommended to wait for that release.

**Comment by dorlaor** [comment]
@penberg, our counters are just fine and there is not know problem with
them.
2.0 only improve the performance of the counters (which is pretty good to
begin with).
We were careful to use --experimental on the first release we published
them but it's perfectly
fine to use them in 1.7 in production.

**Comment by avikivity** [comment]
Counters are now non-experimental. Closing.
