### ISSUE TITLE
scylla does not have 'system' keyspace

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#2514]
cassandra 3.X has 'system' keyspace with all the tables (batches, hints, peers, local etc.)
scylla master does not have this

**Comment by elcallio** [comment]
Skylla most certainly have a system  keyspace. It is right in
system_keyspace.cc.

Den 20 jun 2017 12:59 skrev "Larisa Ustalov" <notifications@github.com>:

**Comment by slivne** [comment]
Larisa can you boot a scylla node (and provide the git commit you used for
that).

and connect using cqlsh and do describe schema -

**Comment by elcallio** [comment]
But I will grant that it is not listed by cqlsh, while C3:s is, so 
something is indeed slightly fishy.


Den 2017-06-20 kl. 12:59, skrev Larisa Ustalov:

**Comment by elcallio** [comment]
Seems that while the keyspace exists, it is _not_ inserted into system_schema.keyspaces. So cqlsh/driver/whatnot has no idea to look for it.

**Comment by tgrabiec** [comment]
The commit was reverted in f0b20be14deca79c702bebebb9a46a9f7f0d0941
