### ISSUE TITLE
Package sstableloader independently 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2515]
sstableloader is used to migrate from Cassandra to Scylla. As such, it will be useful to install it on a Cassandra server.
Scylla itself have [conflict](https://github.com/scylladb/scylla/commit/da55aecca3e8b9d9d000996fec99a3ccf45c13cf) with Cassandra, but for sstableloader it should be straightforward to solve the conflict, for example by naming it scylla-sstableloader.

**Comment by slivne** [comment]
fixed by scylladb/scylla-tools-java@0cd37a991eaafb651e644a3391ae81f24538aff5

**Comment by tzach** [comment]
@slivne is this really new in 2.1?

**Comment by slivne** [comment]
nope it was already done there are to packages now for scylla-tools,
scylla-tools-core

sstableloader is part of scylla-tools-core and its also can be installed on
a cassandra server - in which case to run it you run scylla-sstableloader

**Comment by slivne** [comment]
it was part of 2.0
