### ISSUE TITLE
Scylla should be able to re-read the configuration file without restart).

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#2517]
Scylla version (or git commit hash): 1.7

Scylla needs to compare the yaml file changes between the run time config and the file and if possible 
apply the changes (like enabling an experimental flag dynamically). Need to send Scylla a notice (or can it register to the yaml file changes) when the content changes

**Comment by glommer** [comment]
Just to make it clear: If I read the patch correctly, this is still not enough to change seastar properties, like the block detector threshold.

Correct?
