### ISSUE TITLE
error system:103, Software caused connection abort

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#2518]
*Installation details*
Scylla version (or git commit hash): 1.7.1

I got a this messages..
When do I get this message?

scylla: [shard 0] cql_server - acccept failed: std::system_error (error system:103, Software caused connection abort)

 scylla is working normally.

**Comment by slivne** [comment]
pasted comment from avi
> Ok, what happened here that the client initiated a connection, but even before the connection was established, it was dropped.
