### ISSUE TITLE
AMI does not get ixgbevf on c4.*xlarge

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#252]
I'm not sure this is our AMI issue or EC2 issue, but I haven't able to get ixgbevf with our AMI, on c4.*xlarge.
(I could get ixgbevf with official linux image before)
Therefore build_ami.sh only supports posix mode for now.

**Comment by slivne** [comment]
Vlad has enabled enhanced netoworking on the base AMI - so this can be closed
