### ISSUE TITLE
Don't invalidate whole repair range in cache

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2523]
Currently repair and token range ownership movements (e.g. during node join) share the infrastructure on replica side (see  `column_family::flush_streaming_mutations()`), which invalidates affected ranges in cache. However, that is only really necessary for range movements. Repair can rely just on the regular cache update logic which happens on memtable flush, which can be much more fine grained.

**Comment by asias** [comment]
flush_streaming_mutations is removed for a while. Repair does not invalidate whole repair range in cache.
