### ISSUE TITLE
Single-key sstable reads are treated like scans

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2524]
*Installation details*
Scylla version (or git commit hash): master

After commit 317d7fc, `column_family::make_sstable_reader()` will use the single-key sstable reader only if `!fwd_mr`:

```
    if (pr.is_singular() && pr.start()->value().has_key() && !fwd_mr) {        
```

However, `fwd_mr` still defaults to `yes` in most places, including `column_family::data_query()`. So single-key reads will behave like scans, which means doing I/O for every sstable instead of only those which contain the key (according to the bloom filter).

The same fix should be applied here as was to `sstable::as_mutation_source()` in 186f031, that is to assume mutation_reader::forwarding::no for single-key restrictions.

**Comment by avikivity** [comment]
@roydahan @larisau this is the kind of bug that read amplification tests are supposed to catch, so we can use it to test the test.
