### ISSUE TITLE
scylla crash on sstable corruption

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#2532]
1. create 1-node cluster
2. run stress write:
../scylla-tools-java/tools/bin/cassandra-stress write n=1000000 -node 127.0.0.1 -port jmx=9042 -pop seq=0..1000000
3. flush data to sstables
4. corrup sstable files - flip number of bits in 2 files:
keyspace1-standard1-ka-12-Data.db
keyspace1-standard1-ka-12-Index.db
5. run stress read:
./scylla-tools-java/tools/bin/cassandra-stress read n=1000000 -node 127.0.0.1 -port jmx=9042 -pop seq=0..1000000
6. scylla process crashed

from scylla log:
INFO  2017-06-27 17:05:53,614 [shard 0] compaction - Compacting [/home/larisau/.ccm/scylla-corrupt/node1/data/keyspace1/standard1-948e67705b3e11e78ff6000000000000/keyspace1-standard1-ka-30-Data.db:level=0, /home/larisau/.ccm/scylla-corrupt/node1/data/keyspace1/standard1-948e67705b3e11e78ff6000000000000/keyspace1-standard1-ka-12-Data.db:level=0, /home/larisau/.ccm/scylla-corrupt/node1/data/keyspace1/standard1-948e67705b3e11e78ff6000000000000/keyspace1-standard1-ka-13-Data.db:level=0, /home/larisau/.ccm/scylla-corrupt/node1/data/keyspace1/standard1-948e67705b3e11e78ff6000000000000/keyspace1-standard1-ka-29-Data.db:level=0, /home/larisau/.ccm/scylla-corrupt/node1/data/keyspace1/standard1-948e67705b3e11e78ff6000000000000/keyspace1-standard1-ka-14-Data.db:level=0, /home/larisau/.ccm/scylla-corrupt/node1/data/keyspace1/standard1-948e67705b3e11e78ff6000000000000/keyspace1-standard1-ka-18-Data.db:level=0, /home/larisau/.ccm/scylla-corrupt/node1/data/keyspace1/standard1-948e67705b3e11e78ff6000000000000/keyspace1-standard1-ka-16-Data.db:level=0, /home/larisau/.ccm/scylla-corrupt/node1/data/keyspace1/standard1-948e67705b3e11e78ff6000000000000/keyspace1-standard1-ka-22-Data.db:level=0, /home/larisau/.ccm/scylla-corrupt/node1/data/keyspace1/standard1-948e67705b3e11e78ff6000000000000/keyspace1-standard1-ka-26-Data.db:level=0, /home/larisau/.ccm/scylla-corrupt/node1/data/keyspace1/standard1-948e67705b3e11e78ff6000000000000/keyspace1-standard1-ka-24-Data.db:level=0, /home/larisau/.ccm/scylla-corrupt/node1/data/keyspace1/standard1-948e67705b3e11e78ff6000000000000/keyspace1-standard1-ka-11-Data.db:level=0, /home/larisau/.ccm/scylla-corrupt/node1/data/keyspace1/standard1-948e67705b3e11e78ff6000000000000/keyspace1-standard1-ka-20-Data.db:level=0, /home/larisau/.ccm/scylla-corrupt/node1/data/keyspace1/standard1-948e67705b3e11e78ff6000000000000/keyspace1-standard1-ka-28-Data.db:level=0, ]
ERROR 2017-06-27 17:05:57,884 [shard 0] compaction_manager - compaction failed: marshal_exception (marshalling error)
INFO  2017-06-27 17:05:57,884 [shard 0] compaction_manager - compaction task handler sleeping for 160 seconds
ERROR 2017-06-27 17:06:02,845 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: std::bad_alloc
ERROR 2017-06-27 17:06:02,850 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: std::bad_alloc
ERROR 2017-06-27 17:06:02,854 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: std::bad_alloc
ERROR 2017-06-27 17:06:02,860 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: std::bad_alloc
ERROR 2017-06-27 17:06:02,861 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: std::bad_alloc
ERROR 2017-06-27 17:06:02,861 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: std::bad_alloc
ERROR 2017-06-27 17:06:02,863 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: std::bad_alloc
ERROR 2017-06-27 17:06:02,865 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: std::bad_alloc
ERROR 2017-06-27 17:06:02,871 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: std::bad_alloc
ERROR 2017-06-27 17:06:02,872 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: std::bad_alloc
ERROR 2017-06-27 17:06:02,877 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: std::bad_alloc
ERROR 2017-06-27 17:06:02,878 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: std::bad_alloc
ERROR 2017-06-27 17:06:02,878 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: std::bad_alloc
ERROR 2017-06-27 17:06:02,879 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: std::bad_alloc
WARN  2017-06-27 17:06:02,894 [shard 0] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace: 0x499943, 0x4999a1, 0xa8449f, 0xab9bfa, 0xabdcc7, 0xabe496, 0xabe8bb, 0xaa6073, 0x845b8c, 0x89f47c, 0x89f9fd, 0x982691, 0x985eff, 0x9864c8, 0x98b922, 0x98f547, 0x8fdf36, 0x982691, 0x985eff, 0x9864c8, 0x96a370, 0x96aa3c, 0x951dc4, 0x72735c, 0x78d8a1, 0x79c545, 0x89bd68, 0x4f925c, 0x496599, 0x4e92ea, 0x56da24, 0x421eae, 0x7f900c90c400, 0x4925e9
scylla: sstables/index_reader.hh:270: sstables::index_reader::advance_to_page(uint64_t)::<lambda(sstables::shared_index_lists::list_ptr)>: Assertion `!_current_list->empty()' failed.
Aborting on shard 0.
Backtrace:
  0x0000000000498738
  0x0000000000498855
  0x0000000000498903
  0x00007f900ccc35af
  0x00007f900c9218de
  0x00007f900c9234d9
................

**Comment by avikivity** [comment]
@larisau please mention the version number (full package name) and provide the whole backtrace so we can decode it.

**Comment by larisau** [comment]
[scylla-corrupt-sstables.tar.gz](https://github.com/scylladb/scylla/files/1105631/scylla-corrupt-sstables.tar.gz)

**Comment by larisau** [comment]
[system_log.txt](https://github.com/scylladb/scylla/files/1105644/system_log.txt)

**Comment by larisau** [comment]
running scylla master compiled 26.06

**Comment by avikivity** [comment]
Oh, then we can't decode it ourselves. Please decode the backtrace using

    addr2line -fCe /path/to/scylla 0x0000000000498738 0x0000000000498855 ...

**Comment by tgrabiec** [comment]
That assert should be turned into exception complaining about corrupted index.

**Comment by larisau** [comment]
seastar::backtrace_buffer::append_backtrace()
/home/larisau/dev/scylla/seastar/core/reactor.cc:277
seastar::print_with_backtrace(char const*)
/home/larisau/dev/scylla/seastar/core/reactor.cc:295
sigabrt_action
/home/larisau/dev/scylla/seastar/core/reactor.cc:3512
??
??:0
??
??:0
??
??:0
??
??:0
??
??:0
sstables::index_reader::advance_to_page(unsigned long)::{lambda(sstables::shared_index_lists::list_ptr)#2}::operator()(sstables::shared_index_lists::list_ptr) const
/home/larisau/dev/scylla/sstables/index_reader.hh:270 (discriminator 1)
seastar::apply_helper<sstables::index_reader::advance_to_page(unsigned long)::{lambda(sstables::shared_index_lists::list_ptr)#2}, std::tuple<sstables::shared_index_lists::list_ptr>&&, std::integer_sequence<unsigned long, 0ul> >::apply({lambda(sstables::shared_index_lists::list_ptr)#2}&&, std::tuple<sstables::shared_index_lists::list_ptr>)
/home/larisau/dev/scylla/seastar/core/apply.hh:36
sstables::index_reader::advance_to_page(unsigned long)
/home/larisau/dev/scylla/sstables/index_reader.hh:282
sstables::index_reader::advance_to(dht::ring_position_view)
/home/larisau/dev/scylla/sstables/index_reader.hh:573
sstables::index_reader::advance_to_end(nonwrapping_range<dht::ring_position> const&)
/home/larisau/dev/scylla/sstables/index_reader.hh:296
std::_Function_handler<seastar::future<seastar::lw_shared_ptr<sstables::sstable_data_source> > (), sstables::mutation_reader::impl::impl(seastar::lw_shared_ptr<sstables::sstable>, seastar::lw_shared_ptr<schema const>, nonwrapping_range<dht::ring_position> const&, query::partition_slice const&, seastar::io_priority_class const&, seastar::bool_class<streamed_mutation::forwarding_tag>, seastar::bool_class<mutation_reader::forwarding_tag>)::{lambda()#1}>::_M_invoke(std::_Any_data const&)
/usr/include/c++/6.3.1/functional:1717
std::function<seastar::future<seastar::lw_shared_ptr<sstables::sstable_data_source> > ()>::operator()() const
/usr/include/c++/6.3.1/functional:2127
sstable_range_wrapping_reader::operator()()
/home/larisau/dev/scylla/sstable_mutation_readers.hh:43
mutation_reader::operator()()
/home/larisau/dev/scylla/mutation_reader.hh:89
filtering_reader<bool (&)(streamed_mutation const&)>::operator()()
/home/larisau/dev/scylla/mutation_reader.hh:222
mutation_reader::operator()()
/home/larisau/dev/scylla/mutation_reader.hh:89
combined_mutation_reader::next()
/home/larisau/dev/scylla/mutation_reader.cc:53
combined_mutation_reader::operator()()
/home/larisau/dev/scylla/mutation_reader.cc:123
mutation_reader::operator()()
/home/larisau/dev/scylla/mutation_reader.hh:89
restricting_mutation_reader::operator()()
/home/larisau/dev/scylla/mutation_reader.cc:261
mutation_reader::operator()()
/home/larisau/dev/scylla/mutation_reader.hh:89
mutation_reader::operator()()
/home/larisau/dev/scylla/mutation_reader.hh:89
combined_mutation_reader::next()
/home/larisau/dev/scylla/mutation_reader.cc:53
combined_mutation_reader::operator()()
/home/larisau/dev/scylla/mutation_reader.cc:123
mutation_reader::operator()()
/home/larisau/dev/scylla/mutation_reader.hh:89
_ZZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows1E20query_result_builderEEEDa15mutation_readerOT_bENKUlRS7_RT0_RT1_E_clIS6_S5_NSt12experimental15fundamentals_v18optionalI17streamed_mutationEEEEDaS9_SB_SD_
/home/larisau/dev/scylla/mutation_reader.hh:403
data_query(seastar::lw_shared_ptr<schema const>, mutation_source const&, nonwrapping_range<dht::ring_position> const&, query::partition_slice const&, unsigned int, unsigned int, std::chrono::time_point<gc_clock, std::chrono::duration<int, std::ratio<1l, 1l> > >, query::result::builder&, seastar::lw_shared_ptr<tracing::trace_state>)
/home/larisau/dev/scylla/mutation_partition.cc:1914
column_family::query(seastar::lw_shared_ptr<schema const>, query::read_command const&, query::result_request, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > > const&, seastar::lw_shared_ptr<tracing::trace_state>, query::result_memory_limiter&, unsigned long)::{lambda(query::result_memory_accounter)#1}::operator()(query::result_memory_accounter)::{lambda()#1}::operator()() const
/home/larisau/dev/scylla/database.cc:2773
do_until_continued<column_family::query(schema_ptr, const query::read_command&, query::result_request, const partition_range_vector&, tracing::trace_state_ptr, query::result_memory_limiter&, uint64_t)::<lambda(query::result_memory_accounter)> mutable::<lambda()>, std::_Bind<std::_Mem_fn<bool (query_state::*)() const>(query_state*)> >
/home/larisau/dev/scylla/seastar/core/future-util.hh:155
then<column_family::query(schema_ptr, const query::read_command&, query::result_request, const partition_range_vector&, tracing::trace_state_ptr, query::result_memory_limiter&, uint64_t)::<lambda(query::result_memory_accounter)> >
/home/larisau/dev/scylla/./seastar/core/future.hh:890
seastar::future<seastar::lw_shared_ptr<query::result> > std::__invoke_impl<seastar::future<seastar::lw_shared_ptr<query::result> >, seastar::future<seastar::lw_shared_ptr<query::result> > (column_family::* const&)(seastar::lw_shared_ptr<schema const>, query::read_command const&, query::result_request, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > > const&, seastar::lw_shared_ptr<tracing::trace_state>, query::result_memory_limiter&, unsigned long), column_family*, seastar::lw_shared_ptr<schema const>, query::read_command const&, query::result_request, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > > const&, seastar::lw_shared_ptr<tracing::trace_state>, query::result_memory_limiter&, unsigned long>(std::__invoke_memfun_deref, seastar::future<seastar::lw_shared_ptr<query::result> > (column_family::* const&)(seastar::lw_shared_ptr<schema const>, query::read_command const&, query::result_request, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > > const&, seastar::lw_shared_ptr<tracing::trace_state>, query::result_memory_limiter&, unsigned long), column_family*&&, seastar::lw_shared_ptr<schema const>&&, query::read_command const&, query::result_request&&, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > > const&, seastar::lw_shared_ptr<tracing::trace_state>&&, query::result_memory_limiter&, unsigned long&&)
/usr/include/c++/6.3.1/functional:227
seastar::execution_stage::flush()::{lambda()#1}::operator()() const
/home/larisau/dev/scylla/seastar/core/execution_stage.hh:161
seastar::reactor::run_tasks(seastar::circular_buffer<std::unique_ptr<seastar::task, std::default_delete<seastar::task> >, std::allocator<std::unique_ptr<seastar::task, std::default_delete<seastar::task> > > >&)
/home/larisau/dev/scylla/seastar/core/reactor.cc:2316
seastar::reactor::run()
/home/larisau/dev/scylla/seastar/core/reactor.cc:2774
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&)
/home/larisau/dev/scylla/seastar/core/app-template.cc:142
main
/home/larisau/dev/scylla/main.cc:677
??
??:0
_start
??:?

**Comment by espindola** [comment]
I will take a look

**Comment by avikivity** [comment]
Fixed by 684fb607c4190f1a040f55b2fbbb40513e5decf4.

@espindola please follow the github format for autoclosing fixes.
