### ISSUE TITLE
Headless offline installer

### ISSUE THREAD

**Issue by siculars** [scylladb/scylla#2533]
The offline installer dumps into the interactive setup script.

-How do you run this headless?
-How do you pass flags to the setup script?
-How do you pass a config file to the setup script?

Use case: orchestrated multi-node cluster install.

https://github.com/scylladb/scylla/wiki/Offline-Installer

**Comment by dorlaor** [comment]
@siculars please go and dive deeper and come up with data/changes to make it happen.
Haven't you opened another github issue for it before?
