### ISSUE TITLE
Empty cache continuity

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2536]
When initializing the row cache, if there are no sstables (new table or a node boots with no data), then we should set the partition continuity flag (and clear it on full cache invalidate).

**Comment by tgrabiec** [comment]
Invalidation already clears continuity properly, so there's nothing to do on that front.

attaching sstables (during boot as well) is supposed to invalidate appropriate ranges. 

So we could just pass a flag to cache's constructor in column_family indicating that the underlying mutation source is empty.
