### ISSUE TITLE
Add script to install Scylla dependencies

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#2543]
Just like Seastar has `install-dependencies.sh`, so should Scylla have an equivalent multi-platform script.

**Comment by avikivity** [comment]
Makes sense to wait for @syuu1228's ppas, so it will work on non-Fedora.

**Comment by duarten** [comment]
Done by 06b7ec6901f18cfcf57610e29cf610021622c39e.

**Comment by avikivity** [comment]
Still not fully working for Ubuntu/debian/centos.

**Comment by duarten** [comment]
Oops, sorry, thought there was a specific issue for the ppas.

**Comment by avikivity** [comment]
We won't support ppas. So Ubuntu users will have to manually install dependencies or use dbuild.
