### ISSUE TITLE
order-by doesn't work with IN

### ISSUE THREAD

**Issue by abvgedeika** [scylladb/scylla#2548]
seems like we don't track this case

*Installation details*
Scylla version (or git commit hash): https://github.com/scylladb/scylla/commit/d177ec05cb0c5a451a1a5b93646d3a35d2a6cc0b

steps:
1)CREATE TABLE test(
                  my_id varchar,
                  col1 int,
                  value varchar,
                  PRIMARY KEY (my_id, col1))
2) INSERT INTO test(my_id, col1, value) VALUES ( 'key1', 1, 'a')
INSERT INTO test(my_id, col1, value) VALUES ( 'key2', 3, 'c')
INSERT INTO test(my_id, col1, value) VALUES ( 'key3', 2, 'b')
3) query with ORDER BY and IN
SELECT col1 FROM test WHERE my_id in('key1', 'key2', 'key3') ORDER BY col1

[Invalid query] message="Cannot page queries with both ORDER BY and a IN restriction on the partition key; you must either remove the ORDER BY or the IN and sort client side, or disable paging for this query"

**Comment by gleb-cloudius** [comment]
Does it work with Cassandra? Seams like they have the same check.

--
			Gleb.

**Comment by duarten** [comment]
According to the [docs](http://docs.datastax.com/en/dse/5.1/cql/cql/cql_using/useQueryIN.html?hl=order), it shouldn't work.

**Comment by avikivity** [comment]
Note that RDBMSs handle this by buffering the data in a temporary table and sorting it before streaming it to the client.

**Comment by abvgedeika** [comment]
https://issues.apache.org/jira/browse/CASSANDRA-4327

**Comment by gleb-cloudius** [comment]
On Wed, Jul 05, 2017 at 08:39:47AM +0000, Andrei wrote:
> https://issues.apache.org/jira/browse/CASSANDRA-4327
> 
This is some other problem. Try to disabling paging and retry.

--
			Gleb.

**Comment by abvgedeika** [comment]
@gleb-cloudius you are right. with disabling paging ORDER BY with IN works properly. I've updated my tests. the issue is closed
