### ISSUE TITLE
Schema migration from 1.7 to 2.0 writes to system tables before commitlog replay

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2551]
*Installation details*
Scylla version (or git commit hash): master

May cause assertion failure during memtable sealing after replay (#2074).

May also result in migration working on stale schema tables if there are some updates in the commitlog. 

Migration cannot be moved after the replay, because user tables must be already set up at that point.

The simplest solution seems to be to refuse to boot on upgrade in case commitlog is unclean.

**Comment by tgrabiec** [comment]
@avikivity @tzach @elcallio Do you think it's fine to refuse to boot with an unclean commit log in this case?

**Comment by tzach** [comment]
Yes. The upgrade procedure, for example, [1.6 to 1.7](http://docs.scylladb.com/upgrade/upgrade-guide-from-1.6-to-1.7-rpm/)  require draining the node.

Having say that, we need to validate:
- a clear error message
- by pass procedure in case there is (for any reason) a commit log

A valid by pass can be: restart Scylla with the older version, drain, and try again.

**Comment by avikivity** [comment]
That can be pretty hard, since you need to downgrade the installed packages.

**Comment by tzach** [comment]
> That can be pretty hard, since you need to downgrade the installed packages.

Agree, but it's a procedure we are validating anyway
http://docs.scylladb.com/upgrade/upgrade-guide-from-1.6-to-1.7-rpm/#rollback-procedure

There might be easier solutions

**Comment by slivne** [comment]
@avikivity @tzach we need to decide on this - to have the code committed for 2.0 - although its not simple - refusing to boot in case of having old schema and having commitlog seems to be reasonable in my view. The only complication is that 47b1e3941064349e3a4e650e481ba0ca12f48354 exists only in 1.7.3 - so users will need to upgrade after upgrading to 1.7.3+ release (or else they may have commitlogs still existing even though they shouldn't)

**Comment by elcallio** [comment]
I vote yes. Disallowing (major) upgrading a potentially broken node (unclean commitlog indicates a crash) is very reasonable.

**Comment by slivne** [comment]
@syuu1228 can you please add this validation to the pre-inst step - e.g. if there are commitlogs files (need to find the location  from config if there is one) than fail upgrade and tell the user that he may need to upgarde to 1.7.3 (or later) and make sure commitlogs do not exist prior to upgrade.

**Comment by gleb-cloudius** [comment]
People usually upgrade rpm before stopping Scylla process, so commitlog files are expected to be there.

**Comment by slivne** [comment]
not according to our procedures

http://docs.scylladb.com/upgrade/upgrade-guide-from-1.6-to-1.7-ubuntu/

http://docs.scylladb.com/upgrade/upgrade-guide-from-1.6-to-1.7-rpm/

**Comment by slivne** [comment]
reopen - we need the debian fix as well
