### ISSUE TITLE
Add a systemd alternative logging option

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#2552]
Some users cannot change even tiny bit of systemd and thus cannot consume
our logging. Even they cannot configure systemd to log to a file.

Need to add a Scylla self contained option for logging which won't be the default.

**Comment by slivne** [comment]
copying an answer from @avikivity on internal mailing list

> run `systemctl edit scylla.service`
> 
> 
> [Service]
> 
> StandardOutput=syslog
> StandardError=syslog
> SyslogIdentifier=scylla
> 
> 
> Install the syslog-ng package, and configure it to log to a file. It requires root, but not changing systemd logging.

@dorlaor is this what you are after - does that suffice

**Comment by tzach** [comment]
Closing as @avikivity provides a valid solution. I added a scylla-doc ticket to document this solution.
@dorlaor please reopen if this does not work for you.
