### ISSUE TITLE
Get rid of sstable atomic deletion

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2560]
Now that we reshard before compacting, we can get rid of sstable atomic deletion. We just need to make sure that we never compact or clean a shared sstable.

**Comment by slivne** [comment]
Is compaction waiting for all shards to finish resharding - or only for the
files that are relevant for it ?

**Comment by raphaelsc** [comment]
On Sun, Jul 9, 2017 at 10:46 AM, Shlomi Livne <notifications@github.com>
wrote:

> Is compaction waiting for all shards to finish resharding - or only for the
> files that are relevant for it ?


shared sstables are excluded from regular compaction, so it may happen that
resharding and regular compaction proceed in parallel.

**Comment by avikivity** [comment]
Yes, but it's not a problem.

**Comment by raphaelsc** [comment]
working on this, patches on mailing list, but need more testing. one of the really good benefits too is that boot will be made much faster given that we no longer need to consider all sstables in all shards.

**Comment by raphaelsc** [comment]
Can be closed @slivne

**Comment by slivne** [comment]
fixed by 432268f582a23badd20b283f143fa8f24a7f7567
