### ISSUE TITLE
Scylla docker: correctly handle --host parameter

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2561]
Scylla version (or git commit hash): 1.7.1 
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

Running scylla docker with --host option fails with the following error

```
seastar - Exiting on unhandled exception: std::system_error (error system:99, Cannot assign requested address)
```

**Comment by tzach** [comment]
On a second test `-h` or `--host` works find with a string hostname 
```
sudo docker run -h tzach --name some-scylla -d scylladb/scylla --memory=1G --smp=1
```

but Scylla fails with an IP like hostname
```
sudo docker run -h 1.2.3.4 --name some-scylla -d scylladb/scylla --memory=1G --smp=1
```

On both cases, the hostname is set correctly.

**Comment by slivne** [comment]
@tzach I think its because the ip you are providing is the incorrect one - so scylla is not able to bind to it -
 if I run with 127.0.0.1 it works 

```
sudo docker run -h 127.0.0.1 --name some-scylla -d scylladb/scylla --memory=1G --smp=1
```
