### ISSUE TITLE
cqlsh failes with timeout on 'DROP KEYSPACE' after resharding

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#2565]
Caught by resharding test on master built on July 10:
[https://github.com/scylladb/scylla-dtest/pull/474/files]

steps to reproduce:
1. create one-node cluster with murmur3_partitioner_ignore_msb_bits=0
2. run cassandra stress write (n=1000000)
3. re-start node with murmur3_partitioner_ignore_msb_bits': 12
4. wait for resharding finish
5. run cassandra stress read
6. DROP KEYSPACE

It seems that the keyspace is dropped, but cqlsh returns with timeout.

**Comment by tgrabiec** [comment]
Maybe same as https://github.com/scylladb/scylla/issues/1913 ?
