### ISSUE TITLE
IN still doesn't support 'wide rows' in SELECT statement: [Invalid query] "Clustering column "c2" cannot be restricted by an IN relation"

### ISSUE THREAD

**Issue by abvgedeika** [scylladb/scylla#2566]
*Installation details*
Scylla version (or git commit hash): https://github.com/scylladb/scylla/commit/d177ec05cb0c5a451a1a5b93646d3a35d2a6cc0b

we already have the test but it still uses old conduct

test: in_clause_wide_rows_test
https://github.com/scylladb/scylla-dtest/blob/master/cql_additional_tests.py#L789-L807

```
        # composites
        session.execute("""
            CREATE TABLE test2 (
                k int,
                c1 int,
                c2 int,
                v int,
                PRIMARY KEY (k, c1, c2)
            ) WITH COMPACT STORAGE;
        """)

        # Inserts
        for x in range(0, 10):
            session.execute("INSERT INTO test2 (k, c1, c2, v) VALUES (0, 0, %i, %i)" % (x, x))

        # Check first we don't allow IN everywhere
        if self.cluster.version() >= '2.2':  # FIXME: Scylla reports 2.2, but has 2.1 behavior.
            assert_none(session, "SELECT v FROM test2 WHERE k = 0 AND c1 IN (5, 2, 8) AND c2 = 3")
        else:
            assert_invalid(session, "SELECT v FROM test2 WHERE k = 0 AND c1 IN (5, 2, 8) AND c2 = 3")
```

**SELECT v FROM test2 WHERE k = 0 AND c1 IN (5, 2, 8) AND c2 = 3**

actual result:
InvalidRequest: Error from server: code=2200 [Invalid query] message="Clustering column "c2" cannot be restricted by an IN relation"

 expected behaviour for current 3.0 version:
empty list []

**Comment by slivne** [comment]
#1437

**Comment by slivne** [comment]
this is working on 3.0.rc1 (3.0.rc1-0.20181031.0f3a21f0b)
