### ISSUE TITLE
Cache prevents compacted sstables from being removed on disk until next memtable flush

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2570]
*Installation details*
Scylla version (or git commit hash): 2.0, master

Since 8ba6366610b98b70351d3669f530be951d140d35, cache keeps the current snapshot of the underlying mutation source (sstables). That snapshot will prevent sstables present in the `sstable_list` held by the snapshot from being removed. See c82c6ec6ed8e76fc6af7b62fe0f708ff5737bb25:

```
snapshot_source
column_family::sstables_as_snapshot_source() {
    return snapshot_source([this] () {
        // FIXME: Will keep sstables on disk until next memtable flush. Make compaction force cache refresh.
```

So those sstables may be left on disk until next memtable flush, which updates the cache and switches it to the current sstable list.

The fix would be to make compaction replace compacted sstables in the `sstable_list` held by the snapshot with the sstables which are the result of compaction, like it does for the main `sstable_list`.

Refs #2563.

**Comment by tomer-sandler** [comment]
Shouldn't we add here the repro Shlomi did and the other details from #2563 that I added?
Also, I see you refer to snapshots, but this happen on a system with no snapshots whatsoever...

**Comment by tgrabiec** [comment]
2017-07-12 9:22 GMT+02:00 tomer-sandler <notifications@github.com>:

> Shouldn't we add here the repro Shlomi did and the other details from
> #2563 <https://github.com/scylladb/scylla/issues/2563> that I added?
>
This can be reproduced in a simpler way. I don't think more details are
necessary to understand this issue, and #2563 is linked. I am still not
sure it is caused by this, since you said that flush didn't help.

> Also, I see you refer to snapshots, but this happen on a system with no
> snapshots whatsoever...
>

You're probably referring to "nodetool snapshot"? I was referring to a
different kind of snapshots. We do in-memory snapshots all the time.
