### ISSUE TITLE
make scylla resilient to sstable corruption

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#2606]
Scylla should be able to recover from a scenario in which one or more sstables are corrupted without any downtime. At the moment, a single corrupted sstable will prevent compaction from making progress. To fix it, sysadmin needs to remove bad sstables manually (error prone) and restart node (downtime). I suggested filtering out corrupted sstables from internal activities such that the problem can be fixed without downtime and @glommer suggested repairing *only affected* ranges automatically (so no sysadmin intervention). It would be nice to move corrupted tables instead of deleting them because it will still allow us to investigate the root of the issue.
World isn't perfect, corruption happens, so it's better if scylla takes action when it happens.

**Comment by avikivity** [comment]
Removing an sstable is dangerous, it can cause bad data to be served (if we remove an sstable with a tombstone, it may resurrect dead data). Better to stop the node.

**Comment by raphaelsc** [comment]
@avikivity My idea is to only filter it out from activities such as compaction (allows it to make progress), not remove it from sstable set. If tombstone is corrupted in a sstable, shadowed data is resurrected until repair for its range completes.
But stopping the node right away prevents resurrection... 

If we're going to stop the node, we expect user to remove corrupted table(s), put the node back on and issue repair. I think we can do it for the user. We can do a finer-grained repair because we know the exact ranges that need repair. It would also require pausing transportation services and resuming them when repair completes to prevent resurrection.

**Comment by avikivity** [comment]
The user can choose to restore from backup and run repair.

**Comment by glommer** [comment]
If we have run a repair automatically in every key that is contained in
that sstable - and it suceeded, I don't understand what is the risk in
moving it out of the way.

**Comment by avikivity** [comment]
Before the repair is run, you are serving corrupted data.

There is a bigger issue here, when something like corruption happens you can't assume that these things just happen and move on. Is it a bug that is causing Scylla to corrupt data? Then it will eat all the sstables and you will be left with nothing. Is it bad hardware? The operator needs to know when it happens.

Automation is great for the common case but is really bad for the uncommon case, because we can't anticipate everything.

**Comment by glommer** [comment]
@avikivity how exactly it is that we serve corrupted data? The whole assumption here is that we can identify the bad sstable - enough to stop the node. If we can do that, we can just as easily isolate it and stop serving data from it.

**Comment by avikivity** [comment]
From my first comment:

> Removing an sstable is dangerous, it can cause bad data to be served (if we remove an sstable with a tombstone, it may resurrect dead data)
