### ISSUE TITLE
take occupancy into account when deciding to flush a memtable

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#261]
Right now we flush a memtable when its region reaches 11% of total allowed dirty memory (itself 50% of total memory).  But due to overwrites, the occupancy of this region may be low.  So we can take occupancy into account, relying on compaction to free this memory later.

Low priority since compaction will usually keep occupancy high.

**Comment by slivne** [comment]
@avikivity do we need this for GA ?

**Comment by avikivity** [comment]
No.

**Comment by slivne** [comment]
@avikivity , @glommer - glommer's work in 1.5 changed all of this - can I close this issue

**Comment by glommer** [comment]
yes you can
