### ISSUE TITLE
scylla_raid_setup script: syntax error 

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2610]
*Installation details*
Scylla version (or git commit hash): 2.0.rc0-0.20170712.a371b8a
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0c84881a

/usr/lib/scylla/scylla_raid_setup: line 132: syntax error 
near unexpected token `fi'

lack of 'then'

```
130 if is_debian_variant;
131     update-initramfs -u
132 fi
```

@syuu1228

**Comment by amoskong** [comment]
Posted a fix to scylla-dev maillist:
[PATCH scylla] scylla_raid_setup: fix syntax error

**Comment by syuu1228** [comment]
Ahh.. sorry. Thanks for the patch.
