### ISSUE TITLE
i3.16xlarge: network interrupts have repeated smp affinity

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2611]
*Installation details*
Scylla version (or git commit hash):  2.0.rc0-0.20170703.a619b97
Cluster size:1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-ae7370b8

Expected result: the smp affinity of different network interrupts should be different

```
Running 'cat /etc/scylla.d/io.conf |grep -v \#'
[stdout] SEASTAR_IO="--num-io-queues 63 --max-io-requests 1536"

Running 'cat /etc/scylla.d/cpuset.conf |grep -v \#'
[stdout] CPUSET="--cpuset 1-63 "

Running 'cat /proc/interrupts |grep eth'
[stdout]  683:       6374          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  xen-pirq-msi-x     eth0-Tx-Rx-0
[stdout]  684:       6135          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  xen-pirq-msi-x     eth0-Tx-Rx-1
[stdout]  685:       6516          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  xen-pirq-msi-x     eth0-Tx-Rx-2
[stdout]  686:       1583          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  xen-pirq-msi-x     eth0-Tx-Rx-3
[stdout]  687:       9256          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  xen-pirq-msi-x     eth0-Tx-Rx-4
[stdout]  688:      12734          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  xen-pirq-msi-x     eth0-Tx-Rx-5
[stdout]  689:      12925          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  xen-pirq-msi-x     eth0-Tx-Rx-6
[stdout]  690:       5705          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0          0  xen-pirq-msi-x     eth0-Tx-Rx-7
Running 'cat /proc/irq/683/smp_affinity'
[stdout] 00000000,00000000,00000000,00000001

Running 'cat /proc/irq/684/smp_affinity'
[stdout] 00000000,00000000,00000000,00000001
...
...
Running 'cat /proc/irq/690/smp_affinity'
[stdout] 00000000,00000000,00000000,00000001
```

**Comment by glommer** [comment]
Why do you think the affinities should be different?

They are all routed to CPU 0 because there are not enough interrupts for decent multi-queue.

**Comment by amoskong** [comment]
For the i3.4xlarge and i3.8xlarge cases, we still don't have enough interrupts, but the affinities are different.

Instance Type | Ena Driver | io.conf | cpuset.conf | Net Interrupts | smp_affinity | Boot (service is up) | C-s testing
-- | -- | -- | -- | -- | -- | -- | --
i3.large | Good | SEASTAR_IO="--num-io-queues 2 --max-io-requests 192" | CPUSET="--cpuset 0-1 " | 2 | net interrupts have different affinity | Good | Good
i3.xlarge | Good | SEASTAR_IO="--num-io-queues 4 --max-io-requests 192" | CPUSET="--cpuset 0-3 " | 4 | net interrupts have different affinity | Good | Good
i3.2xlarge | Good | SEASTAR_IO="--num-io-queues 8 --max-io-requests 192" | CPUSET="--cpuset 0-7 " | 8 | net interrupts have different affinity | Good | Good
i3.4xlarge | Good | SEASTAR_IO="--num-io-queues 16 --max-io-requests 384" | CPUSET="--cpuset 0-15 " | 8 | net interrupts have different affinity | Good | Good
i3.8xlarge | Good | SEASTAR_IO="--num-io-queues 32 --max-io-requests 768" | CPUSET="--cpuset 0-31 " | 8 | net interrupts have different affinity | Good | Good
i3.16xlarge | Good | SEASTAR_IO="--num-io-queues 63 --max-io-requests 1536" | CPUSET="--cpuset 1-63 " | 8 | all net interrupts have same affinity "00000000,00000000,00000000,00000001" | Good | Good

**Comment by glommer** [comment]
More likely the others are wrong.

**Comment by glommer** [comment]
@amoskong that is 2.0, right?

@vladzcloudius you might want to take a look at those results.

**Comment by amoskong** [comment]
yes, ami-ae7370b8 (2.0.rc0-0.20170703.a619b97)

**Comment by vladzcloudius** [comment]
@glommer @amoskong The configuration looks correct.
The number of HTs on the i3.8xlarge (I guess that's the only one in question above, isn't it?) is 32 (16 physical cores) and we have 8 NICs Rx queues.

We would select a non-MQ mode when the ratio of cores/queue > 4. 
For i3.8xlarge it's exactly 4 therefore we still auto-select the MQ mode.

For i3.16xlarge the ratio for HTs is 64/8 > 4 and for physical cores 32/8 == 4 therefore we select the non-split sq mode.

**Comment by glommer** [comment]
Based on what I saw recently, I am starting to question if our current heuristics really are sane. What vlad describe is what we currently do - but I think it would be nice to get some numbers from those instances (4x and 8x) to back that up.

@slivne

**Comment by vladzcloudius** [comment]
I've opened a corresponding issue in the `seastar` github project: https://github.com/scylladb/seastar/issues/308

**Comment by slivne** [comment]
@vladzcloudius - can you please validate the settings are ok (I am sure @glommer will be happy to answer questions on how todo that).

one other thing we had questions about is disk interrupts - are they spread / all directed to the same core - does it really matter on these instances

**Comment by slivne** [comment]
@glommer I need a bit more info on how you want that tested on the 2.0 branch.

single node vs 3 node cluster
# of cassandra-stress / command if you have that info available (it can be similar to what you ran lately with cassandra-stress-and-deploy - if you can provide the info, it will make the cycles shorter)

**Comment by nyh** [comment]
@vladzcloudius I'm not sure I understood the exact numbers, but if I understood correctly what you said above, when we have 64 hyperthreads and only 8 receive queues (64/8 > 4), we use a single queue and a single hyperthread is removed to handle its interrupts.
Is that really the best option?
In this case, what if we removed *8* hyperthreads, and each one would handle interrupts for 7 other hyperthreads?
We'll have fewer hyperthreads to run our code, but the network stack will be much more scalable.

**Comment by vladzcloudius** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    
    
    On 07/24/2017 08:16 AM, nyh wrote:
    
    
      @vladzcloudius I'm not sure I
        understood the exact numbers, but if I understood correctly what
        you said above, when we have 64 hyperthreads and only 8 receive
        queues (64/8 > 4), we use a single queue and a single
        hyperthread is removed to handle its interrupts.
    
    
    
    @nyh Not exactly - we will bind all 8 queues to the same
      hyperthtead (CPU0) and will take CPU0 out of scylla CPUs. This
      would work as if the NIC has a single queue and it's
      bound to CPU0 - thus the name of the mode - SQ.
    
    
    
    
      
        Is that really the best option?
        In this case, what if we removed 8 hyperthreads, and
        each one would handle interrupts for 7 other hyperthreads?
        We'll have fewer hyperthreads to run our code, but the network
        stack will be much more scalable.
    
    
    
    I doubt that would be a good configuration.
    
    
      Making scylla running on 7 shard less is a serious performance
        impact.
      So far handling all scylla's networking traffic (10Gbps media)
        wasn't able to saturate a single hyperthread completely (as far
        as we know), therefore having 8 HTs making the same work would
        be a tremendous waste of CPU power.
      RFS has proven to distribute the networking a lot better than
        RSS (or RPS) therefore as long as IRQs' handling doesn't become
        a bottleneck the setup above is supposed to deliver the best
        results and this is what we saw in our testings so far.
      
    
    
    
    
    
    
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/scylladb/scylla","title":"scylladb/scylla","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/scylladb/scylla"}},"updates":{"snippets":[{"icon":"PERSON","message":"@nyh in #2611: @vladzcloudius I'm not sure I understood the exact numbers, but if I understood correctly what you said above, when we have 64 hyperthreads and only 8 receive queues (64/8 \u003e 4), we use a single queue and a single hyperthread is removed to handle its interrupts.\r\nIs that really the best option?\r\nIn this case, what if we removed *8* hyperthreads, and each one would handle interrupts for 7 other hyperthreads?\r\nWe'll have fewer hyperthreads to run our code, but the network stack will be much more scalable."}],"action":{"name":"View Issue","url":"https://github.com/scylladb/scylla/issues/2611#issuecomment-317403990"}}}

**Comment by glommer** [comment]
@slivne single node should be enough for this. What we want is to start a pattern that will generate as much network load as possible (measured in packets/sec). So just bombarding those machines with a write load with small partitions should do the trick.

Then we need to compare the results of the various options available.

When running -mq we should run Scylla on all CPUs. When running the sq modes we should adjust cpuset accordingly.

**Comment by glommer** [comment]
@vladzcloudius Please see the attached graph.

Run in the left is mq, when I noticed it was really bad I stopped it. Run in the right is -sq. Payloads are 1kB in size, other than that it is a simple RF=3 write test.

Load is the same and instance is i3.2xlarge - where queues should be more than enough.
![vlad](https://user-images.githubusercontent.com/331197/28641117-05bc239e-721c-11e7-81ce-1b121b709cf5.png)

*PLEASE* let's investigate this in time for a good 2.0 release. I agree in principle that mq should work for those machines, but there's something wrong here. I suspect (but haven't looked that closely yet) that the ENA driver does some polling, which could be harmful for us.

In general, I see in this load peaks of almost 20 % sysirq time in the Scylla CPUs - for a load that delivers 200 packet/s per node. I am starting to question whether we should ever be configuring anything in mq mode, at least for i3.

**Comment by vladzcloudius** [comment]
@slivne Could you increase our quota on i3.4xlarge instances?  We seem to be limited by up to 2 such intances (i3.8xlarge limit is higher for instance).

**Comment by vladzcloudius** [comment]
Here are the [results](https://docs.google.com/a/cloudius-systems.com/spreadsheets/d/1NaWg_tY7coRAH_8on9gBN3YsKi9OBfha9-rpViaqVLI/edit?usp=sharing) of testing of i3.2xlarge and i3.8xlarge instances.
The tests were performed on a cluster of 3 Nodes with RF=3 with the scylla version 1.7.4.
READ queries were forced to be served from the disk (by restarting the scylla before each test).

We may see that even on the 2xlarge instances which have exactly the same amount of HTs and NIC HW queues there is no a clear advantage to the MQ mode: SQ is definitely better in a WRITE test while MQ is slightly better in a READ test.

With the bigger instances the SQ mode increases the gap in the WRITE test (14% in op rate and huge gains in latencies across the board). More that that, the same test configuration had a few write timeouts in MQ mode. 
The READ test in most aspects has better results in a SQ mode as well (there is some "glitch" in the 95th percentile).

However the READ test suffered from a serious load imbalance between the shards:

![image](https://user-images.githubusercontent.com/6103981/28733537-a4498206-73aa-11e7-9c5a-bb66da06bc14.png)

Although this imbalance was persistent both in an MQ and in a SQ modes on big instances we'd better retest this once we fix this.

*Conclusion*
It seems that except for the cases with <CPU num> == <NIC HW queues number> MQ is absolutely not justified.

*Proposal*
Implement the following heuristics: 
1) Don't allow SQ mode if it takes less than 25% of the compute power.
2) Prefer SQ-split, when (1) allows it.
3) Use MQ only when  <shards num>==<NIC HW queues num>.

**Comment by glommer** [comment]
@avikivity I, for one, am in agreement and would be like to hear from you.

What I think ends up happening in MQ mode if shard count != nr_queues is that the whole node will just start operating at the speed of the shards that are bashed with interrupts. We'd be better off with SQ/SQ-split as vlad's results show IMHO

**Comment by slivne** [comment]
@vladcloudius - in SQ mode did you allocate a dedicate core / ht for
interrupts - can you please clarify that.

**Comment by vladzcloudius** [comment]
@slivne A short answer is - only a single HT (CPU0).

In this particular testing I used a so called SQ mode which allocates only CPU0 for handling IRQs.
The is also a SQ-SPLIT mode that would allocate CPU0 and all its HT siblings for IRQs handling.

**Comment by glommer** [comment]
guys - any resolution here?

I am testing i3 again, and for machines like 8xlarge I do validate vlad's findings that SQ performs much better than MQ. I think we should enforce mq only if when nr_shards == nr_queues.

**Comment by amoskong** [comment]
Attached the new test result with `2.0.rc2-0.20170815.8370e1b`, I marked the difference to yellow (comparing with result of 2.0.rc0)

[i3 AMI test.xlsx](https://github.com/scylladb/scylla/files/1231964/i3.AMI.test.xlsx)

**Comment by slivne** [comment]
@amoskong thanks for sharing the info

@glommer , @vladzcloudius  please review the excel - if it looks ok - please comment and I'll close the issue

**Comment by glommer** [comment]
@vladzcloudius heuristics doc say: 
```
* Use MQ only when number HTs is less or equal than 4 or when number of Rx queues equals to the number of HTs.
```

But according to amos spreadsheet i3.2xlarge has 8 == 8 and still ends up in SQ.

Is that what you intended?

**Comment by vladzcloudius** [comment]
@amoskong Could you clarify, please, what "Good" status means? It would be easier to see some actual numbers in order to be able to actually compare the different configurations.

**Comment by amoskong** [comment]
@vladzcloudius 

The `Good` in Boot testing means: the scylla-server can startup without error
The `Good` in C*-stress testing means: c-s workload can be executed and finish without error

Which kind of information do you want to get except the content in result excel?

**Comment by vladzcloudius** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    
    
    On 08/24/2017 12:27 PM, Amos Kong
      wrote:
    
    
      @vladzcloudius
      The Good in Boot testing means: the scylla-server
        can startup without error
        The Good in C*-stress testing means: c-s workload
        can be executed and finish without error
    
    
    
    Got it. Thanks for the clarification.
    
    
    
    
      Which kind of information do you want to get except the content
        in result excel?
    
    
    
    I'd like to see the actual performance numbers.
    
    
    
    
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/scylladb/scylla","title":"scylladb/scylla","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/scylladb/scylla"}},"updates":{"snippets":[{"icon":"PERSON","message":"@amoskong in #2611: @vladzcloudius \r\n\r\nThe `Good` in Boot testing means: the scylla-server can startup without error\r\nThe `Good` in C*-stress testing means: c-s workload can be executed and finish without error\r\n\r\nWhich kind of information do you want to get except the content in result excel?"}],"action":{"name":"View Issue","url":"https://github.com/scylladb/scylla/issues/2611#issuecomment-324686808"}}}

**Comment by tzach** [comment]
@vladzcloudius @avi can we close this?

**Comment by vladzcloudius** [comment]
@tzach I think so.

**Comment by tzach** [comment]
Thanks, @vladzcloudius please share relevant commits
In particular, did all of the commits backported to 2.0?

**Comment by vladzcloudius** [comment]
@tzach "[COMMIT scylla-seastar branch-2.0] scripts: perftune.py: change the network module mode auto selection heuristic"

**Comment by tzach** [comment]
Thanks @vladzcloudius 
@amoskong please validate once rc3 is ready

**Comment by slivne** [comment]
@amoskong - rc3 is out - can you please do the retest - hopefully everything will be correct on rc3

**Comment by amoskong** [comment]
Test result: The yellow part is the difference with 2.0.rc2.

![image](https://user-images.githubusercontent.com/309708/30027498-dde191bc-91b3-11e7-90be-5913667564a3.png)

**Comment by slivne** [comment]
@gleb-cloudius / @vladzcloudius - so is RC4 setup correct ?

**Comment by vladzcloudius** [comment]
@slivne The networking settings are as expected.

**Comment by slivne** [comment]
haleluya
