### ISSUE TITLE
Can we add ZSTD compression?

### ISSUE THREAD

**Issue by MarkReedZ** [scylladb/scylla#2613]
https://github.com/MatejTymes/cassandra-zstd

Cassandra supports ZSTD compression by including the jar files built from the above source.

**Comment by avikivity** [comment]
There is a C library, so it's certainly possible.

A nice feature is that it includes a training mode that should improve compression ratio for sstables even with small chunk size.

**Comment by raphaelsc** [comment]
On Sun, Apr 1, 2018 at 6:22 AM, Sokolov Yura <notifications@github.com>
wrote:

> Why it takes so long to consider?
>
We consider it definitely given that its compression ratio seems
significantly better than lz4 at roughly the same compression speed, but
it's not a high priority item for us at this very moment.

**Comment by OzySky** [comment]
+1

**Comment by dorlaor** [comment]
Just read about it within the context of myRocks, sounds like an easy win:
https://github.com/facebook/zstd

**Comment by OzySky** [comment]
Any news on this?

**Comment by nwong-blz** [comment]
Adding my voice to requesting this!

**Comment by dorlaor** [comment]
This is actually a good low hanging fruit that someone new to Scylla can
code in a couple of hours

**Comment by MarkReedZ** [comment]
Awesome! Thanks guys
