### ISSUE TITLE
No way to install Scylla on my Ubuntu Xenial server

### ISSUE THREAD

**Issue by bzkdjc** [scylladb/scylla#2614]
*Installation details*
Scylla version (or git commit hash): v 1.7
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04.2

Platform (physical/VM/cloud instance type/docker): VM
Hardware: sockets= cores=4 hyperthreading= memory=16GiB
Disks: (SSD/HDD, count) 1 SSD

I can't manage to install ScyllaDB when following insctructions here: http://www.scylladb.com/download/ubuntu-16-04/ 

```bash
$ sudo wget -O /etc/apt/sources.list.d/scylla.list http://downloads.scylladb.com/deb/ubuntu/scylla-1.7-xenial.list
Saved : «/etc/apt/sources.list.d/scylla.list»

/etc/apt/sources.list.d/scylla.list        100%[======>]     107  --.-KB/s    in 0s

2017-07-20 01:11:45 (12,0 MB/s) - «/etc/apt/sources.list.d/scylla.list» saved [107/107]

$ sudo apt update
Err:6 http://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu xenial Release
  404  Not Found
Reading... Done
E: The repository 'http://s3.amazonaws.com/downloads.scylladb.com/deb/ubuntu xenial Release' does not have a Release file.
```

The repo does not seem to exist!  (404 Not Found)
Therefore, install process does not reach `apt install` step.

**Comment by tzach** [comment]
@bzkdjc look similar to #1991
Can you please try the bypass suggested by @syuu1228 
https://github.com/scylladb/scylla/issues/1991#issuecomment-272072367

**Comment by bzkdjc** [comment]
Please, note that `apt update` returns an E/Err (ERROR), not a W (Warning). 
So, the local cache is not updated. 

When trying to bypass, I just get : 
```bash
$ sudo apt install scylla
Reading... Done
E: Unable to find package scylla
```

**Comment by syuu1228** [comment]
@bzkdjc "apt update" won't work with unsigned repo on Ubuntu 16.04.
Following commands will work.
```
sudo apt-get update --allow-unauthenticated
sudo apt-get install scylla --allow-unauthenticated
```

**Comment by bzkdjc** [comment]
Thank you  @syuu1228; the commands you supplied worked with warnings. 
The local cache is now updated and all Scylla packages and dependencies (many) are available for install without problem. 

**It works!** 

Should we consider these commands (`--allow-unauthenticated`) as a temporary workaround or is this the way to install Scylla on *apt*-compatible systems?

**Comment by penberg** [comment]
@bzkdjc It's the way to install the packages until we actually sign our packages. See https://github.com/scylladb/scylla/issues/848 for more discussion.
