### ISSUE TITLE
io_tune coredump on Ubuntu 16

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2618]
*Installation details*
Scylla version (or git commit hash): 1.7.2-0.20170706.a24dcf1-0ubuntu1
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): 16.04.2 LTS

```
scylla_setup --no-raid-setup --no-version-check --disks /dev/xvdc --setup-nic --nic ens3
```

```
Generating evaluation file sized 10GB... stopped early due to disk space issues. Will continue but accuracy may suffer.
6.0946GB written in 72 seconds
Refining search for maximum. So far, 10684 IOPS
Maximum throughput: 10684 IOPS
IOtune timed out before it could finish. An estimate will be provided but accuracy may suffer
/usr/lib/scylla/scylla_io_setup: line 81: 27388 Floating point exception(core dumped) iotune --evaluation-directory $DATA_DIR --format envfile --options-file /etc/scylla.d/io.conf $IOTUNE_ARGS
```

coredump uploaded to `scylladb-users-upload.s3.amazonaws.com/84a48956-ce18-420f-8aba-ca01478c7006/core.iotune`

io_tune fails on 3 out of 4 runs. The successful run produces the following results:
```
Generating evaluation file sized 10GB... timed out before we could write the entire file. Will continue but accuracy may suffer.
6.47534GB written in 144 seconds
Refining search for maximum. So far, 56816 IOPS
Maximum throughput: 56816 IOPS
Recommended --max-io-requests: 93
Written the above values to /etc/scylla.d/io.conf
```

**Comment by slivne** [comment]
@tzach - which instance is this tested on ? to make sure we have this fixed we need reproducer information

@glommer - do you have time to look at this ?

**Comment by tzach** [comment]
Pretty sure it was c3.xlarge

**Comment by tzach** [comment]
I was able to reproduce io_tune coredump on a c3.xlarge, with AMI ami-835b4efa (Ubuntu 16) on the Oregon region

**Comment by benoit-canet** [comment]
@tzach Trying to reproduce this with a c3.xlarge using ubuntu 16.04 and scylla version 1.7.4-0.20170726.ff643e3. Am I doing it right ?

Everything seem to go fine in my testing.

What is clear is that it crash only when you have low iops count on the instance (10k iops)

**Comment by benoit-canet** [comment]
@tzach: will try to reproduce in the Oregon zone

**Comment by benoit-canet** [comment]
@tzach: Is it on purpose that you use the "--no-raid-setup" flag ? It will make the test to run on the operating system disk which may be not so performing and lack disk space.

**Comment by benoit-canet** [comment]
@tzach: I reproduced the crash but I wonder if it just because the root disk is low on disk space.

**Comment by slivne** [comment]
the file should not be created on root disk it should be on the attached
formatted disk /dev/xvdc

**Comment by benoit-canet** [comment]
@slivne but from the first trace of the issue it indicate that the free space that what eaten by iotune match exactly the free space of the root disk. The maximum IOPS count of the trace confirm this.

Maybe we have a pathological case when iotune fill the disk.

I'll compile scylla on this machine to track this down.

**Comment by benoit-canet** [comment]
@tzach ping

**Comment by tzach** [comment]
If this is the case, io_tune should either refuse to run or exit gracefully. not coredump

**Comment by slivne** [comment]
Fair enough lets add code prior to generating the 10GB file to check there
is 10GB available - or else why try.

Tzach - what about the issue of running scylla_setup without raid - does
that need fixing or not ?

**Comment by tzach** [comment]
Here is what I think happened:
With only one disk (/dev/xvdc) I assumed there is no need to setup RAID, so I used the `--no-raid-setup` option. Without this option, the disk parameter `--disks /dev/xvdc` was ignored, and, as @benoit-canet  pointed out, io_tune run on the root device. Since root had less than 10Gb disk space, io_tune took the entire disk space, failed to write the results, and coredump.

Here is how to improve install process:

- iotune should exit immediately (before starting) with less than 20GB of space
- scylla_setup should not accept --disks parameter if it is ignored
- `--no-raid-setup` option should be either rename to `--no-raid-and-xfs-setup` or better yet, split to `--no-raid-setup` and `--no-xfs-setup` where one does not force the other. 
- scylla_setup can skip the "Creating RAID0" step is only one disk was provided

One more observation is Ubuntu 16 AMI mount one of the two attached SSD, /dev/xvdb, by default. This leaves just one /dev/xvdc for scylla_setup to use. We can recommend unmounting before running scylla_setup, so it can be used for data.

@slivne @benoit-canet @syuu1228 if we agree with the above, I will close this issue and open new ones for each bullet.

**Comment by syuu1228** [comment]
@tzach Ignoring --disks option is correct behavior, when you specified --no-raid-setup.
Even you have only one disk, you cannot specify --no-raid-setup, you should run RAID setup for /dev/xdc.
But then the script will create RAID0 (/dev/md0) on only one disk (/dev/xvdc), I think that's the real issue.
(It still works finely, but may have performance degradation, and it doesn't make sense to create RAID with only one disk)

I also think the name of the option "--no-raid-setup" and the name of the script "scylla_raid_setup" is not correct, this is the stage to setup additional disks for data partition, so probably "--no-disk-setup" and "scylla_disk_setup" is better name.

**Comment by tzach** [comment]
https://github.com/scylladb/scylla/issues/2674

**Comment by tzach** [comment]
https://github.com/scylladb/scylla/issues/2675

**Comment by tzach** [comment]
https://github.com/scylladb/scylla/issues/2676

**Comment by tzach** [comment]
> @tzach Ignoring --disks option is correct behavior, when you specified --no-raid-setup.

Wouldn't it be better to let the user knows the script ignore his parameter, rather than silently ignore it?

**Comment by tzach** [comment]
Closing this issue, after breaking it to 3 new issues.
