### ISSUE TITLE
Installing scylla-tools-core on deb8/ubuntu14/ubuntu16 works, using scylla-sstableloader fails

### ISSUE THREAD

**Issue by harelassayag** [scylladb/scylla#2621]
Any usage of scylla-sstableloader will lead to error:
`Error: Could not find or load main class com.scylladb.tools.BulkLoader
`
## Reproduction

1. Install Debian 8 (Jessie) / Ubuntu 14.04 LTS / Ubuntu 16.04 LTS on n1-standard-2 (2 vCPUs, 7.5 GB memory) (GCE)
2. Install Java 8
```
sudo vim /etc/apt/sources.list.d/java-8-debian.list
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886
sudo apt-get update
sudo apt-get install oracle-java8-installer
```
3. Install Cassandra (**not necessary**, did that to check for conflict in installation, mentioning it just in case)
```
echo "deb http://www.apache.org/dist/cassandra/debian 311x main" | sudo tee -a /etc/apt/sources.list.d/cassandra.sources.list
curl https://www.apache.org/dist/cassandra/KEYS | sudo apt-key add -
sudo apt-get update
sudo apt-get install cassandra
```
4. Add scylla reposetory

- Debian 8 (Jessie)
```
sudo wget -0 /etc/apt/sources.list.d/scylla-tools-core.list https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/jessie/branch-2.0/7/scylla.list
sudo apt-get update
```
- Ubuntu 14.04 LTS
```
sudo wget -O /etc/apt/sources.list.d/scylla-tools-core.list https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/xenial/branch-2.0-branch-2.0-branch-2.0/9/scylla.list
sudo apt-get update
```
- Ubuntu 16.04 LTS
```
sudo wget -O /etc/apt/sources.list.d/scylla-tools-core.list https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/xenial/branch-2.0-branch-2.0-branch-2.0/9/scylla.list
sudo apt-get update
```
5. install scylla-tools-core
`sudo apt-get install scylla-tools-core
`
6. run scylla-sstableloader

**Comment by slivne** [comment]
- will try to fix - if we can not will revert

**Comment by slivne** [comment]
@syuu1228  can you please send the patches for centos as well

**Comment by slivne** [comment]
fixed by scylladb/scylla-tools-java@5a4e15da42116a73cca28d4caf6ced1d28a3b174

@harelassayag this will be part of 2.0-rc3 - once its releases please test

**Comment by tzach** [comment]
@harelassayag ping

**Comment by slivne** [comment]
@harelassayag - rc3 is out - lets test this

**Comment by harelassayag** [comment]
tested with the following repositories:
Debian: https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/jessie/branch-2.0/27/scylladb-2.0/scylla.list
Ubuntu-14: https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/ubuntu/branch-2.0/25/scylladb-2.0/scylla.list
Ubuntu-16: sudo wget -O /etc/apt/sources.list.d/scylla-tools-core.list https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/xenial/branch-2.0/26/scylladb-2.0/scylla.list

Works fine with all (also pre-installed Cassandra on all of them to make sure there are no conflicts).

**Comment by slivne** [comment]
@harelassayag thanks
