### ISSUE TITLE
Versioned sstable_set

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2622]
Right now any time we modify an `sstable_set` (add an sstable after a memtable flush, or replace one set of sstables by another due to compaction), we create a copy of the `sstable_set`. For large `sstable_set`s this is expensive.

What we can do instead is create a multiversioned `sstable_set`; each add/remove operation creates a new version; each sstable within the set has is associated with a range of versions where it is valid.

```c++
class versioned_sstable_set {
public:
    void update(sstable_list removed, sstable_list added); // creates a version; strong exception guarantee
    sstable_set get() const; // captures a version and returns a pointer to a version within the set
};
```
as soon as all `sstable_set` handles that point to a specific version dies, that version is removed and any sstables that can be freed are released.

Internally, we can replace sstables in `bag_sstable_set` and `partitioned_sstable_set` with something like

```c++
struct versioned_sstable_data {
    version _version_added;
    optional<version> _version_removed;
    shared_sstable sst;
};

using version_sstable = lw_shared_ptr<versioned_sstable_data>;

std::unordered_multimap<version, versioned_sstable> _added_at;
std::unordered_multimap<version, versioned_sstable> _removed_at;
std::unordered_map<version, unsigned> _reference_count;
```

`sstable_set` functions such as `select()` would skip over sstables not in the captured version.

**Comment by avikivity** [comment]
@wmitros try to get yourself assigned to this

**Comment by raphaelsc** [comment]
On Wed, Aug 12, 2020 at 11:56 AM Avi Kivity <notifications@github.com>
wrote:

> @wmitros <https://github.com/wmitros> try to get yourself assigned to this
>
This will help a lot with the incremental compaction approach, which
modifies the sstable set way too frequently.

**Comment by kbr-** [comment]
Sounds like we could just replace these `std::unordered_*map` structures with purely-functional data structures.
https://en.wikipedia.org/wiki/Persistent_data_structure
Doesn't boost or abseil have anything?

**Comment by avikivity** [comment]
Not that I know. And note that one of the sstable_set implementations is an interval map, so not a common container.

**Comment by wmitros** [comment]
I've started to work on this issue and I have a a question about what do we want the `sstable_set `to be after this change. Should it be a class that's bound to a `versioned_sstable_set` and reads values from the data that's shared across versions, or do we want it to stay as-is, but only create instances of it for versions that are captured? Or maybe do we want to have both options?

**Comment by avikivity** [comment]
The former (shared state in versioned_sstable_set; an sstable_set is a pointer into the shared state with a version identifier).

But before rushing into implementation let's ensure we have a shared understanding of the problem. Here is mine:

1. sstable_sets evolve slowly as memtables are flushed into new sstables that are added, and as some sstables are replaced by compaction
2. each such change involves a copy of the sstable_set, which is O(n log n) for partitioned_sstable_set
3. eventually the old copies of sstable_set are destroyed, which may be another O(n log n) operation (or maybe O(log n) if the destructor is optimized).
4. Inserting an sstable that has a wide span (such as a newly-flushed memtable) is an O(n) operation (for partitioned_sstable_set), since that sstable needs to be added into each ring_position interval managed by the set

This last fact makes me wary then even if we implement a versioned sstable_set we will still have O(n) problems. Although, if _use_level_metadata is set, it is mitigates for level 0. It still happens for level 1 with O(n / 10) cost, which may be small enough.

**Comment by denesb** [comment]
@wmitros having full instances for each version alive is what we have today and it is what we want to avoid. We want to have a more light-weight version, where adding a new sstable creates just a new version, something that is more lightweight than a full copy. I imagine something like our MVCC, where the oldest version alive is a full snapshot and all later versions are composed of a reference to the full snapshot + the modifications they add on top. When all outside references to the oldest version is dropped it is merged with the next version. Mutations of the set create a new version, which just stores the mutation itself, kinda like how our data model works.

**Comment by avikivity** [comment]
It might be enough to tag each element of the data structure with the versions it applies to, and have the iterators skip elements that don't apply to the version being iterated.

**Comment by wmitros** [comment]
Let me first explain what motivated my previous question. 
The sstable_set is not used exclusively as this "evolving" table member, it's also being used independently of any versioned_sstable_set, as a container for a vector of shared_sstables (view_update_generator::start(), compaction::setup()) or as a mutable local copy of a versioned_sstable_set snapshot (regular_compaction::update_pending_ranges()). This issue shouldn't be hard algorithmically but it may need adding a non-versioned variation of the sstable_set.

When it comes to the sstable_sets that are actually evolving, one thing is also worth noticing: when we want to access the sstables stored in the set, if using any other method than all() (so select(), select_sstable_runs() or incremental_selector::select()) we're creating a new vector with copies of all selected shared_sstables. It might not be that expensive assuming we'll read all selections anyway, but if that isn't the case, this should probably be optimized too. On the other hand, if we're selecting from all captured versions, adding a versioned_sstable_set might not help too much - it would simply let us copy the element once instead of twice.

Still, the versioned_sstable_set definitely does help with creating new versions without copying everything. I see that inserting sstables into partitioned_sstable_set might still hold us back - maybe using some structure that's smarter than boosts interval map could help, but I guess that a separate issue.

Before addressing your implementation suggestions, I'd like to ask about what's the size of data that the sstable_set will be working with? In particular, how many versions can there be and how big a version can get? I suppose it can be quite large, but if that's the case, the approach that involves skipping elements that don't apply to an iterated version might cause the iterator to skip over an disproportionately big number of elements.

**Comment by denesb** [comment]
Note that when calling `select()` at all, the assumption is that:
* we have a non-partitioned sstables set and we select all sstables -- in case we need not make a copy, we can just return a reference to `_all`;
* we have a partitioned sstable set, in which case only a small subset of the sstables will be selected on each select call, so we are copying only a small subset of them in total (and a subset of these per select call);

**Comment by denesb** [comment]
> Still, the versioned_sstable_set definitely does help with creating new versions without copying everything. I see that inserting sstables into partitioned_sstable_set might still hold us back - maybe using some structure that's smarter than boosts interval map could help, but I guess that a separate issue.
> 
> Before addressing your implementation suggestions, I'd like to ask about what's the size of data that the sstable_set will be working with? In particular, how many versions can there be and how big a version can get? I suppose it can be quite large, but if that's the case, the approach that involves skipping elements that don't apply to an iterated version might cause the iterator to skip over an disproportionately big number of elements.

We are typically adding (memtable flush, compaction) or removing (compaction) a few elements. When adding new elements, we can insert these into a parallel interval map and consult both on select. When removing, we can remember the address of the removed sstable and remove these from the selection.

I expect to have 1-2 versions alive typically.

**Comment by avikivity** [comment]
> Let me first explain what motivated my previous question.
> The sstable_set is not used exclusively as this "evolving" table member, it's also being used independently of any versioned_sstable_set, as a container for a vector of shared_sstables (view_update_generator::start(), compaction::setup()) or as a mutable local copy of a versioned_sstable_set snapshot (regular_compaction::update_pending_ranges()). This issue shouldn't be hard algorithmically but it may need adding a non-versioned variation of the sstable_set.

I'd treat this as a low-priority requirement. If the design forces us to have a versioned_sstable_set for view_update_generator, then so be it. Of course it's nicer if it doesn't force us, but it is secondary to meeting the requirement of inexpensive copies and operations on sstable_sets.

> 
> When it comes to the sstable_sets that are actually evolving, one thing is also worth noticing: when we want to access the sstables stored in the set, if using any other method than all() (so select(), select_sstable_runs() or incremental_selector::select()) we're creating a new vector with copies of all selected shared_sstables.

This is for bag_sstable_set, yes? The assumption is that bag_sstable_set is used for small numbers of sstables. For Size Tiered Compaction Strategy you'd expect small_constant * log(disk_size / memory_size). For our target maximum disk_size / memory_size (100), that number is a few dozen. So it shouldn't be that expensive.

For partitioned_sstable_set we expect (table_size / (nr_shards * 160MB)) (for Leveled Compaction Strategy), with s/160MB/1GB/ for Incremental Compaction Strategy. For a 60 TB table on 60 shards, that translates to 6,000 sstables. Combined with the more expensive data structure that generates stalls.

> It might not be that expensive assuming we'll read all selections anyway,

In general something selected will need to be touched in some way. At least we have to check the bloom filter, and if that passes actually perform a disk read (which is much more expensive than a short vector copy). 

> but if that isn't the case, this should probably be optimized too. On the other hand, if we're selecting from all captured versions, adding a versioned_sstable_set might not help too much - it would simply let us copy the element once instead of twice.
> 
> Still, the versioned_sstable_set definitely does help with creating new versions without copying everything. I see that inserting sstables into partitioned_sstable_set might still hold us back - maybe using some structure that's smarter than boosts interval map could help, but I guess that a separate issue.

Well, we should see that we don't solve half the issue only to bump into the other half once it's solved.

> 
> Before addressing your implementation suggestions, I'd like to ask about what's the size of data that the sstable_set will be working with?

See the calculation above, we get about 6,000 for that sample table. I'd like to increase the 160MB sstable size to 1GB so it would be 1,000 sstables, but there is a lot of inertia in this area. We're afraid to change those sizes because it might affect existing workloads in ways we can't predict. @raphaelsc please help.

> In particular, how many versions can there be and how big a version can get? 

There will be a "few" versions but many snapshots. Each time a compaction or a query start, they take a snapshot (=copy). Each time a compaction completes, it mutates the sstable_set stored in the table. Each time a query completes, it drops its snapshot. So a snapshot should be really cheap, but the number of non-identical snapshots at any time is low (less than 10, usually 1-4).

> I suppose it can be quite large, but if that's the case, the approach that involves skipping elements that don't apply to an iterated version might cause the iterator to skip over an disproportionately big number of elements.

Because the lifetime of snapshots isn't very high compared to the mutation rate, I think skipping is viable.

**Comment by raphaelsc** [comment]
On Mon, Sep 14, 2020 at 10:57 AM Avi Kivity <notifications@github.com>
wrote:

> Let me first explain what motivated my previous question.
> The sstable_set is not used exclusively as this "evolving" table member,
> it's also being used independently of any versioned_sstable_set, as a
> container for a vector of shared_sstables (view_update_generator::start(),
> compaction::setup()) or as a mutable local copy of a versioned_sstable_set
> snapshot (regular_compaction::update_pending_ranges()). This issue
> shouldn't be hard algorithmically but it may need adding a non-versioned
> variation of the sstable_set.
>
> I'd treat this as a low-priority requirement. If the design forces us to
> have a versioned_sstable_set for view_update_generator, then so be it. Of
> course it's nicer if it doesn't force us, but it is secondary to meeting
> the requirement of inexpensive copies and operations on sstable_sets.
>
> When it comes to the sstable_sets that are actually evolving, one thing is
> also worth noticing: when we want to access the sstables stored in the set,
> if using any other method than all() (so select(), select_sstable_runs() or
> incremental_selector::select()) we're creating a new vector with copies of
> all selected shared_sstables.
>
> This is for bag_sstable_set, yes? The assumption is that bag_sstable_set
> is used for small numbers of sstables. For Size Tiered Compaction Strategy
> you'd expect small_constant * log(disk_size / memory_size). For our target
> maximum disk_size / memory_size (100), that number is a few dozen. So it
> shouldn't be that expensive.
>
> For partitioned_sstable_set we expect (table_size / (nr_shards * 160MB))
> (for Leveled Compaction Strategy), with s/160MB/1GB/ for Incremental
> Compaction Strategy. For a 60 TB table on 60 shards, that translates to
> 6,000 sstables. Combined with the more expensive data structure that
> generates stalls.
>
> It might not be that expensive assuming we'll read all selections anyway,
>
> In general something selected will need to be touched in some way. At
> least we have to check the bloom filter, and if that passes actually
> perform a disk read (which is much more expensive than a short vector copy).
>
> but if that isn't the case, this should probably be optimized too. On the
> other hand, if we're selecting from all captured versions, adding a
> versioned_sstable_set might not help too much - it would simply let us copy
> the element once instead of twice.
>
> Still, the versioned_sstable_set definitely does help with creating new
> versions without copying everything. I see that inserting sstables into
> partitioned_sstable_set might still hold us back - maybe using some
> structure that's smarter than boosts interval map could help, but I guess
> that a separate issue.
>
> Well, we should see that we don't solve half the issue only to bump into
> the other half once it's solved.
>
> Before addressing your implementation suggestions, I'd like to ask about
> what's the size of data that the sstable_set will be working with?
>
> See the calculation above, we get about 6,000 for that sample table. I'd
> like to increase the 160MB sstable size to 1GB so it would be 1,000
> sstables, but there is a lot of inertia in this area. We're afraid to
> change those sizes because it might affect existing workloads in ways we
> can't predict. @raphaelsc <https://github.com/raphaelsc> please help.
>
I'm planning to address this in my upcoming doc for us to close the loop on
LCS. I'm not confident about switching the default *now* as I'm not
confident about LCS' current ability to reshape *effectively* on sstable
size change. There will be an increase in temporary SA, which is expected,
from ~10*160M to ~10*1G, which is okay. I'd like to understand better the
impact on WA, as a result of L1 being ~6x (1G/160M) bigger and still being
rewritten entirely on every L0->L1 promotion, however, the # of levels is
expected to decrease, so they may cancel each other out.

**Comment by avikivity** [comment]
One thing we can try is to have a separate interval_map for each level. Mixed levels are expensive because a change to L1 (that happens frequently) touches 10 L2, 100 L3, and 1000 L4. And a promotion from L0 to L1 touches all to L1, so it's basically an O(n) operation.

**Comment by avikivity** [comment]
Functions like select() will become less efficient - they'll have to select each interval_map separately and merge the results.

**Comment by raphaelsc** [comment]
> One thing we can try is to have a separate interval_map for each level. Mixed levels are expensive because a change to L1 (that happens frequently) touches 10 L2, 100 L3, and 1000 L4. And a promotion from L0 to L1 touches all to L1, so it's basically an O(n) operation.

the insertion cost seems inversely proportional to the level we're promoting data to. promoting from L0->L1 spans 100% of intervals, but L1->L2 only ~10%, and L2->L3 ~1%. so perhaps storing only L1 in a separate interval map is enough? so that will reduce the penalty on select() you were worried about. we already store L0 separately, but to avoid a quadratic space issue.

**Comment by avikivity** [comment]
I'd like to reduce the complexity, so I prefer per-level map than special-cases.

**Comment by avikivity** [comment]
@wmitros see #7220 for a similar problem. token_metadata evolves slowly, and is quite large. It can benefit from the same rework. I'm not suggesting to merge the problems, just keep it in mind.

**Comment by wmitros** [comment]
Thanks for the advice, I'll go with the skipping iterator approach. Tagging the sstables with versions doesn't give a efficient way of deciding which sstables to remove completely and when to do it, or at least I don't see one, so for that purpose I'll add something like our MVCC where we merge versions that aren't referenced anywhere - when the version that adds an sstable merges with the version that erases it, the sstable will be removed.
I still think I'll need to add some local version of the versioned_sstable_set. It won't be needed in cases where we create a set off a vector, but in compaction we add, erase, and select sstables from a copy of the tables sstable_set and we don't want to copy or modify the versioned_sstable_set in this case
