### ISSUE TITLE
create materialized view accepts empty "where" clause, but then fails on all subsequent ops

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#2628]
copied over from scylladb/scylla-tools-java#39

original issue from @elcallio 

If I create a simple table like:
```

create keyspace ks WITH replication={ 'class' : 'SimpleStrategy', 'replication_factor' : 1 } ; 
use ks;
create table  test (pk text primary key, c0 int, c1 int, c2 int);
insert into test (pk, c0, c1, c2) values('apa', 1, 2, 3);
insert into test (pk, c0, c1, c2) values('kossa', 4, 5, 6);

```
then do

```
create materialized view test_by_c2 as select c2, c1, c0, pk from test primary key (c2, pk);
```

it succeeds. But both queries, and more importantly, inserts into the `test` table, will fail due to the generated select statement being broken (WHERE <nothing> ALLOW..).

Note that origin also does not handle an empty where, so maybe the problem is that we allow the view creating without where clause.

**Comment by nyh** [comment]
I can reproduce this bug. Indeed, Scylla allows a user to create a view without the mandatory "where c2 is not null" without any error message, and then inserts fail. The client gets an obscure error on insert:
```
WriteFailure: Error from server: code=1500 [Replica(s) failed to execute write] message="Operation failed for try1.cf - received 0 responses and 1 failures from 1 CL=ONE." info={'failures': 1, 'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}
```
The log contains:
```
ERROR 2018-03-19 18:00:55,342 [shard 0] storage_proxy - exception during mutation write to 127.0.0.1: exceptions::syntax_exception (line 1:24 no viable alternative at input 'ALLOW')
```
I've reproduced this in a unit test, and will submit a patch and a unit test that confirms the problem and its fix.

**Comment by nyh** [comment]
After I wrote a unit test which reproduces this bug, I realized we already have one, test_primary_key_is_not_null, but it does NOT reproduce this bug. What the heck? Now investigating.

**Comment by nyh** [comment]
Turns out test_primary_key_is_not_null was buggy, it got exceptions where it expected, but those were things like syntax errors, not actual "is not null" problems :-) I'm writing a new test for this. And of course will need to fix the bug...

**Comment by nyh** [comment]
I just sent a patch to fix the bug, and a sepate patch to fix the unit test, to the mailing list. Please review.
I also tested manually that my patch fixes the error reported at the top of this issue - not just my new unit test :-)
