### ISSUE TITLE
Failed to install specific Scylla patch - CentOS 7 

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#2629]
Trying to install a specific Scylla version

1  `sudo yum install epel-release wget`
2  `sudo wget -O /etc/yum.repos.d/scylla.repo http://downloads.scylladb.com/rpm/centos/scylla-1.6.repo`
3 ` sudo yum install scylla-1.6.4`
4  `scylla --version`
5. Result is **Scylla version 1.6.6** and not 1.6.4

**Comment by amoskong** [comment]
`scylla` is the meta package, but it doesn't request dependencies of the right version.

In Nir's example, we expected other scylla packages of 1.6.4 are also installed, but actually scylla-1.6.4 and latest other scylla packages are installed.

**Comment by slivne** [comment]
There maybe a workaround till we fix this try running
```
sudo yum install  yum install scylla\-*1.6.X
```

**Comment by slivne** [comment]
related to #2642
