### ISSUE TITLE
total dirty memory trigger for flushing memtables

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#263]
We will flush a memtable if it reaches 11%*50% of memory, but what if we have 100 memtables, each taking 0.5% of memory?  We will then have 50% dirty memory, so no new requests, but no memtables will be flushed -> livelock.

Should fix by picking the largest memtable at around 45%, and flushing it, if no flushing is in progress, or something.

**Comment by slivne** [comment]
@avikivity what is the status of this - we have modified this as far as I recall since anglerfish

**Comment by avikivity** [comment]
Fixed by 895e838ac0b6950f9badb73b5a28d1795b426600.
