### ISSUE TITLE
longevity(decommission & repair): std::bad_alloc (std::bad_alloc)

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2638]
*Installation details*
Scylla version (or git commit hash): 1.7.3-0.20170719.41b4055
Cluster size: 3 datacenters (us-east1-b:5 nodes, us-west1-b:5 nodes, us-east4-b:3 nodes)
db instance type: n1-highmem-8 (8 vCPUs, 52 GB memory)
3 loaders, type: n1-highcpu-4 (4 vCPUs, 3.6 GB memory)
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

Monitor [link](http://35.196.21.163:3000/dashboard/db/scylla-per-server-metrics-1-7?from=now-250m&to=now)

Test content: Random decommission and repair Nemesis
C-s cmdline: `cassandra-stress write cl=QUORUM duration=10080m -schema keyspace=keyspace$2 'replication(strategy=NetworkTopologyStrategy,us-east1-b=3,us-west1-b=3,us-east4-b=2)' -port jmx=6868 -mode cql3 native -rate threads=1000 -pop seq=1..100000000`
three c-s processes, --node parameter assigned to first node in different datacenters

*Issue Description*
In Longevity test of multiple datacenters, one node in `3rd datacenter` raised many `std::bad_alloc` error after job run `20 hours`.

There are only 3 nodes in 3rd datacenter, the bad_allloc error occurred on `sct-mdcdev-scylla-db-node-552560e0-2-18` when `sct-mdcdev-scy
lla-db-node-552560e0-2-13` is decommissioned and new node (sct-mdcdev-scylla-db-node-552560e0-2-22) is added.

```
2017-07-26 05:16:38,160 nemesis          L0224 INFO | sdcm.nemesis.MdcChaosMonkey: Decommission Node sct-mdcdev-scy
lla-db-node-552560e0-2-13 [35.188.247.87 | 10.240.0.85] (seed: False) PASS
...
2017-07-26 05:17:48,408 remote           L0197 DEBUG| [35.188.250.148] [stdout] Jul 26 05:17:48 warning|  [shard 7] storage_proxy - Failed to apply mutation from 10.240.0.74#6: std::bad_alloc (std::bad_alloc)
...
2017-07-26 08:01:21,985 remote           L0197 DEBUG| [35.188.250.148] [stdout] Jul 26 08:01:21 err    |  [shard 4] storage_proxy - exception during mutation write to 10.240.0.84: std::bad_alloc (std::bad_alloc)

$ cat latest/job.log |grep bad_alloc|wc -l
1702147
```

All the bad_alloc errors are raised by node  sct-mdcdev-scylla-db-node-552560e0-2-18 (35.188.250.148|10.240.0.84), it's a node in 3rd datacenter.

![wechatimg220](https://user-images.githubusercontent.com/309708/28612815-069ee790-7223-11e7-8dfa-8d1cdff868b2.jpeg)

**Comment by amoskong** [comment]
Grafana Monitor [link](http://35.196.21.163:3000/dashboard/db/scylla-per-server-metrics-1-7?from=now-250m&to=now)   (live now)

Snapshot of memory:
![wechatimg221](https://user-images.githubusercontent.com/309708/28613286-90772224-7224-11e7-9d1a-344885ede6b0.jpeg)

**Comment by slivne** [comment]
maybe related to #2040

**Comment by harelassayag** [comment]
this happened twice on longevity 1.7.3 1TB while adding a node after decommission.
@roydahan

**Comment by duarten** [comment]
Do we have a core dump yet?

**Comment by duarten** [comment]
Closing this as stale.
