### ISSUE TITLE
Package our own boost version

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#2639]
In order to move to C++17, we need to apply patches to boost icl, which is currentely unmaintained.

We could package our own boost, or put it in a repo we control, to solve this problem. It would also allow to us to pin it to a version we can assure works well with Scylla.

**Comment by nyh** [comment]
If the boost ICL specifically is dead, perhaps we should create a fork just of it, and leave the non-dead parts to continue to use the build machine's Boost, not a fork.

**Comment by duarten** [comment]
Maybe this can be closed now, seeing as we already do have our own boost version? /cc @avikivity
