### ISSUE TITLE
[AMI for ec2] insufficient memory for the Java Runtime Environment

### ISSUE THREAD

**Issue by l15k4** [scylladb/scylla#2641]
*Installation details*
AMI `ami-98e1e9fe` for ec2 i3 instances for eu-west with 1.7.0rc3

Hey, there is a serious problem with this AMI, most of the time, `java` cannot be used on these instances because of : 
```
$ java -version
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000005e0c00000, 335544320, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (mmap) failed to map 335544320 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /home/centos/hs_err_pid13186.log
```
Which prevents from running `nodetool` and thus leads to loosing control of the cluster management.
Notice the amount of memory that `java` tries to allocate.

I tried to control nodes remotely, but even though I allowed remote jmx connections, I could not connect to them remotely for some reason, so this issue is very painful.

**Comment by l15k4** [comment]
I have a temporary workaround for this if anybody needed : 
`java -version` actually works this way `java -Xmx128m -version`, so it needs to be edited at : 
```
$ sudo vim /etc/scylla/cassandra/cassandra-env.sh
```
`-Xmx128m -version`  # this is the first fail point
https://github.com/scylladb/scylla-tools-java/blob/master/conf/cassandra-env.sh#L90

The second fail point is : 
```
$ sudo vim /usr/bin/nodetool
```
where `-Xmx` must be also explicitly set to `-Xmx128m`. The cassandra scripts that are sourced in `nodetool` set `JVM_OPTS` to `7666M`, possibly accidentally because it is too much for `nodetool`.

so by forcing any `java` invocation to use `-Xmx128m` finally makes it work on Centos.

**Comment by tzach** [comment]
Thanks, @l15k4 look like a reasonable solution in the long term as well.
We need to `-Xmx256m` limit for the nodetool does not break any of its commands.
You are more than welcome to sign the [Contributor Agreement](http://www.scylladb.com/open-source/cla/)  and [send a patch](http://docs.scylladb.com/contribute/) if you want to

**Comment by l15k4** [comment]
@tzach this rather a workaround, the root issue here is some Centos system level problem with `java`.
I will move this to https://github.com/scylladb/scylla-ami/issues/26 and close.
