### ISSUE TITLE
scylla-server stop/waiting

### ISSUE THREAD

**Issue by sureshpujari** [scylladb/scylla#2651]
Please help me with the below error that i am receiving in ubuntu 14 while starting the service,

sudo service scylla-server start

scylla-server stop/waiting

and the service is not starting.

uname -r

4.2.0-42-generic

**Comment by duarten** [comment]
What do the logs say?

**Comment by slivne** [comment]
@sureshpujari  closing the issue

if there is more info please post 

to get more interactive help - please join the slack channel.
