### ISSUE TITLE
coredump during node bootstrap while initializing 70-node cluster 

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#2652]
*Installation details*
Scylla version (or git commit hash):
Cluster size: 70
OS (RHEL/CentOS/Ubuntu/AWS AMI):  ami-b390ccc8 (1.7.4) 

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

[centos@ip-172-30-12-82 ~]$ coredumpctl info
           PID: 2835 (scylla)
           UID: 994 (scylla)
           GID: 1001 (scylla)
        Signal: 11 (SEGV)
     Timestamp: Mon 2017-07-31 09:45:50 UTC (54min ago)
  Command Line: /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --num-io-queues 16 --max-io-requests 128 --cpuset 1-7,9-15
    Executable: /usr/bin/scylla
 Control Group: /system.slice/scylla-server.service
          Unit: scylla-server.service
         Slice: system.slice
       Boot ID: cb1ade67dffc4e5da2a493d005c6528e
    Machine ID: 8ea3e6ea03b64d018847fcdf669935d4
      Hostname: ip-172-30-12-82
       Message: Process 2835 (scylla) of user 994 dumped core.
                
                Stack trace of thread 2835:
                #0  0x00000000005cfa37 _ZZN3net24posix_server_socket_implILN7seastar9transportE6EE6acceptEvENKUl11pollable_fd14socket_addressE_clES4_S5_ (/usr/bin/scylla)

**Comment by larisau** [comment]
[journalctl_log.txt](https://github.com/scylladb/scylla/files/1187259/journalctl_log.txt)

**Comment by gleb-cloudius** [comment]
The trace in the log is:

```
print_backtrace_safe at /usr/src/debug/scylla-1.7.4/seastar/core/reactor.cc:2374
 (inlined by) print_with_backtrace at /usr/src/debug/scylla-1.7.4/seastar/core/reactor.cc:3198
sigsegv_action at /usr/src/debug/scylla-1.7.4/seastar/core/reactor.cc:3202
 (inlined by) operator() at /usr/src/debug/scylla-1.7.4/seastar/core/reactor.cc:3178
 (inlined by) _FUN at /usr/src/debug/scylla-1.7.4/seastar/core/reactor.cc:3174
?? ??:0
net::posix_server_socket_impl<(seastar::transport)6>::accept()::{lambda(pollable_fd, socket_address)#1}::operator()(pollable_fd, socket_address) const at /usr/src/debug/scylla-1.7.4/seastar/net/posix-stack.cc:199
apply_helper<net::posix_server_socket_impl<(seastar::transport)6>::accept()::{lambda(pollable_fd, socket_address)#1}, std::tuple<pollable_fd, socket_address>&&, std::integer_sequence<unsigned long, 0ul, 1ul> >::apply({lambda(pollable_fd, socket_address)#1}&&, std::tuple<pollable_fd, socket_address>) at /usr/src/debug/scylla-1.7.4/seastar/core/apply.hh:34
 (inlined by) auto apply<net::posix_server_socket_impl<(seastar::transport)6>::accept()::{lambda(pollable_fd, socket_address)#1}, pollable_fd, socket_address>(net::posix_server_socket_impl<(seastar::transport)6>::accept()::{lambda(pollable_fd, socket_address)#1}&&, std::tuple<pollable_fd, socket_address>&&) at /usr/src/debug/scylla-1.7.4/seastar/core/apply.hh:42
 (inlined by) future<connected_socket, socket_address> futurize<future<connected_socket, socket_address> >::apply<net::posix_server_socket_impl<(seastar::transport)6>::accept()::{lambda(pollable_fd, socket_address)#1}, pollable_fd, socket_address>(net::posix_server_socket_impl<(seastar::transport)6>::accept()::{lambda(pollable_fd, socket_address)#1}&&, std::tuple<pollable_fd, socket_address>&&) at /usr/src/debug/scylla-1.7.4/seastar/core/future.hh:1267
_ZZN6futureIJ11pollable_fd14socket_addressEE4thenIZN3net24posix_server_socket_implILN7seastar9transportE6EE6acceptEvEUlS0_S1_E_S_IJ16connected_socketS1_EEEET0_OT_ENUlSE_E_clI12future_stateIJS0_S1_EEEEDaSE_ at /usr/src/debug/scylla-1.7.4/seastar/core/future.hh:872
reactor::run_tasks(circular_buffer<std::unique_ptr<task, std::default_delete<task> >, std::allocator<std::unique_ptr<task, std::default_delete<task> > > >&) at /usr/src/debug/scylla-1.7.4/seastar/core/reactor.cc:2025
reactor::run() at /usr/src/debug/scylla-1.7.4/seastar/core/reactor.cc:2467
app_template::run_deprecated(int, char**, std::function<void ()>&&) at /usr/src/debug/scylla-1.7.4/seastar/core/app-template.cc:131
main at /usr/src/debug/scylla-1.7.4/main.cc:659
```

**Comment by gleb-cloudius** [comment]
Is there core file?

**Comment by larisau** [comment]
scylladb-users-upload.s3.amazonaws.com/core.scylla.994.cb1ade67dffc4e5da2a493d005c6528e.2835.1501494350000000/core.scylla.994.cb1ade67dffc4e5da2a493d005c6528e.2835.1501494350000000.gz
