### ISSUE TITLE
node crashed during bootstrap

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#2656]
*Installation details*
Scylla version (or git commit hash):
Cluster size: 85
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-b390ccc8 (1.7.4)

Grow cluster test with initial count of nodes 85.
[centos@ip-172-30-12-18 ~]$ addr2line -fCipe /usr/lib/debug/.build-id/0b/25f69602bf37171fa60a9c8d1d9f9953afe23f.debug

?? ??:0
0x00007f0f025455f7
0x00007f0f02546e28
0x0000000000fef5dd
0x000000000103a653
0x00000000004e2140
0x0000000000531c33
0x00000000005b1c3d
0x00000000004733de
0x00007f0f02531b15
0x00000000004de0df?? ??:0
?? ??:0
then<db::schema_tables::merge_lock()::<lambda()> mutable::<lambda(bool)>::<lambda()>, future<bool_class<stop_iteration_tag> > > at /usr/src/debug/scylla-1.7.4/seastar/core/future.hh:879
 (inlined by) operator() at /usr/src/debug/scylla-1.7.4/db/schema_tables.cc:593
 (inlined by) apply at /usr/src/debug/scylla-1.7.4/seastar/core/apply.hh:34
 (inlined by) apply<db::schema_tables::merge_lock()::<lambda()> mutable::<lambda(bool)>, bool> at /usr/src/debug/scylla-1.7.4/seastar/core/apply.hh:42
 (inlined by) apply<db::schema_tables::merge_lock()::<lambda()> mutable::<lambda(bool)>, bool> at /usr/src/debug/scylla-1.7.4/seastar/core/future.hh:1267
future<bool_class<stop_iteration_tag> >::state() at /usr/src/debug/scylla-1.7.4/seastar/core/future.hh:693
 (inlined by) future<bool_class<stop_iteration_tag> >::forward_to(promise<bool_class<stop_iteration_tag> >&&) at /usr/src/debug/scylla-1.7.4/seastar/core/future.hh:933
 (inlined by) operator()<future_state<bool> > at /usr/src/debug/scylla-1.7.4/seastar/core/future.hh:872
 (inlined by) run at /usr/src/debug/scylla-1.7.4/seastar/core/future.hh:390
std::default_delete<task>::operator()(task*) const at /opt/scylladb/include/c++/5.3.1/bits/unique_ptr.h:76
 (inlined by) std::unique_ptr<task, std::default_delete<task> >::reset(task*) at /opt/scylladb/include/c++/5.3.1/bits/unique_ptr.h:344
 (inlined by) reactor::run_tasks(circular_buffer<std::unique_ptr<task, std::default_delete<task> >, std::allocator<std::unique_ptr<task, std::default_delete<task> > > >&) at /usr/src/debug/scylla-1.7.4/seastar/core/reactor.cc:2026
reactor::run() at /usr/src/debug/scylla-1.7.4/seastar/core/reactor.cc:2468
app_template::run_deprecated(int, char**, std::function<void ()>&&) at /usr/src/debug/scylla-1.7.4/seastar/core/app-template.cc:131
main at /usr/src/debug/scylla-1.7.4/main.cc:659
?? ??:0
^C

**Comment by larisau** [comment]
Aug 01 13:57:43 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - InetAddress 172.30.12.138 is now DOWN, status = NORMAL
Aug 01 13:57:44 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - InetAddress 172.30.12.138 is now UP, status = NORMAL
Aug 01 13:57:45 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - Favor newly added node 172.30.12.138
Aug 01 13:57:59 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - InetAddress 172.30.12.213 is now DOWN, status = NORMAL
Aug 01 13:57:59 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - InetAddress 172.30.12.157 is now DOWN, status = NORMAL
Aug 01 13:58:00 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - InetAddress 172.30.12.157 is now UP, status = NORMAL
Aug 01 13:58:00 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - InetAddress 172.30.12.213 is now UP, status = NORMAL
Aug 01 13:58:00 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - Favor newly added node 172.30.12.157
Aug 01 13:58:00 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - Favor newly added node 172.30.12.213
Aug 01 13:58:04 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - InetAddress 172.30.12.210 is now DOWN, status = NORMAL
Aug 01 13:58:04 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - InetAddress 172.30.12.210 is now UP, status = NORMAL
Aug 01 13:58:05 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - Favor newly added node 172.30.12.210
Aug 01 13:58:12 ip-172-30-12-18 scylla[2175]:  [shard 0] storage_service - fail to update schema_version for 172.30.12.81: std::bad_alloc (std::bad_alloc)
Aug 01 13:58:12 ip-172-30-12-18 scylla[2175]:  [shard 0] storage_service - fail to update schema_version for 172.30.12.143: std::bad_alloc (std::bad_alloc)
Aug 01 13:58:12 ip-172-30-12-18 scylla[2175]:  [shard 0] storage_service - fail to update schema_version for 172.30.12.146: std::bad_alloc (std::bad_alloc)
Aug 01 13:58:12 ip-172-30-12-18 scylla[2175]:  [shard 0] storage_service - fail to update schema_version for 172.30.12.8: std::bad_alloc (std::bad_alloc)
Aug 01 13:58:12 ip-172-30-12-18 scylla[2175]:  [shard 0] storage_service - fail to update schema_version for 172.30.12.114: std::bad_alloc (std::bad_alloc)
Aug 01 13:58:12 ip-172-30-12-18 scylla[2175]:  [shard 0] storage_service - fail to update schema_version for 172.30.12.137: std::bad_alloc (std::bad_alloc)
Aug 01 13:58:12 ip-172-30-12-18 scylla[2175]:  [shard 0] storage_service - fail to update schema_version for 172.30.12.161: std::bad_alloc (std::bad_alloc)
Aug 01 13:58:13 ip-172-30-12-18 scylla[2175]:  [shard 0] storage_service - fail to update schema_version for 172.30.12.97: std::bad_alloc (std::bad_alloc)
Aug 01 13:58:14 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - Fail to handle GOSSIP_DIGEST_ACK2: std::bad_alloc (std::bad_alloc)
Aug 01 13:58:14 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - Fail to handle GOSSIP_DIGEST_ACK2: std::bad_alloc (std::bad_alloc)
Aug 01 13:58:15 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - Fail to handle GOSSIP_DIGEST_ACK2: std::bad_alloc (std::bad_alloc)
Aug 01 13:58:15 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - Fail to handle GOSSIP_DIGEST_ACK2: std::bad_alloc (std::bad_alloc)
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - Fail to handle GOSSIP_DIGEST_ACK2: std::bad_alloc (std::bad_alloc)
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]:  [shard 0] gossip - Fail to handle GOSSIP_DIGEST_ACK2: std::bad_alloc (std::bad_alloc)
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]: Aborting on shard 0.
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]: Backtrace:
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]: 0x00000000004e06ca
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]: 0x00000000004e07d3
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]: 0x00007f0f028e10ff
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]: 0x00007f0f025455f6
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]: 0x00007f0f02546ce7
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]: 0x0000000000fef5dc
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]: 0x000000000103a652
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]: 0x00000000004e213f
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]: 0x0000000000531c32
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]: 0x00000000005b1c3c
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]: 0x00000000004733dd
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]: 0x00007f0f02531b14
Aug 01 13:58:16 ip-172-30-12-18 scylla[2175]: 0x00000000004de0de

**Comment by larisau** [comment]
core file url:
scylladb-users-upload.s3.amazonaws.com/core.scylla.994.8ae65ec2ae884ed1b5
a1fda6c95a8cf0.2175.1501595896000000/core.scylla.994.8ae65ec2ae884ed1b5a1fda6c95a8cf0.2175.1501595896000000.gz

**Comment by slivne** [comment]
we will run a large cluster test on 2.2 - to recheck the status - closing this issue.
