### ISSUE TITLE
Scylla Setup Complete the installation, but Scylla will not start

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla#2665]
*Installation details*
Scylla version (or git commit hash): 1.6.6-20170715.dd70520
Cluster size:1 node
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 14.04

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): GCE 8vcpu, 16GB
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count), 1 drive 40GB

Installed Scylla on Ubuntu 14.04. Installation completed successfully, although the drive Scylla was installed on is ext4. Can Scylla work with ext4? if not, Scylla_setup should warn about the incompatible file system.

The Setup created io.conf file /etc/scylla.d/
cat /etc/scylla.d/io.conf
SEASTAR_IO="--max-io-requests=39"

Once I tried to start Scylla, I got the following error:
Aug  2 23:36:14 eg-ubuntu1404 scylla:  [shard 0] database - Row: max_vector_size: 32, internal_count: 5
Aug  2 23:36:14 eg-ubuntu1404 scylla:  [shard 1] database - Row: max_vector_size: 32, internal_count: 5
Aug  2 23:36:14 eg-ubuntu1404 scylla:  [shard 2] database - Row: max_vector_size: 32, internal_count: 5
Aug  2 23:36:14 eg-ubuntu1404 scylla:  [shard 3] database - Row: max_vector_size: 32, internal_count: 5
Aug  2 23:36:15 eg-ubuntu1404 scylla:  [shard 0] init - /var/lib/scylla/commitlog is not on XFS. This is a non-supported setup, and performance is expected to be very bad.#012For better performance, placing your data on XFS-formatted directories is required. To override this error, see the developer_mode configuration option.
Aug  2 23:36:15 eg-ubuntu1404 scylla:  [shard 0] init - /var/lib/scylla/data is not on XFS. This is a non-supported setup, and performance is expected to be very bad.#012For better performance, placing your data on XFS-formatted directories is required. To override this error, see the developer_mode configuration option.
Aug  2 23:36:15 eg-ubuntu1404 scylla:  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (invalid configuration: path "/var/lib/scylla/commitlog" on unsupported filesystem)
Aug  2 23:36:15 eg-ubuntu1404 scylla:  [shard 0] compaction_manager - Asked to stop
 

Disk information:
yal@eg-ubuntu1404:~$ df -T
Filesystem     Type     1K-blocks    Used Available Use% Mounted on
udev           devtmpfs   7687908       4   7687904   1% /dev
tmpfs          tmpfs      1540056     272   1539784   1% /run
/dev/sda1      ext4      41251136 1608912  37843396   5% /
none           tmpfs            4       0         4   0% /sys/fs/cgroup
none           tmpfs         5120       0      5120   0% /run/lock
none           tmpfs      7700280       0   7700280   0% /run/shm
none           tmpfs       102400       0    102400   0% /run/user

**Comment by duarten** [comment]
Possibly refs #2651.

**Comment by tzach** [comment]
Closing. This is a non longer supported Scylla version, on a non longer supported Ubuntu.
