### ISSUE TITLE
Scylla on i3 using 2.0 doesn't start due to SCYLLA_ARGS parameters

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#2668]
*Installation details*
Scylla version (or git commit hash): 2.0.rc1-0.20170730.aaa59d3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

When trying to start scylla-server2.0 using ami-97114bec on i3.8xlarge, scylla fails to start with the error:
```

Aug 03 15:33:58 ip-172-30-0-123 scylla[46171]: error: too many positional options have been specified on the command line
Aug 03 15:33:58 ip-172-30-0-123 scylla[46171]: Try --help.
```

The SCYLLA_ARGS configuration in sysconfig is set using:
```
# scylla arguments (for posix mode)
SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix"

## scylla arguments (for dpdk mode)
#SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack native --dpdk-pmd"

# setup as AMI instance
AMI=yes
# Experimental for i3 AMIs
SCYLLA_ARGS="$SCYLLA_ARGS --background-writer-scheduling-quota 0.5 --auto-adjust-flush-quota 1"

```

When, marking the second SCYLLA_ARGS as a comment and moving the parameters to the first SCYLLA_ARGS, scylla-server starts successfully.

**Comment by slivne** [comment]
fixed by scylladb/scylla-ami@b41e5eb8baeb4b5414d128536a6f51e9147f7a22

**Comment by slivne** [comment]
@roydahan if you tested this please post the AMI id and close

**Comment by roydahan** [comment]
Worked using ami-84e4d1ff on i3.2xlarge.
