### ISSUE TITLE
bloom filter estimation for resharding needs to be fixed

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#2672]
Resharding on sstable that is shared by N shards may produce N sstables with filter of same size as original. That may potentially lead to OOM when resharding a high number of sstables that belong to all shards. We could possibly use scylla metadata to estimate keys for each shard owning the sstable about to be resharded.

**Comment by slivne** [comment]
did we run into an issue with this on a real system ?

**Comment by avikivity** [comment]
Yes, we did.
