### ISSUE TITLE
fragmented-partition streaming memtable can result in too-small sstables

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2679]
When streaming, large partitions are fragmented and the individual fragments are sent to avoid allocating unbounded memory. To preserve isolation, these fragments are collected in a streaming big-partition memtable and only made visible when the streaming plan is committed.

However, when the streaming plan is small-ish, the generated sstables will be small.

To fix this, instead of flushing the streaming big-partition memtable to an sstable, we can merge it with the normal streaming memtable; it will then be flushed according to the normal rules and so can grow and generate large sstables.

**Comment by asias** [comment]
Fixed by new streaming code.

8ee807321f773fcd8a38724f19789860b4020617

#3591
