### ISSUE TITLE
Selecting by second clustering key

### ISSUE THREAD

**Issue by Capitan-KoLiBer** [scylladb/scylla#2682]
Hi guys

I have a problem with  ScyllaDB

in my scenario i have a table with three columns

```CREATE TABLE test (a text , b text , c text , PRIMARY KEY ( ( a ) , b ,c ) );```

Now i want to select data's by the second cluster key ( c ) but b is needed.

My goal but incorrect query is :

```SELECT * FROM test WHERE c='...' ALLOW FILTERING```

And correct query is this :

```SELECT * FROM test WHERE b='...' AND c='...' ALLOW FILTERING```

Unfortunately indexes yet not supported and i hope to support it in new versions of scylladb

is there any solution for my problem to only use b cluster key in select query ? or i should change my data structure ?

**Comment by duarten** [comment]
Without support for secondary indexes or materialized views, you should change the data structure. You cannot restrict a clustering key without restricting the previous clustering columns.

**Comment by slivne** [comment]
I am closing this we can continue the discussion on the user mailing list or users slack channel.
