### ISSUE TITLE
promoted index entry generation triggered too often

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2684]
*Installation details*
Scylla version (or git commit hash): 1.6+

We emit a new promoted index block every 64k of uncompressed data, which is usually a  lot less compressed data. Thus, we have too many index entries, and a bloated index.

We should trigger index generation based on the compressed data size.

**Comment by slivne** [comment]
@raphaelsc - did you resolve this ?

**Comment by nyh** [comment]
I believe we didn't change this.

@avi, are you convinced we should do this? The "64K" (which is a parameter, anyway) isn't just about reading from disk, it's also data we need to parse through linearly to find a specific row (for example), and even with compression, it still remains 64K of data we need to parse. Compression just reduces the disk bandwidth, but not all the overhead.

**Comment by slivne** [comment]
@raphaelsc - did we resolve this - 

I know we changed in 8726ee937da24a1d4a20bf73d98cd434b237027e the summary generation - did we do a change to the promoted index generation

**Comment by raphaelsc** [comment]
we already feed the compressed data offset (when compression is enabled) to the summary sampling procedure. So this issue can be closed @slivne
