### ISSUE TITLE
Segregate data by timestamp for time_window_compaction_strategy

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2687]
*Installation details*
Scylla version (or git commit hash): 2.1

When opening a writer while using time window compaction strategy, create a special one that emits an sstable for every time window. This way, writes due read repairs, or compactions with imported sstables don't mess the windowing.

This is similar to how the writer for leveled compaction strategy opens a new sstable every 160MB.

**Comment by raphaelsc** [comment]
On Wed, Aug 9, 2017 at 11:31 AM, Avi Kivity <notifications@github.com>
wrote:

> /cc @raphaelsc <https://github.com/raphaelsc>
>

@avikivity interesting discussion about it here:
https://issues.apache.org/jira/browse/CASSANDRA-10496

**Comment by slivne** [comment]
related to #1660

we need to decide if we are fixing DTCS as well or only aiming to solve TWCS

**Comment by avikivity** [comment]
Implementation idea:

```c++

future<>
classify_by_timestamp(
        flat_mutation_reader input,
        noncopyable_function<int (timestamp_time ts)> classifier,
        noncopyable_function<future<> (flat_mutation_reader)> new_consumer);
```

`classify_by_timestamp()` classifies each atom's timestamp by converting it to an int. If a consumer exists for that timestamp class, the atom (and the partition key and clustering key that point to it) are written to that consumer. If not, then the consumer is created first using `new_window()`.

Note we can short-circuit the classifier if it is known in advance (due to metadata) that only a single window is needed.

**Comment by denesb** [comment]
Do we want to be strict and generate a new sstable for each window or do something like what's described in [CASSANDRA-10496](https://issues.apache.org/jira/browse/CASSANDRA-10496) (altough this might require changes in the compaction strategy as well)? I seem to recall that we had (have?) problems with streaming generating loads of small sstables.

**Comment by denesb** [comment]
What do you mean by "and anything else"?

**Comment by avikivity** [comment]
Whatever CASSANDRA-10496 is describing. I initially thought they're generating one sstable for all data outside the current window, but looks like that's not the case.

**Comment by denesb** [comment]
It appears that throughout the code-base we are directly creating sstables and writing into them. This will not work for TWCS.
We are writing sstables in the following places:
1) Flushing a memtable. I assume we switch memtables when moving to a new window, though I still couldn't find the code which does that.
2) Compaction, this works when all sstables satisfy the invariant (do not span windows), as each compaction will only compacts sstables belonging to the same window. Windows are dropped as a whole when expired. Will break when we have sstables spanning multiple windows (e.g. improted sstables).
3) Streaming (`stream_session`):
    - repair (read-repair and partition-level repair)
    - node operations that involve streaming
4) Row-level repair

It appears we need to fix (2)-(4). Which one of these are included in this ticket? Asking because @avikivity said a few comments back:
> Streaming is getting its own fix.

We also seem to have a streaming write path that writes to memtables, though I could not yet figure out when do we use that. This write path also doesn't seem to respect the TWCS (or any compaction strategy related) invariant.

I'm still in the process of skimming through the code so I might have missed some places or got something wrong.

**Comment by avikivity** [comment]
> It appears that throughout the code-base we are directly creating sstables and writing into them. This will not work for TWCS.
> We are writing sstables in the following places:
> 
> 1. Flushing a memtable. I assume we switch memtables when moving to a new window, though I still couldn't find the code which does that.

We don't. We can wire the memtable flush through the splitter, or force a memtable flush.

> 2. Compaction, this works when all sstables satisfy the invariant (do not span windows), as each compaction will only compacts sstables belonging to the same window. Windows are dropped as a whole when expired. Will break when we have sstables spanning multiple windows (e.g. improted sstables).

We can wire imports through the splitter (in the same way that we reshard them). We can also wire compactions through, but we should short-circuit if all inputs are within the same window.

> 3. Streaming (`stream_session`):
>    
>    * repair: read-repair and partition-level repair (not really sure about this).
>    * node operations that involve streaming.
> 4. Row-level repair.
> 
> It appears we need to fix (2)-(4). Which one of these are included in this ticket? Asking because @avikivity said a few comments back:
> 
> > Streaming is getting its own fix.
> 
> We also seem to have a streaming write path that writes to memtables, though I could not yet figure out when do we use that. This write path also doesn't seem to respect the TWCS (or any compaction strategy related) invariant.

We can ignore that (it's outdated), but if we wire memtable flush through the splitter, it works automatically.

> 
> I'm still in the process of skimming through the code so I might have missed some places or got something wrong.

**Comment by denesb** [comment]
What is the `atom` that is the basis for splitting mutations Row or cell?

**Comment by denesb** [comment]
What remains to be addressed (after https://github.com/scylladb/scylla/commit/dd769431259ddfea6b7523e45635e643fa11ef58) is memtable flush. Currently we have no mechanism (that I know of) that would initiate a memtable flush on window boundaries, so we depend on window size and workload combination for correctness here. Of course the stakes are a lot lower than in the case of streaming. In the worst case we will end up with several neighbouring windows flushed into a single sstable vs. wildly different windows ending up in the same sstable as in the case of streaming. I will open a separate issue for this and we can prioritize it.

It was also determined that we don't need splitting for compaction. The only case where this would have been needed was resharding and that case can be addressed by resharding the sstables window-by-window. Will open a new issue for that as well.
