### ISSUE TITLE
collectd API is not working

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#2699]
The collectd has an API to retrieve and control collectd reporting, it was broken during the changes in the metrics layer.
version 1.7 and up

**Comment by slivne** [comment]
@amnonh not clear is collectd not working at all or is it only the control api.

if collectd is not working at all we need to fix it for 2.0

If its only the latter then fix the title and we can fix this for 2.1

**Comment by amnonh** [comment]
It's the rest API of collectd, not collectd itself

**Comment by slivne** [comment]
@amnonh - please list the rest api that does not work and we will schedule accordingly

**Comment by amnonh** [comment]
Before the addition of the prometheus API and the metrics layer, the collectd had an API to get the collectd metrics names and disable collectd registration.

Becuase of the changes in the metrics, this is no longer working.

Going forward, there are two alternatives:
1. implementing a control API on the metric layer
2. allow to pick and choose specific metrics 

we decided to go with the second one, so we probably should discard this API (or at least limit its functionality)

**Comment by slivne** [comment]
@avikivity / @tzach - can we drop the rest collected api - AFAIK we have not released the API and no one is using this.

**Comment by tzach** [comment]
We do not know that nobody is using it.
Let's start by calling it deprecated for one release, giving users a chance to move away from it.

**Comment by amnonh** [comment]
We do, it's not working for a long time,

The only one that ever used it, is me when I was testing things in the
collectd.

**Comment by tzach** [comment]
> We do, it's not working for a long time

From which release?

**Comment by amnonh** [comment]
it's not working at least from 1.7, no one ever used that API

**Comment by tzach** [comment]
@amnonh you are talking about REST API to control Collectd
I was talking about the collectd metric protocol itself.
The first probably not in used
The second is in use, for example with scyllatop

I'm fine with dropping the first
I'm fine with deprecating the second in the future.

**Comment by slivne** [comment]
@amnonh - lets remove this
