### ISSUE TITLE
latency metrics should be disabled in 2.0

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#2701]
In machines with many cores and many column families, the per column family latency histogram can impact the overall performance.

They should be disabled

**Comment by dorlaor** [comment]
Ouch. Why can't we aggregate the latency numbers per table and not do them
per core?
Exactly like the node tool? We should also have active latency, not just
histogram.

This is very important and basic for a database with performance focus.

**Comment by glommer** [comment]
@dor we have many latency metrics in many places. A lot of them will be
kept. The ones we are disabling here are the per-CF ones only.

That said, for the ones we do keep, I am still unhappy about how they get
exported. The histograms are really hard to consume from grafana

**Comment by amnonh** [comment]
It's true that histogram are a bit more tricky to use, but Prometheus does support some useful functions for them:
https://prometheus.io/docs/practices/histograms/

And specifically:
https://prometheus.io/docs/practices/histograms/#quantiles

**Comment by dahankzter** [comment]
The quantiles are fantastic. Having the 95- 99 percentiles can be super
useful.

I would not sacrifice much performance for them but still they are very
nice to have.

tors 17 aug. 2017 kl 09:00 skrev Amnon Heiman <notifications@github.com>:

**Comment by glommer** [comment]
That is great info. I will play a bit with them

**Comment by amnonh** [comment]
not merged yet, discussion still on the mailing list

**Comment by amoskong** [comment]
Verified the fix on `2.0.rc4-0.20170903.6e6de34`.

Test method:
1. Update scylla.yaml to enable column family metrics
 `enable_keyspace_column_family_metrics: 'true'`
2. cleanup prometheus data, and restart prometheus, check metrics list
3. disable column family metrics in scylla.yaml
4. same as step 2

*Enable*
![image](https://user-images.githubusercontent.com/309708/30338912-d1743cfa-981f-11e7-992a-344b18b82a1a.png)

*Disable*
![image](https://user-images.githubusercontent.com/309708/30338934-e69727b4-981f-11e7-8a25-d14df4ff5e6b.png)
