### ISSUE TITLE
Generating sstable sharding metadata can cause long latencies

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2707]
Installation details
Scylla version (or git commit hash): 1.6/1.7+

With the default (for 1.7) murmur3_ignore_msb_bits value of 12, the split_range_to_single_shard requires 4MB of contiguous memory (4096 shards * 100 bytes per partition_range). This can cause cache evictions if memory is fragmented.

**Comment by avikivity** [comment]
Er, the math is wrong - 100*4096 = 400k.

**Comment by glommer** [comment]
400k is still pretty large

**Comment by avikivity** [comment]
It's just 2 lsa segments.
