### ISSUE TITLE
Isolate large partitions in their own summary entry

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2712]
*Installation details*
Scylla version (or git commit hash): 1.3

Reading the index page for a small partition involves reading all of its entries (less so with the new index_reader). Large partitions have a low footprint in the index; if we isolate them to their own summary entry (index page), we still get a small summary, and any small partitions around don't suffer.

**Comment by slivne** [comment]
did 8726ee937da24a1d4a20bf73d98cd434b237027e fix this ?

**Comment by raphaelsc** [comment]
@slivne: it does

**Comment by avikivity** [comment]
Not completely, we can still have an index page that contains a mix of small and large partitions, with the small ones in front. However with #2981 it may not matter.
