### ISSUE TITLE
Merging of large partition versions in MVCC is inefficient

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2715]
If readers are short-lived relative to the time it takes to fill a memtable (likely), we will have small versions at the front and a big one at the back. Current merging in `partition_snapshot::merge_partition_versions()` merges older into newer, which is O(src mutation size). This makes merging very inefficient if we accumulated a large partition. We should merge smaller partition into larger one, while preserving asymmetry of the merging operator.

I observed this causing large latencies in `perf_cache_eviction -c1 -m4G` after reads start to miss:

Before:
```
rd/s: 9, wr/s: 71369, ev/s: 0, pmerge/s: 0, miss/s: 7, cache: 472/555 [MB], LSA: 532/627 [MB], std free: 3411 [MB]

reads : min: 124   , 50%: 8239  , 90%: 11864 , 99%: 11864 , 99.9%: 11864 , max: 11864  [us]
writes: min: 3     , 50%: 4     , 90%: 4     , 99%: 6     , 99.9%: 4768  , max: 5722   [us]
```

After:
```
rd/s: 3, wr/s: 49663, ev/s: 0, pmerge/s: 0, miss/s: 3, cache: 0/0 [MB], LSA: 338/402 [MB], std free: 70 [MB]

reads : min: 315852, 50%: 315852, 90%: 379022, 99%: 379022, 99.9%: 379022, max: 379022 [us]
writes: min: 3     , 50%: 4     , 90%: 4     , 99%: 5     , 99.9%: 17    , max: 379022 [us]
```

![screenshot from 2017-08-21 16-18-49](https://user-images.githubusercontent.com/283695/29523325-f6beb0ac-868c-11e7-9bc9-c027d7467ea1.png)

**Comment by tgrabiec** [comment]
Refs https://github.com/scylladb/scylla/issues/2379

**Comment by haaawk** [comment]
I'm looking into it.

**Comment by haaawk** [comment]
I'm having troubles reproducing the issue. Everytime I run the tests, latencies are good.

**Comment by tgrabiec** [comment]
It's probably because the read always hits, so they and before writes can be applied on top of them, so we only have one version ever. Do you see any `miss/s`? In my case there was a miss due to cache being evicted.

**Comment by haaawk** [comment]
I don't see any misses. I do see some pmerge though.

**Comment by tgrabiec** [comment]
@haaawk It's probably because I've changed cache to be continuous when table is created, so you will never miss unless your cache overflows and triggers eviction. Do you see cache occupancy growing?

**Comment by haaawk** [comment]
@tgrabiec It can be. I don't see cache growing at all.

**Comment by slivne** [comment]
If its related to tomek's change a simple solution is to restart the node
after there are some sstables - that will guarantee the cache can not be
started with continuous set.
