### ISSUE TITLE
[Materialized Views] MV tables do not return expected results when filtering for a specific columns

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla#2719]
MV created before insertion of data to the original table.
Original table created with the following syntax:
CREATE TABLE IF NOT EXISTS x_by_y(
    y text,
    x text,
    date timestamp,
    PRIMARY KEY ((y), date, x)
 )
    WITH CLUSTERING ORDER BY (date DESC, x DESC)
    
MV tables created as follow:
CREATE MATERIALIZED VIEW IF NOT EXISTS y_by_x AS
    SELECT * FROM x_by_y WHERE x IS NOT NULL AND y IS NOT NULL
    PRIMARY KEY ((x), date, y)
    WITH CLUSTERING ORDER BY (date DESC, y DESC)

and:

CREATE MATERIALIZED VIEW IF NOT EXISTS dates_by_x_y AS
    SELECT x, y, date FROM x_by_y WHERE x IS NOT NULL and y IS NOT NULL
    PRIMARY KEY ((x, y), date)
    WITH CLUSTERING ORDER BY (date DESC)

When looking into the information in the tables:
SELECT * from dates_by_x_y;

 x                                 | y             | date
--------------------------------------+-------------------+--------------------------
 a45daeae-a1d7-40a2-a5f3-ddcf7661ed9a |     alice@abc.com | 2017-08-04 08:57:00+0000
 459724d8-7b9d-23ab-a4b1-51b81e795726 |  bob@abc.com | 2017-08-04 04:57:00+0000
 11602c57-0853-4118-bd8d-333717f524e1 | charlie@abc.com | 2017-06-11 13:36:19+0000
 705e3dc3-08c7-4ea2-8bb7-4bb22ebb9c2c |  dan@abc.com | 2017-08-05 16:58:00+0000
 705e3dc3-08c7-4ea2-8bb7-4bb22ebb9c2c |  dan@abc.com | 2017-08-04 09:57:00+0000
 705e3dc3-08c7-4ea2-8bb7-4bb22ebb9c2c |  dan@abc.com | 2017-08-04 06:57:00+0000
 a45daeae-a1d7-40a2-a5f3-ddcf7661ed9a |      echo@abc.com | 2017-08-04 06:57:00+0000
 a45daeae-a1d7-40a2-a5f3-ddcf7661ed9a |       frank@abc.com | 2017-08-04 23:57:00+0000
 e98b9fb9-e205-4555-bddf-fed2056f6203 | gorge@abc.com | 2017-04-09 13:36:03+0000

(9 rows)
 SELECT x, y, date from dates_by_x_y WHERE x = '705e3dc3-08c7-4ea2-8bb7-4bb22ebb9c2c' AND y = 'dan@abc.com';

 x | y  | date
------+-------+------

(0 rows)
 SELECT * from dates_by_x_y WHERE x = 'a45daeae-a1d7-40a2-a5f3-ddcf7661ed9a' AND y = 'alice@abc.com';

 x | y | date
------+-------+------

(0 rows)

**Comment by tomer-sandler** [comment]
Bugs found on 2.0 RC1 and reproduced by the customer also on 2.0 RC2

**Comment by duarten** [comment]
Works for me in master. Also, the issue is a bit strange, and only tangentially related to MVs since there is no special handling for materialized views in the read side.

**Comment by slivne** [comment]
@roydahan - can we please validate this on 2.1

**Comment by slivne** [comment]
MV is experimental in 2.1 - we will test this as part of 2.2 (it should not block 2.1)

**Comment by duarten** [comment]
Any progress on this? Seems we should close this as stale (and the problem doesn't seem related to MVs).

**Comment by roydahan** [comment]
@juliayakovlev is verifying on 2.1

**Comment by juliayakovlev** [comment]
The bug is not reproduced in 2.1
Tested using Amazon EC2 AMI (us-east-1, ami-5bb55626).
