### ISSUE TITLE
networking configuration may not match the cpuset.conf after the upgrade

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#2725]
*Installation details*
Scylla version (or git commit hash): branch-2.0 (a98e3aec45075ace83208f83cf8523ebcccdb2ba)

*Description*
The scylladb/seastar cfe280cdd8f9e19fdfbfd17c3e496e33a7227ea5 commit may cause a change in a decision about the networking mode configuration for certain setups.
As a result the cpuset.conf generated by a previous scylla version may not match the networking mode configured by the perftune.py after the upgrade and result in a significantly suboptimal performance.

**Comment by avikivity** [comment]
It looks like I misunderstood the problem.

I thought that the change in perftune would cause Scylla 2.0 to start with a different number of shards than 1.7. But it looks like the number of shards was already persistent. There is still the problem in the issue description, but it's not a resharding problem. Can you confirm?

**Comment by vladzcloudius** [comment]
@avikivity You got it absolutely right. The only issue we have is the possibly suboptimal performance due to networking configuration  inconsistent with the cpuset.conf content created by the initial scylla installation.

Re-sharding was prevented when cpuset.conf was introduced for the first time (day0?).

**Comment by avikivity** [comment]
> @avikivity You got it absolutely right. 

That means I got it absolutely wrong before :(

**Comment by avikivity** [comment]
Yes, no question.
