### ISSUE TITLE
[bug] INSERT data with same primary key

### ISSUE THREAD

**Issue by liuzheng712** [scylladb/scylla#2727]
*Installation details*
Scylla version (or git commit hash): docker scylladb/scylla:latest              HASH: 4f2cd3bc046c        3 weeks ago
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CoreOS stable (1409.7.0)

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): docker
Hardware: sockets= cores=32 hyperthreading= memory=56G
Disks: (SSD/HDD, count)
SSD 1T

Just for test the cql, but when primary key is the same, the `INSERT INTO` became `UPDATE`, using `IF NOT EXISTS` will throw an error `ServerError: Not implemented: LWT`

```
cqlsh:demodb> CREATE TABLE bigrow (id uuid,rowname varchar,PRIMARY KEY (id));
cqlsh:demodb> INSERT INTO bigrow (id , rowname) VALUES (9697c0bf-24ad-4ada-b2ae-17b95586cf4a,'test333') IF NOT EXISTS;
ServerError: Not implemented: LWT
cqlsh:demodb> INSERT INTO bigrow (id , rowname) VALUES (9697c0bf-24ad-4ada-b2ae-17b95586cf4a,'test333') ;
cqlsh:demodb> select * from bigrow;

 id                                   | rowname
--------------------------------------+---------
 9697c0bf-24ad-4ada-b2ae-17b95586cf4a | test333

(1 rows)
cqlsh:demodb> INSERT INTO bigrow (id , rowname) VALUES (9697c0bf-24ad-4ada-b2ae-17b95586cf4a,'test33cc3') ;
cqlsh:demodb> select * from bigrow;

 id                                   | rowname
--------------------------------------+-----------
 9697c0bf-24ad-4ada-b2ae-17b95586cf4a | test33cc3

(1 rows)
```

**Comment by penberg** [comment]
Scylla does not support light-weight transactions (LWT), which are required for the `IF NOT EXISTS` syntax you are using above. See https://github.com/scylladb/scylla/issues/1359 for more discussion on supporting LWT.

**Comment by avikivity** [comment]
In CQL, UPDATE and INSERT are nearly equivalent. It is expected that two INSERTs with the same primary key will end up writing the same row.

**Comment by liuzheng712** [comment]
Thanks all, so I need to keep the primary key global uniq by myself?
That is a little stupid...

**Comment by penberg** [comment]
Since you are already using UUID type for your primary key, you could use the `uuid()` CQL function to generate an ID for you as follows:

```cql
INSERT INTO bigrow (id, rowname) VALUES (uuid(), 'foo') ;
```

**Comment by liuzheng712** [comment]
@penberg you sure the uuid() is uniq?
we have billions data per day.

**Comment by avikivity** [comment]
The second "u" in uuid stands for "unique".

**Comment by penberg** [comment]
The `uuid()` CQL function generates a [Type 4 UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_.28random.29), which has 122 randomly generated bits. The chance of UUID collision is very, very low, but you know your application requirements better to make that decision.
