### ISSUE TITLE
sstable mutation reader doesn't handle empty set of row ranges

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2734]
Such queries can be issued by counter updates which involve only static row.

Causes failure in `test_query_only_static_row` invoked from `sstable_mutation_test`. See commit 6572f384502ba6677889f9984fdf7595c49311d5, which fixed the problem in cache reader.

**Comment by tzach** [comment]
@tgrabiec is it a regression from 1.7 ?

**Comment by tgrabiec** [comment]
@tzach Yes.
