### ISSUE TITLE
M4 instance type is not supported for Scylla AMI, yet it's not printed upon login to the VM

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla#2739]
*Installation details*
Scylla version (or git commit hash): 2.0 RC2 (AMI)
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): AMI (AWS)

*Hardware details* 
Platform (physical/VM/cloud instance type/docker): M4.2XL
Disks: EBS

This is what I saw upon login to the M4.2XL machines on AWS, after deploying them with Scylla 2.0 RC2 AMI. According to Eyal, there should be some indication that this is a non-supported instance type, but I don't see it.

```
[Tomer.DESKTOP-L5VEDC1] ➤ ssh -i tomer-key-aws.pem centos@54.162.184.114
X11 forwarding request failed on channel 0
Last login: Mon Aug 28 17:08:28 2017 from 84.94.46.131

   _____            _ _       _____  ____
  / ____|          | | |     |  __ \|  _ \
 | (___   ___ _   _| | | __ _| |  | | |_) |
  \___ \ / __| | | | | |/ _` | |  | |  _ <
  ____) | (__| |_| | | | (_| | |__| | |_) |
 |_____/ \___|\__, |_|_|\__,_|_____/|____/
               __/ |
              |___/


Nodetool:
        nodetool help
CQL Shell:
        cqlsh
More documentation available at:
        http://www.scylladb.com/doc/
By default, Scylla sends certain information about this node to a data collection server. For information, see http://www.scylladb.com/privacy/

    Constructing RAID volume...

Please wait for setup. To see status, run
 'systemctl status scylla-ami-setup'

After setup finished, scylla-server service will launch.
To see status of scylla-server, run
 'systemctl status scylla-server'
```

**Comment by tzach** [comment]
@syuu1228 shouldnt we get the `scylla_io_setup`  message here?

See #2879

**Comment by glommer** [comment]
It seems to me that the issue is that at this particular point in time we
haven't yet reached a point far enough in the setup in which we can declare
the instance as not supported.
Maybe we can move the tests earlier
