### ISSUE TITLE
Scylla AMI: Add User Data option to disable Scylla automatic launch

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2742]
*Installation details*
Scylla version (or git commit hash): 2.0
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Allow the user to launch a Scylla AMI without starting Scylla. This makes a configuration change before launching Scylla easier.

**Comment by tzach** [comment]
the option already exists (but not documented)
```
--stop-services
```

**Comment by glommer** [comment]
Hi Tzach

--stop services only creates a file, ami_disabled. But I don't see that
file being read anywhere. Can you please enlighten me as to how this works ?

**Comment by tzach** [comment]
@glommer I tested, and its working. That's all I know.
