### ISSUE TITLE
Instance fails to boot normally and is inaccessible on AWS after start/stop cycle

### ISSUE THREAD

**Issue by siculars** [scylladb/scylla#2749]
When installing Scylla manually via scylla_setup, instance will become inaccessible if mount fails to locate ephemeral disk.

scylla_setup calls scylla_raid_setup with --update-fstab by default which causes mount to mount a drive that does not exist after an AWS stop/start cycle. AWS will preserve ephemeral disks (ebs, nvme) through warm reboots but not through a start/stop cycle. This causes the instance to hang and not be ssh'able after a stop/start cycle in AWS. 

https://github.com/scylladb/scylla/blob/0f9b095867b37bc86fb343af34e7e4be93ec03ca/dist/common/scripts/scylla_setup#L416

If you manually comment out the line in fstab after executing scylla_setup and running through a start/stop cycle the instance will come back and you will be able to ssh to it.

The AMI setup, on the other hand, does not pass --update-fstab to scylla_raid_setup. Either way the AMI installation will call scylla_ami_setup on every boot which will recreate the raid0 and mount /var/lib/scylla .

--update-fstab should not be a thing. It causes your instance to be unavailable via ssh if your disk isnt there. Mounting drives should be executed after boot and before scylla startup like scylla_ami_setup.service.

**Comment by slivne** [comment]
stop / starting an instance with ephemeral drives is not a "common" task - as the user will loose the data - and the user knows that.

on the other hand stop/starting an instance with EBS may be done and we should survive that.

as such marking this low

**Comment by siculars** [comment]
It's one thing to lose data, it's another thing to not have access to your instance. The way scylla_setup setups the instance, you lose access to the instance and are not able to ssh to it.

**Comment by avikivity** [comment]
Fixed by e6e43594142fc484da3e6397e2893ba181bee3cc.
