### ISSUE TITLE
AMI: "yum update" fails on 2.0-rc3 AMI image

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#2751]
Seems like amzn kernel on our AMI has a dependency issue, we get following error while running "yum update":

```
--> Processing Dependency: /sbin/new-kernel-pkg for package: kernel-4.9.17-8.31.amzn1.x86_64
--> Finished Dependency Resolution
Error: Package: kernel-4.9.17-8.31.amzn1.x86_64 (@amzn-main)
           Requires: /sbin/new-kernel-pkg
           Removing: grubby-8.28-17.el7.x86_64 (@base)
               Not found
           Updated By: grubby-8.28-21.el7_3.x86_64 (updates)
               Not found
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

**Comment by avikivity** [comment]
Let's pin the kernel version so it doesn't get updated, as a workaround.

We can then look for a better solution.

Isn't our current kernel 4.4?

**Comment by syuu1228** [comment]
@avikivity Currently we specifies latest version(2017.03 now) of amzn repo, so it fetches 4.9 kernel:
https://github.com/scylladb/scylla-ami/blob/master/amzn-main.repo#L3
Should we stick to kernel 4.4.x(2016.09) at least for release 2.0?

**Comment by avikivity** [comment]
Since we tested with 4.9, let's stick with it. But pin it so `yum update` doesn't complain.

**Comment by syuu1228** [comment]
@avikivity I've found we can avoid the issue by preinstalling grubby (patch sent), should we still need to exclude amzn kernel from 'yum update'?

**Comment by avikivity** [comment]
No, if you have a fix, then we can keep the current behavior.
