### ISSUE TITLE
TLS server socket may become inacssesible because of one bad client

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#2753]
*Installation details*
Scylla version (or git commit hash):  1006a946e8fe7966054966f593e277c8c00946e0

tls::accept() runs handshake in the foreground, so no other accept is possible while handshake is executed. One buggy client may kill a server.

**Comment by gleb-cloudius** [comment]
Corresponding seastar issue:  https://github.com/scylladb/seastar/issues/335

**Comment by tzach** [comment]
@gleb @slivne is it a regression?
If not, we can push the fix to 2.1

**Comment by slivne** [comment]
closing as the seastar issue was closed.
