### ISSUE TITLE
Coordinator-side speculative retry (for percentile settings)

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2757]
If a replica fails, then requests targeting it will time out. The will cause a huge increase in latency, and a huge drop in throughput if client concurrency is bounded.

**Comment by gleb-cloudius** [comment]
> If a replica fails, then requests targeting it will time out. The will cause a huge increase in latency, and a huge drop in throughput if client concurrency is bounded.
> 
The code is all there (this is why it will only cause increase in
latency to 2.5 second and not failure). The only thing that is missing
is latency statistics for a CF (the code just uses timeout/2, in the
Origin CF provides latency statistics).

--
			Gleb.

**Comment by avikivity** [comment]
Good, then it should be easy to implement.

**Comment by gleb-cloudius** [comment]
> Good, then it should be easy to implement.
Given the function to get 99%il latency for a CF should be one liner. Do
we have one?

--
			Gleb.

**Comment by avikivity** [comment]
Are `ALWAYS` and `3ms` implemented?

**Comment by avikivity** [comment]
> Given the function to get 99%il latency for a CF should be one liner. Do
we have one?

I think we do collect these statistics.

**Comment by gleb-cloudius** [comment]
On Sun, Sep 03, 2017 at 10:13:24AM +0000, Avi Kivity wrote:
> Are `ALWAYS` and `3ms` implemented?
> 
Yes.

--
			Gleb.

**Comment by amnonh** [comment]
There is an estimated_histogram object for each CF, it can be used to calculate percentile estimation.
It actually has a percentile function, but It was never used, so take a look at the output to make sure it makes sense.

**Comment by gleb-cloudius** [comment]
On Mon, Sep 04, 2017 at 06:44:26AM -0700, Amnon Heiman wrote:
> There is an estimated_histogram object for each CF, it can be used to calculate percentile estimation.
> It actually has a percentile function, but It was never used, so take a look at the output to make sure it makes sense.
> 
Actually I do not think what we have now is good enough. It measure
latencies of local access, not latencies as seen by a coordinator.
Apache(tm) Cassanda(tm) uses CoordinatorReadLatency for speculative
retry.

--
			Gleb.
