### ISSUE TITLE
scylla-server.service can start before its mount point is ready

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2767]
If we mount a filesystem, the scylla service should depend on it. Can be done via systemd mount units.

**Comment by slivne** [comment]
@syuu1228 / @penberg - is this solved by https://github.com/scylladb/scylla/commit/ff55e3c247a91ba5139f71f6e4ec6eef84563b76

**Comment by avikivity** [comment]
@slivne yes. Note if the user bypasses scylla_raid_setup they are at risk (but they can add the RequireMountsFor themselves).

**Comment by avikivity** [comment]
Fixed by https://github.com/scylladb/scylla/commit/ff55e3c247a91ba5139f71f6e4ec6eef84563b76

**Comment by slivne** [comment]
@tzach Do you want to add a comment in the docs for https://github.com/scylladb/scylla/issues/2767#issuecomment-636824503
