### ISSUE TITLE
collectd gets the same metric twice

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#2770]
Version 2.0
During testing, I get warning such as: 

Sep 07 07:56:58 ip-172-30-0-93 collectd[2807]: uc_update: Value too old: name = ip-172-30-0-93/execution_stages-0/derive-function_calls_enqueued-cql3_modification; value time = 1504771018.000; last cache update 
S

This means that the collectd get the same metric twice, most likely because two metrics appear to have the same name (missing label or problem with labels)

**Comment by slivne** [comment]
@amnonh was this fixed ?

**Comment by amnonh** [comment]
On Wed, Sep 13, 2017 at 3:32 PM, Shlomi Livne <notifications@github.com>
wrote:

> @amnonh <https://github.com/amnonh> was this fixed ?
>
no, didn't find the root cause yet

**Comment by slivne** [comment]
@amnonh so please do work on finding it and fixing it

**Comment by avikivity** [comment]
Seen again with 2.1rc2:

```
Jan 22 15:33:08 longevity-1tb-7d-2-1-db-node-ef77397b-0-1 collectd[962]: uc_update: Value too old: name = longevity-1tb-7d-2-1-db-node-ef77397b-0-1/database-1/gauge-queued_reads-reads; value time = 1516635188.000; la
```

**Comment by slivne** [comment]
@amnonh  ?

**Comment by amnonh** [comment]
The relevant commit is there,
I'll check
