### ISSUE TITLE
Track (and restrict) the resource consumption of index readers

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#2778]
After #2692 is merged we'll have memory-consumption based tracking and restriction of sstable readers. However index readers continue to fly under the radar, consuming all the memory they desire.

Implementation is complicated by the fact that index readers can be shared between multiple readers. See some related discussion at the review of #2692's [patch-set](https://groups.google.com/d/topic/scylladb-dev/UM1g_F2-1Tw/discussion).

/cc @avikivity 
/cc @tgrabiec

**Comment by tzach** [comment]
@avikivity @tgrabiec ping

**Comment by denesb** [comment]
@avikivity I think we should close this. We already track I/O buffers used by index reads. While we don't track every aspect of index reads, we shouldn't strive to, unless a certain aspect turns out to be problematic, in which case we should open a specific issue for it.

Restricting is not something we will do anyway.
