### ISSUE TITLE
Trying to invoke a second rebuild while another is running - will cause the node to shutdown

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#2780]
*Installation details*
Scylla version (or git commit hash): 1.6

invoking a second rebuild will cause a node to shutdown 

```
Aug 17 20:07:56 adcd02 scylla:  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Operation rebuild is in progress, try again)
```

we need to catch the exception and return the result to nodetool

**Comment by asias** [comment]
I think this problem is already fixed.

$ nodetool rebuild
nodetool: Scylla API server HTTP POST to URL '/storage_service/rebuild' failed: Operation rebuild is in progress, try again
See 'nodetool help' or 'nodetool help <command>'.

**Comment by asias** [comment]
@slivne  ^^^

**Comment by slivne** [comment]
@asias can you provide the commit id ? - it would be good to know in which version we fixed it.

**Comment by nirmaayan** [comment]
@asias ping

**Comment by asias** [comment]
I am not sure which version propagated the exception correctly to nodetool. The code for rebuild is doing this correctly in the first place. Maybe @amnonh knows.

**Comment by amnonh** [comment]
There are two things here, the API always catches the exception from the beginning.
There were different patches that changes how it is shown in the nodetool.

But regardless of how it is shown, it should not cause the node to shutdown

**Comment by asias** [comment]
@amnonh FYI, the node to shutdown issue is gone. shlomi is asking for the commit id fixed the problem.

**Comment by nirmaayan** [comment]
@asias @amnonh on which version we have the fix?

**Comment by amnonh** [comment]
@nirmaayan It's kind of confusing, a failure in the API should not cause the node to crash, that's from the beginning, there were some changes in how errors are propagated, but it's not something that would cause the node to shutdown.

@asias says that from the repair perspective there also no changes

**Comment by slivne** [comment]
@roydahan - lets add a dtest to validate that second rebuild will not cause a node to crash

f371d1788 seems to be working correctly - that is the second nodetool rebuild fails with ```Operation rebuild is in progress, try again```

**Comment by tzach** [comment]
@roydahan any update of the dtest for this issue?

**Comment by roydahan** [comment]
not yet.
