### ISSUE TITLE
mutation_write_timeout_exception in longevity test running materialized views workload

### ISSUE THREAD

**Issue by larisau** [scylladb/scylla#2783]
*Installation details*
Scylla version (or git commit hash):
Cluster size: 4 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): gce

cassandra stress command:
cassandra-stress user profile=/tmp/cs_mv_profile.yaml ops'(insert=3,read1=1,read2=1,read3=1)' cl=QUORUM duration=10080m -port jmx=6868 -mode cql3 native -rate threads=100

[cs_mv_profile_yaml.txt](https://github.com/scylladb/scylla/files/1292119/cs_mv_profile_yaml.txt)

[scylla-2.0-longevity-1TB-gce-part.gz](https://github.com/scylladb/scylla/files/1292129/scylla-2.0-longevity-1TB-gce-part.gz)

**Comment by duarten** [comment]
How many servers were involved? Is it possible to get scylla logs? I see some errors related to the device being out of space.

**Comment by roydahan** [comment]
@larisau

**Comment by duarten** [comment]
Closing in favour of #3080.
