### ISSUE TITLE
Scylla AMI not able to create device

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#2784]
*Installation details*
Scylla version (or git commit hash): AMI - 2.0.RC4
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-1597816e
Instance c3.large

```
.
.
Sep 10 17:36:43 ip-172-31-20-163 scylla_ami_setup[2690]: mdadm: Defaulting to version 1.2 metadata
Sep 10 17:36:43 ip-172-31-20-163 kernel: md: could not open unknown-block(202,16).
Sep 10 17:36:43 ip-172-31-20-163 kernel: md: md_import_device returned -16
Sep 10 17:36:43 ip-172-31-20-163 scylla_ami_setup[2690]: mdadm: ADD_NEW_DISK for /dev/xvdb failed: Device or resource busy
```

could it be related to the following http://dev.bizo.com/2012/07/mdadm-device-or-resource-busy.html

complete log [journal.log.txt](https://github.com/scylladb/scylla/files/1292150/journal.log.txt)

**Comment by tzach** [comment]
@syuu1228 can you please take a look?

**Comment by syuu1228** [comment]
Patch is on ML, but haven’t reviewed for long time: “[PATCH scylla v2] dist/common/scripts/scylla_raid_setup: prevent 'device or resource busy' on creating mdraid device”
