### ISSUE TITLE
nodetool refresh error

### ISSUE THREAD

**Issue by zhiguoxu** [scylladb/scylla#2786]
*Installation details*
Scylla version (or git commit hash):1.5
Cluster size:1
OS (RHEL/CentOS/Ubuntu/AWS AMI):centos7.3

1. cp /path/to/snapshot/* /var/lib/scylla/data/test/simple/upload/
2. nodetool refresh test simple
the 2 step cause a error:
"nodetool: Scylla API server HTTP POST to URL '/storage_service/sstables/test' failed: Storage I/O error: 1: Operation not permitted"
How can I fix it ?

**Comment by gleb-cloudius** [comment]
On Mon, Sep 11, 2017 at 08:56:56PM -0700, zhiguoxu wrote:
> *Installation details*
> Scylla version (or git commit hash):1.5
> Cluster size:1
> OS (RHEL/CentOS/Ubuntu/AWS AMI):centos7.3
> 
> 1. cp /path/to/snapshot/* /var/lib/scylla/data/test/simple/upload/
> 2. nodetool refresh test simple
> the 2 step cause a error:
> "nodetool: Scylla API server HTTP POST to URL '/storage_service/sstables/test' failed: Storage I/O error: 1: Operation not permitted"
> How can I fix it ?
> 
Check that files in upload have correct permissions.

--
			Gleb.

**Comment by avikivity** [comment]
Note that 1.5 is no longer supported.
