### ISSUE TITLE
Gossip listener may take a long time to process new endpooint state map

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2787]
`gossiper::apply_state_locally()` calls `handle_major_state_change()` for each endpoint, in a seastar thread, which calls `mark_alive()` for new nodes, which calls `ms().send_gossip_echo(id).get()`. So it synchronously waits for each node to respond before it moves on to the next entry. As a result it may take a while before whole state is processed. 

Apache (tm) Cassandra (tm) sends echos in the background.

**Comment by gleb-cloudius** [comment]
Why it waits for a reply at all? It should be no reply message. To late
to change it now.

--
			Gleb.

**Comment by asias** [comment]
The handler of the echo message does nothing but returning a ready future. if we do not wait for it how can we know peer has received the echo message.

**Comment by gleb-cloudius** [comment]
On Wed, Sep 13, 2017 at 12:20:39AM -0700, Asias He wrote:
> The handler of the echo message does nothing but returning a ready future. if we do not wait for it how can we know peer has received the echo message.
> 
Do we use this information in any way? The node is dead if its
generation number is not update for a long time, not when echo message
cannot be sent, no?

--
			Gleb.

**Comment by asias** [comment]
echo message is used only when we want to mark a node as UP from DOWN. This implies we 1) we have received the update (the update can reach this node indirectly) 2) we have managed to send a direct message to that node

**Comment by gleb-cloudius** [comment]
On Wed, Sep 13, 2017 at 07:40:38AM +0000, Asias He wrote:
> echo message is used only when we want to mark a node as UP from DOWN. This implies we 1) we have received the update (the update can reach this node indirectly) 2) we have managed to send a direct message to that node
> 
I see. I thought the ACK message is the one that propagates updates. In
that case the code should be parallelised, instead of working node by
node sequentially.

--
			Gleb.
