### ISSUE TITLE
Repair - support addition options

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#279]
from #79

Currently (after my latest patch), the "ranges" and "primaryRanges" options are supported, as well as the default (all ranges). The other options - "parallelism", "incremental", "jobThreads", "columnFamilies", "dataCenters", "hosts" and "trace", are silently ignored.

**Comment by slivne** [comment]
from @tzach: 
columnFamilies, dataCenters, hosts are needed for GA

**Comment by nyh** [comment]
columnFamilies option is now supported. Still working on the other two.

**Comment by nyh** [comment]
"hosts" and "dataCenters" (-hosts and -dc in nodetool) now work too.

**Comment by tzach** [comment]
@slivne @nyh we can close this issue.  We will open a new issue for non supported options once and if we recognize them as important
