### ISSUE TITLE
Range scans of small tables on large clusters can time out

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#2792]
If a table has a small number of rows overall (say, a few thousand) distributed over a large-ish cluster (say 50 nodes), then queries are likely to time out. There will be 50*256 = 12,800 vnodes to scan, and if each scan takes 1ms, the whole query takes 12.8 seconds. The only thing that can save us is small page size as we will stop earlier.

**Comment by avikivity** [comment]
Possible fix: increase the number of scanned vnodes exponentially. The number of scans then reduces to log2(12,800) = 40. We will need to sort the results from the parallel scans, or perhaps issue each vnode scan in a separate RPC call (but send those RPCs in parallel).

**Comment by avikivity** [comment]
Note: we had the same problem when scanning shards within a node, fixed in a1cafed3701604c818609350fde504b81850b832.

**Comment by gleb-cloudius** [comment]
This is a dup of #1230. Given proper implementation of
estimate_result_rows_per_range() the current code will do all that is
needed to query multiple vnodes in parallel.

--
			Gleb.

**Comment by avikivity** [comment]
Close dup
