### ISSUE TITLE
be more informative with I/O error messages

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#2793]
When we find an I/O error, we print the following message to the logs:

```
      "Shutting down communications due to I/O errors until operator intervention"
```

This message really doesn't help the user much. We should ideally augment the infrastructure around it to allow recording which file generated the error. At the very least, we can say if the error came from the commitlog or data files.

**Comment by avikivity** [comment]
Since we intercept file API calls, this should not be too hard.

**Comment by tzach** [comment]
ping @slivne
