### ISSUE TITLE
WARNING: closing file in reactor thread during exception recovery

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#28]
Please fix or quiet this warning. It is too noise. 

WARNING: closing file in reactor thread during exception recovery
WARNING: closing file in reactor thread during exception recovery
WARNING: closing file in reactor thread during exception recovery
WARNING: closing file in reactor thread during exception recovery
WARNING: closing file in reactor thread during exception recovery
WARNING: closing file in reactor thread during exception recovery
WARNING: closing file in reactor thread during exception recovery
WARNING: closing file in reactor thread during exception recovery
WARNING: closing file in reactor thread during exception recovery
WARNING: closing file in reactor thread during exception recovery
WARNING: closing file in reactor thread during exception recovery
WARNING: closing file in reactor thread during exception recovery

**Comment by penberg** [comment]
Fixed by https://github.com/scylladb/seastar/commit/64442081ef9ea39eb94037a78725f92b894d9330.
