### ISSUE TITLE
Cap compaction speed

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#280]
When I run a simple write stress against the Intel setup with plenty of CPUs we get performance
spikes due to compaction. The correlation is clear - when compaction doesn't run the throughput of
10 threads is around 88k and great latency. On compaction it drops to the floor. In the past it wasn't
like this so I guess we need to slow it down. The server is definitely idle in terms of memory and cpu.

@raphaelsc, @glommer @avikivity knock yourself out :)

Server cmdline:
sudo build/release/scylla --network-stack native --dpdk-pmd --dhcp 0 --host-ipv4-addr 1.1.1.1  --gw-ipv4-addr 1.1.1.2 --netmask-ipv4-addr 255.255.255.0 --collectd 1 --collectd-address 1.1.1.2:25826 --smp 20  --datadir /data --commitlog-directory  /data --default-log-level info --options-file conf/scylla.yaml --hugepages /dev/hugepages -m 20G --collectd-hostname=intel1

Compaction output:

INFO    [shard 5] compaction - Compacting [/data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7805-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7825-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7785-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7845-Data.db:level=0, ]
INFO    [shard 2] compaction - Compacting [/data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7842-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7802-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7782-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7862-Data.db:level=0, ]
INFO    [shard 13] compaction - Compacting [/data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7833-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7813-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7793-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7853-Data.db:level=0, ]
INFO    [shard 5] compaction - Compacted 4 sstables to [/data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7865-Data.db]. 50133224 bytes to 14892056 (~29% of original) in 1320ms = 10.7572MB/s. ~170240 total partitions merged to 50311.
INFO    [shard 2] compaction - Compacted 4 sstables to [/data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7882-Data.db]. 45861648 bytes to 14842328 (~32% of original) in 1269ms = 11.1538MB/s. ~155648 total partitions merged to 50143.
INFO    [shard 13] compaction - Compacted 4 sstables to [/data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7873-Data.db]. 50242152 bytes to 14905672 (~29% of original) in 1328ms = 10.6965MB/s. ~170496 total partitions merged to 50357.
INFO    [shard 9] compaction - Compacting [/data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7849-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7769-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7749-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7869-Data.db:level=0, ]
INFO    [shard 10] compaction - Compacting [/data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7850-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7770-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7750-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7870-Data.db:level=0, ]
INFO    [shard 16] compaction - Compacting [/data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7856-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7776-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7756-Data.db:level=0, /data/keyspace1/standard1-173c96d050a911e59d7a000000000000/keyspace1-standard1-ka-7876-Data.db:level=0, ]

HEAD - 6fe853fe7ba2d2297cf89ea24b01edad0a63a663

```
~/apache-cassandra-2.1.7/tools/bin/cassandra-stress write duration=5m  -mode native cql3  -rate threads=10 -node 1.1.1.1
Unable to create stress keyspace: Keyspace keyspace1 already exists
Sleeping 2s...
Warming up WRITE with 50000 iterations...
INFO  06:27:45 Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
INFO  06:27:45 New Cassandra host /1.1.1.1:9042 added
Connected to cluster: Test Cluster
Datatacenter: datacenter1; Host: /1.1.1.1; Rack: rack1
Failed to connect over JMX; not collecting these stats
Running WRITE with 10 threads 5 minutes
Failed to connect over JMX; not collecting these stats
type,      total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
total,         87580,   87569,   87569,   87569,     0.1,     0.1,     0.1,     0.2,     0.2,     8.6,    1.0,  0.00000,      0,      0,       0,       0,       0,       0
total,        170239,   76492,   76492,   76492,     0.1,     0.1,     0.1,     0.2,     0.2,   201.0,    2.1,  0.05072,      0,      0,       0,       0,       0,       0
total,        255347,   83623,   83623,   83623,     0.1,     0.1,     0.1,     0.2,     0.2,   200.4,    3.1,  0.03555,      0,      0,       0,       0,       0,       0
total,        342609,   84826,   84826,   84826,     0.1,     0.1,     0.1,     0.2,     0.2,   201.6,    4.1,  0.02674,      0,      0,       0,       0,       0,       0
total,        434283,   90800,   90800,   90800,     0.1,     0.1,     0.1,     0.2,     0.2,     1.0,    5.1,  0.02554,      0,      0,       0,       0,       0,       0
total,        520137,   82373,   82373,   82373,     0.1,     0.1,     0.1,     0.2,     0.2,   200.8,    6.2,  0.02130,      0,      0,       0,       0,       0,       0
total,        609745,   88380,   88380,   88380,     0.1,     0.1,     0.1,     0.2,     0.2,     5.7,    7.2,  0.01877,      0,      0,       0,       0,       0,       0
total,        693479,   82421,   82421,   82421,     0.1,     0.1,     0.1,     0.2,     0.2,    42.7,    8.2,  0.01712,      0,      0,       0,       0,       0,       0
total,        782157,   87825,   87825,   87825,     0.1,     0.1,     0.1,     0.2,     0.2,     8.2,    9.2,  0.01552,      0,      0,       0,       0,       0,       0
total,        867071,   84114,   84114,   84114,     0.1,     0.1,     0.1,     0.2,     0.2,   200.8,   10.2,  0.01409,      0,      0,       0,       0,       0,       0
total,        952181,   84442,   84442,   84442,     0.1,     0.1,     0.1,     0.2,     0.2,   200.7,   11.2,  0.01287,      0,      0,       0,       0,       0,       0
total,       1043025,   90215,   90215,   90215,     0.1,     0.1,     0.1,     0.2,     0.2,     4.6,   12.2,  0.01257,      0,      0,       0,       0,       0,       0
total,       1132212,   88454,   88454,   88454,     0.1,     0.1,     0.1,     0.2,     0.2,   200.5,   13.3,  0.01180,      0,      0,       0,       0,       0,       0
total,       1218939,   86064,   86064,   86064,     0.1,     0.1,     0.1,     0.2,     0.2,   200.3,   14.3,  0.01096,      0,      0,       0,       0,       0,       0
total,       1301840,   82238,   82238,   82238,     0.1,     0.1,     0.1,     0.2,     0.2,    46.7,   15.3,  0.01023,      0,      0,       0,       0,       0,       0
total,       1385467,   83062,   83062,   83062,     0.1,     0.1,     0.1,     0.2,     0.2,   200.7,   16.3,  0.00983,      0,      0,       0,       0,       0,       0
total,       1475701,   89415,   89415,   89415,     0.1,     0.1,     0.1,     0.2,     0.2,     4.2,   17.3,  0.00953,      0,      0,       0,       0,       0,       0
total,       1565207,   88679,   88679,   88679,     0.1,     0.1,     0.1,     0.2,     0.2,     5.5,   18.3,  0.00914,      0,      0,       0,       0,       0,       0
total,       1654561,   88673,   88673,   88673,     0.1,     0.1,     0.1,     0.2,     0.2,     5.8,   19.3,  0.00877,      0,      0,       0,       0,       0,       0
total,       1742684,   87407,   87407,   87407,     0.1,     0.1,     0.1,     0.2,     0.2,    26.1,   20.3,  0.00835,      0,      0,       0,       0,       0,       0
total,       1832418,   88928,   88928,   88928,     0.1,     0.1,     0.1,     0.2,     0.2,     4.1,   21.3,  0.00806,      0,      0,       0,       0,       0,       0
total,       1899826,   67050,   67050,   67050,     0.1,     0.1,     0.1,     1.3,     4.7,    47.9,   22.3,  0.01183,      0,      0,       0,       0,       0,       0
total,       1913156,   13241,   13241,   13241,     0.7,     0.1,     3.8,     7.9,    51.6,   103.2,   23.3,  0.03913,      0,      0,       0,       0,       0,       0
total,       1931724,   17911,   17911,   17911,     0.5,     0.1,     3.1,     7.8,    44.3,    77.3,   24.4,  0.05092,      0,      0,       0,       0,       0,       0
total,       1957671,   25812,   25812,   25812,     0.4,     0.1,     2.1,     4.5,    46.0,    54.8,   25.4,  0.05716,      0,      0,       0,       0,       0,       0
total,       2016076,   57988,   57988,   57988,     0.2,     0.1,     0.1,     2.7,     4.8,   200.4,   26.4,  0.05634,      0,      0,       0,       0,       0,       0
total,       2104809,   88295,   88295,   88295,     0.1,     0.1,     0.1,     0.2,     0.2,     5.0,   27.4,  0.05422,      0,      0,       0,       0,       0,       0
total,       2203511,   87794,   87794,   87794,     0.1,     0.1,     0.1,     0.2,     0.2,   201.1,   28.5,  0.05225,      0,      0,       0,       0,       0,       0
total,       2291017,   86760,   86760,   86760,     0.1,     0.1,     0.1,     0.2,     0.2,    25.3,   29.5,  0.05043,      0,      0,       0,       0,       0,  
```

**Comment by avikivity** [comment]
@penberg why did the bot add the Backport candidate label to this?

**Comment by dorlaor** [comment]
Maybe compaction steals resources from the bot. #AIwars
