### ISSUE TITLE
Scylla refuse to start, report not enough memory when there is

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2803]
*Installation details*
Scylla version (or git commit hash): 1.7.4
Cluster size: 1
OS: Ubuntu 16
```
Machine type

g1-small (1 vCPU, 1.7 GB memory)
CPU platform

Intel Haswell
```

Starting Scylla result with 
```
[shard 0] init - Only 476 MiB per shard; this is below the recommended minimum of 1 GiB/shard; terminating.Configure more memory (--memory option) or decrease shard count (--smp option).
```
altho there is 1.7 RAM and only one core

```
> cat /etc/scylla.d/cpuset.conf 
#CPUSET="--cpuset 0 "
> free -m
              total        used        free      shared  buff/cache   available
Mem:           1694          98        1329           2         266        1419
Swap:             0           0           0
```

**Comment by avikivity** [comment]
Scylla leaves some memory for the OS so you can run `nodetool`.

**Comment by tzach** [comment]
@avikivity how much? 
Scylla should somehow let the user know, this is confusing and bad UX.

**Comment by avikivity** [comment]
About 1GB.

See scyllafb/scylla-tools-java#52.

**Comment by tzach** [comment]
Maybe the following will help

 Only 476 MiB per shard; this is below the recommended minimum of 1 GiB/shard; **keeping 1GB for the OS**.  Terminating. Configure more memory (--memory option) or decrease shard count (--smp option).
```

**Comment by avikivity** [comment]
Perhaps, scylla_setup can warn about this condition. It is run in the foreground with the user's attention.

```
You have too little memory for the number of logical processors (CPUs). Proceed [y/N]? Y
Reduce number of processors used [Y/n]? Y
Will use just 1 processor(s).
```

**Comment by amnonh** [comment]
On Sat, Sep 16, 2017 at 7:14 PM, Avi Kivity <notifications@github.com>
wrote:

> Perhaps, scylla_setup can warn about this condition. It is run in the
> foreground with the user's attention.
>
> You have too little memory for the number of logical processors (CPUs). Proceed [y/N]? Y
> Reduce number of processors used [Y/n]? Y
> Will use just 1 processor(s).
>
>
Note that for images, the image runs scylla_setup without any user
interaction
