### ISSUE TITLE
Schema changes are not applied atomically if failure happens during schema merge

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2805]
On schema change we write to many tables. If failure happens in the middle (process crash, exception, I/O error), we may end up with some changes applied and some not. As a result the schema may not be consistent when the node is restarted.

We should make schema change an atomic transaction, with rollback on failure.

On schema merge:
 1) disable commitlog writes for schema tables
 1) at the beginning, make a persistent snapshot of schema tables. 
 2) store the name of that snapshot in a local system table (schema_snapshot field). Any modification of that field is followed by sstable flush so that a booting node sees it before commitlog replay. If that field is set on boot, it means we failed.
 3) do the regular merge
 4) on success, clear schema_snapshot, then delete the snapshot
 5) on exception, restore from snapshot, then clear schema_snapshot

On boot, if schema_snapshot exists then restore from it, then clear schema_snapshot.

We cannot recover from a failure to restore from snapshot, so it aborts the node.

**Comment by tzach** [comment]
@tgrabiec how does Apache Cassandra handle this case?

**Comment by tgrabiec** [comment]
Cassandra 2.1.17 applies mutations targeting many tables as one atomic transaction to the commit log.

**Comment by gleb-cloudius** [comment]
When we will move to raft we will have snapshot that is stored in raft log already. It looks to me the best course of action is to abolish all the legacy schema code all together.  Make is a standard raft state machine that holds its state in memory and uses raft log for persistency. If legacy cql interface is  needed make it a virtual table.

**Comment by tgrabiec** [comment]
@gleb-cloudius Implementing virtual tables is hard, it's best done by writing to actual (maybe temporary) tables and returning a reader to them. We may as well make those tables permanent, like would be the case for user tables which use raft. 

After we have atomic multi-mutation writes to the commit log, this issue will be taken care of.

**Comment by gleb-cloudius** [comment]
On Thu, Jan 07, 2021 at 09:59:52AM -0800, Tomasz Grabiec wrote:
> @gleb-cloudius Implementing virtual tables is hard, it's best done by writing to actual (maybe temporary) tables and returning a reader to them. We may as well make those tables permanent, like would be the case for user tables which use raft. 
> 
> After we have atomic multi-mutation writes to the commit log, this issue will be taken care of.
> 
No, it will not. We need to move all schema handling related things to
shard zero and make it use a spacial partitioner to store everything on
shard zero as well (and IIRC you said that per table partitioner has
its issues too). And there are more bugs related to schema been
spread over multiple tables which can be updated independently.

What we already learned with LWT is that building on send does not give you
a linearisability even if upper layers are sound. My prediction is that
even if we will build perfect raft on top of what we have now we will
chaise a lot of issues for a lot of time in the layers below. Now we
have a chance do design something sane and provide backwards
compatibility using virtual tables. Schema state is small so having
temporary memtable should not be a bug issue if this is how we end up
implementing virtual tables.

--
			Gleb.

**Comment by tgrabiec** [comment]
After bf115e7d69b12f4ed4f208646b3eb9c02c966ec2, schema tables are owned only by shard 0.

**Comment by tgrabiec** [comment]
Fixed by 3b20407f2536de65bb599116876095bd5ec6a585
