### ISSUE TITLE
Documentation competability with cassandra

### ISSUE THREAD

**Issue by eldad87** [scylladb/scylla#2809]
Hi,
While reading the scylla documentation in order to evaluate it, it seems like an older version of Cassandra's CQL (<=2.1).

For example:
http://docs.scylladb.com/getting-started/dml/#select-statement
> Moreover, the IN relation is only allowed on the last column of the partition key and on the last column of the full primary key.

While:
https://www.datastax.com/dev/blog/a-deep-look-to-the-cql-where-clause
> Prior to 2.2, the IN restrictions could only be applied to the last column of the partition key. So, for example, if your table was:
```
CREATE TABLE numberOfRequests (
    cluster text,
    date text,
    time text,
    numberOfRequests int,
    PRIMARY KEY ((cluster, date), time)
)
```
> In 2.1, you could only use an IN operator on the date column. In 2.2 you can use the IN operator on any partition key column. By consequence, a query like:
```
SELECT * FROM numberOfRequests
    WHERE cluster IN ('cluster1', 'cluster2')
    AND date = '2015-05-06'
    AND time >= '12:00'
    AND time <= '14:00';
```
> is valid since 2.2 but is invalid in the prior releases.

And based on your [compatibility]http://www.scylladb.com/product/technology/scylla-roadmap/#cassandra-compatibility) to Cassandra/roadmap; you should already to support it.

Please advise,
Thanks!

**Comment by tgrabiec** [comment]
There is an open bug about the multi-column IN support: https://github.com/scylladb/scylla/issues/2473

**Comment by tzach** [comment]
@eldad87 I'm closing this since it is a duplication of #2473 
If you think we should improve the doc on this, please let me know, and I will do it ASAP.
Thanks
