### ISSUE TITLE
Paging doesn't work, but only on one machine?

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#2812]
Paging does usually work, and we even have dtests that test it daily in Jenkins.
However, when @larisau tried to run the paging dtests, they failed with:
```
<Error from server: code=000a [Protocol error] message="Invalid value for the paging state">
```
Running cqlsh manually on the cluster created during that dtest showed that this is not a dtest-specific problem, cqlsh also fails in the same way: If we try "paging 5; select * ...", we see the first page but when pressing enter we get that "Invalid value for the paging state".

This error is thrown in service/pager/paging_state.cc when we get a paging state which has the wrong version information or can't be deserialized. But which, and why? 

I can't reproduce this bug on my machine, despite it seems me and @larisau have the same version of gcc (6.4.1), same python driver, same cqlsh, same scylla.

**Comment by avikivity** [comment]
Things to try:
`catch throw` in gdb
`tcpdump` and examine the outgoing and incoming paging state for correctness

**Comment by tgrabiec** [comment]
@larisau Where did you get the Scylla binary from?

**Comment by larisau** [comment]
The scylla was compiled on my laptop(fedora25)

**Comment by slivne** [comment]
We need to clarify why this happens (version/driver/etc.) - if we can not do this and official versions work - then we need to close this.

Larisa - if this keeps happening - its probably a combination of driver / scylla version - please take a tcpdump as avi requested and we will try to analyze this.
