### ISSUE TITLE
Downloading file from the API cause large memory allocation

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#2816]
All version

The http allocate a bufer in the size of a file when downloading a file, this can be avoided by using output stream for file download implementation

**Comment by tzach** [comment]
When and why does anyone download a file using the API?

**Comment by amnonh** [comment]
if they are using the swagger-ui, they are downloading some of the swagger
files locally

**Comment by slivne** [comment]
@amnonh - was this solved ?

**Comment by amnonh** [comment]
it should be solved

**Comment by slivne** [comment]
@amnonh - can you please confirm its solved - reduce the threshold for memory detector access the swagger and lets see that it works ok.

**Comment by amnonh** [comment]
I've just tested it with 16MB file download,
I think we can close it
