### ISSUE TITLE
CORRECT_COUNTER_ORDER feature is enabled by default (even when COUNTERS isn't enabled)

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#2817]
*Installation details*
Scylla version (or git commit hash): 1.7.5

The default features for 1.7.5 without experimental flag are:
supported_features=RANGE_TOMBSTONES,LARGE_PARTITIONS,CORRECT_COUNTER_ORDER

Shall we have CORRECT_COUNTER_ORDER enabled by default?

(related note: according the decision here, we should test the upgrade from 1.7.4 and 1.7.5 to 2.0) with and without experimental flag.

**Comment by pdziepak** [comment]
I don't see why it shouldn't be. The flag COUNTERS is still the one that decides whether the counters are enabled. CORRECT_COUNTER_ORDER is used only to determine whether the node is capable of accepting counters with their shards correctly ordered.

**Comment by roydahan** [comment]
@slivne does...

**Comment by slivne** [comment]
ok closing this ....still strange in my view
