### ISSUE TITLE
Scylla unable to copy data from .csv

### ISSUE THREAD

**Issue by Jammink2** [scylladb/scylla#2821]
*Installation details*
Scylla version (or git commit hash): 1.7.1-0.20170607.dbbf99d
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker running on Mac OS 10.12.6

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):  Docker
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count):  SSD, 1

I've modeled the hotel  keyspace from "Cassandra The Definitive Guide", and I'm running into trouble when I try to import the .csv associated with it - 0 rows get imported.

**Here's the problematic command and result:**

cqlsh:hotel> COPY available_rooms_by_hotel_date FROM '/Users/John/Desktop/available_rooms.csv' ;
Using 3 child processes

Starting copy of hotel.available_rooms_by_hotel_date with columns [hotel_id, date, room_number, is_available].
Processed: 0 rows; Rate:       0 rows/s; Avg. rate:       0 rows/s
0 rows imported from 0 files in 0.333 seconds (0 skipped).
cqlsh:hotel> select * from available_rooms_by_hotel_date;

 hotel_id | date | room_number | is_available
----------+------+-------------+--------------

(0 rows)

********************
**cqlsh:hotel> describe available_rooms_by_hotel_date;**
CREATE TABLE hotel.available_rooms_by_hotel_date (
    hotel_id text,
    date date,
    room_number smallint,
    is_available boolean,
    PRIMARY KEY (hotel_id, date, room_number)
) WITH CLUSTERING ORDER BY (date ASC, room_number ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = 'Q4. Find available rooms by hotel / date'
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

********************
**$ less '/Users/John/Desktop/available_rooms.csv'** :

hotel_id,date,room_number,is_available
AZ123,2016-01-01,101,TRUE
AZ123,2016-01-02,101,TRUE
AZ123,2016-01-03,101,TRUE
AZ123,2016-01-04,101,TRUE
AZ123,2016-01-05,101,TRUE
AZ123,2016-01-06,101,TRUE
AZ123,2016-01-07,101,TRUE
... (57 rows)

*********************

I've noticed that I can change the .csv filename to just about anything and I get the same error.

**Comment by penberg** [comment]
Where are you running `cqlsh`? Are you sure it sees the file, which seems to be on the host?

I downloaded the CSV file from here:

https://raw.githubusercontent.com/jeffreyscarpenter/cassandra-guide/master/resources/available_rooms.csv

and I'm able to import it to Scylla:

```
cqlsh:hotel> COPY available_rooms_by_hotel_date FROM 'available_rooms.csv';
Using 7 child processes

Starting copy of hotel.available_rooms_by_hotel_date with columns [hotel_id, date, room_number, is_available].
Failed to import 1 rows: ParseError - Failed to parse date : time data 'date' does not match format '%Y-%m-%d',  given up without retries
Failed to process 1 rows; failed rows written to import_hotel_available_rooms_by_hotel_date.err
Processed: 311 rows; Rate:     559 rows/s; Avg. rate:     814 rows/s
311 rows imported from 1 files in 0.382 seconds (0 skipped).
```

**Comment by slivne** [comment]
@Jammink2 -  have you been able to import the files ? do you need further assistance ?

**Comment by Jammink2** [comment]
@penberg, @slivne  - sorry for the delay

I am not able to import it.  Fails every time.  Here's what I get:

cqlsh:hotel> select * from available_rooms_by_hotel_date;

 hotel_id | date | room_number | is_available
----------+------+-------------+--------------

(0 rows)
cqlsh:hotel> COPY available_rooms_by_hotel_date FROM '/Users/John/Desktop/available_rooms.csv' WITH HEADER=true;
Reading options from the command line: {'header': 'true'}
Using 3 child processes

Starting copy of hotel.available_rooms_by_hotel_date with columns [hotel_id, date, room_number, is_available].
Processed: 0 rows; Rate:       0 rows/s; Avg. rate:       0 rows/s
0 rows imported from 0 files in 0.315 seconds (0 skipped).

Nothing imported.  I tried also changing text fields in the csv accordingly:

[John@:John'sMacBookPro Desktop]$ head -5 available_rooms.csv
hotel_id,date,room_number,is_available
`AZ123`,2016-01-01,101,TRUE
`AZ123`,2016-01-02,101,TRUE
`AZ123`,2016-01-03,101,TRUE
`AZ123`,2016-01-04,101,TRUE

Still doesn't import.

**Comment by Jammink2** [comment]
@penberg - I am using the absolute path to the CSV I am trying to import.  How can I ensure that CQLSH is (or isn't) finding it?

**Comment by Jammink2** [comment]
Aha!  I just did a $yum install wget on the node. By trial and error, **apt-get** didn't work.  

Question to self:  **do the docker docs mention that scylla docker image is CentOS based?**

Once I did that, I was able to use wget to get the csv on my node and I could run the COPY command from there.   

Starting copy of hotel.available_rooms_by_hotel_date with columns [hotel_id, date, room_number, is_available].
Processed: 310 rows; Rate:     482 rows/s; Avg. rate:     731 rows/s
310 rows imported from 1 files in 0.425 seconds (0 skipped).

**Comment by penberg** [comment]
@Jammink2 The documentation on Docker Hub indeed does not mention it's CentOS based. We didn't document that as most Docker images I came across don't do that either. We can definitely add it there somewhere. @tzach, thoughts?

**Comment by tzach** [comment]
Docker containers are usually self-contain. One does not install on a Docker instance, rather create a new docker instance using the existing one as a base layer. I do not see any hard in mentioning out Docker is CentOS base, but it should not matter.

Regardless, this is orthogonal to the original copy data from .csv issue.

**Comment by slivne** [comment]
@Jammink2 closing this - if there are additional comments / questions please comment here - we can reopen
