### ISSUE TITLE
Doesn't install and also doesnt build on debian 9

### ISSUE THREAD

**Issue by dioptre** [scylladb/scylla#2831]
Tried all debian dpkg then attempted to build from source.

Missing dependencies - thrift and and antlr3 - had to add them manually which was time consuming...

Also doesn't build 
./antlr3cyclicdfa.inl:170:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
./antlr3cyclicdfa.inl: In instantiation of ‘ANTLR_INT32 antlr3::CyclicDFA<ImplTraits, ComponentType>::predict(CtxType*, antlr3::CyclicDFA<ImplTraits, ComponentType>::RecognizerType*, antlr3::CyclicDFA<ImplTraits, ComponentType>::IntStreamType*, SuperType&) [with SuperType = cql3_parser::CqlLexerCyclicDFA44; ImplTraits = antlr3::Traits<cql3_parser::CqlLexer, cql3_parser::CqlParser>; CtxType = cql3_parser::CqlLexer; ANTLR_INT32 = int; antlr3::CyclicDFA<ImplTraits, ComponentType>::RecognizerType = antlr3::Traits<cql3_parser::CqlLexer, cql3_parser::CqlParser>::RecognizerType<antlr3::InputStream<antlr3::TraitsBase<antlr3::CustomTraitsBase> > >; antlr3::CyclicDFA<ImplTraits, ComponentType>::IntStreamType = antlr3::TraitsBase<antlr3::CustomTraitsBase>::IntStreamType<antlr3::InputStream<antlr3::TraitsBase<antlr3::CustomTraitsBase> > >]’:
build/release/gen/cql3/CqlLexer.cpp:20579:83:   required from here
./antlr3cyclicdfa.inl:170:11: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
In file included from ./antlr3bitset.hpp:221:0,
                 from ./antlr3.hpp:41,
                 from build/release/gen/cql3/CqlLexer.hpp:56,
                 from build/release/gen/cql3/CqlLexer.cpp:56:
./antlr3bitset.inl: In member function ‘antlr3::BitsetList<AllocatorType>::BitsetType* antlr3::BitsetList<AllocatorType>::bitsetLoad() [with ImplTraits = antlr3::TraitsBase<antlr3::CustomTraitsBase>]’:
./antlr3bitset.inl:54:2: error: nonnull argument ‘this’ compared to NULL [-Werror=nonnull-compare]
  if (this != NULL)
  ^~
cc1plus: all warnings being treated as errors
^Cninja: build stopped: interrupted by user.

*Installation details*
Scylla version (or git commit hash): 1.7, 2.0, Source
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): debian 9

Platform (physical/VM/cloud instance type/docker): Default VM on EC2

**Comment by r-tock** [comment]
Posting as suggested by @tzach over email.

Your Debian stretch as well as jessie repo is effectively broken. I spent 6-7 hours yesterday trying to figure it out, then seeing an issue on your GitHub related to it.

We use Google Issued Stretch images on Google cloud. if you want to reproduce it

**Comment by tzach** [comment]
reference: support for Debian 9 https://github.com/scylladb/scylla/issues/2541

**Comment by tzach** [comment]
@syuu1228 can you please take a look at the build issue?

**Comment by avikivity** [comment]
The missing deps are [available here](https://build.opensuse.org/project/show/home:scylladb:scylla-3rdparty).

**Comment by dioptre** [comment]
When was the last time you tried building on Debian?

Does it work? When I followed the binary install and source build
instructions both didn't work. I manually installed the dependencies so not
sure if this will cut it for everyone else.

I won't have time to try this again for a little bit, but I'd appreciate
someone from scylladb update the instructions for debian on the site so the
next people aren't left here. It'll really help with user acceptance and
churn. Next time I try it I'd really like to know it just works.

Thanks
A

**Comment by avikivity** [comment]
I've never personally built or installed on debian. I use Fedora.

Our prebuilt obviously do build, and we install-test them before release, so at least at some point in time, they did install correctly; perhaps a debian update caused it to fail. I know it's frustrating to have something fail as soon as you take it out of the box, hopefully the support will improve soon.

**Comment by dioptre** [comment]
Another 6 months and won't build on debian.

Good to know you're not supporting the only free and stable distribution of Linux.

**Comment by dorlaor** [comment]
@dioptre we have debian 8, are you looking for 9?
It's a relatively benign change, how about you help us to make it happen?

**Comment by reflectivist** [comment]
Fails badly in multiple ways when trying to build on Debian 9, during testing. Such a waste of time.
