### ISSUE TITLE
Implement "Transitional" authenticator/authorizer

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#2836]
Emulating the (documented) behaviour of DSE authenticators with the same name(-ish). 

I.e. wrappers around "normal" auth (password/permissions) but only actually using said auth for super user access. 
All other access requires authentication, but said authentication is not verified/enforced. 
The idea is to allow a rolling upgrade of a cluster to authentication op by first making all clients provide credentials (ignored by non-auth), then node by node enable auth with transitional handlers, then ensure user DB is populated and distributed, and finally rollingly enable strict auth for each node. Pfew.

**Comment by amoskong** [comment]
Quote from DSE doc:

`transitional_mode` Sets the behavior when authentication fails and credentials are missing:
- disabled
  - Transitional mode is disabled. Default.
- permissive
  - Only a superuser is authenticated and logged in. All other authentication attempts are logged in as the anonymous user.
- normal
  - Only users that provide valid credentials are logged in.
  - If the authentication is successful, the user is logged in.
  - If the authentication fails, the user is logged in as anonymous.
  - If no credentials are passed, the user is logged in as anonymous.
- strict
  - If credentials are passed, they are authenticated.
  - If the authentication is successful, the user is logged in.
  - If the authentication fails, then an authentication error is returned.
  - If no credentials are passed, the user is logged in as anonymous

**Comment by amoskong** [comment]
what's the `said auth` in first description? @elcallio

**Comment by amoskong** [comment]
We use transitional auth to switch from free auth to strict auth, and switch from strict auth to free auth? of just for switch to strict?

**Comment by amoskong** [comment]
@slivne @elcallio where can we find the DseAuthenticator implementation code? Reverse engineering the jar?

dse-5.1.5 amoskong$ grep -r DseAuthenticator .
Binary file ./clients/dse-byos_2.11-5.1.5.jar matches
Binary file ./resources/driver/lib/dse-java-driver-core-1.2.2.jar matches
Binary file ./resources/spark/client-lib/dse-byos_2.11-5.1.5.jar matches
Binary file ./lib/dse-core-5.1.5.jar matches
Binary file ./demos/weather_sensors/lib/dse-java-driver-core-1.2.2.jar matches

**Comment by elcallio** [comment]
transitional_mode=permissive is newer DSE equivalent of TransitionalAuthorizer in older DSE. Our transitional-yadayada is a semi-clone of the latter. thus it is equivalent to transitional_mode=permissive.

The purpose of the transitional-stuff is to be able to set the node up with auth tokens (i.e. create users and permissions) without enforcing them. I.e. you have an underlying auth (normal password) and can do create user, but not all clients need to be updated, and in the case of using drivers with smart routing, not all cluster need to be synced. Once all nodes are move to transitional, users are created, and auth tables have been verified to replicate across the cluster, an admin can start the tedious task of updating all clients to use credentials, and once that is done, node by node switch to strict auth instead. 

DSE is closed source. We only have access to byte code (jars, dse-byos_2.11-5.1.5.jar).

**Comment by amoskong** [comment]
TransitionalAuthenticator / TransitionalAuthorizer in DSE 4.8 :
https://docs.datastax.com/en/datastax_enterprise/4.8/datastax_enterprise/sec/secEnablingInternalSecurity.html

**Comment by elcallio** [comment]
Sorry, I meant transitional_mode=normal. And my description of the procedure should probably be the other way around: First add (meaningless) tokens to clients, then move to transitional mode, create users, replicate across cluster, the switch to normal security.

**Comment by amoskong** [comment]
Great! Then my latest understanding of this feature is right.

- transitional_auth: User can't login as anonymous when authentication
failed #3096
  I posted a fix [PATCH scylla v2 0/3] fix transitional authenticator of
authentication fail

**Comment by tzach** [comment]
@amoskong can we close this? the test patch is mergred and #3096 is fixed
