### ISSUE TITLE
DISTINCT is ignored with IN restrictions

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#2837]
when using IN restrictions DISTINCT is not applied to result set returned

cassandra 2.2.9

```
CREATE KEYSPACE blues WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '2'}  AND durable_writes = true;
CREATE TABLE blues.test (a text, b text, PRIMARY KEY (a, b));
use blues;
insert into test (a, b) values ('A2', 'A');
insert into test (a, b) values ('A3', 'C');
insert into test (a, b) values ('A3', 'D');
SELECT DISTINCT a FROM test ;

 a
----
 A2
 A3

(2 rows)
SELECT DISTINCT a FROM test where a in ('A2','A2');

 a
----
 A2
```

scylla

```
.
.
.
cqlsh:blues> SELECT * FROM test;

 a  | b
----+---
 A2 | A
 A3 | C
 A3 | D

cqlsh:blues> SELECT DISTINCT a FROM test;

 a
----
 A2
 A3

(2 rows)

cqlsh:blues> SELECT DISTINCT a FROM test where a in ('A2','A2');

 a
----
 A2
 A2

(2 rows)
```

**Comment by eliransin** [comment]
The problematic part of the query (and query processing) is not in the distinct notation ,but the list of none unique values of the "IN" clause. this will trigger multiple executors on the same partition each of which will return the same result set, the combined result set will simply contain duplicates. will submit a patch to make the values list unique before execution.
