### ISSUE TITLE
scylladb source build error

### ISSUE THREAD

**Issue by zhiguoxu** [scylladb/scylla#2838]
ninja-build failed and the error info is:

[4/5] LINK build/release/apps/iotune/iotune
FAILED: g++ -MD -MT build/release/net/tls.o -MF build/release/net/tls.o.d -O2 -I/root/scylla_src/scylla/seastar/build/release/gen -I/root/scylla_src/scylla/seastar/build/release/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden  -pthread -I/root/scylla_src/scylla/seastar -U_FORTIFY_SOURCE  -march=nehalem -I/root/scylla_src/scylla/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -DFMT_HEADER_ONLY -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/release/net/tls.o net/tls.cc
In file included from /root/scylla_src/scylla/seastar/core/seastar.hh:45:0,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/root/scylla_src/scylla/seastar/core/future.hh: In instantiation of 'void seastar::future_state<T>::set(A&& ...) [with A = {std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >}; T = {seastar::connected_socket}]':
/root/scylla_src/scylla/seastar/core/future.hh:705:9:   required from 'seastar::future<T>::future(seastar::ready_future_marker, A&& ...) [with A = {std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >}; T = {seastar::connected_socket}]'
/root/scylla_src/scylla/seastar/core/future.hh:1197:73:   required from 'seastar::future<T ...> seastar::make_ready_future(A&& ...) [with T = {seastar::connected_socket}; A = {std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >}]'
net/tls.cc:1165:108:   required from here
/root/scylla_src/scylla/seastar/core/future.hh:210:9: error: no matching function for call to 'std::tuple<seastar::connected_socket>::tuple(std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >)'
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /opt/scylladb/include/c++/5.3.1/unordered_map:41:0,
                 from /root/scylla_src/scylla/seastar/core/sstring.hh:29,
                 from /root/scylla_src/scylla/seastar/core/seastar.hh:44,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/opt/scylladb/include/c++/5.3.1/tuple:538:2: note: candidate: template<class _Alloc, class ... _UElements, class> std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, std::tuple<_Args2 ...>&&)
  tuple(allocator_arg_t __tag, const _Alloc& __a,
  ^
/opt/scylladb/include/c++/5.3.1/tuple:538:2: note:   template argument deduction/substitution failed:
In file included from /root/scylla_src/scylla/seastar/core/seastar.hh:45:0,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/root/scylla_src/scylla/seastar/core/future.hh:210:9: note:   cannot convert 'std::forward<std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> > >((* & a#0))' (type 'std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >') to type 'std::allocator_arg_t'
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /opt/scylladb/include/c++/5.3.1/unordered_map:41:0,
                 from /root/scylla_src/scylla/seastar/core/sstring.hh:29,
                 from /root/scylla_src/scylla/seastar/core/seastar.hh:44,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/opt/scylladb/include/c++/5.3.1/tuple:529:2: note: candidate: template<class _Alloc, class ... _UElements, class> std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, const std::tuple<_Args2 ...>&)
  tuple(allocator_arg_t __tag, const _Alloc& __a,
  ^
/opt/scylladb/include/c++/5.3.1/tuple:529:2: note:   template argument deduction/substitution failed:
In file included from /root/scylla_src/scylla/seastar/core/seastar.hh:45:0,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/root/scylla_src/scylla/seastar/core/future.hh:210:9: note:   cannot convert 'std::forward<std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> > >((* & a#0))' (type 'std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >') to type 'std::allocator_arg_t'
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /opt/scylladb/include/c++/5.3.1/unordered_map:41:0,
                 from /root/scylla_src/scylla/seastar/core/sstring.hh:29,
                 from /root/scylla_src/scylla/seastar/core/seastar.hh:44,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/opt/scylladb/include/c++/5.3.1/tuple:523:2: note: candidate: template<class _Alloc> std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, std::tuple< <template-parameter-1-1> >&&)
  tuple(allocator_arg_t __tag, const _Alloc& __a, tuple&& __in)
  ^
/opt/scylladb/include/c++/5.3.1/tuple:523:2: note:   template argument deduction/substitution failed:
In file included from /root/scylla_src/scylla/seastar/core/seastar.hh:45:0,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/root/scylla_src/scylla/seastar/core/future.hh:210:9: note:   cannot convert 'std::forward<std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> > >((* & a#0))' (type 'std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >') to type 'std::allocator_arg_t'
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /opt/scylladb/include/c++/5.3.1/unordered_map:41:0,
                 from /root/scylla_src/scylla/seastar/core/sstring.hh:29,
                 from /root/scylla_src/scylla/seastar/core/seastar.hh:44,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/opt/scylladb/include/c++/5.3.1/tuple:519:2: note: candidate: template<class _Alloc> std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, const std::tuple< <template-parameter-1-1> >&)
  tuple(allocator_arg_t __tag, const _Alloc& __a, const tuple& __in)
  ^
/opt/scylladb/include/c++/5.3.1/tuple:519:2: note:   template argument deduction/substitution failed:
In file included from /root/scylla_src/scylla/seastar/core/seastar.hh:45:0,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/root/scylla_src/scylla/seastar/core/future.hh:210:9: note:   cannot convert 'std::forward<std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> > >((* & a#0))' (type 'std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >') to type 'std::allocator_arg_t'
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /opt/scylladb/include/c++/5.3.1/unordered_map:41:0,
                 from /root/scylla_src/scylla/seastar/core/sstring.hh:29,
                 from /root/scylla_src/scylla/seastar/core/seastar.hh:44,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/opt/scylladb/include/c++/5.3.1/tuple:513:2: note: candidate: template<class _Alloc, class ... _UElements, class> std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, _UElements&& ...)
  tuple(allocator_arg_t __tag, const _Alloc& __a,
  ^
/opt/scylladb/include/c++/5.3.1/tuple:513:2: note:   template argument deduction/substitution failed:
In file included from /root/scylla_src/scylla/seastar/core/seastar.hh:45:0,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/root/scylla_src/scylla/seastar/core/future.hh:210:9: note:   cannot convert 'std::forward<std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> > >((* & a#0))' (type 'std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >') to type 'std::allocator_arg_t'
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /opt/scylladb/include/c++/5.3.1/unordered_map:41:0,
                 from /root/scylla_src/scylla/seastar/core/sstring.hh:29,
                 from /root/scylla_src/scylla/seastar/core/seastar.hh:44,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/opt/scylladb/include/c++/5.3.1/tuple:506:2: note: candidate: template<class _Alloc> std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&, const _Elements& ...)
  tuple(allocator_arg_t __tag, const _Alloc& __a,
  ^
/opt/scylladb/include/c++/5.3.1/tuple:506:2: note:   template argument deduction/substitution failed:
In file included from /root/scylla_src/scylla/seastar/core/seastar.hh:45:0,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/root/scylla_src/scylla/seastar/core/future.hh:210:9: note:   cannot convert 'std::forward<std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> > >((* & a#0))' (type 'std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >') to type 'std::allocator_arg_t'
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /opt/scylladb/include/c++/5.3.1/unordered_map:41:0,
                 from /root/scylla_src/scylla/seastar/core/sstring.hh:29,
                 from /root/scylla_src/scylla/seastar/core/seastar.hh:44,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/opt/scylladb/include/c++/5.3.1/tuple:502:2: note: candidate: template<class _Alloc> std::tuple< <template-parameter-1-1> >::tuple(std::allocator_arg_t, const _Alloc&)
  tuple(allocator_arg_t __tag, const _Alloc& __a)
  ^
/opt/scylladb/include/c++/5.3.1/tuple:502:2: note:   template argument deduction/substitution failed:
In file included from /root/scylla_src/scylla/seastar/core/seastar.hh:45:0,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/root/scylla_src/scylla/seastar/core/future.hh:210:9: note:   cannot convert 'std::forward<std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> > >((* & a#0))' (type 'std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >') to type 'std::allocator_arg_t'
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /opt/scylladb/include/c++/5.3.1/unordered_map:41:0,
                 from /root/scylla_src/scylla/seastar/core/sstring.hh:29,
                 from /root/scylla_src/scylla/seastar/core/seastar.hh:44,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/opt/scylladb/include/c++/5.3.1/tuple:496:19: note: candidate: template<class ... _UElements, class> constexpr std::tuple< <template-parameter-1-1> >::tuple(std::tuple<_Args1 ...>&&)
         constexpr tuple(tuple<_UElements...>&& __in)
                   ^
/opt/scylladb/include/c++/5.3.1/tuple:496:19: note:   template argument deduction/substitution failed:
In file included from /root/scylla_src/scylla/seastar/core/seastar.hh:45:0,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/root/scylla_src/scylla/seastar/core/future.hh:210:9: note:   'std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >' is not derived from 'std::tuple<_Elements ...>'
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /opt/scylladb/include/c++/5.3.1/unordered_map:41:0,
                 from /root/scylla_src/scylla/seastar/core/sstring.hh:29,
                 from /root/scylla_src/scylla/seastar/core/seastar.hh:44,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/opt/scylladb/include/c++/5.3.1/tuple:489:19: note: candidate: template<class ... _UElements, class> constexpr std::tuple< <template-parameter-1-1> >::tuple(const std::tuple<_Args1 ...>&)
         constexpr tuple(const tuple<_UElements...>& __in)
                   ^
/opt/scylladb/include/c++/5.3.1/tuple:489:19: note:   template argument deduction/substitution failed:
In file included from /root/scylla_src/scylla/seastar/core/seastar.hh:45:0,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/root/scylla_src/scylla/seastar/core/future.hh:210:9: note:   'std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >' is not derived from 'const std::tuple<_Elements ...>'
         new (&_u.value) std::tuple<T...>(std::forward<A>(a)...);
         ^
In file included from /opt/scylladb/include/c++/5.3.1/unordered_map:41:0,
                 from /root/scylla_src/scylla/seastar/core/sstring.hh:29,
                 from /root/scylla_src/scylla/seastar/core/seastar.hh:44,
                 from /root/scylla_src/scylla/seastar/core/reactor.hh:25,
                 from net/tls.cc:28:
/opt/scylladb/include/c++/5.3.1/tuple:484:17: note: candidate: constexpr std::tuple< <template-parameter-1-1> >::tuple(std::tuple< <template-parameter-1-1> >&&) [with _Elements = {seastar::connected_socket}]
       constexpr tuple(tuple&&) = default; 
                 ^
/opt/scylladb/include/c++/5.3.1/tuple:484:17: note:   no known conversion for argument 1 from 'std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >' to 'std::tuple<seastar::connected_socket>&&'
/opt/scylladb/include/c++/5.3.1/tuple:479:19: note: candidate: template<class ... _UElements, class> constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...)
         constexpr tuple(_UElements&&... __elements)
                   ^
/opt/scylladb/include/c++/5.3.1/tuple:479:19: note:   template argument deduction/substitution failed:
/opt/scylladb/include/c++/5.3.1/tuple:475:40: error: no type named 'type' in 'struct std::enable_if<false, void>'
       template<typename... _UElements, typename = typename
                                        ^
/opt/scylladb/include/c++/5.3.1/tuple:472:17: note: candidate: constexpr std::tuple< <template-parameter-1-1> >::tuple(const _Elements& ...) [with _Elements = {seastar::connected_socket}]
       constexpr tuple(const _Elements&... __elements)
                 ^
/opt/scylladb/include/c++/5.3.1/tuple:472:17: note:   no known conversion for argument 1 from 'std::unique_ptr<seastar::tls::tls_connected_socket_impl, std::default_delete<seastar::tls::tls_connected_socket_impl> >' to 'const seastar::connected_socket&'
/opt/scylladb/include/c++/5.3.1/tuple:468:17: note: candidate: constexpr std::tuple< <template-parameter-1-1> >::tuple() [with _Elements = {seastar::connected_socket}]
       constexpr tuple()
                 ^
/opt/scylladb/include/c++/5.3.1/tuple:468:17: note:   candidate expects 0 arguments, 1 provided
ninja: build stopped: subcommand failed.
[47/458] CXX build/release/gen/cql3/CqlParser.o
ninja: build stopped: subcommand failed.

**Comment by argenet** [comment]
This issue is tracked as https://github.com/scylladb/seastar/issues/338 and has been recently fixed.
Should be resolved for Scylla on the next seastar submodule update.

**Comment by tzach** [comment]
Thanks @argenet 
@zhiguoxu please test on master and let us know

**Comment by slivne** [comment]
@zhiguoxu - closing this - if needed we can reopen
