### ISSUE TITLE
Support for varint and decimal in aggregate functions

### ISSUE THREAD

**Issue by hagrid-the-developer** [scylladb/scylla#2842]
Scylla version (or git commit hash): 63eb9f61c080291d00f49f436e05578721c1e752

It seems that scylla doesn't support aggregate functions sum(.) and avg(.) for decimal and varint. While it is trivial to add support for varint, for decimal one would need to add + and / to C++ type big_decimal. Since big_decimal can store decimal numbers with only finite number of digits one can probably implement (big_decimal / ::uint64_t) that calculates divisions for limited number of decimal digits (eg. 2*max{number of decimal digits of the dividend, number of decimal digits of the divisor}).

**Comment by tzach** [comment]
@hagrid-the-developer does Apache Cassandras support aggregate functions for varint and decimal?
In which version?

**Comment by hagrid-the-developer** [comment]
I tried C 3.6, but according to this Issue it was probably added in 2.2.0 beta: https://issues.apache.org/jira/browse/CASSANDRA-4914 .

    CREATE TABLE aqd (sensor_id text, time timestamp, co_ppm int, co_ppmd decimal, co_ppmd2 decimal, co_ppmv varint, PRIMARY KEY (sensor_id, time));
    INSERT INTO air_quality_data(sensor_id, time, co_ppm, co_ppmd, co_ppmd2, co_ppmv) VALUES ('my_home', '2016-08-30 07:01:00', 17, 17, 17.00, 17);
    INSERT INTO aqd(sensor_id, time, co_ppm, co_ppmd, co_ppmd2, co_ppmv) VALUES ('my_home', '2016-08-30 07:01:00', 17, 17, 17.00, 17);
    INSERT INTO aqd(sensor_id, time, co_ppm, co_ppmd, co_ppmd2, co_ppmv) VALUES ('my_home', '2016-08-30 07:01:01', 18, 18, 18.00, 18);
    INSERT INTO aqd(sensor_id, time, co_ppm, co_ppmd, co_ppmd2, co_ppmv) VALUES ('my_home', '2016-08-30 07:01:02', 19, 19, 19.00, 19);
    INSERT INTO aqd(sensor_id, time, co_ppm, co_ppmd, co_ppmd2, co_ppmv) VALUES ('my_home', '2016-08-30 07:01:03', 20, 20, 20.00, 20);
    INSERT INTO aqd(sensor_id, time, co_ppm, co_ppmd, co_ppmd2, co_ppmv) VALUES ('my_home', '2016-08-30 07:01:04', 30, 30, 30.00, 30);
    INSERT INTO aqd(sensor_id, time, co_ppm, co_ppmd, co_ppmd2, co_ppmv) VALUES ('my_home', '2016-08-30 07:01:04', 31, 31, 31.00, 31);
    INSERT INTO aqd(sensor_id, time, co_ppm, co_ppmd, co_ppmd2, co_ppmv) VALUES ('my_home', '2016-08-30 07:01:10', 20, 20, 20.00, 20);
    SELECT avg(co_ppm), avg(co_ppmd), avg(co_ppmd2), avg(co_ppmv) FROM aqd;

     system.avg(co_ppm) | system.avg(co_ppmd) | system.avg(co_ppmd2) | system.avg(co_ppmv)
    --------------------+---------------------+----------------------+---------------------
                     20 |                  21 |                20.83 |                  20
