### ISSUE TITLE
Scylla Debian installation returns 404

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#2847]
Version 1.7

During installation you get 
E: Failed to fetch libstdc++6_5.4.1-5_amd64.deb  HttpError404

**Comment by amnonh** [comment]
Should verify that software-properties-common and apt-transport-https are installed

**Comment by benoit-canet** [comment]
apt-get update ? :)

2017-09-28 9:35 GMT+02:00 Amnon Heiman <notifications@github.com>:

**Comment by slivne** [comment]
@amnonh - did this happen on GCE ?

@syuu1228 / @amoskong - can you please comment

**Comment by amoskong** [comment]
@amnonh what's the complete version? which repo did you use to install scylla?

The last [artifact test job - debian8](http://jenkins.cloudius-systems.com:8080/job/scylla-1.7-debian8-deb-test/27/label=huginn/artifact/latest/job.log) is good.
scylla-server_1.7.5-0.20170924.760af56-1_amd64.deb

**Comment by amnonh** [comment]
It happen on GCE, the problem is not with the scylla version but with the
use of https

**Comment by amnonh** [comment]
When I did testing on Thursday it still happening, I used scylla-2.0 but I
don't think this is the problem.

Can you please attach the history of what you did so I can compare?

**Comment by tzach** [comment]
> When I did testing on Thursday it still happening, I used scylla-2.0 but I
> don't think this is the problem.

@amnonh can you attach your logs as well? are we sure you and @syuu1228 are using the same Debian version?

**Comment by amnonh** [comment]
I'll run it again and include them

**Comment by amnonh** [comment]
$ cat /etc/debian_version
8.9

$ if [ ! -f /etc/apt/sources.list.d/backports.list ]; then
> sudo echo 'deb http://http.debian.net/debian jessie-backports main' | sudo tee /etc/apt/sources.list.d/backports.list > /dev/null;
> fi
amnon@amnon-debian8:~$ 
amnon@amnon-debian8:~$ sudo wget -O /etc/apt/sources.list.d/scylla.list http://repositories.scylladb.com/scylla/repo/67b24184b1731cb29351b68f11de4097/debian/scylladb-2.0-jessie.list
--2017-12-10 08:50:59--  http://repositories.scylladb.com/scylla/repo/67b24184b1731cb29351b68f11de4097/debian/scylladb-2.0-jessie.list
Resolving repositories.scylladb.com (repositories.scylladb.com)... 54.192.82.226, 54.192.82.202, 54.192.82.2, ...
Connecting to repositories.scylladb.com (repositories.scylladb.com)|54.192.82.226|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://repositories.scylladb.com/scylla/repo/67b24184b1731cb29351b68f11de4097/debian/scylladb-2.0-jessie.list [following]
--2017-12-10 08:50:59--  https://repositories.scylladb.com/scylla/repo/67b24184b1731cb29351b68f11de4097/debian/scylladb-2.0-jessie.list
Connecting to repositories.scylladb.com (repositories.scylladb.com)|54.192.82.226|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 142 [text/plain]
Saving to: ‘/etc/apt/sources.list.d/scylla.list’

/etc/apt/sources.list.d/scylla.l 100%[==========================================================>]     142  --.-KB/s   in 0s     

2017-12-10 08:51:02 (2.26 MB/s) - ‘/etc/apt/sources.list.d/scylla.list’ saved [142/142]

amnon@amnon-debian8:~$ sudo apt-get update
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?

**Comment by slivne** [comment]
amnon we do not support 8.9 (stretch)

we support jessie

**Comment by amnonh** [comment]
9 is stretch, 8.9 is jessie

**Comment by avikivity** [comment]
We support both debian 8 and 9.

**Comment by slivne** [comment]
Avi we don't officially support 9 we haven't released that yet in any
release.

**Comment by amnonh** [comment]
and the issue we have is with debian 8

**Comment by avikivity** [comment]
@slivne a comment earlier you said we don't support 8.9.

Anyway, the intent is to support both.

**Comment by slivne** [comment]
@amnonh is this resolved can we close this ?

**Comment by amnonh** [comment]
@slivne it's resolved
