### ISSUE TITLE
Replication of default auth settings may fail

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2852]
When node starts and auth tables are empty it will create them and issue inserts with default settings. Because creation of the tables doesn't wait for schema agreement, the inserts race with schema change notification processing on other nodes. The inserts can fail to replicate to those nodes if schema change notifications are not processed quickly enough. Symptom in logs:

```
ERROR 2017-09-28 15:02:43,069 [shard 0] storage_proxy - Exception when communicating with 127.0.23.2: Can't find a column family with UUID 1064e0a0-1f2c-3a17-b803-cb8e23d8458f
```

In this case it is benign, because if the tables are empty, the other node will do the setup on its own too.

**Comment by slivne** [comment]
@tgrabiec - so can we wait for schema agreement before doing the insert - or do you have another suggestion ?

**Comment by tgrabiec** [comment]
That seems like a natural solution.

**Comment by hakuch** [comment]
I will also need to address this class of bug in the role manager for role-based access control. @tgrabiec, would you please point me in the direction of code for checking schema agreement?

**Comment by tgrabiec** [comment]
@hakuch We do a similar thing during bootstrap:

```
        // if our schema hasn't matched yet, keep sleeping until it does
        // (post CASSANDRA-1391 we don't expect this to be necessary very often, but it doesn't hurt to be careful)
        while (!get_local_migration_manager().is_ready_for_bootstrap()) {
            set_mode(mode::JOINING, "waiting for schema information to complete", true);
            sleep(std::chrono::seconds(1)).get();
        }
```

**Comment by duarten** [comment]
Another manifestation of this bug:

Node `127.0.32.4`:
```
DEBUG 2018-01-27 16:43:20,721 [shard 0] migration_manager - Requesting schema 28aadabd-9246-3ae4-8e53-5603b2006265 from 127.0.32.2:0
DEBUG 2018-01-27 16:43:20,722 [shard 0] schema_registry - Loading of 28aadabd-9246-3ae4-8e53-5603b2006265 failed: std::_Nested_exception<schema_version_loading_failed> (Failed to load schema version 28aadabd-9246-3ae4-8e53-5603b2006265): std::_Nested_exception<no_such_keyspace> (Can't find a keyspace system_auth): std::out_of_range (_Map_base::at)
```
Node `127.0.32.2`:
```
DEBUG 2018-01-27 16:43:20,721 [shard 0] storage_proxy - Schema version request for 28aadabd-9246-3ae4-8e53-5603b2006265
ERROR 2018-01-27 16:43:20,722 [shard 0] storage_proxy - Exception when communicating with 127.0.32.4: Failed to load schema version 28aadabd-9246-3ae4-8e53-5603b2006265
```

**Comment by slivne** [comment]
We also have system_traces ...

I think the solution for both was to use a fixed UUID  for the system_auth
and system_traces - is that already done ?

**Comment by duarten** [comment]
I think that's unrelated. The UUID is determined by the schema version, which should be the same for identical schemas.

**Comment by hakuch** [comment]
I'll have a patch for this issue very shortly. I'm wrapping up testing now.

**Comment by hakuch** [comment]
@tgrabiec, when I insert the following into `auth/common.cc`:

```c++
static future<> wait_for_schema_agreement(::service::migration_manager& mm) {
    using namespace std::chrono_literals;
    return do_until([&mm] { return mm.is_ready_for_bootstrap(); }, [] { return sleep(1s); });
}
```
and add it as a continuation after announcing the new column family, the start-up of Scylla hangs forever.

Is there another way to ensure that schema changes have propagated throughout the cluster? Perhaps this function of the `migration_manager` makes an assumption about state that does not hold at the time that auth is initialized?

**Comment by duarten** [comment]
That's probably in the startup path, before we initialize gossip, so that will never resolve. Better to put it somewhere else, in the query path, or something.

**Comment by hakuch** [comment]
I was thinking the same thing after I posted, @duarten.

For auth modules which create default data, the table is created synchronously as part of the initialization of auth inside of the initialization of `storage_service`. After a 10 s "start-up" period, we asynchronously (controlled with a `seastar::abort_source`) query the tables and insert the default row if it does not exist.

I modified the code to call `wait_for_schema_agreement` just before we issue the query for the default data. I assumed that the gossiper would have been initialized by this time. However, observed the same problem: the future never resolves.

**Comment by duarten** [comment]
Hum.. are you testing with one node only? I think you should check `storage_service::should_bootstrap()`.

**Comment by tgrabiec** [comment]
@duarten should_bootstrap() is false for seeds, and we want to coordinate auth creation for seeds as well. 

I would try to understand why `is_ready_for_bootstrap()` (which should be renamed to `wait_for_schema_agreement()`) is not progressing.
