### ISSUE TITLE
memtable scanning_reader::fast_forward_to does not work when memtable is flushed

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#2854]
After memtable gets flushed, mutation_reader obtained from it before the flush does not handle fast_forward_to correctly.

**Comment by tgrabiec** [comment]
Currently used only in tests, so not serious. Added in e14f8027d5226406460f8727f3d629e0abf393b0.

**Comment by haaawk** [comment]
@tgrabiec I sent a patch reproducing the bug and fixing on the mailing list already.
