### ISSUE TITLE
If sending counter mutation to a leader fails an error escapes to a client. 

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#2859]
*Installation details*
Scylla version (or git commit hash): 8e46d15f918fd23f1ef0aa48f418d967f42c1ee5

If sending a counter mutation to a chosen leader fails with an exception
other than a timeout the error escapes to a client and confuses it greatly
(cassandra-stress claim that it cannot connect to any node and fails).

To reproduce run c-s with counter_write and RF=3 and kill one node with "kill -9".

**Comment by haaawk** [comment]
@gleb-cloudius Could we transfer this to @jul-stas ?

**Comment by slivne** [comment]
moved :)
