### ISSUE TITLE
Make gossip synchronization on bootstrap more robust 

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2866]
Currently it simply waits for ring_delay (30 seconds).

If processing of the state takes longer than that, e.g. due to the number of nodes in the cluster, it will start bootstrapping before it finished processing all the nodes, leading to data loss. Refs #2855.

The wait could be improved by, in addition to a fixed sleep, wait for:
  - the endpoint state map to stop growing 
  - all received but not yet processed gossip messages to finish processing

**Comment by tzach** [comment]
@tgrabiec maybe a new node should ask, and receive, more info on its first round of gossip.
If it gets the full cluster data (line in a shadow round), it will know there are nonresponsive nodes.

**Comment by tgrabiec** [comment]
We already do a shadow round with the seeds, so will learn all they know.

**Comment by elcallio** [comment]
Is that not basically asking for having "wait_for_gossip_to_settle()" moved to the storage_service::bootstrap() code (or called there as well mayhap, since the waiting part is conditional in bootstrap)? Plus maybe adding some message state awareness to it?

**Comment by tgrabiec** [comment]
Something like that, yes.
