### ISSUE TITLE
Unexpected gocql.ErrNotFound when fetching from materialized view

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#2868]
Scylla version 2.0.0-0.20170929.e265c91
Cluster size: 1
OS CentOS 7.3

I am testing materialized view support via the gocql interface and found some inconsistency from the Cassandra 3.x behavior.  It seems like the query interface returns ErrNotFound if any of the columns in the select statement are null.  The Scylla MV implementation also seems to work better when every column in the MV primary key are specified in the query.  The C* implementation returns a valid row with err set to null and null for columns that do not exist.  And the C* implementation returns rows when a subset of the columns in the PK are specified.

I've built the following repro:

CREATE TABLE t1 (a int,b uuid,c text, PRIMARY KEY (a, b));  
CREATE MATERIALIZED VIEW v1 AS SELECT a, b, c FROM t1 WHERE a IS NOT NULL AND b IS NOT NULL PRIMARY KEY (b, a);

insert into t1 (a, b) values (1, 00000000-0000-1000-0000-000000000001)
insert into t1 (a, b, c) values (2, 00000000-0000-1000-0000-000000000001, 'test')

And then executed the following queries:

1: SELECT a,b from v1 where b = 00000000-0000-1000-0000-000000000001 LIMIT 1
2: SELECT a,b from v1 where b = 00000000-0000-1000-0000-000000000001 and a = 1 LIMIT 1
3: SELECT a,b,c from v1 where b = 00000000-0000-1000-0000-000000000001 LIMIT 1
4: SELECT a,b,c from v1 where b = 00000000-0000-1000-0000-000000000001 and a = 1 LIMIT 1

5: SELECT a,b from v1 where b = 00000000-0000-1000-0000-000000000001 LIMIT 1
6: SELECT a,b from v1 where b = 00000000-0000-1000-0000-000000000001 and a = 2 LIMIT 1
7: SELECT a,b,c from v1 where b = 00000000-0000-1000-0000-000000000001 LIMIT 1
8: SELECT a,b,c from v1 where b = 00000000-0000-1000-0000-000000000001 and a = 2 LIMIT 1

Here are the results I see:

$ ./mvtest 
Connected to Scylla.
Inserted row..
Inserted row..
Waiting one second..
Fetch 1 failed, err not found
Fetch 2 failed, err not found
Fetch 3 failed, err not found
Fetch 4 failed, err not found
Fetch 5 failed, err not found
Fetch 6 worked, a 2 b 00000000-0000-1000-0000-000000000001
Fetch 7 failed, err not found
Fetch 8 worked, a 2 b 00000000-0000-1000-0000-000000000001

I've also attached my repro.  

Thanks.

Jonathan

[mvtest.txt](https://github.com/scylladb/scylla/files/1360595/mvtest.txt)

**Comment by duarten** [comment]
This is odd. Queries over a MV are just normal queries (there is no special handling), and the data is there (at least key 2, key 1 may be missing). Could this be a compatibility issue? Did you test reading from a normal Scylla table with the same schema as the view?

**Comment by veramine** [comment]
I think you are probably right that it is some kind of compatibility issue.  I just tested with a regular table having same schema as the view and it worked fine as expected.  But in this last test all the MV fetches returned gocql.ErrNotFound, including those where the row had no null values and the query with all PK elements specified.  And including unqualified fetches.  In those cases, I got the error:

Fetch 17 failed, err Can't find a column family with UUID 3cc67de0-aa01-11e7-806f-000000000002
Fetch 18 failed, err Can't find a column family with UUID 3cc67de0-aa01-11e7-806f-000000000002

So there is definitely something going on that is unlikely to be scylla-server's fault.  I will try to enable tracing or some other mechanism to get more visibility from gocql into what is happening.  I am glad to hear it is not a known issue or something that has been troublesome to solve.  Probably a compatibility issue locally.  I will let you know when I solve it.  Thanks.

**Comment by veramine** [comment]
I changed the table names and all the sudden every query worked.  I wonder if there was some stale state leading to the inconsistencies..?  I was dropping the view and table between each test but it seems like that may not have been sufficient to flush all old state.  All good now though.

$ ./mvtest 
Connected to Scylla.
Inserted row..
Inserted row..
Inserted row..
Waiting one second..
Fetch 1 worked, a 1 b 00000000-0000-1000-0000-000000000001
Fetch 2 worked, a 1 b 00000000-0000-1000-0000-000000000001
Fetch 3 worked, a 1 b 00000000-0000-1000-0000-000000000001
Fetch 4 worked, a 1 b 00000000-0000-1000-0000-000000000001
Fetch 5 worked, a 1 b 00000000-0000-1000-0000-000000000001
Fetch 6 worked, a 2 b 00000000-0000-1000-0000-000000000001
Fetch 7 worked, a 1 b 00000000-0000-1000-0000-000000000001
Fetch 8 worked, a 2 b 00000000-0000-1000-0000-000000000001
Fetch 9 worked, a 1 b 00000000-0000-1000-0000-000000000001
Fetch 10 worked, a 1 b 00000000-0000-1000-0000-000000000001
Fetch 11 worked, a 1 b 00000000-0000-1000-0000-000000000001
Fetch 12 worked, a 1 b 00000000-0000-1000-0000-000000000001
Fetch 13 worked, a 1 b 00000000-0000-1000-0000-000000000001
Fetch 14 worked, a 2 b 00000000-0000-1000-0000-000000000001
Fetch 15 worked, a 1 b 00000000-0000-1000-0000-000000000001
Fetch 16 worked, a 2 b 00000000-0000-1000-0000-000000000001
Fetch 17 worked, a 1 b 00000000-0000-1000-0000-000000000001
Fetch 18 worked, a 1 b 00000000-0000-1000-0000-000000000001 c 
Fetch 19 worked, a 3 b 00000000-0000-1000-0000-000000000001 c test
Fetch 20 worked, a 3 b 00000000-0000-1000-0000-000000000001 c test

**Comment by dorlaor** [comment]
Duarte is the one who should look into it but be advised that we have a
current limitation that we don't index
existing data in the table if the view is created after it was populated.
The limitation will be lifted in 2.1

**Comment by veramine** [comment]
Yep, I noticed that and it is no problem.  Everything working ok for us now!  Will try to do some stress testing over the weekend and let you know if we come up with anything unexpected.  Feel free to close this issue.  Thanks!
