### ISSUE TITLE
Unstable throughput result on i2.xlarge

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2870]
*Installation details*
Scylla version (or git commit hash): ScyllaDB 2.0.0 (ami-af14eed7) 
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): us-west-2b, 

Running the following c-s load from one c3.8xlarge node
```
cassandra-stress write n=100000000 -node 172.31.43.43,172.31.45.129,172.31.34.80 -rate threads=250
```

The throughput seems unstable, very jumpy. 
![image](https://user-images.githubusercontent.com/170200/31315797-3032e8ce-ac28-11e7-8519-05b380eea1de.png)

![image](https://user-images.githubusercontent.com/170200/31315801-4b6bcec6-ac28-11e7-8c81-cf93de133774.png)

health-check-report uploaded to 
```
http://upload.scylladb.com/dd7c64e8-9a47-4563-916d-beead418bb8f/172.31.34.80-health-check-report.txt
```

Prometheus data
```
http://upload.scylladb.com/dd7c64e8-9a47-4563-916d-beead418bb8f/prometheus_data.tar.gz
```

**Comment by tzach** [comment]
@roydahan does this look familiar?
could be my setting, but I can not find what

**Comment by glommer** [comment]
This is very normal for insert-intensive CPU-bound workloads. That is related to compactions and flushes. This will get better when the controllers are merged.

**Comment by tzach** [comment]
Look like its not a regression from 1.7 or 1.6
