### ISSUE TITLE
stream_throughput_outbound_megabits_per_sec in scylla.yaml has no effect

### ISSUE THREAD

**Issue by zhiguoxu** [scylladb/scylla#2876]
*Installation details*
Scylla version (or git commit hash): 1.7
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos7.3

The configuration "stream_throughput_outbound_megabits_per_sec: " in scylla.yaml seems to have no effect. When I set "stream_throughput_outbound_megabits_per_sec: 1" in both node, and I writed data to one node, the network stream between the two nodes was still very high.

**Comment by tzach** [comment]
Indeed, this parameter have no effect and should be removed from scylla.yaml
