### ISSUE TITLE
Scylla AMI: when running on a non precooked instance type

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2879]
*Installation details*
Scylla version (or git commit hash): 2.0
OS (RHEL/CentOS/Ubuntu/AWS AMI): Scylla 2.0.0 AMI, instance type c4.4xlarge

For precooked instances type (i2, i3) Scylla setup the RAID, XFS and use pre-set io tune parameters.
Which of the above is used on a different instance type, like c4?
Look like it does set XFS and RAID, but not more

**Comment by tzach** [comment]
related to #2878

**Comment by tzach** [comment]
@syuu1228 can you help?

**Comment by syuu1228** [comment]
@tzach The difference of supported instance type vs unsupported instance type is iotune parameters.
User has responsibility to run "sudo scylla_io_setup" manually on unsupported instance type.
We don't have any other difference here.
Why we decided not to run scylla_io_setup automatically is, it sometimes takes too much time, user may not understand why scylla instance doesn't startup.

The code is here: https://github.com/scylladb/scylla-ami/blob/master/scylla_ami_setup#L9

**Comment by tzach** [comment]
> @tzach The difference of supported instance type vs unsupported instance type is iotune parameters.
> User has responsibility to run "sudo scylla_io_setup" manually on unsupported instance type.
> We don't have any other difference here.
> Why we decided not to run scylla_io_setup automatically is, it sometimes takes too much time, user may not understand why scylla instance doesn't startup.

So, which part of the scylla_setup does the user need to run? only the scylla_io_setup?

**Comment by syuu1228** [comment]
@tzach It should be only scylla_io_setup, unless we're missing something. Because we are running exactly same command on both supported/unsupported except scylla_io_setup.

**Comment by tzach** [comment]
Thanks
In think case, this should be the instructions are correct
```
    c4.4xlarge is not supported instance type!
To continue startup ScyllaDB on this instance, run 'sudo scylla_io_setup' then 'systemctl start scylla-server'.
For a list of optimized instance types and more EC2 instructions see http://www.scylladb.com/doc/getting-started-amazon/
```
