### ISSUE TITLE
Calculating row digest is slow

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#2884]
*Installation details*
Scylla version (or git commit hash): >= 2.0, master

The stall detector reported stack traces pointing to digest calculation taking more than 6ms:

```
md5_hasher::update(char const*, unsigned long) at /usr/src/debug/scylla-enterprise-2017.1.2.rc2/md5_hasher.hh:24
 (inlined by) void appending_hash<std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> >, void>::operator()<md5_hasher>(md5_hasher&, std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> >) const at /usr/src/debug/scylla-enterprise-2017.1.2.rc2/./bytes.hh:64
 (inlined by) void feed_hash<md5_hasher, std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> > >(md5_hasher&, std::experimental::fundamentals_v1::basic_string_view<signed char, std::char_traits<signed char> > const&) at /usr/src/debug/scylla-enterprise-2017.1.2.rc2/./hashing.hh:43
 (inlined by) void appending_hash<atomic_cell_view, void>::operator()<md5_hasher>(md5_hasher&, atomic_cell_view) const at /usr/src/debug/scylla-enterprise-2017.1.2.rc2/atomic_cell_hash.hh:43
hash_row_slice(md5_hasher&, schema const&, column_kind, row const&, std::vector<unsigned int, std::allocator<unsigned int> > const&) [clone .constprop.1215] at mutation_partition.cc:?
mutation_querier::consume(clustering_row&&, tombstone) at ??:?
future<bool_class<stop_iteration_tag> > do_consume_streamed_mutation_flattened<stable_flattened_mutations_consumer<compact_for_query<(emit_only_live_rows)1, query_result_builder> > >(streamed_mutation&, stable_flattened_mutations_consumer<compact_for_query<(emit_only_live_rows)1, query_result_builder> >&) at ??:?
_ZN8futurizeI6futureII10bool_classI18stop_iteration_tagEEEE5applyIZZZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows1E20query_result_builderEEEDa15mutation_readerOT_bENKUlRSF_RT0_RT1_E_clISE_SD_NSt12experimental15fundamentals_v18optionalI17streamed_mutationEEEEDaSH_SJ_SL_ENKUlvE_clEvEUlSF_E_I18optimized_optionalISR_EEEES4_SG_OSt5tupleIIDpT0_EE at ??:?
_ZN6futureII18optimized_optionalI17streamed_mutationEEE4thenIZZZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows1E20query_result_builderEEEDa15mutation_readerOT_bENKUlRSD_RT0_RT1_E_clISC_SB_NSt12experimental15fundamentals_v18optionalIS1_EEEEDaSF_SH_SJ_ENKUlvE_clEvEUlSD_E_S_II10bool_classI18stop_iteration_tagEEEEESG_SE_ at ??:?
_Z6repeatIZZ17consume_flattenedI35stable_flattened_mutations_consumerI17compact_for_queryIL19emit_only_live_rows1E20query_result_builderEEEDa15mutation_readerOT_bENKUlRS8_RT0_RT1_E_clIS7_S6_NSt12experimental15fundamentals_v18optionalI17streamed_mutationEEEEDaSA_SC_SE_EUlvE_E6futureIJEES9_ at mutation_partition.cc:?
data_query(lw_shared_ptr<schema const>, mutation_source const&, nonwrapping_range<dht::ring_position> const&, query::partition_slice const&, unsigned int, unsigned int, std::chrono::time_point<gc_clock, std::chrono::duration<int, std::ratio<1l, 1l> > >, query::result::builder&) at ??:?
column_family::query(lw_shared_ptr<schema const>, query::read_command const&, query::result_request, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > > const&, lw_shared_ptr<tracing::trace_state>, query::result_memory_limiter&, unsigned long)::{lambda(query::result_memory_accounter)#1}::operator()(query::result_memory_accounter)::{lambda()#1}::operator()() const at /usr/src/debug/scylla-enterprise-2017.1.2.rc2/database.cc:2564
future<lw_shared_ptr<query::result> > futurize<future<lw_shared_ptr<query::result> > >::apply<column_family::query(lw_shared_ptr<schema const>, query::read_command const&, query::result_request, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > > const&, lw_shared_ptr<tracing::trace_state>, query::result_memory_limiter&, unsigned long)::{lambda(query::result_memory_accounter)#1}, query::result_memory_accounter>(column_family::query(lw_shared_ptr<schema const>, query::read_command const&, query::result_request, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > > const&, lw_shared_ptr<tracing::trace_state>, query::result_memory_limiter&, unsigned long)::{lambda(query::result_memory_accounter)#1}&&, std::tuple<query::result_memory_accounter>&&) at database.cc:?
column_family::query(lw_shared_ptr<schema const>, query::read_command const&, query::result_request, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > > const&, lw_shared_ptr<tracing::trace_state>, query::result_memory_limiter&, unsigned long) at ??:?
database::query(lw_shared_ptr<schema const>, query::read_command const&, query::result_request, std::vector<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > > const&, lw_shared_ptr<tracing::trace_state>, unsigned long) at ??:?
```

I benchmarked it and got the following results:

```
size = 256; elapsed = 4us
size = 512; elapsed = 8us
size = 1024; elapsed = 14us
size = 2048; elapsed = 21us
size = 4096; elapsed = 33us
size = 8192; elapsed = 51us
size = 16384; elapsed = 86us
size = 32768; elapsed = 150us
size = 65536; elapsed = 278us
size = 131072; elapsed = 531us
size = 262144; elapsed = 1032us
size = 524288; elapsed = 2026us
size = 1048576; elapsed = 4004us
size = 2097152; elapsed = 7943us
size = 4194304; elapsed = 15800us
size = 8388608; elapsed = 31731us
size = 16777216; elapsed = 64681us
size = 33554432; elapsed = 130752us
size = 67108864; elapsed = 263154us
```

Machine:

Core I7-5960X @ 3Ghz (C-states disabled, XMP and Turbo enabled)
64GB DDR4 2800Mhz

While 4us is fine and dandy for 246 bytes, we can see that 8MB already takes 15msec. 64MB takes 263msec.

Here is a flamegraph: 

<img width="1196" alt="screen shot 2017-10-10 at 23 00 23" src="https://user-images.githubusercontent.com/501746/31412959-0aaa33c6-ae0f-11e7-90e4-9ed388a728ad.png">

**Comment by duarten** [comment]
For reference, this is the benchmark:

```c++
return seastar::async([] {
    auto builder = schema_builder("ks", "cf")
            .with_column("pk", bytes_type, column_kind::partition_key)
            .with_column("ck", bytes_type, column_kind::clustering_key)
            .with_column("v", bytes_type, column_kind::regular_column);
    auto make_blob = [] (unsigned blob_size, int8_t prefix) {
        bytes b(blob_size, int8_t(0));
        std::copy_n(&prefix, sizeof(prefix), b.begin());
        return b;
    };
    auto schema = builder.build();
    auto pkey = partition_key::from_single_value(*schema, make_blob(128, 0));
    auto dk = dht::global_partitioner().decorate_key(*schema, pkey);
    auto prange = dht::partition_range::make_singular(dk);
    auto ckey = clustering_key::from_exploded(*schema, { make_blob(128, 1) });
    auto slice = partition_slice_builder(*schema).build();

    auto size = 256;
    while (size < (1 << 27)) {
        mutation m(pkey, schema);
        deletable_row& row = m.partition().clustered_row(*schema, ckey);
        auto cell = atomic_cell::make_live(1, make_blob(size, 4));
        row.cells().apply(schema->column_at(column_kind::regular_column, 0), std::move(cell));
        row.marker() = row_marker(1);
        auto source = mutation_source([m = std::move(m)] (
                        schema_ptr,
                        const dht::partition_range&,
                        const query::partition_slice&,
                        const io_priority_class&,
                        tracing::trace_state_ptr,
                        streamed_mutation::forwarding,
                        mutation_reader::forwarding) {
            return make_reader_returning(m);
        });

        auto ops = 100;
        std::chrono::duration<double> acc;
        auto start = std::chrono::high_resolution_clock::now();
        for (int i = 0; i < ops; ++i) {
            query::result::builder b(slice, query::result_request::only_digest, { });
            data_query(schema, source, prange, slice, 10000, query::max_partitions, gc_clock::now(), b, nullptr).get();
        }
        auto total = std::chrono::duration<double>(std::chrono::high_resolution_clock::now() - start);
        auto total_op = std::chrono::duration_cast<std::chrono::microseconds>(total).count() / ops;

        std::cout << "size = " << size << "; elapsed = " << total_op << "us" << std::endl;
        size = size << 1;
    }
});
```

**Comment by gleb-cloudius** [comment]
On Tue, Oct 10, 2017 at 10:04:10PM +0000, Duarte Nunes wrote:
> I benchmarked it and got the following results:
> 
> ```
> size = 256; elapsed = 4us
> size = 512; elapsed = 8us
> size = 1024; elapsed = 14us
> size = 2048; elapsed = 21us
> size = 4096; elapsed = 33us
> size = 8192; elapsed = 51us
> size = 16384; elapsed = 86us
> size = 32768; elapsed = 150us
> size = 65536; elapsed = 278us
> size = 131072; elapsed = 531us
> size = 262144; elapsed = 1032us
> size = 524288; elapsed = 2026us
> size = 1048576; elapsed = 4004us
> size = 2097152; elapsed = 7943us
> size = 4194304; elapsed = 15800us
> size = 8388608; elapsed = 31731us
> size = 16777216; elapsed = 64681us
> size = 33554432; elapsed = 130752us
> size = 67108864; elapsed = 263154us
> ```
> 
> Machine:
> 
> Core I7-5960X @ 3Ghz (C-states disabled, XMP and Turbo enabled)
> 64GB DDR4 2800Mhz
> 
> While 4us is fine and dandy for 246 bytes, we can see that 8MB already takes 15msec. 64MB takes 263msec.
> 
If a query is paged (as it should be) we limit page size to 1M which
takes 4ms. Yes, this is too much.

--
			Gleb.

**Comment by avikivity** [comment]
Perhaps we can switch to a faster hash (one with hardware support).

**Comment by slivne** [comment]
A bit of topic yet are we computing a digest for the complete row data or
only for the part the user requested ?

**Comment by duarten** [comment]
We should only be calculating the digest for the columns the user selected.

**Comment by slivne** [comment]
Adding information we had on the daily call - If a user is selecting a blob of 1MB and requesting metadata of that blob ttl or writetime - currently we do not have capability to compute digest only on the metadata and are forced to compute the digest on the blob and its metadata.

We have discussed the following options:
- Switch to a HW accelerated digest and how to make sure the complete cluster supports that
- Pushing down query information - in which case we would be able to compute the digest on the needed info.
- Adding "yield" spots in the computation path - that may help in some cases - yet in case of a large blob - not clear if it will help.

One other option that may help in such a case is maybe instead of computing the digest returning back the information that was requested - @gleb-cloudius - is there a way that a user can force a query on ``` select ttl(X) ... ``` to return back the query_result instead of computing the digest ?

**Comment by duarten** [comment]
The part about the metadata is not clear to me. If we do this in the context of read repair, wouldn't it be wrong to send the digest of the metadata instead of the value? Two different values may have equal metadata.

Yielding also wouldn't help much, as it would increase even more the latency of the query. We would also need to add defer points to the algorithm itself, for which we currentely use a third-party library.

**Comment by slivne** [comment]
We need to compute the digest of the relevant part of the returned query data - if the user requested only the ttl of a cell then we could compute the digest for that part and verify it is correct / fix only that part if needed.

Consider the following case:
two nodes A, B a row with element X stored in both where:
Node A: X = Node B: X
Node A: ttl(X) != Node B: ttl(x)

A query with CL=QUORUM of select ttl(X) ... on current master would "fix" the data (although the ttl(X) on both nodes is the same) and that was the only part the user requested

**Comment by duarten** [comment]
The ttl is part of the cell, so it will always appear in the digest. However, if we have:

Node A: X != Node B: X
Node A: ttl(X) = Node B: ttl(x)

Then we still want to repair.

**Comment by slivne** [comment]
I am not sure that is correct - the user requested a specific part of the
data

in a way its similar to stating the digest should cover the complete row /
partition and not only the part the user requested in the query.

- if we would have returned the query_result and not the digest that would
only be the ttl and not the complete cell data.

**Comment by gleb-cloudius** [comment]
On Wed, Oct 11, 2017 at 08:25:25PM +0000, Shlomi Livne wrote:
> One other option that may help in such a case is maybe instead of computing the digest returning back the information that was requested - @gleb-cloudius - is there a way that a user can force a query on ``` select ttl(X) ... ``` to return back the query_result instead of computing the digest ?
> 
Even query_result has a digest if CL > ONE. CL=ONE bypass digest
calculation (on recent enough version).

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Wed, Oct 11, 2017 at 01:29:21PM -0700, Duarte Nunes wrote:
> Yielding also wouldn't help much, as it would increase even more the latency of the query. We would also need to add defer points to the algorithm itself, for which we currentely use a third-party library.
> 
If a user created a query with a megabyte blob he cannot expect very
good latencies any way, the point of yielding is to not let slow query
to hurt other queries.

--
			Gleb.

**Comment by duarten** [comment]
On Oct 12, 2017 08:41, "Gleb Natapov" <notifications@github.com> wrote:

On Wed, Oct 11, 2017 at 01:29:21PM -0700, Duarte Nunes wrote:
> Yielding also wouldn't help much, as it would increase even more the
latency of the query. We would also need to add defer points to the
algorithm itself, for which we currentely use a third-party library.
>
If a user created a query with a megabyte blob he cannot expect very
good latencies any way, the point of yielding is to not let slow query
to hurt other queries.


I think 1MB is reasonable. True that for really big blobs it's a good idea
to yield.

**Comment by avikivity** [comment]
1ms compute on 1MB blob -> 1GB/s, we will never get that from a single core. Sub-millisecond latencies can only be provided on significantly smaller queries.

Our blobs are already fragmented into smaller chunks (currently we linearize them for processing, but in the future we won't). Fragmentation gives natural yield points.

**Comment by duarten** [comment]
Maybe we could add some metadata to each row in the cache, and cache a cell's hash in that metadata, which would be lazily populate.

**Comment by avikivity** [comment]
Interesting idea. Would increase footprint, perhaps do it for large cells only.

**Comment by avikivity** [comment]
Perhaps [xxhash](https://github.com/Cyan4973/xxHash). It's not cryptographic but might not matter.

**Comment by duarten** [comment]
Better results with xxhash:

```
size = 256; elapsed = 2us
size = 512; elapsed = 1us
size = 1024; elapsed = 1us
size = 2048; elapsed = 2us
size = 4096; elapsed = 2us
size = 8192; elapsed = 3us
size = 16384; elapsed = 5us
size = 32768; elapsed = 8us
size = 65536; elapsed = 14us
size = 131072; elapsed = 28us
size = 262144; elapsed = 59us
size = 524288; elapsed = 116us
size = 1048576; elapsed = 226us
size = 2097152; elapsed = 456us
size = 4194304; elapsed = 935us
size = 8388608; elapsed = 1848us
size = 16777216; elapsed = 4723us
size = 33554432; elapsed = 10507us
size = 67108864; elapsed = 21622us
```

It's 64bits instead of 128.

**Comment by slivne** [comment]
@duarten - are you really coding this - if not I'll move it to someone else

**Comment by duarten** [comment]
@slivne I do have a branch moving us to xxhash, yes. I'll finish it this week!
