### ISSUE TITLE
Streaming performed when node is removed blocks gossip

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2886]
*Installation details*
Scylla version (or git commit hash): 2.0+

Call chain: `storage_service::on_change()` -> `storage_service::handle_state_removing()` -> `storage_service::restore_replica_count()` -> `streamer->stream_async()`

Listeners run as part of gossip message processing, which is serialized. This means we won't be processing any gossip messages until streaming completes.

**Comment by slivne** [comment]
@tgrabiec is this a regression from 1.7 ?

**Comment by tgrabiec** [comment]
I think it is a regression
