### ISSUE TITLE
Cache the permissions checking results for prepared statements

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#2888]
Cache the permissions check result for a user for a specific prepared statement.

**Comment by vladzcloudius** [comment]
This issue is resulted by a discussion on a thread with the Message-ID: 20170810202139.GB18598@moon

**Comment by slivne** [comment]
@vladzcloudius - can we close this ?

If not what is missing ?

**Comment by slivne** [comment]
fixed by 4eb47d136b0ec13ccd2fb9b7e9936b0a7b37b06b

**Comment by slivne** [comment]
fixed by 4eb47d136b0ec13ccd2fb9b7e9936b0a7b37b06b
