### ISSUE TITLE
Materialized view writes seem "stuck"

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#2891]
Scylla version 2.0.0-0.20170929.e265c91
Cluster size: 1
OS CentOS 7.3

We are testing Scylla 2.0 experimental MV support with our existing Cassandra schema.  Scylla's performance is fabulous so far, much better than C* on same hardware.  However, we have twice gotten into a state where rows from a table are not being propagated to its materialized views.  In both cases, I have gotten "unstuck" by creating a new MV with the same definition and reading from the new MV instead.  I am currently in this situation.  Is there a way to enable tracing or a debug log to gather more detailed debugging information?  This condition survives a scylla restart so I can use a debug or nightly build server binary if it would help.  I've attached the relevant portion of our schema but I am not sure if it will be useful without state information from the node..

Here was the order of operations.

create table hosts...
create materialized view hosts_quarantined...
create materialized view hosts_systemguid...
create materialized view hosts_createdat...
create materialized view hosts_hostname...
insert row into hosts table.  All 4 MV's populated properly.  

Later I discovered that hosts_systemguid and hosts_hostname were not being written to so I tried recreating them..

drop materialized view hosts_systemguid
drop materialized view hosts_hostname
truncate hosts
create materialized view hosts_systemguid...
create materialized view hosts_hostname...
insert row into hosts table.  Still no rows in hosts_systemguid or hosts_hostname..

So I dropped them again and created new MVs with different name and same definition

drop materialized view hosts_systemguid
drop materialized view hosts_hostname
truncate hosts
create materialized view hosts_systemguid_mv...
create materialized view hosts_hostname_mv...
insert row into hosts table.  Both new MVs got the inserts.  

This worked fine for four days.. 2017-10-05 21:26:08+0000 until 2017-10-09 16:53:59+0000.  There were 71 new rows inserted into hosts table during this time and every insert and update was propagated properly to the new MV's.  I was happy.  But today I noticed that none of these 4 MV's have gotten any updates since 2017-10-09 16:53:59+0000 despite 19 new rows inserted into hosts table since then.  

Today I created a new hosts_systemguid_mv1 with the same schema as hosts_systemguid_mv and all new inserts and updates since the MV creation have been propagated to hosts_systemguid_mv1.  However, none of the four other MV's are getting updates, even hosts_systemguid_mv that has the exact same schema definition as hosts_systemguid_mv1.

Any suggestions on where to look or how to get more information that might help debug this situation?  Thanks.

Jonathan

[schema.txt](https://github.com/scylladb/scylla/files/1380777/schema.txt)

**Comment by duarten** [comment]
This might have been fixed by 115ff1095edc59097fc599e491be8a3538366bb7, which is not in 2.0. Please note that MV is still an experimental feature and under heavy development.

**Comment by dorlaor** [comment]
Does our nightly contain it?

**Comment by veramine** [comment]
If so, I will try it.  We are brave.  This is not our production instance so we can test whatever.

**Comment by duarten** [comment]
Yes, the nightly does.

**Comment by veramine** [comment]
What is the update procedure from 2.0 to nightly?  Will it work to 

sudo wget -O /etc/yum.repos.d/scylla.repo http://repositories.scylladb.com/scylla/repo/984fcac6b9c111f0894816cd1a8e07ab/centos/master/latest/scylladb.repo

and then

yum update scylla-server 

?

**Comment by veramine** [comment]
I have since deployed our product to larger, more powerful Azure node and have not hit this issue again.  Might be due to limited io bandwidth, not sure.  Regardless, might be less important.

**Comment by duarten** [comment]
With the same version or with the nightly version?

**Comment by veramine** [comment]
Same version (2.0).  I wanted to test clustering and struggled to get nightly version to join the cluster so I used the same version.

**Comment by veramine** [comment]
We hit this again today with our two node cluster.  I am now decommissioning one of the nodes to see if I can hit it again with the more powerful hardware and single node cluster.

**Comment by veramine** [comment]
I hit this again with the one node cluster.  This condition had not previously resolved itself on its own.  The only way to fix it had been to drop the materialized view, re-create it, and update all the rows in the table to propagate the data to the materialized view.  This time, instead I upgraded to the nightly build and everything seems to be working again (no need to drop and re-create).

**Comment by duarten** [comment]
The issue would never have resolved on itself since it was a bug, but the nightly may contain the fix.

**Comment by veramine** [comment]
I built an RPM from branch-2.0 with the https://github.com/scylladb/scylla/commit/115ff1095edc59097fc599e491be8a3538366bb7 fix and updated my one node test cluster to run this new version 2.0.1-0.20171118.b1899f0.  

Immediately after updating and starting scylla, I tried writing to an existing base table row and the corresponding materialized views was not updated.  I also rebooted the server and still was not getting any updates in MV's after updating an existing row.  However, I then dropped all my materialized views and recreated them with the same schema.  Every new write to the base table was then immediately being also written to the materialized views.  I think this is an improvement over 2.0 because previously I had to create an MV with a different name in order to get un-stuck.  However, I am still a little concerned that I might hit this issue again because 2.0.1-0.20171118 did not immediately start working for new writes after the update the way the nightly did.  

I'll update this thread if I am able to hit this issue again.  It's been working for several hours now with low load (a few thousand writes per minute) and regular background compaction.

**Comment by duarten** [comment]
@veramine Did you hit this issue again or can we close it?

**Comment by veramine** [comment]
Never hit it again on any build with the https://github.com/scylladb/scylla/commit/115ff1095edc59097fc599e491be8a3538366bb7 <https://github.com/scylladb/scylla/commit/115ff1095edc59097fc599e491be8a3538366bb7> fix.  Feel free to close it for any release that includes that fix.  Thanks!
