### ISSUE TITLE
Website repo for "Nightly unstable release" returns 403 Forbidden

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#2897]
I'd like to test the nightly build but I am not having much luck getting it on CentOS 7.3.  The repo listed at http://www.scylladb.com/download/centos_rpm/ under "More Versions" returns 403 to me:

$ sudo wget -O /etc/yum.repos.d/scylla.repo http://repositories.scylladb.com/scylla/repo/984fcac6b9c111f0894816cd1a8e07ab/centos/master/latest/scylladb.repo
--2017-10-15 03:02:18--  http://repositories.scylladb.com/scylla/repo/984fcac6b9c111f0894816cd1a8e07ab/centos/master/latest/scylladb.repo
Resolving repositories.scylladb.com (repositories.scylladb.com)... 54.239.132.42, 54.239.132.191, 54.239.132.87, ...
Connecting to repositories.scylladb.com (repositories.scylladb.com)|54.239.132.42|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://repositories.scylladb.com/scylla/repo/984fcac6b9c111f0894816cd1a8e07ab/centos/master/latest/scylladb.repo [following]
--2017-10-15 03:02:18--  https://repositories.scylladb.com/scylla/repo/984fcac6b9c111f0894816cd1a8e07ab/centos/master/latest/scylladb.repo
Connecting to repositories.scylladb.com (repositories.scylladb.com)|54.239.132.42|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2017-10-15 03:02:18 ERROR 403: Forbidden.

**Comment by tzach** [comment]
@amnonh can you please take a look?

**Comment by amnonh** [comment]
It was reported yesterday, I'm already looking at it

**Comment by veramine** [comment]
Great, thank you!

**Comment by veramine** [comment]
I checked repo this morning and the scylladb-nightly.repo is available now!  However, not sure if it is pointing to any newer bits...

[jness@scyllatest1 ~]$ rpm -qa | grep scylla-server
scylla-server-2.0.0-0.20170929.e265c91.el7.centos.x86_64
[jness@scyllatest1 ~]$ sudo yum update scylla\* -y
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * epel: mirror.sjc02.svwh.net
No packages marked for update

**Comment by slivne** [comment]
Vermaine Hi,

The repo indeed works the version in the repo is
scylla-server-666.development-0.20170729.e624031.el7.centos.x86_64

I installed scylla from the nightly repo and it works.

We haven't tested an upgrade between the 2.0 to nightly - it may also
relate to the dates.

Can you try and uninstall scylla and install it.

**Comment by veramine** [comment]
Thank you, good suggestion!  After removing the old scylla version and clearing yum cache, I was able to get  666.development-0.20170729.e624031.el7.centos.  Everything appears to have installed properly but unfortunately something is preventing the service from being started via systemd:
```
[jness@scyllatest5 scylla]$ sudo systemctl start scylla-server
Job for scylla-server.service failed because the control process exited with error code. See "systemctl status scylla-server.service" and "journalctl -xe" for details.
[jness@scyllatest5 scylla]$ sudo journalctl -xe
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit scylla-server.service has failed.
-- 
-- The result is failed.
Oct 19 00:14:46 scyllatest5 scylla[1961]:  [shard 2] compaction_manager - Stopped
Oct 19 00:14:46 scyllatest5 systemd[1]: Dependency failed for Scylla JMX.
-- Subject: Unit scylla-jmx.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit scylla-jmx.service has failed.
-- 
-- The result is dependency.
Oct 19 00:14:46 scyllatest5 scylla[1961]:  [shard 3] compaction_manager - Asked to stop
Oct 19 00:14:46 scyllatest5 systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
Oct 19 00:14:46 scyllatest5 scylla[1961]:  [shard 3] compaction_manager - Stopped
Oct 19 00:14:46 scyllatest5 systemd[1]: Dependency failed for Run Scylla Housekeeping daily mode.
-- Subject: Unit scylla-housekeeping-daily.timer has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit scylla-housekeeping-daily.timer has failed.
-- 
-- The result is dependency.
Oct 19 00:14:46 scyllatest5 polkitd[566]: Unregistered Authentication Agent for unix-process:1952:52869 (system bus name :1.34, object path /org/freedesktop/PolicyKit1/AuthenticationAge
Oct 19 00:14:46 scyllatest5 systemd[1]: Job scylla-housekeeping-daily.timer/start failed with result 'dependency'.
Oct 19 00:14:46 scyllatest5 systemd[1]: Dependency failed for Run Scylla Housekeeping restart mode.
-- Subject: Unit scylla-housekeeping-restart.timer has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit scylla-housekeeping-restart.timer has failed.
-- 
-- The result is dependency.
Oct 19 00:14:46 scyllatest5 systemd[1]: Job scylla-housekeeping-restart.timer/start failed with result 'dependency'.
Oct 19 00:14:46 scyllatest5 systemd[1]: Unit scylla-server.service entered failed state.
Oct 19 00:14:46 scyllatest5 systemd[1]: scylla-server.service failed.
```

**Comment by veramine** [comment]
This is working for me now.  You can close this bug.  Thanks for the help!
