### ISSUE TITLE
Not implemented: RANGE_QUERIES

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#29]
This worked for me in the past, but it does not work anymore.

asias@hjpc urchin$ for i in {1..2}; do cqlsh 127.0.0.$i -e "select * from ks.tb";done
<stdin>:1:<ErrorMessage code=0000 [Server error] message="Not implemented: RANGE_QUERIES">
<stdin>:1:<ErrorMessage code=0000 [Server error] message="Not implemented: RANGE_QUERIES">

I tested with this commit:
commit 5339783d560df9cdb41ade0a6f5364ea13aaf768
Author: Avi Kivity <avi@cloudius-systems.com>
Date:   Sun Jul 19 21:41:42 2015 +0300

    build: handle case where ninja command is named 'ninja-build'

**Comment by penberg** [comment]
@pdziepak @tgrabiec this is fixed by c2b53c5282764d33120d6c1b3203dc369cfd7fe2, no?

**Comment by tgrabiec** [comment]
yes
