### ISSUE TITLE
system_traces.events activity filed text is indent to the right

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2901]
*Installation details*
OS (RHEL/CentOS/Ubuntu/AWS AMI): Scylla 2.0

When looking at the the system_traces.events the activity filed text is indent to the right (like Hebrew?) which make it hard to read

![image](https://user-images.githubusercontent.com/170200/31655642-2e97bdd0-b332-11e7-97a7-2f052108c581.png)

**Comment by tzach** [comment]
@vladzcloudius ?

**Comment by vladzcloudius** [comment]
@tzach That's the way `cqlsh` represents it.

**Comment by tzach** [comment]
OK, I'm not the first one with this question, and its a UX design decision 
https://stackoverflow.com/questions/28848315/why-does-cqlsh-right-align-strings
