### ISSUE TITLE
Minor discrepency between Cassandra and Scylla ALTER TABLE syntax

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#2907]
Scylla version 2.0.0-0.20170929.e265c91 experimental=true
Cluster size: 1
OS CentOS 7.3

Cassandra allows for multiple columns to be added to a table in one alter table statement by specifying a comma-delimited list of column names inside parenthesis, as described at https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlAlterTable.html.  Scylla reports a SyntaxException when it encounters the opening parenthesis.  Does not work to specify multiple columns outside parenthesis either.  Alter table works fine one columns at a time.

```
cqlsh:veraminetest> alter table a add (b text,c set<text>,d timestamp,e boolean,f boolean,g boolean);
SyntaxException: line 1:40 no viable alternative at input '('
cqlsh:veraminetest> alter table a add (b text);
SyntaxException: line 1:40 no viable alternative at input '('
cqlsh:veraminetest> alter table a add b text;
cqlsh:veraminetest> alter table a add c set<text>,d timestamp,e boolean,f boolean,g boolean;
SyntaxException: line 1:59  : syntax error...
```

**Comment by nyh** [comment]
This feature was added to Apache Cassandra in version 3.6 - see https://issues.apache.org/jira/browse/CASSANDRA-10411

**Comment by bhalevy** [comment]
Duplicated by #3691
