### ISSUE TITLE
is there any c++ client example to connect scylladb? and what driver can be used for c++? 

### ISSUE THREAD

**Issue by onesea** [scylladb/scylla#2911]
i found java driver in github, bot not c++

**Comment by dorlaor** [comment]
You should use the C* c++ driver: https://github.com/datastax/cpp-driver
We're about to double down on drivers and add more docs, binaries and
examples,
today we only do a decent job with go:
http://docs.scylladb.com/getting-started/scylla_drivers/

**Comment by onesea** [comment]
seemed there are test programs in the test directory which can connect scylladb server in c++. they should not used any external driver code, right? can i write client program like that?

**Comment by dorlaor** [comment]
Correct, you should be able to build them and run them against a Scylla
cluster for fun and profit ;)

**Comment by tzach** [comment]
@onesea I'm closing this issue, assuming you got an answer.
We will be happy to discuss further on the mailing list https://groups.google.com/forum/#!forum/scylladb-users
We are working to add driver examples to Scylla documentation
