### ISSUE TITLE
Configure.py fails on Centos7

### ISSUE THREAD

**Issue by threedliteguy** [scylladb/scylla#2916]
*Installation details*
Scylla version (or git commit hash): latest open source
Cluster size: local
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos 7.3
After running prior quick start steps successfully:
Configure.py fails with 
Installed boost version too old
Missing libsystemd
Updating boost via yum doesn't help.

**Comment by avikivity** [comment]
Use the copr repository https://copr.fedorainfracloud.org/coprs/scylladb/scylla-3rdparty/ for missing packages, and add `--cflags='-I /opt/scylladb/include -L /opt/scylladb/lib64'.

**Comment by tzach** [comment]
@avikivity should we add this to the [CentOS installation guide](http://www.scylladb.com/download/centos_rpm/) ?
7.3 only or 7.2 too?

**Comment by tzach** [comment]
@avikivity @syuu1228 ping

**Comment by avikivity** [comment]
We should fix configure.py to recommend running `sudo ./install-dependencies.sh` if dependencies are not found, and make sure `install-dependencies.sh` knows about that repo.

**Comment by syuu1228** [comment]
I already sent a patch for this, please review "[PATCH scylla] install-dependencies.sh: use package build dependencies instead of manually specifies dependent packages"

**Comment by slivne** [comment]
@syuu1228 ping - avi had some comments on the patch

**Comment by tzach** [comment]
@denesb did you sent patches for this issue?

**Comment by denesb** [comment]
Yes I recently sent patches to fix build issues on Centos7 and they address all issues here, except `libsystemd`, but that is an optional dependency and is trivial to add. I'll send a patch for that too.

**Comment by denesb** [comment]
@tzach I think this can be closed.
