### ISSUE TITLE
Scylla nightly permanently fails to restart due to read_timeout_exception on system_schema.tables after creating 100+ tables

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#2923]
Scylla version 666.development-0.20170729.e624031.el7.centos 
Cluster size: 1
OS CentOS 7.4

Hardware: Azure Standard "L4S" instance (Intel® Xeon® processor E5 v3 family)
4 vcpus, 32 GB memory, local instance SSD
Azure claims max uncached disk throughput: IOPS / MBps 5,000 / 125
iotune reports 10GB written in 52 seconds, 23748 IOPS

I'd like to test the nightly build to see if https://github.com/scylladb/scylla/issues/2891 is fixed by https://github.com/scylladb/scylla/commit/115ff1095edc59097fc599e491be8a3538366bb7.  Unfortunately, I'm unable to use the nightly build after loading our schema (no data, just the schema).  Even after removing the materialized views and any "experimental" feature, I still hit this permanent failure.  After loading the schema every attempt to start or restart the database fails.  I suspect it is due to the large number of tables because it seems to work ok with fewer tables.  I've attached the specific minimized test schema I am using to hit this and the commands I run from VM creation to failure.  If you have any trouble reproducing in your own environment you might try doing so on Azure L4S.  Thanks.

```
$ sudo yum remove -y abrt
..
$ sudo yum install epel-release
...
$ sudo curl -o /etc/yum.repos.d/scylla.repo -L http://repositories.scylladb.com/scylla/repo/984fcac6b9c111f0894816cd1a8e07ab/centos/scylladb-nightly.repo
...
$ sudo yum install scylla
...
Installed:
  scylla.x86_64 0:666.development-0.20170729.e624031.el7.centos                                                                                                              
...
$ sudo vi /etc/scylla/scylla.yaml  # changed cluster name
$ sudo umount /mnt/resource     # frees up /dev/sdb1
$ sudo scylla_setup                     # yes to all except CPU scaling, network card optimization
...
$ sudo init 6          # to disable SELinux
...
$ cqlsh
Connected to veramine at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> quit
$ cqlsh -e "SOURCE '/tmp/tableschema.txt'"
$ nodetool drain
$ sudo systemctl restart scylla-server
Job for scylla-server.service failed because the control process exited with error code. See "systemctl status scylla-server.service" and "journalctl -xe" for details.
$ sudo journalctl | grep -v collectd 
...
Oct 25 19:02:36 scyllax scylla[1355]:  [shard 0] database - Keyspace system: Reading CF compaction_history
Oct 25 19:02:36 scyllax scylla[1355]:  [shard 0] legacy_schema_migrator - Moving 0 keyspaces from legacy schema tables to the new schema keyspace (system_schema)
Oct 25 19:02:36 scyllax scylla[1355]:  [shard 0] legacy_schema_migrator - Dropping legacy schema tables
Oct 25 19:02:36 scyllax scylla[1355]:  [shard 0] legacy_schema_migrator - Completed migration of legacy schema tables
Oct 25 19:02:41 scyllax scylla[1355]:  [shard 0] seastar - Exiting on unhandled exception: exceptions::read_timeout_exception (Operation timed out for system_schema.tables - received only 0 responses from 1 CL=ONE.)
Oct 25 19:02:41 scyllax scylla[1355]:  [shard 0] compaction_manager - Asked to stop
Oct 25 19:02:41 scyllax scylla[1355]:  [shard 3] compaction_manager - Asked to stop
Oct 25 19:02:41 scyllax scylla[1355]:  [shard 3] compaction_manager - Stopped
Oct 25 19:02:41 scyllax scylla[1355]:  [shard 1] compaction_manager - Asked to stop
Oct 25 19:02:41 scyllax scylla[1355]:  [shard 1] compaction_manager - Stopped
Oct 25 19:02:41 scyllax scylla[1355]:  [shard 2] compaction_manager - Asked to stop
Oct 25 19:02:41 scyllax scylla[1355]:  [shard 0] compaction_manager - Stopped
Oct 25 19:02:41 scyllax scylla[1355]:  [shard 2] compaction_manager - Stopped
Oct 25 19:02:41 scyllax systemd[1]: scylla-server.service: main process exited, code=exited, status=1/FAILURE
Oct 25 19:02:41 scyllax systemd[1]: Failed to start Scylla Server.
Oct 25 19:02:41 scyllax systemd[1]: Dependency failed for Scylla JMX.
Oct 25 19:02:41 scyllax systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
Oct 25 19:02:41 scyllax systemd[1]: Dependency failed for Run Scylla Housekeeping daily mode.
Oct 25 19:02:41 scyllax systemd[1]: Job scylla-housekeeping-daily.timer/start failed with result 'dependency'.
Oct 25 19:02:41 scyllax systemd[1]: Dependency failed for Run Scylla Housekeeping restart mode.
Oct 25 19:02:41 scyllax systemd[1]: Job scylla-housekeeping-restart.timer/start failed with result 'dependency'.
Oct 25 19:02:41 scyllax systemd[1]: Unit scylla-server.service entered failed state.
Oct 25 19:02:41 scyllax systemd[1]: scylla-server.service failed.
Oct 25 19:02:41 scyllax polkitd[596]: Unregistered Authentication Agent for unix-process:1336:12631 (system bus name :1.32, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en_US.UTF-8) (disconnected from bus)
Oct 25 19:03:22 scyllax sudo[1390]:    jness : TTY=pts/0 ; PWD=/home/jness ; USER=root ; COMMAND=/bin/journalctl
...

$ sudo systemctl start scylla-server
Job for scylla-server.service failed because the control process exited with error code. See "systemctl status scylla-server.service" and "journalctl -xe" for details.
$ sudo systemctl start scylla-server
Job for scylla-server.service failed because the control process exited with error code. See "systemctl status scylla-server.service" and "journalctl -xe" for details.
...
```
[tableschema.txt](https://github.com/scylladb/scylla/files/1415848/tableschema.txt)
[journalctl-all.txt](https://github.com/scylladb/scylla/files/1415862/journalctl-all.txt)

**Comment by veramine** [comment]
I attempted to repro on AWS and could not.  I started with the Scylla ami-857a49e5 running on an i3.large instance, uninstalled the 2.0 release, installed the nightly build, loaded the same table schema, and everything worked.  I'd like to get this working on Azure though as the rest of our infrastructure is running on Azure.

**Comment by veramine** [comment]
Good news!  I booted a larger Azure VM, L8S, and it worked.  This VM has 8 cores and 64gb memory.  iotune during scylla_setup recommended --max-io-requests: 108.  No timeout during the restart this time.  I am unblocked now and will continue testing.

**Comment by slivne** [comment]
@roydahan - lets try to reproduce this on 2.0/2.1 - with the schema the user provided and a setup parallel in resources (4 vcpus, 32 GB) - its a single node setup - not clear why we should have an issue with just creating schemas

**Comment by slivne** [comment]
@roydahan - can we test this

**Comment by slivne** [comment]
@roydahan  - are we able to restart with the 100+ tables ?

**Comment by amoskong** [comment]
I didn't reproduce this problem with  4 vcpu, 32G mem
- 666.development-0.20180205.6919c7434
- 2.1.rc2-0.20180122.5e44bf97f

**Comment by slivne** [comment]
@veramine - would it be possible to share your schema so we can test using your schema.

**Comment by amoskong** [comment]
@slivne I'm using @veramine 's schema, which was provided in https://github.com/scylladb/scylla/files/1415848/tableschema.txt

**Comment by slivne** [comment]
a step ahead - great :+1:
