### ISSUE TITLE
Select statement cannot contain count(*) and other count(...)

### ISSUE THREAD

**Issue by hagrid-the-developer** [scylladb/scylla#2925]
*Installation details*
Scylla version (or git commit hash):1701fc2e507eb85b076b9cff54a6e84e5c244180

This command doesn't work:

    select count(*), count(co_ppm) from air_quality_data;
        SyntaxException: <Error from server: code=2000 [Syntax error in CQL query] message="line 1:15  : syntax error...
       ">

but this command does:

      select count(sensor_id), count(co_ppm) from air_quality_data;

      system.count(sensor_id) | system.count(co_ppm)
     -------------------------+----------------------
                            2 |                    2

    (1 rows)

**Comment by denesb** [comment]
`COUNT(*)` and `COUNT(1)` are a special case and cannot be mixed with any other aggregate functions or column selections. Not sure if this is a bug or deliberate. I seem to recall that we already have an issue about it but I couldn't find it now.

**Comment by hagrid-the-developer** [comment]
I tried it in C* 3.6 and it seems to work:

    select count(*), count(co_ppm) from air_quality_data;

     count | system.count(co_ppm)
    -------+----------------------
         3 |                    3

    (1 rows)

    Warnings :
    Aggregation query used without partition key

**Comment by denesb** [comment]
Then it's possibly another case that we inherited from C* 2.{0,1} but they changed since.

**Comment by duarten** [comment]
Duplicates #2218.
