### ISSUE TITLE
Timed out reads should be dropped by a local node.

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#2928]
Similar to #2927 but for local reads. Local writes are dropped after timeout, reads should do the same.

**Comment by tgrabiec** [comment]
#2927 is about all reads, local and non-local. Is there any difference?

**Comment by gleb-cloudius** [comment]
On Thu, Nov 02, 2017 at 08:20:37AM +0000, Tomasz Grabiec wrote:
> #2927 is about all reads, local and non-local. Is there any difference?
> 
From the code point of view yes. As I see it #2927 is about propagating
timeout through RPC and timing out in RPC queues (sender and receiver)
and this one is about the code path in the database.cc. There will be
two patches, so better to have two issues.

--
			Gleb.

**Comment by tgrabiec** [comment]
I think we should propagate the timeout all the way through, including database layer. Does it make sense to timeout only at RPC level and not at database level? If not, it should be a single series, and a single issue.

**Comment by gleb-cloudius** [comment]
On Thu, Nov 02, 2017 at 08:32:04AM +0000, Tomasz Grabiec wrote:
> I think we should propagate the timeout all the way through, including database layer. Does it make sense to timeout only at RPC level and not at database level? If not, it should be a single series, and a single issue.
> 
Timing out on RPC level only will make things better but obviously its
only half of a fix. It was two different fixes for write case. The one
for RPC I can write in a day (probably) and can send shortly. The one
for database.cc will be much more involved and probably done by someone
else since I am not to familiar with the internals.

--
			Gleb.

**Comment by tgrabiec** [comment]
2017-11-02 9:36 GMT+01:00 Gleb Natapov <notifications@github.com>:

> On Thu, Nov 02, 2017 at 08:32:04AM +0000, Tomasz Grabiec wrote:
> > I think we should propagate the timeout all the way through, including
> database layer. Does it make sense to timeout only at RPC level and not at
> database level? If not, it should be a single series, and a single issue.
> >
> Timing out on RPC level only will make things better but obviously its
> only half of a fix. It was two different fixes for write case. The one
> for RPC I can write in a day (probably) and can send shortly. The one
> for database.cc will be much more involved and probably done by someone
> else since I am not to familiar with the internals.
>

I see, ok.

**Comment by gleb-cloudius** [comment]
On Thu, Nov 02, 2017 at 08:51:30AM +0000, Tomasz Grabiec wrote:
> 2017-11-02 9:36 GMT+01:00 Gleb Natapov <notifications@github.com>:
> 
> > On Thu, Nov 02, 2017 at 08:32:04AM +0000, Tomasz Grabiec wrote:
> > > I think we should propagate the timeout all the way through, including
> > database layer. Does it make sense to timeout only at RPC level and not at
> > database level? If not, it should be a single series, and a single issue.
> > >
> > Timing out on RPC level only will make things better but obviously its
> > only half of a fix. It was two different fixes for write case. The one
> > for RPC I can write in a day (probably) and can send shortly. The one
> > for database.cc will be much more involved and probably done by someone
> > else since I am not to familiar with the internals.
> >
> 
> I see, ok.
> 
And when I start looking into it I saw that RPC part is fully
implemented already, so only database.cc changes are left to be
implemented.

--
			Gleb.
