### ISSUE TITLE
shutdown: flushout commitlogs and then exit

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#293]

**Comment by asias** [comment]
Any update on this issue regarding clean shutdown?

We have tons of 

 // #293 - do not stop anything
 // engine().at_exit([] { return db::get_batchlog_manager().stop(); });

which is a workaround at the moment. 

Do we want to fix before GA?

**Comment by avikivity** [comment]
We don't, it's too hard, but it's clear we will have to address it immediately afterwards.  So don't leave any future without someone waiting for it.

We will drop the use of `at_exit` completely in favor of `seastar::sharded::stop()`.

**Comment by asias** [comment]
On Wed, Jan 27, 2016 at 4:19 PM, Avi Kivity <notifications@github.com>
wrote:

> We don't, it's too hard, but it's clear we will have to address it
> immediately afterwards. So don't leave any future without someone waiting
> for it.
>
> We will drop the use of at_exit completely in favor of
> seastar::sharded::stop().
>

We at least need one of the at_exit callback to stop all the services.

See my patch:

[PATCH scylla v1 3/4] storage_service: Add drain on shutdown logic


>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/293#issuecomment-175476067>.
>



-- 
Asias

**Comment by avikivity** [comment]
at_exit is fine for now, but in the future, main will look like

future<> started = (all the start junk)
return started.then( wait for engine.stopped().then (start stopping things))

and we return that to app_template.run().
