### ISSUE TITLE
`config_test` is broken

### ISSUE THREAD

**Issue by hakuch** [scylladb/scylla#2933]
*Installation details*
Scylla version (or git commit hash): 2e96069f2f24ecbc2b4ec17b4c4edbce113ab33b

`config_test` fails on `master`:

```
Running 1 test case...
WARN  2017-11-03 13:53:53,962 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
unknown location(0): fatal error: in "test_parse_yaml": std::invalid_argument: Option memtable_allocation_typeis not applicable
seastar/tests/test-utils.cc(40): last checkpoint

*** 1 failure is detected in the test module "tests/config_test.cc"
```
I believe this failure was introduced in c468e59817c1242f7cef9e0bc4f6d4944ea3473c.

@duarten @elcallio

**Comment by duarten** [comment]
@pdziepak pointed this out on the mailinglist. Some fixes are needed to that patch.

**Comment by penberg** [comment]
Bonus points to whoever fixes that missing space in the exception error message:

```
Option memtable_allocation_typeis not applicable
                               ^ insert space here
```
