### ISSUE TITLE
enhanced network isn't enabled in instance to build new ami

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#2936]
*Installation details*
Scylla version (or git commit hash): latest master: 2e96069
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

It's failed to setup scylla for ec2_check failed (the enhanced networking wasn't enabled in aws instance which was used to build ami), then ami building failed.

Error message:  Enhanced networking is disabled!

Expected driver: ixgbevf (c4.xlarge)
Current driver: vif

```
[amos@amos-centos7 scylla]$ cat dist/ami/scylla.json |grep enhanced
      "enhanced_networking": true,

dist/ami/variables.json
{
    "access_key": "xxxxxxxxxx",
    "secret_key": "xxxxxxxxxxx",
    "subnet_id": "subnet-ec4a72c4",
    "security_group_id": "sg-c5e1f7a0",
    "region": "us-east-1",
    "associate_public_ip_address": "true",
    "instance_type": "c4.xlarge"
}
```

@syuu1228 @glommer

**Comment by amoskong** [comment]
We can workaround the issue by skipping ec2_check.

option 1: clean scylla_ec2_check script before setup
```
echo "exit 0" > /usr/lib/scylla/scylla_ec2_check
chmod +x /usr/lib/scylla/scylla_ec2_check
```

option 2: use --no-ec2-check to skip ec2 check

**Comment by syuu1228** [comment]
Okay, I'll try to handle it..

**Comment by amoskong** [comment]
[PATCH scylla-ami] scylla_install_ami: skip ec2_check while building AMI
Takuya's patch works, wait to be applied.
