### ISSUE TITLE
rpm: auto_bootstrap should be set to true by default

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#294]
Currently, 

cat /var/lib/scylla/conf/scylla.yaml

auto_bootstrap: false

**Comment by slivne** [comment]
@asias - is this in the AMI or in general - if its in general why not update the scylla.yaml

**Comment by asias** [comment]
On Mon, Dec 21, 2015 at 8:54 PM, slivne <notifications@github.com> wrote:

> @asias <https://github.com/asias> - is this in the AMI or in general - if
> its in general why not update the scylla.yaml
>

It is in general. cassandra.yaml does not include this option.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/294#issuecomment-166297767>.
>



-- 
Asias

**Comment by slivne** [comment]
#505
