### ISSUE TITLE
Dependency failed for Run Scylla Housekeeping daily/restart mode

### ISSUE THREAD

**Issue by baiwfg2** [scylladb/scylla#2943]
I installed scylla by adding the scylla-2.0.repo. When I use `systemctl start scylla-server` to start, it failed. When using `journalctl` , I got:

> [root@10.110.36.139 scylla]# journalctl -xe
>  Unit scylla-jmx.service has failed.
>  The result is dependency.
> Nov 08 17:43:27 10.110.36.139 systemd[1]: Job scylla-jmx.service/start failed with result 'dependency'.
> Nov 08 17:43:27 10.110.36.139 systemd[1]: Dependency failed for Run Scylla Housekeeping daily mode.
>  Subject: Unit scylla-housekeeping-daily.timer has failed
>  Defined-By: systemd
>  Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel 
>  Unit scylla-housekeeping-daily.timer has failed. 
>  The result is dependency.
> Nov 08 17:43:27 10.110.36.139 systemd[1]: Job scylla-housekeeping-daily.timer/start failed with result 'dependency'.
> Nov 08 17:43:27 10.110.36.139 systemd[1]: Dependency failed for Run Scylla Housekeeping restart mode.
>  Subject: Unit scylla-housekeeping-restart.timer has failed
>  Defined-By: systemd
>  Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel 
>  Unit scylla-housekeeping-restart.timer has failed.
>  The result is dependency.
> Nov 08 17:43:27 10.110.36.139 systemd[1]: Job scylla-housekeeping-restart.timer/start failed with result 'dependency'.
> Nov 08 17:43:27 10.110.36.139 systemd[1]: Unit scylla-server.service entered failed state.
> Nov 08 17:43:27 10.110.36.139 systemd[1]: scylla-server.service failed.
> Nov 08 17:43:27 10.110.36.139 polkitd[980]: Unregistered Authentication Agent for unix-process:19694:2981725716 (system bus name :1.234190, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en
> Nov 08 17:45:33 10.110.36.139 crontab[21738]: (root) LIST (root)
> Nov 08 17:46:09 10.110.36.139 crontab[22643]: (root) LIST (root)
> Nov 08 17:46:37 10.110.36.139 crontab[23659]: (root) LIST (root)
> Nov 08 17:50:01 10.110.36.139 systemd[1]: Started Session 108252 of user root.
>  Subject: Unit session-108252.scope has finished start-up
>  Defined-By: systemd
>  Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

I can start it on my another node of same OS. I don't see what's going wrong here.  Help is appreciated.

*Installation details*
Scylla version (or git commit hash): 2.0.0-0.20170929.e265c91
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI):CentOs 7

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by baiwfg2** [comment]
Luckily I found the answer. It turns out that I misconfigured scylla for the first time, then when I start it for the second time, it would show such error. So I clean all stuff in data directory including /var/lib/scylla/commitlog/* /var/lib/scylla/data/*, then start it again, it will be ok.

**Comment by penberg** [comment]
@baiwfg2 Did you see any other error messages in `journalctl _COMM=scylla`?
