### ISSUE TITLE
Scanning read may temporarily not return data for uncached partition range if memory allocation failure happens at certain place

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2944]
Scylla version (or git commit hash): 2.0+

If assignment to `_lower_bound` in the `_secondary_in_progress = true;` case in `scanning_and_populating_reader::do_read_from_primary()` throws due to allocation failure, the update section will be retried and we will take the `not_moved` path, skipping the range which was discontinuous.

**Comment by slivne** [comment]
@tgrabiec - was this fixed ?

**Comment by tgrabiec** [comment]
Patches are on the mailing list
