### ISSUE TITLE
Support timeuuid function

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#2950]
*Installation details*
Scylla version (or git commit hash): 2.0

Add support function `now`, `currentTimeUUID` (alias of now), `minTimeuuid` and `maxTimeuuid`

source: http://cassandra.apache.org/doc/latest/cql/functions.html#timeuuid-functions

**Comment by slivne** [comment]
now is supported
minTimeuuid, maxTimeuuid should be part of 2.1

currentTimeUUID is missing

**Comment by slivne** [comment]
currenttimeuuid is part of #2949  all the rest are part of 2.1 - closing this

**Comment by slivne** [comment]
need to validate it works

**Comment by slivne** [comment]
@roydahan can we validate this is working - do we have a dtest for this ?

**Comment by roydahan** [comment]
We have timeuuid_test in cql_additional_tests.py for minTime and maxTime

**Comment by slivne** [comment]
Tx moving this to 2.2 ...

**Comment by slivne** [comment]
@roydahan ping

**Comment by roydahan** [comment]
we can close this one.
