### ISSUE TITLE
scylla_dev_mode_setup not working on GCE centos

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#2953]
on GCE centos verify_args is missing, trying to run scylla_dev_mod_setup:

/usr/lib/scylla/scylla_dev_mode_setup: line 15: verify_args: command not found

**Comment by tzach** [comment]
@syuu1228 can you please take a look?

**Comment by syuu1228** [comment]
Duplicated with #2945, and fix is already on the ML, please review it: “[PATCH scylla] dist/common/scripts/scylla_dev_mode_setup: include scylla_lib.sh”

**Comment by tzach** [comment]
@syuu1228 Thanks for the prompt response
@amnonh please review the patch
