### ISSUE TITLE
Paging support for secondary index queries

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#2960]
Currently, secondary index queries don't implement paging, which makes secondary indexes difficult to use for low cardinality indexes when there's lots of data.

**Comment by psarna** [comment]
No it's not. I went through some review iterations with @denesb, but before I push a final version I'd first wait for maintainer's (@duarten) review too.

**Comment by duarten** [comment]
Will review today!

**Comment by duarten** [comment]
Initial support for secondary index paging is in. To fully implement the [design document](https://docs.google.com/document/d/1MZa3Y6BiMaqbIj43QAo2q0U7rZJtWJdnDbfHlC_sJDQ) - and to increase performance - some enhancements are need, described in the following issues:

#### Full support for partition_slice specific ranges #3804

This entails changing the partition_slice class to support assigning each partition key one or more clustering ranges. It will then be possible to use a single read_command to query a vnode, even in the case where we’re asking for non-consecutive rows.

#### Use a read_command per vnode #3805

This will allow us to further consolidate the two base query paths (row-by-row and single partition); we’ll create a read_command per vnode from the rows returned by the view query (c.f., #3802), and similarly to storage_proxy::query_partition_key_range_concurrent(), use those read_commands to query base replicas in an incremental fashion.

#### Adaptive concurrency and page size #3807

Calculate an adaptive page size and concurrency, which are stored in the prepared statement and also in the paging state.

#### Support for range queries #3808

Range queries will leverage the work performed in 2), and won’t consider the index selectivity or use filtering queries.

#### Cut off base query opportunistically #3809

If we’re about to timeout, or if we can’t achieve CL for a sub-query, we can return the results we already have to the client.

#### Execute paged range queries as base filtering queries #3810

This entails keeping statistics about index selectivity, and optionally turn index range queries into base table filtering queries.
