### ISSUE TITLE
types_test is flaky

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#2974]
It fails now and then and passes after a retry. Here's a log:

FAILED: build/release/tests/types_test                             
  with error code -6                   
=== stdout START ===
terminate called after throwing an instance of 'marshal_exception'
  what():  marshalling error
Running 48 test cases...
Aborting.
Backtrace:
  0x00000000004a7a0b
  0x00000000004a7adc
  0x00000000004a7b93
  /lib64/libpthread.so.0+0x00000000000123af
  /lib64/libc.so.6+0x000000000003669a
  /lib64/libc.so.6+0x000000000003849f
  /lib64/libstdc++.so.6+0x0000000000092054
  /lib64/libstdc++.so.6+0x000000000008fc45
  /lib64/libstdc++.so.6+0x000000000008fc90
  /lib64/libstdc++.so.6+0x000000000008fed3
  0x0000000000d098de
  0x00000000006c0912
  0x00000000006d2ccb
  0x00000000006d3169
  0x000000000182167a
  0x000000000180251c
  0x00000000018025f5
  0x0000000001802d19
  0x0000000001808392
  0x0000000001831896
  0x0000000001831ac7
  0x0000000001810a11
  0x000000000181a3be
  /lib64/libc.so.6+0x0000000000020509
  0x00000000004a00c9

=== stdout END ===

**Comment by duarten** [comment]
Duplicates #2967
