### ISSUE TITLE
Range tombstones are incorrectly applied in reversed queries

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#2982]
After the following preparatory commands:
```cql
CREATE TABLE cf (pk int, ck int, v int, PRIMARY KEY (pk, ck));
INSERT INTO cf (pk, ck, v) VALUES (0, 0, 0);
INSERT INTO cf (pk, ck, v) VALUES (0, 2, 2);
INSERT INTO cf (pk, ck, v) VALUES (0, 4, 4);
INSERT INTO cf (pk, ck, v) VALUES (0, 5, 5);
INSERT INTO cf (pk, ck, v) VALUES (0, 6, 6);
DELETE FROM cf WHERE pk = 0 AND ck >= 1 AND ck <= 3;
DELETE FROM cf WHERE pk = 0 AND ck > 4 AND ck <= 8;
DELETE FROM cf WHERE pk = 0 AND ck > 0 AND ck <= 1;
```

```cql
SELECT v FROM cf WHERE pk = 0 ORDER BY ck DESC;
```
returns:
```
 v
---
 6
 5
 2

(3 rows)
```
while:
```cql
SELECT v FROM cf WHERE pk = 0;
```
returns:
```
 v
---
 0
 4

(2 rows)
```

Looks like this problem has been present since range tombstones support was added in 1.3.

**Comment by duarten** [comment]
We should add more unit tests for ranged deletions; we don't have many of those.

**Comment by tgrabiec** [comment]
2017-11-16 15:14 GMT+01:00 Duarte Nunes <notifications@github.com>:

> We should add more unit tests for ranged deletions; we don't have many of
> those.
>

I think we have tests for range deletions, see mutation_source_test.cc. We
don't have enough tests for reversed reads though.

**Comment by duarten** [comment]
Ah, missed those!
