### ISSUE TITLE
Are DNS look-ups cached?

### ISSUE THREAD

**Issue by hakuch** [scylladb/scylla#2983]
*Installation details*
Scylla version (or git commit hash): 6950389a3f53893fd0f322a8186895a71b0539d2

## Background

One useful feature of Kubernetes is that we can assign static host names to nodes in the cluster like `scylla-0`, `scylla-1`, etc, and DNS records will be created. This means that even if a Kubernetes Pod is moved to another host or has its IP address changed, the host names will refer to the new locations.

What I'd like to confirm is that DNS look-ups of host names are not cached in Scylla/Seastar, so that a name being reassigned will not be ignored by the system.

## Details

When a host name is given as an argument to `--seeds`, the IP address is resolved using `gms::inet_address::lookup()` -> `seastar::net::inet_address` -> ` seastar::net::dns_resolver::resolve_name()` and ultimately `ares_gethostbyname()` (in `seastar/net/dns.cc`), from the `c-ares` library.

Looking at the code and the documentation of `c-ares`, I don't see any obvious mentions of caching behaviour. Is it a safe assumption that no caching takes place?

/cc @elcallio

**Comment by elcallio** [comment]
No. C-ares does not cache. It is wholly a query mechanism. Caching and caching policy is up to either client or queried server. 
Also, there are other ways to communicate beyond github issues, who, in my opinion, should maybe be reserved for actual issues. Just to reduce noise.

**Comment by avikivity** [comment]
Please don't use the issue tracker for random questions.
