### ISSUE TITLE
Add QA and Benchmarking Tests for Spark over Scylla

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla#2985]
Add a functional and performance testing for Spark.
The tests should include various Cassandra-spark connector versions, starting with version 2.0.3

Functional test should be able to retrieve and post several sizes RDDs from to Scylla. The tests should verify number of connections opened between Scylla and the Spark master/executors
Benchmarking should include: Execution times for selected workloads, elimination of timeouts both on the Scylla and the Spark side and benchmark data retrievals that are larger than Scylla servers memory size (read data from SSTables)

Any additional ideas are more than welcomed.

**Comment by dorlaor** [comment]
@slivne @roydahan Eyal is right, this isn't the right location for it, so please move it to the automation
github first and then, close this issue

**Comment by roydahan** [comment]
Added to QA tickets.
