### ISSUE TITLE
Avoid calling range_tombstones_for_row() when writing promoted index entry

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#2997]
We should ensure that tombstone_accumulator always only contains tombstones which are relevant for the cell being written, which we should do anyway. Then we don't need to slice it, just write all currently present tombstones.

**Comment by duarten** [comment]
Doesn't this amount to calling `drop_unneeded_tombstones()` at some different place?

**Comment by tgrabiec** [comment]
Not relevant to the MC sstable format and above.
