### ISSUE TITLE
Azure: ScyllaDB setup error (optimize NIC queue settings)

### ISSUE THREAD

**Issue by Ritaja** [scylladb/scylla#3001]
*Installation details*
Scylla version : 2.0.1-0.20171115.7b19167
Cluster size: 1 (Single Node evaluation)
OS : Ubuntu 16.04.3 LTS (Xenial Xerus)

*Hardware details * 
Platform (physical/VM/cloud instance type/docker): Azure
Hardware: cores= 8 (lcores) memory=32 vm_type= Standard E4s v3 with one NIC attached
Disks: : 2 SSD(s) 256 Each

After installation, while running `sudo scylla_setup` it fails on Network Throttle step (Do you want to optimize NIC queue settings?) at the script `posix_net_conf.sh` with error:
`ERROR: 'NoneType' object is not iterable. Your system can't be tuned until the issue is fixed.`

**Comment by vladzcloudius** [comment]
The issue was caused by the fact that the `perftune.py` script (invoked by the `posix_net_conf.sh`) didn't handle the case when the underlying networking device didn't have the configurable IRQs like in the Azure's case.

I've sent the patch that fixes this issue on the seastar-dev list.

**Comment by slivne** [comment]
fixed
