### ISSUE TITLE
CentOS7 RPM build fails when build environment doesn't have /usr/share/distribution-gpg-keys/centos

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#3002]
It seems mock requires GPG file which specified at "gpgkey=" on scylla-epel-7-x86_64.cfg on HOST environment, not chrooted CentOS7 image.
Latest Fedora/Ubuntu16/CentOS7 does contains it because recent versions of mock requires the file on package install, but older build environment doesn't have this, ex) CentOS-7.2.

We have docker image for jenkins CentOS rpm task, which is CentOS-7.2, so it fails:
```
DEBUG util.py:417:  Retrieving key from file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-7
DEBUG util.py:417:  GPG key retrieval failed: [Errno 14] curl#37 - "Couldn't open file /usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-7"
DEBUG util.py:542:  Child return code was: 1
DEBUG util.py:176:  kill orphans
```

Because it doesn't have such file on the path.
But, gpgkey= can be http URL, so we should replace it to URL.

**Comment by avikivity** [comment]
Note, we can replace the docker build with a mock build on Fedora.
