### ISSUE TITLE
Scylla won't install on Ubuntu 17.04

### ISSUE THREAD

**Issue by boardmaster357** [scylladb/scylla#3004]
Installing Scylla on Ubuntu 17.04 fails with the following error:

The following packages have unmet dependencies:
 scylla-server : Depends: libboost-date-time1.58.0 but it is not installable
                 Depends: libboost-filesystem1.58.0 but it is not installable
                 Depends: libboost-program-options1.58.0 but it is not installable
                 Depends: libboost-system1.58.0 but it is not installable
                 Depends: libboost-thread1.58.0 but it is not installable
                 Depends: libcrypto++9v5 but it is not installable
                 Depends: libprotobuf9v5 but it is not installable

Scylla requires libboost1.58, but only 1.61, 1.62, and 1.63 are available.

**Comment by glommer** [comment]
@syuu1228 can you please confirm this and advise on how to proceed ?

**Comment by slivne** [comment]
we will support 18.04 (Bionic Beaver) 

we are only supporting LTS releases (officially)

**Comment by horschi** [comment]
The Scylla homepage is not offering any 18.04 downloads yet. Will there be a Ubuntu 18.04 download?

**Comment by tzach** [comment]
Yes, 18.04 packages will be available with the upcoming Scylla 2.3

**Comment by horschi** [comment]
https://github.com/scylladb/scylla/issues/3598
