### ISSUE TITLE
I can't update my kali every time I try to install or updte som thing it says the following packag s have unmet dependencies gnome-shell

### ISSUE THREAD

**Issue by Mrawil** [scylladb/scylla#3008]
*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by duarten** [comment]
Please provide a meaningful description of the issue, including details about your environment and Scylla version. I can't fully parse the title, but are you sure this is the correct project for the issue?

**Comment by slivne** [comment]
closing this - @Mrawil if its relevant please provide additional information
