### ISSUE TITLE
Do not activate write behind if XFS is used.

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#301]
Issue #197 describes a problem we found in XFS. That is pretty widespread and likely to be present in a lot of the kernels in which we will run.

The first fix I thought of for that, was 100 % seastar-ish, but it is becoming clear that some scylla work will be needed. First of all, we need to warn the user about what's going on, and that won't be done in seastar.

But second, and most importantly, the commit log - as @avikivity just told me, do not use file streams, but rather writes directly to the file. That has to be fixed.

@slivne : the result of this is severe and unpredictable data loss. This is a showstopper for anglerfish.

**Comment by slivne** [comment]
@avikivity

For GA should we have a flag that enables writebehind - that the user needs to set manually via config - the default would be disabled ?

**Comment by slivne** [comment]
Related to #658

**Comment by slivne** [comment]
@avikivity doesn't fsqual cover this - can we close this

**Comment by avikivity** [comment]
We disabled write-behind for performance reasons in any case, so this issue is obsolete.

**Comment by nyh** [comment]
On Thu, Feb 18, 2016 at 10:53 AM, Avi Kivity <notifications@github.com>
wrote:

> We disabled write-behind for performance reasons in any case, so this
> issue is obsolete.
>
In this case, should we remove the write-behind code path from Seastar?

**Comment by avikivity** [comment]
No, we will reactivate it one day.

**Comment by nyh** [comment]
But you just said we disabled it not because of some XFS bugs, but because it simply doesn't perform any better... If that was really the case, we will *never* want to reactivate it?

**Comment by avikivity** [comment]
Write-behind performs badly because of an XFS bug/misfeature.  In general it is a good idea.
