### ISSUE TITLE
transitional_auth: auth validate problem during rolling enable Authentication

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3011]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20171121.c1b97d1
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS
$ cqlsh --version
cqlsh 5.0.1

Problem Description:
- in my new transitional_auth test, session of node1 doesn't work when only Authentication of node1 is enabled, but session of node0 (its Authentication isn't enabled) exceptional works.

- The result of `cqlsh cmdline` is strangely `right as expected`, only session of node1 works when only Authentication of node1 is enabled.

My transitional_auth test (with workaround & debug):
https://github.com/amoskong/scylla-dtest/commits/transitional_auth_dev

Test scenario:
- start cluster (two nodes) without Authentication
- check node1 will get Unauthorized error (both with / without account parameters)
- enable Authentication of node1 by restart
- check and expect session of `node1 with account parameters` `will` have permission (real result: Unauthorized error)
- check and expect session of `node0 with account parameters` `won't` have permission (real result: have permission)
- enable Authentication of node0 by restart
- check session of node0 & node1, expect they all work

More:
- I also try to sleep some seconds to wait the auth cache is updated, but the problem still exist.
- I tried to adjust the permissions_validity，the problem still exist

Test log (I changed the code to workaround two auth issues):
```
going to run tests sequentially
cluster ccm directory: /home/amos/.dtest/dtest-INYZtW
127.0.0.1
127.0.0.2
STEP: check session before enable Authenticator
get_session .... 127.0.0.1
_create_session: 127.0.0.1
4
get_session .... 127.0.0.1
_create_session: 127.0.0.1
4
Error from server: code=2100 [Unauthorized] message="You have to be logged in and not anonymous to perform this request"
Good: session isn't available (unauthorized error) as expected
Error from server: code=2100 [Unauthorized] message="You have to be logged in and not anonymous to perform this request"
Good: session isn't available (unauthorized error) as expected
STEP: restart node1 to enable Authenticator
STEP: check session after set node1
get_session .... 127.0.0.2
_create_session: 127.0.0.2
4
can't get session of node1 without user/password
get_session .... 127.0.0.2
_create_session: 127.0.0.2
4
Error from server: code=2100 [Unauthorized] message="You have to be logged in and not anonymous to perform this request"
Good: session isn't available (unauthorized error) as expected
^^^ WORKAROUND ISSUE: expect session of node1 is available
get_session .... 127.0.0.1
_create_session: 127.0.0.1
4
Error from server: code=2100 [Unauthorized] message="You have to be logged in and not anonymous to perform this request"
Good: session isn't available (unauthorized error) as expected
get_session .... 127.0.0.1
_create_session: 127.0.0.1
4
Debug users list: [Row(name=u'cassandra', super=True)]
Good: session is available as expected
^^^ WORKAROUND ISSUE: expect session of node0 isn't available
STEP: restart node0 to enable Authenticator
STEP: check session after set node0
get_session .... 127.0.0.1
_create_session: 127.0.0.1
4
can't get session of node0 without user/password
get_session .... 127.0.0.1
_create_session: 127.0.0.1
4
Debug users list: [Row(name=u'cassandra', super=True)]
Good: session is available as expected
get_session .... 127.0.0.2
_create_session: 127.0.0.2
4
Debug users list: [Row(name=u'cassandra', super=True)]
Good: session is available as expected
.
----------------------------------------------------------------------
Ran 1 test in 65.719s

OK
```

CC: @elcallio @hakuch

**Comment by hakuch** [comment]
I'm not sure what the function of `transitional_auth` is, especially given the move to roles. @elcallio, would you please clarify its purpose?

**Comment by elcallio** [comment]
The comment and associated issue pretty much describes it: It is an 
authenticator that requires login, but does not care about the content 
of the login -> you can have authentication on, without fully 
populating/propagating the user table. For rolling upgrade to 
authenticated operations.

And roles do not in any supercede authentication/user identities. It is 
a mechanism for grouping permission levels.

**Comment by amoskong** [comment]
@elcallio @hakuch 

Question:
Why it got different result than cqlsh?
It will get reverse result if we use 3 nodes(same as cqlsh)?

**Comment by elcallio** [comment]
If I read your test correctly, you are not using the transitional authenticator. You are using normal password auth + default authorizer. Also, using the "cassandra" login will not do what you think. That is the default suprt user, and that special account (any super user account) is treated as normal authntication by trans-auth. To test it you should use a (non-existing) "normal" login.

**Comment by amoskong** [comment]
Thanks for your reply. I have better understand of this feature.
It can be enabled by `com.scylladb.auth.TransitionalAuthenticator` and
`com.scylladb.auth.TransitionalAuthorizer`.
I will update the test.

**Comment by amoskong** [comment]
Can we update https://github.com/scylladb/scylla/wiki/Access-control-in-Scylla to add transitional_auth?

@hakuch

**Comment by amoskong** [comment]
Test Scenario: start cluster with default authenticator/authorizer, try to enable transitional authenticator/authorizer one by one, the enable strict PasswordAuthenticator/CassandraAuthorizer.

Test result:
![image](https://user-images.githubusercontent.com/309708/33298901-fb3db8e6-d423-11e7-85d8-d1c9d7f114ca.png)

  |   | get_session | get_session with pwd | list users
-- | -- | -- | -- | --
  |   |   |   |  
start with default auth | node0 | Good | Good | Unauthorized
node1 | Good | Good | Unauthorized
enable Transitional auth on node0 | node0 | AuthenticationFailed | Good | Unauthorized
node1 | Good | Good | Unauthorized
enable Transitional auth on node1 | node0 | AuthenticationFailed | Good | Good
node1 | AuthenticationFailed | Good | Good
enable pwdauth/cassandraauth on node0 | node0 | AuthenticationFailed | Good | Good
node1 | AuthenticationFailed | Good | Good
enable pwdauth/cassandraauth on node1 | node0 | AuthenticationFailed | Good | Good
node1 | AuthenticationFailed | Good | Good

**Comment by amoskong** [comment]
I rewrite the testcase, and split it to 4 (or more) small test.

And reported two new issues:
- https://github.com/scylladb/scylla/issues/3024
- https://github.com/scylladb/scylla/issues/3025

**Comment by slivne** [comment]
@amoskong - is this still relevant ?

**Comment by amoskong** [comment]
@slivne Let's close this issue, the 'problem' was found by immature, and I didn't see it in latest test.
