### ISSUE TITLE
Move write() methods from class sstable to class sstable_writer

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3012]
*Installation details*
Scylla version (or git commit hash): master

Despite us having a `class sstable_writer`, the methods that actually carry out writing are defined in `class sstable`, alongside some writer-specific code. We should clean this up by moving the `write()` methods to `sstable_writer` and the related state.

**Comment by raphaelsc** [comment]
that's an important step towards a well defined interface for storage engine. important to mention that we have some auxiliary data being left over in the sstable class which is used only during write, so wasting some memory (maybe irrelevant) for each new table.

**Comment by avikivity** [comment]
Not a bug, not backporting.
