### ISSUE TITLE
Support non-optional fields in sstable_writer_config

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3014]
*Installation details*
Scylla version (or git commit hash): master

`sstable_writer_config` should support required configuration fields, which do not have a default value. For example, specifying whether an sstable should correctly serialize non-compound range tombstones depends on a cluster feature, which we check, by accessing the global `storage_service`, in the sstable layer. Things like this should be specified by the upper layers, but to protect against bugs, callers mustn't be able to rely on a default value.

**Comment by bhalevy** [comment]
@xemul please own this wrt your efforts to de-globalize storage_service

**Comment by xemul** [comment]
Btw, I think that it was addressed by 90678463. The sstable_writer_config is now free from default values and is always explicitly initialized by creator. @bhalevy

**Comment by bhalevy** [comment]
Thanks, we can close the issue then.
No backport needed.
