### ISSUE TITLE
normal user isn't treated as anonymous after enabled transitional auth

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3024]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20171121.c1b97d1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

Test steps:
1. start a node with default AllowAllAuthenticator/AllowAllAuthorizer
2. update scylla.yaml to use `com.scylladb.auth.TransitionalAuthenticator`, `com.scylladb.auth.TransitionalAuthorizer`
3. restart the node to enable Transitional Auth
4. get session by default super (cassandra) and create a normal user (nosuper)
5. try to execute `LIST USERS;` with normal user session

Expected result:
1. get Unauthorized error in step 5 (err: You have to be logged in and not anonymous to perform this request)

Actually result:
1. normal session can list all users, and it's not treated as anonymous.

**Comment by amoskong** [comment]
```
    def transitional_auth_normal_test(self):
        """
        Start one node cluster with default Auth, enable Transitional Auth,
        create a normal user, and verify it's treated as anonymous.
        """
        debug('STEP: start one node cluster with default Auth')
        self.prepare(nodes=1, enable_auth=False)
        node = self.cluster.nodelist()[0]

        debug('STEP: update conf to use TransitionalAuthenticator/TransitionalAuthorizer')
        config = {'authenticator': 'com.scylladb.auth.TransitionalAuthenticator',
                   'authorizer': 'com.scylladb.auth.TransitionalAuthorizer'}
        self.cluster.set_configuration_options(values=config)

        debug('STEP: restart node0 to enable Transitional Auth')
        node.stop(wait_other_notice=True, gently=False)
        node.start(wait_for_binary_proto=True)

        session = self.get_session(user='cassandra', password='cassandra')
        debug('STEP: create normal user (normal) by super cassandra')
        session.execute("CREATE USER normal WITH PASSWORD '123456' NOSUPERUSER")

        debug('STEP: verify normal user is treated as anonymous')
        session = self.get_session(user='normal', password='123456')
        self.assertUnauthorized("You have to be logged in and not anonymous to perform this request", session,
                                "LIST USERS")
```

Results:
```
cluster ccm directory: /home/amos/.dtest/dtest-aoXEQU
STEP: start one node cluster with default Auth
STEP: update conf to use TransitionalAuthenticator/TransitionalAuthorizer
STEP: restart node0 to enable Transitional Auth
STEP: create normal user (normal) by super cassandra
STEP: verify normal user is treated as anonymous
F
======================================================================
FAIL: transitional_auth_normal_test (auth_test.TestAuth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/amos/space/scylla-dtest/auth_test.py", line 1695, in transitional_auth_normal_test
    "LIST USERS")
  File "/home/amos/space/scylla-dtest/auth_test.py", line 1727, in assertUnauthorized
    session.execute(query)
AssertionError: Unauthorized not raised

----------------------------------------------------------------------
Ran 1 test in 22.177s
```

@elcallio

**Comment by slivne** [comment]
@elcallio can you please provide your feedback on this

**Comment by slivne** [comment]
@amoskong - can you provide full details to reproduce (repo , test file, test name) - even better command line

**Comment by elcallio** [comment]
Transitional auth gives the same permission set as the DSE counterpart. List stuff is in that. Btw, a non-super user is not equal to an anonymous user, it is an anonymous user with the permissions equal to a "normal" user.

**Comment by amoskong** [comment]
I have two Questions, @elcallio can you help to answer them?

1. If a non-super user was treated as anonymous, what's the effect / change for it?
2. how do I verify the non-super user was treated as anonymous?

**Comment by amoskong** [comment]
Test Details:

The tests can be found in https://github.com/scylladb/scylla-dtest/pull/545
The test name: transitional_auth_from_default_test

PRINT_DEBUG=true KEEP_TEST_DIR=true REUSE_CLUSTER=false nosetests --logging-filter=none -s auth_test.py:TestAuth.transitional_auth_from_default_test

Full dtest log:  [dtest-eWUcbe.tar.gz](https://github.com/scylladb/scylla/files/1577821/dtest-eWUcbe.tar.gz)


```
cluster ccm directory: /home/amos/.dtest/dtest-eWUcbe
STEP: start one node cluster with default Auth
STEP: update conf to use TransitionalAuthenticator/TransitionalAuthorizer
STEP: restart node0 to enable Transitional Auth
STEP: create normal user (normal) by super cassandra
STEP: verify normal user is treated as anonymous
F
======================================================================
FAIL: transitional_auth_from_default_test (auth_test.TestAuth)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/amos/space/scylla-dtest/auth_test.py", line 1696, in transitional_auth_from_default_test
    "LIST USERS")
  File "/home/amos/space/scylla-dtest/auth_test.py", line 1836, in assertUnauthorized
    session.execute(query)
AssertionError: Unauthorized not raised  

----------------------------------------------------------------------
Ran 1 test in 29.017s

FAILED (failures=1)
```

**Comment by amoskong** [comment]
Posted a fix to scylladb-dev maillist:
- [PATCH 1/2] auth/transitinal: add log of treating user as anonymous
- [PATCH 2/2] auth/transitional: call self implemented authenticate()

**Comment by amoskong** [comment]
Exact case:
- Scylla: set TransitionalAuthenticator
- DSE: set transitional_mode to permissive OR normal mode

Tests:
- cqlsh

Expected result: If the authentication fails, the user is logged in as anonymous.

Results:
- Scylla: AuthenticationFailed
- DSE: can login as anonymous

Conclusion: Scylla transitional authenticator doesn't process auth failed user as anonymous.

**Comment by hakuch** [comment]
I've reviewed the patch series that address this bug. I think the proposed solution goes in the wrong direction, and I've submitted for your consideration my own idea for a fix.

**Comment by amoskong** [comment]
I _wrongly_ understood description in https://github.com/scylladb/scylla/issues/2836#issue-260275062 as that we want to implement 'normal' transitional_mode in DSE, but process all non-super as anonymous. 

Now I guess `but only actually using said auth for super user access` is talking about transitional_authorizer, the `said auth` should be all permissions, what we want to implement is completely same as normal transitional_mode in DSE.

DSE transitional_mode: normal
- Only users that provide valid credentials are logged in.
- If the authentication is successful, the user is logged in.
- If the authentication fails, the user is logged in as anonymous.
- If no credentials are passed, the user is logged in as anonymous.

So the problem in first comment is NOTABUG, let's close this issue.
