### ISSUE TITLE
transitional auth might extended permission of nosuper user

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3026]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20171121.c1b97d1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

Test steps:
1. Started a cluster (one node) with PasswordAuthenticator/CassandraAuthorizer
2. connect cqlsh by super cassandra
3. create a nonsuper user by `CREATE USER bob WITH PASSWORD '12345';`
4. connect cqlsh by bob user, and try to create a keyspace
` CREATE KEYSPACE ks WITH replication = {'class':'SimpleStrategy', 'replication_factor':1};`
5. switch to transitional Auth, reboot
6. connect cqlsh by bob user, try to create another ks` CREATE KEYSPACE ks2 WITH replication = {'class':'SimpleStrategy', 'replication_factor':1};`

Results:
failed to create ks in step 4, success to create k2 in step 6.

Expected result:
The permission of nosuper users should not change when we switch transition Auth, it's `unsafe`.

It seems we give the nosuper user fixed permission in auth/transitional.cc:
```
    future<permission_set> authorize(service& ser, ::shared_ptr<authenticated_user> user, data_resource resource) const override {
        return is_super_user(ser, *user).then([](bool s) {
            static const permission_set transitional_permissions =
                            permission_set::of<permission::CREATE,
                                            permission::ALTER, permission::DROP,
                                            permission::SELECT, permission::MODIFY>();
            return make_ready_future<permission_set>(s ? permissions::ALL : transitional_permissions);
        });
    }
```

@elcallio

**Comment by slivne** [comment]
@elcallio can you please provide your feedback on this

**Comment by slivne** [comment]
@amoskong - can you provide full details to reproduce (repo , test file, test name) - even better command line

**Comment by elcallio** [comment]
Transitional auth gives a fixed set of permissions to non-super users. This is by design. Transitional auth is not intended as a replacement for actual auth. It is a placeholder auth during auth rollout. Moving from actual DefaultAuthorizer to transitional auth is the _wrong_ direction.

**Comment by amoskong** [comment]
Let's close this issue, it's a design.

**Comment by slivne** [comment]
@elcallio - can you please comment on this

**Comment by elcallio** [comment]
Again, our transactional auth is based on DSE 4.x. (I hope I am not messing up the numbers here). "Additional modes" is a feature of the 5.x series, where everything was moved into the tangled web of the "unified auth" class. Not sure why we'd care to implement the 5.x model. 

The docs should simply point out that transactional auth _is not actually auth_. And in no way safe. It is placeholder auth. The same objection as above can be made of switching from password+normal auth to no auth. It also allows all to have super user rights. And afaik, we don't raise any errors if a user simply turns off his auth settings. How could we? We have no config history...
 
Again, just ensure the docs explain that trans-auth is _not_ an actual authentication system. It enforces very little.
