### ISSUE TITLE
scylla shutdown fails: Exceptional future ignored: exceptions::read_timeout_exception (Operation timed out for system_auth.roles - received only 0 responses from 1 CL=ONE.)

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#3028]
*Installation details*
Scylla version (or git commit hash): 4cfcd8055ebe1b221e980bbd103d505ebb5654ac
Cluster size: 3

*Description*
When stopping 3 nodes `ccm` cluster we get the following error:

```
INFO  2017-11-28 23:09:41,983 [shard 0] storage_service - CQL server stopped
INFO  2017-11-28 23:09:41,983 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2017-11-28 23:09:41,983 [shard 0] storage_service - messaging_service stopped
INFO  2017-11-28 23:09:41,983 [shard 0] storage_service - Stop transport: shutdown messaging_service done
INFO  2017-11-28 23:09:41,983 [shard 0] storage_service - stream_manager stopped
INFO  2017-11-28 23:09:41,983 [shard 0] storage_service - Stop transport: shutdown stream_manager done
WARN  2017-11-28 23:09:46,990 [shard 0] seastar - Exceptional future ignored: exceptions::read_timeout_exception (Operation timed out for system_auth.roles - received only 0 responses from 1 CL=ONE.), backtrace:   0x49d3e4
  0x50aace
  0x49ff84
  0x49c1c4
  0x49c49c
  0x4eb044
  0x57d8e4
  0x42582f
  /lib/x86_64-linux-gnu/libc.so.6+0x2082f
  0x497da8
```

**Comment by hakuch** [comment]
Interesting. I haven't observed this with single-node clusters. I'll have to investigate. Do you have any hints or guesses as to the conditions that would throw this kind of error?

**Comment by gleb-cloudius** [comment]
On Wed, Nov 29, 2017 at 02:33:58PM +0000, Jesse Haber-Kucharsky wrote:
> Interesting. I haven't observed this with single-node clusters. I'll have to investigate. Do you have any hints or guesses as to the conditions that would throw this kind of error?
> 
The future is destroyed while it holds exceptional value. It may happen
with the code like this:

futurize_apply([] {throw "boom"; }).then(...)

Look for end-of-the-fiber continuation which is not then_wrapped() or
handle_exception().

--
			Gleb.

**Comment by hakuch** [comment]
Thanks, @gleb-cloudius.

@vladzcloudius, could you describe the exact steps to reproduce?

**Comment by vladzcloudius** [comment]
@hakuch Sure. Here you go:
1) Create the 3 nodes cluster with `ccm`: `ccm create scylla-3 --scylla --vnodes -n 3 --install-dir=<scylla dir>`
2) Start it. I used the following command: `ccm start --jvm_arg="--memory" --jvm_arg="1G" --jvm_arg="--collectd-address" --jvm_arg="127.0.0.1:25826" --jvm_arg="--collectd" --jvm_arg="1" --jvm_arg="--default-log-level" --jvm_arg="info" --jvm_arg="--smp" --jvm_arg="2"`
3) Stop it: `ccm stop`.

FYI. There is a similar issue during the start attempt of the cluster that has already been started before:
```
INFO  2017-11-28 23:08:37,373 [shard 0] compaction - Compacting [/home/vladz/.ccm/scylla-3/node1/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-14-Data.db:level=0, /home/vladz/.ccm/scylla-3/node1/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-16-Data.db:level=0, /home/vladz/.cc
m/scylla-3/node1/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-10-Data.db:level=0, /home/vladz/.ccm/scylla-3/node1/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-12-Data.db:level=0, ]
INFO  2017-11-28 23:08:37,476 [shard 0] compaction - Compacted 4 sstables to [/home/vladz/.ccm/scylla-3/node1/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-18-Data.db:level=0, ]. 33619 bytes to 12596 (~37% of original) in 103ms = 0.12MB/s. ~1024 total partitions merged to 1.
INFO  2017-11-28 23:08:37,554 [shard 0] storage_service - NORMAL: node is now in normal status
ERROR 2017-11-28 23:08:37,557 [shard 0] seastar - Exiting on unhandled exception: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
INFO  2017-11-28 23:08:37,557 [shard 0] compaction_manager - Asked to stop
INFO  2017-11-28 23:08:37,557 [shard 1] compaction_manager - Asked to stop
```

**Comment by hakuch** [comment]
A patch on the [mailing list](https://groups.google.com/d/msg/scylladb-dev/Z23WtcgHyek/r8d3qKbgBgAJ) fixes the issue that @vladzcloudius observed.

Please let me know if that solves the issue.

**Comment by hakuch** [comment]
Note that [this patch](https://groups.google.com/d/msg/scylladb-dev/DWceQq_CNas/wOR6VfTXBgAJ) also corrects a typo (and is separate bug), but I don't believe that particular bug is the cause of this issue.

(/cc @duarten).
