### ISSUE TITLE
ami: dist/ami/files/scylla-setup.sh

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#303]
cat dist/ami/files/scylla-setup.sh
```
#!/bin/sh -e

if [ -f /dev/md0 ]; then
    echo "RAID already constructed."
    exit 1
fi
mdadm --create --verbose /dev/md0 --level=0 -c256 --raid-devices=2 /dev/xvdb /dev/xvdc
blockdev --setra 65536 /dev/md0
mkfs.xfs /dev/md0 -f
echo "DEVICE /dev/xvdb /dev/xvdc" > /etc/mdadm.conf
mdadm --detail --scan >> /etc/mdadm.conf
mkdir /data
echo "/dev/md0 /data xfs noatime 0 0" >> /etc/fstab
mount /data
mkdir -p /data/data
mkdir -p /data/commitlog
chown scylla:scylla /data/*
/usr/lib/scylla/setup_yaml.py
systemctl disable scylla-setup.service
systemctl enable scylla-server.service
systemctl start scylla-server.service
```

Right now, we hard code the number of extra disks to use for scylla data. We'
d better use all available disks.

For user to try it out, we do not have to ask user to specify two more ebs disks. 

How about

1) make out ami's rootfs use xfs
2) if there is only one disk (the root disk) we skip creating the RAID, just make the /data/data direcotry
3) if there are more than one disks, use all of them except the rootdisk as RAID 0.

**Comment by slivne** [comment]
@asias please close this you fix it
