### ISSUE TITLE
ALTER KEYSPACE durable_writes = false not effective

### ISSUE THREAD

**Issue by QLeelulu** [scylladb/scylla#3034]
*Installation details*
Scylla version (or git commit hash): 2.0.1-0.20171115.7b19167
Cluster size: 1 
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.2

Create KEYSPACE with durable_writes = false will not write commitlog. It's OK.
But if create  KEYSPACE with durable_writes = **true**, and then ALTER KEYSPACE with durable_writes = **false**, it will still write commitlog.

```
cqlsh> CREATE KEYSPACE test4 WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 1} 
 AND durable_writes = true;
cqlsh> ALTER KEYSPACE test4 WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : 1}  
 AND durable_writes = false;
```

**Comment by ruimateus** [comment]
was this bug solved? we are hitting the same behaviour.

**Comment by avikivity** [comment]
This is a very rare operation, and a workaround exists (rolling restart), so not backporting.
