### ISSUE TITLE
incremental backup : no `backup` directory

### ISSUE THREAD

**Issue by aguilbau** [scylladb/scylla#3037]
### installation details
Scylla version : `2.0.1-0.20171115.7b19167`
Cluster size :  `3`
OS : `Ubuntu 16.04`

### description
With incremental backups enabled, I don't see a `backup` directory created in the table directory.

### steps
 - enable incremental backups in scylla.conf `incremental_backups: true`
 - enable incremental backups with nodetool `$> nodetool enablebackup`
 - take a snapshot `$> nodetool snapshot <keyspace>`
 - take another snapshot `$> nodetool snapshot`

No backup directory is created. However, looking at the snapshots, you find : 
```
du -sh snapshots/*
444K	snapshots/1512149296429
8.0K	snapshots/1512149299586
```

So there seem to be incremental backups, however I'm not sure how to restore from them.

**Comment by nirmaayan** [comment]
Scylla version: 2.0.1-0.20171115.7b19167
backups folder was created

Steps

1. Enable incremental backups in scylla.yaml file incremental_backups: true
2. cqlsh - create keyspace
`CREATE KEYSPACE nba WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : '3'};
`
3. create table
```
CREATE TABLE nba.team_roster (
player_name text,
player_jersy_number int,
player_position text,
team text,
PRIMARY KEY (player_name));
```
4. nodetool snapshot
5. Write data 
```
INSERT INTO nba.team_roster (player_name, player_jersy_number, player_position, team ) VALUES ('Russell Westbrook', 0, 'Guard','Oklahoma City Thunder');
INSERT INTO nba.team_roster (player_name, player_jersy_number, player_position, team ) VALUES ('Andre Roberson', 21, 'Forward','Oklahoma City Thunder');
INSERT INTO nba.team_roster (player_name, player_jersy_number, player_position, team ) VALUES ('Steven Adams', 12, 'Center','Oklahoma City Thunder');
INSERT INTO nba.team_roster (player_name, player_jersy_number, player_position, team ) VALUES ('Victor Oladipo ', 5, 'Forward','Oklahoma City Thunder');
INSERT INTO nba.team_roster (player_name, player_jersy_number, player_position, team ) VALUES ('Jermi Grant ', 9, 'Forward','Oklahoma City Thunder');
```
6. nodetool flush
7. Result: 

```
ls /var/lib/scylla/data/nba1/team_roster-c3866f50d82011e7ad39000000000000/backups

nba1-team_roster-ka-1-CompressionInfo.db  nba1-team_roster-ka-2-CompressionInfo.db
nba1-team_roster-ka-1-Data.db             nba1-team_roster-ka-2-Data.db
nba1-team_roster-ka-1-Digest.sha1         nba1-team_roster-ka-2-Digest.sha1
nba1-team_roster-ka-1-Filter.db           nba1-team_roster-ka-2-Filter.db
nba1-team_roster-ka-1-Index.db            nba1-team_roster-ka-2-Index.db
nba1-team_roster-ka-1-Scylla.db           nba1-team_roster-ka-2-Scylla.db
nba1-team_roster-ka-1-Statistics.db       nba1-team_roster-ka-2-Statistics.db
nba1-team_roster-ka-1-Summary.db          nba1-team_roster-ka-2-Summary.db
nba1-team_roster-ka-1-TOC.txt             nba1-team_roster-ka-2-TOC.txt
```

**Comment by nirmaayan** [comment]
@aguilbau did you create some data and run nodetool flush?

**Comment by aguilbau** [comment]
Hello, no I didn't run nodetool flush.
I think the information is missing on this page however : http://docs.scylladb.com/procedures/backup/#incremental-backup

**Comment by tzach** [comment]
To clarify, Scylla automaticity flashes memtable to sstable, and flash more frequently the more data you write. You only need to use `nodetool flush` if you write very little data, and do not want to wait for the automatic flush.

**Comment by aguilbau** [comment]
ooh ok ! thanks for clarification, my bad then.

**Comment by slivne** [comment]
@aguilbau - closing this - if you have additional questions / comments please post them and we can reopen.
