### ISSUE TITLE
Compilation fails - Missing optional package libsystemd

### ISSUE THREAD

**Issue by drasko** [scylladb/scylla#3044]
*Installation details*
Scylla version (or git commit hash): `f3d56741089c83893be546a68b881418acfe3ffe`
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian Buster

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): PC

```
drasko@Marx:~/scylla$ ./configure.py --mode=release
Missing optional package libsystemd (or alteratives libsystemd-daemon)
666.development-0.20171203.f3d567410
python3: can't open file './configure.py': [Errno 2] No such file or directory
Seastar configuration failed
```

**Comment by duarten** [comment]
That's just a message saying you're missing that package, but since it's optional, it shouldn't prevent the build from succeeding. Indeed, it seems that what's missing is the seastar directory.

Did you follow the build instructions in README.md? In particular, did you do `git submodule update --init --recursive`?

**Comment by drasko** [comment]
Now seeing:
```
build/release/gen/cql3/CqlParser.hpp:56:10: fatal error: antlr3.hpp: No such file or directory
 #include <antlr3.hpp>
          ^~~~~~~~~~~~
compilation terminated.
```
Similar to https://github.com/scylladb/scylla/issues/664

**Comment by raphaelsc** [comment]
On Mon, Dec 4, 2017 at 7:38 PM, Drasko DRASKOVIC <notifications@github.com>
wrote:

> Now seeing:
>
> build/release/gen/cql3/CqlParser.hpp:56:10: fatal error: antlr3.hpp: No such file or directory
>  #include <antlr3.hpp>
>           ^~~~~~~~~~~~
> compilation terminated.
>
>
that's probably antlr3-C++-devel missing

have you tried install-dependencies.sh (located in scylla dir)?

**Comment by raphaelsc** [comment]
On Mon, Dec 4, 2017 at 8:12 PM, Raphael S. Carvalho <raphaelsc@scylladb.com>
wrote:

>
>
> On Mon, Dec 4, 2017 at 7:38 PM, Drasko DRASKOVIC <notifications@github.com
> > wrote:
>
>> Now seeing:
>>
>> build/release/gen/cql3/CqlParser.hpp:56:10: fatal error: antlr3.hpp: No such file or directory
>>  #include <antlr3.hpp>
>>           ^~~~~~~~~~~~
>> compilation terminated.
>>
>>
> that's probably antlr3-C++-devel missing
>
> have you tried install-dependencies.sh (located in scylla dir)?
>

Hmm just saw you use Debian. Reading install-dependencies.sh, i noticed the
following:
    apt -y install libyaml-cpp-dev libjsoncpp-dev libsnappy-dev
    echo antlr3 and thrift still missing - waiting for ppa

So you probably will need to install those two packages manually.

**Comment by drasko** [comment]
Had to install manually: https://github.com/apache/thrift

Now I have one error left:
```
drasko@Marx:~/scylla$ ninja -j8
[40/478] NINJA seastar/build/release/libseastar.a seastar/build/release/apps/iotune/iotune seastar/build/release/gen/http/request_parser.hh seastar/build/release/gen/http/http_response_parser.hh
ninja: Entering directory `seastar'
ninja: no work to do.
[72/478] CXX build/release/cql3/cql3_type.o
FAILED: build/release/cql3/cql3_type.o 
g++ -MD -MT build/release/cql3/cql3_type.o -MF build/release/cql3/cql3_type.o.d -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden -Wno-attributes -pthread -I/home/drasko/scylla/seastar -U_FORTIFY_SOURCE  -march=nehalem -I/home/drasko/scylla/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -Wno-sign-compare -Wno-error=cpp -DFMT_HEADER_ONLY -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -DHAVE_ASAN_FIBER_SUPPORT -O2 -I/home/drasko/scylla/seastar/build/release/gen -I/home/drasko/scylla/seastar/build/release/c-ares -I/usr/include/jsoncpp -DBOOST_TEST_DYN_LINK -Wno-maybe-uninitialized -Wno-tautological-compare -Wno-missing-braces -Wno-misleading-indentation -Wno-overflow -Wno-noexcept-type -Wno-nonnull-compare -Wno-error=deprecated-declarations  -I. -I build/release/gen -I seastar -I seastar/build/release/gen  -c -o build/release/cql3/cql3_type.o cql3/cql3_type.cc
In file included from ./cql3/util.hh:34:0,
                 from cql3/cql3_type.cc:27:
build/release/gen/cql3/CqlParser.hpp:56:10: fatal error: antlr3.hpp: No such file or directory
 #include <antlr3.hpp>
          ^~~~~~~~~~~~
compilation terminated.
[79/478] CXX build/release/cql3/statements/create_keyspace_statement.o
ninja: build stopped: subcommand failed.
```

**Comment by duarten** [comment]
You need to install `antlr3`.

**Comment by drasko** [comment]
@duarten it has been installed:

```
drasko@Marx:~/scylla$ sudo apt-get install antlr3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
antlr3 is already the newest version (3.5.2-8).
0 upgraded, 0 newly installed, 0 to remove and 209 not upgraded.
```
BTW. I had to install it by hand, it was not installed by dependencies script.

**Comment by duarten** [comment]
Yeah, like @raphaelsc pointed out, we'll provide a ppa for those dependencies, both thrift and antlr, but now it's still manual. 

Although I see references to `http://ppa.launchpad.net/scylladb/ppa/ubuntu`. and to `scylla-antlr35-c++-dev`, so maybe we already provide it? /cc @avikivity @syuu1228

**Comment by drasko** [comment]
@duarten I am using Debian, not Ubuntu.

**Comment by duarten** [comment]
Oh! Never mind then, we need a debian ppa.

**Comment by drasko** [comment]
Let me try manual installation of `antlr3`.

**Comment by slivne** [comment]
@drasko please follow the instructions in the Readme QuickStart

https://github.com/scylladb/scylla#quick-start

install-dependenices.sh will install the needed 3rdparties.

**Comment by avikivity** [comment]
@duarten the debian 3rd parties are hosted on opensuse build service (a 4th party)

**Comment by slivne** [comment]
@drasko - closing this - if you still have problems - or the info is not complete on the quiclstart - please post and we will fix (for the next person :) ).

**Comment by makorne** [comment]
> or the info is not complete on the quiclstart - please post

The same problem with debian buster and antlr3.

`sudo ./install-dependencies.sh`

```
Reading state information... Done
E: Unable to locate package scylla-libthrift010-dev
E: Unable to locate package scylla-antlr35-c++-dev
E: Couldn't find any package by regex 'scylla-antlr35-c++-dev'
Reading package lists... Done
Building dependency tree       
Reading state information... Done
antlr3 is already the newest version (3.5.2-9).
```

`ninja ./build/release/scylla`

```
In file included from build/release/gen/alternator/expressionsLexer.cpp:57:
build/release/gen/alternator/expressionsLexer.hpp:55:10: fatal error: antlr3.hpp: No such file or directory
 #include <antlr3.hpp>
          ^~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```

**Comment by dami0** [comment]
@makorne 
You can use the Scylladb PPA for Ubuntu (Bionic) to install scylla-env and scylla-antlr35-c++-dev on Debian Buster after having installed dependencies with the provided script. Antlr3 itself should come from the Debian repo. Then using the commands:
`CPLUS_INCLUDE_PATH=/opt/scylladb/include/`
`export CPLUS_INCLUDE_PATH`
you can inform your system where to look for the header files and compile as normal. As of yet I haven't finished compiling but it fixes your issue.

**Comment by roychowdhuryrohit-dev** [comment]
@drasko I am facing the similar error on Raspberry Pi 4 running on Ubuntu 20.04.

`sudo ./install-dependencies.sh`

```
Reading state information... Done
E: Unable to locate package scylla-libthrift010-dev
E: Unable to locate package scylla-antlr35-c++-dev
E: Couldn't find any package by regex 'scylla-antlr35-c++-dev'
Reading package lists... Done
Building dependency tree       
Reading state information... Done
```

I have to build the project from source since arm64 architecture is not supported using `/etc/apt/sources.list.d/scylla.list`.
Any solutions?
