### ISSUE TITLE
nodetool has not enough memory to run

### ISSUE THREAD

**Issue by julienlau** [scylladb/scylla#3045]
*Installation details*
Scylla version (or git commit hash): 1.7.4
Cluster size: 2 datacenters located at same region/location.
One datacenter with 3 nodes and replication 3. VM used are F8S : 8 cores 16Gb RAM with 4x1Tb SSD in RAID0.
One datacenter with 1 node and replication 1. VM used are F16S : 16 cores 32Gb RAM with 4x1Tb SSD in RAID0.
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos 7.3

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): azure
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

NB: I do not perform automatic restart of my nodes.
After something like a week running OK, nodetool refuse to start on my scyllaDB node.
The problem is that no free memory is available to start a java process on the system.
Even a simple command "java -version" fails even if I try to use -Xmx 128m.
In order to solve this I was forced to edit the scylla -server launch command and specify manually with the option "--memory XXg" to keep 3Gb spare for system and others process.
This very annoying since launching repair operation needs some memory.

Note: I use java oracle 1.8.0_144.

Thanks and regards,
Julien

**Comment by tzach** [comment]
@avikivity should we reduce the memory Scylla take further?

**Comment by julienlau** [comment]
Additionnal note: the prometheus metrics exporter is activated, but the VM only host scyllaDB (no spark or anything else).

**Comment by slivne** [comment]
We have a fix in 2.1

scylladb/scylla-tools-java@c4ba9fc850b5d3d8b73fe6e74174c73ab25e1317

@juliaangell - you can try and use the 2.1.rc's or wait for the final release

closing this - if there is still an issue pleas let us know.

**Comment by julienlau** [comment]
thanks
