### ISSUE TITLE
Something wrong with Upgrade Guide - Scylla 1.7 to 2.0 for Red Hat Enterprise Linux 7 or CentOS 7

### ISSUE THREAD

**Issue by julienlau** [scylladb/scylla#3047]
*Installation details*
Scylla version (or git commit hash): 1.7.4 -> 2.0.1
Cluster size: DC1: 3nodes + DC2: 1 node
OS (RHEL/CentOS/Ubuntu/AWS AMI): 
cat /etc/system-release
CentOS Linux release 7.4.1708 (Core) 

Hi,

I made the update on two different nodes and had issues with conf files in /etc/scylla.d
I think the update move the existing *.conf *.cfg *.yaml files contained in /etc/scylla.d to backup by renaming them with the suffix ".rpmsave".

When updating scylla-server with "yum update", launching scylla_io_setup is not sufficient to re-generate these files and I did not manage to perform the update. I was forced to perform a "yum uninstall" followed by "yum install".

In addition, I think that the rpm lacks a dependency for python34 since the /usr/lib/scylla/hex2list.py failed with an error (input() is void)  if I did not make a "yum update + yum upgrade".

Thanks for your work and best regards,
Julien

**Comment by tzach** [comment]
@amoskong @syuu1228

**Comment by amoskong** [comment]
@julienlau Did you see some notes in upgrading about processing the existed configure file?
I will try and give you a feedback soon, thanks for the report.

**Comment by julienlau** [comment]
I did not see any notes regarding all these configuration files in the doc. In fact, the upgrade doc says to save scylla.yaml and that is all.

**Comment by julienlau** [comment]
There is something wrong in the script perftune.py that goes wrong on the IRQ part when doing the scylla_setup of scylla 2.0

Things get better if I get the last version commited 11 days ago on the project seastar.

Some Debug information with the perftune.py packaged in current RPM of scylladb 2.0.2:
 2.0.2-0.20171201.07b039f.el7.centos.x86_64


/usr/lib/scylla/perftune.py --nic eth0    --options-file /etc/scylla.d/perftune.yaml --tune net
ERROR: 'NoneType' object is not iterable. Your system can't be tuned until the issue is fixed.

/usr/lib/scylla/
[root@CAS-01-SCUS]> /usr/lib/scylla/posix_net_conf.sh $IFNAME --options-file /etc/scylla.d/perftune.yaml
/usr/lib/scylla/perftune.py --nic eth0    --options-file /etc/scylla.d/perftune.yaml --tune net
ERROR: 'NoneType' object is not iterable. Your system can't be tuned until the issue is fixed.
/usr/lib/scylla/
[root@CAS-01-SCUS]> /usr/lib/scylla/posix_net_conf.sh $IFNAME --options-file /etc/scylla.d/perftune.yaml
/usr/lib/scylla/perftune.py --nic eth0    --options-file /etc/scylla.d/perftune.yaml --tune net
Traceback (most recent call last):
  File "/usr/lib/scylla/perftune.py", line 936, in <module>
    raise e
  File "/usr/lib/scylla/perftune.py", line 919, in <module>
    tuners.append(NetPerfTuner(args))
  File "/usr/lib/scylla/perftune.py", line 334, in __init__
    self.__nic2irqs = self.__learn_irqs()
  File "/usr/lib/scylla/perftune.py", line 501, in __learn_irqs
    return { self.nic : self.__learn_irqs_one(self.nic) }
  File "/usr/lib/scylla/perftune.py", line 485, in __learn_irqs_one
    all_irqs = set(learn_all_irqs_one("/sys/class/net/{}/device".format(iface), irqs2procline, iface)).intersection(irqs2procline.keys())
TypeError: 'NoneType' object is not iterable


learn_all_irqs_one("/sys/class/net/{}/device".format(iface), irqs2procline, iface) return None
ll /sys/class/net/eth0/device
lrwxrwxrwx. 1 root root 0 Dec 19 09:41 /sys/class/net/eth0/device -> ../../../000d3a74-98d6-000d-3a74-98d6000d3a74

/sys/
[root@CAS-01-SCUS]> find . -name modalias
./devices/0006:045E:0621.0001/modalias
./devices/pci0000:00/0000:00:00.0/modalias
./devices/pci0000:00/0000:00:07.0/VMBUS:01/modalias
./devices/pci0000:00/0000:00:07.0/PNP0800:00/modalias
./devices/pci0000:00/0000:00:07.0/PNP0C04:00/modalias
./devices/pci0000:00/0000:00:07.0/modalias
./devices/pci0000:00/0000:00:07.1/modalias
./devices/pci0000:00/0000:00:07.3/modalias
./devices/pci0000:00/0000:00:08.0/modalias
./devices/system/cpu/modalias
./devices/virtual/dmi/id/modalias
./devices/virtual/input/input2/modalias
./devices/platform/i8042/modalias
./devices/platform/i8042/serio0/input/input1/modalias
./devices/platform/i8042/serio0/modalias
./devices/platform/i8042/serio1/input/input4/modalias
./devices/platform/i8042/serio1/modalias
./devices/platform/alarmtimer/modalias
./devices/platform/pcspkr/input/input3/modalias
./devices/platform/pcspkr/modalias
./devices/platform/serial8250/modalias
./devices/platform/Fixed MDIO bus.0/modalias
./devices/platform/floppy.0/modalias
./devices/platform/microcode/modalias
./devices/platform/HYPER_V_GEN_COUN:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/PNP0303:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/PNP0501:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/PNP0501:01/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/2dd1ce17-079e-403c-b352-a1921ee207ee/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/99221fa0-24ad-11e2-be98-001aa01bbf6e/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/58f75a6d-d949-4320-99e1-a2a2576d581c/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/f5bee29c-1741-4aad-a4c2-8fdedb46dcc2/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/d34b2567-b9b6-42b9-8778-0a4ec0b955bf/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/d34b2567-b9b6-42b9-8778-0a4ec0b955bf/serio2/input/input5/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/d34b2567-b9b6-42b9-8778-0a4ec0b955bf/serio2/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/00000000-0001-8899-0000-000000000000/host3/target3:0:1/3:0:1:0/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/00000000-0001-8899-0000-000000000000/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/00000000-0000-8899-0000-000000000000/host2/target2:0:0/2:0:0:0/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/00000000-0000-8899-0000-000000000000/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/000d3a74-98d6-000d-3a74-98d6000d3a74/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/b6650ff7-33bc-4840-8048-e0676786f393/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/5620e0c7-8062-4dce-aeb7-520c7ef76171/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/fd149e91-82e0-4a7d-afa6-2a4166cbd7c0/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/f8b3781b-1e82-4818-a1c3-63d806ec15bb/host5/target5:0:0/5:0:0:0/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/f8b3781b-1e82-4818-a1c3-63d806ec15bb/host5/target5:0:0/5:0:0:1/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/f8b3781b-1e82-4818-a1c3-63d806ec15bb/host5/target5:0:0/5:0:0:2/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/f8b3781b-1e82-4818-a1c3-63d806ec15bb/host5/target5:0:0/5:0:0:3/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/f8b3781b-1e82-4818-a1c3-63d806ec15bb/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/242ff919-07db-4180-9c2e-b86cb68c8c55/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/4487b255-b88c-403f-bb51-d1f69cf17f87/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/f8b3781a-1e82-4818-a1c3-63d806ec15bb/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/2450ee40-33bf-4fbd-892e-9fb06e9214cf/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/PNP0700:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/PNP0800:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/PNP0B00:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/PNP0C02:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/PNP0C02:01/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/PNP0C04:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/PNP0F03:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/PNP0000:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/PNP0100:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/PNP0200:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0A03:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0C01:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0C0F:00/modalias
./devices/LNXSYSTM:00/device:00/PNP0C0F:01/modalias
./devices/LNXSYSTM:00/device:00/PNP0C0F:02/modalias
./devices/LNXSYSTM:00/device:00/PNP0C0F:03/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:00/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:01/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:02/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:03/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:04/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:05/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:06/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:07/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:08/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:09/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:10/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:11/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:12/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:13/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:14/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:15/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:16/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:17/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:18/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:19/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:20/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:21/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:22/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:23/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:24/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:25/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:26/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:27/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:28/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:29/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:30/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:31/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:32/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:33/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:34/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:35/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:36/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:37/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:38/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:39/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:0a/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:0b/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:0c/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:0d/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:0e/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:0f/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:1a/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:1b/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:1c/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:1d/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:1e/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:1f/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:2a/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:2b/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:2c/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:2d/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:2e/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:2f/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:3a/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:3b/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:3c/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:3d/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:3e/modalias
./devices/LNXSYSTM:00/device:00/LNXCPU:3f/modalias
./devices/LNXSYSTM:00/device:00/HYPER_V_GEN_COUN:00/modalias
./devices/LNXSYSTM:00/modalias
./devices/LNXSYSTM:00/LNXPWRBN:00/input/input0/modalias
./devices/LNXSYSTM:00/LNXPWRBN:00/modalias


/sys/
[root@CAS-01-SCUS]> find . -name modalias -exec cat {} \;
hid:b0006g0001v0000045Ep00000621
pci:v00008086d00007192sv00000000sd00000000bc06sc00i00
platform:VMBUS:01
platform:PNP0800:00
platform:PNP0C04:00
pci:v00008086d00007110sv00001414sd00000000bc06sc01i00
pci:v00008086d00007111sv00000000sd00000000bc01sc01i80
pci:v00008086d00007113sv00000000sd00000000bc06sc80i00
pci:v00001414d00005353sv00000000sd00000000bc03sc00i00
x86cpu:vendor:0000:family:0006:model:003F:feature:,0000,0001,0002,0003,0004,0005,0006,0007,0008,0009,000B,000C,000D,000E,000F,0010,0011,0013,0017,0018,0019,001A,001B,001C,002B,0034,003D,0068,006F,0070,0072,0074,007D,0080,0081,0089,008C,008D,0093,0094,0096,0097,0099,009A,009B,009C,009D,009E,009F,00C0,00C5,0120,0123,0125,0127,0128,0129,012D,0140
dmi:bvnAmericanMegatrendsInc.:bvr090006:bd05/23/2012:svnMicrosoftCorporation:pnVirtualMachine:pvr7.0:rvnMicrosoftCorporation:rnVirtualMachine:rvr7.0:cvnMicrosoftCorporation:ct3:cvr7.0:
input:b0006v045Ep0621e0001-e0,1,2,3,4,k110,111,112,113,114,r8,a0,1,m4,lsfw
platform:i8042
input:b0011v0001p0001eAB41-e0,1,4,11,14,k71,72,73,74,75,76,77,79,7A,7B,7C,7D,7E,7F,80,8C,8E,8F,9B,9C,9D,9E,9F,A3,A4,A5,A6,AC,AD,B7,B8,B9,D9,E2,ram4,l0,1,2,sfw
serio:ty06pr00id00ex00
input:b0011v0002p000Ae0000-e0,1,2,k110,111,r0,1,amlsfw
serio:ty01pr00id00ex00
platform:alarmtimer
input:b0010v001Fp0001e0100-e0,12,kramls1,2,fw
platform:pcspkr
platform:serial8250
platform:Fixed MDIO bus
platform:floppy
platform:microcode
platform:HYPER_V_GEN_COUN:00
acpi:PNP0303:PNP030B:
acpi:PNP0501:
acpi:PNP0501:
acpi:VMBUS:
vmbus:30e62795aed07b49adcee80ab0175caf
vmbus:1657e6f8b33c064a9a601889c5cccab5
vmbus:9eb6a8cf4a5bc04cb98b8ba1a1f3f95a
vmbus:f4ac6a2715ac6c4298dd7521ad3f01fe
vmbus:6dad12f9172bea48bd65f927a61c7684
input:b0011v0001p0001eAB00-e0,1,4,14,k71,72,73,74,75,76,77,79,7A,7B,7C,7D,7E,7F,80,8C,8E,8F,9B,9C,9D,9E,9F,A3,A4,A5,A6,AC,AD,B7,B8,B9,D9,E2,ram4,lsfw
serio:ty06pr00id00ex00
scsi:t-0x00
vmbus:32264132cb86a2449b5c50d1417354f5
acpi:VMBUS:
scsi:t-0x00
vmbus:32264132cb86a2449b5c50d1417354f5
vmbus:635161f83edfc546913ff2d2f965ed0e
vmbus:31600b0e13523449818b38d90ced39db
vmbus:02780ada77e3ac4a8e770558eb1073f8
vmbus:394f16571591784eab55382f3bd5422d
scsi:t-0x00
scsi:t-0x00
scsi:t-0x00
scsi:t-0x00
vmbus:d96361baa104294db60572e2ffb1dc7f
vmbus:e7f4a0a9455a964db8278a841e8c03e6
vmbus:f4ba7533159e304bb76567acb10d607b
vmbus:d96361baa104294db60572e2ffb1dc7f
vmbus:292efa3523ea364296ae3a6ebacba440
acpi:PNP0700:
acpi:PNP0800:
acpi:PNP0B00:
acpi:PNP0C02:
acpi:PNP0C02:
acpi:PNP0C04:
acpi:PNP0F03:PNP0F13:
acpi:PNP0000:
acpi:PNP0100:
acpi:PNP0200:
acpi:PNP0A03:
acpi:PNP0C01:
acpi:PNP0C0F:
acpi:PNP0C0F:
acpi:PNP0C0F:
acpi:PNP0C0F:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:LNXCPU:
acpi:HYPER_V_GEN_COUNTER_V1:VM_GEN_COUNTER:
acpi:LNXSYSTM:
input:b0019v0000p0001e0000-e0,1,k74,ramlsfw
acpi:LNXPWRBN:

**Comment by slivne** [comment]
@julienlau - were you able to upgrade - the last issue seems to be related to perftune and not to the upgrade ?

@amoskong - any update

@vladzcloudius - can you please take a look at the perftune part - if we have resolved the issue can you provide the version/commit that fixed this

**Comment by vladzcloudius** [comment]
@julienlau This issue duplicates the issue #3001. The issue has been fixed and closed. You can find the corresponding commit in the issue above.
Is your setup some PV virtualization machine?
