### ISSUE TITLE
memory setting gone after upgrade

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla#3049]
*Installation details*
Scylla version (or git commit hash): 2.0.1
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets= cores=40 hyperthreading= memory=256
Disks: (SSD/HDD, count) HDD, 2

we are using "-m 166G" to limit scylla to not interfere with other apps, this change was done to add the option in /etc/sysconfig/scylla-server
BUT after upgrade from 1.7.4 to 2.0.1 this setting was lost

perhaps we need something like memory.conf in addition to existing io and cpu confs (/etc/scylla.d/cpuset.conf) ?

**Comment by avikivity** [comment]
The rpm spec file says:

```
%config(noreplace) %{_sysconfdir}/sysconfig/scylla-server
```

So `scylla-server` should not have replaced. Do you have .rpmnew or .rpmsave files there? Do they have the edited content?

/cc @syuu1228

**Comment by tarzanek** [comment]
diff /etc/sysconfig/scylla-server /etc/sysconfig/scylla-server.rpmsave
38c38
< SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix"
---
> SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --memory 166G"

bear in mind this is 1.7.4 to 2.0.1

**Comment by tarzanek** [comment]
OK, I have an explanation now, this box was reinstalled and not upgraded ...
hence the overwrite ...

**Comment by avikivity** [comment]
Ok, thanks for confirming.

**Comment by tarzanek** [comment]
sorry for false alarm, thank you
