### ISSUE TITLE
scylla start failed

### ISSUE THREAD

**Issue by zhiguoxu** [scylladb/scylla#3055]
*Installation details*
Scylla version (or git commit hash): 2.0
Cluster size : 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos 7.3

Scylla failed to start，the error log shows below info ：
12月 08 15:42:01 lw.71.zhizi scylla_prepare[56530]: tuning /sys/devices/pci0000:00/0000:00:01.0/0000:03:00.0/host0/target0:0:1/0:0:1:0/block/sdb/sdb1
12月 08 15:42:01 lw.71.zhizi scylla[56582]: scylla: core/resource.cc:202: resource::allocate_io_queues(hwloc_topology*&, resource::configuration, std::vector<resource::cpu>)::<lambda(unsigned int)>: Assertion `0' failed.
12月 08 15:42:01 lw.71.zhizi scylla[56582]: Aborting.
Can anyone give me any clue about this situation.

**Comment by dorlaor** [comment]
Something is fishy with hardware discovery.
What's the hardware/software setup?
What's the output of hwloc-ls

**Comment by zhiguoxu** [comment]
hwloc-ls:
Machine (126GB)
  Package L#0 + L3 L#0 (30MB)
    L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
      PU L#0 (P#0)
      PU L#1 (P#12)
    L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1
      PU L#2 (P#1)
      PU L#3 (P#13)
    L2 L#2 (256KB) + L1d L#2 (32KB) + L1i L#2 (32KB) + Core L#2
      PU L#4 (P#2)
      PU L#5 (P#14)
    L2 L#3 (256KB) + L1d L#3 (32KB) + L1i L#3 (32KB) + Core L#3
      PU L#6 (P#3)
      PU L#7 (P#15)
    L2 L#4 (256KB) + L1d L#4 (32KB) + L1i L#4 (32KB) + Core L#4
      PU L#8 (P#4)
      PU L#9 (P#16)
    L2 L#5 (256KB) + L1d L#5 (32KB) + L1i L#5 (32KB) + Core L#5
      PU L#10 (P#5)
      PU L#11 (P#17)
    L2 L#6 (256KB) + L1d L#6 (32KB) + L1i L#6 (32KB) + Core L#6
      PU L#12 (P#6)
      PU L#13 (P#18)
    L2 L#7 (256KB) + L1d L#7 (32KB) + L1i L#7 (32KB) + Core L#7
      PU L#14 (P#7)
      PU L#15 (P#19)
    L2 L#8 (256KB) + L1d L#8 (32KB) + L1i L#8 (32KB) + Core L#8
      PU L#16 (P#8)
      PU L#17 (P#20)
    L2 L#9 (256KB) + L1d L#9 (32KB) + L1i L#9 (32KB) + Core L#9
      PU L#18 (P#9)
      PU L#19 (P#21)
    L2 L#10 (256KB) + L1d L#10 (32KB) + L1i L#10 (32KB) + Core L#10
      PU L#20 (P#10)
      PU L#21 (P#22)
    L2 L#11 (256KB) + L1d L#11 (32KB) + L1i L#11 (32KB) + Core L#11
      PU L#22 (P#11)
      PU L#23 (P#23)
  HostBridge L#0
    PCIBridge
      PCI 1000:005d
        Block(Disk) L#0 "sda"
        Block(Disk) L#1 "sdb"
        Block(Disk) L#2 "sdc"
        Block(Disk) L#3 "sdd"
        Block(Disk) L#4 "sde"
        Block(Disk) L#5 "sdf"
        Block(Disk) L#6 "sdg"
        Block(Disk) L#7 "sdh"
    PCIBridge
      PCI 14e4:165f
        Net L#8 "em3"
      PCI 14e4:165f
        Net L#9 "em4"
    PCIBridge
      PCI 14e4:165f
        Net L#10 "em1"
      PCI 14e4:165f
        Net L#11 "em2"
    PCI 8086:8d62
    PCIBridge
      PCIBridge
        PCIBridge
          PCIBridge
            PCI 102b:0534
              GPU L#12 "card0"
              GPU L#13 "controlD64"
    PCI 8086:8d02

**Comment by zhiguoxu** [comment]
/etc/sysconfig/scylla-server
# ethernet device name
IFNAME=em1

# setup NIC's interrupts, RPS, XPS (posix)
SET_NIC=yes

# ethernet device driver (dpdk)
ETHDRV=tg3

# ethernet device PCI ID (dpdk)
ETHPCIID=0000:01:00.0

# number of hugepages
NR_HUGEPAGES=64

# user for process (must be root for dpdk)
USER=scylla

# group for process
GROUP=scylla

# scylla home dir
SCYLLA_HOME=/home/ssd/scylla

# scylla config dir
SCYLLA_CONF=/etc/scylla

# scylla arguments (for posix mode)
SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --memory=16G --smp=8"

## scylla arguments (for dpdk mode)
#SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack native --dpdk-pmd"

# setup as AMI instance
AMI=no

**Comment by zhiguoxu** [comment]
The problem seems to be in /etc/scylla.d/cpuset.conf, the configure for cpu core number larger than configuration in /etc/sysconfig/scylla-server.

**Comment by amoskong** [comment]
Can you provide /etc/scylla.d/io.conf & /etc/scylla.d/cpuset.conf?

**Comment by slivne** [comment]
@zhiguoxu - can you please provide the resolution / additional info requested so we can fix this.

Closing the issue for now - will reopen when we get the additional info
