### ISSUE TITLE
CREATE USER IF NOT EXISTS strips superuser

### ISSUE THREAD

**Issue by hakuch** [scylladb/scylla#3058]
*Installation details*
Scylla version (or git commit hash): 2.0.0 (and `master`)

I'm using `PasswordAuthenticator` and `CassandraAuthorizer`.

If a user is a superuser, then executing `CREATE USER IF NOT EXISTS` without changing superuser status will always strip superuser from the user.

## Example

```
cassandra@cqlsh> CREATE USER bob WITH PASSWORD 'bob';
cassandra@cqlsh> LIST USERS;

 name      | super
-----------+-------
       bob | False
 cassandra |  True

(2 rows)
cassandra@cqlsh> ALTER USER bob SUPERUSER;
cassandra@cqlsh> LIST USERS;

 name      | super
-----------+-------
       bob |  True
 cassandra |  True

(2 rows)
cassandra@cqlsh> CREATE USER IF NOT EXISTS bob WITH PASSWORD 'bob';
cassandra@cqlsh> LIST USERS;

 name      | super
-----------+-------
       bob | False
 cassandra |  True

(2 rows)
```

I've verified that this bug does not effect Apache Cassandra.

/cc @elcallio

**Comment by hakuch** [comment]
I'm reasonably sure the culprit is a missing `return` statement [here](https://github.com/scylladb/scylla/blob/scylla-2.0.0/cql3/statements/create_user_statement.cc#L78).

I can write a patch for `master`, but it will need to be back-ported to all relevant release-branches.

**Comment by hakuch** [comment]
Patch at https://groups.google.com/d/msg/scylladb-dev/Z4pI1mg_0WA/bQcqXhD_AgAJ.

**Comment by tzach** [comment]
@hakuch if I understand this correctly, its not an urgent issue, as it limits (not extended) old Bob privileges. If this is teh case, backporting is less urgent.
