### ISSUE TITLE
Do we consider to change the default cluster name back to 'Test Cluster' for compatibility?

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3060]
*Installation details*
Scylla version (or git commit hash): 2.1.rc0
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

In commit 0608947, @daniel-from-scylla not just added warning, but also changed the default cluster name. This change had been included in 2.1.rc0

User will fail to start the node if they use new scylla.yaml from 2.1, if user really used original default cluster name `Test Cluster`. They can explicitly reassign cluster_name to 'Test Cluster' in scylla.yaml to solve the problem.

My concern is that:
- can we assume our users know above solution when they touch the error? if not we need to mention this in release note or upgrade guide.
- solution for changing the cluster name (I guess it's not easy)
- Do we consider to change the default cluster name back to 'Test Cluster'?

More:
- reminder user to change default cluster_name in scylla_setup?  @tzach @slivne

**Comment by amoskong** [comment]
Posted a fix: 
```
[PATCH scylla] reset default cluster_name back to 'Test Cluster' for compatibility

There are some users used original default cluster_name 'Test Cluster',
they will fail to start the node for cluster_name change if they use
new scylla.yaml.

'ScyllaDB Cluster' isn't more beautiful than 'Test Cluster', reset back
to original old to avoid problem for users.
```

**Comment by slivne** [comment]
When will they use new scylla.yaml when they add a new node to an existing
cluster / replace a node ?

They should not hit this when they are upgrading an existing cluster.

**Comment by tzach** [comment]
This should apply only for adding new nodes, and assuming they do not have a new cluster name already.
This is a low-risk issue since its easy to find (node won't start).

**Comment by amoskong** [comment]
In upgrading existing cluster, they might overwrite old scylla.yaml.

**Comment by tzach** [comment]
> In upgrading existing cluster, they might overwrite old scylla.yaml.

Upgrade does not update scylla.yaml

**Comment by amoskong** [comment]
In Ubuntu 16.04, it asks user to make a decision (Y or I  : install the
package maintainer's version)

```

scylla-test@amos-ubuntu16:/etc/scylla$ sudo apt dist-upgrade scylla

...

Setting up scylla-conf (2.1~rc0-0.20171212.516a1ae-0ubuntu1~xenial) ...


Configuration file '/etc/scylla/scylla.yaml'

 ==> Modified (by you or by a script) since installation.

 ==> Package distributor has shipped an updated version.

   What would you like to do about it ?  Your options are:

    Y or I  : install the package maintainer's version

    N or O  : keep your currently-installed version

      D     : show the differences between the versions

      Z     : start a shell to examine the situation

 The default action is to keep your current version.

*** scylla.yaml (Y/I/N/O/D/Z) [default=N] ?

```
