### ISSUE TITLE
nodetool refresh in large boxes can be very slow

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#3064]
`nodetool refresh` needs to disable writes from the column family that it is refreshing. That is dangerous, since it can lead to memory overflow.

It also has to reach agreement with other shards about when to stop, and grab a lock in every shard so we know that it is safe to add tables to the node.

However, we don't stop compactions to do that. So it could be that one shard that has already stopped now has to wait minutes before one other shard finishes compacting and grabs the lock.

Since this is not a common operation, we could stop compactions to minimize that time.

**Comment by glommer** [comment]
another option that @raphaelsc and I had already discussed many times is that maybe we shouldn't wait for that lock at all if we are moving files from the update directory. That should be po

**Comment by slivne** [comment]
@glommer can you please add some context - I assume you have seen that on the field - machine of how many cores - how long did it take ?

**Comment by glommer** [comment]
Ok, this is much simpler than we've been discussing.

There is no need to prevent sstables for being written for nodetool refresh. We only need to prevent sstables from being *created*, since that is what determines the generation number. Once the generation number is established, we can safely proceed moving our files: 

Therefore we only really need to take the lock for a very small amount of time and release it.

I'll send a patch

**Comment by raphaelsc** [comment]
closing this issue as refresh is no longer disabling writes for a table after off-strategy changes
