### ISSUE TITLE
client_encryption_options.require_client_auth not work

### ISSUE THREAD

**Issue by 303248153** [scylladb/scylla#3072]
*Installation details*
Scylla version (or git commit hash): 2.0.2-0.20171201.07b039f
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

Hello, about the option "require_client_auth" under "client_encryption_options" in scylla.yaml, I found it's not works as expected.
When the client certificate is not provided, the scylla server will refuse the connection.
But when an **invalid** client certificate is provided, the scylla server will accept the connection without check the client certificate with trust store.

The weird thing is "require_client_auth" under "server_encryption_options" is work, an invalid client certificate will cause "The certificate is NOT trust" error between internode communication.
I wrote a reproduce script, please download the attached file, ensure docker image "scylladb/scylla" is exists and run main.sh, the expected behavior is "cqlsh --ssl" failed with certificate error.

[reproduce-pack.zip](https://github.com/scylladb/scylla/files/1570348/reproduce-pack.zip)

**Comment by glommer** [comment]
@elcallio

**Comment by elcallio** [comment]
Verified. Seems we sort of misunderstood the gnutls "required" attribute. It only demands a remote cert. It does not run verification automatically. Needs a seastar fix.

**Comment by elcallio** [comment]
See scylladb/seastar#393

**Comment by slivne** [comment]
lets close this after the patch is merged to 2.1 stream
