### ISSUE TITLE
Warnings when installing Scylla on Debian 8

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#3074]
*Installation details*
Scylla version (or git commit hash): 2.0
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 8 on GCE

When running `sudo apt-get install scylla` I get the following warnings:

```
W: Size of file /var/cache/apt/archives/partial/scylla-jmx_2.0.2-20171130.65da215-1~jessie_all.deb is not what the server reported 5874232 2819958
W: Size of file /var/cache/apt/archives/partial/scylla-tools_2.0.2-20171130.42be60a-1~jessie_all.deb is not what the server reported 2169406 17038
```

Other than that the install is successful

**Comment by tzach** [comment]
@syuu1228 ?

**Comment by syuu1228** [comment]
@tzach Not reproducible for me, and I think it should able to fix by “apt-get update” (or “apt-get clean” prior to update, if the error doesn’t fix)
Maybe last “apt-get update” failed or outdated or something..

**Comment by slivne** [comment]
@amoskong ? can you also try ?

**Comment by amoskong** [comment]
Not reproduce for me.

It also doesn't exist on latest job:
http://jenkins.cloudius-systems.com:8080/job/scylla-2.0-debian8-deb-test/label=huginn/46/artifact/latest/job.log

**Comment by slivne** [comment]
closing for now
