### ISSUE TITLE
Debian 8 installation  does not add scylla_setup to default path 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#3076]
*Installation details*
Scylla version (or git commit hash): 2.0
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 8 on GCE / AWS

After the installation process completes, scylla_setup is available on 
```
/usr/lib/scylla/scylla_setup
/usr/sbin/scylla_setup
```
but not in the default path, as it is for other distors and how it is documented[1]

[1] http://www.scylladb.com/download/debian8/

**Comment by syuu1228** [comment]
@tzach /usr/sbin is not on PATH for non-privileged users since the command is only for privileged user. We just need to do "sudo scylla_setup" instead.

**Comment by syuu1228** [comment]
It's same on other distributions.

**Comment by slivne** [comment]
@tzach - can I close this
