### ISSUE TITLE
scylla_io_setup freeze the VM with 100% IO wait

### ISSUE THREAD

**Issue by santithorn** [scylladb/scylla#3078]
*Installation details*
Scylla version (or git commit hash): 2.0.2
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.3.1611

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): VM (KVM)
Hardware: vcores=2 memory=8 GB
Disks: 100GB qcow2 image on 8xHDD (RAID-5)

Fresh install CentOS 7.3.1611
Install scylla 2.0.2 and run scylla_io_setup, output shows:

Generating evaluation file sized 10GB...10GB written in 16 seconds

After 5-10 seconds, the system load starts increasing, iostats -x shows:

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0.00    0.00    0.00  100.00    0.00    0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
vda               0.00     0.00    0.00    0.00     0.00     0.00     0.00   128.00    0.00    0.00    0.00   0.00 100.00

And the system becomes unresponsive to any command that seems to access disk. Need to hard reset the VM.

**Comment by avikivity** [comment]
Looks like a virtio bug. Try `echo 100 > /sys/block/vda/queue/nr_requests`.

Also, you will have a bad experience with HDD and with qcow2.

**Comment by santithorn** [comment]
I try `echo 100 > /sys/block/vda/queue/nr_requests` and it still freezes with avgqu-sz saturated at max (100).

However, I convert the disk image from qcow2 to raw format and it now can survive the iotune test.

**Comment by slivne** [comment]
since you managed to resolve the problem closing this - if need be we can reopen
