### ISSUE TITLE
unimplemented causes are fully unimplemented or partially unimplemented ?

### ISSUE THREAD

**Issue by baiwfg2** [scylladb/scylla#3079]
*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

Recently I've been trying scylla and met some unimplemented issues such as `index` and `batch update`. So I found the `unimplemented::cause` in source code. I wonder the causes in namespace `unimplemented`  are fully unimplemented or partially unimplemented. As far as I know, `CONSISTENCY` and `GOSSIP` are implemented, although I don't know whether they're complete.

And any priorities plans on implementing them ?

Thanks.

**Comment by tgrabiec** [comment]
It depends on the cause. `GOSSIP` and `CONSISTENCY` causes are not used any more, they're fully implemented. `INDEXES`, which corresponds to secondary indexes, is being implemented, it's not yet fully implemented. I couldn't find a cause for `batch update`, which version of Scylla is that?

Questions like this are better asked on the mailing list or slack: http://www.scylladb.com/open-source/
