### ISSUE TITLE
cassandra-stress: com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency LOCAL_ONE

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#308]
With the same cmd:

cassandra-stress write duration=2m -mode native cql3 -rate threads=150 -node 127.0.0.1 -log file=perf.write.log.1

The cluster has 3 nodes.

Sometimes I saw:

com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency LOCAL_ONE (1 required but only 0 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency LOCAL_ONE (1 required but only 0 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency LOCAL_ONE (1 required but only 0 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency LOCAL_ONE (1 required but only 0 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency LOCAL_ONE (1 required but only 0 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency LOCAL_ONE (1 required but only 0 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency LOCAL_ONE (1 required but only 0 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency LOCAL_ONE (1 required but only 0 alive)
com.datastax.driver.core.exceptions.UnavailableException: Not enough replica available for query at consistency LOCAL_ONE (1 required but only 0 alive)

**Comment by slivne** [comment]
@asias is this reproducible on head / 0.18

**Comment by asias** [comment]
I can not reproduce this with head (3 out 3 runs)

commit fedba9d6cd475e0f0e661e0a57f0ff60fdbe9d17
Merge: b42a32e 697b164
Author: Avi Kivity <avi@scylladb.com>
Date:   Wed Feb 24 13:44:06 2016 +0200

with the same c-s cmd. I think we can close the issue now.
