### ISSUE TITLE
Swap order of arguments in mutation::mutation(dht::decorated_key, schema_ptr) constructor

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#3084]
All other constructor variants have schema before the key. It is annoying that in some cases the order is reversed and one guesses it wrong.

**Comment by jvanz** [comment]
I'm working on this right now... ;)

**Comment by jvanz** [comment]
I believe we can close this issue. :)

**Comment by avikivity** [comment]
You can have github auto-close the issue by adding "Fixes #xyz" on the commit log.
