### ISSUE TITLE
make_forwardable() assumes single-partition range

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#3089]
Scylla version (or git commit hash): 2.1

As a result, memtable/cache multi-partition reads are broken for streamed_mutation::forwarding::yes. Probably affects only tests, but this should be fixed.

**Comment by haaawk** [comment]
@tgrabiec I created a test that supposed to reproduce the problem but it does not want to fail: https://github.com/scylladb/seastar-dev/commit/7701512efce33f234232b4f5e85e5afa28ff541e

**Comment by haaawk** [comment]
I found a problem with fast_forward_to(partition_range&). Test and fix are here: https://github.com/scylladb/seastar-dev/commits/haaawk/3089_v2
