### ISSUE TITLE
Schema disagreement. Too often changes the schema version.

### ISSUE THREAD

**Issue by vabezruchko** [scylladb/scylla#3091]
*Installation details*
Scylla version (or git commit hash): 2.0.2-0.20171130.07b039f-1, 2.0.0-0.20170929.e265c91-1
Cluster size:
OS (Debian 8): 32

Scylla's nodes receive a lot of messages "[shard 0] database - Schema version changed to" after restart one node. Network tx traffic on the restarted node is more than other nodes in 3 times. Cpu consumption rose to almost 100% on the restarted node and by 15% on other nodes. After stopping this node, the cluster returns to normal state.

**Comment by tgrabiec** [comment]
Could you attach the logs for that node, and for one of the healthy nodes?

You mentioned two versions, are you performing a rolling upgrade from 2.0.0 to 2.0.2?

**Comment by vabezruchko** [comment]
>>You mentioned two versions, are you performing a rolling upgrade from 2.0.0 to 2.0.2?
No, we upgraded just one node because we are afraid to restart other nodes.

I attached two log files from the restarted node and some other node.

[restarted_scylla_node_log.txt](https://github.com/scylladb/scylla/files/1578585/restarted_scylla_node_log.txt)
[some_scylla_node_log.txt](https://github.com/scylladb/scylla/files/1578586/some_scylla_node_log.txt)

**Comment by tgrabiec** [comment]
Can you send the logs since the boot of each of those nodes?

A copy of sstables of the system_schema keyspace from an old node and a new node would also be helpful.

**Comment by vabezruchko** [comment]
I attached the log since boot from the restarted node. But we don't have the log since boot from other nodes. 

Also i attached copy of sstables of the system_schema keyspace from those nodes.

[scylla_restarted_node_boot_log.txt.zip](https://github.com/scylladb/scylla/files/1581869/scylla_restarted_node_boot_log.txt.zip)
[scylla_another_node_log.txt.zip](https://github.com/scylladb/scylla/files/1581871/scylla_another_node_log.txt.zip)

[data_old_node.zip](https://github.com/scylladb/scylla/files/1581891/data_old_node.zip)
[scylla_new_node_data.zip](https://github.com/scylladb/scylla/files/1581893/scylla_new_node_data.zip)

**Comment by vabezruchko** [comment]
Is there some workaround to attach the node to the cluster without performance issues?

We tried to replace the node, but still have this problem.

Our problem may be related to https://github.com/scylladb/scylla/issues/3068, because previously we recreated keyspace with UDT.

**Comment by slivne** [comment]
3068 is fixed in 2.1.3

if the cluster was upgrade from 1.7 we have found an issue #3394 - could this be it ? - to solve this there is a need todo a rolling restart in the cluster.

I am closing this - if the problem still persists with 2.1.3 and after a rolling restart - please post on the issue with updated logs and I'll reopen
