### ISSUE TITLE
the new labels in 2.1 for database queue are confusing

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#3094]
In 2.1 instead of the database active_reads/queue streaming and system be part of the metrics name where made into a label.

But the labels are confusing.
Now it's
for example:
streaming="read" 

It would be clearer if it would something like:
src="streaming"

**Comment by slivne** [comment]
@glommer / @avikivity your input

**Comment by amnonh** [comment]
This is already solve, it should be closed

**Comment by slivne** [comment]
please provide the commit id

**Comment by amnonh** [comment]
a0a1961b6dbfeb784294cbaf02e087f73974ad75
