### ISSUE TITLE
transitional_auth: User can't login as anonymous when authentication failed

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3096]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20171121.c1b97d1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

Test steps:
1. prepare a cluster with 1 node (using default AllowAll authenticator)
2. Scylla: set authenticator to TransitionalAuthenticator
3. Restart node
4. $ cqlsh -ucassandra -pwrong -e 'list users'

Expected result in step4:
Unauthorized: Error from server: code=2100 [Unauthorized] message="You have to be logged in and not anonymous to perform this request"

Real Results in step4:
Connection error: ('Unable to connect to any servers', {'127.0.0.1': AuthenticationFailed('Failed to authenticate to 127.0.0.1: Error from server: code=0100 [Bad credentials] message="authentication failed"',)})

-------

When I tested with DSE (transitional_mode: normal), I can get expected result in step4

**Comment by amoskong** [comment]
Setup transitional_mode to `normal` in DSE:

```
ccm stop

ccm updateconf "authenticator: com.datastax.bdp.cassandra.auth.DseAuthenticator"
ccm updateconf "authorizer: com.datastax.bdp.cassandra.auth.DseAuthorizer"

ccm updatedseconf "authentication_options.enable: true"
ccm updatedseconf "authentication_options.transitional_mode: normal"

ccm start
```

**Comment by elcallio** [comment]
This was broken by ba6a41d397923c45045c4dddcbfa2c667a3a59ef. By removing the global auth object, it made sasl challenge unable to find the right authenticator.

**Comment by hakuch** [comment]
For the record, https://github.com/scylladb/scylla/commit/ba6a41d397923c45045c4dddcbfa2c667a3a59ef [did not](https://groups.google.com/d/msg/scylladb-dev/q-O7r24m5i0/jvPKUhGkDQAJ) break this.
