### ISSUE TITLE
transitional_auth: User can't login as anonymous if no credentials are passed

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3098]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20171121.c1b97d1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

Test steps:
1. prepare a cluster with 1 node (using default AllowAll authenticator)
2. Scylla: set authenticator to TransitionalAuthenticator
3. Restart node
4. $ cqlsh -e 'list users'

Expected result in step4:
Unauthorized: Error from server: code=2100 [Unauthorized] message="You have to be logged in and not anonymous to perform this request"

Real Results in step4:
Connection error: ('Unable to connect to any servers', {'127.0.0.1': AuthenticationFailed('Remote end requires authentication.',)})

-------

When I tested with DSE (transitional_mode: normal), I can get expected result in step4.

**Comment by amoskong** [comment]
From: https://docs.datastax.com/en/dse/5.1/dse-admin/datastax_enterprise/security/Auth/secEnableDseAuthenticator.html

transitional_mode: `normal`
- Only users that provide valid credentials are logged in.
- If the authentication is successful, the user is logged in.
- If the authentication fails, the user is logged in as anonymous.
- `If no credentials are passed, the user is logged in as anonymous.`

This issue relates with the last item - no credentials are passed

**Comment by amoskong** [comment]
I could not reproduce problem with DSE now with steps in [comment 0](https://github.com/scylladb/scylla/issues/3098#issue-284394547).

Setup transitional_mode to `normal` in DSE:

```
ccm stop

ccm updateconf "authenticator: com.datastax.bdp.cassandra.auth.DseAuthenticator"
ccm updateconf "authorizer: com.datastax.bdp.cassandra.auth.DseAuthorizer"

ccm updatedseconf "authentication_options.enable: true"
ccm updatedseconf "authentication_options.transitional_mode: normal"

ccm start
```
----

And I checked cassandra-driver code and cql protocol, they are conflicted with the description in DSE doc.

If server returns AUTHENTICATE msg, client without credentials will raise error (`Remote end requires authentication`). But server have to return AUTHENTICATE msg in startup stage for verifying the credenticals of (normal user & super).

### Conclusion:
It seems DSE doc cheated us.

References:
- https://raw.githubusercontent.com/apache/cassandra/trunk/doc/native_protocol_v4.spec
- https://docs.datastax.com/en/dse/5.1/dse-admin/datastax_enterprise/security/Auth/secEnableDseAuthenticator.html

**Comment by amoskong** [comment]
The server side of both DSE & Scylla (with my fix [1]) has ability to treat user without credenticals to anonymous. But cqlsh client won't enter this condition, it won't send AUTH_RESPONSE to server without credenticals.

Quote from [CQL protoco v4](https://raw.githubusercontent.com/apache/cassandra/trunk/doc/native_protocol_v4.spec):
The server will respond by either a READY message (...) or AUTHENTICATE message
  (in which case `credentials will need to be provided` using AUTH_RESPONSE).

[1] [PATCH scylla v2 0/3] fix transitional authenticator of authentication fail

**Comment by slivne** [comment]
@elcallio - is this still open - did we fix this -

**Comment by elcallio** [comment]
According to the ultimate source of info, i.e. source code, transitional mode is supposed to give "all" permissions to super user, and "read, write, describe, authorize" to everyone else. Describe keyspace seems to fall into this set?

**Comment by amoskong** [comment]
This issue is about login, not permissions after login.

**Comment by elcallio** [comment]
Fair enough. However, I get the exact same behaviour with DSE 5.1 (transitional mode = normal) and scylla (transitional authenticator + authorizer). From what I can tell, it is indeed the clients that refuse to go ahead with no user/pass once asked for it (which they are by both). 
Both cqlsh and Java driver exhibit the same behaviour, but I would call this working as designed. The docs should reflect that one should ensure adding credentials to clients _before_ transitioning even to transitional auth.

**Comment by slivne** [comment]
@amoskong - calle provided his answer - do you agree
 in the docs, can you validate that this is aligned 
https://github.com/scylladb/scylla-docs/pull/709

**Comment by amoskong** [comment]
@slivne Agree with calle's answer (it's a design not problem, doc reflect that one should ensure adding credentials to clients).  Our document scylladb/scylla-docs#709  clearly mentions this.

**Comment by slivne** [comment]
Tx, so I am closing this item.
