### ISSUE TITLE
Sample queries time, keep track of slow queries

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#31]
DSE Performance Service[1] collect slow queries in systems tables.
cql_slow_log_threshold_ms is used to set the threshold for what is consider slow
It will be useful to have a similar feature.

[1] http://docs.datastax.com/en/datastax_enterprise/4.7/datastax_enterprise/mngServ/capSrv/capSrvTOC.html

**Comment by slivne** [comment]
we support tracing of slow queries
