### ISSUE TITLE
Scylla on docker swarm and docker compose

### ISSUE THREAD

**Issue by Superman132** [scylladb/scylla#3101]
*Installation details*
Scylla version (or git commit hash): Latest docker image
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

I was just wondering how to use Scylladb in a cluster with docker swarm and docker compose, since the Scylladb docker image only accepts the seeds as `docker run` command line arguments instead of environment variables.

**Comment by tzach** [comment]
You can see an example of Docker swarm here
https://github.com/scylladb/scylla-code-samples/blob/master/mms/docker-compose.yml

More on Scylla on Docker here
http://docs.scylladb.com/procedures/best_practices_scylla_on_docker/

I'm closing this issue, please reopen if you have more questions or use the mailing list 
https://groups.google.com/forum/#!forum/scylladb-users to follow up
