### ISSUE TITLE
MIN/MAX aggregation functions can't be called for date/timestamp/timeuuid type columns

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3104]
*Installation details*
Scylla version (or git commit hash): master
Cluster size: 1 node
OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora

I received exception when tried call MIN/MAX for date/timestamp/timeuuid type columns.
This function is working in Cassandra (checked in v3.2).
Scenario:
1. Create table: create table testda(k int primary key, c date);
 Add data:
   insert into testda (k,c) values(0, '2017-12-02');
   insert into testda (k,c) values(0, '2016-12-02');
3. Select min (same error when data): select min(c) from testda;
Exception:
InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid call to function min, none of its type signatures match (known type signatures: system.min : (org.apache.cassandra.db.marshal.UTF8Type) -> org.apache.cassandra.db.marshal.UTF8Type, system.min : (org.apache.cassandra.db.marshal.DoubleType) -> org.apache.cassandra.db.marshal.DoubleType, system.min : (org.apache.cassandra.db.marshal.FloatType) -> org.apache.cassandra.db.marshal.FloatType, system.min : (org.apache.cassandra.db.marshal.DecimalType) -> org.apache.cassandra.db.marshal.DecimalType, system.min : (org.apache.cassandra.db.marshal.IntegerType) -> org.apache.cassandra.db.marshal.IntegerType, system.min : (org.apache.cassandra.db.marshal.LongType) -> org.apache.cassandra.db.marshal.LongType, system.min : (org.apache.cassandra.db.marshal.Int32Type) -> org.apache.cassandra.db.marshal.Int32Type, system.min : (org.apache.cassandra.db.marshal.ShortType) -> org.apache.cassandra.db.marshal.ShortType, system.min : (org.apache.cassandra.db.marshal.ByteType) -> org.apache.cassandra.db.marshal.ByteType)"

**Comment by roydahan** [comment]
@juliayakovlev, did we update the tests after the fix?

**Comment by juliayakovlev** [comment]
@roydahan  Yes, it should be run. I updated them
