### ISSUE TITLE
disable search engine record of repositories.scylladb.com

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3105]
If repositories.scylladb.com only provides private links, we should disable search engine record on it.

I found a test private link was recorded by Google:

![screenshot from 2017-12-28 20-38-58](https://user-images.githubusercontent.com/309708/34411065-03560a6e-eb9a-11e7-8122-961285cfecf8.png)

@amnonh

**Comment by amnonh** [comment]
@tzach what do you want to to do about it?

**Comment by tzach** [comment]
As a start, add no search
https://support.google.com/webmasters/answer/93710?hl=en

**Comment by amnonh** [comment]
Tzach I don't think adding noindex to the http reply would have any effect.

we should probably not index the download page

**Comment by avikivity** [comment]
robots.txt?

**Comment by tzach** [comment]
> we should probably not index the download page

How?

**Comment by amnonh** [comment]
On Wed, Jan 17, 2018 at 11:29 AM, Avi Kivity <notifications@github.com>
wrote:

> robots.txt?
>
Yup

**Comment by tzach** [comment]
```
<meta name="robots" content="noindex, nofollow">
```

**Comment by amnonh** [comment]
@tzach that for the html page, not the download

**Comment by slivne** [comment]
closing fixed
