### ISSUE TITLE
Scylla node shutdown cql server but the process is not dead

### ISSUE THREAD

**Issue by zhiguoxu** [scylladb/scylla#3107]
Installation details
Scylla version (or git commit hash): 1.6.4
Cluster size : 12
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos 7.3

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets=1 cores=8 hyperthreading=2 memory=128G
Disks: (SSD/HDD, count) SSD 16T

Our scylladb nodes always run into an abnormal status and stop the CQL server.
"nodetool status" shows it is in Normal state, but other nodes show it is Dead.
The log shows below:

[shard 0] batchlog_manager - Exception in batch replay: exception::read_timeout_exception (Operation timed out for system.batchlog - reveiced only 0 responses form 1 CL=ONE.)
[shard 0] stable - stable_writer failed to close file: std::bad_alloc (std::bad_alloc)
[shard 0] compassion_manager - companion failed: std::bad_alloc (std::bad_alloc)
[shard 0] storage_service - Shutting down communications due to I/O errors until operator intervention
[shard 0] storage_service Stop transport: starts
[shard 0] gossip -My status = NORMAL
[shard 0] gossip - Announcing shutdown
[shard 0] storage_service - Node XXX state jump to normal
[shard 0] seastar - Exceptional future ignored: storage_io_error(Storage I/O error: 9: Bad file description)
[shard 0] storage_service - stop transport: stop_gossiping down
[shard 0] storage_service - Thrift server stopped
[shard 0] storage_service - CQL server stopped
[shard 0] storage_service - Stop transport: shutdown rpc and cql server done

Since the process is not dead, the server will not be restarted by systemd, and this node will keep this state forever. Can anyone give me a hint of how to solve this problem?

**Comment by slivne** [comment]
On IO/Error scylla drains the node and leaves it up so that the node can be probed.
The commit 34f6218dc54fc64e37f879602e1a44bfb6c599c6  will change the reported status of the node
