### ISSUE TITLE
CAST/MIN(CAST)/MAX(CAST)/AVG(CAST) and others: wrong precision after cast from decimal to double, float to double, double to float and from integers to float/double.

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3112]
Scylla version (or git commit hash): master

CAST/MIN(CAST)/MAX(CAST)/AVG(CAST)/ CAST(AVG)/CAST(SUM) /CAST(MIN): wrong precision after cast from float to double, double to float , from int to float/double, from decimal to double and float.

FLOAT_PRECISION Cassandra parameter = 10.
Cassandra (expected result) returns 10 digits after "."
Scylla (actual results) - 11 

Scenario 1: **float**
1. Create and pre-fill table:
    CREATE TABLE cast_float_test (k int PRIMARY KEY, float_clmn float
    INSERT INTO cast_float_test (k, float_clmn) VALUES (0, -564)
    INSERT INTO cast_float_test (k, float_clmn) VALUES (1, 3543.45654297)
2. SUM(CAST(float as double)): SELECT sum(cast(float_clmn as double)) FROM cast_float_test
    Expected result: 2979.4565429688. Actual result: 2979.45654296875
3. AVG(CAST(float as double)): SELECT avg(cast(float_clmn as double)) FROM cast_float_test
    Expected result: 1489.7282714844] Actual result: 1489.728271484375
4. MAX(CAST(float as double)): SELECT max(cast(float_clmn as double)) FROM cast_float_test
    Expected result: 3543.4565429688. Actual result: 3543.45654296875
5. CAST(float as double): SELECT cast(float_clmn as double) FROM cast_float_test WHERE k=1
    Expected result: 3543.4565429688. Actual result: 3543.45654296875

Senario 2: **int**
1 Create and pre-fill table:
CREATE TABLE cast_int_test (k int PRIMARY KEY, int_clmn int
INSERT INTO cast_int_test (k, int_clmn) VALUES (0, 0)
INSERT INTO cast_int_test (k, int_clmn) VALUES (1, 32767)
INSERT INTO cast_int_test (k, int_clmn) VALUES (2, -32767)
INSERT INTO cast_int_test (k, int_clmn) VALUES (3, -12876)

2. AVG(CAST(int as float)): SELECT avg(cast(int_clmn as **float**)) FROM cast_int_test
Expected result: -2044.4000244141. Actual result: -2044.4000244140625

3. AVG(CAST(int as double)): SELECT avg(cast(int_clmn as **double**)) FROM cast_int_test
    Expected result: -2044.4. Actual result: -2044.400000000000091

Senario 3: **varint**
1. Create and pre-fill table:
    CREATE TABLE IF NOT EXISTS cast_varint_test (k int PRIMARY KEY, varint_clmn varint
   INSERT INTO cast_varint_test (k, varint_clmn) VALUES (0, 32767456456456456456545678943512357658768763546575675)
   INSERT INTO cast_varint_test (k, varint_clmn) VALUES (1, -32767456456456456456545678943512357658768769876743674)
   INSERT INTO cast_varint_test (k, varint_clmn) VALUES (2, 4258)

2. CAST(varint as double): SELECT cast(varint_clmn as double) FROM cast_varint_test WHERE k=0
    Expected result: 3.27674564565e+52. Actual result: 3.27674564564565e+52

Scenario 4: **decimal**
1. CREATE TABLE IF NOT EXISTS cast_decimal_test (k int PRIMARY KEY, decimal_clmn decimal
    INSERT INTO cast_decimal_test (k, decimal_clmn) VALUES (0, 76571.345)
    INSERT INTO cast_decimal_test (k, decimal_clmn) VALUES (1, -254.256987)
2. CAST(AVG(decimal) as double): SELECT cast(avg(decimal_clmn) as double) FROM cast_decimal_test
   Expected result: 38158.544006500000251. Actual result: 38158.544005999996443
3. CAST(AVG(decimal) as float): SELECT cast(avg(decimal_clmn) as float) FROM cast_decimal_test
   Expected result: 38158.54296875. Actual result: 38158.546875
4 CAST(decimal as double): SELECT cast(decimal_clmn as double) FROM cast_decimal_test WHERE k=0
   Expected result: 76571.345. Actual result: 76571.345000000001164
5. CAST(SUM(decimal) as float): SELECT cast(sum(decimal_clmn) as float) FROM cast_decimal_test
   Expected result: 76317.0859375. Actual result: 76317.09375

**Comment by avikivity** [comment]
`float_precision` is interpreted in cqlsh, so Scylla can't have any effect on it.

**Comment by hagrid-the-developer** [comment]
The differences between the results are very small, it is probably issue with rounding, not with the calculations. I think when we calculate with floating points we cannot expect exactly the same results (especially if we support more platforms like x86 and ARM). In theory results can even differ within x86 because compiler can use AVX or FMA instructions.

**Comment by hagrid-the-developer** [comment]
It seems scylla under x86 contains some FMA instructions:

    $ objdump -D build/release/scylla | grep fma /tmp/scylla.S | wc -l
    126

**Comment by avikivity** [comment]
Unlikely, fma is a recent addition and we don't build with that ISA extension enabled. 

You probably found some symbol or instruction with the string "fma" in it.

**Comment by hagrid-the-developer** [comment]
I understand your scepticism but they are really there:

    ...
    178ed70a:   0f 0f 00 a4             pfmax  (%rax),%mm0
    18e84af9:   c4 02 8d b6 08          vfmaddsub231pd (%r8),%ymm14,%ymm9
    18f02b24:   c4 02 f5 b9 23          vfmadd231sd (%r11),%xmm1,%xmm12
    19188f80:   62 22 05 00 b9 01       vfmadd231ss (%rcx),%xmm31,%xmm24
    19298223:   c4 02 4d a9 2a          vfmadd213ss (%r10),%xmm6,%xmm13
    192a35de:   c4 02 f5 96 6d 00       vfmaddsub132pd 0x0(%r13),%ymm1,%ymm13
    19a61084:   62 92 95 05 a6 03       vfmaddsub213pd (%r11),%xmm29,%xmm0{%k5}
    19c9e940:   62                      v4fmaddps (bad),%xmm12,%xmm30{%k4}{z}
    1a75ca20:   c4                      vfmaddsd (bad),%xmm0,(%r8),%xmm7,%xmm15
    1abb5a8e:   c4                      vfmaddsubps (bad),%ymm15,0x0(%r10),%ymm8,%ymm15
    1ac45a82:   c4                      vfmaddsubps (bad),%ymm4,-0x69ccfc00(%r11),%ymm10,%ymm8
    1b3cd8ce:   c4                      vfmaddsubps (bad),%xmm0,(%rcx),%xmm15,%xmm2
    1c2f7a64:   c4 02 85 b8 67 00       vfmadd231pd 0x0(%r15),%ymm15,%ymm12
    1c554940:   c4 02 75 96 a6 01 2a    vfmaddsub132ps -0x77fdd5ff(%r14),%ymm1,%ymm12
    1cc42d86:   c4                      vfmaddpd (bad),%ymm7,0x0(%r14),%ymm2,%ymm13
    1d9ee3f5:   c4 03 51 6b 27 00       vfmaddsd %xmm0,(%r15),%xmm5,%xmm12
    ...

**Comment by avikivity** [comment]
Those are just random instructions. You used objdump -D, which disassembles non-text sections. Notice how they don't even decode correctly (`(bad)`)

**Comment by hagrid-the-developer** [comment]
You are right @avikivity , objdump -d doesn't find fma instructions...

**Comment by hagrid-the-developer** [comment]
Scenario 1:

It seems that parameter `DOUBLE_PRECISION` must be set for precisions of doubles. I got expected results for scylla, cqlsh 3.11.1 and following `~/.cassandra/cqlshrc`:

    [ui]
    float_precision = 10
    double_precision = 10

Scenario 2:

(0+32767-32767-12876)/4 = -3219

So probably wrong example is provided?

Scenario 3:

Issue with conversion X -> double -> Decimal as in https://github.com/scylladb/scylla/issues/3110 .

Scenario 4:

I got 38158.544006 for 2 and expected results for 3 and 4. With C* 3.11.1 I got 38158.544007 :-) for 2 and expected results for the rest. It seems that C* (or Java) uses some kind of Narrowing Primitive Conversion for conversion Decimal -> float/double and Scylla uses conversion: Decimal -> rational number (boost::multiprecision::cpp_rational) -> float/double. I thought that such conversion would provide the most precise results and was quite easy to implement.

**Comment by hagrid-the-developer** [comment]
Scenario 4:
I tried to study conversion BigDecimal -> double for various Java implementations and there are a lot of differences. It looks to me that we can stay with the implementation we have now, C* results will differ for different Java engines.

Examples of implementations:

* GWT Servlet: BigDecimal -> String -> double:
    http://grepcode.com/file/repo1.maven.org/maven2/com.google.gwt/gwt-servlet/2.7.0/java/math/BigDecimal.java#BigDecimal.doubleValue%28%29

* OpenJDK:
   (x / 10^y) for values that fits into double, BigDecimal -> string -> double otherwise:
   http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/java/math/BigDecimal.java#BigDecimal.doubleValue%28%29

* Android:
   The most complicated and sophisticated I have found :-)
    http://grepcode.com/file/repo1.maven.org/maven2/org.robolectric/android-all/5.0.0_r2-robolectric-1/java/math/BigDecimal.java#BigDecimal.doubleValue%28%29

So different versions of Java aren't coinsistent with each other.

**Comment by slivne** [comment]
@juliayakovlev / @roydahan 

Scenario 1, Scenario 2 - can you provide your feedback

**Comment by juliayakovlev** [comment]
Scenario 2:
Sorry, I missed one insert:
INSERT INTO cast_int_test (k, int_clmn) VALUES (4, 2654) ;
If you add it to the others - you will receive the difference between Scylla and Cassandra

**Comment by juliayakovlev** [comment]
Scenario 1:
I perform a few  additional tests (now with CQL is compatible with version 3.3.2).
I tested with different float_precision/double_precision  values: default / 10 / 15
In all cases I received correct results in the Scylla, compatible with Cassandra.
In case the parameters are not defined, I receive 5 decimal numbers for both Scylla and Cassandra.
So this scenario is OK from my point of view (if I won't find something else). I'll correct expected results. 
All tests will be performed with default float_precision/double_precision.
@roydahan  please approve

**Comment by hagrid-the-developer** [comment]
@juliayakovlev Thanks. In such case, scenario 2 is the same as scenario 1. The number of printed decimal numbers depends on `FLOAT_PRECISION` and `DOUBLE_PRCISION` from `~/.cassandra/cqlshrc` and C* and S* behaves the same, is it correct?

**Comment by hagrid-the-developer** [comment]
So for the summary:
Scenario 4: We use a different algorithm from Java, but various Java implementations use different algorithms as well. And it seems that final results for our implementation don't vary too much, so I think it is not worth to try to change our implementation.

Scenario 3: 

Issue with conversion X -> double -> Decimal that is covered by #3110 .

Scenario 1 & 2:
It seems that we work exactly the same as C*.

**Comment by slivne** [comment]
@avikivity  /  @tzach seems dependent on the decision of not reimplementing java code .... and excepting the implementation we have.

**Comment by slivne** [comment]
based on https://github.com/scylladb/scylla/issues/3109 closing
