### ISSUE TITLE
Materialized view does not work on Production environment.

### ISSUE THREAD

**Issue by BhattiMarry** [scylladb/scylla#3114]
I have a scylla cluster of 2 nodes running in production mode. I have set

`developer_mode=false`

`experimental=true` in scylla config file. However the system is up but i am getting errors on creating `materialized view`. Here is the error.

> cqlsh:test> CREATE MATERIALIZED VIEW alltimehigh AS
        ...        SELECT user FROM scores
        ...        WHERE game IS NOT NULL AND score IS NOT NULL AND user IS NOT NULL AND year IS NOT NULL AND month IS NOT NULL AND day IS NOT NULL
        ...        PRIMARY KEY (game, score, user, year, month, day)
        ...        WITH CLUSTERING ORDER BY (score desc);
InvalidRequest: Error from server: code=2200 [Invalid query] message="Can't create materialized views until the whole cluster has been upgraded"

Is this something missing from configuration or Scylla does not support these features for production environment.

**Comment by duarten** [comment]
You need to ensure that: both nodes are running the same version, `experimental=true` is set on both nodes, and that enough time has passed that they have detected they both support the feature.

**Comment by BhattiMarry** [comment]
Yes everything was same but i forgot to configure the `endpoint_snitch` option in both of the nodes.

Thank you for your reply. Closing it now.

**Comment by robdefeo** [comment]
@EmMerry How did you configure `endpoint_snitch`? I have it set to `SimpleSnitch` and it is giving me the same error you had.
