### ISSUE TITLE
Link command fail during drop table cause transport shutdown

### ISSUE THREAD

**Issue by frank8989** [scylladb/scylla#3117]
*Installation details*
Scylla version (or git commit hash): 1.7.5
Cluster size: 3 
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS Linux release 7.2.1511 (Core)

1.Drop a table in cqlsh, at the same time, write data into another table.
2. Find in the log:
 Jan 02 23:39:28  kernel: type=1702 audit(1514907568.425:5): op=linkat ppid=1 pid=127005 auid=4294967295 uid=1001 gid=1001 euid=1001 suid=1001 fsuid=1001 egid=1001 sgid=1001 fsgid=1001 tty=(none) ses=4294967295 comm="scylla" exe="/usr/bin/scylla" res=0
Jan 02 23:39:28 kernel: type=1302 audit(1514907568.425:6): item=0 name="/data/scylla/data/bluecat/device_features_20171224-7823e300e97611e7bcb7000000000015/bluecat-device_features_20171224-ka-6003-Summary.db" inode=8596043576 dev=fd:00 mode=0100644 ouid=0 ogid=0 rdev=00:00 objtype=NORMAL

Jan 02 23:39:28  scylla[126940]:  [shard 11] storage_service - Shutting down communications due to I/O errors until operator intervention
Jan 02 23:39:28  scylla[126940]:  [shard 0] storage_service - Stop transport: starts
Jan 02 23:39:28 scylla[126940]:  [shard 0] gossip - My status = NORMAL
Jan 02 23:39:28  scylla[126940]:  [shard 0] gossip - Announcing shutdown

The node's transport is closed because of the link command failed. But there is no detailed error reported. This drop command failure cause the node useless even in monitor, that node is ok. 

Can scylla record the real error in the log, thus we know why the link fail?

Thanks,
Frank

**Comment by tgrabiec** [comment]
Can you attach Scylla log from before `Jan 02 23:39:28`, which surely includes all events after drop was initiated? 

Why do you think the link command failed?

**Comment by frank8989** [comment]
Jan 02 23:39:02  scylla[126940]:  [shard 8] compaction - Compacting [/data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-3928-Data.db:level=0, /data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-3872-Data.db:level=0, /data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-4040-Data.db:level=0, /data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-3984-Data.db:level=0, ]
Jan 02 23:39:02  scylla[126940]:  [shard 48] compaction - Compacting [/data/scylla/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-13264-Data.db:level=0, /data/scylla/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-13208-Data.db:level=0, /data/scylla/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-13152-Data.db:level=0, /data/scylla/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-13096-Data.db:level=0, ]
Jan 02 23:39:03  scylla[126940]:  [shard 48] compaction - Compacting [/data/scylla/data/system/schema_columnfamilies-45f5b36024bc3f83a3631034ea4fa697/system-schema_columnfamilies-ka-13264-Data.db:level=0, /data/scylla/data/system/schema_columnfamilies-45f5b36024bc3f83a3631034ea4fa697/system-schema_columnfamilies-ka-13208-Data.db:level=0, /data/scylla/data/system/schema_columnfamilies-45f5b36024bc3f83a3631034ea4fa697/system-schema_columnfamilies-ka-13152-Data.db:level=0, /data/scylla/data/system/schema_columnfamilies-45f5b36024bc3f83a3631034ea4fa697/system-schema_columnfamilies-ka-13096-Data.db:level=0, ]
Jan 02 23:39:03  scylla[126940]:  [shard 48] compaction - Compacted 4 sstables to [/data/scylla/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-13320-Data.db:level=0, ]. 31517 bytes to 30646 (~97% of original) in 261ms = 0.111978MB/s. ~1024 total partitions merged to 1.
Jan 02 23:39:03  scylla[126940]:  [shard 48] compaction - Compacted 4 sstables to [/data/scylla/data/system/schema_columnfamilies-45f5b36024bc3f83a3631034ea4fa697/system-schema_columnfamilies-ka-13320-Data.db:level=0, ]. 81087 bytes to 78832 (~97% of original) in 252ms = 0.298334MB/s. ~1024 total partitions merged to 1.
Jan 02 23:39:03  scylla[126940]:  [shard 33] schema_tables - Dropping bluecat.device_features_20171224 id=7823e300-e976-11e7-bcb7-000000000015 version=e4b3ded8-7ec9-36e2-8679-07dce485421a
Jan 02 23:39:07  scylla[126940]:  [shard 20] compaction - Compacted 4 sstables to [/data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-6516-Data.db:level=0, ]. 677017150 bytes to 635357083 (~93% of original) in 84220ms = 7.19453MB/s. ~809600 total partitions merged to 808792.
Jan 02 23:39:07  scylla[126940]:  [shard 48] compaction - Compacting [/data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-3912-Data.db:level=0, /data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-3968-Data.db:level=0, /data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-4080-Data.db:level=0, /data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-4024-Data.db:level=0, ]
Jan 02 23:39:15  scylla[126940]:  [shard 55] compaction - Compacted 4 sstables to [/data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-4703-Data.db:level=0, ]. 771652189 bytes to 725569537 (~94% of original) in 81612ms = 8.47862MB/s. ~920704 total partitions merged to 919929.
Jan 02 23:39:15  scylla[126940]:  [shard 55] compaction - Compacting [/data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-3863-Data.db:level=0, /data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-4423-Data.db:level=0, /data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-4143-Data.db:level=0, /data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-4703-Data.db:level=0, ]
Jan 02 23:39:17  scylla[126940]:  [shard 12] compaction - Compacting [/data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-3652-Data.db:level=0, /data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-3596-Data.db:level=0, /data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-3764-Data.db:level=0, /data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-3708-Data.db:level=0, ]
Jan 02 23:39:19  kernel: i40e 0000:01:00.0: TX driver issue detected, PF reset issued
Jan 02 23:39:20  scylla[126940]:  [shard 42] compaction - Compacted 4 sstables to [/data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-4130-Data.db:level=0, ]. 873046292 bytes to 819945274 (~93% of original) in 49712ms = 15.7298MB/s. ~1041280 total partitions merged to 1040477.
Jan 02 23:39:20  kernel: i40e 0000:01:00.0: i40e_ptp_init: added PHC on eth0
Jan 02 23:39:20  kernel: i40e 0000:01:00.0: enabling bridge mode: VEPA
Jan 02 23:39:20  kernel: i40e 0000:01:00.0 eth0: NIC Link is Up 10 Gbps Full Duplex, Flow Control: None
Jan 02 23:39:20  scylla[126940]:  [shard 10] compaction - Compacting [/data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-3650-Data.db:level=0, /data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-3594-Data.db:level=0, /data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-3762-Data.db:level=0, /data/scylla/data/bluecat/device_features_20171231-2ba47ab0efb811e792ed000000000035/bluecat-device_features_20171231-ka-3706-Data.db:level=0, ]
Jan 02 23:39:23  kernel: i40e 0000:01:00.0: TX driver issue detected, PF reset issued
Jan 02 23:39:23  scylla[126940]:  [shard 38] compaction - Compacted 4 sstables to [/data/scylla/data/bluecat/device_features_20171230-53846c80efc611e79744000000000006/bluecat-device_features_20171230-ka-2950-Data.db:level=0, ]. 590003084 bytes to 553663051 (~93% of original) in 69504ms = 7.59689MB/s. ~705792 total partitions merged to 704992.



Before logs are related to compaction. During the drop command, we were writing data into Scylla.


Because storage_service shutdown commuications due to I/O errors, there is a line ：
kernel: type=1702 audit(1514907568.425:5): op=linkat ppid=1 pid=127005 auid=4294967295 uid=1001 gid=1001 euid=1001 suid=1001 fsuid=1001 egid=1001 sgid=1001 fsgid=1001 tty=(none) ses=4294967295 comm="scylla" exe="/usr/bin/scylla" res=0

storage_service - Shutting down communications due to I/O errors until operator intervention

I had the same error before during I create snapshot. It also reported linkat command. So I think it's link command problems.

**Comment by pdziepak** [comment]
Looks like `sysctl fs.protected_hardlinks` is enabled which makes the kernel prevent users from creating links to files that they do not own or do not have read and write access to. This is exactly what is happening here since, as can be seen in the logs, the sstable file is owned by the root and has permissions set to 644 while the Scylla process is running with uid=1001.

This is most likely not a Scylla bug. Situation like this could happen if some sstables were moved manually or created by a Scylla process that was run with the root privileges. The simplest solution seem to be changind the owner of sstable files to uid=1001.

**Comment by avikivity** [comment]
Agree it's not a Scylla bug, but we could be friendlier by refusing to start if we don't own all files and directories we load, and have rwx permissions on directories and r on files.

**Comment by frank8989** [comment]
I came across this issue again. I finally find it's related to sstabledump command.  I used sstabledump to dump the data file before, obviously, that summary file ower/group id had been changed from scylla(1001) to root. Then create link command failed because of the permission and thus cause the service stopped.

How sstabledump command will cause this? I run it use with sudo.

Feb 06 20:01:34 kernel: type=1702 audit(1517918494.026:7): op=linkat ppid=1 pid=163250 auid=4294967295 uid=1001 gid=1001 euid=1001 suid=1001 fsuid=1001 egid=1001 sgid=1001 fsgid=1001 tty=(none) ses=4294967295 comm="scylla" exe="/usr/bin/scylla" res=0
Feb 06 20:01:34  kernel: type=1302 audit(1517918494.026:8): item=0 name="/data/scylla/data/test1/device_features_20180131-dbc1a930076a11e883ce000000000019/test1-device_features_20180131-ka-9135-Summary.db" inode=8596038660 dev=fd:00 mode=0100644 ouid=0 ogid=0 rdev=00:00 objtype=NORMAL
Feb 06 20:01:34  scylla[163220]:  [shard 7] storage_service - Shutting down communications due to I/O errors until operator intervention
Feb 06 20:01:34 scylla[163220]:  [shard 0] storage_service - Stop transport: starts
Feb 06 20:01:34  scylla[163220]:  [shard 15] migration_manager - Failed to update definitions from 172.22.4.34:36: storage_io_error (Storage I/O error: 1: Operation not permitted)

Feb 05 17:05:26  sudo[60654]:   hadoop : TTY=pts/0 ; PWD=/data/scylla/data ; USER=root ; COMMAND=/bin/sstabledump test1/device_features_20180131-dbc1a930076a11e883ce000000000019/test1-device_features_20180131-ka-9135-Data.db
Feb 05 17:05:42  bash[60839]: user=hadoop,ppid=58988,from=172.25.0.9 41497 22,pwd=/data/scylla/data,command:20180205-170526:sudo sstabledump test1/device_features_20180131-dbc1a930076a11e883ce000000000019/test1-device_features_20180131-ka-9135-Data.db
Feb 05 17:05:44  bash[60843]: user=hadoop,ppid=58988,from=172.25.0.9 41497 22,pwd=/data/scylla/data,command:20180205-170526:sudo sstabledump test1/device_features_20180131-dbc1a930076a11e883ce000000000019/test1-device_features_20180131-ka-9135-Data.db

172.22.4.33:hadoop@:/data/scylla/data]$ sudo stat test1/device_features_20180131-dbc1a930076a11e883ce000000000019/test1-device_features_20180131-ka-9135-Summary.db
  File: ‘test1/device_features_20180131-dbc1a930076a11e883ce000000000019/test1-device_features_20180131-ka-9135-Summary.db’
  Size: 163051          Blocks: 320        IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 8596038660  Links: 1
Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-02-05 17:06:41.096817448 +0800
Modify: 2018-02-05 17:05:37.521685282 +0800
Change: 2018-02-05 17:05:37.521685282 +0800
 Birth: -

172.22.4.33:hadoop@:/data/scylla/data]$ sudo ls -al test1/device_features_20180131-dbc1a930076a11e883ce000000000019/test1-device_features_20180131-ka-9135-Summary.db
-rw-r--r-- 1 root root 163051 Feb  5 17:05 test1/device_features_20180131-dbc1a930076a11e883ce000000000019/test1-device_features_20180131-ka-9135-Summary.db

**Comment by slivne** [comment]
@frank8989 - I think you hit https://github.com/scylladb/scylla-tools-java/issues/26 - we need to fix it.
