### ISSUE TITLE
Server-side generated timestamps are not monotinically increasing on subsequent requests on the same Client connection

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#3118]
*Installation details*
Scylla version (or git commit hash): e29b598c5f336207cef9c395e1ac733d97462bfe

*Description*
The current code doesn't ensure that if Req1 arrived after Req2 on a particular connection then Req1 is going to use a time stamp older than the one of Req2. 

This may lead to a very unexpected behavior like data reviving or data loss.

**Comment by nyh** [comment]
I think your bug report is missing some context... If the timestamps come from the client, he's very well allowed to give an older mutation after a new one. So you're talking about server-side timestamp generation?

**Comment by vladzcloudius** [comment]
@nyh Right. I updated the issue name. Thanks.
