### ISSUE TITLE
Binding named statement parameters out of order results in a marshalling error.

### ISSUE THREAD

**Issue by homer6** [scylladb/scylla#3122]
*Installation details*
Scylla version (or git commit hash): 2.0.2-0.20171130.07b039f
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16

Using the datastax c client (libcassandra.so.2.5.0), binding a statement parameter out of order results in a marshalling error (see: `cass_statement_bind_string_by_name`).

I didn't test whether it was out of order versus the schema or the statement string (insert statement), but I was definitely able to reproduce it in several instances. Binding in an order that matched the insert statement resolved the marshalling error.

This was code that was working under Cassandra. I only noticed it when I migrated to Scylla. It seems logical that you would be able to bind in any order, given that the function `cass_statement_bind_string_by_name` exists in the first place, but the workaround was minimal.

**Comment by slivne** [comment]
can you please capture a wireshark sample with a sample (starting from setting up the connections), so we can analyze this.

If possible please make the connection noncompressed - its easier to analyze this.

**Comment by slivne** [comment]
closing this issue - if there will be additional information we can reopen
