### ISSUE TITLE
partition_snapshot_reader exception safety

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3123]
*Installation details*
Scylla version (or git commit hash): master

I think that there are some exception safety gaps in `partition_snapshot_reader`. For example, in `read_static_row()`, we change `_last_entry` before creating the `mutation_fragment`, which can result in `bad_alloc`; we shouldn't even set it before calling `emplace_mutation_fragment()`, which too may throw. Similarly for the actual clustering rows.

**Comment by tgrabiec** [comment]
We should test it using allocation failure injection, like in `test_exception_safety_of_reads` in row_cache_test.cc
