### ISSUE TITLE
Scylla prints warning when using --version

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#3124]
Version 2.1

When running scylla --version, we expect to get the version and that the process would exit.
Now there are additional warnings.
ARN  2018-01-09 12:53:41,475 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE

In centos:
Reactor stalled for 0 ms on shard 0.

**Comment by tzach** [comment]
I notice the same issue on all distros (centos, ubuntu 16)

**Comment by slivne** [comment]
@argenet can you try and move the printout of the scylla_version earlier (before calling run_deprecated) - I think that should solve it.
