### ISSUE TITLE
Invalid use of incomplete type struct std::hash under g++ 5.3

### ISSUE THREAD

**Issue by baiwfg2** [scylladb/scylla#3127]
*Installation details*
Scylla version (or git commit hash):fe788e0a5de38f26a2b3e03f69c7097d1124d7e3
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

./utils/hash.hh:40:30: error: invalid use of incomplete type ‘struct std::hash<auth::resource_kind>’
         return std::hash<T>()(t);
                              ^
In file included from /opt/scylladb/include/c++/5.3.1/bits/basic_string.h:5473:0,
                 from /opt/scylladb/include/c++/5.3.1/string:52,
                 from /opt/scylladb/include/c++/5.3.1/stdexcept:39,
                 from /opt/scylladb/include/c++/5.3.1/experimental/optional:44,
                 from ./auth/role_manager.hh:24,
                 from ./auth/standard_role_manager.hh:24,
                 from auth/standard_role_manager.cc:22:

Should hash for auth::resource_kind be specialized ?

**Comment by duarten** [comment]
That's https://gcc.gnu.org/bugzilla/show_bug.cgi?id=60970. You should update your compiler to gcc 7.x.

**Comment by baiwfg2** [comment]
@duarten Must compiler version not be less than gcc 7.x ? I use 5.3 to compile scylla-2.1.rc1, compile error is:

> FAILED: g++ -MD -MT build/debug/http/transformers.o -MF build/debug/http/transformers.o.d -fsanitize=address -fsanitize=leak -fsanitize=undefined -fno-sanitize=vptr -DASAN_ENABLED -O0 -DDEBUG -DDEBUG_SHARED_PTR -DDEFAULT_ALLOCATOR -DSEASTAR_THREAD_STACK_GUARDS -DNO_EXCEPTION_HACK -I/data/scylla-src/seastar/build/debug/gen -I/data/scylla-src/seastar/build/debug/c-ares -std=gnu++1y -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden  -pthread -I/data/scylla-src/seastar -U_FORTIFY_SOURCE  -march=nehalem -I/data/scylla-src/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-overloaded-virtual -Wno-maybe-uninitialized -Wno-sign-compare -Wno-error=cpp -DFMT_HEADER_ONLY -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_LZ4_COMPRESS_DEFAULT -c -o build/debug/http/transformers.o http/transformers.cc
> http/transformers.cc: In member function ‘virtual seastar::output_stream<char> seastar::httpd::content_replace::transform(std::unique_ptr<seastar::httpd::request>, const sstring&, seastar::output_stream<char>&&)’:
> http/transformers.cc:205:112: error: converting to ‘std::tuple<seastar::basic_sstring<char, unsigned int, 15u>, seastar::basic_sstring<char, unsigned int, 15u> >’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = const char (&)[9]; _U2 = seastar::basic_sstring<char, unsigned int, 15u>&; <template-parameter-2-3> = void; _T1 = seastar::basic_sstring<char, unsigned int, 15u>; _T2 = seastar::basic_sstring<char, unsigned int, 15u>]’
>      return output_stream<char>(content_replace_data_sink(std::move(s), {{"Protocol", protocol}, {"Host", host}}), 32000, true);
>                                                                                                                 ^
> http/transformers.cc:205:112: error: converting to ‘std::tuple<seastar::basic_sstring<char, unsigned int, 15u>, seastar::basic_sstring<char, unsigned int, 15u> >’ from initializer list would use explicit constructor ‘constexpr std::tuple<_T1, _T2>::tuple(_U1&&, _U2&&) [with _U1 = const char (&)[5]; _U2 = seastar::basic_sstring<char, unsigned int, 15u>&; <template-parameter-2-3> = void; _T1 = seastar::basic_sstring<char, unsigned int, 15u>; _T2 = seastar::basic_sstring<char, unsigned int, 15u>]’
> ninja: build stopped: subcommand failed.
> ninja: build stopped: subcommand failed.

Then I change to g++ 6.1, then it shows:

> /opt/scylladb/include/boost/multiprecision/cpp_int.hpp: At global scope:
> /opt/scylladb/include/boost/multiprecision/cpp_int.hpp:181:56: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
>     BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
>                                                      ~~~^~~~~~~~~~~~~~~~~~
> /opt/scylladb/include/boost/multiprecision/cpp_int.hpp:404:56: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
>     BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
>                                                      ~~~^~~~~~~~~~~~~~~~~~
> /opt/scylladb/include/boost/multiprecision/cpp_int.hpp:556:56: error: right operand of shift expression ‘(1u << 63u)’ is >= than the precision of the left operand [-fpermissive]
>     BOOST_STATIC_CONSTANT(limb_type, sign_bit_mask = 1u << (limb_bits - 1));
>                                                      ~~~^~~~~~~~~~~~~~~~~~
> ninja: build stopped: subcommand failed.

These are packages I used for compiling:

> scylla-boost-iostreams-1.58.0-11.el7.centos.x86_64
> scylla-gcc-5.3.1-2.el7.centos.x86_64
> scylla-jmx-2.0.0-20170930.e9c546a.el7.centos.noarch
> scylla-env-1.0-1.el7.centos.noarch
> scylla-boost-thread-1.58.0-11.el7.centos.x86_64
> scylla-boost-test-1.58.0-11.el7.centos.x86_64
> scylla-libstdc++-5.3.1-2.el7.centos.x86_64
> scylla-libasan-5.3.1-2.el7.centos.x86_64
> scylla-binutils-2.25-15.el7.centos.x86_64
> scylla-boost-graph-1.58.0-11.el7.centos.x86_64
> scylla-boost-random-1.58.0-11.el7.centos.x86_64
> scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
> scylla-boost-math-1.58.0-11.el7.centos.x86_64
> scylla-boost-devel-1.58.0-11.el7.centos.x86_64
> scylla-cpp-5.3.1-2.el7.centos.x86_64
> scylla-gcc-c++-5.3.1-2.el7.centos.x86_64
> scylla-ninja-build-1.6.0-2.el7.centos.x86_64
> scylla-kernel-conf-2.0.0-0.20170929.e265c91.el7.centos.x86_64
> scylla-boost-system-1.58.0-11.el7.centos.x86_64
> scylla-boost-date-time-1.58.0-11.el7.centos.x86_64
> scylla-boost-wave-1.58.0-11.el7.centos.x86_64
> scylla-conf-2.0.0-0.20170929.e265c91.el7.centos.x86_64
> scylla-boost-timer-1.58.0-11.el7.centos.x86_64
> scylla-boost-atomic-1.58.0-11.el7.centos.x86_64
> scylla-boost-python-1.58.0-11.el7.centos.x86_64
> scylla-boost-container-1.58.0-11.el7.centos.x86_64
> scylla-libgcc-5.3.1-2.el7.centos.x86_64
> scylla-libstdc++-devel-5.3.1-2.el7.centos.x86_64
> scylla-libubsan-5.3.1-2.el7.centos.x86_64
> scylla-tools-2.0.0-20170930.81c4784.el7.centos.noarch
> scylla-antlr3-tool-3.5.2-1.el7.centos.noarch
> scylla-boost-chrono-1.58.0-11.el7.centos.x86_64
> scylla-boost-regex-1.58.0-11.el7.centos.x86_64
> scylla-boost-locale-1.58.0-11.el7.centos.x86_64
> scylla-boost-serialization-1.58.0-11.el7.centos.x86_64
> scylla-isl-0.14-4.el7.centos.x86_64
> scylla-libstdc++-static-5.3.1-2.el7.centos.x86_64
> scylla-tools-core-2.0.0-20170930.81c4784.el7.centos.noarch
> scylla-antlr3-C++-devel-3.5.2-1.el7.centos.x86_64
> scylla-boost-log-1.58.0-11.el7.centos.x86_64
> scylla-boost-signals-1.58.0-11.el7.centos.x86_64
> scylla-boost-1.58.0-11.el7.centos.x86_64
> scylla-libgomp-5.3.1-2.el7.centos.x86_64
> scylla-ragel-6.8-5.el7.centos.x86_64
> scylla-server-2.0.0-0.20170929.e265c91.el7.centos.x86_64
> scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64

Should I update some of them, for example, boost ?

**Comment by baiwfg2** [comment]
And any special options that I should configure when building gcc 7.x by myself ? A lot of **abi:cxx11** issues occur during compiling. The 3rd-party packages are installed by yum.

**Comment by nyh** [comment]
On Wed, Jan 17, 2018 at 5:44 AM, Lewis Chan <notifications@github.com>
wrote:

> @duarten <https://github.com/duarten> Must compiler version not be less
> than gcc 7.x ?
>

Yes... We have recently switched Scylla to rely on C++17. Only gcc 7.x
fully supports C++17.
