### ISSUE TITLE
partition_snapshot_reader is unsafe on allocating section retry

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#3133]
Looks like there are several correctness problems in `partition_snapshot_reader` (used by memtables) caused by the fact that a large portion of the logic runs inside an allocating section and is expected to be restartable.

For example:

After the static row is read optional `_last_row` is engaged. However, later pushing the row to the buffer may fail. Upon retry `_last_row` will already be engaged and static row not emitted.
https://github.com/scylladb/scylla/blob/378f2ba8e4b2c40b42b71308155c8dfcc911dc5d/partition_snapshot_reader.hh#L198-L204
https://github.com/scylladb/scylla/blob/378f2ba8e4b2c40b42b71308155c8dfcc911dc5d/partition_snapshot_reader.hh#L164-L171

`MemoryAccounter` is being called before a fragment is pushed to the buffer. This may result in duplicate accounting of mutation fragments and also requires the accounter logic to be aware of the restartable context in which it is executes.
https://github.com/scylladb/scylla/blob/378f2ba8e4b2c40b42b71308155c8dfcc911dc5d/partition_snapshot_reader.hh#L193-L196

`_range_tombstones` is stateful and `get_next()` modifies that state. If pushing the range tombstone fails it won't be emitted on the retry.
https://github.com/scylladb/scylla/blob/378f2ba8e4b2c40b42b71308155c8dfcc911dc5d/partition_snapshot_reader.hh#L175

Considering how many fixes were already submitted for similar problems in cache and how easy it is to miss these issues when writing or reviewing code I think that the real culprit here are the allocating sections themselves and the fact that they require restartable code, something that humans are apparently not very good at writing.

A relatively simple solution (that would not require redesigning how we handle memory) would be to make entering allocating sections much cheaper (e.g. by splitting the reserving part and the "disable reclaim + check if iterators" are still valid part) so that we can reduce the amount of logic that runs inside them and try to remove as many side effects as possible.

**Comment by duarten** [comment]
Refs #3123.
