### ISSUE TITLE
export database layer statistics in terms of rows, not (only) partitions

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#3146]
Since 2.0, our cache metrics are available in number of rows (missed, hit, etc) and also partitions. But the number of requests , the database reads/writes, etc, are only available in partitions. We should export the database metrics in terms of rows as well.

We've been asked many times "how come I have 200 requests/sec and 20k cache hits/sec?"

**Comment by slivne** [comment]
Its not clear to me which metrics you are looking to add .... the total
requests is composed of insert/update/select/btach - so trying to correlate
the total request to cache hits is very "hard"

Can you please clarify, is the issue with the # of returned rows in CQL
Select ?

We have CQL operations

CQL Insert / CQL Update / CQL Batch / CQL Select.

The user can get the exact number of CQL Select he did and compare that to
the cache hits/cache miss (which may be larger in case the query returned
multiple rows).

Are you looking to add a metrtic of the number of rows returned for CQL
Select ?

Please note that Cache Hits are a replica side metric while CQL Select are
a coordinator side metric (and so would be the # of rows returned), so
there is a CL factor between the two

**Comment by tgrabiec** [comment]
@glommer Those metrics are not actually in partitions either, they're in "requests". You can have a multi-partition scan which will be counted as one request on database layer.

**Comment by glommer** [comment]
@slivne the total number of requests is grouped - yes. But we have replica-side reads / writes.
What I am after here is a way to see how many rows were returned in a read (or written in a write).

If we are doing range scans, or complex requests (as @tgrabiec) pointed out, we could still count how many rows are touched by it.
