### ISSUE TITLE
query_result_builder move issues

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#3158]
Although this class is move-constructible, doing so after calling any of its non-const members will result in it blowing up in your face. The reason is that after it's `consume_new_partition()` method is called it stores references to it's own member which it doesn't update when moved, hence the references become dangling.
Proposed solution: either disallow move-construction (inconvenient) or fix (requires navigating the jungle that class is).

**Comment by avikivity** [comment]
Internal thing, not backporting.
