### ISSUE TITLE
Materialized views does not contain old data

### ISSUE THREAD

**Issue by robdefeo** [scylladb/scylla#3160]
I have been materialized views with the experimental flag, the preview [docs](http://www.scylladb.com/2017/07/27/materialized-views-preview-scylla-2-0/) states
> Currently, only new data written after the creation of a view will appear in that view. If you add a view to a table with existing data, a background process to copy that data to the new view is not yet started. The related “nodetool viewbuildstatus” command is also not supported.

What are the issues to track this feature?

**Comment by duarten** [comment]
It's #1141. Also, please ask questions over the mailing list and not using the bug tracker.
