### ISSUE TITLE
Fail to install Scylla on Debian 8 due to Java instructions issue

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#3162]
*Installation details*
Scylla version (or git commit hash): 2.0.x
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 8 on GCE

```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
```

The first step in [Java install on site](http://www.scylladb.com/download/debian8/) is
```
sudo apt-get install -t jessie-backports ca-certificates-java 
```

results:
```
$ sudo apt-get install -t jessie-backports ca-certificates-java
Reading package lists... Done
E: The value 'jessie-backports' is invalid for APT::Default-Release as such a release is not available in the sources
```

**Comment by tzach** [comment]
@syuu1228 any idea?

**Comment by syuu1228** [comment]
@tzach I couldn't reproduce this on GCE, but I think it's probably because we are missing "apt-get update" before "apt-get install".

**Comment by slivne** [comment]
@tzach ping
