### ISSUE TITLE
LIST USERS always queries with consistency level 1

### ISSUE THREAD

**Issue by hakuch** [scylladb/scylla#3165]
A note that this bug is slightly related to #2968 and also #2976. Furthermore, this bug is solved in the soon-to-be-merged roles patch series. Therefore, this issue is relevant for release branches and not necessarily for `master`.

When `LIST USERS` is executed in `cql3::statements::list_users_statement::execute`, it uses an overload of `cql3::query_processor::process` that always uses consistency level (CL) 1 despite the code indicating `db::consistency_level::QUORUM`. The quorum read is necessary because the default superuser is inserted with `CL=quorum`. As a result of this bug, it's possible that `LIST USERS` will return stale data.

\cc @glommer

**Comment by slivne** [comment]
now that 03608d269e845d39265a72a98c1eb80f3530f7c7 is merged can we close this ?

**Comment by hakuch** [comment]
It's fixed on `master`, but a dedicated patch (independent of roles stuff) needs to be prepared and sent to the mailing-list for active release branches.

**Comment by slivne** [comment]
so for 2.2 its fixed (once aster will be branched)

in 2.1 and older releases it is an open bug - is it a regression in 2.1 / older releases ?

**Comment by hakuch** [comment]
That's right. I don't know if it can be called a regression since it looks like the bug has existed since Scylla's inception.

**Comment by hakuch** [comment]
This was fixed in `master` with 741d2155160191737af6208650a8fd7a6327accb.
