### ISSUE TITLE
cell_locker: Timeout should apply across cells

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3169]
*Installation details*
Scylla version (or git commit hash): master

Currently, the cell_lock timeout is not decreased after each cell's lock is acquired, which means we may not respect it if taking all of the cell's locks surpass the timeout, but each individual lock acquisition if within it.

**Comment by pdziepak** [comment]
In that code timeout is a `db::timeout_clock::time_point` and not a duration. I don't think the problem you described can happen.

**Comment by duarten** [comment]
Oh! I didn't notice that; closing.
