### ISSUE TITLE
Spark testing 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#317]
Using https://github.com/datastax/spark-cassandra-connector

verify that scylla works with spark

**Comment by cleaton** [comment]
What's the current status for the spark-cassandra-connector support? I've got a single node (centos 7) setup with scylla and tried connecting to with with cassandra-connector 1.5.0-m2 and 1.4.0 but no success so far. This is the error message i get for both versions:

com.datastax.driver.core.UnsupportedProtocolVersionException: [/host:port] Host /host:port does not support protocol version V4 but V4)

**Comment by pdziepak** [comment]
@cleaton This is an problem with version negotiation between Java driver 2.2.0 and Scylla (hence the strange message "version V4 unsupported, but V4 is supported"). A patch fixing this issue has been sent.

Versions 1.3.x of the connector should be unaffected (probably 1.5.0-m1 too).

**Comment by cleaton** [comment]
@pdziepak Thanks for the quick response.
Turns out IntelliJ didn't clean external libraries when I tried 1.4.0 (cassandra-driver-core 2.2.0-rc3 was still there and overrode 2.1.5 from 1.4.0). After removing it I can connect using 1.5.0-M1 and earlier versions.

Thanks!
