### ISSUE TITLE
add parameter --experimental to enable/disable experimental features for AMI instance

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3179]
Installation details
Scylla version (or git commit hash): 2.1.rc2-0.20180129.63e92418d
Cluster size: 201
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-04fcc47e

When the ami instance is created, it will automatically setup scylla and start the service. Sometimes, we don't have chance to update the scylla.yaml config to enable `experimental` before scylla service is active.

If we add a new parameter to ec2_userdata, it can help to enable experimental when we create AMI instance.

@syuu1228 @slivne @roydahan

**Comment by syuu1228** [comment]
@amoskong I think it’s totally fine to add it if you need to automate the configuration from user data parameter for testing purposes, but if you just want to prevent to run Scylla automatically, you can use —stop-services.

**Comment by tzach** [comment]
Make sense. We have a similar feature in Scylla docker for the same reason.

**Comment by amoskong** [comment]
@syuu1228 --stop-service can solve my current problem.
This request is just for UX.

**Comment by tzach** [comment]
@bentsi AFAIU this is part of latest AMI. Is it the case?

**Comment by tzach** [comment]
Answering myself **experimental** is supported in Scylla AMI user data:
```
{
"scylla_yaml": {
  "cluster_name": "my-test-cluster",
  "experimental": true
  }
}
```
