### ISSUE TITLE
build_rpm.sh causes "No matching package to install: 'yaml-cpp-static'" on Fedora 27

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#3183]
When we run build_rpm.sh **WITHOUT** --target parameter on Fedora 27 (witch means we build .rpm for Fedora 27), we get following error:
```
No matching package to install: 'yaml-cpp-static'
Not all dependencies satisfied
Error: Some packages could not be found.
```
It seems Fedora does not provides separated -static package, so we should drop the dependency on Fedora.

**Comment by avikivity** [comment]
Note that Fedora does plan to add it: https://bugzilla.redhat.com/show_bug.cgi?id=1541094

**Comment by duarten** [comment]
Btw, I tried doing `build_rpm.sh --target centos` but it failed with 

```
ERROR: Could not find required config file: /etc/mock/centos.cfg
ERROR:   If you're trying to specify a path, include the .cfg extension, e.g. -r ./target.cfg
```

**Comment by avikivity** [comment]
For plan centos, use `epel-7-x86_64`.

But Scylla needs more, use `--target dist/redhat/mock/scylla-epel-7-x86_64.cfg`, that adds the third-party repositories.

**Comment by syuu1228** [comment]
On Mon, Feb 5, 2018 at 7:48 PM, Avi Kivity <notifications@github.com> wrote:

> For plan centos, use epel-7-x86_64.
>
> But Scylla needs more, use --target dist/redhat/mock/scylla-epel-
> 7-x86_64.cfg, that adds the third-party repositories.
>

Don't need to do this, build_rpm.sh automatically specifies
mock/scylla-epel-7-x86_64.cfg when --target epel-7-x86_64.

**Comment by syuu1228** [comment]
@avikivity should we change dependency to yaml-cpp-devel on Fedora for a while, or just wait for Fedora provides -static package?

**Comment by avikivity** [comment]
Let's change it back. I think -static will only come with Fedora 28.
