### ISSUE TITLE
systemd: Unknown lvalue 'Ambient / Unknown lvalue 'AmbientCapabilities'

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3184]
*Installation details*
Scylla version (or git commit hash):  2.1.rc2-0.20180129.63e92418d
Cluster size: 200
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS
instance type: m3.medium

```
Feb 04 16:14:58 ip-172-30-0-12.ec2.internal systemd[1]: [/usr/lib/systemd/system/scylla-server.service:28] Unknown lvalue 'Ambient
Feb 04 16:16:25 ip-172-16-1-88 systemd[1]: [/usr/lib/systemd/system/scylla-server.service:28] Unknown lvalue 'AmbientCapabilities'
Feb 04 16:16:25 ip-172-16-1-88 systemd[1]: Starting Scylla Server...
```

@syuu1228

**Comment by avikivity** [comment]
What systemd do you have? Probably too old.

Anyway, it's just a warning and it should work without it.

**Comment by amoskong** [comment]
$ rpm -qa |grep systemd
systemd-python-219-19.el7_2.13.x86_64
systemd-libs-219-19.el7_2.13.x86_64
systemd-219-19.el7_2.13.x86_64
systemd-sysv-219-19.el7_2.13.x86_64

**Comment by avikivity** [comment]
Latest is `systemd-219-42.el7_4.7.x86_64`. Update systemd and the message will go away.

**Comment by amoskong** [comment]
This note is harmless, it doesn't exist with latest systemd-219-42.el7_4.7.x86_64.

Our AMI instance (base image) uses `systemd-219-19.el7_2.13.x86_64` by default, do we need to upgrade it in building ami?

**Comment by avikivity** [comment]
Yes, let's run `yum update` as part of the AMI creation process.

**Comment by syuu1228** [comment]
That can be done in scylla_install_ami, but maybe latest CentOS AMI has
updated package (there is 2018-Jan-14
version of CentOS official AMI), will check package version
https://wiki.centos.org/Cloud/AWS

**Comment by slivne** [comment]
I am not sure that calling yum update on AMI boot is a good solution- it will cause the node boot to be much slower - we have done that in the past and disabled it as far as I remember.

**Comment by avikivity** [comment]
> I am not sure that calling yum update on AMI boot is a good solution

When we create the AMI, not when we boot it.

**Comment by syuu1228** [comment]
I sent CentOS base AMI update patch, should we also block installing .rpm when systemd < 219-42, like kernel version check?
