### ISSUE TITLE
Materialized view can be truncated

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3188]
Scenario:
1. Create table:
CREATE TABLE users (username varchar, password varchar, gender varchar, session_token varchar, state varchar, birth_year bigint, PRIMARY KEY (username))
2. Create MV:
CREATE MATERIALIZED VIEW users_by_state AS SELECT * FROM users WHERE STATE IS NOT NULL AND username IS NOT NULL PRIMARY KEY (state, username)
3. Insert one record:
INSERT INTO users (state, username) VALUES ('TX', 'user1')
4. Run truncate on MV:
TRUNCATE table users_by_state

Truncate succeeded. MV is empty. Base table has the record.
I expected this statement will fail because of materialized view is immutable

**Comment by duarten** [comment]
And if you truncate the base table, I don' think the view will be truncated (this is in my to-do list).

**Comment by juliayakovlev** [comment]
I plan to add this test. Could you update me, when it will be performed, please?

**Comment by duarten** [comment]
I'll let you know :)

**Comment by juliayakovlev** [comment]
dtest: materialized_views_test.py/TestMaterializedViews#truncate_base_test
