### ISSUE TITLE
Add '--jobs' parameter to dist/debian/build_deb.sh

### ISSUE THREAD

**Issue by argenet** [scylladb/scylla#3195]
Currently, we can specify the number of jobs when building an RPM:
```
% dist/redhat/build_rpm.sh --help
build_rpm.sh --rebuild-dep --jobs 2 --target epel-7-x86_64
  --jobs  specify number of jobs
  --dist  create a public distribution rpm
  --target target distribution in mock cfg name
  --rebuild-dep  ignored (for compatibility with previous versions)
  --xtrace print command traces before executing command
```

It is not supported for building .deb though:
```
% dist/debian/build_deb.sh --help                                                                                     :(
build_deb.sh -target <codename> --dist --rebuild-dep
  --target target distribution codename
  --dist  create a public distribution package
  --no-clean  don't rebuild pbuilder tgz
```

It would be nice to support this flag for build_deb.sh too to allow for better tuning on Debian/Ubuntu.

One use case for this is Travis CI integration for Scylla. Currently it fails because there is only 8GB of RAM available which is insufficient when running the maximum amount of jobs. We could restrict this to fewer jobs and get Travis CI builds (they will still take a lot of time to complete, but that is still better than nothing).

**Comment by penberg** [comment]
The scripts have no such option as of 9388f3d626ce9f366f5fa16c2a683c419e427cc2. Furthermore, the script is replaced with a `ninja dist` target anyway.
