### ISSUE TITLE
Is there any way to recover data that is deleted by cql statement "delete * from table where ..."?

### ISSUE THREAD

**Issue by zhiguoxu** [scylladb/scylla#3197]
We have deleted some important data by mistake,  so... Is there any way to recover data that is deleted by cql statement "delete * from table where ..."?

**Comment by avikivity** [comment]
Please ask questions on the mailing list, not the bug tracker.

First, take a snapshot immediately (`nodetool snapshot`). Then, if compactions did not take place, there is a chance the data could be resurrected.
