### ISSUE TITLE
Unable to fetch programmatically (gocql) from MV after it is dropped and recreated

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#3198]
Installation details
Scylla version 2.0.2
Cluster size: 1
OS: AWS AMI ami-9509d3ed
Hardware: i3.large

This could be an issue with prepared statements not being invalidated in response to a drop materialized view command.   Everything works fine from cqlsh but after I drop a materialized view and recreate it, I can never fetch rows from it.  The rows are there in the view but I just can't fetch them using gocql.  I can fetch from either the base table or the view with cqlsh but I cannot fetch from the view with gocql.  I think Cassandra had a similar problem before and they implemented some kind of prepared statement invalidation watcher to resolve it.  

I've also attached a stand-alone test repro tool.  Here are the simple repro steps:

- create table
- create view
- insert row1 into table
- fetch row1 from view (that works, of course)
- drop view
- recreate same view
- insert row2 into table
- fetch row2 from table (that works, of course)
- fetch row2 from view (that does not work, and never starts working again)

Fetching the view row2 from cqlsh works fine.

Sample output from the tool:

```
+ Created keyspace test1
+ Created table t1
+ Created view v1
+ Inserted first row into t1
+ Fetched from v1: c2 [aee28b2e-0d72-11e8-8280-d050996434d1] c3 [86ad57b5-8269-45e4-b3b5-49856f388833]
+ Dropped view v1
+ Re-created view v1 with same schema
+ Inserted second row into t1 (c1=8cf27568-5b41-4568-8d05-8549a967525d, c4=qwer)
** [2018-02-09 00:24:46.660810317 -0800 PST m=+4.074223877] Fetching rows where c1=8cf27568-5b41-4568-8d05-8549a967525d and c4=qwer
+ Fetched successfully from table t1. c2 [b01801e6-0d72-11e8-8281-d050996434d1] c3 [168278b8-796f-4cd0-b147-2ac7392255b6]
- Unable to fetch from v1 where c1=8cf27568-5b41-4568-8d05-8549a967525d and c4=qwer. Err not found
** [2018-02-09 00:24:51.661950582 -0800 PST m=+9.075364287] Fetching rows where c1=8cf27568-5b41-4568-8d05-8549a967525d and c4=qwer
+ Fetched successfully from table t1. c2 [b01801e6-0d72-11e8-8281-d050996434d1] c3 [168278b8-796f-4cd0-b147-2ac7392255b6]
- Unable to fetch from v1 where c1=8cf27568-5b41-4568-8d05-8549a967525d and c4=qwer. Err not found
** [2018-02-09 00:24:56.66322745 -0800 PST m=+14.076641173] Fetching rows where c1=8cf27568-5b41-4568-8d05-8549a967525d and c4=qwer
+ Fetched successfully from table t1. c2 [b01801e6-0d72-11e8-8281-d050996434d1] c3 [168278b8-796f-4cd0-b147-2ac7392255b6]
- Unable to fetch from v1 where c1=8cf27568-5b41-4568-8d05-8549a967525d and c4=qwer. Err not found
...

jness@services:/tmp$ cqlsh
Connected to veraminev2 at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> use test1 ;
cqlsh:test1> select c2,c3 from v1 where c1=8cf27568-5b41-4568-8d05-8549a967525d and c4='qwer';

 c2                                   | c3
--------------------------------------+--------------------------------------
 b01801e6-0d72-11e8-8281-d050996434d1 | 168278b8-796f-4cd0-b147-2ac7392255b6

(1 rows)
```

[main_go.txt](https://github.com/scylladb/scylla/files/1710237/main_go.txt)

**Comment by slivne** [comment]
Can you try to drop the connection and query again

I expect that a non prepared query (e.g. cql text) should work

It may be an issue with invalidating prepared statememts

**Comment by veramine** [comment]
Thanks for the quick fix!  As a workaround until a release includes this fix, we will build materialized view queries using sprintf instead of bind variables.  It seems like gocql queries built up with sprintf do not re-use previously-prepared prepared statements.

**Comment by robdefeo** [comment]
Any idea what release this fix will make it into?

**Comment by slivne** [comment]
It will not be part pf 2.1.0, we will include this in 2.1.1
