### ISSUE TITLE
checked_file treats discarded pending read-aheads as errors if file descriptor is closed before they are completed

### ISSUE THREAD

**Issue by argenet** [scylladb/scylla#3218]
This has been found when researching #3213. The issue is broader than the one discovered there and may require more generic approach.

Our `file_input_stream` supports speculative execution by reading buffers ahead. In the case when some read-aheads are issued but the input stream is closed their results are discarded. For those discarded in-flights we don't really care whether they succeed or fail.
The problem happens when we use `checked_file_impl` that checks every IO operation to succeed. In this case, it may happen that we close the input_stream and the underlying `file` while there are still some pending reads on it. If the file descriptor is closed before those reads are attempted, they fail with a "Bad file descriptor" error. `checked_file_impl` will report those failures to the `io_error_handler` which may further shut down the system ("Shutting down communications due to I/O errors until operator intervention").

#3213 revealed one such case but it can happen to any scenario that involves `file_input_stream` based on a `checked_file_impl` where the stream and the file are closed before the stream is read to the end.
The worst thing about this is that this issue is intermittent by its nature as those reads may complete before the file is closed most of the times.

**Comment by duarten** [comment]
Doesn't `file_data_source_impl` wait for pending read aheads in `close()`?

**Comment by argenet** [comment]
Hmm... Indeed it does. Somehow this didn't work for me when I tried to make the file outlive the call to `input_stream.close()`. Will double check that.
