### ISSUE TITLE
License blurb in source code is inconsistent about the license

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#3225]
The license blurb in the Scylla source code looks like this:
```
/*
 * This file is part of Scylla.
 *
 * Scylla is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Scylla is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Scylla.  If not, see <http://www.gnu.org/licenses/>.
 */
```
This blurb first says that the license is **GNU Affero General Public License**, but then, repeats the name of a *different* license, **GNU General Public License**, twice. It also gives a link to some generic page on a dozen different license types, to add to the confusion.

We should fix the text to only mention "GNU Affero General Public License", and add a link to that specific license: either https://www.gnu.org/licenses/#AGPL or https://www.gnu.org/licenses/agpl.html

A related question: Do we have a script that fixes up these blurbs in all files? I can't find one in scripts/.

**Comment by avikivity** [comment]
Better to replace all those blurbs with SPDX.

**Comment by nyh** [comment]
@avikivity did exactly what he proposed four years ago - replace all those blurbs with SPDX. So closing this issue.
