### ISSUE TITLE
scylla_cpuset_setup should check for root permission

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#3228]
Like other scripts scylla_cpuset_setup should check for root permissions before
starting, and there are none it should issue the right warning

**Comment by slivne** [comment]
scylla_cpuset_setup is run from scylla_setup and ask that it will be run with privileged user - when do we ask the user to run this script directly ?

**Comment by amnonh** [comment]
I'm not sure if we ask him to run it directly, but if he does (like I did) the error he's getting is confusing

**Comment by tzach** [comment]
@amnonh why did you run it directly? what is the use case?
