### ISSUE TITLE
Observe distributed view building status

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3237]
*Installation details*
Scylla version (or git commit hash): master

There are use cases that require us to have global knowledge of the building status for a particular materialized view, namely:

1. `nodetool` command that reports the view building progress and status;
2. range movement during the view building process, such as introducing a new node;
3. node failure and subsequent removal.

Right now, view building information is present on each node, in their local system tables. 

An immediate solution is to introduce a distributed system keyspace to hold the per-node view building status. This allows querying the cluster so clients/peers can fetch the necessary data for 1. and 2., and by setting a RF > 1, this also mitigates 3. This is the approach Apache Cassandra adopted, although there are some [bugs](https://issues.apache.org/jira/browse/CASSANDRA-11098). 

We can consider some alternative approaches.

* Independent solutions: each of the use cases can have a particular solution; we can deal with 1. by querying all cluster nodes, with 2. by propagating the built ranges to the node data is streamed to, and with 3. by simply rebuilding the ranges for which we lost data.

* Augmented local system tables and gossip: each node can propagate it's local view building status to other nodes, such that each nodes knows the global view building status; this is essentially a distributed system table with RF=ALL.

**Comment by duarten** [comment]
It seems Apache Cassandra uses the distributed system table approach only to support the `nodetool` command. For range movements, it assumes (except for repair and sstable loading) that the view is built (and leaves it to the user to issue rebuilds). 

In our case, we should check during streaming whether the view is built across all base replicas responsible for the range in question. We could query just the base replica that's paired with view replica we will be paired with, but we may not have a ring snapshot at that point, and it may not be stable if we support multiple range movements. Better to be conservative and query all of them base nodes.

**Comment by dorlaor** [comment]
If it helps, we can use Scylla Manager for collecting/storing the global
view.
OTH, it is nice that every node has a global view.
In general we should have the same type of solution in place for other
similar problems

**Comment by duarten** [comment]
Yes, we already use the distributed keyspace approach for `system_trace`, so it makes sense to use that here.
