### ISSUE TITLE
we have absolutely no idea about the I/O topology at runtime

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#3238]
I found myself today wanting to correlate read timeouts with high CPU usage. This is a very common task do I do all the time: it's easy to do if num_io_queues == nr_shards.

But when many shards share an I/O queue, this is significantly harder to achieve: we need to correlate the timeouts with the specific shard that is dispatching I/O. But which shard is the I/O coordinator of a specific shard?

@avikivity  suggested we'd use environment variables to export that. I find that a bit challenging, since they are bound to a session that may or may not exist.

My personal preference is export this over REST. The disadvantage is that this is a Scylla-specific solution to a seastar problem.

Worst case, we could export over prometheus itself. The disadvantage here is that we'd be using some precious bandwidth to export something that is essentially constant every second (I wish prometheus had some native support for things that change infrequently), but the advantage is that we can use the result to compose complex queries in the monitoring.

@slivne FYI.

**Comment by amnonh** [comment]
On Tue, Feb 27, 2018 at 4:00 PM, Avi Kivity <notifications@github.com>
wrote:

> The environment variable idea doesn't work, since the /proc/pid/environ is
> not dynamic.
>
> I think we already expose it in prometheus via the ioshard label. A queue
> metric has both shard and ioshard labels, with ioshard performing the I/O
> on behalf of shard.
>
And luckily was just merged in 2017.1.5

If you look at the io queue metrics now, the shard will actually be the
owner of the queue not the shard holding the queue.

Which makes it clearer, so no need for tough corolloations.

**Comment by glommer** [comment]
I thought the ioshard parameter was the coordinator index, not the actual shard? If it is the actual shard I can work with that.

**Comment by amnonh** [comment]
On Tuesday, February 27, 2018, Glauber Costa <notifications@github.com>
wrote:

> I thought the ioshard parameter was the coordinator index, not the actual
> shard? If it is the actual shard I can work with that.
>
> These are the only metrics in the system that the shard is not the actual
> shard the code is running on.
>
so we report both, ioshard is the shard that hold the queue.

shard is the shard that own the queue.

so let's say we have four shards and two queues.

we'll have four instances of the metrics two would have the same ioshard
and the shard will be 0—3

**Comment by nyh** [comment]
On Tue, Feb 27, 2018 at 4:56 AM, Glauber Costa <notifications@github.com>
wrote:

> I found myself today wanting to correlate read timeouts with high CPU
> usage. This is a very common task do I do all the time: it's easy to do if
> num_io_queues == nr_shards.
>
> But when many shards share an I/O queue, this is significantly harder to
> achieve: we need to correlate the timeouts with the specific shard that is
> dispatching I/O. But which shard is the I/O coordinator of a specific shard?
>
> @avikivity <https://github.com/avikivity> suggested we'd use environment
> variables to export that. I find that a bit challenging, since they are
> bound to a session that may or may not exist.
>
> My personal preference is export this over REST. The disadvantage is that
> this is a Scylla-specific solution to a seastar problem.
>

Seastar is a C++ library, and as such, its solutions should be in the C++
library level, i.e., a function to inquire about the I/O queue
configuration.

In Scylla, we can use this function to report this information in various
ways - REST API, prometheus, or virtual tables.
Or, since, if I understand correctly, this setup never changes after boot,
you can just output the I/O configuration as a message to the logfile
during boot, and you can look in the log file to find this information.

> Worst case, we could export over prometheus itself. The disadvantage here
> is that we'd be using some precious bandwidth to export something that is
> essentially constant every second (I wish prometheus had some native
> support for things that change infrequently), but the advantage is that we
> can use the result to compose complex queries in the monitoring.
>
Yes, that's true. In that sense it is more convenient than manually looking
up stuff in the log file.

**Comment by glommer** [comment]
Confirmed that the `ioshard` tag does what I want.
