### ISSUE TITLE
Unneeded systemd unit files installed on Ubuntu 14.04

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#3245]
Related with #3239, we don't provide upstart scripts for scylla-fstrim and node-exporter, Ubuntu 14.04 does not able to run these services.

**Comment by syuu1228** [comment]
Found that node-exporter installs upstart script on node_exporter_install:
https://github.com/scylladb/scylla/blob/bd3517efd8f684c65ecf7dc5dd38025b0bac2002/dist/common/scripts/node_exporter_install#L55

Also realized we have implemented scylla-fstrim as a cron job on Ubuntu 14.04/Debian 8/Debian 9:
https://github.com/scylladb/scylla/blob/master/dist/debian/build_deb.sh#L158

So these are working finely on Ubuntu 14.04 without installing upstart scripts.
However, we do install unneeded systemd unit files on Ubuntu 14.04, it should be drop.

Also, on Debian 8/9, we install scylla-fstrim cron job, but also enables scylla-fstrim systemd unit.
We should drop one of them.

**Comment by syuu1228** [comment]
Created Debian 8/9 issue separately.
https://github.com/scylladb/scylla/issues/3249

**Comment by amnonh** [comment]
I've just installed 2.1 on ubuntu 14 and check that node_exporter is running.
So if i understand correctly, the problem is not that the file is missing, but that there are redundant systemd files.
@syuu1228 
Beside the housekeeping, is there any regression between the versions?

**Comment by slivne** [comment]
@syuu1228 - is the issue that node_exporter does not run at all ?

@amnonh - did you restart and verofy that node_exporter is brought up when node is restarted ?
