### ISSUE TITLE
scylla_setup --no-fstrim-setup does not disable scylla-fstrim service

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#3248]
Since we enabling scylla-fstrim.timer on "Do you want to enable ScyllaDB services?" part, --no-fstrim-setup doesn't effect, systemd runs scylla-fstrim service anyway.
To make it expected behavior, move enabling scylla-fstrim.timer code to scylla_fstrim_setup.

see: https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_setup#L294

**Comment by slivne** [comment]
@syuu1228 is this a regression ?

**Comment by slivne** [comment]
@syuu1228 ping
