### ISSUE TITLE
Debian 8/9 enables both scylla-fstrim cron job and scylla-fstrim systemd unit

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#3249]
It installs cron job:
https://github.com/scylladb/scylla/blob/master/dist/debian/build_deb.sh#L126

But it's also enables systemd unit:
https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_setup#L294

Need to drop one of them.

**Comment by slivne** [comment]
@syuu1228 is this a regression ?
