### ISSUE TITLE
CPU load metrics is broken when cache is disabled

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#3251]
*Installation details*
Scylla version (or git commit hash): 2.1-rc3 (3ab1c8ab)
Cluster size: 1

*Description*
The `scylla_reactor_utilization` metric is broken when scylla is started with `--enable-cache=0`.
The patch that broke this is somewhere between the bdbbfe9 and 3ab1c8ab hashes.

Here is how the graph looks like when we run the same test with 3ab1c8ab and bdbbfe9:

Just the "utilization graph":
![image](https://user-images.githubusercontent.com/6103981/36926605-b920e696-1e46-11e8-8e1b-9a670e722d14.png)

Some more graphs from the same run:
![image](https://user-images.githubusercontent.com/6103981/36926592-a907a93e-1e46-11e8-931b-5ac0db6f0fbf.png)

**Comment by tgrabiec** [comment]
@vladzcloudius Is the problem that load is 100%? Did you try to profile it?

**Comment by vladzcloudius** [comment]
@tgrabiec No, the problem is that it doesn't properly show the load level which *IS* 100% in this test.

**Comment by glommer** [comment]
We had a bug that looked eeringly similar to this. But I thought Raphael fixed it ?

**Comment by vladzcloudius** [comment]
@glommer I didn't check the master. Maybe the mentioned fix hasn't been backported to 2.1?

**Comment by glommer** [comment]
This is a seastar fix. Maybe you didn't update the submodules correctly when bisecting it ?

**Comment by vladzcloudius** [comment]
@glommer I didn't bisect here. Do you have a hash?

**Comment by vladzcloudius** [comment]
@glommer Yes, I did it every time as far as I remember. Let me double-check.

**Comment by vladzcloudius** [comment]
@glommer You were right. I must have forgotten to run a `git submodule update --init --recursive`. The issue doesn't reproduce with the properly aligned seastar tree.
