### ISSUE TITLE
If repair process is run on base table, the data in the MV is not fixed

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3255]
If repair process is run on base table, the data in the MV is not fixed.
Scenario:

1. Create a base table and a view on it where one of the base's non-key columns (let's call it "b") becomes a clustering key in the view table (the partition key, "a", remains the same).
N=3, RF=3. (BTW, This, and also the fact of same partition key, means each node is paired with itself).
2. Add a single base row with b=2.
3. Now killed one of the nodes (for example, node2)
4. Update the base partition setting b=3.
This should, one the two living view replicas, delete the row with clustering key b=2, and add a new row with b=3.
5. Now restore the killed node.
6. Repair base table
7. Stop other nodes (node1 and node3)
8. Now query the view from non-updated node
Result:
 - base table  include new data 
 - MV - old (not updated data) is returned

If run repair of all data (not specify the entity), the data is repaired.

Dtests for reproduce the problem (not merged yet, still in the my repo):
materialized_views_test.py/TestMaterializedViews#base_replica_repair_test

**Comment by duarten** [comment]
There are 4 dtests in materialized_views_test.py that exemplify this issue (which were inherited from Cassandra). The issue #3275, we're not activating the view write path. Closing this as a duplicate.
