### ISSUE TITLE
Kairosdb 1.2.1 is broken with Scylla 2.1.0 (feb 16 build)

### ISSUE THREAD

**Issue by lewisdiamond** [scylladb/scylla#3256]
*Installation details*
Scylla version (or git commit hash): 58b90ceee

Kairosdb + Scylladb is broken now
```
kairosdb_1   | 21:47:46.072 [main] ERROR [CassandraModule.java:136] - Unable to setup cassandra schema
kairosdb_1   | com.datastax.driver.core.exceptions.InvalidQueryException: Unknown function 'tounixtimestamp'
```
There's that too:
```
kairosdb_1   | 21:47:46.051 [main] WARN  [Schema.java:250] - Unable to perform efficient range deletes, consider upgrading to a newer version of Cassandra 
kairosdb_1   | 21:47:46.063 [main] WARN  [Schema.java:275] - Unable to perform service key list query, consider upgrading to newer version of Cassandra
```

**Comment by glommer** [comment]
Update: I talked with Mr. Lannister over slack about that, and he reports that 1.2.0 worked just fine.

So it's probably something that Kairos changed in that mean time.

**Comment by duarten** [comment]
KairosDB now has CQL support, so these are compatibility issues.

We seem to be missing the [`toUnixTimestamp ` function](https://docs.datastax.com/en/cql/3.3/cql/cql_reference/timeuuid_functions_r.html).

> Unable to perform efficient range deletes, consider upgrading to a newer version of Cassandra 

That's related to #432 (I think we're just missing the CQL layer). Relevant KairosDb code [here](https://github.com/kairosdb/kairosdb/blob/9dcbce64d47fb0b58f1439789ffb15ea8772b3a3/src/main/java/org/kairosdb/datastore/cassandra/Schema.java#L119).

> Unable to perform service key list query, consider upgrading to newer version of Cassandra

This is probably #2025. Relevant KairosDb code [here](https://github.com/kairosdb/kairosdb/blob/9dcbce64d47fb0b58f1439789ffb15ea8772b3a3/src/main/java/org/kairosdb/datastore/cassandra/Schema.java#L170).

**Comment by tomer-sandler** [comment]
Indeed we do not support ```toUnixTimestamp``` according to these tickets:
 #2915 -> #2950 (Closed) -> #2949 (open for 7 months)

**Comment by evilezh** [comment]
scylla: 2.1.3
Neither kairosdb 1.2.0 nor 1.2.1 is working with scylla. At least fresh install.

I guess this is related, I do not see exactly what it does not like, but I guess can be same thing.
```
16:39:11.345 [main] ERROR [CassandraModule.java:136] - Unable to setup cassandra schema
com.datastax.driver.core.exceptions.SyntaxError: line 1:62  : syntax error...
```

**Comment by tzach** [comment]
added an issue to track `toUnixTimestamp` #3567

**Comment by tzach** [comment]
depended on #1969 and then on #432

**Comment by tzach** [comment]
@slivne with both #1969 and #432 closed, can we close this issue as well?

**Comment by slivne** [comment]
yes you are correct ... we can
