### ISSUE TITLE
Scylla AMI doesn't support multiple availability zone

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla#3263]
When trying to create Scylla cluster with multiple availability zones (For example with CloudFormation) it's not supported by the reflector thus each node has its own seeds.

**Comment by slivne** [comment]
@noamha - when not using the reflector is there any issue ?

**Comment by noamha** [comment]
@slivne It works with the `--seeds` param

**Comment by slivne** [comment]
@noamha so can we close this.

**Comment by slivne** [comment]
ok great ... working on the postscript "[scylla-ami PATCH] Add custom script options to AMI user-data"

**Comment by slivne** [comment]
scylladb/scylla-ami@5200f3fab99e18b4572696f13a0895914311b1da
