### ISSUE TITLE
Failure during resharding from 7 to 7 CPUs: Exiting on unhandled exception: std::runtime_error, Exception while populating keyspace - no TOC found for SSTable

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3274]
I ran test that try to perform resharding from 7 to 7 CPUs (that actually is not resharding. Nothing happens is expected, just restart of node) during stress I/O.
Cluster size: 1 node
The test ran on my laptop with 8 CPUs.
Test failed. 
Log:
[system7_7.log](https://github.com/scylladb/scylla/files/1800258/system7_7.log)

I received it twice. But after can't recreate.
Last commit: 101e909

Error I found in the system log:

INFO  2018-03-11 10:46:45,871 [shard 0] database - Keyspace keyspace1: Reading CF standard1 
ERROR 2018-03-11 10:46:45,918 [shard 0] database - Exception while populating keyspace 'keyspace1' with column family 'standard1' from file '/home/juliay/.dtest/dtest-Zs7tXD/test/node1/data/keyspace1/standard1-92bf4ed0250711e888a6000000000003': sstables::malformed_sstable_exception (At directory: /home/juliay/.dtest/dtest-Zs7tXD/test/node1/data/keyspace1/standard1-92bf4ed0250711e888a6000000000003: no TOC found for SSTable with generation 195!. Refusing to boot)
WARN  2018-03-11 10:46:45,918 [shard 0] seastar - Exceptional future ignored: std::runtime_error (Exception while populating keyspace 'keyspace1' with column family 'standard1' from file '/home/juliay/.dtest/dtest-Zs7tXD/test/node1/data/keyspace1/standard1-92bf4ed0250711e888a6000000000003': sstables::malformed_sstable_exception (At directory: /home/juliay/.dtest/dtest-Zs7tXD/test/node1/data/keyspace1/standard1-92bf4ed0250711e888a6000000000003: no TOC found for SSTable with generation 195!. Refusing to boot)), backtrace:   0x583ec8
  0x5e6ec2
  0x582816
  0x5829d9
  0x657b24
  0x7824b0
  0x50d085
  /lib64/libc.so.6+0x21009
  0x57d319

ERROR 2018-03-11 10:46:45,918 [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Exception while populating keyspace 'keyspace1' with column family 'standard1' from file '/home/juliay/.dtest/dtest-Zs7tXD/test/node1/data/keyspace1/standard1-92bf4ed0250711e888a6000000000003': sstables::malformed_sstable_exception (At directory: /home/juliay/.dtest/dtest-Zs7tXD/test/node1/data/keyspace1/standard1-92bf4ed0250711e888a6000000000003: no TOC found for SSTable with generation 195!. Refusing to boot))

**Comment by denesb** [comment]
I also have seen this (#3199), but we couldn't reproduce it so it was closed.
/cc @raphaelsc

**Comment by juliayakovlev** [comment]
I received it today when run resharding from 7 to 2 CPUs.
Compaction strategy: DateTieredCompactionStrategy.

INFO  2018-03-12 15:49:57,135 [shard 0] database - Keyspace keyspace1: Reading CF standard1 
ERROR 2018-03-12 15:49:57,226 [shard 0] database - Exception while populating keyspace 'keyspace1' with column family 'standard1' from file '/home/juliay/.dtest/dtest-3kQKL_/test/node1/data/keyspace1/standard1-dab0c63025fa11e898d1000000000003': sstables::malformed_sstable_exception (At directory: /home/juliay/.dtest/dtest-3kQKL_/test/node1/data/keyspace1/standard1-dab0c63025fa11e898d1000000000003: no TOC found for SSTable with generation 135!. Refusing to boot)
WARN  2018-03-12 15:49:57,227 [shard 0] seastar - Exceptional future ignored: std::runtime_error (Exception while populating keyspace 'keyspace1' with column family 'standard1' from file '/home/juliay/.dtest/dtest-3kQKL_/test/node1/data/keyspace1/standard1-dab0c63025fa11e898d1000000000003': sstables::malformed_sstable_exception (At directory: /home/juliay/.dtest/dtest-3kQKL_/test/node1/data/keyspace1/standard1-dab0c63025fa11e898d1000000000003: no TOC found for SSTable with generation 135!. Refusing to boot)), backtrace:   0x583ec8
  0x5e6ec2
  0x582816
  0x5829d9
  0x657b24
  0x7824b0
  0x50d085
  /lib64/libc.so.6+0x21009
  0x57d319

ERROR 2018-03-12 15:49:57,227 [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Exception while populating keyspace 'keyspace1' with column family 'standard1' from file '/home/juliay/.dtest/dtest-3kQKL_/test/node1/data/keyspace1/standard1-dab0c63025fa11e898d1000000000003': sstables::malformed_sstable_exception (At directory: /home/juliay/.dtest/dtest-3kQKL_/test/node1/data/keyspace1/standard1-dab0c63025fa11e898d1000000000003: no TOC found for SSTable with generation 135!. Refusing to boot))
INFO  2018-03-12 15:49:57,227 [shard 0] compaction_manager - Asked to stop
INFO  2018-03-12 15:49:57,227 [shard 0] compaction_manager - Stopped
INFO  2018-03-12 15:49:57,227 [shard 1] compaction_manager - Asked to stop
INFO  2018-03-12 15:49:57,227 [shard 1] compaction_manager - Stopped

**Comment by raphaelsc** [comment]
Please share listing of all files in /home/juliay/.dtest/dtest-3kQKL_/test/node1/data/keyspace1/standard1-dab0c63025fa11e898d1000000000003

**Comment by juliayakovlev** [comment]
@raphaelsc  I assume you don't need the listing, correct?

**Comment by raphaelsc** [comment]
@juliayakovlev I think so. If you still face it, please open another issue with it.
