### ISSUE TITLE
Undefined behaviour in antlr

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#3286]
There is a potential null pointer dereference here: https://github.com/antlr/antlr3/blob/master/runtime/Cpp/include/antlr3exception.inl#L315

m_expectingSet is very often null. It should be checked before doing anything with this pointer.

Currently it leads to undefined behaviour and sometimes crashes of the whole program.

**Comment by syuu1228** [comment]
This is fixed, updated antlr is uploaded for all distributions, it will automatically download on scylla package building (to fetch updated package on local environment, need to 'apt upgrade' or 'yum update').

Updated packages are:
scylla-antlr35-c++-dev-3.5.2-ubuntu3 on Ubuntu,
scylla-antlr35-c++-dev-3.5.2-3 on Debian,
scylla-antlr35-C++-devel-3.5.2-2 on CentOS.
