### ISSUE TITLE
oversized allocation after upgrade to 2.1

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla#3287]
*Installation details*
Scylla version (or git commit hash): 2.1
Cluster size: 6 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentoOS

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets=2 cores=10 hyperthreading= memory=192G
Disks: (SSD/HDD, count) 4xSSD

After upgrade from 2.0.3 to 2.1 we get upon starting of the node:
Mar 08 10:10:30 XXXXXX scylla[1259]:  [shard 22] seastar_memory - oversized allocation: 59846656 bytes, please report: at   0x558659 ...

I moved the stack to readable format:
```
/usr/src/debug/scylla-2.1.0/seastar/core/memory.cc:629
/usr/src/debug/scylla-2.1.0/seastar/core/memory.cc:637
/usr/src/debug/scylla-2.1.0/seastar/core/memory.cc:1264
/usr/src/debug/scylla-2.1.0/seastar/core/memory.cc:1549
/usr/src/debug/scylla-2.1.0/utils/allocation_strategy.hh:179
/usr/src/debug/scylla-2.1.0/utils/managed_bytes.hh:228
/usr/src/debug/scylla-2.1.0/atomic_cell_or_collection.hh:32
/usr/src/debug/scylla-2.1.0/streamed_mutation.hh:56
/usr/src/debug/scylla-2.1.0/partition_snapshot_row_cursor.hh:268
/usr/src/debug/scylla-2.1.0/cache_flat_mutation_reader.hh:446
/usr/src/debug/scylla-2.1.0/row_cache.hh:548
/usr/src/debug/scylla-2.1.0/cache_flat_mutation_reader.hh:221
/usr/src/debug/scylla-2.1.0/cache_flat_mutation_reader.hh:221
/usr/src/debug/scylla-2.1.0/cache_flat_mutation_reader.hh:210
/usr/src/debug/scylla-2.1.0/cache_flat_mutation_reader.hh:215
/usr/src/debug/scylla-2.1.0/flat_mutation_reader.hh:338
/usr/src/debug/scylla-2.1.0/row_cache.cc:682
/usr/src/debug/scylla-2.1.0/seastar/core/future-util.hh:346
/usr/src/debug/scylla-2.1.0/seastar/core/reactor.cc:2431
/usr/src/debug/scylla-2.1.0/seastar/core/reactor.cc:2841
/opt/scylladb/include/c++/7/bits/unique_ptr.h:267
/usr/src/debug/scylla-2.1.0/seastar/core/reactor.cc:3931 (discriminator 3)
/opt/scylladb/include/c++/7/bits/std_function.h:706
```

we do have some "tuning" in place in scylla.yaml:
  $batch_size_warn_threshold_in_kb     = 51200
  $batch_size_fail_threshold_in_kb     = 512000
  $commitlog_segment_size_in_mb        = 128

Is that something to worry about? (since this message wasn't in 2.0.3?)

Thank you
Lubos

**Comment by tgrabiec** [comment]
The backtrace tells us that a reader is returning a row with a cell which is 59 MB in size. Such large cells are not handled well currently, they may cause performance issues due to excessive cache eviction or memory allocation failures. See https://github.com/scylladb/scylla/issues/2409.

The reason you didn't get a warning about that in earlier version is that we didn't warn about this in earlier versions.

**Comment by tarzanek** [comment]
thank you, will have a look on what I can do to avoid the perf issues
