### ISSUE TITLE
Doc: repetition of a the first paragraph of http://docs.scylladb.com/getting-started/ddl

### ISSUE THREAD

**Issue by vibl** [scylladb/scylla#3290]
The first paragraph of http://docs.scylladb.com/getting-started/ddl has been copy-pasted twice.

**Comment by tzach** [comment]
Thanks @vibl 
Good catch

**Comment by nirmaayan** [comment]
Fixed by https://github.com/scylladb/scylla-docs/pull/843
We can close this issue.
Thank you @vibl :+1:
