### ISSUE TITLE
API for failure injection

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3295]
*Installation details*
Scylla version (or git commit hash): master

As a complex distributed system, Scylla must deal with failure scenarios, which must be thoroughly tested. Such failures are usually simulated by stopping the node while operations are ongoing, but this presents some issues:

* There is little determinism, and tests risk becoming flaky or giving false negatives;
* Tests take longer, since stopping and starting nodes is expensive;
* Harder to impossible to do in unit tests.

What we could do instead is define a set of failure points (e.g., before applying a mutation to the commit log, before flushing a memtable, before sending view updates, etc.), properly tagged, which can be activated by the REST API or locally, in case of unit tests.

We can also provide a "production" build mode which deactivates the failure injection points.

**Comment by psarna** [comment]
Hi, I was in desperate need of this API for at least 5 times already, so I'm calling dibs on it (as a weekend project). If there are no objections, feel free to assign this one to me.

**Comment by duarten** [comment]
Have fun :)
