### ISSUE TITLE
Failed to install Scylla 2.1 on RHEL7.4

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#3298]
*Installation details*
Scylla version (or git commit hash): 2.1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL 7.4

*Hardware details (for performance issues)*          
Platform (physical/VM/cloud instance type/docker): AWS i3.xlarge

I tried installing Scylla 2.1 on an AWS i3.xlarge instance built from the "Quick Start" Red Hat Enterprise Linux 7.4 (HVM), SSD Volume Type - ami-223f945a.  Installation was successful but scylla_setup requested a reboot since it disabled SELinux and the instance hit a kernel panic on startup.  Here is the AWS system log:

```
[   12.606386] ena: Feature 10 isn't supported
[   12.610704] ena: Feature 18 isn't supported
[   12.616470] ena: Feature 27 isn't supported
[   13.320351] ISOFS: Unable to identify CD-ROM format.
[   19.050588] BUG: unable to handle kernel NULL pointer dereference at           (null)
[   19.056339] IP: [<          (null)>]           (null)
[   19.059969] PGD 80000007c1ba4067 PUD 7c1bd7067 PMD 0 
[   19.063763] Oops: 0010 [#1] SMP 
[   19.066154] Modules linked in: isofs sb_edac cirrus edac_core ttm intel_rapl iosf_mbi crc32_pclmul ghash_clmulni_intel drm_kms_helper aesni_intel lrw ppdev gf128mul syscopyarea glue_helper sysfillrect ablk_helper sysimgblt fb_sys_fops cryptd drm raid0 i2c_piix4 i2c_core pcspkr parport_pc parport xen_netfront ip_tables xfs libcrc32c ata_generic pata_acpi xen_blkfront ata_piix nvme libata crct10dif_pclmul crct10dif_common ena crc32c_intel nvme_core serio_raw floppy
[   19.098367] CPU: 0 PID: 4585 Comm: xz Not tainted 3.10.0-693.11.6.el7.x86_64 #1
[   19.103467] Hardware name: Xen HVM domU, BIOS 4.2.amazon 08/24/2006
[   19.107898] task: ffff8807f9e48000 ti: ffff8807c1a34000 task.ti: ffff8807c1a34000
[   19.113303] RIP: 0010:[<0000000000000000>]  [<          (null)>]           (null)
[   19.118772] RSP: 0000:ffff880800a03c80  EFLAGS: 00010206
[   19.122603] RAX: ffffffffc006e1a0 RBX: ffff8807f0b70f00 RCX: 0000000000000af9
[   19.127713] RDX: 0000000000000006 RSI: ffff8807eb6cba00 RDI: ffff8807f9700000
[   19.132810] RBP: ffff880800a03cd8 R08: ffffc90003bef7e0 R09: 0000000000000000
[   19.137829] R10: ffffc90003f64000 R11: 0000000000000af9 R12: ffff8807f9700000
[   19.142750] R13: 000000009af99af9 R14: ffff880800a03ce8 R15: 0000000000000000
[   19.147791] FS:  00007fe4e4d89740(0000) GS:ffff880800a00000(0000) knlGS:0000000000000000
[   19.153544] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   19.157662] CR2: 0000000000000000 CR3: 00000007c1a16000 CR4: 00000000001606f0
[   19.162728] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[   19.167724] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[   19.172655] Call Trace:
[   19.174391]  <IRQ> 
[   19.175815]  [<ffffffff8158733c>] ? get_rps_cpu+0x30c/0x370
[   19.180044]  [<ffffffff81589268>] netif_receive_skb_internal+0x98/0xc0
[   19.184590]  [<ffffffff8158a318>] napi_gro_receive+0xd8/0x130
[   19.188601]  [<ffffffffc0064777>] ena_clean_rx_irq+0x237/0x7b0 [ena]
[   19.193002]  [<ffffffffc0066825>] ena_io_poll+0x335/0x710 [ena]
[   19.197221]  [<ffffffff8158999d>] net_rx_action+0x16d/0x380
[   19.201321]  [<ffffffff810925bf>] __do_softirq+0xef/0x280
[   19.205249]  [<ffffffff816bd3ac>] call_softirq+0x1c/0x30
[   19.209061]  [<ffffffff8102d405>] do_softirq+0x65/0xa0
[   19.212820]  [<ffffffff81092945>] irq_exit+0x105/0x110
[   19.216616]  [<ffffffff813eabd5>] xen_evtchn_do_upcall+0x35/0x50
[   19.220999]  [<ffffffff816bd702>] xen_hvm_callback_vector+0x232/0x240
[   19.225714]  <EOI> 
[   19.227199] Code:  Bad RIP value.
[   19.230122] RIP  [<          (null)>]           (null)
[   19.234022]  RSP <ffff880800a03c80>
[   19.236585] CR2: 0000000000000000
[   19.238995] ---[ end trace e9117e752492a5ec ]---
[   19.242277] Kernel panic - not syncing: Fatal exception in interrupt
```

I wonder if this is related to the scylladb use of the NVMe disk.  I've attached the full install log.  I tried on two different instance types (i3.large, i3.xlarge) and both had the same result so it should be straightforward for you to reproduce.  Not sure if an additional configuration step needs to be added to scylla_setup or...?

[log.txt](https://github.com/scylladb/scylla/files/1821444/log.txt)

**Comment by glommer** [comment]
This is a known issue with the RHEL/CentOS kernel, and the reason we switch to the AWS kernel in the AMI. The issue is with the ENA driver for the network card and os exclusive to i3.

**Comment by veramine** [comment]
Oh ok.  I will switch to a different instance type and try again.  Thanks.

**Comment by dorlaor** [comment]
It's better to stick to i3 instances but just replace the kernel to the AWS
one

**Comment by glommer** [comment]
Dor: The problem of course is that the moment you do that, you lose the
benefits of the RHEL subscription.

If CentOS is an option for you then I second Dor's recommendation

**Comment by veramine** [comment]
We are using CentOS for our own instances and it works fine. One of our customers wants to do an on prem deployment and they must RHEL 7.4 according to Corp policy so I was testing that on AWS.  But as long as they do not use the problematic hardware then they should be ok. What advice could I give them regarding hardware selection to avoid this incompatibility?

**Comment by glommer** [comment]
First, if they are supported it would be really nice if they could work
with Red Hat to get an update on this. This really is a RHEL bug and is
quite annoying.

The next best thing is i2. They are a bit more expensive than i3 and their
SSDs is slower.

It also may be possible to change how we set up networking so as not to hit
this bug - but you will lose some performance and reliability there as well.

Lastly, since this is not a Scylla bug,  maybe we can close this issue and
move this conversation to slack ?

I will be more than happy to help you going forward here.

**Comment by veramine** [comment]
Absolutely fine to close the bug.  Thanks for the insight, and I will connect with you on slack on Monday. Thanks again!
