### ISSUE TITLE
Unexpected re-sharding

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3303]
Cluster with 1 node and:
SMP: 4
 murmur3 parameter: 15

I restarted the node without change SMP and MURMUR3 parameters.
I expected the node will start without resharding. But in the log I found Resharding messages:
[system.log](https://github.com/scylladb/scylla/files/1824307/system.log)

**Comment by slivne** [comment]
@juliayakovlev please include either scylla version or (better) github commit

**Comment by juliayakovlev** [comment]
commit f80d4a28d75689817111284cbf52152a53431a59

**Comment by raphaelsc** [comment]
@juliaangell Hi. I need more details. Was it a clean restart? Did you upload any sstable in the interval scylla was offline? From the log, i see it's a dtest. Which one?

**Comment by slivne** [comment]
its the wrong julia ..... @juliayakovlev 

"Hi. I need more details. Was it a clean restart? Did you upload any sstable in the interval scylla was offline? From the log, i see it's a dtest. Which one?"

**Comment by juliayakovlev** [comment]
@raphaelsc 
Hi Raphael, sorry for delay with answer.
The procedure is:
- run cassandra stress and wait for the finish
- stop the node
- set 'murmur3_partitioner_ignore_msb_bits' to the same value
- start the node with the same SMP

In the time when node was offline, any sstables shouldn't be uploaded.
The test named "resharding_by_same_smp_test"

**Comment by juliayakovlev** [comment]
@raphaelsc 
I performed some tests. 
If I does not set smp **AND** murmur3 in time node start **explicitly**, re-sharding is not started:

If I set both of parameter in time of starting the node, like in the test (see below), re-sharding is started:
     self.node.set_configuration_options(values={'murmur3_partitioner_ignore_msb_bits': murmur3})
     self.node.start(jvm_args=['--smp', smp, '--memory', self.set_memory_param(smp)],
                        wait_other_notice=True, wait_for_binary_proto=True)

**Comment by juliayakovlev** [comment]
Yes, you are right. The murmur3 default value is 12, not 15.
I fixed the test and now it's passed.
Closing the issue
