### ISSUE TITLE
Assertion 'end >= _stream_position' failed.

### ISSUE THREAD

**Issue by EmpireJones** [scylladb/scylla#3304]
*Installation details*
Scylla version (or git commit hash): docker image scylladb/scylla:2.1.0
Cluster size: 3
OS:  docker image scylladb/scylla:2.1.0, via kubernetes with host running container linux (coreos) AMI.

Nodes keep dieing in loop with:
```
INFO  2018-03-20 01:21:11,743 [shard 0] storage_service - Thrift server listening on 10.200.4.20:9160 ...
scylla: sstables/consumer.hh:304: seastar::future&lt;&gt; data_consumer::continuous_data_consumer&lt;StateProcessor&gt;::fast_forward_to(size_t, size_t) [with StateProcessor = sstables::data_consume_rows_context; size_t = long unsigned int]: Assertion `end &gt;= _stream_position' failed.
Aborting on shard 0.
Backtrace:
  0x00000000004a38ab
  0x00000000004a397c
  0x00000000004a3a33
  /lib64/libpthread.so.0+0x000000000000f5df
  /lib64/libc.so.6+0x00000000000351f6
  /lib64/libc.so.6+0x00000000000368e7
  /lib64/libc.so.6+0x000000000002e265
  /lib64/libc.so.6+0x000000000002e311
  0x0000000000cc2e3a
  0x0000000000ccdd6d
  0x0000000000ce969d
  0x0000000000ced966
  0x0000000000ceddd6
  0x0000000000cee86e
  0x0000000000cef64d
  0x00000000004a026a
  0x00000000004a054c
  0x00000000004ef444
  0x0000000000583a36
  0x000000000042ab2a
  /lib64/libc.so.6+0x0000000000021c04
  0x000000000049bebd
```
Nothing is in the coredump folder.

This was after one of the nodes died complaining about NOFILE limit. I attempted to up that on the host, and now I get this. Maybe stuff got corrupt when the nofile limit was hit.

The docker images don't have the scylla-debuginfo package, but here are other package details:
```
$ rpm -qa | grep scylla                                                                                                                                   
scylla-libgcc72-7.2.1-1.el7.centos.x86_64
scylla-server-2.1.0-0.20180216.58b90ceee.el7.centos.x86_64
scylla-tools-2.1.0-20180216.804760b4e.el7.centos.noarch
scylla-2.1.0-0.20180216.58b90ceee.el7.centos.x86_64
scylla-env-1.0-1.el7.centos.noarch
scylla-libstdc++72-7.2.1-1.el7.centos.x86_64
scylla-conf-2.1.0-0.20180216.58b90ceee.el7.centos.x86_64
scylla-kernel-conf-2.1.0-0.20180216.58b90ceee.el7.centos.x86_64
scylla-tools-core-2.1.0-20180216.804760b4e.el7.centos.noarch
scylla-jmx-2.1.0-20180216.02df8c1.el7.centos.noarch
```

**Comment by tgrabiec** [comment]
A coredump would be very helpful. 

If possible, a log with trace-level sstable logging enabled which leads to the crash. To enable, pass `--logger-log-level sstable=trace` to the command line arguments of the scylla server. Beware that it may generate a lot of output.

**Comment by slivne** [comment]
@EmpireJones
- do all the nodes - die, or only the one that have the file limit issue ?
- if we can get a coredump that will be great
- another alternative we can try, if its possible is sharing a sample sstable and schema (assuming its reproducible).

**Comment by EmpireJones** [comment]
Any instructions on how to get a coredump if it's not output to the coredump folder?
@tgrabiec  I'll see what info I can collect tomorrow (US time). It looks like I can't just pass that arg to the docker entrypoint, so I'll have to start things manually.
@slivne all (3) nodes die

**Comment by slivne** [comment]
with regards to generating coredumps  - I admit I did not find a good solution 
- I did find this: https://github.com/moby/moby/issues/11740 - and that did work 

change   /proc/sys/kernel/core_pattern 
```
echo `/tmp/core.%e.%p.%t` > /proc/sys/kernel/core_pattern 
```
boot scylla 

I was able to generate some coredumps with 
```
pkill -ABRT scylla
kill -ABRT <scylla-pid>
```

yet not in all cases

and I am not sure this viable in your setup as well - if its - we can try that.

in addition if its possible to share a sample sstable and schema (assuming its reproducible) / a cassandra-stress profile.yaml that has the schema and dummy generation of datat - we can try and run it here.

**Comment by EmpireJones** [comment]
Assuming everything worked, I've uploaded core.scylla.228.1521602023.xz to the scylladb server using uuid c2962e42-b66e-49ef-b5e6-7d298bf4c4c0

**Comment by tgrabiec** [comment]
@EmpireJones I have a patch which most likely fixes your issue. Do you want an RPM for testing or do you prefer to wait for a blessed patch release?

**Comment by avikivity** [comment]
@tgrabiec please also send the patch to the list

**Comment by EmpireJones** [comment]
@tgrabiec I'm glad you were able to track this down! Nice work! I could use an RPM if the patch release is a ways out; otherwise, I'm fine with waiting. Thanks!

**Comment by tgrabiec** [comment]
@EmpireJones Scylla 2.1.1 was just released with the fix.

**Comment by wqwiii** [comment]
> 
> 
> @EmpireJones Scylla 2.1.1 was just released with the fix.

no it still happen in 2.1.6

**Comment by tgrabiec** [comment]
@wqwiii You're probably hitting a different problem, which triggers the same assert. Please upload the core dump: https://docs.scylladb.com/troubleshooting/report_scylla_problem/#core-dump
