### ISSUE TITLE
offline installer - from packages

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#3306]
*Installation details*

In some cases, Scylla nodes to-be do not have access to the public repo.
It would be useful to provide an "uber-tar", with all the dependencies included for a user to download on a node with external access, and copy to Scylla node for installation.
The uber-tar path will be available on the scylla.com site, similar to Scylla repo.

Current [Offline-Installer](https://github.com/scylladb/scylla/wiki/Offline-Installer) instructions require one to build Scylla from source.

**Comment by tzach** [comment]
@slivne ping

**Comment by syuu1228** [comment]
@slivne @tzach After we merged relocatable package (currently master only, probably available on 3.1?) dependencies are significantly less than before, we almost done this request.

But we still have two big dependencies, python3 for scripts, OpenJDK for -jmx & -tools.
I’m not sure this is correct appoach but we may able to provide them by using relocatable package, too(copy them from Fedora).

**Comment by slivne** [comment]
@glommer  / @syuu1228 in 3.1 do we have this supported now ? I know python3 was fixed

**Comment by tzach** [comment]
@syuu1228 ?

**Comment by tzach** [comment]
Done!
