### ISSUE TITLE
is CQL can be attacked with SQL Injection

### ISSUE THREAD

**Issue by codenoid** [scylladb/scylla#3308]
*Installation details*
Scylla version (or git commit hash): 2.1.0-0.20180216.58b90ce
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

**Comment by raphaelsc** [comment]
is that a question or you're affirming it? if the latter, please share more details.

**Comment by codenoid** [comment]
it's a question

**Comment by codenoid** [comment]
i use python cassandra driver

**Comment by avikivity** [comment]
Please ask questions on the mailing list, not bug tracker.

**Comment by codenoid** [comment]
i'll use mongo, tq

**Comment by nyh** [comment]
And in any case, "SQL Injection" is when an application or website or wherever, passes unvalidated input directly to an SQL database and cause it to do unintended (by the developer) things.
CQL will have exactly the same issue if you pass to it un-validated input.

**Comment by codenoid** [comment]
right
