### ISSUE TITLE
dist/ami: not able to build with http://repositories.scylladb.com/ repo

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#3312]
When we passes repo URL on http://repositories.scylladb.com/, AMI builder does not recognize the .repo, and it seems including HTML:
```
    amazon-ebs: File contains no section headers.
    amazon-ebs: file: file:///etc/yum.repos.d/scylla_install.repo, line: 1
    amazon-ebs: '<html>\r\n
```

This is because the URL using redirection, but curl command does not followed the redirection.

**Comment by tzach** [comment]
`curl -L` should do the trick

**Comment by amoskong** [comment]
Related with https://github.com/scylladb/scylla-cluster-tests/issues/508
HTTP server returns 301 error, it's fixed by adding `-L` for curl.
