### ISSUE TITLE
Add cluster identifier to all metrics

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#3322]
*Installation details*

When monitoring more than one cluster, monitoring system needs a way to identify which metrics are reported from which cluster.
One way to do that is adding cluster name as a label. But, since users may not change cluster name, it will be useful to add a unique id to the cluster name.

**Comment by tzach** [comment]
Problem: cluster agreement on a unique identifier to use in addition to the not so unique cluster-name.
Since a node boot before it knows it is part of a cluster,  the identifier should result in an agreement between cluster nodes, and propagate over gossip

@asias any idea?

**Comment by slivne** [comment]
@asias - help

**Comment by asias** [comment]
We can generate a uuid as the cluster identifier but it is not easy to make all the nodes to agree on a one.

**Comment by asias** [comment]
Since we know the ip of a node and which ip belongs to which cluster. Isn't this enough?

**Comment by slivne** [comment]
We can push this post LWT - then we will have a manner to set such a property up.

I suggest we add the cluster name, even if its not perfect its better then not having anything today (and advanced users know thye need to modify it - or should know that).

**Comment by slivne** [comment]
@amnonh - so please add cluster-name to all metrics - better then nothing at this point

**Comment by amnonh** [comment]
Let's move it to Prometheus configuration

**Comment by amnonh** [comment]
@tzach I think we should close this one

**Comment by tzach** [comment]
Do we have an issue/PR on another project?
