### ISSUE TITLE
Scylla unable to boot when deleting temporary TOC for a column family that has generations with different versions

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#3324]
distributed_loader::populate_column_family() (at database.cc) only gets version and format once and forwards them to all generations with tmp TOC. So KA may be forward as version to a generation which is LA, and as a result, the deletion code will not work because it will fail to look for the files.

**Comment by raphaelsc** [comment]
@daniel-from-scylla

**Comment by raphaelsc** [comment]
The fix is about saving the version for all files with temporary TOC. That can all be done inside distributed_loader::populate_column_family()

**Comment by glommer** [comment]
Effect of this bug is that a node was basically dead and unrecoverable.

**Comment by hagrid-the-developer** [comment]
How can I save the version of the files? Maybe I simply don't understand.

**Comment by avikivity** [comment]
I think it's `distributed_loader::populate_column_family()::verifier`. It remembers the generation, but forgets the version.

**Comment by raphaelsc** [comment]
Avi is right. kill sstable_descriptor and extend verifier to remember version and format. Then propagate them both to call sstables::sstable::remove_sstable_with_temp_toc()

**Comment by duarten** [comment]
Still not solved for me:

```
INFO  2018-04-13 20:28:58,879 [shard 0] storage_service - Node 127.0.0.1 state jump to normal
ERROR 2018-04-13 20:28:58,880 [shard 0] sstable - Could not create SSTable component tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-2-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
ERROR 2018-04-13 20:28:58,880 [shard 0] database - failed to write sstable tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-2-big-Data.db: std::system_error (error system:2, No such file or directory)
WARN  2018-04-13 20:28:58,880 [shard 0] sstable - Unable to delete tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-2-big-TOC.txt because it doesn't exist.
ERROR 2018-04-13 20:28:59,320 [shard 0] sstable - Could not create SSTable component tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-17-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
ERROR 2018-04-13 20:28:59,320 [shard 0] database - failed to write sstable tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-17-big-Data.db: std::system_error (error system:2, No such file or directory)
WARN  2018-04-13 20:28:59,320 [shard 0] sstable - Unable to delete tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-17-big-TOC.txt because it doesn't exist.
^C^[[AERROR 2018-04-13 20:29:08,880 [shard 0] sstable - Could not create SSTable component tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-3-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
ERROR 2018-04-13 20:29:08,880 [shard 0] database - failed to write sstable tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-3-big-Data.db: std::system_error (error system:2, No such file or directory)
WARN  2018-04-13 20:29:08,880 [shard 0] sstable - Unable to delete tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-3-big-TOC.txt because it doesn't exist.
ERROR 2018-04-13 20:29:09,320 [shard 0] sstable - Could not create SSTable component tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-18-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
ERROR 2018-04-13 20:29:09,320 [shard 0] database - failed to write sstable tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-18-big-Data.db: std::system_error (error system:2, No such file or directory)
WARN  2018-04-13 20:29:09,320 [shard 0] sstable - Unable to delete tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-18-big-TOC.txt because it doesn't exist.
ERROR 2018-04-13 20:29:18,881 [shard 0] sstable - Could not create SSTable component tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-4-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
ERROR 2018-04-13 20:29:18,881 [shard 0] database - failed to write sstable tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-4-big-Data.db: std::system_error (error system:2, No such file or directory)
WARN  2018-04-13 20:29:18,881 [shard 0] sstable - Unable to delete tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-4-big-TOC.txt because it doesn't exist.
ERROR 2018-04-13 20:29:19,320 [shard 0] sstable - Could not create SSTable component tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-19-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
ERROR 2018-04-13 20:29:19,320 [shard 0] database - failed to write sstable tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-19-big-Data.db: std::system_error (error system:2, No such file or directory)
WARN  2018-04-13 20:29:19,321 [shard 0] sstable - Unable to delete tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-19-big-TOC.txt because it doesn't exist.
ERROR 2018-04-13 20:29:28,881 [shard 0] sstable - Could not create SSTable component tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-5-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
ERROR 2018-04-13 20:29:28,881 [shard 0] database - failed to write sstable tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-5-big-Data.db: std::system_error (error system:2, No such file or directory)
WARN  2018-04-13 20:29:28,881 [shard 0] sstable - Unable to delete tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-5-big-TOC.txt because it doesn't exist.
ERROR 2018-04-13 20:29:29,321 [shard 0] sstable - Could not create SSTable component tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-20-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
ERROR 2018-04-13 20:29:29,321 [shard 0] database - failed to write sstable tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-20-big-Data.db: std::system_error (error system:2, No such file or directory)
WARN  2018-04-13 20:29:29,321 [shard 0] sstable - Unable to delete tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-20-big-TOC.txt because it doesn't exist.
ERROR 2018-04-13 20:29:38,881 [shard 0] sstable - Could not create SSTable component tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-6-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
...
```

Scylla doesn't boot and this just keeps happening.

**Comment by raphaelsc** [comment]
On Fri, Apr 13, 2018 at 3:31 PM, Duarte Nunes <notifications@github.com>
wrote:

> Still not solved for me:
>
> INFO  2018-04-13 20:28:58,879 [shard 0] storage_service - Node 127.0.0.1 state jump to normal
> ERROR 2018-04-13 20:28:58,880 [shard 0] sstable - Could not create SSTable component tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-2-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
> ERROR 2018-04-13 20:28:58,880 [shard 0] database - failed to write sstable tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-2-big-Data.db: std::system_error (error system:2, No such file or directory)
> WARN  2018-04-13 20:28:58,880 [shard 0] sstable - Unable to delete tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-2-big-TOC.txt because it doesn't exist.
> ERROR 2018-04-13 20:28:59,320 [shard 0] sstable - Could not create SSTable component tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-17-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
> ERROR 2018-04-13 20:28:59,320 [shard 0] database - failed to write sstable tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-17-big-Data.db: std::system_error (error system:2, No such file or directory)
> WARN  2018-04-13 20:28:59,320 [shard 0] sstable - Unable to delete tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-17-big-TOC.txt because it doesn't exist.
> ^C^[[AERROR 2018-04-13 20:29:08,880 [shard 0] sstable - Could not create SSTable component tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-3-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
> ERROR 2018-04-13 20:29:08,880 [shard 0] database - failed to write sstable tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-3-big-Data.db: std::system_error (error system:2, No such file or directory)
> WARN  2018-04-13 20:29:08,880 [shard 0] sstable - Unable to delete tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-3-big-TOC.txt because it doesn't exist.
> ERROR 2018-04-13 20:29:09,320 [shard 0] sstable - Could not create SSTable component tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-18-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
> ERROR 2018-04-13 20:29:09,320 [shard 0] database - failed to write sstable tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-18-big-Data.db: std::system_error (error system:2, No such file or directory)
> WARN  2018-04-13 20:29:09,320 [shard 0] sstable - Unable to delete tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-18-big-TOC.txt because it doesn't exist.
> ERROR 2018-04-13 20:29:18,881 [shard 0] sstable - Could not create SSTable component tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-4-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
> ERROR 2018-04-13 20:29:18,881 [shard 0] database - failed to write sstable tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-4-big-Data.db: std::system_error (error system:2, No such file or directory)
> WARN  2018-04-13 20:29:18,881 [shard 0] sstable - Unable to delete tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-4-big-TOC.txt because it doesn't exist.
> ERROR 2018-04-13 20:29:19,320 [shard 0] sstable - Could not create SSTable component tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-19-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
> ERROR 2018-04-13 20:29:19,320 [shard 0] database - failed to write sstable tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-19-big-Data.db: std::system_error (error system:2, No such file or directory)
> WARN  2018-04-13 20:29:19,321 [shard 0] sstable - Unable to delete tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-19-big-TOC.txt because it doesn't exist.
> ERROR 2018-04-13 20:29:28,881 [shard 0] sstable - Could not create SSTable component tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-5-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
> ERROR 2018-04-13 20:29:28,881 [shard 0] database - failed to write sstable tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-5-big-Data.db: std::system_error (error system:2, No such file or directory)
> WARN  2018-04-13 20:29:28,881 [shard 0] sstable - Unable to delete tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-5-big-TOC.txt because it doesn't exist.
> ERROR 2018-04-13 20:29:29,321 [shard 0] sstable - Could not create SSTable component tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-20-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
> ERROR 2018-04-13 20:29:29,321 [shard 0] database - failed to write sstable tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-20-big-Data.db: std::system_error (error system:2, No such file or directory)
> WARN  2018-04-13 20:29:29,321 [shard 0] sstable - Unable to delete tmp/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/la-20-big-TOC.txt because it doesn't exist.
> ERROR 2018-04-13 20:29:38,881 [shard 0] sstable - Could not create SSTable component tmp/system/peers-37f71aca7dc2383ba70672528af04d4f/la-6-big-TOC.txt.tmp. Found exception: std::system_error (error system:2, No such file or directory)
> ...
>
> Scylla doesn't boot and this just keeps happening.
>

looks like another bug to me, possibly originated from the attempt to fix
this issue's bug.

**Comment by duarten** [comment]
You're likely right, the last time I ran Scylla from this directory was without this patch.

**Comment by hagrid-the-developer** [comment]
@duearte Could you provide more context? I tried to simulate the issue but everything seems to work. I tried: Build older version of scylla, start it with empty /var/lib/scylla and then build the up-to-date version of scylla and start it again, with already initialised /var/lib/scylla.

I tried both versions before fix of 3324 and version before la format was introduced...

**Comment by duarten** [comment]
Unfortunately, that's the extent of the information I can provide. There were `ka` sstables (I didn't preserve them, and I don't know the commit I was at when they were created), Scylla booted and tried to delete `la` sstables instead of `ka`, and then it tried to delete that missing sstable (presumably because that's the standard reaction to an error), and so on and so forth.

**Comment by duarten** [comment]
Looking closer, it seems the issue is probably unrelated to this: we were failing to create the sstable and getting ENOENT, which missing something was missing in the path?
