### ISSUE TITLE
Migration manager failure when create the materialized view during node removing

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3333]
Scenario:
1. create and prefill table
2. run in parallel:
    - create a few materialized views on the table
    - remove node (127.0.0.2) 
After the node has been removed, the error was thrown:
ERROR 2018-03-29 16:27:32,467 [shard 0] migration_manager - Failed to update definitions from 127.0.0.4:0: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID eedb77b0-3354-11e8-a031-000000000000): std::out_of_range (_Map_base::at)

INFO  2018-03-29 16:28:30,056 [shard 0] rpc - client 127.0.0.2: fail to connect: Connection refused
ERROR 2018-03-29 16:28:31,754 [shard 0] migration_task - Can't send migration request: node 127.0.0.2 is down.

By UUID of the column family it's base table

**Comment by duarten** [comment]
This doesn't seem like an issue to me. You stopped a node and we failed to communicate with it, for a schema pull.

**Comment by juliayakovlev** [comment]
In this test I remove the node, not stop.
I have another test where node is stopped (not removed). This test is passed.
My question is: should we try to send migration request if node has been removed and does not exist in the cluster anymore?

**Comment by duarten** [comment]
It takes time for the other nodes to realize one is down, so it's possible. That it passes for stop and not for remove means that when stopping, the node may wait for the others to realize it's going down (I'll have to check the implementation).

**Comment by duarten** [comment]
There are some steps that are not clear to me:

- Do you wait for schema agreement after creating the views and before removing the node?
- How many nodes are there?
- Which node do you call removenode on?
- Which node do you create the MVs on?

Maybe it would also help if you could share the test :)

**Comment by juliayakovlev** [comment]
The test is mv_populating_from_existing_data_during_node_remove_test

>> Do you wait for schema agreement after creating the views and before removing the node?
As I mentioned in the issue description, view creation and removing the node were run in parallel, not sequentially 
>> How many nodes are there?
4 nodes
>> Which node do you call removenode on?
node2
>> Which node do you create the MVs on?
I create session that run MVs creation from is node1.

**Comment by duarten** [comment]
Sorry, waiting for schema agreement wouldn't even work, because the node is going down.

So, removing the node basically calls`node.stop(gently=False)`, which translates to doing a `kill -9` on the node.

The migration requests fails because it either happens in parallel with stopping the node, or before gossip can mark the node as dead. The migration request happens because we don't wait for schema agreement before starting to send data.

**Comment by juliayakovlev** [comment]
I don't send the data in this scenario. 
I assume the data is sent by MV creation mechanism (or some other mechanism) after MV is created. I do not perform it in this test.
The scenario is:
1. create base table
2. prefill the table with data
3. Run creation of few MVs
4. In parallel with MVs creation one of the nodes was removed.

It seems me real user scenario.
Do we have some restriction (explained to the user) that not allow to perform some nodes manipulations during MV creation?
@slivne @roydahan  Please, let your opinion, if this expected behavior in case node removing?

**Comment by duarten** [comment]
Yes, view building sends existing base table data to the MVs. Users can do what they want, but if a node fails or they stop it forcefully then they can't expected it to get normal updates, or view updates.
