### ISSUE TITLE
docker should default to overprovisioned

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#3336]
Currently our docker image does not default to overprovisioned.
The effects of that is that if there are more than one container running, even if the host isn't really overprovisioned and resources are statically partitioned with --smp, all containers will bind to the same set of CPUs. That results in performance being really bad.

We should default to overprovisioned, and then let the user remove it when tuning is done.

**Comment by penberg** [comment]
Fixed in master by https://github.com/scylladb/scylla/commit/ef84780c272c731d4d62c3116123a6a094493aad.
