### ISSUE TITLE
2.2 AMI still uses master pkgs & repo

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3343]
*Installation details*
Scylla version (or git commit hash): scylla-666.development-0.20180403.8bf6f3939.el7.centos.x86_64
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): AMI ami-14d07269

Job link: http://jenkins.cloudius-systems.com:8080/job/scylla-2.2-ami-test/3

```
[centos@ip-10-97-132-87 ~]$ rpm -qa |grep scylla
scylla-libstdc++73-7.3.1-1.el7.centos.x86_64
scylla-kernel-conf-666.development-0.20180403.8bf6f3939.el7.centos.x86_64
scylla-jmx-666.development-20180403.5aaa5fa.el7.centos.noarch
scylla-666.development-0.20180403.8bf6f3939.el7.centos.x86_64
scylla-env-1.0-1.el7.centos.noarch
scylla-conf-666.development-0.20180403.8bf6f3939.el7.centos.x86_64
scylla-tools-core-666.development-20180403.16e3f6681.el7.centos.noarch
scylla-debuginfo-666.development-0.20180403.8bf6f3939.el7.centos.x86_64
scylla-libgcc73-7.3.1-1.el7.centos.x86_64
scylla-tools-666.development-20180403.16e3f6681.el7.centos.noarch
scylla-server-666.development-0.20180403.8bf6f3939.el7.centos.x86_64
[centos@ip-10-97-132-87 ~]$ cat /etc/yum.repos.d/scylla.repo 
[scylla]
name=Scylla for Centos $releasever - $basearch
baseurl=http://downloads.scylladb.com/rpm/unstable/centos/master/latest/scylla/\7/$basearch/
enabled=1
gpgcheck=0

[scylla-generic]
name=Scylla for centos $releasever
baseurl=http://downloads.scylladb.com/rpm/unstable/centos/master/latest/scylla/\7/noarch/
enabled=1
gpgcheck=0

[scylladb-scylla-3rdparty]
name=Copr repo for scylla-3rdparty owned by scylladb
baseurl=https://copr-be.cloud.fedoraproject.org/results/scylladb/scylla-3rdparty/epel-7-x86_64/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/scylladb/scylla-3rdparty/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
```

@syuu1228

**Comment by syuu1228** [comment]
@amoskong No it's not, this is actually correct branch-2.2 packages.
See: http://jenkins.cloudius-systems.com/view/scylla-2.2/job/scylla-2.2-centos-rpm/7/
We have exactly same file name rpms between 2.2-ami job and 2.2-centos-rpm job.

Also you can verify it by comparing where rpms are uploaded:
http://jenkins.cloudius-systems.com/view/scylla-2.2/job/scylla-2.2-centos-rpm/7/console
And it matches with scylla_repo_file_url:
http://jenkins.cloudius-systems.com/view/scylla-2.2/job/scylla-2.2-ami/3/injectedEnvVars/

We are not yet versioned branch-2.2:
https://github.com/scylladb/scylla/blob/branch-2.2/SCYLLA-VERSION-GEN#L3
After VERSION= on the script rewrite to 2.2.x, you will get 2.2.x rpms.

**Comment by amoskong** [comment]
It seems we will persistently use `666.development` until 2.2.rc0 release.

CC @penberg

**Comment by roydahan** [comment]
@slivne, can we fix it somehow?

**Comment by slivne** [comment]
it should be fixed now
