### ISSUE TITLE
Scylla-2.2 fails to start on Debian 8

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#3344]
Seems like "AmbientCapabilities=CAP_SYS_NICE" causes Invalid argument on Debian 8:
```
Apr 04 12:57:12 takuya-jessie2 systemd[24327]: scylla-server.service: Failed at step CAPABILITIES spawning /usr/bin/scylla: Invalid argument
```
Tested on GCE Debian 8 instance with branch-2.2 .deb package.
After commented out the line on scylla-server.service, it just worked finely.

**Comment by syuu1228** [comment]
Probably this isn't really about "AmbientCapabilities=CAP_SYS_NICE" on the systemd unit file, I actually able to run branch-2.1 package on same machine WITH the option.

**Comment by syuu1228** [comment]
Maybe related with https://github.com/systemd/systemd/issues/5000

**Comment by syuu1228** [comment]
systemd version in Debian 8 (230-7~bpo8+2) matches with the issue reported on systemd issue list https://github.com/systemd/systemd/issues/5000.

But the patch which closed the issue (https://github.com/keszybz/systemd/commit/1a3a5dc6032a7bcac5b75478028349f09b2f4c10)  is just trying to be more verbose when the error occurs, maybe there is real reason cannot to set capabilities, which is not because we are using old version of systemd.

**Comment by syuu1228** [comment]
@avikivity any idea with this?

**Comment by slivne** [comment]
@avikivity , @syuu1228 - ping - any resolution

**Comment by avikivity** [comment]
@syuu1228 does it work without the capability line? if so, we can just remove that line for now.

**Comment by avikivity** [comment]
(just for debian 8)

**Comment by syuu1228** [comment]
@avikivity It just starts finely (w/o the capability line), and I also tested with cassandra-stress for few minites, no errors occurred. So I think we can drop the line for Debian8 for now

**Comment by syuu1228** [comment]
Sent patch "[PATCH scylla] dist: Drop AmbientCapabilities from scylla-server.service for Debian 8"
