### ISSUE TITLE
row_cache_test occasionally times out

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#3346]
Occasionally, row_cache_test will not complete, spinning. I've seen this mostly on the build machines.

**Comment by nyh** [comment]
I have the following. Not sure if it's the same problem:

> I just saw from test.py --mode=release the error:
> *** 3 failures are detected in the test module "tests/row_cache_test.cc"
> I can sometimes reproduce this problem with test.py (3 out of 6 runs failed in this manner), but couldn't reproduce it in several manual runs of the test, though I do consistently get a scary-looking (but maybe it's a deliberate part of the test?):
> WARN  2018-04-24 12:02:57,043 [shard 0] cache - Failure during cache update: std::bad_alloc (std::bad_alloc)

**Comment by slivne** [comment]
@avikivity / @tgrabiec have we fixed this ?

**Comment by tgrabiec** [comment]
@slivne I've sent several fixes to this test since then, which could have solved this. Avi, you are monitoring jenkins more than I do, has this stopped happening?

**Comment by avikivity** [comment]
No issues for a while.
