### ISSUE TITLE
Can not replace a node after all nodes shutdown

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#3347]
Problem:
       Start node 1 2 3
       Shutdown node2
       Shutdown node1 node3
       Start node1 node3
       Try to repalce_address for node 2
       The replace operation fails with the error:
         seastar - Exiting on unhandled exception: std::runtime_error
         (Cannot replace_address node2 because it doesn't exist in gossip)

This is because after all nodes shutdown, the other nodes do not have the
tokens and host_id info of node2 until node2 boots up and talks to the cluster.

**Comment by tzach** [comment]
@asias which version?

**Comment by asias** [comment]
all
