### ISSUE TITLE
gc_clock will explode in 2038

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#3353]
gc_clock uses a 32-bit representation with 1-second resolution, ending the world in 2038. Given we store times in the future (for TTLs), we can already see the problem with large TTLs.

We should move gc_clock to 64 bits, and make sure atomic_cell and sstable representations are adjusted. Likely `m` format sstables will work if they use vint serialization.

**Comment by avikivity** [comment]
Related Cassandra issue: https://issues.apache.org/jira/browse/CASSANDRA-14092

**Comment by yksdb** [comment]
Which release(s) is this bug fixed in? @tzach ?

**Comment by bhalevy** [comment]
> Which release(s) is this bug fixed in? @tzach ?

@yksdb: 3.1 (with related upgrade issue fixed in 3.1.1)
