### ISSUE TITLE
Improve error message - nodetool refresh

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#3372]
*Installation details*
Scylla version (or git commit hash): 2.0.2
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Steps to reproduce 
1. Create keyspace - `CREATE KEYSPACE nba WITH replication = {'class': 'SimpleStrategy', 'replication_factor' : '3'};
`
2. Create table - `
CREATE TABLE nba.omg (
id int,
a int,
b text,
c text,
PRIMARY KEY ((id, a), b)
); 
`
3. Run `nodetool refresh nba omg`
This issue appears on 2.0.2 but not on 2.1.1

**Comment by slivne** [comment]
closing
