### ISSUE TITLE
scylla-server conflicts with abrt-2.1.11-50.el7.x86_64

### ISSUE THREAD

**Issue by ishibaev** [scylladb/scylla#3377]
*Installation details*
Scylla version (or git commit hash): trying to create 2.1.2 offline package
Cluster size: 4 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Red Hat Enterprise Linux Server release 7.5 (Maipo)

When I run (as root)
yumdownloader --installroot=/build/installroot --archlist=x86_64 --destdir=build/offline_installer --resolve scylla

I received error -
_scylla-server conflicts with abrt-2.1.11-50.el7.x86_64
Dependency resolution failed, some packages will not be downloaded._
and  process continue.
2 Questions - 
1st - there are no abrt-2.1.11-50.el7.x86_64 on host, why this message appeared?
2nd - is it possible to know, which packages were not downloaded ?

**Comment by tzach** [comment]
duplicate with #892

**Comment by ishibaev** [comment]
#892 case is about problem with ABRT.
My problem with one step, when I'm  trying to create local installer, the strange message about ABRT package appeared. ABTR package is not installed on host, it's only available in yum, but not installed.
with all this information above, does my  case still duplicate with #892 ?

**Comment by tzach** [comment]
@ishibaev I'm not sure. @syuu1228 can you help?

**Comment by slivne** [comment]
@syuu1228 ping ?

**Comment by syuu1228** [comment]
Possibly offline installer broken on RHEL, will check.

**Comment by tzach** [comment]
@syuu1228 ping

**Comment by tzach** [comment]
@syuu1228 any update?

**Comment by xhoong** [comment]
Hi, I'm running both online and offline install, but during `yum install scylla` it complain on the conflict of scylla-server and abrt. I'm running on CentOS 7.3.

**Comment by xhoong** [comment]
I have success in installing, one need to remove existing package of abrt before proceed. For offline install, you need to remove the abrt package and move all the abrt package out of your local install path. You will also need pyparsing and python-urwid package which was not included when you do yumdownloader for scylla.

Additionally, I have to take out openssl-devel package, turns out it only needs libcrypto from openssl-libs package. 

Hope it helps. Cheers.

**Comment by dpz3579** [comment]
@xhoong it works.
I did `yum remove abrt.x86_64`

and then installed it worked perfectly..
