### ISSUE TITLE
select count(*) from table not working 

### ISSUE THREAD

**Issue by alokgogate** [scylladb/scylla#3378]
Hello 

I have installed scylla db and when I do 
`select count(*) from abc`
or count(*) or count(1) from table I get timeout errors. Rest queries do seem to work

Any suggestion?

**Comment by dorlaor** [comment]
Count goes over the entire table. You should increase your timeout in order
to wait for the answer which is
a function of the amount of data you have and cluster speed

**Comment by tzach** [comment]
@alokgogate closing this since it's not a bug. Selecting over the entire DB and all nodes will take time.
As @dorlaor suggested, you can increase the client side timer, but it's a short-term solution. Running `select count` is an anti-pattern.
See #1385 for a possible enhancement to improve in this case.

**Comment by tzach** [comment]
The timeout you are getting is most likely from the client
If for example, you are using cqlsh, try using
```
cqlsh --request-timeout=2000
```

**Comment by LavishPatodi** [comment]
@tzach  thanks for your quick response it really helped.

**Comment by cc32d9** [comment]
But shouldn't it be quick if I specify the partition key in WHERE statement? So far it's timing out as well.

**Comment by avikivity** [comment]
How large is your partition?

**Comment by cc32d9** [comment]
@avikivity several gigabytes. I just opened #4484 for more details.

**Comment by avikivity** [comment]
It's not possible to count 1.6GB worth of data in a few seconds on a single core. Increase your timeouts.
