### ISSUE TITLE
Improve install-dependencies.sh for Debian and Ubuntu

### ISSUE THREAD

**Issue by argenet** [scylladb/scylla#3379]
Scylla version (or git commit hash): master (11940ca39e26bebcb67c074ea48da170836e75f9)

Currently, the `install-dependencies.sh` script does not contain/use information about supported versions of external packages used for building Scylla. Also, it doesn't install some packages (`thrift`, `antlr3`) and notifies the user on that:
```
echo antlr3 and thrift still missing - waiting for ppa
```

Our current logic of the `install-dependencies.sh` for Debian/Ubuntu should be improved in the following ways:

- Use ScyllaDB repositories to bring in supported versions of packages such as `thrift`, `antlr3`. It should be ScyllaDB PPA for Ubuntu (https://launchpad.net/~scylladb/+archive/ubuntu/ppa) and Debian packages (http://download.opensuse.org/repositories/home:/scylladb:/).
- Install the supported version of GCC as most distros use older versions by default
- Provide an example of command line parameters for `configure.py` to use third-party packages from Scylla repositories.

See ff055a291a3ce6eae6b7a8f1f67a62b89771f7fa where the same has been done for CentOS.

**Comment by bentsi** [comment]
I've succeeded to compile Scylla `branch-3.0` in Ubuntu 18.04 docker.
Run Ubuntu docker image:
`docker run -it --rm ubuntu:18.04 bash`
Inside the running container:
```
apt-get update
apt-get install -y sudo git software-properties-common
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys A874136B215467E8
sudo add-apt-repository ppa:scylladb/ppa
sudo apt-get update
git clone --recursive --branch branch-3.0 https://github.com/scylladb/scylla.git
git submodule update --init --recursive

sudo apt-get install -y python3-setuptools python3-all python3-all-dev debhelper \
 liblz4-dev libsnappy-dev libcrypto++-dev libjsoncpp-dev libaio-dev thrift-compiler \
 ragel ninja-build git libgnutls28-dev libhwloc-dev libnuma-dev libpciaccess-dev \
 xfslibs-dev python3-pyparsing libxml2-dev libsctp-dev python-urwid pciutils \
 libprotobuf-dev protobuf-compiler systemtap-sdt-dev cmake libssl-dev scylla-gcc73-g++-7 \
 scylla-libthrift010-dev scylla-antlr35-c++-dev scylla-libboost-program-options165-dev \
 scylla-libboost-filesystem165-dev scylla-libboost-system165-dev \
 scylla-libboost-thread165-dev scylla-libboost-test165-dev libsystemd-dev antlr3 \
 libyaml-cpp-dev

cd scylla
 ./configure.py --compiler /opt/scylladb/bin/g++-7  --cflags="-I/opt/scylladb/include" --ldflags="-L/opt/scylladb/lib/x86_64-linux-gnu" --mode=release --with=scylla
ninja -j 4
```

**Comment by avikivity** [comment]
Closing as this is not actionable. If you see a missing dependency, send a patch to fix it. Otherwise this bug will always be closed and reopened.
