### ISSUE TITLE
Redefine LCS 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#3380]
Quoting Avi:

>  I think we should redefine LCS from
> 
>     nr_sstables(level) = fan_out ^ level
> 
> to
> 
>    nr_sstables(level) = nr_sstables(level + 1) / fan_out
> 
> 
> This prevents an LCS pathology where we have 10 sstables in L1, 100 sstables in L2, and 100 sstables in L3, resulting in 2X space amplification instead of the expected 1.1X. The fact that space amplification depends on total size may be the reason that the backlog fluctuates.
> 
> The new definition also eliminates the problem of demotion.
> 

more in "[dev-int] backlog estimation for LeveledCompaction"

**Comment by nyh** [comment]
This the a dup of #2912 ?

**Comment by raphaelsc** [comment]
> This the a dup of #2912 ?

This issue also talks about a backlog issue which is a side effect of the SA issue affecting LCS, so let's keep it opened.

**Comment by avikivity** [comment]
Merged into #2912
