### ISSUE TITLE
dtest fail with sorted_tokens is empty in first_token_index

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#3382]
Scylla version (or git commit hash): 11940ca39e26bebcb67c074ea48da170836e75f9

update_cluster_layout_tests.py:TestUpdateClusterLayout.increment_decrement_counters_in_threads_nodes_restarted_test

```
ERROR 2018-04-24 19:03:17,414 [shard 1] token_metadata - sorted_tokens is empty in first_token_index!
```

**Comment by duarten** [comment]
This happens in many tests. I think it may be related to #3121.

**Comment by juliayakovlev** [comment]
I received same problem despite the #3121 is closed.
I ran dtest (materialized_views_test.py) on scylla master includes the commit that the #3121 is closed with:

[juliay@juliay scylla]$ git branch
* master
[juliay@juliay scylla]$ git log | grep 3c8ed25
commit 3c8ed255ace9575aca161e45f190cd2ba7224c1c

**Comment by juliayakovlev** [comment]
@slivne  I am not familiar with  increment_decrement_counters_in_threads_nodes_restarted_test test. I seems the question not for me

**Comment by roydahan** [comment]
It's weird, I see it's part of the dtest master run till July 2017 (mails from Jenkins), but I can't find any trace for it being part of scylla-tests file.

**Comment by slivne** [comment]
I ran the test manually 2 times and the issue does not occur - I have not seen this reported for a while - following the conclusion about the tests and why they are not run lets close the issue

tx @roydahan

**Comment by slivne** [comment]
on 2.3 this just happend on the last run
