### ISSUE TITLE
Use hinted handoff to "replay" missed consistency updates from base to view

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#3383]

**Comment by duarten** [comment]
I just realized we're missing dtests for this, are we not?

**Comment by psarna** [comment]
There are `stop_node_during_mv_insert_*_nodes` tests that may be kind of related, but true, we miss specific dtests. I'm not sure how to make a deterministic one without some kind of failure injection API though.

**Comment by duarten** [comment]
Dtests allow you to stop or disconnect nodes, which should be enough to test this.
