### ISSUE TITLE
materialized view doesn't work when partition column's name is case sensitive

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#3388]
If a materialized view is created when the base table's partition key column name is case-sensitive (wrapped in double-quotes), we get errors while using it:
```
CREATE TABLE tab ("FooBar" int PRIMARY KEY, b int, c int
CREATE MATERIALIZED VIEW myview as select * from tab where b is not null and "FooBar" is not null primary key (b, "FooBar"
INSERT INTO tab ("FooBar", b, c) VALUES (1, 2, 3)
```

The table is created fine, but the INSERT fails with the following line in the log
```
ERROR 2018-04-25 12:25:27,119 [shard 0] storage_proxy - exception during mutation write to 127.0.0.1: exceptions::invalid_request_exception (restriction 'foobar IS NOT null' unknown column foobar)
```

This bug also directly causes a bug in secondary-indexing when the table's partition key column name is case-sensitive. That bug is similar in symptoms to issue #3154, but not the same (the issue there was the name of the column being indexed).

**Comment by duarten** [comment]
`test_case_sensitivity` was supposed to cover this, but I guess it doesn't!

**Comment by nyh** [comment]
Hi, @duarten does that even test anything?
First of all, because none of the identifiers in that test are quoted, they are NOT actually case sensitive, and all should be folded to lowercase despite the fancy camel casing.
Second, even that folding isn't tested, because you always used the same camel casing and didn't even try to use "theClustering" on one line and "tHecLusTerinG" on another line to check that this folding works correctly.
Anyway, I wrote a new test to reproduce this issue, and now trying to fix it :-)

**Comment by duarten** [comment]
It's missing the quotes. If it was working, it wouldn't be passing :) 

No need for a new test unless it does something totally different, we should fix and add to the current one.

**Comment by nyh** [comment]
@duarten I have no idea what this test intended to test, so it's hard for me to "fix". In particular you do there weird things like renaming columns, and other stuff, which I'm not sure how it's even related to case sensitivity or why we want to retain any of this in test which never really tested what it was supposed to test ;-)

**Comment by duarten** [comment]
The test is supposed to test case sensitive columns work correctly, that data can be inserted and queried, and that case sensitive columns in views can be renamed. It's just the quotes that are missing.
