### ISSUE TITLE
scylla_setup sets scylla parameters that will fail the bootup

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#3397]
*Installation details*
Scylla version (or git commit hash): 1a9aaece3e38e0418d30a632140b3062e8d37bce

*Description* 
scylla_setup is missing the detection of the particular server limitations that require extra scylla parameters. For instance, if the server has a lot of CPUs but not enough RAM scylla should be restricted to a CPU set smaller than the total CPU set of the server in order to boot up.

We should think about all such restrictions we have and have them configurable via `scylla_setup`.

We should never allow the situation when parameters auto-configured by `scylla_setup` cause scylla to fail the boot.

**Comment by vladzcloudius** [comment]
@dor No, it wouldn't.
@tzach What would we like to do in this case? Print an informative message and disable the service? Detecting the problem is simple but choosing a "good" configuration is more complicated since there may be multiple options.

**Comment by tzach** [comment]
@vladzcloudius is it a duplicate of  #2808?

**Comment by vladzcloudius** [comment]
@tzach @dorlaor Looks like it. Closing...
