### ISSUE TITLE
ka tables are translated to la tables during nodetool refresh 

### ISSUE THREAD

**Issue by hagrid-the-developer** [scylladb/scylla#3399]
*Installation details*
Scylla version (or git commit hash):03c22ad52485089a942cbfd31167003090cf3903

Reported by @glommer:

*When we called nodetool refresh on a set of ka tables they were moved down as la.
This shouldn't happen. If we are loading from an existing format we should keep that format.
Nodetool refresh calls load_new_sstables in database.cc to upload the files.*

**Comment by tzach** [comment]
> When we called nodetool refresh on a set of ka tables they were moved down as la.
This shouldn't happen. If we are loading from an existing format we should keep that format.

Why is that? Doesn't it make sense to write to the "canonical" format?

**Comment by glommer** [comment]
I think this is fine - although I haven't verified again. In conversation with @slivne , there is a chance that we aren't changing the files -> they are compacted, and then the new files generated by compaction are in the new format (which is fine)

**Comment by slivne** [comment]
ok closing this issue
