### ISSUE TITLE
Secondary-Index default name may be different in Scylla than in Cassandra

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#3403]
By default, a secondary index created on table xyz for column abc will be called "xyz_abc_idx". There's hardly a reason to know this name except for one thing: You need to know this name to **drop** the index. If you didn't specify a name explicitly, you need to know this default name policy. It is the same in Cassandra and Scylla, so Cassandra CQL code will continue working. Except for one (fairly unusual) edge case - when the column name includes non-alpha-numeric characters, e.g., a space:

Neither Cassandra nor Scylla allow table names to contain non-alphanumeric characters, even when quoted. There is no good technical reason for this rule, but it is enforced nevertheless. Column names, however, do not have this limitation and may contain e.g., spaces (when quoted). When Cassandra builds the default index name, it wishes to have the index name follow the same rule as table names, and removes invalid characters from the default name. Scylla doesn't. The following code works on Cassandra, but not on Scylla:
```
        create table "TableName2" (abc int primary key, "Foo Bar" int)
        create index on "TableName2" ("Foo Bar")
        insert into "TableName2" (abc, "Foo Bar") VALUES (1, 2)
        select * from "TableName2" WHERE "Foo Bar" = 2"
        drop index "TableName2_FooBar_idx" // note no space
```
While in Scylla, the drop needs to be instead:
```
        drop index "TableName2_Foo Bar_idx" // note space
```
There's nothing inherently wrong with what Scylla does, it's just different from Cassandra. So it may, however unlikely this may be, break existing CQL scripts which try to drop an index with a default name when the column has a quoted name.

**Comment by nyh** [comment]
I'm adding a "security" tag because I worry that this can also become a security issue: If the indexed column name contains "/..", it may lead Scylla to write outside the intended directory.

If this is a real problem, then besides removing "/" characters (among other things) when building the index name - as suggested above - we should add additional layers of security, i.e. the table creation code should refuse to create a table whose name contains illegal characters (slash or null).

**Comment by nyh** [comment]
I just wrote a test that verified that this is a **real** bug - anyone with CQL index-creation capabilities can use it to crash Scylla or create a subdirectory anywhere in the filesystem. This doesn't have a huge security impact, but should be fixed nontheless.

The only documentation I could find on the default index name is in the Scylla repository, `docs/design-notes/secondary_index.md`, so that should be updated as well.

By the way, the document https://docs.scylladb.com/getting-started/secondary-indexes/ claims that index name is in re('[a-zA-Z_0-9]+'), so let's enforce the default one to match this too.

**Comment by nyh** [comment]
By the fact that "/some/nonexistent/dir/../../../the/real/dir" even works is very curious. Unix or Linux don't allow this - ".." isn't used on strings, it only works in existing directories. I guess one of the Boost libraries we use for filesystem access invented this broken behavior :-(

**Comment by avikivity** [comment]
Minor, not backporting.
