### ISSUE TITLE
Support for secondary-index of partition-key column

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#3404]
When there is just one partition key column, "create index" for this column is forbidden by Scylla, and by Cassandra, because such an index is not needed - the column is already the partition key.

However, when there are multiple partition key columns (a.k.a. a composite partition key), it does make sense to add an index for each individual partition key column, and Cassandra does allow this. It appears that Scylla currently crashes on this case:
```
        create table cf (p1 int, p2 int, a int, primary key ((p1, p2)))
        create index on cf (p1)
```
The result is:
```
secondary_index_test: schema.cc:300: schema::schema(const schema::raw_schema&, std::experimental::fundamentals_v1::optional<raw_view_info>): Assertion `!def.id || def.id == id - column_offset(def.kind)' failed.
```

**Comment by ndelvalle** [comment]
@nyh Is this going to be supported in the future? Or is not allowed?
