### ISSUE TITLE
Secondary index gives wrong results on table with multiple clustering columns

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#3405]
I created a table with 6 columns: two partition-key columns, two clustering-key columns, and two regular columns. I then indexed all 6 columns, and searched using them.

The search results over the two partition key columns, and the *first* clustering key column, were correct. But the search results over the *second* clustering key column, as well as on either of the two regular columns, were incorrect (sometimes more results than expected, sometimes less). I guess we have a secondary-index bug in this case?

**Comment by nyh** [comment]
If I understand correctly now, the bug is limited to the case where we have a composite clustering key (multiple clustering key columns), but will be fairly hard to fix:

**`indexed_table_select_statement::do_execute()`** does the indexed search: It first calls `indexed_table_select_statement::find_index_partition_ranges()` which executes the query on the index view, to get a list of matching **primary keys**. It then needs to find the rows of the base table matching those primary keys. What it actually does is to take the partition keys from those found primary keys to determine which partitions need to be fetched from the base table. However, which **clustering rows** do we need to read in each partition

IIUC, the current code has two cases (see `indexed_table_select_statement::find_index_partition_ranges()` calling `make_partition_slice()`):

1. If the original query is restricted by the clustering key - i.e., we are searching ("where x=2") on an index clustering column x - we use that as the clustering slice to take from each partition (same for all partitions).
2. If the original query is not restricted by the clustering key, we take the entire partitions.

But both are the wrong thing to do when we have multiple clustering columns:

1. When the clustering key is composite, taking the second clustering column (as we had in the original problem reported) as a clustering prefix is wrong, and will not match anything. This is why we got 0 results for searches on the second clustering key.
2. When the clustering key is composite and we search on a regular column, we will return all rows from each partition. This is wrong - the original query on the index returned not just partition keys, it also returned full clustering keys, and we only need to find rows which match those clustering keys - not everything in those partitions. This is why we got more results than expected in some of these searches for the regular columns.

The original sin is the attempt in `indexed_table_select_statement::do_execute()` to have a list of partitions we need to read from the base table ("partition_ranges") and then a single partition slice (created by make_partition_ranges()) for all of them. When the clustering key is composite we may (if the search is on one of the clustering compoents) need a different clustering key subset for each partition.

I think we can fix this by two cases:
1. If the base table has 0 or 1 clustering key components, we can do what we do now.
1. If there are >=2 clustering key components and the search is on the first one, what we do now (take the expected first column value as a clustering-prefix for the slice, same one for all partitions) is fine.
2. If there are >=2 clustering key components and the search is on second or later one, make_partition_slice() cannot create an efficient slice for the second component having a certain value. Instead, it should probably give an unbounded slice for all the partitions, to read the entire partitions, but as a last pass trim from the results any row which doesn't match the given restriction (note that such trimming is also useful in case we have inconsistent data in the index). 
3. If there are >=2 clustering key components but the search is not on one of them, we need to read a specific clustering key from each partition, and in some cases (long partitions) doing that may be more efficient than reading the entire partition. But it seems we cannot do such a search (different clustering key for each partition key) in our current query API, and if we can't fix that, we need to fall back to option 2, i.e., read entire partitions and trim those which don't match the given restriction on the regular column.

**Comment by nyh** [comment]
@slivne I'm working on this issue, already submitted a test, and have a partial solution which still is missing an important part (filtering of the result set, see also #2025).

**Comment by nyh** [comment]
Here is a summary of this issue and what it would take to fix it which I sent to the mailing list:

In secondary index search, we have two steps: First, use the index table to find a list of **primary keys** matching the query. Second, read the rows matching these primary keys from the base table and return the selected columns.

The second step is easy when the base table's primary key contains just **partition** columns - in that case, we can read exactly the rows which we need in those partitions, and we're done.

It's also easy (but somewhat harder to explain) when the base table's primary key contains **one clustering column**, and the search is on it; In that case, we can take the list of matching partitions *sliced* by a clustering key prefix. This case also works correctly in the existing code.

But, everything falls apart once you have clustering columns and search a regular column, or if you search the second or later clustering column. In those cases, the first phase returns a list of primary keys which includes both partition and clustering components. We do not have an API to read only these rows from disk. Our existing request API only allows us to read entire partitions, or many partition with the same set of clustering range in each partition.

We have two options how to fix this last case:

1. Add a new query function which given a list of rows' primary keys, reads only these rows (and not entire partitions, etc.). Only SI will use this new function. @avikivity recommends that we do that, because for a low number of results, the work is proportional to the number of results, and doesn't explode if we have huge partitions. We can even start with an inefficient implementation of this function (e.g., read each row by a separate query!) and improve it later.

2. Add a facility of filtering the result of reading entire paritions and leave only rows which match the given restrictions (i.e., the requested value of the search column).  This will be useful for SI, but also in the future for supporting "ALLOW FILTERING" (issue #2025). But this approach will be inefficient when we have very large partitions with many rows, but the search results are just a few rows.

Earlier I was leaning towards approach 2 (especially since it would also help solving #2025) but following Avi's advice, I'll switch to approach 1 instead.

**Comment by eyalgutkind** [comment]
See similar issue when having a single clustering key in the table,
The query on the clustering key secondary index return an empty results.
Here is the use case:
```
cqlsh> CREATE TABLE try2index.mytable ( colm1 int, colm2 int, colm3 int, PRIMARY KEY (colm1, colm2));

cqlsh> CREATE INDEX on try2index.mytable (colm2);
cqlsh> INSERT INTO try2index.mytable (colm1 , colm2 , colm3 ) VALUES ( 1, 2, 3);
cqlsh> INSERT INTO try2index.mytable (colm1 , colm2 , colm3 ) VALUES ( 2, 3, 4);
cqlsh> INSERT INTO try2index.mytable (colm1 , colm2 , colm3 ) VALUES ( 3, 4, 5);

cqlsh> SELECT * FROM try2index.mytable ;

 colm1 | colm2 | colm3
-------+-------+-------
     1 |     2 |     3
     2 |     3 |     4
     3 |     4 |     5

(3 rows)
cqlsh> SELECT * FROM try2index.mytable WHERE colm1=1;

 colm1 | colm2 | colm3
-------+-------+-------
     1 |     2 |     3

(1 rows)
cqlsh> SELECT * FROM try2index.mytable WHERE colm2=2;

 colm1 | colm2 | colm3
-------+-------+-------

(0 rows)
cqlsh>

```

**Comment by nyh** [comment]
@eyalgutkind yes, I think it's the same bug. I've sent a patch series fixing this bug and closing this issue. When it's committed, please retest your scenario.

**Comment by Thiamath** [comment]
I'm still having [this issue](https://github.com/scylladb/scylla/issues/3405#issuecomment-389724323) on v3.0.10
