### ISSUE TITLE
testing the ticket process

### ISSUE THREAD

**Issue by lauranovich** [scylladb/scylla#3407]
Testing the ticket process
UUID 30a93e1a-d505-4f42-9556-8e7d9878355d

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by duarten** [comment]
@lauranovich Can this be closed?
