### ISSUE TITLE
Can't find a column family with UUID abc...

### ISSUE THREAD

**Issue by avnerbarr** [scylladb/scylla#3409]
Scylla version (or git commit hash):
2.1.2
Cluster size: 3
CentOS

Getting this error:

```
storage_proxy - Exception when communicating with xxxx . Can't find a column family with UUID abc...
```

I've seen it once in a production environment, but it happens relatively frequently when running through docker.

**Comment by tzach** [comment]
@avnerbarr can you please attach Scylla log?
What is the CQL command you using?

**Comment by nyh** [comment]
Could this be https://github.com/scylladb/scylla/issues/2852? @tzach do you know if its fix ever backported to 2.1 (it seems to me the answer is no, but maybe I'm looking wrong)?
What do you see in the log a few lines before the exception?

**Comment by avikivity** [comment]
This can happen if you create tables dynamically. It can take time for the schema to propagate. Is this the case?

@avnerbarr please describe your scenario in detail.

**Comment by avnerbarr** [comment]
Yes, the tables are created dynamically in some cases (in production environment). 

But in this particular case (the last time I saw it) the table was generated using a script like this (through docker):

```
create_tables.txt (configuration file)
...
CREATE KEYSPACE IF NOT EXISTS data_feeds WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

...

SCYLLA_SHELL_COMMANDS=`cat create_tables.txt`
docker exec -i scylla_master /bin/sh -c "echo \"$SCYLLA_SHELL_COMMANDS\" | cqlsh"
```

**Comment by avikivity** [comment]
In that case it is normal to have some propagation delay for the schema.

**Comment by avnerbarr** [comment]
So what is the action to take?

**Comment by avikivity** [comment]
Wait for a few seconds for the schema to propagate, or tolerate the error, or check on all nodes before writing.

**Comment by tzach** [comment]
Closing this assuming this is a race condition between schema propagation and writing to the new schema
@avnerbarr, please reopen if you suspect this is not the case.

**Comment by avnerbarr** [comment]
I'm getting this error again on tables that have already been created. Not a propogation issue

**Comment by avnerbarr** [comment]
The messaages ran for more than an hour while nothing was running against this keyspace

**Comment by avnerbarr** [comment]
I don't know if it is coincidence or otherwise, but I changed consistency level to "ALL" and seems that this issue didn't appear.

**Comment by avnerbarr** [comment]
Ok I take it back. Again seeing this issue. Must have been a coincidence that it stopped for a certain period of time. Unrelated to the consistency level

**Comment by avnerbarr** [comment]
I'm getting tons of timeouts and in the logs 

```
Aug 02 13:21:24 scylladb-cluster-1-srv-6c922fc.use.dynamicyield.com scylla[30594]:  [shard 0] schema_tables - Altering data_feeds_migration_delete_this_eventually.mids_8765534_6374_0 id=f3a60de0-9656-11e8-8766-000000000007 version=b9a44f94-d283-3371-807e-0b05186a1b51
Aug 02 13:21:24 scylladb-cluster-1-srv-6c922fc.use.dynamicyield.com scylla[30594]:  [shard 0] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/system_schema-keyspaces-ka-536-Data.db:level=0, ]. 21275 byt
Aug 02 13:21:24 scylladb-cluster-1-srv-6c922fc.use.dynamicyield.com scylla[30594]:  [shard 0] migration_manager - Failed to update definitions from 172.30.7.55:5: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID f3a60de0-9656-11e8-8766
Aug 02 13:21:25 scylladb-cluster-1-srv-6c922fc.use.dynamicyield.com scylla[30594]:  [shard 0] database - Schema version changed to 07fce60c-07c1-38a9-a126-abc6f8c0e529
```

**Comment by avikivity** [comment]
@avnerbarr this happens when you run DDL commands creating the same table from multiple clients in parallel. DDL operations are not synchronized, so you created two versions of the same table.

Is it possible you are doing that?

**Comment by avnerbarr** [comment]
Yes and no in the sense that the table already exists so it isn't being created in parallel

But since jobs are running from spark there could be many "create table if not exists" statements.

Currently can't run any spark jobs successfully. all of them are timing out.
