### ISSUE TITLE
Real time notifications

### ISSUE THREAD

**Issue by Extarys** [scylladb/scylla#3411]
*Installation details*
Scylla version (or git commit hash): Latest docker image
Cluster size: 3 local

I'm trying to find a scallable database that can offer something to create live events. Notifications, chat, etc. Scylla advertise itself as realtime.

The Scylla guide is lacking a little I think since I never used cassandra. Even their docs is incomplete.

Im using rhe cassandra-driver for nodejs.

Any thoughts on that? Thanks for your help.

**Comment by duarten** [comment]
Please use the mailing list to ask questions, not the bug tracker.

**Comment by duarten** [comment]
I'm an automated bot!

The [contributing guidelines](https://github.com/scylladb/scylla/blob/master/CONTRIBUTING.md) should have all the necessary info.
