### ISSUE TITLE
Latency problems with Scylla 2.1.2

### ISSUE THREAD

**Issue by avnerbarr** [scylladb/scylla#3412]
Scylla version (or git commit hash): 2.1.2-0.20180417.87cb8a1fa
Cluster size: 3 nodes @ i.x3large 4 Core 32Gig
Centos

I've uploaded prometheus data with UUID d264af01-4028-45ef-9634-6669089cd40d per instructions [here](http://docs.scylladb.com/operating-scylla/troubleshooting/report_scylla_problem/)

We are peaking at 30-40K read requests (close to 0 writes ops in some cases)
We experience latency problems and they can appear before the peak of 30-40K read requests. 

Each partition is returning a single row (i.e. each query returns a single row)
Partition size is small , around ~1k 

Most queries are "hits" for existing partitions.

All queries are identical, i.e. reading from the same table and columns (only the primary key varies per request)

The key space is defined at replication factor 3 (on all nodes)

The read query is configured at "single node" 

There is one client connection per process and it is configured at 4 connections per host, (1 connection per core per host node per @glommer  suggestion in slack channel ). 

```
const client = new cassandra.Client({
    contactPoints: [program.node],
    pooling: {
        coreConnectionsPerHost: {
            [distance.local]: coresPerNode,
            [distance.remote]: coresPerNode
        }
    }
});
```

I've played with concurrent request count , usually getting best results at concurrency 100-200.

**Comment by avnerbarr** [comment]
Note that the prometheus data is a small snapshot from yesterday, Please check around 18:00

**Comment by tomer-sandler** [comment]
@avnerbarr what is the consistency level for this read query? assuming it is not local_one, than it might be going to your remote DC. Can you you try and perform the tracing and slow query procedures described [here](http://docs.scylladb.com/using-scylla/tracing/), and send us the info?

**Comment by slivne** [comment]
@avnerbarr - I think you moved to bigger nodes and are also running the 2.2-mv version - is there still an issue. if so please post here.

If not we will close the issue

**Comment by tzach** [comment]
Closing as we do not have enough info.
@avnerbarr please reopen this issue, or a new one once you have more data.
