### ISSUE TITLE
Don't count MV view replica writes as user writes

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3416]
View replica writes are performed with CL=ONE (and RF=1 + pending_endpoints.size()), which are counted towards the user write metrics (foreground writes and background writes). This shouldn't be the case, since view replicas writes are not in the user request path.

The view replica writes are accounted separately in the view-specific metrics (#3385).

We can leverage the `db::write_type` argument to have the `storage_proxy` not count those  view replica writes.

**Comment by nyh** [comment]
Yes, the MV code (`mutate_MV()`) already passes a different write type - `db::write_type::VIEW` - which can be used to differentiate these writes.
