### ISSUE TITLE
Feature detection failure after failed startup

### ISSUE THREAD

**Issue by EmpireJones** [scylladb/scylla#3425]
*Installation details*
Scylla version (or git commit hash): 2.1.2
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): kubernetes/docker image, coreos host

I believe this is the second time that this has happened to me. If a cluster is created in a state in which NOFILE rlimit is not set high enough, scylla refuses to start (this is as expected). Once that is resolved and the nodes are restarted, I get the following error when creating a table:
InvalidRequest: Error from server: code=2200 [Invalid query] message="Counter support is not enabled"

Note that this counter no longer requires the experimental flag, which indicates that the feature detection in general isn't working in that scenario.

Nuking the drives and recreating the cluster fixes this issue.

I can't guarentee that the NOFILE issue is for sure related, but I believe the last time I ran into this NOFILE limit error, I ran into the feature detection error too.

**Comment by tzach** [comment]
@asias any idea what might cause this issue? 
@EmpireJones was this cluster upgrade from an older version of Scylla, when Counter was not available by default?

**Comment by EmpireJones** [comment]
@tzach If any upgrade did occur, it would have just been from 2.1.0 or 2.1.1. Also, I previously experienced the "Counter support is not enabled" behavior on one of those earlier versions.

**Comment by asias** [comment]
Did you see logs like "Feature COUNTERS is enabled" on all the nodes?
The cluster won't start using the counter if any of the node does not support counter.

**Comment by EmpireJones** [comment]
@asias - in what case would a node not support counters? All of the nodes were at the same version.

**Comment by asias** [comment]
Hello @EmpireJones, if the oldest version the nodes ever runs was 2.1.0 or 2.1.1, then COUNTERS feature is supposed to be supposed by all nodes, even without giving the --experimental == true flag. 

I checked the code, 2.1.0 and 2.1.1 has COUNTERS_FEATURE supported. 

Next time, you see the same error. Take a look at the scylla log, to see if 'Feature COUNTERS is enabled' is in the log on all nodes. 

@pdziepak Do we have other places that can trigger the following exception:

```
$ git grep  'Counter support is not enabled'
cql3/statements/create_table_statement.cc:211:            throw exceptions::invalid_request_exception("Counter support is not enabled");
```

**Comment by slivne** [comment]
closing this if there is additional info we can reopen
