### ISSUE TITLE
std::bad::alloc

### ISSUE THREAD

**Issue by krishnaod** [scylladb/scylla#3426]
*Installation details*
Scylla version (or git commit hash): 2.0.3
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.4.1708

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): Dedicated VM
Hardware: sockets= cores= hyperthreading= memory= 48 CPU
Disks: (SSD/HDD, count): HDD

May 12 11:03:44 37cassandradb scylla: [shard 19] gossip - Fail to handle GOSSIP_DIGEST_SYN: std::bad_alloc (std::bad_alloc)
May 12 11:03:45 37cassandradb scylla: [shard 13] seastar - Exceptional future ignored: std::bad_alloc (std::bad_alloc), backtrace: 0x4f07c3, 0x4f0821, 0x166b0a3, 0x166c9bd, 0x4ed3ef, 0x540f1a, 0x5427c0, 0x59b44d, 0x7f3c1ec91e24, 0x7f3c1e9bf34c
May 12 11:03:45 37cassandradb scylla: [shard 19] gossip - Fail to handle GOSSIP_DIGEST_SYN: std::bad_alloc (std::bad_alloc)

**Comment by argenet** [comment]
Hi @krishnaod,

Can you please add the information about how much RAM is available on cluster nodes?

**Comment by krishnaod** [comment]
I was inserting 80 K records, every 5 min (router data). Preparing the reports. Keeping data for 10 days and drop tables after 10 days.
Compaction Strategy: NULL
Things were good till one week.
The total data was 900GB approx (300GB on each node)
Cluster size: 3

**Comment by slivne** [comment]
how many tables ?

did it happen during a drop of tables ?

can you share additional logs /promethues data

**Comment by krishnaod** [comment]
Tables: 240
It happen during massive inserts.
I don't have promethes at the moment.

**Comment by tzach** [comment]
@krishnaod it is very hard to understand without metric data from Prometheus
Alternatively, we can try to reproduce with more details on your setup, schema.

**Comment by slivne** [comment]
closing this issue till additional information will be provided

@krishnaod - if you can provide additional information on this pleas epost and we will reopen and continue
