### ISSUE TITLE
Support sending mutation_fragment over RPC

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#3431]
We need this for new scylla streaming and row level repair.

For example, the streaming data flow is:

on the sender side flat mutation reader generates mutation_fragment -> serialization of mutation_fragment -> send over RPC -> on the receiver side deserialization mutation_fragment -> write the mutation_fragment.

**Comment by slivne** [comment]
related to new streaming

**Comment by pdziepak** [comment]
Implemented in 3a4d11d3741f049c27574d4e75c4f148c70d7621.
