### ISSUE TITLE
raid0.devices_discard_performance kernel parameter causes raid0 module load failure

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#3437]
*Installation details*
Scylla version (or git commit hash): 2.0+
OS: RHEL / CentOS

Newer RHEL kernels, as well as non-RHEL kernels, don't have the `raid0.devices_discard_performance` module parameter. The kernel refuses to load the module, so we don't have access to the RAID array.

**Comment by slivne** [comment]
dup #3427

**Comment by syuu1228** [comment]
@avikivity should we drop the parameter unconditionally, or we should keep it for older kernel (and try to prevent applying to newer kernel)?

**Comment by avikivity** [comment]
@syuu1228 it would be better to apply the parameter conditionally, but it is very hard. The installed kernel need not be the same as the running kernel (we can have old and new kernel co-installed) and there is no way to make the modprobe configuration file conditional.

So I think the best we can do is remove the parameter and ask everyone who is impacted to upgrade the kernel (which delivers better discard performance anyway).
