### ISSUE TITLE
scylla_io_setup(iotune) fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#3448]
*Installation details*
Scylla version (or git commit hash): c053275a480d0c6a5038ae73c16c32dace1042a1
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 18.04LTS

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical
Hardware: i7 6950X / 64GB RAM
Disks: (SSD/HDD, count) Samsung SSD SM951

It seems IO measurement itself is succeed, but exception occurred while writing configuration file:  
```
INFO  2018-05-21 18:36:27,959 [shard 0] iotune - /var/lib/scylla/data passed sanity checks
Measuring sequential write bandwidth: 1234 MB/s
Measuring sequential read bandwidth: 1902 MB/s
Measuring random write IOPS: 87334 IOPS
Measuring random read IOPS: 301666 IOPS
Recommended --num-io-queues: 12
ERROR 2018-05-21 18:37:09,891 [shard 0] iotune - Exception when writing configuration file: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::bad_any_cast> > (boost::bad_any_cast: failed conversion using boost::any_cast).
Please add the above values manually to your seastar command line.
```

**Comment by slivne** [comment]
@syuu1228 - is this consistently failing - if we try this on gce will it reproduce - it would help if we can get a reproducer env

**Comment by syuu1228** [comment]
@slivne Tested on recent build of master and 2.3, but couldn't reproduce on same machine, so close the issue now.
