### ISSUE TITLE
Scylla fails to boot due to inexistence of /var/lib/scylla/hints

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#3451]
*Installation details*
Scylla version (or git commit hash): 62c3b4c429c365273ce8d1086616feb994fcc6a2 
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Regression may have been introduced in this series 4b2fd8d6f28e0eff936980ddac1a3efb8c4ae755

**Comment by psarna** [comment]
Yeah, creating `/var/lib/scylla/hints` should be added to install.sh and some docs, I'll make a patch

**Comment by raphaelsc** [comment]
Actually we should have a internal way of dealing with it when running in developer mode. Like creating a directory ourselves in the parent directory of user-specified data directory

**Comment by glommer** [comment]
we create the commitlog and data directories inside scylla.

Hints should be no different.

We still want to install them from packaging, because tools that run before
Scylla may check for them. But the safe bet is to do both.

**Comment by psarna** [comment]
oh, my bad... we do create them with `hinted_handoff` explicitly enabled, but not when it's only enabled because of materialized views... will fix.
