### ISSUE TITLE
Ec2MultiRegionSnitch does not (always) honor prefer _local 

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#3454]
*Installation details*
Scylla version (or git commit hash): 2.0.4
Cluster size: 2 dcs 3 nodes each with TLS enabled

I expect to see connections on local address only between nodes in the same DC in netstat, but netstat shows only some (very low number of) connections use local address and all others continue to be on global one. Note that test setup is with TLS. may it has something to do with it.

**Comment by vladzcloudius** [comment]
For the record, this has been broken since the commit 926ce145dbc0a715c47461ad9dae3c321dcafc6f

```
locator::i_endpoint_snitch_base: move _gossip_started to the base class  

Move the member and add an access method. This is needed in order to be able to access this state using snitch_ptr handle.  

This also allows to get rid of ec2_multi_region_snitch::_helper_added member since it duplicates _gossip_started semantics.  

Signed-off-by: Vlad Zolotarov <vladz@cloudius-systems.com>
```
