### ISSUE TITLE
Coordinator timeout

### ISSUE THREAD

**Issue by aerskine** [scylladb/scylla#3455]
*Installation details*
Scylla version (or git commit hash):  2.1.1-0.20180325.cce455b1f
Cluster size: 3 machines, 12 cores
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL 7.4

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): Physical
Hardware: sockets= cores=48 hyperthreading= memory=64GB
Disks: (SSD/HDD, count) 2x SSD in RAID1

Files uploaded to: 6a5b4231-80be-4476-9114-7d78fc3c3a6e/prometheus_data.tar.gz

**Comment by slivne** [comment]
@aerskine - we need more info to help

**Comment by tzach** [comment]
Closing since we did not get more info. @aerskine please reopen once you can provide the data
