### ISSUE TITLE
TWCS  timestamp overlap

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#3458]
*Installation details*
Scylla version (or git commit hash): scylla-enterprise-tools-core-2018.1.0-0.20180425.5ce22ad.el7.centos.noarch
Cluster size: 1 node

* table config
    AND compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': '1', 'compaction_window_unit': 'DAYS'}
    AND compression = {'chunk_length_kb': '64', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 259200
    AND gc_grace_seconds = 0

I am testing scylladb with Time Window Compaction Strategy
Looking closely at timestamps, we can see that the oldest SSTable has a minimum timestamp on 05/19, which overlaps with SSTable test-ka-2904-Data.db
Why does timestamp overlap occur? Is this normal?
Since we are testing with one node, there is no read repair, anti-entropy repair

for f in *Data.db; do meta=$(sudo sstablemetadata $f); echo -e "Max:" $(date --date=@$(echo "$meta" | grep Maximum\ time | cut -d" "  -f3| cut -c 1-10) '+%m/%d/%Y %H:%M:%S') "Min:" $(date --date=@$(echo "$meta" | grep Minimum\ time | cut -d" "  -f3| cut -c 1-10) '+%m/%d/%Y %H:%M:%S') $(echo "$meta" | grep droppable) ' \t ' $(ls -lh $f | awk '{print $5" "$6" "$7" "$8" "$9}'); done | sort		

Max: 05/20/2018 08:39:54 Min: **05/19/2018** 08:51:54 Estimated droppable tombstones: 0.7136295292748591      11G May 20 09:09 test-ka-1072-Data.db
Max: 05/20/2018 08:45:47 Min: 05/19/2018 08:54:05 Estimated droppable tombstones: 0.7147768286165789      11G May 20 09:13 test-ka-1044-Data.db
Max: 05/20/2018 08:50:56 Min: 05/19/2018 08:49:02 Estimated droppable tombstones: 0.7199997700152891      12G May 20 09:19 test-ka-1115-Data.db
Max: 05/21/2018 08:43:21 Min: 05/20/2018 08:50:56 Estimated droppable tombstones: 0.7153369887791089      12G May 21 09:11 test-ka-1763-Data.db
Max: 05/21/2018 08:45:23 Min: 05/20/2018 08:45:47 Estimated droppable tombstones: 0.7188161590065993      12G May 21 09:13 test-ka-1668-Data.db
Max: 05/21/2018 08:48:05 Min: 05/20/2018 08:49:03 Estimated droppable tombstones: 0.7185609084666112      12G May 21 09:16 test-ka-1675-Data.db
Max: 05/21/2018 08:48:07 Min: 05/20/2018 08:39:54 Estimated droppable tombstones: 0.722983317880978       11G May 21 09:17 test-ka-1654-Data.db
Max: 05/21/2018 08:48:46 Min: 05/20/2018 08:49:47 Estimated droppable tombstones: 0.7192467988395198      12G May 21 09:18 test-ka-1736-Data.db
Max: 05/21/2018 08:59:21 Min: 05/20/2018 08:47:18 Estimated droppable tombstones: 0.7252565030534253      12G May 21 09:28 test-ka-1683-Data.db
Max: 05/22/2018 08:42:55 Min: 05/21/2018 08:43:21 Estimated droppable tombstones: 0.028021770197376103            12G May 22 09:11 test-ka-2411-Data.db
Max: 05/22/2018 08:43:15 Min: 05/21/2018 08:59:21 Estimated droppable tombstones: 0.0193274533873123      11G May 22 09:11 test-ka-2289-Data.db
Max: 05/22/2018 08:55:31 Min: 05/21/2018 08:48:07 Estimated droppable tombstones: 0.02295341289881877     12G May 22 09:23 test-ka-2266-Data.db
Max: 05/22/2018 08:58:33 Min: 05/21/2018 08:48:05 Estimated droppable tombstones: 0.02340034728384699     12G May 22 09:26 test-ka-2323-Data.db
Max: 05/22/2018 08:59:18 Min: 05/21/2018 08:45:23 Estimated droppable tombstones: 0.025553746018195742            12G May 22 09:28 test-ka-2292-Data.db
Max: 05/22/2018 08:59:54 Min: 05/21/2018 08:48:46 Estimated droppable tombstones: 0.02286139788979944     11G May 22 09:28 test-ka-2342-Data.db
Max: 05/23/2018 08:42:45 Min: 05/19/2018 08:49:02 Estimated droppable tombstones: 0.0033867571541399064           12G May 23 09:13 test-ka-3041-Data.db
Max: 05/23/2018 08:49:12 Min: 05/22/2018 08:43:15 Estimated droppable tombstones: 0.0     11G May 23 09:17 test-ka-2901-Data.db
Max: 05/23/2018 08:50:48 Min: **05/19/2018** 08:54:05 Estimated droppable tombstones: 0.0021456454530204704           11G May 23 09:19 test-ka-2904-Data.db
Max: 05/23/2018 08:51:47 Min: 05/22/2018 08:58:33 Estimated droppable tombstones: 0.0     12G May 23 09:21 test-ka-2971-Data.db
Max: 05/23/2018 08:57:10 Min: 05/22/2018 08:59:54 Estimated droppable tombstones: 0.0     12G May 23 09:26 test-ka-2954-Data.db
Max: 05/23/2018 08:59:23 Min: 05/19/2018 08:51:54 Estimated droppable tombstones: 0.002440072309983679            12G May 23 09:27 test-ka-2920-Data.db

**Comment by raphaelsc** [comment]
On Wed, May 23, 2018 at 11:21 PM, Junghyun Park <notifications@github.com>
wrote:

> *Installation details*
> Scylla version (or git commit hash): scylla-enterprise-tools-core-
> 2018.1.0-0.20180425.5ce22ad.el7.centos.noarch
> Cluster size: 1 node
>
>    - table config
>    AND compaction = {'class': 'TimeWindowCompactionStrategy',
>    'compaction_window_size': '1', 'compaction_window_unit': 'DAYS'}
>    AND compression = {'chunk_length_kb': '64', 'sstable_compression': '
>    org.apache.cassandra.io.compress.LZ4Compressor'}
>    AND crc_check_chance = 1.0
>    AND dclocal_read_repair_chance = 0.0
>    AND default_time_to_live = 259200
>    AND gc_grace_seconds = 0
>
> I am testing scylladb with Time Window Compaction Strategy
> Looking closely at timestamps, we can see that the oldest SSTable has a
> minimum timestamp on 05/19, which overlaps with SSTable test-ka-2904-Data.db
> Why does timestamp overlap occur? Is this normal?
>
Depends. A sstable is bound to a time window based on its maximum
timestamp. That's why TWCS decided not to merge 2904 with those old
sstables which time range overlap. Is the client the one providing the
server with timestamps? I could see this problem happening either with
repair (where old and new data can be mixed) or also user application
mixing old and new data somehow.

The good news is that we plan to fix this by segregating data based on its
age, you can follow its progress here:
https://github.com/scylladb/scylla/issues/2687 (no ETA yet). I plan to work
on it myself.

**Comment by infordb** [comment]
@raphaelsc 
We used one client  for the same server as scylla, and the timestamp was provided by the client.
there was no read repair, anti-entropy repair, etc
I think our test case should not cause timestamp overlap.

**Comment by infordb** [comment]
@raphaelsc 
We are using the dfault setting. may be microsecond-precision timestamp
https://docs.datastax.com/en/developer/java-driver/3.0/manual/query_timestamps/

**Comment by slivne** [comment]
- how many shards - the ssatbles can belong to different shards - in which case its clear why they can overlap - they hold different data.

**Comment by infordb** [comment]
@slivne 
 we set compaction_window_size': '1', 'compaction_window_unit': 'DAYS'
  It is strange that such a long time window(4day) is made.
    
Max: 05/23/2018 08:50:48 
Min: 05/19/2018 08:54:05 
Estimated droppable tombstones: 0.0021456454530204704 11G May 23 09:19 test-ka-2904-Data.db

**Comment by denesb** [comment]
#2687 was merged. Is this issue still relevant?

**Comment by raphaelsc** [comment]
closing it as #2687 is fixed.
