### ISSUE TITLE
NoHostAvailable:

### ISSUE THREAD

**Issue by jkdntc** [scylladb/scylla#3460]
*Installation details*
Scylla version (or git commit hash):Scylla version 2.1.3-0.20180501.8e33e80
Cluster size:5
OS (RHEL/CentOS/Ubuntu/AWS AMI):Linux version 4.4.0-127-generic (buildd@lcy01-amd64-023) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) ) #153-Ubuntu SMP Sat May 19 10:58:46 UTC 2018

Platform (physical/VM/cloud instance type/docker): KVM
Hardware: sockets= cores=4 hyperthreading= memory=16G
Disks: HDD

$ nodetool status
Datacenter: datacenter1

> =======================

Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  192.168.0.14  1.22 MB    256          ?       aa9513f2-d0f9-4058-b5f3-6c4c5fb2bf27  rack1
DN  192.168.0.15  1.02 MB    256          ?       2f1c8ec3-1b5f-4526-829f-a162677751b6  rack1
UN  192.168.0.16  955.37 KB  256          ?       c52e46a5-9ed1-4db0-a535-57f7c43fe516  rack1
UN  192.168.0.17  954.85 KB  256          ?       76a179e7-3dcf-4878-90c8-f4939aa3e5a6  rack1
UN  192.168.0.18  963.21 KB  256          ?       eb82b361-e4fe-4ed1-82ad-1fd3dbef9451  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless

cqlsh> CONSISTENCY ONE ;
Consistency level set to ONE.
cqlsh> select * from mapping.test ;
NoHostAvailable:

table DDL：

CREATE KEYSPACE mapping WITH replication = { 
  'class': 'SimpleStrategy',
  'replication_factor': '1'
};

CREATE TABLE mapping.test (
  rmid text,  
  uid text, 
  last_access timestamp,
  PRIMARY KEY (uid, last_access)
) WITH CLUSTERING ORDER BY (last_access DESC) AND bloom_filter_fp_chance = 0.01 
AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'};

scylla.yml:
cluster_name: 'Mapping Cluster'
num_tokens: 256
data_file_directories:
    - /data1/scylla/data
commitlog_directory: /data1/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 16
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "192.168.0.14, 192.168.0.15, 192.168.0.16, 192.168.0.17, 192.168.0.18"
listen_address: 192.168.0.14
native_transport_port: 9042
read_request_timeout_in_ms: 20000
write_request_timeout_in_ms: 20000
endpoint_snitch: SimpleSnitch
rpc_address: 192.168.0.14
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
concurrent_reads: 64
concurrent_writes: 64
concurrent_counter_writes: 64
commitlog_total_space_in_mb: -1
prometheus_address: 192.168.0.14
murmur3_partitioner_ignore_msb_bits: 12
api_ui_dir: /usr/lib/scylla/swagger-ui/dist/
api_doc_dir: /usr/lib/scylla/api/api-doc/

**Comment by tzach** [comment]
Two comments:
- You do not need to include all cluster nodes as seeds, 2 or 3 should do
- With RF=1, even with one fail node, you already loose availability, as some of the data is not available

**Comment by jkdntc** [comment]
@tzach You mean：
parameters:
- seeds: "192.168.0.14, 192.168.0.15, 192.168.0.16"
and
set RF=2 or 3？

**Comment by tzach** [comment]
Thanks for the update @jkdntc 
Yes, RF=3 is the most common option for medium and small clusters.
With RF=3 you can use CL=ONE or QUORUM base on your read/write consistency requirements.
You can read more about CL and RF here http://docs.scylladb.com/architecture/architecture-fault-tolerance/
