### ISSUE TITLE
ServerError: No index found.

### ISSUE THREAD

**Issue by jaspreetb** [scylladb/scylla#3470]
*Installation details*
Scylla version (or git commit hash): 2.1.3-0.20180501.8e33e80
Cluster size: 4 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04

**Keyspace created using** :  
`create keyspace list_sample with replication = {'class': 'SimpleStrategy', 'replication_factor': '1'} AND durable_writes = true;`

**Table created using** : 
`create table test ( name text, dog_name text, genres list<text>, year_month list<text>, primary key (name) );`

**Inserts** : 
`insert into test (name, dog_name, genres, year_month) values ('jaspreet', 'snowy', ['rock', 'indian_classical', 'sufi', 'country'], ['2018-01', '2018-02', '2018-05']);`
`insert into test (name, dog_name, genres, year_month) values ('ski', 'jimmy', ['pop'], ['2018-01', '2018-03', '2018-04']);`
`insert into test (name, dog_name, genres, year_month) values ('trinity', 'milo', ['pop', 'rock', 'jazz'], ['2018-01', '2018-03', '2018-04']);`

**Index creation**:
`create index on test (genres);`
`select count(*) from test where genres contains 'pop';`
**Error** : ServerError: No index found.

`insert into test (name, dog_name, genres, year_month) values ('vian', 'o2', ['reggae', 'punk rock'], ['2018-01']);`
**Error** : WriteTimeout: Error from server: code=1100 [Coordinator node timed out waiting for replica nodes' responses] message="Operation timed out for list_sample.test - received only 0 responses from 1 CL=ONE." info={'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}

**Comment by duarten** [comment]
This `No index found.` issue is fixed master. What isn't done is #2962, so I don't think the `contains` query would work correctly.

**Comment by jaspreetb** [comment]
I see. It isn't just contains query that throws errors, I wasn't able to insert any data to the table after creating the index.
Will there be support for indexing collections in the near future? Thanks

**Comment by jaspreetb** [comment]
Got it. I'll close the issue. Thanks
