### ISSUE TITLE
Get rid of the moving operation support

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#3475]
The moving operation changes a node's token to a new token. It is supported only when a node has one token. The legacy moving operation is useful in the early days before the vnode is introduced where a node has only one token.  I don't think it is useful anymore. 
Removing it simplifies the cluster operation logic and code.

**Comment by asias** [comment]
@avikivity What do you think?

**Comment by slivne** [comment]
in the future we may want to use the move operation to balance the node of a cluster

**Comment by asias** [comment]
I assume you mean changing the number of tokens of a node, e.g., increase the num_tokens from 256 to 512.  This operation is very different from current moving operation.
