### ISSUE TITLE
nodetool rebuild_index is missed in Scylla

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3481]
Cassandra supports rebuild secondary index without dropping.
They support rebuild_index option in nodetool.
We miss this ability

**Comment by tzach** [comment]
In Apache Cassandra rebuild_index is a local task for rebuilding SI
In Scylla, SI is not local rather base on MV.
@duarten @nyh is there an equivalent action for MV ?

**Comment by duarten** [comment]
No, I don’t think there’s any reason to support this.

**Comment by slivne** [comment]
closing the issue as scylla sec index is based on mv
