### ISSUE TITLE
request to re-setup after rollback from 2.2 to 2.1

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3489]
*Installation details*
Scylla version (or git commit hash): 
- 2.1.3-0.20180501.8e33e80ad
- 2.2.rc1-0.20180516.eb646c61e

Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

* Reference upgrade guide: http://docs.scylladb.com/upgrade/upgrade-guide-from-2.1-to-2.2-rpm/

* Test steps
1. create a cluster with 4 nodes
2. upgrade the first node from 2.1 to 2.2
3. upgrade the second node from 2.1 to 2.1
4. rollback the second node from 2.2 to 2.1

* Description
Package conflict occurred in step 4 (`sudo yum downgrade scylla\* -y`)

Workaround 1 in rollback: (remove packages to avoid conflicts)
```
sudo yum remove scylla-tools-core scylla-libgcc73 scylla-libstdc++73
sudo yum downgrade scylla\* -y
sudo yum install scylla -y
```

Workaround 2 in rollback: (recover the io.conf file, otherwise we need to resetup)
```
sudo cp /etc/scylla.d/io.conf.rpmsave /etc/scylla.d/io.conf
```

**Comment by slivne** [comment]
@amoskong 
- Not clear to me if we have todo Workaround 1 & Workaround 2

If only Workaround 1 is needed its fine and we should update the docs.

**Comment by amoskong** [comment]
I will provide you more detail of steps & error for workaround 2 later,
then we can make a decision.
I will also try if we can solve the problem by remove *conf package when we
remove scylla-tools-core package.

**Comment by amoskong** [comment]
When we remove `scylla-tools-core scylla-libgcc73 scylla-libstdc++73`, `scylla-server` will also be removed for dependencies,  which contains the `io.conf` & `cpuset.conf`. If io.conf & cpuset.conf were changed during scylla_setup, they will be saved to `io.conf.rpmsave` `cpuset.conf.rpmsave` automatically.

After the downgrade rest scylla-conf & scylla-kernel-conf, we reinstall other scylla package by `sudo yum install scylla -y`. But the `io.conf` is from scylla-server 2.1.3, it's unconfigured. SO we have to re-setup or manually recovery the `io.conf.rpmsave` to `io.conf`.

I didn't found if other setup was lost during the rollback, maybe re-setup is safer.


```
[scylla-test@rolling-upgrade-ak-2-2-db-node-8360b844-0-4 scylla]$ ls /etc/scylla.d
cpuset.conf  dev-mode.conf  housekeeping.cfg  io.conf perftune.yaml

[scylla-test@rolling-upgrade-ak-2-2-db-node-8360b844-0-4 scylla]$ sudo yum remove scylla-tools-core scylla-libgcc73 scylla-libstdc++73
Removing:
 scylla-libgcc73                                x86_64                             7.3.1-1.2.el7.centos                                                 @scylladb-scylla-3rdparty                             179 k
 scylla-libstdc++73                             x86_64                             7.3.1-1.2.el7.centos                                                 @scylladb-scylla-3rdparty                             1.8 M
 scylla-tools-core                              noarch                             2.2.rc1-20180516.2cc0012aa.el7.centos                                @scylla-generic                                        25 M
Removing for dependencies:
 scylla                                         x86_64                             2.2.rc1-0.20180516.eb646c61e.el7.centos                              @scylla                                               0.0  
 scylla-jmx                                     noarch                             2.2.rc1-20180516.4d3a6bb.el7.centos                                  @scylla-generic                                       6.3 M
 scylla-server                                  x86_64                             2.2.rc1-0.20180516.eb646c61e.el7.centos                              @scylla                                                78 M
 scylla-tools                                   noarch                             2.2.rc1-20180516.2cc0012aa.el7.centos                                @scylla-generic                                       625 k

[scylla-test@rolling-upgrade-ak-2-2-db-node-8360b844-0-4 scylla.d]$ ls
cpuset.conf.rpmsave  housekeeping.cfg  io.conf.rpmsave  perftune.yaml

[scylla-test@rolling-upgrade-ak-2-2-db-node-8360b844-0-4] sudo yum downgrade scylla\* -y
[scylla-test@rolling-upgrade-ak-2-2-db-node-8360b844-0-4] sudo yum install scylla -y

[scylla-test@rolling-upgrade-ak-2-2-db-node-8360b844-0-4 scylla.d]$ ls
cpuset.conf  cpuset.conf.rpmsave  dev-mode.conf  housekeeping.cfg  io.conf  io.conf.rpmsave  perftune.yaml
```

```
Jun 05 05:32:27 rolling-upgrade-ak-2-2-db-node-8360b844-0-4 scylla[1337]:  [shard 0] init - I/O Scheduler is not properly configured! This is a non-supported setup, and performance is expected to be unpredictably
                                                                           Reason found: --max-io-requests is not set.
                                                                          To properly configure the I/O Scheduler, run the scylla_io_setup utility shipped with Scylla.
                                                                          To ignore this, see the developer_mode configuration option.
Jun 05 05:32:27 rolling-upgrade-ak-2-2-db-node-8360b844-0-4 scylla[1337]:  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Bad I/O Scheduler configuration)
```

**Comment by amoskong** [comment]
On Tue, Jun 5, 2018 at 2:54 PM, Shlomi Livne <notifications@github.com>
wrote:

> There are more configurations files - so we need to backup them all and
> restore them all - like we do for the enterprise release
>
> http://docs.scylladb.com/upgrade/upgrade-guide-from-2.
> 1-to-2018.1-rpm/#backup-configuration-files
>
> http://docs.scylladb.com/upgrade/upgrade-guide-from-2.
> 1-to-2018.1-rpm/#restore-the-configuration-file
>

Thanks.

> can you please prepare the upgrade guide.
>

I already prepared a upgrade guide (from 2.1 to 2.2)


> We need to verify if this is needed also for ubuntu/debian.
>
I will test it, and update the guide.

**Comment by tzach** [comment]
@amoskong ping

**Comment by slivne** [comment]
@amoskong / @roydahan ping

**Comment by amoskong** [comment]
We also need to backup and restore the configuration files during the rollback.

The upgrade guide had been updated:
- http://docs.scylladb.com/upgrade/upgrade-guide-from-2.1-to-2.2-ubuntu/
- http://docs.scylladb.com/upgrade/upgrade-guide-from-2.1-to-2.2-debian/
