### ISSUE TITLE
Remove default-install of collectd 

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#3490]
Since bc7503feee1a8c7292e09217fecfca7fe2aad40b `scyllatop` no longer needs collectd. This allows us to drop collectd, which consumes a lot of CPU on large machines.

We can move collectd support (including the dependency on `collectd`) to a sub-package `scylla-collectd` that is not installed by default, and change the default configuration to disable collectd.

**Comment by tzach** [comment]
@avikivity this is a breaking change for anyone who does use collectd.
We should add a 2.2 disclaimer that collectd is deprecated, and will be disable by default in the future.
In 2.3 (or 2.4) we can implement the change with a proper note.

**Comment by avikivity** [comment]
It is not a breaking change, we retain collectd support. It's just not default.

When upgrading, they'll need an additional step of `yum install scylla-collectd` and everything will continue working.

**Comment by avikivity** [comment]
2.2 and 2.3 will still ship with collectd enabled by default/

**Comment by avikivity** [comment]
It's nicer to pull in fewer dependencies.

In the past, EPEL's collectd pulled in qt and half a million xorg dependencies; this has since been correctd. Still, it's nicer not to pull in something you don't need.

btw, since we no longer need a local collectd, perhaps we don't need anything. Someone who wants collectd can just configure it to point to their remote instance.

It will mean an extra step for collectd users, but it will be worthwhile for them.
