### ISSUE TITLE
Support arithmetic operations in WHERE clause

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#3499]
*Installation details*
Scylla version (or git commit hash): 2.0

Part of datetime functions support issue (#2949) is unrelated to datetime, so I move it to a separate issue.

Add support for basic operations on constants in WHERE clauses. Examples:
~~~
SELECT * FROM myTable WHERE date >= currentDate() - 2d
~~~

~~~
SELECT * FROM myTable WHERE count >= 7 - 3
~~~

See also:
https://issues.apache.org/jira/browse/CASSANDRA-11935
https://issues.apache.org/jira/browse/CASSANDRA-11936

**Comment by duarten** [comment]
Duplicates #2694 and #2693?

**Comment by psarna** [comment]
Yup.
