### ISSUE TITLE
If insert into text or varchar column more then 8192 bytes, just 8192 bytes will be inserted.

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3501]
1. Create table with text column 
2. Insert into this column value with 8193 length
3. Select from the column - just 8192 characters is inserted

**Comment by psarna** [comment]
I can't manually reproduce on master(4a90eeb326d31476196e92ef70eff624ad9e171a) in cqlsh, inserting a text column with 8193 characters works just fine and select returns a proper row. Can I have version details and perhaps specific cql commands that failed?

**Comment by psarna** [comment]
Ok, I can reproduce, it works fine when the column is primary key, but regular columns are indeed truncated to 8192.
