### ISSUE TITLE
Nightly build for Ubuntu 16 not avilable

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#3504]
*Installation details*
OS (RHEL/CentOS/Ubuntu/AWS AMI): Nightly

Following the instructions on 
https://www.scylladb.com/download/ubuntu-16-04/

I get `HTTP request sent, awaiting response... 404 Not Found` for the repo.
Other versions (2.1, 2.0) works fine

**Comment by tzach** [comment]
@slivne ?

**Comment by amoskong** [comment]
Nightly build for Ubuntu 14 is also not available.
http://xxxxxx.com/scylla/repo/xxxxxxxxxxxxxxxxx/ubuntu/scylladb-nightly-trusty.list

{errorMessage=RequestId: xxxxxxxxxxxxxxxxx Process exited before completing request}

@amnonh

**Comment by syuu1228** [comment]
I able to install latest nightly build of Ubuntu 16.04 by using
https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/xenial/master/761/scylladb/scylla.list
so I don't understand what is the problem.
Same as Ubuntu 14.04.

**Comment by slivne** [comment]
the promotion is probably broken ...

there is a downstream project after the artifacts are tested called
scylla-promote that may be broken ... need to check it.

**Comment by slivne** [comment]
@hagitsegev - please take a look

We promote the passed nightly build artifacts to be latest for all distributions and they should be available to install

**Comment by nyh** [comment]
In http://jenkins.cloudius-systems.com:8080/view/scylla-master/job/scylla-master-ubuntu-deb-16.04/839/console I see the error message
```
dpkg-source: error: source package has two conflicting values - scylla-server and unknown
```
Following a bunch of warnings. I don't know what this means. @syuu1228 do you know what this means, and why this problem only started to appear now?

**Comment by syuu1228** [comment]
.deb build on master is broken now, should be fixed by "[PATCH scylla] dist/debian: fix broken debian/changelog" on ml.

**Comment by slivne** [comment]
@penberg / @hagitsegev can we close this ?

**Comment by penberg** [comment]
The URL @tzach is referencing here does not exists, and Ubuntu nightly build URL is also different (with relocatable package, they're unified across different Ubuntu variants):

http://downloads.scylladb.com/deb/unstable/unified/master/latest/scylladb-master/

So I'm closing this.
