### ISSUE TITLE
Scylla - Collections performance issues

### ISSUE THREAD

**Issue by san213** [scylladb/scylla#3506]
*Installation details*
Scylla version (or git commit hash): Pulling from scylladb/scylla docker 
Cluster size: 3 nodes, 4 core boxes each with ssd attached
OS (RHEL/CentOS/Ubuntu/AWS AMI): ubuntu

*Hardware details (for performance issues)*       3 nodes, 4 core boxes each with ssd attached
Platform (physical/VM/cloud instance type/docker): scylla setup on the aws vm using docker.
Hardware: sockets= cores= hyperthreading= memory= Refer to the lstopo output below
Disks: (SSD/HDD, count) SSD, 1 for each box.

lstopo

Machine (7480MB)
  Socket L#0 + L3 L#0 (25MB)
    L2 L#0 (256KB) + L1d L#0 (32KB) + L1i L#0 (32KB) + Core L#0
      PU L#0 (P#0)
      PU L#1 (P#2)
    L2 L#1 (256KB) + L1d L#1 (32KB) + L1i L#1 (32KB) + Core L#1
      PU L#2 (P#1)
      PU L#3 (P#3)
  HostBridge L#0
    PCI 8086:7010
    PCI 1013:00b8
    PCI 8086:10ed
      Net L#0 "eth0"

Problem:

We are facing issue if the size of collections increases beyond 500. The latency shoots up like crazy. We are hitting scylla at the throughput of 15000 rps. The size of each element in collection is about 251 bytes. There are only about 20 rows in the table and each row in the table has the map collections with about more than 500 key/value pairs. With around 200 elements in map we are getting around 6ms/request, but if the elements size increases beyond 500 the latency shoots up to 100ms/request. Can you please help in overcoming this issue?

**Comment by tgrabiec** [comment]
How does your schema look like? 

When you say that the latency shoots up, you mean the latency of a write, a read, or both? What kind of statements are you executing?

**Comment by san213** [comment]
Schema would like this.

CREATE TABLE test.data (
    key1 text,
    key2 text,
    key3 text,
    key4 text,
    key5 boolean,
    key6 text,
    *data_map* map<bigint, text>,
    PRIMARY KEY ((key1, key2, key3, key4, key5, key6))
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression':
'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

We are doing very less writes on this. It is complete read. As the elements
in *data_map *increase, the scylla read latency is increasing. It is
straightforward select query.

**Comment by slivne** [comment]
@san213 - how are you writting into the map 

are you appending values into the map or overwriting the map contents.

**Comment by slivne** [comment]
- to clarify

- if you are appending values into the map than we need to scan the related sstables to make sure we collect all elements
-  if you are overwtirring the complete map  than a tombstone would also be added - which can provide an input to stop the search since older data is not valid.

I am not suggesting a change - I would like to understand the use case better.

I am closing this issue at this point - if there is additional information please post and we can reopen and continue
