### ISSUE TITLE
install-dependencies fails to complete on Ubuntu 14.04

### ISSUE THREAD

**Issue by argenet** [scylladb/scylla#3515]
Scylla version (or git commit hash): 
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 14.04

The `install-dependencies.sh` script fails on Ubuntu 14.04 with
```
E: Unable to locate package libsystemd-dev
```

The problem is that there is no `libsystemd-dev` package in Ubuntu 14.04. `libsystemd-daemon-dev` should be used instead.

**Comment by avikivity** [comment]
Ubuntu 14.04 is no longer supported.
