### ISSUE TITLE
Using Scylla as a general Prometheus source

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#3521]
Relates to #2190
This is more of a seastar issue.
The idea is to add an API for scylla to add external metrics that would be reported by scylla.

For example, it would be better if scylla would report the current available latest version that the housekeeping is getting, this would allow setting an alarm when a newer version is available (we can extend it to critical updates).

Generalization of this would allow us to collect different metrics from the os that are currently done by node_exporter and report them with scylla.

A good candidate for that task is the housekeeping, that can be extended to track system resources, core, logs etc.
If scylla would be the reporting endpoint, we can limit the resources taken by the information collector by limiting it's scrapping interval (it doesn't need to be available all the time) .
For example, we can check and report to scylla the disk usage once every 10 minutes, but scylla would report that information once every 15 seconds.

**Comment by tzach** [comment]
The housekeeping service is a better candidate to be folded into Scylla than node_exporter, as it is much simpler. Rewriting node_exporter in housekeeping is a lot of work with a small gain.

**Comment by amnonh** [comment]
@tzach following your comment, I'm closing the issue
