### ISSUE TITLE
Add Rust native driver to Scylla's documentation

### ISSUE THREAD

**Issue by senselogic** [scylladb/scylla#3527]
While not as popular as Go, C++ and Java, Rust remains one of the best programming languages to implement high performance servers : 

https://www.techempower.com/benchmarks/#section=data-r16&hw=ph&test=plaintext

It already has a native Cassandra driver which implements all the features described in Cassandra binary protocol specification (versions 3 and 4) :

https://github.com/AlexPikalov/cdrs

So I think it may be worth that you also test this driver, in order to add it to Scylla's driver documentation here :

https://github.com/scylladb/scylla/wiki/Driver-Status
http://docs.scylladb.com/using-scylla/scylla_drivers/

**Comment by tzach** [comment]
Good idea!
Thanks @senselogic

**Comment by tzach** [comment]
Done

**Comment by senselogic** [comment]
👍
