### ISSUE TITLE
doc: dc_suffix is no longer only used by EC2SnitchXXX

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3533]
*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Default cassandra-rackdc.properties describes that `dc_suffix=<Data Center name suffix, used by EC2SnitchXXX snitches>`

It's used by GoogleCloudSnitch, referencing: http://docs.scylladb.com/operating-scylla/snitch/#googlecloudsnitch

Question: we need to update the comment in cassandra-rackdc.properties

```
$ cat conf/cassandra-rackdc.properties
#
# cassandra-rackdc.properties
#
# The lines may include white spaces at the beginning and the end.
# The rack and data center names may also include white spaces.
# All trailing and leading white spaces will be trimmed.
#  
# dc=my_data_center
# rack=my_rack
# prefer_local=<false | true>
# dc_suffix=<Data Center name suffix, used by EC2SnitchXXX snitches>
#


```

@vladzcloudius @lauranovich @tzach

**Comment by vladzcloudius** [comment]
I agree that the comment in the `cassandra-rackdc.properties` is misleading and should be fixed.
Note however that `dc_suffix` is used by all scylla snitches that use `cassandra-rackdc.properties` which in addition to already mentioned included a GossipingPropertyFileSnitch.

**Comment by lauranovich** [comment]
Is this file ours to change, or do we need to submit a patch to Cassandra?
Just tell me if this will be fixed so I know how to change the documentation accordingly.

**Comment by slivne** [comment]
@amoskong please move to the docs and close the issue

**Comment by amoskong** [comment]
The `cassandra-rackdc.properties` is in scylla repo:
https://github.com/scylladb/scylla/blob/master/conf/cassandra-rackdc.properties

We need to submit patch for scylla if we want to update the comment.

**Comment by amoskong** [comment]
Create issue in https://github.com/scylladb/scylla-docs/?  But the problem
file is in scylla project.

**Comment by vladzcloudius** [comment]
@amoskong @slivne @lauranovich @tzach Guys and Laura, I must apologize but I misled you in my previous comment.

This all is rather confusing and I only added to it. I refreshed my memory by reading the code and would like to clarify it for the last time (hopefully :)):

 * cassandra-rackdc.properties is used by the following snitches:
   * GossipingPropertyFileSnitch
   * Ec2 snitches: Ec2Snitch and Ec2MultiRegionSnitch
   * GceSnitch
 * There are 4 fields that are *always allowed* to be present in the cassandra-rackdc.properties:
   * rack
   * dc
   * prefer_local
   * dc_suffix
 * GossipingPropertyFileSnitch will take into an account *only*
   * rack (mandatory)
   * dc (mandatory)
   * prefer_local (optional, false by default) 
 * GossipingPropertyFileSnitch is going to ignore dc_suffix (*unlike what I wrote before*)
 * GceSnitch and both Ec2 snitches are going to ignore all but dc_suffix field which is optional.

I'm sorry for a confusion. Hope it clearer now.
This in particular means that the comment in the cassandra-rackdc.properties was ok until before GceSnitch was added. It may now be either removed or changed to state something like "used by cloud snitched".

**Comment by lauranovich** [comment]
If we are going to change the cassandra-rackdc.properties file we should do the following
1. remove "used by EC2SnitchXXX snitches" from the file
2. explain where you have mandatory and optional parameters (not completely necessary as this can be done in the docs, but it is nice to have.
3. explain which snitches use this file - a must

**Comment by lauranovich** [comment]
I am opening an issue in docs as well.

**Comment by slivne** [comment]
@lauranovich did you send a patch to fix conf/cassandra-rackdc.properties
