### ISSUE TITLE
Scylla recompacts on restart

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#3534]
*Installation details*
Scylla version (or git commit hash): 7afef3abc5e26dac4a4c388fff98799ad291d07b
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

On a restart, scylla starts recompacting column family with LCS

**Comment by slivne** [comment]
@raphaelsc - please provide reproducer

**Comment by raphaelsc** [comment]
To reproduce, 

run:
./tools/bin/cassandra-stress write n=10000000 -rate threads=30 -pop seq=1..10000000 -schema 'compaction(strategy=LeveledCompactionStrategy,sstable_size_in_mb=5)';

and wait for compaction to finish and reboot.

**Comment by raphaelsc** [comment]
Low sstable_size_in_mb triggers this behavior, but it's expected. Memtable flushed during shutdown will be big enough for L0, but will not be compacted during shutdown because compaction manager is stopped. After reboot, that new sstable is compacted into level 1, then level 2, and so on, because size limit of levels is small with low sstable_size_in_mb.

**Comment by slivne** [comment]
Can you please verify this

1. After c-s ends do a nodetool flush
2. Wait for comoactions to end
3. Do a reboot

**Comment by raphaelsc** [comment]
@slivne flushed, and no compaction after reboot.

**Comment by raphaelsc** [comment]
looks like the pending compaction is not only due the memtable only flushed at shutdown. It may also happen that compaction manager will stop compacting a column family ***after it stopped being written to*** due to a bug in the compaction manager itself.
