### ISSUE TITLE
Does scyllaDB support GeoPartial data ?

### ISSUE THREAD

**Issue by s4kibs4mi** [scylladb/scylla#3537]
Does ScyllaDB support GeoPartial data. Found that Cassandra supports geopartial operations using lucene index.

**Comment by dorlaor** [comment]
We have plans to support index but not using Lucene, more like SASI

**Comment by tzach** [comment]
> We have plans to support index but not using Lucene, more like SASI

https://github.com/scylladb/scylla/issues/2203
