### ISSUE TITLE
nodetool info return wrong gossiper status

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#354]
Scylla print out:
```
Start gossiper service ...
```

nodetool infro output
```
$ nodetool info
ID                     : 0d2ce3b6-dcc9-4d16-ab72-1b2789f82526
Gossip active          : false
Thrift active          : true
```

Gossip active should be true if it is active.

**Comment by amnonh** [comment]
Like in origin the gossip active is mapped to storage_service _initialized. 
I believe there is a missing initialization of _initialized, but this will not explain what we see here (it could explain if the gossiper would have been active before it was started), I did not go into the storage service details, but it seems that something is missing in the gossip starting procedure.

**Comment by asias** [comment]
@amnonh Can you please show me show  the code where you get the

    Gossip active

info.

This should be trivial to fix.

**Comment by slivne** [comment]
from tzach

1. Testing 0.10, I see Gossip active is false and Thrift active is true. AFAIK, both are wrong.
I tested on EC2 with a two nodes cluster. The cluster is working fine and data is replicated.

2. What does the 2.38MB off heap stands for? Look like the cache (which is fine)

$ nodetool info
ID                     : e795ffb9-034d-4535-952b-37eb028f3f3e
Gossip active          : false
Thrift active          : true
Native Transport active: true
Load                   : 84359.0
Generation No          : 0
Uptime (seconds)       : 768
Heap Memory (MB)       : 288.04 / 13419.00
Off Heap Memory (MB)   : 2.38
Data Center            : datacenter1
Rack                   : rack1
Exceptions             : 0
Key Cache              : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, 0.000 recent hit rate, 0 save period in seconds
Row Cache              : entries 9, size 9 bytes, capacity 2.34 MB, 37 hits, 48 requests, 0.771 recent hit rate, 0 save period in seconds
Counter Cache          : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, 0.000 recent hit rate, 0 save period in seconds
Token                  : (invoke with -T/--tokens to see all 512 tokens)

**Comment by amnonh** [comment]
for thrift active: the method is mapped to service::get_local_storage_service().is_rpc_server_running(); that return true when it should return false

**Comment by asias** [comment]
I will send a patch.
