### ISSUE TITLE
Commitlog: preallocate segments

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#356]
We need to modify commitlog to preallocate a segment ahead of time, so that under the normal configuration add_mutation() returns a ready future.

For bonus points:
- the number of preallocated segments should adjust itself.  We might consume a segment faster than it takes to allocate one!
- call file::allocate() to make it even easier for the fs to write.
- make segments larger? (how large are they now?)

**Comment by slivne** [comment]
@elcallio whats the status of this ?

**Comment by elcallio** [comment]
I submitted patch sets. One was backed out again due to some 
fluctuations in Tomeks benchmarks results.
Then a last one was sent for testing (by aforementioned Tomek). I've 
heard nothing on the results.

Den 2015-09-29 kl. 11:54, skrev slivne:

**Comment by avikivity** [comment]
I missed it.  Please bump it on the list.

**Comment by elcallio** [comment]
This was sent to the old dev-list, and since changing mailboxes I cannot 
find it to add a "ping" to the mails. :-P
The branch is at seastar-dev: calle/commitlog_latency though. I can 
resend the patch series if you like. (its two patches)

Den 2015-09-29 kl. 11:58, skrev Avi Kivity:

**Comment by tgrabiec** [comment]
29 wrz 2015 11:57 AM "Calle Wilund" <notifications@github.com> napisał(a):
>
> I submitted patch sets. One was backed out again due to some
> fluctuations in Tomeks benchmarks results.
> Then a last one was sent for testing (by aforementioned Tomek). I've
> heard nothing on the results.

It's in my queue, but I'm using the softlayer setup for cluster testing
now, which as I understand has higher priority.

**Comment by slivne** [comment]
On Tue, Sep 29, 2015 at 1:17 PM, Tomasz Grabiec <notifications@github.com>
wrote:

> 29 wrz 2015 11:57 AM "Calle Wilund" <notifications@github.com> napisał(a):
> >
> > I submitted patch sets. One was backed out again due to some
> > fluctuations in Tomeks benchmarks results.
> > Then a last one was sent for testing (by aforementioned Tomek). I've
> > heard nothing on the results.
>
> It's in my queue, but I'm using the softlayer setup for cluster testing
> now, which as I understand has higher priority.
>

cluster testing is higher priority :)

**Comment by avikivity** [comment]
Please repost it regardless.  We (you) can retest on monster.
