### ISSUE TITLE
Automatic protection against resurrection of deleted data

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#3560]
All changes of data in Scylla must be represented by commutative objects (mutations) so that writes which go to different replicas, or different sstables on disk, can be eventually reconciled when merged. That applies to data deletions, which are represented by mutations called tombstones.

In order to avoid accumulation of tombstones indefinitely, tombstones expire after a configurable amount of time called GC grace. It's configurable per-table using a property called `gc_grace_seconds`, which is 10 days by default. After this amount of time, a replica is allowed to drop the tombstone [*], based on the assumption that all replicas in the cluster have received all writes for which the tombstone could be relevant by then, including the tombstone itself. If this assumption is not kept, it can happen that deleted data will be resurrected. For example, if we failed to replicate a deletion of a row to replica A, and then the tombstone is dropped from all other replicas, then any read which involves A will see the row as alive again, and repair will replicate it to other nodes.

In order to keep the assumption satisfied and avoid those problems, it is required from users to repair all nodes in the cluster at least once in each GC grace period. Relying on this is error-prone. Users may not be aware of this, forget to run repair, or be unable to complete repair due to some technical difficulties. In order to improve safety, we should expire tombstones not based on a static GC grace threshold, but based on when given partition was last repaired. It would be still required to run repair in a timely fashion to reclaim space taken by tombstones, but failure to do so would not lead to inconsistency.

Each replica would keep a local table with a map of partition ranges and repair timestamps. The map would be updated after a successful repair of given range, on each of the involved replica, and the timestamp used will be the timestamp of the start of the repair. Repair in this context would have to mean that all replicas exchanged all writes which were persisted before repair started. It is not enough to consume missing writes on the replica on which the repair was started, all other replicas would have to be fully repaired in that range as well.

We would consider a tombstone expired if it is older than GC grace period and its partition range was repaired later than tombstone's timestamp + GC grace period (later than tombstone's expiration according to the GC grace period). The GC grace period is still there to account for mutation delays above replica's data store, before a mutation gets visible to the repair. It should take into account things like delays on the client side, network delays, delays of application of mutation to the memtable, clock drifts, etc. It no longer has to include the maintenance period of running repair, so it could be much shorter than it currently is.

[*] The replica is still responsible for keeping its internal state consistent by not loosing any received writes, so it cannot drop a tombstone, even if expired, from one of its mutation stores (e.g. an sstable), if it is still relevant for mutations stored in some other mutation stores. The dropping happens during compaction when mutation sources are merged and replica figures out that the tombstone is no longer relevant for mutations stores which are not being merged.

**Comment by duarten** [comment]
Another thing to consider is the hinted handoff TTL. A given node C that is not responsible for a partition range PR can nonetheless hold a hint for node R, which is responsible for PR. If data in the hints log could be shadowed by the tombstone that is about to be purged, data could be resurrected.

Batches could also lead to this issue.

**Comment by tzach** [comment]
Related https://issues.apache.org/jira/browse/CASSANDRA-6434

**Comment by gleb-cloudius** [comment]
On Fri, Jun 29, 2018 at 09:30:12AM -0700, Duarte Nunes wrote:
> Another thing to consider is the hinted handoff TTL. A given node C that is not responsible for a partition range PR can nonetheless hold a hint for node R, which is responsible for PR. If data in the hints log could be shadowed by the tombstone that is about to be purged, data could be resurrected.
> 
> Batches could also lead to this issue.
> 
Both HH and Batches drop data older than gc grace period.

--
			Gleb.

**Comment by duarten** [comment]
@gleb-cloudius Consider the case where we decide to send a hint right before it becomes older than the GC grace period, but when the intended replica processes it, it already is. Or consider clock drift, which causes the node with the hint to think it is still not older than the GC grace period.

**Comment by gleb-cloudius** [comment]
On Mon, Jul 02, 2018 at 04:41:37PM -0700, Duarte Nunes wrote:
> @gleb-cloudius Consider the case where we decide to send a hint right before it becomes older than the GC grace period, but when the intended replica processes it, it already is. Or consider clock drift, which causes the node with the hint to think it is still not older than the GC grace period.
> 
Clock drift is not the issue since gc grace period clock is local. The
first issue is. We discussed it with Vlad before he started to write HH
and I proposed to drop hints that are older than gcgp - delta where
delta is sufficiently large to be large that any possible network delay
(lets say 1 hour). Not ideal, but very unlikely to cause any problems in
real deployments. What better can we do? Drop hints for repaired
partitions? But the information that partition is repaired on node A and
a hint to node A are sitting on different hosts.

--
			Gleb.

**Comment by asias** [comment]
> We would consider a tombstone expired if it is older than GC grace period and its partition range was repaired later than tombstone's timestamp + GC grace period (later than tombstone's expiration according to the GC grace period).

@tgrabiec Why should the range be repaired LATER than tombstone's timstamp + gc grace peirod?

Say tombstone's timestamp is t1, gc grace period is 10 days, shouldn't  we repair NOT later than t1 + 10 days?

**Comment by tgrabiec** [comment]
On Sat, Jul 31, 2021 at 3:17 AM Asias He ***@***.***> wrote:

> We would consider a tombstone expired if it is older than GC grace period
> and its partition range was repaired later than tombstone's timestamp + GC
> grace period (later than tombstone's expiration according to the GC grace
> period).
>
> @tgrabiec <https://github.com/tgrabiec> Why should the range be repaired
> LATER than tombstone's timstamp + gc grace peirod?
>
> Say tombstone's timestamp is t1, gc grace period is 10 days, shouldn't we
> repair NOT later than t1 + 10 days?
>

In the new algorithm we don't impose any constraints on when you
should repair. You can repair whenever you want, regardless of gc period
and timestamps. The repair time determines which tombstones can be
considered expired, and the quoted text implies the tombstone from you
example is expired when its range is repaired later than t1 + 10 days. The
new gc grace period wouldn't be as large as 10 days, since it has a
different meaning now and can be much shorter. It is still there to account
for the period in which writes are coming into the system, e.g. due to
propagation delay between the client and replica nodes. You don't want to
expire a deletion which can cover a write which is yet to arrive to some
replica.

>

**Comment by asias** [comment]
> On Sat, Jul 31, 2021 at 3:17 AM Asias He ***@***.***> wrote: We would consider a tombstone expired if it is older than GC grace period and its partition range was repaired later than tombstone's timestamp + GC grace period (later than tombstone's expiration according to the GC grace period). @tgrabiec <https://github.com/tgrabiec> Why should the range be repaired LATER than tombstone's timstamp + gc grace peirod? Say tombstone's timestamp is t1, gc grace period is 10 days, shouldn't we repair NOT later than t1 + 10 days?
> In the new algorithm we don't impose any constraints on when you should repair. You can repair whenever you want, regardless of gc period and timestamps. The repair time determines which tombstones can be considered expired, and the quoted text implies the tombstone from you example is expired when its range is repaired later than t1 + 10 days. The new gc grace period wouldn't be as large as 10 days, since it has a different meaning now and can be much shorter. It is still there to account for the period in which writes are coming into the system, e.g. due to propagation delay between the client and replica nodes. You don't want to expire a deletion which can cover a write which is yet to arrive to some replica.

Yes, I know with the new algorithm user can run repair after gc period without any correctness issue. By "we should repair not latter than t1 + 10 days", I mean this will help to remove the tombstone in the time gc period. If the repair happens before t1 + 10 days, I think this repair is still eligible for removing the tombstone. 

I am not sure reusing the gc grace period as the propagation delay is a good idea. Users are used to  setting the value to change how fast the cluster should remove the tombstone. Now it is interpreted as the propagation delay. It is hard to set such delay correctly. More importantly, the delay also does not have any guarantee. Can we have something without a delay based algorithm?

**Comment by tgrabiec** [comment]
On Mon, Aug 2, 2021 at 4:07 AM Asias He ***@***.***> wrote:

> On Sat, Jul 31, 2021 at 3:17 AM Asias He *@*.***> wrote: We would
> consider a tombstone expired if it is older than GC grace period and its
> partition range was repaired later than tombstone's timestamp + GC grace
> period (later than tombstone's expiration according to the GC grace
> period). @tgrabiec <https://github.com/tgrabiec>
> https://github.com/tgrabiec Why should the range be repaired LATER than
> tombstone's timstamp + gc grace peirod? Say tombstone's timestamp is t1, gc
> grace period is 10 days, shouldn't we repair NOT later than t1 + 10 days?
> In the new algorithm we don't impose any constraints on when you should
> repair. You can repair whenever you want, regardless of gc period and
> timestamps. The repair time determines which tombstones can be considered
> expired, and the quoted text implies the tombstone from you example is
> expired when its range is repaired later than t1 + 10 days. The new gc
> grace period wouldn't be as large as 10 days, since it has a different
> meaning now and can be much shorter. It is still there to account for the
> period in which writes are coming into the system, e.g. due to propagation
> delay between the client and replica nodes. You don't want to expire a
> deletion which can cover a write which is yet to arrive to some replica.
>
> Yes, I know with the new algorithm user can run repair after gc period
> without any correctness issue. By "we should repair not latter than t1 + 10
> days", I mean this will help to remove the tombstone in the time gc period.
> If the repair happens before t1 + 10 days, I think this repair is still
> eligible for removing the tombstone.
>
If we're talking about the old gc grace period, then it should just be
ignored by the new algorithm. If we're talking about the new gc grace
period as described above, the purpose of it is to prevent tombstones from
being removed, so repair must keep the tombstones unless it was executed
later than expiration (t1 + 10 days).

> I am not sure reusing the gc grace period as the propagation delay is a
> good idea. Users are used to setting the value to change how fast the
> cluster should remove the tombstone. Now it is interpreted as the
> propagation delay. It is hard to set such delay correctly.
>
Yes, I think we should introduce a new name for the new gc grace period and
ignore the old setting.

> More importantly, the delay also does not have any guarantee. Can we have
> something without a delay based algorithm?
>
I don't think we can avoid it without coordination with the sources of
writes. We can add coordination with internal sources, like coordinators.
When repair starts, we could issue a barrier to all coordinators which
would wait for the active writes to drain. If all CQL clients use
server-side timestamps, this would be enough to establish a safe expiration
time.

If client-side timestamps are used, we would have to coordinate with the
clients, and that would be a protocol and driver change. It's probably not
worth the complication. We can add protection against violation of the
expiration threshold by rejecting writes with timestamps which are older
than our established expiration threshold for a given key range.

>

**Comment by mykaul** [comment]
@annastuchlik - is this feature documented for 5.2?

**Comment by annastuchlik** [comment]
@mykaul It was already documented but marked as "experimental": https://docs.scylladb.com/stable/cql/ddl.html#ddl-tombstones-gc
I'm waiting for the green light from @tzach to remove the "experimental" note.
