### ISSUE TITLE
Hints won't be written for failures other than timeouts

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3563]
In `storage_proxy::register_response_handler`, we register an `abstract_write_response_handler` together with a timer that expires when the write times out. The callback of that timer ultimately calls `abstract_write_response_handler::on_timeout`, but it is also responsible for potentially storing a hint. A timeout, however, is the only failure for which we will store a hint.

We should have similar code in `storage_proxy::got_failure_response`, which can cause the `abstract_write_response_handler` to be unregistered, and the associated timer to be cancelled.

**Comment by vladzcloudius** [comment]
@duarten The current code doesn't seem right indeed. @gleb-cloudius, what do you think? Do we miss something here?

**Comment by gleb-cloudius** [comment]
The code looks (mostly) correct to me and I confirmed that with
CL=QUORUM if one replica sends failed response while two other succeed
a hint is written.

CL=ANY handling looks wrong since if all replicas will send failed response
the request will fail, but it should fail only if no hints are written.

--
			Gleb.

**Comment by duarten** [comment]
@gleb-cloudius Where's the code that triggers the timer or stores a hint when CL is reached and the remaining replicas reply with failure?

**Comment by gleb-cloudius** [comment]
On Tue, Jul 03, 2018 at 02:26:39AM -0700, Duarte Nunes wrote:
> @gleb-cloudius Yes, there is. Consider the following:
> 
> ```
> void storage_proxy::got_failure_response(storage_proxy::response_id_type id, gms::inet_address from, size_t count) {
>     auto it = _response_handlers.find(id);
>     if (it != _response_handlers.end()) {
>         tracing::trace(it->second.handler->get_trace_state(), "Got {} failures from /{}", count, from);
>         if (it->second.handler->failure(from, count)) {
>             remove_response_handler(id); // last one, remove entry. Will cancel expiration timer too.
>         }
>     }
> }
> ```
> 
> The call to `remove_response_handler` will trigger the destructor of `rh_entry`, which will tigger the destructor of `timer<clock_type> expire_timer`, which will do:
> 
> ```
> timer<Clock>::~timer() {
>     if (_queued) {
>         engine().del_timer(this);
>     }
> }
> ```
> 
And that's fine. Request failed. No hints should be stored.

--
			Gleb.

**Comment by duarten** [comment]
So, even though we got replies from all replicas, we'll wait until the timer expires to store the hint? This doesn't make sense.

**Comment by gleb-cloudius** [comment]
On Tue, Jul 03, 2018 at 02:28:23AM -0700, Duarte Nunes wrote:
> Are you saying that in your case (QUORUM, CL is reached, remaining replicas reply with failure), we don't remove the handler, and let it expire? Isn't this wrong? And where is the code that prevents it from being removed?
> 
It is not wrong. It is suboptimal and can be optimized indeed.
A handler is removed either if CL cannot be reached because of errors,
or all replicas replied with success or timeout was triggered.

--
			Gleb.

**Comment by duarten** [comment]
This means that ANY handling is correct also, no?

**Comment by gleb-cloudius** [comment]
On Tue, Jul 03, 2018 at 02:31:43AM -0700, Duarte Nunes wrote:
> So, even though we got replies from all replicas, we'll wait until the timer expires to store the hint? This doesn't make sense.
> 
Yes, the case where enough replicas for CL replied with success and rest with
failures (but all of them replied) is not handled optimally exactly for
the hint handing reason. It can be optimized by detecting this case and
run timer immediately, but there is not HH handling problem. It was easy
to test for this too BTW.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Tue, Jul 03, 2018 at 02:34:22AM -0700, Duarte Nunes wrote:
> This means that ANY handling is correct also, no?
> 
I do not think so. If all replicas replied with failure we should write
hints, but we do not. Not sure ANY is interesting use case to be honest.

--
			Gleb.

**Comment by duarten** [comment]
Well, we leverage it for views: if the single view replica replies with failure, we'll want to store the hint.

**Comment by gleb-cloudius** [comment]
On Tue, Jul 03, 2018 at 02:40:46AM -0700, Duarte Nunes wrote:
> Well, we leverage it for views: if the single view replica replies with failure, we'll want to store the hint.
> 
Good point. I'll fix it. Lest close this one and open another about
CL=ANY.

--
			Gleb.

**Comment by duarten** [comment]
I was thinking of retrofitting this one as an enhancement, making it about the optimization. Is that ok?

**Comment by gleb-cloudius** [comment]
On Tue, Jul 03, 2018 at 03:04:39AM -0700, Duarte Nunes wrote:
> I was thinking of retrofitting this one as an enhancement, making it about the optimization. Is that ok?
> 
Sure.

--
			Gleb.

**Comment by duarten** [comment]
Or better to just close this one and open two new issues.

**Comment by duarten** [comment]
Opened https://github.com/scylladb/scylla/issues/3565

**Comment by duarten** [comment]
And https://github.com/scylladb/scylla/issues/3566
