### ISSUE TITLE
Support for CQL toUnixTimestamp

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#3567]
*Installation details*
Scylla version (or git commit hash): 2.3

Commit https://github.com/psarna/scylla/commit/602aa5c85906bdb78e2c6a971af6f67b79f65c61 added  time and uuid conversion function, but did not include `toUnixTimestamp`

* `toUnixTimestamp(timeuuid)`  Converts timeuuid to UNIX timestamp format.
* `toUnixTimestamp(timestamp)` Converts timestamp to UNIX timestamp format.
* `toTimestamp(date)` Converts date to timestamp format.

Reference
https://issues.apache.org/jira/browse/CASSANDRA-9229
https://docs.datastax.com/en/cql/3.3/cql/cql_reference/timeuuid_functions_r.html

**Comment by psarna** [comment]
Oh but I did :)
~~~
create table x (a timeuuid PRIMARY KEY, b timestamp);
insert into x (a, b) values (now(), 123);
select tounixtimestamp(a), tounixtimestamp(b) from x;
~~~
works perfectly fine on current master.

`timestamptounixtimestamp()` from psarna/scylla@602aa5c commit message is exactly `toUnixTimestamp(timestamp)`, maybe it's just unfortunately worded.

**Comment by tzach** [comment]
Thanks, @psarna I was testing with 2.1 which does not have it
If its in master I will close this issue.
