### ISSUE TITLE
QUORUM query during auth. shut-down hangs if the cluster is unavailable

### ISSUE THREAD

**Issue by hakuch** [scylladb/scylla#3569]
The auth. sub-system performs some tasks asynchronously in the background during its start-up.

When the `syclla` process is terminated on a node and the sub-system is shut-down, it waits for this background task to conclude or be terminated by the `seastar::abort_source`.

As part of this background task, some `QUORUM` queries are executed to check for the need to migrate legacy auth. metadata and to create default auth. metadata. These queries are executed with infinite time-outs.

If the cluster is unavailable at the that these queries are executed and a shut-down is initiated (such that the cluster will never be available), then the query will hang indefinitely and prevent shut-down of the process on the node.

**Comment by slivne** [comment]
@gleb-cloudius - can we close this ?

**Comment by gleb-cloudius** [comment]
On Mon, Jul 16, 2018 at 12:39:39AM -0700, Shlomi Livne wrote:
> @gleb-cloudius - can we close this ?
> 
We should not run cross node queries with infinity timeout. We can
either reuse this one or open another one. From the bug description it
sound like some queries are writes and if this is the case the may still
hang.

--
			Gleb.

**Comment by hakuch** [comment]
The behavior that I observed when I wrote this issue is resolved with ac27d1c93b06bd6de860c870c4e79401db322b5a.

Therefore, I believe this issue can be closed.

I'm working on #3603 to address the infinite-timeout issue, @gleb-cloudius. I would appreciate it if you would elaborate (probably on the page for that issue) on why infinite time-outs are a problem.
