### ISSUE TITLE
nodetool listsnapshots completely broken

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#3572]
nodetool listsnapshots is not working at all, and is particularly broken with la files.

The first reason is easy: we are moving the snapshot directory name before we use it.

But even if we fix that, it still doesn't work for la files.

The reason is that we validate if the file is really an SSTable - which is a good thing, but
the la regex says this:

```
 static std::regex dir(".*/([^/]*)/(\\w+)-[\\da-fA-F]+(?:/upload)?/?");
```

But the snapshot paths have a snapshot piece. We then fail with an exception:

```
failed: invalid version for file la-24-big-Scylla.db with path /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/snapshots/1530654533804. Path doesn't match known pattern.
```

@roydahan -> we should have a dtest about this

**Comment by tzach** [comment]
Related to the change in sstable file format to Apache Cassandra 2.2 (`la`)
