### ISSUE TITLE
Support multi-column restrictions in ALLOW FILTERING

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#3574]
Currently `ALLOW FILTERING` does not implement multi-column restrictions, so it should be implemented with accompanying tests.

Note that multi-column EQ can be trivially split into a set of single column restrictions, but it's not so with IN and other restrictions.

Also note, that multi-column restrictions that include parts of primary keys or static row **and** regular columns should be handled with care, especially that filtering caches failed partition key and static row restrictions for a partition.

Refs #2025

**Comment by bura2017** [comment]
Suffer from this bug. Please fix it as soon as possible.

**Comment by slivne** [comment]
@psarna - will your change support the following as well

```
Create table tbl(id int, a text, b text, primary key ((id,a)));

Insert into tbl(id, a, b) values (1, ‘a’, ‘b’);
Insert into tbl(id, a, b) values (2, ‘a’, ‘b’);

Select * from tbl where id=1 and token(id,a) > 0 allow filtering
```

**Comment by avnerbarr** [comment]
Thanks - just to clarify, 
I want to do "efficient full table scan" per the blog post (https://www.scylladb.com/2017/02/13/efficient-full-table-scans-with-scylla-1-6/)

but while filtering on part of the partition key `partition key = ((col1,col2))`

```
select * from t1 where col1=k11 and token(col1) >= lower_range and token(col1) < upper_range allow filtering
+------+------+------+
| Col1 | Col2 | Col3 |
+------+------+------+
| k11  | k21  |  ... |
| ...  | ...  |  ... |
| k11  | k22  |  ... |
| ...  | ...  |  ... |
| k12  | ...  |  ... |
| ...  | ...  |  ... |
+------+------+------+
```

**Comment by psarna** [comment]
This change enables only multiple comparisons and multiple IN-relations and it doesn't touch token restrictions. Right now the column cannot have both token and normal relations (it will result in error message `Columns XXX cannot be restricted by both a normal relation and a token relation`) - it should be a separate issue.

**Comment by avikivity** [comment]
@psarna please file it then. It makes filtering scans impossible.

**Comment by dekimir** [comment]
Is this still relevant?  #6200 suggests that multi-column relations *are* possible (though buggy) with ALLOW FILTERING.

**Comment by psarna** [comment]
@dekimir is what relevant? This issue is closed since Feb 19.
