### ISSUE TITLE
Failed at step CAPABILITIES spawning

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#3582]
we have installed scylladb 2.1 
but , scylladb failed to start
could you check this log.
Is it related to systemd version ? 

###log
Failed at step CAPABILITIES spawning /usr/bin/scylla: Invalid argument                
scylla-server.service: main process exited, code=exited, status=218/CAPABILITIES
ExecStart=/usr/bin/scylla $SCYLLA_ARGS $SEASTAR_IO $DEV_MODE $CPUSET (code=exited, status=218/CAPABILITIES)

### systemd version 
yum list | grep systemd
oci-systemd-hook.x86_64                 1:0.1.14-1.git1ba44c6.el7 
systemd.x86_64                          219-42.el7_4.4             
systemd-libs.x86_64                     219-42.el7_4.4             
systemd-python.x86_64                   219-42.el7_4.4             
systemd-sysv.x86_64                     219-42.el7_4.4             

###cat /proc/version
Linux version 3.10.0-327.el7.x86_64 (mockbuild@x86-034.build.eng.bos.redhat.com) (gcc version 4.8.3 20140911 (Red Hat 4.8.3-9) (GCC) ) #1 SMP Thu Oct 29 17:29:29 EDT 2015

###rpm -qa | grep scylla
scylla-tools-2.1.1-20180325.29e38b3c1.el7.centos.noarch
scylla-env-1.0-1.el7.centos.noarch
scylla-tools-core-2.1.1-20180325.29e38b3c1.el7.centos.noarch
scylla-libgcc72-7.2.1-1.el7.centos.x86_64
scylla-server-2.1.1-0.20180325.cce455b1f.el7.centos.x86_64
scylla-kernel-conf-2.1.1-0.20180325.cce455b1f.el7.centos.x86_64
scylla-jmx-2.1.1-20180325.930e719.el7.centos.noarch
scylla-libstdc++72-7.2.1-1.el7.centos.x86_64
scylla-conf-2.1.1-0.20180325.cce455b1f.el7.centos.x86_64
scylla-2.1.1-0.20180325.cce455b1f.el7.centos.x86_64

**Comment by infordb** [comment]
Scylla is started when commenting as below.
/etc/systemd/system/multi-user.target.wants/scylla-server.service 
#AmbientCapabilities=CAP_SYS_NICE

**Comment by avikivity** [comment]
Ambient capabilities support was added to the kernel in version 3.10.0-408.el7. If you update to a newer version, it will work.

**Comment by infordb** [comment]
@avikivity 
The scylla 2.1 worked well in 3.10.0-327.el7. 
Since upgrading the systemd version from 219-19 to 219-42, it does not work properly, 
is it relevant to the systemd version?
We are in a difficult situation to upgrade the kernel version. 
And we have used scylla 2.1 in the 3.10.0-327.el7 version.

**Comment by avikivity** [comment]
@infordb I strongly recommend to upgrade the kernel. New kernels have fixes for bugs and security vulnerabilities.

In case that's not possible, you can drop a file called `/etc/systemd/system/scylla-server.service.d/capabilities.conf` with the contents:

```
[Service]
AmbientCapabilities=
```

and it may fix the problem. You can also downgrade systemd.

**Comment by avikivity** [comment]
Duplicate of #3486, closing. If the workaround doesn't work for you, please continue the conversation there.

**Comment by infordb** [comment]
@avikivity Thank you for a reply.
What problems can workaround that you said have ?
since scylla 2.2, Is using 3.10.0-408 or a higher version of the kernel a prerequisite ?

**Comment by avikivity** [comment]
@infordb without AmbientCapabilities support, you will have higher latency spikes.

It is not mandatory to use a new kernel, just a strong recommendation. You can apply the workaround if you wish to remain on an old kernel.

**Comment by infordb** [comment]
@avikivity 
This file does not exist on our system. The scylla-server.service.d directory also does not exist.
/etc/systemd/system/scylla-server.service.d/capabilities.conf

Can I delete AmbientCapabilities lines from this file?
/usr/lib/systemd/system/scylla-server.service

[Service]
#AmbientCapabilities=CAP_SYS_NICE
