### ISSUE TITLE
ec2 check fails in non-AMI environments

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#3584]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 2.1
Cluster size: N/A
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

scylla_setup fails on EC2 for some users not running our AMI. The reason seems to be that in the user's environment the network card is named ens3, while in the ec2_checks script, we have the following test:

```
    match = re.search(r'^driver: (\S+)$', out('ethtool -i eth0'), flags=re.MULTILINE)
```

We should add the NIC name as a parameter for this script. `scylla_setup` knows the NIC name and then it could pass down to the script.

**Comment by tzach** [comment]
@glommer what instance type?

**Comment by syuu1228** [comment]
Okay will fix.. it seems problem occurs both on shellscript implementation and current python3 implementation.
