### ISSUE TITLE
Add Scylla AMI for South America

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#3592]
Add Scylla AMI for [South America](https://sa-east-1.console.aws.amazon.com/console/home?region=sa-east-1)

**Comment by tzach** [comment]
@penberg can we add this region to teh release process?

**Comment by tzach** [comment]
There are 18 regions, with ap-northeast-1  and sa-east-1 #563 we will only have 6 regions, which is easier to manage, at least for now

**Comment by tzach** [comment]
@penberg ping (should we move this to https://github.com/scylladb/scylla-ami ?)

**Comment by penberg** [comment]
This is fixed as of 3.0.0.
