### ISSUE TITLE
combined_reader gallop mode

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#3593]
Inspired by [Timsort](https://en.wikipedia.org/wiki/Timsort).

If a particular input reader contributes a stream of fragments and keeps winning over other readers, we can enter a gallop mode where we assume it will keep winning, and instead of entering the next fragment from that reader into the heap, we can compare it against the min element of the heap and move it to the output directly, avoiding the O(log N) compares needed to heapify. If it fails the comparison, exit gallop mode and push that fragment to the heap.

This is likely to occur with time series workloads, where sstables will have disjoint runs of clustering keys. It's also likely to happen with LCS partition keys, because the lower level sstables have fewer keys per token than higher level sstables, but that's unlikely to be much help because we're only merging two sstables.

**Comment by denesb** [comment]
When there is a single reader producing fragments for the current 
partition (LCS case mentioned) we already won't have any other fragments 
to compare the produced fragments to until the next partition is reached.

In the case of disjoint clustering ranges we can fast-track the fragment 
into `_current` in `prepare_next()` to avoid the heapifying like you 
mentioned. Note that this will add an extra comparison to the worst 
(normal?) case when the heapifying still has to happen.

**Comment by avikivity** [comment]
For LCS, the problem still happens with partition_start fragments. Usually the higher level will supply 10 fragments for every fragment from the lower level. However, heapify for 2 readers is just a single compare, so nothing is saved.

For clustering keys, we can do the compare vs. _current conditional on gallop mode. Enter gallop mode if we see a reader contributing 3 fragments consecutively, exit gallop mode when the extra compare fails. The check for gallop mode should be cheap in comparison with the full key compare.

**Comment by denesb** [comment]
On 2018-07-10 11:50, Avi Kivity wrote:
> For LCS, the problem still happens with partition_start fragments. 
> Usually the higher level will supply 10 fragments for every fragment 
> from the lower level. However, heapify for 2 readers is just a single 
> compare, so nothing is saved.

partition_start fragments are never kept in the `_fragment_heap`. They 
are in a separate heap (`_reader_heap`) that is checked only when the 
current partition runs out.

> 
> For clustering keys, we can do the compare vs. _current conditional on 
> gallop mode. Enter gallop mode if we see a reader contributing 3 
> fragments consecutively, exit gallop mode when the extra compare fails. 
> The check for gallop mode should be cheap in comparison with the full 
> key compare.
> 

Yes, by keeping a separate `_in_gallop_mode` boolean we can alleviate 
the need for the extra check when we are not in gallop mode.
I think this should be fairly easy to add.

**Comment by avikivity** [comment]
> partition_start fragments are never kept in the `_fragment_heap`. They
are in a separate heap (`_reader_heap`) that is checked only when the
current partition runs out.

Well, the same principle applies. Consider a table with single-row partitions, it will be the reader heap that sees most of the action, and can benefit from the optimization (although it's less important because it's limited to range scans, and because only in LCS will we have a single sstable that dominates in terms of key density).

**Comment by avikivity** [comment]
Enhancement, removing backport candidate label.
