### ISSUE TITLE
Decommission node fails with LZ4 uncompression failure

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#3595]
*Installation details*
Installation details
Scylla version (or git commit hash): Scylla version 2.1.0 community edition
Cluster size: 12 (6 per DC)

Hardware details (for performance issues)
OS Ubuntu 16.04
Platform VM
Hardware: 4 cores, 32G RAM
Disks: (SSD/HDD) - 1TB
Problem: Decommission node fails with LZ4 uncompression failure

**Comment by avikivity** [comment]
That's too few details for us to have a chance to fix.

**Comment by tzach** [comment]
Closing as we do not have enough info to debug.
