### ISSUE TITLE
Improvement: Our 404 page needs an overhaul

### ISSUE THREAD

**Issue by lauranovich** [scylladb/scylla#3599]
Our 404 error page on our website needs a bit of fine tuning. 

1. the colors are not corporate colors.
2. the movement may be problematic. 

I like the idea of the humor, and what we can do is play up the Scylla - Charybdis connection and that the user "steered off course" and headed towards Charybdis (the cyclone) and should steer back towards Scylla immediately! by clicking a link which says - get me outta here (redirects to home page) or something else which makes for a longer time on our site.

It makes more sense over that Scylla ate the page. A 404 error can occur when the page is erased but it also can happen when the user makes a spelling mistake in the URL.

**Comment by nyh** [comment]
@lauranovich which "movement" is problematic? For me the 404 page, e.g., https://www.scylladb.com/zzz, I don't see any sort of movement or animation.
I actually like the current "ate the page" graphic, maybe just the text could be improved.
 For example, 
"Cannot find the page you asked for, maybe the Scylla Monster ate it?
 Try to find what you're looking for in Scylla's homepage"

If we can provide a **search box** to Scylla's site, it would also be nice to show that search box as an option to find the missing content.

**Comment by tzach** [comment]
@lauranovich please open this on the doc project.
@nyh checkout http://docs.scylladb.com/zzz

**Comment by nyh** [comment]
@tzach why should www.scylladb.com and docs.scylladb.com have a different 404 page designed? Looks to me like duplicated effort. The www.scylladb.com version is better, in my opinion, although I would improve the text as suggested above. And of course the docs.scylladb.com. Each 404 page can link to "/" so each one would point to the top page in the appropriate domain.
