### ISSUE TITLE
restricting_mutation_reader: more efficient `fill_buffer()`

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#3604]
`restricting_mutation_reader` is present in *all* user queries that go to sstables. It's sole purpose is to make sure readers obtain a read permit before they are created. As such it does not do any transformation to the read fragments, yet it moves them along (to the higher layers) one-by-one adding a per-fragment overhead to every read [1].
This per-fragment overhead could be easily alleviated altogether if the `restricting_mutation_reader` just did an `std::swap(_buffer, reader._impl->_buffer)` [2] in every `fill_buffer()` call. This would basically resolve to a swap of pointers.

[1] I haven't measured this so I don't know how significant this is.
[2] And a corresponding update of the respective `_buffer_size`es

**Comment by denesb** [comment]
Of course the respective `_buffer_size` members have to be swapped as well.

**Comment by geokollias** [comment]
I was thinking about something along these lines:

```
diff --git a/mutation_reader.cc b/mutation_reader.cc
index ab06852..42c54771 100644
--- a/mutation_reader.cc
+++ b/mutation_reader.cc
@@ -744,9 +744,7 @@ class restricting_mutation_reader : public flat_mutation_reader::impl {
         return with_reader([this, timeout] (flat_mutation_reader& reader) {
             return reader.fill_buffer(timeout).then([this, &reader] {
                 _end_of_stream = reader.is_end_of_stream();
-                while (!reader.is_buffer_empty()) {
-                    push_mutation_fragment(reader.pop_mutation_fragment());
-                }
+                exchange_buffer(reader);
             });
         }, timeout);
     }
```

```
diff --git a/flat_mutation_reader.hh b/flat_mutation_reader.hh
index 66201e7..1b6ff45 100644
--- a/flat_mutation_reader.hh
+++ b/flat_mutation_reader.hh
@@ -120,6 +120,11 @@ class flat_mutation_reader final {
         const circular_buffer<mutation_fragment>& buffer() const {
             return _buffer;
         }
+        void exchange_buffer(flat_mutation_reader& reader) {
+            std::exchange(_buffer_size, reader.buffer_size());
+            std::exchange(_buffer, reader.detach_buffer());
+        }
+
     private:
         static flat_mutation_reader reverse_partitions(flat_mutation_reader::impl&);
     public:
```

It's very similar to the `swap` solution but I think it's slightly more clear that lower-level reader's buffer should be empty after `fill_buffer` is done. Still, my limited C++ skills might not be helping me here.

I was wondering about:

1. Is it guaranteed that higher-level reader's `_buffer` is empty before the buffers exchange/swap? If no, we'd lose fragments.

2. AFAICS, `mutation_reader_test`'s `restricted_reader_*` tests don't care if fragments' pop/push is correct. I tested it manually by adding some logging before & after the exchanges in `exchange_buffer`. Any ideas about other tests that would exercise that part or any suggestions on better ways to test it?

3. I added `exchange_buffer` to `flat_mutation_reader::impl` because `_buffer`/`_buffer_size` are private. Please let me know if sth else would be preferred (e.g. make `_buffer`/`_buffer_size` protected).

**Comment by denesb** [comment]
Thanks for looking into this!

On Sun, 2018-10-07 at 11:34 -0700, George Kollias wrote:
> I was thinking about something along these lines:

Please post patches to the mailing list (scylladb-
dev@googlegroups.com). See 
https://github.com/scylladb/scylla/blob/master/HACKING.md#preparing-patches

If you are uncertain about whether the code works or about the approach
you took, just mark your patch as RFC (request for comments) by passing
`--rfc` to `git-format-patch`.

> diff --git a/mutation_reader.cc b/mutation_reader.ccindex
> ab06852..42c54771 100644--- a/mutation_reader.cc+++
> b/mutation_reader.cc@@ -744,9 +744,7 @@ class
> restricting_mutation_reader : public flat_mutation_reader::impl
> {         return with_reader([this, timeout] (flat_mutation_reader&
> reader) {             return reader.fill_buffer(timeout).then([this,
> &reader] {                 _end_of_stream =
> reader.is_end_of_stream();-                while
> (!reader.is_buffer_empty())
> {-                    push_mutation_fragment(reader.pop_mutation_frag
> ment());-                }+                exchange_buffer(reader);  
>            });         }, timeout);     }
> diff --git a/flat_mutation_reader.hh b/flat_mutation_reader.hhindex
> 66201e7..1b6ff45 100644--- a/flat_mutation_reader.hh+++
> b/flat_mutation_reader.hh@@ -120,6 +120,11 @@ class
> flat_mutation_reader final {         const
> circular_buffer<mutation_fragment>& buffer() const
> {             return _buffer;         }+        void
> exchange_buffer(flat_mutation_reader& reader) {

We recently added `move_buffer_content_to()` that does exactly what
this method is supposed to do. Please use that.
See: 
https://github.com/scylladb/scylla/blob/4162bff37a3188333d636a723f567f666968c5f8/flat_mutation_reader.hh#L310-L323

> +            std::exchange(_buffer_size,
> reader.buffer_size());+            std::exchange(_buffer,
> reader.detach_buffer());

`std::exchange` is equivalent to a simple assignment if its return
value is ignored.

> +        }+     private:         static flat_mutation_reader
> reverse_partitions(flat_mutation_reader::impl&);     public:It's very
> similar to the swap solution but I think it's slightly more clear
> that lower-level reader's buffer should be empty after fill_buffer is
> done. Still, my limited C++ skills might not be helping me here.
> 
> I was wondering about:
> 
> 
> 
> Is it guaranteed that higher-level reader's _buffer is empty before
> the buffers exchange/swap? If no, we'd lose fragments.

The restricted reader swaps its buffer with a lower level reader's, so
the restricted reader has to only make sure its own buffer is empty.
With `move_buffer_content_to()` however this is no longer necessary, it
works correctly with non-empty buffers too.

> 
> AFAICS, mutation_reader_test's restricted_reader_* tests don't care
> if fragments' pop/push is correct. I tested it manually by adding
> some logging before & after the exchanges in exchange_buffer. Any
> ideas about other tests that would exercise that part or any
> suggestions on better ways to test it?

I suggest using the mutation source test suite: 
https://github.com/scylladb/scylla/blob/4162bff37a3188333d636a723f567f666968c5f8/tests/mutation_source_test.hh#L30
There are several examples of how it can be set up and run on a reader
in the `tests/` directory.

> 
> I added exchange_buffer to flat_mutation_reader::impl because
> _buffer/_buffer_size are private. Please let me know if sth else
> would be preferred (e.g. make _buffer/_buffer_size protected).

Use the recently added `move_buffer_content_to()`.

**Comment by geokollias** [comment]
Ah I was playing with a version before `move_buffer_content_to` was introduced. Thanks for the pointer, will use that instead.

Two quick questions:

- When `other._buffer.empty()` in `move_buffer_content_to`, is there any reason to not do `other._buffer = detach_buffer()` (after setting the correct `_buffer_size`) so that we clear `this->buffer` instead of assigning it to `other._buffer`? We might save some memory this way, no? (I'm testing it locally)
- In general, is a new test case required for such a limited change?

Will try to send the patch soonish.

**Comment by denesb** [comment]
On Mon, 2018-10-08 at 19:40 +0000, George Kollias wrote:
> Ah I was playing with a version before move_buffer_content_to was
> introduced. Thanks for the pointer, will use that instead.
> 
> Two quick questions:
> 
> 
> When other._buffer.empty() in move_buffer_content_to, is there any
> reason to not do other._buffer = detach_buffer() (after setting the
> correct _buffer_size) so that we clear this->buffer instead of
> assigning it to other._buffer? We might save some memory this way,
> no? (I'm testing it locally)

Doing this would mean that the lower level reader, whose buffer was
detached will have to reallocate storage for its buffer on the next
fill_buffer() call. However if the buffers are swapped, no allocation
has to happen, the two buffers just swap the pointer to their
underlying storage.

> In general, is a new test case required for such a limited change?

In general it's recommended to add a test whenever the changed code
does not already have a test and it is feasible to do so (some stuff
might be very hard to test).

If the restricted reader doesn't have already (I don't recall off the
top of my head) you can add a simple test using the mutation source
test cases.

**Comment by geokollias** [comment]
>  When other._buffer.empty() in move_buffer_content_to, is there any reason to not do other._buffer = detach_buffer() (after setting the correct _buffer_size) so that we clear this->buffer instead of assigning it to other._buffer? We might save some memory this way, no? (I'm testing it locally)

Ah makes sense. Thanks.

> If the restricted reader doesn't have already (I don't recall off the top of my head) you can add a simple test using the mutation source test cases.

I couldn't find any so I decided to add one. It's based loosely on `test_combined_mutation_source_is_a_mutation_source`.

Will clean it up a bit & submit the changes.

**Comment by geokollias** [comment]
@denesb I emailed the patch to scylladb-dev@googlegroups.com yesterday, but it hasn't appeared on the ML yet. Also, I cc'ed you and another maintainer I picked from the `find-maintainer` output.

**Comment by avikivity** [comment]
It was caught by the spam filter, I let it through.

**Comment by geokollias** [comment]
Thank you @avikivity. Let's hope spam filter was incorrect :)
