### ISSUE TITLE
system.large_partitions access should be restricted to operator

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#3607]
The large_partitions table contains partition keys, which are potentially sensitive. They should be restricted to the superuser by default.

(in fact the entire system keyspace should prevent writes by non-superusers).

**Comment by slivne** [comment]
In cassandra all system tables are resitricted from being written from CQL - currently we have not blocked that.

**Comment by tzach** [comment]
> in fact the entire system keyspace should prevent writes by non-superusers

prevent from reading as well, for the reason mentioned (contains partition keys)

**Comment by StarostaGit** [comment]
What exactly do you mean by default in this case @avikivity ? With `CassandraAuthorizer` non-superusers have no permissions by default, so they cannot access the `system` keyspace in any way. Do we then want to restrict access also in the `AllowAllAuthorizer`?

**Comment by haaawk** [comment]
I understand that the whole system keyspace needs to be impossible to write by anyone using CQL and only possible to read by super-user no matter what authorizer is used. @avikivity @tzach @slivne is that the goal?

**Comment by avikivity** [comment]
> What exactly do you mean by default in this case @avikivity ? With `CassandraAuthorizer` non-superusers have no permissions by default, so they cannot access the `system` keyspace in any way. Do we then want to restrict access also in the `AllowAllAuthorizer`?

No, AllowAll allows all. If it's already restricted with CassandraAuthorizer, then there is nothing to be done.

**Comment by avikivity** [comment]
> I understand that the whole system keyspace needs to be impossible to write by anyone using CQL and only possible to read by super-user no matter what authorizer is used. @avikivity @tzach @slivne is that the goal?

It makes sense but then how would drivers learn the schema and peers table?

**Comment by haaawk** [comment]
> > I understand that the whole system keyspace needs to be impossible to write by anyone using CQL and only possible to read by super-user no matter what authorizer is used. @avikivity @tzach @slivne is that the goal?
> 
> It makes sense but then how would drivers learn the schema and peers table?

Fair point but then how does it work with `CassandraAuthorizer` when driver logs in as a user with no permissions to system keyspace. @StarostaGit have you tried that? Even a simple test using cqlsh would be sufficient. Can you select tables from system keyspace once you use cqlsh with a user created with no additional permissions and when `CassandraAuthorizer` is used?

**Comment by StarostaGit** [comment]
> Fair point but then how does it work with `CassandraAuthorizer` when driver logs in as a user with no permissions to system keyspace. @StarostaGit have you tried that? Even a simple test using cqlsh would be sufficient. Can you select tables from system keyspace once you use cqlsh with a user created with no additional permissions and when `CassandraAuthorizer` is used?
 Yes, I tried selecting from system tables as a newly created user and it's not possible, authorization error is being raised. It also aligns with what should have happened

**Comment by avikivity** [comment]
But then how does the driver work? Doesn't it need to query the system tables?

Or maybe it's just cqlsh that reads the system tables?

**Comment by haaawk** [comment]
We checked on Friday and it turns out that some tables in system keyspace are accessible for reading while others are not. I asked @StarostaGit to provide the list of all the tables grouped into two groups (accessible and not).

**Comment by StarostaGit** [comment]
1. **large_partitions** x
2. **truncated** x
3. **size_estimates** x
4. **scylla_views_builds_in_progress** x
5. **batchlog** x
6. **large_cells** x
7. **IndexInfo** x
8. **cdc_local** x
9. **sstable_activity** x
10. **peer_events** x
11. **compaction_history** x
12. **local** read only
13. **range_xfers** x
14. **scylla_local** x
15. **views_builds_in_progress** x
16. **built_views** x
17. **scylla_table_schema_history** x
18. **hints** x
19. **peers** read only
20. **clients** x
21. **large_rows** x
22. **compactions_in_progress** x

The above represent all the tables in the system keyspace and their permissions for a default, newly created role when using cqlsh (so a python driver). 'x' represents no permissions. All in all there two tables with any permissions from the get go - `peers` and `local`, both read only.

An interesting thing to note is that those permissions, albeit existent somehow, do not show up in the `system_auth.role_permissions` table.

cc: @nyh @elcallio , I saw you respond in the PR so I'm redirecting where the discussion is happening now

**Comment by haaawk** [comment]
So is my impression correct that everything's fine and we can just close the issue? Only tables required by drivers are exposed with read-only access while others are guarded? Is it the same with every authorizer @StarostaGit ?

**Comment by StarostaGit** [comment]
The above is done with the `CassandraAuthorizer`, the `AllowAll` allows everything, but that is the expected behavior (I asked about this in this thread). Are there any other authorizers we provide?

**Comment by haaawk** [comment]
dunno @dekimir ?

**Comment by StarostaGit** [comment]
(according to `scylla.yaml` nope)

**Comment by haaawk** [comment]
If the behavior of AllowAll is expected then it seems we could just close this issue (and the PR). What do you think @avikivity ?

**Comment by dekimir** [comment]
> Are there any other authorizers we provide?

We also have TransitionalAuthorizer.

**Comment by avikivity** [comment]
I think AllowAll can allow everything.

**Comment by StarostaGit** [comment]
> > Are there any other authorizers we provide?
> 
> We also have TransitionalAuthorizer.

Do I set it up the same way I set up CassandraAuthorizer (i.e. in scylla.yaml)?

**Comment by dekimir** [comment]
> > We also have TransitionalAuthorizer.
> 
> Do I set it up the same way I set up CassandraAuthorizer (i.e. in scylla.yaml)?

Yes.

> In particular, does it require the password authenticator to work?

I think it requires TransitionalAuthenticator: https://github.com/scylladb/scylla/issues/2836

**Comment by StarostaGit** [comment]
Alright
So, when using the `Transitional` duo, a full set of permissions is given to everybody. Not sure whether we want to change that, as it's purpose is only to switch from non-strict to strict auths, afaik. @avikivity ?

**Comment by avikivity** [comment]
I know nothing about TransitionalAuthenticator.

**Comment by StarostaGit** [comment]
@dekimir @haaawk what do you think?
It seems to me this could be closed as is

**Comment by haaawk** [comment]
I also know nothing about TrasitionalAuthenticator so @dekimir is the best person to decide.

Maybe you could write here a bit more detailed explanation of what this TransitionalAuthenticator is doing, @StarostaGit ?

That would help me to develop an opinion.

**Comment by haaawk** [comment]
Ok. Your description on https://github.com/scylladb/scylla/pull/7565 is enough for me. It seems that we should be able to close this issue. I'm closing it now. @avikivity @dekimir feel free to reopen if you think there's anything left to do here.
