### ISSUE TITLE
Clustering key prefix optimizations for filtering

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#3611]
There are at least two optimizations related to clustering key prefix that can be done to make filtering more efficient:
* if clustering key restrictions require filtering, but they still contain any part of the prefix, this prefix can be used to narrow down the query by using it in computing clustering bounds
* right now if an indexed query has full partition key restrictions or full primary key restrictions, it does not require filtering, because it can be optimized by adding these restrictions to the index query; this behaviour should be extended to accept any clustering key prefix too, not only the whole key.

**Comment by tgrabiec** [comment]
Can you give an example query you want to optimize? Why limit ourselves to clustering key prefixes and not allow any clustering ranges?

**Comment by psarna** [comment]
Sure - before this issue is resolved, if we have a query that restricts both an indexed column and a part of primary key, then the index is queried first and then all rows are filtered to discard those with wrong keys.

~~~
CREATE TABLE t (p int, c1 int, c2 int, v int, PRIMARY KEY (p, c1, c2));
CREATE INDEX ON t(v);

SELECT * from t WHERE v = 7 and p = 1 and c1 = 3;
~~~

Now, the index is underneath a materialized view with v as partition key and (token, p, c1, c2) as clustering keys. So the optimization is that instead of doing that under the hood:
~~~
SELECT * from t_idx WHERE v = 7;
~now filter out rows that have p = 1 and c1 = 3~
~~~

It becomes
~~~
SELECT * from t_idx WHERE v = 7 and token = computed_token_value and p = 1 and c1 = 3;
~~~
so it's faster and it's not needed to append ALLOW FILTERING anymore.

And it's a prefix because only prefix restrictions can be used in valid index query.
