### ISSUE TITLE
High rate of background writes during performance benchmark

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#3613]
*Installation details*
Scylla version (or git commit hash): 2.2.0-0.20180709.240b9f122
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0a785275

Platform (physical/VM/cloud instance type/docker): AWS i3.8xlarge

Results of performance throughput tests comparing 2.1.5 and 2.2.0 with a 1TB data set point higher latency (almost double) for a 100% write workload in 2.2.0.

During the write workload there is a very high rate of "Background writes" (accumulating up to ~ 1M) for 2 out of 3 nodes.
![screen shot 2018-07-19 at 16 08 01](https://user-images.githubusercontent.com/20959584/42944297-efb64fcc-8b6d-11e8-9a07-1d93742feacf.png)

(In 2.1 for the same test, the background writes are much lower and spikes for several minutes to around 400K).
![screen shot 2018-07-19 at 16 04 48](https://user-images.githubusercontent.com/20959584/42944138-885a5d8c-8b6d-11e8-9d5a-904a611fe8e6.png)

The test workload consist of two stages:
1. Populating 1TB of data using c-s ( -col 'size=FIXED(1024) n=FIXED(1)' -pop seq=1..1000000000")
2. Running 4 loaders of c-s writing with a gaussian distribution:
cassandra-stress write no-warmup cl=QUORUM duration=50m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate 'threads=100 limit=15000/s' -errors ignore -col 'size=FIXED(1024) n=FIXED(1)' -pop 'dist=gauss(1..1000000000,500000000,50000000)' 

Full grafana screenshot:
2.2:
![screencapture-18-232-76-46-3000-dashboard-db-scylla-per-server-metrics-nemesis-master-2018-07-19-16_36_03](https://user-images.githubusercontent.com/20959584/42945796-f45683e0-8b71-11e8-9aba-b7bfabf70911.png)

2.1:
![screencapture-34-229-108-200-3000-dashboard-db-scylla-per-server-metrics-nemesis-master-2018-07-19-16_06_09](https://user-images.githubusercontent.com/20959584/42944202-b30df00c-8b6d-11e8-8de6-d610baf30e3c.png)

**Comment by tgrabiec** [comment]
@roydahan I think you attached the same full grafana snapshot twice, they're identical

**Comment by roydahan** [comment]
Thanks, fixing.

**Comment by roydahan** [comment]
Right, the 1M isn't the rate, it's the size.

I don't think it's a slower node issue, it's constantly reproduce on 2.2 while in 2.1 not even close to this size.

**Comment by slivne** [comment]
@avikivity / @glommer - its clear that non-lsa memory is increaing because of the background writes - need your input on this.

It "should be easy" to add a read workload that will perform much worse because of less LSA memory

**Comment by slivne** [comment]
@glommer I asigned you - not sure you will chase  it but I at least you and @avikivity inputs to move forward

**Comment by slivne** [comment]
closing this as scylla has changed and backpressure has gone multiple updates since then.
