### ISSUE TITLE
counter of scylladb work differently 

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#3617]
The counter of scylladb seems to work differently than cassandra.
Once deleted, counter column values cannot be used again.
Is this the intended behavior?
It may be a problem if you are migrating from cassandra.

CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
CREATE TABLE test.cf (pk int PRIMARY KEY, my_counter counter);

### cassandra test ###
test version : apache-cassandra-3.11.2

cqlsh:test> UPDATE test.cf SET my_counter = my_counter + 6 WHERE pk = 0;
cqlsh:test> SELECT * FROM cf;

 pk | my_counter
----+------------
  0 |          6

(1 rows)
cqlsh:test> delete from test.cf where pk=0;
cqlsh:test> select * from cf;

 pk | my_counter
----+------------

(0 rows)
cqlsh:test> UPDATE test.cf SET my_counter = my_counter + 6 WHERE pk = 0;
cqlsh:test> select * from test.cf;

 pk | my_counter
----+------------
  0 |         12

(1 rows)

### scylladb  test ###
test version : scylla-2.2.rc2-1.mv.20180617.b95be056b.el7.x86_64

cqlsh> UPDATE test.cf SET my_counter = my_counter + 6 WHERE pk = 0;
cqlsh> select * from test.cf;

 pk | my_counter
----+------------
  0 |          6

(1 rows)
cqlsh> delete from test.cf where pk=0;
cqlsh> select * from test.cf;

 pk | my_counter
----+------------

(0 rows)
cqlsh> UPDATE test.cf SET my_counter = my_counter + 6 WHERE pk = 0;
cqlsh> select * from test.cf;

 pk | my_counter
----+------------

(0 rows)

**Comment by dorlaor** [comment]
+= Pawel to the thread

**Comment by pdziepak** [comment]
This is a departure from Cassandra 2.x behaviour. It doesn't seem make much sense and may be a bug. I'll investigate more.

Note however, that reusing deleted counters is most likely a bad idea, since the behaviour differs depending on whether the tombstone is present or not.

**Comment by tzach** [comment]
Apache Cassandra 2.2 gives the same result as Scylla 2.2.
Its look like a Cassandra 3.11 bug to me
see
https://issues.apache.org/jira/browse/CASSANDRA-7326
https://issues.apache.org/jira/browse/CASSANDRA-7326

**Comment by tzach** [comment]
Closing as Scylla logic makes more sense than Apache Cassandra 3.0 for this case
