### ISSUE TITLE
imr::utils::make() calls free with incorrect size on failure

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#3618]
Scylla version (or git commit hash): aab6b0ee27a7bc3fdf1d879d25291f807b4795a5

`imr::utils::make()` allocates memory and creates IMR objects:
https://github.com/scylladb/scylla/blob/6bd087facb416e0f74460278a1f3a675d96ab851/imr/utils.hh#L165-L182

Most IMR objects are not fixed size and rely on their LSA migrator to compute their size on deallocation. Usually, IMR object creation is done in three steps: first the size of the object and any buffers it may own is computed, then memory is allocated and finally the object data is written. If a creation of IMR objects requires allocation of multiple buffers and one of them fails the ones that are already allocate will be free by `imr::utils::make()`. However, sine they do not contain a valid IMR object (it is written in the third step, allocation is second), the migrator will return a meaningless value when asked for the object size.

This can be solved by using custom unique_ptr deleter that remebers the object size so that the LSA doesn't need to consult migrators.

**Comment by tzach** [comment]
@pdziepak is this critical for 2.3?

**Comment by pdziepak** [comment]
I guess it is. This can lead to memory corruption and a crash. Fix is on the mailing list.
