### ISSUE TITLE
`may_need_paging()` disables result size limiter

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#3620]
There is a bad interaction between `may_need_paging()` and query result size limiter. The former is trying to avoid the complexity of paged queries when the number of returned rows is going to be smaller than the
page size. The latter uses the fact that paged queries need not return all requested rows to limit the size of a query results. Since `may_need_paging()` may turn a paged query into non-paged one as a side effect it disables the oversized result protection.

We should limit the number of cases where `may_need_paging()` disables paging, this, however, makes #3619 worse.

**Comment by tzach** [comment]
@pdziepak is this a correctness or performance issue?
