### ISSUE TITLE
Nodetool status issue for "Load"

### ISSUE THREAD

**Issue by johnyannj** [scylladb/scylla#3624]
scylla 2.1.14

I insert 2T data to cluster.

I truncate the table and clear the data.

Create an another table,

I insert 1T data to it again,  there are only 1T data in disk.

but I get about 3T from "nodetool status"

Datacenter: DC1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens       Owns    Host ID                               Rack
UN  192.168.64.1 2.9 TB    256          ?       994ba097-e4d5-41ce-b947-a60a4e551646  myrack
UN  192.168.64.2 2.9 TB     256          ?       2b62c823-1edb-49de-97e5-72e6803b78fb  myrack
UN  192.168.64.3 2.9 TB     256          ?       1f029bcf-bdef-4887-a2a9-580ad011c73c  myrack

**Comment by avikivity** [comment]
Perhaps the data is in snapshots? Please check.

**Comment by tomer-sandler** [comment]
There are probably still 2TB worth of tombstones consuming disk space. They need to be compacted and will be deleted once `gc_grace_period` expires.

You can do the following to speed things up:
1) Run a repair to ensure tombstones are consistent
2) Decrease `gc_grace_seconds` for the relevant table ([alter table statement](http://docs.scylladb.com/getting-started/ddl/#alter-table-statement))
3) Check statistics about tombstones in `nodetool cfstats`

**Comment by johnyannj** [comment]
@tomer-sandler @avikivity 

There are no snapshot and tombstone.

I truncate  the table A, and clear snapshot.

Then insert data to table B.

There are only 1TB data  in  disk.

**Comment by tomer-sandler** [comment]
@johnyannj - how did you check that there are no tombstones (the truncated 2TB)?

**Comment by johnyannj** [comment]
@tomer-sandler  

“Turncate an table”  will introduce tombstone？  

when an table is turncated,
it is completely empty for the table,  no any sstables in disk.

Will there be a tombstone？

**Comment by tomer-sandler** [comment]
@johnyannj you are correct, I confused the default snapshot upon truncate with tombstones.
No tombstones are created upon truncate, as all the sstables are deleted.

**Comment by tzach** [comment]
@amnonh please try to repreduce

**Comment by slivne** [comment]
@amnonh can you please provide the info from which API we get the load information ? so we can map this to someone.

**Comment by amnonh** [comment]
The API in use is:
/storage_service/load_map

That is mapped to:
service::get_local_storage_service().get_load_map()

**Comment by slivne** [comment]
@asias I need your help - the computation is based on information that is sent over gossip - can you map this to the place in the code that fills this info.

**Comment by slivne** [comment]
@asias ping

**Comment by asias** [comment]
The load info is injected into the cluster by the load broadcaster:

```
service/load_broadcaster.hh:69:        if (state == gms::application_state::LOAD) {
service/load_broadcaster.hh:75:        auto* local_value = ep_state.get_application_state_ptr(gms::application_state::LOAD);                                                
service/load_broadcaster.hh:77:            on_change(endpoint, gms::application_state::LOAD, *local_value);                                                                 
service/misc_services.cc:73:            return _gossiper.add_local_application_state(gms::application_state::LOAD,   
```

**Comment by asias** [comment]
This is where we get the load info. 

```
 57 void load_broadcaster::start_broadcasting() {
 58     _done = make_ready_future<>();
 59 
 60     // send the first broadcast "right away" (i.e., in 2 gossip heartbeats, when we should have someone to talk to);
 61     // after that send every BROADCAST_INTERVAL.
 62 
 63     _timer.set_callback([this] {
 64         llogger.debug("Disseminating load info ...");
 65         _done = _db.map_reduce0([](database& db) {
 66             int64_t res = 0;
 67             for (auto i : db.get_column_families()) {
 68                 res += i.second->get_stats().live_disk_space_used;
 69             }
 70             return res;
 71         }, int64_t(0), std::plus<int64_t>()).then([this] (int64_t size) {
 72             gms::versioned_value::factory value_factory;
 73             return _gossiper.add_local_application_state(gms::application_state::LOAD,
 74                 value_factory.load(size)).then([this] {
 75                 _timer.arm(BROADCAST_INTERVAL);
 76                 return make_ready_future<>();
 77             });
 78         });
 79     });
 80 
 81     _timer.arm(2 * gms::gossiper::INTERVAL);
 82 }
```

**Comment by slivne** [comment]
@bhalevy so we found the source of where the load information in nodetool is reported - in some cases we are reporting incorrect values and this is taken from the db.column_families reported live_disk_space_used (so we may have a bug around this metric)

**Comment by bhalevy** [comment]
It looks like the stats aren't updated in the  `database::truncate -> table::discard_sstables` path.
I think that we need to update `_sstables_compacted_but_not_deleted` and then call `rebuild_statistics()`

@raphaelsc what do you think?

**Comment by raphaelsc** [comment]
@bhalevy good catch! like in compact completion, we need to call r__s() and update compacted but not deleted list, or stats will go crazy after a truncate for that table.
