### ISSUE TITLE
INSERT JSON: fails to insert JSON when there are less values, then columns in the table

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3664]
*Installation details*
Scylla version (or git commit hash): master, last commit 6b179b0

Scenario:
1. CREATE COLUMNFAMILY users (key int PRIMARY KEY, varint_clmn varint, bigint_clmn bigint, tinyint_clmn tinyint, uuid_clmn uuid, float_clmn float, inet_clmn inet, timestamp_clmn timestamp, ascii_clmn ascii, time_clmn time, boolean_clmn boolean, blob_clmn blob, smallint_clmn smallint, double_clmn double, timeuuid_clmn timeuuid, text_clmn text, decimal_clmn decimal, date_clmn date) WITH comment='test cf' AND compression = {} AND compaction={'class': 'LeveledCompactionStrategy'}

2. INSERT INTO users JSON '{"key": 0}'

Fails with error:
_Incorrect value kind in JSON INSERT statement_

Works in Cassandra

In case there are non-PK columns in the table with collection type, the error is like:
_Unexpected cqlsh error: <stdin>:4:InvalidRequest: Error from server: code=2200 [Invalid query] message="marshaling error: read_simple - not enough bytes (expected 4, got 0) Backtrace:   0x7a5478
      0x10e0284
      0x10e0dc0
      0x1f1dbd7
      0x1ac2620
      0x1be8775
      0x1be971c
      0x1bea00c
      0x1bae3f3
      0x1bc2367
      0x1bc53a5
      0x1bc769a
      0x1bca24e
      0x1bca2ac
      0x1bd1764
      0x6f6c1c
      0x58ea9e
      0x58ec61
      0x65bea7
      0x67f45a
      0x7348dd
      /lib64/libpthread.so.0+0x761a
      /lib64/libc.so.6+0x11798e_

**Comment by tzach** [comment]
@psarna please take a look

**Comment by juliayakovlev** [comment]
Still fails. How to reproduce:

1. Create schema
         
            ... CREATE TYPE t_todo_item (
            ...   label text,
            ...   details text );
         
            ... CREATE TYPE t_todo_list (
            ...   name text,
            ...   todo_list list<frozen<t_todo_item>> );

            ... CREATE TYPE t_kitchen_sink (
            ...   item1 ascii,
            ...   item2 blob,
            ...   item3 inet,
            ...   item4 text,
            ...   item5 timestamp,
            ...   item6 timeuuid,
            ...   item7 uuid,
            ...   item8 varchar,
            ...   item9 bigint,
            ...   item10 decimal,
            ...   item11 double,
            ...   item12 float,
            ...   item13 int,
            ...   item14 varint,
            ...   item15 boolean,
            ...   item16 list<int> );

            ... CREATE TABLE complex_types (
            ...   key1 text PRIMARY KEY,
            ...   mylist list<text>,
            ...   myset set<uuid>,
            ...   mymap map<text, int>,
            ...   mytuple frozen<tuple<text, int, uuid, boolean>>,
            ...   myudt frozen<t_kitchen_sink>,
            ...   mytodolists list<frozen<t_todo_list>>,
            ...   many_sinks list<frozen<t_kitchen_sink>>,
            ...   named_sinks map<text, frozen<t_kitchen_sink>> );

2. INSER JSON: INSERT INTO complex_types JSON '{"key1":"row2"}'

Error in the log and cluster went down:

scylla: types.cc:2505: collection_type_impl::mutation_view collection_type_impl::deserialize_mutation_form(bytes_view) const: Assertion `in.empty()' failed.
Aborting on shard 1.
Backtrace:
  0x00000000006907e2
  0x00000000005ac52c
  0x00000000005ac7d5
  0x00000000005ac883
  /lib64/libpthread.so.0+0x0000000000012aef
  /lib64/libc.so.6+0x000000000003766a
  /lib64/libc.so.6+0x0000000000039380
  /lib64/libc.so.6+0x000000000002f8f9
  /lib64/libc.so.6+0x000000000002f971
  0x0000000001f199e3
  0x00000000013fa41f
  0x0000000001404512
  0x000000000140a670
  0x00000000014135c8
  0x000000000126508f
  0x0000000001265c88
  0x0000000002128bc9
  0x0000000002204b67
  0x0000000002149931
  0x00000000021a6343
  0x00000000021a66f0
  0x00000000006f5a7c
  0x000000000058d8fe
  0x000000000058dac1
  0x000000000065ad07
  0x000000000067e2ba
  0x000000000073373d
  /lib64/libpthread.so.0+0x000000000000761a
  /lib64/libc.so.6+0x000000000011798e

**Comment by psarna** [comment]
I'll fix the crash in the upcoming patches, but this scenario will still not work due to not-implemented-yet tuples and user types. I opened a separate issue for that: https://github.com/scylladb/scylla/issues/3708

**Comment by juliayakovlev** [comment]
Are all fixed backported to 2.3?

**Comment by psarna** [comment]
The first iteration was, but the empty collections case is not yet merged to master (it's in /next since today)
