### ISSUE TITLE
INSERT JSON: Scylla failed to parse JSON if numeric value supplied as text

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3666]
*Installation details*
Scylla version (or git commit hash): master, last commit 6b179b0

Scenario:
1. CREATE TABLE primitive_type_test (key1 text PRIMARY KEY, col10 decimal)
2. INSERT INTO primitive_type_test JSON '{"key1": "bar", "col10": "1234.45678"}'

Cassandra successes to insert.

Scylla fails with error:
_ServerError: marshaling error: "1234.45678" must be represented as numeric in JSON_

**Comment by tzach** [comment]
@psarna please take a look

**Comment by juliayakovlev** [comment]
@duarten Still failed for int type: "ServerError: marshaling error: unable to make int from "2147483648"

**Comment by duarten** [comment]
That's expected, 2147483648 is not a signed int, is it?

**Comment by juliayakovlev** [comment]
Actually I was confused by the message "make int". It's wrong message. The column type is varint, not int. So it's expected to be succeeded.

**Comment by psarna** [comment]
I have a 3-line fix that I'll send in 10 minutes after the tests pass, so there's no need for reopening
