### ISSUE TITLE
Failure when read using toJson() from column with null value

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3667]
*Installation details*
Scylla version (or git commit hash): master, last commit 6b179b0

Scenario:
1. CREATE TABLE my_counters ( key1 text PRIMARY KEY, col1 counter,   col2 counter ) 
2. UPDATE my_counters SET col1 = col1+1 WHERE key1 = 'foo'
3. SELECT  toJson(col2) from my_counters

Error:
_Unexpected cqlsh error: <stdin>:4:ServerError: Attempt to access value of a disengaged optional object_

**Comment by tzach** [comment]
@psarna please take a look

**Comment by juliayakovlev** [comment]
@avikivity  @psarna  Is this fix backported to 2.3?

**Comment by psarna** [comment]
Yes it is: https://github.com/scylladb/scylla/commit/fd2b02a12c858b94c4de26da119aa9bf93c2b604
