### ISSUE TITLE
Add collectd configuration to seastar.yaml  / scylla.yaml

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#367]
Collectd can be set in CLI
```
--collectd-address <ip:port>  # send metrics to
--collect-hostname <name>   # metrics to appear under this name
```
But when running Scylla as a service, using command line parameter is harder.
It will be more friendly to use the config file

**Comment by tzach** [comment]
@avikivity whats the right/easy way to add parameters to scylla-server service, in particular collectd parameters?

**Comment by avikivity** [comment]
/etc/sysconfig/scylla (only for packaged scylla)

**Comment by tzach** [comment]
Thanks 
you mean /etc/sysconfig/scylla-server

**Comment by tzach** [comment]
Close with https://github.com/scylladb/scylla/commit/03caacaad023f840e4a53ab12545f57388a56001
One can do it using collectd.conf now
