### ISSUE TITLE
scylla_setup UX: Skip note should be only for interactive mode

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3674]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20180809.ad7bc313f
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu18.04

* Description
I assigned some arguments in scylla_setup commandline, it's not interactive mode, but I saw a note about skipping steps. Actually I can't skip any steps by answering 'no'.

```
scylla-test@amos-ubuntu18:~$ sudo scylla_setup --nic ens4 --disks /dev/sdb --no-cpuscaling-setup
Skip any of the following steps by answering 'no'
INFO  2018-08-08 23:47:08,260 [shard 0] iotune - /var/tmp/mnt passed sanity checks
This is a supported kernel version.
```

@syuu1228 @tzach

**Comment by syuu1228** [comment]
sent fix on ml: "[PATCH scylla] dist/common/scripts/scylla_setup: don't mention about interactive mode prompt when running on non-interactive mode"
