### ISSUE TITLE
ALLOW FILTERING does not work with prepared statements

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#3677]
Scylla version (or git commit hash): master, 55d2fdee9a3e303ce08f66a564a3bf2d10e3fde4

During filtering, restrictions are checked with values via this call:
~~~
restriction.is_satisfied_by(data, cql3::query_options({ }));
~~~
It works great for simple statements, but for prepared ones like
~~~
SELECT * FROM tab where x = ? ALLOW FILTERING
~~~
values still need to be bound from `options` parameters. Using empty `cql3::query_options({ })` will always result in an error. In order to solve that, `options` must be passed down to restrictions_filter.

_I'll handle this issue myself and I created it just as a reminder, because my queue is getting kind of big._

**Comment by avikivity** [comment]
> I'll handle this issue myself and I created it just as a reminder, because my queue is getting kind of big.

A good idea anyway if the fix will want a backport.
