### ISSUE TITLE
AMI: .scylla_ami_login: KeyError: 'red'

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3680]
*Installation details*
Scylla version (or git commit hash): 2.3.rc1-0.20180809.e4d6577ef
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI):  scylla_2018-08-09T13-18-17Z (ami-0093efe46c277ee4f)
AWS instance type: c4.large

I created an instance with latest 2.3 AMI, and I saw an error after login the instance by:
`$ ssh -i ~/.ssh/amos-ec2-key.pem centos@34.201.250.49`

```
$ ssh -i ~/.ssh/amos-ec2-key.pem centos@34.201.250.49
Last login: Thu Aug  9 22:43:06 2018 from 113.201.55.102

   _____            _ _       _____  ____  
  / ____|          | | |     |  __ \|  _ \ 
 | (___   ___ _   _| | | __ _| |  | | |_) |
  \___ \ / __| | | | | |/ _` | |  | |  _ < 
  ____) | (__| |_| | | | (_| | |__| | |_) |
 |_____/ \___|\__, |_|_|\__,_|_____/|____/ 
               __/ |                       
              |___/                        


Nodetool:
	nodetool help
CQL Shell:
	cqlsh
More documentation available at: 
	http://www.scylladb.com/doc/
By default, Scylla sends certain information about this node to a data collection server. For information, see http://www.scylladb.com/privacy/

Traceback (most recent call last):
  File "/home/centos/.scylla_ami_login", line 97, in <module>
    colorprint(MSG_UNSUPPORTED_INSTANCE_TYPE.format(type=aws.instance_class()))
KeyError: 'red'
[centos@ip-172-30-0-155 ~]$ echo $?
1
```

* .scylla_ami_login
```
MSG_UNSUPPORTED_INSTANCE_TYPE = '''
    {red}{type} is not supported instance type!{nocolor}
To continue startup ScyllaDB on this instance, run 'sudo scylla_io_setup' then 'systemctl start scylla-server'.
For a list of optimized instance types and more EC2 instructions see http://www.scylladb.com/doc/getting-started-amazon/"

'''[1:-1]

....

    if not aws.is_supported_instance_class():
        colorprint(MSG_UNSUPPORTED_INSTANCE_TYPE.format(type=aws.instance_class()))
```

Hi @syuu1228 , Python tried to get an assignment for {red}, the Shell color flag conflicts with format syntax.

**Comment by amoskong** [comment]
Similar error in scylla_setup
```
# sudo scylla_setup
....
....
Do you want to install node exporter to export Prometheus data from the node? Note that the Scylla monitoring stack uses this data
Yes - install node exporter. No - skip this  step.
[YES/no]
node_exporter already installed
Traceback (most recent call last):
  File "/sbin/scylla_setup", line 353, in <module>
    run_setup_script('node exporter', '/usr/lib/scylla/node_exporter_install')
  File "/sbin/scylla_setup", line 105, in run_setup_script
    colorprint('{red}{name} setup failed. Press any key to continue...{nocolor}'.format(name=name))
KeyError: 'red'
```

**Comment by syuu1228** [comment]
@amoskong duplicated with https://github.com/scylladb/scylla/issues/3649, fix is https://github.com/scylladb/scylla/commit/f8cec2f891f3ad66f581fbceb576e83effd8a404

**Comment by avikivity** [comment]
Closing as duplicate.

**Comment by syuu1228** [comment]
The fix is not merged on 2.3 https://github.com/scylladb/scylla/commit/ad7bc313f7bf91ee1ae434fcbf7b107e452795fa

**Comment by syuu1228** [comment]
No, I was wrong, commit id is different but it merged on branch-2.3 + next-2.3. https://github.com/scylladb/scylla/commit/f8cec2f891f3ad66f581fbceb576e83effd8a404

**Comment by amoskong** [comment]
The commit (f8cec2f
<https://github.com/scylladb/scylla/commit/f8cec2f891f3ad66f581fbceb576e83effd8a404>)
doesn't related with the following error code:


Traceback (most recent call last):
  File "/home/centos/.scylla_ami_login", line 97, in <module>

colorprint(MSG_UNSUPPORTED_INSTANCE_TYPE.format(type=aws.instance_class()))
KeyError: 'red'
[centos@ip-172-30-0-155 ~]$ echo $?
1



Question: how do we generate file ~/.scylla_ami_login for AMI instance? I
didn't find it in scylla and scylla-ami.

**Comment by syuu1228** [comment]
Fix sent for this issue: [PATCH scylla branch-2.3] dist/ami/files/.scylla_ami_login: fix python error message on unsupported instance type

**Comment by syuu1228** [comment]
@amoskong we don't generate it: https://github.com/scylladb/scylla/blob/branch-2.3/dist/ami/files/.scylla_ami_login

**Comment by amoskong** [comment]
Thanks, I saw it in branch-2.3
