### ISSUE TITLE
Multiple columns in partition key do not work with INSERT JSON

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#3687]
Scylla version (or git commit hash): master, 183d5ba1785c02f293410ee2e8ecd5e5fb877585

INSERT JSON doesn't work properly with multiple-column partition keys, because `from_single_value()` is wrongly used instead of `from_exploded` in partition key creation. 

How to reproduce:
~~~
cqlsh:keyspace1> create table z (key1 text, key2 text, c int, primary key ((key1, key2)));
cqlsh:keyspace1> insert into z json '{"key1": "x", "key2": "v"}' ;
cqlsh:keyspace1> select * from z;

 key1 | key2 | c
------+------+------
    x |      | null
    v |      | null

(2 rows)
~~~

@duarte _please assign it to me_

**Comment by tzach** [comment]
@psarna can we close this issue?

**Comment by psarna** [comment]
It will be closed automatically once my patches are merged, for now there are still in review: https://groups.google.com/forum/#!topic/scylladb-dev/9zVFfMlma3g
