### ISSUE TITLE
Scylla silently stops handling writes under load if open file limit is low

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#369]
I tested with 7 c-s processes, 22 connections and 1400 threads per proceses. Soon all clients fail with the following error message:

```
java.io.IOException: Operation x10 on key(s) [4c4d504f4b3437504e30]: Error executing: (WriteTimeoutException): Cassandra timeout during write query at consistency LOCAL_ONE (1 replica were required but only 0 acknowledged the write)

        at org.apache.cassandra.stress.Operation.error(Operation.java:216)
        at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:188)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:99)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:107)
        at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:259)
        at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)
```

There is nothing in scylla logs.

Bumping up open file limit to `100000` makes the problem not occur.

The problem is not that we don't work with low number of open files, that's acceptable, but that there is no information about the underlying cause of failure in the logs, so it's not easy to figure out why scylla stops responding.

**Comment by asias** [comment]
@slivne right now, we the limit in systemd. we can close this.

**Comment by tgrabiec** [comment]
24 wrz 2015 12:23 AM "Asias He" <notifications@github.com> napisał(a):
>
> @slivne right now, we the limit in systemd. we can close this.

This issue was more about the fact that in case we hit open file limit we
silently stop responding, whereas we should shout in logs. Was this
resolved?

**Comment by slivne** [comment]
the issue is with non ami users who try to install rpms and then have
scylla stop working.

no so lets make sure we provide a proper error message - still open.

**Comment by gleb-cloudius** [comment]
I checked and scylla is far from been silent:
ERROR [shard 0] database - failed to write sstable: Too many open files
ERROR [shard 0] database - failed to write sstable: Too many open files
ERROR [shard 0] database - failed to write sstable: Too many open files
ERROR [shard 0] database - failed to write sstable: Too many open files
ERROR [shard 0] database - failed to write sstable: Too many open files

**Comment by slivne** [comment]
Tomek - what are you getting - in your scenario ? / maybe its failing in
the read path and not the write path ?

**Comment by gleb-cloudius** [comment]
Sometimes I also see:
WARNING: exceptional future ignored of type 'std::system_error': Error system:24 (Too many open files)
I'll check where this coming from

**Comment by gleb-cloudius** [comment]
#0  report_failed_future (eptr=...) at core/reactor.cc:2101
#1  0x0000000000798843 in ~future (this=0x60000197cc70, 
    __in_chrg=<optimized out>)
    at /home/gleb/work/seastar/seastar/core/future.hh:691
#2  ~<lambda> (this=0x60000197cc70, __in_chrg=<optimized out>)
    at sstables/compaction.cc:243
#3  ~<lambda> (this=0x60000197cc50, __in_chrg=<optimized out>)
    at /home/gleb/work/seastar/seastar/core/future.hh:785
#4  ~continuation (this=0x60000197cc40, __in_chrg=<optimized out>)
    at /home/gleb/work/seastar/seastar/core/future.hh:358
#5  continuation<future<T>::then(Func&&) [with Func = sstables::compact_sstables(std::vector<lw_shared_ptr<sstables::sstable> >, column_family&, std::function<lw_shared_ptr<sstables::sstable>()>)::<lambda()>; Result = future<>; T = {}]::<lambda(auto:1&&)> >::~continuation(void) (this=0x60000197cc40, 
    __in_chrg=<optimized out>)
    at /home/gleb/work/seastar/seastar/core/future.hh:358
#6  0x0000000000477d89 in operator() (this=<optimized out>, 
    __ptr=0x60000197cc40) at /usr/include/c++/4.9.2/bits/unique_ptr.h:76
#7  reset (__p=0x60000197cc40, this=<synthetic pointer>)
    at /usr/include/c++/4.9.2/bits/unique_ptr.h:344
#8  reactor::run_tasks (this=this@entry=0x6000001df000, tasks=...)
    at core/reactor.cc:1118
#9  0x00000000004a352b in reactor::run (this=0x6000001df000)
---Type <return> to continue, or q <return> to quit---
    at core/reactor.cc:1234
#10 0x00000000004f7eeb in app_template::run_deprecated(int, char**, std::function<void ()>&&) (this=this@entry=0x7fffffffdb10, ac=ac@entry=18, 
    av=av@entry=0x7fffffffdd58, 
    func=func@entry=<unknown type in /home/gleb/work/seastar/build/release/scylla, CU 0x512632, DIE 0x5bb4e5>) at core/app-template.cc:122
#11 0x000000000041eeac in main (ac=18, av=0x7fffffffdd58) at main.cc:324

**Comment by tgrabiec** [comment]
@slivne In my tests, I got no message at all. I need to retest with latest.

**Comment by tgrabiec** [comment]
I seem to be getting error messages with scylla 0.9, so closing.

```
ERROR [shard 32] storage_proxy - exception during write: Too many open files
```
