### ISSUE TITLE
ALTER TABLE statement should allow adding or dropping multiple columns

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#3691]
The ALTER TABLE statement allows today to add (or drop) just one column at a time, e.g.,
```
ALTER TABLE tab ADD col1 int;
```
If you want to add or drop multiple columns, you have to do it in multiple statements. It would be convenient and natural to allow and do it in one, with a syntax like:
```
ALTER TABLE tab ADD (col1 int, col2 int);
```
This feature is available in Apache Cassandra since version 3.6 - see https://issues.apache.org/jira/browse/CASSANDRA-10411 - so it should also be considered a Cassandra 3 compatibility issue.

**Comment by duarten** [comment]
Duplicates #2907.
