### ISSUE TITLE
Scylla node crashes upon prepare request with multi-column IN restriction

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla#3692]
*Installation details*
Scylla version (or git commit hash): 183d5ba1785c02f293410ee2e8ecd5e5fb877585
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI):Fedora

When preparing a select statement with a multi-column in restriction, the node crashes.
The specific prepared statement that crashed the node: `SELECT a FROM t WHERE (b,c) IN ?`

A coredump is at UUID: **cac8abf1-96e9-47e9-9f86-8e3768ccbdab**

Testcase:
```
CREATE KEYSPACE blues WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
use blues;
CREATE TABLE t (a text, b text,c text, PRIMARY KEY (a, b,c));
INSERT INTO t (a, b, c) values ('A2', 'A','B');
INSERT INTO t (a, b, c) values ('A3', 'C','D');
INSERT INTO t (a, b, c) values ('A3', 'D','E');
```
Then prepare the above select statement using any client.
This happened using a python driver with the following python script:
```
from cassandra.cluster import Cluster

cluster = Cluster()

session = cluster.connect('blues');
pstatement = session.prepare("SELECT a FROM t WHERE (b,c) IN ?")
```
also happened using unitest framework: `e.prepare("select r1 from tir2 where (c1,r1) in ?;");`
Attached also the parsed bt from the crash.
[backtrace.txt](https://github.com/scylladb/scylla/files/2287394/backtrace.txt)

**Comment by tzach** [comment]
@eliransin @duarten is this even suppose to work?
My understanding of the CQL spec is IN is limited to one column.
(clearly, the server should not crash)

**Comment by eliransin** [comment]
The In statement is limited to one column only on partition keys.
It can have multi column on clustering keys (which is kind of make sense).
The C* CQL syntax spec iin the  clustering filters section states this as one of its options:
`|( column_name , column_name [, column_name ] . . . ) IN term-tuple [,term-tuple] . . . )`
I also failed to state in the issue that the same query with explicit IN clause woks.
For example:
`SELECT a FROM t WHERE (b,c) IN (('A','B'),('D','E'))`
returns:
```
 a
----
 A2
 A3
```

**Comment by eliransin** [comment]
Just noticed this is a duplicate of duplicate of #3204
