### ISSUE TITLE
ReadFailure returned due to connection problems prevents client from retrying teh request

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#3699]
*Installation details*
Scylla version (or git commit hash): f5f6cf20963fcd3090a3dfda9ed26daeed9901bb

If a request has no replicas to speculate to (because speculation is disabled or it is a range query) a connection failure during the request execution will case request to fail immediately (after commit ac27d1c93b06bd6de86) and this will prevent a client from retrying it, but retry may choose another set of replicas and succeed.

**Comment by duarten** [comment]
Don't we have an internal speculative reply? Or by client do you just mean the calling code?

**Comment by gleb-cloudius** [comment]
On Mon, Aug 20, 2018 at 02:17:16AM -0700, Duarte Nunes wrote:
> Don't we have an internal speculative reply? Or by client do you just mean the calling code?
> 
Speculative retry is not used for range reads and can be disabled for
regular reads.

--
			Gleb.

**Comment by duarten** [comment]
Ah, now I've had coffee and re-read the first sentence of the issue :)

So this is leveraging specific drivers that have themselves some speculative retry? Can't we instead return an "Unavailable exception" error?

**Comment by gleb-cloudius** [comment]
On Mon, Aug 20, 2018 at 02:49:10AM -0700, Duarte Nunes wrote:
> Ah, now I've had coffee and re-read the first sentence of the issue :)
> 
> So this is leveraging specific drivers that have themselves some speculative retry?
All of them do (configurable, but enabled by default).

> Can't we instead return an "Unavailable exception" error? 
But this is even worse. The data is available, it's just that we chose
wrong replicas (read may not use all of them). The real fix is to move
to another replica if available in read resolver and not limit ourselves
to CL replicas. Impossible to do for range reads though because of
optimization that tries to find CL set of replicas that contains multiple ranges
to minimize inter-node communication.

--
			Gleb.

**Comment by duarten** [comment]
Well, I think "unavailable" refers to nodes, not to data, but looking at the protocol description, it's not totally appropriate to use here (requires number of live nodes to be less than what's required for CL, which is not the case here).

**Comment by gleb-cloudius** [comment]
"unavailable" refers to CL. It means that the data is unavailable with
requested CL.

--
			Gleb.

**Comment by duarten** [comment]
From the protocol:

> \<required\> is an [int] representing the number of nodes that
>                            should be alive to respect \<cl\>

"Unavailable exception" is for nodes.

"Read_failure" (even the error names are inconsistent) seems to be for data, since it includes fields such as "data_present":
 
> \<data_present\> is a single byte. If its value is 0, it means
>                                the replica that was asked for data had not
>                                responded. Otherwise, the value is != 0.

**Comment by avikivity** [comment]
> Impossible to do for range reads though because of
optimization that tries to find CL set of replicas that contains multiple ranges
to minimize inter-node communication.

Let's drop this optimization. It only optimizes tiny tables where a vnode contains less than a page.

**Comment by gleb-cloudius** [comment]
On Mon, Aug 20, 2018 at 03:13:03AM -0700, Duarte Nunes wrote:
> From the protocol:
> 
> > \<required\> is an [int] representing the number of nodes that
> >                            should be alive to respect \<cl\>
> 
> "Unavailable exception" is for nodes.
> 
I do not know what you mean by "for nodes" or "for data". The above says exactly what
I said. If there is not enough live nodes for CL return this error since
no read can be started.

> "Read_failure" (even the error names are inconsistent) seems to be for data, since it includes fields such as "data_present":
This one means that when read started there were enough node for CL, but
some returned error and now CL cannot be reached any longer. "data_present" is
just an implementation detail of how digest resolving works. It request
data from only subset of nodes (usually one) and rest return only
digest. data_present indicates if data request already completed when
error was generated (timeout has the same flag). It does not say
anything about data availability. I cannot imaging why client would be
interested in this information, but for debugging it sometimes useful if
you know that data requests are usually served locally (given token
aware driver).

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Mon, Aug 20, 2018 at 03:14:05AM -0700, Avi Kivity wrote:
> > Impossible to do for range reads though because of
> optimization that tries to find CL set of replicas that contains multiple ranges
> to minimize inter-node communication.
> 
> Let's drop this optimization. It only optimizes tiny tables where a vnode contains less than a page.
> 
Let's open an issue about it. May be we can start slow by querying vnode
by vnode and move to aggregation if results are small.

--
			Gleb.

**Comment by avikivity** [comment]
> Let's open an issue about it. 

Please do, you know the most about the implications of such a change (good and bad).

**Comment by gleb-cloudius** [comment]
On Mon, Aug 20, 2018 at 03:43:09AM -0700, Avi Kivity wrote:
> > Let's open an issue about it. 
> 
> Please do, you know the most about the implications of such a change (good and bad).
> 
#3700

--
			Gleb.
