### ISSUE TITLE
Log directory 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#37]
Log should be be written to ```/var/log/scylla/system.log``` not ```/var/log/urchin.log```
to match origin convention

**Comment by tzach** [comment]
It is better user experience to have a dedicate log file, like Cassandra have.
If it is config only - even better, lets make it default config.

**Comment by avikivity** [comment]
Using the journal you can look at just scylla log entries, or intermixed system and scylla entries.  Having our own log file means we need to do log rotation, log shipping, and any other stuff that logging systems do.

Log file = for developers.

**Comment by tzach** [comment]
@avikivity make sense.
We are all fans of Systemd here.

**Comment by dorlaor** [comment]
Syslog will work for rhel and Ubuntu 14 but we need to document how to grep
our staff
