### ISSUE TITLE
Question/feature request - Adding cluster name and datacenter name to prometheus metrics

### ISSUE THREAD

**Issue by avnerbarr** [scylladb/scylla#3702]
I would like to separate our dashboards by cluster name as well as by datacenter name (maybe even rack name...)

I see labels in the prometheus metrics for "instance" name but I don't see labels for the cluster name and for the data center name.

i.e. 

```
[avner@scylladb-cluster-1-work-456cbab.use ~]$ curl -s localhost:9180/metrics | head -3
# HELP scylla_batchlog_manager_total_write_replay_attempts Counts write operations issued in a batchlog replay flow. The high value of this metric indicates that we have a long batch replay list.
# TYPE scylla_batchlog_manager_total_write_replay_attempts counter
scylla_batchlog_manager_total_write_replay_attempts{instance="scylladb-cluster-1-work-456cbab.use.dynamicyield.com",shard="0",type="derive"} 0
```

I hacked something together for filtering by cluster name using a regex on the hostname instance.

Is there a different way to do it?

**Comment by slivne** [comment]
this is part of the work toward monitoring 2.0

you can take a look at the changes in https://github.com/scylladb/scylla-grafana-monitoring/pull/357

**Comment by avnerbarr** [comment]
ok that will be very helpful
Thanks
