### ISSUE TITLE
Update static list element >= 2.0.3 - Attempted to set an element on a list which is null

### ISSUE THREAD

**Issue by rlk833** [scylladb/scylla#3703]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 2.2.0 (Scylla Docker tag: latest)
Cluster size: Docker image
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker image

I was running in 1.7.3 with no problems. When I migrated up to 2.0.3 I ran into this problem. It is preventing me from moving our production database to a new Compose cluster. Compose is currently at 2.0.3 and they don't support a new database at a lower level. We need to move to the new cluster

----------
I simplified it to:
Schema:

```
create table testlist (id text, liststatic list<text> static, id2 text, edata text, elist list<text>, primary key(id, id2));
insert into testlist (id, liststatic, id2, edata, elist) values('a', ['b'], 'c', 'd', ['e']);

```

I execute in cqlsh (Note: exact same failures occurs using gocql driver so not driver specific)

```
Contacting localhost:9042
Default keyspace for this branch is 'catalog'
Connected to  at localhost:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh:catalog> select * from testlist;

 id | id2 | liststatic | edata | elist
----+-----+------------+-------+-------
  a |   c |      ['b'] |     d | ['e']

(1 rows)
cqlsh:catalog> UPDATE testlist SET edata='uptext', liststatic[0]='up' WHERE id='a' AND id2='c';
InvalidRequest: Error from server: code=2200 [Invalid query] message="Attempted to set an element on a list which is null"
```

----
We are blocked from moving at this time.

Thank you, Rich

**Comment by duarten** [comment]
The regression was introduced in 9e88b60ef5f7e1f2ea8078cf6069dcd8f19b1069, which broke the lookup for prefetched values of lists when a clustering key is specified. Patch is on the mailing list.

**Comment by rlk833** [comment]
@duarten Thanks. This will get into the next fix releases, right? Is there a schedule for these? It will go into which releases?

**Comment by duarten** [comment]
It will at least get into 2.3, which is now in RC. @tzach will know best though, including the schedule.

**Comment by rlk833** [comment]
@tzach Hi, do you have a preliminary release plan on when 2.1.x or 2.2.x with this fix will come out? Currently, because of this bug, I can't do a disaster recovery. My DB is at level 1.7.5 in Compose, and Compose doesn't support restore a backup at 1.7.5. They are currently supporting 2.0.3. I think I could convince them to go to 2.1 or 2.2, but I can't convince them to allow a restore at 1.7.5. Also, my company, IBM, is asking to do a disaster recovery test real soon, which includes restore from backup.  Thanks, Rich Kulp

**Comment by dorlaor** [comment]
2.1 and 2.2 are out long ago and we'll release 2.3 this month. 1.7 ended
its life the millisecond 2.1 seen the light of day
