### ISSUE TITLE
Improve login username for the AMI

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#3705]
Default login to the AMI should be `scyllaadm`, not `centos`.

**Comment by tzach** [comment]
We should take advantage of #5160 
Does not make sense to switch to yet another proprietary login

**Comment by avikivity** [comment]
How is #5160 related?

**Comment by tzach** [comment]
> How is #5160 related?

Is it just the kernel, or will the AMI be based on Amazon AMI?
If the first, you can close this issue
If the second, it have a different default login (not `centos`)

**Comment by avikivity** [comment]
#5160 is about the kernel.

I don't see why I can close either issue.

What is "it" in "it can have a different default login"?

**Comment by tzach** [comment]
@syuu1228 can we close this?
This is part of https://github.com/scylladb/scylla-enterprise-machine-image/commit/de1bb48faf75fc2edbfa83dc9108d69217476a21
but AFAIK, we did not switch to Amazon Linux 2

**Comment by syuu1228** [comment]
@tzach We reverted Amazon Linux 2 patch but backported "scyllaadm" user and "centos" alias user to CentOS7, so we already have this, can close now.

**Comment by tzach** [comment]
Can approve scyllaadm login works with Scylla 4.3 AMI

**Comment by tzach** [comment]
Need to update https://www.scylladb.com/download/?platform=aws to reflect this

**Comment by tzach** [comment]
2020.1 still does not work with the new login

**Comment by tzach** [comment]
> Need to update https://www.scylladb.com/download/?platform=aws to reflect this

done
