### ISSUE TITLE
CQL JSON support for tuples and user types should be implemented

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#3708]
Scylla version (or git commit hash): 231174cda

Right now JSON support in CQL statements is supported for all types except tuples and user defined types. These should be implemented as well.

**Comment by mailmahee** [comment]
So the Kafka connect framework just uses the JSON interface of cassandra driver - and it is failing when we use this for UDT - can we look into getting this fixed?
@tzach

**Comment by fgelcer** [comment]
This is a dup of #3662, which probably can be closed as well.
