### ISSUE TITLE
Materialize view on frozen<list<text>> fails

### ISSUE THREAD

**Issue by clanstyles** [scylladb/scylla#3712]
Hey!

I'm running the latest docker container which contains:
```[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]```

If you try to make a Material view on a `frozen<list<text>>` it allows you to, but it wont ever let you insert data into the original table. You end up getting the following error:
`[shard 4] storage_proxy - exception during mutation write to 127.0.0.1: exceptions::syntax_exception (line 1:39 no viable alternative at input 'ALLOW')`

**Comment by clanstyles** [comment]
I'm running the latest tagged docker version. The date today is Aug 22nd. I believe it's version 2.2.0.

You can re-create this by creating your example table and inserting a test record.

```
CREATE TABLE testdata (
	values frozen<list<text>>,
	key text,
	PRIMARY KEY (key)
);

INSERT INTO testdata (values, key) VALUES(['test1'], 'key');
```

Then add on your materialized view and try to insert a record to the original table, this will fail.

```
CREATE MATERIALIZED VIEW testdata_by_values
AS SELECT values, key
FROM testdata
PRIMARY KEY (values, key);

INSERT INTO testdata (values, key) VALUES(['test2'], 'key1');

```

**Comment by duarten** [comment]
Unfortunately, 2.2 is ancient in terms of MV work. It seems there's a `2.3-rc1` docker container available, which should have all of the relevant fixes.

In this particular case, this is #3009, and what's missing is the `where` clause in your `create materialized view` statement. It should be:

```
CREATE MATERIALIZED VIEW testdata_by_values
AS SELECT values, key
FROM testdata
WHERE values is not null AND key is not null
PRIMARY KEY (values, key);
```
