### ISSUE TITLE
Duplication Query Result Issue

### ISSUE THREAD

**Issue by ban4785** [scylladb/scylla#3713]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 2.1.1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.3

i used same key in query after cqlsh paging off, and found that query result was duplicated.

- test query 
 select count(*) from efem_log where efem_id='EFEMserver1Thread9' and module='MD96Thread9' and **part_key in ('2018082213','2018082213');**

part_key is same = 2018082213

- test schema
CREATE TABLE sems.efem_log (
    efem_id text,
    module text,
    part_key text,
    event_time timestamp,
    seq int,
    message text,
    PRIMARY KEY ((efem_id, module, part_key), event_time, seq)
) WITH CLUSTERING ORDER BY (event_time ASC, seq ASC)

this is query result with paging off;
![duplica2](https://user-images.githubusercontent.com/20348151/44446385-2956bc00-a5d4-11e8-843c-b7becd8e9214.png)

and this is query result with paging on, it's right query result.
![duplica1](https://user-images.githubusercontent.com/20348151/44446410-468b8a80-a5d4-11e8-8fb1-eeb526ad12e5.png)

there was nothing insert transaction while testing query.
i guess querying with same partition key wasn't filtered with large fetchSize or paging off.

**Comment by duarten** [comment]
Seems  correct now, right? 1028/2 = 514

**Comment by ban4785** [comment]
actullay, i want same result with `=` Query because program has fixed preparedstatement query "select  * from efem_log where efem_id=? and module=? and part_key in (?,?)"

**Comment by duarten** [comment]
The "in" restriction works, but only if you specify different values - we had a bug that caused us to return duplicate data in that case, but the fix isn't in any released version. You can detect whether you're specifying duplicate data in your program, and use another prepared statement in that case.

**Comment by tzach** [comment]
@duarten can we close this issue?

**Comment by duarten** [comment]
Yes, but we should backport https://github.com/scylladb/scylla/commit/d734d316a6b32a5e317d1229fff32b4ce1cb2c96.

**Comment by tzach** [comment]
@duarten is this a regression in 2.3?

**Comment by duarten** [comment]
It’s not a regression, and it’s already fixed, we just need to make sure we backport the fix.

**Comment by slivne** [comment]
fixed by 7c9b9a4e24c17e8cdb8416afe4f0b7a251d2941c
