### ISSUE TITLE
Stale data can't be cleaned & the nodetool compact cost too much disk.

### ISSUE THREAD

**Issue by zhiguoxu** [scylladb/scylla#3714]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 1.6
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos7

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets=2 cores=8 hyperthreading=2 memory=192G
Disks: (SSD/HDD, count) SSD, 8T /node, used 6T / node
When I keep updating the value of data, the disk usage keeps growing up, and the old sstable containing the old value won't be cleaned up. Also the deleted data is still in the disk too, even after the default gc time(10 days). So I have to use the nodetool compact command, but it failed for no disk space left. It has cost too much disk usage (more than 2T) to complete. So any one can tell me how to release the old value and release the disk in current hardware config.

**Comment by dorlaor** [comment]
Either way 1.6 is a release that ended its life and you must upgrade anyway.

**Comment by raphaelsc** [comment]
On Wed, Aug 22, 2018 at 4:48 AM, zhiguoxu <notifications@github.com> wrote:

> This is Scylla's bug tracker, to be used for reporting bugs only.
> If you have a question about Scylla, and not a bug, please ask it in
> our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.
>
>    - [] I have read the disclaimer above, and I am reporting a suspected
>    malfunction in Scylla.
>
> *Installation details*
> Scylla version (or git commit hash): 1.6
> Cluster size: 6
> OS (RHEL/CentOS/Ubuntu/AWS AMI): centos7
>
> *Hardware details (for performance issues)* Delete if unneeded
> Platform (physical/VM/cloud instance type/docker):
> Hardware: sockets=2 cores=8 hyperthreading=2 memory=192G
> Disks: (SSD/HDD, count) SSD, 8T /node, used 6T / node
> When I keep updating the value of data, the disk usage keeps growing up,
> and the old sstable containing the old value won't be cleaned up. Also the
> deleted data is still in the disk too, even after the default gc time(10
> days). So I have to use the nodetool compact command, but it failed for no
> disk space left. It has cost too much disk usage (more than 2T) to
> complete. So any one can tell me how to release the old value and release
> the disk in current hardware config.
>

That looks like you need to enable tombstone compaction for your use case.
Which compaction strategy are you using?

**Comment by tzach** [comment]
> That looks like you need to enable tombstone compaction for your use case.
> Which compaction strategy are you using?
> 

@zhiguoxu ?

**Comment by zhiguoxu** [comment]
We are using the “SizeTieredCompactionStrategy”，is LeveledCompactionStrategy” better in this situation? 
And how to enable tombstone compaction?
Thanks!

**Comment by tzach** [comment]
@zhiguoxu its hard to say without understanding your schema and usage pattern
Take a look at http://docs.scylladb.com/architecture/compaction/compaction-strategies/#which-strategy-is-best for compaction strategy recommendation

Also, maybe the disk usage is due to snapshots? You can try `node clearsnapshot`
Make sure to copy the snapshot elsewhere is you want to keep a backup (recommended)
http://docs.scylladb.com/operating-scylla/procedures/delete_snapshot/

**Comment by zhiguoxu** [comment]
Thanks for you reply, I have read the table, but the second (Overwrite) line and the fourth line (Read-mostly, with many updates) seems a contradiction to me, because the overwrite is the same as update in our DB.

**Comment by raphaelsc** [comment]
On Mon, Aug 27, 2018 at 6:10 AM, zhiguoxu <notifications@github.com> wrote:

> We are using the “SizeTieredCompactionStrategy”，is
> LeveledCompactionStrategy” better in this situation?
> And how to enable tombstone compaction?
>

Realized version 1.6 is used. Tombstone compaction is only available from
scylla version 2.1.0 on. Do you consider upgrading scylla?
