### ISSUE TITLE
Memtable flushes for system tables can be starved of CPU

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#3715]
Scylla version: 2.2+

There are three throttling/flushing groups of memtables:
  - system
  - streaming
  - regular

memtable flushes for system and regular run under the `memtable_scheduling_group`, but the controller adjusts shares based on the occupancy of the regular memtable group. 

It can happen that regular is not under pressure, but system is. In this case the controller will incorrectly assign low shares to the memtable flush of system. This may result in high latency and low throughput for writes in that group.

**Comment by tgrabiec** [comment]
Correction, streaming doesn't run under memtable_scheduling_group, so the above applies only to the system group.

**Comment by tgrabiec** [comment]
@avikivity @glommer Do you think we need a full-blown controller for the system group, or running in main is good enough?

**Comment by glommer** [comment]
system is usually well behaved. I think it should be enough to run it in main.
the main group is indeed mostly used for system things -> specially as we move more and more things out of it.

**Comment by avikivity** [comment]
Running in main is best. System should be prioritized above everything else, and conversely, doesn't receive much traffic, so it won't impact anything.

We might want to make some tables in the system keyspaces behave like user tables (like tracing tables), but that's another issue.

**Comment by tgrabiec** [comment]
Fixed in 10f6b125c8c77b5914b4c7e52350639e027a989a
