### ISSUE TITLE
Soft-pressure memtable flusher picks unflushable memtable lists even though flushable ones exist

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#3716]
The flusher picks the memtable list which contains the largest region according to `region_impl::evictable_occupancy().total_space()`, which follows `region::occupancy().total_space()`. But only the latest memtable in the list can start flushing. It can happen that the memtable corresponding to the largest region was already flushed to an sstable (flush permit released), but not yet moved to cache, so it's still in the memtable list. The latest memtable in this group can be much smaller, there could be other lists with larger latest memtables. The flusher should consider only flushable (latest) memtables.

The latest memtable in the winning list may be small (or empty), in which case the soft pressure flusher will not be able to make much progress. This can lead to writes blocking on dirty.

I observed this for the system memtable group, where it's easy for the memtables to overshoot small soft pressure limits. The flusher kept trying to flush empty memtables, while the previous non-empty memtable was still in the group.

The CPU scheduler makes this worse, because it runs `memtable_to_cache` in a separate scheduling group, so it further defers in time the removal of the flushed memtable from the memtable list.

**Comment by glommer** [comment]
Awesome work as usual, Tomek.

Indeed of all the problems you have opened today, I think this is the most crucial one. We will have poor utilization if we are not able to start flushing a new memtable asap.

**Comment by tzach** [comment]
@tgrabiec @glommer is this a 2.3 regression compare to 2.2?

**Comment by tgrabiec** [comment]
@tzach I don't think it's a regression compared to 2.2, the soft-pressure flusher was introduced in 1.6 (f08162e181262f79c8172c77f989ea406cf4ce71). I think this issue may now be more likely to hit due to the CPU scheduler, which spreads related tasks in time more, giving the flusher more time to OOM the memory.

**Comment by glommer** [comment]
If it generates bad behavior now whereas before it didn't, it's a regression. That's regardless of whether or not the code was already there unchanged.

**Comment by tgrabiec** [comment]
@glommer For the bad behavior related to this we have a different issue: #3717. The fix for #3717 could be backported without the need for backporting the fix for this issue.
