### ISSUE TITLE
Soft-pressure flusher can cause OOM

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#3717]
As explained in https://github.com/scylladb/scylla/issues/3716, there could be soft pressure, but soft-pressure flusher may not be able to make progress. It will keep trying to flush empty memtables, which block on earlier flushes to complete, and thus allocate continuations in memory. Those continuations accumulate in memory and can cause OOM.

https://github.com/scylladb/scylla/issues/3715 makes the problem worse for system tables, because the original flush will take longer to complete. Due to scheduling group isolation the soft-pressure flusher will keep getting the CPU.

This causes bad_alloc and crashes of dtest: `limits_test.py:TestLimits.max_cells_test`

**Comment by avikivity** [comment]
Already in 3.3 and 4.0.
