### ISSUE TITLE
Flaky restricted_reader_timeout test

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3719]
The `restricted_reader_timeout_test` is flaky, and fails in debug mode with:

```
mutation_reader_test: tests/mutation_reader_test.cc:1095: restricted_reader_timeout::run_test_case()::<lambda()>: Assertion `read2_fut.failed()' failed.
```

In an over-provisioned run, nothing ensures the `sleep()` will resume after the continuations that fail the expected futures. Those checks should be in an eventually block.

Also, instead of `sleep()`ing, we should just fast-forward the clock.

**Comment by slivne** [comment]
@duarten / @tgrabiec - have we fixed this one ?

**Comment by duarten** [comment]
I don't think so.

**Comment by denesb** [comment]
I will prepare a patch.

**Comment by denesb** [comment]
Patch on the list.
