### ISSUE TITLE
Using $CASSANDRA_HOME in scylla.yaml

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#372]
We are still using $CASSANDRA_HOME in scylla.yaml
For example:

```
# Directory where Scylla should store data on disk.
# If not set, the default directory is $CASSANDRA_HOME/data/data.
data_file_directories:
    - /var/lib/scylla/data

# commit log.  when running on magnetic HDD, this should be a
# separate spindle than the data directories.
# If not set, the default directory is $CASSANDRA_HOME/data/commitlog.
commitlog_directory: /var/lib/scylla/commitlog
```

**Comment by tzach** [comment]
The doc on scylla.yaml still refer to CASSANDRA_HOME
https://github.com/scylladb/scylla/blob/master/conf/scylla.yaml#L26
https://github.com/scylladb/scylla/blob/master/tests/config_test.cc#L141

**Comment by dorlaor** [comment]
+1 to use $SCYLLA_HOME (and leave C* for backward compat)

**Comment by glommer** [comment]
As of 2019 I verified that our yaml no longer refers to CASSANDRA_HOME. We do use that string in the text but it is in a commented section that doesn't influence the output of the test anyway. Closing.
