### ISSUE TITLE
Scylla I/O Scheduler does not respect shares when used with legacy setup

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#3721]
Version affected 2.3rc1.

When the old configuration is used for the I/O Scheduler (--max-io-requests instead of YAML file), the scheduler is failing to respect the shares. Every request is being let go without proper prioritization.

**Comment by denesb** [comment]
The fix for this (https://github.com/scylladb/seastar/commit/d5ad5f84dede3a5a8abdaba4184c191b947d91d0) breaks nodes using the new configuration. See https://github.com/scylladb/scylla/issues/3718.

**Comment by glommer** [comment]
@avikivity seastar patches needed to fix this 2.3 regression:

scylladb/seastar@d5ad5f84dede3a5a8abdaba4184c191b947d91d0
scylladb/seastar@8ad870fc49b13d2657543ff09dc181634865fd05
scylladb/seastar@12f18ce06056978355f74f48c07c0286762f6523

**Comment by avikivity** [comment]
Fixed by 22396d57c228262bb85b72e64973a7620615d531.
