### ISSUE TITLE
scylla_io_setup picks too few queues leading to bottlenecks

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#3722]
Scylla_io_setup, through Seastar's IOTune picks fewer queues than it did before for many disks, by a factor of three.

The goal of the selection process in IOTune was to pick about the same number of IO queues than we did before, but we forgot to take into account that the latency goals of the scheduler are for requests to finish in 3 task quotas, and not 1.

**Comment by tzach** [comment]
@glommer I assume this is 2.3 regression and need to be fixed for 2.3. Is it so?

**Comment by glommer** [comment]
@avikivity seastar patch needed to fix this 2.3 regression: scylladb/seastar@858bef57d9c77ba7f479e8ab0aa7960b9507c4c4

**Comment by avikivity** [comment]
Fixed by 22396d57c228262bb85b72e64973a7620615d531.
