### ISSUE TITLE
Scylladb would crash when querying secondary index with large partition.

### ISSUE THREAD

**Issue by infordb** [scylladb/scylla#3726]
scylla version : scylla-server-2.3.rc1-2.filtering_for_2_3.20180813.8a9cae69b.el7.x86_64

As you can see in the schema below, the secondary index is using an inappropriate column.
it is low cardinality indexes which have few unique values.
Scylladb would crash when querying secondary index with large partition.
the schema is inefficient but the problem is that scylla crashes
Could you check the log below.

## schema
CREATE TABLE ampush.push_request (
    request_time_bound bigint,
    request_time timeuuid,
    message map<text, text>,
    messageid text,
    status text,
    statusdetails text,
    topic text,
    version text,
    PRIMARY KEY (request_time_bound, request_time)
) WITH CLUSTERING ORDER BY (request_time DESC) ;
CREATE INDEX idx_push_request_status ON ampush.push_request (status);

## partition size
* push_request 
ompacted partition maximum bytes: 49.65 MB
* idx_push_request_status_index 
Compacted partition maximum bytes: 177.92 MB

##cqlsh client log
cqlsh> select count(*) from push_request ;
 count
---------
 1199999

cqlsh> select count(*) from ampush.push_request where status='REQUEST_FINISH';
NoHostAvailable: 

## scylla server log
Aug 27 10:23:27 jangsoo02 scylla: [shard 1] seastar_memory - oversized allocation: 83886080 bytes, please report: at   0x7b3a58#012  0x73f039#012  0x744846#012  0x744d94#012  0x25d1dfe#012  0x25c933e#012  0x25c84fa#012  0x1e9674c#012  0x1e99b79#012  0x585196#012  0x585351#012  0x652a37#012  0x655be5#012  0x73da4d#012  /lib64/libpthread.so.0+0x7e24#012  /lib64/libc.so.6+0xf834c
Aug 27 10:23:27 jangsoo02 scylla: [shard 1] seastar_memory - oversized allocation: 167772160 bytes, please report: at   0x7b3a58#012  0x73f039#012  0x744846#012  0x744d94#012  0x25d1dfe#012  0x25c933e#012  0x25c84fa#012  0x1e9674c#012  0x1e99b79#012  0x585196#012  0x585351#012  0x652a37#012  0x655be5#012  0x73da4d#012  /lib64/libpthread.so.0+0x7e24#012  /lib64/libc.so.6+0xf834c
Aug 27 10:23:28 jangsoo02 scylla: Reactor stalled for 2000 ms on shard 1.
Aug 27 10:23:28 jangsoo02 scylla: Backtrace:
Aug 27 10:23:28 jangsoo02 scylla: 0x0000000000688d12
Aug 27 10:23:28 jangsoo02 scylla: 0x00000000005a3ddc
Aug 27 10:23:28 jangsoo02 scylla: 0x00000000005a4296
Aug 27 10:23:28 jangsoo02 scylla: /lib64/libpthread.so.0+0x000000000000f5df
Aug 27 10:23:28 jangsoo02 scylla: 0x0000000001ed77bd
Aug 27 10:23:28 jangsoo02 scylla: 0x0000000001e975c0
Aug 27 10:23:28 jangsoo02 scylla: 0x0000000001e99b79
Aug 27 10:23:28 jangsoo02 scylla: 0x0000000000585196
Aug 27 10:23:28 jangsoo02 scylla: 0x0000000000585351
Aug 27 10:23:28 jangsoo02 scylla: 0x0000000000652a37
Aug 27 10:23:28 jangsoo02 scylla: 0x0000000000655be5
Aug 27 10:23:28 jangsoo02 scylla: 0x000000000073da4d
Aug 27 10:23:28 jangsoo02 scylla: /lib64/libpthread.so.0+0x0000000000007e24
Aug 27 10:23:28 jangsoo02 scylla: /lib64/libc.so.6+0x00000000000f834c
Aug 27 10:23:28 jangsoo02 scylla: [shard 3] tracing - Dropped 1 sessions: open_sessions 1100, cached_records 10 pending_for_write_records 0, flushing_records 525
Aug 27 10:23:28 jangsoo02 scylla: [shard 3] tracing - Dropped 10001 sessions: open_sessions 1100, cached_records 200 pending_for_write_records 0, flushing_records 0
Aug 27 10:23:28 jangsoo02 scylla: [shard 1] tracing - Maximum records limit is hit 150001 times
Aug 27 10:23:28 jangsoo02 scylla: [shard 3] tracing - Dropped 20001 sessions: open_sessions 1100, cached_records 200 pending_for_write_records 0, flushing_records 5
Aug 27 10:23:28 jangsoo02 scylla: [shard 3] tracing - Dropped 30001 sessions: open_sessions 1100, cached_records 200 pending_for_write_records 0, flushing_records 12
Aug 27 10:23:28 jangsoo02 scylla: [shard 1] tracing - Maximum records limit is hit 160001 times
Aug 27 10:23:28 jangsoo02 scylla: [shard 3] tracing - Dropped 40001 sessions: open_sessions 1100, cached_records 200 pending_for_write_records 0, flushing_records 7
Aug 27 10:23:28 jangsoo02 scylla: [shard 1] tracing - Maximum records limit is hit 170001 times
Aug 27 10:23:28 jangsoo02 scylla: [shard 3] tracing - Dropped 50001 sessions: open_sessions 1100, cached_records 202 pending_for_write_records 0, flushing_records 6
Aug 27 10:23:28 jangsoo02 scylla: [shard 1] tracing - Maximum records limit is hit 180001 times

....
Aug 27 10:23:37 jangsoo02 scylla: Aborting on shard 1.
Aug 27 10:23:37 jangsoo02 scylla: Backtrace:
Aug 27 10:23:37 jangsoo02 scylla: 0x0000000000688d12
Aug 27 10:23:37 jangsoo02 scylla: 0x00000000005a3ddc
Aug 27 10:23:37 jangsoo02 scylla: 0x00000000005a4085
Aug 27 10:23:37 jangsoo02 scylla: 0x00000000005a4133
Aug 27 10:23:37 jangsoo02 scylla: /lib64/libpthread.so.0+0x000000000000f5df
Aug 27 10:23:37 jangsoo02 scylla: /lib64/libc.so.6+0x00000000000351f6
Aug 27 10:23:37 jangsoo02 scylla: /lib64/libc.so.6+0x00000000000368e7
Aug 27 10:23:37 jangsoo02 scylla: 0x0000000001e92a5d
Aug 27 10:23:37 jangsoo02 scylla: 0x0000000001eab91c
Aug 27 10:23:37 jangsoo02 scylla: 0x0000000001eadc81
Aug 27 10:23:37 jangsoo02 scylla: 0x0000000000585196
Aug 27 10:23:37 jangsoo02 scylla: 0x0000000000585351
Aug 27 10:23:37 jangsoo02 scylla: 0x0000000000652a37
Aug 27 10:23:37 jangsoo02 scylla: 0x0000000000655be5
Aug 27 10:23:37 jangsoo02 scylla: 0x000000000073da4d
Aug 27 10:23:37 jangsoo02 scylla: /lib64/libpthread.so.0+0x0000000000007e24
Aug 27 10:23:37 jangsoo02 scylla: /lib64/libc.so.6+0x00000000000f834c
Aug 27 10:24:12 jangsoo02 systemd-coredump: Not enough disk space for coredump of 3660 (scylla), refusing.
Aug 27 10:24:14 jangsoo02 systemd-coredump: Process 3660 (scylla) of user 997 dumped core.
Aug 27 10:24:14 jangsoo02 systemd: scylla-server.service: main process exited, code=killed, status=6/ABRT
Aug 27 10:24:14 jangsoo02 systemd: Stopped Run Scylla Housekeeping restart mode.
Aug 27 10:24:14 jangsoo02 systemd: Stopping Run Scylla Housekeeping restart mode.
Aug 27 10:24:14 jangsoo02 systemd: Stopped Run Scylla Housekeeping daily mode.
Aug 27 10:24:14 jangsoo02 systemd: Stopping Run Scylla Housekeeping daily mode.
Aug 27 10:24:14 jangsoo02 systemd: Unit scylla-server.service entered failed state.
Aug 27 10:24:14 jangsoo02 systemd: scylla-server.service failed.
Aug 27 10:24:15 jangsoo02 systemd: scylla-server.service holdoff time over, scheduling restart.
Aug 27 10:24:15 jangsoo02 systemd: Stopping Scylla JMX...
Aug 27 10:24:15 jangsoo02 systemd: scylla-jmx.service: main process exited, code=exited, status=143/n/a
Aug 27 10:24:15 jangsoo02 systemd: Unit scylla-jmx.service entered failed state.
Aug 27 10:24:15 jangsoo02 systemd: scylla-jmx.service failed.
Aug 27 10:24:15 jangsoo02 systemd: Starting Scylla Server...

**Comment by infordb** [comment]
other query 

## cqlsh log
cqlsh:ampush> SELECT count(*) FROM ampush.push_request WHERE request_time_bound = 1535001840000 AND status = 'REQUEST_FINISH';
ReadFailure: Error from server: code=1300 [Replica(s) failed to execute read] message="Operation failed for ampush.push_request - received 0 responses and 1 failures from 1 CL=ONE." info={'failures': 1, 'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}

## scylla server log
Aug 27 13:49:45 jangsoo02 scylla: [shard 3] storage_proxy - Exception when communicating with 70.60.31.206: sstable inactive read queue overloaded
Aug 27 13:49:45 jangsoo02 scylla: [shard 3] storage_proxy - Exception when communicating with 70.60.31.206: sstable inactive read queue overloaded
Aug 27 13:49:45 jangsoo02 scylla: [shard 3] storage_proxy - Exception when communicating with 70.60.31.206: sstable inactive read queue overloaded
Aug 27 13:49:45 jangsoo02 scylla: [shard 3] storage_proxy - Exception when communicating with 70.60.31.206: sstable inactive read queue overloaded
Aug 27 13:49:45 jangsoo02 scylla: [shard 3] storage_proxy - Exception when communicating with 70.60.31.206: sstable inactive read queue overloaded
Aug 27 13:49:45 jangsoo02 scylla: [shard 3] storage_proxy - Exception when communicating with 70.60.31.206: sstable inactive read queue overloaded

**Comment by tzach** [comment]
@duarten ?

**Comment by dorlaor** [comment]
It's probably due to too big memory pressure. There is actively work to add
back pressure for MV which is
the underlying tech for SI.

About collection, it's known and there is another issue for it.

**Comment by LuaiKamel** [comment]
Thank you for quick response, is this mean scylla will support SI on top of MV? 
Is it techincally possible to support small fixed size(2 elements) list/set types as primary key for base table and MV ? 
This way we will be able to fetch with the full list/set or with contains values of one of the elements.

**Comment by psarna** [comment]
It may also be related to the lack of secondary index paging in 2.3 - when querying a large partition the result may be too big.  If that's the case, then secondary index paging was merged to master just yesterday (https://github.com/scylladb/scylla/commit/e6630c627be92f863993f472122fe957d25a6b80).

**Comment by duarten** [comment]
Without a core dump or a resolved backtrace (where's scylla-server-2.3.rc1-2.filtering_for_2_3.20180813.8a9cae69b.el7.x86_64?) it's hard to say, but this are has seen a lot of fixes.

At least the "sstable inactive read queue overloaded" message seems to indicate a replica is overloaded, which can be related to how secondary indexes worked before paging was merged, like @psarna said.

**Comment by slivne** [comment]
SI paging was merged - it will be part of 3.0 you can test on the 3.0.rc1 that will be released soon @infordb once its released if you test on that version and hit it again we can reopen.
