### ISSUE TITLE
scylla-housekeeping to report version change as a metric

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#3728]
scylla housekeeping check if scylla is running the latest version. currently, it reports it's an old version to the log.

It will be better if we can also report it to the dashboard.

See: https://github.com/scylladb/scylla-grafana-monitoring/issues/294
To do so, it needs to create a metric that would indicate that scylla is running an old version.
A simple way of reporting metrics is by using the node_exporter file extension.
This way a file is placed in a specific directory and node_exporter would add it to the list of metrics it reports.

**Comment by tzach** [comment]
@amnonh not sure what is the goal here
If it is for an Alert manager to generate an alert on  running an old version: 
- I do not think its worth the effort and complexity
- The monitoring system (or Manager) can use REST to read the latest version number. With Scylla reporting its own version, it can generate an alert.

**Comment by amnonh** [comment]
The main focus is: https://github.com/scylladb/scylla-grafana-monitoring/issues/294
It will allow for the housekeeping to check for additional stuff in the future and report them.

**Comment by tzach** [comment]
As explained, it can be done by monitoring/manager, no need to add it to Scylla.
