### ISSUE TITLE
Some nodes hang after dropping a table and creating again

### ISSUE THREAD

**Issue by xuchen-plus** [scylladb/scylla#3729]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [Y] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 2.2 from the centos repo
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.4

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): AWS EC2 i3.2xlarge
Hardware: sockets=1 cores=8 hyperthreading= memory=64GB
Disks: (SSD/HDD, count): NVMe SSD * 1

When creating a table immediately after dropping it, 2 nodes out of 3 hang with high cpu usage. During this time all other operations timed out. After restarting the 2 nodes, they restore to normal.

The hung nodes have no requests being served, no IO on disk, just spinning on all cpu cores. And the syslog has the following contents:

```
8月 28 15:02:50 ip-172-31-27-184.ap-southeast-1.compute.internal scylla[1741]:  [shard 0] migration_manager - Requesting schema pull from 172.31.22.61:0
8月 28 15:03:51 ip-172-31-27-184.ap-southeast-1.compute.internal scylla[1741]:  [shard 2] migration_manager - Create new Keyspace: KSMetaData{name=user_action_offline, strategyClass=org.apache.cassandra.locator.SimpleStrategy, strategyO
ptions={replication_factor=2}, cfMetaData={}, durable_writes=1, userTypes=org.apache.cassandra.config.UTMetaData@0x6021b0e8f108}
8月 28 15:04:52 ip-172-31-27-184.ap-southeast-1.compute.internal scylla[1741]:  [shard 0] migration_manager - Requesting schema pull from 172.31.22.61:0
8月 28 15:30:40 ip-172-31-27-184.ap-southeast-1.compute.internal scylla[1741]:  [shard 3] migration_manager - Create new Keyspace: KSMetaData{name=offline, strategyClass=org.apache.cassandra.locator.SimpleStrategy, strategyOptions={replication_factor=2}, cfMetaData={}, durable_writes=1, userTypes=org.apache.cassandra.config.UTMetaData@0x60300105e648}
8月 28 15:31:36 ip-172-31-27-184.ap-southeast-1.compute.internal scylla[1741]:  [shard 3] migration_manager - Create new ColumnFamily: org.apache.cassandra.config.CFMetaData@0x6031bc949c00[cfId=65311f80-aa94-11e8-816f-000000000004,ksName=user_action,cfName=tmp,cfType=Standard,comparator=org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType(616474797065:org.apache.cassandra.db.marsh
......
```

**Comment by slivne** [comment]
@xuchen-plus - I am closing this issue as we do not have additional info - it woud be very appreciated if you could provide the additional info.
