### ISSUE TITLE
Scylla 2.3 one shard at very high latency compared to all others

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla#3730]
*Installation details*
Scylla version (or git commit hash): 2.3 rc1
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

*Hardware details (for performance issues)*         
Platform (physical/VM/cloud instance type/docker): i3.8xlarge 
Disks: (SSD/HDD, count): 2x 1900 nvme

Running a mixed stress against the 2.3 AMI, I ran into a situation where the latency average seemed to be too high, compared to 2.2

Digging in deeper to the shard level, we found that while latency was much better on 2.3, there was a single shard on each node that had a very high latency, which messed up the average (see graphs attached, especially 2.3-overview).

The load was generated by 4 loaders reading and 4 writing, one reader and one writer for each of the 4 keyspaces. 

Write command: cassandra-stress write no-warmup cl=QUORUM duration=180m -schema 'keyspace=keyspace1 replication(factor=3)' -mode cql3 native -rate 'threads=200 limit=20000/s' -errors ignore -pop 'dist=gauss(1..1000000000,500000000,5000000)' -node $NODES

Read command: cassandra-stress read no-warmup cl=QUORUM duration=180m -schema 'keyspace=keyspace1 replication(factor=3)' -mode cql3 native -rate 'threads=200 limit=20000/s' -errors ignore -pop 'dist=gauss(1..1000000000,500000000,5000000)' -node $NODES

[2.3-overview.pdf](https://github.com/scylladb/scylla/files/2332409/2.3-overview.pdf)

UPDATE: Managed to reproduce the issue with a single loader hitting only one keyspace, with a read load the read latencies have a single shard higher than others and the same goes with a write load. 

UPDATE2: After restarting the nodes, the issue seems to be gone, rewarming the cache to see if it will reproduce afterwards again

**Comment by dyasny** [comment]
Sicne I could not reproduce the issue, closing for now

**Comment by tgrabiec** [comment]
@dyasny Do you still have the prometheus database with the metrics?

**Comment by dyasny** [comment]
@tgrabiec yes, I replied to you in slack with the link
