### ISSUE TITLE
Difficult in compiling ScyllaDB

### ISSUE THREAD

**Issue by Dragonslair5** [scylladb/scylla#3733]
Hi,

I would like to know what is the best environment to compile ScyllaDB.
What GCC version? What libboost version? is there some container in DockerHub that is "ready" to clone ScyllaDB from github and compile?

---------

I followed the steps shown in [this page](https://www.scylladb.com/download/#source), but with no success.

Most of the problems that I encountered seems to be related with some incompatibility with libboost, similar to this thread-> #3505 

I already tried with Ubuntu 16.04 and 18.04, and CentOS 7.5.
gcc version 7.3.1
libboost 1.55, 1.63 and 1.66.
The Scylla version is the one from the "master" branch with hash 8dea1b3c6104b42baf4d12d48e04465dce0a2692

The "best attempt" I believe was with CentOS 7.5 and libboost 1.63, that stops with the following error:

> [126/555] LINK (stripped) build/release/tests/log_heap_test
> FAILED: build/release/tests/log_heap_test 
> g++  -O3 --param inline-unit-growth=300 -DXXH_PRIVATE_API -I. -I build/release/gen -I seastar -I seastar/build/release/gen -s  -fuse-ld=gold  -L/home/mauricio/ScyllaDB/scylla/seastar/build/release -L/home/mauricio/ScyllaDB/scylla/seastar/build/release/fmt/fmt -Wl,--whole-archive,-lseastar,--no-whole-archive -lfmt -std=gnu++1z -g  -Wall -Werror -Wno-error=deprecated-declarations -fvisibility=hidden -Wno-attributes -pthread -I/home/mauricio/ScyllaDB/scylla/seastar -U_FORTIFY_SOURCE  -gz -march=nehalem -fconcepts -I/home/mauricio/ScyllaDB/scylla/seastar/fmt -DBOOST_TEST_DYN_LINK -Wno-ignored-attributes -Wno-overloaded-virtual -Wno-maybe-uninitialized -Wno-error=cpp -Wno-stringop-overflow -DSEASTAR_HAVE_GCC6_CONCEPTS -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_NUMA -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT  -Wl,--no-as-needed     -lboost_program_options -lboost_system -lboost_filesystem -lstdc++ -lm -lstdc++fs -lboost_thread -lcryptopp -lrt -lgnutls -lgnutlsxx -llz4 -lprotobuf -ldl -lgcc_s  -lyaml-cpp -lhwloc -lnuma -lpciaccess -lxml2 -lz -lcares-seastar -lfmt -o build/release/tests/log_heap_test build/release/tests/log_heap_test.o utils/arch/powerpc/crc32-vpmsum/crc32.S seastar/build/release/libseastar.a -lyaml-cpp -llz4 -lz -lsnappy -ljsoncpp -lboost_filesystem  -lcrypt  -lcryptopp -lboost_date_time -lsystemd -lboost_unit_test_framework 
> /usr/local/include/boost/test/tree/test_unit.hpp:249: error: undefined reference to 'boost::unit_test::test_case::test_case(boost::unit_test::basic_cstring<char const>, boost::unit_test::basic_cstring<char const>, unsigned long, boost::function<void ()> const&)'
> tests/log_heap_test.cc:98: error: undefined reference to 'boost::unit_test::ut_detail::auto_test_unit_registrar::auto_test_unit_registrar(boost::unit_test::test_case*, boost::unit_test::decorator::collector&, unsigned long)'
> tests/log_heap_test.cc:42: error: undefined reference to 'boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
> tests/log_heap_test.cc:48: error: undefined reference to 'boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
> tests/log_heap_test.cc:49: error: undefined reference to 'boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
> tests/log_heap_test.cc:55: error: undefined reference to 'boost::test_tools::tt_detail::report_assertion(boost::test_tools::assertion_result const&, boost::unit_test::lazy_ostream const&, boost::unit_test::basic_cstring<char const>, unsigned long, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, unsigned long, ...)'
> collect2: error: ld returned 1 exit status
> [129/555] CXX build/release/tests/sstable_3_x_test.o
> ninja: build stopped: subcommand failed.

**Comment by slivne** [comment]
@Dragonslair5 - closing this issue - if you have followup questions please post and we can reopen
