### ISSUE TITLE
Timed-out background reads are shown as foreground in the metrics

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#3734]
The foreground reads metric is derived from the number of live read executors - background reads. Background reads are counted down when their resolver times out. However, a read executor may still be around for a while, resulting in such reads being accounted as foreground.

Usually, the gap in which this happens is short, because executor reference holders timeout quickly as well. It's not always the case though. For instance, local read executor doesn't time out quickly when the target shard has an overloaded CPU, and it takes a while before the request goes through all the queues, even if IO is not involved. Observed in https://github.com/scylladb/scylla/issues/3628#issuecomment-415441770

**Comment by tgrabiec** [comment]
@tzach how is #3419 related?

**Comment by tzach** [comment]
> @tzach how is #3419 related?

In the sense that is hard (for me) to understand what foreground and backgrounds means. Not more than that.
