### ISSUE TITLE
dtest/repair_additional_test fail: fail to stop auth_service

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3736]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20180901.659322684
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

* Description:
    * Two dtest subtests failed in stopping node, it seems the problem exists in stopping `_auth_service`
[repair_additional_test.RepairAdditionalTest.repair_option_pr_multi_dc_test](http://jenkins.cloudius-systems.com:8080/view/scylla-master/job/scylla-master-dtest/label=scylla-dtest,mode=release,smp=2/855/testReport/junit/repair_additional_test/RepairAdditionalTest/repair_option_pr_multi_dc_test/)
[repair_additional_test.RepairAdditionalTest.repair_abort_test ](http://jenkins.cloudius-systems.com:8080/view/scylla-master/job/scylla-master-dtest/label=scylla-dtest,mode=release,smp=2/855/testReport/junit/repair_additional_test/RepairAdditionalTest/repair_abort_test/)

```
File "/jenkins/workspace/scylla-master-dtest/label/scylla-dtest/mode/release/smp/2/urchin-ccm/ccmlib/scylla_node.py", line 465, in stop
    raise NodeError("Problem stopping node %s" % self.name)
```

* repair_abort_test scenario:

  - create cluster of 3 nodes
  - create keyspace / table
  - add data only on node1 (stop node2 & node3)
  - add data only on node2 (stop node1 & node3)
  - add data only on node3 (stop node1 & node2)
  - start node1 & node2
  - check keyspace number  (`problem occurred in this step`, we will stop nodes in this step)
  - wait to find the repari stream sessions
  - abort repair sessions by `storage_service/force_terminate_repair`
  - check keyspace number to know if the repair is abort

* Fail log of dtest ([repair_additional_test:RepairAdditionalTest.repair_abort_test](https://github.com/scylladb/scylla-dtest/blob/master/repair_additional_test.py#L1656))

```
2018-09-02 02:02:56.652782 going to run tests sequentially
repair_abort_test (repair_additional_test.RepairAdditionalTest) ... 2018-09-02 02:02:56.656591 cluster ccm directory: /home/amos/.dtest/dtest-tMJcTG
2018-09-02 02:03:23.414773 CREATE COLUMNFAMILY cf (key varchar PRIMARY KEY, c2 text, c1 text) WITH comment='test cf' AND compression = {} AND read_repair_chance=0.000000
2018-09-02 02:03:24.730749 Adding data only on node 1...
2018-09-02 02:04:13.710454 Adding data only on node 2...
2018-09-02 02:04:51.304074 Adding data only on node 3...
2018-09-02 02:06:10.120083 starting repair...
2018-09-02 02:06:16.298391 Before Repair - node1, keys num: 3000
2018-09-02 02:06:44.851115 Before Repair - node3, keys num: 3000
ERROR

======================================================================
ERROR: repair_abort_test (repair_additional_test.RepairAdditionalTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/amos/space/scylla-dtest/repair_additional_test.py", line 2062, in repair_abort_test
    return RepairAdditionalBase._repair_abort_test(self)
  File "/home/amos/space/scylla-dtest/repair_additional_test.py", line 1739, in _repair_abort_test
    checking_keys_num('Before Repair')
  File "/home/amos/space/scylla-dtest/repair_additional_test.py", line 1716, in checking_keys_num
    node.stop(wait_other_notice=True)
  File "/home/amos/space/scylla-ccm/ccmlib/scylla_node.py", line 465, in stop
    raise NodeError("Problem stopping node %s" % self.name)
NodeError: Problem stopping node node3

----------------------------------------------------------------------
Ran 1 test in 383.326s

FAILED (errors=1)
```

* database log of node3:

```
....
INFO  2018-09-02 02:07:11,896 [shard 0] compaction_manager - Asked to stop
INFO  2018-09-02 02:07:11,896 [shard 0] compaction_manager - Stopped
INFO  2018-09-02 02:07:11,896 [shard 0] view - Stopping view builder
INFO  2018-09-02 02:07:11,896 [shard 0] storage_service - Drain on shutdown: starts
INFO  2018-09-02 02:07:11,896 [shard 0] storage_service - Stop transport: starts
INFO  2018-09-02 02:07:11,896 [shard 0] gossip - My status = NORMAL
INFO  2018-09-02 02:07:11,896 [shard 0] gossip - Announcing shutdown
INFO  2018-09-02 02:07:11,896 [shard 0] storage_service - Node 127.0.0.3 state jump to normal
INFO  2018-09-02 02:07:12,897 [shard 0] rpc - client 127.0.0.1: fail to connect: Connection refused
INFO  2018-09-02 02:07:13,923 [shard 0] storage_service - Stop transport: stop_gossiping done
INFO  2018-09-02 02:07:13,923 [shard 0] storage_service - Thrift server stopped
INFO  2018-09-02 02:07:13,924 [shard 0] storage_service - CQL server stopped
INFO  2018-09-02 02:07:13,924 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2018-09-02 02:07:13,926 [shard 0] storage_service - messaging_service stopped
INFO  2018-09-02 02:07:13,926 [shard 0] storage_service - Stop transport: shutdown messaging_service done
INFO  2018-09-02 02:07:13,926 [shard 0] storage_service - stream_manager stopped
INFO  2018-09-02 02:07:13,926 [shard 0] storage_service - Stop transport: shutdown stream_manager done
(END)
```

```
future<> storage_service::stop_transport() {
    return run_with_no_api_lock([] (storage_service& ss) {
        return seastar::async([&ss] {
            slogger.info("Stop transport: starts");

            gms::stop_gossiping().get();
            slogger.info("Stop transport: stop_gossiping done");

            ss.shutdown_client_servers().get();
            slogger.info("Stop transport: shutdown rpc and cql server done");

            ss.do_stop_ms().get();
            slogger.info("Stop transport: shutdown messaging_service done");

            ss.do_stop_stream_manager().get();
            slogger.info("Stop transport: shutdown stream_manager done");

            ss._auth_service.stop().get();
            slogger.info("Stop transport: auth shutdown");

            slogger.info("Stop transport: done");
        });
    });
}
```

@hakuch @nyh  @asias

**Comment by amoskong** [comment]
This problem still exists in 2.3 test, job link: [job/scylla-2.3-dtest/38/label=scylla-dtest,mode=release,smp=1/testReport/repair_additional_test/RepairAdditionalTest/repair_abort_test/](http://jenkins.cloudius-systems.com:8080/job/scylla-2.3/job/scylla-2.3-dtest/38/label=scylla-dtest,mode=release,smp=1/testReport/repair_additional_test/RepairAdditionalTest/repair_abort_test/)

**Comment by slivne** [comment]
in abort it always happens - in other tests 

http://jenkins.cloudius-systems.com:8080/view/scylla-2.3/job/scylla-2.3/job/scylla-2.3-dtest/label=scylla-dtest,mode=release,smp=1/lastCompletedBuild/artifact/urchin-dtest/logs-release.1/1536040850984_repair_test.TestRepair.simple_parallel_repair_test/node1.log

**Comment by hakuch** [comment]
I'm investigating this issue.

I wasn't able to reproduce failures in `repair_option_pr_multi_dc_test` locally on `master`, but I was able to reproduce failures in `repair_abort_test`.

It's possible that the issue is related to request time-outs, or it may be an issue in the RPC code similar to the one that caused the previous dtest failures with shut-down.

I'll provide an update once I have more information.

**Comment by hakuch** [comment]
Tentatively, I've identified the issue and I'm verifying both the error and its resolution on `branch-2.3`.

**Comment by hakuch** [comment]
I verified the patch I sent on the [mailing list](https://groups.google.com/d/msg/scylladb-dev/AKfunuwDTr8/PahX5PA1AgAJ) applies to path `master` and `branch-2.3` and resolves the dtests that I was able to reproduce locally.
