### ISSUE TITLE
scylla_raid_setup: No such file or directory: '/etc/systemd/system/scylla-server.service.d/mounts.conf

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3738]
*Installation details*
Scylla version (or git commit hash): 2.3~rc2-0.20180902.5eb4fde2d-0ubuntu1~trusty
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 14 & Ubuntu 16 & Debian 8 & Debian 9

This problem doesn't exist in CentOS7 ([job/scylla-2.3-centos-rpm-test/label=muninn/52](http://jenkins.cloudius-systems.com:8080/job/scylla-2.3/job/2.3-test/job/scylla-2.3-centos-rpm-test/label=muninn/52/artifact/latest/job.log))

* Job links
   [job/scylla-2.3-ubuntu-deb-test/label=huginn/30/](http://jenkins.cloudius-systems.com:8080/job/scylla-2.3/job/2.3-test/job/scylla-2.3-ubuntu-deb-test/label=huginn/30/artifact/latest/job.log)
   [job/scylla-2.3-ubuntu-deb-16.04-test/label=huginn/32/ 
](http://jenkins.cloudius-systems.com:8080/job/scylla-2.3/job/2.3-test/job/scylla-2.3-ubuntu-deb-16.04-test/label=huginn/32/artifact/latest/job.log)
   [job/scylla-2.3-debian-deb-9-test/label=huginn/26/](http://jenkins.cloudius-systems.com:8080/job/scylla-2.3/job/2.3-test/job/scylla-2.3-debian-deb-9-test/label=huginn/26/artifact/latest/job.log)
   [job/scylla-2.3-debian8-deb-test/label=huginn/43/
](http://jenkins.cloudius-systems.com:8080/job/scylla-2.3/job/2.3-test/job/scylla-2.3-debian8-deb-test/label=huginn/43/artifact/latest/job.log)

* Scylla-setup log:
```
2018-09-02 18:43:28,133 | Running '/usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/vdb --no-cpuscaling-setup'
18:43:29,748 | INFO  2018-09-02 18:43:29,735 [shard 0] iotune - /var/tmp/mnt passed sanity checks
......
18:43:59,495 | W: mdadm: /etc/mdadm/mdadm.conf defines no arrays.
18:44:18,635 | Processing triggers for ufw (0.34~rc-0ubuntu2) ...
18:44:18,769 | Processing triggers for libc-bin (2.19-0ubuntu6.14) ...
18:44:22,315 | meta-data=/dev/vdb               isize=256    agcount=4, agsize=983040 blks
18:44:22,315 |          =                       sectsz=512   attr=2, projid32bit=0
18:44:22,315 | data     =                       bsize=4096   blocks=3932160, imaxpct=25
18:44:22,315 |          =                       sunit=0      swidth=0 blks
18:44:22,315 | naming   =version 2              bsize=4096   ascii-ci=0
18:44:22,315 | log      =internal log           bsize=4096   blocks=2560, version=2
18:44:22,315 |          =                       sectsz=512   sunit=0 blks, lazy-count=1
18:44:22,315 | realtime =none                   extsz=4096   blocks=0, rtextents=0
18:44:22,329 | Creating XFS volume for scylla using 1 disk(s): /dev/vdb
18:44:22,351 | Traceback (most recent call last):
18:44:22,351 |   File "/usr/lib/scylla/scylla_raid_setup", line 152, in <module>
18:44:22,351 |     with open(mounts_conf, 'w') as f:
18:44:22,351 | FileNotFoundError: [Errno 2] No such file or directory: '/etc/systemd/system/scylla-server.service.d/mounts.conf'
18:44:22,367 | Your current Scylla release is 2.3.rc2, while the latest patch release is 2.3, and the latest minor release is 2.2 (recommended)
18:44:22,367 | RAID setup failed.
```

**Comment by tzach** [comment]
@syuu1228 please take a look
