### ISSUE TITLE
how to make secondary index?

### ISSUE THREAD

**Issue by joyplux24** [scylladb/scylla#3739]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

CentOS 7.x

$ docker run --name scylla -d scylladb/scylla --experimental 1

$ docker exec -it scylla bash

$ cqlsh

Connected to  at 172.17.0.4:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.

cqlsh> CREATE KEYSPACE ks WITH REPLICATION = {'class' : 'SimpleStrategy', 'replication_factor' : 1};

cqlsh> CREATE TABLE ks.users (
  userid uuid,
  name text,
  email text,
  country text,
  PRIMARY KEY (userid)
);

cqlsh> INSERT INTO ks.users (userid, name, email, country) VALUES (uuid(), 'Bondie Easseby', 'beas...@house.gov', 'France');

cqlsh> INSERT INTO ks.users (userid, name, email, country) VALUES (uuid(), 'Demetri Curror', 'dcur...@techcrunch.com', 'France');

cqlsh> INSERT INTO ks.users (userid, name, email, country) VALUES (uuid(), 'Langston Paulisch', 'lpaul...@reverbnation.com', 'United States');

cqlsh> INSERT INTO ks.users (userid, name, email, country) VALUES (uuid(), 'Channa Devote', 'cdev...@marriott.com', 'Denmark');

cqlsh> SELECT * FROM ks.users;

 userid                               | country       | email                       | name
--------------------------------------+---------------+-----------------------------+-------------------
 4d0652bd-bea2-43cf-8f72-bcce03103d91 |        France |         beas...@house.gov |    Bondie Easseby
 c09b663a-6535-41bf-a865-98d0851e87fb | United States | lpaul...@reverbnation.com | Langston Paulisch
 7590f82f-bf83-4fb8-a5bd-8fe081cd44ae |       Denmark |      cdev...@marriott.com |     Channa Devote
 940d0c14-3ba3-450a-806a-57e7f2621dae |        France |     dcur...@techcrunch.com |    Demetri Curror

(4 rows)

cqlsh> CREATE INDEX ON ks.users (email);
cqlsh> CREATE INDEX ON ks.users (country);

cqlsh> SELECT * FROM ks.users WHERE email = 'beas...@house.gov';

 userid | country | email | name
--------+---------+-------+------

(0 rows)

cqlsh> desc ks.users;

CREATE TABLE ks.users (
    userid uuid PRIMARY KEY,
    country text,
    email text,
    name text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
CREATE INDEX users_email_idx ON ks.users (email);
CREATE INDEX users_country_idx ON ks.users (country);

CREATE MATERIALIZED VIEW ks.users_email_idx_index AS
    SELECT email, userid
    FROM ks.users
    WHERE email IS NOT NULL
    PRIMARY KEY (email, userid)
    WITH CLUSTERING ORDER BY (userid ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW ks.users_country_idx_index AS
    SELECT country, userid
    FROM ks.users
    WHERE country IS NOT NULL
    PRIMARY KEY (country, userid)
    WITH CLUSTERING ORDER BY (userid ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

http://docs.scylladb.com/using-scylla/secondary-indexes/

What is wrong?

I would be grateful for any advice!

**Comment by duarten** [comment]
What version of Scylla are you using? It seems it's one without view building, where creating an index (or materialized view) on a table won't cause existing data to be indexed.

**Comment by joyplux24** [comment]
[root@localhost ~]# docker exec -it scylla bash
[root@26208d7d61c3 /]# scylla --version
2.2.0-0.20180705.240b9f122

Thank's for reply

**Comment by duarten** [comment]
Please try the 2.3-rc1 tag. It should include view building, so your example should work. However, note secondary indexes are still experimentals and some limitations apply.

**Comment by joyplux24** [comment]
great!! it's work. thank you :)
