### ISSUE TITLE
Filtering ranges with descending clustering order yields wrong results

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#3741]
*Installation details*
Scylla version (or git commit hash): 6593226849352ce4560adc2e3723da19e3b6e5e8

When clustering order is set to be `DESC`, range filtering on clustering keys doesn't accept enough rows.

Reproduce with:
~~~
CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true; use ks;

CREATE TABLE t (p1 int, p2 int, c1 int, c2 int, v int, PRIMARY KEY((p1, p2), c1, c2)) WITH CLUSTERING ORDER BY (c1 DESC);

INSERT INTO t (p1, p2, c1, c2, v) values (1, 1, 1, 7, 3);
INSERT INTO t (p1, p2, c1, c2, v) values (1, 2, 2, 0, 1);
INSERT INTO t (p1, p2, c1, c2, v) values (1, 3, 3, 5, 4);

SELECT * FROM t WHERE c1 > 1 ALLOW FILTERING;

 p1 | p2 | c1 | c2 | v
----+----+----+----+---
~~~

Note that equality filtering works fine, it's just `<` and `>` operators that fail. My educated guess is that maybe the clustering order is not properly passed to `restrictions_filter`, so restriction checks with a regular type rather than reversed one, which in turn filters out wrong rows.

**Comment by psarna** [comment]
@tzach you can also assign me, I wrote this code in the first place and I'll take a look at it now

**Comment by avikivity** [comment]
Is 2.3 vulnerable?

**Comment by psarna** [comment]
No it isn't, my filtering series weren't part of 2.3.
