### ISSUE TITLE
Data missing after resharding

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#3744]
*Installation details*
Scylla version (or git commit hash): master
Cluster size: 1 node / 4 nodes

Data missing after resharding.

Tests in resharding_tests.py:
- resharding_by_smp_increase_test - resharding with SMP increasing
- resharding_by_smp_decrease_test - resharding with SMP decreasing

Test scenario:
- run writes into a table 
- validate that the table has expected rows number
- start resharding and wait for resharding has been finished
- run reads from the table 
- validate rows number again. 
The test fails on this validation with error like: " 98762.0 not greater than or equal to 100000"

This test performs with all compaction strategies, on 1 node and 4 nodes clusters

The problem is not reproduced every run

**Comment by denesb** [comment]
Can you link the problem to one particular configuration? Or does it happen randomly?

**Comment by juliayakovlev** [comment]
Increase SMP test: increase SMP from 5 to 9
Decrease SMP test: decrease SMP from 5 to 2

The tests are performed with all compaction strategies.
Last failure happened for LCS on the cluster with 1 node

But it were another failures - report from August 9:
- STCS on 1 node cluster (increase SMP)
- DTCS on 4 nodes cluster (decrease SMP)

Also in the status email from Aug 9 additional failure was reported:
created table with counter columns and performed resharding with SMP increasing (DTCS on 1 node cluster). Error: "Expecting counter1 = 40000, got 40004"

As we can see it happened pretty randomly

**Comment by juliayakovlev** [comment]
I can't reproduce it yet. I saw it happened just in the Jenkins run

**Comment by slivne** [comment]
after multiple attempts the issue seems to be in cassandra-stress not in the resharding process.

once resharding completes we have two different scans to validate the data
1. using cassandra-stress
2. using select count(*)

The issue is the cassandra-stress when invoked with a specific n=X may report at the end less partitions.

- I was able to reproduce this using the cassandra-stress we have against cassandra 3.11.2

```
END
shlomi@localhost~/scylla-tools-java/tools/bin (branch-2.3)$ ./cassandra-stress read n=100000  no-warmup -rate threads=16 -port jmx=7101
Sleeping 2s...
Running READ with 16 threads for 100000 iteration
Connected to cluster: cas-1, max pending requests per connection 128, max connections per host 8
Datatacenter: datacenter1; Host: localhost/127.0.0.1; Rack: rack1
Failed to connect over JMX; not collecting these stats
type,      total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
total,          1096,    1095,    1095,    1095,    13.9,     6.8,    47.0,   113.8,   123.7,   125.3,    1.0,  0.00000,      0,      0,       0,       0,       0,       0
total,          2630,    1478,    1478,    1478,    11.0,     6.4,    37.5,    78.7,   116.3,   146.6,    2.0,  0.10534,      0,      0,       0,       0,       0,       0
total,          5355,    2673,    2673,    2673,     5.9,     3.4,    19.7,    38.8,   100.4,   137.3,    3.1,  0.22179,      0,      0,       0,       0,       0,       0
total,          9129,    3638,    3638,    3638,     4.4,     2.5,    15.0,    35.1,    48.9,    49.7,    4.1,  0.22600,      0,      0,       0,       0,       0,       0
total,         13121,    3903,    3903,    3903,     4.1,     3.0,    12.4,    23.1,    48.3,    69.8,    5.1,  0.19621,      0,      0,       0,       0,       0,       0
total,         20415,    7186,    7186,    7186,     2.2,     1.2,     7.7,    14.5,    34.3,    60.7,    6.1,  0.24604,      0,      0,       0,       0,       0,       0
total,         31537,   11035,   11035,   11035,     1.4,     0.9,     4.2,     9.6,    18.6,    25.9,    7.1,  0.27938,      0,      0,       0,       0,       0,       0
total,         42922,   11099,   11099,   11099,     1.4,     0.8,     4.0,    11.0,    19.4,    27.7,    8.2,  0.25353,      0,      0,       0,       0,       0,       0
total,         54271,   11284,   11284,   11284,     1.4,     0.9,     4.1,     9.6,    15.2,    18.3,    9.2,  0.22646,      0,      0,       0,       0,       0,       0
total,         65956,   11502,   11502,   11502,     1.4,     0.8,     3.9,     9.2,    15.4,    25.1,   10.2,  0.20333,      0,      0,       0,       0,       0,       0
total,         77604,   11481,   11481,   11481,     1.4,     0.8,     3.8,     9.4,    16.6,    23.4,   11.2,  0.18366,      0,      0,       0,       0,       0,       0
total,         88502,   10810,   10810,   10810,     1.5,     0.8,     4.5,    10.7,    16.4,    22.6,   12.2,  0.16640,      0,      0,       0,       0,       0,       0
total,         99996,   11427,   11427,   11427,     1.4,     0.8,     3.8,    10.6,    18.0,    38.5,   13.2,  0.15260,      0,      0,       0,       0,       0,       0


Results:
op rate                   : 7566 [READ:7566]
partition rate            : 7566 [READ:7566]
row rate                  : 7566 [READ:7566]
latency mean              : 2.1 [READ:2.1]
latency median            : 1.0 [READ:1.0]
latency 95th percentile   : 7.1 [READ:7.1]
latency 99th percentile   : 17.8 [READ:17.8]
latency 99.9th percentile : 49.2 [READ:49.2]
latency max               : 146.6 [READ:146.6]
Total partitions          : 99996 [READ:99996]
Total errors              : 0 [READ:0]
total gc count            : 0
total gc mb               : 0
total gc time (s)         : 0
avg gc time(ms)           : NaN
stdev gc time(ms)         : 0
Total operation time      : 00:00:13
END
```

The number iterations requested is 100000 and that is what c-s prints when it starts, yet at the end the total # of partitions reported is only 99996

As such we will change the test and not validate the "Total partitions" and only check that the c-s completed successfully and that error count is zero.
