### ISSUE TITLE
SyntaxError: no viable alternative at input 'toDate'

### ISSUE THREAD

**Issue by MasterGroosha** [scylladb/scylla#3747]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [*] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 2.3.rc2-0.20180820.b47d18f9f
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 18.04.1 LTS (Server uses UTC time)

Let's say I have the following table:
```sql
CREATE TABLE Session (
PKInsertTime timestamp,
PKInsertSeqNum int,
SomeNum int
PRIMARY KEY(PKInsertTime, PKInsertSeqNum)
);
```

After inserting some values I see:
```
|       PKInsertTime       |   PKInsertSeqNum  |    SomeNum   |
| 2018-09-04 13:20:00+0000 |         5         |       10     |
```

And while I'm trying to query: 
`SELECT * from Session WHERE toDate(PKInsertTime) = '2018-09-04'`
I get `SyntaxException: line 1:53 no viable alternative at input '2018-09-04'`

I tried reverse order: 
`SELECT * from Session WHERE '2018-09-04' = toDate(PKInsertTime)`
Same error.

**Comment by avikivity** [comment]
These queries are not legal and cannot be efficiently implemented. Scylla searches its tables using a hash of the partition key; the hash of toDate(pkInsertTime) has no relationship to hash(pkInsertTime) and so can't be used to search the table.

For more help, please contact the mailing list.
You'll need to remodel the data, perhaps with a partition key consisting of the insert date and a clustering key consisting of a timestamp or a timeuuid.

**Comment by MasterGroosha** [comment]
@avikivity I'm afraid you didn't get me right: `toDate(PKInsertTime)` will return Date object, right? Then I'm comparing it with '2018-09-08' which is a valid Date interpretation.

There's no hash comparison.

**Comment by avikivity** [comment]
First, pkInsertTime is a timestamp, not a date.

If you want an equality comparison, don't use a function.

```
cqlsh:keyspace1> CREATE TABLE Session ( PKInsertTime timestamp, PKInsertSeqNum int, SomeNum int, PRIMARY KEY(PKInsertTime, PKInsertSeqNum) );
cqlsh:keyspace1> insert into session (pkinserttime , pkinsertseqnum , somenum ) values ('2018-09-04 13:20:00+0000', 5, 10);
cqlsh:keyspace1> select * from session where pkinserttime = '2018-09-04 13:20:00+0000';

 pkinserttime             | pkinsertseqnum | somenum
--------------------------+----------------+---------
 2018-09-04 13:20:00+0000 |              5 |      10

(1 rows)
```

**Comment by MasterGroosha** [comment]
@avikivity 

![default](https://user-images.githubusercontent.com/2780044/45043309-82632d00-b075-11e8-9bdc-ec8b4ebbe62c.png)

I have another experience.

**Comment by avikivity** [comment]
`timestamp` has millisecond precision, so:
 - if the key was inserted with non-zero millisecond part, it's impossible to retrieve using the string representation
 - the numeric (unixtime) representation has to be multiplied by 1000 to get milliseconds, and you have to get the millisecond part right.

```
cqlsh:keyspace1> select * from session  where pkinserttime = 1536067200;

 pkinserttime | pkinsertseqnum | somenum
--------------+----------------+---------

(0 rows)
cqlsh:keyspace1> select * from session  where pkinserttime = 1536067200000;

 pkinserttime             | pkinsertseqnum | somenum
--------------------------+----------------+---------
 2018-09-04 13:20:00+0000 |              5 |      10

```
