### ISSUE TITLE
Improve error message

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#3748]
If invalid prepared statements are sent down to Scylla, we will return the following exception:

```
        throw exceptions::invalid_request_exception("Invalid amount of bind variables");
```

It can be the case that users may not know where did they made the mistake in their code. Scylla could help them, by making this exception a lot more verbose, and saying exactly what was expected and what was found.

**Comment by withings-sas** [comment]
I agree especially since I have the case where the same query will fail in Scylla but succeed in Cassandra... How can I debug this ?

**Comment by jul-stas** [comment]
Hi @glommer, I can easily tell the number of parameters (expectation vs. reality), but do you think it's enough? Perhaps you have something more on your mind?

**Comment by avikivity** [comment]
Cosmetic change, so not backporting. Removing backport candidate label.
