### ISSUE TITLE
Querying secondary index ignores WHERE restrictions

### ISSUE THREAD

**Issue by MasterGroosha** [scylladb/scylla#3754]
- [*] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version: 2.3.rc2-0.20180820.b47d18f9f
Cluster size: 1 
OS: Ubuntu 18.04.1 LTS

**TL;DR:**
![default](https://user-images.githubusercontent.com/2780044/45151506-33350d80-b1d7-11e8-9903-fd71e6083088.png)

Now text:
First, we create a sample table:
`CREATE TABLE mytest (mdate timestamp, num1 int, num2 int, PRIMARY KEY (mdate, num1));`
`mdate` is partition key and `num1` is clustering column.

Populating tables:
```sql
INSERT INTO mytest (mdate, num1, num2) VALUES ('2018-01-01', 1, 1);
INSERT INTO mytest (mdate, num1, num2) VALUES ('2018-01-01', 2, 2);
INSERT INTO mytest (mdate, num1, num2) VALUES ('2018-01-01', 3, 3);
INSERT INTO mytest (mdate, num1, num2) VALUES ('2018-01-02', 1, 1);
INSERT INTO mytest (mdate, num1, num2) VALUES ('2018-01-02', 2, 2);
INSERT INTO mytest (mdate, num1, num2) VALUES ('2018-01-02', 3, 3);
```
Now we have 6 rows in total. Let's query rows from 1st Jan 2018:
`SELECT * FROM mytest WHERE mdate = '2018-01-02';`
3 rows found - correct. 

Let's restrict out query a bit:
`SELECT * FROM mytest WHERE mdate = '2018-01-02' AND num1 = 1;`
1 row found - correct.

Hmm..can we query with num2 instead of num1?
`SELECT * FROM mytest WHERE mdate = '2018-01-02' AND num2 = 1;`
ServerError: No index found.

Whoa, let's create index then!
`CREATE INDEX ON mytest (num2);`

So, let's query again:
`SELECT * FROM mytest WHERE mdate = '2018-01-02' AND num2 = 1;`
2 rows found - **INCORRECT**!

The last query ignores `mdate` restriction and searches only by num2 which is obviously incorrect behaviour.

**Comment by psarna** [comment]
The problematic query works correctly on current master branch (ab361e9897b149641bdf4dba9b09fe3c48fe64e5):
~~~
cqlsh:keyspace1>  SELECT * FROM mytest WHERE mdate = '2018-01-02' AND num2 = 1;

 mdate                    | num1 | num2
--------------------------+------+------
 2018-01-01 23:00:00+0000 |    1 |    1

~~~
I think it might have to do with changes introduced along with `ALLOW FILTERING`, which is not part of 2.3.

**Comment by MasterGroosha** [comment]
@psarna Thank you for the answer! I've performed a more complex test and want to share results with you. 

My setup:
```CREATE TABLE mytest (mdate TIMESTAMP, num1 INT, num2 INT, num3 INT,
PRIMARY KEY (mdate, num1));
CREATE INDEX ON mytest (num2);
INSERT INTO mytest (mdate, num1, num2, num3) values ('2018-01-01', 1, 1, 1);
INSERT INTO mytest (mdate, num1, num2, num3) values ('2018-01-02', 2, 2, 2);
INSERT INTO mytest (mdate, num1, num2, num3) values ('2018-01-03', 3, 3, 3);
```
Here `mdate` is **partition key**, `num1` is **clustering column**, `num2` has **secondary index** and `num3` is just a column without any extra features.
I performed multiple SELECT queries like "SELECT * FROM mytest WHERE {extra params}".
So, for example, when I write `num1+num2` I mean `SELECT * FROM mytest WHERE num1={...} AND num2 = {...}`. + sign means I used "AND" modifier.

Here are bugs (?) I found:
1. When I query `mdate + num2` I have wrong result. 
For example: `SELECT * FROM mytest WHERE mdate = '2018-01-03' AND num2 = 1` must return 0 rows, but it returns `2018-01-01 1 1 1`. It ignores mdate and searches exclusively by num2.

2. When I query `num1 + num2`, I have duplicate lines as if I queried these columns separately and then concatenated. Screenshot:
![default](https://user-images.githubusercontent.com/2780044/45157880-02f76a00-b1eb-11e8-948c-7a479e6c14e6.png)
(I used `allow filtering` because Scylla asks me to add it to query string)

3. `num2 + num3`. Same as (1). Query works only for `num2`. `mdate` is ignored.

4. `mdate + num1 + num2`. Same as (1). Query works only for `num2`. Everything else is ignored.

5. `mdate + num1 + num2 + num3`. Same as (1). Query works only for `num2`. Everything else is ignored.

**Comment by psarna** [comment]
All these queries work fine on current master (ab361e9897b149641bdf4dba9b09fe3c48fe64e5). 2.3-rc2 doesn't contain `ALLOW FILTERING` patches and secondary indexes are still marked experimental, hence the inconsistencies. 

Enhanced filtering support is planned for the next release (ref: https://www.scylladb.com/2018/08/16/upcoming-enhancements-filtering-implementation/).

**Comment by MasterGroosha** [comment]
@psarna gotcha! Is 2.3 release planned this month?

**Comment by avikivity** [comment]
@psarna at least, 2.3 should reject those queries instead of returning incorrect results.

**Comment by psarna** [comment]
@avikivity True, but they're all the result of indexes being experimental and the problems date back before any of my filtering patches. I could prepare some hotfixes for 2.3 indexing, so they refuse these kinds of queries, if necessary.

**Comment by avikivity** [comment]
Please do, if it's simple. They'll miss 2.3, but can make it into 2.3.1.

**Comment by slivne** [comment]
will be part of 2.3.1
