### ISSUE TITLE
Error applying view update to other cluster node after server reboot

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#3756]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):  2.2.0-0.20180705.240b9f122
Cluster size: 3, RF=2
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7

*Hardware details (for performance issues)*         
Platform (physical/VM/cloud instance type/docker): VMWare ESXi 5.5
Hardware: 16 cores, 32gb RAM
Disks: SSD x1

One of our customers wanted to increase the hardware resources available to their cluster of Scylla servers running on VMWare ESXi.  We told them to increase the hardware at the hypervisor layer and reboot each server one at a time, checking nodetool status after each server reboot to ensure that all three nodes were = UN.  We probably should have told them to nodetool drain each node first before rebooting it but I forgot about that  Everything looked fine until they did a load test and in one hour there were hundreds of thousands of errors that looked like this in the journalctl log:

scylla[1428]:  [shard 5] view - Error applying view update to [remote IP]: exceptions::mutation_write_timeout_exception (Operation timed out for [MV name] - received only 0 responses from 1 CL=ONE.)

Tons and tons of those errors.  The interesting thing is that these timeouts were only ever for materialized views, never base tables.  And only for a few views, not all views (although its possible some base tables with views did not get updated during this time).  The individual nodes themselves did not appear distressed and did not report any timeouts executing operations locally, only when trying to apply a view update to a remote node.  Node 1 had many errors applying view updates to nodes 2 and 3.  Node 2 had many errors applying view updates to nodes 1 and 3.  And Node 3 had many errors applying view updates to nodes 1 and 2.  

I suspect this is related to the shutdown / restart procedure because we didn't drain before rebooting.  But nodetool status reports all nodes "UN" so its not like they are out of sync or experiencing connectivity issues.  There were also a bunch of reactor stalls in the log when the server first started up prior to the keyspace population but I'm not sure if those are related or unrelated.  I see some hints about potentially related issues such as #3080 but in this case the node was rebooted and all three nodes were present while the errors were being thrown.

**Comment by veramine** [comment]
We tried 'systemctl restart scylla-server' on each of the three nodes in sequence and they all restarted with no errors but then when we started the load test again the same errors came back.  So a simple restart was not enough to fix the issue.  I just keep thinking it is something like the view metadata has gotten corrupted or something so the changes to the base table are going to the wrong server or something.  I am guessing we could probably drop all the views and recreate them and it would probably work but I'd rather try to repair if possible.  It sounds like the infrastructure team powered off the servers using vSphere to add more cpu's and ram so scylla may have gotten interrupted while trying to write something important, not sure.

**Comment by duarten** [comment]
Hard to figure out what's going on without metrics for that cluster, but if I had to guess, the view replica was overloaded (#2538).

**Comment by veramine** [comment]
We resolved the issue by issuing a "fake" materialized view alter table statement to "reset" the views.  We just did this for every view:

ALTER materialized view schema.view with comment='test';

That seems to have resolved this issue.

**Comment by duarten** [comment]
I don't understand how that could have helped with timeout issues. Are there maybe other errors in the view replica's logs that you didn't paste?

**Comment by veramine** [comment]
Turns out you were right (as usual).  The alter materialized view statements did not fix the problematic views.  The error is back again.  I've uploaded an example journalctl log to the following:

http://upload.scylladb.com/E959FBF8-91B0-41D4-B483-52C253C9EBD1/log1209.txt

As you can see, there was one additional error just as the node was starting, before the schema even loaded:

```
seastar::backtrace_buffer::append_backtrace() at /usr/src/debug/scylla-2.2.0/seastar/core/reactor.cc:303
 (inlined by) print_with_backtrace at /usr/src/debug/scylla-2.2.0/seastar/core/reactor.cc:324
seastar::reactor::block_notifier(int) at /usr/src/debug/scylla-2.2.0/seastar/core/reactor.cc:615
?? ??:0
logalloc::segment_zone::try_creating_zone() at /usr/src/debug/scylla-2.2.0/utils/logalloc.cc:530 (discriminator 2)
logalloc::segment_pool::allocate_segment() at /usr/src/debug/scylla-2.2.0/utils/logalloc.cc:770
logalloc::segment_pool::segment_pool() at /usr/src/debug/scylla-2.2.0/utils/logalloc.cc:903
__tls_init at /usr/src/debug/scylla-2.2.0/utils/logalloc.cc:1031
 (inlined by) ?? at /usr/src/debug/scylla-2.2.0/utils/logalloc.cc:1031
 (inlined by) logalloc::shard_tracker() at /usr/src/debug/scylla-2.2.0/utils/logalloc.cc:301
 (inlined by) logalloc::tracker_reclaimer_lock::tracker_reclaimer_lock() at /usr/src/debug/scylla-2.2.0/utils/logalloc.cc:261
 (inlined by) operator() at /usr/src/debug/scylla-2.2.0/utils/logalloc.cc:2247
repeat<logalloc::region_group::start_releaser()::<lambda()>::<lambda()> > at /usr/src/debug/scylla-2.2.0/seastar/core/future-util.hh:281
 (inlined by) operator() at /usr/src/debug/scylla-2.2.0/utils/logalloc.cc:2253
 (inlined by) apply at /usr/src/debug/scylla-2.2.0/seastar/core/apply.hh:36
 (inlined by) apply<logalloc::region_group::start_releaser()::<lambda()> > at /usr/src/debug/scylla-2.2.0/seastar/core/apply.hh:44
 (inlined by) apply<logalloc::region_group::start_releaser()::<lambda()> > at /usr/src/debug/scylla-2.2.0/seastar/core/future.hh:1362
operator()<seastar::future_state<> > at /usr/src/debug/scylla-2.2.0/seastar/core/future.hh:943
 (inlined by) run_and_dispose at /usr/src/debug/scylla-2.2.0/seastar/core/future.hh:413
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/src/debug/scylla-2.2.0/seastar/core/reactor.cc:2500
seastar::reactor::run_some_tasks() at /usr/src/debug/scylla-2.2.0/seastar/core/reactor.cc:2910
seastar::reactor::run_some_tasks() at /opt/scylladb/include/c++/7/chrono:377
 (inlined by) seastar::reactor::run() at /usr/src/debug/scylla-2.2.0/seastar/core/reactor.cc:3057
seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const at /usr/src/debug/scylla-2.2.0/seastar/core/reactor.cc:4002
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::posix_thread::start_routine(void*) at /usr/src/debug/scylla-2.2.0/seastar/core/posix.cc:52
?? ??:0
?? ??:0
?? ??:0
```

Here's the count of timeouts by view name:

```
   2 veraminetest.network_connections6_remoteaddress_idx_index
  10 veraminetest.session_info_by_customerguid
  16 veraminetest.portallogins_email_idx_index
  25 veraminetest.unsigned_unscanned_detected_binaries_bycustomer
 607 veraminetest.network_connections6_remoteport_idx_index
1760 veraminetest.network_connections6_lowerprocessbasename_idx_index
2510 veraminetest.network_connections6_processguid_idx_index
5318 veraminetest.detections_by_systemguid
5387 veraminetest.detections_by_usersid
18377 veraminetest.network_connections6_hostid_idx_index
65519 veraminetest.processexittime_by_processguid
158344 veraminetest.services_systemguid
```

We don't have the full monitoring stack running in this environment, unfortunately, because it is a disconnected environment and we couldn't get an offline build working for the version of CentOS we have running here.  But are there specific metrics that you would suggest we fetch?  Prometheus is running but we just can't get the grafana stuff running unfortunately.

**Comment by duarten** [comment]
That backtrace is from a reactor stall (an operation that's taking over 2 seconds), but if it's happening only during boot it's not a concern. I see there are some oversized allocations too, which are maybe mutations (would have to decode the backtraces).

Do you have the logs from the view replicas?

**Comment by veramine** [comment]
I will decode more of the backtraces.  In the meantime, I have uploaded the logs from all three nodes (running with RF=2) we hit this issue last week.  Thanks!

http://upload.scylladb.com/E959FBF8-91B0-41D4-B483-52C253C9EBD1/logs.zip

**Comment by veramine** [comment]
I've attached a file here with all the backtraces from those three logs decoded.  The first backtrace was hit 45 times but that is most likely just the thing during boot hit once per core (3 nodes, hit on cores 1-15)

Thanks.

[decoded.txt](https://github.com/scylladb/scylla/files/2376247/decoded.txt)

**Comment by duarten** [comment]
No other errors in the logs, which makes me think those are legitimate timeouts due to overloaded (#2538). There are 274035 timeouts and it was a stress test, so presumably the load is high.

Regarding the stalls, the recurring one is zone allocation, which we got rid of (252c5dfa52).

I also see some related to  `database::apply_with_commitlog` (3) and `column_family::query` (1), but hard to say if they're actual issues.

**Comment by veramine** [comment]
We are going to try to get the stats.  In particular:

- foreground_writes
- background_writes
- requests_blocked_memory
- dirty_bytes

Also, I see there is some progress toward #2538 checked into the 2.3 branch.  We will see if we can replace one of the 2.2 nodes with a new 2.3 node and see if we still see the same timeouts there.

**Comment by veramine** [comment]
We were able to reproduce this issue again on the same three-node Scylla 2.2 cluster and this time captured the monitoring stack metrics.  We are not sure the best way to interpret these metrics at the time of the flood of timeouts in the log.  The 95th percentile and 99th percentile write latencies seem great but those read latencies, yikes!  Any suggestions on the best way to get more throughput from this cluster?  

I've also uploaded the logs corresponding to these performance metrics at http://upload.scylladb.com/3DEB5027-1A49-47EF-9DED-07F52F626360/logs1809.zip.  These logs have the same type of error messages as the previous logs.

<img width="1359" alt="1" src="https://user-images.githubusercontent.com/26036714/45671448-48187780-bada-11e8-8472-67ad0c6f57ef.png">
<img width="1358" alt="2" src="https://user-images.githubusercontent.com/26036714/45671458-4f3f8580-bada-11e8-88da-1a428bff80c6.png">
<img width="1358" alt="3" src="https://user-images.githubusercontent.com/26036714/45671463-54043980-bada-11e8-8d61-ce6e01559fb5.png">
<img width="1361" alt="4" src="https://user-images.githubusercontent.com/26036714/45671470-58c8ed80-bada-11e8-84a7-41d99b9d969e.png">
<img width="1357" alt="5" src="https://user-images.githubusercontent.com/26036714/45671475-5cf50b00-bada-11e8-9589-dc3dda9cbfba.png">

**Comment by duarten** [comment]
Yeah, this is clearly #2538. You can see the writes being accumulated in memory.

Is the benchmark write-only or are there reads too?

**Comment by veramine** [comment]
This test is both reads and writes

**Comment by duarten** [comment]
The read-before-write for MVs likely interfere with the read workload, so you see those abysmal read latencies. I think 2.3 will also help here, though the work done there in this area was mostly meant to avoid the read timeouts.

**Comment by veramine** [comment]
Okay we will try to upgrade this cluster to 2.3.  Thanks!

**Comment by slivne** [comment]
@duarten - is this related to the write backpressure mechanism or something else ?

**Comment by duarten** [comment]
@slivne Yep.

**Comment by nyh** [comment]
@slivne @duarten isn't this a dup (with additional information) of #2538, i.e., view-update flow control?

**Comment by slivne** [comment]
It is closing this
