### ISSUE TITLE
when use twcs and all dimenisons in primary key, will led to no gc old expired sstables

### ISSUE THREAD

**Issue by xmm1989218** [scylladb/scylla#3763]
I use jaeger and use scylladb replacing cassandra, I get some problems.

below is one schema which can't gc fine:

CREATE TABLE IF NOT EXISTS ${keyspace}.tag_index (
    service_name    text,
    tag_key         text,
    tag_value       text,
    start_time      bigint,
    trace_id        blob,
    span_id         bigint,
    PRIMARY KEY ((service_name, tag_key, tag_value), start_time, trace_id, span_id)
)
    WITH CLUSTERING ORDER BY (start_time DESC)
    AND compaction = {
        'compaction_window_size': '1',
        'compaction_window_unit': 'HOURS',
        'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'
    }
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 21600
    AND speculative_retry = 'NONE'
    AND gc_grace_seconds = 10800; -- 3 hours of downtime acceptable on nodes

I view scylla‘s code, in twcs, gc old expired sstables depends on sstable's max_local_deletion_time, and max_local_deletion_time depends on cell's deletion_time. but if all dimmisions in primary key, will no cells in row. so sstable's max_local_deletion_time always equals to int32_max is that right? 
I using sstablemetadata to view sstable's meta, will get "SSTable max local deletion time: 2147483647"

I search the web, cassandra also exists this bug: http://user.cassandra.apache.narkive.com/MTHPUtGG/ttls-on-tables-with-only-primary-keys

now I add dummy dimension in schema to let it not trigered, I seem work fine.

the key thing, will scylladb fix this problem?

**Comment by xmm1989218** [comment]
I use scylla 2.2.0-0.20180705.240b9f122

**Comment by raphaelsc** [comment]
On Tue, Sep 11, 2018 at 9:59 PM, xumingmin <notifications@github.com> wrote:

> I use jaeger and use scylladb replacing cassandra, I get some problems.
>
> below is one schema which can't gc fine:
>
> CREATE TABLE IF NOT EXISTS ${keyspace}.tag_index (
> service_name text,
> tag_key text,
> tag_value text,
> start_time bigint,
> trace_id blob,
> span_id bigint,
> PRIMARY KEY ((service_name, tag_key, tag_value), start_time, trace_id,
> span_id)
> )
> WITH CLUSTERING ORDER BY (start_time DESC)
> AND compaction = {
> 'compaction_window_size': '1',
> 'compaction_window_unit': 'HOURS',
> 'class': 'org.apache.cassandra.db.compaction.TimeWindowCompactionStrategy'
> }
> AND dclocal_read_repair_chance = 0.0
> AND default_time_to_live = 21600
> AND speculative_retry = 'NONE'
> AND gc_grace_seconds = 10800; -- 3 hours of downtime acceptable on nodes
>
> I view scylla‘s code, in twcs, gc old expired sstables depends on
> sstable's max_local_deletion_time, and max_local_deletion_time depends on
> cell's deletion_time. but if all dimmisions in primary key, will no cells
> in row. so sstable's max_local_deletion_time always equals to int32_max is
> that right?
>
I using sstablemetadata to view sstable's meta, will get "SSTable max local
> deletion time: 2147483647"
>
I search the web, cassandra also exists this bug:
> http://user.cassandra.apache.narkive.com/MTHPUtGG/ttls-on-
> tables-with-only-primary-keys
>
> now I add dummy dimension in schema to let it not trigered, I seem work
> fine.
>
> the key thing, will scylladb fix this problem?
>

I don't fully get the problem you described above. The link above talks
about ttl function not working on a specific primary key component. It
seems your problem is actually about sstable expiration, right?

That value above for max local deletion time means sstable contains some
data that will not ever be expired. Did you set TTL for all data you
inserted into that table? Are you suggesting that sstable is incorrectly
set with INT32_MAX for max local deletion time for your case?

**Comment by xmm1989218** [comment]
@raphaelsc my english is poor, I try my best to decrible problem clearly

my problem is about old expired sstable GC

see the schema, default_time_to_live = 21600, the table should only keep last 6 hours, but actually sstable is expired, but no one GCd. I show the link ( http://user.cassandra.apache.narkive.com/MTHPUtGG/ttls-on- tables-with-only-primary-keys), because in the link, also describe "I need these to eventually get GCd however it doesnât seem to work." and as my table schema, his table schema also all dimensions in primary key. and I use his fix way(add dummy dimension), every thing seem work fine, the expired sstable can be GCd. so I think I met problem as same as he met

more detail, I think this problem should be related to max_local_deletion_time. before adding dummy dimension, the expired sstable's max_local_deletion_time = int32_max, after adding dummy dimension, the expired sstable's max_local_deletion_time = 1536753543 (unix timestamp)

I think if all dimensions in primary key and default_time_to_live = duration, the max_local_deletion_time shouldn't be int32_max, should it be sstable's Maximum timestamp + default_time_to_live?

**Comment by tgrabiec** [comment]
@raphaelsc We don't seem to be calling `column_stats::update_local_deletion_time()` for expiring row markers, that could explain it.

**Comment by slivne** [comment]
@raphaelsc - ping

**Comment by bhalevy** [comment]
This has actually been fixed in commit 0ca4ae658c1a964e3d3badaafb8c11ecc3ca0f2c as part of #4026

**Comment by bhalevy** [comment]
It's already in branch-3.1 so I think this issue can be closed.
