### ISSUE TITLE
Housekeeping is confused about version numbers for release candidates

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#3765]
Housekeeping is very confused about version numbers. I see the following when I run 2.3-rc3 on Docker:

```
Your current Scylla release is 2.3.rc3, while the latest patch release is 2.3, and the latest minor release is 2.2 (recommended)
```

I completely agree on the recommendation of 2.2, but why does it say latest _patch_ release is 2.3, when it's 2.3.rc3?

**Comment by penberg** [comment]
We have an user report on Scylla's user channel that suggests this was not fixed:

```
scylla-housekeeping: You current Scylla release is 2.3.0 the latest minor release is 2.2 go to http://www.scylladb.com for upgrade instructions
```

**Comment by amnonh** [comment]
It still needs to be updated manually, I just did

**Comment by penberg** [comment]
@amnonh So we can close this issue?

**Comment by amnonh** [comment]
I think we can close it

**Comment by tzach** [comment]
The problem is the housekeeping version bump is not automate as part of the release process.
Till we fix this, this problem will be back which each release
