### ISSUE TITLE
system_auth keyspace and RF

### ISSUE THREAD

**Issue by Roaming9** [scylladb/scylla#3766]
Hi ScyllaDB team.
There is one question I want to ask.

Below is the test content about system_auth/RF.
**1) Node 1 Start
2) create 1~20 user
3) Node 2 Start ( Join Node 1 Cluster )
4) alter keyspace system_auth RF=2**
In normal cases, ScyllaDB now need the "nodetool repair system_auth" operation.
But I was wondering if the client's request was done well before the "repair" job was finished.

So I tested the "cqlsh" connection after step "4)".
(I did not do "repair".)
Then some user's connection was not made.
(A user I do not specify is a connection is successful.)
**[First attempt]**
[root@jjeo02 users-473588ad9c7938be8b59e06c10456ba0]# cqlsh 10.40.95.153 9042 -u ming9 -p ming
Connection error: ('Unable to connect to any servers', {'10.40.95.153': AuthenticationFailed('Failed to authenticate to 10.40.95.153: Error from server: code=0100 [Bad credentials] message="User ming9 doesn\'t exist - create it with CREATE USER query first"',)})

[root@jjeo02 users-473588ad9c7938be8b59e06c10456ba0]# cqlsh 10.40.95.153 9042 -u ming10 -p ming
Connection error: ('Unable to connect to any servers', {'10.40.95.153': AuthenticationFailed('Failed to authenticate to 10.40.95.153: Error from server: code=0100 [Bad credentials] message="authentication failed"',)})

[root@jjeo02 users-473588ad9c7938be8b59e06c10456ba0]# cqlsh 10.40.95.153 9042 -u ming10 -p ming
Connection error: ('Unable to complete the operation against any hosts', {<Host: 10.40.95.153 datacenter1>: ConnectionException('Host has been marked down or removed',)})

[root@jjeo02 users-473588ad9c7938be8b59e06c10456ba0]# cqlsh 10.40.95.153 9042 -u ming11 -p ming
Connection error: ('Unable to complete the operation against any hosts', {<Host: 10.40.95.153 datacenter1>: ConnectionException('Host has been marked down or removed',)})

[root@jjeo02 users-473588ad9c7938be8b59e06c10456ba0]# cqlsh 10.40.95.153 9042 -u ming18 -p ming
Connection error: ('Unable to connect to any servers', {'10.40.95.153': AuthenticationFailed('Failed to authenticate to 10.40.95.153: Error from server: code=0100 [Bad credentials] message="authentication failed"',)})

**[After the second connection attempt]**
[root@jjeo02 data]# cqlsh 10.40.95.153 9042 -u ming20 -p ming
Connection error: ('Unable to connect to any servers', {'10.40.95.153': AuthenticationFailed('Failed to authenticate to 10.40.95.153: Error from server: code=0100 [Bad credentials] message="authentication failed"',)})

[root@jjeo02 data]# cqlsh 10.40.95.153 9042 -u ming19 -p ming
Connection error: ('Unable to complete the operation against any hosts', {<Host: 10.40.95.153 datacenter1>: ConnectionException('Host has been marked down or removed',)})

[root@jjeo02 data]# cqlsh 10.40.95.153 9042 -u ming2 -p ming
Connection error: ('Unable to connect to any servers', {'10.40.95.153': AuthenticationFailed('Failed to authenticate to 10.40.95.153: Error from server: code=0100 [Bad credentials] message="authentication failed"',)})

Whenever I try to connect, the connection of the specific user becomes normal / abnormal.
Of course, if you do repair, this phenomenon will disappear.
But I was wondering if the client's request was done well before the "repair" job was finished.
Is this a normal phenomenon?
If not, I wonder if there is a solution.

**Comment by glommer** [comment]
Hello,

Please note that this is the scylla bug tracker, in which we expect bug reports, not questions. We do enforce this policy, otherwise it makes it harder for folks who are searching later for bug reports.

I will close this, and kindly ask you to post this question to scylladb-users@googlegroups.com

**Comment by slivne** [comment]
copying from the email just to close this cleanly

> normal authentication requests are done with consistency LOCAL_ONE.
> So if you set your keyspace to RF=2, the new node now believes it has a replica and it will try to use that to authenticate.
> Because it doesn't, then the authentication fails.
> 
> Therefore, this is expected. The repair is absolutely necessary.
> 
> Note that repairs can (and should) be done per keyspace, and system_auth is usually minuscule.
> So the repair should be really fast.


Repair is part of the documented procedure in the documentation https://docs.scylladb.com/operating-scylla/security/authentication/#authentication
