### ISSUE TITLE
row_cache: Avoid reading sstables if bloom filter tells given key is missing

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#377]
When populating the database, some partitions will only reside in memtable, which didn't get big enough yet to get flushed to sstables. When those partitions are queried, cache will miss on them, resulting in unnecessary IO. We could use bloom filter to detect that the partition is missing in sstables and avoid IO.

**Comment by slivne** [comment]
@glommer  can you look at this - we may have a bug in the bloom filter

**Comment by glommer** [comment]
Sure.

**Comment by tzach** [comment]
@slivne @tgrabiec is this a only performance issue? if so we can push it post GA.

**Comment by nyh** [comment]
@slivne does this bug still exist?

Issue #1066 asked bloom-filter metrics, one of them is a counter of bloom filter false positives (case where the bloom filter said some token may exist in an sstable, but it didn't). If we had this counter (do we?) we could see this problem happening.

**Comment by raphaelsc** [comment]
ping. I think this is probably fixed
