### ISSUE TITLE
Allow user to disable caching from a specific client/session

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#3770]
*Installation details*
Scylla version (or git commit hash): 2.x

In some case, for example, bulk upload, or batch writes, a user knows he wants to bypass the cache.
Other plan enhancements like #2664, #755 define caching strategy in the table level.
This enrichment request is in the client level, as the same table can be used, with caching by some clients, while disabled for others.

**Comment by avikivity** [comment]
@tzach I proposed a `BYPASS CACHE` clause to select this on a per-statement level:

https://groups.google.com/d/topic/scylladb-dev/K_zIjE_0Kco/discussion

**Comment by amnonh** [comment]
In Oracle sql there is a NOCACHE optimization hint, maybe we can use that

**Comment by tzach** [comment]
@avikivity note that https://github.com/scylladb/scylla/issues/2664 altho less dynamic does not require CQL extension and covers a similar use case.

**Comment by lkosco** [comment]
+1 on insert cache bypass, we could definitely use it

**Comment by avikivity** [comment]
It's ready for 3.1.

**Comment by avikivity** [comment]
Fixed by 2a371c2689d327a10f5888f39414ec66efedb093
