### ISSUE TITLE
Improve tombstones compactions heuristics

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#3772]
HEAD: a84c26799d8d947ee2111e844185312f5940df65

*Description*
Right now sstables don't have the information how much data in the current sstable is covered by tombstones from the same sstable. Therefore if tombstones *do not* cover any data in the same sstable our tombstones compaction may kick in for this sstable and the outcome of it will be zero if not negative - we will waste CPU and I/O resources without any positive result.

Another issue is that after we issued tombstones compaction for a particular sstable we will  compact it again after `tombstone_compaction_interval` even if there isn't TTLed data.
This will result in a pointless compaction invocation until major compaction for sstables described in the first part. Namely we may continue wasting resources again and again "compacting" such sstables for a very long time.

*Proposed solution*
 * Have an sstable statistics (in its meta-data) of how much of live data is covered by tombstones.

This is going to provide a convenient tool to resolve both issues above.

**Comment by tgrabiec** [comment]
wt., 18 wrz 2018 o 23:54 vladzcloudius <notifications@github.com>
napisał(a):

> HEAD: a84c267
> <https://github.com/scylladb/scylla/commit/a84c26799d8d947ee2111e844185312f5940df65>
>
> *Description*
> Right now sstables don't have the information how much data in the current
> sstable is covered by tombstones from the same sstable. Therefore if
> tombstones *do not* cover any data in the same sstable our tombstones
> compaction may kick in for this sstable and the outcome of it will be zero
> if not negative - we will waste CPU and I/O resources without any positive
> result.
>

I think sstables should never contain tombstones which cover data within
it, because the stream used to write the sstable should be already
compacted, so live data covered by tombstones is dropped.

We currently don't do that when flushing a memtable, but that needs to be
fixed.

**Comment by vladzcloudius** [comment]
@tgrabiec I agree. I this case (when it's done) we will be able to eliminate "tombstones compactions" all together.

**Comment by glommer** [comment]
What Tomek refers to is just a bug (if it is present at all)

The heuristic we have in place deals with expired tombstones.

See the code in size_tiered_compaction_strategy.hh:

```
    // if there is no sstable to compact in standard way, try compacting single sstable whose droppable tombstone
    // ratio is greater than threshold.
    // prefer oldest sstables from biggest size tiers because they will be easier to satisfy conditions for
    // tombstone purge, i.e. less likely to shadow even older data.
``

So when there are good candidate SSTables to be compacted, we will compact an SSTable against itself if it has more droppable tombstones than a threshold.

The problem we saw, was that we thought there were droppable tombstones when we had all the reason to believe that there were no droppable tombstones.

In the case we have in mind, there were no deletions and TTL, and the tombstones came from collections

So Scylla thinks an SSTable is full of droppable tombstones when in fact it isn't.

**Comment by vladzcloudius** [comment]
So, all I wrote above was a result of my misunderstanding of how things work.
I'm closing this issue.

**Comment by tgrabiec** [comment]
śr., 19 wrz 2018 o 16:02 Glauber Costa <notifications@github.com>
napisał(a):

> What Tomek refers to is just a bug (if it is present at all)
>
> The heuristic we have in place deals with expired tombstones.
>
> See the code in size_tiered_compaction_strategy.hh:
>
>     // if there is no sstable to compact in standard way, try compacting single sstable whose droppable tombstone
>     // ratio is greater than threshold.
>     // prefer oldest sstables from biggest size tiers because they will be easier to satisfy conditions for
>     // tombstone purge, i.e. less likely to shadow even older data.
> ``
>
> So when there are good candidate SSTables to be compacted, we will compact an SSTable against itself if it has more droppable tombstones than a threshold.
>
> The problem we saw, was that we thought there were droppable tombstones when we had all the reason to believe that there were no droppable tombstones.
>
> In the case we have in mind, there were no deletions and TTL, and the tombstones came from collections
>
>
I don't understand. Why is the fact that the tombstones came from
collections relvant, they can still be droppable, like any other tombstone.

**Comment by glommer** [comment]
That is the part I don't understand either.

The fact is that it came from collections, and the other fact is that the heuristic got totally wrong. It kept compacting SSTables alone (1 SSTable per compaction) and the end result had the same size of the original  - thus indicating that the heuristic for dropptable tombstones misfired.

**Comment by vladzcloudius** [comment]
@tgrabiec Another important thing I didn't realize here was that apparently a single sstable compaction was never going to compact live data with tombstones from this sstable.
