### ISSUE TITLE
Remove resharded SSTables from the sstable set for 'mc' format

### ISSUE THREAD

**Issue by argenet** [scylladb/scylla#3777]
In SSTables 3.x ('mc') format, the `ancestors` field of compaction metadata is no longer written to the Statistics.db file.
This has been done to the Origin under CASSANDRA-7066.

This means that resharded sstables wouldn't be removed from the sstable set. 
We need to come up with an alternative approach for proper clean-up.

/cc @raphaelsc

**Comment by glommer** [comment]
This is certainly a 3.0 blocker.
