### ISSUE TITLE
Compilation with gcc/g++-8 with --enable-dpdk is broken

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#3790]
*Installation details*
Scylla version: 8276ada1c48c548190015ae3e370cf203e2f2f4b
Reported by @ultrabug 

*Description*
Compilation is broken due to https://github.com/scylladb/seastar/issues/501

**Comment by ultrabug** [comment]
Full build log if it can help:

[build.log.zip](https://github.com/scylladb/scylla/files/2425704/build.log.zip)

**Comment by Luo-Liang** [comment]
any updates on this?

**Comment by avikivity** [comment]
Fixed by 7195f75fb2995dcc2b61b8a3927544bdab00170e
