### ISSUE TITLE
Segmentation fault when running 2.3.0 with Docker

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#3792]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):  2.3.0
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI):  Scylla 2.3.0 AMI

We are running Scylla 2.3 using the official Docker image running on the Scylla AMI and have hit a segfault four times over the past week.  Three of those instances were running in Docker but we also noticed a similar stack trace on our 2.3.0 baremetal installation.  We haven't had much luck decoding the stack trace using addr2line with any version of scylla.debug.  I don't think this stack trace is decoded correctly but here's what we see:

/usr/src/debug/scylla-2.3.0/seastar/util/backtrace.hh:56
/usr/src/debug/scylla-2.3.0/seastar/core/reactor.cc:390
/usr/src/debug/scylla-2.3.0/seastar/core/reactor.cc:418
/usr/src/debug/scylla-2.3.0/seastar/core/reactor.cc:3934
??:0
/opt/scylladb/include/c++/7/bits/list.tcc:330
/usr/src/debug/scylla-2.3.0/db/hints/manager.cc:477
/usr/src/debug/scylla-2.3.0/db/hints/manager.cc:276 (discriminator 2)
/usr/src/debug/scylla-2.3.0/service/storage_proxy.cc:1805
/opt/scylladb/include/c++/7/bits/std_function.h:706
/usr/src/debug/scylla-2.3.0/seastar/core/reactor.cc:3278
/opt/scylladb/include/c++/7/bits/std_function.h:706
/usr/src/debug/scylla-2.3.0/seastar/core/reactor.cc:4227
/opt/scylladb/include/c++/7/bits/std_function.h:706

More usefully, I hope, we were able to get a dump this time running in Docker and I've uploaded it here: http://upload.scylladb.com/1f8ebc84-9892-40e7-9657-152aae526f06/dump.tgz

I also uploaded our prometheus data here:   http://upload.scylladb.com/1f8ebc84-9892-40e7-9657-152aae526f06/prometheus_data.tgz

I've also attached our database schema in case it is helpful as you debug: [schema.cql.txt](https://github.com/scylladb/scylla/files/2426998/schema.cql.txt)

We would be happy to try running Master if there have been fixes in this area.  We actually tried and didn't have any luck getting the nightly docker container to work.  

Thanks, and good luck.

**Comment by tgrabiec** [comment]
pt., 28 wrz 2018 o 08:20 Veramine <notifications@github.com> napisał(a):

> This is Scylla's bug tracker, to be used for reporting bugs only.
> If you have a question about Scylla, and not a bug, please ask it in
> our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.
>
>    - I have read the disclaimer above, and I am reporting a suspected
>    malfunction in Scylla.
>
> *Installation details*
> Scylla version (or git commit hash): 2.3.0
> Cluster size: 3
> OS (RHEL/CentOS/Ubuntu/AWS AMI): Scylla 2.3.0 AMI
>
> We are running Scylla 2.3 using the official Docker image and have hit a
> segfault four times over the past week. Three of those instances were
> running in Docker but we also noticed a similar stack trace on our 2.3.0
> baremetal installation. We haven't had much luck decoding the stack trace
> using addr2line with any version of scylla.debug.
>

Did you follow the instructions from "What if I have a stripped binary"
section of
https://github.com/scylladb/scylla/wiki/How-to-resolve-backtrace#what-if-i-have-a-stripped-binary
?

**Comment by veramine** [comment]
Nope, doesn't seem stripped:

```
/usr/lib/debug/usr/bin/scylla.debug: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 2.6.32, BuildID[sha1]=85ab2ed2a7bae5e533496c04eb07d0dbbed4756b, not stripped
```

**Comment by veramine** [comment]
We found a dmesg entry from around the same time that indicates the docker container ran out of memory and killed scylla.  It was reported in the scylla docker log as a segfault but it could have been the kernel deciding to sacrifice the process due to OOM.  We have since adjusted the docker configuration to reserve more memory for scylla and have not re-hit the same crash again yet.

**Comment by slivne** [comment]
@veramine closing this issue - we can reopen
