### ISSUE TITLE
Counters for I/O errors

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#3794]
Our users routinely look at grafana, but not always look at logs. That is specially true because logs are local and we'll only usually look at logs when we suspect a problem in a node.

Today it happened again that we spent some time looking at grafana to try to figure out what was wrong with an unresponsive node. After concluding that there was no problem, we checked the logs to see I/O errors.

If those errors were present in grafana, we would immediately see them. Scylla should add a counter about them and we could then capture in the monitoring.

**Comment by amnonh** [comment]
Can you add some trace examples?

**Comment by tzach** [comment]
Nothing against this idea, but I think the long term, and common solution is log collecting stack, like ELK, alongside the monitoring stack.

**Comment by glommer** [comment]
```
Sep 30 17:27:10 ip-XXX.ec2.internal scylla[95689]:  [shard 10] commitlog - Failed to persist commits to disk for CommitLog-1-180143995629683151.log: storage_io_error (Storage I/O error: 5: Input/output error)
```

I don't see why we wouldn't count I/O Errors

**Comment by avikivity** [comment]
Can be in the badness dashboard.

**Comment by glommer** [comment]
Yes, that is where it belongs.
But the first step is to expose the counter in Scylla.

**Comment by avikivity** [comment]
s/Scylla/Seastar/

**Comment by bhalevy** [comment]
Depends on scylladb/seastar#505

**Comment by bhalevy** [comment]
Counters added to seastar in 9953448

**Comment by slivne** [comment]
@amnonh - these counters are "badness" counters that should be added in some manner

**Comment by slivne** [comment]
Scylla 3.1 will include this counters

**Comment by slivne** [comment]
@amnonh please open an enhacement in scylla-grapha-monitoring and we can close this issue in scylla

**Comment by amnonh** [comment]
Fixed by https://github.com/scylladb/scylla-grafana-monitoring/issues/576
