### ISSUE TITLE
Non-zero shards may have stale values of gossiper application states of a restarted node for some time

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#3798]
*Installation details*
Scylla version: 2.1+
Cluster size: >1

Application states of each node are versioned per-node with a pair of generation number (more significant) and value version. Generation number uniquely identifies the life time of the scylla process. Generation number changes after restart. Value versions start from 0 on each restart. When a node gets updates for application states, it merges them with its view on given node. Value updates with older versions are ignored.

Gossiper processes updates only on shard 0, and replicates value updates to other shards. When it sees a value with a new generation, it correclty forgets all previous values. However, non-zero shards don't forget values from previous generations. As a result, replication will fail to override the values on non-zero shards when generation number changes until their value version exceeds the version prior to the restart.

Introduced in 2d5fb9d109a81e3539d6862a17ac623b6b612e86.

**Comment by tgrabiec** [comment]
One of the possible effects is that heat-weighted load-balancing will work with stale values of hit ratio for restarted replicas.

**Comment by tgrabiec** [comment]
Another incarnation of this issue will result in non-seeds to have their STATUS set to `shutdown` on non-zero shards after being restarted.

When restarting a non-seed node, it will do a shadow gossip round before setting its `STATUS` to NORMAL. In the shadow round it will learn from other nodes about itself, and set its `STATUS` to `shutdown` on all shards with a high value version. Later, when it sets its status to NORMAL, it will override it only on shard 0, because on other shards the version of STATUS is higher.

Note that other nodes will see their STATUS correctly as NORMAL, on all shards, becuase the change to `shutdown` is not replicated to non-zero shards, due to effects mentioned in the issue description.

The problem doesn't happen when restarting a seed, because it doesn't do a shadow gossip round.

**Comment by tzach** [comment]
@tgrabiec @slivne we need to backport to this fix to 2018.1
