### ISSUE TITLE
Nonpaged index queries should use simple base query instead of incremental one

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#3800]
*Installation details*
Scylla version (or git commit hash): master (bebe5b5df)

Right now base queries for indexed select statements are executed incrementally in order to work with secondary index paging. However, before paging was implemented, all base queries used a simpler query mechanism (without any incremental mechanisms and range splitting). This simpler mechanism can still be used for nonpaged queries, so it should be restored.

**Comment by duarten** [comment]
The mechanism that existed (asking one row at a time) was the worst possible thing we could do. It's also not  clear to me why the mechanism that increments concurrency exponentially is insufficient to deal with the corner case of non paged queries returning large result sets?

**Comment by psarna** [comment]
Rows - yeah, I was thinking about the whole partition optimization. Right now the code will result in logarithmic number of queries instead of a single one. But, again, my original decision was to drop the old code, I'm just raising this issue because I had doubts about the 'asking for partitions' case. On the other hand, large queries *should* be paged and small queries would result in a single base query anyway.

**Comment by duarten** [comment]
I don't think we need to make things more complex for very little gain.

**Comment by psarna** [comment]
I'm convinced already, closing.
