### ISSUE TITLE
desc schema command fails with: 'NoneType' object has no attribute 'export_for_schema' after issuing a malformed query

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#3801]
scenario:
1. run cassandra stress with malformed dc names by wrapping them with double quotes:
`$ cassandra-stress write cl=QUORUM duration=100m -schema 'replication(strategy=NetworkTopologyStrategy,"us-eastscylla_node_east=3","us-west-2scylla_node_west=3")' -port jmx=6868 -mode cql3 native -rate threads=200 -pop seq=1..100000000 -node `hostname``

2. connecting to cql prompt and issuing desc schema commad
```
[centos@ip-172-30-0-45 ~]$ cqlsh `hostname`
Connected to manager-1.2-multidc-db-cluster-4d2ef86f at ip-172-30-0-45.ec2.internal:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> DESC SCHEMA 

'NoneType' object has no attribute 'export_for_schema'

```
==> result: fails as in above error: "'NoneType' object has no attribute 'export_for_schema'"

3. Droping the 'bad' keyspace - 'keyspace1'.
4. running desc schema again and it shows up ok:

```
cqlsh> DESC SCHEMA 

CREATE KEYSPACE keyspace4 WITH replication = {'class': 'NetworkTopologyStrategy', 'us-eastscylla_node_east': '3', 'us-west-2scylla_node_west': '3'}  AND durable_writes = true;

CREATE TABLE keyspace4.employee1 (...
...

```

```
[centos@ip-172-30-0-45 ~]$ scylla --version
2.3.rc3-0.20180907.1bac88601
```

**Comment by psarna** [comment]
As @penberg pointed out, other strategies are also affected with the same issue - replication factor parsing should be moved to a separate function which validates its input.

**Comment by psarna** [comment]
Oh, we already have `validate_replication_factor`... I'll move the updated network topology check there, it will solve all the replication factor checks.

**Comment by avikivity** [comment]
Backported to 3.3.
