### ISSUE TITLE
Repair last much longer on one shard compare to other shards

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#3816]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20180916.9d27045c7
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

During longevity test, the repair jobs took much longer than expected (~20 hours to repair 1.3TB).
From a shard view, it seems like all shards completed the repair in 8 hours and only one shard left doing "streaming reads".
The read ratio is very low (2MB/s) and the shard utilization is 100%.
![screen shot 2018-10-04 at 23 09 31](https://user-images.githubusercontent.com/20959584/46500112-a8bde900-c82a-11e8-97ef-8cb607df504c.png)

After some digging we found out that this shard is doing much more interrupts than the other shards on the NVMe irqs.
Looking on the smp_affinity for these irqs shows that almost all of them are set on this shard and irqbalance is running.

After the disabling irqbalance and setting smp_affinity of all NVMe irqs to core1, the "streaming reads" rate went up to ±10MB/S and the repair task finished.

**Comment by roydahan** [comment]
@slivne / @vladzcloudius, I know we have an issue / patch to disable the irqbalance.
I wanted the issue to be recorded for future tracking.

**Comment by tgrabiec** [comment]
We saw this also in https://github.com/scylladb/scylla/issues/3628

**Comment by slivne** [comment]
@roydahan any luck checking if vlads patches fixed the issue on the ami ?

**Comment by roydahan** [comment]
not yet for repairs.

**Comment by slivne** [comment]
@roydahan ping ...

**Comment by roydahan** [comment]
On 3.0.rc1-0.20181118.6fd1cfcfc during longevity 7 days:

One Repair of 1.3TB took ~6 hours.

![screen shot 2018-11-27 at 20 12 21](https://user-images.githubusercontent.com/20959584/49102207-e23a3000-f280-11e8-87bf-3f2005b2ebbc.png)

However, an earlier repair took ~24 hours:
![screen shot 2018-11-27 at 20 18 54](https://user-images.githubusercontent.com/20959584/49102517-afdd0280-f281-11e8-94c4-6352aac3a4b0.png)

We still need to look into that repair and its metrics and understand if it's the same issue or not.
From looking at the metrics it doesn't look like the original behaviour where only 1-2 shards left with work to do.

**Comment by slivne** [comment]
@roydahan - we need to close this whats the status

**Comment by roydahan** [comment]
still not clear.
We are checking current runs, not sure if these bad disks or something with scylla.

**Comment by roydahan** [comment]
Still no answer, all "streaming" nemesis takes very long time in the recent runs and we check what is the issue.

**Comment by slivne** [comment]
@roydahan updated ping - do we have an update - we ran longevity without m/v and with the fixes for streaming.

**Comment by roydahan** [comment]
From recent longevity of 400GB dataset with 4 DB nodes, I suspect the issue still exist.
Although, it doesn't look like only one Shard is left behind to do streaming, the repair takes ~12 hours (2 out of 2 repairs on this test).

This is with build where the IRQs should be balanced (3.0.rc2-0.20181221.04e982f90).

![screen shot 2018-12-24 at 17 12 42](https://user-images.githubusercontent.com/20959584/50402561-36f99980-07a0-11e9-9db5-cf8a041c724f.png)

(I have live system with all details in case someone would like to explore it).

**Comment by asias** [comment]
@roydahan Can you share the Grafana Dashboard and the Scylla logs? On which node did you run repair? Repair checksum reads will be counted as streaming read in the metrics. So the period from 10:00 to 22:00 looks like the nodes were doing repair checksum and had no streaming on wire.

**Comment by asias** [comment]
@roydahan What is the time to repair considered normal with the same config "400GB dataset with 4 DB nodes" within the runs in the past?

**Comment by asias** [comment]
We do not have streaming during the time 10:00 to 20:00.

![image](https://user-images.githubusercontent.com/320076/50419809-c751e000-086d-11e9-8045-e0eea909b7b5.png)

Compaction steal most of the disk IO:
```
   Compaction IO bw = 1 GBps
   Repair checksum read IO bw = 10 MBps
   Query IO bw = 70 Mbps
```
Compaction has dynamic io queue shares. While Query and Repair read has const 1K and 200 shares. 

![image](https://user-images.githubusercontent.com/320076/50419893-49420900-086e-11e9-9b04-ebd93217ab9f.png)

**Comment by asias** [comment]
In the last 3 hours before the repair completes, there are multiple shards finishes the checksum reading at different times. More shards finish around 22:00. It is not the case that only some "bad" shards left behind. 

![image](https://user-images.githubusercontent.com/320076/50436536-6d125700-0921-11e9-907a-8a0d0054b937.png)

@avikivity Compaction got 80MB/s of disk bandwidth while repair checksum only got 1MB/s of disk bandwidth, a sample of shard 6. Looks like it is a combination of disk (for reading the data from disk) and CPU (for doing the checksum) starving which makes the checksum reading so slow. What do yo think?


![image](https://user-images.githubusercontent.com/320076/50436686-135e5c80-0922-11e9-93d3-d339fa58db8b.png)

Compaction and streaming CPU time:

![image](https://user-images.githubusercontent.com/320076/50436840-97184900-0922-11e9-9a73-5701a209aecd.png)

Repair reading CPU time:
![image](https://user-images.githubusercontent.com/320076/50436848-a39ca180-0922-11e9-9b70-31f680ad93a8.png)

**Comment by avikivity** [comment]
@asias can you isolate the bad shard? there's too much noise in the graphs.

We need a perf report on the bad shard to understand what it is doing.

Also, let's verify that we don't lose the io_priotity_class for repair.

**Comment by asias** [comment]
By "lose the io_priotity_class for repair", do you mean use do not use the streaming io priority to read the data from disk? We can't, because the checksum code uses the table::make_streaming_reader() which uses service::get_local_streaming_read_priority to get the priority. And, if it does not use the streaming io priority, we won't  see data in the io streaming io query metric at all.

I sent you the prometheus grafana link by email. 

There is no shard that is particularly bad. All the shards have very low bandwidth compared to compaction.

Do you think is this related to scheduling?

@roydahan Could you help with the perf report Avi asked for?

**Comment by roydahan** [comment]
Do you mean "perf record" on this shard?
If so, It won't be easy or something I can do quickly, it's part of a longevity that already ended.

**Comment by asias** [comment]
Yes, "perf record". I thought you still have this longevity cluster around.

**Comment by vladzcloudius** [comment]
On 12/24/18 10:21 AM, Roy Dahan wrote:
>
> From recent longevity of 400GB dataset with 4 DB nodes, I suspect the 
> issue still exist.
> Although, it doesn't look like only one Shard is left behind to do 
> streaming, the repair takes ~12 hours (2 out of 2 repairs on this test).
>
> This is with build where the IRQs should be balanced 
> (3.0.rc2-0.20181221.04e982f90).
>

Roy, I'm a little confused. The perftune.py patches that address the 
NVMe IRQ balancing issue on i3 hasn't been merged yet.
Could you, please, clarify how you ensure the proper balancing?

**Comment by roydahan** [comment]
AFAIK, some patches already merged, but it wasn’t optimal as suggested by Gleb.

**Comment by vladzcloudius** [comment]
@roydahan I don't see anything merged (it was a single patch).

**Comment by slivne** [comment]
patch "[seastar-dev] [PATCH v2] perftune.py: tune only active NVMe HW queues on i3 AWS instances" in master

**Comment by vladzcloudius** [comment]
@slivne Yes, since yesterday. ;)

**Comment by slivne** [comment]
the patch was merged to 3.0

**Comment by slivne** [comment]
@roydahan - can we check if this is fixed

**Comment by slivne** [comment]
closing this issue, if this happens again please create a new issue

repair has also been changed to row level repair
