### ISSUE TITLE
Repair floods the row cache

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#382]
column_family::make_reader(), when "_config.enable_cache" is on, reads the sstable through _cache.make_reader(range), which in turn calls row_cache::make_scanning_reader(), and puts every one of the partitions being read into the cache.

On one hand, this makes sense - we've already read those partitions from disk, so why not save them in memory as long as we can? On the other hand, we have a limited cache size, and unless our cache policy is based on use frequency (is it?), we are risking evicting all the frequently-queried partitions from the cache, when an operation like compaction or repair reads entire sstables - and floods the row cache with swathes of cold data from they read from disk. Moreover, even if we had a smart cache policy, if the sstables being compacted/repaired are significantly larger than our memory, the extra caching is certain not to help at all, and is a complete waste of time to do it.

So I'm not sure what we should best do here, but I'm opening this bug to remind us to reconsider it.

This issue is a spin-off from issue #376 (where the extra caching is causing an OOM).

**Comment by slivne** [comment]
@nyh is this still relevant ?

**Comment by nyh** [comment]
I believe it is still relevant, I don't see that this code has changed.
This might be another reason to read sstables directly in repair, and not use make_reader().

**Comment by slivne** [comment]
thanks 

@asias does streaming() for a new node flood the row cache as well ?

**Comment by asias** [comment]
streaming uses

    service::get_storage_proxy().local().make_local_reader()
    consume()

to read a mutation, and

   service::get_storage_proxy().local().mutate_locally(fm)

to apply the mutation on the destination node.

With recently patch (not merged yet):

   streaming: Invalidate cache upon receiving of stream

We invalidate the related ranges in row cache.

**Comment by slivne** [comment]
On Sun, Dec 27, 2015 at 2:18 PM, Asias He <notifications@github.com> wrote:

> streaming uses
>
> service::get_storage_proxy().local().make_local_reader()
> consume()
>
>  to read a mutation, and
>

So does this mean that we insert the data to the cache ?

**Comment by nyh** [comment]
On Sun, Dec 27, 2015 at 2:18 PM, Asias He <notifications@github.com> wrote:

> streaming uses
>
> service::get_storage_proxy().local().make_local_reader()
> consume()
>
> to read a mutation, and
>
> service::get_storage_proxy().local().mutate_locally(fm)
>
> to apply the mutation on the destination node.
>
> With recently patch (not merged yet):
>
> streaming: Invalidate cache upon receiving of stream
>
> We invalidate the related ranges in row cache.
>

If you use make_local_reader() when *sending* a range, then as I explained
in this issue, you are filling the cache with everything you read. Which
might not be a good idea.

The *receiving* side has a similar, but more complicated, problem: Let's
say you receive a million partitions, each time you fill a new memtable
with data you receive over the wire, and when you flush this memtable to
disk, you still keep the old memtable's data in the cache - thereby pushing
out all old data out of the cache.

It seems neither problem is solved by "invalidating the cache upon
receiving of stream", so I don't understand what this patch solves?

**Comment by tgrabiec** [comment]
We could extend data source interface (make_reader) to let the users signal that the data is unlikely to be read again any time soon and so should not be cached.

**Comment by dorlaor** [comment]
IMHO it's a performance optimization which isn't a must for 1.0
Potentially in time we may automatically handle it by a generic ARC
algorithm

**Comment by asias** [comment]
Patch has been sent by @glommer 
[PATCH 00/10] Isolate streams into their own writes

**Comment by asias** [comment]
@slivne we can close this now since we have @glommer 's patches merged.

**Comment by glommer** [comment]
No. We still have a lot to do not to polute the row cache. The writers will
not touch it but the readers will.

**Comment by asias** [comment]
@glommer You are right. Thanks.

**Comment by slivne** [comment]
@glommer is this fixed in your repair series - e.g. on the reading side do we polut the cache by data we read ?

**Comment by glommer** [comment]
The cache behavior is not changed in my work.

**Comment by slivne** [comment]
We are changing the repair code to read from a set of sstables from the disk and not use the cache/memtables for streaming
