### ISSUE TITLE
estimated histgoram are accumulate twice

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#3827]
Commit fc4416abcc60b4a531f1d0c42d834066fdabcb9e change the get_histogram method to return an accumulative histogram instead of a regular histogram.

prometheus assumes that the return histogram is regular one and accumulate the result also,
The end result is that the histograms are now broken.

**Comment by glommer** [comment]
I don't understand how this is the case. Before that patch, the histograms were verified to be bogus. Can you show me an example of the histograms being bad now ?

Also this link : https://prometheus.io/docs/concepts/metric_types/#histogram explicitly says that the buckets are expected to be cumulative: (see first bullet)

```
A histogram with a base metric name of <basename> exposes multiple time series during a scrape:

* cumulative counters for the observation buckets, exposed as <basename>_bucket{le="<upper inclusive bound>"}
* the total sum of all observed values, exposed as <basename>_sum
* the count of events that have been observed, exposed as <basename>_count (identical to <basename>_bucket{le="+Inf"} above)
```

**Comment by amnonh** [comment]
Prometheus expect it to be accumulative, but that is taking care of on the Prometheus level.

Point your browser to:
http://{ip}:9180/metrics

(for example http://localhost:9180/metrics)

and look for scylla_storage_proxy_coordinator_write_latency_bucket for example

see that the total number is less than the value of the last bucket.


The code that does the accumulation is found at:
prometheus.cc:write_text_representation
while I was debugging this issue i found another one with the labels of the sum and count.
