### ISSUE TITLE
Very high p99th read latency during "Read only" workload

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#3831]
*Installation details*
Scylla version (or git commit hash): 
Version: 666.development
build date: 20181003
commit id: de48966ab

Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI (ami-07a19a5ddd3867bae)
instance_type_db: i3.4xlarge
instance_type_loader: c4.2xlarge

test_name: test_latency_read

c-s command used in the test:
population phase (using 4 loaders, each command on different loader):
```
["cassandra-stress write no-warmup cl=QUORUM n=250000000 -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=200 -col 'size=FIXED(1024) n=FIXED(1)' -pop seq=1..250000000",
"cassandra-stress write no-warmup cl=QUORUM n=250000000 -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=200 -col 'size=FIXED(1024) n=FIXED(1)' -pop seq=250000000..500000000",
"cassandra-stress write no-warmup cl=QUORUM n=250000000 -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=200 -col 'size=FIXED(1024) n=FIXED(1)' -pop seq=500000000..750000000",
"cassandra-stress write no-warmup cl=QUORUM n=250000000 -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=200 -col 'size=FIXED(1024) n=FIXED(1)' -pop seq=750000000..1000000000"]
```
**read phase:**
```
cassandra-stress read no-warmup  cl=QUORUM duration=50m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate 'threads=100 throttle=10000/s' -col 'size=FIXED(1024) n=FIXED(1)' -pop 'dist=gauss(1..1000000000,500000000,50000000)'
```

The p99th latency should be around 3-5 ms compared to previous release.
On the latest master releases it starts around 12ms and peakes to 150-200ms for long periods.

![screen shot 2018-10-08 at 19 14 53](https://user-images.githubusercontent.com/20959584/46620829-7f54d400-cb2e-11e8-80a4-43be13d3b78a.png)
![screen shot 2018-10-08 at 19 14 41](https://user-images.githubusercontent.com/20959584/46620830-7f54d400-cb2e-11e8-8e5c-237978a3d589.png)

One of the obvious observations from the metrics is that we have replicas writes during the "read only" workload.
The prime suspects is the read_reapir.

![screen shot 2018-10-08 at 19 15 26](https://user-images.githubusercontent.com/20959584/46620847-8ed41d00-cb2e-11e8-84d8-bb94fd311d36.png)
![screen shot 2018-10-08 at 19 16 04](https://user-images.githubusercontent.com/20959584/46620865-a0b5c000-cb2e-11e8-8a34-d61c08f56d20.png)
![screen shot 2018-10-08 at 19 16 18](https://user-images.githubusercontent.com/20959584/46620873-a8756480-cb2e-11e8-9d28-204e459daa5c.png)

**Comment by roydahan** [comment]
![screen shot 2018-10-08 at 19 17 58](https://user-images.githubusercontent.com/20959584/46620984-ea060f80-cb2e-11e8-987b-99d7e91e1e01.png)

**Comment by roydahan** [comment]
AFAIK, there aren't enough metrics to tell what went wrong during the population phase, this one was suggested by @gleb-cloudius:

![screen shot 2018-10-08 at 19 19 22](https://user-images.githubusercontent.com/20959584/46621048-17eb5400-cb2f-11e8-8262-2f573ba37034.png)

**Comment by slivne** [comment]
@gleb-cloudius / @roydahan please update the issue we know we have timeouts in writes ...

**Comment by roydahan** [comment]
@gleb-cloudius, I think that the theory of read-repair doesn't hold.
Comparing to 2.3 where we also have many "write failed", the read latency in 2.3 ranges between 3-4ms during the entire test (and there are also replica writes during the test).

c-s p99th latency:
![screen shot 2018-10-09 at 19 21 00](https://user-images.githubusercontent.com/20959584/46683281-7f210b00-cbf8-11e8-8141-b9c1384c6f82.png)

Writes during read workload:
![screen shot 2018-10-09 at 19 25 18](https://user-images.githubusercontent.com/20959584/46683523-16865e00-cbf9-11e8-9c66-cc123d20c713.png)

"Failed writes" during population phase (2.3):
![screen shot 2018-10-09 at 19 27 50](https://user-images.githubusercontent.com/20959584/46683675-73821400-cbf9-11e8-972a-c959f3ac2935.png)
![screen shot 2018-10-09 at 19 27 07](https://user-images.githubusercontent.com/20959584/46683676-741aaa80-cbf9-11e8-8be6-af2e3ee9ed9a.png)

"Failed writes" during population phase (master):
![screen shot 2018-10-09 at 19 28 57](https://user-images.githubusercontent.com/20959584/46683737-9ca2a480-cbf9-11e8-8d85-a765859540c4.png)
![screen shot 2018-10-09 at 19 28 38](https://user-images.githubusercontent.com/20959584/46683738-9d3b3b00-cbf9-11e8-9b09-2b1113c6260d.png)

**Comment by roydahan** [comment]
Another test is running now on master, this time the population is done using CL=ALL.

**Comment by gleb-cloudius** [comment]
Run both tests on 2.3 and on 3.0 without data loss. We do not want to
compare noise.

--
			Gleb.

**Comment by avikivity** [comment]
We saw high nvme interrupt rate on some shards, coinciding with the high latency periods. nvme interrupts were managed by irqbalance. On bare metal (including i3.metal) nvme interrupts were tied to the CPUs that manage their queues, and were ignored by by irqbalance.

It's not clear why 2.3 did not exhibit this behavior (or maybe it did and the effects were smaller).

I also filed https://github.com/scylladb/seastar/issues/507 as a further optimization (but not part of this).

**Comment by avikivity** [comment]
@roydahan can you attach prometheus charts in support of the above?

**Comment by roydahan** [comment]
![screen shot 2018-10-14 at 20 29 32](https://user-images.githubusercontent.com/20959584/46919979-0eab2d00-cff0-11e8-9729-8c2bbd1f9aa9.png)

![screen shot 2018-10-14 at 20 31 53](https://user-images.githubusercontent.com/20959584/46
![screen shot 2018-10-14 at 20 33 17](https://user-images.githubusercontent.com/20959584/46920001-5b8f0380-cff0-11e8-992c-7d33d7566b8f.png)
919985-2b476500-cff0-11e8-9aad-05601aea46ea.png)
![screen shot 2018-10-14 at 20 32 41](https://user-images.githubusercontent.com/20959584/46919996-44e8ac80-cff0-11e8-8d5e-181718f01729.png)

**Comment by glommer** [comment]
On Thu, Oct 18, 2018 at 8:23 AM Roy Dahan <notifications@github.com> wrote:

> I reran the test with a script from @vladzcloudius
> <https://github.com/vladzcloudius> for IRQ tuning (optimized for i3.4x
> while test is running on i3.2x).
>
> L0194 DEBUG| [54.197.7.53] [stdout] File /etc/sysconfig/irqbalance.scylla.orig already exists - not overwriting.
> L0194 DEBUG| [54.197.7.53] [stdout] Restarting irqbalance: going to ban the following IRQ numbers: 111, 112, 110, 98, 99, 103, 109, 97, 101, 106, 107, 102, 108, 104, 105, 100 ...
> L0194 DEBUG| [54.197.7.53] [stdout] Restarting irqbalance via systemctl...
> L0194 DEBUG| [54.197.7.53] [stdout] No non-NVMe disks to tune
> L0194 DEBUG| [54.197.7.53] [stdout] Setting NVMe disks: nvme0n1...
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000001 in /proc/irq/111/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000001 in /proc/irq/112/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000010 in /proc/irq/110/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000010 in /proc/irq/98/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000002 in /proc/irq/99/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000002 in /proc/irq/103/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000020 in /proc/irq/109/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000020 in /proc/irq/97/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000004 in /proc/irq/101/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000004 in /proc/irq/106/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000040 in /proc/irq/107/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000040 in /proc/irq/102/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000008 in /proc/irq/108/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000008 in /proc/irq/104/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000080 in /proc/irq/105/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Setting mask 00000080 in /proc/irq/100/smp_affinity
> L0194 DEBUG| [54.197.7.53] [stdout] Writing 'noop' to /sys/devices/pci0000:00/0000:00:1e.0/nvme/nvme0/nvme0n1/queue/scheduler
> L0194 DEBUG| [54.197.7.53] [stdout] Failed to write into /sys/devices/pci0000:00/0000:00:1e.0/nvme/nvme0/nvme0n1/queue/scheduler: (<class 'OSError'>, OSError(22, 'Invalid argument'), <traceback obj
>
> latencies dropped significantly compared to master and there aren't huge
> spikes anymore.
> However, compactions still runs longer than 2.3 and sleeping for 10 mins
> between the loads isn't enough as it was in 2.3.
> in matter of fact, the compactions continue during the entire read test
> (50mins).
>

Botond saw a similar thing, I think.

We need to understand that one. There are no changes in 3.0 that would
justify this.
All relevant compaction changes are in 2.3 already

The logs would help so we can trace a history of what compactions are doing
and why are they called.

**Comment by slivne** [comment]
@roydahan AFAIK you have run multiple tests - with the workaround for interrupts.

What is our status

**Comment by roydahan** [comment]
using the workaround for setting smp_affinity the issue has gone.
3.0 behaves even slightly better than 2.3.
I'll attach here some results after my last run.

Workaround for now is:
`sudo /usr/lib/scylla/perftune.py --tune disks --dir /var/lib/scylla`
