### ISSUE TITLE
do not runs scylla on cpu that process networking interrupt

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#384]
Exclude it using --cpuset 1-$NUM_CPUS (assuming networking irq bound to cpu zero here)

**Comment by slivne** [comment]
@gleb-cloudius / @asias please close this - latest ami resolved this

**Comment by asias** [comment]
Only gleb can close.

On Thu, Sep 24, 2015 at 9:50 PM, slivne <notifications@github.com> wrote:

> @gleb-cloudius <https://github.com/gleb-cloudius> / @asias
> <https://github.com/asias> please close this - latest ami resolved this
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/384#issuecomment-142933499>.
>



-- 
Asias
