### ISSUE TITLE
reactor stalls when closing SSTables

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#3846]
I haven't seen this one before - not sure if it is new in 3.0 or already there.
I am running this in a box with 86 CPUs

```
Oct 12 19:00:51 dell-1 scylla[435045]: Backtrace:[Backtrace #0]
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /home/sylla/scylla/seastar/util/backtrace.hh:56
seastar::backtrace_buffer::append_backtrace() at /home/sylla/scylla/seastar/core/reactor.cc:410
 (inlined by) print_with_backtrace at /home/sylla/scylla/seastar/core/reactor.cc:431
seastar::reactor::block_notifier(int) at /home/sylla/scylla/seastar/core/reactor.cc:749
_L_unlock_13 at funlockfile.c:?
std::experimental::fundamentals_v1::_Optional_base<range_bound<dht::ring_position>, true>::_Optional_base(std::experimental::fundamentals_v1::_Optional_base<range_bound<dht::ring_position>, true>&&) at /opt/scylladb/include/c++/7/experimental/optional:247
 (inlined by) std::experimental::fundamentals_v1::optional<range_bound<dht::ring_position> >::optional(std::experimental::fundamentals_v1::optional<range_bound<dht::ring_position> >&&) at /opt/scylladb/include/c++/7/experimental/optional:493
 (inlined by) wrapping_range<dht::ring_position>::wrapping_range(wrapping_range<dht::ring_position>&&) at /home/sylla/scylla/./range.hh:61
 (inlined by) nonwrapping_range<dht::ring_position>::nonwrapping_range(nonwrapping_range<dht::ring_position>&&) at /home/sylla/scylla/./range.hh:430
 (inlined by) void __gnu_cxx::new_allocator<nonwrapping_range<dht::ring_position> >::construct<nonwrapping_range<dht::ring_position>, nonwrapping_range<dht::ring_position> >(nonwrapping_range<dht::ring_position>*, nonwrapping_range<dht::ring_position>&&) at /opt/scylladb/include/c++/7/ext/new_allocator.h:136
 (inlined by) void std::allocator_traits<std::allocator<nonwrapping_range<dht::ring_position> > >::construct<nonwrapping_range<dht::ring_position>, nonwrapping_range<dht::ring_position> >(std::allocator<nonwrapping_range<dht::ring_position> >&, nonwrapping_range<dht::ring_position>*, nonwrapping_range<dht::ring_position>&&) at /opt/scylladb/include/c++/7/bits/alloc_traits.h:475
 (inlined by) nonwrapping_range<dht::ring_position>& std::deque<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >::emplace_back<nonwrapping_range<dht::ring_position> >(nonwrapping_range<dht::ring_position>&&) at /opt/scylladb/include/c++/7/bits/deque.tcc:167
 (inlined by) std::deque<nonwrapping_range<dht::ring_position>, std::allocator<nonwrapping_range<dht::ring_position> > >::push_back(nonwrapping_range<dht::ring_position>&&) at /opt/scylladb/include/c++/7/bits/stl_deque.h:1558
 (inlined by) dht::split_range_to_single_shard(dht::i_partitioner const&, schema const&, nonwrapping_range<dht::ring_position> const&, unsigned int) at /home/sylla/scylla/dht/i_partitioner.cc:454
dht::split_range_to_single_shard(schema const&, nonwrapping_range<dht::ring_position> const&, unsigned int) at /home/sylla/scylla/dht/i_partitioner.cc:464
create_sharding_metadata at /home/sylla/scylla/sstables/sstables.cc:2075
 (inlined by) sstables::sstable::write_scylla_metadata(seastar::io_priority_class const&, unsigned int, sstables::sstable_enabled_features) at /home/sylla/scylla/sstables/sstables.cc:2435
sstables::sstable_writer_m::consume_end_of_stream() at /home/sylla/scylla/sstables/sstables.cc:3483
sstables::compaction::finish_new_sstable(std::experimental::fundamentals_v1::optional<sstables::sstable_writer>&, seastar::lw_shared_ptr<sstables::sstable>&) at /home/sylla/scylla/sstables/compaction.cc:338
 (inlined by) sstables::regular_compaction::stop_sstable_writer() at /home/sylla/scylla/sstables/compaction.cc:579
 (inlined by) sstables::regular_compaction::finish_sstable_writer() at /home/sylla/scylla/sstables/compaction.cc:585
sstables::compacting_sstable_writer::consume_end_of_stream() at /home/sylla/scylla/sstables/compaction.cc:494
 (inlined by) auto compact_mutation_state<(emit_only_live_rows)0, (compact_for_sstables)1>::consume_end_of_stream<sstables::compacting_sstable_writer>(sstables::compacting_sstable_writer&) at /home/sylla/scylla/./mutation_compactor.hh:292
 (inlined by) compact_mutation<(emit_only_live_rows)0, (compact_for_sstables)1, sstables::compacting_sstable_writer>::consume_end_of_stream() at /home/sylla/scylla/./mutation_compactor.hh:397
 (inlined by) stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer> >::consume_end_of_stream() at /home/sylla/scylla/./mutation_reader.hh:366
 (inlined by) auto flat_mutation_reader::impl::consume_in_thread<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer> >, std::function<bool (dht::decorated_key const&)> >(stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer> >, std::function<bool (dht::decorated_key const&)>, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /home/sylla/scylla/./flat_mutation_reader.hh:288
 (inlined by) auto flat_mutation_reader::consume_in_thread<stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer> >, std::function<bool (dht::decorated_key const&)> >(stable_flattened_mutations_consumer<compact_for_compaction<sstables::compacting_sstable_writer> >, std::function<bool (dht::decorated_key const&)>, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000l> > >) at /home/sylla/scylla/./flat_mutation_reader.hh:370
 (inlined by) operator() at /home/sylla/scylla/sstables/compaction.cc:757
 (inlined by) apply at /home/sylla/scylla/seastar/core/apply.hh:35
 (inlined by) apply<sstables::compaction::run(std::unique_ptr<sstables::compaction>)::<lambda()> > at /home/sylla/scylla/seastar/core/apply.hh:43
 (inlined by) apply<sstables::compaction::run(std::unique_ptr<sstables::compaction>)::<lambda()> > at /home/sylla/scylla/seastar/core/future.hh:1309
 (inlined by) operator() at /home/sylla/scylla/./seastar/core/thread.hh:315
 (inlined by) _M_invoke at /opt/scylladb/include/c++/7/bits/std_function.h:316
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::thread_context::main() at /home/sylla/scylla/seastar/core/thread.cc:313
```

Without knowing too much about this, I have tried blindly adding a yield into create_sharding_metadata at /home/sylla/scylla/sstables/sstables.cc:2075 - stalls are still present, indicating that the source of the stalls is the internal loop inside `split_range_to_single_shard`

This is probably related to #3335 - one stall when creating, one stall when reading.

`split_range_to_single_shard` seems to be called only by the sstable code. So naively we could insert a preemption point there.

**Comment by slivne** [comment]
@glommer this is generic ... (e.g. not mc specific - right ?)

**Comment by avikivity** [comment]
> split_range_to_single_shard seems to be called only by the sstable code. So naively we could insert a preemption point there.

Also called by checksum_range().

**Comment by avikivity** [comment]
Sorry, that's split_range_to_shards. However, functions in dht don't know whether they're called in a thread or not. Perhaps we should use a generator object.

**Comment by glommer** [comment]
@slivne this is generic and I am not saying this is a 3.0 issue - just opening the bug since I saw it.
More than happy to defer it to 3.1. But please note that this and #3335 are probably the only stalls left (that I know of) in our happy path.

**Comment by slivne** [comment]
just been bumped to 3.1

**Comment by juliayakovlev** [comment]
Received same during test with materialized views and secondary indexes. 
Test ran with SStable 3.0 format enabled.
Scylla version is 3.0.rc1-0.20181125.6e7e7f382

Stalls happen when new node was added to the cluster. I saw it few times after, for example:
```Scylla version 3.0.rc1-0.20181125.6e7e7f382 starting ...```
```[shard 0] storage_service - JOINING: Starting to bootstrap...```
 
```
0x00000000006a83f2
0x00000000005bfb1c
0x00000000005bffd6
/lib64/libpthread.so.0+0x000000000000f6cf
0x0000000002f3d104
0x0000000002f405db
0x0000000002f17066
0x0000000003620442
0x00000000036242a7
0x000000000362a1b4
0x000000000362cbfa
0x000000000052f8f5


void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/src/debug/scylla-3.0.rc1/seastar/util/backtrace.hh:56
seastar::backtrace_buffer::append_backtrace() at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:410
 (inlined by) print_with_backtrace at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:431
seastar::reactor::block_notifier(int) at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:749
?? ??:0
wrapping_range<dht::token>::wrapping_range(wrapping_range<dht::token> const&) at /usr/src/debug/scylla-3.0.rc1/./range.hh:61
 (inlined by) nonwrapping_range<dht::token>::operator wrapping_range<dht::token>() const & at /usr/src/debug/scylla-3.0.rc1/./range.hh:458
 (inlined by) dht::range_streamer::get_all_ranges_with_strict_sources_for(seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::vector<nonwrapping_range<dht::token>, std::allocator<nonwrapping_range<dht::token> > >) at /usr/src/debug/scylla-3.0.rc1/dht/range_streamer.cc:160
dht::range_streamer::add_ranges(seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::vector<nonwrapping_range<dht::token>, std::allocator<nonwrapping_range<dht::token> > >) at /usr/src/debug/scylla-3.0.rc1/dht/range_streamer.cc:236
dht::boot_strapper::bootstrap() at /usr/src/debug/scylla-3.0.rc1/dht/boot_strapper.cc:59
service::storage_service::bootstrap(std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >) at /usr/src/debug/scylla-3.0.rc1/service/storage_service.cc:697
service::storage_service::join_token_ring(int) at /usr/src/debug/scylla-3.0.rc1/service/storage_service.cc:559
service::storage_service::init_server(int, seastar::bool_class<service::bind_messaging_port_tag>)::{lambda()#1}::operator()() const at /usr/src/debug/scylla-3.0.rc1/service/storage_service.cc:1469
apply at /usr/src/debug/scylla-3.0.rc1/seastar/core/apply.hh:35
 (inlined by) apply<service::storage_service::init_server(int, service::bind_messaging_port)::<lambda()> > at /usr/src/debug/scylla-3.0.rc1/seastar/core/apply.hh:43
 (inlined by) apply_tuple<service::storage_service::init_server(int, service::bind_messaging_port)::<lambda()> > at /usr/src/debug/scylla-3.0.rc1/seastar/core/future.hh:1343
 (inlined by) apply<service::storage_service::init_server(int, service::bind_messaging_port)::<lambda()> > at /usr/src/debug/scylla-3.0.rc1/seastar/core/future.hh:1377
 (inlined by) operator() at /usr/src/debug/scylla-3.0.rc1/seastar/core/thread.hh:315
 (inlined by) _M_invoke at /opt/scylladb/include/c++/7/bits/std_function.h:316
std::function<void ()>::operator()() const at /opt/scylladb/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::thread_context::main() at /usr/src/debug/scylla-3.0.rc1/seastar/core/thread.cc:313
```

**Comment by avikivity** [comment]
How long was the stall?

In any case it happens during initialization, so it's not a big problem.

**Comment by juliayakovlev** [comment]
In case "storage_service - JOINING: Starting to bootstrap" it was 600 ms

**Comment by avikivity** [comment]
Wow, that's huge. But it doesn't hurt anyone since it's a non-serving node that is initializing.

Still nice to clear it to avoid having to analyze it each time.

Note it's a new bug, not related to sstables.

**Comment by glommer** [comment]
@avikivity while this one happens during initialization, there are plenty of stalls that happen when we inspect & manage tokens that are happening during normal operations.

**Comment by avikivity** [comment]
Such generic statements don't help. If there's such a problem, open an issue and post a backtrace.

**Comment by glommer** [comment]
https://github.com/scylladb/scylla/issues/3335 is opened since March.

**Comment by avikivity** [comment]
Issue number <-> opening date associations are also not helpful. If an 
issue is important to you, try to escalate its priority.

**Comment by asias** [comment]
> Received same during test with materialized views and secondary indexes.
> Test ran with SStable 3.0 format enabled.
> Scylla version is 3.0.rc1-0.20181125.6e7e7f382
> 
> Stalls happen when new node was added to the cluster. I saw it few times after, for example:
> `Scylla version 3.0.rc1-0.20181125.6e7e7f382 starting ...`
> or
> `[shard 0] storage_service - JOINING: Starting to bootstrap...`
> 
> ```
> 0x00000000006a83f2
> 0x00000000005bfb1c
> 0x00000000005bffd6
> /lib64/libpthread.so.0+0x000000000000f6cf
> 0x0000000002f3d104
> 0x0000000002f405db
> 0x0000000002f17066
> 0x0000000003620442
> 0x00000000036242a7
> 0x000000000362a1b4
> 0x000000000362cbfa
> 0x000000000052f8f5
> 
> 
> void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/src/debug/scylla-3.0.rc1/seastar/util/backtrace.hh:56
> seastar::backtrace_buffer::append_backtrace() at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:410
>  (inlined by) print_with_backtrace at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:431
> seastar::reactor::block_notifier(int) at /usr/src/debug/scylla-3.0.rc1/seastar/core/reactor.cc:749
> ?? ??:0
> wrapping_range<dht::token>::wrapping_range(wrapping_range<dht::token> const&) at /usr/src/debug/scylla-3.0.rc1/./range.hh:61
>  (inlined by) nonwrapping_range<dht::token>::operator wrapping_range<dht::token>() const & at /usr/src/debug/scylla-3.0.rc1/./range.hh:458
>  (inlined by) dht::range_streamer::get_all_ranges_with_strict_sources_for(seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::vector<nonwrapping_range<dht::token>, std::allocator<nonwrapping_range<dht::token> > >) at /usr/src/debug/scylla-3.0.rc1/dht/range_streamer.cc:160
> dht::range_streamer::add_ranges(seastar::basic_sstring<char, unsigned int, 15u, true> const&, std::vector<nonwrapping_range<dht::token>, std::allocator<nonwrapping_range<dht::token> > >) at /usr/src/debug/scylla-3.0.rc1/dht/range_streamer.cc:236
> dht::boot_strapper::bootstrap() at /usr/src/debug/scylla-3.0.rc1/dht/boot_strapper.cc:59
> service::storage_service::bootstrap(std::unordered_set<dht::token, std::hash<dht::token>, std::equal_to<dht::token>, std::allocator<dht::token> >) at /usr/src/debug/scylla-3.0.rc1/service/storage_service.cc:697
> service::storage_service::join_token_ring(int) at /usr/src/debug/scylla-3.0.rc1/service/storage_service.cc:559
> service::storage_service::init_server(int, seastar::bool_class<service::bind_messaging_port_tag>)::{lambda()#1}::operator()() const at /usr/src/debug/scylla-3.0.rc1/service/storage_service.cc:1469
> apply at /usr/src/debug/scylla-3.0.rc1/seastar/core/apply.hh:35
>  (inlined by) apply<service::storage_service::init_server(int, service::bind_messaging_port)::<lambda()> > at /usr/src/debug/scylla-3.0.rc1/seastar/core/apply.hh:43
>  (inlined by) apply_tuple<service::storage_service::init_server(int, service::bind_messaging_port)::<lambda()> > at /usr/src/debug/scylla-3.0.rc1/seastar/core/future.hh:1343
>  (inlined by) apply<service::storage_service::init_server(int, service::bind_messaging_port)::<lambda()> > at /usr/src/debug/scylla-3.0.rc1/seastar/core/future.hh:1377
>  (inlined by) operator() at /usr/src/debug/scylla-3.0.rc1/seastar/core/thread.hh:315
>  (inlined by) _M_invoke at /opt/scylladb/include/c++/7/bits/std_function.h:316
> std::function<void ()>::operator()() const at /opt/scylladb/include/c++/7/bits/std_function.h:706
>  (inlined by) seastar::thread_context::main() at /usr/src/debug/scylla-3.0.rc1/seastar/core/thread.cc:313
> ```

The fix for stall of get_all_ranges_with_strict_sources_for was already fixed in master.
```
commit 8edf3defdf4bc0ece99ae11e60b6691e4cf12168
Author: Asias He <asias@scylladb.com>
Date:   Wed Sep 5 16:21:12 2018 +0800

    range_streamer: Futurize add_ranges
    
    It might take long time for get_all_ranges_with_sources_for and
    get_all_ranges_with_strict_sources_for to calculate which cause reactor
    stall. To fix, run them in a thread and yield. Those functions are used in
    the slow path, it is ok to yield more than needed.
    
    Fixes #3639
    
    Message-Id: <63aa7794906ac020c9d9b2984e1351a8298a249b.1536135617.git.asias@scylladb.com>

```
The fix is not backported to 3.0 or enterprise yet.

**Comment by asias** [comment]
The call chain is:

sstable_writer_k_l::consume_end_of_stream and mc::writer::consume_end_of_stream -> sstable::write_scylla_metadata -> create_sharding_metadata -> dht::split_range_to_single_shard

We have:


$ gg consume_end_of_stream
compaction.cc:149:    void consume_end_of_stream();
compaction.cc:354:        writer->consume_end_of_stream();
compaction.cc:513:void compacting_sstable_writer::consume_end_of_stream() {
mc/writer.cc:745:    void consume_end_of_stream() override;
mc/writer.cc:1342:void writer::consume_end_of_stream() {
sstables.cc:1919:    void consume_end_of_stream();
sstables.cc:2135:void components_writer::consume_end_of_stream() {
sstables.cc:2233:    void consume_end_of_stream() override;
sstables.cc:2300:void sstable_writer_k_l::consume_end_of_stream()
sstables.cc:2304:    _components_writer->consume_end_of_stream();
sstables.cc:2367:void sstable_writer::consume_end_of_stream() {
sstables.cc:2369:    return _impl->consume_end_of_stream();
sstables.hh:883:    void consume_end_of_stream();
writer_impl.hh:49:    virtual void consume_end_of_stream() = 0;

@avikivity @raphaelsc Does consume_end_of_stream always get called in a thread? Otherwise we need to futurize  consume_end_of_stream everywhere?

**Comment by asias** [comment]
@raphaelsc Can you please comments on the idea of futurize 
 consume_end_of_stream?

**Comment by denesb** [comment]
@asias sstable writing happens in a thread.

**Comment by asias** [comment]
@denesb So can I assume everything call in the chain:

sstable_writer_k_l::consume_end_of_stream and mc::writer::consume_end_of_stream -> sstable::write_scylla_metadata -> create_sharding_metadata -> dht::split_range_to_single_shard

runs in a thread?

**Comment by denesb** [comment]
Yes, the sstable writer assumes a thread context.
