### ISSUE TITLE
commitlog replay failures are silently ignored.

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#3847]
We currently happily skip over corrupted commitlog files, just printing a warning to the logs.
This is not only dangerous - since most people won't see the logs until it is too late, but also may make debugging those issues impossible: the replay will seem successful, and after a flush the commitlog file will be deleted. We will then never know how it got corrupted.

I propose we stop doing this, and halt the database start on commitlog replay failures. If the user desires, they can delete those files themselves.

**Comment by glommer** [comment]
The ability to skip over corrupted mutations was added explicitly in commit 76b43fbf74a54bc22a320fa4def36efcdb1fccbe

@elcallio would you not agree with the danger rationale I exposed above? Anything I should be aware of that led you to add this functionality ?

**Comment by elcallio** [comment]
See #593.

**Comment by avikivity** [comment]
I don't see how we can change this. It would mean recovery after power failure would require operator intervention.

**Comment by glommer** [comment]
Only if we corrupt parts of the commitlog, no ? I would expect the commitlog to be in a sane state even after a power failure.
