### ISSUE TITLE
OOM during cassandra-stress write test

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#385]
I'm running a 2-cpu Scylla nodes on the same machine, with 1GB of memory each, and adding 11 million partitions to both nodes (RF=2) with a cassandra-stress write run:

```
/home/nyh/cassandra/cassandra.git/tools/bin/cassandra-stress write n=11000000 -schema "replication(strategy=org.apache.cassandra.locator.SimpleStrategy,factor=2)" 
```

This eventually (after about 8 million partitions) runs out-of-memory:

```
ERROR [shard 0] database - failed to write sstable: std::bad_alloc
ERROR [shard 0] compaction_manager - compaction failed: std::bad_alloc
ERROR [shard 0] database - failed to write sstable: std::bad_alloc
scylla: sstables/sstables.cc:1129: void sstables::prepare_summary(sstables::summary&, uint64_t): Assertion `expected_partition_count >= 1' failed.
```

I can reproduce this problem, and it always fails during the compaction phase. 
Looking at the sstable directory at the time at the crash, we have generation 127 currently written by a compaction (so it still has a tmp TOC),  generations 128 through 133 have all been successfully flushed to disk (but not yet compacted), generation 134 is partially flushed, and generation 135 has empty files - my guess (?) is that this is either an attempt to start a second compaction in parallel, or an attempt to start flushing another memtable while the previous one is still being flushed.

When I try to do the same thing with only one node, it does *not* run out of memory, which is surprising because one would expect that in the two-node test, each node does the same as the single node, so the single node would run out of memory in the same way - but it doesn't.

So my suspicion (not yet completely founded) is that I have a problem with backlog of unflushed memtables which fill the memory: The two nodes run on the same machine (my laptop) so share the same disk. With a single node, I see in iostat a peak write of about 25 MB/sec, so it is possible (?) my laptop's SSDs cannot handle the full write speed of two nodes (the maximum I'm seeing is 35 MB/sec), and while two nodes are busy doing a long compaction at full speed, they cannot flush memtables quickly enough and those start to pile up and deplete the available memory. Again, this is just a guess.

**Comment by avikivity** [comment]
Memtables are limited to 50% of memory

**Comment by slivne** [comment]
We have fixed #642 - @nyh is this still reproducible

**Comment by slivne** [comment]
@nyh - ping ?

**Comment by slivne** [comment]
@nyh - ping

**Comment by nyh** [comment]
@slivne, #642 is unrelated, because in that issue the problem was that we didn't leave enough memory *outside* scylla, causing the kernel to kill random programs including scylla. In this issue my problem was that scylla ran out of its own memory.

I'm trying to reproduce this problem with the latest scylla, and will update whether I can still reproduce it, or it appears to have been fixed.

**Comment by nyh** [comment]
This bug appears to have been fixed already, so I'm closing it.

I run the same workload on latest Scylla, with double the run time (22 million writes, taking 28 minutes on my laptop), even while a large compaction of a 1 GB file is going, on, sstable flushing seems to proceeding as well, and scylla does **not** run out of memory. 

The total amount of disk write bandwidth hovers between 30 MB - 35 MB per second, exactly as reported earlier, so there is no regression there as well. Cassandra-stress performance seems to fluctuate a bit from second to second (seeing numbers between 10,000 and 18,000 operations per second), but there is no dramatic performance drop while the huge compactions are in progress. Another good sign is that throughout the huge compactions, we seeing read bandwidth about one third of write bandwidth, suggesting that compaction's write bandwidth, memtable flush bandwidth, and commit log bandwidth is shared equally (while the read bandwidth is more-or-less the same as the compaction write bandwidth).

Moreover, if I lower the amount of memory per node from 1GB to merely 100MB, Scylla has a much harder time, often barely able to process any requests while compaction is still ongoing (and filling up memory), and it flushes memtables much more often, but Scylla still does not crash. Good sign.

So I think this bug is gone.
