### ISSUE TITLE
When overloaded with range scans, Scylla starts trashing them

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#3856]
Affected Scylla versions: master, 3.0

Range scans involve a lot of work. Multiple reads have to be made, from multiple shards. If any of these reads fail, the entire scan fails, wasting all the work that went into filling the page so far. When a node is overloaded with range scans it starts "trashing". Range scans can't complete as at some point in filling the page, a read request is timed out by the read concurrency semaphore, killing the entire scan. If the overload is bad enough, barely any scan can make any progress, as the client keeps retrying failed scans.
This has become even worse with the introduction of stateful range scans. Now range scans keep all their shard readers alive, at least for the duration of filling the page. All the more chance that any given scan will hit a time-out on one of the shards, due to the heavily overloaded read queues.

From the client's perspective this has surprising effects. Up until a certain point, let's call it the *treshold*, increasing range scan concurrency yields higher throughput. However once pushed past the treshold, concurrency drops drastically, most of the requests time out, range scans starts to trash.

This drop was observed to be as bad 1/3 of the pre-treshold request rate. As a user I would expect the database to start rejecting requests when it reaches a point where it cannot handle any more requests, pushing more requests should result in maintaining the maximum request rate (or close to it) and rejecting requests it cannot handle.

**Comment by duarten** [comment]
We should work on also applying backpressure for reads. We can use the same strategy as for views, and reflect a replica's read queue at the coordinator.

**Comment by denesb** [comment]
I was experimenting yesterday with admission control (overload protection) on the replica level, with promising results. Do you think replica-level admission control still makes sense if we'd have backpressure.

**Comment by gleb-cloudius** [comment]
On Tue, Oct 16, 2018 at 11:34:05PM -0700, Botond Dénes wrote:
> On second though, backpressure and admission control are orthogonal, it's best to have both.
> 
Exactly. Back pressure does nothing for clients with unlimited
parallelism (unlimited = more than we can handle).

--
			Gleb.

**Comment by duarten** [comment]
We need both. For reads we can start to shed load when running low on memory, and also when having too many in-flight IO requests.

**Comment by denesb** [comment]
On Wed, 2018-10-17 at 00:06 -0700, Duarte Nunes wrote:
> We need both. For reads we can start to shed load when running low on
> memory, and also when having too many in-flight IO requests.

We already have load shedding in form of the concurrency semaphores.
When we have more requests than we can handle, reads start to timeout,
and we also have an upper limit for the number of queued requests.

The problem is that this doesn't work well for range scans, as in their
case it's not the entire read that is timed out, but just one (or more)
if the shard readers. So we need something that estimates whether the 
scan can can finish or not before even starting to process it. I'm
working on something like this.

**Comment by denesb** [comment]
We had this before to some extent, #1865 just made it worse. My fix for #3835 should make this better, essentially going back to how it was before.
The fact however remains, when overloaded, the performance will drop significantly, compared to the peak performance Scylla can offer.
@avikivity had a suggestion that should further improve this. His suggestion was that shard readers belonging to a range scan should not go through the queue of their respective concurrency semaphore, instead they should be allowed to just "steal" the units they need, allowing range scans to proceed unhampered by other reads, once they acquired a permit for the entire scan.

**Comment by denesb** [comment]
@slivne after some thinking I think this *is* a regression, in the same way that #3835 is.

**Comment by avikivity** [comment]
I think the problem is that the concurrency semaphore won't evict idle queriers. If it did, then in the worst case 3.0 would perform like 2.3 (queriers would be cached and immediately evicted).

**Comment by denesb** [comment]
According to my observations, the querier cache has a very low population (< 3), so eviction works, but you are right in that it doesn't evict as much as it could, as it is not notified of new queriers inserted into the cache. Instead it only evicts these newly inserted queriers, when a new reader is enqueued.
I think the fact that the multishard reader holds on to all of its shard readers is a much larger factor in this, and making inactive readers evictable will essentially make the worst case perform like 2.3 (only one reader active at a time, readers recreated each time a shard is visited).

**Comment by denesb** [comment]
Fixed by 414b14a6bd803a432fbb72ad32ac60bec81e569c. In my manual tests this problem didn't manifest itself anymore after the fix. A workload, that before the fix would generate a timeout storm, had no timeouts at all after the fix, even after further increasing the concurrency.
