### ISSUE TITLE
View building should avoid storing view updates as hints

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3857]
View building works on data that is already on disk at a base replica, so if a target view replica is down, then we don't benefit from writing the view updates as hints to retry later. Instead, we can simply resume view building when the view replica becomes available. 

The drawback is that retrying a view building iteration means sending updates to potentially many view replicas, which will have to process this extra load (and write amplification) in case only one of them was unavailable.

**Comment by nyh** [comment]
Doesn't this "drawback" disqualify the idea? I'll try to explain, but I understood two different ideas from you :-)

1. Your first paragraph suggests that we pause the view building the first time a view replica is unavailable. In the general case (where the partition key of the view is not the same as the base's)  every base write ends up going to (at least one) different view replica. So if we have just one dead node in the system, all view building activity in the system will pause very quickl. I don't think this is acceptable, what do you think?

2. Your second paragraph suggests we do continue the build process even if some writes cannot be done, as today, but don't write hints. Instead, you seem to suggest we redo the entire step again later. As above, in a large system with, say, 50 nodes, we would be re-doing work that only 1/50th of it failed. That sounds like incredible waste, not just a "drawback", no? 

It sounds to me like today's method, of writing hints, makes most sense. When we have too many of those hints, or they expire, that's fine too - it would be similar to the case of a normal write with one of the view replicas being unavailable - One of the view replicas will be missing data, and some repair (?) will fix it.

**Comment by duarten** [comment]
Right now we don't really pause view building per se, we just sleep for a while when we get an exception, and retry again afterwards. We only get an exception if we fail to send the view update and fail to write a hint. We can be much smarter here, but it's not clear how far we want to go. (A simple improvement would be to plug in to the gossip layer to resume when the view replica is again available.)

In the absence of hints, allowing individual view replicas to fall behind results in an explosion of complexity, both in bookkeeping data structures and also in code. Hints allow this to happen naturally. However, we can easily run out of disk space. We could slow down view building as we see the the hints queue growing, but this might be indistinguishable from pausing view building and resuming at full speed "later".

Maybe the current approach is indeed the best compromise, as hints allow us to handle a small window of view replica unavailability, and pausing/backing-off allows us to handle a greater window of unavailability.

**Comment by duarten** [comment]
I think MV partition key selectivity is important here too. For a highly selective key, then leveraging hinted handoff is a great option, because it’s what saves the most amount of work. 

On the other hand, a key with low selectivity can cause us to try to send most updates to the same view replica. This can deplete the hinted handoff disk queue, depending on the size of those updates and the period of unavailability. 

A good compromise would be too keep track of the hints backlog, and back off accordingly.
