### ISSUE TITLE
fail to launch scyllatop for permission issue to open /etc/scylla.d/scyllatop.log

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3860]
*Installation details*
Scylla version (or git commit hash): 3.0.rc0-0.20181017.0fee1d9e4
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

```
[amos@amos-centos7 scylla.d]$ scyllatop
Traceback (most recent call last):
  File "/usr/lib/scylla/scyllatop/scyllatop.py", line 82, in <module>
    file_log = logging.FileHandler(filename=arguments.logfile)
  File "/usr/lib64/python2.7/logging/__init__.py", line 902, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib64/python2.7/logging/__init__.py", line 925, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/etc/scylla.d/scyllatop.log'

[amos@amos-centos7 scylla.d]$ ls -lh /etc/|grep scylla
drwxr-xr-x.  5 root root 4.0K Oct 17 09:13 scylla
drwxr-xr-x.  3 root root 4.0K Oct 17 09:13 scylla.d
[amos@amos-centos7 scylla.d]$ ls -l
total 36
drwxr-xr-x  2 scylla scylla   6 Nov 14  2017 conf
-rw-r--r--  1 root   root    21 Oct 17 09:20 cpuset.conf
-rw-r--r--  1 root   root    21 Oct 17 09:14 cpuset.conf.rpmsave
-rw-r--r--  1 root   root   118 Oct 17 05:36 dev-mode.conf
-rw-r--r--  1 root   root   146 Dec 21  2017 dev-mode.conf.rpmsave
-rw-r--r--  1 root   root    35 Oct 17 05:36 housekeeping.cfg
-rw-r--r--. 1 root   root    37 Mar 16  2017 housekeeping.uuid
-rw-r--r--  1 root   root    35 Oct 17 09:20 io.conf
-rw-r--r--  1 root   root    35 Oct 17 09:14 io.conf.rpmsave
-rw-r--r--  1 root   root    55 Jan 30  2018 perftune.yaml
[amos@amos-centos7 scylla.d]$ ls -lh /etc/scylla.d/scyllatop.log
ls: cannot access /etc/scylla.d/scyllatop.log: No such file or directory
```

```
[amos@amos-centos7 scylla.d]$ rpm -qf /usr/bin/scyllatop
scylla-server-3.0.rc0-0.20181017.0fee1d9e4.el7.x86_64
```

**Comment by slivne** [comment]
what is the log file ? did we have it in the previous incarnation of scyllatop - or this in addition.

if it was in the previous incarnation what has changed ?

could it be that scyllatop is invoked in a bad manner ?

**Comment by amoskong** [comment]
scyllatop will open/create a log file (default is ./scyllatop.log in current directory)

We need better error note, such as: 
`Fail to create log file (/etc/scylla.d/scyllatop.log), you can specify path for log file by  it by `-L LOGFILE, --logfile LOGFILE`

**Comment by slivne** [comment]
@amnonh still I need an answer

**Comment by amnonh** [comment]
The logging is there from the beginning and was last modified about 3 years ago.
I assume the issue arises because the test tries to run nodetool from /etc/scylla.d directory.

I'll send a patch for a better error code, but it would still fail.
so regardless, the test needs to be changed.

**Comment by amoskong** [comment]
@amnonh The problem was found in manual testing (I changed some configure file in /etc/scylla.d/), our scyllatop test in dtest is fine (no permission problem).

**Comment by amnonh** [comment]
Great!
Still, a nicer error code is a good idea so let's keep this issue open until the relevant patch is merged.

**Comment by tzach** [comment]
@amoskong can we close this issue?

**Comment by amnonh** [comment]
@tzach see my comment, let's keep it open until the patch with the better warning is merged
