### ISSUE TITLE
UX: no output after lunch scyllatop for 3 seconds

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3864]
*Installation details*
Scylla version (or git commit hash): 3.0.rc0-0.20181017.0fee1d9e4
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

* Description:
Launch `scyllatop`, the default screen is empty. Scyllatop should try to connect with node (prometheus server) to collect information and then display on the screen.

In my test, sometimes it can't get outputs in 3 seconds, 5 seconds is safe.

Question: 
1. how much wait time is acceptable for users? do we need to optimize it?

Suggestion for UX:
display something by default, such as: `Scyllatop is connecting the server to collect information ..... `.
Or display some information can be easy got, such as:
- scylla process information
- /var/lib/scylla mount point
- configuration: io.conf / cpu.conf
- scylla website / github issue  address
- etc

At least, we know scyllatop works well.

**Comment by tzach** [comment]
3 sec seems very long for a non-java app to start
The progress dots suggestion make sense

**Comment by tzach** [comment]
Closing. scyllatop is less popular these days, as users moved to the monitoring stack.
