### ISSUE TITLE
Enqueueing multishard_combining_readers to the read concurrency semaphore without timeout may cause deadlock

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#3865]
Given: readerA, readerB, two shards with a single available permit
* readerA: open reader on shard 0 -> obtain permit
* readerB: open reader on shard 1 -> obtain permit
* reader A: open reader on shard 1 -> queued
* readerB: open reader on shard0 -> queued

The two readers now are in a deadlock.
This can only happen when a semaphore is hit with many multishard reads that don't have a timeout. Having a timeout resolves the deadlock as one of the readers will timeout, giving way to the other one.
Reads without timeout are a legit use case, for example, repair and system queries don't use timeout.

**Comment by slivne** [comment]
copy pasting avi's inputs

> Previously, the wait we avoided such problems is to let a reader continue to make progress by borrowing from the semaphore instead of waiting on it. Perhaps we can do the same?
> 
> But don't we have this:
> 
> 
>     auto r = resources(1, static_cast<ssize_t>(memory));
>     if (!may_proceed(r) && _evict_an_inactive_reader) {
>         while (_evict_an_inactive_reader() && !may_proceed(r));
>     }
> 
> 
> Perhaps the multishard reader should return the readers to the cache when not using them, even during a scan, so it only uses and holds a permit for one at a time.
>

**Comment by denesb** [comment]
In theory fixed by 414b14a6bd803a432fbb72ad32ac60bec81e569c but I have received reports of the deadlock still happening. Investigating...

**Comment by denesb** [comment]
After some investigation it seems there are two problems:
1) Not all EOS'd readers are paused (made evictable).
2) Readers created as part of a read-ahead are only paused when the multishard reader reaches them and moves to another shard. These readers can consume all the permits and cause a deadlock.

(1) is easy to fix, (2) is not that easy.

**Comment by denesb** [comment]
A simple (but very brute) solution is to disable read-ahead altogether. This is not desirable however, as read-ahead can benefit reads of small tables greatly.
