### ISSUE TITLE
scylla-jmx org.apache.cassandra.metrics:type=ColumnFamily MBean missing in 2.3

### ISSUE THREAD

**Issue by whitedr** [scylladb/scylla#3869]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 2.3
Cluster size: 3 i3.2xl
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

After upgrading from 2.2 -> 2.3, I was no longer able to see the MBeans under: `org.apache.cassandra.metrics:type=ColumnFamily,*` (or the ones in `org.apache.cassandra.metrics:type=Table,*` which I believe are an alias for ColumnFamily).  These are the ones that I do still see under that path in jconsole:

<img width="237" alt="screen shot 2018-10-18 at 4 43 36 pm" src="https://user-images.githubusercontent.com/59305/47183069-11aa6400-d2f5-11e8-8b6e-e225e8b0c134.png">

**Comment by glommer** [comment]
@amnonh

**Comment by amnonh** [comment]
@elcallio

**Comment by elcallio** [comment]
Afaict, this is "Reduce memory usage and speed up start time" from @haaawk that has stopped working.  
See /scylladb/scylla-jmx#57

**Comment by slivne** [comment]
fixed - will be part of 2.3.1
