### ISSUE TITLE
when 2.2 nodetool repair will coredump

### ISSUE THREAD

**Issue by wqwiii** [scylladb/scylla#3873]
Oct 19 19:24:53 scylla6 scylla: scylla: sstables/consumer.hh:324: seastar::future<> data_consumer::continuous_data_consumer<StateProcessor>::fast_forward_to(size_t, size_t) [with StateProcessor = sstables::data_consume_rows_context; size_t = long unsigned int]: Assertion `begin >= _stream_position.position' failed.
Oct 19 19:24:53 scylla6 scylla: Aborting on shard 0.
Oct 19 19:24:53 scylla6 scylla: Backtrace:
Oct 19 19:24:53 scylla6 scylla: 0x00000000005b010c
Oct 19 19:24:53 scylla6 scylla: 0x00000000005b03b5
Oct 19 19:24:53 scylla6 scylla: 0x00000000005b0463
Oct 19 19:24:53 scylla6 scylla: /lib64/libpthread.so.0+0x000000000000f6cf
Oct 19 19:24:53 scylla6 scylla: /lib64/libc.so.6+0x0000000000036276
Oct 19 19:24:53 scylla6 scylla: /lib64/libc.so.6+0x0000000000037967
Oct 19 19:24:53 scylla6 scylla: /lib64/libc.so.6+0x000000000002f095
Oct 19 19:24:53 scylla6 scylla: /lib64/libc.so.6+0x000000000002f141
Oct 19 19:24:53 scylla6 scylla: 0x0000000001753592
Oct 19 19:24:53 scylla6 scylla: 0x000000000177bbc6
Oct 19 19:24:53 scylla6 scylla: 0x0000000000592ee6
Oct 19 19:24:53 scylla6 scylla: 0x00000000005930a1
Oct 19 19:24:53 scylla6 scylla: 0x0000000000658ca7
Oct 19 19:24:53 scylla6 scylla: 0x0000000000784a5f
Oct 19 19:24:53 scylla6 scylla: 0x000000000051ce5e
Oct 19 19:24:53 scylla6 scylla: /lib64/libc.so.6+0x0000000000022444
Oct 19 19:24:53 scylla6 scylla: 0x000000000058d11d

**Comment by slivne** [comment]
@wqwiii ping

**Comment by slivne** [comment]
@wqwiii closing the issue - if you still have the coredump please post and we will reopen
