### ISSUE TITLE
Add Scylla version to first printout of a backtrace

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla#3879]
To help understand a backtrace, it will be helpful to know the version of Scylla version the backtrace belongs to.
At least on the first backtrace printout, add also the Scylla version this backtrace belongs to.

for example:
 scylla[32483]: Reactor stalled for 1100 ms on shard 7.
scylla[32483]: Backtrace:
**scylla[32483]: Version: 2.3.rc2-0.20180828.b47d18f9f**
 scylla[32483]: 0x000000000050f422
 scylla[32483]: 0x00000000004a537b
 scylla[32483]: 0x00000000004a5611
scylla[32483]: /lib64/libpthread.so.0+0x000000000000f6cf
 scylla[32483]: 0x0000000000aef664
scylla[32483]: 0x0000000000b026ed
scylla[32483]: 0x0000000000b66803
 scylla[32483]: 0x0000000000b68efd

**Comment by glommer** [comment]
Agree with Eyal. There are times in which all we have is the backtrace and there is confusion about the version running. It's simple enough to add and can go a long way

**Comment by denesb** [comment]
The code that collects and prints backtraces is in `seastar::core`, while the version is in Scylla code. Also, most backtraces are generated without any Scylla intervention (from a signal handler).
So we need to come up with an application meta-information mechanism that Scylla can use to register its name and version.

**Comment by avikivity** [comment]
What, even more lines in a backtrace?

Let's try to use journald fields to store this metadata.

**Comment by tzach** [comment]
@avikivity if you are against this, please close the issue
