### ISSUE TITLE
Scylla's shadowable tombstones are not written to SSTables 3.x.

### ISSUE THREAD

**Issue by argenet** [scylladb/scylla#3885]
Scylla's shadowable tombstones used in materialized views differ from those used by Cassandra in that Scylla maintains two tombstones, regular and shadowable, and needs to write/read either of those or both from/to SSTables.

We need to support this as a Scylla-specific extension to the SSTables `mc` format that is not backward-compatible with Cassandra.

It is deemed to be safe to do since we don't import MVs to Scylla anyway (we have to re-build them from base tables).

**Comment by argenet** [comment]
The fix for this issue has been merged in as `8210f4c982396aba127cfc2511998c502bed39b5` so it can be closed.

**Comment by slivne** [comment]
fixed by  scylladb/scylla@8210f4c982396aba127cfc2511998c502bed39b5
