### ISSUE TITLE
ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [scylladb/scylla#389]
Is there a possibility to consider licensing ScyllaDB sever components also under a liberal license like ASL 2.0

**Comment by avikivity** [comment]
Some server components are available under ASL 2.0, see https://github.com/scylladb/seastar.  The Scylla core is under deliberately under AGPL in order to protect it from abuse by SaaS vendors like cloud providers; under a more liberal license they could simply keep their own changes to themselves without giving back to the community.

**Comment by sirinath** [comment]
I am not sure if they will have their own fork, but there is inertia to use GPL family code. Any way aside from this perhaps you can also consider joining the Apache Software Foundation? You definitely will get more exposure and wider adaptation.

Also with this new product what is your commitment to OSv? I see commits are becoming less frequent lately.

**Comment by avikivity** [comment]
We will certainly consider joining ASF.  I can't promise anything, of course, but we will consider it.

OSv is still a ScyllaDB project; it's true that development is slower but it is not orphaned.

**Comment by sirinath** [comment]
ASF might be a good idea for Seastar and OSv also.

**Comment by ronnyek** [comment]
Protecting against SaaS vendors in which way? I want to build a service that utilizes scylladb, but happens to be a part of a SaaS piece of software... I immediately have to move to some hugely expensive commercial license? 

Thats an honest question... seems like licensing is always a touchy subject and I agree, I wouldnt want to release something have people abuse that relationship... just seems like in this day and age, the likelihood of someone wanting to use scylla or cassandra as a part of a SaaS package is pretty common thing.

**Comment by penberg** [comment]
@ronnyek IANAL, so you really need to read up on AGPL yourself or consult a professional if you don't understand the license.

That said, you don't pay for a license to _run_ GPL-licensed Linux, do you? The only difference between GPL and AGPL is that the latter closes a loophole where SaaS vendors can _modify_ the sources and never contribute the changes back as long if they don't distribute the binaries.

AGPL does not allow that so if you modify the sources, you need to share your changes. But it doesn't restrict your ability to run an unmodified version of Scylla. In fact, the AGPL license is very explicit on that:

```
This License explicitly affirms your unlimited permission to run the unmodified Program.
```

Also, if you understand how copyleft licenses work, it's important to remember that your applications link against the drivers that are Apache licensed, not the AGPL licensed server code.

So I don't really know how we could abuse the relationship. But like I said, you really should really figure out the AGPL license for yourself if you are worried.

**Comment by ronnyek** [comment]
Sorry my references to paying to license the software was more something I picked up from ITextSharp, and ServiceStack projects where basically you can use the software as you see fit (as long as the modification clauses are met) with the exception of hosting in the cloud... (in which case you buy a commercial license). As you can see if this were in fact the case with this software, that would be prohibitive.

I do get what you are saying when you say you link against the apache drivers... and that is sufficient.

**Comment by penberg** [comment]
@ronnyek Remember, the AGPL is a software license governed by the Free Software Foundation, not by us. It is also approved by the Open Source Initiative. I don't know the licenses of the two products you mention but I highly doubt such a clause would be possible for an OSI-approved license and there's no chance in hell FSF would come up with one.

**Comment by sirinath** [comment]
Any way it will be interesting if this becomes a ASF project with multiple organisation backing up the project. More stable and larger contribution. Hence please consider joining ASF.

**Comment by RobertoMalatesta** [comment]
+1 on @sirinath's stance.
Affero's license bad reputation is the Kiss of Death in enterprises.

**Comment by sirinath** [comment]
ASL 2.0 gives corporate clients a peace of mind and contractors can readily use such projects without much overheads or approvals. The cases any one forking a project like this is very minimal or next to nothing. If you look at forks mainly they happen due to discord in community. In your case most of the contributors are from one company and there is no sizable contributor community to make a fork. Also for a company to fork this is is losing proposition as any new updates will not get incorporated into their code base of they have to incorporate it themselves. If they have any cases they are better off upstreaming what they have changed. Perhaps you can encourage contribution like this. I think ASL and even perhaps ASF is the way to go forward.
