### ISSUE TITLE
problem with scylla_setup( raid0 xfs)

### ISSUE THREAD

**Issue by erzent** [scylladb/scylla#3893]
*Installation details*
Scylla version (or git commit hash): scylla-2.3.1-0.20181021.336c77166.el7.x86_64
Cluster size:
OS CentOS Linux release 7.5.1804 (Core)

*Hardware details (for performance issues)*          
Platform vm vmware esxi 6.5
Hardware: sockets= 4 core= hyperthreading= yes memory= 8
Disks: HDD
lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
sda      8:0    0   40G  0 disk 
├─sda1   8:1    0    1G  0 part /boot
└─sda2   8:2    0   38G  0 part /
sdb      8:16   0   40G  0 disk 
sdc      8:32   0   40G  0 disk 
sdd      8:48   0   40G  0 disk 

during surgery :"please select unmounted disks from the following list: ['/dev/sdd', '/dev/sdc', '/dev/sdb']"
the following error occurs : 
> '/dev/sdd', '/dev/sdc', '/dev/sdb'
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: []
'/dev/sdd' not found
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: []
 '/dev/sdc' not found
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: []
 '/dev/sdb' not found
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: []

drives are empty, not mounted

**Comment by slivne** [comment]
@erzent is there additional information you can share ....

**Comment by slivne** [comment]
closing the issue 

@erzent we do not have enough information to try and fix this
