### ISSUE TITLE
Better name resolution error msg

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#3894]
Scylla version: 2.3

Here is the output of a bad resolution, hard to realize what's the error is, need to be more descriptive and print the faulty name:

ERROR 2018-10-27 19:38:01,572 [shard 0] init - Bad configuration: invalid value in 'seeds': 'scylla-0.scylla.default.svc.cluster.local': std::system_error (error C-Ares:4, Not found)
ERROR 2018-10-27 19:38:01,575 [shard 0] seastar - Exiting on unhandled exception: bad_configuration_error (std::exception)

**Comment by dorlaor** [comment]
Thanks!

**Comment by tzach** [comment]
@elcallio @dorlaor can we close this issue?
