### ISSUE TITLE
Column count recorded in sstable statistics in the mc format is twice as large

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#3898]
*Installation details*
Scylla version (or git commit hash): 3.0-rc1

Current code invokes the cell writer twice (first to size it, then to write it), hence updating the statistics twice.

**Comment by bhalevy** [comment]
@tgrabiec wasn't this fixed in 0a9f5b563a2c556ad30ed4e8829d2f5588221ba8 ?

**Comment by tgrabiec** [comment]
Yes.
