### ISSUE TITLE
Not able to run scylla on docker

### ISSUE THREAD

**Issue by visshal** [scylladb/scylla#390]
Environment: Mac OS/X 10.10.5 Yosemite, 2.7 GHz, 16 GB RAM
Steps to reproduce:
1. boot2docker init
2. boot2docker up
3. docker pull scylladb/scylla
4. docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
scylladb/scylla     latest              36b0904b18db        21 hours ago        819.4 MB
5. docker run -p 192.168.59.103:9042:9042 -i -t scylladb/scylla
scylla: core/memory.cc:1020: void memory::configure(std::vector<resource::memory>, std::experimental::fundamentals_v1::optional<std::basic_string<char> >): Assertion `r == 0' failed.
/start-scylla: line 11:     7 Aborted                 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --options-file $HOME/scylla.yaml --listen-address $IP --rpc-address $IP --network-stack posix

**Comment by penberg** [comment]
@avikivity Looks like the mbind() system call fails in that setup. Perhaps we should just the assertion and print a warning instead?

**Comment by dorlaor** [comment]
On Wed, Sep 23, 2015 at 9:13 AM, Pekka Enberg <notifications@github.com>
wrote:

> @avikivity <https://github.com/avikivity> Looks like the mbind() system
> call fails in that setup. Perhaps we should just the assertion and print a
> warning instead?
>

Any idea why it fails on boot2docker and works on Ubuntu as a docker file?

**Comment by penberg** [comment]
@dorlaor Not really but I can always speculate...

Boot2docker is actually a light-weight Linux distribution that runs on top of a hypervisor. Perhaps the Linux kernel they're using doesn't have NUMA enabled (and the system call always fails) or the hypervisor provided memory layout is wrong.

Regardless, I don't really see why mbind() failing should _kill_ the process. Yes, it can lead to suboptimal performance on real NUMA machines but a warning should be sufficient.

But lets ask @avikivity to voice his opinion.

**Comment by avikivity** [comment]
Failing fast is better than not failing and hiding the problem, but now that there's a real use case that fails, we have to support it.

**Comment by penberg** [comment]
@visshal The bug is fixed but I haven't uploaded a new Docker image yet. I'll ping you when that's done.

**Comment by visshal** [comment]
@penberg : Sure please let me know asap, I am so looking forward to try Scylla.

**Comment by penberg** [comment]
@visshal Sorry for the delay. I have now uploaded a new version to Docker Hub which should fix the problem you were seeing.

**Comment by visshal** [comment]
Thanks @penberg : Just started pulling scylladb/scylla during Avi's talk at summit. I'll post here once I get it up and running.

**Comment by visshal** [comment]
Okay so it worked well and I was able to start the scylla db server on 9042 and connect CQL driver.

Thanks. Will play around more.

 docker run -p 192.168.59.103:9042:9042 -i -t scylladb/scylla
WARNING: unable to mbind shard memory; performance may suffer: 
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Detected lcore 2 as core 2 on socket 0
EAL: Detected lcore 3 as core 3 on socket 0
EAL: Detected lcore 4 as core 4 on socket 0
EAL: Detected lcore 5 as core 5 on socket 0
EAL: Detected lcore 6 as core 6 on socket 0
EAL: Detected lcore 7 as core 7 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 8 lcore(s)
EAL: VFIO modules not all loaded, skip VFIO support...
EAL: Setting up physically contiguous memory...
EAL: Cannot open /proc/self/pagemap: Operation not permitted. virt2phys address translation will not work
EAL: TSC frequency is ~2704657 KHz
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: Master lcore 0 is ready (tid=9b112bc0;cpuset=[0])
Scylla version 0.9-20150924.49d6cba starting ...
Start Storage service ...
Start gossiper service ...
Starting listening for CQL clients on 172.17.0.1:9042...
Seastar HTTP server listening on 172.17.0.1:10000

**Comment by teodor-pripoae** [comment]
Hi,

My container is running at 100% CPU on one core, with empty database. Any idea why ?

```
$ docker run -i -t -p 9042:9042 -p 9160:9160 -p 10000:10000 scylladb/scylla

$ docker stats <cid>
CONTAINER           CPU %               MEM USAGE/LIMIT     MEM %               NET I/O
efdcd1259fe3        100.98%             42.09 MB/6.274 GB   0.67%               508 B/12.03 kB
```

Running on boot2docker / OSX

**Comment by teodor-pripoae** [comment]
Console log:

```
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Detected lcore 2 as core 2 on socket 0
EAL: Detected lcore 3 as core 3 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 4 lcore(s)
EAL: VFIO modules not all loaded, skip VFIO support...
EAL: Setting up physically contiguous memory...
EAL: Cannot open /proc/self/pagemap: Operation not permitted. virt2phys address translation will not work
EAL: TSC frequency is ~2294289 KHz
EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
EAL: Master lcore 0 is ready (tid=c4ffebc0;cpuset=[0])
Scylla version 0.9-20150924.49d6cba starting ...
Start Storage service ...
Start gossiper service ...
Starting listening for CQL clients on 172.17.0.133:9042...
Seastar HTTP server listening on 172.17.0.133:10000
```

**Comment by avikivity** [comment]
It's an artifact of the way seastar works.  We're working on improving things, but the server is working as expected.

**Comment by dahankzter** [comment]
I can't get this to work again. I have this now:

docker is configured to use the default machine with IP 192.168.99.100
For help getting started, check out the docs at https://docs.docker.com

➜  ~ docker pull scylladb/scylla
Using default tag: latest
latest: Pulling from scylladb/scylla

Digest: sha256:250ad21b909892ca3c6ed523ee26024ccbecce81ea0dc8a66ae485d0cbb46718
Status: Image is up to date for scylladb/scylla:latest
➜  ~ docker run -p 127.0.0.1:9042:9042 -i -t scylladb/scylla
WARNING: unable to mbind shard memory; performance may suffer:
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Detected lcore 2 as core 2 on socket 0
EAL: Detected lcore 3 as core 3 on socket 0
EAL: Detected lcore 4 as core 4 on socket 0
EAL: Detected lcore 5 as core 5 on socket 0
EAL: Detected lcore 6 as core 6 on socket 0
EAL: Detected lcore 7 as core 7 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 8 lcore(s)
EAL: VFIO modules not all loaded, skip VFIO support...
EAL: Setting up physically contiguous memory...
EAL: Cannot open /proc/self/pagemap: Operation not permitted. virt2phys address translation will not work
EAL: TSC frequency is ~2793533 KHz
EAL: Master lcore 0 is ready (tid=62e7f680;cpuset=[0])
EAL: lcore 7 is ready (tid=53486700;cpuset=[7])
EAL: lcore 2 is ready (tid=55c8b700;cpuset=[2])
EAL: lcore 1 is ready (tid=5648c700;cpuset=[1])
EAL: lcore 5 is ready (tid=54488700;cpuset=[5])
EAL: lcore 6 is ready (tid=53c87700;cpuset=[6])
EAL: lcore 3 is ready (tid=5548a700;cpuset=[3])
EAL: lcore 4 is ready (tid=54c89700;cpuset=[4])
EAL: PCI device 0000:00:03.0 on NUMA socket 0
EAL:   probe driver: 8086:100e rte_em_pmd
EAL:   Not managed by a supported kernel driver, skipped
EAL: PCI device 0000:00:08.0 on NUMA socket 0
EAL:   probe driver: 8086:100e rte_em_pmd
EAL:   Not managed by a supported kernel driver, skipped
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer: WARNING: unable to mbind shard memory; performance may suffer:

WARNING: unable to mbind shard memory; performance may suffer:
WARNING: unable to mbind shard memory; performance may suffer:
Scylla version 1.0.2-20160423.60307f6 starting ...
Scylla API server listening on 127.0.0.1:10000 ...



And the example bench:

./cassandra-stress write -mode cql3 native
java.lang.RuntimeException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1] Cannot connect), localhost/0:0:0:0:0:0:0:1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect))
	at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:217)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpacesNative(SettingsSchema.java:79)
	at org.apache.cassandra.stress.settings.SettingsSchema.createKeySpaces(SettingsSchema.java:69)
	at org.apache.cassandra.stress.settings.StressSettings.maybeCreateKeyspaces(StressSettings.java:224)
	at org.apache.cassandra.stress.StressAction.run(StressAction.java:54)
	at org.apache.cassandra.stress.Stress.main(Stress.java:121)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1] Cannot connect), localhost/0:0:0:0:0:0:0:1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/0:0:0:0:0:0:0:1] Cannot connect))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:231)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:77)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1414)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:393)
	at org.apache.cassandra.stress.util.JavaDriverClient.connect(JavaDriverClient.java:143)
	at org.apache.cassandra.stress.settings.StressSettings.getJavaDriverClient(StressSettings.java:208)
	... 5 more

I can't telnet to the 9042 port either. Am I missing something or?

**Comment by dahankzter** [comment]
Reinstalling docker machine completely gives:

docker run -p 127.0.0.1:9042:9042 -i -t scylladb/scylla
WARNING: unable to mbind shard memory; performance may suffer:
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 1 lcore(s)
EAL: VFIO modules not all loaded, skip VFIO support...
EAL: Setting up physically contiguous memory...
EAL: TSC frequency is ~2793534 KHz
EAL: Master lcore 0 is ready (tid=1a4f0680;cpuset=[0])
EAL: PCI device 0000:00:03.0 on NUMA socket 0
EAL:   probe driver: 8086:100e rte_em_pmd
EAL:   Not managed by a supported kernel driver, skipped
EAL: PCI device 0000:00:08.0 on NUMA socket 0
EAL:   probe driver: 8086:100e rte_em_pmd
EAL:   Not managed by a supported kernel driver, skipped
Scylla version 1.0.2-20160423.60307f6 starting ...
Scylla API server listening on 127.0.0.1:10000 ...


Still not able to connect. I think I am missing something fundamental but in that case perhaps the dpcs needs an update?

**Comment by avikivity** [comment]
Confirmed.

What is dpcs?

**Comment by dahankzter** [comment]
Sorry, that would be "docs". So there is something. I can test, just let me know when and what.

**Comment by avikivity** [comment]
Running

    docker run -p 0.0.0.0:9042:9042 -p 0.0.0.0:10000:10000  --rm  scylladb/scylla scylla --options-file /etc/scylla/scylla.yaml

Makes it utter

    INFO  2016-05-02 13:25:00,609 [shard 0] storage_service - Starting listening for CQL clients on localhost:9042...

But since it's listening on localhost, connections from outside don't get through.  We need to pre-edit the config to listen on the docker-assigned IP address.

@penberg, how did this ever work?

**Comment by avikivity** [comment]
btw, use `-v /path/to/some/xfs/directory:/var/lib/scylla`, with the directory set to a+rwx, to get any hint of performance, assuming we can connect.

**Comment by penberg** [comment]
@avikivity, it works by changing the Scylla configuration file to bind to the Docker IP address. See the ``hostname -i`` part of the Docker startup script:

https://github.com/scylladb/scylla/blob/master/dist/docker/redhat/start-scylla

**Comment by avikivity** [comment]
Well, now it doesn't.

**Comment by penberg** [comment]
Hmm.

So I see Scylla binding to 127.0.0.1 as well:

```
[penberg@nero ~]$ docker run -p 127.0.0.1:9042:9042 -i -t scylladb/scylla
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 1 on socket 0
EAL: Detected lcore 2 as core 2 on socket 0
EAL: Detected lcore 3 as core 3 on socket 0
EAL: Detected lcore 4 as core 0 on socket 0
EAL: Detected lcore 5 as core 1 on socket 0
EAL: Detected lcore 6 as core 2 on socket 0
EAL: Detected lcore 7 as core 3 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 8 lcore(s)
EAL: VFIO modules not all loaded, skip VFIO support...
EAL: Setting up physically contiguous memory...
EAL: TSC frequency is ~3707270 KHz
EAL: Master lcore 0 is ready (tid=43733680;cpuset=[0])
EAL: lcore 7 is ready (tid=33d3a700;cpuset=[7])
EAL: lcore 5 is ready (tid=34d3c700;cpuset=[5])
EAL: lcore 6 is ready (tid=3453b700;cpuset=[6])
EAL: lcore 1 is ready (tid=36d40700;cpuset=[1])
EAL: lcore 4 is ready (tid=3553d700;cpuset=[4])
EAL: lcore 3 is ready (tid=35d3e700;cpuset=[3])
EAL: lcore 2 is ready (tid=3653f700;cpuset=[2])
Scylla version 1.0.2-20160423.60307f6 starting ...
Scylla API server listening on 127.0.0.1:10000 ...
```

However, ``cassandra-stress`` from scylla-tools repository works fine:

```
[penberg@nero scylla-tools-java]$ ./tools/bin/cassandra-stress write
INFO  17:42:57 Found Netty's native epoll transport in the classpath, using it
INFO  17:42:57 Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
INFO  17:42:57 New Cassandra host localhost/127.0.0.1:9042 added
Connected to cluster: Test Cluster
Datatacenter: datacenter1; Host: localhost/127.0.0.1; Rack: rack1
Created keyspaces. Sleeping 1s for propagation.
Sleeping 2s...
Warming up WRITE with 50000 iterations...
Failed to connect over JMX; not collecting these stats
WARNING: uncertainty mode (err<) results in uneven workload between thread runs, so should be used for high level analysis only
Running with 4 threadCount
Running WRITE with 4 threads until stderr of mean < 0.02
Failed to connect over JMX; not collecting these stats
type,      total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
total,         10851,   10851,   10851,   10851,     0.4,     0.3,     0.7,     1.5,     4.1,     7.9,    1.0,  0.00000,      0,      0,       0,       0,       0,       0
```

**Comment by dahankzter** [comment]
I have in the meantime started using a Ubuntu machine and I can't seem to
get it to bind to anything but localhost. I haven't really checked deeper
but it seems like the listen_address is not biting. I can get the other
ports to use other interfaces.

Might not be related at all just thought I'd share it here.

**Comment by dahankzter** [comment]
`henrik@henrik-Ubuntu14:~$` sudo netstat -natlp|grep scyl
tcp        0      0 0.0.0.0:10000           0.0.0.0:*               LISTEN      2768/scylla     
tcp        0      0 127.0.0.1:9042          0.0.0.0:*               LISTEN      2768/scylla     
tcp        0      0 172.31.118.254:7000     0.0.0.0:*               LISTEN      2768/scylla     
tcp        0      0 127.0.1.1:10000         127.0.0.1:38584         ESTABLISHED 2768/scylla     
tcp        0      0 127.0.1.1:10000         127.0.0.1:38582         ESTABLISHED 2768/scylla
`

Conf:
listen_address: 172.31.118.254
- seeds: "172.31.118.254"

ps gives:
`scylla`    2768     1  4 08:20 ?        00:00:12 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix --developer-mode=1
scylla    2781     1  4 08:20 ?        00:00:13 java -Dcassandra.jmx.local.port=7199 -Xmx256m -XX:+UseSerialGC -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -jar `/usr/lib/scylla/jmx/scylla-jmx-1.0.jar`


Is there another file that I should use or is the /etc/scylla/scylla.yaml the one? I can't see it referenced anywhere on the commandline but that could of course mean nothing.

**Comment by dahankzter** [comment]
I get the same on Fedora. Only 7000 gets bound to the listen_address it seems.
I am at a loss now. I am probably making a mistake somewhere. I have only tweaked the listen_address.

Is there any other setting needed?

**Comment by dahankzter** [comment]
Actually when I set all possible ips to the interface I want to use it seems to work. Now I just have problems with my bridge in virtualbox. 

Sorry for the noise.

**Comment by avikivity** [comment]
It's not noise, I got the same issue and probably others did too. (plus, I much prefer a report on a non-issue to a non-report on an issue).

What do you mean by "I set all possible ips to the interface"?

**Comment by dahankzter** [comment]
In the scylla.yaml there are a number of possible places that accepts ip numbers such as listen_address and API/RPC endpoints. 

I did that just as a test and then netstat displays only my desired IP being used. listen_address alone does not seem to work as I initially understood it to work. I.e. controlling what IP cqlsh and nodetool connects to.

**Comment by dahankzter** [comment]
I just wanted to use a dedicated IP instead of localhost so that I could bridge it from virtualbox.

I do however think we need it on deploy right? Rarely the scylla process is co-deployed with an app right?
