### ISSUE TITLE
Track updated columns in memtable to use when writing SSTables 3.x

### ISSUE THREAD

**Issue by argenet** [scylladb/scylla#3901]
In Cassandra's memtable, all updates are tracked so that updated columns are known and the set of updated columns (which can be a subset of all columns in schema) is stored in serialization header.
Refer to https://github.com/scylladb/scylla/wiki/SSTables-3.0-Data-File-Format#row for more details.

Currently in Scylla we do not track filled columns and instead serialize all the columns from the schema used on flushing.

This may result in additional disk space being wasted for rows that don't have all columns from schema filled if they have all columns filled across all rows in the current table. In this case, Cassandra would set a `HAS_ALL_COLUMNS` flag, but Scylla needs to encode the missing columns indices.

Another potential source of disk space waste are tables that have no static rows but flushed with schema that contains static columns - see #3900 for details.

This issue can be seen as an enhancement.

**Comment by slivne** [comment]
Copying the discussion from the mailing list

from avikivity 
> I'm not sure the optimization is worthwhile. Yes, during some parts of the a workload we'll get slightly smaller sstables. But as soon as it gets compacted with older data, the optimization blows away. And it takes very specific conditions to see those temporary gains.

from pdziepak 
> I'm inclined to agree, so I guess the fix for #3901 is "wontfix".
