### ISSUE TITLE
docker scylla 2.3.1 develope-mode 0 fatal error

### ISSUE THREAD

**Issue by joyplux24** [scylladb/scylla#3903]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

scylla 2.3.1
docker
cpu 24thread, memory 64gb
ssd

docker run --name scylla -d scylladb/scylla:2.3.1 --developer-mode 0

/////////////////////////
// logs
/////////////////////////

running: (['/usr/lib/scylla/scylla_dev_mode_setup', '--developer-mode', '0'],)
running: (['/usr/lib/scylla/scylla_io_setup'],)
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
Reactor stalled for 2000 ms on shard 0.
Backtrace:
  0x00000000005ba592
  0x00000000004d9a9c
  0x00000000004d9f56
  /lib64/libpthread.so.0+0x000000000000f6cf
  /lib64/libc.so.6+0x00000000000f8ec8
  0x00000000006b289b
  0x00000000006b2312
  0x000000000042d075
  0x000000000042fa8a
  0x000000000041fb95
Reactor stalled for 4000 ms on shard 0.
Backtrace:
  0x00000000005ba592
  0x00000000004d9a9c
  0x00000000004d9f56
  /lib64/libpthread.so.0+0x000000000000f6cf
  /lib64/libc.so.6+0x00000000000f8ec8
  0x00000000006b289b
  0x00000000006b2312
  0x000000000042d075
  0x000000000042fa8a
  0x000000000041fb95
WARN  2018-11-07 04:55:15,185 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
INFO  2018-11-07 04:55:19,202 [shard 0] iotune - /var/lib/scylla/data passed sanity checks
WARN  2018-11-07 04:55:19,204 [shard 0] iotune - Scheduler for /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/scheduler set to deadline. It is recommend to set it to noop before evaluation so as not to skew the results.
WARN  2018-11-07 04:55:19,204 [shard 0] iotune - nomerges for /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/nomerges set to 0. It is recommend to set it to 2 before evaluation so that merges are disabled. Results can be skewed otherwise.
Measuring sequential write bandwidth: 158 MB/s
Measuring sequential read bandwidth: 328 MB/s
Measuring random write IOPS: 524 IOPS
Measuring random read IOPS: 1186 IOPS
Recommended --num-io-queues: 1
tuning /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/sdb3
tuning /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb
tuning: /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/nomerges to 2
2018-11-07 04:57:11,746 CRIT Supervisor running as root (no user in config file)
2018-11-07 04:57:11,746 WARN Included extra file "/etc/supervisord.conf.d/scylla-server.conf" during parsing
2018-11-07 04:57:11,746 WARN Included extra file "/etc/supervisord.conf.d/scylla-jmx.conf" during parsing
2018-11-07 04:57:11,746 WARN Included extra file "/etc/supervisord.conf.d/scylla-housekeeping.conf" during parsing
2018-11-07 04:57:11,779 INFO RPC interface 'supervisor' initialized
2018-11-07 04:57:11,780 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2018-11-07 04:57:11,780 INFO supervisord started with pid 59
2018-11-07 04:57:12,782 INFO spawned: 'scylla-jmx' with pid 62
2018-11-07 04:57:12,784 INFO spawned: 'scylla' with pid 63
2018-11-07 04:57:12,785 INFO spawned: 'scylla-housekeeping' with pid 64
tuning /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/sdb3
tuning /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb
tuning: /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/scheduler noop
warning: unable to tune /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/scheduler to noop
tuning: /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/nomerges to 2
tuning /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/sdb3
Connecting to http://localhost:10000
Starting the JMX server
Could not initialize seastar: std::out_of_range (_Map_base::at)
2018-11-07 04:57:13,272 INFO exited: scylla (exit status 1; not expected)
JMX is enabled to receive remote connections on port: 7199
2018-11-07 04:57:14,672 INFO success: scylla-jmx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2018-11-07 04:57:14,673 INFO spawned: 'scylla' with pid 91
2018-11-07 04:57:14,674 INFO success: scylla-housekeeping entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
tuning /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/sdb3
tuning /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb
tuning: /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/scheduler noop
warning: unable to tune /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/scheduler to noop
tuning: /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/nomerges to 2
tuning /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/sdb3
Could not initialize seastar: std::out_of_range (_Map_base::at)
2018-11-07 04:57:15,140 INFO exited: scylla (exit status 1; not expected)
2018-11-07 04:57:17,145 INFO spawned: 'scylla' with pid 94
tuning /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/sdb3
tuning /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb
tuning: /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/scheduler noop
warning: unable to tune /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/scheduler to noop
tuning: /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/nomerges to 2
tuning /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/sdb3
Could not initialize seastar: std::out_of_range (_Map_base::at)
2018-11-07 04:57:17,634 INFO exited: scylla (exit status 1; not expected)
Traceback (most recent call last):
  File "/usr/lib/scylla/scylla-housekeeping", line 174, in <module>
    args.func(args)
  File "/usr/lib/scylla/scylla-housekeeping", line 101, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
  File "/usr/lib/scylla/scylla-housekeeping", line 65, in get_api
    return get_json_from_url("http://" + api_address + path)
  File "/usr/lib/scylla/scylla-housekeeping", line 62, in get_json_from_url
    return json.loads(data)
  File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
2018-11-07 04:57:21,010 INFO spawned: 'scylla' with pid 105
tuning /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/sdb3
tuning /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb
tuning: /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/scheduler noop
warning: unable to tune /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/scheduler to noop
tuning: /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/queue/nomerges to 2
tuning /sys/devices/pci0000:00/0000:00:09.0/0000:04:00.0/host4/target4:1:1/4:1:1:0/block/sdb/sdb3
Could not initialize seastar: std::out_of_range (_Map_base::at)
2018-11-07 04:57:21,478 INFO exited: scylla (exit status 1; not expected)
2018-11-07 04:57:22,479 INFO gave up: scylla entered FATAL state, too many start retries too quickly

what is wrong?

**Comment by glommer** [comment]
You are hitting #3779. You should be able to edit the configuration files inside the container and then restart the scylla process by doing `sudo docker exec -it <ct_name> supervisorctl restart scylla-server`.

Please see the description of the issue for details, and sorry about that!

**Comment by joyplux24** [comment]
thanks~~! it's work now
