### ISSUE TITLE
Where will i get the password to be entered for starting scylla server for cloud user centos when deployed on AWS? 

### ISSUE THREAD

**Issue by awaradkar** [scylladb/scylla#3905]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by tzach** [comment]
`centos`

**Comment by tzach** [comment]
See here for doc https://www.scylladb.com/download/#aws
