### ISSUE TITLE
scylla-housekeeping-restart.service is misconfigured for Debian/Ubuntu

### ISSUE THREAD

**Issue by CogumelosMaravilha** [scylladb/scylla#3906]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 2.3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 9 /Ubuntu 18.04

Platform (physical/VM/cloud instance type/docker): EC2
After installing ScyllaDB 2.3 in Debian and Ubuntu, Scylla was not starting. After some debugging, I've found in scylla-housekeeping-restart.service:
ExecStart=/usr/lib/scylla/scylla-housekeeping --uuid-file /var/lib/scylla-housekeeping/housekeeping.uuid -q -c /etc/scylla.d/housekeeping.cfg --repo-files '/etc/yum.repos.d/scylla*.repo' version --mode r

I'm assuming the problem is the repos in RedHat configuration.
Thanks in advance.

**Comment by tzach** [comment]
@syuu1228 ?

**Comment by syuu1228** [comment]
@tzach sent fix "[PATCH scylla] dist/common/systemd/scylla-housekeeping-restart.service.mustache: specify correct repo for Debian variants"
