### ISSUE TITLE
Scylla_setup: still ask for nic in non-interactive mode

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#3908]
*Installation details*
Scylla version (or git commit hash): scylla-server-3.0.rc1-0.20181107.e57907a1d.el7.x86_64
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

* Description:
I already assigned nic (eth0) in scylla_setup cmdline, but it still asked for nic.

```
$ sudo scylla_setup --nic eth0 --no-raid-setup
INFO  2018-11-09 23:36:21,363 [shard 0] iotune - /var/tmp/mnt passed sanity checks
This is a supported kernel version.
Unable to retrieve version information
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: mirrors.usc.edu
 * epel: mirror.us.leaseweb.net
 * extras: repos.lax.quadranet.com
 * updates: mirror.fileplanet.com
Package ntp-4.2.6p5-28.el7.centos.x86_64 already installed and latest version
Package ntpdate-4.2.6p5-28.el7.centos.x86_64 already installed and latest version
Nothing to do
 9 Nov 23:36:30 ntpdate[10800]: adjust time server 169.254.169.254 offset -0.005077 sec
kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %p %u %g %s %t %e"
Please select a NIC from the following list:
['eth0', 'virbr0', 'virbr0-nic']
>
```

@syuu1228

**Comment by amoskong** [comment]
```diff --git a/dist/common/scripts/scylla_setup b/dist/common/scripts/scylla_setup
index b2a7a30365..996458c422 100755
--- a/dist/common/scripts/scylla_setup
+++ b/dist/common/scripts/scylla_setup
@@ -336,8 +336,8 @@ if __name__ == '__main__':
     if interactive:
         sysconfig_setup = interactive_ask_service('Do you want to setup a system-wide customized configuration for Scylla?', 'Yes - setup the sysconfig file. No - skips this step.', 'yes')
     if sysconfig_setup:
-        nic = interactive_choose_nic()
         if interactive:
+            nic = interactive_choose_nic()
             set_nic = interactive_ask_service('Do you want to enable Network Interface Card (NIC) optimization?', 'Yes - optimize the NIC queue settings. Selecting Yes greatly improves performance. No - skip this step.', 'yes')
     if sysconfig_setup:
         setup_args = '--setup-nic' if set_nic else ''
```

**Comment by slivne** [comment]
@amoskong please send a patch

**Comment by amoskong** [comment]
Just sent a patch to scylla-dev list:
- [PATCH scylla] scylla_setup: only ask for nic in interactive mode

**Comment by SiddhantSawant** [comment]
Non Interactive
faced it again on 3.2.1-0.20200122.e3e301906d5

scylla_setup --setup-nic-and-disks --nic=eth0 --no-ntp-setup --no-raid-setup --no-node-exporter
Please select a NIC from the following list:
['eth0'
....

below if condition needs
if interactive conditons

   if sysconfig_setup:
        set_nic_and_disks = interactive_ask_service('Do you want to enable Network Interface Card (NIC) and disk(s) optimization?', 'Yes - optimize the NIC queue and disks settings. Selecting Yes greatly improves performance. No - skip this step.', set_nic_and_disks)
        setup_args = '--setup-nic-and-disks' if set_nic_and_disks else ''
        nic = interactive_choose_nic()
and

    if ec2_check:
        nic = interactive_choose_nic()
    if ec2_check:
        run('{}/scylla_ec2_check --nic {}'.format(scriptsdir(), nic))
