### ISSUE TITLE
Add support for DEFAULT UNSET for INSERT JSON

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#3909]
INSERT JSON statement should accept an optional DEFAULT UNSET keyword, which would prevent overwriting unset values in the inserted JSON to null.

Ref:
https://stackoverflow.com/questions/53231917/scylla-db-json-support-for-insert-with-default-unset-directive-not-working

**Comment by avikivity** [comment]
apache/cassandra@12911352de32c948282779a70848211008409441, CASSANDRA-11424 (Cassandra 3.10)
