### ISSUE TITLE
I get the following issue when i try to run scylla on AWS."Only 476 MiB per shard; this is below the recommended minimum of 1 GiB/shard". I am using the free tier service of AWS. The instance memory is 10 GB.

### ISSUE THREAD

**Issue by awaradkar** [scylladb/scylla#3910]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by awaradkar** [comment]
Dear Shlomi,

I am using type t2.micro.

Thanks and Regards,
Aniruddha Waradkar

**Comment by slivne** [comment]
t2.micro have 1 GB of memory - Scylla will not be able to use the full 1GB as nothing will be left for the OS.

To run scylla on t2 you can enable developer mode https://docs.scylladb.com/getting-started/install_scylla/dev_mod/

**Comment by awaradkar** [comment]
Ok thank you.

**Comment by tzach** [comment]
> t2.micro have 1 GB of memory - Scylla will not be able to use the full 1GB as nothing will be left for the OS.
> 
> To run scylla on t2 you can enable developer mode https://docs.scylladb.com/getting-started/install_scylla/dev_mod/

We should include this info in the error code, making users life easier.
