### ISSUE TITLE
Mark MV and SI features as no longer "experimental"

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#3917]
I'm opening a new issue because I don't have permissions to reopen #1141 (over-strict github permissions system...), where @dorlaor already noticed this:

In service/storage_service.cc we still have
```
    if (config.experimental()) {
        features.push_back(MATERIALIZED_VIEWS_FEATURE);
        features.push_back(INDEXES_FEATURE);
    }
...
    if (_db.local().get_config().experimental()) {
        _materialized_views_feature = gms::feature(MATERIALIZED_VIEWS_FEATURE);
        _indexes_feature = gms::feature(INDEXES_FEATURE);
    }

```
since we decided to upgrade these features to complete, we need to drop the experimental() check and allow these features unconditionally.

BTW, does anyone remember why the unit tests worked with MV and SI, did we enable the experiment flag? We should stop enabling it to see that these tests pass without it. And similarly for dtests - we probably shouldn't pass the "experimental" flag to dtests which don't need it. 

CC @slivne @duarten

**Comment by slivne** [comment]
the change of dtests can be done after its changed in the code and removed from experimental
