### ISSUE TITLE
scylla db version 2.3 not running when enable experimental and showing control process exited while starting scylla db server

### ISSUE THREAD

**Issue by rsb007** [scylladb/scylla#3919]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by nyh** [comment]
Can you please include more information beyond what you put in the title? In particular, how do you run Scylla and what is the exact error you see and where?

**Comment by rsb007** [comment]
> Can you please include more information beyond what you put in the title? In particular, how do you run Scylla and what is the exact error you see and where?

hey nyh it shows me this error 
 service scylla-server start
Job for scylla-server.service failed because the control process exited with error code.
See "systemctl status scylla-server.service" and "journalctl -xe" for details.

**Comment by gleb-cloudius** [comment]
On Thu, Nov 15, 2018 at 05:07:45AM -0800, rsb007 wrote:
> See "systemctl status scylla-server.service" and "journalctl -xe" for details.
> 
Have you done it?

--
			Gleb.

**Comment by rsb007** [comment]
no

**Comment by gleb-cloudius** [comment]
On Thu, Nov 15, 2018 at 05:10:42AM -0800, rsb007 wrote:
> no
> 
Can you? And post output here.

--
			Gleb.

**Comment by rsb007** [comment]
it shows me this error
$ service scylla-server start
Job for scylla-server.service failed because the control process exited with error code.
See "systemctl status scylla-server.service" and "journalctl -xe" for details.

**Comment by gleb-cloudius** [comment]
Run "systemctl status scylla-server.service" and post its output here.

--
			Gleb.

**Comment by rsb007** [comment]
$ systemctl status scylla-server.service
● scylla-server.service - Scylla Server
   Loaded: loaded (/lib/systemd/system/scylla-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2018-11-15 17:14:39 IST; 17h ago
  Process: 11814 ExecStopPost=/usr/lib/scylla/scylla_stop (code=exited, status=0/SUCCESS)
  Process: 8645 ExecStart=/usr/bin/scylla $SCYLLA_ARGS $SEASTAR_IO $DEV_MODE $CPUSET (code=exited, status=0/SUCCESS)
  Process: 11796 ExecStartPre=/usr/lib/scylla/scylla_prepare (code=exited, status=1/FAILURE)
 Main PID: 8645 (code=exited, status=0/SUCCESS)

Nov 15 17:14:38 rahul scylla_prepare[11796]:   File "/usr/lib/scylla/scylla_prepare", line 71, in <module>
Nov 15 17:14:38 rahul scylla_prepare[11796]:     run('/usr/lib/scylla/scylla-blocktune')
Nov 15 17:14:38 rahul scylla_prepare[11796]:   File "/usr/lib/scylla/scylla_util.py", line 263, in run
Nov 15 17:14:38 rahul scylla_prepare[11796]:     return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr)
Nov 15 17:14:38 rahul scylla_prepare[11796]:   File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
Nov 15 17:14:38 rahul scylla_prepare[11796]:     raise CalledProcessError(retcode, cmd)
Nov 15 17:14:38 rahul scylla_prepare[11796]: subprocess.CalledProcessError: Command '['/usr/lib/scylla/scylla-blocktune']' returned non-zero exit status 1.
Nov 15 17:14:38 rahul systemd[1]: scylla-server.service: Control process exited, code=exited status=1
Nov 15 17:14:39 rahul systemd[1]: scylla-server.service: Failed with result 'exit-code'.
Nov 15 17:14:39 rahul systemd[1]: Failed to start Scylla Server.

**Comment by glommer** [comment]
This means that scylla-blocktune found and error and couldn't tune the disks.
This usually happens if you don't have permissions to write to /var/lib/scylla/data (or commitlog), and/or one of those directories don't exist.

**Comment by rsb007** [comment]
> Run "systemctl status scylla-server.service" and post its output here.
> […](#)
> -- Gleb.
$ systemctl status scylla-server.service
● scylla-server.service - Scylla Server
Loaded: loaded (/lib/systemd/system/scylla-server.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Thu 2018-11-15 17:14:39 IST; 17h ago
Process: 11814 ExecStopPost=/usr/lib/scylla/scylla_stop (code=exited, status=0/SUCCESS)
Process: 8645 ExecStart=/usr/bin/scylla $SCYLLA_ARGS $SEASTAR_IO $DEV_MODE $CPUSET (code=exited, status=0/SUCCESS)
Process: 11796 ExecStartPre=/usr/lib/scylla/scylla_prepare (code=exited, status=1/FAILURE)
Main PID: 8645 (code=exited, status=0/SUCCESS)

Nov 15 17:14:38 rahul scylla_prepare[11796]: File "/usr/lib/scylla/scylla_prepare", line 71, in 
Nov 15 17:14:38 rahul scylla_prepare[11796]: run('/usr/lib/scylla/scylla-blocktune')
Nov 15 17:14:38 rahul scylla_prepare[11796]: File "/usr/lib/scylla/scylla_util.py", line 263, in run
Nov 15 17:14:38 rahul scylla_prepare[11796]: return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr)
Nov 15 17:14:38 rahul scylla_prepare[11796]: File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
Nov 15 17:14:38 rahul scylla_prepare[11796]: raise CalledProcessError(retcode, cmd)
Nov 15 17:14:38 rahul scylla_prepare[11796]: subprocess.CalledProcessError: Command '['/usr/lib/scylla/scylla-blocktune']' returned non-zero exit status 1.
Nov 15 17:14:38 rahul systemd[1]: scylla-server.service: Control process exited, code=exited status=1
Nov 15 17:14:39 rahul systemd[1]: scylla-server.service: Failed with result 'exit-code'.
Nov 15 17:14:39 rahul systemd[1]: Failed to start Scylla Server.

**Comment by gleb-cloudius** [comment]
Have you seen @glommer's comment above: https://github.com/scylladb/scylla/issues/3919#issuecomment-439386172

**Comment by nyh** [comment]
@gleb-cloudius @glommer even if this (unwritable directory) is the problem, we should change the code to say that - and not just "returned non-zero exit status". Users are not mind-readers, especially not of software (which doesn't really have a mind). It would be nice to avoid showing all that Python crap in the error message too :-)

**Comment by gleb-cloudius** [comment]
On Tue, Nov 20, 2018 at 04:20:26AM -0800, nyh wrote:
> @gleb-cloudius @glommer even if this (unwritable directory) is the problem, we should change the code to say that - and not just "returned non-zero exit status". Users are not mind-readers, especially not of software (which doesn't really have a mind). It would be nice to avoid showing all that Python crap in the error message too :-)
> 
Non-zero exit status message is from systemd. Not sure if there is an
api to pass more meaningful info for it to print during failure. I agree
that out python scrips should handle their error and print clear errors
to be seen in the logs though.

--
			Gleb.

**Comment by syuu1228** [comment]
@rsb007 Could you post a result of following command? "journalctl -xe|grep scylla_prepare"
I guess there are more error message ahead of the log you posted.
