### ISSUE TITLE
flaky (?) view_build_test

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#3920]
In the Jenkins promotion tests, we had a failure in view_build_test: http://jenkins.cloudius-systems.com:8080/job/scylla-master/job/next/100/execution/node/59/log/?consoleFull
Some snippets from this log:
```
16:37:44 unknown location(0): fatal error: in "test_builder_with_large_partition": seastar::timed_out_error: timedout
16:37:44 seastar/tests/test-utils.cc(40): last checkpoint
...
16:37:44 The following test(s) have failed:
16:37:44   build/debug/tests/view_build_test --report_level=no --logger=HRF,test_suite:XML,test_suite,jenkins_test.debug.view_build_test.boost.xml -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --blocked-reactor-notify-ms 2000000 --collectd 0
```
Note that it was the debug test which failed, which is even slower than usual, so it's even more likely that this is just a "timeout is too low" scenario.
CC: @duarten

**Comment by duarten** [comment]
I saw it and I plan to remove the timeout in `wait_until_built`.

**Comment by nyh** [comment]
I just sent a patch increasing the timeout, and suggesting in the future to remove the timeout altogether. I suggest we commit my patch to increase the timeout and get the tests to succeed and the "next" backlog to be finally promoted, and later you can send another patch to remove it completely if you want.
