### ISSUE TITLE
nodetool: Unable to connect to Scylla API server: java.net.UnknownHostException: null

### ISSUE THREAD

**Issue by mukeshmodiindia** [scylladb/scylla#3921]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 2.3.1-0.20181022.336c77166
Cluster size: Did basic setup and installation, couldn't check the size
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu
mukesh@mukesh-VirtualBox:/etc/scylla/cassandra$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): VM
Hardware: sockets= cores= hyperthreading= memory= cores -1, memory- 11GB
Disks: (SSD/HDD, count)- HDD

Error Log-

mukesh@mukesh-VirtualBox:/etc/scylla/cassandra$ nodetool status
07:40:57,355 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback-tools.xml] at [file:/tmp/tmp.ijo7rvUl9i/logback-tools.xml]
07:40:57,356 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-tools.xml] occurs multiple times on the classpath.
07:40:57,356 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-tools.xml] occurs at [file:/tmp/tmp.ijo7rvUl9i/logback-tools.xml]
07:40:57,356 |-WARN in ch.qos.logback.classic.LoggerContext[default] - Resource [logback-tools.xml] occurs at [file:/etc/scylla/cassandra/logback-tools.xml]
07:40:57,564 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
07:40:57,566 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
07:40:57,578 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [STDERR]
07:40:57,698 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
07:40:57,856 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to WARN
07:40:57,857 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [STDERR] to Logger[ROOT]
07:40:57,857 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
07:40:57,861 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@1ea9f6af - Registering current configuration as safe fallback point

WARN  02:10:58 Only 42494 MB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
nodetool: Unable to connect to Scylla API server: java.net.UnknownHostException: null
See 'nodetool help' or 'nodetool help <command>'.

Let me know what details you required.

**Comment by mukeshmodiindia** [comment]
Well, I haven't run scylla-jmx manually. I just started the scylla with the below command.

sudo systemctl start scylla-server

Please find the scylla-jmx process running here.

mukesh@mukesh-VirtualBox:~$ ps -eaf | grep scylla
scylla     613     1  0 06:43 ?        00:00:00 /usr/bin/node_exporter -collectors.enabled interrupts,conntrack,diskstats,entropy,filefd,filesystem,loadavg,mdadm,meminfo,netdev,netstat,sockstat,stat,textfile,time,uname,vmstat
scylla    4476     1  4 07:08 ?        00:17:48 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --num-io-queues=1 --io-properties-file=/etc/scylla.d/io_properties.yaml
scylla    4489     1  0 07:08 ?        00:00:29 /usr/lib/scylla/jmx/symlinks/scylla-jmx -Xmx256m -XX:+UseSerialGC -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.host=localhost -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7199 -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=7199 -Djavax.management.builder.initial=com.scylladb.jmx.utils.APIBuilder -jar /usr/lib/scylla/jmx/scylla-jmx-1.0.jar
mukesh   23183  2862  0 13:43 pts/0    00:00:00 grep --color=auto scylla
mukesh@mukesh-VirtualBox:~$ 

Cheers,
Mukesh Kumar

**Comment by mukeshmodiindia** [comment]
I don't know why it's strike in output of scylla process, but it's the process running currently.

**Comment by mukeshmodiindia** [comment]
mukesh@mukesh-VirtualBox:~$ date
Sun Nov 18 17:01:46 IST 2018
mukesh@mukesh-VirtualBox:~$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment (build 11.0.1+13-Ubuntu-2ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.1+13-Ubuntu-2ubuntu1, mixed mode, sharing)
mukesh@mukesh-VirtualBox:~$ date
Sun Nov 18 17:01:51 IST 2018
mukesh@mukesh-VirtualBox:~$

**Comment by amnonh** [comment]
I have tried to reproduce the problem, I run it on GCE with nothing similar.

Can you try getting the logs for the scylla-jmx:

journalctl -u scylla-jmx.service

I'm particularly looking for the first 50 lines or so that describes how the jmx connect to scylla

**Comment by amnonh** [comment]
It seems that there is something wrong with the ip address, can you check in 
 /etc/scylla/scylla.yaml

for the api_address
it should be 127.0.0.1

**Comment by mukeshmodiindia** [comment]
Oops, it was empty. I emptied all the ip_address, like listen_address, rpc_address.

# IP for the REST API server
api_address:

**Comment by amnonh** [comment]
Please set it to 127.0.0.1 and restart scylla service 

sudo systemctl restart scylla-server

**Comment by mukeshmodiindia** [comment]
Yes, already restarted, it's working fine. Thank you.

mukesh@mukesh-VirtualBox:~$ nodetool status
WARN  12:38:19 Only 41199 MB free across all data volumes. Consider adding more capacity to your cluster or removing obsolete snapshots
Datacenter: my_data_center
==========================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns    Host ID                               Rack
UN  127.0.0.1  225.69 KB  256          ?       4dee9c60-4f04-4465-878c-5870915d9ea3  my_rack

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
mukesh@mukesh-VirtualBox:~$ cqlsh
Connected to blogfordba at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> desc KEYSPACES ;

system_traces  system_schema  system_auth  system  system_distributed

cqlsh>

**Comment by mukeshmodiindia** [comment]
Closing the Issue, appreciate your quick help.
