### ISSUE TITLE
SStable compression changed to be disabled by default

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#3926]
Reported by @tgrabiec on the mailing list:

Somewhere between 2.0.3 and 2.2.0 Scylla started to create uncompressed sstables when no compression options are set on a table.
Was that intentional?
I think the docs suggest that it is enabled by default:
https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlCreateTable.html#tabProp__moreCompression

My own (@nyh) addition: we should also have a unit test verifying this default is what we think it is, and doesn't change unintentionally in future releases.

**Comment by nyh** [comment]
@duarten on the mailing list: I think we should be default-compatible with Cassandra. Pros: least surprise, less cognitive overload, compression is good and lz4 is cheap, users that test for such things won't see any difference in sstable size for the same inputs to Cassandra and Scylla and open issues. Cons: slightly slower sstable writing.

**Comment by bhalevy** [comment]
@tzach fyi, this has product ramifications...

**Comment by tzach** [comment]
> Somewhere between 2.0.3 and 2.2.0 Scylla started to create uncompressed sstables when no compression options are set on a table.

Do you know have the relevant commit? 

> @duarten on the mailing list: I think we should be default-compatible with Cassandra. Pros: least surprise, less cognitive overload, compression is good and lz4 is cheap, users that test for such things won't see any difference in sstable size for the same inputs to Cassandra and Scylla and open issues. Cons: slightly slower sstable writing.

Agree.

**Comment by duarten** [comment]
It was mea culpa: e33c02aa6047f8c7d5e3daf46366bf243578d690.

Fixing.

**Comment by duarten** [comment]
Oh, maybe it was 74758c87cd4747c75a268a76c0a30b5bc03f0bcd.
