### ISSUE TITLE
change node exporter version to 0.16/7

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#3927]
We should upgrade the node_exporter version, this is not backward compatible and will need to be reflected in changes to the dashboards.

**Comment by slivne** [comment]
is there a way to support both versions  ? / have some "trick" on the prometheus/grafana todo renames ...
(https://medium.com/quiq-blog/prometheus-relabeling-tricks-6ae62c56cbda)

**Comment by amnonh** [comment]
There is with the price of readability.

we can create an expression that is a combination of both metric version, assuming only one would be available.

It would work,but it would look ugly

**Comment by tzach** [comment]
@slivne I think this is an overkill.
Once we start shipping Scylla with node_exporter 0.17, we will ship the matching dashboards from Scylla monitoring Stack.

**Comment by slivne** [comment]
@tzach ping ...

**Comment by slivne** [comment]
@amnonh please update the issue as we have fixed this and close

**Comment by amnonh** [comment]
We didn't yet, i only solved the grafana issue, u still need to test a
scylla test to actually upgrade the node exporter

**Comment by tzach** [comment]
@avikivity can we backport to 3.0
node_exporter 0.14 won't work on latest i3.metal
