### ISSUE TITLE
nodetool status is slow

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#393]
```
$ time nodetool -p 7199 status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address        Load       Tokens  Owns    Host ID                               Rack
UN  172.31.19.251  24825      256     ?       42f39ab0-708c-4782-9a48-9267db779d9d  rack1
UN  172.31.19.250  ?          256     ?       c66606a9-33b3-4dea-a368-e45148836ae8  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless

real	0m28.320s
user	0m2.612s
sys	0m0.206s
```

**Comment by slivne** [comment]
@tzach - can you check if this is still an issue

**Comment by slivne** [comment]
on 0.18

shlomi@localhost~/scylla (master)$ time ccm node1 nodetool status

Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens  Owns    Host ID                               Rack
UN  127.0.0.1  79.48 KB   256     ?       2dd51c8e-b2b8-4a04-ba7e-2d48322fa4a9  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless


real	0m1.076s
user	0m1.630s
sys	0m0.080s
