### ISSUE TITLE
Disable repair on views

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#3935]
Repair should not be allowed to run between views - only between base tables / base-view pairs.

**Comment by asias** [comment]
It is not clear to me what is allowed and what is not allowed. Can you elaborate?

**Comment by slivne** [comment]
- repair should run only on regular tables (CREATE TABLE)
- repair should not be run on views (CREATE VIEW) - the user should get
back an error.

**Comment by asias** [comment]
Do we need this for 3.0?

**Comment by asias** [comment]
@nyh Do you know if there is a way to tell if a table is view table?

**Comment by asias** [comment]
@psarna ^^^

**Comment by asias** [comment]
Thanks.

- If user specifies a table to repair and the table is a view table, we will return an error.  However, we do not have a way to return the reason why the repair failed with the restful API. 

- If user does not specify a table to repair, we will run the repair and only repair the normal table, and return 'succesfull'

**Comment by asias** [comment]
Patch on list: [PATCH scylla] repair: Do not allow to repair view table

@psarna could you please give it a try?

**Comment by asias** [comment]
Good, we will get the error from the resultful api and propagates to nodetool.
```
$ nodetool repair amos standard1
error: Scylla API server HTTP POST to URL '/storage_service/repair_async/amos' failed: It is not allowed to repair a view table, keyspace=amos, table=standard1
```

**Comment by asias** [comment]
v2 on list:

[PATCH scylla v2] repair: Do not allow to repair view table

**Comment by nyh** [comment]
If we consider disabling repair or read repair (see issue #3933) on views, there is something very important we need to keep in mind: We will also need to disable tombstone GCing for view tables!

The danger is as follows: Consider that a base-table update led to the deletion of a view row. The view update reached two view replicas, but not the third (perhaps base replicas rebooted, or a view replica was down for a long time and the hints file overflowed). So now two view replicas have a new tombstone, one older data. If neither repair no read-repair is done on this view row before the tombstones get GCed (after gc_grace_seconds), the deleted view row gets resurrected.

So I'm starting to think that if we don't change our tombstone GC policy, suggesting that we shouldn't repair view tables was wrong. We should repair view tables, just like base tables, more often than once every gc_grace_seconds, for the same reason we always need to do that - to prevent resurrection of deleted data.

**Comment by gleb-cloudius** [comment]
On Wed, Jan 29, 2020 at 12:23:41AM -0800, nyh wrote:
> If we consider disabling repair or read repair (see issue #3933) on views, there is something very important we need to keep in mind: We will also need to disable tombstone GCing for view tables!
> 
IIRC we already disabled repairs on views. Not read repairs though
because I strongly disagreed, but read repair is not substitution for
proper repair.

--
			Gleb.

**Comment by nyh** [comment]
@gleb-cloudius the fact that this issue is still open is supposed to mean that we never went ahead and disabled repair on views. I see above a patch from @denesb for doing this, but it appears it was never committed. I don't remember why.

**Comment by gleb-cloudius** [comment]
On Wed, Jan 29, 2020 at 01:06:33AM -0800, nyh wrote:
> @gleb-cloudius the fact that this issue is still open is supposed to mean that we never went ahead and disabled repair on views. I see above a patch from @denesb for doing this, but it appears it was never committed. I don't remember why.
> 
Hmm, the patch was from Asias, but it was pushed to @denesb branch. I
mistakenly thought it was pushed to master.

--
			Gleb.

**Comment by asias** [comment]
> f we consider disabling repair or read repair (see issue #3933) on views, there is something very important we need to keep in mind: We will also need to disable tombstone GCing for view tables!
> 
> The danger is as follows: Consider that a base-table update led to the deletion of a view row. The view update reached two view replicas, but not the third (perhaps base replicas rebooted, or a view replica was down for a long time and the hints file overflowed). So now two view replicas have a new tombstone, one older data. If neither repair no read-repair is done on this view row before the tombstones get GCed (after gc_grace_seconds), the deleted view row gets resurrected.
> 
> So I'm starting to think that if we don't change our tombstone GC policy, suggesting that we shouldn't repair view tables was wrong. We should repair view tables, just like base tables, more often than once every gc_grace_seconds, for the same reason we always need to do that - to prevent resurrection of deleted data.

To be clear: we currently do not disable repair on the view tables at all. View table can be repaired just as the normal table. 

I am closing this issue to avoid confusing.
