### ISSUE TITLE
tests: sstables_3_x test appears to rely on unordered_map iteration order

### ISSUE THREAD

**Issue by mundaym** [scylladb/scylla#3937]
I am seeing failures (on IBM Z) that result from mismatches between the generated Statistics files and golden data. After digging into this a bit I think that the mismatch comes from the `disk_hash` written out at the start of the Statistics file. The `disk_hash` wraps an `unordered_map` which is written to the file using this code:

https://github.com/scylladb/scylla/blob/dcd18e2b62036deec607ca52f3e58db0bdae8b66/sstables/sstables.cc#L552

https://github.com/scylladb/scylla/blob/dcd18e2b62036deec607ca52f3e58db0bdae8b66/sstables/sstables.cc#L540-L545

As far as I can tell we should either replace the golden data check or order the map. Any thoughts?

**Comment by tgrabiec** [comment]
Cassandra writes the statistics sorted by metadata type (org.apache.cassandra.io.sstable.metadata.MetadataSerializer#serialize), so should we.

Note that since 8f686af9aff33fa68ce066d97021addc0e1a57e3 that test should ignore the statistics.

**Comment by mundaym** [comment]
> Note that since 8f686af that test should ignore the statistics.

Yes, that commit stops these tests failing, thanks. I have a patch that sorts the data when an `unordered_map` is written out. Not sure if it's exactly what you want to do here but I'll send it anyway and you can see what you think.

**Comment by mundaym** [comment]
@tgrabiec I've sent the patch: https://groups.google.com/forum/#!topic/scylladb-dev/QyYsdrUHvMk

**Comment by tgrabiec** [comment]
Fixed by 8f686af
