### ISSUE TITLE
Installing both scylla-server and scylla-env package breaks entire distribution

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#3943]
On Scylla 3rdparty tools, we add /opt/scylladb/lib to LD_LIBRARY_PATH.
We use same directory for relocatable binaries, including libc.so.6.
Once we install both scylla-env package and relocatable version of scylla-server package, the loader tries to load libc from /opt/scylladb/lib then entire distribution become unusable like this:
```
$ ls
ls: relocation error: /opt/scylladb/lib/libc.so.6: symbol _dl_starting_up version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
$ systemctl
systemctl: /opt/scylladb/lib/libc.so.6: version `GLIBC_2.27' not found (required by /lib/systemd/libsystemd-shared-237.so)
$ bash
bash: relocation error: /opt/scylladb/lib/libc.so.6: symbol _dl_starting_up version GLIBC_PRIVATE not defined in file ld-linux-x86-64.so.2 with link time reference
```

It might be very dangerous, I think it's better to use different directory for relocatable binaries.
(In fact I just break my local build environment!)

**Comment by syuu1228** [comment]
Note that this might be affect user environment when user tries to install scylla-gdb, not just developer environment.

**Comment by syuu1228** [comment]
@avikivity Can we move relocatable binaries (libraries) to /opt/scylladb/lib/scylla/ or somewhere else to avoid this issue?

**Comment by syuu1228** [comment]
@avikivity ping

**Comment by avikivity** [comment]
Ok, better to be safe, but need to add symlinks to /opt/scylladb/bin

**Comment by avikivity** [comment]
Alternatively, add Requires: scylla-env > ..., or even Obsoletes: scylla-env.

**Comment by syuu1228** [comment]
@avikivity About "Requires: scylla-env > ...", I think we can't solve issue with it, since we cannot drop /etc/ld.so.conf.d/scylla.x86_64.conf from scylla-env, unless we remove all libraries from scylla-3rdparty repo.
But /opt/scylladb/lib is only user for Scylla build dependencies, so if we can create another repo just for scylla-gdb we may able to drop /etc/ld.so.conf.d/scylla.x86_64.conf.

Also, "Obsoletes: scylla-env" is not possible since we are not able to install 3rdparty packages and Scylla together.
