### ISSUE TITLE
SStable generated during cassandra-stress have extra characters in cell name according to sstable2json

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#395]
I've noticed that sstables generated during cassandra-stress run have larger footprint per partition on Scylla than Cassandra 2.1.9, 296 bytes vs 281 bytes.

sstable2json (I tried running both the one from 2.1.9 and 2.1.8) revealed this:

Cassandra 2.1.9:

```
{"key": "324b4c34374e4f4f4c30",
 "cells": [["C0","5de358252de0cf33ab32c9bf77b73ec443d4e9175a8c5d2311ee5c77292df854ab57",1442994237819210],
```
   
Scylla:

```
{"key": "3336324f384b37343431",
 "cells": [["\u0000\u0002C0\u0000","1107dfbe0d342165cfce22cd0b1588522e888f4c94be650bf763ecc728ec43e5a09c",1442994694868031],
```

As you can see, we generate some extra characters in column names.

**Comment by nyh** [comment]
These "extra characters" look like a composite column name. In CQL, these are the default, even if there are no clustering keys (see https://github.com/scylladb/scylla/wiki/SSTables-interpretation-in-Urchin). So Scylla's composite column names look *correct* unless you specified "WITH COMPACT STORAGE" in the CQL command to create this table.

However, I'm not sure how you ran Cassandra-stress - if you ran it with Thrift, not CQL, it is possible it does not use composite keys at all, and this explains why Cassandra generate the non-composite column names like in your dup. Scylla needs to also create non-composite keys in Thrift mode, but we don't currently support Thrift anyway.

**Comment by tgrabiec** [comment]
This is indeed the case, the schema in Cassandra sstables has compact storage, while the one in Scylla does not. I didn't change c-s command line though, just switched from the stock c-s to the one provided by scylla-tools. Closing as not an issue.
