### ISSUE TITLE
Indexed query may not contain multiple restrictions

### ISSUE THREAD

**Issue by danicar12** [scylladb/scylla#3957]
Looks like in version 2.3.1 still we are not able to use an indexed query with multiple restrictions. When is going to be fixed?

**Comment by duarten** [comment]
In 3.0.

**Comment by danicar12** [comment]
Is there any planned date for 3.0?

Thanks,
Daniel

On 3 Dec 2018, at 15:06, Duarte Nunes <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #3957<https://github.com/scylladb/scylla/issues/3957>.

**Comment by duarten** [comment]
There's no specific date, but very likely to be before xmas :)

**Comment by danicar12** [comment]
Thanks!!
Daniel

On 3 Dec 2018, at 16:18, Duarte Nunes <notifications@github.com<mailto:notifications@github.com>> wrote:

There's no specific date, but very likely to be before xmas :)
