### ISSUE TITLE
TLS?

### ISSUE THREAD

**Issue by kjniemi** [scylladb/scylla#396]
Scylla status page mentions that there is currently no support for transport encryption. Are there plans to implement TLS between client-node and/or node-node (both within rack and inter-dc topologies)?

**Comment by asias** [comment]
Yes, of course. Security matters ;-)

**Comment by avikivity** [comment]
@penberg

**Comment by slivne** [comment]
We are adding support for it  please track  #415 , #414 

closing as its a duplicate for those
