### ISSUE TITLE
Row cache: readers with `streamed_mutation::forwarding::yes` may miss data

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#3963]
It appears that the mutation readers for cache do not handle `streamed_mutation::forwarding::yes` properly. The test case below shows cache reader missing the second partition entirely after properly reading the first one.

This is a relatively minor issue since such request are not created outside of the tests but if intra-partition forwarding is supported it must return correct data. 

```c++
SEASTAR_THREAD_TEST_CASE(oops) {
    const sstring value = "v";

    simple_schema s;
    auto dkeys = s.make_pkeys(2);
    std::vector<mutation> mutations;

    {
        auto m = mutation(s.schema(), dkeys.at(0));
        for (auto ckey = 0u; ckey < 2; ckey++) {
            s.add_row(m, s.make_ckey(ckey), value);
        }
        mutations.emplace_back(std::move(m));
    }
    {
        auto m = mutation(s.schema(), dkeys.at(1));
        for (auto ckey = 0u; ckey < 2; ckey++) {
            s.add_row(m, s.make_ckey(ckey), value);
        }
        mutations.emplace_back(std::move(m));
    }

    cache_tracker tracker;
    auto mt = make_lw_shared<memtable>(s.schema());
    for (auto&& m : mutations) {
        mt->apply(m);
    }

    auto cache = make_lw_shared<row_cache>(s.schema(), snapshot_source_from_snapshot(mt->as_data_source()), tracker);

    auto ck = s.make_ckey(0);
    auto mr = cache->make_reader(s.schema(), query::full_partition_range, s.schema()->full_slice(), default_priority_class(), nullptr, streamed_mutation::forwarding::yes, mutation_reader::forwarding::yes);
    assert_that(std::move(mr))
        .produces_partition_start(mutations[0].decorated_key())
        .produces_end_of_stream()
        .fast_forward_to(position_range(
            position_in_partition(position_in_partition::clustering_row_tag_t(), ck),
            position_in_partition(position_in_partition::after_clustering_row_tag_t(), ck)))
        .produces_row_with_key(ck)
        .next_partition()
        .produces_partition_start(mutations[1].decorated_key())
        .fast_forward_to(position_range(
            position_in_partition(position_in_partition::clustering_row_tag_t(), ck),
            position_in_partition(position_in_partition::after_clustering_row_tag_t(), ck)))
        .produces_row_with_key(ck)
        .produces_end_of_stream();
}
```

```
$ build/release/tests/row_cache_test_g -l message --run_test=oops 
tests::random seed = 4108759601
Running 1 test case...
Expecting partition start with key {key: pk{000406000000}, token:-5566252076597558760}
Expecting end of stream
Fast forward to clustering range: {{position: clustered,ckp{000c636b30303030303030303030},0}, {position: clustered,ckp{000c636b30303030303030303030},1}}
Expect ckp{000c636b30303030303030303030}
Skip to next partition
Expecting partition start with key {key: pk{000400000000}, token:-3485513579396041028}
./tests/flat_mutation_reader_assertions.hh(50): fatal error: in "oops": Expected: partition start with key {key: pk{000400000000}, token:-3485513579396041028}, got end of stream

*** 1 failure is detected in the test module "tests/row_cache_test.cc"

```

**Comment by pdziepak** [comment]
Since the performance of `streamed_mutation::forwarding::yes` mode is in no way critical it's probably best to drop native support for it from the row cache readers and use `make_forwardable` adaptor instead. No need to make cache code more complex than it needs to be.

**Comment by denesb** [comment]
Is there any user of `streamed_mutation::forwarding::yes` apart from the row-cache itself?
\cc @tgrabiec 

If now, perhaps we should just drop it from the `flat_mutation_reader` interface, and introduce a new interface `skipping_mutation_reader`, that only the `sstable` readers would implement, for the row-cache's sake.
`sm:fwd` causes constant confusion, pain, bugs, tears, destruction, sickness, etc.

**Comment by tgrabiec** [comment]
@denesb Cache is creating sstable readers with `streamed_mutation::forwarding::yes`. This issue is about the cache reader itself, and no one uses it with `streamed_mutation::forwarding::yes` apart from tests.

**Comment by pdziepak** [comment]
It may be indeed beneficial to have `mutation_reader` and `fast_forwardable_mutation_reader` so that we can move the problem whether such mode is supported to the type system, but while it may indeed make the design cleaner (not sure about implementation, though, intermediate readers will now have to accept both types) it won't bring us huge benefits, since the readers that don't care about `sm::fwd` can just use `make_forwardable()` adaptor – the problem here was precisely that the cache didn't care about fast forwarding but attempted to implement it.

**Comment by denesb** [comment]
So @tgrabiec do you see any obstacle for (or do you have any arguments against) doing the split I proposed? A complication is the combined reader, which the cache is also using to merge the output of all the sstable readers.
I don't propose to do it as part of this issue, *if* we agree it is something worth looking into I'll open a new one for it.

I spent countless hours implementing `sm::fwd` in new readers, and even more hours debugging and fixing bugs related to it, because I thought it must be widely used if it is part of the mutation reader interface.

**Comment by denesb** [comment]
On Thu, 2018-12-06 at 07:16 -0800, Paweł Dziepak wrote:
> It may be indeed beneficial to have mutation_reader and
> fast_forwardable_mutation_reader so that we can move the problem
> whether such mode is supported to the type system, but while it may
> indeed make the design cleaner (not sure about implementation,
> though, intermediate readers will now have to accept both types) it 

There aren't that many intermediate readers.
The row cache, according to my admittedly quite limited knowledge,
directly uses sstable readers, combined with the combined reader.

**Comment by tgrabiec** [comment]
In the long term we want to switch to the skip semantics (https://github.com/scylladb/scylla/issues/2913), in which case we will have a default implementation in the base class.

Splitting the types would make things a bit safer, at the expense of having to templatize intermediate readers. There's not only the combined reader, but also transformers like schema upgrader. There is simplicity in having all readers conform to one interface. In cases when we don't need the reader to be natively forwardable, we can use the `make_forwardable()` adaptor. So I'm not in favor of the split.

**Comment by denesb** [comment]
Ok, makes sense. Let's wait and see, how this skip interface will look.
