### ISSUE TITLE
Write hints for view updates on shutdown

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#3966]
View updates are propagated with a high timeout (minutes-scale). This is by design, since we gain nothing  by aggressively timing out these internal writes, leading to wasted work on both the base and view replicas. However, we wait for view updates on shutdown to minimize inconsistencies, which can cause us to wait for minutes.

We can have a shorter shutdown time by writing the pending view updates as hints. If we have no space to write more hints, then we can wait for a period of time lower than the write timeout (lets say, 1 minute) for the view updates to drain, and in case that doesn't happen, we can discard the view updates.

**Comment by slivne** [comment]
@duarten 

> However, we wait for view updates on shutdown to minimize inconsistencies, which can cause us to wait for minutes.

Is this something that is happening on 3.0 ? 

Is there any cap on how long do we wait ? (maximum 10 minutes ?)

What will happen if we are not able to "complete" all view updates - remote node is overloaded  / not available - will we shutdown the node ?

I want to understand if we MUST have this resolved in 3.0 release or can push it out to 3.1

**Comment by duarten** [comment]
Right now, view updates have the same timeout as normal user writes (two seconds by default). With my patches, that will grow to 5min. If the write times out, then we will write the view updates as hints.

I think we can push this to 3.1. It will just mean some shutdowns can take up to 5min.

**Comment by duarten** [comment]
This together with #3826 should be fairly high on our priority list.
