### ISSUE TITLE
docker 3.0-rc1 New scylla-server with old scriptology error.

### ISSUE THREAD

**Issue by gnumoreno** [scylladb/scylla#3968]
@vladzcloudius @penberg 

Container created with:
`docker run --name some-scylla --volume /mnt/1:/var/lib/scylla -d scylladb/scylla:3.0-rc1 --developer-mode 0`

```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/configparser.py", line 761, in get
    value = d[option]
  File "/usr/lib64/python3.4/collections/__init__.py", line 805, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib64/python3.4/collections/__init__.py", line 797, in __missing__
    raise KeyError(key)
KeyError: 'SET_NIC'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/scylla/scylla_prepare", line 65, in <module>
    set_nic = cfg.get('SET_NIC')
  File "/usr/lib/scylla/scylla_util.py", line 484, in get
    return self._cfg.get('global', key).strip('"')
  File "/usr/lib64/python3.4/configparser.py", line 764, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'SET_NIC' in section: 'global'
```

`cat /etc/sysconfig/scylla-server`

```
# choose following mode: virtio, dpdk, posix
NETWORK_MODE=posix

# tap device name(virtio)
TAP=tap0

# bridge device name (virtio)
BRIDGE=virbr0

# ethernet device name
IFNAME=eth0

# setup NIC's and disks' interrupts, RPS, XPS, nomerges and I/O scheduler (posix)
SET_NIC_AND_DISKS=no

# ethernet device driver (dpdk)
ETHDRV=

# ethernet device PCI ID (dpdk)
ETHPCIID=

# number of hugepages
NR_HUGEPAGES=64

# user for process (must be root for dpdk)
USER=scylla

# group for process
GROUP=scylla

# scylla home dir
SCYLLA_HOME=/var/lib/scylla

# scylla config dir
SCYLLA_CONF=/etc/scylla

# scylla arguments
SCYLLA_ARGS="--log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix"

# setup as AMI instance
AMI=no
```

**Comment by vladzcloudius** [comment]
`scylla-3.0.rc1` is supposed to use "old" scriptology *and* `scylla-server` however for some reason this docker image has the "new" `scylla-server`.

**Comment by slivne** [comment]
is this #3908 ?

**Comment by gnumoreno** [comment]
@slivne I'm not sure but easy enough to reproduce. The command to deploy the docker image is in the beginning of the report.
`docker run --name some-scylla --volume /mnt/1:/var/lib/scylla -d scylladb/scylla:3.0-rc1 --developer-mode 0`

**Comment by vladzcloudius** [comment]
@slivne Hi. Is the a file I forgot to patch? It seems like it's a docker image building scriptology issue which I have no idea about. It looks like we don't use the corresponding tag/branch for all files when we build the image.

**Comment by gnumoreno** [comment]
@penberg can probably help here.

**Comment by penberg** [comment]
@vladzcloudius @gnumoreno Sorry, I don't undestand the question. What exactly is _scriptology_?

Please note that Scylla's Docker image uses `supervisord` to manage service. The Scylla server is started with:

https://github.com/scylladb/scylla/blob/master/dist/docker/redhat/scylla-service.sh

and

https://github.com/scylladb/scylla/blob/master/dist/docker/redhat/etc/supervisord.conf.d/scylla-server.conf

**Comment by penberg** [comment]
@vladzcloudius Please re-test with 3.0-rc2. Perhaps the RPM repository was not switched in time for -rc1:

https://github.com/scylladb/scylla/commit/f94b46e7e0373988c7a3bca070c68dc717e57cae

**Comment by gnumoreno** [comment]
@penberg tested with rc2 and the error is gone. Please close the issue.

**Comment by penberg** [comment]
Thanks @gnumoreno and @vladzcloudius!

**Comment by SiddhantSawant** [comment]
faced it again on 3.2.1-0.20200122.e3e301906d5

# scylla_setup  --setup-nic-and-disks --nic=eth0 --no-ntp-setup --no-raid-setup --no-node-exporter
Please select a NIC from the following list:
['eth0'
....

below if condition needs 
if interactive conditons

       if sysconfig_setup:
            set_nic_and_disks = interactive_ask_service('Do you want to enable Network Interface Card (NIC) and disk(s) optimization?', 'Yes - optimize the NIC queue and disks settings. Selecting Yes greatly improves performance. No - skip this step.', set_nic_and_disks)
            setup_args = '--setup-nic-and-disks' if set_nic_and_disks else ''
            nic = interactive_choose_nic()

and 

        if ec2_check:
            nic = interactive_choose_nic()
        if ec2_check:
            run('{}/scylla_ec2_check --nic {}'.format(scriptsdir(), nic))

**Comment by gnumoreno** [comment]
@SiddhantSawant please include steps to reproduce the problem (I would also advise to open a new issue). Are you running on docker?

**Comment by tarzanek** [comment]
@gnumoreno let's track this in https://github.com/scylladb/scylla/issues/5725
3.2 seems to be missing the patches from #3908
