### ISSUE TITLE
Looking good! Kafka port in progress?

### ISSUE THREAD

**Issue by jmealo** [scylladb/scylla#397]
Kudos, I've never seen Cassandra look so good!

I have three questions:
* Will you please consider rescuing other databases from the JVM?
* ... like Kafka?
* How do you think it would have impacted humanity if all Apache software was written in native code?

**Comment by avikivity** [comment]
Thanks!

**Comment by dorlaor** [comment]
Kafka is indeed a protocol we had in mind and we may do something about it
in the future.
Can you define a subset of the api that you think it's valuable to add to
Scylla?
