### ISSUE TITLE
multishard_combining_reader: reduce number of trips to foreign shards

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#3970]
The recent change (414b14a6bd803a432fbb72ad32ac60bec81e569c) of making inactive shard readers evictable introduced an explosion in the number of trips done to remote shards, per each shard reader.
We should investigate batching some of these calls together to reduce the latency penalty of the roundtrips.
For example:
* When we resume a reader we know we will want to also do a `fill_buffer()` call on it, so no need to do that in a separate `smp::submit_to()` call.
* When we re-create a reader (because it was evicted while paused) we also know we'll want to also do a `fill_buffer()` on it. This is the same when we create a reader for the first time.

What makes this batching difficult is that different actions are done by different components. Creating, re-creating and resuming readers is the responsibility of the `reader_lifecycle_policy`, while doing the fill-buffer calls is the responsibility of the `foreign_reader`. We have to examine whether this optimization is possible without breaking up the component boundaries and without introducing too much complexity.

**Comment by slivne** [comment]
@denesb - on very large systems with sparse tables with large partitions - what will the effect be ? can you cap this by some number - e.g. if we have increased the parallelism to 4096 would that mean we need to send 4096 messages or more ?

**Comment by denesb** [comment]
If the partitions are large then this is not a problem, as the page will be filled from one or a few of the shards. On large systems, with sparse tables and small partitions it's also not a problem as read-ahead will take care of reading the data in.
I don't think this will have a significant visible effect in any combination of node, table and partition size, but it can shave of a couple of task quota worth of time from the latency. But now that I think of it, range-scans are not that latency sensitive, so maybe this whole issue is moot?
