### ISSUE TITLE
system_distributed keyspace initialization prevents reaching schema agreement

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#3976]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): master (09a3b11c2), 3.0 too

Commit ca5dfdffc67b44fe74633bd74227e77b907f7a87 introduced a potential problem when adding a node to the cluster - `system_distributed` keyspace is now also included in computing schema digest used to check for schema agreement. Since `system_distributed` is initialized from code, the new node may have new timestamps in `system_schema`'s entry for `system_distributed` keyspace, so these would need to be pulled by other nodes in order to reach schema agreement. But, schema agreement is also needed for the said node to complete, and pulling schema from not-fully-initialized node is prohibited (until they stop being `gossip_only_member`s and start being fully fledged ring members.
As a result, new node keeps waiting for schema agreement before it can start sending its schema to other nodes, but that can't happen until other nodes pull schema from it, which is a circular dependency.

**Comment by tgrabiec** [comment]
The issue can still happen if you didn't start with a version with the fix because the old nodes will already contain mutations for `system_distributed` with different timestamps than the ones which are created by the bootstrapping node after the fix.

**Comment by tgrabiec** [comment]
@psarna Can you explain why we need to create those tables before the bootstrapping node syncs the schema?

**Comment by psarna** [comment]
@tgrabiec do you mean pushing the initialization right before starting the bootstrap process? I vaguely remember that it was my first idea to fix this issue, but it turned out to be not enough, because there were other independent places where the node could deadlock on a schema agreement (I think it was view building and something else, but I don't recall now).
Anyhow, we do not *need* to create the tables before syncing schema in `storage_service::join_token_ring`, AFAIK system distributed table keyspace initialization can be moved right before calling `bootstrap()`.

**Comment by tgrabiec** [comment]
Yes, basically we should not create any non-local tables before the bootstrapping node syncs the schema.

**Comment by psarna** [comment]
I'll create a patch, and meanwhile somebody with github superpowers could reopen this issue and reassign it to me.
