### ISSUE TITLE
cqlsh: Error: No module named cassandra

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#398]
[fedora@ip-172-31-46-74 ~]$ cqlsh IP

Python Cassandra driver not installed, or not on PYTHONPATH.
You might try "pip install cassandra-driver".

Python: /usr/bin/python
Module load path: ['/usr/bin', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages']

Error: No module named cassandra

**Comment by slivne** [comment]
@asias can we close this

**Comment by prateekarya28** [comment]
Am getting the below error while running the cqlsh ?? can somebody help me to pass this hurdle

[root@rac1 site-packages]# $CASSANDRA_PATH/bin/cqlsh

Python Cassandra driver not installed, or not on PYTHONPATH.
You might try "pip install cassandra-driver".

Python: /usr/local/bin/python
Module load path: ['/opt/cassandra/apache-cassandra-2.2.10/bin/../lib/six-1.7.3-py2.py3-none-any.zip', '/opt/cassandra/apache-cassandra-2.2.10/bin/../lib/futures-2.1.6-py2.py3-none-any.zip', '/opt/cassandra/apache-cassandra-2.2.10/bin/../lib/cassandra-driver-internal-only-3.5.0.post0-d8d0456.zip/cassandra-driver-3.5.0.post0-d8d0456', '/opt/cassandra/apache-cassandra-2.2.10/bin', '/usr/local/lib/python2.7/site-packages', '/usr/local/lib/python27.zip', '/usr/local/lib/python2.7', '/usr/local/lib/python2.7/plat-linux2', '/usr/local/lib/python2.7/lib-tk', '/usr/local/lib/python2.7/lib-old', '/usr/local/lib/python2.7/lib-dynload']

Error: can't decompress data; zlib not available

**Comment by penberg** [comment]
That looks like a different kind of problem:

```
Error: can't decompress data; zlib not available
```

Which OS is this? How did you install your Python?

**Comment by prateekarya28** [comment]
Red Hat Enterprise Linux Server release 5.3 (Tikanga)

python installation:-

tar -xvzf Python-2.7.8.tgz
cd Python-2.7.8
./configure --prefix=/usr/local
make
make install

**Comment by penberg** [comment]
@prateekarya28 I think you need to have ``zlib-devel`` package installed when you build Python for zlib to work.

**Comment by prateekarya28** [comment]
have tried to install but no package with name as zlib-devel

[root@rac1 lib]# yum install zlib-devel
Loaded plugins: security
Setting up Install Process
Parsing package install arguments
No package zlib-devel available.
Nothing to do

But zlib already installed on my system

[root@rac1 lib]# yum install zlib
Loaded plugins: security
Setting up Install Process
Parsing package install arguments
Package zlib-1.2.3-3.i386 already installed and latest version
Nothing to do
[root@rac1 lib]#

**Comment by penberg** [comment]
@prateekarya28 The `zlib` package is not enough for Python to build zlib support. It needs the development package, which contains things like source headers. I don't really know RHEL 5.3 very well, but perhaps you need to install EPEL for `zlib-devel` to become visible. Or alternatively, that package might be with a different name.

In any case, I think this is a Python installation issue (which lacks zlib), not Cassandra driver or ScyllaDB problem.
