### ISSUE TITLE
scylla_setup on offline installer always fails because of scylla-housekeeping

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#3980]
Since we run scylla-housekeeping unconditionally on scylla_setup, it likely always fails since it's offline.
We should ask before running, also it's better to skip scylla-housekeeping when it's in offline installer (special mode of scylla_setup, perhaps specify by --offline or something).

**Comment by syuu1228** [comment]
My description was bit wrong, scylla_setup actually asks "Do you want to enable Scylla to check if there is a newer version of Scylla available?", and disables housekeeping service if answer is "No".
However, scylla_setup tries to run scylla-housekeeping unconditionally just after that, to notify user if new version available.
And that code will always fail on offline node.
I think we shouldn't run scylla-housekeeping when user answered "No" to previous question.

**Comment by syuu1228** [comment]
reference: https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_setup#L224

**Comment by glommer** [comment]
We just hit this in the field. Do we have an estimate for a fix ?
This seems like a one-liner to me.

**Comment by gnumoreno** [comment]
Actually, I think the line is now https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_setup#L272

Why is that outside the conditional block on line 252, totally escapes me. https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_setup#L252

**Comment by glommer** [comment]
@gnumoreno it's called a bug.
The way to get rid of it is to send a patch, that puts it inside the conditional.

**Comment by amnonh** [comment]
Please note that whatever changes you are doing, regardless if the user choose to regularly check for housekeeping or not, checking during setup is not conditional.

In the original bash script failing to check for newer version did not fail the script.
What does need to change is that the python script will not fail, just as it used to be.

**Comment by glommer** [comment]
@amnonh we shouldn't do that check for nodes without internet connection.
If we can fail that fast, that's ok as well.

**Comment by amnonh** [comment]
We can either fail safely, as it used to be or as @syuu1228 suggested have an offline mode.
But the current behavior should remain

**Comment by glommer** [comment]
+1 for fail safely - and unit test that please.

**Comment by amnonh** [comment]
@syuu1228 I'm looking at the code, I'm not sure why it's a problem, from what I can tell, it should print a warning, but continue, which is ok.
