### ISSUE TITLE
'Request timed out while waiting for schema agreement.[...]' in restore_snapshot_using_old_token_ownership_test (backup_restore_tests.TestBackupRestore)

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#3982]
This issue is very hard to reproduce. I managed to do it only once.
[error.log](https://github.com/scylladb/scylla/files/2671990/error.log) has more details

Possibly related to #2820 and #3413 

Seems not SSTable MC format related because I reproduced it without "--enable-sstables-mc-format true"

More logs are available here:
http://jenkins.cloudius-systems.com:8080/job/scylla-byo-dtest/label=monster/121/consoleFull
http://jenkins.cloudius-systems.com:8080/job/scylla-byo-dtest/label=monster/121/artifact/scylla-dtest/logs-release.2/1543967925447_backup_restore_tests.TestBackupRestore.restore_snapshot_using_old_token_ownership_test/

The problem appears when "DROP KEYSPACE ks" is executed.
In logs from the 2 nodes in seems that the schema change was successful.

**Comment by tgrabiec** [comment]
On Wed, Dec 12, 2018 at 2:08 PM Piotr Jastrzębski <notifications@github.com>
wrote:

> This issue is very hard to reproduce. I managed to do it only once.
> error.log <https://github.com/scylladb/scylla/files/2671990/error.log>
> has more details
>
> Possibly related to #2820 <https://github.com/scylladb/scylla/issues/2820>
> and #3413 <https://github.com/scylladb/scylla/issues/3413>
>

Those look unrelated. In #2820 agreement is eventually reached, and #3413
is about a reactor stall.

Does the failed run contain a fix for
https://github.com/scylladb/scylla/issues/3976?

**Comment by haaawk** [comment]
> Does the failed run contain a fix for #3976?

I don't think so. Dtest run was started over 7 days ago and the fix was commited on 12 Dec.

**Comment by slivne** [comment]
there have been only to runs since the fix for #3976 went in both passed

direct link http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest/label=scylla-dtest,mode=release,smp=2/969/testReport/junit/backup_restore_tests/TestBackupRestore/restore_snapshot_using_old_token_ownership_test/history/

lets wait 3-4 additional runs if they all path - assume its fixed by that and close

**Comment by slivne** [comment]
so it hasn't failed since ... so I am closing this we can reopen/create new one if it fails again
