### ISSUE TITLE
Large row detector

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#3988]
Large rows can be a problem.

Lets enhance the Large Partition to detect also large rows.

**Comment by espindola** [comment]
I have sent a patch that adds a warning for large rows.

For partitions, we also have the system.LARGE_PARTITIONS table and a Swagger api.

Do we want to add a table with all large rows?

Do we want to extent the current api to report rows? There were talks about developing a new api based on a new specification format, but I am fuzzy on the details.

**Comment by tzach** [comment]
Using a table for large rows, as we have for wide partitions make a lot of sense

**Comment by slivne** [comment]
1. Lets get the version with the warning merged 
1. Lets create a table for system.LARGE_ROWS as well
1. Unless I am missing something all the stats that are returned today are used by jmx for nodetool cfxxx commands.  In this case I think there is currently there is no need to add parallel swagger api at this step and we can start with the warning and table and add stats if/when we find its needed. 
```
/column_family/metrics/estimated_row_size_histogram/
/column_family/metrics/estimated_row_count/
.
.
```
