### ISSUE TITLE
Thrift support

### ISSUE THREAD

**Issue by okrasz** [scylladb/scylla#399]
The status page says there is no support for Thrift clients. We have an app using Thrift. Any plans to support that?

**Comment by avikivity** [comment]
While we have a partial thrift implementation (enough to support cassandra-stress), it is incomplete, and therefore disabled. Thrift support will be enabled depending on customer demand; we have to prioritize thrift against other Cassandra features and new Scylla features as well.

**Comment by anvie** [comment]
vote for this :+1:

**Comment by jfenton** [comment]
adding my vote :+1:

**Comment by dorlaor** [comment]
Thanks for voting!

**Comment by VenkateshSub** [comment]
+1 for thrift support

**Comment by psterk1** [comment]
+1

**Comment by wpc009** [comment]
+1

**Comment by marcelow** [comment]
+1

**Comment by pouledodue** [comment]
+1000

**Comment by janprill** [comment]
+1 for thrift support

**Comment by dorlaor** [comment]
The plan is to have Thrift support in 1.3 - July 7th.
Super columns may take additional month.

**Comment by mkeagar** [comment]
+1 for Thrift support. Any updates on this?

**Comment by dorlaor** [comment]
It's there, we can close it. Go ahead and try it
