### ISSUE TITLE
cassandra-stress warning: !!!! Required field 'type' was not present! Struct: CqlResult(type:null)

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#40]
When running cassandra-stress 2.1.7 against urchin[1] on EC2 (without DPDK), I see the following warning initial warning from cassandra-stress:
```
!!!! Required field 'type' was not present! Struct: CqlResult(type:null)
```
After that, cassandra-stress seems to run fine.

[1] commit 78ee9e74783b6703e688cb6047dce7969c74209a

**Comment by slivne** [comment]
we have our version that works without thrift
