### ISSUE TITLE
Add enable_sstables_mc_format to scylla.yaml

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#4006]
*Installation details*
Scylla version (or git commit hash): 3.0

The new enable_sstables_mc_format parameter deserve place in scylla.yaml

related #4003

**Comment by tzach** [comment]
On second thought, having the parameter in scylla.yaml will be problematic in future releases, where the format should be enabled by default.

**Comment by dyasny** [comment]
Just ran into this myself and was about to open an issue. If this is a configurable option, why not set it, and default to true in future versions? 

Or maybe change it to `sstable_version: 3` (versus 2 in the current builds by default)

**Comment by avikivity** [comment]
It is set to true.

There is no such thing as sstable version 2 or sstable version 3.

**Comment by dyasny** [comment]
@avikivity I am looking at the documentation:

> In Scylla 3.0 the new disk format will be disabled by default and can be enabled by setting the new 
> enable_sstables_mc_format parameter to ‘true’ in scylla.yaml.

from: https://docs.scylladb.com/architecture/sstable/

**Comment by dyasny** [comment]
I just checked on scylla-server-3.0.rc4-0.20190106.5a178ff63.el7.x86_64

Without the setting in yaml, I am getting la sstables, with the setting, I am getting mc. So the docs are correct

**Comment by avikivity** [comment]
I meant the naming. There's no sstable version 2 or sstable version 3.

**Comment by dyasny** [comment]
OK then, the first part of my question stands - why not add it to scylla.yaml and set a true/false default according to what we decide? Hiding available options is bad UX.

**Comment by avikivity** [comment]
We have 161 options, we can't put everything there. Only the most important ones should be there.

Since it will default to true in the next version, it has limited lifespan.
