### ISSUE TITLE
Use offset maps to improve skipping in the MC-format sstable

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4007]
Currently, the promoted index (a row index within a partition) reader has to read all entries up to the target entry. Doing that is expensive in terms of CPU time and IO.

We could avoid this by doing a binary search in the promoted index. To do that, we need to know the offsets of promoted index entries (they have a variable length). The promoted index of the MC format contains an array with offsets for each promoted index entry, following the promoted index.

It would make sense to do the binary search with IO block granularity. When reading a promoted index block, compare against extreme entries present in that block first. Then either rule out the whole block, or binary search within it.

**Comment by bhalevy** [comment]
@avikivity this is issue tracking the binary search in the promoted index.
If I understood you correctly, we want also to cache the offset maps using LRU replacement.

**Comment by avikivity** [comment]
It is, but describing a different algorithm.

**Comment by avikivity** [comment]
Here's my design: https://docs.google.com/document/d/18xG6ILeCEVfogxJJz_mFtVXUUNzndBrEzfdIUtqvRoo/edit#heading=h.6mbvmwun4hfe
