### ISSUE TITLE
MC-format promoted index parser doesn't handle CK_SIZE split across buffers correctly

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4011]
Scylla version (or git commit hash): 3.0+

When data.size() is smaller than 2 in `(1)` below, we will incorrectly fall-through to the next state instead of returning and reading more data:

```c++
case state_m::CK_KIND:
                ctx.kind = bound_kind_m{_u8};
                if (ctx.kind == bound_kind_m::clustering) {
                    ctx.state = state_m::CK_BLOCK;
                    goto ck_block_label;
                }
                if (read_16(data) != read_status::ready) {
                    ctx.state = state_m::CK_SIZE;
// (1) ----> missing return here
                }
            case state_m::CK_SIZE:
```

This can manifest in a number of ways, an abort, or incorrect read.

Introduced in 917528c4274c49f6b166078bc401fe4ef8e1d822

**Comment by dorlaor** [comment]
Tomek, did you use your hawk eyes and brains or also an additional tool
that goes
through the code and automatically suggests interrogation of such
clauses/patterns?

**Comment by bhalevy** [comment]
@dorlaor https://groups.google.com/forum/#!searchin/scylladb-dev/continuous_data_consumer$3A$20Randomize$20buffer$20splits$20in$20debug$20mode$20build%7Csort:date/scylladb-dev/KUkAruw6CKw/61D8qGrPCAAJ
