### ISSUE TITLE
Insert using JSON: not clear message when primary key omitted from the column list and omitted from the JSON data

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#4015]
Scylla branch: master
JSON test run from 23.12.2018 failed.

Scenario:
1. Create table like:
     CREATE TABLE primitive_type_test (key1 text PRIMARY KEY, col1 ascii)
2. Run insert:
     INSERT INTO primitive_type_test JSON '{"col1": "bar"}

Expected error message:
     "InvalidRequest: Error from server: code=2200 [Invalid query] message="Missing mandatory PRIMARY KEY part key1""

Received message:
    "ServerError: _Map_base::at"

**Comment by psarna** [comment]
It looks like the issue was fixed, probably long ago and it just wasn't marked with `Fixes #4015`. Here's a run from master:
```
cqlsh:ks>  CREATE TABLE primitive_type_test (key1 text PRIMARY KEY, col1 ascii);
cqlsh:ks>  INSERT INTO primitive_type_test JSON '{"col1": "bar"}';
InvalidRequest: Error from server: code=2200 [Invalid query] message="Missing mandatory PRIMARY KEY part key1"
```
