### ISSUE TITLE
Three dtests failing after MV backpressure series

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#4019]
On branch-3.0, we are seeing three dtests failing:
```
materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_half_to_low_test
materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test
materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_max_to_half_test
```
The failures do not happen every time, but happen quite often.
All tests stop a cluster of nodes while it is building a view for existing data. This stopping is done gently, i.e., a signal is sent to the process and if it fails to stop within two minutes, the test is marked failed.

As it turns out, the shutdown process hangs in `view_builder.stop()`. It actually completes in most shards, but some times, in some shards, it does not complete.

Adding printouts to `view_builder::stop()`, I found the part which hung was
```c++
          return _sem.wait()
```
This _sem is (view_builder.hh):
```c++
    // Ensures bookkeeping operations are serialized, meaning that while we execute
    // a build step we don't consider newly added or removed views. This simplifies
    // the algorithms. Also synchronizes an operation wrt. a call to stop().
    seastar::semaphore _sem{1};
```
Maybe we have a deadlock - i.e., aborting in the middle of a build step keeps this semaphore locked, or something? Also, I don't know what the recent back-pressure code changed here, if at all. Could it be just a timing issue which made a pre-existing problem more common? (note that even today, it doesn't fail every time)

**Comment by nyh** [comment]
What happens is that all through a single "build step" the semaphore is taken, so the code assumes it will be able to abort an ongoing build step immediately (more or less) via the abort_source. But this is not happening: on one of the shards, a build step hangs and doesn't respond to the abort source.  

The logs confirm that this shard is sending updates to a node which has gone down (in this tests, all nodes are taken down but it doesn't happen at exactly the same time).

Looking at the view builder code in view.cc, specifically view_builder::consumer, it calls populate_views(), and that probably hangs somewhere, I still need to figure out where. Because this is a new failure when backpressure was added, this might have something to do with view_update_concurrency_semaphore, although I don't understand how (view building is supposed to be synchronous so shouldn't use much allocation from that semaphore and never see it hang).

**Comment by gleb-cloudius** [comment]
On Tue, Dec 25, 2018 at 02:29:36AM -0800, nyh wrote:
> As far as I can tell from printouts I added, a build step's populate_views() hangs on the last mutate_MV which happens right before this node notices the remote node is down:
> ```
> ARN  2018-12-25 12:12:30,221 [shard 0] database - NYH populate_views starting mutate_MV
> DEBUG 2018-12-25 12:12:30,221 [shard 0] view - Sending view update to endpoint 127.0.0.3, with pending endpoints = {}
> INFO  2018-12-25 12:12:30,221 [shard 0] gossip - InetAddress 127.0.0.3 is now DOWN, status = shutdown
> DEBUG 2018-12-25 12:12:30,221 [shard 0] storage_service - endpoint=127.0.0.3 on_dead
> DEBUG 2018-12-25 12:12:30,221 [shard 0] messaging_service - dropped connection to 127.0.0.3
> ```
> Despite noticing the remote node went down, mutate_MV never gives up (we let it give up for 2 minutes). 
> 
> Maybe what broke this test is commit e33e1870963b45db3dab37e81fdce47df43a2e55, which changed a view update timeout to 5 minutes (in this test we don't wait for 5 minutes, only 2)? Our theory was that as soon as the remote node is officially noticed down, we'll recognize this *immediately* and wouldn't need to wait until the 5 minute timeout (or any timeout) happens. But apparently this isn't happening - at least not in the view building case tested here.
> 
I explained it in details on the patch that changed timeout to 30m (and
before that too) that thinks do not work this way, but all I was able to
achieve is changing timeout back to 5m.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Tue, Dec 25, 2018 at 03:26:02AM -0800, nyh wrote:
> @gleb-cloudius  I was worried like you, during the review, about the timeout issues, specifically during shutdown (where a timeout can be worse than just a waste of memory - it can prevent the shutdown from succeeding).
> Anyway, to be concrete what doesn't work this way? We have, as far as I can tell, a call to storage_proxy::send_to_endpoint() to another node, which may or may not be already dead, but very soon the gossiper will recognize this node to be dead. We have the db::consistency_level::ANY consistency level. So shouldn't this send_to_endpoint() quickly decide to write a hint (because of CL=ANY) and return instead of continuing to try to send?
> 
> Unfortunately, I'm not an expert enough in our RPC to tell what really happens in this case. Will RPC blindly wait 5 minutes on some TCP connection or write attempt, without checking whether the node went down in the meantime?
> 
RPC does not get notifications from gossiper. They are on entirely
different level. Storage proxy may subscribe to DOWN event an than
iterate over all handler that involve DOWN destination and notify them
they will probably not get a reply, but first we lack that code, second,
a node may restart faster then we seeing DOWN event, there is RESTART
event that is triggered by generation change, so we can subscribe to that
too, but then how do you know if a write started before or after another
node was restarted? Will we keep generation number for each node in
write handler? Third while subscribing to gossiper events may somewhat
help MV since it sends only direct messages, but regular write path uses
message forwarding which races the question: if forwarding node
dies should we mark all messages it forwarded as lost or only the
one it has to reply to? The later will cause HA issues the former will
cause us to wait for timeout anyway. And last, but not least we can lose
messages even without any node restarting, it is enough for connection
to drop for some reason (bad network). In short it is a mess.

--
			Gleb.

**Comment by nyh** [comment]
@gleb-cloudius If I understand correctly now, a CL=ANY write (like we do for view writes) may in fact wait the full timeout when the remote node is down instead of immediately writing a hint. Whether it does wait the full timeout or not depends on the circumstances: A write that starts after we know the other node is down, will not wait at all (just write a hint) but if the node goes down in the middle of an individual write it **may** hang for the entire timeout time. Which explains why we see this problem sporadically, and not in all tests involving shutting down multiple nodes.

Given this, using a high 5-minute timeout for the **synchronous** view build (we wait for every view update) is very bad, as one node going down may hang the entire view build for five minutes, and also prevent shutdown during this time, and of course break these three tests.

We can greatly decrease this timeout, but may need to keep a different, high, timeout for the normal view writes (not the view build) because those are asynchronous and may have longer delays. But then we'll have a similar problem when trying to shut down during normal view writes: We wait for all of them to complete, and this may wait for the entire duration of the timeout.

I wonder what will happen if as an ad-interim solution, I just reduce the timeout, across the board (both view builds and normal view writes) from 5 minutes to, say,  30 seconds. 30 seconds is low enough to allow this test to succeed (it waits 2 minutes), and low enough for a reasonable operator to not give up during a shutdown attempt. On the other hand, it's pretty large even when a relatively long view-update queue exists. Not perfect, but still pretty large.

I think the long-term solution is something like #3826, where orthogonallly to whether or not individual writes timeout, we should be able to stop an ongoing write immediately when the operation that includes it (in this case, a view build step) wants to shut down. Such a fix would not solve the 5-minute (or whatever) hang of individual view writes or the entire view build when a node goes down, but will solve the shutdown problems which prompted this issue.

**Comment by slivne** [comment]
@nyh for 3.0 did we fix the dtests ? - we agreed to not change the 5 minute default that causes the tests to fail AFAIK.

**Comment by nyh** [comment]
@slivne Indeed with much regret on my part, we agreed to "fix" the dtests, not the code.
My patches for the dtest were already committed: https://github.com/scylladb/scylla-dtest/pull/780
So I'll close this issue.
