### ISSUE TITLE
Compaction should recalculate encoding stats

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4022]
Currently (since 15ef4ca73ca1b09a17f4661161c48343e736c36a) compaction just uses the default encoding_stats for writing the resulting sstable. It can do better by, e.g.:
1. Merge all input sstables encoding stats by taking the minimum values across the sstables.
2. Run an initial read-only phase to calculate the effective minimum values before constructing the writer.

**Comment by avikivity** [comment]
I don't understand phase 2.

**Comment by bhalevy** [comment]
Compaction may remove old mutations (especially with TWCS) so the minimum deletion time in the compacted sstable may be larger than the minima of the input sstables.  We must determine that before writing the sstable statistics (and data) file but if I understand correctly compaction runs a single pass to consume the input data and write the output.  If we want to determine the new minimum values we need to look at the whole data twice. One time to calculate the statistics and another time to write (and delta-encode) the output.

**Comment by avikivity** [comment]
Doubling the cost of compaction to make the timestamp baseline more accurate is terrible in terms of cost/benefit. The gain is almost nil, and you are making the most expensive process in the system twice as expensive.

Note that we can have accurate statistics, just not an accurate baseline for the timestamps.

**Comment by bhalevy** [comment]
Agreed. I just gave it as an example. What I had in mind was the smaller sstable run fragments that may fit in memory but even then 2 passes may prove to be too costly.

**Comment by avikivity** [comment]
Interesting, I didn't consider fragments. But yes the end result is still expensive in terrms if CPU consumed, and even with smallish fragments it will require huge amounts of memory.

**Comment by bhalevy** [comment]
So let's start with the first option then, and if particular compaction strategies can do better and analytically determine better lower bounds on the to-be-encoded ttl/deletion_time/timestamp they may use these instead.

**Comment by argenet** [comment]
I believe just addressing #3971 should be enough and will put Scylla in line with Cassandra for compactions.

There is no goal to have the exact minimal values across mutations actually stored in the data file so if the mutation that has the smallest value is dropped during compaction it is still fine to use, the delta-encoded values may take a bit more disk space but it is so small a per cent it can be neglected.

**Comment by bhalevy** [comment]
> the delta-encoded values may take a bit more disk space but it is so small a per cent it can be neglected

FWIW, that might be true if most values are close to the minimum.  If their dynamic range is large and the table consists many timestamp'ed cells that don't use the row's time stamp or tombstones, the savings might be more significant...

**Comment by bhalevy** [comment]
Closing as duplicate of #3971
