### ISSUE TITLE
Encoding stats minimum values should default to zero

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4023]
Cassandra picked an arbitrary date (2015-09-22 00:00:00 UTC) for the default
encoding stats (see [CASSANDRA-9828](https://issues.apache.org/jira/browse/CASSANDRA-9828)) for optimizing delta encoding by increasing the baseline value for unix timestamps.  We currently use these arbitrary epoch values as the default minimum encoding stats values in compaction.

This works ok while gc_clock::rep is int32_t thanks to wrap-around.  When we encode delta_deletion_time that is older than this epoch we encode a negative int32 value as a large uint32 and when it's read back and added to the minimum, it wraps around and results in the old unix time.

However, there are two issues with that:
1. We want to detect wrap around to catch invalid cases like large ttl that causes wrap around (See scylladb/scylla-enterprise#664)
2. We would like to use a 64 bit gc_clock::rep (#3353) and with that, since we're not encoding signed delta varint values but rather unsigned values, those large values (>= 0x80000000), that represent valid deletion times, won't wrap around in 64 bits and will look like dates in the far futures. So for future compatibility we better store these as small, 0-based deltas.

**Comment by bhalevy** [comment]
@slivne because of the future compatibility issue I mentioned above this should be fixed in 3.0.

**Comment by argenet** [comment]
Beware that Cassandra's default values are used to delta-encode values that are stored in the SerializationHeader in Statistics.db, so changing those values will break reading Cassandra-written files because base values will be incorrectly complemented when reading metadata stats from Statistics.db.

In fact, delta-encoding is applied twice on writing:
1) Values in Data.db file are delta-encoded against minimal values from `encoding_stats` collected in the memtable.
2) Minimal values in SerializationHeader (Statistics.db) are delta-encoded against defaults from Cassandra.

So, when reading data back, those delta-encoded values from SerializationHeader will be summed with defaults and if those defaults differ from Cassandra's that will result in datafile values being skewed.

That was the reason why we at some point resorted to Cassandra's default: b3572acd6e202959c4f08ae7dcb7f32a07558e2f

It is possible to workaround this by telling Cassandra-produced files from Scylla's own SSTables because Cassandra doesn't have a Scylla.db file but that's definitely to be done if defaults are changed so that Cassandra's values are still used for reading Cassandra-produced files.

**Comment by bhalevy** [comment]
@argenet 
> Beware that Cassandra's default values are used to delta-encode values that are stored in the SerializationHeader in Statistics.db

Yeah, I noticed that :-/  It's a pity.

> It is possible to workaround this by telling Cassandra-produced files from Scylla's own SSTables because Cassandra doesn't have a Scylla.db file but that's definitely to be done if defaults are changed so that Cassandra's values are still used for reading Cassandra-produced files.

I came to the same unfortunate conclusion last night. Cassandra's defaults for delta-encoding the serialization header are hard coded rather than stored in the SSTable, so it's not self describing as it should.

**Comment by bhalevy** [comment]
I'm actually testing a close approach right now of keeping the serialization header's min_local_deletion_time as vint<uint64_t> so that if it needs to wrap around Cassandra's epoch it would do that in a future compatible way - when gc_clock will be upgraded to 64 bits.  Then in the new world we will store also every other local_deletion_time as vint<uint64_t>

**Comment by avikivity** [comment]
That doesn't work, because if Cassandra encodes a baseline that is before its epoch it will encode it as 32-bit positive number, which we will interpret as way in the future.

**Comment by avikivity** [comment]
The idea is to use one of the delta encodings to make sure we never have a negative number in the other, and then the other can be 64-bit. It was really silly to use delta encoding in the serialization header, it happens once per file.

**Comment by bhalevy** [comment]
> It was really silly to use delta encoding in the serialization header, it happens once per file.
I strongly agree.

> That doesn't work, because if Cassandra encodes a baseline that is before its epoch it will encode it as 32-bit positive number, which we will interpret as way in the future.

I'm not sure we'll see that in the field, but we do see that in testing.  If we care to support importing of C* files with these earlier-than-epoch baselines then we should keep it as 32 bits as you said.  But doing that will also expose us to the 32 bit wraparound in the data file (scylladb/scylla-enterprise#664).

Either way we can be screwed...

Keeping the serialization header at 32 bits somewhat limits the benefit for delta-encoding dates in the far future.

We can be bold and have both as 64 bits when the scylla component is present or both at 32 bits otherwise.

**Comment by avikivity** [comment]
> > It was really silly to use delta encoding in the serialization header, it happens once per file.
> > I strongly agree.
> 
> > That doesn't work, because if Cassandra encodes a baseline that is before its epoch it will encode it as 32-bit positive number, which we will interpret as way in the future.
> 
> I'm not sure we'll see that in the field, but we do see that in testing. If we care to support importing of C* files with these earlier-than-epoch baselines then we should keep it as 32 bits as you said. But doing 

Yes

>that will also expose us to the 32 bit wraparound in the data file ([scylladb/scylla-enterprise#664](https://github.com/scylladb/scylla-enterprise/issues/664)).
> 
> Either way we can be screwed...
>

No. Currently, we decode as

    local_deletion_time = cassandara_epoch + decode_32(serialization header delta) + decode_32(cell delta)
 
I propose to change it to 

    local_deletion_time = uint32_t(cassandara_epoch + decode_32(serialization header delta)) + decode_64(cell delta)

if cell_delta is never negative, this is compatible in both directions.

> Keeping the serialization header at 32 bits somewhat limits the benefit for delta-encoding dates in the far future.

The format will change by then.

> 
> We can be bold and have both as 64 bits when the scylla component is present or both at 32 bits otherwise.

That works, except for Scylla->Cassandra direction which doesn't read the Scylla component.

**Comment by bhalevy** [comment]
> >  We can be bold and have both as 64 bits when the scylla component is present or both at 32 bits otherwise.
> 
> That works, except for Scylla->Cassandra direction which doesn't read the Scylla component.

Wouldn't encoding cell delta values larger than max int32 have the same problem?

**Comment by avikivity** [comment]
Cassandra doesn't support it anyway. We only need to keep compatibility for deletion times that can be expressed in Cassandra.

**Comment by bhalevy** [comment]
#4074 fix allows us to safely represent negative deltas so this issue can be closed.
