### ISSUE TITLE
View build hangs for 5 minutes when one of the nodes is removed

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#4028]
After commit e33e1870963b45db3dab37e81fdce47df43a2e55, as we already noted in #4019, a view build may hang for 5 minutes (the timeout set in `storage_proxy::send_to_endpoint()`) when one of the other nodes is taken down.

This behavior is arguably (?) reasonable if the remote node is down temporarily: In that case it may make sense to pause building the view for 5 minutes, instead of spending 5 minutes generating millions of hints to disk, which we will need to send later anyway. **However**, the test secondary_indexes_test.TestSecondaryIndexes.test_remove_node_during_index_build which now fails, demonstrates a bigger problem:

This test wants to stop and **remove** a node (with `nodetool removenode`) from the cluster. The node will never come back up, and is officially leaving the cluster forever. Nevertheless, the view build will wait for 5 minutes for no reason. But even more worryingly, we plan to increase this 5 minute timeout eventually. This example demonstrates that #3966 (shutdown-related) is not enough, and we also need #3826 (the ability to break the view-building's write as soon as the gossiper discovers the remove node is down).

In the short term, we should at least allow the test to pass by increasing the test's timeout on when it expects the view build to have completed, to more than the 5 minutes.

**Comment by duarten** [comment]
Doesn't this duplicate #3826?

**Comment by nyh** [comment]
Duarte, #3826 is very vague. As I said above, #3826 will indeed solve this. But this issue is about a very specific test which is failing, secondary_indexes_test.TestSecondaryIndexes.test_remove_node_during_index_build 
Maybe I should change the title...
