### ISSUE TITLE
View update hints shouldn't count towards marking a view as built

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#4039]
When building a view, any view update a node fails to deliver is stored as a hint. This enables the view builder to continue making progress and eventually mark the view as built. This is, however, wrong, since some updates have not made it to the view yet.

This is important in the context of streaming, where the view update propagation path can be invoked based on whether the view is built or not. The following problem can happen:

1. Base Ba finishes view building, but stored some updates to view Va as hints;
2. The view is globally marked as built;
3. Ba is lost and `nodetool removenode` is invoked;
4. The replicas of Ba will stream the data to some other node, which will see that the view is already built and won't invoke; Va won't be updated.

See also #3857, which gives other reasons to avoid storing view updates as hints when coming from view building.

**Comment by nyh** [comment]
While I agree this should perhaps fixed, I think (please correct me if I'm wrong and I'll delete this comment...) that your proposal is not really relevant to the problem you outlined as "can happen". Let me explain:

The reason why that special streaming path is needed is not because Ba didn't finish updating Va - that's not a problem, since Va will be dropped anyway so it doesn't matter at all if some of Va's updates got to hints or really made it all the way to Va and then Va got deleted. Rather, the problem in your scenario is that the node of Va as a base node (let's call it Bx) *also* does its own view building as a base node, and didn't finish before being killed. *That* is why we need the special view-building-streaming path. On the other hand, if Bx *did* finish its own view building, then no fix is needed regardless of whether Ba saved hints for Va or not...

Luckily, when the node Bx is killed in the middle of the view build, its "still building" flag remains on, forever, so the streaming code - which checks if *any* node has this flag on - will already work as expected, without the fix you suggest in this issue. If anything, there's an opposite problem now: That flag remains there forever, and even a month later, streaming will unnecessarily go through the view-update step.

**Comment by nyh** [comment]
Sorry, I messed up the example. I'm removing my comment and rethink the example tomorrow.

**Comment by gleb-cloudius** [comment]
On Tue, Jan 01, 2019 at 01:22:52PM -0800, Duarte Nunes wrote:
> When building a view, any view update a node fails to deliver is stored as a hint. This enables the view builder to continue making progress and eventually mark the view as built. This is, however, wrong, since some updates have not made it to the view yet.
> 
> This is important in the context of streaming, where the view update propagation path can be invoked based on whether the view is built or not. The following problem can happen:
> 
> 1. Base Ba finishes view building, but stored some updates to view Va as hints;
> 2. The view is globally marked as built;
> 3. Ba is lost and `nodetool removenode` is invoked;
> 4. The replicas of Ba will stream the data to some other node, which will see that the view is already built and won't invoke; Va won't be updated.
> 
How is it different from a regular MV write path where some updates may
end up as hints and a node that hold the hints may be removed thus
loosing some updates?

--
			Gleb.

**Comment by duarten** [comment]
It's different because the view is marked as built, when not all view updates have been delivered. In other words, we know the view replica isn't synced.

**Comment by gleb-cloudius** [comment]
On Wed, Jan 02, 2019 at 01:08:05AM -0800, Duarte Nunes wrote:
> It's different because the view is marked as built, when not all view updates have been delivered. In other words, we know the view replica isn't synced.
> 
But replicas may go out of sync immediately after view build completed
successfully and regular traffic begins, so why the view build is so
special? With a window of 10s between commit log sync it may even happen
with any writes after view build.

--
			Gleb.

**Comment by duarten** [comment]
I don't understand your argument. Then why write hints at all, if a node can go down and lose them?  Or, why did we introduce the mechanism in streaming to allow another node to continue the view building a previous one was in the middle of? We do these things to keep inconsistency to a minimum. In this case, a node can accumulate hints for a large period of time, which a) is not really needed, and just wastes disk space (#4039); and b) losing that node can introduce needless inconsistency.

**Comment by gleb-cloudius** [comment]
My argument is that unless we can solve all inconsistency problems all
together I do not see a point to special casing some code paths. We
should have proper view repair and run it regularly. Of course
continuing view building if it fails in the middle is required, but
aborting view building just because a messages was written into HH is
overkill and will only annoy people when MV building fails for no
apparent reason.

--
			Gleb.

**Comment by duarten** [comment]
I don't think anyone suggested aborting view building. View building is a resumable process, if a node is down it can just wait until it's up again.

We don't have proper view repair, and we may not have it. 

View building is special though, because while the normal view write path can be implemented in the future using strong consistency, that's harder to do for view building. So we should take care not to introduce inconsistencies when we can avoid doing that.

**Comment by gleb-cloudius** [comment]
On Wed, Jan 02, 2019 at 02:45:26AM -0800, Duarte Nunes wrote:
> I don't think anyone suggested aborting view building. View building is a resumable process, if a node is down it can just wait until it's up again.
> 
OK. So what does it mean to not mark view build is complete? Who will
complete it and when? If one write was dropped, but all other succeed
from which point view building will be restarted?

> We don't have proper view repair, and we may not have it. 
> 
How is it even optional? View and base may get out of sync.

> View building is special though, because while the normal view write path can be implemented in the future using strong consistency, that's harder to do for view building. So we should take care not to introduce inconsistencies when we can avoid doing that.
> 
I presume using strong consistency for view building precludes using of
hints anyway, no? Also it does look like using strong consistency will
affect performance greatly. Even with weak one we see that it affects
regular writes too much. But this is another topic.

--
			Gleb.

**Comment by duarten** [comment]
> On Wed, Jan 02, 2019 at 02:45:26AM -0800, Duarte Nunes wrote: I don't think anyone suggested aborting view building. View building is a resumable process, if a node is down it can just wait until it's up again.
> OK. So what does it mean to not mark view build is complete? Who will complete it and when? If one write was dropped, but all other succeed from which point view building will be restarted?

If the base node that was in the middle of building a view is removed, the nodes the ranges will migrate to will continue the build process.

Right now we build in chunks. If one write fails, then we would need to restart from the beginning of the chunk. (Similar to HH, which can re-send more hints than needed depending on the position of the mutation that failed to be sent in the file.)

> We don't have proper view repair, and we may not have it.
> How is it even optional? View and base may get out of sync.
> View building is special though, because while the normal view write path can be implemented in the future using strong consistency, that's harder to do for view building. So we should take care not to introduce inconsistencies when we can avoid doing that.
> I presume using strong consistency for view building precludes using of hints anyway, no? Also it does look like using strong consistency will affect performance greatly. Even with weak one we see that it affects regular writes too much. But this is another topic.

Yes, in the normal view write path. Whether it precludes hints in the view build path depends on the outcome of these issues.

**Comment by gleb-cloudius** [comment]
On Wed, Jan 02, 2019 at 11:05:43AM +0000, Duarte Nunes wrote:
> > On Wed, Jan 02, 2019 at 02:45:26AM -0800, Duarte Nunes wrote: I don't think anyone suggested aborting view building. View building is a resumable process, if a node is down it can just wait until it's up again.
> > OK. So what does it mean to not mark view build is complete? Who will complete it and when? If one write was dropped, but all other succeed from which point view building will be restarted?
> 
> If the base node that was in the middle of building a view is removed, the nodes the ranges will migrate to will continue the build process.
> 
> Right now we build in chunks. If one write fails, then we would need to restart from the beginning of the chunk. (Similar to HH, which can re-send more hints than needed depending on the position of the mutation that failed to be sent in the file.)
> 
In that case using HH will guaranty progress if networking is fluky.
Instead of restarting from beginning of a chunk on each failure we
delegate fixing small inconsistencies to HH. What you said about HH is
true, but more of implementation details because of how commitlog code
was written. If it will cause us problems we can change that.

> > We don't have proper view repair, and we may not have it.
> > How is it even optional? View and base may get out of sync.
> > View building is special though, because while the normal view write path can be implemented in the future using strong consistency, that's harder to do for view building. So we should take care not to introduce inconsistencies when we can avoid doing that.
> > I presume using strong consistency for view building precludes using of hints anyway, no? Also it does look like using strong consistency will affect performance greatly. Even with weak one we see that it affects regular writes too much. But this is another topic.
> 
> Yes, in the normal view write path. Whether it precludes hints in the view build path depends on the outcome of these issues.
> 
How is it relevant to that issue? "Strong consistency" means that we
guaranty that data reached its destination, not sitting in HH.

--
			Gleb.

**Comment by duarten** [comment]
> On Wed, Jan 02, 2019 at 11:05:43AM +0000, Duarte Nunes wrote: > On Wed, Jan 02, 2019 at 02:45:26AM -0800, Duarte Nunes wrote: I don't think anyone suggested aborting view building. View building is a resumable process, if a node is down it can just wait until it's up again. > OK. So what does it mean to not mark view build is complete? Who will complete it and when? If one write was dropped, but all other succeed from which point view building will be restarted? If the base node that was in the middle of building a view is removed, the nodes the ranges will migrate to will continue the build process. Right now we build in chunks. If one write fails, then we would need to restart from the beginning of the chunk. (Similar to HH, which can re-send more hints than needed depending on the position of the mutation that failed to be sent in the file.)
> In that case using HH will guaranty progress if networking is fluky. Instead of restarting from beginning of a chunk on each failure we delegate fixing small inconsistencies to HH. What you said about HH is true, but more of implementation details because of how commitlog code was written. If it will cause us problems we can change that.

Yes, that was the thinking. But it can introduce inconsistencies, which we want to minimize. 

> > We don't have proper view repair, and we may not have it. > How is it even optional? View and base may get out of sync. > View building is special though, because while the normal view write path can be implemented in the future using strong consistency, that's harder to do for view building. So we should take care not to introduce inconsistencies when we can avoid doing that. > I presume using strong consistency for view building precludes using of hints anyway, no? Also it does look like using strong consistency will affect performance greatly. Even with weak one we see that it affects regular writes too much. But this is another topic. Yes, in the normal view write path. Whether it precludes hints in the view build path depends on the outcome of these issues.
> How is it relevant to that issue? "Strong consistency" means that we guaranty that data reached its destination, not sitting in HH.

I don't follow. The view build code will be the same, it's just new writes that will leverage LWT.

**Comment by gleb-cloudius** [comment]
On Wed, Jan 02, 2019 at 03:36:52AM -0800, Duarte Nunes wrote:
> > On Wed, Jan 02, 2019 at 11:05:43AM +0000, Duarte Nunes wrote: > On Wed, Jan 02, 2019 at 02:45:26AM -0800, Duarte Nunes wrote: I don't think anyone suggested aborting view building. View building is a resumable process, if a node is down it can just wait until it's up again. > OK. So what does it mean to not mark view build is complete? Who will complete it and when? If one write was dropped, but all other succeed from which point view building will be restarted? If the base node that was in the middle of building a view is removed, the nodes the ranges will migrate to will continue the build process. Right now we build in chunks. If one write fails, then we would need to restart from the beginning of the chunk. (Similar to HH, which can re-send more hints than needed depending on the position of the mutation that failed to be sent in the file.)
> > In that case using HH will guaranty progress if networking is fluky. Instead of restarting from beginning of a chunk on each failure we delegate fixing small inconsistencies to HH. What you said about HH is true, but more of implementation details because of how commitlog code was written. If it will cause us problems we can change that.
> 
> Yes, that was the thinking. But it can introduce inconsistencies, which we want to minimize. 
> 
And the chance to introduce them is the same as in regular write path,
so why special case view building code? That's my only point here.

> > > We don't have proper view repair, and we may not have it. > How is it even optional? View and base may get out of sync. > View building is special though, because while the normal view write path can be implemented in the future using strong consistency, that's harder to do for view building. So we should take care not to introduce inconsistencies when we can avoid doing that. > I presume using strong consistency for view building precludes using of hints anyway, no? Also it does look like using strong consistency will affect performance greatly. Even with weak one we see that it affects regular writes too much. But this is another topic. Yes, in the normal view write path. Whether it precludes hints in the view build path depends on the outcome of these issues.
> > How is it relevant to that issue? "Strong consistency" means that we guaranty that data reached its destination, not sitting in HH.
> 
> I don't follow. The view build code will be the same, it's just new writes that will leverage LWT. 
> 
You've said: "Whether it precludes hints in the view build path depends
on the outcome of these issues.". How LWT using or not using hints
depends on outcome of this issue?

Also if base write will not wait for view update like it does now I do
not see how using LWT will solve inconsistency issue. Which races another
question: you wrote above that "while the normal view write path can be
implemented in the future using strong consistency, that's harder to do
for view building". Why is it so? It looks other way to me since regular
write path is async WRT base write but view building is synchronous
process.

--
			Gleb.

**Comment by duarten** [comment]
> On Wed, Jan 02, 2019 at 03:36:52AM -0800, Duarte Nunes wrote: > On Wed, Jan 02, 2019 at 11:05:43AM +0000, Duarte Nunes wrote: > On Wed, Jan 02, 2019 at 02:45:26AM -0800, Duarte Nunes wrote: I don't think anyone suggested aborting view building. View building is a resumable process, if a node is down it can just wait until it's up again. > OK. So what does it mean to not mark view build is complete? Who will complete it and when? If one write was dropped, but all other succeed from which point view building will be restarted? If the base node that was in the middle of building a view is removed, the nodes the ranges will migrate to will continue the build process. Right now we build in chunks. If one write fails, then we would need to restart from the beginning of the chunk. (Similar to HH, which can re-send more hints than needed depending on the position of the mutation that failed to be sent in the file.) > In that case using HH will guaranty progress if networking is fluky. Instead of restarting from beginning of a chunk on each failure we delegate fixing small inconsistencies to HH. What you said about HH is true, but more of implementation details because of how commitlog code was written. If it will cause us problems we can change that. Yes, that was the thinking. But it can introduce inconsistencies, which we want to minimize.
> And the chance to introduce them is the same as in regular write path, so why special case view building code? That's my only point here.

Like I said, the view building path is already special. If we can avoid introducing inconsistencies, we should do so.

> > > We don't have proper view repair, and we may not have it. > How is it even optional? View and base may get out of sync. > View building is special though, because while the normal view write path can be implemented in the future using strong consistency, that's harder to do for view building. So we should take care not to introduce inconsistencies when we can avoid doing that. > I presume using strong consistency for view building precludes using of hints anyway, no? Also it does look like using strong consistency will affect performance greatly. Even with weak one we see that it affects regular writes too much. But this is another topic. Yes, in the normal view write path. Whether it precludes hints in the view build path depends on the outcome of these issues. > How is it relevant to that issue? "Strong consistency" means that we guaranty that data reached its destination, not sitting in HH. I don't follow. The view build code will be the same, it's just new writes that will leverage LWT.
> You've said: "Whether it precludes hints in the view build path depends on the outcome of these issues.". How LWT using or not using hints depends on outcome of this issue? Also if base write will not wait for view update like it does now I do not see how using LWT will solve inconsistency issue. Which races another question: you wrote above that "while the normal view write path can be implemented in the future using strong consistency, that's harder to do for view building". Why is it so? It looks other way to me since regular write path is async WRT base write but view building is synchronous process.

I got trapped in my own sentence structure. I meant to say, a future version of MVs may not have hints in the write path due to LWT, and it may or may not have hints in the view build path depending on this issue.

**Comment by roydahan** [comment]
@duarten do view hints behave like regular HH?
What happens if a node is down for very long time? 
Till what point we continue accumulate these hints?
Can hints get dropped like in regular HH?
Does it mean the view will never get built till the stopped node gets back or replaced?
Can the user drop/cancel the view at this point?

**Comment by duarten** [comment]
@roydahan Yes, view hints are regular hints. If a node is down for a long time, hints are accumulated until we run out of space. They can be dropped if we don't have any space, or if they are older than GC grace period. A view can only be built once all view updates have made it to the view replicas. The user can drop views at any point they want.

**Comment by roydahan** [comment]
Thanks @duarten
