### ISSUE TITLE
xfs aio seams to be not always aio

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#404]
I am running cluster on aws and sometimes I see scylla cpus become partially idle. Checking wchan of those cpus shows things like:
call_rwsem_down_read_failed
inode_dio_wait
down
submit_bio_wait
wait_on_page_bit
_xfs_log_force_lsn
md_flush_request

**Comment by gleb-cloudius** [comment]
looks like inode_dio_wait is the main offender. Looking at the xfs code it seams that it is called if write is done beyond file size or it is unaligned. Are we doing any of those?

**Comment by avikivity** [comment]
We write beyond file size, not unaligned.

We may fix that by adding a truncate() call in posix_file_impl::allocate() (and truncate it back when we flush/close).

**Comment by gleb-cloudius** [comment]
On Fri, Sep 25, 2015 at 03:50:34PM -0700, Avi Kivity wrote:
> We write beyond file size, not unaligned.
> 
> We may fix that by adding a truncate() call in posix_file_impl::allocate() (and truncate it back when we flush/close).
> 
According to my testing we really should. Or use block storage like real
DB and ditch XFS too.

--
			Gleb.

**Comment by penberg** [comment]
@gleb-cloudius @avikivity Isn't that because we explicitly tell ``fallocate`` to ``FALLOC_FL_KEEP_SIZE``? Dropping that should make the ``truncate`` call redundant, no?

**Comment by gleb-cloudius** [comment]
On Sat, Sep 26, 2015 at 02:10:49AM -0700, Pekka Enberg wrote:
> @gleb-cloudius @avikivity Isn't that because we explicitly tell ``fallocate`` to ``FALLOC_FL_KEEP_SIZE``? Dropping that should make the ``truncate`` call redundant, no?
> 
The only use of fallocate in out code that I see is for trimming, not
preallocation.

--
			Gleb.

**Comment by avikivity** [comment]
No, it's preallocation.

**Comment by nyh** [comment]
On Sat, Sep 26, 2015 at 9:03 AM, Gleb Natapov <notifications@github.com>
wrote:

> On Fri, Sep 25, 2015 at 03:50:34PM -0700, Avi Kivity wrote:
> > We write beyond file size, not unaligned.
> >
> > We may fix that by adding a truncate() call in
> posix_file_impl::allocate() (and truncate it back when we flush/close).
> >
> According to my testing we really should. Or use block storage like real
> DB and ditch XFS too.
>

It is sad to see how bugs in the various filesystems prevent AIO from being
non-blocking as expected, and apparently nobody ever noticed, or nobody
cared enough to fix it. Yes, I know fixing these bugs is not easy, but a
lot of not-easy things have been done, and the fact that they haven't
(especially in ext4) means that apparently, nobody uses AIO in Linux!

So it would indeed be good in the long run to stop depending on Linux's
filesystems, and come up with a simple one (just for sstables and commit
logs) of our own, that uses the block device directly. Not depending on xfs
will also mean we could run scylla efficiently on OSv, not just Linux (I
know it's not a priority, but it would be nice).

--
> Gleb.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/404#issuecomment-143401686>.
>



-- 
Nadav Har'El
nyh@cloudius-systems.com

**Comment by slivne** [comment]
@avikivity  who can handle this ?

**Comment by avikivity** [comment]
@gleb-cloudius or me.

**Comment by slivne** [comment]
@avikivity can we close this now ?

**Comment by avikivity** [comment]
Still waiting for @elcallio commitlog patches (in addition to my truncate patch)

**Comment by elcallio** [comment]
I sent the patches a while ago: "Handle segments with pre-allocated disk 
data"

Den 2015-10-14 kl. 16:25, skrev Avi Kivity:

**Comment by avikivity** [comment]
Missed them
