### ISSUE TITLE
Memtable should update encoding stats for ttl in dead row marker

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4041]
We need to encode ttl=-1 for dead row markers and therefore we need to account for it in encoding_stats.min_ttl

**Comment by pdziepak** [comment]
Could you point me to the source of that `ttl=-1` requirement? Cassandra code seems to suggest it should be `Integer.MAX_VALUE`:
https://github.com/apache/cassandra/blob/ef1817a75ceeaa5f8eb11cd4acd0bcbe5f1ed14d/src/java/org/apache/cassandra/db/LivenessInfo.java#L28-L54

**Comment by bhalevy** [comment]
> Could you point me to the source of that `ttl=-1` requirement? Cassandra code seems to suggest it should be `Integer.MAX_VALUE`:
> https://github.com/apache/cassandra/blob/ef1817a75ceeaa5f8eb11cd4acd0bcbe5f1ed14d/src/java/org/apache/cassandra/db/LivenessInfo.java#L28-L54

I saw it in our documentation: https://github.com/scylladb/scylla/wiki/SSTables-3.0-Data-File-Format
"For dead row markers or expired liveness info, a special value -1 of TTL is set."

**Comment by bhalevy** [comment]
Agreed.  We need to encode max int32_t.
