### ISSUE TITLE
no status page while running scylla using docker/how to create keyspace using docker image

### ISSUE THREAD

**Issue by harrydevnull** [scylladb/scylla#405]
I was trying out scylla using docker on my mac and on command line it says
Starting listening for CQL clients on 172.17.0.10:9042...
Seastar HTTP server listening on 172.17.0.10:10000 

but if i were to hit 172.17.0.10:10000  via browser it just hangs, would a status page showing health of scylla come up?
how would I create keyspaces and schema after running docker image?

**Comment by penberg** [comment]
@harrydevnull You connect to the ScyllaDB instance via ``cqlsh`` from our scylla-tools package (RPM-only unfortunately) or with one from Cassandra 2.1.8 distribution.

As for the HTTP server, it obviously should not hang. @amnonh?

**Comment by slivne** [comment]
On Sep 25, 2015 9:43 AM, "Pekka Enberg" <notifications@github.com> wrote:
>
> @harrydevnull You connect to the ScyllaDB instance via cqlsh from our
scylla-tools package (RPM-only unfortunately) or with one from Cassandra
2.1.8 distribution.
>
> As for the HTTP server, it obviously should not hang. @amnonh?

I think we are missing the swagger and api desc files from the packaging
ill try to check later today or on sunday

**Comment by harrydevnull** [comment]
@slivne  I installed cqlsh using pip then tried connecting to localhost; but alas it wasn't working
   cqlsh
    Connection error: Could not connect to localhost:9160
    λ ~/ cqlsh
    Connection error: Could not connect to localhost:9160
    λ ~/ cqlsh 172.17.0.1      
    Connection error: Could not connect to 172.17.0.1:9160
   λ ~/ cqlsh 172.17.0.1 9042
   Connection error: Could not connect to 172.17.0.1:9042


Scylla version 0.9-20150924.49d6cba starting ...
Start Storage service ...
Start gossiper service ...
Starting listening for CQL clients on 172.17.0.1:9042...
Seastar HTTP server listening on 172.17.0.1:10000 ...

**Comment by penberg** [comment]
@harrydevnull Which version of ``cqlsh`` did you install? Port 9160 is the Thrift port which we don't have enabled by default so I suspect your version is older than the one in Cassandra 2.1.8.

Also, how did you start Scylla with ``docker run``? Port forwarding mode, right? So you should connect to ``localhost``, not the Docker internal IP.

**Comment by harrydevnull** [comment]
@penberg I think i do have the latest version of cqlsh 
```shell
λ ~/ cqlsh --version
cqlsh 4.1.1
```
I ran docker with the following command
```shell 
docker run -d -i -t mycass
```
the output of active process
``` shell
docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS              PORTS                                          NAMES
bde7c64e8891        mycass              "/bin/sh -c /start-sc"   About a minute ago   Up About a minute   7000-7001/tcp, 9042/tcp, 9160/tcp, 10000/tcp   condescending_bhaskara

docker-machine ip default
192.168.99.100
```

**Comment by penberg** [comment]
I don't think it's up-to-date enough for Scylla:

```
[penberg@nero apache-cassandra-2.1.8]$ ./bin/cqlsh --version
cqlsh 5.0.1
```

AFAICT, ``docker ps`` will not tell which ports are actually open. Use ``docker inspect`` for that.

**Comment by harrydevnull** [comment]
I did not want to install cassandra on my mac, that is the reason why i used docker
I installed cqlsh alone via pip install  cqlsh


output of ``` shell docker inspect```
``` json
[
{
    "Id": "07006796c3aef44bd63e22b909370a2049e66a4893988cb74f8cdd9246501e27",
    "Parent": "d266339d6b3ac284465b9c3da5f41e4fd66e80df34663e03d7f60217a98d9333",
    "Comment": "",
    "Created": "2015-09-24T20:44:43.609471555Z",
    "Container": "8e4a748bb92438fdb99374c23c3d5d79e14fb0d9b601f6ec082295354d5cd7e1",
    "ContainerConfig": {
        "Hostname": "76cf7f67d83a",
        "Domainname": "",
        "User": "scylla",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "10000/tcp": {},
            "7000/tcp": {},
            "7001/tcp": {},
            "9042/tcp": {},
            "9160/tcp": {}
        },
        "PublishService": "",
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": [
            "/bin/sh",
            "-c",
            "#(nop) CMD [\"/bin/sh\" \"-c\" \"/start-scylla\"]"
        ],
        "Image": "d266339d6b3ac284465b9c3da5f41e4fd66e80df34663e03d7f60217a98d9333",
        "Volumes": {
            "/var/lib/scylla": {}
        },
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": [],
        "Labels": {}
    },
    "DockerVersion": "1.8.2",
    "Author": "Avi Kivity \u003cavi@cloudius-systems.com\u003e",
    "Config": {
        "Hostname": "76cf7f67d83a",
        "Domainname": "",
        "User": "scylla",
        "AttachStdin": false,
        "AttachStdout": false,
        "AttachStderr": false,
        "ExposedPorts": {
            "10000/tcp": {},
            "7000/tcp": {},
            "7001/tcp": {},
            "9042/tcp": {},
            "9160/tcp": {}
        },
        "PublishService": "",
        "Tty": false,
        "OpenStdin": false,
        "StdinOnce": false,
        "Env": [
            "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        ],
        "Cmd": [
            "/bin/sh",
            "-c",
            "/start-scylla"
        ],
        "Image": "d266339d6b3ac284465b9c3da5f41e4fd66e80df34663e03d7f60217a98d9333",
        "Volumes": {
            "/var/lib/scylla": {}
        },
        "VolumeDriver": "",
        "WorkingDir": "",
        "Entrypoint": null,
        "NetworkDisabled": false,
        "MacAddress": "",
        "OnBuild": [],
        "Labels": {}
    },
    "Architecture": "amd64",
    "Os": "linux",
    "Size": 0,
    "VirtualSize": 823670227,
    "GraphDriver": {
        "Name": "aufs",
        "Data": null
    }
}
]
```

**Comment by penberg** [comment]
Well, I don't see any trace of Docker networking actually being enabled. But I'm really don't know Docker deeply enough to help you here.

The version you installed from ``pip`` is from 2012 according to Python package index so it likely doesn't even support CQL and thus won't work with ScyllaDB.

**Comment by harrydevnull** [comment]
@penberg really appreciate your effort for helping me out here. I think 2012 was the first  version of cqlsh , I might be totally wrong !!!

**Comment by penberg** [comment]
@harrydevnull Indeed, and I was wrong about the date as well. There's a ``cql`` package from 2012 but the ``cqlsh`` package is from 2014.

Unfortunately, it's not compatible with ScyllaDB. I installed ``cqlsh`` locally and it fails exactly the same way. Turns out the version installed from ``pip`` requires Thrift port to be enabled which is not the case for ScyllaDB. It's not the case for Cassandra 2.2 series either, btw.

So unfortunately, the ``cqlsh`` version is simply not compatible with ScyllaDB right now. You should still be able to run Python applications if you use recent enough driver, though:

https://github.com/datastax/python-driver

**Comment by penberg** [comment]
Oh, looks like there's a pull request against the ``cqlsh`` package to update it to 5.0.1 which will work with ScyllaDB:

https://github.com/amussey/cqlsh/pull/4

**Comment by harrydevnull** [comment]
@penberg can we enable the thrift port?  as in can it be turned on using a change of configuration param  or is the feature itself is totally absent?

can i assume the cqlsh 5 indeed speaking over cql 3 and not thrift?
AFAICT This would be a problem as many enterprises that uses java to connect to cassandra uses asytanax library https://github.com/Netflix/astyanax from netflix and that library speaks using thrift protocol not cql 3.0 .
The client libraries would have to changed in order to use scylla instead of cassandra

**Comment by penberg** [comment]
@harrydevnull There is indeed preliminary Thrift support in Scylla but the port is disabled by default because we are focusing on CQL.

I tried enabling it but unfortunately the ``cqlsh`` version you are using trips over an ``internal error``. That suggests that our Thrift implementation isn't compatible with the version of ``cqlsh`` you are using either.

**Comment by slivne** [comment]
@harrydevnull  have you bee able to use the cqlsh of a newer version - can we close this issue ?

**Comment by harrydevnull** [comment]
@slivne how can i install 5.1 cqlsh alone without installing cassandra on my local? anyways shouldn't scylla be backward compatible ? meaning shouldn't it work with cqlsh 4.1.1 seamlessly?

**Comment by slivne** [comment]
@harrydevnnull

you can pull of scylla-tools-java annd thenn use the bin/cqlsh provided
with it
https://github.com/scylladb/scylla-tools-java/tree/scylla-tools/anglerfish-2.1.8

1. git clone https://github.com/scylladb/scylla-tools-java -b
scylla-tools/anglerfish-2.1.8
2. then run bin/cqlsh <host> <port>

that will provide a cqlsh that works with scylla versionn

With regards to backward compatibility - scylla and cassandra are actually
the same in that regards - the client drivers can support different
versions - cqlsh can be forced to work with other versions (using
--cqlversion version flag) - yet I have used it only for backward versions
rather then forward versions which naturally may cause issues.

**Comment by harrydevnull** [comment]
Thanks !!! The instruction on ReadMe is not complete, the port forwarding had to enabled so that cqlsh -ing from the host could tunnel into the docker vm. Once that change is pulled in, you could close down the issue

**Comment by penberg** [comment]
@harrydevnull What's the status of this issue? Can we close it?

**Comment by harrydevnull** [comment]
@penberg : you can; but the instruction on the README has to be updated to include the  port forwarding, I believe you have that tracked as a separate IIRC or something!!

**Comment by penberg** [comment]
@harrydevnull Fixed in https://github.com/scylladb/scylla/commit/763b71841882684cbfa0c791312e7a01c99503e6, thanks for the reminder!
