### ISSUE TITLE
Run tests with halt_on_error=1

### ISSUE THREAD

**Issue by espindola** [scylladb/scylla#4054]
Currently we build with ubsan, but we run the tests without halt_on_error=1, which means it just reports an issue and keeps going.

**Comment by espindola** [comment]
Testing a patch for this found:

https://github.com/scylladb/scylla/issues/5413
https://github.com/scylladb/scylla/issues/5412

**Comment by avikivity** [comment]
Nice. So we have to fix those issues before we can apply, yes?

**Comment by espindola** [comment]
> Nice. So we have to fix those issues before we can apply, yes?

Yes. So far I have emailed a patch only for seastar (where no errors were found), not scylla.

**Comment by bhalevy** [comment]
For ASAN, https://github.com/google/sanitizers/wiki/SanitizerCommonFlags says:
```
abort_on_error | false (true on Darwin) | If set, the tool calls abort() instead of _exit() after printing the error report.
```

**Comment by avikivity** [comment]
This is just a unit test enhancement, no need to backport.
