### ISSUE TITLE
MC Format add support for shadowable tombstones in sstabledump 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4056]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by haaawk** [comment]
This can be closed now. It's fixed by https://github.com/scylladb/scylla-tools-java/commit/b3837032dc76d3c9b2146a0f0f4e42559aa1e48e
