### ISSUE TITLE
posix_net_conf.sh issue on system with more than 32 cores

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#406]
$ posix_net_conf.sh
Binding IRQ 231 to CPU0
Binding IRQ 232 to CPU0
Binding IRQ 233 to CPU0
Setting mask 3fffe in /sys/class/net/eth0/queues/rx-0/rps_cpus
Setting mask ffffc0000 in /sys/class/net/eth0/queues/rx-1/rps_cpus
posix_net_conf.sh: line 32: echo: write error: Value too large for defined data type
[fedora@ip-172-31-47-55 fedora]$ cat /sys/class/net/eth0/queues/rx-1/rps_cpus
00000000,00000000,00000000,00000000

When the mask is more than 32 bits, the correct format looks like below:

[fedora@ip-172-31-47-55 fedora]$ cat /sys/class/net/eth0/queues/rx-0/rps_cpus
00000000,00000000,00000000,0003fffe

[fedora@ip-172-31-47-55 fedora]$ cat /sys/class/net/eth0/queues/rx-1/rps_cpus
00000000,00000000,0000000f,fffc0000

**Comment by asias** [comment]
@vladzcloudius can you fix this?

**Comment by vladzcloudius** [comment]
On Sep 25, 2015 9:28 AM, "Asias He" <notifications@github.com> wrote:
>
> @vladzcloudius can you fix this?

Sure. I'll take a look.

**Comment by vladzcloudius** [comment]
On 09/25/15 16:01, Vladislav Zolotarov wrote:
>
>
> On Sep 25, 2015 9:28 AM, "Asias He" <notifications@github.com 
> <mailto:notifications@github.com>> wrote:
> >
> > @vladzcloudius can you fix this?
>
> Sure. I'll take a look.
>

I've sent a patch with the fix to dev-internal

**Comment by slivne** [comment]
resolved by seastar 7b8549d9f2e39b9747b63a6062806ceca6a6b58e
