### ISSUE TITLE
Take number of SSTables into account for the compaction controller

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#4076]
The compaction controller currently does not take number of SStables into account, just size of data.
This can be problematic for tables with explicit flushes or imported tables that generate a lot of small SSTables in large number.

Avi says:

* the compaction controller should take the number of sstables into consideration, not just the byte backlog
* memtable flush shoud wait until the number of sstables (per tier or whatever) is below some threshold before creating a new sstable

**Comment by slivne** [comment]
@glommer -  is the origin of this issue the case of truncation/drop creating many system tables - #4083 ?

**Comment by avikivity** [comment]
That's just one victim. Any scenario that results in lots of small sstables can suffer from this. One example is writes to large numbers of tables, resulting in small memtables, resulting in large numbers of small sstables.

**Comment by slivne** [comment]
@glommer / @avikivity  what is the 

compaction controller 
- what is the weight between the two  - should it be 50% the backlog size and 50% the number of tables ?
can you please provide some indication of how you want to take into account the two.

**Comment by glommer** [comment]
I am sure Avi has his own ideas on how to take this into account.
One thing we could do is calculate the natural amount of SSTables expected by the extrategy for the given backlog (For instance, for size tiered, that will be some proportion to the log of size).

Until we are within a reasonable margin from that we can ignore number of SSTables. Once we cross that, then we can start adding to the backlog to compensate for that.

**Comment by bhalevy** [comment]
@raphaelsc, doesn't d8833de3bb1274500e90590197df300a097d93ba fix this issue as well?

**Comment by raphaelsc** [comment]
> @raphaelsc, doesn't [d8833de](https://github.com/scylladb/scylla/commit/d8833de3bb1274500e90590197df300a097d93ba) fix this issue as well?

Let me think...

the backlog for a table is SSTable_size * log(Table_size / SSTable_size). 

for Table_size=100G and new small SSTable_size=100M,

each such new SSTable will add to the backlog: 100M * log (100G / 100M = 5) = 500M.

With 32 new such SSTables, 16G was added to the backlog.

Assuming high disk:memory ratio of 100:1, this node has 1G of memory.

16G adds (16G / 1G) 16 to the normalized backlog. That's already enough for us to be running at relatively high shares, probably about ~500 or so.

Doubling the # of sstables to 64, we'll probably close to full speed, i.e. shares approaching 1000.


Now if we're talking about really tiny sstables, then we have a problem as their size alone cannot make an impact on shares. So we should make the # of sstables a factor, not only their size.

**Comment by bhalevy** [comment]
To summarize our 1:1 discussion: we could have a constant (normalized) cost per sstable + variable cost proportional to the sstable data size such that many small sstables will still contribute the backlog.
We need to do some research to find out the coefficients for `C + F * data_size / mem_size`

**Comment by bhalevy** [comment]
@mikolajsieluzycki is looking into taking the number of sstables into account in `compaction_manager::calculate_weight`

**Comment by raphaelsc** [comment]
> compaction_manager::calculate_weight

this procedure is used for the sole purpose of serializing similar-sized jobs, so has no impact on compaction shares. I think we should look at size_tiered_backlog_tracker::refresh_sstables_backlog_contribution() instead

**Comment by mikolajsieluzycki** [comment]
With https://github.com/scylladb/scylla/commit/8edb79ea80746886cdb3bce6d9f0b324bfd00bbc and https://github.com/scylladb/scylla/pull/10717 this becomes less relevant. The expected gain would be marginal and hard to even measure, as small sstables are compacted quickly anyway.
