### ISSUE TITLE
Data resurrection on scylla/os crash during sstable deletion after compaction

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#4082]
After compaction, we delete the input sstables. If we crash during this deletion, and we've successfully deleted an sstable that contains a tombstone but did not delete an sstable that contained data that was covered by this tombstone, and if the compacion output sstable did not contain this tombstone, then data will be resurrected.

**Comment by bhalevy** [comment]
Let's consider a sub-directory to link sstables_to_delete_atomically files
ahead of time and use it for rolling forward the operation on restart
in case we crash during delete_atomically and before recursively deleting
the subdirectory.

**Comment by bhalevy** [comment]
@raphaelsc fyi

**Comment by raphaelsc** [comment]
@bhalevy Having a pending deletion directory with TOC files would be indeed cool
you could have like one dir for each atomic deletion inside a pending deletion dir but i think a single dir could do just as well. Perhaps we don't need to store each atomic deletion separately belonging to same cf. We just need to ignore all sstables inside the subdir to avoid ressurection

**Comment by bhalevy** [comment]
The problem with dumping all toc's in the same directory is that you want
atomicity for each subset so you either delete all sstables in a subset or
none. Without arranging each subset separately you don't know that the
subset deletion was committed successfully.  Hence the direction we want
take is storing the subset in a plain file in a e.g. pending_deletion
subdir, starting with a temporary name for the file and renaming it after
writing, flushing, and closing, then flushing the subdir. After that
actual deletions of the sstable files may proceed and eventually, the
subset file in the pending_deletions subdir will be deleted.

**Comment by nyh** [comment]
@bhalevy one way we could achieve atomic deletion of many files is to state our intent to delete a collection of files in a single text file. For example, imagine we need to atomically delete files A, B, C, D. By "atomically delete" (which is somewhat of a misnomer) what we really mean that after a reboot, we need all of these files to have been deleted. We could write to a text file called (for example) A.delete our intent to delete A, B, C, D. Our code first deletes A, B, C and D, and only when these deletions are confirmed, deletes A.delete. During boot, if a file called "*.delete" exists, it is "replayed", and the files listed there, if they still exist, are deleted, and the ".delete" file itself is only deleted after those deletions succeed.

**Comment by bhalevy** [comment]
> @bhalevy one way we could achieve atomic deletion of many files is to state our intent to delete a collection of files in a single text file. For example, imagine we need to atomically delete files A, B, C, D. By "atomically delete" (which is somewhat of a misnomer) what we really mean that after a reboot, we need all of these files to have been deleted. We could write to a text file called (for example) A.delete our intent to delete A, B, C, D. Our code first deletes A, B, C and D, and only when these deletions are confirmed, deletes A.delete. During boot, if a file called "*.delete" exists, it is "replayed", and the files listed there, if they still exist, are deleted, and the ".delete" file itself is only deleted after those deletions succeed.

@nyh agreed. That's essentially what I wrote above in my reply to Raphael.
