### ISSUE TITLE
`node_health_check` should also collect `/etc/redhat-release`, in addition to `os-release`, so we could see the OS minor version

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla#4093]
`node_health_check` should collect `/etc/redhat-release`, instead of `os-release`, so we could see the OS minor version.
`/etc/redhat-release` should go into `system_checks` output folder in the script.

**Comment by dyasny** [comment]
patch submitted: https://groups.google.com/forum/#!topic/scylladb-dev/vmLvpaqX0jo

**Comment by glommer** [comment]
maybe not instead , but in addition. (it needs to keep working for ubuntu, etc)

**Comment by dyasny** [comment]
"instead" was the wrong word. The patch adds redhat-release in addition to
it, of course

**Comment by nyh** [comment]
Note that /etc/os-release is a fairly standard file (see https://www.freedesktop.org/software/systemd/man/os-release.html) and also includes the distributions version. What more do you expect to find in /etc/redhat-release?
Although I guess it can't hurt to have *more* data in the report...

**Comment by dyasny** [comment]
On Wed, Jan 16, 2019 at 11:09 AM nyh <notifications@github.com> wrote:

> Note that /etc/os-release is a fairly standard file (see
> https://www.freedesktop.org/software/systemd/man/os-release.html) and
> also includes the distributions version. What more do you expect to find in
> /etc/redhat-release?
>
os-release doesn't contain the minor version. For CentOS7.5 it will only
say "Centos 7". redhat-release will give us the minor version as well
(7.5). This is why this patch is needed, nothing else, really

**Comment by nyh** [comment]
@dyasny I never noticed that. Good to know.
