### ISSUE TITLE
`node_health_check` does not collect the content of `/etc/scylla.d/*` - important CPU conf files to collect

### ISSUE THREAD

**Issue by tomer-sandler** [scylladb/scylla#4094]
`node_health_check` does not collect the content of `/etc/scylla.d/*` - important CPU conf files to collect.
`/etc/scylla.d/*` collection should go into `scylladb_checks` output folder in the script

**Comment by dyasny** [comment]
https://groups.google.com/forum/#!topic/scylladb-dev/1Mu51HWWj3I
