### ISSUE TITLE
AWS AMI: make scylla-ami independent from other scylla projects

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#410]

**Comment by tzach** [comment]
@slivne I suggest to push this post GA

**Comment by slivne** [comment]
I am against that

We have been going back and forth on the AMI and what we want todo with it
(upgrade / no upgrade / stand alone / install roms) - we need to decide and
do that - I want to try and have a decision tomorrow on the daily.

Once its done we should impl what we decide - this is a real pain -we also
have ntp configuration etc that we need todo and I want to finish all of
that as well.

**Comment by glommer** [comment]
A comment from Jan 12th said we would decide this "tomorrow", so I am assuming tomorrow already came
(For future reference, it is better to be atemporal in issues and don't assume external context for the benefit of both future and external-to-the-thread readers).

To the best of my knowledge we already made decisions on all of this and are steering in the direction of providing updatable packages for AMIs. Closing.
