### ISSUE TITLE
partition_snapshot_reader reemits range tombstones with each overlapping ck range

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#4104]
When `partition_snapshot_reader` is created with a partition-slice that contains multiple ck ranges, and the queried partition has range tombstones that overlap with more than one of these ck ranges, the reader will emit all overlapping range tombstones when entering each ck range.
Example:
Given the partition: `ps{}, rt{[1,4]}, cr{1}, cr{2}, cr{3}, cr{4}, pe{}`
And a partition-slice, with the following ck ranges: `[1], [2], [3], [4]`
The reader will emit the following fragments: `ps{}, rt{[1,4]}, cr{1}, rt{[1,4]}, cr{2}, rt{[1,4]}, cr{3}, rt{[1,4]}, cr{4}, pe{}`
This breaks mutation fragment monotonicity. The reader should emit the tombstone exactly once, before the first row it applies to (`cr{1}`).

**Comment by denesb** [comment]
The problematic code:
https://github.com/scylladb/scylla/blob/7308effb450a83b129aaa68ca11a36cbf6d8cdc8/partition_snapshot_reader.hh#L85-L90

This should not apply any range tombstone, whose position is less than that of the last emitted fragment.

**Comment by slivne** [comment]
@denesb which versions does this apply to ?

**Comment by denesb** [comment]
I found it in master. I'll check tomorrow whether it applies to 3.0 and 2.3
as well.

**Comment by avikivity** [comment]
I'll need help to decide if it requires backporting.

**Comment by tgrabiec** [comment]
I also think, with weak confidence, that this is benign.

**Comment by slivne** [comment]
Whats the risk of backporting ?

**Comment by tgrabiec** [comment]
This touches `memtable` reader in a non-trivial way, which is a risk of introducing data loss.

**Comment by slivne** [comment]
@tgrabiec thanks
@denesb / @tgrabiec - are our tests covering _"memtable reader in a non-trivial way, which is a risk of introducing data loss"_ this well enough ? 

Trying to make sure that this will not introduce a data loss / correctness issue. If we need to add tests lets do that.

**Comment by denesb** [comment]
I will soon send a series that reverts this intrusive change and replaces it with a much safer one.
About the tests: we have the usual mutation source test for the memtable which is pretty thorough (but didn't detect this bug though).
