### ISSUE TITLE
sstables::malformed_sstable_exception seen in update_cluster_layout_tests.TestLargeScaleCluster.add_50_nodes_test

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4108]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 02d88de082d2b2fdfc04c45f5583e7ce68476ad0
Cluster size: 50

See [node25.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest/label=scylla-dtest,mode=release,smp=2/1004/artifact/urchin-dtest/logs-release.2/1547702971381_update_cluster_layout_tests.TestLargeScaleCluster.add_50_nodes_test/node25.log)

For example:
```
ERROR 2019-01-17 07:29:17,845 [shard 0] compaction_manager - compaction failed: sstables::malformed_sstable_exception (c1 definition in serialization header does not match schema. Expected org.apache.cassandra.db.marshal.UTF8Type but got org.apache.cassandra.db.marshal.UTF8Type in sstable /jenkins/.dtest/dtest-Qij8K4/test/node25/data/ks/cf-92aec9a01a1311e99ce4000000000001/mc-160-big-Data.db): retrying
```
This exception is generated in sstables/mp_row_consumer.hh:
```
    void check_schema_mismatch(const column_translation::column_info& column_info, const column_definition& column_def) {
        if (column_info.schema_mismatch) {
            throw malformed_sstable_exception(
                    format("{} definition in serialization header does not match schema. Expected {} but got {}",
                        column_def.name_as_text(),
                        column_def.type->name(),
                        column_info.type->name()));
        }
    }
```
And since "expected" and "got" seem the same, it's possible that the column definition differs from the type by is_multi_cell/is_counter.
sstables/column_translation.hh:
```
                    if (def) {
                        id = def->id;
                        schema_mismatch = def->is_multi_cell() != type->is_multi_cell() ||
                                          def->is_counter() != type->is_counter() ||
                                          !def->type->is_value_compatible_with(*type);
                    }
```

**Comment by bhalevy** [comment]
@haaawk: please take a look

**Comment by haaawk** [comment]
Has this test passed before? Does it make sense to do bisect to find the first commit that it fails for?

**Comment by haaawk** [comment]
Which branch is this for master, scylla-3.0.0 or scylla-3.0.rc4? Each one has 02d88de.

**Comment by haaawk** [comment]
Ok I see it's master, isn't it?

**Comment by bhalevy** [comment]
> Ok I see it's master, isn't it?

Yes, it's master.  The test has passed before, but it fails occasionally.  I'm not sure if it's for the same reason though.  Need to dig into the nodes' logs.

**Comment by haaawk** [comment]
This is weird. When I run this test cassandra-stress fails with unknown parameter limit:

```
[haaawk@desktop scylla-dtest]$ nosetests -v update_cluster_layout_tests.py:TestLargeScaleCluster.add_50_nodes_test
add_50_nodes_test (update_cluster_layout_tests.TestLargeScaleCluster) ... Invalid parameter limit=100/s
Usage:      cassandra-stress <command> [options]
Help usage: cassandra-stress help <command>

---Commands---
read                 : Multiple concurrent reads - the cluster must first be populated by a write test
write                : Multiple concurrent writes against the cluster
mixed                : Interleaving of any basic commands, with configurable ratio and distribution - the cluster must first be populated by a write test
counter_write        : Multiple concurrent updates of counters.
counter_read         : Multiple concurrent reads of counters. The cluster must first be populated by a counterwrite test.
user                 : Interleaving of user provided queries, with configurable ratio and distribution
help                 : Print help for a command or option
print                : Inspect the output of a distribution definition
legacy               : Legacy support mode
version              : Print the version of cassandra stress

---Options---
-pop                  : Population distribution and intra-partition visit order
-insert               : Insert specific options relating to various methods for batching and splitting partition updates
-col                  : Column details such as size and count distribution, data generator, names, comparator and if super columns should be used
-rate                 : Thread count, rate limit or automatic mode (default is auto)
-mode                 : Thrift or CQL with options
-errors               : How to handle errors when encountered during stress
-schema               : Replication settings, compression, compaction, etc.
-node                 : Nodes to connect to
-log                  : Where to log progress to, and the interval at which to do it
-transport            : Custom transport factories
-port                 : The port to connect to cassandra nodes on
-sendto               : Specify a stress server to send this command to
-graph                : Graph recorded metrics
-tokenrange           : Token range settings
```

**Comment by haaawk** [comment]
It seems that cassandra-stress compiled from master of scylla-tools-java has problems with 'limit' parameter:

```
[haaawk@desktop scylla-tools-java]$ git branch
* master
[haaawk@desktop scylla-tools-java]$ ./tools/bin/cassandra-stress write -rate threads=2 limit=100/s
Invalid parameter limit=100/s
Usage:      cassandra-stress <command> [options]
Help usage: cassandra-stress help <command>
```

**Comment by haaawk** [comment]
It seems that in latest cassandra-stress throttle or fixed should be used instead of limit:
https://docs.datastax.com/en/dse/6.7/dse-dev/datastax_enterprise/tools/toolsCStress.html

```
Set the rate using the following options:
-rate threads=N [throttle=N] [fixed=N]
```

**Comment by haaawk** [comment]
Changing limit=100/s to throttle=100/s in update_cluster_layout_tests.py solved the problem for me but I wonder how does jenkins work without it this.

**Comment by slivne** [comment]
@haaawk its a bug @roydahan we need to fix this across the board so check if we have other limits

its since updating the tools to 3.11 c-s seems to have changed

@haaawk  Having said that - you still need to fix the bug

The test passes on 3.0 (maybe in an empty method) - it fails on master with mc enabled by default.

It does not allways fail in the same manner - so it will be hard to reproduce - we need to base the fix on what jenkins reported and analysis.

If you need to add additional tracing to the test / more information info to the error do that (it will serve us on the field as well :) ).

**Comment by roydahan** [comment]
The "limit" is the old c-s parameter.
It was changed when we moved to tools 3.11.
It seems like it's the only place in dtest where we have limit, but I don't understand how the test passed till now...

**Comment by haaawk** [comment]
It's a mystery for me too @roydahan :) - it also creates a bit of a doubt about the test results unfortunately.

**Comment by roydahan** [comment]
I agree, unless branch-3.0 doesn't really use java-tools 3.11.

**Comment by haaawk** [comment]
But isn't this failure for master?

**Comment by roydahan** [comment]
Yes, this one is on master, but the same test passes also on branch-3.0.
From what I see, I don't think the test ever failed due to this c-s failure, it's probably ignoring it, but I need to verify.

**Comment by avikivity** [comment]
The only explanation I can see is that an sstable was created on one shard and used on another.

@asias is that possible during streaming/repair?

**Comment by avikivity** [comment]
(abstract_type::is_value_compactible_with() is supposed to return true for the same type, buf if the type objects belong to different shards, it will fail)

**Comment by asias** [comment]
> The only explanation I can see is that an sstable was created on one shard and used on another.
> 
> @asias is that possible during streaming/repair?

If it was the reader, then it can be the flat mutation reader pick up the wrong sstable.
If it was the write, then it can be the multishard_writer write to wrong shard. 

I am not sure about 1), but I am pretty sure multishard_writer does not do that.

**Comment by avikivity** [comment]
The first priority is to get it to reproduce locally and reliably. Once we have that we can add all sorts of instrumentation.

**Comment by avikivity** [comment]
@asias the error happened during read

**Comment by haaawk** [comment]
@avikivity I tried to reproduce it already but the test does not fail on my machine. Is it reproducible on jenkins?

**Comment by avikivity** [comment]
I don't know.

**Comment by haaawk** [comment]
Couple of thoughts:
1. There are only logs for nodes 1 to 25 on jenkins and failure is logged in log for node25 so we can expect that the problem occurred on a node being added to the cluster.
2. Problem happened for ks.cf which is not the table used by the background c-s writes. There is a chance that we can remove background c-s from the test and still observe the problem. I may be crucial for the problem to occur though because of the pressure it puts on the cluster.

**Comment by avikivity** [comment]
A suspect is `multishard_mutation_query`. I audited the code and saw no leaks of a schema that were not mediated by `global_schema_ptr`, but maybe I missed something. It's also possible that the multishard writer installed a bad schema and later the read suffered from it.

**Comment by avikivity** [comment]
@denesb any ideas?

**Comment by avikivity** [comment]
(I also audited multishard_writer and it seemed fine too)

**Comment by avikivity** [comment]
I don't think `make_multishard_streaming_reader` can be implicated, it fails during compaction. So that leaves multishard_writer.

**Comment by avikivity** [comment]
I don't see how it can be a simple using-the-wrong-shard bug. It would always fail in that case. Maybe it was a random memory corruption. Let's wait for it to reproduce in the next few runs.

**Comment by slivne** [comment]
It reproduced again

[node28](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest/label=scylla-dtest,mode=release,smp=2/1009/artifact/urchin-dtest/logs-release.2/1548172242657_update_cluster_layout_tests.TestLargeScaleCluster.add_50_nodes_test/node28.log)

**Comment by denesb** [comment]
I just saw an assert-failure in shard-writer, shared ptr complains about a cross-shard free. Could be related?

**Comment by denesb** [comment]
```
seastar::debug_shared_ptr_counter_type::check() const at /home/botond/ScyllaDB/scylla/seastar/include/seastar/core/shared_ptr_debug_helper.hh:63 (discriminator 1)
seastar::debug_shared_ptr_counter_type::operator++() at /home/botond/ScyllaDB/scylla/seastar/include/seastar/core/shared_ptr_debug_helper.hh:44
seastar::lw_shared_ptr<table>::lw_shared_ptr(seastar::lw_shared_ptr_counter_base*) at /home/botond/ScyllaDB/scylla/seastar/include/seastar/core/shared_ptr.hh:261
seastar::enable_lw_shared_from_this<table>::shared_from_this() at /home/botond/ScyllaDB/scylla/seastar/include/seastar/core/shared_ptr.hh:435
repair_writer::create_writer(unsigned int)::{lambda(flat_mutation_reader)#2}::operator()(flat_mutation_reader) const at /home/botond/ScyllaDB/scylla/repair/row_level.cc:403
std::_Function_handler<seastar::future<> (flat_mutation_reader), repair_writer::create_writer(unsigned int)::{lambda(flat_mutation_reader)#2}>::_M_invoke(std::_Any_data const&, flat_mutation_reader&&) at /usr/include/c++/8/bits/std_function.h:283
std::function<seastar::future<> (flat_mutation_reader)>::operator()(flat_mutation_reader) const at /usr/include/c++/8/bits/std_function.h:687
shard_writer::consume()::{lambda(mutation_fragment*)#1}::operator()(mutation_fragment*) const at /home/botond/ScyllaDB/scylla/multishard_writer.cc:118
seastar::apply_helper<shard_writer::consume()::{lambda(mutation_fragment*)#1}, std::tuple<mutation_fragment*>&&, std::integer_sequence<unsigned long, 0ul> >::apply({lambda(mutation_fragment*)#1}&&, std::tuple<mutation_fragment*>) at /home/botond/ScyllaDB/scylla/seastar/include/seastar/core/apply.hh:35
auto seastar::apply<shard_writer::consume()::{lambda(mutation_fragment*)#1}, mutation_fragment*>(shard_writer::consume()::{lambda(mutation_fragment*)#1}&&, std::tuple<mutation_fragment*>&&) at /home/botond/ScyllaDB/scylla/seastar/include/seastar/core/apply.hh:43
seastar::future<> seastar::futurize<seastar::future<> >::apply<shard_writer::consume()::{lambda(mutation_fragment*)#1}, mutation_fragment*>(shard_writer::consume()::{lambda(mutation_fragment*)#1}&&, std::tuple<mutation_fragment*>&&) at /home/botond/ScyllaDB/scylla/seastar/include/seastar/core/future.hh:1389
_ZZN7seastar6futureIJP17mutation_fragmentEE4thenIZN12shard_writer7consumeEvEUlS2_E_NS0_IJEEEEET0_OT_ENUlSA_E_clINS_12future_stateIJS2_EEEEEDaSA_ at /home/botond/ScyllaDB/scylla/seastar/include/seastar/core/future.hh:963
seastar::continuation<seastar::future<> seastar::future<mutation_fragment*>::then<shard_writer::consume()::{lambda(mutation_fragment*)#1}, seastar::future<> >(shard_writer::consume()::{lambda(mutation_fragment*)#1}&&)::{lambda(auto:1)#1}, mutation_fragment*>::run_and_dispose() at /home/botond/ScyllaDB/scylla/seastar/include/seastar/core/future.hh:414
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /home/botond/ScyllaDB/scylla/seastar/src/core/reactor.cc:2700
seastar::reactor::run_some_tasks() at /home/botond/ScyllaDB/scylla/seastar/src/core/reactor.cc:3123 (discriminator 2)
seastar::reactor::run() at /home/botond/ScyllaDB/scylla/seastar/src/core/reactor.cc:3270
seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const at /home/botond/ScyllaDB/scylla/seastar/src/core/reactor.cc:4339 (discriminator 3)
std::_Function_handler<void (), seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}>::_M_invoke(std::_Any_data const&) at /usr/include/c++/8/bits/std_function.h:297
std::function<void ()>::operator()() const at /usr/include/c++/8/bits/std_function.h:687
seastar::posix_thread::start_routine(void*) at /home/botond/ScyllaDB/scylla/seastar/src/core/posix.cc:52
start_thread at pthread_create.c:?
__GI_iopl at :?
```

**Comment by avikivity** [comment]
@denesb yesss

**Comment by avikivity** [comment]
Well, I only see t used around view stuff, so if views aren't used, it doesn't explain it. Still a critical bug.

**Comment by denesb** [comment]
What do you mean by `t`? I saw this while playing with repair (checking that I solved the deadlocks). The pointer in question is an `lw_shared_ptr<table>`, which in theory could have been used to access sstables from the wrong core.

**Comment by denesb** [comment]
I'm not saying you are wrong, but I had just the default `scylla_bench`
schema without any views.

It looks like any component that has "multishard" in its name is doomed to
produce all sorts of nasty bugs.

**Comment by avikivity** [comment]
the use of `t` is enough to trigger the warning but shouldn't trigger the problem. Of course, maybe I missed something and the bug does explain the problem.

Certainly, crossing shards is dangerous.

**Comment by haaawk** [comment]
@avikivity @denesb @slivne @bhalevy I managed to reproduce the issue locally.

I don't think the problem is connected to cross shard usage. The mismatch is observed when the sstable is loaded so schema for that shard is used. Here is what my additional logging reported:

```
WARN  2019-01-23 17:45:09,418 [shard 0] sstable_column_translation - SSTable does not match schema during column translation.
Column translation created on shard [0]
Schema version: [d0c105be-70b9-3337-9645-c5fb748f1419].
Column id: [0]
Column name in schema: raw [c1] cql [c1]
Column name in serialization header: [c1]
Column type name in schema: [org.apache.cassandra.db.marshal.UTF8Type]
Column type name in serialization header: [org.apache.cassandra.db.marshal.UTF8Type]
Column type parsed from serialization header name: [org.apache.cassandra.db.marshal.UTF8Type]
Column type CQL name in schema: [text]
Column type parsed from serialization header CQL name: [text]
Schema type collection [0], counter [0]
Serialization header type collection [0], counter [0]
Are value compatible: [0]

WARN  2019-01-23 17:45:09,418 [shard 0] sstable_column_translation - SSTable does not match schema during column translation.
Column translation created on shard [0]
Schema version: [d0c105be-70b9-3337-9645-c5fb748f1419].
Column id: [1]
Column name in schema: raw [c2] cql [c2]
Column name in serialization header: [c2]
Column type name in schema: [org.apache.cassandra.db.marshal.UTF8Type]
Column type name in serialization header: [org.apache.cassandra.db.marshal.UTF8Type]
Column type parsed from serialization header name: [org.apache.cassandra.db.marshal.UTF8Type]
Column type CQL name in schema: [text]
Column type parsed from serialization header CQL name: [text]
Schema type collection [0], counter [0]
Serialization header type collection [0], counter [0]
Are value compatible: [0]
```

For some reason this fails:
const column_definition* def = s.get_column_definition("c1");
data_type type = db::marshal::type_parser::parse(to_sstring_view("org.apache.cassandra.db.marshal.UTF8Type"));
assert(def->type->is_value_compatible_with(*type));

Apparently type obtained from db::marshal::type_parser::parse is not value compatible with the same type in column_definition.

**Comment by avikivity** [comment]
But they're both the same type! That's why I think it's cross shard: both are utf8_type, but the objects belong to different shards, and we compare by address.

Try printing the type's address, not just the name (data_type::get()).

**Comment by haaawk** [comment]
It seems that is_value_compatible_with really checks the pointers and utf8_type_impl is value compatible only with the same instance of utf8_type_impl and the instance of asci_type_imp for the same shard.

I'm wondering how come column_definition in schema has different utf8_type_imp instance than the one returned by the parse method.

**Comment by avikivity** [comment]
That's why I suspect multishard_writer: it crosses shards, and it's involved in streaming.

**Comment by haaawk** [comment]
I think you're right @avikivity. Today I got the following error while trying to reproduce the issue:
```
ERROR 2019-01-24 08:48:22,595 [shard 1] compaction_manager - compaction failed: std::runtime_error (A regular compaction for keyspace1.standard1 INCORRECTLY used sstable /home/haaawk/.dtest/dtest-pslN52/test/node33/data/keyspace1/standard1-18713cd01fa511e99f28000000000001/mc-300-big-TOC.txt which doesn't belong to this shard!): retrying
```

**Comment by haaawk** [comment]
Here's full log from the node. 
[system.log](https://github.com/scylladb/scylla/files/2790680/system.log)

**Comment by haaawk** [comment]
@avikivity I managed to reproduce the issue again with logging of the types addresses and it seems that we're using schema which has utf8_type instance from different shard. See last 3 lines:

```
WARN  2019-01-24 11:52:20,833 [shard 0] sstable_column_translation - SSTable does not match schema during column translation.
Column translation created on shard [0]
Schema version: [7d44a3ac-cff3-3748-8f21-3f85f7efeb27].
Column id: [0]
Column name in schema: raw [c1] cql [c1]
Column name in serialization header: [c1]
Column type name in schema: [org.apache.cassandra.db.marshal.UTF8Type]
Column type name in serialization header: [org.apache.cassandra.db.marshal.UTF8Type]
Column type parsed from serialization header name: [org.apache.cassandra.db.marshal.UTF8Type]
Column type CQL name in schema: [text]
Column type parsed from serialization header CQL name: [text]
Schema type collection [0], counter [0]
Serialization header type collection [0], counter [0]
Are value compatible: [0]
Schema type address: [0x60100008d600]
Serialization header type address: [0x6000003d9720]
Current shard type address: [0x6000003d9720]
```
Going backwards:
1. Address of utf8_type on current shard is 0x6000003d9720
2. Address of utf8_type returned by parse method is the same - 0x6000003d9720
3. Address of utf8_type obtained from schema is different - 0x60100008d600

**Comment by avikivity** [comment]
Yikes. Some sharding tips:

 - the shard of an sstable is its generation % smp::count (so odd/even for this two-shard case)
 - the 8 bits of an address after 0x6 are corrlated to the shard (they aren't exactly the shard number).

**Comment by avikivity** [comment]
> Schema type address: [0x60100008d600]

so, it's using the schema from the wrong shard?

But multishard_writer appears to be doing the right thing:

```
future<> multishard_writer::make_shard_writer(unsigned shard) {
    auto this_shard_reader = make_foreign(std::make_unique<flat_mutation_reader>(make_flat_mutation_reader<queue_reader>(_s, _queues[shard])));
    return smp::submit_to(shard, [gs = global_schema_ptr(_s),
            consumer = _consumer,
            reader = std::move(this_shard_reader)] () mutable {
        auto this_shard_reader = make_foreign_reader(gs.get(), std::move(reader));
        return make_foreign(std::make_unique<shard_writer>(gs.get(), std::move(this_shard_reader), consumer));
```

**Comment by haaawk** [comment]
Would changing &cf to cf = cf.shared_from_this() fix the problem?

**Comment by avikivity** [comment]
No, it's the same cf.

We need `table* database::on_this_shard(table*)` and `keyspace* database::on_this_shard(keyspace*)`. Then instead of smp::submit_to() you would use database::invoke_on(), look up the table/keyspace on the local database instance, and use that.

**Comment by denesb** [comment]
The `table` could also be obtained based on the local `schema`. Then the capturing of `cf` is not necessary.

**Comment by haaawk** [comment]
I believe the same problem occurs in repair/row_level.cc

**Comment by haaawk** [comment]
@denesb That's right I think I will just use databas::find_column_family(reader.schema());

**Comment by avikivity** [comment]
@haaawk it looks like 3.0 is not vulnerable, do you agree?

**Comment by haaawk** [comment]
@avikivity I will double check tomorrow. Let me get back on this.

**Comment by avikivity** [comment]
Note that changes can be introduced without a trace of the commit by backporting a merge commit.

However, looking at the code, it performs the table lookup on the writer's shard, so it's correct.
