### ISSUE TITLE
ami: on first startup, user able to login before scylla-setup.service finishes

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#411]
On first startup of our AMI, user able to login the instance via SSH before scylla-setup.service finished.
I think it will done in 1min or less, but user may try to connect scylla before that, and it may fail.

Maybe we need notice about it on a document, or insert loop on .bashrc to wait startup of scylla-server.

**Comment by slivne** [comment]
DataStax ami has the same issue ... lets take a look at what they do

**Comment by lmr** [comment]
@slivne @syuu1228 I have a suggestion - what about we condition `scylla-setup.service` to run before `sshd.service`? The implementation would be simple:

    diff --git a/dist/ami/files/scylla-setup.service b/dist/ami/files/scylla-setup.service
    index fd18679..56379ba 100644
    --- a/dist/ami/files/scylla-setup.service
    +++ b/dist/ami/files/scylla-setup.service
    @@ -5,6 +5,7 @@ After=network.target
     [Service]
     Type=oneshot
     ExecStart=/usr/lib/scylla/scylla-setup.sh
    +Before=sshd.service
     RemainAfterExit=yes
     
     [Install]

**Comment by syuu1228** [comment]
This is fixed at fc29a341d2df0b32b8ca905f08baf8a05d3d9215
