### ISSUE TITLE
seastar - Exceptional future ignored: std::system_error (error system:104, Connection reset by peer)/(error system:32, Broken pipe), backtrace:

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#4117]
*Installation details*
Scylla version (or git commit hash):
- old: 2.2.1-0.20181021.7f24b5319
- new: 2.3.2-0.20190118.22c891e6d

Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

Test job: http://jenkins.cloudius-systems.com:8080/job/scylla-2.3/job/2.3-test/job/scylla-2.3-rolling-upgrade-centos-test/base_version=2.2,label=gce3-qavpc,version_desc=2-3/54/console

There are two kinds of error in draining node during rolling upgrade, the errors were raised from both the drained node and other nodes.

```
Jan 21 04:50:44 warning|  [shard 7] seastar - Exceptional future ignored: std::system_error (error system:104, Connection reset by peer), backtrace:
  0x594a78
  0x960683
  0x2c98d40
  0x2c99d19
  0x593386
  0x593541
  0x659147
  0x65fa33
  0x72ef8d
  /lib64/libpthread.so.0+0x7dd4
  /lib64/libc.so.6+0xfdeac

Jan 21 04:50:44 warning|  [shard 4] seastar - Exceptional future ignored: std::system_error (error system:32, Broken pipe), backtrace: 
  0x594a78
  0x960683
  0x2c98d40
  0x2c99d19
  0x593386
  0x593541
  0x659147
  0x65fa33
  0x72ef8d
  /lib64/libpthread.so.0+0x7dd4
  /lib64/libc.so.6+0xfdeac
```

**Comment by slivne** [comment]
@amoskong - is this a regression ? did the upgrade from 2.2.1 to 2.3.1 / 2.2.0 to 2.3.0 also have this.

What I to understand is if this is an issue due to a change in 2.3 - in which case we may work to fix this - or is happening because of a bug in 2.2 that we will not fix. 

The information you share may help to better understand this.

**Comment by amoskong** [comment]
I did see this error in original upgrade test

Shlomi Livne <notifications@github.com> 于 2019年1月24日周四 下午7:07写道：

**Comment by slivne** [comment]
@amoskong - just to verify in upgrade between 2.3 to 3.0 does this appear as well ?
