### ISSUE TITLE
hinted handoff discards hints during sending for no good reason

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#4122]
*Installation details*
Scylla version: dbc1894bd59cf50239ad97bf06c51ce47efe1257
Releases affected: any release that includes HH

*Description*
Hints are being discarded during sending because column family mapping is not found.

How to reproduce:

1. Create a 3 nodes ccm cluster: `ccm create scylla-3 --scylla --vnodes -n 3:3 --install-dir=<directory to the local scylla repo>`
2. Start it: `ccm start --jvm_arg="--memory" --jvm_arg="3G" --jvm_arg="--collectd-address" --jvm_arg="127.0.0.1:25826" --jvm_arg="--collectd" --jvm_arg="1" --jvm_arg="--default-log-level" --jvm_arg="info" --jvm_arg="--smp" --jvm_arg="3"  --jvm_arg="--logger-log-level"  --jvm_arg="hints_manager=trace"`
3. Run a cassandra-stress against it: `cassandra-stress write n=10000000 cl=ONE no-warmup -rate threads=300 -mode native cql3 -schema "keyspace=ks1 replication(factor=3)"`

Grep logs of node1 as follows:
```
$ tail -f ~/.ccm/scylla-3/node1/logs/system.log | grep "is missing" 
```

Observe a non-empty output after some time - when hints will begin to be sent.
This is not expected because there is no schema change (which could have caused such errors).

**Comment by vladzcloudius** [comment]
This is caused by a logic in out HH implementation that would send the segment not from the beginning but rather from the place it left off in the previous send attempt (in the example above this would be caused by the timeout because the receiving node is overloaded). 

In this code we cache the last replay position but do not cache the columns mappings we learned so far and would start with an empty column mappings cache the next time we try to re-transmit the segment. However commitlog framework doesn't save the corresponding column mapping in each entry and tries to optimize it and saves it once in each segment. Therefore when we start re-transmitting from the middle of a segment we may need mappings that were written in entries we have already sent.

TODO:
1. Cache column mappings together with the last replay position.
2. Add `hints.discarded` metric to account hints that are discarded during sending.

**Comment by vladzcloudius** [comment]
@slivne I already have the patch that addresses both items above. I'm going to send them tomorrow after I finish testing.

**Comment by tzach** [comment]
@vladzcloudius can you explain the user impact of this bug?
My understanding: some hints may be lost. 
Is it the case? Can we scope the effect further, to a particular condition?

**Comment by vladzcloudius** [comment]
On Tue, Jan 22, 2019, 2:20 AM Tzach Livyatan <notifications@github.com
wrote:

> @vladzcloudius <https://github.com/vladzcloudius> can you explain the
> user impact of this bug?
> My understanding: some hints may be lost.
>

Correct. Not just lost - we will have no indication about that.


Is it the case? Can we scope the effect further, to a particular condition?
>

I'm not sure I fully comprehend what do you refer as a "condition" here.
The worst impact is going to be on MV which, AFAIU relies on consistency of
HH and its metrics.

**Comment by vladzcloudius** [comment]
@elcallio I would like to ask you something: I noticed that commitlog resets column family mappings every "cycle". This means that if a segment has undergo a few "cycles" it would save information of the same CF a few times. In the use case I described above (default c-s schema) this is the case and I saw that some segments have the same cf mapping is saved ~250 times!!! 
I wonder what's the reason to save it more than once per-segment?

**Comment by vladzcloudius** [comment]
@glommer @slivne 
@elcallio ping. Could you, please, address my question above?

**Comment by glommer** [comment]
I have no idea, therefore deferring to mr @elcallio

**Comment by vladzcloudius** [comment]
@elcallio @glommer @slivne ping
