### ISSUE TITLE
Scylla cannot be connected with cqlsh

### ISSUE THREAD

**Issue by zhuxijiang** [scylladb/scylla#4123]
Hardware environment: 8 cores 32G
Scylla version: 2.1.6
the Scylla system log prompts this, and then we can't connect it with cqlsh. What's the problem?
The system logs are as follows:
Jan 21 22:06:01 scylla4 systemd: Started Session 18577 of user root.
Jan 21 22:06:01 scylla4 systemd: Starting Session 18577 of user root.
Jan 21 22:06:02 scylla4 crond: sendmail: fatal: parameter inet_interfaces: no local interface found for ::1
Jan 21 22:06:02 scylla4 systemd: Removed slice user-0.slice.
Jan 21 22:06:02 scylla4 systemd: Stopping user-0.slice.
Jan 21 22:07:01 scylla4 systemd: Created slice user-0.slice.
Jan 21 22:07:01 scylla4 systemd: Starting user-0.slice.
Jan 21 22:07:01 scylla4 systemd: Started Session 18580 of user root.
Jan 21 22:07:01 scylla4 systemd: Starting Session 18580 of user root.
Jan 21 22:07:01 scylla4 systemd: Started Session 18579 of user root.
Jan 21 22:07:01 scylla4 systemd: Starting Session 18579 of user root.
Jan 21 22:07:01 scylla4 crond: sendmail: fatal: parameter inet_interfaces: no local interface found for ::1
Jan 21 22:07:01 scylla4 systemd: Removed slice user-0.slice.
Jan 21 22:07:01 scylla4 systemd: Stopping user-0.slice.
Jan 21 22:07:20 scylla4 scylla: [shard 4] compaction - Compacting [/var/lib/scylla/data/click/common_click_android_log-659b51d0291511e89f1c000000000003/click-common_click_android_log-ka-417860-Data.db:level=0, /var/lib/scylla/data/click/common_click_android_log-659b51d0
291511e89f1c000000000003/click-common_click_android_log-ka-417852-Data.db:level=0, /var/lib/scylla/data/click/common_click_android_log-659b51d0291511e89f1c000000000003/click-common_click_android_log-ka-417868-Data.db:level=0, /var/lib/scylla/data/click/common_click_andr
oid_log-659b51d0291511e89f1c000000000003/click-common_click_android_log-ka-417844-Data.db:level=0, ]
Jan 21 22:07:22 scylla4 scylla: Reactor stalled for 2000 ms on shard 4.
Jan 21 22:07:22 scylla4 scylla: Backtrace:
Jan 21 22:07:22 scylla4 scylla: 0x00000000004a492b
Jan 21 22:07:22 scylla4 scylla: 0x00000000004a4bc1
Jan 21 22:07:22 scylla4 scylla: /lib64/libpthread.so.0+0x000000000000f5cf
Jan 21 22:07:22 scylla4 scylla: 0x0000000000a56837
Jan 21 22:07:22 scylla4 scylla: 0x0000000000b7123f
Jan 21 22:07:22 scylla4 scylla: 0x0000000000b7acb5
Jan 21 22:07:22 scylla4 scylla: 0x0000000000ae65fa
Jan 21 22:07:22 scylla4 scylla: 0x0000000000b057d3
Jan 21 22:07:22 scylla4 scylla: 0x0000000000b06f07
Jan 21 22:07:22 scylla4 scylla: 0x0000000000b06f88
Jan 21 22:07:22 scylla4 scylla: 0x0000000000bb32f1
Jan 21 22:07:22 scylla4 scylla: 0x0000000000bb349a
Jan 21 22:07:22 scylla4 scylla: 0x0000000000bb3523
Jan 21 22:07:22 scylla4 scylla: 0x0000000000b9ee86
Jan 21 22:07:22 scylla4 scylla: 0x000000000094da1b
Jan 21 22:07:22 scylla4 scylla: 0x00000000004a12f4
Jan 21 22:07:22 scylla4 scylla: 0x00000000004a15cc
Jan 21 22:07:22 scylla4 scylla: 0x00000000004f04c4
Jan 21 22:07:22 scylla4 scylla: 0x00000000004f5bb2
Jan 21 22:07:22 scylla4 scylla: 0x000000000055886d
Jan 21 22:07:22 scylla4 scylla: /lib64/libpthread.so.0+0x0000000000007dd4
Jan 21 22:07:22 scylla4 scylla: /lib64/libc.so.6+0x00000000000fdeac
Jan 21 22:07:23 scylla4 scylla: [shard 4] compaction - Compacted 4 sstables to [/var/lib/scylla/data/click/common_click_android_log-659b51d0291511e89f1c000000000003/click-common_click_android_log-ka-417876-Data.db:level=0, ]. 9263923 bytes to 8985358 (~96% of original) in 3027ms = 2.83MB/s. ~512 total partitions merged to 11.
Jan 21 22:08:01 scylla4 systemd: Created slice user-0.slice.
Jan 21 22:08:01 scylla4 systemd: Starting user-0.slice.
Jan 21 22:08:01 scylla4 systemd: Started Session 18582 of user root.
Jan 21 22:08:01 scylla4 systemd: Starting Session 18582 of user root.
Jan 21 22:08:01 scylla4 systemd: Started Session 18581 of user root.

**Comment by tzach** [comment]
@zhuxijiang note that 2.1 is not supported anymore, it is recommended to upgrade to the latest and greatest, Scylla 3.0 (2.1 to 2.2, 2.2 to 2.3, 2.3 to 3.0)

The warning itself might be related to the handling of a large partition, which was greatly improved in later releases. To check if you have a large partition, use [nodetool cfstats](https://docs.scylladb.com/operating-scylla/nodetool-commands/cfstats/#nodetool-cfstats) and check the `Compacted partition maximum bytes` value.
If the result is more than ~100MB it might be the issue

**Comment by slivne** [comment]
closing this issue since 2.1 is EOL 

@zhuxijiang - if after the upgrade to 2.3 / 3.0 there is still an issue please post and we will work to fix this
