### ISSUE TITLE
dtest paging_test.TestPagingData.static_columns_paging_test failed with too few results

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4138]
Dtest [#1009](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest/label=scylla-dtest,mode=release,smp=2/1009/)
scylla@826cf90f3f6a5d9994758e3e66051b2545fdcf5b
scylla-dtest@b03f5c1e00abfb32b03a45e93530a73abc9e16fc

Stack trace excerpt from [log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest/1009/label=scylla-dtest,mode=release,smp=2/testReport/paging_test/TestPagingData/static_columns_paging_test/):
```
Stacktrace

  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/urchin-dtest/tools.py", line 298, in wrapped
    f(obj)
  File "/jenkins/workspace/scylla-master/dtest/label/scylla-dtest/mode/release/smp/2/urchin-dtest/paging_test.py", line 736, in static_columns_paging_test
    self.assertEqual(16, len(results))
  File "/usr/lib64/python2.7/unittest/case.py", line 551, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python2.7/unittest/case.py", line 544, in _baseAssertEqual
    raise self.failureException(msg)
"16 != 15
```

paging_test.py:
```
 732         for page_size in (2, 3, 4, 5, 15, 16, 17, 100):
 733             session.default_fetch_size = page_size
 734             for selector in selectors:
 735                 results = list(session.execute("SELECT %s FROM test WHERE a = 99" % selector))
 736                 self.assertEqual(16, len(results))
```

**Comment by slivne** [comment]
One idea tzach had was that we may be returning less rows then the page requires - we do have this in the code. We need to verify that.

**Comment by slivne** [comment]
@bhalevy is this happening - if not lets close and reopen when we hit it

**Comment by bhalevy** [comment]
@slivne, no this was never reproduced.  closing...
