### ISSUE TITLE
Node to Node Encryption

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#414]
Node-to-node encryption protects data transferred between nodes in a cluster, including gossip communications, using SSL (Secure Sockets Layer).

Similar feature in Cassandra:
http://docs.datastax.com/en/cassandra/2.0/cassandra/security/secureSSLNodeToNode_t.html

**Comment by gwicke** [comment]
As privacy advocates, TLS for cross-DC traffic is high on our list of things we @wikimedia would like to see in Scylla.

**Comment by slivne** [comment]
We have client-server encryption available since 1.1 (http://www.scylladb.com/doc/tls-ssl/)
