### ISSUE TITLE
Compile scylla core into a shared library and link tests against it.

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#4142]
Test executables are ridiculously large (1.6G on my box) because each of them will include all Scylla object files, even if the test is just 2 lines long. The number of unit tests is ever growing, resulting in the situation that, even with a 377GB home partition, I can only keep around one(!!!) scylla repo that contains a full build.

I think we should try to compile Scylla into a shared library then link the test executables against it. This should theoretically drastically reduce the total size of a full build (and perhaps the time needed to produce it). I know this is not trivial, otherwise somebody would have already done it. So I opened this issue to collect all the obstacles that are preventing it, and to discuss how to remove or work around them.

**Comment by avikivity** [comment]
Shared libraries come with a performance hit. Perhaps we can make debug and dev mode shared, and keep release mode static.

**Comment by hakuch** [comment]
@avikivity, why do we care about the performance of release-mode unit tests? I would think only correctness matters.

**Comment by denesb** [comment]
Are we interested in the performance of release mode tests (apart from the stuff in `tests/perf`)?

**Comment by avikivity** [comment]
The object files have to be build to support a shared library, and that will cause them to take the performance hit. @espindola I think -fpic is not a huge concern on x86_64, but what about the TLS model? will we take a hit there?

**Comment by nyh** [comment]
@denesb About the huge tests, this is https://github.com/scylladb/scylla/issues/5 which despite being closed, has some interesting discussion. In particular it's worth noting that:
1. The tests are most ridiculously huge if compiled with debugging information. This is why we strip (or at least stripped, before the recent cmake overhaul), the debugging symbols from all tests, and only re-link it with debugging symbols when one builds a test called build/release/tests/some_test_g. 
2. The "debug" tests with sanitizers are also half huge :-(

@avikivity it would be interesting to measure the performance hit (I assume you mean the TLS overhead?) and see if it's not negligable. For development builds, definitely it's not an issue. But may even for release builds we can live with 1% performance decrease, if it's just 1% (we need to measure to make an informed decision)? Also, it might be possible to reduce the TLS overhead by somehow using it less (I don't know if it's really possible, but I said "might").

**Comment by denesb** [comment]
@nyh re: #5 it's funny to see that "ridiculously large" was 0.5G back then (with debug symbols?) and now its triple that size (without debug symbols).
In any case, if all debug tests all compiled (no debug symbols):
```
$ du -sh `find -executable`
175G    .
```

**Comment by pdziepak** [comment]
We are never going to `dlopen()` `libscylla-core.so` so we can use initial-exec TLS model which is much more reasonable than the default general dynamic: https://godbolt.org/z/pFW7Dc

I am for anything that discourages us from using globals of any kind.

**Comment by avikivity** [comment]
I don't want to leave 1% on the table. We worked hard for it.

Since we're going to have a dev build, let's focus our build-time optimizations there.

Of course, if it turns out the overhead is much lower than 1%, we can do a shared library even for release mode.

**Comment by nyh** [comment]
On Thu, Jan 24, 2019 at 5:22 PM Botond Dénes <notifications@github.com>
wrote:

> @nyh <https://github.com/nyh> re: #5
> <https://github.com/scylladb/scylla/issues/5> it's funny to see that
> "ridiculously large" was 0.5G back then (with debug symbols?) and now its
> triple that size (without debug symbols).
> In any case, if all debug tests all compiled (no debug symbols):
>
> $ du -sh `find -executable`
> 175G    .
>
>
Wow :-(

By the way, as I mentioned in the closed issue #5, in our "debug" build the
size comes not from the debug symbols (which we strip - I hope also in the
debug build... It used to be this way), but from UBSAN (see also
https://github.com/scylladb/seastar/issues/47). Which is why I rarely build
a debug build any more unless for debugging one specific test, and usually
build only "release" tests.
Of course the specific measurements are less important than adding at least
a possibility to build as a shared library. I also suggested this in #5.

**Comment by espindola** [comment]
For debug info, split dwarf could help a lot, but we need to switch to icecream since distcc doesn't support it.

On x86_64 itself, position independence itself is not a big issue. The problem are the tools :-(

-fPIC is not just "make this position independent". It is also "assume everything can be preempted at runtime". That can be solved with careful use of hidden visibility, but that is a pain if done just for tests. In theory protected visibility would be perfect for this, but the support in gnu tools is horrible.

Realistically we should keep the scylla release binary statically linked and the .o files it links with should be compiled without -fPIC, unless some benchmark can show it is not a problem.

But I agree that we should just start with the Dev build since there a shared library will be a clear win. One we have support for that it should be easy to benchmark the cost/benefit on other build modes.

**Comment by avikivity** [comment]
@espindola won't removal of -fvisibility=hidden adversly affect dev mode? Of course, we may gain more than we lose.

**Comment by espindola** [comment]
It will impact dev mode, yes. Access to local variables and functions will use a plt or got.

**Comment by espindola** [comment]
> I meant in terms of bloat. Lots of huge symbol tables.

Also true. It is probably still worth it given  what dev is for.

**Comment by bhalevy** [comment]
> For debug info, split dwarf could help a lot, but we need to switch to icecream since distcc doesn't support it.
> 
> On x86_64 itself, position independence itself is not a big issue. The problem are the tools :-(
> 
> -fPIC is not just "make this position independent". It is also "assume everything can be preempted at runtime". That can be solved with careful use of hidden visibility, but that is a pain if done just for tests. In theory protected visibility would be perfect for this, but the support in gnu tools is horrible.
> 
> Realistically we should keep the scylla release binary statically linked and the .o files it links with should be compiled without -fPIC, unless some benchmark can show it is not a problem.
> 
> But I agree that we should just start with the Dev build since there a shared library will be a clear win. One we have support for that it should be easy to benchmark the cost/benefit on other build modes.

Ref scylladb/scylla-pkg#593

**Comment by denesb** [comment]
I started looking into implementing this and found another aspect of `thread-local` storage variables. Consider `thread_local jmp_buf_link* g_current_context;` from `seastar/src/core/thread.cc` and the main thread from scylla. The `g_current_context` is initialized in the scylla executable, using the `thread-local` from the executable. When the thread starts/resumes/blocks inside a function in `libscylla-core.so`, it will use the `thread-local` from the shared-library from the respective operation, leading to a crash. I suppose we'll find many more `thread-locals` like that. So if we make `libscylla-core.so` a shared lib, we also have to make seastar a shared library to makes sure all the thread-locals therein have exactly one instance.

**Comment by denesb** [comment]
I ran an experiment in dev mode:
```
BEFORE

$ time ninja -j30 dev-build
real    13m27.847s
user    361m31.771s
sys     11m22.727s

$ du -sh ./build/dev/
5.8G    ./build/dev/

$ du -sh ./build/dev/scylla
60M     ./build/dev/scylla

$ du -sh ./build/dev/test/boost/mutation_reader_test
33M     ./build/dev/test/boost/mutation_reader_test

$ du -sh ./build/dev/test/boost/cql_query_test
33M     ./build/dev/test/boost/cql_query_test

AFTER
real    13m33.520s
user    356m25.948s
sys     10m36.809s

$ du -sh build/dev
1.2G    build/dev

$ du -sh build/dev/scylla
15M     build/dev/scylla

$ du -sh build/dev/test/boost/mutation_reader_test
5.3M    build/dev/test/boost/mutation_reader_test

$ du -sh build/dev/test/boost/cql_query_test
5.7M    build/dev/test/boost/cql_query_test
```
There is no improvement in build time, there is however a *huge* improvement in space requirement.

**Comment by denesb** [comment]
Results for a debug build:
```
BEFORE

real    23m22.818s
user    525m40.447s
sys     20m19.910s

$ du -sh ./build/debug
97G     ./build/debug

$ du -sh ./build/debug/scylla
1.7G    ./build/debug/scylla

$ du -sh ./build/debug/test/boost/mutation_reader_test
530M    ./build/debug/test/boost/mutation_reader_test

$ du -sh ./build/debug/test/boost/cql_query_test
531M    ./build/debug/test/boost/cql_query_test

AFTER

$ time ninja -j30 debug-build
real    20m11.892s
user    508m13.473s
sys     14m44.706s

$ du -sh build/debug/
22G     build/debug/

$ du -sh build/debug/scylla
420M    build/debug/scylla

$ du -sh build/debug/test/boost/mutation_reader_test
96M     build/debug/test/boost/mutation_reader_test

$ du -sh build/debug/test/boost/cql_query_test
95M     build/debug/test/boost/cql_query_test
```
Again, the build time barely improved, while storage requirement reduced by an order of 5 just like in the case of dev build.

**Comment by denesb** [comment]
Given that the main pain is build time, not storage I'm not so sure it is worth pursuing this. Opinions?

**Comment by denesb** [comment]
I think we should look into https://github.com/scylladb/scylla/issues/9155 instead of this.

**Comment by denesb** [comment]
Closing as I think this path is not worth pursuing, reopen/comment if you disagree.
