### ISSUE TITLE
Bad permissions on scylla_io_setup files

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#4157]
A user reported today, on Scylla 3.0, that Scylla would crash with the following message:

```
Could not initialize seastar: YAML::BadFile (yaml-cpp: error at line 0, column 0: bad file)
```

Upon investigation, turns out that this was because the permission of files in /etc/scylla.d looked like this:

```
:/etc/scylla.d$ ls -l
total 20
-rw-r--r-- 1 root root 114 Jan 20 12:33 cpuset.conf
-rw-r--r-- 1 root root 118 Jan 20 12:33 dev-mode.conf
-rw-r--r-- 1 root root  35 Jan 27 22:47 housekeeping.cfg
-rw-r--r-- 1 root root  86 Jan 27 22:49 io.conf
-rw-r----- 1 root root 147 Jan 27 22:49 io_properties.yaml
```

1) Why are those files owned by root and not whichever user Scylla is configured to use ? (Keeping the rootless installs in mind, we should be able to choose which user is that in the command line of scylla_setup)

2) Why is it that io_properties.yaml is created as 0640 ? This is certainly not the case in all systems, so my best bet is that we're not explicitly setting the property and end up being harmed by the system's default umask.

**Comment by mailmahee** [comment]
This customer is running Scylla on Ubuntu 16.04 
downloading the binaries from - https://www.scylladb.com/download/ubuntu-16-04/

**Comment by glommer** [comment]
We are hitting this pretty constantly. I am moving tiering this issue. Please prioritize

**Comment by tzach** [comment]
Running Ubuntu 16 install I get a similar result, except  io_properties do have the same as the others.

```
 sudo ls -l /etc/scylla.d/
total 20
-rw-r--r-- 1 root root 137 May 30 06:04 cpuset.conf
-rw-r--r-- 1 root root 118 May 27 07:30 dev-mode.conf
-rw-r--r-- 1 root root  35 May 30 06:03 housekeeping.cfg
-rw-r--r-- 1 root root  85 May 30 06:06 io.conf
-rw-r--r-- 1 root root 144 May 30 06:06 io_properties.yaml
```

Still, Scylla is up and running with no problems.
Why do you think permission is related to the original `Could not initialize seastar` problem?

**Comment by glommer** [comment]
Tzach, the message we got was bad yaml, indicating the yaml could not be read.
It can't be read because the permissions are wrong.
And when we fix it, then it works.

**Comment by syuu1228** [comment]
Seems like io_properties.yaml mistakenly becomes 0640 on some condition, that the reason why Seastar getting the error.
I think I had tried to reproduce the issue and I never succeed, but trying it again now.

**Comment by glommer** [comment]
The reason is that those systems have a different umask than the default. If you set the umask to a more restrictive value you will reproduce it. However when I talked to Avi, if I recall correctly, his wish was that instead of messing with umask or explicit permissions we should just get those files owned by scylla (that would work too)

**Comment by syuu1228** [comment]
Okay now I able to reproduced it.
@glommer @avikivity I think we also can solve the issue by re-setting umask inside scylla_io_setup script, but changing owner to scylla is better than that?

```
root@ip-172-16-99-36:/etc/scylla.d# umask 026
root@ip-172-16-99-36:/etc/scylla.d# scylla_io_setup 
tuning /sys/devices/vbd-768/block/xvda/xvda1
tuning /sys/devices/vbd-768/block/xvda
already tuned: /sys/devices/vbd-768/block/xvda/queue/nomerges
INFO  2019-05-30 06:38:28,054 [shard 0] iotune - /var/lib/scylla/data passed sanity checks
WARN  2019-05-30 06:38:28,055 [shard 0] iotune - Scheduler for /sys/devices/vbd-768/block/xvda/queue/scheduler set to deadline. It is recommend to set it to noop before evaluation so as not to skew the results.
Starting Evaluation. This may take a while...
Measuring sequential write bandwidth: 132 MB/s
Measuring sequential read bandwidth: 130 MB/s
Measuring random write IOPS: 3305 IOPS
Measuring random read IOPS: 3061 IOPS
Recommended --num-io-queues: 1
Writing result to /etc/scylla.d/io_properties.yaml
Writing result to /etc/scylla.d/io.conf
root@ip-172-16-99-36:/etc/scylla.d# ls -l
total 20
-rw-r--r-- 1 root root 114 May 27 07:30 cpuset.conf
-rw-r--r-- 1 root root 118 May 27 07:30 dev-mode.conf
-rw-r--r-- 1 root root  35 May 27 07:30 housekeeping.cfg
-rw-r----- 1 root root  85 May 30 06:40 io.conf
-rw-r----- 1 root root 127 May 30 06:40 io_properties.yaml
root@ip-172-16-99-36:/etc/scylla.d# systemctl start scylla-server
root@ip-172-16-99-36:/etc/scylla.d# journalctl |grep seastar
May 30 06:43:13 ip-172-16-99-36 scylla[8919]: Could not initialize seastar: YAML::BadFile (yaml-cpp: error at line 0, column 0: bad file)

```

**Comment by glommer** [comment]
all of those files in scylla.d should be owned by scylla

**Comment by syuu1228** [comment]
Okay will post the patch to do this.

**Comment by glommer** [comment]
@syuu1228 please keep in mind that some users change the USER variable to run scylla as some other user. We should make those files owned by whoever user Scylla is configured to run under.

I also personally don't mind making those files readable by everybody inside iotune

**Comment by syuu1228** [comment]
@glommer If user modified Scylla user and also changed umask, then we will get same problem again. To avoid this, I think we have to set umask even after we changed owner of /etc/scylla.d/* to scylla, anyway.

Also, note that we hardcoded 'User=scylla' on systemd unit file, so $USER variable does not affect https://github.com/scylladb/scylla/blob/master/dist/common/systemd/scylla-server.service.mustache#L29

**Comment by glommer** [comment]
users can and do change the systemd unit file to run scylla as other users.

**Comment by syuu1228** [comment]
Posted a patchset "[PATCH scylla 0/3] Switch /etc/scylla.d owner to scylla user"
