### ISSUE TITLE
Improve compaction by dropping earlier fully expired sstable which meets overlapping criteria

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#4159]
Fully expired sstable which contains no data that will cause resurrection can be dropped as early as the compaction start, which will improve a lot the disk space requirement for time series use cases. Right now, we hold them till the compaction finishes. Compaction already gets list of fully expired sstables, so we only need to provide them to incremental compaction machinery which allows early replacement of exhausted sstables.

**Comment by raphaelsc** [comment]
@bhalevy could u please assign this to me? i won't be working on it anytime soon though

**Comment by slivne** [comment]
Does TWCS/DTCS suffer from this as well ? do we drop fully expired sstables in a separate compaction or early on.

**Comment by bhalevy** [comment]
@slivne did you intend to close this issue?

**Comment by raphaelsc** [comment]
@slivne in the end of current compaction. there may be a mix of fully and partially expired ssts in the same compaction procedure
