### ISSUE TITLE
Multiple CONTAINS restrictions for one column are not handled properly

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#4161]
*Installation details*
Scylla version (or git commit hash): master (ea34e242d)

~~Currently, SELECT statement restrictions for a single column are kept in a map `column_definition -> restriction`. That usually makes sense, but it should also be possible and valid to apply multiple `contains` restrictions to a single collection column.
What's more, CQL layer happily accepts statements like:~~
~~~
SELECT * FROM t WHERE l contains 1 and l contains 2 ALLOW FILTERING;
~~~
~~but only first of these restrictions will be applied and used in filtering, because of the map's capacity to hold only one restriction per column.~~

~~Long story short, internal data structure that keeps single column restrictions should act like a multimap and be able to store multiple values (for at least `contains` restrictions) per one column.~~

The actual issue is the code which validates a `CONTAINS` restriction against a collection - it erroneously just checks for the first one.

**Comment by duarten** [comment]
Or `contains` restrictions should be mergeable, and specify a set of values that the collection must contain (`l contains (1 and 2)`), which is what I think we do for other restrictions.

**Comment by psarna** [comment]
Reproducer (select clauses are semantically identical, but they return different results since only the first restriction is applied):
~~~
CREATE TABLE t1 (id int PRIMARY KEY, l list<int>);
insert into t1 (id, l) values (1, [1,2,3]);
insert into t1 (id, l) values (2, [1,3]);
SELECT * from t1 WHERE l CONTAINS 1 AND l CONTAINS 2 ALLOW FILTERING;
SELECT * from t1 WHERE l CONTAINS 2 AND l CONTAINS 1 ALLOW FILTERING;
~~~
