### ISSUE TITLE
Reuse temporary_buffer when reading from the commitlog

### ISSUE THREAD

**Issue by duarten** [scylladb/scylla#4163]
We read from the commitlog file into a newly allocated temporary buffer, which is deserialized into a `commitlog_entry`. We could reuse the same temporary buffer. `read_log_file()` could specify that the buffer is up for grabs when the future returned by the caller-supplied callback is resolved, by passing the buffer by reference instead of by value.

**Comment by elcallio** [comment]
I don't quite understand what you are getting at. 
The commitlog reader code uses a `fragmented_temporary_buffer::reader` to read each entry. These are by the design of the reader returned by value. Forwarding them to the actual replayer by reference would not make any difference beyond forcing the reader to put them in unique_ptr and keep until callback is over.

**Comment by duarten** [comment]
Reading the code again, I don't remember what I was getting at either :(
