### ISSUE TITLE
Do not compile iotune when it is not asked for

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#4165]
When compiling scylla with:

   ./configure.py  --mode release  --with scylla
   ninja-build

I saw iotune is always built:

   build/release/apps/iotune/iotune

During development, we do not need it most of the time.

**Comment by espindola** [comment]
It looks like we used to build all seastar artifices with a single ninja invocation to avoid having two ninja process running in parallel.

The real fix was to add a pool of size one. With that done it does look like we can avoid building iotune unconditionally.

**Comment by avikivity** [comment]
Note that the pool of depth 1 was added to fix a build bug (which I think no longer exists), building dpdk in the source rather than target directory.
