### ISSUE TITLE
compaction failed: A regular compaction for ks.cf INCORRECTLY used sstable which doesn't belong to this shard!

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4181]
Scylla version 4537ec7426b3fe13d94f59b8c3dabd4f2179ea58

Seen in [update_cluster_layout_tests.TestLargeScaleCluster.add_50_nodes_test/node32.log #1005](http://jenkins.cloudius-systems.com:8080/job/scylla-master/job/dtest/label=scylla-dtest,mode=release,smp=2/1005/artifact/urchin-dtest/logs-release.2/1547865657196_update_cluster_layout_tests.TestLargeScaleCluster.add_50_nodes_test/node32.log):
```
INFO  2019-01-19 04:40:32,582 [shard 1] compaction - Compacting [/jenkins/.dtest/dtest-Z97tyg/test/node32/data/ks/cf-b09a62b01b8c11e9a75a000000000001/mc-69-big-Data.db:level=0, /jenkins/.dtest/dtest-Z97tyg/test/node32/data/ks/cf-b09a62b01b8c11e9a75a000000000001/mc-105-big-Data.db:level=0, /jenkins/.dtest/dtest-Z97tyg/test/node32/data/ks/cf-b09a62b01b8c11e9a75a000000000001/mc-100-big-Data.db:level=0, ]
...
ERROR 2019-01-19 04:40:32,613 [shard 0] compaction_manager - compaction failed: std::runtime_error (SSTable write failed due to existence of TOC file for generation 100 of ks.cf): retrying
...
ERROR 2019-01-19 04:40:32,750 [shard 1] compaction_manager - compaction failed: std::runtime_error (A regular compaction for ks.cf INCORRECTLY used sstable /jenkins/.dtest/dtest-Z97tyg/test/node32/data/ks/cf-b09a62b01b8c11e9a75a000000000001/mc-100-big-TOC.txt which doesn't belong to this shard!): retrying
...
and keeps retrying until the node hits (unrelated, I think) oversized allocation

**Comment by bhalevy** [comment]
The oversized allocation issue is #4180

**Comment by raphaelsc** [comment]
I think this is indeed a regression. The problem cannot be easily reproduced, so I'll come up with a solid theory instead and see if i can find the bug.

**Comment by slivne** [comment]
Lets try to run this in debug mode (reduce the 50 nodes to be 10) and see if we can find (by luck) a bug

**Comment by slivne** [comment]
@bhalevy did we stumble on this more then once ?

**Comment by bhalevy** [comment]
> @bhalevy did we stumble on this more then once ?

@slivne no, hit once and never reproduced.  We also didn't find any valid way this could have happened by the existing code, so this might have been a spurious memory corruption.  I suggest closing this issue until reproduced.
