### ISSUE TITLE
Add counter for system table queries

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4182]
Queries to system tables have multiple sources:
- some are internal from inside scylla
- some are done from client drivers 

We need to count these queries to be able to distinguish them from client application queries for optimization information https://github.com/scylladb/scylla-grafana-monitoring/blob/master/grafana/scylla-cql-optimization.master.template.json

**Comment by jul-stas** [comment]
The link does not work for me, but that's no big deal atm. Now be warned: lame questions ahead. 

- So we need a counter (or `cql_stats`? other `stats`?) for "internal queries to system tables" - is that right?
- What is the desired granularity? (e.g. one counter for whole sys KS/node/table/..?). Similar example would be appreciated.
- I'm looking into `seastar::metrics` in `query_processor` (is this a correct approach?), but cannot see a way to distinguish queries that come from internal components. Can anyone guide me to a proper example? This looked promising but is obviously commented out:
```
#if 0
        if (!queryState.getClientState().isInternal)
            metrics.regularStatementsExecuted.inc();
#endif
```

**Comment by slivne** [comment]
A bit more information on why we need this.

In the CQL Optimization dashboard we have a pane showing the user that the are non prepared statement queries, and advise him that 100% of the queries should be prepared. The simplified formula is looking at scylla_query_processor_statements_prepare/ (scylla_cql_reads+inserts+updates+deletes). 
The user does not have full control on all scylla_cql_reads - some of them are driver generates and as such are not prepared. 

This is especially misleading when there is no client traffic and it seems that 100% percent of the requests are not prepared (yet the source of that is that all the queries are driver generated).

So we need to count the number of scylla_cql_reads that have been directed to system tables - scylla_system_cql_reads and then be able to have the update formula.

scylla_query_processor_statements_prepare/ (scylla_cql_reads-scylla_system_cql_reads+inserts+updates+deletes).

With regards to internal system table queries - we have some internal queries being done for system keyspaces (system, system_schema, system_auth, system_distributed), those queries are at times a source for system issues (hot nodes / shards for pulling non replicated system_auth information as an example). We need to detect and count internal system table replica reads.
