### ISSUE TITLE
Scylla does not include schema.cql file in snapshot folder

### ISSUE THREAD

**Issue by Kvikal** [scylladb/scylla#4192]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.2-0.20190131.5174b1cd1
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04

Cassandra provides schema.cql file in snapshot folder (for each table, next to SSTables and others), that describes the schema at the time of the snapshot.
Scylla does not behave this way.

This functionality makes backup/restore on Cassandra easier and should probably be part of Scylla as well.

**Comment by slivne** [comment]
@eliransin - I want to prioritize this - scylla-manager will provide backups and this is needed

**Comment by mmatczuk** [comment]
@eliransin any update on that? This is blocking for manager backup. Manager does not have access to CQL by design and will not take schema snapshots. This should be done automatically anyway.

cc @tzach

**Comment by amnonh** [comment]
Schema is generated by the driver, as a reference see:
https://github.com/datastax/java-driver/blob/4.x/core/src/main/java/com/datastax/oss/driver/api/core/metadata/schema/TableMetadata.java

**Comment by tzach** [comment]
Apache Cassandra correlating feature https://issues.apache.org/jira/browse/CASSANDRA-7190
Fix Version/s: 3.0.9, 3.10

**Comment by mmatczuk** [comment]
@amnonh please check https://github.com/apache/cassandra/blob/f9b46aeb3123e3d387837aa8525126b0a450851b/src/java/org/apache/cassandra/db/ColumnFamilyStore.java#L1738
