### ISSUE TITLE
Bootstrapping node doesn't wait for schema before joining the ring

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4196]
This means the node will receive writes before it has an up to date schema. This normally isn't a big problem, because writes will force schema pull when the table is missing. However, user-defined types are currently not pulled, so this bug exposes https://github.com/scylladb/scylla/issues/3760.

Evidence from the log that schema is not synced:

```
Feb 05 02:22:11 [shard 0] storage_service - JOINING: waiting for ring information
Feb 05 02:22:11 [shard 0] storage_service - JOINING: schema complete, ready to bootstrap
```

There's a check inside `have_schema_agreement()` which makes the node think it has complete schema if it doesn't see other nodes:
```
    if (known_endpoints.size() == 1) {
        // Us.
        return true;
    }
```

This is a change in behavior introduced in 3e415e28bc71701a4f96e40a45244a33aef0db5b (2.3.0).

The check for ring information is also a no-op because `_db.local().get_version()` is set 
 and thus not `database::empty_version` much earlier in the boot (when internal tables are created):
```
        set_mode(mode::JOINING, "waiting for ring information", true);
        // first sleep the delay to make sure we see all our peers
        for (int i = 0; i < delay; i += 1000) {
            // if we see schema, we can proceed to the next check directly
            if (_db.local().get_version() != database::empty_version) {
                slogger.debug("got schema: {}", _db.local().get_version());
                break;
            }
            sleep(std::chrono::seconds(1)).get();
        }
```

**Comment by slivne** [comment]
@tgrabiec if a new node is added to the cluster and the new node is not a seed node will it be able to hit the issue  ?

In your view - should we force bootstrapping non seed nodes to pull schema before doing anything else ?

With regards to pulling UDTs, its clear we need to add this - yet I hope the solution above is simpler to implement.

**Comment by tgrabiec** [comment]
The issue applies to non-seeds.

Yes, I think a bootstrapping node should sync the schema before proceeding. The procedure was already trying to do this, just wasn't working as intended.
