### ISSUE TITLE
When uploading from scyllla 2.3 to 3.0 need to remove node_exporter

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#4197]
Also relates to #4195
Scylla versions older than 3.0 uses node_exporter 0.14.

Scylla 3.X uses node_exporter 0.17.

While there is no limitation of using any of the versions, the service file for the node-exporter comes with scylla and is different.

This means that after an upgrade node_exporter will still be 0.14 but its service file will be 0.17 (See #3989)

The best approach will be to remove the node_exporter and run node_exporter_install to install node_exporter 0.17.

**Comment by slivne** [comment]
@tzach ?

**Comment by tzach** [comment]
Its a shame we did not document this as part of the upgrade process.
But we can still do that. @amnonh can you please open a doc issue for
https://docs.scylladb.com/upgrade/upgrade-opensource/upgrade-guide-from-2.3-to-3.0/
and send a PR?

**Comment by amnonh** [comment]
I already open an issue on the docs, see the referenced issue

**Comment by slivne** [comment]
#4201 to solve this
