### ISSUE TITLE
MC sstable format is not enabled correctly for the whole cluster

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#4205]
The process has to have multiple stages:
1. All nodes in the cluster have to support MC_SSTABLE_FEATURE
2. When a node observes that whole cluster supports MC_SSTABLE_FEATURE then it should start using MC format. This should be done by setting local USING_MC_SSTABLES_LOCAL_FEATURE flag.
3. Once all shards start to use MC then a node should broadcast that it is using MC by setting USING_MC_SSTABLE_FEATURE flag
4. Once whole cluster supports USING_MC_SSTABLE_FEATURE flag we can start accepting MC features on CQL level.

**Comment by nyh** [comment]
I have two ignorant questions:
1. Why does the sstable format needs to be identical across the whole cluster? Isn't the sstable format internal to a node, and it communicates with other nodes and with clients using different protocols, that have nothing to do with the sstable format?
2. If there are "MC features on the CQL level" (what are these?), is it enough that all nodes decided to write new data in MC format? What if we still have old sstables in older formats? What will those MC CQL (?) requests do with them?

**Comment by haaawk** [comment]
For example open-ended range tombstones can't be represented in formats below MC. This means we can now support them but only after every node starts to support MC.

**Comment by nyh** [comment]
Yes, I had a hunch that this is this was probably the example. But still, what if "every node starts to support MC" but most of the sstables were pre-existing in older formats, will this work? I'm trying to think if "every node supports MC" really guarantees anything.

**Comment by haaawk** [comment]
Old sstables are not a problem. They are immutable and they don't have any open-ended range tombstones. Compactions will be writing MC sstables since a node uses MC so every new request will be handled by MC code. Old sstables are just old data that's compatible both with MC and formats older than MC.

**Comment by bhalevy** [comment]
Refs #4113, #3913
