### ISSUE TITLE
remove, rebuild, replace, are not safe and can stream stale data, causing QUORUM queries to return wrong results

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#4208]
(edited: as per discussion with @slivne , add itself seems safe)

Current operations like ~~add~~, remove and rebuild will stream data from one of the replicas only.

It is possible that if the cluster is not fully repaired that the replica that has stale data ends up transferring.
After a sequence of ~~adds~~ (removes) within the same time window without repair, you can end up with no data at all.
Things are even worse if we consider that the cluster will have ongoing writes. We will repair some ranges, but could very well transfer a range that was written to after it was repaired -- meaning that we now need a repair both before & after streaming.

If we really need to ask for repairs in between streaming operations then it would be easier to just pay the price of consulting more replicas upfront to make sure we have up2date data. An option can still be given to people who want faster repairs to do so, but it should in no way be the default. By default we should touch all live replicas to stream to guarantee those operations are always safe.

**Comment by tzach** [comment]
@glommer till this is fix, I understand that running a repair as a prerequisite to the above operation will mitigate the issue. Please comment.

**Comment by slivne** [comment]
I do not agree with all that is stated:

- Add node is a safe operation - it transfers ownership from one node to another - doesn't stream from a random node  - so inconsistency (if there is any will be kept).
- Rebuild operation does what it claims todo - streams information from one other replica to this replica. If there are inconsistencies they are kept not increased. 

- Remove node is not safe and should have repair added - but that should be done prior to removenode not after !!!!

**Comment by glommer** [comment]
Let's get clarification about the first bullet then.

About the second and third, "it does what it is supposed to do" is pointless if what is supposed to do is unsafe. We should then change what it is supposed to do.

rebuild should stream the most up2date copy.
remove should stream the most up2date copy. 

The only way to get those two operations (for now) to be safe is to run repairs before you trigger them. If that's the case they should do the repair themselves (or just do the transfers with increased consistency-level).

While it doesn't we should definitely state it in the documentation that those are needed. But "they do what they are supposed to do" is a poor excuse for a badly designed operation.

**Comment by slivne** [comment]
If the user does rebuild he will not get the node to a worse state then it was

Consider the current state: 3 nodes RF=3

Node A: correct data
Node B: old copy T1
Node C: old copy T2 (T2 < T1)

If the user reads at this state with QUORUM he can get the correct value if Node A is read from or can get old copy T1 (if Node B,C are used in the read).

If the user runs rebuild on Node C:
- If node A is used then Node C will be updated to the correct data 
- if node B is used then Node C will receive "old copy T1"

Quorum reads will be kept as they are.

No one claimed that rebuild will repair the replica - there is a command called repair for that  - I am not sure why someone would expect rebuild todo a repair - if the user wants to repair he should run repair not rebuild.

There are specific cases in which rebuild should be used - when adding a DC for example. 

A user selecting to use rebuild is expected to know why he is doing that vs using a repair

**Comment by glommer** [comment]
Shlomi, that's not true:

Node A : correct data
Node B: old copy
Node C: correct data

Node C dies and the user runs rebuild (or replace) on node C:

* If node B is used, now we have two copies of old data.
Quorum queries that hit B and C will return stale data.

If rebuild is used to stream to a new datacenter: it is entirely possible that all 3 replicas in the new DC will stream from a stale replica and no node in that datacenter will have the new data until a repair

Please stop saying that "this is how it works" and "the user is expected to know".

I know this is the current behavior. What I am saying is that the current behavior SUCKS, is unsafe, easy to get wrong, and we should make those things easier, safer and hassle free.

Not trying to shift the blame by being able to point to a draconian procedure and saying "the user should know better".

**Comment by slivne** [comment]
Ok ...

Now I understand better the use case - a node is booted without any data and the user does a replace/rebuild.

**Comment by vladzcloudius** [comment]
@slivne Do we always stream from the primary replica? If not then we DO have an issue and the fact that we "change the ownership" doesn't change that.

Think of the following example:

RF=3. Writes with CL=QUORUM.
One non-primary replica has "old" data. 
If the data is streamed from the replica that has the old version of data then after streaming there's going to be 2 replicas with "old" version and one with the "new" one (since a primary replica is a new node now).

After that a READ with CL=QUORUM may deliver the "old" data (if the replica with the "new" version of data goes down for instance).

BUM!!!

**Comment by slivne** [comment]
There is no notion of primary replica being more up to date in Scylla / Cassandra - we need to solve this - one way to solve this is to stream all replicas - but I think there are other alternatives

 1. for remove node - to run a repair on the replicas for ranges that are going to be streamed and then do the streaming
 1. for replace node - run repair after streaming from a replica and then make the node alive

streaming from all replicas maybe be techincally simpler but has a cost ....

**Comment by glommer** [comment]
The cost of streaming from all replicas is unlikely to be more than doing a repair (which may stream from all replicas) and then streaming.

I liked the idea Avi had last time we discussed this: also allow a consistency level to be set for those operations (glauber's addendum: default to quorum).

If you want those operations to be unsafe because you're cool with low consistency anyway, tune it to CL=one

**Comment by slivne** [comment]
If streaming is not more expensive than repair then why not do that always and not repiar. Streaming that writes directly to sstables has the side effect that you need to compact the sources (unlesss we want to invent the wheel again and do streaming in parallel from multiple sources)

With partition level repair and large rows - its arguable. With row level repair it will not be.

**Comment by avikivity** [comment]
Streaming and repair are efficient at different points. Streaming is more efficient when one node has no data. Repair is more efficient when the nodes are very close to each other.

Stream from one replica + repair is the most efficient, but leaves a window with reduced consistency of we streamed from an old replica. Streaming from all replicas is more expensive, can be reduced by merging before writing.

**Comment by slivne** [comment]
On Wed, Feb 13, 2019 at 11:03 AM Avi Kivity <notifications@github.com>
wrote:

> Streaming and repair are efficient at different points. Streaming is more
> efficient when one node has no data. Repair is more efficient when the
> nodes are very close to each other.
>

We are focusing here on two specific operations

rebuild and replace node

In both cases there will be a need to stream a complete replica to the node
(or repair would have been done). The question is how to make the node in
synch (should additional streaming be done or repair pre/post)

> Stream from one replica + repair is the most efficient, but leaves a
> window with reduced consistency of we streamed from an old replica.
>
For replace node - if we bring the node up to be online after streaming and
before repair thats true. But if we hold the node in joining state till
repair ends - there will be no such window.

For rebuild - the node is up it receives read and writes - the
inconsistency  window exists in both cases.

> Streaming from all replicas is more expensive, can be reduced by merging
> before writing.
>

Thats another rehawl - streaming from multiple replicas merging in memory
and then writing to sstables (without using memtables - we do not have that
today).

We can of course make the stream+repair more optimized - stream from one
replica and than repair against the other replica and only then write. But
we do not have this capability today as well.

**Comment by glommer** [comment]
Just a reminder that we are talking about remove as well, not just replace / rebuild.
It has the same issue. But it is also the case that it will be transferring the entire set of tokens to a new replica so the same considerations about speed apply
