### ISSUE TITLE
installing from RPM on Fedora22: scylla-tools require scylla-server

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#421]
scylla-tools is unnecessarily depend on scylla-server
```
$ sudo dnf install scylla-tools-0.9-20150924.86671d1.fc22.noarch.rpm
Last metadata expiration check performed 0:03:58 ago on Wed Sep 30 06:15:54 2015.
Error: nothing provides scylla-server needed by scylla-tools-0.9-20150924.86671d1.fc22.noarch
```

**Comment by slivne** [comment]
origins cassandra-tools requires cassandra as well

there are items that we need from scylla rpm (mainly the scylla.yaml at
this point)

i think we should keep this dependency at thos point  to make things
simpler and to make sure installation and usage are consistent

**Comment by tzach** [comment]
Why is the yaml required?
This make installing cassandra-stress from scylla-tools unnecessary complex.
In many cases, cassandra-stress is all required on a server.

**Comment by slivne** [comment]
why they require it is a good question - we inheritted this dependency, did
not create it, while we can go and try to resolve this i dont think we
should

i think its not cassandra-stress that requires it rather nodetool

**Comment by avikivity** [comment]
There's no need to copy origin bugs.

Even nodetools shouldn't require it.

**Comment by slivne** [comment]
We are not copying them we are taking their code - do we want to start
updating such items - at this point it seems to me like a waste of time and
it will also be harder afterwords to import updates they do.

**Comment by slivne** [comment]
I think there is a real reason nodetool uses it.

When you run nodetool on the same host as scylla you do not need to specify
the ip - it is taken from the config,
if we remove this then when you run nodetool you will need to specify ip in
all cases when the localhost is not listened on.

Yes we can make the code better and check if the file exists - etc ... yet
is it worth it.

**Comment by avikivity** [comment]
I don't understand.  Of course if I run on a remote node I need to specify the IP, but why does there have to be an rpm dependency?

**Comment by slivne** [comment]
There are two deployment types

1. install on the same server as scylla (what we do on the ami as an
example).

In such a case running nodetool locally on the same server as scylla,
nodetool will go and fetch from the yaml file the info about which ip
address scylla is listening on and will connect directly without the need
of specifying the ip.

2. install on different server and connect remotely - in this case you must
specify the ip.

nodetool tries to access the cassandra.yaml (scylla.yaml) in both case.

**Comment by syuu1228** [comment]
What is correct solution for it?
Maybe we can just remove rpm dependency, user will have responsibility to provide scylla.yaml to nodetool?

**Comment by slivne** [comment]
Create a scylla.core that holds the base for all

Avi, gleb i think this was your preferred solution

**Comment by syuu1228** [comment]
If we move scylla.yaml to scylla-core package, it will cause file conflict when user try to upgrade from previous version, they have to uninstall previous version then install again. Is it okay?
I suppose if there's no way to prevent it, we should do it now. Doing it on post GA, it would be more harmful.

**Comment by slivne** [comment]
The scylla.yaml should survive upgrades .... if this is not possible with a
scylla.core package thenthe additional package is a bad solution

gleb ?

**Comment by avikivity** [comment]
No, rpm will be able to upgrade with this, I don't think it's a problem.

Package should be called scylla-conf.  (and we should have a package called scylla that pulls in scylla-server, scylla-jmx, and scylla-tools).

**Comment by avikivity** [comment]
I think it can be done by having scylla-conf do

    Obsoletes: scylla-server < scylla-server-0.17

but I'm not 100% sure

**Comment by syuu1228** [comment]
This is marked as post 1.0, but isn't it better to do now?
After we released, probably it become more difficult to do such big change on packages.

**Comment by benoit-canet** [comment]
I created the configuration file package and the meta package as separate .spec files since I am not fan at all of big clutered spec files.

As expected by @syuu1228 a file conflict arise when installing scylla-conf.

I tried the Obsolette tag in vain as @avikivity suggested it.

After an intense googling session I found:
https://en.opensuse.org/openSUSE:Package_dependencies#Replace_a_package_by_another_with_the_same_functionality "splitting and merging".

From this document the solution would be to put "Provides: scylla-server:/etc/scylla/scylla.yaml" in the scylla-conf spec file header. I tried that and it does not work either.

So I come with this very pragmatic idea of instructing the user to make use of rpm --replacefiles if upgrading from <= 1.0. It would work fine because if the file already exists the new one is prefixed .rpmnew.

What do you think about it ?
