### ISSUE TITLE
Auto-expand replication_factor for NetworkTopologyStrategy

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#4210]
Scylla version (or git commit hash): 3.0

Apache Cassandra add an option for using `replication_factor` with `NetworkTopologyStrategy` so, **each** DC have the same RF (for example 3):

```
 CREATE KEYSPACE test WITH replication = {'class': 'NetworkTopologyStrategy', 'replication_factor': 3}
```
https://issues.apache.org/jira/browse/CASSANDRA-14303

Pros:
* decoupled DC names from the schema. 
* no need to update RF when adding new DCs
* C* comptability

Cons:
* easy to miss the RF will apply to all clusters.

**Comment by tzach** [comment]
Can be used for system_auth https://github.com/scylladb/scylla/issues/1796

**Comment by haaawk** [comment]
Please add all relevant Cassandra dtests to our dtests and maybe write some new.

**Comment by tzach** [comment]
Closing. @kbr- please use the "Fix #4210" syntax in PR, so merge will close the issue automatically

**Comment by tzach** [comment]
@kbr- is the RF extends to an added DCs?
AFAIU, it is for https://issues.apache.org/jira/browse/CASSANDRA-14303

**Comment by kbr-** [comment]
@tzach when we:
1. Add a new datacenter,
2. Run ALTER KEYSPACE and provide 'replication_factor',

it will expand the option to this new datacenter too.

But RF won't be set automatically for this keyspace just because a new DC started existing.

**Comment by tzach** [comment]
Thanks @kbr- 

- Is it different than Apache Cassandra?
- ALTER KEYSPACE to what? if it is already `{'class': 'NetworkTopologyStrategy', 'replication_factor': 3}` what should I change to apply RF=3 to the new DC?

**Comment by kbr-** [comment]
1. It's the same
2. run ALTER KEYSPACE with the same option: {'class': 'NetworkTopologyStrategy', 'replication_factor': 3}. It will expand to DCs that exist at the moment of executing ALTER KEYSPACE.

Example:


Suppose we have a single datacenter, 'dc1'.
We run CREATE KEYSPACE with {'class': NTS, 'replication_factor': 3}.
It expands to {'class': NTS, 'dc1': 3}.

Then we bootstrap a node in a different datacenter, 'dc2'.
The keyspace's replication option is still {'class': NTS, 'dc1': 3} (INSPECT will show it).

Then we run ALTER KEYSPACE with {'class': NTS, 'replication_factor': 3}.
It expands to {'class': NTS, 'dc1' : 3, 'dc2': 3}.

**Comment by tzach** [comment]
Thanks
Running the same `ALTER KEYSPACE with {'class': NTS, 'replication_factor': 3}`
twice (or more) and getting different results every time seems anti-intuitive.

**Comment by kbr-** [comment]
Maybe.

'relication_factor' was only meant to be used with SimpleStrategy in the first place, it didn't make sense for NTS.

That's why it requires clear documentation to explain exactly what happens. Maybe the example helps.
