### ISSUE TITLE
Annoying message on i3.large: scylla_prepare[4973]: ERROR: Bad configuration mode (sq_split) and cpu-mask value (0x00000003): this results in a zero-mask for compute. Your system can't be tuned until the issue is fixed.

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#4211]
*Installation details*
Scylla version: 3.0.2
Cluster size: 1

*Hardware details*
Platform: AWS i3.large

*Description*
`scylla-server` service is able to start but there is an annoying error message in the syslog:

```
scylla_prepare[4973]: ERROR: Bad configuration mode (sq_split) and cpu-mask value (0x00000003): this results in a zero-mask for compute. Your system can't be tuned until the issue is fixed.
```

**Comment by slivne** [comment]
Patch

"[PATCH scylla v1] scylla_util.py: ignore perftune.py's error messages when calling it in order to get mode's CPU mask"

**Comment by vladzcloudius** [comment]
The issue is re-introduced by 

```
commit c3dae6673f53b0e838d98c19094a138d528fb5b9
Author: Takuya ASADA <syuu@scylladb.com>
Date:   Thu Apr 18 21:43:45 2019 +0900

    dist/common/scripts: use out() to run perftune.py
    
    perftune.py executes hwloc-calc, the command is now provided as
    relocatable binary, placed under /opt/scylladb/bin.
    So we need to add the directory to PATH when calling
    subprocess.check_output(), but our utility function already do that,
    switch to it.
    
    Fixes #4443
    
    Signed-off-by: Takuya ASADA <syuu@scylladb.com>
    Message-Id: <20190418124345.24973-1-syuu@scylladb.com>
```

the issue is present in 3.0.5.

@slivne Please, re-open it.
@glommer FYI

**Comment by slivne** [comment]
@vladzcloudius was this fixed ?

**Comment by vladzcloudius** [comment]
@slivne I don't think so.

**Comment by slivne** [comment]
@vladzcloudius you sent a patch to hide the errors - Avi did not approve the approach 

It seems that all the configuration is coming from scripts/perftune.py (that you are faimilar with) - can you try and fix

**Comment by vladzcloudius** [comment]
@slivne To clarify, the patch that hid the error has been merged by Avi long ago.
However after that there was another patch (from Takuya) that broke it. And patch in question simply tries to bring the code base to the state before my my original patch got broken.

**Comment by avikivity** [comment]
Prehistoric, removing label.
