### ISSUE TITLE
Migrating counter data from Cassandra 2.1 to Scylla 3.x using enable_dangerous_direct_import_of_cassandra_counters fails

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#4219]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): da9628c6dcc5b5660342ef9f56611a7845e0aab8
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

Migrating data from Cassandra 2.1 with counters copying the the sstables and running `nodetool refresh -- ks cf` failed, same data with was loader with `sstableloader --ignore-dropped-counter-data`

```
INFO  2019-02-13 10:54:20,934 [shard 0] storage_service - Done loading new SSTables for ks.cf for all shards
DEBUG 2019-02-13 10:54:20,934 [shard 0] compaction_manager - Accepted compaction job (2 sstable(s)) of weight 5 for ks.cf
DEBUG 2019-02-13 10:54:20,934 [shard 0] compaction - Checking droppable sstables in ks.cf
DEBUG 2019-02-13 10:54:20,934 [shard 0] compaction - Checking if candidate of generation 1 and max_deletion_time 2147483647 is expired, gc_before is   1549184060
DEBUG 2019-02-13 10:54:20,934 [shard 0] compaction - Checking if candidate of generation 2 and max_deletion_time 2147483647 is expired, gc_before is   1549184060
INFO  2019-02-13 10:54:20,934 [shard 0] compaction - Compacting [/home/fruch/.dtest/dtest-FSvayx/test/node1/data/ks/cf-f34bdf002f6c11e9b8e6000000000000/ks-cf-ka-1-Data.db:level=0, /home/fruch/.dtest/dtest-FSvayx/test/node1/data/ks/cf-f34bdf002f6c11e9b8e6000000000000/ks-cf-ka-2-Dat$
ERROR 2019-02-13 10:54:20,934 [shard 0] compaction_manager - compaction failed: marshal_exception (marshaling error: encountered a local shard in a counter cell): retrying
INFO  2019-02-13 10:54:20,934 [shard 0] compaction_manager - compaction task handler sleeping for 5 seconds
DEBUG 2019-02-13 10:54:20,945 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
DEBUG 2019-02-13 10:54:20,947 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
DEBUG 2019-02-13 10:54:20,947 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
DEBUG 2019-02-13 10:54:20,948 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
DEBUG 2019-02-13 10:54:20,948 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
DEBUG 2019-02-13 10:54:20,948 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
DEBUG 2019-02-13 10:54:20,948 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
DEBUG 2019-02-13 10:54:20,948 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
DEBUG 2019-02-13 10:54:20,948 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
DEBUG 2019-02-13 10:54:20,948 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
DEBUG 2019-02-13 10:54:20,958 [shard 0] auth_service - Refreshing permissions for <anonymous>
DEBUG 2019-02-13 10:54:20,958 [shard 0] paging - Query of f34bdf00-2f6c-11e9-b8e6-000000000000, page_size=5000, limit=2147483647 requires paging
DEBUG 2019-02-13 10:54:20,958 [shard 0] paging - Fetching f34bdf00-2f6c-11e9-b8e6-000000000000, page size=5000, max_rows=5000
DEBUG 2019-02-13 10:54:20,958 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 5000, ranges.size(): 257; concurrent range requests: 1
ERROR 2019-02-13 10:54:20,958 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: marshal_exception (marshaling error: encountered a local shard in a counter cell)
DEBUG 2019-02-13 10:54:20,959 [shard 0] storage_proxy - Error during read query exceptions::read_failure_exception (Operation failed for ks.cf - received 0 responses and 1 failures from 1 CL=ONE.)
```

**Comment by pdziepak** [comment]
How were the sstables generated? If they indeed contain pre-2.1 shards then the behaviour is exactly as expected.

The flag that allows direct import of non-Scylla counter tables doesn't make us support legacy counter shards. It is, as the flag description says, going to work only with the new counter shards (Cassandra 2.1 or later).

**Comment by slivne** [comment]
@pdziepak will sstabledump of this counters provide an answer about this ? if so @fruch please provide that

**Comment by pdziepak** [comment]
It should.

However, whenever we use binary files of any kind we should always document exactly how they were prepared (commands and Scylla or Cassandra exact versions), so that future ourselves don't need to waste time trying to figure this out.

**Comment by glommer** [comment]
On Wed, Feb 13, 2019 at 4:13 AM Israel Fruchter <notifications@github.com>
wrote:

> This is Scylla's bug tracker, to be used for reporting bugs only.
> If you have a question about Scylla, and not a bug, please ask it in
> our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.
>
>    - I have read the disclaimer above, and I am reporting a suspected
>    malfunction in Scylla.
>
> *Installation details*
> Scylla version (or git commit hash): da9628c
> <https://github.com/scylladb/scylla/commit/da9628c6dcc5b5660342ef9f56611a7845e0aab8>
> Cluster size: 1
> OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu
>
> Migrating data from Cassandra 2.1 with counters copying the the sstables
> and running nodetool refresh -- ks cf failed, same data with was loader
> with sstableloader --ignore-dropped-counter-data
>
> INFO  2019-02-13 10:54:20,934 [shard 0] storage_service - Done loading new SSTables for ks.cf for all shards
> DEBUG 2019-02-13 10:54:20,934 [shard 0] compaction_manager - Accepted compaction job (2 sstable(s)) of weight 5 for ks.cf
> DEBUG 2019-02-13 10:54:20,934 [shard 0] compaction - Checking droppable sstables in ks.cf
> DEBUG 2019-02-13 10:54:20,934 [shard 0] compaction - Checking if candidate of generation 1 and max_deletion_time 2147483647 is expired, gc_before is   1549184060
> DEBUG 2019-02-13 10:54:20,934 [shard 0] compaction - Checking if candidate of generation 2 and max_deletion_time 2147483647 is expired, gc_before is   1549184060
> INFO  2019-02-13 10:54:20,934 [shard 0] compaction - Compacting [/home/fruch/.dtest/dtest-FSvayx/test/node1/data/ks/cf-f34bdf002f6c11e9b8e6000000000000/ks-cf-ka-1-Data.db:level=0, /home/fruch/.dtest/dtest-FSvayx/test/node1/data/ks/cf-f34bdf002f6c11e9b8e6000000000000/ks-cf-ka-2-Dat$
> ERROR 2019-02-13 10:54:20,934 [shard 0] compaction_manager - compaction failed: marshal_exception (marshaling error: encountered a local shard in a counter cell): retrying
> INFO  2019-02-13 10:54:20,934 [shard 0] compaction_manager - compaction task handler sleeping for 5 seconds
> DEBUG 2019-02-13 10:54:20,945 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
> DEBUG 2019-02-13 10:54:20,947 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
> DEBUG 2019-02-13 10:54:20,947 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
> DEBUG 2019-02-13 10:54:20,948 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
> DEBUG 2019-02-13 10:54:20,948 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
> DEBUG 2019-02-13 10:54:20,948 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
> DEBUG 2019-02-13 10:54:20,948 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
> DEBUG 2019-02-13 10:54:20,948 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
> DEBUG 2019-02-13 10:54:20,948 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
> DEBUG 2019-02-13 10:54:20,948 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 2147483647, ranges.size(): 1; concurrent range requests: 1
> DEBUG 2019-02-13 10:54:20,958 [shard 0] auth_service - Refreshing permissions for <anonymous>
> DEBUG 2019-02-13 10:54:20,958 [shard 0] paging - Query of f34bdf00-2f6c-11e9-b8e6-000000000000, page_size=5000, limit=2147483647 requires paging
> DEBUG 2019-02-13 10:54:20,958 [shard 0] paging - Fetching f34bdf00-2f6c-11e9-b8e6-000000000000, page size=5000, max_rows=5000
> DEBUG 2019-02-13 10:54:20,958 [shard 0] storage_proxy - Estimated result rows per range: 0; requested rows: 5000, ranges.size(): 257; concurrent range requests: 1
> ERROR 2019-02-13 10:54:20,958 [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: marshal_exception (marshaling error: encountered a local shard in a counter cell)
>
>
This sounds like the bug Pawel fixed, no?

If your tree has my patch but not Pawel's , this is also expected.

**Comment by pdziepak** [comment]
No. That bug wouldn't say that we have a local shard if we don't. It did that only for remote shards.

**Comment by slivne** [comment]
@fruch can you please provide an sstabledump so we can make some progress

**Comment by fruch** [comment]
I couldn't run sstabledump on those files for some reason, move to scylla-tools-java origin/branch-2.1, and it still didn't work:
```
../scylla-tools-java/tools/bin/sstabledump cassandra-sstables/migration/2_1_x/with_wide_rows/ks-cf-ka-1-Data.db 
Exception in thread "main" java.lang.IllegalArgumentException: Could not locate schema info for /home/fruch/Projects/scylla-dtest/cassandra-sstables/migration/2_1_x/with_wide_rows/ks-cf-ka-1/(ks:cf). Make sure your 'data_file_directories' is pointed correctly.
        at com.scylladb.tools.SSTableExport.metadataFromSSTable(SSTableExport.java:30)
        at org.apache.cassandra.tools.SSTableExport.run(SSTableExport.java:192)
        at com.scylladb.tools.SSTableExport.main(SSTableExport.java:44)
```

the data being used is part of dtest (it was created 2 years ago, so I don't have the info exactly how it was created and with which exact version of cassandra):
https://github.com/scylladb/scylla-dtest/tree/next/cassandra-sstables/migration/2_1_x/with_old_format_counter

**Comment by slivne** [comment]
old_format measn the counters are not the types we support - so it is not supported and should not be used.

you can tun sstableloader without the counter flag and it will not work as well.

The additional flag enable_dangerous_direct_import_of_cassandra_counters  only allows loading the counters we support (the same ones that sstabloader supports wtihout the additional flag)
