### ISSUE TITLE
Large collection detector

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4234]
Collections tend to cause challenges when they grow to big, 

Some of that has todo with some collection operations requiring a RMW  - for example inserting into a specific location in a list requires reading the whole list. 

We have the large partition and large row detector.

Yet its simple to stay in the bound of the row detector default limitation (10 MB) and create a huge collection.
 
Lets add a large collection detector so we can find those and warn the user.

**Comment by tzach** [comment]
Related to issue #3750 and to enhancement #3988 (large rows detector)

**Comment by espindola** [comment]
What should the default size be? Given that for rows it is 10 MiB, I assume this would have to be quite a bit smaller.
