### ISSUE TITLE
dtest-debug: benign runtime error: member access within null pointer of type 'const struct shared_ptr' messages in logs

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4237]
since e988521b89d95bbe0c51feaadb9706522351d0aa we're consistently seeing the following benign messages in the logs. For example:

[52/artifact/logs-debug.2/1550266708659_auth_test.TestAuth.kill_one_of_the_nodes_with_the_auth_info_test/node1.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-debug/52/artifact/logs-debug.2/1550266708659_auth_test.TestAuth.kill_one_of_the_nodes_with_the_auth_info_test/node1.log)
```
/jenkins/workspace/scylla-master/dtest-debug/scylla/seastar/include/seastar/core/shared_ptr.hh:506:20: runtime error: member access within null pointer of type 'const struct shared_ptr'
cql3/cql3_type.cc:333:36: runtime error: reference binding to null pointer of type 'const struct shared_ptr'
```

Unlike the other types, `empty_type` is defined in types.cc using `const data_type` (`using data_type = shared_ptr<const abstract_type>` in types.hh) while the rest use `const shared_ptr<const abstract_type>` directly.

I wonder if the extra type indirection, combined with -Og trips a compiler anomaly.

**Comment by slivne** [comment]
@avikivity ?

**Comment by bhalevy** [comment]
497367f9f7e7f933076906d2e398cb81a13c8e28 reverts -Og
