### ISSUE TITLE
Spurious "compaction_manager - Asked to stop" INFO message at the end of the log

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#4238]
If I run Scylla and then kill it with a signal, the last message I see in the log is:
```
INFO  2019-02-17 15:02:15,386 [shard 0] compaction_manager - Asked to stop
```
This message appears frightening - as if "asked to stop" without a final "stopped" message suggest the shutdown is hung. In fact it probably isn't, and this is a spurious, second, attempt to shut down compaction_manager. A few second earlier in the same log I have:
```
INFO  2019-02-17 15:02:12,684 [shard 0] compaction_manager - Asked to stop
INFO  2019-02-17 15:02:12,684 [shard 0] compaction_manager - Stopped
```
So compaction did stop, correctly, and the attempt to stop it again at the end is probably unnecessary, and produced that half-output.

Finally, it would be nice for the shutdown process to print one "Shutdown ended" (or similar) message at the very end of the shutdown, so we can more reliably know, looking at he log, whether the shutdown hung or not.

**Comment by nyh** [comment]
Turns out we are shutting down the compaction manager in two places. The very last `at_exit()` in main.cc is:
```c++
            engine().at_exit([&db] {
                return db.invoke_on_all([](auto& db) {
                    return db.get_compaction_manager().stop();
                });
            });
```
So the compaction manager is the *first* thing that gets shut down.
Then, the *last* thing to be shut down (i.e., the first `at_exit()`) is
```c++
            engine().at_exit([&db, &return_value] {
                // call stop on each db instance, but leave the shareded<database> pointers alive.
                return db.invoke_on_all([](auto& db) {
                    return db.stop();
```
This calls `db.stop()` and `database::stop()` starts with a call to `_compaction_manager->stop()`.

**Comment by raphaelsc** [comment]
On Sun, Feb 17, 2019 at 11:16 AM nyh <notifications@github.com> wrote:

> Turns out we are shutting down the compaction manager in two places. The
> very last at_exit() in main.cc is:
>
>             engine().at_exit([&db] {
>                 return db.invoke_on_all([](auto& db) {
>                     return db.get_compaction_manager().stop();
>                 });
>             });
>
> So the compaction manager is the *first* thing that gets shut down.
> Then, the *last* thing to be shut down (i.e., the first at_exit()) is
>
>             engine().at_exit([&db, &return_value] {
>                 // call stop on each db instance, but leave the shareded<database> pointers alive.
>                 return db.invoke_on_all([](auto& db) {
>                     return db.stop();
>
> This calls db.stop() and database::stop() starts with a call to
> _compaction_manager->stop().
>
If I remember correctly, we only stopped compaction manager in
database::stop() which is the right thing to do because manager is an
entity managed by it. Later on, we added an explicit call to stop manager
earlier in the shutdown process to make it faster. I think this is okay
because compaction_manager::stop() is idempotent.

**Comment by nyh** [comment]
@raphaelsc I agree. This is why I sent a patch to avoid the printout, but keep the stop()-from two places - which is as you explained, fine.

**Comment by slivne** [comment]
patch "[PATCH] compaction manager: avoid spurious "asked to stop" message at the end of the log"
