### ISSUE TITLE
repair_during_update_test failed: 'Future' object has no attribute 'is_alive'

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4241]
scylla version: 7b411e30a9a286dcffb466569fb4379a6be14de9
scylla-dtest version: a7ebe94b78d02faad404912cf227533cb448a07f

Seen in [dtest-release/35/testReport/repair_additional_test/RepairAdditionalTest/repair_during_update_test/](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/35/testReport/repair_additional_test/RepairAdditionalTest/repair_during_update_test/):
```
'Future' object has no attribute 'is_alive'
```

FWIW, I didn't find anything suspicious in the [logs](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/35/artifact/logs-release.2/1550545487055_repair_additional_test.RepairAdditionalTest.repair_during_update_test/).
Where is this error coming from?

**Comment by asias** [comment]
I think the `'Future' object has no attribute 'is_alive'` is from dtest itself. A bug in dtest not in scylla.

**Comment by bhalevy** [comment]
@fruch looks like this could be related to scylladb/scylla-dtest@06b27b4333313372bf5807971f50f23803b73be2
I'll open a scylla-dtest issue...

**Comment by slivne** [comment]
dtest was fixed closing
