### ISSUE TITLE
column family snapshot should have a true_snapshots_size method

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#425]
The API needs to report the snap shots true size

**Comment by elcallio** [comment]
This was fixed by glauber in 71c1b2fe6904740773f72f98f43bfff0c526a9b8

**Comment by amnonh** [comment]
I've just realizde that glauber fix is not in the column_family level, the
issue need to be reopened

**Comment by penberg** [comment]
Fixed by https://github.com/scylladb/scylla/commit/3674ee2fc1497dc9bb91e691f4ff1a6a773c385e
