### ISSUE TITLE
`mutation_reader_merger` is slower with partition-level forwarding disabled

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#4254]
`mutation_reader_merger` keeps a `std::list` of active `flat_mutation_reader`s. That particular container was chosen because of stable references required by the rest of the logic. Unsurprisingly, it causes performance problems.

When partition-level fast-forwarding is disabled, the merger drops readers that have reached the end of stream. To do so it needs to iterate over the list:
```c++
} else if (_fwd_mr == mutation_reader::forwarding::no) {
    _all_readers.remove_if([mr = rk.reader] (auto& r) { return &r == mr; });
}
```
Commenting out that line or enabling partition-level fast-forwarding improves performance as reported by `perf_fast_forward`:

Before:
```
running: large-partition-single-key-slice on dataset large-part-ds1
Testing effectiveness of caching of large partition, single-key slicing reads:
   range            time (s)     frags     frag/s    mad f/s    max f/s    min f/s    aio      (KiB) blocked dropped  idx hit idx miss  idx blk    c hit   c miss    c blk    cpu 
-> [0, 1]           0.000413         2       4846        351       6542       1698      3        108       2       1        0        1        1        0        0        1 100.0% 
-> [1, 100)         0.000367        99     269418       1542     272137     183761      2        112       2       0        0        1        1        0        0        1 100.0% 
-> (100, 200]       0.000391       100     255828       1561     263088     243110      2        112       2       0        0        1        1        0        0        1 100.0%
```

After (commented out):
```
running: large-partition-single-key-slice on dataset large-part-ds1
Testing effectiveness of caching of large partition, single-key slicing reads:
   range            time (s)     frags     frag/s    mad f/s    max f/s    min f/s    aio      (KiB) blocked dropped  idx hit idx miss  idx blk    c hit   c miss    c blk    cpu 
-> [0, 1]           0.000384         2       5214        579       6874       1831      3        108       2       0        0        1        1        0        0        1 100.0% 
-> [1, 100)         0.000355        99     278739       2125     286858     193601      2        112       2       0        0        1        1        0        0        1 100.0%
-> (100, 200]       0.000379       100     263749       1568     271662     246900      2        112       2       0        0        1        1        0        0        1 100.0% 
```

Such results are not exactly expected, since disabling a feature should, if anything, increase performance (which it still may in some cases, thanks to the very fact that it does drop unneeded readers).

This is related to #4246.

**Comment by denesb** [comment]
Maybe instead of pointers (to readers) we should store iterators, so this scan of the list can be dropped.

**Comment by pdziepak** [comment]
Very good idea. Definitely worth doing.

I am also suspecting that the destruction of mutation readers, not being exactly the cheapest operation, may benefit from being batched (which is what happens if the fast-forwarding is enabled), but don't know for sure, yet.
