### ISSUE TITLE
Support User Defined Types (UDT)

### ISSUE THREAD

**Issue by tmonk42** [scylladb/scylla#426]
http://docs.datastax.com/en/cql/3.1/cql/cql_reference/cqlRefUDType.html

Having UDT support would allow Scylla to used as the backend for https://github.com/pyr/cyanite

Specifically: https://github.com/pyr/cyanite/blob/master/doc/schema.cql

**Comment by sfescape** [comment]
+1 for UDTs.

**Comment by tzach** [comment]
UDT also used in [Cyanite](http://cyanite.io/) a  Graphite API over Cassandra.
https://github.com/pyr/cyanite/blob/deade8842e8f14a9051b8b06cf79f7927977a60e/doc/schema.cql
