### ISSUE TITLE
Streaming gets stuck: The session X made no progress with peer Y

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#4260]
*Installation details*
Scylla version: 3.0.3
Cluster size: 6

*Hardware details*
Platform: physical
Hardware: 
 * shards: 36
 * mem: 120GB
 
Disks: 
 * 12 SSDs Samsung 883 1.8 TB RAID5

*Description*

Cluster topology:
6 scylla nodes. 3 racks, 2 nodes per rack. one DC

Schema:
```
CREATE KEYSPACE stress WITH replication = {'class': 'NetworkTopologyStrategy', 'dc': '3'}  AND durable_writes = true;
CREATE TABLE stress.bulk (
   key int,
   cluster_key int,
   data blob,
   primary key (key, cluster_key)
);
```

1) Populate 2.5TB of data with 100 rows in each partition and 100KB in a `data` in each row.
2) Kill one node and issue a rebuild.
3) See a lot of `The session X made no progress with peer Y` on all nodes.

**Comment by dorlaor** [comment]
Isn't there more data - what does the node do - net/disk activity, logs, ..

**Comment by slivne** [comment]
@vladzcloudius - Are you running rebuild while a node is down ?

**Comment by vladzcloudius** [comment]
@slivne node rebuilding was performed by following a "node replace" procedure:
1) Build a 6 nodes cluster
2) Populate data (RF=3) and schema data set specification as above.
3) Stop one node - nodeX
4) On nodeX:
   1) Delete contents of `data`, `commitlog` of nodeX. 
   2) Set `auto_bootstrap: true`
   3) Set `replace_address_first_boot: <nodeX boradcast_address>`
5) Start nodeX

**Comment by asias** [comment]
We have b8158dd65d3f9cc23865ff15ed8459a93e15761a in master.
