### ISSUE TITLE
Installing node_exporter in offline deployments is a hassle

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#4261]
We currently download node_exporter from the internet in the user site.

This is horrible for the offline installer, since there will be no connection to the internet in that use case.
While we could pre-download node_exporter just for that case, they seem to be apache licensed so I don't see why we can't ship their binary in our packages.

The offline installer would work as-is, and even outside of it, people do have issues with intermittent connectivity and our process would be more robust.

**Comment by avikivity** [comment]
Certainly we can create scylla-node-exporter. We'll need to fork the node_exporter repository and build it.

**Comment by glommer** [comment]
(Btw, I appreciate the title change but I don't think it describes the problem : we can install it, it's just a hassle -> have to download it separately)

**Comment by glommer** [comment]
My view is we should tag it for 3.1, that is expected to provide good offline support. @syuu1228

**Comment by tzach** [comment]
dup of #2190
