### ISSUE TITLE
increment_counters_in_threads_test failed with wrong count

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4265]
Scylla version (or git commit hash): 0eddf19432d12e68503194852d3183c20e9cf964

Seen in [40/testReport/counter_tests/TestCounters/increment_counters_in_threads_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/40/testReport/counter_tests/TestCounters/increment_counters_in_threads_test/):
```
Expecting counter0 = 100000, got 100064
```

**Comment by bhalevy** [comment]
Seen also in [dtest-release/40/testReport/counter_tests/TestCounters/increment_decrement_counters_in_threads_test/](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/40/testReport/counter_tests/TestCounters/increment_decrement_counters_in_threads_test/)

**Comment by bhalevy** [comment]
@pdziepak can you please look into this?
Let's try to figure this out.

**Comment by pdziepak** [comment]
The logs show that there are timeouts, which explains why we didn't get the value that was expected.
The question remains why there were timeouts and why the test attempted to retry the queries.

**Comment by bhalevy** [comment]
We see sporadic timeouts due to environment issues.
Current suspect is leftover processes due to timeouts that cause domino effect scylla-pkg#217

Closing this issue since the particular error seen is not a bug.
