### ISSUE TITLE
Scylla drops duplicated columns in the result 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4268]
Scylla version (or git commit hash): 3.0.3

Duplicates columns are not produced in the result set returned by scylla

```
cassandra@cqlsh> select key,"C0" from keyspace1.standard1; 

 key  | C0
------+------
 0x00 | 0x11

(1 rows)
cassandra@cqlsh> select key,"C0","C0" from keyspace1.standard1; 

 key  | C0   | C0
------+------+------
 0x00 | 0x11 | null

(1 rows)
cassandra@cqlsh> select key,"C0","C0","C1" from keyspace1.standard1; 

 key  | C0   | C0   | C1
------+------+------+------
 0x00 | 0x11 | 0x22 | null

(1 rows)
cassandra@cqlsh> select * from keyspace1.standard1; 

 key  | C0   | C1   | C2   | C3   | C4
------+------+------+------+------+------
 0x00 | 0x11 | 0x22 | null | null | null

(1 rows)
```

**Comment by eliransin** [comment]
This bug also exists in "cassandra" [(CASSANDRA-13262)](https://issues.apache.org/jira/browse/CASSANDRA-13262)
it seams that there is a solution waiting for verification there.
This seams like a cqlsh only bug and not a Scylla bug. Testing queries that present the above phenomena came out correctly when made using the python driver. Also validated with wireshark that showed that columns
that appeared multiple times in the query, showed up multiple times in the responce. The behavior seams to change slightly between 2 different cqlsh versions, one will just remove the duplicate columns and the other will show them in the header but will "compress" the column values - as showed above.
@slivne how do you want to handle it?

**Comment by eliransin** [comment]
@slivne ping

**Comment by eliransin** [comment]
@slivne ?

**Comment by slivne** [comment]
ok so cassandra fixed this in 3.11.4

We can fix it as well.

**Comment by eliransin** [comment]
We will eventually need to merge from upstream into scylla-tools-java.

**Comment by eliransin** [comment]
This is a cqlsh problem which is in another repository.
A proper issue is here: scylladb/scylla-tools-java#129
