### ISSUE TITLE
test_no_base_column_in_view_pk_complex_timestamp_with_flush failed: Expected [[1, 1, None, None]] from SELECT * FROM mv, but got []

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4271]
scylla version: 0eddf19432d12e68503194852d3183c20e9cf964
(passed with 84465c23c4d74ad5f2e12d6092427d4c157c964f)

Seen starting [dtest-release/39/testReport/materialized_views_test/TestMaterializedViews/test_no_base_column_in_view_pk_complex_timestamp_with_flush](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/39/testReport/materialized_views_test/TestMaterializedViews/test_no_base_column_in_view_pk_complex_timestamp_with_flush/):
```
Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 2189, in test_no_base_column_in_view_pk_complex_timestamp_with_flush
    self._test_no_base_column_in_view_pk_complex_timestamp(flush=True)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 2253, in _test_no_base_column_in_view_pk_complex_timestamp
    self.eventually_assert_one(session, "SELECT * FROM mv", [1, 1, None, None])
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 56, in eventually_assert_one
    return self.eventually(lambda: assert_one(*args))
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 50, in eventually
    return fun()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 56, in <lambda>
    return self.eventually(lambda: assert_one(*args))
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 968, in inner
    return func(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/assertions.py", line 53, in assert_one
    assert list_res == [expected], "Expected %s from %s, but got %s" % ([expected], query, list_res)
Expected [[1, 1, None, None]] from SELECT * FROM mv, but got []
```

materialized_views_test.py:
```
2250         # delete with ts=3, view row should be alive due to unselected@ts4
2251         self.update_view(session, "DELETE FROM t USING TIMESTAMP 3 WHERE k=1 AND c=1;", flush)
2252         self.eventually_assert_one(session, "SELECT * FROM t", [1, 1, None, None, None, 1])
2253         self.eventually_assert_one(session, "SELECT * FROM mv", [1, 1, None, None])
```

Any chance this was caused by bd52e05ae23458581d7e7276f706ae87d96f284b ?

**Comment by bhalevy** [comment]
Seen also in [dtest-release/40/testReport/materialized_views_test/TestMaterializedViews/test_no_base_column_in_view_pk_complex_timestamp_without_flush/](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/40/testReport/materialized_views_test/TestMaterializedViews/test_no_base_column_in_view_pk_complex_timestamp_without_flush/)

**Comment by nyh** [comment]
@psarna this is scary - it may mean that one of your optimization was not properly tested by the unit tests, which is what I tried to most insist on in the first review of your patch set (unfortunately it seems I didn't review your final version before Duarte committed it - I'll go back to reviewing it even though it was committed).

It's very fortunate that our dtest had a low level coverage test which we missed in the unit test. Usually it is (and should be) the other way around.

**Comment by psarna** [comment]
I did expand the test coverage for additional TTL cases and some more before it was merged. I'll investigate it tomorrow, and by the way some tests from materialized_view_tests.py, cql_additional_tests.py and friends can be moved to unit test layer with very little effort - I'll do that too.

**Comment by nyh** [comment]
Thanks @psarna.
Yes, it will be good to copy those to the unit test, but beyond that, it's worrying that we forgot to test something. It may mean we did not understand all the corner cases, and that we may be missing more tests. I'll review your code to think if we missed more cases.

**Comment by bhalevy** [comment]
Refs/duplicates scylladb/scylla-dtest#839

**Comment by psarna** [comment]
@bhalevy this one is actually not related to [scylladb/scylla-dtest#839](https://github.com/scylladb/scylla-dtest/issues/839), it's about the series that introduced optimizing the number of view updates (https://github.com/scylladb/scylla/issues/3819), the fix series is in review.
