### ISSUE TITLE
Schema exchange fails in a cluster with mixed schema of schema tables

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4273]
Currently, schema exchange between nodes assumes that the schema of the schema tables (not to be confused with the schema of user tables) is the same on all nodes. Nodes deserialize `frozen_mutations` using their local `schema_ptr` for schema tables. If the schema of schema tables is different on some nodes (rolling upgrade), e.g. a new column is added, this will trigger undefined behavior, most likely a failure to deserialize and apply the schema locally.

To fix this, we should exchange `canonical_mutation`, which can be deserialized using any `schema_ptr`.

If we decide to go with https://github.com/scylladb/scylla/issues/4248, then this issue is gone.

**Comment by denesb** [comment]
@tgrabiec just to confirm, only the background schema sync needs to be migrated to use `canonical_mutation`, the on-demand schema pulls (on reads and writes) already use it, right?

**Comment by tgrabiec** [comment]
Yes.

**Comment by bhalevy** [comment]
I discussed with @denesb if this needs to backported or not.
The conclusion is that we don't have to backport this fix since it is not a regression.

**Comment by denesb** [comment]
The goal we want to achieve with this change is to make parsing schema mutations with the wrong schema version defined, *not* to make it "just work". We still want to know about any instances of new nodes sending tables and/or columns to old nodes they don't know about, we just don't want the old node to crash or worse, get into a corrupt state.

This can only partially achieved with the current `canonical_mutation`, as it will tolerate any incompatibilities with the schema used for parsing it. So for now we contend with rejecting schema mutations that contain mutations for unknown tables.

**Comment by bhalevy** [comment]
@avikivity / @tgrabiec please consider backporting.

**Comment by bhalevy** [comment]
This patch could have helped #5291

**Comment by avikivity** [comment]
It's a major change, introducing new verbs and formats. It's too large for backports.
