### ISSUE TITLE
ignore_invalid_roles_test: set member_of without check if the role exists

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#4279]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20190122.dbc1894bd
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

* Description: 
`UPDATE system_auth.roles SET member_of = {'role1'} where role = 'mike'` completed without error, but actually `role1` doesn't exist.
Error occurred in `LIST ROLES OF mike;`

* Dtest subtest:  auth_roles_test:TestAuthRoles.ignore_invalid_roles_test   (ERROR)

```
ERROR: ignore_invalid_roles_test (auth_roles_test.TestAuthRoles)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/amos/space/scylla-dtest/auth_roles_test.py", line 1220, in ignore_invalid_roles_test
    assert_all(cassandra, "LIST ROLES OF mike", [mike_role])
  File "/home/amos/space/scylla-dtest/dtest.py", line 968, in inner
    return func(*args, **kwargs)
  File "/home/amos/space/scylla-dtest/assertions.py", line 71, in assert_all
    res = session.execute(simple_query)
  File "cassandra/cluster.py", line 2134, in cassandra.cluster.Session.execute
    return self.execute_async(query, parameters, trace, custom_payload, timeout, execution_profile, paging_state).result()
  File "cassandra/cluster.py", line 4026, in cassandra.cluster.ResponseFuture.result
    raise self._final_exception
InvalidRequest: Error from server: code=2200 [Invalid query] message="Role role1 doesn't exist."

----------------------------------------------------------------------
Ran 1 test in 26.957s

FAILED (errors=1)
```

* Manual reproduce steps:
```
cassandra@cqlsh> CREATE ROLE mike WITH LOGIN = true;
cassandra@cqlsh> LIST ROLES OF mike;

 role  | super | login | options
-------+-------+-------+---------
 mike | False |  True |        {}

(1 rows)
cassandra@cqlsh> UPDATE system_auth.roles SET member_of = {'role1'} where role = 'mike'
   ... ;
cassandra@cqlsh> LIST ROLES OF mike;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Role role1 doesn't exist."
cassandra@cqlsh> LIST ROLES OF role1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Role role1 doesn't exist."
cassandra@cqlsh> LIST ROLES;

 role      | super | login | options
-----------+-------+-------+---------
 cassandra |  True |  True |        {}
      mike | False |  True |        {}

(2 rows)
```

@hakuch @slivne @roydahan

**Comment by amoskong** [comment]
Good example: 
Set member_of with existing role (`mike2`), it succeed, and `LIST ROLES OF mike3;` is fine.

```
cassandra@cqlsh> CREATE ROLE mike2 WITH LOGIN = true;
cassandra@cqlsh> CREATE ROLE mike3 WITH LOGIN = true;
cassandra@cqlsh> UPDATE system_auth.roles SET member_of = {'mike2'} where role = 'mike3' ;
cassandra@cqlsh> LIST ROLES OF mike3;

 role  | super | login | options
-------+-------+-------+---------
 mike2 | False |  True |        {}
 mike3 | False |  True |        {}

(2 rows)
```

**Comment by amoskong** [comment]
After created role1, the list command will succeed.
```
cassandra@cqlsh> LIST ROLES OF mike;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Role role1 doesn't exist."
cassandra@cqlsh> CREATE ROLE role1 WITH LOGIN = true;
cassandra@cqlsh> LIST ROLES OF mike;

 role  | super | login | options
-------+-------+-------+---------
  mike | False | False |        {}
 role1 | False |  True |        {}

(2 rows)
```


So we allow to set member with non-existing role, and the member role can be created later?

**Comment by hakuch** [comment]
I don't understand why you are manually changing `system_auth.roles`. That table is meant only for internal use of Scylla.

**Comment by amoskong** [comment]
All update is executed by legal cql statement. Do you mean update
statement? OR grant?

The test is from dtest upstream.

Jesse Haber-Kucharsky <notifications@github.com> 于 2019年2月25日周一 下午11:36写道：

**Comment by hakuch** [comment]
I mean any query that is modifying `system_auth.roles` directly.

I realize that it's from upstream, but I don't think the test is valid.

**Comment by amoskong** [comment]
Can we prevent users to update the internal table system_auth.roles through CQL queries?

**Comment by hakuch** [comment]
Possibly, but we have many other internal tables in the implementation of Scylla that are similar to `system_auth.roles`, so it doesn't seem like a worthwhile goal to me.

The root problem is that tests should not fuss with internal implementation details. Especially integration tests.

**Comment by amoskong** [comment]
On Tue, Feb 26, 2019 at 7:47 AM Jesse Haber-Kucharsky <
notifications@github.com> wrote:

> Possibly, but we have many other internal tables in the implementation of
> Scylla that are similar to system_auth.roles, so it doesn't seem like a
> worthwhile goal to me.
>
Sure.

> The root problem is that tests should not fuss with internal
> implementation details. Especially integration tests.
>
Agree.

**Comment by slivne** [comment]
@roydahan / @amoskong can we close this ?

**Comment by amoskong** [comment]
Yes.  Not a bug.
