### ISSUE TITLE
CQL compatibility in delete

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#4286]
scylla 3.0

Delete should support ALLOW FILTERING
Example:
cqlsh> DELETE from scylla_demo.tweets where text='text_1' ALLOW FILTERING;
SyntaxException: line 1:51  : syntax error...

Delete with no WHERE part should be supported:
example:
cqlsh> DELETE from scylla_demo.tweets;
SyntaxException: line 1:30  : syntax error...

**Comment by slivne** [comment]
ALLOW FILTERING in queries not in insert/update/delete.

there is a way to specify conditions with lwt for delete/update/insert - but this is also limited to a partition and does not suppoet allow filtering
