### ISSUE TITLE
CQL compatibility non equal in select

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#4287]
scylla 3.0

In cassandra cql you can use not equal `!=` or the `not` keywords.
Examples:
 cqlsh> select * from scylla_demo.tweets where tweet_id!=8adda51e-39af-11e9-a25c-28f10e03285d;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Unsupported "!=" relation: tweet_id != 8adda51e-39af-11e9-a25c-28f10e03285d"

cqlsh> select * from scylla_demo.tweets where not tweet_id=8adda51e-39af-11e9-a25c-28f10e03285d;
SyntaxException: line 1:39 no viable alternative at input 'not'

**Comment by amnonh** [comment]
The schema I used:
CREATE KEYSPACE scylla_demo WITH replication = {'class': 'NetworkTopologyStrategy', 'dc1':3, 'dc2':3};

CREATE TABLE scylla_demo.tweets (
    tweet_id uuid PRIMARY KEY,
    time timeuuid,
    user text,
    text text
); 

I've tried it with the primary key and with a normal key and allow filtering

**Comment by tzach** [comment]
The above test did not works on Apache Cassandra either (3.11)

```
CREATE KEYSPACE mykeyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
use mykeyspace;                                                               
CREATE TABLE tweets (tweet_id uuid PRIMARY KEY,
              ... time timeuuid,
              ... user text,
              ... text text
              ... );
select * from tweets where tweet_id!=8adda51e-39af-11e9-a25c-28f10e03285d;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Unsupported "!=" relation: tweet_id != 8adda51e-39af-11e9-a25c-28f10e03285d"
```
As far as I underated the spec (below) it should not work. From Apache Cassandra refercene:

> The WHERE clause specifies which rows must be queried. It is composed of relations on the columns that are part of the PRIMARY KEY and/or have a secondary index defined on them.
Not all relations are allowed in a query. For instance, **non-equal relations (where IN is considered as an equal relation) on a partition key are not supported** ...

http://cassandra.apache.org/doc/latest/cql/dml.html#the-where-clause


Also see here
https://stackoverflow.com/questions/19370130/cassandra-cql-not-equal-operator-on-any-column

**Comment by slivne** [comment]
closing cassandra does not support this as well ...

amnon can you please provide a sample on cassandra that this is allowed
