### ISSUE TITLE
CQL Alter Keyspace

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#429]

**Comment by slivne** [comment]
We are still missing enabeling of different unitests (both in dtest and cassandra-java-unitests)

**Comment by penberg** [comment]
@slivne There are patches from @elcallio to enable dtests. I'll enable the unit tests.

**Comment by slivne** [comment]
the patches from @elcallio are only for the auth_test there are additional
tests to enable

**Comment by Freeaqingme** [comment]
Awesome. Tnx!

**Comment by penberg** [comment]
@slivne, oh, you are correct. He sent patches only against auth_test, not against the rest.
