### ISSUE TITLE
update compaction history failed during shutdown: Exceptional future ignored: seastar::broken_promise (broken promise)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4291]
scylla version ca288189a9418d15b5beea32c0a4afeb5fd793b7

Seen in [dtest-release/43/testReport/repair_additional_test/RepairAdditionalTest/repair_abort_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/43/testReport/repair_additional_test/RepairAdditionalTest/repair_abort_test/):
```
Unexpected error in node3 node log: ['ERROR 2019-02-27 02:21:02,659 [shard 0] system_keyspace - update compaction history failed: exceptions::mutation_write_failure_exception (Operation failed for system.compaction_history - received 0 responses and 1 failures from 1 CL=ONE.): ignored']
```

[node3.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/43/artifact/logs-release.2/1551227051416_repair_additional_test.RepairAdditionalTest.repair_abort_test/node3.log):
```
INFO  2019-02-27 02:21:02,597 [shard 0] compaction_manager - Asked to stop
INFO  2019-02-27 02:21:02,597 [shard 1] compaction_manager - Asked to stop
INFO  2019-02-27 02:21:02,600 [shard 1] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-IE4O8e/test/node3/data/ks/cf-0d26ac303a2511e9b3b1000000000000/mc-47-big-Data.db:level=0, ]. 186369 bytes to 180362 (~96% of original) in 259ms = 0.66MB/s. ~1664 total partitions merged to 1550.
INFO  2019-02-27 02:21:02,601 [shard 1] compaction_manager - Stopped
INFO  2019-02-27 02:21:02,601 [shard 0] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-IE4O8e/test/node3/data/ks/cf-0d26ac303a2511e9b3b1000000000000/mc-48-big-Data.db:level=0, ]. 186222 bytes to 179584 (~96% of original) in 200ms = 0.86MB/s. ~1664 total partitions merged to 1536.
WARN  2019-02-27 02:21:02,652 [shard 1] seastar - Exceptional future ignored: seastar::broken_promise (broken promise), backtrace:   0x452d99b
  0x40b35e4
  0xac01b6
  0x2481499
  0x40b2171
  0x40b236e
  0x4188efd
  0x41b2e6b
  0x4081e2d
  /lib64/libpthread.so.0+0x858d
  /lib64/libc.so.6+0xfd6a2

ERROR 2019-02-27 02:21:02,659 [shard 0] system_keyspace - update compaction history failed: exceptions::mutation_write_failure_exception (Operation failed for system.compaction_history - received 0 responses and 1 failures from 1 CL=ONE.): ignored
INFO  2019-02-27 02:21:02,659 [shard 0] compaction_manager - Stopped
INFO  2019-02-27 02:21:03,228 [shard 0] init - Scylla version 666.development-0.20190227.ca288189a shutdown complete.
```

**Comment by bhalevy** [comment]
FYI @espindola's patches in [shutdown-order-patches-v2](https://github.com/espindola/scylla/commits/espindola/shutdown-order-patches-v2) may help here.

**Comment by bhalevy** [comment]
Seen again in [dtest-release/48/artifact/logs-release.2/1551743072408_repair_additional_test.RepairAdditionalTest.repair_abort_test/node3.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/48/artifact/logs-release.2/1551743072408_repair_additional_test.RepairAdditionalTest.repair_abort_test/node3.log)

**Comment by slivne** [comment]
48 was using da0a25859bc5f22f9bbaf0446fd5baa661e4e37a

all the patches related to shutdown and stopping data/commitlog diffrently went in after that - closing this issue - will reopen if we hit this again

**Comment by bhalevy** [comment]
shutdown changes went in in a29ec4be76d457094a1da4894f8289e425a04e19
