### ISSUE TITLE
truncate tables is very slow under pressure

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#4294]
Truncating a table is very slow if the system is under pressure. Because in that case we mostly just want to get rid of the existing data, it shouldn't take this long. The problem happens because truncate has to wait for memtable flushes to end, twice. This is regardless of whether or not the table being truncated has any data.

1. The first time is when we call truncate itself:

if auto_snapshot is enabled, we will flush the contents of this table first and we are expected to be slow. However, even if auto_snapshot is disabled we will still do it -- which is a bug -- if the table is marked as durable. We should just not flush in this case and it is a silly bug.

2. The second time is when we call cf->stop(). Stopping a table will wait for a flush to finish. At this point, regardless of which path (Durable or non-durable) we took in the previous step we will have no more data in the table. However, calling `flush()` still need to acquire a flush_permit, which means we will wait for whichever memtable is flushing at that very moment to end.

If the system is under pressure and a memtable flush will take many seconds, so will truncate.
Even if auto_snapshots are enabled, we shouldn't have to flush twice. The first flush should already put is in a state in which the next one is immediate (maybe holding on to the permit, maybe destroying the memtable_list already at that point -> since no other memtables should be created).

If auto_snapshots are not enabled, the whole thing should just be instantaneous.

**Comment by elcallio** [comment]
Snapshot if table is durable is not a bug. It is implementing the origin behaviour.

**Comment by glommer** [comment]
We don't snapshot durable tables already.
We just flush them.
