### ISSUE TITLE
materialized_views/secondary_indexes tests fail with: views not built

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4298]
Seen in several tests since ea34e242de82d5f76375e7767d0db434de7b6701

Recent examples:
[dtest-release/43/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/43/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test/):
```
View ks.tm_table_mv_2 not built
```
All node logs show that the view started building but not finished.

[dtest-release/42/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_restart_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/42/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_restart_test/)

[dtest/1019/label=scylla-dtest,mode=release,smp=2/testReport/secondary_indexes_test/TestSecondaryIndexes/test_stop_node_during_index_build](http://jenkins.cloudius-systems.com:8080/job/scylla-master/job/dtest/1019/label=scylla-dtest,mode=release,smp=2/testReport/secondary_indexes_test/TestSecondaryIndexes/test_stop_node_during_index_build/)

**Comment by bhalevy** [comment]
Refs/duplicates scylladb/scylla-dtest#839

**Comment by psarna** [comment]
It should be covered by https://github.com/scylladb/scylla-dtest/commit/f5669d68337f2935c1038ab2a5a106179a578623

**Comment by slivne** [comment]
closing issue - since the patch is merged - we can reopen if it happens again
