### ISSUE TITLE
Mutation diff

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#430]
for read repair need the ability to compute a mutation diff and send the diff @gleb-cloudius can you please provide additional info / ref to origin

**Comment by pdziepak** [comment]
@gleb-cloudius The code that computes mutation difference is more or less completed, but I'm not very familiar with out repair and streaming implementation and would any appreciate some pointers to the relevant parts of the code so that I can wire it up.

**Comment by gleb-cloudius** [comment]
On Thu, Oct 22, 2015 at 02:11:46AM -0700, Paweł Dziepak wrote:
> @gleb-cloudius The code that computes mutation difference is more or less completed, but I'm not very familiar with out repair and streaming implementation and would any appreciate some pointers to the relevant parts of the code so that I can wire it up.
> 
I'll write it up, just let me have it :)

--
			Gleb.
