### ISSUE TITLE
Include node_exporter in Scylla Docker

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#4300]
*Installation details*
Scylla version (or git commit hash): 3.0
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

Currently, node_exporter is not part of the standard Scylla Docker image
This makes monitoring of a Docker deployment of Scylla not standard and harder to use.
For example, monitoring stack generate alerts as if the node is down since no reports is coming from node_exporter

See the following setup as an example
https://gist.github.com/tzach/66c8d0ce76ae50fd6ead36f263b5bedf

![image](https://user-images.githubusercontent.com/170200/53694301-f12a0480-3dd2-11e9-99c5-d1d193e759ef.png)

**Comment by tzach** [comment]
related to #2190

**Comment by amnonh** [comment]
you are right, but node_exporter install is part of docker, so for demo purposes, you can use it.

For example, I use the following:
```
docker exec -it some-scylla /usr/sbin/node_exporter_install

Traceback (most recent call last):
  File "/usr/sbin/node_exporter_install", line 70, in <module>
    with open('/etc/init/node_exporter.conf', 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/init/node_exporter.conf'

```
Ignores the error.

Now you can run:
``` 
docker exec some-scylla /usr/lib/scylla/Prometheus/node_exporter/node_exporter-0.17.0.linux-amd64/node_exporter

```

**Comment by slivne** [comment]
@tzach - since in some cases we should not run node_exporter and in others we should - should we install it by default and not run it by default - and only start if an option is passed ?

**Comment by tzach** [comment]
> @tzach - since in some cases we should not run node_exporter and in others we should - should we install it by default and not run it by default - and only start if an option is passed ?

We can, but I would suggest to **enable** by default.
In most cases it is useful, and when it does not, one can disable it with an option
