### ISSUE TITLE
add counters breaking up cql requests based on consistency_level

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4309]
Some CL 
- ALL - are not recommended as they will cause availability issues if a cluster node is down. 
- ANY - is discouraged as it does not give any guarantee the data has been written to any replica

By adding this counters we will be able to advise users to modify their application

**Comment by dekimir** [comment]
I plan to implement this by adding a new histogram metrics to [query_processor](https://github.com/scylladb/scylla/blob/master/cql3/query_processor.cc#L107).  The histogram will have one bar for every member of [db::consistency_level](https://github.com/scylladb/scylla/blob/master/db/consistency_level_type.hh#L48).

**Comment by dekimir** [comment]
The metric value will be updated in various `query_processor::process*` methods.

**Comment by glommer** [comment]
It seems to me the best would be to just add a label to the existing CQL counters.
There is a finite number of them and we always know which ones we want to see.

This also means that all existing counters would keep working, just showing the full aggregation.

**Comment by dekimir** [comment]
@glommer what precisely do you mean by "existing CQL counters"?  I don't think I know of any existing metrics that fit that description.

**Comment by glommer** [comment]
Our standard dashboard ships for instance, the following metric:
`sum(irate(scylla_cql_inserts{instance=~"[[node]]",cluster=~"$cluster|$^", dc=~"$dc", shard=~"[[shard]]"}[300s])) by ([[by]])`
(similar for deletes, updates, etc)

This is taken at the CQL layer so we should still have CL information when we derive them.
Why not add consistency level as a label to that metric?

**Comment by dekimir** [comment]
Thanks, but I'm missing some context here and cannot understand easily what that metric is.  Could you tell me, eg, where this metric is registered in the source code?  Or which code updates it?  And does it cover regular, non-modifying, queries?

**Comment by glommer** [comment]
Those metrics are registered in the constructor of query_processor (cql3/query_processor.cc)
There are separate metrics for separate verbs, but in the end all should be covered.

Another option is to use total_requests from transport/server.cc. I don't care much which metric exactly is changed, but I do think that labels are better than a separate metric.

**Comment by dekimir** [comment]
Oh, I think I understand now: you're saying use additional labels to enable grouping existing metrics by consistency level.  Sounds reasonable.  Let me research how exactly to do that...

**Comment by glommer** [comment]
yes, that's what I am saying. The metrics above are some suggestions on where this can take place, but since I haven't really double checked which info is available where, feel free to add labels to whichever one you think makes sense.

**Comment by amnonh** [comment]
On Thursday, March 21, 2019, Glauber Costa <notifications@github.com> wrote:

> Our standard dashboard ships for instance, the following metric:
> sum(irate(scylla_cql_inserts{instance=~"[[node]]",cluster=~"$cluster|$^",
> dc=~"$dc", shard=~"[[shard]]"}[300s])) by ([[by]])
> (similar for deletes, updates, etc)
>
> This is taken at the CQL layer so we should still have CL information when
> we derive them.
> Why not add consistency level as a label to that metric?
>
This is the better approach, more so, i was thinking making the action
(insert, delete, etc) a label

**Comment by dekimir** [comment]
I didn't manage to find any suitable existing metrics whose update code has ready access to consistency level.  I just sent out an [RFC](https://groups.google.com/forum/#!topic/scylladb-dev/YDAN-JDYm3s) with the new metrics I added.  PTAL, I hope it's a step in the right direction.

**Comment by dekimir** [comment]
Question: when a query is paged, should that bump the metric?  Or are we only counting queries, regardless of how many pages are fetched?
