### ISSUE TITLE
Scylla shows in journalctl as dpdk_args

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#431]
CentOS 7, scylla-server-0.9-20150924.4de5875.el7.centos.x86_64

```
$ journalctl
...
pa<C5><BA> 01 07:17:57 m2 dpdk_args[5032]: [shard 0] config - Option hinted_handoff_enabled is not (yet) used.

[root@m2 ~]# pgrep scylla
5032
```

**Comment by avikivity** [comment]
Fix is to avoid a script altogether, and have everything needed to the command line in the config file.

**Comment by gleb-cloudius** [comment]
On Thu, Oct 01, 2015 at 05:38:02AM -0700, Avi Kivity wrote:
> Fix is to avoid a script altogether, and have everything needed to the command line in the config file.
> 
no, we should pass real argv0 to dpdk init function.

> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/scylladb/scylla/issues/431#issuecomment-144714501

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Thu, Oct 01, 2015 at 06:25:43PM +0300, Gleb Natapov wrote:
> On Thu, Oct 01, 2015 at 05:38:02AM -0700, Avi Kivity wrote:
> > Fix is to avoid a script altogether, and have everything needed to the command line in the config file.
> > 
> no, we should pass real argv0 to dpdk init function.
> 
I've send the patch to do just so.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Mon, Oct 19, 2015 at 04:06:42PM +0300, Gleb Natapov wrote:
> On Thu, Oct 01, 2015 at 06:25:43PM +0300, Gleb Natapov wrote:
> > On Thu, Oct 01, 2015 at 05:38:02AM -0700, Avi Kivity wrote:
> > > Fix is to avoid a script altogether, and have everything needed to the command line in the config file.
> > > 
> > no, we should pass real argv0 to dpdk init function.
> > 
> I've send the patch to do just so.
> 
Patch is applied, we can close this.

--
			Gleb.
