### ISSUE TITLE
TWCS: if compaction_window_size is not set we default to 24H

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4310]
scylla : e9bc2a7912bcc3539f0a10c436a60069b88d1cab

sstables/time_window_compaction_strategy.hh
```
    std::chrono::seconds sstable_window_size = DEFAULT_COMPACTION_WINDOW_UNIT(DEFAULT_COMPACTION_WINDOW_SIZE);

.
.
        it = options.find(COMPACTION_WINDOW_SIZE_KEY);
        if (it != options.end()) {
            try {
                sstable_window_size = std::stoi(it->second) * window_unit;
            } catch (const std::exception& e) {
                throw exceptions::syntax_exception(sstring("Invalid integer value ") + it->second + " for " + COMPACTION_WINDOW_SIZE_KEY);
            }
        }
```

so a user that changes the default UNIT from DAYS to HOURS and does not set the compaction_window_size will endup with a window of 24H instead of 1H.

According to the docs https://docs.scylladb.com/getting-started/compaction/#twcs-options - compaction_window_size should default to a value of 1.

**Comment by nyh** [comment]
By the way, Cassandra's coumentation, https://docs.datastax.com/en/cql/3.3/cql/cql_reference/cqlCreateTable.html#compactSubprop__compactionSubpropertiesTWCS suggests that the unit's default, in Cassandra, is milliseconds, not days, and there's apparently no default for the size. I don't know what happens in Cassandra if you don't set it.
Maybe we should have the same defaults as Cassandra, in case someone brings a yaml file from Cassadra?

**Comment by bhalevy** [comment]
@nyh:
1. This is a separate issue.
2. What about backward compatibility with existing customers that rely on scylla's defaults?
