### ISSUE TITLE
repair_option_pr_multi_dc_test: rpc client::negotiate_protocol: Assertion `_state' failed.

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4316]
scylla version 2718c90448514f97f7f21200da13e1d9d704904d
seastar version scylladb/seastar@e6403148bdf1943af599cc9f2f41097d7c5495dd

See in [dtest-release/53/artifact/logs-release.2/1552184683430_repair_additional_test.RepairAdditionalTest.repair_option_pr_multi_dc_test/node3.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/53/artifact/logs-release.2/1552184683430_repair_additional_test.RepairAdditionalTest.repair_option_pr_multi_dc_test/node3.log):
```
INFO  2019-03-10 02:28:28,819 [shard 0] repair - Repair 16 out of 256 ranges, id=1, shard=0, keyspace=ks, table={cf}, range=(-8172271308588008710, -8172242701734474297]
scylla: ../../include/seastar/core/future.hh:511: void seastar::promise<T>::set_value(A&& ...) [with A = {}; T = {}]: Assertion `_state' failed.
Aborting on shard 1.
Backtrace:
  0x00000000041f7eb2
  0x00000000040f6965
  0x00000000040f6c65
  0x00000000040f6d13
  0x00007f027bea602f
  /lib64/libc.so.6+0x000000000003853e
  /lib64/libc.so.6+0x0000000000022894
  /lib64/libc.so.6+0x0000000000022768
  /lib64/libc.so.6+0x00000000000309f5
  0x00000000044f00e9
  0x00000000044f4884
  0x00000000040f3df1
  0x00000000040f3fee
  0x00000000041c80e5
  0x00000000041eeddb
  0x00000000040c39cd
  /lib64/libpthread.so.0+0x000000000000858d
  /lib64/libc.so.6+0x00000000000fd6a2

seastar::future<> seastar::futurize<seastar::future<> >::apply<seastar::rpc::client::client(seastar::rpc::logger const&, void*, seastar::rpc::client_options, seastar::socket, seastar::socket_address const&, seastar::socket_address const&)::{lambda(seastar::connected_socket)#1}::operator()(seastar::connected_socket) const::{lambda()#1}>(seastar::rpc::client::client(seastar::rpc::logger const&, void*, seastar::rpc::client_options, seastar::socket, seastar::socket_address const&, seastar::socket_address const&)::{lambda(seastar::connected_socket)#1}::operator()(seastar::connected_socket) const::{lambda()#1}&&, std::tuple<>&&) [clone .isra.1697] at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../include/seastar/core/future.hh:511
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../include/seastar/core/shared_future.hh:259
 (inlined by) operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../src/rpc/rpc.cc:652
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../include/seastar/core/apply.hh:35
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../include/seastar/core/apply.hh:43
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/build/release/../../include/seastar/core/future.hh:1478
```

**Comment by bhalevy** [comment]
@gleb-cloudius can you please look into this stack trace?

**Comment by bhalevy** [comment]
See core file in godzilla:/jenkins/corefiles/2019-03-10/scylla.17612.core

**Comment by gleb-cloudius** [comment]
The core is not very useful without the binary that goes with it.

**Comment by bhalevy** [comment]
scylla binary for the above core dump is here: [http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/53/artifact/logs-release.2/scylla](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/53/artifact/logs-release.2/scylla)

**Comment by gleb-cloudius** [comment]
In which environment the binary was built? gdb cannot open it properly
without correct libraries.

--
			Gleb.

**Comment by bhalevy** [comment]
It was generated with dbuild so we need the frozen toolchain

**Comment by bhalevy** [comment]
I could open the core file properly on my f29 machine, looks like our docker image lacks libraries required by gdb.

**Comment by gleb-cloudius** [comment]
On Sun, Mar 10, 2019 at 05:00:52AM -0700, Benny Halevy wrote:
> I could open the core file properly on my f29 machine, looks like our docker image lacks libraries required by gdb.
> 
> 
Yes, in fedora 29 docker it works.

--
			Gleb.

**Comment by bhalevy** [comment]
Seen in [dtest-release/56/artifact/logs-release.2/1552481486926_sstable_generation_loading_test.TestSSTableGenerationAndLoading.sstableloader_compression_snappy_to_snappy_test/node1.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/56/artifact/logs-release.2/1552481486926_sstable_generation_loading_test.TestSSTableGenerationAndLoading.sstableloader_compression_snappy_to_snappy_test/node1.log)

scylla version b8158dd65d3f9cc23865ff15ed8459a93e15761a

Core on godzilla:/jenkins/scylla.2302.core.lz4
Binary: [http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/56/artifact/logs-release.2/scylla](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/56/artifact/logs-release.2/scylla)

**Comment by slivne** [comment]
gleb is looking into this ... chatted f2f

**Comment by bhalevy** [comment]
Another core on godzilla:/jenkins/corefiles/dtest-release-59/scylla.29562.core.lz4
Binary: [http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/59/artifact/logs-release.2/scylla](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/59/artifact/logs-release.2/scylla)

scylla version f4f56027bf3a898745f49f55a595c926fa8cc093
seastar version scylladb/seastar@463d24ec0aa09de771e07e344d4ba10733bbbaae
