### ISSUE TITLE
replace node: Cannot replace token x which does not exist

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#4325]
In https://github.com/scylladb/scylla/issues/4319, user found another issue when trying to replace a node showing 
```
Mar 12 19:22:34 ip-172-31-24-103.ec2.internal scylla.bin[41958]:  [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (Cannot replace token -9207630143415525763 which does not exist!)
```

I am able to find a simple reproducer as follow:

```
1. start n1 n2 n3
2. shutdown n1,  n2, n3
3. start n1, n2
4. start n4 to replace n3
we will see n4 complains "Cannot replace token -9207630143415525763 which does not exist"
```

This is because in step 2 we shutdown all the nodes, so in step 3, all the nodes lost n3's status information which is supposed to be NORMAL in this case. When n4 starts to replace n3, n4 won't have the token info in token_metadata, because n4 only inserts n3's token info into token_metatdata when it receives STATUS application state.  When n4 does the check to make sure it is replacing a valid node in storage_service::join_token_ring, we see the "Cannot replace token x which does not exist" error.

A workaround can be disabling the check. I verified it worked. Of course, a proper fix is needed.  

```
--- a/service/storage_service.cc
+++ b/service/storage_service.cc
@@ -543,7 +543,7 @@ void storage_service::join_token_ring(int delay) {
                         }
                         current.insert(*existing);
                     } else {
-                        throw std::runtime_error(sprint("Cannot replace token %s which does not exist!", token));
+                        // throw std::runtime_error(sprint("Cannot replace token %s which does not exist!", token));
                     }
                 }
             } else {
```

**Comment by slivne** [comment]
@asias what does cassandra do here ?

**Comment by slivne** [comment]
a workaroud for this that asias suggested is to run 
```
1. start n1 n2 n3
2. shutdown n1,  n2, n3
3. start n1, n2
4. nodetool removenode n3
4. start n4 
```

**Comment by asias** [comment]
> @asias what does cassandra do here ?

Cassandra will fail to replace the node in a even more bad way. 

```
 ERROR [main] 2019-03-15 08:49:47,015 CassandraDaemon.java:708 - Exception encountered during startup
 java.lang.RuntimeException: Cannot replace_address /127.0.0.3 because it doesn't exist in gossip
```

**Comment by asias** [comment]
Patch on list: [PATCH scylla v1] storage_service: Allow replacing node when all nodes were shutdown
The patch is not merged yet.

**Comment by tgrabiec** [comment]
The more general problem which encloses this issue is https://github.com/scylladb/scylla/issues/6088

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
