### ISSUE TITLE
Extensions need mechanism to ensure a keyspace is populated/inited before user keyspaces

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#4327]
Since an extension might potentially need to read data from sstables to fulfil its role during bootstrap, extensions need a mechanism to make non-system keyspaces populated before other "user" keyspaces.

Either be able to do manual populate on demand (and more importantly change bootstrap to handle possibly calling populate_cf twice, or have an extension mechanism to treat a ks like a system keyspace w.r. to the partitioning of population system/rest. 

The latter is probably easier and less error prone.

**Comment by slivne** [comment]
patch on list - [PATCH] extensions: Add functionality to designate keyspace for early init

**Comment by elcallio** [comment]
Please close this as wontfix. The underlying problem goes somewhat deeper than this, and I've posted a better, isolated, solution for it on internal lists. No need to augment the extensions further.
