### ISSUE TITLE
boost::bad_any_cast: failed conversion using boost::any_cast

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#433]
cqlsh:

```
CREATE KEYSPACE ks WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 };
use ks;
CREATE TABLE apa (ola text PRIMARY KEY, tuta map<frozen<tuple<uuid, int>>, blob>);
INSERT INTO apa (ola, tuta) VALUES ('foo', { (62c36092-82a1-3a00-93d1-46196ee77204, 2) : bigintAsBlob(3) });
truncate apa;
```
->
```
ProtocolException: <ErrorMessage code=000a [Protocol error] message="Error during truncate: std::runtime_error (boost::bad_any_cast: failed conversion using boost::any_cast)">
```

Guessing something that does not handle tuple type at some point. Did not have time to investigate futher yet, no idea if it is even related to truncate. This issue is a reminder to do check it.

**Comment by avikivity** [comment]
Can't reproduce with e3429142651f55f4

**Comment by elcallio** [comment]
Yeah, I think this is actually a side effect of me having slightly trashed system tables, so probably false alarm. Let me verify this and then we can close this.

**Comment by elcallio** [comment]
Ok, verified as false alarm.

**Comment by elcallio** [comment]
Please close this.
