### ISSUE TITLE
TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test failed: Expected a row count of 200000 in table 't_by_v', but got 199307

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4330]
scylla version b8158dd65d3f9cc23865ff15ed8459a93e15761a
dtest version scylladb/scylla-dtest@926728aa195c7532a90eb624f9aca6066b5e6f01

Seen in [dtest-release/56/testReport/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_half_to_max_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/56/testReport/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_half_to_max_test/):
```
Error Message
Expected a row count of 200000 in table 't_by_v', but got 199307

Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 1980, in interrupt_build_process_with_resharding_half_to_max_test
    self._do_resharding_test(str(cpu_count() / 2), str(cpu_count() - 1))
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 2045, in _do_resharding_test
    self.eventually(lambda: assert_row_count(session, 't_by_v', rows, consistency_level=ConsistencyLevel.ALL))
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 49, in eventually
    return fun()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 2045, in <lambda>
    self.eventually(lambda: assert_row_count(session, 't_by_v', rows, consistency_level=ConsistencyLevel.ALL))
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 993, in inner
    return func(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/assertions.py", line 101, in assert_row_count
    expected, table_name, count)
```

**Comment by bhalevy** [comment]
Cc @eliransin

**Comment by psarna** [comment]
Looks like it's flaky for the usual reason - big cassandra-stress-based test (200k rows expected to be checked) + waiting on asynchronous view updates for not enough time. I'll make `eventually()` function's delay exponential

**Comment by bhalevy** [comment]
Similar failure seen in [dtest-release/66/testReport/secondary_indexes_test/TestSecondaryIndexes/test_remove_node_during_index_build](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/66/testReport/secondary_indexes_test/TestSecondaryIndexes/test_remove_node_during_index_build/):
```
Expected a row count of 100000 in table "b_index_index", but got:
 Node: node1, actual count: 99993
 Node: node3, actual count: 99993
 Node: node4, actual count: 99995
 Node: node5, actual count: 99993
```

**Comment by bhalevy** [comment]
Seen in [dtest-release/75/testReport/secondary_indexes_test/TestSecondaryIndexes/test_remove_node_during_index_build](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/testReport/secondary_indexes_test/TestSecondaryIndexes/test_remove_node_during_index_build/):
```
Error Message
Expected a row count of 100000 in table "b_index_index", but got:
 Node: node1, actual count: 99984
 Node: node3, actual count: 99978
 Node: node4, actual count: 99987
 Node: node5, actual count: 99975
```

scylladb/scylla-dtest@394eefcc800e9a28fa14bbd7a6523adae9469397

**Comment by bhalevy** [comment]
@psarna is the following an indication of the same problem?
[dtest-release/75/testReport/materialized_views_test/TestMaterializedViews/add_dc_after_mv_network_replication_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/testReport/materialized_views_test/TestMaterializedViews/add_dc_after_mv_network_replication_test/):
```
Error Message
Expected [[-1055, 1055]] from SELECT * FROM t_by_v WHERE v = -1055, but got []
```

**Comment by psarna** [comment]
most likely yes

**Comment by bhalevy** [comment]
The relevant tests now pass with scylladb/scylla-dtest#1001 so closing this issue.
