### ISSUE TITLE
storage_proxy counters are not updated on cql counter operations

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4337]
Version : Scylla 3.0.3

reproduce 

```
cassandra-stress counter_write no-warmup n=1000 -node 172.17.0.2

curl http://172.17.0.2:9180/metrics | grep write_attempts
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP scylla_storage_proxy_coordinator_read_repair_write_attempts_local_node number of write operations in a read repair contexton a local Node
# TYPE scylla_storage_proxy_coordinator_read_repair_write_attempts_local_node counter
scylla_storage_proxy_coordinator_read_repair_write_attempts_local_node{instance="e484ce6da61b",op_type="mutation_data",shard="0",type="derive"} 0
scylla_storage_proxy_coordinator_read_repair_write_attempts_local_node{instance="e484ce6da61b",op_type="mutation_data",shard="1",type="derive"} 0
scylla_storage_proxy_coordinator_read_repair_write_attempts_local_node{instance="e484ce6da61b",op_type="mutation_data",shard="2",type="derive"} 0
scylla_storage_proxy_coordinator_read_repair_write_attempts_local_node{instance="e484ce6da61b",op_type="mutation_data",shard="3",type="derive"} 0
# HELP scylla_storage_proxy_coordinator_total_write_attempts_local_node total number of write requestson a local Node
# TYPE scylla_storage_proxy_coordinator_total_write_attempts_local_node counter
scylla_storage_proxy_coordinator_total_write_attempts_local_node{instance="e484ce6da61b",op_type="mutation_data",shard="0",type="derive"} 38
scylla_storage_proxy_coordinator_total_write_attempts_local_node{instance="e484ce6da61b",op_type="mutation_data",shard="1",type="derive"} 11
scylla_storage_proxy_coordinator_total_write_attempts_local_node{instance="e484ce6da61b",op_type="mutation_data",shard="2",type="derive"} 7
scylla_storage_proxy_coordinator_total_write_attempts_local_node{instance="e484ce6da61b",op_type="mutation_data",shard="3",type="derive"} 7
100  217k    0  217k    0     0  40.3M      0 --:--:-- --:--:-- --:--:-- 42.4M
[root@e484ce6da61b /]# curl http://172.17.0.2:9180/metrics | grep cql_update
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP scylla_cql_updates Counts a total number of CQL UPDATE requests.
# TYPE scylla_cql_updates counter
scylla_cql_updates{instance="e484ce6da61b",shard="0",type="derive"} 211
scylla_cql_updates{instance="e484ce6da61b",shard="1",type="derive"} 260
scylla_cql_updates{instance="e484ce6da61b",shard="2",type="derive"} 249
scylla_cql_updates{instance="e484ce6da61b",shard="3",type="derive"} 308
100  217k    0  217k    0     0  35.3M      0 --:--:-- --:--:-- --:--:-- 42.4M
[root@e484ce6da61b /]# curl http://172.17.0.2:9180/metrics | grep cql_insert
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  8058    0  8058    0     0  4548k      0 --:--:-- --:--:-- --:--:-- 3934k# HELP scylla_cql_inserts Counts a total number of CQL INSERT requests.
# TYPE scylla_cql_inserts counter
scylla_cql_inserts{instance="e484ce6da61b",shard="0",type="derive"} 8
scylla_cql_inserts{instance="e484ce6da61b",shard="1",type="derive"} 4
scylla_cql_inserts{instance="e484ce6da61b",shard="2",type="derive"} 0
scylla_cql_inserts{instance="e484ce6da61b",shard="3",type="derive"} 0
100  217k    0  217k    0     0  20.8M      0 --:--:-- --:--:-- --:--:-- 21.2M
```

we are doing 1000 CQL updates to counters  and thos are counted in ```scylla_cql_updates``` but the ```scylla_storage_proxy_coordinator_total_write_attempts_local_node``` is not updated

**Comment by gleb-cloudius** [comment]
Storage proxy does not apply local counter mutations, so it does not
count them.

--
			Gleb.

**Comment by slivne** [comment]
Well on reads the numbers seem to be incremented so this is miss-leading

**Comment by mrsinham** [comment]
is this impacting performance or just reporting ? thx

**Comment by bhalevy** [comment]
> is this impacting performance or just reporting ? thx

It's just about statistics accounting, there is no affect on performance.

**Comment by mrsinham** [comment]
Thanks.

**Comment by slivne** [comment]
@slivne ping

**Comment by slivne** [comment]
@amnonh based on glebs input (that he thinks the current method is totally off) we will add a metric specific for this - I suggest that for now if there are batches or counters or lwt you will not provide the info for token awarness in CQL - this will remove the incorrect cases till we have the additional counter in place.

**Comment by slivne** [comment]
@jul-stas - can you synch with @gleb-cloudius on (https://github.com/scylladb/scylla/issues/4337#issuecomment-789661486) the additional metric and where to place it and send a patch.

**Comment by slivne** [comment]
@jul-stas / @gleb-cloudius ping - we need this resolved (so we will have a correct metric)

**Comment by gleb-cloudius** [comment]
On Sat, Mar 13, 2021 at 11:23:30PM -0800, Shlomi Livne wrote:
> @jul-stas / @gleb-cloudius ping - we need this resolved (so we will have a correct metric)
> 
We already have writes_coordinator_outside_replica_set. We need to
update in on counter path as well.

--
			Gleb.

**Comment by jul-stas** [comment]
@slivne Aaaah, I was adding a whole new metric for non-token aware queries :( 
I'll do as @gleb-cloudius says: include counters in `writes_coordinator_outside_replica_set`.

**Comment by slivne** [comment]
On Mon, Mar 15, 2021 at 10:57 AM Juliusz Stasiewicz <
***@***.***> wrote:

> @slivne <https://github.com/slivne> Aaaah, I was adding a whole new
> metric for non-token aware queries :(
> I'll do as @gleb-cloudius <https://github.com/gleb-cloudius> says:
> include counters in writes_coordinator_outside_replica_set.
>

I wasn't aware as well .... and gleb was quiet with providing the info.

**Comment by gleb-cloudius** [comment]
On Mon, Mar 15, 2021 at 02:34:57AM -0700, Shlomi Livne wrote:
> On Mon, Mar 15, 2021 at 10:57 AM Juliusz Stasiewicz <
> ***@***.***> wrote:
> 
> > @slivne <https://github.com/slivne> Aaaah, I was adding a whole new
> > metric for non-token aware queries :(
> > I'll do as @gleb-cloudius <https://github.com/gleb-cloudius> says:
> > include counters in writes_coordinator_outside_replica_set.
> >
> 
> I wasn't aware as well .... and gleb was quiet with providing the info.
> 
I did not remember it exists, but when I looked how to implement one I
found we already have it.

--
			Gleb.

**Comment by avikivity** [comment]
Minor, not backporting.
