### ISSUE TITLE
storage_proxy add a counter for cql requests that arrived to a non replica

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4338]
We are currently computing this as the diff between

scylla_cql_reads - scylla_storage_proxy_coordinator_reads_local_node

yet HWLB may redirect requests - so we need a direct counter for this

**Comment by kostja** [comment]
Suggested counter name: 
scylla_cql_bounced_reads Number of CQL queries that could not be executed locally

**Comment by slivne** [comment]
This counter should count all requests insert/update/delete/query that are replica specific (single partition). 

Schema changes / partition range scans should not be counted.
