### ISSUE TITLE
materialized views: virtual columns in schema may not be propagated correctly

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#4339]
In commit 36a657fc1096af7c56c7fa2606238e6fe0e2cc25, we persisted the list of "virtual columns" in materialized views to a new schema table, VIEW_VIRTUAL_COLUMNS.

However, @psarna noticed that in `db/schema_tables.cc` we forgot to add it to the "ALL" list.  Why does this matter? In private correspondence @psarna  explained that the ALL is used "to propagate schema during migrations" and that without being listed on ALL "the migration manager will not generate mutations from it when somebody issues a migration request, and it will also not be used to calculate schema's md5 to check if it matches, after all view virtual columns information is also a vital part of view schemas.".

By the way it's interesting that although we forgot to add this new virtual-columns table to "ALL", we did remember to add it to `all_tables()`. So we should ask ourselves why we even need both of these lists, if ALL can be trivially calculated from all_tables() (e.g., `all_tables() | boost::adaptors::transformed([] (auto schema) { return schema->cf_name(); })`. Is performance an issue here?

It would be good if we can write a regression test to reproduce this problem (and verify its fix). @psarna noted that:
> I believe the problem will reveal itself when we have two nodes with schema information that has conflicting values in system_schema.view_virtual_columns. Since so far these values are not md5'd, nodes will decide that their schemas' hashes match, so there's no need to resolve any conflicts. And with different virtual columns information, we'd get different columns in select statements, depending on which node performed the query. Also, when one node pulls schema information from another one (e.g. because it have just bootstrapped and needs schema information), it will not pull system_schema.view_virtual_columns at all - and then, as above, the mismatch will never be detected.

Because this problem will only be visible with multiple nodes, unfortunately we'll probably need to test it with a dtest, and not in the current single-node unit test framework.

**Comment by nyh** [comment]
I sent a patch for this issue to the mailing list, titled "Make db::schema_tables::ALL a function".
I have a dtest reproducing the problem, and verifying that it is fixed, but I can only submit that patch after the fixes for #4339 and #4340, on which it relies, are committed.

**Comment by avikivity** [comment]
@nyh please evaluate this patch with respect to backports (e.g. have ALL or all_table_names() changed between 3.0, 3.1, 3.2)

**Comment by avikivity** [comment]
@nyh reminder ^

**Comment by nyh** [comment]
The patch ("materialized_views: propagate "view virtual columns" between nodes) is already in 3.1 and 3.2, so doesn't need backporting there.

It *does* need backporting to 3.0, which includes the problematic patch ("schema: persist "view virtual" columns to a separate system table") which this patch is supposed to fix. The commit even has a "Branches: 3.0" text, but apparently the backport never happened.

I'll backport now.

**Comment by nyh** [comment]
I pushed commit afa2c1b0bf3380d9d797f98793c52f22006155d6 on branch next-3.0.

Unfortunately, I couldn't compile this version, because of compilation errors in Seastar in my modern compiler - I don't remember the proper incantations I should use to compile these old versions (do I need to run a specific old compiler?). So I hope the promotion test will test it for me.

**Comment by avikivity** [comment]
Already backported, removing label.

**Comment by avikivity** [comment]
@nyh look at tools/toolchain/dbuild.
