### ISSUE TITLE
materialized views: allow view without clustering columns

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#4340]
The function `create_view_statement::announce_migration()` does various sanity checks on the the view we are trying to create, among them is:
```c++
    if (_clustering_keys.empty()) {
        throw exceptions::invalid_request_exception(format("No columns are defined for Materialized View other than primary key"));
    }
```
But why do we need or want this test?
We already have a separate test that any of the base table's primary key columns (partition key or clustering key columns) appear as a primary-key column of the view table. So why do we insist here that there be at least one **clustering** key column? Shouldn't we be able to create a view where all the primary key columns are partition-key-columns, and none of them are in a clustering key (so the view has short partitions)?

As a second example, currently we don't allow a case where neither base nor view even have clustering keys. Consider a simple table with just a partition key, and a view which is simply a subset of the columns (with the same key):
```
CREATE TABLE tab (a INT, b INT, c INT, PRIMARY KEY (a));
CREATE MATERIALIZED VIEW mv AS SELECT a,b FROM tab WHERE a IS NOT NULL AND b IS NOT NULL PRIMARY KEY (a)
```
For this we get the error:
```
No columns are defined for Materialized View other than primary key
```
This is not the most useful use-case for materialized views, but why should it not be allowed?

**Comment by nyh** [comment]
By the way this test existed in the original Cassandra code we started with,
```java
        if (targetClusteringColumns.isEmpty())
            throw new InvalidRequestException("No columns are defined for Materialized View other than primary key");
```
but I don't see it in the newest Cassandra code in CreateViewStatement.java. Yet Cassandra users have also recently reported this issue (maybe on older Cassandra?) see  this issue: https://issues.apache.org/jira/browse/CASSANDRA-13564 https://issues.apache.org/jira/browse/CASSANDRA-13857 and patch in https://github.com/apache/cassandra/compare/trunk...aivakov:CASSANDRA-13857 (I'm not sure why all these issues are still alive in Cassandra if I don't see the bug in their new code, maybe I'm missing something)

**Comment by duarten** [comment]
I don't understand why we would want the view in your example, since all queries that can be performed on it can also be performed on the base table.

I agree though that the check is not needed.
