### ISSUE TITLE
scylla-ena driver is broken on 3.0/master AMI

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#4356]
ENA driver doesn't built since dkms.conf is missing: 
```
    amazon-ebs: Error! Could not locate dkms.conf file.
    amazon-ebs: File: /usr/src/ena-2.0.2/dkms.conf does not exist.
    amazon-ebs: Error! Could not locate dkms.conf file.
    amazon-ebs: File: /usr/src/ena-2.0.2/dkms.conf does not exist.
```

**Comment by syuu1228** [comment]
scylla-ena-2.0.2-1dkms rpm was corrupted, fixed rpm scylla-ena-2.0.2-2dkms is released on Copr.

**Comment by syuu1228** [comment]
Checked AMI image "ScyllaDB 3.0.4 (ami-0031e31faf043f1cd)", it's failed to build ENA driver but kernel-ml-5.0.1-1.el7.elrepo.x86_64 contains ENA "v2.0.3K", so the AMI image works finely on ENA based instance types.

**Comment by slivne** [comment]
so do we need to build the ena driver at all ? or should we use the one from the kernel ?

**Comment by slivne** [comment]
@syuu1228 / @avi ping

**Comment by syuu1228** [comment]
@slivne On branch-3.1 / master we just dropped scylla-ixgbevf and scylla-ena, use the driver on kernel-ml:
https://github.com/scylladb/scylla-ami/commit/45172331ed690a0a87fb4bf94e6fa51b61f58cb0
On branch-3.0, we should backport same patch but looks like we haven't do that.
@avikivity could you merge https://github.com/scylladb/scylla-ami/commit/45172331ed690a0a87fb4bf94e6fa51b61f58cb0 to branch-3.0?

**Comment by slivne** [comment]
backported as scylladb/scylla-ami@dee79e5fc4516d169c4e0378c2544e43cae6ff46
