### ISSUE TITLE
repair_abort_test failed: Node is not in NORMAL status yet!

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4359]
scylla version 57521747626903f0d37c75bbb702826c57fe71d4
scylla-dtest version scylladb/scylla-dtest@0d225442d4be6fb2bad830cb9cc0b9744208f831

Seen in [dtest-release/65/testReport/repair_additional_test/RepairAdditionalTest/repair_abort_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/65/testReport/repair_additional_test/RepairAdditionalTest/repair_abort_test/)
```
Error Message
23 Mar 2019 04:16:48 [node3] Missing: ['Repair 5 out of']:
...
dtest: DEBUG: repair_additional_test.RepairAdditionalTest.repair_abort_testrepair_abort_test - Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/resources/cassandra/bin/nodetool -h localhost -p 7368 repair ks' failed; exit status: 2; stderr: error: Scylla API server HTTP POST to URL '/storage_service/repair_async/ks' failed: Node is not in NORMAL status yet!
```

**Comment by slivne** [comment]
according to @asias this is probably a timing issue in the tests - and we need to update the test code

**Comment by asias** [comment]
Same dtest issue that misses "wait_for_binary_proto=True" when starting scylla node:

scylladb/scylla-dtest#916
https://github.com/scylladb/scylla/issues/4360

With the fix below to dest, i see no issues.

```
--- a/repair_additional_test.py
+++ b/repair_additional_test.py
@@ -1751,7 +1751,7 @@ class RepairAdditionalBase(Tester):
                     assert len(result) <= less_than_num
 
                 for node in stopped_nodes:
-                    node.start(wait_other_notice=True)
+                    node.start(wait_other_notice=True, wait_for_binary_proto=True)
 
         def repair_thread(more_options, repair_uses_stream):
             try:
diff --git a/repair_test.py b/repair_test.py
```

**Comment by asias** [comment]
dtest fix: https://github.com/scylladb/scylla-dtest/pull/917

**Comment by slivne** [comment]
@asias - so scylla is actually behaving correctly - e.g. not allowing running repair if the node is not in normal state - right ?

**Comment by asias** [comment]
> @asias - so scylla is actually behaving correctly - e.g. not allowing running repair if the node is not in normal state - right ?

Yes, Scylla is behaving correctly. 

> 
> If this is the case - I think a test checking this out will be usefull as well.

Yes, we could.

**Comment by slivne** [comment]
@asias - so lets create a dtest issue for this - since its not clear howto catch this exact state

**Comment by asias** [comment]
it is here: https://github.com/scylladb/scylla-dtest/issues/947
