### ISSUE TITLE
nodetool stop

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#436]
Stops the compaction process.
http://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsStopDaemon.html

The only way to stop a run away compaction process

**Comment by slivne** [comment]
@tzach  this is not in the API Workplan worksheet do we need this  for GA ?

**Comment by raphaelsc** [comment]
I forgot to mention this issue in my patchset, but this issue can be closed after: 5e953b5

**Comment by penberg** [comment]
@raphaelsc We only support the ``COMPACTION`` compaction type, right? @tzach, is that sufficient for closing the issue?

**Comment by raphaelsc** [comment]
On Fri, Jan 22, 2016 at 5:14 AM, Pekka Enberg <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> We only support the COMPACTION
> compaction type, right?
>
Also CLEANUP.


> @tzach <https://github.com/tzach>, is that sufficient for closing the
> issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/436#issuecomment-173830737>.
>



-- 
Raphael S. Carvalho

**Comment by tzach** [comment]
@amnonh @raphaelsc I vaguely remember this was fix
Is it so?

**Comment by tzach** [comment]
@amnonh 'nodetool stop' for compaction is merged.
If it is tested I will close this.

**Comment by amnonh** [comment]
I didn't test it and don't have a test for it yet, but I understand that it
is working.

I'm working on adding tests, so I'll let you know when I'll add a test for
it

**Comment by tzach** [comment]
@amnonh do you have a test?

**Comment by slivne** [comment]
@amnonh ping

**Comment by amnonh** [comment]
I don't

**Comment by tzach** [comment]
Closing this feature request, as it is done and documented.
We will open a new issue if any future test fails.
