### ISSUE TITLE
dc_repair_test: Assertion `local_is_initialized()' failed

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4360]
scylla version 57521747626903f0d37c75bbb702826c57fe71d4
scylla-dtest version scylladb/scylla-dtest@0d225442d4be6fb2bad830cb9cc0b9744208f831

Seen in [dtest-release/65/testReport/repair_test/TestRepair/dc_repair_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/65/testReport/repair_test/TestRepair/dc_repair_test/)
and [dtest-release/65/testReport/repair_test/TestRepair/local_dc_repair_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/65/testReport/repair_test/TestRepair/local_dc_repair_test/)

```
Error Message
Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/resources/cassandra/bin/nodetool -h localhost -p 7130 repair -dc dc1 -dc dc2 -seq -full ks' failed; exit status: 2; stdout: [2019-03-23 04:53:31,980] Starting repair command #1, repairing 1 ranges for keyspace ks (parallelism=SEQUENTIAL, full=true)
[2019-03-23 04:53:33,099] Repair session 1 failed
[2019-03-23 04:53:33,099] Repair session 1 finished
; stderr: error: Repair job has failed with the error message: [2019-03-23 04:53:33,099] Repair session 1 failed
```

[node2.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/65/artifact/logs-release.2/1553316813832_repair_test.TestRepair.dc_repair_test/node2.log):
```
scylla: /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/sharded.hh:560: Service& seastar::sharded<T>::local() [with Service = db::system_distributed_keyspace]: Assertion `local_is_initialized()' failed.
Aborting on shard 1.
Backtrace:
  0x000000000423bbc2
  0x0000000004139075
  0x0000000004139375
  0x0000000004139423
  0x00007fda5e2a702f
  /lib64/libc.so.6+0x000000000003853e
  /lib64/libc.so.6+0x0000000000022894
  /lib64/libc.so.6+0x0000000000022768
  /lib64/libc.so.6+0x00000000000309f5
  0x0000000003583658
  0x00000000037a6ef4
  0x0000000004136501
  0x00000000041366fe
  0x000000000420bab5
  0x0000000004232aeb
  0x000000000410619d
  /lib64/libpthread.so.0+0x000000000000858d
  /lib64/libc.so.6+0x00000000000fd6a2

std::_Function_handler<seastar::future<> (flat_mutation_reader), repair_writer::create_writer(unsigned int)::{lambda(flat_mutation_reader)#2}>::_M_invoke(std::_Any_data const&, flat_mutation_reader&&) at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/sharded.hh:560
 (inlined by) repair_writer::create_writer(unsigned int)::{lambda(flat_mutation_reader)#2}::operator()(flat_mutation_reader) const at /jenkins/workspace/scylla-master/dtest-release/scylla/repair/row_level.cc:394
 (inlined by) std::_Function_handler<seastar::future<> (flat_mutation_reader), repair_writer::create_writer(unsigned int)::{lambda(flat_mutation_reader)#2}>::_M_invoke(std::_Any_data const&, flat_mutation_reader&&) at /usr/include/c++/8/bits/std_function.h:283
seastar::continuation<seastar::future<mutation_fragment*>::then_impl<shard_writer::consume()::{lambda(mutation_fragment*)#1}, seastar::future<> >(shard_writer::consume()::{lambda(mutation_fragment*)#1}&&)::{lambda(auto:1)#1}, mutation_fragment*>::run_and_dispose() at /usr/include/c++/8/bits/std_function.h:687
 (inlined by) operator() at /jenkins/workspace/scylla-master/dtest-release/scylla/multishard_writer.cc:118
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:35
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/apply.hh:43
 (inlined by) ?? at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1478
 (inlined by) operator()<seastar::future_state<mutation_fragment*> > at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:1015
 (inlined by) run_and_dispose at /jenkins/workspace/scylla-master/dtest-release/scylla/seastar/include/seastar/core/future.hh:425
```

Seen also in

**Comment by slivne** [comment]
@asias ping

**Comment by asias** [comment]
It is caused by _sys_dist_ks is not initialized when repair runs.

**Comment by asias** [comment]
The test does:
```
cluster = self._setup_multi_dc
node1.repair

```
In line 389,  we call self.check_rows_on_node()
```
353     def _setup_multi_dc(self):
354         """
355         Sets up 3 DCs (2 nodes in 'dc1', and one each in 'dc2' and 'dc3').
356         After set up, node2 in dc1 lacks some data and needs to be repaired.
357         """
358         cluster = self.cluster
359 
360         # Disable hinted handoff and set batch commit log so this doesn't
361         # interfer with the test (this must be after the populate)
362         cluster.set_configuration_options(values={'hinted_handoff_enabled': False}, batch_commitlog=True)
363         debug("Starting cluster..")
364         # populate 2 nodes in dc1, and one node each in dc2 and dc3
365         cluster.populate([2, 1, 1]).start()
366 
367         [node1, node2, node3, node4] = cluster.nodelist()
368         session = self.patient_cql_connection(node1)
369         session.execute("CREATE KEYSPACE ks WITH replication = {'class': 'NetworkTopologyStrategy', 'dc1': 2, 'dc2': 1, 'dc3':1};")
370         session.execute("USE ks")
371         self.create_cf(session, 'cf', read_repair=0.0, columns={'c1': 'text', 'c2': 'text'})
372 
373         # Insert 1000 keys, kill node 3, insert 1 key, restart node 3, insert 1000 more keys
374         debug("Inserting data...")
375         insert_c1c2(session, n=1000, consistency=ConsistencyLevel.ALL)
376         node2.flush()
377         node2.stop(wait_other_notice=True)
378         insert_c1c2(session, keys=(1000, ), consistency=ConsistencyLevel.THREE)
379         node2.start(wait_for_binary_proto=True, wait_other_notice=True)
380         node1.watch_log_for_alive(node2)
381         insert_c1c2(session, keys=range(1001, 2001), consistency=ConsistencyLevel.ALL)
382 
383         cluster.flush()
384 
385         # Verify that only node2 has only 2000 keys and others have 2001 keys
386         debug("Checking data...")
387         self.check_rows_on_node(node2, 2000, missings=[1000])
388         for node in [node1, node3, node4]:
389             self.check_rows_on_node(node, 2001, found=[1000])
390         return cluster
```

In check_rows_on_node, we start the node without waiting for the cql is ready. So we start repair on node1 when node2 is not ready yet. So we see the abort. 

```
 19     def check_rows_on_node(self, node_to_check, rows, found=None, missings=None, restart=True):
 20         if found is None:
 21             found = []
 22         if missings is None:
 23             missings = []
 24         stopped_nodes = []
 25 
 26         for node in self.cluster.nodes.values():
 27             if node.is_running() and node is not node_to_check:
 28                 stopped_nodes.append(node)
 29                 node.stop(wait_other_notice=True)
 30 
 31         session = self.patient_cql_connection(node_to_check, 'ks')
 32         result = list(session.execute("SELECT * FROM cf LIMIT %d" % (rows * 2)))
 33         self.assertEqual(len(result), rows, len(result))
 34 
 35         for k in found:
 36             query_c1c2(session, k, ConsistencyLevel.ONE)
 37 
 38         for k in missings:
 39             query = SimpleStatement("SELECT c1, c2 FROM cf WHERE key='k%d'" % k, consistency_level=ConsistencyLevel.ONE)
 40             res = list(session.execute(query))
 41             self.assertEqual(len(filter(lambda x: len(x) != 0, res)), 0, res)
 42 
 43         if restart:
 44             for node in stopped_nodes:
 45                 node.start(wait_other_notice=True)
```

With the patch below, I do not see the abort any more.
```
--- a/repair_test.py
+++ b/repair_test.py
@@ -42,7 +42,7 @@ class TestRepair(Tester):
 
         if restart:
             for node in stopped_nodes:
-                node.start(wait_other_notice=True)
+                node.start(wait_other_notice=True, wait_for_binary_proto=True)
 
     @since('2.2.1')
     @skip('Scylla does not support anticompaction.')
```

**Comment by asias** [comment]
So, we should 1) fix dtest that make sure node is fully started 2) fix scylla to reject repair if node is not fully initialized.

**Comment by bhalevy** [comment]
scylladb/scylla-dtest#916 opened for the dtest fix.
Let keep this issue for the scylla part.

**Comment by asias** [comment]
dtest fix: https://github.com/scylladb/scylla-dtest/pull/917

**Comment by juliayakovlev** [comment]
Received similar error during MV backpressure test. Issue https://github.com/scylladb/scylla/issues/4381

**Comment by bhalevy** [comment]
> Received similar error during MV backpressure test. Issue #4381

@juliayakovlev was it with scylladb/scylla-dtest#917 merged?

**Comment by juliayakovlev** [comment]
@bhalevy 
> > Received similar error during MV backpressure test. Issue #4381
> 
> @juliayakovlev was it with [scylladb/scylla-dtest#917](https://github.com/scylladb/scylla-dtest/pull/917) merged?

It was SCT test, not dtest

**Comment by bhalevy** [comment]
@slivne noted that this was hit in [branch-3.0](http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/scylla-dtest/label=scylla-dtest,mode=release,smp=2/118/artifact/urchin-dtest/logs-release.2/1554226089392_repair_test.TestRepair.local_dc_repair_test/node2.log) as well.

**Comment by asias** [comment]
@bhalevy can you help to decode ?

```
http://jenkins.cloudius-systems.com:8080/job/scylla-3.0/job/scylla-dtest/label=scylla-dtest,mode=release,smp=2/118/artifact/urchin-dtest/logs-release.2/1554226089392_repair_test.TestRepair.local_dc_repair_test/node2.log
```

**Comment by bhalevy** [comment]
$ addr2line -Cfpi -e scylla-4360 
  0x00000000035514ad
  0x0000000003947782
  0x000000000059cf8e
  0x000000000059d151
  0x000000000066a297
  0x000000000068d83a
  0x00000000007430fd
std::_Function_handler<seastar::future<> (flat_mutation_reader), streaming::stream_session::init_messaging_service_handler()::{lambda(seastar::rpc::client_info const&, utils::UUID, utils::UUID, utils::UUID, unsigned long, seastar::rpc::optional<streaming::stream_reason>, seastar::rpc::source<frozen_mutation_fragment>)#4}::operator()(seastar::rpc::client_info const&, utils::UUID, utils::UUID, utils::UUID, unsigned long, seastar::rpc::optional<streaming::stream_reason>, seastar::rpc::source<frozen_mutation_fragment>) const::{lambda()#1}::operator()()::{lambda(seastar::lw_shared_ptr<schema const>)#1}::operator()(schema)::{lambda(flat_mutation_reader)#2}>::_M_invoke(std::_Any_data const&, flat_mutation_reader&&) at /jenkins/workspace/scylla-3.0/scylla-dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/core/sharded.hh:540
 (inlined by) operator() at /jenkins/workspace/scylla-3.0/scylla-dtest/label/scylla-dtest/mode/release/smp/2/scylla/streaming/stream_session.cc:242
 (inlined by) _M_invoke at /usr/include/c++/7/bits/std_function.h:302
seastar::continuation<seastar::future<mutation_fragment*>::then<shard_writer::consume()::{lambda(mutation_fragment*)#1}, seastar::future<> >(shard_writer::consume()::{lambda(mutation_fragment*)#1}&&)::{lambda(auto:1)#1}, mutation_fragment*>::run_and_dispose() at /usr/include/c++/7/bits/std_function.h:706
 (inlined by) operator() at /jenkins/workspace/scylla-3.0/scylla-dtest/label/scylla-dtest/mode/release/smp/2/scylla/multishard_writer.cc:118
 (inlined by) ?? at /jenkins/workspace/scylla-3.0/scylla-dtest/label/scylla-dtest/mode/release/smp/2/scylla/./seastar/core/apply.hh:35
 (inlined by) ?? at /jenkins/workspace/scylla-3.0/scylla-dtest/label/scylla-dtest/mode/release/smp/2/scylla/./seastar/core/apply.hh:43
 (inlined by) ?? at /jenkins/workspace/scylla-3.0/scylla-dtest/label/scylla-dtest/mode/release/smp/2/scylla/./seastar/core/future.hh:1389
 (inlined by) operator()<seastar::future_state<mutation_fragment*> > at /jenkins/workspace/scylla-3.0/scylla-dtest/label/scylla-dtest/mode/release/smp/2/scylla/./seastar/core/future.hh:963
 (inlined by) run_and_dispose at /jenkins/workspace/scylla-3.0/scylla-dtest/label/scylla-dtest/mode/release/smp/2/scylla/./seastar/core/future.hh:414
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /jenkins/workspace/scylla-3.0/scylla-dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/core/reactor.cc:2695
seastar::reactor::run_some_tasks() [clone .part.2768] at /jenkins/workspace/scylla-3.0/scylla-dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/core/reactor.cc:3118
seastar::reactor::run() at /jenkins/workspace/scylla-3.0/scylla-dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/util/log.hh:313
 (inlined by) seastar::reactor::run() at /jenkins/workspace/scylla-3.0/scylla-dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/core/reactor.cc:3265
seastar::smp::configure(boost::program_options::variables_map)::{lambda()#3}::operator()() const at /jenkins/workspace/scylla-3.0/scylla-dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/core/reactor.cc:4334
seastar::posix_thread::start_routine(void*) at /usr/include/c++/7/bits/std_function.h:706
 (inlined by) seastar::posix_thread::start_routine(void*) at /jenkins/workspace/scylla-3.0/scylla-dtest/label/scylla-dtest/mode/release/smp/2/scylla/seastar/core/posix.cc:52
```

**Comment by asias** [comment]
@bhalevy Thanks. I think I know what is going on. We have similar issue in 3.0 where _sys_dist_ks is not fully initialized. 

Analysis:
sys_dist_ks is initialized in storage_service::join_token_ring during boot up. At this point, this node already has started the gossip service and message service, other nodes can run repair or streaming against this node.

**Comment by asias** [comment]
@psarna can we init sys_dist_ks much earlier?

**Comment by psarna** [comment]
@asias we definitely should init it before we allow streaming, as it depends on sys_dist_ks now, after we added view update generation during streaming. I already moved it to be initialized earlier in ca5dfdffc6, but it's not easy for me to decode all hidden dependencies here.
Do you have any idea where it should be initialized in order to avoid broken dependencies and dependency cycles? I see that sys_dist_ks depends on query_processor and migration_manager directly, but hidden dependencies like repair are  way harder to find.

**Comment by asias** [comment]
Patch for streaming is on list: [PATCH scylla v1] streaming: Reject stream if the _sys_dist_ks or _view_update_generator are not ready

Patch for repair is on list: [PATCH scylla v1] repair: Reject repair if the _sys_dist_ks or _view_update_generator are not ready

We need to backport [PATCH scylla v1] streaming: Reject stream if the _sys_dist_ks or _view_update_generator are not ready to 3.0 branch.

**Comment by asias** [comment]
> @asias we definitely should init it before we allow streaming, as it depends on sys_dist_ks now, after we added view update generation during streaming. I already moved it to be initialized earlier in [ca5dfdf](https://github.com/scylladb/scylla/commit/ca5dfdffc67b44fe74633bd74227e77b907f7a87), but it's not easy for me to decode all hidden dependencies here.
> Do you have any idea where it should be initialized in order to avoid broken dependencies and dependency cycles? I see that sys_dist_ks depends on query_processor and migration_manager directly, but hidden dependencies like repair are way harder to find.

If _sys_dist_ks and _view_update_generator only depends on   query_processor and migration_manager, init them after query_processor and migration_manager are initialized. 

repair and streaming are user of _sys_dist_ks and _view_update_generator.
