### ISSUE TITLE
counter can't be updated correctly

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#4362]
*Installation details*
Scylla version (or git commit hash): 3.0.4-0.20190313.5e3a52024
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

1. prepare a cluster with 4 nodes
2.  create keyspace
CREATE KEYSPACE keyspace1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}
3. create table
CREATE TABLE counters_test (userid int, url text, total counter, PRIMARY KEY (userid, url)) WITH COMPACT STORAGE;

4. init the value
```
UPDATE counters_test SET total = total + 1 WHERE userid = 1 AND url = 'http://foo.com'
SELECT total FROM counters_test WHERE userid = 1 AND url = 'http://foo.com'
expected result 1
```

5. execute update tests

```
UPDATE counters_test SET total = total - 4 WHERE userid = 1 AND url = 'http://foo.com'
SELECT total FROM counters_test WHERE userid = 1 AND url = 'http://foo.com'
expected result -3

UPDATE counters_test SET total = total+1 WHERE userid = 1 AND url = 'http://foo.com'
SELECT total FROM counters_test WHERE userid = 1 AND url = 'http://foo.com'
expected result -2

UPDATE counters_test SET total = total -2 WHERE userid = 1 AND url = 'http://foo.com'
SELECT total FROM counters_test WHERE userid = 1 AND url = 'http://foo.com'
expected result -4
```

Real result:
The query result isn't same as expected in step 5.

@pdziepak

**Comment by amoskong** [comment]
Test job: http://jenkins.cloudius-systems.com:8080/job/enterprise-2019.1/job/rolling-ugrades-tests/job/rolling-upgrade-centos-test/16/base_version=3.0,label=gce3-qavpc,test_sst3=false,version_desc=2019-1/console

```
20:42:26 query: SELECT total FROM counters_test WHERE userid = 1 AND url = 'http://foo.com'
20:42:26 result: [[1]]
20:42:26 expect: [[1]]
20:42:26 query: UPDATE counters_test SET total = total - 4 WHERE userid = 1 AND url = 'http://foo.com'
20:42:26 result: []
20:42:26 expect: []
20:42:26 query: SELECT total FROM counters_test WHERE userid = 1 AND url = 'http://foo.com'
20:42:26 result: [[1]]
20:42:26 expect: [[-3]]
20:42:26 SELECT total FROM counters_test WHERE userid = 1 AND url = 'http://foo.com' Lists differ: [[1]] != [[-3]]
20:42:26 
20:42:26 First differing element 0:
20:42:26 [1]
20:42:26 [-3]
20:42:26 
20:42:26 - [[1]]
20:42:26 + [[-3]]
```

**Comment by slivne** [comment]
your replication is RF=3 - which CL are you using for read and write.

IF the CL is QUORUM / LOCAL_QUORUM you should get results back.

**Comment by amoskong** [comment]
IN SCT, the default_consistency_level is set to `ConsistencyLevel.ONE`.

I will try with QUORUM / LOCAL_QUORUM

**Comment by amoskong** [comment]
When I set default_consistency_level to QUORUM / LOCAL_QUORUM, this issue doesn't exist.

@slivne then it's not a bug?

**Comment by amoskong** [comment]
@slivne ping

**Comment by roydahan** [comment]
I think we can close due to eventual consistency.
