### ISSUE TITLE
hints attempts to send a broken segment forever

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#4364]
*Installation details*
HEAD: ddf795d2f93c18997beef6ee54ff4457cfb8947b
The same as in #4231 

*Description*
If HH stumbles upon the corrupted segment (e.g. due to #4231) it will attempt to send it forever since it interprets any exception as a failure to send the hint.

We need to handle this case separately and drop a corrupted segment since there is nothing we can do about it.

We should definitely log such events and it will also be beneficiary to have a metric that would account such events.

**Comment by slivne** [comment]
ML: "hinted handoff: discard corrupted segments"

**Comment by bhalevy** [comment]
Backported to 3.1 in ac0d435c3e2d68d6e380afe224490751044ab2cf

**Comment by bhalevy** [comment]
@tgrabiec looks like this still needs backporting to 3.0

**Comment by avikivity** [comment]
In 3.0 as 79c7015cce08f0d309746cad2e00f3c8972f31fe.
