### ISSUE TITLE
Allow synchronous updates for materialized views with partition key the same as base's

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#4365]
If the partition key of a materialized view matches the one from its base, view updates will always be applied locally for this view. We can take advantage of this fact and allow applying these updates synchronously in order to provide stronger guarantees for the user.

A special case of a materialized view with partition key matching its base is local indexing: #4185 

/cc @nyh /cc @dekimir

**Comment by nyh** [comment]
Just to clarify what these "stronger guarantees" we can provide are:
Today when a writes with CL=QUORUM to a base table successfully completes, a read with CL=QUORUM is guaranteed to return the latest value. However, if we now read from a materialized view or use a secondary index, we have no such guarantee... The view updates are done asynchronously (without the client waiting for them), and we don't know how much time it will take after the request returns for the new data to be visible in a view or index.
As @psarna said above, for the special case when the views's partition key is the same as the the base's, the view updates are guaranteed to be local, and we can actually do the view update synchronously (wait for it before considering the base update done), without sacrificing high-availability.
We should consider whether the synchronicity in this case optional (some sort of table option?) or on by default.

**Comment by slivne** [comment]
with regards to LSI what guarantees does Cassandra provide for LSI. I assume they do the updates in a synchronized manner (even as a single commitlog entry).

**Comment by avikivity** [comment]
We can go even further, and store local views in the same partition. We can do this by prefixing an implicit clustering key column to the clustering key; this new column designates which view we're addressing now. It can also take a "base" value for addressing base rows.

partition:
   base ck1 ck2 r1 r2 r3
   base ck1 ck2 r1 r2 r3
   view1 r2 ck1 ck2
   view1 r2 ck1 ck2
   view2 ck2 ck1

corresponding to view1 with key ((pk), r2) and view2 with key ((pk), ck2).

The advantage is that smaller partitions can be indexed with one disk read; the disadvantage is that scans will have to skip over local views.

**Comment by psarna** [comment]
I have a half-finished RFC branch, which I'm going to leave here just in case, while I'm busy with higher priorities: https://github.com/psarna/scylla/tree/allow_synchronous_view_updates_for_local_views
The list of todos is listed in the commit message of the last patch.

**Comment by psarna** [comment]
@eliransin update: I totally forgot that I have an RFC for it, but it looks like I do, so I'll just pursue it one day, once I'm done with other priorities. I think I'll go with using tags to enable/disable synchronous view updates, now that we have them from alternator.
