### ISSUE TITLE
Record in the system.large_partitions isn't removed after the sstable was deleted

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#4371]
*Installation details*
Scylla version (or git commit hash): /home/juliay/.dtest/dtest-u1KV38/test/node4/data/wide_row/user_events-e2c7ed50514411e99495000000000000
Cluster size: 4 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): fedora

Run test (in the dtest) for large partition detector.
Scenario:
- start 4 nodes cluster with 'compaction_large_partition_warning_threshold_mb'=4
- create partition with RF=3
- create the table as:
```
CREATE TABLE wide_row.user_events (userid text, event timestamp, value blob, 
PRIMARY KEY (userid, event)) with compression = { }
```
- insert 10 partitions with 60000 row in each partition. Blob column size is 1K
- cluster.flush
- run select from system.large_partitions on every node:
```
select partition_key, sstable_name, partition_size from system.large_partitions
```
I expected partition size is about 62400000 byte.
But on the one node I found that for one partition it's reported about 2 different sstables. But "mc-4-big-Data.db" file doesn't exist (assume, it was compacted). But it still exists in system.large_partitions
```
user7 | /home/juliay/.dtest/dtest-u1KV38/test/node4/data/wide_row/user_events-e2c7ed50514411e99495000000000000/mc-14-big-Data.db |       62760019
user7 |  /home/juliay/.dtest/dtest-u1KV38/test/node4/data/wide_row/user_events-e2c7ed50514411e99495000000000000/mc-4-big-Data.db |       36553535
```
It doesn't happen every run

**Comment by slivne** [comment]
large partition table is written in compaction - as such if the same partition is recompacted then the record remains.

@bhalevy AFAIK we did not do any change to remove records when sstables are removed

**Comment by bhalevy** [comment]
@slivne the record is supposed to be deleted when the sstable is deleted since it contains the actual sstable file name.  If the large partition/row/cell is compacted into a new sstable the old record is supposed to be deleted and a new one should be created, pointing to the new, compacted sstable, if the partition/row/cell are still large above the respective threshold.

Cc @espindola

**Comment by bhalevy** [comment]
That said, we don't wait for the deletion to happen synchronously so if the test exits (did it, @juliayakovlev?) the record might still be there.

**Comment by espindola** [comment]
This is tested in cql_query_test.cc:test_large_data. From the test:

        // In order to guarantee that system.large_rows has been updated, we have to                                                                                                                                                          
        // * flush, so that a thumbstone for the above delete is created.                                                                                                                                                                     
        // * do a major compaction, so that the thumbstone is combined with the old entry.                                                                                                                                                    
        // * stop the db, as only then do we wait for sstable deletions.

**Comment by juliayakovlev** [comment]
> That said, we don't wait for the deletion to happen synchronously so if the test exits (did it, @juliayakovlev?) the record might still be there.
> 
> Ref #4264

@bhalevy 

As @espindola  described above:
```
In order to guarantee that system.large_rows has been updated, we have to flush
```
The test flush the data before select from system.large_partitions. 
How can I recognize that  the deletion was completed?

**Comment by bhalevy** [comment]
> > That said, we don't wait for the deletion to happen synchronously so if the test exits (did it, @juliayakovlev?) the record might still be there.
> > Ref #4264
> 
> @bhalevy
> 
> As @espindola described above:
> 
> ```
> In order to guarantee that system.large_rows has been updated, we have to flush
> ```
> 
> The test flush the data before select from system.large_partitions.
> How can I recognize that the deletion was completed?

@juliayakovlev we may need something like `block_on_compaction_log` in compation_test.py that runs major compaction after `node.flush` to make sure the wide data system tables are written.

**Comment by espindola** [comment]
> @juliayakovlev we may need something like `block_on_compaction_log` in compation_test.py that runs major compaction after `node.flush` to make sure the wide data system tables are written.

I don't think that is sufficient. You have to wait for sstable deletion, and the only way to do that from the outside is to shutdown the database. It might also be possible to just look at the filesystem to see that the files were deleted and then do a full compaction, but it is probably a good idea to audit the code to make sure that is really sufficient.

**Comment by bhalevy** [comment]
On Mon, Jul 15, 2019, 19:16 Rafael Ávila de Espíndola <
notifications@github.com> wrote:

> @juliayakovlev <https://github.com/juliayakovlev> we may need something
> like block_on_compaction_log in compation_test.py that runs major
> compaction after node.flush to make sure the wide data system tables are
> written.
>
> I don't think that is sufficient. You have to wait for sstable deletion,
> and the only way to do that from the outside is to shutdown the database.
> It might also be possible to just look at the filesystem to see that the
> files were deleted and then do a full compaction, but it is probably a good
> idea to audit the code to make sure that is really sufficient.
>
on_compaction_completion acquires the _sstable_deletion_sem so it should
serialize the actual deletions by delete_atomically

**Comment by bhalevy** [comment]
Hmm, I'm actually not sure about the above...

**Comment by espindola** [comment]
> Hmm, I'm actually not sure about the above...

If it is now possible to test for deletions without stopping the db we should update test_large_data in cql_query_test.cc to do that instead, as it is a more strict guarantee and we should test it.

**Comment by slivne** [comment]
@bhalevy in 4.4 / master is this fixed ? - do we remove the records ?

**Comment by avikivity** [comment]
It was reverted due to the range tombstones problem.

**Comment by bhalevy** [comment]
@avikivity what fix do you refer to?

I think that we can consider 8dd6e13468c6cc6fb3c222e665f2a60fe69f0e9b (that fixed #4909) a fix to this issue.

To start with, the original scenario described by @juliayakovlev had no explicit compaction involved, just flush, so there's no synchronization point after which we can require system.large_* to be consistent with whatever we see on the file system.

8dd6e13468c6cc6fb3c222e665f2a60fe69f0e9b provides this synchronization point by waiting for the ssatble deletes on compaction completion. `sstable::unlink` updates the large data tables when the sstable is removed, so they should agree with the state on disk after compaction.

**Comment by avikivity** [comment]
I don't think we delete from the large data tables at all, due to the range tombstones problem.

Ah, in master we do: 64a4ffc579f90bf9fd0fe2cc6adf33bfee524614.

I can't tell which version this was reported against.

**Comment by slivne** [comment]
closing this issue - its still not great since we will generate range-tombstones in the case we do have large partitions - and range-tombstones have multiple issues
