### ISSUE TITLE
nodetool describecluster

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#438]
Provide the name, snitch, partitioner and schema version of a cluster
http://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsDescribeCluster.html

This command is required when looking for Handling schema disagreements
http://docs.datastax.com/en/cassandra/2.1/cassandra/troubleshooting/trblshootSchemaDisagree.html

**Comment by slivne** [comment]
@amnonh can we close this ?
