### ISSUE TITLE
mv_populating_from_existing_data_during_node_stop_test failed: View ks.tm_table_mv_2 not built

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4382]
Scylla version 77a0d5c5da46521d70a29df62338ee27f6b5a518
scylladb/scylla-dtest@3d5f8781ba2ce9cd9053cc7d615a8aef695a1972

Seen in [next/668/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/next/668/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test/):
```
Error Message
View ks.tm_table_mv_2 not built

Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/materialized_views_test.py", line 587, in mv_populating_from_existing_data_during_node_stop_test
    self._mv_populating_from_existing_data_during_changes_test('stop node', nodes=4, rf=3, mvs=10, prefill=40000, fail=False)
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/materialized_views_test.py", line 653, in _mv_populating_from_existing_data_during_changes_test
    wait_for_view(cluster=self.cluster, session=session, ks=tm.keyspace, view=mv_name)
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/scylla_tools.py", line 905, in wait_for_view
    raise Exception(error_msg)
```

Node logs are [here](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/next/668/artifact/logs-release.2/1554102223280_materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_node_stop_test/)

**Comment by bhalevy** [comment]
Also in the next try [next/668/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test_2](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/next/668/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test_2/):
```
Unexpected error in node3 node log: ["ERROR 2019-04-01 07:00:24,072 [shard 1] view - Error applying view update to 127.0.77.3: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID d217b440-544b-11e9-83d8-000000000000): std::out_of_range (_Map_base::at)\nERROR 2019-04-01 07:00:24,072 [shard 0] view - Error applying view update to 127.0.77.3: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID d217b440-544b-11e9-83d8-000000000000): std::out_of_range (_Map_base::at)\nWARN  2019-04-01 07:00:24,072 [shard 1] view - Error executing build step for base ks.tm_table: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID d217b440-544b-11e9-83d8-000000000000): std::out_of_range (_Map_base::at)\nWARN  2019-04-01 07:00:24,072 [shard 0] view - Error executing build step for base ks.tm_table: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID d217b440-544b-11e9-83d8-000000000000): std::out_of_range (_Map_base::at)"]

Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 396, in run
    self.tearDown()
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/dtest.py", line 725, in tearDown
    raise AssertionError('Unexpected error in %s node log: %s' % (node.name, errors))
```

**Comment by bhalevy** [comment]
Seen also in [dtest-release/75/testReport/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_half_to_max_test](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/testReport/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_half_to_max_test/):
```
Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release@2/scylla-dtest/materialized_views_test.py", line 1982, in interrupt_build_process_with_resharding_half_to_max_test
    self._do_resharding_test(str(cpu_count() / 2), str(cpu_count() - 1))
  File "/jenkins/workspace/scylla-master/dtest-release@2/scylla-dtest/materialized_views_test.py", line 2044, in _do_resharding_test
    wait_for_view(cluster=self.cluster, session=session, ks='ks', view="t_by_v2")
  File "/jenkins/workspace/scylla-master/dtest-release@2/scylla-dtest/scylla_tools.py", line 905, in wait_for_view
    raise Exception(error_msg)

View ks.t_by_v2 not built
```

@sarna please see the logs.  It looks like node3 did not finish building ks.t_by_v2 after resuming.

[node1.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/artifact/logs-release.2/1554080036164_materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test/node1.log):
```
INFO  2019-04-01 00:43:45,450 [shard 0] rpc - client 127.0.79.3:7000: fail to connect: Connection refused
INFO  2019-04-01 00:43:45,450 [shard 0] rpc - client 127.0.79.2:7000: fail to connect: Connection refused
INFO  2019-04-01 00:43:45,460 [shard 0] compaction - Resharding [/jenkins/workspace/scylla-master/dtest-release@2/scylla/.dtest/dtest-cH03XJ/test/node1/data/ks/t-a0f671b0541611e98330000000000009/mc-31-big-Data.db:level=0, ]
...
ERROR 2019-04-01 00:44:35,116 [shard 21] view - Error applying view update to 127.0.79.3: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2019-04-01 00:44:35,116 [shard 21] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
INFO  2019-04-01 00:44:35,769 [shard 0] rpc - client 127.0.79.3:7000: fail to connect: Connection refused
INFO  2019-04-01 00:44:37,780 [shard 0] rpc - client 127.0.79.3:7000: fail to connect: Connection refused
INFO  2019-04-01 00:44:38,786 [shard 0] rpc - client 127.0.79.3:7000: fail to connect: Connection refused
INFO  2019-04-01 00:44:39,792 [shard 0] rpc - client 127.0.79.3:7000: fail to connect: Connection refused
INFO  2019-04-01 00:44:40,797 [shard 0] rpc - client 127.0.79.3:7000: fail to connect: Connection refused
INFO  2019-04-01 00:44:42,807 [shard 0] rpc - client 127.0.79.3:7000: fail to connect: Connection refused
INFO  2019-04-01 00:44:43,813 [shard 0] rpc - client 127.0.79.3:7000: fail to connect: Connection refused
INFO  2019-04-01 00:44:46,828 [shard 0] rpc - client 127.0.79.3:7000: fail to connect: Connection refused
INFO  2019-04-01 00:44:48,844 [shard 0] gossip - InetAddress 127.0.79.3 is now UP, status = 
INFO  2019-04-01 00:44:52,259 [shard 0] view - Finished building view ks.t_by_v2
INFO  2019-04-01 00:45:00,856 [shard 0] storage_service - Node 127.0.79.3 state jump to normal
```

So it took up to 67 seconds for node1 to get to `Finished building view ks.t_by_v2`, right?

[node2.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/artifact/logs-release.2/1554080036164_materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test/node2.log):
```
INFO  2019-04-01 00:44:42,713 [shard 0] init - Scylla version 666.development-0.20190331.77a0d5c5d initialization completed.
INFO  2019-04-01 00:44:42,742 [shard 0] view - Building view ks.t_by_v2, starting at token minimum token
ERROR 2019-04-01 00:44:42,746 [shard 1] view - Error applying view update to 127.0.79.3: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
...
ERROR 2019-04-01 00:44:49,769 [shard 9] view - Error applying view update to 127.0.79.3: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2019-04-01 00:44:49,769 [shard 9] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
INFO  2019-04-01 00:44:49,809 [shard 0] gossip - InetAddress 127.0.79.3 is now UP, status = 
INFO  2019-04-01 00:44:58,843 [shard 0] view - Finished building view ks.t_by_v2
INFO  2019-04-01 00:45:00,605 [shard 0] storage_service - Node 127.0.79.3 state jump to normal
```
[node3.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/75/artifact/logs-release.2/1554080036164_materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test/node3.log):
```
INFO  2019-04-01 00:43:34,547 [shard 0] view - Building view ks.t_by_v2, starting at token minimum token
...
ERROR 2019-04-01 00:43:34,761 [shard 14] view - Error applying view update to 127.0.79.1: exceptions::mutation_write_timeout_exception (Operation timed out for ks.t_by_v2 - received only 0 responses from 1 CL=ONE.)
INFO  2019-04-01 00:43:37,653 [shard 0] compaction_manager - Asked to stop
...
INFO  2019-04-01 00:44:46,670 [shard 0] init - Scylla version 666.development-0.20190331.77a0d5c5d starting.
...
INFO  2019-04-01 00:45:12,614 [shard 0] init - Scylla version 666.development-0.20190331.77a0d5c5d initialization completed.
INFO  2019-04-01 00:45:12,644 [shard 0] view - Resuming to build view ks.t_by_v2 at minimum token
```

**Comment by sarna** [comment]
@bhalevy I think you meant to ping @psarna :)

**Comment by bhalevy** [comment]
> @bhalevy I think you meant to ping @psarna :)

@sarna You're absolutely right. Sorry for noise (I guess it's not the first time... :-))

**Comment by psarna** [comment]
@bhalevy About node3 logs:
`error applying view update` errors that happen before node3 shutdown are induced - since view building is persistent, we just time out existing requests from the view building queue in order to shut down faster (this change was introduced a while ago).

Then, I see that node3 does start view building as it should, it just happens late enough that the 2 minutes checking period is exceeded... I wonder if this could be helped significantly by making the "gossip wait times" more robust with a patch, as in the mailing list discussion.

For now, it looks like it's yet again the issue of increasing a timeout, this time in wait_for_view()... but the fact that this single case needs more than 2 minutes and there are 5 or more subcases means that the real solution would be to make the nodes boot much quicker on startup - at least for testing purposes.

**Comment by bhalevy** [comment]
@psarna I'd like to have the dtest more robust regardless of improving gossip wait times
Care to open a github issue for scylla-dtest and fix that?
We may consider to readjust the timeouts once node start up time is reduced.

**Comment by psarna** [comment]
I think for now it's sufficient and correct to just raise the timeout in wait_for_view, because the fact is that in our test cases we do not wait enough time for views to finish building. Then, after speeding up gossip wait times, the test cases will just remain correct and no action will be necessary.

**Comment by bhalevy** [comment]
> I think for now it's sufficient and correct to just raise the timeout in wait_for_view, because the fact is that in our test cases we do not wait enough time for views to finish building. Then, after speeding up gossip wait times, the test cases will just remain correct and no action will be necessary.

Agreed. Sounds good.

**Comment by slivne** [comment]
closing

**Comment by bhalevy** [comment]
Reopening as this was hit again in [dtest-release/116/testReport/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_half_to_max_test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/116/testReport/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_half_to_max_test/).  It is unclear to me why the 5 minutes wait didn't help.  Maybe there's something else that needs fixing besides it.

[node1.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/116/artifact/logs-release.2/1557172275397_materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test/node1.log):
```
INFO  2019-05-06 19:41:31,022 [shard 0] view - Resuming to build view ks.t_by_v at 9143775578573763947
INFO  2019-05-06 19:41:31,023 [shard 0] view - Building view ks.t_by_v2, starting at token 9143775578573763947
ERROR 2019-05-06 19:41:31,028 [shard 4] view - Error applying view update to 127.0.51.3: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
...
INFO  2019-05-06 19:41:58,730 [shard 0] gossip - InetAddress 127.0.51.3 is now UP, status = 
INFO  2019-05-06 19:42:02,070 [shard 0] view - Finished building view ks.t_by_v
INFO  2019-05-06 19:42:11,639 [shard 0] storage_service - Node 127.0.51.3 state jump to normal
```

[node2.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/116/artifact/logs-release.2/1557172275397_materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test/node2.log):
```
INFO  2019-05-06 19:41:53,165 [shard 0] view - Resuming to build view ks.t_by_v at 7926484272140320917
INFO  2019-05-06 19:41:53,165 [shard 0] view - Building view ks.t_by_v2, starting at token 7926484272140320917
ERROR 2019-05-06 19:41:53,169 [shard 30] view - Error applying view update to 127.0.51.3: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
...
INFO  2019-05-06 19:41:59,166 [shard 0] gossip - InetAddress 127.0.51.3 is now UP, status = 
INFO  2019-05-06 19:42:00,314 [shard 0] view - Finished building view ks.t_by_v
INFO  2019-05-06 19:42:01,398 [shard 0] view - Finished building view ks.t_by_v2
INFO  2019-05-06 19:42:11,220 [shard 0] storage_service - Node 127.0.51.3 state jump to normal
```

[node3.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/116/artifact/logs-release.2/1557172275397_materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_half_to_max_test/node3.log):
```
INFO  2019-05-06 19:42:22,707 [shard 0] storage_service - Starting listening for CQL clients on 127.0.51.3:9042 (unencrypted)
INFO  2019-05-06 19:42:22,719 [shard 0] storage_service - Thrift server listening on 127.0.51.3:9160 ...
INFO  2019-05-06 19:42:22,724 [shard 0] init - Scylla version 666.development-0.20190506.47d04e49e initialization completed.
INFO  2019-05-06 19:42:22,728 [shard 0] view - Building view ks.t_by_v2, starting at token minimum token
INFO  2019-05-06 19:42:24,001 [shard 0] view - Finished building view ks.t_by_v2
```

**Comment by psarna** [comment]
It looks like logs look perfectly fine, so it might just as well be that 5 minutes is slightly not enough... hard to say and the issue doesn't really reproduce locally.

One thing we could try is like in https://github.com/scylladb/scylla-dtest/commit/71e97d7df305e6c31f1d83a84ad692134a0b0b4d , we cut the length short in some tests, which makes the test run faster while still checking what it needs to check.

This particular test still has `rows = 200000` workload, which is rather large. I have no idea if resharding tests depend on a large value, or maybe it's fine to reduce it tenfold?

**Comment by bhalevy** [comment]
I'm not sure if we need so many rows to be inserted.
The test stops the cluster right after the call to `_wait_for_view_build_start` and that seem to take fractions of a second.
Are the 5 minutes tied to the time it takes to actually complete building the view after restart and all nodes stabilizing or the the overall time including the fuzzy period where we see lots of `Cannot achieve consistency level for cl ONE. Requires 1, alive 0` errors?

After these errors stop, view building seem to take only 1-2 seconds. Does that make sense?

**Comment by psarna** [comment]
The 5 minutes counter starts when `wait_for_view()` is called, so it definitely includes the fuzzy period. I don't know how to access debug logs for dtests, but the code has debug information:
~~~
debug("Wait and ensure the MV build resumed.")
wait_for_view(cluster=self.cluster, session=session, ks='ks', view="t_by_v")
wait_for_view(cluster=self.cluster, session=session, ks='ks', view="t_by_v2")
~~~,
so if we could track when this debug message was printed, it will help give us more context.

Anyway, even if this issue remains open, decreasing `rows = 200000` to something like `rows = 10000` would speed up dtest execution time, which is always a win. The only question is whether it doesn't hurt the resharding scenario.

**Comment by psarna** [comment]
Locally the test passes fine, I tried several times.

**Comment by bhalevy** [comment]
Still hitting this quite regularly. For example, [dtest-release/160/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_restart_test](http://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/160/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_restart_test/):
```
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 618, in mv_populating_from_existing_data_during_node_restart_test
    self._mv_populating_from_existing_data_during_changes_test('restart node', nodes=4, rf=3, mvs=10, prefill=40000, fail=False)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/materialized_views_test.py", line 676, in _mv_populating_from_existing_data_during_changes_test
    wait_for_view(cluster=self.cluster, session=session, ks=tm.keyspace, view=mv_name)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/scylla_tools.py", line 907, in wait_for_view
    raise Exception(error_msg)
Exception: View ks.tm_table_mv_2 not built
```

Node logs [here](http://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/160/artifact/logs-release.2/1561622709829_materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_node_restart_test/)
```
node1:
WARN  2019-06-27 07:57:57,477 [shard 1] view - Error executing build step for base ks.tm_table: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID 45e723c0-98b1-11e9-b310-000000000000): std::out_of_range (_Map_base::at)

node2:
INFO  2019-06-27 07:58:25,681 [shard 0] init - Scylla version 666.development-0.20190627.2d3e3640df initialization completed.
INFO  2019-06-27 07:58:25,687 [shard 0] view - Resuming to build view ks.tm_table_mv_1 at -6749793566962050514
INFO  2019-06-27 07:58:25,687 [shard 0] view - Resuming to build view ks.tm_table_mv_2 at -6749793566962050514
INFO  2019-06-27 07:58:25,687 [shard 0] view - Resuming to build view ks.tm_table_mv_3 at -6749793566962050514
INFO  2019-06-27 07:58:25,687 [shard 0] view - Building view ks.tm_table_mv_9, starting at token -6749793566962050514
INFO  2019-06-27 07:58:25,688 [shard 0] view - Building view ks.tm_table_mv_8, starting at token -6749793566962050514
INFO  2019-06-27 07:58:25,688 [shard 0] view - Building view ks.tm_table_mv_5, starting at token -6749793566962050514
INFO  2019-06-27 07:58:25,688 [shard 0] view - Building view ks.tm_table_mv_6, starting at token -6749793566962050514
INFO  2019-06-27 07:58:25,688 [shard 0] view - Building view ks.tm_table_mv_4, starting at token -6749793566962050514
INFO  2019-06-27 07:58:25,688 [shard 0] view - Building view ks.tm_table_mv_7, starting at token -6749793566962050514
INFO  2019-06-27 07:58:26,240 [shard 0] view - Finished building view ks.tm_table_mv_1
INFO  2019-06-27 07:58:26,764 [shard 0] view - Finished building view ks.tm_table_mv_2
INFO  2019-06-27 07:58:27,267 [shard 0] view - Finished building view ks.tm_table_mv_3
INFO  2019-06-27 07:58:27,481 [shard 0] view - Finished building view ks.tm_table_mv_7
INFO  2019-06-27 07:58:27,481 [shard 0] view - Finished building view ks.tm_table_mv_4
INFO  2019-06-27 07:58:27,481 [shard 0] view - Finished building view ks.tm_table_mv_6
INFO  2019-06-27 07:58:27,481 [shard 0] view - Finished building view ks.tm_table_mv_5
INFO  2019-06-27 07:58:27,481 [shard 0] view - Finished building view ks.tm_table_mv_8
INFO  2019-06-27 07:58:27,481 [shard 0] view - Finished building view ks.tm_table_mv_9

node3:
WARN  2019-06-27 07:57:59,493 [shard 1] view - Error executing build step for base ks.tm_table: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID 45e723c0-98b1-11e9-b310-000000000000): std::out_of_range (_Map_base::at)

node4:
WARN  2019-06-27 07:57:59,500 [shard 0] view - Error executing build step for base ks.tm_table: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID 45e723c0-98b1-11e9-b310-000000000000): std::out_of_range (_Map_base::at)
```

**Comment by bhalevy** [comment]
Ref scylladb/scylla-dtest#895

**Comment by bhalevy** [comment]
Moving @nyh's [comment](https://github.com/scylladb/scylla/issues/4730#issuecomment-512227845) from the dup issue #4730, so we can continue the discussion here:

... looked at the new logs:

In https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/lastFailedBuild/artifact/logs-release.2/1563273063601_materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_node_stop_test/ it seems that log2 - with address**127.0.55.2** - is the one with the node that got stopped and then started, because it has two Scylla boots. According to this log, the time this node was down was just 1.2 seconds, but according to log1, this was enough for the other nodes to notice. So it's not a "5 minute hang during build" issue. It's something else.

Anyway, looking at log1, you can see that starting at 10:23:51,836,  we start seeing
```
ERROR 2019-07-16 10:23:51,836 [shard 0] view - Error applying view update to 127.0.55.1: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID ce56a440-a7b3-11e9-b00c-000000000000): std::out_of_range (_Map_base::at)
WARN  2019-07-16 10:23:51,836 [shard 0] view - Error executing build step for base ks.tm_table: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID ce56a440-a7b3-11e9-b00c-000000000000): std::out_of_range (_Map_base::at)
```

and this problem doesn't end until 5 minutes later, when the test times out. So this is why the build cannot complete.

But why can't 127.0.55.1, when it tells *itself* to build a table with this cf id, find it?
I think the answer is related to two lines just above in log1:
```
INFO  2019-07-16 10:23:51,835 [shard 0] schema_tables - Dropping ks.tm_table_mv_4 id=ce56a440-a7b3-11e9-b00c-000000000000 version=3fd46945-2492-3a67-890c-6d2afe0ea96c
INFO  2019-07-16 10:23:51,835 [shard 0] schema_tables - Creating ks.tm_table_mv_4 id=ce58ee30-a7b3-11e9-99fa-000000000000 version=3ee12eb9-32a2-34bd-9390-f5b1e4cc445a
```

Note how the view with id ce56a440-a7b3-11e9-b00c-000000000000 - the one the build is trying to build - gets dropped, and instead one with a different id is being created!

I have no idea why this happens (it it related to the other node going down around the same time?). But if it really should happen (?), the view build should probably adapt to this change - it should recalculate the schema id on every build step instead of trying and retrying with the now dead id...

**Comment by bhalevy** [comment]
Cc @nyh @eliransin

**Comment by eliransin** [comment]
Same test as #4270

**Comment by psarna** [comment]
Seeing entries like:
```
INFO  2019-07-16 10:23:51,835 [shard 0] schema_tables - Dropping ks.tm_table_mv_4 id=ce56a440-a7b3-11e9-b00c-000000000000 version=3fd46945-2492-3a67-890c-6d2afe0ea96c
INFO  2019-07-16 10:23:51,835 [shard 0] schema_tables - Creating ks.tm_table_mv_4 id=ce58ee30-a7b3-11e9-99fa-000000000000 version=3ee12eb9-32a2-34bd-9390-f5b1e4cc445a
```
in the logs **should** result in the view builder first stopping the building (after the view was dropped), and then restarting the building (after the view was created). It's weird that it does not happen. What makes this issue hard to debug is that it simply does not reproduce locally... I have an ongoing loop that stops once this test fails and it runs flawlessly for its second hour now.

What I don't understand is how dropping+recreating a view does not result in stopping and starting the building process. The code which logs `Dropping (...)` is immediately followed by continuations which abort view building for such views, and all bookkeeping operations are serialized with a semaphore, so no races there.

This scenario would happen if our log entries actually inform that a **table**, not a view, with this name, is recreated (the code is shared for tables and views). I have no clue how it could happen, but if it would, then that's what the symptoms would be - if  a table which is not a view is dropped, no view building needs to be stopped.

I have additional debug prints in my code - if I'm lucky enough for this issue to reproduce even once, I should be able to confirm/reject my guesses.

**Comment by psarna** [comment]
Found it... I added tons of debug printing, and found this gem:
```
INFO  2019-12-03 12:24:59,827 [shard 0] view - Starting to build view ks.tm_table_mv_5
INFO  2019-12-03 12:24:59,827 [shard 0] view - Stopping to build view ks.tm_table_mv_5
```
It's a result of mutating a schema - in the mutations, there exists both a mutation which creates a view, and a one that deletes an old version of it (uuids changed, happens).

However, view builder does not operate on `uuid`s directly when it accepts a `on_view_drop` event - it operates on names. Now, notifications are sent in this order:
```cpp
notify(tables_diff.created, [&] (auto&& gs) { return mm.notify_create_column_family(gs); });
notify(tables_diff.altered, [&] (auto&& gs) { return mm.notify_update_column_family(gs, *it++); });
notify(tables_diff.dropped, [&] (auto&& dt) { return mm.notify_drop_column_family(dt.schema); });
notify(views_diff.created, [&] (auto&& gs) { return mm.notify_create_view(view_ptr(gs)); });
notify(views_diff.altered, [&] (auto&& gs) { return mm.notify_update_view(view_ptr(gs), *it++); });
notify(views_diff.dropped, [&] (auto&& dt) { return mm.notify_drop_view(view_ptr(dt.schema)); });
```
... which indicates that creation events get notified first. That's why we see `INFO  2019-12-03 12:24:59,827 [shard 0] view - Starting to build view ks.tm_table_mv_5` in logs, all good.
Then, comes the deletion, and with it: `INFO  2019-12-03 12:24:59,827 [shard 0] view - Stopping to build view ks.tm_table_mv_5`. View building operation queueing is serialized, so they come in this exact order.

Now here comes the problem - on view creation, view builder allocates build steps and other structures for this view. On view deletion, it goes over all steps and structures, and once it finds entries that correspond to the deleted view, it dequeues the steps, **assuming there's only one queued view with given name**. This is not correct in our current state, since for a while there will be two of them - because creation got notified before deletion. Then, deletion will remove the view from building, but it just so happens that it removes entries we just inserted (with updated uuids), and the old, deprecated entry is left intact.

The solution is dead simple - notify deletions first. That's under the assumption that if 2 mutations come at the same time, and one creates a table and the other one removes it, it's more likely that the user intended a replacement of this table (delete old + create new), rather than an atomic creation+removal of a new table, which is pretty much a no-op.

I'll push a patch in a moment.

**Comment by psarna** [comment]
By the way - *some* errors like `std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID ce56a440-a7b3-11e9-b00c-000000000000): std::out_of_range (_Map_base::at)` can still occur in the logs when somebody replaces an old view definition with a new one, because there's a preemption point between removing the view from the database and stopping its view building. View builder is ready for that and these errors are totally benign - they're just last cries of stale build steps before the whole building process is aborted, but nonetheless they may appear.

Fortunately, these errors are already ignored, because they'll all start with `Error applying view update (...)`, which is on the ignore list. I'm just writing it here so people know what might be the source of these benign errors.

**Comment by bhalevy** [comment]
> By the way - _some_ errors like `std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID ce56a440-a7b3-11e9-b00c-000000000000): std::out_of_range (_Map_base::at)` can still occur in the logs when somebody replaces an old view definition with a new one, because there's a preemption point between removing the view from the database and stopping its view building. View builder is ready for that and these errors are totally benign - they're just last cries of stale build steps before the whole building process is aborted, but nonetheless they may appear.
> 
> Fortunately, these errors are already ignored, because they'll all start with `Error applying view update (...)`, which is on the ignore list. I'm just writing it here so people know what might be the source of these benign errors.

That's true.  Another note for future readers of this issue is that they are ignored only if the test gets to `check_errors`.  unlike cases that call `_mv_populating_from_existing_data` that sets:
https://github.com/scylladb/scylla-dtest/blob/5936f11fb1e3668e836a769306991563d1f1fe29/materialized_views_test.py#L563
`_mv_populating_from_existing_data_during_changes_test` doesn't set this (or other errors) in `self.ignore_log_patterns`.  Ignoring happens as a side effect of calling check_errors in:
https://github.com/scylladb/scylla-dtest/blob/5936f11fb1e3668e836a769306991563d1f1fe29/materialized_views_test.py#L696-L699

For example, see https://jenkins.scylladb.com/view/scylla-3.2/job/scylla-3.2/job/dtest-release/20/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_restart_test_2/
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 396, in run
    self.tearDown()
  File "/jenkins/workspace/scylla-3.2/dtest-release/scylla-dtest/dtest.py", line 907, in tearDown
    self.cleanUpCluster()
  File "/jenkins/workspace/scylla-3.2/dtest-release/scylla-dtest/dtest.py", line 923, in cleanUpCluster
    raise AssertionError('Unexpected error in %s node log: %s' % (node.name, errors))
AssertionError: Unexpected error in node1 node log: ["ERROR 2019-12-09 09:20:48,293 [shard 0] view - Error applying view update to 127.0.82.1: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID 2f781780-1a65-11ea-aa12-000000000000): std::out_of_range (_Map_base::at)\nWARN  2019-12-09 09:20:48,293 [shard 0] view - Error executing build step for base ks.tm_table: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID 2f781780-1a65-11ea-aa12-000000000000): std::out_of_range (_Map_base::at)\nERROR 2019-12-09 09:20:48,294 [shard 1] view - Error applying view update to 127.0.82.1: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID 2f781780-1a65-11ea-aa12-000000000000): std::out_of_range (_Map_base::at)\nWARN  2019-12-09 09:20:48,294 [shard 1] view - Error executing build step for base ks.tm_table: std::_Nested_exception<no_such_column_family> (Can't find a column family with UUID 2f781780-1a65-11ea-aa12-000000000000): std::out_of_range (_Map_base::at)"]
```

This happened after it failed [here](https://jenkins.scylladb.com/view/scylla-3.2/job/scylla-3.2/job/dtest-release/20/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_restart_test/):
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-3.2/dtest-release/scylla-dtest/materialized_views_test.py", line 626, in mv_populating_from_existing_data_during_node_restart_test
    self._mv_populating_from_existing_data_during_changes_test('restart node', nodes=4, rf=3, mvs=10, prefill=40000, fail=False)
  File "/jenkins/workspace/scylla-3.2/dtest-release/scylla-dtest/materialized_views_test.py", line 684, in _mv_populating_from_existing_data_during_changes_test
    wait_for_view(cluster=self.cluster, session=session, ks=tm.keyspace, view=mv_name)
  File "/jenkins/workspace/scylla-3.2/dtest-release/scylla-dtest/scylla_tools.py", line 916, in wait_for_view
    raise Exception(error_msg)
Exception: View ks.tm_table_mv_2 not built
```

**Comment by avikivity** [comment]
Already in 3.3, 4.0.
