### ISSUE TITLE
Reactor stall on all shards + backtrace

### ISSUE THREAD

**Issue by Kvikal** [scylladb/scylla#4387]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.2-0.20190131.5174b1cd1
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04

One of the nodes experienced timeouts and erratic CPU load. Logs are filled with following backtrace. Stalls are occuring on all shards.

Nodetool on node does not respond. API server does work when querying version.
Restarting service via systemctl hangs forever. 

After cancelling the command to stop scylla, the scylla process eventually exits.

<del> Starting scylla after via systemctl again hangs forever, but scylla process does start and seems to function properly without any errors in logs. <del>

Edit: After several minutes, reactors are stalling again and same backtrace is being logged.

Backtrace

```
Apr 02 12:59:41 node-name scylla[2741111]: Reactor stalled for 2368 ms on shard 1.
Apr 02 12:59:41 node-name scylla[2741111]: Backtrace:
Apr 02 12:59:41 node-name scylla[2741111]:   0x00000000006a7b12
Apr 02 12:59:41 node-name scylla[2741111]:   0x00000000005c4c2c
Apr 02 12:59:41 node-name scylla[2741111]:   0x00000000005c50e6
Apr 02 12:59:41 node-name scylla[2741111]:   /lib/x86_64-linux-gnu/libpthread.so.0+0x000000000001138f
Apr 02 12:59:41 node-name scylla[2741111]:   0x00000000005a2bef
Apr 02 12:59:41 node-name scylla[2741111]:   /lib/x86_64-linux-gnu/libpthread.so.0+0x000000000001138f
Apr 02 12:59:41 node-name scylla[2741111]:   /lib/x86_64-linux-gnu/libc.so.6+0x00000000001014d8
Apr 02 12:59:41 node-name scylla[2741111]:   0x00000000007ad298
Apr 02 12:59:41 node-name scylla[2741111]:   0x0000000000643f4b
Apr 02 12:59:41 node-name scylla[2741111]:   0x00000000005a1be4
Apr 02 12:59:41 node-name scylla[2741111]:   0x0000000000673226
Apr 02 12:59:41 node-name scylla[2741111]:   0x00000000006962fa
Apr 02 12:59:41 node-name scylla[2741111]:   0x000000000074b97d
Apr 02 12:59:41 node-name scylla[2741111]:   /lib/x86_64-linux-gnu/libpthread.so.0+0x00000000000076b9
Apr 02 12:59:41 node-name scylla[2741111]:   /lib/x86_64-linux-gnu/libc.so.6+0x000000000010741c
```

**Comment by Kvikal** [comment]
Apparently one of our system drives was causing extremely high IO latency. Removing this drive from RAID1 seems to have solved the issue. Note that data is stored on different drives. I will keep monitoring and post here, if the issue reappears.

**Comment by tzach** [comment]
Thanks for the update @Kvikal if this problem return, it will be useful to see metrics from the Monitoring system.
