### ISSUE TITLE
storage_proxy - exception during mutation write to 127.0.93.2: seastar::broken_promise (broken promise) during shutdown

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4394]
scylla version a66a5d423abd0fc3687fefc4a069c2f0827fcf1a

This seems like a generic issue with updating large data tables on shutdown and not specific to the particular dtest it was hit with below (repair_during_update_test).

Ref #4384
And probably a reincarnation of #4291

Seen in [next/675/artifact/logs-release.2/1554246996225_repair_additional_test.RepairAdditionalTest.repair_during_update_test/node2.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/next/675/artifact/logs-release.2/1554246996225_repair_additional_test.RepairAdditionalTest.repair_during_update_test/node2.log):
```
INFO  2019-04-02 23:10:15,127 [shard 0] storage_service - Drain on shutdown: tracing is stopped
INFO  2019-04-02 23:10:15,127 [shard 0] storage_service - Drain on shutdown: system distributed keyspace stopped
INFO  2019-04-02 23:10:15,127 [shard 0] hints_manager - Asked to stop
INFO  2019-04-02 23:10:15,127 [shard 0] hints_manager - Stopped
INFO  2019-04-02 23:10:15,127 [shard 1] hints_manager - Asked to stop
INFO  2019-04-02 23:10:15,127 [shard 1] hints_manager - Stopped
INFO  2019-04-02 23:10:15,127 [shard 0] storage_service - Drain on shutdown: hints manager is stopped
INFO  2019-04-02 23:10:15,783 [shard 0] storage_service - Drain on shutdown: flush column_families done
INFO  2019-04-02 23:10:15,784 [shard 0] storage_service - Drain on shutdown: shutdown commitlog done
INFO  2019-04-02 23:10:15,784 [shard 0] storage_service - Drain on shutdown: done
INFO  2019-04-02 23:10:15,784 [shard 0] repair - Starting shutdown of repair
INFO  2019-04-02 23:10:15,784 [shard 0] repair - Completed shutdown of repair
INFO  2019-04-02 23:10:15,785 [shard 0] init - Shutdown database started
WARN  2019-04-02 23:10:15,923 [shard 0] seastar - Exceptional future ignored: seastar::broken_promise (broken promise), backtrace:   0x449cc8b
  0x402fb84
  0xa1b0e6
  0x23f01c9
  0x402e6f1
  0x402e8ee
  0x4103525
  0x3f9ca34
  0x92c614
  /jenkins/slave/workspace/scylla-master/next/scylla-dtest/../scylla/dynamic_libs/libc.so.6+0x24412
  0x98c57d

WARN  2019-04-02 23:10:15,924 [shard 0] large_data - Failed to drop entries from large_cells: ks = ks, table = cf, sst = /jenkins/slave/workspace/scylla-master/next/scylla/.dtest/dtest-uMFzkj/test/node2/data/ks/cf-19398220559811e9affc000000000001/mc-1060-big-Data.db exception = exceptions::mutation_write_failure_exception (Operation failed for system.large_cells - received 0 responses and 1 failures from 1 CL=ONE.)
ERROR 2019-04-02 23:10:16,118 [shard 0] storage_proxy - exception during mutation write to 127.0.93.2: seastar::broken_promise (broken promise)
[and many more of the above 2 messages...]
```

**Comment by fgelcer** [comment]
I have seen such message on SCT longevity (1TB) for 3.1, and it still not clear if it crashes nodes, but i'm investigating.
if more data is needed, it will be provided on demand.

**Comment by fgelcer** [comment]
it happens during decommission nemesis, apparently for MV

**Comment by espindola** [comment]
I tried to reproduce this by just creating a large entry, deleting it and quickly shutting down the database, but couldn't.

I will try running dtest, but for now I am just reading the code at revision a66a5d4. From the log it seems that the "DELETE FROM system.{}" fails and some inner future is ignored. Since the final future from execute_cql is passed to a handle_exception, it cannot be the one that causes the backtrace.

One potential problem that shows right away is that we can delete sstable files from the sstable destructor and there we cannot wait for the future. As far as I know we can also destroy those objects fairly late.

One other issue: when are schema objects destroyed? The future returned by maybe_delete_large_data_entries can hold a reference to one and we don't wait for it until await_background_jobs_on_all_shards or _sstable_deletion_gate.close() (depending on where it is called from).

Also, on this revision we don't wait for deletions until the very end, where we wait for _sstable_deletion_gate.close().

So it is not too unexpected that the execute_cql can fail, but I still don't know which future is being ignored.

trying dtest.

**Comment by espindola** [comment]
I can reproduce this with dtest. The backtrace is

seastar::current_backtrace() at /home/espindola/scylla/scylla/seastar/build/release/../../include/seastar/util/backtrace.hh:55
 (inlined by) seastar::current_backtrace() at /home/espindola/scylla/scylla/seastar/build/release/../../src/util/backtrace.cc:84
seastar::report_failed_future(std::__exception_ptr::exception_ptr) at /home/espindola/scylla/scylla/seastar/build/release/../../src/core/reactor.cc:5506
std::_Optional_payload<seastar::promise<>, false, false, false>::~_Optional_payload() at /home/espindola/scylla/scylla/seastar/include/seastar/core/future.hh:1345
 (inlined by) ?? at /home/espindola/scylla/scylla/seastar/include/seastar/core/future.hh:1338
 (inlined by) ?? at /home/espindola/scylla/scylla/seastar/include/seastar/core/future.hh:470
 (inlined by) ?? at /usr/include/c++/8/optional:200
 (inlined by) std::_Optional_payload<seastar::promise<>, false, false, false>::~_Optional_payload() at /usr/include/c++/8/optional:197
seastar::continuation<seastar::future<>::then_wrapped_impl<seastar::shared_future<seastar::with_clock<seastar::lowres_clock> >::shared_future(seastar::future<>&&)::{lambda(seastar::future<>&&)#1}, seastar::future<> >(seastar::shared_future<seastar::with_clock<seastar::lowres_clock> >::shared_future(seastar::future<>&&)::{lambda(seastar::future<>&&)#1}&&)::{lambda(auto:1)#1}>::run_and_dispose() at /usr/include/c++/8/optional:661
 (inlined by) ?? at /usr/include/c++/8/optional:943
 (inlined by) ?? at /home/espindola/scylla/scylla/seastar/include/seastar/core/expiring_fifo.hh:60
 (inlined by) ?? at /home/espindola/scylla/scylla/seastar/include/seastar/core/chunked_fifo.hh:435
 (inlined by) ?? at /home/espindola/scylla/scylla/seastar/include/seastar/core/expiring_fifo.hh:165
 (inlined by) ?? at /home/espindola/scylla/scylla/seastar/include/seastar/core/shared_future.hh:120
 (inlined by) seastar::shared_future<seastar::with_clock<seastar::lowres_clock> >::shared_future(seastar::future<>&&)::{lambda(seastar::future<>&&)#1}::operator()(seastar::future<>&&) at /home/espindola/scylla/scylla/seastar/include/seastar/core/shared_future.hh:168
 (inlined by) ?? at /home/espindola/scylla/scylla/seastar/include/seastar/core/future.hh:1420
 (inlined by) ?? at /home/espindola/scylla/scylla/seastar/include/seastar/core/future.hh:1469
 (inlined by) auto seastar::future<>::then_wrapped_impl<seastar::shared_future<seastar::with_clock<seastar::lowres_clock> >::shared_future(seastar::future<>&&)::{lambda(seastar::future<>&&)#1}, seastar::future<> >(seastar::shared_future<seastar::with_clock<seastar::lowres_clock> >::shared_future(seastar::future<>&&)::{lambda(seastar::future<>&&)#1}&&)::{lambda(auto:1)#1}::operator()<seastar::future_state<> >(seastar::future_state<>) at /home/espindola/scylla/scylla/seastar/include/seastar/core/future.hh:1069
 (inlined by) seastar::continuation<seastar::future<>::then_wrapped_impl<seastar::shared_future<seastar::with_clock<seastar::lowres_clock> >::shared_future(seastar::future<>&&)::{lambda(seastar::future<>&&)#1}, seastar::future<> >(seastar::shared_future<seastar::with_clock<seastar::lowres_clock> >::shared_future(seastar::future<>&&)::{lambda(seastar::future<>&&)#1}&&)::{lambda(auto:1)#1}>::run_and_dispose() at /home/espindola/scylla/scylla/seastar/include/seastar/core/future.hh:425
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /home/espindola/scylla/scylla/seastar/build/release/../../src/core/reactor.cc:3633
seastar::reactor::run_some_tasks() [clone .part.2867] at /home/espindola/scylla/scylla/seastar/build/release/../../src/core/reactor.cc:4058
seastar::reactor::run() at /home/espindola/scylla/scylla/seastar/build/release/../../src/core/reactor.cc:4041
 (inlined by) seastar::reactor::run() at /home/espindola/scylla/scylla/seastar/build/release/../../src/core/reactor.cc:4201
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /home/espindola/scylla/scylla/seastar/build/release/../../src/core/app-template.cc:186
main at /home/espindola/scylla/scylla/main.cc:350
__libc_start_main at ??:?
_start at ??:?

Which means the warning is from shared_future:

                while (_peers) {
                    _peers.front().set_exception(_future_state.get_exception());
                    _peers.pop_front(); // promise is destroyed and we warn
                }
Which means that someone called get_future on a shared_promise and did nothing with that future.

**Comment by espindola** [comment]
The probable backtrace for the creation of the broken promise is:

[backtrace-decoded.txt](https://github.com/scylladb/scylla/files/3622142/backtrace-decoded.txt)

**Comment by avikivity** [comment]
Already backported everywhere.
