### ISSUE TITLE
doc: documentation link doesn't exist: http://www.scylladb.com/kb/kb-fs-not-qualified-aio/

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#4398]
*Installation details*
Scylla version (or git commit hash): 666.development-0.2019040 amd64
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 16.04

On ubuntu 16.04 & 18.04, When the kernel check failed, we would see the error:
```
Please upgrade to a newer kernel version.
see http://www.scylladb.com/kb/kb-fs-not-qualified-aio/ for details
```

But `http://www.scylladb.com/kb/kb-fs-not-qualified-aio/` doesn't exist.
I might be moved to `https://docs.scylladb.com/troubleshooting/error_messages/kb_fs_not_qualified_aio/`

Hi @tzach @slivne @roydahan ,  Do we need to redirect `http://www.scylladb.com/kb/kb-fs-not-qualified-aio/` to `https://docs.scylladb.com/troubleshooting/error_messages/kb_fs_not_qualified_aio/`?

Or update the link to `https://docs.scylladb.com/troubleshooting/error_messages/kb_fs_not_qualified_aio/` in dist/common/scripts/scylla_kernel_check?

**Comment by tzach** [comment]
@amoskong please update the link in Scylla
I will check if we can redirect for older Scylla versions

**Comment by amoskong** [comment]
Posted a patch to scylladb-dev list:
- [PATCH scylla] scylla_kernel_check: update kb_fs_not_qualified_aio doc link
