### ISSUE TITLE
nodetool disableautocompaction

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#440]
Disables autocompaction for a keyspace and one or more tables.
http://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsDisableAutoCompaction.html

Can be useful when compaction take too much space
http://nieksand.tumblr.com/

**Comment by glommer** [comment]
We have no one assigned for this. I took a stab once but it was never merged. There has been already situations in the field where this would have been very helpful when handling nodes that are having issues.

Can we assign someone ?

**Comment by duarten** [comment]
Duplicates https://github.com/scylladb/scylla-tools-java/issues/41

**Comment by nyh** [comment]
Looking at the code it appears we already have a `compaction_enabled` flag for tables,  and CQL support for setting it from the "enabled" option, but the compaction manager just ignores this parameter. Also, the REST API has /column_family/autocompaction/ but it's a GET-only API (just get the value, can't change it) and its implementation is hard-coded to return TRUE in any case.

**Comment by dorlaor** [comment]
I am not sure it should be a tier-1, yes, it's a good thing but it's mostly a hack/plaster and not a solution that can hold for long. Agree it's something that can help to cure a specific live issue

**Comment by glommer** [comment]
Dor, not sure github is the best place do discuss tagging? Tzach questioned me on that and I justified saying that in situations in which we need to do this, not being able to has been, in the past, disastrous.

My perspective when tagging is not about functionality & features (I leave that to shlomi), but about safety and recoverability.

**Comment by slivne** [comment]
related to #1488

**Comment by slivne** [comment]
@bhalevy - the one that solves #1488 should also solve this
