### ISSUE TITLE
tcp dns queries can fail

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#4404]
Name resolution (e.g. for seeds) can fail if the DNS server uses TCP instead of the usual UDP.

**Comment by avikivity** [comment]
Fixed by 183c2369f36c8bf8034c24fae2869860dc531465.

**Comment by tzach** [comment]
@avikivity should we backport this?

**Comment by avikivity** [comment]
It was already backported, check the issue before assigning.
