### ISSUE TITLE
nodetool disablegossip

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#441]
Disables the gossip protocol.
http://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsDisableGossip.html

Useful too for gradual disconnecting a server from the cluster  
http://devblog.michalski.im/2012/11/25/safe-cassandra-shutdown-and-restart/

**Comment by slivne** [comment]
@amnonh can we close this

**Comment by amnonh** [comment]
can be closed
