### ISSUE TITLE
nodetool proxyhistograms fails with an error

### ISSUE THREAD

**Issue by gudladona87** [scylladb/scylla#4416]
Scylla version (or git commit hash): 3.0.4-0.20190313.5e3a52024
Cluster size: 5*i3.16XL
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

running `nodetool proxyhistograms` yields the following error. The API server is pointing to 12.0.0.1. We see the same issue even when it is pointed to node IP.

$ nodetool proxyhistograms
nodetool: Scylla API server HTTP GET to URL 'storage_proxy/metrics/cas_read/moving_average_histogram' failed: Not found
See 'nodetool help' or 'nodetool help <command>'.

**Comment by tzach** [comment]
@amnonh ?

**Comment by slivne** [comment]
@gudladona87 - the address you are using for the api server is it 12.0.0.1 or 127.0.0.1 ?

**Comment by slivne** [comment]
@gudladona87 ping - any new info - if not we will close the issue.

**Comment by slivne** [comment]
on docker 3.0.3-0.20190211.c36c58c64

```
nodetool proxyhistograms 
nodetool: Scylla API server HTTP GET to URL 'storage_proxy/metrics/cas_read/moving_average_histogram' failed: Not found
See 'nodetool help' or 'nodetool help <command>'.

```

on docker 2.3.2-0.20190117.22c891e6d

```
proxy histograms
Percentile      Read Latency     Write Latency     Range Latency
                    (micros)          (micros)          (micros)
50%                 12619.00            361.00          16242.00
75%                 18524.00           8013.00          34466.50
95%                 30418.60           9177.40          57027.75
98%                 32977.80          13596.96          63633.00
99%                 33206.64          24168.00          63633.00
Min                    52.00             57.00           1783.00
Max                 33235.00          24168.00          63633.00
```

**Comment by slivne** [comment]
Patches
```
[PATCH scylla-jmx] StorageProxy.java: Add view write metrics
[PATCH] API: storage_proxy add CAS and View endpoints
```

**Comment by slivne** [comment]
@amnonh lets add also a dtest for this to make sure it stays working

**Comment by amnonh** [comment]
There is already a test for it, maybe nodetool tests are not running?

**Comment by slivne** [comment]
@amnonh - the test is not running because of https://github.com/scylladb/scylla-dtest/blob/next/nodetool_additional_test.py#L1284 

```    @require('#2167')```

please remove it check the test passes and then submit a pr
