### ISSUE TITLE
date_type (timestamp in cql) less comparison is broken

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#4419]
Scylla version (or git commit hash): master(1f009b5e9)

`date_type_impl::less()` will always return `true` for two values that are not equal. Internally `date_type_impl::less()` compares the two (raw bytes) values via `compare_unsigned()`. The latter is a tri-compare function, but `less()` implicitly converts the returned value to `bool` causing the above mentioned effect.

**Comment by tgrabiec** [comment]
Does it mean that if `date` type was used as part of the clustering key we produced sstables with incorrect order of rows?

**Comment by denesb** [comment]
Possibly. I think in this case clustering rows would be written in append order. As a new key would compare less than all the existing keys that it is not equal to. Streaming and compaction further complicates this. In effect the rows would not be in any particular order.

**Comment by glommer** [comment]
since when is this true ?

**Comment by denesb** [comment]
According to git-blame, since ddcc750210.

**Comment by tgrabiec** [comment]
If the whole clustering key is composed of byte-order-comparable types then we don't go through `less()` for key comparison and don't hit this bug.

`compound_type::compare()` calls `compare_unsigned` directly in such case:
```
    int compare(bytes_view b1, bytes_view b2) {
        if (_byte_order_comparable) {
            if (_is_reversed) {
                return compare_unsigned(b2, b1);
            } else {
                return compare_unsigned(b1, b2);
            }
        }
        return lexicographical_tri_compare(_types.begin(), _types.end(),
            begin(b1), end(b1), begin(b2), end(b2), [] (auto&& type, auto&& v1, auto&& v2) {
                return type->compare(v1, v2);
            });
    }
```

**Comment by denesb** [comment]
It appears that `date_type` is not used at all. We currently map `timestamp` cql type to the `timestamp_type` data type. I failed to find the commit which removes the usage of `date_type` (if it was ever used at all).

**Comment by denesb** [comment]
Does anybody remembers when we stopped using it and why? And why are we still keeping the code around (if the lack of usage is not a mistake)?

**Comment by avikivity** [comment]
Here's a comment from Cassandra:

```
/**
 * This is the old version of TimestampType, but has been replaced as it wasn't comparing pre-epoch timestamps
 * correctly. This is kept for backward compatibility but shouldn't be used in new code.
 */
```

**Comment by denesb** [comment]
So I guess we keep it to be able to read sstables using this type.

**Comment by denesb** [comment]
I'll add a similar comment as the current situation is quite confusing.

**Comment by avikivity** [comment]
It's also possible for the name to be passed via the Thrift interface.
