### ISSUE TITLE
nodetool drain

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#442]
Drains the node from live traffic
http://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsNodetool_r.html

Example usage:
http://devblog.michalski.im/2012/11/25/safe-cassandra-shutdown-and-restart/
http://www.slideshare.net/nmilford/cassandra-for-sysadmins (#32)

**Comment by tzach** [comment]
@slivne drain is for GA, and not implemented yet

**Comment by penberg** [comment]
@tzach @slivne, really? I thought 39af3ec1909b89ae369ecdc5a23fe60927b7c388 added ``nodetool drain`` support?

Ping @pdziepak

**Comment by pdziepak** [comment]
It should be available at REST API level. Perhaps some glue code in scylla-jmx is missing.

**Comment by penberg** [comment]
``StorageService.drain()`` seems to have the necessary glue. @tzach, hmm?

**Comment by tzach** [comment]
I tested with 0.13.2 and its not there
```
nodetool drain
error: API call is not supported yet
```

**Comment by amnonh** [comment]
assign it to me

**Comment by penberg** [comment]
@tzach It's in master, not in 0.13.2.

**Comment by tzach** [comment]
I can't keep up with you youngsters, I only test RPMs
For 0.13.2 the HTTP is not avilable either
```
curl -X POST --header "Content-Type: application/json" --header "Accept: application/json" "http://localhost:10000/storage_service/drain"
{"message": "API call is not supported yet", "code": 500}
```

**Comment by amnonh** [comment]
I've just check it on head and it works.
So wait for the next release and try again

**Comment by slivne** [comment]
there is still a discussion between gleb and pawel (unless they sorted it
out) on impl items in drain.

**Comment by amnonh** [comment]
I'm not sure how well it works, but you don't get the experience Tzach was
getting.

Now the drain command completed without any errors.
And scylla prints to the log that it runs drain

**Comment by slivne** [comment]
@pdziepak I know we have talked about this - is there still something missing for this ?

**Comment by slivne** [comment]
@pdziepak , @gleb-cloudius  is there still an opem item here ?

**Comment by pdziepak** [comment]
On 18 February 2016 at 00:49, slivne <notifications@github.com> wrote:

> @pdziepak <https://github.com/pdziepak> , @gleb-cloudius
> <https://github.com/gleb-cloudius> is there still an opem item here ?
>

Drain is implemented and working correctly. There is a regression that
causes segmentation fault when shutting down drained node, but I've just
sent a patch to fix it.
