### ISSUE TITLE
resharding_by_murmur3_increase_test: seastar::semaphore_timed_out

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4424]
scylla version e3a5ac29454e09bd8f2d91ce630049e697f72ea9

Seen in [dtest-release/88/artifact/logs-release.2/1554952002046_resharding_test.ReshardingTest_nodes4_with_LeveledCompactionStrategy.resharding_by_murmur3_increase_test/node1.log](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/dtest-release/88/artifact/logs-release.2/1554952002046_resharding_test.ReshardingTest_nodes4_with_LeveledCompactionStrategy.resharding_by_murmur3_increase_test/node1.log):
```
INFO  2019-04-11 03:06:25,387 [shard 0] init - Scylla version 666.development-0.20190411.e3a5ac294 initialization completed.
ERROR 2019-04-11 03:06:39,483 [shard 0] storage_proxy - Exception when communicating with 127.0.15.1: seastar::semaphore_timed_out (Semaphore timedout)
...
and so on...
```

**Comment by bhalevy** [comment]
@raphaelsc please look into this

**Comment by raphaelsc** [comment]
On Thu, Apr 11, 2019 at 12:25 PM Benny Halevy <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> please look into this
>

looking

**Comment by slivne** [comment]
@bhalevy is this still happening ?

**Comment by bhalevy** [comment]
> @bhalevy is this still happening ?

No.  I checked the test history on Jenkins and all failures in the last couple of months were related to the infamous error storms, not to the semaphore time out, so we can close this issue IMO.
