### ISSUE TITLE
Materialized view: TTL was set and removed after by updating of non-view column, so it should be removed from MV as well

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#4426]
I re-run the test after the issue #3140 fixing. But the test failed again

**Comment by nyh** [comment]
I'm sorry, I don't understand what this issue is about. Which test is "the test" that is failing? Is it some unit test or test? Is it failing on master or one of the branches?

**Comment by nyh** [comment]
If I understand correctly https://github.com/scylladb/scylla-dtest/commit/296737f6ab21e3c759c7cfc87af47f4209ad9b42 the failing test was the dtest decommission_node_during_mv_insert_4_nodes_test - is this correct?
This test had `@require('#3382')` before you removed it...  So how is it related to issue 3140 which you mentioned above?
How does the test fail?

**Comment by juliayakovlev** [comment]
> If I understand correctly [scylladb/scylla-dtest@296737f](https://github.com/scylladb/scylla-dtest/commit/296737f6ab21e3c759c7cfc87af47f4209ad9b42) the failing test was the dtest decommission_node_during_mv_insert_4_nodes_test - is this correct?

It's TTL test, not decommission: ttl_remove_with_non_mv_column_test

> This test had `@require('#3382')` before you removed it... So how is it related to issue 3140 which you mentioned above?

TTL test is requier with #3140

> How does the test fail?

**Comment by nyh** [comment]
Ok, I can confirm that dtest `materialized_views_test.py:TestMaterializedViews.ttl_remove_with_non_mv_column_test` fails on current master.
The error message:
```
dtest: DEBUG: materialized_views_test.TestMaterializedViews.ttl_remove_with_non_mv_column_testttl_remove_with_non_mv_column_test - retrying: AssertionError("Expected a row count of 1 in table 'tm_table_mv_0', but got 0",)
dtest: DEBUG: materialized_views_test.TestMaterializedViews.ttl_remove_with_non_mv_column_testttl_remove_with_non_mv_column_test - Number of retries exceeded!
```
I'll look into it.

**Comment by nyh** [comment]
@juliayakovlev I think this is a test bug, not a Scylla error, but I need to your help to understand what this test was supposed to be doing, and if I'm right that the test is buggy:

I added some printouts, and this is what we have before sleeping 60 seconds:
```
2019-04-15 13:40:32.194153 before in base table:
2019-04-15 13:40:32.222356 [Row(id=0, clmn_int0=590, clmn_int1=0), Row(id=1, clmn_int0=3467, clmn_int1=3467)]
2019-04-15 13:40:32.222422 before in view table:
2019-04-15 13:40:32.234222 [Row(id=0, clmn_int0=590), Row(id=1, clmn_int0=3467)]
```
Now, after sleeping 60 seconds, we are left with:
```
2019-04-15 13:41:17.238535 after in base table:
2019-04-15 13:41:17.274805 [Row(id=0, clmn_int0=None, clmn_int1=0)]
2019-04-15 13:41:17.274999 after in view table:
2019-04-15 13:41:17.304257 []
```
As you can see, one row is completely gone (I guess TTL'ed). The other is not gone, but its clmn_int0 was TTLed away. But isn't this is the column which was added to the view? If it was, then indeed, this row should not appear in the view (a view always has "IS NOT NULL" restriction on the key columns). If this is the case then the output - with one row in the base but zero in the view - is actually right, it's not an error.

Maybe you meant to add  clmn_int1 to the view, not clmn_int0?

**Comment by juliayakovlev** [comment]
> @juliayakovlev I think this is a test bug, not a Scylla error, but I need to your help to understand what this test was supposed to be doing, and if I'm right that the test is buggy:
> 
> I added some printouts, and this is what we have before sleeping 60 seconds:
> 
> ```
> 2019-04-15 13:40:32.194153 before in base table:
> 2019-04-15 13:40:32.222356 [Row(id=0, clmn_int0=590, clmn_int1=0), Row(id=1, clmn_int0=3467, clmn_int1=3467)]
> 2019-04-15 13:40:32.222422 before in view table:
> 2019-04-15 13:40:32.234222 [Row(id=0, clmn_int0=590), Row(id=1, clmn_int0=3467)]
> ```
> Now, after sleeping 60 seconds, we are left with:
> 
> ```
> 2019-04-15 13:41:17.238535 after in base table:
> 2019-04-15 13:41:17.274805 [Row(id=0, clmn_int0=None, clmn_int1=0)]
> 2019-04-15 13:41:17.274999 after in view table:
> 2019-04-15 13:41:17.304257 []
> ```
> As you can see, one row is completely gone (I guess TTL'ed). The other is not gone, but its clmn_int0 was TTLed away. But isn't this is the column which was added to the view? If it was, then indeed, this row should not appear in the view (a view always has "IS NOT NULL" restriction on the key columns). If this is the case then the output - with one row in the base but zero in the view - is actually right, it's not an error.
> 
> Maybe you meant to add clmn_int1 to the view, not clmn_int0?

The meaning of  this test is: if the row should be expired because of TTL, but TTL of one of the columns was removed, the row shouldn't be expired. It means that primary key stays alive. This is the reason, that the row exists in the table. So in the materialized view this row should not be deleted as well.

**Comment by nyh** [comment]
@juliayakovlev I showed you above exactly what the row looks like in the **base** table during this test - one of the rows is still alive but one of it's columns *was* expired. If this column is the key in the view table, it means that although the base row exists, the view row will **not** exist. And this is correct. So unless I'm missing something the test is looking at a correct situation and calling it correct.
So please reconsider the validity of this test, and consider whether you actually tried to do something else (maybe you didn't intend for that column to be TTLed at all - you suggested above that you tried to cancel that TTLing? Or maybe you intended the second column to be TTLed and?)

**Comment by nyh** [comment]
@juliayakovlev let me make more direct questions to demonstrate why I think the test is buggy:
As I said above, *after* the sleep, the base and view have the following data (I printed it in the test):
```
2019-04-15 13:41:17.238535 after in base table:
2019-04-15 13:41:17.274805 [Row(id=0, clmn_int0=None, clmn_int1=0)]
2019-04-15 13:41:17.274999 after in view table:
2019-04-15 13:41:17.304257 []
```
Now my questions:
1. Did you intend the **base** output to be exactly this one row (note the "None" value)? If not, it's a test bug :-)
2. Is clmn_int1 the key of the materialized view? (I'm guessing so, but it's hard to understand the code...)
3. If so, why isn't it correct that the materialized view does NOT have this row, considering materialized views are always created with "IS NOT NULL" (i.e., if a base row has a NULL value for the view key, it's not included in the view)?

**Comment by juliayakovlev** [comment]
> @juliayakovlev let me make more direct questions to demonstrate why I think the test is buggy:
> As I said above, _after_ the sleep, the base and view have the following data (I printed it in the test):
> 
> ```
> 2019-04-15 13:41:17.238535 after in base table:
> 2019-04-15 13:41:17.274805 [Row(id=0, clmn_int0=None, clmn_int1=0)]
> 2019-04-15 13:41:17.274999 after in view table:
> 2019-04-15 13:41:17.304257 []
> ```
> Now my questions:
> 
> 1. Did you intend the **base** output to be exactly this one row (note the "None" value)? If not, it's a test bug :-)
> 2. Is clmn_int1 the key of the materialized view? (I'm guessing so, but it's hard to understand the code...)
No, this column is not part of the MV
> 3. If so, why isn't it correct that the materialized view does NOT have this row, considering materialized views are always created with "IS NOT NULL" (i.e., if a base row has a NULL value for the view key, it's not included in the view)?

I understand. I re-check this test again

**Comment by nyh** [comment]
Thanks for rechecking. I had a typo in my second question - the question is of course whether clmn_int0 (not 1) which we saw is None is the view's key (which I'm guessing it is).
