### ISSUE TITLE
too much replica read.

### ISSUE THREAD

**Issue by wqwiii** [scylladb/scylla#4427]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):2.1.6
Cluster size:5
OS (RHEL/CentOS/Ubuntu/AWS AMI):centos

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets=4000 cores=16 hyperthreading= memory=64
Disks: (SSD/HDD, count)ssd
![图片](https://user-images.githubusercontent.com/5996447/56074743-1191a980-5dea-11e9-962a-d48558ee3beb.png)
why that is no more than 100 read and write,but replica read is 5k rps?

**Comment by gleb-cloudius** [comment]
Are any of those reads happen to be range scans?

**Comment by wqwiii** [comment]
> 
> 
> Are any of those reads happen to be range scans?

range scans can make so much replica read ?

**Comment by gleb-cloudius** [comment]
5 nodes means that you have 1280 vnodes (with default config). If each read scans every one of them it can be so.

**Comment by wqwiii** [comment]
> 
> 
> 5 nodes means that you have 1280 vnodes (with default config). If each read scans every one of them it can be so.

how to avoid it?

**Comment by gleb-cloudius** [comment]
Did you confirm that it happenes because of range scans? If yes then the way to avoid it is to stop doing those scans. If you need to do them then why do you try to avoid it?

**Comment by wqwiii** [comment]
> 
> 
> 5 nodes means that you have 1280 vnodes (with default config). If each read scans every one of them it can be so.

but i have set CREATE KEYSPACE click WITH replication = {'class': 'NetworkTopologyStrategy', 'DC1': '4', 'DC2': '1', 'DC3': '1'}  AND durable_writes = true; that meas each nodes have all data,does rang scan need to scan all nodes?

**Comment by denesb** [comment]
All vnodes != all nodes. `vnode` is just a contiguous token range. It is possible that all nodes have all vnodes. A range scan will still generate a lot of replica reads for a single scan. Why are you worried about these reads? Are you experiencing a negative impact on the performance of your main queries?

**Comment by gleb-cloudius** [comment]
It needs to scan all vnodes. I see that all nodes get requests, so all of then will see database accesses.
What kind of queries and in which DCs are you running and with which CL?

**Comment by wqwiii** [comment]
> 
> 
> It needs to scan all vnodes. I see that all nodes get requests, so all of then will see database accesses.
> What kind of queries and in which DCs are you running and with which CL?

cl=one

**Comment by wqwiii** [comment]
> 
> 
> It needs to scan all vnodes. I see that all nodes get requests, so all of then will see database accesses.
> What kind of queries and in which DCs are you running and with which CL?

the question is ,since i have all data in each node by set replication factor = node number,and query data by cl=one, why it will cause so much read in replica?

**Comment by denesb** [comment]
Replica read doesn't necessarily means a cross-node hop. When coordinator == replica and the read is local it will still be counted as a replica read (no @gleb-cloudius ?).

**Comment by gleb-cloudius** [comment]
Yes. 

--
			Gleb.

**Comment by slivne** [comment]
@wqwiii, are you still missing something ? if so please post and we will reopen
