### ISSUE TITLE
resharding needs to be aware of sstable runs

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#4428]
sstables generated by resharding for a given shard must share the same run identifier, or we would destroy runs which must share same run identifier for scylla to build them on boot phase.

**Comment by bhalevy** [comment]
Cc @slivne

**Comment by raphaelsc** [comment]
i am sending a patch @slivne @bhalevy

**Comment by bhalevy** [comment]
> i am sending a patch @slivne @bhalevy

Perfect, thanks!
