### ISSUE TITLE
seastar's bug?

### ISSUE THREAD

**Issue by wqwiii** [scylladb/scylla#4430]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):2.1.6
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):centos

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores=16 hyperthreading= memory=64
Disks: (SSD/HDD, count)ssd
base seastar rule no sharing, scylladb deal with one table(one shard) with one cpu?, when that's many requests to one table the cpu will 100% work but other cpu just almoust 100% idle,thus cause service fail,how to fix it?
![图片](https://user-images.githubusercontent.com/5996447/56092635-2442d600-5ef1-11e9-9d0c-01aa30968e9a.png)

**Comment by avikivity** [comment]
If you read/write to one row, you will experience poor performance. You'll only have up to RF nodes in the cluster working, and one core in each node. Scylla was designed for accessing multiple rows in parallel, not just one row.

**Comment by wqwiii** [comment]
> 
> 
> If you read/write to one row, you will experience poor performance. You'll only have up to RF nodes in the cluster working, and one core in each node. Scylla was designed for accessing multiple rows in parallel, not just one row.

we are not just use one row,but one table have many client to use;does scylladb deal with one table just use one cpu?

**Comment by dorlaor** [comment]
Pls share the grafana monitor images and also use cql trace to show a
sample of the data plus provide the schema

**Comment by denesb** [comment]
Data within a table is distributed on two levels: nodes and shards (within nodes). As Avi noted above, a single partition (and by extension a single row) will always be handled by the same shard (within a node). So if your clients distribute their queries well among the partitions of the table, the load will be well distributed among the nodes and CPUs. If your clients happen to hammer the same partition/row then you get bad work distribution like this (hot shard).

**Comment by avikivity** [comment]
If you have architectural questions, please direct them to the mailing list.
