### ISSUE TITLE
epel-release isn't available by default in AMI

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#4431]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20190413.adf539fb2
Cluster size: 1 
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-069a04abcc23e0f8b

* Description: The ami-test failed for installing `pip` by `sudo yum install python2-pip`.
Then I found epel is `no longer` available for scylla AMI.

* Job: http://jenkins.cloudius-systems.com:8080/job/scylla-master/job/ami-tests/label=muninn/36/artifact/job-2019-04-14T02.17-a932046/job.log

```
[centos@ip-172-10-139-189 ~]$ rpm -qa |grep epel
[centos@ip-172-10-139-189 ~]$ 
```

@syuu1228

**Comment by amoskong** [comment]
Quote: 
```
On Mon, Apr 15, 2019 at 4:35 PM Takuya ASADA <syuu@scylladb.com> wrote:
> EPEL is removed from master.
```

It seems it's expected.

**Comment by syuu1228** [comment]
This is expected behavior not an issue, can be close.

**Comment by amoskong** [comment]
> This is expected behavior not an issue, can be close.

Thanks for the confirm.

I already update ami-test to install epel-release by itself, we can close this issue now.
