### ISSUE TITLE
Scylla Docker cannot find python3

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#4432]
Probably related to the latest Python changes, when creating a new image with scylla latest and trying to run the image you get:
/usr/bin/env: python3: No such file or directory

**Comment by glommer** [comment]
Which script is this inside docker?
Scripts now have to be relocated, so if the docker scripts are not relocated we will have to do it too.

**Comment by syuu1228** [comment]
@amnonh @glommer I found that there are python scripts for docker which is not relocated, I'll send fix.

**Comment by syuu1228** [comment]
This issue fixed by 3cf7cf015a7e876d2cb07f292f60cf4ae925407b and 0a874f18973e24ac3bb64d415fdc0a85d06eb16f

**Comment by tzach** [comment]
@amnonh can you please validate with 3.1.0.rc2

**Comment by amnonh** [comment]
Just to be clear, we use python2 for the 2.4 monitoring and it's not part
of scylla.
Typically, the monitoring runs on a different machine.

**Comment by slivne** [comment]
```
python3
Python 3.7.2 (default, Mar 21 2019, 10:09:12) 
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> quit
Use quit() or Ctrl-D (i.e. EOF) to exit
>>> 
[root@8913c9c2bd65 /]# /usr/bin/env python3
Python 3.7.2 (default, Mar 21 2019, 10:09:12) 
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
[root@8913c9c2bd65 /]# 

```
on docker 3.1-rc2 it works
