### ISSUE TITLE
test_nested_user_types failed when list items returned out of order

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4433]
Not clear if this is an issue with the dtest or with scylla.

scylla version b9327f81cfeace41e164fb0eabf14829d592849b
scylla-dtest version scylladb/scylla-dtest@0b2fbb5f4f1765e88678b062dfb0acfcd15d6f08

Seen in [scylla-master/job/next/709/testReport/user_types_test/TestUserTypes/test_nested_user_types](http://jenkins.cloudius-systems.com:8080/view/master/job/scylla-master/job/next/709/testReport/user_types_test/TestUserTypes/test_nested_user_types/):
```
Lists differ: [[[u'stuff3', [u'one_2_other',... != [[[u'stuff2', [u'one_other', u...

First differing element 0:
[[u'stuff3', [u'one_2_other', u'two_2_other']], [u'stuff2', [u'one_other', u'two_other']], [u'stuff4', [u'one_3_other', u'two_3_other']]]
[[u'stuff2', [u'one_other', u'two_other']], [u'stuff3', [u'one_2_other', u'two_2_other']], [u'stuff4', [u'one_3_other', u'two_3_other']]]

+ [[[u'stuff2', [u'one_other', u'two_other']],
- [[[u'stuff3', [u'one_2_other', u'two_2_other']],
? ^^

+   [u'stuff3', [u'one_2_other', u'two_2_other']],
? ^^

-   [u'stuff2', [u'one_other', u'two_other']],
    [u'stuff4', [u'one_3_other', u'two_3_other']]]]
```

The test executes the cql updates sequentially using cqlsh like this:
```
        stmt = """
              UPDATE bucket
              SET other_containers = other_containers + [{{stuff: 'stuff2', more_stuff: {{sub_one: 'one_other', sub_two: 'two_other'}}}}]
              WHERE id={id};
           """.format(id=_id)
        session.execute(stmt)

        stmt = """
              UPDATE bucket
              SET other_containers = other_containers + [{{stuff: 'stuff3', more_stuff: {{sub_one: 'one_2_other', sub_two: 'two_2_other'}}}}, {{stuff: 'stuff4', more_stuff: {{sub_one: 'one_3_other', sub_two: 'two_3_other'}}}}]
              WHERE id={id};
           """.format(id=_id)
        session.execute(stmt)
```

It expects the list items to return in insertion order. See [https://docs.datastax.com/en/cql/3.3/cql/cql_using/useQueryCollections.html](https://docs.datastax.com/en/cql/3.3/cql/cql_using/useQueryCollections.html):
"Retrieve events stored in a list ... Note: The order is not alphabetical, but rather in the order of insertion."

But they are returned inter-mixed (stuff2), (stuff3 stuff4) returns in this order: (stuff3 stuff2 stuff4)

**Comment by slivne** [comment]
For lists AFAIK we use a timestamp to insert the elements into the container.

Since we have three nodes and RF=2 there is nothing enforcing we will pass through the same node, so one possibity is that the inserts are passed through different nodes with different clocks.

Having said that - if we would have used the client timestamp for inserting the elements the order should have been preserved no matter what.

Which timestamp are we using for the container ?

**Comment by denesb** [comment]
We are using `UUID_gen::get_time_UUID_bytes()` and we are either not passing anything or we are passing `db_clock::now()`:

`append`:
https://github.com/scylladb/scylla/blob/d9136f96f3909112cf3aa374dcb473a80f7a9140/cql3/lists.cc#L386-L391

`prepend`:
https://github.com/scylladb/scylla/blob/d9136f96f3909112cf3aa374dcb473a80f7a9140/cql3/lists.cc#L414-L425

In conclusion, it seems we are using the server's timestamp in both cases.

**Comment by slivne** [comment]
@bhalevy can you find this in cassandra as well ... it seems odd that the client provides timestamps and we are using that for cells but are not doing that for collections of elements.

**Comment by bhalevy** [comment]
We started seeing that way more often recently in next runs.
@yaronkaikov what was the recent change you made to the next promotion test fleet and when exactly was it made?
I wonder if it could have anything to do with that.

https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/next/39/testReport/junit/user_types_test/TestUserTypes/dtest___test_nested_user_types/ (job started on `2020-07-14T09:35:25.868Z`)

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2235/testReport/junit/user_types_test/TestUserTypes/dtest___test_nested_user_types/ (job started on `2020-07-14T13:07:02.826Z`)
https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2237/testReport/junit/user_types_test/TestUserTypes/dtest___test_nested_user_types/

**Comment by nyh** [comment]
I think there are two issues here:

1. The test can be fixed easily by having the different list append operations be sent to the **same coordinator** (i.e., set up an "exclusive" session that uses just one coordinator, instead of a regular session). This will close **this** issue (which is about the test's failure).

2. A separate issue is whether using the server time - instead of the request's timestamp - for list appends is correct. This is what Cassandra also does, but it's not an excuse. I'll open a new issue about this.

**Comment by bhalevy** [comment]
@nyh:
> Shouldn't Scylla use the timestamp of the request, not the current time, for the list append???

That's a valid point.  But it could be problematic with user-provided timestamps that violate the insertion order.
Also, updates may change the cells timestamp and should retain the insertion order IIUC.
I think that for strict ordering, the user can use an exclusive connection so to reach the same coordinator.

**Comment by bhalevy** [comment]
@nyh I'm still puzzled about reversal of timestamp, even on different nodes since they are just different processes running on the same node so they shouldn't drift significantly from each other.

**Comment by nyh** [comment]
> @nyh I'm still puzzled about reversal of timestamp, even on different nodes since they are just different processes running on the same node so they shouldn't drift significantly from each other.

Very good point. I imagined in my mind different nodes, but I think you're right - if it's dtest, it's just different processes... They have exactly the same time.

But I think I know what is the problem - and it's even worse than I thought....

In  utils/UUID_gen.hh we have code `create_time_safe()` which supposedly returns unique nano-second resolution time. But it doesn't actually do that...
It seems it actually has a **millisecond** resolution time, with the nanoseconds being used to avoid returning the same number again. But this "protection" only works on the same node.
So, if two updates on two nodes happen to have the same millisecond (sounds quite likely), they can be ordered randomly or even overwrite each other (I'm not sure why we aren't seeing this overwrite, maybe we are and it's just impossible to understand the nosetest output?).

**Comment by yaronkaikov** [comment]
> We started seeing that way more often recently in next runs.
> @yaronkaikov what was the recent change you made to the next promotion test fleet and when exactly was it made?
> I wonder if it could have anything to do with that.
> 
> https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/next/39/testReport/junit/user_types_test/TestUserTypes/dtest___test_nested_user_types/ (job started on `2020-07-14T09:35:25.868Z`)
> 
> https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2235/testReport/junit/user_types_test/TestUserTypes/dtest___test_nested_user_types/ (job started on `2020-07-14T13:07:02.826Z`)
> https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2237/testReport/junit/user_types_test/TestUserTypes/dtest___test_nested_user_types/

@bhalevy Recent changes in next fleet was simply start using a local SSD on spot instead of EBS .

**Comment by nyh** [comment]
In any case, please note that the fix I suggested (to make an "exclusive" session) should - I think - fix this test. I'll open other issues on the underlying list append issue, which shouldn't be related to this test of "nested user types".

**Comment by bhalevy** [comment]
> In any case, please note that the fix I suggested (to make an "exclusive" session) should - I think - fix this test. I'll open other issues on the underlying list append issue, which shouldn't be related to this test of "nested user types".

yes, I agree.  I'll make this change.

**Comment by nyh** [comment]
Opened https://github.com/scylladb/scylla/issues/6846
