### ISSUE TITLE
nodetool gossipinfo

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#444]
Provides the gossip information for the cluster.
http://docs.datastax.com/en/cassandra/2.1/cassandra/tools/toolsGossipInfo.html

**Comment by tzach** [comment]
Usage example in decommission a data-center
http://www.uberobert.com/decommission-cassandra-data-center/

**Comment by asias** [comment]
=== c* 2.1.11
bin/nodetool gossipinfo
localhost/127.0.0.1
 generation:1448958906
 heartbeat:72
 RPC_ADDRESS:3:127.0.0.1
 RELEASE_VERSION:4:2.1.11
 RACK:8:rack1
 NET_VERSION:1:8
 DC:6:datacenter1
 HOST_ID:2:7d23f277-79d4-4dbb-a504-3ce4782208f8
 SEVERITY:74:0.0
 LOAD:24:52917.0
 STATUS:18:NORMAL,-1103534862242593394
 SCHEMA:12:6403a0ff-f93b-3b1f-8c35-0a8dc85a5b66
 TOKENS:17:<hidden>

=== scylla
127.0.0.1
 generation:1448959255
 heartbeat:80
 HOST_ID:9ad46b96-8ed0-4a6e-8ebb-07e5e2b5c19c
 STATUS:NORMAL,3270601696115574654
 RELEASE_VERSION:2.1.8
 RPC_ADDRESS:127.0.0.1
 LOAD:905
 SCHEMA:59adb24e-f3cd-3e02-97f0-5b395827453f
 DC:datacenter1
 NET_VERSION:0
 RACK:rack1

c* 2.1.11 added TOKENS info and the version number for each field.

**Comment by slivne** [comment]
We should not pull only this in we are currently compatible with 2.1.8

**Comment by asias** [comment]
=== c * 2.1.8
./nodetool gossipinfo
localhost/127.0.0.1
  generation:1448963496
  heartbeat:75
  RACK:rack1
  SCHEMA:6403a0ff-f93b-3b1f-8c35-0a8dc85a5b66
  LOAD:52804.0
  NET_VERSION:8
  STATUS:NORMAL,-1032113607154970680
  SEVERITY:0.625
  DC:datacenter1
  HOST_ID:1cd2a254-3d0b-4106-a7f7-d3c28c335ed3
  RPC_ADDRESS:127.0.0.1
  RELEASE_VERSION:2.1.8

**Comment by slivne** [comment]
@amnonh can we close this ?

**Comment by amnonh** [comment]
It is missing the SEVERITY which I think has a different bug on.
The rest is working and tested

**Comment by tzach** [comment]
On ver 0.15 Scylla version still miss TOKEN.
In addition, most of the lines missed additional info element.
For example:
* Scylla: `DC:datacenter1`
* Cassa: `DC:6:datacenter1`

Note the extra `:6`. Similar info elements on all other lines.

**Comment by amnonh** [comment]
I'm comparing the version, what cassanra version are you using? When I try with cassandra 2.18 the output seems the same

**Comment by tzach** [comment]
There is different output format between Cassandra 2.1.8 and 2.1.11
Scylla is compatible to the first, so this is not a bug.
