### ISSUE TITLE
Any updates on implementing SASI indexes into ScyllaDB?

### ISSUE THREAD

**Issue by micobarac** [scylladb/scylla#4440]
Any updates on implementing SASI indexes into ScyllaDB? 

With current secondary indexes, there is no way to use LIKE operator in WHERE clause, nor it is possible to filter timestamp index by range. 
Only EXACT values with = operator are allowed, which is pretty rigid!

My company is considering Scylla as the alternative to DataStax Cassandra, but this problem with indexes are holding us back from it.

Btw, [documentation](https://docs.scylladb.com/getting-started/secondary_indexes/) on indexes seems rather outdated (2016?) and scarce.

```cql
CREATE TABLE audit (
    action_id uuid,
    username text,
    time timestamp,
    arguments text,
    info text,
    ip text,
    roles text,
    status text,
    PRIMARY KEY ((action_id, username), time)
) WITH CLUSTERING ORDER BY (time DESC);

CREATE INDEX ON audit (username);
CREATE INDEX ON audit (time);

SELECT * FROM audit WHERE username LIKE '%admin';

SyntaxException: line 1:26 no viable alternative at input 'username'

SELECT * FROM audit WHERE time >= '2019-04-01' and time < '2019-04-17';

InvalidRequest: Error from server: code=2200 [Invalid query] message="Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING"
```

**Comment by tzach** [comment]
Hi @micobarac 
Closing this issue. Duplicated with https://github.com/scylladb/scylla/issues/2203
Please add your comment and example there!

Also, please take a look at Scylla+ES integration for a similar functionality 
https://www.scylladb.com/2019/03/07/scylla-and-elasticsearch-part-two-practical-examples-to-support-full-text-search-workloads/

**Comment by micobarac** [comment]
@tzach I know that this is a duplicate, but I cannot find any information here or on forum on plans regarding CONTAINS and SPARSE indexes support.

**Comment by nyh** [comment]
@micobarac a bug tracker is not the place to ask questions - you can do this on the Scylla developers or users mailing lists. Also duplicating an issue doesn't double the chance we'll solve it, it only doubles the confusion ;-) Anyway, the short answer is that no, nobody is working on SASI implementation at the moment.
