### ISSUE TITLE
cell locking data structures consume 64KiB of RAM per table

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4441]
Not all tables need this.

**Comment by dekimir** [comment]
Am I correct in presuming this means `table::_counter_cell_locks` allocates too many buckets speculatively?  How can I see/verify this 64KiB consumption for myself?

When you say "Not all tables need this", do you mean that some tables never call `table::lock_counter_cells()`?

**Comment by tgrabiec** [comment]
On Wed, May 15, 2019 at 3:10 AM Dejan Mircevski <notifications@github.com>
wrote:

> Am I correct in presuming this means table::_counter_cell_locks allocates
> too many buckets speculatively?
>
Yes.

> How can I see/verify this 64KiB consumption for myself?
>
I've noticed it on the heap allocation profile:
https://github.com/scylladb/scylla/wiki/Seastar-heap-profiler

You could perhaps also measure it by checking seastar::memory::stats()
before and after the table object is created.


> When you say "Not all tables need this", do you mean that some tables
> never call table::lock_counter_cells()?
>

Yes. Only tables which have counter columns in their schema need this.

>

**Comment by dekimir** [comment]
How about I make `table::_counter_cell_locks` a pointer and allocate it on first use?

**Comment by tgrabiec** [comment]
Sounds good to me.
