### ISSUE TITLE
nodetool cleanup leaves the data in replica's cache

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4446]
The cleanup compaction doesn't invalidate the row cache, so the cleaned up data can still be available to queries once the node regains the ownership of the token range.

I don't think this bug could manifest in inconsistency on the cluster level if decommission / removenode are used to remove the nodes from the ring, because those operations invalidate the ranges of a node who gets its range ownership extended (by calling flush_streaming_mutations()). 

In case a node is forcibly removed without streaming using `nodetool assassinate`, then we could see deleted data being resurrected (not confirmed by experiment).

We should not depend on `flush_streaming_mutations()` in any case because it is not required to invalidate the whole range, it could update the cache from what it received during streaming.

The cleanup compaction should invalidate ranges which are not owned by the node.

**Comment by asias** [comment]
In

https://github.com/scylladb/scylla/issues/4655#issue-464629528

we have a dtest reproducer.

**Comment by asias** [comment]
@slivne @bhalevy Please prioritise this bug. The simple_decommission_node_2_test test will fail after https://github.com/scylladb/scylla/issues/5769.

**Comment by bhalevy** [comment]
@raphaelsc:
> The cleanup compaction should invalidate ranges which are not owned by the node.

We need to address this in higher priority than #828 and the like

**Comment by raphaelsc** [comment]
@bhalevy jumping on it in 3 2 1

**Comment by asias** [comment]
@raphaelsc Can you please update the status of the patch for this issue?

**Comment by raphaelsc** [comment]
On Wed, Feb 19, 2020 at 12:34 AM Asias He <notifications@github.com> wrote:

> @raphaelsc <https://github.com/raphaelsc> Can you please update the
> status of the patch for this issue?
>
working on v2 of [PATCH] sstables/cleanup: Fix stale data being returned
due to lack of cache invalidation

**Comment by avikivity** [comment]
Backported to 3.3.
