### ISSUE TITLE
How to enable large partition in v2.3.1

### ISSUE THREAD

**Issue by xueyilong** [scylladb/scylla#4451]
Hi ,my cluster's version is 2.3.1 and have 3 nodes, i want using large partition,
when i configured the parameter "compaction_large_partition_warning_threshold_mb: 100" in A node and restart A node,it's ok;
but when i configured the parameter in B node and restart B node,it failed,the error is 

 systemd: Starting Scylla Server...
 scylla_prepare: Traceback (most recent call last):
 scylla_prepare: File "/usr/lib/scylla/scylla-blocktune", line 40, in <module>
 scylla_prepare: tune_yaml('/etc/scylla/scylla.yaml', args.nomerges)
 scylla_prepare: File "/usr/lib/scylla/scylla_blocktune.py", line 89, in tune_yaml
 scylla_prepare: y = yaml.load(open(path))
 scylla_prepare: File "/usr/lib64/python3.4/site-packages/yaml/__init__.py", line 72, in load
 scylla_prepare: return loader.get_single_data()
 scylla_prepare: File "/usr/lib64/python3.4/site-packages/yaml/constructor.py", line 35, in get_single_data
 scylla_prepare: node = self.get_single_node()
 scylla_prepare: File "/usr/lib64/python3.4/site-packages/yaml/composer.py", line 36, in get_single_node
 scylla_prepare: document = self.compose_document()
 scylla_prepare: File "/usr/lib64/python3.4/site-packages/yaml/composer.py", line 55, in compose_document
 scylla_prepare: node = self.compose_node(None, None)
 scylla_prepare: File "/usr/lib64/python3.4/site-packages/yaml/composer.py", line 84, in compose_node
 scylla_prepare: node = self.compose_mapping_node(anchor)
 scylla_prepare: File "/usr/lib64/python3.4/site-packages/yaml/composer.py", line 127, in compose_mapping_node
 scylla_prepare: while not self.check_event(MappingEndEvent):
 scylla_prepare: File "/usr/lib64/python3.4/site-packages/yaml/parser.py", line 98, in check_event
 scylla_prepare: self.current_event = self.state()
 scylla_prepare: File "/usr/lib64/python3.4/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
 scylla_prepare: "expected <block end>, but found %r" % token.id, token.start_mark)
 scylla_prepare: yaml.parser.ParserError: while parsing a block mapping
 scylla_prepare: in "/etc/scylla/scylla.yaml", line 17, column 1
 scylla_prepare: expected <block end>, but found '<block mapping start>'
 scylla_prepare: in "/etc/scylla/scylla.yaml", line 613, column 2
 scylla_prepare: Traceback (most recent call last):
 scylla_prepare: File "/usr/lib/scylla/scylla_prepare", line 71, in <module>
 scylla_prepare: run('/usr/lib/scylla/scylla-blocktune')
 scylla_prepare: File "/usr/lib/scylla/scylla_util.py", line 263, in run
 scylla_prepare: return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr)
 scylla_prepare: File "/usr/lib64/python3.4/subprocess.py", line 558, in check_call
 scylla_prepare: raise CalledProcessError(retcode, cmd)
 scylla_prepare: subprocess.CalledProcessError: Command '['/usr/lib/scylla/scylla-blocktune']' returned non-zero exit status 1
 systemd: scylla-server.service: control process exited, code=exited status=1

I check the data_file_directories and commitlog_directory,both owner is scylla user,
what happend to my operation?

**Comment by glommer** [comment]
This indicates there is some problem parsing your yaml file. Please upload it here

**Comment by xueyilong** [comment]
[scylla.yaml.txt](https://github.com/scylladb/scylla/files/3103658/scylla.yaml.txt)

**Comment by glommer** [comment]
According to the logs there are potential problems in (or around) the following lines:

```
cluster_name: 'Cluster'
```

and 
```
compaction_large_partition_warning_threshold_mb: 100
```

However I cannot find anything wrong and I am loading the file just fine.

**Comment by xueyilong** [comment]
Thanks，maybe one more space before 'compaction_large_partition_warning_threshold_mb', now it's ok

Another question is table system.large_partitions is null,that's like no large partition
![image](https://user-images.githubusercontent.com/20434574/56552458-eebb7e00-65bd-11e9-817f-5632571d60a2.png)

But through the grafana monitor find the cluster disk io read is high, increass the memory can't slove.
![image](https://user-images.githubusercontent.com/20434574/56553018-95ece500-65bf-11e9-80a2-48e8c03b0803.png)

![image](https://user-images.githubusercontent.com/20434574/56553075-c6cd1a00-65bf-11e9-8485-74575681a5c6.png)

![image](https://user-images.githubusercontent.com/20434574/56553040-a7ce8800-65bf-11e9-880e-378912801d50.png)

![image](https://user-images.githubusercontent.com/20434574/56553052-b157f000-65bf-11e9-9061-a8a07970d3cd.png)

**Comment by tgrabiec** [comment]
@xueyilong `bad_alloc` can have many causes. You can be getting it because you're out of memory. What do you see on the "non-lsa memory" graph?

You could be out of memory due to a too high concurrency of reads which need to read from sstables, especially if you have many sstables.

**Comment by xueyilong** [comment]
This is about LSA 、cache、 partition and partition graph
![image](https://user-images.githubusercontent.com/20434574/56572785-555a8f00-65f2-11e9-97f5-2ecf922efa1b.png)

1、In one node have 48G memory and 4 cpus ,is it reasonable ? What is the optimum proportion of memory and cpu  (or shards and partition )？

2、Why high concurrency of reads is bad ? How the client connection consumes memory  of scylla?
What 's the Recommend max connections?

**Comment by tgrabiec** [comment]
On Tue, Apr 23, 2019 at 12:31 PM xueyilong <notifications@github.com> wrote:

> This is about LSA 、cache、 partition and partition graph
>
Please split the graphs per shard. Being out-of-memory is a shard-local
condition so looking at totals for all shards is not useful.

Also, provide your total on-disk size of sstable metadata:

    find /var/lib/scylla/data -name *.db -a ! \( -name "*-Data.db" -o -name
"*-Index.db" \) | xargs du -ch


Also, provide the graphs under the "replica" section inside the per-server
metrics dashboard (split by shard, for the node experiencing bad_allocs).
Note that the node which contains the logs of "bad_alloc" may not
necessarily be the one which is experiencing out of memory, the error is
propagated to the coordinator node.



> [image: image]
> <https://user-images.githubusercontent.com/20434574/56572785-555a8f00-65f2-11e9-97f5-2ecf922efa1b.png>
>
> 1、In one node have 48G memory and 4 cpus ,is it reasonable ?
>
Yes.

> What is the optimum proportion of memory and cpu (or shards and partition
> )？
>
Are you asking about the optimum amount of memory per CPU? There is a
minimum recommended amount of about 1G, but I think the more the better.

2、Why high concurrency of reads is bad ?
>

Each read needs memory for the data it reads from disk. If you have too
many reads, you will leave little space for cache or exhaust memory
completely, in which case you will see failures in operations executing on
that node, and maybe even a node crash.

How the client connection consumes memory of scylla?
>
There is some constant and small amount of memory needed for handling a
connection, I don't remember the exact amount. But memory is mostly used by
the ongoing operations you run through the connection. You can have
thousands of active reads on a single connection.

> What 's the Recommend max connections?
>
I think you should use as few connections as possible, but not fewer than
is needed to fully utilize a node. One connection per shard (from the
node's perspective, not a single client's) is best.

**Comment by xueyilong** [comment]
Sorry to reply so later, a node crash yesterday night and delete many history datas to release the cache. 

This is  now total on-disk size of sstable metadata in one node
[total_sstable.txt.zip](https://github.com/scylladb/scylla/files/3111027/total_sstable.txt.zip)

>Each read needs memory for the data it reads from disk. If you have too
many reads, you will leave little space for cache or exhaust memory
completely, in which case you will see failures in operations executing on
that node, and maybe even a node crash.

Do you mean each read needs memory for the different data it reads from disk?
If thousands of active reads read the same data,the memory is share or not ?

>You can have thousands of active reads on a single connection.

Is there have a recommend connection pool between application and scylladb?

**Comment by tgrabiec** [comment]
On Wed, Apr 24, 2019 at 9:31 AM xueyilong <notifications@github.com> wrote:

> Sorry to reply so later, a node crash yesterday night and delete many
> history datas to release the cache.
>
> This is now total on-disk size of sstable metadata in one node
> total_sstable.txt.zip
> <https://github.com/scylladb/scylla/files/3111027/total_sstable.txt.zip>
>
> Each read needs memory for the data it reads from disk. If you have too
> many reads, you will leave little space for cache or exhaust memory
> completely, in which case you will see failures in operations executing on
> that node, and maybe even a node crash.
>
> Do you mean each read needs memory for the different data it reads from
> disk?
>
Yes.

> If thousands of active reads read the same data,the memory is share or not
> ?
>
Sharing is done on the cache level. Data which was read by one read will be
available (until evicted) to the next read because it was inserted into the
cache.

There is no sharing below that. If two reads are populating the cache at
the same time, they will read the data twice.


> You can have thousands of active reads on a single connection.
>
> Is there have a recommend connection pool between application and scylladb?
>

Yes. Existing drivers take care of that. Which driver are you using to
connect to scylla?

>

**Comment by xueyilong** [comment]
>Yes. Existing drivers take care of that. Which driver are you using to
connect to scylla?

All of applications which connect to scylladb is developed by golang.

How to statistically count the reading and writing numbers of connections at one moment or history?

**Comment by tgrabiec** [comment]
On Wed, Apr 24, 2019 at 4:44 PM xueyilong <notifications@github.com> wrote:

> Yes. Existing drivers take care of that. Which driver are you using to
> connect to scylla?
>
> All of applications which connect to scylladb is developed by golang.
>
> How to statistically count the reading and writing numbers of connections
> at one moment or history?
>

We have counters for open connections which you can observe in grafana. The
metric is called "scylla_transport_current_connections", and it's shown on
the "Client CQL connections by ..." graph.

There are no counters for the number of connections which have active
requests.

There is a counter for the number of currently active requests (on any
connection): scylla_transport_requests_serving

**Comment by xueyilong** [comment]
Thank you very much for you help, let me close the issue now
