### ISSUE TITLE
Limited query results when querying a table with a large text column

### ISSUE THREAD

**Issue by asliwinski** [scylladb/scylla#4454]
*Installation details*
Scylla version (or git commit hash): 3.0.5-0.20190414.403f66eca
Cluster size: 1
OS: CentOS
Developer mode: enabled

*Hardware details (for performance issues)*
Platform: VMware

The structure of my table is as follows:
```
CREATE TABLE jobs_cp (
    source text,
    posted timestamp,
    url text,
    company text,
    content text,
    PRIMARY KEY (source, posted, url)
) WITH
  CLUSTERING ORDER BY (posted DESC,url ASC)
```
  
The `content` column contains HTML (2-3 KB) so it's relatively large. The total number of rows in the table is 682, however, when I query the table using the [node.js driver](https://github.com/datastax/nodejs-driver) (`client.execute`) I only get the first 278 rows. Streaming works fine, so it's not much of a problem though. The issue is that apparently I'm not able to access any of the rows past the first 278, even when querying for a single row and a single column which is not `content`.
For instance, trying to pull the `url` field of the 491th row:
```
  const getRows = `SELECT url FROM ${keyspace}.jobs_cp WHERE company = 'Seez' ALLOW FILTERING`;

  const rows = (await client.execute(getRows, [], {
    prepare: true
  })).rows;
```
returns a zero-element array.

When I use `client.stream` it works OK, but it doesn't seem correct to use streaming in order to pull a single row.

I just tested it using a Cassandra VM (https://bitnami.com/stack/cassandra/virtual-machine) and it returns the correct number of rows, so the issue is with Scylla and not the driver.

When I remove the `content` column it works correctly, so it looks like some buffer issue.

The create and insert scripts as well as the scylla.yml can be pulled from:
https://andrzejsliwinski.com/static/scylla.zip

**Comment by bhalevy** [comment]
Cc @eliransin this looks like the mixed order issue you were working on, no?

**Comment by tzach** [comment]
> Cc @eliransin this looks like the mixed order issue you were working on, no?

@eliransin is there an issue to reference?

**Comment by eliransin** [comment]
@tzach and @bhalevy the commit is in but the issue number is #2050 .
Is it reproducible?

**Comment by slivne** [comment]
@asliwinski we have tried to reproduce both cases:
- In the first case when you get the first 278 lines - its because this is the first page, although the default page size is 5000 rows, there is no requirement to return all results, as such scylla optimizes for performance and returns the first page. To receive all rows you can disable paging.
- In the second case ```SELECT url FROM ${keyspace}.jobs_cp WHERE company = 'Seez' ALLOW FILTERING``` - again to optimize for performance scylla returns empty pages in this case as well (allow filtering is executed on the coordinator node and we limit the amount of data we fetch from the replicas) - you can disable paging and you will get the single line.

**Comment by asliwinski** [comment]
@slivne thank you for reproducing the issue and the explanation. I have some concerns though.

- For a "drop-in Apache Cassandra alternative" this behavior is significantly different from the original project.
- If what I'm getting is the first page, then how can I verify it and query for the following pages, apart from switching to `stream()` or `eachRow()` (the `nextPage` property is undefined in the result object, even though `pageState` contains a value, unlike in Cassandra where either `pageState = null` and `nextPage = undefined` or both pageState and nextPage contain values)?
- I don't see a way to disable paging in `cassandra-driver` API (which is Scylla's recommended driver for Node.js).

**Comment by slivne** [comment]
@asliwinski 

1. Cassandra can also change their behavior (to optimize for performance), they have an issue for that https://issues.apache.org/jira/browse/CASSANDRA-6492 - so while it is working for you its not part of the protocol (as can be seen)
2. I expect the nextPage and the pagingStae both to have a value - is this not the case ? if so we may need to look deeper at the nodejs driver (all the other drivers AFAIK return empty pages correctly).

**Comment by slivne** [comment]
@asliwinski are you missing anything - if you are please post and we can reopen.

Please note we did have a bug related to paging with nodejs https://github.com/scylladb/scylla/issues/4569 on secondary indexes (but it does not seem like you were struggling with that).

**Comment by asliwinski** [comment]
@slivne 

> I expect the nextPage and the pagingStae both to have a value - is this not the case ?

This stays wrong, as I explained before, unless you fixed it.
