### ISSUE TITLE
Minor compatibility issue when querying a secondary index column and using IN with one value

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla#4455]
*Installation details*
Scylla version (or git commit hash): 3.0.3
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): docker

The result is:
`InvalidRequest: Error from server: code=2200 [Invalid query] message="Select on indexed columns and with IN clause for the PRIMARY KEY are not supported"`

Cassandra v3.11.13 works fine.

Using __more than one__ value in the IN clause fails in cassandra as well with the same error.

**Comment by nyh** [comment]
We inherited the validation code printing this message from Cassandra, in our code it is:
```c++
void statement_restrictions::validate_secondary_index_selections(bool selects_on
ly_static_columns) {
    if (key_is_in_relation()) {
        throw exceptions::invalid_request_exception(
            "Select on indexed columns and with IN clause for the PRIMARY KEY are not supported");
    }
```
And in the latest Cassandra:
```java
    private void validateSecondaryIndexSelections(boolean selectsOnlyStaticColumns)
    {
        checkFalse(keyIsInRelation(),
                   "Select on indexed columns and with IN clause for the PRIMARY KEY are not supported");
```

So I'm guessing that in Cassandra, somehow a single-value IN clause doesn't match keyIsInRelation(), so it doesn't match this check - but unfortunately I can't find where this actually happens in the Java code (I couldn't find a special case in keyIsInRelation() or in the parser) but it's probably easy to fix in the C++ code even without finding the relevant Java code. 

In any case, note that the general case of IN with multiple values is deliberately not supported in Cassandra: see https://jira.apache.org/jira/browse/CASSANDRA-4386

**Comment by nyh** [comment]
Slight correction: This case is different from what is described in CASSANDRA-4386. There the issue is an IN query on the secondary-indexed column. Here we're talking about a query involving a secondary-indexed column **and** also an IN relation on the **primary** key. So it's an even more esoteric case.

**Comment by nyh** [comment]
Reproducer:
```
       create table cf (p int primary key, a int);
       create index on cf (a);
       insert into cf (p, a) VALUES (1, 2);
       insert into cf (p, a) VALUES (3, 4);
       select * from cf where p = 3 and a = 4      /// works
       select * from cf where p IN (3) and a = 4    /// doesn't work!
```
Note that also `select * from cf where a IN (4)"` doesn't work although equality does, but I guess this is a separate issue.

**Comment by psarna** [comment]
@nyh I'm pretty sure I once saw that a single value `IN` is simply degraded to `EQ` in Cassandra, but I can't find this code now either. That would explain why it doesn't return true from `key_is_in_relation()`.

**Comment by nyh** [comment]
This is driving me crazy - I can add this to our parser, but can't find this code in Cassandra so I'm worried maybe will break something :-(

**Comment by nyh** [comment]
Found it :-)
```java
    {
        ColumnMetadata columnDef = entity.prepare(table);
        List<? extends ColumnSpecification> receivers = toReceivers(columnDef);
        List<Term> terms = toTerms(receivers, inValues, table.keyspace, boundNames);
        if (terms == null)
        {
            Term term = toTerm(receivers, value, table.keyspace, boundNames);
            return new SingleColumnRestriction.InRestrictionWithMarker(columnDef, (Lists.Marker) term);
        }

        // An IN restrictions with only one element is the same than an EQ restriction
        if (terms.size() == 1)
            return new SingleColumnRestriction.EQRestriction(columnDef, terms.get(0));

        return new SingleColumnRestriction.InRestrictionWithValues(columnDef, terms);
    }
```
Added in Cassandra commit 4205011c0fb92bfb6a7456ab620f5d6b40cb9160 from August 2016, which is after we copied the relevant code.
