### ISSUE TITLE
commitlog file header

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#446]
Add a header to commitlog, with version and feature flags, so that updates to the format can be performed.

**Comment by avikivity** [comment]
@elcallio

**Comment by elcallio** [comment]
Actually, the version is already in the file name.
Could add explicit features in the header, but for now, we could 
probably just use version == features.

Den 2015-10-07 kl. 13:39, skrev Avi Kivity:

**Comment by avikivity** [comment]
Ah, the -1-?

An explicit feature list is better, but when you have zero features, you don't really need it.

**Comment by elcallio** [comment]
Indeed the -1-.

Den 2015-10-07 kl. 13:45, skrev Avi Kivity:
