### ISSUE TITLE
Ubuntu 18.04 setup where is {cassandra.logdir}/debug.log

### ISSUE THREAD

**Issue by jneo8** [scylladb/scylla#4468]
*Installation details*
Scylla version (or git commit hash): 3.0.5-0.20190414.403f66eca
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu18.04 LTS

I just install scylla on ubuntu 18.04, I want to see debug.log but there are nothing in `/var/log/cassandra`.

And I can't find any info about logging on ubuntu 18.04 in document.

**Comment by amoskong** [comment]
You can find db log by `journalctl _COMM=scylla`

**Comment by jneo8** [comment]
> You can find db log by `journalctl _COMM=scylla`

Thanks!!
