### ISSUE TITLE
Server status page

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#447]
`http://my.scylla.server:10000`

should have a nice server status html page so I can see the health of the node (membership status, connection count, current operation rate, disk status) at a glance.

**Comment by tzach** [comment]
Something along the lines of the OSv UI? (only better looking)

**Comment by avikivity** [comment]
Yes. Static files with the application running in the browser.

**Comment by tzach** [comment]
I will mock-up a dashboard and share for review
with @haimagami help it will look good and align to our style guide.

**Comment by dorlaor** [comment]
This time I like to have something really neat, way nicer than the boring
osv graphics.
It should have super modern gauges.

As a start it should track a single node but we'll quickly use it for a
whole
cluster gui and later for multiple clusters (and later for world domination)

**Comment by tzach** [comment]
@dorlaor for centralize monitoring we can go with [tessera](https://github.com/urbanairship/tessera) and customize dashboard.
The choice is between a static, stateless server, as @avikivity suggested, or cluster solution which is *not* colocate with Scylla.

**Comment by dorlaor** [comment]
On Sat, Oct 10, 2015 at 9:24 PM, Tzach Livyatan <notifications@github.com>
wrote:

> @dorlaor <https://github.com/dorlaor> for centralize monitoring we can go
> with tessera <https://github.com/urbanairship/tessera> and customize
> dashboard.
> The choice is between a static, stateless server, as @avikivity
> <https://github.com/avikivity> suggested, or cluster solution which is
> *not* colocate with Scylla.
>

A local Tessera/reimann may be a good thing. Let's discuss this further f2f.
The bundled one can be a light weight mgmt and later we can reuse the code
to run as a standalone

**Comment by glommer** [comment]
I would like to close this issue if nobody opposes.
Since then we have moved our stack to prometheus and away from local monitoring.

We may do local monitoring one day but I don't see this day arriving unless we can use scylla itself as a columnar database to store the metrics.

Since pings about older issue tends to just go ignored I am being proactive and closing this. If you disagree and think this should be kept open please reopen
