### ISSUE TITLE
Missing rows in secondary-index on partition-key column, when "UPDATE" used

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#4471]
This is report from a Slack user. The report was missing information on the Scylla version used so it is very possible that this report is nothing more than a duplicate of #4144 which was already fixed in February by commit aa476cd6c99e34dfcaef2eaee25a0b69fceb91ae. However, I want to file an issue in case it turns out this is a new corner case (the test case test_secondary_index_contains_virtual_columns only checks indexing the clustering key, not a partition key column) or a missed backport to one of the extant Scylla branches.

The report:

I am new in scylla and i found something strange to me. In case I do update (upsert) one row who does not exist and write to db secondary index has some strange behavior.
I have a small demo below.
It is a bug or something is missing out on me.
Τhanks

```
CREATE TABLE IF NOT EXISTS keyspace1.table1(
                                            pk1  uuid,
                                            pk2  uuid,
                                            timestamp  timestamp,
                                            dummytext text,
                                            dummyint int,
                                            dummyint2 int,
                                            PRIMARY KEY ((pk1,pk2), timestamp))
                                            WITH CLUSTERING ORDER BY (timestamp DESC);
                                        
CREATE INDEX IF NOT EXISTS idx_1 ON keyspace1.table1 (pk1);
CREATE INDEX IF NOT EXISTS idx_2 ON keyspace1.table1 (pk2);
```

if you do
```
UPDATE table1 SET dummyint = 3, dummyint2 = null, dummytext = null WHERE pk1 =  04c9b91c-0b5b-476f-b026-a9e538f31da6 AND pk2 =  8fecc202-fd95-4ebb-b5f8-37bf50ff277c AND "timestamp" = '2019-12-12T00:00:00.000+0000';
```
instead of
```
INSERT INTO keyspace1.table1(pk1, pk2, timestamp,dummytext,dummyint,dummyint2) VALUES (04c9b91c-0b5b-476f-b026-a9e538f31da6,8fecc202-fd95-4ebb-b5f8-37bf50ff277c,'2019-12-12T00:00:00.000+0000',null,null,1);
```
Then
```
select * from keyspace1.table1 where pk1 = 04c9b91c-0b5b-476f-b026-a9e538f31da6
```
bring nothing
```
select * from keyspace1.table1 where pk2 = 8fecc202-fd95-4ebb-b5f8-37bf50ff277c 
```
bring nothing

```
select * from keyspace1.table1 where pk1 = 04c9b91c-0b5b-476f-b026-a9e538f31da6 and pk2 = 8fecc202-fd95-4ebb-b5f8-37bf50ff277c
```
brings the row

P.S. If you do the insert after update index work properly again

**Comment by aristotelis79** [comment]
Hi @nyh,

Thank you for opening the issue in my on my behalf.
The scylla version is 3.0.4-0.20190313.5e3a52024 via docker host by docker desktop on windows 10 (local machine).

Thanks.

**Comment by nyh** [comment]
Unfortunately, it appears that although we noticed that this patch also should have been back ported to the 3.0 branch, we forgot to do it, so it is missing from the 3.0.4 you used.

**Comment by nyh** [comment]
@avikivity just committed this patch on branch 3.0, so it should be in the next release (@slivne would know if that would be 3.0.5 or 3.0.6). So I'm closing this issue. Please reopen if necessary.
