### ISSUE TITLE
scylla doesn't enforce the use of TSC clocksource, potentially ends up with bad performance

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#4474]
Because Scylla is timestamp-intensive, the choice of the clocksource can have a very big impact on performance. For our AMI, we enforce the TSC clocksource through a boot option, but for users who are not in the AMI that is not enforced.

I debugged a problem today that was pinned to a clocksource other than tsc being used even though tsc was available.

Scylla_setup should enforce that.

**Comment by slivne** [comment]
patch "[PATCH] add option to scylla_setup to check clocksource"

**Comment by avikivity** [comment]
Already everywhere.
