### ISSUE TITLE
Incremental compaction may cause data loss when compaction is interrupted

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#4479]
Scylla version (or git commit hash): b197924

Compaction when interrupted will delete generated sstables, but it may happen that in incremental compaction a sstable generated already replaced an input one, the latter being already deleted.
So it could happen that we would incorrectly get rid of a sstable in face of interruption triggered by something like ENOSPC.

**Comment by bhalevy** [comment]
according to @raphaelsc, needs backport to 3.1

**Comment by avikivity** [comment]
3.1 doesn't have incremental compaction, does it?

**Comment by dorlaor** [comment]
Need to move this to Enterprise

**Comment by raphaelsc** [comment]
On Mon, May 13, 2019, 3:28 PM Avi Kivity <notifications@github.com> wrote:

> 3.1 doesn't have incremental compaction, does it?
>
It turns out it does

**Comment by bhalevy** [comment]
There is an issue for enterprise. It's already backported and closed...
