### ISSUE TITLE
Warn user about using SimpleStrategy with Multi DC deployment

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#4481]
Scylla version (or git commit hash): 3.0

Using Simple-Strategy in a multi-dc deployment is not recommended
Scylla can warn the user is this is the case.

https://docs.scylladb.com/getting-started/ddl/#create-keyspace-statement

**Comment by tzach** [comment]
related to https://github.com/scylladb/scylla/issues/1789

**Comment by slivne** [comment]
- We can write an error/warning to the log 
- Can we return a warning to the client (if this is run via cqlsh) ?
