### ISSUE TITLE
MV hints manager should not share "hints in progress" counter with the regular hints manager

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#4483]
Scylla version (or git commit hash): master (d9136f96f3909112cf3aa374dcb473a80f7a9140)

Refs: https://github.com/scylladb/scylla/issues/4450

Hints manager counts the number of in-flight hints, and if the number hits the limit, it starts applying admission control to the user by returning an `overloaded` error on writes.

Currently, all hints managers share a single resource manager, which takes care of both space usage and limits like `hints in progress`. That may cause anomalies, e.g. high number of MV-related in-flight hints causing regular user writes to be refused with an `overloaded` error. If each manager was responsible for its own `hints in progress`, admission control for regular user writes will only be launched in case of too many regular hints.

One of the solutions could be to move `hints in progress` from a shared resource manager to individual hints managers, so they can take care of their limits, decoupled from other managers.

**Comment by nyh** [comment]
There's something I don't understand here. Is there an inherent reason why "hints in progress" related to materialized views should have a different order of magnitude from those related to base tables? If not, then why is this split important? The only reason I see why it can become important is if, by chance, without MV we already were reaching 90% of the limit, and with MV we are above the limit. But if this is the case, it just seems that the limit was chosen wrong. How is this limit actually chosen?

**Comment by psarna** [comment]
The limit is hardcoded (`static constexpr uint64_t max_size_of_hints_in_progress = 10 * 1024 * 1024; // 10MB`).

The reason for splitting is that the admission control mechanism was meant to start returning errors to the client once it decides that the node can't handle any more pressure. Previously, when there was only one manager, the `hints` resource was only consumed by user writes and admission control worked as expected. Now that we have two hints managers, one of which configurable, the other one used internally for materialized views, the admission control for user writes can fire off just because we generated lots of background view updates and one of the targets was down. That would mean that we favour background writes (that do not even count towards consistency level) over ensuring availability for the user, which I think is detrimental.

So, by splitting, we ensure that mv-hints cannot starve user hints, and that's important, because user hints have a very powerful backpressure mechanism of returning an error to the client.

**Comment by slivne** [comment]
@psarna sent a patch on the ML "[PATCH] db,hints: decouple in-flight hints limits from resource manager"

**Comment by vladzcloudius** [comment]
@slivne I think this should be backported to 2019.1.3 
@glommer What do you think?

**Comment by glommer** [comment]
2019.1.3 is probably too late, but .4, for sure.

**Comment by avikivity** [comment]
Aged out.
