### ISSUE TITLE
query priority class is not used

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#4494]
Scylla 3.0

In 3.0 the "query" priority class is defined:
https://github.com/scylladb/scylla/blob/a20000c1a2b2e0e464c031c57099157d372cc980/service/priority_manager.hh#L72
        , _sstable_query_read(engine().register_one_priority_class("query", 1000))

But it is not been used, this results with missing metrics in the dashboards.
If this is intentional, then the dashboard needs to be changed, if it's by mistake this needs to be fixed.

See https://github.com/scylladb/scylla-grafana-monitoring/issues/601

**Comment by tgrabiec** [comment]
It is used, and I can see metrics for it exported on 3.0.4:

```bash
$ curl http://127.0.0.1:9180/metrics | grep io_queue_query
# HELP scylla_io_queue_query_delay total delay time in the queue
# TYPE scylla_io_queue_query_delay gauge
scylla_io_queue_query_delay{instance="hal",ioshard="0",mountpoint="undefined",shard="0",type="gauge"} 0.000041
# HELP scylla_io_queue_query_queue_length Number of requests in the queue
# TYPE scylla_io_queue_query_queue_length gauge
scylla_io_queue_query_queue_length{instance="hal",ioshard="0",mountpoint="undefined",shard="0",type="queue_length"} 0.000000
# HELP scylla_io_queue_query_shares current amount of shares
# TYPE scylla_io_queue_query_shares gauge
scylla_io_queue_query_shares{instance="hal",ioshard="0",mountpoint="undefined",shard="0",type="gauge"} 1000.000000
# HELP scylla_io_queue_query_total_bytes Total bytes passed in the queue
# TYPE scylla_io_queue_query_total_bytes counter
scylla_io_queue_query_total_bytes{instance="hal",ioshard="0",mountpoint="undefined",shard="0",type="derive"} 315392
# HELP scylla_io_queue_query_total_operations Total bytes passed in the queue
# TYPE scylla_io_queue_query_total_operations counter
scylla_io_queue_query_total_operations{instance="hal",ioshard="0",mountpoint="undefined",shard="0",type="derive"} 55
```

**Comment by amnonh** [comment]
I've tested it with docker Scylla 3.0.6 and i don't see it.
This was originally reported by the field, see:
 scylladb/scylla-grafana-monitoring#601

**Comment by slivne** [comment]
maybe they are created on the fly on the first read ?

amnon did you run a read workload that hit the disk ?

**Comment by amnonh** [comment]
i tried write, mixed and read load

**Comment by gleb-cloudius** [comment]
If your data set is smaller than cache you will not see IO.

--
			Gleb.

**Comment by amnonh** [comment]
I'll try a write load for a longer period and see if I'll get the metrics

**Comment by gleb-cloudius** [comment]
You need to write more, not only longer.

--
			Gleb.

**Comment by amnonh** [comment]
I run it again, limiting the container size, I saw scylla memory rises until the limit.

I'm using a mix load and still nothing.

I'm closing scylladb/scylla-grafana-monitoring#601 as it's clearly not an issue with the dashboards.

**Comment by tzach** [comment]
@amnonh ?

**Comment by slivne** [comment]
@amnonh - after doing populate can you please try to stop the node and start the node - it will force the node todo reads from disk and not potentially having everything in cache/memtables

**Comment by gleb-cloudius** [comment]
On Sun, May 19, 2019 at 03:14:37AM -0700, Shlomi Livne wrote:
> @amnonh - after doing populate can you please try to stop the node and start the node - it will force the node todo reads from disk and not potentially having everything in cache/memtables
> 
Do we flush sstable on stop? If not and the dataset is less than the
threshold we flush sstable at all the data will be in commitlog and will
be replayed into the memtable. Force flush and restart will work.

--
			Gleb.

**Comment by amnonh** [comment]
After flush I did start seen metrics report so I'm closing.
