### ISSUE TITLE
scylla_setup does not find python psutil and fails in debian tests

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4495]
scylla version 285ada503557c367ae32aa4111091c01edaefb00

As seen in, e.g. [scylla-master/job/ubuntu-deb-16.04-test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/ubuntu-deb-16.04-test/lastFailedBuild/label=huginn/artifact/latest/job.log):
```
2019-05-14 07:42:18,919 process          L0333 INFO | Running '/usr/lib/scylla/scylla_setup --nic ens3 --disks /dev/vdb --no-cpuscaling-setup'
2019-05-14 07:42:19,054 process          L0420 DEBUG| [stderr] Traceback (most recent call last):
2019-05-14 07:42:19,055 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_setup", line 30, in <module>
2019-05-14 07:42:19,055 process          L0420 DEBUG| [stderr]     from scylla_util import *
2019-05-14 07:42:19,055 process          L0420 DEBUG| [stderr]   File "/usr/lib/scylla/scylla_util.py", line 32, in <module>
2019-05-14 07:42:19,055 process          L0420 DEBUG| [stderr]     import psutil
2019-05-14 07:42:19,055 process          L0420 DEBUG| [stderr] ImportError: No module named 'psutil'
```

Is the following required?
```
diff --git a/dist/debian/control.mustache b/dist/debian/control.mustache
index f493be7592..23ab129488 100644
--- a/dist/debian/control.mustache
+++ b/dist/debian/control.mustache
@@ -16,7 +16,7 @@ Conflicts: {{product}}-server (<< 1.1)
 
 Package: {{product}}-server
 Architecture: amd64
-Depends: ${shlibs:Depends}, ${misc:Depends}, adduser, hwloc-nox, {{product}}-conf, python-yaml, python-urwid, python-requests, curl, util-linux, python3-yaml, python3, uuid-runtime, pciutils, python3-pyudev, gzip, realpath | coreutils, num-utils, file
+Depends: ${shlibs:Depends}, ${misc:Depends}, adduser, hwloc-nox, {{product}}-conf, python-yaml, python-urwid, python-requests, python-psutil, curl, util-linux, python3-yaml, python3, uuid-runtime, pciutils, python3-pyudev, gzip, realpath | coreutils, num-utils, file
 Description: Scylla database server binaries 
  Scylla is a highly scalable, eventually consistent, distributed,
  partitioned row DB.
```

**Comment by glommer** [comment]
If this is master, let's please move debian to relocatable python as well -> this way we'll be immune to these problems. Takuya had already suggested that, and I believe that should be the solution we adopt.

**Comment by bhalevy** [comment]
> If this is master, let's please move debian to relocatable python as well -> this way we'll be immune to these problems. Takuya had already suggested that, and I believe that should be the solution we adopt.

It's in 3.1 as well.

**Comment by glommer** [comment]
yes, because 3.1 also uses the same infrastructure. It should have the same change

**Comment by bhalevy** [comment]
@glommer @syuu1228 I'm not sure we want such a big change as moving debian to relocatable python in 3.1.  We may need a less intrusive (and quick to deliver) solution in 3.1
@penberg / @avikivity / @slivne what's your take?

**Comment by bhalevy** [comment]
Reverted in 5f6c5d566a4dc70a2f4000b6797f09b6683598ec, reopening.

Cc @eliransin @penberg
