### ISSUE TITLE
UX: add scylla version to AMI description or Tags

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#4499]
*Installation details*
Scylla version (or git commit hash): latest master
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): AMI

How about add installed packages list to AMI description? Or use the AMI tags.

```
scylla-server-666.development-0.20190416.52e1125b5.el7.x86_64
scylla-tools-core-666.development-20190416.afb1857210.noarch
scylla-kernel-conf-666.development-0.20190416.52e1125b5.el7.x86_64
scylla-666.development-0.20190416.52e1125b5.el7.x86_64
scylla-tools-666.development-20190416.afb1857210.noarch
scylla-jmx-666.development-20190416.cb1ac4a.noarch
scylla-conf-666.development-0.20190416.52e1125b5.el7.x86_64
scylla-python3-3.7.2-0.20190416.52e1125b5.el7.x86_64
```

At least the scylla version `scylla-666.development-0.20190416.52e1125b5` is very useful.

@syuu1228 @tzach

**Comment by tzach** [comment]
+1
Just made the same comment
https://github.com/scylladb/scylla-enterprise/issues/288#issuecomment-492523426

**Comment by syuu1228** [comment]
@amoskong @tzach Seems like we can add description or tags in Packer which is what we use for generating AMIs, so I'll try to test it.
https://www.packer.io/docs/builders/amazon-ebs.html
