### ISSUE TITLE
Impossible to gracefully stop scylla in the middle of bootstrapping

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#4501]
*Installation details*
HEAD: 285ada503557c367ae32aa4111091c01edaefb00
Cluster size: 4 = 3 + 1 (bootstrapping)

*Description*
scylla doesn't react to any signal when node is in the middle of bootstrapping.
The only way to stop scylla in this case is `kill -9`.

Reproducible with a 3 nodes `ccm` cluster when you add a new node to it and try to issue a `ccm node4 stop` command before the bootstrapping node finished joining.

This is a regression introduced but this patch.

```
commit b19792405faee91ed9410357dc41b7cda648690f
Author: Avi Kivity <avi@scylladb.com>
Date:   Sat Apr 20 20:57:33 2019 +0300

    main: RAII-ify shutdown
    
    Instead of app-template::run_deprecated() and at_exit() hooks, use
    app_template::run() and RAII (via defer()) to stop services. This makes it
    easier to add services that do support shutdown correctly.
    
    Ref #2737
    Message-Id: <20190420175733.29454-1-avi@scylladb.com>
```

**Comment by slivne** [comment]
@avikivity - any comments ?

**Comment by slivne** [comment]
@avikivity ?

**Comment by bhalevy** [comment]
Ref #4384

**Comment by avikivity** [comment]
Aged out.
