### ISSUE TITLE
Respect maximum sstable size for large partitions

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#4504]
*Installation details*
Scylla version (or git commit hash): b19792405faee
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Currently, we are only able to stop at partition boundary. So if compaction has a 10GB partition in the input sstables and maximum sstable size is 1GB for example, that large partition would end up all in just one sstable regardless.

**Comment by raphaelsc** [comment]
Avi says: "LCS cannot split a partition. If it does, then a partition key can be found on more than one sstable in a level, violating the constraint (potentially on all sstables in a level)."

Raphael says: "Makes sense. It looks like we should then recommend that LCS should be
configured such that partition size will not disrespect max sstable size.
That disrespect implies in each level having less sstables, which may
increase further the write amplification. Level L is supposed to have 10^L
sstables. A large partition of size S could reduce that # of sstables in a
level to (10^L*max_sstable_size)/S. With L=2 and S=1G and
max_sstable_size=100M, L2 will have only 10 sstables instead of 100, each
containing only 1 partition. When merging L1 into L2, we could end up
rewriting the whole L2, given that 1 sstable in L1 could contain fragments
of all partitions in L2. So is it that the number of sstables in a given L
is also important because of write amplification? That seems to be a
problem only with large partitions."

We should either drop this or move towards a different solution to make LCS behave better with large partitions.

**Comment by glommer** [comment]
Closing, we're not doing this
