### ISSUE TITLE
multishard_mutation_query: forward the received `io_priority_class` to the shard reader

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#4506]
*Installation details*
Scylla version (or git commit hash): master, 3.1, 3.0

Currently `query_mutations_on_all_shards()` doesn't pass the received `io_priority_class` to shard readers created on remote shards. This is because, at the time that code was written, passing `io_priority_class` across shards was not possible. So `query_mutations_on_all_shards()` creates remote readers with `service::get_local_sstable_query_read_priority()`, regardless of what the passed in `io_priority_class` was. So far this was fine as this method is only used for queries. However, this has to be remedied as `query_mutations_on_all_shards()` is intended to be a generic building block for multi-shard scans (and indeed it will be used by row-level repair as well). Thankfully, since https://github.com/scylladb/seastar/commit/cd9a78e2 it is possible to pass `io_priority_class` through shard boundaries, so the fix should be easy.

**Comment by denesb** [comment]
Fixed in 18581cfb76472f65a88b6b40817a4331da652ca2 so now all readers on all shards use the same priority class, however `query_mutation_on_all_shard()` still doesn't take a priority class itself and always uses `service::get_local_sstable_query_read_priority()`.

**Comment by avikivity** [comment]
@denesb please file an issue for q_m_o_a_s().

**Comment by denesb** [comment]
@avikivity the other query_ variants don't take a priority class. Is there a reason `query_mutation_on_all_shard()` should be different in this regard? I realize the description of this issue might suggest that `query_mutation_on_all_shard()` is the entry point for all range scans, but in fact it is only used for queries (like its name suggests), repair for example uses `make_multishard_streaming_reader()`, which is of course hard-coded to use the streaming priority class.
