### ISSUE TITLE
mulit in relation: tuple element type mismatch

### ISSUE THREAD

**Issue by LouayKamel** [scylladb/scylla#4509]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.4
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora/Centos

Hi everyone,

There is a **Possibility of a bug in multi_in_relation** 

Consider the following statement 
`SELECT * FROM table WHERE pk = ? AND (ckey_1, ckey_2) IN ? ;`

Data types:
`pk is varchar, ckey_1 is tinyint, ckey_2 is varint`

The problem: 

`(ckey_1, ckey_2) IN ? ` 

value structure -> ( {:list, {:tuple, [:tinyint, :varint] } , [ [**1**,**2**] ] )
value binary(buffer) -> <<0, 0, 0, 1, 0, 0, 0, 10, 0, 0, 0, 1, **1**, 0, 0, 0, 1, **2**>>
Received response -> **Error**{message: "**tuple element type mismatch**", reason: :server_failure}

I tried many schema and types but the problem still the same,

Would you please elaborate, what's going on? am I doing something wrong?

Note: **The following queries does work perfectly:** 
1. `(ckey_1,ckey_1) = ? `  {:tuple, [:tinyint, :varint] }
2. `(ckey_1) IN ? `   {:list, {:tuple, [:tinyint] }
3. `ckey_1 IN ?`  {:list, :tinyint }

Thanks

**Comment by slivne** [comment]
@LouayKamel I have tried the following

```
create table t (pk int, ck1 int, ck2 int, val int, primary key (pk,ck1,ck2));
cqlsh:ks> insert into t (pk, ck1 , ck2 , val) values (1,1,1,1);
cqlsh:ks> insert into t (pk, ck1 , ck2 , val) values (1,1,2,1);
cqlsh:ks> insert into t (pk, ck1 , ck2 , val) values (1,1,3,1);
cqlsh:ks> select * from t WHERE pk=1;

 pk | ck1 | ck2 | val
----+-----+-----+-----
  1 |   1 |   1 |   1
  1 |   1 |   2 |   1
  1 |   1 |   3 |   1

(3 rows)
cqlsh:ks> select * from t WHERE pk=1 and ck1 in (1) and ck2 in (1,2);

 pk | ck1 | ck2 | val
----+-----+-----+-----
  1 |   1 |   1 |   1
  1 |   1 |   2 |   1

(2 rows)
cqlsh:ks> select * from t WHERE pk=1 and (ck1,ck2) in ((1,2));

 pk | ck1 | ck2 | val
----+-----+-----+-----
  1 |   1 |   2 |   1

(1 rows)
cqlsh:ks> select * from t WHERE pk=1 and (ck1,ck2) in ((1,2),(1,3));

 pk | ck1 | ck2 | val
----+-----+-----+-----
  1 |   1 |   2 |   1
  1 |   1 |   3 |   1

```

creating a sample in python to use prepared statements 

```
from cassandra.cluster import Cluster

cluster = Cluster(['172.17.0.2'])

session = cluster.connect()

p = session.prepare("select * from ks.t WHERE pk=1 and (ck1,ck2) in ?");
res = session.execute(p,[((1,2),(1,3))]);
print res[0]
print res[1]
```

you can try and run this and check what the binary format used on the wire.

Please update the issye so we can close it

**Comment by LouayKamel** [comment]
@slivne interesting I tried your schema and it worked fine, but unfortunately the problem still in the following table schema.
```
CREATE TABLE ks.t (
    v1 text,
    lb tinyint,
    ts varint,
    v2 text,
    ex text,
    ix varint,
    el varint,
    lx varint,
    sx text,
    PRIMARY KEY (v1, lb, ts, v2, ex, ix)
) WITH CLUSTERING ORDER BY (lb ASC, ts DESC, v2 ASC, ex ASC, ix ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cqlsh:tangle> INSERT INTO t (v1, lb, ts, v2, ex, ix) VALUES ( '1', 1, 1, 'v2', 'ex', 0);
cqlsh:tangle> INSERT INTO t (v1, lb, ts, v2, ex, ix) VALUES ( '1', 1, 2, 'v2', 'ex', 0);
cqlsh:tangle> INSERT INTO t (v1, lb, ts, v2, ex, ix) VALUES ( '1', 1, 3, 'v2', 'ex', 0);
```
creating a sample in python to use prepared statements
```
from cassandra.cluster import Cluster

cluster = Cluster(['172.17.0.2'])

session = cluster.connect()

p = session.prepare("select * from ks.t WHERE v1='1' and (lb,ts) in ?");
res = session.execute(p,[((1,2),(1,3))]);
error: message="tuple element type mismatch"
```

Thank you for taking the time to resolve this issue.
