### ISSUE TITLE
Build from source instructions in README.md

### ISSUE THREAD

**Issue by dmarti** [scylladb/scylla#451]
The README.md includes instructions on how to build RPM packages and a Docker container, but not how to do an old-fashioned build from source (just running configure.py and then ninja-build).

Is it possible to add those two steps, or will the user end up with something missing?

**Comment by avikivity** [comment]
Well, need `git submodule update --init --recursive`, and to install dependencies, and be on Fedora 21+, but otherwise it should just work.

**Comment by avikivity** [comment]
Note that dependencies include seastar dependencies; we should bring them to scylla's README.

**Comment by dmarti** [comment]
These are the instructions that I have been using ( @penberg posted to the mailing list)

`./configure.py --mode=release --with=scylla --disable-xen`

`ninja-build -j2 # you can use more cpus if you have tons of RAM`

and a shiny new Scylla executable appears in:

`build/release/scylla`
