### ISSUE TITLE
scylla seems to ignore listen_address

### ISSUE THREAD

**Issue by pkesso** [scylladb/scylla#4511]
It seems that scylla ignores listen_address in config. I can reproduce it on 2 clusters of 3 nodes.  I set listen_address in /etc/scylla/scylla.yml to the server's ip address:

    listen_address: 10.30.7.67
But I only can connect on 127.0.0.1:

    telnet 10.30.7.66 9042
    Trying 10.30.7.66...
    telnet: connect to address 10.30.7.66: Connection refused

    telnet 127.0.0.1 9042
    Trying 127.0.0.1...
    Connected to 127.0.0.1.
    Escape character is '^]'.

I did restart service, and even reboot node. 

*Installation details*

scylla version 3.0.6-0.20190503.bf68fae01
Cluster size: 3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos 7 latest

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical 64bit

**Comment by glommer** [comment]
clients connect to rpc_address, not to listen_address
