### ISSUE TITLE
Nodetool tablestats reports inconsistent bloom filter size

### ISSUE THREAD

**Issue by gibsn** [scylladb/scylla#4513]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.6
Cluster size: 6 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.5.1804

We tried to make a BF_size(num_partitions) plot (https://plot.ly/~Bychin/42.embed) out of `nodetool tablestats` output and it looks like BF size stays ~const with the number of partitions constantly growing, while I would expect  it to constantly grow. According to our research in dev 1B partitions would require ~600MB BF with 10%FP. `ls` of bloom filters in the data directory reports something closer to 600MB rather than 60MB.

We have TWCS, writing ~300M new unique partitions every week, never expiring old data. To me it looks like `nodetool tablestats` reports size of something close to BF of one time window.

**Comment by tzach** [comment]
@amnonh ?

**Comment by slivne** [comment]
@gibsn 

> ls of bloom filters in the data directory reports something closer to 600MB rather than 60MB.

I expect you meant _ls of bloom filters in the data directory reports something closer to 60MB rather than 600MB._

**Comment by gibsn** [comment]
> @gibsn
> 
> > ls of bloom filters in the data directory reports something closer to 600MB rather than 60MB.
> 
> I expect you meant _ls of bloom filters in the data directory reports something closer to 60MB rather than 600MB._

Nope, the opposite, that is the issue

**Comment by amnonh** [comment]
I assume that the graph was based on `Bloom filter space used`.

@gibsn to validate, can you add the output from `nodetool tablestats`?

It is mapped to get_bloom_filter_disk_space_used and to sstable::filter_size() that seems ok but maybe I'm missing something.

**Comment by gibsn** [comment]
@amnonh
>I assume that the graph was based on Bloom filter space used.

Yes
 
> can you add the output from nodetool tablestats

We have altered the BF FP chance so now the BF size is different.

```
        Read Count: 3
        Read Latency: 0.2906666666666667 ms
        Write Count: 4114707003
        Write Latency: 1.542649499799634E-5 ms
        Pending Flushes: 1
                Table: events
                SSTable count: 840
                SSTables in each level: [840/4]
                Space used (live): 6064358297895
                Space used (total): 6064358297895
                Space used by snapshots (total): 0
                Off heap memory used (total): 6479468528
                SSTable Compression Ratio: 0.238855
                Number of partitions (estimate): 2134840631
                Memtable cell count: 1465331
                Memtable data size: 4183223741
                Memtable off heap memory used: 6058409984
                Memtable switch count: 4940
                Local read count: 3
                Local read latency: 290.795 ms
                Local write count: 2082682629
                Local write latency: 0.016 ms
                Pending flushes: 1
                Percent repaired: 0.0
                Bloom filter false positives: 0
                Bloom filter false ratio: 0.00000
                Bloom filter space used: 172093920
                Bloom filter off heap memory used: 172093800
                Index summary off heap memory used: 248964744
                Compression metadata off heap memory used: 0
                Compacted partition minimum bytes: 73
                Compacted partition maximum bytes: 21356903512
                Compacted partition mean bytes: 13371
                Average live cells per slice (last five minutes): 0.0
                Maximum live cells per slice (last five minutes): 0
                Average tombstones per slice (last five minutes): 0.0
                Maximum tombstones per slice (last five minutes): 0
                Dropped Mutations: 0
```

**Comment by amnonh** [comment]
@slivne how we calculate BF size currently:
For every-shard:
    For every table (one or more):
         for every stable:
              sum filter_size

Maybe it should be counted only once per table?

**Comment by avikivity** [comment]
@amnonh looks like it's still broken.

**Comment by gibsn** [comment]
Another update:

BF and Summaries size as seen by ls -l:
```
Shard	Bloom Filter	Summary File
0	114.39 MB	96.03 MB
1	119.52 MB	96.08 MB
2	111.02 MB	95.31 MB
3	116.24 MB	95.51 MB
4	121.30 MB	95.62 MB
5	121.83 MB	95.40 MB
6	121.09 MB	95.39 MB
7	126.93 MB	96.08 MB
8	115.89 MB	95.53 MB
9	122.62 MB	94.63 MB
10	122.40 MB	94.50 MB
11	117.53 MB	94.63 MB
12	121.30 MB	94.14 MB
13	116.83 MB	94.49 MB
14	119.55 MB	93.73 MB
15	127.94 MB	93.71 MB
16	123.23 MB	94.12 MB
17	126.13 MB	94.62 MB
18	119.07 MB	94.35 MB
19	123.24 MB	94.67 MB
20	118.13 MB	95.05 MB
21	118.64 MB	94.36 MB
22	122.86 MB	94.16 MB
23	119.97 MB	94.90 MB
24	123.28 MB	95.10 MB
25	118.91 MB	95.05 MB
26	121.33 MB	95.52 MB
27	126.40 MB	94.80 MB
28	126.08 MB	95.08 MB
29	120.95 MB	95.36 MB
```

While cfstats for this node gives us:
```
                Bloom filter off heap memory used: 141708400
                Index summary off heap memory used: 233749582
```

**Comment by slivne** [comment]
We used to have shared sstables - this is not possible anymore - we reshard sstables on boot - so this can't be the cause anymore.

Looking at the numbers shared https://github.com/scylladb/scylla/issues/4513#issuecomment-627936880  it seems that we are not summing up all shards and only returning a single shard value - @amnonh - can you please double check this again.

**Comment by amnonh** [comment]
It seems that sstable::filter_size return the wrong information.
I've run a single node with 3 shards. run a load and did nodetool flush.
The reported filter size is:
``Bloom filter space used: 218536``

After the first ``nodetool flush`` the files in the directory are:
$ ls -lrt tmp_data/data/keyspace1/standard1-bf420360639a11eba96e6288801e4a2e/*Filter.db
-rw-r--r--. 1 amnon amnon 73464 Jan 31 10:03 tmp_data/data/keyspace1/standard1-bf420360639a11eba96e6288801e4a2e/md-4-big-Filter.db
-rw-r--r--. 1 amnon amnon 72576 Jan 31 10:03 tmp_data/data/keyspace1/standard1-bf420360639a11eba96e6288801e4a2e/md-5-big-Filter.db
-rw-r--r--. 1 amnon amnon 72496 Jan 31 10:03 tmp_data/data/keyspace1/standard1-bf420360639a11eba96e6288801e4a2e/md-3-big-Filter.db
which is correct.

After the second flush, the reported bloom filter size remain the same but
$ ls -lrt tmp_data/data/keyspace1/standard1-bf420360639a11eba96e6288801e4a2e/*Filter.db
-rw-r--r--. 1 amnon amnon  73464 Jan 31 10:03 tmp_data/data/keyspace1/standard1-bf420360639a11eba96e6288801e4a2e/md-4-big-Filter.db
-rw-r--r--. 1 amnon amnon  72576 Jan 31 10:03 tmp_data/data/keyspace1/standard1-bf420360639a11eba96e6288801e4a2e/md-5-big-Filter.db
-rw-r--r--. 1 amnon amnon  72496 Jan 31 10:03 tmp_data/data/keyspace1/standard1-bf420360639a11eba96e6288801e4a2e/md-3-big-Filter.db
-rw-r--r--. 1 amnon amnon 416848 Jan 31 10:18 tmp_data/data/keyspace1/standard1-bf420360639a11eba96e6288801e4a2e/md-7-big-Filter.db
-rw-r--r--. 1 amnon amnon 417144 Jan 31 10:18 tmp_data/data/keyspace1/standard1-bf420360639a11eba96e6288801e4a2e/md-8-big-Filter.db
-rw-r--r--. 1 amnon amnon 416048 Jan 31 10:18 tmp_data/data/keyspace1/standard1-bf420360639a11eba96e6288801e4a2e/md-6-big-Filter.db

So the filter is set once and never updated, note that it should take into concideration the entire size.
I suspect ``sstable::update_info_for_opened_data`` is to blame but I didn't investigate it futher.

**Comment by amnonh** [comment]
@slivne I'm unassigning myself, re-assign me if I'm needed

**Comment by bhalevy** [comment]
@amnonh the bug is in `cf::get_bloom_filter_disk_space_used` and friends in the way they use [std::accumulate](https://en.cppreference.com/w/cpp/algorithm/accumulate)
The functor passed to it is binary and it should sum the current value into the accumulator, which it doesn't.

**Comment by amnonh** [comment]
@bhalevy have you seen the way I reproduced the issue?

**Comment by bhalevy** [comment]
@amnonh how is this unary?
https://github.com/scylladb/scylla/blob/bb202db1ff7c0a3889ec9a7e9c971cbeee7f18e7/api/column_family.cc#L658-L660

It needs to do this:
```
            return std::accumulate(cf.get_sstables()->begin(), cf.get_sstables()->end(), uint64_t(0), [](uint64_t s, auto& sst) {
                return s + sst->filter_size();
            });
```

**Comment by avikivity** [comment]
Backported to 4.2, 4.3, 4.4.
