### ISSUE TITLE
Install on RHEL 6.6/CentOS 6.6

### ISSUE THREAD

**Issue by dmarti** [scylladb/scylla#452]
Additional dependencies required?

**Comment by avikivity** [comment]
I doubt that xfs support is at the same level as R7.  In addition our init scripts are for systemd, not whatever R6 uses.

**Comment by avikivity** [comment]
(besides tons of other dependencies, but we could supply those without a huge effort)

**Comment by maticmeznar** [comment]
I recommend NOT spending time supporting old, non-systemd distributions like CentOS 6, Ubuntu 14.04 LTS, Debian 7, etc. Developer time could be better spent elsewhere. The most popular server OS in the cloud is Ubuntu and new LTS comes in April 2016 with systemd support. I recommend supporting that when it's released.

**Comment by avikivity** [comment]
Makes sense.  We should target 15.10 now (with a dependency on systemd).

**Comment by avikivity** [comment]
RHEL 6 will not be supported. Looking forward to RHEL 8.
