### ISSUE TITLE
Request for enhancement  nodetool toppartitions - need to be more general

### ISSUE THREAD

**Issue by nirmaayan** [scylladb/scylla#4520]
When using ``nodetool toppartitions`` we need to specify ``keyspace`` and ``table`` (and duration)

We need to have a more generic scan for the active toppartitions 

For example 

nodetool toppartitions <ks> <duration> and not specify the table.
This way we can have a more general scan for our toppartitions.

**Comment by avikivity** [comment]
Agree that it is a natual change (and indeed makes more sense than what we have).
