### ISSUE TITLE
tests.py oversbscribes `aio-max-nr`

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#4522]
*Installation details*
Scylla version (or git commit hash): master

On a sufficiently beefy machine `tests.py` will run enough test jobs parallelly to exhaust the number of `aio` ops on the machine, causing random tests to fail. Currently `tests.py` determines the amount of jobs to run by the amount of available RAM. It should also take into consideration the amount of `aio` ops available and make sure each test process will be able to allocate the amount of `aio` ops it needs to run.

**Comment by glommer** [comment]
why not just bump aio ops ? It's just a proc file

**Comment by avikivity** [comment]
It's greately exacerbated by aio-poll, which needs to allocate aio slots for polls and not just file I/O. We can have the tests allocate fewer poll slots, since they usually don't serve millions of connections.

**Comment by kostja** [comment]
Never happened here, but maybe because I set aio-max-nr to ridiculously high value. Is it still relevant? If so, what should be the fix, in the tests or in test.py? I'd say the fix should be in HACKING.md, where we should instruct ppl to change aio-max-nr for any serious hacking.

**Comment by denesb** [comment]
I would settle for an entry in "troubleshooting" (if we have that) in HACKING.md as a fix for this.

**Comment by avikivity** [comment]
That's strange, test.py only runs two shards per test, so it shouldn't consume so many.

Anyway, we can also tell it to consume even less, since it's not going to be accepting thousands of network connections.

**Comment by denesb** [comment]
I haven't seen this in a long time, it is possible that it was fixed, maybe because I bumped my `aio-max-nr` to a really high number.

**Comment by avikivity** [comment]
Closing until it happens again.
