### ISSUE TITLE
Compaction not releasing sstables early as efficiently as it could

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#4531]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

Installation details
Scylla version (or git commit hash): 616932528
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

We have two runs A and B, each divided to 5 fragments, A1..A5, B1..B5.

They have the following token ranges:

 A:  A1=[0, 3]   A2=[4, 7]  A3=[8, 11]   A4=[12, 15]    A5=[16,18]
B is the same as A's ranges, offset by 1:

 B:  B1=[1,4]    B2=[5,8]  B3=[9,12]    B4=[13,16]    B5=[17,19] 
Let's say we are finished flushing output until position 10 in the compaction. We are currently working on A3 and B3, so obviously those
cannot be deleted.
Because B2 overlaps with A3, we cannot delete B2 either.
Now, A2 overlaps with B2 which we couldn't delete yet, so we can't delete A2.
Now A2 overlaps with B1 so we can't delete B1. And B1 overlaps with A1 so we can't delete A1.
So we can't delete any fragment.

There are two solutions available:

A)

Imagine that we had a "midway" between completely deleting an sstable and completely keeping it. This midway would be to turn the sstable (perhaps by renaming it or adding a flag somewhere or a new sstable component) into a "tombstone-only" sstable. A "tombstone-only" sstable is still its original data intact, but any time it is read the reader ignores all data except the tombstones. So no data from such an sstable could be ressurected.

Now, let's return to my example above. We are working on compacting fragments A3 and B3.
B2 was already fully compacted and flushed, so we wanted to delete it but can't because it overlaps with A3 and may contain purged tombstones for A3's data.
So we mark B2 "tombstone-only sstable".
Now, A2 intersects with B2, but we can completely delete it! Because B2 is not permanently a "tombstone-only sstable", its data can never be resurected so it doesn't matter if A2 contains tombstones for it.

B)

Instead of purging tombstones right away, write those tombstones (which would be purged) into a temporary sstable run that would be deleted at the end of compaction. Mutation compaction would feed such tombstones to compaction via a callback (like we do when calculating max purgeable timestamp), and that tombstone would be written to a sstable writer that was opened for it. The performance penalty is relatively small because of the size of the tombstone data.

CONCLUSION:
B) is more efficient than solution A) because all the non-exhausted fragments can be released at a point in which a new fragment is sealed in the incremental compaction process. Also it's less intrusive in that the invariant of immutable sstable isn't broken, sstable read path code isn't changed, and that no further complexity is introduced to the system, meaning implementation of B) is also easier.

**Comment by tgrabiec** [comment]
> The performance penalty is relatively small because of the size of the tombstone data.

It depends. It's not true for TTLed data sets, where most of the sstable may be expired.
