### ISSUE TITLE
A partition key index may cause a regular query to fail with "No such index"

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#4539]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): master (9213d56a069a223c0009ab2c2677aa408cf6b5cb)

The following, perfectly legal sequence of queries:
~~~
CREATE TABLE test_a(a BIGINT, b BIGINT, c BIGINT, PRIMARY KEY ((a, b)));
CREATE INDEX ON test_a(a);
INSERT INTO test_a (a, b, c) VALUES (1, 2, 3);
SELECT * FROM test_a WHERE a=1 AND b=2 AND c = 3 ALLOW FILTERING;
~~~
will cause a `No index found.` error, because there's a bug in the code that tries to figure out if a query is an indexed query or a regular one. I'm leaving the issue here as a placeholder, as I already pinpointed the problem, but I need some time to provide it with proper tests. Feel free to assign this issue to me.

**Comment by slivne** [comment]
@psarna do we need to backport this to 3.0 ?

**Comment by psarna** [comment]
@slivne yes, same for https://github.com/scylladb/scylla/issues/4540 and https://github.com/scylladb/scylla/issues/4541

**Comment by avikivity** [comment]
Backported, removing frrom backport candidates.
