### ISSUE TITLE
Encryption at rest

### ISSUE THREAD

**Issue by jstandish** [scylladb/scylla#454]
Currently Cassandra Enterprise offers encryption at rest for PCI compliance. http://www.datastax.com/wp-content/uploads/2013/12/WP-DataStax-Enterprise-PCI-Compliance.pdf

**Comment by avikivity** [comment]
Encryption at rest is a future feature.  You can use Linux disk encyption functionality for now.

**Comment by tzach** [comment]
Relevant Cassandra features:
Add ability to encrypt sstables https://issues.apache.org/jira/browse/CASSANDRA-9633 (3.x)
Add option to encrypt commitlog https://issues.apache.org/jira/browse/CASSANDRA-6018 (3.4)

**Comment by eyalgutkind** [comment]
Will it happen with 1.4? or should it be kicked to 1.5?

cc @glommer @vladzcloudius

**Comment by avikivity** [comment]
Likely to be an enterprise-only feature.

**Comment by denesb** [comment]
EAR is in enterprise 2019.1, can we close this issue, @tzach ?

**Comment by tzach** [comment]
Closing. EaR as a Scylla Enterprise feature.
