### ISSUE TITLE
Schema change concurrent with repair initiation may result in undefined behavior

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4549]
Scylla version (or git commit hash): 3.1+

When repair is initiated, all nodes involved are concurrently obtaining schema versions they will use throughout the repair process. Each node uses its own schema to serialize the mutations it sends and deserialize mutations it receives from other nodes. Deserializing a mutation using a different schema version than was used to serialize it is undefined behavior (among it: crash, data corruption).

**Comment by slivne** [comment]
patch [PATCH scylla v1 0/2] Use same schema version for repair nodes
