### ISSUE TITLE
Update docs/system_keyspace.md with large_rows and large_cells

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4552]
As of 8a3fe3ac9b588ff515be6e4e34c3655ca746cd9b
`docs/system_keyspace.md` is missing documentation for large_{rows,cells}

**Comment by bhalevy** [comment]
Cc @tzach @fgelcer

**Comment by avikivity** [comment]
doc fix, not backporting.

**Comment by fgelcer** [comment]
> Cc @tzach @fgelcer

thanks
