### ISSUE TITLE
nodetool clearsnapshot does not propagate failures to exit code 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4558]
nodetool clearsnapshot does not propegate failures to exit code - and return exit code 0 

as such scripts running clearsnapshot can not detect failures bassed on error code.

**Comment by slivne** [comment]
to reproduce

1. create a docker instrance
2. create ~20-30 tables with some data
3. run  ```nodetool snapshot & nodetool clearsnapshot ; echo $? & ```
4. check the logs for 

```
 storage_io_error (Storage I/O error: 39: filesystem error: remove failed: Directory not empty [...]
```

**Comment by amnonh** [comment]
The full logs are seastar - Exceptional future ignored: storage_io_error (Storage I/O error: 39: filesystem error: remove failed: Directory not empty.

It means that when an error is thrown while trying to delete a directory it gets lost.
looking in to it
