### ISSUE TITLE
large cell detection doesn't work even when creating a singe cell with 10mb blob

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#4564]
when trying to write tests to verify the large cell detection, creating a single cell with a 10mb blob didn't trigger the alert (after running nodetool compact).

the test fails because the alert wasn't generated neither in the respective system table nor on the logs.

**Comment by fgelcer** [comment]
@bhalevy FYI

**Comment by glommer** [comment]
aren't all those detectors compaction based ?

**Comment by fgelcer** [comment]
@glommer , yes, they are.. the test after creating this large cell runs "nodetool compact" cmd

**Comment by tgrabiec** [comment]
@fgelcer Do you also run `nodetool flush` before `nodetool compact`? Maybe the cell is still in the memtable.

**Comment by fgelcer** [comment]
@tgrabiec , yes, the test does it too (just to make it clear, I'm basing this test on a previous test that is testing large row detection, so, i believe all the steps are being executed there, as they are in the new test)

**Comment by bhalevy** [comment]
@fgelcer is the new tests aren't merged yet, please push your development branch to your fork of scylla-dtest so they can be used for reference and for reproducing the issue.

@espindola can you please look at this?

**Comment by fgelcer** [comment]
@bhalevy , created a branch on my fork called large_cells_collections

**Comment by espindola** [comment]
Are you using the MC format?

Cheers,
Rafael

**Comment by espindola** [comment]
fgelcer <notifications@github.com> writes:

> @bhalevy , created a branch on my fork called large_cells_collections

On which repository?

Cheers,
Rafael

**Comment by bhalevy** [comment]
@espindola https://github.com/fgelcer/scylla-dtest

**Comment by espindola** [comment]
What version of scylla are you testing against.

Cheers,
Rafael

**Comment by espindola** [comment]
it works for me with a build of master:

WARN  2019-06-17 10:26:19,764 [shard 19] large_data - Writing large cell test_ks/test: 2 val (1048580 bytes)

keyspace_name | table_name | sstable_name                                                                                     | cell_size | partition_key | clustering_key | column_name | compaction_time
---------------+------------+--------------------------------------------------------------------------------------------------+-----------+---------------+----------------+-------------+---------------------------------
       test_ks |       test | /home/espindola/scylla/home/data/test_ks/test-2cd00030912411e9b338000000000007/mc-51-big-Data.db |   1048580 |             2 |                |         val | 2019-06-17 17:26:19.764000+0000


I created the entry with:

blob='a'*1024*1024
session.execute("INSERT INTO test_ks.test (key, val) values (2,'" + blob + ')")

Cheers,
Rafael

**Comment by fgelcer** [comment]
did you do it using the new test?

and as i can see, you are calling a blob, but at the end, you are adding a string, and the test do insert a blob (using the function textAsBlob()). could it behave differently?
is it possible that even a 'a*1024*1024*10' was converted and became less than 1mb?

**Comment by espindola** [comment]
I have tested by running scylla directly. Please let me know if you
can't reproduce with that.

I don't have time right now to try to run dtest to debug a new test.

Cheers,
Rafael

**Comment by fgelcer** [comment]
@espindola , it doesn't work for me consistently.
LMK when we can make a session together and debug dtest.

**Comment by espindola** [comment]
Does it work if you are *not* using dtest?

You also never replied with sstable format is being used.

Cheers,
Rafael

**Comment by fgelcer** [comment]
i have succeeded to receive the alert, hence closing this ticket.

**Comment by espindola** [comment]
For the record, what was the issue?

Cheers,
Rafael

**Comment by fgelcer** [comment]
I have made many changes to the table creation, data population and the test itself. I have also updated to use a newer version of scylla (I'm not sure what exactly fixed the issue, but with all those changes put together, I was able to see the logs and sstable entries.
