### ISSUE TITLE
Decomission fails after other node terminates unexpectedly

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla#4566]
*Installation details*
Scylla version (or git commit hash): 3.1.0.rc1-0.20190609.224f9cee7
Cluster size: 10
AWS AMI: ami-09fbc240dab3d8276 [ CentOS Linux release 7.6.1810 (Core) | kernel 5.1.8-1.el7.elrepo.x86_64 ]

Steps that caused failure (using SCT parallel nemesis):
1. 2019-06-16 04:55:40.623: TerminateAndReplaceNode Nemesis starts (node 10.0.255.27)
2. 2019-06-16 04:55:52.837: Decommission Nemesis starts (node 10.0.194.252)
3. 2019-06-16 04:58:21.085: New node (10.0.162.55) boots (and unable to join cluster)
Stuck on "storage_service - Checking bootstrapping/leaving nodes: tokens 0, leaving 1, sleep 1 second and check again"
4. 2019-06-16 05:10:28,595 Nodetool command 'nodetool -u cassandra -pw cassandra --host localhost decommission' failed on node Node longevity-tls-1tb-7d-abykov-paralle-db-node-48c74857-6 [34.245.144.62 | 10.0.194.252] (seed: False): Command exited with status 1.
=== stdout ===
nodetool: Scylla API server HTTP POST to URL '/storage_service/decommission' failed: Stream failed
See 'nodetool help' or 'nodetool help <command>'.

DB Logs
- [10-0-194-252.gz](https://github.com/scylladb/scylla/files/3297197/10-0-194-252.gz)
- [10-0-162-55.gz](https://github.com/scylladb/scylla/files/3297280/10-0-162-55.gz)

Nodetool status:
```
Datacenter: eu-west
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  10.0.249.82   591.1 GB   256          ?       96910c57-a594-489b-87d8-564661cfcbf6  1a
UN  10.0.64.99    582.02 GB  256          ?       cbd56f50-d063-40b2-9719-3571b323e2d3  1a
UN  10.0.33.147   572.58 GB  256          ?       2bcb99ff-9754-40e1-a3f6-0d6404720732  1a
UN  10.0.169.154  586.2 GB   256          ?       386822a7-1436-4bc5-ad25-7370dc4a31a5  1a
UN  10.0.115.11   564.2 GB   256          ?       e080ad82-ddcc-4ddd-9e44-ad467129bf05  1a
DN  10.0.255.27   569.75 GB  256          ?       96646692-66c4-4b69-85c3-d458f9ddeef2  1a
UL  10.0.194.252  566.91 GB  256          ?       0e09233e-2552-4dce-b6d8-14d90e32a123  1a
UN  10.0.84.238   590.33 GB  256          ?       8454fb91-a5ca-41d2-a9b5-e0a312c31dbb  1a
UN  10.0.61.111   607.9 GB   256          ?       fd9b99ec-03c5-4e52-b02d-03a1ba42ab8c  1a
UN  10.0.76.175   571.11 GB  256          ?       d4582481-d08d-48e2-884f-8ab774884d6c  1a
```
CC: @slivne @roydahan

**Comment by slivne** [comment]
decomission should fail - since the other node was lost so it can not complete (data can't be streamed to the node that went down)
the node that attempted to decomission is supposed to move back to normal state 

if this is happening then everything is ok in my view

**Comment by slivne** [comment]
@asias - can you make any sense out of this - decomission is supposed to fail if another node is down in the cluster - why does it take 15 minute to fail ?

**Comment by asias** [comment]
@bentsi It is very hard to make a node that failed to run decommission back to the normal status. We need to restart the node to make it UN again.

**Comment by asias** [comment]
> @asias - can you make any sense out of this - decomission is supposed to fail if another node is down in the cluster - why does it take 15 minute to fail ?

This is due to the retry.  (60+90+135+202+303)/60 = 13min


```
$ cat 10-0-194-252.log|grep "retry"
Jun 16 04:57:06 ip-10-0-194-252.eu-west-1.compute.internal scylla.bin[7101]:  [shard 0] range_streamer - Unbootstrap failed to stream. Will retry in 60 seconds ...
Jun 16 04:58:09 ip-10-0-194-252.eu-west-1.compute.internal scylla.bin[7101]:  [shard 0] range_streamer - Unbootstrap failed to stream. Will retry in 90 seconds ...
Jun 16 04:59:42 ip-10-0-194-252.eu-west-1.compute.internal scylla.bin[7101]:  [shard 0] range_streamer - Unbootstrap failed to stream. Will retry in 135 seconds ...
Jun 16 05:02:00 ip-10-0-194-252.eu-west-1.compute.internal scylla.bin[7101]:  [shard 0] range_streamer - Unbootstrap failed to stream. Will retry in 202 seconds ...
Jun 16 05:05:24 ip-10-0-194-252.eu-west-1.compute.internal scylla.bin[7101]:  [shard 0] range_streamer - Unbootstrap failed to stream. Will retry in 303 seconds ...
```

**Comment by bentsi** [comment]
Thanks @asias 
Is this documented somewhere? Our clients should be aware of this @glommer  or this should be somehow fixed. 
@slivne please advise: should we make this as a procedure and document it? or we will fix this?

**Comment by slivne** [comment]
@asias what does cassandra do ?  do they have a solution to move a node back from UL to UN / is the restart documented in cassandra (if so can you reference that).

**Comment by asias** [comment]
> @asias what does cassandra do ? do they have a solution to move a node back from UL to UN / is the restart documented in cassandra (if so can you reference that).

No. They do not document the restart.  They also can not move from the failed decommission operation to UN.

**Comment by slivne** [comment]
closing this issue create a doc issue
