### ISSUE TITLE
Write timeouts @ CL=ONE

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#457]
With CL=ONE, writes return immediately after appending to the local commitlog, and issue RF-1 RPCs to replicas.  There is nothing that limits the amount of outstanding RPCs, so they grow and grow, and eventually we experience timeouts.

@tgrabiec @gleb-cloudius

**Comment by slivne** [comment]
@gleb-cloudius I think you have added a mechanism to back pressure toward the client and limit the memory - is there anything left here ?

**Comment by gleb-cloudius** [comment]
On Sun, Feb 14, 2016 at 02:08:38PM -0800, slivne wrote:
> @gleb-cloudius I think you have added a mechanism to back pressure toward the client and limit the memory - is there anything left here ?
> 
No. We can improve the mechanism in the future, but this is unrelated to
the issue.

--
			Gleb.
