### ISSUE TITLE
Fails scylla_ntp_setup on RHEL8

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#4571]
RHEL8 has dropped ntpd/ntpdate and switched to chrony, need to support it on scylla_ntp_setup:
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/using-chrony-to-configure-ntp

**Comment by syuu1228** [comment]
Note that all of our supported distributions (CentOS7 / Ubuntu 14,16,18 / Debian 8,9) has chrony package, we may able to just switch to it, instead of support both ntpd and chrony.

**Comment by tzach** [comment]
Dropping the NTP installation in scylla_setup will be a nice result, and a step toward easier offline install.

**Comment by syuu1228** [comment]
@tzach Doesn't it important to sync system clock using NTP prior to start using Scylla? For offline install we can just skip NTP setup. If it's not needed I'll just drop it though

**Comment by tzach** [comment]
Sync the clock is important.
I was under the impression chrony replaced ntp, and we do not need to install it.

**Comment by slivne** [comment]
@syuu1228 - we do not support ubuntu 14, is chrony installed by default ?

**Comment by tzach** [comment]
@syuu1228 any update on this issue?

**Comment by avikivity** [comment]
Will not backport since it's a new OS for us.
