### ISSUE TITLE
Repair may not repair writes touching new columns if new schema is not propagated to all nodes

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4575]
Scylla version (or git commit hash): 3.1+

Repair schema is chosen on the repair master node and will be used throughout the repair on all involved nodes to read and digest mutations. If the master node doesn't have the latest schema, it can happen that repair readers on other nodes will not see, and thus repair, writes which make use of the new schema (e.g. write to new columns). If such writes were ACKed before the repair was started, repair is expected to repair them.

One of the consequences of not repairing those writes may be data resurrection, in case those writes are tombstones, or an increased risk of data loss.

To solve this, repair should force synchronous schema sync across all involved nodes when starting.

**Comment by asias** [comment]
Patch is on list: [PATCH scylla v2 0/2] Sync schema before repair

**Comment by tgrabiec** [comment]
Backported to 3.1
