### ISSUE TITLE
Log encryption options that were used during `CREATE TABLE`

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#4579]
*Installation details*
HEAD: 91b71a0b1a5a18b520327e87df52b88b7a715e09

*Description*
Log used encryption options when table is created.
This is important especially when default values are used.

**Comment by vladzcloudius** [comment]
@elcallio FYI

**Comment by tzach** [comment]
Closing, Encryption is not a Scylla Open Source feature.
