### ISSUE TITLE
Avoid quadratic complexity in to_repair_rows_on_wire in repair

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#4580]
*Installation details*
Scylla version (or git commit hash): 3.1+

The repair_rows in row_list are sorted. It is only possible for the current repair_row to share the same partition key with the last repair_row inserted into repair_row_on_wire.  So, no need to search from the beginning of the repair_rows_on_wire which causes quadratic complexity.

**Comment by avikivity** [comment]
@tgrabiec @asias I think we should backport this, it can cause a performance regression if we have to search many very small rows in the buffer.

**Comment by asias** [comment]
Backport +1

**Comment by tgrabiec** [comment]
Backported to 3.1

**Comment by avikivity** [comment]
@tgrabiec if you backport, remove the "Backport candidate" label so the issue drops off the queue.
