### ISSUE TITLE
Log message when services are stopped

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4586]
As a follow up to #4583 @nyh suggested:
> I wonder if you shouldn't add after every "stopping ..." message and the actual stop code, a "stopped ..." message.
> The problem is that when users see "stopping prometheus API server" and then other stuff, they have no idea if the stopping was actually successful or it hung. If "stopping prometheus API server" is the last thing in the log than it's obvious it hung, but in some cases you get in the log various other things which are happening concurrently.

> You can have a generic stop(name, func) function that prints "stopping name", runs func() and then a finally() to print "stopped name", to make this all automatic with minimum boilerplate code.

**Comment by bhalevy** [comment]
Can be addressed as part of #4384

**Comment by avikivity** [comment]
Enahancement; not backporting.
