### ISSUE TITLE
Job for scylla-server.service failed.

### ISSUE THREAD

**Issue by aby005** [scylladb/scylla#4587]
Abhishek Kumar [3:22 PM]
Hi..! my scylla server is not starting on running 'sudo systemctl start scylla-server'. It is showing 'Job for scylla-server.service failed'. I am sharing the screenshots below. I have tried the commands that it suggested : "journalctl -xe" and ''systemctl status scylla-server.service", which is showing failed to start.

`scylla@scyllaNode:~$ sudo systemctl start scylla-server
Job for scylla-server.service failed because a fatal signal was delivered causing the control process to dump core.
See "systemctl status scylla-server.service" and "journalctl -xe" for details.
`

On systemctl status scylla-server.service, I get this.

`scylla@scyllaNode:~$ systemctl status scylla-server.service
● scylla-server.service - Scylla Server
   Loaded: loaded (/lib/systemd/system/scylla-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: core-dump) since Thu 2019-06-20 09:35:31 UTC; 5min ago
  Process: 16309 ExecStopPost=/usr/lib/scylla/scylla_stop (code=exited, status=0/SUCCESS)
  Process: 16294 ExecStart=/usr/bin/scylla $SCYLLA_ARGS $SEASTAR_IO $DEV_MODE $CPUSET (code=dumped, signal=ABRT)
  Process: 16283 ExecStartPre=/usr/lib/scylla/scylla_prepare (code=exited, status=0/SUCCESS)
Main PID: 16294 (code=dumped, signal=ABRT)
   Status: "creating snitch"

Jun 20 09:35:31 scyllaNode systemd[1]: Failed to start Scylla Server.
Jun 20 09:35:31 scyllaNode systemd[1]: scylla-server.service: Service hold-off time over, scheduling restart.
Jun 20 09:35:31 scyllaNode systemd[1]: scylla-server.service: Scheduled restart job, restart counter is at 5.
Jun 20 09:35:31 scyllaNode systemd[1]: Stopped Scylla Server.
Jun 20 09:35:31 scyllaNode systemd[1]: scylla-server.service: Start request repeated too quickly.
Jun 20 09:35:31 scyllaNode systemd[1]: scylla-server.service: Failed with result 'core-dump'.
Jun 20 09:35:31 scyllaNode systemd[1]: Failed to start Scylla Server.
`

**Comment by tzach** [comment]
What version of Scylla and what OS are you using?
Is this a post installation/upgrade issue? 
Can you please share more of the log with `journalctl -xe" | grep scylla"

**Comment by slivne** [comment]
Closing this issue as there is no additional information - @aby005 we can reopen if you share info

**Comment by dreamerHarshit** [comment]
Facing the same issue with Scylla 4.3 on RHEL 8.

**Comment by nukemberg** [comment]
@dreamerHarshit can you attach the scylla logs? e.g. `journalctl --user _SYSTEMD_UNIT=scylla-server.unit` output?

**Comment by dreamerHarshit** [comment]
i tried this command journalctl --user _SYSTEMD_UNIT=scylla-server.unit
but no logs are there.

**Comment by penberg** [comment]
@dreamerHarshit If it's the exact same error, it suggests that `scylla` crashed. Does `coredumpctl` show a core dump? If it does, can you please upload it as per instructions here: https://docs.scylladb.com/troubleshooting/report_scylla_problem/#core-dump
