### ISSUE TITLE
nodetool_refresh_with_wrong_upload_modes_test: scylla Failed to get test_symlink type

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4606]
Starting version b1e78313fe7ed58496232c63f524e0fd331d7277
Seen in [dtest-release/158/testReport/nodetool_additional_test/TestNodetool/nodetool_refresh_with_wrong_upload_modes_test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/158/testReport/nodetool_additional_test/TestNodetool/nodetool_refresh_with_wrong_upload_modes_test/):
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 1263, in nodetool_refresh_with_wrong_upload_modes_test
    debug_message='with symlink')
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/nodetool_additional_test.py", line 1213, in _nodetool_refresh_expect_fail
    assert re.search(expected_error, str(error)), "/{}/ not found in '{}'".format(expected_error, error)
AssertionError: /Must be either a regular file or a directory/ not found in 'Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/resources/cassandra/bin/nodetool -h localhost -p 7175 refresh -- keyspace1 standard1' failed; exit status: 1; stdout: nodetool: Scylla API server HTTP POST to URL '/storage_service/sstables/keyspace1' failed: Failed to load new sstables: std::runtime_error (Failed to get /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-eAHCND/test/node1/data/keyspace1/standard1-8a0b563096d511e99cad000000000001/upload/test_symlink type.)
See 'nodetool help' or 'nodetool help <command>'.
```

So instead of detecting a symbolic link when listing the upload directory and throwing `"Must be either a regular file or a directory"` from `distributed_loader::verify_owner_and_mode`, it looks like `lister::guarantee_type` throws `"Failed to get {} type."` when `reactor::file_type` return empty `optional<directory_entry_type>()`

**Comment by slivne** [comment]
@bhalevy is this fixed ?

**Comment by slivne** [comment]
@bhalevy is this a regression ?

**Comment by bhalevy** [comment]
> @bhalevy is this a regression ?

@slivne no, the issue was always there.  It seems to depend on the file system holding broken symlink, where some file systems return the symlink file type in the directory entry when listing the directory and some don't.  In any case, the user-visible behavior is quite similar; the difference is only at the error message the user will see.

**Comment by bhalevy** [comment]
@avikivity I see this failing the same way also in 3.1
Can we backport a0499bbd31ddcef0ac3fa8e3c4e5b8f2fc2342bd to 3.1?
scylladb/seastar@45ac30887e160e9e730ca2da67b16a0362782c1e is a prerequisite.

**Comment by bhalevy** [comment]
@avikivity ping. I see that scylladb/seastar@45ac30887e160e9e730ca2da67b16a0362782c1e is now included in branch-3.1 seastar submodule.  Now a0499bbd31ddcef0ac3fa8e3c4e5b8f2fc2342bd can be backported to branch-3.1

**Comment by avikivity** [comment]
@bhalevy why does this need a backport? Looks like a relatively obscure bug (someone tries to import sstables that use symbolic links), no?

**Comment by bhalevy** [comment]
> @bhalevy why does this need a backport? Looks like a relatively obscure bug (someone tries to import sstables that use symbolic links), no?

@avikivity the fix is indeed relevant to this remote scenario.
The narrow issue is tripped when the user tries to import sstables with **broken** symlinks.
If the symlinks point to actual files I think loading would even work, but this is completely untested.

**Comment by avikivity** [comment]
Aged out.
