### ISSUE TITLE
Add ability to control collectd client through RESTful API

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#461]
It would be useful to be able to enable/disable metric sending at run time, without having to restart Scylla. 

It would be nice to be able to disable/enable metrics based on regex. Some metrics generate a lot of data (eg. smp*), but are not always of interest.

**Comment by tzach** [comment]
@amnonh any update on this feature? is it in 1.2?

**Comment by amnonh** [comment]
It was decided not to merge it to 1.2
Waiting for the seastar series to be merged

**Comment by tzach** [comment]
@amnonh any updates?

**Comment by amnonh** [comment]
It's merged

**Comment by tzach** [comment]
> It's merged

Great. What is the commit hash?

**Comment by slivne** [comment]
commit 401c333b118059c156700caf7dc8ae903532fee3
Author: Amnon Heiman <amnon@scylladb.com>
Date:   Sun May 29 15:39:20 2016 +0300

    scollectd: Support filtering specific collectd metrics
    
    This patch adds the ability to turn on and off specific collectd
    metrics.
    
    It has the following changes:
    add an enable flag to the collectd value_list it then uses that flag
    when sending notification to decide if a specific meter should be sent
    or not.
    
    To be able to enable/disable the flag from the API two helper function
    where added:
    
    One that takes a bool and type_instance id and either enable or disable
    that metrics.
    
    and one that takes a type_instance_id and return if it's enable or
    disable.
    
    Signed-off-by: Amnon Heiman <amnon@scylladb.com>
    Message-Id: <1464525560-28242-2-git-send-email-amnon@scylladb.com>
