### ISSUE TITLE
On master, trying Scylla package upgrade twice or more causes error

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#4611]
Since we moving old /usr/lib/scylla to /usr/lib/scylla.old specifically, if user tries to upgrade Scylla to master twice or more, scriptlet will fails because /usr/lib/scylla.old is already exists.
```
if [ -d /usr/lib/scylla ]; then
    mv /usr/lib/scylla /usr/lib/scylla.old
fi
ln -sfT /opt/scylladb/scripts /usr/lib/scylla
```
https://github.com/scylladb/scylla/blob/master/dist/redhat/scylla.spec.mustache#L81

We should randomize directory name.

Note that why we moving old /usr/lib/scylla directory not just let package manager to remove old files is, because both .rpm/.deb package manager could not remove entire /usr/lib/scylla directory on package upgrade, if we tries to install /usr/lib/scylla symlink as a part of master package install will fails.
So I decided to move old directory then create symlink in %posttrans scriptlet, not part of %files.

**Comment by syuu1228** [comment]
Patch posted to ML: "[PATCH scylla 2/2] dist: randomize scylla.old directory name"

**Comment by slivne** [comment]
is this relevant for 3.1 as well ?

**Comment by avikivity** [comment]
Already backported.
