### ISSUE TITLE
TWCS: flush memtable on window boundaries

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#4617]
Currently we have no mechanism (that I know of) that would initiate a memtable flush on window boundaries, so we depend on window size and workload combination to produce sstables containing a single time-window.

There are two solutions:
1) Have a timer that initiates a flush on window boundaries.
2) Wire the flush writer through the timestamp based splitter.

I think (2) is much better as it doesn't interfere with our memtable flush policies.

See: #2687

**Comment by raphaelsc** [comment]
This will not only happen TWCS, but any other strategy which desires to segregate data on flush. I am working on a new compaction strategy for S3 work which segregates data by object identifier on flush.

**Comment by raphaelsc** [comment]
EDIT: s/happen/benefit

**Comment by raphaelsc** [comment]
i'll work on making it in good shape for upstream, but i already have working version, from my hackathon work: https://github.com/sitano/s3-scylla/commit/d05f82e8613b58a06076e657bd74093b8cc05176

**Comment by avikivity** [comment]
Not a regression, so not backporting.
