### ISSUE TITLE
TWCS: reshard sstables window-by-window

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#4618]
Resharding can mess up the windows by merging windows together. We should reshard a single window at a time. Maybe this is already the case, @raphaelsc can you please clarify?

**Comment by denesb** [comment]
See: #2687

**Comment by raphaelsc** [comment]
@denesb for TWCS, each sstable (which belongs to more than one shard) is individually resharded. Given that each time window is represented by only 1 sstable in each shard, and reshard may produce N (where N <= smp count) output sstables for each input sstable (each output sst belonging to a different shard), it can happen that when resharding completes, each shard will have N sstables per time window, which will later be all merged into one by regular compaction. So I don't think resharding will mess with the windowing.

**Comment by denesb** [comment]
Right, I think we can close this then.
