### ISSUE TITLE
AWS AMI - clock source

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#462]
We should configure Xen to use the tsc clocksource to reduce the clock
reads. Probably it's good case across the board.

**Comment by avikivity** [comment]
Depends, is the tsc clocksource stable enough?

**Comment by slivne** [comment]
both you and dor mentioned this

" We may want to do this on AWS AMIs, except that if we get time wrong,
users get wrong results, so we need to be sure time is still right."

So what do you mean by "make sure time is still right" ?

**Comment by avikivity** [comment]
There are reasons that Xen uses xenclock and not tsc.

Those reasons are:
(1) the hypervisor may change the tsc frequency
(2) the hypervisor may move the vcpu from one cpu to another
(3) the vm may be live migrated to a host with a different tsc
(4) the tsc may be unsynchronized in the first place

1 is impossible on modern cpus
2 doesn't happen on AWS (except for burstable instances)
3 doesn't happen on AWS
4 is unlikely

so it's probably safe, but not certain.

**Comment by dorlaor** [comment]
CrowdStrike use the tsc and so does netflix, I think it is safe.
Let's do it in the Scylla start script, verify that the flags are good and
log it

**Comment by syuu1228** [comment]
Is this what we want here?
```
[syuu@devil scylla]$ git diff
diff --git a/dist/ami/files/scylla-setup.sh b/dist/ami/files/scylla-setup.sh
index 70ae345..bb4f116 100755
--- a/dist/ami/files/scylla-setup.sh
+++ b/dist/ami/files/scylla-setup.sh
@@ -3,6 +3,8 @@
 RAIDCNT=`grep xvdb /proc/mdstat | wc -l`
 RAIDDEV=`grep xvdb /proc/mdstat | awk '{print $1}'`
 
+echo tsc > /sys/devices/system/clocksource/clocksource0/current_clocksource
+
 if [ $RAIDCNT -ge 1 ]; then
     echo "RAID already constructed."
     mount -o noatime,discard /dev/$RAIDDEV /var/lib/scylla
```

**Comment by avikivity** [comment]
I think the kernel will (incorrectly) detect skew and switch it back to 
xen, so maybe need to disable the xen clock.

**Comment by syuu1228** [comment]
What's the way to disable it?

There's "unbind_clocksource" on sysfs, but it seems xen clocksource impossible to unbind. (other items can, but xen > unbind_clocksource causes "Device or resource busy")

And looks like there's "notsc" like boot parameters for xen clocksource.

**Comment by avikivity** [comment]
There is `clocksource=tsc tsc=reliable` kernel command line options to force the tsc.
