### ISSUE TITLE
Need an API to return all pending taks by keyspace/table

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#4634]
See #4228

**Comment by amnonh** [comment]
Should be closed

**Comment by slivne** [comment]
fixed by 1c6dec139f7dc424b0aa0693796a0073b6ebcfde

**Comment by tzach** [comment]
@amnonh what nodetool command use this API?

**Comment by amnonh** [comment]
nodetool compactionstats
Also see #4228

**Comment by tzach** [comment]
OK, so its not a new nodetool command rather a bug fix

**Comment by amnonh** [comment]
Yes
