### ISSUE TITLE
scylla_setup is throwing errors while run on i3en instances

### ISSUE THREAD

**Issue by mailmahee** [scylladb/scylla#4638]
*Installation details*
Scylla version: 3.0.8
Cluster size: 2 i3en.6xls
OS (RHEL/CentOS/Ubuntu/AWS AMI): centos 7
Platform (physical/VM/cloud instance type/docker): AWS

```
[centos@ip-10-10-252-154 ~]$ sudo scylla_setup
Skip any of the following steps by answering 'no'
Do you want to run Amazon EC2 configuration check?
Yes - runs a script to verify that this instance is optimized for running Scylla. No - skips the configuration check.
[YES/no]YES
i3en doesn't support enahanced networking!
To enable enhanced networking, please use the instance type which supports it.
More documentation available at:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html#enabling_enhanced_networking
Traceback (most recent call last):
  File "/sbin/scylla_setup", line 204, in <module>
    run('/usr/lib/scylla/scylla_ec2_check --nic {}'.format(nic))
  File "/usr/lib/scylla/scylla_util.py", line 270, in run
    return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr)
  File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/lib/scylla/scylla_ec2_check', '--nic', 'eth0']' returned non-zero exit status 1.
```

```
[centos@ip-10-10-252-154 ~]$ ethtool -i eth0
driver: ena
version: 2.0.3K
firmware-version: 
expansion-rom-version: 
bus-info: 0000:00:05.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
```

ENA support is enabled for these instances already

```14:36 $ aws ec2 describe-instances --instance-ids i-09582189ac3739580 --query "Reservations[].Instances[].EnaSupport"
[
    true
]
✔ ~
14:36 $ aws ec2 describe-instances --instance-ids i-070a0945a39af8eb8 --query "Reservations[].Instances[].EnaSupport"
[
    true
]```

**Comment by mailmahee** [comment]
looks like the script is looking for `en` instead of `ena` here: https://github.com/scylladb/scylla/blob/scylla-3.0.8/dist/common/scripts/scylla_ec2_check#L45

**Comment by slivne** [comment]
3.0.8 doesn't support i3.en out of the box - this was added only to the
upcoming 3.1 release and to the 2019.1.X releases

**Comment by glommer** [comment]
@slivne if ena really is the issue, how is this specific to i3en? i3.metal uses ENA as well, as does any i3.

This is a new bug, if it is really is related to that.

**Comment by glommer** [comment]
However @mailmahee now that I read the code Shlomi is correct.

The script is not looking for `en`. That's just the name of the variable, it could be anything, including `mahee`

That variable gets the result of a function, that in turn scans for a list of supported instances:

```
    def get_en_interface_type(self):
        instance_class = self.instance_class()
        instance_size = self.instance_size()
        if instance_class in ['c3', 'c4', 'd2', 'i2', 'r3']:
            return 'ixgbevf'
        if instance_class in ['c5', 'c5d', 'f1', 'g3', 'h1', 'i3', 'i3en', 'm5', 'm5d', 'p2', 'p3', 'r4', 'x1']:
            return 'ena'
        if instance_class == 'm4':
            if instance_size == '16xlarge':
                return 'ena'
            else:
                return 'ixgbevf'
        return None
```

That has to list i3en explicitly. Please bypass that by not calling the `ec2_check` stage for enhanced networking in the setup phase.

**Comment by mailmahee** [comment]
Thanks @glommer @slivne - we resolved the issue with the customer.

**Comment by jaihind213** [comment]
asd

**Comment by jaihind213** [comment]
hi 

i tried today with the scylla 3.10 ami on i3.en.6x and error pops up.

steps to reproduce
1) launch ami (https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#LaunchInstanceWizard:ami=ami-0b88175d56d413224) 
2) i3.en.6x
3) once instance is up , cd /usr/lib/scylla & run scylla_setup.

attaching screenshot.
<img width="891" alt="Screenshot 2019-08-26 at 13 49 21" src="https://user-images.githubusercontent.com/1289751/63668061-86e5a000-c808-11e9-8ff1-1a29fc568e19.png">
