### ISSUE TITLE
Fix possible stalls in row level repair

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#4642]
After switching to rpc stream interface, we increased the row buffer
size. Code works on the buffer that do not yield can stall the reactor.
We should futurize or run the code in thread and yield.

**Comment by avikivity** [comment]
In 3.2. Will see how it fares in production first.

**Comment by avikivity** [comment]
Will wait one more week with 3.2.

**Comment by avikivity** [comment]
Aged out.
