### ISSUE TITLE
lsa: invalid memory accesses caused by `align_up_for_asan()`

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#4653]
Since e071445373f3587d4f4656eb7d1fa66985b4616d (Merge "More precise poisoning in logalloc" from Rafael) LSA, in debug mode, requires objects to be aligned at 8-byte boundary so that it can maximise the coverage that AddressSanitizer provides. LSA, being an allocator is doing some pointer arithmetic, and where there's pointer arithmetic there are bugs.

In particular, `align_up_for_asan()` allowed access past the end of a range in loops like this one:

```c++
auto pos = seg->at<const char>(0);
while (pos < seg->at<const char>(segment::size)) {
    align_up_for_asan(pos);
    /* ... something that dereferences `pos` ... */
}
```

Only debug build is susceptible.

**Comment by bhalevy** [comment]
Cc @espindola

**Comment by espindola** [comment]
In general yes, the alignment could make pos == segment::size.

But in this code, close_active should always creates a last element that ends exactly at the end of the segment, no?

What is the best way of reproducing the issue, apply  #4643 again?

**Comment by pdziepak** [comment]
If the last "real" object ends somewhere in the last 8 bytes of a segment then `close_active()` will not create a dummy object that covers the rest of the segment.

**Comment by avikivity** [comment]
Issue not present in any branch.
