### ISSUE TITLE
Error when build_rpm.sh on centos with linux kernal version : 2.6.x

### ISSUE THREAD

**Issue by cloudtrends** [scylladb/scylla#466]
hi , all

Following the readme file , I run build rpm package command:

$ ./dist/redhat/build_rpm.sh

error: cannot open build/srpms/binutils-2.25-5.fc22.src.rpm: No such file or directory

the linux version is : 

Linux n225 2.6.32-573.el6.x86_64 #1 SMP Thu Jul 23 15:44:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

When re-install binutils

$ sudo yum install binutils
Package binutils-2.20.51.0.2-5.43.el6.x86_64 already installed and latest version

Do I have to force install binutils-2.25.x ?

thanks.

**Comment by dorlaor** [comment]
On Mon, Oct 19, 2015 at 3:44 AM, ChunFeng <notifications@github.com> wrote:

> hi , all
>
> Following the readme file , I run build rpm package command:
>
> $ ./dist/redhat/build_rpm.sh
>
> error: cannot open build/srpms/binutils-2.25-5.fc22.src.rpm: No such file
> or directory
>
> the linux version is :
>
> Linux n225 2.6.32-573.el6.x86_64 #1
> <https://github.com/scylladb/scylla/issues/1> SMP Thu Jul 23 15:44:03 UTC
> 2015 x86_64 x86_64 x86_64 GNU/Linux
>
> When re-install binutils
>
> $ sudo yum install binutils
> Package binutils-2.20.51.0.2-5.43.el6.x86_64 already installed and latest
> version
>
> Do I have to force install binutils-2.25.x ?
>

So far we support only Centos/RHEL 7.x
A possible path to run it is to install it in chroot on rhel6 but we
haven't tested it.

**Comment by avikivity** [comment]
Stale bug, closing.
