### ISSUE TITLE
sporadic failures in TestMigrationUpgradeSSTables dtests

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4660]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): c987397e529a6f3838da37199ca277a48cda4634
Cluster size: 1

Several similar dtest cases expect only sstables version mc after `nodetool upgradesstable` and they fail when seeing also sstables from an older version that were uploaded to the node.

For example:
[dtest-release/166/testReport/junit/migration_test/TestMigrationUpgradeSSTables_with_2_2_x/migrate_sstable_with_collection_map_test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/166/testReport/junit/migration_test/TestMigrationUpgradeSSTables_with_2_2_x/migrate_sstable_with_collection_map_test/)
[dtest-release/167/testReport/junit/migration_test/TestMigrationUpgradeSSTables_with_2_2_x/migrate_sstable_with_compact_storage_and_composite_key_test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/167/testReport/junit/migration_test/TestMigrationUpgradeSSTables_with_2_2_x/migrate_sstable_with_compact_storage_and_composite_key_test/)
[dtest-release/169/testReport/junit/migration_test/TestMigrationUpgradeSSTables_with_2_2_x/migrate_sstable_with_static_cell_test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/169/testReport/junit/migration_test/TestMigrationUpgradeSSTables_with_2_2_x/migrate_sstable_with_static_cell_test/)
[dtest-release/170/testReport/junit/migration_test/TestMigrationUpgradeSSTables_with_2_1_x/migrate_sstable_with_lz4_compression_test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/170/testReport/junit/migration_test/TestMigrationUpgradeSSTables_with_2_1_x/migrate_sstable_with_lz4_compression_test/)

The test looks correct in the sense that it checks the data directory right after `nodetool upgradesstables` completes as the latter should be synchronous and return after compaction upgraded the loaded sstables and deleted the old ones.

**Comment by slivne** [comment]
@bhalevy what about sstables that are currently held for reading - they may remain ?

e.g. are the tests run on an idle system in which no active reads are happening - if so we need to find why we have old sstables remaining

**Comment by bhalevy** [comment]
> @bhalevy what about sstables that are currently held for reading - they may remain ?
> 
> e.g. are the tests run on an idle system in which no active reads are happening - if so we need to find why we have old sstables remaining

@slivne there shouldn't be any read.  The sstables are loaded by copying the sstable files (la, ka, or mc) and running nodetool refresh.  Then they are upgraded using nodetool upgradesstables, and then the directory is scanned (and la/ka files are found in addition to mc).  I'm not able to reproduce this locally so I'll add some debug printouts to the test to help understand what is left.

**Comment by bhalevy** [comment]
@raphaelsc is it possible that compaction will leave old sstables around after `nodetool upgradesstables` returns?

**Comment by bhalevy** [comment]
I think this could be a result of the background deletes seen in #4622 and should be fixed with PR #4691

**Comment by slivne** [comment]
pull request waiting to be merged https://github.com/scylladb/scylla/pull/4691

**Comment by slivne** [comment]
@bhalevy please check if the patch is in master and backported ?

**Comment by bhalevy** [comment]
Fixed in master with 6dad9baa1c0e4634f69d698612dd3d5dd7133f1d
wasn't backported yet
