### ISSUE TITLE
Cleanup potentially mess up the sstable run structure

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#4663]
*Installation details*
Scylla version (or git commit hash): fca1ae69ff63f30
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

After cleanup runs, sstable run structure is messed up because each cleaned sstable ends up receiving a sstable run identifier, meaning the table ends up with a new sstable run for each of them.

**Comment by avikivity** [comment]
No vulerable releases.
