### ISSUE TITLE
Need drop scylla-3rdparty repo from Scylla-3.1 .repo/.list

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#4666]
Since we dropped ALL dependencies for 3rdparty repo when we switched to relocatable package, Scylla-3.1 (and future releases of Scylla) should drop 3rdparty repo from its .repo / .list.
Also need to remove it from Install Document.

For users who upgraded from previous versions, it's better to suggest in our Upgrade Document to drop 3rdparty packages when package upgrade since we don't need it anymore.
But Scylla-3.1 designed to co-exist with 3rdparty packages, it just works fine with these packages.

**Comment by slivne** [comment]
Every scylla release has a since .repo/.list file that includes all the repos that are needed.

As such a user upgrading to the new release will get a repo file that does not reference the scylla-3rdpart if this is correct.

Do we still host gdb and other tools on the 3rdparty that may be needed by the user if so we can't drop it

**Comment by slivne** [comment]
@syuu1228 / @avikivity  please comment

**Comment by slivne** [comment]
@syuu1228 ping
@avikivity ping

**Comment by syuu1228** [comment]
@slivne @avikivity I think we just need scylla-gdb fro scylla-3rdparty repo, correct?
I think all other packages are build time dependencies, now we have "dbuild" for them.
I think we should provide scylla-gdb in same way as scylla-python3, make it relocatable package if it possible.
I'm already trying to make gdb relocatable package, but I haven't able to make it work yet. It seems there are external dependencies.

**Comment by slivne** [comment]
Leaving this open for 3.1.X solution (X > 0) - we will drop from the 3.1 repo files scylla-3rdparty @hagitsegev / @yaronkaikov / @penberg - lets update the repo files accordingly.

**Comment by slivne** [comment]
@hagitsegev / @penberg / @yaronkaikov  any update

**Comment by avikivity** [comment]
scylla-gdb in scylla-3rdparty is outdated, so we can drop scylla-3rdparty completely. Core files should be debugged in a dbuild container. If someone needs to debug on a live host, they can copy the gdb binary from the dbuild toolchain.

**Comment by glommer** [comment]
On Mon, Aug 19, 2019 at 2:45 AM Avi Kivity <notifications@github.com> wrote:

> scylla-gdb in scylla-3rdparty is outdated, so we can drop scylla-3rdparty
> completely. Core files should be debugged in a dbuild container. If someone
> needs to debug on a live host, they can copy the gdb binary from the dbuild
> toolchain.
>

will we have all the libraries available ?

If we have to copy files to the host, isn't a package a good way to do so ?
We very often do debugging in live hosts, so I wouldn't like that to become
overly complex.

**Comment by hagitsegev** [comment]
Maybe we can run another rc to verify things?
We also have some testing repo, in which we can (at least partially) debug.

בתאריך יום ב׳, 19 באוג׳ 2019, 15:29, מאת Glauber Costa ‏<
notifications@github.com>:

**Comment by avikivity** [comment]
We might build a package or not, but we're dropping scylla-3rdparty for sure.

**Comment by slivne** [comment]
@penberg can we close this did we update the repo files

**Comment by hagitsegev** [comment]
I ran "update metadata" during rc5, and the repo's look OK to me. I think we can close. @penberg do you want to verify?

**Comment by penberg** [comment]
The 3.1 repository looks OK to me:

http://downloads.scylladb.com.s3.amazonaws.com/rpm/centos/scylla-3.1.repo

```[scylla-3.1]
name=Scylla for Centos $releasever - $basearch
baseurl=https://s3.amazonaws.com/downloads.scylladb.com/downloads/scylla/rpm/centos/scylladb-3.1/$releasever/$basearch/
enabled=1
gpgcheck=0

[scylla-generic-3.1]
name=Scylla for centos $releasever
baseurl=https://s3.amazonaws.com/downloads.scylladb.com/downloads/scylla/rpm/centos/scylladb-3.1/$releasever/noarch/
enabled=1
gpgcheck=0```

@slivne I think we can close this.

**Comment by hagitsegev** [comment]
Please note that I ran this process from my branch, which is a merge of the scylla-pkg repo from master to 3.1 (before reloc big change).
After rc5 I'll run all builds from this branch, and will merge when all potential issues will be fixed. I didn't cherry-pick changes, as there are many, and I want them all.
