### ISSUE TITLE
Installing on RHEL7.1 (AWS)

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#467]
Installing CentOS binary packages works well, but I found some minor issues:

1. Cannot "yum install epel-release"
There's no epel-release package on official repo, need to install manually by:
```
curl -O https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -ivh epel-release-latest-7.noarch.rpm
```
We need to fix our document.

2. $releasever is different with CentOS7
When I use scylla.repo which is on our document, it causes 404:
```
https://s3.amazonaws.com/downloads.scylladb.com/rpm/centos/7Server/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```
Because RHEL7's $releasever is 7Server, not 7.
We need symlink 7 to 7Server, or upload same contents on both dirs.

**Comment by slivne** [comment]
The repo now include 7, 7Server aws s3 does not have symlinks so its a copy at this point

I would rather not remove releasever and have 7 hardcoded as it detects issue in case someone tries to install from other versions
