### ISSUE TITLE
UDT in columns with descending order are unusable

### ISSUE THREAD

**Issue by espindola** [scylladb/scylla#4672]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

On master, 

create type my_type (a int);
create table tbl (a int, b frozen<my_type>, primary key ((a), b)) with clustering order by (b desc);
insert into tbl (a, b) values (1, (2));

Will fail because scylla thinks that (2) is not a valid literal for a reversed udt.

**Comment by tzach** [comment]
I can approve the above work with Apache Cassandra 3.11.4, but not with Scylla 3.1rc1

### Cassandra 
```
cqlsh> CREATE KEYSPACE myks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
cqlsh> use myks ;
cqlsh:myks> create type my_type (a int);
cqlsh:myks> create table tbl (a int, b frozen<my_type>, primary key ((a), b)) with clustering order by (b desc);
cqlsh:myks> insert into tbl (a, b) values (1, (2));
cqlsh:myks> select * from tbl;

 a | b
---+--------
 1 | {a: 2}
```

### Scylla

```
cqlsh> CREATE KEYSPACE myks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
cqlsh> use myks ;
cqlsh:myks> create type my_type (a int);
cqlsh:myks> create table tbl (a int, b frozen<my_type>, primary key ((a), b)) with clustering order by (b desc);
cqlsh:myks> insert into tbl (a, b) values (1, (2));
InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid tuple type literal for b of type frozen<my_type>"

```

**Comment by espindola** [comment]
I have a patch for this: "[PATCH v2] Fix use of UDT in reversed columns"

**Comment by avikivity** [comment]
Backported to 3.0, 3.1. 3.2 not vulnerable.
