### ISSUE TITLE
Control memory usage with row level repair

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#4675]
After commit 8a0c4d508a2519f71ae80dec434500dd97aceba1 (Merge "Repair switch to rpc stream" from Asias), we increased the row buffer size for repair from 512KiB to 32MiB per repair instance. We allow repairing 16 ranges (16 repair instance) in parallel per repair request. So, a node can consume 16 * 32MiB = 512MiB per user requested repair. In addition, the repair master node can hold data from all the repair followers, so the memory usage on repair master can be larger than 512MiB. We need to provide a way to limit the memory usage.

**Comment by avikivity** [comment]
Feature not bug, not backporting.
