### ISSUE TITLE
Connect the docker image to the other graphite metric containers

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#468]
So out of the box we'll have metrics working

**Comment by tzach** [comment]
@dorlaor this is what https://github.com/scylladb/scylla-monitoring is doing

**Comment by dorlaor** [comment]
@tzach , do you mean that we can easily use scyllatop w/ our docker image?

**Comment by glommer** [comment]
Can we close this? Nobody uses graphite anymore and docker works fine with modern scylla monitoring
