### ISSUE TITLE
Scylla hangs or even segfaults when querying system.size_estimates

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#4689]
*Installation details*
Scylla version (or git commit hash): branch master as of time of writing this issue, commit a0499bbd31ddcef0ac3fa8e3c4e5b8f2fc2342bd. But it's been there since at least 256b7d34e2a91df591ad6ec07260293e31d528b4 (4 months ago). I weren't able to compile previous commits because of the old fmt dependency.
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora 29, kernel 5.1.16-200.fc29.x86_64

Easy to reproduce on a fresh database:
```select * from system.size_estimates```
timeouts, Scylla starts using 100% CPU and can't be closed with usual interrupt (needs to be killed). Most probably goes into an infinite loop somewhere.

I even managed to create a database in which the above results in a segfault. Unsurprisingly, the trace points to the function `db::size_estimates::size_estimates_mutation_reader::estimates_for_current_keyspace`.

**Comment by avikivity** [comment]
Backported to 3.1. @kbr- please prepare backports for 3.0 and 2.3 (if vulnerable).

**Comment by avikivity** [comment]
@kbr- ^^^
