### ISSUE TITLE
Interrupting "ninja" can cause build.ninja to disappear

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#4706]
Sometimes running "ninja" will cause `configure.py` to be rerun.

If you quickly kill it with control-C, you can end up with configure.py deleting your old `build.ninja` file but not yet creating a new one. So if you try to run "ninja" again, it will fail (and force you to manually rerun configure.py). This is annoying, and even more so for people who had a bunch of parameters for configure.py and now need to rerun it with all those parameters.

The safest option is for configure.py to atomically create build.ninja. For example, it can write to a temporary file and then rename it. 
Another, simpler, option is to trap signals like SIGINT et al. in configure.py, so it cannot be interrupted in the middle without an explicit (and hopefully deliberate) SIGKILL.

**Comment by avikivity** [comment]
rename seems simplest to me.

**Comment by avikivity** [comment]
Minor build time problem; not backporting.

**Comment by nyh** [comment]
Reopening, because just had the same problem again:

```
$ ninja build/dev/scylla
[0/1] python3 configure.py --disable-dpdk^C
ninja: error: rebuilding 'build.ninja': interrupted by user
$ ninja build/dev/scylla
ninja: error: loading 'build.ninja': No such file or directory
```

I see that my patch above - which replaces build.ninja in one rename - is still in. So we can't end up with a half-written build.ninja. But in this case, the build.ninja was outright **deleted**. I suspect that the real problem (which my patch never fixed...) is that ninja deleted what it considered a rule's output - when it saw the rule failed.

**Comment by nyh** [comment]
It turns out the new version of this bug is harder to trigger than it used to be - usually when you interrupt the build.ninja rebuild, the original file remains and this bug does **not** occur. But configure.py at some point near its end renames the new build.ninja.tmp to build.ninja - and only if you are (un)lucky enough to interrupt it from that point until the end of the configure.py run then is build.ninja removed.

It turns out that Ninja code (see this commit https://github.com/pcc/ninja/commit/af38b5730f670bd4507ced5fc26fb6d2074cf3ac) only removes an output file on rule error (or interrupt) if this output file was **modified**. So if we interrupt configure.py between the time that it rewrote build.ninja until configure.py ends - ninja will see a modified file, and delete it.

I think the best solution would be to move the rename to the very last line of configure.py. This way the chances of interrupting it between that time and the time it exits are close to zero (and the chance that a configure.py failure happens at that point becomes zero).

A more elaborate solution can be to have configure.py write (perhaps if called with a special option) not directly to build.ninja but to a new file, say build.ninja.new, and then add a move rule to move build.ninja.new to build.ninja. If the configure fails or is interrupted, it will be build.ninja.new - not build.ninja - which will be removed.

**Comment by avikivity** [comment]
Build only, not backporting.
