### ISSUE TITLE
how to build in redhat6.5 or centos7.0?

### ISSUE THREAD

**Issue by wuchuguang** [scylladb/scylla#471]
git clone all scylladb code and submodule
./dist/redhat/build_rpm.sh
notice: Unsupported distribution
uname -a
Linux real-server-04 2.6.32-431.el6.x86_64 #1 SMP Sun Nov 10 22:19:54 EST 2013 x86_64 x86_64 x86_64 GNU/Linux

**Comment by slivne** [comment]
We currently do not support building on centos6/rhel6.
We do support building on centos7
So executing this command on a centos7 machine will work and build the rpms
Please note that from branch-0.10 on wards (including head) for performance gains we will build gcc5.1 on centos 7
If you pull out branch-0.9 it will use gcc 4.9 that is available on centos 7

**Comment by dorlaor** [comment]
@slivne , I think we can close it. In parallel, let's open a centos6 feature request issue

**Comment by tzach** [comment]
>  let's open a centos6 feature request issue

https://github.com/scylladb/scylla/issues/452

**Comment by avikivity** [comment]
Question not bug; closing.
