### ISSUE TITLE
utils::config_file::broadcast_to_all_shards does not propapgate to dependent files

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#4713]
The rewrite of config_file to use sharded storage (and consequentially require the "broadcast" op) failed to take info account that the main config file can be also populated with external entries that are not direct members. This is allowed (and used) by extensions to add extra attributes yet keep them in isolated objects (less things in main db/config.hh). 

However, if those external config_file objects are _not_ broadcast, the values they hold (set through main config object) will not be accessible from shards != 0. 

Can fix by either doing explicit broadcasts of the other files, but that would mean more code directly in main.cc or similar to handle config reload. 

Simpler solution is to just propagate broadcast in config_file IFF entries are from other files.

**Comment by avikivity** [comment]
No branch is vulnerable.
