### ISSUE TITLE
Undefined behavior in cleanup sstables

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#4718]
git commit: 8774adb9d06696b

Depending on the evaluation order, the following snippet in cleanup sstables may lead to use after move:
sstables::compaction_descriptor({ std::move(sst) }, sst->get_sstable_level());

**Comment by slivne** [comment]
@raphaelsc is this relevant only to runs or regular cleanups as well 

need to mark if its needed for 3.0/3.1

**Comment by raphaelsc** [comment]
On Thu, Jul 18, 2019 at 6:49 AM Shlomi Livne <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> is this relevant only to runs
> or regular cleanups as well
>
> need to mark if its needed for 3.0/3.1
>
regular cleanup as well. i created two separate issues for that patchset
which fixes the undefined behavior and also cleanup not being run aware

**Comment by avikivity** [comment]
Backporting to 3.1, 3.0, and 2.3.
