### ISSUE TITLE
describe_schema_versions is missing in storage_proxy

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#472]
In origin, describeSchemaVersions is used to get the schema versions from all node, this functionality is needed for nodetool describecluster

**Comment by slivne** [comment]
@amnonh is this resolved ?

**Comment by amnonh** [comment]
no

**Comment by tzach** [comment]
Affect `nodetool describecluster`

**Comment by amnonh** [comment]
test: nodetool_additional_test.py:TestNodetool.describecluster_test verify the bug
