### ISSUE TITLE
Can not replace a node which is failed in the middle of boot up process

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#4723]
In TerminateAndReplace nemsis test, we saw error:
```
Exiting on unhandled exception: std::runtime_error (Could not find tokens for 10.0.41.195 to replace)
```

After looking at the cluster, it turns out other nodes in the cluster did not have TOKENS in the gossip but it has the tokens in the system table for node node 10.0.41.195.

The could happen if 10.0.41.195 failed in the middle of a restarting process.

A node will miss the TOKENS and STATUS application state, if it is killed after line 3 and before line 7, as a result we could not replace the node.
```
    0 stoarge_service::init_server
    1    prepare_to_join()
    2          add gossip application state of NET_VERSION, SCHEMA and so on.
    3         _gossiper.start_gossiping().get()
    4    join_token_ring()
    5           _token_metadata.update_normal_tokens(tokens, get_broadcast_address());
    6           replicate_to_all_cores().get()
    7           storage_service::set_gossip_tokens() which adds the gossip application state of TOKENS and STATUS
```

**Comment by avikivity** [comment]
Alreday backported.
