### ISSUE TITLE
Implement "sstable description" api command

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#4726]
In general, and for certain enterprise features in particular, it would be useful to have a "describe sstables" command that list all/some sstables properties and attributes, such as size, generation, timestamp, version and compression and other "extended" attributes that affect its use and behaviour.

**Comment by slivne** [comment]
@elcallio whats missing to close this ?

**Comment by elcallio** [comment]
It should be backported everywhere now, so nothing.
