### ISSUE TITLE
UX: live in multiple java environment

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#4739]
*Installation details*
Scylla version (or git commit hash): scylla master, scylla-tools-java master
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): All distros

Currently (scylla master/scylla-tools-java master) `nodetool` (maybe all our java tools) doesn't work with openjdk-11-jre (java 1.11), it works with openjdk-8-jre (java 1.8).

We had fixed one dependency issue of scylla-tools-java by https://github.com/scylladb/scylla-tools-java/commit/9dc9cb5a39596e67b8d11309e08c2d1b2ff0fad6, then openjdk-8-jre/openjdk-8-jre-headless will always be installed during scylla installation.

BUT if there is newer java installed before scylla installation, then default java won't be java 1.8, then old (3.0, 2019.1) scylla-jmx won't work,  nodetool (maybe all our java tools) won't work.

----

##### QUESTION:
 Can we use a customized java version (the dependent java in scylla-tools-java) for scylla-jmx, all our java tools?

One workaround for nodetool command:
`JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/ nodetool xxx` 

@tzach

**Comment by tzach** [comment]
@syuu1228 can we?

**Comment by slivne** [comment]
we need to move the tools to support jdk9+

**Comment by slivne** [comment]
https://github.com/scylladb/scylla-tools-java/pull/141

**Comment by slivne** [comment]
should be part of 4.1

**Comment by slivne** [comment]
support for java8...java11 was merged closing
