### ISSUE TITLE
compaction_manager error and coredump upon gemini tests with large number of columns

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#4741]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20190614.4ad06c7ee 3.1.rc99
Cluster size:3 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-087e402340465a532(us-east-1)

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): AWS 
test instances: instance_type_db: 'i3.4xlarge'
oracle instances: instance_type_db_oracle: 'i3.8xlarge'

Using gemini tool run tests over cluster with 3 nodes.
next command was used to run for gemini version 1.4.3
`/$HOME/gemini -d --duration 60m --warmup 10m -c 100 -m mixed -f --non-interactive --cql-features normal --max-columns 100 --min-columns 60 --max-clustering-keys 16 --max-partition-keys 8 --max-mutation-retries 5 --max-mutation-retries-backoff 100ms --test-cluster=172.30.0.66 --oracle-cluster=172.30.0.117 --outfile /tmp/gemini-l0-15a17746-fd5a-4058-8d24-460c5bcdfa3c.log --seed 86`

after several minutes test was failed and with errors:

```
Jul 19 08:43:56 ip-172-30-0-28.ec2.internal scylla.bin[6799]:  [shard 8] compaction_manager - compaction failed: sstables::malformed_sstable_exception (non-null component after null component in sstable /var/lib/scylla/data/ks1/table1-0a7af3f0aa0111e9b36500000000000a/mc-22-big-Data.db): retrying

0x2fd839b
0x2c80143
0x2c8477b
0xfb2377
0xfce78d
0xfcfb5a
0xfd0dd5
0xfd1c15
0x101b2a8
0x10374dd
0x1038684
0xd1d3ae
0xd20dc9
0x1069176
0x1046978
0x747b81
```
Also coredumps were found:
```
[centos@ip-172-30-0-66 ~]$ cat coredumps.info 
           PID: 7091 (scylla)
           UID: 996 (scylla)
           GID: 1001 (scylla)
        Signal: 6 (ABRT)
     Timestamp: Пт 2019-07-19 08:44:07 UTC (52min ago)
  Command Line: /usr/bin/scylla /opt/scylladb/bin/../libexec/scylla.bin --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15
    Executable: /opt/scylladb/libreloc/ld.so
 Control Group: /
       Boot ID: c81c815a77f649cd97d83bbc31f0ab53
    Machine ID: df877a200226bc47d06f26dae0736ec9
      Hostname: ip-172-30-0-66.ec2.internal
       Message: Process 7091 (scylla) of user 996 dumped core.
                
                Stack trace of thread 7103:
                #0  0x00007f9c47fef53f raise (/opt/scylladb/libreloc/libc.so.6)
                #1  0x00007f9c47fd995e abort (/opt/scylladb/libreloc/libc.so.6)
                #2  0x0000000002c83b8b on_allocation_failure (/opt/scylladb/libexec/scylla.bin)

           PID: 10077 (scylla)
           UID: 996 (scylla)
           GID: 1001 (scylla)
        Signal: 6 (ABRT)
     Timestamp: Пт 2019-07-19 08:47:01 UTC (49min ago)
  Command Line: /usr/bin/scylla /opt/scylladb/bin/../libexec/scylla.bin --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 1-7,9-15
    Executable: /opt/scylladb/libreloc/ld.so
 Control Group: /
       Boot ID: c81c815a77f649cd97d83bbc31f0ab53
    Machine ID: df877a200226bc47d06f26dae0736ec9
      Hostname: ip-172-30-0-66.ec2.internal
      Coredump: /var/lib/systemd/coredump/core.scylla.996.c81c815a77f649cd97d83bbc31f0ab53.10077.1563526021000000
       Message: Process 10077 (scylla) of user 996 dumped core.
                
                Stack trace of thread 10088:
                #0  0x00007f184bbf453f raise (/opt/scylladb/libreloc/libc.so.6)
                #1  0x00007f184bbde95e abort (/opt/scylladb/libreloc/libc.so.6)
                #2  0x0000000002c83b8b on_allocation_failure (/opt/scylladb/libexec/scylla.bin)
````

Logs are available by link:
https://cloudius-jenkins-test.s3.amazonaws.com/ae637a44-dcbd-42ce-ae38-cf3e32d0e087/2019_07_19_09_37_23/db-cluster-ae637a44.zip

instances are available:
```
abykov-gemini-basic-3.1-db-node-ae637a44-3        | ec2-3-86-43-23.compute-1.amazonaws.com   
abykov-gemini-basic-3.1-loader-node-ae637a44-1    | ec2-3-91-226-159.compute-1.amazonaws.com   
abykov-gemini-basic-3.1-db-node-ae637a44-2        | ec2-3-95-156-23.compute-1.amazonaws.com    
abykov-gemini-basic-3.1-db-node-ae637a44-1        | ec2-3-88-173-215.compute-1.amazonaws.com   
abykov-gemini-basic-3.1-monitor-node-ae637a44-1   | ec2-34-201-57-65.compute-1.amazonaws.com   
abykov-gemini-basic-3.1-oracle-db-node-ae637a44-1 | ec2-52-23-195-6.compute-1.amazonaws.com9
```

Monitoring Node:
http://ec2-34-201-57-65.compute-1.amazonaws.com:3000/d/ZHfJhSNZk/scylla-per-server-metrics-nemesis-master?orgId=1&from=1563525774645&to=1563525934213&var-by=instance&var-cluster=&var-dc=All&var-node=All&var-shard=All&var-sct_tags=CoreDumpEvent

**Comment by slivne** [comment]
@aleksbykov while this is promissing - I need a run on 3.1.rc2 to see if this reproduces, and if we have a blocker for 3.1

**Comment by aleksbykov** [comment]
@slivne Use rc99 because it has more recent day than rc2. i thought it was a latest stable rc.

Rerun on rc2.  Test failed again. Got next error:
` scylla[9964]:  [shard 7] storage_proxy - Exception when communicating with 172.30.0.247: std::runtime_error (sstable inactive read queue overloaded)`
` [shard 9] storage_proxy - Exception when communicating with 172.30.0.247: std::runtime_error (sstable inactive read queue overloaded)`

The same gemini command with same seed was run on same cluster configuration:
monitor node [link](http://ec2-3-86-102-252.compute-1.amazonaws.com:3000/d/2v7vicNWz/scylla-per-server-metrics-nemesis-3-1?refresh=30s&orgId=1&var-by=instance&var-cluster=&var-dc=All&var-node=All&var-shard=All&var-sct_tags=CoreDumpEvent)
instances available:
```
abykov-gemini-basic-3.1-loader-node-125eb347-1    | ec2-54-165-214-75.compute-1.amazonaws.com
abykov-gemini-basic-3.1-monitor-node-125eb347-1   | ec2-3-86-102-252.compute-1.amazonaws.com 
abykov-gemini-basic-3.1-db-node-125eb347-2        | ec2-3-87-187-207.compute-1.amazonaws.com 
abykov-gemini-basic-3.1-oracle-db-node-125eb347-1 | ec2-54-210-214-122.compute-1.amazonaws.com
abykov-gemini-basic-3.1-db-node-125eb347-3        | ec2-18-208-178-161.compute-1.amazonaws.com
abykov-gemini-basic-3.1-db-node-125eb347-1        | ec2-3-94-121-12.compute-1.amazonaws.com
```

**Comment by slivne** [comment]
@aleksbykov did you get the same coredumps and the same error during compaction ?

- if you did get a coredump on 3.1.rc2 please upload and provide the exact information on how to access
- if you did get the error in compaction ```... compaction_manager - compaction failed: sstables::malformed_sstable_exception (non-null component after null component in sstable): retrying  ```
please post the logs / files 

on 3.1.rc2 any of these maybe a showstopper for the release - if the coredump/compaction error is only on master its for 3.2 release

**Comment by slivne** [comment]
@aleksbykov ping

**Comment by slivne** [comment]
I am currently waiting for Alex answer to know if to tag this differently

**Comment by aleksbykov** [comment]
@slivne Sorry for delay.
The latest rerun on give the next errors:
```
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: Reactor stalled for 650 ms on shard 9.
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: Backtrace:
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000004151ca2
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x000000000403ef25
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x000000000403f465
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x000000000403f757
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x00007f0bbb7e102f
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x00007f0bbb2101fd
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000002d58abb
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000002d59e9d
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000002d5c32a
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000002d5d6e7
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000002d607dd
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x000000000298a45a
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000001e7e824
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000001e8307f
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000001e6f1eb
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000001d4a264
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000001d76570
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000001dd1020
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000001dd4a83
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x00000000030e4f83
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x00000000030ebd8e
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x000000000191d4cf
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000001934b0e
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000001934b6c
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x000000000194ab72
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x0000000003faafec
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x000000000403c411
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x000000000403c60e
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x000000000411e2dd
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x000000000414894b
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: 0x000000000400a70d
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: /opt/scylladb/bin/../libreloc/libpthread.so.0+0x000000000000858d
Jul 23 05:15:53 ip-172-30-0-221.ec2.internal scylla[7290]: /opt/scylladb/bin/../libreloc/libc.so.6+0x00000000000fd6a2
```
Logs are available here : https://cloudius-jenkins-test.s3.amazonaws.com/ee10c8e5-dfaf-4cbe-8fed-6a44db9d0d82/abykov-gemini-basic-3.1-db-cluster-ee10c8e5.zip
https://cloudius-jenkins-test.s3.amazonaws.com/beef7636-13ff-4ccd-86a7-447d597f26ee/abykov-gemini-basic-3.1-db-cluster-beef7636.zip

**Comment by aleksbykov** [comment]
> @aleksbykov did you get the same coredumps and the same error during compaction ?
> 
> * if you did get a coredump on 3.1.rc2 please upload and provide the exact information on how to access
> * if you did get the error in compaction `... compaction_manager - compaction failed: sstables::malformed_sstable_exception (non-null component after null component in sstable): retrying  `
>   please post the logs / files
> 
> on 3.1.rc2 any of these maybe a showstopper for the release - if the coredump/compaction error is only on master its for 3.2 release

logs for compaction errors are here: https://cloudius-jenkins-test.s3.amazonaws.com/ae637a44-dcbd-42ce-ae38-cf3e32d0e087/2019_07_19_09_37_23/db-cluster-ae637a44.zip

**Comment by aleksbykov** [comment]
```
| abykov-gemini-basic-3.1-db-node-b1b49863-1        | ec2-52-206-106-39.compute-1.amazonaws.com  |
| abykov-gemini-basic-3.1-monitor-node-b1b49863-1   | ec2-3-86-81-163.compute-1.amazonaws.com    |
| abykov-gemini-basic-3.1-db-node-b1b49863-3        | ec2-35-172-133-90.compute-1.amazonaws.com  |
| abykov-gemini-basic-3.1-loader-node-b1b49863-1    | ec2-3-88-177-199.compute-1.amazonaws.com   |
| abykov-gemini-basic-3.1-db-node-b1b49863-2        | ec2-100-26-203-84.compute-1.amazonaws.com  |
| abykov-gemini-basic-3.1-oracle-db-node-b1b49863-1 | ec2-3-93-6-151.compute-1.amazonaws.com     |
```

**Comment by aleksbykov** [comment]
This issue is stay for coredump of scylla for 3.1.rc99

**Comment by slivne** [comment]
@aleksbykov I need to understand if we are getting coredumps 

Stalls are not the same.

If we are getting coredumps for this on 3.3 / master please comment with the info and we will reopen
