### ISSUE TITLE
commit log might not close all files

### ISSUE THREAD

**Issue by espindola** [scylladb/scylla#4745]
On current master (7604980d638ef83cf8f8d8083fa1a82c00572ba4) each commit log segment keeps track of whether it is closed or not. This is not exactly the same thing as the underlying file being closed. The discrepancy can cause files to be left open until they are destroyed.

**Comment by avikivity** [comment]
Backported to 3.1. I think 3.0 is not vulerable since it doesn't reuse segments, @espindola please confirm.

**Comment by espindola** [comment]
The code in 3.0 is at least suspicious. It has

  future<sseg_ptr> finish_and_get_new(db::timeout_clock::time_point timeout) {
        _closed = true;
        sync();
...

So there is at least a time windown where _closed is true but the file has not been closed.
