### ISSUE TITLE
Read execution stage can grow without bounds.

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#4749]
*Installation details*
Scylla version (or git commit hash): 7604980d638ef83cf8f8d8083fa1a82c00572ba4

We observe that under heavy read load read execution stage grows to several million entries:

![execstage](https://user-images.githubusercontent.com/6554938/61623488-66fa1400-ac7f-11e9-8043-5128208069d2.png)

The problem is that nothing is limiting the queue size. If works comes in faster than it can be dequeued the queue will grow until all memory is consumed. The graph of preempted execution stage flushes shows that indeed the queue cannot be depleted by a single flush task:

![execpreempt](https://user-images.githubusercontent.com/6554938/61623670-c3f5ca00-ac7f-11e9-942e-acc2ef88c8ea.png)

**Comment by avikivity** [comment]
Backported to 3.0 and 3.1.
