### ISSUE TITLE
SSTables: read_indexes() could guarantee non-overlapping ranges

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#475]
It will be beneficial for the users of `sstable::read_indexes()` if it guaranteed that returned ranges of keys never overlap, i.e. for each partition key present in the sstable there is only one `idx` that `read_indexes(idx)` returns a range containing that key.

**Comment by pdziepak** [comment]
This probably can be done as a side effect of fixing #474.

**Comment by raphaelsc** [comment]
In simple words, different summary indexes cannot cover the same partition key. Correct?

**Comment by pdziepak** [comment]
On 23 October 2015 at 19:24, Raphael Carvalho <notifications@github.com>
wrote:

> In simple words, different summary indexes cannot cover the same partition
> key. Correct?
>
Yes, that right. The goal is that if we concatenate outputs of
read_indexes(i) for all i we get a sorted array of all partition keys
present in that sstable without any duplicates.

**Comment by pdziepak** [comment]
This is fixed by 01e301fc9a65585e75e08ce9d738659c54008224.
