### ISSUE TITLE
scylla.yaml parameter "rpc_interface_prefer_ipv6: false" is ignored

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#4751]
Scylla version (or git commit hash): master

As far as I can see, `rpc_interface_prefer_ipv6` parameter is ignored.

In Apache Cassandra, the same parameter is read
https://github.com/apache/cassandra/blob/cassandra-3.11/src/java/org/apache/cassandra/config/DatabaseDescriptor.java#L857

**Comment by tzach** [comment]
@elcallio should this be part of the ipv6 addition?

**Comment by tzach** [comment]
Cassandra also include a parameter `listen_interface_prefer_ipv6: false`
https://github.com/apache/cassandra/blob/cassandra-3.11/conf/cassandra.yaml#L622

**Comment by elcallio** [comment]
I honestly had no idea those even existed. But they should probably be implemented, yes.
However, they are also a bit misleading as we don't really have any "interface" support in scylla/seastar.

**Comment by tzach** [comment]
> I honestly had no idea those even existed.

same here

**Comment by slivne** [comment]
@elcallio - which parts in the config related to ipv6 are supported ?

the ipv6 that we merged covered a configuration value: ``` enable_ipv6_dns_lookup ``` any other config related to ipv6 ?

aside of that are all addresses in the config can be set to ipv6 value: 
listen_address, broadcast_address, rpc_address, api_address, prometheus_address, broadcast_rpc_address, seeds ?

**Comment by elcallio** [comment]
Any address can be specified as ipv6, and if enabled, DNS name lookup will pick up ipv6 names (depending on DNS answer). `enable_ipv6_dns_lookup` is the only explicit flag enabled, and it simply enables accepting either ipv4 or ipv6 address answers on DNS query when binding symbolic names.

**Comment by avikivity** [comment]
no release branch affected.
