### ISSUE TITLE
cache-mostly read workloads can overload memory

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#4758]
Requests served from disk have a queue that limits memory use an expire timed-out requests, but requests served from cache do not. This can cause those requests to consume too much memory, and the reactor to process expired requests rather than timing them out and returning an error.

**Comment by eliransin** [comment]
@avikivity I see you have a commit that is noted as fixing this. It it still relevant?

**Comment by avikivity** [comment]
The commit is not committed.

@denesb's work will make it possible to revisit this soon.

**Comment by denesb** [comment]
@avi what is required for this to move on?

**Comment by avikivity** [comment]
1. Have reader_concurrency_semaphore track how many permit-holding requests are free to run (vs. waiting for I/O to complete).
2. Change reader_concurrency_semaphore not to admit new requests while the number of non-blocked requests is nonzero
3. Move r_c_s in front of the cache

**Comment by denesb** [comment]
So, basically we need https://github.com/scylladb/scylla/issues/5718.

**Comment by denesb** [comment]
I'm working on a series now that adds a permit to all flat mutation readers (it adds it to `flat_mutation_reader::impl` right next to `_schema`). With that, we will be just one step away.
