### ISSUE TITLE
Fix cql server admission control to take all leftover work into account

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#4768]
*Installation details*
Scylla version (or git commit hash): 733c68cb13ed20883078a13eb7f9dbc8c5652eb2

Current admission control takes a permit when cql requests starts and releases it when reply is sent, but some requests may leave background work behind after that point (some because there is genuine background work to do like complete a write or do a read repair, and some because a read/write may stuck in a queue longer than the request's timeout, so after Scylla replies with a timeout some resources are still occupied). 

One way to fix that is to make admission control  pass the permit  to storage proxy (or may be even to the DB) and release it only when no background work is left.

**Comment by avikivity** [comment]
Will reconsider for backport after 3.2 gains some mileage.

**Comment by avikivity** [comment]
Aged out.
