### ISSUE TITLE
Partial runs incorrectly selected for compaction

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#4773]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 8774adb9d06
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Scyla could have partial run being incorrectly compacted, look:

[shard 0] compaction - Compacted 6 sstables to [/var/lib/scylla/data/keyspace1/standard1-5ca6a220a94611e995fc000000000008/la-350-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-5ca6a220a94611e995fc000000000008/la-406-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-5ca6a220a94611e995fc000000000008/la-462-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-5ca6a220a94611e995fc000000000008/la-532-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-5ca6a220a94611e995fc000000000008/la-588-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-5ca6a220a94611e995fc000000000008/la-630-big-Data.db:level=0, ]. 5377474739 bytes to 5377384696 (~99% of original) in 473523ms = 10.83MB/s. ~4920576 total partitions merged to 4920172.

[shard 0] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-5ca6a220a94611e995fc000000000008/la-588-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-5ca6a220a94611e995fc000000000008/la-966-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-5ca6a220a94611e995fc000000000008/la-1008-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-5ca6a220a94611e995fc000000000008/la-1554-big-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-5ca6a220a94611e995fc000000000008/la-1512-big-Data.db:level=0, ]

Observe that generation la-588, which run also contains gens 350, 630, etc, is compacted alone in the Compacting message above.

**Comment by bhalevy** [comment]
@raphaelsc do we have a reproducer for this issue so we can add it as a regression test?

**Comment by slivne** [comment]
@Raphael S. Carvalho <raphaelsc@scylladb.com>  - please note

"@raphaelsc <https://github.com/raphaelsc> do we have a reproducer for this
issue so we can add it as a regression test?"

Please reply although this was merged

**Comment by raphaelsc** [comment]
On Sun, Aug 11, 2019 at 4:07 PM Shlomi Livne <notifications@github.com>
wrote:

> @Raphael S. Carvalho <raphaelsc@scylladb.com> - please note
>
> "@raphaelsc <https://github.com/raphaelsc> do we have a reproducer for
> this
> issue so we can add it as a regression test?"
>
> Please reply although this was merged
>

I will write an unit test for this, but I think a dtest would be more
efficient testing wise.

**Comment by avikivity** [comment]
No released branches can generate partial runs; removing backport candidacy.
