### ISSUE TITLE
Improve compaction log printouts

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4778]
We need to include more information in the compaction printouts like:
- a unique compaction identifier that will help match start and finish pairs.
- sstables run identifier

**Comment by bhalevy** [comment]
Since compaction already spams the log, we should move the logs with the additional information into the compaction_history table.

**Comment by raphaelsc** [comment]
not long time ago I sent a patch to compress the logs, but I still need to work on v2. and @bhalevy recently worked on the uuid which helps matching compaction start and finish.

**Comment by bhalevy** [comment]
This is done already
