### ISSUE TITLE
DTEST batch_test.py:TestBatch.acknowledged_by_batchlog_set_when_batchlog_write_succeeds_test

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#478]
using commit cf734132e7c2a925d784a276fd49f30969d36ddb
Merge: 93c1035 02732f1
Author: Avi Kivity <avi@scylladb.com>
Date:   Tue Oct 20 17:36:57 2015 +0300

    Merge "Flusing of CF:s without replay positions" from Calle
    
    "Fixes: #469
    
    We occasionally generate memtables that are not empty, yet have no
    high replay_position set. (Typical case is CL replay, but apparently
    there are others).
    
    Moreover, we can do this repeatedly, and thus get caught in the flush
    queue ordering restrictions.
    
    Solve this by treating a flush without replay_position as a flush at the
    highest running position, i.e. "last" in queue. Note that this will not
    affect the actual flush operation, nor CL callbacks, only anyone waiting
    for the operation(s) to complete.
    
    To do this, the flush_queue had its restrictions eased, and some introspection
    methods added."

the test fails consistently it passed in older versions (branch-0.10)

```

shlomi@localhost~/urchin-dtest (master)$ pkill -9 scylla;  KEEP_TEST_DIR=true nosetests -v -s batch_test.py:TestBatch.acknowledged_by_batchlog_set_when_batchlog_write_succeeds_test
acknowledged_by_batchlog_set_when_batchlog_write_succeeds_test (batch_test.TestBatch) ... FAIL

======================================================================
FAIL: acknowledged_by_batchlog_set_when_batchlog_write_succeeds_test (batch_test.TestBatch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/batch_test.py", line 150, in acknowledged_by_batchlog_set_when_batchlog_write_succeeds_test
    """, ConsistencyLevel.THREE, received_responses=2)
  File "/home/shlomi/urchin-dtest/batch_test.py", line 197, in assert_timedout
    assert e.received_responses == received_responses, msg
AssertionError: Expecting received_responses to be 2, got: 1
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/shlomi/.dtest/dtest-eTSowm
cassandra.cluster: WARNING: Host 127.0.0.3 has been marked down
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.3, scheduling retry in 2.0 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.3, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.3, scheduling retry in 8.0 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.3, scheduling retry in 16.0 seconds: [Errno 111] Tried connecting to [('127.0.0.3', 9042)]. Last error: Connection refused
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 35.859s

FAILED (failures=1)
```

**Comment by elcallio** [comment]
I very much doubt that the commit above is responsible for the failure. If I disable all flush queueing, the test still fails. 
Still investigating though...

**Comment by slivne** [comment]
I don't think its related - it is related to the changes between
branch-0.10 and current head.

It started failing between branch-0.10 and
c8cc8a0b0fdf5660cae7d2affbc5703c079c0004
