### ISSUE TITLE
add counters for DDL

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4785]
Schema changes are "rare" events that at times cause extra load on the system.

Currently schema changes are only visible via logs.

Export schema change CQL requests via a metric in CQL level - starting from a single counter that is incremented on every CQL DDL request (CREATE TABLE ...).

Add a counter that is increased when ever the local schema changes - this will allow to detect changes in which the schema's are not getting synchronized and are changing rapidly (via metrics instead of logs).

**Comment by tzach** [comment]
We can report the schema version itself (UUID) from each node, and present it in the new node table
It will allow us to see the history of schema updates in the cluster.

**Comment by tzach** [comment]
@amnonh can we break the schema hash into a list of numbers?

**Comment by amnonh** [comment]
There is no clear way of reporting the UUID with a metric.
We can use a label, but that would mean that it will be registered as a new metric all the time.

If we are going to use a counter, is it going to be monotonic? i.e. what will happen when restarting a node?

**Comment by tzach** [comment]
Restart should not change the schema UUID
If each server report the schema as a label with counter=1 
Can we use it to extract the latest schema of each node?

**Comment by slivne** [comment]
since one attempt was blocked (reporting the UUID) lets add a counter for DDL

**Comment by avikivity** [comment]
Not a bug; removing backport candidate label.
