### ISSUE TITLE
KA/LA sstable reader doesn't emit partition_end and partition_start

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#4786]
mp_row_consumer_k_l::push_ready_fragments has a bug that when _ready is set it will only call mp_row_consumer_k_l::push_ready_fragments_with_ready_set and no mp_row_consumer_k_l::push_ready_fragments_out_of_range.

That leads to sstable_mutation_reader::fill_buffer reading the content of the next partition without closing the previous one.

**Comment by haaawk** [comment]
Related to https://github.com/scylladb/scylla-enterprise/issues/968

**Comment by haaawk** [comment]
Fixed by https://github.com/scylladb/scylla/commit/9b8ac5ecbc66de574b8ce885de809cbe08d7c16c

**Comment by tgrabiec** [comment]
@haaawk Can you explain why didn't we run into this bug all the time?

**Comment by haaawk** [comment]
@tgrabiec It requires partition ending with range tombstone and a row plus it has to happen at the end of the flat mutation reader buffer. The chances are relatively low. Moreover, this bug can go unnoticed if the fragments of the next partition are all after the last fragment of the previous partition. Such situation creates a valid sstable but data inside is wrong as some rows have migrated from one partition to the other.

**Comment by slivne** [comment]
@haaawk if a user does not have range tombstones - does that mean he will not hit the bug ?

**Comment by haaawk** [comment]
@slivne That's my understanding. If there's no range tombstone then consuming row end will emit row that's stored in _in_progress and will leave _ready empty so push_ready_fragments won't pick [this branch](https://github.com/scylladb/scylla-enterprise/blob/scylla-2018.1.11/sstables/partition.cc#L1173) and instead emit partition_end by picking [this branch](https://github.com/scylladb/scylla-enterprise/blob/scylla-2018.1.11/sstables/partition.cc#L1177).

**Comment by vladzcloudius** [comment]
@haaawk Following Shlomi's question: can range tombstones be generated only by range DELETE operations or are they other possibilities that could lead to appearance of range tombstones, e.g. can a few tombstones of consequent tokens with the same time stamp get merged into a single range tombstone?

**Comment by haaawk** [comment]
@vladzcloudius I don't think consecutive tombstones are ever combined into range tombstone. Same with truncate. In general, I'm not aware of any other way to create range tombstone but DELETE operation.

**Comment by vladzcloudius** [comment]
@haaawk Thanks, sir!
