### ISSUE TITLE
Receiving side of streaming may abort or produce incorrect sstables when failure happens on the sender side

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4789]
Scylla version (or git commit hash): 3.0

We've seen a node abort inside sstable writer:
```
sstables/sstables.cc:1748: void sstables::seal_summary(sstables::summary&, std::experimental::fundamentals_v1::optional<sstables::key>&&, std::experimental::fundamentals_v1::optional<sstables::key>&&, const sstables::index_sampling_state&): Assertion `first_key' failed. 
```

The cause was that active partition was not closed in the input mutation fragment stream (missing `partition_end` fragment). Because that was the only partition, the sstable writer appeared to have no partitions, which triggers the asserts.

If there were more partitions, the writer would not fail, but sstable index and partition range metadata would be incorrect, which would manifest as errors during read, or data apparently missing. Recompacting such sstable fixes the problem without loosing any data.

The writer belonged to the streaming receiver and it looked like the generating reader reached end-of-stream after emitting `clustering_row`. This is incorrect since there should be a `partition_end` fragment before the stream ends.

It does so when the mutation fragment generating functor returns a disengaged optional. The streaming functor does so when it gets a disengaged optional from the RPC stream's source:

```
auto get_next_mutation_fragment = [source, plan_id, from, s] () mutable {
                        return source().then([plan_id, from, s] (stdx::optional<std::tuple<frozen_mutation_fragment>> fmf_opt) mutable {
                            if (fmf_opt) {
                                frozen_mutation_fragment& fmf = std::get<0>(fmf_opt.value());
                                auto sz = fmf.representation().size();
                                auto mf = fmf.unfreeze(*s);
                                streaming::get_local_stream_manager().update_progress(plan_id, from.addr, progress_info::direction::IN, sz);
                                return make_ready_future<mutation_fragment_opt>(std::move(mf));
                            } else {
                                return make_ready_future<mutation_fragment_opt>();
                            }
                        });
                    };
```

The matching sink on the sender side looks like this:

```
auto sink_op = [sink, si, got_error_from_peer] () mutable -> future<> {
            return do_with(std::move(sink), [si, got_error_from_peer] (rpc::sink<frozen_mutation_fragment>& sink) {
                return repeat([&sink, si, got_error_from_peer] () mutable {
                    return si->reader(db::no_timeout).then([&sink, si, s = si->reader.schema(), got_error_from_peer] (mutation_fragment_opt mf) mutable {
                        if (mf && !(*got_error_from_peer)) {
                            frozen_mutation_fragment fmf = freeze(*s, *mf);
                            auto size = fmf.representation().size();
                            streaming::get_local_stream_manager().update_progress(si->plan_id, si->id.addr, streaming::progress_info::direction::OUT, size);
                            return sink(fmf).then([] { return stop_iteration::no; });
                        } else {
                            return make_ready_future<stop_iteration>(stop_iteration::yes);
                        }
                    });
                }).finally([&sink] () mutable {
                    return sink.close();
                });
            });
        }();
```

The stream may end prematurely if any exception happens before `si->reader` is exhausted.

**Comment by bhalevy** [comment]
@tgrabiec great catch!
@asias does that fall in your realm?

**Comment by asias** [comment]
> @tgrabiec great catch!
> @asias does that fall in your realm?

Yes. PR sent.

**Comment by tgrabiec** [comment]
@asias Doesn't backport cleanly to 3.0, please send a patch.

**Comment by asias** [comment]
I already did part of the work. Waiting for the other 2 PRs. I need them to
do the back port.

**Comment by bhalevy** [comment]
@asia, @tgrabiec: are we done with the backports for this issue?
If so, please clear the "Backport candidate" label.

**Comment by tgrabiec** [comment]
@bhalevy Yes.

Backported to 3.1 and 3.0
