### ISSUE TITLE
migration_manager::sync_schema() may succeed even if schema was not synced

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4791]
Currently used only when repair starts

It calls `migration_manager::submit_migration_task()` which calls `service::migration_task::run_may_throw()`, which has this:

```
    if (!gms::get_local_gossiper().is_alive(endpoint)) {
        mlogger.warn("Can't send migration request: node {} is down.", endpoint);
        return make_ready_future<>();
    }
```

So if one of the requested nodes is down we will succeed the sync, while we should fail. According to the doc:

```
// Makes sure that this node knows about all schema changes known by "nodes" that were made prior to this call.
```

**Comment by slivne** [comment]
@asias ?

**Comment by slivne** [comment]
@asias ping since we have moved to used repair for base operations we need this cleared out

**Comment by asias** [comment]
Schema sync should be done before we use repair to sync the data during bootstrap. To be safe, I think we can make migration_manager::sync_schema return exceptional future if not all nodes has responded the schema pull request.

**Comment by asias** [comment]
PR sent https://github.com/scylladb/scylla/pull/6079

**Comment by avikivity** [comment]
Backported to 4.0 (4.1+ have it)
