### ISSUE TITLE
Add info to SSTable meta data

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#4798]
*Installation details*
Scylla version (or git commit hash): 3.1

When the case of an issue with SSTable, it will be useful to know which element in the system generate the SSTable, for example, compaction, flush, streaming.
If possible, even what type of streaming: repair, topology change etc.

**Comment by raphaelsc** [comment]
@bhalevy looks like this can be closed after origin added to scylla component

**Comment by bhalevy** [comment]
Agreed. The changes are da4fa06 and scylladb/sstable-tools@f309b10
