### ISSUE TITLE
Need tool for dumping sstable scylla metadata

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4801]
We need a tool to dump sstable scylla metadata.
Depends on #4800 - rather than developing it as a java tool, it would be better to share code with scylla using a library.

**Comment by bhalevy** [comment]
Ref #4798

**Comment by haaawk** [comment]
Have you seen this: https://github.com/scylladb/sstable-tools

**Comment by bhalevy** [comment]
> Have you seen this: https://github.com/scylladb/sstable-tools

It doesn't seem to have a tool for the dumping the scylla component, does it?
And in general, it maybe faster to develop tools ad-hoc but in the long run it's a nightmare to maintain the tools without sharing code with scylla.

**Comment by haaawk** [comment]
I dunno. Haven't used it much. Just for reading index once.

**Comment by denesb** [comment]
> It doesn't seem to have a tool for the dumping the scylla component, does it?
> And in general, it maybe faster to develop tools ad-hoc but in the long run it's a nightmare to maintain the tools without sharing code with scylla.

In theory yes, but in practice sstable formats don't really change, so the investment has to be done once. Using `sstable_tools.sstablelib` one can write a tool to dump the scylla component in less then half an hour.

**Comment by bhalevy** [comment]
> > It doesn't seem to have a tool for the dumping the scylla component, does it?
> > And in general, it maybe faster to develop tools ad-hoc but in the long run it's a nightmare to maintain the tools without sharing code with scylla.
> 
> In theory yes, but in practice sstable formats don't really change, so the investment has to be done once. Using `sstable_tools.sstablelib` one can write a tool to dump the scylla component in less then half an hour.

But in practice we do change extend the scylla metadata over time (e.g. #4798).
Once we have the infrastructure to share the format code I to generate json as an output format it should also be trivial to create a new dump tool.

The main benefit would be that it will be automatically version controlled along with the format change.

**Comment by denesb** [comment]
> > > It doesn't seem to have a tool for the dumping the scylla component, does it?
> > > And in general, it maybe faster to develop tools ad-hoc but in the long run it's a nightmare to maintain the tools without sharing code with scylla.
> > 
> > 
> > In theory yes, but in practice sstable formats don't really change, so the investment has to be done once. Using `sstable_tools.sstablelib` one can write a tool to dump the scylla component in less then half an hour.
> 
> But in practice we do change extend the scylla metadata over time (e.g. #4798).
> Once we have the infrastructure to share the format code I to generate json as an output format it should also be trivial to create a new dump tool.
> 
> The main benefit would be that it will be automatically version controlled along with the format change.

Scylla metadata is pretty much the only one that can change, as the other components are "set in stone".
Don't get me wrong, I agree that using the core scylla code for these dump tools would be the best, but until we get there, new `sstable_tools` utilities are pretty low effort to create/maintain for the most part, given that we already have a lot of the parsing infrastructure in place.

**Comment by tgrabiec** [comment]
We discover bugs in the sstable writer from time to time and introduce feature flags to change the behavior of the reader to interpret sstables differently depending on whether it was generated before or after the fix. The benefit of reusing Scylla code is that the tool would automatically account for such fixes and interpret the sstable the same as Scylla would.

sstable-tools cannot work with the mc format, and adding that would be a major effort I think.

**Comment by denesb** [comment]
Indeed the data component is a though nut and is definitely not worth the effort. I had the others in mind, which are reasonably simple and static.

**Comment by slivne** [comment]
there are other tools that work with mc format https://github.com/instaclustr/cassandra-sstable-tools as well - they are not scylla component aware but are mc aware.

**Comment by raphaelsc** [comment]
https://github.com/scylladb/sstable-tools/ is now able to dump scylla.db, after https://github.com/scylladb/sstable-tools/commit/523dc12a148fe5b4fc8a77be643aef6ff3f85d67#diff-99ad7487558c5f05406924960c9ed984d210effcd9d10b45fc70482529e744fe

so i am closing this...

**Comment by bhalevy** [comment]
Agreed.  The changes are https://github.com/scylladb/scylla/commit/da4fa0629ad6cba44e72ad8a9b441e3b8f9ec8cf and https://github.com/scylladb/sstable-tools/commit/f309b102a236efac96b0a3ddef6b9e2d1a5f0418
