### ISSUE TITLE
Expand sstable writer validation check for partition fragments monotonicity

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4803]
Based on @tgrabiec internal presentation:

Patch 95c08047318ba819cdd74ac7b1aabcd35f086a0b added validation of partition_end being  emitted 

Expand the validation to cover monotonicity of all partition fragments parts:

* partition_start
* static_row
* clustering row
* partition_end

such that they adhere partition_start, [static_row], {clustering_row}* parition_end

**Comment by bhalevy** [comment]
I think this should be backported to 3.1 given that mc format is planned to be enabled by default there.

**Comment by bhalevy** [comment]
Consider backport to 3.1 and 3.0

**Comment by bhalevy** [comment]
Key monotonicty validation can be enabled in testing, e.g. for longevity runs that are not performance sensitive.

**Comment by roydahan** [comment]
we enabled it starting 3.2
