### ISSUE TITLE
Expand sstable writer check for fragment position monotonicity

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4804]
based on @tgrabiec internal presentation

in addition to #4803 add fragment position monotonicity of partition_start keys and clustering_row keys

since this will require an overhead to store the last key and also to compare need to decide if this will be enabled by default or by flag.

**Comment by denesb** [comment]
@tgrabiec would it be feasible to add reference counting capabilities to `managed_bytes`, allowing us to avoid the cost of copying the keys? The references would not be equal. There would be a main reference (the original one) and the others would be basically be const views that also keep the data alive. Thus we wouldn't need to worry about rouge writes. Also the default copy behaviour could stay the same, creating such a ref counted view would be an explicit operation.
This would also help in other areas, like keeping track of the last position in the multishard reader.

**Comment by bhalevy** [comment]
I think this should be backported to 3.1 given that mc format is planned to be enabled by default there.

**Comment by avikivity** [comment]
Feature, not bug fix.
