### ISSUE TITLE
Unsealed sstables due to failed repair or streaming are left on disk until node is restarted

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4807]
Scylla version: 3.0

We should delete them as soon as we detect that they're not going to be attached to the database (the operation failed) so that they don't take up space unnecessarily.

Maybe mark for deletion when creating them, and unmark when attaching.

**Comment by slivne** [comment]
The main issue is that we maybe accumulating such files (especially if users have challenging network) in which case we may run out of diskspace.

Is there a limit on the size of files we are streaming and that may get stuck in this state ?

**Comment by tgrabiec** [comment]
I don't think there is any limit.

**Comment by bhalevy** [comment]
> Maybe mark for deletion when creating them, and unmark when attaching.

Maybe this (delete in destructor) should just be the default for any unsealed sstable.
I can't think of any reason right where we want to keep unsealed sstables when we destruct their object.

**Comment by avikivity** [comment]
Agree.

**Comment by avikivity** [comment]
Aged out (and not a regression).
