### ISSUE TITLE
Provide information about clients connected

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#4820]
While we have counters for the number of open connections it would help to extract the info on the clients connected and as much info as possible (protocol version / ssl / user / driver / driver versionn / cql version etc.)

https://issues.apache.org/jira/browse/CASSANDRA-13665

yet extend it to extract all the info from auth state and also from the STARTUP phase that does include additional info 

![Screenshot from 2019-08-09 00-25-25](https://user-images.githubusercontent.com/3465480/62738952-44684900-ba3c-11e9-97da-38ec466de80e.png)

It would be best to expose this as a system table and not only as a nodetool command

**Comment by dorlaor** [comment]
+1 for system/virtual table.

**Comment by haaawk** [comment]
Probably being able to detect shard awareness would be a nice addition too.

**Comment by jul-stas** [comment]
So we want *both* nodetool command *and* virtual table?

Also, this is a minor thing: I see the tag C*4.x-compatibility - does that mean that new vtable should go to "system_views.clients"? I was advised to call @tzach for this one - it'd be great if you could hint me here.

**Comment by nyh** [comment]
@jul-stas you closed this issue, but the patch you wrote to address it was not yet committed. Was this by mistake?

**Comment by jul-stas** [comment]
Aww, I didn't even notice that, so must have been a mistake. Sorry and thanks.

**Comment by tzach** [comment]
@psarna can / should we add the Scylla node IP to the table as well?

**Comment by psarna** [comment]
@tzach I think it's unnecessary - system.clients is a local table (keeps separate local system information separately on each node, without any replication), so IP of the Scylla node is implied as the node you sent the request to.
