### ISSUE TITLE
3.1.0.rc3 fails to start on volume mount permission errors

### ISSUE THREAD

**Issue by robertfreund** [scylladb/scylla#4823]
scylla --version 3.1.0.rc3-0.20190725.bebfd7b26

Running inside a docker container and mounting a volume at /var/lib/scylla fails with below error. Previous version 3.0.9 worked fine.

`
running: (['/usr/lib/scylla/scylla_dev_mode_setup', '--developer-mode', '0'],)
running: (['/usr/lib/scylla/scylla_io_setup'],)
/usr/lib/scylla/libexec/scylla_io_setup:88: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(open(os.path.join(conf_dir, "scylla.yaml")))
ERROR:root:/var/lib/scylla/commitlog was not found. Please check the configuration and run scylla_io_setup again.

tuning /sys/devices/pci0000:00/0000:00:1f.0/nvme/nvme1/nvme1n1
tuning: /sys/devices/pci0000:00/0000:00:1f.0/nvme/nvme1/nvme1n1/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:1f.0/nvme/nvme1/nvme1n1/queue/nomerges to 2

failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 17, in <module>
    setup.io()
  File "/scyllasetup.py", line 51, in io
    self._run(['/usr/lib/scylla/scylla_io_setup'])
  File "/scyllasetup.py", line 30, in _run
    subprocess.check_call(*args, **kwargs)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/lib/scylla/scylla_io_setup']' returned non-zero exit status 1.
/scyllasetup.py:42: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(open(os.path.join(conf_dir, "scylla.yaml")))
`

My current workaround is to use a custom docker_entrypoint.py  that creates /var/lib/scylla/commitlog and chown -R scylla:scylla /var/lib/scylla before supervisord spins up processes.

**Comment by avikivity** [comment]
A nasty side effect of user-id virtualization. We should disable the uid checks in docker since the volume usually comes from the host where we have no control over it. The alternative is to use userns-remap, but it is likely to be too complicated to be worth the effort.

**Comment by avikivity** [comment]
Looks like we should revert b1226fb15a5a8f0ac4d37733df3c5ba12d84644c, and instead disable the owner checks on /var/lib/scylla (when running under docker). uid is meaningless in a container, because the filesystem is imported from the host.

**Comment by avikivity** [comment]
Alternatively, adjust the enteypoint like @robertfreund did to chown the volume. This will cause the volume to appear to be owned by a random user at the host level.

**Comment by slivne** [comment]
@avikivity do you want to introduce a specific flag for this or reuse the ```--overprovisioned``` one  it seems not to be related

**Comment by penberg** [comment]
@slivne There's no flag for this. Instead, when Scylla notices it's running as effective user ID zero (`root` which is default for `docker run`), it will just skip the checks.

**Comment by robfreund** [comment]
I was hoping to find this fixed. I have upgraded to 3.3.rc3 and have same error as before. I was hoping to avoid having to roll my own scylla again.

running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '0'],)
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
tuning /sys/devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:5/0:0:5:0/block/sdb
tuning: /sys/devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:5/0:0:5:0/block/sdb/queue/nomerges 2
warning: unable to tune /sys/devices/pci0000:00/0000:00:03.0/virtio0/host0/target0:0:5/0:0:5:0/block/sdb/queue/nomerges to 2

ERROR:root:/var/lib/scylla/commitlog was not found. Please check the configuration and run scylla_io_setup again.

failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 17, in <module>
    setup.io()
  File "/scyllasetup.py", line 61, in io
    self._run(['/opt/scylladb/scripts/scylla_io_setup'])
  File "/scyllasetup.py", line 32, in _run
    subprocess.check_call(*args, **kwargs)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/opt/scylladb/scripts/scylla_io_setup']' returned non-zero exit status 1.
