### ISSUE TITLE
Non-full clustering keys may cause paging or reader recreation to skip over rows

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#4839]
`query::trim_clustering_row_ranges_to()` creates a clusterin range bound which excludes the key (treated as a prefix), so if the key is non-full, we will exclude not just that key, but all keys prefixed by it.

Refs: https://github.com/scylladb/scylla/issues/1446

**Comment by slivne** [comment]
@tgrabiec is this limited to compact tables (like #1416 or true for all cases)

**Comment by tgrabiec** [comment]
Yes, only compact tables can have non-full keys.

**Comment by denesb** [comment]
The problematic code:
https://github.com/scylladb/scylla/blob/595434a5540271f262fcaf77c3295954f77b42f4/query.cc#L101-L104

> If the key is a non-full key, using after_all_prefixed may cause us to skip over some rows, right?
> I think we should use position_in_partition::after_key() here, and fix it to work with prefix keys.

You mean `::after_key()` should null extend non-full prefixes? This would be the simplest solution.

We currently have the following `bound_weight` values:
https://github.com/scylladb/scylla/blob/595434a5540271f262fcaf77c3295954f77b42f4/position_in_partition.hh#L57-L61

Neither would work here with a non-full prefix. `after_all_prefixed` would ignore other clustering rows that are prefixed by the key. `equal` would include all keys that are prefixed by it (including itself). We need to continue *right after* the key.

**Comment by slivne** [comment]
@tgrabiec to make it super clear

"Yes, it's limited to compact tables, only compact tables can have non-full keys."

Only when used by Thrift - if the use is using CQL thats not possible correct ?

**Comment by tgrabiec** [comment]
On Wed, Aug 14, 2019 at 12:43 PM Shlomi Livne <notifications@github.com>
wrote:

> @tgrabiec <https://github.com/tgrabiec> to make it super clear
>
> "Yes, it's limited to compact tables, only compact tables can have
> non-full keys."
>
> Only when used by Thrift - if the use is using CQL thats not possible
> correct ?
>

No, you can create non-full keys via CQL as well.

>

**Comment by tgrabiec** [comment]
On Wed, Aug 14, 2019 at 12:41 PM Botond Dénes <notifications@github.com>
wrote:

> The problematic code:
>
> https://github.com/scylladb/scylla/blob/595434a5540271f262fcaf77c3295954f77b42f4/query.cc#L101-L104
>
> If the key is a non-full key, using after_all_prefixed may cause us to
> skip over some rows, right?
> I think we should use position_in_partition::after_key() here, and fix it
> to work with prefix keys.
>
> You mean ::after_key() should null extend non-full prefixes? This would
> be the simplest solution.
>

Yes, and use before_all_prefixed as the weight. That's what would happen
internally.

Externally, after_key(x) would return a position such that it's greater
than x and smaller than any key larger than x.

We currently have the following bound_weight values:

**Comment by denesb** [comment]
> Yes, and use before_all_prefixed as the weight. That's what would happen
internally.
>
> Externally, after_key(x) would return a position such that it's greater
than x and smaller than any key larger than x.

We might have to introduce a new method for this, because this can only be done for `position_in_partition`, which would introduce an unexpected inconsistency between `position_in_partition::after_key()` and `position_in_partition_view::after_key()` due to the latter not being able to modify the key in-flight (to make it full).

**Comment by tgrabiec** [comment]
That's problematic indeed. I see two ways out: (1) null-extending all clustering_keys which are used as actual keys. (2) introducing a new weight which would treat the key as implicitly null-extended.

**Comment by denesb** [comment]
Created an issue for the more general problem of correctly handling non-full prefix keys: https://github.com/scylladb/scylla/issues/4923.

**Comment by avikivity** [comment]
Will let 3.2 gain some mileage with this fix. It's a bad bug, but limited to compact storage tables and requires non-full keys, so should be very rare.

**Comment by avikivity** [comment]
No 3.2 problems reported with this. Will wait one more week.

**Comment by avikivity** [comment]
Delayed so much it aged out.
