### ISSUE TITLE
Add node update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_add_node_2_test

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#484]
head

commit 5453cfbab75d7a9c968c0226020dfcda5277a028
Merge: cf73413 3a95a9c
Author: Avi Kivity <avi@scylladb.com>
Date:   Wed Oct 21 08:59:42 2015 +0300

    Merge "snapshots: take + clear" from Glauber
    
    "This is the code for taking a snapshot, and clearing a snapshot."

fails

please note you need to pull ccm, dtest to get this results
```
shlomi@localhost~/urchin-dtest (update_cluster_simple_add_node_tests)$ pkill -9 scylla;rm -Rf ~/.dtest/*; KEEP_TEST_DIR=true REUSE_CLUSTER=false DEBUG=true PRINT_DEBUG=true nosetests -v -s update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_add_node_2_test
simple_add_node_2_test (update_cluster_layout_tests.TestUpdateClusterLayout) ... cluster ccm directory: /home/shlomi/.dtest/dtest-b1jr3Y
FAIL

======================================================================
FAIL: simple_add_node_2_test (update_cluster_layout_tests.TestUpdateClusterLayout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/update_cluster_layout_tests.py", line 159, in simple_add_node_2_test
    self.assertEqual(node1_cache_entries + node2_cache_entries,1000, "node1 cache %d node2 cache %d expected total of 1000" % (node1_cache_entries,node2_cache_entries))
AssertionError: node1 cache 1001 node2 cache 539 expected total of 1000
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/shlomi/.dtest/dtest-b1jr3Y
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 54.465s

FAILED (failures=1)


```

The test fails as it seems that when we stream ownership of some partitions we do not remove them from the row cache 

This is problematic consider the following case:
* node 1 has items A,B,C (all in cache)
* node 2 started and gains ownership of item B,C (not deleting them from cache)
* item B is deleted
* node 2 runs a repair and compaction after gc_period - tombstone of B being deleted is lost
* node 2 is removed passing item C
* node 1 receives ownership of item C, yet in the cache it has a non existing item B and will return it on query

**Comment by slivne** [comment]
Given that #527 once implemented is going to cause partitions to be removed during compaction there will no correlation anymore between the cache and the sstables - that is  the cache can contain keys that do not exist in the sstables and are not owned by the node.

How are we going to handle this ?

**Comment by tgrabiec** [comment]
As far as I understand doing #527 alone is just an optimization to ensure that data which is no longer owned doesn't consume disk space. For cache, this will be achieved automatically - partitions which are not queried will eventually get evicted. 

To ensure that partitions not owned by the node are not returned in queries, #527 is not sufficient. Is it some how coupled with token ownership transitions? If not, compaction may complete after the node became not responsible for given partition, leaving a window in which old partitions are still available in old sstables. 

If we take token ownership changes aside, in the read flow it is the coordinator node which ensures that each replica is queried only with a range it is responsible for. I am not sure what's the mechanism which ensures consistency in case of token ownership transitions, @asias ?

**Comment by asias** [comment]
For instance, when we decommission a node, we will make the status of the node to "LEAVING" and gossip it. I am not sure if the code in the read path will take special care of such status of a node.

**Comment by slivne** [comment]
@pdziepak please check what we need todo when we transfer ownership of a range - please share the info before doing any work toward solving this.

**Comment by slivne** [comment]
I have run a small tests on origin using ccm to try and see what happens.

To me it seems that cassandra relies on a nodetool cleanup operation to be executed - if cleanup is not executed then it looses track of ownership and obsolete data can become alive.

The following is a sample test I ran on cassandra to test this out.

   1. ccm create cas-2 --vnodes -n 2 --install-dir=/home/shlomi/urchin-ccm/../cassandra
   1. ccm node1 start
   1. ccm node1 stress write n=1000 -mode cql3 native 
   1. vi ~/.ccm/cas-2/node2/conf/cassandra.yaml (change bootstrap,remove node 127.0.0.2 from seeds)
   1. ccm node1 flush
   1. ccm node1 compact
   1. ccm node2 cqlsh -e "alter table keyspace1.standard1 with gc_grace_seconds=0 ;"
   1. ccm node2 start
   1. ccm node2 cqlsh (select 10 keys and delete them)
   1. ccm node1 cqlsh -e "paging off;select count(*) from keyspace1.standard1;"
```
Disabled Query paging.

 count
-------
   990

```
   1. ccm node2 flush
   1. ccm node2 compact (removes tombstones - can be validated using sstable2json)
   1. ccm node2 stop
   1. ccm node2 start
   1. ccm node2 decommission
   1. ccm node1 cqlsh -e "paging off;select count(*) from keyspace1.standard1;"
```
Disabled Query paging.

 count
-------
   992
```

**Comment by pdziepak** [comment]
I'm not sure we have any bug here at all. `nodetool cleanup` documantation says:

> Cassandra does not automatically remove data from nodes that lose part of their partition range to a newly added node. Run nodetool cleanup on the source node and on neighboring nodes that shared the same subrange after the new node is up and running. Failure to run this command after adding a node causes Cassandra to include the old data to rebalance the load on that node.

So, the resurrection of the data when node regains responsibility over a certain range is sort of expected if the cleanup hasn't been performed. Assuming that we have correct `nodetool cleanup` implementation (do we?) there doesn't seem to be a need to do any other kind of old data removal.

As for invalidating the cache, I've read some of the related origin code and (I admit I may be missing something) the relevant part of the bootstrap looks like this:
1. Bootstrapping node requests streaming of the data it is going to be responsible for.
2. After the streaming is done the node changes its state to "normal" and the others update their information about who's responsible for what in the cluster.
It seems that, as it was already said, it is the storage proxy job to ask nodes only for the ranges they are responsible for).

I also haven't found any relevant here part of the code that would remove from cache data that the node is no longer responsible for. If the above is correct there is no real need to do that, is there?

Does this test pass on Cassandra? (I tried but got `row_cache_entries()` always equal 0, probably something wrong with the setup.)

**Comment by slivne** [comment]
Thanks Pawel I added some additional data based on a test I ran and the
results seem to be the same.

Would cleanup clean the row cache ?

With regards to running this on cassandra - by default row cache is
disabled on cassandra - when creating the test I have tried to enable it
and did not spend to mutch time on it.

So the test seems to be incorrect at this point - and we need a nodetool
cleanup added - yet in my view the cleanup should also update the row cache
(it also aligns with Tomek's original input the cache is just a view of the
sstable data - so if the data is removed from the sstables it should also
be removed from the cache).

Shlomi

**Comment by pdziepak** [comment]
Cleanup seems to be implemented as a special case of compaction and it doesn't invalidate the cache.

Cache is cleaned by StreamReceiveTask on completion of streaming. So when a node is decomissioned, it streams all its data to the node that is going to be responsible for its ranges (possibly a node that has previously owned them) and that node invalidate relevant parts of its cache when the streaming is done.

**Comment by slivne** [comment]
@Asias are we missing this in our streaming implementation ?

Cleanup seems to be implemented as a special case of compaction and it
doesn't invalidate the cache.

Cache is cleaned by StreamReceiveTask on completion of streaming. So when a
node is decomissioned, it streams all its data to the node that is going to
be responsible for its ranges (possibly a node that has previously owned
them) and that node invalidate relevant parts of its cache when the
streaming is done.

—
Reply to this email directly or view it on GitHub
<https://github.com/scylladb/scylla/issues/484#issuecomment-164676081>.

**Comment by asias** [comment]
@pdziepak what code in StreamReceiveTask do you think it is cleaning up the cache?

**Comment by pdziepak** [comment]
StreamReceiveTask.OnCompletionRunnable.run() calls cfs.invalidateRowCache(nonOverlappingBounds).

**Comment by asias** [comment]
@pdziepak what c* version are you looking at. There is no such call in c* 2.1.11 version.

**Comment by pdziepak** [comment]
There is in 2.1.12. See: https://issues.apache.org/jira/browse/CASSANDRA-10341

**Comment by pdziepak** [comment]
Before this fix cache invalidation was in StreamReader.writeRow().

**Comment by asias** [comment]
On Tue, Dec 15, 2015 at 5:03 PM, Paweł Dziepak <notifications@github.com>
wrote:

> Before this fix cache invalidation was in StreamReader.writeRow().
>

OK.  When node1(source) streams data to node2(destination),  the
destination node will invalidate the row cache. The source node is not
invalidated.


-- 
Asias

**Comment by pdziepak** [comment]
On 15 December 2015 at 10:13, Asias He <notifications@github.com> wrote:

> On Tue, Dec 15, 2015 at 5:03 PM, Paweł Dziepak <notifications@github.com>
> wrote:
>
> > Before this fix cache invalidation was in StreamReader.writeRow().
> >
>
> OK. When node1(source) streams data to node2(destination), the
> destination node will invalidate the row cache. The source node is not
> invalidated.
>
>
Yes, that should be sufficient. When bootstraping the node gains
responsibility over some ranges and ask their current owners to stream the
data. After that streaming is done the mapping of ranges to nodes is
updated in the cluster so that node that lost responsibility over a range
doesn't receive such requests anymore. When a node is decommissioned it may
regain responsibility over some ranges (and even after nodetool cleanup it
may still have some stale data in cache) but it will get these ranges via
streaming from the leaving node and after streaming is done invalidate its
cache thus removing any stale data.

**Comment by slivne** [comment]
It may also do that because the streaming code in origin I think is in
sstable level so it creates files on the disk but will not update the cache?

Is out streaming code updating the cache ?, if it is - should it ?

**Comment by asias** [comment]
Yes.  In other words:

1) When a node lost responsibility for certain token ranges, the service_proxy code will never ask it for data for that range. This makes sure even if this node has stale cache it is fine.

 2) When a node gain or regain responsibility for certain token ranges, streaming will be performed, upon receiving of the data, the cache is invalidated.

I think this also cures what @slivne 's issue in the first comment.

**Comment by slivne** [comment]
Well - the existing test is not ok - we will need to change it todo
add_node and then decomission and validate the cache change

Once cleanup will be available we can check the update for sstables ?

**Comment by slivne** [comment]
I have created a different test to test this out 
update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_decommission_node_2_test

It is currently not passing because of #676 once it is closed we can test that this test passes as well.

**Comment by tzach** [comment]
@slivne, @avikivity is this still open?
look like a showstopper.

**Comment by slivne** [comment]
The cache invalidation is already impl and already in


    def simple_decommission_node_2_test(self):
        """
        Test that on decommission row cache entries of non owned
transfeered range are invalidated

        1. Create a cluster with a single node with rf=1,insert data
        2. Check the row cahe can be used as an estimator
        3. Add a new node
        4. Check that all data can be read
        5. Delete all the data
        6. Compact data on new node
        7. Restart new node (it should not have any data including
tombstones)
        8. Decommission the new node
        9. Test if any data exists in the cluster
        """


We have a nother bug that Raphael is handelting related to row marker that
are left that currently block this from being tested end to end
https://github.com/scylladb/scylla/issues/676

So yes this is High yet the patch is in and we can not test without another
bug fix.


There is even a dtest for this

**Comment by slivne** [comment]
rm -Rf ~/.dtest/*;  pkill -9 scylla; export CASSANDRA_DIR=~/scylla; KEEP_TEST_DIR=true DEBUG=true PRINT_DEBUG=true nosetests -v update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_decommission_node_2_test
simple_decommission_node_2_test (update_cluster_layout_tests.TestUpdateClusterLayout) ... ok

----------------------------------------------------------------------
Ran 1 test in 138.067s

OK
