### ISSUE TITLE
It should be possible to install both scylla and scylla-jmx from a single RPM

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#485]
When installing scylla via RPM it should bring the scylla-jmx RPM with it

**Comment by avikivity** [comment]
No it shouldn't.

We can have a mega-rpm that has dependencies, but let's not make everything depend on everything else.

**Comment by tzach** [comment]
More than possible, it should be the default, main path of installation.

**Comment by avikivity** [comment]
Right.  There should be a scylla rpm that pulls in scylla-server and scylla-jmx, and a scylla.service that makes sure they are started and stopped in the correct order via systemd dependencies.

**Comment by zouyonghao** [comment]
And I think there shoud be a offline installtion method.

**Comment by penberg** [comment]
@amnonh We have a ``scylla`` superpackage so I guess we can close the issue?

**Comment by amnonh** [comment]
On Mon, Aug 8, 2016 at 2:49 PM, Pekka Enberg <notifications@github.com>
wrote:

@amnonh <https://github.com/amnonh> We have a scylla superpackage so I
> guess we can close the issue?
>
I think so too
