### ISSUE TITLE
Updates with TTL fail to replicate in a mixed cluster of 3.0 and 3.1

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla#4855]
Reported by @ultrabug via ticket #793

*Installation details*
Scylla version (or git commit hash):
3.0.9 

Platform (physical/VM/cloud instance type/docker): Gentoo

@ultrabug built current master of scylla and tried upgrading a node of his current 3.0.9 staging cluster with it.

It failed with :

Aug 14 14:44:07 scy-st-1-p1 scylla: [shard 17] storage_proxy - Failed to apply mutation from 10.6.18.12#1: std::out_of_range (deserialization buffer underflow)on the master version node 
Aug 14 14:43:58 scy-st-1-p2 scylla: [shard 1] storage_proxy - Failed to apply mutation from 10.6.18.11#24: std::runtime_error (Truncated frame) 
on the other nodes

Logs available in ticket #793

**Comment by ultrabug** [comment]
Thanks for getting the discussion here 

@dyasny just my 2 cents, those autolinks to support ticket using pound are misleading because they point to a GH issue

**Comment by dyasny** [comment]
agreed, I just didn't want to post enterprise ticket links in a public issue

**Comment by tzach** [comment]
@avikivity, please advise

**Comment by slivne** [comment]
we do not allow/test upgrade from 3.0 --> master (3.2), we still need to clear this out

**Comment by avikivity** [comment]
There's nothing in principle that should prevent this, so it's a bug. Question is whether it's a 3.0->3.1 regression or a 3.1->master regresion.

**Comment by slivne** [comment]
Upgrade from 3.0-->3.1 work (at least in all the tests we do).

So I expect its a 3.1 --> master regression but agree it would be nice to
know

**Comment by avikivity** [comment]
We should reproduce with a similar schema (3.0->master), then determine where the problem is.

**Comment by slivne** [comment]
I have tried to reproduce this by downsizing the schema to include all the types that they have ...

[numberly_all_types.cql.txt](https://github.com/scylladb/scylla/files/3694943/numberly_all_types.cql.txt)

I ran a cluster with 3.0.9 and upgraded a single node to 3.1.0.rc8 and did writes in both old and new nodes

I then upgrade the node from 3.1.0.rc8 to master 3b9bf9d448 (so the cluster was one node in 3.09 and another in 3b9bf9d448) and did writes on both nodes and it worked

I also extended the writes to include multiple elements 

```
insert into ks.all_types (timestamp_k, text_k, boolean_k , bigint_k , date_k , smallint_k , blob_k , double_k , float_k , ascii_k , uuid_k , timeuuid_k , int_k , 
                          timestamp_c , text_c , boolean_c , bigint_c , date_c , smallint_c , blob_c , double_c , float_c , ascii_c , uuid_c , timeuuid_c , int_c, 
                          timestamp_v , text_v , boolean_v , bigint_v , date_v , smallint_v , blob_v , double_v , float_v , ascii_v , uuid_v , timeuuid_v , int_v,
                          list_text_v, list_bigint_v, frozen_list_double_v, frozen_list_bigint_v, frozen_list_text, frozen_set_text, set_text, frozen_map_text
) values ('2019-01-01','0',true,0,'2019-01-01',0,0x00,0.0,0.0,'0',now(),now(),0,
          '2019-01-01','0',true,0,'2019-01-01',0,0x00,0.0,0.0,'0',now(),now(),0,
          '2019-01-01','0',true,0,'2019-01-01',0,0x00,0.0,0.0,'0',now(),now(),0,
          ['0','1'],[0,1],[0.0, 1.1],[0, 1],['0', '1'],{'0', '1'},{'0', '1'},{'0':'0', '1':'1'});
```

I am not able to reproduce this (in a simple manner).

to be clear I did not create a schema with all the customer permutations but tried an inclusive schema of everything

**Comment by tarzanek** [comment]
so it seems their problem is between 3.0.10 to 3.1

**Comment by tgrabiec** [comment]
Caused by 93270dd, which changed the representation of gc_clock::duration from 32-bit to 64-bit.

The IDL references it directly (which is also a weakness of our IDL):

```
class expiring_marker stub [[writable]] {
    live_marker lm;
    gc_clock::duration ttl;
    gc_clock::time_point expiry;
};
```

**Comment by ultrabug** [comment]
@tgrabiec this indeed "solves" the problem on my 3.1.0 node that now does not spout any error message any more

BUT one of my 3.0.10 node spams logs with

```
Oct 18 16:41:45 scy-st-1-p2 scylla:  [shard 27] storage_proxy - Failed to apply mutation from 10.6.18.11#8: std::runtime_error (Truncated frame)
```

**Comment by ultrabug** [comment]
Please note that those logs are not present on the 3rd node running 3.0.10...

**Comment by tgrabiec** [comment]
@ultrabug Does it still happen if you wipe-out hinted handoff and commitlog directories on 3.1 (with the server stopped while doing it)?

**Comment by ultrabug** [comment]
@tgrabiec indeed the logs do not come up after dropping commitlog & hints directories!

**Comment by ultrabug** [comment]
So I will keep the 3.1.0 node up & running until tomorrow and monitor how it's going.

So far so good...

If that indeed fixes the case, I'd like to kindly ask for a quick 3.1.1 release please.

**Comment by ultrabug** [comment]
Following-up:

- [x] metrics looking good
- [x] no errors in logs
- [x] cqlsh working good
- [] repair run from scylla-manager

One the repair is done, I'll report back.

Then I'll close support tickets and maintain the patch on my side to deploy on the rest of the cluster in the hope of a soon 3.1.1 (friendly hint for #5190).

**Comment by ultrabug** [comment]
^ repair works (not completed due to scylla-manger being too slow) so proceeding with upgrade on the other nodes

**Comment by ultrabug** [comment]
I reported another issue where a server which is not running a previous version won't restart if the majority of the cluster is running 3.1.0 (logs provided).

Scenario:

- 2 nodes running 3.1.0
- 1 node running 3.0.10

node running 3.0.10 will not restart and stay stuck after log:

`[shard 3] compaction_manager - compaction failed: exceptions::mutation_write_failure_exception (Operation failed for system.compaction_history - received 0 responses and 1 failures from 1 CL=ONE.)`

The failing node would only restart after being upgraded to 3.1.0

**Comment by tgrabiec** [comment]
On Mon, Oct 21, 2019 at 5:16 PM Ultrabug <notifications@github.com> wrote:

> I reported another issue where a server which is not running a previous
> version won't restart if the majority of the cluster is running 3.1.0 (logs
> provided).
>
> Scenario:
>
>    - 2 nodes running 3.1.0
>    - 1 node running 3.0.10
>
> node running 3.0.10 will not restart and stay stuck after log:
>
> [shard 3] compaction_manager - compaction failed:
> exceptions::mutation_write_failure_exception (Operation failed for
> system.compaction_history - received 0 responses and 1 failures from 1
> CL=ONE.)
>
> The failing node would only restart after being upgraded to 3.1.0
>

How many times did this happen?

Can you take a core dump of the node while it hangs?

>

**Comment by ultrabug** [comment]
@tgrabiec did try restart 3 times, every time I had to kill -9 scylla since it didn't want to stop properly

I now have upgraded the node, couldn't wait any longer

**Comment by tgrabiec** [comment]
@ultrabug The issue with restarts doesn't seem related to this bug.

Looks like you hit https://github.com/scylladb/scylla/issues/4458, which caused your old node to auto-stop immediately after booting. compaction failure error was probably due to database stopping concurrently with compaction and rejecting local writes to system.compaction_history (a bug, but benign). The fact that auto-stop is hanging is another bug. To debug that we'd need to have a core dump or a reproducer.

**Comment by ultrabug** [comment]
rgr @tgrabiec thanks

> hope of a soon 3.1.1
and
> friendly hint for #5190

**Comment by amoskong** [comment]
We already enhanced our upgrade test by https://github.com/scylladb/scylla-cluster-tests/pull/1411, then this issue can be easily reproduced by http://jenkins.scylladb.com/job/scylla-staging/job/amos/job/rolling-upgrade-clone-3.1/job/rolling-upgrade-centos7/11/

I just submitted to jobs to verify the issue is really fixed.
- http://jenkins.scylladb.com/job/scylla-3.1/job/rolling-upgrade/job/rolling-upgrade-centos7/163/ (w/o the fix, expected to FAIL)
- http://jenkins.scylladb.com/job/scylla-3.1/job/rolling-upgrade/job/rolling-upgrade-centos7/162/ (fixed scylla, expected to PASS)

**Comment by avikivity** [comment]
Backported everywhere needed.
