### ISSUE TITLE
There should be a way to start both scylla and the jmx in a single command

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#486]
The scylla start script should start the jmx proxy with the correct setting, so each scylla process should have its own jmx proxy.

When multiple scylla processes are starting each should set the jmx proxy to its own API port

**Comment by avikivity** [comment]
scylla-jmx should have its own start script.

**Comment by amnonh** [comment]
I've rename it, can you please reopen?

**Comment by slivne** [comment]
when #504 will be resolved this will not be an issues starting scylla-server will start scylla-jmx
