### ISSUE TITLE
sstables: delete_atomically: misplaced parenthesis in warning message

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4861]
Introduced in commit 024d0a6d49297903a68112c6b1ee2f5b580baf32:

https://github.com/scylladb/scylla/blob/14d40cc659352ef91a5ec4ce9435405868331495/sstables/sstables.cc#L3195

**Comment by bhalevy** [comment]
Fixed with 20083be9f6240bb8fc3bd43cbf207664d57f688f

**Comment by avikivity** [comment]
Backported to 3.1; 3.0 not vulnerable.
