### ISSUE TITLE
Make DTCS/TWCS split partitions based on time during compaction

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4862]
The following issue was filed against Cassandra:
https://issues.apache.org/jira/browse/CASSANDRA-10496:
> To avoid getting old data in new time windows with DTCS (or related, like TWCS), we need to split out old data into its own sstable during compaction.
> 
> My initial idea is to just create two sstables, when we create the compaction task we state the start and end times for the window, and any data older than the window will be put in its own sstable.
> 
> By creating a single sstable with old data, we will incrementally get the windows correct - say we have an sstable with these timestamps:
> 
> [100, 99, 98, 97, 75, 50, 10]
> and we are compacting in window [100, 80] - we would create two sstables:
> [100, 99, 98, 97], [75, 50, 10], and the first window is now 'correct'. The next compaction would > compact in window [80, 60] and create sstables [75], [50, 10] etc.
> 
> We will probably also want to base the windows on the newest data in the sstables so that we actually have older data than the window.

**Comment by denesb** [comment]
This C* Jira issue served as the basis for the timestamp based data segregation issue (https://github.com/scylladb/scylla/issues/2687).

**Comment by bhalevy** [comment]
@denesb so all the follow up work is in #4617 and #4618 right?

**Comment by denesb** [comment]
Correct.

**Comment by raphaelsc** [comment]
@denesb this can be closed now right?

**Comment by denesb** [comment]
Yes.
