### ISSUE TITLE
Safely increase replication factor

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#4867]
Scylla cannot safely increase the replication factor.

If you have 3 replicas, and then suddenly increase it to 5, QUORUMs will potentially fail -- assuming only two replicas had the data.

Situation is even worse for CL=(LOCAL_) ONE, since now the requests have a 40% chance of hitting empty nodes even if the cluster was perfectly repaired before.

A repair surely fixes this, but until the repair is ran, we find ourselves in a fragile place with queries not meeting consistency. Because of that, we're forced to play tricks like adding datacenters just to remove the old DC later , traffic split, etc.

We should have a special operation that:
- calculates which nodes will be the new recipients of data
- start sending new writes to those nodes, akin to how bootstrap currently works
- runs a repair in the background (or similar, streaming) so that those nodes have the data
- and only *then* tell gossip about the change, so the clients can reach the right nodes.

**Comment by tgrabiec** [comment]
Looks similar to https://github.com/scylladb/scylla/issues/2594

**Comment by tzach** [comment]
> Looks similar to #2594

@glommer do we need both issues?

**Comment by glommer** [comment]
no, we can keep just one of them. As long as the resulting issue has my tier tag.

**Comment by slivne** [comment]
duplicate
