### ISSUE TITLE
large rows and cells are only recorded for the MC format

### ISSUE THREAD

**Issue by espindola** [scylladb/scylla#4868]
Currently maybe_record_large_rows and maybe_record_large_cells are only called from sstables/mc/writer.cc.

**Comment by tzach** [comment]
Good catch. At the very least we should document this.

**Comment by slivne** [comment]
doc issue https://github.com/scylladb/scylla-docs/issues/2121

**Comment by espindola** [comment]
So we never want to implement this in older formats?

**Comment by slivne** [comment]
No not needed
