### ISSUE TITLE
accept a separate directory when issuing nodetool refresh

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#487]
Currently nodetool refresh will rescan the sstable directory in the search for new sstables and make them usable at the current node.

This is compatible with Cassandra, so it needs to exist.

The problem, though, is that design is inherently unsafe: when copying the SSTables, one could overwrite existing ones. Even if one checks to see which tables are there and rename accordingly, because the node is still running the generation numbers can increase and eventually reach the ones being copied.

The solution to that is use a separate directory - in addition, not in opposition - to scanning the column family data directory.

This means that tools & scripts expecting to do that that already work for Cassandra will keep working, but we will be able to provide users with a safer solution should they want to.

**Comment by slivne** [comment]
we added the upload directory

e5f0314afd261bb2880f8f62b1f898de959d23a1
```
Author: Raphael S. Carvalho <raphaelsc@scylladb.com>
Date:   Wed May 18 21:50:24 2016 -0300

    db: introduce upload directory for sstable migration
    
    This change is intended to make migration process safer and easier.
    All column families will now have a directory called upload.
    With this feature, users may choose to copy migrated sstables to upload
    directory of respective column families, and call 'nodetool refresh'.
    That's supposed to be the preferred option from now on.
    
    For each sstable in upload directory, refresh will do the following:
    1) Mutate sstable level to 0.
    2) Create hard links to its components in column family dir, using
    a new generation. We make it safe by creating a hard link to temporary
    TOC first.
    3) Remove all of its components in upload directory.
    
    This new code runs after refresh checked for new sstables in the column
    family directory. Otherwise, we could have a generation conflict.
    Unlike the first step, this new step runs with sstable write enabled.
    It's easier here because we know exactly which sstables are new.
    
    After that, refresh will load new sstables found in column family
    and upload directories.
    
    Signed-off-by: Raphael S. Carvalho <raphaelsc@scylladb.com>
```

**Comment by avikivity** [comment]
We need a blog post explaining this, plus an entry in the admin guide to refer to it when talking about migrations.
