### ISSUE TITLE
Scylla crash during shutdown in repair_option_pr_dc_host_test

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4875]
Seen in dtest-release 3.1 test, e.g. [http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/110/artifact/logs-release.2/1566341926518_repair_additional_test.RepairAdditionalTest.repair_option_pr_dc_host_test/](http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/110/artifact/logs-release.2/1566341926518_repair_additional_test.RepairAdditionalTest.repair_option_pr_dc_host_test/)

Core: [node5-ld-linux-x86-64.32693.1566341866.core.gz](http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/110/artifact/logs-release.2/1566341926518_repair_additional_test.RepairAdditionalTest.repair_option_pr_dc_host_test/node5-ld-linux-x86-64.32693.1566341866.core.gz)
Binary: [scylla](http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/lastFailedBuild/artifact/logs-release.2/scylla)

Decoded backtrace:
```
seastar::deferred_action<main::{lambda()#1}::operator()() const::{lambda()#2}::operator()() const::{lambda()#33}>::~deferred_action() [clone .cold.4868] at /jenkins/workspace/scylla-3.1/dtest-release@2/scylla/seastar/include/seastar/util/defer.hh:44
main::{lambda()#1}::operator()() const::{lambda()#2}::operator()() const at /jenkins/workspace/scylla-3.1/dtest-release@2/scylla/main.cc:927
_ZN7seastar20noncopyable_functionIFvvEE17direct_vtable_forIZZNS_5asyncIZZ4mainENKUlvE_clEvEUlvE0_JEEENS_8futurizeINSt9result_ofIFNSt5decayIT_E4typeEDpNS9_IT0_E4typeEEE4typeEE4typeENS_17thread_attributesEOSA_DpOSD_ENUlRZNS4_IS6_JEEESL_SM_SN_SP_E4workE_clESR_EUlvE_E4callEPKS2_ at /jenkins/workspace/scylla-3.1/dtest-release@2/scylla/seastar/include/seastar/core/apply.hh:35
 (inlined by) ?? at /jenkins/workspace/scylla-3.1/dtest-release@2/scylla/seastar/include/seastar/core/apply.hh:43
 (inlined by) ?? at /jenkins/workspace/scylla-3.1/dtest-release@2/scylla/seastar/include/seastar/core/future.hh:1312
 (inlined by) operator() at /jenkins/workspace/scylla-3.1/dtest-release@2/scylla/seastar/include/seastar/core/thread.hh:324
 (inlined by) call at /jenkins/workspace/scylla-3.1/dtest-release@2/scylla/seastar/include/seastar/util/noncopyable_function.hh:71
seastar::thread_context::main() at /jenkins/workspace/scylla-3.1/dtest-release@2/scylla/seastar/build/release/../../include/seastar/util/noncopyable_function.hh:145
 (inlined by) seastar::thread_context::main() at /jenkins/workspace/scylla-3.1/dtest-release@2/scylla/seastar/build/release/../../src/core/thread.cc:317
```
This points at the vicinity of https://github.com/scylladb/scylla/blob/417250607b1ef254d3f1467295742c24eee65574/main.cc#L923-L927

Recently changed in 417250607b1ef254d3f1467295742c24eee65574

**Comment by bhalevy** [comment]
ping @psarna

**Comment by psarna** [comment]
I have no idea how to proceed with this one. I have the following insights that trouble me:
1. Right before the crash, the node printed `terminate called without an active exception`, which, according to what I've read is printed only if an `std::thread` is joinable, but neither joined or detached, and the program exits, which I have no idea how to interpret in case of Scylla...
2. The backtrace informs that the failure occurred in `~future` destructor, which does nothing for a resolved future and prints a warning for a failed future, so it doesn't have many opportunities to segfault.
3. gdb returns a rather alarming frame info:
~~~
(gdb) info frame
Stack level 0, frame at 0x7fb52bbe88d0:
 rip = 0x7fb52c67e7fe in seastar::future<>::~future() (/jenkins/workspace/scylla-3.1/dtest-release/scylla/seastar/include/seastar/core/future.hh:710); saved rip = 0x0
 inlined into frame 1
 source language c++.
 Arglist at unknown address.
 Locals at unknown address, Previous frame's sp in rsp
~~~
What troubles me is `saved_rip = 0x0`. Why would the return address be null? @tgrabiec can it be a result of `seastar::thread`s jumping with `longjmp` and thus confusing `gdb` or does it suggest stack corruption?

**Comment by psarna** [comment]
I'm currently polishing my gdb skills by trying to see if there's anything special in shard1's view_builder instance via gdb, but I'm not sure I'll find anything useful.

**Comment by psarna** [comment]
I've reached I point where I have no idea how to proceed:

I wanted to check how do per-shard instances of view_builder look like, so:
1. I found the address of a static sharded variable I wanted to examine:
~~~
[sarna@localhost benny]$ nm -C scylla  | grep ' b '.*main.*view_builder | grep -v guard
000000000511ec50 b main::{lambda()#1}::operator()() const::{lambda()#2}::operator()() const::view_builder
~~~
2. I examined the contents of the sharded service with gdb, being careful not to try printing futures, as they tend to crash gdb:
~~~
(gdb) set $sharded = (seastar::sharded<db::view::view_builder>*)0x000000000511ec50

(gdb) p *$sharded
$4 = {_instances = {<std::_Vector_base<seastar::sharded<db::view::view_builder>::entry, std::allocator<seastar::sharded<db::view::view_builder>::entry> >> = {
      _M_impl = {<std::allocator<seastar::sharded<db::view::view_builder>::entry>> = {<__gnu_cxx::new_allocator<seastar::sharded<db::view::view_builder>::entry>> = {<No data fields>}, <No data fields>}, _M_start = 0x600001963540, _M_finish = 0x6000019635a0, _M_end_of_storage = 0x6000019635a0}}, <No data fields>}}

(gdb) p sizeof(seastar::sharded<db::view::view_builder>::entry)
$10 = 48

# Entry for shard0 is the first one that vector's _M_start points to, entry for shard1 is the first one + the offset of 48
(gdb) set $vb0_entry = (seastar::sharded<db::view::view_builder>::entry*)0x600001963540
(gdb) set $vb1_entry = (seastar::sharded<db::view::view_builder>::entry*)0x6000019635d0

# vb0_entry and vb1_entry types are seastar::shared_ptr<db::view::view_builder>
(gdb) print $vb0_entry->service
$8 = {_b = 0x0, _p = 0x0}
(gdb) print $vb1_entry->service
$9 = {_b = 0x600000726800, _p = 0x600000726800}
~~~

So, it looks like the instance for shard0 is properly freed, while the instance for shard1 contains garbage - it makes no sense for a `seastar::shared_ptr`, which is the type of `vb1_entry->service`, to have both refcount and data pointing to the same address, and it also looks rather suspicious for a real address.

I have no idea at all how can it be the case, unless I messed up one of the gdb steps.

**Comment by bhalevy** [comment]
@avikivity The crash here: http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/121/artifact/logs-release.2/1567021519769_repair_additional_test.RepairAdditionalTest.repair_option_pr_dc_host_test/
for example does have your fix 417250607b1ef254d3f1467295742c24eee65574
but gdb still barfs on the core dump

**Comment by denesb** [comment]
> I examined the contents of the sharded service with gdb, being careful not to try printing futures, as they tend to crash gdb:

Do `set print static-members no` to avoid `gdb` crashing on printing futures.

**Comment by denesb** [comment]
I'm also downloading the core to have a look.

**Comment by denesb** [comment]
It looks like there was an exception thrown from a destructor.

**Comment by denesb** [comment]
* more specifically from a lambda executed by `~deferred_action()`.

**Comment by psarna** [comment]
Makes sense, I'll verify tomorrow how noexcept `view_builder::stop()` is. It probably needs an extra catch.

**Comment by denesb** [comment]
(thread debugging still doesn't work)

**Comment by denesb** [comment]
The executable doesn't have its interpreter patched:
```
bdenes@localhost:~/Storage/Work/scylla-master-4875
$ file node5-ld-linux-x86-64.32693.1566341866.core 
node5-ld-linux-x86-64.32693.1566341866.core: ELF 64-bit LSB core file, x86-64, version 1 (SYSV), SVR4-style, from 'scylla --library-path /jenkins/workspace/scylla-3.1/dtest-release@2/scylla-dtes', real uid: 800, effective uid: 800, real gid: 1012, effect
ive gid: 1012, execfn: '/jenkins/workspace/scylla-3.1/dtest-release@2/scylla-dtest/../scylla/dynamic_libs/ld-linux-x86-64.so.2', platform: 'x86_64'
bdenes@localhost:~/Storage/Work/scylla-master-4875
$ file scylla
scylla: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=b550fc9ae2305ea00e61067e2940eaa0984c90cb, with debug_info, not stripped
```

**Comment by bhalevy** [comment]
> The executable doesn't have its interpreter patched:
> 
> ```
> bdenes@localhost:~/Storage/Work/scylla-master-4875
> $ file node5-ld-linux-x86-64.32693.1566341866.core 
> node5-ld-linux-x86-64.32693.1566341866.core: ELF 64-bit LSB core file, x86-64, version 1 (SYSV), SVR4-style, from 'scylla --library-path /jenkins/workspace/scylla-3.1/dtest-release@2/scylla-dtes', real uid: 800, effective uid: 800, real gid: 1012, effect
> ive gid: 1012, execfn: '/jenkins/workspace/scylla-3.1/dtest-release@2/scylla-dtest/../scylla/dynamic_libs/ld-linux-x86-64.so.2', platform: 'x86_64'
> bdenes@localhost:~/Storage/Work/scylla-master-4875
> $ file scylla
> scylla: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=b550fc9ae2305ea00e61067e2940eaa0984c90cb, with debug_info, not stripped
> ```

@fruch does scylladb/scylla-ccm#153 take care of this?

**Comment by fruch** [comment]
@bhalevy no it's not changing any files. if we'll use the install.sh it might address it.

**Comment by bhalevy** [comment]
> @bhalevy no it's not changing any files. if we'll use the install.sh it might address it.

We should.  that's scylladb/scylla-ccm#169
