### ISSUE TITLE
scylla ignores SIGTERM if stuck in the "JOINING: waiting for schema information to complete" loop

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#4885]
*Installation details*
HEAD: 698b72b5018868df6a839d08fd24c642db97ffcd
Cluster size: 4

*Description*
Scylla gets stuck in the loop above (sometimes forever if syncing fails for some reason) ignoring SIGTERM and (still) requiring the `kill -9` to shut it down.

Related to https://github.com/scylladb/scylla/issues/4674

IMO the chosen approach that requires explicit "checking at strategic points" and call for `_abort_source.check()` has a built in flaw - an explicit patching of every such point is required.

A more generic and robust approach would be to tag continuations created from the "stop()" flow of each sharded service and interrupt/discard every non-tagged continuation in the main loop after the signal reception.

**Comment by tzach** [comment]
@avikivity ?

**Comment by avikivity** [comment]
@asias please take a look

**Comment by asias** [comment]
I think https://github.com/scylladb/scylla/pull/4697 will help. Since the _abort_source is now available inside storage_service. we can call sleep_abortable(time, _abort_source).

**Comment by avikivity** [comment]
Can you update the patch please?

**Comment by asias** [comment]
Yes, in my queue.

**Comment by asias** [comment]
Updated. Please review.

**Comment by avikivity** [comment]
Ah, you didn't even have to pass the abort_source.

**Comment by avikivity** [comment]
In all active branches.
