### ISSUE TITLE
[feature] add redis protocol for drop-in replacement redis

### ISSUE THREAD

**Issue by rnz** [scylladb/scylla#4887]
A good opportunity to increase popularity and solve user problems would be to add support for the Redis protocol in ScyllaDB. Redis is ugly, its scaling is ugly and ineffective, its looks like a set of crutches.
![image](https://user-images.githubusercontent.com/851927/63593446-b56f3b00-c5bc-11e9-9cf8-0246f1241345.png)

**Comment by dorlaor** [comment]
Actually there is work in progress on the mailing list by @fastio to merge Pedis to Scylla. Since it's a medium term and on going work, I'll close the issue but you are welcome to test Pedis today and also review the patches
