### ISSUE TITLE
Add counters for all types of CQL requests

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#4888]
*Installation details*
HEAD: 698b72b5018868df6a839d08fd24c642db97ffcd

*Description*
Currently these are CQL stats that we have:
```
struct cql_stats {
    uint64_t reads = 0;
    uint64_t inserts = 0;
    uint64_t updates = 0;
    uint64_t deletes = 0;
    uint64_t batches = 0;
    uint64_t statements_in_batches = 0;
    uint64_t batches_pure_logged = 0;
    uint64_t batches_pure_unlogged = 0;
    uint64_t batches_unlogged_from_logged = 0;
    uint64_t rows_read = 0;
    uint64_t reverse_queries = 0;
    uint64_t unpaged_select_queries = 0;

    int64_t secondary_index_creates = 0;
    int64_t secondary_index_drops = 0;
    int64_t secondary_index_reads = 0;
    int64_t secondary_index_rows_read = 0;

    int64_t filtered_reads = 0;
    int64_t filtered_rows_matched_total = 0;
    int64_t filtered_rows_read_total = 0;
};
```

We need to add counters for requests like STARTUP.
The full list of opcodes according to the CQL spec v4 is:
```
      4.1.1. STARTUP
      4.1.2. AUTH_RESPONSE
      4.1.3. OPTIONS
      4.1.4. QUERY
      4.1.5. PREPARE
      4.1.6. EXECUTE
      4.1.7. BATCH
      4.1.8. REGISTER
```

**Comment by tzach** [comment]
@amnonh please consider adding this info to the CQL dashboard 
@vladzcloudius do you think it would be helpful?

**Comment by vladzcloudius** [comment]
On 1/27/21 11:15 AM, Tzach Livyatan wrote:
>
> @amnonh <https://github.com/amnonh> please consider adding this info 
> to the CQL dashboard
> @vladzcloudius <https://github.com/vladzcloudius> do you think it 
> would be helpful?
>

I definitely would.
