### ISSUE TITLE
dist: Ubuntu package does not able to use SCYLLA-VERSION-GEN

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#490]
Currently, Ubuntu package uses statically define version number on debian/changelog (it defined as "0.10-1").
If we dynamically generate debian/changelog just like we are doing on scylla-server.spec.in, but we have problem here.
When we working on master branch, Version will be "development", Release will be $DATE.$GIT_COMMIT, like "scylla-server-development-20151021.769ce84.el7.centos.x86_64.rpm".
However, Debian package system does not accept "development-" as version number, then package build will fail.
I think we need some number for it.

**Comment by penberg** [comment]
@avikivity, ping.

**Comment by avikivity** [comment]
What should we do?  Rename it to 666 or something?

**Comment by syuu1228** [comment]
On a policy manual it says should start a digit, alphabet allowed afterwards.
So maybe 0development is acceptable. Sounds strange though.

"The upstream_version may contain only alphanumerics[36] and the characters . + - : ~ (full stop, plus, hyphen, colon, tilde) and should start with a digit. If there is no debian_revision then hyphens are not allowed; if there is no epoch then colons are not allowed."

https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version

**Comment by slivne** [comment]
@syuu1228  We need to resolve this as deb packages do not contain the corret version and do not contain the git hash - so unless there is a better suggestion - use 0development I can leave with that.
