### ISSUE TITLE
major compaction should wait on background deletes

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4909]
In several cases in distributed testing (dtest) we trigger compaction using `nodetool compact` assuming that when it is done, it is indeed really done.
However, the way compaction is currently implemented in scylla, it may leave behind some background tasks to delete the old sstables that were compacted.

I would like to change major compaction (triggered via the ss::force_keyspace_compaction api)
so it would wait on the background deletes and will return only when they finish.

**Comment by raphaelsc** [comment]
@bhalevy I think we should possibly limit this behavior to major compaction. When doing regular compaction with incremental compaction enabled, we'll have compaction submitting deletion requests at every 2GB of compacted data, on average, which results in compaction being blocked until deletion completes. It's better to allow compaction to proceed in parallel to deletion requests.

**Comment by bhalevy** [comment]
> @bhalevy I think we should possibly limit this behavior to major compaction. When doing regular compaction with incremental compaction enabled, we'll have compaction submitting deletion requests at every 2GB of compacted data, on average, which results in compaction being blocked until deletion completes. It's better to allow compaction to proceed in parallel to deletion requests.

@raphaelsc the synchronization with background deletions happens in table::on_compaction_completion, and passed to compact_sstables as part of the replacer function.
If it's called for each exhausted fragment, should we define a callback to be called when regular compaction is done.  I don't want to synchronize with deletions only for major compaction since I don't want background deletions to accumulate in an unbounded way.

**Comment by raphaelsc** [comment]
On Mon, Feb 17, 2020 at 1:21 PM Benny Halevy <notifications@github.com>
wrote:

> @bhalevy <https://github.com/bhalevy> I think we should possibly limit
> this behavior to major compaction. When doing regular compaction with
> incremental compaction enabled, we'll have compaction submitting deletion
> requests at every 2GB of compacted data, on average, which results in
> compaction being blocked until deletion completes. It's better to allow
> compaction to proceed in parallel to deletion requests.
>
> @raphaelsc <https://github.com/raphaelsc> the synchronization with
> background deletions happens in table::on_compaction_completion, and passed
> to compact_sstables as part of the replacer function.
> If it's called for each exhausted fragment, should we define a callback to
> be called when regular compaction is done.
>
like to wait for all deletions of a compaction to complete? currently, we
do call on_compaction_completion() for each exhausted sstable(s), but
currently we do wait for their deletion to complete.

> I don't want to synchronize with deletions only for major compaction since
> I don't want background deletions to accumulate in an unbounded way.
>
_sstable_deletion_sem guarantees that there's only one deletion request
going on per table in a given shard.

**Comment by bhalevy** [comment]
But they'll accumulate in a queue as background tasks that wait on the _sstable_deletion_sem.
It'd be better to formalize a queue for sstable deletions and let a thread started by the sstable manager flush this queue, then when adding to the queue, limit its length so that the compaction job would wait for the queue to return below the threshold before adding more sstables to delete.
And then wait for the queue to drain when the whole compaction job is completed.
