### ISSUE TITLE
Potential increased write amplification in LCS due to incorrect SSTable demotion 

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#4919]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): b60d201a
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

LCS may incorrectly demote a sstable if there's an ongoing compaction for its table and many sstables are created by memtable flush for example (triggers compaction attempt) in between. The strategy will look for candidates even though parallel is disabled and there's an ongoing compaction, and could incorrectly think high-levels have gone many rounds without any activity, which would later on lead to incorrect demotion, which in turn leads to increased write amplification

**Comment by slivne** [comment]
@bhalevy / @raphaelsc is this a regression ? - if so from which commit ?

**Comment by slivne** [comment]
@bhalevy / @raphaelsc ping

**Comment by raphaelsc** [comment]
Parallel compaction was disabled for LCS since ever, and so this problem was not caused by a regression.

**Comment by slivne** [comment]
@raphaelsc thanks

I am trying to understand when did we add the "LCS may incorrectly demote a sstable  ..." - 
- does this happen in 3.0 ?
- does this happen in 2.3 ?

If the answer is Yes this bug/issue exists in 2.3, 3.0 - then we will tag it for 3.2 and once we have a fix validate if we can backport.

**Comment by raphaelsc** [comment]
On Sun, Sep 8, 2019 at 4:11 AM Shlomi Livne <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> thanks
>
> I am trying to understand when did we add the "LCS may incorrectly demote
> a sstable ..." -
>
>    - does this happen in 3.0 ?
>    - does this happen in 2.3 ?
>
> If the answer is Yes this bug/issue exists in 2.3, 3.0 - then we will tag
> it for 3.2 and once we have a fix validate if we can backport.
>
yes, it can potentially happen in both versions.

**Comment by raphaelsc** [comment]
patch sent to mailing list as: [PATCH v2] sstables/LCS: Fix increased write amplification due to incorrect SSTable demotion

**Comment by avikivity** [comment]
This is only a performance problem in a minor compaction strategy, so not backporting.
