### ISSUE TITLE
Scylla crashes with SIGILL on older processors

### ISSUE THREAD

**Issue by gavrilyuc** [scylladb/scylla#4921]
Scylla version: latest download from docker io
OS: CentOS 7

Logs:

scylla-manager-db    | 2019-08-29 08:02:48,108 INFO RPC interface 'supervisor' initialized
scylla-manager-db    | 2019-08-29 08:02:48,109 CRIT Server 'inet_http_server' running without any HTTP authentication checking
scylla-manager-db    | 2019-08-29 08:02:48,110 INFO supervisord started with pid 11
scylla-manager-db    | 2019-08-29 08:02:49,122 INFO spawned: 'scylla-jmx' with pid 14
scylla-manager-db    | 2019-08-29 08:02:49,135 INFO spawned: 'scylla' with pid 15
scylla-manager-db    | 2019-08-29 08:02:49,152 INFO spawned: 'scylla-housekeeping' with pid 16
scylla-manager-db    | 2019-08-29 08:02:50,158 INFO success: scylla-jmx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scylla-manager-db    | 2019-08-29 08:02:50,158 INFO success: scylla entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scylla-manager-db    | 2019-08-29 08:02:50,158 INFO success: scylla-housekeeping entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
scylla-manager-db    | 2019-08-29 08:02:50,544 INFO exited: scylla (terminated by SIGILL (core dumped); not expected)
scylla-manager-db    | 2019-08-29 08:02:51,558 INFO spawned: 'scylla' with pid 29
scylla-manager-db    | 2019-08-29 08:02:52,127 INFO exited: scylla (terminated by SIGILL (core dumped); not expected)
scylla-manager-db    | Connecting to http://localhost:10000
scylla-manager-db    | Starting the JMX server
scylla-manager-db    | JMX is enabled to receive remote connections on port: 7199
scylla-manager-db    | 2019-08-29 08:02:53,223 INFO spawned: 'scylla' with pid 35
scylla-manager-db    | 2019-08-29 08:02:53,816 INFO exited: scylla (terminated by SIGILL (core dumped); not expected)
scylla-manager-db    | Traceback (most recent call last):
scylla-manager-db    |   File "/usr/lib/scylla/scylla-housekeeping", line 174, in <module>
scylla-manager-db    |     args.func(args)
scylla-manager-db    |   File "/usr/lib/scylla/scylla-housekeeping", line 101, in check_version
scylla-manager-db    |     current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
scylla-manager-db    |   File "/usr/lib/scylla/scylla-housekeeping", line 65, in get_api
scylla-manager-db    |     return get_json_from_url("http://" + api_address + path)
scylla-manager-db    |   File "/usr/lib/scylla/scylla-housekeeping", line 62, in get_json_from_url
scylla-manager-db    |     return json.loads(data.decode('utf-8'))
scylla-manager-db    |   File "/usr/lib64/python2.7/json/__init__.py", line 338, in loads
scylla-manager-db    |     return _default_decoder.decode(s)
scylla-manager-db    |   File "/usr/lib64/python2.7/json/decoder.py", line 366, in decode
scylla-manager-db    |     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
scylla-manager-db    |   File "/usr/lib64/python2.7/json/decoder.py", line 384, in raw_decode
scylla-manager-db    |     raise ValueError("No JSON object could be decoded")
scylla-manager-db    | ValueError: No JSON object could be decoded
scylla-manager-db    | 2019-08-29 08:02:56,312 INFO spawned: 'scylla' with pid 45

**Comment by ashishka** [comment]
Hello! We have a problem with running scylla docker container at the CEntOS 7.6 at the VMware ESXi hypervisor. 
Our VM have 500GB disk, 4 core Intel Xeon, and 16GB RAM. 
We trying to start scylla identically we could see at the scylla doc - https://docs.scylladb.com/operating-scylla/manager/1.3/run-in-docker/#running-with-docker-compose

But always we saw message like this
scylla-manager-db | 2019-08-29 08:02:52,127 INFO exited: scylla (terminated by SIGILL (core dumped); not expected)

But at the other environment (MacOS docker, Cloud like AWS/GCP) - scylla started well.

Our docker-compose file is
```
version: '3'
services:

  scylla-manager:
    image: scylladb/scylla-manager
    container_name: scylla-manager
    depends_on:
      - scylla-manager-db

  scylla-manager-db:
    image: scylladb/scylla:latest
    container_name: scylla-manager-db
```

Can you anyone explain us - what mistake we did ?
Thank you!

**Comment by tzach** [comment]
I ran the latest Scylla docker which seems to work fine
```
 docker run --name some-scylla -d scylladb/scylla
~$ docker exec -it some-scylla cqlsh
Connected to  at 172.17.0.2:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
```
@gavrilyuc can you please check which version is your Docker instance?
"latest" does not always mean the latest on Dockerhub

**Comment by ashishka** [comment]
yep, we too. but at the other env (eq AWS/GCP or MacOS), so, i guess - maybe we need to tune our ESXi + VM with some special parameters ?
this craches for us only at the ESXi, nothing else.

**Comment by ashishka** [comment]
results this action, which we did, looks like this
```
[root@powerbi-gateway test_user]# docker run --name some-scylla -d scylladb/scylla
237c4982e0d3d75ff6a49cda29529b5d4e6550bec6c11e0ff1f17231363a534c

[root@powerbi-gateway test_user]# docker exec -it some-scylla cqlsh
Connection error: ('Unable to connect to any servers', {'172.17.0.2': error(111, "Tried connecting to [('172.17.0.2', 9042)]. Last error: Connection refused")})
[root@powerbi-gateway test_user]# docker --version
Docker version 19.03.1, build 74b1e89
[root@powerbi-gateway test_user]#
```

**Comment by ashishka** [comment]
and we tried run docker container with that docker hub images with identical results
```
scylladb/scylla:latest
scylladb/scylla:3.0.10
scylladb/scylla:3.0.8
scylladb/scylla:2.3.6
```

**Comment by avikivity** [comment]
You need to wait for the server to open port 9042, that doesn't happen immediately.

**Comment by avikivity** [comment]
Ah, SIGILL indicates you are running on a very old CPU. Please post the output of `lscpu`.

**Comment by ashishka** [comment]
Yes, sure.
```
[root@powerbi-gateway test_user]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    1
Core(s) per socket:    2
Socket(s):             2
NUMA node(s):          1
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 15
Model name:            Intel(R) Xeon(R) CPU            5140  @ 2.33GHz
Stepping:              11
CPU MHz:               2333.416
BogoMIPS:              4666.83
Hypervisor vendor:     VMware
Virtualization type:   full
L1d cache:             32K
L1i cache:             32K
L2 cache:              4096K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx lm constant_tsc arch_perfmon pebs bts nopl tsc_reliable nonstop_tsc aperfmperf eagerfpu pni ssse3 cx16 x2apic tsc_deadline_timer hypervisor lahf_lm tsc_adjust dtherm
```
and on this working well
```
bash-3.2$ sysctl -a | grep machdep.cpu
machdep.cpu.max_basic: 13
machdep.cpu.max_ext: 2147483656
machdep.cpu.vendor: GenuineIntel
machdep.cpu.brand_string: Intel(R) Core(TM) i5-2415M CPU @ 2.30GHz
machdep.cpu.family: 6
machdep.cpu.model: 42
machdep.cpu.extmodel: 2
machdep.cpu.extfamily: 0
machdep.cpu.stepping: 7
```

**Comment by avikivity** [comment]
The bad one is a Woodcrest. Scylla requires a Westmere or higher. 

I see it is running under a hypervisor, perhaps you can configure the hypervisor to expose a newer CPU type (if the real CPU is not 13 years old).

**Comment by ashishka** [comment]
Thank you! We will try.

**Comment by avikivity** [comment]
Ok, closing this.

**Comment by avikivity** [comment]
Actually, we should have checked the cpu in the startup script instead of crashing like that, reopening.

**Comment by ashishka** [comment]
Yes, Thank you so much!

**Comment by avikivity** [comment]
We have 

```c++
static bool cpu_sanity() {
#if defined(__x86_64__) || defined(__i386__)
    if (!__builtin_cpu_supports("sse4.2")) {
        std::cerr << "Scylla requires a processor with SSE 4.2 support\n";
        return false;
    }
#endif
    return true;
}
```

But maybe it is called too late.

**Comment by ashishka** [comment]
Any way, we will look to the modern CPU HW, because we need to start scylla )

**Comment by avikivity** [comment]
Fixes a rare situation (13 year old cpu), will let it age out.
