### ISSUE TITLE
Memory used by flat_mutation_readers is not accounted for

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#4928]
Our restricted_reader carefully acounts for memory used by file buffers, but in some workloads (large blobs) memory use be dominated by mutation_fragments. For example, reading a 5MB blob from an sstable will allocate a 5MB mutation_fragment but only a few hundred kilobytes for sstable data buffers.

**Comment by avikivity** [comment]
We might make reader_permit a more general type and pass it to all flat_mutation_readers. After all, mutation_source already passes a reader_resource_tracker everywhere. The base flat_mutation_reader type can account for data in its buffers, more complicated readers (like combining_readers) can account for more.

**Comment by tgrabiec** [comment]
The same problem is mentioned in https://github.com/scylladb/scylla/issues/4176

**Comment by avikivity** [comment]
Duplicate of #4176.
