### ISSUE TITLE
changes_while_node_down_test: There were multiple schema versions

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4947]
scylla version 6c4ad932969749ee132c3a13b3c79328a1c575b5
scylladb/scylla-dtest@2846bff39db09d2cecff0e8e76d1745696484887

[dtest-release/231/testReport/concurrent_schema_changes_test/TestConcurrentSchemaChanges/changes_while_node_down_test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/231/testReport/concurrent_schema_changes_test/TestConcurrentSchemaChanges/changes_while_node_down_test/):
```
Error Message
There were multiple schema versions: '45276701-db67-32f5-a4d1-522db7bff743: [127.0.1.2]\n\n\t\t6dd4829f-e561-3b93-9bfa-a5a8c121f21c: [127.0.1.1]'
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/concurrent_schema_changes_test.py", line 435, in changes_while_node_down_test
    self.validate_schema_consistent(node1)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/concurrent_schema_changes_test.py", line 132, in validate_schema_consistent
    assert num_schemas == 1, "There were multiple schema versions: " + pprint.pformat(schemas)
AssertionError: There were multiple schema versions: '45276701-db67-32f5-a4d1-522db7bff743: [127.0.1.2]\n\n\t\t6dd4829f-e561-3b93-9bfa-a5a8c121f21c: [127.0.1.1]'
```

**Comment by slivne** [comment]
this test has been passing for the last 50 runs 

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/436/testReport/junit/concurrent_schema_changes_test/TestConcurrentSchemaChanges/changes_while_node_down_test/history

closing this issue
