### ISSUE TITLE
install.sh: be consistent about $root/$prefix

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4949]
scylla version 6c4ad932969749ee132c3a13b3c79328a1c575b5

In most case the script uses `$root/$prefix` but in one occasion a path is constructed this way:
`--set-interpreter "$prefix/libreloc/ld.so"`
This needs to be `--set-interpreter "$root/$prefix/libreloc/ld.so"`

**Comment by avikivity** [comment]
What's the user effect? bugs should be about user imparct, not what you want the code to look like.

**Comment by bhalevy** [comment]
> What's the user effect? bugs should be about user imparct, not what you want the code to look like.

@avi it's not about how the code should look like.  How can a user use both `--root` and `--prefix` if in some cases only `$prefix` is used by the prefix and in other cases `$root/$prefix`, for what appears to be the same file. Definitely didn't work for @fruch when he tried to use `install.sh` for ccm.

**Comment by slivne** [comment]
@bhalevy is this fixed ?

**Comment by fruch** [comment]
no it's not,

We still hack install.sh for two things, this is one of them:
https://github.com/scylladb/scylla-ccm/blob/next/ccmlib/scylla_repository.py#L218

**Comment by avikivity** [comment]
@bhalevy $root points to the root filesystem after installation: as if the user will execute "chroot $root" before running anything. $prefix is where the binary ends up in that chroot. So --set-interpreter $root/something doesn't make sense, because you're already in $root when executing.

**Comment by bhalevy** [comment]
@avikivity in ccm we aren't running in chroot.

ccm installs the relocatable package e.g. onto `$HOME/.ccm/scylla-repository/unstable/master/latest/scylla`
with `--root $HOME/.ccm/scylla-repository/unstable/master/latest/scylla --prefix /opt/scylladb`
`install.sh` uses `$prefix` to prepare the `$root/$prefix/bin/scylla` shell script wrapper.
ccm then copies this script to the cluster it builds, e.g. '$HOME/.ccm/scylla-cluster/node1/bin/scylla`
The paths it wants in the script should point into the installation directory, fully qualified.

**Comment by avikivity** [comment]
> @avikivity in ccm we aren't running in chroot.
> 

They you shouldn't use --root. It's for chroot or chroot-like use cases (like preparing a package).

> ccm installs the relocatable package e.g. onto `$HOME/.ccm/scylla-repository/unstable/master/latest/scylla`
> with `--root $HOME/.ccm/scylla-repository/unstable/master/latest/scylla --prefix /opt/scylladb`
> `install.sh` uses `$prefix` to prepare the `$root/$prefix/bin/scylla` shell script wrapper.
> ccm then copies this script to the cluster it builds, e.g. '$HOME/.ccm/scylla-cluster/node1/bin/scylla`
> The paths it wants in the script should point into the installation directory, fully qualified.

ccm should use --prefix $HOME/.ccm/scylla-repository/unstable/master/latest/scylla. I believe copying that_thing/bin/scylla to whereever you like should work, IIRC our relocations use aboslute paths.

**Comment by avikivity** [comment]
(--root says where / is; if it's not where / is, --root will not work for you)

**Comment by bhalevy** [comment]
Can be closed with scylladb/scylla-ccm@b7251e3
