### ISSUE TITLE
mv_populating_from_existing_data_during_node_stop_test: Failed to update materialized view bookkeeping (seastar::no_sharded_instance_exception (sharded instance does not exists))

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4954]
Seen in [scylla-3.1/job/dtest-release/128/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test/](https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/128/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test/):
```
Stacktrace
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-3.1/dtest-release/scylla-dtest/materialized_views_test.py", line 611, in mv_populating_from_existing_data_during_node_stop_test
    self._mv_populating_from_existing_data_during_changes_test('stop node', nodes=4, rf=3, mvs=10, prefill=40000, fail=False)
  File "/jenkins/workspace/scylla-3.1/dtest-release/scylla-dtest/materialized_views_test.py", line 690, in _mv_populating_from_existing_data_during_changes_test
    'mutation_write_timeout_exception', 'Error applying view update to'])
  File "/jenkins/workspace/scylla-3.1/dtest-release/scylla-dtest/materialized_views_test.py", line 328, in _check_errors
    assert False, '\n'.join(list(errors))
'ERROR 2019-09-02 20:46:12,243 [shard 0] view - Failed to update materialized view bookkeeping (seastar::no_sharded_instance_exception (sharded instance does not exists)), continuing anyway.\n
```

[node2.log](https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/128/artifact/logs-release.2/1567457318171_materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_node_stop_test/node2.log):
```
INFO  2019-09-02 20:46:12,243 [shard 0] view - Stopping view builder
INFO  2019-09-02 20:46:12,243 [shard 1] view - Stopping view builder
ERROR 2019-09-02 20:46:12,243 [shard 0] view - Failed to update materialized view bookkeeping (seastar::no_sharded_instance_exception (sharded instance does not exists)), continuing anyway.
```

**Comment by bhalevy** [comment]
@psarna the error looks benign during shutdown.
Can we detect we're shutting down and either not not log it or demote it to a warning in this case?
I'm not sure we can always exclude it in `_mv_populating_from_existing_data_during_changes_test` in dtest.

**Comment by slivne** [comment]
May not be related - yet avi has a pull request pending related to views shutdown https://github.com/scylladb/scylla/pull/4937 - lets review again after this is merged

**Comment by slivne** [comment]
waiting for the backport for avis patch to be merged and then we can check again

**Comment by bhalevy** [comment]
@bhalevy revalidate if reproduced with Avi's patch.

**Comment by bhalevy** [comment]
Last reproduction was in https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/128/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test
that's based on scylla version 623ea5e3d9de240db866d9f8432ee1d96e105395 (`scylla-3.1.0-rc5) which doesn't include the fix (2e1e1392ea4dc0cc641a406807397063d92d6dc1)

Next failure: https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/134/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test/
Shows a different pattern (#4382)

**Comment by bhalevy** [comment]
Reproduced in https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/137/testReport/materialized_views_test/TestMaterializedViews/mv_populating_from_existing_data_during_node_stop_test/
Scylla version 582f3323ac21615dab3dd64692e4aebdae1d31d0

**Comment by psarna** [comment]
I'd say it's a combination of using globals and our complicated startup/shutdown routines. I expect that this error happens because one of our global services (say, migration_manager) is already shut down, while one of the bookkeeping ops still has a continuation that runs `get_local_migration_manager`, which tries to get an instance of an already stopped sharded service, which results in seeing no_sharded_instance_exception. I'm totally fine with degrading this error log to warning, but I also think that it can be solved in dtest by temporarily ignoring this error. In general, it should be fixed by reorganising our shutdown procedures so there are no races, but it won't be easy to do.

**Comment by bhalevy** [comment]
Ref #4384 for the proper shutdown ordering work.

**Comment by nyh** [comment]
This old change is already in 3.3 and 4.0. Removing backport-candidate tag.
