### ISSUE TITLE
fix import logging in perftune.py

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla#4958]
seastar in scylla 3.0 has broken perftune.py
it looks something like this:
```
Aug 29 13:13:27 cassandra scylla_prepare: ERROR: name 'logging' is not defined. Your system can't be tuned until the issue is fixed.
Aug 29 13:13:27 cassandra scylla_prepare: Traceback (most recent call last):
Aug 29 13:13:27 cassandra scylla_prepare: File "/usr/lib/scylla/scylla_prepare", line 69, in <module>
Aug 29 13:13:27 cassandra scylla_prepare: run("{} --options-file /etc/scylla.d/perftune.yaml".format(perftune_base_command()))
Aug 29 13:13:27 cassandra scylla_prepare: File "/usr/lib/scylla/scylla_util.py", line 270, in run
Aug 29 13:13:27 cassandra scylla_prepare: return subprocess.check_call(cmd, shell=shell, stdout=stdout, stderr=stderr)
Aug 29 13:13:27 cassandra scylla_prepare: File "/usr/lib64/python3.6/subprocess.py", line 311, in check_call
Aug 29 13:13:27 cassandra scylla_prepare: raise CalledProcessError(retcode, cmd)
Aug 29 13:13:27 cassandra scylla_prepare: subprocess.CalledProcessError: Command '['/usr/lib/scylla/perftune.py', '--tune', 'disks', '--dir', '/var/lib/scylla/data', '--dir', '/var/lib/scylla/commitlog', '--options-file', '/etc/scylla.d/perftune.yaml']' returned non-zero exit status 1.
Aug 29 13:13:27 cassandra systemd: scylla-server.service: control process exited, code=exited status=1
```
quick fix is to edit
`/usr/lib/scylla/libexec/perftune.py`
and add
`import logging` (ideally after import itertools )

This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by amoskong** [comment]
duplicated with https://github.com/scylladb/scylla/issues/4922
