### ISSUE TITLE
 nodetool removenode api

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#496]
1) remove_node api should take hostid instead of token as the parameter

    "path":"/storage_service/remove_node",
    "name":"token",
    "description":"The token to remove",

2) it seems nodetool does not send the correct parameter to our http api server
$ nodetool removenode bcb4cb9d-b6f4-4189-a84b-405af0f1e374
Failed with /storage_service/remove_node {"message": "Missing mandatory parameter 'token'", "code": 400}

**Comment by slivne** [comment]
@asias , @amnonh is this still open - do we have this covered by a dtest ?

**Comment by tzach** [comment]
Look like this is solved:
```
nodetool removenode 9bf1529d-f6fc-4278-bcf0-2becdcdc1bdc
error: Node /172.31.33.227 is alive and owns this ID. Use decommission command to remove it from the ring
```
The error is a result of #700, but the host is correctly identified

**Comment by slivne** [comment]
using head of scylla

commit 827a4d00106415e80d9d70395db0d60a2dcc366c
Merge: 2c79fe1 2d32195
Author: Avi Kivity <avi@scylladb.com>
Date:   Mon Dec 28 10:24:46 2015 +0200

    Merge "streaming: Invalidate cache upon receiving of stream" from Asias
    
    "When a node gain or regain responsibility for certain token ranges, streaming
    will be performed, upon receiving of the stream data, the row cache
    is invalidated for that range.
    
    Refs #484."

using head of scylla-jmx

commit 0f044e2f476c8370e6673afa24da3e0bb7999f71
Author: Pekka Enberg <penberg@scylladb.com>
Date:   Thu Dec 17 09:26:19 2015 +0200

    Rename "com.cloudius.urchin" package to "com.scylladb.jmx"
    
    Move the Scylla JMX code under "com.scylladb.jmx" package.
    
    Signed-off-by: Pekka Enberg <penberg@scylladb.com>

running test
nosetests -v -s update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_removenode_1_test
passes
