### ISSUE TITLE
Data doesn't drop after TTL is exceeded

### ISSUE THREAD

**Issue by vladamir** [scylladb/scylla#4969]
Hello! I have cluster of 15 nodes and use docker containers with 3.0.7 version. I had table settings `default_time_to_live` in 14 days. Then I disabled Hinted Handoff and increased TTL up to 30 days, now table settings are: 

```
WITH CLUSTERING ORDER BY (id ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': '1', 'compaction_window_unit': 'HOURS'}
    AND compression = {'chunk_length_kb': '64', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 2592000
    AND gc_grace_seconds = 86400
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

And I see, my data doesn't drop from disk (Jul 31):

```
-rw-r--r-- 1 root root  164M Jul 31 20:02 data/sc-node-1/data/stats/clicks-bfd22e30971911e9a09000000000000b/mc-298235-big-Data.db
-rw-r--r-- 1 root root  260M Jul 31 19:09 data/sc-node-1/data/stats/clicks-bfd22e30971911e9a09000000000000b/mc-292083-big-Data.db
-rw-r--r-- 1 root root  259M Jul 31 19:09 data/sc-node-1/data/stats/clicks-bfd22e30971911e9a09000000000000b/mc-298067-big-Data.db
-rw-r--r-- 1 root root  298M Jul 31 19:04 data/sc-node-1/data/stats/clicks-bfd22e30971911e9a09000000000000b/mc-296244-big-Data.db
-rw-r--r-- 1 root root  288M Jul 31 18:12 data/sc-node-1/data/stats/clicks-bfd22e30971911e9a09000000000000b/mc-296745-big-Data.db
```

Now already September, 5th, and passed more than 30 days + gc_grace_seconds. Also expired data is unavailable via CQL - it means TTL works, but files are still on a disk. 

I checked the certain file `mc-298235-big-Statistics.db` with a sstable-tools, `sstable-statistics.py` showed: 

```
"min_timestamp": 1564599514635449,
"max_timestamp": 1564602604443911,
"min_local_deletion_time": 1564599587,
"max_local_deletion_time": 1565812204,
"min_ttl": 1209600,
"max_ttl": 1209600,
```

where `max_timestamp` corresponds to `2019-07-31 19:50:04`, making conclusion it should be removed already. Moreover, `max_ttl` is only 14 days. 

How can I free my disks up?

**Comment by slivne** [comment]
@raphaelsc any logs that can be enabled to view why TWCS is not removing those files ?

**Comment by slivne** [comment]
@vladamir which scylla version ?

**Comment by vladamir** [comment]
> @vladamir which scylla version ?

like I said, I use docker containers with 3.0.7 build version

**Comment by raphaelsc** [comment]
On Thu, Sep 5, 2019 at 9:28 AM Shlomi Livne <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> any logs that can be enabled to
> view why TWCS is not removing those files ?
>

we could set compaction log to debugging level and look for the following
messages: "Checking if candidate of generation", ""Adding candidate of
generation", and "Dropping expired SSTable".

It's worth mentioning that we're probably facing a issue where a sstable
mixed with old and new data prevents a fully expired sstable from being
purged WHERE they overlap. Let's confirm that with the log.

If that's the case, I think we could force TWCS to release disk space by
enabling tombstone compaction

**Comment by slivne** [comment]
@vladamir please provide logs from compaction while setting both `compaction` and `compaction_manager` to trace

```
nodetool setlogginglevel compaction trace
nodetool setlogginglevel compaction_manager trace
```
and provide the logs and we can have a look

**Comment by vladamir** [comment]
@slivne hello! Yes, sure, [these logs for last hour](https://yadi.sk/d/T71_jMivQp4ilw)

**Comment by raphaelsc** [comment]
On Mon, Sep 9, 2019 at 12:01 PM vladamir <notifications@github.com> wrote:

> @slivne <https://github.com/slivne> hello! Yes, sure, these logs for last
> hour <https://yadi.sk/d/T71_jMivQp4ilw>
>

From the log it can be seen that fully expired sstables are not being
removed because there are older, overlapping sstables which prevent them
from being deleted. That could be due to sstables containing both old and
new data, which could happen after repair for example. We fixed it (#2687).
I'd suggest enabling tombstone compaction for TWCS to get rid of as much
expired data as possible. It will look for sstables with more than N% of
droppable data and include it for compaction. Tombstone compaction can be
enabled by setting compaction property tombstone_threshold.

**Comment by vladamir** [comment]
Issue is still open. Some of the SStables were deleted, but only a few. I keep seeing old SStables on a disk. And I see `SSTable max local deletion time: 2147483647` for one of them. It's too long) This is a full output from sstablemetadata:
<details>
<summary>sstablemetadata /var/lib/scylla/data/stats/clicks-bfd22e30971911e9a09000000000000b/mc-303572-big-Data.db</summary>
<pre>
SSTable: /var/lib/scylla/data/stats/clicks-bfd22e30971911e9a09000000000000b/mc-303572-big
Partitioner: org.apache.cassandra.dht.Murmur3Partitioner
Bloom Filter FP chance: 0.010000
Minimum timestamp: 1564732189238786
Maximum timestamp: 1564736196480069
SSTable min local deletion time: 1564732189
SSTable max local deletion time: 2147483647
Compressor: org.apache.cassandra.io.compress.LZ4Compressor
Compression ratio: 0.32022139927141396
TTL min: 0
TTL max: 2592000
First token: -8751242873063049335 (key=1052:260788620)
Last token: 9105688642375689313 (key=156:260789076)
minClustringValues: [5d43eb1d1d267e0001525a0d]
maxClustringValues: [5d43fac4eb7ba5000154501d]
Estimated droppable tombstones: 0.7698264218268914
SSTable Level: 0
Repaired at: 0
Replay positions covered: {}
totalColumnsSet: 75343671
totalRows: 2430441
Estimated tombstone drop times:
1564732211:    345038
1564732275:    326492
1564732340:    343223
1564732405:    341061
1564732470:    363307
1564732534:    366546
1564732598:    364521
1564732674:    418393
1564732750:    308397
1564732812:    301051
1564732880:    383132
1564732958:    401311
1564733030:    321491
1564733092:    274806
1564733150:    295569
1564733218:    427920
1564733287:    335596
1564733356:    390459
1564733433:    455242
1564733510:    525633
1564733592:    581228
1564733663:    463071
1564733720:    415757
1564733775:    345342
1564733829:    380556
1564733894:    481692
1564733980:    770596
1564734059:   1253716
1564734144:   1335142
1564734231:   1323215
1564734319:   1505700
1564734406:   1411518
1564734488:   1262874
1564734562:   1153176
1564734632:   1550939
1564734706:   1521642
1564734779:   1492719
1564734852:   1616706
1564734929:   1740337
1564735006:   1694654
1564735081:   1605793
1564735153:   1520090
1564735216:    543881
1564735301:    446995
1564735379:    363245
1564735441:    304400
1564735509:    398298
1564735573:    262326
1564735628:    322859
1564735697:    383318
1564735787:    526807
1564735860:    616125
1564735928:    608900
1564735990:    551510
1564736045:    483128
1564736100:    503932
1564736162:    672980
1565941807:    254955
1565941856:    192634
1565941912:    284645
1565941975:    279837
1565942037:    282126
1565942096:    272116
1565942154:    289440
1565942221:    340199
1565942290:    253024
1565942354:    251940
1565942417:    280391
1565942483:    283626
1565942543:    231959
1565942601:    264156
1565942664:    257372
1565942727:    259574
1565942782:    211734
1565942836:    304288
1565942900:    296155
1565942963:    265733
1565943028:    328759
1565943089:    323691
1565943154:    409555
1565943217:    337086
1565943276:    420305
1565943337:    380107
1565943401:    363940
1565943464:    359708
1565943530:    386109
1565943605:    703858
1565943675:   1179415
1565943761:   1359693
1565943855:   1430517
1565943948:   1478637
1565944040:   1479592
1565944134:   1461042
1565944225:   1661441
1567327812:    330533
1567327867:    539420
1567327933:    559359
1567328005:    666493
1567328082:    613587
1567328158:    677209
Count               Row Size        Cell Count
1                          0                 0
2                          0                 0
3                          0                 0
4                          0                 0
5                          0                 0
6                          0                 0
7                          0                 0
8                          0                 0
10                         0                 0
12                         0                 0
14                         0                 0
17                         0                 0
20                         0                 0
24                         0                 0
29                         0                 0
35                         0                 0
42                         0                 0
50                         0                 0
60                         0                 0
72                         0                 0
86                         0                 0
103                        0                 0
124                        0                 0
149                        0                 0
179                        0                 0
215                        0                 0
258                        0                 0
310                        0                 0
372                        0                 0
446                        0                 0
535                        0                 0
642                        0                 0
770                        0                 0
924                        0                 0
1109                       0                 0
1331                       0                 1
1597                       0                 1
1916                       0                 0
2299                       0                 0
2759                       0                 0
3311                       0                 0
3973                       0                 0
4768                       0                 0
5722                       0                 0
6866                       0                 0
8239                       0                 1
9887                       0                 3
11864                      0                 4
14237                      0                 0
17084                      1                 0
20501                      1                 2
24601                      0                 1
29521                      0                 1
35425                      0                 5
42510                      0                 0
51012                      0                 1
61214                      0                 4
73457                      0                 0
88148                      0                 0
105778                     0                 0
126934                     0                 0
152321                     3                 0
182785                     5                 0
219342                     0                 0
263210                     0                 0
315852                     3                 6
379022                     1                 7
454826                     2                 5
545791                     1                 4
654949                     3                18
785939                     0                 5
943127                     4                 3
1131752                    0                 7
1358102                    0                 1
1629722                    0                 1
1955666                    0                 1
2346799                    0                 0
2816159                    0                 1
3379391                    0                 6
4055269                    4                 3
4866323                    2                 1
5839588                    6                 0
7007506                    3                 0
8409007                    2                 0
10090808                  18                 0
12108970                   9                 0
14530764                   2                 0
17436917                   6                 0
20924300                   3                 0
25109160                   2                 0
30130992                   0                 0
36157190                   1                 0
43388628                   1                 0
52066354                   0                 0
62479625                   9                 0
74975550                   1                 0
89970660                   0                 0
107964792                  0                 0
129557750                  0                 0
155469300                  0                 0
186563160                  0                 0
223875792                  0                 0
268650950                  0                 0
322381140                  0                 0
386857368                  0                 0
464228842                  0                 0
557074610                  0                 0
668489532                  0                 0
802187438                  0                 0
962624926                  0                 0
1155149911                 0                 0
1386179893                 0                 0
1663415872                 0                 0
1996099046                 0                 0
2395318855                 0                 0
2874382626                 0
3449259151                 0
4139110981                 0
4966933177                 0
5960319812                 0
7152383774                 0
8582860529                 0
10299432635                 0
12359319162                 0
14831182994                 0
17797419593                 0
21356903512                 0
25628284214                 0
30753941057                 0
36904729268                 0
44285675122                 0
53142810146                 0
63771372175                 0
76525646610                 0
91830775932                 0
110196931118                 0
132236317342                 0
158683580810                 0
190420296972                 0
228504356366                 0
274205227639                 0
329046273167                 0
394855527800                 0
473826633360                 0
568591960032                 0
682310352038                 0
818772422446                 0
982526906935                 0
1179032288322                 0
1414838745986                 0
Estimated cardinality: 65
EncodingStats minTTL: 0
EncodingStats minLocalDeletionTime: 1442880000
EncodingStats minTimestamp: 1442880000000000
KeyType: org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.LongType)
ClusteringTypes: [org.apache.cassandra.db.marshal.UTF8Type]
StaticColumns: {}
</pre>
</details>


What can I do else to drop them totally? And also I noticed that now there are more compactions than was before

**Comment by raphaelsc** [comment]
On Mon, Sep 16, 2019 at 3:13 AM vladamir <notifications@github.com> wrote:

> Issue is still open. Some of the SStables were deleted, but only a few. I
> keep seeing old SStables on a disk. And I see SSTable max local deletion
> time: 2147483647 for one of them. It's too long) This is a full output
> from sstablemetadata:
>

That means the sstable contains non-expirable data. Do you know how that
could have happened? Did you change default TTL at some point? or perhaps
your application did that at some point? wrote a piece of data with no TTL
at all?

Such sstables containing non-expirable data can only be worked on with
tombstone compaction, which you already enabled. Note that the sstable is
estimated to contain only 76% of droppable data.

**Comment by vladamir** [comment]
> wrote a piece of data with no TTL at all?

yes, maybe. Is there a way to drop them at all without any kind of "estimation"? Major compaction can help?

**Comment by vladamir** [comment]
> tombstone compaction is the way to go.

Can I run tombstone compaction by force?

**Comment by raphaelsc** [comment]
On Tue, Sep 17, 2019 at 5:25 AM vladamir <notifications@github.com> wrote:

> tombstone compaction is the way to go.
>
> Can I run tombstone compaction by force?
>
Right now, we can't. Need to wait for compaction to run it. I think we
should possibly consider changing when tombstone compaction runs, giving it
more chance to run. Because, right now, it only runs when standard
compaction has nothing to do. So if compaction is busy with all the new
sstables, tombstone compaction will barely have a chance to run. It could
take a long while. I think it could be interesting to add a command for it
in the API. We would issue a compaction job that keeps compacting sstables
that have more than N% of droppable data.

**Comment by vladamir** [comment]
Thank you very much for replies! I think the issue might be closed.
