### ISSUE TITLE
cql_server::stop() doesn't kill existing connections and wait for them

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#498]
so this will likely crash.

http/jmx API will call storage_service::stop_native_transport() which in turn calls cql_server::stop().

**Comment by slivne** [comment]
@asias - what do we do now in Ctrl+C / SIGTERM we are not crashing because of this

**Comment by asias** [comment]
With the following patch, we now kill existing connections and wait for them. So we can now close this one.

```
commit b5cc3ac81c9a8fa3584fea88e6bbcbd5a228f543
Author: Asias He <asias@scylladb.com>
Date:   Fri Nov 13 15:40:18 2015 +0800

    transport: Fix cql server stop

    Abort accept and kill existing connections and wait for them.
```
