### ISSUE TITLE
Implement Change Data Capture

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#4985]
Change Data Capture is a feature that enables users to monitor data in a selected table and get notifications whenever it's changed.

This is a top-level issue for the whole feature which will be implemented in smaller steps:

1. Minimal CDC version that logs only primary key for each change #4986 
2. Logging of mutation itself #4987
3. Logging pre-image of data in the moment just before the change #4988
4. Handling cluster topology changes #4989
5. Handling schema changes of the observed table #4990
6. Making sure schema of CDC Log and CDC Description can't be changed manually by the user #4991
7. Implement post-image of data #4992

**Comment by haaawk** [comment]
Closing this one as the first version of CDC was implemented.

**Comment by tzach** [comment]
Closing this issue
GA level CDC is part of 4.3
