### ISSUE TITLE
Protect CDC Log and CDC Description tables from being modified by the user

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#4991]
This is an enhancement of the minimal version of the Change Data Capture that logs only primary keys. It should make sure that user can't mess up with CDC Log and CDC Description. Those tables should be managed by Scylla itself exclusively.

This is a subtask of #4985.

**Comment by psarna** [comment]
Also, table names that end with `_scylla_cdc_log` can be problematic, so they should either be disallowed in the CQL layer, or creating a table with CDC should fail if it cannot create the cdc subtable because of the name conflict.

**Comment by piodul** [comment]
Fixed in https://github.com/scylladb/scylla/pull/5724, closing
