### ISSUE TITLE
repair_option_pr_multi_dc_test crashes in 3.1 around stop_view_builder

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#4995]
scylla version 2ec036f50c12632b7b28c1ce079b22282649f377
(including acff367ea8c6ff60ba5362e6923e275ae72c6891 that fixes #4589)

[dtest-release/134/artifact/logs-release.2/1567977520184_repair_additional_test.RepairAdditionalTest.repair_option_pr_multi_dc_test/node2.log](https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/134/artifact/logs-release.2/1567977520184_repair_additional_test.RepairAdditionalTest.repair_option_pr_multi_dc_test/node2.log)
```
INFO  2019-09-08 21:17:36,989 [shard 0] view - Stopping view builder
INFO  2019-09-08 21:17:36,989 [shard 1] view - Stopping view builder
INFO  2019-09-08 21:17:37,076 [shard 0] storage_service - Node 127.0.51.6 state jump to normal
terminate called without an active exception
Aborting on shard 0.
Backtrace:
  0x000000000417e822
  0x000000000406bd75
  0x000000000406c075
  0x000000000406c123
  0x00007fd57244002f
  /jenkins/workspace/scylla-3.1/dtest-release/scylla-dtest/../scylla/dynamic_libs/libc.so.6+0x000000000003853e
  /jenkins/workspace/scylla-3.1/dtest-release/scylla-dtest/../scylla/dynamic_libs/libc.so.6+0x0000000000022894
  /jenkins/workspace/scylla-3.1/dtest-release/scylla-dtest/../scylla/dynamic_libs/libstdc++.so.6+0x0000000000090f1a
  /jenkins/workspace/scylla-3.1/dtest-release/scylla-dtest/../scylla/dynamic_libs/libstdc++.so.6+0x000000000009738b
  /jenkins/workspace/scylla-3.1/dtest-release/scylla-dtest/../scylla/dynamic_libs/libstdc++.so.6+0x00000000000973e6
  0x000000000041e301
  0x00000000008789eb
  0x000000000087bdf9
  0x0000000000832ea1

seastar::deferred_action<main::{lambda()#1}::operator()() const::{lambda()#2}::operator()() const::{lambda()#33}>::~deferred_action() [clone .cold.4868] at /jenkins/workspace/scylla-3.1/dtest-release/scylla/seastar/include/seastar/util/defer.hh:44
main::{lambda()#1}::operator()() const::{lambda()#2}::operator()() const at /jenkins/workspace/scylla-3.1/dtest-release/scylla/main.cc:927
_ZN7seastar20noncopyable_functionIFvvEE17direct_vtable_forIZZNS_5asyncIZZ4mainENKUlvE_clEvEUlvE0_JEEENS_8futurizeINSt9result_ofIFNSt5decayIT_E4typeEDpNS9_IT0_E4typeEEE4typeEE4typeENS_17thread_attributesEOSA_DpOSD_ENUlRZNS4_IS6_JEEESL_SM_SN_SP_E4workE_clESR_EUlvE_E4callEPKS2_ at /jenkins/workspace/scylla-3.1/dtest-release/scylla/seastar/include/seastar/core/apply.hh:35
 (inlined by) ?? at /jenkins/workspace/scylla-3.1/dtest-release/scylla/seastar/include/seastar/core/apply.hh:43
 (inlined by) ?? at /jenkins/workspace/scylla-3.1/dtest-release/scylla/seastar/include/seastar/core/future.hh:1312
 (inlined by) operator() at /jenkins/workspace/scylla-3.1/dtest-release/scylla/seastar/include/seastar/core/thread.hh:324
 (inlined by) call at /jenkins/workspace/scylla-3.1/dtest-release/scylla/seastar/include/seastar/util/noncopyable_function.hh:71
seastar::thread_context::main() at /jenkins/workspace/scylla-3.1/dtest-release/scylla/seastar/build/release/../../include/seastar/util/noncopyable_function.hh:145
 (inlined by) seastar::thread_context::main() at /jenkins/workspace/scylla-3.1/dtest-release/scylla/seastar/build/release/../../src/core/thread.cc:317
```

According to @psarna 
> something threw in ~deferred_action, and we're back to the issue of implementations of stop() not being noexcept

#4993 will help figure out what the exception was.

#4875 is a probable cause
So we need to backport #4932 (11b38726d9e258ade87f29cefd19260a6b0caff4) to 3.1

**Comment by slivne** [comment]
backport done d61dd1a9334b9342e00cb49ecfd33ff5de77370d

closing

**Comment by slivne** [comment]
@bhalevy is this a regression from 3.0 ?

**Comment by slivne** [comment]
@bhalevy ping

**Comment by bhalevy** [comment]
Trying [byo/598](https://jenkins.scylladb.com/view/master/job/scylla-master/job/manual-and-scheduled-tests/job/byo_build_tests_dtest/598)

**Comment by bhalevy** [comment]
> Trying [byo/598](https://jenkins.scylladb.com/view/master/job/scylla-master/job/manual-and-scheduled-tests/job/byo_build_tests_dtest/598)

byo dtest doesn't run on 3.0 and https://jenkins.scylladb.com/view/scylla-3.0/job/scylla-3.0/job/scylla-dtest doesn't seem to have any results since May 20 :-/

**Comment by bhalevy** [comment]
I will add this test case to dtest-debug

**Comment by bhalevy** [comment]
> @bhalevy does this reproduce after the addition to dtest-debug - if so great - do we have additional info, if not can we close ?

Sorry, I added a different case to dtest-debug.
Will add this one as well.

**Comment by psarna** [comment]
I assume the issue was not reproduced, since the last update is from October '19?

**Comment by bhalevy** [comment]
> I assume the issue was not reproduced, since the last update is from October '19?

Not AFAIR. Can be closed...
