### ISSUE TITLE
Alternator: GSI: with two regular base columns as keys, update of second one is broken

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5006]
For several reasons (which deserve a separate issue) Cassandra and Scylla only allow an MV to be defined with **one** regular base column as a key column in the view. However, for Alternator, we have to allow two: It is legal in the DynamoDB API to create a GSI where both hash and range keys are regular columns in the base table.

Alternator currently supports this case, by simply bypassing the checks in the CQL layer (which we don't use anyway) and creating these two key columns. And this almost works. But there is still one bug, where if you update the *second* of these columns, Scylla forgets to delete the old rows involved.

We already have an xfailing test, `test_gsi_update_second_regular_base_column`, to reproduce this issue.

@psarna has a working patch for this issue, which he sent titled "[RFC PATCH] view: handle multiple regular base columns in view pk", but it needs further review.

**Comment by psarna** [comment]
I digged my patch out, so it's visible in the bug tracker; also, I added a line which enables a previously xfailed test, which passes with the patch.

**Comment by nyh** [comment]
This patch is already in branches 3.3 and 4.0, so nothing left to backport. Removing backport candidate tag.
