### ISSUE TITLE
Alternator: use scheduling group for request parsing

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5008]
In main.cc, we start the alternator HTTP server with with:

```c++
            alternator_server.init(addr, cfg->alternator_port()).get();
```

But for the two other protocols - CQL and thrift, the startup code looks like:

```c++
            with_scheduling_group(dbcfg.statement_scheduling_group, [] {
                return service::get_local_storage_service().start_native_transport();
            }).get();
```

We should probably run the Alternator server under this "statement_scheduling_group" as well.

**Comment by avikivity** [comment]
Enhancement, not backporting.
