### ISSUE TITLE
config: support setting storage_port changing the inter-node communication port

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#501]
storage_port   (Default: 7000) The port for inter-node communication.

**Comment by slivne** [comment]
@asias 

can we close this

we have this merged:

commit 2c8867c34816258b741dcb8a3b8f9c8a3a5e8a75
Author: Asias He <asias@scylladb.com>
Date:   Wed Oct 28 13:50:31 2015 +0800

    config: Enable storage_port option

**Comment by asias** [comment]
Yes
