### ISSUE TITLE
Writes may fail on a replica soon after boot if keyspace was created while the node was down

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#5011]
Scylla version (or git commit hash): 3.1

Introduced in 7f64a6e, which exposes https://github.com/scylladb/scylla/issues/3760 for all schemas, not only those which have UDTs.

The problem is that table schema deserialization now requires keyspace to be present. If the replica hasn't received schema changes which introduce the keyspace yet, the write will fail.

**Comment by asias** [comment]
Is this backported to 3.1?

**Comment by avikivity** [comment]
@asias yes, 024d156
