### ISSUE TITLE
Running manual operations like nodetool compact will crash if the controller is disabled

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#5016]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

Scylla will crash if we run with the controller disabled and invoke a manual operation, like nodetool compact.

Unfortunately, due to the fact that we still hit bugs with some corner cases in the controller, disabling them is still something we do in some (thankfully rarer and rarer) situations.

**Comment by avikivity** [comment]
Backported to 3.0 and 3.1; removing backport candidate label.
