### ISSUE TITLE
config: support setting broadcast_rpc_address

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#502]
broadcast_rpc_address 
    (Default: unset)note RPC address to broadcast to drivers and other Cassandra nodes. This cannot be set to 0.0.0.0. If blank, it is set to the value of the rpc_address or rpc_interface. If rpc_address or rpc_interfaceis set to 0.0.0.0, this property must be set.

**Comment by tzach** [comment]
@asias is this closed with 7ddf8963 ?

**Comment by asias** [comment]
Yes.
