### ISSUE TITLE
Scylla hangs when shutting down in repair_option_pr_multi_dc_test

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5020]
Scylla version 8517eecc2883945dc56d2fbb49d9f8244ca875bc
Seen in [dtest-release/244/testReport/repair_additional_test/RepairAdditionalTest/repair_option_pr_multi_dc_test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/244/testReport/repair_additional_test/RepairAdditionalTest/repair_option_pr_multi_dc_test/):
```
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/repair_additional_test.py", line 2467, in repair_option_pr_multi_dc_test
    return RepairAdditionalBase._repair_option_pr_multi_dc_test(self)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/repair_additional_test.py", line 838, in _repair_option_pr_multi_dc_test
    self.check_rows_on_node(node, 2000)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/repair_additional_test.py", line 33, in check_rows_on_node
    node.stop(wait_other_notice=True)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 519, in stop
    node.watch_log_for_death(self, from_mark=mark)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 461, in watch_log_for_death
    self.watch_log_for(tofind, from_mark=from_mark, timeout=timeout, filename=filename)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 435, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
TimeoutError: 15 Sep 2019 00:51:03 [node3] Missing: ['127.0.6.1 is now [dead|DOWN]']:
```

[node1.log](https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/244/artifact/logs-release.2/1568508664028_repair_additional_test.RepairAdditionalTest.repair_option_pr_multi_dc_test/node1.log):
```
INFO  2019-09-15 00:40:56,973 [shard 0] init - Signal received; shutting down
INFO  2019-09-15 00:40:56,973 [shard 0] init - stopping compaction manager
INFO  2019-09-15 00:40:56,973 [shard 0] compaction_manager - Asked to stop
INFO  2019-09-15 00:40:56,973 [shard 0] compaction_manager - Stopped
INFO  2019-09-15 00:40:56,973 [shard 1] init - stopping compaction manager
INFO  2019-09-15 00:40:56,973 [shard 1] compaction_manager - Asked to stop
INFO  2019-09-15 00:40:56,973 [shard 1] compaction_manager - Stopped
INFO  2019-09-15 00:40:56,973 [shard 0] init - stopping view builder
INFO  2019-09-15 00:40:56,973 [shard 0] view - Stopping view builder
INFO  2019-09-15 00:40:56,973 [shard 1] view - Stopping view builder
INFO  2019-09-15 00:41:04,359 [shard 0] storage_service - Node 127.0.6.6 state jump to normal
```

**Comment by bhalevy** [comment]
I'm working on a patch to scylla-ccm to kill the stuck node with SIGABRT so we can at least get a coredump in these cases to help analyse the problem.

Cc @espindola 

Refs #4384

**Comment by espindola** [comment]
I tried to reproduce this with

 NOSE_PROCESSES=1 KEEP_TEST_DIR=true CASSANDRA_DIR=$HOME/scylla/scylla/build/debug nosetests  --process-timeout=7200 -v repair_additional_test.py:RepairAdditionalTest.repair_option_pr_multi_dc_t
est

and also with a release build. Both finished successfully, but I got a

seastar - Exceptional future ignored: seastar::rpc::closed_error (connection is closed)

The backtrace passes shared_future, so what I got is probably a false alarm that "[PATCH v3] shared_future: don't warn on broken futures" will fix.

Lets see if this happens again and we manage to get a core dump.

**Comment by slivne** [comment]
closing this issue - if it happens again ... lets reopen (with the core :) ).

**Comment by bhalevy** [comment]
It still happens often when `Stopping view builder`, in a class of dtests including this one.
For example:
https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-debug/lastFailedBuild/artifact/logs-debug.2/1571885797429_repair_additional_test.RepairAdditionalTest.repair_option_pr_dc_host_test/node2.log

**Comment by bhalevy** [comment]
@psarna it is merged now.
I'll update the issue once we have a core dump.

**Comment by psarna** [comment]
Was this issue reproduced since its last update in October?

**Comment by bhalevy** [comment]
> Was this issue reproduced since its last update in October?

Not AFAIR. We can close it.
