### ISSUE TITLE
Alternator: in "Expect" conditional operations, wrong equality check for sets

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5021]
In the handling of Expect (conditional operations), the test for EQ (equality) of set values is wrong: we just compare the stored JSON representation. But because sets do not have order, we can have two different JSON representations for the same set, and wrongly conclude these are different sets.

We have an xfailing test - `test_update_expected_1_eq_set` - to reproduce this bug.

To fix this bug we need to change the EQ implementation to compare sets without regard to item order. This will require parsing the the serialized JSON stored for the value (the second JSON, the one given in the query, is already parsed with the entire query).

A possible optimization of the above is to always keep the stored JSON value sorted in some particular way (e.g., lexicographically). The set will need to be sorted when first assigned, and when modified (e.g., the ADD operation). If we do this we don't need to parse or sort this JSON so the comparison is faster. But I don't know if it's worth optimizing this case. Moreover, we can't do this optimization if we ever change our implementation of sets to use a CRDT instead of serialized JSON.

**Comment by psarna** [comment]
are there any dibs on that one? @dekimir? That's the last xfailing test case we have for `test_expected.py`, I can tackle it if there are no volunteers, but if anyone is interested I'd happily withdraw.

**Comment by nyh** [comment]
It's yours!

**Comment by psarna** [comment]
ok. I'll wait for Dejan to wake up and respond first, just in case he has a solution stored somewhere as a local patch already, given that his https://github.com/scylladb/scylla/pull/5447 touches quite similar code.

**Comment by dekimir** [comment]
I'm awake! :smile: Sadly, I don't have any stashed solution for this, so @psarna have at it!

**Comment by avikivity** [comment]
Alternator is still experimental, so not backporting. Will do so if there is demand.
