### ISSUE TITLE
Alternator: filtering: support additional operators

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5028]
Currently, filtering (in `Query` and `Scan` requests) is only implemented for equality restrictions. We should implement all other restriction kinds as well, inequality restrictions, etc. We also need tests for these cases - they are missing in `test_query.py` and `test_scan.py`.

**Comment by eliransin** [comment]
@dekimir - is this what you implemented recently ?
/cc @nyh

**Comment by dekimir** [comment]
> @dekimir - is this what you implemented recently ?

No, mine was #5034

**Comment by nyh** [comment]
I added `test_query_filter.py` with a comprehensive test suite for the `QueryFilter` feature requested in this issue.
Testing `Scan` would be similar, but probably not necessary to this level of detail.
The tests in `test_query_filter.py` exercise all the parts we implemented and the parts we didn't: 32 tests all pass on DynamoDB, but 21 still xfail on Alternator.

The new tests show that our implementation of the "EQ" operator is in fact correct, but all other operators were not yet implemented. Moreover, "AND"ing several "EQ" conditions works correctly as well, but "OR"ing them is not yet supported.

**Comment by nyh** [comment]
It's not as trivial as I hoped to implement other operators besides EQ:

The implementation is in the `get_filtering_restrictions()` function in `conditions.cc`. The problem is that usually (when GSI/LSI keys are not involved), the check whether "a < 3" really means checking whether "attributes[a] < 3" for the attributes map column. Scylla's existing "restrictions" type currently only offers one type of restriction relevant for map columns, and it is is cql3::restrictions::single_column_restriction::contains, which we can use to implement equality check, but not more. We will need to implement a "map_value_slice" restriction similar to the existing "slice" restriction that we have for atomic columns, to implement LT, GT, etc.

Moreover, this observation also shows we need to expand the test of filtering: Our implementation has two cases - the normal case where the filtered column is implemented as an attribute in a map, and the special case where the filtered column happens to be a real Scylla column. Since "Query" filtering is not allowed on key columns, the existing tests in `test_query_filter.py` do not cover this case. Instead, this case can be covered in on of:
1. GSI/LSI tests, which have an additional indexed column, but then do a Query with a filter on the base table.
2. unlike Query, a Scan does allow filtering on the partition or sort key.
We need to add such tests, testing all the different filtering operators to exercise their implementation.

**Comment by nyh** [comment]
Implementing a "map_value_slice" restriction as described above is significantly more involved than we thought, and will be Alternator-specific:

Remember that in Alternator, attribute values may be of any type - and are therefore put inside the Scylla map, whose value must always have the same type, as a serialized byte array. So the restriction to check whether "attributes[a] < 3" cannot require the value to be a number and compare numbers - it needs to de-serialize the value, and if it is a number compare it to 3. The "contains" restriction is even more complicated: It needs to de-serialize the attribute's value, and do different checks depending on whether the value happened to be a list, set or string.

So we'll probably need one new "single_column_restriction::alternator_restriction" with different parameters (or subclasses) that knows how to do this.

By the way, this deserialization step is similar to what we'll also need for doing a materialized view on attributes from the map (issue #5022)

**Comment by psarna** [comment]
One more way we could consider is *alternator-side filtering*, i.e. implementing this layer not along our regular (CQL) filtering, but in alternator executor - e.g. in `describe_items_visitor`. I'm not really a huge fan of this option, but perhaps it's worth mentioning, since this visitor is precisely when we need to deserialize these alternator-specific values anyway - we might just as well apply some filitering there as well. This layer already works on top of paging, so it's probably not that hard to add. As a bonus, we won't inject weird alternator-specific code into Scylla, especially that alternator's internal representation is theoretically subject to change in the future.

**Comment by dekimir** [comment]
> the restriction to check whether "attributes[a] < 3" cannot require the value to be a number and compare numbers - it needs to de-serialize the value, and if it is a number compare it to 3

The comparison is performed by the `abstract_type` from the column definition.  Maybe you can have an Alternator-specific `abstract_type` that knows how to compare correctly.  The rest of the code is unaffected.

> By the way, this deserialization step is similar to what we'll also need for doing a materialized view on attributes from the map

I thought we already have deserialization code from #5034.

**Comment by nyh** [comment]
@psarna, yes, that's an excellent point. We could indeed do the filtering completely on the Alternator side - when preparing the JSON output of Query or Scan, we could simply leave out some items out of the output. This would simplify **everything** - there will be no need to add restrictions or more deserialization code, and the filtering code will be the same regardless if the filtered column is a key column or non-key attribute - which would save me from the tedious need of writing dozens more tests ;-) So I really like this option. I think it fits Scylla very well (i.e., not require massive changes to Scylla), and fit's DynamoDB's model very well (in DynamoDB, filtering always works as the last step, after you have already paid for the entire read).  

The question is, what would we lose by this approach? Do we lose any performance? At first I thought that maybe the filtering, if done with Scylla's "restrictions", can be pushed to the replica instead of being on the coordinator. But I no longer think it can... Consider that we filter with "a < 10", the filtering cannot be done on the replica side: A replica can't drop an item (row) just because it has a column a=11, because although it has a=11 which doesn't match the filter, another node may have a=8 with a newer timestamp, so overall the item *does* match the filter, and the values on the node where a=11 may matter (it may have new timestamps on other columns!).

So, why do you not like the Alternator-side filtering approach?

**Comment by psarna** [comment]
My initial thought was that the idea of having several filtering implementations happening on different layers sounds like bad design. But the more I think about it, the more it makes sense... Since we already have an alternator-specific serialization layer, it's natural that it's exactly the right place to filter these results as well. It *would* be nice to have one single generic place in the code where we perform filtering, but it's not really possible with our serialization routines. I also initially thought that this solution may have performance overhead, but it's actually no different than coordinator-side filtering we now have for CQL.  So, after giving it more thought, I actually *am* in favor of this idea.

**Comment by nyh** [comment]
Another bug in the current partial implementation: The "Count" output field returns the pre-filter count, while it should return the post-filter count. Wrote a test `test_query_filter_counts` to show that.

**Comment by nyh** [comment]
See also issue #6573 - we have a bug in the sort order of byte arrays (we do them as signed instead of unsigned bytes), and this will also affect filtering and need to be fixed.

**Comment by avikivity** [comment]
Enhancement, no backports.
