### ISSUE TITLE
Alternator: hook to admission control (like CQL does)

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5029]
@gleb-cloudius in commit 1779c3b7f6f80bd81d633bed9f4c27e499e61e56 ("move admission control semaphore from cql server to storage_service") added a feature to allow the different APIs supported by Scylla - CQL, Thrift, and Alternator - to share the same admission control memory pool.

This works by passing around a service permit. Currently we work around the admission control limits by using `empty_service_permit()` everywhere in Alternator (in `mutate()` and `query()` calls) but this is obviously a bad idea, and we need to do it properly and participate in the admission control.

Moreover, if admission control refuses admission of a query, Alternator should return the correct error code as specified by the DynamoDB API - perhaps RequestLimitExceeded or ProvisionedThroughputExceededException. It's better not to return a random internal error - clients may have smarter backoff algorithms if they know this is a rare limiting thing, and not an internal error.

**Comment by nyh** [comment]
Moreover, if admission control refuses admission of a query, Alternator should return the correct error code as specified by the DynamoDB API - perhaps RequestLimitExceeded or ProvisionedThroughputExceededException. It's better not to return a random internal error - clients may have smarter backoff algorithms if they know this is a rare limiting thing, and not an internal error.

**Comment by eliransin** [comment]
@psarna this is the issue.
What I have so far is that it is one thing to hook into admission control and another to actually calculate meaningful admition.

**Comment by nyh** [comment]
Already in branch 4.0. This is a performance improvement, not backporting it to earlier experimental releases.
