### ISSUE TITLE
Alternator: provide sample load-balancing solution

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5030]
In Cassandra or Scylla, client libraries ("drivers") are aware of the cluster's nodes and pick one of the nodes with the overall intention of loading all nodes more-or-less equally. The DynamoDB API is different: The client is normally only aware of one URL (the service "endpoint") and isn't aware of the cluster's individual nodes. It is the server's duty to balance connections to this one URL to many nodes, using one of following two techniques, or a combination of both:

1. DNS load balancing. Experiments on Amazon's DynamoDB show that the DNS server for each DynamoDB published endpoint, such as `dynamodb.us-east-1.amazonaws.com`, resolves to one of several hundreds different IP address, at random. The DNS resolution has a TTL=4, meaning that clients who got stuck with a node that suddenly die, will recover (by switching to a different server node) in 4 seconds. If many clients use this technique, the load on the servers is balanced. Unfortunately if there is just one client machine, it is possible all its connections will be directed to the same node, which is bad. Note also that a connection that is reused for more than 4 seconds will remain connected to the same original server node. This case (one client machine) is unlikely in Amazon's multi-tenant installations, but may become a problem on smaller Scylla installations.

2. IP (or more likely, TCP or even HTTP-level) load balancing. All clients send requests to the same IP address, where a load balancer will direct their requests to a different nodes at random.

We should try to use an existing DNS server and/or HTTP load balancer (e.g., [haproxy](http://www.haproxy.org/) which @psarna has already tried successfully with Alternator) and provide at least an example of how to set them up for Alternator users.

When either a DNS server or TCP / HTTP load balancer is involved, an important issue is the need to reconfigure it automatically when the Scylla cluster configuration changed. This could be as simple as a shell script, which periodically queries Scylla (e.g. via the REST API or CQL protocol?) about the live node list, and if it changes, reconfigures or restarts the load balancer.

**Comment by tzach** [comment]
>  This could be as simple as a shell script, which periodically queries Scylla (e.g. via the REST API or CQL protocol?) about the live node list, and if it changes, reconfigures or restarts the load balancer.

Scylla Manager pings the CQL port every sec and reports (now, to monitoring) if a node is down.
Adding HTTP ping should be straight forward.

Also, this kind of functionality can be added to the LB itself, most include customize Health Check function. For example https://www.haproxy.com/documentation/aloha/10-0/traffic-management/lb-layer7/health-checks/

**Comment by gleb-cloudius** [comment]
Can Scylla answer with an http redirect by itself without using separate proxy?

--
			Gleb.

**Comment by nyh** [comment]
I didn't check whether repsonding to DynamoDB with an HTTP redirect works. I guess it won't work because the driver would need to contain special code to support that feature - but why would it, given that Amazon DynamoDB doesn't use this technique? But maybe it's worth checking to confirm.
Even if it does work, it sounds like a problematic technique, because it means every single new connection will be opened to the same server which will become a single point of failure - and to avoid this single-point-of-failure we'll anyway need to use one of the other two techniques (DNS or HTTP load balancing), and if we use them anyway, why do we also need the HTTP redirect technique?

**Comment by gleb-cloudius** [comment]
If DynamoDB driver uses some kind of generic HTTP client library and not
something NIH it may support all HTTP code properly. By using code 301
(moved permanently, this and all future requests should be directed to
the given URI) we may distribute client equally between nodes. In case
a node that is given as a first connection point fails all nodes
connected to it will fail though, but how haproxy solves the same
problem?

--
			Gleb.

**Comment by nyh** [comment]
For this issue, I'm writing a publicly-accessible document about the various load balancing options.
It will be here:

https://docs.google.com/document/d/1twgrs6IM1B10BswMBUNqm7bwu5HCm47LOYE-Hdhuu_8/edit#heading=h.2uba364pdulv

**Comment by nyh** [comment]
We have a new repository, with load-balancing solutions and instructions: https://github.com/scylladb/alternator-load-balancing/
All that remains to do before closing this issue is to put a link into this repository in `docs/alternator/alternator.md`.

**Comment by avikivity** [comment]
Enhancement, clearing backport candidate label.

**Comment by nyh** [comment]
@avikivity you removed by mistake the "Alternator" label instead of the "Backport candidate" label :-) Fixed it now.
