### ISSUE TITLE
Alternator: "Expect": implement unimplemented operators

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5034]
For the "Expect" parameter (the old-style syntax for conditional operations), we only implemented so far the EQ and BEGINSWITH operators - which were used by the Tic-Toe-Toe demo. We need to implement the rest of the operators: NE, LE, LT, GE, GT, NOT_NULL, NULL, CONTAINS, NOT_CONTAINS, IN, BETWEEN.
All of these operators already have full tests in `test_expected.py` (currently all these tests xfail)

**Comment by nyh** [comment]
Committed patch set by @dekimir adding support for NE, IN, NULL and NOT_NULL.

Operators still remains to be supported: LE, LT, GE, GT, CONTAINS, NOT_CONTAINS.

**Comment by dekimir** [comment]
> Committed patch set by @dekimir adding support for NE, IN, NULL and NOT_NULL.
> 
> Operators still remains to be supported: LE, LT, GE, GT, CONTAINS, NOT_CONTAINS.

BETWEEN also remains to be supported.

**Comment by nyh** [comment]
Committed patch by @dekimir adding support for more operators.
Now the only unimplemented operators remain CONTAINS and NOT_CONTAINS.
