### ISSUE TITLE
Alternator: support KeyConditionExpression

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5037]
In the `Query` operation, we support the older `KeyConditions` parameter to pick the partitions and/or items being queried, but we also need to support the newer `KeyConditionExpression` parameter.

We have the existing xfailing test `test_query_key_condition_expression`, but we probably need more extensive tests for more of `KeyConditionExpression` syntax features.

**Comment by slivne** [comment]
Since this is the "new" syntax and we support the old syntax users can use the old syntax and get the code working

**Comment by nyh** [comment]
In commit 576f80b already in master, I added a comprehensive test for this feature and all (I hope) its various sub-cases and corner cases.
