### ISSUE TITLE
scylla-jmx service does not start when scylla-server service start

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#504]
scylla-jmx service goes down when scylla-server service goes down,
but does not start when scylla-server starts.

Bug or a feature?
It is confusing.

**Comment by slivne** [comment]
this is working on ubuntu,

need to chekc if this can be done via systemd

**Comment by tzach** [comment]
Problem still exists with Scylla 1.2.1 AMI

**Comment by tzach** [comment]
My tests show this issue is solved in Scylla AMI 1.4.1
and scylla-jmx do start when starting scylla-server service
@amnonh can you confirm?

**Comment by amnonh** [comment]
This was solved and confirmed the the rollback patch few weeks ago
