### ISSUE TITLE
Altered nested user type is not noticed

### ISSUE THREAD

**Issue by espindola** [scylladb/scylla#5049]
On 60656d1959f0caa4d313f12cc9d4c8d80ab28618, the following commands

```
CREATE KEYSPACE test_ks WITH REPLICATION = { 'class' : 'SimpleStrategy' , 'replication_factor' : 1 };
use test_ks;
CREATE TYPE foo (
    foo_k int,
);
CREATE TYPE bar (
    bar_k frozen<foo>
);
alter type foo add zed_v int;
CREATE TABLE tbl (
    key int PRIMARY KEY,
    val frozen<bar>
);
insert into tbl (key, val) values (1, {bar_k: {foo_k: 2, zed_v: 3} });
```

Produces the following error:

 Error from server: code=2200 [Invalid query] message="Unknown field 'zed_v' in value of user defined type foo

Thanks to @juliayakovlev for first noticing the issue.

**Comment by espindola** [comment]
This is a regression from 89b2c4ddc592805217ac07410edd04b7de576236

**Comment by roydahan** [comment]
detect by new dtest (not merged yet) -test_alter_inner_udt_by_another_udt

**Comment by espindola** [comment]
Fix at https://github.com/scylladb/scylla/pull/5051

**Comment by bhalevy** [comment]
Let's target backport for 3.1.1

**Comment by avikivity** [comment]
Backported to 3.1; 3.0 not vulnerable.
