### ISSUE TITLE
support auto_bootstrap configuration param

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#505]
In Cassandra auto_bootstrap is use as follow
* true (default): migrate, import, data to itself at boot
* false: does not import data to itself on boot. To use only with a fresh cluster

http://docs.datastax.com/en/cassandra/2.1/cassandra/configuration/configCassandra_yaml_r.html

**Comment by slivne** [comment]
@asias I think we support it - or are we missing something ?

**Comment by asias** [comment]
We support it. And it is default to true.  Ask tzach if we want this
included in scylla.conf.

**Comment by slivne** [comment]
In my view we want to default it to the same default that cassandra has and
include it / not include it in the same manner

**Comment by slivne** [comment]
```
auto_bootstrap  
    (Default: true) This setting has been removed from default configuration. It makes new (non-seed) nodes automatically migrate the right data to themselves. When initializing a fresh cluster without data, add auto_bootstrap: false.
```
