### ISSUE TITLE
Alternator: REST API ping service

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#5050]
Exposing a ping service in the API make it easier for services to check Scylla availability by, for example by a LB.
Example of REST end point: `connectivity/ping/`

**Comment by mmatczuk** [comment]
This could be implemented by Scylla Manager agent.

**Comment by nyh** [comment]
@tzach, good point, I completely missed that - although the DynamoDB API only officially services HTTP **POST** requests (and this is what we do in Alternator as well), Amazon's endpoints actually also serve a **GET /** request on the same port, replying with a trivial always-successful message (and not requiring authentication):
```
$ curl -i https://dynamodb.us-west-2.amazonaws.com
$ curl -i https://dynamodb.us-west-2.amazonaws.com
HTTP/1.1 200 OK
Server: Server
Date: Wed, 18 Sep 2019 12:30:48 GMT
Content-Length: 42
Connection: keep-alive
x-amzn-RequestId: GGM3B162KP9AIS1980QIHVCILRVV4KQNSO5AEMVJF66Q9ASUAAJG
x-amz-crc32: 1920725165

healthy: dynamodb.us-west-2.amazonaws.com
```
We should do the same. It's very easy to implement.

By the way, if the client tries to GET a different URI, the result is an HTTP 404 failure:
```
$ curl -i https://dynamodb.us-west-2.amazonaws.com/aaa
HTTP/1.1 404 Not Found
Server: Server
Date: Wed, 18 Sep 2019 12:32:24 GMT
Content-Length: 272
Connection: keep-alive
x-amzn-RequestId: SAOLOB2HQ8G70R675H9KTUS98FVV4KQNSO5AEMVJF66Q9ASUAAJG
x-amz-crc32: 2548615100

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
  <title>Page Not Found</title>
</head>
<body>Page Not Found</body>
</html>
```

**Comment by psarna** [comment]
I created a trivial commit that fixes the issue, but for simplicity it's rebased on top of my `system_auth.roles`+authorization integration patches, so I'm not sending anything on a list yet.

**Comment by nyh** [comment]
Removing "backport candidate" label. 3.1 does not include Alternator, and 3.2 was branched after this patch. Moreover, this is a feature, not a fix.
