### ISSUE TITLE
Alternator: Read-modify-write operations to the same item are not isolated

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5054]
Currently, read-modify-write (RMW) operations in `UpdateItem`, such as `SET a=b`, `SET a=if_not_exist(a,bal)`, or `SET a=a+1`, are implemented but not **isolated** or **serialized**: If several such operations are done in parallel to the same item, the results may be wrong - for example two concurrent `SET a=a+1` may leave `a` incremented just once - or twice.

A related problem is conditional updates, which are again RMW (read the value, and only if it matches some expectation, do the update).

Alternator currently uses the `maybe_get_previous_item()` function to do the R part of these RMW operations, and it is not protected at all from concurrent operations. We can try all sorts of hacks to improve this in some specific cases, but the general solution will probably involve replacing Scylla's consistency approach with a **leader model** - where only one replica is in charge of leading the writes to a specific item, and this replica can use a local lock to serialize RMW operations on the same item.

**Comment by dorlaor** [comment]
It's beneficial initially to identify these cases and with a configuration
option print a warning on the DB side.
I believe if-not-exist is easy to identify and a=a+1 too. What's the a=b
case ? What's the guarantee origin gives it?

**Comment by nyh** [comment]
I propose that we start to implement RMW operations (cases where maybe_get_previous_item() ends up reading) using Scylla's new LWT code. In the future we can revisit this and use a new leader model or Raft support, but propose we start with the code we're already writing anyway for LWT.

I propose we should do the following:

1. Writes with RMW will always use LWT. This won't actually be the CQL LWT syntax, which isn't powerful enough (it can only do conditional updates, not something like "a=b" or "a=a+1") but rather the underlying C++ code "cas_request" which can pass our function the old value of a row, and let it do some operation on it and return the new value - while ensuring serialization of the whole thing. We will use LOCAL_QUORUM for the commit consistency level.

2. There will be an option determining what writes **without** needing a read (`needs_read_before_write` comes out false) do. If this option is set to "safe", we also use the LWT code but not bother to go through the read step (we still do the serialization). If the option is set to "optimized", we use regular write with CL=LOCAL_QUORUM. The assumption of the "optimized mode" is that the user doesn't mix RMW and writes-only to the same top-level attribute (different top-level attributes will anyway be naturally isolated in Scylla).

3. Reads will always be done normally, without LWT (with CL=ONE or LOCAL_QUORUM, depending on requested consistency of the read). The Jury is still out on whether this is fine, or whether we really need to do the reads through LWT to ideally support failed writes. It will be really great for performance if we could do normal reads. Remember that in DynamoDB, reads are significantly cheaper than writes (a write of an 8KB item costs 40 times more than reading it with eventual consistency!), so hurting their performance will be bad for our cost-performance comparison.

**Comment by dorlaor** [comment]
+1

**Comment by avikivity** [comment]
Major feature, not backporting.
