### ISSUE TITLE
Local mutation application doesn't time-out when some shards have overloaded CPUs

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#5055]
Mutations time-out on replica side when they're blocked on dirty memory, but not when they're blocked before that stage. They may be stuck inside the SMP queue when the target shard is overloaded with work.

That may lead to inefficiency where we waste resources on replication of writes which failed on the coordinator side. See https://github.com/scylladb/scylla/issues/1756 and 5ea235e3e88d0a223a817c8f119bde00b174e00c for more rationale.

If the memtable space and commit log are also not under pressure, timed out writes may be still executed once they are finally dequeued from the SMP queue. This will further waste resources and reduce the availability of the node and make recovery from the overload situation take longer.

Observed in https://github.com/scylladb/scylla/issues/4994

**Comment by slivne** [comment]
For local cross shard I think @avikivity merged t master d481521a2e4318c250ce6a5af775f818e1f0f2a7  that is supposed to help make sure we are not overloading a single shard - does this fix the issue ?

**Comment by tgrabiec** [comment]
@slivne The `smp_service_group` patch doesn't solve this. The queue still forms on the shard of origin, just in a different place - in the `smp_service_group` instead of the SMP queue.

**Comment by gleb-cloudius** [comment]
RPC send queue has a notion of an entry with a timeout. If a timeout was
specified for an rpc call it will create an entry with a timer attached
to it. When the timer expires it removes the entry. SMP queue should
have the same.

--
			Gleb.

**Comment by tgrabiec** [comment]
For queues, we have `expiring_fifo`.

**Comment by gleb-cloudius** [comment]
On Mon, Sep 23, 2019 at 03:14:30AM -0700, Tomasz Grabiec wrote:
> For queues, we have `expiring_fifo`.
> 
We should use it and provide submit_to() with a timeout parameter.

--
			Gleb.

**Comment by avikivity** [comment]
Aged out, no need to backport.
