### ISSUE TITLE
TestMigrationUpgradeSSTables_with_3_0_mc/migrate_sstable_with_user_defined_types_test timed out

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5056]
Seen in [scylla-3.1/job/dtest-release/146/testReport/migration_test/TestMigrationUpgradeSSTables_with_3_0_mc/migrate_sstable_with_user_defined_types_test](http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/146/testReport/migration_test/TestMigrationUpgradeSSTables_with_3_0_mc/migrate_sstable_with_user_defined_types_test/)
With scylla version 024d1563ad61898bb4fe9dfd7219ad3f1d7f5a30
Not sure if this just flakiness or a regression.

[node1.log](http://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/146/artifact/logs-release.2/orphaned/1568750072_migration_test.TestMigrationUpgradeSSTables_with_3_0_mc.migrate_sstable_with_user_defined_types_test/node1.log) show these repeated errors:
```
ERROR 2019-09-17 19:55:10,008 [shard 1] compaction_manager - compaction failed: std::runtime_error (A regular compaction for ks.cf INCORRECTLY used shared sstable /jenkins/workspace/scylla-3.1/dtest-release/scylla/.dtest/dtest-SuCi_o/test/node1/data/ks/cf-08c5f6a0d98511e9aac6000000000001/mc-1-big-TOC.txt. Only resharding work with those!): retrying
```

Cc @espindola due to user defined types

**Comment by espindola** [comment]
From a quick look at the code I don't see how UDT might be responsible for the problem.

The warning is from table::on_compaction_completion where we iterate over sstables_to_remove and check that they belong only to the current shard.

Could the check be moved to the code that adds sstables to sstables_to_remove so that we catch the situation earlier?

I am trying to reproduce the issue and will report back.

**Comment by espindola** [comment]
I have tried multiple runs with debug and release builds, but could not reproduce this.

**Comment by raphaelsc** [comment]
Looks like there's some refresh here. I think the problem may be that we didn't account this shared sstable properly and as a result it was incorrectly selected for regular compaction

**Comment by bhalevy** [comment]
This happened during `node.nodetool("upgradesstables -a")`

**Comment by raphaelsc** [comment]
the issue is that sstable upgrade is including shared sstables, and those should be only worked on by resharding.

**Comment by raphaelsc** [comment]
will cook a patch

**Comment by avikivity** [comment]
Already backported to 3.1, the only vulnerable branch.
