### ISSUE TITLE
Alternator: support parallel Scan

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5059]
We noticed in the past that scanning a large table on one thread doesn't make sense - you need to allow the client to scan different chunks of the table in parallel. See [this blog post](https://www.scylladb.com/2017/02/13/efficient-full-table-scans-with-scylla-1-6/ ) and [this blog post](https://www.scylladb.com/2017/03/28/parallel-efficient-full-table-scan-scylla/). 

The DynamoDB developers made the same observation, and the `Scan` operation provides the [parallel scan](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html#Scan.ParallelScan) feature: The client picks how many "TotalSegments" to divide the scan into, and then runs this number of parallel `Scan` operations, each specifying the same `TotalSegments` and a `Segment` between 0 and `TotalSegments-1`.

We need to implement this parallel scan feature. We should also write a test for it: We should make sure that after we scan all segments, we have seen all items and haven't missed any item - and on the other hand, we shouldn't see any item twice (same item in more than one segment).

**Comment by nyh** [comment]
If we don't implement this feature quickly, we should at least fail the Scan request if TotalSegments is specified and not 1 - so that users who use this unsupported feature will at least know, instead of being ignored.

**Comment by nyh** [comment]
Added a test as described above: test_scan.py::test_scan_parallel. (the test xfails on Alternator, passes on DynamoDB).
Also temporarily added trivial code in `executor::scan()` to fail the `Scan` request if the parameters `Segment` or `TotalSegments` are given (until we have a full implementation of this feature).

**Comment by psarna** [comment]
Side note: CQL could also benefit from this simplified syntax. It's certainly clearer for the user to specify that he wants to query "segment 7 out of 16", than `token(p1, p2, p3) >= -51246677337347 && token(p1, p2, p3) < -13256343463467`, and Scylla would do the split correctly, ensuring that there are no holes and that the ranges are even.

**Comment by nyh** [comment]
I decided to backport this fix to branch 4.0 because this version isn't yet out and this is a relatively simple fix and a feature requested by users, so I think it's worth having it in 4.0 and not waiting for 4.1. Commit dbb9574aa22214662973650d40cbf3a622a6dbfb.
