### ISSUE TITLE
move scylla.yaml from /var/lib/scylla/ to /etc/scylla/

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#506]
Cassandra data is under  `/var/lib/cassandra` and configuration under `/etc/cassandra/cassandra.yaml`
Scylla have both data and configuration at ` /var/lib/scylla/`
Is it better?
On cassandra I can stop the service and clean everything under  `/var/lib/cassandra`  for a fresh restart.
On Scylla, this will remove the configuration.

**Comment by syuu1228** [comment]
This is already fixed at https://github.com/scylladb/scylla/commit/b5bd34c0c2519d3616613bd8e3b5b67924944404
