### ISSUE TITLE
systemd/upstart integration does not restart service on failure

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#507]
To continue serving, we need to auto-restart the server after a crash.

**Comment by slivne** [comment]
@syuu1228  - isn't this already configured

**Comment by syuu1228** [comment]
Well, we disabled before because it inconvenient for debugging. Maybe enable it again just for each release?

**Comment by dorlaor** [comment]
Wasn't this resolved this week through another bug?

**Comment by avikivity** [comment]
No, that was something else.

**Comment by slivne** [comment]
systemd support to restart only on exit code !=0 was merged

commit 1b49c0ce19d22b891f3cd4161cfe2a809ab64c06
Author: Avi Kivity <avi@scylladb.com>
Date:   Sun Feb 14 11:11:43 2016 +0200

    dist: Restart scylla on abnormal termination
    
    Restarting the service can recover from a transient failure.
    
    Fixes #904 (on systemd systems only)
    Message-Id: <1455441103-11963-1-git-send-email-avi@scylladb.com>

Ubuntu #907

**Comment by syuu1228** [comment]
Avi fixed Fedora at https://github.com/scylladb/scylla/commit/1b49c0ce19d22b891f3cd4161cfe2a809ab64c06, and I fixed Ubuntu at https://github.com/scylladb/scylla/commit/5a213341a4821990f9c3b72ae17ac9b92c9479a3 so please close it.
