### ISSUE TITLE
oversized allocation warnings during internal PCI DSS vulnerability scan

### ISSUE THREAD

**Issue by scavara** [scylladb/scylla#5075]
*Installation details*
Scylla version (or git commit hash): `2.3.6-0.20190817.d71836fef`
Cluster size: 6
OS (): CentOS

During an internal PCI DSS (https://docs.tenable.com/nessus/Content/ScanAndPolicyTemplates.htm?Highlight=internal%20pci) scan on one of the cluster nodes where client had session timeouts, but also "seastar_memory - oversized allocation" warnings on the scanned node.

[trace_decoded.txt](https://github.com/scylladb/scylla/files/3635457/trace_decoded.txt)

**Comment by slivne** [comment]
all backtraces have from "thrift_server", you can disable the thrift port via ```start_rpc : false ``` in scylla.yaml 

If following that you still find issues - please update and we will be happy to help

**Comment by slivne** [comment]
3.0.X includes 6bf4a73d887bf8463b8543190f8ff3b2d6770b34

Consider to upgrade
