### ISSUE TITLE
Table's backlog tracker may go wild after resharding

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#5077]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): a09479e63cd4fd
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Table's backlog tracker goes wild because it accounts for sstables that belong to more than one shard and it cannot do anything about them. That's because there's a special tracker for resharding operations and table's backlog is only about regular compaction.

**Comment by bhalevy** [comment]
`[RFC PATCH] table: Don't account for shared SSTables in compaction backlog tracker` on ML

**Comment by avikivity** [comment]
Resharding is rare enough that it's not worth the risk to backport.
