### ISSUE TITLE
scylla nodetool gossipinfo does not match c*

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#508]
=== with scylla ===
$ nodetool -p 7100  gossipinfo
127.0.0.1
  generation:1446001292
  heartbeat:102
  0:NORMAL,8251763528961471825;-9147358554612963965;5334343410266177046
  1:906
  2:cfdcf77d-cb52-341b-81c0-b633c119f0a6
  3:datacenter1
  4:rack1
  5:2.1.8
  8:127.0.0.1
  11:0
  12:d56deb66-80c0-430e-89c1-ab9765698a72

127.0.0.2
  generation:1446001300
  heartbeat:78
  0:NORMAL,-8662120869268300396;-6320239659584118281;903070659414180367
  1:66236
  2:cfdcf77d-cb52-341b-81c0-b633c119f0a6
  3:datacenter1
  4:rack1
  5:2.1.8
  8:127.0.0.2
  11:0
  12:df999aec-f645-4d7e-8de6-8521f273e700

=== with c* cluster ===

nodetool -p 7100  gossipinfo
/127.0.0.1
  generation:1446000877
  heartbeat:630
  SEVERITY:0.0
  RELEASE_VERSION:2.1.8-SNAPSHOT
  HOST_ID:df708d27-4ed0-493c-b020-3d8c21965229
  DC:datacenter1
  LOAD:52848.0
  STATUS:NORMAL,-1139428872328849340
  SCHEMA:6403a0ff-f93b-3b1f-8c35-0a8dc85a5b66
  NET_VERSION:8
  RACK:rack1
  RPC_ADDRESS:127.0.0.1
/127.0.0.2
  generation:1446000877
  heartbeat:627
  SEVERITY:0.0
  RELEASE_VERSION:2.1.8-SNAPSHOT
  DC:datacenter1
  HOST_ID:b0d5496a-a41b-48c4-806e-d9164bceb7e4
  LOAD:52830.0
  STATUS:NORMAL,-1027710716370203666
  SCHEMA:6403a0ff-f93b-3b1f-8c35-0a8dc85a5b66
  NET_VERSION:8
  RACK:rack1
  RPC_ADDRESS:127.0.0.2

**Comment by slivne** [comment]
amnon, please compare this to cassandra 2.1.X

**Comment by tzach** [comment]
@amnonh any updates?

**Comment by slivne** [comment]
@amnonh is this fixed ? or are there still missing items

**Comment by amnonh** [comment]
It's fixed

**Comment by asias** [comment]
@amnonh it seems we still have difference for the node ip (the extra "/")

=== scylla ===
$ nodetool -p 7100 gossipinfo
127.0.0.1

=== cassandra === 
nodetool -p 7100 gossipinfo
/127.0.0.1
