### ISSUE TITLE
big_table_with_ttls_test AssertionError: Expected 100000 rows in the big partition, but received 98974

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5084]
Scylla version b4cf429aab0407422818460f7714eef3232714b2
Seen in [next/1190/testReport/junit/migration_test/TTLWithMigrate/big_table_with_ttls_test](https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/1190/testReport/junit/migration_test/TTLWithMigrate/big_table_with_ttls_test):
```
Error Message
Expected 100000 rows in the big partition, but received 98974
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/case.py", line 367, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/next/scylla-dtest/migration_test.py", line 933, in big_table_with_ttls_test
    '{scylla_big_partition_count}'.format(**locals()))
  File "/usr/lib64/python2.7/unittest/case.py", line 460, in assertTrue
    raise self.failureException(msg)
AssertionError: Expected 100000 rows in the big partition, but received 98974
```

**Comment by bhalevy** [comment]
Reproduced in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/1358/testReport/junit/migration_test/TTLWithMigrate/big_table_with_ttls_test/

Since this was seen on next, and apparently no on master dtest-release,
maybe the test is sensitive to timing on slow test machines.

**Comment by bhalevy** [comment]
TTLs are supposed to be in the [1800, 3600] range, and the test log doesn't support rows expiring...

**Comment by slivne** [comment]
dtest fixed
