### ISSUE TITLE
ScyllaDB can't run on ZFS

### ISSUE THREAD

**Issue by rnz** [scylladb/scylla#5094]
When I try to run scylladb - have next error:
```
Sep 24 14:29:36 host1 scylla[679]:  [shard 0] seastar - Could not open file at /etc/scylla/scylla.yaml. Does your filesystem support O_DIRECT?: std::experimental::filesystem::v1::__cxx11::file
Sep 24 14:29:36 host1 scylla[679]:  [shard 0] init - Could not read configuration file /etc/scylla/scylla.yaml: std::experimental::filesystem::v1::__cxx11::filesystem_error (error system:22, I
Sep 24 14:29:36 host1 scylla[679]:  [shard 0] seastar - Exiting on unhandled exception: std::experimental::filesystem::v1::__cxx11::filesystem_error (error system:22, Invalid argument)
```
*Installation details*
```# apt-cache policy scylla-server
scylla-server:
 Installed: 3.0.10-0.20190815.b3bfd8c08-1~stretch (edited) 
Cluster size: 1
OS: Debian 9.11
Kernel: 4.15.18-9-pve #1 SMP PVE 4.15.18-30 (Thu, 15 Nov 2018 13:32:46 +0100) x86_64 GNU/Linux
FS: ZFS (ZoL)
# apt-cache policy zfs-initramfs
zfs-initramfs:
 Installed: 0.7.12-pve1~bpo1
```

**Comment by raphaelsc** [comment]
On Tue, Sep 24, 2019 at 1:04 PM RNZ <notifications@github.com> wrote:

> When I try to run scylladb - have next error:
>
> Sep 24 14:29:36 host1 scylla[679]:  [shard 0] seastar - Could not open file at /etc/scylla/scylla.yaml. Does your filesystem support O_DIRECT?: std::experimental::filesystem::v1::__cxx11::file
> Sep 24 14:29:36 host1 scylla[679]:  [shard 0] init - Could not read configuration file /etc/scylla/scylla.yaml: std::experimental::filesystem::v1::__cxx11::filesystem_error (error system:22, I
> Sep 24 14:29:36 host1 scylla[679]:  [shard 0] seastar - Exiting on unhandled exception: std::experimental::filesystem::v1::__cxx11::filesystem_error (error system:22, Invalid argument)
>
>
ZFS is double buffer so direct io cannot be supported. Workaround it by
setting scylla's relaxed-dma parameter.

**Comment by slivne** [comment]
@rnz closing this issue since raphael provided a workaround (we highly recommend using XFS and this is what most customer use).

**Comment by edisonch** [comment]
how to do scylla dma params to satisfied zfs again? could you please elaborate

**Comment by raphaelsc** [comment]
> how to do scylla dma params to satisfied zfs again? could you please elaborate

use param --relaxed-dma. don't recommend it though due to performance reasons. XFS is our recommendation.
