### ISSUE TITLE
upgradesstables should wait until all sstables are upgraded one way or another

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5100]
As @slivne noted, with the fix for #5056:
> When nodetool upgradesstable ends the user assumes all tables have been upgraded - this will not be true anymore since shared sstables will not be upgraded
>
> are we supposed to return an error at the end - signalling that not all sstables have been upgraded?

@avikivity:
> Good point. We should wait until all sstables are upgraded one way or another (via direct upgrade, compaction, or resharding).

**Comment by slivne** [comment]
- As a start we can upgrade what we can and return a failure as the shared sstables  have not been upgraded 
- If the operations returns a cause we can specify the specific reason.
- The workaround for this is to check on the filesystem if all files have been upgraded or not.

**Comment by slivne** [comment]
Scylla now reshards sstables from upload / on boot before they are used - as such there are no "active" sstables (that are eligibile for upgrade) that are shared.

So this can be closed/.
