### ISSUE TITLE
Paged query cannot return more than 2^32 rows

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#5101]
A simple query

    SELECT * FROM tab

Will not return more than 2^32 rows.

See: https://issues.apache.org/jira/browse/CASSANDRA-14683

We have an equivalent problem, except we use unsigned integers, so we stop after 4 billion rows.

**Comment by avikivity** [comment]
The fix should be simple, add an extra 32-bit field and use it as an extension of the original paging_state::get_remaining(). If it is missing (query that was originated on an old server) we can assume 0.

**Comment by slivne** [comment]
We better align with the solution that C* selects to make sure driver and applications are compatible

**Comment by denesb** [comment]
The paging state is an opaque blob, the driver doesn't care what we put in it and hence how we solve the problem.

**Comment by amoskong** [comment]
> The fix should be simple, add an extra 32-bit field and use it as an extension of the original paging_state::get_remaining(). If it is missing (query that was originated on an old server) we can assume 0.

After added an extra 32-bit filed, our new limitation will be 2**64 rows?
