### ISSUE TITLE
Allow any type to be casted to itself

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#5102]
*Installation details*
Scylla version (or git commit hash): 425cc0c1049cb98678e6e87a8e5a2c7396719215

When trying to cast a type to itself Scylla rejects the query:
```
select cast(mailing_list_content_id as uuid) from member_statistics limit 1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="org.apache.cassandra.db.marshal.UUIDType cannot be cast toorg.apache.cassandra.db.marshal.UUIDType"`
```
Casting the type to itself doesn't really make sense but it is harmless. This kind of query can happen as a result of a schema alter statement that is not followed by updating all the select statements, or just because whoever writes the query doesn't know the type of the column. In any case the resulting error message is very confusing and is unnecessary.

**Comment by avikivity** [comment]
Minor annoyance (can be avoided by not casting), not backporting.
