### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by MimikFc7** [scylladb/scylla#5117]
Hello! i try compile your sources and have error without logs and info
Killed signal terminated program cc1plus
[44/280] CXX build/release/sstables/sstables.o
ninja: build stopped: subcommand failed.

tell me please where i can find logs and understand error?

**Comment by espindola** [comment]
MimikFc7 <notifications@github.com> writes:

> Hello! i try compile your sources and have error without logs and info
> Killed signal terminated program cc1plus
> [44/280] CXX build/release/sstables/sstables.o
> ninja: build stopped: subcommand failed.
>
> tell me please where i can find logs and understand error?

My guess is that gcc is running out of memory. I would suggest trying to
run "ninja -j<smaller number>".

Cheers,
Rafael

**Comment by MimikFc7** [comment]
16gb ram and 8core not enough ?

**Comment by espindola** [comment]
MimikFc7 <notifications@github.com> writes:

> 16gb ram and 8core not enough ?

2gb per core is probably a bit low unfortunatelly. I would try "ninja -j4".

Cheers,
Rafael

**Comment by MimikFc7** [comment]
okm thanks i do, compile go to next stem, wait!
