### ISSUE TITLE
Load in  nodetool info should contain unit

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#512]
=== with c* ===

$ nodetool info

ID                     : df708d27-4ed0-493c-b020-3d8c21965229
Gossip active          : true
Thrift active          : true
Native Transport active: true
Load                   : 118.98 KB
Generation No          : 1446109462
Uptime (seconds)       : 19
Heap Memory (MB)       : 46.90 / 495.00
Off Heap Memory (MB)   : 0.00
Data Center            : datacenter1
Rack                   : rack1
Exceptions             : 0
Key Cache              : entries 6, size 448 bytes, capacity 24 MB, 17 hits, 26 requests, 0.654 recent hit rate, 14400 save period in seconds
Row Cache              : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, NaN recent hit rate, 0 save period in seconds
Counter Cache          : entries 0, size 0 bytes, capacity 12 MB, 0 hits, 0 requests, NaN recent hit rate, 7200 save period in seconds
Token                  : (invoke with -T/--tokens to see all 256 tokens)

=== with scylla === 

$  nodetool info

ID                     : 61cdea04-33f6-49d0-8543-35cf2e94d55d
Gossip active          : true
Thrift active          : false
Native Transport active: true
Load                   : 261032.0
Generation No          : 1446109649
Uptime (seconds)       : 45
Heap Memory (MB)       : 217.79 / 3438.50
Off Heap Memory (MB)   : 2.13
Data Center            : datacenter1
Rack                   : rack1
Exceptions             : 0
Key Cache              : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, 0.000 recent hit rate, 0 save period in seconds
Row Cache              : entries 9, size 9 bytes, capacity 1.97 MB, 14 hits, 29 requests, 0.500 recent hit rate, 0 save period in seconds
Counter Cache          : entries 0, size 0 bytes, capacity 0 bytes, 0 hits, 0 requests, 0.000 recent hit rate, 0 save period in seconds
Token                  : (invoke with -T/--tokens to see all 768 tokens)

**Comment by tzach** [comment]
Good catch

**Comment by amnonh** [comment]
patch is on the way

**Comment by slivne** [comment]
@amnonh did you patch this - is this still open ?

**Comment by amnonh** [comment]
it's closed
