### ISSUE TITLE
nodetool refresh during adding new node causes write timeouts 

### ISSUE THREAD

**Issue by bentsi** [scylladb/scylla#5120]
*Installation details*
Scylla version (or git commit hash): `3.1.0.rc8-0.20190925.d7fc7bcf9`
Cluster size: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-06430761396e594ee [eu-west-1]
Test config: [longevity-2TB-4days-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/branch-3.1/test-cases/longevity/longevity-2TB-4days-authorization-and-tls-ssl-1dis-2nondis-nemesis.yaml)
Scenario (running in parallel): 

1. terminate and replace Nemesis during add node
2. nodetool refresh on another node

During refresh we see failed writes
![image](https://user-images.githubusercontent.com/5269241/65832851-4f1fbb80-e2d2-11e9-9384-5de5a9157640.png)

Load going down
![image](https://user-images.githubusercontent.com/5269241/65832889-e127c400-e2d2-11e9-9981-50c9b6bd7489.png)

Cassandra stress get overloaded exceptions
```
< t:2019-09-26 20:31:09,681 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.81.221]: WARN  20:31:04,997 Host ip-10-0-170-178.eu-west-1.compute.internal/10.0.170.178:9042 is overloaded.
< t:2019-09-26 20:31:09,683 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.81.221]: com.datastax.driver.core.exceptions.OverloadedException: Queried host (ip-10-0-170-178.eu-west-1.compu
te.internal/10.0.170.178:9042) was overloaded: Too many in flight hints: 10486526
< t:2019-09-26 20:31:09,683 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.222.247]: com.datastax.driver.core.exceptions.TransportException: [ip-10-0-114-255.eu-west-1.compute.internal/1
0.0.114.255:9042] Connection has been closed
< t:2019-09-26 20:31:09,683 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.81.221]: com.datastax.driver.core.exceptions.OverloadedException: Queried host (ip-10-0-170-178.eu-west-1.compu
te.internal/10.0.170.178:9042) was overloaded: Too many in flight hints: 10485960
< t:2019-09-26 20:31:09,684 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.222.247]: com.datastax.driver.core.exceptions.OverloadedException: Queried host (ip-10-0-170-178.eu-west-1.comp
ute.internal/10.0.170.178:9042) was overloaded: Too many in flight hints: 10485960
< t:2019-09-26 20:31:09,685 f:remote.py       l:642  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.81.221]: WARN  20:31:03,993 Host ip-10-0-170-178.eu-west-1.compute.internal/10.0.170.178:9042 is overloaded
```

Grafana snapshot:
https://snapshot.raintank.io/dashboard/snapshot/pjtf4zQ9JMlzAVPmKQy174I9l08TLB98?orgId=2

**Comment by bhalevy** [comment]
@denesb can you please take a look?

**Comment by denesb** [comment]
The information in the snapshot is not enough to determine what is causing the issue, it just contains more symptoms. We see writes blocked on dirty and heavy eviction of the cache. The snapshot is just an interactive screenshot, I can't switch to shard mode, expand the time-range, or see other metrics. Can we dump the prometheus database when failures happen? Would it be too big?

**Comment by slivne** [comment]
@bentsi how can we upload the run info in hydra ?

**Comment by slivne** [comment]
@bentsi ping

**Comment by slivne** [comment]
@bentsi ping

**Comment by slivne** [comment]
closing this issue - old stable - if this reproduces please provide full run information so metrics can be pulled and issue analyzed
