### ISSUE TITLE
Compiler error when building AMI

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#5122]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 12aa310b929
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Unbounded number of jobs can lead to the following error:

 -I build/release/gen -I seastar -I seastar/build/release/gen  -c -o build/release/database.o database.cc
g++-7.3: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.

Extend dist/ami/build_ami.sh to allow user to specify number of jobs.

**Comment by slivne** [comment]
closing this issue - we have moved to build ami's in a different manner
