### ISSUE TITLE
querier_cache: population is mis-accounted

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#5123]
Versions: 3.1, master (c9aae13faecf470f480378c47af1bf2eaa3a8cc7).

```
(gdb) p $db->_querier_cache._entries._M_impl._M_node._M_size 
$108 = 83
(gdb) p $db->_querier_cache._stats
$109 = {lookups = 0, misses = 0, drops = 0, time_based_evictions = 8157, resource_based_evictions = 101295, memory_based_evictions = 0, population = 38}
```
The two should be equal. Also seen population counts that under-flowed.

**Comment by avikivity** [comment]
Maybe an exceptional path that caused miss-accounting? Accounting should take place in the same place we add/remove from the cache.

**Comment by denesb** [comment]
The problem was found to be entries that are evicted immediately on insert. These were not added to the population but were subtracted upon eviction nevertheless. Patch with the fix is already on the list.

**Comment by avikivity** [comment]
Already backported, removing backport candidate label.
