### ISSUE TITLE
incrementally add sstable readers during single partition reads

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#5124]
Scylla version (or git commit hash): master(c9aae13faecf470f480378c47af1bf2eaa3a8cc7)

We need a mechanism, similar to https://github.com/scylladb/scylla/issues/1935 for single partition reads. Currently, the combined reader will open all sstables that contain the read partition. If the partition is huge this could mean dozens of sstables will be read parallelly. Combined with the stateful queries this means that reads from such large partitions will put a large pressure on the memory allocator.

**Comment by avikivity** [comment]
I don't see how it's possible to do this for a multi-row query without temporary storage.

For single-row reads, we have #324.

**Comment by denesb** [comment]
Can't we use the promoted index for this? This would require an index read before before/when adding the sstable to the selector which might be difficult to integrate though.

**Comment by denesb** [comment]
It is an index read we are going to do anyway when reading the sstable.

**Comment by tgrabiec** [comment]
I think we should increase the granularity of sstable's range (indicated by first_key and last_key) from `partition_key`  to `(partition_key, clustering_key)` and adjust `incremental_selector` and friends to work with higher granularity.

**Comment by avikivity** [comment]
> Can't we use the promoted index for this? This would require an index read before before/when adding the sstable to the selector which might be difficult to integrate though.

We can, if we have reason to expect that this partition's rows will be disjoint across sstables (or a subset of all sstables). In the general case, we don't, and can expect the combined reader to consume from all participating sstables.

**Comment by tgrabiec** [comment]
Actually, `(partition_key, position_in_partition)` to account for tombstones and static rows. A partition with a partition tombstone should be accounted as `(pk, before_all_rows)`.

**Comment by avikivity** [comment]
> I think we should increase the granularity of sstable's range (indicated by first_key and last_key) from `partition_key` to `(partition_key, clustering_key)` and adjust `incremental_selector` and friends to work with higher granularity.

This would allow breaking an sstable mid-partition for LCS (and ICS), but this issue is for single partition reads.

**Comment by tgrabiec** [comment]
> > I think we should increase the granularity of sstable's range (indicated by first_key and last_key) from `partition_key` to `(partition_key, clustering_key)` and adjust `incremental_selector` and friends to work with higher granularity.
> 
> This would allow breaking an sstable mid-partition for LCS (and ICS), but this issue is for single partition reads.

It would solve the problem for single-partition reads as well, wouldn't it? Just like current incremental selector design solves it for single-ring reads.

**Comment by avikivity** [comment]
Suppose first_key is (A;ck=3) and last_key is (C;ck=7) but we're reading key B. The information in first_key and last_key doesn't give us anything.

We should revive the column min/max thing though, it can help with TWCS.

**Comment by tgrabiec** [comment]
> Suppose first_key is (A;ck=3) and last_key is (C;ck=7) but we're reading key B. The information in first_key and last_key doesn't give us anything.
> 
> We should revive the column min/max thing though, it can help with TWCS.

I thought that the problem in this issue is that we read from non-overlapping sstables (generated by repair or LCS) as if they all overlapped. My suggestion helps with that. If the sstables actually overlap, then yes it won't help with that.

**Comment by avikivity** [comment]
LCS sstables cannot overlap since LCS won't stop mid-partition (IIRC). That's bad and your solution would fix that.

Repair sstables generally come from different vnodes and so wouldn't contain the same partition, so the bloom filter and existing first/last key fixes should be sufficient.

**Comment by denesb** [comment]
In the actual case (https://github.com/scylladb/scylla/issues/5111) that made me open this proposal, the sstable were user written. This was of course a particular workload, whose commonness in the wild I have no idea of.

**Comment by avikivity** [comment]
User-loaded sstables, all with one key, are super-uncommon.

I guess this can happen if someone is writing a really huge partition. In this case, each memtable (and the resulting sstables) will contain the same partition key. Whether those partitions are disjoint in the clustering key range is another matter.

**Comment by denesb** [comment]
Yes. So it seems this is doable but not worth it. We should just fix our memory accounting to prevent OOMing in those rare cases where this particular write pattern does happen.
