### ISSUE TITLE
How install scylladb on Mac?

### ISSUE THREAD

**Issue by andirey** [scylladb/scylla#5125]
I tried to install from "Source" on Mac community edition and get error for this step:

sudo ./install-dependencies.sh

./install-dependencies.sh: line 20: /etc/os-release: No such file or directory
seastar/install-dependencies.sh: line 20: /etc/os-release: No such file or directory
Your system () is not supported by this script. Please install dependencies manually.

Please, help to pass this stage correctly
Thanks

**Comment by denesb** [comment]
Scylla can only be built and ran on Linux, Mac is not supported.

**Comment by andirey** [comment]
RE: Scylla can only be built and ran on Linux, Mac is not supported.
> Understand. Despite my desire to use Scylla - it seems Cassandra will be more acceptable choice as it's very friendly in setup on Mac. Hope to know when Scylla will be on Mac.

**Comment by denesb** [comment]
There is no theoretical obstacle for that, someone just needs to do the work of porting seastar -- the framework Scylla is built on -- to Mac. As the only use-case is development and all devs are on Linux the demand is low, but of course patches are welcome. :)

**Comment by tzach** [comment]
@andirey note that you can easily run Scylla, for functional evaluation, on Mac as Docker container
https://hub.docker.com/r/scylladb/scylla/

**Comment by uzair004** [comment]
> @andirey note that you can easily run Scylla, for functional evaluation, on Mac as Docker container https://hub.docker.com/r/scylladb/scylla/

what about interacting with it using cqlsh?

**Comment by mykaul** [comment]
> > @andirey note that you can easily run Scylla, for functional evaluation, on Mac as Docker container https://hub.docker.com/r/scylladb/scylla/
> 
> what about interacting with it using cqlsh?

docker run -it scylladb/scylla-cqlsh ${SCYLLA_HOST} perhaps ?
CC @fruch

**Comment by fruch** [comment]
> > > @andirey note that you can easily run Scylla, for functional evaluation, on Mac as Docker container https://hub.docker.com/r/scylladb/scylla/
> > 
> > 
> > what about interacting with it using cqlsh?
> 
> docker run -it scylladb/scylla-cqlsh ${SCYLLA_HOST} perhaps ? CC @fruch

Installing cqlsh on mac directly is also possible 
we supply wheels for macos
https://pypi.org/project/scylla-cqlsh/#files

as long as you have the most recent pip, it should be working out of the box:
```
pip install scylla-cqlsh
```

and there a cqlsh executable embedded into the docker image, so you can run cqlsh command from with the docker instance
