### ISSUE TITLE
max and min on a inet column returns unexpected result

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#5139]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): ReleaseVersion: 3.0.8
Cluster size: 
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

c* returns the value, as it is represented as a string:
```
cqlsh> CREATE KEYSPACE group_functions WITH replication={'class':'SimpleStrategy', 'replication_factor':1} ;
cqlsh> USE group_functions ;
cqlsh:group_functions> create TABLE all_types (id int PRIMARY KEY, my_inet inet);
cqlsh:group_functions> SELECT * from all_types ;

 id | my_inet
----+---------

(0 rows)
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (0, '1.1.1.1');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (1, '1.1.1.2');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (2, '1.1.1.3');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (3, '1.1.1.4');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (4, '1.1.1.5');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (6, '1.1.1.6');
cqlsh:group_functions> SELECT cou
                       <blobLiteral>          <colname>              <float>                <identifier>           <pgStringLiteral>      <quotedStringLiteral>  <uuid>                 <wholenumber>          COUNT                  
cqlsh:group_functions> SELECT count(my_inet) from all_types ;

 system.count(my_inet)
-----------------------
                     6

(1 rows)

Warnings :
Aggregation query used without partition key

cqlsh:group_functions> SELECT min(my_inet) from all_types ;

 system.min(my_inet)
---------------------
             1.1.1.1

(1 rows)

Warnings :
Aggregation query used without partition key

cqlsh:group_functions> SELECT max(my_inet) from all_types ;

 system.max(my_inet)
---------------------
             1.1.1.6

(1 rows)

Warnings :
Aggregation query used without partition key

cqlsh:group_functions>
```

but scylla does something else:
```
cqlsh:group_functions> create TABLE all_types (id int PRIMARY KEY, my_inet inet);
cqlsh:group_functions> SELECT * from all_types ;

 id | my_inet
----+---------

(0 rows)
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (0, '1.1.1.1');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (1, '1.1.1.2');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (2, '1.1.1.3');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (3, '1.1.1.4');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (4, '1.1.1.5');
cqlsh:group_functions> INSERT INTO all_types (id, my_inet) VALUES (6, '1.1.1.6');
cqlsh:group_functions> SELECT count(my_inet) from all_types ;

 system.count(my_inet)
-----------------------
                     6

(1 rows)
cqlsh:group_functions> SELECT min(my_inet) from all_types ;

 system.min(my_inet)
---------------------
          0x01010101

(1 rows)
cqlsh:group_functions> SELECT max(my_inet) from all_types ;

 system.max(my_inet)
---------------------
          0x01010106

(1 rows)
```

**Comment by fgelcer** [comment]
same happened for:
* list
* set
* tuple

**Comment by fgelcer** [comment]
detected by new test, cql_group_functions_tests.py

**Comment by jul-stas** [comment]
@fgelcer  I can't find a case of BLOBs+min/max misbehavior (comparing against C*-3.11.3). Can you please clarify?

**Comment by avikivity** [comment]
Probably should be backported. Seems safe enough. Nevertheless will let it cook for a while longer.

**Comment by avikivity** [comment]
Wait, the fix does not match the bug. @jul-stas please clarify.

**Comment by jul-stas** [comment]
At first I submitted partial solution (PR #5311). And, later, the rest (PR #5428, this time with description "Fixes #5139"). 
However, both branch names contained "5139", so maybe here's the source of confusion..?

**Comment by avikivity** [comment]
Please file an issue that describes the problem that this patch fixes. As far as I can tell, 9efad36fb8a6e280c6f36b798923b13edc42e001 has nothing to do with inet, which is what this bug is about.

**Comment by jul-stas** [comment]
According to this comment: https://github.com/scylladb/scylla/issues/5139#issuecomment-538752723 min/max for collections was also reported here. So I'd argue that both patches belong here.
If you don't agree **no** action from you is required - I'll open the issue tomorrow :)

**Comment by avikivity** [comment]
You're right, we can just update the issue title.

**Comment by avikivity** [comment]
Aged out.
