### ISSUE TITLE
Include sstableloader in scylla-tools 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#514]
sstableloader is useful when migrating from C* cluster to a new, smaller, scylla cluster.
sstableloader should be flexible enough to import from as many SSTable versions as possible.

**Comment by penberg** [comment]
@slivne @tzach The ``sstableloader`` tool uses C* inter node messaging protocol for streaming the data.

**Comment by slivne** [comment]
Yes we need to provide our own, we can not use origin's

**Comment by elcallio** [comment]
Fwiw, I've committed an initial implementation in seastar-dev, calle/bulkloader. 
Somewhat rudimentary, and almost wholly untested (please suggest good sources of sstables with "weird" content). 

Also, to quote code comments:

```
 * This works fairly ok for most normal types, as well as frozen collections. 
 * However, it breaks down completely for non-frozen lists. 
 * 
 * In cassandra, a list is stored as actually a "map" of time UUID -> value. 
 * Since maps in turn are just prefixed thrift column names (the key is part of column name), 
 * UUID sorting makes sure the list remains in order. However, actually determining
 * what is index 0, 1, 2 etc cannot be done until the whole list is materialized (reading 
 * backwards etc yadayada). 
 * Since we 
 * a.) Read forwards
 * b.) Might not be reading all relevant sstables
 * we have no idea what is actually in the CQL list. 
 * Thus we cannot generate any of the valid expressions to manipulate the list in question. 
 * 
 * As a "workaround", the code will instead generate map expressions, using the actual 
 * time UUID keys for all list ops. This is of course bogus, and indeed will result in 
 * wild errors from for example Origin getting any such statements. 

```

**Comment by avikivity** [comment]
In the internal protocol, we introduced a "collections_as_maps" option (cf.) to solve the same problem.  We might add a private extension to the cql protocol to support this.

(we might need an extension to the language, too)

**Comment by avikivity** [comment]
Probably would not need an extension to the language, just when the option is set, a list index becomes a uuid instead of an integer.

**Comment by dorlaor** [comment]
We can try to push a solution to C* upstream but not block on it

**Comment by elcallio** [comment]
Again, fwiw, the Cassandra java driver seems ok with transmitting the "list[?] = ?" , <uuid>, <value> statement. But as soon as it reaches the server, it of course breaks. 
Unfortunately, getting a new options field through the Java driver requires modifying the driver code itself, as there is no "user level" option to extend it. And nothing to override.

**Comment by avikivity** [comment]
We could have our own little fork.

Or simply assume that a 16-byte value is a uuid (and verify it has the same format) vs. a 4-byte value for normal operations.

**Comment by avikivity** [comment]
Maybe a fake column `update foo set xxx_scyla_list[?] = ?` will trigger the special behavior?

**Comment by penberg** [comment]
This issue has been fixed by https://github.com/scylladb/scylla-tools-java/commit/da4585a429b4f314aa2e29867a58147415cfae06
and https://github.com/scylladb/scylla-tools-java/commit/ae31ca33a1264c0dddc81e0b469a060b54ba978b
