### ISSUE TITLE
high space amplification on major compaction for incremental compaction

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#5140]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): c9aae13faecf470f4
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

Incremental compaction is not having an effect on major compaction, because it fails to release disk space of sstables released earlier. look:
https://snapshot.raintank.io/dashboard/snapshot/ot6he19jo3yPyY3p2oAzF090eBjLoYbk?orgId=2&panelId=4&fullscreen&from=1567522033076&to=1567523169198&var-cluster=&var-dc=All&var-node=All&var-by=instance&var-monitor_disk=md0&var-monitor_network_interface=eth0&var-mount_point=%2Fvar%2Flib%2Fscylla

**Comment by raphaelsc** [comment]
It's fixed after patch sent to mailing list ([PATCH] sstables: Fix major compaction's space amplification with incremental compaction): https://snapshot.raintank.io/dashboard/snapshot/ulWh7uvitnTShAnDy3I07n8tyZDnwx4H?orgId=2

**Comment by avikivity** [comment]
No vulnerable release, removing backport candidate label.
