### ISSUE TITLE
Innocuous schema changes have high impact

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#5142]
Changing something innocuous like read repair probablity counts as a full schema change and causes all of the schema upgrade machinery to kick in, which has some cost, even though it's not really needed.

**Comment by avikivity** [comment]
We could fix this by splitting the schema into components:
 - storage schema, containing the types and names of cells
 - primary key schema (which cannot change in a table once created)
 - anciliary schema, containing things like read repair probability or compaction strategy

Each of these would have its own version. Different components can decide which part they carry (and therefore compare in order to detect mismatch). For example, mutation readers would work with storage_schema, partition key comparators would work with primary_key_schema, while the rest of the code would work with the full schema (containing all three components).

A downside is that it will be harder to trigger the schema change machinery in tests, so we'd need to add more tests.

**Comment by tgrabiec** [comment]
Related: https://github.com/scylladb/scylla/issues/2718

**Comment by avikivity** [comment]
Duplicate of #2718
