### ISSUE TITLE
Token relation restriction

### ISSUE THREAD

**Issue by jsurloppe** [scylladb/scylla#5143]
- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.10-0.20190815.b3bfd8c08

A very useful query in Cassandra is to restrict query by a range of token, in Scylla the supports for that type of queries seems limited, there's an error when we query a token range and some filter.

For example, on scylla, the last query described on [that page of cassandra documentation](https://docs.datastax.com/en/archived/cql/3.3/cql/cql_using/useToken.html) doesn't work and return: `InvalidRequest: Error from server: code=2200 [Invalid query] message="Columns "ColumnDefinition{name=year, type=org.apache.cassandra.db.marshal.TimestampType, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}" cannot be restricted by both a normal relation and a token relation"`

**Comment by tzach** [comment]
Full example below

```
CREATE KEYSPACE cycling
  WITH REPLICATION = { 
   'class' : 'SimpleStrategy', 
   'replication_factor' : 1 
  };

CREATE TABLE cycling.last_3_days (
  race_name text, 
  year timestamp, 
  rank int, 
  cyclist_name text, 
  PRIMARY KEY (year, rank, cyclist_name)
);

SELECT * FROM cycling.last_3_days WHERE TOKEN(year) > TOKEN('2015-05-24');

 year | rank | cyclist_name | race_name
------+------+--------------+-----------

(0 rows)

SELECT * FROM cycling.last_3_days WHERE TOKEN(year) < TOKEN('2015-05-26') AND year IN ('2015-05-24','2015-05-25');
InvalidRequest: Error from server: code=2200 [Invalid query] message="Columns "ColumnDefinition{name=year, type=org.apache.cassandra.db.marshal.TimestampType, kind=PARTITION_KEY, componentIndex=0, droppedAt=-9223372036854775808}" cannot be restricted by both a normal relation and a token relation"
cqlsh> 

```

**Comment by tzach** [comment]
@psarna this looks like the same issue as #4244 is it so?

**Comment by psarna** [comment]
@tzach yes, that's precisely the issue

**Comment by tzach** [comment]
Dup with #4244
