### ISSUE TITLE
Admission control should drop queries with "overloaded" error

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#5144]
*Installation details*
Scylla version (or git commit hash): 9d4e71bbc6fdd3d62365fd339df36733c354be80

Currently admission control pauses for unspecified time when a memory limit is reached. It should start load shedding if pause is too long.

**Comment by tgrabiec** [comment]
Can you explain in more detail why is this pausing behavior a problem?

**Comment by gleb-cloudius** [comment]
On Mon, Oct 07, 2019 at 01:38:42PM -0700, Tomasz Grabiec wrote:
> Can you explain in more detail why is this pausing behavior a problem? 
> 
Because it causes client side timeouts and may admit requests which are
no longer waited by a client.

--
			Gleb.

**Comment by tgrabiec** [comment]
> On Mon, Oct 07, 2019 at 01:38:42PM -0700, Tomasz Grabiec wrote: Can you explain in more detail why is this pausing behavior a problem?
> Because it causes client side timeouts

Why are client-side timeouts something we better avoid?

>  may admit requests which are no longer waited by a client.

How long do you think the pause should be before we start shedding? Suppose that's T.

What does a pause mean, does it mean that none of the admitted requests completes within T?

Note that this doesn't prevent client-side timeouts. If the server is processing requests at a steady rate, so no pause, but that rate is lower than the rate of incoming requests, eventually we will start seeing client-side timeouts.

**Comment by gleb-cloudius** [comment]
On Tue, Oct 08, 2019 at 01:51:25AM -0700, Tomasz Grabiec wrote:
> > On Mon, Oct 07, 2019 at 01:38:42PM -0700, Tomasz Grabiec wrote: Can you explain in more detail why is this pausing behavior a problem?
> > Because it causes client side timeouts
> 
> Why are client-side timeouts something we better avoid?
> 
c-s for instance consider it to be more serious error than timeout. But
more importantly after the timeout a client will send new request, but
the old one will still be admitted and processed for nothing which
basically increase perceived concurrency.

> >  may admit requests which are no longer waited by a client.
> 
> How long do you think the pause should be before we start shedding? Suppose that's T.
Couple of ms. 

> 
> What does a pause mean, does it mean that none of the admitted requests completes within T?
A request may complete, but still hold admission permit for duration of
background operation.

> 
> Note that this doesn't prevent client-side timeouts. If the server is processing requests at a steady rate, so no pause, but that rate is lower than the rate of incoming requests, eventually we will start seeing client-side timeouts.
> 
We need to start shedding load before that.

--
			Gleb.

**Comment by eliransin** [comment]
This issue is very similar to #1823
I think it is a duplicate.

**Comment by gleb-cloudius** [comment]
It is.
