### ISSUE TITLE
CQL result set null values encoded incorrectly

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#515]
Running the following query:

```
[cqlsh 5.0.1 | Cassandra 2.1.11 | CQL spec 3.2.1 | Native protocol v3]
Use HELP for help.
cqlsh> CREATE KEYSPACE IF NOT EXISTS cql_test_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
cqlsh> USE cql_test_keyspace;
cqlsh:cql_test_keyspace> CREATE TABLE foo (userid uuid, ip text, port int, time bigint, PRIMARY KEY (userid, ip, port)) WITH COMPACT STORAGE;
cqlsh:cql_test_keyspace> INSERT INTO foo (userid, ip, time) VALUES (f47ac10b-58cc-4372-a567-0e02b2c3d479, '192.168.0.3', 42);
cqlsh:cql_test_keyspace> SELECT ip, port, time FROM foo WHERE userid = f47ac10b-58cc-4372-a567-0e02b2c3d479 AND ip = '192.168.0.3';
```

Shows correct behavior in C* where ``port`` is ``null``:

```
 ip          | port | time
-------------+------+------
 192.168.0.3 | null |   42

(1 rows)
```

but incorrect behavior in ScyllaDB where ``port`` is an empty value:

```
 ip          | port | time
-------------+------+------
 192.168.0.3 |      |   42
```

Spotted while running C* unit tests.

**Comment by penberg** [comment]
Ping @tgrabiec, @pdziepak

**Comment by tgrabiec** [comment]
I think I can see where the problem is, will cook up a patch

**Comment by pdziepak** [comment]
The problem seems to be that using clustering_key we can't distinguish between empty and null values. clustering_key_prefix can do that and using it instead should solve the problem.

**Comment by tgrabiec** [comment]
@pdziepak Yes, we should switch to clustering_key_prefix. One clarification though. Neither of them supports null components, clustering_key_prefix allows trailing components to be not set. It doesn't allow not-set components in the middle. But neither does C*, so we should be fine.
