### ISSUE TITLE
Sluggish backlog tracking with incremental compaction 

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#5157]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 64c2d28a7f8fa6ae3d591a57af8a656bcefcbdfc
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Backlog controller is not properly updated after an early replacement triggered by incremental compaction.

**Comment by tzach** [comment]
[PATCH] sstables: Fix sluggish backlog controller with incremental compaction

**Comment by avikivity** [comment]
No branch is vulnerable; removing backport candidate label.
