### ISSUE TITLE
ami: using mainline kernel can be risky

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#5160]
We are now using mainline kernel (from elrepo kernel-ml). This was done to work around the centos kernel not supporting AWS i3 well, but it is likely that i3 support was backported to the centos kernels, so we can use a more stable kernel by switching back.

We should also consider CentOS 8 and Amazon Linux 2.

**Comment by slivne** [comment]
we are moving to Amazon Linux 2 / Centos 8 - once done this can be closed

**Comment by tzach** [comment]
@slivne AFAIU this is not going to be in 4.2

**Comment by slivne** [comment]
@yaronkaikov / @avikivity I think we moved away from mainline kernel - can we close this

**Comment by avikivity** [comment]
Obsoleted by scylladb/scylla-machine-image@de1bb48faf75fc2edbfa83dc9108d69217476a21
