### ISSUE TITLE
Consistent semaphore Timedout in two nodes in large partition

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla#5162]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):3.1.0.rc9-0.20191006.05272c53e
Cluster size:4
OS (RHEL/CentOS/Ubuntu/AWS AMI):ami-09c8d17ff81a2773e (Ireland)
Instance Type: i3en.3xlarge

## Summery:
For 36 hours, two of the nodes in the cluster experienced constant Semaphore Timedouts. The nodes that experienced the issue:
longevity-large-partitions-4d-3-1-db-node-3f8c72be-4  |  10.0.28.220
longevity-large-partitions-4d-3-1-db-node-3f8c72be-5  |  10.0.154.238

First appearance:
```
2019-10-07T08:26:26+00:00  ip-10-0-154-238 !ERR     | scylla: [shard 11] storage_proxy - Exception when communicating with 10.0.154.238: seastar::semaphore_timed_out (Semaphore timedout)
```

## Logs:
* Logs of the faulty logs can be found here: scratch.scylladb.com/shlomib/large_partition_10_10_relevant_faulty_logs.zip

* Logs of all of the nodes can be found here:
scratch.scylladb.com/shlomib/large_partition_10_10_logs_of_all_nodes.zip

* Grafana snapshot: https://snapshot.raintank.io/dashboard/snapshot/cuxbruxh8VIK1ml9abCxtrQcNHVrxAYg

* Longevity yaml: https://github.com/scylladb/scylla-cluster-tests/blob/branch-3.1/test-cases/longevity/longevity-large-partition-4days.yaml

**Comment by slivne** [comment]
- we have improved memory management in master (3.4) 
- we have now added the semaphore name to get additional information for debugging.

closing this issue  - please create a new issue if this happens post 3.3 with the additional informatin
