### ISSUE TITLE
wrong key type used when creating non-frozen map virtual column

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#5165]
version: master, been there for some time though
in db/view/view.cc:
```
        builder.with_column(name, map_type_impl::get_instance(mtype->get_values_type(), empty_type, true), column_kind::regular_column, column_view_virtual::yes);
```
should be `mtype->get_keys_type()`.

**Comment by avikivity** [comment]
Backported to 3.0, 3.1.

**Comment by tzach** [comment]
@kbr- when this might happen? can you give a CQL example?

**Comment by kbr-** [comment]
```
create table a (a int, b int, c map<int, text>, primary key (a, b));
create materialized view v as select a, b
create materialized view v AS select a, b from a where b is not null primary key (b, a);
select * from system_schema.view_virtual_columns ;

 keyspace_name | table_name | column_name | clustering_order | column_name_bytes | kind    | position | type
---------------+------------+-------------+------------------+-------------------+---------+----------+-----------------
             d |          v |           c |             NONE |              0x63 | regular |       -1 | map<int, empty>
```
the `map<int, empty>` would instead be `map<text, empty>`.

I'm not sure if this actually makes anything crash or work incorrectly. The virtual columns are there to check liveness, so we're only interested in timestamps in their mutations. But there is a piece of code that could serialize a text field while thinking that it's an int field, or the other way around. Maybe it could cause some undefined behavior.
