### ISSUE TITLE
Node replace procedure may end up losing replaced node tokens

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#5172]
*Installation details*
Scylla version: 2.3.5
Cluster size: 5
OS: Ubuntu 16.04 + 18.04

*Hardware details*
Platform: bare metal

*Description*
1) Provision a cluster of 4 nodes.
2) Populate it with some data.
3) Stop and clean one node (nodeX): delete its `data` and `commitlog` directories.
4) Make nodeX replace itself: set `replace_address_first_boot: <IP of NodeX>` in its `scylla.yaml` and start it.
5) Kill -9 nodeX in the middle of streaming.
6) Remove replace_address_first_boot from the scylla.yaml
7) Clean nodeX'es data and commitlog.
7) Start nodeX .

See that nodeX starts bootstrapping as it's a new node in the cluster and other nodes don't have any information about previous tokens of nodeX as they had after step (3) above.

This effectively equivalent to `nodetool removenode` without streaming.

**Comment by tzach** [comment]
Why should a node replace itself?
Seems like this option should simply be blocked

**Comment by vladzcloudius** [comment]
@tzach One option could be: because you have lost the disk(s) on that node, fixed it and want this node back.

**Comment by glommer** [comment]
The node replacing itself is by far the most common way of replacing the node.

In any cloud for instance, when the machine is stopped the private IP doesn't change, so to return back to the cluster the node has to replace itself.

**Comment by slivne** [comment]
@asias can you please comment on this scenario - does the problem exist.

does C* have this issue as well ?

**Comment by asias** [comment]
> @asias can you please comment on this scenario - does the problem exist.

I reproduced it. The problem is that during bootstrap when we check if a node is safe to bootstrap, we do not consider HIBERNATE node to be unsafe.  To be extra safe, I think we can whitelist the status that is allowed to be bootstrapped, i.e., node is not in gossip at all, STATUS_LEFT (for node being decommissioned), REMOVED_TOKEN (for node removed with nodetool removenode)

```
storage_service::check_for_endpoint_collision
     _gossiper.is_safe_for_bootstrap

2176 bool gossiper::is_safe_for_bootstrap(inet_address endpoint) {
2177     auto* eps = get_endpoint_state_for_endpoint_ptr(endpoint);
2178 
2179     // if there's no previous state, or the node was previously removed from the cluster, we're good
2180     if (!eps || is_dead_state(*eps)) {
2181         return true;
2182     }
2183     
2184     sstring status = get_gossip_status(*eps);
2185 
2186     logger.debug("is_safe_for_bootstrap: node {} status {}", endpoint, status);
2187 
2188     // these states are not allowed to join the cluster as it would not be safe
2189     std::unordered_set<sstring> unsafe_statuses{
2190         sstring(versioned_value::STATUS_UNKNOWN), // failed bootstrap but we did start gossiping
2191         sstring(versioned_value::STATUS_NORMAL), // node is legit in the cluster or it was stopped with kill -9
2192         sstring(versioned_value::SHUTDOWN) // node was shutdown
2193     };          
2194 
2195     return !unsafe_statuses.count(status);
2196 }
```

> does C* have this issue as well ?

Yes.

**Comment by asias** [comment]
PR sent. https://github.com/scylladb/scylla/pull/5995

**Comment by avikivity** [comment]
Backported to 3.3. (already in 4.0).
