### ISSUE TITLE
Don't gossip cache hit rates when they are not used

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#5183]
When cache_hit_rate_read_balancing is set to false, heat-weighted load balancing is turned off and we gossip cache hit rates for no good reason. The size of gossiped data is linear on number of tables in the database so it's good to avoid such traffic when it is not used.

Ref https://github.com/scylladb/scylla-enterprise/issues/1092

**Comment by gleb-cloudius** [comment]
The node may not know that _other_ nodes do not use it though.

--
			Gleb.

**Comment by haaawk** [comment]
I think the assumption is that we want the whole cluster to either have HWLB enabled or not. The mismatch can occur only while rolling update of this property.

**Comment by gleb-cloudius** [comment]
On Tue, Oct 22, 2019 at 06:34:19AM -0700, Piotr Jastrzębski wrote:
> I think the assumption is that we want the whole cluster to either have HWLB enabled or not. The mismatch can occur only while rolling update of this property.
> 
Yes, but there are always mistakes or intermediate state while HWLB is
been disabled.
 
--
			Gleb.

**Comment by haaawk** [comment]
> On Tue, Oct 22, 2019 at 06:34:19AM -0700, Piotr Jastrzębski wrote: I think the assumption is that we want the whole cluster to either have HWLB enabled or not. The mismatch can occur only while rolling update of this property.
> Yes, but there are always mistakes or intermediate state while HWLB is been disabled.
> […](#)
> -- Gleb.

Yes so the idea is to not use HWLB unless all replicas that participate have it enabled.

**Comment by gleb-cloudius** [comment]
On Tue, Oct 22, 2019 at 07:32:39AM -0700, Piotr Jastrzębski wrote:
> Yes so the idea is to not use HWLB unless all replicas that participate have it enabled.
> 
OK. That sounds right.

--
			Gleb.

**Comment by haaawk** [comment]
It seems that the issue in the enterprise was fixed already so closing this one.
