### ISSUE TITLE
Better compaction for sstables generated by maintenance operations

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#5199]
When we run a node maintenance operation, e.g., bootstrap, repair, a set of new sstables will be created. For a given token range for a given table, typically a vnode token range, streaming will create 1 new sstables per shard, repair will create 1 new sstables per shard on repair followers and RF - 1 new sstables per shard on repair master. Those sstables do not have the invariant properties defined by the compaction strategy. 

Currently, we add those new sstables to the main sstables set directly and let the normal compaction to compact and "reshape" those sstables. As a result, we effectively push the maintenance work to the compaction scheduling group, not running under maintenance scheduling group, having impact on the user read performance. In addition, those sstables without the invariant properties defined by the compaction strategy may cause bad read performance.

**Comment by slivne** [comment]
merged with https://github.com/scylladb/scylla/issues/5226
