### ISSUE TITLE
dist: http://localhost:10000/ui/ does not work on .rpm/.deb/ami

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#520]
Because of missing swagger-ui/ and api/api-doc/, http://localhost:10000/ui/ does not work correctly on .rpm/.deb/ami.

**Comment by tzach** [comment]
+1 for fixing it for the next minor release.
Provide useful and easy to use UI for Scylla operations.

**Comment by tzach** [comment]
@syuu1228 @avikivity is this fix?

**Comment by syuu1228** [comment]
This is fixed.

**Comment by tzach** [comment]
> This is fixed.

@syuu1228 with which commit?
