### ISSUE TITLE
Add metrics for Full scan, and for CQL BYPASS

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#5209]
Scylla version (or git commit hash): 3.1

A full scan is a resource-heavy operation that users should be careful with.
In most cases, the full scan should be used with the BYPASS CACHE feature.

To follow the execution of the above, we should add the following metrics:
- Full scan execution (where a full scan is a query without a partition key limitation in the WHERE)
   * For user tables (more interesting)
   * For system table (less interesting)
- Query with BYPASS CACHE
- Full scans without BYPASS CACHE (system/user)
 
The last can be added to the optimized CQL dashboard, as a hint for a bad query.

**Comment by slivne** [comment]
@alecco take a stab at it
