### ISSUE TITLE
Unable to parse a date that's in valid C* format

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#521]
I tried running the example CQL in the "Copying collections" section:

http://docs.datastax.com/en/cql/3.1/cql/cql_reference/copy_r.html

but it failed with Scylla as follows:

```
cqlsh:music> INSERT INTO music.songs (id, venue) VALUES (7db1a490-5878-11e2-bcfd-0800200c9a66, { '2013-9-22 12:01'  : 'The Fillmore', '2013-10-1 18:00' : 'The Apple Barrel'});
InvalidRequest: code=2200 [Invalid query] message="marshaling error: unable to parse date '2013-9-22 12:01'"
```

The same insert statement works fine in C*.

**Comment by penberg** [comment]
Ping @avikivity, @pdziepak, @tgrabiec

**Comment by avikivity** [comment]
Well the parser for date_type says "not implemented".  Should be easy to fix.

**Comment by pdziepak** [comment]
Actually the problem seems to be that timestamp type doesn't accept date in format YYYY-M-DD. Still, easy to fix.

**Comment by avikivity** [comment]
@pdziepak, please fix that bit, I'll make date_type work.

**Comment by slivne** [comment]
@pdziepak does your patch "[PATCH scylla 0/4] Make date parser more liberal" fix this

**Comment by pdziepak** [comment]
On 23 December 2015 at 14:13, slivne <notifications@github.com> wrote:

> @pdziepak <https://github.com/pdziepak> does your patch "[PATCH scylla
> 0/4] Make date parser more liberal" fix this
>

Yes, it does.

**Comment by slivne** [comment]
Ok will close ones its merged
