### ISSUE TITLE
Allow build rpms in debug mode

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5231]
Currently we can build rpms only in release mode.
Provide option to override the default and specify a different mode for building the rpms so we can eventually build ami with scylla in debug mode.

**Comment by penberg** [comment]
This should be supported. The workflow is as follows. You first build a relocatable package in debug mode and you then invoke `build_rpm.sh` using that tarball.

See the following section of the package build document for details:

https://github.com/scylladb/scylla/blob/master/docs/building-packages.md#scylla-server

**Comment by bhalevy** [comment]
good, let's make sure it's automated by build_ami.sh
If nothing else is required in build_rpm.sh than we can close this issue...

**Comment by hagitsegev** [comment]
While working on https://github.com/scylladb/scylla-pkg/issues/698
We need to create the debug RPMs with a debug name.
Currently, when I go ahead with the process, I override the release files (or some of them) with the debug files.
The name of RPMs is generated by calling dist/redhat/scylla.spec.mustache
It takes the "scylla" (or scylla-enterprise) prefix from SCYLLA-PRODUCT-FILE.
We need to create a SCYLLA-PRODUCT-FILE for debug, that will contain scylla-debug (or scylla-enterprise-debug or scylla-debug-enterprise).
In this way - we will have files with the right name, so I can use them.

**Comment by bhalevy** [comment]
> While working on [scylladb/scylla-pkg#698](https://github.com/scylladb/scylla-pkg/issues/698)
> We need to create the debug RPMs with a debug name.
> Currently, when I go ahead with the process, I override the release files (or some of them) with the debug files.
> The name of RPMs is generated by calling dist/redhat/scylla.spec.mustache
> It takes the "scylla" (or scylla-enterprise) prefix from SCYLLA-PRODUCT-FILE.
> We need to create a SCYLLA-PRODUCT-FILE for debug, that will contain scylla-debug (or scylla-enterprise-debug or scylla-debug-enterprise).
> In this way - we will have files with the right name, so I can use them.

I think that it would be best if `SCYLLA-VERSION-GEN` would be called with a `mode` parameter and  use it to generate the `SCYLLA-*-FILE` files under `build/$mode` and will append the mode to the `PRODUCT` name if `mode != release` (that would end up as `scylla-enterprise-debug` for scylla-enterprise)

**Comment by nyh** [comment]
@bhalevy, @penberg explained above that it is, in fact, possible to create debugging RPMs. In any case you need to run build_reloc first and only then build_rpm, and build_reloc has the "--mode" option.

There seems to be another issue here regarding the resulting package's **name**. I think it would be better to close this one and open a new issue with a clearer explanation of what is actually the problem.

**Comment by avikivity** [comment]
Note you can now build debug rpms with ninja `build/dist/debug/redhat`

**Comment by espindola** [comment]
> Note you can now build debug rpms with ninja `build/dist/debug/redhat`

Should we close this?

**Comment by penberg** [comment]
As of commit 5d99d667ec7de8cb2d0bb514b290fa3f4a0c892e, you can build debug packages with:

```
./configure.py --mode=debug && ninja dist
```
