### ISSUE TITLE
repair: assert failure when local node fails to produce checksum

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#5238]
Affected version: all active versions (2.1+).

https://github.com/scylladb/scylla/blob/85168c500c5102d81770e9884a546ce1f36ac604/repair/repair.cc#L809-L839

If `checksums[0]` is a failed future, the exception is extracted and logged. Calling `checksum[0].get_exception()` resets the future to `state::invalid`. If at least some of the other nodes produced a checksum, the `if` at line 834 will fall through as `live_neighbours` is not empty and `checksums[0].failed()` will return false, due to the future being in `state::invalid` state. Thus, execution happily proceeds to line 839, where it calls `checksums[0].get0()`, which leads to an assert failure, because the `future::get()` will attempt to get the thread context of the (non-available) future and will fail.

**Comment by avikivity** [comment]
Alrready backported.
