### ISSUE TITLE
connection storm when attempting to achieve shard-per-connection

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#5239]
When a client attempts to establish a connection per shard, it generates a large amount of connections until (randomly) it manages to reach all shards, at which point it can drop the old ones. If there are many clients connecting simultaneouly (this can happen when a node restarts) there can be a huge number of connections happening at once, increasing the load on the node.

**Comment by avikivity** [comment]
This can be fixed with the new SO_ATTACH_FILTER_EBPF. The client selects a source port that is shard id (mod nr_shards) to indicate which shard they are interested in reaching, and the bpf program then selects the shard's socket. Clients will have to be adjusted, but it's a simple bind() call.

Note this is defeated by NAT, so we have to be able to fall back to the old method.

**Comment by avikivity** [comment]
Actually, we don't need the bpf program. We can use server_socket::load_balancing_algorithm::port. The ebpf thing is just an optimization that lets the kernel do it, which isn't critical for us since connections are rare.

**Comment by avikivity** [comment]
@gleb-cloudius no?

**Comment by gleb-cloudius** [comment]
On Tue, Oct 29, 2019 at 05:56:00AM -0700, Avi Kivity wrote:
> @gleb-cloudius no?
> 
Right. The reason I did not pursued it is because I worried what will
happen with new Scylla and old driver. But may be it will not be worse
that what we have today.

--
			Gleb.

**Comment by avikivity** [comment]
Maybe we can make it conditional on some flag exposed by the STARTUP verb

**Comment by glommer** [comment]
With NAT being so pervasive (most aws/azure/gcp deployments will have scylla running on internal IPs), is it even worth it to pursue a solution that will be defeated by NAT ?

**Comment by avikivity** [comment]
The word NAT by itself doesn't defeat the solution. The client has to be NATted, not the server, for the solution to be defeated; and if the server has a public IP address outgoing connections are not NATted. So if you connect from your home network you will get the wrong port, but if two servers have public IP addresses they will work. Likewise servers using the internal addresses should work.

If you connect from a client with a public IP to a server with a public IP, the port number should be preserved. I verified this by connecting two AWS instances together using their public IPs:

```
[ec2-user@ip-10-99-0-202 ~]$ ss -t 
State                              Recv-Q                                Send-Q                                                                
ESTAB                              0                                     0                                                                       10.99.0.202:ssh                                                                18.232.119.118:41284  
```

```
[ec2-user@ip-10-99-0-8 ~]$ ss -t
State                              Recv-Q                               Send-Q                                                                Local Address:Port                                                                  Peer Address:Port                                
ESTAB                              0                                    0                                                                         10.99.0.8:41284                                                                 3.83.188.167:ssh                                 
```

You can see they use the same port, so source port selection should work.

**Comment by haaawk** [comment]
@avikivity Can we just open a port on the server for each shard and then client would be able to connect to a particular shard by just targeting the right port?
