### ISSUE TITLE
patchelf fails on scylla binary in debug mode as it is too large

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5245]
Scylla version 49aa8ab8a0698c3ee939bceedebab0e2556beeb9
scylla-ccm version 706eefdf7191f83a5b6c37aa5beb0b5fcd804518

Seen in [dtest-debug/297](https://jenkins.scylladb.com/job/scylla-master/job/dtest-debug/297/)
But this is also a requirement for #5232 as patchelf is required to install the relocatable package.

The 2GB file size limitation is fixed since NixOS/patchelf@ba2695a8110abbc8cc6baf0eea819922ee5007fa (included in version 0.10)

**Comment by avikivity** [comment]
fedora 31 has patchelf 0.10. So we can upgrade our frozen toolchain to fedora 31, and make sure we run patchelf from the toolchain, not the host.

**Comment by nyh** [comment]
@avikivity another, more difficult, alternative is to invest effort to find ways to make the binary smaller. It will certainly grow again in the future and pass the 2GB mark again - but hopefully the improved patchelf will have become popular by then.
Of course, finding ways to make the binary smaller will have additional benefits, not just pleasing patchelf...

**Comment by bhalevy** [comment]
stripping the binary also reduces its size so we can also use that as an intermediate workaround.

**Comment by avikivity** [comment]
It is not more difficult, it is futile. The debug binary is large because it performs a lot of debug checks and has a lot of debug information. Since we are adding features, it will grow.

To reduce it, we will have to invent and implement new debug information format and to update the compiler to optimize the debug checks for size. It is an effort that is not in proportion to the gain, especially when the move to patchelf 0.10 is just generation of a new docker image.

**Comment by avikivity** [comment]
Stripping the binary also reduces its usefulness.

**Comment by kostja** [comment]
We could also take a look at what is the biggest contributor to the bloated debug info - maybe there are some low hanging fruits.

**Comment by avikivity** [comment]
The biggest contributor is -O0 and lots of inline functions that are expected to be eliminated by the compiler. We could try -O1, but it might degrade the debugging experience, which is one of the main benefits of debug mode.

**Comment by nyh** [comment]
@avikivity I don't know how much we're over the 2GB mark, and how fast this size is growing. It may be the case (and I don't know if that is in fact the case...) that we can find one or few "low hanging fruits" (as @kostja said) that can help the binary remain below 2GB for the next 6 months, and such a grace period will be enough until everyone has a newer patchelf.

One idea I raised in the past is to use a pragma (or equivalent [[gnu::...]] attribute) to cause specific functions to always be compiled with -O1 even for debugging builds. My assumption was that in some very low-level stuff, we almost assume that everything is inlined and deduplicated etc. by the compiler, and nobody wants to debug inside it. The question is how do we find the specific places where more optimization can get us a big object size decrease. I'm not sure what the answer is.

**Comment by kostja** [comment]
Can we use -O1 but add some gcc-specific attributes to avoid optimizing out frames in the most important places?

**Comment by bhalevy** [comment]
> Stripping the binary also reduces its usefulness.

Agreed, but this will only prevent symbols in backtraces.
At least for developer's use, dtest.sh collects the unstripped binary to the artifacts directory before running any tests, so that it could be used to resolve addresses using addr2line and for gdb use.
Any core files should be just as useful without debugging symbols, no?

**Comment by bhalevy** [comment]
Fixed by 1164ff5329fbf81b0c2118b64e9ced3286d09fc3

**Comment by espindola** [comment]
This is not actually fixed until the bots start using it.
