### ISSUE TITLE
Filtering on a static column in an empty partition is incorrect

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#5248]
While debugging my weekend project on rewriting restrictions I found a test case for filtering which does not work correctly:
```cql
CREATE TABLE t (p int, c int, s int static, PRIMARY KEY(p, c));
INSERT INTO t (p, s) VALUES (1, 1);
SELECT * FROM t WHERE s = 2 ALLOW FILTERING;

 p | c    | s
---+------+---
 1 | null | 1

```
The problem is that an otherwise empty partition can still have a valid static column. Filtering didn't take that fact into account and only filtered full-fledged rows, which may a result in an intruder like the one above sneaking in.

I have the solution ready along with a test case, I'll post it today.

**Comment by avikivity** [comment]
Already present on all active branches.
