### ISSUE TITLE
Can scylla support golang?

### ISSUE THREAD

**Issue by torfuzx** [scylladb/scylla#526]
Hi scyllaer.
I want to use scylladb by golang,what I do?
Can you help me?

**Comment by penberg** [comment]
I have not tested it myself but Scylla should work with the ``gocql`` driver:

https://github.com/gocql/gocql

**Comment by torfuzx** [comment]
Hi,penberg.
Thank you very much.I will give it a try.

**Comment by penberg** [comment]
@torfuzx Please do report back when you do! If there are issues with it, we're happy to fix them.

**Comment by torfuzx** [comment]
@penberg OK.

**Comment by nkev** [comment]
@torfuzx Did you get a chance to try the gocql driver?

**Comment by torfuzx** [comment]
Hi,guys.
I compare  scylla with cassandra 2.2.3.I use gocql to call them by executing gocql example(https://github.com/gocql/gocql#example).

They have different results.
### scylla
```
[leslie@zhang src]$ go run cql.go 
2015/11/25 22:06:42 can not marshal string into unknown_type_10
```
### cassandra
```
[leslie@zhang src]$ go run cql.go 
Tweet: 7ee0c167-937e-11e5-b2c3-00262dff336a hello world
Tweet: 7ee0c167-937e-11e5-b2c3-00262dff336a hello world
```

But above all,gocql support for scylla  is not very good.We need to improve it.

**Comment by avikivity** [comment]
@penberg looks like type_codec::type_id::TEXT does not exist in version >= 3.

So we need to make type_codec a per-version object.

**Comment by avikivity** [comment]
(TEXT was type 10 in v1/v2)

**Comment by penberg** [comment]
@avikivity I think they just dropped ``TEXT`` in favor of ``VARCHAR`` that already exists in v1/v2. The following change should be sufficient to make things compatible for all versions:

```
diff --git a/transport/server.cc b/transport/server.cc
index 257b899..d269b69 100644
--- a/transport/server.cc
+++ b/transport/server.cc
@@ -1441,7 +1441,6 @@ thread_local const type_codec::type_id_to_type_type type_codec::type_id_to_type
     (type_id::DOUBLE    , double_type)
     (type_id::FLOAT     , float_type)
     (type_id::INT       , int32_type)
-    (type_id::TEXT      , utf8_type)
     (type_id::TIMESTAMP , timestamp_type)
     (type_id::UUID      , uuid_type)
     (type_id::VARCHAR   , utf8_type)
```

@tgrabiec, @pdziepak, comments?

**Comment by avikivity** [comment]
Isn't this used to create a bimap?  It would mean that v<3 loses TEXT in the incoming direction.

**Comment by penberg** [comment]
@avikivity I only see that being used in the encoding path so AFAICT no.

**Comment by avikivity** [comment]
Let's the un-bimap it, to be sure.

**Comment by avikivity** [comment]
the=then

**Comment by tgrabiec** [comment]
Yes, looks like we only use the map for encoding, we never get types back from the client. decoding could be useful if we wanted to reuse the code to write our own seastar-based CQL client, but that's out of scope for now I guess.

**Comment by avikivity** [comment]
Interesting that the server returns typed values to the client, but 
relies on the client to provide correctly-typed values to the server.  
This makes it impossible to build a fully dynamic client.

**Comment by penberg** [comment]
@torfuzx I sent a patch to fix up the marshaling error. Please note that the example doesn't fully work because Scylla doesn't support secondary indices yet.

**Comment by indykish** [comment]
@torfuzx  Hey,  have you used scylla with `golang`, if so what version did you use ? and did you use `gocql/gocql` driver ?

**Comment by torfuzx** [comment]
@indykish Based on scylla of uncertainty,I use cassandra 2.2.4.
 gocql support for scylla is not very good.
