### ISSUE TITLE
scylla 3.1 query stuck by replica read with semaphore timeout(UUID:58563649-EFEB-4202-BE18-A463F10C625E)

### ISSUE THREAD

**Issue by zhaoyuankui** [scylladb/scylla#5260]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.1.0-0.20191012.9c3cdded9
Cluster size: 3 seeds in 1 IDC
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets=10Gbit cores=12 hyperthreading=12 core memory=32G
Disks: (SSD/HDD, count)
3 HDD as RAID0 xfs

Hello! I'm struggling on the scylla failure of reading. 

Firstly, I'd like to post the error log:
`scylla[]:  [shard 7] storage_proxy - Exception when communicating with 10.189.32.47: seastar::semaphore_timed_out (Semaphore timedout)`

And below are some key dashboards:
1. General read and write
![image](https://user-images.githubusercontent.com/11934120/68069522-e4174800-fd9b-11e9-85ad-b6bc41caab0e.png)
2. Cordinator
![image](https://user-images.githubusercontent.com/11934120/68069536-1aed5e00-fd9c-11e9-844d-14a552634cd7.png)
3. Replica read failure
![image](https://user-images.githubusercontent.com/11934120/68069543-33f60f00-fd9c-11e9-9e6c-7a61ffbc237e.png)
4. IO queue seems abnormal
![image](https://user-images.githubusercontent.com/11934120/68069551-4a9c6600-fd9c-11e9-8876-1a2f715399ee.png)
5. The cpu load is low
![image](https://user-images.githubusercontent.com/11934120/68069560-70c20600-fd9c-11e9-8a18-af880063c48a.png)

My instance is build for tracing data of micro-services. And this problem was triggered by the spark job that analyses the dependencies of micro-services.

My health check report has been submitted, and the report uuid is 58563649-EFEB-4202-BE18-A463F10C625E.

Hope somebody to help me out!

Many thanks!

**Comment by bhalevy** [comment]
@psarna please check if this is a dup of #4999

**Comment by psarna** [comment]
Are materialized views (or indexes) involved here? The issue description doesn't mention them at all. It still may be a dup of #4999, but that would also mean that #4999 is not directly related to materialized views either.

A while ago I sent a patch which allows naming the semaphores to Seastar, and having a semaphore name in the exception message would be really useful here, but it looks like this patch didn't pass review. Once back in the office, I think I'll just make the patch Scylla-specific and push it again, but to scylla-dev, and hopefully future debugging of such issues would get easier.

**Comment by slivne** [comment]
@zhaoyuankui AFAICT jaeger is not using SecondaryIndexes or MaterializedViews

https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/cassandra/schema/v001.cql.tmpl
https://github.com/jaegertracing/jaeger/blob/master/plugin/storage/cassandra/schema/v002.cql.tmpl

Can you please confirm

**Comment by eyusim** [comment]
we seem to be having the same issue. starting yesterday the foreground reads spiked up, our p95 latency went from 5-10ms to 4+ seconds. there's been no changes in the number of requests or the type of requests to scylla. 2 of the 5 servers in the problematic datacenter outputing a lot of "semaphore_timed_out" errors. 

We've had this happen before with the high spike of foreground reads and high latency with version 2.0, but the issue only lasted a few hours. Right now we're on day 2. Restarting scylla on the 2 servers getting the errors didn't help. 

our read timeouts on the server are 25s, and on the client set to 60s. 

submitted healthcheck report: 907e4ed9-bf3e-472a-9481-5de6ea03c411

Installation details
Scylla version (or git commit hash): 3.1.2-0.20191127.9d78d848e
Cluster size: 5 nodes in us-east-1, 3 nodes in us-west-2
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS
Platform: AWS i3.4xl 

<img width="1360" alt="Screen Shot 2020-01-03 at 9 48 39 AM" src="https://user-images.githubusercontent.com/1714250/71740355-d66c5600-2e10-11ea-8dfe-fad569cf4fe0.png">
<img width="1369" alt="Screen Shot 2020-01-03 at 9 42 35 AM" src="https://user-images.githubusercontent.com/1714250/71740356-d66c5600-2e10-11ea-9609-113e65a74c0c.png">
<img width="1362" alt="Screen Shot 2020-01-03 at 9 42 19 AM" src="https://user-images.githubusercontent.com/1714250/71740357-d66c5600-2e10-11ea-80c5-ce7c2fb5feb6.png">
<img width="1383" alt="Screen Shot 2020-01-03 at 9 42 00 AM" src="https://user-images.githubusercontent.com/1714250/71740358-d66c5600-2e10-11ea-94fd-84c21f00de1e.png">
<img width="1375" alt="Screen Shot 2020-01-03 at 9 41 45 AM" src="https://user-images.githubusercontent.com/1714250/71740359-d704ec80-2e10-11ea-89bd-184aa3fc2b68.png">
<img width="1373" alt="Screen Shot 2020-01-03 at 9 41 35 AM" src="https://user-images.githubusercontent.com/1714250/71740360-d704ec80-2e10-11ea-887d-53532e3594e8.png">

**Comment by eyusim** [comment]
we figured out our issue was due to a "magic value" partition key that should have been filtered out before getting to scylladb as there would never be any data for it.

this key would at most account for 1-2% of the queries. would that cause an imbalance of queries per server? or does this cause a cache miss each time causing more read IO?

**Comment by slivne** [comment]
@eyusim - thanks for the update - and its great that you solved it.

Scylla is sharded per node (each shard owns part of the data) - so queries for a specific partition key need togo to a specific shard. 

Scylla does cache single partitions that do not exist on first attempt https://github.com/scylladb/scylla/commit/6069bab755eaa34fb6152becef626af024503def , unless this is a range scan and not a single partition query we should not have accessed the disk over and over for the same key. 

So if the "magic value" was a partition key accessed for a simple table it should have not created sstable reads.

I guess there is something else in play here.

If you would like to further check this out we need the query the magic key and schema.

**Comment by slivne** [comment]
@zhaoyuankui - not sure this is the same issue as @eyusim or not - it doesn't sound like it.

If you are running a spark job my best suggestion for you - is to add BYPASS CACHE for the spark job queries that do a scan at some point. 

The BYPASS CACHE will allow the online workload to keep on running while the analytics workload (spark job) to be run off disk effecting less the online workload. 

Let me know if this helped you or not.

**Comment by slivne** [comment]
closing this issue as there are no updates, if there is anything else to check @zhaoyuankui / @eyusim please post and we can reopen

**Comment by arunsandu1** [comment]
@slivne we started to notice similar issue, not sure if it is related to using i3en instance types we recently swapped. cluster is reporting higher latencies and requests are getting timeout with failed reads. load and cpu are normal.

```
Scylla version: 3.2.5-0.20200418.77500f9171
Cluster size: 10 nodes
OS : ubuntu
Platform: AWS i3en.3xlarge
health check report uuid: aed34175-62c6-4da7-b8c4-b4275280500a
```
schema
```
CREATE TABLE _mins_count (
    key text,
    mins_ts timestamp,
    count int,
    PRIMARY KEY (key, mins_ts)
) WITH CLUSTERING ORDER BY (mins_ts DESC)
```
range query with less than 20 rows for a given partition key.


```
2020-06-15T05:44:01.665988+00:00 10.0.xx.xx scylla:  [shard 7] storage_proxy - Exception when communicating with 10.0.xx.xx: seastar::semaphore_timed_out (Semaphore timedout)
2020-06-15T05:44:01.666030+00:00 10.0.xx.xx  scylla:  [shard 6] storage_proxy - Exception when communicating with 10.0.xx.xx: seastar::semaphore_timed_out (Semaphore timedout)
2020-06-15T05:44:01.725409+00:00 ip-10.0.xx.xx scylla:  [shard 1] storage_proxy - Exception when communicating with 10.0.xx.xx: seastar::semaphore_timed_out (Semaphore timedout)
2020-06-15T05:44:01.755779+00:00 10.0.xx.xx scylla:  [shard 4] storage_proxy - Exception when communicating with 10.0.xx.xx: seastar::semaphore_timed_out (Semaphore timedout)
2020-06-15T05:44:01.776765+00:00 10.0.xx.xx scylla:  [shard 0] storage_proxy - Exception when communicating with 10.0.xx.xx: seastar::semaphore_timed_out (Semaphore timedout)
```

We see spikes with sstable reads and queued sstables reads.
![image](https://user-images.githubusercontent.com/31780299/84622082-0f652800-ae91-11ea-9e35-65939ff29477.png)


![image](https://user-images.githubusercontent.com/31780299/84622345-9b774f80-ae91-11ea-8de6-1013f2de74bb.png)
![queuedsstablereads](https://user-images.githubusercontent.com/31780299/84622462-e7c28f80-ae91-11ea-9b57-3c7efa037a36.png)
