### ISSUE TITLE
Resharding's space requirement is not temporary

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#5261]
*Installation details*
Scylla version (or git commit hash): 7b7e4be049162b
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Below you can see that disk usage grows during resharding (expected behavior) and remains so after it finishes (buggy behavior)
https://snapshot.raintank.io/dashboard/snapshot/AoSTQsyoFblLx0LNm6Jhpftw8VPbeQ7a?orgId=2

lsof confirms that:
scylla  50775 scylla  614r      REG                9,0 1048576111 5100316826 /var/lib/scylla/data/keyspace1/standard1-31731950fe7b11e9bfc5000000000008/la-9216-big-Data.db (deleted)
scylla  50775 scylla  615r      REG                9,0 1048576111 5105182898 /var/lib/scylla/data/keyspace1/standard1-31731950fe7b11e9bfc5000000000008/la-12077-big-Data.db (deleted)
scylla  50775 scylla  616r      REG                9,0 1048576111 5100275770 /var/lib/scylla/data/keyspace1/standard1-31731950fe7b11e9bfc5000000000008/la-9750-big-Data.db (deleted)

I think the problem is that we're not refreshing row cache after the operation finishes. So disk space of input sstables remain used until cache is refreshed.

**Comment by raphaelsc** [comment]
my theory is correct, nodetool flush fixes the space issue.

**Comment by raphaelsc** [comment]
cooking a patch...

**Comment by bhalevy** [comment]
> cooking a patch...

thanks @raphaelsc 
cc @tgrabiec

**Comment by raphaelsc** [comment]
patch is sent to mailing list as [PATCH] distributed_loader: Release disk space of SSTables deleted by resharding

**Comment by avikivity** [comment]
Rare issue (involves resharding) and a workaround is available; not backporting.
