### ISSUE TITLE
Trigger regular compaction after resharding finishes

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#5262]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 7b7e4be049162b
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

Resharding should trigger regular compaction for the strategy to be satisfied, which is not true after resharding completes.

**Comment by bhalevy** [comment]
cc @xemul, fyi

**Comment by avikivity** [comment]
Aged out, no need to backport.
