### ISSUE TITLE
Filter out irrelevant partitions during compaction

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#527]
During compaction, we should skip data that does not belong to this shard or to this node:

1. When nodes are added to the cluster and this node stops being responsible for some token ranges, it should drop partitions in this range during compactions, or the special "nodetool cleanup" operation (which is a kind of compaction).
2. When booting up with a different number of shards than a previous boot (or when starting with data files from Apache Cassandra), eventually each shard should write just its own data during compactions.

We've always said we'll be doing this, but I think it's missing from the actual code...

**Comment by slivne** [comment]
@nyh, @avikivity  

First a question on what do we do when we have files that are used by multiple shards - such as when we are doing migration.

So what does compaction do on a shared when it needs to compact new sharded files with old non sharded files ?

Or did we solve it in another manner I may have unrecalled.

In general related to the scenario above:

Does origin do this ?

There is a special nodetool command for this nodetool cleanup.

I think there may be a reason to actually separate this removal to later after seeing the new node is working correctly - and not having it beeing applied automatically.

**Comment by avikivity** [comment]
We should drop partitions that don't belong to the shard like @nyh says and it should just work.

**Comment by slivne** [comment]
I think that in cassandra regular compaction does not do this as well - only cleanup removes data
