### ISSUE TITLE
Oversized allocation

### ISSUE THREAD

**Issue by ratcashdev** [scylladb/scylla#5275]
*Installation details*
Scylla version (or git commit hash): 3.1.1
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.7

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): L16s_v2 on Azure
Hardware: cores=16, memory=128GB
Disks: (SSD/HDD, count): 2 x NVMe 1.8TB in RAID0 on XFS

The syslog shows numerous reports of the following (which ultimately result in write-timeouts):
```
Nov 13 09:07:22 INT-TEST-DB-CASS-10 scylla[21370]:  [shard 9] seastar_memory - oversized allocation: 1572864 bytes. This is non-fatal, but could lead to latency and/or fragmentation issues. Please report: at   0x453c9eb
                                                     0x403d813
                                                     0x40422fb
                                                     0xf597f6
                                                     0xeeb38e
                                                     0xf6e2f1
                                                     0xf75400
                                                     0x408a6b1
                                                     0x408a8ce
                                                     0x416c65d
                                                     0x4196ccb
                                                     0x405898d
                                                     /opt/scylladb/libreloc/libpthread.so.0+0x858d
                                                     /opt/scylladb/libreloc/libc.so.6+0xfd6a2
```

Docs says, the disks perform well until 1000 queue length. Slowing down beyond that.

Config:
```
$ cat /etc/scylla.d/io.conf 
SEASTAR_IO="--num-io-queues=14 --io-properties-file=/etc/scylla.d/io_properties.yaml"
$ cat /etc/scylla.d/io_properties.yaml 
disks:
  - mountpoint: /var/lib/scylla/data
    read_iops: 801497
    read_bandwidth: 6195400192
    write_iops: 586210
    write_bandwidth: 2870956544
```

**Comment by ratcashdev** [comment]
in addition, the docs (https://docs.microsoft.com/en-us/azure/virtual-machines/linux/storage-performance) say:

> The hardware that powers the Lsv2-series VMs utilizes NVMe devices with eight I/O Queue Pairs (QP)s. Every NVMe device I/O queue is actually a pair: a submission queue and a completion queue. The NVMe driver is set up to optimize the utilization of these eight I/O QPs by distributing I/O’s in a round robin schedule. To gain max performance, run eight jobs per device to match.

> The maximum supported queue depth per I/O queue pair for Lsv2 VM NVMe device is 1024 (vs. Amazon i3 QD 32 limit). Lsv2 users should limit their (synthetic) benchmarking workloads to queue depth 1024 or lower to avoid triggering queue full conditions, which can reduce performance.

is having --num-io-queues=14 ok? Can we tell scylla to keep the limit of 1024 request per queue?

**Comment by avikivity** [comment]
Please decode the trace according to https://docs.scylladb.com/kb/decode-stack-trace/.

num-io-queues=14 is fine, it describes the scylla->kernel interface, not the kernel->hardware interface. Scylla will limit the number of requests it sends to the disk automatically, well below 1000.

**Comment by ratcashdev** [comment]
@avikivity on it.
While preparing it, do you think countless messages in the log of
```
scylla[62718]:  [shard 4] storage_proxy - Failed to remove mutations from batchlog: exceptions::mutation_write_timeout_exception (Operation timed out for system.batchlog - received only 0 responses from 1 CL=ANY.)
```
could be related? I simply fail to find a combination of 
connections_per_host, requests_per_connection and total_requests_in_flight that would avoid producing those except with extremely low values (like 1, 100, 50).

**Comment by avikivity** [comment]
That exception is typical when the server is overloaded. Do you have scylla-monitoring installed?

**Comment by ratcashdev** [comment]
yes! 
![DeepinScreenshot_select-area_20191113140459](https://user-images.githubusercontent.com/2928922/68766186-b42f3680-061e-11ea-9658-38d75ceb3ef6.png)

**Comment by ratcashdev** [comment]
@avikivity got it decoded:
[decoded.txt](https://github.com/scylladb/scylla/files/3841311/decoded.txt)

**Comment by ratcashdev** [comment]
also the /proc/interrupts (some time after those timeouts happened):
[interrupts.txt](https://github.com/scylladb/scylla/files/3841348/interrupts.txt)

**Comment by avikivity** [comment]
Looks like one of the following:
1. you are not using paged queries
2. you have huge amounts of tombstones

There is a counter in scylla-monitoring for unpaged queries.

Are you using logged batch writes? These are not recommended. Use unlogged batch, or better just write individual rows, if your workload allows it.

**Comment by ratcashdev** [comment]
2 is correct. and logged batches are also correct.
We're evaluating the possibility to use unlogged or individual statements, but that's the future.
What was the major hint at tombstones/batches? What to do with these exceptions?

**Comment by avikivity** [comment]
I saw in the trace that the coordinator is collecting lots of partitions in some vector, and that can happen when most of the partitions are deleted. And in fact that can happen when using logged batches.

You should really move away from them, and your problems will go away.

**Comment by ratcashdev** [comment]
@avikivity last question. Could those allocation issues cause write latencies in the range of 3-4s? If not, I may have to check something else too.
