### ISSUE TITLE
scylla-gdb: scylla active sstables does not work with k_l/mc sstable_mutation_reader

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5277]
`find_single_sstable_readers` looks up active sstable readers using their template arguments.
It currently only looks for `sstable_range_wrapping_reader`, but this applies only to legacy versions (< 2.1 according to comment).

Since version 3.0 we need to support `mp_row_consumer_{k_l,m}`

**Comment by avikivity** [comment]
Will backport if need arises.
