### ISSUE TITLE
Alternator cannot restart if there is a table with secondary index

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5280]
This bug was discovered by @dekimir in https://github.com/scylladb/scylla/pull/5256/commits/1151de875ac718c06b694b81aa3df891dd3fcf6f. 

When a table is created in Alternator with a secondary index (either GSI or LSI), everything works fine until you try to reboot Scylla, at which point the sstable reading code doesn't like to see the ":" character - which Alternator uses in materialized view names - in the directory path, and refuses to boot.

To reproduce this bug, run Scylla with Alternator, create a table with GSI with the following CLI command (it assumes you are running with the same security setup as needed for alternator-test):
```
AWS_ACCESS_KEY_ID=alternator AWS_SECRET_ACCESS_KEY=secret_pass aws --endpoint-url 'http://127.0.0.1:8000' dynamodb create-table --table-name abc4 --attribute-definitions AttributeName=x,AttributeType=S --key-schema AttributeName=x,KeyType=HASH --billing-mode PAY_PER_REQUEST --global-secondary-indexes "IndexName=hello,KeySchema=[{AttributeName=x,KeyType=HASH}],Projection={ProjectionType=ALL}"
```
Then put some data in it (without any rows, there will be no sstables):
```
AWS_ACCESS_KEY_ID=alternator AWS_SECRET_ACCESS_KEY=secret_pass aws --endpoint-url 'http://127.0.0.1:8000' dynamodb put-item --table-name abc4 --item '{"x": { "S": "value"}}'
```
Now, "killall scylla" (**not** with -9, to give Scylla a chance to flush sstables) and wait for the sstables to be flushed.
Now run Scylla again on the same data directory, and see this in the log:

```
INFO  2019-11-14 16:20:46,426 [shard 0] init - Startup failed: std::runtime_error (Exception while populating keyspace 'alternator' with column family 'abc4:hello' from file '/home/nyh/scylla.maintainer/tmp/1/data/alternator/abc4:hello-40b4354206e911ea8ee0000000000001': sstables::malformed_sstable_exception (invalid version for file mc-2-big-CompressionInfo.db with path /home/nyh/scylla.maintainer/tmp/1/data/alternator/abc4:hello-40b4354206e911ea8ee0000000000001. Path doesn't match known pattern.))
```

The problem is in `entry_descriptor::make_descriptor()`, which has:
```c++
    static std::regex dir(".*/([^/]*)/(\\w+)-[\\da-fA-F]+(?:/staging|/upload|/snapshots/[^/]+)?/?");
```
The "`\w`" is needlessly restrictive. It could have been just `.` or better `[^/]` to allow any character in table names. Or, if for some reason we don't want that, at least `(\w|[:!])` to allow this ':' and '!' character which Alternator uses for GSI and LSI respectively.

**Comment by nyh** [comment]
Backported to 3.2 as this fixes a serious bug for Alternator. Previous releases did not have Alternator so this patch isn't interesting for them.

**Comment by avikivity** [comment]
No vulernable branches remain.
