### ISSUE TITLE
name reader concurrency semaphores

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#5281]
We should do to reader concurrency semaphores what https://github.com/scylladb/scylla/pull/5269 is doing for all regular semaphores in the codebase, that is name them and add this name to error messages generated from said semaphores.
We have three concurrency semaphores: user, system and streaming and albeit conceptually they do have names, these are not propagated down to the semaphore itself.

**Comment by denesb** [comment]
This would greatly help with debugging problems, as these semaphores are some of the most often timing out ones.

**Comment by tgrabiec** [comment]
I'd also throw the ones we have on the write path: in the commitlog (`segment_manager::_request_controller`) and before the memtable (`region_group::run_when_memory_available()`)
