### ISSUE TITLE
Data expired via TTL is returned with null values for a short period of time

### ISSUE THREAD

**Issue by eyusim** [scylladb/scylla#5290]
*Installation details*
Scylla version (or git commit hash): 2.1.6 / 3.1.1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

We have noticed after upgrading from 2.0 -> 3.1.1 (starting with 2.1.6) that scylla will return rows that have been recently expired due to TTL with null values in non-key columns. 

This issue happens in both 2.1.6 and 3.1.1. 

Below is python code to reproduce the issue (just change the port in the Cluster constructor). 

The code inserts 2 rows with same partition key, one row has a 5 second ttl and the other 1 hour. Continuous querying of the data will show that about 5 times the query returns 2 rows with the expired rows data having been wiped out but it's still being returned. 

Running the code against a docker container for the latest cassandra or scylla 2.0.2 behaves as you would expect, with the result set eventually being 1 row and no missing data in-between. 

```python
from cassandra.cluster import Cluster
import time

cluster = Cluster(['localhost'], port=9043)

session = cluster.connect()
session.execute('drop keyspace if exists ttltest ')

session.execute("""create keyspace if not exists ttltest WITH replication = { 'class': 'SimpleStrategy', 'replication_factor': '1' }""")
session.set_keyspace('ttltest')

session.execute("""
create table if not exists data_with_ttl(
            thekey text,
            num bigint,
            data text,
            PRIMARY KEY (thekey, num)
          ) 
""")

session.execute("insert into data_with_ttl (thekey, num, data) values('key1', 123, 'long live data') using TTL 3600")
session.execute("insert into data_with_ttl (thekey, num, data) values('key1', 456, 'quick expire data') using TTL 5")

tries = 0
while tries < 100:
    tries = tries + 1
    rows = session.execute("select * from data_with_ttl where thekey = 'key1'")
    resultSize = len(rows.current_rows)
    print "try number:", tries, "result size:", resultSize
    for row in rows:
        print '\t',  row.num, row.data
    if resultSize == 1:
        break
    time.sleep(0.2)

session.execute('drop keyspace ttltest')

```

**Comment by tzach** [comment]
Look like https://github.com/scylladb/scylla/issues/4263

**Comment by slivne** [comment]
@haaawk please assign to have someone look at this

**Comment by avikivity** [comment]
Backported to 3.0, 3.1, 3.2.

**Comment by avikivity** [comment]
Already backported.
