### ISSUE TITLE
Scylladb Nodes seems intermittently restarting.

### ISSUE THREAD

**Issue by mnpaliwaldse** [scylladb/scylla#5292]
Scylladb Nodes seems intermittently restarting. Please find attached node_health_check script output, output_files.tgz
Is there a tool via which we can analyze coredump file generated when syclladb shuts down.
In one of the server. The coredump size is of 91GB

Does Scylladb uses Garbage Collector? We found scylla-jmx component though.
Are there any specific/important parameters in SerialGC which scylladb uses which we can set.

We are using scylla db version 3.0.rc4-0.20190106.5a178ff63

**Comment by dorlaor** [comment]
The tool to analyze the core dump is gdb. You didn't provide the
logs/upload.
You're using an old RC release, pls move to a formal release.
Logs will be helpful. The scylla jmx is Java based but normally is fine
regarding GC

**Comment by mnpaliwaldse** [comment]
Hey Dor

Thanks for replying, unfortunately my company seems not allowing
output_files.gz and github seems not allowing files greater than 10MB.
Is there any way to send coredump file except github etc

--Aman Paliwal

**Comment by glommer** [comment]
There is but I would not worry about it for now

As Dor said, this is an rc version and not an official release. Plus is old.

We would kindly ask you to move to the latest 3.0 patch and the issue will
likely be fixed.

If it is not, then we would be happy to look at it

**Comment by mnpaliwaldse** [comment]
Hey Costa/Dor

Thanks Guys for replying.
This is seed node logs which is DN and not starting. Also we dont have
internet on those machines. Scylladb doesnt seems have tarball for now i
think.
Is there any rpm list for 3.1 version as you guys were suggesting?

Nov 16 18:43:26 NVMBD2ALT03D00 scylla[1322307]: 0x0000000001c0e172
Nov 16 18:43:26 NVMBD2ALT03D00 scylla[1322307]: 0x0000000001c101b1
Nov 16 18:43:26 NVMBD2ALT03D00 scylla[1322307]: 0x00000000005a015e
Nov 16 18:43:26 NVMBD2ALT03D00 scylla[1322307]: 0x00000000005a0321
Nov 16 18:43:26 NVMBD2ALT03D00 scylla[1322307]: 0x000000000066e9b7
Nov 16 18:43:26 NVMBD2ALT03D00 scylla[1322307]: 0x000000000067312a
Nov 16 18:43:26 NVMBD2ALT03D00 scylla[1322307]: 0x00000000007561bd
Nov 16 18:43:26 NVMBD2ALT03D00 scylla[1322307]:
/lib64/libpthread.so.0+0x0000000000007e24
Nov 16 18:43:26 NVMBD2ALT03D00 scylla[1322307]:
/lib64/libc.so.6+0x00000000000f834c
Nov 16 18:46:06 NVMBD2ALT03D00 scylla[1325017]: Scylla version
3.0.rc4-0.20190106.5a178ff63 starting ...
Nov 16 18:49:01 NVMBD2ALT03D00 scylla[1325017]:  [shard 13] seastar - Timer
callback failed: std::bad_alloc (std::bad_alloc)
Nov 16 18:49:09 NVMBD2ALT03D00 scylla[1325017]:  [shard 0] storage_proxy -
Exception when communicating with 10.140.2.20: std::runtime_error (SSTable
reader found an ex
Nov 16 18:49:15 NVMBD2ALT03D00 scylla[1325017]:  [shard 0] storage_proxy -
Exception when communicating with 10.140.2.20: std::bad_alloc
(std::bad_alloc)
Nov 16 18:49:21 NVMBD2ALT03D00 scylla[1325017]:  [shard 0] storage_proxy -
Exception when communicating with 10.140.2.20: std::bad_alloc
(std::bad_alloc)
Nov 16 18:49:53 NVMBD2ALT03D00 scylla[1325017]:  [shard 1] storage_proxy -
Exception when communicating with 10.140.2.20: std::runtime_error (SSTable
reader found an ex
Nov 16 18:49:54 NVMBD2ALT03D00 scylla[1325017]:  [shard 1] storage_proxy -
Exception when communicating with 10.140.2.20: std::runtime_error (SSTable
reader found an ex
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]: Aborting on shard 13.
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]: Backtrace:
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]: 0x00000000006a7682
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]: 0x00000000005bedac
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]: 0x00000000005bf055
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]: 0x00000000005bf103
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]:
/lib64/libpthread.so.0+0x000000000000f5df
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]:
/lib64/libc.so.6+0x00000000000351f6
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]:
/lib64/libc.so.6+0x00000000000368e7
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]: 0x00000000007385ec
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]: 0x000000000073887c
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]: 0x00000000008d1b6f
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]: 0x0000000001b43ad5
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]: 0x0000000001bc5095
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]: 0x0000000001bc59f6
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]: 0x0000000001c060be
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]: 0x0000000001c0e172
Nov 16 18:50:09 NVMBD2ALT03D00 scylla[1325017]: 0x0000000001c101b1

--Aman Paliwal

**Comment by slivne** [comment]
@mnpaliwaldse 

you can follow https://docs.scylladb.com/troubleshooting/report_scylla_problem/ to report and upload files / cores.

have you upgraded to a non rc version release

if you still need help in resolving this - pleas epost following an upgrade to a non rc version and we will reopen the issue and try to resolve this.
