### ISSUE TITLE
nodetool cfstats make reading statistics wrong

### ISSUE THREAD

**Issue by roseboych** [scylladb/scylla#5295]
I run “select * from cftest. info where id = 1” on a table,
and see nodetool cfstats the reading statistics + 1 
 but when I read without where clause(select * from cftest. info) the reading statistics is wrong.
is it a bug? 
i also have a test on cassandra, it is same with scylla.

**Comment by slivne** [comment]
there is a difference between the two queries

the *where* version is a single partition read

the *no where* version is a range scan

scylla will expose different metrics for range scans and regular reads https://github.com/scylladb/scylla/issues/5209
