### ISSUE TITLE
Getting compilation error on message/messaging_service.cc with Ubuntu 14.04

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#530]
Here's an error message:
```
FAILED: g++-5 -MMD -MT build/release/message/messaging_service.o -MF build/release/message/messaging_service.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I/home/syuu/scylla/seastar -I/home/syuu/scylla/seastar/build/release/gen  -march=nehalem -DHAVE_DPDK -I/home/syuu/scylla/seastar/build/dpdk/include -march=corei7 -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2 -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof    -O2 -I/usr/include/jsoncpp -Wno-maybe-uninitialized  -I. -I build/release/gen -I seastar -I seastar/build/release/gen -c -o build/release/message/messaging_service.o message/messaging_service.cc
message/messaging_service.cc: In member function ‘void net::messaging_service::foreach_server_connection_stats(std::function<void(const rpc::client_info&, const rpc::stats&)>&&) const’:
message/messaging_service.cc:217:14: error: ‘struct net::messaging_service::rpc_protocol_server_wrapper’ has no member named ‘foreach_connection’
     _server->foreach_connection([f](const rpc_protocol::server::connection& c) {
              ^
message/messaging_service.cc: In lambda function:
message/messaging_service.cc:218:18: error: passing ‘const rpc::protocol<net::serializer, net::messaging_verb>::server::connection’ as ‘this’ argument discards qualifiers [-fpermissive]
         f(c.info(), c.get_stats());
                  ^
In file included from message/messaging_service.cc:34:0:
/home/syuu/scylla/seastar/rpc/rpc.hh:90:19: note:   in call to ‘auto& rpc::protocol<Serializer, MsgType>::server::connection::info() [with Serializer = net::serializer; MsgType = net::messaging_verb]’
             auto& info() { return _info; }
                   ^
message/messaging_service.cc:218:23: error: ‘const class rpc::protocol<net::serializer, net::messaging_verb>::server::connection’ has no member named ‘get_stats’
         f(c.info(), c.get_stats());
                       ^
ninja: build stopped: subcommand failed.
make[1]: *** [override_dh_auto_build] Error 1
make[1]: Leaving directory `/home/syuu/scylla'
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
debuild: fatal error at line 1364:
dpkg-buildpackage -rfakeroot -D -us -uc failed
```

**Comment by amnonh** [comment]
It seems like you are missing a seastar patch

**Comment by tgrabiec** [comment]
Did you try `git submodule update --init --recursive -f` ?

**Comment by syuu1228** [comment]
No I haven't tried with "-f". I'm rebuilding with it now

**Comment by avikivity** [comment]
On 11/05/2015 10:04 AM, Takuya ASADA wrote:
>
> Here's an error message:
>
> |FAILED: g++-5 -MMD -MT build/release/message/messaging_service.o -MF 
> build/release/message/messaging_service.o.d -std=gnu++1y -g -Wall 
> -Werror -fvisibility=hidden -pthread -I/home/syuu/scylla/seastar 
> -I/home/syuu/scylla/seastar/build/release/gen -march=nehalem 
> -DHAVE_DPDK -I/home/syuu/scylla/seastar/build/dpdk/include 
> -march=corei7 -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2 
> -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3 
> -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2 
> -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2 
> -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof 
> -O2 -I/usr/include/jsoncpp -Wno-maybe-uninitialized -I. -I 
> build/release/gen -I seastar -I seastar/build/release/gen -c -o 
> build/release/message/messaging_service.o message/messaging_service.cc 
> message/messaging_service.cc: In member function ‘void 
> net::messaging_service::foreach_server_connection_stats(std::function<void(const 
> rpc::client_info&, const rpc::stats&)>&&) const’: 
> message/messaging_service.cc:217:14: error: ‘struct 
> net::messaging_service::rpc_protocol_server_wrapper’ has no member 
> named ‘foreach_connection’ _server->foreach_connection([f](const 
> rpc_protocol::server::connection& c) { |


Maybe it's right.  Try changing it to

|_server->template foreach_connection([f](const 
rpc_protocol::server::connection& c) {|



> |^ message/messaging_service.cc: In lambda function: 
> message/messaging_service.cc:218:18: error: passing ‘const 
> rpc::protocol<net::serializer, 
> net::messaging_verb>::server::connection’ as ‘this’ argument discards 
> qualifiers [-fpermissive] f(c.info(), c.get_stats()); ^ In file 
> included from message/messaging_service.cc:34:0: 
> /home/syuu/scylla/seastar/rpc/rpc.hh:90:19: note: in call to ‘auto& 
> rpc::protocol<Serializer, MsgType>::server::connection::info() [with 
> Serializer = net::serializer; MsgType = net::messaging_verb]’ auto& 
> info() { return _info; }|

This was added Nov 2.  Is your seastar synced to the right version?

**Comment by amnonh** [comment]
On Thu, Nov 5, 2015 at 10:14 AM, Avi Kivity <notifications@github.com>
wrote:

>
>
> On 11/05/2015 10:04 AM, Takuya ASADA wrote:
> >
> > Here's an error message:
> >
> > |FAILED: g++-5 -MMD -MT build/release/message/messaging_service.o -MF
> > build/release/message/messaging_service.o.d -std=gnu++1y -g -Wall
> > -Werror -fvisibility=hidden -pthread -I/home/syuu/scylla/seastar
> > -I/home/syuu/scylla/seastar/build/release/gen -march=nehalem
> > -DHAVE_DPDK -I/home/syuu/scylla/seastar/build/dpdk/include
> > -march=corei7 -DRTE_MACHINE_CPUFLAG_SSE -DRTE_MACHINE_CPUFLAG_SSE2
> > -DRTE_MACHINE_CPUFLAG_SSE3 -DRTE_MACHINE_CPUFLAG_SSSE3
> > -DRTE_MACHINE_CPUFLAG_SSE4_1 -DRTE_MACHINE_CPUFLAG_SSE4_2
> >
> -DRTE_COMPILE_TIME_CPUFLAGS=RTE_CPUFLAG_SSE,RTE_CPUFLAG_SSE2,RTE_CPUFLAG_SSE3,RTE_CPUFLAG_SSSE3,RTE_CPUFLAG_SSE4_1,RTE_CPUFLAG_SSE4_2
>
> > -Wno-error=literal-suffix -Wno-literal-suffix -Wno-invalid-offsetof
> > -O2 -I/usr/include/jsoncpp -Wno-maybe-uninitialized -I. -I
> > build/release/gen -I seastar -I seastar/build/release/gen -c -o
> > build/release/message/messaging_service.o message/messaging_service.cc
> > message/messaging_service.cc: In member function ‘void
> >
> net::messaging_service::foreach_server_connection_stats(std::function<void(const
>
> > rpc::client_info&, const rpc::stats&)>&&) const’:
> > message/messaging_service.cc:217:14: error: ‘struct
> > net::messaging_service::rpc_protocol_server_wrapper’ has no member
> > named ‘foreach_connection’ _server->foreach_connection([f](const
> > rpc_protocol::server::connection& c) { |
>
>
> Maybe it's right. Try changing it to
>
> |_server->template foreach_connection([f](const
> rpc_protocol::server::connection& c) {|
>
>
>
> > |^ message/messaging_service.cc: In lambda function:
> > message/messaging_service.cc:218:18: error: passing ‘const
> > rpc::protocol<net::serializer,
> > net::messaging_verb>::server::connection’ as ‘this’ argument discards
> > qualifiers [-fpermissive] f(c.info(), c.get_stats()); ^ In file
> > included from message/messaging_service.cc:34:0:
> > /home/syuu/scylla/seastar/rpc/rpc.hh:90:19: note: in call to ‘auto&
> > rpc::protocol<Serializer, MsgType>::server::connection::info() [with
> > Serializer = net::serializer; MsgType = net::messaging_verb]’ auto&
> > info() { return _info; }|
>
> This was added Nov 2. Is your seastar synced to the right version?
>
> > |^ message/messaging_service.cc:218:23: error: ‘const class
> > rpc::protocol<net::serializer,
> > net::messaging_verb>::server::connection’ has no member named
> > ‘get_stats’ f(c.info(), c.get_stats()); ^ ninja: build stopped:
>
the same patch that added get_stats made info const
that's why I think maybe it's a git issue

can you get seastar head manually and test?

**Comment by syuu1228** [comment]
"git submodule update --init --recursive -f" solves the problem, thanks
