### ISSUE TITLE
stop migration_manager before we stop the database layer

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5300]
Derived from [#5274](https://github.com/scylladb/scylla/issues/5274#issuecomment-555031846)
> The `mutation_write_failure_exception` exception which happens after the node is stopped is probably due to the fact that the database layer is stopped earlier and rejects writes to `system.local` as well (refs #5196). This is benign.
> 
> We should stop `migration_manager` before we stop the database layer (and before stopping RPC).

**Comment by avikivity** [comment]
Benign, so not backporting.
