### ISSUE TITLE
scylla setup get stuck in an air gapped system

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla#5302]
It looks like a repetition to Issue #4462, but now in 3.1.
*Installation details*
Scylla version (or git commit hash):3.1.1-0.20191024.f32ec885c
Cluster size:4 
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos 7.7
The following code now moved to: /usr/lib/scylla/libexec/scylla_setup
Causing Scylla_setup to halt forever when the nodes are not connected to the internet, it seems that the housekeeping is insisting on understanding if it is the latest version.

```
 if len(cur_version) > 0:
        if is_debian_variant():
            new_version=out('sudo -u scylla /usr/lib/scylla/scylla-housekeeping --uuid-file /var/lib/scylla-housekeeping/housekeeping.uuid --repo-files \'/etc/apt/sources.list.d/scylla*.list\' version --version {} --mode i'.format(cur_version), shell=True, exception=False)
        else:
            new_version=out('sudo -u scylla /usr/lib/scylla/scylla-housekeeping --uuid-file /var/lib/scylla-housekeeping/housekeeping.uuid --repo-files \'/etc/yum.repos.d/scylla*.repo\' version --version {} --mode i'.format(cur_version), shell=True, exception=False)
        if len(new_version) > 0:
            print(new_version)
    else:
        if is_debian_variant():
            new_version=out('sudo -u scylla /usr/lib/scylla/scylla-housekeeping --uuid-file /var/lib/scylla-housekeeping/housekeeping.uuid --repo-files \'/etc/apt/sources.list.d/scylla*.list\' version --version unknown --mode u', shell=True, exception=False)
        else:
            new_version=out('sudo -u scylla /usr/lib/scylla/scylla-housekeeping --uuid-file /var/lib/scylla-housekeeping/housekeeping.uuid --repo-files \'/etc/yum.repos.d/scylla*.repo\' version --version unknown --mode u', shell=True, exception=False)
        print('A Scylla executable was not found, please check your installation {}'.format(new_version))
```

**Comment by tzach** [comment]
@amnonh ?

**Comment by amnonh** [comment]
@syuu1228 I think that the python script does not give up, maybe we can add a timeout to it?

**Comment by slivne** [comment]
@amnonh please send a fix

**Comment by nyh** [comment]
Since installation on a non-Internet-connected system is a feature we want to maintain, we should probably test it. Do we have tests for the installation procedure? If not, we should have such tests. If we do already have such test(s), we should make at least one of them run on VMs without a connection to the Internet, to verify this feature continues to work.

**Comment by tzach** [comment]
Offline install is not available yet https://github.com/scylladb/scylla/issues/3306
but we can move there step by step (in this case, better error handling)

**Comment by avikivity** [comment]
Aged out, no need to backport.
