### ISSUE TITLE
CDC: make schema management operate on migration manager subscriptions instead

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#5315]
Right now, CDC schema introspection (i.e. check options and create log table etc) is hung up in alter/create schema statement in cql3. 

CDC should exist as a "service" (or even better, sub-object to either database or storage proxy) and subscribe to migration manager notifications on schema updates. 

This has one somewhat notable drawback of course, namely that this will see notifications from both locally and other nodes. Thus creating log schema might race across all nodes receiving a base schema update/create. However, the schema generated should be compatible across all nodes (we can even ensure the UUID is the same for all generators), so should reconcile pretty fast. Even more so for schema alters. 

The big benefits are not being tied to cql3 (alternator etc) and also making log schema update somewhat more "safe" in the sense that iff originating node creates base schema, sends it out, but crashes before the resulting future becomes avail and the current code to check the schema is reached, the log should be created by someone else, without waiting for the original node to restart (assuming we have schema scan on startup).

**Comment by elcallio** [comment]
This was fixed by PR #5366

**Comment by slivne** [comment]
fixed by 8157f530f5573b44273e37ff285813a536f9defc
