### ISSUE TITLE
redis-test - tests failing

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5317]
Right now when I run `pytest` in `redis-test`, I see two tests failing:

1. `test_del_non_existent_key` fails because delete of a non-existant key returns 1 (key requested to be deleted) instead of 0 (keys actually deleted).

2. `test_select` fails because `SELECT 1` returns 0 instead of None (I don't know what this means).

@fastio, if these tests are known inconsistencies with Redis (I know the first one is), they should be marked with `@pytest.mark.xfail`, i.e., an "expected failure", so we don't think this is a regression. You can see an example of how to use xfail in `alternator-test/`.
The goal is that `pytest` should always remain successful (with potentially some "expected failures") unless we have a real regression. I don't want to see a red "2 failed" every time I run the tests.

Also, if you have known issues like the deletion count, it would be nice to open issues for them in this bug tracker (and also refer to this issue number in the xfail string). You can use the new "Redis API" label I created for these issues to make it easier for you to search all the Redis API issues.

**Comment by amoskong** [comment]
fixed by: https://github.com/scylladb/scylla/pull/5381

**Comment by slivne** [comment]
fixed by 5b2f35a21a1a542383ce8b087742b56729381708
