### ISSUE TITLE
Serialize calls to 'nodetool cleansnapshot'

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#5318]
*Installation details*
HEAD: 486e3f94d037738c2f322e890ada42fdbd43048b

*Description*
`nodetool cleansnapshot` operation is a highly parallelized operation that runs on a set of files and potentially deletes them according to given parameters.

When two or more such operations run on the same set of files at the same time this may lead to various FS-level errors like "No such file".

I don't see much added value in being able to run multiple `nodetool` in parallel on the same host in general and `nodetool cleansnapshot ...` in particular.

However if we still want to preserve the multiple `nodetool cleansnapshot...` commands execution in parallel we should at least serialize them on the CF level.

**Comment by slivne** [comment]
We can either
- fail the second and force the user to run again.
- create a queue

**Comment by vladzcloudius** [comment]
> We can either
> 
>     * fail the second and force the user to run again.
> 
>     * create a queue

@slivne IMO the former is simpler and is good enough.
From my experience this use case is usually not intended, thus the sooner it's discovered (via seeing errors) the better.

**Comment by bhalevy** [comment]
Ref #5603

**Comment by bhalevy** [comment]
@slivne with #4557 and #5603 fixed I don't think there's anything more to do for this issue and it can be closed.

**Comment by slivne** [comment]
closing :)
