### ISSUE TITLE
alternator test_health_only_works_for_root_path failing

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5321]
The test `test_health_only_works_for_root_path` fails on my development machine while checking the URL "`http://localhost:8000/..`" - that case returns 200 (success) instead of the expected 404 (error). The same URL also unexpectedly succeeds with both Curl and Firefox.

However, it the reason this URL works on all these tools is that the client actually does some canonization of the URL before passing it to the server, and drops this "..".  I confirmed with wireshark that the test sent "/", not "/..", as the URL. I also confirmed had the test actually sent "/..", it would have failed:

```
$ echo 'GET /.. HTTP/1.1\r\n' | nc localhost 8000
HTTP/1.1 404 Not Found
...
```

@psarna I think we should just drop the '../' from this test. I don't think it's worth the extra hassle of working around the Python HTTP client and using TCP directly (plus, if we do that, we'll also need to implement the https version).

**Comment by psarna** [comment]
Certainly, feel free to drop it. I also noticed some tools (like Firefox) canonizalize `/..`, but if this test case makes your pytest fail then it's definitely not worth keeping.

**Comment by avikivity** [comment]
Alternator test fix, not backporting.
