### ISSUE TITLE
Implement the atomic DEL command in Scylla to support the multiple keys.

### ISSUE THREAD

**Issue by fastio** [scylladb/scylla#5334]
The current implementation of Redis DEL command in Scylla does not support to delete multiple keys.
It should support delete multiple keys atomically, return the number of actually deleted keys.

As @nyh mentioned in the [Redis API in Scylla](https://github.com/scylladb/scylla/pull/5132) , there features should be supported eventually.

**Comment by nyh** [comment]
@fastio, what did you mean "delete multiple keys atomically" - if one of them is missing, none of the deletes are done? Is this a Redis feature?
I'm aware of two things that the current code is missing, please correct me if this is the wrong list:
1. We need to support the *syntax* of deleting multiple keys in one DEL command.
2. We need to support DEL's feature of returning the number of really deleted keys. I don't know how we can do this efficiently, as this requires a read-before-write (LWT, if we want to be really consistent), which will significantly slow us down. I wonder how often users actually use the return value of DEL, and if they don't often do - maybe it makes sense to have an option to not support it.

**Comment by fastio** [comment]
>  @fastio, what did you mean "delete multiple keys atomically" - if one of them is missing, none of the deletes are done? Is this a Redis feature?

Sorry, It's a mistake here. I want say that we can delete multiple keys at once using the DEL command of Redis.  In the Redis implementation, the DEL command does not remove multiple keys
atomically. The command returns the number of removed keys in the operation.

> I'm aware of two things that the current code is missing, please correct me if this is the wrong list:
> 
> 1. We need to support the syntax of deleting multiple keys in one DEL command.
> 2. We need to support DEL's feature of returning the number of really deleted keys. 
> I don't know  how we can do this efficiently, as this requires a read-before-write (LWT, if we want to be really consistent), which will significantly slow us down. I wonder how often users actually use the return value of DEL, and if they don't often do - maybe it makes sense to have an option to not support it.

You are right. I agree with you. I think users are concerned about whether the keys are deleted correctly in most use scenarios.
