### ISSUE TITLE
Change experimental flag granularity to per feature

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla#5338]
The current experimental flag has a granularity of all features. This means that if one of the features is broken it might force the user to turn off the experimental flag altogether, preventing him from using the features that do work.
An example for this situation is #5288 where this solution is suggested, where CDC breaks rolling upgrade from 3.1 to 3.2 forcing turning off the experimental flag and not using LWT since it is also experimental.
The solution suggested in #5288 needs to be implemented, it is roughly outlined in https://github.com/scylladb/scylla/issues/5288#issuecomment-557110306

**Comment by avikivity** [comment]
Already backported to 3.2, not backporting to already-released branches.

**Comment by avikivity** [comment]
(as this is essentially a small feature)

**Comment by dekimir** [comment]
Are all three argument values valid in 3.2?
