### ISSUE TITLE
repair: rx_hashes_nr metrics are not updated correctly

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#5339]
In get_full_row_hashes_with_rpc_stream and
repair_get_row_diff_with_rpc_stream_process_op which were introduced in
the "Repair switch to rpc stream" series, rx_hashes_nr metrics are not
updated correctly.

**Comment by tgrabiec** [comment]
What is the effect on users?

**Comment by asias** [comment]
Nothing. It is introduced in 3.2 only which is not released yet.

**Comment by avikivity** [comment]
Aged out (and never had a vulnerable release).
