### ISSUE TITLE
Collection [de]serialization operates on contiguous buffers

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#5341]
Serializing or deserializing collections happens with usage of contiguous buffers. This puts a large strain on the memory allocator.

While the proper solution to this would be to get rid of this internal serializtion and deserializtion altogether, doing that is a major effort with a lot of unknowns. To relieve the pain caused by these large allocations, we should change the de/serialization code to work on fragmented buffers in the meanwhile.

This is point (1a) and (3) of #3602.

**Comment by slivne** [comment]
@bhalevy I assigned it to botond please prioritize it.

**Comment by denesb** [comment]
I already started working on this.

**Comment by avikivity** [comment]
A large and dangerous change, so not backporting for now.
