### ISSUE TITLE
database.cc:1763: database::truncate(const keyspace&, column_family&, database::timestamp_func, bool)

### ISSUE THREAD

**Issue by eliranshlomo1** [scylladb/scylla#5345]
*Installation details*
Scylla version (or git commit hash): scylla-server-3.1.1-0.20191024.f32ec885c.el7.x86_64
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos 7 (ami-027c1337dcb46da50)

Platform (physical/VM/cloud instance type/docker): aws  i3.4xlarge
Disks: 2 nvme

UUID: 4707ad52-c266-4e2e-8eb7-e992d9871336

Nodes crash when trying to drop\truncate conter table

`scylla: scylla: database.cc:1763: database::truncate(const keyspace&, column_family&, database::timestamp_func, bool)::<lambda()>::<lambda()> mutable::<lambda()>::<lambda(db_clock::time_point)>::<lambda()>::<lambda(db::replay_position)>: Assertion `low_mark <= rp || rp == db::replay_position()' failed.
scylla: Aborting on shard 5.
scylla: Backtrace:
scylla: 0x000000000419fed2
scylla: 0x000000000408d1e5
scylla: 0x000000000408d4e5
scylla: 0x000000000408d593
scylla: 0x00007fc44899302f
scylla: /opt/scylladb/libreloc/libc.so.6+0x000000000003853e
scylla: /opt/scylladb/libreloc/libc.so.6+0x0000000000022894
scylla: /opt/scylladb/libreloc/libc.so.6+0x0000000000022768
scylla: /opt/scylladb/libreloc/libc.so.6+0x00000000000309f5
scylla: 0x0000000000a94553
scylla: 0x000000000408a6b1
scylla: 0x000000000408a8ce
scylla: 0x000000000416c65d
scylla: 0x0000000004196ccb
scylla: 0x000000000405898d
scylla: /opt/scylladb/libreloc/libpthread.so.0+0x000000000000858d
scylla: /opt/scylladb/libreloc/libc.so.6+0x00000000000fd6a2`

table desc:
`CREATE TABLE member_challenge_points_count (
    member_id ascii,
    challenge_id int,
    points counter,
    PRIMARY KEY (member_id, challenge_id)
) WITH CLUSTERING ORDER BY (challenge_id ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';`

**Comment by elcallio** [comment]
Does this happen every time? 
How is the table populated? Any chance of providing a simple repro-case?

**Comment by barakseri1** [comment]
Yes, it happens on every truncate.
The tables are populated with regular inserts, and to reproduce it we just need to truncate the table, whether via a simple cql command or using the php driver

**Comment by elcallio** [comment]
So obviously this works fine for me, so I am gonna need some more info. Could you provide a script/program that inserts data causing the issue to reproduce? How much data is inserted before the truncate?
Are you running a single node? The above has 8 logical cores, no?

**Comment by fruch** [comment]
one more user is facing this issue: https://scylladb-users.slack.com/archives/C2NLNBXLN/p1594797476326800

**Comment by nyh** [comment]
In issue #6995 this happens specifically with auto_snapshot = 0. @eliranshlomo1 could you have been using the auto_snapshot = 0 configuration option?

**Comment by eliranshlomo1** [comment]
@nyh Yes,
in our configuration it set to auto_snapshot: false

**Comment by nyh** [comment]
Thanks for confirming. Then this is almost certainly a dup of #6995. Patch is already on "next" branch, should appear in master branch today and in other branches later. Closing as a dup.
