### ISSUE TITLE
swagger: wrong return type of `column_family/metrics/total_disk_space_used`

### ISSUE THREAD

**Issue by zimnx** [scylladb/scylla#5347]
*Installation details*
Scylla version (or git commit hash): master

[API](https://github.com/scylladb/scylla/blob/master/api/column_family.cc#L554) endpoint [returns uint64_t](https://github.com/scylladb/scylla/blob/master/api/column_family.cc#L218) but swagger file [returns integer](https://github.com/scylladb/scylla/blob/master/api/api-doc/column_family.json#L1623) which maps to int32. 
Other endpoints around may also have wrong return type.

**Comment by amnonh** [comment]
Unfortunately, we are limited to swagger 1.2 type formats.
I will change it to long

**Comment by avikivity** [comment]
No vulnerable active branches.
