### ISSUE TITLE
./tools/toolchain/dbuild ./reloc/build_rpm.sh fails

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#5350]
I was on 3.1.1 branch with Avi's dbuild patch for podman. 

./tools/toolchain/dbuild ./reloc/build_rpm.sh fails the "Cannot rename directory". I tried a simple dnf update inside the dbuild docker it fails too. I suspect there is something run with the docker images. 

$ docker images
docker.io/scylladb/scylla-toolchain   fedora-29-20190405   4911afdbcd5c   7 months ago    1.38 GB

$ ./tools/toolchain/dbuild -it -- bash

bash-4.4# dnf update
...

Cannot rename directory "/var/cache/dnf/fedora-modular-ce4dd907f26812da/tmpdir.wszKIB/repodata" to "/var/cache/dnf/fedora-modular-ce4dd907f26812da/repodata": Directory not empty
Error: Cannot rename directory "/var/cache/dnf/fedora-modular-ce4dd907f26812da/tmpdir.wszKIB/repodata" to "/var/cache/dnf/fedora-modular-ce4dd907f26812da/repodata": Directory not empty

**Comment by avikivity** [comment]
It is probably a bug in fuse-overlayfs.

**Comment by avikivity** [comment]
Well, dnf update worked for me in a podman container. Please make sure you're running the latest kernel and are fully updated.

Worked for me with 5.3.11-300.fc31.x86_64.

**Comment by asias** [comment]
The system is fully updated. Mine is 5.3.11-300.fc31.x86_64 too.

**Comment by avikivity** [comment]
Try to report it upstream.

**Comment by asias** [comment]
Same host, same dbuild, different images: dnf update works fine in fedora-31-20191119 but fails in fedora-29-20190405. Looks like an image issue?

docker.io/scylladb/scylla-toolchain   fedora-31-20191119 
docker.io/scylladb/scylla-toolchain   fedora-29-20190405

**Comment by avikivity** [comment]
Does the "bad" image fail in docker? If not, it's a fuse-overlayfs problem.

**Comment by asias** [comment]
> Does the "bad" image fail in docker? If not, it's a fuse-overlayfs problem.

I do not have docker on my f31 box ;(

**Comment by avikivity** [comment]
I ran `podman run -it --rm fedora:29 dnf -y update` and it succeded.

**Comment by avikivity** [comment]
> > Does the "bad" image fail in docker? If not, it's a fuse-overlayfs problem.
> 
> I do not have docker on my f31 box ;(

I'm sure you can figure out how to install it.

**Comment by avikivity** [comment]
Ah, the "bad" image fails for me too.

**Comment by slivne** [comment]
@asias / @avikivity can I close this ?

**Comment by avikivity** [comment]
I tried again, and it worked.
