### ISSUE TITLE
row level repair: add timetout to reads executed as part of the repair

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#5359]
Scylla version (or git commit hash): master(4160b36), 3.2, 3.1

We recently saw repairs blocking and not making progress for a prolonged time (days). One of he primary suspects is reads belonging to several repairs deadlocking on the streaming read concurrency semaphore. This is something that we've seen in the past during internal testing, and
although theoretically we have fixed it, such deadlocks are notoriously hard to reliably reproduce so not seeing them in recent testing doesn't mean they definitely cannot happen.

The main reason these deadlocks can happen in the first place is that reads belonging to repairs don't use timeouts. This means that if there happens to be a deadlock, neither of the participating repairs will give up and the only way to release the deadlock is restarting the node.

**Comment by slivne** [comment]
@asias did we add timeouts ?

**Comment by asias** [comment]
No. Avi is against adding the timeout because it can cause false alarm, e.g., the read is slow and exceed what ever timeout we choose. Adding timeout is a workaround, the proper fix should be fixing the reader. Recently hang suggests the hang is not from reader. Adding timeout is less urgent now.

**Comment by glommer** [comment]
If on the one hand Botond is right, on the other hand we did see in the past many issues in which timeouts would trigger in recoverable situations.

I am in favor, however, of adding manual controls to stop a running repair in this case. Then we hav a human timeout.

**Comment by glommer** [comment]
@asias we have mechanisms to kill a repair now, right?
If we already do and they are satisfactory I will close this issue.

**Comment by denesb** [comment]
There is opposition against this, the preferred alternative being to improve the current repair interruption mechanism (by extending it to also kill the ongoing read maybe).
