### ISSUE TITLE
Error message not clear enough: "Exiting on unhandled exception of type 'std::system_error': Error system:98 (Address already in use)"

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#537]
When running first Cassandra and then Scylla on the same server, I got the following from Scylla:

```
scylla --smp 1 --native-transport-port 9052
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 0 on socket 0
EAL: Detected lcore 2 as core 1 on socket 0
EAL: Detected lcore 3 as core 1 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 4 lcore(s)
EAL: VFIO modules not all loaded, skip VFIO support...
EAL: Setting up physically contiguous memory...
EAL: Cannot open /proc/self/pagemap: Operation not permitted. virt2phys address translation will not work
EAL: TSC frequency is ~2294687 KHz
EAL: Master lcore 0 is ready (tid=40c05440;cpuset=[0])
Scylla version 0.11.1-20151104.eaabbba starting ...
WARN  [shard 0] config - Option partitioner is not (yet) used.
Start Storage service ...
Exiting on unhandled exception of type 'std::system_error': Error system:98 (Address already in use)
```

Using a different transport port, I expected both DB to run. 
Obviously, they overlap on other port, which the error message does not help finding.

**Comment by dorlaor** [comment]
@tzach example for a UX issue we discussed although it is not that bad msg. Pls decide whether you close it or promote it

**Comment by glommer** [comment]
I am promoting it. The message is still there as is and it doesn't list which port failed to bind.

**Comment by kokizzu** [comment]
this is obviously an serious issue..
have to grep all port on scylla.yaml and check with netstat to found that it's port 10000 (in my case) that causes this

**Comment by glommer** [comment]
This is fixed in the seastar framework (scylladb/seastar@4a56166bc19eabe08c28e6128682416f3bb6e855) and should be part of Scylla 3.1. Closing

(Agree this is really annoying)
