### ISSUE TITLE
CDC dtests: Test cluster rolling upgrade from version without CDC to version with CDC

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#5388]
1. Setup a cluster with Scylla version that does not have CDC implemented
2. Perform rolling upgrade to Scylla version with CDC implemented
3. Check that it is possible to create a table with CDC enabled
4. Do some writes to that table and verify that CDC Desc and CDC Log have the corresponding entries.

**Comment by slivne** [comment]
CDC is still experimental in 4.0

**Comment by slivne** [comment]
Done - closing
