### ISSUE TITLE
redis/commands/ has tiny source files which slows down compilation

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5394]
Although in other projects tiny source files are encouraged, in Scylla those have huge compile-time overheads because of the complexity of our header files and templates.

For example, the recently added introduced `redis/commands/echo.cc` has barely 6 lines of code, but takes 24 seconds (!) to compile.

I think we should combine all the source files redis/commands/*.cc into just one file, redis/commands.cc. This combined file will still be small, by the way.

@amoskong @fastio

**Comment by fastio** [comment]
I'm working around it.

**Comment by avikivity** [comment]
Not a user facing bug, so not backporting.
