### ISSUE TITLE
Add node: crash with unhandled exception update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_add_new_node_while_adding_info_2

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#540]
head

commit 368ee17d53e972df3b1d2c1918a7c4a629dcc312
Author: Takuya ASADA <syuu@scylladb.com>
Date:   Fri Nov 6 19:15:26 2015 +0000

    dist: prevent error building ubuntu package on EC2
    
    fixes #491
    
    Signed-off-by: Takuya ASADA <syuu@scylladb.com>

shlomi@localhost~/urchin-dtest (add_simple_kill_new_node_while_bootstrapping)$ rm -Rf ~/.dtest/*; pkill -9 scylla; KEEP_TEST_DIR=true PRINT_DEBUG=true DEBUG=true nosetests -v -s update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_add_new_node_while_adding_info_2

in ndoe4 logs I get after a few minutes

INFO  [shard 0] storage_service - JOINING: Starting to bootstrap...
Exiting on unhandled exception of type 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::io::too_many_args> >': boost::too_many_args: format-string referred to less arguments than were passed

killing the run manually.

  * cluster of 3 ndoes
  * RF=2
  * some data is inserted with CL=2
  * new node is added
  * while node is added additional info is written 
  * bootstrapping node crashes

**Comment by asias** [comment]
@slivne I run 3 times with the branch I gave you. The tests finishes in about one minute. It passed all the 3 tests.
----------------------------------------------------------------------
Ran 1 test in 71.673s
OK

**Comment by slivne** [comment]
Ok I'll test this as well on the branch with patches you sent me.

**Comment by slivne** [comment]
Ok on your branch this passes ... send the patches and mention that it
clsoes this issue as well
