### ISSUE TITLE
LIKE operator: incorrect filtering with where statement by pk and ck.

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#5400]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Version data for date: 2019-12-02 00:13
git@github.com:scylladb/scylla.git SHA: 9889e553e698aec2c385620d70362d89e4a92284
git@github.com:scylladb/scylla-jmx.git SHA: bc2b9aa67ddde1a43f505127dc948bb2d07c83db
git@github.com:scylladb/scylla-tools-java.git SHA: 7dc16419b82d5d91fd78d75d1ccb19aabda38114
Jenkins build: scylla-3.2/build [12]
Address on S3: downloads.scylladb.com/relocatable/unstable/branch-3.2/201912012052
build/SCYLLA-PRODUCT-FILE:
scylla
/build/SCYLLA-RELEASE-FILE:
0.20191202.9889e553e69
build/SCYLLA-VERSION-FILE:
3.2.rc1
Cluster size: 1 node
OS (RHEL/CentOS/Ubuntu/AWS AMI): Dtest, ubuntu 18.04, relocatable packages

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): ubuntu 18.04, relocatable packages

Issue was found by dtest written for LIKE operator. 
next table was created:
CREATE TABLE test (
                            pk text,
                            ck text,
                            test text,
                            PRIMARY KEY (pk, ck)
Used next data set
        [
            ['teststring0', '0teststring', 'test0string'],
            ['teststring0', '1teststring', 'test1string'],
            ['teststring1', '0teststring', 'test0string'],
            ['teststring1', '1teststring', 'test1string'],
            ['teststring2', '0teststring', 'test0string'],
            ['teststring2', '1teststring', 'test1string'],
            ['teststring3', '0teststring', 'test0string'],
            ['teststring3', '1teststring', 'test1string'],
            ['teststring4', '0teststring', 'test0string'],
            ['teststring4', '1teststring', 'test1string'],
        ]

Run next SELECT request:
SELECT * FROM test WHERE pk LIKE '_e%t%g_' AND ck LIKE '0%' ALLOW FILTERING
Expecting, that should be return only rows where clustering key starts from '0'
[
 [u'teststring0', u'0teststring', u'test0string'],
 [u'teststring1', u'0teststring', u'test0string'],
 [u'teststring2', u'0teststring', u'test0string'],
 [u'teststring3', u'0teststring', u'test0string'],
 [u'teststring4', u'0teststring', u'test0string']]

But next result is returned:
[u'teststring0', u'0teststring', u'test0string'], [u'teststring0', u'1teststring', u'test1string'], [u'teststring1', u'0teststring', u'test0string'], [u'teststring1', u'1teststring', u'test1string'], [u'teststring2', u'0teststring', u'test0string'], [u'teststring2', u'1teststring', u'test1string'], [u'teststring3', u'0teststring', u'test0string'], [u'teststring3', u'1teststring', u'test1string'], [u'teststring4', u'0teststring', u'test0string'], [u'teststring4', u'1teststring', u'test1string']

Actual result looks like error, because it returns only result related for first part of where statement without 

dtest is attached
[test_issue.py.txt](https://github.com/scylladb/scylla/files/3910103/test_issue.py.txt)

**Comment by aleksbykov** [comment]
Another query which returned with wrong result is:
SELECT * FROM test WHERE pk LIKE 'teststring3' AND ck LIKE '0teststring' AND test LIKE 'test1string' ALLOW FILTERING
expected, that this query return empty result, because there is not row with
['teststring0', '0teststring', 'test1string']
But returned next
[u'teststring3', u'1teststring', u'test1string']

**Comment by tzach** [comment]
@dekimir ?

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
