### ISSUE TITLE
Add node - need to align streaming and bootstrapping info messages

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#541]
Currently our boostrapping/streaming messages do not seem aligned - need to try to align them

**Comment by asias** [comment]
@slivne do you have specific messages that you needed to be aligned with c*, e.g. making test pass?

**Comment by slivne** [comment]
@asias I am currently using this "Beginning stream session" to detect that
streaming started - need to align the start of streaming message.

**Comment by asias** [comment]
We did have this line

$ gg 'Beginning stream session'
streaming/stream_coordinator.cc:201:        sslog.info("[Stream #{} ID#{}] Beginning stream session with {}", session->plan_id(), session->session_index(), session->peer);

cat /tmp/out2 |grep 'Beginning stream session'
INFO  [shard 0] stream_session - [Stream #a7267330-8770-11e5-a769-000000000000 ID#0] Beginning stream session with 127.0.0.1
