### ISSUE TITLE
nodetool cfstats hangs forever

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#5414]
Scylla:  3.1.2
Nodetool: 35906df2a0d1b94ab0df095dffd7f8c4ecf33e3a

Start two 2 nodes in the cluster

Inject data with:
$ scylla-bench -workload sequential -mode write  -nodes 127.0.0.1 -rows-per-request 1  -partition-count 1000  -clustering-row-count 100  -clustering-row-size 1024000  -keyspace myks1024000  -table t1 -replication-factor 2

Then run nodetool. It never returns
$ nodetool cfstats

Other nodetool cmds work correctly:
```
$ nodetool status
Datacenter: dc1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens       Owns    Host ID                               Rack
UN  127.0.0.1  10.69 GB   256          ?       96aaf970-c8b8-414c-9eb4-71bd4c9be29b  rack1
UN  127.0.0.2  10.93 GB   256          ?       7a758917-1f30-4e35-9292-045ee29a0555  rack1
```

**Comment by slivne** [comment]
@amoskong so its clear:
- did you run nodetool cfstats after scylla_bench has ended
or
- did you run nodetool cfstats while scylla_bench was running and loading data into the cluster

**Comment by asias** [comment]
It was after bench was done to generate the load. When I run nodetool cfstats, zero load in the cluster.

**Comment by slivne** [comment]
@amnonh can you please start the debugging and indicate where its stuck on scylla end

**Comment by amnonh** [comment]
It didn't reproduce for me, it does take a long time, on my laptop it took 25s

**Comment by slivne** [comment]
cosing the issue if it reproduces - please open a new bug with exact time it took and how much time you waited (and if there were stalls in scylla)

**Comment by let4be** [comment]
Same issue here, after I did `nodetool clearsnapshots` and also dropped some no more used keyspaces via cqlsh - `nodetool cfstats ...` hangs forever

```
scylla --version
3.2.1-0.20200122.e3e301906d5
```

**Comment by slivne** [comment]
@let4be - agreed, 

yet to understand if its long time or hangged can you please share the info on how long you waited for nodetool cfstats to return.

**Comment by let4be** [comment]
I waited over 20 min with zero success - process `nodetool` was in `ps` output, I tried killing it multiple times and starting again - nothing helped.

When all this failed I decided to completely take pressure off scylla and stopped all data producers, scylla cpu usage fell basically to zero but I still could not get a response from `nodetool cfstats` in a sane time(within several minutes).
Restarting scylla solved the issue for me, but I think it will come back eventually... I'd really like to avoid restarting production database(this was on a testing instance, so restarting was easy)

(running single node scylla)

**Comment by slivne** [comment]
@amnonh ping

**Comment by amnonh** [comment]
I'm still unable to reproduce. @let4be is is something you can reproduce easily?

If so, can you run scylla-jmx sith logging enabled:

`./scripts/scylla-jmx -Djava.util.logging.config.file=log.properties`

`$ cat log.properties `
```

handlers=java.util.logging.FileHandler, java.util.logging.ConsoleHandler
.level=DEBUG
java.util.logging.ConsoleHandler.level=FINEST
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
confLogger.level=FINEST

java.util.logging.FileHandler.pattern=/home/amnon/scylla-jmx/log.log
java.util.logging.FileHandler.limit = 50000
java.util.logging.FileHandler.count = 1
java.util.logging.FileHandler.formatter = java.util.logging.SimpleFormatter

javax.*=FINEST
org.apache.cassandra.service.StorageService.level=FINEST
org.apache.cassandra.service.StorageProxy.level=FINEST
org.apache.cassandra.service.MessagingService.level=FINEST
org.apache.cassandra.db.commitlog.CommitLog.level=FINEST
org.apache.cassandra.gms.Gossiper.level=FINEST
org.apache.cassandra.locator.EndpointSnitchInfo.level=FINEST
org.apache.cassandra.gms.FailureDetector.level=FINEST
org.apache.cassandra.db.ColumnFamilyStore.level=FINEST
org.apache.cassandra.service.CacheService.level=FINEST
org.apache.cassandra.db.compaction.CompactionManager.level=FINEST

```

**Comment by slivne** [comment]
no response from users - if this happens - please provide requested information https://github.com/scylladb/scylla/issues/5414#issuecomment-619836029

**Comment by yarongilor** [comment]
reproduced in 4.4 2TB longevity. will add details soon.

**Comment by yarongilor** [comment]
according to @roydahan this issue can be re-closed since there's a newer open issue for that, (not sure which one).
