### ISSUE TITLE
Materialized views use scan readers for single-partition scans during read-before-write which causes read amplification

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#5418]
When materialized view updates are pushed (`do_push_view_replica_updates`), they create readers with a default value of `mutation reader forwarding` parameter == `yes`. It hurts performance, because it will create scanning readers which use readahead instead of simpler single-partition readers. The problem can be observed with a simple write-intensive test with an index (or a materialized view) present:
```cql
  CREATE INDEX index1  ON myks2.standard1 ("C1");
```
```bash
cassandra-stress write no-warmup n=1000000 cl=ONE -schema \
  'replication(factor=2) compaction(strategy=LeveledCompactionStrategy)' \
  keyspace=myks2 -pop seq=4000000..8000000 -rate threads=100 -errors
  skip-read-validation -node 127.0.0.1;
```

This test generates hundreds of megabytes of data, but it causes around 36GB to be read from disk - confirmed via metrics and `iotop`. After changing the readers to not use fast-forwarding, read I/O drops to a couple of hundred megabytes, which matches the amount of data in the tables.

Branches: 3.0, 3.1, 3.2

**Comment by slivne** [comment]
@psarna are all versions suspect to this

**Comment by psarna** [comment]
I didn't check all versions, but the code is here since the original implementation of mvs, so it's very likely.

**Comment by nyh** [comment]
@psarna I agree that all extant versions are susceptible to this issue. The "fast forward" thing isn't as old as the original MV implementation, but is old enough.

**Comment by avikivity** [comment]
Backported to 3.0, 3.1, 3.2
