### ISSUE TITLE
`ascii` type column isn't validated on INSERT

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#5421]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 666.development-0.20191121.9a686ac551
Cluster size: 1

## Summery

While working on port a specific test from cassandra-dtest I've encounter this behavior between scylla and cassandra.
seems like scylla isn't validating ascii type column on INSERTs 

### Scylla
``` bash

cqlsh:ks> DROP TABLE invalid_string_literals ;
cqlsh:ks> CREATE TABLE  invalid_string_literals (k int primary key, a ascii, b text) ;
cqlsh:ks> INSERT INTO invalid_string_literals (k, a) VALUES (0, 'ಋ') ;
cqlsh:ks> SELECT * FROM invalid_string_literals ;
 k | a              | b
---+----------------+------
 0 | '\xe0\xb2\x8b' | null
(1 rows)
Failed to format value '\xe0\xb2\x8b' : 'ascii' codec can't decode byte 0xe0 in position 0: ordinal not in range(128)
```

### cassandra 3.11.0
``` bash
cqlsh> 
cqlsh> CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor':1 } ;                                        
cqlsh> USE ks;
cqlsh:ks> CREATE TABLE  invalid_string_literals (k int primary key, a ascii, b text) ;
cqlsh:ks> INSERT INTO invalid_string_literals (k, a) VALUES (0, 'ಋ') ;                                                                     
InvalidRequest: Error from server: code=2200 [Invalid query] message="Invalid ASCII character in string literal: java.nio.charset.UnmappableCharacterException: Input length = 1"
cqlsh:ks> exit
```

**Comment by avikivity** [comment]
I think this is already fixed, but better to check.

**Comment by fruch** [comment]
> I think this is already fixed, but better to check.

test on `scylladb/scylla-nightly:666.development-0.20201004.5b5b8b3264` 
Still there is no validation of ascii on insert
```
cqlsh> CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor':1 } ; 
cqlsh> CREATE TABLE  ks.invalid_string_literals (k int primary key, a ascii, b text) ;
cqlsh> INSERT INTO ks.invalid_string_literals (k, a) VALUES (0, 'ಋ') ;
cqlsh> SELECT * FROM ks.invalid_string_literals ;

 k | a              | b
---+----------------+------
 0 | '\xe0\xb2\x8b' | null

(1 rows)
Failed to format value '\xe0\xb2\x8b' : 'ascii' codec can't decode byte 0xe0 in position 0: ordinal not in range(128)
```

**Comment by avikivity** [comment]
That is really strange, because I see the code for it.

Perhaps the code isn't called on some paths.

**Comment by avikivity** [comment]
@StarostaGit looks like we have same problem with string types.

**Comment by fruch** [comment]
@avikivity this one doesn't cover it ?
https://github.com/scylladb/scylla/commit/ffd8c8c505b92a71df7e34d5196c7545f11cb12f

I was just looking at that commit today, giving someone to write a test to cover it for 4.3.
or those are different code paths ?

**Comment by avikivity** [comment]
> @avikivity this one doesn't cover it ?
> [ffd8c8c](https://github.com/scylladb/scylla/commit/ffd8c8c505b92a71df7e34d5196c7545f11cb12f)


No

> 
> I was just looking at that commit today, giving someone to write a test to cover it for 4.3.
> or those are different code paths ?

Yes

**Comment by fruch** [comment]
> > @avikivity this one doesn't cover it ?
> > [ffd8c8c](https://github.com/scylladb/scylla/commit/ffd8c8c505b92a71df7e34d5196c7545f11cb12f)
> 
> No
> 
> > I was just looking at that commit today, giving someone to write a test to cover it for 4.3.
> > or those are different code paths ?
> 
> Yes

So if I understood correctly https://github.com/scylladb/scylla/commit/ffd8c8c505b92a71df7e34d5196c7545f11cb12f is just improvement for the machinery to validate utf8, and not yet wired to all the right places ? like the simple INSERT command in this example ?

**Comment by avikivity** [comment]
ffd8c8c505b92a71df7e34d5196c7545f11cb12f adds the position of the invalid character to invalidation failure exceptions.

**Comment by StarostaGit** [comment]
I made a draft of the solution in #7625
Will attach a proper test to it tomorrow.

**Comment by nyh** [comment]
> I made a draft of the solution in #7625
> Will attach a proper test to it tomorrow.

@avikivity @StarostaGit  this issue was a about ascii type, and is already closed. Can you please open a new issue for the utf8 problem? It will make it easier to remember to backport the new patch.

**Comment by avikivity** [comment]
Backported to 4.2, 4.3.
