### ISSUE TITLE
print the binary build-id on startup

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5426]
So it would be easier to correlate the log with the binary and possible core dump.

Ref https://github.com/scylladb/scylla-pkg/issues/715

**Comment by espindola** [comment]
A trivial program that prints its own build-id is attached. I will turn that into a patch tomorrow.

[test.cc.txt](https://github.com/scylladb/scylla/files/3947964/test.cc.txt)

**Comment by vladzcloudius** [comment]
@bhalevy @espindola The patch above introduces a regression. 
I'm going to open a separate issue for this with more details.
