### ISSUE TITLE
AMI build can fail due to too long description.

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla#5435]
When trying to pack an AMI, it can fail if the description is too long. The description is composed out
of all the version strings of the components (scylla,jmx,java-tools etc...).
AWS allows for a maximum of 250 characters for description so it might be that the packer will fail
when trying to set the description string.
The "problematic" line is here:
https://github.com/scylladb/scylla/blob/0e319e03599d8f89235d217faef30c6ec2dbba01/dist/ami/scylla.json#L60

My suggested solution it to add another variable that will be trimmed to 255 character. All of the information is available anyway in individual per component tags:
https://github.com/scylladb/scylla/blob/0e319e03599d8f89235d217faef30c6ec2dbba01/dist/ami/scylla.json#L62-L66

/cc @penberg @syuu1228

**Comment by avikivity** [comment]
@eliransin is only master vulnerable, or any branches too?

**Comment by eliransin** [comment]
@avikivity 3.1 and above (inclusive) are vulnerable.
