### ISSUE TITLE
mutation_fragment_stream_validator: add clustering monotonicity validation

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#5445]
Expanding on https://github.com/scylladb/scylla/issues/4803 and https://github.com/scylladb/scylla/issues/4804 we need a check that validates clustering key monotonicity. Should be enabled/disabled via a command line switch.

**Comment by bhalevy** [comment]
496467d0a2b35aa2fb9ba5ae7062d501001733e8 validates position_in_partition monotonicity under the enable_sstable_key_validation option, including clustering_key_prefix.

**Comment by denesb** [comment]
Right, I don't know how I didn't see that.
