### ISSUE TITLE
list_test failed for wrong order (expect the result order to be same as write order)

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5446]
*Installation details*
Scylla version (or git commit hash): 3.1.2-0.20191127.9d78d848e
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

#### Description:
Verify test before upgrade from 3.1.2 to master failed, so upgrade hasn't started.

We didn't see this problem in 3.0.10, and we didn't see this problem after upgraded from 3.0 to 3.1.0

#### Living cluster:

There is no living cluster there, it's easy to reproduce by centos upgrade job. If someone needs a living cluster for debug, I can rerun the job to reproduce this issue.

#### SCT configuration YAML:
https://github.com/scylladb/scylla-cluster-tests/blob/master/test-cases/upgrades/rolling-upgrade.yaml

#### Test job info:
- job link: https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7/17/
- logs: https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7/17/artifact/scylla-cluster-tests/latest/

#### The relevant log messages with timestamps of the issue

- FAIL 1: https://jenkins.scylladb.com/job/scylla-master/job/rolling-upgrade/job/rolling-upgrade-centos7/17/artifact/scylla-cluster-tests/
```
15:12:22  FAIL: test_rolling_upgrade (upgrade_test.UpgradeTest)
15:12:22  ----------------------------------------------------------------------
15:12:22  Traceback (most recent call last):
15:12:22    File "/sct/upgrade_test.py", line 434, in test_rolling_upgrade
15:12:22      self.fill_and_verify_db_data('BEFORE UPGRADE', pre_fill=True)
15:12:22    File "/sct/upgrade_test.py", line 405, in fill_and_verify_db_data
15:12:22      self.verify_db_data()
15:12:22    File "/sct/sdcm/fill_db_data.py", line 2981, in verify_db_data
15:12:22      self.run_db_queries(session, session.default_fetch_size)
15:12:22    File "/sct/sdcm/fill_db_data.py", line 2943, in run_db_queries
15:12:22      raise ex
15:12:22    File "/sct/sdcm/fill_db_data.py", line 2940, in run_db_queries
15:12:22      self.assertEqual([list(row) for row in res], item['results'][i])
15:12:22  AssertionError: Lists differ: [[['foo', 'bar', 'foobar', 'foo']]] != [[['foo', 'bar', 'foo', 'foobar']]]
```
- FAIL 2: https://jenkins.scylladb.com/job/scylla-3.2/job/rolling-upgrade/job/rolling-upgrade-centos7/28

```
14:16:11  AssertionError: Lists differ: [[[u'bar', u'foo', u'foobar', ... != [[[u'foo', u'bar', u'foo', u'f...
14:16:11  
14:16:11  First differing element 0:
14:16:11  [[u'bar', u'foo', u'foobar', u'foo']]
14:16:11  [[u'foo', u'bar', u'foo', u'foobar']]
14:16:11  
14:16:11  - [[[u'bar', u'foo', u'foobar', u'foo']]]
14:16:11  ?                             --------
14:16:11  
14:16:11  + [[[u'foo', u'bar', u'foo', u'foobar']]]
14:16:11  ?    ++++++++
```
#### Test senario:

```
CREATE KEYSPACE IF NOT EXISTS keyspace_fill_db_data
WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'} AND durable_writes = true;

CREATE TABLE list_test (
                            fn text,
                            ln text,
                            tags list<text>,
                            PRIMARY KEY (fn, ln)
                        );

UPDATE list_test SET tags = tags + [ 'foo' ] WHERE fn='Tom' AND ln='Bombadil';
UPDATE list_test SET tags = tags + [ 'bar' ] WHERE fn='Tom' AND ln='Bombadil';
UPDATE list_test SET tags = tags + [ 'foo' ] WHERE fn='Tom' AND ln='Bombadil';
UPDATE list_test SET tags = tags + [ 'foobar' ] WHERE fn='Tom' AND ln='Bombadil';

select tags from list_test;
```

----
#### Name & IP of the node with the issue:
rolling-upgrade-upgrade--centos-db-node-58beb5b8-0-1 [35.237.136.53 | 10.142.0.6] 
rolling-upgrade-upgrade--centos-db-node-58beb5b8-0-2 [35.231.228.89 | 10.142.0.7] 
rolling-upgrade-upgrade--centos-db-node-58beb5b8-0-3 [35.229.60.15 | 10.142.0.11] 
rolling-upgrade-upgrade--centos-db-node-58beb5b8-0-4 [35.196.185.227 | 10.142.0.14] 
rolling-upgrade-upgrade--centos-loader-node-58beb5b8-0-1 [35.196.7.32 | 10.142.0.17] 
rolling-upgrade-upgrade--centos-monitor-node-58beb5b8-0-1 [35.227.72.155 | 10.142.0.26]

#### Instance type + number of instances + number of DCs
gce_instance_type_db: n1-highmem-8
number of instances: 4
dc number: 1

#### upgrade test

https://github.com/scylladb/scylla-cluster-tests/blob/master/upgrade_test.py#L362

![image](https://user-images.githubusercontent.com/309708/70483889-f74cce80-1b24-11ea-97bb-a731a06fd809.png)

/CC @roydahan @slivne

**Comment by amoskong** [comment]
I didn't reproduce this issue manually with a single node. But it can be reproduced by upgrade job of `centos7` (not always, but not difficult).

**Comment by amoskong** [comment]
Try to reproduce by job : [scylla-3.2/job/rolling-upgrade/job/rolling-upgrade-centos7/29/](https://jenkins.scylladb.com/job/scylla-3.2/job/rolling-upgrade/job/rolling-upgrade-centos7/29/)
- job is running ...
- db nodes will be kept for debugging

**Comment by amoskong** [comment]
> Try to reproduce by job : [scylla-3.2/job/rolling-upgrade/job/rolling-upgrade-centos7/29/](https://jenkins.scylladb.com/job/scylla-3.2/job/rolling-upgrade/job/rolling-upgrade-centos7/29/)
> 
> * job is running ...
> * db nodes will be kept for debugging

The test failed for SCT issue: https://github.com/scylladb/scylla-cluster-tests/issues/1537

Will retest when the sct issue is solved.

**Comment by slivne** [comment]
@amoskong If this is an SCT bug - please close

**Comment by amoskong** [comment]
> @amoskong If this is an SCT bug - please close

The job (https://jenkins.scylladb.com/job/scylla-3.2/job/rolling-upgrade/job/rolling-upgrade-centos7/29/) failed for SCT issue, but the list order problem is a real problem of Scylla, It can be reproduced.

**Comment by slivne** [comment]
copy pasting from another thread

AmosKong wrote

> I found a problem in test script, I'm running another job with detail debug msg.
Wish the delay is really added this time. Will update you result later.

> This` issue won't occur after correctly added the delay for each insert.


closing the issue
