### ISSUE TITLE
CREATE TABLE compaction non compatible with Cassandra

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#545]
Cassandra
```
CREATE TABLE (
...
) WITH compaction = {'class': 
'org.apache.cassandra.db.compaction.LeveledCompactionStrategy'}
```

Scylla
```
CREATE TABLE (
...
) WITH compaction = {'class': 'LeveledCompactionStrategy'}
```

Although it make sense to allow the shorter version, the full Java class name (org.apache...) is in used in schema, and it would be easir to allow it as well.

**Comment by slivne** [comment]
this is fixed on head amnon sent a patch for this earlier this week
