### ISSUE TITLE
Comparison operator for alternator's rjson is inconsistent

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#5454]
As a by-product of reviewing https://github.com/scylladb/scylla/pull/5453, several issues with the implementation of rjson's equality operator were discovered:
* it doesn't check if compared types are the same in cases where it should
* for strings, after checking that the first object is a string, it assumes the second object is a string as well, which might not be the case
* it mentions "set" in one of the error messages, while this operator is generic, not crafted for sets or any other data structures specifically
* there are inconsistencies, e.g. comparing True against an object will return true, while comparing an object against True throws an internal error
etc.

**Comment by nyh** [comment]
adding "low" label, as this only effects esoteric cases where the user is trying to do things that should be errors anyway.
