### ISSUE TITLE
Update 3rd party dependencies on debian regarding java

### ISSUE THREAD

**Issue by hankipanky** [scylladb/scylla#5463]
We are unable to install scylla 3.1.1 on Debian 10, since the tools depend on OpenJDK 8 (see also #4665). 
The Debian maintainers will not support [OpenJDK 8 on Debian 10](https://lists.debian.org/debian-java/2019/04/msg00036.html).

Installation output:

```
The following packages have unmet dependencies:
 scylla-jmx : Depends: openjdk-8-jre-headless but it is not installable or
                       openjdk-8-jre but it is not installable or
                       oracle-java8-set-default but it is not installable
 scylla-tools-core : Depends: openjdk-8-jre-headless but it is not installable or
                              openjdk-8-jre but it is not installable or
                              oracle-java8-set-default but it is not installable
E: Unable to correct problems, you have held broken packages.

```
In absence of OpenJDK 8 we tried using Oracle Java 8, built for Debian 10 via https://github.com/rraptorr. Those packages provide the virtual packages `java-virtual-machine`, `java8-runtime-headless`, etc; however this is not acceptable to Scylla.

Kindly update the 3rd party depencies  and replace `oracle-java8-set-default` with `java8-runtime-headless`.

**Comment by AdamNuclear** [comment]
Same issue with ubuntu 18.04LTS. Default is openjdk-11-jre-headless and scylla want openjdk-8-jre-headless. After uninstalling openjdk-11-jre-headless it works.

**Comment by hankipanky** [comment]
> After uninstalling openjdk-11-jre-headless it works.
Thanks, but I don't think this is the same issue. Scylla-tools don't support Java 11 yet; they depend on Java 8. The point is that the alternatives to OpenJDK 8 should be more generic, for those platforms where it is not available.

**Comment by tarzanek** [comment]
is https://adoptopenjdk.net/releases.html publishing debian packages?

**Comment by avikivity** [comment]
@syuu1228 can was add a conflict with java 11 to solve the ubuntu issue?

**Comment by slivne** [comment]
@syuu1228 / @avikivity can we close this ?

**Comment by syuu1228** [comment]
@slivne Yes.
