### ISSUE TITLE
Make scylla backtraces always print in oneline

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#5464]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

## Summary
Right now, `seastar/src/util/backtrace.cc` functions are printing backtraces in one line while
`backtrace_buffer` from `./seastar/src/core/reactor.cc` print the backtraces in multiple lines.

While testing or automating tool reading the logs, it would be a great help if all the exceptions printed would be same as in `seastar/src/util/backtrace.cc` and printed in one line.

right now we are having trouble when backtraces from multiple shard are interleaved, and it make finding those backtraces for decoded a bit more error prone from our side.

**Comment by roydahan** [comment]
@avikivity would you consider this?
It will help our automation better detect full backtraces.

**Comment by denesb** [comment]
Which Scylla version is this? Since https://github.com/scylladb/seastar/commit/1ee2be13ae0c3deb1de04a810b1008851f7fca3e all backtraces are printed the same way -- in multiple lines. IIRC Scylla 3.0+ has this code.

**Comment by fruch** [comment]
Well I know we see this difference also in 3.2 and even before that.

Anyhow we want to change it to be one liner, or at least a way to configure it like that.

Since the multiple line backtraces make it very hard to collect and attribute the correct backtrace to the error taking place

**Comment by denesb** [comment]
Can you copy here a snippet of such a one-liner? I cannot see in the code where we would produce such a backtrace. Both `backtrace_buffer` in `reactor.cc` and `operator<<(saved_backtrace)` in `util/backtrace.cc` print multi line traces.

**Comment by fruch** [comment]
I guess we still see that in branch-3.0 
https://github.com/scylladb/scylla/issues/5291

But the our issue isn't that it's not consistent, is that we want it to be one-liner, or at least a way to configure it so.

**Comment by denesb** [comment]
I think that that one-line backtrace was multi-line originally and the newline chars were eaten somewhere in the log processing/capturing pipeline.

As part of the work of https://github.com/scylladb/seastar/commit/1ee2be13ae0c3deb1de04a810b1008851f7fca3e there was a decision to make all backtraces consistent and the multi-line format was chosen. I don't remember the exact arguments, but I seem to remember that field preferred them over one-liners.

> right now we are having trouble when backtraces from multiple shard are interleaved, and it make finding those backtraces for decoded a bit more error prone from our side.

Scylla (seastar) will never interleave log lines from multiple shards as the logging is thread-safe, so I guess the interleaving happens somewhere in the aggregation pipeline. Fixing that should be possible but having one-liner backtraces would be easier I guess. On the other hand seastar doesn't guarantee that log messages are single line, so making backtraces single-line would only defer the problem until another multi-line log message appears. @fruch how does your system aggregate logs? Would it be very difficult to make it recognize log lines?

**Comment by fruch** [comment]
Is a simple reading it line by line from a file, right now. nothing
sophisticated.
logs are transferred to the machine we are running the tests with
rsyslod via network.

but the main issue with reading from multiple lines, is not know where is
the end of that backtrace.
So, we'll need to understand which shard this log line belongs to.
and once we get the EOF we need to keep that information/part of backtrace
to the next read we are doing of the file.

Having it in one print, and having a clear marker for the end of the
backtrace would remove a bit portion of the logic we need to implement to
get it right.

**Comment by denesb** [comment]
Changing this is not as simple as it sounds. Unconditionally making all backtraces single-line would be a two line patch, but:
* This is in seastar code. Changing it would change how *all* seastar applications log their backtraces. We can't just make a change like that on a whim.
* Even if this was scylla-only code, there is now a bunch of tools all built around multi-line backtraces. Changing it would possibly brake everybody's tools.

Making this configurable would result in a complicated patch, that would have to propagate a configuration option down to code that until now was simple and didn't depend on anything from the outside.

**Comment by gleb-cloudius** [comment]
On Mon, Dec 16, 2019 at 12:38:03AM -0800, Botond Dénes wrote:
> I think that that one-line backtrace was multi-line originally and the newline chars were eaten somewhere in the log processing/capturing pipeline.
> 
> As part of the work of https://github.com/scylladb/seastar/commit/1ee2be13ae0c3deb1de04a810b1008851f7fca3e there was a decision to make all backtraces consistent and the multi-line format was chosen. I don't remember the exact arguments, but I seem to remember that field preferred them over one-liners.
> 
I was always for the one-line backtrace for all the good reasons Israel
brings here. The only argument in favor of multi-linear was that some
loggers may by default truncate lines that are too long so there was a
concern that user bug reports will be incomplete. The argument is not
convincing to me at all since it is very easy to ask for non truncated
log.

> > right now we are having trouble when backtraces from multiple shard are interleaved, and it make finding those backtraces for decoded a bit more error prone from our side.
> 
> Scylla (seastar) will never interleave log lines from multiple shards as the logging is thread-safe, so I guess the interleaving happens somewhere in the aggregation pipeline. Fixing that should be possible but having one-liner backtraces would be easier I guess. On the other hand seastar doesn't guarantee that log messages are single line, so making backtraces single-line would only defer the problem until another multi-line log message appears. @fruch how does your system aggregate logs? Would it be very difficult to make it recognize log lines?
> 
Seastar will not interleave log lines but the message sync (AKA logging
subsystem) gets logs from all shards simultaneously and is not shard
aware.

--
			Gleb.

**Comment by avikivity** [comment]
I was also in favor of a single-line backtrace.

I also had plans to base64-encode the addresses (and drop leading zeros), but it's too much effort for too little gain.

**Comment by roydahan** [comment]
So how do we get a QUORUM on this decision or we should choose a leader to decide (@avikivity )?
For better QA auto detection and prevent incomplete backtraces, I think one liner is no brainer.

**Comment by avikivity** [comment]
It's not enough to decide, someone needs to write the code.

For a trace with 10 non-inline calls, assuming 6 hex digits compressed to 4 base64 digits + 1 marker, we get 50 characters. We'll also need to record libraries, I think we reach around 80 characters for a compressed backtrace.

**Comment by roydahan** [comment]
@avikivity, After verifying with support and field, it's safe to assume that users send their logs in a way that long backraces won't get truncated.
We have it in some places even now (seastar as mentioned above).

Would it be ok to start with one-line backtrace and later optimize its length?

**Comment by slivne** [comment]
@avikivity do we have your ok to change the backtarce to a single line (without the additional "compression") - if so I'll assign it to someone

**Comment by roydahan** [comment]
@avikivity / @bhalevy / @raphaelsc , in order to be able to analyze stalls detection automatically, we must have this at least for stall detector backtraces.

**Comment by bhalevy** [comment]
> @avikivity / @bhalevy / @raphaelsc , in order to be able to analyze stalls detection automatically, we must have this at least for stall detector backtraces.

@roydahan bare in mind that even if we make this change in master it won't reach the present release branches.
I think it's a reasonable change to make, but why is it a *must* for decoding?

**Comment by roydahan** [comment]
master is fine, we test on master.
It's a must because when getting 1000 stalls and we would like to know how many of them unique and report only the unique ones, we can't do it with the current implementation.

**Comment by fgelcer** [comment]
@bhalevy , as the code that decodes the backtraces are not run in the DB nodes, the log could contain external lines (from other backtraces, in different nodes for example) and could result in a broken decoded backtrace.

we already have few backtraces in one line, and for them, we have a mechanism in SCT that decodes them, when identified in the logs.
