### ISSUE TITLE
build_rpm.sh: add option to strip the scylla binary

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5467]
See https://github.com/scylladb/scylla-pkg/issues/788 for context.

This gist of it is to always build scylla with `--debuginfo 1` (and `--test-debuginfo 0` by default) and then strip the debug info only when building the centos rpm, that is used consequently to build the ami.

**Comment by espindola** [comment]
The rpm build process already spits the debug info to its on package. We get scylla-server with the binary and scylla-debuginfo with the debug info.

Why do we wan to strip the scylla binary?

**Comment by bhalevy** [comment]
@penberg if this is indeed not required we can close this issue.

**Comment by nyh** [comment]
@bhalevy should we close this issue? I think we always want to have one RPM with the stripped executable, and a second RPM with the debug information, and we never really want what you suggested in this issue, which was to completely strip the executable and not leave the debugging information anywhere.

**Comment by avikivity** [comment]
@bhalevy already consented to closing, so closing.
