### ISSUE TITLE
storage_proxy: should not throw exceptions when nodes are not alive

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#547]
exceptions during normal operation are the enemy of seastar: the take a futex and lead us to block the reactor.

Turns out we are using exceptions to notify that a node is dead and take us out of the normal control flow.

We use that in assure_sufficient_live_nodes().

If we can't assure that there are sufficient nodes, we will be throwing exceptions all the time.

**Comment by tzach** [comment]
@glommer 
What is the affect of this issue? 
Does it significantly slow down Scylla when one of the node is down?

**Comment by gleb-cloudius** [comment]
On Tue, Feb 16, 2016 at 05:05:36AM -0800, Tzach Livyatan wrote:
> @glommer 
> What is the affect of this issue? 
> Does it significantly slow down Scylla when one of the node is down?
> 
Regardless, it cannot be fixed without changing interface between
storage_proxy and its callers that expect exceptional future to be
returned in case of an error, to create one exception has to be thrown.

--
			Gleb.

**Comment by glommer** [comment]
@tzach if the node is down, I don't know (but likely yes). My motivation to look at the question was basically from the point of view of an overloaded node that can't handle some particular requests.

The problem in that case is that we would have very high blocking wait times, and that can lead to more requests that were on the verge of timing out, actually timing out.

I remember that @gleb-cloudius  eventually wrote a patch that could potentially mitigate this by avoiding re-throws at the seastar then_wrapped() level, but we never got to test it.

Gleb: it would be nice if we could explore that further, at least, before we go look into reworking storage proxy's paths.

**Comment by glommer** [comment]
This situation has been much improved since we fixed the glibc.
We also made rethrowing through futures itself more efficient.
It is not clear to me if the insane amount of work required not to use exception paths justified, probably isn't.

Closing
