### ISSUE TITLE
Improve the ability to estimate the amount of tombstones in a particular data element

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#5471]
*Installation details*
HEAD: 7b37a700e11ae298940a2015815e51e1434ede6f

*Description*
As of today there is no way to know how many tombstones needs to be scanned in order to read a particular data element (e.g. a partition).

This is a very important feature that is required when debugging read latency issues.

**Comment by vladzcloudius** [comment]
One way to resolve this is to instrument CQL Tracing.

There is an initial work that has been done in this regard: "[PATCH scylla v1 0/9] CQL tracing: trace the amount of read data".

Someone (me?) should get it to completion unless there is a better way to address this.

**Comment by slivne** [comment]
We already have some information in CQL Trace with regards to reading data off sstables - can this help ?

**Comment by vladzcloudius** [comment]
@slivne Could you clarify which info you refer? 
AFAIK the only info we have is that sstable with a particular name has been read. 
If that's the only info we get this is clearly not enough because it doesn't tell us how much "bad" data has been read (at all or from a particular sstable).
