### ISSUE TITLE
scylla_prepare causes KeyError when SET_CLOCKSOURCE haven't configured by scylla_setup

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#5474]
Since we don't have SET_CLOCKSOURCE on dist/common/sysconfig/scylla-server by default,
scylla_prepare causes KeyError when SET_CLOCKSOURCE haven't configured by scylla_setup.

```
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: Traceback (most recent call last):
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: File "/opt/scylladb/python3/lib64/python3.7/configparser.py", line 788, in get
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: value = d[option]
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: File "/opt/scylladb/python3/lib64/python3.7/collections/__init__.py", line 916, in __getitem__
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: return self.__missing__(key)            # support subclasses that define __missing__
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: File "/opt/scylladb/python3/lib64/python3.7/collections/__init__.py", line 908, in __missing__
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: raise KeyError(key)
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: KeyError: 'SET_CLOCKSOURCE'
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: During handling of the above exception, another exception occurred:
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: Traceback (most recent call last):
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: File "/opt/scylladb/scripts/libexec/scylla_prepare", line 77, in <module>
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: if create_perftune_conf(cfg):
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: File "/opt/scylladb/scripts/scylla_util.py", line 556, in create_perftune_conf
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: if cfg.get('SET_CLOCKSOURCE') == 'yes':
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: File "/opt/scylladb/scripts/scylla_util.py", line 664, in get
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: return self._cfg.get('global', key).strip('"')
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: File "/opt/scylladb/python3/lib64/python3.7/configparser.py", line 791, in get
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: raise NoOptionError(option, section)
Dec 12 22:36:46 01ee2b0964d9 scylla_prepare[7820]: configparser.NoOptionError: No option 'SET_CLOCKSOURCE' in section: 'global'
```

**Comment by syuu1228** [comment]
Probably it's better to return empty string just like on shell script, instead of raising exception.

**Comment by glommer** [comment]
Thanks @syuu1228 .

Indeed we need to work and be compatible with older files that won't have that variable - in which case we should just not set it.

@flucchese please fix.

**Comment by syuu1228** [comment]
I already sent a fix for it:
[PATCH scylla 1/2] dist/common/scripts: don't raise exception when sysconfig.get() does not find entry on sysconfig file
[PATCH scylla 2/2] dist/common/sysconfig: add SET_CLOCKSOURCE

**Comment by glommer** [comment]
It's not better to return an empty string. I have responded to your patch.

Please keep the exception, catch it in the caller, and document get() saying explicitly that optional variables will throw so that nobody else makes this mistake in the future.

**Comment by amoskong** [comment]
> Probably it's better to return empty string just like on shell script, instead of raising exception.

the expected return values have different type, empty string or none is not good unless we double check and fix or caller.

**Comment by amoskong** [comment]
I also touched a problem of scylla_setup.

related issue: https://github.com/scylladb/scylla/issues/5474

**Comment by flucchese** [comment]
I would argue that the "SET_CLOCKSOURCE" parameter should be treated like the other ones, meaning that it should be incorporated to scylla_server in its default value.

**Comment by flucchese** [comment]
@amoskong did you update the scylla_server in your patch?

**Comment by amoskong** [comment]
Yes, but the PR (https://github.com/scylladb/scylla/pull/5476/
<https://github.com/scylladb/scylla/pull/5476/files>) was closed.  Your
original commit was reverted.

**Comment by avikivity** [comment]
Aged out, no need to backport.
