### ISSUE TITLE
nonroot mode installer does not specify correct datadir

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#5475]
It seems failing specify correct datadir, scylla tries to use default path (/var/lib/scylla/data) and fails to startup.
```
[shard 0] init - Directory '/var/lib/scylla/data' cannot be initialized. Tried to do it but failed with: storage_io_error (Storage I/O error: 13: filesystem error: mkdir failed: Permission denied [/var/lib/scylla/])
```

**Comment by avikivity** [comment]
Exposed by --workdir, which isn't in any release version, so no need to backport.

**Comment by syuu1228** [comment]
On Wed, Dec 25, 2019 at 1:10 AM Avi Kivity <notifications@github.com> wrote:

> Exposed by --workdir, which isn't in any release version, so no need to
> backport.
>
In that case, maybe we should use data_file_directories,
commitlog_directory... etc instead?
Then no need backporting.
