### ISSUE TITLE
Column family has wrong ID

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#548]
In a cluster with 3 nodes, loaded with standard cassandra-stress write test, I am seeing this in one of the nodes:

```
DEBUG [shard 25] sstable - Writing TOC file
/data/data/keyspace1/standard1-9005484087af11e593f7000000000001/keyspace1-standard1-ka-56-TOC.txt.tmp
DEBUG [shard 25] database - Flushing done
ERROR [shard 25] database - failed to write sstable: std::system_error
(error system:2, No such file or directory)
```

The reason we fail this write, is that this column family does not exist:

```
[fedora@host ~]$ sudo ls /data/data/keyspace1/
standard1-9001c5d087af11e5b67a000000000000
```

So the CF is there, but it has a different UUID attached to it. That
directory is empty,  and the commitlog directory is 9G big in size.

I don't know how to reproduce but something triggers the problem. I will try more tomorrow, but we should be inspecting code paths that may lead to this

@penberg says on the matter: 

> One potential explanation I can think of is that CF was created on
> different nodes simultaneously and our schema merging validation logic
> in database::update_column_family() failed to kick in.

**Comment by slivne** [comment]
@glommer just to verify:

the scenario is the following:

1. a cluster f 3 nodes
2.  run multiple cassandra-stress toward the nodes

**Comment by slivne** [comment]
probably related to #420

**Comment by tgrabiec** [comment]
Could be related to #753

**Comment by tgrabiec** [comment]
Most likely dup of #420

**Comment by avikivity** [comment]
Closing, leaving #420.
