### ISSUE TITLE
Paging issue: when using select count(*) paging is applied 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#549]
with head

commit b95ff5c09e1402d0302eef28bfee2b1040e835be
Merge: dcc7302 43712a5
Author: Avi Kivity <avi@scylladb.com>
Date:   Wed Nov 11 11:42:47 2015 +0200

    Merge "Commitlog format change: add scylla "magic"" from Calle
    
    "Slight file format change for commitlog segments, now incluing
    a scylla "marker". Allows for fast-fail if trying to load an
    Origin segment.
    
    WARNING: This changes the file format, and there is no good way for me to
    check if a CL is "old" scylla, or Origin (since "version" is the same). So
    either "old" scylla files also fail, or we never fail (until later, and
    worse). Thus, if upgrading from older to this patch ensure to
    have cleaned out all commit logs first."

starting a node
cassandra-stress write n=1000 -mode cql3 native
connect via cqlsh
doing select count(*) from keyspace1.standard1

I get

```
cqlsh> select count(*) from ks.cf;

 count
-------
   100

---MORE---
 count
-------
   100

---MORE---

 count
-------
   100

---MORE---


 count
-------
   100

---MORE---


 count
-------
   100

---MORE---


 count
-------
   100

---MORE---

 count
-------
   100

---MORE---


 count
-------
   100

---MORE---




 count
-------
   100

---MORE---





 count
-------
   100

---MORE---




 count
-------
   100

---MORE---




 count
-------
   100

---MORE---



 count
-------
   100

---MORE---

 count
-------
   100

---MORE---

 count
-------
   100

---MORE---

 count
-------
   100

---MORE---

 count
-------
   100

---MORE---



 count
-------
   100

---MORE---



 count
-------
   100

---MORE---


 count
-------
   100

---MORE---

 count
-------
   100

---MORE---

 count
-------
   100

---MORE---

 count
-------
   100

---MORE---

 count
-------
   100

---MORE---

 count
-------
   100

---MORE---
 count
-------
   100

---MORE---

 count
-------
   100

---MORE---

 count
-------
   100

---MORE---
 count
-------
   100

---MORE---

 count
-------
   100

---MORE---

 count
-------
   100

---MORE---

 count
-------
   100

---MORE---

 count
-------
   100

---MORE---

 count
-------
   100

---MORE---

 count
-------
   100

---MORE---

 count
-------
   100

---MORE---
 count
-------
   100

---MORE---
 count
-------
   100

---MORE---

 count
-------
   100

.
.
.
```

This is incorrect.

**Comment by elcallio** [comment]
Yeah, well, obviously a "count" query should not page at all. So the "might_need_paging" is incomplete...

**Comment by elcallio** [comment]
Or, to be more precise, _paging_ is supposed to happen, but it should have been applied by the "aggregate" path in selection_statement...

**Comment by elcallio** [comment]
Which is a big, empty "TODO" in the code. So much for my following through... :-P
