### ISSUE TITLE
Verify on startup that clock epochs match our expectation

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5498]
This is a spinoff from https://github.com/scylladb/scylla/pull/5485, based on observations by @kbr- 

Comments in `db_clock.hh` say that it assumes that the epoch of this clock, based on `std::chrono::system_clock`, is in the Unix epoch of 1970. However, the existing C++ standard doesn't give this guarantee. 

In the same file we have methods `to_time_t` and `from_time_t`, and `to_gc_clock`, which also suggest they work without knowing what the clock's implementation's epoch is, but I think this suggestion is wrong - and in fact all these methods will only work as expected if both db_clock (`std::chrono::system_clock`) and gc_clock (`seastar::lowres_system_clock`) have the same epoch.

I think we should continue to make this assumption that the epoch of these clocks are the same (Jan 1, 1970), because it is true on all systems we use, and as I understand, a future C++ standard will standardize it. However, we can feel safer if we verify that this is truely the case. We could, on startup of Scylla, take now() from the clocks we use, as well as C's `time()` (which has a standardized meaning regarding the epoch and the treatment of leap seconds), and compare that all result in the same number (approximately). We can then modify that comments about the epoch assumption saying that we *know* this holds because of the function we have for testing it.

In practice, we can just use the C function` time()` and compare it to `std::chrono::duration_cast<seconds>(system_clock::now().time_since_epoch())` and verify that they are the same. To account for the possibility of the two calls spanning a second boundary, we can run the test a second time if the first one failed, or just allow the possibility of one second difference.

This assumption can also be formalized in code (instead of comments) by having a function `verify_unix_epoch(clock)` and each source file which needs the unix epoch (Jan 1, 1970) will call this function in a static constructor. But I think this is probably overkill, and one check in main.cc plus comments will be good enough.

**Comment by michoecho** [comment]
The epoch of `std::chrono::system_clock` was standardized in C++20. This issue can be closed.
