### ISSUE TITLE
super long path for the dynamic linker should apply also to iotune

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5505]
8d777b3ad5a23953fa23988ab0b92ca056d4f9ba adds a long prefix of `/`s to the dynamic linker path so that we can run patchelf on the binary later in in `install.sh` to set the interpreter to some path known at install time.

 237ba747436370eb0e8a04556846845897dd3de1 added a test in `install.sh` that verifies patchelf's result on the `scylla` and `iotune` binaries.

However, as seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/dtest-byo/35, the verification fails for iotune, as follows:
```
10:54:51  /jenkins/slave/workspace/scylla-master/byo/dtest-byo/scylla/.ccm/scylla-repository/c0aea19419daa75677fa6f8ecd59d8398637839f/scylla//opt/scylladb/libexec/iotune.before /jenkins/slave/workspace/scylla-master/byo/dtest-byo/scylla/.ccm/scylla-repository/c0aea19419daa75677fa6f8ecd59d8398637839f/scylla//opt/scylladb/libexec/iotune.after differ: byte 39, line 1
10:54:51  patchelf modified the LOAD program headers. Core files would be missing build-id
```

I suspect that setting the linker flags at `./configure.py` time does not affect iotune, but rather only scylla.

440ad6abccfa4486108ea58296996a7ec560f83d reverted 237ba747436370eb0e8a04556846845897dd3de1 that should be re-merged once this issue is resolved.

Also it would be better to just print a warning about the possibly missing build-id, if the verification in install.sh failed and go on, rather then `exit 1` and failing the installation.

**Comment by bhalevy** [comment]
On Thu, 2019-12-19 at 08:40 -0800, @espindola wrote:
> Avi Kivity <avi@scylladb.com> writes:
> 
> > On 19/12/2019 18.06, Rafael Avila de Espindola wrote:
> > > Commit Bot <bot@cloudius-systems.com> writes:
> > > 
> > > > From: Avi Kivity <avi@scylladb.com>
> > > > Committer: Avi Kivity <avi@scylladb.com>
> > > > Branch: master
> > > > 
> > > > Revert "relocatable: Check that patchelf didn't mangle the PT_LOAD headers"
> > > > 
> > > > This reverts commit 237ba747436370eb0e8a04556846845897dd3de1. While it
> > > > works for the scylla executable, it fails for iotune, which is built
> > > > by seastar. It should be reinstated after we pass the correct link
> > > > parameters to the seastar build system.
> > > > 
> > > Do you have a link to the failure? I just tried
> > > 
> > > % ./configure.py  --ldflags=-Wl,--build-id=sha1,--dynamic-linker=////lib64/ld-linux-x86-64.so.2
> > > 
> > > and I got
> > > 
> > > % readelf -lW ./build/dev/seastar/apps/iotune/iotune
> > > ...
> > > 
> > > [Requesting program interpreter: ////lib64/ld-linux-x86-64.so.2]
> > 
> > https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/dtest-byo/34/console
> 
> That log has
> 
> [2019-12-19T08:27:43.350Z] Getting artifact scylla/build/debug/scylla-package.tar.gz
> [2019-12-19T08:27:43.409Z] [Pipeline] step
> [2019-12-19T08:28:09.831Z] Copied 1 artifact from "scylla-master » next" build number 1417
> 
> And the next build does
> 
> [2019-12-19T06:36:40.481Z] + /jenkins/workspace/scylla-master/next/scylla/tools/toolchain/dbuild -v /jenkins/mirror.git:/jenkins/mirror.git -v /var/cache/ccache:/var/cache/ccache:z -e
> CCACHE_DIR=/var/cache/ccache -e CCACHE_UMASK=002 -e PATH=/usr/lib64/ccache:/usr/bin:/usr/sbin -- ./reloc/build_reloc.sh --mode debug --compiler g++ --configure-flags '--debuginfo 1 --tests-debuginfo 
> 0   --enable-dpdk ' --jobs 48
> 
> So --configure-flags is used, and DEFAULT_FLAGS is not. The issue is not
> iotune versus scylla.
> 
> I am on "vacation", so I really don't feel like going over how jenkins
> should use build_reloc right now. Feel free to open a bug and I will
> look into it when I get back.
> 

Cc @fruch

**Comment by espindola** [comment]
As explained, this has *nothing* to do with iotune and the description
in the revert message is wrong. What is actually happening is:

   That log has

   [2019-12-19T08:27:43.350Z] Getting artifact scylla/build/debug/scylla-package.tar.gz
   [2019-12-19T08:27:43.409Z] [Pipeline] step
   [2019-12-19T08:28:09.831Z] Copied 1 artifact from "scylla-master » next" build number 1417

   And the next build does

   [2019-12-19T06:36:40.481Z] + /jenkins/workspace/scylla-master/next/scylla/tools/toolchain/dbuild -v /jenkins/mirror.git:/jenkins/mirror.git -v /var/cache/ccache:/var/cache/ccache:z -e
   CCACHE_DIR=/var/cache/ccache -e CCACHE_UMASK=002 -e PATH=/usr/lib64/ccache:/usr/bin:/usr/sbin -- ./reloc/build_reloc.sh --mode debug --compiler g++ --configure-flags '--debuginfo 1
   --tests-debuginfo 0   --enable-dpdk ' --jobs 48

   So --configure-flags is used, and DEFAULT_FLAGS is not. The issue is not
   iotune versus scylla.

**Comment by espindola** [comment]
I think this (and its dependencies) should be backported to 3.2 so that we get reliable mapping from core files to executables.
@avi, do you agree?

**Comment by avikivity** [comment]
I agree, but all the branches aged out.
