### ISSUE TITLE
init - Failed owner and mode verification: std::runtime_error (Failed to get .../view_hints/0/.o_direct_test type.)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5510]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/349/testReport/compaction_test/TestCompaction_with_LeveledCompactionStrategy/sstable_deletion_test/
```
Unexpected error in node1 node log: ['ERROR 2019-12-22 02:26:35,406 [shard 0] init - Failed owner and mode verification: std::runtime_error (Failed to get /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-s7yQcE/test/node1/view_hints/0/.o_direct_test type.)\nERROR 2019-12-22 02:26:35,408 [shard 0] init - Failed owner and mode verification: std::runtime_error (Failed to get /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-s7yQcE/test/node1/hints/1/.o_direct_test type.)']
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/349/testReport/paging_additional_test/TestLargePaging/test_large_page_range_queries/
```
Unexpected error in node3 node log: ['ERROR 2019-12-22 03:11:13,503 [shard 0] init - Failed owner and mode verification: std::runtime_error (Failed to get /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-3vRrBg/test/node3/hints/1/.o_direct_test type.)']
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/349/testReport/repair_additional_test/RepairAdditionalTest/repair_option_pr_dc_host_test_2/
```
Unexpected error in node2 node log: ['ERROR 2019-12-22 03:44:53,295 [shard 0] init - Failed owner and mode verification: std::runtime_error (Failed to get /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-xis5EW/test/node2/view_hints/0/.o_direct_test type.)']
```

Scylla version 3a6cb0ed8c5057aea2473319be32ca86d67211df

**Comment by bhalevy** [comment]
I suspect that due to changes in parallelism introduced in 00ae4af94c73e11568aed026af8f830cdf1756ce
`distributed_loader::verify_owner_and_mode` which is recursive sees the `.o_direct_test` files created and removed by `disk_sanity` in parallel, on sub-directories.

`verify_owner_and_mode` should be run only on the root dir of any unique path.

**Comment by bhalevy** [comment]
Maybe it's the change in 373fcfdb3e519263902f9e355d514bd834da1e1b from `std::unordered_set` to `std::vector`.
In any case, we can either not run `verify_owner_and_mode` on the per-shard direcotries, only on the base directory of `cfg.hints_directory()` and `cfg.view_hints_directory()`, or we can serialize `touch_and_lock(path).then( return disk_sanity(path); }` on all dirs (in parallel) with `verify_owner_and_mode` on all dirs (in parallel).

**Comment by xemul** [comment]
Another option is not to mess with the basedir at all, but only check, touch, lock and scan per-shard ones.

**Comment by bhalevy** [comment]
That is simpler and will require less code, though it will do some unnecessary calls to `disk_sanity` and `verify_owner_and_mode` on each per-shard dir rather than just on the base dirs, but we don't have to optimize for that since this is done once during startup so it's a valid approach too.

**Comment by avikivity** [comment]
Aged out.
