### ISSUE TITLE
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000007a1000000, 191365120, 0) failed; error='Cannot allocate memory'       (errno=12)

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5515]
*Installation details*
Scylla version (or git commit hash): 3.2.rc3-0.20191215.39b17be5620
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0cab4c6eceb3249ac (eu-west-2)

### Description:

In decommission nemesis of (2019-12-20 08:36 UTC), that's the last nemesis of this job.
Workloads failed for memory allocate when the new node was bootstraping. I didn't found serious db error around that point. loader has 16G memory

The new node (longevity-tls-1tb-7d-3-2-db-node-5eef4f47-10) finally got ready.

Grafana snapshot of last nemesis: https://snapshot.raintank.io/dashboard/snapshot/uwshsi1PI84M31n7eZ97L0SMtHyC9KM0
Grafana snapshot of whole test: https://snapshot.raintank.io/dashboard/snapshot/gCIuI2KG3lw6pL9kz8nih36W8x1dCVw5

### ERROR from workloads:

There is insufficient memory for the Java Runtime Environment to continue.', '# Native memory allocation (mmap) failed to map 191365120      bytes for committing reserved memory.', '# An error report file with more information is saved as:', '# /h
ome/centos/hs_err_pid22552.log', 'Failed to connect over JMX; not collecting these stats', 'Failed to connect over JMX; not collecting these stats
', "OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000007a1000000, 191365120, 0) failed; error='Cannot allocate memory'       (errno=12)"

#### 4 JVM ERROR files from two loaders:

- https://storage.cloud.google.com/upload.scylladb.com/amos/3.2-longevity-1tb/hs_err_pid16904.log?authuser=0
- https://storage.cloud.google.com/upload.scylladb.com/amos/3.2-longevity-1tb/hs_err_pid18174.log?authuser=0
- https://storage.cloud.google.com/upload.scylladb.com/amos/3.2-longevity-1tb/hs_err_pid22552.log?authuser=0
- https://storage.cloud.google.com/upload.scylladb.com/amos/3.2-longevity-1tb/hs_err_pid4054.log?authuser=0

### Living cluster:

- https://eu-west-1.console.aws.amazon.com/ec2/home?region=eu-west-1#Instances:search=5eef4f47;sort=tag:Name

INFO:
- longevity-tls-1tb-7d-3-2-db-node-5eef4f47-1 [34.254.190.145 | 10.0.212.240] (living)
- longevity-tls-1tb-7d-3-2-db-node-5eef4f47-2 [34.245.23.233 | 10.0.145.169]
- longevity-tls-1tb-7d-3-2-db-node-5eef4f47-3 [34.244.242.32 | 10.0.16.209]
- longevity-tls-1tb-7d-3-2-db-node-5eef4f47-4 [34.251.249.77 | 10.0.30.12]
- longevity-tls-1tb-7d-3-2-db-node-5eef4f47-5 [18.203.221.38 | 10.0.207.147]
- longevity-tls-1tb-7d-3-2-db-node-5eef4f47-6 [52.213.83.251 | 10.0.138.70] (living)
- longevity-tls-1tb-7d-3-2-db-node-5eef4f47-7 [34.241.149.163 | 10.0.165.51]
- longevity-tls-1tb-7d-3-2-db-node-5eef4f47-8 [34.243.155.34 | 10.0.185.85]
- longevity-tls-1tb-7d-3-2-db-node-5eef4f47-9 [18.203.254.211 | 10.0.190.129] (living)
- longevity-tls-1tb-7d-3-2-db-node-5eef4f47-10 [54.154.212.156 | 10.0.253.252] (living)

Loader:
- longevity-tls-1tb-7d-3-2-loader-node-5eef4f47-1: 34.254.198.37  16G memory
- longevity-tls-1tb-7d-3-2-loader-node-5eef4f47-2: 34.254.232.29 16G memory

### Monitor:
- http://34.245.130.24:3000/d/luEK45fWz/scylla-per-server-metrics-nemesis-3-2?orgId=1&from=1576563711698&to=1576875980616&var-by=instance&var-cluster=&var-dc=All&var-node=All&var-shard=All

### SCT configuration YAML
https://github.com/scylladb/scylla-cluster-tests/blob/branch-3.2/test-cases/longevity/longevity-1TB-7days-authorization-and-tls-ssl.yaml

### instance type:
- instance_type_db: i3.4xlarge
-  instance_type_loader: c5.2xlarge
-  instance_type_monitor: t3.large

**Comment by amoskong** [comment]
### Test job: 
https://jenkins.scylladb.com/job/scylla-3.2/job/longevity/job/longevity-1tb-7days/6/console

### Test id:
 5eef4f47-1867-49f9-bca0-0054d7d8bfdf

### Test logs: 
- https://cloudius-jenkins-test.s3.amazonaws.com/5eef4f47-1867-49f9-bca0-0054d7d8bfdf/grafana-screenshot-overview-20191220_115911-longevity-tls-1tb-7d-3-2-monitor-node-5eef4f47-1.png
- https://cloudius-jenkins-test.s3.amazonaws.com/5eef4f47-1867-49f9-bca0-0054d7d8bfdf/grafana-screenshot-scylla-per-server-metrics-nemesis-20191220_115859-longevity-tls-1tb-7d-3-2-monitor-node-5eef4f47-1.png
- https://cloudius-jenkins-test.s3.amazonaws.com/5eef4f47-1867-49f9-bca0-0054d7d8bfdf/20191220_120157/db-cluster-5eef4f47.zip
- https://cloudius-jenkins-test.s3.amazonaws.com/5eef4f47-1867-49f9-bca0-0054d7d8bfdf/20191220_120157/loader-set-5eef4f47.zip
- https://cloudius-jenkins-test.s3.amazonaws.com/5eef4f47-1867-49f9-bca0-0054d7d8bfdf/20191220_120157/monitor-set-5eef4f47.zip
- https://cloudius-jenkins-test.s3.amazonaws.com/5eef4f47-1867-49f9-bca0-0054d7d8bfdf/20191220_120157/sct-runner-5eef4f47.zip

**Comment by roydahan** [comment]
@amoskong why is it opened for "scylla"? maybe for "scylla-tools-java" or the new driver if it's related.

**Comment by amoskong** [comment]
> @amoskong why is it opened for "scylla"? maybe for "scylla-tools-java" or the new driver if it's related.

It seems problem of client side.  issues in scylla-tools-java is easy to be ignored.

**Comment by amoskong** [comment]
@roydahan @slivne   do you want to find someone check the cluster?
If not, I will terminate it.

BTW, in the comment 0, there are 4 JVM error files, can someone check if it's helpful?

**Comment by amoskong** [comment]
> @roydahan @slivne do you want to find someone check the cluster?
> If not, I will terminate it.

> BTW, in the comment 0, there are 4 JVM error files, can someone check if it's helpful?

ping

**Comment by slivne** [comment]
kill the cluster ...

**Comment by amoskong** [comment]
> kill the cluster ...

The cluster had been killed last week, ping you for checking the JVM error files.

**Comment by slivne** [comment]
@elcallio when you are back can you have a brief look and see if you can make a sesne out of it ....

**Comment by slivne** [comment]
@amoskong does this reproduce everytime ?

**Comment by amoskong** [comment]
No.

**Comment by avikivity** [comment]
Was this running cassandra-stress? Or nodetool?

**Comment by amoskong** [comment]
> Was this running cassandra-stress? Or nodetool?

the error is from cassandra-stress

**Comment by elcallio** [comment]
Fwiw, I cannot really see anything beyond "cassandra stress managed to get a hard OOM". Note that it was native allocation (i.e. JVM itself) that failed allocation, so my guess is that java mx flags were not set?
Might be an idea to set those to something less than sum of ram+swap.

**Comment by slivne** [comment]
@amoskong are we hitting this - if not please close
