### ISSUE TITLE
"Schema version is not same on all nodes" after Add/Drop column

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla#5517]
We have implemented new nemesis that Adds and Drops columns, on very first test run we spotted following error:
```
2019-12-23 13:26:45.704: 
Schema version is not same on all nodes in gossip info: 
10.0.153.140: 3d938bdc-c217-3a5d-9b08-8e533f45c013
10.0.57.251: 9c2ee0b9-d597-3770-9d65-24c2a21cb193
10.0.19.49: 3d938bdc-c217-3a5d-9b08-8e533f45c013
```
This run contained only 5 AddDropColumnNemisises.
Test id: 87a6d3e3-b03c-4edf-a505-df7a4f24880c
AMI: (eu-west-1) ami-0774f71da58840549
Scylla Branch: branch-3.2:latest

Main c-s: cassandra-stress write cl=QUORUM duration=180m -schema keyspace=keyspace1 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=1000 -pop seq=1..10000000 -log interval=5 -node 10.0.57.251

Error:
(ClusterHealthValidatorEvent Severity.CRITICAL): type=error name=GossipNodeSchemaVersion node=dk-byo-longevity-10gb-3h-master-db-node-87a6d3e3-1 error=Schema version is not same on all nodes in gossip info: 10.0.153.140: 3d938bdc-c217-3a5d-9b08-8e533f45c013
10.0.57.251: 9c2ee0b9-d597-3770-9d65-24c2a21cb193
10.0.19.49: 3d938bdc-c217-3a5d-9b08-8e533f45c013

![Screenshot from 2019-12-24 17-30-18](https://user-images.githubusercontent.com/40304587/71409204-49d4d180-2673-11ea-8fbb-fab222fea577.png)
[logs.zip](https://github.com/scylladb/scylla/files/3998071/logs.zip)

**Comment by roydahan** [comment]
not scylla issue
