### ISSUE TITLE
C* like Memtable

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#552]
A Memtable is basically a write-back cache of data rows that can be looked up by key -- that is, unlike a write-through cache, writes are batched up in the Memtable until it is full, when it is flushed.
https://wiki.apache.org/cassandra/MemtableSSTable

**Comment by avikivity** [comment]
Not sure what the problem is

**Comment by tzach** [comment]
Enhancement, not a bug

**Comment by slivne** [comment]
why do we need it ...

it seems like using a column family without commitlog - or is it more then
that ?

**Comment by avikivity** [comment]
What is the enhancement?

Try not to write issues as statements, instead try to write what is 
wrong with the current situation and how it could be improved.
