### ISSUE TITLE
Strange gossip status message `[shard 0] gossip - InetAddress 10.88.1.1 is now UP, status = `

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#5520]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.1.2
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): docker

I see the following message in the log, after bootstrapping the second node. What does it mean?

```
INFO  2019-12-25 14:16:29,119 [shard 0] gossip - InetAddress 10.88.1.1 is now UP, status = 
```

**Comment by asias** [comment]
1) Bootstrap n1
2) Bootstrap n2

On n1, you saw after step 2: 
```
gossip - InetAddress n2 is now UP, status =
```

This is because n2 joins gossip but hasn't set any status application state yet.  The first application state a bootstrapping node set is "bootstrapping" which is way later than n2 starts gossip service.

**Comment by slivne** [comment]
@avikivity does this answer the question ?

**Comment by avikivity** [comment]
It does, but it's still a bug. There should be some state in that message.

**Comment by avikivity** [comment]
Maybe UNKNOWN. Better to set it to a known value, but just leaving it blank is bad.

**Comment by avikivity** [comment]
@slivne it's not a question, it's a bug report. We shouldn't have strange messages.

**Comment by asias** [comment]
PR is sent: https://github.com/scylladb/scylla/pull/5606

**Comment by avikivity** [comment]
Aged out.
