### ISSUE TITLE
scylla crashes with a very cryptic error: scylla: build_id.cc:44: const Elf64_Nhdr* get_nt_build_id(dl_phdr_info*): Assertion `0 && "no NT_GNU_BUILD_ID note"' failed. 

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#5525]
*Installation details*
HEAD: 60a851d3a55f973e65ee71af61516f2750fe4aeb
OS: Ubuntu 19.10
Compiler: g++ (Ubuntu 9.2.1-9ubuntu2) 9.2.1 20191008

*Description*
Scylla build from a local repository crashes right on the start with the following symptom:
```
 scylla: build_id.cc:44: const Elf64_Nhdr* get_nt_build_id(dl_phdr_info*): Assertion `0 && "no NT_GNU_BUILD_ID note"' failed. 
```

This is a regression introduced by the following patch:
```
commit 91c7f5bf4470783dd03d1c3c2c4c972302251e08
Author: Rafael Ávila de Espíndola <espindola@scylladb.com>
Date:   Tue Dec 17 19:15:56 2019 -0800
    Print build-id on startup
    Fixes #5426
    Signed-off-by: Rafael Ávila de Espíndola <espindola@scylladb.com>
    Message-Id: <20191218031556.120089-1-espindola@scylladb.com>
```

*Steps to reproduce*
1) Build scylla:
   * ./configure.py --compiler=g++-9 '--cflags=-Wno-attributes -Wno-unused-result -Wno-missing-attributes -Wno-array-bounds -I/usr/include/lua5.3' --c-compiler=gcc-9 '--ldflags=-fuse-ld=lld -L/usr/local/lib -lfmt'
   * ninja ./build/debug/scylla (the same reproduced with `dev` build as well).
2) Run `scylla --help`

**Comment by bhalevy** [comment]
How did you hit it?
Is it reproducible?

**Comment by vladzcloudius** [comment]
> How did you hit it?
> Is it reproducible?

Yes, it's very easily reproducible.
I updated the description.

**Comment by espindola** [comment]
> To add to the insult when I revert the patch in question scylla is able to print build ID just fine:
> 
> ```
> $ ./build/debug/scylla --version
> 666.development-0.20191226.60a851d3a
> ```

That is not the build-id.

> _Steps to reproduce_
> 
>     1. Build scylla.

How? Please provide the exact commands and environment you used. In particular, are you using dbuild?

**Comment by vladzcloudius** [comment]
> > To add to the insult when I revert the patch in question scylla is able to print build ID just fine:
> > ```
> > $ ./build/debug/scylla --version
> > 666.development-0.20191226.60a851d3a
> > ```
> 
> That is not the build-id.

@espindola 
Sorry. I didn't understand it at first - I fixed the description.

> 
> > _Steps to reproduce_
> > ```
> > 1. Build scylla.
> > ```
> 
> How? Please provide the exact commands and environment you used. In particular, are you using dbuild?

No, I didn't (see the updated description).

**Comment by espindola** [comment]
looking, thanks.

**Comment by espindola** [comment]
I think this and its dependencies should be backported to 3.2 so that logs produced by 3.2 include the build-id.
@avi, do you agree?

**Comment by avikivity** [comment]
Should have been backported, but wasn't. Meanwhile aged out.
