### ISSUE TITLE
--cpuset parameter doesn't work on Ubuntu 14.04

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#554]
Package used: scylla-server_0.10-ubuntu1
Ubuntu distro: 14.04

The actual CPU indices values in --cpuset  are ignored and scyllaDB uses CPUs starting from CPU0.
It do parses the --cpuset value to get the requested number of CPUs though.

For instance, if "--cpuset 4-7" is given, only CPUs 0, 1, 2 and 3 will be used. 

The CPUs that are going to be used are always the contiguous range of CPUs staring from CPU0.

For instance, if "--cpuset 4,6,8,9" is given, scyllaDB will use CPUs 0,1,2 and 3.

**Comment by vladzcloudius** [comment]
When I built the executable manually:
1) Built and installed all the dependencies by applying this patch:
```
diff --git a/dist/ubuntu/build_deb.sh b/dist/ubuntu/build_deb.sh
index 4724b38..30e99dd 100755
--- a/dist/ubuntu/build_deb.sh
+++ b/dist/ubuntu/build_deb.sh
@@ -24,4 +24,6 @@ cp dist/ubuntu/changelog.in debian/changelog
 sed -i -e "s/@@VERSION@@/$SCYLLA_VERSION/g" debian/changelog
 sed -i -e "s/@@RELEASE@@/$SCYLLA_RELEASE/g" debian/changelog

+exit 0
+
 debuild -r fakeroot --no-tgz-check -us -uc
```
and then running `./dist/ubuntu/build_deb.sh`
2) `./configure.py --compiler=g++-5 --disable-xen --enable-dpdk`
3) `ninja`

--cpuset works as expected.

There must be something in the way the .deb package is built.

**Comment by syuu1228** [comment]
I found it causing because of missing libhwloc, so we need to add it on package dependencies.
It seems disabled on building time, because build script haven't installed libhwloc-dev.
I'll send a fix for it.
