### ISSUE TITLE
storage_service::_is_bootstrap_mode may be used uninitialized

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5543]
Found by ubsan with bootstrap_test:TestBootstrap.manual_bootstrap_test in debug mode:
  service/storage_service.cc:3519:37: runtime error: load of value 190, which is not a valid value for type 'bool'

Scylla version 60a851d3a55f973e65ee71af61516f2750fe4aeb

The use site is:
  service::storage_service::is_cleanup_allowed(seastar::basic_sstring<char, unsigned int, 15u, true>)::{lambda(service::storage_service&)#1}::operator()(service::storage_service&) const at /local/home/bhalevy/dev/scylla/service/storage_service.cc:3519

https://github.com/scylladb/scylla/blob/aa87169670931336c4568f9cf7efd2940e387df3/service/storage_service.cc#L3519-L3522

**Comment by bhalevy** [comment]
Introduce in f87658074081e2802100e5480cea6c1f8d4b1053
Since branch-3.2

**Comment by bhalevy** [comment]
Will be fixed by 8aa5d84dd85011276833f3cafc367f5b200c7ad5 (currently merged to next)

**Comment by avikivity** [comment]
No vulnerable branches.
