### ISSUE TITLE
User-defined types with quoted names are unusable

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5544]
The following simple test case currently fails:
```c++
SEASTAR_TEST_CASE(test_user_type_quoted) {
    return do_with_cql_env_thread([] (cql_test_env& e) {
        e.execute_cql("CREATE TYPE ks.\"PHone\" (country_code int, number text)").discard_result().get();
        e.execute_cql("CREATE TABLE ks.cf (pk blob, pn \"PHone\", PRIMARY KEY (pk))").discard_result().get();
    });
}
```
The test creates a user-defined type with a quoted (i.e., case-sensitive) name, as CQL allows - "PHone". The test then tries to use this type name "PHone" in a CREATE TABLE command - but that unfortunately fails - we get an exception:
```
exceptions::invalid_request_exception: Unknown type ks.phone
```
In other words, the CREATE TABLE command mistakenly lowercased the type name PHone while searching for it.

Interestingly, while this test fails, trying a similar sequence of commands via cqlsh works. My guess is that the difference is between prepared and non-prepared statements, maybe the former (which cql_test_env uses) parses types to and from CQL too many times, and in one of these stages of translation, some fidelity is lost. Or something (?). 

Thanks to @amnonh for helping me hunt down this bug.

**Comment by nyh** [comment]
@slivne I already sent a patch for this issue and i was committed (to next), so assigning it to me now is a bit too late :-)

**Comment by avikivity** [comment]
No vulnerable branches.
