### ISSUE TITLE
alternator test failures in HTTPS mode because of unwanted certificated verification

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5557]
When running "pytest --https", 4 tests fail, in two files - test_authorization and test_health:

All four errors are caused by
```
E               SSLError: HTTPSConnectionPool(host='localhost', port=8043): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)'),))
```

We use made-up SLL certificates in the tests, they shouldn't be verified. We have the code disabling the verification, but apparently we forgot to disable it in some of the tests.

@psarna

**Comment by psarna** [comment]
sent a patch to the list: `[PATCH] alternator-test: turn off TLS self-signed verification`

**Comment by nyh** [comment]
Already in branch 4.0, and not backporting test improvements to earlier branches.
