### ISSUE TITLE
Setting setcap=ep prevents scylla from generating core dumps

### ISSUE THREAD

**Issue by ultrabug** [scylladb/scylla#5560]
While trying to debug scylla with Gleb and wondering why scylla didn't create a coredump after crashing I found out that it was because I had set capabilities +ep to the scylla binary.

# Context

When starting up scylla on my nodes, I had the following message:

```
scylla:  [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
```

so I added the requested cap_sys_nice using:

```
setcap 'cap_sys_nice=ep' /usr/bin/scylla
```

which indeed cleared the startup message...

but then when scylla crashed, no coredump was generated!

reverting the setcap and having scylla crash generates the coredump alright..

**Comment by espindola** [comment]
I can reproduce that locally. It looks to be the expected behavior and
is controlled by /proc/sys/fs/suid_dumpable.

Looks like scylla should also be able to use prctl(PR_SET_DUMPABLE...)
to override this.

BTW, this warning is only printed by the epoll backend. That means that
detect_aio_poll is returning false for you. Any idea why?

Cheers,
Rafael

**Comment by avikivity** [comment]
Old kernel (or old scylla, that doesn't have the aio backend)

**Comment by ultrabug** [comment]
kernel is linux-4.15.7

scylla is 3.1.2

```
$ zgrep AIO /proc/config.gz
CONFIG_AIO=y
```

what is the kernel CONFIG I should be looking for plz?

**Comment by espindola** [comment]
> kernel is linux-4.15.7

Looks like aio poll was added in bfe4037e722ec672c9dafd5730d9132afeeb76e9, which seems to be 4.18.

**Comment by ultrabug** [comment]
Thanks @espindola !

**Comment by avikivity** [comment]
Backported to 3.1, 3.2 (3.3 already had it).
