### ISSUE TITLE
environment file path is wrong in scylla-server.service

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5570]
*Installation details*
Scylla version (or git commit hash): scylla_666.development-0.20200107.6e0a073b2e5-1_amd64
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 10

### Description

Scylla setup completed (exit code is 0), but failed to start scylla-server

```
scylla-test@amos-debian10:~$ sudo systemctl restart scylla-server 
Job for scylla-server.service failed because of unavailable resources or another system error.
See "systemctl status scylla-server.service" and "journalctl -xe" for details.
scylla-test@amos-debian10:~$ echo $?
1

scylla-test@amos-debian10:~$ systemctl status scylla-server.service -f
● scylla-server.service - Scylla Server
   Loaded: loaded (/lib/systemd/system/scylla-server.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/scylla-server.service.d
           └─mounts.conf
   Active: failed (Result: resources) since Wed 2020-01-08 11:51:49 UTC; 14s ago

scylla-test@amos-debian10:~$ sudo journalctl  -u scylla-server -f
-- Logs begin at Wed 2020-01-08 10:55:07 UTC. --
Jan 08 11:48:25 amos-debian10 systemd[1]: scylla-server.service: Failed to load environment files: No such file or directory
Jan 08 11:48:25 amos-debian10 systemd[1]: scylla-server.service: Failed to run 'start-pre' task: No such file or directory
Jan 08 11:48:25 amos-debian10 systemd[1]: scylla-server.service: Failed with result 'resources'.
Jan 08 11:48:25 amos-debian10 systemd[1]: Failed to start Scylla Server.
Jan 08 11:48:25 amos-debian10 systemd[1]: scylla-server.service: Service RestartSec=100ms expired, scheduling restart.
Jan 08 11:48:25 amos-debian10 systemd[1]: scylla-server.service: Scheduled restart job, restart counter is at 5.
Jan 08 11:48:25 amos-debian10 systemd[1]: Stopped Scylla Server.
Jan 08 11:48:25 amos-debian10 systemd[1]: scylla-server.service: Start request repeated too quickly.
Jan 08 11:48:25 amos-debian10 systemd[1]: scylla-server.service: Failed with result 'resources'.
Jan 08 11:48:25 amos-debian10 systemd[1]: Failed to start Scylla Server.
```

### env file path is wrong in systemd config:

```
scylla-test@amos-debian10:~$ grep Env /lib/systemd/system/scylla-server.service 
EnvironmentFile=/etc/sysconfig/scylla-server
EnvironmentFile=/etc/scylla.d/*.conf

scylla-test@amos-debian10:~$ ls /etc/scylla.d/*.conf
/etc/scylla.d/cpuset.conf  /etc/scylla.d/dev-mode.conf  /etc/scylla.d/io.conf

scylla-test@amos-debian10:~$ ls /etc/sysconfig/scylla-server
ls: cannot access '/etc/sysconfig/scylla-server': No such file or directory

scylla-test@amos-debian10:~$ ls /etc/default/scylla-server 
/etc/default/scylla-server
scylla-test@amos-debian10:~$ ls /etc/default/scylla-server  -l
-rw-r--r-- 1 root root 944 Jan  8 11:43 /etc/default/scylla-server
```

### Scylla Setup Log:

[debian10-scylla-setup-log.txt](https://github.com/scylladb/scylla/files/4035125/debian10-scylla-setup-log.txt)

**Comment by syuu1228** [comment]
This is local build of latest master .deb, we should have /etc/systemd/system/scylla-server.service.d/sysconfdir.conf like this.
Otherwise something going wrong.
I'll check what's happening.

```
root@04b2650d0c4d:/# systemctl status scylla-server.service
● scylla-server.service - Scylla Server
   Loaded: loaded (/lib/systemd/system/scylla-server.service; disabled; vendor p
  Drop-In: /etc/systemd/system/scylla-server.service.d
           └─dependencies.conf, sysconfdir.conf
   Active: inactive (dead)

root@04b2650d0c4d:/# dpkg -L scylla-server|grep /etc/systemd
/etc/systemd
/etc/systemd/system
/etc/systemd/system/scylla-housekeeping-daily.service.d
/etc/systemd/system/scylla-housekeeping-daily.service.d/sysconfdir.conf
/etc/systemd/system/scylla-housekeeping-restart.service.d
/etc/systemd/system/scylla-housekeeping-restart.service.d/sysconfdir.conf
/etc/systemd/system/scylla-server.service.d
/etc/systemd/system/scylla-server.service.d/dependencies.conf
/etc/systemd/system/scylla-server.service.d/sysconfdir.conf
root@04b2650d0c4d:/# cat /etc/systemd/system/scylla-server.service.d/sysconfdir.conf
[Service]
EnvironmentFile=
EnvironmentFile=/etc/default/scylla-server
EnvironmentFile=/etc/scylla.d/*.conf
```

**Comment by syuu1228** [comment]
sysconfdir.conf is generated by install.sh, only when --sysconfdir <directory> is specified.
https://github.com/scylladb/scylla/blob/master/install.sh#L194
And we call install.sh --sysconfdir /etc/default on debian/rules.
https://github.com/scylladb/scylla/blob/master/dist/debian/rules.mustache#L20

I just compared these two scripts, seems like branch-3.2 and master does not have difference with the conf file generation.

@amoskong does the problem fix by systemctl daemon-reload?
The package contains /etc/systemd/system/scylla-server.service.d/sysconfdir.conf or not?

**Comment by syuu1228** [comment]
I just tested scylla 3.2.rc4 on Debian 10, and it just works for me.
The package has /etc/systemd/system/scylla-server.service.d/sysconfdir.conf
So I'm not able to reproduce the problem, and package itself looks correct.
(Unless it was because of daemon-reload issue, again)

```
root@04b2650d0c4d:/etc/apt/sources.list.d# dpkg -l|grep scylla-server
ii  scylla-server                    3.2.rc4-0.20200105.c8d5738a482-1 amd64        Scylla database server binaries
root@04b2650d0c4d:/etc/apt/sources.list.d# cat /etc/systemd/system/scylla-server.service.d/sysconfdir.conf
[Service]
EnvironmentFile=
EnvironmentFile=/etc/default/scylla-server
EnvironmentFile=/etc/scylla.d/*.conf
root@04b2650d0c4d:/etc/apt/sources.list.d# systemctl start scylla-server
root@04b2650d0c4d:/etc/apt/sources.list.d# systemctl status scylla-server
● scylla-server.service - Scylla Server
   Loaded: loaded (/lib/systemd/system/scylla-server.service; disabled; vendor p
  Drop-In: /etc/systemd/system/scylla-server.service.d
           └─dependencies.conf, sysconfdir.conf
   Active: active (running) since Wed 2020-01-08 18:38:15 UTC; 4s ago
  Process: 31978 ExecStartPre=/opt/scylladb/scripts/scylla_prepare (code=exited,
 Main PID: 31987 (scylla)
   Status: "starting storage service"
    Tasks: 40 (limit: 77045)
   Memory: 1.2G
   CGroup: /docker/04b2650d0c4d02ad085b3639b66779149b6a1ffda6e1cce4254c4520f8313
           └─31987 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default

Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 18] compaction - Compacted 2
Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 19] compaction - Compacted 2
Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 10] compaction - Compacted 2
Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 6] compaction - Compacting [
Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 0] database - Schema version
Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 0] storage_service - Startin
Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 6] compaction - Compacted 2
Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 6] compaction - Compacting [
Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 0] messaging_service - Start
Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 6] compaction - Compacted 2

```

**Comment by amoskong** [comment]
The problem can't be solved by daemon-reload.
In the scylla-server.service file, EnvironmentFile is set to `/etc/sysconfig/scylla-server` (centos style)
Actually the env file is in another directory: /etc/default/scylla-server   (deb style)

/etc/systemd/system/scylla-server.service.d/sysconfdir.conf doesn't exist.

```
scylla-test@amos-debian10:~$ sudo find /etc|grep sysconfdir
/etc/systemd/system/scylla-jmx.service.d/sysconfdir.conf
scylla-test@amos-debian10:~$ ls /etc/systemd/system/scylla-server.service.d/sysconfdir.conf
ls: cannot access '/etc/systemd/system/scylla-server.service.d/sysconfdir.conf': No such file or directory

scylla-test@amos-debian10:~$ dpkg -l |grep scylla
ii  scylla                                666.development-0.20200107.6e0a073b2e5-1 amd64        Scylla database metapackage
ii  scylla-conf                           666.development-0.20200107.6e0a073b2e5-1 amd64        Scylla database main configuration file
ii  scylla-jmx                            666.development-20200108.4c8660d41ad-1   all          Scylla JMX server binaries
ii  scylla-kernel-conf                    666.development-0.20200107.6e0a073b2e5-1 amd64        Scylla kernel tuning configuration
ii  scylla-python3                        3.7.5-0.20200108.6e0a073b2e5-1           amd64        A standalone python3 interpreter that can be moved around different Linux machines
ii  scylla-server                         666.development-0.20200107.6e0a073b2e5-1 amd64        Scylla database server binaries
ii  scylla-tools                          666.development-20200108.76275abbacd-1   all          Scylla database tools
ii  scylla-tools-core                     666.development-20200108.76275abbacd-1   all          Scylla database tools core files
```

**Comment by amoskong** [comment]
> I just tested scylla 3.2.rc4 on Debian 10, and it just works for me.

Did you test with a clean env?

I touched https://github.com/scylladb/scylla/issues/5585 in testing with latest master & 3.2 on Debian 10.


> The package has /etc/systemd/system/scylla-server.service.d/sysconfdir.conf
> So I'm not able to reproduce the problem, and package itself looks correct.
> (Unless it was because of daemon-reload issue, again)
> 
> ```
> root@04b2650d0c4d:/etc/apt/sources.list.d# dpkg -l|grep scylla-server
> ii  scylla-server                    3.2.rc4-0.20200105.c8d5738a482-1 amd64        Scylla database server binaries
> root@04b2650d0c4d:/etc/apt/sources.list.d# cat /etc/systemd/system/scylla-server.service.d/sysconfdir.conf
> [Service]
> EnvironmentFile=
> EnvironmentFile=/etc/default/scylla-server
> EnvironmentFile=/etc/scylla.d/*.conf
> root@04b2650d0c4d:/etc/apt/sources.list.d# systemctl start scylla-server
> root@04b2650d0c4d:/etc/apt/sources.list.d# systemctl status scylla-server
> ● scylla-server.service - Scylla Server
>    Loaded: loaded (/lib/systemd/system/scylla-server.service; disabled; vendor p
>   Drop-In: /etc/systemd/system/scylla-server.service.d
>            └─dependencies.conf, sysconfdir.conf
>    Active: active (running) since Wed 2020-01-08 18:38:15 UTC; 4s ago
>   Process: 31978 ExecStartPre=/opt/scylladb/scripts/scylla_prepare (code=exited,
>  Main PID: 31987 (scylla)
>    Status: "starting storage service"
>     Tasks: 40 (limit: 77045)
>    Memory: 1.2G
>    CGroup: /docker/04b2650d0c4d02ad085b3639b66779149b6a1ffda6e1cce4254c4520f8313
>            └─31987 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default
> 
> Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 18] compaction - Compacted 2
> Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 19] compaction - Compacted 2
> Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 10] compaction - Compacted 2
> Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 6] compaction - Compacting [
> Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 0] database - Schema version
> Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 0] storage_service - Startin
> Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 6] compaction - Compacted 2
> Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 6] compaction - Compacting [
> Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 0] messaging_service - Start
> Jan 08 18:38:15 04b2650d0c4d scylla[31987]:  [shard 6] compaction - Compacted 2
> ```

**Comment by syuu1228** [comment]
@amoskong If it's not part of the package you maybe correct, but it's appear on "dpkg -L <pkg>".
if it's part of the package the file should be exist (unless we do on bad thing on .postinst handler or something).
I just tested again with yesterday build on newly created docker instance, sysconfdir.conf still exist finely.
```
root@936c37cb70c7:/etc/apt/sources.list.d# dpkg -l|grep scylla-server
ii  scylla-server                 666.development-0.20200111.3853594108-1 amd64        Scylla database server binaries
root@936c37cb70c7:/etc/apt/sources.list.d# cat /etc/systemd/system/scylla-server.service.d/sysconfdir.conf
[Service]
EnvironmentFile=
EnvironmentFile=/etc/default/scylla-server
EnvironmentFile=/etc/scylla.d/*.conf
```

**Comment by syuu1228** [comment]
@amoskong Sorry, latest my comment was not branch-3.2, I'll test again with 3.2

**Comment by syuu1228** [comment]
No, on this issue you mentioned version "666.development-0.20200107.6e0a073b2e5", so testing on master is correct

**Comment by syuu1228** [comment]
Just for make sure the issue does not occur on my side, tested with "3.2.rc4-0.20200109.7eb86fbbb40-1" on newly created Debian 10 Docker image:

```
root@c33f19210863:/etc/apt/sources.list.d# systemctl status scylla-server
● scylla-server.service - Scylla Server
   Loaded: loaded (/lib/systemd/system/scylla-server.service; disabled; vendor p
reset: enabled)
  Drop-In: /etc/systemd/system/scylla-server.service.d
           └─dependencies.conf, sysconfdir.conf
   Active: inactive (dead)
root@c33f19210863:/etc/apt/sources.list.d# dpkg -S /etc/systemd/system/scylla-server.service.d/sysconfdir.conf 
scylla-server: /etc/systemd/system/scylla-server.service.d/sysconfdir.conf
root@c33f19210863:/etc/apt/sources.list.d# cat /etc/systemd/system/scylla-server.service.d/sysconfdir.conf 
[Service]
EnvironmentFile=
EnvironmentFile=/etc/default/scylla-server
EnvironmentFile=/etc/scylla.d/*.conf
root@c33f19210863:/etc/apt/sources.list.d# dpkg -l|grep scylla-server
ii  scylla-server             3.2.rc4-0.20200109.7eb86fbbb40-1 amd64        Scylla database server binaries
```

**Comment by syuu1228** [comment]
@amoskong ping, do you still not possible to get sysconfdir.conf on your testing environment?

**Comment by yarongilor** [comment]
All Debian and Ubuntu rolling-upgrade tests are failing for this error after rollback from 3.3 (or master) to 3.2

**Comment by amoskong** [comment]
@yarongilor I just reported a new issue (https://github.com/scylladb/scylla/issues/5734) for the problem in upgrade test.

**Comment by amoskong** [comment]
Can't reproduce with problem with latest master & latest 3.3, let's close this issue.
