### ISSUE TITLE
CDC - inserted some rows in the table, log table does not reflect the changes

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla#5571]
*Installation details*
Scylla version (or git commit hash):

[root@ip-10-148-40-253 centos]# scylla --version 
3.2.rc2-0.20191205.9dd714ae641 

OS (RHEL/CentOS/Ubuntu/AWS AMI):
CentOS 7

```
[root@ip-10-148-40-253 centos]# nodetool status 
Datacenter: dc1 
=============== 
Status=Up/Down 
|/ State=Normal/Leaving/Joining/Moving 
-- Address Load Tokens Owns Host ID Rack 
UN 10.148.45.86 1.48 MB 256 ? 0e32c356-a340-40bb-aa62-fbec1ca15b98 1c 
UN 10.148.40.253 1.41 MB 256 ? 9b9426bb-cae1-414f-b50c-605cb1a92139 1a 
UN 10.148.43.31 1.4 MB 256 ? e2ea7388-23cd-4e04-9550-d65011b7b72d 1b 
Note: Non-system keyspaces don’t have the same replication settings, effective ownership information is meaningless
```

```
ALTER TABLE orders WITH cdc = {‘enabled’: ‘true’, ‘preimage’: ‘true’}; 
[3:12 PM] 
cqlsh:cdc_test> desc tables

orders_scylla_cdc_log orders_scylla_cdc_desc orders 
[3:12 PM] 
cqlsh> select * from cdc_test.orders 
  ... ;

 *id* | *amount* | *first_order* 
----+--------+------------- 
 *5* |  *100* |    *True* 
 *1* |  *100* |    *True* 
 *2* |  *100* |    *False* 
 *4* |  *100* |    *False* 
 *6* |  *100* |    *False* 
 *3* |  *100* |    *True* 
[3:13 PM] 
cqlsh> select * from cdc_test.orders_scylla_cdc_log;

 *stream_id* | *time* | *batch_seq_no* | *_amount* | *_first_order* | *_id* | *operation* | *ttl* 
-----------+------+--------------+---------+--------------+-----+-----------+-----

(0 rows)

```

```
cqlsh> desc KEYSPACE cdc_test 
CREATE KEYSPACE cdc_test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
CREATE TABLE cdc_test.orders_scylla_cdc_log (
    stream_id uuid,
    time timeuuid,
    batch_seq_no int,
    "_amount" frozen<tuple<tinyint, double, bigint>>,
    "_first_order" frozen<tuple<tinyint, boolean, bigint>>,
    "_id" int,
    operation tinyint,
    ttl bigint,
    PRIMARY KEY (stream_id, time, batch_seq_no)
) WITH CLUSTERING ORDER BY (time ASC, batch_seq_no ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'CDC log for cdc_test.orders'
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 86400
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
CREATE TABLE cdc_test.orders_scylla_cdc_desc (
    node_ip inet,
    shard_id int,
    created_at timestamp,
    stream_id uuid,
    PRIMARY KEY ((node_ip, shard_id), created_at)
) WITH CLUSTERING ORDER BY (created_at ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'CDC description for cdc_test.orders'
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
CREATE TABLE cdc_test.orders (
    id int PRIMARY KEY,
    amount double,
    first_order boolean
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
cqlsh> 
```

**Comment by yksdb** [comment]
CDC works for me in 3.2.rc3-0.20191215.39b17be5620
No issues observed, seems to work as advertised on a single node.

Tried to test it in 3.2.rc2-0.20191205.9dd714ae641 (single node, in docker)
It gave me "ConfigurationException: CDC not supported by the cluster"
Does that mean it needs a cluster to work? The original issue reported by a user with a 3 node cluster.

**Comment by yksdb** [comment]
Below is a test case for 3 node cluster in docker for 3.2.rc2-0.20191205.9dd714ae641
edited /etc/scylla/scylla.yaml
Added this
experimental_features:
    - cdc

Done a rolling restart of all nodes.

[root@0062160d4e87 /]# scylla --version
3.2.rc2-0.20191205.9dd714ae641

[root@1b2b4567663e /]# nodetool status
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address     Load       Tokens       Owns    Host ID                               Rack
UN  172.17.0.5  ?          256          ?       030cdb5c-87ac-4592-9be2-e07671f7ddbd  rack1
UN  172.17.0.4  0 bytes    256          ?       fd6b227a-5f8a-4316-b95f-223663dc4007  rack1
UN  172.17.0.6  ?          256          ?       0b848b5d-2f59-4292-a188-349e795f8b6d  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless

[root@0062160d4e87 /]# cqlsh
Connected to  at 172.17.0.6:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> CREATE KEYSPACE cdc_test
   ... WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}
   ... AND durable_writes = true;
cqlsh> CREATE TABLE cdc_test.orders (
   ...     id int PRIMARY KEY,
   ...     amount double,
   ...     first_order boolean
   ... );
cqlsh> ALTER TABLE cdc_test.orders WITH cdc = {'enabled': 'true', 'preimage': 'true'};
ConfigurationException: CDC not supported by the cluster

cqlsh> insert into cdc_test.orders (id, amount, first_order) values (1, 10.32, true);
insert into cdc_test.orders (id, amount, first_order) values (4, 14.24, true);
cqlsh> insert into cdc_test.orders (id, amount, first_order) values (2, 12.00, true);
cqlsh> insert into cdc_test.orders (id, amount, first_order) values (3, 13.11, false);
cqlsh> insert into cdc_test.orders (id, amount, first_order) values (4, 14.24, true);
cqlsh> insert into cdc_test.orders (id, amount, first_order) values (5, 15.56, false);
cqlsh> insert into cdc_test.orders (id, amount, first_order) values (6, 16.63, true);
cqlsh> delete from cdc_test.orders where id = 2;
cqlsh> update cdc_test.orders set amount = 20 where id in (3,4,5);
cqlsh>
cqlsh> select * from cdc_test.orders;

 id | amount | first_order
----+--------+-------------
  5 |     20 |       False
  1 |  10.32 |        True
  4 |     20 |        True
  6 |  16.63 |        True
  3 |     20 |       False

(5 rows)
cqlsh> ALTER TABLE cdc_test.orders WITH cdc = {'enabled': 'true', 'preimage': 'true'};
ConfigurationException: CDC not supported by the cluster

Attached log from the node I worked on (oss_3.2.rc2_n3)
[oss_3.2.rc2_n3.log](https://github.com/scylladb/scylla/files/4036568/oss_3.2.rc2_n3.log)

**Comment by haaawk** [comment]
There were some issues with cluster upgrade and CDC which were fixed recently. Please try again with scylla-3.2.rc4 (which is not yet released) or master.

**Comment by yksdb** [comment]
I confirmed that it works in a 3 node cluster of scylladb/scylla:3.2.rc4
(Although scylla-jmx seems to be broken in 3.2.rc4-0.20200103.c8d5738a482, so nodetool does not work)

**Comment by slivne** [comment]
thanks @yksdb
