### ISSUE TITLE
data/cell.hh: cell::make_collection() assumes all ranges are nothrow copyable and movable

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#5575]
`cell::make_collection()` assumes all ranges are nothrow copyable and movable, however this is neither documented, nor verified. Passing ranges that can throw on copy or move will trigger an `std::terminate()` as the ranges are copied/moved around in `noexcept` functions. This will convert an `std::bad_alloc` to a crash.

**Comment by denesb** [comment]
In theory all releases having `imr` are vulnerable (3.1+), but practically only master is susceptible as the bug was uncovered by 0a453e5d30cdb6e5de2429f7a21a3ea56ad188c1.

**Comment by avikivity** [comment]
Aged out, and probably no user impact.
