### ISSUE TITLE
Change alternator keyspace to use NetworkToplogyStartegy with auto expand

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#5596]
Alternator creates a keyspace for all the global tables the user provisions, right now there is additional work that needs to be done to setup the keyspace across multiple dcs.

The keyspace should move and use {NetworkToplogyStrategy, replication_factor: 3} (scylladb/scylla#4210) that would assure that all dcs will have 3 replicas.

**Comment by nyh** [comment]
@slivne I'm not sure that when we implement the global tables feature (#5062) this proposal will remain relevant: Today, Alternator tables default to "all dcs"; But to improve DynamoDB compatibility, tables will default to just a single DC, and will need to be manually added to additional DCs. So adding a new DC to the cluster shouldn't change the replication of any of the existing tables. So it sounds like the option you are recommending isn't needed.

Also, I'm curious how the `{NetworkToplogyStrategy, replication_factor: 3}` setting you mentioned works when a new DC appears. Who/how/when will the actual data be replicated to the new data center?

**Comment by eliransin** [comment]
According to https://docs.scylladb.com/getting-started/ddl/#auto-expand-replication-factor
there is a need to run this every time a dc is added. @slivene is that what you meant?

**Comment by nyh** [comment]
Following up with what @eliransin said, it seems that the mere fact that @psarna didn't explicitly list the different DCs in the system, and just listed the RF aiming for it to be applied for *all* (currently) existing DCs, this is exactly the "Auto Expand" as explained in the document to which @eliransin pointed.
So I think we can close this issue. @slivne , feel free to reopen if we are actually missing something which you hoped to get from "auto expand"....

**Comment by slivne** [comment]
can you please paste desc schema for a keyspace/table for alternator so it will be clear what is used

**Comment by psarna** [comment]
@slivne the schema depends on how many datacenters exist in the cluster. The template looks like this:
```cql
CREATE KEYSPACE "a#{ALTERNATOR_TABLE_NAME}"
WITH replication = {
    'class': 'NetworkTopologyStrategy',
    FOR_EACH_DATACENTER_NAME{ '$datacenter_name': '3' }
}
AND durable_writes = true;
```
and here's a real life example:
```cql
CREATE KEYSPACE "a#alternator_Test_1582013217801"
WITH replication = {
    'class': 'NetworkTopologyStrategy',
    'datacenter1': '3',
    'datacenter2': '3',
    'datacenter3': '3'
}
AND durable_writes = true;
```

**Comment by slivne** [comment]
OK - and this is computed by scylla when the table in alternator is created
since you used the NetworkToplogyStretagey, replication_factor=3 (so scylla
computed this based on the existing DCs)

If so thats correct and great

**Comment by psarna** [comment]
Yes, it's computed during table creation, for all datacenters existing in that moment (based on information taken from the snitch).

**Comment by slivne** [comment]
Perfect thanks ...
