### ISSUE TITLE
Parallel compactions on a single column_family are executed in smp

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#56]
According to the following

```
    // NOTE: Compaction code runs in parallel to the rest of the system, so
    // when it's time to stop a column family, we need to prevent any new
    // compaction from starting and wait for a possible ongoing compaction.
    // That's possible by closing gate, busting semaphore and waiting for
    // _compaction_done future to resolve.
    _compaction_done = keep_doing([this] {
        // Semaphore is used here to allow at most one compaction to happen
        // at any time yet queueing pending requests.
        return _compaction_sem.wait().then([this] {

```

We are trying to limit compaction on a single column family to be one - the code supports one per shard - so on multiple shards we will have multiple compaction running in parallel.

 [shard 0] database - started compaction for column_family keyspace1/standard1
 [shard 0] compaction - Compacting [tmp/keyspace1/standard1-af590d20-3684-11e5-bd1b-000000000000/la-2-big-Data.db:level=0, tmp/keyspace1/standard1-af590d20-3684-11e5-bd1b-000000000000/la-4-big-Data.db:level=0, tmp/keyspace1/standard1-af590d20-3684-11e5-bd1b-000000000000/la-6-big-Data.db:level=0, tmp/keyspace1/standard1-af590d20-3684-11e5-bd1b-000000000000/la-8-big-Data.db:level=0, ]
 [shard 1] database - started compaction for column_family keyspace1/standard1
 [shard 1] compaction - Compacting [tmp/keyspace1/standard1-af590d20-3684-11e5-bd1b-000000000000/la-3-big-Data.db:level=0, tmp/keyspace1/standard1-af590d20-3684-11e5-bd1b-000000000000/la-5-big-Data.db:level=0, tmp/keyspace1/standard1-af590d20-3684-11e5-bd1b-000000000000/la-7-big-Data.db:level=0, tmp/keyspace1/standard1-af590d20-3684-11e5-bd1b-000000000000/la-9-big-Data.db:level=0, ]
 [shard 0] compaction - Compacted 4 sstables to [tmp/keyspace1/standard1-af590d20-3684-11e5-bd1b-000000000000/la-10-big-Data.db]. 59401280 bytes to 14850320 (~25% of original) in 0ms = 0MB/s. ~201216 total partitions merged to 50170.
 [shard 1] compaction - Compacted 4 sstables to [tmp/keyspace1/standard1-af590d20-3684-11e5-bd1b-000000000000/la-11-big-Data.db]. 58998720 bytes to 14749680 (~25% of original) in 0ms = 0MB/s. ~200192 total partitions merged to 49830.

Multiple column_families will also run in parallel, we are missing the CompactionManager functionality

**Comment by tzach** [comment]
@slivne what the impact of this issue? is it slower compaction?

**Comment by avikivity** [comment]
Behavior is correct and needed to maximize cpu utilization.
