### ISSUE TITLE
--cpuset doesn't work when hwloc library is not present

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#561]
HEAD: 6626d1a1008000bafce27d11395ed4fb8e860d7f
The issue: CPUs are chosen starting from CPU0 and forward ignoring the CPUs indices given in --cpuset parameter.

**Comment by nyh** [comment]
"--cpuset" is a Seastar option. I suggest you close this issue, and reopen on the Seastar bug tracker.

**Comment by vladzcloudius** [comment]
On 11/15/15 15:13, nyh wrote:
>
> "--cpuset" is a Seastar option. I suggest you close this issue, and 
> reopen on the Seastar bug tracker.
>

Ah, right... ;)

**Comment by vladzcloudius** [comment]
On 11/15/15 15:13, nyh wrote:
>
> "--cpuset" is a Seastar option. I suggest you close this issue, and 
> reopen on the Seastar bug tracker.
>

Done. Shlomi, could u, pls., close this one?

thanks,
vlad
