### ISSUE TITLE
Alternator: switch from single alternator keyspace, to separate keyspace per table

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5611]
This issue replaces issue #5596 and is a first step towards #5062 (global tables).
Today, we create a single "alternator" keyspace, and put all Alternator tables inside it. Among other things, this means that all Alternator tables need to live on the same set of DCs. This makes sense today, when all Alternator tables are global, but if in the future we want to be compatible with DynamoDB and allow different tables to live on different subsets of DCs (with the default being that a table only lives on a single DC - see issue #5062), we can't have multiple tables share the same keyspace - we need a separate keyspace for each table, so as to allow us later to change the DC choice of each table, separately. We should switch to a separate keyspace per table **now**, otherwise users will not be able to upgrade Scylla with existing data once #5062 is done.

Currently, when all tables are global, we should do what is described in issue #5596 so that they remain global as the cluster acquires new DCs.

But beyond that, we should already consider how we will support the full global tables vs local tables feature (#5062). This will affect how we name the keyspace, and table inside it - we need a way which will support all the possible ways that global and local tables are used and created, and keeping in mind that Scylla does not currently allow moving tables between keyspaces, and doesn't even allow renaming tables or keyspaces. This isn't trivial, and I propose the following plan:

1. The first time that a table named X is created (from DC Y), it will get keyspace X and table name X.
2. After keyspace X already exists, creating a second table with the same name "X", now in a different DC Z, will get keyspace "X_Z", table name X. (note - this can only happen after we add the capability of creating a non-global table).
3. Since both tables may remain alive and separate, reading from table X on a client in DC Z will need to inspect both keyspaces X and X_Z and find the one which has DC Z in its replication.
4. In the old technique for creating a global table, the second table called X (in keyspace X_Z) remains empty and is then joined into a global table. This is easy - we remove the keyspace X_Z and update keyspace X to include the new DC. 
5. In the new (2019) technique of creating a global table, the user asks to modify the DCs of table X without creating another empty table first. We can do this by modifying keyspace X.
6. But there's a snag - above we created an invariant that a global table X will always be in a keyspace X (and not, say, X_Z).  But theoretically (we need to test this in practice!) DynamoDB may allow two global tables with the same name... E.g., we may have one global table X on DCs Y and Z, and another one with the same name X in DCs Q and W. Only one keyspace can be called "X". If the other one will be "X_Q" for example, how would a read on DC W know to look up a keyspace called X_Q? I don't have a pretty solution for this. Maybe we should just forbid this situation, and not allow two global tables with the same name to exist? I doubt anybody really wants this confusing situation? 
7. We should mark Alternator keyspace somehow, perhaps with a common prefix (but note the name length limit issue...) or in another way, so users cannot access non-Alternator tables with the Alternator API.

**Comment by psarna** [comment]
Since the support for global tables has 3.x priority, am I correct to assume that in scope of 3.4 it's enough to just code a solution which creates a separate keyspace for each created table, without the elaborate logic for multiple tables with identical names? So that creating table "xyz" will simply result in putting it in an "alternator_xyz" namespace? That solution will not completely solve this issue, but it will solve the minimum needed for enabling #5596 for 3.4.

**Comment by nyh** [comment]
@psarna yes, I think keyspace alternator_xyz for table xyz will be fine for now (but note that this extra prefix will effect the legal table name), but please take a look on the future plan I wrote above to see if it makes sense, because we want to be forward-looking in our disk format (we don't want to need to "upgrade" tables later because we made a bad choice on how we store them).

**Comment by psarna** [comment]
@nyh I'll also investigate if we can get away with a `alternator:` prefix, with `:` being an illegal character in the identifier, similarly to our `:attrs` column. Perhaps if we make sure that Scylla boots properly without detecting `alternator:`-prefixed table names as corrupted, we won't need to delegalize any user table names CQL-side. As for having to put tighter restrictions against the name size - well, we can trim to something like 'a:` or even `:` to minimize the damage.

**Comment by nyh** [comment]
Don't worry about the name length restriction - we already can't support the full 255 because of some "stuff" we add at the end of the directory name (see comments in the code), so perhaps the "alternator_" or "alternator:" prefix won't even reduce it further, or even if it will, it doesn't matter if our limit is 240 or 230 characters. We just need to make sure we handle this restriction correctly - we don't won't to reach I/O errors when we go to create that directory (an I/O error brings down a Scylla node completely).

**Comment by nyh** [comment]
Already in 4.0. This is a non-backward-compatible change, so we should NOT backport it to a minor release in the 3.3 branch.
