### ISSUE TITLE
Trace loglevel + counters = abort

### ISSUE THREAD

**Issue by jul-stas** [scylladb/scylla#5616]
Happens on current master, e.g. on 8fde8e36007f8abcc41190f10661f6e26ab48f96
Run scylla with TRACE loglevel on `mutation_data`
```
[julex@localhost scylla]$ ./build/dev/scylla --developer-mode=true --logger-log-level mutation_data=trace
```
Then create and bump a counter:
```
cqlsh> CREATE KEYSPACE ks with replication = {'class':'SimpleStrategy', 'replication_factor': 1};
cqlsh> CREATE TABLE ks.tbl (name text PRIMARY KEY, entities counter);
cqlsh> UPDATE ks.tbl SET entities = entities + 1 where name = 'asdf';
NoHostAvailable:
```
Scylla aborts on line https://github.com/scylladb/scylla/blob/a74a82d4d245d75311c19d0d8fba404d5d75937e/service/storage_proxy.cc#L1897

**Comment by avikivity** [comment]
Backported to 3.3.

**Comment by avikivity** [comment]
Already backported; removing label.
