### ISSUE TITLE
upgrade from 3.1 to 3.2 fails on std::logic_error (Column idx_token doesn't exist in base and this view is not backing a secondary index)

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla#5621]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.2
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by tarzanek** [comment]
Upgrade fails on
```
Jan 21 14:42:19 scy-st-1-p1 scylla:  [shard 26] storage_proxy - Failed to apply mutation from 10.6.18.13#26: std::logic_error (Column idx_token doesn't exist in base and this view is not backing a secondary index)
```

**Comment by ultrabug** [comment]
FYI after downgrading scylla fails to start with

```
scylla:  [shard 0] init - Startup failed: sstables::malformed_sstable_exception (Column cdc missing in current schema in sstable
```

Fix is to copy the system table files from another node and restart

**Comment by tarzanek** [comment]
the possible cause per current data is https://github.com/scylladb/scylla/issues/4744
as per @psarna 
also this info would be good to get:
-  it would be useful to see what are the schemas
and what are the contents of local system tables on the node that fails, especially system_schema.indexes and system_schema.computed_columns (if it exists)
- full logs of the node that was upgraded upon his first boot, is the node actually booted or the boot never completes?

**Comment by tarzanek** [comment]
and this might be related to https://github.com/scylladb/scylla/issues/5288
but let's focus on this issue only
data is in https://supportscylladb.zendesk.com/agent/tickets/954

**Comment by bhalevy** [comment]
Cc @eliransin

**Comment by ultrabug** [comment]
https://patch-diff.githubusercontent.com/raw/scylladb/scylla/pull/5624

This indeed fixed my upgrade problem!

**Comment by avikivity** [comment]
@nyh backported this to 3.2, 3.3 and according to him 3.1 is not vulnerable.

**Comment by psarna** [comment]
@avikivity 3.1 is not vulnerable indeed, it uses older code which correctly checks if a schema represents an index.

**Comment by avikivity** [comment]
Removing the backport candidate label which the bot re-added (@penberg).
