### ISSUE TITLE
Crash on asset fail at schema.cc:300

### ISSUE THREAD

**Issue by mxx** [scylladb/scylla#5629]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version 2.3.1
Cluster size: 6 node
OS (Ubuntu 18.04):

Platform (physical):physical
Hardware: sockets= cores= hyperthreading= memory=
Disks: SSD

when creating a new table with indexes , scylladb crashed, all node down, and could not restart any more, the log file tell that 

schema.cc:300 assertion fail , assert(!def.id || def.id == id - column_offset(def.kind)), 

anybody has hints to bypass this fail, and make nodes restart?

the cql like this:

`CREATE TABLE IF NOT EXISTS indi_info (dist_code int,
                                                   y int,
                                                   m int,
                                                   d int,
                                                   sn int,
                                                   addr text,
                                                   name text,
                                                   group text,
                                                   cid text,
                                                   uiid uuid,
                                              PRIMARY KEY (d,cid,name));`

CREATE INDEX IF NOT EXISTS uiid ON indi_info(uiid);
CREATE INDEX IF NOT EXISTS year ON indi_info(y);
CREATE INDEX IF NOT EXISTS month ON indi_info(m);
CREATE INDEX IF NOT EXISTS name ON indi_info(name);
CREATE INDEX IF NOT EXISTS dist_code ON indi_info(dist_code);
CREATE INDEX IF NOT EXISTS group ON indi_info(group);

**here is log:**

Jan 22 19:30:14 scylla06 scylla[31812]: scylla: schema.cc:300: schema::schema(const schema::raw_schema&, std::experimental::fundamentals_v1::optional<raw_view_info>): 
Jan 22 19:30:14 scylla06 scylla[31812]: Aborting on shard 0.
Jan 22 19:30:14 scylla06 scylla[31812]: Backtrace:
Jan 22 19:30:14 scylla06 scylla[31812]:   0x00000000004497f7
Jan 22 19:30:14 scylla06 scylla[31812]:   0x0000000000367339
Jan 22 19:30:14 scylla06 scylla[31812]:   0x00000000003675f9
Jan 22 19:30:14 scylla06 scylla[31812]:   0x00000000003676b5
Jan 22 19:30:14 scylla06 scylla[31812]:   /lib/x86_64-linux-gnu/libpthread.so.0+0x000000000001288f
Jan 22 19:30:14 scylla06 scylla[31812]:   /lib/x86_64-linux-gnu/libc.so.6+0x000000000003ee96
Jan 22 19:30:14 scylla06 scylla[31812]:   /lib/x86_64-linux-gnu/libc.so.6+0x0000000000040800
Jan 22 19:30:14 scylla06 scylla[31812]:   /lib/x86_64-linux-gnu/libc.so.6+0x0000000000030399
Jan 22 19:30:14 scylla06 scylla[31812]:   /lib/x86_64-linux-gnu/libc.so.6+0x0000000000030411
Jan 22 19:30:14 scylla06 scylla[31812]:   0x00000000011b16b1
Jan 22 19:30:14 scylla06 scylla[31812]:   0x00000000011b3cfa
Jan 22 19:30:14 scylla06 scylla[31812]:   0x00000000026feb3e
Jan 22 19:30:14 scylla06 scylla[31812]:   0x0000000002705886
Jan 22 19:30:14 scylla06 scylla[31812]:   0x0000000000347966
Jan 22 19:30:14 scylla06 scylla[31812]:   0x0000000000347b21
Jan 22 19:30:14 scylla06 scylla[31812]:   0x0000000000415b47
Jan 22 19:30:14 scylla06 scylla[31812]:   0x000000000054dce7
Jan 22 19:30:14 scylla06 scylla[31812]:   0x00000000002cf61a
Jan 22 19:30:14 scylla06 scylla[31812]:   /lib/x86_64-linux-gnu/libc.so.6+0x0000000000021b96
Jan 22 19:30:14 scylla06 scylla[31812]:   0x0000000000341e99

**Comment by glommer** [comment]
Hello.

As per Scylla's policy, only two versions receive patches at any time. As of this comment (Jan 22nd 2020), that means 3.2 and 3.1 versions. 2.3 is therefore unsupported.

I am closing the ticket. Please upgrade your cluster to 3.1 or 3.2 and let us know if the issue persists

**Comment by mxx** [comment]
thank you for your infomation

**Comment by mxx** [comment]
same crash on Scylla version 3.3.0-0.20200319.7ae2cdf46c7 with build-id e1a6c0b608140610f1e783632d61f1f2c7fb932d

scylla[1546]: scylla: schema.cc:303: schema::schema(const schema::raw_schema&, std::optional<raw_view_info>): Assertion `!def.id || def.id == id - column_offset(def.kind)' failed.
Apr 17 19:08:17 scylla02 scylla[1546]: Aborting on shard 11.
Apr 17 19:08:17 scylla02 scylla[1546]: Backtrace:
Apr 17 19:08:17 scylla02 scylla[1546]:   0x0000000002a5de52
Apr 17 19:08:17 scylla02 scylla[1546]:   0x0000000002a049cb
Apr 17 19:08:17 scylla02 scylla[1546]:   0x0000000002a04cc5
Apr 17 19:08:17 scylla02 scylla[1546]:   0x0000000002a04d60
Apr 17 19:08:17 scylla02 scylla[1546]:   0x00007f00118f3b1f
Apr 17 19:08:17 scylla02 scylla[1546]:   /opt/scylladb/libreloc/libc.so.6+0x000000000003c624
Apr 17 19:08:17 scylla02 scylla[1546]:   /opt/scylladb/libreloc/libc.so.6+0x00000000000258d8
Apr 17 19:08:17 scylla02 scylla[1546]:   /opt/scylladb/libreloc/libc.so.6+0x00000000000257a8
Apr 17 19:08:17 scylla02 scylla[1546]:   /opt/scylladb/libreloc/libc.so.6+0x0000000000034a65
Apr 17 19:08:17 scylla02 scylla[1546]:   0x0000000000a444ee
Apr 17 19:08:17 scylla02 scylla[1546]:   0x0000000000a44dee
Apr 17 19:08:17 scylla02 scylla[1546]:   0x000000000170b48b
Apr 17 19:08:17 scylla02 scylla[1546]:   0x000000000170d7ad
Apr 17 19:08:17 scylla02 scylla[1546]:   0x0000000002a00c71
Apr 17 19:08:17 scylla02 scylla[1546]:   0x0000000002a00e7f
Apr 17 19:08:17 scylla02 scylla[1546]:   0x0000000002a41645
Apr 17 19:08:17 scylla02 scylla[1546]:   0x0000000002a5029c
Apr 17 19:08:17 scylla02 scylla[1546]:   0x00000000029db50d
Apr 17 19:08:17 scylla02 scylla[1546]:   /opt/scylladb/libreloc/libpthread.so.0+0x00000000000094e1
Apr 17 19:08:17 scylla02 scylla[1546]:   /opt/scylladb/libreloc/libc.so.6+0x0000000000101692
Apr 17 19:08:17 scylla02 systemd[1]: Started Process Core Dump (PID 1593/UID 0).

**Comment by denesb** [comment]
@mxx please upload a coredump, see https://docs.scylladb.com/troubleshooting/report_scylla_problem/#core-dump.

**Comment by slivne** [comment]
@mxx we would be happy to solve this if you can help and upload the coredumps, once done - comment and we will reopen.

closing the issue as its stale
