### ISSUE TITLE
Scylla 3.2.0 ships with yaml.load CVE from seastar & tools

### ISSUE THREAD

**Issue by ultrabug** [scylladb/scylla#5630]
Hi,

I hoped it was old news but it seems that the seastar tag on scylla 3.2.0 is still pointing to a revision of seastar which does not include the patch for yaml.load 

This makes 3.2.0 vulnerable along with sad pandas :(

Please merge https://github.com/scylladb/seastar/pull/720 and update seastar submodule so that 3.2 is clean?

Also, related to 3.2 release : https://github.com/scylladb/scylla-tools-java/issues/139

**Comment by penberg** [comment]
The fix to `perftune.py` is now queued to next and will be backported to 3.1 and 3.2 once it passes verification.

Thanks, @ultrabug!

**Comment by ultrabug** [comment]
Cool, cheers @penberg

**Comment by avikivity** [comment]
Backported to 3.3 (was already in 3.2).

**Comment by avikivity** [comment]
and 3.1.
