### ISSUE TITLE
Allow changing the hinted handoff configuration in the run time

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#5634]
HEAD: 6909d4db42d3e7aa78035c44c038f102108e1ca3

## Description

Allow changing the node's hinted handoff configuration in the run time, e.g. via REST API.

Today changing HH state requires a node restart which is a serious pain for big clusters.

There isn't any technical difficulty to change HH state in the run time: we simply change the HH configuration and let all outstanding hints to be stored.

Hints sending doesn't need to be touched at all - after all outstanding hints are sent out it will dry out by itself...

**Comment by slivne** [comment]
we support changing config at runtime - we have some samples in the code lets align (I think there are also nodetool specific commands for this
