### ISSUE TITLE
Filtering on counter columns doesn't work (works in Cassandra 3.0)

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5635]
A user reported on stack-overflow https://stackoverflow.com/questions/59859080/filter-condition-not-working-on-counter-columns-in-scylladb-where-it-works-in-ca:

> Filter condition not working on counter columns in ScyllaDB where it works in Cassandra 3.0
>
> I have a use case where I am using filters on counter columns in cassandra. Now I am migrating to Scylla, and I see that scylla won't support counter column filters.

**Comment by avikivity** [comment]
Backported to 4.0 (4.1+ are safe).
