### ISSUE TITLE
Alternator: use LWT also for BatchWriteItem

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5637]
After #5054 is fixed, we now use LWT for all PutItem, UpdateItem and GetItem operations. We do this even for pure writes (that do not involve a read before the write).

Well, BatchWriteItem also does pure writes - and it doesn't use LWT. For consistency, it probably should.

This should be easy to fix - we need to use storage_proxy::cas() but we know it doesn't need to read anything or check any condition because BatchWriteItem's writes are pure writes.

**Comment by slivne** [comment]
@nyh I do not see how we can have BatchWriteItem not use LWT if other writes are being done with LWT. 

All writes should follow the same rules

I am marking this as a bug for now

**Comment by nyh** [comment]
@slivne, indeed, that's the point of this issue. It should use LWT as well. I assigned myself to this issue, to fix it ASAP.

**Comment by nyh** [comment]
Already in branch 4.0, not relevant to 3.3 which didn't use LWT
