### ISSUE TITLE
Crash in transport and commit log under cassandra-stress

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#5644]
How to repeat: 

Take the latest Scylla from master, use cqlstress-lwt-example.yaml from cassandra 4.0.
`./cassandra-stress user profile=../cqlstress-lwt-example.yaml "ops(insert=1)"
`
Observe the crash:

`scylla: ./transport/messages/result_message.hh:89: virtual void cql_transport::messages::result_message::visitor_base::visit(const cql_transport::messages::result_message::bounce_to_shard&): Assertion `false' failed.
`
If scylla is run with --smp=1 then:

`scylla: db/commitlog/commitlog.cc:810: db::commitlog::segment::batch_cycle(seastar::lowres_clock::time_point)::<lambda()>::<lambda()>: Assertion `me->_flush_pos > fp' failed.`

**Comment by gleb-cloudius** [comment]
Looks the same as #5496 which was suppose to be fixed by 60a851d3a55f973e65ee71af61516f2750fe4aeb

**Comment by gleb-cloudius** [comment]
I split  #5670 for commit log issue.

**Comment by avikivity** [comment]
Already in 4.0, lwt is experimental in 3.3, not backporting.
