### ISSUE TITLE
Version 3.2 allows `udf` as a valid value of experimental_features

### ISSUE THREAD

**Issue by dekimir** [scylladb/scylla#5645]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.2
Cluster size: n/a
OS (RHEL/CentOS/Ubuntu/AWS AMI): n/a

Scylla 3.2 doesn't include the UDF feature, but its configuration code allows `--experimental-features=udf`.  We should remove UDF from `experimental_features_t`, the description of `--experimental-features` flag, and `conf/scylla.yaml`.

**Comment by bhalevy** [comment]
@espindola can you please own this?

**Comment by dekimir** [comment]
If we're going to ignore the n00b label, it makes more sense if I own this...

**Comment by dekimir** [comment]
Fixed by #5655
