### ISSUE TITLE
jepsen cassandra.batch-test/batch-bridge-bootstrap test causes 'Unable to contact any seeds!' exception

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#565]
This test periodically partitions the 5 nodes cluster into two parts where in each partition 2 nodes are mutually connected and are also connected to the third node, which is also connected to the other partition (this is a "bridge" part).
In addition, two nodes are bootstrapped about 3 minutes after  the rest of the cluster is up and active (there are about 1000 'add' operations performed at that stage). 
These two nodes are bootstrapped one after another with about a minute delay in between.

With about 70% probability we hit the above exception and as a result the bootstrapping node shuts down.

**Comment by tzach** [comment]
If a new node have no access to any seed it should shutdown.
Why is it a bug?

**Comment by vladzcloudius** [comment]
On 11/17/15 10:27, Tzach Livyatan wrote:
>
> If a new node have no access to any seed it should shutdown.
>

Because it has an access...

**Comment by tzach** [comment]
> Because it has an access...

Direct or via the bridge?
If A, B are seeds, and D and E are the new ones, they do not
![image](https://cloud.githubusercontent.com/assets/170200/11206456/f151d45c-8d17-11e5-9f65-3b972e140d64.png)

**Comment by vladzcloudius** [comment]
There is a bootleg patch from Asias that fixes this issue at dev asias/gossip/for_vald

**Comment by vladzcloudius** [comment]
On 11/17/15 10:43, Tzach Livyatan wrote:
>
>     Because it has an access...
>
> Direct or via the bridge?
>

There is no such thing as "seeing the node via bridge" in ScyllaDB - it 
sees it directly and Gossiper shadow round against the seeder passes 
just fine.

**Comment by slivne** [comment]
@vladzcloudius  did @asias patch resolve this - is it merged

**Comment by vladzcloudius** [comment]
@slivne I have no idea. Which patch are u talking about? 
In any case, I haven't run this particular test for a long time.

**Comment by slivne** [comment]
@vladzcloudius 

4 comments above a comment by vladcloudius
"There is a bootleg patch from Asias that fixes this issue at dev asias/gossip/for_vald"

did this resolve the issue or not ? is that patch merged ?

**Comment by vladzcloudius** [comment]
On 12/23/2015 03:26 PM, slivne wrote:
>
> @vladzcloudius <https://github.com/vladzcloudius>
>
> 4 comments above a comment by vladcloudius
> "There is a bootleg patch from Asias that fixes this issue at dev 
> asias/gossip/for_vald"
>
> did this resolve the issue or not ? is that patch merged ?
>

According to my comment - the branch above was fixing the issue however 
this didn't mean that it was commitable...
@asias, could u clarify what's the status of this?

**Comment by asias** [comment]
The patch in the branch is "gossip: Favor just added new node in do_gossip_to_live_member". It is merged:

```
commit 3b52033371408a347de72fc23ae8907864512695
Author: Asias He <asias@scylladb.com>
Date:   Tue Nov 17 14:44:07 2015 +0800

    gossip: Favor newly added node in do_gossip_to_live_member

    When a new node joins a cluster, it will starts a gossip round with seed
    node. However, within this round, the seed node will not tell the new
    node anything it knows about other nodes in the cluster, because the
    digest in the gossip SYN message contains only the new node itself and
    no other nodes. The seed node will pick randomly from the live nodes,
    including the newly added node in do_gossip_to_live_member to start a
    gossip round. If the new node is "lucky", seed node will talk to it very
    soon and tells all the information it knows about the cluster, thus the
    new node will mark the seed node alive and think it has seen the seed
    node. If there considerably large number of live nodes, it might take a
    long time before the seed node pick the new node and talk to it.

    In bootstrap code, storage_service::bootstrap checks if we see any nodes
    after sleep of RING_DELAY milliseconds and throw "Unable to contact any
    seeds!" if not, thus the node will fail to bootstrap.

    To help the seed node talk to new node faster, we favor new node in
    do_gossip_to_live_member.
```

**Comment by vladzcloudius** [comment]
On 12/23/2015 03:35 PM, Asias He wrote:
>
> The patch in the branch is "gossip: Favor just added new node in 
> do_gossip_to_live_member". It is merged:
>
> |commit 3b52033371408a347de72fc23ae8907864512695 Author: Asias He 
> <asias@scylladb.com> Date: Tue Nov 17 14:44:07 2015 +0800 gossip: 
> Favor newly added node in do_gossip_to_live_member When a new node 
> joins a cluster, it will starts a gossip round with seed node. 
> However, within this round, the seed node will not tell the new node 
> anything it knows about other nodes in the cluster, because the digest 
> in the gossip SYN message contains only the new node itself and no 
> other nodes. The seed node will pick randomly from the live nodes, 
> including the newly added node in do_gossip_to_live_member to start a 
> gossip round. If the new node is "lucky", seed node will talk to it 
> very soon and tells all the information it knows about the cluster, 
> thus the new node will mark the seed node alive and think it has seen 
> the seed node. If there considerably large number of live nodes, it 
> might take a long time before the seed node pick the new node and talk 
> to it. In bootstrap code, storage_service::bootstrap checks if we see 
> any nodes after sleep of RING_DELAY milliseconds and throw "Unable to 
> contact any seeds!" if not, thus the node will fail to bootstrap. To 
> help the seed node talk to new node faster, we favor new node in 
> do_gossip_to_live_member.|

Looks like the issue may be closed. ;)
