### ISSUE TITLE
alternator: use LWT timestamp, not current timestamp, in mutations

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5653]
In the current code, the code which generates new mutations for write operations, e.g., `make_item_mutation()` called from `put_item_operation::apply()`, uses the current timestamp (`api::new_timestamp()`) for this mutation.

However, @kostja and @gleb-cloudius explained on the mailing list that this is not the right thing to do with LWT, because different coordinators may have slightly different clocks but an LWT write needs to unconditionally take effect. So instead of this-node's-current-timestamp, the LWT `cas()` function passes our `rmw_operation::apply()` a `api::timestamp_type ts`, which **we currently ignore**. We shouldn't ignore it... We should use this timestamp in the mutation we build. LWT guarantees that this timestamp is monotonic globally, even if coordinator clocks aren't synchronized, so the new mutation we apply doesn't get overridden by older data.

Beyond fixing this, we should find a way to write a regression test for this issue that would demonstrate the bug in the existing code. Such a test might need to involve several Scylla processes where the clock of one is (artificially) shifted. This should be fairly easy to simulate.

**Comment by psarna** [comment]
note: some references of `alternator: use LWT timestamp - in BatchWriteItems too` that are allegedly pushed by me appeared here, but they're just the result of a rebase of another series, please disregard them.

**Comment by nyh** [comment]
Already in branch 4.0, not needed in 3.3 which didn't use LWT.
