### ISSUE TITLE
multishard_mutation_query_test generates invalid xml

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#5654]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

```
$ xmllint testlog/dev/xml/multishard_mutation_query_test.1.xunit.xml 
testlog/dev/xml/multishard_mutation_query_test.1.xunit.xml:1: parser error : Opening and ending tag mismatch: TestCase line 1 and unparseable
/multishard_mutation_query_test.cc" line="806"><![CDATA[ has passed]]></Info></>
                                                                               ^
testlog/dev/xml/multishard_mutation_query_test.1.xunit.xml:1: parser error : Opening and ending tag mismatch: TestSuite line 1 and unparseable
t/boost/multishard_mutation_query_test.cc" line="814"><![CDATA[ == ]]></Info></>
                                                                               ^
testlog/dev/xml/multishard_mutation_query_test.1.xunit.xml:1: parser error : Opening and ending tag mismatch: TestLog line 1 and unparseable
boost/multishard_mutation_query_test.cc" line="814"><![CDATA[check ]]></Info></>
                                                                               ^
testlog/dev/xml/multishard_mutation_query_test.1.xunit.xml:1: parser error : Extra content at the end of the document
boost/multishard_mutation_query_test.cc" line="814"><![CDATA[check ]]></Info></>
                                                                              ^
```

**Comment by denesb** [comment]
I suspect this will be due to multiple shards using `BOOST_` macros.

**Comment by avikivity** [comment]
Ah, they're unprotected? Boost doesn't support multithreaded tests?

Semi-related, our tests generate huge log files which are then archived, analyzed, and moved around, but no one ever looks at them. We should look at reducing the output.

**Comment by denesb** [comment]
I'm not 100% sure. I do know `BOOST_TEST_MESSAGE` produces unintelligible interspersed output when invoked on multiple shards.

**Comment by avikivity** [comment]
According to google, it is not thread safe.

http://boost.2283326.n4.nabble.com/BoostTest-Is-BOOST-MESSAGE-is-not-thread-safe-td2580110.html

**Comment by denesb** [comment]
Looks like I'll have to forgo using `BOOST_TEST_` macros in the worker shards. Great.
I seem to remember hitting multi-threading related problems when writing the test.

**Comment by kbr-** [comment]
Same issue:
https://github.com/scylladb/scylla/issues/4774

**Comment by avikivity** [comment]
Closing as duplicate of #4774.
