### ISSUE TITLE
Scylla API delete snapshot for a table

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla#5658]
In backup when uploading a huge number of tables we want to release snapshot hard links as soon as possible i.e. when we know that snapshot for a given table is safely stored.

I think `DELETE /storage_service/snapshots` could get a `cf` parameter similar to `POST` endpoint.

**Comment by mmatczuk** [comment]
Which version this will be available in?

**Comment by avikivity** [comment]
@mmatczuk 4.0.

**Comment by avikivity** [comment]
Since this is a feature, not backporting.
