### ISSUE TITLE
cql_server - exception while processing connection: std::system_error (error system:32, sendmsg: Broken pipe)

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#5661]
Installation details
Scylla version (or git commit hash): 3.3 - Scylla version 666.development-0.20200123.e1b22b6a4c5 with build-id 98f8288b4a56c70373b863b3f012bd7e6a4a45dd
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0e0bc3eb9e39a481d

scenario: 50GB longevity - got multiple of this error for thousands of times.
```
[jenkins@aws-scylla-qa-builder latest]$ grep 'sendmsg: Broken pipe' sct.log | head -n 10
< t:2020-01-26 19:51:25,787 f:cluster.py      l:1369 c:sdcm.cluster         p:DEBUG > 2020-01-26T19:51:21+00:00  longevity-tls-50gb-4d-master-db-node-aaa5420a-6 !INFO    | scylla: [shard 2] cql_server - exception while processing connection: std::system_error (error system:32, sendmsg: Broken pipe)
< t:2020-01-26 19:55:40,181 f:cluster.py      l:1369 c:sdcm.cluster         p:DEBUG > 2020-01-26T19:55:35+00:00  longevity-tls-50gb-4d-master-db-node-aaa5420a-5 !INFO    | scylla: [shard 2] cql_server - exception while processing connection: std::system_error (error system:32, sendmsg: Broken pipe)
< t:2020-01-26 19:55:40,182 f:cluster.py      l:1369 c:sdcm.cluster         p:DEBUG > 2020-01-26T19:55:35+00:00  longevity-tls-50gb-4d-master-db-node-aaa5420a-5 !INFO    | scylla: [shard 5] cql_server - exception while processing connection: std::system_error (error system:32, sendmsg: Broken pipe)
< t:2020-01-26 19:55:40,183 f:cluster.py      l:1369 c:sdcm.cluster         p:DEBUG > 2020-01-26T19:55:35+00:00  longevity-tls-50gb-4d-master-db-node-aaa5420a-5 !INFO    | scylla: [shard 4] cql_server - exception while processing connection: std::system_error (error system:32, sendmsg: Broken pipe)
< t:2020-01-26 19:55:40,186 f:cluster.py      l:1369 c:sdcm.cluster         p:DEBUG > 2020-01-26T19:55:35+00:00  longevity-tls-50gb-4d-master-db-node-aaa5420a-5 !INFO    | scylla: [shard 12] cql_server - exception while processing connection: std::system_error (error system:32, sendmsg: Broken pipe)
< t:2020-01-26 20:12:10,224 f:cluster.py      l:1369 c:sdcm.cluster         p:DEBUG > 2020-01-26T20:12:02+00:00  longevity-tls-50gb-4d-master-db-node-aaa5420a-1 !INFO    | scylla: [shard 12] cql_server - exception while processing connection: std::system_error (error system:32, sendmsg: Broken pipe)
< t:2020-01-26 20:12:10,391 f:cluster.py      l:1369 c:sdcm.cluster         p:DEBUG > 2020-01-26T20:12:02+00:00  longevity-tls-50gb-4d-master-db-node-aaa5420a-2 !INFO    | scylla: [shard 6] cql_server - exception while processing connection: std::system_error (error system:32, sendmsg: Broken pipe)
< t:2020-01-26 20:12:11,114 f:cluster.py      l:1369 c:sdcm.cluster         p:DEBUG > 2020-01-26T20:12:02+00:00  longevity-tls-50gb-4d-master-db-node-aaa5420a-3 !INFO    | scylla: [shard 6] cql_server - exception while processing connection: std::system_error (error system:32, sendmsg: Broken pipe)
< t:2020-01-26 20:12:12,036 f:cluster.py      l:1369 c:sdcm.cluster         p:DEBUG > 2020-01-26T20:12:02+00:00  longevity-tls-50gb-4d-master-db-node-aaa5420a-4 !INFO    | scylla: [shard 6] cql_server - exception while processing connection: std::system_error (error system:32, sendmsg: Broken pipe)
< t:2020-01-26 20:12:13,339 f:cluster.py      l:1369 c:sdcm.cluster         p:DEBUG > 2020-01-26T20:12:02+00:00  longevity-tls-50gb-4d-master-db-node-aaa5420a-6 !INFO    | scylla: [shard 6] cql_server - exception while processing connection: std::system_error (error system:32, sendmsg: Broken pipe)

```
```
$ grep 'sendmsg: Broken pipe' sct.log -c
55872
```
logs:
+-------------------------------------------------------------------------------------------------------------------------------------------------+
| Collected logs by test-id: aaa5420a-1826-4dea-aeeb-2705e870858e Directory: /home/yarongilor/sct-results/20200127-111038-078407/collected_logs |
+--------------+----------------------------------------------------------------------------------------------------------------------------------+
| Cluster set | Link |
+--------------+----------------------------------------------------------------------------------------------------------------------------------+
| db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/aaa5420a-1826-4dea-aeeb-2705e870858e/20200127_111035/db-cluster-aaa5420a.zip |
| monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/aaa5420a-1826-4dea-aeeb-2705e870858e/20200127_111035/monitor-set-aaa5420a.zip |
| loader-set | https://cloudius-jenkins-test.s3.amazonaws.com/aaa5420a-1826-4dea-aeeb-2705e870858e/20200127_111035/loader-set-aaa5420a.zip |
| sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/aaa5420a-1826-4dea-aeeb-2705e870858e/20200127_111035/sct-runner-aaa5420a.zip |
+--------------+----------------------------------------------------------------------------------------------------------------------------------+

**Comment by roydahan** [comment]
This bug doesn't have enough details, please elaborate.

**Comment by gleb-cloudius** [comment]
This error started to be printed recently when a client closes connection.

**Comment by raphaelsc** [comment]
On Wed, Jan 29, 2020 at 8:39 AM Gleb Natapov <notifications@github.com>
wrote:

> This error started to be printed recently when a client closes connection.
>

bumped into this too, shouldn't we make the message less scary to users?

**Comment by yarongilor** [comment]
reproduced in another longevity - longevity-large-partition-200k-pks-4days.
details:
Installation details
Scylla version (or git commit hash): 3.3 - Scylla version 666.development-0.20200123.e1b22b6a4c5 with build-id 98f8288b4a56c70373b863b3f012bd7e6a4a45dd
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0e0bc3eb9e39a481d eu-west1

scenario: 
longevity-large-partition-200k-pks-4days at 2020-02-03 13:03:44.

Test: longevity_large_partition_test.LargePartitionLongevityTest.test_large_partition_longevity
Test-id: dd772ace-bb57-4b43-a737-cfae50b78267
Test details
Start time: 2020-02-03 13:03:44
End time: 2020-02-05 22:11:45
Build URL: link
Test run by User: yarongilor
System under test
Scylla version: (ami-0dbad0053cd68fcfe)
Instance type: i3en.3xlarge
Number of scylladb nodes: 5

Nemesis Details
Running nemesis: ChaosMonkey

Name | Count | Runs | Failures
-- | -- | -- | --
ValidateHintedHandoffShortDowntime | 1 | 0 | 1
RestartThenRepairNode | 1 | 1 | 0
MultipleHardRebootNode | 1 | 1 | 0

Hydra commands:
Restore Monitor Stack command: $ hydra investigate show-monitor dd772ace-bb57-4b43-a737-cfae50b78267
Show all stored logs command: $ hydra investigate show-logs dd772ace-bb57-4b43-a737-cfae50b78267
Running instances
```
Name	Ip address	Current State	Cloud	Region
longevity-large-partitions-200k-pks-db-node-dd772ace-4	52.50.10.159	running	aws	eu-west-1
longevity-large-partitions-200k-pks-db-node-dd772ace-1	52.209.193.53	running	aws	eu-west-1
longevity-large-partitions-200k-pks-db-node-dd772ace-3	34.240.52.33	running	aws	eu-west-1
longevity-large-partitions-200k-pks-monitor-node-dd772ace-1	63.33.206.104	running	aws	eu-west-1
longevity-large-partitions-200k-pks-db-node-dd772ace-7	34.242.62.175	running	aws	eu-west-1
longevity-large-partitions-200k-pks-db-node-dd772ace-8	54.76.132.190	running	aws	eu-west-1
```
![200pk_large_partitions](https://user-images.githubusercontent.com/9427929/74151343-a769b100-4c14-11ea-92f0-1f97e061ca3e.png)




scenario failures:
```
2020-02-04 01:32:24.000: (DatabaseLogEvent Severity.CRITICAL): type=DATABASE_ERROR regex=Exception  line_number=77420 node=Node longevity-large-partitions-200k-pks-db-node-dd772ace-4 [34.242.84.132 | 10.0.58.160] (seed: False)
2020-02-04T01:32:24+00:00  longevity-large-partitions-200k-pks-db-node-dd772ace-4 !INFO    | scylla: [shard 0] cql_server - exception while processing connection: std::system_error (error system:32, sendmsg: Broken pipe)
```
logs:
+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                 Log links for testrun with test id dd772ace-bb57-4b43-a737-cfae50b78267                                                                                                  |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                                                                                                                                     |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 20200205_220127 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/dd772ace-bb57-4b43-a737-cfae50b78267/20200205_220127/grafana-screenshot-overview-20200205_220216-longevity-large-partitions-200k-pks-monitor-node-dd772ace-1.png                          |
| 20200205_220127 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/dd772ace-bb57-4b43-a737-cfae50b78267/20200205_220127/grafana-screenshot-scylla-per-server-metrics-nemesis-20200205_220137-longevity-large-partitions-200k-pks-monitor-node-dd772ace-1.png |
| 20200205_220800 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/dd772ace-bb57-4b43-a737-cfae50b78267/20200205_220800/grafana-screenshot-overview-20200205_220844-longevity-large-partitions-200k-pks-monitor-node-dd772ace-1.png                          |
| 20200205_220800 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/dd772ace-bb57-4b43-a737-cfae50b78267/20200205_220800/grafana-screenshot-scylla-per-server-metrics-nemesis-20200205_220802-longevity-large-partitions-200k-pks-monitor-node-dd772ace-1.png |
| 20200205_221153 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/dd772ace-bb57-4b43-a737-cfae50b78267/20200205_221153/db-cluster-dd772ace.zip                                                                                                              |
| 20200205_221153 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/dd772ace-bb57-4b43-a737-cfae50b78267/20200205_221153/loader-set-dd772ace.zip                                                                                                              |
| 20200205_221153 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/dd772ace-bb57-4b43-a737-cfae50b78267/20200205_221153/monitor-set-dd772ace.zip                                                                                                             |
| 20200205_221153 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/dd772ace-bb57-4b43-a737-cfae50b78267/20200205_221153/sct-runner-dd772ace.zip                                                                                                              |
+-----------------+-------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Comment by slivne** [comment]
@gleb-cloudius with regards to this https://github.com/scylladb/scylla/issues/5661#issuecomment-579716896 is this the expected behavior, is it a race condition between closing the connection and response sent to the client ?

Even if its a race condition - if we were able to avoid the "scary log" it would be better to remove it now as well.

**Comment by slivne** [comment]
@gleb-cloudius ping

**Comment by gleb-cloudius** [comment]
@slivne I am not an expert here and did not looks the code too much, I just reported that those errors are started to appear recently (in metoo fashion) after some changes to cql server that were supposed to be a clienup.

**Comment by gnumoreno** [comment]
Any chance this issue with sstableloader on stackoverflow is related to this issue?

`https://stackoverflow.com/questions/61361140/scylla-sstableloader-giving-error-on-copying-sstables-from-cassandra-to-scylla`

**Comment by avikivity** [comment]
@gleb-cloudius please investigate if you have a reproducer.

It can be that exception handling change and we now report an exception during normal disconnects rather than swallow it, or it can be that we don't handle a connection correctly and so the driver closes it unexpectedly.

**Comment by gleb-cloudius** [comment]
On Thu, Jun 11, 2020 at 02:13:04AM -0700, Avi Kivity wrote:
> @gleb-cloudius please investigate if you have a reproducer.
> 
Avi, anyone has a reproducer. It happens every time a client is stopped
abruptly. Run c-s, ^C, get the error.

> It can be that exception handling change and we now report an exception during normal disconnects rather than swallow it, or it can be that we don't handle a connection correctly and so the driver closes it unexpectedly.
> 
Most probably the former.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
27dfda0b9edcb76bb787752af51d22f2fb63767a promoted the logging from debug to info level.

**Comment by avikivity** [comment]
So let's demote it back. Better, let's demote just this exception, not others.

**Comment by avikivity** [comment]
Backported to 3.3, 4.0, 4.1.
