### ISSUE TITLE
Commit logs fills up whole disk space

### ISSUE THREAD

**Issue by bublikOff** [scylladb/scylla#5663]
Unfortunately I was not lucky enough to find the answer for my problem
The problem is that from time to time Ive to remove node from cluster, cleanup any data from old instance and create a new one to clean up growing commit logs size.
The whole DB size is only 6.5GB. Commit logs are growing its size until it fills up the whole disk space. 
Any ideas what it could be and how to fix this problem? Any ideas how to clean up commit logs from time to time?

-----------------------
Scylla version: 3.2 (docker container)
Cluster size: 4 nodes
OS: CoreOS

**Comment by avikivity** [comment]
What is your memory size and disk size?

**Comment by bublikOff** [comment]
There are 2 servers. Each server hosts 2 scylla nodes and has 32 GB RAM. 
1) The first server has 500 GB SSD drive. For the moment it has about 140 GB of free space. Commit logs size are Node1 - 6560 MB, Node2 - 8600MB
2) The second server 250 GB SSD drive. For the moment it has about 30 GB of free space. Commit logs size are Node3 - 6720 MB, Node4 - 7200MB

**Comment by bublikOff** [comment]
Any thoughts? The situation with this issue is a bit annoying. Originaly cluster was build on DataStax Cassandra. Then we have moved to ScyllaDB and there was no problems. Later we have made software updates and moved from CentOS to CoreOS. And of course we have installed latest stable version of ScyllaDB and for already more than a month we have this problem.

**Comment by slivne** [comment]
Its not clear why commitlogs fill up your disk, commitlogs should be cleared when data is flushed from memtables to disk as sstables - so its not expected.

can you try and run a nodetool flush and see if this helps.

Are those maybe hints being accumulated ?

**Comment by slivne** [comment]
@bublikOff we would like to try and help - if you can provide additional information it would be appreciated.

**Comment by slivne** [comment]
@bublikOff I am closing this issue as its stale for ~30 days - if there is additional info please post and we will reopen and try to resolve
