### ISSUE TITLE
alternator: rethink smp_service_group used to bounce LWT requests between shards

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5664]
When Alternator does LWT requests (`storage_proxy::cas()`) it needs to bounce them first to the right shard. The `invoke_on()` method has a smp_service_group, and we currently just used `default_smp_service_group()` - in four different places in `alternator/executor.cc` (four types of requests which use LWT in their implementation - PutItem, UpdateItem, DeleteItem and BatchWriteItems).

But if I understand correctly we should be using a different smp_service_group, not the default one. @gleb-cloudius can you perhaps explain if, and why, it is important to do that?

**Comment by slivne** [comment]
@gleb-cloudius ping

**Comment by gleb-cloudius** [comment]
If many shards handle a lot of requests targeting one single shard that single shard can be overwhelmed by a lot of work and OOM. Reasonably limiting service group will prevent this from happening.

**Comment by nyh** [comment]
@gleb-cloudius, looking at the CQL LWT code, I see you use cql_server::connection::process_on_shard() to bounce requests that arrived at the wrong shard, and this function uses **bounce_request_smp_service_group** which appears to be set to **default_smp_service_group** as far as I can tell unless overridden - but I don't see what can override it?

If this setting is considered correct, the places I used `default_smp_service_group()` in Alternator (when bouncing a request to a different shard because it uses LWT) should be correct as well, no?

According to a comment in smp.hh, this default group "does not impose any limits on concurrency in the target shard. This makes is deadlock-safe, but can consume unbounded resources". Do we consider this a problem in LWT and/or Alternator (theoretically someone might bombard the server with requests to the same partition and all of them get bounced to the same shard)?

**Comment by slivne** [comment]
@nyh / @gleb-cloudius lets fix this if its needs to be fixed.

**Comment by slivne** [comment]
@nyh ping

**Comment by nyh** [comment]
@slivne I sent a patch for this, waiting on the list for @psarna and/or @gleb-cloudius to review ("alternator: use separate smp_service_group for bouncing requests").

**Comment by nyh** [comment]
Already in branch 4.0, not relevant for 3.3 where Alternator did not yet use LWT.
