### ISSUE TITLE
Scylla will crash with `Assertion me->_flush_pos > fp failed.` during mixed lwt and non lwt workload

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#5670]
*Installation details*
Scylla version (or git commit hash): b06b34478eda94bd8072d0bbf3cfa514168c63b2

**Comment by avikivity** [comment]
Backported to 3.3. Will consider for 3.2 after more mileage.

**Comment by avikivity** [comment]
Aged out.
