### ISSUE TITLE
terminate called recursively

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5672]
Seen in https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/236/artifact/logs-release.2/1580252983159_materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_low_to_half_test/node1.log
scylla version: 3.1.3-0.20200128.b0d122f9c

```
INFO  2020-01-28 23:09:35,943 [shard 0] init - Scylla version 3.1.3-0.20200128.b0d122f9c shutdown complete.
terminate called recursively
terminate called after throwing an instance of 'std::system_error'
Could not initialize seastar:   what():  : Resource temporarily unavailableAborting on shard 0.
Backtrace:
  0x00000000041db2f2
  0x00000000040c8845
  0x00000000040c8b45
  0x00000000040c8bf3
  0x00007f9d2f88f02f
  /jenkins/workspace/scylla-3.1/dtest-release/scylla/build/release/dynamic_libs/libc.so.6+0x000000000003853e
  /jenkins/workspace/scylla-3.1/dtest-release/scylla/build/release/dynamic_libs/libc.so.6+0x0000000000022894
  /jenkins/workspace/scylla-3.1/dtest-release/scylla/build/release/dynamic_libs/libstdc++.so.6+0x00000000000995e9
  /jenkins/workspace/scylla-3.1/dtest-release/scylla/build/release/dynamic_libs/libstdc++.so.6+0x000000000009738b
  /jenkins/workspace/scylla-3.1/dtest-release/scylla/build/release/dynamic_libs/libstdc++.so.6+0x0000000000096398
  /jenkins/workspace/scylla-3.1/dtest-release/scylla/build/release/dynamic_libs/libstdc++.so.6+0x0000000000096d57
  0x00007f9d2f3332b2
  0x00007f9d2f333bcc
  0x00000000007b2512
  0x000000000409401d
  /jenkins/workspace/scylla-3.1/dtest-release/scylla/build/release/dynamic_libs/libpthread.so.0+0x000000000000858d
  /jenkins/workspace/scylla-3.1/dtest-release/scylla/build/release/dynamic_libs/libc.so.6+0x00000000000fd6a2

std::system_error (error system:
```

core [here](https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/236/artifact/logs-release.2/1580252983159_materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_low_to_half_test/node1-reactor-20.26235.1580252982.core.gz)
binary [here](https://jenkins.scylladb.com/view/scylla-3.1/job/scylla-3.1/job/dtest-release/236/artifact/logs-release.2/scylla)

**Comment by bhalevy** [comment]
@xemul please look into this issue.
It looks there's something fishy going on with shutdown...

I just hit another possibly similar issue when running a dtest (`secondary_indexes_test.TestSecondaryIndexes.test_insert_data_after_recreating_cf`) locally
with bhalevy/scylla@606db0d412

[node4.log](https://github.com/scylladb/scylla/files/4134570/system.log):
```
INFO  2020-01-30 16:37:21,684 [shard 0] gossip - My status = NORMAL
INFO  2020-01-30 16:37:21,684 [shard 0] gossip - Announcing shutdown
INFO  2020-01-30 16:37:21,685 [shard 0] storage_service - Node 127.0.15.4 state jump to normal
INFO  2020-01-30 16:37:22,246 [shard 0] gossip - InetAddress 127.0.15.3 is now DOWN, status = shutdown
ERROR 2020-01-30 16:37:22,252 [shard 0] init - Unexpected error shutting down local storage: std::invalid_argument (Not an IPv4 address)
terminate called after throwing an instance of 'std::invalid_argument'
  what():  Not an IPv4 address
Aborting on shard 0.
Backtrace:
  0x0000000002a94c02
  0x0000000002a3b2bb
  0x0000000002a3b5b5
  0x0000000002a3b650
  0x00007f771f83ab1f
  /lib64/libc.so.6+0x000000000003c624
  /lib64/libc.so.6+0x00000000000258d8
  /lib64/libstdc++.so.6+0x000000000009e6b5
  /lib64/libstdc++.so.6+0x00000000000aa86b
  /lib64/libstdc++.so.6+0x00000000000a9878
  /lib64/libstdc++.so.6+0x00000000000aa223
  0x00007f771efa3c62
  0x00007f771efa454d
  0x000000000042752a
  0x0000000000792703
  0x0000000000793a76
  0x00000000007776cc
```

```
$ addr2line -Cfpie ~/dev/scylla/build/release/scylla 
  0x0000000002a94c02
  0x0000000002a3b2bb
  0x0000000002a3b5b5
  0x0000000002a3b650
  0x00007f771f83ab1f
  /lib64/libc.so.6+0x000000000003c624
  /lib64/libc.so.6+0x00000000000258d8
  /lib64/libstdc++.so.6+0x000000000009e6b5
  /lib64/libstdc++.so.6+0x00000000000aa86b
  /lib64/libstdc++.so.6+0x00000000000a9878
  /lib64/libstdc++.so.6+0x00000000000aa223
  0x00007f771efa3c62
  0x00007f771efa454d
  0x000000000042752a
  0x0000000000792703
  0x0000000000793a76
  0x00000000007776cc
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /local/home/bhalevy/dev/scylla/seastar/include/seastar/util/backtrace.hh:56
seastar::backtrace_buffer::append_backtrace() at /local/home/bhalevy/dev/scylla/seastar/src/core/reactor.cc:722
 (inlined by) print_with_backtrace at /local/home/bhalevy/dev/scylla/seastar/src/core/reactor.cc:743
seastar::print_with_backtrace(char const*) at /local/home/bhalevy/dev/scylla/seastar/src/core/reactor.cc:750
seastar::install_oneshot_signal_handler<6, &seastar::sigabrt_action>()::{lambda(int, siginfo_t*, void*)#1}::_FUN(int, siginfo_t*, void*) at /local/home/bhalevy/dev/scylla/seastar/src/core/reactor.cc:3433
 (inlined by) operator() at /local/home/bhalevy/dev/scylla/seastar/src/core/reactor.cc:3415
 (inlined by) _FUN at /local/home/bhalevy/dev/scylla/seastar/src/core/reactor.cc:3411
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
?? ??:0
defer_verbose_shutdown<main::{lambda()#2}::operator()() const::{lambda()#2}::operator()() const::{lambda()#41}>(char const*, main::{lambda()#2}::operator()() const::{lambda()#2}::operator()() const::{lambda()#41}&&)::{lambda()#1}::operator()() [clone .cold] at /local/home/bhalevy/dev/scylla/main.cc:401
main::{lambda()#2}::operator()() const::{lambda()#2}::operator()() const at /local/home/bhalevy/dev/scylla/seastar/include/seastar/util/defer.hh:44
 (inlined by) operator() at /local/home/bhalevy/dev/scylla/main.cc:1107
_ZN7seastar20noncopyable_functionIFvvEE17direct_vtable_forIZZNS_5asyncIZZ4mainENKUlvE0_clEvEUlvE0_JEEENS_8futurizeINSt9result_ofIFNSt5decayIT_E4typeEDpNS9_IT0_E4typeEEE4typeEE4typeENS_17thread_attributesEOSA_DpOSD_ENUlRZNS4_IS6_JEEESL_SM_SN_SP_E4workE_clESR_EUlvE_E4callEPKS2_ at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/apply.hh:36
 (inlined by) apply<main(int, char**)::<lambda()>::<lambda()> > at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/apply.hh:44
 (inlined by) apply<main(int, char**)::<lambda()>::<lambda()> > at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/future.hh:1565
 (inlined by) operator() at /local/home/bhalevy/dev/scylla/seastar/include/seastar/core/thread.hh:252
 (inlined by) call at /local/home/bhalevy/dev/scylla/seastar/include/seastar/util/noncopyable_function.hh:101
seastar::noncopyable_function<void ()>::operator()() const at /local/home/bhalevy/dev/scylla/seastar/include/seastar/util/noncopyable_function.hh:184
 (inlined by) seastar::thread_context::main() at /local/home/bhalevy/dev/scylla/seastar/src/core/thread.cc:286
```

So this comes from:
https://github.com/bhalevy/scylla/blob/606db0d412473f88886feca5876b1f6038be6b69/main.cc#L1105-L1107

Uploaded core dump to http://scratch.scylladb.com/issues/5672/20200130/scylla.2630836.1580395042.core.gz
and binary: http://scratch.scylladb.com/issues/5672/20200130/scylla.gz

**Comment by xemul** [comment]
@bhalevy , these two look different. The first issue is here:

    Could not initialize seastar:   what():  : Resource temporarily unavailableAborting on shard 0.

this happens eary in app_template::run_deprecated() in case smp::configure fails. While the 2nd one is about "Not an IPv4 address". What makes you think they are related?

**Comment by xemul** [comment]
For the record. Logs from 2nd issue:

    INFO  2020-01-30 16:37:19,130 [shard 0] init - Shutting down local storage
    INFO  2020-01-30 16:37:19,130 [shard 0] storage_service - Drain on shutdown: starts
    INFO  2020-01-30 16:37:19,130 [shard 0] storage_service - Stop transport: starts
    INFO  2020-01-30 16:37:21,600 [shard 0] storage_service - Thrift server stopped
    INFO  2020-01-30 16:37:21,684 [shard 0] storage_service - CQL server stopped
    INFO  2020-01-30 16:37:21,684 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
    INFO  2020-01-30 16:37:21,684 [shard 0] gossip - My status = NORMAL
    INFO  2020-01-30 16:37:21,684 [shard 0] gossip - Announcing shutdown
    INFO  2020-01-30 16:37:21,685 [shard 0] storage_service - Node 127.0.15.4 state jump to normal
    INFO  2020-01-30 16:37:22,246 [shard 0] gossip - InetAddress 127.0.15.3 is now DOWN, status = shutdown
    ERROR 2020-01-30 16:37:22,252 [shard 0] init - Unexpected error shutting down local storage: std::invalid_argument (Not an IPv4 address)
    terminate called after throwing an instance of 'std::invalid_argument'
      what():  Not an IPv4 address

**Comment by xemul** [comment]
Scylla build b0d122f9 needs seastar cfc082207cfe8cb832b300fde2a47a5dd1bc8073 which cannot be found in scylladb/seastar repo. What kind of seatar is it? @bhalevy

**Comment by avikivity** [comment]
It's a scylla-seastar. Add a remote in seastar/ for https://github.com/scylladb/scylla-seastar.git and fetch it, then git submodule update --recursive in the parent directory should work.

**Comment by xemul** [comment]
Not to forget. According to @bhalevy , the 1st calltrace came to us after upgrading to newer Fedora.

**Comment by avikivity** [comment]
Yes, new fedora -> new docker -> 1024 pids limit in the cgroup -> resource temporarily unavailable when creating a thread. We can file that under environment problems.

**Comment by avikivity** [comment]
(was fixed by configuring docker with a ulimited pids)

**Comment by bhalevy** [comment]
> (was fixed by configuring docker with a ulimited pids)

Closing this issue then.
