### ISSUE TITLE
nodetool rebuild fails with no data: 

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla#5678]
*Installation details*
Scylla version (or git commit hash): 3.2.1-e3e301906

When running `nodetool rebuild` we see a lot of empty `[]` in the log and nothing happens

Example:
```
Jan 30 01:49:15 scy-st-1-p1 scylla:  [shard 0] range_streamer - Rebuild with [] for keyspace=bic started, nodes_to_stream=0

```

**Comment by dyasny** [comment]
@glommer @vladzcloudius @eyalgutkind this is the last of the 3.2.1-gentoo issues encountered today

**Comment by eliransin** [comment]
@dyasny can we have some more context please? What is the background for this issue? is that happen in conjunction with #4080 style messages?

**Comment by dyasny** [comment]
@eliransin yes, exactly. These two bugs are part of a series

**Comment by slivne** [comment]
@dyasny where is the log from this node ?

If there is no log please close the issue - I am not accepting issues with a single error line

**Comment by dyasny** [comment]
Logs are in 9346b97a-6dfe-41a2-994e-234e00c98c42
Timeframe: Jan 28 14:34:21 and Jan 28 21:50:58

**Comment by pidiaquez** [comment]
[9346b97a-6dfe-41a2-994e-234e00c98c42_scy-st-1-p1.scylla.log-20200129.gz](https://github.com/scylladb/scylla/files/4237539/9346b97a-6dfe-41a2-994e-234e00c98c42_scy-st-1-p1.scylla.log-20200129.gz)
[9346b97a-6dfe-41a2-994e-234e00c98c42_scy-st-1-p2.scylla.log-20200129.gz](https://github.com/scylladb/scylla/files/4237543/9346b97a-6dfe-41a2-994e-234e00c98c42_scy-st-1-p2.scylla.log-20200129.gz)
attached logs

**Comment by slivne** [comment]
I can't find a single line with ` range_streamer ` in the logs 

Please note you provided the logs from the 28th of January the error is from the 30th of January

```
[shlomi@localhost issue_5678]$ ls -lstra
total 460452
     4 drwxrwxr-x. 25 shlomi shlomi      4096 Mar 28 23:00 ..
 52724 -rw-rw-r--.  1 shlomi shlomi  53985129 Mar 28 23:01 scy-st-1-p1.scylla.log-20200129
135828 -rw-rw-r--.  1 shlomi shlomi 139082152 Mar 28 23:01 scy-st-1-p2.scylla.log-20200129
271892 -rw-rw-r--.  1 shlomi shlomi 278409964 Mar 28 23:01 scy-st-1-p3.scylla.log-20200129
     4 drwxrwxr-x.  2 shlomi shlomi      4096 Mar 28 23:05 .
[shlomi@localhost issue_5678]$ grep "range_streamer" *
```

@dyasny please provide correct logs or close the issue
