### ISSUE TITLE
writes to local.paxos create small sstables and cause a lot of compaction activity

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#5682]
*Installation details*
Scylla version (or git commit hash): d13492485f1772fc2350b09595ca1fc57e783f8a

Tables in a local keyspace usually have very limited amount of memory for memtables because not a lot of writes are expected there. Paxos table is different though, it takes a lot of writes from user and should be treated as a user table in this regards,

**Comment by avikivity** [comment]
Already backported to 3.2, 3.2.
