### ISSUE TITLE
CDC: unused (unnecessary?) `ttl` column in the log table

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#5689]
The CDC log table has a mysterious `ttl` column which is never set.

The design doc says:
> There are two special columns. First is operation which determines what type of change is recorded and ttl which is a column where a time-to-live parameter of the change is preserved. 

However, no examples from the doc confirm this. Also:
```
cqlsh> create table ks.t (pk int, ck int, v int, primary key (pk, ck)) with cdc = {'enabled':'true'};
cqlsh> insert into ks.t (pk, ck, v) values (1,2,3) using ttl 10;
cqlsh> select * from ks.t_scylla_cdc_log ;

 stream_id_1         | stream_id_2         | time                                 | batch_seq_no | _ck | _pk | _v         | operation | ttl
---------------------+---------------------+--------------------------------------+--------------+-----+-----+------------+-----------+------
 8267724797562199281 | 3002957834881714423 | c94b8f74-4425-11ea-8422-5f19bf29462a |            0 |   2 |   1 | (0, 3, 10) |         1 | null
```

looks like my ttl was stored in the `_v` tuple: `(0, 3, 10)`. The `ttl` column was null.

I see three ways to deal with this:
1. someone explains what this column is for
2. we remove this column
3. we change the regular-cdc-log-column type to be a 2-element tuple, not a 3-element tuple, and store ttl in the `ttl` column instead.

Between 2 and 3, I prefer 3, tuples are ugly.

**Comment by kbr-** [comment]
@haaawk @elcallio

**Comment by slivne** [comment]
keep ttl column and remove it from the tuple.

batch
insert into ks.t (pk, ck, v1) values (1,2,3) using ttl 10;
insert into ks.t (pk, ck, v2) values (1,2,3) using ttl 20;
end batch 

this will generate a single mutation for the table but in cdc this will be recorded as multiple rows each with a different _ttl.

**Comment by piodul** [comment]
PR associated with this issue was merged, so I'm closing it.
