### ISSUE TITLE
CDC: log entries store reduntant information

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#5704]
Given a static or regular column of type `base_type` in the base table, the corresponding column in the log table is of type
```
frozen<tuple<tinyint, base_type, bigint>>
```
However, the `tinyint` (first tuple element) doesn't add any additional information. Suppose `v` is a value in such a column. Then for delta rows `v[0]` can be computed as follows:
```
if v[1] == None:
    v[0] = 1 (del)
else:
    v[0] = 0 (set)
```
for preimage rows it's even simpler:
```
v[0] = 0 (set)
```

in particular, the `add` op, defined here:
```
enum class column_op : int8_t {
    set = 0, del = 1, add = 2,
};
```
is not used.

This might change when we handle non-frozen collections, but maybe it won't? I'm opening this issue just in case.
If `v[0]` stays redundant, we can remove it. Together with https://github.com/scylladb/scylla/issues/5689 which also claims that `v[2]` is not necessary (this information can be stored in the `ttl` column instead), we can make the schema much simpler, using `base_type` for log table columns.
@haaawk @elcallio

**Comment by haaawk** [comment]
It was meant to be used for collections. @elcallio do you still think it will be useful?

**Comment by elcallio** [comment]
If we want delta handling of non-atomics, yes. Otherwise we're back to storing a computed full value. 
Though, technically, we could probably move to just having the op part for collections.

**Comment by kbr-** [comment]
If we want a consistent log which could then (in theory) be used for replication / replaying a sequence of writes starting from some snapshot with the same final result, we can't "compute a full value" (presumably by querying the database): we must use the mutation that the write generated.

And for non-atomics, in the case of an UPSERT, the mutation only gives us a (key, value) pair + liveness info, which we should somehow store in the delta without loosing information so the user can then replay these writes. I don't know how that'd work for lists though because the user can't specify the timeuuid index for a list write (or can he?).

If we want a consistent log _and_ fully computed values, we'd probably have to linearize all writes, i.e. use LWT or the underlying mechanisms (consensus).

**Comment by elcallio** [comment]
As you might recall, the consensus for non-atomics seems to be to store "nice" updates for the good collections, i.e. set and map, and fall back to ugly deltas for lists (i.e. store as map<timeuuid, value>). 
For UDT:s we're f**ked and can mroe or less only fall back to synthesizing a full UDT value using preimage data, unless we create some horrible mega-tuple monster of flags + values representing the UDT.

**Comment by kbr-** [comment]
> fall back to ugly deltas for lists (i.e. store as map<timeuuid, value>)

That's a pretty nice delta!
If we add the possibility for the user to specify the timeuuid for CQL list updates (or maybe we already have it), this will allow replaying.

> For UDT:s we're f**ked and can mroe or less only fall back to synthesizing a full UDT value using preimage data, unless we create some horrible mega-tuple monster of flags + values representing the UDT.

Why not store exactly the thing that the mutation gives us, i.e. `map<field index, value>`?

**Comment by kbr-** [comment]
Ok, different types

**Comment by elcallio** [comment]
Nice as in "we can reconstruct". Ugly as in "reader must reconstruct". 

The storage/cql rep for UDT is actually a vector<value>, where index in vector is determined by the field index. We cannot use this as deltas, because in the case of a field delete for example, which would be 1 = null (set field 1 to null), we only know about this field. So to deliver a frozen version of the UDT we'd have to write [null, null, null ...] i.e. it would look like a delete of all fields. 

The concept map<index, value> does not work, because the value part is not consistent. I.e. field 0 is not necessarily same type as field 1.

**Comment by kbr-** [comment]
Could we use a non-frozen UDT for that? Assuming we're able to get rid of the outer 3-tuple, we can make the column non-frozen.

We could also implement "non-frozen tuples" and use them... all required mechanisms are already there, we just need to add the frontend. Then "set first field to null" would be representable.

If not, maybe the "mega-tuple monster" is the best alternative. And it's not such a monster, it's just a tuple of pairs.

**Comment by slivne** [comment]
not a bug ....

**Comment by kbr-** [comment]
@elcallio please provide an example with collections where we need an additional "tuple element" to distinguish between two different operations.

**Comment by kbr-** [comment]
Copy-pasting part of the discussion from "Some CDC feedback" thread on scylladb-dev:

> If we remove the tuple completely, how do we distinguish setting a column to null from not doing any operation on it at all? I proposed using a one-element tuple. There were other propositions to use a separate metadata column that says what has changed. Maybe everything can be somehow kept in the `operation` column?

>Maybe using `operation` is best. So a mutation that sets A=1 and B=NULL is written as two operations, one for A=1 and one for B=NULL. But still, what do we set _B to?
> Maybe have an extra columns nulled_columns with the names of those columns? But that is very inconsistent with having a cdc log column for each base table column (which is nice).
> Maybe have some kind of default value (e.g. 0 for integrals) that we store there? But we'll have to tell the users, look for any non-NULL column, and those are the ones set to NULL. Not very intuitive.
> Maybe split the tuple into two columns? so _A and _del_A (of type boolean), and either one or the other will be set. It doubles the column count, but is quite intuitive.

@avikivity

**Comment by avikivity** [comment]
> > fall back to ugly deltas for lists (i.e. store as map<timeuuid, value>)
> 
> That's a pretty nice delta!
> If we add the possibility for the user to specify the timeuuid for CQL list updates (or maybe we already have it), this will allow consistent replaying.


We already have it: search for SCYLLA_TIMEUUID_LIST_INDEX in cql3/Cql.g. It allows you to write

  UPDATE foo SET bar[timeuuid_list_index(:idx)] = :val WHERE key = ?

Although we don't have similar syntax for the entire list, or for reads, we can add one.

**Comment by elcallio** [comment]
Sets. Currently they are encoded as frozen<set>, i.e. just a collection of unique values. The op determines if we added or removed from the set. 
Otherwise we have to encode sets as frozen<map<elem, elem>> and mark deletions by nulls like actual storage does. Somewhat consistent with other non-atomics, but also ugly and less intuitive for user. 
But we also derive the op as a helpful clue to the consumer - he does not have to figure things out for himself - esp with non-atomics.

**Comment by kbr-** [comment]
> Sets. Currently they are encoded as frozen, i.e. just a collection of unique values. The op determines if we added or removed from the set.

So:
1. for a `frozen<set<int>>` column in base we'll have `frozen<tuple<tinyint, set<int>>>`  column in log
2. when we add an element `x` to the base set, we'll get `(ADD, {x})` in the log

is this correct @elcallio ?

**Comment by elcallio** [comment]
No, for a `set<int>` we have `tuple<tinyint, frozen<set<int>>>` (the second frozen is also redundant, since tuple contents is frozen just like the tuple). 
But 2 is correct.

**Comment by kbr-** [comment]
@elcallio 

Note that you can do:
```
cqlsh> create table ks.coll (a int primary key, b set<int>);
cqlsh> update ks.coll set b = {1,2} where a = 0;
cqlsh> update ks.coll set b = b + {3}, b = b - {1} where a = 0;
cqlsh> select * from ks.coll  ;

 a | b
---+--------
 0 | {2, 3}

```

`(ADD/DELL, {...})` can't represent
```
cqlsh> update ks.coll set b = b + {3}, b = b - {1} where a = 0;
```

**Comment by kbr-** [comment]
In any case, we can drop the tuple for atomic types, right? (leaving us only with the null/non-null problem)
And devise a general enough column for each non-atomic type.

**Comment by elcallio** [comment]
Ugh. I did not know that was legal cql syntax. That would require breaking the log row into two (commented in the atomix branch). 
You still cannot drop the tuple for non-atomic columns since again you need to store whether the column was set to null or simply was not part of the mutation. So either a single-elem tuple, or no tuple + additional column or similar. In any case, so marker bit is required.

**Comment by elcallio** [comment]
Note however that your statement that the above sets op is valid cql is a big argument for simply dropping any "nice" packing pretence, and just go the map<> route (saves logic in breaking up log rows).

**Comment by kbr-** [comment]
> That would require breaking the log row into two (commented in the atomix branch).

Please, no :(
Let's go with something like `map<base_set_element_type, empty_type>`
(however, `empty_type` is not exposed for CQL, so we can use e.g. `map<base_set_element_type, tinyint>`)

**Comment by elcallio** [comment]
Actually, come to think of it, we have sort of a problem with the above (and maps as well). 
The cql encoding (i.e. flattened/frozen) does not make any difference between an empty value (`string{}`) and a null value. So encoding `map["apa"] = ""` is equivalent to `map["apa"] = null` in the cdc log. Unless of course the `op` is there + breaking stuff into neat rows... :-(

**Comment by kbr-** [comment]
@elcallio 

How about going the one-element-tuple way everywhere? It's pretty elegant IMO:
```
cqlsh> create table ks.c (a int primary key, b frozen<map<int, tuple<text>>>);
cqlsh> insert into ks.c (a, b) values (0, {0: (null)});
cqlsh> select * from ks.c;

 a | b
---+-------------
 0 | {0: (None)}

(1 rows)

cqlsh> insert into ks.c (a, b) values (0, {0: ('')});
cqlsh> select * from ks.c;

 a | b
---+-----------
 0 | {0: ('')}

(1 rows)
```

**Comment by elcallio** [comment]
It potentially adds much more overhead in the case of a collection (disparate add/deletes are rare). I don't really care, but I think Avi might dislike it. The user will need to jump some hoops...

**Comment by kbr-** [comment]
@elcallio 

If you claim than add+delete in the same update is rare, then I claim that two adds are also rare.
For the most common situation -- single add or delete -- I suspect that `{0: (None)}` isn't really worse than `(DEL, {0})`. It might be even better, we'd have to check.

In any case this discussion is really premature optimization... We should focus on simplicity and correctness first.

> The user will need to jump some hoops...

IMO with tuples it's fewer hoops than with `ADD/DEL` tags. It's very simple too.
A single-elem tuple has 3 states: `null`, `(None)`, `(value)`. `null` means nothing happened to this element, `(None)` means it was deleted/set to null, `(value)` means it was set to non-null `value`.

**Comment by kbr-** [comment]
Also splitting a single insert into multiple entries in the log adds problems for the user, because he then has to handle single-timestamp-batch-updates even in cases where he didn't even perform a batch.
