### ISSUE TITLE
CQL: Scylla does not guarantee the uniqueness of the return value of the function now();

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#571]
According to the Cassandra documentation:

http://docs.datastax.com/en/cql/3.0/cql/cql_reference/timeuuid_functions_r.html

* `now()` - Generates a new unique timeuuid when the statement is executed. This method is useful for inserting values. The value returned by `now()` is guaranteed to be unique.

If we programatically execute a series of inserts in the database in the form:

    CREATE KEYSPACE IF NOT EXISTS lmr_test_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
    CREATE TABLE lmr_test_keyspace.table_timeuuid (k int, t timeuuid, PRIMARY KEY(k, t))

And add a bunch of records in the form:

    INSERT INTO lmr_test_keyspace.table_timeuuid (k, t) VALUES (0, now());

Given that now() is guaranteed to return unique values, the resulting table should
have as many records as the number of times we run insert on that table.

However, this is not happening. If you automate this procedure, you'll see that
the number of rows stored is smaller than the number of times the table had
insertions, suggesting that now() is not guaranteed to be unique.

I believe this might by scylla's version of the origin bug:

https://issues.apache.org/jira/browse/CASSANDRA-5616

Steps to reproduce:

1) Download and untar the attached reproducer
2) Start a cassandra cluster using ccm
3) Run `mvn test` inside the reproducer's directory

You'll see an error similar to:

    Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.95 sec <<< FAILURE!
    testTimeuuid(org.apache.cassandra.cql3.validation.entities.TimeuuidTest)  Time elapsed: 0.476 sec  <<< FAILURE!
    java.lang.AssertionError: expected:<4> but was:<2>
    ...
    java backtrace follows

Expected result: Test passes, indicating that now() is returning unique values
Actual result: Test fails, indicating that now() can return 2 identical now() values

**Comment by lmr** [comment]
The reproducer can be found on

https://lmr.fedorapeople.org/github-issues/scylla/issues/571/time-uuid-issue-reproducer.tar.gz

**Comment by penberg** [comment]
The ``now`` function maps to ``UUIDGen.getTimeUUIDBytes()`` in C* and to ``utils::UUID_gen::get_time_UUID()`` in Scylla. Perhaps we have a bug in the latter?

@avikivity @tgrabiec @nyh

**Comment by penberg** [comment]
I think I found the problem. Assigning to myself.

**Comment by lmr** [comment]
@penberg, awesome, Indeed we're now passing the unittests. Thanks!
