### ISSUE TITLE
Moving sstables from staging should be atomic/idempotent

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5714]
Since 3.1 sstables are moved from the staging directory to the table base directory by the view builder, and the operation may be retried when scylla starts and populated the keyspace (de43b4f41d).

Since the move operation is not atomic and not idempotent, retrying it may fail as that target links may exist.

We can roll back the move on startup if the temporary TOC component still exists, meaning the move operation is not finished, showing like an unsealed sstable.  However there is still a possible point in time, when `sstable::create_links` that the target sstable is "sealed" and the source sstable is not removed yet.

**Comment by slivne** [comment]
@bhalevy can we close this ?

**Comment by bhalevy** [comment]
> @bhalevy can we close this ?

I wanted to verify that we do the right thing on restart if we hit a failure while moving sstables from `staging`.
When this issue was opened the distributed loader didn't process the folders at the right order and saw both the sstable in the staging directory and its linked copy in the main directory causing confusion.

This code had significantly changed in b34c0c2ff6918d0265393c461b1032c8f9b934ed so.
That said, the issue hasn't been since the fix for #7429 for merged, so we can gratuitously close the issue and reopen if it hits again.

**Comment by bhalevy** [comment]
Closing since this wasn't reproduced.
