### ISSUE TITLE
alternator: configuring per-table write isolation-mode using tags

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5716]
Alternator current support four modes for how on how to implement write isolation: FORBID_RMW, LWT_ALWAYS, LWT_RMW_ONLY, UNSAFE_RMW.
Currently, the mode is chosen using a global compile-time constant (which currently defaults to LWT_ALWAYS).

Now that we have tag support (#5066), we can use tags on each table to determine the mode to use for all writes to this table.

**Comment by psarna** [comment]
I see that I forgot to mark the github issue in the commit message, so I'll do this manually: abdbb70ad9458833df312a1f9a5db47d35e7bb02 was queued to next.

**Comment by nyh** [comment]
The aforementioned commit reached the master branch, so we can close this issue.
