### ISSUE TITLE
CDC: batch write mutations should (sometimes?) be split

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#5719]
```
cqlsh> create table ks.t (pk int, ck int, v1 int, v2 int, primary key (pk, ck)) with cdc = {'enabled':'true'};
cqlsh> begin batch
   ... insert into ks.t (pk, ck, v1) values (0,0,1) using timestamp 1580833443199000;
   ... insert into ks.t (pk, ck, v2) values (0,0,1) using timestamp 1580833443198000;
   ... apply batch;
cqlsh> select system.totimestamp(time), batch_seq_no, "_pk", "_ck", "_v1", "_v2", operation from ks.t_scylla_cdc_log;

 system.totimestamp(time)        | batch_seq_no | _pk | _ck | _v1          | _v2          | operation
---------------------------------+--------------+-----+-----+--------------+--------------+-----------
 2020-02-04 16:24:03.199000+0000 |            0 |   0 |   0 | (0, 1, None) | (0, 1, None) |         1
```

clearly in the above example two entries should've appeared in the log, because two different timestamps were used on separate cells. Information about `v2`'s timestamp was lost.

However it is perhaps worthy to discuss whether we should split in the following example, where we write to the same cell:
```
cqlsh> create table ks.t (pk int, ck int, v int, primary key (pk, ck)) with cdc = {'enabled':'true'};
cqlsh> begin batch
   ... insert into ks.t (pk, ck, v) values (0,0,1) using timestamp 1580833443199000;
   ... insert into ks.t (pk, ck, v) values (0,0,1) using timestamp 1580833443198000;
   ... apply batch;
cqlsh> select system.totimestamp(time), batch_seq_no, "_pk", "_ck", "_v", operation from ks.t_scylla_cdc_log;

 system.totimestamp(time)        | batch_seq_no | _pk | _ck | _v           | operation
---------------------------------+--------------+-----+-----+--------------+-----------
 2020-02-04 16:24:03.199000+0000 |            0 |   0 |   0 | (0, 1, None) |         1
```
_can_ we even split? I'd guess that the information about
```
   ... insert into ks.t (pk, ck, v) values (0,0,1) using timestamp 1580833443198000;
```
was completely lost during merging.

Continuing the discussion... in the following case:
```
cqlsh> create table ks.t (pk int, ck int, v1 int, v2 int, primary key (pk, ck)) with cdc = {'enabled':'true'};
cqlsh> begin batch
   ... insert into ks.t (pk, ck, v1) values (0,0,1);
   ... insert into ks.t (pk, ck, v2) values (0,0,1);
   ... apply batch;
```
should we split? Is this different than
```
cqlsh> create table ks.t (pk int, ck int, v1 int, v2 int, primary key (pk, ck)) with cdc = {'enabled':'true'};
cqlsh> insert into ks.t (pk, ck, v1, v2) values (0,0,1,1);
```
? Perhaps the above two cases are indistinguishable from a mutation's perspective, so again we _can't_ split, but it requires research (and if it can, a decision whether we should).

Well... we can decide to always split when dealing with multiple columns, even in that last case (one insert to two columns): each column always gets a separate entry.
Perhaps we _should_ do that, because of:
```
cqlsh> create table ks.t (pk int, ck int, v1 int, v2 int, primary key (pk, ck)) with cdc = {'enabled':'true'};
cqlsh> begin batch
   ... insert into ks.t (pk, ck, v1) values (0,0,1) using ttl 10;
   ... insert into ks.t (pk, ck, v2) values (0,0,1);
   ... apply batch;
```
if we want to keep the `ttl` column and remove ttl from the tuple, we have to split in this last case.

Issue requires:
1. research (what can and cannot be done)
2. decision that's consistent and makes sense
3. implementation
4. testing

**Comment by kbr-** [comment]
@haaawk @elcallio @avikivity 
let's discuss

**Comment by gleb-cloudius** [comment]
What do you mean by "split"? You cannot split a batch because it has to
be applied atomically (if all entires modify the same key).

--
			Gleb.

**Comment by kbr-** [comment]
The following:
```
cqlsh> create table ks.t (pk int, ck int, v1 int, v2 int, primary key (pk, ck)) with cdc = {'enabled':'true'};
cqlsh> begin batch
   ... insert into ks.t (pk, ck, v1) values (0,0,1);
   ... insert into ks.t (pk, ck, v2) values (0,1,1);
   ... apply batch;
```
internally creates a vector of two mutations (notice I used a different clustering key).

But the following:
```
cqlsh> create table ks.t (pk int, ck int, v1 int, v2 int, primary key (pk, ck)) with cdc = {'enabled':'true'};
cqlsh> begin batch
   ... insert into ks.t (pk, ck, v1) values (0,0,1);
   ... insert into ks.t (pk, ck, v2) values (0,0,1);
   ... apply batch;
```
internally creates a singleton vector (because the primary key is the same in both inserts).

CDC works by taking the vector of mutations and basically performing a `transform` on this vector. Each base mutation generates an extra (CDC log) mutation.

However for some mutations it would (perhaps) be desirable to take such a base mutation and perform a 2-step operation on it:
`base batch mutation` -> `multiple base mutations` -> `multiple log mutations`
The first step is the split, the second step is the `transform`.

Of course we would write the original base batch mutation to the base table. The split would be an intermediate step to generate CDC mutations. Or we can say it's just a way of thinking about the problem, it won't necessarily be a literal split into multiple base mutations.
