### ISSUE TITLE
CDC: inserts and updates should be different operations

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#5723]
Because they have different effects. CDC log's "operation" column should provide that information.
(and until yesterday I thought insert and update is the same thing, "upsert"...)

```
cqlsh> create table ks.t (pk int, ck int, v int, primary key (pk, ck)) with cdc = {'enabled':'true', 'preimage':'true'};
cqlsh> update ks.t set v = null where pk = 0 and ck = 0;
cqlsh> select * from ks.t where pk = 0 and ck = 0;

 pk | ck | v
----+----+---

(0 rows)
cqlsh> insert into ks.t (pk,ck,v) values (0,0,null);
cqlsh> select * from ks.t where pk = 0 and ck = 0;

 pk | ck | v
----+----+------
  0 |  0 | null

(1 rows)
cqlsh> 
```

the difference is that `insert` _inserts a live row marker_. `update` doesn't touch the row marker at all.

By the way: `update` with setting a column to `null` is the same as a _column delete_:
```
update ks.t set v = null where pk = 0 and ck = 0;
```
is the same as
```
delete v from ks.t where pk = 0 and ck = 0;
```
column delete also doesn't touch the row marker, it just inserts a dead cell into the selected column, just like `update` with `null`. Thus we don't need to distinguish a column delete from a null update.

In cdc/log.hh we have:
```
enum class operation : int8_t {
    // note: these values will eventually be read by a third party, probably not privvy to this
    // enum decl, so don't change the constant values (or the datatype).
    pre_image = 0, update = 1, row_delete = 2, range_delete_start = 3, range_delete_end = 4, partition_delete = 5
};
```
we need to add another entry: "insert".

Note that null update/column delete is different from a row delete. This issue is related to https://github.com/scylladb/scylla/issues/5709, but it's different. Here's a summary of differences between inserts, updates, and row deletes:
1. `insert` inserts a live row marker and maybe updates some columns (if specified).
2. `update` doesn't touch the row marker at all, only updates some columns.
3. row `delete` (but not a column `delete`, which is the same as `update`) inserts a _row tombstone_ which kills all cells, including the row marker.

These 3 cases should be distinguished in CDC.

**Comment by elcallio** [comment]
Something is broken with your update. CQL docs clearly says "UPDATE is an upsert operation. If a matching row does not exist it is created". And that is what happens when I do a similar update.

**Comment by kbr-** [comment]
CQL docs are not 100% accurate.

> when I do a similar update.

Similar in what sense? Did you also set a `null`?

**Comment by elcallio** [comment]
Ah, sorry, missed the null part. Indeed. But can we distinguish these on a mutation level?

**Comment by kbr-** [comment]
Yes, by looking at the row marker:
1. `update` doesn't touch the row marker (it won't be present in the mutation)
2. `insert` inserts a live row marker
3. bonus: row delete (`delete from t ...`) inserts a dead row marker

**Comment by kbr-** [comment]
Proof: I added in cdc/log.cc `transform`:
```
                std::cout << "ROW MARKER MISSING: " << r.row().marker().is_missing() << std::endl;
```

Then:
```
cqlsh> update ks.t set v = null where pk = 0 and ck = 0;
```
gives in Scylla's logs:
```
ROW MARKER MISSING: 1
```

but
```
cqlsh> insert into ks.t (pk,ck,v) values (0,0,null);
```
gives
```
ROW MARKER MISSING: 0
```

**Comment by kbr-** [comment]
About row deletes I wasn't completely precise: `delete from ks.t ...` inserts a _row tombstone_, which kills the row marker (if it wasn't dead already).
