### ISSUE TITLE
Scylla_setup: still ask for nic in non-interactive mode 

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla#5725]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.2.1
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

fixes are missing for https://github.com/scylladb/scylla/issues/3908 in some "if" branches

**Comment by tarzanek** [comment]
# scylla_setup  --setup-nic-and-disks --nic=eth0 --no-ntp-setup --no-raid-setup --no-node-exporter
Please select a NIC from the following list:
['eth0', 'veth3a9422c', 'vethbaa4cef', 'docker0', 'veth9c57d7c']

above is in ec2

**Comment by tarzanek** [comment]
seems checks are missing in
```
 if is_ec2():
        ec2_check = interactive_ask_service('Do you want to run Amazon EC2 configuration check?', 'Yes - runs a script to verify that this instance is optimized for running Scylla. No - skips the configuration check.', ec2_check)
        args.no_ec2_check = not ec2_check
        if ec2_check:
            nic = interactive_choose_nic()
        if ec2_check:
            run('{}/scylla_ec2_check --nic {}'.format(scriptsdir(), nic))
```
and
```
  if sysconfig_setup:
            if interactive:
                nic = interactive_choose_nic()
```

**Comment by syuu1228** [comment]
I also able to reproduce this issue on non-EC2 environment too.
And it occurs on scylla-3.1, 3.2, 3.3 and master.
I think the change between 3.0 and 3.1 causes the problem.

**Comment by dyasny** [comment]
@slivne @eliransin hitting this in the field, we need the fix backported to 3.2 and 3.3

**Comment by dyasny** [comment]
Ticket number 1135

**Comment by avikivity** [comment]
Aged out.
