### ISSUE TITLE
Cluster freezes with lots of  'Reactor stalled for 2000 ms' exceptions after adding new node

### ISSUE THREAD

**Issue by jeltok** [scylladb/scylla#5732]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.10-0.20190815.b3bfd8c08.el7.x86_64
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): EC2 i3.4xlarge
Hardware: sockets= cores= hyperthreading= memory= 16 cores / 128 GB
Disks: (SSD/HDD, count) RAID of 2 SSDs

Hi, I have a cluster running v3.0.1o on AWS, that now consists of 2 nodes, I am having trouble adding 3rd node. When I am adding a new node, it starts fine, replicates all data, and than that new node fails with a lot of stack traces. The whole cluster stops accepting reads and writes. Once I remove that 3rd node, the cluster (2 remaining nodes) come back after several minutes.

I have discussed it on ScyllaDB slack, and was advised to open an issue.

Below are fragments of the log file (attached, that point to the issue)

Feb 02 05:53:27 ip-172-31-18-216.ec2.internal scylla[17861]:  [shard 0] storage_service - Node 172.31.18.216 state jump to normal
Feb 02 05:53:27 ip-172-31-18-216.ec2.internal scylla[17861]:  [shard 0] storage_service - NORMAL: node is now in normal status
...
Feb 02 05:53:39 ip-172-31-18-216.ec2.internal scylla[17861]:  [shard 0] gossip - No gossip backlog; proceeding
Feb 02 05:53:39 ip-172-31-18-216.ec2.internal scylla[17861]:  [shard 0] storage_service - Starting listening for CQL clients on 0.0.0.0:9042 (unencrypted)
Feb 02 05:53:39 ip-172-31-18-216.ec2.internal scylla[17861]:  [shard 0] storage_service - Thrift server listening on 0.0.0.0:9160 ...
Feb 02 05:53:43 ip-172-31-18-216.ec2.internal scylla[17861]:  [shard 10] compaction - Compacting [/var/lib/scylla/data/pushnomics/pushnomics_offers-a5f09760d70011e891b5000000000007/la-598-big-Data.db:level=0, /var/lib/scylla/data/pushnomics/pushnomics_offers-a5f09760d70011e891b5000000000007/la-626-big-Data.db:level=0, ]
Feb 02 05:53:45 ip-172-31-18-216.ec2.internal scylla[17861]: Reactor stalled for 2000 ms on shard 9.
Feb 02 05:53:45 ip-172-31-18-216.ec2.internal scylla[17861]: Backtrace:
Feb 02 05:53:45 ip-172-31-18-216.ec2.internal scylla[17861]: 0x00000000006ab5a2
Feb 02 05:53:45 ip-172-31-18-216.ec2.internal scylla[17861]: 0x00000000005c2c8c
Feb 02 05:53:45 ip-172-31-18-216.ec2.internal scylla[17861]: 0x00000000005c3146
Feb 02 05:53:45 ip-172-31-18-216.ec2.internal scylla[17861]: /lib64/libpthread.so.0+0x000000000000f5cf
Feb 02 05:53:45 ip-172-31-18-216.ec2.internal scylla[17861]: 0x0000000001f88632

Please advise how to overcome this issue.
[scylla_error.log](https://github.com/scylladb/scylla/files/4162984/scylla_error.log)

**Comment by asias** [comment]
I decoded the stall with the binary scylla-debuginfo-3.0.10-0.20190815.b3bfd8c08.el7.x86_64.rpm

$ seastar/scripts/seastar-addr2line   -e  ~/Downloads/issue.slack.add.node/./usr/lib/debug/usr/bin/scylla.debug -f ~/Downloads/issue.slack.add.node/selected.stall.txt

[selected.stall.decode.txt](https://github.com/scylladb/scylla/files/4162989/selected.stall.decode.txt)
[selected.stall.txt](https://github.com/scylladb/scylla/files/4162990/selected.stall.txt)
[full.decode.txt](https://github.com/scylladb/scylla/files/4162991/full.decode.txt)

The stall comes from cql.

**Comment by asias** [comment]
Btw, according to the log,  both the bootstrap and decommission were successful.

Node3 added successfully.
```
Feb 02 05:53:27 ip-172-31-18-216.ec2.internal scylla[17861]:  [shard 0] storage_service - Bootstrap completed! 
```

Node3 is removed successfully.
```
Feb 02 05:59:44 ip-172-31-18-216.ec2.internal scylla[17861]:  [shard 0] storage_service - DECOMMISSIONING: done
```

**Comment by jeltok** [comment]
Thanks for the info Asias. That's correct adding and removing of the node was successful, however the whole cluster of 3 nodes stopped receiving reads and writes as soon as 'Reactor stalled for 2000 ms' exception started to appear in logs. It was frozen until I removed that new node, and restarted the other two nodes.

**Comment by fruch** [comment]
@asias did you noticed those `oversized allocation`:
```
Feb 02 05:54:43 ip-172-31-18-216.ec2.internal scylla[17861]:  [shard 0] seastar_memory - oversized allocation: 2097152 bytes, please report: at   0x7d0358
                                                               0x75b6b3
                                                               0x760eb6
                                                               0x761404
                                                               0x6c4a63
                                                               0x5c9722
                                                               0x1d62666
                                                               0x5a0ef4
                                                               0x5c5018
                                                               0x6bac85
                                                               0x59f874
                                                               0x6727d6
                                                               0x7b0603
                                                               0x537548
                                                               /lib64/libc.so.6+0x22494
                                                               0x59df3d
```

@jeltok  how big are your rows ?

also do you have [scylla-monitoring](https://github.com/scylladb/scylla-monitoring) connected to this setup ? this would help us gain much more insight into what's going on (you know, one picture vs. 1000 word and all that)

**Comment by avikivity** [comment]
Note that 3.0 has reached end-of-life and is no longer supported.

What kind of queries are you sending? From the trace it looks like you are sending complicated queries, but maybe this is the wrong interpretation. Also, are you using prepared statements?

**Comment by jeltok** [comment]
Thanks everybody! We have upgraded 2 cluster nodes to 3.0.11 and were able to add 3rd node successfully. Next step we will upgrade the whole cluster to 3.1 -> 3.2. 
We have Scylla Monitoring connected to the cluster, and that's what was happening when adding the 3rd node:

![Annotation 2020-02-06 195533](https://user-images.githubusercontent.com/1056801/73995764-9de7fc80-4927-11ea-9851-ec6e49104aa3.jpg)

Cluster had trouble accepting writes for about 5 minutes, but then everything came back to normal.
Hope it will behave better with latest versions of ScyllaDB.

Our queries are key/value inserts and lookups, with TTL. In some cases we use collections to store multiple values per key with individual TTLs. I have noticed that one of our tables has pretty huge max partition size: 1386179893 bytes. Will try to figure out how to address that.

Please let me know if I should close the issue, since I was able to add the 3rd node.

**Comment by fruch** [comment]
Sounds like you on the right path.

Since the old version won't going to get any fixes.
I think you can close this it.

Good luck with the upgrades, would love to hear if things went smoothly
