### ISSUE TITLE
CQL: Scylla does not support tuple from string notation

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#574]
Even though it 's not documented on the TupleType definition [1], [2] (I'm yet to find a piece of documentation that mentions it whatsoever), Cassandra supports specifying strings using literal notation (output obtained using cassandra 2.1.11):

    [cqlsh 5.0.1 | Cassandra 2.1.11 | CQL spec 3.2.1 | Native protocol v3]
    Use HELP for help.
    cqlsh> CREATE KEYSPACE IF NOT EXISTS lmr_test_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
    cqlsh> CREATE TABLE lmr_test_keyspace.table_tuple_type_test (k int, c int, t frozen<tuple<int, text>>, PRIMARY KEY (k, c));
    cqlsh> INSERT INTO lmr_test_keyspace.table_tuple_type_test (k, c, t) VALUES (0, 0, '0:0');
    cqlsh> SELECT * FROM lmr_test_keyspace.table_tuple_type_test;

     k | c | t
    ---+---+----------
     0 | 0 | (0, '0')

    (1 rows)

Scylla does not support that:

    Connected to scylla-3 at 127.0.0.1:9042.
    [cqlsh 5.0.1 | Cassandra 2.1.8 | CQL spec 3.2.0 | Native protocol v3]
    Use HELP for help.
    cqlsh> CREATE KEYSPACE IF NOT EXISTS lmr_test_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
    cqlsh> CREATE TABLE lmr_test_keyspace.table_tuple_type_test (k int, c int, t frozen<tuple<int, text>>, PRIMARY KEY (k, c));
    cqlsh> INSERT INTO lmr_test_keyspace.table_tuple_type_test (k, c, t) VALUES (0, 0, '0:0');
    ServerError: <ErrorMessage code=0000 [Server error] message="not implemented">

If some good soul can find where this spec is located, that'd be appreciated. Maybe I just don't know the ropes to find things in the docs yet.

Anyway, if it serves, the origin unittests have the following references to insert statements that should be valid:

        createTable("CREATE TABLE %s (k int, c int, t frozen<tuple<int, text>>, PRIMARY KEY (k, c))");

        TupleType innerTupleType = TupleType.of(DataType.cint(), DataType.text());
        TupleType outerTupleType = TupleType.of(DataType.cint(), DataType.cint(), innerTupleType);

        execute("INSERT INTO %s (k, c, t) VALUES (0, 0, '0:0')");
        execute("INSERT INTO %s (k, c, t) VALUES (0, 1, '0:1')");
        execute("INSERT INTO %s (k, c, t) VALUES (0, 2, '1')");
        execute("INSERT INTO %s (k, c, t) VALUES (0, 3, '1:1\\:1')");
        execute("INSERT INTO %s (k, c, t) VALUES (0, 4, '@:1')");

        assertAllRows(
            row(0, 0, tuple(outerTupleType, 0, "0")),
            row(0, 1, tuple(outerTupleType, 0, "1")),
            row(0, 2, tuple(outerTupleType, 1)),
            row(0, 3, tuple(outerTupleType, 1, "1:1")),
            row(0, 4, tuple(outerTupleType, null, "1"))
        );
I hope this helps.

[1] http://docs.datastax.com/en/developer/java-driver/2.1/java-driver/reference/tupleTypes.html
[2] https://cassandra.apache.org/doc/cql3/CQL.html - It states that version 3.2.0 added tuples, but I don't see using string literal notation specification for tuples.

**Comment by penberg** [comment]
Fixed by https://github.com/scylladb/scylla/commit/d3f91eec614e95d08cfdd59cc88a24bafd6f18b6
