### ISSUE TITLE
Alternator - reactor stall during compaction

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#5742]
during a [3h alternator longevity job](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/alternator-longevity-3h/2), we encountered a stall during a compaction (after a nodetool truncate failed).

```
2020-02-04 08:48:05.000: (DatabaseLogEvent Severity.CRITICAL): type=REACTOR_STALLED regex=Reactor stalled line_number=7625 node=Node alternator-3h-master-db-node-b083bf22-1 [52.48.29.150 | 10.0.188.201] (seed: True)
2020-02-04T08:48:05+00:00  alternator-3h-master-db-node-b083bf22-1 !INFO    | scylla: Reactor stalled for 3457 ms on shard 0.

void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:743
seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:1158
seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1061
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1184
?? ??:0
void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseStringToStream<0u, rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>, rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::StackStream<char> >(rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>&, rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::StackStream<char>&) at /usr/include/fmt/format.h:1158
void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseString<0u, rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> >(rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>&, bool) at /usr/include/fmt/format.h:1158
void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> >(rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>&) at /usr/include/fmt/format.h:1158
void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseObject<0u, rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> >(rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>&) at /usr/include/fmt/format.h:1158
void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> >(rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>&) at /usr/include/fmt/format.h:1158
void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseObject<0u, rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> >(rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>&) at /usr/include/fmt/format.h:1158
void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> >(rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>&) at /usr/include/fmt/format.h:1158
void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseObject<0u, rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> >(rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>&) at /usr/include/fmt/format.h:1158
void rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::ParseValue<0u, rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> >(rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>&) at /usr/include/fmt/format.h:1158
rapidjson::ParseResult rapidjson::GenericReader<rapidjson::UTF8<char>, rapidjson::UTF8<char>, rapidjson::CrtAllocator>::Parse<0u, rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator> >(rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>&, rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>&) at /usr/include/fmt/format.h:1158
 (inlined by) rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>& rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>::ParseStream<0u, rapidjson::UTF8<char>, rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream> >(rapidjson::EncodedInputStream<rapidjson::UTF8<char>, rapidjson::MemoryStream>&) at /usr/include/rapidjson/document.h:2159
rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>& rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>::Parse<0u, rapidjson::UTF8<char> >(rapidjson::UTF8<char>::Ch const*, unsigned long) at /usr/include/fmt/format.h:1158
 (inlined by) rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>& rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>::Parse<0u>(char const*, unsigned long) at /usr/include/rapidjson/document.h:2254
 (inlined by) rapidjson::GenericDocument<rapidjson::UTF8<char>, rapidjson::CrtAllocator, rapidjson::CrtAllocator>::Parse(char const*, unsigned long) at /usr/include/rapidjson/document.h:2258
 (inlined by) rjson::parse_raw(char const*, unsigned long) at ./alternator/rjson.cc:47
rjson::parse(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) at /usr/include/fmt/format.h:1158
alternator::executor::put_item(service::client_state&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) at /usr/include/fmt/format.h:1158
operator() at /usr/include/fmt/format.h:1158
 (inlined by) do_with<service::client_state, alternator::executor::put_item(alternator::executor::client_state&, std::string)::<lambda(alternator::executor&)> mutable::<lambda(service::client_state&)> > at ././seastar/include/seastar/core/do_with.hh:94
 (inlined by) operator() at ./alternator/executor.cc:1233
operator() at /usr/include/fmt/format.h:1158
 (inlined by) apply<seastar::sharded<T>::invoke_on(unsigned int, seastar::smp_service_group, Func&&) [with Func = alternator::executor::put_item(alternator::executor::client_state&, std::string)::<lambda(alternator::executor&)>; Ret = seastar::future<std::variant<seastar::json::json_return_type, alternator::api_error> >; Service = alternator::executor]::<lambda()>&> at ././seastar/include/seastar/core/future.hh:1655
 (inlined by) operator() at ././seastar/include/seastar/core/smp.hh:194
 (inlined by) apply at ././seastar/include/seastar/core/apply.hh:36
 (inlined by) apply<seastar::smp_message_queue::async_work_item<Func>::process() [with Func = seastar::sharded<T>::invoke_on(unsigned int, seastar::smp_service_group, Func&&) [with Func = alternator::executor::put_item(alternator::executor::client_state&, std::string)::<lambda(alternator::executor&)>; Ret = seastar::future<std::variant<seastar::json::json_return_type, alternator::api_error> >; Service = alternator::executor]::<lambda()>]::<lambda()>&> at ././seastar/include/seastar/core/apply.hh:44
 (inlined by) apply<seastar::smp_message_queue::async_work_item<Func>::process() [with Func = seastar::sharded<T>::invoke_on(unsigned int, seastar::smp_service_group, Func&&) [with Func = alternator::executor::put_item(alternator::executor::client_state&, std::string)::<lambda(alternator::executor&)>; Ret = seastar::future<std::variant<seastar::json::json_return_type, alternator::api_error> >; Service = alternator::executor]::<lambda()>]::<lambda()>&> at ././seastar/include/seastar/core/future.hh:1645
 (inlined by) operator() at ././seastar/include/seastar/core/future-util.hh:85
 (inlined by) run_and_dispose at ././seastar/include/seastar/core/task.hh:48
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/include/fmt/format.h:1158
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2695
seastar::app_template::run_deprecated(int, char**, std::function<void ()>&&) at /usr/include/boost/program_options/variables_map.hpp:146
seastar::app_template::run(int, char**, std::function<seastar::future<int> ()>&&) at /usr/include/boost/program_options/variables_map.hpp:146
main at ./main.cc:481
?? ??:0
_start at ??:?
```

**Comment by fgelcer** [comment]
the same apparently happen another time, few hours later (few minutes after repair):

```
< t:2020-02-04 10:24:10,822 f:remote.py       l:121  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.122.23]: Command "addr2line -Cpife /tmp/scylla-666.development-0.20200204.2816404f575.x86_64.debug 0x0000000003281052 0x000000000321ca2b 0x000000000321cf52 0x000000000321d287 0x00007faf8943bb1f 0x00007faf8943a87b 0x0000000003244b98 0x0000000003218ce1 0x0000000003218eef 0x0000000003259b55 0x000000000326879c 0x00000000031e401d /libreloc/libpthread.so.0+0x00000000000094e1 /libreloc/libc.so.6+0x00000000001016d2" finished with status 0
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > 2020-02-04 10:24:05.000: (DatabaseLogEvent Severity.CRITICAL): type=REACTOR_STALLED regex=Reactor stalled line_number=32702 node=Node alternator-3h-master-db-node-b083bf22-1 [52.48.29.150 | 10.0.188.201] (seed: True)
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > 2020-02-04T10:24:05+00:00  alternator-3h-master-db-node-b083bf22-1 !INFO    | scylla: Reactor stalled for 3583 ms on shard 1.
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > 
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  >  (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:743
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > seastar::internal::cpu_stall_detector::generate_trace() at /usr/include/fmt/format.h:1158
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > seastar::internal::cpu_stall_detector::maybe_report() at /usr/include/fmt/format.h:1158
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  >  (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1061
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  >  (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1184
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > ?? ??:0
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > ?? ??:0
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > seastar::file_desc::read(void*, unsigned long) at /usr/include/fmt/format.h:1158
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  >  (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:275
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  >  (inlined by) apply at ./build/release/seastar/./seastar/include/seastar/core/apply.hh:36
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  >  (inlined by) apply<seastar::reactor::read_some(seastar::pollable_fd_state&, void*, size_t)::<lambda()> > at ./build/release/seastar/./seastar/include/seastar/core/apply.hh:44
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  >  (inlined by) apply<seastar::reactor::read_some(seastar::pollable_fd_state&, void*, size_t)::<lambda()> > at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1645
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  >  (inlined by) operator() at ./build/release/seastar/./seastar/include/seastar/core/future.hh:1191
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  >  (inlined by) run_and_dispose at ./build/release/seastar/./seastar/include/seastar/core/future.hh:506
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/include/fmt/format.h:1158
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  >  (inlined by) seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2695
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at /usr/include/fmt/format.h:1158
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > std::function<void ()>::operator()() const at /usr/include/c++/9/bits/std_function.h:690
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  >  (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:52
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > ?? ??:0
< t:2020-02-04 10:24:10,835 f:sct_events.py   l:711  c:sdcm.sct_events      p:INFO  > ?? ??:0
```

**Comment by fgelcer** [comment]
```
+--------------------------------------------------------------------------------------------------------------------------------------------+
|           Collected logs by test-id: b083bf22-ac7c-42f9-8430-be7beda7c6c1 Directory: /sct/20200204-080729-056551/collected_logs            |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Cluster set | Link                                                                                                                         |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/b083bf22-ac7c-42f9-8430-be7beda7c6c1/20200204_113307/db-cluster-b083bf22.zip  |
| monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/b083bf22-ac7c-42f9-8430-be7beda7c6c1/20200204_113307/monitor-set-b083bf22.zip |
| loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/b083bf22-ac7c-42f9-8430-be7beda7c6c1/20200204_113307/loader-set-b083bf22.zip  |
| sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/b083bf22-ac7c-42f9-8430-be7beda7c6c1/20200204_113307/sct-runner-b083bf22.zip  |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by nyh** [comment]
@glommer I think you're the expert on these reactor stalls, can you please give me a few hints how to debug them? The stack trace in the bug report suggests we were doing some simple JSON parsing in an Alternator PutItem request, but I don't understand how this can possibly hang. Could it be that something else hung, and the PutItem request was just the first thing after the hang - or was blamed for another reason?
Given Alternator's nature as an API layer above the existing code, I don't see how it could have caused any hangs, but I don't know how to prove/disprove my theory.

**Comment by psarna** [comment]
@nyh on the other hand, if any rjson operation would be a suspect for stalling, it would be `rjson::parse`. It parses a whole JSON document by repeatedly calling a function in recursive manner (`rapidjson::ParseValue`) without yielding and it includes allocations.

@fgelcer, could you estimate how big were the items inserted in this longevity test? If we're talking about JSONs with tens of thousands of variously sized elements inside them, I could imagine such a series of allocations to stall, if the system is strained.

@nyh just so you know, rapidjson also offers a faster option of parsing the whole document, but the programmer needs to be careful when using it. It's called in-situ parsing, and instead of allocating memory for the JSON object, it does two delicate things:
1. it ruins the string passed as an argument - e.g. given a json string `{"key":"value"}`, it will simply overwrite redundant characters like `"` with its own internal markers (hence the name - in-situ)
2. it will create the JSON object with references to the ruined string - it does not own the string however, so the programmer needs to take care about its liveness.

So, one of the options to make the parsing potentially faster would be to leverage in-situ parsing wherever possible. With minor interface changes, we could usually do that, since we don't need the raw string passed to us from HTTP layer - we're only interested in transforming it into a JSON.

Option 2, probably faster, would be to rip `Parse` out of rapidjson library and make it yieldable. The fastest way to do that would be to simply copy the implementation (it's in the header), wrap it with a seastar thread and check for `should_yield` in appropriate places (e.g. after parsing a single value). Suboption two is to rewrite `Parse` so that it returns futures. I think I'll take a quick shot at the seastar thread option, since it sounds super fast to implement. Naturally, it would be great to be able to reproduce this stall first. I'll try passing really big jsons to PutItem, maybe I'll see a stall myself.

**Comment by fgelcer** [comment]
> @nyh on the other hand, if any rjson operation would be a suspect for stalling, it would be `rjson::parse`. It parses a whole JSON document by repeatedly calling a function in recursive manner (`rapidjson::ParseValue`) without yielding and it includes allocations.
> 
> @fgelcer, could you estimate how big were the items inserted in this longevity test? If we're talking about JSONs with tens of thousands of variously sized elements inside them, I could imagine such a series of allocations to stall, if the system is strained.
> 
> @nyh just so you know, rapidjson also offers a faster option of parsing the whole document, but the programmer needs to be careful when using it. It's called in-situ parsing, and instead of allocating memory for the JSON object, it does two delicate things:
> 
> 1. it ruins the string passed as an argument - e.g. given a json string `{"key":"value"}`, it will simply overwrite redundant characters like `"` with its own internal markers (hence the name - in-situ)
> 2. it will create the JSON object with references to the ruined string - it does not own the string however, so the programmer needs to take care about its liveness.
> 
> So, one of the options to make the parsing potentially faster would be to leverage in-situ parsing wherever possible. With minor interface changes, we could usually do that, since we don't need the raw string passed to us from HTTP layer - we're only interested in transforming it into a JSON.
> 
> Option 2, probably faster, would be to rip `Parse` out of rapidjson library and make it yieldable. The fastest way to do that would be to simply copy the implementation (it's in the header), wrap it with a seastar thread and check for `should_yield` in appropriate places (e.g. after parsing a single value). Suboption two is to rewrite `Parse` so that it returns futures. I think I'll take a quick shot at the seastar thread option, since it sounds super fast to implement. Naturally, it would be great to be able to reproduce this stall first. I'll try passing really big jsons to PutItem, maybe I'll see a stall myself.

@psarna , we hare 10 columns per row, with 1024 bytes per column:
```
["bin/ycsb load dynamodb -P workloads/workloada -threads 250 -p recordcount=20000000 -p fieldcount=10 -p fieldlength=1024 -s",
"bin/ycsb run dynamodb -P workloads/workloada -threads 100 -p recordcount=20000000 -p fieldcount=10 -p fieldlength=1024 -p operationcount=10000 -s"]
```

**Comment by psarna** [comment]
update: I succeeded with stalling a reactor for 262ms by putting a million items with `PutItem`, with an identical trace. That at least proves where the problem is. I'll prepare a patch which wraps `rapidjson::Parse` in yieldable code and retest. Reproduce with `alternator-test` by adding the following case:
```python
# Test a big JSON in put_item for stalls
def test_humongous_put(test_table):
    p = random_string()
    c = random_string()
    val = dict()
    for i in range(1000000):
        val[str(i)] = 'x'
    test_table.put_item(Item={'p': p, 'c': c, 'attribute': val})


```

**Comment by psarna** [comment]
I also see that in rapidjson you can pass a `kParseIterativeFlag`, which will switch to an iterative implementation of parsing the JSON (with user-allocated stack instead of call stack), which is a very good idea. I'll add that too.

**Comment by psarna** [comment]
Unfortunately, rapidjson's parsing is object-oriented, which doesn't allow easy modification of class methods... I'll try inheritance first, and if it doesn't work as I expect it to, there's also a hacky solution we can apply.

**Comment by nyh** [comment]
> update: I succeeded with stalling a reactor for 262ms by putting a million items with `PutItem`, with an identical trace. That at least proves where the problem is. I'll prepare a patch which wraps `rapidjson::Parse` in yieldable code and retest. Reproduce with `alternator-test` by adding the following case:
> 
> ```python
> # Test a big JSON in put_item for stalls
> def test_humongous_put(test_table):
>     p = random_string()
>     c = random_string()
>     val = dict()
>     for i in range(1000000):
>         val[str(i)] = 'x'
>     test_table.put_item(Item={'p': p, 'c': c, 'attribute': val})
> ```

@psarna I don't think your test represents what @fgelcer did. It is not putting "a million items", it's one single item with one million attributes. This is an illegal operation in DynamoDB (an item is limited to 400 KB), and while I guess we should have tried harder to block this request *before* stalling - to avoid denial-of-service attacks - I don't think it explains the problem here.

**Comment by fgelcer** [comment]
> > update: I succeeded with stalling a reactor for 262ms by putting a million items with `PutItem`, with an identical trace. That at least proves where the problem is. I'll prepare a patch which wraps `rapidjson::Parse` in yieldable code and retest. Reproduce with `alternator-test` by adding the following case:
> > ```python
> > # Test a big JSON in put_item for stalls
> > def test_humongous_put(test_table):
> >     p = random_string()
> >     c = random_string()
> >     val = dict()
> >     for i in range(1000000):
> >         val[str(i)] = 'x'
> >     test_table.put_item(Item={'p': p, 'c': c, 'attribute': val})
> > ```
> 
> @psarna I don't think your test represents what @fgelcer did. It is not putting "a million items", it's one single item with one million attributes. This is an illegal operation in DynamoDB (an item is limited to 400 KB), and while I guess we should have tried harder to block this request _before_ stalling - to avoid denial-of-service attacks - I don't think it explains the problem here.

this issue happened before latest @fruch changes, where we were calling in a loop 10K keys for the whole duration of the test (in between 20M keys) - always the same 10K keys.
New code will work in a different way, and will exercise more keys (if not all of them).

**Comment by fruch** [comment]
> this issue happened before latest @fruch changes, where we were calling in a loop 10K keys for the whole duration of the test (in between 20M keys) - always the same 10K keys.
> New code will work in a different way, and will exercise more keys (if not all of them).

I'm no sure it's related to the way we used YCSB, maybe only since those were the same keys with same data, being written again and again.

**Comment by nyh** [comment]
> > this issue happened before latest @fruch changes, where we were calling in a loop 10K keys for the whole duration of the test (in between 20M keys) - always the same 10K keys.
> > New code will work in a different way, and will exercise more keys (if not all of them).
> 
> I'm no sure it's related to the way we used YCSB, maybe only since those were the same keys with same data, being written again and again.

I still don't understand this theory. Even if we keep writing to the same key again and again, I don't see how it can cause an individual request to become very big.

**Comment by psarna** [comment]
I uploaded a non-mergeable RFC with my thougthts about the topic, feel free to revise the ideas: https://github.com/scylladb/scylla/pull/5767

**Comment by fgelcer** [comment]
> > > this issue happened before latest @fruch changes, where we were calling in a loop 10K keys for the whole duration of the test (in between 20M keys) - always the same 10K keys.
> > > New code will work in a different way, and will exercise more keys (if not all of them).
> > 
> > 
> > I'm no sure it's related to the way we used YCSB, maybe only since those were the same keys with same data, being written again and again.
> 
> I still don't understand this theory. Even if we keep writing to the same key again and again, I don't see how it can cause an individual request to become very big.

it isn't a theory, just a fact on how we used the YCSB, that might have impact on how stressing few keys could cause stalls to grow big...

**Comment by slivne** [comment]
Since the stall is 3.5 seconds we need to figure this out and see what are these stalls.

**Comment by slivne** [comment]
we haven't seen this in the last 2 weeks

please provide the params used with ycsb to generate this issues.

please provide info on what is the cluster size / node types

and we will try to reproduce with that.

If it does not reproduce lets close

**Comment by fgelcer** [comment]
> we haven't seen this in the last 2 weeks
> 
> please provide the params used with ycsb to generate this issues.
> 
```bin/ycsb load dynamodb -P workloads/workloada -threads 250 -p recordcount=20000000 -p fieldcount=10 -p fieldlength=1024 -s```
```bin/ycsb run dynamodb -P workloads/workloada -threads 100 -p recordcount=20000000 -p fieldcount=10 -p fieldlength=1024 -p operationcount=10000 -s```
> please provide info on what is the cluster size / node types

3x i3.4xlarge

> 
> and we will try to reproduce with that.
> 
> If it does not reproduce lets close

**Comment by slivne** [comment]
closing this
