### ISSUE TITLE
cdc = {'enabled':true, 'ttl':'-1'} should be forbidden

### ISSUE THREAD

**Issue by jul-stas** [scylladb/scylla#5747]
Having CDC enabled while allowing CDC log writes with TTL == -1 is self-contradictory. For example, normal writes `USING TTL -1` are forbidden. This behavior should be unified.
```
cqlsh> create table ks.t4 (a int primary key, b int) with cdc = {'enabled':true,'ttl':'-1'};
cqlsh> insert into ks.t4 (a,b) values (1,1) using ttl -1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="A TTL must be greater or equal to 0"
```

**Comment by kbr-** [comment]
> and preventing CDC log writes with TTL == -1

you probably meant "and allowing".

**Comment by avikivity** [comment]
Minor, experimental feature, not backporting.
