### ISSUE TITLE
cql_tracing_test.TestCqlTracing.tracing_shutdown_test is flaky

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#5749]
The test sometimes fails with:
```
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 648, in run
    self.tearDown()
  File "/jenkins/workspace/scylla-master/byo/byo_build_tests_dtest/scylla-dtest/dtest.py", line 925, in tearDown
    self.cleanUpCluster()
  File "/jenkins/workspace/scylla-master/byo/byo_build_tests_dtest/scylla-dtest/dtest.py", line 960, in cleanUpCluster
    raise AssertionError('Unexpected errors found: {}'.format(found_errors))
```

More info here: https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/921/testReport/junit/cql_tracing_test/TestCqlTracing/dtest_not_Parallel___tracing_shutdown_test/

BYO run that failed: https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/921/
BYO run that was successful: https://jenkins.scylladb.com/job/scylla-master/job/byo/job/byo_build_tests_dtest/922/

**Comment by haaawk** [comment]
FYI @penberg @hagitsegev @avikivity @roydahan @fruch

**Comment by bhalevy** [comment]
@haaawk you didn't quote what errors the test failed with and the logs are long gone.
If they were `Timer callback failed: seastar::metrics::double_registration` (see https://github.com/scylladb/scylla/issues/5697) then adf07f971b4bbb9a076146bcfc06df82a6e1ef16 ignores them and fixes its flakiness with this respect.
Anyhow, the test failed only once in master in the last 3 months and for a different reason, so closing this issue.

**Comment by haaawk** [comment]
Sorry. Didn't thought it will take so long :D.
