### ISSUE TITLE
scylla_coredump_setup should bind-mount coredump dir on Ubuntu 18.04

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5753]
Seen on enterprise release 2019.1.4

systemd-coredump on Ubuntu 18.04 does not work properly when using a symbolic link to replace `/var/lib/systemd/coredump` to `/var/lib/scylla/coredump`.
These lines are printed on the system log:
```
systemd-coredump@0-20226-0.service: Failed to set up special execution directory in /var/lib: Not a directory 
systemd-coredump@0-20226-0.service: Failed at step STATE_DIRECTORY spawning /lib/systemd/systemd-coredump: Not a directory
```

This does not happen when using `mount --bind  /var/lib/systemd/coredump /var/lib/systemd/coredump`.

This method can be applied on all linux distros but it requires either adding a corresponding line in /etc/fstab to bind-mount the directory on boot, or run `mount --bind` when the scylla service starts.

**Comment by bhalevy** [comment]
example /etc/fstab row:
```
/var/lib/scylla/coredump /var/lib/systemd/coredump	none	defaults,bind	0 0
```

**Comment by bhalevy** [comment]
Cc @penberg @syuu1228

**Comment by bhalevy** [comment]
In addition, as suggested with @avikivity, we need to:
1. stop and disable `apport`
2. generate a coredump during setup time and make sure we see it and that it's readable by gdb (not truncated, for example).

**Comment by avikivity** [comment]
Aged out.
