### ISSUE TITLE
CQL: Scylla does not support version 3.2.1 of the specification

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#576]
I know this might be controversial, but the reasoning for me to open this bug is:

Scylla is compatible with Cassandra 2.1 (with documented exceptions). Cassandra 2.1.11 (The latest stable package in their 2.1 series) does support CQL 3.2.1. Therefore, Scylla should support CQL 3.2.1 as well.

**Comment by penberg** [comment]
The only difference between 3.2.0 and 3.2.1 is the new ``TRUNCATE X`` alias for ``TRUNCATE TABLE X``. I sent a patch that fixes that but it was rejected by @avikivity.

**Comment by avikivity** [comment]
If that is the only change we can merge it.  Bump it please.

**Comment by lmr** [comment]
@penberg Awesome, thanks!

**Comment by slivne** [comment]
We have visited this in the past and said that we want to be compatible
with a Cassandra version

Compatability with a Cassandra version does not entail only cql it has more
aspects to it.

So what Cassandra version are we compatible now that we have merged this ?

**Comment by penberg** [comment]
@slivne We have never been compatible with any exact version. We're aiming for 2.1 compatibility.

**Comment by slivne** [comment]
Not true we where aiming before this  merge to be compatible with 2.1.8
hance the 3.2.0 cql version , mbeans etc.
