### ISSUE TITLE
Coredump during gemini test

### ISSUE THREAD

**Issue by yarongilor** [scylladb/scylla#5760]
Installation details
Scylla version (or git commit hash): 3.3.rc0-0.20200207.9225b17b99c
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0ec97fbcbda97c7fb

scenario: 
Test: gemini_test.GeminiTest.test_random_load
Test details
Test-id: 0f54cd6d-6bd2-4bff-872d-a9c9655a4231
Test run by User: jenkins
Start time: 2020-02-08 00:09:59
End time: 2020-02-08 03:40:24
Gemini command:
/$HOME/gemini -d --duration 10800s --warmup 1800s -c 100 -m mixed -f --non-interactive --cql-features normal --test-cluster=172.30.0.248 --outfile /home/centos/gemini_result_da634771-62f0-4d28-a771-9f5a08e88612.log --seed 30 --oracle-cluster=172.30.0.81
Gemini version: 1.6.3
Build URL: link

Nemesis Details
Running nemesis: NoOpMonkey
System under test
Scylla v3.3.rc0 (ami-0ec97fbcbda97c7fb)
Instance type: i3.large
Number of scylladb nodes: 3
Test oracle
Scylla v3.0.11 (ami-0a49c99b529429c18)
Instance type: i3.8xlarge
Number of test oracle db nodes: 1
SCT test results
FAILED
2020-02-08 00:40:25.000: (CoreDumpEvent Severity.CRITICAL): node=Node gemini-basic-3h-3-3-db-node-0f54cd6d-1 [18.208.150.172 | 172.30.0.123] (seed: True)
corefile_url=
https://storage.cloud.google.com/upload.scylladb.com/core.scylla.996.ca1ba28bc6874818b3b37d8391db5546.3798.1581122425000000/core.scylla.996.ca1ba28bc6874818b3b37d8391db5546.3798.1581122425000000.gz
backtrace=           PID: 3798 (scylla)
           UID: 996 (scylla)
           GID: 1001 (scylla)
        Signal: 11 (SEGV)
     Timestamp: Sat 2020-02-08 00:40:25 UTC (1min 33s ago)
  Command Line: /usr/bin/scylla --blocked-reactor-notify-ms 500 --abort-on-lsa-bad-alloc 1 --abort-on-seastar-bad-alloc --abort-on-internal-error 1 --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix --io-properties-file=/etc/scylla.d/io_properties.yaml --cpuset 0-1
    Executable: /opt/scylladb/libexec/scylla
 Control Group: /
       Boot ID: ca1ba28bc6874818b3b37d8391db5546
    Machine ID: df877a200226bc47d06f26dae0736ec9
      Hostname: gemini-basic-3h-3-3-db-node-0f54cd6d-1
      Coredump: /var/lib/systemd/coredump/core.scylla.996.ca1ba28bc6874818b3b37d8391db5546.3798.1581122425000000
       Message: Process 3798 (scylla) of user 996 dumped core.
                
                Stack trace of thread 3799:
                #0  0x00007fde5596bda5 __memmove_avx_unaligned_erms (libc.so.6)
                #1  0x0000000001025a20 _ZNSt11__copy_moveILb0ELb1ESt26random_access_iterator_tagE8__copy_mIaEEPT_PKS3_S6_S4_ (scylla)
                #2  0x000000000227a95a with_linearized<fragmented_temporary_buffer::view, tracing::trace_state::raw_value_to_sstring(const cql3::raw_value_view&, const data_type&)::<lambda(bytes_view)> > (scylla)
                #3  0x000000000227abc7 _ZN7tracing11trace_state20raw_value_to_sstringERKN4cql314raw_value_viewERKN7seastar10shared_ptrIK13abstract_typeEE (scylla)
                #4  0x000000000227ae2d _ZN7tracing11trace_state37build_parameters_map_for_one_preparedERKN7seastar11checked_ptrINS1_8weak_ptrIN4cql310statements18prepared_statementEEENS1_25default_null_deref_actionEEERSt8optionalISt6vectorISt17basic_string_viewIcSt11char_traitsIcEESaISH_EEERSD_INS4_14raw_value_viewESaISM_EERKNS1_13basic_sstringIcjLj15ELb1EEE (scylla)
                #5  0x000000000227b62e _ZN7tracing11trace_state20build_parameters_mapEv (scylla)
                #6  0x000000000227c4b0 _ZN7tracing11trace_state25stop_foreground_and_writeEv (scylla)
                #7  0x000000000227d705 _ZN7tracing11trace_stateD2Ev (scylla)
                #8  0x00000000015011bc _ZN7seastar18shared_ptr_no_esftIN7tracing11trace_stateEED4Ev (scylla)
                #9  0x00000000015019c0 _ZN7service22write_response_handlerD4Ev (scylla)
                #10 0x000000000145ea16 _ZN7seastar10shared_ptrIN7service31abstract_write_response_handlerEED4Ev (scylla)
                #11 0x00000000029f45a2 _ZN7seastar7reactor9run_tasksERNS0_10task_queueE (scylla)
                #12 0x00000000029f47b0 _ZN7seastar7reactor14run_some_tasksEv (scylla)
                #13 0x0000000002a34f76 _ZN7seastar7reactor14run_some_tasksEv (scylla)
                #14 0x0000000002a43bcd _ZZN7seastar3smp9configureEN5boost15program_options13variables_mapENS_14reactor_configEENKUlvE1_clEv (scylla)
                #15 0x00000000029cee3e _ZNKSt8functionIFvvEEclEv (scylla)
                #16 0x00007fde5626c4e2 start_thread (libpthread.so.0)
                #17 0x00007fde55908693 __clone (libc.so.6)
                
                Stack trace of thread 3801:
                #0  0x00007fde5627687c read (libpthread.so.0)
                #1  0x0000000002de5966 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000002de5c52 operator() (scylla)
                #3  0x00000000029cee3e _ZNKSt8functionIFvvEEclEv (scylla)
                #4  0x00007fde5626c4e2 start_thread (libpthread.so.0)
                #5  0x00007fde55908693 __clone (libc.so.6)
                
                Stack trace of thread 3800:
                #0  0x00007fde5627687c read (libpthread.so.0)
                #1  0x0000000002de5966 _ZN7seastar11thread_pool4workENS_13basic_sstringIcjLj15ELb1EEE (scylla)
                #2  0x0000000002de5c52 operator() (scylla)
                #3  0x00000000029cee3e _ZNKSt8functionIFvvEEclEv (scylla)
                #4  0x00007fde5626c4e2 start_thread (libpthread.so.0)
                #5  0x00007fde55908693 __clone (libc.so.6)
                
                Stack trace of thread 3798:
                #0  0x00007fde559031ad syscall (libc.so.6)
                #1  0x0000000002de806a _ZN7seastar8internal13io_pgeteventsEmllPNS0_9linux_abi8io_eventEPK8timespecPK10__sigset_tb (scylla)
                #2  0x0000000002de4989 _ZN7seastar19reactor_backend_aio12await_eventsEiPK10__sigset_t (scylla)
                #3  0x0000000002de4d4d _ZN7seastar19reactor_backend_aio16wait_and_processEiPK10__sigset_t (scylla)
                #4  0x00000000029f4d85 _ZN7seastar7reactor16wait_and_processEiPK10__sigset_t (scylla)
                #5  0x0000000002a35408 _ZN7seastar7reactor3runEv (scylla)
                #6  0x000000000299b080 _ZN7seastar12app_template14run_deprecatedEiPPcOSt8functionIFvvEE (scylla)
                #7  0x000000000299c1af _ZN7seastar12app_template3runEiPPcOSt8functionIFNS_6futureIJiEEEvEE (scylla)
                #8  0x0000000000729e14 main (scylla)
                #9  0x00007fde5582e1a3 __libc_start_main (libc.so.6)
                #10 0x0000000000774d5e _start (scylla)
download_instructions=
gsutil cp gs://upload.scylladb.com/core.scylla.996.ca1ba28bc6874818b3b37d8391db5546.3798.1581122425000000/core.scylla.996.ca1ba28bc6874818b3b37d8391db5546.3798.1581122425000000.gz .
gunzip /var/lib/systemd/coredump/core.scylla.996.ca1ba28bc6874818b3b37d8391db5546.3798.1581122425000000.gz
2020-02-08 00:40:25.000: (DatabaseLogEvent Severity.CRITICAL): type=SEGMENTATION regex=segmentation line_number=5507 node=Node gemini-basic-3h-3-3-db-node-0f54cd6d-1 [18.208.150.172 | 172.30.0.123] (seed: True)
2020-02-08T00:40:25+00:00  gemini-basic-3h-3-3-db-node-0f54cd6d-1 !INFO    | scylla: Segmentation fault on shard 1.
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at /usr/include/fmt/format.h:1158
seastar::backtrace_buffer::append_backtrace() at /usr/include/fmt/format.h:1158
 (inlined by) print_with_backtrace at ./build/release/seastar/./seastar/src/core/reactor.cc:742
seastar::print_with_backtrace(char const*) at /usr/include/fmt/format.h:1158
sigsegv_action at /usr/include/fmt/format.h:1158
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3406
 (inlined by) _FUN at ./build/release/seastar/./seastar/src/core/reactor.cc:3402
?? ??:0
?? ??:0
signed char* std::__copy_move<false, true, std::random_access_iterator_tag>::__copy_m<signed char>(signed char const*, signed char const*, signed char*) at /usr/include/fmt/format.h:1158
 (inlined by) signed char* std::__copy_move_a<false, signed char const*, signed char*>(signed char const*, signed char const*, signed char*) at /usr/include/c++/9/bits/stl_algobase.h:404
 (inlined by) signed char* std::__copy_move_a2<false, signed char const*, signed char*>(signed char const*, signed char const*, signed char*) at /usr/include/c++/9/bits/stl_algobase.h:440
 (inlined by) signed char* std::copy<signed char const*, signed char*>(signed char const*, signed char const*, signed char*) at /usr/include/c++/9/bits/stl_algobase.h:474
 (inlined by) signed char* boost::range::copy<std::basic_string_view<signed char, std::char_traits<signed char> >, signed char*>(std::basic_string_view<signed char, std::char_traits<signed char> > const&, signed char*) at /usr/include/boost/range/algorithm/copy.hpp:34
 (inlined by) seastar::basic_sstring<signed char, unsigned int, 31u, false> linearized<fragmented_temporary_buffer::view>(fragmented_temporary_buffer::view const&)::{lambda(std::basic_string_view<signed char, std::char_traits<signed char> >)#1}::operator()(std::basic_string_view<signed char, std::char_traits<signed char> >) const at ././utils/fragment_range.hh:146
 (inlined by) seastar::basic_sstring<signed char, unsigned int, 31u, false> linearized<fragmented_temporary_buffer::view>(fragmented_temporary_buffer::view const&)::{lambda(std::basic_string_view<signed char, std::char_traits<signed char> >)#1} std::for_each<fragmented_temporary_buffer::view::iterator, seastar::basic_sstring<signed char, unsigned int, 31u, false> linearized<fragmented_temporary_buffer::view>(fragmented_temporary_buffer::view const&)::{lambda(std::basic_string_view<signed char, std::char_traits<signed char> >)#1}>(fragmented_temporary_buffer::view::iterator, fragmented_temporary_buffer::view::iterator, seastar::basic_sstring<signed char, unsigned int, 31u, false> linearized<fragmented_temporary_buffer::view>(fragmented_temporary_buffer::view const&)::{lambda(std::basic_string_view<signed char, std::char_traits<signed char> >)#1}) at /usr/include/c++/9/bits/stl_algo.h:3876
 (inlined by) seastar::basic_sstring<signed char, unsigned int, 31u, false> linearized<fragmented_temporary_buffer::view>(fragmented_temporary_buffer::view const&)::{lambda(std::basic_string_view<signed char, std::char_traits<signed char> >)#1} boost::range::for_each<fragmented_temporary_buffer::view, seastar::basic_sstring<signed char, unsigned int, 31u, false> linearized<fragmented_temporary_buffer::view>(fragmented_temporary_buffer::view const&)::{lambda(std::basic_string_view<signed char, std::char_traits<signed char> >)#1}>(fragmented_temporary_buffer::view const&, seastar::basic_sstring<signed char, unsigned int, 31u, false> linearized<fragmented_temporary_buffer::view>(fragmented_temporary_buffer::view const&)::{lambda(std::basic_string_view<signed char, std::char_traits<signed char> >)#1}) at /usr/include/boost/range/algorithm/for_each.hpp:102
 (inlined by) seastar::basic_sstring<signed char, unsigned int, 31u, false> linearized<fragmented_temporary_buffer::view>(fragmented_temporary_buffer::view const&) at ././utils/fragment_range.hh:145
_Z15with_linearizedIN27fragmented_temporary_buffer4viewEZN7tracing11trace_state20raw_value_to_sstringERKN4cql314raw_value_viewERKN7seastar10shared_ptrIK13abstract_typeEEEUlSt17basic_string_viewIaSt11char_traitsIaEEE_EDcRKT_OT0_ at /usr/include/fmt/format.h:1158
tracing::trace_state::raw_value_to_sstring(cql3::raw_value_view const&, seastar::shared_ptr<abstract_type const> const&) at /usr/include/fmt/format.h:1158
tracing::trace_state::build_parameters_map_for_one_prepared(seastar::checked_ptr<seastar::weak_ptr<cql3::statements::prepared_statement>, seastar::default_null_deref_action> const&, std::optional<std::vector<std::basic_string_view<char, std::char_traits<char> >, std::allocator<std::basic_string_view<char, std::char_traits<char> > > > >&, std::vector<cql3::raw_value_view, std::allocator<cql3::raw_value_view> >&, seastar::basic_sstring<char, unsigned int, 15u, true> const&) at /usr/include/fmt/format.h:1158
tracing::trace_state::build_parameters_map() at /usr/include/fmt/format.h:1158
tracing::trace_state::stop_foreground_and_write() at /usr/include/fmt/format.h:1158
tracing::trace_state::~trace_state() at /usr/include/fmt/format.h:1158
service::abstract_write_response_handler::~abstract_write_response_handler() at crtstuff.c:?
 (inlined by) seastar::internal::lw_shared_ptr_accessors_no_esft<tracing::trace_state>::dispose(seastar::lw_shared_ptr_counter_base*) at ././seastar/include/seastar/core/shared_ptr.hh:213
 (inlined by) seastar::lw_shared_ptr<tracing::trace_state>::~lw_shared_ptr() at ././seastar/include/seastar/core/shared_ptr.hh:300
 (inlined by) tracing::trace_state_ptr::~trace_state_ptr() at ././tracing/trace_state.hh:503
 (inlined by) service::abstract_write_response_handler::~abstract_write_response_handler() at ./service/storage_proxy.cc:373
service::write_response_handler::~write_response_handler() at crtstuff.c:?
 (inlined by) service::write_response_handler::~write_response_handler() at ./service/storage_proxy.cc:601
_ZN7seastar12continuationIZZNS_6futureIJEE19then_wrapped_commonILb0ES2_ZNS2_16handle_exceptionIZN7service13storage_proxy22send_to_live_endpointsEmNSt6chrono10time_pointINS_12lowres_clockENS7_8durationIlSt5ratioILl1ELl1000EEEEEEEUlNSt15__exception_ptr13exception_ptrEE1_EES2_OT_EUlSJ_E_EENS_8futurizeIT0_E4typeEOT1_ENKUlvE_clEvEUlONS_12future_stateIJEEEE_JEE15run_and_disposeEv at storage_proxy.cc:?
 (inlined by) ~<lambda> at ./service/storage_proxy.cc:2411
 (inlined by) ~<lambda> at ././seastar/include/seastar/core/future.hh:1413
 (inlined by) ~<lambda> at ././seastar/include/seastar/core/future.hh:1264
 (inlined by) ~continuation at ././seastar/include/seastar/core/future.hh:502
 (inlined by) ~continuation at ././seastar/include/seastar/core/future.hh:502
 (inlined by) run_and_dispose at ././seastar/include/seastar/core/future.hh:507
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at /usr/include/fmt/format.h:1158
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
seastar::reactor::run_some_tasks() at /usr/include/fmt/format.h:1158
 (inlined by) seastar::reactor::run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2686
seastar::smp::configure(boost::program_options::variables_map, seastar::reactor_config)::{lambda()#3}::operator()() const at /usr/include/fmt/format.h:1158
std::function<void ()>::operator()() const at /usr/include/c++/9/bits/std_function.h:690
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:52
?? ??:0
?? ??:0

Status | FAILED
-- | --
write_ops | 485848
write_errors | 1
read_ops | 100
read_errors | 0
errors | Mutation failed: unable to apply mutations to the test store: [cluster = test, query = 'INSERT INTO ks1.table1 (pk0,pk1,pk2,ck0,ck1,ck2,col0,col1,col2,col3,col4,col5,col6) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?) ']: Cannot achieve consistency level for cl QUORUM. Requires 1, alive 0

Name | Ip address | Current State | Cloud | Region
-- | -- | -- | -- | --
gemini-basic-3h-3-3-db-node-0f54cd6d-2 | 54.209.130.207 | running | aws | us-east-1
gemini-basic-3h-3-3-db-node-0f54cd6d-3 | 34.226.249.49 | running | aws | us-east-1
gemini-basic-3h-3-3-db-node-0f54cd6d-1 | 18.208.150.172 | running | aws | us-east-1
gemini-basic-3h-3-3-oracle-db-node-0f54cd6d-1 | 54.86.50.147 | running | aws | us-east-1
gemini-basic-3h-3-3-monitor-node-0f54cd6d-1 | 54.152.39.239 | running | aws | us-east-1

**Comment by bhalevy** [comment]
@gleb-cloudius can this be caused by 4893bc9139c?

**Comment by gleb-cloudius** [comment]
dup of #5700
