### ISSUE TITLE
Counters support

### ISSUE THREAD

**Issue by thefosk** [scylladb/scylla#577]
Any plans to support counters in the feature? Or is it a hard limit on the architecture, therefore not doable?

**Comment by avikivity** [comment]
We plan to support counters, but priority will be determined by demand.  So far we haven't seen many users wanting them.

**Comment by sinzone** [comment]
+1

**Comment by nosideeffects** [comment]
+1
GitHub needs a star/votes or something on Issues.

**Comment by itayadler** [comment]
👍

**Comment by meteozond** [comment]
+1

**Comment by atin65536** [comment]
+1

**Comment by mike86k** [comment]
+1

**Comment by sequoiar** [comment]
+1

**Comment by horschi** [comment]
+1

**Comment by pdziepak** [comment]
We now have a wiki page describing how counters work.
https://github.com/scylladb/scylla/wiki/Counters

**Comment by npenkov** [comment]
+1

**Comment by sequoiar** [comment]
+1

**Comment by rohitjoshi** [comment]
+1

**Comment by manigandham** [comment]
@meteozond @atin65536 @mike86k @itayadler @sequoiar @horschi @npenkov @rohitjoshi 

FYI: When voting, it's best to use the Github reactions feature to add a "thumbs up" on the issue itself - this avoids the extraneous +1 comments and allows issues to be easily sorted by the number of reactions on the main issues page.

![image](https://cloud.githubusercontent.com/assets/457226/22179530/8dd9c766-e00b-11e6-9b56-6853fc807421.png)

**Comment by dorlaor** [comment]
btw @pdziepak is actively working on it and we're confident we'll deliver it in March, probably sooner on the main branch

**Comment by rohitjoshi** [comment]
Great !! Thanks.

**Comment by Robert-Xie** [comment]
+1

**Comment by Robert-Xie** [comment]
Thanks

**Comment by blunney1** [comment]
Please update your [Features](http://docs.scylladb.com/cassandra-compatibility/#features) page to reflect this is in `master`.  Management skims these lists, ya know!

**Comment by tzach** [comment]
> Please update your Features page to reflect this is in master. Management skims these lists, ya know!

@blunney1 good point.
I will, once its part of an official release. Most users does not compile Scylla.

**Comment by RobinUS2** [comment]
When is the next stable release expected which contains counters?

**Comment by Citrullin** [comment]
I think it's not that important. Focus on the main features. It's only a nice to have. In my opinion, it's a better design to count in your streaming application and write it as aggregated data to scylla.

**Comment by avikivity** [comment]
@RobinUS2 1.7 (released in a few days) will have experimental (but working) support for counters

**Comment by RobinUS2** [comment]
@avikivity thanks, that sounds like a reasonable timeframe for us to wait for!

**Comment by avikivity** [comment]
@RobinUS2 if your fingers are itching, you can try the last release candidate: https://groups.google.com/d/topic/scylladb-users/jQtFnuCikL4/discussion

**Comment by Sam-I-Am-Not** [comment]
I'm not clear on something here.  On the compatibility page (http://docs.scylladb.com/cassandra-compatibility/) the feature of consistency level SERIAL says to follow here.  Does this issue imply support for SERIAL?

**Comment by dorlaor** [comment]
@Sam-I-Am-Not you're right, it's not related to this. @tzach please fix and point SERIAL towards LWT

**Comment by tzach** [comment]
Good catch @Sam-I-Am-Not 
Fixed.

**Comment by tomer-sandler** [comment]
Kong is now supported with Scylla 2.2. Read here: https://github.com/Kong/kong/issues/754#issuecomment-408696135
