### ISSUE TITLE
lwt: optimize learn phase by avoid a full blown query to system.truncate table

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#5771]
During learn phase we need to skip updating the paxos table if it was truncated after the transaction timestamp. Currnetly, this is done by querying the system table for the truncation timestamp and comparing the two.

Apart from being inefficient, since it has to go execute a full blown prepared statement to get the truncation time, this breaks the balance between cpu cores, since is always handled by shard 0.  Uner load, shard 0 becomes the bottleneck and all cores become underutilized. According to our measurements, even though the query itself is not significant on the performance profile, removing it leads to +10% in performance thanks to the reduced number of cross-shard calls.

**Comment by gleb-cloudius** [comment]
Small correction: it is handled by a single shard for the same base
table, not necessary shard 0 and it may be different shard for different
tables.

--
			Gleb.
