### ISSUE TITLE
gossip_control_test: cdc - get_local_streams_timestamp: tried to retrieve streams timestamp after bootstrapping, but it's not present

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5772]
Since  https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/385/testReport/nodetool_additional_test/TestNodetool/gossip_control_test/
scylla version 27b36beb4abd856d0b5ac4826b5ad7b82a798ec6
We see
```
Nodetool command '/jenkins/workspace/scylla-master/dtest-release/scylla/.ccm/scylla-repository/bcc464755227898fb67ea77d4b48dd224d3ab5b3/scylla-tools-java/bin/nodetool -h 127.0.11.1 -p 7111 enablegossip' failed; exit status: 1; stdout: nodetool: Scylla API server HTTP POST to URL '/storage_service/gossiping' failed: std::runtime_error (get_local_streams_timestamp: tried to retrieve streams timestamp after bootstrapping, but it's not present)
```
and
```
Unexpected errors found: [('node1', ["ERROR 2020-02-10 03:59:22,711 [shard 0] cdc - get_local_streams_timestamp: tried to retrieve streams timestamp after bootstrapping, but it's not present"])]
```

**Comment by bhalevy** [comment]
Cc @haaawk

**Comment by haaawk** [comment]
@kbr-

**Comment by haaawk** [comment]
@asias Could you please explain us what nodetool enablegossip does?

**Comment by bhalevy** [comment]
Fixed with 6c4f2b97170a3986aeee326292699ca07ff0b304

**Comment by asias** [comment]
> @asias Could you please explain us what nodetool enablegossip does?
> It would help us a lot.

I actually hit this issue myself when running nodetool enablegossip. 

It is used to reanble gossip after nodetool disablegossip.

**Comment by haaawk** [comment]
So we can enable/disable gossip with nodetool? Cool!

**Comment by asias** [comment]
> So we can enable/disable gossip with nodetool? Cool!

Yes. We do not usually use it though.
