### ISSUE TITLE
Proactively prune records from system.paxos table

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#5779]
In absense of topology chagnes or down nodes, we don't need to keep a committed record in system.paxos table and can prune it as soon as all participants have learned the decision.
This could reduce write amplification caused by an ongoing lwt workload, as well as reduce demands on disk footprint of system.paxos, which currently can quickly grow to hundreds of GB in size.

**Comment by kostja** [comment]
Tested with a quick and dirty patch which violates correctness and got +15-30% performance boost. The performance impact from compaction are not as sharp anymore.

**Comment by kostja** [comment]
Typical results before:
Op rate                   :    2,348 op/s  [insert: 2,348 op/s]
Partition rate            :    2,348 pk/s  [insert: 2,348 pk/s]
Row rate                  :    3,208 row/s [insert: 3,208 row/s]
Latency mean              :   12.7 ms [insert: 12.7 ms]
Latency median            :    8.3 ms [insert: 8.3 ms]
Latency 95th percentile   :   41.0 ms [insert: 41.0 ms]
Latency 99th percentile   :  111.5 ms [insert: 111.5 ms]
Latency 99.9th percentile :  531.1 ms [insert: 531.1 ms]
Latency max               : 1313.9 ms [insert: 1,313.9 ms]
Total partitions          :    100,000 [insert: 100,000]
Total errors              :          0 [insert: 0]
Total GC count            : 0
Total GC memory           : 0.000 KiB
Total GC time             :    0.0 seconds
Avg GC time               :    NaN ms
StdDev GC time            :    0.0 ms
Total operation time      : 00:00:42

Typical results after:
Results:
Op rate                   :    3,042 op/s  [insert: 3,042 op/s]
Partition rate            :    3,042 pk/s  [insert: 3,042 pk/s]
Row rate                  :    4,162 row/s [insert: 4,162 row/s]
Latency mean              :    9.7 ms [insert: 9.7 ms]
Latency median            :    7.2 ms [insert: 7.2 ms]
Latency 95th percentile   :   31.7 ms [insert: 31.7 ms]
Latency 99th percentile   :   90.1 ms [insert: 90.1 ms]
Latency 99.9th percentile :  154.9 ms [insert: 154.9 ms]
Latency max               :  231.9 ms [insert: 231.9 ms]
Total partitions          :    100,000 [insert: 100,000]
Total errors              :          0 [insert: 0]
Total GC count            : 0
Total GC memory           : 0.000 KiB
Total GC time             :    0.0 seconds
Avg GC time               :    NaN ms
StdDev GC time            :    0.0 ms
Total operation time      : 00:00:32

**Comment by kostja** [comment]
Patch used for quick-and-dirty check (the patch is obviously violating lwt correctness).
`diff --git a/db/system_keyspace.cc b/db/system_keyspace.cc
index 589fa7901..7edcf144a 100644
--- a/db/system_keyspace.cc
+++ b/db/system_keyspace.cc
@@ -2203,15 +2203,11 @@ future<> save_paxos_decision(const schema& s, const service::paxos::proposal& de
     // Erasing the last proposal is just an optimization and does not affect correctness:
     // sp::begin_and_repair_paxos will exclude an accepted proposal if it is older than the most
     // recent commit.
-    static auto cql = format("UPDATE system.{} USING TIMESTAMP ? AND TTL ? SET proposal_ballot = null, proposal = null,"
-            " most_recent_commit_at = ?, most_recent_commit = ? WHERE row_key = ? AND cf_id = ?", PAXOS);
+    static auto cql = format("DELETE FROM system.{} USING TIMESTAMP ? WHERE row_key = ? AND cf_id = ?", PAXOS);
     partition_key_view key = decision.update.key(s);
     return execute_cql_with_timeout(cql,
             timeout,
             utils::UUID_gen::micros_timestamp(decision.ballot),
-            paxos_ttl_sec(s),
-            decision.ballot,
-            ser::serialize_to_buffer<bytes>(decision.update),
             to_legacy(*key.get_compound_type(s), key.representation()),
             s.id()
         ).discard_result();
`

**Comment by kostja** [comment]
The performance improvement may obviously come from reduced commit log traffic too, which won't be there in a correct patch.

**Comment by avikivity** [comment]
in 4.0; 3.3 lwt is experimental, not backporting.
