### ISSUE TITLE
CDC: cql command: desc table <base_table_with_cdc> incorrectly display parameter cdc enable

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#5785]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

on master branch:
Scylla version 666.development-0.20200209.bcc46475522 with build-id efabf5c2dd17e58991b81f5b6bcf9f8b220db20e

Base table was altered with cdc enabled. After that the cql desc table <base table> was executed. 
Return result doesn't correctly display that cdc is enabled:
```
CREATE TABLE cdc_keyspace.test_cdc (
    userid bigint PRIMARY KEY,
    firstname text,
    lastname text
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cdc = {'enabled': 'true'}
```
On scylla 
Scylla version 3.3.rc1-0.20200209.0d0c1d43188 with build-id d6a28c1f87e959483c864fd44fe3606d484d10b6
there is not such information at all:
```
cqlsh:ks1> DESC table table1_scylla_cdc_desc 

CREATE TABLE ks1.table1_scylla_cdc_desc (
    node_ip inet,
    shard_id int,
    created_at timestamp,
    stream_id uuid,
    PRIMARY KEY ((node_ip, shard_id), created_at)
) WITH CLUSTERING ORDER BY (created_at ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'CDC description for ks1.table1'
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

```

**Comment by haaawk** [comment]
This is not a bug since last week per table _scylla_cdc_desc tables were replaced with system_distributed.cdc_description.
For more info: https://github.com/kbr-/scylla-docs/blob/cdc/using-scylla/cdc.md#querying-streams

**Comment by amoskong** [comment]
@haaawk This issue is different than Alex's email.
It's not about _scylla_cdc_desc table doesn't exist, but the "cdc" property isn't displayed in desc result.

**Comment by amoskong** [comment]
@aleksbykov what's your expected result?

**Comment by haaawk** [comment]
Right. Thanks @amoskong. This is still not an issue but expected behaivour. cdc property is an extension and that's why it's printed this way.
