### ISSUE TITLE
row::append_cell() assert protecting append invariant too harsh

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#5786]
This assert, added by 060e3f8ac2fa0afa9a9416e86760f8e53c8d65ef is supposed to make sure the invariant of the `append()` is respected, in order to prevent building an invalid row. The `assert` however proved to be too harsh, as it converts any bug causing out-of-order clustering rows into cluster unavailability. Downgrade it to `on_internal_error()`. This will still prevent corrupt data from spreading in the cluster, without the unavailability caused by the assert.

**Comment by avikivity** [comment]
Backported to 3.3, 3.2, 3.1
