### ISSUE TITLE
Requests to alternator failing while a node is decommissioning

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#5787]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200209.bcc46475522
Cluster size: 3 
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0b464ba1fef4f6228

## Summary
Requests to alternator failing while a node is decommissioning 
with the following error:
```
801384 [Thread-237] ERROR site.ycsb.db.DynamoDBClient  -com.amazonaws.AmazonServiceException: Internal server error: exceptions::mutation_write_failure_exception (Operation failed for alternator.usertable - received 0 responses and 1 failures from 2 CL=LOCAL_SERIAL.) (Service: AmazonDynamoDBv2; Status Code: 500; Error Code: Internal Server Error; Request ID: null)
```
**NOTE:** it was while trying to use the DNS server solutions, and it wasn't exactly working as we expected yet, hence requests are still sent out to this node by YCSB.

maybe this node isn't returned in alternator /localnodes API, but I think we should also stop the alternator service in all the places the CQL/thirft service is going down (in stopping scylla, decommision and etc.)

## Logs
```
hydra investigate show-monitor 89d30cf8-7f61-4401-aa70-bd82fabbb0c0
hydra investigate show-logs 89d30cf8-7f61-4401-aa70-bd82fabbb0c0
```

* **db-cluster**: https://cloudius-jenkins-test.s3.amazonaws.com/89d30cf8-7f61-4401-aa70-bd82fabbb0c0/20200211_023545/db-cluster-89d30cf8.zip                                                                                                 
* **loader-set**: https://cloudius-jenkins-test.s3.amazonaws.com/89d30cf8-7f61-4401-aa70-bd82fabbb0c0/20200211_023545/loader-set-89d30cf8.zip                                                                                                 
* **monitor-set**: https://cloudius-jenkins-test.s3.amazonaws.com/89d30cf8-7f61-4401-aa70-bd82fabbb0c0/20200211_023545/monitor-set-89d30cf8.zip                                                                                                
* **sct-runner**: https://cloudius-jenkins-test.s3.amazonaws.com/89d30cf8-7f61-4401-aa70-bd82fabbb0c0/20200211_023545/sct-runner-89d30cf8.zip 
* **grafana**
  * https://cloudius-jenkins-test.s3.amazonaws.com/89d30cf8-7f61-4401-aa70-bd82fabbb0c0/20200211_023249/grafana-screenshot-alternator-20200211_023411-alternator-3h-alternat-monitor-node-89d30cf8-1.png
  * https://cloudius-jenkins-test.s3.amazonaws.com/89d30cf8-7f61-4401-aa70-bd82fabbb0c0/20200211_023249/grafana-screenshot-overview-20200211_023334-alternator-3h-alternat-monitor-node-89d30cf8-1.png
   * https://cloudius-jenkins-test.s3.amazonaws.com/89d30cf8-7f61-4401-aa70-bd82fabbb0c0/20200211_023249/grafana-screenshot-scylla-per-server-metrics-nemesis-20200211_023256-alternator-3h-alternat-monitor-node-89d30cf8-1.png

**Comment by gleb-cloudius** [comment]
@slivne I am not sure what I have to do with alternator

**Comment by slivne** [comment]
Internal server error: exceptions::mutation_write_failure_exception
(Operation failed for alternator.usertable - received 0 responses and
1 failures from 2 CL=LOCAL_SERIAL.)

**Comment by gleb-cloudius** [comment]
I have not what kind of query alternator runs. I need some kind of assessment from alternator people what kind of query they executed against what kind of table (RF specifically). Can it be that RF=2?

**Comment by fruch** [comment]
just to clearify, on CQL when node is currently decommissioning, it closing the CQL port, right ?

**Comment by slivne** [comment]
what is the schema can you provide it

**Comment by fruch** [comment]
```
cqlsh> DESC KEYSPACE alternator ;

CREATE KEYSPACE alternator WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;

CREATE TABLE alternator.usertable (
    p text,
    c text,
    ":attrs" map<text, blob>,
    PRIMARY KEY (p, c)
) WITH CLUSTERING ORDER BY (c ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

scylla_tags = {}
```

**Comment by gleb-cloudius** [comment]
@fruch did you have a setup with 3 nodes and you decommissioned one? This is not suppose to work.

**Comment by gleb-cloudius** [comment]
Well, it is not that it is not suppose to work - we still have a quorum but we do not have HA - each hiccup will cause  requests to fail.

**Comment by fruch** [comment]
yep, sorry about that, we added nemesis to this test, but forgot to enlarge the cluster to accommodate it

**Comment by gleb-cloudius** [comment]
On Tue, Feb 11, 2020 at 03:48:23AM -0800, Israel Fruchter wrote:
> yep, sorry about that, we added nemesis to this test, but forgot to enlarge the cluster to accommodate it
> 
I see some nodes are overloaded as well and have a lot of errors. Also
the report is supper unclear: there are 5 directories in the
db-cluster.zip, some of then contain only messages.log for some reason.
How do I suppose to know which directory belongs to what node? Which one
was decommissioned? Why database.log is in tar.gz and not just gz (there
is no point to tar one file). So many questions...

--
			Gleb.

**Comment by slivne** [comment]
@fruch can you please help gleb find the missing info

**Comment by fruch** [comment]
@slivne  I thought the conclusion was that we didn't have enough nodes for running nemsis, we decommissioned one node of 3 while RF=3.

I think we could close this one.

**Comment by nyh** [comment]
@gleb-cloudius you asked what kind of requests Alternator makes, well, writes always use CL=LOCAL_QUORUM and a cas() which (in the YCSB write-only case) doesn't read anything, but still does the write through cas() with LOCAL_SERIAL serialization. I assume that in the message "received 0 responses and 1 failures from 2 CL=LOCAL_SERIAL", the "2" is the CL (i.e., quorum for RF=3) and "CL=LOCAL_SERIAL" refers to the LWT CL option - it would be nice if this message could be changed to be more consistent (it's a Scylla exception, not Alternator's).

But let's return to @fruch's question in the beginning of this thread. He suggested that while a node is being decomissioned, its CQL server is brought down, and we forgot to do this for the Alternator HTTP server. @psarna, do you know if it's true? @fruch did you send the failing requests to the node being decomissioned - not to the other non-decomissioning node?

**Comment by fruch** [comment]
@fruch I was using the DNS solution here, So it was keep sending, without me having direct control to which node the requests are going.

I'll take a look tomorrow again if any print in the logs suggesting from which node this failure originate.

**Comment by gleb-cloudius** [comment]
On Sun, Feb 16, 2020 at 12:17:01PM -0800, Israel Fruchter wrote:
> @slivne  I thought the conclusion was that we didn't have enough nodes for running nemsis, we decommissioned one node of 3 while RF=3.
> 
> I think we could close this one.
> 
Yes. Also the two other nodes were overloaded.

--
			Gleb.

**Comment by slivne** [comment]
Before closing

Putting aside Alternator:

@gleb-cloudius If a cluster has RF=3 and 3 nodes and we decommission a single node - can't we run LWT queries ? I think we should be able to (regular reads and writes with QUORUM consistency do work in this scenario).

If the nodes were overloaded and that is the source of the issue then we can close this.

**Comment by gleb-cloudius** [comment]
On Mon, Feb 24, 2020 at 11:47:56PM -0800, Shlomi Livne wrote:
> Before closing
> 
> Putting aside Alternator:
> 
> @gleb-cloudius If a cluster has RF=3 and 3 nodes and we decommission a single node - can't we run LWT queries ? I think we should be able to (regular reads and writes with QUORUM consistency do work in this scenario).
> 
Of course, but any error by any remaining node will cause it to fail (no HA).

> If the nodes were overloaded and that is the source of the issue then we can close this. 
> 
Yes, both remaining nodes had errors due to overload.

--
			Gleb.

**Comment by slivne** [comment]
@kostja lets add a test of 3 nodes RF=3 and decomission one node and see that LWT still works.

Once we have this test in dtest we can close this issue.

For alterantor I don;t think we need anything.

**Comment by kostja** [comment]
These are items 3.3 and 3.4 from the test plan (dtest) and 4.2, 4.3 (scylla-cluster-test, stress test). Both in patch-pending. Closing then.
