### ISSUE TITLE
CQL: Scylla crashes with setting static columns + frozen sets

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#579]
Reproducer:

    CREATE KEYSPACE IF NOT EXISTS lmr_test_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
    CREATE TABLE lmr_test_keyspace.table_static_column_usage_test (a int, b int, c frozen<map<set<int>, list<int>>> static, d int, PRIMARY KEY (a, b));
    INSERT INTO lmr_test_keyspace.table_static_column_usage_test (a, b, c, d) VALUES (0, 0, {}, 0);
    SELECT * FROM lmr_test_keyspace.table_static_column_usage_test;

    Column family 'table_static_column_usage_test' not found

Exit cqlsh, then try to execute it again. You'll get:

    Connection error: ('Unable to connect to any servers', {'127.0.0.1': ValueError("Don't know how to parse type string u'org.apache.cassandra.db.marshal.CompositeType(org.apache.cassandra.db.marshal.Int32Type,org.apache.cassandra.db.marshal.UTF8Type,org.apache.cassandra.db.marshal.ColumnToCollectionType))': list index out of range",)})

Expected behavior:

    Connected to Test Cluster at 127.0.0.1:9042.
    [cqlsh 5.0.1 | Cassandra 2.1.11 | CQL spec 3.2.1 | Native protocol v3]
    Use HELP for help.
    cqlsh>     CREATE KEYSPACE IF NOT EXISTS lmr_test_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
    cqlsh>     CREATE TABLE lmr_test_keyspace.table_static_column_usage_test (a int, b int, c frozen<map<set<int>, list<int>>> static, d int, PRIMARY KEY (a, b));
    cqlsh>     INSERT INTO lmr_test_keyspace.table_static_column_usage_test (a, b, c, d) VALUES (0, 0, {}, 0);
    cqlsh>     SELECT * FROM lmr_test_keyspace.table_static_column_usage_test;

     a | b | c | d
    ---+---+---+---
     0 | 0 |  {} | 0

    (1 rows)

**Comment by lmr** [comment]
This is related to #559.

**Comment by penberg** [comment]
I think the bug is related to how we encode the type (or validator) of the column ``c``.

In Cassandra, the table schema is stored as follows:

```
cqlsh> SELECT * FROM system.schema_columns WHERE keyspace_name = 'lmr_test_keyspace';

 keyspace_name     | columnfamily_name              | column_name | component_index | index_name | index_options | index_type | type           | validator
-------------------+--------------------------------+-------------+-----------------+------------+---------------+------------+----------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 lmr_test_keyspace | table_static_column_usage_test |           a |            null |       null |          null |       null |  partition_key |                                                                                                                                                                                                                   org.apache.cassandra.db.marshal.Int32Type
 lmr_test_keyspace | table_static_column_usage_test |           b |               0 |       null |          null |       null | clustering_key |                                                                                                                                                                                                                   org.apache.cassandra.db.marshal.Int32Type
 lmr_test_keyspace | table_static_column_usage_test |           c |               1 |       null |          null |       null |         static | org.apache.cassandra.db.marshal.FrozenType(org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.Int32Type),org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.Int32Type)))
 lmr_test_keyspace | table_static_column_usage_test |           d |               1 |       null |          null |       null |        regular |                                                                                                                                                                                                                   org.apache.cassandra.db.marshal.Int32Type
```

The ``cqlsh`` error message from Scylla suggests that we encode the same type as ``org.apache.cassandra.db.marshal.ColumnToCollectionType``. The only place where I could find an occurence of that is in ``schema.cc::to_string()`` if we have a compound schema (not sure what that means).

Applying the following patch fixes the problem:

```
diff --git a/schema.cc b/schema.cc
index 071341c..48fc58c 100644
--- a/schema.cc
+++ b/schema.cc
@@ -556,11 +556,7 @@ static sstring compound_name(const schema& s) {
 }
 
 sstring to_sstring(const schema& s) {
-    if (!s.is_compound()) {
         return s.regular_column_name_type()->name();
-    } else {
-        return compound_name(s);
-    }
 }
 
 bool check_compound(sstring comparator) {
```

However, I don't really understand what a "compound schema" even means nor do I understand why it's set for the table.

Ping @pdziepak @tgrabiec

**Comment by pdziepak** [comment]
I think the problem is that `compound_name()` doesn't distinguish between frozen and 'normal' collections. In case of the former it shouldn't add them to the comparator. I will try to send a patch for that soon.
