### ISSUE TITLE
lwt: add cql tests for CDC, INSERT JSON, and USING TTL

### ISSUE THREAD

**Issue by alecco** [scylladb/scylla#5792]
Add CQL tests for WITH CDC, INSERT JSON, and USING TTL query options.

**Comment by slivne** [comment]
@alecco is this merged ?

**Comment by alecco** [comment]
> @alecco is this merged ?

@slevine no, I need to resend a patch

**Comment by alecco** [comment]
> > @alecco is this merged ?
> 
> @slivne no, I need to resend a patch

@slivne sent patch, waiting for queue/merge
