### ISSUE TITLE
Materialized view updates with future partition tombstones are not correctly generated

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#5793]
When the base table does not have any rows, but it does have a partition tombstone with a given timestamp, inserting a base row with a smaller timestamp will generate an incorrect materialized view update - even though the base table contains 0 rows, because the only row we inserted was covered by a partition tombstone with higher timestamp, we can observe a materialized view row.

Reproducing code, courtesy of @eliransin:
```cql
CREATE KEYSPACE test WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE test.test (
    a int PRIMARY KEY,
    b int,
    c int,
    d int,
    e int
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE MATERIALIZED VIEW test.test_by_b_view AS
    SELECT *
    FROM test.test
    WHERE a IS NOT null AND b IS NOT null
    PRIMARY KEY (b, a)
    WITH CLUSTERING ORDER BY (a ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cqlsh> delete from test.test using timestamp 10 where a=1;
cqlsh> select * from test.test; 

 a | b | c | d | e
---+---+---+---+---

(0 rows)
cqlsh> select * from test.test_by_b_view ;

 b | a | c | d | e
---+---+---+---+---

(0 rows)
cqlsh> insert into test.test (a,b,c,d,e) values (1,2,3,4,5) using timestamp 8;
cqlsh> select * from test.test;

 a | b | c | d | e
---+---+---+---+---

(0 rows)
cqlsh> select * from test.test_by_b_view ;

 b | a | c | d | e
---+---+---+---+---
 2 | 1 | 3 | 4 | 5

(1 rows)
```

I'll assign myself to this issue, since I'm pretty sure I pinpointed where to place the fix.

**Comment by nyh** [comment]
Started backporting to 3.3, 3.2 and 3.1 (I'm not sure a backport to 3.1 is required because 3.3 RC is already out, but @psarna specifically requested for one).

**Comment by nyh** [comment]
Cherry-picking commit e93c54e83798190a0d0bbc80c11fb37dcb604132:
Backported to next-3.2.
Unfortunately couldn't backport to next-3.1 (configure.py making some opaque complaints about my uild system), nor to next-3.3 (next-3.3 branch contains compilations errors...).
So leaving the "Backport candidate" tag for now. Backport to 3.3 and 3.1 still needs to be done.

**Comment by nyh** [comment]
Backported to next-3.3 as well.
If we could agree that now that 3.3 is out as RC we will not have further 3.1 releases, we are done with this backport-candidate. Otherwise, we still need to backport to next-3.1 too.

**Comment by avikivity** [comment]
We do need to backported to 3.1. 3.1 support will stop only after 3.3 is released.

**Comment by avikivity** [comment]
3.1 was aged out.
