### ISSUE TITLE
Impossible WHERE condition returns a non-empty slice

### ISSUE THREAD

**Issue by dekimir** [scylladb/scylla#5799]
Scylla:
```cql
cqlsh:ks> CREATE TABLE t1 ( p int PRIMARY KEY, r int );
cqlsh:ks> INSERT INTO t1 (p, r) VALUES (1, 10);
cqlsh:ks> INSERT INTO t1 (p, r) VALUES (2, 20);
cqlsh:ks> SELECT * FROM t1 WHERE r>10 AND r<10 ALLOW FILTERING ;

 p | r
---+----
 2 | 20
---MORE---
(1 rows)
```

Cassandra:
```cql
cqlsh:ks> CREATE TABLE t1 ( p int PRIMARY KEY, r int );
cqlsh:ks> INSERT INTO t1 (p, r) VALUES (1, 10);
cqlsh:ks> INSERT INTO t1 (p, r) VALUES (2, 20);
cqlsh:ks> SELECT * FROM t1 WHERE r>10 AND r<10 ALLOW FILTERING ;

 p | r
---+---

(0 rows)
```

**Comment by denesb** [comment]
I bet this can be reproduced with token restrictions as well. We do not detect such impossible ranges.

**Comment by avikivity** [comment]
@dekimir "Backport candidate" labels are added automatically when an issue is closed.

**Comment by avikivity** [comment]
Backported to 4.0, 4.1, 4.2.

**Comment by avikivity** [comment]
@penberg why is the bot adding the "backport candidate" label?

**Comment by roydahan** [comment]
@dekimir do you know if it has a dtest?

**Comment by dekimir** [comment]
> @dekimir do you know if it has a dtest?

I don't know, but I hope it doesn't.  Dtests duplicating unit tests is a constant source of headaches for me, without discernible benefits.

**Comment by roydahan** [comment]
ok, I agree unit test is enough in this case.
