### ISSUE TITLE
Active nodes wrongfully marked as DOWN 

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#5800]
User reported an issue that after a node restart, the restarted node
is marked as DOWN by other nodes in the cluster while the node is up
and running normally.

**Comment by pidiaquez** [comment]
Hi Team

     Customer asks if will it be delivered as a patch for 2019.1.2 Enterprise version they have? Or will it go to 2020? Or else...

Thanks in advance

Pablo

**Comment by avikivity** [comment]
Will backport, but later after it gets some more mileage in master.
