### ISSUE TITLE
Abort reverse queries that read too much data

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#5804]
Reverse queries have to read the entire partition into memory to reverse its rows. This means that a big enough partition, or a handful of them can single handedly cause OOM and crash the node.

The proper solution would be to implement reading in reverse from the disk, however that is a big effort. Until that is implemented we should cap the memory we are willing to use for a to-be-reversed partition, and if the read data goes above the threshold, abort the read.

A good value for this limit would be 1MB, which is our current page size.

**Comment by slivne** [comment]
seems similar to: #1413 

we have a counter for this  #3492
