### ISSUE TITLE
CQL: Scylla does not support frozen map inside a map

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#581]
Consider the following example that creates a column that is a map that contains a frozen map:

    CREATE KEYSPACE IF NOT EXISTS lmr_test_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
    CREATE TABLE lmr_test_keyspace.table_test_frozen_map_in_map (k int primary key, m map<frozen<map<int, int>>, int>);
    INSERT INTO lmr_test_keyspace.table_test_frozen_map_in_map (k, m) VALUES (1, {{1 : 1, 2 : 2} : 1});

This insert in scylla will give you a:

    ServerError: <ErrorMessage code=0000 [Server error] message="not implemented">

As I understand, scylla has support to frozen maps, frozen list in map, frozen list in set, frozen list in list. It needs to support frozen map inside a map.

**Comment by penberg** [comment]
Fixed by https://github.com/scylladb/scylla/commit/63bdeb65f25ad037c84804bb250939bccfca7184
