### ISSUE TITLE
raid_setup script does not creates all directories

### ISSUE THREAD

**Issue by pgacek** [scylladb/scylla#5811]
*Installation details*
```
root@scylladb-generic3-s-0:/opt/scylladb/scripts# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

root@scylladb-generic3-s-0:/opt/scylladb/scripts# scylla --version
3.2.1-0.20200122.e3e301906d5

single cluster node - it does not matter
```

While trying to run `scylla_setup --disks /dev/disk --nic eth0` on dedicated data disk the io tune setup fails because of missing of hints directory

```
Yes - let iotune study my disk(s). Note that this action will take a few minutes. No - skip this step.
[YES/no]
tuning /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/00000000-0001-8899-0000-000000000000/host3/target3:0:1/3:0:1:0/block/sdb/sdb1
tuning /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/00000000-0001-8899-0000-000000000000/host3/target3:0:1/3:0:1:0/block/sdb
already tuned: /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/00000000-0001-8899-0000-000000000000/host3/target3:0:1/3:0:1:0/block/sdb/queue/nomerges
tuning /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/00000000-0001-8899-0000-000000000000/host3/target3:0:1/3:0:1:0/block/sdb/sdb1
ERROR:root:/var/lib/scylla/hints was not found. Please check the configuration and run scylla_io_setup again.
IO configuration setup failed. Press any key to continue...
```

I think for fix the issue is just as easy as add missing directory to this file
https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_raid_setup#L134

**Comment by slivne** [comment]
I don;t think thats the solution - in developer mode there is no need to run scylla_io_setup and scylla should create the directories.

**Comment by slivne** [comment]
yet you maybe correct this is from inside scylla_io_setup (https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_io_setup#L102) that does collect the directories to check.

So there is a bug - and I think it works for everyone else, since no one uncomments the line in scylla.yaml
```
# hints_directory: /var/lib/scylla/hints
```

so when scylla_io_setup runs it does not find a configuration for hints in the yaml file and so that is not added to the list of directories to check io_tune on. 

What you can do for now to workaround this is not to comment `hints_directory` in the scylla.yaml since you are using the default.

**Comment by pgacek** [comment]
> yet you maybe correct this is from inside scylla_io_setup (https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_io_setup#L102) that does collect the directories to check.
> 
> So there is a bug - and I think it works for everyone else, since no one uncomments the line in scylla.yaml
> 
> ```
> # hints_directory: /var/lib/scylla/hints
> ```
> 
> so when scylla_io_setup runs it does not find a configuration for hints in the yaml file and so that is not added to the list of directories to check io_tune on.
> 
> What you can do for now to workaround this is not to comment `hints_directory` in the scylla.yaml since you are using the default.

and there is my config scylla.yaml

It's not commented.

```
# The directory where hints files are stored if hinted handoff is enabled.
hints_directory: /var/lib/scylla/hints
```

**Comment by avikivity** [comment]
Backported to 3.3. 4.0 had it already.
