### ISSUE TITLE
/etc/sysctl.d/99-scylla-coredump.conf is not valid on CentOS8

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#5818]
On scylla_coredump_setup, we creates /etc/sysctl.d/99-scylla-coredump.conf by following pattern:
```
kernel.core_pattern="|/usr/lib/systemd/systemd-coredump %p %u %g %s %t %e"
```
so we have 6 arguments, but this is not correct on CentOS8, it causes an error:
```
Feb 16 14:51:51 ip-10-0-0-47.ec2.internal systemd-coredump[6199]: Not enough arguments passed by the kernel (6, expected 7).
```
Because new argument produced at systemd v238:
https://github.com/systemd/systemd/commit/f45b8015513d38ee5f7cc361db9c5b88c9aae704#diff-06f104abc8d8c746be4ecc40858585d4

Also, CentOS8 uses systemd-coredump by default, so we don't need to change kernel.core_pattern at all.

**Comment by tzach** [comment]
@slivne CentOS support is 3.3

**Comment by slivne** [comment]
Please backport to 3.3, so we can consider if to add Centos 8.0 support in 3.3

**Comment by avikivity** [comment]
CentOS 8 did not make it to 3.3, so this need not be backported.
