### ISSUE TITLE
CQL: Scylla does not support frozen map inside a set

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#582]
Consider the following example that creates a column that is a set that contains a frozen map:

    CREATE KEYSPACE IF NOT EXISTS lmr_test_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
    CREATE TABLE lmr_test_keyspace.table_test_frozen_map_in_set (k int primary key, s set<frozen<map<int, int>>>);
    INSERT INTO lmr_test_keyspace.table_test_frozen_map_in_set (k, s) VALUES (1, {{1 : 1, 2 : 2}});

This insert in scylla will give you a:

    ServerError: <ErrorMessage code=0000 [Server error] message="not implemented">

As I understand, scylla has support to frozen maps, frozen list in map, frozen list in set, frozen list in list. It needs to support frozen map inside a set.

**Comment by penberg** [comment]
Fixed by https://github.com/scylladb/scylla/commit/63bdeb65f25ad037c84804bb250939bccfca7184.
