### ISSUE TITLE
User defined functions run in the default scheduling group

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#5827]
seastar::async() doesn't inherit the current scheduling group by default.

In selection.hh:
```
    template<typename Func>
    auto with_thread_if_needed(Func&& func) {
        if (_selectors->requires_thread()) {
            return async(std::move(func));
        } else {
            return futurize_apply(std::move(func));
        }
    }
```

```
cql3/functions/user_function.cc: bool user_function::requires_thread() const { return true; }
```

**Comment by espindola** [comment]
I intend to remove the requires_thread, but I see that you have a patch changing async to inherit the current scheduling group, which is probably also a good thing.

**Comment by raphaelsc** [comment]
On Tue, Feb 18, 2020 at 7:54 PM Rafael Ávila de Espíndola <
notifications@github.com> wrote:

> I intend to remove the requires_thread, but I see that you have a patch
> changing async to inherit the current scheduling group, which is probably
> also a good thing.
>
turns out async already inherits the current scheduling group meaning this
issue can probably be closed.
