### ISSUE TITLE
scylla_setup without --nic shows up strange error when eth0 does not exists

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#5828]
Since we set 'eth0' as default NIC name, we get following error when running scylla_setup in non-interactive mode without --nic parameter:
```
$ sudo scylla_setup --setup-nic-and-disks --no-raid-setup --no-verify-package --no-io-setup
NIC eth0 doesn't exist.
```
It looks strange since user actually does not specified 'eth0', they might forget to specify --nic.
I think we should shows up usage, when eth0 is not available on the system.

**Comment by avikivity** [comment]
Aged out.
