### ISSUE TITLE
offline install with relocated packages

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#5830]
*Installation details*
Scylla version (or git commit hash): master
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

I tried to offline install scylla on a GCE (centos7) instance by relocated packages, it's completed, but not a good practice.

It's not good to install scylla by relocated packages in production environment with firewall limit. There are some external setup or attribute change in RPM or Deb installation, it's not enough to run the install.sh in all relocated packages. The independency is also a big problem, we can't solve them one by one manually in production env.

The current recommended offline installer (https://github.com/scylladb/scylla/wiki/Offline-Installer) depends on RPM or deb, and all dependency packages will be prepared.

But the install.sh in relocated packages only copy the files to right directories without setting the attributes (ownership, permission). And the dependencies have to be solved manually.

My Procedure (Offline installation with relocated packages):
- https://docs.google.com/document/d/11eg74ojQs_4Zud7aIND8Grdhd0cE2DLDcNtFY4NMUQc/edit?usp=sharing

It seems original offline install script is better. If we want to switch offline install to use relocate packages, we need to improve the setup and solve the dependency issue.

@syuu1228 @slivne @roydahan

**Comment by amoskong** [comment]
The original offline installer depends on RPM or deb packages, so it's also easy to upgrade or rollback.

**Comment by slivne** [comment]
@amoskong I need the list of packaged that the current version dependes on 

Java can be installed externally

Scylla-Server should not have any external dependency
Scylla-JMX - what are the additional missing dependencies (aside of Java)
Scylla-Tools-Java whar are the additional dependencies (aside of Java)

**Comment by syuu1228** [comment]
Currently install.sh does not have feature to add scylla user/group and chown /var/lib/scylla to scylla:scylla, since root-mode is used for packaging, we don't want create user on package build time.
Also there is no dependency resolution on install time (almost all dependencies are provided by relocatable package, but there are few exceptions), we don't want to do it on packaging build time neither.

So, we probably need to add ---packaging option to install.sh, do following work when the option NOT specified:
 - add scylla user/group
 - chown /var/lib/scylla
 - resolve dependencies

Then .rpm/.deb build script call install.sh --packaging, offline user can call install.sh without the option.

**Comment by syuu1228** [comment]
Seems like scylla_post_install.sh should be called too, since it provides /etc/systemd conf files.
But I guess we may able to move /etc/systemd setup to scylla_setup, if we requires to run scylla_setup before starting scylla-server, anyway.

**Comment by syuu1228** [comment]
Adding more note: we also need systemctl daemon-reload, but scylla_post_install.sh should call it anyway so we don't have to call it twice.

**Comment by syuu1228** [comment]
To merge separated relocatable package into single tar.gz, we need to merge "[RFCv2] join all relocatable packages into single unified package" on ML.

**Comment by amoskong** [comment]
> @amoskong I need the list of packaged that the current version dependes on
> 
> Java can be installed externally
> 
> Scylla-Server should not have any external dependency
> Scylla-JMX - what are the additional missing dependencies (aside of Java)
> Scylla-Tools-Java whar are the additional dependencies (aside of Java)

Dependencies:

- Scylla
  - kernel >= 3.10.0-514
  - mdadm
  - Xfsprogs
  - kmod
- Scylla-tools:
  - python2
  - PyYAML (/usr/lib64/python2.7/site-packages/_yaml.so)
  - java-1.8.0-openjdk-headless
- Scylla-jmx
  - java-1.8.0-openjdk-headless

**Comment by amoskong** [comment]
I collected some items from spec file of scylla/scylla-tools/scylla-jmx, additional setup after running install.sh in relocatable packages:

- prepare: add scylla user/group
- post: 
  - /opt/scylladb/scripts/scylla_coredump_setup
  - scylla_post_install.sh
  - ln -sfT /etc/scylla /var/lib/scylla/conf
  - %post conf in scylla.yaml
     "api_ui_dir: /opt/scylladb/swagger-ui/dist/" 
     "api_doc_dir: /opt/scylladb/api/api-doc/" 
  - post kernel-conf
    /usr/lib/systemd/systemd-sysctl 99-scylla-sched.conf 
    /usr/lib/systemd/systemd-sysctl 99-scylla-aio.conf
    /usr/lib/systemd/systemd-sysctl 99-scylla-vm.conf
  - chown /var/lib/scylla
  - resolve dependencies
  - systemctl daemon-reload
- scylla-tools:
  - mkdir {_sysconfdir}/bash_completion.d
  - cd pylib && python setup.py install --no-compile

**Comment by amoskong** [comment]
> Currently install.sh does not have feature to add scylla user/group and chown /var/lib/scylla to scylla:scylla, since root-mode is used for packaging, we don't want create user on package build time.
> Also there is no dependency resolution on install time (almost all dependencies are provided by relocatable package, but there are few exceptions), we don't want to do it on packaging build time neither.
> 
> So, we probably need to add ---packaging option to install.sh, do following work when the option NOT specified:
> 
> * add scylla user/group

> * chown /var/lib/scylla

Is it enough? there are many more attributes update in rpm spec file:

%attr(0755,root,root) %dir %{_sysconfdir}/scylla
%attr(0755,scylla,scylla) %dir %{_sharedstatedir}/scylla/
%attr(0755,scylla,scylla) %dir %{_sharedstatedir}/scylla/data
%attr(0755,scylla,scylla) %dir %{_sharedstatedir}/scylla/commitlog
%attr(0755,scylla,scylla) %dir %{_sharedstatedir}/scylla/hints
%attr(0755,scylla,scylla) %dir %{_sharedstatedir}/scylla/view_hints
%attr(0755,scylla,scylla) %dir %{_sharedstatedir}/scylla/coredump
%attr(0755,scylla,scylla) %dir %{_sharedstatedir}/scylla-housekeeping

> * resolve dependencies
> 
> Then .rpm/.deb build script call install.sh --packaging, offline user can call install.sh without the option.

**Comment by syuu1228** [comment]
> > Currently install.sh does not have feature to add scylla user/group and chown /var/lib/scylla to scylla:scylla, since root-mode is used for packaging, we don't want create user on package build time.
> > Also there is no dependency resolution on install time (almost all dependencies are provided by relocatable package, but there are few exceptions), we don't want to do it on packaging build time neither.
> > So, we probably need to add ---packaging option to install.sh, do following work when the option NOT specified:
> > 
> > * add scylla user/group
> 
> > * chown /var/lib/scylla
> 
> Is it enough? there are many more attributes update in rpm spec file:
> 
> %attr(0755,root,root) %dir %{_sysconfdir}/scylla
> %attr(0755,scylla,scylla) %dir %{_sharedstatedir}/scylla/
> %attr(0755,scylla,scylla) %dir %{_sharedstatedir}/scylla/data
> %attr(0755,scylla,scylla) %dir %{_sharedstatedir}/scylla/commitlog
> %attr(0755,scylla,scylla) %dir %{_sharedstatedir}/scylla/hints
> %attr(0755,scylla,scylla) %dir %{_sharedstatedir}/scylla/view_hints
> %attr(0755,scylla,scylla) %dir %{_sharedstatedir}/scylla/coredump
> %attr(0755,scylla,scylla) %dir %{_sharedstatedir}/scylla-housekeeping
It basically chown scylla:scylla -R /var/lib/scylla.
(Also chown scylla:scylla -R /var/lib/scylla-housekeeping, too)

> 
> > * resolve dependencies
> > 
> > Then .rpm/.deb build script call install.sh --packaging, offline user can call install.sh without the option.

**Comment by dyasny** [comment]
don't forget node_exporter and the manager agent
