### ISSUE TITLE
alternator: limit huge requests

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5832]
As written in https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html, DynamoDB has a strict 400KB limit on an item size. This naturally limits the size of CRUD requests (GetItem, PutItem, UpdateItem, DeleteItem), whose request and/or response may contain the entire item - which is now limited in size. BatchGetItem and BatchWriteItems have higher limits on their response and request size, respectively, but there is still a limit: 16 MB.

In Alternator it is harder to enforce a limit on the total item size if it is written piecemeal in multiple UpdateItem operations (note that even if LWT is used, we don't always read the item before updating it). Nevertheless we could more easily start with refusing oversized single operations such as PutItem and BatchWriteItem. One of the problems with oversized operations is that the code currently (see #5742) parses the entire request without yielding, which can hurt latency of other requests and can also become a denial-of-service attack on a (future) multi-tenant setup. Another problem is that today we read the entire request up-front so if we want to reject oversized HTTP requests, we should do this without reading the entire request to a buffer up-front.

This may also be related to issue #5029 - in admission control we may want to have some estimated limits on the size of the request before handling it.

**Comment by psarna** [comment]
note: while investigating huge alternator requests I found another possible source of stalls (~30ms for a 4MB request) - `serialize_collection_mutation`, used broadly via `collection_mutation_description::serialize`. A 4MB request creates a large collection, and serializing this whole collection is done without yielding - with a simple loop over all elements. Such large collections are fortunately expected to be rare, but nonetheless it's yet another potential source of stalls. Converting `serialize_collection_mutation` to yieldable seastar loop primitives would help, but it also requires refactoring quite a few layers to be future-based. We already have a few issues related to optimizing collections in Scylla, so I'm not going to create another one, but I decided to leave this note here just in case.
