### ISSUE TITLE
"No query parameter set for a session requesting a slow_query_log record" error while tracing slow batch queries

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#5843]
*Installation details*
Scylla version (or git commit hash): 6c7aa1823826817b38268871a0633a818cd98495
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

`trace_keyspace_helper::make_slow_query_mutation_data()` assumes there is `query` parameter, but for batch there are `query[0], query[1]...`. See `trace_keyspace_helper::make_slow_query_mutation_data()`

**Comment by slivne** [comment]
@gleb-cloudius does this crash the node or only report an error ?

**Comment by gleb-cloudius** [comment]
Only an error and of course trace does not work.

--
			Gleb.

**Comment by slivne** [comment]
Given that Paxos queries by design are slower ... lets fix this.

**Comment by avikivity** [comment]
Backported to 4.0, 4.1, 4.2.
