### ISSUE TITLE
Exiting with not enabled schema_tables_v3 feature may case broken_promise in migration_manager

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla#5847]
The migration_manager's maube_schedule_schema_pull waits for the "cluster upgraded" event on the schema_tables_v3 feature. If the feature_service exits and frees all the features this ends up in broken_promise exception.

**Comment by slivne** [comment]
was this causght in some version upgrade test ?

**Comment by xemul** [comment]
No, it's the consequences of feature service recent rework

**Comment by xemul** [comment]
Fixed with 7aa7e4f55041402ec9db8e8d42744522c5208b48

**Comment by bhalevy** [comment]
Not sure why the "Fixes" tag was lost from the commit message when merged...

**Comment by bhalevy** [comment]
Backportwed to 3.3 in d2293f9fd506a918b56946518937ca3b1f3c61f4
