### ISSUE TITLE
Exiting with not enabled unbounded_range_tobmstone feature may case broken_promise in storage_service

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla#5848]
The storage_service subscribes on this feature in constructor, but if feature_service stops before this feature is enabled we get the broken_promise exception.

**Comment by slivne** [comment]
is this in upgrade tests of 3.2 --> 3.3 or some other version upgrade ?

**Comment by xemul** [comment]
No, that's the result of feature service recent rework

**Comment by bhalevy** [comment]
Fixed by 8435e93549a6aed875c9dd5819abf550c1923fc5

**Comment by bhalevy** [comment]
Not sure why the "Fixes" tag was lost from the commit message when merged...

**Comment by xemul** [comment]
It doesn't need backporting, neiter feature_service not storage_service is stopped in it.
