### ISSUE TITLE
Commitlog code can perfrome huge writes

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#5857]
*Installation details*
Scylla version (or git commit hash): a46f2350925cfd5e1c0b01927bfc0c6998a238f5

While zeroing segments commitlog code writes entire segment at once which may case big latencies
for other I/O users. The writes were suppose to be split to smaller once, but due to a bug this did not happen.

**Comment by avikivity** [comment]
Backported to 3.3 (4.0 had it already).

**Comment by avikivity** [comment]
Reopening since the fix was reverted.

**Comment by kostja** [comment]
@elcallio can we close this one now? I believe you've changed the code to yield when zeroing the block a while ago.
