### ISSUE TITLE
Commitlog uses incrorrect IO class while zeroing segments

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#5858]
*Installation details*
Scylla version (or git commit hash): a46f2350925cfd5e1c0b01927bfc0c6998a238f5

Comitlog use default class to zero segments which has lowest priority while comimtlog class is the highest. This may cause commitlog writes waiting on a segment been zeroed to be delayed for a long time.

**Comment by avikivity** [comment]
Backported to 3.2, 3.3 (all affected versions).
