### ISSUE TITLE
systemctl stop scylla-server generates core dump

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#586]
I remember I had this issue in the past. Please make sure it works in the latest release.

**Comment by syuu1228** [comment]
I found sharded::~sharded() raising abort() on shutdown, so I sent a patch for it https://groups.google.com/forum/?hl=ja#!topic/seastar-dev/eTo3PNyo_fo

**Comment by tzach** [comment]
duplicate with #601 ?

**Comment by syuu1228** [comment]
Abort caused at destructor of "distributed<database> db" https://github.com/scylladb/scylla/blob/master/main.cc#L232 , and exact place of it is https://github.com/scylladb/seastar/blob/master/core/sharded.hh#L327 .
We need to call sharded<Service>::stop() before delete the instance, but haven't called in this case

**Comment by slivne** [comment]
noam will try to reproduce on ami of 0.18 and see if it happens as well
