### ISSUE TITLE
install.sh does not provide a way to upgrade scylla

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#5874]
Related with #5830, current install.sh only provides a way to install scylla, but not upgrade scylla.
To support upgrade, we need to prevent overwrite config files and existing data.

**Comment by dyasny** [comment]
The current, RPM based offline installer is easy to adjust: since all it does is unpack a local repo, we can simply let the user choose whether it will do a `yum install` or `yum update` once the repo is inflated and enabled. 

Frankly though, I don't think we really need to go this far, it should be enough to package a repo that people can use, running yum is something everyone can do in whatever way

**Comment by amoskong** [comment]
> The current, RPM based offline installer is easy to adjust: since all it does is unpack a local repo, we can simply let the user choose whether it will do a `yum install` or `yum update` once the repo is inflated and enabled.
> 
> Frankly though, I don't think we really need to go this far, it should be enough to package a repo that people can use, running yum is something everyone can do in whatever way

Totally agree.

**Comment by avikivity** [comment]
> The current, RPM based offline installer is easy to adjust: since all it does is unpack a local repo, we can simply let the user choose whether it will do a `yum install` or `yum update` once the repo is inflated and enabled.
> 
> Frankly though, I don't think we really need to go this far, it should be enough to package a repo that people can use, running yum is something everyone can do in whatever way

This is about the rpm-less installer (install.sh).

**Comment by amoskong** [comment]
> > The current, RPM based offline installer is easy to adjust: since all it does is unpack a local repo, we can simply let the user choose whether it will do a `yum install` or `yum update` once the repo is inflated and enabled.
> > Frankly though, I don't think we really need to go this far, it should be enough to package a repo that people can use, running yum is something everyone can do in whatever way
> 
> This is about the rpm-less installer (install.sh).

Why the user don't want to use RPM or deb packages?
What's the benefit to use relocate packages for offline installation?

**Comment by avikivity** [comment]
@amoskong some poor users do not have root access to their machines. So rpm/deb are not usable for them.

Relocatable packages have the following benefits:
 - they already exist as the source for our rpm/deb packages, so we don't need to work to create them
 - they demand very little from the host regarding installed libraries and versions, and so should work on most hosts without tweaking

**Comment by amoskong** [comment]
So original offline installer (based on rpm/deb package repo) should be the recommended (supported) solution for offline installation.

We can't replace original offline installer by the relocated solution, and only use it for the poor users.
In our testing, I didn't limit users' permission,  used sudo to change the files' attribute and scylla_setup.
I will retest it.

**Comment by avikivity** [comment]
Tarball upgrade is a new feature; not backporting.
