### ISSUE TITLE
CQL: Scylla is reporting null values as empty on dense composite tables

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#588]
Consider the example:

    CREATE KEYSPACE IF NOT EXISTS lmr_test_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
    CREATE TABLE lmr_test_keyspace.table_test_dense_composite_table (userid uuid, ip text, port int, time bigint, PRIMARY KEY (userid, ip, port)) WITH COMPACT STORAGE;
    INSERT INTO lmr_test_keyspace.table_test_dense_composite_table (userid, ip, port, time) VALUES (550e8400-e29b-41d4-a716-446655440000, '192.168.0.1', 80, 42);
    INSERT INTO lmr_test_keyspace.table_test_dense_composite_table (userid, ip, port, time) VALUES (550e8400-e29b-41d4-a716-446655440000, '192.168.0.2', 80, 24);
    INSERT INTO lmr_test_keyspace.table_test_dense_composite_table (userid, ip, port, time) VALUES (550e8400-e29b-41d4-a716-446655440000, '192.168.0.2', 90, 42);
    UPDATE lmr_test_keyspace.table_test_dense_composite_table SET time = 24 WHERE userid = 550e8400-e29b-41d4-a716-446655440000 AND ip = '192.168.0.2' AND port = 80;
    INSERT INTO lmr_test_keyspace.table_test_dense_composite_table (userid, ip, time) VALUES (f47ac10b-58cc-4372-a567-0e02b2c3d479, '192.168.0.3', 42);
    UPDATE lmr_test_keyspace.table_test_dense_composite_table SET time = 42 WHERE userid = f47ac10b-58cc-4372-a567-0e02b2c3d479 AND ip = '192.168.0.4';

After the updates, origin reports the value of port for ips 192.168.0.4 and 192.168.0.3 correctly as null:

    SELECT ip, port, time FROM lmr_test_keyspace.table_test_dense_composite_table WHERE userid = f47ac10b-58cc-4372-a567-0e02b2c3d479 and ip = '192.168.0.4';

     ip          | port | time
    -------------+------+------
     192.168.0.4 | null |   42

    (1 rows)
    SELECT ip, port, time FROM lmr_test_keyspace.table_test_dense_composite_table WHERE userid = f47ac10b-58cc-4372-a567-0e02b2c3d479 and ip = '192.168.0.3';

     ip          | port | time
    -------------+------+------
     192.168.0.3 | null |   42

    (1 rows)

However, scylla reports the same port values as an empty value:

    SELECT ip, port, time FROM lmr_test_keyspace.table_test_dense_composite_table WHERE userid = f47ac10b-58cc-4372-a567-0e02b2c3d479 and ip = '192.168.0.4';

     ip          | port | time
    -------------+------+------
     192.168.0.4 |      |   42

    (1 rows)
    SELECT ip, port, time FROM lmr_test_keyspace.table_test_dense_composite_table WHERE userid = f47ac10b-58cc-4372-a567-0e02b2c3d479 and ip = '192.168.0.3';

     ip          | port | time
    -------------+------+------
     192.168.0.3 |      |   42

    (1 rows)

**Comment by avikivity** [comment]
Lo and behold, I just posted a patchset to deal with this.

The patchset does not fix the issue, but lays the groundwork for the fix.

**Comment by lmr** [comment]
@avikivity I've seen your discussion with Tomek, and I was actually thinking about linking this to that discussion.

**Comment by tgrabiec** [comment]
@avikivity I don't think your series is directly related. We already distinguish missing values from empty ones in queries. What's special here is that port is part of the clustering key and we don't handle prefixed clustering keys right now, looks like a duplicate of #515

**Comment by lmr** [comment]
Problem solved as of latest master (8f4e90b87a1571533c3b15be4899ad5efe2d7170).
