### ISSUE TITLE
CQL: Scylla returns incorrect result set on single cluster columns

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#589]
CREATE KEYSPACE IF NOT EXISTS lmr_test_keyspace WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'};
    CREATE TABLE lmr_test_keyspace.table_test_single_clustering (p text, c text, v text, s text static, PRIMARY KEY (p, c));
    INSERT INTO lmr_test_keyspace.table_test_single_clustering (p, c, v, s) values ('p1', 'k1', 'v1', 'sv1');
    INSERT INTO lmr_test_keyspace.table_test_single_clustering (p, c, v) values ('p1', 'k2', 'v2');
    INSERT INTO lmr_test_keyspace.table_test_single_clustering (p, s) values ('p2', 'sv2');
    SELECT * FROM lmr_test_keyspace.table_test_single_clustering WHERE p='p1' AND c<='k0';

Origin correctly reports 0 rows:

     p | c | s | v
    ---+---+---+---

    (0 rows)

As scylla reports one row:

     p  | c    | s   | v
    ----+------+-----+------
     p1 | null | sv1 | null

    (1 rows)

Other examples of queries in the same table that report a single row while origin reports 0 rows:

    SELECT * FROM lmr_test_keyspace.table_test_single_clustering WHERE p='p1' AND c>='k3';

     p  | c    | s   | v
    ----+------+-----+------
     p1 | null | sv1 | null

    (1 rows)

    SELECT * FROM lmr_test_keyspace.table_test_single_clustering WHERE p='p1' AND c<='k0';

     p  | c    | s   | v
    ----+------+-----+------
     p1 | null | sv1 | null

    (1 rows)

**Comment by penberg** [comment]
I initially suspected this might be related to the less than equals operator ("<=") but turns out equality operator is enough to reproduce the issue:

```
SELECT * FROM lmr_test_keyspace.table_test_single_clustering WHERE p='p1' AND c='k0';

 p  | c    | s   | v
----+------+-----+------
 p1 | null | sv1 | null

(1 rows)
```

Seems like we ignore clustering key altogether. Ping @tgrabiec, @pdziepak

**Comment by tgrabiec** [comment]
@penberg The problem is that we should exclude the static row if there are clustering restrictions and none of the clustered rows match. Calle's working on this one.

**Comment by penberg** [comment]
@tgrabiec Great, thanks for the update! It will fix few C* unit tests as well.
