### ISSUE TITLE
Commitlog pre-zeroing (when using O_DSYNC) should not re-write existing file data

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#5891]
When creating segments with the o_dsync option active, we write `max_size` zeros to disk, to ensure actual disk blocks are allocated. 
However, due to code paths being as they are, if we recycle a segment, we still do a full zeroing of the file, even though by this logic, it should already have actual disk blocks allocated. 
We should, when not actually creating a new file, check the existing size on disk, and only zero any blocks not already allocated (i.e. if recycled file was smaller than `max_size`, due to segement truncation on close).

**Comment by slivne** [comment]
Not clear to me if this is a performance enhancement or a bug for notzeroing parts that shoudl have been.

**Comment by elcallio** [comment]
It is a bug, but it does not cause any errors, just unnecessary stall. It is low frequency though, but still...

**Comment by gleb-cloudius** [comment]
On Mon, Feb 24, 2020 at 07:09:13AM -0800, Calle Wilund wrote:
> When creating segments with the o_dsync option active, we write `max_size` zeros to disk, to ensure actual disk blocks are allocated. 
> However, due to code paths being as they are, if we recycle a segment, we still do a full zeroing of the file, even though by this logic, it should already have actual disk blocks allocated. 
> We should, when not actually creating a new file, check the existing size on disk, and only zero any blocks not already allocated (i.e. if recycled file was smaller than `max_size`, due to segement truncation on close). 
> 
I am trying to do that and see that sometimes recycled file is larger
than max_size. Can you think of a reason why it can be so?

--
			Gleb.

**Comment by elcallio** [comment]
Two reasons: 
1.) we are reusing segments from a failed run (crash + replay), and max_size changed (config),
2.) More likely, we touch the border condition where we write an extra zero block to a recycled segment. This one should really be possible to remove, but I doubt it is worth doing before coroutines (and more readable code).

**Comment by gleb-cloudius** [comment]
On Mon, Feb 24, 2020 at 08:21:47AM -0800, Calle Wilund wrote:
> Two reasons: 
> 1.) we are reusing segments from a failed run (crash + replay), and max_size changed (config),
That's obviously not my case, but need to be handle anyway.

> 2.) More likely, we touch the border condition where we write an extra zero block to a recycled segment. This one should really be possible to remove, but I doubt it is worth doing before coroutines (and more readable code). 
> 
This additional write may cause file system to allocate an extent and
write metadata which may be slow.

--
			Gleb.

**Comment by elcallio** [comment]
This is true, but I'd prefer to address it as a separate issue. The "terminate" aspect in segment close should look at current position, and iff we filled the last block (file size == max_size), ignore writing an additional block. I'll create a separate issue for this.

**Comment by kostja** [comment]
A possible cause of #5834

**Comment by avikivity** [comment]
In 4.0, and only experimental in 3.3, not backporting.
