### ISSUE TITLE
alternator - missing support for UpdateItem ADD operation

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5893]
In the old-style AttributeUpdates parameter for the UpdateItem operation (later superseded by newer UpdateExpression parameter), an ADD operation can be used to increment numbers or append to a set (i.e., this is a type of conditional expression, which would require LWT). We don't support this syntax yet, and don't even have a test for it yet.

In the code we have the following check, so at least it gives an error if used:
```c++
            } else {
                // FIXME: need to support "ADD" as well.
                throw api_error("ValidationException",
                        format("Unknown Action value '{}' in AttributeUpdates", action));
            }
```

**Comment by nyh** [comment]
Added a test for this feature: `test_item.py::test_update_item_add`.

**Comment by dimaqq** [comment]
My 2c, as an average user:
1. new code can use new syntax
2. for existing apps, this creates friction both to transition to scylla as well as simply to try it out

Given current scylla pricing model (minimum quote: 10K ops/s; 1TB data), I feel that `2.` should be more important than `1.`, shouldn't it?

**Comment by nyh** [comment]
> My 2c, as an average user:
> 
>     1. new code can use new syntax
> 
>     2. for existing apps, this creates friction both to transition to scylla as well as simply to try it out
> 
> 
> Given current scylla pricing model (minimum quote: 10K ops/s; 1TB data), I feel that `2.` should be more important than `1.`, shouldn't it?

You know that Scylla is open-source, so users who are just starting out can use it for free? :-) But anyway, I agree - full compatibility with DynamoDB and all its operations has always been our goal. For some reason we never got around to fixing *this* one - I'll try to get to it very soon.

**Comment by nyh** [comment]
Ok, I implemented this missing feature. As I expected it was relatively straightforward. I'll send a pull request in a few minutes.

**Comment by nyh** [comment]
This feature reached branch 4.6.
As it can be considered a feature, not backporting to older branches.
