### ISSUE TITLE
alternator: empty string, blob or set should not be allowed

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#5896]
DynamoDB does not allow empty string, blog or sets to exist (see https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html#HowItWorks.DataTypes).
In particular, setting them with PutItem, UpdateItem+AttributeUpdates or UpdateItem+UpdateExpression should all be rejected.

Here is an example test (for UpdateItem+AttributeUpdates) which passes on DynamoDB, but fails on Alternator:
```python
def test_update_item_empty_attribute(test_table_s):
    p = random_string()
    # Empty string, byte array and set are *not* allowed
    with pytest.raises(ClientError, match='ValidationException.*empty'):
        test_table_s.update_item(Key={'p': p},
            AttributeUpdates={'a': {'Action': 'PUT', 'Value': ''}})
    with pytest.raises(ClientError, match='ValidationException.*empty'):
        test_table_s.update_item(Key={'p': p},
            AttributeUpdates={'b': {'Action': 'PUT', 'Value': bytearray('', 'utf-8')}})
    with pytest.raises(ClientError, match='ValidationException.*empty'):
        test_table_s.update_item(Key={'p': p},
            AttributeUpdates={'c': {'Action': 'PUT', 'Value': set([])}})
    assert not 'Item' in test_table_s.get_item(Key={'p': p}, ConsistentRead=True)
```

**Comment by slivne** [comment]
I don't think this is urgent it can be marked as a bug and we can do it post 3.4 - its low priority

**Comment by nyh** [comment]
@slivne I'm discovering these bugs as I write more tests, often while writing tests for other things and thinking of more corner-cases I didn't previously consider. I agree that this is a low-priority bug, but if its fix is trivial, and the hard part (discovering it and writing the test) is already done, then it's worth just getting it over with. I'll see how it works out.

**Comment by nyh** [comment]
Already in 4.0. Not backporting to 3.3 (where Alternator was experimental) as this is a minor compatibility issue in an unexpected (ought to be rejected) case that correct applications would not try.
