### ISSUE TITLE
Commitlog should not add trailing zeros to segment if this exceeds max_size

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#5899]
When terminating (closing) a segment, we write a trailing block of zero so reader can have an empty region after last used chunk as end marker. This is due to using recycled, pre-allocated segments with potentially non-zero data extending over the point where we are ending the segment (i.e. we are not fully filling the segment due to a huge mutation or similar). 

However, if we reach end of segment writing the final block (typically many small mutations), the file will end naturally after the data written, and any trailing zero block would in fact just extend the file further. While this will only happen once per segment recycled (independent on how many times it is recycled), it is still both slightly breaking the disk usage contract and also potentially causing some disk stalls due to metadata changes (though of course very infrequent).

Should:
1.) Only write trailing zero if we are below the `max_size` file size when terminating
2.) Always truncate any segments reused from a previous (crashed + replayed) run to `max_size`

**Comment by gleb-cloudius** [comment]
FWIW I am working on 2.

--
			Gleb.

**Comment by elcallio** [comment]
Oh, I already wrote a patch for both. Think I forgot to send it though... scatterbrain...

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please consider backport to 4.0

**Comment by avikivity** [comment]
Already backported to 4.0+.
