### ISSUE TITLE
Is it normal to consume 300% cpu with no data and no operations

### ISSUE THREAD

**Issue by shivshankardayal** [scylladb/scylla#590]
I installed scylla db version 0.11 on a VM and with no data and no operations going on it is consuming 1.4G RAM and 3 full cores of CPU. I am curious to know for what purposes an idle instance keeps consuming 3 cores of CPU. Is it normal or is it a bug?

**Comment by gleb-cloudius** [comment]
On Wed, Nov 18, 2015 at 07:32:50PM -0800, Shiv Shankar Dayal wrote:
> I installed scylla db version 0.11 on a VM and with no data and no operations going on it is consuming 1.4G RAM and 3 full cores of CPU. I am curious to know for what purposes an idle instance keeps consuming 3 cores of CPU. Is it normal or is it a bug?
> 
It is normal since scylla use polling loop (and prints this during
startup too). Please use scyalldb-user mailing list
(https://groups.google.com/forum/#!forum/scylladb-users) for question instead
of the bug tracker.

--
			Gleb.

**Comment by shivshankardayal** [comment]
Thanks. I will post queries there.

**Comment by dorlaor** [comment]
Shiv, it's on our FAQ: http://www.scylladb.com/doc/faq/
We're aware it's a problem when the system isn't loaded and thus we'll
reduce the polling rate when it's not idle. Expect that to arrive within
1-2 months since
it's not that urgent but definitely nice to have.
