### ISSUE TITLE
Making output streams for sstable file_writers should be moved out of the constructors

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#5901]
As noted by @espindola in https://github.com/scylladb/scylla/pull/5509#discussion_r377289279
> My preference is for constructors that are super simple (noexcept in particular). That way ownership transfer is simple, once the constructor is called the destructor is responsible for freeing resources.
>
> Any convenience that is lost by the simple constructor (like being able to call non noexcept functinos like make_file_output_stream) is regained by moving that to a static make function.

**Comment by denesb** [comment]
@espindola @bhalevy we already have such a `make()` function: `make_file_output_stream()` and `make_file_data_sink()` and they fail us just the same.

I sent an RFC to move closing the file on failure on the `make_file_data_sink` level.

**Comment by denesb** [comment]
See the RFC here: https://groups.google.com/d/msg/seastar-dev/0hBiwNzr6mE/AdVhTYjXBgAJ

**Comment by bhalevy** [comment]
This was done in 13282b3d4cc31c4c7d2d9f477bfe3536b15b270e
and improved in e5876f669601d5bfd7a29afb08306007ded5d4f4
