### ISSUE TITLE
Feature request: Allow more than one LIKE relation for a single column

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#5902]
We are testing out LIKE support added in Scylla 3.2.  It works very well and we think this can replace some of our elasticsearch usage (yay!).  However, we need to use multiple LIKE constraints on the same column.  For example:

create table clothes (speciesid int, familyid int, clothingid int, clothingdescription text, primary key ((speciesid, familyid), clothingid));
insert into clothes (speciesid, familyid, clothingid, clothingdescription) values (1,1,1,'man pants');
insert into clothes (speciesid, familyid, clothingid, clothingdescription) values (1,1,2,'baby pants');
insert into clothes (speciesid, familyid, clothingid, clothingdescription) values (1,1,3,'baby bib');

Both these queries work:

select * from clothes where speciesid = 1 and familyid in (1,2) and clothingdescription like '%baby%' allow filtering;
select * from clothes where speciesid = 1 and familyid in (1,2) and clothingdescription like '%pants%' allow filtering;

But this does not work:

select * from clothes where speciesid = 1 and familyid in (1,2) and clothingdescription like '%baby%' and clothingdescription like '%pants%' allow filtering;
InvalidRequest: Error from server: code=2200 [Invalid query] message="clothingdescription cannot be restricted by more than one relation if it includes a LIKE"

Could it work?  Thanks.  

@dekimir - Glauber told me I could tell you to do it, for whatever that's worth.  :) :) :)  Or maybe more accurately he told me I could tell you that he told me to tell you to do it.  Not sure.

**Comment by dekimir** [comment]
Hey, I'll do anything for our users. ;) What's your timeline?

**Comment by veramine** [comment]
Oh, there's no rush.  If 3.3 is already baked, 3.4 would be fine.  Thanks.

**Comment by veramine** [comment]
Awesome, thanks!
