### ISSUE TITLE
Classify queries based on initiator, instead of target table

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#5919]
Queries are classified as `user` or `system` based on the table they target. This classification determines various limits that applies to queries:

| what            | system  | user      |
|-----------------|---------|-----------|
| timeout         | no      | yes       |
| concurrency [1] | 10/2%/∞ | 100/2%/2% |
| max memory [2]  | ∞       | 1MB       |

[1] count / memory / queue memory
[2] nonpaged and reverse queries: https://github.com/scylladb/scylla/issues/5804 and https://github.com/scylladb/scylla/issues/5870

This classification has a vulnerability in that users are also allowed to query system tables. Internally these will be treated as internal (system) queries however. This has caused meltdowns in the past. We should classify queries based on who initates them (user or the system), not based on the target table. This is increasingly important as we keep adding new limits that don't apply to system queries.

**Comment by slivne** [comment]
ref #4711

**Comment by slivne** [comment]
#5870 - can't be merged without having this fixed.

**Comment by denesb** [comment]
@slivne I think we can fix https://github.com/scylladb/scylla/issues/5870 before this. We just need to make sure we don't limit system query memory, the same way we didn't limit it for reverse queries in https://github.com/scylladb/scylla/issues/5804.

This will not be a regression compared to what we have now. Instead of two sources of external queries having the possibility of causing OOM: user queries to user tables, and user queries to system tables, only the latter will remain until we fix this too.
