### ISSUE TITLE
Aggressive compactions and poor read performance after bootstrapping

### ISSUE THREAD

**Issue by gibsn** [scylladb/scylla#5921]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [*] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.1.1
Cluster size: 9 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): C7.5

Platform (physical/VM/cloud instance type/docker): bare metal
Hardware: sockets=2 x Intel(R) Xeon(R) Gold 6230 CPU @ 2.10GHz cores=40 hyperthreading=yes memory= 6x32GB DDR4 2666MHz
Disks: RAID 10 of 10HDDs 14TB each for data, RAID 1 SSD 1TB for clogs

We have a cluster of 8 nodes, 4 nodes in each DC, RF = 1, 20TBs of compressed time series data, TWCS.
We bootstrapped a new node, the whole process took ~1week. A couple days after bootstrapping finished the new node started lots of compactions, `nodetool compactionstats` would show ~3million (!) pending tasks, which led to bad read performance (95pct went from ~200ms to 8sec).  We thought that was because of disks overload, so we started decreasing `num-io-queues`. By the moment `num-io-queues` was 6 times lower than the original, read performance still was not getting better. We decided to update to 3.2.2 to check disk timings in tracing and after update `nodetool compactionstats` pending tasks decreased from 3e6 to ~150 (guess thanks to #2687). Then I discovered this:
![Снимок экрана 2020-02-28 в 15 36 08](https://user-images.githubusercontent.com/11294101/75549135-00707c00-5a40-11ea-8791-f34f407110d0.png)

So here are 2 problems we encountered:
1. After bootstrapping the new node probably starts compacting older time windows which it shouldn't (fixed #2687)
2. After bootstrapping the new node has super high amount of compaction shares, which dramatically affects read performance

CPU dashboard for the new node by shard:
![Снимок экрана 2020-02-28 в 15 43 56](https://user-images.githubusercontent.com/11294101/75549600-1cc0e880-5a41-11ea-8669-48e48d457a77.png)

**Comment by slivne** [comment]
scylladb/scylla#2687 - should solve the issue of bootstrapping new nodes with TWCS compaction.

**Comment by slivne** [comment]
So its clear - did you upgrade the new added node  from 3.1 --> 3.2 ?

What is the current state of the cluster ? 
8 nodes 3.1
1 node 3.2 ?

**Comment by gibsn** [comment]
@slivne 
> did you upgrade the new added node from 3.1 --> 3.2 ?

3.1.1 => 3.2.2

> What is the current state of the cluster ?

8 nodes 3.1.1, 1 node 3.2.2

**Comment by slivne** [comment]
@gibsn you can't add nodes with different major versions - this is not supported.

The solution is first to upgrade the other nodes and then add a node ...

Can we close this ?

We are working on a better solution, https://github.com/scylladb/scylla/issues/5226

**Comment by gibsn** [comment]
@gibsn you can close, thanks
