### ISSUE TITLE
Commitlog: "Exiting on unhandled exception of type 'std::runtime_error': Checksum error in data entry"

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#593]
Raphael 

AFAICT, commitlog integrity is not guaranteed. For example, the instance may be killed while a commitlog entry is being written, right?! Is it up to the sysadmin to remove corrupted commitlog entries before trying another reboot? Or should scylla itself move/delete such corrupted entries?

Avi 

No, Scylla or any other database should not depend on an admin in case of a restart.

**Comment by elcallio** [comment]
Origin silently ignores broken commitlog entries (assuming a failed/missing sync or disk corruption). I take it you want me to change to this behaviour?

**Comment by slivne** [comment]
@avikivity - its seems to me that this is the best we can do with a corrupt
file, please approve

**Comment by avikivity** [comment]
I don't see any other way.

Let's have commitlog report the number of bytes/files ignored due to bad checksum.
