### ISSUE TITLE
scylla-jmx configuration in scylla docker image

### ISSUE THREAD

**Issue by juanramb** [scylladb/scylla#5939]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.1.3
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Scylla docker image (rhel)

I expected scylla-jmx to be properly configured when editing /etc/sysconfig/scylla-jmx to have the daemon listen on 0.0.0.0 and allow remote connections.
I changed /etc/sysconfig/scylla-jmx to have the following vars:
```# use alternate jmx address
SCYLLA_JMX_ADDR="-ja 0.0.0.0"
# allow to run remotely
SCYLLA_JMX_REMOTE="-r"
```
But /scylla-jmx-service.sh does not pass sourced env vars to /usr/lib/scylla/jmx/scylla-jmx:
```
#!/bin/bash

source /etc/sysconfig/scylla-jmx

exec /usr/lib/scylla/jmx/scylla-jmx -l /usr/lib/scylla/jmx
```
So scylla-jmx is run with these params:
`scylla_1                         | + exec /usr/lib/scylla/jmx/symlinks/scylla-jmx -Xmx256m -XX:+UseSerialGC -XX:+HeapDumpOnOutOfMemoryError -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.host=localhost -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7199 -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=7199 -Djavax.management.builder.initial=com.scylladb.jmx.utils.APIBuilder -jar /usr/lib/scylla/jmx/scylla-jmx-1.0.jar
`
Only if I change /scylla-jmx-service.sh:
```
#!/bin/bash

source /etc/sysconfig/scylla-jmx

exec /usr/lib/scylla/jmx/scylla-jmx $SCYLLA_JMX_ADDR $SCYLLA_JMX_REMOTE -l /usr/lib/scylla/jmx
```
scylla-jmx is run with the correct params:
`
scylla_1                         | + exec /usr/lib/scylla/jmx/symlinks/scylla-jmx -Xmx256m -XX:+UseSerialGC -XX:+HeapDumpOnOutOfMemoryError -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.host=0.0.0.0 -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=7199 -Djava.rmi.server.hostname=localhost -Dcom.sun.management.jmxremote.rmi.port=7199 -Djavax.management.builder.initial=com.scylladb.jmx.utils.APIBuilder -jar /usr/lib/scylla/jmx/scylla-jmx-1.0.jar
`

I can modify both files so my container works as intended (allow connections in other IP different from localhost so I can run nodetool from a remote container), but I believe /scylla-jmx-service.sh should be modified accordingly so every configurable parameter present in /etc/sysconfig/scylla-jmx is passed to /usr/lib/scylla/jmx/scylla-jmx script

**Comment by avikivity** [comment]
Aged out, no need to backport.
