### ISSUE TITLE
test_user_function_disabled seems to be flaky

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#5946]
I sometimes see following faliure:

test/boost/user_function_test.cc(59): fatal error: in "test_user_function_disabled": exception ire expected but not raised

**Comment by haaawk** [comment]
@espindola

**Comment by espindola** [comment]
That is quite odd. There is a bug in the test (db_cfg_ptr is not used) that causes that line to be identical to the previous check at line 52.

Under what conditions this normally reproduces? For instance, dev, debug or release?

**Comment by haaawk** [comment]
I was running dev.

**Comment by espindola** [comment]
just test.py --mode=dev?

**Comment by haaawk** [comment]
exactly

**Comment by espindola** [comment]
I think that the patch "gms: Add a default constructor to feature_config" might fix this.

**Comment by espindola** [comment]
I tried to use valgrand to confirm it, but it can't handle our use of io_submit. We should try to get msan going one day, but that requires building with clang *and* having a build system that allows us to build all of our dependencies.

**Comment by espindola** [comment]
The patch is now 9445608df63b60966daae2f5789c1b360187e4c2 in master.  Lets close this. Please reopen if you see a failure again.
