### ISSUE TITLE
Row cache is incorrectly invalidated in incremental compaction 

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#5956]
*Installation details*
Scylla version (or git commit hash):  8a1c8ce8a62889
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Incremental compaction will incorrectly invalidate the cache when compaction purges expired data. That's because incremental compaction temporarily stores data in sstables containing only expired data and those sstables were added to table using a function that invalidates the cache.

**Comment by bhalevy** [comment]
Based on our conversation, this may cause performance degradation.
This is not a correctness issue.

**Comment by avikivity** [comment]
Present everywhere, no need for backport.
