### ISSUE TITLE
No unavailable exception if replication_factor=0 and replication strategy is "Simple"

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#5962]
Cassandra and Scylla allow to configure a keyspace with replication factor 0. This is mainly used for NetworkTopologyStrategy, when certain a keyspace can be made local to a specific data center this way (e.g. by saying that it's replication_factor in the other data center is 0).

Perhaps as an omission RF=0 is also allowed for SimpleStrategy. However, unlike Cassandra, Scylla wrongly selects endpoints for RF=0 and SimpleStrategy, always including all endpoints.

**Comment by avikivity** [comment]
Backported to 3.1, 3.2, 3.3.
