### ISSUE TITLE
internode_compression does not work

### ISSUE THREAD

**Issue by Laboltus** [scylladb/scylla#5963]
After set `internode_compression: dc` I see no changes in bandwidth usage between datacenters. I checked traffic on port 7000 with tcpdump and I see uncompressed data.  Scylla compress all traffic or only some part of it ?

**Comment by Laboltus** [comment]
I forgot to mention that I tested Scylla 3.1.3, 3.1.4, 3.2.2 with identical results.

**Comment by Laboltus** [comment]
I put traffic in the OpenVPN tunnel (turned off encryption and turned on LZ4 compression), and it was reduced by at least half. So I'm pretty sure that the internode_compression does not work.

**Comment by dorlaor** [comment]
@elcallio @gleb-cloudius do we use this parameter? From a quick git grep I didn't find we actually use it.

**Comment by slivne** [comment]
We do use this in the code ...

@Laboltus can you please share 
- nodetool status
- a scylla.yaml 

if all the nodes are in one dc there will be no compression.

**Comment by Laboltus** [comment]
I tried set the option to "all", so the topology is not the problem, I guess.
Here is nodetool status:
Datacenter: us-colo-bocaraton
===============================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  172.16.2.69   1.52 TB    256          ?       d4966382-d74b-4ff9-84c2-cb8b8deb406f  bocaraton
Datacenter: us-colo-herndon
=============================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  172.16.2.5    1.53 TB    256          ?       3830daca-5672-40c6-9c55-165650dd7735  herndon
Datacenter: us-east
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address       Load       Tokens       Owns    Host ID                               Rack
UN  172.31.2.110  1.14 TB    256          ?       8abc3995-b212-432c-b4ea-d26f9396b928  1b
UN  172.31.2.135  1.1 TB     256          ?       3d92b268-208b-42be-8fdb-961d849cd422  1b
UN  172.31.2.246  1.34 TB    256          ?       40ac2649-9ae7-45dc-9bcd-531ed75f6295  1b


Here is scylla.yaml:
num_tokens: 256
data_file_directories:
    - /mnt/scylla/data
commitlog_directory: /mnt/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "bocaraton-db.adx1int"
listen_address: 172.16.2.5
broadcast_address: 172.16.2.69
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 2000
cas_contention_timeout_in_ms: 1000
endpoint_snitch: GossipingPropertyFileSnitch
rpc_address: 172.16.2.69
broadcast_rpc_address: 172.16.2.69
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
hints_directory: /mnt/scylla/hints
 
view_hints_directory: /mnt/scylla/view_hints
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
internode_compression: dc
prometheus_address: 172.16.2.69
murmur3_partitioner_ignore_msb_bits: 12
cluster_name: scylla-cluster
api_ui_dir: /opt/scylladb/swagger-ui/dist/
api_doc_dir: /opt/scylladb/api/api-doc/

**Comment by elcallio** [comment]
internode_compression does indeed not work. Because of a static init fiasco in scylla using non-initialized seastar constants. I'll send a patch.

**Comment by elcallio** [comment]
See /scylladb/seastar#744

**Comment by slivne** [comment]
@roydahan can we internode_compression to the rolling upgrades to make sure we cover this as well.

**Comment by slivne** [comment]
fixed by scylladb/scylla@bf2ab10b6a1b448c38129cb747c8985e95465dc8

**Comment by slivne** [comment]
The fix will be part of 4.1 - backporting to older releases will follow

**Comment by avikivity** [comment]
Backported to 4.0.

**Comment by Laboltus** [comment]
I'm now running 5.1.11 and see the same symptom - pain text on port 7000.
