### ISSUE TITLE
Drop key space do not remove data on disk. do i need to remove manually?

### ISSUE THREAD

**Issue by yuqin11** [scylladb/scylla#5984]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):3.0.7
Cluster size:2
OS (RHEL/CentOS/Ubuntu/AWS AMI):Centos

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):docker
Hardware: sockets= cores= hyperthreading= memory=32G
Disks: (SSD/HDD, count)HDD

**Comment by amoskong** [comment]
You can release the space by two commands:

1. nodetool cleanup
https://docs.scylladb.com/operating-scylla/nodetool-commands/cleanup/

2. nodetool clearsnapshot
https://docs.scylladb.com/operating-scylla/nodetool-commands/clearsnapshot/

**Comment by yuqin11** [comment]
is there any method that use java package com.datastax.driver.core.Cluster or rest api?

**Comment by nyh** [comment]
Indeed, Scylla keeps dropped tables (including the case where a keyspace was dropped) as a "snapshot" to allow undoing the "drop table" operation, if required. This behavior surprises many (it surprised me when I first encountered it!) but was done intentionally, and documented:

https://docs.scylladb.com/troubleshooting/drop_table_space_up/
https://docs.scylladb.com/faq/#dropping-a-table-does-not-reduce-storage-used-by-scylla-how-can-i-clean-the-disk-from-dropped-tables

So I'm closing this issue.
