### ISSUE TITLE
AMI: attach instance storage by default?

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#599]
C*'s AMI already comes with all their instance storage attached. For us, that's an extra step to be taken.

That complicates the user's deployment scripts, because you need to always specify which disks you want to attach, which can vary from instance to instance. There should be a way for us to create an AMI that includes all the available disks by default.

**Comment by tzach** [comment]
Duplicate with https://github.com/scylladb/scylla-ami/issues/9

**Comment by slivne** [comment]
impled work on 0.18
