### ISSUE TITLE
Node operations will process materialized view twice

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#5998]
Node operations (both streaming and repair based) will transfer over materialized view tables along with the normal ones. Both streaming and repair has a hook from the view building code however that will cause each transferred sstable to be registered with the `view_mutation_builder`, which will then generate view updates for it. This is good if the view is missing updates for some of the base table mutations, but in the general case it will generate twice as many writes for MVs.

Found while investigating https://github.com/scylladb/scylla/issues/5930.

**Comment by slivne** [comment]
I am not sure this is true (at least with old non repair based operations
it wasnt).

When you bootstrapped a new node - you transferred the base and the views -
I don't think we force the new added node todo view building for all the
base sstables it just got ownership of.

**Comment by denesb** [comment]
Indeed it is not as bad as I thought:
https://github.com/scylladb/scylla/blob/d895f5e1311118cc93e8c84384914a0a9bde2267/db/view/view.cc#L1848-L1861

We will only generate view updates if the stream reason is repair or if there is view building going on for any of the affected views.

**Comment by slivne** [comment]
Great

Now we need to figure out - if this changes since we moved bootstrapping to
be based on repair.

@Piotr Sarna <sarna@scylladb.com> / @Asias He <asias@scylladb.com>  need
your inputs on this.

**Comment by denesb** [comment]
Actually https://github.com/scylladb/scylla/issues/5930 does view building. So we just need a simple confirmation from @asias that repair based node operations use the correct streaming reason and we can close this.

**Comment by asias** [comment]
> Actually #5930 does view building. So we just need a simple confirmation from @asias that repair based node operations use the correct streaming reason and we can close this.

Currently, all repair use streaming::stream_reason::repair unconditionally, including the ones used by repair based node ops.  We can extend repair to send the real reason for the repair, e.g., bootstrap, repair. We need to consider the resume cases though. Say, bootstrap failed in the middle, we need to resume the bootstrap. Since the repair reason is now bootstrap, the view update will not be triggered when we stream (using repair) the base table, the view table will not be updated. I think this is fine because when we resume the bootstrap, we will stream (using repair) the view table too, so any mismatch between the existing nodes and the new nodes will be synced from the view table from the existing nodes, no need to sync from the base table on the new node. 


```
 488     void create_writer(unsigned node_idx) {
 489         if (_writer_done[node_idx]) {
 490             return;
 491         }               
 492         _mq[node_idx] = seastar::queue<mutation_fragment_opt>(16);
 493         auto get_next_mutation_fragment = [this, node_idx] () mutable {
 494             return _mq[node_idx]->pop_eventually();
 495         };
 496         auto& db = service::get_local_storage_service().db();
 497         table& t = db.local().find_column_family(_schema->id());
 498         _writer_done[node_idx] = mutation_writer::distribute_reader_and_consume_on_shards(_schema, dht::global_partitioner(),
 499                 make_generating_reader(_schema, std::move(get_next_mutation_fragment)),
 500                 [&db, estimated_partitions = this->_estimated_partitions] (flat_mutation_reader reader) {
 501             auto& t = db.local().find_column_family(reader.schema());
 502             return db::view::check_needs_view_update_path(_sys_dist_ks->local(), t, streaming::stream_reason::repair).then([t = t.shared_from_this(), estimated_partitions, reader = std::move(reader)] (bool use_view_update_path     ) mutable {
 503                 //FIXME: for better estimations this should be transmitted from remote
 504                 auto metadata = mutation_source_metadata{};
 505                 auto& cs = t->get_compaction_strategy();
 506                 const auto adjusted_estimated_partitions = cs.adjust_partition_estimate(metadata, estimated_partitions);
 507                 auto consumer = cs.make_interposer_consumer(metadata, 
 508                         [t = std::move(t), use_view_update_path, adjusted_estimated_partitions] (flat_mutation_reader reader) {
 509                     sstables::shared_sstable sst = use_view_update_path ? t->make_streaming_staging_sstable() : t->make_streaming_sstable_for_write();
 510                     schema_ptr s = reader.schema();
 511                     auto& pc = service::get_local_streaming_write_priority();
 512                     return sst->write_components(std::move(reader), std::max(1ul, adjusted_estimated_partitions), s,
 513                                                  sstables::sstable_writer_config{}, encoding_stats{}, pc).then([sst] {
 514                         return sst->open_data();
 515                     }).then([t, sst] {
 516                         return t->add_sstable_and_update_cache(sst);
 517                     }).then([t, s, sst, use_view_update_path]() mutable -> future<> {
 518                         if (!use_view_update_path) {
 519                             return make_ready_future<>();
 520                         }
 521                         return _view_update_generator->local().register_staging_sstable(sst, std::move(t));
 522                     });
 523                 });
 524                 return consumer(std::move(reader));
 525             });     
 526         },
 527         t.stream_in_progress());
 528     }    
```

**Comment by avikivity** [comment]
Already backported, removing label.
