### ISSUE TITLE
Scylla should refuse starting if its FS is missing

### ISSUE THREAD

**Issue by roydahan** [scylladb/scylla#6012]
*Installation details*
Scylla version (or git commit hash): 3.3.rc1-0.20200223.756574d0946 (but relevant since 2.3).
Cluster size: ANY
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

In case scylla starts when its FS is missing (/var/lib/scylla), the service is able to start but produces many errors like:
"ERR     | scylla: [shard 0] storage_proxy - Exception when communicating with 10.0.181.73: std::runtime_error (Can't find a column family with UUID 3cc8e850-57dd-11ea-9e81-00000000000c)"
And/or:
"Failed to load schema version"
"No space left on device"

This is reproducing every time longevity runs "RestartAndRepair" nemesis which is stoping i3 instance, causing it to lose its ephemeral disks and not able to mount the FS.
(The nemesis then later take care of it, fixing the FS mount and running a repair on the node).

**Comment by syuu1228** [comment]
Scylla already should refuse startup when /var/lib/scylla not mounted, by ff55e3c247a91ba5139f71f6e4ec6eef84563b76 (From 3.0)
Related: #3640


@roydahan Is there more logs while startup?
Does the instance have /etc/systemd/system/scylla-server.service.d/mounts.conf?

**Comment by roydahan** [comment]
One of our nemesis stops i3 instance (uses ephemeral drives).
When you stop such instance, it clears the ephemeral disk.
So, what we do in the nemesis is removing the **/var/lib/scylla** from fstab.
(otherwise, it waits on disk that doesn't exist and the node can't boot successfully).

So, I'm not sure if what we do is "legal" for your above solution, but it's possible.
In this case, scylla just starts and throws many errors.

So, to reproduce:
1. Start scylla on i3.large using AMI.
2. Comment out /var/lib/scylla in fstab.
3. Stop the instance.
4. Start the instance.

**Comment by syuu1228** [comment]
Okay I found ```RequiresMountsFor=/var/lib/scylla``` in /etc/systemd/system/scylla-server.service.d/mounts.conf does not prevent starting up scylla-server.service when /var/lib/scylla is removed from /etc/fstab.
But, I suppose correct usage of our AMI is not removing the entry from /etc/fstab.

**Comment by roydahan** [comment]
Make sense, thing is that it's the only way to boot the node after loosing the disk.
I guess we can disable Scylla if we want to workaround it.

**Comment by slivne** [comment]
@roydahan - sorry I'm lost if the FS is not mounted will scylla boot or not - are you removing something prior to reboot ?

**Comment by avikivity** [comment]
Agree that the bug is invalid. The fstab entry was used to prevent scylla from starting, you removed it, and it started.

**Comment by roydahan** [comment]
Yes, if the fstab is our way to prevent it from starting we can close the issue.
AFAIK, we don't have an easy way to handle this in our testing without commenting it first from the fstab.
