### ISSUE TITLE
Crash on attempt to access partition key in lightweight transaction SELECT

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#6016]
When evaluating the right shard for an unbounded select we assume there always is a partition key supplied in the query and crash on attempt to access it.

Backtrace:

https://pastebin.com/fpEmT4DF

Unchecked access:

https://github.com/scylladb/scylla/blob/master/cql3/statements/select_statement.cc#L342

How to reproduce: 
        self.create_ks(session=session1, name="lwt")   
        cql = "create table if not exists t (a int primary key)"                
        session.execute(cql)        
        session.execute(SimpleStatement("select * from t",         
                                         consistency_level=ConsistencyLevel.SERIAL))

**Comment by kostja** [comment]
Note that Cassandra will simply fool you it handles the query using serial consistency in this case:
cassandra@cqlsh:test> serial consistency serial
Serial consistency level set to SERIAL.
cassandra@cqlsh:test> select * from lwt;

 a
---
 1
 2
 3

(3 rows)

**Comment by avikivity** [comment]
In 4.0, lwt in 3.3 is experimental
