### ISSUE TITLE
Error while updating rows in table - Storage Proxy Exception

### ISSUE THREAD

**Issue by SaubereSache** [scylladb/scylla#6020]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.2.1-0.20200122.e3e301906d5
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 9

When updating a row of the table described below I get the following exception:
``Cassandra failure during write query at consistency LOCAL_ONE (1 responses were required but only 0 replica responded, 3 failed)``

The log file (``/var/log/syslog``) shows me the following error message:
``Mar 13 20:09:28 scylladb1 scylla:  [shard 1] storage_proxy - exception during mutation write to 10.4.0.2: std::out_of_range (vector::_M_range_check: __n (which is 7) >= this->size() (which is 7))``

``UPDATE applications SET audit_log_auth = '`XxXxXxXxX' WHERE id = cf42724a-0908-494f-89c6-db57ff4cb99e``

```
create table applications
(
    id             uuid primary key,
    app_metadata   frozen<application_metadata>,
    app_options    frozen<application_options>,
    audit_log_auth text,
    created_at     timestamp,
    filesystem     list<frozen<application_filesystem_entry>>,
    owner          uuid
)
    with caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
     and compaction = {'class': 'SizeTieredCompactionStrategy'}
     and compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
     and dclocal_read_repair_chance = 0.1
     and speculative_retry = '99.0PERCENTILE';

create index application_owner_index
    on applications (owner);
```

It used to work before, after I last used the table I did the following actions:
* Removed 2 fields
* Added the ``audit_log_auth`` field

**Comment by slivne** [comment]
- can you please run ```nodetool describecluster ``` so we can check that all nodes agree with the schema.
- can you please run ```desc schema``` so we can check the schema that exists in the cluster.
- can you please provide the full sequence of operations starting from the original schema - so we can try and reproduce on our end.

**Comment by SaubereSache** [comment]
Restarting all nodes in the cluster fixed it. Unable to reproduce.

**Comment by slivne** [comment]
@SaubereSache to try and reproduce this can you please try and provide the info requested here https://github.com/scylladb/scylla/issues/6020#issuecomment-600313774

**Comment by slivne** [comment]
closing this issue stale for 21 days
