### ISSUE TITLE
commitlog_test.TestCommitLog.test_mixed_mode_commitlog Fails

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla#6025]
Seen in dtest run on:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/424/testReport/commitlog_test/TestCommitLog/test_mixed_mode_commitlog/

From skimming through the dtest code and validating with @kostja it seams that validating 
that a periodic log is flushed upon submission to the batch log fails.

cc @kostja @gleb-cloudius

**Comment by kostja** [comment]
https://jenkins.scylladb.com/job/scylla-enterprise/job/next/480/testReport/junit/test_boost_commitlog_test.cc/test_boost_commitlog_test/test_commitlog_delete_when_over_disk_limit/

(another failure, possibly unrelated)

**Comment by gleb-cloudius** [comment]
The test operates under the false assumption. It assumes that lwt writes
persists all non lwt writes before it. First of all this is incorrect:
it happens to persist all lwt writes that happened on the same shard,
not all of them, but even that is an implementation detail that should
not be relied upon and definitely not set in stone by a test. Suggest
just delete the test altogether.

--
			Gleb.

**Comment by slivne** [comment]
@kostja  ?

**Comment by eliransin** [comment]
@kostja I agree with @gleb-cloudius , unless the is a cassandra parity issue here. AFIAR every time the issue of a mixed writes issue was discussed (LWT and non LWT) , we came to a conclusion that the behavior is undefined for this situation.

**Comment by gleb-cloudius** [comment]
On Tue, Mar 17, 2020 at 11:45:54PM -0700, Eliran Sinvani wrote:
> @kostja I agree with @gleb-cloudius , unless the is a cassandra parity issue here. AFIAR every time the issue of a mixed writes issue was discussed (LWT and non LWT) , we came to a conclusion that the behavior is undefined for this situation.
> 
The test writes into different partitions and this is well defined, but it
also guaranties nothing about durability of non lwt writes.

--
			Gleb.

**Comment by juliayakovlev** [comment]
This is explanation of @gleb-cloudius :
"LWT write flushes all non-LWT writes that come before it."

And:
> So this is part of the feature (not timing): all writes that came before
> LWT write, will be flushed?
>
Yes. You wrote "But running together with LWT writes, non-LWT looks like are flushed
immediately, like LWT". And what I was trying to clarify is that it is
true only for non-LWT writes that were done before an LWT write. But if
there was no LWT write after non-LWT one it may not be flushed.

So according to this I created the test: after 150 non-LWT writes arrived one LWT write and it flushed all previous non-LWT writes. After this LWT record I sent 50 non-LWT writes more and expect that it will not be flushed.

Is it not guarantiee tha previous non-LWT writes will be flushed?

**Comment by gleb-cloudius** [comment]
Here is your original question and my answer:

  > On Thu, Mar 5, 2020 at 5:56 PM Yulia Yakovlev <julia.yakovlev@scylladb.com>
  > wrote:
  >
  > > Hi Gleb,
  > > I added the tests for this "allow commitlog to wait for specific entries
  > > to be flushed on disk" feature.
  > > When I run just non-LWT inserts, then after node stop, part of the rows
  > > (or all) is missed. Always. It's expected
  > > But when I run non-LWT and LWT inserts together, I always find all rows,
  > > non-LWT and LWT, after node restart.
  > > Is it expected?
  > >
  It is expected to find all rows that were written before last LWT write.

So the answer stands. It is expected in certain situations to see
non-lwt entries to be flushed as well. It is guarantied as in "has to
happen and have to be tested to do so", nope it is implementation
detail that not even true in all circumstances.

--
			Gleb.

**Comment by juliayakovlev** [comment]
In case that it's not garantiee that non-LWT writes will be flushed, the test can validate LWT writes only (when exists both LWT and non-LWT writes)

**Comment by kostja** [comment]
Julia, I am assigning this to you since under any circumstances the fix is in the test, and not in the code. Please let me know if I should reassign.

**Comment by juliayakovlev** [comment]
> Julia, I am assigning this to you since under any circumstances the fix is in the test, and not in the code. Please let me know if I should reassign.

It's mine. Will change the test

**Comment by eliransin** [comment]
The issue was fixed in dtest - closing.
