### ISSUE TITLE
materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_low_to_half_test Fails

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla#6038]
The following tests are failing with the view containing less rows than expected.
The failing tests:
1. https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/429/testReport/junit/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_low_to_half_test/
2. https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/429/testReport/junit/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_half_to_low_test/
3. https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/429/testReport/junit/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_half_to_max_test/
I validated that the regular table contains all of the rows.
Bisection shows it is cause by fd49fd773 
/cc @psarna

**Comment by psarna** [comment]
Hm, that's interesting, fd49fd7 was intended to introduce **no** functional changes... all view updates are still performed in the background, just like before.

**Comment by psarna** [comment]
Oh wait, snap, of course, view building. That's true, here, the contract there was different - we kept waiting for the view updates to be applied... I didn't notice that `mutate_MV` was used in two places - once for generating view updates during writes in the background, and once for view building for generating view updates in the *foreground*. It's a bug, I'll fix it.

**Comment by eliransin** [comment]
@psarna you are too fast, but I was suspecting the same thing and wanted to start writing it here when your response popped.
I will still give myself a pet on the back for being only few steps behind you :laughing:

**Comment by bhalevy** [comment]
Let's add one of those test cases to next-gating once this bug is fixed to prevent regression.

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please backport to 4.0

Also, can you please add the a `Backport 4.0` label?

**Comment by bhalevy** [comment]
0c11e07faf4afb512096100893b0b5f3d82275b5 is in branch-4.0, removed "Backport candidate" label...
