### ISSUE TITLE
Size of row reported by mutation_fragment is only half of real size

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#6043]
Observed on: 325c3e13ebf
While investigating an [OOM](https://github.com/scylladb/scylla/issues/5994), I noticed that the `mutation_fragment::data::_size_in_bytes` is only half of the number one arrives at if one iterates over all the cell storage referenced by all cells in the row.
See [this comment](https://github.com/scylladb/scylla/issues/5994?email_token=AAKTFWIJBEXH6ZLPWCPSQI3RG537HA5CNFSM4LEVMSP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEOPIDRQ#issuecomment-600698880) and the ones after it in the above mentioned [issue #5994](https://github.com/scylladb/scylla/issues/5994).

**Comment by denesb** [comment]
Possible causes:
* A mistake in my `gdb` script - there is no bug at all.
* A mistake in the memory accounting of `row`. Minor impact, we are not using this as input for tracking the memory consumption of readers yet. Some readers might have larger buffers then they think they have, but at the cell-size we are seeing in this issue, this is not a problem, a single cell is larger then the targeted buffer size anyway.
* A mistake in the code allocating memory for fragmented cell storage. Major impact, as this would mean we are using twice the amount of memory to store already large cells.

**Comment by denesb** [comment]
I'm looking more closely into this as part of my work of improving the accuracy of reader memory tracking (#4176). It looks like it's the latter case (we allocate more memory than we mean). To the extent to what my brain is capable to parse IMR code, it looks like IMR wants to allocate 8KB chunks but ends up allocating 8KB + 8 byte which results in a 16KB allocation and hence practically double memory consumption.

**Comment by avikivity** [comment]
Good catch. I recommend backing up your brain before looking at IMR code though.

**Comment by denesb** [comment]
Actually it allocates 8KB + 2 * sizeof(void*), but I can't see in the code where the other is coming from -- although I can see it in object graphs, the chunks form an intrusive double linked list.

**Comment by denesb** [comment]
@avi why does a `2 * sizeof(void*)` overshoot result in a 16K allocation? We have 10K and 12K size classes as well. I wrote a little program to see what allocation seastar actually makes for the above mentioned overshoot for the larger (small) size classes:
```c++
#include <malloc.h>
#include <iostream>
#include <cassert>
#include <seastar/core/memory.hh>

const uint64_t sizes[] = {
    1024,
    1280,
    1536,
    1792,
    2048,
    2560,
    3072,
    3584,
    4096,
    5120,
    6144,
    7168,
    8192,
    10240,
    12288,
    14336,
    16384};

int main(int argc, char** argv) {
    const auto alignment = sizeof(void*);
    for (const auto size : sizes) {
        std::cout << size;
        void* ptr_exact;
        void* ptr_overshoot;
        assert(!posix_memalign(&ptr_exact, alignment, size));
        assert(!posix_memalign(&ptr_overshoot, alignment, size + 2 * sizeof(void*)));
        std::cout << " exact=" << malloc_usable_size(ptr_exact);
        std::cout << " overshoot=" << malloc_usable_size(ptr_overshoot);
        std::cout << std::endl;
    }
    return 0;
}
```

The output:
```
1024 exact=1024 overshoot=2048
1280 exact=2048 overshoot=2048
1536 exact=2048 overshoot=2048
1792 exact=2048 overshoot=2048
2048 exact=2048 overshoot=4096
2560 exact=4096 overshoot=4096
3072 exact=4096 overshoot=4096
3584 exact=4096 overshoot=4096
4096 exact=4096 overshoot=8192
5120 exact=8192 overshoot=8192
6144 exact=8192 overshoot=8192
7168 exact=8192 overshoot=8192
8192 exact=8192 overshoot=16384
10240 exact=16384 overshoot=16384
12288 exact=16384 overshoot=16384
14336 exact=16384 overshoot=16384
16384 exact=16384 overshoot=32768
```

**Comment by denesb** [comment]
It looks like aligned allocations are always a power of two. On second thought there is a comment saying exactly this in `memory.cc`:
```c++
void* allocate_aligned(size_t align, size_t size) {
    if (size <= sizeof(free_object)) {
        size = std::max(sizeof(free_object), align);
    }
    void* ptr;
    if (size <= max_small_allocation && align <= page_size) {
        // Our small allocator only guarantees alignment for power-of-two
        // allocations which are not larger than a page.
        size = 1 << log2ceil(object_size_with_alloc_site(size));
        ptr = get_cpu_mem().allocate_small(size);
    } else {
        ptr = allocate_large_aligned(align, size);
    }
    if (!ptr) {
        on_allocation_failure(size);
    } else {
#ifdef SEASTAR_DEBUG_ALLOCATIONS
        std::memset(ptr, debug_allocation_pattern, size);
#endif
    }
    ++g_allocs;
    return ptr;
}
```

**Comment by avikivity** [comment]
> It looks like aligned allocations are always a power of two. On second thought there is a comment saying exactly this in `memory.cc`:

But why would IMR be doing an aligned allocation here?

**Comment by denesb** [comment]
IMR is using `utils::allocation_strategy`, and the `utils::standard_allocation_strategy` uses aligned allocations:
https://github.com/scylladb/scylla/blob/764866ed020984da6095f8027c7ad897b19de4e9/utils/allocation_strategy.hh#L187-L200

**Comment by denesb** [comment]
Maybe we should make an unaligned allocation if `alignment` is 0 here.

**Comment by avikivity** [comment]
I think we can relax our allocator to use standard allocation if the alignment requirement is satisfied by standard alignment.

**Comment by avikivity** [comment]
And also, we should hack imr to allocate a block that wouldn't leave any waste.

**Comment by denesb** [comment]
> And also, we should hack imr to allocate a block that wouldn't leave any waste.

Agree, patch is already on the list: [PATCH v1] data/cell: don't overshoot target allocation sizes

**Comment by avikivity** [comment]
Not a regression, and not critical (even 2X under-estimate only results in a little more memory usage) so not backporting.
