### ISSUE TITLE
Compaction Backlog controller will misbehave for time series use cases

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6054]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): df8b3cd5dc1a2
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Using TTL result in sstables being eventually fully expired. When compaction selects those, it can be seen that the backlog only keeps growing even though fully expired sstables are constantly purged and the data size remains roughly the same.

![out](https://user-images.githubusercontent.com/1409139/77230590-10c5d380-6b74-11ea-9f61-02bd61c77be4.png)

schema:
CREATE TABLE keyspace1.standard1 (
    key blob PRIMARY KEY,
    "C0" blob,
    "C1" blob,
    "C2" blob,
    "C3" blob,
    "C4" blob
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 30
    AND gc_grace_seconds = 0
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

**Comment by slivne** [comment]
using STCS for this king of workload seems wrong users should be using TWCS for this kind of workload.

Does this issue also exist in TWCS.

**Comment by raphaelsc** [comment]
@slivne the leakage happens outside any strategy-specific implementation of backlog tracker, which means TWCS is also affected.

**Comment by raphaelsc** [comment]
The side effect of this bug is that compaction will potentially steal resources from other system components even when the *actual* compaction backlog is very low, leading to an unstable state.

**Comment by raphaelsc** [comment]
![unnamed](https://user-images.githubusercontent.com/1409139/79627720-ff3eff80-8110-11ea-9b01-4eba2c74e071.png)

**Comment by raphaelsc** [comment]
![out](https://user-images.githubusercontent.com/1409139/79627860-4a0d4700-8112-11ea-920b-fb08bf0f2c58.png)

**Comment by raphaelsc** [comment]
That's a terrible bug I need to fix, as backlog will be keep growing to the sky, and so compaction will be dominate the resources, even though there's actually no work to do. A restart can alleviate this issue, but it's a matter of time for that scenario to be installed   again. Will try to provide a fix for this next week. This potentially affects all TWCS users.

@avikivity @bhalevy

**Comment by raphaelsc** [comment]
This fix become even more need after CDC, which uses TWCS, and not fixing this could affect system stability as compaction can steal resources from other components even when the actual compaction backlog is low.

**Comment by slivne** [comment]
@bhalevy / @raphaelsc is this still relevant ?

**Comment by raphaelsc** [comment]
On Mon, Feb 15, 2021 at 4:39 AM Shlomi Livne <notifications@github.com>
wrote:

> @bhalevy <https://github.com/bhalevy> / @raphaelsc
> <https://github.com/raphaelsc> is this still relevant ?
>

yes, because of it, shares may be higher than needed. we need to increase
priority of this issue as it may cause all compactions in the node to be
more aggressive than needed (if there's an active TWCS table)

**Comment by slivne** [comment]
@avikivity you approved this patch to be backport to 4.4

**Comment by avikivity** [comment]
Backported to 4.4.
