### ISSUE TITLE
unbalanced token in repair_option_pr_multi_dc_test

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6063]
Seen a few times, most recently in dtest-release: 
https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/431/testReport/repair_additional_test/RepairAdditionalTest/repair_option_pr_multi_dc_test/
```
False is not true : expected pr repair to repair between 1050 to 1300 rows, but count is 1568
```

According to @asias, the node log confirms that:
```
INFO 2020-03-19 04:09:06,625 [shard 1] repair - repair id 1 on shard 1 stats: ranges_nr=257, sub_ranges_nr=257, round_nr=337, round_nr_fast_path_already_synced=257, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=80, rpc_call_nr=7940, tx_hashes_nr=0, rx_hashes_nr=663, duration=4.019 seconds, tx_row_nr=2615, rx_row_nr=300, tx_row_bytes=491620, rx_row_bytes=56400, row_from_disk_bytes={{127.0.52.1, 53204}, {127.0.52.2, 56400}, {127.0.52.3, 0}, {127.0.52.4, 0}, {127.0.52.5, 0}, {127.0.52.6, 0}}, row_from_disk_nr={{127.0.52.1, 283}, {127.0.52.2, 300}, {127.0.52.3, 0}, {127.0.52.4, 0}, {127.0.52.5, 0}, {127.0.52.6, 0}}, row_from_disk_bytes_per_sec={{127.0.52.1, 0.0126249}, {127.0.52.2, 0.0133832}, {127.0.52.3, 0}, {127.0.52.4, 0}, {127.0.52.5, 0}, {127.0.52.6, 0}} MiB/s, row_from_disk_rows_per_sec={{127.0.52.1, 70.4155}, {127.0.52.2, 74.6454}, {127.0.52.3, 0}, {127.0.52.4, 0}, {127.0.52.5, 0}, {127.0.52.6, 0}} Rows/s, tx_row_nr_peer={{127.0.52.2, 283}, {127.0.52.3, 583}, {127.0.52.4, 583}, {127.0.52.5, 583}, {127.0.52.6, 583}}, rx_row_nr_peer={{127.0.52.2, 300}}


INFO 2020-03-19 04:09:05,814 [shard 0] repair - repair id 1 on shard 0 stats: ranges_nr=257, sub_ranges_nr=257, round_nr=319, round_nr_fast_path_already_synced=257, round_nr_fast_path_same_combined_hashes=0, round_nr_slow_path=62, rpc_call_nr=7582, tx_hashes_nr=0, rx_hashes_nr=540, duration=3.219 seconds, tx_row_nr=2552, rx_row_nr=268, tx_row_bytes=479776, rx_row_bytes=50384, row_from_disk_bytes={{127.0.52.1, 55648}, {127.0.52.2, 50384}, {127.0.52.3, 0}, {127.0.52.4, 0}, {127.0.52.5, 0}, {127.0.52.6, 0}}, row_from_disk_nr={{127.0.52.1, 296}, {127.0.52.2, 268}, {127.0.52.3, 0}, {127.0.52.4, 0}, {127.0.52.5, 0}, {127.0.52.6, 0}}, row_from_disk_bytes_per_sec={{127.0.52.1, 0.0164865}, {127.0.52.2, 0.014927}, {127.0.52.3, 0}, {127.0.52.4, 0}, {127.0.52.5, 0}, {127.0.52.6, 0}} MiB/s, row_from_disk_rows_per_sec={{127.0.52.1, 91.954}, {127.0.52.2, 83.2557}, {127.0.52.3, 0}, {127.0.52.4, 0}, {127.0.52.5, 0}, {127.0.52.6, 0}} Rows/s, tx_row_nr_peer={{127.0.52.2, 296}, {127.0.52.3, 564}, {127.0.52.4, 564}, {127.0.52.5, 564}, {127.0.52.6, 564}}, rx_row_nr_peer={{127.0.52.2, 268}}
```

> node2 indeed sent 300+268= 568 rows to node1 during repair.
>
> Perhaps, this is due to a very unbalanced tokens.

Other instances of this issue:
https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/412/testReport/repair_additional_test/RepairAdditionalTest/repair_option_pr_multi_dc_test/

https://jenkins.scylladb.com/job/scylla-master/job/dtest-debug/429/testReport/repair_additional_test/RepairAdditionalTest/repair_option_pr_multi_dc_test/

**Comment by asias** [comment]
I think it is the test is not reliable.

What the test does:

```
n1 n2 n3 n4 n5 n6
rf = dc1:2 dc2:2 dc3:2
write 1000 row to node1 only
write 1000 row to node2 only
start all nodes
repair on node11
stop node2
query on node2 with local_one
```


The rf is dc1:2 dc2:2 dc3:2. So each row in keyspace ks will be stored on all the 6 nodes.

node1 will repair 256 ranges out of 256*6 ranges. In theory, node1 will get only 1/6 of the data from node2 which is inserted to node2 only. 
However, the key is between 2000, 3000. There is no guarantee that the data will be distributed to the 256*6 ranges evenly. It is quite possible more than 1/6 of  the 1000 keys are distributed to the primary ranges owned by node1. Because the key space is so small. 

It is easier to consider there is 1 token per node.  We have 6 ranges in total. Nothing guarantees that the 1000 key be distributed to the 6 ranges evenly. With 256 ranges per node, the possibility increases, but still. We can get unevenly distribution with a small key space.

**Comment by bhalevy** [comment]
@asias coming to think about, with this multi-dc RF why is repiar only for ~1/6 and not ~1/2, since there are only 2 nodes in each dc?

**Comment by asias** [comment]
> @asias coming to think about, with this multi-dc RF why is repiar only for ~1/6 and not ~1/2, since there are only 2 nodes in each dc?

The rf is dc1:2 dc2:2 dc3:2, for any key, the key will be stored on all the 6 nodes. The repair starts with the -pr option, which asks the node to repair only the primary ranges. A primary range is a range that a node is the first one in the list of nodes that  calculate_natural_endpoints returns. n1 owns 1/6  of all the ranges as primary range.

**Comment by bhalevy** [comment]
> > @asias coming to think about, with this multi-dc RF why is repiar only for ~1/6 and not ~1/2, since there are only 2 nodes in each dc?
> 
> The rf is dc1:2 dc2:2 dc3:2, for any key, the key will be stored on all the 6 nodes. The repair starts with the -pr option, which asks the node to repair only the primary ranges. A primary range is a range that a node is the first one in the list of nodes that calculate_natural_endpoints returns. n1 owns 1/6 of all the ranges as primary range.

Ah, I presumed that the primary range is per dc, not cluster global...
