### ISSUE TITLE
Gcc compile source code of scylla and use cpu 100%，but compiling-Program jammed

### ISSUE THREAD

**Issue by dongyujun** [scylladb/scylla#6064]
when compiling scylla，cpu is used about 100%  and compiling-Program  is jammed。After waittting for a long time，it remains jammed.

scylla version : 3.1.2
compiling use 8 cpu,and memory is 32G.

**Comment by nyh** [comment]
Please give more details. What does " jammed" mean - is it very slow but eventually completes? Does it never complete? On **which source file** does it hang (you can do "ps auxww" to see which compilations are active)? What version of gcc are you using (`gcc --version`).

Finally, minus some rare gcc bug that causes it to go into an infinite loop (we never saw such a problem before), the most likely explanation is that are running out of memory, and swapping started making the compilation extremely slow. The amount of memory used depends on the concurrency of the build. Try running "ninja -j4" to allow only four concurrent compilations, and see if that helps. If it works, try a higher number next time. Ninja's default is the number of CPUs plus two, i.e., "-j10" in your case.

**Comment by slivne** [comment]
@dongyujun if you still have an issue and can share more info requested we would be happy to help


I am closing this issue as its stale
