### ISSUE TITLE
Support SSL Certificate Hot Reloading

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#6067]
Scylla version (or git commit hash): 3.4

Support hot reloading of SSL Certificates, perdiacly and using `nodetool reloadssl` command
See http://cassandra.apache.org/doc/latest/operating/security.html#ssl-certificate-hot-reloading

**Comment by tzach** [comment]
Example: using https://letsencrypt.org/ to generate the Certificates that expire every 60 days

**Comment by mailmahee** [comment]
another customer who has requested this feature is Dexcomm and they are using vault for this
https://www.hashicorp.com/blog/certificate-management-with-vault/

**Comment by amoskong** [comment]
nodetool doesn't have this subcmd : `nodetool reloadssl`


```
scylla-tools-core-666.development-20200412.2f73d3ae377.noarch
scylla-tools-666.development-20200412.2f73d3ae377.noarch
scylla-tools-core-666.development-20200412.2f73d3ae377.noarch
```

It exists in Apache Cassandra.
```
[apache-cassandra]$ git grep reloadssl
debian/nodetool-completion:            reloadssl
doc/source/operating/security.rst:Certificate Hot reloading may also be triggered using the ``nodetool reloadssl`` command. Use this if you want to Cassandra to
src/java/org/apache/cassandra/tools/ReloadSslCertificates.java:@Command(name = "reloadssl", description = "Signals Cassandra to reload SSL certificates")
[apache-cassandra]$ git remote -v
origin	https://github.com/apache/cassandra (fetch)
origin	https://github.com/apache/cassandra (push)
```

**Comment by elcallio** [comment]
The implementation as it is currently done uses file watches to monitor file changes. It should effectively make reloadssl redundant, as there is no real delay between a file changing and reloading happening (i.e. it is not a poll mechanism).

**Comment by tzach** [comment]
@elcallio to validate: the PR doesn **not** include  `nodetool reloadssl` just fiel watch

**Comment by elcallio** [comment]
No `nodetool reloadssl`, but again: not needed. Certificate reloading should be instantaneous.

**Comment by avikivity** [comment]
Not a bug, so not backporting.
