### ISSUE TITLE
Add nodetool scrub command

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#6072]
Scylla version (or git commit hash): 3.3

**Comment by tzach** [comment]
The command was disabled in https://github.com/scylladb/scylla-tools-java/commit/e36f2228
Now Scylla has REST API support, and we should enable it

**Comment by tzach** [comment]
https://github.com/scylladb/scylla/issues/5487
https://github.com/scylladb/scylla-docs/issues/2484

**Comment by slivne** [comment]
fixed by scylladb/scylla-tools-java@e5c911381acb324c6d6a58810328880b90c8ab60
