### ISSUE TITLE
scylla in Docker WARNING: unable to mbind shard memory; performance may suffer:

### ISSUE THREAD

**Issue by yuqin11** [scylladb/scylla#6085]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --num-io-queues=1 --io-properties-file=/etc/scylla.d/io_properties.yaml --memory 8G --smp 4 --listen-address 0.0.0.0 --rpc-address 0.0.0.0 --seed-provider-parameters seeds=172.16.16.30 --broadcast-address 172.16.16.30 --broadcast-rpc-address 172.16.16.30 --blocked-reactor-notify-ms 999999999

Disks: HDD

this is the start log

`WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: WARNING: unable to mbind shard memory; performance may suffer: WARNING: unable to mbind shard memory; performance may suffer: 

WARNING: unable to mbind shard memory; performance may suffer: WARNING: unable to mbind shard memory; performance may suffer: 

WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARNING: unable to mbind shard memory; performance may suffer: 
WARN  2020-03-13 12:34:48,905 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
INFO  2020-03-13 12:34:49,846 [shard 0] iotune - /var/lib/scylla/data passed sanity checks
WARN  2020-03-13 12:34:49,847 [shard 0] iotune - nomerges for /sys/devices/pci0000:00/0000:00:05.0/virtio2/block/vdb/queue/nomerges set to 0. It is recommend to set it to 2 before evaluation so that merges are disabled. Results can be skewed otherwise.
Starting Evaluation. This may take a while...
Measuring sequential write bandwidth: 131 MB/s
Measuring sequential read bandwidth: 130 MB/s
Measuring random write IOPS: 3372 IOPS
Measuring random read IOPS: 3355 IOPS
Recommended --num-io-queues: 1
`

**Comment by slivne** [comment]
@penberg can you please try and assist

**Comment by slivne** [comment]
seems to be related to #6017 - closing this till we resolve #6017
