### ISSUE TITLE
Rename "in_progress_ballot" in systen.paxos table to "promise"

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#6087]
*Installation details*
Scylla version (or git commit hash): 7ed083a6a79fc33c832d30e6318b72a814fe3699

The value that is stored in "in_progress_ballot" cell is the value of
promised ballot, so call the cell accordingly to avoid confusion
especially as we have a notion of "in progress" proposal in the code
which is not the same as in_progress_ballot here.

**Comment by slivne** [comment]
I am not sure I am in favor of renaming a system table column that we inherited from C* - although the raw content is scylla specific, tools may expect the specific structure.

**Comment by avikivity** [comment]
In 4.0. 3.3 lwt was experimental, not backporting.
