### ISSUE TITLE
Provide packages for Ubuntu 15.10

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#609]
Currently only Ubuntu 14 packages are provided
http://www.scylladb.com/download/#installing-scylla-on-ubuntu-1404

This is a problem for users who are already using Ubuntu 15

**Comment by syuu1228** [comment]
We haven't provided package for Ubuntu 15+ yet, but Ubuntu 15.10 works after https://github.com/scylladb/scylla/commit/1eebe8bce143a3aec41de22ecabb939b3c4a239d merged.

**Comment by syuu1228** [comment]
Since 16.04LTS released 15.10 is not latest release anymore, so I think we should focus 16.04.
https://github.com/scylladb/scylla/issues/1007

**Comment by tzach** [comment]
16.04 is the right Ubuntu release in the long/mid term, but it is still new, and will take users time to move to it.
Many users are using 15.10 on their desktop, and wants to evaluate Scylla.
To conclude, we need both.

**Comment by syuu1228** [comment]
Nightly build is added for Ubuntu 15.10
https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/wily/master/3/scylla.list

**Comment by syuu1228** [comment]
Since we decided to delete Ubuntu 15.10 build jenkins job, I think we don't need this issue anymore. Please close it.

**Comment by tzach** [comment]
Closing. This issue was relevant before Ubuntu 16 was available and is not relevant any more.
