### ISSUE TITLE
Unable to connect with datastax cpp_driver

### ISSUE THREAD

**Issue by skeetor** [scylladb/scylla#6099]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.11
Cluster size: 
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 9.6

I have installed the scylla server on my Debian 9.6 machine. I could connect with the cqlsh tool and create a table and select from it. Now I compiled the source from https://github.com/datastax/cpp-driver which I understood to be the prefered way to go. Now when I try to run i.E.  examples/simple the connection hangs and wont come back in this line:

    if (cass_future_error_code(connect_future) == CASS_OK)

Any help appreciated as I'm a bit at a loss how to proceed.

I captured a PCAP file from both applications, as I wanted to see if there is some difference. Since I don't know the protocol, I didn't notice something obvious (to me). If this helps I can attach the two files.

**Comment by skeetor** [comment]
I also tried the sample on Ubuntu 16.04 and it shows the same behavior.

**Comment by dorlaor** [comment]
You're using LWT, need to enable --experimental flag for it in <= 3.3
releases.
The upcoming 4.0 has it in GA. Pls report if it's solved and turn on some
logging too

**Comment by skeetor** [comment]
Thanks for your response!

What do you mean by "I'm using LWT"? What is that and how can I disable it? Or do I have to enable it with that switch? I assume this "--experimental" is when I compile the cpp_driver? Or is this on the server side?

**Comment by skeetor** [comment]
I found now the solution to the problem. After comparing the release notes, I noticed this:
    [CPP-914] Possible for a WaitForHandler's on_set() method to be called after timeout/error

So I downgraded to 2.15.0 and this works now. I don't know if this indicates a bug in your latest release, or just some missmatch with my scallydb version, but for me this issue seems to be relsolved for now.

**Comment by dorlaor** [comment]
Please scratch my comment (note to self, don't write at 1am, I read
CASS as Cas as compare and swap..).

CPP-914 looks like a fix in connection timeout code and indeed is
directly related.
I'd test with a new Scylla 3.3 (3.0 is end of life), if the problem
persists, check also with new Cassandra
and report it to the driver project.

**Comment by jul-stas** [comment]
This is a bug with 2.15.1 driver. A more detailed discussion can be found here: https://github.com/scylladb/scylla/issues/6476
The solution is to use 2.15.2 or 2.15.0, so I'm closing.
