### ISSUE TITLE
compaction failed: read exception: sstables::malformed_sstable_exception (FIXME COUNTER_MASK)

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#610]
I am using current master (c3f03d5c96cf02a3235bada4fb466332fc295396) and running scylla with the following flags:
```
build/release/scylla -c1 -m1G
```
When I run `cassandra-stress write` after a while error messages like the one below start to appear:
```
ERROR [shard 0] compaction_manager - compaction failed: read exception: sstables::malformed_sstable_exception (FIXME COUNTER_MASK)
```

**Comment by avikivity** [comment]
How long is "a while"?  Is this repeatable?

I think this is a regression, so a bisect may help.

**Comment by pdziepak** [comment]
Yes, I get it every time. First message appears after ~3 minutes.
Bisecting right now.

**Comment by pdziepak** [comment]
I am at bb1470f0d4a21c5753d79935f262f940a07c2167 right now and see the following message instead of the one from the original post. Bisecting continues...
```
ERROR [shard 0] compaction_manager - compaction failed: read exception: std::bad_alloc (std::bad_alloc)
```

**Comment by nyh** [comment]
On Wed, Nov 25, 2015 at 4:05 PM, Paweł Dziepak <notifications@github.com>
wrote:

> I am using current master (c3f03d5
> <https://github.com/scylladb/scylla/commit/c3f03d5c96cf02a3235bada4fb466332fc295396>)
> and running scylla with the following flags:
>
> build/release/scylla -c1 -m1G
>
> When I run cassandra-stress write after a while error messages like the
> one below start to appear:
>
> ERROR [shard 0] compaction_manager - compaction failed: read exception: sstables::malformed_sstable_exception (FIXME COUNTER_MASK)
>
>
This is really surprising because it indicates we found a counter which we
shouldn't have.
Instead, it is more likely you were out of memory (like your other mail
suggests) and somehow this caused this COUNTER_MASK thing. But we need to
understand why. I can't figure out how this could have happened.

**Comment by slivne** [comment]
@pdziepak  did you find the source  ?

**Comment by pdziepak** [comment]
On 29 November 2015 at 12:06, slivne <notifications@github.com> wrote:

> @pdziepak <https://github.com/pdziepak> did you find the source ?
>
This actually has got weird. Sometimes the failure didn't happen (or
happened much earlier), not like I previously said that it is 100%
reproducible in the first minutes of cassandra-stress run and that's what
ruined my bisection. I noticed also that the problem happens only on one
disk. I've tested with different disk on the same machine and a completely
different machine and it never happened. The strange thing is that the disk
doesn't seem to cause any trouble with other tools (I've run fio with
verify for a while), smartctl doesn't show anything suspicious as well.

I will test some more, but it is very probable that this is not a Scylla
bug.

**Comment by pdziepak** [comment]
I've been unable to reproduce this issue on the exactly same hardware configuration on which it did happen before and I've been running cassandra-stress for much longer than it usually took to get that error message. My best bet is that it was some driver bug (since I never got that error on different disks) that has been fixed since, but to be honest I have no real idea what was going on there.
However, without a way to reproduce it I guess there is not much more we can do about it, so I think the issue can be closed.
