### ISSUE TITLE
Empty partition keys make nodes unbootable

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#6106]
Observed with 3.1 but applies to master as well.

In theory we shouldn't have empty keys in the database, as we validate all keys that enter the database via CQL with `validation::validate_cql_keys()`, which will reject empty keys. In this context, empty means a single-component key, with its only component being empty.

Yet recently we've seen empty keys appear in a cluster and wreak havoc on it, as they will cause the memtable flush to fail due to the sstable summary rejecting the empty key. This will cause an infinite loop, where Scylla keeps retrying to flush the memtable and failing. The intermediate consequence of this is that the node cannot be shut down gracefully. The indirect consequence is possible data loss, as commitlog files cannot be replayed as they just re-insert the empty key into the memtable and the infinite flush retry circle starts all over again. A workaround is to move problematic commitlog files away, allowing the node to start up. This can however lead to data loss, if multiple replicas had to move away commitlogs that contain the same data.

The solution is to check for the emptiness of keys in more places, as well as ignore entries with empty keys when replaying the commitlog.

**Comment by tarzanek** [comment]
@avikivity can we backport this to 4.0 and 2020.1 ?

**Comment by avikivity** [comment]
@tarzanek we don't discuss enterprise on this tracker, and if you want something this large backported, you must justify it.

**Comment by tarzanek** [comment]
this is an upgrade blocker for https://github.com/scylladb/scylla-enterprise/issues/1301 ... 
(and I dare to say this isn't that large, it's just validation for commitlog replay, unless there is something I am missing (and thanks for clarification))

**Comment by avikivity** [comment]
we don't discuss enterprise on this tracker,

**Comment by avikivity** [comment]
Aged out.
