### ISSUE TITLE
key linearization is confusing

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#6108]
Keys (partition and clustering keys) use `managed_bytes` as their storage type. This suggests that they might have values that are large enough to be fragmented, and that great care has to be taken when using them, to provide a valid `managed_bytes::linearization_context` through `with_linearized_managed_bytes()` when accessing their value in linearized form.

Yet, `compound_wrapper` and by extension `partition_key` and `clustering_key_prefix` is full of hidden linearizations happening. To mention an example `partition_key::begin()` and `partition_key::end()` quietly linearise the key representation, yet this is mentioned nowhere in the entire `keys.hh`, what's worse, this won't even be apparent when looking at methods themselves as the linearisation happens in `compound_type::iterator` to which the `representation()` is passed down. Which brings me to the next problem.

`compound_wrapper` has an implicit `operator TopLevelView()`. In the case of `partition_key` this resolves to `partition_key_view`. This implicit conversion involves linearising the key's representation. Heck, even `managed_bytes` has an implicit `operator bytes_view()`.

All this smells like a huge landmine. Stuff happens to work, because in practice we have no fragmented keys at all. Keys are only fragmented inside LSA to begin with, and in practice not even there, as the max contiguous allocation size of LSA is larger than the max key size.

I think we should do one of two things:
* Don't pretend we support keys large enough to be fragmented. This would lead to significant simplification of the code.
* If we still want to support such large keys, we should mean it and make our code around keys safer.

I favour the first approach as the key size seems to be an ABI that is not likely to change anytime soon.

**Comment by tgrabiec** [comment]
I'm in favor of the first option as well.

**Comment by bhalevy** [comment]
I'm also in favor of limiting support to non-fragmented keys at this time.

**Comment by denesb** [comment]
@avikivity pointer out in https://groups.google.com/d/topic/scylladb-dev/vnO-Jps-XBg/discussion that I overlooked an important detail and in fact we can have fragmented keys. I will do some tests to check the effects of using keys large enough to be fragmented.

**Comment by avikivity** [comment]
Suppose some has a key large enough to require fragmentation. If we stopped supporting it, their database would stop working once they upgraded.

**Comment by avikivity** [comment]
Note that managed_bytes is only fragmented inside cache and memtables. Once you copy it out, it is not fragmented.

**Comment by denesb** [comment]
@avikivity the proposed solution is not to restrict key size, which like you said is quite problematic, but to simply always allocate keys contiguously, do away with the whole fragmentation ordeal.

**Comment by avikivity** [comment]
We fragment keys for LSA, which requires it.

**Comment by denesb** [comment]
Does it strictly require that all objects are fragmented with the same fragment size? Or would the max key size be too large of an allocation for LSA?

**Comment by avikivity** [comment]
We could relax it to 256k - espilon (segment size). The penalty is a lot of wastage in extreme cases. Since a key cannot be larger than 64k, in extreme cases we'd have 75% occupancy instead of the worst case 90% we have now. We also lost forward-progress guarantees, today we can take 10 segments with 80% occupancy and end up with 9 segments at 90% occupancy, but now we can start with 10 @ 80% and end with 10 @ 80%.

Are fragmented keys in cache a problem? We don't touch them a lot.

**Comment by denesb** [comment]
My problem is with the key API, where certain methods have different preconditions in cache/memtables and outside. This leads to confusion, people either:
* Think that keys can be really fragmented anywhere and start using `with_linearized_managed_bytes()` where it is not necessary.
* Think that keys are de-facto linear and don't use `with_linearized_managed_bytes()` at all.
* Have no idea about this whole ordeal. This is very likely as many methods sneakily linearise the key behind the scenes.

Also fragmented keys are one the two remaining roadblocks in getting rid of `managed_bytes::linearize()` and friends. The other being de/serialization in our type-system.

**Comment by michoecho** [comment]
I think this issue was fixed by #7820 and can be closed.

**Comment by denesb** [comment]
Yes, indeed.
