### ISSUE TITLE
Consider disabling dc_local_read_repair_chance by default

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#6109]
`dc_local_read_repair_chance` is a legacy of old times: Cassandra itself now defaults to zero, and we should look into that too.

Most serious production clusters are either repaired through our asynchronous repair, or don't need repair at all.

Synchronous read repair can help things converging, but it implies an impact at query time. For clusters that are on an asynchronous repair schedule this should not be needed.

**Comment by gleb-cloudius** [comment]
On Tue, Mar 31, 2020 at 11:20:59AM -0700, Glauber Costa wrote:
> `dc_local_read_repair_chance` is a legacy of old times: Cassandra itself now defaults to zero, and we should look into that too.
> 
Cassandra deprecated both local and global probabilistic read repairs in https://issues.apache.org/jira/browse/CASSANDRA-13910

And we have this  https://github.com/scylladb/scylla/issues/3502, so
this issue may be considered as a dup.

--
			Gleb.

**Comment by avikivity** [comment]
This is a default change, not a fix, so not backporting.
