### ISSUE TITLE
multi_counter_update_test sometimes fails to select counter_one in debug mode

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6112]
Test first regression in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/434/testReport/counter_tests/TestCounters/multi_counter_update_test/
Scylla version cb26de89a173e3538e42b2a22f174963f888de22
```
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/counter_tests.py", line 253, in multi_counter_update_test
    self.assertEqual(v, count[0][0])
IndexError: list index out of range
```

I don't see anything wrong with the test at first glance so I'm filing this against scylla until proven otherwise.
I'll improve the assert message just in case.

Happened again in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/439/testReport/counter_tests/TestCounters/multi_counter_update_test/
FWIW, I also see no error in the node logs.

**Comment by jul-stas** [comment]
I ran the test on debug build over 1000 times - no error so far. And I don't think that counters would fail in such a simple scenario - it's a solid piece of code and we would detect such error much earlier. So there must be another factor at play.

@bhalevy do you have any hints/ideas what might be the "another factor"? If not, then I'm afraid that we'll have to wait until the assert fires.

**Comment by bhalevy** [comment]
> I ran the test on debug build over 1000 times - no error so far. And I don't think that counters would fail in such a simple scenario - it's a solid piece of code and we would detect such error much earlier. So there must be another factor at play.
> 
> @bhalevy do you have any hints/ideas what might be the "another factor"? If not, then I'm afraid that we'll have to wait until the assert fires.

@jul-stas No, sorry.  I don't even have a speculation...

**Comment by slivne** [comment]
closing this issue - till the issue happens again and the assert fires
