### ISSUE TITLE
This part of the code will drop into interactive query about the NIC whether it was in the --nic arg or not

### ISSUE THREAD

**Issue by dyasny** [scylladb/scylla#6119]
https://github.com/scylladb/scylla/blob/0b23e7145d05c6b49a66bb2197ea0eff8ab16d95/dist/common/scripts/scylla_setup#L376

Observed at a customer install, workaround to go completely non-interactive is to use `--no-sysconfig-setup` which isn't very healthy

**Comment by dyasny** [comment]
CentOS Linux release 7.7.1908 (Core)
Scylla 3.2.2

**Comment by dyasny** [comment]
setting FT2 tag @vladzcloudius please change if you think it'a more urgent

**Comment by vladzcloudius** [comment]
@dyasny Could you, please, describe how the problem manifests itself?

**Comment by dyasny** [comment]
Not reproducing internally, closing.
