### ISSUE TITLE
Alternator: make sure users can access the system tables providing them info on their apps

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#6122]
We have many system tables that are used by developers to check their application behavior.

It would be preferable if this is exposed via the alternator api

Can users access these tables ?

**Comment by slivne** [comment]
@psarna / @nyh is this possible today ?

**Comment by psarna** [comment]
Not possible without CQL interface. I suppose we could expose read-only system tables by introducing a notion of virtual tables in alternator.
