### ISSUE TITLE
When speculative read is configured a write may fail even though enough replicas are alive

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#6123]
*Installation details*
Scylla version (or git commit hash): dee0b6834738778921fc582b5a90484a214ef56f

If during a read that has a replica to for speculation there is a missmatch the read repair is done between all replicas which may fail if one of them does not answer. We need to repair between CL replicas.

**Comment by slivne** [comment]
What does C* do ?

**Comment by gleb-cloudius** [comment]
On Thu, Apr 02, 2020 at 05:59:50AM -0700, Shlomi Livne wrote:
> What does C* do ?
> 
What does it matter? Their code is completely different.

--
			Gleb.

**Comment by glommer** [comment]
I don't see backport tags here. Should we backport this to stable versions ?

**Comment by glommer** [comment]
@pidiaquez and I are trying to reproduce this.

One of the things I have noticed is that both with and without speculative retry, when the node is killed abruptly the performance drops *A LOT*. With speculative retry enabled, from a 30kreq/s baseline to around 300 req/s. The drop is actually softer with speculative retry disabled.

Could it be that we don't lose availability, it's just that the performance drop so much in the live cluster as to essentially create a de-facto outage on percentage of the keys ?

**Comment by avikivity** [comment]
Backported to 3.3, 4.0.
