### ISSUE TITLE
lwt_test.py:read_round_optimization test is flaky

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#6125]
Error Message
{'scylla_storage_proxy_coordinator_cas_failed_read_round_optimization': 0} {'scylla_storage_proxy_coordinator_cas_failed_read_round_optimization': 0}
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/lwt_test.py", line 178, in read_round_optimization_test
    assert after[name] - before[name] ==  1, "{} {}".format(before, after)
AssertionError: {'scylla_storage_proxy_coordinator_cas_failed_read_round_optimization': 0} {'scylla_storage_proxy_coordinator_cas_failed_read_round_optimization': 0}

For whatever reason metric is not increased when it should (the read round optimization round should fail.)

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/445/testReport/lwt_test/LwtTest/read_round_optimization_test/

**Comment by kostja** [comment]
Changed the test case to make the failure easy to reproduce:
https://github.com/kostja/scylla-dtest/tree/lwt

According to trace, replicas for whatever reason yield empty cell for a row:

node3.log-TRACE 2020-04-03 23:36:42,180 [shard 0] paxos - CAS[0] prepare_ballot: got a response prepare_promise(empty, empty) from 127.0.3.2
node3.log-TRACE 2020-04-03 23:36:42,180 [shard 0] paxos - CAS[0] prepare_ballot: got enough replies to proceed
node3.log:DEBUG 2020-04-03 23:36:42,180 [shard 0] paxos - CAS[0]: Using prefetched values for CAS precondition

Perhaps the empty response is returned due to this:
                // Silently ignore any errors querying the current value as the caller is prepared to fall back
                // on querying it by itself in case it's missing in the response. 

Need to investigate more.

**Comment by bhalevy** [comment]
@kostja how about https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/447/testReport/junit/lwt_test/LwtTest/metrics_test/?
Do you suspect it's the same issue?

**Comment by kostja** [comment]
It's also addressed by this patch.

**Comment by bhalevy** [comment]
Closed by scylladb/scylla-dtest#1412
