### ISSUE TITLE
Rolling upgrade fails because of std::runtime_error (Wrong token bytes size: expected 8 but got 0)

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#6131]
When we switched token representation to int64_t
we added some sanity checks that byte representation
is always 8 bytes long.

It turns out that for token_kind::before_all_keys and
token_kind::after_all_keys bytes can sometimes be empty
because for those tokens they are just ignored. The check
introduced with the change is too strict and sometimes
throws the exception for tokens before/after all keys 
created with empty bytes.

**Comment by avikivity** [comment]
Backported to 4.0.

**Comment by avikivity** [comment]
No vulernerable branches.
