### ISSUE TITLE
secondary_indexes_test: test_truncate_base: Error from server: code=0000 [Server error] message="Column key was expected to be provided in the index clustering key, but the whole index clustering key is missing"

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6134]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/447/testReport/junit/secondary_indexes_test/TestSecondaryIndexes/test_truncate_base/
Scylla version a15b32c9d9668928aaddd7b8491c63322b1aa578
```
Error Message
('Unable to complete the operation against any hosts', {<Host: 127.0.29.2:9042 dc1>: <Error from server: code=0000 [Server error] message="Column key was expected to be provided in the index clustering key, but the whole index clustering key is missing">, <Host: 127.0.29.3:9042 dc1>: <Error from server: code=0000 [Server error] message="Column key was expected to be provided in the index clustering key, but the whole index clustering key is missing">, <Host: 127.0.29.4:9042 dc1>: <Error from server: code=0000 [Server error] message="Column key was expected to be provided in the index clustering key, but the whole index clustering key is missing">, <Host: 127.0.29.1:9042 dc1>: <Error from server: code=0000 [Server error] message="Column key was expected to be provided in the index clustering key, but the whole index clustering key is missing">})
Stacktrace
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/secondary_indexes_test.py", line 759, in test_truncate_base
    cl=ConsistencyLevel.QUORUM)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1311, in inner
    return func(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/assertions.py", line 86, in assert_all
    list_res = _get_list_res(session, query, cl, ignore_order, result_as_string)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/assertions.py", line 51, in _get_list_res
    res = session.execute(simple_query)
  File "cassandra/cluster.py", line 2611, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4829, in cassandra.cluster.ResponseFuture.result
cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.0.29.2:9042 dc1>: <Error from server: code=0000 [Server error] message="Column key was expected to be provided in the index clustering key, but the whole index clustering key is missing">, <Host: 127.0.29.3:9042 dc1>: <Error from server: code=0000 [Server error] message="Column key was expected to be provided in the index clustering key, but the whole index clustering key is missing">, <Host: 127.0.29.4:9042 dc1>: <Error from server: code=0000 [Server error] message="Column key was expected to be provided in the index clustering key, but the whole index clustering key is missing">, <Host: 127.0.29.1:9042 dc1>: <Error from server: code=0000 [Server error] message="Column key was expected to be provided in the index clustering key, but the whole index clustering key is missing">})
```

This exception was added in b3fdb742aed5ef1b8d849ef099a1e2044561831e for #5856

**Comment by bhalevy** [comment]
@psarna please look into this

**Comment by psarna** [comment]
Yay, the trap worked :) Now I only need to figure out how the heck this situation happened, and perhaps #5856 can finally get solved.

**Comment by psarna** [comment]
I'll just leave a hypothesis I just came up with for tomorrow: perhaps lack of the clustering key is a valid paging state after all, and this assertion should is too strict? E.g. when the last row from a paged query was a static row - that would mean that the paging state should have a partition key to indicate a partition, but no specific clustering key...
If that's the case, the solution would be to simply generate an open-ended clustering range if the clustering key was not present in the old base paging state.
```cpp
if (old_paging_state->get_clustering_key() && _schema->clustering_key_size() > 0) {
    auto base_ck = generate_base_key_from_index_pk<clustering_key>(old_paging_state->get_partition_key(),
            old_paging_state->get_clustering_key(), *_schema, *_view_schema);
    command->slice.set_range(*_schema, base_pk,
            std::vector<query::clustering_range>{query::clustering_range::make_starting_with(range_bound<clustering_key>(base_ck, false))});
} else {
    command->slice.set_range(*_schema, base_pk, std::vector<query::clustering_range>{query::clustering_range::make_open_ended_both_sides()});
}
```

**Comment by psarna** [comment]
... indeed, that's the case (the comment says it all):
```cpp
service/pager/query_pagers.cc:
            // last ck can be empty depending on whether we
            // deserialized state or not. This case means "last page ended on
            // something-not-bound-by-clustering" (i.e. a static row, alone)
            const bool has_ck = _has_clustering_keys && _last_ckey;
```

**Comment by psarna** [comment]
So - the assertion from b3fdb74 is incorrect, but instead of reverting it, it's better to simply fix the code. I'll send a patch tomorrow at the latest.

**Comment by psarna** [comment]
or rather - the assertion itself is correct, but due to another bug, it can be triggered in an incorrect path

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please consider backporting to 4.0

**Comment by bhalevy** [comment]
@nyh please evaluate backport.  Is it required? Is it safe?

**Comment by nyh** [comment]
@bhalevy I'll evaluate the backporting of this now. The "backport-4.0" tag isn't helpful and even confusing - did you evaluate that it's not needed for previous versions? If so, it would have been better to say this with words, not tags.

**Comment by nyh** [comment]
Backported to 4.0. New commits b3fdb742aed5ef1b8d849ef099a1e2044561831e and 0819d221f48644452849951f925e8b8bbf3f18c7. 
This patch fixes a situation asserted in a very recent patch (from April 1st), so no need to backport to other releases. So removing need backporting tags.

**Comment by bhalevy** [comment]
> Backported to 4.0. New commits [b3fdb74](https://github.com/scylladb/scylla/commit/b3fdb742aed5ef1b8d849ef099a1e2044561831e) and [0819d22](https://github.com/scylladb/scylla/commit/0819d221f48644452849951f925e8b8bbf3f18c7).
> This patch fixes a situation asserted in a very recent patch (from April 1st), so no need to backport to other releases. So removing need backporting tags.

Thanks @nyh

**Comment by avikivity** [comment]
Oops, changed title on wrong bug, changed it back.
