### ISSUE TITLE
Batchlog size threshold (support for batch_size_fail_threshold_in_kb)

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#614]
from tzach

I'm running similar load with RF=3 CL=3 and I see the following error messages
```
 [shard 3] BatchStatement - Batch of prepared statements for features.doc1 is of size 1018, exceeding specified threshold of 1000 by 18.
```
For all shards, many times.

Another example
```
 [shard 1] BatchStatement - Batch of prepared statements for features.doc1 is of size 5087, exceeding specified threshold of 2000 by 3087
```

from gleb

This comes from cql batch statement verifier. It has two threshold (hardcoded to 1000 and 2000 currently). Warning it sprinted after first one and after second query is failed. BTW it looks like our code is incorrect. Origin checks batch size in kb, not number of queries in a batch (parameter is called batch_size_fail_threshold_in_kb).

**Comment by elcallio** [comment]
In the version of origin we build against (i.e. the scylla fork), the "fail" portion of batch size verification seems to be gone. Should I assume that this is the goal for us as well (and respecting the config flag).
