### ISSUE TITLE
docker-entrypoint.py doesn't gracefully shutdown scylla when the container is stopped

### ISSUE THREAD

**Issue by hos-omar** [scylladb/scylla#6150]
Looks like the current **docker-entrypoint.py** is not able to handle graceful shutdown of the DB.
when I stop the container I don't see any logs indicating the DB is shutting down, and eventually it gets killed after the termination grace period.

to correctly propagate the SIGTERM signal shouldn't supervisord be running as PID 1?
As this is currently not the case.

This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version: 3.0.8
Cluster size: 5
OS: Ubuntu

**Comment by tzach** [comment]
@penberg  ?

**Comment by fruch** [comment]
I've managed to pass along the signals, with the following code in `docker-entrypoint.py`:

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import os
import sys
import signal
import subprocess
import scyllasetup
import logging
import commandlineparser

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG, format="%(message)s")

supervisord = None

def signal_handler(signum, frame):
    supervisord.send_signal(signum)

signal.signal(signal.SIGINT, signal_handler)
signal.signal(signal.SIGTERM, signal_handler)
try:
    arguments = commandlineparser.parse()
    setup = scyllasetup.ScyllaSetup(arguments)
    setup.developerMode()
    setup.cpuSet()
    setup.io()
    setup.cqlshrc()
    setup.arguments()
    setup.set_housekeeping()
    supervisord = subprocess.Popen(["/usr/bin/supervisord", "-c",  "/etc/supervisord.conf"])
    supervisord.wait()
except Exception:
    logging.exception('failed!')
```

**Comment by avikivity** [comment]
Aged out, no need to backport.
