### ISSUE TITLE
Conflicting LWT transactions may be committed due to pruning

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#6154]
Scylla version (or git commit hash): >= 4.0
Cluster size: > 3

Split from https://github.com/scylladb/scylla/issues/6139

1. x = 0
1. CAS1 is preparing set x = 1 if x = 0 using ballot t0
1. CAS1 is successfully prepared and got read results with x = 0 but hasn't moved to the accept phase yet
1. CAS2 is preparing set x = 2 if x = 0 using ballot t1
1. CAS2 also sees x = 0, is accepted, committed and prunes paxos_state
1. CAS1 attempts accept() and succeeds, because paxos state doesn't remember t1 from CAS2 anymore
1. CAS1 commits

Both CAS1 and CAS2 will succeed but they conflict.

**Comment by slivne** [comment]
@kostja is this also in C* ?

**Comment by slivne** [comment]
Backport to 4.0
