### ISSUE TITLE
via cqlsh not possible to escape special characters such as ' when used as FILTER for UPDATE

### ISSUE THREAD

**Issue by pidiaquez** [scylladb/scylla#6156]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.0.2

Issue Description: when having special characters such as (') "single quote". on column of TEXT data type

CQLSH allows to INSERT this special character by using $$TEXT$$
also allows for SELECT using FILTER by this PK by using $$TEXT$$

but it does not allow to UPDATE the row if a FILTER is used attempting to escape with this method ,

below how to reproduce:

INSERT works:
`
insert into pi.upui (upuishort, createddate, expirydate , state , updateddate , valflag) VALUES ($$uyuyuey'yeuyruwey$$, '2020-10-17T00:00:00+0000','2020-10-17T00:00:00+0000',1,'2020-10-17T00:00:00+0000',5); cqlsh:system> select * from pi.upui;
`
SELECT works:
`
select * from pi.upui where upuishort=$$uyuyuey'yeuyruwey$$ ; upuishort | createddate | expirydate | fid | parentaui | primaryrepositoryid | state | updateddate | upuilong | valflag -------------------+---------------------------------+---------------------------------+------+-----------+---------------------+-------+---------------------------------+----------+--------- uyuyuey'yeuyruwey | 2020-10-17 00:00:00.000000+0000 | 2020-10-17 00:00:00.000000+0000 | null | null | null | 1 | 2020-10-17 00:00:00.000000+0000 | null | 5
`

UPDATE does not work

`
update pi.upui set createddate='1974-10-17 00:00:00.00+0000' where upuishort=$$uyuyueyy'euyruwey$$;
`

in the latest case cqlsh stays waiting for EOF

**Comment by nyh** [comment]
In our CQL syntax parser, `cql3/Cql.g`, the parsing code seems correct:
In the `relation` target, we have the relevant production:
```
  : name=cident type=relationType t=term
```
In the `term` we have `value`, and in `value` in turn we have a `constant`, and `constant` can be a `STRING_LITERAL` - and this is the code which parses the $$ stuff, and is supposedly the same code for all the string literals, not special for updates...

So this is supposed to work. Let's write a unit test that checks the "$$" quoting, if we don't already have one.

**Comment by pidiaquez** [comment]
given that CQLSH in this case does not seems to finish the command ( waiting for EOF), is it possible that the issue is on the client side?

**Comment by dyasny** [comment]
@vladzcloudius can you please assign this field priority as well? This is from support ticket 1145

**Comment by eliransin** [comment]
definetly a cqlsh thing - 
I tried it with the cqlsh provided with 3.0 and it shows what you saw.
```
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> update pi.upui set createddate='1974-10-17 00:00:00.00+0000' where upuishort=$$uyuyueyy'euyruwey$$;
   ... 
```
And when I tried it with pip installed cqlsh on my system I got:
```
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> update pi.upui set createddate='1974-10-17 00:00:00.00+0000' where upuishort=$$uyuyueyy'euyruwey$$;
InvalidRequest: Error from server: code=2200 [Invalid query] message="Keyspace pi does not exist"
```

I am now validating with master latest (in a docker).

**Comment by eliransin** [comment]
The cqlsh in master latest (7ae2cdf46c7) suffers from the same problem.
This means that it is a problem in our supplied cqlsh.

**Comment by eliransin** [comment]
Closing - this issue was moved to scylla-tools-java repo , scylladb/scylla-tools-java#150
