### ISSUE TITLE
Support for Cassandra 2.2 (LA) SSTable formats 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#616]

**Comment by slivne** [comment]
in 1.7 we will support uploading 2.2 sstable via sstableloader.

**Comment by penberg** [comment]
I think this issue was about Scylla supporting 2.2 sstables _natively_, no?

We also have an open issue for supporting 3.0 sstables by Scylla in https://github.com/scylladb/scylla/issues/1969.

**Comment by tzach** [comment]
Agree with @penberg here. The original issue was a native support.
Having said that, sstableloader is a better solution for more users, so the original issue can be pushed to the future.

**Comment by slivne** [comment]
@tzach as we do not intend to support it at this point lets close it as wont-fix

**Comment by avikivity** [comment]
Why? We'll support it at some point.

**Comment by tzach** [comment]
We can keep it open and wait for the community feedback. For now it does not look urgent

**Comment by avikivity** [comment]
It's a simple change that will improve our bloom filter performance and a step on the way to the 3.x format.

**Comment by penberg** [comment]
@avikivity Indeed. I certainly don't see why we would _not_ support 2.2 format. We already supported it pre-1.0 and it was a last minute decision to go back to 2.1 format. /cc @glommer

**Comment by hagrid-the-developer** [comment]
I tried to find corresponding C* issue related to change that can increase bloom filter performance and I found following CR: https://issues.apache.org/jira/browse/CASSANDRA-9060 that is related to Bloom filter serialization (both in-memory and on the disc representations use big endian). Is it the correct CR?

**Comment by slivne** [comment]
the fx version for this is 2.1.5 - so I doubt this is it

**Comment by slivne** [comment]
check this out

https://issues.apache.org/jira/browse/CASSANDRA-8413

I know its marked for 3.0

Yet there is a comment about LA (2.2) as well

https://issues.apache.org/jira/browse/CASSANDRA-8413?focusedCommentId=14487735&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14487735

**Comment by hagrid-the-developer** [comment]
@slivne It really looks like what I was looking for but I am able to find this change in 3.0 only, not in 2.x ...

**Comment by slivne** [comment]
@hagrid-the-developer - I think you are correct - so this should be done in 3.0

**Comment by slivne** [comment]
fixed 03c22ad52485089a942cbfd31167003090cf3903
