### ISSUE TITLE
alternator: trying to fetch data from a nonexistent table may result in segfault

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#6161]
When a table name is getting resolved and it's not found in the database, alternator also tries to check if maybe the table is actually an index. Unfortunately, it tries to extract the index name from the request even if the user didn't pass the `IndexName` parameter, which results in dereferencing a `nullptr`.

This issue is already solved by a patch which resides on a mailing list, but this issue is created to track it - especially that it's a backport candidate.

/cc @nyh

**Comment by psarna** [comment]
Patch in question: https://groups.google.com/d/msg/scylladb-dev/85kim_PKOxU/mbjPEDE3AQAJ

It's easy to miss it in Gmail UI, since it shows as a response for the whole series, even though it's re-sent as a separate patch. Thunderbird shows it properly as a separate patch.

**Comment by nyh** [comment]
Backported to 4.0 (commit b2b1bfb1599c69fb163c3af0c97d14746dcc4105). Not backporting to older releases as Alternator was experimental then.
