### ISSUE TITLE
cdc perf: large collections: Load/Throughput of each db node isn't balanced

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#6168]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200405.df48b5ec9d5
Cluster size: 6 * i3.4xlarge
loader: 2 * c5.xlarge
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0d8e83b5352fe4da7 (eu-west-1)

### Description:
In CDC longevity jobs, the Load and Throughput of 3 db nodes are very low, but the numbers of other 3 db nodes are very similar (higher).

![image](https://user-images.githubusercontent.com/309708/78873393-614a9580-7a7d-11ea-94e6-297388068e4b.png)

### Test info
Test job: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h/19/

SCT log: https://cloudius-jenkins-test.s3.amazonaws.com/ef9758d1-e7ff-4edf-b46b-6099bd1b355c/20200406_074143/sct-runner-ef9758d1.zip 

### db log:

- db log: https://cloudius-jenkins-test.s3.amazonaws.com/ef9758d1-e7ff-4edf-b46b-6099bd1b355c/20200406_074143/db-cluster-ef9758d1.zip

### Workload
- cassandra-stress user no-warmup profile=/tmp/cdc_profile.yaml ops'(insert=2,read1=1,update_number=1,update_name=1,delete1=1)'
  - profile: https://github.com/scylladb/scylla-cluster-tests/blob/master/data_dir/cdc_profile.yaml
- cassandra-stress user no-warmup profile=/tmp/cdc_profile_preimage.yaml ops'(insert=2,read1=1,update_number=1,update_name=1,delete1=1)'
  - profile: https://github.com/scylladb/scylla-cluster-tests/blob/master/data_dir/cdc_profile_preimage.yaml

### Cluster info:

- longevity-cdc-100gb-4h-master-db-node-ef9758d1-1 [52.48.248.215 | 10.0.65.140] 
- longevity-cdc-100gb-4h-master-db-node-ef9758d1-2 [34.244.126.146 | 10.0.41.24] 
- longevity-cdc-100gb-4h-master-db-node-ef9758d1-3 [54.194.19.203 | 10.0.167.35] 
- longevity-cdc-100gb-4h-master-db-node-ef9758d1-4 [54.154.105.19 | 10.0.20.128] 
- longevity-cdc-100gb-4h-master-db-node-ef9758d1-5 [34.244.151.8 | 10.0.183.163] 
- longevity-cdc-100gb-4h-master-db-node-ef9758d1-6 [54.194.99.50 | 10.0.103.30] 
- longevity-cdc-100gb-4h-master-loader-node-ef9758d1-1 [34.244.148.188 | 10.0.48.16] 
- longevity-cdc-100gb-4h-master-loader-node-ef9758d1-2 [34.247.191.93 | 10.0.242.191] 
- longevity-cdc-100gb-4h-master-monitor-node-ef9758d1-1 [63.32.93.6 | 10.0.90.126] 
                                                                                
/CC @slivne @haaawk @roydahan @aleksbykov

**Comment by slivne** [comment]
It may be related to the tokens issue - https://github.com/scylladb/scylla/issues/6193 - look at the results without cdc and you should have an answer if its related to that or not

**Comment by amoskong** [comment]
The issue still exists after disabled cdc:


- job: https://jenkins.scylladb.com/job/scylla-staging/job/amos/job/longevity-cdc-100gb-4h/9/
- version: 666.development-0.20200405.df48b5ec9d5
- grafana snapshot: https://snapshot.raintank.io/dashboard/snapshot/cHQb34j6IA2GZFabskW6OENEiH8gA4ba

![image](https://user-images.githubusercontent.com/309708/79183752-f1edf080-7e44-11ea-8cf7-2e60710983a5.png)

**Comment by slivne** [comment]
@amoskong AFAIK latest master numbers are much better - can we close this ?

**Comment by amoskong** [comment]
> @amoskong AFAIK latest master numbers are much better - can we close this ?

Yes, throughput and load of each node is stable in latest master/4.1/4.0 CDC longevity.

### Scylla version: 666.development (ami-04d2848ff6d5c4a41)
![image](https://user-images.githubusercontent.com/309708/83372439-dbe9be80-a3f7-11ea-98c0-e8d85de85d76.png)

### Scylla version: 4.1.rc1 (ami-00907d577946117dd)
![image](https://user-images.githubusercontent.com/309708/83372538-266b3b00-a3f8-11ea-9fd3-5881d1931578.png)

### Scylla version: 4.0.1 (ami-07a2e61ddb2a8f407)
![image](https://user-images.githubusercontent.com/309708/83372377-b3fa5b00-a3f7-11ea-8cce-ba08f6e84503.png)
