### ISSUE TITLE
LWT word police

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#6169]
In Scylla, we decided to use terms prepare, accept, learn for Paxos protocol steps. 
Still, some of the user visible metrics use the old (Cassandra) terminology, and should be updated:

* cas_propose
* cas_commit

**Comment by slivne** [comment]
@kostja - lets get this in - updating metrics later is a mess

**Comment by tzach** [comment]
@amnonh this will require dashboard update, pleas keep track.

**Comment by kostja** [comment]
Since scylla-jmx depends on old names, following Amnon's
suggestion this version doesn't change the rest API, only updates
the internals.
Hence it also does not need a backport to 4.0.

**Comment by tzach** [comment]
@amnonh please make sure 4.1 LWT dashboard are updated

**Comment by avikivity** [comment]
Not backporting word police.
