### ISSUE TITLE
speculative retries are mistagged

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#6170]
Speculative retries are not correctly tagged.

I am looking at a cluster that is set up to use workload prioritization with Scylla Enterprise. The queries all go to `service_level_pc_0`. However the I/O graph still showed activity in the `query` class.

Upon disabling speculative retry, the query class activity went down to zero, indicating that speculative retry was the source of those queries.

Speculative retry should happen in the context of the query that generated the speculation, not in the main `query` class

@gleb-cloudius

**Comment by gleb-cloudius** [comment]
@glommer why is this issue on open source and not on the enterprise bug tracker?

@eliransin  workload prioritization is your turf. Speculative retries are started from a timer. I guess they are not properly tagged there unless a timer inherits scheduling group from whoever armed them
automatically. There are other things that are running from timers. It looks like the timer infrastructure should handle scheduling classes.

**Comment by glommer** [comment]
Because the tagging of requests and inheriting service levels seems to be
totally open source. If you, who know the code better thinks this is best
in Enterprise let me know and I will move it.

**Comment by glommer** [comment]
To clarify my comment, in my understanding all we need to do is to make sure that speculative retry is executed with the same scheduling class / I/O class that originated the request. We don't need to worry about which scheduling class is that. Therefore, OSS.

**Comment by eliransin** [comment]
> To clarify my comment, in my understanding all we need to do is to make sure that speculative retry is executed with the same scheduling class / I/O class that originated the request. We don't need to worry about which scheduling class is that. Therefore, OSS.

I agree to that. I will have a look, it turns out we have several of these cases. In OSS it manifests in unbalanced statistics (#5797) that happens when an operation starts in on SG and completes/times out in another. I will start picking some long hanging fruits in this area (including this one) soon.
Then we might need to think of ways to catch the others.

**Comment by avikivity** [comment]
I think it makes sense for seastar::timer to capture the scheduling group it is called with (and also provide an explicit constructor). That means that timers will have to be executed in a task, not in the poller.

**Comment by avikivity** [comment]
@gleb-cloudius @glommer as reported the bug should be in enterprise, but note it also affects open-source, since speculative retries will fall to the main group instead of the statement group, giving retries an edge over normal statements.

**Comment by gleb-cloudius** [comment]
I am less worried where it should be and more about timers not
respecting scheduling class. @avi can you confirm the timer part?

--
			Gleb.

**Comment by avikivity** [comment]
Confirmed, patch soon.

**Comment by avikivity** [comment]
https://groups.google.com/d/msg/seastar-dev/0JFob8-Qvc0/KKc3HN7YBgAJ

**Comment by avikivity** [comment]
This is worth a backport, but also worth waiting for a while.

**Comment by avikivity** [comment]
Backported to 3.3, 4.0.
