### ISSUE TITLE
CDC: Frozen lists are serialized incorrectly in CDC log

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla#6172]
(discovered by @aleksbykov, [here](https://github.com/scylladb/scylla/issues/6050#issuecomment-611995704))

A column of type `frozen<list<T>>` will have a corresponding column of type `frozen<map<timeuuid, T>>` in CDC log:

```cql
CREATE TABLE ks.cf_scylla_cdc_log (
    "cdc$stream_id" blob,
    "cdc$time" timeuuid,
    "cdc$batch_seq_no" int,
    "cdc$deleted_v" boolean,
    "cdc$operation" tinyint,
    "cdc$ttl" bigint,
    pk int,
    v frozen<map<timeuuid, text>>,
    PRIMARY KEY ("cdc$stream_id", "cdc$time", "cdc$batch_seq_no")
) WITH CLUSTERING ORDER BY ("cdc$time" ASC, "cdc$batch_seq_no" ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = 'CDC log for ks.cf'
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE ks.cf (
    pk int PRIMARY KEY,
    v frozen<list<text>>
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cdc = {'postimage': 'false', 'preimage': 'true', 'enabled': 'true', 'ttl': '86400'}
```

When preparing mutation to the log table, if `transformer::transform` encounters an update of an atomic column, it just copies the value directly to the corresponding column in the log row, without any re-serialization. The function does not have special handling for frozen list case, therefore the serialized value of frozen list is copied to the frozen map column, which results in cells that cannot be deserialized as map:

```cql
cqlsh:ks> insert into cf (pk, v) values (0, ['a', 'b']);
cqlsh:ks> select v from cf_scylla_cdc_log ;
Traceback (most recent call last):
  File "/home/piodul/code/scylla-tools-java/bin/cqlsh.py", line 1053, in perform_simple_statement
    result = future.result()
  File "/home/piodul/code/scylla-tools-java/bin/../lib/cassandra-driver-internal-only-3.11.0-bb96859b.zip/cassandra-driver-3.11.0-bb96859b/cassandra/cluster.py", line 3925, in result
    raise self._final_exception
DriverException: Failed decoding result column "v" of type map<timeuuid, varchar>: bytes is not a 16-char string
```

**Comment by aleksbykov** [comment]
The error happened for any frozen type (list, set,  map)

**Comment by piodul** [comment]
@aleksbykov I tried re-running the example above with frozen map or frozen set, and I did not get any errors.

I identified the issue, and it is specific to frozen lists - the corresponding type of the column in cdc log is incorrect only in case of frozen lists. I'll submit a patch shortly.

**Comment by aleksbykov** [comment]
I will recheck.

**Comment by haaawk** [comment]
> The error happened for any frozen type (list, set, map)

Are you sure @aleksbykov it fails for all the types? only list is handled in a special way so there shouldn't be a problem with collections other than list.

**Comment by aleksbykov** [comment]
@haaawk @piodul 
I rechecked. You were right. Reproduced only for frozen list

**Comment by haaawk** [comment]
@avikivity @slivne it would be good to backport this bugfix to 4.0 if possible. Could we do that, please?

**Comment by nyh** [comment]
This is an old commit, already in 4.1 and alter. Not backporting to 4.0 now - CDC is still an experimental feature, and nobody who uses it should be using 4.0.
