### ISSUE TITLE
Trace MV update in the context of Write request trace

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#6175]
*Installation details*
HEAD: f1aaa91e2193e3db32af5e8899734e2a28476da0

*Description*
We don't have very little tools to debug MV related performance issues today.
In particular MVs write path is completely not instrumented by Tracing.

Tracing write path instrumentation stops at mutate_begin() (not including).

It will make a lot of sense to instrument this path.

**Comment by vladzcloudius** [comment]
@slivne @psarna @eyalgutkind FYI

**Comment by avikivity** [comment]
Enhancement, not backporting.
