### ISSUE TITLE
Improve Alternator docs

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#6179]
*Installation details*
Scylla version (or git commit hash): 3.3

This refer mostly to https://github.com/scylladb/scylla/blob/master/docs/alternator/alternator.md

Some features are missing from Alternator API, but do have good solution via other API from Scylla, and should be documented as such.
Examples are:
- Backups. No Alternator API. Good [Backup solution with Scylla Manager (https://docs.scylladb.com/operating-scylla/manager/2.0/backup/)
- Streams. No Alternator API, but an alternative (Via CQL) with [CDC](https://docs.scylladb.com/using-scylla/cdc/)

**Comment by nyh** [comment]
Sent a patch titled "docs, alternator: alternator.md cleanup" to the mailing list. Fixed more than just the things you asked for. @tzach please review, and consider how/if you want to copy the updates to the website as well.

**Comment by nyh** [comment]
Backported to 4.0. No need to backport to older releases (Alternator was experimental, and updated content is relevant only to the newest code anyway).
