### ISSUE TITLE
ami: RAID on Ephemeral disk does not working beyond AMI stop/start

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#6184]
On i3 with RAID on ephemeral disks (which is default on i3), /var/lib/scylla does not correctly initialized beyond AMI stop/start.

After started the instance again, it shows up:
```
   _____            _ _       _____  ____  
  / ____|          | | |     |  __ \|  _ \ 
 | (___   ___ _   _| | | __ _| |  | | |_) |
  \___ \ / __| | | | | |/ _` | |  | |  _ < 
  ____) | (__| |_| | | | (_| | |__| | |_) |
 |_____/ \___|\__, |_|_|\__,_|_____/|____/ 
               __/ |                       
              |___/                        


Nodetool:
	nodetool help
CQL Shell:
	cqlsh
More documentation available at: 
	http://www.scylladb.com/doc/
By default, Scylla sends certain information about this node to a data collection server. For information, see http://www.scylladb.com/privacy/

    Failed mounting RAID volume!

ScyllaDB aborted startup because of RAID volume missing.
To see status, run
 'systemctl status scylla-server'

This EC2 instance is optimized for Scylla.
[centos@ip-10-0-0-75 ~]$ cat /etc/fstab 

#
# /etc/fstab
# Created by anaconda on Mon Apr  3 17:42:52 2017
#
# Accessible filesystems, by reference, are maintained under '/dev/disk'
# See man pages fstab(5), findfs(8), mount(8) and/or blkid(8) for more info
#
UUID=0a84de8e-5bfe-43e7-992b-5bfff8cdce43 /                       xfs     defaults        0 0
UUID="652585da-9655-42fb-8cbd-bfdf6b135376" /var/lib/scylla xfs noatime,nofail 0 0
[centos@ip-10-0-0-75 ~]$ cat /proc/mdstat 
Personalities : 
unused devices: <none>
[centos@ip-10-0-0-75 ~]$ systemctl status scylla-ami-setup
● scylla-ami-setup.service - Scylla AMI Setup
   Loaded: loaded (/usr/lib/systemd/system/scylla-ami-setup.service; enabled; vendor preset: disabled)
   Active: inactive (dead)
Condition: start condition failed at Mon 2020-04-13 08:00:19 UTC; 3min 46s ago
           ConditionPathExists=!/etc/scylla/ami_configured was not met
```
It seems like we mistakenly broke ephemeral support on our AMI at some point, the setup script tries to handle ephemeral disk as non-ephemeral disk, and failing (because it have lost data on shutting down the instance).
It maybe related with #6012 , but behavior / result is different.

**Comment by syuu1228** [comment]
Seems like scylla-ami-setup.service itself supports ephemeral but does not started since it has ```ConditionPathExists=!/etc/scylla/ami_configured```, so after deleting the file /etc/scylla/ami_configured and then shutdown & restart, the instance succeed to re-construct RAID and start scylla-server.

**Comment by syuu1228** [comment]
I do not remember / does not understand why we decided we need this, but the commit https://github.com/scylladb/scylla-ami/commit/37fad2eee37ea65f91a2627abfe3ddaf91b1e25d,  https://github.com/scylladb/scylla-ami/commit/b7db861643422a41302aa657f2cf9e72fecfaed9 is for  https://github.com/scylladb/scylla/issues/3640, and seems like we were fine with this.

**Comment by roydahan** [comment]
We need to differentiate between simple reboot like in #3640 (very common) and "stop-> start" i3 instance (pretty rare).

**Comment by slivne** [comment]
@syuu1228 roy provided his view - can we close this ?

**Comment by avikivity** [comment]
This is the expected behavior. Stop/start causes data loss, so we should alert the operator that something is wrong and not proceed.
