### ISSUE TITLE
snapshots directory is not created inside the data directory

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#619]
The snapshots directory should be created in the data directory, currently if it's not there trying to call snapshot will fail quietly and get snapshot will fail with a file not found

**Comment by amnonh** [comment]
Column family snapshots are stored in a directory under the column family directory

A call to get_snapshot_detail without a snapshot (which is a valid operation) would throw an exception instead of returning an empty map

**Comment by tzach** [comment]
@amnonh what is the user impact of this issue? 
Should this be fixed in open source as well?
