### ISSUE TITLE
Implement reference client for CDC

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#6197]
The reference client should be just a simple Java library that uses Java driver to read CDC Log for the selected table(s). 

The library should work more or less like this:

1. Read streams description
2. For each stream keep doing:
2.1. Wait for some amount of time
2.2. Execute select * from CDCLog where time > <timeuuid of last processed change> and time < now() - 30s
2.3. Execute some callback on each row obtained with that select
2.4. Update <timeuuid of last processed change>

Maybe allow some hook for the library user to persist last seen timeuuid in case of client breakage to allow recovery.

The library should correctly handle schema changes. This can probably be done by registering a listener on schema changes in the driver.

The library should also handle topology changes. This can be done by registering a listener on cluster changes in the driver. On topology change, the library should keep reading from the existing streams until it doesn't get any new data for 1s. Then it should read new streams and start consuming them. It is possible that multiple changes to the topology occur after each other. The library should handle that correctly by first consuming all the streams for the first change, waiting for 1s and then consuming streams for the second change.

**Comment by haaawk** [comment]
@kbr- please link the documentation you mentioned on the call.

**Comment by kbr-** [comment]
https://docs.scylladb.com/using-scylla/cdc/cdc-querying-streams/#reacting-to-topology-changes

**Comment by tzach** [comment]
This is not mentioned explicitly, but the client should read *all* updates in face of network, client, and nodes restarts, as well as toplogy changes.

**Comment by elcallio** [comment]
Initial stab at integ library + simple client: 
https://github.com/elcallio/scylla-cdc-java

Devoid of comments and explicit topology change handling (though it is implicitly handled)

**Comment by haaawk** [comment]
This task is done both in Java and in Go now.
