### ISSUE TITLE
Alternator encryption at rest

### ISSUE THREAD

**Issue by giorgiozoppi** [scylladb/scylla#6201]
DynamoDB encryption at rest provides an additional layer of data protection by securing your data in an encrypted table—including its primary key, local and global secondary indexes, streams, global tables, backups, and DynamoDB Accelerator (DAX) clusters whenever the data is stored in durable media. Organizational policies, industry or government regulations, and compliance requirements often require the use of encryption at rest to increase the data security of your applications. 

We would like to have it on Alternator.

**Comment by dorlaor** [comment]
Our Enterprise product has encryption at rest and within the next rebase
of Scylla 4.0 OSS of Enterprise 2020.1 release will result in encryption at
rest

**Comment by giorgiozoppi** [comment]
Ok So we can close this issue
