### ISSUE TITLE
Need distributed loader concurrency control bypass

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#6202]
Distributed loader sstable opening is gated through the `database::sstable_load_concurrency_sem()` semaphore, at a concurrency of 3. 
This is (according to creation comment) to reduce memory footprint during bootstrap, by partially serializing the actual opening of existing sstables. 

However, in certain versions of the product, there exist circular dependencies between data in some sstables and the ability to actually read others. Thus when gated as above, we can end up with the dependents acquiring the semaphore fully, and once stuck waiting for population of their dependency effectively blocking this from ever happening. 

Since we probably do not want to remove the concurrency control, and increasing it would only push the problem further away, the best/simplest solution I can come up with is simply to be able to mark certain keyspaces as "prioritized" (pre-bootstrap), and allow them to populate outside the normal concurrency control semaphore (effectively increasing the concurrency by `<num sstables in keyspace>`. 

Another option would be to create a per-thread semaphore of 1 for each prio keyspace to keep concurrency down.

**Comment by avikivity** [comment]
Not-a-bug, not backporting.
