### ISSUE TITLE
Scylla 3.2.4 JMX wouldn't start 

### ISSUE THREAD

**Issue by Qsick** [scylladb/scylla#6204]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.2.4-0.20200325.4c38534f75-1
Cluster size: N/A
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

Platform (physical/VM/cloud instance type/docker): Cloud
Hardware: sockets= cores= hyperthreading= memory= N/A
Disks: (SSD/HDD, count) N/A

Performed an upgrade of a server from opensource 3.1 -> 3.2 on Ubuntu 18.04 and scylla-jmx wouldn’t start.
It was reporting that something was missing journelctl log.
/opt/scylladb/jmx/scylla-jmx: line 134: /usr/lib/scylla/jmx/symlinks/scylla-jmx: No such file or directory

This could be because we are installing in /opt
I solved this by making the following link:
$ ls -l /usr/lib/scylla/jmx
lrwxrwxrwx 1 root root 18 Apr 14 23:37 /usr/lib/scylla/jmx -> /opt/scylladb/jmx/

Just wanted to make you aware in the event you wanted to fix it in the debian package

**Comment by penberg** [comment]
@syuu1228 If I understand correctly, this issue is fixed in 3.3 by commit 46681753cd43dd563cceea4fe422b44a77230de2 and we can just backport that to fix 3.2?

**Comment by penberg** [comment]
Btw, thanks for reporting and analyzing the issue, @Qsick!

**Comment by slivne** [comment]
3.2 is EOL - we will not backport or spin new releases for it
