### ISSUE TITLE
test.py: rewrite Alternator's tests integration

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#6212]
Currently, to test Alternator, `test.py` just runs an external script, `test/alternator/run`. This script does all the preparation for the test (create temporary directory, start Scylla), runs the test (via pytest) and then does the cleanup (kill Scylla, remove the temporary directory).

It would be nicer if the setup and cleanup work would be done by `test.py` itself, in Python code. Besides having the code in a more likable (to some...) language, the more important benefit is that in the future additional tests could use the same test setup to test other things besides Alternator. For example, we could have functional tests written in Python for testing CQL (using the python CQL driver). 

I am proposing that we add to test.py the following features:

1. test.py should be able to create a temporary directory for a test suite to use. test.py will ensure that the temporary directory is removed at the end.
2. test.py should be able to start a one-node Scylla, and ensure that it is killed (with SIGKILL, no need for clean shutdown) at the end. Scylla's files will go to a temporary directory (see above), and it will run on a unique localhost IP address (on of the over a million addresses in 127.0.0.0/8) so multiple such tests as well as dtests can run concurrently. Which Scylla executable this should run depends on the requested build mode.

Once we have these features in `test.py`, the Alternator test support in `test.py` can simply use hose features and then just run "pytest" with the appropriate parameters (`--url` telling it where is Scylla, and `--junit-xml` telling it where to put the test results). The script `test/alternator/run` could then be removed. The "Run" test suite can be removed too, but we'll need a new test suite type specifically for the Alternator tests.

CC @kostja

**Comment by espindola** [comment]
Let me know if I should open another bug, but an issue I found with the current setup is that ./test.py --mode=foo might not run the test with the expected scylla

The problem comes from the run script selecting the newest scylla binary. So, if one runs

```
ninja && ./test.py alternator/run
```

test.py will run test/alternator/run 3 times and it will test the same scylla binary 3 times (whichever finished linking last)

**Comment by nyh** [comment]
Yes, @espindola this is a known, but unrelated issue. We don't have an issue for it. I'll open one.

**Comment by nyh** [comment]
While it still makes sense to improve `test.py` to do some of the work that `test/alternator/run` does today, after 6 months of experience with the `test/alternator/run` script, I grew fond of it. It's important to note that it has several features that `test.py` does not have today:
1. `run` allows running just a subset of the Alternator tests - one file or even just one test function.
2. `run` allows options like "--https" and hopefully in the future more (e.g., #7236) to control the way tests are run.
3. `run` conveniently puts all the relevant pytest and Scylla output and errors into a single output file.
If we ever drop the `test/alternator/run` script in favor of functions inside `test.py`, we should add these features to `test.py`.

**Comment by nyh** [comment]
In the time that passed, I added `test/cql-pytest` which also uses a run script. However, `cql-pytest`'s version is in Python, and uses a bunch of utility functions in `run.py` which can be used to run a Scylla process. Before changing anything it `test.py`, let's change `test/alternator/run` to be written in Python like `test/cql-pytest/run`, and shared the same `run.py` utility functions.

Eventually, we can move the shared `run.py` code into `test.py`. However, I think it's not urgent at all, and there are also some benefits to the current situation.

**Comment by nyh** [comment]
Almost another year has passed, and the process I describe in my previous comment continued: At this point, we have a small Python library, **test/cql-pytest/run.py**, which knows how to create and delete a temporary directory, how to pick a unique local IP address, how to start and kill a temporary process, how to run pytest, and more. The same library is now used by four different test runners (all written in Python): **test/alternator/run**, **test/cql-pytest/run**, **test/redis/run**, **test/rest_api/run**. It is also used by a fifth runner **test/cql-pyest/run-cassandra**, which is like test/cql-pytest/run` but runs Cassandra instead of Scylla as usual. 

All five scripts are now very short with almost no code duplication (e.g., test/alternator/run has code for choosing Alternator-specific command line parameters and for testing that Alternator went up - but doesn't have any code for running Scylla, handling a temporary directory, and so on).

Given that, there is no more any urgent need to move the common Python code from `test/cql-pytest/run.py` into `test.py`.
Moreover, as I noted above, it is very convenient that we can run `test/alternator.py` (for example) directly, not from `test.py`. This allows us to run specific test files or tests which test.py doesn't yet support (currently, test.py is not aware of all the subtests inside `test/alternator` et al.). It also allows us to run the same tests in a completely different way, such as running Alternator tests against AWS DynamoDB (`test/alternator/run --aws`) or the CQL tests against Cassandra, not Scylla (`test/cql-pytest/run-cassandra`). 

We could theoretically add these options to test.py, but such options would be strange inconsistent there: For example, consider that we were to add to `test.py` an option to "run against AWS DynamoDB" - what would that option mean for CQL tests? And if we add an option to "run against Cassandra" - what would that mean for the Alternator or Redis tests?
I guess this issue can be solved as well. Maybe if test.py is asked to run **only** Alternator tests, then additional options can be used like the option to run on AWS DynamoDB. But I'm no longer convinced that this is the right direction. It no longer seems (to me) necessary to put code inside test.py just because multiple tests want to share it.

**Comment by kostja** [comment]
I'm doing it right now

**Comment by nyh** [comment]
@kostja has basically done something similar to what I proposed in the original issue, while my own approach has drifted slightly as I explained in comments above :-) So closing this issue.
