### ISSUE TITLE
Partition estimation wildly inaccurate with TWCS interposer enabled 

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6214]
*Installation details*
Scylla version (or git commit hash): edef6800591e
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

When TWCS interposer is enabled partition estimation is wildly inaccurate, potentially leading to creation of bad bloom filters.

**Comment by avikivity** [comment]
Will backport, but later.

**Comment by avikivity** [comment]
Backported to 4.0.
