### ISSUE TITLE
Cooler check version message

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#6219]
minikube have a similar message as Scylla do, but with cool unicode
```
🎉  minikube 1.9.2 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.9.2
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'
```

**Comment by tzach** [comment]
@amnonh

**Comment by amnonh** [comment]
@tzach this is going to the log, not the screen, I believe it would only hurt us and the users when using automation tools

**Comment by tzach** [comment]
No love for unicode here. Closing.
