### ISSUE TITLE
commitlog replay will replay any file in the commitlog directory, not just commitlog segments

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#6220]
commitlog_replay is given a file prefix to match, but it ignores it, so any file in the commitlog directory is replayed.

This can cause recycled segments to be replayed. This isn't terrible, since they're commitlog segments, but is wasteful. Other files there can cause bigger problems.

**Comment by slivne** [comment]
merged 2039b79664ba22d4f8d7dd376e6c5868093bfa1a
