### ISSUE TITLE
Backlog can be negative due to bad accounting of total bytes in the tracker

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6227]
It was observed that backlog can become negative because tracker can incorrectly manage total bytes for all SSTables managed by it, like a SSTable is removed when not previously added or removed more than once, which makes backlog tracker's total bytes go negative which reuslts in a negative backlog

look:
(compaction_backlog_tracker*) 0x62e0100cc968 backlog=0.000000 total_bytes=-99005 contrib=7383562.825064 wr_total=0 comp_total=0 wr_contrib=0.000000 comp_contrib=0.000000

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
