### ISSUE TITLE
Seastar doesn't build in ubuntu 18.04

### ISSUE THREAD

**Issue by giorgiozoppi** [scylladb/scylla#6229]
The last repo doesn't build after install dependencies in ubuntu 18.04. The reason is libcares:
 Checking for module 'libcares'
--   Found libcares, version 1.14.0
-- Found c-ares: /usr/lib/x86_64-linux-gnu/libcares.so (found suitable version "1.14.0", minimum required is "1.13") 
-- Found cryptopp: /usr/lib/x86_64-linux-gnu/libcryptopp.so (Required is at least version "5.6.5") 
-- Could NOT find dpdk (missing: dpdk_INCLUDE_DIR dpdk_PMD_VMXNET3_UIO_LIBRARY dpdk_PMD_I40E_LIBRARY dpdk_PMD_IXGBE_LIBRARY dpdk_PMD_E1000_LIBRARY dpdk_PMD_BNXT_LIBRARY dpdk_PMD_RING_LIBRARY dpdk_PMD_CXGBE_LIBRARY dpdk_PMD_ENA_LIBRARY dpdk_PMD_ENIC_LIBRARY dpdk_PMD_NFP_LIBRARY dpdk_PMD_QEDE_LIBRARY dpdk_RING_LIBRARY dpdk_KVARGS_LIBRARY dpdk_MEMPOOL_LIBRARY dpdk_MEMPOOL_RING_LIBRARY dpdk_HASH_LIBRARY dpdk_CMDLINE_LIBRARY dpdk_MBUF_LIBRARY dpdk_CFGFILE_LIBRARY dpdk_EAL_LIBRARY dpdk_ETHDEV_LIBRARY dpdk_NET_LIBRARY dpdk_TIMER_LIBRARY dpdk_PCI_LIBRARY dpdk_BUS_PCI_LIBRARY dpdk_BUS_VDEV_LIBRARY dpdk_PMD_FM10K_LIBRARY dpdk_PMD_SFC_EFX_LIBRARY) 
CMake Error at cmake/SeastarDependencies.cmake:107 (find_package):
  Could not find a configuration file for package "fmt" that is compatible
  with requested version "5.0.0".
  The following configuration files were considered but not accepted:
    /usr/lib/cmake/fmt/fmt-config.cmake, version: 4.0.0
Call Stack (most recent call first):
  CMakeLists.txt:307 (seastar_find_dependencies)
-- Configuring incomplete, errors occurred!
See also "/home/jozoppi/CLionProjects/seastar/cmake-build-debug/CMakeFiles/CMakeOutput.log".
See also "/home/jozoppi/CLionProjects/seastar/cmake-build-debug/CMakeFiles/CMakeError.log".
[Failed to reload]

I will install libcares.

**Comment by avikivity** [comment]
The error shows that the problem is with fmt, not c-ares. Install a newer fmt, or ask Ubuntu to upgrade their old version.
