### ISSUE TITLE
Consider bypassing cache for materialized views' read-before-write

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#6233]
Following a discussion about reducing materialized view update generation overhead, @slivne suggested that we should consider bypassing cache for generating view updates, since these are system reads, not user reads.

There are two places to consider:
 - generating view updates for user writes
 - generating view updates from staging sstables

**Comment by haaawk** [comment]
BTW I have a change that allows bypassing cache for a selected table. Will post it this week.

**Comment by nyh** [comment]
This change makes some sense, but is it based on making sense, or some specific use case or workload or user complaint?

The thing is, the MV does **does** do a read. So after we do this read, it sounds like a shame to deliberately forget it. Caching this read may help if the user's write is followed by a read, but will also help if the user's write is followed by another write. I don't think it's obvious or universal that this caching doesn't make sense, or more accurately that keeping this value cached makes less sense than keeping other values in the cache...

@slivne maybe you can write a bit about the reasons you had in mind why we should deliberately avoid this caching?

**Comment by psarna** [comment]
Sure, I definitely prefer a discussion before merging this one (if we decide to merge it). I think that the main reason was that these reads are not directly triggered by the user, so we want to avoid the situation when mv updates cause hot user data to be evicted with cold data from view updates. That could certainly be the case when we run a big repair or load lots of sstables via /upload.

**Comment by nyh** [comment]
I think you made here an interesting distinction. **Repair**, specifically, indeed reads a lot of data that the repair process itself is guaranteed never to read again after reading it for the first time. This was relevant for "ordinary" reads of the repair (I assume these are already uncached) but also for reads generated by MV writes. So indeed it makes sense to disable caching in that specific case (of read-before-a-write during the repair).

By the way, what I said above, that the repair will not write the same row again, isn't true in the old-style repair (before the new row-level repair). There, when RF=3, the repair master received writes from two repair slaves, so each row is always written twice, so caching the read-before-the-write helps a bit. 

In any case, this issue mentions (and your patch changes) not only repairs, but also normal user-initiated writes. It's not clear to me whether in this case we *should* cache the old-row read, but it's not obvious to me that we shouldn't. A user use-case which often writes and re-writes to the same row will benefit from caching the read, won't it?

**Comment by psarna** [comment]
Yes, intensive rewrites would benefit from having this data cached - the question is how often this use case actually appears (and how well it mixes with having materialized views, since it's kind of an antipattern - rewrites usually produce 2 view updates per just 1 user write).
I suppose a more versatile solution could use more context, similarly to the `streaming_reason` parameter that we have in streaming.

**Comment by denesb** [comment]
I think its a question -- as @psarna already mentioned -- whether reads or writes should drive the content of the cache. The fact that on memtable flush we merge the content of the memtable with the cache muddies the waters, although we don't merge *everything*, see https://github.com/scylladb/scylla/issues/5257.

**Comment by avikivity** [comment]
Certainly user writes should use the cache. It would be a huge slowdown if a workload that could hit the cache (like multiple updates to the same row in a short time) was forced ot miss.

For repair, it makes sense to skip the cache, since we won't touch the same row twice.

**Comment by psarna** [comment]
@avikivity I agree, makes sense. I assume that our cache writes through in case of the same row being read/written multiple times, right? Under the assumption that the old state of the row would already be cached when the write happens - because otherwise hitting the same row during view updates wouldn't bring much benefit, since the cache entry would already be invalidated by the write operation.

**Comment by kostja** [comment]
Addressing each specific workload which leads to watering down the cache will lead to fragmentation of the fix for the problem. Normally this is handled by splitting the cache to warm and hot zones, so that the hot zone is never affected by sweeping scans.

**Comment by avikivity** [comment]
Not a bug, not backporting.
