### ISSUE TITLE
Creating schemas with explicit column_ids should be deprecated

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#6235]
Following a mailing list discussion: https://groups.google.com/forum/#!topic/scylladb-dev/xZSJArP1CwI

The usual way of creating a new schema was to add columns one-by-one with a `with_column()` method. This method has several overloads, one of which allowing to explicitly set the column id, used to decide the final order of columns. The other, more commonly used overload, assumes that the order is the same as the order in which the user added the columns with `with_column()` calls.

The first interface is confusing, since it makes it unclear who is responsible for sorting the columns - the caller or the callee?

In order to unify the interface and remove the ambiguity, the less used overload which allows explicitly stating the order should be removed.

This issue is inspired by #5856, whose root cause is a result of this confusion.

**Comment by psarna** [comment]
edit: creating with `column_id` via the interface which uses `column_definition` is quite heavily used by schema tables... I started to prepare a patch, but it's getting very ugly and I'm not yet halfway through all the changes. The problematic part is when compound keys have their components ordered differently than the lexicographical order, which results in them not being ordered in `system_schema.columns`:

```cql
 keyspace_name | table_name | column_name | clustering_order | column_name_bytes | kind          | position | type
---------------+------------+-------------+------------------+-------------------+---------------+----------+------
            ks |         tt |          c1 |              ASC |            0x6331 |    clustering |        1 |  int
            ks |         tt |          c2 |              ASC |            0x6332 |    clustering |        0 |  int
            ks |         tt |          c3 |              ASC |            0x6333 |    clustering |        2 |  int
            ks |         tt |         id1 |             NONE |          0x696431 | partition_key |        0 |  int
            ks |         tt |         id2 |             NONE |          0x696432 | partition_key |        1 |  int
            ks |         tt |          v1 |             NONE |            0x7631 |       regular |       -1 |  int
            ks |         tt |          v2 |             NONE |            0x7632 |       regular |       -1 |  int
            ks |         tt |          v4 |             NONE |            0x7634 |       regular |       -1 |  int
            ks |         tt |          v5 |             NONE |            0x7635 |       regular |       -1 |  int
            ks |         tt |          v6 |             NONE |            0x7636 |       regular |       -1 |  int
```
- note that the clustering key is actually (c2, c1, c3). The whole code which restores and saves columns relies on adding the columns with explicit column_id, assuming that they will be sorted later, and moving all the sorting to the callee results in a rather complicated, error-prone patch...

**Comment by psarna** [comment]
@avikivity fyi ^, I'm not sure if deprecating the interface is worth it anymore, given that it actually has quite a few users in delicate parts of schema management code.

**Comment by avikivity** [comment]
Then maybe make the overload that takes column_id private (or remove it).

**Comment by avikivity** [comment]
And add with_column_ordered(column_definition)

**Comment by avikivity** [comment]
Internal change, not backporting.
