### ISSUE TITLE
repair failed with error get_full_row_hashes_with_rpc_stream_handler

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#6239]
*Installation details*
Scylla version (or git commit hash): 4.0.rc1-0.20200412.a8ef820f27c with build-id 15fa5c2e803b98279bb1932abf806dfb7937238c
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0e1584bf517753731

Longevity 1TB, running with only `terminate_and_repair` nemesis, trying to reproduce the issue #6182 .

Nodes were deployed, and the data set was written (prepare stage), and then, a `terminate_and_replace` nemesis started. After 6 hours, the 1st try to add a node timed out (node-5) during `replace_with_repair`.

After it timed out, SCT marked it as failed, and deploy a new node, where this time, succeeded to `replace_with_repair`, but lately failed on `user-requested` repair.

The error happened on only 1 shard being repaired (all other shards succeeded), after a node was terminated and replaced:
```
< t:2020-04-15 09:39:04,198 f:cluster.py      l:1417 c:sdcm.cluster         p:DEBUG > 2020-04-14T16:36:08+00:00  longevity-tls-1tb-7d-longevit-db-node-a9c535be-2 !INFO    | scylla: [shard 6] repair - Failed to process get_full_row_hashes_with_rpc_stream_handler from=10.0.255.213, repair_meta_id=300877: seastar::rpc::closed_error (connection is closed)
```

node logs can be found here:
```
+--------------------------------------------------------------------------------------------------------------------------------------------+
|                                      Collected logs by test-id: a9c535be-1ea6-4ddb-8c17-4e2b712772d6                                       |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| Cluster set | Link                                                                                                                         |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
| db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/a9c535be-1ea6-4ddb-8c17-4e2b712772d6/20200419_135903/db-cluster-a9c535be.zip  |
| monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/a9c535be-1ea6-4ddb-8c17-4e2b712772d6/20200419_135903/monitor-set-a9c535be.zip |
| loader-set  | none                                                                                                                         |
| sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/a9c535be-1ea6-4ddb-8c17-4e2b712772d6/20200419_135903/sct-runner-a9c535be.zip  |
+-------------+------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by slivne** [comment]
@roydahan are we hitting this on 4.1 - if not lets close

**Comment by roydahan** [comment]
haven't seen that yet, but let's wait for the other issues where repair get stuck before we're closing this.

**Comment by asias** [comment]
The repair get stuck issue is fixed on 4.1 and 4.2. Can we close this issue now?

**Comment by avikivity** [comment]
It was reported on 4.0. What's the status there?

**Comment by slivne** [comment]
4.0.X is dead - closing this issue

We still have some issues related to repair (namely repair and TWCS) - but we have other issues tracking this - closing this issue
