### ISSUE TITLE
Missing API for compaction history

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#624]
When calling the compaction summary API you get an
Failed with /compaction_manager/compaction_summary {"message": "API call is not supported yet", "code": 500}

**Comment by slivne** [comment]
@amnonh can we close this ?

**Comment by tzach** [comment]
@amnonh what nodetool operation is affected?

**Comment by avikivity** [comment]
@amnonh please update

**Comment by amnonh** [comment]
Commit: https://github.com/scylladb/scylla/commit/54b4f26cb0c0fce28cb55e8077ad8c5f2e63e35a
Removed the compaction_summary endpoint, `/compaction_manager/compactions` return a list of running compactions.
And `/compaction_manager/compaction_history` the compactions history

**Comment by avikivity** [comment]
Already in 0.13+, not backporting further.
