### ISSUE TITLE
multishard_writer can dead lock when producer fails

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#6241]
We have this in multishard_writer:
    
    future<uint64_t> multishard_writer::operator()() {
        return distribute_mutation_fragments().finally([this] {
            return wait_pending_consumers();
        }).then([this] {
            return _consumed_partitions;
        });
    }
    
The wait_pending_consumers which waits for the consumers to finish is
called even when distribute_mutation_fragments fails.
    
When distribute_mutation_fragments fails and the failure is due to the
producer fails, consumers can wait for data which will never come because
the producer has failed already. This can cause a deadlock.

This is supposed to be the root cause of stream hang during repair observed by a user.

**Comment by avikivity** [comment]
Already backported.
