### ISSUE TITLE
dist/offline_installer/redhat: causes "scylla does not work with current umask setting (0077)"

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#6243]
After installed rpm, the script causes following error while auto-executing scylla_setup.
```
Scylla does not work with current umask setting (0077),
please restore umask to the default value (0022).
```
Because offline install script which generated by "makeself" modifies umask at the beginning of the script:
```
#!/bin/sh
# This script was generated using Makeself 2.2.0

umask 077
```

**Comment by penberg** [comment]
@syuu1228 Wasn't this issue fixed by https://github.com/scylladb/scylla/commit/1e2509ffec632b7332832065eeb39df1fe23180d? Can we close the issue?

**Comment by fruch** [comment]
@syuu1228 I've trying to use OEL8.1, and failing on the same issue:

https://jenkins.scylladb.com/job/scylla-staging/job/fruch/job/oel8/3/console

**Comment by roydahan** [comment]
Apparently not closed, still happens on 4.4.rc0 with OEL 8.1.
@yarongilor please add the details.

**Comment by yarongilor** [comment]
reproduced in:

Test details
Test: artifacts_test.ArtifactsTest.test_scylla_service
Build number: 4
Backend: aws: eu-west-1
Test-id: 1c6a30b2-6099-4ef6-8b88-a773001b4376
Start time: 2021-01-25 16:06:39
End time: 2021-01-25 16:11:39
Started by user: yarongilor
Private repo: https://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla/branch-4.4/rpm/centos/2021-01-20T19:17:24Z/scylla.repo
Test result
FAILED
System under test
ScyllaDB version:
ScyllaDB repo: https://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla/branch-4.4/rpm/centos/2021-01-20T19:17:24Z/scylla.repo
Actual aws image used: ami-0e883e67243efea62
AWS region: eu-west-1
Instance type: i3.large
Scylla packages installed:
scylla-node-exporter-4.4.rc0-0.20210120.46e627382.x86_64
scylla-tools-4.4.rc0-0.20210120.46e627382.noarch
scylla-conf-4.4.rc0-0.20210120.46e627382.x86_64
scylla-python3-4.4.rc0-0.20210120.46e627382.x86_64
scylla-jmx-4.4.rc0-0.20210120.46e627382.noarch
scylla-kernel-conf-4.4.rc0-0.20210120.46e627382.x86_64
scylla-tools-core-4.4.rc0-0.20210120.46e627382.noarch
scylla-4.4.rc0-0.20210120.46e627382.x86_64
scylla-server-4.4.rc0-0.20210120.46e627382.x86_64

error:
```
2021-01-25 16:11:32.888: (TestFrameworkEvent Severity.ERROR), source=ArtifactsTest.SetUp()
exception=[Node artifacts-oel76-jenkins-db-node-1c6a30b2-1 [34.251.94.206 | 10.0.0.107] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic ens3 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
Exit code: 1
Stdout:
 [1;31mScylla does not work with current umask setting (0077),
please restore umask to the default value (0022). [0m
Stderr:
/etc/bashrc: line 99: TMOUT: readonly variable
/etc/bashrc: line 100: TMOUT: readonly variable
Traceback (most recent call last):
File "/home/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-oel81-test@2/scylla-cluster-tests/sdcm/cluster.py", line 3268, in node_setup
cl_inst.node_setup(_node, **setup_kwargs)
File "/home/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-oel81-test@2/scylla-cluster-tests/sdcm/cluster.py", line 3894, in node_setup
self._scylla_post_install(node, install_scylla, devname)
File "/home/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-oel81-test@2/scylla-cluster-tests/sdcm/cluster_aws.py", line 933, in _scylla_post_install
super()._scylla_post_install(node, new_scylla_installed, devname)
File "/home/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-oel81-test@2/scylla-cluster-tests/sdcm/cluster.py", line 3958, in _scylla_post_install
node.scylla_setup(disks, devname)
File "/home/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-oel81-test@2/scylla-cluster-tests/sdcm/utils/decorators.py", line 110, in inner
res = func(*args, **kwargs)
File "/home/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-oel81-test@2/scylla-cluster-tests/sdcm/cluster.py", line 2181, in scylla_setup
self.remoter.run('sudo /usr/lib/scylla/scylla_setup --nic {} --disks {} --setup-nic-and-disks {}'
File "/home/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-oel81-test@2/scylla-cluster-tests/sdcm/remote/remote_base.py", line 604, in run
result = _run()
File "/home/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-oel81-test@2/scylla-cluster-tests/sdcm/utils/decorators.py", line 61, in inner
return func(*args, **kwargs)
File "/home/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-oel81-test@2/scylla-cluster-tests/sdcm/remote/remote_base.py", line 596, in _run
return self._run_execute(cmd, timeout, ignore_status, verbose, new_session, watchers)
File "/home/jenkins/slave/workspace/scylla-4.4/artifacts/artifacts-oel81-test@2/scylla-cluster-tests/sdcm/remote/remote_base.py", line 537, in _run_execute
result = connection.run(**command_kwargs)
File "<decorator-gen-3>", line 2, in run
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 30, in opens
return method(self, *args, **kwargs)
File "/usr/local/lib/python3.9/site-packages/fabric/connection.py", line 721, in run
return self._run(self._remote_runner(), command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/context.py", line 101, in _run
return runner.run(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 291, in run
return self._run_body(command, **kwargs)
File "/usr/local/lib/python3.9/site-packages/invoke/runners.py", line 442, in _run_body
raise UnexpectedExit(result)
invoke.exceptions.UnexpectedExit: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic ens3 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
Exit code: 1
Stdout:
 [1;31mScylla does not work with current umask setting (0077),
please restore umask to the default value (0022). [0m
Stderr:
/etc/bashrc: line 99: TMOUT: readonly variable
/etc/bashrc: line 100: TMOUT: readonly variable
```

Logs:
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/1c6a30b2-6099-4ef6-8b88-a773001b4376/20210125_161156/db-cluster-1c6a30b2.zip
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/1c6a30b2-6099-4ef6-8b88-a773001b4376/20210125_161156/sct-runner-1c6a30b2.zip
Links:
Build URL: https://jenkins.scylladb.com/job/scylla-4.4/job/artifacts/job/artifacts-oel81-test/4/

**Comment by penberg** [comment]
This is fixed by the series https://github.com/scylladb/scylla/pull/6244. @syuu1228 there are still some outstanding review comments from @avikivity. Can you please address them and let's get it merged?

**Comment by yarongilor** [comment]
fixed on scylla master. not fixed in branch 4.4 after backport.
the fix was:
2500dd1dc - Merge 'dist/offline_installer/redhat: fix umask error' from Takuya ASADA
the backport is: 
https://www.google.com/url?q=https://github.com/scylladb/scylla/commit/2500dd1dc47c311179fa98eadbf6d580dbc5efc8&sa=D&source=editors&ust=1612861073002000&usg=AFQjCNF4sTxEAXvMRlXqYNLXs2ehuPa7-w

Test details
Test: artifacts_test.ArtifactsTest.test_scylla_service
Build number: 6
Backend: aws: eu-west-1
Test-id: 7200ff6c-341c-4401-9fbd-3621eab071a7
Start time: 2021-02-08 12:02:55
End time: 2021-02-08 12:07:51
Started by user: roy
Private repo: https://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla/branch-4.4/rpm/centos/2021-02-05T17:31:17Z/scylla.repo
Test result
FAILED
System under test
ScyllaDB version:
ScyllaDB repo: https://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla/branch-4.4/rpm/centos/2021-02-05T17:31:17Z/scylla.repo
Actual aws image used: ami-0e883e67243efea62
AWS region: eu-west-1
Instance type: i3.large
Scylla packages installed:
scylla-node-exporter-4.4.rc1-0.20210205.2500dd1dc.x86_64
scylla-tools-4.4.rc1-0.20210205.2500dd1dc.noarch
scylla-conf-4.4.rc1-0.20210205.2500dd1dc.x86_64
scylla-python3-4.4.rc1-0.20210205.2500dd1dc.x86_64
scylla-jmx-4.4.rc1-0.20210205.2500dd1dc.noarch
scylla-kernel-conf-4.4.rc1-0.20210205.2500dd1dc.x86_64
scylla-tools-core-4.4.rc1-0.20210205.2500dd1dc.noarch
scylla-4.4.rc1-0.20210205.2500dd1dc.x86_64
scylla-server-4.4.rc1-0.20210205.2500dd1dc.x86_64

error log:
```
2021-02-08 12:07:45.188: (TestFrameworkEvent Severity.ERROR), source=ArtifactsTest.SetUp()
exception=[Node artifacts-oel76-jenkins-db-node-7200ff6c-1 [34.244.79.61 | 10.0.3.230] (seed: True)] NodeSetupFailed: Encountered a bad command exit code!
Command: 'sudo /usr/lib/scylla/scylla_setup --nic ens3 --disks /dev/nvme0n1 --setup-nic-and-disks  --swap-directory / '
Exit code: 1
Stdout:
 [1;31mScylla does not work with current umask setting (0077),
please restore umask to the default value (0022). [0m
Stderr:
/etc/bashrc: line 99: TMOUT: readonly variable
/etc/bashrc: line 100: TMOUT: readonly variable
```

**Comment by syuu1228** [comment]
@yarongilor It is not caused by dist/offline_installer/redhat, since any artifact test running the script.
The script is not well maintained and rarely used, I think we never run any test on it.
And it's NOT what we called "offline installer" today, confusing though.

I found OEL8 AMI causing the issue, please see #8049

**Comment by syuu1228** [comment]
I think this issue can close now.

**Comment by yarongilor** [comment]
thanks, @syuu1228 .

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
