### ISSUE TITLE
Row level repair export parameters in a metric

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla#6245]
Scylla Manager should be able to get know the maximal level of parallelism of a shard.
[max_repair_ranges_in_parallel](https://github.com/scylladb/scylla/blob/13a9c5eaf7fa4c7be33c047382e05e62f4852b24/repair/repair.cc#L226) should be exposed as a metric.

**Comment by slivne** [comment]
@mmatczuk the config is exposed - can't you fetch the info from that ?

**Comment by mmatczuk** [comment]
We want to know what Scylla runtime thinks is the max nr. of ranges in parallel (per shard) it can do.
This is a function of max_repair_memory, maybe the code could be ported but we agreed with @asias to expose the runtime value as a metric.

https://github.com/scylladb/scylla/blob/d78fbf7c1677a6d30d9f4c24796147c45b582871/repair/repair.cc#L225

Can you point me to the exposed config I failed to find it @slivne.

**Comment by mmatczuk** [comment]
I had a look around, it seems that I could estimate the value.
Let N be total host memory in bytes.

`max_repair_ranges_in_parallel ~= N * 0.93 * 0.1 / (32 * 1024 * 1024)`

@amnonh is there a way in API to get memory assigned to Scylla?

**Comment by slivne** [comment]
@mmatczuk my bad - I thought its under some configuration.

**Comment by slivne** [comment]
@asias is this true for row level repair and "old" partition level repair ?

**Comment by asias** [comment]
> I had a look around, it seems that I could estimate the value.
> Let N be total host memory in bytes then:
> 
> `max_repair_ranges_in_parallel ~= N * 0.93 * 0.1 / (32 * 1024 * 1024)`
> 
> @amnonh is there a way in API to get memory assigned to Scylla?

Hello @mmatczuk 

The calculation is:

max_repair_ranges_in_parallel = max_repair_memory / max_repair_memory_per_range = 10% * memory_per_shard / max_repair_memory_per_range = 0.1 * memory_per_shard / 32 MiB 

E.g., 1GiB memory  per shard, we will have:

INFO  2020-05-14 10:13:12,161 [shard 0] repair - Setting max_repair_memory=107374182, max_repair_memory_per_range=33554432, max_repair_ranges_in_parallel=3

If you can get the per shard memory size, you can calculate the max_repair_ranges_in_parallel in scylla manager.

**Comment by mmatczuk** [comment]
Yes so this is in essence what I wrote. In my version it's aggregated for all shards plus I estimate Scylla memory. Need to check if there is a metric for that.

**Comment by mmatczuk** [comment]
I found:

```
# HELP scylla_memory_total_memory Total memeory size in bytes
# TYPE scylla_memory_total_memory counter
```

**Comment by asias** [comment]
Since we can calculate the number from scylla_memory_total_memory. We can avoid exporting it as metrics. @mmatczuk I am closing this please reopen if you disagree.
