### ISSUE TITLE
alternator tests can be slow or fail depending on host configuration

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#6251]
Alternator tests run with the host number of CPUs, but only 1GB RAM, leading to very low memory per shard in some configurations. The configuration also insists on fsyncing writes, which is slow on some disks.

**Comment by avikivity** [comment]
Patch posted: "[PATCH scylla v1] test: alternator: configure scylla for test environment in terms of cpu and disk"

**Comment by nyh** [comment]
Already backported to 4.0 by Avi (commit 2482e53de98c5b3dfaab994444daa84f2bec7bd9). No additional backports needed.
