### ISSUE TITLE
Alternator streaming test does not work on newer boto3 versions

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#6255]
Since boto3 started validating more parameters on its own, one of our tests which check incorrect behavior got deprecated. This issue is already solved by fe6cecb26d, but it needs a tracking issue number in order to be backported properly.

**Comment by psarna** [comment]
queued as bc67da1a2

**Comment by nyh** [comment]
Closing. @psarna also already backported to 4.0 so nothing left to do.
