### ISSUE TITLE
XFS mount with discard caused issues

### ISSUE THREAD

**Issue by noamha-ken** [scylladb/scylla#626]
I've mounted a raid XFS with "discard" option, this may have caused the XFS to crush after running a heavy stress on Scylla, which resulted in very very slow deletion of the Commit Log folder.

**Comment by tzach** [comment]
@noamha-ken what command did you use?

**Comment by slivne** [comment]
It's from our wiki

https://github.com/scylladb/scylla/wiki/Scylla-production-recommendation

Taken from the ami we need to fix it as well

**Comment by slivne** [comment]
fixed by 79e70568d7f05d41b4fa24fcb2217769f6b6ef40
