### ISSUE TITLE
Staging SSTables can be resharded while being moved to new directory

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6261]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

Staging SSTables which become shared after a restart can be selected for resharding, and there could be a race condition in which a shared staging SSTable can be resharded in the staging directory itself while it's being moved to a new directory. Investigate that.

**Comment by raphaelsc** [comment]
This problem no longer affects master, but it still affects older versions, so it's still worth a fix AFAICT. @bhalevy @slivne

**Comment by raphaelsc** [comment]
BTW, what I am saying is that this problem was unintentionally fixed by off-strategy work. Backporting off-strategy work to older versions is probably a big no-no as it hasn't cooked well and still not properly tested. So if this issue is affecting users, we should possibly consider writing a simple fix and backport it.

**Comment by bhalevy** [comment]
Agreed.  We need a (simple) fix for the affected versions.
Is disallowing loading new sstables from the base directory enough?
I think it would be not too complicated to be implemented in `storage_service::load_new_sstables`

**Comment by raphaelsc** [comment]
@bhalevy No because even if the sstable comes from upload dir it still could be picked for resharding after it was loaded into staging dir. The simplest fix I can think of is to filter out staging sstables in the resharding procedure that collects shared sstables from all shards for resharding.

**Comment by bhalevy** [comment]
@raphaelsc does the problem exist in 4.2?

**Comment by raphaelsc** [comment]
@bhalevy, no. any branch that has https://github.com/scylladb/scylla/commit/e40aa042a7405d9c0d3db97e639f6280f95eb98e#diff-6f3b06db526ce55c337ae0c258546480 is not vulnerable.

**Comment by slivne** [comment]
closing this issue - 4.1 is not supported anymore

**Comment by slivne** [comment]
we reshard at boot before node is online - so there is no possibility to reshard while moving files
