### ISSUE TITLE
Drop OVERFLOW_ERROR cql binary protocol extention.

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#6264]
*Installation details*
Scylla version (or git commit hash): 3.3.0, 4.0.rc1,  2aaf81bf7c288eb1292a9c06b3d7a122e7ab4f06

We should not extent cql binary protocol without negotiating with a driver that the extension is supported. But this is what  e97a111f642aff2aa1241a9d4261edfd97e545c1 does. We either need to drop the extension or add negotiation.

**Comment by bhalevy** [comment]
I guess we can overload `exception_code::INVALID` for arithmetic overflow.
Looking at cassandra code it it a catch-all exception with a flexible message.
@avikivity, @penberg what do you think?

**Comment by avikivity** [comment]
Aged out, no need to backport.
