### ISSUE TITLE
Commit log reader drops subscription

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#6265]
In e4b8f52237dee8aa776f3cfb0c1b3f8d7912d306 the return type for `commitlog::read_log_file` was changed to a `future<>`, namely the future of `subscription<...>::done()`. However, the subscription in question was not preserved across reader `stream` lifetime, which in turn will occasionally cause us to call into a deleted object. 

Need to preserve `substription` during returned future life time.

**Comment by elcallio** [comment]
Note: the crashing occurs iff we manage to reach the execution point where we free the subscription as a result of continuation switching in the the `produce`callback (`next`). Deleted subscriptions unregister from their streams, but does not wait for any calls into them to complete (nor should they). 

If we are "lucky", we will instead miss commitlog entries, and probably hang waiting for the future.

**Comment by avikivity** [comment]
Backported to 4.0. 3.3 appears not to have the problem, @elcallio please confirm.

**Comment by elcallio** [comment]
3.3 (and older I presume) still have the subscription-returning variant, so not susceptible, no.
