### ISSUE TITLE
Support versions in Scylla repos

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#627]
It should be possible to install specific version of Scylla from the repo, not just the latest.
For example
```
sudo yum install scylla-server-0.11
```
or
```
sudo apt-get install -t=0.11 scylla-server
```

**Comment by tzach** [comment]
@slivne what is the effort require to allow this?

**Comment by tzach** [comment]
@slivne can we close?

**Comment by slivne** [comment]
@tzach: yes
