### ISSUE TITLE
Alternator test may not wait long enough in debug mode on slow machine

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#6271]
The script `alternator/test/run` has an arbitrary timeout of 100 seconds for booting Scylla to be tested. This is normally more than enough (on my machine, it usually takes about  25 seconds), but @yarongilor saw in a few cases such as https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/build_debug/762/consoleFull that 100 seconds was not enough. Apparently this happens only in _debug_ builds, and on extremely overcommitted test machines.

So we should increase this timeout of 100 seconds.
There is no risk in increasing this timeout: In normal circumstances, we never wait for this timeout. Both boot successes and failures are recognized quickly, and we don't wait for the full timeout.

**Comment by nyh** [comment]
Oops, tagged the wrong Yaron. Actualy @yaronkaikov

**Comment by nyh** [comment]
Sent a patch for this to the mailing list, titled "test/alternator: increase timeout on Scylla boot"

**Comment by psarna** [comment]
queued as 92e36c5df515e6c2e7dd1842833647b61bbbc5d3

**Comment by nyh** [comment]
Backported to 4.0 (commit 92e36c5df515e6c2e7dd1842833647b61bbbc5d3). No further backports needed.
