### ISSUE TITLE
Lots of messages like "sstable - Unable to delete /path/to/la-1-big-TOC.txt because it doesn't exist."

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6275]
Scylla version (or git commit hash): 12ddacc

Description
User started seeing a lot of the following errors in logs of multiple nodes and in the context of multiple tables:

Compaction strategy: LCS

[shard 21] sstable - Unable to delete /path/to/la-1-big-TOC.txt because it doesn't exist.

**Comment by raphaelsc** [comment]
This problem happens when deleting a GC SSTable

**Comment by avikivity** [comment]
@raphaelsc please backport to 4.0.

**Comment by raphaelsc** [comment]
On Wed, Jul 1, 2020 at 6:51 AM Avi Kivity <notifications@github.com> wrote:
>
> @raphaelsc please backport to 4.0.

Not an easy task to backport this, lots of conflicts. I will prepare a
backport probably next week as I'd like to do some proper testing to
make sure there's no regression.

**Comment by avikivity** [comment]
@raphaelsc please increase priority

**Comment by withings-sas** [comment]
We are seeing this related error on our 4.0 cluster:

```
sstable - Unable to delete /var/lib/scylla/data/measure/measure_99_ng-a765b280ceba11e98d69000000000001/mc-31760-big-TOC.txt because it doesn't exist
```

And stuck pending compactions:

```
# nodetool compactionstats
pending tasks: 51
```

Will upgrading to 4.1 fix this or should I wait for a patch release of 4.0 ?

**Comment by avikivity** [comment]
Upgrading should fix it.

**Comment by raphaelsc** [comment]
On Thu, Aug 6, 2020 at 6:11 AM Avi Kivity <notifications@github.com> wrote:

> @raphaelsc <https://github.com/raphaelsc> please increase priority
>
Alright. I will work on it today.

**Comment by avikivity** [comment]
Aged out.
