### ISSUE TITLE
Failing on creation of second scylla container

### ISSUE THREAD

**Issue by ssdubey** [scylladb/scylla#6276]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): Scylla version 3.3.0-0.20200319.7ae2cdf46c7
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): docker
Hardware: sockets= cores= hyperthreading= memory= core: 56; memory: 62GB
Disks: (SSD/HDD, count): HDD

Unable to create the second container with the docker. First container is created normally. The issue has arbitrarily occured on this machine. I have nicely running clusters on other machines. Second container is failing while creation itself. Below is the attached log:

shashank@church:~$ docker logs bm_scylla2
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '1'],)
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
2020-04-23 12:33:44,360 CRIT Supervisor running as root (no user in config file)
2020-04-23 12:33:44,360 WARN Included extra file "/etc/supervisord.conf.d/scylla-server.conf" during parsing
2020-04-23 12:33:44,361 WARN Included extra file "/etc/supervisord.conf.d/node-exporter.conf" during parsing
2020-04-23 12:33:44,361 WARN Included extra file "/etc/supervisord.conf.d/scylla-jmx.conf" during parsing
2020-04-23 12:33:44,361 WARN Included extra file "/etc/supervisord.conf.d/sshd-server.conf" during parsing
2020-04-23 12:33:44,361 WARN Included extra file "/etc/supervisord.conf.d/scylla-housekeeping.conf" during parsing
2020-04-23 12:33:44,405 INFO RPC interface 'supervisor' initialized
2020-04-23 12:33:44,406 CRIT Server 'inet_http_server' running without any HTTP authentication checking
2020-04-23 12:33:44,406 INFO supervisord started with pid 25
2020-04-23 12:33:45,409 INFO spawned: 'scylla-jmx' with pid 28
2020-04-23 12:33:45,412 INFO spawned: 'scylla' with pid 29
2020-04-23 12:33:45,415 INFO spawned: 'node-exporter' with pid 30
2020-04-23 12:33:45,418 INFO spawned: 'sshd' with pid 31
2020-04-23 12:33:45,421 INFO spawned: 'scylla-housekeeping' with pid 32
time="2020-04-23T12:33:45Z" level=info msg="Starting node_exporter (version=0.17.0, branch=HEAD, revision=f6f6194a436b9a63d0439abc585c76b19a206b21)" source="node_exporter.go:82"
time="2020-04-23T12:33:45Z" level=info msg="Build context (go=go1.11.2, user=root@322511e06ced, date=20181130-15:51:33)" source="node_exporter.go:83"
time="2020-04-23T12:33:45Z" level=info msg="Enabled collectors:" source="node_exporter.go:90"
time="2020-04-23T12:33:45Z" level=info msg=" - arp" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - bcache" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - bonding" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - conntrack" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - cpu" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - diskstats" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - edac" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - entropy" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - filefd" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - filesystem" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - hwmon" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - infiniband" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - interrupts" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - ipvs" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - loadavg" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - mdadm" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - meminfo" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - netclass" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - netdev" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - netstat" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - nfs" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - nfsd" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - sockstat" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - stat" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - textfile" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - time" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - timex" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - uname" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - vmstat" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - xfs" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg=" - zfs" source="node_exporter.go:97"
time="2020-04-23T12:33:45Z" level=info msg="Listening on :9100" source="node_exporter.go:111"
Generating public/private ed25519 key pair.
Your identification has been saved in /etc/ssh/ssh_host_ed25519_key.
Your public key has been saved in /etc/ssh/ssh_host_ed25519_key.pub.
The key fingerprint is:
SHA256:VmH0QvTcG02+R90GIxa5/Ojh+NFjXjybruh+1Pi0CE8 root@9c4ba6aeac04
The key's randomart image is:
+--[ED25519 256]--+
|         o* +oo .|
|         o *.o *o|
|          o.+.o B|
|         . .o  =.|
|        S    o+..|
|       .   .oE.+.|
|           +*.B.+|
|          . +B =+|
|          o=o.++ |
+----[SHA256]-----+
Connecting to http://localhost:10000
Starting the JMX server
Scylla version 3.3.0-0.20200319.7ae2cdf46c7 with build-id e1a6c0b608140610f1e783632d61f1f2c7fb932d starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.3 --rpc-address 172.17.0.3 --seed-provider-parameters seeds=172.17.0.3 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.3, rpc-address: 172.17.0.3, seed-provider-parameters: seeds=172.17.0.3, blocked-reactor-notify-ms: 999999999]
terminate called without an active exception
terminate called recursively
terminate called recursively
Aborting on shard 4.
Backtrace:
  0x0000000002a5de52
  0x0000000002a049cb
  0x0000000002a04cc5
  0x0000000002a04d60
  0x00007fe54fe11b1f
  /opt/scylladb/libreloc/libc.so.6+0x000000000003c624
  /opt/scylladb/libreloc/libc.so.6+0x00000000000258d8
  /opt/scylladb/libreloc/libstdc++.so.6+0x000000000009e6b5
  /opt/scylladb/libreloc/libstdc++.so.6+0x00000000000aa86b
  /opt/scylladb/libreloc/libstdc++.so.6+0x00000000000aa8c6
  0x0000000002df286a
  0x000000000067a472
  0x0000000002a4bac5
  0x0000000002a4f769
  0x00000000029db50d
  /opt/scylladb/libreloc/libpthread.so.0+0x00000000000094e1
  /opt/scylladb/libreloc/libc.so.6+0x0000000000101692
Generating public/private rsa key pair.
Your identification has been saved in /etc/ssh/ssh_host_rsa_key.
Your public key has been saved in /etc/ssh/ssh_host_rsa_key.pub.
The key fingerprint is:
SHA256:rj3Uxa1sjDRE3AZfYeSv5IGzYzb+GYRSB6iV/V2dpNI root@9c4ba6aeac04
The key's randomart image is:
+---[RSA 4096]----+
|         oo*..*oo|
|          *.==..o|
|         + +oEo..|
|        . o.++o..|
|        So.*+.+ .|
|       .. o.=* o |
|       ..  .* +  |
|       o.  + o o |
|      . ..  ..o  |
+----[SHA256]-----+
JMX is enabled to receive remote connections on port: 7199
Could not load host key: /etc/ssh/ssh_host_ecdsa_key
2020-04-23 12:33:46,183 INFO exited: scylla (terminated by SIGABRT (core dumped); not expected)
2020-04-23 12:33:47,185 INFO success: scylla-jmx entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-23 12:33:47,188 INFO spawned: 'scylla' with pid 131
2020-04-23 12:33:47,189 INFO success: node-exporter entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-23 12:33:47,189 INFO success: sshd entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2020-04-23 12:33:47,189 INFO success: scylla-housekeeping entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Scylla version 3.3.0-0.20200319.7ae2cdf46c7 with build-id e1a6c0b608140610f1e783632d61f1f2c7fb932d starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.3 --rpc-address 172.17.0.3 --seed-provider-parameters seeds=172.17.0.3 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.3, rpc-address: 172.17.0.3, seed-provider-parameters: seeds=172.17.0.3, blocked-reactor-notify-ms: 999999999]
terminate called without an active exception
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
Aborting on shard 17.
Backtrace:
  0x0000000002a5de52
  0x0000000002a049cb
  0x0000000002a04cc5
  0x0000000002a04d60
  0x00007f18b923bb1f
  /opt/scylladb/libreloc/libc.so.6+0x000000000003c624
  /opt/scylladb/libreloc/libc.so.6+0x00000000000258d8
  /opt/scylladb/libreloc/libstdc++.so.6+0x000000000009e6b5
  /opt/scylladb/libreloc/libstdc++.so.6+0x00000000000aa86b
  /opt/scylladb/libreloc/libstdc++.so.6+0x00000000000aa8c6
  0x0000000002df286a
  0x000000000067a472
  0x0000000002a4bac5
  0x0000000002a4f769
  0x00000000029db50d
  /opt/scylladb/libreloc/libpthread.so.0+0x00000000000094e1
  /opt/scylladb/libreloc/libc.so.6+0x0000000000101692
2020-04-23 12:33:47,928 INFO exited: scylla (terminated by SIGABRT (core dumped); not expected)
2020-04-23 12:33:49,933 INFO spawned: 'scylla' with pid 217
Scylla version 3.3.0-0.20200319.7ae2cdf46c7 with build-id e1a6c0b608140610f1e783632d61f1f2c7fb932d starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.3 --rpc-address 172.17.0.3 --seed-provider-parameters seeds=172.17.0.3 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.3, rpc-address: 172.17.0.3, seed-provider-parameters: seeds=172.17.0.3, blocked-reactor-notify-ms: 999999999]
terminate called without an active exception
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
Aborting on shard 13.
Backtrace:
  0x0000000002a5de52
  0x0000000002a049cb
  0x0000000002a04cc5
  0x0000000002a04d60
  0x00007f92cf118b1f
  /opt/scylladb/libreloc/libc.so.6+0x000000000003c624
  /opt/scylladb/libreloc/libc.so.6+0x00000000000258d8
  /opt/scylladb/libreloc/libstdc++.so.6+0x000000000009e6b5
  /opt/scylladb/libreloc/libstdc++.so.6+0x00000000000aa86b
  /opt/scylladb/libreloc/libstdc++.so.6+0x00000000000aa8c6
  0x0000000002df286a
  0x000000000067a472
  0x0000000002a4bac5
  0x0000000002a4f769
  0x00000000029db50d
  /opt/scylladb/libreloc/libpthread.so.0+0x00000000000094e1
  /opt/scylladb/libreloc/libc.so.6+0x0000000000101692
2020-04-23 12:33:50,611 INFO exited: scylla (terminated by SIGABRT (core dumped); not expected)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1298, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1247, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/opt/scylladb/python3/lib64/python3.7/http/client.py", line 938, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/scylladb/python3/lib64/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/opt/scylladb/python3/lib64/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scylladb/python3/lib64/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 64, in get_url
    return urllib.request.urlopen(path).read().decode('utf-8')
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 1347, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/opt/scylladb/python3/lib64/python3.7/urllib/request.py", line 1321, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 197, in <module>
    args.func(args)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 123, in check_version
    current_version = sanitize_version(get_api('/storage_service/scylla_release_version'))
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 82, in get_api
    return get_json_from_url("http://" + api_address + path)
  File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 74, in get_json_from_url
    retval = result.get(timeout=5)
  File "/opt/scylladb/python3/lib64/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
2020-04-23 12:33:53,893 INFO spawned: 'scylla' with pid 299
Scylla version 3.3.0-0.20200319.7ae2cdf46c7 with build-id e1a6c0b608140610f1e783632d61f1f2c7fb932d starting ...
command used: "/usr/bin/scylla --log-to-syslog 0 --log-to-stdout 1 --default-log-level info --network-stack posix --developer-mode=1 --overprovisioned --listen-address 172.17.0.3 --rpc-address 172.17.0.3 --seed-provider-parameters seeds=172.17.0.3 --blocked-reactor-notify-ms 999999999"
parsed command line options: [log-to-syslog: 0, log-to-stdout: 1, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 172.17.0.3, rpc-address: 172.17.0.3, seed-provider-parameters: seeds=172.17.0.3, blocked-reactor-notify-ms: 999999999]
terminate called without an active exception
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
Aborting on shard 14.
Backtrace:
  0x0000000002a5de52
  0x0000000002a049cb
  0x0000000002a04cc5
  0x0000000002a04d60
  0x00007fbf63eceb1f
  /opt/scylladb/libreloc/libc.so.6+0x000000000003c624
  /opt/scylladb/libreloc/libc.so.6+0x00000000000258d8
  /opt/scylladb/libreloc/libstdc++.so.6+0x000000000009e6b5
  /opt/scylladb/libreloc/libstdc++.so.6+0x00000000000aa86b
  /opt/scylladb/libreloc/libstdc++.so.6+0x00000000000aa8c6
  0x0000000002df286a
  0x000000000067a472
  0x0000000002a4bac5
  0x0000000002a4f769
  0x00000000029db50d
  /opt/scylladb/libreloc/libpthread.so.0+0x00000000000094e1
  /opt/scylladb/libreloc/libc.so.6+0x0000000000101692
2020-04-23 12:33:54,620 INFO exited: scylla (terminated by SIGABRT (core dumped); not expected)
2020-04-23 12:33:55,622 INFO gave up: scylla entered FATAL state, too many start retries too quickly

**Comment by tzach** [comment]
Wild guess, but this might be related to the (high) number of cores on the server
See https://github.com/scylladb/scylla/issues/5173 for possible solutions (limited the cores number with `--smp` or set `fs.aio-max-nr`)

**Comment by ssdubey** [comment]
Apparantly,  `scylla-jmx` lib was missing in the base system. It can be installed using `sudo apt-get install scylla-jmx`. I found this when I tried to install scylla directly on the machine and this error came up. However still the error was bit misleading. Not sure how I could have arrived to this from the above log :(
