### ISSUE TITLE
Test Scylla with nodejs-driver

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#628]
[datastax nodejs-driver](https://github.com/datastax/nodejs-driver) use CQL so it should work.

**Comment by tzach** [comment]
I tested the examples in 
https://github.com/datastax/nodejs-driver/tree/master/examples

The following works:
- basic
- metadata
- tuple

The following does not work
- tracing (make sense as tracing is not supported yet #206)
- udt (make sense as UDT is not supported yet #426)

**Comment by avikivity** [comment]
Was tested (see https://tamingnoiseblog.wordpress.com/2016/05/13/web-api-with-nodejs-and-scylladb/).

**Comment by rilut** [comment]
Does datastax node.js driver's `client.stream()` works on Scylla?
