### ISSUE TITLE
Alternator: : signed integer overflow

### ISSUE THREAD

**Issue by espindola** [scylladb/scylla#6280]
Running tests in debug fails with:

alternator/executor.cc:2993:79: runtime error: signed integer overflow: 1085102592571150094 * 9 cannot be represented in type 'long int'

The decoded backtrace is attached.
[decoded.txt](https://github.com/scylladb/scylla/files/4531849/decoded.txt)

**Comment by psarna** [comment]
Oh, right, the delta will sometimes exceed `int64_t::max()`... thanks, I'll fix that.

**Comment by nyh** [comment]
Backported to 4.0 (commit e17c237febbd22edf2d7ed7869181bb925cbc5e5), after the buggy code was also backported to 4.0. Earlier versions are not vulnerable.
