### ISSUE TITLE
over-aligned sstable reads due to file buffer tracking

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#6290]
sstable reads are now always 4k aligned even if they could be smaller.

**Comment by avikivity** [comment]
This is because tracking_file_impl doesn't copy the alignment parameters from the underlying file.

**Comment by nyh** [comment]
I remember in the past we verified manually that when possible (e.g., no compression enabled), sstable reads could get as small as 512 bytes. Had we had a regression test that could verify this automatically, this feature could not have regressed. Let's write a regression test for this as part as fixing this issue, please.

**Comment by avikivity** [comment]
It's hard to regression-test this because it depends on the underlying disk.

**Comment by avikivity** [comment]
This is a minor performance bug only, not backporting.
