### ISSUE TITLE
Filtering captures uninitialized/deleted values of certain types

### ISSUE THREAD

**Issue by jul-stas** [scylladb/scylla#6295]
On fresh master, e.g. 7304a795e584f2697f37d0ca78e8428127c8c3d1

Unset values pass some predicates when filtering:
```
cqlsh> CREATE TABLE ks.tbl_int2 (pk int primary key, i1 int, i2 int);
cqlsh> INSERT INTO ks.tbl_int2 (pk, i1) VALUES (0, 0);
cqlsh> SELECT * FROM ks.tbl_int2 WHERE i2 < -999 ALLOW FILTERING;

 pk | i1 | i2
----+----+------
  0 |  0 | null

(1 rows)
```
Sadly, deleted values behave in the same way:
```
cqlsh> INSERT INTO ks.tbl_int2 (pk, i1, i2) VALUES (1, 1, 1);
cqlsh> DELETE i2 from ks.tbl_int2 WHERE pk = 1;
cqlsh> SELECT * FROM ks.tbl_int2 WHERE i2 < -999 ALLOW FILTERING;

 pk | i1 | i2
----+----+------
  1 |  1 | null
  0 |  0 | null

(2 rows)
```
I checked that it happens for all integer types, but other types (like floats or UUIDs) have similar semantics of `compare_visitor` and might be affected as well. Possible solution would be to exclude NULLs from filtering on higher levels.

**Comment by slivne** [comment]
Is this a regression ?

**Comment by haaawk** [comment]
Probably not but worth checking.

**Comment by jul-stas** [comment]
Checked on 3.1.4 and 3.0.0 (randomly chosen versions) - same behavior.

**Comment by jul-stas** [comment]
@dekimir If I change this line:
https://github.com/scylladb/scylla/blob/4c221855a14dd3107efa14bd17b53433595dd1f7/cql3/selection/selection.cc#L458
to:
```
return false;
```
Then this issue is solved. I thought it's wrong because then `SELECT ... WHERE x = NULL ALLOW FILTERING` will always return an empty set. But as you said, it's going to be the desired behavior after your refactor.

My question is: should I do it? Or should we close this task and wait for your refactor?

**Comment by dekimir** [comment]
@jul-stas I presume you mean `regular_restriction_matches = false` rather than `return false`.

I'd wait for now, as my (partial) rewrite is currently in next (b0698df) and should hit master soon.

**Comment by jul-stas** [comment]
@dekimir Yes, my mistake. Thanks, I'll see how it works and close if no action is required.

**Comment by jul-stas** [comment]
@dekimir Since your rewrite already hit `master`, I repeated the test:
```
cqlsh> CREATE TABLE ks.tbl_int (pk int PRIMARY KEY, i int);
cqlsh> INSERT INTO ks.tbl_int (pk) VALUES (0);
cqlsh> SELECT * FROM ks.tbl_int where i < -1 ALLOW FILTERING;

 pk | i
----+------
  0 | null

(1 rows)

cqlsh> SELECT * FROM ks.tbl_int where i = NULL ALLOW FILTERING;  -- just to prove that I used correct version

---MORE---
(0 rows)
```
So no good. Are you planning to do some related work in these areas, or is it time for me to patch it?
If the latter is the case - any advice on where to catch these kinds of NULLs now?

**Comment by dekimir** [comment]
@jul-stas I'd expect you'll need to change [this](https://github.com/scylladb/scylla/blob/29fccd76eaaa0da641b91c8c64bd4957edbe5c9f/cql3/restrictions/statement_restrictions.cc#L810) line to `return false`.  You'll also need to drop `std::nullopt` element from [this](https://github.com/scylladb/scylla/blob/29fccd76eaaa0da641b91c8c64bd4957edbe5c9f/test/boost/restrictions_test.cc#L235) test.

**Comment by dekimir** [comment]
Forgot to add: I'm swamped with other things right now, so I'd appreciate it very much if you could do it. :)

**Comment by jul-stas** [comment]
> Forgot to add: I'm swamped with other things right now, so I'd appreciate it very much if you could do it. :)

Sure, I'm on it already.

**Comment by avikivity** [comment]
This is relatively hard to backport, and a relatively minor bug, so not backporting.
