### ISSUE TITLE
lwt writes are not linearizable

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#6299]
*Installation details*
Scylla version (or git commit hash): 7304a795e584f2697f37d0ca78e8428127c8c3d1

Suppose we have three nodes A, B, C and a write of a value V failed after managed to be accepted on A. Then suppose that a client tries to read the value twice in a row: first read accessed B and C and read nothing second one access A and B notices that V is accepted, replays the write and returns V. So we have two reads with no write in between that  return different value which breaks linearizability.

**Comment by gleb-cloudius** [comment]
Cassandra issue  https://issues.apache.org/jira/browse/CASSANDRA-12126

**Comment by kostja** [comment]
The issue also impacts writes for which CAS condition is not met. Such writes do not update the most recently accepted ballot, and therefore allow an older (in wall clock time) transaction to be accepted after a CAS statement with condition not met was evaluated and was not applied, based on the current state of the database.

**Comment by avikivity** [comment]
@tgrabiec please evaluate for backport

**Comment by tgrabiec** [comment]
It's a high-risk change and the problem has been in Cassandra from the beginning. I'd say we don't backport.
