### ISSUE TITLE
Scylla: does not reclaim disk space when expired via TTL

### ISSUE THREAD

**Issue by edisonqkj** [scylladb/scylla#6308]
*Installation details*
Scylla version: 3.1.2
Cluster size: 3 nodes (1 data center)
OS: CentOS 7.7.1908/7.3.1611/7.3.1611

*Hardware details (for performance issues)*
Platform: cloud instance
Hardware: memory 64GB/32GB/64GB
Disks: SSD 322GB/50GB/200GB

I'm inserting 100 thousands of jpgs, submitted as binary data, into the blob field in scylla. the size of each jpg file is about 120KB. During the insert processing, the compaction is doing normally. 
![image](https://user-images.githubusercontent.com/5396193/80479870-4c796780-8982-11ea-941d-2403a0745b11.png)

As one node's disk space is only 50GB, i want to expire the old jpgs to reclaim disk space. While i set the TTL for each row with '**Using TTL 1000**' in insert statement, the rows are still there after it should be expired. 

CQL result is shown as following:
z=1, the result is right
z=2, 8 rows are returned (16 totally inserted)
![image](https://user-images.githubusercontent.com/5396193/80479741-1340f780-8982-11ea-94da-e3e77cfc3db0.png)

Table **tbl3**:
CREATE TABLE tile.tbl3 (
    z int,
    x int,
    y int,
    img blob,
    PRIMARY KEY (z, x, y)
) WITH CLUSTERING ORDER BY (x ASC, y ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND **default_time_to_live = 1000**
    AND **gc_grace_seconds = 0**
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

**Question A**:
when the sstables are compacted before the rows are expired via TTL(1000), does TTL still work? is this a bug?
i checked this: https://stackoverflow.com/questions/60246041/snapshot-will-keep-data-against-ttl-expired-or-ttl-expired-table-in-cassandra
> when Scylla decides to **compact** the sstable containing the expired data, does it actually **remove this old data** from disk (and, sometimes, needs to replace it by a deletion marker, a tombstone - the details of this aren't relevant to your question).

**Question B**
in my case, how can i reclaim the disk space efficiently?

thanks.

**Comment by tzach** [comment]
@tgrabiec could this be related to https://github.com/scylladb/scylla/issues/4855 ?

**Comment by raphaelsc** [comment]
@edisonqkj Yes. TTL is propagated through compaction, that information is never lost. The problem is that you're using STCS (size tiered compaction), you should probably switch to TWCS. See: https://docs.scylladb.com/getting-started/compaction/

STCS is known to mixing old and new data, preventing SSTables from being fully expired. Also, I'd recommend you to play with tombstone compaction properties that will help you getting rid of SSTables that are partially expired.

**Comment by raphaelsc** [comment]
@edisonqkj Do you use explicit deletes or only rely on TTL for eventual deletion?

**Comment by tgrabiec** [comment]
> @tgrabiec could this be related to #4855 ?

I don't see how.

**Comment by edisonqkj** [comment]
> @edisonqkj Do you use explicit deletes or only rely on TTL for eventual deletion?

only TTL, i didn't use any deletes. the CQL results are acquired after 1000s.

**Comment by slivne** [comment]
@edisonqkj 

- Your table has ```default_time_to_live = 1000, gc_grace_seconds=0```, was this set prior to any insert or after some inserts have been done ?
  - If this was set after there were some inserts those inserts will use the old value (given you did not specify ```using ttl```)
  - This setting are only applicable for inserts done after default_time_to_live, gc_grace_seconds were set.

So,
- If your query returns old inserted data - that measn that it was not inserted with using TTL nor did the default setting on the table apply. you can check that in a query using `select ttl(<column>)`
- If you still want to check why some data is not cleared - you can run nodetool sstabledump and get the raw data from the sstables. 

raphaelsc also provided you some items you can check.

If there is anything else we can help with please let us know

**Comment by slivne** [comment]
@edisonqkj closing this as the issue is stale - If there is additional info please post and we work with you to resolve this
