### ISSUE TITLE
Reactor stalls in memory reclaim path

### ISSUE THREAD

**Issue by gjaldon** [scylladb/scylla#6317]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.1.2-0.20191127.9d78d848e
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 9

*Hardware details (for performance issues)* 
Platform (physical/VM/cloud instance type/docker): Google Compute Engine VM
Hardware: n2-custom (24 vCPUs, 192 GB memory)
Disks: (SSD/HDD, count)
1 500GB SSD for commitlog
1 6000GB SSD for scylla data

The issue:
I’m seeing reactor stalls of 5-10 seconds which look like they are caused by writing large cells. Right before the stall, was seeing a lot of writing large cell warnings on shard 10 in the logs and then compactions. I get 2 reactor stalls which have the same backtrace of:
```
  0x00000000041df5e2
  0x00000000040cc8f5
  0x00000000040cce35
  0x00000000040cd177
  0x00007fe3c561702f
  0x0000000000edbfd6
  0x0000000000d8b4c4
  0x0000000000ec7127
  0x0000000000eb6f57
  0x0000000000ebc1a9
  0x000000000407d368
  0x000000000407dc0e
  0x000000000408151d
  0x00000000014fa1b7
  0x0000000001523d9e
  0x00000000015271ba
  0x0000000001529fb1
  0x000000000152b7c8
  0x00000000040c9dc1
  0x00000000040c9fde
  0x00000000041abd6d
  0x00000000041d63db
  0x000000000409809d
```

Here’s a gist that shows the resolved backtrace and some lines from the logs:
https://gist.github.com/gjaldon/3ea59661fa4c89eac0c46245c7c28776

Notes:
@bdenes on ScyllaDB-Users slack had this to say about the issue:
> This stall is not caused by large cells, at least not directly. The stall happens in the memory reclaim path. Scylla is under memory pressure and is trying to reclaim memory by compacting its long-term memory storage space (where cache and memtables reside).

**Comment by glommer** [comment]
and @xemul since he is rewriting the cache.

**Comment by denesb** [comment]
This issue is not cache specific, rather LSA specific. I think LSA, when reclaiming, should spend at most a task quota worth of time on compacting. This will mean that we'd fail allocations that could be satisfied with some more work. This could be solved if allocations returned a future.

**Comment by glommer** [comment]
It's going to be really hard for allocations to return a future. However maybe we can do futurized reservations? It's essentially the same thing

**Comment by denesb** [comment]
What kind of reservations are you thinking about? We do LSA compaction when there is no free memory to satisfy the allocation from. Maybe we also do idle compaction, but I'm not sure.

**Comment by glommer** [comment]
Akin to STL's `.reserve()`. We can then use something akin to placement new to put the LSA structures into the memory we just reserved.

LSA is very different so the syntax and usage will not be exactly the same, but conceptually I think it should work.

**Comment by tgrabiec** [comment]
debug-level LSA logging during the stalls could sched more light:

```
curl -X POST http://localhost:10000/system/logger/lsa?level=debug
curl -X POST http://localhost:10000/system/logger/lsa-timing?level=debug
```

Refs https://github.com/scylladb/scylla/issues/4186

**Comment by slivne** [comment]
@gjaldon ping can you please follow tgabriec request https://github.com/scylladb/scylla/issues/6317#issuecomment-621446124 and provide the additional info so we can try and resolve this

**Comment by gjaldon** [comment]
@tgrabiec ok just set the LSA logging to debug-level. Will update you when I get new logs for these reactor stalls

**Comment by avikivity** [comment]
We should have a background task to reclaim memory from lsa when it falls from below a certain level, so most allocations have the reclaim work already done.

LSA itself should not benefit from this reserve, as it would just eat it all up immediately. e.g. lsa shoud self-reclaim until it is above the reserve.

**Comment by gjaldon** [comment]
@tgrabiec @slivne I no longer see that issue in our logs. We retain logs for 2 weeks. It looks this issue has been resolved on our end for some weeks now. We changed the data model for some tables which emitted some large cell warnings. Had cells up to 20MB in size. This might have been related somehow?

**Comment by avikivity** [comment]
Certainly a 20MB cell will cause these stalls. The problem is that in order to allocate these 20MB cells our allocator has to evict other cells from cache. If the cells on the tail end of the LRU happen to be small, then we'll need to evict a large number of them to make room, and this causes the stall.

**Comment by avikivity** [comment]
Closing this as the immediate problem appears resolved (although we still have to improve reclaim when large allocations are present)
