### ISSUE TITLE
Taking snapshot timeouts for a single node

### ISSUE THREAD

**Issue by ajankovic** [scylladb/scylla#6324]
*Installation details*
Scylla Enterprise 2019.1.7-0.20200328.c8f0d16d2
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Scylla Cloud

Hardware details (for performance issues)
I3.XLARGE

*Cluster setup:*

Each node in the cluster is populated with ~475GiB distributed across one keyspace containing ~5K of tables. Tables are created mostly with:

```
CREATE TABLE IF NOT EXISTS data_%d (id uuid PRIMARY KEY, data blob) WITH compaction = {'class': 'LeveledCompactionStrategy', 'sstable_size_in_mb' : 500}
```

Keyspace:

```
CREATE KEYSPACE test_keyspace WITH replication = {'class' : 'SimpleStrategy','replication_factor' : 3};
```

But there are some tables with `'sstable_size_in_mb' : 20` and `'sstable_size_in_mb' : 10` along with some tables with default compaction strategy. This results in hundreds of thousands of files.

*Issue*

When snapshot is requested with POST to `/storage_service/snapshots?kn=test_keyspace&tag=sm_20200428172538UTC` response is not received after total waiting time of 7m30s.

Subsequently in the next operation on the same node when GET is sent to `/storage_service/snapshots` to list all available snapshots same node timeouts even after 6h of waiting.

Timeouts are only happening on the same node in the three node cluster.

Before taking snapshot, keyspaces are flushed with POST to `/storage_service/keyspace_flush/{keyspace}`

Everything returns to normal after nodes are restarted.

Logs from all nodes in the cluster are available upon request.

**Comment by slivne** [comment]
@ajankovic can you please upload the logs https://docs.scylladb.com/troubleshooting/report_scylla_problem/#send-files-to-scylladb-support

**Comment by slivne** [comment]
closing this - if it happens again please provide logs
