### ISSUE TITLE
set gc period to 0 at least for system.large* tables (ideally for all local tables)

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla#6325]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

**Comment by denesb** [comment]
I think we can do this for all *local* system tables, not just the `large_*` ones.

**Comment by tarzanek** [comment]
fix schemas in https://github.com/scylladb/scylla/blob/master/db/system_keyspace.cc#L473
at least for large*

**Comment by tarzanek** [comment]
set at least
    AND gc_grace_seconds = 864000

a question is if it doesn't make sense to also TTL some of the tables (or how do we take care of cleaning old records?)
    AND default_time_to_live = 0

**Comment by tarzanek** [comment]
also dclocal_read_repair_chance = 0.1 doesn't make much sense in those tables

**Comment by avikivity** [comment]
@tarzanek please detail the negative effects here, so I can evaluate for a backport. "
set gc period to 0 at least for system.large* tables (ideally for all local tables)
#6325" tells me nothing about what the impact on the user is.

Bugs should explain what the problem is; this one just describes the solution.

**Comment by tarzanek** [comment]
The problem description in object defect format:
Observability/traceability of scylla is not working.
Customer is not able to display/list large partitions table, since it takes more than 5mins to display the empty list in them on a very powerful box.
(Customer cleaned up his big partitions, compactions deleted older findings, but their tombstones just made showing the table a nightmare)

**Comment by avikivity** [comment]
Ok, I'll backport it. Please update the description to aid the release notes preparation.

**Comment by avikivity** [comment]
Backported to 4.0.
