### ISSUE TITLE
ENOENT when resharding deletes SSTables being used by a parallel operation like snapshot

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6328]
*Installation details*
Scylla version (or git commit hash): 1f902302a
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Resharding deletes input SSTables in the coordinator shard, so it's important to only remove them from the SSTable sets of the shards they belong to, after acquiring a deletion semaphore.

**Comment by avikivity** [comment]
This issue says very little about the problem, it just outlines a solution.

What problem is solved?

**Comment by raphaelsc** [comment]
@avikivity Sorry. Going to change the description, but it's basically about ENOENT when a operation, which iterates through the SSTable set, runs in parallel to resharding.

**Comment by bhalevy** [comment]
#6439 was caused by the fix for this issue 88d2486fcafc4e0e25d988b4dc9c4022ddf9bd1d

**Comment by raphaelsc** [comment]
> @raphaelsc not sure if I should backport or not, please advise.

This bug could result in snapshot not saving the data being resharded, but if we do backport this patch, we need to backport https://github.com/scylladb/scylla/commit/c06cdcdb3ca410a81929b8aff0c13d67d3c67475 too, like @bhalevy pointed out, because this fix caused #6439.

**Comment by avikivity** [comment]
Not backporting, seems like a rare/minor bug.
