### ISSUE TITLE
lwt: tag metrics for prepared statements executed on behalf of LWT

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#6329]
https://github.com/scylladb/scylla-monitoring/issues/906 complains that LWT skews CQL write metrics, used by clients to track client-side writes.

This happens because LWT internally uses CQL prepared statements to write to system.paxos table. A single LWT statement can lead to any number of writes to system.paxos:
1) 1 if successfully prepared ballot and condition is not met
2) 3 if  any one node is down
3) 4 if all nodes are up
4) any other number in case of re-tries

This makes such writes impossible to separate reliably from client writes, so they need to be tagged accordingly in metrics.

**Comment by gleb-cloudius** [comment]
This is true for every internal user of CQL. There is nothing special
about LWT here and I do not believe it to be an big issue (if at all).
Furthermore I do not see why CQL metrics are singled out here. What
about storage_proxy metrics? Database metrics? If CQL metrics will not
include internal CQL user all those other metrics will not make sens.

--
			Gleb.

**Comment by slivne** [comment]
@amnonh fixed this on the monitoring end - I think the fix is reasonable - we can close this for now in my view

**Comment by slivne** [comment]
closing this issue - I assume all agree

**Comment by kostja** [comment]
@shlomi can we document the fix or reference it from here? I am not sure it is possible to fix reliably on the monitoring end only.
