### ISSUE TITLE
ami: discard 'discard'

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#633]
Re: #632

**Comment by slivne** [comment]
duplicate of #626

**Comment by dorlaor** [comment]
Discard 'discard 'discard''..

**Comment by penberg** [comment]
Isn't this fixed by https://github.com/scylladb/scylla/commit/79e70568d7f05d41b4fa24fcb2217769f6b6ef40?

**Comment by avikivity** [comment]
Fixed by 79e70568d7f05d41b4fa24fcb2217769f6b6ef40.
