### ISSUE TITLE
Integrate Redis tests with test.py

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#6331]
Let's do what Alternator did in commit https://github.com/scylladb/scylla/commit/4e2bf28b8455527237baabe629f01c775fe4e48c, and move the tests to `test/redis` and integrate them with `test.py` so we will run the Redis tests as part of our CI.

**Comment by nyh** [comment]
This can be very easily achieved by copying the short `test/alternator/run` script with only a few lines 
of change (the options needed to enable Alternator will need to change to those enabling redis).

Duplicating this script has the risk that later we'll improve the Alternator `run` script and forget to modify the Redis one too. There's an easy solution: modify `test/alternator/run` to take the Alternator-specific options as an environment variable with the Alternator options being the default, and `test/redis/run` will just run `../alternator/run` overriding this variable.

In issue #6212 I suggested a less hackish long-term solution where we integrate some of the capabilities of `test/alternator/run` (such as creating/deleting a temporary directory, and starting Scylla) into `test.py`.

**Comment by avikivity** [comment]
Not a bug, not backporting.
