### ISSUE TITLE
lwt: assertion in boost::dynamic_bitset on execution of multi partition LWT batch.

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylla#6332]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.0.rc2
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

Trying to make following CQL and instead of syntax error got assertion:

```
CREATE TABLE transactions (
  id UUID,
  src_bic TEXT,
  src_ban TEXT,
  dst_bic TEXT,
  dst_ban TEXT,
  amount DECIMAL,
  status TEXT,
  PRIMARY KEY (id)
);

CREATE TABLE transactions_in_progress (
  id UUID,
  PRIMARY KEY (id)
);

BEGIN BATCH
  INSERT INTO transactions (id, src_bic, src_ban, dst_bic, dst_ban, amount, status)
    VALUES ({transaction_uuid}, '1', '1', '1', '2', 100, 'in progress') IF NOT EXISTS
  INSERT INTO transactions_in_progress (id) VALUES ({transaction_uuid}) IF NOT EXISTS
APPLY BATCH
```

Assertion:

```
scylla: /usr/include/boost/dynamic_bitset/dynamic_bitset.hpp:868: boost::dynamic_bitset<Block, Allocator>& boost::dynamic_bitset<Block, Allocator>::operator|=(const boost::dynamic_bitset<Block, Allocator>&) [with Block = long unsigned int; Allocator = std::allocator<long unsigned int>]: Assertion `size() == rhs.size()' failed.
```

**Comment by bentsi** [comment]
@kostja are you aware of this?

**Comment by kostja** [comment]
Well, Evgeniy mentioned earlier he hit a crash, I wasn't aware of the specifics. Will take a look.

**Comment by avikivity** [comment]
@tgrabiec please evaluate for backport

**Comment by tgrabiec** [comment]
Seems safe for backporting. 

Could bring a cluster down when hit, so we probably should backport.

**Comment by avikivity** [comment]
Backported to 4.0, 4.1.
