### ISSUE TITLE
Support mutli-table in take snapshot

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#6333]
The take-spanshot command takes multiple keyspaces it would be helpful to support multiple tables as well.

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please consider backport to 4.1 and 4.0 (it's already in 4.2)
and from there to the enterprise release(s)

**Comment by avikivity** [comment]
It looks like a feature, certainly not a regression or critical bug fix.

Enterprise should be discussed in its own repository.
