### ISSUE TITLE
Alternator: improve error message on creation of an already-existing table

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#6340]
If we try to create an already existing table, e.g., by running twice a table-creation command such as
```
aws --endpoint-url 'http://172.17.0.1:8000' dynamodb create-table --table-name mytab --attribute-definitions AttributeName=key,AttributeType=S --key-schema AttributeName=key,KeyType=HASH --billing-mode PAY_PER_REQUEST
```
We get an error message saying:
> An error occurred (ResourceInUseException) when calling the CreateTable operation: Keyspace for table mytab already exists

The error message should say that the table already exists (even if what we technically tried to do was to create a keyspace for it), because the DynamoDB API does not have a concept of keyspaces, so error messages shouldn't mention this concept (except in the case of unexpected internal errors, which can mention internal implementation details).

**Comment by psarna** [comment]
It can theoretically create a confusing error, if an old keyspace with identical name we automatically created somehow still exists, and now the user tries to create a table with the same name - the error would say that the table already exists, but DescribeTable will insist that it doesn't :) But I guess that this error is rare, and mentioning "keyspaces" in an environment that doesn't know what a keyspace is, is even more confusing. I'll send a patch.

**Comment by nyh** [comment]
> It can theoretically create a confusing error, if an old keyspace with identical name we automatically created somehow still exists, and now the user tries to create a table with the same name - the error would say that the table already exists, but DescribeTable will insist that it doesn't :)

This is true. The safest thing we could do is, if keyspace creation failed because it already exists, we could proceed to try to create the table (and likely fail that too). This will slow down the already-exists case, but will ensure the possibility you described won't happen.

**Comment by psarna** [comment]
I'd prefer to leave this fix as. The reason is that when we end up in a situation that an arbitrary keyspace X exists, but its table X doesn't, we probably don't want the `CreateTable X` request to succeed - we'd have no control over the replication strategy, since it will use the old one, whatever it was. In this case I think it's better to just fail the creation and wait for the support team to fix the inconsistency via CQL.

**Comment by nyh** [comment]
But the only reason for this situation to happen (except if someone maliciously used CQL :-)) is for the non-atomic creation to half-succeed - maybe creating a keyspace failed and then the node crashed or something happened and the create table failed. If this happens, the cluster becomes unusable.
If we want to be really pedantic we can check if the keyspace that already exists has the right properties. But maybe we shouldn't be that pedantic - it can even be used as a hack to pre-create (with CQL) a keyspace with weird properties, deliberately?

**Comment by psarna** [comment]
Hm, true, it could be useful to be able to do this hack. I'll create another patch which ignores the fact that a keyspace already exists and continues to try to create a table.

**Comment by nyh** [comment]
Not backporting, this is an error-message improvement but doesn't fix a bug in any error-free path.
