### ISSUE TITLE
system.local can still be used to store truncation records sometimes.

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#6341]
*Installation details*
Scylla version (or git commit hash): eac9e253e7e40e6266de67d22e3ad3a707191768

A node starts with 'need_legacy_truncation_records' set to true and only after `cluster_supports_truncation_table` feature is resolved it is reset to false and legacy records are no longer saved. But between those two events any truncate attempt will be saved in system.local.
 
One such case is `drop_legacy_tables()` which is called before `cluster_supports_truncation_table` is resolved. 

Another happens because of messaging service is also enabled before  `cluster_supports_truncation_table` is resolved meaning that any truncation request coming from RPC during this window will also be recorded in system.local. Such request may arrive if a truncation coordinator did not notice that the node reboots which may happen during crash.

**Comment by slivne** [comment]
Truncation was added prior to 4.0 - which means that all releases of open source have this supported and there is no mix cluster mode. Can we move and make the code always write to the truncation table (as if the feature is set). ?

@elcallio / @avikivity  ?

**Comment by avikivity** [comment]
We have many such cases. This is due to a window we have during boot before we recognize the other nodes' features. We need to compute those features earlier (and I see we store supported_features in the peers table).

**Comment by elcallio** [comment]
Is it true for live enterprise releases as well, that we don't have any live with legacy truncation records? Removing the feature dependency would indeed be nice.

**Comment by slivne** [comment]
@avikivity - the comment is correct - yet we need also to make sure that we did not do a rollback. In any case this is handled by a different design tomek created - I do not think we need to couple the general issue with this specific one.

Like in the KA/LA case - we can now move and assume all clusters will support this feature and we will not have an open source upgrade that will require to write in a mixed cluster state.

**Comment by avikivity** [comment]
@slivne what is "the change"?

**Comment by slivne** [comment]
@avikivity not wait for the general change of feature bits and always get back the feature is supported and that will force writing truncate records unconditionally to system truncate table
