### ISSUE TITLE
Support for Ubuntu 20.04

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#6343]
*Installation details*
Scylla version (or git commit hash): 4.0

Ubuntu 20.04 LTS (Focal Fossa) is now available https://releases.ubuntu.com/20.04/

**Comment by syuu1228** [comment]
I only able to find this issue installing scylla on Ubuntu 20.04LTS, at this point:
https://github.com/scylladb/scylla/issues/6673

Everything else looks fine.

**Comment by batara666** [comment]
How this going my friend

**Comment by amoskong** [comment]
> How this going my friend

Quote from https://groups.google.com/g/scylladb-users/c/aztsVnGtz3A

```
[RELEASE] Scylla 4.3 Release Candidate 3 (RC3)

Ubuntu 20 will *not* be part of Scylla 4.3, it was pushed for a the next release
```

I think Scylla-master works well on Ubuntu 20.

/Cc @tzach

**Comment by tzach** [comment]
@penberg AFAIK this is part of master.
Can we close?

**Comment by slivne** [comment]
Yes we can and we did try to push it into 4.3 at the end - we can announce it with 4.3.1
