### ISSUE TITLE
cdc: repair causes TimeoutException and Semaphore timed out, then health check query failed

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#6349]
*Installation details*
Scylla version (or git commit hash): 4.0.rc2-0.20200427.602ed43ac7a
Cluster size: 6 db nodes
Db instance type: i3.4xlarge
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0fcdfef1a8f37ec6d (eu-west-1)

### Description

A general 'nodetool repair' caused the `Semaphore timed out: smp_service_group`.
Just execute 'nodetool repair' on a db node.

At the end of NoCorruptRepair nemesis, a series of 'seastar::named_semaphore_timed_out (Semaphore timed out: smp_service_group#2 10->12 semaphore)' raised. Repair finally finished successfully, but the schema check query failed, the query was executed on target node (db-node-1bb14a1e-4)

```
CMD: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "select peer, data_center, host_id, rack, release_version, rpc_address, schema_version, supported_features from system.peers" 10.0.198.22 9042'

Exit code: 1

Stderr: Connection error: ('Unable to connect to any servers', {'10.0.198.22': ReadTimeout('Error from server: code=1200 [Coordinator node timed out waiting for replica nodes\' responses] message="Operation timed out for system.peers - received only 0 responses from 1 CL=ONE." info={\'received_responses\': 0, \'required_responses\': 1, \'consistency\': \'ONE\'}',)})
```

The repair was executed on db-node-4 (10.0.198.22), the health check query was also executed on the node.

#### Yulia comment

The checking failed on one node, node4 that was the target node of no-corrupt-repair nemesis. There are a lot ot TimeoutException from storage_proxy at the same time. Cassandra-stress also is not able to connect with this node. I checked the node log - compaction runs at the same time and also there are timeouts.
When the health checker runs next time (mgmt_repair_cli), the connection problem still exists. 
But when the checker was run before next the nemesis (snapshot_operations) , it already succeeded and the node started responding.

When the health checker runs, it can't know what is the reason, why the node doesn't respond. 
I think this failure should be ignored (suppressed) by the code

### Test log:
Job: https://jenkins.scylladb.com/job/scylla-4.0/job/longevity/job/longevity-cdc-100gb-4h/15/
test id: 1bb14a1e-150f-4c0d-a6bb-6574cd025a39
test log: https://cloudius-jenkins-test.s3.amazonaws.com/1bb14a1e-150f-4c0d-a6bb-6574cd025a39/20200427_173551/sct-runner-1bb14a1e.zip
db log: https://cloudius-jenkins-test.s3.amazonaws.com/1bb14a1e-150f-4c0d-a6bb-6574cd025a39/20200427_173551/db-cluster-1bb14a1e.zip

### Nemesis:

```
2020-04-27 13:14:48,903 >>>>>>>>>>>>>Started random_disrupt_method no_corrupt_repair
2020-04-27 13:31:01,727 <<<<<<<<<<<<<Finished random_disrupt_method no_corrupt_repair

<Health check query failed>
< t:2020-04-27 13:31:38,383 INFO  > Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "select
peer, data_center, host_id, rack, release_version, rpc_address, schema_version, supported_features from system.peers" 10.0.198.22 9042'
< t:2020-04-27 13:31:38,383 INFO  > Connection error: ('Unable to connect to any servers', {'10.0.198.22': ReadTimeout('
Error from server: code=1200 [Coordinator node timed out waiting for replica nodes\' responses] message="Operation timed out for system.peers - received only 0 responses
from 1 CL=ONE." info={\'received_responses\': 0, \'required_responses\': 1, \'consistency\': \'ONE\'}',)})

2020-04-27 13:37:25,589 >>>>>>>>>>>>>Started random_disrupt_method mgmt_repair_cli
2020-04-27 13:39:03,796 >>>>>>>>>>>>>Started random_disrupt_method major_compaction
2020-04-27 14:21:06,775 <<<<<<<<<<<<<Finished random_disrupt_method major_compaction
2020-04-27 14:29:06,259 >>>>>>>>>>>>>Started random_disrupt_method snapshot_operations
2020-04-27 14:30:14,602 <<<<<<<<<<<<<Finished random_disrupt_method snapshot_operations
2020-04-27 14:38:10,619 >>>>>>>>>>>>>Started random_disrupt_method network_random_interruptions
2020-04-27 14:41:10,241 >>>>>>>>>>>>>Started random_disrupt_method nodetool_decommission
```

**Comment by amoskong** [comment]
### CDC:

cdc is enabled in this job.
used 4 workloads to cover both true and false of preimage and postimage.

### SCT config:

https://github.com/scylladb/scylla-cluster-tests/blob/branch-4.0/test-cases/longevity/longevity-cdc-100gb-4h.yaml

### Workloads:
stress_cmd: [ "cassandra-stress user no-warmup profile=/tmp/cdc_profile.yaml ops'(insert=2,read1=1,update_number=1,update_name=1,delete1=1)' cl=QUORUM duration=240m -port jmx=6868 -mode cql3 native -rate threads=100",
              "cassandra-stress user no-warmup profile=/tmp/cdc_profile_preimage.yaml ops'(insert=2,read1=1,update_number=1,update_name=1,delete1=1)' cl=QUORUM duration=240m -port jmx=6868 -mode cql3 native -rate threads=100",
              "cassandra-stress user no-warmup profile=/tmp/cdc_profile_postimage.yaml ops'(insert=2,read1=1,update_number=1,update_name=1,delete1=1)' cl=QUORUM duration=240m -port jmx=6868 -mode cql3 native -rate threads=100",
              "cassandra-stress user no-warmup profile=/tmp/cdc_profile_preimage_postimage.yaml ops'(insert=2,read1=1,update_number=1,update_name=1,delete1=1)' cl=QUORUM duration=240m -port jmx=6868 -mode cql3 native -rate threads=100"
             ]

#### C-s profiles:
- https://github.com/scylladb/scylla-cluster-tests/tree/branch-4.0/data_dir/cdc_profile.yaml
- https://github.com/scylladb/scylla-cluster-tests/tree/branch-4.0/data_dir/cdc_profile_postimage.yaml
- https://github.com/scylladb/scylla-cluster-tests/tree/branch-4.0/data_dir/cdc_profile_preimage.yaml
- https://github.com/scylladb/scylla-cluster-tests/tree/branch-4.0/data_dir/cdc_profile_preimage_postimage.yaml

**Comment by slivne** [comment]
We have changed the code a lot around parallelism and resource allocation - please retest on master / 4.3 and report - if this doesn't reoccur we will close

**Comment by amoskong** [comment]
> We have changed the code a lot around parallelism and resource allocation - please retest on master / 4.3 and report - if this doesn't reoccur we will close

I checked recent jobs in https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h-test/
They are not stable, some failed for known scylla issue. Let me work with @aleksbykov to make the job stable first, then retest if the TimeoutException & Semphore timeout occur during repair.

BTW, I didn't see TimeoutException & Semphore timeout in recent jobs, which didn't run too much time.

**Comment by amoskong** [comment]
Decommission failed in latest longevity-cdc-4h:

- job: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h-test/106/console
- test id: dc06a2a7-a264-448f-9112-55b1556efe1b
- db log: https://cloudius-jenkins-test.s3.amazonaws.com/dc06a2a7-a264-448f-9112-55b1556efe1b/20200919_130908/db-cluster-dc06a2a7.zip
- repair based ops

```
2020-09-19 12:40:52.648: (DisruptionEvent Severity.ERROR): type=end name=Decommission node=Node longevity-cdc-100gb-4h-master-db-node-dc06a2a7-5 [13.49.74.248 | 10.0.2.180] (seed: False) duration=737 error=Encountered a bad command exit code!
Command: 'nodetool  decommission '
Exit code: 1
Stdout:
Using /etc/scylla/scylla.yaml as the config file
nodetool: Scylla API server HTTP POST to URL '/storage_service/decommission' failed: std::runtime_error ({shard 0: std::runtime_error (Failed to repair for keyspace=cdc_test, cf=test_table_scylla_cdc_log, range=(6480522232142308994, 6485177755424644336]), shard 1: seastar::rpc::closed_error (connection is closed), shard 2: std::runtime_error (Failed to repair for keyspace=cdc_test, cf=test_table_postimage, range=(3240737431671722330, 3260390885516189155]), shard 3: seastar::rpc::closed_error (connection is closed), shard 4: std::runtime_error (Failed to repair for keyspace=cdc_test, cf=test_table_preimage_postimage_scylla_cdc_log, range=(3231670850116136613, 3239240827868440335]), shard 5: std::runtime_error (Failed to repair for keyspace=cdc_test, cf=test_table_postimage, range=(1914476493232653953, 1941330900499047821]), shard 6: seastar::rpc::closed_error (connection is closed), shard 7: seastar::rpc::closed_error (connection is closed), shard 8: std::runtime_error (Failed to repair for keyspace=cdc_test, cf=test_table_preimage_postimage_scylla_cdc_log, range=(3516472647975501943, 3579701400737024579]), shard 9: seastar::rpc::closed_error (connection is closed), shard 10: seastar::rpc::closed_error (connection is closed), shard 11: seastar::rpc::closed_error (connection is closed), shard 12: std::runtime_error (Failed to repair for keyspace=cdc_test, cf=test_table_postimage, range=(3931832453148153231, 3959036512143320459]), shard 13: seastar::rpc::closed_error (connection is closed)})
See 'nodetool help' or 'nodetool help <command>'.
```

**Comment by amoskong** [comment]
The repair still has problem:

- job: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-cdc-100gb-4h-test/105/
- test id: 106b2e13-9250-4a31-973b-c987de6f9a09
- CorruptThenRepair nemesis failed

```
Command: 'nodetool  repair '
Exit code: 2
Stdout:
Using /etc/scylla/scylla.yaml as the config file
[2020-09-19 09:54:54,897] Starting repair command #1, repairing 1 ranges for keyspace cdc_test (parallelism=SEQUENTIAL, full=true)
[2020-09-19 10:46:04,528] Repair session 1 failed
[2020-09-19 10:46:04,529] Repair session 1 finished
Stderr:
error: Repair job has failed with the error message: [2020-09-19 10:46:04,528] Repair session 1 failed
-- StackTrace --
java.lang.RuntimeException: Repair job has failed with the error message: [2020-09-19 10:46:04,528] Repair session 1 failed
at org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)
at org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)
at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:583)
at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:533)
at com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:452)
at com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor$1.run(ClientNotifForwarder.java:108)
```

**Comment by slivne** [comment]
@amoskong which version is this - is this on 4.3 or master (4.4-dev)

**Comment by amoskong** [comment]
> @amoskong which version is this - is this on 4.3 or master (4.4-dev)

The last test used 666.development-0.20200917.9650b8d4b, which is pre-4.3

**Comment by slivne** [comment]
CDC repair is related to TWCS repair - we had multiple fixes (and still some comming in related to TWCS - lets wait for them and then rerun) 

Closing this as we have multiple issues tracking this https://github.com/scylladb/scylla/issues/6054 - we will be running tests on CDC (and TWCS by inference to fix all of these) - closing this specific one.
