### ISSUE TITLE
Error when replacing node: Startup failed: std::runtime_error (unable to find sufficient sources for streaming range ...

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6351]
Seen in multiple dtests at scylla version e44b2826abba0d1c6ae91b7d40f0af112a24517d
I suspect it could be caused by d78fbf7c1677a6d30d9f4c24796147c45b582871
With or without relationship to b8ac10c4514d2ff099a288dfa3cb6f938b42d582

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/471/artifact/logs-release.2/1588467306499_counter_tests.TestCountersOnMultipleNodes.counter_consistency_node_replace_test/node4.log
```
ERROR 2020-05-03 00:54:56,295 [shard 0] init - Startup failed: std::runtime_error (unable to find sufficient sources for streaming range (9166892199407561264, +inf) in keyspace system_auth)
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/471/artifact/logs-release.2/1588473761239_replace_address_test.TestReplaceAddress.replace_node_no_hibernate_state_test/node4.log
```
ERROR 2020-05-03 02:42:41,124 [shard 0] init - Startup failed: std::runtime_error (Cannot replace token 3444658265712363823 which does not exist!)
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/471/artifact/logs-release.2/1588473890707_replace_address_test.TestReplaceAddress.replace_shutdown_node_test/node4.log
```
ERROR 2020-05-03 02:44:50,626 [shard 0] init - Startup failed: std::runtime_error (unable to find sufficient sources for streaming range (-8679473293557364538, -8617587428664198610] in keyspace system_auth)
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/471/artifact/logs-release.2/1588479514271_update_cluster_layout_tests.TestUpdateClusterLayout.verify_latest_copy_replace_node_test/node4.log
```
ERROR 2020-05-03 04:18:33,992 [shard 0] init - Startup failed: std::runtime_error (unable to find sufficient sources for streaming range (9184757305069671073, +inf) in keyspace system_auth)
```

**Comment by bhalevy** [comment]
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/471/artifact/logs-release.2/1588474220631_replace_address_test.TestReplaceAddress.replace_first_boot_test/node4.log has a slightly different failure signature but it could be related.

node4 is started to replace node3 using `"-Dcassandra.replace_address_first_boot="+self.cluster.get_node_ip(3)`
but it seems like it is trying to stream data from it:

```
WARN  2020-05-03 02:42:59,473 [shard 0] stream_session - [Stream #cd1c0100-8ce7-11ea-8bf3-000000000000] Streaming plan for Bootstrap-system_auth-index-0 failed, peers={127.0.14.3}, tx=0 KiB, 0.00 KiB/s, rx=0 KiB, 0.00 KiB/s
WARN  2020-05-03 02:42:59,473 [shard 0] range_streamer - Bootstrap with 127.0.14.3 for keyspace=system_auth failed, took 0.01 seconds: streaming::stream_exception (Stream failed)
WARN  2020-05-03 02:42:59,473 [shard 0] range_streamer - Bootstrap failed, took 0 seconds, nr_ranges_remaining=2325
WARN  2020-05-03 02:42:59,473 [shard 0] range_streamer - Bootstrap failed to stream. Will retry in 60 seconds ...

and on...
```

**Comment by slivne** [comment]
@asias this started failing after the series for replacing node take writes

**Comment by asias** [comment]
It is a known issue which is described below.  In short, with a keyspace with rf =1, the old stream plan based node operations can not find a source to stream data and decides to fail the operation. Repair based node operations does not have this issue, it ignores ranges that have zero neighbours. 
We hit this issue when "repair based ops" is not enabled by default. 
We have more work to make "stream plan based ops" to work with rf = 1. 

```
commit cdcedad2abef5637263e5f862b4408579662e43e
Author: Asias He <asias@scylladb.com>
Date:   Wed Feb 5 16:19:45 2020 +0800

    auth: Increase system_auth from RF 1 to 3
    
    This makes the replace operation to fail like:
    
       [shard 0] init - Startup failed: std::runtime_error (unable to find
       sufficient sources for streaming range (9203926935651910749, +inf) in
       keyspace system_auth)
    
    The reason is the system_auth keyspace has default RF of 1. It is
    impossible to find a source node to stream from for the ranges owned by
    the replaced node.
    
    Before the operation passes, because the replacing node calls
    token_metadata.update_normal_tokens(tokens, ip_of_replacing_node) before
    streaming. We see:
    
       [shard 0] range_streamer - Bootstrap : keyspace system_auth range
       (-9021954492552185543, -9016289150131785593] exists on {127.0.0.6}
    
    Node 127.0.0.6 is the replacing node 127.0.0.5. The source node check in
    range_streamer::get_range_fetch_map will pass if the source is the node
    itself. However, it will not stream from the node itself. So, as a
    result, the system_auth keyspace will not get any data.
    
    After the "Make replacing node take writes" series, the replacing node
    calls token_metadata.update_normal_tokens(tokens, ip_of_replacing_node)
    after the streaming finishes. We see:
    
       [shard 0] range_streamer - Bootstrap : keyspace system_auth range
       (-9049647518073030406, -9048297455405660225] exists on {127.0.0.5}
    
    Since 127.0.0.5 is dead, the source node check fails.
    
    TODO:
    - Handle existing cluster already has system_auth with RF 1.
    - We may need a way to allow replace operation with keyspace with RF 1
      if user allows to lost the data for that keyspace.
```

**Comment by asias** [comment]
Patch is being reviewed.

**Comment by avikivity** [comment]
Backported to 4.1.

**Comment by bhalevy** [comment]
The test test still fails in 4.1: https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/dtest-release/36/artifact/logs-release.2/1592500627759_replace_address_test.TestReplaceAddress.replace_shutdown_node_test/node4.log
```
ERROR 2020-06-18 17:17:07,662 [shard 0] init - Startup failed: std::runtime_error (unable to find sufficient sources for streaming range (-9101054723225309955, -9090611437111734139] in keyspace system_auth)
```

@avikivity I don't see 761f0516f18445095628611920bf0e28864c8413 in 4.1
was it dequeued?

**Comment by bhalevy** [comment]
@avikivity ping. it looks like the backport to 4.1 didn't happen after all.
We need to backport the following patches:
* fa9ee234a0 streaming: Use separate streaming reason for replace operation
* 81f0260816 range_streamer: Handle table of RF 1 in get_range_fetch_map

**Comment by avikivity** [comment]
Yes, it was dequeued due to compilation faiure.

**Comment by avikivity** [comment]
Re-backported.
