### ISSUE TITLE
verify_latest_copy dtests fail with unexpected query results

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6352]
Seen starting https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/470/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/verify_latest_copy_rebuild_node_test/
And in 4.0, starting https://jenkins.scylladb.com/view/scylla-4.0/job/scylla-4.0/job/dtest-release/29/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/verify_latest_copy_rebuild_node_test/

Looks like this was triggered by b8ac10c4514d2ff099a288dfa3cb6f938b42d582
(and 4cf201fc24214ee7279db09d0a83f487b16224bf in branch-4.0)

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/update_cluster_layout_tests.py", line 1685, in verify_latest_copy_rebuild_node_test
    scylla_tools.query_c1c2_concurrent(session, keys=range(0, 500), consistency=ConsistencyLevel.ONE, c1_values=cs, c2_values=cs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/scylla_tools.py", line 152, in query_c1c2_concurrent
    check_c1c2_result_one(result[0], list(result[1]), tolerate_missing, must_be_missing, c1, c2)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/scylla_tools.py", line 123, in check_c1c2_result_one
    assert len(res) == 2 and res[0] == c1_value and res[1] == c2_value, res
AssertionError: Row(c1='0', c2='0')
```

Reproducing this locally shows that the test expects the values to be both '1' but the query returns '0'
I'll send a patch to dtest to improve the assert messages.

**Comment by bhalevy** [comment]
Removing the "showstopper" label and the 4.0 milestone as these tests were written with repair-based node operations in mind (e.g. scylladb/scylla-dtest@58567755a0896f7093ab45137beb2a9ae010dc33) and they won't pass without explicit repair with streaming.  So them failing cannot be considered a regression.

**Comment by slivne** [comment]
4.0 lets disable the tests
main / 4.1 - lets force repair based operations

**Comment by bhalevy** [comment]
after discussing with @slivne offline, we can enable repair-base ops in this test in 4.0 too.
