### ISSUE TITLE
Compression is missing getCompressionRatio method

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#636]
In origin there is a method that report the compression ratio, we should report that value.

**Comment by tzach** [comment]
@amnonh what nodetool operation is affected?

**Comment by eyalgutkind** [comment]
Tested compression rate reporting on a small table, nodetool cfstats provided the ratio, using LZ4 compressor.
Works.

use mykeyspace ;
cqlsh:mykeyspace> DESCRIBE TABLE users 

CREATE TABLE mykeyspace.users (
    id uuid PRIMARY KEY,
    addresses map<text, frozen<address>>,
    direct_reports set<frozen<fullname>>,
    name frozen<fullname>
) WITH bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL","rows_per_partition":"ALL"}'
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

cqlsh:mykeyspace> SELECT count(*) FROM users ;

 count
-------
     2

(1 rows)


Keyspace: mykeyspace
	Read Count: 0
	Read Latency: NaN ms.
	Write Count: 0
	Write Latency: NaN ms.
	Pending Flushes: 0
		Table: users
		SSTable count: 1
		Space used (live): 5242
		Space used (total): 5242
		Space used by snapshots (total): 0
		Off heap memory used (total): 131384
		SSTable Compression Ratio: 0.730189
		Number of keys (estimate): 2
