### ISSUE TITLE
CreateTable/DescribeTable should verify the table is available on all nodes

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#6361]
DynamoDB clients create a table by doing a `CreateTable`, and then waiting in a loop until a `DescribeTable` request reports the table exists. Once the table is reported to exist, the table should be available - on any node to which the client sends a request . @fruch said in https://github.com/scylladb/scylla-dtest/pull/1458 that these operations wait enough time for the table to be available on one node, but not on all nodes - and a later request may complain that the table does not exist.

It's not clear to me how this issue, if it exists (@fruch, can we write a dtest reproducing it?), didn't also happen with CQL. Also with CQL, a user might "CREATE TABLE", wait for it to return, and then send a request for this table _to a different node_, and get an error when this other node doesn't know about this table yet.  

`CreateTable` already waits too much for the table to be actually created (this is issue #5052) so one option is to fix it to **really** wait enough for the table to be available on all nodes, not just on the node creating the CreateTable. Another option is not to touch `CreateTable` (which already waits too much) and fix `DescribeTable` to not find a table which isn't available on all nodes.

**Comment by nyh** [comment]
@fruch adds in the above linked pull request that "the problem in our case, that we were taking nodes down before they go this update, or doing operation on them before the schema synced.".
How does Scylla handle this case also in CQL?
1. If a node comes up from being dead, doesn't it try to sync the schema before serving?
2. If a node was alive but temporarily partitioned from the cluster, does `CREATE TABLE` wait for it or not?

**Comment by fruch** [comment]
the case I've clearly seen it was here:
https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/dtest-byo-parallel/130/testReport/alternator_tests/AlternatorTest/test_dynamo_queries_on_multi_dc/

https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fruch/job/dtest-byo-parallel/130/artifact/logs-release.2.0/1588517521968_alternator_tests.AlternatorTest.test_dynamo_queries_on_multi_dc/

on a multi-dc test case.

I couldn't reproduce it locally, event that I've tried using docker to limit the CPU.
```diff
diff --git a/scripts/run_test.sh b/scripts/run_test.sh
index 48b1191d..6af28808 100755
--- a/scripts/run_test.sh
+++ b/scripts/run_test.sh
@@ -196,6 +196,7 @@ docker_cmd="docker run --detach=true \
     -v ${HOME}/.cassandra:${HOME}/.cassandra \
     ${DOCKER_NETWORK_PARAM} \
     --privileged \
+    --cpuset-cpus 0-1 \
     ${DOCKER_IMAGE} bash -c 'sudo rsyslogd; pip3 install --user -e ${CCM_DIR} ; export PATH=\$PATH:\${HOME}/.local/bin ; cp -a /.ccm/repo* \${HOME}/.ccm/ ; bash -c \"${INSTALL_CASSANDRA}\"; python3 -m nose --nologcapture -v -s $*'"
 echo "Running Docker: $docker_cmd"
 container=$(eval $docker_cmd)
```

and running like this:
```
SCYLLA_EXT_OPTS="--smp 2 --memory 1024M" SCYLLA_VERSION=unstable/master:2020-04-26T20:59:59Z ./scripts/run_test.sh alternator_tests.py
```

**Comment by fruch** [comment]
I don't know regarding the CQL behavior, but if quorum is used in the inserts, even if the table doesn't exist on one node, it should succeed.
in dynamodb we need to get the table first from one specific client, before we do the insert (at least when `DynamoDB.Table` is being used, and `client.get_item()` which take the table as parameter.

**Comment by slivne** [comment]
Cassandra Drivers following a DDL wait for schema agreement as well - https://docs.datastax.com/en/developer/java-driver/3.6/manual/metadata/

**Comment by psarna** [comment]
Given that CreateTable is (or at least should be) a rare operation, the easiest fix would be to make it wait for schema agreement before returning to the client. True, it already waits longer than DynamoDB does, but waiting for schema agreement should be the same order of magnitude as creating an announcing a new table. I'd rather do that than move the waiting to DescribeTable - especially that drivers are expected to poll this value repeatedly after doing DDL changes. I'll create a quick pull request that adds waiting for schema agreement after creating a table, since it will take me only a couple of minutes to code, and we'll see if it looks acceptable.

**Comment by nyh** [comment]
@psarna I have a stupid question: What does "wait for schema agreement" do when one of the nodes is down? Do we know that when a node comes up and it missed a "wait for schema agreement" event, it will pull the new schema before starting to serve requests (via RPC, not just CQL)?

**Comment by psarna** [comment]
I'm pretty sure a node will ensure having schema agreement during startup before enabling client protocols, but I don't have any immediate lines to copy and prove my point. I'll try to refresh my knowledge in this area and find the relevant lines, unless somebody more fluent in schemas has the answer ready - if so, please help :)

**Comment by nyh** [comment]
> I'm pretty sure a node will ensure having schema agreement during startup before enabling client protocols

Note that "before enabling client protocols" is a big can of worms. With Alternator, even if a node isn't answering the Alternator protocol it can be reached when some random node receives a request and decides to send the request (via RPC, not a client protocol!) to this booting node. I suspected (but never proved) that #6359 was something like this - a node being listed on the ring, and accepting RPC requests, before actually being ready. But it's possible I'm completely wrong on that. 

In any case, none of this is a reason not to take your patch. I'll review it. Thanks.

**Comment by nyh** [comment]
Backporting to 4.1. This is not a major bug, but can nevertheless hit users, and even more so - does hit our dtests, so if we'd like to run Alternator dtests against the official release 4.1, we want this patch to be in.
