### ISSUE TITLE
auth: Wrong error code is returned when operation on a non exiting role

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla#6363]
When trying to operate on a non existing role, the error returned from Scylla is 0000 which means server error while the correct error, and the one that is returned also from Cassandra is 2200 which
means invalid request.

**Comment by eliransin** [comment]
Closed by #6356

**Comment by eliransin** [comment]
This issue is eligible for backport to all versions. The main effect of the bug is that Cassandra driver will sometimes behave in an unexpected way like reporting on the mentioned operation - couldn't complete the operation against any host (which wrongfully implies a malfunction in the database)

**Comment by avikivity** [comment]
Backported to 4.0, 3.3. 4.1 already has it.
