### ISSUE TITLE
gmtime() and localtime() are not thread-safe and should not be used

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#6364]
The following time conversion functions:
 - gmtime
 - localtime
 - asctime
 - ctime

are not thread-safe, as they return a pointer to a static global buffer. They all have safer `_r` variants, e.g. `gmtime_r`, and these should be used instead.

Fixes for `gmtime` usage in alternator and clocks-impl are already queued, but there's also an issue with using `localtime` in the gossiper.

**Comment by psarna** [comment]
05ec95134a18bef39039ec715c267770b3326f0f is also related.

**Comment by nyh** [comment]
Backported 05ec95134a18bef39039ec715c267770b3326f0f (the gmtime() fixes) to 4.0. The buggy code did not exist in 3.3.
waiting for the second patch (localtime) to reach master before I can backport it.

**Comment by nyh** [comment]
I was too slow, and 4.0 already aged out. The patch is already in 4.1 (bec95a06051e55f5294944b00709d64175e53a74)
