### ISSUE TITLE
Alternator batch_put_item item with nesting greater then 16 yield ClientError

### ISSUE THREAD

**Issue by Orenef11** [scylladb/scylla#6366]
## Installation details:
Scylla version (or git commit hash): `4.0.rc3-0.20200501.eee4c00e29`
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu (My laptop)

## Summary:
I added the item with method `batch_writer
`and the error I got is` An error occurred (ValidationException
) when calling the BatchWriteItem operation: Max nested level reached: 39`

My code to added new items
`
  with dynamodb_api.resource.Table(name=table_name).batch_writer() as batch:
            for item in items:
                batch.put_item(item)
`
## Logs:
Node logs:[node_logs.log](https://github.com/scylladb/scylla/files/4575357/node_logs.log)

[dict_item.txt](https://github.com/scylladb/scylla/files/4575260/dict_item.txt)

**Comment by psarna** [comment]
Oh, right. Our nested level counter is actually bumped by 2 instead of by 1 on each level. I'll prepare a fix.

**Comment by nyh** [comment]
Please also add a test case that uses a nesting level that we wish to support, and verify that it is really supported (and fails before your patch). Thanks!

**Comment by nyh** [comment]
Already in 4.1. Not backporting anywhere else.
