### ISSUE TITLE
Validate Cassandra cpp-driver with Scylla

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#637]
Validate https://github.com/datastax/cpp-driver with Scylla

**Comment by penberg** [comment]
@tzach Anything specific that needs to be validated? I wrote a small performance tool a while back using the C++ driver and it works fine with Scylla: https://github.com/penberg/cqlperf

**Comment by tzach** [comment]
> @tzach Anything specific that needs to be validated? I wrote a small performance tool a while back > using the C++ driver and it works fine with Scylla: https://github.com/penberg/cqlperf

Cool tool!
Best will be to: 
- include each CQL operation 
- make part of the regression tests
thoughts?

**Comment by dorlaor** [comment]
On Tue, Dec 8, 2015 at 10:09 AM, Tzach Livyatan <notifications@github.com>
wrote:

> @tzach <https://github.com/tzach> Anything specific that needs to be
> validated? I wrote a small performance tool a while back > using the C++
> driver and it works fine with Scylla: https://github.com/penberg/cqlperf
>
> Cool tool!
> Best will be to:
>
>    - include each CQL operation
>    - make part of the regression tests thoughts?
>
>
I wonder how many cql/sec it can do. It can replace the slow
cassandra-stress
in many of our internal tests

**Comment by penberg** [comment]
@dorlaor I haven't done serious comparison but the latency numbers reported by this tool are slightly higher because it doesn't suffer from the coordinated omission problem cassandra-stress does. That's because I'm using the HDR histogram library for tracking the latencies.

**Comment by avikivity** [comment]
cpp-driver is known to work well.
