### ISSUE TITLE
"--start-native-transport" option doesn't work

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#6387]
In commit da3bf20e712e5ae383721e879801a64a5c26a2ed we supposedly enabled
support for Cassandra's "start_native_transport" option which can be set to
0 to run Scylla without listening on the CQL port. This can be useful, for
example, if a user only want the DynamoDB or Redis APIs but not CQL.

Unfortunately, the option was still marked "Unused", so it wasn't really
enabled as a valid command line option: "scylla --start-native-transport 0"
isn't recognized, and "scylla --help" doesn't list this option.

**Comment by avikivity** [comment]
Minor issue, not backporting.

**Comment by avikivity** [comment]
@penberg why is the bot re-adding the label?
