### ISSUE TITLE
Scylla 4.0.0 AMI on i3.xlarge: This EC2 instance is optimized for Scylla

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#6395]
*Installation details*
Scylla version (or git commit hash): 4.0.0 scylla-server-4.0.0-0.20200505.d95aa77b62.x86_64
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ScyllaDB 4.0.0 (ami-044d86315d7819cd7) eu-north-1

After init, I get the following:
```
This EC2 instance is optimized for Scylla.
```

i3.xlarge should be optimized for Scylla AMI.

**Comment by penberg** [comment]
What's the bug, @tzach? This message is coming from the `scylla_ec2_check` script, which, after checking everything, reports that the instance _is_ optimized...

**Comment by tzach** [comment]
Ouch.
Look like I need new glasses.
