### ISSUE TITLE
General snapshot after clean fails

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#640]
When generating a snapshot without a tag, cleans it and generates again the command fail, for what seems to be a combination of the clean snapshot didn't clean everything and the system always generates the same snapshot id.

**Comment by slivne** [comment]
can you please provide the exact sequence of commands to reproduce this or
a test

**Comment by amnonh** [comment]
nodetool snapshot
nodetool clearsnapshot
nodetool snapshot

**Comment by vladzcloudius** [comment]
doesn't reproduce with HEAD 2ba49103850f4d7b0107ab36b9dfcde2b7540743

@slivne, pls., close
