### ISSUE TITLE
incorrect name for coredump mount systemd unit file

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylla#6402]
**Installation details**

Scylla version (or git commit hash): 666.development-20200506.e813778bd1
OS (RHEL/CentOS/Ubuntu/AWS AMI): OEL7.6

**Description**

We have a [failure](https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-oel76/70/) of artifacts test because `scylla_coredump_setup` unable to load coredump mount unit file.

This happen on OEL only due to stricter systemd rules (I think) but anyway it's a requirement from systemd to have unit name matched with `Where=` statement.

```
$ systemd-analyze verify var-lib-systemd-coredump.mount
...
var-lib-systemd-coredump.mount's Where= setting doesn't match unit name. Refusing.
..

$ man systemd.mount
...
       Mount units must be named after the mount point directories they control. 
       Example: the mount point /home/lennart must be configured in a unit file 
       home-lennart.mount. For details about the escaping logic used to convert 
       a file system path to a unit name, see systemd.unit(5). Note that mount 
       units cannot be templated, nor is possible to add multiple names to a 
       mount unit by creating additional symlinks to it.
...
```

This bug introduced by fix for #6300 (#6301) and **we need to rename unit file to `var-lib-scylla-coredump.mount`**

See also https://unix.stackexchange.com/a/345518 for more detailed explanation.

**Comment by roydahan** [comment]
@syuu1228 FYI

**Comment by slivne** [comment]
@syuu1228  OEL is stuck on this

**Comment by amoskong** [comment]
Latest status:  the problem ONLY exists on OEL 
FYI, @roydahan @bentsi @syuu1228 


- scylla-master:  https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-oel76-test/100/
- scylla-4.1: https://jenkins.scylladb.com/job/scylla-4.1/job/artifacts/job/artifacts-oel76/19

**Comment by amoskong** [comment]
This was introduced by https://github.com/scylladb/scylla/commit/e77dad3adf7051a489223bbd55ecbc461b377421
I will fix this issue by revert this commit, it's no longer needed right now.

And it only occurred OEL7 artifact-test. 
When we executed `systemctl cat var-lib-systemd-coredump.mount`, only OEL7 verified the config content, then the configure error can be identified, and failed the job.

The problem can also be touched if we try to enable/start var-lib-systemd-coredump.mount on other distros.


```
[clckwrk@artifacts-oel76-jenkins-db-node-4ad21b7e-1 system]$ systemctl cat var-lib-systemd-coredump.mount
Unit var-lib-systemd-coredump.mount is not loaded: Invalid argument
[clckwrk@artifacts-oel76-jenkins-db-node-4ad21b7e-1 system]$ echo $?
1
[clckwrk@artifacts-oel76-jenkins-db-node-4ad21b7e-1 system]$ sudo systemd-analyze verify var-lib-systemd-coredump.mount
[/usr/lib/systemd/system/scylla-server.slice:7] Unknown lvalue 'IOAccounting' in section 'Slice'
[/usr/lib/systemd/system/scylla-server.slice:14] Unknown lvalue 'IOWeight' in section 'Slice'
[/usr/lib/systemd/system/scylla-server.slice:16] Unknown lvalue 'MemorySwapMax' in section 'Slice'
[/usr/lib/systemd/system/scylla-server.slice:18] Unknown lvalue 'CPUWeight' in section 'Slice'
[/usr/lib/systemd/system/scylla-helper.slice:7] Unknown lvalue 'IOAccounting' in section 'Slice'
[/usr/lib/systemd/system/scylla-helper.slice:10] Unknown lvalue 'CPUWeight' in section 'Slice'
[/usr/lib/systemd/system/scylla-helper.slice:11] Unknown lvalue 'IOWeight' in section 'Slice'
[/usr/lib/systemd/system/scylla-helper.slice:14] Unknown lvalue 'MemoryHigh' in section 'Slice'
[/usr/lib/systemd/system/scylla-helper.slice:17] Unknown lvalue 'MemoryMax' in section 'Slice'
[/usr/lib/systemd/system/scylla-helper.slice:22] Memory limit '5%' invalid. Ignoring.
[/etc/systemd/system/scylla-helper.slice.d/memory.conf:2] Unknown lvalue 'MemoryHigh' in section 'Slice'
[/etc/systemd/system/scylla-helper.slice.d/memory.conf:3] Unknown lvalue 'MemoryMax' in section 'Slice'
var-lib-systemd-coredump.mount's Where= setting doesn't match unit name. Refusing.
Error: org.freedesktop.DBus.Error.InvalidArgs: Unit is not loaded properly: Invalid argument.
Failed to create var-lib-systemd-coredump.mount/start: Invalid argument
[clckwrk@artifacts-oel76-jenkins-db-node-4ad21b7e-1 system]$ 
```

**Comment by amoskong** [comment]
This issue had been fixed by https://github.com/scylladb/scylla/commit/9d9d54c804dd400d90edfdb84c8f5319d06b1633, the new artifact-test of oel76 passed.

- https://jenkins.scylladb.com/view/master/job/scylla-master/job/artifacts/job/artifacts-oel76-test/102/
