### ISSUE TITLE
lwt: remove separate ::query() round altogether

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#6405]
While read round optimization was introduced initially as an optimization only, it's now clear we can always use it, and never do the query() round separately. This will simplify the code. 
The fix is to stop ignoring the failing read future in paxos_state.cc, paxos_state::prepare() and fail the prepare if read fails. Then we can assert the digest is always there and remove the else {} branch handling the failed prefetch case.

**Comment by gleb-cloudius** [comment]
The query() does read repair while the optimization only handles digest
match case. I do not see how the query round can be dropped.

--
			Gleb.

**Comment by kostja** [comment]
I agree we need read repair, but we do not need to read the same data again to discover we need it. If digests mismatch, we can perform read-repair without an extra query.

**Comment by gleb-cloudius** [comment]
Read repair _requires_ extra query because it read the data from all the
nodes to repair, it is not possible to repair based on a digest alone. We may
skip a digest phase of the read, but honestly it is too minor of an
improvement in already slow case.

--
			Gleb.

**Comment by kostja** [comment]
Gleb, I'd still keep this open since I think ignoring the failed future in paxos_state::prepare() is error prone, we shouldn't do it. Thoughts?

**Comment by gleb-cloudius** [comment]
On Tue, May 12, 2020 at 03:12:53PM -0700, Konstantin Osipov wrote:
> Gleb, I'd still keep this open since I think ignoring the failed future in paxos_state::prepare() is error prone, we shouldn't do it. Thoughts?
> 
Why do you think it is error prone?

--
			Gleb.

**Comment by kostja** [comment]
Checked the source, closing as Won't fix.
