### ISSUE TITLE
The Scylla monster ate your page!——"https://www.scylladb.com/download/centos_rpm/"

### ISSUE THREAD

**Issue by Felix-zhoux** [scylladb/scylla#6407]
Hi, I found some of the pages were inaccessible, and I needed them to guide me through how to install Scylla. In particular, how do you install Scylla on systems that are difficult to solve with dependent packages.

**Comment by dorlaor** [comment]
Can you pls refresh your browser cache?
We've made some changes and the OSS release
is at: https://www.scylladb.com/download/#open-source

**Comment by slivne** [comment]
@Felix-zhoux closing this issue - I expect Dor's input helped. if not please repost and we will help you solve it.
