### ISSUE TITLE
Creating snapshot with a tag fails

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#641]
$ nodetool snapshot -t xx2
Requested creating snapshot(s) for [all keyspaces] with snapshot name [xx2]
error: Keyspace keyspace1: snapshot xx2 already exists.

**Comment by vladzcloudius** [comment]
Doesn't reproduce with HEAD 2ba49103850f4d7b0107ab36b9dfcde2b7540743
@slivne Pls., close
