### ISSUE TITLE
assert failed in remove_index_file_test: future_state_base::set_exception may be called in state::invalid from future_state_base::set_to_broken_promise

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6413]
See scylladb/seastar#746

After bypassing that assert and reproducing in debug mode, it appears that this was caused by e8213fb5c3fba3a2b5f12debe91729e956cbb85c
It looks `compaction_manager::stop()` is called twice and 2nd time around
`do_stop` returns immediately, leaving `_stop_future` disengaged.
```
future<> compaction_manager::stop() {
    do_stop();
    return std::move(*_stop_future);
}
```

Test passes with the following patch:
```
diff --git a/sstables/compaction_manager.cc b/sstables/compaction_manager.cc
index fbd0ae6c48..fab15afc16 100644
--- a/sstables/compaction_manager.cc
+++ b/sstables/compaction_manager.cc
@@ -456,7 +456,7 @@ void compaction_manager::postpone_compaction_for_column_family(column_family* cf
 
 future<> compaction_manager::stop() {
     do_stop();
-    return std::move(*_stop_future);
+    return _stop_future ? std::move(*_stop_future) : make_ready_future<>();
 }
 
 void compaction_manager::do_stop() {
```

I'll re-test without the bypass of the assert in seastar and will send to the list.

**Comment by avikivity** [comment]
@bhalevy better to let @glommer see if that's a correct fix. Not failing an assertion is not enough.

**Comment by bhalevy** [comment]
> @bhalevy better to let @glommer see if that's a correct fix. Not failing an assertion is not enough.

no problem.  I based this fix in part on @glommer's comment in this patch:
```
+    // We use a shared promise to indicate whether or not we are stopped because it is legal
+    // for stop() to be called twice. For instance it is called on DRAIN and shutdown.
+    std::optional<future<>> _stop_future;
```

**Comment by glommer** [comment]
we had made the decision of chasing and killing double stops, so indeed
it's better if I figure out where this is coming from too.

I will look at this soon

**Comment by bhalevy** [comment]
To reproduce, see https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/477/testReport/sstable_generation_loading_test/TestSSTableGenerationAndLoading/remove_index_file_test

**Comment by glommer** [comment]
Ok, FYI @avikivity this one seems to be like the gossip one. Not double stop(), but a call to stop() before `start()`

It's becoming increasingly clear that the fact that we conflate `stop` with `enabled` is problematic and that surfaced as feeedback in the offstrategy series as well.

So I'll just rip off the bandaid and handle this right now

**Comment by glommer** [comment]
Also the reason for this stop-before-start seems harder to work around anyway: it's just an exception that happens before the point in time in which we've called start.

**Comment by bhalevy** [comment]
Please backport to 4.1

**Comment by avikivity** [comment]
Backported to 4.1 (only vulnerable release).
