### ISSUE TITLE
hinted handoff: commitlog positions are not removed from rps_set for expired hints

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla#6422]
When sending hints from a single file, we keep track of commitlog positions of hints that are being sent at the moment, and remove them when respective hints are sent successfully. If a hint fails to be sent, we leave it in rps_set. If sending of some hints fail, then we will retry sending hints from that file later, and we will use the lowest commitlog position from rps_set as a starting point.

Usually, rps_set will have bounded size - we allow at most 128 concurrent hints to be sent, and we don't send any more hints if we detect a failure.

Errorneously, when encountering a hint that is expired (its age is greater than gc_grace_seconds of the destination table), we insert its position into rps_set but not remove it. This can cause rps_set to grow large. It may also interfere with non-expired hints, if some of them fail to be sent - new starting point might cause us to resend more hints than necessary.

We should remove commitlog positions of a hint after we detect that it is too old. Relevant change should be made around [this line](https://github.com/scylladb/scylla/blob/7da949026da980caf1cee0d96cce1dc76e6e736c/db/hints/manager.cc#L706).

**Comment by avikivity** [comment]
Backported to 3.3, 4.0, 4.1.
