### ISSUE TITLE
scylla_setup failed on oel7: unit var-lib-systemd-coredump.mount not found

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#6432]
*Installation details*
Scylla version (or git commit hash): scylla-4.1.rc0-0.20200511.0760107b9fa.x86_64.rpm
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): OEL7
Base AMI used for artifact-test: ami_id_db_scylla: 'ami-0d6a24fe35fdf5dc4' (eu-west-1)

This problem doesn't exist with CentOS7:
- PASSed: https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/artifacts/job/artifacts-centos7/2/

### Test Job:
https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/artifacts/job/artifacts-oel76/2/

### Scylla_setup Error:

```
unit var-lib-systemd-coredump.mount not found
```

### Scylla_setup output:

```
Scylla version:  scylla-4.1.rc0-0.20200511.0760107b9fa.x86_64.rpm


sudo /usr/lib/scylla/scylla_setup --nic eth0 --disks /dev/nvme0n1 '
> 
> Exit code: 1
> 
> Stdout:
> 
>          =                       sectsz=512   attr=2, projid32bit=1
>          =                       crc=0        finobt=0, sparse=0, rmapbt=0, reflink=0
> data     =                       bsize=4096   blocks=115966796, imaxpct=25
>          =                       sunit=0      swidth=0 blks
> naming   =version 2              bsize=4096   ascii-ci=0 ftype=1
> log      =internal log           bsize=4096   blocks=56624, version=2
>          =                       sectsz=512   sunit=0 blks, lazy-count=1
> realtime =none                   extsz=4096   blocks=0, rtextents=0
> Creating XFS volume for scylla using 1 disk(s): /dev/nvme0n1
> coredump setup failed.
> 
> Stderr:
> 
> subprocess.CalledProcessError: Command '['systemctl', 'cat', 'var-lib-systemd-coredump.mount']' returned non-zero exit status 1.
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/opt/scylladb/scripts/libexec/scylla_coredump_setup", line 80, in <module>
>     systemd_unit('var-lib-systemd-coredump.mount').enable()
>   File "/opt/scylladb/scripts/scylla_util.py", line 619, in __init__
>     raise SystemdException('unit {} not found'.format(unit))
> scylla_util.SystemdException: unit var-lib-systemd-coredump.mount not found
```

**Comment by roydahan** [comment]
probably a dup of #6402

**Comment by amoskong** [comment]
> probably a dup of #6402

Yes, same one.

**Comment by amoskong** [comment]
This isn't not same issue as #6402

- This issue is that: var-lib-systemd-coredump.mount  file isn't found in coredump_setup.
- Issue #6402 is that var-lib-systemd-coredump.mount file exists, but the content is invalid (failed to load the config)

**Comment by amoskong** [comment]
Latest status:  the problem ONLY exists on OEL 
FYI, @roydahan @bentsi @syuu1228 


- scylla-master:  https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-oel76-test/100/
- scylla-4.1: https://jenkins.scylladb.com/job/scylla-4.1/job/artifacts/job/artifacts-oel76/19

**Comment by amoskong** [comment]
In scylla_util.py, we always raise exception 'Unit xxx not found' when exception raised in executing 'systemctl cat xxx'.

The error is confused.

```
610 class systemd_unit:
611     def __init__(self, unit):
612         if is_nonroot():
613             self.ctlparam = '--user'
614         else:
615             self.ctlparam = ''
616         try:
617             run('systemctl {} cat {}'.format(self.ctlparam, unit), silent=True)
618         except subprocess.CalledProcessError:
619             raise SystemdException('unit {} not found'.format(unit))
620         self._unit = unit
621 
"./dist/common/scripts/scylla_util.py" 686 lines --83%--        
```

I just manually tested on OEL7. Actually it's same issue as #6402 
Detail: https://github.com/scylladb/scylla/issues/6402#issuecomment-637350677

I will post a patch to fix the error.

Close this issue as duplicate with #6402
