### ISSUE TITLE
hinted handoff: commitlog positions are not removed from rps_set for discarded hints

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla#6433]
This issue is similar to https://github.com/scylladb/scylla/issues/6422

In sender::send_one_hint(), if an exception occurs after hint position is inserted to rps_set but before sender::send_one_mutation() is called, then the error will be ignored and the hint will be discarded.

In this case, commitlog position of the hint won't be removed, although it should. rps_set should only retain positions of hints that failed to be sent.

Position of the hint should be removed from rps_set just before [this line](https://github.com/scylladb/scylla/blob/517f2c049058a2231853515b43732fadba77017a/db/hints/manager.cc#L729).

**Comment by avikivity** [comment]
Backported to 3.3, 4.0, 4.1.
