### ISSUE TITLE
replace_address_test fails with: 512 != 256

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6437]
Seen since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/477/testReport/replace_address_test/TestReplaceAddress/replace_first_boot_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/477/testReport/replace_address_test/TestReplaceAddress/replace_shutdown_node_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/477/testReport/replace_address_test/TestReplaceAddress/replace_stopped_node_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/replace_address_test.py", line 48, in replace_shutdown_node_test
    self._replace_node_test(gently=True)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/replace_address_test.py", line 104, in _replace_node_test
    self.assertEqual(len(movedTokensList), numNodes)
  File "/usr/lib64/python3.7/unittest/case.py", line 869, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib64/python3.7/unittest/case.py", line 862, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 512 != 256
```

Scylla version 791acc7f3858e5541ee216034f4c7111818510c5
(That includes 71d0d58f8c2fad106c5282a3ac750e441e1a117c "Revert "config: Do not enable repair based node operations by default")

**Comment by asias** [comment]
The test checks "Token .* changing ownership from" message to check if the token ownership has changed correctly. However it is is not reliable because very time token_metadata_impl::update_normal_tokens is called, we print the message. update_normal_tokens can be called on temporary token_metadata object.

I plan to move the "Token {} changing ownership from {} to {}" message from warn to debug. 

We'd better change the test to use other methods than replying on the  "Token {} changing ownership from {} to {}"  log message.

**Comment by slivne** [comment]
@asias can you please suggest how this can be fixed - what other methods can be used

**Comment by asias** [comment]
> @asias can you please suggest how this can be fixed - what other methods can be used

For example, use the output of nodetool ring.

**Comment by slivne** [comment]
@roydahan please assign someone to fix the test

**Comment by roydahan** [comment]
Added a task for it, you can close this for now if you want.

**Comment by slivne** [comment]
I'll leave this open till we have the dtest fixed

**Comment by bhalevy** [comment]
@roydahan is there a github issue/pull request for the dtest task that we can link to close this issue?

**Comment by roydahan** [comment]
https://trello.com/c/euCXKfJc

**Comment by bhalevy** [comment]
@roydahan ping.  These dtests still fail in the same way.

**Comment by fgelcer** [comment]
i have done a fix, i'm checking if all tests are passing (including an option to `DISABLE_VNODES` that could conflict with the fix i'm currently working on, and shall send a PR with the fix in the next minutes.

**Comment by bhalevy** [comment]
The tests passed in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/547
Issue can be closed
