### ISSUE TITLE
Regular compaction INCORRECTLY used shared sstable (exclusive for resharding)

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6439]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 76d21a0c22049759b
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

ERROR 2020-05-12 09:53:26,160 [shard 7] compaction_manager - compaction failed: std::runtime_error (A regular compaction for system.compaction_history INCORRECTLY used shared sstable /jenkins/workspace/scylla-master/dtest-release/scylla/.dtest/dtest-ykr4ec4t/test/node1/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/mc-9-big-TOC.txt. Only resharding work with those!): retrying

many resharding tests now fail in master like this:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/480/testReport/resharding_test/ReshardingTest_nodes1_with_DateTieredCompactionStrategy/resharding_by_murmur3_smp_test/

**Comment by bhalevy** [comment]
It looks like no backport required at the moment since 88d2486fcafc4e0e25d988b4dc9c4022ddf9bd1d wasn't backported anywhere.
