### ISSUE TITLE
Give users better error message when the config file is in a FS without O_DIRECT support:

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#644]
I was setting up dtests on my laptop, when I got the following error:

    /home/lmr/.ccm/scylla-1/node1/bin/scylla.release --options-file /home/lmr/.ccm/scylla-1/node1/conf/scylla.yaml --api-address 127.0.0.1 --collectd-hostname lmr-XPS-13-9350.node1 --smp 1 --memory 512M --default-log-level info --collectd 0 --cpuset 0
    Scylla version development-20151210.2167173 starting ...
    ERROR [shard 0] init - Could not read configuration file /home/lmr/.ccm/scylla-1/node1/conf/scylla.yaml: std::system_error (error system:22, Invalid argument)
    Exiting on unhandled exception of type 'std::system_error': Error system:22 (Invalid argument)

The file `/home/lmr/.ccm/scylla-1/node1/conf/scylla.yaml` was accessible and had valid YAML config.

It took me and @glommer a bit of time to figure out that the problem was that the file was not in a filesystem with `O_DIRECT` support (encryptfs) [1].

It'd be interesting to have a better error message to the user in such cases (it would have saved us the minutes we lost trying to understand what was wrong).

[1] That's how Ubuntu chose to implement the home directory encryption.

**Comment by glommer** [comment]
We have a quite handy O_DIRECT check that we use for the data directory. All we need to do is to apply the same test to the config file as well.

I'll cook a patch.

**Comment by RobinUS2** [comment]
So we have a similar error:
```
Apr 12 08:29:14 scylla-global-002 scylla:  [shard 0] seastar - Exiting on unhandled exception: std::system_error (error system:22, Invalid argument)
```
which was NOT related to IO, even though the error looks very similar. Which caused us to chase our tails for a bit regarding the aysnc IO and all of that. It turned out to be misconfiguration of the listen_address (was localhost, must have been the internal ip in our case). Writing this here so other people with this vague error might be helped by it.

**Comment by penberg** [comment]
@RobinUS2 Which Scylla version is this? I am not able to reproduce with this information alone because `listen-address` set to `localhost` seems to work OK.
