### ISSUE TITLE
Streaming SSTables are not being accounted by the backlog controller

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6441]
Turns out SSTables created by streamign are not being accounted by the backlog controller. Which means that the controller will not act accordingly after the streaming process is done, so compaction may be slower than expected, affecting read and space amplification.

**Comment by slivne** [comment]
AFAIK streamed sstables can be compacted they need to be moved and then
compacted (at times they will be moved to staging - if there are views). So
should streamed sstables  accounted for when they can be compacted. If I am
not mistaken, off-strategy compaction will compact them together before
moving them.

Thus its not clear to me if the "generic" title is correct or not.

**Comment by raphaelsc** [comment]
On Tue, May 12, 2020 at 6:36 PM Shlomi Livne <notifications@github.com>
wrote:

> AFAIK streamed sstables can be compacted they need to be moved and then
> compacted (at times they will be moved to staging - if there are views). So
> should streamed sstables accounted for when they can be compacted. If I am
> not mistaken, off-strategy compaction will compact them together before
> moving them.
>
> Thus its not clear to me if the "generic" title is correct or not.
>

Reading streaming code, I can confirm that this problem applies to both
regular and view update (which use staging) cases. What is happening in the
backlog tracker internally is that it's not receiving the Streaming
SSTables but we're later asking for their removal due to a bug in the code.
That is leading to incorrect backlog calculation.

The fix, already reviewed by Glauber, for this problem is part of my series
that fixes a couple of backlog bugs, titled as: Make sure SSTables created
by streaming are added to backlog tracker.

**Comment by avikivity** [comment]
I think we should backport, but let's let it cook a little.

**Comment by avikivity** [comment]
Aged out.
