### ISSUE TITLE
API: Add long polling to StorageServiceRepairAsyncByKeyspaceGet

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla#6445]
This is needed to make repairs faster as measured in walltime.

Scylla Manager asks Scylla to repair a given token range and then waits for Scylla to end using `/storage_service/repair_async/{keyspace}` endpoint.

The API where we need to poll for repair job results each Xms introduces a significant delay in the whole process as seen by user.

Let's say we have
- 9 nodes 
- 5k tables
- 4 shards each node
- 16 ranges per shard
- RF=3

If we poll each 50ms, then the mean wasted time per operation is 25ms.

That makes 25 minutes of walltime spent on waiting that could be avoided `(9 * 256 * 5000) / (4 * 16) * 25 / 1000 / 3 / 60`. The wasted CPU time is 3 times as much. It explodes with nr. of tables and if you want to go slower it degradates as well.

Repairing 1 token range at a time results in over a DAY (1600 minutes) of waiting that could be avoided `(9 * 256 * 5000) * 25 / 1000 / 60 / 3`.

To work around it we can:
1. Increase poll time or spin waiting for result - expensive?
1. Repair the whole keyspace - in that case progress UX and resume speed suffer - slow updates and need to redo killed repairs

Suggested API changes:

Extend `/storage_service/repair_async/{keyspace}` endpoint with `int wait` parameter that describes how many seconds to wait for repair result.

**Comment by mmatczuk** [comment]
Please give it a priority @tzach @eyalgutkind cc: @slivne

**Comment by slivne** [comment]
@mmatczuk In the case of row level repair - I am not sure that repairing segment by segment makes sense - I think we have changed that - no ?

**Comment by mmatczuk** [comment]
API did not change, we repair a token range @slivne.

**Comment by slivne** [comment]
for row_level repair we have https://github.com/scylladb/mermaid/issues/1736 - no ? that means that we will have "larger token ranges" (not per shard split by msb_bit) - or am I missing something ?

**Comment by mmatczuk** [comment]
The Scylla API that Manager (or Nodetool) uses remains the same, the way it's used changes in the issue you linked. 

For this issue it's completely irrelevant how you schedule repair job in Scylla. It's important how you wait for Scylla to end.

**Comment by asias** [comment]
Patch posted: https://github.com/scylladb/scylla/pull/6743

**Comment by mmatczuk** [comment]
@tzach can we release that patch in a version?

**Comment by avikivity** [comment]
It will be in 4.4. You can use the nightly builds for testing.

**Comment by slivne** [comment]
Avi means 4.3 - and you can use the nightly build :)

**Comment by mmatczuk** [comment]
Any plans to porting that to Enterprise?

**Comment by mmatczuk** [comment]
Ping.
