### ISSUE TITLE
sstable code needs to close files in error paths

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6448]
Scylla version 517f2c04905 (and all active release branches)
In addition to #5509 I've hit assertion failures when running a large number of dtests locally and running out of file descriptors.

We have a few cases where files opened by the sstable code are not properly closed in error paths:
- when creating or opening the data and index files
- in `read_toc`
- in `remove_by_toc_name`

**Comment by avikivity** [comment]
Change is too large and risky to backport, at least now.

**Comment by avikivity** [comment]
I'm still afraid to backport this.
