### ISSUE TITLE
--abort-on-seastar-bad-alloc is too drastic

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#6449]
To debug OOM situation we often require users to add --abort-on-seastar-bad-alloc, but that is too drastic. We should have bad_alloc print out enough information to understand the situation, similar to scylla-gdb.py's dumps or the kernel's OOM dumps.

**Comment by avikivity** [comment]
/cc @denesb @tgrabiec .

We can add hooks to be called on OOM to print out various stuff. We should have a small memory reserve so that the print routines continue to work while dumping.

**Comment by denesb** [comment]
Refs: https://github.com/scylladb/scylla/issues/6365

**Comment by tgrabiec** [comment]
@avikivity Is this a duplicate of  #6365? 

I think there will still be cases when we will need a core dump to get to the root cause, so --abort-on-seastar-bad-alloc will be useful.

**Comment by avikivity** [comment]
Closing as duplicate. I'm not proposing to retire --abort-on-seastar-bad-alloc, just make it less frequent.

**Comment by gleb-cloudius** [comment]
FWIW when seastar_memory loggers is in trace or debug level it print
information similar to "scylla memory" on allocation failure.

--
			Gleb.

**Comment by denesb** [comment]
Once we have #6535 we can reuse the infrastructure to implement a
--dump-mem-report-on-bad-alloc.
