### ISSUE TITLE
alternator: add configurable *default* write isolation mode

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#6452]
Alternator has four write isolation policies described in `alternator.md`: `always_use_lwt`, `forbid_rmw`, `only_rmw_uses_lwt`, `unsafe`. The policy can be chosen per table (by tagging the table), but if not chosen, it currently always defaults to `always_use_lwt`.

Let's make this default configurable, e.g., via a configuration option "--alternator-write-mode".

Also, @dorlaor asked that this choosing this mode be **mandatory**. I.e., if this option isn't explicitly specified, Alternator will refuse to boot stating this option must be set. This means that we also need to update our documentation of how to start Scylla to mention this option and how to choose the right value for it.

We probably also need to update our docker startup script to support this option.

Issue #6421 is also related: If `forbid_rmw` mode can now become the default mode, the error messages it produces need to be clearer.

**Comment by nyh** [comment]
Backporting to 4.1. This will require the user to change the way they run Alternator, but we want it to be in 4.1. Not backporting to 4.0, where the default Alternator write isolation will remain always_use_lwt.

**Comment by tzach** [comment]
@nyh for new install, user need to provide a value.
What is the status for upgrade from 4.0? will current Alternator deployment stop working till the value is provided?
Can it be added to scylla.yaml? if so, please provide an example

**Comment by tzach** [comment]
@amoskong FYI, this might effect the upgrade procedure

**Comment by nyh** [comment]
@tzach Indeed, a user upgrading from 4.0 will not be able to boot until specifying a value for this option. @dorlaor asked that this option be **mandatory** and there mustn't be a default for it, but perhaps for users upgrading this requirement is too strict. I tend to agree that the upgrade process should set this option for you so that 4.1 behaves like 4.0 did.
If you want to have on 4.1 the same behavior you had on 4.0, you should set the option to **always_use_lwt** (the shortcut **always** also works). Note that the option's name is  **alternator_write_isolation**, not other names proposed earlier in this issue. 
Definitely you can set this option in scylla.yaml. But only for an upgrade! @dorlaor specifically asked that this option should not have a default for new installations, and the user should carefully weigh the available choices and make an informed decision.

**Comment by tzach** [comment]
I also noticed the `unsafe_rmw` is not document

**Comment by nyh** [comment]
> I also noticed the `unsafe_rmw` is not document

I don't think there is any reason to ever use this option, it's the way we had things before we had LWT (i.e., read first and then write, without any concurrency protection) and probably should never use now that we do LWT. I am planning to remove this option in the future - maybe we should have already removed it now.
