### ISSUE TITLE
Bad error message if Docker image started on non-x86

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#6457]
We had someone report that they saw the following error message:

```
standard_init_linux.go:207: exec user process caused "exec format error"
```

It turns out the problem was that they were running Docker on `arm64`, which Scylla does not support. Let's investigate if we can improve the error message by changing the Docker image somehow.

**Comment by ShlomiBalalis** [comment]
The error popped up in the offline centos 8 arm artifact test of the master branch:
## Installation details



Cluster size: 1 nodes (r6gd.large)

Scylla Nodes used in this run:
- artifacts-centos8-jenkins-db-node-c8b34d39-1 (52.50.82.219 | 10.0.1.141) (shards: -1)


OS / Image: `ami-07d54ca4e98347364` (aws: eu-west-1)

Test: `artifacts-centos8-arm-test`
Test id: `c8b34d39-19fc-4587-b6be-777c867f3e1f`
Test name: `scylla-master/artifacts-offline-install/artifacts-centos8-arm-test`
Test config file(s):

- [centos8.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/24e775790ef0b612c193fcc7c44feea35edbef15/test-cases/artifacts/centos8.yaml)

## Issue description

The installation process fails:
```
Command: 'sudo bash -cxe "\ntar xvfz ./unified_package.tar.gz\n./install.sh --housekeeping\nrm -f /tmp/scylla.yaml\n"'

Exit code: 126

Stdout:

scylla-tools/debian/control
scylla-tools/debian/copyright
scylla-tools/debian/rules
scylla-tools/debian/scylla-tools-core.install
scylla-tools/debian/scylla-tools.install
scylla-tools/debian/source/
scylla-tools/debian/source/format
scylla-tools/debian/source/options
uninstall.sh
.relocatable_package_version

Stderr:

+ tar xvfz ./unified_package.tar.gz
+ ./install.sh --housekeeping
./install.sh: line 128: libreloc/ld.so: cannot execute binary file: Exec format error
```

- Restore Monitor Stack command: `$ hydra investigate show-monitor c8b34d39-19fc-4587-b6be-777c867f3e1f`
- Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=c8b34d39-19fc-4587-b6be-777c867f3e1f)
- Show all stored logs command: `$ hydra investigate show-logs c8b34d39-19fc-4587-b6be-777c867f3e1f`

## Logs:
- **db-cluster-c8b34d39.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c8b34d39-19fc-4587-b6be-777c867f3e1f/20220519_055238/db-cluster-c8b34d39.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c8b34d39-19fc-4587-b6be-777c867f3e1f/20220519_055238/db-cluster-c8b34d39.tar.gz)
- **sct-runner-c8b34d39.tar.gz** - [https://cloudius-jenkins-test.s3.amazonaws.com/c8b34d39-19fc-4587-b6be-777c867f3e1f/20220519_055238/sct-runner-c8b34d39.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/c8b34d39-19fc-4587-b6be-777c867f3e1f/20220519_055238/sct-runner-c8b34d39.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/artifacts-offline-install/job/artifacts-centos8-arm-test/4/)

**Comment by avikivity** [comment]
You're installing the wrong package, install the arm package instead.

```
< t:2022-05-19 05:47:20,894 f:sct_config.py   l:1596 c:sdcm.sct_config      p:INFO  > unified_package: http://downloads.scylladb.com/unstable/scylla/master/relocatable/2022-05-19T03:57:38Z/scylla-x86_64-unified-package-5.1.dev.0.20220519.e6fe9cc683f4.tar.gz
```

**Comment by avikivity** [comment]
Closing as WONTFIX. First, we do have an arm docker image now so it won't happen again. Second, that's a docker problem downloading and running an image for an architecture it doesn't support.
