### ISSUE TITLE
Moving of nodes between RACKS and altering keyspaces from SimpleStrategy to NetworkTopologyStrategy requires restarting nodes

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#6459]
Scylla version: 666.development-0.20200125.e1b22b6a4c5

procedure https://docs.scylladb.com/operating-scylla/procedures/cluster-management/update-topology-strategy-from-simple-to-network/

Scenario:

- using GossipingPropertyFileSnitch
- 3 nodes (A,B,C) in one DC - each in a separate rack
- keyspace with SimpleStrategy, replication_factor=2
- stopping nodes B,C and moving them to rack of A
- starting nodes B,C
- Altering keyspace to NetworkToplogyStrategy with replication of 2 in the DC
- running nodetool descringring on node A returns only one replica
- stopping + starting node A
- running nodetool descringring on node A returns all replicas

dtest reproducer
```
import os
from dtest import Tester
from tools import putget
from nose.plugins.attrib import attr


@attr('dtest-full')
class TestMovingFromSimpltToNetwork(Tester):


    def __node_update_dc_rack(self,node,dc,rack):
        rackdc_file = os.path.join(node.get_conf_dir(), 'cassandra-rackdc.properties')
        with open(rackdc_file, 'w') as f:
            f.write("dc=%s\n" % dc)
            f.write("rack=%s\n" % rack)

    def simple_rf2_to_network_test(self):
        cluster = self.cluster
        cluster.populate([1, 1, 1])
        node0, node1, node2 = cluster.nodelist()
        self.__node_update_dc_rack(node0,"dc1","rack1")
        self.__node_update_dc_rack(node1,"dc1","rack2")
        self.__node_update_dc_rack(node2,"dc1","rack3")
        cluster.start()

        session = self.patient_cql_connection(node0)
        self.create_ks(session, 'ks', 2)
        self.create_cf(session, 'cf')

        node1.stop()
        node2.stop()
        self.__node_update_dc_rack(node1,"dc1","rack1")
        self.__node_update_dc_rack(node2,"dc1","rack1")
        node1.start(wait_for_binary_proto=True)
        node2.start(wait_for_binary_proto=True)
        out = node0.nodetool("status")
        print(out)
        session.execute("ALTER KEYSPACE ks WITH REPLICATION = {'class':'NetworkTopologyStrategy', 'dc1':2};")

        out = node0.nodetool("describering ks")
        print(out)
        node0.stop()
        node0.start(wait_for_binary_proto=True)
        out = node0.nodetool("describering ks")
        print(out)
```
Please note that if the nodes are placed in different DCs and the same rack the issue doesn't reproduce (that is we do not need to restart Node A and computation is correct)

**Comment by slivne** [comment]
@elcallio please have a look

**Comment by elcallio** [comment]
So the problem is that when a node moves between racks, we are in this case left with empty racks (no endpoints, they don't actually exist) in `topology`. On restart, since no nodes are configured to the racks, we don't. 

Seems a reasonable fix is to prune empty racks on endpoint changes.

**Comment by gleb-cloudius** [comment]
On Tue, May 19, 2020 at 08:15:33AM -0700, Calle Wilund wrote:
> So the problem is that when a node moves between racks, we are in this case left with empty racks (no endpoints, they don't actually exist) in `topology`. On restart, since no nodes are configured to the racks, we don't. 
> 
> Seems a reasonable fix is to prune empty racks on endpoint changes. 
> 
Yes, but the algorithm should have chosen enough replicas anyway, no?

--
			Gleb.

**Comment by elcallio** [comment]
No, because it believes that there exists racks that are in fact removed at this point. 
I've sent a patch that prunes dead racks from topology.

I am not so fond of doing defensive checking on the returned dc->rack set in the strategy itself, since we should make the available data consistent between clean boot and call after cluster change.

**Comment by avikivity** [comment]
Backported to 4.1. 4.2+ is safe.
