### ISSUE TITLE
lwt_destructive_ddl_test:LwtDestructiveDDLTest.test_drop_column: std::out_of_range (regular column id 0 >= 0)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6467]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/484/testReport/lwt_destructive_ddl_test/LwtDestructiveDDLTest/test_drop_column/
Scylla version a96087165a92959ff4da74364b681c2906c16745
```
Unexpected errors found: [('node3', ['ERROR 2020-05-16 09:01:18,621 [shard 1] storage_proxy - exception during mutation write to 127.0.42.3: std::out_of_range (regular column id 0 >= 0)'])]
```

This is coming from `storage_proxy::send_to_live_endpoints`

**Comment by bhalevy** [comment]
Cc @gleb-cloudius @kostja

**Comment by bhalevy** [comment]
Hit again in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/510/testReport/lwt_destructive_ddl_test/LwtDestructiveDDLTest/test_drop_column/

**Comment by kostja** [comment]
This is another manifestation of #6074

**Comment by bhalevy** [comment]
ping.  happened again in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/566/testReport/lwt_destructive_ddl_test/LwtDestructiveDDLTest/test_drop_column/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 648, in run
    self.tearDown()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1094, in tearDown
    self.cleanUpCluster()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1138, in cleanUpCluster
    raise AssertionError('Unexpected errors found: {}'.format(found_errors))
AssertionError: Unexpected errors found: [('node2', ['ERROR 2020-07-29 07:02:04,638 [shard 1] storage_proxy - exception during mutation write to 127.0.1.2: std::out_of_range (regular column id 0 >= 0)'])]
```

**Comment by kostja** [comment]
@ManManson is still working on a fix :(

**Comment by ManManson** [comment]
Fixed by https://github.com/scylladb/scylla/commit/f893516e55cc9b230c00e7b094d0e4eeb77335b3

**Comment by avikivity** [comment]
Should we backport https://github.com/scylladb/scylla/commit/f893516e55cc9b230c00e7b094d0e4eeb77335b3? It is a large change with a lot of risk.
