### ISSUE TITLE
Schema version calculation depends on serialization format of query results

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#647]
Change in query result serialization format would change the result of schema version calculation which would result in schema disagreements during rolling upgrade of nodes with different serialization formats.

See `schema_tables::calculate_schema_digest()`.

**Comment by tzach** [comment]
@tgrabiec will this affect only user which use ALTER TABLE?

**Comment by tgrabiec** [comment]
@tzach Mainly. We would have to remember about bumping up `messaging_service::current_version` whenever the format changes, this disables attempts to pull schema between nodes in schema disagreement.

Since bfefe5a, we're no longer calculating hash from the query format, so I'm closing this.

**Comment by gleb-cloudius** [comment]
On Mon, Jan 11, 2016 at 08:38:08AM -0800, Tomasz Grabiec wrote:
> @tzach Mainly. We would have to remember about bumping up `messaging_service::current_version` whenever the format changes, this disables attempts to pull schema between nodes in schema disagreement.
> 
Can you elaborate on that? We decided not to rely on single version for
rolling upgrades since it makes backporst impossible.

--
			Gleb.

**Comment by tgrabiec** [comment]
@gleb-cloudius I was referring to the mechanism present in C* and which we inherited a while ago. C* schedules schema sync between nodes when it detects schema version difference, unless the nodes have different "major version", which maps to RPC protocol version, then it doesn't sync. They might avoid doing the sync for several reasons. One may be that if two C* versions calculate schema version in a different way, they would never come to agreement. It could also be that the schema tables changed in an incompatible way, then exchanging the mutations would fail anyway. They solved it by not doing the schema sync during upgrades and disallowing schema changes until all nodes are upgraded. 

In my previous comment I was referring to this mechanism as a way to make the problem described in this issue benign. But in the end the issue was solved by changing schema version calculation to not depend on serialization format.

**Comment by gleb-cloudius** [comment]
On Tue, Jan 12, 2016 at 05:10:22AM -0800, Tomasz Grabiec wrote:
> @gleb-cloudius I was referring to the mechanism present in C* and which we inherited a while ago. C* schedules schema sync between nodes when it detects schema version difference, unless the nodes have different "major version", which maps to RPC protocol version, then it doesn't sync. They might avoid doing the sync for several reasons. One may be that if two C* versions calculate schema version in a different way, they would never come to agreement. It could also be that the schema tables changed in an incompatible way, then exchanging the mutations would fail anyway. They solved it by not doing the schema sync during upgrades and disallowing schema changes until all nodes are upgraded. 
> 
> In my previous comment I was referring to this mechanism as a way to make the problem described in this issue benign. But in the end the issue was solved by changing schema version calculation to not depend on serialization format. 
> 
> 
Thanks, I see. Should we drop version checking in schema sync code then?

--
			Gleb.

**Comment by tgrabiec** [comment]
2016-01-12 14:13 GMT+01:00 Gleb Natapov <notifications@github.com>:

> On Tue, Jan 12, 2016 at 05:10:22AM -0800, Tomasz Grabiec wrote:
> > @gleb-cloudius I was referring to the mechanism present in C* and which
> we inherited a while ago. C* schedules schema sync between nodes when it
> detects schema version difference, unless the nodes have different "major
> version", which maps to RPC protocol version, then it doesn't sync. They
> might avoid doing the sync for several reasons. One may be that if two C*
> versions calculate schema version in a different way, they would never come
> to agreement. It could also be that the schema tables changed in an
> incompatible way, then exchanging the mutations would fail anyway. They
> solved it by not doing the schema sync during upgrades and disallowing
> schema changes until all nodes are upgraded.
> >
> > In my previous comment I was referring to this mechanism as a way to
> make the problem described in this issue benign. But in the end the issue
> was solved by changing schema version calculation to not depend on
> serialization format.
> >
> >
> Thanks, I see. Should we drop version checking in schema sync code then?
>
>
I'm not sure about that. We want to be compatible with C* in schema tables,
if they make an incompatible change, we would have to have a mechanism to
detect this. We could version schema tables separately though.

**Comment by gleb-cloudius** [comment]
On Tue, Jan 12, 2016 at 05:26:39AM -0800, Tomasz Grabiec wrote:
> 2016-01-12 14:13 GMT+01:00 Gleb Natapov <notifications@github.com>:
> 
> > On Tue, Jan 12, 2016 at 05:10:22AM -0800, Tomasz Grabiec wrote:
> > > @gleb-cloudius I was referring to the mechanism present in C* and which
> > we inherited a while ago. C* schedules schema sync between nodes when it
> > detects schema version difference, unless the nodes have different "major
> > version", which maps to RPC protocol version, then it doesn't sync. They
> > might avoid doing the sync for several reasons. One may be that if two C*
> > versions calculate schema version in a different way, they would never come
> > to agreement. It could also be that the schema tables changed in an
> > incompatible way, then exchanging the mutations would fail anyway. They
> > solved it by not doing the schema sync during upgrades and disallowing
> > schema changes until all nodes are upgraded.
> > >
> > > In my previous comment I was referring to this mechanism as a way to
> > make the problem described in this issue benign. But in the end the issue
> > was solved by changing schema version calculation to not depend on
> > serialization format.
> > >
> > >
> > Thanks, I see. Should we drop version checking in schema sync code then?
> >
> >
> I'm not sure about that. We want to be compatible with C* in schema tables,
> if they make an incompatible change, we would have to have a mechanism to
> detect this. We could version schema tables separately though.
> 
Can we pull, check that version is incompatible and forget about
it if not? I see that messaging_service::current_version is used in
bunch of unrelated places. One is in should_pull_schema_from() another
is in reconnectable_snitch_helper::reconnect. How are those related?

--
			Gleb.
