### ISSUE TITLE
Alternator should start supporting empty strings and binary blobs

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#6480]
Following https://aws.amazon.com/about-aws/whats-new/2020/05/amazon-dynamodb-now-supports-empty-values-for-non-key-string-and-binary-attributes-in-dynamodb-tables/ , DynamoDB started supporting empty string and binary blob values (not keys). In order to remain compatible, alternator should implement handling these empty strings as well, along with accompanying tests.

**Comment by nyh** [comment]
This is an improvement, not a fix. Not backporting it per policy. This means we will only see this improvement in 4.2.
