### ISSUE TITLE
Compare Scylla to Cassandra with YCSB  

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#649]
[YCSB](https://github.com/brianfrankcooper/YCSB) is a generic set of benchmarks setting out to compare different key-value store providers under a set of loads.
In particular, YCSB try to [fix the Coordinated Omission problem](http://psy-lob-saw.blogspot.co.il/2015/03/fixing-ycsb-coordinated-omission.html) which cassandra-stress suffer from.
Benchmarking with YCSB is there for interesting and more realistic in that regards.
(it is less realistic from other perspectives, as it does not support c-s user profile)

**Comment by tzach** [comment]
Done and will be publish in the next few days

**Comment by avikivity** [comment]
http://www.scylladb.com/technology/ycsb-cassandra-scylla/
