### ISSUE TITLE
features::UNBOUNDED_RANGE_TOMBSTONES has suboptimal name

### ISSUE THREAD

**Issue by dekimir** [scylladb/scylla#6493]
When `gms::features::UNBOUNDED_RANGE_TOMBSTONES` is disabled, Scylla must reject DELETE statements that don't bound the clustering key from both sides.  The testcase [`test_invalid_range_deletion`](https://sourcegraph.com/github.com/scylladb/scylla@c29ccdea7e74dd5a8894a6f3186592eb56d7ec2a/-/blob/test/boost/cql_query_test.cc?subtree=true#L1095:19) checks this and currently passes.

But there is something unexpected in the test: when there are no relations on clustering keys, the DELETE statement is not rejected.  In other words, the test expects the following statement to execute normally: `DELETE FROM cf WHERE p = 1`.  This cannot be correct, as the clustering range is unbounded.  In contrast, the test expects `DELETE FROM cf WHERE p = 1 AND c1 < 2` to be rejected.  Surely if the latter is considered unbounded, the former must also be?

The likely cause of this is the use of `all_of` [here](https://sourcegraph.com/github.com/scylladb/scylla@c29ccdea7e74dd5a8894a6f3186592eb56d7ec2a/-/blob/cql3/restrictions/single_column_primary_key_restrictions.hh?subtree=true#L128).  That makes `single_column_primary_key_restrictions::has_bound()` return true when `_restrictions` is empty, ie, there are no clustering-key relations.

/cc @psarna

**Comment by dekimir** [comment]
One complication is that `UNBOUNDED_RANGE_TOMBSTONES` is disabled by default, but startup executes this statement: `DELETE FROM system_schema.keyspaces USING TIMESTAMP 1590185870213731 WHERE keyspace_name = ?` and expects it to succeed.  If we change the code to consider this unbounded, we'll have enable UNBOUNDED_RANGE_TOMBSTONES.

**Comment by dekimir** [comment]
@eliransin tells me that this is just a terminology bug, but the code is correct as it stands.  Queries deleting an entire partition are always allowed, even with the old sstable format (ie, `UNBOUNDED_RANGE_TOMBSTONES` disabled).  Furthermore, at startup time, the feature should be disabled, as we don't know if there are other nodes in the cluster that don't support it.

/cc @bhalevy

**Comment by bhalevy** [comment]
> @eliransin tells me that this is just a terminology bug, but the code is correct as it stands. Queries deleting an entire partition are always allowed, even with the old sstable format (ie, `UNBOUNDED_RANGE_TOMBSTONES` disabled). Furthermore, at startup time, the feature should be disabled, as we don't know if there are other nodes in the cluster that don't support it.
> 
> /cc @bhalevy

@dekimir I don't think this is a misnomer since it refers to *range* tombstones, not to partition tombstones nor row tombstones.  I understand that this not apparent in the cql layer, but I think we can live with that feature name as it is.

**Comment by dekimir** [comment]
>
> I think we can live with that feature name as it is.
>

We can live with it, but should we? How many developers will get confused
when half a partition is "unbounded" but the whole partition isn't? I just
spent a few hours trying to fix this before realizing there's nothing to
fix. Can we save the next person to some along from the same fate?

>
>

**Comment by bhalevy** [comment]
Please suggest a better name then.
In other places we referred to them as open-ended, but this seems equally confusing, if your perception of a partition tombstone is of a range tombstone open on both ends.
Maybe "semi-bound"?

**Comment by dekimir** [comment]
I'm trying to think of a better name, but it's such an unintuitive notion: "clustering key bounded from both-or-neither ends". Is that really how sstable works?

**Comment by dekimir** [comment]
I mean, what if I wanted to DELETE WHERE ck > 10?  Isn't that fully equivalent to DELETE WHERE ck > 10 AND ck < 9999999999999999999999?  Isn't that trivial to support?

**Comment by bhalevy** [comment]
> I'm trying to think of a better name, but it's such an unintuitive notion: "clustering key bounded from both-or-neither ends". Is that really how sstable works?

No, it is not how sstables work internally.
partition (and row) tombstones are represented differently than range tombstones.
For the latter we store separate begin and end markers in the sstable, see https://github.com/scylladb/scylla/wiki/SSTables-3.0-Data-File-Format#range-tombstone-marker
so for an unbound range tombstone, one of them will be missing.

Unbound range tombstones were introduced in version 3 with the `mc` sstable format,
but they can't be accepted until the whole cluster upgraded so if dome nodes still don't support it they should be rejected at the upper layers.

> I mean, what if I wanted to DELETE WHERE ck > 10? Isn't that fully equivalent to DELETE WHERE ck > 10 AND ck < 9999999999999999999999? Isn't that trivial to support?

No, it's not equivalent for all data types.  Some don't have a finite maximum.
How would you represent `WHERE ck > 'some string'`?

**Comment by dekimir** [comment]
> How would you represent `WHERE ck > 'some string'`?

I'd need the notion of infinity, of course.  I presume that's not something the sstable format can support?

Thinking about a better name, how about "symmetrically bounded"?  Meaning, it's either bounded or unbounded on both sides.

**Comment by bhalevy** [comment]
> > How would you represent `WHERE ck > 'some string'`?
> 
> I'd need the notion of infinity, of course. I presume that's not something the sstable format can support?
> 
> Thinking about a better name, how about "symmetrically bounded"? Meaning, it's either bounded or unbounded on both sides.

To me `asymmetrical bounded` tombstone sounds more obscure than `semi-bounded`, but in any case, I'm don't think we have a good enough reason to rename it.

**Comment by dekimir** [comment]
> I'm don't think we have a good enough reason to rename it.

OK, closing.
