### ISSUE TITLE
Create a nodetool command to check CDC streams and regenerate them if needed.

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#6498]
This will be a way to check that CDC streams are correct and repair them in case something went wrong.

**Comment by slivne** [comment]
@haaawk to make it clearer - is this command supposed to run on all the nodes in the cluster / one of the nodes in the cluster ?

**Comment by haaawk** [comment]
One node. If needed, user can run nodetool on selected node or all of them one by one.

**Comment by avikivity** [comment]
Not a bug, not backporting.
