### ISSUE TITLE
lwt: validate `frozen_mutation` schema version against the current schema before replaying locally in `paxos_state::learn`

### ISSUE THREAD

**Issue by ManManson** [scylladb/scylla#6502]
Paxos transactions store mutations in paxos tables in case the 
transaction will need a repair. The mutation is stored using 
frozen_mutation format. However, to deserialize frozen_mutation, one 
needs to have a schema_ptr of the same version.

In the current implementation `paxos_state::learn` function calls 
`mutate_locally` and doesn't check the schema version that is 
stored in the mutation against the current schema version. That could 
possibly lead to availability issues.

Suppose we have an aborted paxos round that managed to succeeded 
in accept stage but then failed for some reason.

If some DDL sneaked in before a subsequent LWT operation on the same 
key is performed (leading to the repair of the previous unfinished 
paxos round) the coordinator should fail during the replay of the 
mutation from the previous paxos round with `schema_mismatch_error`.

But instead, currently we don't get an exception in such case and it 
looks like that the impl silently tries to apply the mutation anyway 
(and even could succeed in case schema's column_mapping changed in a 
compatible way).

So there are at least two basic problems to consider:
 * `paxos_state::learn` shouldn't even try to `mutate_locally` if 
   there is is a schema mismatch.
 * `database::apply` should validate the schema version in 
   the passed `frozen_mutation` argument against the version in the 
   `schema_ptr`.

Faulty behavior can be triggered with the following scylla-dtests:
https://github.com/ManManson/scylla-dtest/tree/feature/paxos_schema_mismatch_test (`TestPaxos.schema_mismatch_test`).

**Comment by gleb-cloudius** [comment]
We should not scatter checks sporadically everywhere. This will just
slow down innocent users. The check should be added at the root of the
problem in the begin_and_repair_paxos() where a mutation we got in in_progress
reply is adopted. We should check that it matches our schema. It is not
clear though what should we do if it does not? Just throwing an
exception will not resolve the situation without admin intervention.


--
			Gleb.

**Comment by gleb-cloudius** [comment]
Same when we try to repair most_recent_commit. We should check that the
schema matches. Here if we no longer have the same schema we can force
read repair and prune old mutation from paxos table.

--
			Gleb.

**Comment by denesb** [comment]
You can use `canonical_mutation` instead, which allows unserializing with a later version of the schema.

**Comment by ManManson** [comment]
Fixed by https://github.com/scylladb/scylla/commit/f893516e55cc9b230c00e7b094d0e4eeb77335b3
