### ISSUE TITLE
rows_entry memory leak

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#651]
Starting from a user-provided core dump, I installed centos:7.0.1406 in docker and scylla-server-0.12 on top of that.

```
(gdb) scylla memory
Used memory:    1226833920
Free memory:             0
Total memory:   1226833920

Small pools:
objsz spansz    usedobj       memory  wst%
    1   4096          0            0   0.0
    1   4096          0            0   0.0
    1   4096          0            0   0.0
    1   4096          0            0   0.0
    2   4096          0            0   0.0
    2   4096          0            0   0.0
    3   4096          0            0   0.0
    3   4096          0            0   0.0
    4   4096          0            0   0.0
    5   4096          0            0   0.0
    6   4096          0            0   0.0
    7   4096          0            0   0.0
    8   4096       5686        53248  14.6
   10   4096          0            0   0.0
   12   4096          0            0   0.0
   14   4096          0         8192  99.8
   16   4096       6811       114688   5.0
   20   4096          0            0   0.0
   24   4096          0            0   0.0
   28   4096       7169       204800   1.8
   32   4096       3445       114688   3.9
   40   4096          0            0   0.0
   48   4096          0            0   0.0
   56   4096       2677       155648   3.5
   64   4096       7428       483328   1.6
   80   4096          0            0   0.0
   96   4096          0            0   0.0
  112   4096       2405       278528   1.7
  128   4096    3029213    387743744   0.0
  160   8192          0            0   0.0
  192   8192          0            0   0.0
  224   8192       1260       286720   0.0
  256   8192    3026880    774881280   0.0
  320  16384          0            0   0.0
  384  16384          0            0   0.0
  448  16384        745       360448   5.8
  512  16384      13670      7012352   0.2
  640  32768          0            0   0.0
  768  32768          0            0   0.0
  896  32768        217       262144  24.3
 1024  32768         58        98304  39.6
 1280  65536          0            0   0.0
 1536  65536          0            0   0.0
 1792  65536        363       720896   8.2
---Type <return> to continue, or q <return> to quit---
 2048  65536         66       196608  31.2
 2560 131072          0            0   0.0
 3072 131072          0            0   0.0
 3584 131072         35       393216  66.5
 4096 131072          3       393216  96.9
 5120 262144          0            0   0.0
 6144 262144          0            0   0.0
 7168 262144         40       786432  62.0
 8192 262144        675      6291456  12.1
10240 524288          0            0   0.0
12288 524288          0            0   0.0
14336 524288         32      1572864  69.3
16384 524288          0      1572864 100.0
Page spans:
index      size [B] free [B]
    0          4096 0
    1          8192 0
    2         16384 0
    3         32768 0
    4         65536 0
    5        131072 0
    6        262144 0
    7        524288 0
    8       1048576 0
    9       2097152 0
   10       4194304 0
   11       8388608 0
   12      16777216 0
   13      33554432 0
   14      67108864 0
   15     134217728 0
   16     268435456 0
   17     536870912 0
   18    1073741824 0
   19    2147483648 0
   20    4294967296 0
   21    8589934592 0
   22   17179869184 0
   23   34359738368 0
   24   68719476736 0
   25  137438953472 0
   26  274877906944 0
   27  549755813888 0
   28 1099511627776 0
   29 2199023255552 0
   30 4398046511104 0
   31 8796093022208 0
```

So all memory is leaked into 300M pairs of objects, sizes 128b and 256b.

Examining a random memory location, I see

```
0x60d019000100:	0x000060d018ffff00	0x000060d019000200
0x60d019000110:	0x000060d019000000	0x0000000000000001
0x60d019000120:	0xc872c0d4a6010000	0x0800000800000001
0x60d019000130:	0x8000000000000000	0x0000000000000000
0x60d019000140:	0x0005260ed4a55560	0x0000000000000000
```

So we have three pointers at the beginning, all the vicinity of 'this' and all similarly aligned -> triply linked list -> `boost::instrusive::set`.

Casting the pointer to `rows_entry` shows that it's indeed a `rows_entry`.

`mutation_partition` has a default move assignment operator, even though that will leak the memory pointed to by `mutation_partition::_rows`.

Testing with cassandra-stress shows that the move assigment operator is not hit, but perhaps a different workload does hit it.

Edit: I wrote `rows_entry` instead of `mutation_partition` in some places, thanks @tgrabiec.

**Comment by tgrabiec** [comment]
@avikivity `rows_entry` has a user-defined move constructor, so implicitly-declared move assignment should be deleted. 

Also, `rows_entry` doesn't have `_rows` field.

**Comment by avikivity** [comment]
Sorry, I meant `mutation_partition::_row` and `mutation_partition`'s move assignment operator (which cannot be deleted, it is used by `mutation_partition`'s (copy) assignment operator.

I'll update the description to match.

**Comment by tgrabiec** [comment]
Why would moving `mutation_partition` leak rows? We need mutation_partition to be movable, eg for LSA migrations.

**Comment by avikivity** [comment]
A move constructor does not, but the default move assignment operator does.  It calls `rows_type`'s default move assignment, which is a simply `boost::intrusive::set`.  Since `bi::set` doesn't own its elements, they are unlinked, not disposed.

**Comment by tgrabiec** [comment]
Right. We could remove the move assignment, it's not used.

**Comment by avikivity** [comment]
It is used indirectly by the copy assignment (`std::swap` uses move assignment).

**Comment by avikivity** [comment]
If copy assignment is not used, then this bug could not have been the source of the oom described above.  I'll try to compile with copy assignment deleted to see.

**Comment by avikivity** [comment]
Disturbingly, it built.  So the real leak is somewhere else.  Maybe a `bi::set::insert()` failed, leaving the entry dangling.

**Comment by tgrabiec** [comment]
`bi::set::insert()` isn't supposed to throw.

**Comment by avikivity** [comment]
No, but it can fail if the key is already there (that isn't supposed to happen either, but it could, if our relational operators are inconsistent).

**Comment by avikivity** [comment]
Although the data in the core doesn't match a single uninserted entry.  It looks like complete trees being leaked, the left_ and right_ pointers have valid data.

**Comment by avikivity** [comment]
Maybe `insert_unique_check` (the first part of `bi::set::insert()`) modifies the node.

**Comment by tgrabiec** [comment]
Are we sure they're leaked and not just occupying cache/memtables? Did you check occupancy of active regions (`logalloc::tracker_instance._impl->_regions`)?

**Comment by avikivity** [comment]
They are in heap memory, not lsa.  See `scylla memory` dump above.  I looked at cache/memory and they are empty, also ~1.2G are in 128b and 256b slabs.

**Comment by avikivity** [comment]
More eyes: @pdziepak

**Comment by avikivity** [comment]
I examined a few hundred random `row_entry` structs in memory.  Their color is always `black_t`.

1. the trees are always so small so that red/black balancing never kicks in
2. insert() prepares the node for linking and fails; the color stuff happens in the commit() part.

**Comment by avikivity** [comment]
I did an extra bit of validation.  The clustering key conforms to `timestamp_type`.  The value (stored in the 128b component) conforms to `tuple<double, int, double, double>`; these are the types in the schema.

**Comment by avikivity** [comment]
I verified that 0.12 also compiles with both `mutation_partition` assignment operators deleted.

**Comment by avikivity** [comment]
I'm wrote a script to walk the tree (and verify its connectivity, check for cycles, etc.)  it's still running, but I can already see it's an order-17 tree, which translates to 50MB (with node size of 256+128).

So it could be that we run out of memory while copying a mutation from cache, get an exception, leak during recovery, evict some cache, and try again.

**Comment by avikivity** [comment]
I also see:
- the clustering keys are all valid and sorted correctly
- the node colors are all black

**Comment by avikivity** [comment]
Script is still running, but at ~ 305k nodes now.  At 384 bytes/node, this is ~110MB.  So 11 such mutations could exhaust a shard's memory.

**Comment by tgrabiec** [comment]
Maybe those are not leaked then but are temporary data needed by active readers?

**Comment by avikivity** [comment]
Yes, that's what I'm thinking.  Once the script is done I will investigate the tree's root.

**Comment by avikivity** [comment]
There are a few red nodes too, so it's possible that the tree is simply well balanced.

**Comment by avikivity** [comment]
total nodes: 614741 (236060544 bytes)
red nodes: 27

**Comment by avikivity** [comment]
nodeaddr: parent left right color clustering key
indent == tree level

[tree-dump.zip](https://github.com/scylladb/scylla/files/61332/tree-dump.zip)

**Comment by avikivity** [comment]
Seems like the root's parent points back at a mutation_partition::data.  So it looks like this mutation is valid, and by itself consumes a significant fraction of the shard's memory.

**Comment by avikivity** [comment]
The root correctly points to the leftmost and rightmost elements.

**Comment by avikivity** [comment]
Conclusion: no leak; but server did not protect itself against overlarge partitions.
