### ISSUE TITLE
LWT throughput dropped in twice on 4.1.rc0 (0760107b9fa) for DELETE and INSERT

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla#6512]
TestId: 5da131c2-5d2e-4b59-85ef-23be3a86c196
Dataset: small

INSERT results:
dropped from 12473.00 (4.0.rc3) to 5488.00
![INSERT](https://user-images.githubusercontent.com/40304587/82882577-73b85a00-9f6b-11ea-914a-0c94ab1fa22f.png)

DELETE results:
IF <condition> - dropped from 12473.00 (4.0.rc3) to 5488.00
IF <exists> - dropped from 12882.00 (4.0.rc3) to 5405.00
![DELETE](https://user-images.githubusercontent.com/40304587/82882560-6c914c00-9f6b-11ea-8922-44c7c9815978.png)

MIXED results:
dropped from 6488 (4.0.rc3) to 5134.00
![MIXED](https://user-images.githubusercontent.com/40304587/82882596-7915a480-9f6b-11ea-9bc9-ce36391b20ac.png)

At the same time UPDATE showed 2-3% improvement.

Latency test also showed regression with same magnituted.

*Installation details*
Scylla version (or git commit hash): 4.1.rc0 (0760107b9fa)
AWS Region: us-west-1
AWS AMI:  ami-082292b8a1dd0b876
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Centos

Table:
CREATE TABLE targettable (
        pr1 timeuuid,
        aux1 int,
        aux2 bigint,
        aux3 double,
        aux4 float,
        aux5 tinyint,
        PRIMARY KEY(pr1)
  ) WITH compaction = { 'class':'SizeTieredCompactionStrategy' }
    AND comment='A test table for cs_lwt_perf_small'

Report:
[Report.zip](https://github.com/scylladb/scylla/files/4681059/Report.zip)

Latency report:
[latency_report.zip](https://github.com/scylladb/scylla/files/4681199/latency_report.zip)

c-s profile:
[c-s.profile.zip](https://github.com/scylladb/scylla/files/4681148/c-s.profile.zip)

Jenkins:
https://jenkins.scylladb.com/job/Perf-Regression/job/scylla-release-perf-regression-aws-lwt-small-throught/4/

**Comment by gleb-cloudius** [comment]
Insert, update and delete have the same throughput which is expected.

**Comment by dkropachev** [comment]
> Insert, update and delete have the same throughput which is expected.
@gleb-cloudius 
Could you explain that, why it is expected to see numbers twice less than on prior version ?

**Comment by gleb-cloudius** [comment]
Didn't we investigated it earlier and found out that during insert unlike during update we had a lot of condition unmet cases? Now both cases met and unmet do the same amount of work.

**Comment by dkropachev** [comment]
@gleb-cloudius , this issue is not about performance difference between update and insert, this issue is about performance degradation in UPDATE and DELETE between scylla versions.

**Comment by gleb-cloudius** [comment]
On Tue, May 26, 2020 at 10:57:52PM -0700, Dmitry Kropachev wrote:
> @gleb-cloudius , this issue is not about performance difference between update and insert, this issue is about performance degradation in UPDATE and DELETE between scylla versions.
> 
The issue is one and the same. The moment met and unmet started to do
the same amount of rounds the difference disappeared and you saw it as a
performance degradation. The reason for both is the same problem in the
test itself.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Wed, May 27, 2020 at 10:14:33AM +0300, Gleb Natapov wrote:
> On Tue, May 26, 2020 at 10:57:52PM -0700, Dmitry Kropachev wrote:
> > @gleb-cloudius , this issue is not about performance difference between update and insert, this issue is about performance degradation in UPDATE and DELETE between scylla versions.
> > 
> The issue is one and the same. The moment met and unmet started to do
> the same amount of rounds the difference disappeared and you saw it as a
> performance degradation. The reason for both is the same problem in the
> test itself.
> 
To clarify (hopefully): due to how the test works the result is expected.

--
			Gleb.

**Comment by dkropachev** [comment]
> On Tue, May 26, 2020 at 10:57:52PM -0700, Dmitry Kropachev wrote: @gleb-cloudius , this issue is not about performance difference between update and insert, this issue is about performance degradation in UPDATE and DELETE between scylla versions.
> The issue is one and the same. The moment met and unmet started to do the same amount of rounds the difference disappeared and you saw it as a performance degradation. The reason for both is the same problem in the test itself.
> […](#)
> -- Gleb.
Why did they started to do the same amount of rounds ?
How to fix the test ?

**Comment by gleb-cloudius** [comment]
On Wed, May 27, 2020 at 06:43:52AM -0700, Dmitry Kropachev wrote:
> > On Tue, May 26, 2020 at 10:57:52PM -0700, Dmitry Kropachev wrote: @gleb-cloudius , this issue is not about performance difference between update and insert, this issue is about performance degradation in UPDATE and DELETE between scylla versions.
> > The issue is one and the same. The moment met and unmet started to do the same amount of rounds the difference disappeared and you saw it as a performance degradation. The reason for both is the same problem in the test itself.
> > […](#)
> > -- Gleb.
> Why did they started to do the same amount of rounds ?
We fixed it. The fact that the did not cause a linearisability issues.

> How to fix the test ?
> 
Ideally each stage should work on a fresh cluster or on different key
ranges.

--
			Gleb.

**Comment by dkropachev** [comment]
@gleb-cloudius , Got it.
