### ISSUE TITLE
Failed compaction : compaction_manager - compaction failed: sstables::malformed_sstable_exception (consumer not at partition boundary

### ISSUE THREAD

**Issue by arunsandu1** [scylladb/scylla#6529]
Cleanup process does not complete for days and compactions are failing.

`2020-05-27T18:40:51.959269+00:00 ip-10-0-70-221 scylla:  [shard 10] compaction_manager - compaction failed: sstables::malformed_sstable_exception (consumer not at partition boundary in sstable /var/lib/scylla/data/kairosdb/data_points-6bb3b390d10911e8871b000000000008/mc-195800-big-Data.db): retrying
2020-05-27T18:40:51.959388+00:00 ip-10-0-70-221 scylla:  [shard 10] compaction_manager - compaction task handler sleeping for 300 seconds
`
This cluster got large partitions issue.

*Installation details*
Scylla version (or git commit hash): 3.2.5-0.20200418.77500f9171
Cluster size: 13 
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 18.04.1

*package versions*

> ii  scylla                             3.2.5-0.20200418.77500f9171-1       amd64        Scylla database metapackage
ii  scylla-conf                        3.2.5-0.20200418.77500f9171-1       amd64        Scylla database main configuration file
rc  scylla-env                         1.3-ubuntu1~bionicppa1              all          language tool for constructing recognizers, compilers etc
ii  scylla-jmx                         3.2.5-20200418.857e433a3a-1         all          Scylla JMX server binaries
ii  scylla-kernel-conf                 3.2.5-0.20200418.77500f9171-1       amd64        Scylla kernel tuning configuration
ii  scylla-python3                     3.7.4-0.20200418.77500f9171-1       amd64        A standalone python3 interpreter that can be moved around different Linux machines
ii  scylla-server                      3.2.5-0.20200418.77500f9171-1       amd64        Scylla database server binaries
ii  scylla-tools                       3.2.5-20200418.09885dc0b3-1         all          Scylla database tools
ii  scylla-tools-core                  3.2.5-20200418.09885dc0b3-1         all          Scylla database tools core files

*Hardware details (for performance issues)*         i3.4xlarge
Platform (physical/VM/cloud instance type/docker): AWS ec2
Hardware: sockets= cores= hyperthreading= memory= 
Disks: (SSD/HDD, count) NVM storage

here is the log from the node where cleanup had issue. 
[scylla.log](https://github.com/scylladb/scylla/files/4691295/scylla.log)

**Comment by slivne** [comment]
@arunsandu1 thanks for reporting - would it be possible for you to share the schema and sstable (mc-195800-big-Data.db) from that specific node so we can try and reproduce/check it in our lab ?

**Comment by bhalevy** [comment]
@denesb / @raphaelsc does it ring a bell?

**Comment by raphaelsc** [comment]
I was thinking this could be due to race condition involving GC writer, but it looks like this problem was triggered while running cleanup and there's no way GC writer could be enabled here. Also, from the logs, it looks like no interposer is enabled.

**Comment by denesb** [comment]
This is from the sstable parser code: https://github.com/scylladb/scylla/blob/97cb2892b28222e680a68cdb210c5fe1770f731d/sstables/partition.cc#L296-L299

**Comment by denesb** [comment]
@arunsandu1 would it be possible for us to get the sstable and the schema?

**Comment by slivne** [comment]
@arunsandu1 thanks for reporting - would it be possible for you to share the schema and sstable (mc-195800-big-Data.db) from that specific node so we can try and reproduce/check it in our lab ?

**Comment by denesb** [comment]
I will cook a patch to resolve that FIXME, so next time we will have some more context.

**Comment by arunsandu1** [comment]
@slivne here is the schema. 
`CREATE TABLE kairosdb.data_points (
    key blob,
    column1 blob,
    value blob,
    PRIMARY KEY (key, column1)
) WITH COMPACT STORAGE
    AND CLUSTERING ORDER BY (column1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';`

mc-195800-big-Data.db sstable does not exist. is there anything else I could help with?

**Comment by bhalevy** [comment]
> @slivne here is the schema.
> 
> ```
> CREATE TABLE kairosdb.data_points (
>     key blob,
>     column1 blob,
>     value blob,
>     PRIMARY KEY (key, column1)
> ) WITH COMPACT STORAGE
>     AND CLUSTERING ORDER BY (column1 ASC)
>     AND bloom_filter_fp_chance = 0.01
>     AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
>     AND comment = ''
>     AND compaction = {'class': 'SizeTieredCompactionStrategy'}
>     AND compression = {}
>     AND crc_check_chance = 1.0
>     AND dclocal_read_repair_chance = 0.1
>     AND default_time_to_live = 0
>     AND gc_grace_seconds = 864000
>     AND max_index_interval = 2048
>     AND memtable_flush_period_in_ms = 0
>     AND min_index_interval = 128
>     AND read_repair_chance = 0.0
>     AND speculative_retry = '99.0PERCENTILE';
> ```
> 
> mc-195800-big-Data.db sstable does not exist. is there anything else I could help with?

Thanks @arunsandu1. I assume that (regular) compaction was finally able to compact this sstable so it is possible that the problem was transient, rather than in the sstable itself.

Can you please grep the log for messages mentioning the sstable? (`kairosdb/data_points-.*/mc-195800-big-Data.db`)

Also, if you hit the issue again with a different sstable, please send the schema and sstable for it.

**Comment by arunsandu1** [comment]
thanks @bhalevy . here is the new schema, enabled compression and tried to compact. During cleanup operation we hit the same issue.

`2020-06-18T22:39:25.628486+00:00 ip-10-0-67-243 scylla:  [shard 4] compaction_manager - compaction failed: sstables::malformed_sstable_exception (consumer not at partition boundary in sstable /var/lib/scylla/data/kairosdb/data_points-6bb3b390d10911e8871b000000000008/mc-13394-big-Data.db): retrying`

`CREATE TABLE kairosdb.data_points (
    key blob,
    column1 blob,
    value blob,
    PRIMARY KEY (key, column1)
) WITH COMPACT STORAGE
    AND CLUSTERING ORDER BY (column1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';`

**Comment by arunsandu1** [comment]
Here is the log from 3 different nodes along with the sstable size.

`2020-06-18T22:39:25.628486+00:00 ip-10-0-67-243 scylla:  [shard 4] compaction_manager - compaction failed: sstables::malformed_sstable_exception (consumer not at partition boundary in sstable /var/lib/scylla/data/kairosdb/data_points-6bb3b390d10911e8871b000000000008/mc-13394-big-Data.db): retrying
37G	mc-13394-big-Data.db
2020-06-18T23:06:12.180450+00:00 ip-10-0-69-114 scylla:  [shard 5] compaction_manager - compaction failed: sstables::malformed_sstable_exception (consumer not at partition boundary in sstable /var/lib/scylla/data/kairosdb/data_points-6bb3b390d10911e8871b000000000008/mc-13105-big-Data.db): retrying
39G	mc-13105-big-Data.db
2020-06-18T23:12:49.022464+00:00 ip-10-0-69-0 scylla:  [shard 1] compaction_manager - compaction failed: sstables::malformed_sstable_exception (consumer not at partition boundary in sstable /var/lib/scylla/data/kairosdb/data_points-6bb3b390d10911e8871b000000000008/mc-25781-big-Data.db): retrying
43G	mc-25781-big-Data.db`

**Comment by slivne** [comment]
@bhalevy ping

**Comment by slivne** [comment]
@bhalevy ping

**Comment by slivne** [comment]
@bhalevy ping

**Comment by bhalevy** [comment]
@denesb let's try to reproduce this issue with a dtest

**Comment by denesb** [comment]
@bhalevy I'll first try to reproduce with the update sstables.

**Comment by denesb** [comment]
@arunsandu1 do you still see the error happening? If yes could you please upload another sstable, this time with all the components (not just `*-Data.db`)? Thanks.

**Comment by slivne** [comment]
4.3 will have the additional debugging information.

I am closing this issue as its stale

@arunsandu1 - if you do have additional information it would be great if you can share it and we will reopen and continue

**Comment by zooptwopointone** [comment]
I have also run into something like this.  Cluster info:
Scylla version 4.2.1-0.20201108.4fb8ebccff with build-id d19a95fd85a8e7df2928ccd8c729941f263e8adc
Cluster size: 4 Datacenters (3 x 3 nodes 1 x 7 nodes)
OS (RHEL/CentOS/Ubuntu/AWS AMI): 18.04.5 LTS (GNU/Linux 4.15.0-128-generic x86_64)

Platform (physical/VM/cloud instance type/docker): Physical
Hardware: sockets= 2 cores=8 hyperthreading= 32 memory= 128 GB
Disks: (SSD/HDD, count) 8 SSD


I need to run the command again, but this happens to me when running a repair or compact.    I was just looking into it more to see what level of concern I should have for this.  There are a few tables I have that seem to never be able to repair successfuly.  but that is for another Issue.

This is the generic part of the log:
`[shard 1] storage_proxy - Exception when communicating with 172.21.8.50, to read from keyspace.contact: std::runtime_error (consumer not at partition boundary in sstable /var/lib/scylla/data/.......`

Let me know what other information I can provide.
