### ISSUE TITLE
Social & project banners

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#6538]
@penberg can you pls add nice banners (or alike) to the ones that this project has:
https://github.com/openebs/openebs

Twitter, Slack, CI,all of them are good options.

**Comment by penberg** [comment]
I sent a patch to add Slack and Twitter banners. Our CI is unfortunately not public, so there's no link to add for that.

Please note that one issue that's the top-level of the git repository is cluttered with source files, which makes the README.md hard to discover on Github. You have to scroll all the way down to find it.
