### ISSUE TITLE
Scylla_setup does warns about swap, but not help to set it correctly

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#6539]
Scylla version (or git commit hash): 4.0

Installing Scylla ion AWS i3 add the following warning:
**No swap is configured, it is highly recommended to setup swap on Scylla node.**

It is not clear what one should do next, if at all.
A better  UX will either:
- guide the user on fixing this 
- Add this as a step in scylla_setup (better)

**Comment by avikivity** [comment]
This is a feature, not a bugfix, so not backporting.

**Comment by dyasny** [comment]
This is going to be VERY useful for the cloud (among other places), can we ask for a backport to enterprise as soon as possible @slivne ?

**Comment by slivne** [comment]
Cloud already adds swap to machines.

AMI still doesn't have support for this.

It will make its way into Enterprise AMIs at some point.
