### ISSUE TITLE
Automatic validation of published AMI, RPMs and DEBs

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#654]
http://www.scylladb.com/download/
Includes links to downloadable Scylla artifacts and AMI.
This artifacts may have different problems:
- wrong / broken links - links to a non existing artifact or to the wrong versions.
- wrong / broken AMI
- private AMI or private RPMs
- RPM itself downloadable but broken

The same for DEBs, Docker etc.
It is desirable, all of the above will be tested automatically, as possible, as part of the release publishing process.

**Comment by lmr** [comment]
This has been implemented already, and running on jenkins on every artifact build. The test uses http://avocado-framework.github.io/ and https://github.com/lmr/scylla-artifact-tests.

@slivne and @tzach, please let me know if you need any extra information to close this.

**Comment by tzach** [comment]
The original issue was about validating the install process, starting from the link in the download page

**Comment by lmr** [comment]
A part of the work was implemented in scylla-artifact-tests. About validating the link in the download page, that sounds like a fairly manual process (although it could be automated with some web page scraping, or, better, selenium tests).
