### ISSUE TITLE
repair_option_pr_dc_host_test fails in debug mode: seastar::named_semaphore_timed_out

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6548]
Seen since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/492/testReport/junit/repair_additional_test/RepairAdditionalTest/repair_option_pr_dc_host_test/
Scylla version c4bbeb80dbd867b565e96e7fdc8a86abc4c90672

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/492/artifact/logs-debug.2/1590890039856_repair_additional_test.RepairAdditionalTest.repair_option_pr_dc_host_test/node1.log
```
INFO  2020-05-31 01:53:40,574 [shard 0] storage_service - Node 127.0.7.6 state jump to normal
INFO  2020-05-31 01:53:40,623 [shard 0] storage_service - Remove node 127.0.7.6 from pending replacing endpoint
INFO  2020-05-31 01:53:40,785 [shard 1] compaction - Compacting [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-g3jvcvp9/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-155-big-Data.db:level=0, /jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-g3jvcvp9/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-153-big-Data.db:level=0, ]
INFO  2020-05-31 01:53:41,277 [shard 1] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-g3jvcvp9/test/node1/data/system/peers-37f71aca7dc2383ba70672528af04d4f/mc-157-big-Data.db:level=0, ]. 90730 bytes to 79697 (~87% of original) in 470ms = 0.16MB/s. ~256 total partitions merged to 3.
ERROR 2020-05-31 01:53:49,146 [shard 0] storage_proxy - Exception when communicating with 127.0.7.1: seastar::named_semaphore_timed_out (Semaphore timed out: _system_read_concurrency_sem)
...
```

same issue in:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/493/testReport/repair_additional_test/RepairAdditionalTest/repair_option_pr_multi_dc_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/493/testReport/repair_additional_test/RepairAdditionalTest/repair_option_pr_dc_host_test/

**Comment by slivne** [comment]
@bhalev could this be related to @denesb patch merged 0c6bbc84cd30df1c46a6cd81d87170b99d5a8144

**Comment by slivne** [comment]
Is this a regression ?

**Comment by denesb** [comment]
Maybe https://github.com/scylladb/scylla/commit/0c6bbc84cd30df1c46a6cd81d87170b99d5a8144 uncovered that some repair-related reads are done under the system group.

**Comment by bhalevy** [comment]
> Maybe [0c6bbc8](https://github.com/scylladb/scylla/commit/0c6bbc84cd30df1c46a6cd81d87170b99d5a8144) uncovered that some repair-related reads are done under the system group.

@denesb I think you're right.

I saw the following errors during shutdown.  Do you think it's the same issue, or a diffrent one (that could be related)?

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/497/artifact/logs-debug.2/1591253897798_repair_additional_test.RepairAdditionalTest.repair_option_pr_multi_dc_test/node6.log
```
WARN  2020-06-04 06:36:03,117 [shard 0] seastar - Exceptional future ignored: exceptions::mutation_write_failure_exception (Operation failed for system.local - received 0 responses and 1 failures from 1 CL=ONE.), backtrace:   /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/97cb2892b28222e680a68cdb210c5fe1770f731d/scylla//opt/scylladb/libreloc/libasan.so.6+0x45bad
  0x16a7426f
  0x16a72723
  0x15c0fb77
  0xcd806e9
  0xcd56688
  0xd515be8
  0xd5e2086
  0xd65ad75
  0xd5fad8f
  0xd6f3524
  0xd6b07bb
  0xd72431d
  0xcfda8a0
  0xcf38915
  0xcfda95e
  0xcf3841b
  0xd36a079
  0x15d720f6
  0x15d76167
  0x15d7b3b2
  0x15b91b0d
  0x15b8fa9b
  0xccfdcf4
  /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/97cb2892b28222e680a68cdb210c5fe1770f731d/scylla//opt/scylladb/libreloc/libc.so.6+0x27041
  0xccb369d

WARN  2020-06-04 06:36:03,118 [shard 0] storage_service - Fail to pull schema from 127.0.31.5: seastar::rpc::closed_error (connection is closed)
INFO  2020-06-04 06:36:03,437 [shard 1] compaction - Compacted 2 sstables to [/jenkins/workspace/scylla-master/dtest-debug/scylla/.dtest/dtest-x86_uydi/test/node6/data/system_schema/keyspaces-abac5682dea631c5b535b3d6cffd0fb6/mc-85-big-Data.db:level=0, ]. 122439 bytes to 61434 (~50% of original) in 7611ms = 0.01MB/s. ~256 total partitions merged to 5.
ERROR 2020-06-04 06:36:03,445 [shard 1] system_keyspace - update compaction history failed: exceptions::mutation_write_failure_exception (Operation failed for system.compaction_history - received 0 responses and 1 failures from 1 CL=ONE.): ignored
```

**Comment by denesb** [comment]
@bhalevy I think this is something different. The query classifying changes should not affect writes (unless they do a read-before-write).

**Comment by denesb** [comment]
I cannot reproduce locally, probably because I have a much faster/less congested disk than whatever dtests run on. I do see tons of scans to `system_auth.roles` that run in the `main` group (and hence uses the system semaphore). This table is created by `auth` using normal DDL statements, which means scylla considered it to be a user table before, and hence queries to it would use the user semaphore.

**Comment by denesb** [comment]
There are ~7K scans of `system_auth.roles`, over the course of 6 seconds, all on shard 0.

**Comment by denesb** [comment]
The queries seems to be legit, they are generated by auth on initializing. Also, we don't have 7k queries, this is just the range-scan algorithm dividing a scan into vnode chunks, with increasing concurrency.

The auth subsystem seems to use a hardcoded timeout of 5s for distributed queries. A solution would be to make this configurable, and bump it to a bigger value for dtests.

**Comment by denesb** [comment]
I also proposed a solution to improve range scans on empty and near-empty tables, such as `system_auth.roles`: https://github.com/scylladb/scylla/issues/6599.

**Comment by avikivity** [comment]
If those are system queries, then they should not time out, should they?

**Comment by avikivity** [comment]
Ah, distributed queries must have a timeout. Still, why are we issuing so many?

**Comment by denesb** [comment]
On Sun, Jun 7, 2020, 19:02 Avi Kivity <notifications@github.com> wrote:

> If those are system queries, then they should not time out, should they?
>

These are distributed queries. Should those have no timeout either (I don't
know what the other distributed system queries do). The auth code
explicitely uses timeouts and is prepared for a failure.

**Comment by denesb** [comment]
On Sun, Jun 7, 2020, 19:07 Avi Kivity <notifications@github.com> wrote:

> Ah, distributed queries must have a timeout. Still, why are we issuing so
> many?
>

There isn't a lot, the replicas see a lot of reads due to our scan
algorithm's very high parallelism on near empty tables.

**Comment by bhalevy** [comment]
It seems like this timeout is benign and may becaused just by general debug-mode slowness against the hard coded timeout.
Let's ignore this log message in the tests then.

**Comment by denesb** [comment]
@bhalevy we need to be careful on what messages we ignore exactly. Semaphore timeouts can indicate genuine problems. Since be452b1f912aa3fa45af7a7bca142ab09d11c450 these error messages will also include the keyspace and table name, so we should only ignore those semaphore/keyspace/table combinations that we know are indeed benign.

**Comment by denesb** [comment]
Duplicate of https://github.com/scylladb/scylla/issues/6908, we can close it.

**Comment by bhalevy** [comment]
Closing as duplicate of #6908
