### ISSUE TITLE
cdc: report unexpected exceptions using "error" level in generation management code

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#6557]
When a node sees in gossip that a new CDC generation has appeared, it will try to retrieve the generation data from distributed system tables (`system_distributed.cdc_topology_description`).

The attempt may fail due to e.g. a network partition. It would then report something like UnavailableException or Timeout in the log using the WARN level, and schedule a background process to retry the retrieval. The idea is that eventually, after the partition resolves, the node will retrieve the data.

The relevant functions are: `storage_service::handle_cdc_generation` and `storage_service::async_handle_cdc_generation`.

This behavior might hide bugs, unfortunately. For example, if due to a bug the `cdc_topology_description` table is corrupted, no node will ever be able to retrieve the data, and the exception could be something like `read_simple_exactly - size mismatch`. See, e.g., https://github.com/scylladb/scylla/issues/6537.

For this class of unexpected errors, we should:
- report the error using the ERROR level (instead of WARN), so that these problems will get noticed in tests and tests will fail,
- NOT schedule a retry, but finish the retrieval procedure.

**Comment by avikivity** [comment]
@nyh please evaluate for a backport

**Comment by nyh** [comment]
CDC is still not GA and changing quickly, and this is not a bugfix,  so no need to backport this.
