### ISSUE TITLE
Question about read performance

### ISSUE THREAD

**Issue by dimaqq** [scylladb/scylla#6559]
I'm testing ScyllaDB in a single container on mac, all default settings.

My table definition looks like this:
```cql
CREATE TABLE foo (
    h ASCII,
    r ASCII,
    ... 34 more columns ...
    PRIMARY KEY (h, r)
)
WITH CLUSTERING ORDER BY (r ASC)
```

On purpose, the dataset has a long tail, it has many small and few huge partitions:
* total partitions (distinct `h` values): ~220
* smallest partitions: ~1 row, largest ~50% of the dataset
* total data: ~70K rows, ~54MB data size (values as strings)
* largest partition: ~35K rows, ~29MB data size

Here are the results for "select all":
* `SELECT * FROM foo` takes 26s and returns ~70K rows
* `SELECT * FROM foo WHERE h = %s` (largest partition) takes 1.2s and returns ~35K rows

I'm curious why there's approximately ten-fold difference in throughput between the two.

**Comment by avikivity** [comment]
Please ask questions on the mailing list, where more people will see the answers.

In small datasets, when moving between partitions, scylla also has to move between shards often. A single partition is always in a single shard, so this overhead is avoided.

With a large dataset, scylla still has to move between shards, but not very often, so the overhead is negligible.
