### ISSUE TITLE
Make mutation readers slice based on clustering range

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#656]
So that they can return smaller mutations. If partitions are large, copying whole partitions is very wasteful and may easily exhaust memory. Readers should be given access to clustering range from query so that they can produce smaller temporary objects.

**Comment by avikivity** [comment]
Can slice columns too, or pass other filters.

**Comment by slivne** [comment]
@avikivity do we need this for GA given that many users have large partitions

**Comment by avikivity** [comment]
No, it's an optimization only.

**Comment by nosideeffects** [comment]
Would this affect the performance of streaming an entire large partition with a small fetch size?

**Comment by avikivity** [comment]
Yes, very much.

**Comment by nosideeffects** [comment]
Then this might be a must have (for us) before we can swap out our clusters.

**Comment by avikivity** [comment]
Probably; unless you can fetch the entire partition in one go (and disable paging).

**Comment by nosideeffects** [comment]
I would have to test it out, but I fear we might need to increase the read timeout too much. Our partitions are generally > 1GB, >100k rows. In order to avoid completely overwhelming the GC in Cassandra we've had to both increase the timeouts and decrease fetch size to 500.
