### ISSUE TITLE
cdc: failed to restore cdc log table from snapshot for postimage enabled only with refresh operation

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#6561]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200530.0c6bbc84cd3 with build-id 2d1467d0fd54ded4cae64f3b4d50fa7b6a9dd690
Cluster size: 1

base table was configured with cdc and postimage: enabled only.
Base table is populated with some data, then rows are deleted with DELETE operation, and new data is inserted again
After that snapshot for keyspace is created.

Restoring cdc log table from snapshot if cdc log table contains DELETE operations, cause dtest failing with next error in scylla file log
```
AssertionError: Unexpected errors found: [('node1', ['ERROR 2020-06-01 20:16:47,781 [shard 1] storage_proxy - Exception when communicating with 127.0.3.1: sstables::malformed_sstable_exception (non-null component after null component in sstable /.dtest/dtest-_jggvml7/test/node1/data/ks/cf_scylla_cdc_log-c703fc42a44411eaa155000000000001/mc-3-big-Data.db)'])]
```
or
```
AssertionError: Unexpected errors found: [('node1', ['ERROR 2020-06-01 20:12:54,599 [shard 1] storage_proxy - Exception when communicating with 127.0.29.1: sstables::malformed_sstable_exception (end of input, but not end of partition)'])]
```

test is here: https://github.com/aleksbykov/scylla-dtest/blob/restore_snapshot_cdc_log_table/cdc_snapshot_operation.py

failing tests:
- cdc_snapshot_operation.py:CDCSnapshotOperationTest.test_create_snapshot_with_collection_type_with_base_rows_delete_postimage
- cdc_snapshot_operation.py:CDCSnapshotOperationTest.test_create_snapshot_with_native_type_with_base_rows_delete_postimage

**Comment by aleksbykov** [comment]
Here is a link to dtest result:
https://jenkins.scylladb.com/job/scylla-master/job/byo/job/dtest-byo/173/testReport/

**Comment by slivne** [comment]
@haaawk malformed_sstable_exception is alarming - can you check if this is a CDC or sstable issue if its sstable issue we will reassign to @bhalevy

**Comment by elcallio** [comment]
There is a missing pre-image check in the row deletion code in log.cc. I've sent a patch fixing it.

**Comment by haaawk** [comment]
> There is a missing pre-image check in the row deletion code in log.cc. I've sent a patch fixing it.

Thanks @elcallio

**Comment by avikivity** [comment]
@nyh please evaluate for a backport

**Comment by avikivity** [comment]
@nyh ping

**Comment by nyh** [comment]
Looks like a bug fix that should be backported, but I need to check now which of the version branches actually includes the relevant code - this CDC code has been moving quickly.

**Comment by nyh** [comment]
This relatively-old patch is already in branch-4.2.
Backported to next-4.1 - commit 07b7df9171e5cd6b75efaa4cc8dad086be2e1e89
Backported to next-4.0 - commit 3ee854f9fcc584a28a26a26bc0e81a5475c0539d
