### ISSUE TITLE
Alternator: should output empty map, not empty JSON

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#6568]
This is an issue raised in the past by @tzach and now discovered again by @fruch by running a real application which runs on DynamoDB:

Currently, a `PutItem` request returns an empty response (it is empty because #5027 hasn't been done yet). However, this empty response is output as a completely empty string, which is wrong - it should be an empty map, "{}".  The DynamoDB documentation https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Programming.LowLevelAPI.html shows that the output should be a map, wrapped in "{" and "}", not bare items, so the empty map should look the same.

@fruch says that the JSON parser (which the application uses) doesn't translate the empty string we return to empty map as we would have liked.

**Comment by avikivity** [comment]
Backported to 4.0, 4.1.
