### ISSUE TITLE
Alternator: missing UnprocessedKeys/Items attribute in BatchGetItem/WriteItems result

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#6569]
Issue discovered by @fruch by running code from https://github.com/pynamodb/PynamoDB/tree/master/examples:

The response of the `BatchGetItem` and `BatchWriteItems` requests is supposed to contain a `UnprocessedKeys` and `UnprocessedItems` attribute, respectively. Currently Alternator always processes all the keys/items (see issue #5944) but still, the DynamoDB documentation (https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html and https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html) explicitly state that if there are no unprocessed keys remaining, the response contains an empty  UnprocessedKeys/ UnprocessedItems map.

Alternator fails to add this empty map, and client code like the one @fruch saw which just assumes that this attribute exists in the response, can break.

**Comment by avikivity** [comment]
Backported to 4.0, 4.1.
