### ISSUE TITLE
3 io operation per read instead of possible 2

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla#657]
We ran read only stress scenario with 0% cache hit, it seems the average IO to disk was 3 per key instead of possible 2 IO

Scylla Cluster:
Nodes: 1
Server Type: Rackspace - OnMetal IO v1
Total Keys: 60M
Columns: 5 field, each value size is 2kb (Total row 10kb)

Stress Tools:
Machines: 3
Server Type: Rackspace - OnMetal IO v1
Test: Read, with sequence of 20M keys each

Stress command:
cassandra-stress read cl=ONE n=20000000 -mode native cql3 -rate threads=300 -node $SERVERS -pop seq=1..20000000 -col 'size=FIXED(2048) n=FIXED(5)'

**Comment by avikivity** [comment]
@glommer shouldn't a single-key read require two I/Os? one for the index and one for the data?

**Comment by nyh** [comment]
Just a silly question - is the data uncompressed, or compressed? With
compressed data, we need to read quite a bit more than really needed (but I
don't know how you count "one I/O").


--
Nadav Har'El
nyh@scylladb.com

**Comment by glommer** [comment]
On Mon, Dec 14, 2015 at 7:29 AM, Avi Kivity <notifications@github.com>
wrote:

> @glommer <https://github.com/glommer> shouldn't a single-key read require
> two I/Os? one for the index and one for the data?
>

I think we are generating an extra read to find out where the row ends so
we can issue a read for the whole row at once.
Ideally we would have the size information in the format so we don' t need
to do this, but even with the current format, we
could probably try to remove that read by reading a whole 128k buffer and
if it is too much it is too much.

For really small rows (<= 4K)  the two reads could still be faster
(depending on the disk), since the latency for a 4K operation will be around
100 usec, while a larger read could put us at more than twice as that.
(assuming 500MB/s with a ~ 60usec base).

That is probably the case, BTW, for the default C*-stress read load. So
while we are generating an extra IO op, I am not sure that
this is making us slower. Is there any reason to believe that to be the
case?

**Comment by tgrabiec** [comment]
@glommer Could we get the size from the index by looking where the next key starts?

**Comment by nyh** [comment]
On Mon, Dec 14, 2015 at 6:31 PM, Glauber Costa <notifications@github.com>
wrote:

> On Mon, Dec 14, 2015 at 7:29 AM, Avi Kivity <notifications@github.com>
> wrote:
>
> > @glommer <https://github.com/glommer> shouldn't a single-key read
> require
> > two I/Os? one for the index and one for the data?
> >
>
> I think we are generating an extra read to find out where the row ends so
> we can issue a read for the whole row at once.
>

But we don't need two reads for that - we just need to read two consecutive
index entries for that - and "usually" reading one block of indexes will
have the two indexes.

In this test, how do we define what a single "read" is? Could it be that
reading a block of index entries is counted as two reads? Could it be that
reading a compressed block (which can be fairly large, around 32-64 KB)
counts as two reads?

Do you know if the data file is compressed or not (I think compression *is*
used by default, right)?


That is probably the case, BTW, for the default C*-stress read load. So
> while we are generating an extra IO op, I am not sure that
> this is making us slower. Is there any reason to believe that to be the
> case?


I still don't understand how these IOPS are counted, and where they come
from. So before coming to any conclusions, we should probably figure that
out.

**Comment by glommer** [comment]
Tomasz,

That is what we do, but in the worst case the next key may require a
separate read since we always read the index in 128-entries chunks.

If we are really averaging 3 reads per key that won't be the relevant
factor.

**Comment by avikivity** [comment]
The counter is reactor::_aio_reads.  And no, I don't think the data is compressed.

**Comment by avikivity** [comment]
I saw 1500 cql ops/shard and 4500 aio reads/shard.

**Comment by avikivity** [comment]
It could also be that we're reading one key from one sstable, and another key from two sstables, each time incurring two reads/sstable.  So 4+2 reads / 1+1 ops = 3 reads/op on average.

**Comment by tzach** [comment]
@avikivity as performance optimization its not urgent for GA.
Any objection pushing it for after GA?

**Comment by avikivity** [comment]
No objection.

**Comment by nyh** [comment]
I did a small test which contradicted the complaint here: I see only two reads (one from index, one from data file) per query:

I filled a bunch of data with cassandra-stress (on two nodes, RF=2, just for the heck of it), then connected with cqlsh and ran `SELECT * from keyspace1.standard1` and scrolled down a bunch of screens and picked one of the keys at random. Then I restarted scylla (to clear the cache), attached strace to it and ran in cqlsh `SELECT * from keyspace1.standard1 where key = 0x34363232384f4c4f3631;`.

I grepped for io_submit and found exactly two reads - one for the data file, one for the index file. Each sometimes 4096 bytes and sometimes 8192 bytes (I am guessing we get 8192 when the range happens to cross the alignment border). We can figure out which fd refers to which file by listing /proc/<process-id>/fd while scylla is still running.

I ran this several times, and each time I got just two reads, not three.

So at this point I think Avi's guess (that it's simply a case of several sstables being read) is the remaining option, and is benign (this issue should probably be closed).

**Comment by avikivity** [comment]
I think this is fixed now.

**Comment by tzach** [comment]
@noamha can you please validate this?

**Comment by noamha** [comment]
Tested again, this time there were 2 disk io per each read.

Scylla configuration:
- Scylla 1.5
- Single i2.8xlarge node

Loader:
- Single i2.8xlarge node

Stress for write:
```
cassandra-stress write n=1 cl=ALL -schema "replication(factor=1)" -mode native cql3 -node $SERVERS
	cassandra-stress write cl=QUORUM n=60000000 -mode native cql3 -rate threads=300 -node $SERVERS -pop seq=1..60000000 -col 'size=FIXED(2048) n=FIXED(5)'
```

Restarted Scylla and ran the following stress for read:
```
cassandra-stress read cl=ONE n=20000000 -mode native cql3 -rate threads=300 -node $SERVERS -pop seq=1..20000000 -col 'size=FIXED(2048) n=FIXED(5)'
```

- There were 50K reads per second
- There were 0 cache hits
- Both iostats and Scylla Grafana dashboard shows around 100K disk ops per second

```

**Comment by tzach** [comment]
Thanks @noamha 
Closing this issue then
