### ISSUE TITLE
Scylla crashes when CDC Log is queried with a wrong stream_id

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#6570]
Executing:
`select * from tb_scylla_cdc_log where "cdc$stream_id" = 0x00;`

causes: 

```
scylla: cdc/generation.cc:84: int64_t cdc::bytes_to_int64(bytes_view, size_t): Assertion `b.size() >= offset + sizeof(int64_t)' failed.
```

**Comment by avikivity** [comment]
Backported to 4.1.

**Comment by avikivity** [comment]
(since CDC is still experimental, not backporting too far back).

**Comment by haaawk** [comment]
Wouldn't a crash of the whole node be a good enough reason to get the fix backported @avikivity ? I understand that CDC is experimental but if we refuse to backport even the most critical fixes then how do we want to get early adopters?

**Comment by avikivity** [comment]
It's backported to 4.1, so early adopters have a way to consume it.
