### ISSUE TITLE
Refuse to run without xfs

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#658]
Performance without xfs can be very bad; we should refuse to run without it.

For development/docker/masochists we can add a --allow-bad-aio-implementation command line parameter.

**Comment by tzach** [comment]
> For development/docker/masochists we can add a --allow-bad-aio-implementation command line parameter.

Since we do publish Scylla docker image, the parameter is a must

**Comment by avikivity** [comment]
It's mandatory anyway, because not all developers have xfs installed.
