### ISSUE TITLE
"test_schema_digest_does_not_change" and friends are not specific enough

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#6582]
During rolling upgrade nodes are partitioned into two subsets
- the nodes that are already upgraded,
- and the nodes that are still running the old version.
Rolling upgrade is a process in which the DB admin moves nodes from the second subset to the first, one by one.

The following tests:
- `test_schema_digest_does_not_change`,
- `test_schema_digest_does_not_change_after_computed_columns`,
- `test_schema_digest_does_not_change_with_functions`
-  and `test_schema_digest_does_not_change_with_cdc_options`

defined in test/boost/schema_change_test.cc have one job: ensure that rolling upgrade doesn't fail due to schema disagreement between the upgraded nodes and the rest.

The `test_schema_digest_does_not_change` test works as follows (simplified description). There is a set of pregenerated sstables:
```
$ ls test/resource/sstables/schema_digest_test
commitlog.dir  hints.dir  ks  system  system_auth  system_distributed  system_schema  tests  view_hints.dir
```
e.g.
```
$ ls test/resource/sstables/schema_digest_test/system_schema/
aggregates-924c55872e3a345bb10c12f37c1ba895        indexes-0feb57ac311f382fba6d9024d305702f        types-5a8b1ca866023f77a0459273d308917a
columns-24101c25a2ae3af787c1b40ee1aca33f           keyspaces-abac5682dea631c5b535b3d6cffd0fb6      views-9786ac1cdd583201a7cdad556410c985
computed_columns-cc7c7069374033c192a4c3de78dbd2c4  scylla_tables-5d912ff1f7593665b2c88042ab5103dd  view_virtual_columns-08843b6345dc3be29798a0418295cfaa
dropped_columns-5e7583b5f3f43af19a39b7e1d6f5f11f   tables-afddfb9dbc1e30688056eed6c302ba09
functions-96489b7980be3e14a70166a0b9159450         triggers-4df70b666b05325195a132b54005fd48
```
The test starts a Scylla node using these sstables and a subset of services defined by `cql_test_env`. Then it calculates a hash based on the contents of tables inside the `system_schema` keyspace (these hashes are called digests). Finally, it compares the hash to a hard-coded value.

If the contents of `system_schema` tables when the test runs are different from what was there in a previous version, the test errors out. For example, if the new version creates a new table, a new row will appear inside `system_schema.tables` which will cause the digest to be different.

Unfortunately, the test reports as bugs things that are not actually bugs.

For example, a new version of Scylla may decide to create a new distributed table (for internal use) or even a new keyspace. This table/keyspace is then announced to another nodes through migration_manager (`announce_new_column_family`) so other nodes pull the table's definition and synchronize, even though they are running an old version.

Or a new version of Scylla may use a new local table *which is not included in schema digest calculation*, which means that it won't cause a schema digest mismatch.

Because creating tables adds new rows to `system_schema.tables`, and the contents of these table are included in the schema digest calculation, which causes the digest to be different and the test reports an error. But that doesn't mean there will be a schema digest during upgrade: in fact there won't, as explained above.

So the test is not specific enough, i.e. it has false positives.

The test in fact predicts that there are going to be new system tables added in new versions, such that the new tables won't cause a schema disagreement. Thus it provides a flag with the following comment:
```
    // NOTICE: Regenerating data for this test may be necessary when a system table is added.
    // This test uses pre-generated sstables and relies on the fact that they are up to date
    // with the current system schema. If it is not, the schema will be updated, which will cause
    // new timestamps to appear and schema digests will not match anymore.
    const bool regenerate = false;
```

But that's not very elegant and may cause bugs to be introduced by accident, e.g. if the developer commits a change which does add a new distributed table (safe), but at the same time adds a new local table which is included in schema digest calculation (unsafe unless protected by a feature flag).

---

Suggestion:
the test shouldn't complain when new tables appear that are distributed (and announced to other nodes through the migration manager). Or when new tables appear that are local but not included in schema digest calculation. Maybe contents of `system_schema.tables` and `system_schema.columns` should not be included into the digest calculation, at least for the purpose of the test? But this may cause the test to lose accuracy. Maybe there's a better solution.

@tgrabiec @psarna what do you think?

**Comment by tgrabiec** [comment]
The test was supposed to catch accidental changes of the hash, not caused by changing the schema. If you change the schema, the digest is expected to change, and you need to re-generate the test data. That's by design. 

If the test wouldn't fail if the schema digest changes, it would lose its accuracy. For example, if we'd ignore new tables as you suggested, then unintended changes in the digest of those tables would be ignored.

To test that a rolling upgrade works (digest converges) in case the system schema changes, we need to actually run two different versions of scylla, and that cannot be done in a unit test.

**Comment by kbr-** [comment]
Thanks @tgrabiec , that explains a lot.
And it means my suggestion is just completely wrong.

I'm gonna send a PR adding a comment which explains this test in more detail.
