### ISSUE TITLE
Alternator https port not working with docker

### ISSUE THREAD

**Issue by janknieling** [scylladb/scylla#6583]
*Installation details*
Scylla version (or git commit hash): 4.0.1
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu (Docker)

Hi,

I would like to use ScyllaDB Alternator with https/tls support. If I try to pass the argument/command "--alternator-https-port=XXX2" to the container via docker compose I will receive the following error:

`docker-entrypoint.py: error: unrecognized arguments: --alternator-https-port=XXXX2
usage: docker-entrypoint.py [-h] [--developer-mode {0,1}]
                            [--experimental {0,1}] [--seeds SEEDS]
                            [--cpuset CPUSET] [--smp SMP] [--memory MEMORY]
                            [--overprovisioned {0,1}]
                            [--listen-address LISTENADDRESS]
                            [--rpc-address RPCADDRESS]
                            [--broadcast-address BROADCASTADDRESS]
                            [--broadcast-rpc-address BROADCASTRPCADDRESS]
                            [--api-address APIADDRESS]
                            [--alternator-address ALTERNATORADDRESS]
                            [--alternator-port ALTERNATORPORT]
                            [--disable-version-check]
                            [--authenticator AUTHENTICATOR]
                            [--authorizer AUTHORIZER]
                            [--cluster-name CLUSTERNAME]
                            [--endpoint-snitch ENDPOINTSNITCH]
                            [--replace-address-first-boot REPLACEADDRESSFIRSTBOOT]
docker-entrypoint.py: error: unrecognized arguments: --alternator-https-port=XXX2
`

It seems, that the command isnt implemented or something else. But it should work regarding the help of the "scylla" command on the bash

`root@scylladb01 /]# scylla --help | grep alternator
  --alternator-port arg                 Alternator API port
  --alternator-https-port arg           Alternator API HTTPS port
  --alternator-address arg              Alternator API listening address
  --alternator-enforce-authorization arg
`
My docker-compose:

`version: '3'

services:
  scylladb:
    container_name: teleport-scylladb02
    hostname: teleport-scylladb02
    command: --broadcast-address X.X.X.15 --broadcast-rpc-address X.X.X.15 --seeds=X.X.X.14,X.X.X.15,X.X.X.16 --alternator-port=XXX1 --alternator-https-port XXX2
    ports:
- removed for privacy
    image: scylladb/scylla:4.0.1
    restart: always
    volumes:
     - /mnt/XXXXXX/data:/var/lib/scylla
     - /mnt/XXXXXX/ssl:/ssl_certificates
     - /mnt/XXXXXX/etc/scylla.yaml:/etc/scylla/scylla.yaml
`

Thank you

**Comment by tzach** [comment]
@nyh ?

**Comment by nyh** [comment]
Yes, unfortunately our docker command line parser (`dist/docker/redhat/commandlineparser.py`) doesn't take all of Scylla's command-line parameters, it just takes allows an arbitrary subset of them, and while `--alternator-port` is listed (and so is `--alternator-write-isolation` which is now mandatory, and `--alternator-addresss) but `--alternator-https-port` is missing.

One quick workaround you can use is to set alternator-https-port not via the command line, but by editing the scylla.yaml inside your container.

I'll prepare a patch that will add `--alternator-https-port` support to our docker. However,  @penberg can you please considering whether it might be possible for the docker script to stop parsing most if not all of these options and simply copying all of them verbatim to Scylla? I guess we need a separate issue about that.

**Comment by tzach** [comment]
> One quick workaround you can use is to set alternator_https_port not via the command line, but by editing the scylla.yaml inside your container.

Or by [Overriding scylla.yaml with a Master File](https://docs.scylladb.com/operating-scylla/procedures/tips/best_practices_scylla_on_docker/#overriding-scylla-yaml-with-a-master-file)

**Comment by nyh** [comment]
I have a patch adding the "--alternator-https-port" option to docker, but unfortunately it is not enough. We also need the files /etc/scylla/scylla.crt and /etc/scylla/scylla.key to exist inside the docker - with the key and certificate to use for this SSL.

I'm still not sure what I should do about these files. Should I just document the need to create them inside the docker image? Or what? Docker/SSL experts (@penberg @syuu1228 @slivne @elcallio) any recommendation?

**Comment by avikivity** [comment]
@nyh consider bind-mounting those files

**Comment by avikivity** [comment]
@nyh @psarna please backport if needed

**Comment by psarna** [comment]
queued to next-4.1

**Comment by avikivity** [comment]
@psarna please remove the "Backport candidate" label after backporting (or deciding not to and documenting the reason), in the future.

**Comment by psarna** [comment]
the change reached branch-4.1, removing the label

**Comment by avikivity** [comment]
(I generally leave the "Backport x.y" label on, since I don't use it in queries)
