### ISSUE TITLE
docker: Running scylla_io_setup does not work and is not needed in some cases

### ISSUE THREAD

**Issue by mmatczuk** [scylladb/scylla#6587]
*Installation details*
Scylla version (or git commit hash): 4.1 and 4.0
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

In [scyllasetup.py](https://github.com/scylladb/scylla/blob/branch-4.1/dist/docker/redhat/scyllasetup.py#L62) we now run scylla_io_setup, one needs to note that it requires running with privileges and some setup to make it work. I suggest to disable that if developer mode is enabled.

**Comment by slivne** [comment]
There is indeed a discrepancy - when running scylla outside of docker , setting developer-mode allows scylla to run without scylla_io_setup.

**Comment by slivne** [comment]
- We need to enhance this and not run io_setup in other cases as well (not only when developer mode is set).
- We need to add an option to `--no-io-setup` that is available in scylla_setup, users requested to mount a scylla io configuration settings (similar to what we allow outside of docker on regular installations, as an example - ami and not compute the values everytime).

**Comment by avikivity** [comment]
@penberg please evaluate for a backport

**Comment by erebe** [comment]
Hello @penberg @avikivity,
Is it possible to backport this patch in 4.1.x branche. It will be of great use for running scylla with the operator/kubernetes.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
