### ISSUE TITLE
Implement tool that pulls changes from CDC and pushes them to another cluster

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#6588]
This is needed to perform correctness testing of CDC.

**Comment by slivne** [comment]
isn't this a dup of #6556

**Comment by haaawk** [comment]
It is. I will close one.

**Comment by slivne** [comment]
We have two (and working on a Kafka one :) )

https://github.com/scylladb/scylla-cdc-java/tree/master/scylla-cdc-replicator
https://github.com/scylladb/scylla-cdc-go/tree/master/examples/replicator
