### ISSUE TITLE
protect from over large partitions

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#659]
found in analysis of #651

**Comment by tzach** [comment]
Support for large partitions will be a part of Scylla 1.3

**Comment by andrewrong** [comment]
@tzach  how to support it？

**Comment by tzach** [comment]
@andrewrong rather than protect from large partitions, Scylla 1.3 will transparently handle them.
@pdziepak can you please refer us to the relevant patches?

**Comment by tgrabiec** [comment]
Btw, to see issues related to handling of large partitions, check out the "large partitions" tag: https://github.com/scylladb/scylla/labels/large%20partitions

**Comment by pdziepak** [comment]
Most of large partition support code was merged in 597cbbdedc6ddd438f5f27fe51191f16067add60. There are also follow up series dealing with SSTables 28fab55e6edbb1b2158bb6660c196eda58145939 and streaming de429d6a53963bf7e7d0bd7da121b4da46fc122f.
