### ISSUE TITLE
Implement a test that checks replication based on CDC works correctly

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#6590]
1. Setup two Scylla clusters
2. Start a tool that reads CDC on one of those clusters and populates the second cluster with changes pulled from CDC (#6588)
3. Run load and nemesis on the first cluster
4. Compare that those two clusters contain the same data.

**Comment by slivne** [comment]
@haaawk / @kbr- can we close this

**Comment by haaawk** [comment]
I guess we could.
