### ISSUE TITLE
select query is empty after loading the sstable by 'nodetool refresh ...'

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#6594]
*Installation details*
Scylla version (or git commit hash): 4.1.rc1-0.20200602.4a3eff17ff7
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-07772e2fe7a213b27 (eu-west-1)

### Test info
- test id: e226e8d2-6b1e-464f-b14e-2bf2156a8203
- test log: https://cloudius-jenkins-test.s3.amazonaws.com/e226e8d2-6b1e-464f-b14e-2bf2156a8203/20200604_000154/sct-runner-e226e8d2.zip  
- db log: https://cloudius-jenkins-test.s3.amazonaws.com/e226e8d2-6b1e-464f-b14e-2bf2156a8203/20200604_000154/db-cluster-e226e8d2.zip  

### Description

In SCT, we have two refresh Nemesis.
- RefreshMonkey: loaded a small sstable files.
- RefreshBigMonkey: loaded a 100M sstable files.

In https://jenkins.scylladb.com/view/scylla-4.1/job/scylla-4.1/job/longevity/job/longevity-100gb-4h/11 , the verify query after executed 'nodetool refresh -- keyspace1 standard1' finished, but the key doesn't exist.

I didn't reproduce this problem locally (with one db node)

NOTE: We just improved the verify query recently, so the issue should be not a regression.

### Test log:

```
(start refresh)
2020-06-03T22:34:34+00:00  longevity-100gb-4h-4-1-db-node-e226e8d2-4 !INFO    | scylla: [shard 2] storage_service - Loading new SSTables for keyspace1.standard1...
....
(end refresh)
2020-06-03T22:34:41+00:00  longevity-100gb-4h-4-1-db-node-e226e8d2-4 !INFO    | scylla: [shard 2] storage_service - Done loading new SSTables for keyspace1.standard1 for all shards

Currently we executed the verify query after the 'nodetool refresh ...' returned.

< t:2020-06-03 22:34:41,405 f:remote.py       l:156  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.176.206]: Command "nodetool  refresh -- keyspace1 standard

1" finished with status 0

< t:2020-06-03 22:34:41,405 f:cluster.py      l:2432 c:sdcm.cluster_aws     p:DEBUG > Node longevity-100gb-4h-4-1-db-node-e226e8d2-4 [34.241.41.184 | 10.0.176.206] (seed: Fa

lse): Command 'nodetool  refresh -- keyspace1 standard1' duration -> 11.137227773666382 s

< t:2020-06-03 22:34:41,405 f:remote.py       l:306  c:sdcm.remote          p:DEBUG > RemoteCmdRunner [centos@10.0.176.206]: Running command "cqlsh --no-color   --request-ti

meout=120 --connect-timeout=60  -e "select * from keyspace1.standard1 where key=0x32373131364f334f3830" 10.0.176.206 9042"...


< t:2020-06-03 22:34:43,110 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.176.206]:  key | C0 | C1 | C2 | C3 | C4 | C5 | C6 | C7 | C

8 | C9

< t:2020-06-03 22:34:43,111 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.176.206]: -----+----+----+----+----+----+----+----+----+--

--+----

< t:2020-06-03 22:34:43,111 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.176.206]: 

< t:2020-06-03 22:34:43,111 f:remote.py       l:739  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.176.206]: (0 rows)

< t:2020-06-03 22:34:43,310 f:remote.py       l:156  c:sdcm.remote          p:INFO  > RemoteCmdRunner [centos@10.0.176.206]: Command "cqlsh --no-color   --request-timeout=12

0 --connect-timeout=60  -e "select * from keyspace1.standard1 where key=0x32373131364f334f3830" 10.0.176.206 9042" finished with status 0
```

### Local test
```
I didn't reproduce this problem locally with one db-node.
- 4.1.rc1-0.20200528.bb8fcbff68f

There is only one shard in my machine:
Jun 04 11:22:11 amos-centos8 scylla[6434]:  [shard 0] storage_service - Loading new SSTables for keyspace1.standard1...
Jun 04 11:22:11 amos-centos8 scylla[6434]:  [shard 0] table - Reshuffling SSTables in /var/lib/scylla/data/keyspace1/standard1-85f10e60a65511ea8aaf000000000000...
Jun 04 11:22:11 amos-centos8 scylla[6434]:  [shard 0] storage_service - CF keyspace1.standard1 at shard 0 had SSTables writes disabled for 138 usec
Jun 04 11:22:11 amos-centos8 scylla[6434]:  [shard 0] storage_service - Done loading new SSTables for keyspace1.standard1 for all shards

```

**Comment by slivne** [comment]
@amoskong - are the sstables (using mc) created with RF=3 ? - if they were created with RF=1 - then it could be that the files copied don't have relevant tokens.

In other words - how did you create the sstables used for the refresh, please share the schema

**Comment by amoskong** [comment]
Details to prepare the sstables files:

    1. Created keyspace1 and standard1 by:
     # cassandra-stress write no-warmup n=0
    
    2. Prepare data for small snapshot
     # cassandra-stress write no-warmup n=1000 -pop seq=2000000000..2000001000
    
    2. Additional data for 100M snapshot
     # cassandra-stress write no-warmup n=500000 -pop seq=3000000000..3000500000
    
    $ du -sh *
    99M     keyspace1.standard1.100M.tar.gz
    204K    keyspace1.standard1.tar.gz
    
    $ md5sum /tmp/new/*
    9c5dd19cfc78052323995198b0817270  /tmp/new/keyspace1.standard1.100M.tar.gz
    c033a3649a1aec3ba9b81c446c6eecfd  /tmp/new/keyspace1.standard1.tar.gz
    
     # Schema of keyspace1.standard1
    CREATE KEYSPACE keyspace1 WITH replication = {'class': 'SimpleStrategy',
      'replication_factor': '1'}  AND durable_writes = true;
    
    CREATE TABLE keyspace1.standard1 (
        key blob PRIMARY KEY,
        "C0" blob,
        "C1" blob,
        "C2" blob,
        "C3" blob,
        "C4" blob
    ) WITH bloom_filter_fp_chance = 0.01
        AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
        AND comment = ''
        AND compaction = {'class': 'SizeTieredCompactionStrategy'}
        AND compression = {}
        AND crc_check_chance = 1.0
        AND dclocal_read_repair_chance = 0.1
        AND default_time_to_live = 0
        AND gc_grace_seconds = 864000
        AND max_index_interval = 2048
        AND memtable_flush_period_in_ms = 0
        AND min_index_interval = 128
        AND read_repair_chance = 0.0
        AND COMPACT STORAGE
        AND speculative_retry = '99.0PERCENTILE';

**Comment by slivne** [comment]
@amoskong can you please provide the path to download the files

**Comment by slivne** [comment]
I found the files on s3 - but they do not seem updated 

![s3](https://user-images.githubusercontent.com/3465480/84171774-e05f4880-aa83-11ea-899b-5f81cf268b6b.png)


the last modified date is 3.5 years ago !!!!

@roydahan / @amoskong please double check this - I think we are still using the old files

**Comment by amoskong** [comment]
> I found the files on s3 - but they do not seem updated
> 
> ![s3](https://user-images.githubusercontent.com/3465480/84171774-e05f4880-aa83-11ea-899b-5f81cf268b6b.png)
> 
> the last modified date is 3.5 years ago !!!!
> 
> @roydahan / @amoskong please double check this - I think we are still using the old files
The latest test of master & 4.1 uses the new path.

New files:
- https://s3.amazonaws.com/scylla-qa-team/refresh_nemesis/keyspace1.standard1.100M.tar.gz
- https://s3.amazonaws.com/scylla-qa-team/refresh_nemesis/keyspace1.standard1.tar.gz

Old files:
- https://s3.amazonaws.com/scylla-qa-team/keyspace1.standard1.100M.tar.gz
- https://s3.amazonaws.com/scylla-qa-team/keyspace1.standard1.tar.gz

**Comment by roydahan** [comment]
It seems like invalid issue.
The keys should be loaded to all replicas and they are loaded only to one server.
I think we should add repair to the nemesis.

**Comment by slivne** [comment]
if we are using nodetool refresh - with new data:
 - we need todo it on all nodes 
- we need RF=#number of Nodes in the cluster, load on one node and run repair

I am reassigning this to you guys - please test on a small scale first that this works for you share what you are doing how many nodes / whats the schema - and lest clear this out.

**Comment by amoskong** [comment]
We can close this issue, not a real problem.

> if we are using nodetool refresh - with new data:
> 
> * we need todo it on all nodes
> * we need RF=#number of Nodes in the cluster, load on one node and run repair

I tested with above two methods, they all work.
In our longevity jobs, the RF isn't always same as #number of Nodes, so I will use method in the nemesis.

> I am reassigning this to you guys - please test on a small scale first that this works for you share what you are doing how many nodes / whats the schema - and lest clear this out.

- 3 db nodes - RF = 1  (have to run refresh on all db nodes)
   - after run refresh, parts of the keys will be loaded, (can be queried)
- 3 db nodes - RF = 3 (run refresh on one node, and execute repair)
   - before the repair, we can't query any key

```
REATE KEYSPACE keyspace1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;

CREATE TABLE keyspace1.standard1 (
    key blob PRIMARY KEY,
    "C0" blob,
    "C1" blob,
    "C2" blob,
    "C3" blob,
    "C4" blob
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

**Comment by raphaelsc** [comment]
> We can close this issue, not a real problem.

So closing the issue...

> 
> > if we are using nodetool refresh - with new data:
> > 
> > * we need todo it on all nodes
> > * we need RF=#number of Nodes in the cluster, load on one node and run repair
> 
> I tested with above two methods, they all work.
> In our longevity jobs, the RF isn't always same as #number of Nodes, so I will use method in the nemesis.
> 
> > I am reassigning this to you guys - please test on a small scale first that this works for you share what you are doing how many nodes / whats the schema - and lest clear this out.
> 
> * 3 db nodes - RF = 1  (have to run refresh on all db nodes)
>   
>   * after run refresh, parts of the keys will be loaded, (can be queried)
> * 3 db nodes - RF = 3 (run refresh on one node, and execute repair)
>   
>   * before the repair, we can't query any key
> 
> ```
> REATE KEYSPACE keyspace1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '3'}  AND durable_writes = true;
> 
> CREATE TABLE keyspace1.standard1 (
>     key blob PRIMARY KEY,
>     "C0" blob,
>     "C1" blob,
>     "C2" blob,
>     "C3" blob,
>     "C4" blob
> ) WITH bloom_filter_fp_chance = 0.01
>     AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
>     AND comment = ''
>     AND compaction = {'class': 'SizeTieredCompactionStrategy'}
>     AND compression = {}
>     AND crc_check_chance = 1.0
>     AND dclocal_read_repair_chance = 0.1
>     AND default_time_to_live = 0
>     AND gc_grace_seconds = 864000
>     AND max_index_interval = 2048
>     AND memtable_flush_period_in_ms = 0
>     AND min_index_interval = 128
>     AND read_repair_chance = 0.0
>     AND speculative_retry = '99.0PERCENTILE';
> ```
