### ISSUE TITLE
scylla_coredump_setup: coredumpctl: invalid option -- 'v'

### ISSUE THREAD

**Issue by enaydanov** [scylladb/scylla#6595]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

**Installation details**

Scylla version (or git commit hash): 666.development-0.20200603.97cb2892b

**Description**

`scylla_setup` failed with error:

```
STDOUT:

                #7  0x000000000041e375 reader_loop (bash)
                #8  0x000000000041c9de main (bash)
                #9  0x00007fe798793555 __libc_start_main (libc.so.6)
                #10 0x000000000041d47a _start (bash)
Generating coredump to test systemd-coredump...


systemd-coredump is working finely.
Does not able to detect coredump, failed to configure systemd-coredump.
coredump setup failed.

STDERR:

WARN  2020-06-03 22:59:46,551 [shard 0] iotune - Available space on filesystem at /var/tmp/mnt: 124 MB: is less than recommended: 10 GB
INFO  2020-06-03 22:59:46,551 [shard 0] iotune - /var/tmp/mnt passed sanity checks
Created symlink from /etc/systemd/system/multi-user.target.wants/scylla-server.service to /usr/lib/systemd/system/scylla-server.service.
Created symlink from /etc/systemd/system/multi-user.target.wants/var-lib-systemd-coredump.mount to /etc/systemd/system/var-lib-systemd-coredump.mount.
coredumpctl: invalid option -- 'v'

```

This caused by https://github.com/scylladb/scylla/commit/28c3d4f8e8f7f13da1c28bcaa135d312e87d2d80 because `scylla_util.out()` function should be run with `shell=True` parameter to be able to use pipes.

https://github.com/scylladb/scylla/blob/77dfa4f151bd9bc6689ba338adefd66f130379c3/dist/common/scripts/scylla_util.py#L348-L355

**Comment by fruch** [comment]
@enaydanov thanks for the analysis, @amoskong  already did tat ontop of email thread
and I fixed it in #6589

**Comment by enaydanov** [comment]
@fruch, should this issue be closed right now or after merge from [`scylladb:next`](https://github.com/scylladb/scylla/tree/next)?

**Comment by fruch** [comment]
If it was mentioned in the commit, it would have closed automatically when hitting master.

But since bit was open after the merge took place...
I think we can close it
