### ISSUE TITLE
Resharding can theoretically resurrect data 

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6600]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

@glommer, @avikivity 

The explanation below is based on a research done by me and @glommer.

The theoretical data resurrection possibility is based on the fact that a given SSTable owned by a set of shards, where this set is only a subset of all shards, can be *individually* resharded at *any shard*.

Let's say a shared SSTable, which belongs to shard 1 and 2, is fully expired (all tombstones can now be purged) and is scheduled to be resharded at shard 3. Now let's say there's an unshared SSTable, owned by either shard 1 or 2, which has data shadowed (deleted via tombstone) by that shared SSTable.

Resharding compaction, which in the previous example runs at a shard 3, will use the table's sstable set, at shard 3, to check if the expired tombstone can be purged without resurrecting data. Resharding compaction disables expiration *during compaction* by overriding max_purgeable_func(), however, get_fully_expired_sstables() is called unconditionally in compaction::setup() and it uses the table's sstable set, also at shard 3, to check if there's risk of data resurrection.

Data resurrection will happen in that example above, because resharding compaction runs on shard 3, but the unshared SSTable is located at shard 2's sstable set. So that shared SSTable will incorrectly be all deleted, resulting in data resurrection because the unshared SSTable will be left behind.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
