### ISSUE TITLE
Script scylla_setup freezes

### ISSUE THREAD

**Issue by djuwa4** [scylladb/scylla#6614]
I greet everyone!
I install the scylla, i also installed python 3.8.2.
Then i run the script scylla_setup, on stage: "Do you want IOTune to study your disks IO profile and adapt Scylla to it?"
This is the data that i get after choosing "Y":
..........................................................................................................................................................................................................
/usr/lib/scylla/libexec/scylla_io_setup:88: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  cfg = yaml.load(open(os.path.join(conf_dir, "scylla.yaml")))
tuning /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/00000000-0000-8899-0000-000000000000/host2/target2:0:0/2:0:0:0/block/sda/sda1
tuning /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/00000000-0000-8899-0000-000000000000/host2/target2:0:0/2:0:0:0/block/sda
already tuned: /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/00000000-0000-8899-0000-000000000000/host2/target2:0:0/2:0:0:0/block/sda/queue/nomerges
tuning /sys/devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A03:00/device:07/VMBUS:01/00000000-0000-8899-0000-000000000000/host2/target2:0:0/2:0:0:0/block/sda/sda1
.........................................................................................................................................................................................................
The process does not go forward. In this state the script freezes all weekend.
Here is the information displayed after clicking "ctr+c":
Traceback (most recent call last):
  File "/usr/lib/scylla/libexec/scylla_io_setup", line 128, in <module>
  File "/usr/lib/scylla/libexec/scylla_setup", line 380, in <module>
    "--properties-file", "/etc/scylla.d/io_properties.yaml"] + iotune_args)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 325, in call
    run_setup_script('IO configuration', '/usr/lib/scylla/scylla_io_setup')
  File "/usr/lib/scylla/libexec/scylla_setup", line 130, in run_setup_script
    return p.wait(timeout=timeout)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 990, in wait
    res = run(script, exception=False)
  File "/usr/lib/scylla/scylla_util.py", line 289, in run
    return p.wait()
    return self._wait(timeout=timeout)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 1624, in _wait
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 1624, in _wait
    (pid, sts) = self._try_wait(0)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 1582, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt
    (pid, sts) = self._try_wait(0)
  File "/opt/scylladb/python3/lib64/python3.7/subprocess.py", line 1582, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

Please help with this problem! I know that without  IO profile i can not run: systemctl start scylla-server

1) scylladb-3.1
2) Single Host Cluster
3) OS Debian - first generation virtual machine (Hyper-V);
4) CP cores= 4
5) memory RAM = 12gb
6) SAS hdd on physical machine

**Comment by avikivity** [comment]
First Scylla 3.1 is end of life. Please try again with 4.0.1.

Second, iotune is known to be problematic with HDD. You can work around it by creating io_properties.conf with the following contents:

```
disks:
  - mountpoint: /var/lib/scylla
    read_iops: 200
    read_bandwidth: 300M
    write_iops: 200
    write_bandwidth: 300M
```

adjust for the specs of your disk.

**Comment by djuwa4** [comment]
> creating io_properties.conf

Please tell me in which directory do I need to create the file?

**Comment by avikivity** [comment]
`/etc/scylla.d/io_properties.yaml`

**Comment by djuwa4** [comment]
> `/etc/scylla.d/io_properties.yaml`

Thank you so much! But in the end, only the installation of the new version helped. Our product just worked with the old version and we were afraid of instability when working with the new one.

**Comment by avikivity** [comment]
So, can this be closed?

**Comment by slivne** [comment]
@djuwa4 - closing this issue, if you still need help post and we can reopen
