### ISSUE TITLE
drain is missing from storage_service

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#662]
storage_service is missing the drain method that is needed by the nodetool drain command

**Comment by gleb-cloudius** [comment]
On Wed, Dec 16, 2015 at 12:25:38AM -0800, Amnon Heiman wrote:
> storage_proxy is missing the drain method that is needed by the nodetool drain command
> 
Origin does not have any drains in StorageProxy, did you mean
StorageService?

--
			Gleb.

**Comment by amnonh** [comment]
yes, storage_service
