### ISSUE TITLE
sstable_3_x_test memory leak

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#6624]
The sstable_3_x_test failed once out of three runs:

```
[2020-06-09T22:52:32.811Z] [295/378] boost/sstable_3_x_test                              debug   [ PASS ]
[2020-06-09T22:52:32.811Z] [296/378] boost/sstable_3_x_test                              debug   [ FAIL ]
[2020-06-09T22:52:37.011Z] [297/378] boost/sstable_3_x_test                              debug   [ PASS ]
```

with ASan detecting a memory leak in the failing one:

```
[2020-06-09T23:28:01.243Z] Leaving test module "test/boost/sstable_3_x_test.cc"; testing time: 383865956us
[2020-06-09T23:28:01.243Z]
[2020-06-09T23:28:01.243Z] =================================================================
[2020-06-09T23:28:01.243Z] ==1671==ERROR: LeakSanitizer: detected memory leaks
[2020-06-09T23:28:01.243Z]
[2020-06-09T23:28:01.243Z] Direct leak of 104 byte(s) in 1 object(s) allocated from:
```

Full log here:

https://jenkins.scylladb.com/job/scylla-4.0/job/next/88/consoleText

**Comment by bhalevy** [comment]
I'll build sstable_3_x_test_g at the same version and try addr2line on it to decode the backtrace.

**Comment by espindola** [comment]
I will try to reproduce first, failing that I will build with the same revision and path to try to decode the backtrace.

**Comment by espindola** [comment]
I think the bug is that in sstable::~sstable

Nothing waits for this file close:

   }
    if (_data_file) {
        // Registered as background job.                                                                                                                                                                                                     
        (void)_data_file.close()...

[decoded.txt](https://github.com/scylladb/scylla/files/4806697/decoded.txt)

**Comment by espindola** [comment]
> I think the bug is that in sstable::~sstable
> 
> Nothing waits for this file close:
> 
> }
> if (_data_file) {
> // Registered as background job.
> (void)_data_file.close()...

Nevermind, some of the leaked memory is from the call to await_background_jobs. There might be something being scheduled to new phase.

**Comment by raphaelsc** [comment]
On Fri, Jun 19, 2020 at 6:10 PM Rafael Ávila de Espíndola <
notifications@github.com> wrote:

> I think the bug is that in sstable::~sstable
>
> Nothing waits for this file close:
>
> }
> if (_data_file) {
> // Registered as background job.
> (void)_data_file.close()...
>

it takes the background jobs phased barrier, which can be waited
via await_background_jobs(), perhaps the test is not calling it. test_env
facility, used in most sstable tests, should be
calling await_background_jobs() in the end. if it doesn't, then that's a
problem.

**Comment by raphaelsc** [comment]
On Fri, Jun 19, 2020 at 6:31 PM Raphael S. Carvalho <raphaelsc@scylladb.com>
wrote:

>
>
> On Fri, Jun 19, 2020 at 6:10 PM Rafael Ávila de Espíndola <
> notifications@github.com> wrote:
>
>> I think the bug is that in sstable::~sstable
>>
>> Nothing waits for this file close:
>>
>> }
>> if (_data_file) {
>> // Registered as background job.
>> (void)_data_file.close()...
>>
>
> it takes the background jobs phased barrier, which can be waited
> via await_background_jobs(), perhaps the test is not calling it. test_env
> facility, used in most sstable tests, should be
> calling await_background_jobs() in the end. if it doesn't, then that's a
> problem.
>

[raphaelsc@localhost scylla]$ cat test/boost/sstable_3_x_test.cc | grep
SEASTAR_THREAD_TEST_CASE | wc -l
90
[raphaelsc@localhost scylla]$ cat test/boost/sstable_3_x_test.cc | grep
'await_background_jobs' | wc -l
87

**Comment by raphaelsc** [comment]
On Fri, Jun 19, 2020 at 6:36 PM Raphael S. Carvalho <raphaelsc@scylladb.com>
wrote:

>
>
> On Fri, Jun 19, 2020 at 6:31 PM Raphael S. Carvalho <
> raphaelsc@scylladb.com> wrote:
>
>>
>>
>> On Fri, Jun 19, 2020 at 6:10 PM Rafael Ávila de Espíndola <
>> notifications@github.com> wrote:
>>
>>> I think the bug is that in sstable::~sstable
>>>
>>> Nothing waits for this file close:
>>>
>>> }
>>> if (_data_file) {
>>> // Registered as background job.
>>> (void)_data_file.close()...
>>>
>>
>> it takes the background jobs phased barrier, which can be waited
>> via await_background_jobs(), perhaps the test is not calling it. test_env
>> facility, used in most sstable tests, should be
>> calling await_background_jobs() in the end. if it doesn't, then that's a
>> problem.
>>
>
> [raphaelsc@localhost scylla]$ cat test/boost/sstable_3_x_test.cc | grep
> SEASTAR_THREAD_TEST_CASE | wc -l
> 90
> [raphaelsc@localhost scylla]$ cat test/boost/sstable_3_x_test.cc | grep
> 'await_background_jobs' | wc -l
> 87
>

test_sstable_write_large_row and test_sstable_log_too_many_rows aren't
awaiting for background jobs, I think this patch should fix this particular
problem:
diff --git a/test/lib/test_services.cc b/test/lib/test_services.cc
index 8df601d27..25fa2b02b 100644
--- a/test/lib/test_services.cc
+++ b/test/lib/test_services.cc
@@ -70,6 +70,7 @@ class storage_service_for_tests::impl {
         _token_metadata.stop().get();
         _feature_service.stop().get();
         _abort_source.stop().get();
+        sstables::await_background_jobs_on_all_shards().get();
     }
 };

**Comment by espindola** [comment]
So, a potential fix landed 9 days ago. Should we close and reopen if this happens again?

**Comment by avikivity** [comment]
Yes.
