### ISSUE TITLE
Unified offline installer script

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#6626]
We are going to generate a single, unified tarball for the offline installer. Let's also implement a unified installer script, which calls the different component (core, jmx, tools) installers to simplify offline installation process for the user.

**Comment by syuu1228** [comment]
@penberg We can use previously implemented unified install.sh on scylla-unified-pkg test repo:
https://github.com/syuu1228/scylla-unified-pkg/blob/master/install.sh
Tested with latest relocatable package, it worked.

But, which repo should we merge this script? scylla main repo or scylla-pkg repo, or newly created repo?

**Comment by penberg** [comment]
@syuu1228 Let's put it into scylla.git.
