### ISSUE TITLE
Wrong order of initialization in messaging service constructor

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla#6628]
The register_handler function uses one of the scheduling mechanism functions to determine
the scheduling group to register for each verb.
https://github.com/scylladb/scylla/blob/4c9369e449623f5efd3676c8954179b7c3c952b8/message/messaging_service.cc#L272
The scheduling mechanism itself is initialized in the messaging service's constructor.
https://github.com/scylladb/scylla/blob/4c9369e449623f5efd3676c8954179b7c3c952b8/message/messaging_service.cc#L406-L409
The problem is that in the same constructor just before the mentioned initialization there is a call
to register_handler that results in using this mechanism before it has been initialized.
https://github.com/scylladb/scylla/blob/4c9369e449623f5efd3676c8954179b7c3c952b8/message/messaging_service.cc#L399

The order should be reversed.

**Comment by avikivity** [comment]
@eliransin what's the impact here? Does it need backporting to 4.0/4.1?

**Comment by eliransin** [comment]
@avikivity the problem doesn't exist in 4.0/4.1
And is already fixed in 4.2 (where it existed).

**Comment by avikivity** [comment]
No need to backport then.
