### ISSUE TITLE
Remove SimpleStrategy Replication Factor

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#6635]
*Installation details*
Scylla version (or git commit hash): 4.1

SimpleStrategy Replication Factor is dangerous, since it does not support multi DCs.
The (minor) advantage of SimpleStrategy is one does not have to know the DC name to set the RF, which makes it easier to use for simple demos and trivial use cases.

Instead of disabling it, and break exiting code, we can automatically convert SimpleStrategy to NetworkTopologyStrategy:
```
cqlsh> CREATE KEYSPACE IF NOT EXISTS ks WITH REPLICATION = { 'class' : 'SimpleStrategy'};
```

```
cqlsh> CREATE KEYSPACE IF NOT EXISTS ks WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'replication_factor' : 3 };
```
As suggested by @eliransin

**Comment by tzach** [comment]
Related #1789

**Comment by slivne** [comment]
We can't do it under the hood - the user needs to be aware.

I think the alternative approach of adding a flag that when set will block this (and other non safe options) is preferred.

**Comment by eliransin** [comment]
@slivne can you please create "safe mode" label?
I think we should start collecting issues that falls under this.

**Comment by slivne** [comment]
label added

**Comment by nyh** [comment]
This was duplicated by #8586, which is already fixed (now waiting to get to master), so closing this issue too.

By the way, Tzach wrote:
> The (minor) advantage of SimpleStrategy is one does not have to know the DC name to set the RF, which makes it easier to use for simple demos and trivial use cases.

Even this advantage doesn't exist any more - it is now possible to give a single RF to NetworkTopologyStrategy, and it applies to all currently-existing DCs (the misnamed "auto-expand" mode).
