### ISSUE TITLE
Cannot build scylla from source

### ISSUE THREAD

**Issue by arisuna** [scylladb/scylla#664]
Dear all
I am trying to build scylla from source in ubuntu 15.04. However, I got this error

```
[3/304] ANTLR3 cql3/Cql.g
FAILED: sed -e '/^#if 0/,/^#endif/d' cql3/Cql.g > build/release/gen/cql3/Cql.g && antlr3 build/release/gen/cql3/Cql.g && sed -i 's/^\( *\)\(ImplTraits::CommonTokenType\* [a-zA-Z0-9_]* = NULL;\)$/\1const \2/' build/release/gen/cql3/CqlParser.cpp
error(10):  internal error: no such group file Cpp.stg 

error(20):  cannot find code generation templates Cpp.stg
error(10):  internal error: no such group file Cpp.stg 

error(20):  cannot find code generation templates Cpp.stg
ninja: build stopped: subcommand failed.
```

Please help me. Thank you so much

**Comment by penberg** [comment]
@arisuna Do you have the ``antlr3`` package installed?

I think @tgrabiec and @syuu1228 are developing on Ubuntu so lets ask them.

**Comment by tgrabiec** [comment]
I'm on Ubuntu 14.04, if I remember correctly the problem is that the antlr package from Ubuntu repos doesn't have C++ support. I had to build antlr 3.5.2 from sources. 

```
git clone git@github.com:antlr/antlr3.git
cd antlr3 
mvn package -Dmaven.test.skip=true
```

Then make a script named `antlr3` like the one below, which uses the new jar (adjust the path), make sure it's  on `$PATH`:

```sh
$ cat `which antlr3`
#!/bin/sh

# Replace this with the location of the antlr jar on your system.
ANTLR_JAR=$HOME/src/antlr3/antlr-complete/target/antlr-complete-3.5.3-SNAPSHOT-no-st3.jar

java -jar $ANTLR_JAR "$@"
```

**Comment by arisuna** [comment]
Dear @tgrabiec  I've already downloaded antlr-3.5.2-complete-no-st3.jar from http://www.antlr3.org/download.html (I cannot build antlr 3.5.2 from source because there is something wrong with proxy permission). And then I make script like you recommend. However, the error still happen.
The antlr3 like bellow:
```
$ cat `which antlr3`
#!/bin/sh

# Replace this with the location of the antlr jar on your system.
ANTLR_JAR=$HOME/scylla/antlr-3.5.2-complete-no-st3.jar

java -jar $ANTLR_JAR "$@"
```
And I copy it to /usr/local/bin folder. $PATH:
```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-7-oracle/bin:/usr/lib/jvm/java-7-oracle/db/bin:/usr/lib/jvm/java-7-oracle/jre/bin
```

**Comment by tgrabiec** [comment]
@arisuna Do you also get the complaint about missing `Cpp.stg` when you run it manually like this?
```
antlr3 build/release/gen/cql3/Cql.g
```

The jar file from their download page contains `Cpp.stg`, so it should use it if the `antlr3` command uses that jar:
```
unzip -l ~/Downloads/antlr-3.5.2-complete-no-st3.jar | grep Cpp.stg
3-25 07:07   org/antlr/codegen/templates/Cpp/Cpp.stg
```

Did you verify that `antlr3` resolves to the script which uses the right jar?
```
antlr3 -version
cat `which antlr3`
```

**Comment by syuu1228** [comment]
Have you tried ./dist/ubuntu/build_deb.sh ?
It provides not just Scylla .deb package, but also dependency packages like antlr3.

**Comment by lmr** [comment]
I managed to get scylla to compile in both Ubuntu 14.04 and 15.10. I had to install more packages, though (that reminds me I should have documented the missing
packages to add them to build_deb.sh). `build_deb.sh` was very useful to get a part of the dependencies correctly sorted out.

**Comment by spodkowinski** [comment]
I wasn't able to get the build working using the custom antlr package created by `dist/ubuntu/dep/build_dependency.sh`. The build aborts with a `no such group file Cpp.stg` error and Cpp.stg isn't actually part of the package. 

Good news is that both Ubuntu Wily (15.10) and Debian testing (Stretch) will provide an updated antlr3 v3.5 package that is working just fine. It can be installed by adding the apt repository if you are on a older release.

### Ubuntu

Edit `/etc/apt/apt.conf.d/99defaultrelease` and add:
```
APT::Default-Release "trusty";
```
(assuming your running trusty (14.04))

Add wily repositories by creating `/etc/apt/sources.list.d/wily.list`:

```
deb http://archive.ubuntu.com/ubuntu wily main restricted universe multiverse
#deb-src http://archive.ubuntu.com/ubuntu wily main restricted universe multiverse

deb http://archive.ubuntu.com/ubuntu wily-updates main restricted universe multiverse
#deb-src http://archive.ubuntu.com/ubuntu wily-updates main restricted universe multiverse

deb http://archive.ubuntu.com/ubuntu wily-security main restricted universe multiverse
#deb-src http://archive.ubuntu.com/ubuntu wily-security main restricted universe multiverse

deb http://archive.ubuntu.com/ubuntu wily-backports main restricted universe multiverse
#deb-src http://archive.ubuntu.com/ubuntu wily-backports main restricted universe multiverse
```

Reinstall antlr from wily:
```
sudo apt-get remove libantlr-java libantlr3-runtime-java libstringtemplate-java
sudo apt-get -t wily install antlr3
```

### Debian (not supported yet)

Edit `/etc/apt/apt.conf.d/99defaultrelease` and add:
```
APT::Default-Release "jessie";
```
Add testing repositories by creating `/etc/apt/sources.list.d/testing.list`:

```
deb     http://ftp.debian.org/debian/    testing main contrib non-free
deb-src http://ftp.debian.org/debian/    testing main contrib non-free
deb     http://security.debian.org/         testing/updates  main contrib non-free
```

Reinstall antlr from testing:
```
apt-get update
sudo apt-get remove antlr3 libantlr-java libstringtemplate-java
sudo apt-get -t testing install antlr3
```

**Comment by arisuna** [comment]
Hi, I've already installed antlr3 
```
antlr3 -version
ANTLR Parser Generator  Version 3.2 debian-7ubuntu3
```
And then do like @tgrabiec  said:
```
Then make a script named antlr3 like the one below, which uses the new jar (adjust the path), make sure it's on $PATH:

$ cat `which antlr3`
#!/bin/sh

# Replace this with the location of the antlr jar on your system.
ANTLR_JAR=$HOME/src/antlr3/antlr-complete/target/antlr-complete-3.5.3-SNAPSHOT-no-st3.jar

java -jar $ANTLR_JAR "$@"
```
but It still failed.
I checked:
```
unzip -l antlr-3.5.2-complete-no-st3.jar | grep Cpp.stg
Result: 78786  2014-03-25 07:07   org/antlr/codegen/templates/Cpp/Cpp.stg
```
```
antlr3 build/release/gen/cql3/Cql.g
result: /usr/bin/antlr3: line 1: $: command not found
error(7):  cannot find or open file: build/release/gen/cql3/Cql.g; reason: java.io.FileNotFoundException: build/release/gen/cql3/Cql.g (No such file or directory)
```

**Comment by arisuna** [comment]
@lmr 
I've tried and it said Unsupported release 15.04:
```
 ./dist/ubuntu/build_deb.sh
Unsupported release: 15.04
Pless any key to continue...

[Errno 2] No such file or directory: '/home/thuyntt42/scylla/scylla/seastar/dpdk'
```

**Comment by avikivity** [comment]
For the second error, you need to run `git submodule update --init --recursive` in the `scylla` directory before building.

15.04 is not supported because we didn't test it (right @syuu1228 ?); if you test it and report problems, we will fix them.

@syuu1228 I think modern Ubuntus use systemd, we need to separate the install process differently than just redhat/ubuntu, we have deb vs. rpm and systemd vs. upstart.

**Comment by taidung86** [comment]
Please help me
$ git submodule update --init --recursive
fatal: Not a git repository (or any of the parent directories): .git

**Comment by avikivity** [comment]
What directory are you in?  You should be in the `scylla` directory, after `git clone`.

**Comment by slivne** [comment]
we support ubuntu 16.04 - if there is an issue - please open a new issue

**Comment by ywangtht** [comment]
Same error.
Fixed it by executing this command:
./configure.py --enable-dpdk --mode=release --static-boost --compiler=/opt/scylladb/bin/g++-7.3 --python python3.4 --ldflag=-Wl,-rpath=/opt/scylladb/lib64 --cflags=-I/opt/scylladb/include --with-antlr3=/opt/scylladb/bin/antlr3

Or follow the output of ./install-dependencies.sh
