### ISSUE TITLE
provide strong exception guarantees from load_sstable()

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#6658]
`load_sstable()` does not provide any exception guarantees. As a result, the caller has to figure out what to do if an SSTable fails to load.

As an example, see this snippet from `load_new_sstables` :

```
                try {
                    cf.load_sstable(sst, true);
                } catch(...) {
                    dblog.error("");
                    abort();
                }
```

**Comment by raphaelsc** [comment]
This abort() comes from this recent patch: 1021eb29c9
@bhalevy why are we now aborting if we failed to load a particular sstable? don't think that's a good reason enough to abort the whole system.

BTW, it looks like we'll need a function like table::load_sstables() to atomically load a set of SSTables in a given table.

**Comment by bhalevy** [comment]
> This abort() comes from this patch: [1021eb2](https://github.com/scylladb/scylla/commit/1021eb29c9ff60ec6cd65afdb682a90fd86318bd)
> @bhalevy why are we now aborting if we failed to load a particular sstable? don't think that's a good reason enough to abort the whole system.
> 
> BTW, it looks like we'll need a function like table::load_sstables() to atomically load a set of SSTables in a given table.

@raphaelsc the abort is not new per-se, it just happened elsewhere and moved here IIRC.  We don't support old-format counters hence we can't load the sstable.

**Comment by slivne** [comment]
@bhalevy / @raphaelsc - what can we do here ?

**Comment by bhalevy** [comment]
I'm not sure we need to do anything.
The decision what to do when hitting a sstable that couldn't be loaded is essentially the caller's.
In some cases we can propagate the error back to the client, and in some cases, like when starting scylla, we prefer to abort, when hitting invalid sstables.

By "strong exception guarantees" I'd just expect the table code to not leave any side effects on the table state when throwing an exception in load_ssstables, so that the table object can be used normally after throwing that exception.  Is this "contract" violated in any way?

**Comment by avikivity** [comment]
add_sstable() doesn't provide strong exception guarantees:

```c++
void table::add_sstable(sstables::shared_sstable sstable) {
    if (belongs_to_other_shard(sstable->get_shards_for_this_sstable())) {
        on_internal_error(tlogger, format("Attempted to load the shared SSTable {} at table", sstable->get_filename()));
    }
    // allow in-progress reads to continue using old list
    auto new_sstables = make_lw_shared(*_sstables);
    new_sstables->insert(sstable);
    _sstables = std::move(new_sstables);
    update_stats_for_new_sstable(sstable->bytes_on_disk());
    if (sstable->requires_view_building()) {
        _sstables_staging.emplace(sstable->generation(), sstable);
    } else {
        add_sstable_to_backlog_tracker(_compaction_strategy.get_backlog_tracker(), sstable);
    }
}
```

If any line after the assignment to _sstables fails, we end up in an inconsistent state.

**Comment by avikivity** [comment]
While a real bug, unlikely to be encountered, so not backporting.
