### ISSUE TITLE
scylla_swap_setup: swapsize become 0 when memory size less than 1GB

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#6659]
swapsize become 0GB when memory size less than 1GB, and causes the error:
```
subprocess.CalledProcessError: Command '['fallocate', '-v', '-l', '0GB', '/swapfile']' returned non-zero exit status 1
```

Scylla does not work such low memory environment anyway, we probably should raise error with better message.

**Comment by syuu1228** [comment]
This patch just cause error && exit when <1GB RAM, but do we want to support such environment since we are trying to handle EC2 instance type t2.micro / t2.small (#2630) ?
cc: @tzach

**Comment by avikivity** [comment]
Backported to 4.2.
