### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by yuqin11** [scylladb/scylla#6663]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

centos7: build as readme.

`
make[5]: *** No rule to make target '/data1/cpp/scylla/build/release/seastar/_cooking/ingredient/dpdk/build/x86_64-native-linuxapp-gcc/include/rte_string_fns.h', needed by 'rte_cfgfile.o'.  Stop.
`

**Comment by slivne** [comment]
@yuqin11 can you please provide:
1. the git commit you tried to build
2. the exact commands you ran to build scylla - so we can try and reproduce

**Comment by slivne** [comment]
closing the issue stale - no response from user
