### ISSUE TITLE
Issues with read consistency on a Single Node cluster

### ISSUE THREAD

**Issue by shantanu422** [scylladb/scylla#6681]
*Installation details*
Scylla version (or git commit hash): 3.1.2-0.20191127.9d78d848e
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): 18.04.3 LTS (Bionic Beaver)

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): GCP VM
Hardware: n2-highmem-16 (16 vCPUs, 128 GB memory)
Disks: 24 x 375GB Local SSDs

Trying to run a perf benchmarking on Scylla, however experiencing some consistency issues even with RF 1 on a single node cluster

Keyspace details:
```
CREATE KEYSPACE testks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
```

Table Details:
```
CREATE TABLE testks.match_table (
    id text,
    id_type text,
    country set<text>,
    dpid map<int, bigint>,
    xuid uuid,
    PRIMARY KEY ((id, id_type))
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'SizeTieredCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```
Ingested around 5 Billion Keys in the above table using [Spark-Cassandra-Connector](https://github.com/datastax/spark-cassandra-connector), ver 2.4.3 (default write consistency local_quorum)
All of the spark tasks were successful in the ingestion job.

Around 3 days later, ran read perf benchmark on the same table, again using Spark Cassandra Connector (default read consistency LOCAL_ONE) on the complete ingested data. During some reads perf, restarted Scylla to nullify the cache effect. Out of 5 Billion Keys, only 3 Billion Keys were matched in the run, 2 Billion Keys appeared to be missing.

Used CQL to validate the observation: 
```
cqlsh> select * from testks.match_table where id='XXXXXX-I8YL-FEtumB0GJsB6WkU' and id_type='id_mid_5';
 id | id_type | country | dpid | xuid
----+---------+---------+------+------
(0 rows)
```

Next day, changed compaction strategy to LeveledCompaction, and ran the same CQL statement after sometime
```
cqlsh> select * from testks.match_table where id='XXXXXX-I8YL-FEtumB0GJsB6WkU' and id_type='id_mid_5';

 id                          | id_type  | country | dpid                 | xuid
-----------------------------+----------+---------+----------------------+--------------------------------------
 XXXXXX-I8YL-FEtumB0GJsB6WkU | id_mid_5 | {'USA'} | {678: 1560689111524} | 68a96ff7-bbb6-4cce-92fd-1e51e9ce8636

(1 rows)
```
Out of the initial missing 2 Billion Keys, took a sample of 5 Million Keys, and ran the read perf again, this time only around 160K Keys turned out to be missing.

Open Questions:
1. The keys should have been retrieved even before changing CompactionStrategy, what could be the cause behind this?
2. What effect did changing the CompactionStrategy bring in, so that some of the keys were now made available?

**Comment by raphaelsc** [comment]
Changing compaction strategy from STCS to LCS results in the same data being organized different in disk and also using a different data structure in memory for storing them. Going from STCS to LCS should make read a lot faster. Could it be that we're failing to properly propagate timeout and we're returning an empty result instead for the query in some edge case? I will search for some unknown bug in the reported branch.

Right before you changed the strategy, did you try to run the same query on the missing key?

**Comment by shantanu422** [comment]
The initial set of queries and the compaction strategy change were run pretty close to each other (wouldn't say right before, however no other commands were run between them). Perhaps the issue is not related to CompactionStrategy change. Here are some more observations, post CompactionStrategy change to LeveledCompaction

Some keys still appeared to be missing:
```
cqlsh> select * from testks.match_table where id = 'XXXXXXXX-XXXX-d65d-0000-0000648ed65d' and id_type='id_mid_1';

 id | id_type | country | dpid | xuid
----+---------+---------+------+------

(0 rows)

cqlsh> select * from testks.match_table where id = 'XXXXXXXX-XXXX-c42b-0000-00007e42c42b' and id_type='id_mid_1';

 id | id_type | country | dpid | xuid
----+---------+---------+------+------

(0 rows)
```

Trying the same set of queries after an interval of around 6 hours:
```
cqlsh> select * from testks.match_table where id = 'XXXXXXXX-XXXX-d65d-0000-0000648ed65d' and id_type='id_mid_1';

 id                                   | id_type  | country | dpid                                                                                                 | xuid
--------------------------------------+----------+---------+------------------------------------------------------------------------------------------------------+--------------------------------------
 XXXXXXXX-XXXX-d65d-0000-0000648ed65d | id_mid_1 | {'USA'} | {17: 1562170080115, 223: 1560963444425, 404: 1560289657328, 858: 1560709430087, 1389: 1560095295901} | 372c08e9-1743-494f-af5d-6d8bf65a86d0


cqlsh> select * from testks.match_table where id = 'XXXXXXXX-XXXX-c42b-0000-00007e42c42b' and id_type='id_mid_1';

 id                                   | id_type  | country | dpid                 | xuid
--------------------------------------+----------+---------+----------------------+--------------------------------------
 XXXXXXXX-XXXX-c42b-0000-00007e42c42b | id_mid_1 | {'USA'} | {858: 1558221503803} | 4ffbf8a4-f89f-45df-a0f1-99e7f992f44b
```

**Comment by slivne** [comment]
If you have very large sstables you may be suffering from 90002ca3d261de87868a911939028bc4577bf9f4

Please note that 3.1 is end of lifed - we do not support this release anymore and don't backport fixes to it. 

Please upgrade to a supprted release at this time 3.3.X / 4.0.X 

If you still have an issue after upgrading to the latest release in 3.3 / 4.0 please post and we will be happy to look at the issue and find the bug if one exists

**Comment by slivne** [comment]
Looking at the schema - its probably not the issue - to hit the issue you need huge partitions with many rows - and you have a single row per partition.

Yet, still, please upgrade to a supported release - so we can try and assist you.

**Comment by slivne** [comment]
closing the issue is stale

@shantanu422 , we will be happy to work with you on checking this out further
- can you please provide a smaller reproducer that we can test this out locally
- alternatively if you can share the data we can try and upload this and check it out as well.

Please note only 4.0, 4.1 are supported now.
