### ISSUE TITLE
SSTable upgrade has a 2x disk space requirement

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6682]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 7351db7cab7

SSTable upgrade requires 2x the disk space of input data to succeed.

**Comment by avikivity** [comment]
Backported to 4.0, 4.1. 4.2 already has the commit.
