### ISSUE TITLE
Notify better with background behavior with encryption

### ISSUE THREAD

**Issue by arita37** [scylladb/scylla#6686]
When tables are encrypted,

If the encryption key file is corrupted 
or whatever situation which prevents “write on disk”, node status does not inform of this situation
(State is OK).

However, the node is available for read/write access
(ie similar that shut down).

We need to look at each node file to see
if no error msg appears....

nodetool status should be more verbose
on the state of encryption usage and actual
read/write possibikity on the node.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

**Comment by tzach** [comment]
@arita37 if I understand correctly you are reporting Encryption at Rest issue
Encryption at Rest is a Scylla Enterprise feature, and this project (and issues) are limited to Scylla Open Source. As a Scylla Enterprise customer you are welcome open a support ticket.

**Comment by arita37** [comment]
Where can we open the ticket ?
Was not informed of ticket service....
Looks like Open Source is more reactive(!)

**Comment by tzach** [comment]
> Where can we open the ticket ?
> Was not informed of ticket service....

Can you please email me to tzach at scylladb.com ?
