### ISSUE TITLE
paxos schema_mismatch_test fails: Expected to have "schema_mismatch_error" exception

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6687]
This test never passed after it was reenabled in scylladb/scylla-dtest@8a18bf2bf69351f703159395a1b9e0d388f29391
(See https://github.com/scylladb/scylla-dtest/issues/1534)

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/519/testReport/paxos_tests/TestPaxos/schema_mismatch_test/history/

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/519/testReport/paxos_tests/TestPaxos/schema_mismatch_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/paxos_tests.py", line 436, in schema_mismatch_test
    raise Exception("Expected to have \"schema_mismatch_error\" exception")
Exception: Expected to have "schema_mismatch_error" exception
```

It also fails the same way for me when running locally.

**Comment by bhalevy** [comment]
@alecco can you please check if error injection works properly for this test?

**Comment by alecco** [comment]
> @alecco can you please check if error injection works properly for this test?

Error injections work fine. The very similar test `schema_mismatch_mv_test` use the same error injection and it seems to work. I added debug points and the error injection is triggered and test passes fine.

Perhaps @ManManson can throw some light on this.

**Comment by ManManson** [comment]
@bhalevy I'll look into it now. Probably has something to do with log levels in Scylla. I usually run tests with `TRACE` log level, I suspect this is the issue.
