### ISSUE TITLE
tri_compare/less_compare can be used when the other is expected, leading to strange results

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#6688]
tri_compare returns int, and less_compare returns bool. This types convert to each other, but the function semantics are very different. This results in a trap where one can use one where the other is expected.

**Comment by avikivity** [comment]
Now that we're using C++20, we can return std::strong_ordering (or std::partial_ordering where appropriate); these don't convert to bool, and can't be constructed from bool.

**Comment by tgrabiec** [comment]
Duplicate of https://github.com/scylladb/scylla/issues/1449

**Comment by avikivity** [comment]
lol
