### ISSUE TITLE
scylla_util.py: duplication on detecting distribution

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#6691]
Seems like we mistakenly made two different way to detect distribution, 
 1. is_redhat_variant() / is_debian_variant() uses /etc/os-release, also we have a variable 'os_release' to get ID, ID_LIKE, VERSION, VERSION_ID etc.
 2. dist_name() / dist_ver() were previously used platform.dist(), now switched to distro package.

We can keep these functions, but no need to keep using both interface, os-release and distro.
I suppose distro is better choice, since it provides better abstraction.

**Comment by syuu1228** [comment]
I suppose we don't really need dist_name() / dist_ver(), we just can use ```import distro``` and then ```distro.name()``` or ```distro.ver()```.
dist_name() / dist_ver() was introduced for make platform API readable, since it was like ```platform.dist()[1]```.

**Comment by avikivity** [comment]
Not a bug, not backporting.
