### ISSUE TITLE
multishard_mutation_reader: shard_reader::fast_forward_to(const dht::partition_range&) can leave unexpected fragments in the buffer

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#6715]
`shard_reader::fast_forward_to(const dht::partition_range&, db::timeout_clock::time_point)` clears the buffer *before* `_read_ahead` (if any) is waited for. This means that data read by read-ahead will make it into the buffer and the unlucky consumer will get a bunch of completely out-of order fragments after the fast forwarding finishes.

This bug can affect row-level repair in non-homogenous clusters. The chance of hitting this is close to 0, as non-test consumers usually want to read all data from every range and hence drive the reader to EOS, before fast-forwarding. Still, worth to fix.

Found when auditing the code looking for possible causes of https://github.com/scylladb/scylla/issues/6613.

**Comment by denesb** [comment]
Found another bug in the same function: if there is an ongoing read-ahead, which is the one creating the reader, the reader will not be fast forwarded.

**Comment by slivne** [comment]
@denesb which versions are suspect to this.

**Comment by denesb** [comment]
In theory all, in practice none. The reason for that is that all "production" consumers read all data from the multishard reader before fast forwarding it to the next range. So the scenarios described above -- which are all related to reading parts of the data, then fast-forwarding -- cannot happen in production code. Currently only tests would do things like this.

**Comment by denesb** [comment]
Note that a fix is already queued, it just didn't pass promotion yet.

**Comment by avikivity** [comment]
Not backporting since no production risk
