### ISSUE TITLE
multishard_mutation_query(): fast-forwarded readers saved in the querier cache will have dangling range references

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#6716]
`shard_reader::remote_reader::fast_forward_to()` doesn't make a copy of the fast-forwarded-to range to store it in stable storage for when the reader is saved, like `fill_buffer()` does. This will result in a fast-forwarded, then saved and looked-up reader to use a stale range reference.

Saved readers are not currently never fast-forwarded, so no current code is vulnerable, but this is landmine waiting to explode.

Found when auditing the code looking for possible causes of #6613.

**Comment by denesb** [comment]
This bug can only be triggered if `query_mutations_on_all_shards()` is passed multiple ranges. Currently we only ever pass one range.

**Comment by slivne** [comment]
@denesb can we add an asswert validating we only pass one range - so when someone doesn't we will not need to hunt for the bug in a coredump

**Comment by denesb** [comment]
No need to add an assert, if we decide we don't want to support the multi-range case, we can just change the interface of the `query_mutations_on_all_shards()` to take a single range, instead of a vector of ranges, that only works if you happen to pass one range :).

AFAIK the reason this function needs to take a vector of ranges is backward compatibility to thrift, which supported wrapping ranges, which are expressed as two non-wrapping ranges in our storage system (which doesn't support wrapping ranges natively). So one should never hit this using CQL, only via thrift, don't know about the other APIs (alternator, redis).
