### ISSUE TITLE
Is ScyllaDB slower than cassandra 3.11.6?

### ISSUE THREAD

**Issue by nshigit** [scylladb/scylla#6719]
I try to make a quick compare of the speed for ScyllaDB and Cassandra 3.11.6. 
I choose official ScyllaDB and cassandra docker image to run cassandra-stress test on a 2CPU(E5v2690 8Core*2 128GB Mem SAS HD).
But the result show that ScyllaDB is a little slower than cassandra 3.11.6 in workloadc. (1000000rows, readonly test).
Under what condition ScyllaDB would be faster than cassandra?

**Comment by avikivity** [comment]
Scylla is faster than Cassandra under big data workloads. One million rows is nothing.

Additionally, Scylla is optimized for SSDs, not rotating disks.

Test a realistic multi-terabyte workload, not 0.3 GB.

**Comment by dorlaor** [comment]
In addition, there are ways to optimize the docker deployment and make it
3x faster,
see our blogs

**Comment by tzach** [comment]
https://docs.scylladb.com/operating-scylla/procedures/tips/best_practices_scylla_on_docker/
