### ISSUE TITLE
Scylla frezes when casting a decimal with a negative scale to a float

### ISSUE THREAD

**Issue by espindola** [scylladb/scylla#6720]
INSERT INTO test (key, value) VALUES ('k3', 1e1);
SELECT key, CAST(value as float) from test;

The select will freeze scylla. It is not really frozen and will just probably just run out of memory while trying to compute 10^std::limits<uint64_t>::max().

**Comment by avikivity** [comment]
Backported to 4.0, 4.1, 4.2.
