### ISSUE TITLE
needs_cleanup(), used by SSTable cleanup, is SLOW

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6730]
needs_cleanup() is a procedure used for cleanup to determine whether a SSTable needs cleanup.

The problem is that it iterates through all owned ranges for each SSTable.

A node can have thousands of SSTables and number of ranges for a given node can be 756 with a RF of 3 ((RF / NODES) * (NODES * NUM TOKENS).

The complexity is O(NUM_SSTABLES * NUM_RANGES), but we can make it O(NUM_SSTABLES * LOG(NUM_RANGES)), given that ranges are sorted and non-overlapping.

**Comment by avikivity** [comment]
Not a regression, performance impact only. Not backporting.

**Comment by avikivity** [comment]
This is also related to #6662, which is a 16-second stall! So will backport.

**Comment by avikivity** [comment]
Backported to 4.0, 4.1, 4.2.
