### ISSUE TITLE
seastar-cpu-map.sh missing from PATH

### ISSUE THREAD

**Issue by guy9** [scylladb/scylla#6731]
*Installation details*
Scylla version (or git commit hash): 4.0
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

When trying to run seastar-cpu-map.sh on a Scylla docker instance, version 4.1, as per [this doc.](https://docs.scylladb.com/kb/map-cpu/) The script is not found on the $PATH.
It does exist on the server:
[root@89d8cbcdff24 /]# find . -name "seastar*.*"
./usr/lib/scylla/seastar-cpu-map.sh
./opt/scylladb/scripts/seastar-cpu-map.sh

**Comment by penberg** [comment]
@avikivity @tzach I am not sure which one is broken: packaging or documentation? If we want this to be in `PATH`, then packaging should put it into `bin`:

```patch
diff --git a/install.sh b/install.sh
index d2df63a50f..5d54e06387 100755
--- a/install.sh
+++ b/install.sh
@@ -228,7 +228,7 @@ install -d -m755 "$retc"/scylla "$rsystemd" "$rprefix/bin" "$rprefix/libexec" "$
 install -m644 dist/common/systemd/*.service -Dt "$rsystemd"
 install -m644 dist/common/systemd/*.slice -Dt "$rsystemd"
 install -m644 dist/common/systemd/*.timer -Dt "$rsystemd"
-install -m755 seastar/scripts/seastar-cpu-map.sh -Dt "$rprefix"/scripts
+install -m755 seastar/scripts/seastar-cpu-map.sh -Dt "$rprefix"/bin
 install -m755 seastar/dpdk/usertools/dpdk-devbind.py -Dt "$rprefix"/scripts
 install -m755 libreloc/* -Dt "$rprefix/libreloc"
 # some files in libexec are symlinks, which "install" dereferences
```

**Comment by tzach** [comment]
Any reason why not to have **all** of Scylla/Seastar script in the default path?
Its easier for the user.

**Comment by penberg** [comment]
@tzach I am fine with that, will send a patch.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
