### ISSUE TITLE
Repair should expose it's progress

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#6733]
The repair has traces for its progress, it should expose metrics as well

**Comment by slivne** [comment]
Repairs run via manager provide progress. 

this is a duplicate of https://github.com/scylladb/scylla/issues/1244

**Comment by avikivity** [comment]
Not a bug, not backporting.

**Comment by avikivity** [comment]
Looks like the bug was reused, but the previous backport decision holds.
