### ISSUE TITLE
Need a metrics for Heat weighted load balanacing

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#6734]
HWLB should expose some metrics so it's status can be displayed

**Comment by avikivity** [comment]
HWLB uses cache miss metrics (it tries to make cache misses equal on all nodes)

**Comment by amnonh** [comment]
Can we get the weights exported as metrics?

**Comment by avikivity** [comment]
They are the cache miss metrics, so already exported (but not per-table)

**Comment by gleb-cloudius** [comment]
IIRC we have per table metrics, but by default we do not show those.

--
			Gleb.

**Comment by amnonh** [comment]
To conclude, can I assume that for each node the average recent cache hit-rate is it's relative 'heat'?

**Comment by gleb-cloudius** [comment]
On Tue, Jun 30, 2020 at 04:38:18AM -0700, Amnon Heiman wrote:
> To conclude, can I assume that for each node the average recent cache hit-rate is it's relative 'heat'?
> 
All the calculation are per table, not on average. It is likely that the
average represents accurate what is going on unless someone calls cache
flush on one of the tables.

--
			Gleb.

**Comment by amnonh** [comment]
ok, closing
