### ISSUE TITLE
Scylla 4.2: Fail to build unified deb

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla#6736]
Scylla 4.2 fails to build unified-deb
Looks like some issue with - and ~ 

I ran https://jenkins.scylladb.com/view/nexts/job/scylla-4.2/job/unified-deb/6/ and "told" it to take the artifacts from https://jenkins.scylladb.com/view/nexts/job/scylla-4.2/job/next/3/ it failed. I kept the workspace on loki.
The error message says it expects:
17:49:39  (expected one of scylla-server_4.2~rc0-0.20200629.5f175f810.orig.tar.gz, scylla-server_4.2~rc0-0.20200629.5f175f810.orig.tar.bz2,
17:49:39  scylla-server_4.2~rc0-0.20200629.5f175f810.orig.tar.lzma,  scylla-server_4.2~rc0-0.20200629.5f175f810.orig.tar.xz or scylla-package.orig
Files on loki:
ls -la /data/jenkins/workspace/scylla-4.2/unified-deb/scylla/build/debian
scylla-server_4.2.rc0-0.20200626.58498b4b6.orig.tar.gz
with a "minus".

Yaron Kaikov: I think this is the related issue https://github.com/scylladb/scylla/pull/6546 right?

https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/unified-deb/7/ passed. But it is based on
"scylla-4.2 » next" build number 2
(the last success one) which is before the version change (still 666 dev). So, we can't be happy with this...

**Comment by avikivity** [comment]
Backported to 4.2. Presumably no other branch is vulnerable.
