### ISSUE TITLE
init - Startup failed: std::runtime_error (bootstrap_with_repair: keyspace=system_distributed, range=(9183073555191895134, 9196226903124807343], no existing node in local dc)

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#6744]
Consider a cluster with two nodes:
    
    - n1 (dc1)
    - n2 (dc2)
    
    A third node is bootstrapped:
    
    - n3 (dc2)
    
The n3 fails to bootstrap as follows:
    
[shard 0] init - Startup failed: std::runtime_error (bootstrap_with_repair: keyspace=system_distributed, range=(9183073555191895134, 9196226903124807343], no existing node in local dc)

**Comment by slivne** [comment]
@asias is this a regression

what happens with user tables ?

which versions are effected

**Comment by asias** [comment]
> @asias is this a regression
> 
> what happens with user tables ?
> 
> which versions are effected

Yes, it is a regression. It does matter it is a system or user table. Bootstrap a node with table using SimpleStrategy has this issue in case multiple DC are configured. Versions with repair based ops are affected.

**Comment by asias** [comment]
Patch posted: https://github.com/scylladb/scylla/pull/6745

**Comment by avikivity** [comment]
Backported to 4.2 (only version with repair based node ops enabled).
