### ISSUE TITLE
need to update the sstable per read histogram

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#675]

**Comment by tzach** [comment]
@amnonh what nodetool operation is affected?

**Comment by tzach** [comment]
@amnonh what nodetool operation is affected and how?

**Comment by slivne** [comment]
@amnonh please provide more information so I'll know if we can push this out / assign it to the correct person

**Comment by amnonh** [comment]
nodetool cfhistograms
uses ColumnFamilyStore.getRecentSSTablesPerReadHistogram

Not the recent and not the total:
/column_family/metrics/sstables_per_read_histogram
Are implemented.

The later (that can be used to implement the recent version) is mapped to a column_family stat called:
estimated_sstable_per_read
(how many sstable were used while reading)
That stat need to be updated

**Comment by slivne** [comment]
@raphaelsc amnon may help in impl if its simple - can you add provide an eval and some info on how to impl

**Comment by raphaelsc** [comment]
@amnon: sstablesperRead and recentSSTablesPerRead are defined as follow in C*:

    // for backward compatibility
    @Deprecated public final EstimatedHistogram sstablesPerRead = new EstimatedHistogram(35);
    @Deprecated public final EstimatedHistogram recentSSTablesPerRead = new EstimatedHistogram(35);

*Apparently*, we don't need both. They are updated exactly the same way.

Do we really need a histogram type? At nodetool side, I see that we get an array of doubles.

The impl is about calling a column family function to update the histogram with nr of sstables used. I now need to figure out places in Scylla code that perform reads and see how to get exact number of sstables used in the operation (probably from mutation reader).

**Comment by amnonh** [comment]
you don't need the recent (ever) this is a poor design decision made in
origin and it was depricated.

Whenever there is a recent value, we put an implementation in the jmx
(don't worry about it).

I think there is already a parameter ready for recentssstable_per_read and
what is needed is to update it

**Comment by raphaelsc** [comment]
Thanks. Yes, I found it. It's estimated_sstable_per_read.

**Comment by amnonh** [comment]
ok, if you'll make sure that it is updated I think most of the other parts
are ready or I can complete it

**Comment by glommer** [comment]
I have just merged patches for this but forgot to mention the issue #. Sorry.

This is fixed by cc127295e940aa8c5024f0d4d065af6731b91209.

There is a caveat, however: we are only showing information about misses. We should show hits as well - but the estimated histogram is not a good medium for it since its first bucket is always 1 - never 0.

We need to use a better histogram in Scylla, but also update nodetool to expect the right thing (they have patches because C*3 uses a new histogram, we would just have to backport it).
