### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by blackrez** [scylladb/scylla#6758]
Hello,

I'm trying to build scylladb on ARM Graviton2 and it failed.
I build the docker image for the toolchain.

Here the log : 
https://gist.github.com/blackrez/19f10f814607f4498142378d03afc408

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

**Comment by avikivity** [comment]
Try `./configure.py --disable-dpdk`. The dock integration hasn't been ported yet.
