### ISSUE TITLE
test.py should print tests' durations to the log

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#6759]
Several times in the past, we have seen tests failing because extremely slow runs resulted in unexpected timeouts which caused tests to fail. The last example was issue #6750. When we look at the test.py console output, we see lines like:
```
01:40:58  [271/426] boost/row_cache_test                                 dev    [ PASS ]
01:41:03  [272/426] alternator/run                                       dev    [ PASS ]
01:41:23  [273/426] boost/multishard_mutation_query_test                 dev    [ PASS ]
01:41:36  [274/426] boost/cql_query_like_test                            dev    [ PASS ]
``` 
The timestamps on the left (added by Jenkins) do not help to understand how much time each test took to run, because test.py runs many tests in parallel, and we only learn when each test finished - not when it started.

I think we should add to each line, perhaps after the `"[ PASS ]"` (or `"[ FAIL ]"`) string,  the amount of time this test took from start to finish. We would then be able to recognize tests which unexpectedly took excessive amount of time, or perhaps - setups where all the tests are running extremely slowely, and we should know that. We can also use this information to recognize extremely long tests, which may be hurting our testing latency and we could consider shortening these tests.

CC @kostja

**Comment by avikivity** [comment]
Enhancement, not backporting.
