### ISSUE TITLE
compaction does not remove row tombstones 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#676]
compaction does not remove delete row markers from sstable files

to reproduce

  1. ccm remove; ccm create scylla-1 --scylla --vnodes -n 1 --install-dir=/home/shlomi/urchin-ccm/../scylla; ccm start
  2. ccm node1 -f c2
```
CREATE KEYSPACE keyspace1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '2'}  AND durable_writes = true;

CREATE TABLE keyspace1.standard1 (
    key blob PRIMARY KEY,
    C0 blob,
    C1 blob,
    C2 blob,
    C3 blob,
    C4 blob
) WITH bloom_filter_fp_chance = 0.01
    AND caching = '{"keys":"ALL", "rows_per_partition":"NONE"}'
    AND comment = ''
    AND compaction = {'class': 'org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy'}
    AND compression = {}
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 0
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

insert into keyspace1.standard1 (key,C0,C1) values (0x01,0x01,0x01);
insert into keyspace1.standard1 (key,C0,C1) values (0x02,0x01,0x01);
```
  3. ccm node1 flush
  4. ccm node1 cqlsh -e "delete from keyspace1.standard1 where key in (0x01);"
  5. ccm node1 flush
  6. ccm node1 compact
  7. cd into ~/.ccm/scylla-1/node1/data - and check content

export CASSANDRA_CONF=`pwd`/conf/ ; env cassandra.config=file://`pwd`/../conf/cassandra.yaml

~/cassandra/tools/bin/sstable2json keyspace1/standard1-b57123a0a7b811e58f6f000000000000/keyspace1-standard1-ka-3-Data.db 
[
{"key": "02",
 "cells": [["","",1450685393027190],
           ["c0","01",1450685393027190],
           ["c1","01",1450685393027190]]},
{"key": "01",
 "metadata": {"deletionInfo": {"markedForDeleteAt":1450685406887001,"localDeletionTime":1450685406}},
 "cells": []}
]

doing the same thing on cassandra leaves the data/keyspace/table data file with only the live data.

The test from origin compaction_test.py compaction_delete_test - does not cover this case.

**Comment by nyh** [comment]
On Mon, Dec 21, 2015 at 10:21 AM, slivne <notifications@github.com> wrote:

> insert into keyspace1.standard1 (key,C0,C1) values (0x01,0x01,0x01);
> insert into keyspace1.standard1 (key,C0,C1) values (0x02,0x01,0x01);
>
>    1. ccm node1 cqlsh -e "delete from keyspace1.standard1 where key in
>    (0x01);"
>    2. ccm node1 flush
>    3. ccm node1 compact
>
>
I don't understand how compaction can remove tombstones - what later, older
data comes in (e.g., from repair) and we don't know that we've already
deleted this row?

Does this test tombstone gc to something especially low?

Nadav.

**Comment by slivne** [comment]
@nyh you are correct in the general case - the tombstone needs to exists to make sure that data is not resurected because of repair - the setting gc_grace_seconds is used to ttk the tombstone

I set the  gc_grace_seconds = 0 - so in this case the tombstone should be removed.

**Comment by nyh** [comment]
Ok, I missed that setting. So the actual bug described in this issue isn't that compaction doesn't remove row tombstones (generally, it shouldn't), but that it doesn't do tombstone GC correctly (at least not when the whole partition is deleted). 

In sstables/compaction.cc we have:

```c++
                m->partition().compact_for_compaction(*_schema, max_purgeable, _now);
                if (!m->partition().empty()) {
                    return make_ready_future<mutation_opt>(std::move(m));
                }
                return operator()();
```

If the entire partition has been deleted *and* gc'ed, compact_for_compaction() should return empty(), so this code will skip this partition. I guess this doesn't happen.

@slivne I guess you should assign this issue to Raphael or to me.

**Comment by pdziepak** [comment]
There is another reason why tombstone cannot be removed. Some of the sstables that are not involved in the current compaction pass may have older data belonging this particular partition (or there is a reasonable suspicion that this is the case) and removing the tombstone will resurrect them.

**Comment by slivne** [comment]
1. nodetool compact forces a major compaction - and should compact all the
existing sstable files into a single file  "A major compaction consolidates
all existing SSTables into a single SSTable" - so this is not the case.

2. minor compaction - if the gc_period has passed how does compaction know
if to remove or not to remove - I think that it should rely on the setting.

Pawel can you provide a ref to the code you are refering to.

**Comment by nyh** [comment]
@pdziepak - this is a very interesting observation... In this case, how can we possibly ever GC partition tombstones (or any other type of tombstone!)? Unless we do a major compaction first?

So I think we might have a serious problem here (even more serious than what Shlomi found).... Could it be that the gc period should be *ignored* in most compactions, and should only be used except a major compation?

It would mean that compact_for_compaction() needs an option of whether it is called for a normal compaction, or a major compaction...

**Comment by pdziepak** [comment]
On 21 December 2015 at 10:32, nyh <notifications@github.com> wrote:

> @pdziepak <https://github.com/pdziepak> - this is a very interesting
> observation... In this case, how can we possibly ever GC partition
> tombstones (or any other type of tombstone!)? Unless we do a major
> compaction first?
>
> So I think we might have a serious problem here (even more serious than
> what Shlomi found).... Could it be that the gc period should be *ignored*
> in most compactions, and should only be used except a major compation?
>
> It would mean that compact_for_compaction() needs an option of whether it
> is called for a normal compaction, or a major compaction...
>
This is already taken care of, I only mentioned it since I didn't know that
nodetool compact always forces a major compaction and for minor ones it may
be correct to leave some tombstones alive even if their gc period has
passed.

The relevant code in Scylla is in
sstables/compaction.cc:compact_sstables::compacting_reader::operator().
get_max_purgeable_timestamp()
is called there to get the maximum purgeable timestamp for a given
partition. It does that by checking what's the minimum timestamp in
sstables that (probably) contain that partition, but are not compacted in
this pass.

The equivalent code in cassandra is
in src/java/org/apache/cassandra/db/compaction/LazilyCompactedRow.java.

**Comment by slivne** [comment]
Test 
compaction_test.py:TestCompaction_with_LeveledCompactionStrategy.compaction_delete_2_test
compaction_test.py:TestCompaction_with_SizeTieredCompactionStrategy.compaction_delete_2_test

**Comment by raphaelsc** [comment]
@slivne: I think we can close this issue after 03eee0678465db3b4e090049dab68bc4dc48f95d. Could you please confirm it?

**Comment by dorlaor** [comment]
Promoting to showstopper although we wait for @slivne to check if it can be closed

**Comment by slivne** [comment]
confirmed
