### ISSUE TITLE
scylla_setup: default "done" when there is no disk to choose from

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#6760]
Scylla version (or git commit hash): 4.1

After the user already selected disks, and there is no disk left to select, **done** can become the default selection.

```
Are you sure you want to setup RAID0 and XFS?
If you choose Yes, the selected drive will be reformated, erasing all existing data in the process.
[YES/no]
Please select unmounted disks from the following list: ['/dev/nvme0n1']
type 'cancel' to cancel RAID/XFS setup.
type 'done' to finish selection. Selected: []
> /dev/nvme0n1
type 'cancel' to cancel RAID/XFS setup.
[done] type 'done' to finish selection. Selected: ['/dev/nvme0n1']
> done
```

Also use square bracket for the selected list make it looks like a alternatives.
Maybe better:
```
[done] type 'done' to finish selection. Selected: '/dev/nvme0n1'
```

**Comment by tzach** [comment]
@syuu1228 thoughts?

**Comment by syuu1228** [comment]
@tzach There is no "default selection" on the prompt, I guess we should just remove square bracket from selected list.

**Comment by avikivity** [comment]
Minor, not backporting.
