### ISSUE TITLE
Individual Alternator tests not listed by Jenkins

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#6767]
Jenkins can list the state of individual test functions in larger test files - see https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/lastCompletedBuild/testReport/. But I can't seem to find there any of the Alternator pytests (`test/alternator/*`).
I thought that by `test.py` passing the "--junit-xml" option and creating an output XML file, we would gain this feature but apparently it doesn't work - maybe the file is in the wrong place or has the wrong format or something?

Some details:

If I run:
```
    ./test.py --mode dev alternator/run
```
I get a file `testlog/dev/xml/run.1.xunit.xml` which seems to list a lot of tests in some XML format I don't recognize. These tests do not appear to be listed by Jenkins.
On the other hand, if I run, some Boost test, e.g.,
```
    ./test.py --mode dev boost/alternator_base64_test
```
I get a file `testlog/dev/xml/alternator_base64_test.1` whose tests _are_ listed in Jenkins. The format of this file appears _different_ from the one generated by pytest above.

My question is - why isn't Alternator's log - `testlog/dev/xml/run.1.xunit.xml` - being recognized by Jenkins? Is it in the wrong format? The wrong place? Or what?

**Comment by nyh** [comment]
Hi @hagitsegev, can you please help me with this issue? test.py, specifically `test.py --mode dev alternator/run`, generates a file `testlog/dev/xml/run.1.xunit.xml` which I guess you can find on Jenkins as well. But for some reason, the hundreds of tests summarized in this file, do not get shown in the Jenkins test list, https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/lastCompletedBuild/testReport/. And my question is - why?

I understood from @kostja that there are Groovy scripts which you wrote which translate these XML files into HTML to be shown as the test report. Can you please help me understand why this XML file `testlog/dev/xml/run.1.xunit.xml` doesn't work? Does it have a bad name? A bad format? Is there a bug in the Groovy scripts which prevents it from parsing this file? Please note that this file was generated by **pytest**, with the "--junit-xml=..." option.

**Comment by nyh** [comment]
Hi @penberg @roydahan I need help from someone on your team to either fix the test-result parsing scripts at the Jenkins end to understand the `testlog/dev/xml/run.1.xunit.xml`, or to tell me what is wrong in that results file so I can (hopefully) fix it.

Alternatively, you can tell me that nobody cares and nobody looks at https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/lastCompletedBuild/testReport/ anyway and I should just ignore this problem and close the issue. But it's just that I was told, when asked to integrate Alternator's tests into test.py, that generating such a file is important. But right now this file is just ignored, which doesn't sound very helpful.

**Comment by roydahan** [comment]
I think that the xml need to be named with specific name (results.xml?) and get collected with build artifacts.
@hagitsegev am i correct here?

**Comment by slivne** [comment]
@hagitsegev / @penberg / @yaronkaikov ping

**Comment by hagitsegev** [comment]
I'll look into this on Sunday.

**Comment by nyh** [comment]
> I'll look into this on Sunday.

Thanks!

**Comment by hagitsegev** [comment]
I'm copying from a mail sessions, Splitting it to some comments ahead, trying to make things clear, and see what should be done:

The Jenkins job collects some files to set as artifacts on Jenkins.
As Kostja said, there are 2 formats, junit and xunit.
I collect both, according to these path under scylla dir
"testlog/$mode/xml/*.xunit.xml"
"testlog/$mode/xml/junit.xml"

So
testlog/dev/xml/run.1.xunit.xml => should be catched by my script, so I guess it is in the wrong format.

and 
testlog/dev/xml/alternator_base64_test.1 => is not a candidate for my script. But I guess there is some other process that collects such files into a single junit.xml file that I collect.

But - also -
There is some known issue, in which not all the test results are shown on jenkins. I didn't follow it up lately.

**Comment by hagitsegev** [comment]
Nadav: about "**testlog/dev/xml/run.1.xunit.xml => should be catched by my script, so I guess it is in the wrong format.**":

I don't know if it's the wrong format... I just used the "--junit-xml" option of pytest. The name suggests "junit" but it is an XML format, and "pytest --help" suggests there are different possible output modes called "xunit1", "xunit2", which adds to the confusion.

Can you please take a look at testlog/dev/xml/run.1.xunit.xml and tell me if you think it is junit, not xunit? I couldn't find on the web any explanation what is the difference between these formats :-(
Whatever this file's format is really called, could the Groovy scripts be modified to understand this file? Or maybe it's too far off from the regular xunit format?

Can you run these Groovy scripts manually and look at their logs (are those on Jenkins somewhere?) - maybe you'll see error messages that will help me understand why these tests aren't being recognized?

By the way, if I understand correctly, even if I want this file to be called "junit", not "xunit", I can't, because you only collect as junit just the single file "junit.xml", not a wildcard?

**Comment by hagitsegev** [comment]
Nadav's answer about: 
"**testlog/dev/xml/alternator_base64_test.1 => is not a candidate for my script. But I guess there is some other process that collects such files into a single junit.xml file that I collect.**"

No, the file looks like testlog/dev/xml/alternator_base64_test.2.xunit.xml - it also ends in ".xunit.xml", so I guess it does match your wildcard.

**Comment by nyh** [comment]
@hagitsegev I don't understand anything above, I don't understand what is my question (seems much of your text above are various snippets of thing that *I* wrote), what is your questions, what is an answer and what is some weird quote from somebody else's (?) mail. Please go back to my description of the issue (first thing on this page), I think I explained it very clearly, and it should have a very clear answer. 

But to save time, let me try to ask the question again. Please read the detail's here, not in anyone else's (wrong) interpretation of my question.

I'm asking about the Alternator pytest tests, which are run as a single test "pytest --mode=dev alternator/run".

When this test is run, a file is created `testlog/dev/xml/run.1.xunit.xml` (please don't confuse it with any other file containing the world "alternator" or anything - that is a different test!)
The name "run" in that filename comes from the name "alternator/run", and "1"  is just the test's number - in an actual run it might be 74, and I'd expect to actually have three of them on Jenkins because we run each test 3 times. It will be "1" only when you run this test alone.

I'm sure you can find this `testlog/dev/xml/run.*.xunit.xml` file on Jenkins directory, or you can generate it yourself by running `pytest --mode=dev alternator/run` manually (or I can send one to you).

My question is why don't the Groovy scripts pick up the tests in this file. Does it have the wrong filename? Does it have the wrong format? If something is wrong, please tell me what, so I can fix it. Alternatively, and even better, maybe you can fix the Groovy script. As I said, this file was created by "pytest", so it will be nice to recognize its format - in the future we may start to use pytest even more. 

Thanks,
Nadav.

**Comment by hagitsegev** [comment]
Nadav - I'm still writing, will let you know when done.
Maybe I should have write it on some draft, and copy after that. Sorry.

**Comment by hagitsegev** [comment]
So @nyh , 
I was reading your questions above (and on mails that I quote),
The files on https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2265/artifact/testlog/dev/xml/ are published OK:
alternator_base64_test.34.xunit.xml
alternator_base64_test.35.xunit.xml
alternator_base64_test.36.xunit.xml
(as I thought, the number is a counter, the names are taken from YOUR mail. I'm not confused).

They are published as xml files, but not as test results on https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/2265/testReport/

I see that there are 125 tests (We run each 3 times, and we have 377 xml files on https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2265/artifact/testlog/dev/xml/ one of them is junit.xml which is a summary file (so it appears only once).
While on https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/2265/testReport/ there are 90 tests.

So there are 35 tests that are not published on the results page.
I don't know the reason.
I once talked about it with @kostja, but I don't see an open issue about it.

Publish the test results summary is done by: 
step([$class: 'XUnitPublisher',
	thresholds: [[$class: 'FailedThreshold', unstableThreshold: '1']],
	tools: [[$class: 'BoostTestJunitHudsonTestType', pattern: "$testsWildcardFiles"]]])

(where the pattern $testsWildcardFiles is "testlog/$mode/xml/*.xunit.xml")

Your files are on the right pattern.
I don't see anything different according their structure (compared to a test that is published, as described above).
According to https://javadoc.jenkins.io/plugin/xunit/org/jenkinsci/plugins/xunit/types/package-summary.html there are quite a lot of other types (like BoostTestJunitHudsonTestType). 4 of them are for C++.
Maybe we need to publish more types?

Maybe @penberg / @kostja can help us here?

**Comment by nyh** [comment]
Thanks for the pointer to https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2265/artifact/testlog/dev/xml/. I'm asking about one specific file there, https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2265/artifact/testlog/dev/xml/run.1.xunit.xml. This is the output of the test I'm asking about (there is also run.2.xunit.xml and run.3.xunit.xml there).

So obviously, this file is found. And it does match the wildcard. So the name is not the problem. It has to be its format, then...

I don't know what is this "BoostTestJunitHudsonTestType" and whether it is suitable to parse the pytest output, it doesn't sound right - this test is not Boost.  However, I'm not sure this matters at all (does it?) - Googling around, I found some people complaining that Jenkins can't parse pytest's output. This project https://github.com/thaJeztah/docker-py/commit/9ea3da37a7a03ceb23b992cba269eb3123614f46 suggests that this can be fixed by a junit_family=xunit=xunit2` option can help make the format closer to what Jenkins expects. I'll try that and we'll see if it helps...

**Comment by nyh** [comment]
I sent to the mailing list a one-liner patch titled "alternator test: produce newer xunit format for test results" which I hope fill fix this problem by giving pytest the "xunit2" option which supposedly produces a format that Jenkins can understand.

I don't know how to check this, though, except committing the trivial patch and seeing if it really solved this issue....

**Comment by hagitsegev** [comment]
@nyh we can run BYO to test it.

**Comment by nyh** [comment]
@hagitsegev can you please tell me how? I need to run just the build and test, and just in one mode (dev mode) - no need for 3 build modes, 3 repeats, dtests and other things. Can you please give me a pointer? Thanks.

**Comment by nyh** [comment]
Oh, no need for BYO, I see @penberg already committed my one-line patch and it ran in https://jenkins.scylladb.com/job/scylla-master/job/next/2269. 
But, unfortunately, my patch didnt help... in https://jenkins.scylladb.com/job/scylla-master/job/next/2269/testReport/ I still can't seem to find any of the tests reported in testlog/dev/xml/run.1.xunit.xml. I'm running out of ideas, and have no way to debug this myself... Doesn't Jenkins or Groovy or whatever runs there behind the scene report errors and can tell us why wasn't this run.1.xunit.xml file wasn't parsed, maybe there is a specific problem in it I can correct?

**Comment by hagitsegev** [comment]
We have the general report, in which there are some warnings, that might be related.
Such as:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2269/consoleText/
(Specify the consoleText it is much faster to download and search):
```
[2020-07-20T09:26:37.873Z] WARNING: The file '/jenkins/workspace/scylla-master/next/scylla/testlog/debug/xml/run.1.xunit.xml' is an invalid file.
[2020-07-20T09:26:37.873Z] WARNING: At line 1 of file:/jenkins/workspace/scylla-master/next/scylla/testlog/debug/xml/run.1.xunit.xml:cvc-elt.1: Cannot find the declaration of element 'testsuites'.
[2020-07-20T09:26:37.873Z] WARNING: The result file '/jenkins/workspace/scylla-master/next/scylla/testlog/debug/xml/run.1.xunit.xml' for the metric 'BoostTest' is not valid. The result file has been skipped.
[2020-07-20T09:26:37.896Z] WARNING: The file '/jenkins/workspace/scylla-master/next/scylla/testlog/debug/xml/run.2.xunit.xml' is an invalid file.
[2020-07-20T09:26:37.896Z] WARNING: At line 1 of file:/jenkins/workspace/scylla-master/next/scylla/testlog/debug/xml/run.2.xunit.xml:cvc-elt.1: Cannot find the declaration of element 'testsuites'.
[2020-07-20T09:26:37.896Z] WARNING: The result file '/jenkins/workspace/scylla-master/next/scylla/testlog/debug/xml/run.2.xunit.xml' for the metric 'BoostTest' is not valid. The result file has been skipped.
[2020-07-20T09:26:37.918Z] WARNING: The file '/jenkins/workspace/scylla-master/next/scylla/testlog/debug/xml/run.3.xunit.xml' is an invalid file.
[2020-07-20T09:26:37.918Z] WARNING: At line 1 of file:/jenkins/workspace/scylla-master/next/scylla/testlog/debug/xml/run.3.xunit.xml:cvc-elt.1: Cannot find the declaration of element 'testsuites'.
[2020-07-20T09:26:37.918Z] WARNING: The result file '/jenkins/workspace/scylla-master/next/scylla/testlog/debug/xml/run.3.xunit.xml' for the metric 'BoostTest' is not valid. The result file has been skipped.
```
This might be related to the types.
I can:
Add some publish of the other relevant C++ formats (or any other format you think is relevant) in try&catch blocks, so they will not fail the build.

The way to debug such issues are on BYO.
You specify your Scylla branch (should be under scylla-dev I think).
After that you have quite a lot of parameters to control what you want to run. You can skip dtest, run only dev (this is the default).
https://jenkins.scylladb.com/view/master/job/scylla-master/job/byo/job/byo_build_tests_dtest/
This is doc describes how to use byo: https://github.com/scylladb/scylla-pkg/wiki/Using-BYO---Bring-Your-Own-branch(es)-to-debug-your-changes-before-pushing-them

**Comment by nyh** [comment]
Thanks! I couldn't find these error lines before - I didn't know they were actually in the console output. Great to know.
So the relevant problem is:
```
At line 1 of file:/jenkins/workspace/scylla-master/next/scylla/testlog/release/xml/run.1.xunit.xml:cvc-elt.1: Cannot find the declaration of element 'testsuites'.
```
Indeed, it seems that the Boost tests use the tags TestLog and TestSuite, while run.1.xunit.xml uses the tags: testsuites, testsuite and testcase. So this is a completely different format.

I tried some Googling and it suggests that if you use the "Junit" format in Jenkins, it should be able to parse it. Can you please try it? (I'm hoping that there is a way for you to just try out things interactively instead of submitting a patch and waiting hours for the build and tests to complete).

Thanks for the pointers about BYO - I'll use them next time, but this time it seems what I want to change is Jenkins code, I don't even know where it is.

**Comment by hagitsegev** [comment]
I can try that... 
The only "shortcut" I have is that I can run a test build from my branch (so no need to wait for code review and so).
But I still need to compile and run the tests...
Let me run some tries.

**Comment by nyh** [comment]
@hagitsegev I can't tell if how to do it (if I knew how, I'd do it myself ;-)), but can't you run *just* the conversion script, on just testlog/dev/xml/run.1.xunit.xml (which you can find in any the latest run, after my patch to use the more standard format), interactively - playing the format option or something until the parsing succeeds?
There is no way to write code if you need to wait 4 hours for builds and tests between each modification :-(

**Comment by hagitsegev** [comment]
Indeed I can write a new temp process for it.
Maybe it will be faster.
Just get all the test artifacts from an existing build, and try to publish them.

**Comment by nyh** [comment]
Reopening issue. The patch I sent (and marked this as "Fixed") made the format more standard, but Jenkins still didn't understand it (it wasn't the same format as the Boost tests, just another standard format...). So this issue is still open.

**Comment by hagitsegev** [comment]
Just noticed that under
https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2270/testReport/
we have "(root)" and under it, there are some alternator tests:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2270/testReport/(root)/alternator/
I didn't notice them before.
I don't know if these are ALL the tests you are looking for.

Anyway, I wrote a simple pipeline that gets all the test artifacts from an existing next, and publishes them.
Added the junit publish as you requested.
https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/yaron-debug/job/publish-unittests/5/testReport/
You can see here more tests (such as the core bptree and observable_test). There are 90 tests, while on next (with all modes there are ~50).

Take a look, I think we had a step forward, but I'm not sure this is the final target. Maybe there is more to do.

**Comment by nyh** [comment]
> Just noticed that under
> https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2270/testReport/
> we have "(root)" and under it, there are some alternator tests:
> https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2270/testReport/(root)/alternator/
> I didn't notice them before.
> I don't know if these are ALL the tests you are looking for.

No, these are not the tests I was looking for. The ones you found are just a couple of Boost (C++) tests for Alternator, which work like all the Boost tests. It is not the 500 (!) pytests I am looking for.

Those 500 tests are all listed in testlog/dev/xml/run.1.xunit.xml, which as you showed me in the log - wasn't parsed because of a schema error. The question is whether you managed to fix that?

> 
> Anyway, I wrote a simple pipeline that gets all the test artifacts from an existing next, and publishes them.
> Added the junit publish as you requested.
> https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/yaron-debug/job/publish-unittests/5/testReport/
> You can see here more tests (such as the core bptree and observable_test). There are 90 tests, while on next (with all modes there are ~50).

I don't see anything from the Alternator tests there. Did the parsing of the testlog/dev/xml/run.1.xunit.xml  actually succeed for you?
This file has 500 tests - I can't find any of them in the link https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/yaron-debug/job/publish-unittests/5/testReport/. 

As an example of 1 of these 500 tests, try looking for
```
<testcase classname="test.alternator.test_gsi" name="test_gsi_non_scylla_name" time="0.148">
```
I don't see this test or its class listed anywhere. (I don't know exactly how it was supposed to be listed in the hierarchy).
> 
> Take a look, I think we had a step forward, but I'm not sure this is the final target. Maybe there is more to do.

In testlog/dev/xml/run.1.xunit.xml you can find hundreds of tests, all of them should be listed. As a first step, the script that parses this file (which it seems you know which script this is) needs not to report an error parsing it.

**Comment by hagitsegev** [comment]
@nyh 
Regarding the warnings on run.N.xunit.xml (where N is 1,2,3)
I'm looking on these files, comparing to other files.
Let's take https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2261/artifact/testlog/release/xml/schema_changes_test.13.xunit.xml as an example:

It starts with a number
After that: "This XML file does not appear to have a... "
After that:
XML tags, starting with <TestLog>

```
4667174
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<TestLog>
<TestSuite name="test/boost/schema_changes_test.cc">
<TestCase name="test_schema_changes" file="test/boost/schema_changes_test.cc" line="0">
<TestingTime>4667174</TestingTime>
...
</TestCase>
...
</TestSuite>
...
</TestLog>
```
Looking on the files with the warnings (such as): https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2261/artifact/testlog/release/xml/run.1.xunit.xml
They start with some long text (2 lines).
There is no <TestLog> tag.
You can only see 
<testsuites> on line 3 (end tag on line 858). - On the other files it is <TestSuite (one, not with S, even if there are few tests).
After that there are many <testcase tags.
The warning talks about missing "testsuites"

So the format is just not the same, so no wonder why the same parser can't parse both files.

I don't know to tell you why these tests create this format, and these tests create that format.
I also don't know how to understand what is the other format, and which out of the formats on https://javadoc.jenkins.io/plugin/xunit/org/jenkinsci/plugins/xunit/types/package-summary.html I should use to parse it.

**Comment by nyh** [comment]
@hagitsegev please view the XML file with a text editor - all the "number" and "This XML file does not appear to have a..." messages you quoted are crap added by whichever viewer you used, that do not actually appear in the file :-) I suggest you save the XML file locally and then view it with "vi" or your favorite editor. 

Anyway, looking at both XML files, they are not actually too different: The Boost test has the tag heirarchy TestLog -> TestSuite -> TestCase, while the pytest (run.1.xunit.xml) result has the hierarchy  testsuites -> testsuite -> and testcase. It's almost the same just capitalized differently (does this matter?) and the name "testsuites" is used instead of "testlog". Does it matter? I have absolutely no idea. If I had any knowledge of your setup or Groovy scripts, what I would have done is to play with them interactively (not through 4-hour Jenkins runs...) to see what it takes to parse this file with "testsuites" in it. Sources like https://issues.jenkins-ci.org/browse/JENKINS-36182 suggest that the tag "testsuites" should be supported. You can also try to manually removing that "testsuites" line from the XML and rerun the script, and seeing if it helps, or try Jenkins's different parsers to see if any one of them understands this file?

Thanks.

**Comment by hagitsegev** [comment]
The warning complains about the missing "testsuites".
I have a way to run a try in a less than a minute. but I have no idea how to progress. Just "guess" the formats/parsers? There are dozens... and I didn't find any clue on the web... about pytest+jenkins...

**Comment by hagitsegev** [comment]
Also - I don't like to play with the files format. It is not the "right" thing to do. I'll not do it as a "permanent" solution, so better to find the real solution which is 1 of 2:
- Create the files on the expected format.
- Find the parser for the current format.

Another thing - as I guess we will first try option 2, it will be good to give those file a name I can parse on one way, and the others in the current way (I mean - that I'll have regex / wildcard 1 and 2 for the 2 parsers).

**Comment by nyh** [comment]
@hagitsegev I'm afraid I don't know how to help you debug this. "pytest" is a fairly common testing package, and I would be very surprised if Scylla was the only one using pytest together with Jenkins. There is nothing "wrong" with the XML result file that pytest generates, but I have no understanding of Jenkins or its Groovy code to understand what it actually finds wrong with this XML file, or how it can be fixed. I don't know if you need to pick a different "parser" for this XML, or there is another solution. This definitely requires Jenkins understanding (which I don't have), not pytest or python or XML understanding (which I have). Maybe if you can't figure this out, you can try to approach the Jenkins open-source community with that question?

By the way, right now I'm worried about the Alternator tests, but I'm sure we'll have in the future other types of pytests or other tests we'll want to list and need to know how to do that. I am also curious - why aren't the *dtests* listed there? Are we ok that they aren't listed? Or maybe they are listed in a different place?

If you do ask this question, for some context please note that on Fedora 32 (which I guess we have on Jenkins), we use pytest 4.6.11. We use the options `--junit-xml=outputname.xml  -o junit_family=xunit2` to pytest to cause it to create the XML file. The "`-o junit_family=xunit2`" option is mentioned in many online resources as necessary - and enough - for Jenkins to recognize this output file, so I wonder why it didn't help us. Note that in pytest 6 (which didn't reach Fedora 32) this xunit2 option became the default, so isn't even necessary, but on pytest 4.6.11 it is still (supposedly) necessary.

**Comment by penberg** [comment]
@nyh If you look at the XML generated by Alternator:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2270/artifact/testlog/dev/xml/run.1.xunit.xml/*view*/

and compare it to one generate by Boost:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2265/artifact/testlog/dev/xml/cache_flat_mutation_reader_test.64.xunit.xml/*view*/

You can see that the structure of the XML document is different. At least, at high level, Boost has `TestLog` element and Alternator generates a `TestSuites` element

We use the "xUnit" plugin in Jenkins, which has proven to be pretty sensitive to the format:

https://plugins.jenkins.io/xunit/

**Comment by nyh** [comment]
All the google searches I did suggest that having "testsuites" as the top tag is actually the correct thing for standard xunit files. I don't know how to get Jenkins to accept standard xunit files instead of Boost-specific files, but I was hoping one of you (Hagit or you) would know.
I noticed a Groovy snippet above that used the class name "BoostTestJunitHudsonTestType". This sounds specific to Boost tests, but I have no idea what other code or plugin you should use for non-boost xunit files.

**Comment by hagitsegev** [comment]
I think that the key is somewhere here: https://javadoc.jenkins.io/plugin/xunit/org/jenkinsci/plugins/xunit/types/package-summary.html
Tried to play with it a little bit, but with no luck. The documentation is mostly for java developers, which I'm not (start learning this area is out of my scope now).
I also tried to simply add <TestLog> to the beginning of the file and </TestLog>at the end, but it is still not good.
https://jenkins.scylladb.com/view/master/job/scylla-master/job/releng-testing/job/yaron-debug/job/publish-unittests/10/artifact/testlog/release/xml/run.3.xunit.xml/*view*/
This made the format of the file illegal.

No other ideas for now.

**Comment by penberg** [comment]
@nyh Right you are, the format `pytest` is using is indeed the "JUnit 2" format. The Jenkins pipelines _are_ supposed to support that too, so let's move discussion over to the Jenkins git repository.

**Comment by nyh** [comment]
By the way, apparently this issue was fixed, I don't know when: https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2370/testReport/test.alternator/ - it's beatiful, shows all the little Alternator tests one by one. Thanks @penberg and @hagitsegev !

**Comment by hagitsegev** [comment]
I didn't do anything, so I'm not the one to thank.
