### ISSUE TITLE
cql_query_test/test_cache_bypass fails intermittantly

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6773]
This test has failed a few times in next promotion starting in
https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2166/testReport/test_boost_cql_query_test.cc/test_boost_cql_query_test/test_cache_bypass/
scylla version 3452599bfd844dc07464d7d8e7789ee507dc8d4b (was at Merge "lwt: introduce LWT flag in prepared statement metadata" from Pavel, and then appranetly it was rebased)

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2168/testReport
scylla version bbd3ed9d47d70207dc122bdd61cd69aaf3ec1a8a

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2184/testReport/test_boost_cql_query_test.cc/test_boost_cql_query_test/test_cache_bypass/

and most recently,
https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2190/testReport/junit/test_boost_cql_query_test.cc/test_boost_cql_query_test/test_cache_bypass/
```
[Exception] - critical check without_cache == 0 has failed [4 != 0]
 == [File] - test/boost/cql_query_test.cc
 == [Line] -3503
```

**Comment by slivne** [comment]
We now have a way to detect if queries are system or non system and should be able to filter them out

**Comment by bhalevy** [comment]
@xemul please continue under the original github issue

**Comment by bhalevy** [comment]
Sent "[PATCH 1/1] test: cql_query_test: test_cache_bypass: use table stats" to scylladb-dev

**Comment by avikivity** [comment]
Backported to 4.0, 4.1, 4.2.
