### ISSUE TITLE
db/view: view_update_generator: unbalanced wait/signal can cause unbounded concurrency

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#6774]
Current HEAD: 36b6ee7b11b86aab26e5f69f6cde4ba089f43983

The view update generator has a semaphore to limit concurrency. This semaphore is waited on in `register_staging_sstable()` [1] and later the unit is returned after the sstable is processed in the loop inside `start()` [2].
This was broken by https://github.com/scylladb/scylla/commit/4e6400293e8cb6e7729d30cfb7e27dc03a3190f9, which changed the loop inside `start()` to process sstables in batches, per table, however didn't change the `signal()` call to return the amount of units according to the number of sstables processed. In theory this should cause the semaphore units to dry up, as the loop can process multiple sstables per table but return just a single unit. However what we are seeing instead is that it keeps returning units out of nowhere, as the loop can just as easily process 0 sstables, and indeed most of the time it has no sstables to process. This causes the effective concurrency of the view update generator to keep increasing, allowing for a future producer of staging sstables to register a huge amount of sstables at once, causing memory problems due to the amount of sstable readers that have to be opened (#6603, #6707).

[1] https://github.com/scylladb/scylla/blob/de82b3efaec3a9f285e5e676d32d88c163cee262/db/view/view_update_generator.cc#L123-L137
[2] https://github.com/scylladb/scylla/blob/de82b3efaec3a9f285e5e676d32d88c163cee262/db/view/view_update_generator.cc#L92

**Comment by psarna** [comment]
Snap. Do you perhaps also have a patch that fixes the issue?

**Comment by denesb** [comment]
Yes, I found out about the increase after I wrote a fix for it and wrote a unit test to test it and found out that instead of the concurrency dropping, it grows.

**Comment by denesb** [comment]
Another problem: once added, a table is never removed from `_sstables_with_tables`, so the loop in `start()` will keep spinning, never blocking on the condition variable.

**Comment by bhalevy** [comment]
4e6400293e8cb6e7729d30cfb7e27dc03a3190f9 is in 4.2-rc0, need to backport there.

**Comment by avikivity** [comment]
4.1 needs it too.

**Comment by avikivity** [comment]
Backported to 4.1, 4.2.
