### ISSUE TITLE
hinted handoff: memory leak caused by improper commitlog usage from hints manager

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla#6776]
HEAD: 36b6ee7b11b86aab26e5f69f6cde4ba089f43983 (happens on master as of writing this)

Refs: #6409

Currently, hints manager uses a `commitlog` object for hints storage. In order to manually trigger a flush and repopulate the list of hint segments written to disk, this object is recreated roughly every 10 seconds, like this:

https://github.com/scylladb/scylla/blob/de82b3efaec3a9f285e5e676d32d88c163cee262/db/hints/manager.cc#L354-L363

Unfortunately. the commitlog is not properly cleaned up - `shutdown()` is called, but `release()` is not called afterwards. Because of that, the [`segment_manager::_segments`](https://github.com/scylladb/scylla/blob/de82b3efaec3a9f285e5e676d32d88c163cee262/db/commitlog/commitlog.cc#L369) field is not cleared and references to some `segment`s might still be there. `segment`s hold a [shared pointer backreference to the owning `segment_manager`](https://github.com/scylladb/scylla/blob/de82b3efaec3a9f285e5e676d32d88c163cee262/db/commitlog/commitlog.cc#L439), which causes a reference cycle to occur, and prevents both `segment_manager` and `segment`s from being destroyed when `commitlog` is destroyed.

Found based on investigation in #6409 and by adding logging information about the global count of `segment_manager`s and `segment`s.

**Comment by avikivity** [comment]
Backported to 4.0, 4.1, 4.2.

**Comment by vladzcloudius** [comment]
> Backported to 4.0, 4.1, 4.2.

@avikivity 
Please, consider backporting to 3.0 and to the current Enterprise builds (2019.1.x).

**Comment by avikivity** [comment]
3.0 is at end of life.

Don't discuss enterprise releases on the open-source tracker.
