### ISSUE TITLE
Add uuid to a repair job

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#6786]
Currently, repair uses an integer to identify a repair job. The repair
id starts from 1 since node restart. As a result, different repair jobs
will have same id across restart.

To make the id more unique across restart, we can use an uuid in
addition to the integer id. We can not drop the use of the integer id
completely since the http api and nodetool use it.

**Comment by bhalevy** [comment]
If 4d7faac gets backported, need to backport 28f8798 as well.
