### ISSUE TITLE
Cannot upgrade from 3.3 (and earlier) AMI to 4.0 and later because scylla-ami cannot be upgraded

### ISSUE THREAD

**Issue by TalYoffe** [scylladb/scylla#6793]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 3.3
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): ScyllaDB 3.1.2 (ami-04bcb5cc4e3b1e74b)

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

[centos@ip-10-1-2-48 ~]$ nodetool drain
[centos@ip-10-1-2-48 ~]$ nodetool snapshot
Requested creating snapshot(s) for [all keyspaces] with snapshot name [1593693503470] and options {skipFlush=false}
Snapshot directory: 1593693503470
[centos@ip-10-1-2-48 ~]$ sudo cp -a /etc/scylla/scylla.yaml /etc/scylla/scylla.yaml.backup-src
[centos@ip-10-1-2-48 ~]$ sudo systemctl stop scylla-server
[centos@ip-10-1-2-48 ~]$ sudo yum install epel-release
Loaded plugins: fastestmirror
Determining fastest mirrors
epel/x86_64/metalink                                                                     |  18 kB  00:00:00
 * base: d36uatko69830t.cloudfront.net
 * elrepo: reflector.westga.edu
 * epel: mirror.umd.edu
 * extras: d36uatko69830t.cloudfront.net
 * updates: d36uatko69830t.cloudfront.net
base                                                                                     | 3.6 kB  00:00:00
copr:copr.fedorainfracloud.org:scylladb:scylla-ami-drivers                               | 3.3 kB  00:00:00
elrepo                                                                                   | 2.9 kB  00:00:00
epel                                                                                     | 4.7 kB  00:00:00
extras                                                                                   | 2.9 kB  00:00:00
scylla-3.3                                                                               | 3.3 kB  00:00:00
scylla-generic-3.3                                                                       | 3.3 kB  00:00:00
updates                                                                                  | 2.9 kB  00:00:00
(1/8): epel/x86_64/group_gz                                                              |  95 kB  00:00:00
(2/8): elrepo/primary_db                                                                 | 329 kB  00:00:00
(3/8): epel/x86_64/updateinfo                                                            | 1.0 MB  00:00:00
(4/8): epel/x86_64/primary_db                                                            | 6.8 MB  00:00:00
(5/8): extras/7/x86_64/primary_db                                                        | 194 kB  00:00:00
(6/8): updates/7/x86_64/primary_db                                                       | 3.0 MB  00:00:00
(7/8): scylla-3.3/x86_64/primary_db                                                      |  24 kB  00:00:00
(8/8): scylla-generic-3.3/primary_db                                                     |  16 kB  00:00:01
Resolving Dependencies
--> Running transaction check
---> Package epel-release.noarch 0:7-11 will be updated
---> Package epel-release.noarch 0:7-12 will be an update
--> Finished Dependency Resolution
Dependencies Resolved
================================================================================================================
 Package                        Arch                     Version                   Repository              Size
================================================================================================================
Updating:
 epel-release                   noarch                   7-12                      epel                    15 k
Transaction Summary
================================================================================================================
Upgrade  1 Package
Total download size: 15 k
Is this ok [y/d/N]: y
Downloading packages:
Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
warning: /var/cache/yum/x86_64/7/epel/packages/epel-release-7-12.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
Public key for epel-release-7-12.noarch.rpm is not installed
epel-release-7-12.noarch.rpm                                                             |  15 kB  00:00:00
Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
Importing GPG key 0x352C64E5:
 Userid     : "Fedora EPEL (7) <epel@fedoraproject.org>"
 Fingerprint: 91e9 7d7c 4a5e 96f1 7f3e 888f 6a2f aea2 352c 64e5
 Package    : epel-release-7-11.noarch (@extras)
 From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
Is this ok [y/N]: y
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Updating   : epel-release-7-12.noarch                                                                     1/2
  Cleanup    : epel-release-7-11.noarch                                                                     2/2
  Verifying  : epel-release-7-12.noarch                                                                     1/2
  Verifying  : epel-release-7-11.noarch                                                                     2/2
Updated:
  epel-release.noarch 0:7-12
Complete!
[centos@ip-10-1-2-48 ~]$ sudo curl -o /etc/yum.repos.d/scylla.repo -L http://repositories.scylladb.com/scylla/repo/9e37a9b1-1dc1-4cd0-a1c2-69a4c44e6a27/centos/scylladb-4.0.repo
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   183  100   183    0     0  24666      0 --:--:-- --:--:-- --:--:-- 26142
100   426  100   426    0     0    677      0 --:--:-- --:--:-- --:--:--     0
[centos@ip-10-1-2-48 ~]$ sudo yum install scylla
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: d36uatko69830t.cloudfront.net
 * elrepo: reflector.westga.edu
 * epel: mirror.umd.edu
 * extras: d36uatko69830t.cloudfront.net
 * updates: d36uatko69830t.cloudfront.net
scylla-4.0                                                                               | 3.3 kB  00:00:00
scylla-generic-4.0                                                                       | 3.3 kB  00:00:00
(1/2): scylla-4.0/x86_64/primary_db                                                      |  21 kB  00:00:00
(2/2): scylla-generic-4.0/primary_db                                                     |  14 kB  00:00:00
Resolving Dependencies
--> Running transaction check
---> Package scylla.x86_64 0:3.3.2-0.20200510.c8c057f5f8 will be updated
--> Processing Dependency: scylla = 3.3.2 for package: scylla-ami-3.3.2-20200511.3cf4b8cb447.noarch
---> Package scylla.x86_64 0:4.0.3-0.20200621.1fcf38abd9b will be an update
--> Processing Dependency: scylla-tools-core = 4.0.3 for package: scylla-4.0.3-0.20200621.1fcf38abd9b.x86_64
--> Processing Dependency: scylla-tools = 4.0.3 for package: scylla-4.0.3-0.20200621.1fcf38abd9b.x86_64
--> Processing Dependency: scylla-server = 4.0.3 for package: scylla-4.0.3-0.20200621.1fcf38abd9b.x86_64
--> Processing Dependency: scylla-kernel-conf = 4.0.3 for package: scylla-4.0.3-0.20200621.1fcf38abd9b.x86_64
--> Processing Dependency: scylla-jmx = 4.0.3 for package: scylla-4.0.3-0.20200621.1fcf38abd9b.x86_64
--> Processing Dependency: scylla-conf = 4.0.3 for package: scylla-4.0.3-0.20200621.1fcf38abd9b.x86_64
--> Running transaction check
---> Package scylla.x86_64 0:3.3.2-0.20200510.c8c057f5f8 will be updated
--> Processing Dependency: scylla = 3.3.2 for package: scylla-ami-3.3.2-20200511.3cf4b8cb447.noarch
---> Package scylla-conf.x86_64 0:3.3.2-0.20200510.c8c057f5f8 will be updated
---> Package scylla-conf.x86_64 0:4.0.3-0.20200621.1fcf38abd9b will be an update
---> Package scylla-jmx.noarch 0:3.3.2-20200510.edc87004b3 will be updated
---> Package scylla-jmx.noarch 0:4.0.3-20200621.27764819b37 will be an update
---> Package scylla-kernel-conf.x86_64 0:3.3.2-0.20200510.c8c057f5f8 will be updated
---> Package scylla-kernel-conf.x86_64 0:4.0.3-0.20200621.1fcf38abd9b will be an update
---> Package scylla-server.x86_64 0:3.3.2-0.20200510.c8c057f5f8 will be updated
---> Package scylla-server.x86_64 0:4.0.3-0.20200621.1fcf38abd9b will be an update
---> Package scylla-tools.noarch 0:3.3.2-20200510.593e6165c1 will be updated
---> Package scylla-tools.noarch 0:4.0.3-20200621.169701d9157 will be an update
---> Package scylla-tools-core.noarch 0:3.3.2-20200510.593e6165c1 will be updated
---> Package scylla-tools-core.noarch 0:4.0.3-20200621.169701d9157 will be an update
scylla-generic-4.0/filelists_db                                                          | 9.4 kB  00:00:00
scylla-4.0/x86_64/filelists_db                                                           | 100 kB  00:00:00
--> Finished Dependency Resolution
Error: Package: scylla-ami-3.3.2-20200511.3cf4b8cb447.noarch (@scylla-generic-3.3)
           Requires: scylla = 3.3.2
           Removing: scylla-3.3.2-0.20200510.c8c057f5f8.x86_64 (@scylla-3.3)
               scylla = 3.3.2-0.20200510.c8c057f5f8
           Updated By: scylla-4.0.3-0.20200621.1fcf38abd9b.x86_64 (scylla-4.0)
               scylla = 4.0.3-0.20200621.1fcf38abd9b
           Available: scylla-4.0.rc0-0.20200325.78f5afec30.x86_64 (scylla-4.0)
               scylla = 4.0.rc0-0.20200325.78f5afec30
           Available: scylla-4.0.rc1-0.20200406.9908f009a4a.x86_64 (scylla-4.0)
               scylla = 4.0.rc1-0.20200406.9908f009a4a
           Available: scylla-4.0.rc2-0.20200421.89e79023aeb.x86_64 (scylla-4.0)
               scylla = 4.0.rc2-0.20200421.89e79023aeb
           Available: scylla-4.0.rc3-0.20200501.eee4c00e29.x86_64 (scylla-4.0)
               scylla = 4.0.rc3-0.20200501.eee4c00e29
           Available: scylla-4.0.0-0.20200505.d95aa77b62.x86_64 (scylla-4.0)
               scylla = 4.0.0-0.20200505.d95aa77b62
           Available: scylla-4.0.1-0.20200524.8d9bc57aca6.x86_64 (scylla-4.0)
               scylla = 4.0.1-0.20200524.8d9bc57aca6
           Available: scylla-4.0.2-0.20200615.ce57d0174d4.x86_64 (scylla-4.0)
               scylla = 4.0.2-0.20200615.ce57d0174d4
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by avikivity** [comment]
@syuu1228 @hagitsegev we need to make sure scylla-machine-image is available in the 4.0 repo, and that it can upgrade over scylla-ami (via the Obsoletes: tag)

**Comment by fruch** [comment]
@TalYoffe sorry, I've miss the issue, and answer it on the slack:

you can do the following to workaround it
```bash
sudo yum remove scylla-ami
sudo yum upgrade scylla
sudo yum install scylla-machine-image
```

install scylla-machine-image, which is the replacement of scylla-ami, even that it's currently only working on an instance first boot. 
you'll have it if you spin up new instances with newer versions of the AMI (newer then scylla 4.0)

@avikivity that's out fault, for forgetting about it, even that someone warned us.
it's addressed in :
https://github.com/scylladb/scylla-machine-image/pull/46

and I've tested it, with 3.3 AMI

backported to 4.0, 4.1, 4.2, 2010.1

**Comment by slivne** [comment]
The fix is merged we are spinning new releases with this - closing the issue
