### ISSUE TITLE
Cannot decode backtrace with seastar-addr2line in Ubuntu

### ISSUE THREAD

**Issue by Flamefork** [scylladb/scylla#6795]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- ✅ I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.1, 4.0
Cluster size: n/a
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 18.04

Spin-off of #6780

`addr2line` fails to load `.debug` file from Debian `scylla-server-dbg` package:
```
addr2line: /usr/lib/debug/.build-id/69/7597645b4ac8b44ce5d4fb3f71b7264667715f.debug: unable to initialize decompress status for section .debug_info
addr2line: /usr/lib/debug/.build-id/69/7597645b4ac8b44ce5d4fb3f71b7264667715f.debug: unable to initialize decompress status for section .debug_info
addr2line: /usr/lib/debug/.build-id/69/7597645b4ac8b44ce5d4fb3f71b7264667715f.debug: File format not recognized
```

The same works fine using a `.debug` file from `scylla-debuginfo` RPM.

**Steps to reproduce**
1. Use Dockerfiles from https://gist.github.com/Flamefork/5e61b29073e3fd30c25d743ad580fd12
2. `docker build -f Dockerfile.ubuntu .` to see it failing
3. `docker build -f Dockerfile.centos .` to see it working

It works fine even if you copy a `.debug` file from Centos to Ubuntu and use it there, so *I guess* the problem is in the file itself not in binutils/etc.

**Comment by avikivity** [comment]
@espindola please investigate

**Comment by espindola** [comment]
Was this fixed by disabling compression?

**Comment by bhalevy** [comment]
@kostja can you please try to reproduce (since you're working on Ubuntu IIRC)?

**Comment by kostja** [comment]
kostja@hulk:/$ dpkg --listfiles scylla-server-dbg
/.
/usr
/usr/lib
/usr/lib/debug
/usr/lib/debug/.build-id
/usr/lib/debug/.build-id/36
/usr/lib/debug/.build-id/36/ea361565782a4d96bf3d160e26edd50967ea3f.debug
/usr/lib/debug/.build-id/36/f8a7b490fb7f7638d7828dfe92eecc2c31cbd9.debug
/usr/lib/debug/.build-id/54
/usr/lib/debug/.build-id/54/2149b840deaa7024f519b534588c41981733fd.debug
/usr/lib/debug/.build-id/7c
/usr/lib/debug/.build-id/7c/ad4f745bde5c52c2da346d8b5e5b57008d896c.debug
/usr/lib/debug/.build-id/80
/usr/lib/debug/.build-id/80/70e02b3cad0b0ab6fdd8acd3071007f99053c5.debug
/usr/lib/debug/.build-id/c8
/usr/lib/debug/.build-id/c8/84b569c06fe8ef964bc6d508438a1337dc953c.debug
/usr/lib/debug/.build-id/d3
/usr/lib/debug/.build-id/d3/8f8ad7668c5c1fb21a35a0d469ea5137f48e55.debug
/usr/lib/debug/.build-id/d7
/usr/lib/debug/.build-id/d7/ad28281d2bc94dd0efe070049f7b5dce91ff79.debug
/usr/share
/usr/share/doc
/usr/share/doc/scylla-server-dbg
/usr/share/doc/scylla-server-dbg/changelog.Debian.gz
/usr/share/doc/scylla-server-dbg/copyright

**Comment by kostja** [comment]
```
kostja@hulk:/$ /opt/scylladb/scripts/seastar-addr2line -e /usr/lib/debug/.build-id/d7/ad28281d2bc94dd0efe070049f7b5dce91ff79.debug 
/usr/lib/debug/.build-id/d7/ad28281d2bc94dd0efe070049f7b5dce91ff79.debug: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=d7ad28281d2bc94dd0efe070049f7b5dce91ff79, for GNU/Linux 3.2.0, not stripped


```

**Comment by penberg** [comment]
@kostja So `readelf -n ./opt/scylladb/libexec/scylla | grep "Build ID"` will tell you the build ID of the executable and that's the `.debug` file that contains the symbols.

**Comment by kostja** [comment]
```
root@hulk:/usr/lib/debug/.build-id# readelf -n /opt/scylladb/libexec/scylla | grep "Build ID"
    Build ID: 36f8a7b490fb7f7638d7828dfe92eecc2c31cbd9
root@hulk:/usr/lib/debug/.build-id# find . -name '*36f8a7b490fb7f7638d7828dfe92eecc2c31cbd9*'
root@hulk:/usr/lib/debug/.build-id# 
```

**Comment by penberg** [comment]
@kostja The first two characters are used for a directory name... The file will be `/usr/lib/debug/.build-id/36/f8a7b490fb7f7638d7828dfe92eecc2c31cbd9.debug`

**Comment by kostja** [comment]
This file exists and is parsed by addr2line:
```
root@hulk:/usr/lib/debug/.build-id# /opt/scylladb/scripts/seastar-addr2line -e ./36/f8a7b490fb7f7638d7828dfe92eecc2c31cbd9.debug
root@hulk:/usr/lib/debug/.build-id# 
```

**Comment by Flamefork** [comment]
Checked again with latest 4.1.x after seeing https://github.com/scylladb/scylla/issues/6982 in release notes.
The issue is fixed now.
Thank you!
