### ISSUE TITLE
gossiper: choose seeds according to their proximity to the node - give a priority to seeds in the same DC/RACK

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#6796]
*Installation details*
HEAD: 2d63acdd6aaf00c4c8bf979ad332776e532d2f56

*Description*
Today gossiper sends to all seeders in the seeders' list in the shadow round.
It would make sense to optimized this and prefer seeders that are "closer" to the gossiping node (Snitch provides the corresponding function to order nodes according to the proximity).

It will also make sense to optimize the rest of gossiper operation and make it send digest messages to "remote" nodes more rarely and to local ones - more frequently.

**Comment by vladzcloudius** [comment]
@asias FYI

**Comment by avikivity** [comment]
We should drop the seed concept.

**Comment by vladzcloudius** [comment]
> We should drop the seed concept.

@avikivity In this request you can replace every appearance of "seed" to "nodes being contacted in order to get the current cluster state" and the point would still hold.

The idea is to attempt to fetch the info from the closest available nodes.

**Comment by asias** [comment]
So, you are talking about sending to seed node(s) in local dc in the shadow round in boot up progress. Why does the optimization matter? On the contrary, we want to talk to all nodes instead of just seeds node when a node boot up when we remove the seed concept. 

During normal gossip operation, if nodes send to remote dc rarely, propagation between nodes in different DC will be much slower.  Why is that beneficial? The gossip message traffic is pretty small anyway (we should fix the cache hit message issue O(nr of table) though).

**Comment by avikivity** [comment]
Well, if each node contacts the closest neighbot, the cluster will partition itself into racks and datacenters.

**Comment by slivne** [comment]
#6845  - removing seeds, will close once this one is closed

**Comment by avikivity** [comment]
I think it's invalid regardless of whether we have seed nodes or not. Gossip should try to spread as much as possible, not contact close nodes.

**Comment by vladzcloudius** [comment]
> So, you are talking about sending to seed node(s) in local dc in the shadow round in boot up progress. Why does the optimization matter? 

@asias @avikivity 
Seed nodes today are only contacted when node starts up.
Seeds are absolutely not important/relevant after that.
There are situations when cross-DC link is very slow and even sometimes partitioned and preventing the node to bootup because of some temporary net slowness makes no sense whatsoever.

Giving closer seeds a priority during the node bootup will decrease the probability of failed statup.

@avikivity This has nothing to do with normal gossip operation which will still distribute the information across the whole cluster.

If/when seeders concept is removed - the same reasoning will hold during the bootup process (not to confuse with bootstrap!).

**Comment by vladzcloudius** [comment]
I see that we send Syns in the shadow round to all seed nodes at once and wait for at one to respond.
So, the boot will not fail as I initially thought. 

So, probably what we have is indeed ok as is.

Closing for good now.
