### ISSUE TITLE
Staging SSTables are incorrectly removed or added to backlog after ALTER TABLE / TRUNCATE

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6798]
Staging SSTables aren't added to the backlog tracker when they're first loaded into the table, but it turns out that they could added later to the tracker after an ALTER TABLE or TRUNCATE, because we don't check if a SSTable requires view building before adding or removing it to / from the tracker.

**Comment by raphaelsc** [comment]
Oops, I had to work on v2 and forgot about it. thanks @slivne for the remind

**Comment by raphaelsc** [comment]
v2 sent

**Comment by avikivity** [comment]
Backported to 4.0, 4.1, 4.2.
