### ISSUE TITLE
Compaction - after compaction an sstable is created even if no data should exist

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#68]
DTEST  compaction_test.py:TestCompaction_with_SizeTieredCompactionStrategy.sstable_deletion_test fails

I think the issue is that we create an empty sstable file or have some data in the file although non should exist

The code does the following:

```
       for x in range(0, 100):
            cursor.execute('insert into cf (key, val) values (' + str(x) + ',1)')
        node1.flush()
        for x in range(0, 100):
            cursor.execute('delete from cf where key = ' + str(x))
        node1.flush()
        node1.nodetool('compact')
```
1. it writes 100 key,value
2. flush
3. deletes all key,value
4. flush
5. compact

the end results is that no sstable should exist.

```
nosetests -v compaction_test.py:TestCompaction_with_SizeTieredCompactionStrategy.sstable_deletion_test
sstable_deletion_test (compaction_test.TestCompaction_with_SizeTieredCompactionStrategy) ... FAIL

======================================================================
FAIL: sstable_deletion_test (compaction_test.TestCompaction_with_SizeTieredCompactionStrategy)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/shlomi/urchin-dtest/compaction_test.py", line 111, in sstable_deletion_test
    self.assertFalse("Data" in afile)
AssertionError: True is not false
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/shlomi/.dtest/dtest-tEXfks
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 15.629s

FAILED (failures=1)
```

**Comment by avikivity** [comment]
@raphaelsc I think we now don't create empty sstables; is this correct?

**Comment by raphaelsc** [comment]
On Thu, Jun 15, 2017 at 11:12 AM, Avi Kivity <notifications@github.com>
wrote:

> @raphaelsc <https://github.com/raphaelsc> I think we now don't create
> empty sstables; is this correct?
>

that's true. there was a bug in the past, but it's now fixed. A few months
ago, I tested that rewrite of fully expired sstable won't generate a new
empty sstable. That can also be seen from the compaction logs.

**Comment by avikivity** [comment]
@slivne this should be retested, it's probably fixed.

**Comment by glommer** [comment]
@raphaelsc @slivne can we close this ?

**Comment by raphaelsc** [comment]
retested, and it worked as expected:

INFO  2018-04-30 18:26:29,228 [shard 0] compaction - Compacting
[./data/data/ks/users-f0823d704cbc11e89d4b000000000000/la-1-big-Data.db:level=0,
]
INFO  2018-04-30 18:26:29,228 [shard 0] compaction - Compacted 1 sstables
to []. 4910 bytes to 0 (~0% of original) in 0ms = 0.00MB/s. ~1 total
partitions merged to 0.

please close this
