### ISSUE TITLE
build unified-deb: fix rm command on python3

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla#6802]
While building unified-deb we first use scylla/reloc/build_deb.sh to create the scylla core package, and after that scylla/reloc/python3/build_deb.sh to create python3.

On https://github.com/scylladb/scylla/commit/058da69a3bf8df0ad4713f3e342fd364228ae5ec#diff-4a42abbd0ed654a1257c623716804c82 a new rm -rf command was added.
It causes python3 process to erase Scylla-core process.

Set python3 to erase its own dir scylla-python3-package only.

**Comment by slivne** [comment]
fixed by aec910278f7e83ed6a75764f6213fa89f0d00a1d
