### ISSUE TITLE
Optimize partition filtering of cleanup compaction

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6807]
Partition filtering of cleanup compaction can be optimized by:

1) Removing the check that token belongs to this shard because after off-strategy, table no longer works with shared sstables.

2) Avoid the binary search on each compacted token by remembering the last iterator into the owned token ranges, which is both sorted and non-overlapping. So we can incrementally iterate through owned token ranges as tokens are compacted. So overall complexity for cleanup goes from O(# of input tokens * log(# of owned ranges))  into an average complexity of O(# of input tokens).

@avikivity, @bhalevy

**Comment by slivne** [comment]
What happens if there is a toplogy change during cleanup ?

**Comment by raphaelsc** [comment]
> What happens if there is a toplogy change during cleanup ?

Cleanup sequentially compact SSTables that need to be cleaned up, one at a time. So if topology changes while we're cleanup compacting a given SSTable, only the next compaction will be aware of the topology changes.
