### ISSUE TITLE
Alternator return an error for create-table, but the table is created

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#6809]
*Installation details*
Scylla version (or git commit hash): 4.1.0
OS (RHEL/CentOS/Ubuntu/AWS AMI): Docker

I came across this while testing isolation level, but its probably not spesfic

1. creating a table with a wrong `system:write_isolation` parameter, and failed, as expected.

```
~$ aws  --endpoint-url 'http://127.0.0.1:8000'  dynamodb create-table --table-name IsoMusicTest1 --attribute-definitions AttributeName=Artist,AttributeType=S AttributeName=SongTitle,AttributeType=S --key-schema AttributeName=Artist,KeyType=HASH AttributeName=SongTitle,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --tags Key=system:write_isolation,Value=no-such-value

An error occurred (ValidationException) when calling the CreateTable operation: Incorrect write isolation tag no-such-value. 
```

2. Fix the error, and try again: Table already exists

```
Allowed values: {unsafe_rmw, u, only_rmw_uses_lwt, always_use_lwt, o, a, always, forbid_rmw, forbid, unsafe, f}
~$ aws  --endpoint-url 'http://127.0.0.1:8000'  dynamodb create-table --table-name IsoMusicTest1 --attribute-definitions AttributeName=Artist,AttributeType=S AttributeName=SongTitle,AttributeType=S --key-schema AttributeName=Artist,KeyType=HASH AttributeName=SongTitle,KeyType=RANGE --provisioned-throughput ReadCapacityUnits=5,WriteCapacityUnits=5 --tags Key=system:write_isolation,Value=a

An error occurred (ResourceInUseException) when calling the CreateTable operation: Keyspace for table IsoMusicTest1 already exists
```

**Comment by tzach** [comment]
@nyh ?

**Comment by nyh** [comment]
It is a known bug (#6391) that creating a table with tags is not atomic - the table may be created but the tags writing fails - and the whole operation appears to fail.
However, even before solving #6391, we should probably solve this specific case, which is easier to solve, and more likely to happen, than some rare failure scenario.
I'll write a test case and send a patch.

**Comment by nyh** [comment]
Sent a patch titled "alternator: CreateTable with bad Tags shouldn't create a table" for this issue. The patch includes two test cases for reproducing this issue, and a fix.

**Comment by nyh** [comment]
Backported to next-4.2 (8c929a96cf44484462517020762a2b08cec508ae).
Backporting to older branches, 4.1 and 4.0, is more difficult because the code in this area changed, and not worth it for this minor error-path improvement.
