### ISSUE TITLE
The describe_ring API missing information

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#681]
An example for a single token_range out of the describe_ring API:
{"end_token": "", "start_token": "", "endpoint_details": [{"datacenter": "datacenter1", "host": "127.0.0.2", "rack": "rack1"}], "endpoints": ["127.0.0.2"], "rpc_endpoints": ["Value(127.0.0.2,3)"]}

start_token and end_token are missing
rpc_endpoints should have X.X.X.X format

**Comment by tzach** [comment]
Works fine with scylla 0.15
