### ISSUE TITLE
alternator conditional write error on ComparisonOperator NULL

### ISSUE THREAD

**Issue by brackxm** [scylladb/scylla#6816]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 666.development-0.20200707.4c221855a14
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): docker

a PutItem with a not exists condition (ComparisonOperator NULL) fails with the following error
"With ComparisonOperator, AttributeValueList must be given and an array"
using the aws java SDK 1.11.747

alternator checks that AttributeValueList is empty
https://github.com/scylladb/scylla/blob/master/alternator/conditions.cc#L453
but the java client does not send a value

an AttributeValueList is not required
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_ExpectedAttributeValue.html#DDB-Type-ExpectedAttributeValue-AttributeValueList

the same issues probably also applies to an exists condition (ComparisonOperator NOT_NULL)
https://github.com/scylladb/scylla/blob/master/alternator/conditions.cc#L456

**Comment by nyh** [comment]
Thanks! I'll start fixing this (and writing a test) now.

**Comment by nyh** [comment]
This test case reproduces this bug. I'm working on a patch now.
```python
# When ComparisonOperator = "NULL", AttributeValueList should be empty if it
# exists, but as this test verifies, it may also be missing completely.
def test_update_expected_1_null_missing_list(test_table_s):
    p = random_string()
    test_table_s.update_item(Key={'p': p},
        AttributeUpdates={'a': {'Value': 2, 'Action': 'PUT'}},
        Expected={'a': {'ComparisonOperator': 'NULL'}})
    assert test_table_s.get_item(Key={'p': p}, ConsistentRead=True)['Item']['a'] == 2
```

**Comment by nyh** [comment]
Patch on the mailing list - titled "alternator: fix Expected's "NULL" operator with missing AttributeValueList"

**Comment by avikivity** [comment]
@nyh please evaluate for backport

**Comment by nyh** [comment]
Backported to next-4.2 (43169ffa2c26324587de85b02f27b727fe5c1d9a) and next-4.1 (d5e5a6fe480ebe92b13deae4e24eb6f42bfd8f37)
