### ISSUE TITLE
many cdc tests fail after "merge: cdc: better pre/postimages for complicated batches"

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6822]
There is an avalanche of cdc dtest failures post 9042161ba3971de8bfd9067d9c610291a872aa13
See https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/549/testReport/cdc_types_test/
and https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/549/testReport/cdc_tests/

**Comment by bhalevy** [comment]
Cc @haaawk @nyh

**Comment by piodul** [comment]
The PR fixing this waits for review/merge: https://github.com/scylladb/scylla-dtest/pull/1589

**Comment by bhalevy** [comment]
Closing this issue since the tests need fixing
