### ISSUE TITLE
filter_by_counter_test: Expected [[0, 4, 4, None]] from select * from clicks where c1 > 3 and c2 = 0 ALLOW FILTERING, but got []

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6824]
Regression since b0698dfb38afacbd3daf8f64ec83e63ba0ce0cd9 (`Merge 'Rewrite CQL3 restriction representation' from @dekimir `)
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/549/testReport/cql_additional_tests/TestCQL/filter_by_counter_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cql_additional_tests.py", line 701, in filter_by_counter_test
    expected=[[0, 4, 4, None]])
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1524, in inner
    return func(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/assertions.py", line 89, in assert_all
    assert list_res == expected, "Expected %s from %s, but got %s" % (expected, query, list_res)
AssertionError: Expected [[0, 4, 4, None]] from select * from clicks where c1 > 3 and c2 = 0 ALLOW FILTERING, but got []
```

seems to be 100% reproducible.

@dekimir there should be no functional change evident from changing the representation of the cql restrictions, right?

**Comment by bhalevy** [comment]
Cc @eliransin

**Comment by dekimir** [comment]
> there should be no functional change evident from changing the representation of the cql restrictions, right?

Incorrect, please see #6382.  This test should be adjusted to reflect the new behaviour.

I'm not sure how it slipped past me, I'm positive I ran all the `cql_*` dtests at one point, and they all passed.

**Comment by bhalevy** [comment]
@dekimir there a few more tests that need adjusting apparently due to changed exception text:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/549/testReport/deletion_test/RangeDeletionTester_with_SizeTieredCompactionStrategy/update_by_1ck_range_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/549/testReport/deletion_test/RangeDeletionTester_with_TimeWindowCompactionStrategy/update_by_1ck_range_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/549/testReport/deletion_test/RangeDeletionTester/update_by_1ck_range_test/
```
Error message does not contain Invalid operator in where clause Restrictions (error = Error from server: code=2200 [Invalid query] message="Invalid operator in where clause ((ColumnDefinition{name=ck, type=org.apache.cassandra.db.marshal.SimpleDateType, kind=CLUSTERING_COLUMN, componentIndex=0, droppedAt=-9223372036854775808}) < 8000481a)")
```

**Comment by dekimir** [comment]
> there a few more tests that need adjusting apparently due to changed exception text:

Sorry about that.  Can you please file a separate bug for that?  It's unrelated to this scenario.

**Comment by bhalevy** [comment]
> > there should be no functional change evident from changing the representation of the cql restrictions, right?
> 
> Incorrect, please see #6382. This test should be adjusted to reflect the new behaviour.
> 
> I'm not sure how it slipped past me, I'm positive I ran all the `cql_*` dtests at one point, and they all passed.

@dekimir I see.  I'd consider adding another sub-test for 'c2', see below:
```diff
diff --git a/cql_additional_tests.py b/cql_additional_tests.py
index 317d483d..d0791757 100644
--- a/cql_additional_tests.py
+++ b/cql_additional_tests.py
@@ -698,7 +698,12 @@ class TestCQL(Tester):
         with self.subTest("Filter by counter column with more and equal condition", i=3):
             assert_all(session=session,
                        query=f"select * from clicks where c1 > 3 and c2 = 0 {MSG_ALLOW_FILTERING}",
-                       expected=[[0, 4, 4, None]])
+                       expected=[])
+
+        with self.subTest("Filter by counter column with equal condition", i=4):
+            assert_all(session=session,
+                       query=f"select * from clicks where c2 = 0 {MSG_ALLOW_FILTERING}",
+                       expected=[[1, 0, 0, 0]])
 
         with self.subTest("Filter by counter column with \"in\" and >= condition"):
             assert_all(session=session,
@@ -721,7 +726,7 @@ class TestCQL(Tester):
             session.execute("ALTER TABLE clicks ADD c3 counter")
             assert_all(session=session,
                        query=f"select count(*) from clicks where c3 = 0 {MSG_ALLOW_FILTERING}",
-                       expected=[[10]])
+                       expected=[[0]])
 
             session.execute(f"UPDATE clicks SET c3 = c3-1 WHERE pk=0 and ck=1")
             assert_all(session=session,
@@ -736,7 +741,7 @@ class TestCQL(Tester):
 
             assert_all(session=session,
                        query=f"select * from clicks where c1 = 0 {MSG_ALLOW_FILTERING}",
-                       expected=[[1, 0, 0, 0, None], [1, 1, None, 1, None], [0, 0, 0, None, None]])
+                       expected=[[1, 0, 0, 0, None], [0, 0, 0, None, None]])
 
     @attr('single_node')
     def counters_test(self):
```

**Comment by bhalevy** [comment]
Closing this issue as the dtests need fixing.
