### ISSUE TITLE
Do not allow a node to join with a different snitch

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#6832]
Scylla version (or git commit hash): 4.x

Having nodes in the same cluster using different snitch does not make sense.
If a user forgot to set the endpoint_snitch before starting the service, the node might join in the wrong DC/Rack, which take time to fix later.
Instead, Scylla can test the snitch, similar to the cluster_name snitch.
Note that [rolling snitch switch is not supported](snitch) so this does not add a risk.

**Comment by dyasny** [comment]
How will the node decide which snitch is the correct one? If I have two nodes, each started with a different snitch, which node will stay up and which will go down with an error?

**Comment by tzach** [comment]
Only one node is joining the cluster
Its the same problem as two nodes with different cluster name

**Comment by dyasny** [comment]
Different cluster name means they don't belong together, end of story.  Same cluster name but different snitches is more problematic IMO. Unless the first node that comes up sets the snitch definition for the whole cluster, and then all the joining nodes have to either fit in or stay down.

**Comment by vladzcloudius** [comment]
Having the ability to have mixed snitches is normal practice and is a very strong tool in the field.
These patches introduced a terrible regression.

**Comment by vladzcloudius** [comment]
Ref https://github.com/scylladb/scylla/issues/8302
