### ISSUE TITLE
CDC: need option to turn off delta values

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#6838]
It running CDC with either pre- or postimage, there might be situations where we simply don't care about the delta info.
One very poignant example is alternator streams, where one pre and/or post data is needed.
Conversely, it might be useful to have an option "keys only" that records delta, but only PK/CK data.

Suggest adding additional parameters to the CDC ext settings struct, that (default full delta) has "mode" flag for delta (off, keys, full).

**Comment by avikivity** [comment]
Enhancement, not backporting.
