### ISSUE TITLE
compaction should print a unique id to correlate start and finish log messages

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6840]
class compaction can have a time-uuid that would be printed in `report_start` and `report_finish` to correlated the respective messages, other we can't tell the ancestors of the compacted sstable.  We now just now how many sstables were the input for it.

**Comment by raphaelsc** [comment]
The need of having this implemented becomes more evident with parallel compaction. It's really hard to correlate the compaction end with the compaction start in the logs.

**Comment by avikivity** [comment]
We can use the same uuid that is the key for the compaction history table.
