### ISSUE TITLE
Test failure: cql/cdc_allow_dropping_manually_created_log_test

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla#6852]
Regression was introduced in commit 61f52da9b1c53da6dad25cc90f22a98df56e752c

The `cql/cdc_allow_dropping_manually_created_log_test` fails with the following message:

```
Test cql/cdc_allow_dropping_manually_created_log_test (dev) failed: test output does not match expected result
--- test/cql/cdc_allow_dropping_manually_created_log_test.result	Tue Apr 14 16:51:04 2020
+++ test/cql/cdc_allow_dropping_manually_created_log_test.reject	Thu Jul 16 10:35:13 2020
@@ -1,9 +1,10 @@
 create table ks.test_scylla_cdc_log (pk int primary key);
 {
 	"status" : "ok"
 }
 -- Should be possible to drop it
 drop table ks.test_scylla_cdc_log;
 {
-	"status" : "ok"
+	"message" : "std::_Nested_exception<no_such_column_family> (Can't find a column family test in keyspace ks)",
+	"status" : "error"
 }

```

**Comment by haaawk** [comment]
@nyh it might make sense to revert the alternator streams change and wait for @elcallio to fix it.

**Comment by piodul** [comment]
@haaawk I'm not sure it will be necessary - I identified the problematic place in code and will submit a patch in a second.

**Comment by nyh** [comment]
No need to backport - this fixes a regression introduced by Alternator Streams, which we never backported to any release.
