### ISSUE TITLE
Ninja target `dev-test` should rebuild target `scylla`

### ISSUE THREAD

**Issue by dekimir** [scylladb/scylla#6855]
One of the tests that `dev-test` runs is [alternator/run](../blob/master/test/alternator/run), which stands up a Scylla server to query.  This means that `dev-test` should rebuild `build/dev/scylla`, but it doesn't.

**Comment by nyh** [comment]
`configure.py` has the lines:
```
        f.write(
            'build {mode}-test: test.{mode} {test_executables} $builddir/{mode}/test/tools/cql_repl\n'.format(
                mode=mode,
                test_executables=' '.join(['$builddir/{}/{}'.format(mode, binary) for binary in tests]),
            )
        )
```
Indeed, we also need `$builddir/{mode}/scylla` in that list, not just `cql_repl` and the test executables.

**Comment by avikivity** [comment]
developer ergonomics, not backporting
