### ISSUE TITLE
mutation_reader_test.test_queue_reader abandons fill_buffer_fut

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6858]
Test was introduced in 2ccd8ee47ce
It needs to get fill_buffer_fut.

This was already fixed in master by @espindola in 6fe7706fce19f666d7ba1d7ce5a3e7730bb31b09

Refs https://github.com/scylladb/scylla/issues/6831

**Comment by bhalevy** [comment]
The issue appears to have been there since version 3.2 but I guess it was exposed by gcc 10, similar to 543a9ebd9b55af459964e366038702d2538b52a1

**Comment by bhalevy** [comment]
Failing consistently in next-4.2 since https://jenkins.scylladb.com/view/scylla-4.2/job/scylla-4.2/job/next/38/

**Comment by avikivity** [comment]
Closing, since fixed in master.
