### ISSUE TITLE
nodetool bash complete does not work

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#686]
nodetool version which come with Scylla does not works with bash completion.
It does work with Cassandra, and its very useful.

To reproduce:
- install scylla-tools
- try auto complete, this is what you SHOULD get:
```
$ nodetool st[TAB][TAB]
status        statusbinary  statusthrift  stop          
$ nodetool sta[TAB]
nodetool status
$ nodetool cleanup [TAB]
system  keyspace1
```

tested with scylla 0.13.2

**Comment by slivne** [comment]
with which version of cassandra is this working for you - 2.1.8 ?

**Comment by tzach** [comment]
> with which version of cassandra is this working for you - 2.1.8 ? 

I'm not working with Cassandra at all, just scylla and the nodetool which come with it.
The /etc/bash_completion.d/nodetool is missing when installing from RPM

The relevant Cassandra ticket
https://issues.apache.org/jira/browse/CASSANDRA-6421

**Comment by slivne** [comment]
thanks so this is a dist issue

**Comment by tzach** [comment]
@syuu1228 any update on this? its really hurt UX

**Comment by syuu1228** [comment]
Fixed at https://github.com/scylladb/scylla-tools-java/commit/cf4f35ba82b83e6fcb7e81b35d7b2dce5133b280

**Comment by syuu1228** [comment]
Also for Ubuntu https://github.com/scylladb/scylla-tools-java/commit/7e5bd9e000fa01fd858c462902916b9be8588a96

**Comment by syuu1228** [comment]
@tzach please close this.
