### ISSUE TITLE
alternator streams write fails when attempted too early

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#6864]
The test `test_streams.py::test_get_records`, when run alone with a command line such as
```
test/alternator/run --runxfail test_streams.py::test_get_records
```
seems to always fail. The relevant error lines:
```
>           table.put_item(Item={'p': p, 'c': c, 'a1': val, 'a2': val2})
test_streams.py:318: 
E           botocore.exceptions.ClientError: An error occurred (Internal Server Error) when calling the PutItem operation (reached max retries: 3): Internal server error: std::runtime_error (cdc::metadata::get_stream: could not find any CDC stream (current time: 2020/07/16 17:49:53). Are we in the middle of a cluster upgrade?)
```

Because of these failures I marked this test "xfail".

However, if the entire Alternator test suite is run (just `test/alternator/run` without parameters), and `test_streams.py` comes near the end, this test always passes! (i.e., it is listed as an XPASS in the complete run).

I suspect that this is some sort of CDC initialization timing issue - perhaps the test cannot succeed if run before CDC finished to initialize itself. If this is the case, we will need to add to the relevant Alternator Streams API requests the code to wait until CDC initialization is complete, instead of failing with bizarre exceptions.

CC @elcallio

**Comment by elcallio** [comment]
It is most definitely init issues. @kbr - we apparently can both create a table with CDC log enabled and start writing to it, before the CDC streams set has been created. In this case we get the above exception when trying to get streams in `log.cc:begin_timestamp`. Should not something somewhere in this path wait for the cluster to have CDC finished enabled? I cannot see anything to really wait on? Am I missing something?

**Comment by elcallio** [comment]
Verified that we do in fact have a generation, but it is not valid for the timestamp in the write.

**Comment by haaawk** [comment]
Cool. @kbr- Could you please implement one of the solutions we discussed on the call? Either a check that the generation contains only streams for a single node or changing delay from 2*ring delay + epsilon to 2 * ring delay.

**Comment by elcallio** [comment]
I think we should also consider letting writes to CDC enabled tables silently fail adding CDC log, but succeed the main write, if streams are not available yet. This would be neatly consistent with dynamos concept of streams being in a "enabling" status for a while until they actually collect data.

**Comment by haaawk** [comment]
I guess we could special case this just for dynamo streams

**Comment by elcallio** [comment]
No, we should avoid special casing. The problem is somewhat ludicrous anyway, since it only affects new servers on first start. My thought was that a logged, but non-exceptional fail/ignore of CDC log write would be just as good as throwing, but less intrusive. If I would offer any reasoning it would be that CDC in general should be non-intrusive, i.e. "soft" failures in CDC can lead to CDC log gaps, but should maybe not affect "main" write path. Not sure if that is a good approach or not though.

**Comment by haaawk** [comment]
You've got the point. @kbr- what's your take on this?

**Comment by nyh** [comment]
> I think we should also consider letting writes to CDC enabled tables silently fail adding CDC log, but succeed the main write, if streams are not available yet. This would be neatly consistent with dynamos concept of streams being in a "enabling" status for a while until they actually collect data.

We could do this, indeed. As you said, DynamoDB provides a way to check if the writes will get to the log (waiting for the status of the stream to change from ENABLING) and we'll need to implement this feature. But don't you also need a similar feature in CQL? Or is it acceptable that you enable CDC but writes in the next minute (2*gossip_delay) don't end up in the CDC log? Maybe we just don't care because it's a very esoteric problem - it only happens on the first minute of the first boot?

By the way, how did you not have these problems in dtests? Or are they so slow, that a whole minute passes before they even start? :-)

**Comment by haaawk** [comment]
I think in dtests we either used sleep before we started writing or we shortened delay.

**Comment by elcallio** [comment]
I sent a patch to make alternator streams report streams as not yet available iff CDC id:s don't exist yet. Even if we change the rules for writes/id gen I think this should be the way to treat this from the alternator end. For bookkeep sake I did not mark the PR as "fixing" this issue, even though it fixes the OP problem of single `get_records` test failing on a new instance.

**Comment by kbr-** [comment]
> You've got the point. @kbr- what's your take on this?

I'm against silently introducing inconsistencies.
The CDC log is supposed to reflect changes made to the base table, and it should be possible to replicate the base table using the log.

I'm for computing the generation timestamp delta as follows:
```
delta = (ring_delay || unit_testing) ? (2*ring_delay + leeway) : 0
```

**Comment by kbr-** [comment]
> By the way, how did you not have these problems in dtests? Or are they so slow, that a whole minute passes before they even start? :-)

```
        gen_timestamp = self.wait_for_last_generation_to_be_active(session)
```
where
```
    def wait_for_last_generation_to_be_active(self, session):
        cdc_descriptions = list(self.get_cdc_description_rows(session))
        self.assertGreater(len(cdc_descriptions), 0, "No CDC generations")
        last_timestamp = max(desc.time for desc in cdc_descriptions)

        # Add one second to account for clock differences
        self.sleep_until(last_timestamp + timedelta(seconds=1))
        debug('Current generation timestamp: {}'.format(last_timestamp))
        return last_timestamp
```
