### ISSUE TITLE
bogus size reports from resharding compaction

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#6885]
I see this:

```
INFO  2020-07-21 11:35:36,981 [shard 1] compaction - [Reshard system.compaction_history 268ca5e0-cb2d-11ea-b74c-000000000001] Resharded 1 sstables to [/var/lib/scylla/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/mc-222-big-Data.db:level=0, /var/lib/scylla/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/mc-223-big-Data.db:level=0, /var/lib/scylla/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/mc-227-big-Data.db:level=0, /var/lib/scylla/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/mc-225-big-Data.db:level=0, /var/lib/scylla/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/mc-212-big-Data.db:level=0, /var/lib/scylla/data/system/compaction_history-b4dbb7b4dc493fb5b3bfce6e434832ca/mc-226-big-Data.db:level=0, ]. 108kB to 560kB (~515% of original) in 87ms = 6MB/s. ~256 total partitions merged to 171.
```

Indicating a bloat of 515% after resharding (2 -> 12 shards). Doesn't seem reasonable.

commit e4deaaced3d7240190a0aeecb002d82f54cb4c0f

**Comment by bhalevy** [comment]
@raphaelsc please look into this

**Comment by bhalevy** [comment]
@avikivity can you please upload the whole node log?

**Comment by avikivity** [comment]
[log.gz](https://github.com/scylladb/scylla/files/4965206/log.gz)

Example:

 ```
INFO  2020-07-23 12:50:37,436 [shard 0] compaction - [Reshard system_traces.events f5e638e0-ccc9-11ea-805c-000000000000] Resharded 1 sstables to [/var/lib/scylla/data/system_traces/events-8826e8e9e16a372887533bc1fc713c25/mc-247-big-Data.db:level=0, /var/lib/scylla/data/system_traces/events-8826e8e9e16a372887533bc1fc713c25/mc-248-big-Data.db:level=0, ]. 96kB to 173kB (~180% of original) in 14ms = 12MB/s. ~128 total partitions merged to 30.
```

**Comment by raphaelsc** [comment]
I'd bet almost all my coins that it's related to bad partition estimation.
I will investigate it soon.

**Comment by raphaelsc** [comment]
scylla metadata is apparently growing like never before, probably a regression after off-strategy changes, i will investigate

input sst 111 [
  data   = 9kB
  index  = 3kB
  filter = 1kB
  summar = 92 bytes
  scylla = 78 bytes
] 

output sst 116 [
  data   = 4kB
  index  = 1kB
  filter = 176 bytes
  summar = 92 bytes
  scylla = 88kB
] 
output sst 117 [
  data   = 5kB
  index  = 2kB
  filter = 176 bytes
  summar = 92 bytes
  scylla = 87kB
]

**Comment by raphaelsc** [comment]
that seems like expected behavior. when you change smp count from M to N, where N > M, the sharding metadata of the resharding sstable may grow bigger as a result of splitting more the token range spanned by it. So if data size of input sstable is relatively small, we'll see compaction producing output which is bigger than input. This problem will not happen with reasonably sized sstables, as a result.

**Comment by avikivity** [comment]
Ah, does the report include all components?

If so it makes sense.

**Comment by raphaelsc** [comment]
> Ah, does the report include all components?

yes

> 
> If so it makes sense.

**Comment by avikivity** [comment]
Closing as invalid.
