### ISSUE TITLE
Test tracing of Alternator queries

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#6891]
In https://github.com/scylladb/scylla/issues/6689#issuecomment-661763063 a user ran Alternator queries with tracing enabled, and @avikivity theorized that it "Looks like alternator doesn't propagate the trace session correctly". 

The commit where @psarna added tracing support to Alternator was commit 8d27e1b4a9db7210674da0e581daebf1325e1589 and the commit message had an example of that tracing working. However, it appears that we do not have a test for this so I can't verify that nothing broke this support later.

We should create a test for tracing with Alternator, and confirm that it still works (and if it doesn't, fix it!). It will be great if we could do this in pytest. This will require a CQL driver, not just the DynamoDB driver, but we can skip this test if not running against Alternator or the CQL driver is not installed (similar to the existing "scylla_only" fixture which skips a test if running against Amazon's DynamoDB). The other option instead pytest is to add such a test to the Alternator dtests which already use both the CQL and DynamoDB drivers (CC @fruch).

**Comment by nyh** [comment]
By the way, the commit which added tracing support to Alternator was commit 8d27e1b4a9db7210674da0e581daebf1325e1589. This commit also has an example of what a trace should look like.

**Comment by nyh** [comment]
I'm looking at this now, in the context of issue #6747. In that issue, one of the many guesses thrown around was that our GetItem implementation accidentally starts a scan query, even though it clearly requests just a single item. To know **really** happens during GetItem, I want to use tracing

**Comment by avikivity** [comment]
Not a bug, not backporting.
