### ISSUE TITLE
Alternator's get_key_from_roles has a use after return

### ISSUE THREAD

**Issue by espindola** [scylladb/scylla#6897]
The timeout variable is stack allocated but a reference to it is kept.

**Comment by avikivity** [comment]
@nyh please evaluate for backport

**Comment by nyh** [comment]
Backported to next-4.2 (f699d23f0b8dd59130b956f3f49f08fae05082d1) and to next-4.1 (f699d23f0b8dd59130b956f3f49f08fae05082d1)
