### ISSUE TITLE
cql server shutdown hangs forever

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#690]
I saw the following log which means ss.shutdown_client_servers().get() never returns (storage_service::do_stop_native_transport())

with jepsen test:    lein test :only cassandra.batch-test/batch-bridge-decommission 

ubuntu@ip-172-31-17-221:~/scylla-jepsen/jepsen/cassandra/store/latest$ grep -i decomm n*/system.log
n1/system.log:[Mon Dec 21 10:24:51 2015] DEBUG [shard 0] config - Option override_decommission not set
n2/system.log:[Mon Dec 21 10:24:51 2015] DEBUG [shard 0] config - Option override_decommission not set
n3/system.log:[Mon Dec 21 10:24:51 2015] DEBUG [shard 0] config - Option override_decommission not set
n4/system.log:[Mon Dec 21 10:24:51 2015] DEBUG [shard 0] config - Option override_decommission not set
n4/system.log:[Mon Dec 21 10:30:27 2015] DEBUG [shard 0] storage_service - DECOMMISSIONING
n4/system.log:[Mon Dec 21 10:30:57 2015] DEBUG [shard 0] storage_service - DECOMMISSIONING: before unbootstrap
n4/system.log:[Mon Dec 21 10:34:04 2015] DEBUG [shard 0] storage_service - DECOMMISSIONING: unbootstrap done
n5/system.log:[Mon Dec 21 10:24:51 2015] DEBUG [shard 0] config - Option override_decommission not set

**Comment by slivne** [comment]
related to #568

**Comment by penberg** [comment]
I am new to this code but don't we have an issue if the underlying ``file_desc::shutdown()`` fails (because the connection is already closed, for example) and throws an exception?

We propagate the error all the way down to ``storage_service::do_stop_native_transport()`` (and fail to shutdown input  directions in ``cql_server::connection::shutdown()`` btw) which breaks the future chain and always returns a ready future.

@avikivity?

**Comment by penberg** [comment]
Aah, I misread the code. ``do_stop_native_transport()`` *does* propagate the error to its caller.

**Comment by penberg** [comment]
There still seems to be an issue in ``cql_server::connection::shutdown``, though. If shutting down the input file descriptor throws an exception, we don't close the gate nor shut down the output file descriptor. Not sure it's related to this issue, though.

**Comment by avikivity** [comment]
shutdown should not throw, because it is often needed during error handling.  Since it doesn't wait for anything, it should really throw.

**Comment by asias** [comment]
On Mon, Jan 4, 2016 at 5:30 PM, Avi Kivity <notifications@github.com> wrote:

> shutdown should not throw, because it is often needed during error
> handling. Since it doesn't wait for anything, it should really throw.
>

We have:

  0 future<> cql_server::connection::shutdown()
  1 {
  2     _fd.shutdown_input();
  3     return _pending_requests_gate.close().then([this] {
  4         _fd.shutdown_output();
  5     });
  6 }

Why not:

  0 future<> cql_server::connection::shutdown()
  1 {
  2     try {
  3         _fd.shutdown_input();
  4         _fd.shutdown_output();
  5     } catch (...) {
  6         log the error
  7     }
  8     return _pending_requests_gate.close();
  9 }

Why do we close the gate in the middle?

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/690#issuecomment-168621222>.
>



-- 
Asias

**Comment by pdziepak** [comment]
Closing the gate waits for the outstanding requests, if shutdown_output() was called before closing the gate it would be pointless to wait for them since they won't be able to respond to the client anyway.

**Comment by penberg** [comment]
@avikivity Sorry, I am having difficulties parsing your reply. If you are saying that ``cql_server::connection`` should *not* throw, I completely agree.

**Comment by asias** [comment]
On Mon, Jan 4, 2016 at 5:37 PM, Paweł Dziepak <notifications@github.com>
wrote:

> Closing the gate waits for the outstanding requests, if shutdown_output()
> was called before closing the gate it would be pointless to wait for them
> since they won't be able to respond to the client anyway.
>

Ah, OK.

—
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/690#issuecomment-168622888>.
>



-- 
Asias

**Comment by asias** [comment]
With

commit 33fd0446093a807aebccfe7de06e118657bed7ec
Merge: 7c9f9f0 f646241
Author: Avi Kivity <avi@scylladb.com>
Date:   Mon Jan 4 11:03:01 2016 +0200

    Merge "Event notification exception safety" from Pekka

4 out of 4

lein test :only cassandra.batch-test/batch-bridge-decommission

test passed.

I do not see the cql shutdown hang any more.

**Comment by penberg** [comment]
Great! I'm closing the issue.

**Comment by gleb-cloudius** [comment]
On Mon, Jan 04, 2016 at 01:37:12AM -0800, Paweł Dziepak wrote:
> Closing the gate waits for the outstanding requests, if shutdown_output() was called before closing the gate it would be pointless to wait for them since they won't be able to respond to the client anyway.
> 
It would not be pointless to wait for them since they are holding
reference to cql connection, so cql connection object cannot be destroyed
before gate is closed. Closing connection itself is orthogonal - if we
do it before shutdown we will send all of the replies, if after we will
drop them.

--
			Gleb.

**Comment by asias** [comment]
I saw the hang again with decommission:

lein test :only cassandra.batch-test/batch-halves-decommission

```
[Thu Jan 14 10:38:57 2016] DEBUG [shard 0] storage_service - DECOMMISSIONING
[Thu Jan 14 10:39:27 2016] DEBUG [shard 0] storage_service - DECOMMISSIONING: unbootstrap starts
[Thu Jan 14 10:42:27 2016] DEBUG [shard 0] storage_service - DECOMMISSIONING: unbootstrap done
```

**Comment by asias** [comment]
Please reopen.

**Comment by asias** [comment]
@pdziepak @penberg  Please take a look. This fails decommission.
