### ISSUE TITLE
nodetool refresh throws error (link failed, file exists) affecting older versions

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6903]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.0.1 (DOESN'T AFFECT MASTER)
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

nodetool refresh potentially fails when called in sequence, like this:
ERROR 2020-07-15 13:11:35,885 [shard 0] storage_service - Loading of
new tables failed to keyspace4.standard1 due to filesystem error: link
failed: No such file or directory
[./data/data/keyspace4/standard1-a5e12920c60e11eaab49000000000000/mc-5374-big-TOC.txt]
[./data/data/keyspace4/standard1-a5e12920c60e11eaab49000000000000/mc-5447-big-TOC.txt.tmp]

It no longer affects master as this problem has a lot to do with the capability of loading SSTables from table's main dir and it was disabled by this commit 70e5252a5d5183a51635154b3aa602a4812c67ce

Quoting myself:

```
Reproduced this exact problem with a script as simple as this:
#!/bin/bash

table_dir=/home/raphaelsc/scylla/data/data/keyspace4/standard1-a5e12920c60e11eaab49000000000000
keyspace=keyspace4
table=standard1
from=$table_dir/backup
to=$table_dir/upload

for i in {1..10};
do
echo "Running iteration $i..."
echo "Cleaning $to"
rm -rf $to/*
echo "Creating links from $from to $to"
ln $from/* $to
echo "Refreshing keyspace $keyspace.$table"
/home/raphaelsc/scylla-tools-java/bin/nodetool refresh $keyspace $table
echo "Done with iteration $i"
done


ERROR 2020-07-15 13:11:35,885 [shard 0] storage_service - Loading of
new tables failed to keyspace4.standard1 due to filesystem error: link
failed: No such file or directory
[./data/data/keyspace4/standard1-a5e12920c60e11eaab49000000000000/mc-5374-big-TOC.txt]
[./data/data/keyspace4/standard1-a5e12920c60e11eaab49000000000000/mc-5447-big-TOC.txt.tmp]


The problem is the lack of synchronization between refresh and
resharding. This problem will not happen anymore after we stopped
accepting loading from the main directory. Because refresh will not
pick up the SSTables being operated by resharding. Backporting the
patch "table: no longer accept online loading of SSTable files in the
main directory" to older versions implies that we prevent their users
from relying on a feature that may be part of their application. On
older versions, refresh only proceeds after disabling writes for a
table using table::disable_sstable_write(), perhaps we should fix
disable_sstable_write() to only return after resharding is done for
this particular table. 
```

**Comment by raphaelsc** [comment]
closing this as the affected branches aren't really supported anymore and the supported ones aren't affected by the problem mentioned

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
