### ISSUE TITLE
reader_concurrency_semaphore: make inactive read handles unique per semaphore

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#6907]
Currently inactive read handles just contain an id (an integer), this id is they key to `reader_concurrency_semaphore::_inactive_reads` and is unique in the context of a single semaphore. However this id is not unique across all semaphores, so if one was to use this handle to lookup a paused reader in another semaphore, one might succeed. This is highly undesirable as the other reader can belong to another read altogether, it might read a different table altogether.

To prevent this we should also store a pointer to the semaphore in the handle and match this to the semaphore during lookup and bail out on mismatch.

**Comment by denesb** [comment]
HEAD: b4b9dea

**Comment by avikivity** [comment]
Backported to 4.2.
