### ISSUE TITLE
messaging_service: statement verbs are all registered with the system scheduling group

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#6908]
HEAD: b4b9deadf3ee4f581dc34b6f4bf2f79d2f2f06b9

Messaging service currently uses both old-style per handler isolation, as well as the new per-connection one. The per-handler isolation is used for backward compatibility with older versions, so hence it is used with the client indexes 0-3. Clients indexes 2 and 3 are the statement and statement-ack clients respectively, which since https://github.com/scylladb/scylla/commit/0c6bbc84cd30df1c46a6cd81d87170b99d5a8144 correspond to the default tenant (user statement). Handlers for these should be registered to be used with the statement scheduling group. When registering the handlers, we use `messaging_service::scheduling_group_for_verb()` to determine the scheduling group to be used for the handler. This in turn calls `messaging_service::get_rpc_client_idx()` to map the verb to the client index and then lookup the scheduling group to be used for it. `messaging_service::get_rpc_client_idx()` however relies on the current scheduling group to determine which client to use. This results in the scheduling groups used when registering the verbs determining the client to be used. This scheduling groups happens to be the one `storage_proxy::init_messaging_service()` is executed in, which is the main group, resulting in all statement verbs ending up executing in the main group.

**Comment by denesb** [comment]
This is a regression caused by https://github.com/scylladb/scylla/commit/0c6bbc84cd30df1c46a6cd81d87170b99d5a8144.

**Comment by avikivity** [comment]
Backported to 4.2.
