### ISSUE TITLE
Schema Backup/Restore/Snapshot 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#691]
#101 test data backup and restore
This issue is for schema backup and restore,  keyspace and tables.

**Comment by tzach** [comment]
@slivne can we close this?

**Comment by slivne** [comment]
not sure why it differs from #101 which is still open (although incremental for schema may not be done - no clue).

**Comment by tzach** [comment]
@slivne lets close both, and open a new issues for:
-  incremental backup
- schema backup testing
