### ISSUE TITLE
TWCS: compaction: partition estimate can become 0, causing an assert in sstables::prepare_summary()

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#6913]
HEAD: e7c18963e4bbb7bfecbe168b52e603db37ee8449

When using TWCS, the estimated partition calculation can result in 0 if the TWCS estimates that the amount of windows the compacted sstables will have to be split into is larger than the estimated amount of partitions in said sstables. This results in 0 being passed as the `estimated_partitions` parameter to the `sstables::component_writer` constructor, which then forwards it to `sstables::prepare_summary()` causing an assert in the latter, which asserts that the number of partitions is larger than 0.

This is a regression caused by https://github.com/scylladb/scylla/commit/098b215b0db07ba2f1b68c5bfcbfe006f70eb9b7.

**Comment by denesb** [comment]
This can be reproduced by triggering a compaction on with a set of sstables meeting this criteria. We can achieve this by a procedure like this:
* Create a table with TWCS
* Write one or more partition with several rows, rows should be dispersed among different windows using `WITH TIMESTAMP`.
* nodetool flush; it is important that at this point the memtable content has more time windows than partitions. Can be achieved by having each partition above more than one row, ensuring no two rows shared the same window.
* Repeat until there are enough sstables to trigger compaction.

**Comment by slivne** [comment]
reproducer

1. create a single node cluster

2. cqlsh

```
CREATE KEYSPACE ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;
CREATE TABLE ks.tb (
    k1 int,
    k2 int,
    value int,
    PRIMARY KEY (k1, k2)
) WITH CLUSTERING ORDER BY (k2 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': '1000', 'compaction_window_unit': 'MINUTES'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

 insert into ks.tb (k1, k2, value) values (1,1,1) using timestamp 1595575921924856;
 insert into ks.tb (k1, k2, value) values (1,2,1) using timestamp 1595575921930000;
 insert into ks.tb (k1, k2, value) values (1,2,1) using timestamp 1595575921950000;
 insert into ks.tb (k1, k2, value) values (1,2,1) using timestamp 1595575000050000;
 insert into ks.tb (k1, k2, value) values (1,3,1) using timestamp 1595575000070000;
 insert into ks.tb (k1, k2, value) values (1,4,1) using timestamp 1595576000070000;
 insert into ks.tb (k1, k2, value) values (1,5,1) using timestamp 1595578000070000;
 insert into ks.tb (k1, k2, value) values (1,8,1) using timestamp 1595570001070000;
 insert into ks.tb (k1, k2, value) values (1,9,1) using timestamp 1595570001270000;
 insert into ks.tb (k1, k2, value) values (1,10,1) using timestamp 1595570001470000;
 insert into ks.tb (k1, k2, value) values (1,11,1) using timestamp 1595570001670000;
```

3. nodetool flush

4. cqlsh 
```
alter TABLE ks.tb WITH compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': '1', 'compaction_window_unit': 'MINUTES'} ;
```

5. nodetool compact ks

**Comment by avikivity** [comment]
Backported to 4.1, 4.2.
