### ISSUE TITLE
TLS server setup (CQL/RPC) should not use explicit DH parameters

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#6922]
GnuTLS since version 3.6 discourages use of explicit DH parameters for server credentials setup. Instead, a server should rely in the TLS init string and client negotiation to select from appropriate DH table. (https://www.gnutls.org/manual/gnutls.html#RFC7919).

Recent seastar (/scylladb/seastar#769) supports omitting DH in server credentials setup, and we have relocatable init string + init string user config support for quite a while. 

We should drop the DH usage in TLS server setup.

**Comment by slivne** [comment]
@elcallio was this fixed ? if so can you reference the commit that fixed it

**Comment by elcallio** [comment]
This was fixed in seastar, by changing the dh param init to act as a "minimum required" instead of actual calclulated hash set. 
https://github.com/scylladb/seastar/commit/02ad74fa7d100cf0a032c52e3d77f12f3396d814

No changes required in scylla.
