### ISSUE TITLE
Potential memory corruption because index reader fails to handle failure properly

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6924]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 5371be71e905
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

Turns out that index reader is not handling failure properly as it's not closing all the input streams that were used during the operation (specifically the ones used for promoted index reading), so memory is potentially corrupted as the forgotten read ahead workers will be operating on freed memory.

**Comment by raphaelsc** [comment]
Patch sent to mailing list: [PATCH] sstable: index_reader: Make sure streams are all properly closed on failure

**Comment by raphaelsc** [comment]
Patch sent to seastar mailing list to convert memory corruption bugs which result from read ahead impl into aborts: https://groups.google.com/g/seastar-dev/c/6u9pTucsWSk/m/icLLBL9gAAAJ

**Comment by avikivity** [comment]
Backported to 4.0, 4.1, 4.2.
