### ISSUE TITLE
View building needs to handle incorrect values in its system tables

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#6934]
Currently, view building assumes that its helper system tables, e.g. `system.scylla_views_builds_in_progress`, contain certain values. If the values weren't there the system was prone to segfaulting (#6915), but now the failure ends with an exception. That's still not enough for smooth user experience though, since view building should not be permanently stopped once it encounters incorrect values (e.g. NULL) in its tables, or when querying the local table failed for any other reason. It's better to place an error message in the logs and proceed as if no views were in progress, which would at least allow future views to be built without issues.

**Comment by avikivity** [comment]
Edge case, so not backporting. Usually there are no bad contents in system tables.

**Comment by nyh** [comment]
@psarna you didn't say in this issue how you reached this problem and what the error messages looks like. In issue #8042 a user of 4.2 (to which we never backported this fix) reported a node not coming up because of view_builder failing to start, with the message:
```
Feb 06 16:54:54 scylla2 scylla[25650]: [shard 4] view - start failed: boost::wrapexceptboost::bad_lexical_cast (bad lexical cast: source type value could not be interpreted as target)
```
could this be the same issue as this one, or did this one look different?

**Comment by psarna** [comment]
@nyh I wish I remembered... but it sounds very probable. If the user can send the `sstabledump` output from these view-specific system tables it could help identify the issue, and there's always the option of deleting the data from these system tables and let the view building process start from scratch.

It's a pity boost didn't include the source value in this error message (since it was likely a string)...
