### ISSUE TITLE
Alternator Streams: OldImage is missing the old item's key

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#6935]
As checked by `test_streams.py::test_streams_updateitem_old_image`, DynamoDB Streams includes the entire old item - including its key - as the value of OldImage when OLD_IMAGE mode is enabled. Alternator is missing the key columns in this item. (note that OldImage should only exist and contain the key if an old item actually existed - see #6933). 

The good news is that this test confirms Alternator does include in OldImage all the other (non-key) attributes. I was worried it might include only the modified columns, because this is what our CDC's "preimage" supposedly provides. It works because in cases like this test, not involving an LSI or GSI, all non-key attributes are not actual Scylla columns, but rather just members of a map - and CDC preimage gives the entire contents of the map when it's modified - not just modified items in the map. We will need a separate test to check the LSI case (and separate issue to report it broken).

**Comment by nyh** [comment]
Ok, I understand what causes this "miracle"... The thing is, normally all of the non-key columns are not regular Scylla columns, but rather cells in a map (the ":attrs" map). Apparently, when a map is modified, the CDC preimage includes the **entire contents of the map**, not just the modified cells. Which is surprising (and undocumented), but fortunate in this case.

Unfortunately it means this miracle will not happen when one of the non-key columns is a regular column - and this column will be missing in the OldImage. This case happens when we have an LSI, and we store the LSI's key as a regular column in the base table :-( I'll need to create a separate test to confirm this.

**Comment by elcallio** [comment]
Look at `attr_names` in `get_records`. All regular columns are included, which will include LSI attributes.

**Comment by elcallio** [comment]
And the code most definitely adds keys to the record (line 779). Please share the test that you ran to produce a faulty result.

**Comment by nyh** [comment]
> Look at `attr_names` in `get_records`. All regular columns are included, which will include LSI attributes.

But I don't understand how this is possible, if the underlying CDC "preimage" feature only includes in the preimage the **modified** columns. If we have an attribute which is a stand-alone, regular, column (which is the case of an attribute which is an LSI key but a regular column in the base table), CDC will simply not include it in the preimage, so you will not have it. What am I missing?

**Comment by nyh** [comment]
> And the code most definitely adds keys to the record (line 779). Please share the test that you ran to produce a faulty result.

You're right. I should publish the xfailing test. I'll try to do this now. It requires some cleanup because of the 10 second issue required me to do some ugly (and slow!) sleeps I don't want to keep.

**Comment by elcallio** [comment]
Ah, yes, current preimage is only modified data. This is true. But if I am not mistaken, this will probably change. So for now, this is a discrepancy, but perhaps not forever.

**Comment by avikivity** [comment]
@nyh please evaluate for backport.

**Comment by nyh** [comment]
Alternator Streams was not yet in 4.2, so no need to backport.
