### ISSUE TITLE
Improve log on removing pending replacing node

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#6936]
The log "removing pending replacing node" is printed whenever a node
 jumps to normal status including a normal restarts. For example, on
 node1, we saw the following when node2 restarts.
 
 [shard 0] storage_service - Node 127.0.0.2 state jump to normal
 [shard 0] storage_service - Remove node 127.0.0.2 from pending replacing endpoint
 
 This is confusing since no node is really being replaced.

**Comment by avikivity** [comment]
Cosmetic, not backporting.
