### ISSUE TITLE
Alternator Streams: last result is returned again and again

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#6942]
For an application to read from a DynamoDB stream it does something like the following: It gets an "iterator" for a shard, uses `GetRecords` on this iterator, gets back some results plus a new iterator in the `NextShardIterator`  to use on the next read.

The current implementation has an interesting bug: After you read a few results from a shard, if you read again (using the previously returned new NextShardIterator) and if there is no new content to read - instead of getting nothing, you get the last result again. And again. And again. Forever.

Moreover, in this case, the new NextShardIterator is identical to the input one, which explains why this becomes an endless loop.

I'm pretty sure I understand the cause of this bug. I am guessing it's a combination of two factors:

1. The NextShardIterator is calculated as the last timestamp that was output. Note that it's the last timestamp, without + 1.
2. In the next iteration, we probably look for the relevant records using >= on the timestamp, not >.

I have a reproducer for this bug as part of a bigger test, I'm now working on writing a test just for it.

CC @elcallio

**Comment by nyh** [comment]
This test reproduces this bug. I'm still trying to clean up my mass (or mess) of tests and send them all as a patch - if I just don't run into more bugs while doing that :+1: 

```python
# Test that after fetching the last result from a shard, we don't get it
# yet again. Reproduces issue #9642.
def test_streams_last_result(test_table_ss_keys_only, dynamodbstreams):
    table, arn = test_table_ss_keys_only
    iterators = latest_iterators(dynamodbstreams, arn)
    # Do an UpdateItem operation that is expected to leave one event in the
    # stream.
    table.update_item(Key={'p': random_string(), 'c': random_string()},
        UpdateExpression='SET x = :val1', ExpressionAttributeValues={':val1': 5})
    # Eventually (we may need to retry this for a while), *one* of the
    # stream shards will return one event:
    timeout = time.time() + 15
    while time.time() < timeout:
        for iter in iterators:
            response = dynamodbstreams.get_records(ShardIterator=iter)
            if 'Records' in response and response['Records'] != []:
                # Found the shard with the data! Test that it only has
                # one event and that if we try to read again, we don't
                # get more data (this was issue #6942).
                assert len(response['Records']) == 1
                assert 'NextShardIterator' in response
                response = dynamodbstreams.get_records(ShardIterator=response['NextShardIterator'])
                # Records should be empty now, but because of issue #6926 can also be missing
                if 'Records' in response:
                    assert response['Records'] == []
        time.sleep(0.5)
```

**Comment by elcallio** [comment]
You are not updating `iterators`. You are literally selecting the same records each lap.

**Comment by elcallio** [comment]
Is that intentional?

**Comment by elcallio** [comment]
Missing your fixture to be able to run the above. But if you use a fixture you can't really be sure the streams only hold a single item. I think you need to create a new table for the test.

**Comment by nyh** [comment]
> You are not updating `iterators`. You are literally selecting the same records each lap.

The idea of this test is that we have many iterators (512 in my test setup), but we did only one write and only one of these iterators will *ever* see any activity. We retry the same iterator again and again (no need to change them) until finally we see **one** iterator with data. This one - we check. We get the NextShardIterator and try to read from it, and see that we get the same item yet again. I think I described the situation clearly (and my guess as to why it happens) in the issue above. I just sent an RFC patch which includes this test and all others, so you can try running it for yourself.

**Comment by nyh** [comment]
> But if you use a fixture you can't really be sure the streams only hold a single item. I think you need to create a new table for the test.

I thought I got around this issue by making sure I am using the "LATEST" iterator, which supposedly doesn't include old data, but it turns out that although all my tests pass individually on Amazon, when running all of them not all of them pass. So indeed it may be too risky to use fixtures. Or rather - "session" fixtures. We can still use function-scope fixtures (`@pytest.fixture(scope="function")`) those get recreated separately for each test. I'll think about it. In any case, the fixture problem (or advantage...) is a non-issue if you run a single test each time (you can pass "pytest" or "test/alternator/run" the name of a specific test - e.g., 
```
pytest -vs --runxfail --aws test_streams.py::test_streams_updateitem_keys_only test_streams.py::test_streams_updateitem_keys_only
```

**Comment by nyh** [comment]
Not backporting - the Alternator Streams feature is in master but not yet in 4.2.
