### ISSUE TITLE
UX: scylla_setup: include swap size in the prompt

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#6947]
*Installation details*
Scylla version (or git commit hash): 666.development-0.20200727.a7df8486b
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

Current prompt: 
```
No swap is configured, it is highly recommended to setup swap on Scylla node.
Do you want to configure swapfile?', 'Answer yes to setup swapfile to Scylla, Answer no to do nothing.
```

Problem:
- The swap size is calculated automatically after user inputs the directory and confirms. User doesn't know how much space will be used.

Suggestion:
- include the swap size in the prompt

```
No swap is configured, it is highly recommended to setup swap on Scylla node.
Do you want to configure swapfile?', 'Answer yes to setup swapfile (xxG) to Scylla, Answer no to do nothing.
```

@tzach

**Comment by roydahan** [comment]
I would say even to check how much free disk space is available and if there is not enough free space, to warn the user and give the option to exit the setup and extend the disk space.

**Comment by amoskong** [comment]
> I would say even to check how much free disk space is available and if there is not enough free space, to warn the user and give the option to exit the setup and extend the disk space.

Currently if the assigned directory doesn't have enough space, the dd cmd will fail, and scylla_swap_setup fail, then scylla_setup will exit.

**Comment by roydahan** [comment]
> > I would say even to check how much free disk space is available and if there is not enough free space, to warn the user and give the option to exit the setup and extend the disk space.
> 
> Currently if the assigned directory doesn't have enough space, the dd cmd will fail, and scylla_swap_setup fail, then scylla_setup will exit.

Which is bad.
It's something we could foresee and prevent the user failure.

**Comment by amoskong** [comment]
> > > I would say even to check how much free disk space is available and if there is not enough free space, to warn the user and give the option to exit the setup and extend the disk space.
> > 
> > 
> > Currently if the assigned directory doesn't have enough space, the dd cmd will fail, and scylla_swap_setup fail, then scylla_setup will exit.
> 
> Which is bad.
> It's something we could foresee and prevent the user failure.

Agree with your point.
