### ISSUE TITLE
Unit test scylla-gdb.py

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6952]
`scylla-gdb.py` tends to break from time to time due to various changes.
Could be in the toolchain, gdb itself, or in scylla, like the breakage recently fixed by @xemul after changing to row cache to use B+ tree.

Therefore we need a unit test that could be automated, e.g. in our Jenkins next promotion job.
For example, attach scylla-gdb.py to a running scylla process, after applying some minimal load on it, and run some test scripts that will exercise the core functionality and validate the results.

**Comment by bhalevy** [comment]
@espindola this is in the area of #6365 and #4186 so you can do it would be good to work on them together.

**Comment by denesb** [comment]
We can verify that each command can be executed without errors, which should already be good enough to ensure there are no glaring regressions.

**Comment by bhalevy** [comment]
@denesb transferring ownership of this issue to you...

**Comment by bhalevy** [comment]
We can close this issue with https://github.com/scylladb/scylla/pull/8618
Any further fixes / improvement can be tracked in new GH issues.
