### ISSUE TITLE
Commitlog replay segfaults when mutations use old schema and memtable space is full

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#6953]
Introduced in 79935df959a7066ab1a61c1c4b350391a23cc2b5

Scylla version (or git commit hash): 3.2+

The mutation object may be freed prematurely during commitlog replay in the schema upgrading path. We will hit the problem if the memtable is full and apply_in_memory() needs to defer.

This will typically manifest as a segfault.

**Comment by avikivity** [comment]
Backported to 4.0, 4.1, 4.2.
