### ISSUE TITLE
Scylla 4.0.5 Server not booting up

### ISSUE THREAD

**Issue by bishnuagrawal-zeotap** [scylladb/scylla#6956]
*Installation details*
Scylla version (or git commit hash): 4.0.5-0.20200728.466cfb0ca66
Cluster size: 3 nodes, n2-highmem-16
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu
Kernel: 4.15.0-1029-gcp #31-Ubuntu

Hello Team,

We are running JanusGraph with Scylla as a storage engine. It's a 3 node Scylla cluster that hosts 2 keyspaces (idgraph1, tapadgraph). We are trying upgrading Scylla to 4.0.5 from 3.1 version by restoring backup dump from the old cluster. The cluster starts normally for tapadgraph but fails for idgraph1. **_(We followed the same approach to upgrade Scylla (to 4.0.3-0.20200621.1fcf38abd9b) for a different cluster and it worked fine)_**

**idgraph1 schema:** - Get generated by JanusGraph automatically, no control to the user

```

`CREATE KEYSPACE idgraph1 WITH replication = {'class': 'SimpleStrategy', 'replication_factor': '1'}  AND durable_writes = true;

CREATE TABLE idgraph1.edgestore_lock_ (
    key blob,
    column1 blob,
    value blob,
    PRIMARY KEY (key, column1)
) WITH CLUSTERING ORDER BY (column1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'LeveledCompactionStrategy'}
    AND compression = {'chunk_length_kb': '64', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE idgraph1.txlog (
    key blob,
    column1 blob,
    value blob,
    PRIMARY KEY (key, column1)
) WITH CLUSTERING ORDER BY (column1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'LeveledCompactionStrategy'}
    AND compression = {'chunk_length_kb': '64', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE idgraph1.edgestore (
    key blob,
    column1 blob,
    value blob,
    PRIMARY KEY (key, column1)
) WITH CLUSTERING ORDER BY (column1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'LeveledCompactionStrategy'}
    AND compression = {'chunk_length_kb': '64', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE idgraph1.graphindex_lock_ (
    key blob,
    column1 blob,
    value blob,
    PRIMARY KEY (key, column1)
) WITH CLUSTERING ORDER BY (column1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'LeveledCompactionStrategy'}
    AND compression = {'chunk_length_kb': '64', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE idgraph1.systemlog (
    key blob,
    column1 blob,
    value blob,
    PRIMARY KEY (key, column1)
) WITH CLUSTERING ORDER BY (column1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'LeveledCompactionStrategy'}
    AND compression = {'chunk_length_kb': '64', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE idgraph1.system_properties_lock_ (
    key blob,
    column1 blob,
    value blob,
    PRIMARY KEY (key, column1)
) WITH CLUSTERING ORDER BY (column1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'LeveledCompactionStrategy'}
    AND compression = {'chunk_length_kb': '64', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE idgraph1.janusgraph_ids (
    key blob,
    column1 blob,
    value blob,
    PRIMARY KEY (key, column1)
) WITH CLUSTERING ORDER BY (column1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'LeveledCompactionStrategy'}
    AND compression = {'chunk_length_kb': '64', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE idgraph1.graphindex (
    key blob,
    column1 blob,
    value blob,
    PRIMARY KEY (key, column1)
) WITH CLUSTERING ORDER BY (column1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'LeveledCompactionStrategy'}
    AND compression = {'chunk_length_kb': '64', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

CREATE TABLE idgraph1.system_properties (
    key blob,
    column1 blob,
    value blob,
    PRIMARY KEY (key, column1)
) WITH CLUSTERING ORDER BY (column1 ASC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'LeveledCompactionStrategy'}
    AND compression = {'chunk_length_kb': '64', 'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';`

```
- The schema is same for other keyspace (tapadgraph)

- **Jornalctl Logs:**

```
_/scylla/data/system_schema/types-5a8b1ca866023f77a0459273d308917a/mc-760-big-Data.db:level=0, /var/lib/scylla/data/system_schema/types-5a8b1ca866023f77a0459273d308917a/mc-792-big-Data.db:level=0, /var/lib/scylla/data/system_schema/types-5a8b1ca866023f77a0459273d308917a/mc-88-big-Data.db:level=0, /var/lib/scylla/data/system_schema/types-5a8b1ca866023f77a0459273d308917a/mc-728-big-Data.db:level=0, ]
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 scylla[11954]: scylla: sstables/sstables.cc:3294: sstables::delete_atomically(std::vector<seastar::lw_shared_ptr<sstables::sstable> >)::<lambda()>: Assertion `sstdir == sst->get_dir()' failed.
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 audit[11954]: ANOM_ABEND auid=4294967295 uid=112 gid=116 ses=4294967295 pid=11954 comm="reactor-13" exe="/opt/scylladb/libexec/scylla" sig=6 res=1
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 scylla[11954]: Aborting on shard 13.
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 scylla[11954]: Backtrace:
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 scylla[11954]:   0x0000000002ee3512
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 scylla[11954]:   0x0000000002e88e4b
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 scylla[11954]:   0x0000000002e89145
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 scylla[11954]:   0x0000000002e891e0
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 scylla[11954]:   0x00007fe821653b1f
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 scylla[11954]:   /opt/scylladb/libreloc/libc.so.6+0x000000000003c624
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 scylla[11954]:   /opt/scylladb/libreloc/libc.so.6+0x00000000000258d8
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 scylla[11954]:   /opt/scylladb/libreloc/libc.so.6+0x00000000000257a8
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 scylla[11954]:   /opt/scylladb/libreloc/libc.so.6+0x0000000000034a65
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 scylla[11954]:   0x00000000011a17eb
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 scylla[11954]:   0x00000000011a3b96
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 scylla[11954]:   0x0000000003145f6c
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 systemd[1]: Started Process Core Dump (PID 12123/UID 0).
-- Subject: Unit systemd-coredump@54-12123-0.service has finished start-up
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit systemd-coredump@54-12123-0.service has finished starting up.
--
-- The start-up result is RESULT.
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@54-12123-0 comm="systemd" exe="/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 systemd[12124]: systemd-coredump@54-12123-0.service: Failed to set up special execution directory in /var/lib: Not a directory
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 systemd[12124]: systemd-coredump@54-12123-0.service: Failed at step STATE_DIRECTORY spawning /lib/systemd/systemd-coredump: Not a directory
-- Subject: Process /lib/systemd/systemd-coredump could not be executed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The process /lib/systemd/systemd-coredump could not be executed and failed.
--
-- The error number returned by this process is 20.
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-coredump@54-12123-0 comm="systemd" exe="/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 systemd[1]: scylla-server.service: Main process exited, code=killed, status=6/ABRT
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 systemd[1]: scylla-server.service: Failed with result 'signal'.
Jul 30 16:32:10 scylla-zeograph2-prod-eu-1 systemd[1]: Failed to start Scylla Server.
-- Subject: Unit scylla-server.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support_

```
**Only potential error log I could find is:**

```
sstables::delete_atomically(std::vector<seastar::lw_shared_ptr<sstables::sstable> >)::<lambda()>: Assertion `sstdir == sst->get_dir()' failed.
```

Let me know if I could help with entire log dump to make debugging easy. I could not find core dump logs.

**Update 5th August:**

Let me update what position we are in and little more details about the issue.

- Our servers go into error state because of disk issue (some disk segment gets corrupt, it's a GCP issue & nothing to do with Scylla)
- To get the server back we use the backup and restoration processes which usually take 3-4 hrs for recovery.
- This time it failed while recovering for multiple Scylla versions (3.1.3, 4.0.5) and error logs were the same for all ( give a day time, I can get all logs and we can connect for a detailed analysis) 
- Scylla acts as a storage engine for our JanusGraph server and all tables are created/managed by JG.
- **_Post recovery we deleted **system_properties_lock_** table and it worked fine_** (We may not be correct in terms of logic behind deleting the lock table but yes any support from the team would be really helpful and learning for us)
- We definitely are moving to RF of 3 (at least) to not be in the situation in the future.

**Comment by slivne** [comment]
@bishnuagrawal-zeotap 

from which 3.1.X exactly are you upgrading

Can you please provide the coredump according to https://docs.scylladb.com/troubleshooting/report_scylla_problem/

Please note your keyspace has replication_factor: 1 - you need to make sure to retain to token ownership or else you will "loose" data.

**Comment by avikivity** [comment]
@bishnuagrawal-zeotap can you upload the core file? It will make it much easier to diagnose.

**Comment by raphaelsc** [comment]
I came across a similar issue when reviewing the first off-strategy changes and I found a bug which potentially explain this issue. 

Then I came up with the "sstables: Make SSTable directory consistent", but I later realized it broke the unit tests and I found no time to work on v2, and forgot about it.

The description of the patch describes this bug:
```
SSTable created with a canonical path will return a different
directory string than a SSTable created with a non-canonical
path. That could lead to a failure in delete_atomically()
which asserts that all SSTables being deleted together belong
exactly to the same directory.

We could make SSTable store a fs::path() but that requires lots
of changes throughout our code base which currently requires
a string. By the time being, let's canonicalize its directory.

Found this problem while reviewing off-strategy work which
creates unshared SSTables with a canonical path, when it's
compacted with other SSTables, delete_atomically() triggers
an assert failure.
```

**Comment by raphaelsc** [comment]
@bishnuagrawal-zeotap please upload the full logs as I'd like to make sure your problem will be really fixed with a patch of mine.

**Comment by raphaelsc** [comment]
The patch is ready, but I need the logs to just be 100% certain. @bishnuagrawal-zeotap please upload the logs when you have time.

**Comment by bishnuagrawal-zeotap** [comment]
> @bishnuagrawal-zeotap
> 
> from which 3.1.X exactly are you upgrading
> 
> Can you please provide the coredump according to https://docs.scylladb.com/troubleshooting/report_scylla_problem/
> 
> Please note your keyspace has replication_factor: 1 - you need to make sure to retain to token ownership or else you will "loose" data.

**Comment by bishnuagrawal-zeotap** [comment]
> The patch is ready, but I need the logs to just be 100% certain. @bishnuagrawal-zeotap please upload the logs when you have time.

Hey @raphaelsc ,

- Thanks for finding out the possible bugs and spending time-solving this. I added a few more details of the issue in the description. I would be happy to test the new release with your patch fix.

- I need a day time to get you complete logs & other possible details for your analysis (Apologies for the delay)

**Comment by bishnuagrawal-zeotap** [comment]
**Scylla-server logs:** 
[server.log](https://github.com/scylladb/scylla/files/5033664/server.log)

- I couldn't get core-dump from **/var/lib/scylla/coredump** directory
- We have kept server intact post-recovery

 Let me know if I can help more for analysis

**Comment by raphaelsc** [comment]
By looking at logs, I figured out that Scylla loaded table idgraph1.system_properties_lock from two different directories:
`	Dirs: {'/var/lib/scylla/data/idgraph1/system_properties_lock_-2fe61d40d7af11ea8c5a000000000005', '/var/lib/scylla/data/idgraph1/system_properties-33310280d7af11ea8c5a000000000005'}`

The first dir belongs to mc SSTables, whereas the second belong to ka SSTables, which uses a different naming scheme for the table dir.

The same table being spread across different dirs probably happened when migrating from 3.x version.

Look at this:
```
Found different dir in compaction input:
	Dirs: {'/var/lib/scylla/data/idgraph1/system_properties_lock_-2fe61d40d7af11ea8c5a000000000005', '/var/lib/scylla/data/idgraph1/system_properties-33310280d7af11ea8c5a000000000005'}
		File: /var/lib/scylla/data/idgraph1/system_properties_lock_-2fe61d40d7af11ea8c5a000000000005/la-1662-big-Data.db
		File: /var/lib/scylla/data/idgraph1/system_properties_lock_-2fe61d40d7af11ea8c5a000000000005/la-1678-big-Data.db
		File: /var/lib/scylla/data/idgraph1/system_properties_lock_-2fe61d40d7af11ea8c5a000000000005/la-1646-big-Data.db
		File: /var/lib/scylla/data/idgraph1/system_properties-33310280d7af11ea8c5a000000000005/idgraph1-system_properties_lock_-ka-1070-Data.db
		File: /var/lib/scylla/data/idgraph1/system_properties_lock_-2fe61d40d7af11ea8c5a000000000005/la-1630-big-Data.db
		File: /var/lib/scylla/data/idgraph1/system_properties-33310280d7af11ea8c5a000000000005/idgraph1-system_properties_lock_-ka-1054-Data.db
```

As Scylla is perfectly capable of supporting this, I think the problem lies in the check that see if all compaction input belongs to the same table by only looking at directory, but given that mc/la and ka dirs may differ, we should actually reuse the function that extracts ks and cf from the path for all versions, and compare the pair ks and cf instead.

**Comment by bishnuagrawal-zeotap** [comment]
Hey @raphaelsc,

Thanks for prompt reply.

- Is Compaction run with multiple tables as input possible? Like compacting **system_properties_lock** table with **system_properties** table, logically seems wrong(correct if wrong) ?
- Can a table have two different SSTable types, like ka & mc?

- Considering compaction runs where input is from multiple directories, is it a bug which we are running with or some data issue?

**Comment by raphaelsc** [comment]
> Hey @raphaelsc,
> 
> Thanks for prompt reply.
> 
> * Is Compaction run with multiple tables as input possible? Like compacting **system_properties_lock** table with **system_properties** table, logically seems wrong(correct if wrong) ?

Hmm, those are two different tables, indeed. 

What I think is happening here is that a SSTable from **system_properties_lock** was incorrectly placed at **system_properties** dir, but Scylla was still able to place that SSTable at the correct table. However, Scylla should not even be allowed to boot if that happened. I need to think more about think.

> * Can a table have two different SSTable types, like ka & mc?

Yes, they can coexist as long as the SSTables are from the same table.

> * Considering compaction runs where input is from multiple directories, is it a bug which we are running with or some data issue?

It was detected that compaction was called with SSTables from two different directories.

**Comment by slivne** [comment]
@bishnuagrawal-zeotap anyway to prove Raphael's theory that sstables from one table where placed incorrectly in another tables directory ?
- Did you restore files at some point ?
- Is the a "clean" scylla cluster you started from scratch and wrote CQL - or a "migrated" cluster from cassandra ?

**Comment by bishnuagrawal-zeotap** [comment]
@slivne -
1. I rechecked if we misplaced files in the wrong directory ...but this was not the case
2. We restored the Scylla backup of our old cluster - We use GCP and intermittently we get disk corruption issue, to handle this we have backup and recovery pipeline. 

We deleted the content of _system_properties_lock_ table (since it's a lock/meta table) and Scylla started.

**Comment by slivne** [comment]
@bishnuagrawal-zeotap - ok - please note we are aware of disk corruption issues in gcp with some kernels

zen.ly are using us on GCP and have reported this  https://www.slideshare.net/ScyllaDB/zenly-shares-best-practices-for-running-scylladb-on-gcp

Slide #9 (https://www.slideshare.net/ScyllaDB/zenly-shares-best-practices-for-running-scylladb-on-gcp#9)

(its a gcp kernel bug - not a scylla bug :) ).


with regards to your issue - if you can provide us a reproducer we will try it locally

**Comment by slivne** [comment]
@bishnuagrawal-zeotap closing this issue - if you have any updates please post and we can reopen
