### ISSUE TITLE
Compaction efficiency can be improved by not trimming compaction jobs

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#6957]
Issue opened for possibly backporting the patch 
https://github.com/scylladb/scylla/commit/99b75d1f6378cccf03d43f687863d64fbc0c97f9 that significantly increases the overall compaction efficiency by simply killing the procedure that trimmed compaction jobs. The patch doesn't add any code, so backporting it given the benefits it provides is worth the effort.

Quoting the patch:
```
"This procedure consists of trimming SSTables off a compaction job until its weight[1]
is smaller than one already taken by a running compaction. Min threshold is respected
though, we only trim a job while its size is > min threshold.

[1]: this value is a logarithimic function of the total size of the SSTables in a
given job, and it's used to control the compaction parallelism.

It's intended to improve the compaction efficiency by allowing more jobs to run in
parallel, but it turns out that this can have an opposite effect because the write
amplification can be significantly increased.

Take STCS for example, the more similar-sized SSTables you compact together, the
higher the compaction efficiency will be. With the trimming procedure, we're aiming
at running smaller jobs, thinking that running more parallel compactions will provide
us with better performance, but that's not true. Most of the efficiency comes from
making informed decisions when selecting candidates for compaction.

Similarly, this will also hurt TWCS, which does STCS in current window, and a sort
of major compaction when the current window closes. If the TWCS jobs are trimmed,
we'll likely need another compaction to get to the desired state, recompacting
the same data again."

```

**Comment by raphaelsc** [comment]
Closed by https://github.com/scylladb/scylla/commit/99b75d1f6378cccf03d43f687863d64fbc0c97f9

**Comment by avikivity** [comment]
Not backporting since this isn't a regression or a major bug, just a good performance improvement.

**Comment by raphaelsc** [comment]
> Not backporting since this isn't a regression or a major bug, just a good performance improvement.

@avikivity don't you think it's worth backporting this nice perf improvement to 4.2? well, this change only removes code, and i couldn't see any regression coming out of it, but to be 100% sure, we could let it cook for a few days until 4.2 release.

**Comment by avikivity** [comment]
If we backport indiscriminately 4.2 will never be released. It can wait for 4.3.
