### ISSUE TITLE
cql_query_test fails intermittently with fatal error: in "test_cache_bypass": critical check without_cache == 0 has failed [4 != 0]

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6983]
Seen in a couple recent next promotion runs in debug mode:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2344/artifact/testlog/debug/cql_query_test.4.log
scylla version 1adcd7aca784b13008d1fcabe601116ea7aff334

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2345/artifact/testlog/debug/cql_query_test.4.log
https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2345/artifact/testlog/debug/cql_query_test.6.log
scylla version b5f3aef900ce8f3c61e4e23027fc9442ea8c4930

```
bhalevy@lt tmp$ grep 'fatal' cql_query_test*.log 
cql_query_test-2344.4.log:test/boost/cql_query_test.cc(3504): fatal error: in "test_cache_bypass": critical check without_cache == 0 has failed [4 != 0]
cql_query_test-2345.4.log:test/boost/cql_query_test.cc(3504): fatal error: in "test_cache_bypass": critical check without_cache == 0 has failed [4 != 0]
cql_query_test-2345.6.log:test/boost/cql_query_test.cc(3504): fatal error: in "test_cache_bypass": critical check without_cache == 0 has failed [4 != 0]
```

**Comment by bhalevy** [comment]
@xemul since you're the last one to touch the row cache, please investigate :)

Cc @tgrabiec please also have a look and see if you have some insights from the available test logs.

**Comment by avikivity** [comment]
We're familiar with the problem, some background query touched the cache and its statistics.

**Comment by avikivity** [comment]
We might run the query 10 times and check that the stat change is >= smp::count * 10 with the cache, and <= 2*smp::count without it (tolerating two unrelated scans).

**Comment by slivne** [comment]
We have metrics today to distinguish system vs user queries - we should
check if there was a system generated query and if so try again.

**Comment by bhalevy** [comment]
Duplicate of #6773
