### ISSUE TITLE
snapshot may try to link same sstable from different shards concurrently

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#6984]
Seen while working on https://github.com/scylladb/scylla/issues/5714.
And actually there's even a comment in the already warning about this, added in 9083a0e5a7bc15528e483e32e984897dd0357381:
https://github.com/scylladb/scylla/blob/257c17a87aade379acbc8d0924b2718edb8c93de/table.cc#L1486-L1487

We need only one of the shards owning each ssatble to call create_links.
This will allow us to simplify it and only handle crash/replay scenarios rather than rename/link/remove races.

**Comment by bhalevy** [comment]
Fixed by 122136c6177255cfe8fe344f66fbb07d4755d025

**Comment by avikivity** [comment]
Why backport? It's not a real problem in practice, is it?

**Comment by bhalevy** [comment]
> Why backport? It's not a real problem in practice, is it?

You're right, the existing code ignores errors resulting from the concurrent links.
