### ISSUE TITLE
scylla_setup tool error on AWS instance:  c5n doesn't support enhanced networking! 

### ISSUE THREAD

**Issue by cogitaria-admin** [scylladb/scylla#6991]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.1
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.6

UPDATE:  scylla_setup tool succeeds using AWS instances of type **i3en** and since that is the recommended instance type (storage optimized) perhaps the message about **c5n** instances is not relevant: users should be choosing the i3 types. 

The scylla_setup tool is incorrectly claiming AWS c5n instance type doesn't support enhanced networking. 

The **ethtool** claims the ENA driver is being used:

> ethtool -i ens5
driver: ena
version: 2.0.3K
firmware-version:
expansion-rom-version:
bus-info: 0000:00:05.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
`

The **modinfo** command says that ENA is enabled.  The c5n instance type definitely supports ENA.  

`
> modinfo ena
filename:       /lib/modules/3.10.0-1127.18.2.el7.x86_64/kernel/drivers/net/ethernet/amazon/ena/ena.ko.xz
version:        2.0.3K
license:        GPL
description:    Elastic Network Adapter (ENA)
author:         Amazon.com, Inc. or its affiliates
retpoline:      Y
rhelversion:    7.8
...
`

**Comment by avikivity** [comment]
Backported to 4.0, 4.1, 4.2.
