### ISSUE TITLE
CQL unecrypted native transport is enabled unconditionally

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#6997]
@gnumoreno writes:

```
We enabled ssl and are using native_transport_port_ssl: 9142
Commenting out native_transport_port: 9042 does not disable 9042. Is there a way to disable it?
```

As it turns out, we enable the unencrypted native transport unconditionally in `controller::do_start_server()`. This makes it impossible to configure Scylla to only accept encrypted native transport.

**Comment by haaawk** [comment]
I think it is possible to do that already. You just need to set both native_transport_port_ssl and native_transport_port to the same port and then that port will be using encryption and there won't be any port that is unencrypted.
