### ISSUE TITLE
InvalidBlockDeviceMapping: Volume of size 15GB is smaller than  snapshot <SNAP_NAME> (expect size >= 30GB)

### ISSUE THREAD

**Issue by nizarh11** [scylladb/scylla#6999]
*Installation details*
Scylla version (or git commit hash): master:latest
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI):ami-0b3b647af24631ea3

I am getting the following exception on set-up:

```
botocore.exceptions.ClientError: An error occurred (InvalidBlockDeviceMapping) when calling the RunInstances operation: Volume of size 15GB is smaller than  snapshot 'snap-09e0f802c68b958b7', expect size >= 30GB

```
Jenkins Job:

https://jenkins.scylladb.com/view/master/job/scylla-master/view/master-test/job/longevity/job/longevity-200gb-48h/59/

Logs:

New directory created: /home/nizarh/sct-results/20200809-091441-925805-investigate-show-logs
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id 8077a4f3-996b-4267-9298-aa840034824f                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20200809_074639 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/8077a4f3-996b-4267-9298-aa840034824f/20200809_074639/sct-runner-8077a4f3.zip |

**Comment by roydahan** [comment]
Issue moved to [scylladb/scylla-cluster-tests #2484](https://github.com/scylladb/scylla-cluster-tests/issues/2484) via [**ZenHub**](https://www.zenhub.com/)
