### ISSUE TITLE
scylla-gdb does not install on centos 7

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#7012]
$ cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)

$ cat /etc/yum.repos.d/scylla.repo
```
[scylla-4.2]
name=Scylla for Centos - $basearch
baseurl=http://downloads.scylladb.com/downloads/scylla/rpm/centos/scylladb-4.2/$basearch/
enabled=1
gpgcheck=0

[scylla-generic-4.2]
name=Scylla for centos
baseurl=http://downloads.scylladb.com/downloads/scylla/rpm/centos/scylladb-4.2/noarch/
enabled=1
gpgcheck=0


[scylladb-scylla-3rdparty]
name=Copr repo for scylla-3rdparty owned by scylladb
baseurl=https://copr-be.cloud.fedoraproject.org/results/scylladb/scylla-3rdparty/epel-7-$basearch/
type=rpm-md
skip_if_unavailable=True
gpgcheck=1
gpgkey=https://copr-be.cloud.fedoraproject.org/results/scylladb/scylla-3rdparty/pubkey.gpg
repo_gpgcheck=0
enabled=1
enabled_metadata=1
```

$ sudo yum install scylla-gdb.x86_64
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: d36uatko69830t.cloudfront.net
 * elrepo: www.jules.fm
 * extras: d36uatko69830t.cloudfront.net
 * updates: d36uatko69830t.cloudfront.net
Resolving Dependencies
--> Running transaction check
---> Package scylla-gdb.x86_64 0:7.10.1-30.el7.centos will be installed
--> Processing Dependency: scylla-env for package: scylla-gdb-7.10.1-30.el7.centos.x86_64
--> Processing Dependency: libpython3.4m.so.1.0()(64bit) for package: scylla-gdb-7.10.1-30.el7.centos.x86_64
--> Running transaction check
---> Package scylla-env.noarch 0:1.1-1.el7 will be installed
---> Package scylla-gdb.x86_64 0:7.10.1-30.el7.centos will be installed
--> Processing Dependency: libpython3.4m.so.1.0()(64bit) for package: scylla-gdb-7.10.1-30.el7.centos.x86_64
--> Finished Dependency Resolution
Error: Package: scylla-gdb-7.10.1-30.el7.centos.x86_64 (scylladb-scylla-3rdparty)
           Requires: libpython3.4m.so.1.0()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by slivne** [comment]
Do we still need scylla-gdb - I thought its not needed once we moved to relocatable-packages and toolchain.

**Comment by avikivity** [comment]
We don't need it. A modern gdb can be installed using these commands:

```console
yum -y install centos-release-scl-rh
yum -y install devtoolset-9-gdb
```
