### ISSUE TITLE
scylla rpm should install scylla-gdb.py dependences

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#7014]
$ rpm -qa|grep scylla
scylla-conf-4.2.rc2-0.20200809.0ce379918.x86_64
scylla-tools-4.2.rc2-20200809.712738dfda.noarch
scylla-debuginfo-4.2.rc2-0.20200809.0ce379918.x86_64
scylla-server-4.2.rc2-0.20200809.0ce379918.x86_64
scylla-tools-core-4.2.rc2-20200809.712738dfda.noarch
scylla-machine-image-4.2.rc2-20200810.86ed907cf5.noarch
scylla-python3-3.8.5-0.20200809.0ce379918.x86_64
scylla-kernel-conf-4.2.rc2-0.20200809.0ce379918.x86_64
scylla-4.2.rc2-0.20200809.0ce379918.x86_64
scylla-manager-agent-2.1.1-0.20200707.ca863845.x86_64
scylla-jmx-4.2.rc2-20200809.01614ce.noarch

$ gdb 
gdb ) source /opt/scylladb/scripts/scylla-gdb.py

File "/opt/scylladb/scripts/scylla-gdb.py", line 18, in <module>
    import html
ImportError: No module named html

**Comment by avikivity** [comment]
Why should scylla install gdb? Most users aren't interested in debugging scylla.

**Comment by denesb** [comment]
This is a ptyhon3 vs. python2 thing, `html` comes from the python standard library.

**Comment by denesb** [comment]
Fix on the list: [PATCH v1] scylla-gdb.py: restore python2 compatibility

**Comment by asias** [comment]
> Why should scylla install gdb? Most users aren't interested in debugging scylla.

Not gdb. I mean installing what scylla-gdb.py depends on.

**Comment by avikivity** [comment]
Right, I misread. 

What does it depend on?

**Comment by denesb** [comment]
Nothing besides the standard python library. Python is complaining about the `html` library because this was added in python3, while the system where @asias tried to use the script has python2.

**Comment by avikivity** [comment]
So nothing needs to be done?

**Comment by denesb** [comment]
The patch above fixes the issue (gets rid of the problematic `html` import).

**Comment by avikivity** [comment]
Ah, and the patch references the issue too.

**Comment by denesb** [comment]
The patch was merged as b11d181413, we can close this.
