### ISSUE TITLE
gdb scylla databases gives the same address for different shards

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#7016]
scylla-server-4.2.rc2-0.20200809.0ce379918.x86_64

(gdb) scylla databases;
    0 (database*)0x60d009436010
    1 (database*)0x601009436010
    2 (database*)0x602009436010
    3 (database*)0x603009436010
    4 (database*)0x604009436010
    5 (database*)0x605009436010
    6 (database*)0x606009436010
    7 (database*)0x607009436010
    8 (database*)0x608009436010
    9 (database*)0x609009436010
   10 (database*)0x60a009436010
   11 (database*)0x60b009436010
   12 (database*)0x60c009436010
   13 (database*)0x60d009436010

Shard 0 and 13 have the same address 0x60d009436010.

**Comment by denesb** [comment]
This is because:
```
   2 def find_db(shard=None):                                                                                                                                                                                                                                 
   1     if not shard:                                                                                                                                                                                                                                        
601          shard = current_shard()                                                                                                                                                                                                                          
   1     return gdb.parse_and_eval('::debug::db')['_instances']['_M_impl']['_M_start'][shard]['service']['_p']
```
`not shard` will evaluate to `True` for `shard=0`, so if this is invoked from any shard besides `0`, the database instance for shard 0 will be replaced with that of the current shard.
