### ISSUE TITLE
Unified tarball is not compressed

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#7039]
As pointed out by @hagitsegev, the unified tarball is larger than the sum of the individual tarballs. As it turns out, it's not compressed:

```
$ file ./build/release/scylla-unified-package.tar.gz
./build/release/scylla-unified-package.tar.gz: POSIX tar archive (GNU)
```

In comparison:

```
$ file ./build/dev/scylla-package.tar.gz
./build/dev/scylla-package.tar.gz: gzip compressed data, last modified: Thu Aug 13 11:22:39 2020, from Unix, original size modulo 2^32 130795520
```

**Comment by penberg** [comment]
I have sent a patch ("[PATCH scylla] build_unified.sh: Compress generated tarball") to fix this on the mailing list.

**Comment by avikivity** [comment]
New feature, no need to backport.
