### ISSUE TITLE
abstract_replication_strategy::do_get_ranges is passed a reference to token_metadata that may be invalidated if it yields

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7044]
Change 94995acedb42fc7d15c5e65fcd5def9dcfca1984 added yielding to `abstract_replication_strategy::do_get_ranges`.
However, there is nothing to prevent `token_metadata`, and in particular its `_sorted_tokens` to change while iterating over them in `do_get_ranges` if the latter yields.

`token_metadata_impl::update_normal_tokens` may overwrite `_sorted_tokens`, freeing the previous vector `do_get_ranges` is traversing, and then `calculate_natural_endpoints(tok, tm)` seems also susceptible, (e.g. `simple_strategy::calculate_natural_endpoints`) when calling `tm.ring_range(t)` where `t` is a token from the overwritten sorted tokens.

**Comment by bhalevy** [comment]
The call from `compaction_manager::perform_cleanup` that was added in 07e253542d6b2611ee4b1c8df2653b0af4ef085a is problematic since it walks over the keyspace replication strategy's `token_metadata`.

The call from do_rebuild_replace_with_repair that was added in e3c2d08f4f9 is ok since it uses a local token_metadata parameter.

**Comment by bhalevy** [comment]
Currently this is confined to master so not backport needed.

**Comment by avikivity** [comment]
Please consider people who write release notes when authoring issues. How is someone to make sense of it?

The issue should describe the problem (what's wrong now), not the fix (what it should be doing).
