### ISSUE TITLE
Commit log unhandled write errors

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#705]
When testing scylla with CharibeFS while injecting random errno with probability 1% I got.

ERROR [shard 7] commitlog - Failed to persist commits to disk for CommitLog-1-126100789584856783.log: std::system_error (error system:54, Exchange full)
WARNING: exceptional future ignored of type 'std::system_error': Error system:54 (Exchange full)
ERROR [shard 5] commitlog - Failed to persist commits to disk for CommitLog-1-90071992565892815.log: std::system_error (error system:7, Argument list too long)
WARNING: exceptional future ignored of type 'std::system_error': Error system:7 (Argument list too long)
ERROR [shard 6] commitlog - Failed to persist commits to disk for CommitLog-1-108086391075374799.log: std::system_error (error system:23, Too many open files in system)
WARNING: exceptional future ignored of type 'std::system_error': Error system:23 (Too many open files in system)
ERROR [shard 5] commitlog - Failed to persist commits to disk for CommitLog-1-90071992565892816.log: std::system_error (error system:8, Exec format error)
WARNING: exceptional future ignored of type 'std::system_error': Error system:8 (Exec format error)
ERROR [shard 1] commitlog - Failed to persist commits to disk for CommitLog-1-18014398527964880.log: std::system_error (error system:30, Read-only file system)
WARNING: exceptional future ignored of type 'std::system_error': Error system:30 (Read-only file system)

How do we decide to handle these unhandled write errors ?

**Comment by elcallio** [comment]
Origin has failure policies for commit log, Basically, just report, fail request or stop process. We should at the very least add similar. 
There is some issues with trying to handle the above gracefully, since we could end up trying to write a file section until the end of time. Usually, if a write fails, re-trying will fail to. Otoh, it is not 100% fatal for the node, it just means that the eventual consistency just became more eventual. 
SStable write failure is worse. In a sense.

**Comment by slivne** [comment]
I suggest that we stick with a single option and not code mutiple options in this case - till we see it is really needed

Cassandra has

commit_failure_policy 
    (Default: stop) Policy for commit disk failures:

        die

        Shut down gossip and Thrift and kill the JVM, so the node can be replaced.
        stop

        Shut down gossip and Thrift, leaving the node effectively dead, but can be inspected using JMX.
        stop_commit

        Shut down the commit log, letting writes collect but continuing to service reads (as in pre-2.0.5 Cassandra).
        ignore

        Ignore fatal errors and let the batches fail.

disk_failure_policy 
    (Default: stop) Sets how Cassandra responds to disk failure. Recommend settings are stop or best_effort.

        die

        Shut down gossip and Thrift and kill the JVM for any file system errors or single SSTable errors, so the node can be replaced.
        stop_paranoid

        Shut down gossip and Thrift even for single SSTable errors.
        stop

        Shut down gossip and Thrift, leaving the node effectively dead, but available for inspection using JMX.
        best_effort

        Stop using the failed disk and respond to requests based on the remaining available SSTables. This means you will see obsolete data at consistency level of ONE.
        ignore

        Ignores fatal errors and lets the requests fail; all file system errors are logged but otherwise ignored. Cassandra acts as in versions prior to 1.2.


Incontract to what I wrote to use a single setting and support only that we have some settings from users that have set this different from the default:

disk_failure_policy: stop_paranoid
commit_failure_policy: die

@tzach whats your input - in any case I suggest we do not support multiple methods for GA

**Comment by tzach** [comment]
A good policy will be to exit on both errors, disk_failure_policy and commit_failure_policy.
We can add more policies if and when we need it.

**Comment by benoit-canet** [comment]
Closed by:
1fb9a48ac5fe332a948bd006d9c64aa11916a77a
3b1d3d977d50204400fc6277390a1740e22d34ce

Tested a day of two with CharybdeFS. I am pretty confident it's ok.
