### ISSUE TITLE
Issue generating sharding metadata during repair

### ISSUE THREAD

**Issue by Snipa22** [scylladb/scylla#7056]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.1.3
Cluster size: 5 Servers
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): AWS Cloud instance, i3.Metal
Disks: NVME 8x 1.9Tb, Raid 0,

Thus far, I've rebuilt the node twice from blank in order to attempt to get it to repair properly after, including with a decommission and re-add, as well as with an in-place rebuild by blanking it's data folders and having it re-add itself in under the same IP, but I continue to get the same error whenever a repair is run across it.  This occurs with both a local nodetool repair as well as with a sctool repair from our cluster management node.

The node does not show unusually high CPU or disk usage during these times, nor does it appear to have any issues accessing this data normally, nor does this seem to interfere with the normal usage of this table at any time.

Attached are the logs grepped out of the system in regards to this specific issue
```
Aug 16 10:04:34 us-west-production-scylla-10 scylla[312063]:  [shard 48] repair - repair_writer: keyspace=hashtags, table=user_tag_usage_raw, wait_for_writer_done failed: std::runtime_error (Failed to generate sharding metadata for /data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-275638-big-Data.db)
Aug 16 10:04:49 us-west-production-scylla-10 scylla[312063]:  [shard 0] repair - repair id 1040 failed: std::runtime_error ({shard 48: std::runtime_error (Failed to generate sharding metadata for /data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-275638-big-Data.db)})
Aug 16 10:04:49 us-west-production-scylla-10 scylla[312063]:  [shard 0] repair - repair_tracker run for repair id 1040 failed: std::runtime_error ({shard 48: std::runtime_error (Failed to generate sharding metadata for /data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-275638-big-Data.db)})
Aug 16 23:35:16 us-west-production-scylla-10 scylla[577328]:  [shard 48] repair - repair_writer: keyspace=hashtags, table=user_tag_usage_raw, multishard_writer failed: std::runtime_error (Failed to generate sharding metadata for /data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-3828-big-Data.db)
Aug 16 23:35:16 us-west-production-scylla-10 scylla[577328]:  [shard 48] repair - repair_writer: keyspace=hashtags, table=user_tag_usage_raw, wait_for_writer_done failed: std::runtime_error (Failed to generate sharding metadata for /data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-3828-big-Data.db)
Aug 16 23:35:16 us-west-production-scylla-10 scylla[577328]:  [shard 48] repair - repair id 1 on shard 48 failed: std::runtime_error (Failed to generate sharding metadata for /data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-3828-big-Data.db)
Aug 16 23:35:17 us-west-production-scylla-10 scylla[577328]:  [shard 0] repair - repair id 1 failed: std::runtime_error ({shard 48: std::runtime_error (Failed to generate sharding metadata for /data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-3828-big-Data.db)})
Aug 16 23:35:17 us-west-production-scylla-10 scylla[577328]:  [shard 0] repair - repair_tracker run for repair id 1 failed: std::runtime_error ({shard 48: std::runtime_error (Failed to generate sharding metadata for /data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-3828-big-Data.db)})
Aug 16 23:40:21 us-west-production-scylla-10 scylla[577328]:  [shard 48] repair - repair_writer: keyspace=hashtags, table=user_tag_usage_raw, multishard_writer failed: std::runtime_error (Failed to generate sharding metadata for /data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-3898-big-Data.db)
Aug 16 23:40:21 us-west-production-scylla-10 scylla[577328]:  [shard 48] repair - repair_writer: keyspace=hashtags, table=user_tag_usage_raw, wait_for_writer_done failed: std::runtime_error (Failed to generate sharding metadata for /data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-3898-big-Data.db)
Aug 16 23:40:21 us-west-production-scylla-10 scylla[577328]:  [shard 48] repair - repair id 2 on shard 48 failed: std::runtime_error (Failed to generate sharding metadata for /data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-3898-big-Data.db)
Aug 16 23:40:23 us-west-production-scylla-10 scylla[577328]:  [shard 0] repair - repair id 2 failed: std::runtime_error ({shard 48: std::runtime_error (Failed to generate sharding metadata for /data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-3898-big-Data.db)})
Aug 16 23:40:23 us-west-production-scylla-10 scylla[577328]:  [shard 0] repair - repair_tracker run for repair id 2 failed: std::runtime_error ({shard 48: std::runtime_error (Failed to generate sharding metadata for /data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-3898-big-Data.db)})
```

**Comment by avikivity** [comment]
This can happen if we somehow generated empty sstables during repair. @asias ?

**Comment by slivne** [comment]
Can you please do an ls -l on one of those sstable ids ?

Would it be possible to share one of those sstable ids (even sharing all
the components (aside of tha actual XXX.Data - will be helpfull).

**Comment by raphaelsc** [comment]
On Wed, Aug 19, 2020 at 8:33 AM Avi Kivity <notifications@github.com> wrote:

> This can happen if we somehow generated empty sstables during repair.
> @asias <https://github.com/asias> ?
>
I think this Tomek's theory may explain it:
https://github.com/scylladb/scylla-enterprise/issues/1349#issuecomment-618376735

**Comment by Snipa22** [comment]
ls -l shows that the files do not even exist.
```
root@us-west-production-scylla-10:~# ls -l /data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-3898-big-Data.d
ls: cannot access '/data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-3898-big-Data.d': No such file or directory
root@us-west-production-scylla-10:~# stat /data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-3898-big-Data.d
stat: cannot stat '/data/scyllaData/hashtags/user_tag_usage_raw-1be2c1d0dc8811eaab7700000000001b/mc-3898-big-Data.d': No such file or directory
```

I'm glad to provide any debugging information I can, though not familiar with how to pull the ID's etc/ offhand.  Glad to share as much information as I can to help make sure this gets debugged though.

I'll see about re-running a repair and getting a few more live-stats, we're currently in the middle of what appears to be a halted repair on a couple of our nodes, so I'm probally going to give them a reboot tonight to get them to clear, as they're claiming to be stopped, but the scylla-manager daemon doesn't appear to think so.

**Comment by asias** [comment]
> This can happen if we somehow generated empty sstables during repair. @asias ?

Repair is not supported to create empty sstables because the write is created lazily when  a mutation fragment is received.

**Comment by avikivity** [comment]
@denesb maybe a multishard writer did this?

**Comment by raphaelsc** [comment]
> @denesb maybe a multishard writer did this?

could potentially be a combination of multishard writer and interposer consumer

**Comment by raphaelsc** [comment]
@Snipa22 do you use TWCS?

**Comment by denesb** [comment]
We'd need a coredump to be able to tell for sure.

**Comment by raphaelsc** [comment]
looking at writer code alone, it's unlikely that this problem is about an empty sstable. somehow the data written for a particular sstable at shard S no longer belongs to shard S by the time end of stream is consumed, so that's why writer failed to generate sharding metadata. Could it happen that cluster topology changed while we were repairing data?

**Comment by asias** [comment]
> looking at writer code alone, it's unlikely that this problem is about an empty sstable. somehow the data written for a particular sstable at shard S no longer belongs to shard S by the time end of stream is consumed, so that's why writer failed to generate sharding metadata.

Do you mean when a sstable is seal (the reader attached to the sstable consume reachs eos), the all the partitions within the ssatable does not belong to the shard any more? If this is the case, should we just drop the sstable instead of abort and fail?

**Comment by avikivity** [comment]
I don't think that can happen. We don't change partition->shard mapping at runtime.

**Comment by raphaelsc** [comment]
> I don't think that can happen. We don't change partition->shard mapping at runtime.

Hmm. I claimed that the sstable is not empty because right before we generate sharding metadata, we assert the existence of first and last keys. Could this problem happen if the range spanned by the SSTable being written is no longer owned by the node by the time we try to create its sharding metadata?

**Comment by asias** [comment]
@Snipa22 FYI, we have released 4.1.6 with a few repair related fixes. I would recommend you to upgrade an retry repairing.

**Comment by slivne** [comment]
@Snipa22 can you please retest with 4.1.6 and update us - we would like to resolve this - thanks for all the help so far.

**Comment by gnumoreno** [comment]
`https://scylladb-users.slack.com/archives/C2NLNBXLN/p1601556025111600`

**Comment by slivne** [comment]
@gnumoreno I tried to use the link and couldn't find what you are referncing can you copy paste take a screenshot and paste it here ?

**Comment by gnumoreno** [comment]
![image](https://user-images.githubusercontent.com/7240118/95478684-3bd11280-0960-11eb-8d93-8d09712f786f.png)
![image](https://user-images.githubusercontent.com/7240118/95478719-4a1f2e80-0960-11eb-9936-b103a5b0ae16.png)

**Comment by slivne** [comment]
- I thought that repair is supposed to write sstables to the <table>/staging directory not the <table> directory
- After we seal the sstable we move the sstable from <table>/staging to <table>

@asias can you please clarify this - is writing to staging conditional if we have an MV/SI ?

Could it be that we have a mutation that we think we will write and thus open an sstable but at the end do not write it (example - a tombstone mutation that passes its gc_period) @denesb / @asias  ?

**Comment by slivne** [comment]
I'm attaching the log from the user that has an issue with 4.1.7
[mess.log.gz](https://github.com/scylladb/scylla/files/5349462/mess.log.gz)

**Comment by dimonomid** [comment]
I'm also having this on our 3-node cluster running Scylla 4.2.1. Wondering, how severe it is? Is it safe to just continue using it as usual and not worry about it?

**Comment by p-osipo-v** [comment]
We also having same problem on our 2-DC 10-node cluster running ScyllaDB 4.2.1.

`Dec 26 18:34:18 p1992 scylla[501753]:  [shard 0] repair - repair id 7 failed: std::runtime_error ({shard 5: std::runtime_error (Failed to generate sharding metadata for /u01/scylla/data/<keyspace>/<tablename>/mc-77173-big-Data.db), shard 8: std::runtime_error (Failed to repair for keyspace=pushserver, cf=hpx_sent_out_messages, range=(5793188823999599049, 5835646411208331079])})
Dec 26 18:34:18 p1992 scylla[501753]:  [shard 0] repair - repair_tracker run for repair id 7 failed: std::runtime_error ({shard 5: std::runtime_error (Failed to generate sharding metadata for /u01/scylla/data/<keyspace>/<tablename>/mc-77173-big-Data.db), `

We have upgrade Scylla to 4.2.2 and remove second DC for experiments, but the result is the same.

**Comment by slivne** [comment]
@asias ping

**Comment by zooptwopointone** [comment]
I have just rain into this problem as well. 
4.2.1-0.20201108.4fb8ebccff with build-id d19a95fd85a8e7df2928ccd8c729941f263e8adc
my table is using SizeTiered compaction and does have a materialized view related with it.

**Comment by r4fek** [comment]
Hello,

same for me:
```
mar 01 11:48:29 am4-dbs1 scylla[29230]:  [shard 8] repair - repair id 3 on shard 8 failed: std::runtime_error (Failed to generate sharding metadata for /var/lib/scylla/data/sync/preference-0066a4a094ad11e893cf000000000017/mc-613096-big-Data.db)
```
File is not present on the disk.

**Comment by raphaelsc** [comment]
> I have just rain into this problem as well.
> 4.2.1-0.20201108.4fb8ebccff with build-id d19a95fd85a8e7df2928ccd8c729941f263e8adc
> my table is using SizeTiered compaction and does have a materialized view related with it.

This is potentially materialized view using wrong schema. A recent problem involving wrong schema in mv table is here https://github.com/scylladb/scylla/issues/7061 but the fix is available in 4.2.1. The problem manifested itself first here https://github.com/scylladb/scylla/issues/2932, a long time ago, and of course, it's already fixed as well.

**Comment by slivne** [comment]
@asias ping on https://github.com/scylladb/scylla/issues/7056#issuecomment-705687678

**Comment by asias** [comment]
>     * I thought that repair is supposed to write sstables to the `<table>/staging` directory not the `<table>` directory
> 
>     * After we seal the sstable we move the sstable from `<table>/staging` to `<table>`
> 
> 
> @asias can you please clarify this - is writing to staging conditional if we have an MV/SI ?

If the repair reason is repair (not repair based ops) and the table has MV/SI, we always write to staging directory. 

> 
> Could it be that we have a mutation that we think we will write and thus open an sstable but at the end do not write it (example - a tombstone mutation that passes its gc_period) @denesb / @asias ?

When repair decides to write a mutation fragment, repair already has that mutation fragment in memory. Repair does not read it again from the reader, so case like tombstone mutation fragment is gone after repair decides we need to write a fragment should not happen.

**Comment by slivne** [comment]
@bhalevy / @asias I am lost - so it seems that if MV/SI are not present then we will write sstables to the regular directory - in which case the errors https://github.com/scylladb/scylla/issues/7056#issuecomment-787888689 are generated from repair trying to generate sstables and failing todo so. 

So what is the explanation for getting those errors ?

(based on asias explenation - there is a mutation - there is no "empty" data file - and as such sharding metadata should be created).

**Comment by bhalevy** [comment]
Maybe this is another manifestation of #7482 where an ignored exception might cause us to seal the sstable prematurely.
Yet if we don't complain about missing partition_end there should be at least one key...
cc @gleb-cloudius

**Comment by slnnk** [comment]
I have a same problem on 4.1.11. I noticed that errors for a specific keyspace only occur when compaction is running on the same keyspace.

**Comment by bhalevy** [comment]
> I have a same problem on 4.4.1. I noticed that errors for a specific keyspace only occur when compaction is running on the same keyspace.

@slnnk can you please share scylla logs?

**Comment by asias** [comment]
> > I don't think that can happen. We don't change partition->shard mapping at runtime.
> 
> Hmm. I claimed that the sstable is not empty because right before we generate sharding metadata, we assert the existence of first and last keys. Could this problem happen if the range spanned by the SSTable being written is no longer owned by the node by the time we try to create its sharding metadata?

@raphaelsc Looking at the code, we will throw from get_first_decorated_key or get_first_decorated_key, if no keys were written into the sstable. We did see the throw was coming from line 1602 below. So, the upper layer must have written keys into the sstable.  What could go wrong is that the sstable was written with keys that belongs to the shard. However, looking at multishard_writer::handle_mutation_fragment, the fragment is routed to the correct shard on each fragment basis. This theory does not hold. Another theory: perhaps in create_sharding_metadata, dht::split_range_to_single_shard calucated the ranges wrongly, i.e., a ranges longs to the shard, but dht::split_range_to_single_shard emits zero ranges. 



```
1592 void
1593 sstable::write_scylla_metadata(const io_priority_class& pc, shard_id shard, sstable_enabled_features features, struct run_identifier identifier,
1594         std::optional<scylla_metadata::large_data_stats> ld_stats, sstring origin) {
1595     auto&& first_key = get_first_decorated_key();
1596     auto&& last_key = get_last_decorated_key();
1597     auto sm = create_sharding_metadata(_schema, first_key, last_key, shard);
1598 
1599     // sstable write may fail to generate empty metadata if mutation source has only data from other shard.
1600     // see https://github.com/scylladb/scylla/issues/2932 for details on how it can happen.
1601     if (sm.token_ranges.elements.empty()) {
1602         throw std::runtime_error(format("Failed to generate sharding metadata for {}", get_filename()));
1603     }
```

```
123 future<stop_iteration> multishard_writer::handle_mutation_fragment(mutation_fragment mf) {
124     auto f = make_ready_future<>();
125     if (mf.is_partition_start()) {
126         _consumed_partitions++;
127         if (unsigned shard = shard_for_mf(mf); shard != _current_shard) {
128             _current_shard = shard;
129             if (!bool(_shard_writers[shard])) {
130                 f = make_shard_writer(shard);
131             }
132         }
133     }
134     return f.then([this, mf = std::move(mf)] () mutable {
135         assert(_current_shard != -1u);
136         return _queue_reader_handles[_current_shard]->push(std::move(mf));
137     }).then([] {
138         return stop_iteration::no;
139     });
140 }
```

**Comment by slivne** [comment]
we have added additionbal debug info - if this happens again we will be able to analyze it - closing this issue
