### ISSUE TITLE
Unable to ALTER system_auth tables

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#7057]
*Installation details*
Scylla version: 4.0.3 (I suspect it's broken in the `master` too)
Cluster size: 1

*Description*
When I try to alter most (not all!) system_auth tables as follows I'm getting an error:

```
cqlsh> ALTER TABLE system_auth.roles with speculative_retry = 'NONE';
Unauthorized: Error from server: code=2100 [Unauthorized] message="<table system_auth.roles> is protected"
```

The error above has been received both when authorization was disabled and enabled.

This seems to be a regression from https://github.com/scylladb/scylla/commit/a855e82eff5dfe7f2b2a4f776e302d3b534dd018

**Comment by vladzcloudius** [comment]
The problem comes from the `standard_role_manager::protected_resources()`.
There is also seems to be no way to disable a role manager or choose some kind of "allow all role manager" similarly to authenticator.

**Comment by eliransin** [comment]
@vladzcloudius Why is this a bug? This table is protected for a reason. The system relies on a some of it's properties like schema for functionality. Lets assume for the sake of argument this is a virtual table, what meaning would be to this alter 
query now.
Another question is what is the purpose of the query?
If anything, I would expect something like a configuration option like: `internal_tables_speculative_retry`
Or another possibility is to be more fine grained about what are we protecting, for example some options like speculative retry,
to be unprotected.

**Comment by vladzcloudius** [comment]
> @vladzcloudius Why is this a bug? This table is protected for a reason. The system relies on a some of it's properties like schema for functionality. Lets assume for the sake of argument this is a virtual table, what meaning would be to this alter
> query now.
> Another question is what is the purpose of the query?
> If anything, I would expect something like a configuration option like: `internal_tables_speculative_retry`
> Or another possibility is to be more fine grained about what are we protecting, for example some options like speculative retry,
> to be unprotected.

@eliransin I agree that this whole KS (together with other `system_xxx` KSes) is special - no doubt.
That's why only a privileged users should be allowed to alter them - which I think IS the case.

As to being able to alter both KS and tables - this is a fact of life and we need to do it from time to time, e.g. when we want to change its replication configuration, or like here - when we want to change parameters like `speculative_retry`.

While I do understand your concern, however we were able to do such alterations in the past and the intent of the code seems to allow this when authorization is disabled (at least).

It simply looks like a bug that we can't do it now.

I think it should be safe to restore the original behaviour now and probably make the "protection" checks for `system_xx` tables less coarse in the future, e.g. not allow removing columns.

**Comment by vladzcloudius** [comment]
@eliransin Any progress on fixing this?

**Comment by vladzcloudius** [comment]
@slivne Please, consider changing the milestone for this one - we are suffering from this in the field.

**Comment by vladzcloudius** [comment]
@amihayday Please, add this issue to your tracking list.

**Comment by dekimir** [comment]
> I agree that this whole KS (together with other `system_xxx` KSes) is special - no doubt.
> That's why only a privileged users should be allowed to alter them - which I think IS the case.

It isn't:
```bash
$ cqlsh -u cassandra -p cassandra -e "ALTER TABLE system_auth.roles with speculative_retry = 'NONE';"
<stdin>:1:Unauthorized: Error from server: code=2100 [Unauthorized] message="<table system_auth.roles> is protected"
```
(with PasswordAuthenticator and CassandraAuthorizer)

> As to being able to alter both KS and tables - this is a fact of life and we need to do it from time to time

How do you propose we distinguish between acceptable and unacceptable alterations?  Clearly some alterations can make the database unusable with no warning and no easy repair options.

> , e.g. when we want to change its replication configuration, or like here - when we want to change parameters like `speculative_retry`.

Can you say just a bit more on WHY you want to change these traits?  Which practical problem(s) can be solved only by altering the roles table?

> While I do understand your concern, however we were able to do such alterations in the past

Not since 2.2, almost three years ago.

> and the intent of the code seems to allow this when authorization is disabled (at least).

The intent of `protected_resources` is to protect some resources regardless of authorization, because a wrong operation on such resources bricks a node.  I'm OK with exempting some operations, but first I'd like to a) clearly define them, and b) understand which specific problem that solves.

**Comment by vladzcloudius** [comment]
> > I agree that this whole KS (together with other `system_xxx` KSes) is special - no doubt.
> > That's why only a privileged users should be allowed to alter them - which I think IS the case.
> 
> It isn't:
> 
> ```shell
> $ cqlsh -u cassandra -p cassandra -e "ALTER TABLE system_auth.roles with speculative_retry = 'NONE';"
> <stdin>:1:Unauthorized: Error from server: code=2100 [Unauthorized] message="<table system_auth.roles> is protected"
> ```
> 
> (with PasswordAuthenticator and CassandraAuthorizer)
> 

I meant it WAS the case before the regression, @dekimir. Please, see first two messages on this issue.


> > As to being able to alter both KS and tables - this is a fact of life and we need to do it from time to time
> 
> How do you propose we distinguish between acceptable and unacceptable alterations? Clearly some alterations can make the database unusable with no warning and no easy repair options.
> 

Patch `protected_resources` and `service::client_state::has_access()`.

> > , e.g. when we want to change its replication configuration, or like here - when we want to change parameters like `speculative_retry`.
> 
> Can you say just a bit more on WHY you want to change these traits? Which practical problem(s) can be solved only by altering the roles table?

There are many WHYs. As any other distributed table it requires tweaking sometimes. 
And this regression is very troubling. 
Read some discussion about speculative_retry wonders here: https://github.com/scylladb/scylla/issues/7472.

If you want to discuss in general why speculative_retry is more damaging than helping - let's take it offline. This issue has a much wider scope.

> 
> > While I do understand your concern, however we were able to do such alterations in the past
> 
> Not since 2.2, almost three years ago.

Not sure how this is related to this issue. 

> 
> > and the intent of the code seems to allow this when authorization is disabled (at least).
> 
> The intent of `protected_resources` is to protect some resources regardless of authorization, because a wrong operation on such resources bricks a node. I'm OK with exempting some operations, but first I'd like to a) clearly define them, and b) understand which specific problem that solves.

I suggest we try the opposite direction: which alterations do you think can brick the node?
AFAICT the ONLY operation that can brick the node is deleting a column. (And even this is not going to brick it since one can disable the authorization and add the column back.)

Is there anything else?

If not, please, black list this one and allow us the rest. 
And no, you don't really need to know WHY the user wants to do this or that alteration unless it bricks the node or gets it into an unrecoverable state.

The administrative privileges are meant to be given to users who know what they are doing. So, let's not overthink it, please.

**Comment by vladzcloudius** [comment]
@avikivity, please, consider backporting this.

**Comment by avikivity** [comment]
Too soon!

**Comment by vladzcloudius** [comment]
> Too soon!

I didn't ask to do it "now"... ;)
But you can do it next week for instance :P
