### ISSUE TITLE
SSTable unhandled write error

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#706]
Found with the new CharibeFS regular expression option.

RROR [shard 4] database - failed to write sstable: std::system_error (error system:11, Resource temporarily unavailable)
ERROR [shard 4] database - failed to write sstable: std::system_error (error system:30, Read-only file system)
ERROR [shard 4] database - failed to write sstable: std::system_error (error system:27, File too large)

I think it is related to the decision we must take for #705. What is the sane behavior to adopt.

**Comment by benoit-canet** [comment]
After further examination this look like a catchall error.

With     client.set_fault(["close", "ioctl", "open", "ioctl", "fstat", "fallocate", "lseek"], True, 0, 10000, "", False, 0) this error will trigger despite not having any "write" or "write_buf" in the list.

**Comment by nyh** [comment]
This very strange... This "failed to write sstable" message is in database.cc, after the sstable was already written successfully! So it appears a wrong message? Moreover, I don't understand what error it catches (what in that code can throw an exception), and why it uses try/catch and not future mechanisms?

**Comment by avikivity** [comment]
Why do you think it is unhandled?  It looks handled to me.

Scylla can't magically convert an I/O error to a working system.

A good test is:

write lots of data
inject errors
write even more data
stop injecting errors
write even more
shut down the node
restart
read the data and verify that all acknowledged data was written

the key is to stop injecting errors and let the node recover.

**Comment by slivne** [comment]
Solution should be provided with #705

**Comment by benoit-canet** [comment]
Closed by:
1fb9a48ac5fe332a948bd006d9c64aa11916a77a
3b1d3d977d50204400fc6277390a1740e22d34ce

Tested a day of two with CharybdeFS. I am pretty confident it's ok.
