### ISSUE TITLE
table::get_sstables_by_partition_key(): dangling reference to list of sstables when do_for_each() defers

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#7060]
Scylla version (or git commit hash): 9aa47122705ff31c92fa1f83c605235bb718c14b

https://github.com/scylladb/scylla/blob/9aa47122705ff31c92fa1f83c605235bb718c14b/table.cc#L1152-L1164

Even though `incremental_selector::selection::sstables` is a reference that is guaranteed to be kept valid until the next `select()` call, as we assign it to `auto sst`, we make a copy. This results in a dangling reference if the `do_for_each()` defers.

**Comment by denesb** [comment]
All live releases are affected.

**Comment by denesb** [comment]
This function is called from the REST API method `/column_family/sstables/by_key/{name}`.

**Comment by avikivity** [comment]
Backported to 4.0, 4.1, 4.2.
