### ISSUE TITLE
Schema change, adding a counter column into a non-counter table, is incorrectly persisted and results in a crash

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#7065]
*Installation details*
Scylla version (or git commit hash): f3af6ff22198f14d6
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

```
cqlsh> CREATE TABLE ks.tb (            a text,            b text,            PRIMARY KEY (a, b)         ) WITH CLUSTERING ORDER BY (b ASC);
cqlsh> describe ks.tb

CREATE TABLE ks.tb (
    a text,
    b text,
    PRIMARY KEY (a, b)
) WITH CLUSTERING ORDER BY (b ASC);
```

Scylla crashes when adding counter column into non-counter table
```
cqlsh> alter TABLE ks.tb ADD "c" counter;
NoHostAvailable: 
```

```
INFO  2020-08-18 23:41:13,965 [shard 0] schema_tables - Altering ks.tb id=5abe2880-e1c5-11ea-b41f-000000000000 version=13b7a23e-be1b-373f-88fb-c484d1aa97fc
scylla: table.cc:1600: void table::set_schema(schema_ptr): Assertion `s->is_counter() == _schema->is_counter()' failed.
Aborting on shard 0.
Backtrace:
  0x0000000001b6a378
  0x0000000001b3fcb2
  0x0000000001b3fe05
  0x0000000001b3fe93
  0x00007fda728e2a8f
  /lib64/libc.so.6+0x000000000003c9e4
  /lib64/libc.so.6+0x0000000000025894
  /lib64/libc.so.6+0x0000000000025768
  /lib64/libc.so.6+0x0000000000034e75
  0x0000000000a9c140
  0x0000000000a47918
  0x00000000011b7cd3
  0x00000000011b8f53
  0x0000000001b9f7de
```

When node is restarted, it can be seen schema change was incorrectly persisted even though scylla crashed

```
cqlsh> quit
[raphaelsc@localhost scylla-tools-java]$ ./bin/cqlsh 
Connected to  at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> describe ks.tb

CREATE TABLE ks.tb (
    a text,
    b text,
    "c" counter,
    PRIMARY KEY (a, b)
) WITH CLUSTERING ORDER BY (c ASC);
```

It should have failed with
` ConfigurationException: Cannot add a counter column ("c") in a non counter column family`

**Comment by raphaelsc** [comment]
this was supposed to be handled by this patch 4cbbbc67f0cc79c88ac64a7f17ad731595a57506, so it looks like a regression.

**Comment by slivne** [comment]
Please note this happens only if there are no columns 

```
CREATE TABLE ks.tb (
    a text,
    b text,
    d int,
    PRIMARY KEY (a, b)
) WITH CLUSTERING ORDER BY (b ASC);

alter TABLE ks.tb ADD "c" counter;
ConfigurationException: Cannot add a non counter column (d) in a counter column family
```

will not crash;

**Comment by raphaelsc** [comment]
> Please note this happens only if there are no columns
> 
> ```
> CREATE TABLE ks.tb (
>     a text,
>     b text,
>     d int,
>     PRIMARY KEY (a, b)
> ) WITH CLUSTERING ORDER BY (b ASC);
> 
> alter TABLE ks.tb ADD "c" counter;
> ConfigurationException: Cannot add a non counter column (d) in a counter column family
> ```
> 
> will not crash;

Indeed. Looks like Scylla is incorrectly treating the schema as a counter table, based on the counter column we attempted to add to it. That's wrong.

**Comment by avikivity** [comment]
Backported to 4.0, 4.1, 4.2.
