### ISSUE TITLE
SSTable file close failure

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#707]
Found with the CharibeFS regexp module.

WARN  [shard 4] sstable - sstable close data_file failed: std::system_error (error system:9, Bad file descriptor)

What would be the sane behavior

**Comment by slivne** [comment]
related to #705, #706

**Comment by avikivity** [comment]
What happens here is that a file is closed twice somehow.

Unless charibefs injected that error.  In that case, it should't, it should only inject reasonable errors that can actually happen.

**Comment by benoit-canet** [comment]
Closed by:
1fb9a48ac5fe332a948bd006d9c64aa11916a77a
3b1d3d977d50204400fc6277390a1740e22d34ce

Tested a day of two with CharybdeFS. I am pretty confident it's ok.
