### ISSUE TITLE
scylla_setup: do_verify_package() should support to check installed files directly, not just rpm/deb

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#7075]
*Installation details*
Scylla version (or git commit hash): master unified-package-0.20200819.2e1499ee93f
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

### Description

Currently scylla_setup supports to verify scylla-jmx/scylla-tools packages, it's optional.
But generally it's checked by `rpm -q $name` or `dkpg -s $name`, so it will fail even scylla-jmx/scylla-tools had been installed by offline installer.

It's worth to check those packages at the beginning of scylla_setup. So I suggested we can try to check some key files to know if the packages are installed or not when dpkg or rpm failed.

Or we can run some basic commands to verify that:
- whereis nodetool 
- nodetool help status
- cqlsh --version
- systemctl status scylla-jmx |grep loaded

```
# sudo scylla_setup
....
Do you want to verify the ScyllaDB packages are installed?', 'Yes - runs a script to confirm that ScyllaDB   is installed. No - skips the installation check.
```

/CC @penberg @roydahan @slivne

**Comment by avikivity** [comment]
Offline installer, too new, not backporting.
