### ISSUE TITLE
offline installer: uninstall isn't supported

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#7076]
*Installation details*
Scylla version (or git commit hash): latest master: scylla-unified-package-0.20200819.2e1499ee93f.tar.gz
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS/Debian/Ubuntu

### Description

Original https://github.com/scylladb/scylla/wiki/Offline-Installer is based on RPM/DEB, so we can easily uninstall scylla by removing the RPM/DEB packages.

The new offline installer (unified package) doesn't support to uninstall.

/CC @slivne @roydahan @penberg

**Comment by avikivity** [comment]
New feature, not backporting.
