### ISSUE TITLE
Share sstable index page cache between readers

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#7079]
In 9322c07c712967b3eb4c30f6955890e05932c655 we added a page cache for the index file to support binary search in promoted index. This cache is currently not shared between readers. We could improve efficiency by sharing it. 

When doing random reads over a large partition, some pages will be shared by the reads. In particular, the middle page, which corresponds to the root of the binary search tree, will be hit by every read.

We should also have a single page cache per index file rather than per promoted index (i.e. per partition), so that adjacent partitions can share a page. 

We should also use the page cache for reading the partition index, not just the promoted index.

Refs #2388, #4602

**Comment by denesb** [comment]
This will raise the interesting questions of which reader will "own" the buffers. Currently, there is one permit instance associated with a read, and all accounting goes through this permit. The permit doesn't yet keep tabs on the resources consumed by the read itself, this is all aggregated in the semaphore, however I do plan on implementing this, which will be complicated by shared resources like this. It is also possible that a table will be read by readers belonging to different semaphores. Currently this is only the case for system tables.

This is not really an issue I'm just thinking out lout.

**Comment by avikivity** [comment]
No reader. The buffers are owned by the cache, which can evict them at any time.

**Comment by avikivity** [comment]
btw, not only should index pages by cached, but also parsed index entries. This prevents those middle pages from occupying a lot of space when all that is needed is a small entry.

**Comment by bhalevy** [comment]
@tgrabiec does 7f3083739f20bbc7056b308b742ff77442b7ad5b resolve this issue?

**Comment by tgrabiec** [comment]
@bhalevy No. 7f30837 adds sharing of pages of partition index entries, which is shallow. We only share partition entries, but not the promoted index within.
