### ISSUE TITLE
ami: start 50 nodes cluster, one node does not boot up.

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#708]
[fedora@ip-172-30-0-78 ~]$ nodetool -h 172.30.0.225 status|grep UN |wc -l
49

I check the ip which is not listed in nodetool status and found it is node 172.30.0.202 is missing.

I login node 172.30.0.202 and found scylla process is not started up

[fedora@ip-172-30-0-202 ~]$ ps aux|grep scylla
fedora     937  0.0  0.0  12596  2328 pts/0    S+   02:57   0:00 grep --color=auto scylla

[fedora@ip-172-30-0-202 ~]$ systemctl status scylla-server
● scylla-server.service - Scylla Server
   Loaded: loaded (/usr/lib/systemd/system/scylla-server.service; disabled; vendor preset: disabled)
   Active: inactive (dead)

[fedora@ip-172-30-0-202 ~]$ journalctl |grep scylla
Dec 12 20:12:56 ip-172-30-0-167 groupadd[11928]: group added to /etc/group: name=scylla, GID=1001
Dec 12 20:12:56 ip-172-30-0-167 groupadd[11928]: group added to /etc/gshadow: name=scylla
Dec 12 20:12:56 ip-172-30-0-167 groupadd[11928]: new group: name=scylla, GID=1001
Dec 12 20:12:56 ip-172-30-0-167 useradd[11932]: new user: name=scylla, UID=995, GID=1001, home=/var/lib/scylla, shell=/sbin/nologin
Dec 12 20:12:57 ip-172-30-0-167 audit[11954]: <audit-1116> pid=11954 uid=0 auid=1000 ses=1 subj=unconfined_u:unconfined_r:groupadd_t:s0-s0:c0.c1023 msg='op=add-group acct="scylla" exe="/usr/sbin/groupadd" hostname=? addr=? terminal=? res=failed'
Dec 12 20:12:57 ip-172-30-0-167 audit[11955]: <audit-1114> pid=11955 uid=0 auid=1000 ses=1 subj=unconfined_u:unconfined_r:useradd_t:s0-s0:c0.c1023 msg='op=add-user acct="scylla" exe="/usr/sbin/useradd" hostname=? addr=? terminal=? res=failed'
Dec 12 20:12:57 ip-172-30-0-167 useradd[11955]: failed adding user 'scylla', exit code: 9
Dec 25 02:31:14 ip-172-30-0-167.ec2.internal scylla-setup.sh[414]: RAID does not constructed, going to initialize...
Dec 25 02:31:18 ip-172-30-0-167.ec2.internal scylla-setup.sh[414]: Failed to synchronize cache for repo 'scylla' from 'https://s3.amazonaws.com/downloads.scylladb.com/rpm/fedora/22/x86_64/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Dec 25 02:31:19 ip-172-30-0-167.ec2.internal scylla-setup.sh[414]: Error: Failed to synchronize cache for repo 'fedora' from 'https://mirrors.fedoraproject.org/metalink?repo=fedora-22&arch=x86_64': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-22&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Dec 25 02:31:19 ip-172-30-0-167.ec2.internal systemd[1]: scylla-setup.service: main process exited, code=exited, status=1/FAILURE
Dec 25 02:31:19 ip-172-30-0-167.ec2.internal systemd[1]: Unit scylla-setup.service entered failed state.
Dec 25 02:31:19 ip-172-30-0-167.ec2.internal systemd[1]: scylla-setup.service failed.
Dec 25 02:31:19 ip-172-30-0-167.ec2.internal audit[1]: <audit-1130> pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=scylla-setup comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Dec 25 02:31:20 ip-172-30-0-167.ec2.internal cloud-init[730]: 2015-12-25 02:31:20,102 - __init__.py[WARNING]: Unhandled non-multipart (text/x-not-multipart) userdata: '--clustername scylla50v2...'
Dec 25 02:31:20 ip-172-30-0-167.ec2.internal cloud-init[730]: [CLOUDINIT] __init__.py[WARNING]: Unhandled non-multipart (text/x-not-multipart) userdata: '--clustername scylla50v2...'
Dec 25 02:40:44 ip-172-30-0-202 dnf[869]: scylla: has expired and will be refreshed.
Dec 25 02:40:44 ip-172-30-0-202 dnf[869]: scylla-generic: has expired and will be refreshed.

**Comment by asias** [comment]
scylla-server-0.13.1-20151210.59cd785.fc22.x86_64
scylla_2015-12-12T20-04-27Z (ami-972863fd)

**Comment by slivne** [comment]
We have been running many tests of booting AWS instances and also doing that in clusters - closing this issue till we can reproduce this with newer AMIs
