### ISSUE TITLE
Lost inserts in CQL sets and maps with chaotic timestamps

### ISSUE THREAD

**Issue by aphyr** [scylladb/scylla#7082]
In ScyllaDB 4.2, it appears that inserting unique elements into a CQL map or set can, when clocks are not synchronized, result in the loss of acknowledged inserts. See, for example, [this Jepsen test run](http://jepsen.io.s3.amazonaws.com/analyses/scylla-4.2/20200821T143821.000-0400.zip), in which a single client, performing approximately one insert per second to a single CQL set, loses roughly 35% of acknowledged inserts over a 30 second period--as observed by a single read performed after 20 seconds of quiescence.

This behavior appears to depend on timestamps: when we do not set a TimestampGenerator on clients, or provide clients with a TimestampGenerator which yields values directly from System.currentTimeMillis(), the behavior disappears; when we introduce jitter (on the order of 1 second) to those values, write loss appears.

Our schema for this workload is a [single table](https://github.com/jepsen-io/scylla/blob/604502f3acd3d7a45dfa6117cab79481a0f4cf43/scylla/src/scylla/collections/set.clj#L32-L38) with an integer primary key and a set of integer elements. We insert a single row into this table, and then have clients update that row, each updating the `elements` field to [add a single unique integer](https://github.com/jepsen-io/scylla/blob/604502f3acd3d7a45dfa6117cab79481a0f4cf43/scylla/src/scylla/collections/set.clj#L50-L54). After a few seconds of these inserts, we pause for 20 seconds to allow Scylla time to recover, then perform a [single read](https://github.com/jepsen-io/scylla/blob/604502f3acd3d7a45dfa6117cab79481a0f4cf43/scylla/src/scylla/collections/set.clj#L57-L61) by primary key.

Our randomized timestamps are generated by [this generator](https://github.com/jepsen-io/scylla/blob/604502f3acd3d7a45dfa6117cab79481a0f4cf43/scylla/src/scylla/client.clj#L32-L44)--tuning `uncertainty-s` to zero appears to resolve the write loss issue.

You can reproduce this using [Jepsen's fork](https://github.com/jepsen-io/scylla) of the Scylla Jepsen tests by cloning 604502f and running

```
lein run test-all -w cset --time-limit 30 --nemesis none --concurrency 1 -r 1
```

There may be additional options required (e.g. --user, --password, --nodes-file) depending on your Jepsen environment. See https://github.com/jepsen-io/jepsen#setting-up-a-jepsen-environment for guidance.

This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.2
Cluster size: 5 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): Debian 10

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): LXC
Hardware: sockets=2 cores=24 hyperthreading=2 memory=128GB
Disks: (SSD/HDD, count) SSD (shared via LXC)

**Comment by kostja** [comment]
The following docs are updated with by scylladb/scylla-docs#3150

https://docs.scylladb.com/getting-started/dml/
https://docs.scylladb.com/getting-started/types
https://docs.scylladb.com/kb/lwt-differences
https://docs.scylladb.com/using-scylla/lwt

**Comment by nyh** [comment]
@kostja why did you assign to me a closed issue?
I wanted review the doc commit you mention, but it seems completely unrelated :-( Maybe you have a wrong link?

**Comment by nyh** [comment]
Oh, sorry, I found the right commit in that PR: https://github.com/scylladb/scylla-docs/pull/3150/commits/f5db644ee15df27480cb745867a1b70f06a6b132
Unassigning myself from this issue.
