### ISSUE TITLE
Error in commit log segment reservation

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#709]
WARN  [shard 2] commitlog - Exception in segment reservation: std::system_error (error system:9, Bad file descriptor)
WARN  [shard 6] commitlog - Exception in segment reservation: std::system_error (error system:17, File exists)
WARN  [shard 3] commitlog - Exception in segment reservation: std::system_error (error system:31, Too many links)

The error handling seems improper.

**Comment by slivne** [comment]
#705, #706

**Comment by benoit-canet** [comment]
Closed by:
1fb9a48ac5fe332a948bd006d9c64aa11916a77a
3b1d3d977d50204400fc6277390a1740e22d34ce

Tested a day of two with CharybdeFS. I am pretty confident it's ok.
