### ISSUE TITLE
cdc delta == keys does not produce cdc$operation nor cdc$ttl

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#7095]
If cdc::delta is set to "keys" (keys only), the result is postprocessed to remove certain columns or rows (inefficient - with the latest refactor, it should be easy to just not create it in the first place). 

However, even `cdc$operation` and `cdc$ttl` is removed. That does not seem right.

**Comment by haaawk** [comment]
It seems that @jul-stas was sure this is correct `// We can surely remove "cdc$*" columns.`
but I think we need them actually

**Comment by elcallio** [comment]
Indeed. Fixing.

**Comment by haaawk** [comment]
I have a patch already

**Comment by haaawk** [comment]
Sending it now

**Comment by haaawk** [comment]
The fix is here https://github.com/scylladb/scylla/pull/7096

**Comment by elcallio** [comment]
I think a better fix is to not generate the value parts in the first place, and remove the filtering. With @kbr- :s visitor pattern it is quite straight forward. I have it included in a patch set. I'll send a PR tomorrow.

**Comment by avikivity** [comment]
@nyh please evaluate for backport.

**Comment by nyh** [comment]
Not backporting. These are changes to recently added and refactored code.
