### ISSUE TITLE
Commit log flush failure

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#710]
ERROR [shard 0] commitlog - Failed to flush commits to disk: std::system_error (error system:32, Broken pipe)
ERROR [shard 1] commitlog - Failed to flush commits to disk: std::system_error (error system:8, Exec format error)
ERROR [shard 4] commitlog - Failed to flush commits to disk: std::system_error (error system:11, Resource temporarily unavailable)
ERROR [shard 5] commitlog - Failed to flush commits to disk: std::system_error (error system:31, Too many links)

What is the correct handling for this ?

**Comment by slivne** [comment]
related to #705, #706

**Comment by benoit-canet** [comment]
Closed by:
1fb9a48ac5fe332a948bd006d9c64aa11916a77a
3b1d3d977d50204400fc6277390a1740e22d34ce

Tested a day of two with CharybdeFS. I am pretty confident it's ok.
