### ISSUE TITLE
Alternator Streams: NewImage is missing the old item's key

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7107]
This issue is similar related to #6935, which is the same problem for `OldImage` whereas this issue is about `NewImage`. It is probably possible to solve both problems with the same patch set, although there may be some differences in the implementation so we may end up closing the two issues with separate patches.

DynamoDB Streams includes in `NewImage` the entire new item - including its key attributes. Alternator is currently missing the key attributes in this item.

If the new value of the item is empty - i.e., it includes just key attributes and no other content - then `NewImage` should still appear and include only the key attributes, it shouldn't be missing. However, if the operation is a deletion of the entire item, the `NewImage` should be missing entirely - not empty.

I wrote two tests reproducing this in `test_streams.py`: `test_streams_new_image` and `test_streams_new_and_old_images`.

CC @elcallio

**Comment by elcallio** [comment]
Can you post the tests? Or did I miss them?

**Comment by nyh** [comment]
Sorry, I was about to post them and was too slow :-( Expect the patch in a few minutes.

**Comment by nyh** [comment]
On the mailing list now, titled "alternator test: tests for NewImage feature of Alternator Streams". Sorry about the delay, I created the issue first, to get an issue number to use in the patch, but then was too slow to send out the patch :-)

**Comment by avikivity** [comment]
@nyh please evaluate for backport.

**Comment by nyh** [comment]
Alternator Streams was not yet in 4.2, so no need to backport.
