### ISSUE TITLE
exception during mutation write

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#711]
ERROR [shard 2] storage_proxy - exception during mutation write to 127.0.0.1: std::system_error (error system:47, Level 3 reset)

**Comment by avikivity** [comment]
Did that error result in a crash or other ill effect?

We should already recover from these errors.

**Comment by benoit-canet** [comment]
No it does not crash and I am not sure about ill effect since in my test error are sprayed all over the place.

> We should already recover from these errors.

Maybe making the "Level 3 reset" part more explicit in order to notify the user that everything is fine
would reassure the user.

**Comment by nyh** [comment]
On Sun, Dec 27, 2015 at 5:58 PM, Benoît Canet <notifications@github.com>
wrote:

> No it does not crash and I am not sure about ill effect since in my test
> error are sprayed all over the place.
>
> We should already recover from these errors.
>
> Maybe making the "Level 3 reset" part more explicit in order to notify the
> user that everything is fine
> would reassure the user.
>

The "Level 3 reset" is just the silly name of errno 47, which is of course
completely bogus, so there is now way we can explain better the "Level 3
reset" part ;-)

Perhaps more worrying is the other part of this message: storage_proxy -
exception during mutation write to 127.0.0.1:
I think that the typical user will not be able to make much sense from
"storage_proxy - exception during mutation write": What is a "mutation
write" - is this a replicate to a remote node, or write to disk? What is a
storage_proxy? Is this error a disaster or something that we recovered
from? Was data lost, or did we retry and finally managed to fix things?

I'm not sure what to suggest though. Perhaps this error message is good
enough - if it ever happens, the most the user will be able to do is to
report it to us, but it's better than silently ignoring it, of course.

**Comment by gleb-cloudius** [comment]
On Sun, Dec 27, 2015 at 08:07:13AM -0800, nyh wrote:
> On Sun, Dec 27, 2015 at 5:58 PM, Benoît Canet <notifications@github.com>
> wrote:
> 
> > No it does not crash and I am not sure about ill effect since in my test
> > error are sprayed all over the place.
> >
> > We should already recover from these errors.
> >
> > Maybe making the "Level 3 reset" part more explicit in order to notify the
> > user that everything is fine
> > would reassure the user.
> >
> 
> The "Level 3 reset" is just the silly name of errno 47, which is of course
> completely bogus, so there is now way we can explain better the "Level 3
> reset" part ;-)
> 
> Perhaps more worrying is the other part of this message: storage_proxy -
> exception during mutation write to 127.0.0.1:
> I think that the typical user will not be able to make much sense from
> "storage_proxy - exception during mutation write": What is a "mutation
> write" - is this a replicate to a remote node, or write to disk? What is a
> storage_proxy? Is this error a disaster or something that we recovered
> from? Was data lost, or did we retry and finally managed to fix things?
> 
All those messages are not for typical users. As far as "typical user"
is concerned if cql query for completed successfully his data is safe
(eventually) otherwise error should be returned. Anything else is a bug.

> I'm not sure what to suggest though. Perhaps this error message is good
> enough - if it ever happens, the most the user will be able to do is to
> report it to us, but it's better than silently ignoring it, of course.
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/scylladb/scylla/issues/711#issuecomment-167421849

--
			Gleb.

**Comment by tzach** [comment]
I see the same error message on a cluster testing on EC2, testing with scylla 0.16
```
Jan 28 15:08:49 ip-172-31-40-177 scylla[830]:  [shard 1] storage_proxy - exception during mutation write to 172.31.40.177: std::bad_alloc (std::bad_alloc)
Jan 28 15:08:49 ip-172-31-40-177 scylla[830]:  [shard 1] storage_proxy - exception during mutation write to 172.31.40.177: std::bad_alloc (std::bad_alloc)
Jan 28 15:08:49 ip-172-31-40-177 scylla[830]:  [shard 1] storage_proxy - exception during mutation write to 172.31.40.177: std::bad_alloc (std::bad_alloc)
Jan 28 15:08:49 ip-172-31-40-177 scylla[830]:  [shard 1] storage_proxy - exception during mutation write to 172.31.40.177: std::bad_alloc (std::bad_alloc)
Jan 28 15:08:49 ip-172-31-40-177 scylla[830]:  [shard 1] storage_proxy - exception during mutation write to 172.31.40.177: std::bad_alloc (std::bad_alloc)
Jan 28 15:08:49 ip-172-31-40-177 scylla[830]:  [shard 1] storage_proxy - exception during mutation write to 172.31.40.177: std::bad_alloc (std::bad_alloc)
Jan 28 15:08:49 ip-172-31-40-177 scylla[830]:  [shard 1] storage_proxy - exception during mutation write to 172.31.40.177: std::bad_alloc (std::bad_alloc)
Jan 28 15:08:49 ip-172-31-40-177 scylla[830]:  [shard 1] storage_proxy - exception during mutation write to 172.31.40.177: std::bad_alloc (std::bad_alloc)
Jan 28 15:08:49 ip-172-31-40-177 scylla[830]:  [shard 1] storage_proxy - exception during mutation write to 172.31.40.177: std::bad_alloc (std::bad_alloc)
Jan 28 15:08:49 ip-172-31-40-177 scylla[830]:  [shard 4] storage_proxy - exception during mutation write to 172.31.40.177: std::bad_alloc (std::bad_alloc)
```

**Comment by benoit-canet** [comment]
Closed by:
1fb9a48ac5fe332a948bd006d9c64aa11916a77a
3b1d3d977d50204400fc6277390a1740e22d34ce

Tested a day of two with CharybdeFS. I am pretty confident it's ok.
