### ISSUE TITLE
redis test "test_raw_cmd.py::test_ping_and_eof" fails in debug build

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7114]
The test `test/redis/run test_raw_cmd.py::test_ping_and_eof` fails, but only in debug mode. The problem reported is:

```
>       verify_cmd_response(redis_host, redis_port, "*1\r\n$4\r\nping\r\n\x04", "+PONG\r\n-ERR unknown command ''\r\n", shutdown=True)
test_raw_cmd.py:74: 
...
E       assert '+PONG\r\n' == "+PONG\r\n-ERR unknown command ''\r\n"
```

The same test always passes in dev mode.

CC @syuu1228

**Comment by nyh** [comment]
The plot thickens :-(

Both `test/redis/run test_raw_cmd.py::test_ping_and_eof` and `test/redis/run test_raw_cmd.py::test_ping` **fail** when run against the standard redis (just run redis in the background, and then "pytest"). Which is bad - all our tests should pass on Redis first.

Both tests expect an invalid command name (they use the silly one-character command "0x04") to elicit an "-ERR unknown command ''" error from the server, but redis does not do that, when the garbage command doesn't end with a newline. Experimenting with redis:
```
$ echo hi | nc localhost 6379 
-ERR unknown command `hi`, with args beginning with: 
$ echo -n hi | nc localhost 6379 
``` 
Redis only parses the command when reaching a newline - if there is no newline, it is silently ignored. So the garbage at the end of our tests is just ignored, and our parser should ignore an incompletely parsed command as well.

if we ignore for a moment the fact that we should ignore an incomplete command, note that the 0x04 string used in these tests is just a command name - it could also have been "dog" (the fact that 0x04 is a control character, or just one character, doesn't prevent it from being a "command"). So the "unknown command" error would have been justified. The fact that in debug mode it doesn't happen and in dev mode it does suggest that we have a more serious in the code, perhaps something in the logic of the continuations waiting for commands to finish, continuation reordering, or something. Log messages suggest the unknown command *is* invoked, it just doesn't generate its output in debug mode.

I think we should clean up these tests to test the following:
1. Sending an unknown command, e.g., "dog", ending  command with a newline, should generate an "unknown command" error.
2. Sending an unknown command (e.g., "dog") followed by end of file with new newline, should not generate any output. Obviously in all build modes. We can't have it generate an error in dev build and not generate an error in debug build...

**Comment by nyh** [comment]
I don't know why in the past this test failed only in debug mode. Today it fails in dev mode as well.

**Comment by avikivity** [comment]
Redis is not production ready, so not backporting.
