### ISSUE TITLE
cdc: Should not generate pre-image if a row did not exist

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#7119]
CDC log for an insert should not have pre-image if the row did not already exist. 
If a row exists, but only as row marker, an empty pre-image should be generated.

**Comment by avikivity** [comment]
@nyh please evaluate for backport

**Comment by nyh** [comment]
Not backporting. Changes to recent code, and aimed for fixing a Alternator Streams bug, and Alternator Streams isn't yet in 4.2.
