### ISSUE TITLE
cdc: Should not generate postimage for a deleted row

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#7120]
CDC log should not generate a post-image if the operation(s) in a given batch sequence resulted in the deletion of the row. 
If all columns were deleted, an empty post-image should be generated.

**Comment by avikivity** [comment]
@nyh please evaluate for backport

**Comment by nyh** [comment]
Not backporting. Changes to recent code, and aimed to fix an Alternator Streams bug which isn't in 4.2 anyway.
