### ISSUE TITLE
cdc: check_and_repair_cdc_streams hangs if repair was needed

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#7127]
The `check_and_repair_cdc_streams` function, called by `nodetool checkAndRepairCdcStreams`, is supposed to create a new CDC generation in case the current one (i.e. the last one gossiped by nodes) cannot be retrieved from the CDC generation tables.

It successfully manages to do so, but then it hangs. Nodetool never returns, and the function also doesn't return which I checked by inserting `cout` at the end of the function. It also prevents Scylla from being shut down using an interrupt -- I have to sigkill it. But other than that, Scylla works.

Checked on master (f7c5c48df6e7a39737b85cc91bddfae1ac549f4c).

To reproduce:
1. start a node with CDC experimental feature enabled
2. `select time from system_distributed.cdc_generations`
3. copy the timestamp, for example I got `2020-08-26 14:24:47.702000+0000`
4. fix the timestamp so Scylla can understand it by removing the last 3 `0`s before the `+`, in this example `2020-08-26 14:24:47.702+0000` (probably a bug somewhere either in marshaling or in unmarshaling timestamps...)
5. Delete the generation: `delete from system_distributed.cdc_generations where time = 2020-08-26 14:24:47.702+0000`
6. run scylla-jmx, run `nodetool checkAndRepairCdcStreams`
7. a new generation appears, which is good... but the command hangs

Using `cout`s I investigated that the function hangs here (`cout`s mine):
```
        std::cout << "add local app state" << std::endl;
        _gossiper.add_local_application_state({
                { gms::application_state::CDC_STREAMS_TIMESTAMP, versioned_value::cdc_streams_timestamp(new_streams_ts) },
                { gms::application_state::STATUS, *status }
        }).get();
        std::cout << "update cdc streams ts" << std::endl;
```
that is, it hangs on the `get()`. Which is weird, because logs say that the state was successfully updated:
```
add local app state
INFO  2020-08-26 16:25:29,272 [shard 0] storage_service - Node 127.0.0.2 state jump to normal
```

**Comment by kbr-** [comment]
Looks like a deadlock in `gossiper::add_local_application_state` at this line:
```
            auto permit = gossiper.lock_endpoint(ep_addr).get0();
```

**Comment by kbr-** [comment]
It looks like this line:
```
                gossiper.do_on_change_notifications(ep_addr, state, value);
```
for `state == STATUS` causes recursive `add_local_application_state`, which leads to a deadlock

**Comment by kbr-** [comment]
The issue occurs on the original commit which introduced the function: 0ad50013ff2dfb387aa8ca90606715ac3cc80a6b :(

**Comment by kbr-** [comment]
Btw. this issue is pretty serious, because `add_local_application_state` is called periodically about once every second, for states such as `CACHE_HITRATES` and `VIEW_BACKLOG`. Each tries to get the lock.

**Comment by nyh** [comment]
Fixed by commit 42fb4fe37ce745612b9d60ec9ecb5718747603d0 (which was unfortunately missing a "Fixes:" so this issue didn't get closed automatically). Will do the backports now.

**Comment by nyh** [comment]
Backported to 4.2 (5d90fa17d618f37c3e761ec4efd34570caac3bab). Doesn't apply to older branches.

**Comment by kbr-** [comment]
Thanks.

**Comment by dkropachev** [comment]
> Backported to 4.2 ([5d90fa1](https://github.com/scylladb/scylla/commit/5d90fa17d618f37c3e761ec4efd34570caac3bab)). Doesn't apply to older branches.

Just got this issue on 4.1 when node is just about to start and join the cluster:
2020-09-25T03:25:42+00:00  rolling-upgrade-master-centos-db-node-245b5493-0-3 !INFO    | scylla[49388]: [shard 0] init - Shutting down sighup was successful
2020-09-25T03:25:42+00:00  rolling-upgrade-master-centos-db-node-245b5493-0-3 !ERR     | scylla[49388]: [shard 0] init - Startup failed: exceptions::mutation_write_timeout_exception (Operation timed out for syst
em_distributed.cdc_generations - received only 2 responses from 3 CL=QUORUM.)

**Comment by dkropachev** [comment]
> @dkropachev that's an unrelated error. It looks like the node tried to join into a cluster with a bunch of nodes unavailable.

@kbr- , if you have details could you specify ones on what does "unavailable node" mean in this context. Nodes was up, cql port was up, gossip completed, what we could miss there?

**Comment by kbr-** [comment]
It was a timeout exception, which could mean many things:
- the replica that coordinator tried to contact was down
- there was a network partition between the coordinator and replica
- the replica was super slow and couldn't process the write in time

Please make an issue -- maybe we should make a better decision what to do in this case. As far as I understand, today the node will simply refuse to join if such thing happens, so the admin has to retry bootstrapping it.
