### ISSUE TITLE
cdc: Remove delta_mode::off

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#7128]
CDC information is not useful without at least `delta==keys`, since pre/post image data contains no info on _what_ is actually done in base table operations. 
The addition was a bad (by me - shame!) idea, and we should remove it before we go GA with cdc, so no one uses it by accident.

**Comment by avikivity** [comment]
@nyh please evaluate for backport.

**Comment by nyh** [comment]
No need to backport - fixes a feature added after 4.2.
