### ISSUE TITLE
nonroot install: scylla-python3 isn't loaded for setup scripts

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#7130]
*Installation details*
Scylla version (or git commit hash): scylla-unified-package-666.development-0.20200825.f7c5c48df.tar.gz
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS8

### test steps
1. download unified package
2. uncompress the package
3. install: `./install.sh --nonroot`
4. try to run scylla_setup
```
cd ~/scylladb
./sbin/scylla_setup
```

### Error

```
scylla-test@artifacts-debian10-jenkins-db-node-51429c31-0-1:~/scylladb$ ./sbin/scylla_setup 
Traceback (most recent call last):
  File "/home/scylla-test/scylladb/scripts/libexec/scylla_setup", line 30, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'
scylla-test@artifacts-debian10-jenkins-db-node-51429c31-0-1:~/scylladb$ ./scripts/scylla_setup
Traceback (most recent call last):
  File "/home/scylla-test/scylladb/scripts/libexec/scylla_setup", line 30, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'
scylla-test@artifacts-debian10-jenkins-db-node-51429c31-0-1:~/scylladb$ 
```

**Comment by amoskong** [comment]
The problem doesn't exist if python3 path is assigned for unified/install.sh
But it's strange to assign a non-existing python3 before installing scylla/scylla-python3/scylla-jmx/scylla-tools.

`./install.sh --nonroot --python3 ~/scylladb/python3/bin/python3`

**Comment by amoskong** [comment]
posted an enhancement: https://github.com/scylladb/scylla/pull/7132
- offline installation: fix default value of python3/sysconfdir and a small cleanup #7132

**Comment by syuu1228** [comment]
Looks like a bug of install.sh, not just unified/install.sh, since I copied most of the code from it.
I may mistakenly tested nonroot with locally installed /opt/scylladb/python3/bin/python3..

**Comment by amoskong** [comment]
> Looks like a bug of install.sh, not just unified/install.sh, since I copied most of the code from it.
> I may mistakenly tested nonroot with locally installed /opt/scylladb/python3/bin/python3..

Yes, the problem is fixed by https://github.com/scylladb/scylla/pull/7132

**Comment by avikivity** [comment]
@amoskong is a backport needed? it looks like a new problem.

**Comment by amoskong** [comment]
> @amoskong is a backport needed? it looks like a new problem.

No, the unified/install.sh only exists on master, and new offline installer isn't supported yet.

**Comment by tarzanek** [comment]
just hit something similar with 4.2 rc4 upgrade from 4.1
so I guess backport is needed
```
Sep 30 10:02:25 scylla systemd[1]: Starting Scylla Server...
Sep 30 10:02:25 scylla scylla_prepare[2081]: Traceback (most recent call last):
Sep 30 10:02:25 scylla scylla_prepare[2081]: File "/opt/scylladb/scripts/libexec/scylla_prepare", line 28, in <module>
Sep 30 10:02:25 scylla scylla_prepare[2081]: from scylla_util import *
Sep 30 10:02:25 scylla scylla_prepare[2081]: File "/opt/scylladb/scripts/scylla_util.py", line 35, in <module>
Sep 30 10:02:25 scylla scylla_prepare[2081]: import distro
Sep 30 10:02:25 scylla scylla_prepare[2081]: ModuleNotFoundError: No module named 'distro'
Sep 30 10:02:25 scylla systemd[1]: scylla-server.service: control process exited, code=exited status=1
Sep 30 10:02:25 scylla systemd[1]: Failed to start Scylla Server.
```

**Comment by avikivity** [comment]
@tarzanek please provide more context, was this upgrade in a nonroot install?

**Comment by amoskong** [comment]
> @tarzanek please provide more context, was this upgrade in a nonroot install?

It seems not a nonroot install, need to check if scylla-python3 is installed/upgraded correctly.
Please check if python3-distro exists.

```
$ find /opt/scylladb/python3|grep python3-distro
/opt/scylladb/python3/licenses/python3-distro
/opt/scylladb/python3/licenses/python3-distro/LICENSE
```

**Comment by tarzanek** [comment]
rpm install from repo, not nonroot, so yes, sorry for hijacking
I should open a new issue

Amos:
```
[scylla@scylla ~]$ find /opt/scylladb/python3|grep python3-distro
```
so not there for me

**Comment by tarzanek** [comment]
sorry, filed https://github.com/scylladb/scylla/issues/7305 to track the problem
