### ISSUE TITLE
nonroot install: can't find scylla log by journalctl --user -xe

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#7131]
*Installation details*
Scylla version (or git commit hash): scylla-unified-package-666.development-0.20200825.f7c5c48df.tar.gz
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS8

After nonroot installation on CentOS8.
Scylla-server can be started. But I can't any scylla log in 'jounalctl --user -xe'.

**Comment by penberg** [comment]
@amoskong I think you need to pass the `--user` flag to `journalctl`, no?

**Comment by avikivity** [comment]
@penberg nice

**Comment by amoskong** [comment]
> @amoskong I think you need to pass the `--user` flag to `journalctl`, no?

I tested both `journalctl -xe` and `journalctl --user -xe`.

`journalctl --user -xe` works on Ubuntu 18.04
`journalctl --user -xe` doesn't work on CentOS8.


```
[scylla-test@artifacts-centos8-jenkins-db-node-b138bd73-0-1 ~]$ systemctl --user status scylla-server 
● scylla-server.service - Scylla Server
   Loaded: loaded (/home/scylla-test/.config/systemd/user/../../../scylladb/etc/systemd/scylla-server.service; enabled; vendor preset: enabled)
  Drop-In: /home/scylla-test/.config/systemd/user/scylla-server.service.d
           └─nonroot.conf
   Active: active (running) since Thu 2020-08-27 08:48:25 UTC; 23s ago
 Main PID: 49546 (scylla)
   Status: "starting view update backlog broker"
   CGroup: /user.slice/user-1050.slice/user@1050.service/scylla.slice/scylla-server.slice/scylla-server.service
           └─49546 /home/scylla-test/scylladb/bin/scylla --workdir /home/scylla-test/scylladb --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --n>

Aug 27 08:48:40 artifacts-centos8-jenkins-db-node-b138bd73-0-1 scylla[49546]:  [shard 0] storage_service - NORMAL: node is now in normal status
Aug 27 08:48:40 artifacts-centos8-jenkins-db-node-b138bd73-0-1 scylla[49546]:  [shard 0] cdc - No generation seen during startup.
Aug 27 08:48:40 artifacts-centos8-jenkins-db-node-b138bd73-0-1 scylla[49546]:  [shard 0] init - starting tracing
Aug 27 08:48:40 artifacts-centos8-jenkins-db-node-b138bd73-0-1 scylla[49546]:  [shard 0] init - SSTable data integrity checker is disabled.
Aug 27 08:48:40 artifacts-centos8-jenkins-db-node-b138bd73-0-1 scylla[49546]:  [shard 0] init - starting auth service
Aug 27 08:48:40 artifacts-centos8-jenkins-db-node-b138bd73-0-1 scylla[49546]:  [shard 0] init - starting batchlog manager
Aug 27 08:48:40 artifacts-centos8-jenkins-db-node-b138bd73-0-1 scylla[49546]:  [shard 0] init - starting load meter
Aug 27 08:48:40 artifacts-centos8-jenkins-db-node-b138bd73-0-1 scylla[49546]:  [shard 0] init - starting cf cache hit rate calculator
Aug 27 08:48:40 artifacts-centos8-jenkins-db-node-b138bd73-0-1 scylla[49546]:  [shard 0] init - starting view update backlog broker
Aug 27 08:48:40 artifacts-centos8-jenkins-db-node-b138bd73-0-1 scylla[49546]:  [shard 0] init - Waiting for gossip to settle before accepting client requests.>
[scylla-test@artifacts-centos8-jenkins-db-node-b138bd73-0-1 ~]$ journalctl --user -xe |grep -i scylla
No journal files were found.
[scylla-test@artifacts-centos8-jenkins-db-node-b138bd73-0-1 ~]$ journalctl --user -xe |wc -l
No journal files were found.
1
```

**Comment by penberg** [comment]
@amoskong Is `systemd`  version in Ubuntu 18.04 more up-to-date? I am not sure what we can do here, it's `systemd` functionality after all.

**Comment by slivne** [comment]
We need to document what he user can do 

So we need to know what works on Centos8 / Ubuntu18.04.

**Comment by avikivity** [comment]
We can give up on systemd --user integration. A real pity, since it saves a lot of work.

**Comment by slivne** [comment]
We have to provide an answer to the user how he can read the logs

**Comment by avikivity** [comment]
Apparently it's not possible with the systemd/journald in centos8. If that's the case (let's make sure with a fully updated centos8), then we should abandon the integration with systemd/journald and look for another alternative.

Or maybe we can modify the start command to redirected stdout/stderr to some file.

**Comment by amoskong** [comment]
systemd on CentOS8 is newer, I will try to downgrade it to 237.


```
scylla-test@artifacts-ubuntu1804-jenkins-db-node-cf37ce02-0-1:~$ systemd --version
systemd 237
+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid
```

```
[scylla-test@artifacts-centos8-jenkins-db-node-4f555251-0-1 ~]$ rpm -qa |grep systemd
systemd-pam-239-31.el8_2.2.x86_64
systemd-udev-239-31.el8_2.2.x86_64
rpm-plugin-systemd-inhibit-4.14.2-37.el8.x86_64
systemd-libs-239-31.el8_2.2.x86_64
systemd-239-31.el8_2.2.x86_64
```

**Comment by penberg** [comment]
@avikivity Let's first find out if this is a `systemd` bug before we throw away the integration work.

**Comment by amoskong** [comment]
I didn't find systemd-237 rpm for centos8.

```
[scylla-test@artifacts-centos8-jenkins-db-node-4f555251-0-1 ~]$ sudo yum list systemd --showduplicates
Last metadata expiration check: 0:05:23 ago on Mon 07 Sep 2020 01:43:12 AM UTC.
Installed Packages
systemd.x86_64                                                              239-31.el8_2.2                                                              @BaseOS
Available Packages
systemd.i686                                                                239-31.el8_2.2                                                              BaseOS
systemd.x86_64                                                              239-31.el8_2.2                                                              BaseOS
```


Failed to build v237, v239 on CentOS8, but successfully built latest master of systemd (https://github.com/systemd/systemd/commit/6743a1caf4037f03dc51a1277855018e4ab61957).
Then I can see scylla logs by `journalctl --user  -u scylla-server -f`

[scylla-test@artifacts-centos8-jenkins-db-node-4f555251-0-1 build]$ systemd-run --version
systemd 246 (246-561-g6743a1c)
+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 -ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified

### Build steps:

```
git clone https://github.com/systemd/systemd
sudo dnf builddep systemd
cd systemd/
meson build 
cd build/
sudo meson install
```

**Comment by avikivity** [comment]
Why downgrade? We want it to work on the standard install.

**Comment by amoskong** [comment]
> Why downgrade? We want it to work on the standard install.

I want to check if it works with a older & newer systemd, how do we insure it's a bug of systemd itself?

**Comment by avikivity** [comment]
You can look at systemd changelogs to see when the feature was introduced.

**Comment by penberg** [comment]
@amoskong @syuu1228 Any updates on this?

**Comment by syuu1228** [comment]
Tested this on my side.
I got following error when executing journalctl:
```
[vagrant@localhost unified]$ journalctl --user -xe
Hint: You are currently not seeing messages from the system.
      Users in the 'systemd-journal' group can see all messages. Pass -q to
      turn off this notice.
No journal files were opened due to insufficient permissions.
```
It looks like this one: https://serverfault.com/questions/806469/how-to-allow-a-user-to-use-journalctl-to-see-user-specific-systemd-service-logs
It says `However, this only works if the Storage directive of the [Journal] section of /etc/systemd/journald.conf is set to persistent (instead of auto or volatile)`, and default value of Storage is `auto`.
I changed the value to `Storage=persistent` then rebooted the machine, able to get user mode journal log:
```
[vagrant@localhost ~]$  journalctl --no-pager --user -u scylla-server.service
-- Logs begin at Wed 2020-09-16 05:20:15 UTC, end at Wed 2020-09-16 05:20:24 UTC. --
Sep 16 05:20:24 localhost.localdomain systemd[949]: Starting Scylla Server...
Sep 16 05:20:24 localhost.localdomain scylla[988]: Scylla version 666.development-0.20200912.413c7fc30 with build-id db4219425731b070ff5876ae4b07b3c5c79a11dc starting ...
Sep 16 05:20:24 localhost.localdomain scylla[988]: command used: "/home/vagrant/scylladb/bin/scylla --workdir /home/vagrant/scylladb --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix"
Sep 16 05:20:24 localhost.localdomain scylla[988]: parsed command line options: [workdir: /home/vagrant/scylladb, log-to-syslog: 1, log-to-stdout: 0, default-log-level: info, network-stack: posix]
Sep 16 05:20:24 localhost.localdomain scylla[988]: [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
Sep 16 05:20:24 localhost.localdomain scylla[988]: [shard 0] init - installing SIGHUP handler
Sep 16 05:20:24 localhost.localdomain scylla[988]: [shard 0] init - Scylla version 666.development-0.20200912.413c7fc30 with build-id db4219425731b070ff5876ae4b07b3c5c79a11dc starting ...
Sep 16 05:20:24 localhost.localdomain scylla[988]: [shard 0] init - NOFILE rlimit too low (recommended setting 200000, minimum setting 10000; refusing to start.
Sep 16 05:20:24 localhost.localdomain scylla[988]: [shard 0] init - Shutting down sighup
Sep 16 05:20:24 localhost.localdomain scylla[988]: [shard 0] init - Shutting down sighup was successful
Sep 16 05:20:24 localhost.localdomain scylla[988]: [shard 0] init - Startup failed: std::runtime_error (NOFILE rlimit too low)
Sep 16 05:20:24 localhost.localdomain systemd[949]: scylla-server.service: Main process exited, code=exited, status=1/FAILURE
Sep 16 05:20:24 localhost.localdomain systemd[949]: scylla-server.service: Failed with result 'exit-code'.
Sep 16 05:20:24 localhost.localdomain systemd[949]: Failed to start Scylla Server.
```

However, modifying the configuration file requires root privileges...
Maybe we need to logging to a file not stdout, or switch to supervisord, or wait for fix of systemd on RHEL8.

**Comment by syuu1228** [comment]
Ah, looks like I haven't applied systemd update. I need to try updated version too..

**Comment by syuu1228** [comment]
> Ah, looks like I haven't applied systemd update. I need to try updated version too..

Updated from systemd-239-13.el8.x86_64 to systemd-239-31.el8_2.2.x86_64, no difference

**Comment by avikivity** [comment]
I think it's a bug in systemd. Probably the permissions on /var/log/journal/xxx are created correctly if it's set as persistent and created incorrectly if it's set as auto. Please file a bug in systemd.

**Comment by penberg** [comment]
@syuu1228 Yeah, please open a ticket on systemd. Meanwhile, I think we can go ahead with a release by documenting the workaround. /cc @slivne

**Comment by penberg** [comment]
@avikivity @syuu1228 Isn't the problem here:

https://github.com/systemd/systemd/blob/master/src/journal/journald-server.c#L321

IOW, in the "persistent" mode, `systemd` will create the whole path (including parents), whereas in other modes, it will only attempt to create the leaf directory?

**Comment by penberg** [comment]
That is in `system_journal_open` this happens:

```c
                /* If in auto mode: first try to create the machine path, but not the prefix.
                 *
                 * If in persistent mode: create /var/log/journal and the machine path */

                if (s->storage == STORAGE_PERSISTENT)
                        (void) mkdir_parents(s->system_storage.path, 0755);

                (void) mkdir(s->system_storage.path, 0755);
```

**Comment by syuu1228** [comment]
It's never happen on Fedora, so I guess it's already fixed on recent release of systemd but haven't backported to RHEL8.

**Comment by syuu1228** [comment]
According to [man page of journald.conf](https://www.freedesktop.org/software/systemd/man/journald.conf.html), Storage will be "auto" when it's not specified, and "auto" mode means write log to /var/log/journal only if the directory exists, otherwise fallback to /run/log/journal.
After I created /var/log/journal and reboot, `journalctl --user -xe` just worked on CentOS8.

**Comment by syuu1228** [comment]
Tested on Vagrant VM image, CentOS8 does not have /var/log/journal by default, but Fedora 32 does have it by default.

Fedora 32:
```
[syuu@monster vagrant_f32]$ ls -la /var/log/journal/
total 16
drwxr-sr-x+  3 root systemd-journal   46 Jun 22 23:51 .
drwxr-xr-x. 13 root root            4096 Sep 19 00:01 ..
drwxr-sr-x+  2 root systemd-journal 8192 Sep 19 19:54 0b8c00e936bd479ca9c03c9aaab41e94
[syuu@monster vagrant_f32]$ ls -la /run/log/journal
total 0
drwxr-sr-x+ 2 root systemd-journal 40 Sep 19 19:53 .
drwxr-xr-x. 3 root root            60 Sep 19 19:53 ..
```

CentOS8:
```
[vagrant@localhost ~]$ ls -la /var/log/journal
ls: cannot access '/var/log/journal': No such file or directory
[vagrant@localhost ~]$ sudo ls -la /run/log/journal
total 0
drwxr-sr-x. 4 root systemd-journal 80 Sep 19 11:41 .
drwxr-xr-x. 3 root root            60 Sep 19 11:41 ..
drwxr-x---. 2 root root            60 Sep 19 11:41 564f575fc2bd4d21b6bf7f8f4f8f3ac9
drwxr-s---+ 2 root systemd-journal 60 Sep 19 11:41 5f740e900a9d430cadaf92a906d86cad
```

**Comment by syuu1228** [comment]
Seems like Fedora 32 systemd .rpm creating /var/log/journal, so the difference may comes from .rpm not systemd itself.

**Comment by penberg** [comment]
@avikivity Should this be reported to bugs.centos.org or somewhere else then?

**Comment by avikivity** [comment]
yes

**Comment by syuu1228** [comment]
Reported https://bugs.centos.org/view.php?id=17773

**Comment by syuu1228** [comment]
We may need a workaround for this, it should be logging to a file instead of journal.
It can be done by `StandardOutput=file:/path/to/logfile`, but it will be overwrite when restarting the service, we need some hack to save current log file on ExecStartPre, something like this:
`ExecStartPre=/bin/bash -c 'mv /var/log/my/logs.log /var/log/my/$$(date +%%T)-logs.log`
referenced: https://stackoverflow.com/questions/37585758/how-to-redirect-output-of-systemd-service-to-a-file
(There is "append mode" but not available on CentOS8 systemd)

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
