### ISSUE TITLE
nodetool -h parameter usage issue

### ISSUE THREAD

**Issue by yangly0815** [scylladb/scylla#7137]
*Installation details*
Scylla version (or git commit hash): 4.1.1
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): RHEL

When i use nodetool -h parameter to get remote host's information, it dosen't work expectly.
```
[root@node01 ~]# netstat -ntlp | grep 7199
tcp6       0      0 192.168.75.129:7199     :::*                    LISTEN      22205/scylla-jmx
[root@node01 ~]#
[root@node01 ~]# nodetool -h 192.168.75.129 info
nodetool: Failed to connect to '192.168.75.129:7199' - ConnectException: 'Connection refused (Connection refused)'.
[root@node01 ~]#

```

**Comment by amnonh** [comment]
when you start scylla-jmx you should  use the `-r` flag to enable remote jmx connection

**Comment by slivne** [comment]
@yangly0815 - I  am closing this issue Amnon provided an answer, if you still need help please repost here and we can reopen / answer questions.
