### ISSUE TITLE
"nodetool repair" options are being outright ignored

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#714]
In our repair code  (repair/repair.cc), we carefully obey some options (like primary-range and ranges), and complain about not supporting others. But when a user actually goes and uses one of the options of "nodetool repair" (-par, -pr, -hosts, etc.), they are all ignored - only the keyspace parameter is not ignored...

The problem is in scylla-jmx, src/main/java/org/apache/cassandra/service/StorageService.java

It has two relevant functions, repairAsync() and forceRepairAsync(), but both are buggy:

1. repairAsync() builds the "options" parameter in queryParams, and then goes and forget to pass this queryParams to the call to c.postInt() :-)

2. forceRepairAsync() passes an empty option map to repairAsync() instead of building a map according to its parameters.

Both bugs need to be fixed for the options to be passed to the repair.

**Comment by penberg** [comment]
First part of the issue is fixed by https://github.com/scylladb/scylla-jmx/commit/9b03fa1074d387953b7ca4317f465c8cb5c5757c.

**Comment by nyh** [comment]
Fixed by scylladb/scylla-jmx@69c691366833343dad66d919bcdec5f45c7a13ca, scylladb/scylla-jmx@f8b4dfed38eea6facb65d1b8a6f6e4c136a906ab and also by 7247f055df1810e88fbf279ba6b575f9f87b676a
