### ISSUE TITLE
SSTables in CDC log tables are never expired

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#7141]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

SSTables in CDC log tables are supposed to live 24 hours, but they're never expired because we're not setting the default TTL of CDC tables properly, which defaults to 24 hours. We need to set the default TTL when building schema for CDC log tables.

**Comment by raphaelsc** [comment]
I will cook a patch soon

**Comment by haaawk** [comment]
This is by design @raphaelsc. We set ttls for each inserted row at the time it inserted.

default ttl works only on CQL level and not on internal APIs

**Comment by haaawk** [comment]
https://github.com/scylladb/scylla/issues/5688

**Comment by haaawk** [comment]
And a fix -> https://github.com/scylladb/scylla/pull/5745

**Comment by raphaelsc** [comment]
Thanks a lot for the explanation @haaawk! closing this issue then....
