### ISSUE TITLE
Set gossiper scheduling class explicitly

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#7154]
*Installation details*
Scylla version: 58104d17e08a94b5c339da370cd2bf9abb276209

*Description*
We are not initializing the scheduling class of the gossiper timer explicitly. In this case the scheduling group ID is default-initialized to 0 which happens to come out the same as the ID of the "maintenance" scheduling group *because* we initialize this class the first in the main.cc: https://github.com/scylladb/scylla/blob/master/main.cc#L587 and https://github.com/scylladb/scylla/blob/master/gms/gossiper.cc#L140 - this is very fragile and we'd rather initialize the gossiper scheduling class explicitly in order to avoid surprises if/when scheduling groups numbers change.

**Comment by vladzcloudius** [comment]
@asias @avikivity FYI

**Comment by denesb** [comment]
@vladzcloudius scheduling group id 0 is *not* the maintenance scheduling group, it's the default (main) scheduling group.

**Comment by vladzcloudius** [comment]
> @vladzcloudius scheduling group id 0 is _not_ the maintenance scheduling group, it's the default (main) scheduling group.

Right. I missed that.
So, who are the "noisy neighbours": Prometheus and Co.?

I still think that Gossip deserves a separate scheduling group because its a vital service.
It's actually the most vital service in the system because it defines which replica is alive and which isn't, and therefore it should be the most robust one.

**Comment by asias** [comment]
> > @vladzcloudius scheduling group id 0 is _not_ the maintenance scheduling group, it's the default (main) scheduling group.
> 
> Right, @denesb. I missed that.
> So, who are the "noisy neighbours": Prometheus and Co.?
> 
> I still think that Gossip deserves a separate scheduling group because its a vital service.
> It's actually the most vital service in the system because it defines which replica is alive and which isn't, and therefore it should be the most robust one.

Gossip is tolerant of not updating gossip hearbeat at the level of ~10 seconds. Nothing except bugs should block gossip task for that long even if it is running inside a default scheduling group. 

@denesb Do you remember what is the share of the default group?

**Comment by dorlaor** [comment]
We did see cases where a loaded shard 0 ended up as a down node because of
the load.
The solution is either to keep rotating the gossip handler or to increase
its priority (which
is simpler)

**Comment by denesb** [comment]
> > > @vladzcloudius scheduling group id 0 is _not_ the maintenance scheduling group, it's the default (main) scheduling group.
> > 
> > 
> > Right, @denesb. I missed that.
> > So, who are the "noisy neighbours": Prometheus and Co.?
> > I still think that Gossip deserves a separate scheduling group because its a vital service.
> > It's actually the most vital service in the system because it defines which replica is alive and which isn't, and therefore it should be the most robust one.
> 
> Gossip is tolerant of not updating gossip hearbeat at the level of ~10 seconds. Nothing except bugs should block gossip task for that long even if it is running inside a default scheduling group.
> 
> @denesb Do you remember what is the share of the default group?

This is from a random coredump:
```
(gdb) scylla task-queues 
   id name                             shares  tasks
   00 "main"                           1000.00 0
   01 "atexit"                         1000.00 0
 A 02 "streaming"                       200.00 1
   03 "compaction"                       50.09 0
   04 "mem_compaction"                 1000.00 0
*A 05 "statement"                      1000.00 1063
   06 "memtable"                          1.00 0
   07 "memtable_to_cache"               200.00 0
```

**Comment by asias** [comment]
So, gossip is already running with the highest 1000 shares under main scheduling group. It is as high as statement. I think we should not increase to be higher than "statement" class.

**Comment by avikivity** [comment]
Yes, if gossip is running in main, not streaming, then it's fine.

**Comment by vladzcloudius** [comment]
It's not only about its priority but also about other things that run with the gossiper in the same group.

Ideally gossiper would run in its exclusive scheduling group.

**Comment by avikivity** [comment]
Nothing else should run in the main group, so it already happens.

**Comment by slivne** [comment]
@avikivity can I close this ?

**Comment by avikivity** [comment]
> > @vladzcloudius scheduling group id 0 is _not_ the maintenance scheduling group, it's the default (main) scheduling group.
> 
> Right, @denesb. I missed that.
> So, who are the "noisy neighbours": Prometheus and Co.?

Prometheus is in the maintenance group.

**Comment by avikivity** [comment]
Closing as invalid.

**Comment by nyh** [comment]
> Nothing else should run in the main group, so it already happens.

There is one small benefit of adding a special scheduling group for the gossiper: Today, every time we see in some benchmark too many tasks in the main group, we immediately suspect the gossiper. If the gossiper had its own group, if we would still see a lot of tasks in the main group we would know we have some sort of bug somewhere, and stop suspecting the gossiper.

**Comment by avikivity** [comment]
That's a valid point. We may need to increase the maximum number of scheduling groups, if we keep adding more.

**Comment by asias** [comment]
@avikivity in the past, I had a patch to run code with with_scheduling_group explicitly, you wanted to avoid it and use the inherited scheduling group. I think it is better to use with_scheduling_group as the scheduling is getting more and more complicated. It is hard to track what is inherited. 

Per you comments here: https://github.com/scylladb/scylla/pull/7281#issuecomment-699611701.

If we run with with_scheduling_group explicitly within storage_service::start_gossiping, there is no need to worry about how calls start_gossiping. 

It is also easier to figure out what scheduling group is using when looking at the code.

**Comment by slivne** [comment]
We have plans to add support for hierarchical scheduling groups - this should allow us to have the gossiper in the hierarchy of main. But its not there yet - @avikivity wwhat do you want todo with this issue - @nyh is right that we suspect gossiper when ever we see something running in main (and at times its a bug ...)

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please backport also to 4.3

**Comment by bhalevy** [comment]
@asias are there any special considerations for backporting to 4.3?

**Comment by asias** [comment]
> 
> 
> @asias are there any special considerations for backporting to 4.3?

No. It is a easy backport.

**Comment by avikivity** [comment]
Well, there is the problem with users who have too many workload prioritization service levels running out.

**Comment by avikivity** [comment]
> @scylladb/scylla-maint please backport also to 4.3

Why?

**Comment by asias** [comment]
> 
> 
> > @scylladb/scylla-maint please backport also to 4.3
> 
> Why?

We saw in the field nodes are marked as down by gossip under high load, other tasks leaked into the main class competing with gossip. The backport should mitigate the problem.

**Comment by bhalevy** [comment]
@avikivity please see Asias' response above.

**Comment by avikivity** [comment]
Enterprise issues should not be discussed here. Do we know that 4.3 has the task leak into main?

**Comment by bhalevy** [comment]
> Enterprise issues should not be discussed here. Do we know that 4.3 has the task leak into main?

@avikivity yes, according to https://github.com/scylladb/scylla-enterprise/issues/1851#issuecomment-901573091

**Comment by asias** [comment]
> 
> 
> Enterprise issues should not be discussed here. Do we know that 4.3 has the task leak into main?

I am only mention it since you asked the motivation for the backport.  I think we do have such leaks in 4.3.  We have  a patch 268fa9d9fe10db5e3d0f2ef8518806467a127439 (main: Lower shares for main scheduling group) as a workaround for the leak, which is present in 4.5 and master.
