### ISSUE TITLE
streaming/repair task quote violations and overload can disturb gossip

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#7155]
*Installation details*
Scylla version: 58104d17e08a94b5c339da370cd2bf9abb276209

*Description*
Today we run a gossiper timer in a "streaming" ("maintenance") scheduling class (ref https://github.com/scylladb/scylla/issues/7154) however this makes vital and usually very short gossiper tasks compete for CPU with a low priority heavy and intensive tasks like streaming and hints.

This may cause unnecessary delays and even failures (timeouts) while executing gossiping tasks like sending an ECHO message. This in line may cause other nodes erroneously conclude that such a node(s) is DOWN while they are simply have a lot of low priority work to do (e.g. send a lot of hints or stream a lot of data) and thereby cause a cluster outage (if multiple nodes become overloaded in the streaming class).

It makes sense to run gossiper tasks in a separate scheduling group with a high(er) priority in order to ensure the consistent topology state distribution.

**Comment by vladzcloudius** [comment]
@avikivity @asias @slivne @eliransin @amihayday FYI

**Comment by asias** [comment]
Gossip runs inside default scheduling group while streaming/repair runs inside the streaming (with share of 200). Gossip does not run inside streaming group.

**Comment by avikivity** [comment]
Closing as invalid.
