### ISSUE TITLE
Alternator: Stream sequence number uses wrong format

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#7158]
The sequence number range start and end is specified as being numeric only. Scylla alternator incorrectly uses stringified UUID:s here. This breaks AWS kinesis (Java adapter).

**Comment by nyh** [comment]
Interesting. You're right. The documentation for `SequenceNumber`, https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_StreamRecord.html, only says:

> The sequence number of the stream record. Type: String. Length Constraints: Minimum length of 21. Maximum length of 40.

But the documentation for `SequenceNumberRange` indeed clarifies that it is really a umber (but in string format!) - https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_SequenceNumberRange.html
>  StartingSequenceNumber: The first sequence number for the stream records contained within a shard. **String contains numeric characters only.** Type: String.  Length Constraints: Minimum length of 21. Maximum length of 40.

**Comment by nyh** [comment]
Alternator Streams was not yet in 4.2, so no need to backport.
