### ISSUE TITLE
On disk error stop the node from receiving additional requests - leave it running for JMX probing

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#717]
On Commitlog / SSTable disk error support option 

"stop"

Shut down gossip and Thrif and CQLt, leaving the node effectively dead, but available for inspection using JMX.

**Comment by slivne** [comment]
#705 #706 #707 #709 #710 # 711 #712

**Comment by benoit-canet** [comment]
Shlomi: Do I code this as an option or as the default ?

**Comment by slivne** [comment]
@benoit-canet does this mean that we can close all the specific bugs ?

**Comment by benoit-canet** [comment]
The patch is still not merged.

**Comment by benoit-canet** [comment]
@avikivity Is it ok to derive "file" in scylla ? This way we would have a way to systematically catch the
exception and act upon it ? (I fear that adding try/except clause all over the place streams are used in scylla is error prone)

**Comment by benoit-canet** [comment]
@avikivity: I finally found a method with does not involve shiftting huge code blocks to the right just to handle the exceptions. Thanks for letting me searching by myself ;)

**Comment by benoit-canet** [comment]
Closed by:
1fb9a48ac5fe332a948bd006d9c64aa11916a77a
3b1d3d977d50204400fc6277390a1740e22d34ce

Tested a day of two with CharybdeFS. I am pretty confident it's ok.
