### ISSUE TITLE
cas related failures in dtest after "lwt: for each statement in cas_request provide a row in CAS result set"

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7176]
There are a bunch of regressions in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/598
that seem to stem from bcdcf06ec7da06210a2ec66783e4ab2c596bc44c.

I didn't try to reproduce all but the ones I tried passed at bc77939ada60c2bfbdb42f9ed93df8b9fbfd3689

For example, https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/598/testReport/cql_additional_tests/TestCQL/static_columns_cas_test/
```
Expected [[False, 0, 'k1', 2]] from 
                     BEGIN BATCH
                       UPDATE test SET v='foobar' WHERE id=0 AND k='k1';
                       UPDATE test SET v='barfoo' WHERE id=0 AND k='k2';
                       UPDATE test SET version=3 WHERE id=0 IF version=1;
                     APPLY BATCH
                   , but got [[False, 0, 'k1', 2], [False, None, None, None], [False, 0, 'k1', 2]]
```

And similar failures in other cql tests:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/598/testReport/cql_additional_tests/TestLWTWithCQL/test_batch_insert_delete_same_row/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/598/testReport/cql_additional_tests/TestLWTWithCQL/test_batch_insert_new_delete_old_row/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/598/testReport/cql_additional_tests/TestLWTWithCQL/test_batch_update_insert_same_row/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/598/testReport/cql_additional_tests/TestLWTWithCQL/test_batch_delete_insert_same_row/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/598/testReport/cql_additional_tests/TestLWTWithCQL/test_conditional_deletes_on_static_columns_with_null_values_batch/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/598/testReport/cql_additional_tests/TestLWTWithCQL/test_conditional_updates_on_static_columns_with_null_values_batch/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/598/testReport/cql_additional_tests/TestLWTWithCQL/test_lwt_with_static_columns/

similar to the cql test errors above:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/598/testReport/deletion_test/RangeDeletionTester/delete_by_1ck_range_conditional_batch_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/598/testReport/deletion_test/RangeDeletionTester_with_SizeTieredCompactionStrategy/delete_by_1ck_range_conditional_batch_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/598/testReport/deletion_test/RangeDeletionTester_with_TimeWindowCompactionStrategy/delete_by_1ck_range_conditional_batch_test/

Also, https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/598/testReport/deletion_test/RangeDeletionTester/delete_by_1ck_range_conditional_batch_update_test/
```
'<' not supported between instances of 'int' and 'NoneType'
```

similar:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/598/testReport/deletion_test/RangeDeletionTester_with_SizeTieredCompactionStrategy/delete_by_1ck_range_conditional_batch_update_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/598/testReport/deletion_test/RangeDeletionTester_with_TimeWindowCompactionStrategy/delete_by_1ck_range_conditional_batch_update_test/

**Comment by bhalevy** [comment]
Cc @kostja

**Comment by slivne** [comment]
@kostja / @ManManson please fix - fallout form a change

**Comment by ManManson** [comment]
> @kostja / @ManManson please fix - fallout form a change 

@slivne Yes, I'm on it.
