### ISSUE TITLE
Possible priority inversion between hints and normal write in storage_proxy

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla#7177]
Hints writes are handled by storage_proxy in the exact same way
regular writes are, which in turn means that the same smp service
group is used for both. The problem is that it can lead to a priority
inversion where writes of the lower priority  kind occupies a lot of
the semaphores units making the higher priority writes wait for an
empty slot.
The affected queries and hints are those which originated in a non
shard aware clients since only then they will be queued on the cross
shard semaphore a.k.a smp_service_group

**Comment by slivne** [comment]
@avikivity ping please consider backport to 4.2

**Comment by avikivity** [comment]
@eliransin I need help with the backport. It conflicts with 5ff5df1afd3b5de54f110d855a31fd456f920bb4 in subtle ways.

**Comment by eliransin** [comment]
@avikivity  on it.

**Comment by eliransin** [comment]
@avikivity I read the commit you are referring to and 5ff5df1 , unless I misunderstood, this is not a conflict but a dependency.
The commit itself is king of a semantic nop as it is only a setup for future commits, it only move the "hardcoded" sync::no up the call stack but doesn't change it.
I think we should backport this as a dependency and then backport the fix on top of it. 
The cherry pick is clean that way and I am now going to test compilation and unit tests in dev mode and will update about the result.

**Comment by avikivity** [comment]
Yes, that one. I'm wary of backporting "supposed to be nop" commits that later turn out not to be nops. But there is also risk in doing branch-specific work that ends up being undertested. So if backporting that commit works, we can do it.

**Comment by eliransin** [comment]
@avikivity compilation and unit tests passes.
> I'm wary of backporting "supposed to be nop" commits that later turn out not to be nops.

I guess that I can't argue with experience :slightly_smiling_face: , I double checked it just now and it looks like a real nop.
The commit message claims it to be the case too (implicitly).

**Comment by avikivity** [comment]
Ok. I'll backport the dependency and we'll see.

**Comment by avikivity** [comment]
Backported to 4.2. Will revisit later for older branches.

**Comment by avikivity** [comment]
Backported to 4.1.

@eliransin please review my backport (lots of conflicts due to some tracing being added in 4.2 and not present in 4.1).
@roydahan please test 4.1 with SCT with materialized view, and report the results here.

**Comment by roydahan** [comment]
@eliransin I need your help with designing the test and how to see the effect of the issue/solution.
