### ISSUE TITLE
scylla_setup doesn't support to skip install of hugepages or libhugetlbfs-bin package

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#7182]
*Installation details*
Scylla version (or git commit hash):  latest master (b3f00685ec6c04c67fc9db809fbb63cb1696881e)
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04

hugepages or libhugetlbfs-bin package is installed for Ubuntu 20.04 and later.
scylla_setup should support to disable it, we have some users that run scylla_setup without network.

![image](https://user-images.githubusercontent.com/309708/92348315-62075680-f105-11ea-93a0-5c97da1a451c.png)

@slivne @penberg

**Comment by penberg** [comment]
Yeah, but I wonder how this should be fixed. Turn the installation into a logging "please install hugepage package"? Or add an `--offline` command line option to `scylla_setup`?

@slivne @avikivity thoughts?

**Comment by avikivity** [comment]
I don't think we even need it, apart from dpdk setups.

**Comment by avikivity** [comment]
```
/.
/usr
/usr/bin
/usr/bin/hugeadm
/usr/bin/hugectl
/usr/bin/hugeedit
/usr/bin/ld.hugetlbfs
/usr/bin/pagesize
```

**Comment by avikivity** [comment]
We still use it:

```
    elif mode == 'dpdk':
        ethpciid = cfg.get('ETHPCIID')
        nr_hugepages = cfg.get('NR_HUGEPAGES')
        run('modprobe uio')
        run('modprobe uio_pci_generic')
        run('/opt/scylladb/scripts/dpdk-devbind.py --force --bind=uio_pci_generic {ETHPCIID}'.format(ETHPCIID=ethpciid))
        for n in glob.glob('/sys/devices/system/node/node?'):
            with open('{n}/hugepages/hugepages-2048kB/nr_hugepages'.format(n=n), 'w') as f:
                f.write(nr_hugepages)
        if dist_name() == 'Ubuntu':
            run('hugeadm --create-mounts')
```

But only in dpdk mode. So it should be made optional.

**Comment by syuu1228** [comment]
@avikivity Just drop them or ask "Do you want to install required packages for DPDK mode?" or something?

**Comment by slivne** [comment]
@avikivity ping

I am marking this as low for now

**Comment by syuu1228** [comment]
Added skipping installation on offline mode at https://github.com/scylladb/scylla/pull/7224

**Comment by avikivity** [comment]
@syuu1228 I think we can drop it. Anyone using DPDK mode can figure it out.

**Comment by syuu1228** [comment]
@avikivity New PR created to drop this #7233

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
