### ISSUE TITLE
Unable to disable row cache

### ISSUE THREAD

**Issue by alienth** [scylladb/scylla#7195]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.1.4-0.20200809.76f4
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu

I'm apparently unable to either disable the row cache on existing CFs or create a new CF with it disabled:

```
cqlsh:test> create table test (key ascii, column1 text, value blob, primary key (key, column1)) with compact storage AND CLUSTERING ORDER BY (column1 ASC) and caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'};

cqlsh:test> describe table test;

CREATE TABLE test.test (
...
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
```

```
cqlsh:test> alter table querycache with caching = {'keys': 'ALL', 'rows_per_partition': 'NONE'};
cqlsh:test> describe table querycache;

CREATE TABLE test.querycache (
...
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
```

Scylla logs show no errors when applying the schema change.

**Comment by haaawk** [comment]
To disable cache in Scylla you need to use `WITH caching = {'enabled':false}"`

**Comment by alienth** [comment]
Hi @haaawk ,

I'd like to keep key cache for this CF, but disable row cache. Is that not possible?

Thanks,
Jason

**Comment by haaawk** [comment]
Scylla does not have a key cache at the moment so it is not possible.
