### ISSUE TITLE
Segfault in evaluating multi-column restrictions

### ISSUE THREAD

**Issue by dekimir** [scylladb/scylla#7198]
There was a typo in 62c34a9085e021c920e7f95e6cbcec537ee5742e resulting in a segfault for queries that
- restrict a partition-key column with equality operator, and
- use multi-column restriction, and
- require ALLOW FILTERING

For example: `SELECT pk1 FROM tbl WHERE pk1=5 AND (ck1,ck2)>(10,20) ALLOW FILTERING`

Based on that commit's tags, Scylla versions 4.0, 4.1, and 4.2 are affected.

**Comment by avikivity** [comment]
Backported to 4.0, 4.1, 4.2.
