### ISSUE TITLE
Compaction - rate limiting

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#72]
there is a config value compaction_throughput_mb_per_sec

there is also a nodetool operation setcompactionthroughput

Add support for limiting the amount of disk bandwidth and/or cpu time used by a compaction, and/or all concurrent compactions. Start also to think about the latency that the compaction process adds (how long each compaction continuation is, how much it adds to the disk queue, etc.) and how we can measure and/or limit it.

**Comment by tzach** [comment]
@avikivity I'm assuming IO prioritization will help this issue, making the hard rate limit redundant.
Is this the case?

**Comment by avikivity** [comment]
It's not enough by itself.  Once we have an I/O scheduler we'll need to raise compaction's io priority if it can't keep up, or lower it if it runs too fast.  But we won't need the hard limit.

**Comment by slivne** [comment]
Duplicate with #176

**Comment by tzach** [comment]
@slivne I closed #176 as Scylla handles this kind of issue with IO scheduler, not configuration.
If you agree please close this as well.

**Comment by glommer** [comment]
On Wed, Mar 23, 2016 at 9:53 AM, Tzach Livyatan <notifications@github.com>
wrote:

> @slivne <https://github.com/slivne> I closed #176
> <https://github.com/scylladb/scylla/issues/176> as Scylla handles this
> kind of issue with IO scheduler, not configuration.
> If you agree please close this as well.
>

Please note that we still may have the problem of excessive processor-bound
continuations. It would be advisable to test some compaction scenarios to
see how much they are affecting us. But the disk part is certainly ok by
now.

**Comment by dorlaor** [comment]
We're about to have the cpu scheduler to control it automatically. Closing
