### ISSUE TITLE
nodetool cfhistograms returning 0 Partition Size and Cell Count

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#720]
scylla

```
$ nodetool cfhistograms test users
test/users histograms
Percentile  SSTables     Write Latency      Read Latency    Partition Size        Cell Count
                              (micros)          (micros)           (bytes)                  
50%             0.00              7.00              0.00                 0                 0
75%             0.00             10.00              0.00                 0                 0
95%             0.00             10.00              0.00                 0                 0
98%             0.00             10.00              0.00                 0                 0
99%             0.00             10.00              0.00                 0                 0
Min             0.00              7.00              0.00                 0                 0
Max             0.00             10.00              0.00                 0                 0
```

cassandra
_notice the no SSTable warning_

```
nodetool cfhistograms test users
No SSTables exists, unable to calculate 'Partition Size' and 'Cell Count' percentiles
test/users histograms
Percentile  SSTables     Write Latency      Read Latency    Partition Size        Cell Count
                              (micros)          (micros)           (bytes)                  
50%             0.00             42.00              0.00               NaN               NaN
75%             0.00            215.00              0.00               NaN               NaN
95%             0.00            215.00              0.00               NaN               NaN
98%             0.00            215.00              0.00               NaN               NaN
99%             0.00            215.00              0.00               NaN               NaN
Min             0.00             30.00              0.00               NaN               NaN
Max             0.00            215.00              0.00               NaN               NaN
```

**Comment by derailed** [comment]
Hi, 
   Any updates on this issue? Running nodetool version 2.1.13 and getting same error No SSTables exists. Useless to say these metrics are key to see how a c7a cluster is behaving. Any other workaround to make this work for the rev? 

Thanks!!

**Comment by tzach** [comment]
@derailed what Scylla version are you using?

**Comment by amnonh** [comment]
@tzach this is taken from the latest Master:

./bin/nodetool -p 7100 cfhistograms keyspace1 standard1
keyspace1/standard1 histograms
Percentile  SSTables     Write Latency      Read Latency    Partition Size        Cell Count
                              (micros)          (micros)           (bytes)                  
50%             0.00             12.00            770.00               310                 5
75%             0.00             12.00           1109.00               310                 5
95%             0.00             17.00           2759.00               310                 5
98%             0.00             86.00           4768.00               310                 5
99%             0.00            215.00           8239.00               310                 5
Min             0.00              3.00              6.00               259                 5
Max             0.00          14237.00          20501.00               310                 5


Can we close it?

**Comment by slivne** [comment]
@tzach this should be fixed can you please test and close

**Comment by tzach** [comment]
tested with 1.4.1 and the problem was solved.
