### ISSUE TITLE
Node's bootstrap process is too sensitive to networking problems 

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#721]
scylla HEAD: `827a4d00106415e80d9d70395db0d60a2dcc366c`
seastar HEAD: `8b2171e`
setup: `jepsen AMI running on c3.8xlarge instance`

Nodes seem to be too sensitive to networking problems during bootstrap phase. Tests like `lein test :only cassandra.collections.map-test/cql-map-isolate-node-bootstrap` and `lein test :only cassandra.collections.map-test/cql-map-bridge-bootstrap` always end up with at least one Node failing to bootstrap with the following message in the log:
```
DEBUG [shard 0] range_streamer - get_all_ranges_with_strict_sources_for ks=jepsen_keyspace
Exiting on unhandled exception of type 'std::runtime_error': A node required to move the data consistently is down (192.168.122.13).  If you wish to move the data from a potentially inconsistent replica, restart the node with -Dcassandra.
consistent.rangemovement=false
INFO  [shard 0] compaction_manager - compaction task handler stopped due to shutdown
``` 

It seems that we need a similar treatment for failures in the bootstrap stage like we do in the decommission stage.

**Comment by tzach** [comment]
Maybe be related to [phi_convict_threshold](https://docs.datastax.com/en/cassandra/2.1/cassandra/configuration/configCassandra_yaml_r.html?scroll=reference_ds_qfg_n1r_1k__phi_convict_threshold) ?

**Comment by vladzcloudius** [comment]
On 12/28/2015 06:22 PM, Tzach Livyatan wrote:
>
> Maybe be related to phi_convict_threshold 
> <https://docs.datastax.com/en/cassandra/2.1/cassandra/configuration/configCassandra_yaml_r.html?scroll=reference_ds_qfg_n1r_1k__phi_convict_threshold> 
> ?
>

It's configured to a value 8, which is a default value and the same 
value is used for cassandra (jepsen) testing but still we seem to be 
more sensitive.
Or maybe u mean that "it is related" because we ignore it - then u may 
be right... ;)

**Comment by slivne** [comment]
@asias do we support the phi_convict_threshold ?

**Comment by asias** [comment]
Yes, we support phi_convict_threshold.

**Comment by tzach** [comment]
> Or maybe u mean that "it is related" because we ignore it - then u may
   be right... ;)

From my reading of the code phi_convict_threshold  is not ignored.

**Comment by asias** [comment]
On Mon, Jan 11, 2016 at 4:27 PM, Tzach Livyatan <notifications@github.com>
wrote:

> Or maybe u mean that "it is related" because we ignore it - then u may
> be right... ;)
>
> From my reading of the code phi_convict_threshold is not ignored.
>

No, it is not. If you specify a non-default phi_convict_threshhold it will
take effects.

—
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/721#issuecomment-170462537>.
>



-- 
Asias

**Comment by vladzcloudius** [comment]
On 01/11/2016 10:29 AM, Asias He wrote:
> On Mon, Jan 11, 2016 at 4:27 PM, Tzach Livyatan <notifications@github.com>
> wrote:
>
> > Or maybe u mean that "it is related" because we ignore it - then u may
> > be right... ;)
> >
> > From my reading of the code phi_convict_threshold is not ignored.
> >
>
> No, it is not. If you specify a non-default phi_convict_threshhold it will
> take effects.

And if we specify a default phi_convict_threshold (8)? Will it be 
ignored then?

**Comment by asias** [comment]
On Jan 11, 2016 4:51 PM, "vladzcloudius" <notifications@github.com> wrote:
>
>
>
> On 01/11/2016 10:29 AM, Asias He wrote:
> > On Mon, Jan 11, 2016 at 4:27 PM, Tzach Livyatan <
notifications@github.com>
> > wrote:
> >
> > > Or maybe u mean that "it is related" because we ignore it - then u may
> > > be right... ;)
> > >
> > > From my reading of the code phi_convict_threshold is not ignored.
> > >
> >
> > No, it is not. If you specify a non-default phi_convict_threshhold it
will
> > take effects.
>
> And if we specify a default phi_convict_threshold (8)? Will it be
> ignored then?

No. It will be set to 8.

**Comment by slivne** [comment]
@asias, @vladzcloudius any update on this

**Comment by vladzcloudius** [comment]
On 02/04/2016 11:35 AM, slivne wrote:
>
> @asias <https://github.com/asias>, @vladzcloudius 
> <https://github.com/vladzcloudius> any update on this
>

Nothing is going on on my side.

**Comment by slivne** [comment]
@vladzcloudius in Jepsen are there other tests for unstable network in other stages that we do pass - I want to understand if scylla works well in an unstable network post bootstrap - and only in bootstrap we have an issue.

**Comment by vladzcloudius** [comment]
On 02/24/2016 01:10 PM, slivne wrote:
>
> @vladzcloudius <https://github.com/vladzcloudius> in Jepsen are there 
> other tests for unstable network in other stages that we do pass - I 
> want to understand if scylla works well in an unstable network post 
> bootstrap - and only in bootstrap we have an issue.
>

@asias In addition to bootstrap tests jepsen has decommission and crash 
(kill -9 and then start the node again) modes and there are a few 
combinations of these, e.g. bootstrap + crash.

I can't tell how are we doing in any of them right now since I haven't 
run the whole suite for a long time.

**Comment by slivne** [comment]
@asias can you prioritize this on your queue - we do see some issues in networking and it seems that we need to be tolerant - so if we are not lets work on making scylla more tolerant

**Comment by asias** [comment]
On Mon, Mar 7, 2016 at 10:14 PM, slivne <notifications@github.com> wrote:

> @asias <https://github.com/asias> can you prioritize this on your queue -
> we do see some issues in networking and it seems that we need to be
> tolerant - so if we are not lets work on making scylla more tolerant
>

I am not sure what the "more tolerant" means here and what we could do. The
behavior of the gossip and failure detector is the same as C*.


> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/721#issuecomment-193263291>.
>



-- 
Asias

**Comment by slivne** [comment]
Does cassandra fail on this tests - if not it does something different it
may not be in Gossip/Failure it may be in messaging service / rpc

If the "robustness" needs to go into a different level lets find out what
and then you may code it or someone else

**Comment by vladzcloudius** [comment]
@asias @slivne Let's first see that the problem is still reproducible with the latest master. Shlomi, pls., assign it to me and I'll check this today or tomorrow.

**Comment by vladzcloudius** [comment]
@asias @slivne 
In regard to isolate-node test: the first bootstrapping node failed after 5 GossipEchoMsg failed during 5 seconds:
```
grep timeout /var/lib/scylla/system.log
WARN  2016-03-09 09:42:49,381 [shard 0] gossip - Fail to send EchoMessage to 192.168.122.11:0: rpc::timeout_error (rpc call timed out)
WARN  2016-03-09 09:42:50,381 [shard 0] gossip - Fail to send EchoMessage to 192.168.122.11:0: rpc::timeout_error (rpc call timed out)
WARN  2016-03-09 09:42:51,381 [shard 0] gossip - Fail to send EchoMessage to 192.168.122.11:0: rpc::timeout_error (rpc call timed out)
WARN  2016-03-09 09:42:52,381 [shard 0] gossip - Fail to send EchoMessage to 192.168.122.11:0: rpc::timeout_error (rpc call timed out)
WARN  2016-03-09 09:42:54,445 [shard 0] gossip - Fail to send EchoMessage to 192.168.122.11:0: rpc::timeout_error (rpc call timed out)```

**Comment by vladzcloudius** [comment]
Continuing the above: the second bootstrapping node in the same test mentioned above has failed with even more strange symptoms: there weren't any timed-out messages, the gossiper has just declared all other 3 cluster nodes as DOWN and failed the JOINING:

```
INFO  2016-03-09 09:45:09,381 [shard 0] storage_service - JOINING: waiting for schema information to complete
INFO  2016-03-09 09:45:09,479 [shard 0] gossip - Node 192.168.122.11 is now part of the cluster
INFO  2016-03-09 09:45:09,479 [shard 0] gossip - InetAddress 192.168.122.11 is now UP
INFO  2016-03-09 09:45:09,512 [shard 0] gossip - Node 192.168.122.12 is now part of the cluster
INFO  2016-03-09 09:45:09,512 [shard 0] gossip - InetAddress 192.168.122.12 is now UP
INFO  2016-03-09 09:45:09,551 [shard 0] gossip - Node 192.168.122.13 is now part of the cluster
INFO  2016-03-09 09:45:09,552 [shard 0] gossip - InetAddress 192.168.122.13 is now UP
INFO  2016-03-09 09:45:09,580 [shard 0] schema_tables - Creating jepsen_keyspace.maps id=fe40f7d0-e5da-11e5-8ce4-000000000001 version=e9d7c5ac-302a-307b-8272-88a55b43b005
INFO  2016-03-09 09:45:09,740 [shard 0] compaction - Compacting [/var/lib/scylla/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-4-Data.db:level=0, /var/lib/scylla/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-8-Data.db:level=0, /var/lib/scylla/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-12-Data.db:level=0, /var/lib/scylla/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-16-Data.db:level=0, ]
INFO  2016-03-09 09:45:09,740 [shard 0] compaction - Compacting [/var/lib/scylla/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-4-Data.db:level=0, /var/lib/scylla/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-8-Data.db:level=0, /var/lib/scylla/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-12-Data.db:level=0, /var/lib/scylla/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-16-Data.db:level=0, ]
INFO  2016-03-09 09:45:09,816 [shard 0] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/schema_keyspaces-b0f2235744583cdb9631c43e59ce3676/system-schema_keyspaces-ka-20-Data.db:level=0, ]. 644 bytes to 161 (~25% of original) in 76ms = 0.00202028MB/s. ~1024 total partitions merged to 1.
INFO  2016-03-09 09:45:09,816 [shard 0] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/schema_columns-296e9c049bec3085827dc17d3df2122a/system-schema_columns-ka-20-Data.db:level=0, ]. 1716 bytes to 429 (~25% of original) in 76ms = 0.00538324MB/s. ~1024 total partitions merged to 1.
INFO  2016-03-09 09:45:09,818 [shard 0] compaction - Compacting [/var/lib/scylla/data/system/schema_columnfamilies-45f5b36024bc3f83a3631034ea4fa697/system-schema_columnfamilies-ka-4-Data.db:level=0, /var/lib/scylla/data/system/schema_columnfamilies-45f5b36024bc3f83a3631034ea4fa697/system-schema_columnfamilies-ka-8-Data.db:level=0, /var/lib/scylla/data/system/schema_columnfamilies-45f5b36024bc3f83a3631034ea4fa697/system-schema_columnfamilies-ka-12-Data.db:level=0, /var/lib/scylla/data/system/schema_columnfamilies-45f5b36024bc3f83a3631034ea4fa697/system-schema_columnfamilies-ka-16-Data.db:level=0, ]
INFO  2016-03-09 09:45:09,854 [shard 0] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/schema_columnfamilies-45f5b36024bc3f83a3631034ea4fa697/system-schema_columnfamilies-ka-24-Data.db:level=0, ]. 6704 bytes to 1676 (~25% of original) in 36ms = 0.0443988MB/s. ~1024 total partitions merged to 1.
INFO  2016-03-09 09:45:10,351 [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 192.168.122.11
INFO  2016-03-09 09:45:10,381 [shard 0] storage_service - JOINING: schema complete, ready to bootstrap
INFO  2016-03-09 09:45:10,381 [shard 0] storage_service - JOINING: waiting for pending range calculation
INFO  2016-03-09 09:45:10,381 [shard 0] storage_service - JOINING: calculation complete, ready to bootstrap
INFO  2016-03-09 09:45:10,381 [shard 0] storage_service - Checking bootstrapping/leaving/moving nodes: ok
INFO  2016-03-09 09:45:10,381 [shard 0] storage_service - JOINING: getting bootstrap token
INFO  2016-03-09 09:45:10,414 [shard 0] compaction - Compacting [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-4-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-8-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-12-Data.db:level=0, /var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-16-Data.db:level=0, ]
INFO  2016-03-09 09:45:10,423 [shard 0] storage_service - JOINING: sleeping 30000 ms for pending range setup
INFO  2016-03-09 09:45:10,450 [shard 0] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-20-Data.db:level=0, ]. 12753 bytes to 12540 (~98% of original) in 36ms = 0.332197MB/s. ~1024 total partitions merged to 1.
INFO  2016-03-09 09:45:11,351 [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 192.168.122.12
INFO  2016-03-09 09:45:12,352 [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 192.168.122.13
Failed with /cache_service/metrics/key/hits {"message": "Not found", "code": 404}
Failed with /cache_service/metrics/key/requests {"message": "Not found", "code": 404}
Failed with /cache_service/metrics/row/hits {"message": "Not found", "code": 404}
Failed with /cache_service/metrics/row/requests {"message": "Not found", "code": 404}
Failed with /cache_service/metrics/counter/hits {"message": "Not found", "code": 404}
Failed with /cache_service/metrics/counter/requests {"message": "Not found", "code": 404}
Failed with /compaction_manager/metrics/total_compactions_completed {"message": "Not found", "code": 404}
INFO  2016-03-09 09:45:30,356 [shard 0] gossip - InetAddress 192.168.122.13 is now DOWN
INFO  2016-03-09 09:45:36,358 [shard 0] gossip - InetAddress 192.168.122.12 is now DOWN
INFO  2016-03-09 09:45:37,359 [shard 0] gossip - InetAddress 192.168.122.11 is now DOWN
INFO  2016-03-09 09:45:40,423 [shard 0] storage_service - JOINING: Starting to bootstrap...
Exiting on unhandled exception of type 'std::runtime_error': A node required to move the data consistently is down (192.168.122.11).  If you wish to move the data from a potentially inconsistent replica, restart the node with -Dcassandra.consistent.rangemovement=false
INFO  2016-03-09 09:45:40,435 [shard 0] compaction_manager - Asked to stop
INFO  2016-03-09 09:45:40,436 [shard 0] compaction_manager - Stopped
INFO  2016-03-09 09:45:40,436 [shard 1] compaction_manager - Asked to stop
INFO  2016-03-09 09:45:40,436 [shard 2] compaction_manager - Asked to stop
INFO  2016-03-09 09:45:40,436 [shard 3] compaction_manager - Asked to stop
INFO  2016-03-09 09:45:40,436 [shard 1] compaction_manager - Stopped
INFO  2016-03-09 09:45:40,436 [shard 2] compaction_manager - Stopped
INFO  2016-03-09 09:45:40,436 [shard 3] compaction_manager - Stopped

```

**Comment by vladzcloudius** [comment]
The `bridge` test also didn't complete with all nodes bootstrapped. The picture looks similar to the first failed node in the `isolate-node` test described above.

**Comment by vladzcloudius** [comment]
@asias @slivne I've double checked - Cassandra has shown the same behavior in this tests. So, we may lower the priority of this issue or even close it completely.

**Comment by asias** [comment]
Good to know.

**Comment by vladzcloudius** [comment]
@asias The test goes like this:
1. Three nodes (n1, n2 and n3) are loaded on an empty DB. Nodes' IPs are 192.168.122.11/12/13.
2. The test starts to add new data to the cluster.
3. In parallel the new nodes are bootstrapped: first n4 and then after 1000 seconds n5 (IPs ending with 14 and 15 correspondingly).  
4. In parallel a `nemesis` fucks up the networking. It works in a cycles of `sleep 20s`->`fuck the networking up`->`sleep 60s`->`unfuck the networking`.
In the `isolate node` mode it would randomly chose a node and disconnect it from all other nodes.
In the `bridge mode` it would randomly choose 2 partitions of 2 nodes each and disconnect nodes from different partitions.

**Comment by slivne** [comment]
going back to the original issue "nodes seem to be to sensitive to
networking issues in bootstrap" - are we more sensitive to networking
issues then cassandra ?

If not lets close this - unless someone objects ?

**Comment by vladzcloudius** [comment]
@slivne as I've pointed out - C* shows the same level of 'sensitivity' in this test.

**Comment by slivne** [comment]
so close the bug as the creator you can close it as well
