### ISSUE TITLE
gnutls vulnerability: GNUTLS-SA-2020-09-04

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#7212]
https://www.gnutls.org/security-new.html#GNUTLS-SA-2020-09-04

> It was found by oss-fuzz that the server sending a "no_renegotiation" alert in an unexpected timing, followed by an invalid second handshake can cause a TLS 1.3 client to crash via a null-pointer dereference. The crash happens in the application's error handling path, where the gnutls_deinit function is called after detecting a handshake failure. The issue was reported in the issue tracker as #1071.

Fixed by gnutls 3.6.15

**Comment by avikivity** [comment]
My evaluation is that this is of low importance for us. It's a client crash, and we are only acting as a client to our own servers. In the worst case, if someone takes over our IP address and messes with us, we also crash. So it's a denial of service, but if someone took over our IP addresses we already have a much bigger problem.

There is now way this can lead to a confidentiality compromise.

**Comment by avikivity** [comment]
@elcallio please check my evaluation.

**Comment by elcallio** [comment]
@avikivity  late to the party, but I agree with the eval.

**Comment by avikivity** [comment]
Evaluated as not needed for backport.
