### ISSUE TITLE
paxos test schema_mismatch_mv_test fails with schema_mismatch_error: (Attempted to deserialize schema-dependent object of version a74e98ad-5464-3631-b6fb-fbfa6d7d38e9 using ks.test 8759ae7e-8563-38ab-8abc-045a6caff3cc)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7225]
Seen since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/590/testReport/paxos_tests/TestPaxos/schema_mismatch_mv_test_2/
that includes https://github.com/scylladb/scylla-dtest/pull/1652

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/590/testReport/paxos_tests/TestPaxos/schema_mismatch_mv_test/
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/paxos_tests.py", line 513, in schema_mismatch_mv_test
    verify_results_action=check_schema_mismatch_exc
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/paxos_tests.py", line 419, in _schema_mismatch_test_tpl
    second_insert_action(session, key)
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/paxos_tests.py", line 498, in insert_action
    session.execute(stmt, [key, 0])
  File "cassandra/cluster.py", line 2611, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4829, in cassandra.cluster.ResponseFuture.result
cassandra.WriteFailure: Error from server: code=1500 [Replica(s) failed to execute write] message="Operation failed for ks.test - received 0 responses and 1 failures from 1 CL=ONE." info={'consistency': 'ONE', 'required_responses': 1, 'received_responses': 0, 'failures': 1}
```

```
Unexpected errors found: [('node1', ['ERROR 2020-09-09 18:00:40,154 [shard 0] storage_proxy - exception during mutation write to 127.0.16.1: seastar::internal::backtraced<schema_mismatch_error> (Attempted to deserialize schema-dependent object of version a74e98ad-5464-3631-b6fb-fbfa6d7d38e9 using ks.test 8759ae7e-8563-38ab-8abc-045a6caff3cc Backtrace:    /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/66e821460600f8ad06e2eaf6099227bc9c1cb7be/scylla//opt/scylladb/libreloc/libasan.so.6+0x45bad', 'ERROR 2020-09-09 18:00:40,150 [shard 0] database - failed to log message: seastar::internal::backtraced<schema_mismatch_error> (Attempted to deserialize schema-dependent object of version a74e98ad-5464-3631-b6fb-fbfa6d7d38e9 using ks.test 8759ae7e-8563-38ab-8abc-045a6caff3cc Backtrace:    /jenkins/workspace/scylla-master/dtest-debug/scylla/.ccm/scylla-repository/66e821460600f8ad06e2eaf6099227bc9c1cb7be/scylla//opt/scylladb/libreloc/libasan.so.6+0x45bad'])]
```

**Comment by bhalevy** [comment]
Cc @dkropachev @kostja

**Comment by ManManson** [comment]
It's a flaky test, needs to be adjusted or disabled for now. The cause for the failure is that these tests are expected to hit `schema_registry` cache when asking for an outdated schema version, but in case of `debug` build of scylla and, in particular, jenkins setup the node is slow enough to trigger eviction of needed schema version from the local node cache (i.e. `schema_registry`). Well, actually that means that all `schema_mismatch_*` tests are possibly vulnerable to such failures, especially in `debug` mode.

We have a hardcoded amount of time (see `grace_period()` in `schema_registry.cc`, is set to 1 second) after which in case we don't have any live pointers to a schema object, the associated cache entry will be deallocated too. So in case of jenkins test run the node is slow enough to evict the entry from the cache.

@tgrabiec Would it be reasonable to un-hardcode this limit and be able to override grace period for schema_registry cache? I mean not only for the sake of testing, but for real practical uses in circumstances similar to this test?

**Comment by bhalevy** [comment]
@ManManson we strive to be able to run debug built scylla in SCT with "real" nemesis events so internal timing should be robust enough for debug mode.

**Comment by ManManson** [comment]
@bhalevy Okay, good, then we need to remove parameterize this grace period and provide an option for it. I'll prepare a patch for that.

**Comment by ManManson** [comment]
@bhalevy Should I disable the problematic test while we don't have a workaround solution for the test case?

**Comment by bhalevy** [comment]
I think so.  You can decorate it with `@skip('7225')`.
@roy, @kostja what do you think?

**Comment by tgrabiec** [comment]
On Mon, Sep 14, 2020 at 12:22 PM Pavel Solodovnikov <
notifications@github.com> wrote:

> It's a flaky test, needs to be adjusted or disabled for now. The cause for
> the failure is that these tests are expected to hit schema_registry cache
> when asking for an outdated schema version, but in case of debug build of
> scylla and, in particular, jenkins setup the node is slow enough to trigger
> eviction of needed schema version from the local node cache (i.e.
> schema_registry). Well, actually that means that all schema_mismatch_*
> tests are possibly vulnerable to such failures, especially in debug mode.
>
> We have a hardcoded amount of time (see grace_period() in
> schema_registry.cc, is set to 1 second) after which in case we don't have
> any live pointers to a schema object, the associated cache entry will be
> deallocated too. So in case of jenkins test run the node is slow enough to
> evict the entry from the cache.
>
> @tgrabiec <https://github.com/tgrabiec> Would it be reasonable to
> un-hardcode this limit and be able to override grace period for
> schema_registry cache? I mean not only for the sake of testing, but for
> real practical uses in circumstances similar to this test?
>

We could make it configurable.

But in real world scenarios, this grace period should never cause
correctness issues, it only amortizes the cost of re-requesting old schema
definitions from the sending node which is still behind, and sends requests
rarely.

**Comment by ManManson** [comment]
@tgrabiec Can you please elaborate on how it can cause us problems with correctness? As you've mentioned, it only saves us from doing another request to get schema from the remote node or in case of LWT get the schema locally in case we're, for example, are a lagging for a few seconds more with respect to other nodes. So I think it won't do any harm to make this configurable.

**Comment by tgrabiec** [comment]
> @tgrabiec Can you please elaborate on how it can cause us problems with correctness?

I didn't mean to suggest that it could cause correctness problems.
