### ISSUE TITLE
Some Alternator Streams tests fail on multi-node cluster

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7237]
I ran the Alternator test suite manually against a three-node Scylla (we should make such runs easy via  `test/alternator/run` - see #7236). Most tests passed, but six Alternator Streams failed: `test_streams_updateitem_keys_only_2`, `test_streams_updateitem_old_image`, `test_streams_updateitem_old_image_empty_item`, `test_streams_updateitem_old_image_lsi`, `test_streams_new_image`, `test_streams_new_and_old_images`.

All failures happened when our `fetch_more()` function tried to pass an empty string for `ShardIterator` - which suggests (but need to verify...) that a previous `GetRecords` request returned an empty string for `NextShardIterator`, which is not a valid iterator.

We need to figure out why this happens, and why it only happens (and consistently happens!) in a multi-node test.

CC: @elcallio

**Comment by elcallio** [comment]
See:
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_GetRecords.html

`NextShardIterator` is supposed to be null (which I interpreted as set but no value - wrong?) if the shard is closed - which for us means that the stream_id was from an older stream id set, and we've reached end-of-data (i.e. timestamp at generation end). 
Question is if this check is broken?

**Comment by nyh** [comment]
@elcallio good question! The `fetch_more()` code I wrote for the test checked if there is a `NextShardIterator` attribute at all - not if it is an empty string. It is quite possible that your interpretation is correct, and the test code is wrong (it should check if the attribute is an empty string)  - although we need to confirm which is the correct interpretation. Note that there's even a third option - that it really should be a "null" (there is such a JSON type), not an empty string :-(

But regardless of this potential test bug, I don't understand why we reach this situation in the multi-node test. This is a long-running Scylla cluster, and I rand the test many minutes after the Scylla boot. What causes shards to be "closed"?

**Comment by nyh** [comment]
What a mess :-(
This person claims that DynamoDB will omit `NextShardIterator` (not set it to an empty string) when a shard is closed:
https://stackoverflow.com/questions/33544974/meaning-of-null-nextsharditerator
But this person claims that it will return a null `NextShardIterator`, which is different from empty - whatever that means
https://forums.aws.amazon.com/thread.jspa?threadID=152029
I'm still trying to figure out if there is any way I can test this on DynamoDB.

**Comment by elcallio** [comment]
Seems omitting is a reasonable approach, and assume either explicit null or missing in test/client code. 
As for to why this happens, I think it is simply that one node started before the other, and generated an initial stream id set (based on 1 node, or 2 nodes or whatever), then once all nodes are up, a new generation was computed. But since we have to iterate all "shards" that could ever have existed, we include these primordial shards - which all result in an empty iteration.

**Comment by nyh** [comment]
@elcallio thanks. Your explanation of why we reached this case makes sense. I'm writing now a test to confirm what is DynamoDB's real behavior, and can also make the test code more forgiving to also accept the current null-string behavior.

**Comment by nyh** [comment]
I verified (wrote a test) that DynamoDB's meaning of "null NextShardIterator" is that it is completely missing - not an empty string. I'll prepare a patch / patches. According to my test, the answer in https://stackoverflow.com/questions/33544974/meaning-of-null-nextsharditerator was correct.

**Comment by nyh** [comment]
Not backporting. Alternator Streams does not yet exist in 4.2.
