### ISSUE TITLE
Metrics in “CQL ONE CL Queries” 50 times greater than the metrics in “CQL Reads”

### ISSUE THREAD

**Issue by nikolay-toroptsev** [scylladb/scylla#7238]
*Installation details*
Scylla version (or git commit hash): 4.1.0
Cluster size: 4 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 8

UUID of uploaded prometheus metrics: CD8654F5-45C2-4FA1-A633-8740C8C461C5

<img width="1592" alt="image" src="https://user-images.githubusercontent.com/46109483/93207263-636afb80-f763-11ea-8285-56748697c5a1.png">
<img width="387" alt="image" src="https://user-images.githubusercontent.com/46109483/93207299-71b91780-f763-11ea-928e-f4db46480943.png">

**Comment by slivne** [comment]
@amnonh I checked and if I look in prometheus 

 sum(scylla_query_processor_queries) 
![1](https://user-images.githubusercontent.com/3465480/93723111-830b8500-fba4-11ea-9791-b38e27c102e5.png)

vs

sum(scylla_cql_reads) +sum(scylla_cql_inserts) +sum(scylla_cql_updates) +sum(scylla_cql_deletes) 
![2](https://user-images.githubusercontent.com/3465480/93723114-8868cf80-fba4-11ea-8169-e1f1bb229ae8.png)

they seem to be in the same range and increasing over the specific time in the same manner (e.g. they are aligned more or less)

so I think the issue maybe the way the metrics are exposed in graphana - can you please check this out

**Comment by amnonh** [comment]
@nikolay-toroptsev can you please add the scylla-monitoring version?
you can find it in the overview dashboard at the bottom

**Comment by amnonh** [comment]
After my fix it looks like:
![image](https://user-images.githubusercontent.com/2118079/93750283-e678cf80-fc03-11ea-9806-3b932047e4c4.png)

**Comment by amnonh** [comment]
It will be solved with the next Scylla-Monitoring release (3.5)

**Comment by slivne** [comment]
@amnonh can you reference the commit  / issue in manager ?

@amnonh please note there are other ConsistencyLevel graphs did you fix them all ?

**Comment by slivne** [comment]
@amnonh - read previous comments - and followed the pull request you did address all 

closing issue - fixed by https://github.com/scylladb/scylla-monitoring/pull/1058/commits/40b8911bc3933bc57697e66a44a4778831423838
