### ISSUE TITLE
MV: Allow altering MVs

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#7248]
Scylla version: 5f541fbdc55be813e99ff3c0f7ae6034b2908e3a

*Description*
Today we can't alter MV/SI, e.g. if we want to change their compaction strategy, a speculative read retry configuration or a gc_graces_seconds value.

The only way to change it today is to drop the MV and rebuild it.

It makes sense to allow MV changes without having to drop it.

**Comment by nyh** [comment]
Issue #3284 suggests that in the past, "ALTER MATERIALIZED VIEW" was possible - and in that example, changes the compaction strategy. Is this no longer possible today?

**Comment by vladzcloudius** [comment]
> Issue #3284 suggests that in the past, "ALTER MATERIALIZED VIEW" was possible - and in that example, changes the compaction strategy. Is this no longer possible today?

You are right: the syntax should be "ALTER MATERIALIZED VIEW":

```
fred@cqlsh> alter MATERIALIZED VIEW keyspace1.my_desc_order with compaction = {'class': 'LeveledCompactionStrategy'};
fred@cqlsh> desc keyspace1.my_desc_order;

CREATE MATERIALIZED VIEW keyspace1.my_desc_order AS
    SELECT *
    FROM keyspace1.standard1
    WHERE key IS NOT null AND "C1" IS NOT null
    PRIMARY KEY (key, "C1")
    WITH CLUSTERING ORDER BY ("C1" DESC)
    AND bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'LeveledCompactionStrategy'}
    AND compression = {'sstable_compression': 'org.apache.cassandra.io.compress.LZ4Compressor'}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.1
    AND default_time_to_live = 0
    AND gc_grace_seconds = 864000
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';

```

**Comment by vladzcloudius** [comment]
@gnumoreno FYI
