### ISSUE TITLE
HTTP server init only after bootstrap, data streaming, is done

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#725]
When adding a node to cluster, bootstrap including data streaming from other nodes.
Streaming can take minutes (hours!) depending on data volume and network bandwidth.

nodetool should be available ASAP, reporting the node status.
For that, HTTP server should start ASAP, not after data streaming is done.

**Comment by penberg** [comment]
The commit was reverted due to other breakage it introduced: https://github.com/scylladb/scylla/commit/733584c44df07f231021944cfdda1e88ee1dd6f0

**Comment by amnonh** [comment]
It was already fixed
