### ISSUE TITLE
Possible read resources leak

### ISSUE THREAD

**Issue by page4** [scylladb/scylla#7256]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash):   9650b8d

https://github.com/scylladb/scylla/blob/9650b8d4b57cadf4e0e4ede2ffc5ac320987e9e6/reader_concurrency_semaphore.cc#L172-L173

L172 may leak some resources if an exception is thrown as the following.

https://github.com/scylladb/scylla/blob/fd293768e73673e156e7645a5f869aa621a3a7a3/reader_concurrency_semaphore.cc#L108-L111

**Comment by denesb** [comment]
@page4 the two code fragments are from two different versions, let's look at the first one first (from recent master):
https://github.com/scylladb/scylla/blob/9650b8d4b57cadf4e0e4ede2ffc5ac320987e9e6/reader_concurrency_semaphore.cc#L171-L174

The `resource_units::resource_units()` constructor doesn't allocate so it can't throw, it is even annotated with `noexcept`. `make_ready_future<>()` is also `noexcept` so there is no potential for leak here.

Now the situation is indeed different in the case of the second fragment which is from 3.3:
https://github.com/scylladb/scylla/blob/fd293768e73673e156e7645a5f869aa621a3a7a3/reader_concurrency_semaphore.cc#L108-L111

`make_lw_shared<>()` indeed allocates and can throw so this has the potential to leak the resources. I will check which live versions are affected by this.

Thanks for looking into this.

**Comment by denesb** [comment]
4.0 and 4.1 is affected.

**Comment by page4** [comment]
@denesb yes, the master branch  is safe now, but it may be changed later.  RAII is more safe.

**Comment by denesb** [comment]
`reader_permit::resource_units` is a RAII object, it just doesn't do the consume part in its constructor, but it releases it in its destructor.

**Comment by denesb** [comment]
I would be cleaner if it did the consume in its constructor, I know there was a reason I didn't do it when I wrote this. Maybe with the changes since it can be done. But for 4.0/4.1 we should go for the simpler solution of just allocating the permit before deducting the resources.

**Comment by avikivity** [comment]
What commit fixed it? Maybe the answer is there, or at least a source for a backport.

**Comment by denesb** [comment]
@avikivity this was fixed by https://github.com/scylladb/scylla/commit/0c6bbc84cd30df1c46a6cd81d87170b99d5a8144, namely commit f417b9a3ea, but the commit had a bunch of preparation steps before it.

**Comment by avikivity** [comment]
Yeah, well we aren't going to backport that.

**Comment by denesb** [comment]
Patch on the list: [PATCH v1] reader_permit: reader_resources: make true RAII class

**Comment by denesb** [comment]
Backporting to 4.2 should be trivial. I will prepare a backport for 4.0/4.1 as those have quite different code around reader permits.

**Comment by denesb** [comment]
This backported suprisingly smoothly to 4.1/4.0. Patch on the list: [branch-4.1] reader_permit: reader_resources: make true RAII class.

**Comment by avikivity** [comment]
@denesb please ping the patch on the list, looks like I missed it.

**Comment by avikivity** [comment]
Also, it's not backported to 4.2.

**Comment by avikivity** [comment]
Backported to 4.2.

**Comment by avikivity** [comment]
Already backported.
