### ISSUE TITLE
Make repair progress metrics shorter and use label

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#7270]
Commit 7c8728dd735eecc5d2dae9350c606a28a3ec5876 added repair-based operation metrics.
There are two issues with those metrics:
1. The name is long for example: scylla_node_maintenance_operations_rebuild_finished_percentage
2. The self reporting metrics (i.e. metrics that a node report about itself) would be better off using a single metric differ by label.
this way a user of that metric can check for any repair-based operation.

**Comment by amnonh** [comment]
@slivne can we count on it for 4.3? the change is minimal (I can do it also) but it would be easier for monitoring.

**Comment by slivne** [comment]
@asias is it clear what amnon is requesting - if its clear lets fix it - we want to incldue the metrics in dashboards and its easier if its consistent between version

**Comment by asias** [comment]
> Commit [7c8728d](https://github.com/scylladb/scylla/commit/7c8728dd735eecc5d2dae9350c606a28a3ec5876) added repair-based operation metrics.
> There are two issues with those metrics:
> 
>     1. The name is long for example: scylla_node_maintenance_operations_rebuild_finished_percentage

What is wrong with a long metric name? What is the impact?

>     2. The self reporting metrics (i.e. metrics that a node report about itself) would be better off using a single metric differ by label.
>        this way a user of that metric can check for any repair-based operation.

Amnon, do you need  a label for scylla dashboard? You are the expect.  What is wrong using the individual metrics?

**Comment by amnonh** [comment]
> > Commit [7c8728d](https://github.com/scylladb/scylla/commit/7c8728dd735eecc5d2dae9350c606a28a3ec5876) added repair-based operation metrics.
> > There are two issues with those metrics:
> > ```
> > 1. The name is long for example: scylla_node_maintenance_operations_rebuild_finished_percentage
> > ```
> 
> What is wrong with a long metric name? What is the impact?
It's harder to use and handle, remember that metrics are used inside expressions, such a long metrics names make it un-readable.

> 
> > ```
> > 2. The self reporting metrics (i.e. metrics that a node report about itself) would be better off using a single metric differ by label.
> >    this way a user of that metric can check for any repair-based operation.
> > ```
> 
> Amnon, do you need a label for scylla dashboard? You are the expect. What is wrong using the individual metrics?
Think about 4 types of repair that goes between zero and 1.
the expression `sum(scylla_repair_op) by (instance)` (if repair is running on a single shard, you can add avg for multi-shard) will let you know that a repair operation is in progress.

**Comment by asias** [comment]
> > > Commit [7c8728d](https://github.com/scylladb/scylla/commit/7c8728dd735eecc5d2dae9350c606a28a3ec5876) added repair-based operation metrics.
> > > There are two issues with those metrics:
> > > ```
> > > 1. The name is long for example: scylla_node_maintenance_operations_rebuild_finished_percentage
> > > ```
> > 
> > 
> > What is wrong with a long metric name? What is the impact?
> 
> It's harder to use and handle, remember that metrics are used inside expressions, such a long metrics names make it un-readable.

The longer name makes the metric self-explanatory. 

E.g., 

scylla_node_maintenance_operations_rebuild_finished_percentage

v.s.

snmorfp

Also, the scylla-monitor users use the dashboard so, they even do not need to care about the underlying metrics at all. 

> 
> > > ```
> > > 2. The self reporting metrics (i.e. metrics that a node report about itself) would be better off using a single metric differ by label.
> > >    this way a user of that metric can check for any repair-based operation.
> > > ```
> > 
> > 
> > Amnon, do you need a label for scylla dashboard? You are the expect. What is wrong using the individual metrics?
> 
> Think about 4 types of repair that goes between zero and 1.
> the expression `sum(scylla_repair_op) by (instance)` (if repair is running on a single shard, you can add avg for multi-shard) will let you know that a repair operation is in progress.

We only allow one node operation at a time. For example, we can not run both bootstrap or decommission at the same time.

**Comment by amnonh** [comment]
> > > > Commit [7c8728d](https://github.com/scylladb/scylla/commit/7c8728dd735eecc5d2dae9350c606a28a3ec5876) added repair-based operation metrics.
> > > > There are two issues with those metrics:
> > > > ```
> > > > 1. The name is long for example: scylla_node_maintenance_operations_rebuild_finished_percentage
> > > > ```
> > > 
> > > 
> > > What is wrong with a long metric name? What is the impact?
> > 
> > 
> > It's harder to use and handle, remember that metrics are used inside expressions, such a long metrics names make it un-readable.
> 
> The longer name makes the metric self-explanatory.
> 
> E.g.,
> 
> scylla_node_maintenance_operations_rebuild_finished_percentage
> 
> v.s.
> 
> snmorfp
> 
> Also, the scylla-monitor users use the dashboard so, they even do not need to care about the underlying metrics at all.
> 

Some users uses the metrics, the metrics has a help string and some one needs to maintain the dashboards, those metrics are 3 times longer than all other metrics.

> > > > ```
> > > > 2. The self reporting metrics (i.e. metrics that a node report about itself) would be better off using a single metric differ by label.
> > > >    this way a user of that metric can check for any repair-based operation.
> > > > ```
> > > 
> > > 
> > > Amnon, do you need a label for scylla dashboard? You are the expect. What is wrong using the individual metrics?
> > 
> > 
> > Think about 4 types of repair that goes between zero and 1.
> > the expression `sum(scylla_repair_op) by (instance)` (if repair is running on a single shard, you can add avg for multi-shard) will let you know that a repair operation is in progress.
> 
> We only allow one node operation at a time. For example, we can not run both bootstrap or decommission at the same time.

Exactly, so no look back at `sum(scylla_repair_op) by (instance)` which sums over all label values and see how easy it is.

**Comment by asias** [comment]
How about this:
```
commit 2577032a60679ec5a48e4a13e105c9f2d7697ec9 (HEAD -> repair_use_label_for_metrics)
Author: Asias He <asias@scylladb.com>
Date:   Mon Nov 9 16:17:05 2020 +0800

    repair: Use label for node ops metrics

diff --git a/repair/repair.cc b/repair/repair.cc
index c1d160d34..78e5ec532 100644
--- a/repair/repair.cc
+++ b/repair/repair.cc
@@ -57,19 +57,20 @@ class node_ops_metrics {
 public:
     node_ops_metrics() {
         namespace sm = seastar::metrics;
-        _metrics.add_group("node_maintenance_operations", {
-            sm::make_gauge("bootstrap_finished_percentage", sm::description("Number of finished percentage for bootstrap operation on this shard."),
-                [this] { return bootstrap_finished_percentage(); }),
-            sm::make_gauge("replace_finished_percentage", sm::description("Number of finished percentage for replace operation on this shard."),
-                [this] { return replace_finished_percentage(); }),
-            sm::make_gauge("rebuild_finished_percentage", sm::description("Number of finished percentage for rebuild operation on this shard."),
-                [this] { return rebuild_finished_percentage(); }),
-            sm::make_gauge("decommission_finished_percentage", sm::description("Number of finished percentage for decommission operation on this shard."),
-                [this] { return decommission_finished_percentage(); }),
-            sm::make_gauge("removenode_finished_percentage", sm::description("Number of finished percentage for removenode operation on this shard."),
-                [this] { return removenode_finished_percentage(); }),
-            sm::make_gauge("repair_finished_percentage", sm::description("Number of finished percentage for repair operation on this shard."),
-                [this] { return repair_finished_percentage(); }),
+        auto ops_label_type = sm::label("ops");
+        _metrics.add_group("node_ops", {
+            sm::make_gauge("finished", [this] { return bootstrap_finished_percentage(); },
+                    sm::description("Number of finished percentage for bootstrap operation on this shard."), {ops_label_type("bootstrap")}),
+            sm::make_gauge("finished", [this] { return replace_finished_percentage(); },
+                    sm::description("Number of finished percentage for replace operation on this shard."), {ops_label_type("replace")}),
+            sm::make_gauge("finished", [this] { return rebuild_finished_percentage(); },
+                    sm::description("Number of finished percentage for rebuild operation on this shard."), {ops_label_type("rebuild")}),
+            sm::make_gauge("finished", [this] { return decommission_finished_percentage(); },
+                    sm::description("Number of finished percentage for decommission operation on this shard."), {ops_label_type("decommission")}),
+            sm::make_gauge("finished", [this] { return removenode_finished_percentage(); },
+                    sm::description("Number of finished percentage for removenode operation on this shard."), {ops_label_type("removenode")}),
+            sm::make_gauge("finished", [this] { return repair_finished_percentage(); },
+                    sm::description("Number of finished percentage for repair operation on this shard."), {ops_label_type("repair")}),
         });
     }
     uint64_t bootstrap_total_ranges{0};
```

**Comment by amnonh** [comment]
In general, it looks good. Two things:
1. `finished` is a bit confusing, in fact, it's the progress and it's best to suffix with the units (percent?)
2. The description, needs to be the same for all metrics

**Comment by asias** [comment]
> In general, it looks good. Two things:
> 
>     1. `finished` is a bit confusing, in fact, it's the progress and it's best to suffix with the units (percent?)

It was *_finished_percentage. I think we want short one, so I dropped the _percentage.

How about finished_percentage?


>     2. The description, needs to be the same for all metrics


What do you mean? I can not use different descriptions for different metrics? Why?

```
+            sm::make_gauge("finished", [this] { return removenode_finished_percentage(); },
+                    sm::description("Number of finished percentage for removenode operation on this shard."), {ops_label_type("removenode")}),
+            sm::make_gauge("finished", [this] { return repair_finished_percentage(); },
+                    sm::description("Number of finished percentage for repair operation on this shard."), {ops_label_type("repair")}),
```

**Comment by amnonh** [comment]
> > In general, it looks good. Two things:
> > ```
> > 1. `finished` is a bit confusing, in fact, it's the progress and it's best to suffix with the units (percent?)
> > ```
> 
> It was *_finished_percentage. I think we want short one, so I dropped the _percentage.
> 
> How about finished_percentage?
I find `finished` confusing, it's not the end of the world, but I would have choose something clearer.

> 
> > ```
> > 2. The description, needs to be the same for all metrics
> > ```
> 
> What do you mean? I can not use different descriptions for different metrics? Why?
There is one description for all metrics with the same name. If you look at the metrics output (http://{ip}:9180/metrics) 
You see that each metric is defined once, with a help string followed by all its values.

> 
> ```
> +            sm::make_gauge("finished", [this] { return removenode_finished_percentage(); },
> +                    sm::description("Number of finished percentage for removenode operation on this shard."), {ops_label_type("removenode")}),

I think that '**Number of finished percentage**' is not clear, you don't count finished percentage

> +            sm::make_gauge("finished", [this] { return repair_finished_percentage(); },
> +                    sm::description("Number of finished percentage for repair operation on this shard."), {ops_label_type("repair")}),
> ```

**Comment by avikivity** [comment]
Not a bug, not backporting.
