### ISSUE TITLE
Scylla outputing filesystem related message in networking error message

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#728]
I accidentally broken CharybdeFS while adding code to implement variables delays for Glauber.

The output is:

[root@localhost scylla]# ./build/release/scylla --memory 512M
Scylla version development-20151217.89dcc5d starting ...
WARN  [shard 0] config - Option partitioner is not (yet) used.
Start Storage service ...
WARN  [shard 0] init - /var/lib/scylla/commitlog is not on XFS. This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is strongly recommended
WARN  [shard 0] init - /var/lib/scylla/data is not on XFS. This is a non-supported setup, and performance is expected to be very bad.
For better performance, placing your data on XFS-formatted directories is strongly recommended
Start gossiper service ...
Starting listening for CQL clients on localhost:9042...
Seastar HTTP server listening on localhost:10000 ...
^[[CERROR [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: Cannot allocate memory

This was caused by CharybdeFS's read returning -ENOMEM.

What is strange with this message is the wording. It's is displaying a filesystem exception in networking terms.

With what message could we replace this one ?

**Comment by gleb-cloudius** [comment]
On Tue, Dec 29, 2015 at 08:42:14AM -0800, Benoît Canet wrote:
> 
> I accidentally broken CharybdeFS while adding code to implement variables delays for Glauber.
> 
> The output is:
> 
> [root@localhost scylla]# ./build/release/scylla --memory 512M
> Scylla version development-20151217.89dcc5d starting ...
> WARN  [shard 0] config - Option partitioner is not (yet) used.
> Start Storage service ...
> WARN  [shard 0] init - /var/lib/scylla/commitlog is not on XFS. This is a non-supported setup, and performance is expected to be very bad.
> For better performance, placing your data on XFS-formatted directories is strongly recommended
> WARN  [shard 0] init - /var/lib/scylla/data is not on XFS. This is a non-supported setup, and performance is expected to be very bad.
> For better performance, placing your data on XFS-formatted directories is strongly recommended
> Start gossiper service ...
> Starting listening for CQL clients on localhost:9042...
> Seastar HTTP server listening on localhost:10000 ...
> ^[[CERROR [shard 0] storage_proxy - Exception when communicating with 127.0.0.1: Cannot allocate memory
> 
> This was caused by CharybdeFS's read returning -ENOMEM.
> 
> What is strange with this message is the wording. It's is displaying a filesystem exception in networking terms.
>
Storage proxy communicates with several nodes to accomplish its task.
Sometimes it so happens that one of those nodes is the same one storage
proxy code is running on, but only lowest level knows this (and that's
because we optimized local access to not go throw the network), high
level, where error is captured and reported has no idea. Of course
error reporting code can check if node the error happens with is the same
as local node and use some other wording. Is it worth doing? Not sure,
but patch is welcome.

> With what message could we replace this one ?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/scylladb/scylla/issues/728

--
			Gleb.

**Comment by avikivity** [comment]
It can probably happen when talking to a real remote node too.  The exception happens on the remote node, and is transported back to the local node and printed there.

**Comment by slivne** [comment]
If we added additional info to the exception to know it was from the FS then it would not be misleading.

**Comment by slivne** [comment]
Also related to #705, #706 once we fix those for GA (stopping in one form or another on errors) this should not happen

**Comment by benoit-canet** [comment]
Closed by:
1fb9a48ac5fe332a948bd006d9c64aa11916a77a
3b1d3d977d50204400fc6277390a1740e22d34ce

Tested a day of two with CharybdeFS. I am pretty confident it's ok.
