### ISSUE TITLE
Got offline mode warnings on nonroot mode

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#7286]
Since we defined that nonroot mode is part of offline mode, scylla_setup interactive mode shows up "XXX setup is disabled by default, since the installation is offline mode", but nonroot mode does not able to run them anyway since these scripts requires root privilege.
So it probably should not shows up on nonroot mode.  
```
vagrant@ubuntu1604:~$ ~/scylladb/scripts/scylla_setup 
ntp setup is disabled by default, since the installation is offline mode.
node exporter setup is disabled by default, since the installation is offline mode.
coredump setup disabled by default, since systemd-coredump not available.
cpuscaling setup disabled by default, since cpufrequtils not available.

Skip any of the following steps by answering 'no'
```

**Comment by avikivity** [comment]
Minor, not backporting.
