### ISSUE TITLE
nodetool stop COMPACTION not working

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#729]
```
nodetool stop COMPACTION
error: Not found
-- StackTrace --
java.lang.RuntimeException: Not found
    at com.cloudius.urchin.api.APIClient.getException(APIClient.java:113)
    at com.cloudius.urchin.api.APIClient.post(APIClient.java:100)

```

**Comment by tzach** [comment]
@amnonh ?

**Comment by raphaelsc** [comment]
@tzach It's working now (after ff9b1694f).

**Comment by penberg** [comment]
@tzach Can we close this issue?

**Comment by slivne** [comment]
@tzach ping ?

@amnonh we have a test for this ?

**Comment by amnonh** [comment]
I don't I think Raphael has one

**Comment by raphaelsc** [comment]
BTW, compaction will be retried after user asked it to stop. That's the default behavior for C* too IIRC. A quick test is about triggering compaction, asking for it to stop, then quickly checking that active compaction counter has decreased.

**Comment by raphaelsc** [comment]
@slivne: ping. this can be closed.
