### ISSUE TITLE
Startup check of various OS limits and refuse to boot unless they are sane (unless --developer-mode is provided)

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#730]

**Comment by avikivity** [comment]
Which limit?

**Comment by penberg** [comment]
@slivne The bug report title is badly written out because it fails to mention *which* limit needs to be checked.

However, as you referenced this issue from #692, you're probably talking about ``NOFILE`` rlimit. A check for that was added in https://github.com/scylladb/scylla/commit/2ba49103850f4d7b0107ab36b9dfcde2b7540743 and this issue and thus be closed.

**Comment by slivne** [comment]
I copy pasted from Avi's response email - and I think we need to check all
limits not only files - do we have additional items that can effect scylla

core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 63625
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 4096
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited


Some of them may be defaulted to unlimited usually yet - if any user
changes the default it would be better that we detect it at boot.

**Comment by penberg** [comment]
@slivne Fair enough. I edited the title and reopened the issue.

**Comment by avikivity** [comment]
None of those matter (well, a virtual memory limit will kill scylla immediately, but well before you can check anything).

core file size is important, but it's something for an upper layer to check, scylla itself can run happily without it.
