### ISSUE TITLE
NEW_NODE should be sent after listening for CQL clients has started

### ISSUE THREAD

**Issue by avelanarius** [scylladb/scylla#7301]
After adding a new node to the cluster, Scylla sends a `NEW_NODE` event. Some clients (for example Java Driver 3.x - both Scylla and [DataStax version](https://github.com/datastax/java-driver/blob/373cb519310208f93a3b08b70f913d3e95fd16eb/driver-core/src/main/java/com/datastax/driver/core/Cluster.java#L2398-L2418)) immediately try to connect to such new node, however they (sometimes) fail, because Scylla has not started listening for CQL clients yet.

There is a discrepancy between Scylla and Cassandra: Cassandra waits for CQL listening to start (on a new node) before sending `NEW_NODE` to clients. Therefore in Cassandra clients can immediately connect to the new node described in the `NEW_NODE` event. I have manually verified this waiting behaviour by adding a 20s sleep in Cassandra 3.11.8 before starting CQL listening (`Thread.sleep(20000)` before line 161 in [Server.java](https://github.com/apache/cassandra/blob/8b29b698630960a0ebb2c695cc5b21dee4686d09/src/java/org/apache/cassandra/transport/Server.java#L161)).

*Installation details*
Scylla version (or git commit hash): 666.development-0.20200929.1adf2cc84
Cluster size: 1 (2 after adding second node)
OS (RHEL/CentOS/Ubuntu/AWS AMI): Fedora 32

**Comment by haaawk** [comment]
This is the reason why the on-Node-Added notification sometimes wasn't working in the replicator.

**Comment by nyh** [comment]
This is an old fix, already in branches 4.3 - 4.5, so nothing remains to backport.
