### ISSUE TITLE
Logging batches in `system_traces.node_slow_log` should fill "query" field and split "BEGIN BATCH..."

### ISSUE THREAD

**Issue by jul-stas** [scylladb/scylla#7307]
When a slow batch is logged into `system_traces.node_slow_log`, it should have some meaningful value in `command` column, under `query` key. The agreed-to value is "BATCH QUERY". It should also be the case in case of "BEGIN BATCH..." query.

Also, "BEGIN BATCH..." queries that fall here should be split like batches. So the `parameters` column should have keys like `query[0]`, `query[1]`, `param[0][0]`, etc.

The above is a conclusion from private discussion on #7293.

**Comment by jul-stas** [comment]
@vladzcloudius How to approach "BEGIN BATCH..." (with query opcode)?
That looks like a nightmare to do.

**Comment by vladzcloudius** [comment]
As far as I can tell `BEGIN BATCH` statement is not only executed via QUERY opcode but is also going through the query path in the query_processor code: in particular `query_processor::execute_direct`:

```
TRACE 2020-10-02 17:40:51,588 [shard 0] query_processor - execute_direct: "BEGIN UNLOGGED BATCH  INSERT INTO ks2.test (a, b) VALUES ( 2, '3' ); INSERT INTO ks2.test (a, b) VALUES ( 3, '4' );
 APPLY BATCH ;"
```

I don't have a build env now but I'd assume that after that we eventually get to batch_statement::execute(...).

And at that stage the batch is already parsed by `cql_parser` and split into separate `single_statement`s.

Reconstructing it back from the binary seems like not a wise idea.

We could theoretically, modify cql_parser to store each query string in some string field of `single_statement` if Tracing is requested. 

@dekimir How complicated it may be? 

As much as I'd like to unify these kind of BATCHes with batches coming via `BATCH` opcode - it seems too much of an effort.

The current state is that these batches are going to get the same treatment as non-batch queries from Tracing: 
* The whole batch string is stored in the `query` key of `parameters` map.
* The whole string is stored in the `command` column in `node_slow_log`.

It's not perfect but unless the cql_traces modification I mentioned above is really trivial (noting about cql_traces is usually trivial) does it justify touching cql_parser code to address that - I don't think so.

**Comment by dekimir** [comment]
> I'd assume that after that we eventually get to batch_statement::execute(...).
> 
> And at that stage the batch is already parsed by `cql_parser` and split into separate `single_statement`s.
> 
> Reconstructing it back from the binary seems like not a wise idea.

I think this can be done reasonably easily from raw statements, while they exist.  But read on...

> 
> We could theoretically, modify cql_parser to store each query string in some string field of `single_statement` if Tracing is requested.

That's actually already happening:
https://github.com/scylladb/scylla/blob/scylla-4.2.rc4/cql3/cql_statement.hh#L65-L69

**Comment by vladzcloudius** [comment]
> > I'd assume that after that we eventually get to batch_statement::execute(...).
> > And at that stage the batch is already parsed by `cql_parser` and split into separate `single_statement`s.
> > Reconstructing it back from the binary seems like not a wise idea.
> 
> I think this can be done reasonably easily from raw statements, while they exist. But read on...

What I had in mind when I said that it's not wise was the reconstructed statement could be rather different from the original one (due to defaults and such). 
Since tracing is usually done to catch things in the code - this may harm usefulness of it significantly.


> 
> > We could theoretically, modify cql_parser to store each query string in some string field of `single_statement` if Tracing is requested.
> 
> That's actually already happening:
> https://github.com/scylladb/scylla/blob/scylla-4.2.rc4/cql3/cql_statement.hh#L65-L69

Hmmm... Based on Kostya's comment that was supposed to be working - but  @jul-stas was unable to see that. Julius, did you use the code with these bits?

**Comment by dekimir** [comment]
> > > I'd assume that after that we eventually get to batch_statement::execute(...).
> > > And at that stage the batch is already parsed by `cql_parser` and split into separate `single_statement`s.
> > > Reconstructing it back from the binary seems like not a wise idea.
> > 
> > I think this can be done reasonably easily from raw statements, while they exist. But read on...
> 
> What I had in mind when I said that it's not wise was the reconstructed statement could be rather different from the original one (due to defaults and such).

Raw statements are a high-fidelity representation of what was parsed.  But we quickly translate them into what you called "binary" above and continue working from that.  This may be why Julius wasn't able to see them.  Nevertheless, you might be able to trace the original query early on, while the raw statement still exists.

(I agree that the original CQL cannot be recreated faithfully from the "binary" representation.)

**Comment by vladzcloudius** [comment]
> > > > I'd assume that after that we eventually get to batch_statement::execute(...).
> > > > And at that stage the batch is already parsed by `cql_parser` and split into separate `single_statement`s.
> > > > Reconstructing it back from the binary seems like not a wise idea.
> > > 
> > > 
> > > I think this can be done reasonably easily from raw statements, while they exist. But read on...
> > 
> > 
> > What I had in mind when I said that it's not wise was the reconstructed statement could be rather different from the original one (due to defaults and such).
> 
> Raw statements are a high-fidelity representation of what was parsed. But we quickly translate them into what you called "binary" above and continue working from that. This may be why Julius wasn't able to see them. Nevertheless, you might be able to trace the original query early on, while the raw statement still exists.

@dekimir 
If we can make a raw_statement store the original CQL string - that would be nice.
That in particular can eliminate the need to store that `raw_cql_statement`.

> 
> (I agree that the original CQL cannot be recreated faithfully from the "binary" representation.)

**Comment by dekimir** [comment]
Sorry, I confused the discussion by talking about raw statements unnecessarily.  Let me restart with this claim: anything derived from `cql3::cql_statement` has the `raw_cql_statement` string available.  Therefore, most code under the `scylla/cql3/statements/` directory will let you include the original CQL string in the trace -- just use `this->raw_cql_statement`.

**Comment by vladzcloudius** [comment]
@dekimir 
This is not helping us for uprepared BATCH statements because it is going to contain the whole CQL BATCH string in this case.

Please, re-read my post here: https://github.com/scylladb/scylla/issues/7307#issuecomment-702977042

I wonder if it's too complicated to make CQL parser store singular queries strings somewhere in `single_statement` for instance.

This in particular would allow us to get rid of `raw_cql_statement` which I added back then for Tracing purposes as a quick hack.

**Comment by dekimir** [comment]
> I wonder if it's too complicated to make CQL parser store singular queries strings somewhere in `single_statement` for instance.

That would be difficult, because `single_statement` is prepared from `raw::modification_statement`, which doesn't have the original query string.  It's probably easiest to re-create the string from raw statements in various [`prepare_internal`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/scylladb/scylla%24+prepare_internal+type:symbol&patternType=regexp) overrides.

**Comment by vladzcloudius** [comment]
> > I wonder if it's too complicated to make CQL parser store singular queries strings somewhere in `single_statement` for instance.
> 
> That would be difficult, because `single_statement` is prepared from `raw::modification_statement`, which doesn't have the original query string. It's probably easiest to re-create the string from raw statements in various [`prepare_internal`](https://sourcegraph.com/search?q=repo:%5Egithub%5C.com/scylladb/scylla%24+prepare_internal+type:symbol&patternType=regexp) overrides.

This kind of change would require to modify the parser (lexer) so that it would store the single query sentence. 

These kind of things are usually not very hard if you wrote the lexer grammar. However it wasn't us who did it so I guess it's better not touch it... ;)

@jul-stas I suggest we drop it for now.
