### ISSUE TITLE
4.1: returns error "2 replica were required but only 1 acknowledged the write" on cluster that was just created

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla#7320]
*Installation details*
Scylla version (or git commit hash): 4.1.7-0.20200918.2251a1c577
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): https://www.googleapis.com/compute/v1/projects/debian-cloud/global/images/family/debian-9

*Steps to reproduce*
1. Create cluster of 4 nodes
2. Run cassandra-stress write no-warmup cl=QUORUM n=10100200 -schema 'replication(factor=3) compression=LZ4Compressor' -port jmx=6868 -mode cql3 native compression=lz4 -rate threads=1000 -pop seq=1..10100200 -log interval=5
3. Observe c-s failure with :
java.io.IOException: Operation x10 on key(s) [334c3035344c37373431]: Error executing: (WriteTimeoutException): Cassandra timeout during SIMPLE write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)

[db-log.zip](https://github.com/scylladb/scylla/files/5317586/db-log.zip)

Two logs have the following line in the log, other two don't have it:

```
scylla:  [shard 4] migration_manager - Create new Keyspace: KSMetaData{name=keyspace_entire_test, strategyClass=org.apache.cassandra.locator.SimpleStrategy, strategyOptions={replication_factor=3}, cfMetaData={}, durable_writes=1, userTypes=org.apache.cassandra.config.UTMetaData@0x60400870b098}
```

**Comment by slivne** [comment]
@dkropachev we need a nodetool status prior to the writes running to show the cluster is indeed fully up.

Can you please check this is the status in the logs before cassandra-stress starts to run

**Comment by roydahan** [comment]
It's a dup of known issues with debian9 rolling upgrade tests on GCE.
#5840
