### ISSUE TITLE
Alternator Streams test fails when building on clang

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7325]
@avikivity reported on the mailing list tha scylla built with clang (many unapplied patched needed) passes all unit tests except `alternator/run`, which has one failure - `test_streams_after_sequence_number`:
```
______________________ test_streams_after_sequence_number 
...
>                   assert len(response['Records']) == 1
E                   AssertionError: assert 2 == 1
E                    +  where 2 = len([{'dynamodb':
{'ApproximateCreationDateTime': datetime.datetime(2020, 10, 4, 13, 40,
8, tzinfo=tzlocal()), 'Keys':
{'c...d67e574682740000d1:f8de1e30-062d-11eb-6e12-418927c0cf0b',
'eventName': 'MODIFY', 'eventSource': 'scylladb:alternator'}])

test_streams.py:1019: AssertionError
```

I tried to explain the context of this test and the failure:

> This test checks Alternator Streams (i.e., CDC) . The test writes two items to the table, and reads two items from the stream. This part worked well. Then, it asks to read from the same stream again, but not from the start - it gives the sequence number of the first change, and asks to read *after* it. The result should be just one item, but for some reason we got two so the test failed.
>
> Calle, if I remember correctly, in the past we had a similar bug when your sequence number serialization/deserialization code had a bug and relied on some implied constructor which didn't do what you thought it did - maybe there is a similar bug in the clang build?
>
> The relevant code is probably in alternator/streams.cc, struct sequence_number, and possibly struct shard_iterator, e.g., shard_iterator::shard_iterator(const sstring& s, size_t i). I don't know how to debug it further in my mind without adding printouts and seeing whether the sequence number was printed wrong, parsed wrong, or what actually went wrong...

CC @elcallio

**Comment by avikivity** [comment]
Strangely, it works on clang 11. Could be a bug fixed in the compiler, or just a small perturbation with a big effect.

**Comment by slivne** [comment]
@avikivity not clear to me if we need to chase this or are we targeting to use Clang 11 ?

**Comment by avikivity** [comment]
I don't yet have an answer.

**Comment by nyh** [comment]
With clang now being the default, and most developers still using Fedora 22 and clang 10, this has become and urgent problem to fix :-(

**Comment by nyh** [comment]
The bug is in the constructor of `boost::multiprecisions::uint128_t` which we use in `sequence_number::sequence_number(std::string_view v)`. When this constructor takes a string_view, it outright generates the wrong response. When it takes an std::string, it generates the right response (and the test passes).

I'll try to think what is the least ugly way to work around this bug.

**Comment by elcallio** [comment]
I can verify this. But it makes very little sense, since the string_view routine `assign_from_string_view` just creates a new string and creates from it. Sounds like there is a weird string_view bug in clang 10?

**Comment by nyh** [comment]
What's "assign_from_string_view"?
Looking at the Boost code, it seems it only knows how to convert **null-terminated** strings. And a string_view isn't null terminated. I suspect that might be the problem, but am not really sure. I fi just change the constructor to take std::string(v) instead of v, everything works :-( I'm tempted to just send this as a patch and have a comment that this is a bug in clang 10.
Although, @elcallio, didn't you also have a very similar bug in gcc in the past?

**Comment by elcallio** [comment]
In my version of boost, the constructor looks like this: 
```
template <class Traits>
   explicit inline number(const std::basic_string_view<char, Traits>& view)
   {
      using default_ops::assign_from_string_view; 
      assign_from_string_view(this->backend(), view);
   }
```
with
```
template <class Result, class Traits>
inline void assign_from_string_view(Result& result, const std::basic_string_view<char, Traits>& view)
{
   // since most (all?) backends require a const char* to construct from, we just
   // convert to that:
   std::string s(view);
   result = s.c_str();
}

```

which is why I am somewhat perplexed here. 

I did have trouble with gcc calling the wrong constructor, which iirc is why it explicitly uses the string_view one here.

**Comment by avikivity** [comment]
Probably the bug is in boost, and the switch to Fedora 33 fixed it by updating boost to a version with the fix.

**Comment by elcallio** [comment]
Just an update: I did a debug run and verified that it is indeed almost exactly the reverse of the earlier gcc problem, namely the template guards around the number constructor:
```
template <class V>
   explicit BOOST_MP_FORCEINLINE BOOST_CONSTEXPR number(const V& v, typename boost::enable_if_c<
            detail::is_explicitly_convertible<typename detail::canonical<V, Backend>::type, Backend>::value
            && (detail::is_restricted_conversion<typename detail::canonical<V, Backend>::type, Backend>::value
                || !is_convertible<typename detail::canonical<V, Backend>::type, Backend>::value)
         >::type* = 0)
         BOOST_MP_NOEXCEPT_IF(noexcept(Backend(std::declval<typename detail::canonical<V, Backend>::type const&>())))
      : m_backend(canonical_value(v)) {}

```
not working properly, making the compiler use this instead of the actual string_view one. Converting to string calls not the string_view one, but 
```
template <class V>
   explicit BOOST_MP_FORCEINLINE number(const V& v, typename boost::enable_if_c<
            (boost::is_arithmetic<V>::value || is_same<std::string, V>::value || is_convertible<V, const char*>::value)
            && !detail::is_explicitly_convertible<typename detail::canonical<V, Backend>::type, Backend>::value
            && detail::is_restricted_conversion<typename detail::canonical<V, Backend>::type, Backend>::value
         >::type* = 0) 
         BOOST_MP_NOEXCEPT_IF(noexcept(std::declval<Backend&>() = std::declval<typename detail::canonical<V, Backend>::type const&>()))
   {
      m_backend = canonical_value(v);
   }

```
Which seems not very different. But the std::string is at least null terminated. So I think Avi is right. The flaw is really in the library and its type guards.

**Comment by nyh** [comment]
@elcallio I'm about to commit your patch (still testing it, taking ages to compile...), should I or do you have second thoughts about the commit message or comment you want?
Anyway, the problem *is* specific to clang to some degree, since on gcc, with the same library, it works correctly.

**Comment by elcallio** [comment]
It is descriptive enough. I am just adding this info to the issue for posterity so we have a record of it.

**Comment by avikivity** [comment]
@nyh please evaluate for backport.

**Comment by nyh** [comment]
@avikivity this is only needed with clang 10 on Fedora 32, to work around a bug in some specific combination of that clang and boost versions. Do any of the official releases (maybe 4.3) use this combination? I assume the answer is no, and if it's no, this does not need any backports.

Note that this bug causes a test to fail, so if it happens on some branch, we'll definitely notice it.

**Comment by nyh** [comment]
Not backporting. None of the earlier releases use clang.
