### ISSUE TITLE
Can't allocate memory

### ISSUE THREAD

**Issue by spyworldxp** [scylladb/scylla#733]
terminate called after throwing an instance of 'std::system_error'
  what():  : Cannot allocate memory
/start-scylla: line 12:     7 Aborted                 (core dumped) /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --options-file $HOME/scylla.yaml --listen-address $IP --rpc-address $IP --network-stack posix --smp 1

**Comment by benoit-canet** [comment]
Hello,

Can you try to limit the memory scylla is using with -m 512M for example ?

This option will take power of 2 as a memory limit.

Best regards

Benoît

**Comment by penberg** [comment]
@spyworldxp You're running the Docker image, right? Can you please post full log for the run?

**Comment by spyworldxp** [comment]
I fix the problem. It require swap partition.

**Comment by penberg** [comment]
@spyworldxp OK, good to know. Can you post the full log, though? There really shouldn't be any reason to *require* a swap partition. Perhaps Scylla is grabbing onto too much memory and not leaving enough for the kernel.

**Comment by avikivity** [comment]
What command did you use to start the docker container?

**Comment by slivne** [comment]
Please reopen when you have additional info
