### ISSUE TITLE
Start with docker on mac

### ISSUE THREAD

**Issue by dahankzter** [scylladb/scylla#734]
I am trying to start scylla using docker on mac for development purposes.
I am assuming it is because I have no proper hostname on my local wifi. Using the loopback gives the following error:

docker run -p 127.0.0.1:9042:9042 -i -t scylladb/scylla
scylla: core/resource.cc:165: std::vector<resource::cpu> resource::allocate(resource::configuration): Assertion `!remain' failed.
/start-scylla: line 12:     7 Aborted                 /usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --options-file $HOME/scylla.yaml --listen-address $IP --rpc-address $IP --network-stack posix --smp 1

docker --version
Docker version 1.9.1, build a34a1d5

Any idea how proceed. Really curious to take our app for a spin.

**Comment by penberg** [comment]
@dahankzter Which version of Scylla re you running?

@avikivity This seems to be another hwloc issue when running on Docker and OS X. Seastar tries to divide memory between CPUs and fails in ``resource::allocate()``.

**Comment by FGRibreau** [comment]
Same issue here on MacOSX with docker 1.8.2

**Comment by gembin** [comment]
Same issue on CentOS 7 with 512M memory, so dose it mean it will failed on any low memory machine, but not only using docker on Mac OSX ?

`scylla_run: scylla: core/resource.cc:269: resource::resources resource::allocate(resource::configuration): Assertion '!remain' failed.`

**Comment by avikivity** [comment]
Yes, it's not docker specific.
