### ISSUE TITLE
Alternator shards parent is not set very correctly

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#7346]
The code relies on the sort order of cdc streamid:s from query. Should 
a.) explicitly sort these so we can find token bounds
b.) Select parent so that it is the largest token < child token (i.e. start of range covering my range. (though this is somewhat beside the point).

**Comment by nyh** [comment]
@elcallio I didn't understand this issue. What code, and which query? What does a "parent shard" even mean in our implementation?

**Comment by nyh** [comment]
Not backporting. Alternator Streams does not yet exist in 4.2.
