### ISSUE TITLE
Alternator shard ID:s should be filtered by time 

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#7347]
Since we cannot have data read from any generation that expired more than 24h ago, nor any generation expired before the stream was created, we should filter out these generations from describe_streams.

Without this, we would get an ever larger, unbounded, set of shards as topology changes in the cluster.
Old code tries to do something like this, but looked at the wrong info (expired - never set - and not what we are looking for), and also was not very efficient.

**Comment by nyh** [comment]
Not backporting. Alternator Streams does not yet exist in 4.2.
