### ISSUE TITLE
relocatable scripts lack proper paths

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla#7350]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.1
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

@tarzanek
this command isn't working, I think it's not using the corrects PATH and the relocatable python, from within the scylla_prepare I think it does work
```
/opt/scylladb/scripts/perftune.py --tune net --nic eth0 --get-cpu-mask
```

- above binary is expecting to find hwloc in relocatable paths, but it's not finding it
within scylla-server service is most probably able to find it, but I think this command should work also as standalone

I am opening this bug as a placeholder to open a discussion (or get a fix) to get the tools from scylla work again even with relocatable binaries under different user than scylla (e.g. root)

**Comment by tarzanek** [comment]
rationale behind this is e.g. https://github.com/scylladb/scylla-ansible-roles/commit/7eb2b079b34ac50dca793592d8b89b909806ee44

so all automation scripts out there are basically impacted since we started rolling out relocatable binaries

**Comment by slivne** [comment]
I think we changed the scripts to use the relocatble folder and python3 - maybe we did not change all

**Comment by tarzanek** [comment]
I am only aware about perftune.py so far ...

**Comment by syuu1228** [comment]
That's because we are setting PATH for relocatable CLI tools on scylla_util.py, but perftune.py does not using it since it's not part of Scylla (it's from Seastar).
see: https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_util.py#L493

I guess we need to setup it on python3 thunk instead.

**Comment by avikivity** [comment]
Backported to 4.1, 4.2, 4.3.
