### ISSUE TITLE
Scylla does not start on Ubuntu because NOFILE rlimits check fails

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#738]
issue at boot with limits check
```
Dec 31 10:16:52 ip-10-13-199-53 scylla[11064]: EAL: TSC frequency is ~2800101 KHz
Dec 31 10:16:52 ip-10-13-199-53 scylla[11064]: EAL: Master lcore 0 is ready (tid=ba414440;cpuset=[0])
Dec 31 10:16:52 ip-10-13-199-53 scylla[11064]: EAL: lcore 7 is ready (tid=ad00f700;cpuset=[7])
Dec 31 10:16:52 ip-10-13-199-53 scylla[11064]: EAL: lcore 6 is ready (tid=ad810700;cpuset=[6])
Dec 31 10:16:52 ip-10-13-199-53 scylla[11064]: EAL: lcore 4 is ready (tid=ae812700;cpuset=[4])
Dec 31 10:16:52 ip-10-13-199-53 scylla[11064]: EAL: lcore 1 is ready (tid=b0015700;cpuset=[1])
Dec 31 10:16:52 ip-10-13-199-53 scylla[11064]: EAL: lcore 5 is ready (tid=ae011700;cpuset=[5])
Dec 31 10:16:52 ip-10-13-199-53 scylla[11064]: EAL: lcore 3 is ready (tid=af013700;cpuset=[3])
Dec 31 10:16:52 ip-10-13-199-53 scylla[11064]: EAL: lcore 2 is ready (tid=af814700;cpuset=[2])
Dec 31 10:16:52 ip-10-13-199-53 scylla[11064]:  [shard 0] config - Option partitioner is not (yet) used.
Dec 31 10:16:52 ip-10-13-199-53 scylla[11064]:  [shard 0] init - NOFILE rlimit too low (recommended setting 200000, minimum setting 10000; refusing to start.
Dec 31 10:16:53 ip-10-13-199-53 kernel: [8048420.000451] init: scylla-server main process (11057) terminated with status 1
```

```
cat /etc/security/limits.d/scylla.conf 
scylla  -  core     unlimited
scylla  -  memlock  unlimited
scylla  -  nofile   200000
scylla  -  as       unlimited
scylla  -  nproc    8096

root@ip-10-13-199-53:/home/ubuntu# su scylla -s /bin/bash
scylla@ip-10-13-199-53:/home/ubuntu$ ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 120241
max locked memory       (kbytes, -l) 64
max memory size         (kbytes, -m) unlimited
open files                      (-n) 1024
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 120241
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
scylla@ip-10-13-199-53:/home/ubuntu$ whoami
scylla
```

it seems something is broken in setting limits on ubuntu.

**Comment by benoit-canet** [comment]
Can't this be a system wide policy of restricting limits ? (see dmesg)

**Comment by penberg** [comment]
Looks like ``pam_limits`` is *disabled* in ``/etc/pam.d/su`` so the ``su`` command won't pick them up.

I'm not a Debian or Ubuntu exper there so ping @asias.

**Comment by penberg** [comment]
BTW, the Debian Wiki page on limits https://wiki.debian.org/Limits states that

> pam_limits is not used in /etc/pam.d/common-session and /etc/pam.d/common-session-noninteractive, so it won't be active for daemons

So I suspect that our packaging is simply faulty here. @asias @syuu1228

**Comment by asias** [comment]
Enable

session    required   pam_limits.so

In /etc/pam.d/su

ubuntu $ sudo su - scylla -s /bin/bash

scylla $ ulimit -n
200000

**Comment by slivne** [comment]
Following that if we do service scylla-server start will it work ?

Does our startup script do su and that is the issue ?

**Comment by asias** [comment]
No, it still does not work.

**Comment by asias** [comment]
I added 

session required pam_limits.so

to 

/etc/pam.d/common-session-noninteractive


'service scylla-server start', the ulimit check passes now.

**Comment by slivne** [comment]
Ok so do we need both changes or only one ?

**Comment by asias** [comment]
We only need the /etc/pam.d/common-session-noninteractive change

**Comment by benoit-canet** [comment]
It's very strange because it was also passing if I bumped the limit to
200004

**Comment by penberg** [comment]
@asias Yes, but is the ``/etc/pam.d/common-session-noninteractive`` really something we can do from the Ubuntu package?

**Comment by asias** [comment]
@benoit-canet 

I changed  

ubuntu@ip-10-167-73-195:/etc/security/limits.d$ cat scylla.conf
scylla  -  core     unlimited
scylla  -  memlock  unlimited
scylla  -  nofile   200016
scylla  -  as       unlimited
scylla  -  nproc    8096

to 20016. Without /etc/pam.d/common-session-noninteractive, scylla-server does not start.

**Comment by benoit-canet** [comment]
strange

**Comment by asias** [comment]
On Thu, Dec 31, 2015 at 8:49 PM, Pekka Enberg <notifications@github.com>
wrote:

> @asias <https://github.com/asias> Yes, but is the
> /etc/pam.d/common-session-noninteractive really something we can do from
> the Ubuntu package?
>

No. I don't think we should modify
 /etc/pam.d/common-session-noninteractive in scylla package. I will dig
more.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/738#issuecomment-168189019>.
>



-- 
Asias

**Comment by penberg** [comment]
@asias I think RabbitMQ, for example, uses ``/etc/default`` to set ulimit every time the server is started up. Apache does it in the ``apache2ctl` startup script.

**Comment by syuu1228** [comment]
Maybe we should do same way in /usr/lib/scylla/scylla_run?

**Comment by slivne** [comment]
for 0.14 we can have a workaround patch and then fix it in master in a
better way .... so what can we do ?

**Comment by asias** [comment]
On Thu, Dec 31, 2015 at 9:08 PM, Takuya ASADA <notifications@github.com>
wrote:

> Maybe we should do same way in /usr/lib/scylla/scylla_run?
>

It is better we do not mess up with /etc/pam.d thing.

I tried this /usr/lib/scylla/scylla_run

ulimit -n 300003
exec sudo -E -u $USER /usr/bin/scylla $args

It seems it is working.


—
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/738#issuecomment-168191760>.
>



-- 
Asias

**Comment by penberg** [comment]
@asias I'm certainly OK with that. Can you please send a patch? We can just drop the ``limits.d`` bits from Debian packaging for 0.15.

**Comment by syuu1228** [comment]
@asias Are you trying to send a patch for this? Otherwise I can handle this.

**Comment by slivne** [comment]
Takuya - if its simple send  a patch

**Comment by ikiarazm** [comment]
Hi all

*Installation details*
Scylla version: **Scylla-2.0** (from branch-2.0)
Cluster size: **1**
OS:  **Ubuntu 16.04-3**

I successfully clone and compile scylla-2.0. Also I copy `scylla.yaml` to `$HOME/scylla/conf` location as HACKING.md said(there is no `scylla.yaml` at `/etc/scylla`) and modify it as *Single Data Center* tutorial said.

But I got following error after running `./build/release/scylla` command.
```
Scylla version 2.0.0-0.20171013.ba02e26 starting ...
ERROR 2017-10-13 22:52:27,544 [shard 0] init - NOFILE rlimit too low (recommended setting 200000, minimum setting 10000; refusing to start.
ERROR 2017-10-13 22:52:27,544 [shard 0] seastar - Exiting on unhandled exception: std::runtime_error (NOFILE rlimit too low)
```
@penberg 
I think I have the same issue as this topic concern.
