### ISSUE TITLE
Simultaneous dropping of multiple tables caused stall detections and killed Scylla services

### ISSUE THREAD

**Issue by nikolay-toroptsev** [scylladb/scylla#7382]
Scylla version (or git commit hash): 4.1.0
Cluster size: 4 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 8

Platform (physical/VM/cloud instance type/docker): physical
Hardware: cores=20 hyperthreading=40 memory=128G
Disks: Nvme 4T encrypted. 1 disk per node

When we have dropped about 25 old tables, a lot of compaction of system tables started. This resulted in a heavy load on CPU and disk. Then stall detections were observed and ultimately on 3 out of 4 nodes the Scylla service was killed due to core dump error.

**Comment by nikolay-toroptsev** [comment]
[backtrace1.txt](https://github.com/scylladb/scylla/files/5359999/backtrace.txt)
[backtrace2.txt](https://github.com/scylladb/scylla/files/5360001/backtrace.txt)

**Comment by avikivity** [comment]
How many tables are remaining? And how many columns in total? (e.g. what does `SELECT count(*) FROM system_schema.columns` return?)

**Comment by avikivity** [comment]
Most likely this is the culprit:

```
class canonical_mutation {
    bytes _data;
```

If there are many columns in the database, they all get stuffed into one huge canonical_mutation here.

**Comment by nikolay-toroptsev** [comment]
> How many tables are remaining? And how many columns in total? (e.g. what does `SELECT count(*) FROM system_schema.columns` return?)

154 tables left. 6710 columns

**Comment by avikivity** [comment]
So, even if each column needed 100 bytes to describe it, and each table an extra 1k, that would still be less than 10MB. 

This can cause a stall, but shouldn't cause a crash. Still, should be fixed.

Do you have stack traces from the core dumps?

**Comment by nikolay-toroptsev** [comment]
> Do you have stack traces from the core dumps?
I'm afraid not. All we have left are logs:
```
Oct  9 13:37:47 prod-scylla004 systemd[1]: Created slice system-systemd\x2dcoredump.slice.
Oct  9 13:37:47 prod-scylla004 systemd[1]: Started Process Core Dump (PID 2383977/UID 0).
Oct  9 13:37:50 prod-scylla004 systemd-coredump[2383978]: Core file was truncated to 2147483648 bytes.
Oct  9 13:38:23 prod-scylla004 systemd-coredump[2383978]: Process 1791484 (scylla) of user 988 dumped core.#012#012Stack trace of thread 1791509:#012#0  0x00007fe4c4c5e625 n/a (n/a)
                                                                                   Stack trace of thread 1791509:
                                                                                   #0  0x00007fe4c4c5e625 n/a (n/a)
```
Folder /var/lib/systemd/coredump is empty

**Comment by slivne** [comment]
to allow coredumps to be written to /var/lib/scylla use scylla_coredump_setup (https://docs.scylladb.com/getting-started/system-configuration/#setup-scripts)

@nikolay-toroptsev if you can provide your schema (before the change) and the tables dropped and the specs of the machines we can try and reproduce this on our end locally to get additional information so we can fix this (follow the upload data explained in http://docs.scylladb.com/troubleshooting/report_scylla_problem/)

**Comment by slivne** [comment]
@nikolay-toroptsev hi - if you can provide the schema and what you did we can try and reproduce - if not I'll close the issue till we have a  bit more to work on to solve this.

**Comment by slivne** [comment]
closing this issue as its stale @nikolay-toroptsev if you can provide additional info we can reopen and chase this and fix it.
