### ISSUE TITLE
On clean ubuntu 20.04 image, scylla_setup fails on  '/dev/md0 is already using'

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#7383]
*Installation details*
Scylla version (or git commit hash): 4.1.7
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04
https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/family/ubuntu-2004-lts

Seem like /dev/md0 is already in used in those images, and there is no way to change this parameter vi `scylla_setup`
only if you call with `--no-raid-setup` and run `scylla_raid_setup` on you own

```
23:57:40  Command: 'sudo /usr/lib/scylla/scylla_setup --nic ens5 --disks /dev/nvme0n1,/dev/nvme0n2,/dev/nvme0n3,/dev/nvme0n4,/dev/nvme0n5,/dev/nvme0n6,/dev/nvme0n7,/dev/nvme0n8  --setup-nic-and-disks'
23:57:40  Exit code: 1
23:57:40  Stdout:
23:57:40  ntp-systemd-netif.service is a disabled or a static unit, not starting it.
23:57:40  Setting up libevent-core-2.1-7:amd64 (2.1.11-stable-1) ...
23:57:40  Setting up libevent-pthreads-2.1-7:amd64 (2.1.11-stable-1) ...
23:57:40  Setting up sntp (1:4.2.8p12+dfsg-3ubuntu4) ...
23:57:40  Processing triggers for systemd (245.4-4ubuntu3.2) ...
23:57:40  Processing triggers for man-db (2.9.1-1) ...
23:57:40  Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
23:57:40  8 Oct 20:57:22 ntpdate[26322]: adjust time server 91.189.91.157 offset -0.000273 sec
23:57:40  /dev/md0 is already using
```

**EDIT**:
I know we don't have an official support for this version, let's call it a heads up :), since we were trying it anyhow

**Comment by syuu1228** [comment]
Okay I found the problem.

We currently using /dev/md0 existence check to detect existing MDRAID volume, but on Ubuntu 20 GCE image there is /dev/md0 even it's unused:

```
syuu@takuya-ubuntu201:~$ ls /dev/md0 
/dev/md0
syuu@takuya-ubuntu201:~$ cat /proc/mdstat 
Personalities : 
unused devices: <none>
```

I think we should use /proc/mdstat or mdadm instead.

**Comment by avikivity** [comment]
Won't backport as this is hard to validate in all cases.

**Comment by avikivity** [comment]
Backported to 4.3 as much time has passed.
