### ISSUE TITLE
Alternator stream shards must be reported in lexicographically sorted order. 

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#7409]
While never specified, this is assumed and required by the kinesis adapter, which wholly ignores the "lastevaluatedshardid" field, and just looks at - not the last sent - but the last sent as sorted - shard in list.

This happened to work before, but was broken by me in the parent-management PR.

**Comment by elcallio** [comment]
I will change my evaluation. This was already broken, and if it ever worked it was more pure luck.

**Comment by nyh** [comment]
Not backporting. Alternator Streams does not yet exist in 4.2.
