### ISSUE TITLE
Replacing node should not be marked as alive without the replacing node take writes series

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#7419]
Please consider reverting commit 38d4015 from 4.0 branch (which does not have the full series: storage_service: Make replacing node take writes), it will mark the replacing node as UP so that the replacing node using the same IP address of the node to be replaced will be considered as a target to serve CQL read  which is wrong.

The commit 38d4015 should be backported together with the full "storage_service: Make replacing node take writes" patch set.

**Comment by bhalevy** [comment]
Also you wrote above:
> it will mark the replacing node as UP so that the replacing node using the same IP address of the node to be replaced will be considered as a target to serve CQL read which is not wrong.

I'm confused. If it's not wrong what is the problem then?

Can you describe the problem in the issue title rather than the proposed solution?

**Comment by asias** [comment]
> Also you wrote above:
> 
> > it will mark the replacing node as UP so that the replacing node using the same IP address of the node to be replaced will be considered as a target to serve CQL read which is not wrong.
> 
> I'm confused. If it's not wrong what is the problem then?
> 
> Can you describe the problem in the issue title rather than the proposed solution?

It is a typo. I updated it. 

Replacing node should NOT take read.

**Comment by slivne** [comment]
@avikivity this is the issue for reverting the code related to 4.0

**Comment by avikivity** [comment]
self-ping

**Comment by slivne** [comment]
@avikivity ping

**Comment by asias** [comment]
Closing. The fix storage_service: Make replacing node take writes and friends are already in master for a long time.

**Comment by avikivity** [comment]
7d86a3b208659e92489216e71df13fb33b1a4c3a for reference.
