### ISSUE TITLE
Remove row comparators from mutation_partition

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#742]
Currently `mutation_partition` stores two copies of the clustering key comparator, once in `mutation_partition::_rows` and once in `mutation_partition::_row_tombstones`.  This duplication happens for every row, so if 1G partitions are stored, we have 2G comparators.

We could eliminate this by storing a plain (unsorted) tree instead of a `boost::intrusive::set<>`, and using `boost::intrusive::bstree_algorithms` to manage the tree. Realistically, we should switch the tree to an btree (or other n-ary) tree first.

**Comment by avikivity** [comment]
`boost::intrusive::bstree` can serve as the container; as long as it's managed by algorithms that balance it, it will provide the same guarantees.

**Comment by duarten** [comment]
Since we have to determine the insertion point either way, could we just use a vector of pointers and do a binary search over that? We could even store managed_ptrs and use LSA for range tombstones.

**Comment by avikivity** [comment]
A vector of pointers has O(N) insertion cost vs O(log N) for bstree.

**Comment by avikivity** [comment]
btw, using a union { vector, bstree } is a good idea for small N (and we use the optimization for storing columns in rows; and should use it for rows and tombstones)

**Comment by haaawk** [comment]
I had some spare time during the weekend and cooked up this:
https://github.com/scylladb/seastar-dev/commits/haaawk/742
It turned out to be bigger than I was expecting.
Please take a look and let me know what you think.
If it seems ok then I can prepare a change that uses intrusive_set2 in range_tombstone_list as well.

**Comment by penberg** [comment]
The patch series was reverted from master in commit https://github.com/scylladb/scylla/commit/1d9ee358f11b8299045eabfcb373d1a22558030f so I'll reopen the issue.
