### ISSUE TITLE
AWS kinesis expects SequenceNumbers to be bigint comparable (growing)

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#7424]
Since out stream positions are timeuuids, their bits (views as 128 bits unsigned or whatnot), is _not_ the sort order. Timeuuid msb is somewhat weirdly mangled (see UUID_gen.hh), and thus comparing them like this will potentially run into cases where we report two sequentially growing sequence numbers that kinesis will read as out-of-order. 

We can work around this by de-mangle the msb when converting the values in alternator streams. Since timeuuid sorting is still sort by tuple(time, random lsb), we can reconstruct the time|lsb 128bit int instead.

**Comment by nyh** [comment]
Not backporting. Alternator Streams does not yet exist in 4.2.
