### ISSUE TITLE
Scylla to install node_exporter 1.0 or higher with scylla releases 

### ISSUE THREAD

**Issue by eyalgutkind** [scylladb/scylla#7427]
Today we ship Scylla with node_exporter 0.17.
The official supported node_exporter versions are 1.0.x 
Let's upgrade the released versions.

**Comment by tzach** [comment]
@amnonh FYI
We need to validate latest exporter with Scylla Monitoring

**Comment by amnonh** [comment]
@tzach I already did and it works fine, we should also move to install from packages where possible

**Comment by tzach** [comment]
To validate: node_exporter  1.0.x and 0.17 a re compatible, and no change is required on the monitoring side?
If this is the case, is it just
https://github.com/scylladb/scylla/blob/master/dist/common/scripts/node_exporter_install#L30

**Comment by amnonh** [comment]
@tzach yes, at least for the metrics that we use they are compatible.
About the installation, as node_exporter is GA now, it's better to use packages, but just downloading a newer version would work just the same

**Comment by slivne** [comment]
I do not think we have a dependency on node-exporter today - we install it in scylla_setup.


- We can consider changing that and making it a dependency - that will force installing node-exporter.
- We can maybe consider not starting it, so the depedency will force install it, but will not enable / install a service that starts it

@amnonh 

Users that use DataDog how do they monitor OS Metrics - I expect they use some DataDog agent and not necessarily node_exporter.

Lets make sure we have a solution also for offline-installer

**Comment by amnonh** [comment]
we can keep it optional but still install from packages instead of downloading it. I'm not sure what is better.

Data dog users have their own agent, which is a good point for why we should keep it optional in the setup.

**Comment by tzach** [comment]
Lets not mix two features here.
This issue is about upgrading exporter, and we can do that
We already have an issue about node_exporter packaging #2190

**Comment by avikivity** [comment]
Not a regression, not backporting.
