### ISSUE TITLE
sstable::create_links does not clean up after itself on error

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7429]
This issue is split off of #5714, focusing on `create_links` error handling.

As mentioned in a4d8e99f1cef421974840b9852b1d319a4172291 FIXME comment if `link_file` fails on any of the components (e.g. when running out of space) the function returns the error but it does not clean up after itself, leaving a mess behind that requires human intervention, since retrying the link operation will fail.

**Comment by bhalevy** [comment]
Patchset `[scylladb-dev] [PATCH v1 00/10] sstables: make move_to_new_dir idempotent` was sent to the ML, fixing this issue.

**Comment by avikivity** [comment]
Not a regression, rare error, not fatal, so not backporting.

**Comment by bhalevy** [comment]
@avikivity the issue prevents nodes that experienced a crash from starting when move from staging hits the remainders of partially moved sstables.  This is seen in the field.

**Comment by slivne** [comment]
@bhalevy was this backported to 2021.1  ?

**Comment by bhalevy** [comment]
> @bhalevy was this backported to 2021.1 ?

No, 5b312a123873050819395067ed910ea89d92181a was merged in 4.4 and it was decided not to backport it (see https://github.com/scylladb/scylla/issues/7429#issuecomment-735384398)
