### ISSUE TITLE
CDC log should include an end of record marker

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#7435]
Since a CDC "event" is broken up into potentially several log rows, each representing a sub-modification or pre/post state of a given change/source mutation, a reader cannot really be sure if he has actually read a full event unless he explicitly sees the next timestamp set being. 

Combined with paging and query limits this makes it more difficult to implement a CDC reader/translator without resorting to over-reads and/or stateful caching between calls. 

By adding an end-of-row marker to the last row in a given timestamp group we can always know if we are in fact at an event boundary, even if we don't have "row spill" to check, which makes it easier to write a forward-only reader/translator.

**Comment by nyh** [comment]
This patch did not reach the 4.3 branch. It introduces a change to the schema, so I think we must backport it to the 4.3 branch so it will be included in the GAed release in 4.3.0

**Comment by nyh** [comment]
Backported to next-4.3 (46ea8c9b8b067ccebacb1a3be020c3c8068dc684).
