### ISSUE TITLE
request to add a minimum of swap

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#7451]
*Installation details*
Scylla version (or git commit hash): latest master: dfe4161e6597664f2e99d59ab3d28ede81af3e3d
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

Quote from Shlomi:
```
Lets go ahead with the current calculation of what avi agreed on (what is committed)

I would have preferred to have a minimum of swap - e.g.  a 2 GB machine may need more than 700M of swap - 

Part of the reason to add swap was nodetool/jmx going crazy with memory allocation and we fixed that.
```

related doc: https://docs.scylladb.com/faq/#do-i-need-to-configure-swap-on-a-scylla-node

/CC @syuu1228 @slivne @roydahan

**Comment by penberg** [comment]
Where should this thing be added to? `scylla_swap_setup`?

/cc @syuu1228

**Comment by slivne** [comment]
4.3 images include a swap 

scylla_swap_setup

```
        # Scylla document says 'swap size should be set to either total_mem/3 or
        # 16GB - lower of the two', so we need to compare 16g vs memtotal/3 and
        # choose lower one
        # see: https://docs.scylladb.com/faq/#do-i-need-to-configure-swap-on-a-scylla-node
        swapsize = GB(16) if GB(16) < int(memtotal / 3) else int(memtotal / 3)
```

Lets see if that holds - if not we can change it - closing the issue
