### ISSUE TITLE
Has_conditions not set in modification_statement during validation

### ISSUE THREAD

**Issue by StarostaGit** [scylladb/scylla#7459]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

### Description

Method `modification_statement::has_conditions()` returns false for statement `UPDATE ks.lwt_with_static SET s = 1 WHERE a = 1 IF s = NULL;` in method `modification_statement::validate()`. This is either a bug or very counter-intuitive.
The above table was created as follows: `CREATE TABLE ks.lwt_with_static (a int, b int, s int static, d text, PRIMARY KEY (a, b));
` and there were no other commands executed.

**Comment by haaawk** [comment]
FYI @kostja

**Comment by kostja** [comment]
I think you should add a test case. The code is pretty straightforward (discounted for the general messiness of statements hirerarchy), set a breakpoint to prepare_conditions(), it should be called.

**Comment by haaawk** [comment]
From what I understood, @StarostaGit has added a line that prints out the value of stmt.has_conditions() in validate() and for the statement mentioned above it printed false. Should it print true @kostja ?

**Comment by haaawk** [comment]
@StarostaGit what I'm observing is the following:
1. I added a print:
```
diff --git a/cql3/statements/modification_statement.cc b/cql3/statements/modification_statement.cc
index 6e83bd00f..2acbb8f08 100644
--- a/cql3/statements/modification_statement.cc
+++ b/cql3/statements/modification_statement.cc
@@ -514,6 +514,7 @@ modification_statement::prepare_conditions(database& db, const schema& schema, v
 
 void
 modification_statement::validate(service::storage_proxy&, const service::client_state& state) const {
+    std::cerr << "haaawk " << has_conditions() << std::endl;
     if (has_conditions() && attrs->is_timestamp_set()) {
         throw exceptions::invalid_request_exception("Cannot provide custom timestamp for conditional updates");
     }
```
2. I executed `UPDATE ks.lwt_with_static SET s = 1 WHERE a = 1 IF s = NULL;` once and got:
```
haaawk 1
haaawk 1
haaawk 0
haaawk 0
haaawk 0
haaawk 0
```
when the result of the statement was:
```
 [applied] | s
-----------+------
      True | null
```
3. I executed the same statement again and I observed:
```
haaawk 1
haaawk 1
```
when the result of the statement was:
```
 [applied] | s
-----------+---
     False | 1
```


**It seems that at least some statements generated by this CQL return true from has_conditions()**

**Comment by StarostaGit** [comment]
@haaawk it seems you're right, I think I might have looked at the wrong statement. There are additional statements generated after the initial one that are not conditional and when I printed them out, they are indeed not the original UPDATE - that one is recognized as conditional.

I'm going to close the issue then as it looks like it's working.
