### ISSUE TITLE
compaction: implement maximum I/O bandwidth limiter 

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#7461]
*Installation details*
HEAD:  6c133e36d851cf64682438922a02d545f410975b

*Description*
Our current implementation allows compaction to consume all available resources.
As a result the rest of contexts may become saturated and go as as slow as the compaction, e.g. during the bootstrapping.

Many times however we care much more about "other" contexts to complete as soon as possible than for a compaction to achieve its equilibrium.

Another situation when our current design doesn't work well is when I/O becomes a bottleneck and especially when a number of I/O queues is less than the number of shards.

In this case I/O requests may begin piling up in the I/O HW queue and this would cause a significant negative impact of a query-related I/O latency that would translate into the request latency.  

The problem is caused by a fact that a compaction is a "perfect producers" of I/O while query has more bursty I/O pattern because scylla strives to keep data in memory as much as possible (cache and memtables). 

As a result I/O queue is going to be dominated by compaction I/O tasks and when HW is close to its limits query latency is going to be the worst possible.

*Proposal*
Limit the maximum I/O bandwidth for background I/O consumers like compaction and streaming (separate limits): may be in percents of the total or in the MB/sec.
 
This would allow the user to configure the maximum negative impact of the background I/O consumers on the CQL latency.

**Comment by vladzcloudius** [comment]
@eyalgutkind @asias @raphaelsc FYI

**Comment by denesb** [comment]
Won't this result in endless tuning cycles? I seem to remember that we wanted to have a latency/throughput switch. In latency mode, the seastar would not give 100% of the I/O capacity to background work and would instead reserve some fraction of if for foreground work (queries).

**Comment by vladzcloudius** [comment]
> Won't this result in endless tuning cycles? 

This would result in a very finite tuning cycle, @denesb.

> I seem to remember that we wanted to have a latency/throughput switch. In latency mode, seastar would not give 100% of the I/O capacity to background work and would instead reserve some fraction of if for foreground work (queries).

And how much would it give? What would that number be based on? I don't see a good working solution that would make it good for any possible use case in the nearest future.

However implementing this proposal doesn't conflict with working on what you described above.
The moment there is a good working automagical solution we would stop using a static limit and switch to that.

In the mean time this proposal gives us a good-enough solution.

**Comment by vladzcloudius** [comment]
The more I think about it the more my idea and what we already have resembles me what is already implemented in `systemd`.

I'll open a separate issue.

**Comment by slivne** [comment]
@raphaelsc  / @bhalevy  offline strategy is addressing the need of throtelling compactions while streaming data to a new node - we are going to compact the staged files and move them once - right ?

**Comment by vladzcloudius** [comment]
> @raphaelsc / @bhalevy offline strategy is addressing the need of throtelling compactions while streaming data to a new node - we are going to compact the staged files and move them once - right ?

@slivne note that this issue has a much wider scope than just taming compactions during bootstrapping. We have just as heavy problem with a compaction during a regular operation.

**Comment by xemul** [comment]
bfc521ee9c2ba16fc4a15e68c21f68300658f530
