### ISSUE TITLE
Incrementally delete resharded sstables as they're retired

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7463]
As discussed in https://github.com/scylladb/scylla/issues/7439#issuecomment-712681929, we should be able to delete retired sstables after we reshard them and not wait for the end of the whole resharding compaction.

**Comment by bhalevy** [comment]
The benefits are quite obvious - reducing temporary space requirements, number of open files, and read amplification.

**Comment by raphaelsc** [comment]
That's a regression AFAICT

**Comment by raphaelsc** [comment]
4.2 blocker?

**Comment by raphaelsc** [comment]
not a 4.2.0 blocker according to @slivne, but we can fix it for 4.2.1.

NOTE: users can no longer rely on old resharding space requirement until we fix this, because now resharding requires 50% of extra space

**Comment by raphaelsc** [comment]
cooking a patch...

**Comment by bhalevy** [comment]
> 4.2 blocker?

As discussed with @slivne, this issue is not a 4.2 blocker,
202bc6f3871355580d3a5a8816ce571bda183260 will fix this issues and should be backported to 4.2

**Comment by avikivity** [comment]
Backported to 4.2. According to evaluation above, no previous branch is vulnerable.
