### ISSUE TITLE
'nodetool status' is broken

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#747]
scylla HEAD: f26a75f48b159fd22fd3be1bd38a83c427036f62
scylla-tools-java HEAD: 7e5bd9e000fa01fd858c462902916b9be8588a96

Brought up a cluster with 5 Nodes at 192.168.122.11-15

```
nodetool  -h 192.168.122.11 status
error: null
-- StackTrace --
java.lang.ClassCastException
```

**Comment by dorlaor** [comment]
Did it work before you had 5 nodes? Are you sure the jmx service and scylla are running?

**Comment by vladzcloudius** [comment]
On 01/04/2016 05:57 PM, Dor Laor wrote:
>
> Did it work before you had 5 nodes?
>

I always had 5 nodes. It worked a week ago.

> Are you sure the jmx service and scylla are running?
>

Yes, I'm sure. It doesn't work on my laptop with a single node as well.

**Comment by asias** [comment]
Is it because the sculla-jmx in your jepsen container is out of date?

**Comment by penberg** [comment]
@asias Seems likely. @vladzcloudius I am not able to reproduce here with Scylla master.

**Comment by vladzcloudius** [comment]
On 01/05/2016 10:09 AM, Pekka Enberg wrote:
>
> @asias <https://github.com/asias> Seems likely. @vladzcloudius 
> <https://github.com/vladzcloudius> I am not able to reproduce here 
> with Scylla master.
>

@asias, @penberg - it's quite the possibility regarding the container, 
however the command didn't work on my laptop as well (will a different 
trace though) and I have all things up to date.
I'm checking the issue with Amnon now. I'm sure will get to the core...;)

**Comment by vladzcloudius** [comment]
The issue is void. The problem was caused by an inappropriate version of a nodetool.
The issue may be closed.
