### ISSUE TITLE
Use CDC "end of record" marker in Alternator Streams

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7496]
In issue #7435 fixed by commit 46ea8c9b8b067ccebacb1a3be020c3c8068dc684, we added to CDC an "end of record" marker (a boolean column) which can allow the CDC log reader to make sure that it got the full change (composed of multiple rows in the log). 
The CDC log reader in Alternator Streams should make use of this new flag, to avoid returning to the reader of the Alternator Stream a change event based on partial information.  

CC @elcallio

**Comment by avikivity** [comment]
@nyh please evaluate for backport.

**Comment by nyh** [comment]
Backported to next-4.3 (commit 21bef3b62de3d9a01ef40b81fa3cb70695a59f33).
Earlier releases were not backported the commit this depends on, so no need to backport this either.
