### ISSUE TITLE
cdc code linearizes all values

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#7506]
CDC uses `bytes` and `bytes_view` exclusively when dealing with cells and their values, linearising everything indiscriminately. This will produce stalls and `std::bad_alloc`:s and OOM crashes as soon as somebody starts using it with larger values. Although we don't recommend users to use large cells, cell values as large as >1GB are known to exist and values in the orders of MB can be quite common.

**Comment by denesb** [comment]
Found while working on the 2020 Summit Hackaton, on a project which involves getting rid of linearization.

**Comment by avikivity** [comment]
Performance only, not backporting.
