### ISSUE TITLE
relocatable package contains debug binaries

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla#7511]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.2
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

It looks like debug and normal relocatable .tgz package contain same files:

```
--- /tmp/pkg	2020-10-29 23:56:31.374561914 +0100
+++ /tmp/dbg	2020-10-29 23:57:46.325307830 +0100
@@ -557,6 +557,7 @@
 scylla/libreloc/libssl.so.1.1
 scylla/libreloc/libc.so.6
 scylla/libreloc/libgcc_s.so.1
+scylla/libreloc/libubsan.so.1
 scylla/libreloc/libstdc++.so.6
 scylla/libreloc/libsystemd.so.0
 scylla/libreloc/libm.so.6
@@ -596,6 +597,7 @@
 scylla/libreloc/libboost_program_options.so.1.69.0
 scylla/libreloc/libboost_system.so.1.69.0
 scylla/libreloc/libthrift-0.13.0.so
+scylla/libreloc/libasan.so.6
 scylla/libexec
 scylla/libexec/lsblk
 scylla/libexec/hwloc-calc
```

when checking binaries in http://downloads.scylladb.com/downloads/scylla/relocatable/scylladb-4.2/
http://downloads.scylladb.com.s3.amazonaws.com/downloads/scylla/relocatable/scylladb-4.2/scylla-package-4.2.0-0.20201025.94597e38e2.tar.gz
versus
http://downloads.scylladb.com.s3.amazonaws.com/downloads/scylla/relocatable/scylladb-4.2/scylla-debug-package-4.2.0-0.20201025.94597e38e2.tar.gz

so it looks like the debug package should contain debug scylla and normal package normal scylla

@penberg @yaronkaikov

**Comment by amoskong** [comment]
@tarzanek the `scylla-debug` is "Scylla debug-mode packages", not scylla-debuginfo package.

**Comment by penberg** [comment]
@tarzanek Yes, the "scylla-debug-package.tar.gz" is `scylla` built in debug mode. The `scylla-package.tar.gz` is `scylla` built in release mode, but it should include debug symbols.

What problem are you having?

**Comment by tarzanek** [comment]
the problem is that the tar.gzs are completely the same, it's a report from a customer that we ship the same .tgzs ;-)
(while for rpm the sizes of scylla binary differ a lot when you compare debug package and normal package)

**Comment by avikivity** [comment]
How can they be the same? the diff reported about shows they are not the same.

Please be very detailed, we're going back and forth and not making progress.

**Comment by tarzanek** [comment]
sorry, what I was saying is that basically the small difference is unexpected
what was expected was that scylla binary will be different similar to rpm package

but if this is by design, then please close, I just lack info how the classic relocatable package and debug relocatable package should look like

also if debug relocatable diffs just by those 2 small libs, why package all the rest?
the duplication is obvious here, so someone with design knowledge should validate this and either close this, or fix the building of package

**Comment by avikivity** [comment]
> sorry, what I was saying is that basically the small difference is unexpected
> what was expected was that scylla binary will be different, similar to how we package rpm

I expect the scylla binary to be different too. Is it the same? Comparing the file name is not the same thing as comparing its contents.

Try unpacking the debug and release tarballs and running sha1sum on both binaries.

> 
> but if this is by design, then please close, I just lack info how the classic relocatable package and debug relocatable package should look like
> 
> also if debug relocatable diffs just by those 2 small libs, why package all the rest?

I don't understand the question. Both the debug version and the release version need a bunch of files. The debug version needs, in addition, two more libraries.

> the duplication is obvious here, so someone with reloc package design knowledge should validate this and either close this, or fix the building of either normal or debug package (or both :-) )

**Comment by tarzanek** [comment]
this bug is actually quite funny and doesn't make much sense to me (my expectations):
for
```
scylla-debug-package-4.2.0-0.20201025.94597e38e2.tar.gz
_prod/scylla-package-4.2.0-0.20201025.94597e38e2.tar.gz
```
if I do:
```
diff -r  _prod/scylla/ scylla/
Binary files _prod/scylla/libexec/iotune and scylla/libexec/iotune differ
Binary files _prod/scylla/libexec/scylla and scylla/libexec/scylla differ
Only in scylla/libreloc: libasan.so.6
Only in scylla/libreloc: libubsan.so.1
% bg:0 Mon Nov 16,11:08 taz@tublat:~/foo
➜  foo ls -lah _prod/scylla/libexec/scylla
-rwxr-xr-x 1 taz taz 2.6G Oct 25 08:41 _prod/scylla/libexec/scylla
% bg:0 Mon Nov 16,11:09 taz@tublat:~/foo
➜  foo ls -lah scylla/libexec/scylla
-rwxr-xr-x 1 taz taz 2.5G Oct 25 09:04 scylla/libexec/scylla
```

So prod scylla binary is bigger than debug scylla (compression to blame?)

as said, if above is OK, then I don't have any problems with it (since most my expectations come from rpm and it seems most of them are not valid)

So I guess this can be closed, if nothing it will at least be a documentation for any other user that will be confused by sizes of relocatable packages.
