### ISSUE TITLE
Make sure that secondary indexes created before 3.2 have their `idx_token` column correctly marked as computed

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#7515]
Before 3.2, the `idx_token` column was a special case column, computed on the go from the values of the partition key. Since 3.2, this computation was abstracted to a notion of computed columns. We should make sure that each secondary index created before the change has its schema correctly updated, i.e. its `idx_token` column must be properly marked as computed.

**Comment by avikivity** [comment]
Backported to 4.1, 4.2, 4.3.
