### ISSUE TITLE
select count(*) with limit rows does not limit the result and return strange results

### ISSUE THREAD

**Issue by aloneldi** [scylladb/scylla#752]
--------------------
cassandra 2.1 
---------------------

Total Rows :+1: 
cqlsh:ycsb> select count(*) from usertable ;

 count
-------
  1000

(1 rows)
cqlsh:ycsb> select count(*) from usertable limit 2;

 count
-------
     2

(1 rows)

Scylla DB (cylla-server-0.14-20160104.88d544e.fc22.x86_64)
---------------

1 ) Total Rows :

cqlsh:ycsb> select count(*) from usertable ;

 count
-------
  1000

(1 rows)

2 ) with limit :

cqlsh:ycsb> select count(*) from usertable limit 50;

 count
-------
  1000

(1 rows)
cqlsh:ycsb> select count(*) from usertable limit 2;

 count
-------
   559

(1 rows)

**Comment by elcallio** [comment]
I cannot per sé repro this with newest scylla, but I did otoh find another bug (in aggregate query paging), and also what could potentially cause something like the above; We don't properly cap row count in post processing when page size is less than limit. 
Patches sent.

**Comment by tzach** [comment]
Fail to reproduce as well
```
cassandra-stress write n=10000 no-warmup -rate threads=10
cqlsh> select count (*) from keyspace1.standard1;

 count
-------
 10000

cqlsh> select count (*) from keyspace1.standard1 limit 2;

 count
-------
     2

cqlsh> select count (1) from keyspace1.standard1 limit 1;

 count
-------
     1

cqlsh> select count (1) from keyspace1.standard1 limit 10000000;

 count
-------
 10000
```

**Comment by tzach** [comment]
This issue is more tricky than I thought!

After running 
```
cassandra-stress write n=100000 -rate threads=10 -node x.x.x.x
```

Got the following inconsistent results
```
select count (*) from keyspace1.standard1 limit 100;

 count
-------
 40073

(1 rows)
cqlsh> select count (*) from keyspace1.standard1 limit 200;

 count
-------
   200

(1 rows)
```

while limit 200 seems to work, limit 100 return a higher number.

**Comment by elcallio** [comment]
The above does not reproduce for me. I get the expected results. 
Are you running this on a cluster or a single machine?

**Comment by tzach** [comment]
Cluster of 3 scylla 0.15 ami

**Comment by elcallio** [comment]
Ok, in cluster, somehow this breaks when using limit <= page size.

**Comment by elcallio** [comment]
Duh, row limit <= page size -> no paging is done. However, since this is an aggregate query we really should page it anyhow (if for no other reason so to avoid having to implement the same row limiting logic more than once).
