### ISSUE TITLE
Failed to load view build progress: std::bad_optional_access in interrupt_build_process_with_resharding_max_to_half_test

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7527]
Seen in https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/dtest-release/2/testReport/materialized_views_test/TestMaterializedViews/interrupt_build_process_with_resharding_max_to_half_test/
```
Unexpected errors found: [('node2', ['ERROR 2020-11-01 18:52:38,365 [shard 13] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)'
```

The errors can be seen in context in https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/dtest-release/2/artifact/logs-release.2/1604256811225_materialized_views_test.TestMaterializedViews.interrupt_build_process_with_resharding_max_to_half_test/node2.log but that doesn't seem to help much without a backtrace.
```
INFO  2020-11-01 18:52:38,347 [shard 0] init - starting the view builder
ERROR 2020-11-01 18:52:38,361 [shard 3] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
ERROR 2020-11-01 18:52:38,361 [shard 1] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
ERROR 2020-11-01 18:52:38,362 [shard 4] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
ERROR 2020-11-01 18:52:38,362 [shard 10] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
ERROR 2020-11-01 18:52:38,364 [shard 11] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
ERROR 2020-11-01 18:52:38,364 [shard 6] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
ERROR 2020-11-01 18:52:38,364 [shard 0] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
ERROR 2020-11-01 18:52:38,364 [shard 9] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
ERROR 2020-11-01 18:52:38,364 [shard 8] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
ERROR 2020-11-01 18:52:38,364 [shard 5] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
ERROR 2020-11-01 18:52:38,365 [shard 12] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
ERROR 2020-11-01 18:52:38,365 [shard 13] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
ERROR 2020-11-01 18:52:38,365 [shard 7] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
ERROR 2020-11-01 18:52:38,365 [shard 14] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
ERROR 2020-11-01 18:52:38,365 [shard 15] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
ERROR 2020-11-01 18:52:38,367 [shard 2] system_keyspace - Failed to load view build progress: std::bad_optional_access (bad optional access)
INFO  2020-11-01 18:52:38,367 [shard 0] view - Building view ks.t_by_v2, starting at token minimum token
ERROR 2020-11-01 18:52:38,369 [shard 0] view - Error applying view update to 127.0.67.3: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
WARN  2020-11-01 18:52:38,369 [shard 0] view - Error executing build step for base ks.t: exceptions::unavailable_exception (Cannot achieve consistency level for cl ONE. Requires 1, alive 0)
...
INFO  2020-11-01 18:52:54,814 [shard 0] view - Finished building view ks.t_by_v2
```

**Comment by bhalevy** [comment]
Scylla version bbef05ae3cc7813db0898429300afa5d476f84a8

**Comment by bhalevy** [comment]
@psarna please look into this issue

**Comment by psarna** [comment]
This failure is observed because getting the view progress is an internal CQL query, and later it does:
```cpp
            auto ks_name = row.get_as<sstring>("keyspace_name");
            auto cf_name = row.get_as<sstring>("view_name");
            auto first_token = dht::token::from_sstring(row.get_as<sstring>("first_token"));
```
, which assume that these columns have values (get_as internally unpacks an optional). It's of course possible for them to *not* contain values, which means that view building progress cannot be extracted, but this case is already handled - the view builder just assumes that there's no progress and the building must start from scratch. So, in short, I think that there are two solutions:
* downgrade this message to `.warn`, because it's not fatal at all
* ignore this message in tests.

I'm fine with both solutions, but maybe the first one makes sense, since this situation is totally recoverable and may needlessly scare the user.

**Comment by bhalevy** [comment]
@psarna I favor degrading the log level to WARN too since it's not fatal and the view building will be retried.
Also, if `first_token` can be missing under normal circumstances, how about checking that before calling `get_as<sstring>`, or alternatively catch and handle the std::bad_optional_access exception and produce a more user friendly warning (ideally printed once at the highest layer)?

**Comment by psarna** [comment]
@bhalevy I posted a fix which just degrades to warning because I had it ready for a while and just forgot to push it earlier. Adding a more user friendly text also makes sense, although once it becomes a warning and not an error, it won't usually be interesting to know which field was missing -- regardless, the whole building process will start from scratch.

**Comment by bhalevy** [comment]
The error message was introduced in ee35c4c3d6cbe3c5a6d922e16d8222b1bd6fa024
which is currently present in master and branch-4.3

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
