### ISSUE TITLE
Duplicated partitions when reading system.peers table

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#753]
This manifests itself with `alter table` hanging when executed from `cqlsh`, because the python driver waits for schema agreement in the cluster before completing the operation. The agreement cannot be reached because the results of the query of `system.peers` contain duplicated entries for peers.

```
cqlsh> SELECT peer, schema_version  FROM system.peers;

 peer      | schema_version
-----------+--------------------------------------
 127.0.0.3 | 1064054b-3150-312d-9cb4-ee61e9b9f4f0
 127.0.0.3 | 1064054b-3150-312d-9cb4-ee61e9b9f4f0
 127.0.0.2 | 1064054b-3150-312d-9cb4-ee61e9b9f4f0
 127.0.0.2 | eb009a1c-2137-3fc7-980a-f0b433280c5b
(4 rows)
```

The problem isn't related to schema changes support, the same can be observed with 9d71e4a7eb4dd1e14b1fc2c3e410462633957661 and injected sstables with the following content:

[peers.zip](https://github.com/scylladb/scylla/files/78799/peers.zip)

The problem doesn't happen with a single-partition query:
```
cqlsh> SELECT peer, schema_version  FROM system.peers where peer = '127.0.0.2';

 peer      | schema_version
-----------+--------------------------------------
 127.0.0.2 | 1064054b-3150-312d-9cb4-ee61e9b9f4f0

(1 rows)
```

I will investigate it further.

**Comment by tgrabiec** [comment]
Doesn't happen with `--smp 1`, does happen with `--smp 3`.

**Comment by tgrabiec** [comment]
In `column_family::sstables_as_key_source()`, we attach shard filter only when sstable is marked as shared (`sstable::is_shared()`). It makes sense, because a non-shared sstable should only contain partitions own by the current shard and filtering is not needed. When I change it to attach the filter unconditionally, the problem is gone. It explains why we have duplicate partitions - without the filter many shards return the same partition, while it is assumed that the partition sets are disjoint. It could be that the scylla's shard count changed between restarts. Do we handle that case?

@avikivity @raphaelsc @glommer

**Comment by avikivity** [comment]
We won't call sstable::set_unshared() for a newly probed sstable, so supposedly, that works.

(missing optimization:  do call set_unshared() if we determine that its is wholly owned by the shard)

**Comment by slivne** [comment]
@avikivity / @tgrabiec  is this resolved in the alter table patch set - if not who should handle this ?

**Comment by tgrabiec** [comment]
It's not resolved, I can continue investigating

**Comment by tgrabiec** [comment]
This is caused by the lack of shard-wise filtering of partitions in `sstables::compact_sstables`. There are some pending patches on the list form Raphael for `nodetool cleanup` support which should also fix this.

**Comment by raphaelsc** [comment]
@tgrabiec, I think that this issue can now be closed. 0c67b1d22 should fix this.
