### ISSUE TITLE
Scylla fails to be installed on OEL76

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla#7536]
*Installation details*
Scylla version (or git commit hash): scylla-666.development-0.20201101.6be9f4938.x86_64
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0d6a24fe35fdf5dc4 (eu-west-1)

In the artifact test or oel76 the installation of scylla fails due to a conflict with the kernel:
```
Command: 'sudo yum install -y scylla'

Exit code: 1

Stdout:

Installed size: 341 M
Downloading packages:
--------------------------------------------------------------------------------
Total                                               39 MB/s | 127 MB  00:03     
Running transaction check
ERROR with transaction check vs depsolve:
kernel < 3.10.0-514 conflicts with scylla-server-666.development-0.20201101.6be9f4938.x86_64
 You could try running: rpm -Va --nofiles --nodigest
Your transaction was saved, rerun it with:
 yum load-transaction /tmp/yum_save_tx.2020-11-01.23-25.DruJI0.yumtx

Stderr:

```

Logs:
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                          Log links for testrun with test id 4632c7fd-f283-43c0-997e-3cdef6d569e9                                           |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type   | Link                                                                                                                        |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 20201101_232552 | db-cluster | https://cloudius-jenkins-test.s3.amazonaws.com/4632c7fd-f283-43c0-997e-3cdef6d569e9/20201101_232552/db-cluster-4632c7fd.zip |
| 20201101_232552 | sct-runner | https://cloudius-jenkins-test.s3.amazonaws.com/4632c7fd-f283-43c0-997e-3cdef6d569e9/20201101_232552/sct-runner-4632c7fd.zip |
+-----------------+------------+-----------------------------------------------------------------------------------------------------------------------------+
```

**Comment by roydahan** [comment]
@syuu1228 / @penberg

**Comment by avikivity** [comment]
Not a bug. That installation has a old kernel that scylla doesn't like.

**Comment by roydahan** [comment]
@tzach please update support matrix, what we need to support.
If we're stop supporting OEL 7.6 and move to support later version 8.1?

**Comment by tzach** [comment]
Good point
Look like https://docs.scylladb.com/getting-started/os-support/ is out of date
@avikivity can you please clarify what is supported (and from which Scylla version)

**Comment by avikivity** [comment]
OEL 7.6 is supported. See https://blogs.oracle.com/linux/announcing-the-release-of-oracle-linux-7-update-6.

>Oracle Linux 7 Update 6 ships with the following kernel packages:
>
>Unbreakable Enterprise Kernel (UEK) Release 5 (4.14.35-1818.3.3) for x86-64 and Arm
>Red Hat Compatible Kernel (3.10.0-957) for x86-64 only

957 is greater than 514. That AMI had some old kernel installed, not a 7.6 kernel.

**Comment by roydahan** [comment]
Ok, we need to document somewhere what is the minimum kernel supported.
Until last week this kernel was just fine for us.

Also, do we need to support the UEK?

**Comment by avikivity** [comment]
We support 3.10.0-514 or later. Yes, we support UEK.

**Comment by roydahan** [comment]
https://github.com/scylladb/scylla/issues/7675
