### ISSUE TITLE
The batch size is different from cassandra for the same data.

### ISSUE THREAD

**Issue by chinese20201103** [scylladb/scylla#7537]
cassandra:
WARN [Native-Transport-Requests-1] 2020-11-03 00:38:23,480 BatchStatement.java:301 - Batch for [test.stations] is of size 2.296MiB, exceeding specified threshold of 5.000KiB by 2.292MiB.
scylladb:
WARN 2020-11-03 00:25:07,988 [shard 3] BatchStatement - Batch of prepared statements for test.stations is of size 8332000, exceeding specified WARN threshold of 5120 by 8326880.
7.946MB

**Comment by avikivity** [comment]
That's not a bug, Scylla and Cassandra use different internal representations.

**Comment by chinese20201103** [comment]
hi, The batch size of scylladb is three times as many as cassandra,  is it rensonable? what's more important is that it affects running efficiency.

**Comment by slivne** [comment]
@chinese20201103 is this a batch of prepared or non prepared statements ?

**Comment by chinese20201103** [comment]
String str = String.format("INSERT INTO STATIONS (STATION_ID,OBSERVED_TIME,%s) VALUES(?,?,%s)", 
					strFields, strValues);
			PreparedStatement ps = m_session.prepare(str);
			BatchStatement batch = new BatchStatement();
			//----------------------------------------------------------------------------------------------
			i = 0;
			SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
			Calendar c = new GregorianCalendar(1980, 0, 1);
			while (c.getTime().compareTo(cEnd.getTime()) <= 0) //时间
			{
				for (j = 0; j < 10000; j++) //站点
				{
					BoundStatement bs = ps.bind();
					bs.setString(0, String.format("%05d", j + 1));
					bs.setTimestamp(1, c.getTime());
					for (k = 0; k < 100; k++) //字段
						bs.setDouble(k + 2, k);
					batch.add(bs);
					if ((j + 1) % 1000 == 0)
					{
						//batch_size_fail_threshold_in_kb: 8192
						m_session.execute(batch);
						batch.clear();
					}
					i++;
				}
				System.out.println(String.format("%s 已插入\'%s\' %d", sdf.format(new Date()), sdf.format(c.getTime()), i));
				c.add(Calendar.DATE, 1); //日数据
			}

**Comment by slivne** [comment]
@chinese20201103  so its clear

What is your schema

Is STATION_ID the partition key and OBSERVED_TIME the clustering key .... i will help if you share this info.

Cassandra and Scylla will merge multiple updates to the same partition key into a single mutation - and that will be applied

We can double check if this is what happening here.

Aside of that the internal representation of mutations in scylla and cassandra is different so size difference is expected.

**Comment by chinese20201103** [comment]
DROP TABLE IF EXISTS test.STATIONS;

CREATE TABLE test.STATIONS
(
STATION_ID VARCHAR,
OBSERVED_TIME timestamp,
F001 DOUBLE,
F002 DOUBLE,
F003 DOUBLE,
F004 DOUBLE,
F005 DOUBLE,
F006 DOUBLE,
F007 DOUBLE,
F008 DOUBLE,
F009 DOUBLE,
F010 DOUBLE,
F011 DOUBLE,
F012 DOUBLE,
F013 DOUBLE,
F014 DOUBLE,
F015 DOUBLE,
F016 DOUBLE,
F017 DOUBLE,
F018 DOUBLE,
F019 DOUBLE,
F020 DOUBLE,
F021 DOUBLE,
F022 DOUBLE,
F023 DOUBLE,
F024 DOUBLE,
F025 DOUBLE,
F026 DOUBLE,
F027 DOUBLE,
F028 DOUBLE,
F029 DOUBLE,
F030 DOUBLE,
F031 DOUBLE,
F032 DOUBLE,
F033 DOUBLE,
F034 DOUBLE,
F035 DOUBLE,
F036 DOUBLE,
F037 DOUBLE,
F038 DOUBLE,
F039 DOUBLE,
F040 DOUBLE,
F041 DOUBLE,
F042 DOUBLE,
F043 DOUBLE,
F044 DOUBLE,
F045 DOUBLE,
F046 DOUBLE,
F047 DOUBLE,
F048 DOUBLE,
F049 DOUBLE,
F050 DOUBLE,
F051 DOUBLE,
F052 DOUBLE,
F053 DOUBLE,
F054 DOUBLE,
F055 DOUBLE,
F056 DOUBLE,
F057 DOUBLE,
F058 DOUBLE,
F059 DOUBLE,
F060 DOUBLE,
F061 DOUBLE,
F062 DOUBLE,
F063 DOUBLE,
F064 DOUBLE,
F065 DOUBLE,
F066 DOUBLE,
F067 DOUBLE,
F068 DOUBLE,
F069 DOUBLE,
F070 DOUBLE,
F071 DOUBLE,
F072 DOUBLE,
F073 DOUBLE,
F074 DOUBLE,
F075 DOUBLE,
F076 DOUBLE,
F077 DOUBLE,
F078 DOUBLE,
F079 DOUBLE,
F080 DOUBLE,
F081 DOUBLE,
F082 DOUBLE,
F083 DOUBLE,
F084 DOUBLE,
F085 DOUBLE,
F086 DOUBLE,
F087 DOUBLE,
F088 DOUBLE,
F089 DOUBLE,
F090 DOUBLE,
F091 DOUBLE,
F092 DOUBLE,
F093 DOUBLE,
F094 DOUBLE,
F095 DOUBLE,
F096 DOUBLE,
F097 DOUBLE,
F098 DOUBLE,
F099 DOUBLE,
F100 DOUBLE,
PRIMARY KEY (STATION_ID, OBSERVED_TIME)
);
