### ISSUE TITLE
Support in memory strategy for tables

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#755]
In memory strategy allows a user to define a table as always in memory.
This a more refine way to control caching.  

See similar feature in DS
https://docs.datastax.com/en/datastax_enterprise/4.0/datastax_enterprise/inMemory.html

**Comment by dorlaor** [comment]
Have you seen evidence of someone using it?
With a fast SSD and good enough cache replacement algorithm one won't
need pure in-memory code.

**Comment by LrsK** [comment]
There is a whitepaper from Datastax about the feature here:
http://www.datastax.com/wp-content/uploads/2014/02/WP-DataStax-Enterprise-In-Memory.pdf
According to them, there is a 10-100x speedup improvement when using this feature.

**Comment by dorlaor** [comment]
On Thu, Apr 7, 2016 at 5:02 PM, LrsK <notifications@github.com> wrote:

> There is a whitepaper from Datastax about the feature here:
>
> http://www.datastax.com/wp-content/uploads/2014/02/WP-DataStax-Enterprise-In-Memory.pdf
> According to them, there is a 10-100x speedup improvement when using this
> feature.
>
When the disk is fast enough, Scylla offers 10x and sometimes above so
you cannot expect such gains between Scylla on SSD vs Scylla-in-ram.
However, there will be gains and you won't be required to have a fast disk
which
makes it a cheaper solution

**Comment by lokkju** [comment]
One use case I'd give is a table that is constantly being updated; for instance, a user-resource-last-accessed table, with a UserId, ResourceId, FirstAccessedDate,LastAccessedDate, and AccessedCount.  If this is constantly being updated and accessed, and in memory table that has batched writes or similar would be useful.  Of course, the argument could be made this isn't a proper use case for Scylla at all...

**Comment by dorlaor** [comment]
We're planning to support it in the enterprise release of 2018.2 (mid year)

**Comment by didip** [comment]
Hi all,

Just curious, has this feature been implemented?

**Comment by dorlaor** [comment]
Hi Didip,

It was implemented and will be released in the next Enterprise version.
Dor

**Comment by didip** [comment]
Thank you for the quick reply. Is that something you guys are considering to release in community version?

**Comment by dorlaor** [comment]
Not at the moment. Note that you can get similar but not identical results
by making sure that you have enough ram so everything will be kept in
Scylla's cache
or use a ram-disk

**Comment by avikivity** [comment]
Closing as it is available in enterprise.
