### ISSUE TITLE
Unexpected partition key when repairing with different number of shards

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7552]
This was seen with the fix for #7535 when running the test against scylla build in debug mode.
I reproduced it locally for now based on scylla @ 364ddab148fed1d753b3a39d4f77a05adb967eda
plus a5612529303a0c118e4628a98f0ea826daf8d463 applied on top of it.

```
$ PRINT_DEBUG=true KEEP_TEST_DIR=true CASSANDRA_DIR=../scylla/build/debug NOSE_PROCESSES=2 nosetests -s -v --process-timeout=7200 repair_additional_test:RepairAdditionalTest.repair_disjoint_row_3nodes_diff_shard_count_test

...
ERROR: repair_disjoint_row_3nodes_diff_shard_count_test (repair_additional_test.RepairAdditionalTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/local/home/bhalevy/dev/scylla-dtest/repair_additional_test.py", line 2793, in repair_disjoint_row_3nodes_diff_shard_count_test
    return RepairAdditionalBase._repair_disjoint_row_3nodes_test(self, same_shard_count=False)
  File "/local/home/bhalevy/dev/scylla-dtest/repair_additional_test.py", line 2135, in _repair_disjoint_row_3nodes_test
    info = self._repair(node3, more_options + ['ks'])
  File "/local/home/bhalevy/dev/scylla-dtest/repair_additional_test.py", line 189, in _repair
    return node.repair(options)
  File "/local/home/bhalevy/dev/scylla-dtest/env/lib64/python3.9/site-packages/ccmlib/node.py", line 1258, in repair
    return self.nodetool(cmd, **kwargs)
  File "/local/home/bhalevy/dev/scylla-dtest/env/lib64/python3.9/site-packages/ccmlib/node.py", line 744, in nodetool
    raise NodetoolError(" ".join(args), exit_status, stdout, stderr)
ccmlib.node.NodetoolError: Nodetool command '/local/home/bhalevy/dev/scylla/resources/cassandra/bin/nodetool -h 127.0.77.3 -p 7377 repair ks' failed; exit status: 2; stdout: [2020-11-04 17:06:39,742] Starting repair command #1, repairing 1 ranges for keyspace ks (parallelism=SEQUENTIAL, full=true)
...
dtest: DEBUG: repair_additional_test.py:RepairAdditionalTest.repair_disjoint_row_3nodes_diff_shard_count_test - Test failed with errors: [(<repair_additional_test.RepairAdditionalTest testMethod=repair_disjoint_row_3nodes_diff_shard_count_test>, (<class 'ccmlib.node.NodetoolError'>, NodetoolError("Nodetool command '/local/home/bhalevy/dev/scylla/resources/cassandra/bin/nodetool -h 127.0.77.3 -p 7377 repair ks' failed; exit status: 2; stdout: [2020-11-04 17:06:39,742] Starting repair command #1, repairing 1 ranges for keyspace ks (parallelism=SEQUENTIAL, full=true)\n[2020-11-04 17:12:50,866] Repair session 1 failed\n[2020-11-04 17:12:50,867] Repair session 1 finished\n; stderr: error: Repair job has failed with the error message: [2020-11-04 17:12:50,866] Repair session 1 failed\n-- StackTrace --\njava.lang.RuntimeException: Repair job has failed with the error message: [2020-11-04 17:12:50,866] Repair session 1 failed\n\tat org.apache.cassandra.tools.RepairRunner.progress(RepairRunner.java:124)\n\tat org.apache.cassandra.utils.progress.jmx.JMXNotificationProgressListener.handleNotification(JMXNotificationProgressListener.java:77)\n\tat java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.dispatchNotification(ClientNotifForwarder.java:633)\n\tat java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.doRun(ClientNotifForwarder.java:555)\n\tat java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$NotifFetcher.run(ClientNotifForwarder.java:474)\n\tat java.management/com.sun.jmx.remote.internal.ClientNotifForwarder$LinearExecutor.lambda$execute$0(ClientNotifForwarder.java:108)\n\tat java.base/java.lang.Thread.run(Thread.java:834)\n\n"), <traceback object at 0x7f19b82ada00>))]
```

Node logs show many `Unexpected partition key` warnings like the following:
```
WARN  2020-11-04 19:06:41,168 [shard 1] repair - repair_writer: keyspace=ks, table=cf, multishard_writer failed: invalid_mutation_fragment_stream ([validator 0x7f7fab9903c0 for sstable writer /local/home/bhalevy/.dtest/dtest-oyxtezu6/test/node1/data/ks/cf-6e4870401ebf11eb843d000000000000/md-13-big-Data.db (ks.cf 6e487040-1ebf-11eb-843d-000000000000)] Unexpected partition key: previous {key: pk{00056b33333735}, token:-9076400823946293517}, current {key: pk{00056b32373934}, token:-9081391284741382494})
```

**Comment by bhalevy** [comment]
Here are the logs and cluster data: 
[cluster.tar.gz](https://github.com/scylladb/scylla/files/5489499/cluster.tar.gz)

**Comment by slivne** [comment]
@bhalevy is this a regression - is this test passing on 4.3 / 4.2 / 4.1

**Comment by bhalevy** [comment]
Reproduced with reproduced with scylla-4.3.rc0 bbef05ae3

**Comment by bhalevy** [comment]
> @bhalevy is this a regression - is this test passing on 4.3 / 4.2 / 4.1

@slivne there was no change in this area, so the assumption if that the bug existed since the introduction of the multishard streaming reader

**Comment by denesb** [comment]
```
$ ag 00056b31323436
test/node3/logs/system.log
8390:WARN  2020-11-05 18:25:39,180 [shard 1] repair - repair_writer: keyspace=ks, table=cf, multishard_writer failed: invalid_mutation_fragment_stream ([validator 0x7f37ad1333e0 for sstable writer /home/bdenes/.dtest/dtest-rnz3paqh/test/node3/data/ks/cf-da1375901f8211eb8ebe000000000000/md-652-big-Data.db (ks.cf da137590-1f82-11eb-8ebe-000000000000)] Unexpected partition key: previous {key: pk{00056b31323436}, token:-5041759985487636525}, current {key: pk{00056b31363439}, token:-5050403186519317658})
8391:WARN  2020-11-05 18:25:39,180 [shard 1] repair - repair_writer: keyspace=ks, table=cf, wait_for_writer_done failed: invalid_mutation_fragment_stream ([validator 0x7f37ad1333e0 for sstable writer /home/bdenes/.dtest/dtest-rnz3paqh/test/node3/data/ks/cf-da1375901f8211eb8ebe000000000000/md-652-big-Data.db (ks.cf da137590-1f82-11eb-8ebe-000000000000)] Unexpected partition key: previous {key: pk{00056b31323436}, token:-5041759985487636525}, current {key: pk{00056b31363439}, token:-5050403186519317658})

test/node1/logs/system.log
364847:INFO  2020-11-05 18:25:37,529 [shard 1] mutation_reader - 0x610000113540 shard=1 multishard_combining_reader::fill_buffer(): p={key: pk{00056b31323436}, token:-5041759985487636525}

test/node2/logs/system.log
369893:WARN  2020-11-05 18:25:40,130 [shard 1] repair - repair_writer: keyspace=ks, table=cf, multishard_writer failed: invalid_mutation_fragment_stream ([validator 0x7f4176e203e0 for sstable writer /home/bdenes/.dtest/dtest-rnz3paqh/test/node2/data/ks/cf-da1375901f8211eb8ebe000000000000/md-543-big-Data.db (ks.cf da137590-1f82-11eb-8ebe-000000000000)] Unexpected partition key: previous {key: pk{00056b31323436}, token:-5041759985487636525}, current {key: pk{00056b31363439}, token:-5050403186519317658})
369894:WARN  2020-11-05 18:25:40,130 [shard 1] repair - repair_writer: keyspace=ks, table=cf, wait_for_writer_done failed: invalid_mutation_fragment_stream ([validator 0x7f4176e203e0 for sstable writer /home/bdenes/.dtest/dtest-rnz3paqh/test/node2/data/ks/cf-da1375901f8211eb8ebe000000000000/md-543-big-Data.db (ks.cf da137590-1f82-11eb-8ebe-000000000000)] Unexpected partition key: previous {key: pk{00056b31323436}, token:-5041759985487636525}, current {key: pk{00056b31363439}, token:-5050403186519317658})
```
The validator complains that key `{key: pk{00056b31363439}, token:-5050403186519317658}` is out of order, as it is coming after `{key: pk{00056b31323436}, token:-5041759985487636525}`.

The keys were in the correct reader on the replica:
```
     8 INFO  2020-11-05 18:25:37,500 [shard 1] repair - 0x61b000001ec0 range-generator: pr=[{-5051537582033906346, start}, {-5050036382158116181, start}]
     9 INFO  2020-11-05 18:25:37,500 [shard 1] mutation_reader - 0x610000113540 multishard_combining_reader::fast_forward_to(): pr=[{-5051537582033906346, start}, {-5050036382158116181, start}]
    10 INFO  2020-11-05 18:25:37,500 [shard 1] mutation_reader - 0x611000330e40 shard=0 shard_reader::fast_forward_to(): pr=[{-5051537582033906346, start}, {-5050036382158116181, start}]
    11 INFO  2020-11-05 18:25:37,500 [shard 1] mutation_reader - 0x611000330d00 shard=1 shard_reader::fast_forward_to(): pr=[{-5051537582033906346, start}, {-5050036382158116181, start}]
    12 INFO  2020-11-05 18:25:37,501 [shard 1] mutation_reader - 0x616000411c80 evictable_reader::fast_forward_to(): pr=[{-5051537582033906346, start}, {-5050036382158116181, start}]
    13 INFO  2020-11-05 18:25:37,501 [shard 0] mutation_reader - 0x616000033680 evictable_reader::fast_forward_to(): pr=[{-5051537582033906346, start}, {-5050036382158116181, start}]
    14 INFO  2020-11-05 18:25:37,509 [shard 1] mutation_reader - 0x610000113540 shard=1 multishard_combining_reader::fill_buffer(): p={key: pk{00056b31363439}, token:-5050403186519317658}
    15 INFO  2020-11-05 18:25:37,509 [shard 1] repair - 0x61b000001ec0 range-generator: pr=[{-5047033982406535850, start}, {-5045532782530745685, start}]
    16 INFO  2020-11-05 18:25:37,509 [shard 1] mutation_reader - 0x610000113540 multishard_combining_reader::fast_forward_to(): pr=[{-5047033982406535850, start}, {-5045532782530745685, start}]
    17 INFO  2020-11-05 18:25:37,509 [shard 1] mutation_reader - 0x611000330e40 shard=0 shard_reader::fast_forward_to(): pr=[{-5047033982406535850, start}, {-5045532782530745685, start}]
    18 INFO  2020-11-05 18:25:37,509 [shard 1] mutation_reader - 0x611000330d00 shard=1 shard_reader::fast_forward_to(): pr=[{-5047033982406535850, start}, {-5045532782530745685, start}]
    19 INFO  2020-11-05 18:25:37,510 [shard 1] mutation_reader - 0x616000411c80 evictable_reader::fast_forward_to(): pr=[{-5047033982406535850, start}, {-5045532782530745685, start}]
    20 INFO  2020-11-05 18:25:37,510 [shard 0] mutation_reader - 0x616000033680 evictable_reader::fast_forward_to(): pr=[{-5047033982406535850, start}, {-5045532782530745685, start}]
    21 INFO  2020-11-05 18:25:37,520 [shard 1] repair - 0x61b000001ec0 range-generator: pr=[{-5042530382779165354, start}, {-5041029182903375189, start}]
    22 INFO  2020-11-05 18:25:37,520 [shard 1] mutation_reader - 0x610000113540 multishard_combining_reader::fast_forward_to(): pr=[{-5042530382779165354, start}, {-5041029182903375189, start}]
    23 INFO  2020-11-05 18:25:37,520 [shard 1] mutation_reader - 0x611000330e40 shard=0 shard_reader::fast_forward_to(): pr=[{-5042530382779165354, start}, {-5041029182903375189, start}]
    24 INFO  2020-11-05 18:25:37,520 [shard 1] mutation_reader - 0x611000330d00 shard=1 shard_reader::fast_forward_to(): pr=[{-5042530382779165354, start}, {-5041029182903375189, start}]
    25 INFO  2020-11-05 18:25:37,520 [shard 1] mutation_reader - 0x616000411c80 evictable_reader::fast_forward_to(): pr=[{-5042530382779165354, start}, {-5041029182903375189, start}]
    26 INFO  2020-11-05 18:25:37,521 [shard 0] mutation_reader - 0x616000033680 evictable_reader::fast_forward_to(): pr=[{-5042530382779165354, start}, {-5041029182903375189, start}]
    27 INFO  2020-11-05 18:25:37,529 [shard 1] mutation_reader - 0x610000113540 shard=1 multishard_combining_reader::fill_buffer(): p={key: pk{00056b31323436}, token:-5041759985487636525}
```
They were reordered somewhere in-flight.

**Comment by denesb** [comment]
```
1   // node2                                                                                                                                                                                                                                                    1 INFO  2020-11-12 14:16:32,994 [shard 1] repair - to_repair_rows_on_wire(): pk={key: pk{00056b32373338}, token:-8792908231596295140}                                                                                                                       
  2 INFO  2020-11-12 14:16:32,994 [shard 1] repair - to_repair_rows_on_wire(): pk={key: pk{00056b32373734}, token:-8788413194541208272}                                                                                                                         3 INFO  2020-11-12 14:16:32,994 [shard 1] repair - to_repair_rows_on_wire(): pk={key: pk{00056b32363137}, token:-8774802964518843943}                                                                                                                       
  4 INFO  2020-11-12 14:16:32,994 [shard 0] repair - repair_get_row_diff_with_rpc_stream_process_op() dk=pk{00056b32373338}                                                                                                                                     5 INFO  2020-11-12 14:16:32,995 [shard 0] repair - repair_get_row_diff_with_rpc_stream_process_op() dk=pk{00056b32373734}                                                                                                                                   
  6 INFO  2020-11-12 14:16:32,995 [shard 0] repair - repair_get_row_diff_with_rpc_stream_process_op() dk=pk{00056b32363137}                                                                                                                                     7                                                                                                                                                                                                                                                           
  8 // node1                                                                                                                                                                                                                                                    9 TRACE 2020-11-12 14:16:33,051 [shard 1] repair - get_row_diff: Got repair_row_on_wire with data, dk=pk{00056b32363137}                                                                                                                                     10 TRACE 2020-11-12 14:16:33,051 [shard 1] repair - get_row_diff: Got repair_row_on_wire with data, dk=pk{00056b32373338}     
```
I'm still not sure about it but it looks like data is reordered on the wire, while being transferred via RPC streaming.

**Comment by denesb** [comment]
@gleb-cloudius is it possible that RPC streaming reorders messages in debug mode when the task queues is shuffled?

**Comment by gleb-cloudius** [comment]
On Thu, Nov 12, 2020 at 04:37:11AM -0800, Botond Dénes wrote:
> @gleb-cloudius is it possible that RPC streaming reorders messages in debug mode when the task queues is shuffled?
> 
Very likely. I recently discovered that any use of our semaphore where
more than one unit can be signaled simultaneously becomes point of
reordering in debug mode due to task queues is shuffling. It makes
semaphore much less useful and I am not sure if it is a correct
behaviour even in debug mode.

--
			Gleb.

**Comment by avikivity** [comment]
rpc streaming should not depend in task execution order, it is too fragile.

**Comment by asias** [comment]
> rpc streaming should not depend in task execution order, it is too fragile.

Can we fix the rpc stream? It will be a serious issue if seastar rpc stream can not guarantee the order. 

@slivne Please prioritize.

**Comment by gleb-cloudius** [comment]
On Sun, Nov 15, 2020 at 04:50:30PM -0800, Asias He wrote:
> > rpc streaming should not depend in task execution order, it is too fragile.
> 
> Can we fix the rpc stream? It will be a serious issue if seastar rpc stream can not guarantee the order. 
> 
It guaranties the order given that primitives it uses work
correctly. Debug build breaks semaphore to reorder waiter so anything
that relies on it to be ordered will break in debug build. 

That said I do not longer believe the issue is in the RPC streaming per
se.  Semaphores there suppose to have only one waiter, so no reordering
may happen. _queue_has_room semaphore in smp queue may be a culprit. Or
any semaphore in Scylla streaming code (if any) that may have more that
one waiter released at a time.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
But first try to reproduce with the patch below. If reproducible this is something else entirely. 

```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0fe5ae4bae..2e04a3eea1 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -931,8 +931,7 @@ if ((CMAKE_BUILD_TYPE STREQUAL "Debug") OR (CMAKE_BUILD_TYPE STREQUAL "Sanitize"
     PUBLIC
       SEASTAR_DEBUG
       SEASTAR_DEFAULT_ALLOCATOR
-      SEASTAR_DEBUG_SHARED_PTR
-      SEASTAR_SHUFFLE_TASK_QUEUE)
+      SEASTAR_DEBUG_SHARED_PTR)
 endif ()
 
 set (Seastar_STACK_GUARD_MODES "Debug" "Sanitize" "Dev")
```

**Comment by bhalevy** [comment]
The tests passes in debug mode with the above patch to not enable `SEASTAR_SHUFFLE_TASK_QUEUE`

**Comment by avikivity** [comment]
@gleb-cloudius can you point out which semaphore is in play here?

**Comment by gleb-cloudius** [comment]
On Mon, Nov 16, 2020 at 04:52:23AM -0800, Avi Kivity wrote:
> @gleb-cloudius can you point out which semaphore is in play here?
> 
My guess is: get_smp_service_groups_semaphore

--
			Gleb.

**Comment by bhalevy** [comment]
FWIW, I tried bypassing `get_smp_service_groups_semaphore` in `smp_message_queue::submit_item` and it didn't help.

**Comment by gleb-cloudius** [comment]
On Mon, Nov 16, 2020 at 08:01:57AM -0800, Benny Halevy wrote:
> FWIW, I tried bypassing `get_smp_service_groups_semaphore` in `smp_message_queue::submit_item` and it didn't help.
> 
Well, it looks like semaphore is not the only place that has the
problem. Smp queue may reorder without it as well:

size_t smp_message_queue::process_incoming() {
    auto nr = process_queue<prefetch_cnt>(_pending, [] (work_item* wi) {
        wi->process();
    });
    _received += nr;
    _last_rcv_batch = nr;
    return nr;
}

wi->process(); calls schedule, so with task queue shuffling incoming
messages arriving in the same batch may be reordered. Crazy.

--
			Gleb.

**Comment by bhalevy** [comment]
> On Mon, Nov 16, 2020 at 08:01:57AM -0800, Benny Halevy wrote: FWIW, I tried bypassing `get_smp_service_groups_semaphore` in `smp_message_queue::submit_item` and it didn't help.
> Well, it looks like semaphore is not the only place that has the problem. Smp queue may reorder without it as well: size_t smp_message_queue::process_incoming() { auto nr = process_queue<prefetch_cnt>(_pending, [] (work_item* wi) { wi->process(); }); _received += nr; _last_rcv_batch = nr; return nr; } wi->process(); calls schedule, so with task queue shuffling incoming messages arriving in the same batch may be reordered. Crazy.
> […](#)
> -- Gleb.

I tried selectively disabling shuffling, including on this path and even bypassing the `smp_service_groups_semaphore` and it didn't help. I'm afraid the shuffling issue is even deeper in the guts, possibly from `satisfy_with_result_of -> pr.set_value -> make_ready -> schedule`.  I don't have definite proof yet though...

**Comment by gleb-cloudius** [comment]
The shuffling issue matters only when one continuation signals several
futures. Those futures need to be executed in the order signaled. I do
not see how you can selectively disabling shuffling since any future
signaled by some other continuation will shuffle everything.

--
			Gleb.

**Comment by bhalevy** [comment]
> The shuffling issue matters only when one continuation signals several futures. Those futures need to be executed in the order signaled. I do not see how you can selectively disabling shuffling since any future signaled by some other continuation will shuffle everything.

I hacked seastar to include a `bool do_shuffle` option to make_ready, schedule, etc. and pass it down to add_task to be considered when SEASTAR_SHUFFLE_TASK_QUEUE is defined (and defined it also in dev build to run the test a little faster)

**Comment by gleb-cloudius** [comment]
On Tue, Nov 17, 2020 at 02:23:33AM -0800, Benny Halevy wrote:
> > The shuffling issue matters only when one continuation signals several futures. Those futures need to be executed in the order signaled. I do not see how you can selectively disabling shuffling since any future signaled by some other continuation will shuffle everything.
> 
> I hacked seastar to include a `bool do_shuffle` option to make_ready, schedule, etc. and pass it down to add_task to be considered when SEASTAR_SHUFFLE_TASK_QUEUE is defined (and defined it also in dev build to run the test a little faster)
> 
I do not see how this may work. make_ready(true) will shuffle all the
previous tasks that were added with make_ready(false). What you can try
to do is to change process_incoming() to take only one task from smp
queue.

--
			Gleb.

**Comment by bhalevy** [comment]
> On Tue, Nov 17, 2020 at 02:23:33AM -0800, Benny Halevy wrote: > The shuffling issue matters only when one continuation signals several futures. Those futures need to be executed in the order signaled. I do not see how you can selectively disabling shuffling since any future signaled by some other continuation will shuffle everything. I hacked seastar to include a `bool do_shuffle` option to make_ready, schedule, etc. and pass it down to add_task to be considered when SEASTAR_SHUFFLE_TASK_QUEUE is defined (and defined it also in dev build to run the test a little faster)
> I do not see how this may work. make_ready(true) will shuffle all the previous tasks that were added with make_ready(false). What you can try to do is to change process_incoming() to take only one task from smp queue.

I also modified `shuffle()` to insert the new entry in the middle of the queue without changing the relative order if other tasks in the queue so those that were previously queued without the shuffle flag are dequeued in the same relative order they were inserted.

It looks like this in my branch:
```cpp
void reactor::shuffle(task*& t, task_queue& q) {
    if (q._q.size() < 2) {
        return;
    }
    static thread_local std::mt19937 gen = std::mt19937(std::random_device{}());
    std::uniform_int_distribution<size_t> tasks_dist{0, q._q.size() - 2};
    size_t i = tasks_dist(gen);
    task* tp = t;
    auto& qq = q._q;
    if (t == qq.back()) {
        std::copy_backward(qq.begin() + i, qq.end() - 1, qq.end());
    } else {
        assert(t == qq.front());
        i++;
        std::copy(qq.begin() + 1, qq.begin() + i + 1, qq.begin());
    }
    qq[i] = tp;
}
```

**Comment by gleb-cloudius** [comment]
Where can I see your code?

--
			Gleb.

**Comment by bhalevy** [comment]
> On Mon, Nov 16, 2020 at 08:01:57AM -0800, Benny Halevy wrote: FWIW, I tried bypassing `get_smp_service_groups_semaphore` in `smp_message_queue::submit_item` and it didn't help.
> Well, it looks like semaphore is not the only place that has the problem. Smp queue may reorder without it as well: size_t smp_message_queue::process_incoming() { auto nr = process_queue<prefetch_cnt>(_pending, [] (work_item* wi) { wi->process(); }); _received += nr; _last_rcv_batch = nr; return nr; } wi->process(); calls schedule, so with task queue shuffling incoming messages arriving in the same batch may be reordered. Crazy.

@gleb-cloudius it looks like both your guesses where right on the spot.
With https://github.com/bhalevy/seastar/commits/shuffle-v1 the test passes reliably.
It selectively inhibits shuffling from `smp::poll_queues -> process_incoming|process_completions -> work_item::process`
And also disables shuffling of continuations of available futures (ready or exceptional) - which causes reordering of execution when using semaphores that allow parallelism, when e.g. wait(1) returns a ready future.
In addition it also keeps the FIFO order in the semaphore `wait_list` in signal by calling (a newly introduced) `set_ready_no_shuffle` rather than `set_ready` on the queued tasks (and correspondingly `set_exception(ex, false)` but I doubt that matters for this test)

**Comment by bhalevy** [comment]
@avikivity can you please review https://github.com/bhalevy/seastar/commits/shuffle-v1 too?
I think it's reasonable to commit to make task shuffling in debug workable.

**Comment by bhalevy** [comment]
Sent the patches to the seastar-dev mailing list.
"[RFC PATCH v1 0/9] shuffle selectively in debug mode"

**Comment by denesb** [comment]
This was confirmed as the cause of https://github.com/scylladb/scylla/issues/7623, the same reordering can happen in release mode, although it is very hard to reproduce.

**Comment by gleb-cloudius** [comment]
On Mon, Feb 15, 2021 at 07:37:06AM -0800, Botond Dénes wrote:
> This was confirmed as the cause of https://github.com/scylladb/scylla/issues/7623, the same reordering can happen in release mode, although it is very hard to reproduce.
> 
Not in a resent enough master though since it does not preempt in
future::then().

--
			Gleb.

**Comment by denesb** [comment]
Yes, currently that may be the case, but. technically speaking we still have no ordering guarantee and it might just happen to work at the moment, but to consider this fixed we need the ordering patch.

**Comment by gleb-cloudius** [comment]
On Tue, Feb 16, 2021 at 12:59:16AM -0800, Botond Dénes wrote:
> Yes, currently that may be the case, but. technically speaking we still have no ordering guarantee and it might just happen to work at the moment, but to consider this fixed we need the ordering patch.
> 
Yes.

--
			Gleb.

**Comment by denesb** [comment]
Seastar issue: https://github.com/scylladb/seastar/issues/867

**Comment by avikivity** [comment]
Backported to 4.4 (for now).

**Comment by avikivity** [comment]
Backported to 4.2, 4.3.
