### ISSUE TITLE
Cleanup compaction in KA/LA sstables may crash the node in some cases

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#7553]
MC or later sstable formats are not affected.

Cleanup compaction is using `consume_pausable_in_thread()` to skip over disowned partitions, which uses `flat_mutation_reader::next_partition()`.

The implementation of `next_partition()` for the sstable reader has a bug which may cause the following assertion failure:

```
scylla: sstables/mp_row_consumer.hh:422: row_consumer::proceed sstables::mp_row_consumer_k_l::flush(): Assertion `!_ready' failed.
```

This happens when the sstable reader's buffer gets full when we reach the partition end. The last fragment of the partition won't be pushed into the buffer but will stay in the `_ready` variable. When `next_partition()` is called in this state, `_ready` will not be cleared and the fragment will be carried over to the next partition. This will cause assertion failure when the reader attempts to emit the first fragment of the next partition.

**Comment by tgrabiec** [comment]
Can also manifest in scans with a per-partition row limit

**Comment by tgrabiec** [comment]
In queries which use per-partition row limit and clustering key restrictions can result in the row which is cut-off by the limit to appear under the next partition.

**Comment by avikivity** [comment]
Backported to 4.1, 4.2, 4.3.

**Comment by vladzcloudius** [comment]
> Backported to 4.1, 4.2, 4.3.

@avikivity Could you, please, clarify if this issue is not relevant to 4.0?

**Comment by tomer-sandler** [comment]
Are customers running 2019.1 (on cloud), are exposed to this bug? @avikivity
