### ISSUE TITLE
Create a separate DynamoDB compatibility document for Alternator

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7556]
When a user is thinking of migrating an existing application from DynamoDB to Alternator, they want to know in advance which features might not yet be available in Alternator, and which other surprising things they may encounter - such as the need for some load balancing solution, and the need to choose a write isolation mode.

In `docs/alternator/alternator.md` we already have all this information, but I perhaps (as I was told) not in a form easy enough to consume. I propose to split off the "Current compatibility with DynamoDB" and "Write isolation policies", plus some discussion of load balancing, to a separate document, perhaps `compatibility.md`. The "Current compatibility with DynamoDB" should be rewritten to list only the actual differences, not list commonalities or operations. All missing features already have open issues about them, and I think it will be useful to add links to these issues.

**Comment by lauranovich** [comment]
Following... this would be great!
