### ISSUE TITLE
Docker: iproute package missing from docker image

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#7560]
since https://github.com/scylladb/scylla/commit/bd73898a5c80d14015d759dea0debebbda78b484 was merged, and kernel isn't installed on docker, iproute isn't installed anymore.

We used it in testing of the docker image (also on scylla-operator testing)

tests are depended on `ss` from iproute package:
https://github.com/scylladb/scylla-cluster-tests/commit/3b62d3ec883c909f3bcce90a1f31a5d723973469

**Comment by fruch** [comment]
FYI, @enaydanov

**Comment by slivne** [comment]
@avikivity / @penberg comment - suggest a solution

**Comment by avikivity** [comment]
@slivne the issue title suggests a solution (instead of describing a problem)

**Comment by fruch** [comment]
> he issue title suggests a solution (instead of describing a problem)
 now it's describing the problem.

**Comment by fruch** [comment]
@avikivity we have a fix for that in SCT scylladb/scylla-cluster-tests#2841
my concern is with users that already using this image, and might break then own tooling (if it's in k8s setup, or other)

**Comment by bentsi** [comment]
IMHO, Scylla Docker image should have only packages that are needed for Scylla to work, other nice-to-have/testing related packages should not be included in the official Scylla Docker image...

**Comment by fruch** [comment]
> IMHO, Scylla Docker image should have only packages that are needed for Scylla to work, other nice-to-have/testing related packages should not be included in the official Scylla Docker image...

I agree, but once something it out there, we should try not breaking our users experience, sending them surprises.

**Comment by avikivity** [comment]
I agree with both points. @fruch do we have any evidence that k8s tooling is using it? If it's just testing, we can adjust.

**Comment by fruch** [comment]
> I agree with both points. @fruch do we have any evidence that k8s tooling is using it? If it's just testing, we can adjust.

I don't have evidence, I'm not that familiar with https://github.com/scylladb/scylla-operator if that is depends on any tools on the docker instance. (I hope it isn't)

It was more general concern, since people are building things ontop of what we release. and it's not the first nor the last they depend even on things we didn't intended to provide.

happened to us in `scylla-machine-image`, that people were using a temporary file we created at the end of boot, and we thought it's o.k. to change it's name. (the people who were using it, we scylla-cloud team :cry: )

**Comment by avikivity** [comment]
Please ask the operator maintainers.

**Comment by fruch** [comment]
@zimnx @espindola, are you guys aware of any usage of the operator code, with any tool on the scylla docker instance itself ?, to help us elevate this concern we are having here ?

**Comment by zimnx** [comment]
@fruch Operator directly calls `nodetool` and `/docker-entrypoint.py` inside Scylla container.

**Comment by fruch** [comment]
thanks @zimnx 

@avikivity I think we are going to merge the fix in the test end
https://github.com/scylladb/scylla-cluster-tests/pull/2841

and then we could close this one.

**Comment by fruch** [comment]
we merged the fix for it in SCT, closing this one
