### ISSUE TITLE
Performance degradation due to the ongoing compaction [4.2.0]

### ISSUE THREAD

**Issue by sitano** [scylladb/scylla#7563]
*Installation details*
Scylla version (or git commit hash): 4.1.6-0.20200831.6d9ff622df with build-id c2ed04d00095c63b7456b5fcda6775c5a9f33b0b
Cluster size: 3 x i3.4xlarge
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-013da0bd17560082a

*Hardware details (for performance issues)*
Platform (physical/VM/cloud instance type/docker): AWS
Hardware: sockets=1 cores=8 hyperthreading=yes memory=128 (i3.4xlarge)
Disks: (SSD/HDD, count) 1 md0 = 2 * 1.9 NVMe SSD

Testing 100M YCSB workloads with `git@github.com:sitano/scylla-cluster-tests.git /ivan_100m`: `scylla-staging/job/ivan/job/ivan-byo-longevity/26/console`.

As part of the test scenario, there are 2 phases:

Populate 100M of data (RF=3):

```
$ bin/ycsb load cassandra-cql -P workloads/workloada -threads 84 -p recordcount=100000000 -p cassandra.readconsistencylevel=ONE -p cassandra.writeconsistencylevel=ONE -p readproportion=0 -p updateproportion=1 -p fieldcount=10 -p fieldlength=128 -p insertstart=0 -p insertcount=50000000 -p cassandra.coreconnections=14 -p cassandra.maxconnections=14 -p cassandra.username=cassandra -p cassandra.password=cassandra -s  -p hosts=10.0.0.171,10.0.0.142,10.0.1.8 -p cassandra.readconsistencylevel=QUORUM -p cassandra.writeconsistencylevel=QUORUM -p maxexecutiontime=29400
```

Run the workload. I am running here workload A for 10m with 1 loader in 84 threads per loader with token aware lb policy enabled (https://github.com/brianfrankcooper/YCSB/pull/1473):

```
$ bin/ycsb run scylla -P workloads/workloada -threads 84 -p recordcount=100000000 -p fieldcount=10 -p fieldlength=128 -p operationcount=50000000 -p scylla.coreconnections=14 -p scylla.maxconnections=14 -p scylla.username=cassandra -p scylla.password=cassandra -p scylla.tokenaware=true -p hosts=10.0
.0.171,10.0.0.142,10.0.1.8 -p scylla.readconsistencylevel=ONE -p scylla.writeconsistencylevel=ONE
```

Workload A uses Zipfian distribution (Zetta). It results into 1-2 shads being loaded more than the others. The average load is about 50% where those 2 shards are about 100%.

During the second phase, we expect to see steady 120K OPS and avg p99 latency of 2 ms.
However, right after the start into the test, the op/s and latency start degrading gradually from 120K op/s to 75K (almost x2) while p99 latency rising from 2 ms to 8 ms.

![f2020-10-30-scylla-oy-za-sa-100m-84t-wc-2](https://user-images.githubusercontent.com/564610/98358651-b492bf80-202f-11eb-8acc-c414e6dd897a.png)

Unfortunately, right after the test start, the compaction happened that took CPU from most of the shards after what overall throughput degraded by factor x2 and the latency by factor x4.

![f2020-10-30-scylla-oy-za-sa-100m-84t-wc-8](https://user-images.githubusercontent.com/564610/98359390-d2145900-2030-11eb-9b04-34bf3aa905ca.png)

It can be seen that it is a Compaction that took up to 75% of CPU from the Shards:

![f2020-10-30-scylla-oy-za-sa-100m-84t-wc-11](https://user-images.githubusercontent.com/564610/98359471-f708cc00-2030-11eb-893e-5957d08bf05b.png)

![f2020-10-30-scylla-oy-za-sa-100m-84t-wc-10](https://user-images.githubusercontent.com/564610/98359492-fff99d80-2030-11eb-8e5f-4760e1f4bdfc.png)

It is not what a user would expect from background service operations. Besides compactions it also includes streaming, writing new sstables, memtable flush and etc.

## Normal vs Sick execution

This is how the normal execution of this test looks like:

![f2020-10-30-scylla-oy-za-sa-100m-84t-noc-3](https://user-images.githubusercontent.com/564610/98359758-6088da80-2031-11eb-906b-582ae5f141ed.png)

It gives even higher throughput at 130-140K QPS with steady latency at 2ms.

## Resolution

It must be clear that the user expectations are that background processes don't steal resources from him and that the observed performance does not suffer. It's something that must hold.

We observe that our background processes are not limited. Let's limit them. It will prevent a user from observing at least an unbounded performance degradation.

Why it's a good idea to limit the background processes?

Because a user will not observe unbounded performance degradation in random points in time.

What he will observe instead is only bounded degradation that is much better. 

However, someone would say at this point that limiting background processes such as compaction may prevent compaction from finishing. The answer is: yes. We must embrace it. It is good. It must be like that. It is for good.

Why we don't care if limited resources compaction would not be able to keep up?

Mainly because you PUNISH a user even BEFORE lack of compaction resulted in the growth of read amplification and thus latency and throughput degradation of reads. A user don't want this. He don't want to pay for what did not happen. He want to solve his problems. But random perf degradation is something that can't be solved by the user because a) its random b) he has no control.

Then it may never happen. Compactions don't happen all the time. They will become longer. IF they will become lagging too much a user will always be able to resize a cluster and give it more resources. 

Thus, the resources that can be consumed by the background processes (compaction) must be limited by soft and hard configurable limits. Hard limit must not exceed 20% by default.

## Links

- maybe related https://github.com/scylladb/scylla/issues/3267
- maybe related https://github.com/scylladb/scylla/issues/6928

**Comment by dorlaor** [comment]
There are very few compactions going (1 per shard?), why do you think it's
compaction?
There are metrics for it with compaction shares.

**Comment by sitano** [comment]
@dorlaor because graph "Compactions CPU Runtime" shows 75% CPU usage per shard after what shards Load went 100%. However, I talked to Vlad who mentioned I forgot to state --target parameter that could explain this level of throughput degradation and that small level of latency degradation. I am not looking at the latency distribution but without coordinated omission, latency could be much worse. Also, he pointed out to the low level of the request queue that can affect Scylla schedulers and that means that concurrency is too low. With that in mind, I think I will close this one and retry the tests with --target parameter and higher concurrency. It will not change the fact that compactions overtook CPU from shards but maybe show a different picture in throughput latency. Maybe schedulers will behave differently under different request queue size.

**Comment by sitano** [comment]
I retest the workload with --target 120000 and concurrency level = 20 per Shard = 20 * 14 Shards = 280 connections per host. Request queue got a bit larger but still not that big but not 0. Each time Compactions step in latency goes wild.

```
$ bin/ycsb run scylla -P workloads/workloada -target 120000 -threads 840 -p recordcount=300000000 -p fieldcount=10 -p fieldlength=128 -p operationcount=100000000 -p scylla.coreconnections=280 
-p scylla.maxconnections=280 -p scylla.username=cassandra -p scylla.password=cassandra -p scylla.tokenaware=true -p hosts=10.0.2.51,10.0.3.133,10.0.3.67 -p scylla.readconsistencylevel=ONE -p
 scylla.writeconsistencylevel=ONE
```

Normal execution when there are no compactions:

![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-10m-1](https://user-images.githubusercontent.com/564610/98682364-83d2c300-236c-11eb-992e-6a79106d6c36.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-10m-2](https://user-images.githubusercontent.com/564610/98682365-8503f000-236c-11eb-8f1e-c1e48e20011e.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-10m-3](https://user-images.githubusercontent.com/564610/98682370-859c8680-236c-11eb-920a-ed5cef61493c.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-10m-4](https://user-images.githubusercontent.com/564610/98682372-859c8680-236c-11eb-85dd-3cc86ded0cda.png)

With compactions started:

![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-compaction-1](https://user-images.githubusercontent.com/564610/98682396-8cc39480-236c-11eb-8364-e6a0cb9ed944.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-compaction-2](https://user-images.githubusercontent.com/564610/98682402-8df4c180-236c-11eb-81ac-309eec06c805.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-compaction-3](https://user-images.githubusercontent.com/564610/98682403-8e8d5800-236c-11eb-9021-d66a21a1df88.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-compaction-4](https://user-images.githubusercontent.com/564610/98682404-8e8d5800-236c-11eb-9cc6-82eab636a611.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-compaction-5](https://user-images.githubusercontent.com/564610/98682408-8f25ee80-236c-11eb-8b22-ae63924118d8.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-compaction-6](https://user-images.githubusercontent.com/564610/98682409-8fbe8500-236c-11eb-978b-b1e76607451a.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-compaction-7](https://user-images.githubusercontent.com/564610/98682413-8fbe8500-236c-11eb-9120-387273648840.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-compaction-8](https://user-images.githubusercontent.com/564610/98682414-90571b80-236c-11eb-94de-f46d0740128b.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-compaction-9](https://user-images.githubusercontent.com/564610/98682416-90571b80-236c-11eb-9bc0-92b41bf796d0.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-compaction-10](https://user-images.githubusercontent.com/564610/98682418-90efb200-236c-11eb-9e28-1591ede2a379.png)

**Comment by sitano** [comment]
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-1](https://user-images.githubusercontent.com/564610/98694218-dd8dba00-2379-11eb-8275-e29fa1dea334.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-2](https://user-images.githubusercontent.com/564610/98694220-debee700-2379-11eb-877a-caf4ad0b7ebc.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-3](https://user-images.githubusercontent.com/564610/98694223-dff01400-2379-11eb-880f-ccf0697d8f7a.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-4](https://user-images.githubusercontent.com/564610/98694224-e088aa80-2379-11eb-8281-881bd34fb0d6.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-5](https://user-images.githubusercontent.com/564610/98694228-e088aa80-2379-11eb-908f-89350ed28852.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-6](https://user-images.githubusercontent.com/564610/98694231-e1214100-2379-11eb-8369-cbee17efb028.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-7](https://user-images.githubusercontent.com/564610/98694236-e1b9d780-2379-11eb-82c8-5b13ee9c85e7.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-8](https://user-images.githubusercontent.com/564610/98694239-e2526e00-2379-11eb-8e5a-38d8b3ce3fde.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-9](https://user-images.githubusercontent.com/564610/98694241-e2eb0480-2379-11eb-9e10-5cae76cdbddd.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-10](https://user-images.githubusercontent.com/564610/98694242-e2eb0480-2379-11eb-9016-e1646af03a6c.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-11](https://user-images.githubusercontent.com/564610/98694243-e3839b00-2379-11eb-8981-a9f8608b2448.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-12](https://user-images.githubusercontent.com/564610/98694245-e41c3180-2379-11eb-85d5-e6a18527bb31.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-13](https://user-images.githubusercontent.com/564610/98694247-e4b4c800-2379-11eb-9843-8cc0fef0ad9a.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-14](https://user-images.githubusercontent.com/564610/98694251-e54d5e80-2379-11eb-901a-34888adfa9b7.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-15](https://user-images.githubusercontent.com/564610/98694253-e5e5f500-2379-11eb-9ef2-0f7dba13c17b.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-16](https://user-images.githubusercontent.com/564610/98694255-e67e8b80-2379-11eb-9508-87a3fd6fd4ad.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-17](https://user-images.githubusercontent.com/564610/98694256-e67e8b80-2379-11eb-9436-6c130268ecc2.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-18](https://user-images.githubusercontent.com/564610/98694259-e7172200-2379-11eb-8a3d-bdcf210d9354.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-19](https://user-images.githubusercontent.com/564610/98694261-e7afb880-2379-11eb-923f-bcdf2521fffd.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-20](https://user-images.githubusercontent.com/564610/98694264-e8484f00-2379-11eb-9ea3-cda1c002896f.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-21](https://user-images.githubusercontent.com/564610/98694268-e8e0e580-2379-11eb-9076-c6202e119a17.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-22](https://user-images.githubusercontent.com/564610/98694269-e9797c00-2379-11eb-876c-8cabcf148cc1.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-23](https://user-images.githubusercontent.com/564610/98694271-e9797c00-2379-11eb-88cf-3edb96ec7c0b.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-24](https://user-images.githubusercontent.com/564610/98694273-ea121280-2379-11eb-9adf-f0c3be1c9526.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-25](https://user-images.githubusercontent.com/564610/98694275-eaaaa900-2379-11eb-8c4b-badb536a5bc1.png)
![f2020-11-10-scylla-oy-zf-sa-co-100m-840t-240c-30m-26](https://user-images.githubusercontent.com/564610/98694277-eb433f80-2379-11eb-9170-f2b2b43af29d.png)

**Comment by sitano** [comment]
First I thought its due shards imbalance, but there is specifically the last shard that is getting overloaded.

![f2020-11-11-scylla-oy-zf-sa-co-100m-840t-240c-30m-uniform-14](https://user-images.githubusercontent.com/564610/98800791-8dfecb00-2419-11eb-89f1-e5867e6dab69.png)
![f2020-11-11-scylla-oy-zf-sa-co-100m-840t-240c-30m-uniform-15](https://user-images.githubusercontent.com/564610/98800793-8f2ff800-2419-11eb-8c8d-40e209b66123.png)
![f2020-11-11-scylla-oy-zf-sa-co-100m-840t-240c-30m-uniform-16](https://user-images.githubusercontent.com/564610/98800794-8fc88e80-2419-11eb-898e-3587354b8050.png)

**Comment by sitano** [comment]
I don't know what is the reason for that last shard overload even tho it happens when compactions run but it seems like the reason is not in compactions them selves.
