### ISSUE TITLE
Alternator Query with ScanIndexForward = false is inefficient and limited to 100MB

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7586]
Note: This is an Alternator (i.e., DynamoDB API) issue. For a similar issue in the CQL API #1413.

The Alternator `Query` operations supports the `ScanIndexForward=false` parameter, which requests the query to return items in reversed sort order. This feature already works, and uses the same internal mechanism (`query::partition_slice::option::reversed`) which we use in CQL's `ORDER BY ... DESC` feature.

However, as explained in issue #1413, our implementation of `query::partition_slice::option::reversed` is inefficient - because we don't have support for reading a partition backwards so it resorts to reading the entire partition into memory and then reversing it. This isn't just inefficient - it is also limited to `max_memory_for_unlimited_query_hard_limit` (by default 100MB), beyond which the reverse query will fail.

Beyond a single query page, we will also want to be able to resume readers on the following pages, even when iterating in reverse order. See issue #6278 about Alternator missing support for resuming readers for forward-ordered queries - we need to remember to do this also for reverse-ordered queries.

**Comment by nyh** [comment]
Status update:

There has been a lot of work recently on improving reverse queries in Scylla. The work is done in for the direct benefit of CQL reverse queries (#1413) but it also benefits Alternator reverse queries because both use the same underlying implementation.

We already have a test for reverse queries in Alternator, which can be run by
```
test/alternator/run --runveryslow --runxfail test_query.py::test_query_reverse_long
```

The test is still failing, but it demonstrates that a reverse query with `Limit` does work as expected now - even on very large partition - and the remaining problem is for queries that don't specify a `Limit`. Such queries should still be limited to 1MB per page - but today aren't. This is issue #9487.

**Comment by avikivity** [comment]
Not backporting as it's not a regression.
