### ISSUE TITLE
Scylla process should not restart if fail on init

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#759]
If, for any reason, scylla fail to start, there is no reason for systemd to restart it forever and fill the logs.
For example: data dir is not XFS, and developer-mode is not used. This kind of issue will not fix itself and restart does not help.

**Comment by avikivity** [comment]
I don't understand why this happens.  `scylla-server.service` has `Restart=no` and always did.

**Comment by tzach** [comment]
Maybe the scylla-jmx service is too blame?
It requires scylla-server, and have restart always
https://github.com/scylladb/scylla-jmx/blob/master/dist/redhat/systemd/scylla-jmx.service

**Comment by avikivity** [comment]
Good catch sir.

**Comment by dorlaor** [comment]
Wasn't this fixed in systemd?
What will happen in Ubuntu 14?

**Comment by avikivity** [comment]
Fixed by scylladb/scylla-jmx#24cebcc9a1e30975342f2.  Don't know about ubuntu.

**Comment by avikivity** [comment]
@syuu1228 can you verify that scylla-jmx doesn't force restart of scylla when scylla crashes on ubuntu?

**Comment by syuu1228** [comment]
On Upstart, scylla-jmx never launches until scylla-server started successfully.
So I think we don't have a problem on Ubuntu.
