### ISSUE TITLE
NetworkTopologyStrategy data center options are not validated

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#7595]
Apache Cassandra 4.0-beta 3 does not allow creating or altering a keyspace with non-existent DCs for NetworkTopologyStrategy:

```
cqlsh> CREATE KEYSPACE ks WITH replication = { 'class' : 'NetworkTopologyStrategy', 'nonexistentdc' : 1 };
ConfigurationException: Unrecognized strategy option {nonexistentdc} passed to NetworkTopologyStrategy for keyspace ks
```

Scylla 4.4.dev-0.20201111.44e0cb177e, however, does not validate the options:

```
cqlsh> CREATE KEYSPACE ks WITH replication = { 'class' : 'NetworkTopologyStrategy', 'nonexistentdc' : 1 };
```

**Comment by nyh** [comment]
Already in branch 4.5. Backported to next-4.4 (856aeb5ddb5ab19c9d9d5a1b4589846eb7328185 and test a7a1e59594762934d1d383b5591c789454f1bfc5). Not backporting to next-4.3 because it's on its way out, and the test doesn't backport cleanly.
