### ISSUE TITLE
The future that starts hints manager is not waited on

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla#7598]
In main.cc, we spawn a future which starts the hints manager, but we don't wait for it to complete:

https://github.com/scylladb/scylla/blob/d9810ec8ebcdce41960889ad6e522e6674661680/main.cc#L1028-L1034

This can have the following consequences:
- The hints manager does some asynchronous operations during startup, so it can take some time to start. If it is started after we start handling requests, and we admit some requests which would result in hints being generated, those hints will be dropped instead because we check if hints manager is started before writing them.
- Initialization of hints manager may fail, and Scylla won't be stopped because of it (e.g. we don't have permissions to create hints directories). The consequence of this is that hints manager won't be started, and hints will be dropped instead of being written. This may affect both regular hints manager, and the view hints manager.

As it doesn't seem intentional, we should wait until hints manager is started and check if any errors occured.

**Comment by avikivity** [comment]
Backported to 4.3.
