### ISSUE TITLE
test_periodic_commitlog fails with Could not retrieve CDC streams with timestamp {2020/11/13 02:20:56} upon gossip event

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7610]
Seen in https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/654/testReport/commitlog_test/TestCommitLog/test_periodic_commitlog/
Scylla version 5b123758421fa4d3611cb69915b9bf833a3c6527
(includes 78649c2322c63f3156440d86bdecb1c16ddb2efe)
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 648, in run
    self.tearDown()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/commitlog_test.py", line 38, in tearDown
    super(TestCommitLog, self).tearDown()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1118, in tearDown
    self.cleanUpCluster()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1164, in cleanUpCluster
    raise AssertionError('Unexpected errors found: {}'.format(found_errors))
AssertionError: Unexpected errors found: [('node1', ['ERROR 2020-11-13 02:20:35,033 [shard 0] cdc - Could not retrieve CDC streams with timestamp {2020/11/13 02:20:56} upon gossip event. Reason: "std::runtime_error (Could not find CDC generation with timestamp 2020/11/13 02:20:56 in distributed system tables (current time: 2020/11/13 02:20:35), even though some node gossiped about it.)". Action: not retrying.'])]
```

**Comment by bhalevy** [comment]
@kbr- on slack:
> hypothesis: the cdc generation write did not get persisted due to the periodic commit log mode and non-clean node shutdown.
> solution (if the hypothesis is true): we need to ensure that cdc generation writes are always in synchronous commitlog mode -- we cannot consider them successful if they are not persisted.

**Comment by kbr-** [comment]
Managed to reproduce locally by inserting a tactical sleep in commitlog code. In `db::commitlog::segment::cycle()`:
```
        return _pending_ops.run_with_ordered_post_op(... { ...
            return do_with(... { ...
                return repeat(... { ...
                    return seastar::sleep(5s).then(... { ...
                        return _file.dma_write(...
```
with this `sleep` it reproduces every time.

**Comment by avikivity** [comment]
Backported to 4.3.

**Comment by fruch** [comment]
@kbr- 
this is now happening in
4.3 rolling upgrades (and blocks promoting of 4.3.rc3):
https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/rolling-upgrade/job/rolling-upgrade-debian10-test/15

**Comment by kbr-** [comment]
@fruch unrelated to this issue.
I explained on https://github.com/scylladb/scylla/issues/7817

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.

**Comment by juliayakovlev** [comment]
It reproduced with last master:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1127/testReport/repair_based_node_operations_test/TestRepairBasedNodeOperations/test_disable_rbno_2/

```
failed on teardown with "AssertionError: Unexpected errors found: [('node3', ['ERROR 2022-02-22 03:49:24,332 [shard 0] cdc - Could not retrieve CDC streams with timestamp {(2022/02/22 03:49:48, 695a1172-741d-4cb1-8c0b-765ae373936f)} upon gossip event. Reason: "std::runtime_error (Could not find CDC generation (2022/02/22 03:49:48, 695a1172-741d-4cb1-8c0b-765ae373936f) in distributed system tables (current time: 2022/02/22 03:49:24), even though some node gossiped about it.)". Action: not retrying.'])]"
```

**Comment by bhalevy** [comment]
Cc @kbr-

**Comment by kbr-** [comment]
That's a different issue, no node is being killed here.
It seems that on latest master writes or reads or both are broken and we lost the read-your-writes property.

**Comment by juliayakovlev** [comment]
> That's a different issue, no node is being killed here. It seems that on latest master writes or reads or both are broken and we lost the read-your-writes property.

Would you like I'll open new issue?

**Comment by roydahan** [comment]
> > That's a different issue, no node is being killed here. It seems that on latest master writes or reads or both are broken and we lost the read-your-writes property.
> 
> Would you like I'll open new issue?

Yes please.

**Comment by juliayakovlev** [comment]
> > > That's a different issue, no node is being killed here. It seems that on latest master writes or reads or both are broken and we lost the read-your-writes property.
> > 
> > 
> > Would you like I'll open new issue?
> 
> Yes please.

https://github.com/scylladb/scylla/issues/10138

**Comment by kbr-** [comment]
New issue was opened for the new problem, closing this one.
