### ISSUE TITLE
List append uses the wrong timestamp with LWT

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7611]
This is a Gedankenbug - based on thinking aboout the code - I have not reproduced it yet. This issue is closely related to issue #6846, which is a different problem caused by the same underlying faulty implementation.

Scylla's "list" type is a CRDT which allows a write-only "append" operation, not requiring a read. This is implemented by using the current time on the coordinator node as the key of the new item, so that a second append operation will put the new item after the item from the first append operation. Issue #6846 is about problems in choosing this time stamp across multiple coordinator nodes when LWT is *not* involved.

But in this issue, we are looking into list appends **with LWT**. Here, everything should have been simpler - LWT linearizes (i.e., orders) the different appends, and gives a unique timestamp to each of them. We should be using these timestamps, **not** any other notion of "current time", as the timestamp for the appended item.

However, this is not what the code currently does... `lists::do_append()` (`cql3/lists.cc`) uses `utils::UUID_gen::get_time_UUID_bytes()`, i.e., the current time on this server... In issue #6846 we noted that it neglects to use the client timestamp and here we note that it also neglects to use the LWT-specified timestamp.

Unfortunately, there is one additional complication we need to solve beyond *just* using the LWT-chosen timestamp. A single list-append operation may append **multiple items**, not just one. Each of these items needs a different key (timestamp) - they cannot all be using the same one. The current code simply calls `get_time_UUID_bytes()` multiple times, once for each item, in the loop in `lists::do_append()`, and this `get_time_UUID_bytes()` function is guaranteed to increment the timestamp even if called multiple times in the same millisecond. We need similar logic of incrementing the last-used time in the append loop, even if we use the LWT time as a starting point for this loop. However, we will then need some way to ensure that *subsequent* LWT writes will start after all these timestamps. I don't know how to do that. Maybe we may need to extend LWT so that an `apply()` function can return a number N indicating that it just not just the timestamp it was given, but also N subsequent timestamps, so that future LWT rounds will need to skip those too.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
