### ISSUE TITLE
abrt interfering with core dump

### ISSUE THREAD

**Issue by noamha-ken** [scylladb/scylla#762]
Causing the machine to get stuck

**Comment by tzach** [comment]
@noamha-ken what scylla release are you using?
Are you using scylla AMI?
Please provide more context

**Comment by dorlaor** [comment]
It's no surprise, I didn't think abrt is enterprise-ready

**Comment by syuu1228** [comment]
abrt should not use with scylla, we recommend to use systemd-coredump instead.

**Comment by avikivity** [comment]
Yes, but we should prevent abrt from touching scylla cores, is there a way to tell abrt to keep off certain packages?

**Comment by syuu1228** [comment]
@avikivity abrt installs core dump hook on kernel.core_pattern by default, so all SEGV including scylla hooked by it, without condition.
There is a way to getting core files from systemd-coredumpctl and pass it to abrt, but it disables part of abrt, if we can do that I think we should remove whole package then replace with systemd-coredump:
http://abrt.readthedocs.org/en/latest/examples.html

**Comment by avikivity** [comment]
Maybe we can have a conflicts clause in the rpm so users will have to remove it.
