### ISSUE TITLE
Binding a string column in a prepared statement does not fully validate UTF-8

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7637]
The test in `cql-testpy`, `test_validation.py`::`test_validation_utf8_bound_column` demonstrates that when binding a string parameter to a prepared statement, this string is not fully validated to be legal UTF-8. For example, the test demonstrates that an illegal byte \xC0 is recognized, but non-minimal representation like \xCE\x80 (a non-minimal representation of a null) is not rejected. 

A different test in the same file demonstrates that those other illegal UTF-8 are in fact recognized as illegal in other situations, like converting a blob to a string. So we must have the right validation code - but not calling it in the prepared statement binding case?

Note that Cassandra has exactly the same problem, and misses exactly the same illegal UTF-8, so Cassandra also fails on that test.

**Comment by StarostaGit** [comment]
Should there be a commit with the new tests attached to this issue?

**Comment by nyh** [comment]
@avikivity I wrote another test which checked the conversion of Lua output into strings and how non-UTF-8 is handled, and it exhibits exactly the same problem as I reported here for prepared statement binding: while \xC0 is correctly recognized as an invalid UTF-8, a \xCE\x80 is **not** detected as invalid. If I remember correctly, \xCE\x80 is supposed to be detected as invalid, as "non-minimal" representation of null - I remember you mentioned this when you worked on the invalid UTF8 detection.

So is it possible that we have in our code a version of the UTF-8 checking function which doesn't detect non-minimal representation, and both the user-defined functions and prepared statements are using it?

**Comment by avikivity** [comment]
Maybe this is a regression introduced by 6740907f3dfce8e6f8d07937ff0f2afe156de777. We don't have two different utf8 validators that I know of.

**Comment by nyh** [comment]
> Should there be a commit with the new tests attached to this issue?

I sent a patch series to the mailing list, starting with "[PATCH v3 0/3] test/cql-pytest: tests for string validation". I see it is getting no attention, so maybe I'll convert it to a PR now :-(

**Comment by nyh** [comment]
@avikivity it turns out I have a serious bug in my test_validation_utf8_as_blob() test - it fails everything, not just invalid UTF8 (I 
had a test supposedly testing that valid UTF8 works, but that part of the test had a bug). I debug and prepare a new version of the test.

**Comment by nyh** [comment]
@avikivity you're right - the blob conversion, after fixing the test bug, does behave like all the other checks. Seems like \xCE\x80 is accepted by all methods I tried to insert UTF-8. I'll try to figure out why. In any case, I'll close this issue and perhaps open a new one with a better description (it's not specific to prepared statements at all).

**Comment by nyh** [comment]
And it turns out, there is no bug in our UTF-8 validation. All the case I was able to reproduce do seem to work as expected, and the only case which did fail was a typo. Sorry about that. But the fix test has grown (it now covers 4 different cases of string conversion) and I'll send a test PR shortly. But we don't need to open an issue for this test becaue there is no bug it reproduces.
