### ISSUE TITLE
Bypass the cache when reading Alternator Streams

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7639]
@slivne suggested the idea that reads from Alternator Streams (the `GetRecords` operation) should bypass the cache (i.e. do not store the data we read from the CDC log table in the cache).
The thinking is that it is not typical for an application to read again from the stream the same data that it just recently read from it.

**Comment by elcallio** [comment]
Which cache? Do you mean the querier_cache for paging? This should not be used anyway, since we don't (scylla-)page get_records queries.

**Comment by haaawk** [comment]
Probably regular cache -> row_cache. But that should already be bypassed because Alternator Streams read CDC Log which has already row cache disabled.

**Comment by nyh** [comment]
@elcallio yes, I think we do not use the query cache already because we don't use any API that supports paging in GetRecords - but maybe we need to confirm that too. I meant the row cache.
@haaawk I wasn't aware we have a per-table option to turn off the row cache. How is it called?
Before closing this issue, let's confirm - by looking at the code and even better using metrics - that the CDC log table doesn't use space in the cache.

**Comment by slivne** [comment]
PiotrJ that wrote the feature is correct we have an option to disable - but
what we disable is the update of the cache on memtable  flush - on the
write path.

On the read path - the client has control over this - and should be doing
BYPASS CACHE - this is what our sample client library is doing (or should
be doing if its not :) ) - at least based on the metrics I think it is.

**Comment by haaawk** [comment]
https://github.com/scylladb/scylla/blob/master/cdc/log.cc#L523 @nyh 

I verified it myself and we even have dtests for it thanks to @fgelcer

**Comment by haaawk** [comment]
We disable it also on the read path @slivne

**Comment by haaawk** [comment]
If the cache is disabled for the table we don't even create a reader for the cache:
https://github.com/scylladb/scylla/blob/df197e36fb88b10e57ff097dc2f82630ba6b4243/table.cc#L416-L420

And disabling the cache on a table means the cache is disabled:
https://github.com/scylladb/scylla/blob/f2b98b0aadaf25ba6134232f9ff993a9ab168048/database.hh#L527

**Comment by slivne** [comment]
hm ... ok I was not aware - nice going :)

**Comment by slivne** [comment]
closing this - since CDC does this already

**Comment by nyh** [comment]
@slivne, @haaawk said he tested it and even has dtest for it (name?), so it indeed the issue should be closed. 
I didn't close it myself just because I wanted to confirm it myself, but I guess there isn't a real need for me to do it if @haaawk did.

**Comment by haaawk** [comment]
@nyh bypass_cache_test.py

**Comment by nyh** [comment]
@haaawk I don't see this test checking anything with CDC. Would be good to have a test that explicitly tests that the CDC log table is configured this way, and/or directly check that it really bypasses the cache (like the existing tests in bypass_cache_test.py do).

**Comment by haaawk** [comment]
Probably you're right, @nyh. At the moment, we have only dtests that verify the feature of bypassing cache for a table works.
It is quite apparent from the code that the feature is enabled for CDC but having a test wouldn't hurt.

**Comment by nyh** [comment]
I have in `test/alternator/test_tracing.py` an example of a Scylla-only Alternator test which uses the REST API. So I can easily write an Alternator Streams test which verifies that a GetRecords call **really** bypasses the cache - by doing the same GetRecords call twice and note that the second call comes from disk as well. This will ensure that this feature (GetRecords bypasses cache) doesn't break even if one of the implementation details in the middle change. I'll try to do this as soon as I get through the other stuff I was instructed to do.
