### ISSUE TITLE
sstables: mx writer: clustering_blocks_input_range: check that null components form a suffix

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#7650]
Non-full compounds can have null components, but only at the end of the compound. In other words the non-null components must form a prefix and the null components must form a suffix -- a contiguous trail of null components at the end. A null component can never be followed by non-null one.
This is checked and enforced when parsing clustering keys (which is a compound), but it is not checked when writing it. There is only a comment mentioning this assumption, but it is not checked. This can result in scylla writing sstables that it cannot read back.

**Comment by denesb** [comment]
Discovered while investigating https://github.com/scylladb/scylla/issues/7623.

**Comment by raphaelsc** [comment]
good catch!

**Comment by denesb** [comment]
On re-reading the code now I don't see a way that would produce an bad key, the code looks like this:
```c++
        while (_offset < limit) {
            auto shift = _offset % clustering_block::max_block_size;
            if (_offset < _prefix.size(_schema)) {
                // [...] handle non-null component
            } else {
                // This (and all subsequent) values of the prefix are missing (null)
                // This branch is only ever taken for an ephemerally_full_prefix
                _current_block.header |= (uint64_t(1) << ((shift * 2) + 1));
            }
            ++_offset;
        }
```
We start setting the `null` flag once `_offset >= _prefix.size(_schema)` and as we only ever increment `_offset`, there is no way we will take the true branch once we took the false branch once.

**Comment by denesb** [comment]
Closing, the bad keys were coming from somewhere else after all, also on reinspecting the code (see https://github.com/scylladb/scylla/issues/7650#issuecomment-730404847) I don't think this code can produce bad keys anymore.
