### ISSUE TITLE
SSL server/server reinitiazing in a loop

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#766]
When using server/server SSL between two scylla nodes the connections
reinialize itself after ending with "Encrypted Alert".

tcpdump capture attached:

[blib.zip](https://github.com/scylladb/scylla/files/80352/blib.zip)

The git revision is:
9d71e4a7eb4dd1e14b1fc2c3e410462633957661 + "config: Mark previously unused SSL client/server options as used" and "config: Mark ssl_storage_port as Used"

I just added:
server_encryption_options:
    internode_encryption: all
    certificate: seastar/tests/test.crt
    keyfile: seastar/tests/test.key
    truststore: seastar/tests/tls-ca-bundle.pem

at the end of conf/scylla.yaml.

**Comment by slivne** [comment]
@benoit-canet  can you please also add git head, and some info on configuration if all configuration is via a scylla.yaml can you attach the file of the two servers.

**Comment by benoit-canet** [comment]
@slivne modified

**Comment by elcallio** [comment]
I cannot reproduce this using ccm at least. 
Could you provide the log files?
Also, what machines is this run on? It could be an issue with gnutls version (long shot).

**Comment by benoit-canet** [comment]
Hmm I destroyed the rackspace machines which did the test. I was not aware
of ccm at this time.

I saw nothing on stdout when running scylla on a vt.

It was rackspace latest fedora.

**Comment by elcallio** [comment]
btw, the tcpdump says it is truncated, but at the very least I can see it transfers the certificate used. However, I cannot say I know the protocol nitty gritty enough to really determine what happens after that... 

Is there any way to repro this (preferably locally)?

**Comment by benoit-canet** [comment]
I build scylla from source on two rackspace fedoras and just modified the
configuration file with your example blurb launched scylla by hand from the
build/release/scylla binary in two screens I also used a third machine as a
cassandra stress client.

**Comment by elcallio** [comment]
I finally got around to trying to repro this. I could not. TLS between two rackspace nodes using the snakeoil certs worked fine for me (verfied RPC via 7001). 

If you can repro this again, please let me know, otherwise I don't know what more to do.

**Comment by benoit-canet** [comment]
ok, I will retry.

**Comment by elcallio** [comment]
I am pretty sure this issue is obsolete by now.
