### ISSUE TITLE
sstable_conforms_to_mutation_source_test fails: missing dead row marker

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7666]
Seen in https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/next/2827/artifact/testlog/release/sstable_conforms_to_mutation_source_test.19.log
Scylla version 2c8dcbe5c5a85bbf9cb591520e959a222a292eab
```diff
--- /dev/fd/63	2020-11-22 11:31:43.132980052 +0200
+++ /dev/fd/62	2020-11-22 11:31:43.158980201 +0200
@@ -1,4 +1,4 @@
-test/lib/mutation_assertions.hh(108): fatal error: in "test_sstable_conforms_to_mutation_source": Mutations differ, expected 
+ ...but got: 
 {table: 'ks.cf', key: {'pk': 1806000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, token: -9205109811216406580}, mutation_partition: {
   tombstone: {tombstone: timestamp=-9223372036854775805, deletion_time=1},
   range_tombstones: {
@@ -231,7 +231,6 @@
     {
       cont: true,
       dummy: false,
-      marker: {row_marker: dead -9223372036854775766 2},
       position: {
         bound_weight: 0,
         'ck1': b701000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
@@ -304,3 +303,8 @@
   ]
 }
 }
```

**Comment by bhalevy** [comment]
@denesb can you please investigate?

It isn't reproducible using the same `random_seed`.
Maybe it's timing related, similar to #4695?

**Comment by bhalevy** [comment]
Hit again in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2927/artifact/testlog/dev/sstable_conforms_to_mutation_source_test.19.log
[sstable_conforms_to_mutation_source_test.19.log.gz](https://github.com/scylladb/scylla/files/5702098/sstable_conforms_to_mutation_source_test.19.log.gz)

```diff
@@ -1,4 +1,4 @@
-test/lib/mutation_assertions.hh(108): fatal error: in "test_sstable_conforms_to_mutation_source": Mutations differ, expected 
+ ...but got: 
 {table: 'ks.cf', key: {'pk': 1806000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, token: -9205109811216406580}, mutation_partition: {
   tombstone: {tombstone: timestamp=-9223372036854775805, deletion_time=0},
   range_tombstones: {
@@ -229,6 +229,7 @@
     {
       cont: true,
       dummy: false,
+      marker: {row_marker: dead -9223372036854775736 1},
       position: {
         bound_weight: 0,
         'ck1': 6f01000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000,
@@ -495,3 +496,4 @@
   ]
 }
 }
+test/boost/sstable_conforms_to_mutation_source_test.cc(0): Leaving test case "test_sstable_conforms_to_mutation_source"; testing time: 63230827us
```

**Comment by denesb** [comment]
Row markers have the same asymmetry w.r.t. addition (apply) that tombstones have, see https://github.com/scylladb/scylla/issues/8221#issuecomment-791337591.

**Comment by bhalevy** [comment]
I wonder why this issue wasn't reproducible with the random-seed.
Is there another random-number-generator this unit test uses?

**Comment by denesb** [comment]
Try running the entire test suite. Often individual test cases change the state of the random number generator so you need to run the same test cases in the same order to get the same result.

**Comment by bhalevy** [comment]
Of course.  Yet, this test suite has only one test case (`test_sstable_conforms_to_mutation_source`).

**Comment by denesb** [comment]
Maybe it is time related. Worth checking the entire mutation to see if there is a tombstone that can shadow the row marker. The la writer compacts when writing as far as I remember.

**Comment by bhalevy** [comment]
I can't reproduce the issue locally at f44420f2c9f0f6580b134bac34b9e0f997cb2a97.
Closing for now.  We can reopen if the issue is reproduced.
