### ISSUE TITLE
Keyspace strategy class is stored in unqualified form to system tables

### ISSUE THREAD

**Issue by penberg** [scylladb/scylla#767]
If a keyspace is created using a unqualified strategy class name (i.e. no package name) via CQL, Scylla stores the unqualified form whereas Cassandra converts the strategy class into a fully qualified form and stores that.

Reproducer:

```
CREATE KEYSPACE ks WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 };
SELECT * FROM system.schema_keyspaces WHERE keyspace_name = 'ks';
```

Cassandra 2.1.8:

```
cqlsh> SELECT * FROM system.schema_keyspaces WHERE keyspace_name = 'ks';

 keyspace_name | durable_writes | strategy_class                              | strategy_options
---------------+----------------+---------------------------------------------+----------------------------
            ks |           True | org.apache.cassandra.locator.SimpleStrategy | {"replication_factor":"3"}

(1 rows)
```

Scylla:

```
cqlsh> SELECT * FROM system.schema_keyspaces WHERE keyspace_name = 'ks';

 keyspace_name | durable_writes | strategy_class | strategy_options
---------------+----------------+----------------+----------------------------
            ks |           True | SimpleStrategy | {"replication_factor":"3"}

(1 rows)
```

**Comment by slivne** [comment]
@penberg what is the siede effect from this - what issues does this cause ?

**Comment by penberg** [comment]
@slivne I suspect the only practical issue will be that Scylla-generated schemas are not readable by Cassandra.

**Comment by tzach** [comment]
> I suspect the only practical issue will be that Scylla-generated schemas are not readable by Cassandra.

What will be the affect? AFAIU, it will not allow roll back from Scylla to Cassandra, unless you clean the system tables. @penberg do you agree?

**Comment by penberg** [comment]
@tzach Yes, that's what I would expect to happen.

**Comment by tzach** [comment]
@penberg thanks. In this case this is not as urgent, only manifest on Scylla to Cassandra migration which is less likely as a first step.
Lets keep it as best effort for GA, not a must.

**Comment by avikivity** [comment]
Is this still a problem after the migration to 3.x schema?
