### ISSUE TITLE
Throwing a runtime_exception from unimplemented to/from_string()  methods causes an unexpected interruption of a batch_replay flow flow

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#768]
When I run a jepsen "cassandra batch set halves" test with a log level set to `trace` I get the following error:
```
ERROR [shard 0] batchlog_manager - Exception in batch replay: std::runtime_error (virtual sstring timestamp_type_impl::to_string(const bytes&) const not implemented)
```
Naturally the problem goes away if I turn the log level to `error`.

**Comment by slivne** [comment]
@vladzcloudius aside from the error printout is this causing any other issue ?

**Comment by vladzcloudius** [comment]
@slivne Yes - the exception that is causing this printout is thrown from inside replay_all_failed_batches(), which means it interrupted its normal flow thus preventing the `batch replay` from completion.

**Comment by vladzcloudius** [comment]
@slivne I'm seeing it again. This time it looks like it comes from the compaction flow. Pls., reopen the issue.

**Comment by vladzcloudius** [comment]
Pls., don't reopen - this trace message is expected.
