### ISSUE TITLE
Multi-column restrictions deemed invalid with a secondary index

### ISSUE THREAD

**Issue by dekimir** [scylladb/scylla#7680]
The following CQL works fine on Cassandra:
```cql
create table t (p int, c1 int, c2 int, primary key(p, c1, c2));
create index i1 on t(c1);
insert into t(p, c1, c2) values (1, 11, 21);
insert into t(p, c1, c2) values (2, 12, 22);
select c1 from t where (c1,c2)=(11,21) allow filtering;
```
but throws invalid_request_exception on Scylla:
`exceptions::invalid_request_exception (Single value can be obtained from single-column restrictions only)`

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
