### ISSUE TITLE
current master and 4.3 don't properly recognize disk count from metadata

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla#7684]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.3 rc0 + rc1 and master
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

when you run io setup you see an error
```
Problem when parsing disks from metadata:
Extra data: line 1 column 2 (char 1)
ERROR:root:This is not a recommended Google Cloud instance setup for auto tuning, running manual iotune.
```

fix is easy, https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_util.py#L190 should use "True" to get recursive list of objects for parsing for nvme disks

**Comment by avikivity** [comment]
Backported to 4.3.
