### ISSUE TITLE
Deoverlap range tombstones

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#7687]
Currently mutation fragment streams (coming from `flat_mutation_reader`s) must be monotonic, but not strictly monotonic. That is, for two returned fragments `f1` and `f2` from the same partition such that `f2` was returned later than `f1`, `f2.position() >= f1.position()` but not necessarily `f2.position() > f1.position()`.

The only types of fragments causing this behavior are range tombstones: a mutation fragment stream is allowed to return two range tombstones that have the same start position (and hence the same position - the position of a range tombstone is defined by the position of its start).

In this discussion: https://github.com/scylladb/scylla/pull/7437#discussion_r506064414
@avikivity proposed
> We must fix it, it's a constant thorn.

@denesb commented:
> Most components already use range_tombstone_list to collect and emit range tombstones. If we add deoverlapping support there we already cover many users. Then we'd need to make the combined reader use this too, as well as sstable readers. Memtables and cache could deoverlap on insert.

This issue is created as a follow-up to that discussion.

As far as I understand, the goal is to ensure that every mutation fragment stream is strictly monotonic. The way to solve this is to ensure that range tombstones in such streams are non-overlapping, by cutting/merging them when necessary.

**Comment by denesb** [comment]
Deoverlapping range tombstones also solves more than just then non-strictly monotonous nature of fragment streams. It is also the key to keep the memory usage of range tombstones in check. See https://github.com/scylladb/scylla/issues/3672.

**Comment by avikivity** [comment]
@slivne let's schedule the great deoverlap then

**Comment by horschi** [comment]
Would this also apply for range-tombstones and regular tombstones?

**Comment by denesb** [comment]
Only range tombstones, other tombstones never overlap.

**Comment by horschi** [comment]
But range tombstones can overlap with normal tombstones. Would these normal tombstones be superseded by range tombstones?

**Comment by bhalevy** [comment]
> But range tombstones can overlap with normal tombstones. Would these normal tombstones be superseded by range tombstones?

@horschi they may overlap with row-tombstones that are a special case of a range tombstone, covering a single clustering key.

**Comment by bhalevy** [comment]
@denesb / @tgrabiec do we have anything left on this issue?

**Comment by bhalevy** [comment]
Do you consider the flat_mutation_reader_v2 project the fix for this issue?

**Comment by avikivity** [comment]
Yes.
