### ISSUE TITLE
Alternator test test_fetch_from_system_tables failure in debug mode

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7706]
We saw the test `test_system_tables.py`::`test_fetch_from_system_tables` fail once in debug mode. The complete log:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/2844/artifact/testlog/debug/run.2.log

The specific error is:

>  E           botocore.errorfactory.InternalServerError: An error occurred (InternalServerError) when calling the Scan operation (reached max retries: 3): Internal server error: exceptions::read_timeout_exception (Operation timed out for system.compaction_history - received only 0 responses from 1 CL=LOCAL_ONE.)

Looking at the log, I see that this run was extremely slow - Scylla boot took 90 seconds (it normally takes 1-2 seconds) and the whole test suite took an hour (it usually takes around 30 seconds), and the log is full of stalls of 260 ms. I can't find anything else of interest in the log, unfortunately. If this issue is reproducible we could run it with more verbose logging, but as far as I know it only happened once. 

Note that boto3 reports that it retried the same query 3 times before giving up, and all three failed. So if this is a slowness thing, there should be a reason why this **specific** query is particularly slow and failed 3 times, while thousands of other queries that we did all over the test, did not time out. So some things I want to check:

1. Is the timeout we use for a scan, or for system tables, any different from the timeout we use for other queries? We have in `executor.cc` a `default_timeout()` set to 10 seconds. Does this also apply in this scan? 
2. The other test tables in this test suite are tiny and the `system.compaction_history` table in this test can be large. However, the `scan()` call in question is supposed to only return the first page, so shouldn't be particularly big. Could we perhaps be trying to read an excessively long page by default (this scan did not pass any "Limit" parameter), and this is genuinely taking a very long time in this 50-times-slower-than-normal debug run?

**Comment by nyh** [comment]
1. `do_query()` uses `executor::default_timeout()` for the timeout to `service::pager::query_pagers::pager::fetch_page()`, so it seems the 10s timeout still applies - though we need to verify that `fetch_page()` is really handling this timeout parameter correctly.

2. I see in `executor::scan()` that if `Limit` is not set, we use `limit = std::numeric_limits<uint32_t>::max()` as a limit parameter  to `service::pager::query_pagers::pager::fetch_page()`. We need to verify that `fetch_page()` still has its own internal limit, but perhaps it is still very large and leads to a uniquely slow query (all other queries in these tests only produce a small number of replies)?

**Comment by nyh** [comment]
The problem happened again in https://jenkins.scylladb.com/job/scylla-master/job/next/2880/ - see the failed test in https://jenkins.scylladb.com/job/scylla-master/job/next/2880/testReport/junit/test.alternator/test_system_tables/Test___test_fetch_from_system_tables/
I'll try to look into it.

**Comment by nyh** [comment]
So, I ran the full test suite in debug mode on my laptop, and measured the amount of time that test_fetch_from_system_tables takes to Scan the different system tables that this test scans. And yes, **compaction_history** is indeed the slowest one - a single Scan API call (returning a single page) returned 62,949 bytes in a whopping 2.4 seconds. From this number, it's not far-fetched that once in a while, when the test machine is overcommitted (as it always is) but a bit too much, the call will take 10 seconds and timeout.

So I think this explains the direct reason why we're seeing this failure, which it's rare, and why when it happens it's always in the compaction_history table.

There are still things I don't understand:

1. I don't know why scanning this specific table (compaction_history) is the slowest. The Paxos table returned a similar number of bytes, but in just 1 second. The size_estimates table returned 3 times more bytes, but in only 0.8 seconds. Maybe there are other issues at play beyond just number of bytes, like number of separate sstables, complexity of each row, etc.
2. If debug mode does scans so slowly, a 10-second timeout on scans is not a viable default. At least not for debug mode. Should Alternator have different timeout defaults for debug mode? How do we not run into such problems with CQL (dtests, etc.)? Do we configure higher client-defined timeouts in those tests?
3. There is no reason why this test needs to read so many tables. The intention was to check that reading system tables works - and reading one would have been enough - even better, one where we know what to expect (e.g., the list of tables should contain our fixture's table name). Is there a goal for reading *all* of the tables in this test? @psarna ?

**Comment by nyh** [comment]
Answering my own question 2, I just noticed that dtest's `dtest.py` has this code:

```python
timeout = 10000
...
if isinstance(self.cluster, ScyllaCluster) and self.cluster.scylla_mode == 'debug':
    timeout *= 3
...
self.cluster.set_configuration_options(values={
            'read_request_timeout_in_ms': timeout
```

So, indeed, dtest uses a 10-second timeout for the fast build modes - but 30 seconds for debug mode. So it's what I suspected, and we probably need to do something similar in Alternator.

Unfortunately, in Alternator the client has no official way to configure these timeouts, so they are constant in Alternator and not chosen by the test. We can change this constant via "#ifdef DEBUG". Alternatively, we can make this default timeout a configuration parameter, and when running the debug build in test/alternator/run, increase this default. The default-timeout parameter solution is more complex, but I think it's better - it may be useful to override this default in the future for other reasons, and also, the timeout we need in absurdly-overcommitted test runs is not the same one that makes sense in normal production servers.

**Comment by psarna** [comment]
@nyh I used all tables simply because I wanted to cover as many CQL types as possible. I'm absolutely fine with being more selective and just picking a couple of tables to tests, especially if it speeds up test execution without any loss of coverage. I'll take a look and maybe send a quick patch for that soon.

**Comment by psarna** [comment]
And I agree that we need to allow configuring this parameter - a config entry is a good start. Later, when per-session timeouts are available for CQL, the same can be easily done for alternator with a custom header.

**Comment by nyh** [comment]
Good point about the types, although the test does actually test them for any correctness. I'm thinking of maybe setting a low Limit in the test and see if it makes it faster.

**Comment by psarna** [comment]
Right, makes sense, go ahead and try the limit first. I guess it won't help in specific pessimistic cases (e.g. if tombstones are the source of slowness and they all apply to the first row), but it sounds like a great way to reduce the overall execution time anyway.

**Comment by psarna** [comment]
(and historically the first iteration of this test used just a single table and failed, because there was a bug in how we process collections read from the database, that's why I went one step further and used all tables instead of just one)

**Comment by nyh** [comment]
I sent a patch to the mailing list, "[PATCH] alternator, test: make test_fetch_from_system_tables faster", which should make this problem go away.
It adds a small Limit to the slow query.
I'll follow this up with additional patches for making the default timeout configurable, but this patch should already be enough to make the test failures go away.

**Comment by psarna** [comment]
Curious... I applied your patch Nadav, but Scylla keeps failing when running this test manually with pytest...
```
scylla: db/size_estimates_virtual_reader.cc:204: auto db::size_estimates::get_local_ranges(database &)::(anonymous class)::operator()(std::unordered_set<dht::token, std::hash<dh
t::token>, std::equal_to<dht::token>, std::allocator<dht::token>> &&)::(anonymous class)::operator()(const std::optional<dht::token_range::bound> &) const: Assertion `b' failed.
Aborting on shard 0.
Backtrace:
  0x000000000339dcbb
  0x000000000339dc8c
  0x000000000336b8a0
  0x000000000338cffa
  0x000000000338d07a
  0x000000000338d04a
  0x000000000338d015
  0x00007f3d51bc01df
  /lib64/libc.so.6+0x000000000003dbc4
  /lib64/libc.so.6+0x00000000000268a3
  /lib64/libc.so.6+0x0000000000026788
  /lib64/libc.so.6+0x0000000000035fc5
  0x00000000026b8f11
  0x00000000026b8d40
  0x00000000026b8ae2
  0x00000000026b8aaf
  0x00000000026b8a7f
  0x00000000026b8a4b
  0x00000000026c0405
  0x00000000026c08eb
  0x00000000026c08ab
  0x00000000026c085b
  0x00000000026c081b

```

**Comment by psarna** [comment]
I'll try to verify if it's specific to my configuration somehow

**Comment by nyh** [comment]
> I'll try to verify if it's specific to my configuration somehow

Maybe one of the seemingly "system tables" is actually a "virtual table", and it has buggy support for Limit=50 or something?
Curious I don't see this problem on my setup.

**Comment by psarna** [comment]
It's definitely a virtual table, I'm compiling debug now to peek into some variables. The code failed on a specific assert: https://github.com/scylladb/scylla/blob/0cd05dd0fdcf531c6d62dc137e0768b9b2546251/db/size_estimates_virtual_reader.cc#L204, so it should be easy enough to figure out.

**Comment by psarna** [comment]
Ok, found something suspicious:
```cpp
        auto left_inf = boost::find_if(ranges, [] (auto&& r) {
            return !r.start() || r.start()->value() == dht::minimum_token();
        });
        auto right_inf = boost::find_if(ranges, [] (auto&& r) {
            return !r.end() || r.start()->value() == dht::maximum_token();
        });
```
Note that for `right_inf` the condition is not entirely reversed - in left we check for "no start or start == minimum token", and for right we do "no end or **start** is a maximum token" - doesn't really make sense, does it? We should test for the end here... I'll verify and prepare a patch, although I'm not sure how to prepare an isolated test case for this thing.

**Comment by psarna** [comment]
@kbr- I recall you touched this size estimated things lately, right (git blame confirms)? Any hints how to create a small isolated test case for this thing?

**Comment by psarna** [comment]
Well, turns out that it's not the source of the assert, although this condition is still suspicious to me.

**Comment by psarna** [comment]
Ok, found it:
```cpp
    const optional<bound>& end() const {
        return _singular ? _start : _end;
    }
```
that's we we check for start and not end.

**Comment by psarna** [comment]
Waiiit, these ranges are not singular, so it's not the case.

**Comment by psarna** [comment]
Ok, I'm pretty sure I think I know the problem is, so I'll push a pull request soon and continue the discussion from there, in order not to hijack a rather unrelated alternator issue.

**Comment by psarna** [comment]
spin-off from the discussion (well, more of a monologue): https://github.com/scylladb/scylla/pull/7764

**Comment by psarna** [comment]
@nyh I verified your patch on top of my orthogonal fix and it succeeded with satisfying speedup, so it's queued.

**Comment by nyh** [comment]
I want to backport this because the test slowness can cause spurious test failures just the same on older releases.

Backported to next-4.3 (commit 19aff6f995bf96c742d4475deb5d5ed94aa7d5a5), next-4.2 (e5a6199b4d96d0a6c9c2ba4dd61bdf4ffc433f00),
