### ISSUE TITLE
MV/SI: View inconsistencies in base references 

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla#7709]
The materialized view fix in 4749c58068c063bbe90843e3fc6b712500062493 was not enough. It turns out that there is one more
way for a view to sneak into the schema registry which is a `schema_global_ptr`. Moreover,  there is still a caveat regarding 
an upgrade from versions prior to 4.0 where we didn't have computed columns and the view schemas weren't updated.
All of those circumstances open a room for two things:
1. Bad behaviour while in mixed cluster.
2. Race condition when a view (or a base table) is altered, where for a little while, until the merged schema is actually updated in the database object the view schema exists in the schema registry without any base reference - which leads to an internal error (which was previously segfault).

**Comment by avikivity** [comment]
Backported to 4.4. Please assist with 4.3 and below.

**Comment by eliransin** [comment]
> Backported to 4.4. Please assist with 4.3 and below.

@avikivity should I prepare one for 4.2 as well (it is EOL).
