### ISSUE TITLE
Column index metadata is not read nor persisted

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#772]

**Comment by slivne** [comment]
@tgrabiec I need more context here to know if we must fix this or not 

What does this mean

**Comment by tgrabiec** [comment]
@slivne This is needed for tables with indexes. We don't support indexes so I think we can defer it.

**Comment by duarten** [comment]
I think this is fixed by 11474ed4c6ac662ead0c83accd323dfbc0ec68ba, right @penberg?

**Comment by penberg** [comment]
Indeed.
