### ISSUE TITLE
DPDK: EAL: Error Cannot initialize mbuf pools

### ISSUE THREAD

**Issue by Felix-zhoux** [scylladb/scylla#7731]
*Installation details*
Scylla version (or git commit hash):  4.2.0-0.20201025.94597e38e2 
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

Hi, I want to test Scylla's support for DPDK. DPDK mode is configured, and the following error is reported when starting:
```
Dec 02 11:17:53 scylla[29865]: EAL: Error - exiting with code: 1
Dec 02 11:17:53 scylla[29865]: Cause: Cannot initialize mbuf pools
```

The following file contains the complete log content：
[scylla-dpdk-failed.log](https://github.com/scylladb/scylla/files/5626780/scylla-dpdk-failed.log)

Some of my configurations are as follows：
HugePage
```
AnonHugePages:    329728 kB
HugePages_Total:     256
HugePages_Free:       65
HugePages_Rsvd:       63
HugePages_Surp:        0
Hugepagesize:       2048 kB
```
scylla-server
```
# choose following mode: virtio, dpdk, posix
NETWORK_MODE=dpdk
# tap device name(virtio)
TAP=tap0
# bridge device name (virtio)
BRIDGE=virbr0
# ethernet device name
IFNAME=p1p2
# setup NIC's and disks' interrupts, RPS, XPS, nomerges and I/O scheduler (posix)
SET_NIC_AND_DISKS=no
# tune clocksource
SET_CLOCKSOURCE=no
# ethernet device driver (dpdk)
ETHDRV=ixgbe
# ethernet device PCI ID (dpdk)
ETHPCIID=0000:81:00.1
# number of hugepages
NR_HUGEPAGES=128
# user for process (must be root for dpdk)
USER=root
# group for process
GROUP=root
## scylla arguments (for dpdk mode)
SCYLLA_ARGS=" --developer-mode 1 --alternator-address 10.10.10.35 --alternator-port 8800 --log-to-syslog 1 --log-to-stdout 0 --default-log-level debug --network-stack native --dpdk-pmd"
# setup as AMI instance
AMI=no
```
scylla-server.service
```
#Wants=scylla-jmx.service
#Wants=scylla-housekeeping-restart.timer
#Wants=scylla-housekeeping-daily.timer
...
User=root
```

Is it because I missed some configuration?

**Comment by Felix-zhoux** [comment]
This problem can be solved after restarting the operating system.

**Comment by dorlaor** [comment]
Cool. Please report the performance you get. In order to see a significant
gain you'll need to make sure that the network has a large portion of the
work.
Meaning that you should choose the lightest data model, even better use K/V
CQL
and not the alternator and the sharded drivers of cql.
