### ISSUE TITLE
Benchmark with memtier_benchmark fails when data length exceeds 1417

### ISSUE THREAD

**Issue by thirstycrow** [scylladb/scylla#7733]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.1.9
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7

I'm benchmarking scylla's redis port with memtier_benchmark. When I use a data length >= 1417, the benchmark fails with the following output. Benchmarking redis server with the same params does not have any problem. So I guess there may be something wrong when scylla decoding a long redis request.

```
[root@host~]# memtier_benchmark -s benchmark.scylla.qiyi.database -p 9052 --ratio 1:0 -d 1417 --key-maximum 2000000 -c 1 --threads 1 -n 10000
Writing results to stdout
[RUN #1] Preparing benchmark client...
[RUN #1] Launching threads now...
server 10.67.56.75:9052 handle error response: -ERR unknown command ''
server 10.67.56.75:9052 handle error response: -ERR unknown command ''
server 10.67.56.75:9052 handle error response: -ERR unknown command ''
memtier_benchmark: shard_connection.cpp:330: request* shard_connection::pop_req(): Assertion `m_pending_resp >= 0' failed.
Aborted
```

**Comment by syuu1228** [comment]
Seems like this is same issue as #7273, fixed by 7a6ee9858fa1b10dd345002a57ddcf0e3f526191
