### ISSUE TITLE
Allow checking sstable CRC

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#7737]
We currently have no way to check CRCs of sstable data files, neither on a whole file or a per-chunk (when using compression) basis, even though we do write the CRC component.

We should add a method for the user to trigger a CRC check on the data component. Best would be a REST api and optionally a nodetool command too. The API should allow the CRC check to be done on a per keyspace/table/sstable granularity.

Note that there is also the `crc_check_chance` schema option, which we currently hard-code to `1.0` but don't allow the user to change, nor do we consider it. We should also implement this.

/cc @raphaelsc

**Comment by nyh** [comment]
Duplicate of #497 ?
See also my comment in that issue about the status (at the time) of CRC checking.

**Comment by denesb** [comment]
Yes, this is a duplicate, it appears I didn't do a very good job of grepping for what we do in the code.
