### ISSUE TITLE
CQL prepared statements incomplete support for "unset" values

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7740]
In Cassandra issue https://issues.apache.org/jira/browse/CASSANDRA-7304, an idea was raised to add to prepared statement bindings the notion of "unset" values, which are distinct from "null" values: Updating with a null value is tantamount to deleting the cell, while updating with an "unset" value is simply ignored. This "unset" feature makes it possible to use the same prepared statement in more scenarios instead of creating multiple prepared statement for different combinations of columns. 

This feature was added in Cassandra commit 48f644686b48357354f16c74b02b6d2c450a8c2d in April 2015, and was first released  in Cassandra 2.2.0 and the v4 binary protocol, with the following line in the release notes:
``` 
* Distinguish between null and unset in protocol v4 (CASSANDRA-7304)
```
The way to use it in the Python driver (for example) is through a special UNSET_VALUE value, as  documented in https://docs.datastax.com/en/developer/python-driver/3.24/api/cassandra/query/#module-cassandra.query-module-data

We did add support for unset values in Scylla back in January 2017 - see commit 9fb2f31 by @penberg. However, the Cassandra unit tests for this feature -  `cassandra_tests/validation/entities/collection_test.py`::`testMapWithUnsetValues`, and also `testListWithUnsetValues` and `testSetWithUnsetValues` (translated to cql-pytest as part of #7722) fail, and show that we got some of the details in the implementation wrong. At least when collections are involved.

In some of these tests, the UNSET_VALUE behaves like an ordinary null and causes the cell to be deleted, instead of just not doing anything to it. In the last test, `testSetWithUnsetValues`, the behavior is even worse: One of the operations in that test, `UPDATE %s SET s = s - ? WHERE k = 10"` bound with `UNSET_VALUE`, **crashes** Scylla, with the following assertion failure:
```
test_scylla: cql3/sets.cc:327: virtual void cql3::sets::discarder::execute(mutation &, const clustering_key_prefix
 &, const cql3::update_parameters &): Assertion `svalue' failed.
```
This is potentially dangerous - it can be used to DoS Scylla, so I'm upgrading this issue to "bug".

**Comment by nyh** [comment]
@slivne noted that we *did* add support for unset values. Indeed, we did in commit 9fb2f31616dd08bfc6e76bf7323b05a3ecca72a7 (by @penberg), in January 2017. However, this failing test shows that we got some of the details in the implementation wrong - at least when collections are involved (and possibly in other areas as well?).

**Comment by slivne** [comment]
@eliransin if adding support is complex we should start by returning error on those operations - so that users should be aware we are lacking the support

**Comment by eliransin** [comment]
@dekimir this is a high profile bug since it is a different and unexpected behavior on Scylla's side. Lets asses the effort to fix it and if it is more than a small amount of days we might need to first issue an error where it is used and not really supported.
@penberg are we testing it in Gemini (UNSET_VALUES I mean)?

**Comment by nyh** [comment]
@eliransin please note that I have not sent the patch yet with the test. I'm 90% done but stopped at @slivne's request (this is a large test file, and I was converting all of it). If somebody wants to fix this bug, please ping me so I'll finish and send the test.

**Comment by eliransin** [comment]
@nyh , @dekimir wants to fix this bug :smile:

**Comment by nyh** [comment]
Ok, then, I'll send a patch with the test today.

**Comment by nyh** [comment]
Ok, sent a patch, titled "[PATCH] cql-pytest: port Cassandra's collection_test.py". It includes 50 (!) tests, out of which 6 tests fail because of this issue. Five of the tests are marked "xfail" and one is marked "skip" because it crashes Scylla. Look at collection_test.py and search for "#7740" to see all of them.

You can run xfailing tests by passing "--runxfail" to test/cql-pytest/run or pytest. To run the skipped test, I think you need to edit the test and remove the skip.

**Comment by dekimir** [comment]
> @dekimir this is a high profile bug since it is a different and unexpected behavior on Scylla's side. Lets asses the effort to fix it

The crash fix is a [one-liner](https://github.com/dekimir/scylla/commit/c823c0a8d6acc1b6bef845e5d412d2c359b2fe88).  The other fixes are more involved but still just a couple of days.

**Comment by dekimir** [comment]
Ideally, I'd like to wait for Nadav's tests to be committed before submitting my fix.  That way I can just uncomment the `xfail` or `skip` attributes in my patch, instead of creating new unit tests.

**Comment by nyh** [comment]
@dekimir my tests (actually, Cassandra's tests) were already committed, so it will be great if you can submit patches (or even just a partial patch for the crash).

Note that this is not a comprehensive test suite for unset values - just the part that deals with collections. Although it may expose all the bugs we have in unset values, it is also possible it does not. I will continue to port Cassandra tests to our repository and if I discover more unset-value bugs, I'll report them.

**Comment by bhalevy** [comment]
#7870 was merged and manually closed, fixing this issue.
@dekimir please reopen if anything else is missing.

**Comment by nyh** [comment]
Indeed, while the first version of @dekimir's patch tried to address only a single aspect of the broken "unset_value" support in collections, the final version addressed all known problems and previously-xfailing tests, so we can indeed consider this issue to be fixed, and open a new one if we ever discover new problem.
I added a "backport candidate" manually now, like we would get if this issue was closed by a normal "Fixes".

**Comment by avikivity** [comment]
While a bug, this is for a minor and rarely used (and IMO ill advised) feature. Will backport if it's hit in the field.

**Comment by avikivity** [comment]
Backported to 4.3.

**Comment by avikivity** [comment]
(4.4 wasn't vulnerable).
