### ISSUE TITLE
compaction options' typo in schema.cql of snapshot

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#7741]
*Installation details*
Scylla version (or git commit hash): 4.4.dev-0.20201117.df197e36fb8
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

### Description

There is a typo in schema.cql of snapshot, lack of comma after compaction strategy.

    AND compaction = {'class': 'SizeTieredCompactionStrategy''max_compaction_threshold': '32'}

### Test scenario

1. start a cluster (one node)
2. wrong a cs workload
- cassandra-stress write n=100 no-warmup -rate threads=1
3. create snapshot by :  nodetool snapshot
4. check schema.cql in snapshot directory: 
- /var/lib/scylla/data/keyspace1/standard1-xxx/snapshots/xxx/schema.cql

It will fail to use this schema file to restore the schema, cql syntax problem.

**Comment by avikivity** [comment]
Backported to 4.2, 4.3. 4.4 was safe.
