### ISSUE TITLE
Restrictions missing support for "IN" on tables with collections, added in Cassandra 4.0

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7743]
In Cassandra 4.0 (only recently released), it became legal to use "IN" restrictions in a table with collections. When attempting to do that in Scylla, one gets the error message:
```
Cannot restrict clustering columns by IN relations when a collection is selected by the query
```

This feature was requested in https://issues.apache.org/jira/browse/CASSANDRA-12654  and committed in Cassandra commit  5d48b0d38d996cde1954c3c0df0f0f0a5eecfb81 in Dec 2019, but only officially released in Cassandra 4.0, with the release note:

> * Allow IN restrictions on column families with collections (CASSANDRA-12654)

Scylla doesn't support this feature yet, and since we're overhauling restrictions anyway (CC @dekimir) we should probably consider eventually supporting this as well.

Discovered by the Cassandra unit test `cassandra_tests/validation/entities/collection_test.py`::`testInRestrictionWithCollection`  (translated to cql-pytest as part of #7722)

**Comment by vhavel** [comment]
It seems that just removing relevant checks during query validation is sufficient. I've tested that against the `testInRestrictionWithCollection` cql-test unit test.

Would it be ok to enable it straight away? Or is it planned as part of the overhaul you mentioned @nyh? If the former, I can submit a patch.

**Comment by dekimir** [comment]
@vhavel please submit a patch so we can discuss it.  The overhaul will take a while to hit all its goals, so any quick fixes we can get in are welcome.

The one comment I have about your wip commit is this: there is no need for a new unit test -- just delete this xfail instead:
https://github.com/scylladb/scylla/blob/95197a09c91eb719c252abed847b8c035f5f9600/test/cql-pytest/cassandra_tests/validation/entities/collections_test.py#L475

**Comment by vhavel** [comment]
ok, patch sent

**Comment by dekimir** [comment]
Thanks, @vhavel.  Can you please link it here, too, so I don't lose track?

**Comment by nyh** [comment]
As @vhavel discovered, this issue is a duplicate of #4251

**Comment by nyh** [comment]
Already in 4.5 and 4.4, not backporting to 4.3 because it's on its last days and anyway this is a feature, not a bug fix.
