### ISSUE TITLE
Add metrics for the amount of range tombstones processed during read

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#7749]
Range tombstones can cause performance problems. To help identify such cases in production we should add appropriate metrics:
 * to row_cache, which counts range_tombstones returned during read
 * to sstables, to count range_tombstones read from an sstable

**Comment by tgrabiec** [comment]
This should account for dead rows as well

**Comment by gnumoreno** [comment]
Thanks for cross-referencing here, @tgrabiec 

Metrics are a good start but they can not pinpoint ks/cf. We know for a fact that enabling ks/table metrics in the field is not doable. So it will help to have the metrics but hard to dig deeper.

**Comment by raphaelsc** [comment]
In #7636, I suggested implementing tombstone scanned histogram api, which
will allow us to look at it on a per table basis and also understand better
the distribution of scanned tombstones across all queries via the histogram

(Sent from my phone)

**Comment by slivne** [comment]
We need to add this to tracing - since this we do enable from time to time.
