### ISSUE TITLE
`cql_query_test.test_null_value_tuple_floating_types_and_uuids fails` in master when run manually

### ISSUE THREAD

**Issue by ManManson** [scylladb/scylla#7757]
Boost C++ test `cql_query_test.test_null_value_tuple_floating_types_and_uuids` (`test/boost/cql_query_test.cc`) fails in the current master when run in isolation with the following command:

```./build/dev/test/boost/cql_query_test --run_test=test_null_value_tuple_floating_types_and_uuids```

The culprit is the `-c2` option which `test.py` adds automatically to almost all tests, thus limiting shards count for the test to be 2. If the test is run without the argument, it will use all available cores.

Error in the test log:

```
test/lib/cql_assertions.cc(237): ^[[4;31;49mfatal error: in "test_null_value_tuple_floating_types_and_uuids": execute_prepared failed: Expected rows in result set
test/boost/cql_query_test.cc:4426: originally from here^[[0;39;49m
```

For my specific setup it starts to fail when shards count is larger than `16` (hardware: 24 cores, 48 SMT threads). 

*Installation details*
Scylla version (or git commit hash): master

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
