### ISSUE TITLE
Unexcpted assert when adding back a node

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#776]
When restarting node (node1 of 8) under ccm another goes down (node6)

INFO  [shard 0] compaction - Compacted 4 sstables to [/home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-92-Data.db:level=0, ]. 262251118 bytes to 211514320 (~80% of original) in 106874ms = 1.8874MB/s. ~933888 total partitions merged to 752720.
INFO  [shard 0] compaction - Compacting [/home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-89-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-90-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-91-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-93-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-94-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-95-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-96-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-97-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-98-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-99-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-100-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-101-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-102-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-103-Data.db:level=0, ]
INFO  [shard 0] compaction - Compacted 14 sstables to [/home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-104-Data.db:level=0, ]. 126603988 bytes to 126603988 (~100% of original) in 55060ms = 2.19283MB/s. ~453376 total partitions merged to 450548.
INFO  [shard 0] compaction - Compacting [/home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-105-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-106-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-107-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-108-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-109-Data.db:level=0, /home/benoit/.ccm/scylla-head/node6/data/test1/standard1-88b28110b85c11e58034000000000000/test1-standard1-ka-110-Data.db:level=0, ]
INFO  [shard 0] gossip - Node 127.0.0.1 has restarted, now UP
INFO  [shard 0] gossip - InetAddress 127.0.0.1 is now UP
INFO  [shard 0] storage_service - Node 127.0.0.1 state jump to normal
scylla: /home/benoit/scylla/seastar/rpc/rpc_types.hh:58: T& rpc::client_info::retrieve_auxiliary(const sstring&) [with T = const gms::inet_address; sstring = basic_sstring<char, unsigned int, 15u>]: Assertion `it != user_data.end()' failed.

**Comment by tgrabiec** [comment]
Looks similar to #774

**Comment by penberg** [comment]
That assertion should be fixed by:

https://github.com/scylladb/scylla/commit/d68026716e829fc206b22e91efdfb420447531dc
