### ISSUE TITLE
Data covered by a tombstone is not purged in memtable

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#777]
This is a low importance issue, but since I came across it, I thought I'd document it anyway.

In the dtest `repair_additional_test.py:RepairAdditionalTest.repair_row_delete_test` I create a partition with two clustering rows, and then delete one of these rows.

The resulting sstable is (printed by sstable2json):

```
[
{"key": "nadav",
 "cells": [["adamdami:","",1452526387642170],
           ["adamdami:age","00000001",1452526387642170],
           ["kitty:","",1452526387640251],
           ["kitty:_","kitty:!",1452526403579911,"t",1452526403],
           ["kitty:age","00000005",1452526387640251]]}
]
```

The two clustering keys are "adamdami" and "kitty". The "kitty" is the one I deleted, and as expected the sstable includes a range tombstone (the line with the "t") to delete the row. What I didn't expect was to see the old kitty row's cells - the cql row marker and the "age" cell - in the sstable. Clearly, these cells are hidden by the tombstone and could have been eliminated from the sstable.

Note that this is not a compaction issue, as compaction was not done in this case: The creation and deletions were done while the data was in a memtable, and the above was the first time that this data was flushed to an sstable. If I remember correctly (?), in the compaction code we do purge data hidden by a tombstone. Perhaps we should do the same in mutation::apply() in memory, or when flushing mutations to disk.

**Comment by tgrabiec** [comment]
Refs #652

**Comment by nyh** [comment]
Closing as a duplicate of #652.
