### ISSUE TITLE
Reshape for STCS doesn't work

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#7774]
commit hash: f802356572

STCS reshape is not doing anything even if when there are tons of work to do.

That's because no compaction descriptor is being returned by STCS even when the strategy finds something to reshape.

backport it to branch-4.3

**Comment by raphaelsc** [comment]
patch sent to ml as: "sstables: Fix sstable reshaping for STCS"

**Comment by slivne** [comment]
@raphaelsc - what about 4.2 ?

**Comment by raphaelsc** [comment]
> @raphaelsc - what about 4.2 ?

verified reshape is present only in branch 4.3

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
