### ISSUE TITLE
Scylla RPM for 0.15 is not starting scylla-server.service upon installation (verified on AMI image)

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#778]
Scylla AMI scripts (or RPM post scripts) for 0.15 are not starting scylla-server.service 

I was running my cluster testing when I realized not all of the DB nodes were initialized. First, I went to the AMI log to see if the reflector init was properly made:

    [fedora@ip-172-31-34-110 ~]$ cat ami.log 
    [INFO] Started with user data set to:
    [INFO] --clustername scylla-db-cluster-2ab4fef9 --totalnodes 3
    [INFO] Using user data:
    [INFO] --clustername scylla-db-cluster-2ab4fef9 --totalnodes 3
    [INFO] Using instance type: c4.xlarge
    [INFO] meta-data:instance-type: c4.xlarge
    [INFO] meta-data:local-ipv4: 172.31.34.110
    [INFO] meta-data:public-hostname: ec2-54-201-196-142.us-west-2.compute.amazonaws.com
    [INFO] meta-data:ami-launch-index: 1
    [INFO] meta-data:reservation-id: r-61d05ca4
    [INFO] Using cluster name: scylla-db-cluster-2ab4fef9
    [INFO] Using cluster size: 3
    [INFO] Using seed indexes: [0, 3, 3]
    [INFO] Reflector loop...
    [INFO] 01/11/16-22:07:23 Reflector: Received 1 of 1 responses from: [u'172.31.34.109']
    [INFO] scylla.yaml configured.

So yeah, that part was fine. When I looked at the port 9042:

    [fedora@ip-172-31-34-110 ~]$ netstat -a | grep :9042
    [fedora@ip-172-31-34-110 ~]$

The service wasn't started. After I started it, the port 9042 was bound to the scylla service:

    [fedora@ip-172-31-34-110 ~]$ sudo systemctl start scylla-server.service
    [fedora@ip-172-31-34-110 ~]$ netstat -a | grep :9042
    tcp        0      0 0.0.0.0:9042            0.0.0.0:*               LISTEN     

Users of the AMI have the expectation that the services are properly started after the nodes have been launched.

Scylla version:

    [fedora@ip-172-31-34-110 ~]$ rpm -qa | grep scylla
    scylla-jmx-0.15-20160108.f4e6a27.fc22.noarch
    scylla-server-debuginfo-0.15-20160108.b7d5fbe.fc22.x86_64
    scylla-server-0.15-20160108.b7d5fbe.fc22.x86_64
    scylla-tools-0.15-20160108.0818731.fc22.noarch

Steps to reproduce:

* Start some small number (let's use 3) of scylla AMI (in my case, I tried ami-20776841) with user data `--clustername scylla-db-cluster-2ab4fef9 --totalnodes 3`

Outcome:

* The scylla service on some of these nodes never come up (2 out of 3 in this example). Test it with `netstat -a | grep :9042`

Expected outcome:

* The scylla service starts on all nodes

**Comment by lmr** [comment]
One thing to note here is that I haven't tested it in more recent versions of the AMI. I was using the same AMI for 0.14 because I wanted to keep the AMI stable for the purposes of developing cluster tests (and the new MOTD banner on those new images was breaking assumptions of the tests). I'm going to try it out with the most recent AMI.

**Comment by slivne** [comment]
So thats probably the issue

I tested the AMI of 0.15 and it was working ok - I started  a cluster of 3
nodes and all booted and connected.

I just tested a single server and it also worked ok.

Tzach do we invalidate (make them private) the old AMIs ?

**Comment by tzach** [comment]
> Tzach do we invalidate (make them private) the old AMIs ?

I usually keep 2 older versions, in case someone use them in its scripts.
Since older AMI have known issues, its probably better to delete them till we GA

**Comment by tzach** [comment]
@lmr why do the RPM needs to starts the service? its make sense with the AMI, but not when installing RPMs. What is the convention other RPMs do they start the service automatically?
AFAIK, its not the case.

**Comment by slivne** [comment]
Just to be clear this is a bug we should find a way to make this work /
support a case of upgrade on the ami - yet it is only High not a
Showstopper

**Comment by lmr** [comment]
@tzach, like @slivne said, it's a bug, but not a high priority one on the AMI upgrade account. I put a workaround in the test programs, so on my end, things are clear. But we have to decide  what to do with the older AMIs.

**Comment by slivne** [comment]
We have decided that for ga we are releasing pre installed amis and not pulling any updates

As such the ami will not pull anymore updates of scylla like it did before 

Until we change this there is less aneed to support updates specific to the ami

Updates in general should be suppprted

**Comment by slivne** [comment]
the ami is not doing updates any more on restart 

commit 71a26e14121293c05c4bf5a27e68c6c33b25dd66
Author: Takuya ASADA <syuu@scylladb.com>
Date:   Sat Jan 30 11:53:06 2016 -0500

    dist: don't need AMI_KEEP_VERSION anymore, since we fixed the issue that 'yum update' mistakenly replaces scylla development version with release version
    
    It actually doesn't called unconditionally now, (since $LOCAL_PKG is always empty) so we can safely remove this.
    
    Signed-off-by: Takuya ASADA <syuu@scylladb.com>
