### ISSUE TITLE
Large partition/cell/row tables are broken in master

### ISSUE THREAD

**Issue by amnonh** [scylladb/scylla#7782]
I'm using 4.4.dev-0.20201201.ea9c058be

My test that creates large cell large row and large partition that used to work, is no longer working

I still see the traces for it, but the information does not enter the table, I did see a large-cell but it got deleted quickly, so maybe it's TTL related.

**Comment by avikivity** [comment]
Please provide more information. What test? Is there a way to reproduce it?

**Comment by amnonh** [comment]
I have a python script that does the following:
I have a keyspce/table called: `testing.bigcell `

`testing.bigcell  {"col1": "timestamp", "col2": "text", "key": "col1", "col3": "blob"}`

here is a simplified version of the code that creates big cell:
```
def big_cell(args, session):
    ts = datetime.datetime.now()
    blob = ""
    for i in range(3000000):
        blob = blob + "x"
    session.execute(
        """
        INSERT INTO testing.bigcell (col1, col2, col3)
        VALUES (%s, %s, %s)
        """,
        (ts, "hello", bytearray(blob, 'utf-8'))
```

I then do nodetool flush and check `select keyspace_name, table_name,partition_key, clustering_key,  column_name,cell_size  from system.large_cells`

And the table is empty, at one occurrence, I saw there was a row in the large_cell table, but after a minute or two, the table was empty again.

I have similar tests for large rows and large partitions, all of them used to work and now they don't

**Comment by avikivity** [comment]
> I have a python script that does the following:
> I have a keyspce/table called: `testing.bigcell `
> 
> `testing.bigcell {"col1": "timestamp", "col2": "text", "key": "col1", "col3": "blob"}`
> 
> here is a simplified version of the code that creates big cell:
> 
> ```
> def big_cell(args, session):
>     ts = datetime.datetime.now()
>     blob = ""
>     for i in range(3000000):
>         blob = blob + "x"

This hurts my eyes. Write `'x' *  3000000`


>     session.execute(
>         """
>         INSERT INTO testing.bigcell (col1, col2, col3)
>         VALUES (%s, %s, %s)
>         """,
>         (ts, "hello", bytearray(blob, 'utf-8'))
> ```
> 
> I then do nodetool flush and check `select keyspace_name, table_name,partition_key, clustering_key, column_name,cell_size from system.large_cells`
> 
> And the table is empty, at one occurrence, I saw there was a row in the large_cell table, but after a minute or two, the table was empty again.
> 
> I have similar tests for large rows and large partitions, all of them used to work and now they don't

/cc @bhalevy

**Comment by raphaelsc** [comment]
@bhalevy looks like it's TTL related. don't think we're incorrectly deleting an entry because as fromthe description, it doesn't seem like the single generated sst is unlinked.

**Comment by slivne** [comment]
If I recall correctly we currently record information about large_*** only
on compaction not on the regular write path.

@Amnon Heiman <amnon@scylladb.com> (assuming you are using smp=1) you need
to
1. Insert in CQL
2. nodetoo flush
3. insert some more in CQL
4. ndoetool flush
5. nodetool compact.

**Comment by nyh** [comment]
> My test that creates large cell large row and large partition that used to work, is no longer working

Amnon, can you please create a public test for this and the other tests you described, so in the future it won't just be "your" tests and if it ever breaks again, everyone will see it?
You can do it either in dtest, or if you're adventurous, you can also do it in my new simpler and faster cql-pytest (I can help you write it - since this will be the first cql-pytest that will need to use the REST API, it will be a bit more complicated to write).

**Comment by amnonh** [comment]
Technically of course I can, but it has nothing to do with what I'm doing.

I want to manually add some items to a table because I wanted to test some aspect of the monitoring stack. so write few lines of python instead of one CQL command, I'm not testing this feature, I'm testing the monitoring stack and run into a situation that this feature is not working.

**Comment by bhalevy** [comment]
We have plenty of dtests for large cells/rows/partitions in [wide_rows_test.py](https://github.com/scylladb/scylla-dtest/blob/29790aae002c059113bd69bc996d13e9476d693e/wide_rows_test.py)
so we need to figure out what you did differently.

**Comment by bhalevy** [comment]
@amnonh is it possible your tests stopped working in 4.3, where we disabled removal of large data entries?
FWIW, The "official" dtests for large data are passing in 4.4.dev

**Comment by amnonh** [comment]
@bhalevy I'm not sure when was the previous time it did work, I've pulled master sometimes ago and last week when I needed to test large entities, I've noticed that I do see the traces, but there are no entries to the table.

**Comment by amnonh** [comment]
After talking to @bhalevy I've pulled master and things start working again, so I'm closing this issue
