### ISSUE TITLE
querier_cache: insert() iterates over all entries

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#7795]
HEAD: https://github.com/scylladb/scylla/commit/19ff528ef3095ad5d0da9fbed6d413f0180fa4db
Currently when inserting a new entry into the querier_cache, we iterate over all current entries to determine their current total memory consumption. This can start to become a significant CPU consume drag when the number of entries is very large (~10K). This situation can happen if for some reason the client fires a lot of multi-paged queries but abandons them after the first page. 

The solution is to maintain a memory consumption counter, just like we maintain the population one currently, instead of calculating it on every insert.

**Comment by avikivity** [comment]
Very odd, since 10,000 * 128k = 1.2GB. How can we cache so many queriers?

**Comment by denesb** [comment]
This 10K was observed with an older version (2019.1) which doesn't use the `reader_permit` for memory accounting and hence it it possibly under-estimates the querier's memory consumption.

**Comment by denesb** [comment]
I have a series which make this obsolete.

**Comment by denesb** [comment]
Solved by 913d970c641484a2708aff4d38750c68a06bacfa.
