### ISSUE TITLE
make tools packageable

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#7801]
We currently have two tool binaries: `scylla-types` and `scylla-sstable-index`, but they are not included in packaging due their massive size. As our code-base is not modularized, we practically compile our entire code-base into each tool, making them as big as the main scylla executable.

The proper solution would be to modularize our code-base and allow pulling in just the modules needed for each tool, as these tools are focusing on a certain task, they need only a small sub-set of the code. But we are far away from this. In the meanwhile @avikivity proposed to merge all tools into the main scylla binary and switch on `argv[0]`:
* `scylla [...]` starts the database
* `scylla-types [...]` starts the scylla types tool
* `scylla-sstable-index [...]` starts the sstable-index tool

**Comment by bhalevy** [comment]
@avikivity:
> > We'll also want to adjust the Seastar defaults not to allocate all 
> > memory and all cores of the machine.

@denesb 
> Yes, we need a tool mode for seastar, that, in addition to not taking
> over the entire system, also doesn't expose all the various tuning
> parameters that are irrelevant to a tool that doesn't care about
> performance.

**Comment by nyh** [comment]
> In the meanwhile @avikivity proposed to merge all tools into the main scylla binary and switch on `argv[0]`:

This is a good idea. It was a very common trick in the Unix world, especially in the old days when every bite counted and even a hundred K overhead for each separate executable was deemed too much. It's not as common today with the humongous modern disks and after the advent of _shared libraries_ - but when the binary itself is humongous (as it is in our case) and not split into shared libraries, it starts to make sense again.
