### ISSUE TITLE
unexpected NEW_NODE event in restart

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#7805]
*Installation details*
Scylla version (or git commit hash): 4.4.dev-0.20201202.c7311d108
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

#### Description

Create a cluster with two nodes, and restart the second node (node2), total 3 events will be sent to node1:

- Source 127.0.59.1 sent {'change_type': 'DOWN', 'address': ('127.0.59.2', 9042)}
- Source 127.0.59.1 sent {'change_type': 'NEW_NODE', 'address': ('127.0.59.2', 9042)}
- Source 127.0.59.1 sent {'change_type': 'UP', 'address': ('127.0.59.2', 9042)}

#### Problem

It seems the NEW_NODE is unexpected, it should only be sent for JOINING.

#### test code:

```
    def restart_node_localhost_test(self):
        """
        Test that we don't get client notifications when rpc_address is set to localhost Pre 4.0.
        Test that we get correct client notifications when rpc_address is set to localhost Post 4.0.
        @jira_ticket  CASSANDRA-10052
        @jira_ticket  CASSANDRA-15677

        Scylla doesn't support nodes with same IP, it's worth to test it.

        To set-up this test we override the rpc_address to "localhost" for all nodes, and
        therefore we must change the rpc port or else processes won't start.
        """
        cluster = self.cluster
        cluster.populate(2)
        node1, node2 = cluster.nodelist()

        cluster.start(wait_for_binary_proto=True)

        # register for notification with node1
        waiter = NotificationWaiter(self, node1, ["STATUS_CHANGE", "TOPOLOGY_CHANGE"])

        # restart node 2
        debug("Restarting second node...")
        node2.stop(wait_other_notice=True)
        node2.start(wait_other_notice=True)

        # check that node1 did not send UP or DOWN notification for node2
        debug("Waiting for notifications from {}".format(waiter.address,))
        notifications = waiter.wait_for_notifications(timeout=30.0, num_notifications=3)
        self.assertEquals(3, len(notifications))
        for notification in notifications:
            assert node2.address() == notification["address"][0]
        assert "DOWN" == notifications[0]["change_type"]
        assert "NEW_NODE" == notifications[1]["change_type"]
        assert "UP" == notifications[2]["change_type"]
```

/Cc @asias @roydahan

**Comment by amoskong** [comment]
It might be problem of _endpoints_pending_joined_notification.

```
void cql_server::event_notifier::on_join_cluster(const gms::inet_address& endpoint)
{
    if (!gms::get_local_gossiper().is_cql_ready(endpoint)) {
        _endpoints_pending_joined_notification.insert(endpoint);
        return;
    }

    send_join_cluster(endpoint);
}
void cql_server::event_notifier::on_up(const gms::inet_address& endpoint)
{
    if (_endpoints_pending_joined_notification.erase(endpoint)) {
        send_join_cluster(endpoint);
    }

    bool was_up = _last_status_change.contains(endpoint) && _last_status_change.at(endpoint) == event::status_change::status_type::UP;
    _last_status_change[endpoint] = event::status_change::status_type::UP;
    if (!was_up) {
        for (auto&& conn : _status_change_listeners) {
            using namespace cql_transport;
            if (!conn->_pending_requests_gate.is_closed()) {
                conn->write_response(conn->make_status_change_event(event::status_change::node_up(endpoint, conn->_server_addr.port())));
            };
        }
    }
}
```

----

After sleep 120 seconds before restarting node2, the NEW_NODE event disappeared.

```
    def restart_node_test(self):
        """
        Test that we get correct client notifications during restart
        """
        cluster = self.cluster
        cluster.populate(2)
        node1, node2 = cluster.nodelist()

        cluster.start(wait_for_binary_proto=True)
        time.sleep(120)

        # register for notification with node1
        waiter = NotificationWaiter(self, node1, ["STATUS_CHANGE", "TOPOLOGY_CHANGE"])

        # restart node 2
        debug("Restarting second node...")
        node2.stop(wait_other_notice=True)
        node2.start(wait_other_notice=True)

        # check that node1 did not send UP or DOWN notification for node2
        debug("Waiting for notifications from {}".format(waiter.address,))
        notifications = waiter.wait_for_notifications(timeout=30.0, num_notifications=2)
        self.assertEquals(2, len(notifications))
        for notification in notifications:
            assert node2.address() == notification["address"][0]
        assert "DOWN" == notifications[0]["change_type"]
        assert "UP" == notifications[1]["change_type"]
```

**Comment by slivne** [comment]
@avelanarius I  think you had a patch around new_node area related to cdc / java driver

**Comment by asias** [comment]
@amoskong can you share a branch of your dtest?

**Comment by asias** [comment]
I think this is not a problem. 

And this is what happens:

node1 is the the only node in the cluster
node2 is being added to the cluster
node1 sees node2 as the new node, but node2 hasn't started cql, so node1 doest not send  NEW_NODE event to  clients
node2 restarted
node1 sees node is down, it sends DOWN event to clients
node2 finishes restart
node1 runs on_up and find it hasn't send NEW_NODE to clients. So it sends NEW_NODE and then UP event to clients.

**Comment by asias** [comment]
In the test, we do wait for the cql to be up before restart 2. Why does node1 not see node2 is up before node2 is restarted? This is because node1 knows node2' cql is ready by checking gms::application_state::RPC_READY from node2. It is possible that node1 hasn't know RPC_READY from node2 before node2 is restarted. That's why the delay of 120s makes the NEW_EVENT goes before DOWN.

```
        cluster.start(wait_for_binary_proto=True)
        time.sleep(120)

        # register for notification with node1
        waiter = NotificationWaiter(self, node1, ["STATUS_CHANGE", "TOPOLOGY_CHANGE"])

        # restart node 2
        debug("Restarting second node...")
        node2.stop(wait_other_notice=True)
        node2.start(wait_other_notice=True)
```

**Comment by amoskong** [comment]
> @amoskong can you share a branch of your dtest?

https://github.com/scylladb/scylla-dtest/blob/next/pushed_notifications_test.py#L226
- restart_node_localhost_test

**Comment by amoskong** [comment]
> I think this is not a problem.
> 
> And this is what happens:
> 
> node1 is the the only node in the cluster
> node2 is being added to the cluster
> node1 sees node2 as the new node, but node2 hasn't started cql, so node1 doest not send NEW_NODE event to clients

In the test, cluster is started by `cluster.start(wait_for_binary_proto=True)`. it will wait until cql server is listened on two nodes. But NEW_NODE isn't sent.

> node2 restarted
> node1 sees node is down, it sends DOWN event to clients
> node2 finishes restart
> node1 runs on_up and find it hasn't send NEW_NODE to clients. So it sends NEW_NODE and then UP event to clients.

**Comment by amoskong** [comment]
> In the test, we do wait for the cql to be up before restart 2. Why does node1 not see node2 is up before node2 is restarted? This is because node1 knows node2' cql is ready by checking gms::application_state::RPC_READY from node2. It is possible that node1 hasn't know RPC_READY from node2 before node2 is restarted. That's why the delay of 120s makes the NEW_EVENT goes before DOWN.

I will fix dtest, let's close this issue as NOT a BUG.
> 
> ```
>         cluster.start(wait_for_binary_proto=True)
>         time.sleep(120)
> 
>         # register for notification with node1
>         waiter = NotificationWaiter(self, node1, ["STATUS_CHANGE", "TOPOLOGY_CHANGE"])
> 
>         # restart node 2
>         debug("Restarting second node...")
>         node2.stop(wait_other_notice=True)
>         node2.start(wait_other_notice=True)
> ```
