### ISSUE TITLE
scylla-kernel-conf is not optional

### ISSUE THREAD

**Issue by npeshek-spotx** [scylladb/scylla#7808]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.2.2
Cluster size: 16 nodes
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.8.2003

In Scylla 4.2.2, you recommend that "If you wish to keep tuned installed (not recommended), don't install the scylla-kernel-conf subpackage."

Issue: You cannot skip installing scylla-kernel-conf, so it automatically obsoletes tuned no matter what decision I try and make.

**Comment by avikivity** [comment]
You can avoid installing scylla-kernel-conf by not installing the scylla rpm. just the sub-packages you want (e.g. scylla-server, scylla-conf).

Note there will be a performance impact.

**Comment by avikivity** [comment]
No response -> closing.

**Comment by npeshek-spotx** [comment]
I'm going to re-open this. By adding the obsoletes, we have to hack around to actually install tuned. (Even if we don't install scylla-kernel-conf, when you attempt to restore tuned, it will be marked as uninstallable because it's obsoleted by scylla-kernel-conf) We use tuned to validate and enforce applying the configs you're providing via our configuration management system. Why not provide a tuned profile and enable it rather than blowing the program away?
