### ISSUE TITLE
Upstart service readiness monitoring (ubuntu)

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#781]
5809ed476f50e9441 ("Merge "Orderly service startup for systemd"") added support for notifying systemd when scylla startup is complete and it can report success to the user.  We need to do the same Uith ubuntu.  I see that upstart supports this, via:

`expect stop` in the service configuration file

raise(SIGSTOP) in `supervisor_notify()`.

**Comment by syuu1228** [comment]
Implemented at https://github.com/scylladb/scylla/commit/b92a075a34e64879461ce48994ab513328595736, can be close.
