### ISSUE TITLE
c-s connection reset during nemesis StopStartService.

### ISSUE THREAD

**Issue by shoshan** [scylladb/scylla#7813]
*Installation details*
Scylla version (or git commit hash): `4.4.dev-0.20201217.a60c81b61 with build-id 2d4859128c252569f28931ada0b983ef01df4f52`
Cluster size: 6 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0bf8983bac85cb9f4` (aws: eu-north-1)

Test: `longevity-10gb-3h-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-10gb-3h.yaml] (https://github.com/scylladb/scylla-cluster-tests/blob/0469aa4032849c0a34e90ff5a167f4aee1fd90c9/test-cases/longevity/longevity-10gb-3h.yaml)

Restore Monitor Stack command: `$ hydra investigate show-monitor 5e8a3314-2fd5-4ca2-967f-d80aa14457b1`
Show all stored logs command: `$ hydra investigate show-logs 5e8a3314-2fd5-4ca2-967f-d80aa14457b1`

Test id: `5e8a3314-2fd5-4ca2-967f-d80aa14457b1`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_055209/grafana-screenshot-longevity-10gb-3h-test-scylla-per-server-metrics-nemesis-20201218_055558-longevity-10gb-3h-master-monitor-node-5e8a3314-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_055209/grafana-screenshot-longevity-10gb-3h-test-scylla-per-server-metrics-nemesis-20201218_055558-longevity-10gb-3h-master-monitor-node-5e8a3314-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_055209/grafana-screenshot-overview-20201218_055209-longevity-10gb-3h-master-monitor-node-5e8a3314-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_055209/grafana-screenshot-overview-20201218_055209-longevity-10gb-3h-master-monitor-node-5e8a3314-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_060434/grafana-screenshot-longevity-10gb-3h-test-scylla-per-server-metrics-nemesis-20201218_060752-longevity-10gb-3h-master-monitor-node-5e8a3314-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_060434/grafana-screenshot-longevity-10gb-3h-test-scylla-per-server-metrics-nemesis-20201218_060752-longevity-10gb-3h-master-monitor-node-5e8a3314-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_060434/grafana-screenshot-overview-20201218_060434-longevity-10gb-3h-master-monitor-node-5e8a3314-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_060434/grafana-screenshot-overview-20201218_060434-longevity-10gb-3h-master-monitor-node-5e8a3314-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_061448/db-cluster-5e8a3314.zip](https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_061448/db-cluster-5e8a3314.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_061448/loader-set-5e8a3314.zip](https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_061448/loader-set-5e8a3314.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_061448/monitor-set-5e8a3314.zip](https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_061448/monitor-set-5e8a3314.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_061448/sct-runner-5e8a3314.zip](https://cloudius-jenkins-test.s3.amazonaws.com/5e8a3314-2fd5-4ca2-967f-d80aa14457b1/20201218_061448/sct-runner-5e8a3314.zip)

There is unexpected connection reset during StopStartService.

**Disruption:**
`
2020-12-18 05:55:07.801: (DisruptionEvent Severity.NORMAL): type=StopStartService subtype=start node=Node longevity-lwt-3h-master-db-node-f5f080c9-3 [13.53.35.239 | 10.0.3.160] (seed: False) duration=None
`

**Error** 
`
2020-12-18 05:55:08.000: (DatabaseLogEvent Severity.ERROR): type=DATABASE_ERROR regex=Exception  line_number=22057 node=Node longevity-lwt-3h-master-db-node-f5f080c9-3 [13.53.35.239 | 10.0.3.160] (seed: False)
2020-12-18T05:55:08+00:00  longevity-lwt-3h-master-db-node-f5f080c9-3 !INFO    | scylla: [shard 7] cql_server - exception while processing connection: std::system_error (error system:104, sendmsg: Connection reset by peer)

`

**Comment by fruch** [comment]
@shoshan it was during  `AddDropColumnMonkey`..

**Comment by shoshan** [comment]
@fruch 

error occurred again 
Test-id: 60c51cb8-687f-4fcd-bc86-ae11d36eed29
scylla-master/longevity/longevity-10gb-3h-test#253: 2020-12-20 17:47:19


`2020-12-20 19:03:16.720: (DisruptionEvent Severity.NORMAL): type=StopStartService subtype=start node=Node longevity-10gb-3h-master-db-node-60c51cb8-4 [13.53.123.95 | 10.0.3.36] (seed: False) duration=None
2020-12-20 19:03:17.000: (DatabaseLogEvent Severity.ERROR): type=DATABASE_ERROR regex=Exception  line_number=28030 node=Node longevity-10gb-3h-master-db-node-60c51cb8-4 [13.53.123.95 | 10.0.3.36] (seed: False)
2020-12-20T19:03:17+00:00  longevity-10gb-3h-master-db-node-60c51cb8-4 !INFO    | scylla: [shard 0] cql_server - exception while processing connection: std::system_error (error system:104, sendmsg: Connection reset by peer)
2020-12-20 19:04:27.000: (DatabaseLogEvent Severity.NORMAL): type=BOOT regex=Starting Scylla Server line_number=28243 node=Node longevity-10gb-3h-master-db-node-60c51cb8-4 [13.53.123.95 | 10.0.3.36] (seed: False)
`
