### ISSUE TITLE
Load and stream arbitrary sstables

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#7831]
This feature extends the nodetool refresh to allow loading arbitrary sstables that do not belong to a node into the cluster.  It loads the sstables from disk and calculates the owning nodes of the data and streams to the owners automatically.

From example, say the old cluster has 6 nodes and the new cluster has 3 nodes. We can copy the sstables from the old cluster to any of the new nodes and trigger the load and stream process.  

This can make restores and migrations much easier.

**Comment by slivne** [comment]
@asias we need more info here:
- old cluster 3 nodes (nodes: O1, O2, O3)
- RF is 3
- new cluster is 6 nodes (nodes: N1, N2, N3, N4, N5, N6)

On node N1 data from O1 is placed and nodetool refresh is run - is the data spread across the cluster  to all 3 replicas ?

**Comment by asias** [comment]
> 
> 
> @asias we need more info here:
> 
>     * old cluster 3 nodes (nodes: O1, O2, O3)
> 
>     * RF is 3
> 
>     * new cluster is 6 nodes (nodes: N1, N2, N3, N4, N5, N6)
> 
> 
> On node N1 data from O1 is placed and nodetool refresh is run - is the data spread across the cluster to all 3 replicas ?

Yes.  We can also place 50% of data from O1 to N1 and the other 50% to N2 to speed up the restore.

**Comment by avikivity** [comment]
> > @asias we need more info here:
> > ```
> > * old cluster 3 nodes (nodes: O1, O2, O3)
> > 
> > * RF is 3
> > 
> > * new cluster is 6 nodes (nodes: N1, N2, N3, N4, N5, N6)
> > ```
> > 
> > 
> > On node N1 data from O1 is placed and nodetool refresh is run - is the data spread across the cluster to all 3 replicas ?
> 
> Yes. We can also place 50% of data from O1 to N1 and the other 50% to N2 to speed up the restore.

That doesn't work. You can have partition P1 from O1, O2, O3 go to N1 by accident, and you lose quorum.

**Comment by avikivity** [comment]
(it's enough to replicate each partition to two nodes, but that causes repair work later)

**Comment by slivne** [comment]
@asias its not clear what your yes was about.

Is the idea to replicate the data from O1 to all the replicas in the new cluster - thus copying each partition/row RF times ?

That would mean that we are streaming the data RF-Old*RF-New  times ... which is the exact same thing we are doing if we had to write all the data to the cluster using sstableloader. 

However, since we are placing the data on a node inside the cluster its more demanding on disk space then if it was done externally. 

If this is going to be used for migrations / restoring a backup into a new cluster - it may not be usable.

In some migrations - the mode of operation is to use a huge node and then place on it all the data from the old cluster and then compact it - following that sstableloader is run (causing the data to be written once into the cluster and data is replciated only RF times.

I think we should consider using RF in new cluster being 1 loading the data and then switching RF and repairing.

**Comment by asias** [comment]
> @asias its not clear what your yes was about.

Yes was about the data will be streamed to all 3 replicas. This is at least one of the mode that can work. We can stream only one replica to primary replica and then run repair. That is the another mode that can work. I plan to support both. It is super easy to support streaming to primary replica only, it is just a matter of choosing the target node. 

> 
> Is the idea to replicate the data from O1 to all the replicas in the new cluster - thus copying each partition/row RF times ?
> 
> That would mean that we are streaming the data RF-Old*RF-New times ... which is the exact same thing we are doing if we had to write all the data to the cluster using sstableloader.

RF-old * RF-new is the max streaming amplification. We can choose to stream only RF-old * 1 times. 

> 
> However, since we are placing the data on a node inside the cluster its more demanding on disk space then if it was done externally.

This is true. This feature can be extended to into a standalone tool for extreme use cases when space on new cluster is very tight. 

> 
> If this is going to be used for migrations / restoring a backup into a new cluster - it may not be usable.
> 
> In some migrations - the mode of operation is to use a huge node and then place on it all the data from the old cluster and then compact it - following that sstableloader is run (causing the data to be written once into the cluster and data is replciated only RF times.

This huge node is the only node in the cluster, meaning it owns all the data, right?

This feature can achieve this without extra intermediate huge node which is a big save. 

> 
> I think we should consider using RF in new cluster being 1 loading the data and then switching RF and repairing.

This is one of the mode that can work. It streams less on wire but requires the extra repair after the load and stream process. The disk space is not always an issue, e.g.,  we have 100 tables, we can process 1 table after another, after compaction is done, the extra disk space is released then we move to next table.

**Comment by asias** [comment]
> > > @asias we need more info here:
> > > ```
> > > * old cluster 3 nodes (nodes: O1, O2, O3)
> > > 
> > > * RF is 3
> > > 
> > > * new cluster is 6 nodes (nodes: N1, N2, N3, N4, N5, N6)
> > > ```
> > > 
> > > 
> > > On node N1 data from O1 is placed and nodetool refresh is run - is the data spread across the cluster to all 3 replicas ?
> > 
> > 
> > Yes. We can also place 50% of data from O1 to N1 and the other 50% to N2 to speed up the restore.
> 
> That doesn't work. You can have partition P1 from O1, O2, O3 go to N1 by accident, and you lose quorum.

How is this possible? If P1 from O1, O2, O3 all goes to N1, N1 will have the latest copy.  N1 will streams the latest replica to other replicas nodes nicely. 

This process is off-line in the sense you should read after the load and stream process for a given node is finished. If you read in the middle of the process, read is not guaranteed to return correct data.  A simple example, during load and stream process, a given partition might be not loaded yet at all, a read returns nothing while in fact we have data for that partition.

**Comment by asias** [comment]
> (it's enough to replicate each partition to two nodes, but that causes repair work later)

A new node does not know about if other other new node has streamed the partition or not. So we can not stream only quorum replicas from the old sstables to a given new node, e.g., the primary replica node, to minimize the streaming. 

So the minimum streaming from old nodes to new nodes for a given partition is RF-old.  Yes, we can check before the streaming if the new node selected to receive all the old replicas, has received it or not, or how many replicas has received. This makes the process much more complicated and slower. In practice, it probably be faster just to stream RF replicas directly.

**Comment by asias** [comment]
For the recording, before we need to copy sstables from all old nodes into each and every new nodes, if we want to restore by only copying sstables to new cluter . After we only need to copy sstables from old cluster once. The disk usage difference is number_of_node_in_the_new_cluster times.

**Comment by avikivity** [comment]
> > > > @asias we need more info here:
> > > > ```
> > > > * old cluster 3 nodes (nodes: O1, O2, O3)
> > > > 
> > > > * RF is 3
> > > > 
> > > > * new cluster is 6 nodes (nodes: N1, N2, N3, N4, N5, N6)
> > > > ```
> > > > 
> > > > 
> > > > On node N1 data from O1 is placed and nodetool refresh is run - is the data spread across the cluster to all 3 replicas ?
> > > 
> > > 
> > > Yes. We can also place 50% of data from O1 to N1 and the other 50% to N2 to speed up the restore.
> > 
> > 
> > That doesn't work. You can have partition P1 from O1, O2, O3 go to N1 by accident, and you lose quorum.
> 
> How is this possible? If P1 from O1, O2, O3 all goes to N1, N1 will have the latest copy. N1 will streams the latest replica to other replicas nodes nicely.

I misunderstood you. I thought you meant that `nodetool refresh` on N1 should stream to only two replicas, not three. But you meant that you should execute `nodetool refresh on each node, with each node streaming to three replicas. I agree that's correct.

We should be careful to control the number of streams. If we do this in parallel on N nodes, we have NS streams per shard (S = smp::count). That can be high.

> 
> This process is off-line in the sense you should read after the load and stream process for a given node is finished. If you read in the middle of the process, read is not guaranteed to return correct data. A simple example, during load and stream process, a given partition might be not loaded yet at all, a read returns nothing while in fact we have data for that partition.

Yes, of course. The data is only available after the command returns.

**Comment by avikivity** [comment]
> > (it's enough to replicate each partition to two nodes, but that causes repair work later)
> 
> A new node does not know about if other other new node has streamed the partition or not. So we can not stream only quorum replicas from the old sstables to a given new node, e.g., the primary replica node, to minimize the streaming.

Yes, but read repair will correct it. I agree it's not a good idea.

> 
> So the minimum streaming from old nodes to new nodes for a given partition is RF-old. Yes, we can check before the streaming if the new node selected to receive all the old replicas, has received it or not, or how many replicas has received. This makes the process much more complicated and slower. In practice, it probably be faster just to stream RF replicas directly.


Yes.

**Comment by slivne** [comment]
(instead of sstableloader to a certain extent)

**Comment by tzach** [comment]
@asias please link to the corresponding nodetool issue

**Comment by asias** [comment]
> @asias please link to the corresponding nodetool issue

https://github.com/scylladb/scylla-tools-java/issues/253
