### ISSUE TITLE
IO drop during add_remove_coloumn and large latency increase after nemesis ends 

### ISSUE THREAD

**Issue by shoshan** [scylladb/scylla#7837]
*Installation details*
Scylla version (or git commit hash): `4.3.rc3-0.20201217.5bd52e4db with build-id fbc87a9195ba296dbec0f662bc159d0117d63e2c`
Cluster size: 4 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-00a91e66017de1333` (aws: eu-west-1)

Test: longevity-200gb-48h-test
Test name: longevity_test.LongevityTest.test_custom_time
Test config file(s):
- [longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/c22089da1dd6d37fccee429a6951f26d7578e0dd/test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml)

**Issue description**
 ==================================== 
IO drop during add_remove_coloumn and large latency increase after nemesis ends 
```
2020-12-25 01:20:36.441: (DisruptionEvent Severity.NORMAL): type=start name=AddDropColumnMonkey node=Node longevity-200gb-48h-verify-limited--db-node-1bc6c027-9 [34.245.136.153 | 10.0.0.136] (seed: False) duration=None  
2020-12-25 01:30:41.321: (DisruptionEvent Severity.NORMAL): type=end name=AddDropColumnMonkey node=Node longevity-200gb-48h-verify-limited--db-node-1bc6c027-9 [34.245.136.153 | 10.0.0.136] (seed: False) duration=604 
```
![200gb048h_01_25_](https://user-images.githubusercontent.com/99000/103174293-87150600-4869-11eb-8a2c-eb830ec1c372.png)

c-s reports 
```
2020-12-25 01:33:18.867: (CassandraStressLogEvent Severity.ERROR): type=IOException regex=java\.io\.IOException line_number=326536 node=Node longevity-200gb-48h-verify-limited--loader-node-1bc6c027-1 [54.195.155.168 | 10.0.0.207] (seed: False)                                                                          
java.io.IOException: Operation x10 on key(s) [503850324c3635334e30]: Error executing: (OperationTimedOutException): [/10.0.2.103:9042] Timed out waiting for server response
```

many multiple errors during test 
cql_server - exception while processing connection: std::system_error (error system:22, Invalid argument)  
 journal: Suppressed 10586 messages from /scylla.slice/scylla-server.slice 
scylla: [shard 1] cql_server - exception while processing connection: std::system_error (error GnuTLS:-10, The specified session has been invalidated for some reason.)  
====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 1bc6c027-e526-47ae-ab06-dfca31282e78`
Show all stored logs command: `$ hydra investigate show-logs 1bc6c027-e526-47ae-ab06-dfca31282e78`

Test id: `1bc6c027-e526-47ae-ab06-dfca31282e78`

Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/1bc6c027-e526-47ae-ab06-dfca31282e78/20201225_143019/db-cluster-1bc6c027.zip](https://cloudius-jenkins-test.s3.amazonaws.com/1bc6c027-e526-47ae-ab06-dfca31282e78/20201225_143019/db-cluster-1bc6c027.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/1bc6c027-e526-47ae-ab06-dfca31282e78/20201225_143019/loader-set-1bc6c027.zip](https://cloudius-jenkins-test.s3.amazonaws.com/1bc6c027-e526-47ae-ab06-dfca31282e78/20201225_143019/loader-set-1bc6c027.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/1bc6c027-e526-47ae-ab06-dfca31282e78/20201225_143019/monitor-set-1bc6c027.zip](https://cloudius-jenkins-test.s3.amazonaws.com/1bc6c027-e526-47ae-ab06-dfca31282e78/20201225_143019/monitor-set-1bc6c027.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/1bc6c027-e526-47ae-ab06-dfca31282e78/20201225_143019/sct-runner-1bc6c027.zip](https://cloudius-jenkins-test.s3.amazonaws.com/1bc6c027-e526-47ae-ab06-dfca31282e78/20201225_143019/sct-runner-1bc6c027.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.3/job/longevity/job/longevity-200gb-48h-test/4/)

**Comment by roydahan** [comment]
This does not look like a real issue, or at least not on scylla side.

When we change the schema of the table, the c-s client need to preapre the prepared statements again and report many many messages of:
```
01:26:42.351 [cluster1-nio-worker-4] DEBUG c.d.driver.core.RequestHandler - Scheduling retry now that query is prepared
01:26:42.828 [cluster1-nio-worker-3] INFO  c.d.driver.core.RequestHandler - Query SELECT "C0" FROM "standard1" WHERE KEY=? is not prepared on keyspace1, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
01:26:42.828 [cluster1-nio-worker-3] INFO  c.d.driver.core.RequestHandler - Query SELECT "C0" FROM "standard1" WHERE KEY=? is not prepared on keyspace1, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
```


Then, after a while we start seeing these errors from the client, which cause the read workload to hang:

```
01:30:36.951 [cluster1-nio-worker-7] DEBUG c.d.driver.core.RequestHandler - [1286533444-0] Error querying /10.0.1.238:9042 : com.datastax.driver.core.exceptions.BusyPoolException: [/10.0.1.238:9042] Pool is busy (no available connection and timed out after 5000 MILLISECONDS)
01:30:36.951 [cluster1-connection-reaper-0] WARN  com.datastax.driver.core.Connection - Forcing termination of Connection[/10.0.2.103:9042-152, inFlight=0, closed=true]. This should not happen and is likely a bug, please report.
```

**Comment by roydahan** [comment]
It can also be related to #7748, we need to retest once the issue is solved.

**Comment by yarongilor** [comment]
reproduced again, where read stress got io exception and failed.


Restore Monitor Stack command: `$ hydra investigate show-monitor 29c0edbb-5d83-4a71-a773-c6f4ae2f875e`
Show all stored logs command: `$ hydra investigate show-logs 29c0edbb-5d83-4a71-a773-c6f4ae2f875e`

Test id: `29c0edbb-5d83-4a71-a773-c6f4ae2f875e`


Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/29c0edbb-5d83-4a71-a773-c6f4ae2f875e/20210117_051742/grafana-screenshot-longevity-200gb-48h-scylla-per-server-metrics-nemesis-20210117_052124-longevity-200gb-48h-verify-limited--monitor-node-29c0edbb-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/29c0edbb-5d83-4a71-a773-c6f4ae2f875e/20210117_051742/grafana-screenshot-longevity-200gb-48h-scylla-per-server-metrics-nemesis-20210117_052124-longevity-200gb-48h-verify-limited--monitor-node-29c0edbb-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/29c0edbb-5d83-4a71-a773-c6f4ae2f875e/20210117_051742/grafana-screenshot-overview-20210117_051743-longevity-200gb-48h-verify-limited--monitor-node-29c0edbb-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/29c0edbb-5d83-4a71-a773-c6f4ae2f875e/20210117_051742/grafana-screenshot-overview-20210117_051743-longevity-200gb-48h-verify-limited--monitor-node-29c0edbb-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/29c0edbb-5d83-4a71-a773-c6f4ae2f875e/20210117_054520/db-cluster-29c0edbb.zip](https://cloudius-jenkins-test.s3.amazonaws.com/29c0edbb-5d83-4a71-a773-c6f4ae2f875e/20210117_054520/db-cluster-29c0edbb.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/29c0edbb-5d83-4a71-a773-c6f4ae2f875e/20210117_054520/loader-set-29c0edbb.zip](https://cloudius-jenkins-test.s3.amazonaws.com/29c0edbb-5d83-4a71-a773-c6f4ae2f875e/20210117_054520/loader-set-29c0edbb.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/29c0edbb-5d83-4a71-a773-c6f4ae2f875e/20210117_054520/monitor-set-29c0edbb.zip](https://cloudius-jenkins-test.s3.amazonaws.com/29c0edbb-5d83-4a71-a773-c6f4ae2f875e/20210117_054520/monitor-set-29c0edbb.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/29c0edbb-5d83-4a71-a773-c6f4ae2f875e/20210117_054520/sct-runner-29c0edbb.zip](https://cloudius-jenkins-test.s3.amazonaws.com/29c0edbb-5d83-4a71-a773-c6f4ae2f875e/20210117_054520/sct-runner-29c0edbb.zip)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-200gb-48h/96/)

**Comment by roydahan** [comment]
@yarongilor you're commenting on a closed issue.
Did you see the same log messages that I saw in the original issue?

**Comment by yarongilor** [comment]
> @yarongilor you're commenting on a closed issue.
> Did you see the same log messages that I saw in the original issue?

@roydahan , it is the same longevity and same nemesis and i saw an event of:
```
15:00:28  < t:2021-01-15 13:00:27,915 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 2021-01-15T13:00:14+00:00  longevity-200gb-48h-verify-limited--db-node-29c0edbb-2 !INFO    | scylla: [shard 1] cql_server - exception while processing connection: std::system_error (error GnuTLS:-10, The specified session has been invalidated for some reason.)
```

before the read thread io exceptions.

**Comment by roydahan** [comment]
https://github.com/scylladb/scylla/issues/7837#issuecomment-751716278

**Comment by yarongilor** [comment]
@roydahan , it looks like the same issue, so perhaps we need to decrease stress threads or filter these timeout io exceptions.

the log has:
```

< t:2021-01-17 02:09:57,134 f:nemesis.py      l:1002 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method add_drop_column
< t:2021-01-17 02:13:03,125 f:cluster.py      l:1391 c:sdcm.cluster         p:DEBUG > 2021-01-17T02:12:49+00:00  longevity-200gb-48h-verify-limited--db-node-29c0edbb-5 !INFO    | scylla: [shard 1] cql_server - exception while processing connection: std::system_error (error GnuTLS:-
10, The specified session has been invalidated for some reason.)
< t:2021-01-17 02:13:03,846 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > 2021-01-17T02:12:49+00:00  longevity-200gb-48h-verify-limited--db-node-29c0edbb-5 !INFO    | scylla: [shard 1] cql_server - exception while processing connection: std::system_error (error G
nuTLS:-10, The specified session has been invalidated for some reason.)
< t:2021-01-17 02:13:52,884 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.3.64:9042] Timed out waiting for server response
...

< t:2021-01-17 02:17:31,230 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > 02:13:39.605 [cluster1-nio-worker-6] INFO  c.d.driver.core.RequestHandler - Query UPDATE "standard1" SET "C0" = ? WHERE KEY=? is not prepared on keyspace1, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems
< t:2021-01-17 02:17:31,232 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > 02:13:39.605 [cluster1-nio-worker-7] INFO  c.d.driver.core.RequestHandler - Query UPDATE "standard1" SET "C0" = ? WHERE KEY=? is not prepared on keyspace1, preparing before retrying executing. Seeing this message a few times is fine, but seeing it a lot may be source of performance problems

< t:2021-01-17 02:17:32,824 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > 02:13:52.784 [cluster1-timeouter-0] DEBUG c.d.driver.core.RequestHandler - [1098942567-0] Error querying /10.0.0.27:9042 : com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.0.27:9042] Timed out waiting for response to PREPARE message
< t:2021-01-17 02:17:32,938 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > 02:13:52.785 [cluster1-timeouter-0] DEBUG c.d.driver.core.RequestHandler - [1182755048-0] Error querying /10.0.3.6:9042 : com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.3.6:9042] Timed out waiting for response to PREPARE message
< t:2021-01-17 02:17:32,940 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.OperationTimedOutException: [10.0.0.104/10.0.0.104:9042] Timed out waiting for server response
< t:2021-01-17 02:17:32,991 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.3.64:9042] Timed out waiting for server response
< t:2021-01-17 02:17:32,991 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.OperationTimedOutException: [/10.0.3.64:9042] Timed out waiting for server response
< t:2021-01-17 02:17:32,992 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > com.datastax.driver.core.exceptions.OperationTimedOutException: [10.0.0.104/10.0.0.104:9042] Timed out waiting for server response

< t:2021-01-17 02:19:58,945 f:nemesis.py      l:1012 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method add_drop_column

< t:2021-01-17 02:28:14,726 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > 02:26:04.520 [cluster1-connection-reaper-0] WARN  com.datastax.driver.core.Connection - Forcing termination of Connection[10.0.0.104/10.0.0.104:9042-32, inFlight=0, closed=true]. This should not happen and is likely a bug, please report.

< t:2021-01-17 02:28:27,670 f:base.py         l:220  c:RemoteCmdRunner      p:DEBUG > 02:26:13.127 [cluster1-nio-worker-0] DEBUG c.d.driver.core.RequestHandler - [746950903-0] Error querying /10.0.3.64:9042 : com.datastax.driver.core.exceptions.BusyPoolException: [/10.0.3.64:9042] Pool is busy (no available connection and timed out after 5000 MILLISECONDS)
2021-01-17 02:28:27.600: (CassandraStressLogEvent Severity.ERROR): type=IOException regex=java\.io\.IOException line_number=352787 node=Node longevity-200gb-48h-verify-limited--loader-node-29c0edbb-1 [13.49.18.173 | 10.0.3.74] (seed: False)
java.io.IOException: Operation x10 on key(s) [4e4c384c344b4e353530]: Error executing: (OperationTimedOutException): [/10.0.3.6:9042] Timed out waiting for server response
```

**Comment by roydahan** [comment]
We may need to reduce the num of threads now that we are using the shard-aware driver.
