### ISSUE TITLE
Log that we coredump before creating the core

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#784]
Otherwise there is nothing in the log while we go through length process of gzip the core

**Comment by gleb-cloudius** [comment]
On Wed, Jan 13, 2016 at 01:59:43AM -0800, Dor Laor wrote:
> Otherwise there is nothing in the log while we go through length process of gzip the core
> 
This is in the hands of systemd. Does it have such configuration?

--
			Gleb.

**Comment by dorlaor** [comment]
@gleb-cloudius, we switched out of systemd for the cores in order to support older OSs.
This is what we do (we need to log before and after the core):

#!/bin/sh -e
#
#  Copyright (C) 2015 ScyllaDB

FILE=$1
TIME=`date --date @$2 +%F-%T`
PID=$3

mkdir -p /var/lib/scylla/coredump
/usr/bin/gzip -c > /var/lib/scylla/coredump/core.$FILE-$TIME-$PID.gz

**Comment by gleb-cloudius** [comment]
On Wed, Jan 13, 2016 at 03:37:36AM -0800, Dor Laor wrote:
> @gleb-cloudius, we switched out of systemd for the cores in order to support older OSs.
Ah, good thing we moved from this binary goo to clear and simple shell
script. What about project to replace systemd with easily hackable shell
scripts?

> This is what we do (we need to log before and after the core):
> 
> #!/bin/sh -e
> #
> #  Copyright (C) 2015 ScyllaDB
> 
> FILE=$1
> TIME=`date --date @$2 +%F-%T`
> PID=$3
> 
> mkdir -p /var/lib/scylla/coredump
> /usr/bin/gzip -c > /var/lib/scylla/coredump/core.$FILE-$TIME-$PID.gz
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/scylladb/scylla/issues/784#issuecomment-171262481

--
			Gleb.

**Comment by dorlaor** [comment]
On Wed, Jan 13, 2016 at 1:41 PM, Gleb Natapov <notifications@github.com>
wrote:

> On Wed, Jan 13, 2016 at 03:37:36AM -0800, Dor Laor wrote:
> > @gleb-cloudius, we switched out of systemd for the cores in order to
> support older OSs.
> Ah, good thing we moved from this binary goo to clear and simple shell
> script. What about project to replace systemd with easily hackable shell
> scripts?
>

Nice to find a systemd fan.
I don't mind to go in parallel - one through systemd-all-in approach in new
OSs and
another with more basics for older ones

**Comment by syuu1228** [comment]
@dorlaor we moved to scylla_save_coredump once, but reverted on https://github.com/scylladb/scylla/commit/8886fe739375bee501b6e57f34bf0510da108f5c

**Comment by syuu1228** [comment]
Since we back to systemd-coredump on Fedora/RHEL (still using the script on Ubuntu since there's no other solution), I think there is no way to do this other than print out error message on scylla when it's dieing.

**Comment by avikivity** [comment]
We should file a bug with systemd to do this, citing that when a very large process dumps core it's hard to understand what's happening.

If there are other issues with systemd vs. large applications we should file bugs for them as well.

**Comment by tzach** [comment]
@dorlaor I do not think this is a showstopper. High at best.

**Comment by avikivity** [comment]
We could install a signal handler for SIGBUS/SIGABRT/SIGSEGV, catch the signal, log something, remove the handler, and re-raise the signal.  But this would reduce the quality and reliability of core dumps.

Better to get it fixed in systemd.

**Comment by avikivity** [comment]
(and agree it is very far from a showstopper)

**Comment by dorlaor** [comment]
The thing is, if we'll crash (and we will), the average user may not
realize what's going
on and the overall behaviour wouldn't be good and we may lose the core file
too.
I would say it's high priority but not a show stopper.

**Comment by dorlaor** [comment]
Initially it's fine if it will work well for systemd-only OSs

**Comment by benoit-canet** [comment]
We could have a convenience daemon whatching for systemdcoredump process.
If it start running on scylla we log it.
Else we could wrap the systemd dumper as a temporary solution.

**Comment by syuu1228** [comment]
Until systemd will get fixed, I think simplest approach is enabling scylla_save_coredump again, even it is not Fedora/RHEL standard.

**Comment by syuu1228** [comment]
Any ideas?

**Comment by jfilak** [comment]
Current version of abrt-hook-ccpp writes the following message to syslog few moments after kernel invokes it and before it starts saving core file to disk:
```May 18 09:33:31 photon abrt-hook-ccpp[6983]: Process 6982 (will_cpp_segfault) of user 18601 killed by SIGSEGV - dumping core```

**Comment by avikivity** [comment]
Cool, is this a recent change?  Unfortunately our users are running stable distros, so we have to work with what's out there, but it's good to have this fix in.

**Comment by jfilak** [comment]
The message was added in abrt-2.7.2, so it should be present on Fedora >= 23.

**Comment by avikivity** [comment]
Most of our users are on CentOS/RHEL 7.2 or Ubuntu 14.04, transitioning to 16.04.  I don't think abrt is a problem on Ubuntu, so that leaves out CentOS/RHEL.

**Comment by jfilak** [comment]
RHEL/CentOS, no problem -> https://bugzilla.redhat.com/show_bug.cgi?id=1337186

ABRT is not a problem on Ubuntu because Ubuntu uses Apport [1].


1: https://wiki.ubuntu.com/Apport

**Comment by slivne** [comment]
@tgrabiec added support for backtrace generation in scylladb/seastar@379e928805ea2930b8acc1138a1a3435d45c171d
