### ISSUE TITLE
"dev" mode executable became too slow since switch to clang

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7849]
The "dev" build mode was designed for the need of Scylla developers who were frustrated by the extremely slow compilation of the "release" mode. The idea was to find various places where we gain only a small performance advantage with a large compile-time cost, and turn these things off.

One of the first things we did in dev mode (see commit 6243443591d2f44a98b30a7ece2159f9062fd851) was to use "-O1" optimization instead of "-O3" that was used in release mode. At the time, it was noted that "-O1" build was significantly faster than "-O3", but the resulting executable was only slightly faster.

However, this was with gcc. When we switched from gcc to clang, developers began to notice that **running** dev-build executables became annoyingly slow. Test runs became much slower than they used to be.

I sent a patch to the mailing list titled "**[PATCH] build: switch "dev" build from -O1 to -O2**" where I measured that if we switch the -O1 to -O2, tests becomes 2.5 to 3 times faster (!!), and the slowdown in compilation was just 9%.

My patch was unfortunately not committed. Some people claimed that for them, compilation speed is more important than test speed. Maybe we should have some way to personalize this choice. 

But personally I really believe that dev mode should be (or default to being) a mode that **minimizes compilation time with only small performance loss** (and however we define "small", 3-fold slowdown isn't that). If "-O2" is needed in clang to keep reasonable performance, we need to use it, and if we are worried that this slowed compilation by 9%, we should look for other ways to gain back this 9% loss - other ways which do not significantly slow down the resulting executable. Perhaps we can disable specific optimizations which are slow but offer little gain, or perhaps we can do more type-erasure - a technique which in the past got us a lot of compile-time gains with relatively small run-time slowdown.

**Comment by raphaelsc** [comment]
Quoting myself:
"It's now clear to me we need this patch[1], even though it means more
compilation time. Prior to switch to clang, a simple cassandra-stress
achieved ~30k ops, and after the switch ONLY ~3k ops. 10x slower. Also
compactions which only start after an infinite amount of time are
terribly terribly terribly slow. Seriously, without -O2 in clang's dev
mode, the produced binary is useless for anything other than compile
testing."

[1]: "[PATCH] build: switch "dev" build from -O1 to -O2"

**Comment by nyh** [comment]
Solved long ago by commit 8c9935359c90544e903e5c7b5ac8c81f8a9ebab7
