### ISSUE TITLE
Provide default for serial_consistency even if not specied in a request

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#7850]
*Installation details*
Scylla version (or git commit hash):  5f24ff9187714a65a2f8538cc854b07b3a21465c

Current code sets default to SERIAL in case paging is enabled or non otherwise which is strange.

**Comment by kostja** [comment]
See also https://github.com/scylladb/gocql/issues/58

**Comment by stoiev** [comment]
We've got this behavior discrepancy between Cassandra and ScyllaDB testing same code on both databases. When trying to perform update queries in batch mode on nodejs with an `if` condition, ScyllaDB answer was `Consistency level for LWT is missing for a request with conditions`. 
cassandra-driver version: 3.1.3
scylladb version: 2020.1.4

To fix it on ScyllaDB, we had to add serial consistency to connection options.

```diff
  var cassandra_conf = {
    contactPoints: host_list,
    socketOptions: {
      connectTimeout: options.timeout || 5000,
    },
    pooling: {
      heartbeatInterval: options.timeout || 5000,
      coreConnectionsPerHost: {}
    },
    queryOptions: {
      prepare: true,
      consistency: cassandra.types.consistencies.quorum,
+     serialConsistency: cassandra.types.consistencies.serial
    },
    policies: {}
  };

  if (options.localDc) {
    var dc_policy = new cassandra.policies.loadBalancing.DCAwareRoundRobinPolicy(options.localDc);
    cassandra_conf.policies.loadBalancing = new cassandra.policies.loadBalancing.TokenAwarePolicy(dc_policy);
  }

  cassandra_conf.pooling.coreConnectionsPerHost[distance.local]  = pool.local_size || 4;
  cassandra_conf.pooling.coreConnectionsPerHost[distance.remote] = pool.size || 2;

  if (options.authentication) {
    cassandra_conf.authProvider = new cassandra.auth.PlainTextAuthProvider(options.authentication.username, options.authentication.password);
  }

  var client = new cassandra.Client(cassandra_conf);

```

**Comment by ManManson** [comment]
Cassandra have this bit of code, which we're missing:
https://github.com/apache/cassandra/blob/79e693e16e2152097c5b27d2d7aaa1763e34f594/src/java/org/apache/cassandra/cql3/QueryOptions.java#L398
> this.serialConsistency = serialConsistency == null ? ConsistencyLevel.SERIAL : serialConsistency;

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
