### ISSUE TITLE
test scylla docker is broken, error "Waiting for SSH to be up"

### ISSUE THREAD

**Issue by shoshan** [scylladb/scylla#7851]
scylla_version: 4.4.dev-0.20201225.72c2482f7
test_id=a131e2bd-9181-4751-ad15-bb45aa919a22

**Hydra commands:**
Restore Monitor Stack command: $ hydra investigate show-monitor a131e2bd-9181-4751-ad15-bb45aa919a22
Show all stored logs command: $ hydra investigate show-logs a131e2bd-9181-4751-ad15-bb45aa919a22
**Logs:**
monitor-set - https://cloudius-jenkins-test.s3.amazonaws.com/a131e2bd-9181-4751-ad15-bb45aa919a22/20201226_001413/monitor-set-a131e2bd.zip
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/a131e2bd-9181-4751-ad15-bb45aa919a22/20201226_001413/sct-runner-a131e2bd.zip

test log shows that after starting the built container SSH fails.

```
< t:2020-12-26 00:03:43,333 f:config.py       l:273  c:fabric               p:DEBUG > File not found, skipping
< t:2020-12-26 00:05:16,289 f:docker_utils.py l:202  c:sdcm.utils.docker_utils p:INFO  > Container <ee2a19148b artifacts-docker-jenkins-db-node-a131e2bd-0> started.
< t:2020-12-26 00:05:16,481 f:config.py       l:273  c:fabric               p:DEBUG > File not found, skipping
< t:2020-12-26 00:13:46,599 f:wait.py         l:64   c:sdcm.wait            p:ERROR > Wait for: Node artifacts-docker-jenkins-db-node-a131e2bd-0 [172.17.0.5 | 172.17.0.5] (seed: False): Waiting for SSH to be up: timeout - 500 seconds - expired
```

there are no scylla logs to this test.

**Comment by roydahan** [comment]
@fruch you said that you'll add more details.

**Comment by fruch** [comment]
this is failing with missing supervisord:
```bash
$ docker run -it docker.io/scylladb/scylla-nightly:4.4.dev-0.20201229.700ddd191
running: (['/opt/scylladb/scripts/scylla_dev_mode_setup', '--developer-mode', '1'],)
running: (['/opt/scylladb/scripts/scylla_io_setup'],)
failed!
Traceback (most recent call last):
  File "/docker-entrypoint.py", line 31, in <module>
    supervisord = subprocess.Popen(["/usr/bin/supervisord", "-c",  "/etc/supervisord.conf"])
  File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/supervisord'
```

looking at scylla-core between the working and non-working version `git log 961b9e83902..fd5f0c303`

I think this is the root cause of it:
```
commit ceb67e7728f80b6711bcc534292945e39bbbca52
Author: Pekka Enberg <penberg@scylladb.com>
Date:   Tue Dec 22 13:47:26 2020 +0200

    dist/docker: Remove 'epel-release' from Docker image
    
    We no longer need the 'epel-release' package for anything as our
    scylla-server package bundles all the necessary dependencies.
    
    Closes #7823
```

**Comment by fruch** [comment]
@avikivity can we revert this commit ?

**Comment by slivne** [comment]
the goal of this was to reduce the size ...

**Comment by fruch** [comment]
> the goal of this was to reduce the size ...

I would start with adding `rm -rf /var/cache/yum` to the Dockerfile, 
and maybe start with a smaller base image (i.e. not `centos:7`)

and then try tools like https://github.com/docker-slim/docker-slim

**Comment by avikivity** [comment]
No release branches affected, no backport needed.
