### ISSUE TITLE
Frozen nested set may be created out-of-order via a prepared statement

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7856]
In Scylla, "set" collections are sorted - by the element type's natural order.
Although this is not clearly documented as far as I can tell (?), clients may assume that this the case also for a **frozen** set, for example used as a partition key.

It appears that Scylla can forget to sort the frozen set when inserted using a prepared statement, although does sort it as expected when inserted inline in the statement. It appears that Cassandra correctly sorts the frozen set also for prepared statement.

Here is one subtle and elaborate test case which breaks using a Python driver like an ordinary client. Take a look at this test code:

```python
@pytest.fixture(scope="session")
def table1(cql, test_keyspace):
    table = test_keyspace + "." + unique_name()
    cql.execute(f"CREATE TABLE {table} (k frozen<map<set<int>, int>> PRIMARY KEY)")
    yield table
    cql.execute("DROP TABLE " + table)

def test_broken(cql, table1):
     insert = cql.prepare(f"INSERT INTO {table1} (k) VALUES (?)")
    cql.execute(insert, [{tuple([8, 9, 7]): 1}])
    for row in cql.execute(f"SELECT * from {table1}"):
        k = row.k
        print(k)
        if isinstance(k, OrderedMapSerializedKey):
            print(k._index)
            print(list(k.items()))   # This line throws when run on Scylla, but works fine on Cassandra
```

The test has a nested frozen collection - a map of sets. When run against Cassandra this test works, but when run against Scylla, the `k.items()` call throws. The reason is very subtle: It appears that the Python driver keeps the frozen map keys - each itself is a set - serialized in the way it got them from the server. The items() function appears to do a wasteful back-and-forth conversion - it deserializes each key (resulting in a SortedSet object) and then serializes it again to look it up in the map. Somehow during these conversions, the driver re-sorts the elements, and it fails to look it up in the map. Concretely, the serialized key stored in the map is the wrongly sorted (note \0x08, \t, 0x07 - which means 8, 9, 7):
```
\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x08\x00\x00\x00\x04\x00\x00\x00\t\x00\x00\x00\x04\x00\x00\x00\x07
```
but the key the code looks up (and fails) is the sorted one (note \0x07, \x08, \t - meaning 7, 8, 9):
```
\x00\x00\x00\x03\x00\x00\x00\x04\x00\x00\x00\x07\x00\x00\x00\x04\x00\x00\x00\x08\x00\x00\x00\x04\x00\x00\x00\t
```

The test passes if instead of `tuple([8, 9, 7])` we pass `tuple([7, 8, 9])` to the prepared statement!
 The test also passes if instead of prepared statement, we use an inline statement. Both commands below work the same:
```
    cql.execute("INSERT INTO " + table1 + " (k) VALUES ({{7, 8, 9}: 1})")
    cql.execute("INSERT INTO " + table1 + " (k) VALUES ({{8, 9, 7}: 1})")
 ```

Note that this test appears very contrived, but it is actually a greatly simplified version of a real test I tried to run (translated, perhaps not very well, from a Java test from Cassandra) which failed on Scylla, and this is a simplified example showing why. But I will try to create an even simpler test which only needs a `frozen<set>` without nesting.

**Comment by nyh** [comment]
Here is a simpler test which does not rely on weird details of the driver implementation (the previous example broke because the driver did some useless back-and-forth conversions):
```
def test_broken_simple(cql, table1):
    insert = cql.prepare(f"INSERT INTO {table1} (k) VALUES (?)")
    cql.execute(insert, [{tuple([8, 9, 7]): 1}])
    assert len(list(cql.execute("SELECT * FROM " + table1 + " WHERE k = {{7, 8, 9}: 1}"))) == 1
```

This test adds a partition with a wrongly-sorted key, and then tries to look it up properly sorted - and fails. As before, this test only fails on Scylla but passes on Cassandra. It also passes if the tuple passed to the prepared statement is correctly sorted, and also passes when the insert statement is inline instead of prepared (regardless of the order of elements in the inline statement).

Curiously, I cannot reproduce the same problem on a `frozen<set>` without nesting it in a map as we did in the above examples. In that case, sorting does appear to happen and we can find the item we entered! So it appears the bug that we forget to sort may somehow be specific to nested collections.

**Comment by nyh** [comment]
The two cql-pytest tests we have for this issue, 
* `test_frozen_collection.py::test_wrong_set_order_in_nested`
* `test_frozen_collection.py::test_wrong_set_order_in_nested_2`
do not fail any more, and now appear as XPASS. We need to figure out if this bug got solved at some point along the way, or something else (maybe changes in the driver?) made it harder to reproduce.

**Comment by nyh** [comment]
I verified that what started to pass these tests was a change in Scylla, not the driver (I recompiled Scylla when these tests were introduces, and it still xfails with my current driver). So I proceeded to bisect Scylla - an unbearably slow experience  - to check when these two tests began to pass.

The patch which made these tests pass is the following by @cvybhu:

```
commit 5589f348e7cef9067669ef30c7c3cd0b9889cf41
Author: Jan Ciolek <jan.ciolek@scylladb.com>
Date:   Fri Sep 17 10:26:18 2021 +0200

    cql3: expr: Implement evaluate(expr::bind_variable)
    
    Implement evaluating a bind_variable.
    To be able to evaluate a bind_variable we need to know the type of the bound value.
    This is why a data_type has been added to the bind_variable struct.
    
    There are some quirks when evaluating a bind_variable.
    The first problem occurs when the variable has been sent with an older cql serialization format and contains collections.
    In that case the value has to be reserialized to use the newest cql serialization format.
    
    The second problem occurs when there is a set or a map in the value.
    The set value sent by the driver might not have the elements in the correct order, contain duplicates etc.
    When a set or map is detected in the value it is reserialized as well.
    
    collection_type_impl::reserialize doesn't work for this purpose, because it uses data_value which does not perform sorting or removal.
    
    New code corresponds to old bind() of lists::marker in cql3/lists.cc, sets::marker etc.
    
    Signed-off-by: Jan Ciolek <jan.ciolek@scylladb.com>
```

We need to understand whether this patch **fixed** the bug - i.e., the new binding code sorts sets as it should and then this issue can be marked fixed - or if it somehow hid the bug but it still exists.

**Comment by cvybhu** [comment]
Yes, the new code started handling nested sets correctly

Sets passed as bound values used to be created using from_serialized:
https://github.com/scylladb/scylla/blob/034f79cfb4fd5bca0ba31781f2b70b465382f1c9/cql3/sets.cc#L31

This function sorted only the first level of set, set values were simply represented as managed_bytes.

**Comment by cvybhu** [comment]
Now there is a check whether there is a set or map inside the bound value, and if so the value gets sorted and reserialized

https://github.com/scylladb/scylla/blob/034f79cfb4fd5bca0ba31781f2b70b465382f1c9/cql3/expr/expression.cc#L1530

**Comment by nyh** [comment]
Thanks! So this is really good news - you fixed a real bug while cleaning up the code!

I sent a patch titled "[PATCH] test/cql-pytest: remove "xfail" label on a reproducer for a fixed bug" to the mailing list to remove the no-longer-needed "xfail" markers, and to close this issue.
