### ISSUE TITLE
Scylla-server ver 0.15 core dumps, cluster of 2

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#786]
scylla-server-0.15-20160108.b7d5fbe.el7.centos.x86_64
Scenario:
1. Run a single node, run standard c-s with write only
2. Add a second node
    (Initially the firewall blocked the gossip port between them, later
     I discovered it and stopped the firewall)
3. Run c-s while the second node is being synchronized.
 --> core dump.
      The first node continued to run and c-s continued to work.

**Comment by slivne** [comment]
noam will try to reproduce - dor I assume this was with baremetal servers on rackspace.

**Comment by noamha** [comment]
Had the same results as issue #833 

Configuration:
- 2 nodes x x Rackspace 15 GB I/O v1 CentOS
- Build: https://s3.amazonaws.com/downloads.scylladb.com/rpm/unstable/centos/branch-0.18/13/scylla.repo

Steps:
1. Started the first node
2. Ran the following stress:
time cassandra-stress write cl=ONE n=30000000 -mode native cql3 -rate threads=100 -node $SERVERS -pop seq=1..30000000 -col 'size=FIXED(2048) n=FIXED(5)'
3. Waited until around 7M keys were written
4. Started node2
5. The "service scylla-start" seems to be hanging for a long time
6. nodetool status on the node1 shows node2 in "Joining" status
7. After a while got the following error from console:
```
Job for scylla-server.service failed because a timeout was exceeded. See "systemctl status scylla-server.service" and "journalctl -xe" for details.
```
