### ISSUE TITLE
we should not disable native transport port by setting it to `0'

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#7866]
*Installation details*
Scylla version (or git commit hash): Scylla master
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

### Description

Currently when native_transport_port_ssl is enabled, the only way to disable native_transport_port is setting it to `0'.

Actually the port 0 is a valid port number.  Port 0 is a wildcard port that tells the system to find a suitable port number.
Reference: https://www.lifewire.com/port-0-in-tcp-and-udp-818145

In Cassandra，we can disable native_transport_port by setting native_transport_port_ssl to the same value as native_transport_port, then the port will use ssl.

Related to https://github.com/scylladb/scylla/issues/7500

/cc @roydahan

**Comment by nyh** [comment]
I wish I saw this issue earlier. This request doesn't make sense to me... I agree that port 0 has a meaning in the socket API, but I don't agree that it makes any sense in the context of Scylla. Who would ever want Scylla to pick a random port that he will not know what it is? I dispute the need to support that.

Whereas in the past a lot of features in Scylla could be disabled by setting the port number to 0 (the CQL port ("native"), Alternator, etc.) and people were already used to this idiom - the idea that now we need to support port 0 made these settings more complicated - you can see how complicated it became in https://github.com/scylladb/scylla/pull/8152. I can't even understand the instructions there. Moreover, I don't understand how it doesn't cause compatibility problems with old configuration files, as well as old guides.

I still don't understand the **motivation** for this issue. I think it was a mistake to do it, and more than a month later, we're still seeing patch after patch trying to make sense out of this. I'm thinking of opening an issue to undo all of this, but before I do that, maybe somebody can convince me this wasn't a mistake?

**Comment by jul-stas** [comment]
@amoskong reported it, @slivne marked it as a bug; now it's upstreamed and the update to the docs is still hanging.
If you agree with Nadav, let's take it down.

**Comment by nyh** [comment]
@jul-stas just one question - did all the complexity of that large "matrix" happen because of this change of 0? Or did other things contribute to this complexity as well?

**Comment by jul-stas** [comment]
> @jul-stas just one question - did all the complexity of that large "matrix" happen because of this change of 0? Or did other things contribute to this complexity as well?

Some of the complexity was already there, but noone realized that. And the "0 patch" is almost harmless. The real troublemaker was the need to provide as much SSL as possible in nonsensical configurations and there's no single task for this - it arised from discussions here and there :(

**Comment by nyh** [comment]
Then to be honest, I'm not even sure which patch I'm against :-) I thought this one was responsible for most of the complexity, or at least everything happened after we started with this one, but I'm not sure any more. The only thing I'm quite sure (unless someone convinces me otherwise) is that nobody will want to open a server at a random port number.

**Comment by bhalevy** [comment]
> And the "0 patch" is almost harmless.

Sorry but I think we need to change this part of 29e4737a9b06875ed3ef97e816252a83529c529c that allowed listening on port 0.

(and @jul-stas, for next time, the patch would be much better if it was separated into 2: one fixing the abort issue (#7783) and one implementing this feature - I think it was wrongly mis-categorized as a bug)

Anyhow, even if Cassandra allows listening on a random port by setting it to zero, I think it's a mistake to support that for the following reasons:

1. I don't see how this could be used in practice.  How will the client know what port the server is actually listening on?
2. If we start scylla-jmx after we start scylla, couldn't scylla listen on the jmx port by random chance?

**Comment by bhalevy** [comment]
@amoskong since you opened this issue, please ack.

**Comment by avikivity** [comment]
Backported to 4.4 (4.5+ had it).
