### ISSUE TITLE
Assertion failure (crash) when clustering key is a frozen collection and reverse order

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7868]
The following trivial cql-pytest, creating a table with a frozen collection and reverse sort order and adding one item to it with a **prepared statement**, crashes Scylla on an assertion failure during the insert:
```python
def test_xyz(cql, test_keyspace):
    with create_table(cql, test_keyspace, f"(a int, b frozen<set<int>>, PRIMARY KEY (a,b)) WITH CLUSTERING ORDER BY (b DESC)") as table:
        execute(cql, table, "INSERT INTO %s (a, b) VALUES (?, ?)", 0, {1, 2, 3});
```

(Note: in this code, the `execute` convenience function does both prepare and execute steps - and it is actually the prepare step which fails, not the execute).

The assertion failure is:
```
test_scylla: cql3/abstract_marker.cc:80: virtual ::shared_ptr<term> cql3::abstra
ct_marker::raw::prepare(database &, const seastar::sstring &, lw_shared_ptr<cql3
::column_specification>) const: Assertion `0' failed.
```

The `WITH CLUSTERING ORDER BY (b DESC)` is important for the crash, it doesn't happen without it. Also, it seems to reproduce with frozen collections of any type but not with, for example, int. The content of the set (here `{1, 2, 3}`) doesn't matter - an empty set `{}` will crash the same.

This crash is also specific to prepared statements - it happens in the prepare phase. Unprepared statements also have a bug in this case, but it looks different: I opened a separate issue about it - #7875.

The backtrace of the above assertion failure is:
```
cql3::abstract_marker::raw::prepare(database&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, seastar::lw_shared_ptr<cql3::column_specification>) const at abstract_marker.cc:?
cql3::single_column_relation::to_term(std::vector<seastar::lw_shared_ptr<cql3::column_specification>, std::allocator<seastar::lw_shared_ptr<cql3::column_specification> > > const&, cql3::term::raw const&, database&, seastar::basic_sstring<char, unsigned int, 15u, true> const&, cql3::variable_specifications&) const at single_column_relation.cc:?
cql3::single_column_relation::new_EQ_restriction(database&, seastar::lw_shared_ptr<schema const>, cql3::variable_specifications&) at single_column_relation.cc:?
cql3::relation::to_restriction(database&, seastar::lw_shared_ptr<schema const>, cql3::variable_specifications&) at relation.cc:?
cql3::restrictions::statement_restrictions::statement_restrictions(database&, seastar::lw_shared_ptr<schema const>, cql3::statements::statement_type, std::vector<seastar::shared_ptr<cql3::relation>, std::allocator<seastar::shared_ptr<cql3::relation> > > const&, cql3::variable_specifications&, bool, bool, bool, bool) at statement_restrictions.cc:?
cql3::statements::modification_statement::process_where_clause(database&, std::vector<seastar::shared_ptr<cql3::relation>, std::allocator<seastar::shared_ptr<cql3::relation> > >, cql3::variable_specifications&) at modification_statement.cc:?
cql3::statements::raw::insert_statement::prepare_internal(database&, seastar::lw_shared_ptr<schema const>, cql3::variable_specifications&, std::unique_ptr<cql3::attributes, std::default_delete<cql3::attributes> >, cql3::cql_stats&) const at update_statement.cc:?
cql3::statements::raw::modification_statement::prepare(database&, cql3::variable_specifications&, cql3::cql_stats&) const at modification_statement.cc:?
cql3::statements::raw::modification_statement::prepare(database&, cql3::cql_stats&) at modification_statement.cc:?
```

CC @dekimir who might be familiar with the relations which the backtrace suggests might be involved (but I don't know yet if it is).

This bug also crashes the Cassandra unit test which I translated into Python, `cassandra_tests/validation/entities/frozen_collections_test.py`::`testClusteringKeyUsageWithReverseOrderSet`.

**Comment by dekimir** [comment]
That backtrace suggests that this `if` was true:
https://github.com/scylladb/scylla/blob/e45af3b9b84da07e3b28eafa51d3c785a9a3d253/cql3/restrictions/statement_restrictions.cc#L162

I don't understand how where_clause is nonempty in that INSERT statement...

**Comment by nyh** [comment]
I'm preparing a test for this issue now (it crashed one of the Cassandra tests, I'm trying to distill the simplest possible test out of it). It turns out that the crash happens on the prepare() already, not even on the INSERT actually being run. In the above test code, the `execute` function did both so it wasn't obvious which crashed.

**Comment by nyh** [comment]
Sent an xfailing test for this to the mailing list, patch titled "[PATCH] cql-pytest: add reproducer for issue #7868".
I discovered that both unprepared and prepared statements fail in the reverse-sort-order cases, but they fail in a very different way - the unprepared statement gives an incorrect error message, and the prepared statement version causes an assertion failure and a crash. The patch tests both.

**Comment by dekimir** [comment]
Please file a separate bug for the non-prepared statement case; there's no reason to comingle them.

**Comment by nyh** [comment]
> Please file a separate bug for the non-prepared statement case; there's no reason to comingle them.

Ok, I will, but there is a reason - it is likely the two bugs stem from the same or a very similar cause, and you'll want to fix both of them in the same patch. But since you asked, I will split it.

**Comment by nyh** [comment]
> Please file a separate bug for the non-prepared statement case; there's no reason to comingle them.

Opened #7875

**Comment by nyh** [comment]
Although I've merged above @dekimir's series which closes this issue, the series was apparently rebased and the merge commit with its "Closes" tag got lost, and this issue was never closed despite the individual commits - commit 176ff0238abba11cf0935cf09f71a363b25aab58, commit 6bb10fcf368116b31bb3248fe9e4676d08b2760d and commit 14fa39cfa6a05b3541c0d9f21900dc2ba761f827, all already in master.

So closing this issue manually.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
