### ISSUE TITLE
null filtering with non-pk column doesn't work as expected (result is empty)

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#7872]
*Installation details*
Scylla version (or git commit hash): 4.4.dev-0.20201220.b3e39d81aa8
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS7

### Description

null support behavior was changed by https://github.com/scylladb/scylla/pull/7804
Filtering with pk=null is no longer invalid, nothing will be return it's expected, because the pk won't be null.

I'm trying to filter with `non-pk column` (eg: v1) = null, currently nothing is returned. I know when INDEX is used, the filter is executed in the index table firstly, and v1 in the INDEX table is not null, so the result is empty.

But the expected result should be returning rows with v1 = null in test table.

### Test steps

```
USE keyspace1;
CREATE TABLE test (
    k int,
    c int,
    v1 int,
    v2 set<text>,
    PRIMARY KEY (k, c)
);
CREATE INDEX on test(v1);
INSERT INTO test (k, c, v1) VALUES (0, 0, null);
INSERT INTO test (k, c, v2) VALUES (0, 1, null);
SELECT * from test where k = 0 and c = 0;
SELECT * from test where k = 0 and c = 0 and v1 = null;
SELECT * from test where v1 = null;
```

### Expected result

```
SELECT * from test where k = 0 and c = 0 and v1 = null;
 k | c | v1   | v2
---+---+------+------
 0 | 0 | null | null

SELECT * from test where v1 = null;
 k | c | v1   | v2
---+---+------+------
 0 | 0 | null | null
 0 | 1 | null | null
```

### current result

```
SELECT * from test where k = 0 and c = 0 and v1 = null;
 k | c | v1 | v2
---+---+----+----

(0 rows)

SELECT * from test where v1 = null;
 k | c | v1 | v2
---+---+----+----

(0 rows)
```

/CC @dekimir @juliayakovlev @roydahan

**Comment by dekimir** [comment]
> But the expected result should be returning rows with v1 = null in test table.

No, the expected result is to return no rows.  See https://github.com/scylladb/scylla/pull/5763#discussion_r405455092

**Comment by juliayakovlev** [comment]
@dekimir May be I don't understand this feature. Why we allow filter by "n=null" if it doesn't work, return any answer? Because Cassandra?

**Comment by dekimir** [comment]
> Why we allow filter by "n=null" if it doesn't work, return any answer?

To be compatible with SQL, whose users expect precisely this behaviour.  I suspect it makes the front-end code simpler in many cases.

> Because Cassandra?

Avi mentioned [here](https://github.com/scylladb/scylla/pull/5763#discussion_r405556437) that he's OK differing from Cassandra on this.

**Comment by juliayakovlev** [comment]
> > Why we allow filter by "n=null" if it doesn't work, return any answer?
> 
> To be compatible with SQL, whose users expect precisely this behaviour. I suspect it makes the front-end code simpler in many cases.
> 
> > Because Cassandra?
> 
> Avi mentioned [here](https://github.com/scylladb/scylla/pull/5763#discussion_r405556437) that he's OK differing from Cassandra on this.

@dekimir 
Thank you, Dejian, for explanation. AFAIK, SQL allow to filter by NULL as "WHERE column IS NULL" and return relevant rows for this request. So I am not sure that SQL user expect to receive empty response for such request.

**Comment by dekimir** [comment]
> SQL allow to filter by NULL as "WHERE column IS NULL" and return relevant rows for this request. So I am not sure that SQL user expect to receive empty response for such request.

That's a different query, though.  We are talking about `WHERE column=NULL` here.
