### ISSUE TITLE
Failed unprepared insert when clustering key is a frozen collection and reverse order

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7875]
In issue #7868 I noted that in a table with a frozen collection and reverse sort order, when you add one item to it with a prepared statement, Scylla crashes on an assertion failure. 

We also have a different bug if we try to add an item to such a table with an **unprepared statement**, and this issue is about this bug.

The following test code:
```python
def test_clustering_key_reverse_frozen_collection(cql, test_keyspace):
    with new_test_table(cql, test_keyspace,
            "a int, b frozen<set<int>>, PRIMARY KEY (a,b)",
            "WITH CLUSTERING ORDER BY (b DESC)") as table:
         cql.execute("INSERT INTO " + table + " (a, b) VALUES (0, {1, 2, 3})")

```

Results in an unjustified error message "Invalid set literal for b of type frozen<set<int>>".
There is no such error if we drop the reverse ordering ("WITH CLUSTERING ORDER"), and Cassandra also accepts this case.

**Comment by nyh** [comment]
Although I've merged above @dekimir's series which closes this issue, the series was apparently rebased and the merge commit with its "Closes" tag got lost, and this issue was never closed despite the individual commits - commit 176ff02, commit 6bb10fc and commit 14fa39c, all already in master.

So closing this issue manually.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
