### ISSUE TITLE
Proposal: add sstable origin information to scylla metadata component

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7880]
Today, when we hit a corrupted sstable in the field, it is hard to tell how exactly this sstable was generated.
It could come from e.g. memtable flush, compaction, streaming, repair, etc.

If it came from compaction, it would also be valuable to know which kind of compaction (e.g. regular, resharding, cleanup, scrub) and what compaction strategy was in use.

Also the version of scylla could be useful to correlate the sstable contents with a particular scylla version, as some corruption causes are fixed over time and it's instrumental to know if a sstable was created before or after an upgrade (or follow a chain of compactions that carried over corruption from corrupt sstables from a previous versions).

Theoretically, the software version could also use by an adaptive reader that would compensate for a data-format bug in a previous version, though we should do our best to refrain from doing that.

**Comment by bhalevy** [comment]
Cc @denesb @tgrabiec @raphaelsc @asias

**Comment by denesb** [comment]
The issue of determining the origin of an sstable comes up time and time again during investigations. Big +1 for adding this.
