### ISSUE TITLE
cfhistrograms shows wrong stats

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#789]
While running c-s and having mean latency of 1-2msec I get bogus stat from the nodetool:

[root@server-01 scylla]# nodetool cfhistograms test1 standard1
test1/standard1 histograms
Percentile  SSTables     Write Latency      Read Latency    Partition Size        Cell Count
                              (micros)          (micros)           (bytes)                  
50%             0.00              6.00              0.00               310                 5
75%             0.00              8.00              0.00               310                 5
95%             0.00             17.00              0.00               310                 5
98%             0.00             24.00              0.00               310                 5
99%             0.00             29.00              0.00               310                 5
Min             0.00              0.00              0.00               259                 5
Max             0.00          24601.00              0.00               310                 5

**Comment by tzach** [comment]
> While running c-s and having mean latency of 1-2msec I get bogus stat from the nodetool:

What c-s command did you used? is it read or write?

**Comment by dorlaor** [comment]
If I'm not mistaken it was just writes. Still, it wasn't near the values
that c-s reported.

**Comment by tzach** [comment]
cfhistograms results you included shows only Read latency, so there might be more than one issue here

**Comment by tzach** [comment]
I repeated the test with one node of Scylla and one node of Cassandra for comparison.
Note that c-s run on the same instance as the DB, so the throughput is not very important.

Cassandra
```
cassandra-stress write n=1000000 cl=one -mode native cql3 -schema keyspace="keyspace1" -pop seq=1..1000000 -rate threads=100
...
...
op rate                   : 15341 [WRITE:15341]
partition rate            : 15341 [WRITE:15341]
row rate                  : 15341 [WRITE:15341]
latency mean              : 6.5 [WRITE:6.5]
latency median            : 4.0 [WRITE:4.0]
latency 95th percentile   : 17.7 [WRITE:17.7]
latency 99th percentile   : 32.6 [WRITE:32.6]
latency 99.9th percentile : 95.4 [WRITE:95.4]
latency max               : 1111.4 [WRITE:1111.4]

$ nodetool cfhistograms keyspace1 standard1
keyspace1/standard1 histograms
Percentile  SSTables     Write Latency      Read Latency    Partition Size        Cell Count
                              (micros)          (micros)           (bytes)                  
50%             0.00             10.00              0.00               310                 5
75%             0.00             35.00              0.00               310                 5
95%             0.00            103.00              0.00               310                 5
98%             0.00            215.00              0.00               310                 5
99%             0.00            770.00              0.00               310                 5
Min             0.00              2.00                  0.00               259                 5
Max             0.00        1131752                0.00               310                 5
```

Scylla 

```
cassandra-stress write n=1000000 cl=one -mode native cql3 -schema keyspace="keyspace1" -pop seq=1..1000000 -rate threads=100

...
...
op rate                   : 21281 [WRITE:21281]
partition rate            : 21281 [WRITE:21281]
row rate                  : 21281 [WRITE:21281]
latency mean              : 4.7 [WRITE:4.7]
latency median            : 4.0 [WRITE:4.0]
latency 95th percentile   : 10.1 [WRITE:10.1]
latency 99th percentile   : 17.5 [WRITE:17.5]
latency 99.9th percentile : 36.9 [WRITE:36.9]
latency max               : 106.7 [WRITE:106.7]


$ nodetool cfhistograms keyspace1 standard1
keyspace1/standard1 histograms
Percentile  SSTables     Write Latency      Read Latency    Partition Size        Cell Count
                              (micros)          (micros)           (bytes)                  
50%             0.00              4.00              0.00               310                 5
75%             0.00              5.00              0.00               310                 5
95%             0.00              7.00              0.00               310                 5
98%             0.00              8.00              0.00               310                 5
99%             0.00             10.00              0.00               310                 5
Min             0.00              0.00              0.00               259                 5
Max             0.00           8239.00              0.00               310                 5
```

Observations:
On both DB, the latency is much smaller on the internal measurement, compare to external (c-s)
c-s report in milliseconds while cfhistograms in micros!
50% (median latnecy) for C* is 4.0 ms by c-s, and only 10µ in cfhistogram

Scylla latency seems to make sense, except the max one which seems very high

**Comment by dorlaor** [comment]
There is quite a difference. C-s measures 32msec for 99% while the nodetool
measured 770us. It's 50 times larger.

**Comment by tgrabiec** [comment]
@dorlaor Doesn't c-s measurement include the network round trip while cfhistogram only latency of in-memory apply? I'd expect the latter to be much smaller.

**Comment by dorlaor** [comment]
On Mon, Jan 18, 2016 at 2:44 PM, Tomasz Grabiec <notifications@github.com>
wrote:

> @dorlaor <https://github.com/dorlaor> Doesn't c-s measurement include the
> network round trip while cfhistogram only latency of in-memory apply? I'd
> expect the latter to be much smaller.
>
I agree it shouldn't be identical but 50 times better?
Maybe it's the case for writes since we measure the time since we receive
the query to the time it gets into the memtable but not to the flush time.
This indeed suppose to happen fast. With reads and disk access it will take
longer.

**Comment by tgrabiec** [comment]
The c-s latency accounts many things which cfhistogram doesn't:
  * time spent in TCP queues
  * time spent on the network
  * time spent in seastar's smp queues
  * processing in the CQL server / coordinator
  * writing to the commit log

Depending on load level, time spent in queues may be significantly larger than processing time. What's your concurrency level? Does the difference decrease if you lower the concurrency?

**Comment by tzach** [comment]
Its hard to figure out to what extent the numbers are accurate, but they do look reasonable, and align to the same number in C* (only better) so we can close this issue.

**Comment by tzach** [comment]
For completeness, here are the same results for c-s read

Cassandra
```
cassandra-stress read n=1000000 cl=one -mode native cql3 -schema keyspace="keyspace1" -pop seq=1..1000000 -rate threads=100
...
op rate                   : 15708 [READ:15708]
partition rate            : 15708 [READ:15708]
row rate                  : 15708 [READ:15708]
latency mean              : 6.4 [READ:6.4]
latency median            : 4.2 [READ:4.2]
latency 95th percentile   : 16.2 [READ:16.2]
latency 99th percentile   : 37.8 [READ:37.8]
latency 99.9th percentile : 83.4 [READ:83.4]
latency max               : 235.2 [READ:235.2]


$ nodetool cfhistograms keyspace1 standard1
keyspace1/standard1 histograms
Percentile  SSTables     Write Latency      Read Latency    Partition Size        Cell Count
                              (micros)          (micros)           (bytes)                  
50%             1.00              0.00             50.00               310                 5
75%             1.00              0.00            179.00               310                 5
95%             1.00              0.00            642.00               310                 5
98%             1.00              0.00           3973.00               310                 5
99%             1.00              0.00          11864.00               310                 5
Min             0.00              0.00             15.00               259                 5
Max             1.00              0.00         315852.00               310                 5

```

Scylla

```
cassandra-stress read n=1000000 cl=one -mode native cql3 -schema keyspace="keyspace1" -pop seq=1..1000000 -rate threads=100
....
op rate                   : 21441 [READ:21441]
partition rate            : 21441 [READ:21441]
row rate                  : 21441 [READ:21441]
latency mean              : 4.6 [READ:4.6]
latency median            : 4.1 [READ:4.1]
latency 95th percentile   : 8.6 [READ:8.6]
latency 99th percentile   : 13.9 [READ:13.9]
latency 99.9th percentile : 23.1 [READ:23.1]
latency max               : 112.6 [READ:112.6]


$ nodetool cfhistograms keyspace1 standard1
keyspace1/standard1 histograms
Percentile  SSTables     Write Latency      Read Latency    Partition Size        Cell Count
                              (micros)          (micros)           (bytes)                  
50%             0.00              0.00             10.00               310                 5
75%             0.00              0.00             12.00               310                 5
95%             0.00              0.00             17.00               310                 5
98%             0.00              0.00            103.00               310                 5
99%             0.00              0.00            446.00               310                 5
Min             0.00              0.00              3.00               259                 5
Max             0.00              0.00          24601.00               310                 5

```

**Comment by amnonh** [comment]
@dorlaor  From the discussion above, can it be close?
