### ISSUE TITLE
crash with large (13k+) partition key during in cache

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#7896]
cache_entry::do_read() is missing a with_linearized_managed_bytes(). This can cause a crash if a partition key is larger than 13k.

**Comment by raphaelsc** [comment]
> cache_entry::do_read() is missing a with_linearized_managed_bytes(). This can cause a crash if a partition key is larger than 13k.

looks like this is fixed already by https://github.com/scylladb/scylla/issues/7897, closing this issue...
