### ISSUE TITLE
nodetool gossipinfo is out of sync

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#790]
Found when working on #771 .

    [benoit@localhost scylla-tools-java]$ ./bin/nodetool gossipinfo -p 7100
    127.0.0.3
    generation:1452527837
    heartbeat:3861
    SCHEMA:cdcc50b2-9e07-3a1f-a626-ea5faa87b454
    RACK:rack1 
    RELEASE_VERSION:2.1.8
    STATUS:NORMAL,9075301760351459647
    NET_VERSION:0
    LOAD:2.29843e+09
    HOST_ID:2b213373-9e1b-4f67-8403-5fedf2b14e27
    DC:datacenter1
    RPC_ADDRESS:127.0.0.3
    127.0.0.2
    generation:1452527841
    heartbeat:4514 
    SCHEMA:cdcc50b2-9e07-3a1f-a626-ea5faa87b454 
    RACK:rack1 
    RELEASE_VERSION:2.1.8
    STATUS:NORMAL,951437828564849749
    NET_VERSION:0
    LOAD:4.58926e+09 
    HOST_ID:1121104a-4e3e-4120-af91-d0319abe3c4d 
    DC:datacenter1
    RPC_ADDRESS:127.0.0.2
    127.0.0.1
    generation:1452531571
    heartbeat:695
    SCHEMA:cdcc50b2-9e07-3a1f-a626-ea5faa87b454
    RACK:rack1
    RELEASE_VERSION:2.1.8
    STATUS:NORMAL,9178998398201883111
    NET_VERSION:0 
    LOAD:1.5131e+09 
    HOST_ID:6fa36e4f-881e-4db2-8d6d-0f2acffc8c4e
    DC:datacenter1
    RPC_ADDRESS:127.0.0.1

and

    [benoit@localhost scylla-tools-java]$ ccm status

    Cluster: 'scylla-3'

    node1: UP
    node3: DOWN
    node2: UP

node3 being:
    STATUS:NORMAL,9075301760351459647
is not normal is should be shutdown,true

Patch written and working will soon be sent to the list

**Comment by benoit-canet** [comment]
patch sent to the list

**Comment by asias** [comment]
What did you do to node3? Did you run './bin/nodetool gossipinfo -p 7100' a few seconds later to check "127.0.0.3" is in DOWN state?

**Comment by asias** [comment]
What does nodetool status says? Please note, a node can be in NORMAL status but it is DOWN status. In nodetool status, it shows as DN. The UP and NORMAL node will be show as UN.

**Comment by benoit-canet** [comment]
The state will not change at all disregarding how long we wait for it.

Cassandra would mark the node as shutdown,true.

**Comment by asias** [comment]
Which version did you use 2.1.8? We have backported changes from 2.1.11 in
gossip and storage_service subsystem. Can you verify c* 2.1.11?

On Thu, Jan 14, 2016 at 6:28 PM, Benoît Canet <notifications@github.com>
wrote:

> The state will not change at all disregarding how long we wait for it.
>
> Cassandra would mark the node as shutdown,true.
>
> On Thu, Jan 14, 2016 at 12:18 AM, Asias He <notifications@github.com>
> wrote:
>
> > What did you do to node3? Did you run './bin/nodetool gossipinfo -p 7100'
> > a few seconds later to check "127.0.0.3" is in DOWN state?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/scylladb/scylla/issues/790#issuecomment-171468914>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/790#issuecomment-171599031>.
>



-- 
Asias

**Comment by benoit-canet** [comment]
I confirm the shutdown,true behavior with 2.1.12.

I will send a better patch asap.

**Comment by asias** [comment]
This is log with c* on node1:


```
ccm create cas-test3  --vnodes -n 3 --install-dir=`pwd`/../scylla-tools-java
ccm start
ccm node1 stop
```


```
 0 INFO  [main] 2016-01-15 06:50:24,009 Server.java:182 - Starting listening for CQL clients on /127.0.0.1:9042...
  1 INFO  [main] 2016-01-15 06:50:24,064 ThriftServer.java:119 - Binding thrift service to /127.0.0.1:9160
  2 INFO  [Thread-2] 2016-01-15 06:50:24,068 ThriftServer.java:136 - Listening for thrift clients...
  3 INFO  [GossipStage:1] 2016-01-15 06:50:24,343 OutboundTcpConnection.java:97 - OutboundTcpConnection using coalescing strategy DISABLED
  4 INFO  [HANDSHAKE-/127.0.0.2] 2016-01-15 06:50:24,346 OutboundTcpConnection.java:485 - Handshaking version with /127.0.0.2
  5 INFO  [GossipStage:1] 2016-01-15 06:50:24,367 Gossiper.java:989 - Node /127.0.0.2 is now part of the cluster
  6 INFO  [SharedPool-Worker-1] 2016-01-15 06:50:24,370 Gossiper.java:954 - InetAddress /127.0.0.2 is now UP
  7 INFO  [GossipStage:1] 2016-01-15 06:50:25,328 Gossiper.java:989 - Node /127.0.0.3 is now part of the cluster
  8 INFO  [HANDSHAKE-/127.0.0.3] 2016-01-15 06:50:25,330 OutboundTcpConnection.java:485 - Handshaking version with /127.0.0.3
  9 INFO  [SharedPool-Worker-1] 2016-01-15 06:50:25,331 Gossiper.java:954 - InetAddress /127.0.0.3 is now UP
 10 INFO  [StorageServiceShutdownHook] 2016-01-15 06:51:08,257 ThriftServer.java:142 - Stop listening to thrift clients
 11 INFO  [StorageServiceShutdownHook] 2016-01-15 06:51:08,272 Server.java:213 - Stop listening for CQL clients
 12 INFO  [StorageServiceShutdownHook] 2016-01-15 06:51:08,273 Gossiper.java:1410 - Announcing shutdown
 13 INFO  [StorageServiceShutdownHook] 2016-01-15 06:51:10,274 MessagingService.java:708 - Waiting for messaging service to quiesce
 14 INFO  [ACCEPT-/127.0.0.1] 2016-01-15 06:51:10,276 MessagingService.java:958 - MessagingService has terminated the accept() thread
```


This is scylla's log:

```
  0 Starting listening for CQL clients on 127.0.0.1:9042...
  1 Scylla API server listening on 127.0.0.1:10000 ...
  2 [Fri Jan 15 07:13:35 2016] INFO  [shard 0] gossip - Node 127.0.0.2 is now part of the cluster
  3 [Fri Jan 15 07:13:35 2016] INFO  [shard 0] gossip - InetAddress 127.0.0.2 is now UP
  4 [Fri Jan 15 07:13:35 2016] INFO  [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 127.0.0.2
  5 [Fri Jan 15 07:14:18 2016] INFO  [shard 0] compaction_manager - compaction task handler stopped due to shutdown
  6 [Fri Jan 15 07:14:18 2016] INFO  [shard 0] compaction_manager - compaction task handler stopped due to shutdown
```


The problem is that, c* hooks shutdown (drainOnShutdown), while scylla does not at the moment.

@avikivity can we enable stop on shutdown now?

#293 - do not stop anything
//engine().at_exit([&proxy] { return proxy.stop(); });
