### ISSUE TITLE
Failed SELECT with tuple of reversed-ordered frozen collections

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7902]
This is another bug similar to #7868 and #7875 - a statement with a **reverse-ordered** frozen collection as a clustering key fails because of incorrect type checking in the code that fails to look at the underlying type. This one involves a **tuple** of such frozen collections passed to a SELECT request.

This bug is reproduced by `test/cql-pytest/cassandra_tests/validation/entities/frozen_collections_test.py`::`testNestedClusteringKeyUsageWithReverseOrder`.

The relevant part of the test is:
```python
def testNestedClusteringKeyUsageWithReverseOrder(cql, test_keyspace):
    with create_table(cql, test_keyspace, "(a int, b frozen<map<set<int>, list<int>>>, c frozen<set<int>>, d int, PRIMARY KEY (a, b, c)) WITH CLUSTERING ORDER BY (b DESC)") as table:
         execute(cql, table, "SELECT * FROM %s WHERE a=? AND (b, c) IN ?", 0, [tuple([{frozenset({4, 5, 6}): [1, 2, 3]}, {1, 2, 3}]), tuple([{}, {}])])
```

Where the bound variable needs to be a tuple whose components are a frozen map and a frozen set, but we get the error:
```
E   cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.59.156.120:90
42 datacenter1>: <Error from server: code=0000 [Server error] message="tuple element type mismatch: expected org.apache
.cassandra.db.marshal.ReversedType(org.apache.cassandra.db.marshal.FrozenType(org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.FrozenType(org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.Int32Type)),org.apache.cassandra.db.marshal.FrozenType(org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.Int32Type))))), got org.apache.cassandra.db.marshal.FrozenType(org.apache.cassandra.db.marshal.MapType(org.apache.cassandra.db.marshal.FrozenType(org.apache.cassandra.db.marshal.SetType(org.apache.cassandra.db.marshal.Int32Type)),org.apache.cassandra.db.marshal.FrozenType(org.apache.cassandra.db.marshal.ListType(org.apache.cassandra.db.marshal.Int32Type))))">})
```

Clearly yet again we have code that compares the "ReversedType" instead of the underlying type.

By the way it's unfortunate that this error is marked a "Server Error" (which causes the driver to fail in a weird way) and not a InvalidRequest - that should have been the error if the input was really incorrect (which it wasn't, but Scylla thought it was).

CC @dekimir

**Comment by avikivity** [comment]
Backported to 4.4 (4.5 had it already).
