### ISSUE TITLE
Consistency level mismatch

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#791]
Setup - 3 nodes, 0.15 release.

Client issue the following:
ansible client -a "cassandra-stress write no-warmup duration=15m cl=QUORUM -schema 'replication(factor=3) keyspace=test1' -mode native cql3 -rate limit=250000/s threads=500 -node 10.184.13.11 -log file=/tmp/stress" -u root -vv

When I kill one of the nodes (not the seed one nor the one in the c-s IP), the client receives the following exception. The same case is for writes.

java.io.IOException: Operation x10 on key(s) [384f303733504c334e30]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)

	at org.apache.cassandra.stress.Operation.error(Operation.java:216)
	at org.apache.cassandra.stress.Operation.timeWithRetry(Operation.java:188)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:99)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:107)
	at org.apache.cassandra.stress.operations.predefined.CqlOperation.run(CqlOperation.java:259)
	at org.apache.cassandra.stress.StressAction$Consumer.run(StressAction.java:309)

**Comment by slivne** [comment]
maybe these are in flight requests - ones that are on the wire that fail (either client-cordinator / cordinator-node)

if you start the c-s after the node is down does it work ?

if you do the same with cassandra does it pass ?

**Comment by gleb-cloudius** [comment]
On Wed, Jan 13, 2016 at 06:12:01AM -0800, Dor Laor wrote:
> Setup - 3 nodes, 0.15 release.
> 
> Client issue the following:
> ansible client -a "cassandra-stress write no-warmup duration=15m cl=QUORUM -schema 'replication(factor=3) keyspace=test1' -mode native cql3 -rate limit=250000/s threads=500 -node 10.184.13.11 -log file=/tmp/stress" -u root -vv
> 
> When I kill one of the nodes (not the seed one nor the one in the c-s IP), the client receives the following exception. The same case is for writes.
> 
> java.io.IOException: Operation x10 on key(s) [384f303733504c334e30]: Error executing: (ReadTimeoutException): Cassandra timeout during read query at consistency QUORUM (2 responses were required but only 1 replica responded)
Who is reading what? You ran write workload.

--
			Gleb.

**Comment by dorlaor** [comment]
@gleb-cloudius, the same happens for read workload and for write workload.

**Comment by dorlaor** [comment]
When CL=ONE it does work

**Comment by dorlaor** [comment]
It doesn't happen on another setup. I'll close it for the time being
