### ISSUE TITLE
Failed fromJson() should result in FunctionFailure error, not an internal error

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7911]
The CQL statement
```
INSERT INTO table1 (p, v) VALUES (123, fromJson('dog'))
```
Fails, because `dog` is not a valid JSON. However, it should fail in clear way that makes it clear that this is a problem in the request - not some weird (and retry-able?) internal server error.
In Cassandra the error we get is: 
```
E   cassandra.FunctionFailure: Error from server: code=1400 [User Defined Function failure] message="execution of 'system.fromjson[text]' failed: Could not decode JSON string 'dog': com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'dog': was expecting ('true', 'false' or 'null')
E    at [Source: (String)"dog"; line: 1, column: 7]"
```
In Scylla, we currently return a server internal error for such a query, misleading the driver to think it could retry the same query to other nodes, and ending up reporting a confusing message about nodes being unavailable:
```
E   cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.60.202.231:90
42 datacenter1>: <Error from server: code=0000 [Server error] message="Parsing JSON failed: Invalid value.">})
```

The following trivial test works on Cassandra and fails on Scylla (produces the wrong exception):
```
def test_failed_json_parsing(cql, table1):
    with pytest.raises(FunctionFailure):
        cql.execute(f"INSERT INTO {table1} (p, v) VALUES (123, fromJson('dog'))")
```

The internal server error issue applies not only to unparseable JSON, it also applies to other errors stemming from this evaluation, notably -the JSON producing a result which isn't compatible with the type it's supposed to return, e.g., JSON returning a string when an integer was expected, or returning a string with non-ASCII characters when ASCII was expected, returning a floating-point number when an integer was expected. All of these are cases are correctly detected by Scylla, but produce bizarre "server errors" instead of the expected `FunctionFailure`.

In the `json_tests.py` we have xfailing tests for all these cases - search for the `@pytest.mark.xfail(reason="issue #7911")` marker.

This issue also causes **dozens** of different failures of the translated Cassandra test `cassandra_tests/validation/entities/json_test.py`::`testFromJsonFct`. All of them are marked with the comment "`reproduces #7911`".

**Comment by avikivity** [comment]
Backported to 4.4. 4.5+ had it already.
