### ISSUE TITLE
fromJson() should accept "true" and "false" also as strings

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7915]
When writing to a boolean column **with a prepared statement**, Cassandra's `fromJson()` function allows not just JSON's `true` and `false` constants, it also allows the strings `"true"`, `"false"`:
```
stmt = cql.prepare(f"INSERT INTO {table1} (p, b) VALUES (?, fromJson(?))")
cql.execute(stmt, [p, '"true"'])
```

This capability is not accidental - they even have a special test for it in `cassandra_tests/validation/entities/json_test.py`::`testFromJsonFct`. 

**UPDATE (1 Mar, 2022)** @Jadw1 discovered that the following statements about the unprepared case not working in Cassandra were wrong, and I was just misled by a bug in the test. See the next comment for details.

Strangely this test only tests the prepared statement case. Had Cassandra also tested the unprepared statement case, they would have noticed that it doesn't work! While the prepared statement works, the unprepared statement:
```
cql.execute(f"INSERT INTO {table1} (p, b) VALUES ({p}, '\"true\"')") 
```
Fails with "Invalid STRING constant ("true") for "b" of type boolean". It fails in the same way in Scylla.

But for the prepared statement case, which is allows in Cassandra, Scylla return a  a server error, with the strange message "marshaling error: Invalid JSON object "false"". The message is strange, because the JSON string object is not invalid in any way (it is a valid string, and moreover should be convertible into a boolean).

See also test cases in `test_json.py`: `test_fromjson_boolean_string_unprepared` - which works on both Scylla and Cassandra, and `test_fromjson_boolean_string_prepared` which xfails on Scylla.

**Comment by avikivity** [comment]
Backported to 4.6, 5.0. 5.1 has it.
