### ISSUE TITLE
api: a large allocation occurs in /column_family/ GET request handler

### ISSUE THREAD

**Issue by wmitros** [scylladb/scylla#7916]
As detected in #6376, in the 5000 tables cluster test, a large (>1MB) allocation occurs when responding to a /column_family/ GET request, because we're creating a vector which contains names and keyspaces of all column families, and the response is generated by creating a string with all data from the vector. The function for creating this vector is here https://github.com/scylladb/scylla/blob/6cfc949e6217ac987dbed6b53c10e399cb5cf61e/api/column_family.cc#L313-L323

**Comment by avikivity** [comment]
Minor, not a regression, so not backporting.
