### ISSUE TITLE
Docs: Alternator Documentation Issues

### ISSUE THREAD

**Issue by lauranovich** [scylladb/scylla#7924]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

This is a Documentation bug - please assign to Laura

https://scylla.docs.scylladb.com/master/alternator/compatibility.html

(for example), is not live as an alternative to:

https://github.com/scylladb/scylla/blob/master/docs/alternator/compatibility.md
.

I wanted to ask how this happens in practice - is new content committed to master automatically copied to the new site? Does this copying happen every time there's a commit (how quickly?), or daily (or whatever), or when/how?

I wanted to also ask you to please review the formatting of the new site - please compare the above two links to the same content, and consider where we can learn from github's formatting where it is better. I think there are places where  github's formatting is better (in my opinion) than our new site and we can learn from them. Here are specific examples:

1. github automatically converts URLs to links. On the new site, this feature is missing. It's not useful to see a URL without being able to click on it. The page above has dozens of links - to other documents, to issues, etc., and none of them are usable :-(

2. The gray background of `backquoted text` is, I think, too strong. It is a bit too strong for my taste also in the github rendering, but in ours it's even more prominent, for no reason.

3. The second-level lists are not clear enough in my opinion. In github's rendering they have a different color, and generous indentation. In our version, it's the same bullet style and very narrow indentation.

4. I prefer the way that github's bulleted paragraphs have a generous spacing between them. Our style is good for short lists of items - but less nice (in my opinion) for bulleted paragraphs as used in this document.

**Comment by nyh** [comment]
I moved these requests to the separate docs repository, so closing this issue.
