### ISSUE TITLE
Incorrect output in nodetool compactionstats

### ISSUE THREAD

**Issue by yakirgb** [scylladb/scylla#7927]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

Opened based on [Slack thread](https://scylladb-users.slack.com/archives/C2NLNBXLN/p1610895283055800?thread_ts=1610880220.054200&cid=C2NLNBXLN) with @fruch 

*Installation details*
Scylla version: 4.1.7-0.20200918.2251a1c577
Cluster size: 5TB
OS: CentOS Linux release 7.4.1708 (Core) 

Platform: physical
Hardware: sockets=2 cores=40 hyperthreading=disabled memory=187GB
Disks: 1 NVME, 3 TB

I see incorrect output in `nodetool compactionstats -H`:
```
[root@cor002 ~]# nodetool compactionstats -H
pending tasks: 3
- e_a_ks.r_a: 3
id     compaction type keyspace    table   completed total   unit progress
<none> COMPACTION      e_a_ks      r_a     912979    4153856 keys 21.98%
<none> COMPACTION      e_a_ks      r_a     914629    4083200 keys 22.40%
<none> COMPACTION      e_a_ks      r_a     940824    4056064 keys 23.20%
<none> COMPACTION      e_a_ks      r_a     911964    4079872 keys 22.35%
```

1. Compaction ID is missing and show `none`
2. Unable to see human readable values

Thank you,
Yakir Gibraltar.

**Comment by slivne** [comment]
@amnonh can you try and chase this - do we have compaction ids and why they are not printed.
