### ISSUE TITLE
Reactor stall and oversized allocations while scanning a partition with a long string of tombstones

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#7929]
When scanning a partition with a huge number of consecutive tombstones, the scan cannot stop between them (the precise reason why this is the case is different in Alternator and CQL implementations, but it's true in both). We know this is the case (and have issues #3672 and #3914 about the CQL version, and #7933 suggesting how to fix it in Alternator) and know that it can cause huge latency for this specific request. However, the point of this issue is that in this case we also experience a **reactor stall** - which adds a huge latency to all requests, not just the request to the problematic partition. We also see a huge contiguous allocation which can cause problems. 

A user reported the same issue, complete with decoded stall traces, in #7873.

The following Alternator test reproduces this bug with Alternator in 30 seconds:
```python 
import pytest
from util import create_test_table

@pytest.fixture(scope="function")
def table(dynamodb):
    table = create_test_table(dynamodb,
        KeySchema=[ { 'AttributeName': 'p', 'KeyType': 'HASH' },
                    { 'AttributeName': 'c', 'KeyType': 'RANGE' }  ],
        AttributeDefinitions=[ { 'AttributeName': 'p', 'AttributeType': 'N' },
                    { 'AttributeName': 'c', 'AttributeType': 'N' } ])
    yield table
    table.delete()

def test_scan_long_partition(table):
    count = 100000
    content = 'x' * 100
    with table.batch_writer() as batch:
        for i in range(count):
            batch.put_item(Item={ 'p': 1, 'c': i,
                'attribute': str(i), 'another': content })
     # Delete all items except the first and last
    with table.batch_writer() as batch:
        for i in range(count):
            if i != 0 and i != (count-1):
                batch.delete_item(Key={ 'p': 1, 'c': i})
    response = table.scan()
    assert len(response['Items']) == 2
```

And the following cql-pytest does the same with CQL:

```python
from util import new_test_table
import pytest

def test_scan_long_partition(cql, test_keyspace):
    count = 400000
    with new_test_table(cql, test_keyspace,
            "p int, c int, attribute text, another text, PRIMARY KEY (p, c)") as table:
        content = 'x' * 100
        stmt = cql.prepare(f"INSERT INTO {table} (p, c, attribute, another) VALUES (?, ?, ?, '{content}')")
        for i in range(count):
            cql.execute(stmt, [1, i, str(i)])
        # Delete all items except the first and last
        stmt = cql.prepare(f"DELETE FROM {table} WHERE p=? and c=?")
        for i in range(count):
            if i != 0 and i != (count-1):
                cql.execute(stmt, [1, i])
        response = list(cql.execute(f"SELECT p, c FROM {table}"))
        print(response)
        assert len(response) == 2
```

Each of these test creates _count_ items in a single partition, and then deletes all of them except the first and the last items. It then scans the table. As can be shown by a similar test leaving behind more than two live items, the Scylla paging code does want to avoid a huge read to return one page (there is a limit of 1MB) - but paging also cannot end in the middle of a string of tombstones, so it reads this entire string of _count-2_ tombstones and the first (and only) page contains the last item as well,

The problem is that we see a reactor stall, and oversized allocation, in this run. Both become worse if count is increased further. On my laptop and dev run, the above _count_ is high enough to report a stall. In the Alternator run, I see a 522 ms stall, with a backtrace (abbreviated):

```
boost::intrusive::compact_rbtree_node()
mutation_partition::clustered_row()
partition_builder::accept_row()
mutation_partition_view::do_accept<partition_builder>
frozen_mutation::unfreeze()
to_data_query_result()
```

(this is the same `to_data_query_result()` as implicated in #7887 

We also see in this test an oversized allocation warning for 4001792 bytes, and the backtrace points to the same `to_data_query_result()` function:
```
std::vector<ser::deletable_row_view, std::allocator<ser::deletable_row_view> >::reserve()
ser::idl::serializers::internal::vector_serializer<...>::read<...>(...)
ser::mutation_partition_view::rows()
mutation_partition_view::do_accept<partition_builder>()
frozen_mutation::unfreeze()
to_data_query_result()
```

**Comment by avikivity** [comment]
@nyh you can add your reproducer to one of the existing bugs (and close the others as duplicates).

**Comment by psarna** [comment]
There seem to be two separate problems (with one root cause) here though - one is reactor stalls, and the other is the operation timing out. So if here we're addressing reactor stalls, #3914 is not really a duplicate.

I agree with https://github.com/scylladb/scylla/issues/7873#issuecomment-761849965 though that while reactor stalls can be fixed the same way for alternator and CQL, it would be harder to mitigate the timeout in alternator, due to how paging state is returned in the DynamoDB protocol.

**Comment by nyh** [comment]
> There seem to be two separate problems (with one root cause) here though - one is reactor stalls, and the other is the operation timing out. So if here we're addressing reactor stalls, #3914 is not really a duplicate.

I agree. I'll reword.
 
> I agree with [#7873 (comment)](https://github.com/scylladb/scylla/issues/7873#issuecomment-761849965) though that while reactor stalls can be fixed the same way for alternator and CQL,

Yes, I edited the original issue with a CQL reproducer

> it would be harder to mitigate the timeout in alternator, due to how paging state is returned in the DynamoDB protocol.

It may be possible in both (note that it's not relevant to this issue).To mitigate in CQL would require the ability to return zero-sized pages, which we currently don't have. In Alternator there is no way to say how to continue "between" two live items, but it may still be possible - we can return for `LastEvaluatedKey` a _dead_ item. Dead items still have keys! I think this will work!

**Comment by psarna** [comment]
Right, sounds like it would work indeed. Especially that DynamoDB apps should be ready for empty pages [anyway](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html):
 > A Query operation can return an empty result set and a LastEvaluatedKey if all the items read for the page of results are filtered out.

**Comment by slivne** [comment]
@eliransin / @nyh lets add this to the plan

**Comment by bhalevy** [comment]
Reported by "Performance Regression Compare Results - PerformanceRegressionCDCTest.test_mixed_latency - 5.1.dev - 2022-03-27 07:15:17.739676"

Version Details:
build date: 2022-03-17
commit id: c45050895403
Setup Details:
ami_id_db_scylla: ami-012c8d51c0e308773
cluster_backend: aws
instance_type_db: i3.2xlarge
instance_type_loader: c4.2xlarge
instance_type_monitor: t3.small
region_name: ['us-east-1']

```
2022-03-27 07:18:53.000: (DatabaseLogEvent Severity.DEBUG): type=REACTOR_STALLED regex=Reactor stalled line_number=25865 node=Node perf-cdc-latency-mixed-perf-v10-db-node-d916b5ac-2 [3.239.110.36 | 10.0.3.6] (seed: False)
2022-03-27T07:18:53+00:00  perf-cdc-latency-mixed-perf-v10-db-node-d916b5ac-2 !INFO    | scylla[8582]: Reactor stalled for 66 ms on shard 3. Backtrace: 0x45c5ba2 0x45c4800 0x45c5ab0 0x7faf1b440a1f 0x140058c 0x1640d8a 0x16d4b72 0x1575c61 0x1663b48 0x24e9265 0x250114b 0x45d6be4 0x45d7fc7 0x45f6c95 0x45aab0a 0x92a4 0x100322
0x45c5ba2
0x45c4800
0x45c5ab0
0x7faf1b440a1f
0x140058c
0x1640d8a
0x16d4b72
0x1575c61
0x1663b48
0x24e9265
0x250114b
0x45d6be4
0x45d7fc7
0x45f6c95
0x45aab0a
0x92a4
0x100322
```

Decoded:
```
void seastar::backtrace<seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}>(seastar::backtrace_buffer::append_backtrace_oneline()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace_oneline() at ./build/release/seastar/./seastar/src/core/reactor.cc:764
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:783
seastar::internal::cpu_stall_detector::generate_trace() at ./build/release/seastar/./seastar/src/core/reactor.cc:1358
seastar::internal::cpu_stall_detector::maybe_report() at ./build/release/seastar/./seastar/src/core/reactor.cc:1100
 (inlined by) seastar::internal::cpu_stall_detector::on_signal() at ./build/release/seastar/./seastar/src/core/reactor.cc:1117
 (inlined by) seastar::reactor::block_notifier(int) at ./build/release/seastar/./seastar/src/core/reactor.cc:1341
?? ??:0
~lw_shared_ptr at ././seastar/include/seastar/core/shared_ptr.hh:300
 (inlined by) bound_view::tri_compare::operator()(clustering_key_prefix const&, int, clustering_key_prefix const&, int) const at ././clustering_bounds_comparator.hh:85
std::strong_ordering position_in_partition::tri_compare::compare<position_in_partition_view, position_in_partition_view>(position_in_partition_view const&, position_in_partition_view const&) const at ././position_in_partition.hh:473
 (inlined by) position_in_partition::tri_compare::operator()(position_in_partition_view const&, position_in_partition_view const&) const at ././position_in_partition.hh:481
 (inlined by) rows_entry::tri_compare::operator()(rows_entry const&, position_in_partition_view) const at ././mutation_partition.hh:982
 (inlined by) mutation_partition::append_clustered_row(schema const&, position_in_partition_view, seastar::bool_class<dummy_tag>, seastar::bool_class<continuous_tag>) at ./mutation_partition.cc:603
partition_builder::accept_row(position_in_partition_view, row_tombstone const&, row_marker const&, seastar::bool_class<dummy_tag>, seastar::bool_class<continuous_tag>) at ././partition_builder.hh:57
 (inlined by) void mutation_partition_view::do_accept<partition_builder>(column_mapping const&, partition_builder&) const at ./mutation_partition_view.cc:223
frozen_mutation::unfreeze(seastar::lw_shared_ptr<schema const>) const at ./frozen_mutation.cc:105
to_data_query_result(reconcilable_result const&, seastar::lw_shared_ptr<schema const>, query::partition_slice const&, unsigned long, unsigned int, query::result_options) at ./mutation_partition.cc:2077
operator() at ./service/storage_proxy.cc:3700
operator() at ././seastar/include/seastar/core/future.hh:1668
 (inlined by) void seastar::futurize<void>::satisfy_with_result_of<seastar::future<boost::outcome_v2::basic_result<void, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy> >::then_wrapped_nrvo<void, service::abstract_read_executor::reconcile(db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, seastar::lw_shared_ptr<query::read_command>)::{lambda(seastar::future<boost::outcome_v2::basic_result<void, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy> >)#1}>(service::abstract_read_executor::reconcile(db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, seastar::lw_shared_ptr<query::read_command>)::{lambda(seastar::future<boost::outcome_v2::basic_result<void, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy> >)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda(seastar::future<boost::outcome_v2::basic_result<void, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy> >)#1}&, seastar::future_state<boost::outcome_v2::basic_result<void, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy> >&&)#1}::operator()(seastar::internal::promise_base_with_type<void>, seastar::internal::promise_base_with_type<void>&&, seastar::future_state<boost::outcome_v2::basic_result<void, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy> >) const::{lambda()#1}>(seastar::internal::promise_base_with_type<void>, service::abstract_read_executor::reconcile(db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, seastar::lw_shared_ptr<query::read_command>)::{lambda(seastar::future<boost::outcome_v2::basic_result<void, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy> >)#1}&&) at ././seastar/include/seastar/core/future.hh:2117
 (inlined by) operator() at ././seastar/include/seastar/core/future.hh:1667
 (inlined by) seastar::continuation<seastar::internal::promise_base_with_type<void>, service::abstract_read_executor::reconcile(db::consistency_level, std::chrono::time_point<seastar::lowres_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > >, seastar::lw_shared_ptr<query::read_command>)::{lambda(seastar::future<boost::outcome_v2::basic_result<void, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy> >)#1}, seastar::future<boost::outcome_v2::basic_result<void, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy> >::then_wrapped_nrvo<void, {lambda(seastar::future<boost::outcome_v2::basic_result<void, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy> >)#1}>({lambda(seastar::future<boost::outcome_v2::basic_result<void, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy> >)#1}&&)::{lambda(seastar::internal::promise_base_with_type<void>&&, {lambda(seastar::future<boost::outcome_v2::basic_result<void, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy> >)#1}&, seastar::future_state<boost::outcome_v2::basic_result<void, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy> >&&)#1}, boost::outcome_v2::basic_result<void, utils::exception_container<exceptions::mutation_write_timeout_exception, exceptions::read_timeout_exception, exceptions::read_failure_exception>, utils::exception_container_throw_policy> >::run_and_dispose() at ././seastar/include/seastar/core/future.hh:767
seastar::reactor::run_tasks(seastar::reactor::task_queue&) at ./build/release/seastar/./seastar/src/core/reactor.cc:2344
 (inlined by) seastar::reactor::run_some_tasks() at ./build/release/seastar/./seastar/src/core/reactor.cc:2754
seastar::reactor::do_run() at ./build/release/seastar/./seastar/src/core/reactor.cc:2923
operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:4142
 (inlined by) void std::__invoke_impl<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89&>(std::__invoke_other, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:61
 (inlined by) std::enable_if<is_invocable_r_v<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89&>, void>::type std::__invoke_r<void, seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89&>(seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/invoke.h:111
 (inlined by) std::_Function_handler<void (), seastar::smp::configure(seastar::smp_options const&, seastar::reactor_options const&)::$_89>::_M_invoke(std::_Any_data const&) at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:290
std::function<void ()>::operator()() const at /usr/lib/gcc/x86_64-redhat-linux/11/../../../../include/c++/11/bits/std_function.h:590
 (inlined by) seastar::posix_thread::start_routine(void*) at ./build/release/seastar/./seastar/src/core/posix.cc:60
```

**Comment by bhalevy** [comment]
@nyh I can't reproduce any reactor stalls with the tests you pasted above.

**Comment by nyh** [comment]
(un?)fortunately, it seems you are right. I tried one of the tests which used to reproduce this bug, and it didn't show a stall or an oversized allocation. We do get a read timeout, 

> E           botocore.errorfactory.InternalServerError: An error occurred (InternalServerError) when calling the Scan operation (reached max retries: 0): Internal server error: exceptions::read_timeout_exception (Operation timed out for alternator_alternator_Test_1648745315097.alternator_Test_1648745315097 - received only 0 responses from 1 CL=LOCAL_ONE.)

But that is #7933, not this issue. It seems that somehow we did something to the read code which avoids contiguous allocations while scanning a huge contiguous list of tombstones, and also avoids stalls in this case. I wonder if @denesb or somebody knows what we did in this area (the v2 readers?) that fixed this bug.

I'll think I'll close this issue. Similar tests will be useful for reproducing #7933, but apparently this one can no longer be reproduced.

**Comment by nyh** [comment]
>  It seems that somehow we did something to the read code which avoids contiguous allocations while scanning a huge contiguous list of tombstones, and also avoids stalls in this case. I wonder if @denesb or somebody knows what we did in this area (the v2 readers?) that fixed this bug.

I'm guessing this was fixed by @tgrabiec in commits d039db4bf0714359f29e83c6a27da98dc7054f49 and 36daf43562bb96e044ba3d70edd2c7774c260064

**Comment by nyh** [comment]
Ooops, @tgrabiec it seems that neither of those commits I just mentioned were actually merged! They are part of https://github.com/scylladb/scylla/pull/9223 which was never committed...
So I don't understand how the reactor stall and oversized allocations disappeared. Tomek, are your patches still relevant? Maybe something else already fixed the same problems?

**Comment by tgrabiec** [comment]
If you are getting timeouts then coordinator-side processing does not happen and thus the stalls mentioned in this issue do not happen (they happen during deserialization of query results). Maybe replica-side processing got slower.

**Comment by nyh** [comment]
> If you are getting timeouts then coordinator-side processing does not happen

Why is this the case? I thought (but perhaps I was wrong) that the coordinator needs to fetch from the replica the entire mutation - including the tombstones - and only after fetching those can return the small reponse (without those tombstones) - so we can definitely get a timeout on the client side if the coordinator keeps fetching more and more of these tombstones and it takes too much time. In any case, I only get these timeouts if the request is "huge" enough (e.g., also contains a lot of data which needs to be read from disk) - and that may be the "slower" case you mentioned. But I still don't understand why we no longer get the problems that you wrote a patch to fix.

> and thus the stalls mentioned in this issue do not happen (they happen during deserialization of query results). Maybe replica-side processing got slower.

In any case, if you want to revive your PR which was supposed to fix (or at least partially fix) this issue, please try to build a test case which reproduces the issue it's supposed to fix. As @bhalevy noted, while in the past I was able to see these problems with the tests given here, I no longer can, and I tried a lot of variants of them with different number of tombstones and different item sizes, sstable flushes, and other settings - and couldn't reproduce neither stalls nor oversize allocations.

**Comment by tgrabiec** [comment]
> Why is this the case? I thought (but perhaps I was wrong) that the coordinator needs to fetch from the replica the entire mutation - including the tombstones - and only after fetching those can return the small reponse (without those tombstones) - so we can definitely get a timeout on the client side if the coordinator keeps fetching more and more of these tombstones and it takes too much time. In any case, I only get these timeouts if the request is "huge" enough (e.g., also contains a lot of data which needs to be read from disk) - and that may be the "slower" case you mentioned. But I still don't understand why we no longer get the problems that you wrote a patch to fix.

Yes, coordinator fetches from the replica the entire mutation with all the tombstones. If that times-out, coordinator-side logic which stalls will not be executed. That's why you don't see stalls. Maybe results are not served from cache any more, for example.
