### ISSUE TITLE
aggregated metric reactor.gauge-load have no data

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#793]
Monitoring a relatively large machine, 40 CPUs, there are no metrics of  scylla.reactor.gauge-load , although each scylla.reactor-0.gauge-load, scylla.reactor-1.gauge-load,... do have data.

The same goes for other aggregated metrics.

**Comment by tzach** [comment]
On a second look, it might do sent metrics, but there are all zero, or very close to it

**Comment by tgrabiec** [comment]
@tzach `scylla.reactor.gauge-load` is an aggregated metric generated in riemann as an average of the loads of all shards. If most shards are idle, they'll driver the average down.

**Comment by tzach** [comment]
@tgrabiec I did not know it is generated in riemann.
What I seen in Graphite is all shards are busy, but all aggregations are empty.
Maybe riemann do not generate the aggregations from some resone?

**Comment by tzach** [comment]
This a monitoring problem, not Scylla
Move the issue to https://github.com/scylladb/scylla-monitoring/issues/11
