### ISSUE TITLE
`multishard_combining_reader` uses `smp::count` in one place instead of `_sharder.shard_count()`

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#7945]
`multishard_combining_reader` currently only works under the assumption that every table uses the same sharder configured using the node's number of shards. But we could potentially specify a different sharder for a chosen table, e.g. one that puts everything on shard 0. Then this assumption will be broken and the reader causes a segfault. The fix should be easy - simply replace that one use of `smp::count` with `_sharder.shard_count()`.

**Comment by avikivity** [comment]
This only bites if we use non-default sharding (e.g. with bf115e7d69b12f4ed4f208646b3eb9c02c966ec2). Since no branch has that, no need for backport.
