### ISSUE TITLE
test_dates_type_group: Expected [[UUID('00001e98-5de7-11eb-9652-0000600cd32c')]] from select min(my_timeuuid) from all_types, but got [[UUID('fe87aeba-5de6-11eb-befe-0000600cd329')]]

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7956]
I'm opening this issue against scylla, although it might be a dtest issue, but let's rule out a bug in the new timeuuid code first.

Seen in https://jenkins.scylladb.com/job/scylla-master/job/dtest-release/725/testReport/cql_group_functions_tests/TestGroupFunctions/test_dates_type_group/
Scylla version cb9e2ee00a176064cc4458df9aa0312359697e2f
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cql_group_functions_tests.py", line 107, in test_dates_type_group
    single_type=single_type)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cql_group_functions_tests.py", line 74, in create_tables_and_run_group_functions
    self.check_results(session=session, table_name=table_name, single_type=single_type)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cql_group_functions_tests.py", line 48, in check_results
    cl=ConsistencyLevel.QUORUM)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/dtest.py", line 1643, in inner
    return func(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/assertions.py", line 68, in assert_one
    assert list_res == [expected], "Expected %s from %s, but got %s" % ([expected], query, list_res)
AssertionError: Expected [[UUID('00001e98-5de7-11eb-9652-0000600cd32c')]] from select min(my_timeuuid) from all_types, but got [[UUID('fe87aeba-5de6-11eb-befe-0000600cd329')]]
```

I tried to reproduce locally but this isn't readily reproducible.
You may want to run the test in a loop until it fails.

**Comment by kostja** [comment]
Not reproducible in dev build:
```
kostja@hulk:~/work/scylla/dtest$ KEEP_TEST_DIR=true REUSE_CLUSTER=false  nosetests    -v -s cql_group_functions_tests.py:TestGroupFunctions.test_dates_type_group cql_group_functions_tests.py:TestGroupFunctions.test_dates_type_group cql_group_functions_tests.py:TestGroupFunctions.test_dates_type_group cql_group_functions_tests.py:TestGroupFunctions.test_dates_type_group cql_group_functions_tests.py:TestGroupFunctions.test_dates_type_group cql_group_functions_tests.py:TestGroupFunctions.test_dates_type_group
test_dates_type_group (cql_group_functions_tests.TestGroupFunctions) ... ok
test_dates_type_group (cql_group_functions_tests.TestGroupFunctions) ... ok
test_dates_type_group (cql_group_functions_tests.TestGroupFunctions) ... ok
test_dates_type_group (cql_group_functions_tests.TestGroupFunctions) ... ok
test_dates_type_group (cql_group_functions_tests.TestGroupFunctions) ... ok
test_dates_type_group (cql_group_functions_tests.TestGroupFunctions) ... ok

----------------------------------------------------------------------
Ran 6 tests in 1320.045s

OK
```

**Comment by kostja** [comment]
Release build:
```
kostja@hulk:~/work/scylla/dtest$ KEEP_TEST_DIR=true REUSE_CLUSTER=false  nosetests    -v -s cql_group_functions_tests.py:TestGroupFunctions.test_dates_type_group cql_group_functions_tests.py:TestGroupFunctions.test_dates_type_group cql_group_functions_tests.py:TestGroupFunctions.test_dates_type_group cql_group_functions_tests.py:TestGroupFunctions.test_dates_type_group cql_group_functions_tests.py:TestGroupFunctions.test_dates_type_group cql_group_functions_tests.py:TestGroupFunctions.test_dates_type_group
test_dates_type_group (cql_group_functions_tests.TestGroupFunctions) ... ok
test_dates_type_group (cql_group_functions_tests.TestGroupFunctions) ... ok
test_dates_type_group (cql_group_functions_tests.TestGroupFunctions) ... ok
test_dates_type_group (cql_group_functions_tests.TestGroupFunctions) ... ok
test_dates_type_group (cql_group_functions_tests.TestGroupFunctions) ... ok
test_dates_type_group (cql_group_functions_tests.TestGroupFunctions) ... ok

----------------------------------------------------------------------
Ran 6 tests in 919.927s

OK
```

**Comment by kostja** [comment]
The failure could be timing specific. 
Do we have a saved data directory for this failure? 

The test is running a timeuuid sort inside Python and then compares the results with a sorted output performed by Scylla.
CQL sort order does not have to match Python sort order for lower bits of UUID. We will be able to check if the test is impacted by this when we grab the data directory.

**Comment by kostja** [comment]
@bhalevy ^^

**Comment by bhalevy** [comment]
> The failure could be timing specific.
> Do we have a saved data directory for this failure?

Unfortunately we don't save the data directories on dtest failures, just the log.

> The test is running a timeuuid sort inside Python and then compares the results with a sorted output performed by Scylla.
> CQL sort order does not have to match Python sort order for lower bits of UUID. We will be able to check if the test is impacted by this when we grab the data directory.

Can you run an experiment to check the compatibility?
Maybe even develop a quick dtest that will use injected timeuuid's as clustering keys and verify their order compared to the test's ordering.

Maybe we need to use some pytohn library like https://pypi.org/project/time-uuid/ for compatibility, or write our own code if needed.

**Comment by kostja** [comment]
I know the sort order is not compatible: https://stackoverflow.com/questions/59630690/differences-for-max-time-uuid-in-cqlsh-and-python-cassandra-driver - but as you can see, it's only for lower bits, so in order for that to happen there must be a timestamp collision.y It would be nice to verify that the collision is indeed present, and hence the lower timeuuid bits are taken into account.
If we can't do it, we should fix the test to use the correct comparator, and print out the entire table in case of comparison failure.
@fgelcer is the author of the original test.

**Comment by bhalevy** [comment]
Seen again in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/730/testReport/cql_group_functions_tests/TestGroupFunctions/test_dates_type_group/
```
Expected [[UUID('00002522-6200-11eb-a375-00006013b31a')]] from select min(my_timeuuid) from all_types, but got [[UUID('faa5b3fe-61ff-11eb-ae5e-00006013b311')]]
```

**Comment by kostja** [comment]
UUID('00001e98-5de7-11eb-9652-0000600cd32c') is 2021-01-24T01:53:48.376Z[UTC], Raw UUID Timestamp: 138307460283768480

UUID('fe87aeba-5de6-11eb-befe-0000600cd329') is 2021-01-24T01:53:45.909Z[UTC], Raw UUID Timestamp: 138307460259098300

MIN function in Scylla returns a smaller UUID.

**Comment by kostja** [comment]
>>> uuid.UUID('00001e98-5de7-11eb-9652-0000600cd32c') < uuid.UUID('fe87aeba-5de6-11eb-befe-0000600cd329')
True
>>> uuid.UUID('00001e98-5de7-11eb-9652-0000600cd32c').time < uuid.UUID('fe87aeba-5de6-11eb-befe-0000600cd329').time
False
>>> uuid.UUID('00001e98-5de7-11eb-9652-0000600cd32c').time
138307460283768472L
>>> uuid.UUID('fe87aeba-5de6-11eb-befe-0000600cd329').time
138307460259098298L

**Comment by kostja** [comment]
The test is using tools.py for UUID value generation, which uses time.time() (float number of seconds) and narrows it down to an int and then passes to uuid1() as a node identifier. The expectation is perhaps that the UUID will be based on the given time, but first, this is too coarse, and second, the value is actually taken as node, not as the current time.
kostja@hulk:~/work/scylla/dtest$ git diff tools.py
diff --git a/tools.py b/tools.py
index 5a58aa2c..43f766ba 100644
--- a/tools.py
+++ b/tools.py
@@ -563,7 +563,7 @@ class ColumnType:
         elif data_type.lower() == 'timestamp':
             value = int(time.time())
         elif data_type.lower() == 'timeuuid':
-            value = uuid1(int(time.time()))
+            value = uuid1()
         elif data_type.lower() in ['decimal', 'double', 'float']:
             value = self.gen_random_decimal_number(length=random.randint(2, 15))
         elif data_type.lower() == 'inet':

**Comment by kostja** [comment]
```
>>> uuid.UUID('00001e98-5de7-11eb-9652-0000600cd32c') < uuid.UUID('fe87aeba-5de6-11eb-befe-0000600cd329')
True
>>> time_uuid.TimeUUID('00001e98-5de7-11eb-9652-0000600cd32c') < time_uuid.TimeUUID('fe87aeba-5de6-11eb-befe-0000600cd329')
False
```

**Comment by kostja** [comment]
https://github.com/kostja/scylla-dtest/tree/kostja/gh-7956

**Comment by bhalevy** [comment]
> https://github.com/kostja/scylla-dtest/tree/kostja/gh-7956

Did you open a PR?

**Comment by kostja** [comment]
https://github.com/scylladb/scylla-dtest/pull/1931

**Comment by bhalevy** [comment]
@kostja unfortunately it looks like scylladb/scylla-dtest#1931 did not fix the issue.
See https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug-random/lastFailedBuild/testReport/cql_group_functions_tests/TestGroupFunctions/test_dates_type_group/
Running with scylladb/scylla-dtest@d1041a56cfcf49d7ae29d10546315ddf4044df6c
That includes scylladb/scylla-dtest@5ab6600f53a53a64436fdb89012d89739de99352
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/cql_group_functions_tests.py", line 110, in test_dates_type_group
    single_type=single_type)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/cql_group_functions_tests.py", line 77, in create_tables_and_run_group_functions
    self.check_results(session=session, table_name=table_name, single_type=single_type)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/cql_group_functions_tests.py", line 51, in check_results
    cl=ConsistencyLevel.QUORUM)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/dtest.py", line 1643, in inner
    return func(*args, **kwargs)
  File "/jenkins/workspace/scylla-master/dtest-debug-random/scylla-dtest/assertions.py", line 68, in assert_one
    assert list_res == [expected], "Expected %s from %s, but got %s" % ([expected], query, list_res)
AssertionError: Expected [[TimeUUID('000218d8-77c6-11eb-a1e5-0242ac110002')]] from select min(my_timeuuid) from all_types, but got [[UUID('9aad8274-77c5-11eb-a1e5-0242ac110002')]]
```

**Comment by bhalevy** [comment]
Note the AssertError expected TimeUUID, but got UUID
why is min(my_timeuuid) results with a UUID?
Is this a problem on Scylla's side or on the test side?

Cc @fgelcer

**Comment by bhalevy** [comment]
Hit again in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/780/testReport/cql_group_functions_tests/TestGroupFunctions/test_dates_type_group/
Scylla version 6a2377a233b6708598777bfb11a18afcab27c1e6

**Comment by kostja** [comment]
000218d8-77c6-11eb-a1e5-0242ac110002 is 2021-02-26 00:03:05.229948.0 UTC
9aad8274-77c5-11eb-a1e5-0242ac110002 is 2021-02-26 00:00:15.225714.0 UTC

The database is right, the test is wrong, again.

**Comment by kostja** [comment]
```
kostja@hulk:~$ python2
Python 2.7.18 (default, Mar  8 2021, 13:02:45) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import time_uuid
>>> time_uuid.TimeUUID('00001e98-5de7-11eb-9652-0000600cd32c') < time_uuid.TimeUUID('fe87aeba-5de6-11eb-befe-0000600cd329')
False
>>> 
kostja@hulk:~$ python3
Python 3.8.6 (default, Oct  9 2020, 11:59:16) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import time_uuid
>>> time_uuid.TimeUUID('00001e98-5de7-11eb-9652-0000600cd32c') < time_uuid.TimeUUID('fe87aeba-5de6-11eb-befe-0000600cd329')
True
```

**Comment by kostja** [comment]
Python `time_uuid` library is abandoned. There is a pull request to make it work in Python3 open for 3 years: https://github.com/samuraisam/time_uuid/pull/2

**Comment by bhalevy** [comment]
> Python `time_uuid` library is abandoned. There is a pull request to make it work in Python3 open for 3 years: [samuraisam/time_uuid#2](https://github.com/samuraisam/time_uuid/pull/2)

How hard would it be to write our own code to process the timeuuid.
It'd be better to verify our implementation against a trusted one, but until we find a trust python implementation we may need to write our own.

**Comment by fgelcer** [comment]
probably and hopefully will be fixed by https://github.com/scylladb/scylla-dtest/pull/2089

**Comment by bhalevy** [comment]
Closing.  Please open a new issue if seen again
