### ISSUE TITLE
row_cache_test: test_eviction_from_invalidated may fail on bad_alloc

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#7959]
Seen in https://jenkins.scylladb.com/job/scylla-master/job/next/3094/artifact/testlog/dev/row_cache_test.312.log
Not much info there but maybe it could be reproduced with the printed seeds
```
random-seed=2599816874
...
test/boost/row_cache_test.cc(0): Entering test case "test_eviction_from_invalidated"
random_mutation_generator seed: 1578196465
unknown location(0): fatal error: in "test_eviction_from_invalidated": std::bad_alloc: std::bad_alloc
./seastar/src/testing/seastar_test.cc(43): last checkpoint
test/boost/row_cache_test.cc(0): Leaving test case "test_eviction_from_invalidated"; testing time: 80463690us
```

**Comment by bhalevy** [comment]
@xemul please look into this

**Comment by xemul** [comment]
On 9038a81317 reproduces with `./build/dev/test/boost/row_cache_test -t test_eviction_from_invalidated -- -m512M -c1 --random-seed 3190990723`

**Comment by xemul** [comment]
Funny. The test tries to allocate `10*segment_size` chunks of memory in a loop doing this while region total space is greater than this value. When the badalloc fires the region had evicted all rows (the `tracker.get_stats().rows == 0`), but the region occupancy is non-zero (~400 bytes), so the last segment cannot be reclaimed, and the (last) test chunk doesn't fit. Thus bad_alloc.

**Comment by xemul** [comment]
Dumping of all objects from all segments shows: region occupancy used_space is 384 bytes, 1 object of 288 bytes (it matches `bptree::node` size, bptree is used to keep partitions in), 1 object of 80 bytes (matches `bptree::data` size). "Missing" 16 bytes -- 2 descriptors 8 bytes each (alignment for both bptree structures is 8 bytes).

**Comment by xemul** [comment]
OK, so there's an empty partition left after invalidate(). And it doesn't get evicted, because partition is only evicted ... together with its last row.

**Comment by bhalevy** [comment]
@xemul see cb0b8d190357b0792217680918ae7beab9ed8167

**Comment by xemul** [comment]
@bhalevy , this patch removes dummy row entries, in my case there's a dummy cache entry (~ a partition) stuck in the region.

**Comment by bhalevy** [comment]
right, I just mentioned it to give you ideas about how to get rid of it (at the right time :)

**Comment by bhalevy** [comment]
Seen also in https://jenkins.scylladb.com/view/scylla-4.3/job/scylla-4.3/job/next/173/artifact/testlog/dev/row_cache_test.309.log

@scylla-maint please consider backport

**Comment by avikivity** [comment]
Backported to 4.3. 4.4, 4.5 had it already.
