### ISSUE TITLE
Data may be resurrected after truncate was acked

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#797]
Looking at current implementation it seems possible that data removed by an ACKed truncate statement could get resurrected after a node crash.

`database::truncate()` calls `column_family::discard_sstables()` which calls `sstable::mark_for_deletion`. The last one only marks the sstable as free to go away, but the sstable is actually removed once it is no longer used on any shard. An active query may keep the sstable used and thus preventing its deletion for a long period of time. We should probably interrupt all sstable users to stop using them and wait for them.

**Comment by elcallio** [comment]
See also #884

**Comment by elcallio** [comment]
I'm not sure this is a problem (at least not in the truncation implementation, at least not once #884 is fixed). 

The only real uses of sstables (afaict) are the column family itself, and the compaction. Truncation is run "with compaction disabled", which is at least supposed to end any on-going compaction before actually processing, so we should not be sharing with it. This leaves other shards. 
Now:

- sstables created during the instance life time are never shared across shards, so that should not be an issue. 
- sstables loaded from disk might be shared, but these should always have a load time < truncation time, so they should be guaranteed to be marked + removed from sstable list for all shard CF:s. 

Now, of course if we crash before destructors are run, we have an issue. Thus also, if there are any other mechanisms grabbing a table (stream, whatnot), then the problem might arise again. (I guess I'm saying clean shutdown would be nice). 

Could we not simply unlink the actual files on first "mark_for_deletion", and just rely on existing file handles? Or does the sstable read more than the index+data after opening?

**Comment by tgrabiec** [comment]
@elcallio In general, `mark_for_deletion()` cannot remove a shared sstable until all shards agree it should go away, it might not have been yet compacted by those shards. But if we're sure that all data in given sstable is no longer needed by any shard, like you say should be the case for truncation, we could have a separate method for marking for deletion with immediate effect but without affecting existing readers. There is already a mechanism for marking an sstable in a way which would cause it to be removed on next boot but allowing all components but TOC to still exist on disk and thus be accessed by readers. It is done by renaming the TOC file to a "temporary" TOC file, see `remove_by_toc_name()`.

**Comment by slivne** [comment]
What happens with inflight compaction / inflight repairs - when truncation
is requested ?

**Comment by elcallio** [comment]
run_with_compaction_disabled removes the CF from compaction before proceeding, so any compaction of the affected sstables should be aborted. 
Repairs, I don't know...

**Comment by slivne** [comment]
lets write two tests for this for compaction-truncate, repair-truncate and see that it works as expected

**Comment by avikivity** [comment]
@tgrabiec since truncate should be `invoke_on_all()`d then each shard's sstables ought to be `mark_for_deletion()`ed individually, no?  I don't think we need/can force deletion.

**Comment by benoit-canet** [comment]
@slivne: What do you expect from me ? Write the two test ? Fix the issue ? or Both ?

**Comment by tgrabiec** [comment]
2016-02-18 11:59 GMT+01:00 Avi Kivity <notifications@github.com>:

> @tgrabiec <https://github.com/tgrabiec> since truncate should be
> invoke_on_all()d then each shard's sstables ought to be
> mark_for_deletion()ed individually, no? I don't think we need/can force
> deletion.
>
@avikivity Do we agree that it is an error for data removed by an ACKed
truncate statement to get resurrected at some point later? It would at
least violate read monotonicity.

Current mechanism, which only marks sstables for deletion, with actual
deletion happening possibly much later, doesn't provide this in case of a
crash. Correctness of truncate relies on the fact that those sstables will
not be queryable from now on. By unlinking them from the data source list
we ensure that for the current process, but if the process crashes before
the files on disk are actually deleted, they will become available for
reads again when we restart.

I think we don't need to delete those sstables immediately, just mark them
so that they are removed on next boot, for instance by renaming TOC to a
temporary TOC.

**Comment by avikivity** [comment]
@tgrabiec agree on problem and solution.  Renaming the TOC is a persistent way to mark an sstable for deletion.

**Comment by slivne** [comment]
I admit I am not following all - no one will do a restart in real systems,
will this sstables be removed prior to restart - or only on next restart -
no one restarts servers for weeks (or at least this is our goal)  it will
take up disk space - if it waits for next restart

**Comment by avikivity** [comment]
We can have involuntary restarts on crashes.

**Comment by tgrabiec** [comment]
2016-03-16 9:46 GMT+01:00 slivne <notifications@github.com>:

> I admit I am not following all - no one will do a restart in real systems,
> will this sstables be removed prior to restart - or only on next restart -
> no one restarts servers for weeks (or at least this is our goal) it will
> take up disk space - if it waits for next restart
>

@shlomi Those sstables will be removed as soon as they are no longer used
on all shards. The issue is about dealing with crashes which may happen
before that.

**Comment by slivne** [comment]
Ok thanks ....

So I'll reassin this.

**Comment by penberg** [comment]
There are patches on the mailing list but we are still waiting for review from @nyh, @raphaelsc, @glommer.
