### ISSUE TITLE
scylla_setup  IOTune fail

### ISSUE THREAD

**Issue by shawn-cheng** [scylladb/scylla#7971]
env: n1-standard-4 (4 vCPUs, 15 GB memory) 
os:Ubuntu 18.04 lts
scylla version 4.3(latest)  

Do you want IOTune to study your disks IO profile and adapt Scylla to it? (*WARNING* Saying NO here means the node will not boot in production mode unless you configure the I/O Subsystem manually!)
Yes - let iotune study my disk(s). Note that this action will take a few minutes. No - skip this step.
[YES/no]y
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_io_setup", line 239, in <module>
    if idata.is_recommended_instance():
  File "/opt/scylladb/scripts/scylla_util.py", line 311, in is_recommended_instance
    diskSize = self.firstNvmeSize
  File "/opt/scylladb/scripts/scylla_util.py", line 291, in firstNvmeSize
    firstDisk = ephemeral_disks[0]
IndexError: list index out of range
IO configuration setup failed. Press any key to continue...

**Comment by slivne** [comment]
- If you are running on a cloud machine can you please share the cloud and
the instance you are using

- If you are running outside of a cloud can you please share the HW specs -
you can try and use (
http://docs.scylladb.com/troubleshooting/report_scylla_problem/#health-check-report
although it tried to collect info from scylla as well - and we arenot
there, nbut it should be able to collect the HW / OS info needed)

**Comment by shawn-cheng** [comment]
I did create the instance on google cloud but I cant share the instance. I have upload the file and the uuid is
06285a54-52b0-4e56-8e4d-09ff49fb0e64

**Comment by shawn-cheng** [comment]
I tried to install different OS in GCP instance. CentsOS7 & Debian 10 & Ubuntu 18.04 all thees have the same issue when I try to execute the scylla_setup. And it's only work if I bypass the check.

**Comment by slivne** [comment]
@shawn-cheng -= benny sent a patch - yet you need to use local ssds to get good performance. Using network drives (which includes the root disk) for storing scylla data may provide bad performance (if I recall correctly - some use a large cache that is not flushed on every fsynch) 

please follow the instructions https://www.scylladb.com/download/?platform=gcp

**Comment by godsey** [comment]
Scylla should not force users to use ephemeral vs network block device storage in GCP.

**Comment by slivne** [comment]
I totally agree - and we will fix the bug - benny's patch was merged and will be rolled out to releases.

Having said that expecting great performance from resources that can't provide that is as expected impossible.

**Comment by avikivity** [comment]
Backported to 4.3, 4.4. GCP support didn't exist in 4.2.
