### ISSUE TITLE
Timeouts during read operations may contribute to high number of background reads

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#7981]
This issue is part of the discussion on unbounded background reads.

This issue's root cause would have to be confirmed, but it sounds likely - @gleb-cloudius suggested it via the mailing list. It was observed during an overload test, that even though speculative retry and probabilistic repair were turned off, a considerable number of background reads still appeared in the system.
The reason might be that once a request goes past its timeout, an error is returned to the client, but a local replica-side read operation still goes on, because we don't have a mechanism for aborting local reads. That in turn occupies resources and contributes to the overloaded state of the cluster.

Ref https://github.com/scylladb/scylla/issues/7978 https://github.com/scylladb/scylla/issues/7979

**Comment by eliransin** [comment]
It looks like we have a reproducer and we can actually work on this :slightly_smiling_face:

**Comment by eliransin** [comment]
This seastar commit can probably be part of the solution - the issue it solves is scylladb/seastar#811:
https://github.com/scylladb/seastar/commit/4b5cc0ee340b014764ec16bcae310689ecc44f9a

**Comment by slivne** [comment]
@bhalevy AFAIK you are working on the last part - having the closed readers actually doing the cancellation.

**Comment by bhalevy** [comment]
@psarna duplicate of https://github.com/scylladb/scylla/issues/2927 ?

**Comment by psarna** [comment]
@bhalevy looks like it. I'll close this one and add the `overload` label to #2927
