### ISSUE TITLE
Compact mutation fragment stream when flushing memtables

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#7983]
It can be that most of the data in memtable is covered by range tombstones. Writing rows which are covered by tombstones wastes resources and adds more work for compaction later. We should insert a compacting reader after the flush reader in the reader pipeline.

This matters for RAFT where log is frequently truncated by deleting a range of rows.

**Comment by bhalevy** [comment]
Can be closed with a88f7df1952eabfb436a7424410d6ad8e5e91091

**Comment by bhalevy** [comment]
No backport needed
