### ISSUE TITLE
Interactive version of scylla_raid_setup

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#799]
scylla_raid_setup, or a script running it, should look for available driver, and prompt the user to choose the relevant driver interactively. Running is silent mode, as it is now, should also be available.

scylla_raid_setup can be later a part of a larger, interactive setup script.

**Comment by syuu1228** [comment]
interactive scylla_setup have been merged, so this can close.

**Comment by slivne** [comment]
commit 2d429e602a4ee0b11c8990ce7d52c3856154c397
Author: Takuya ASADA <syuu@scylladb.com>
Date:   Tue Feb 16 04:23:10 2016 +0900

    dist: interactive scylla_setup
    
    Signed-off-by: Takuya ASADA <syuu@scylladb.com>
