### ISSUE TITLE
interactive version of posix_net_conf.sh

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#800]
posix_net_conf or a script running it, should look for available interfaces, and prompt the user to choose the relevant interface interactively. Running is silent mode, as it is now, should also be available.

posix_net_conf can be later a part of a larger, interactive setup script.

**Comment by dorlaor** [comment]
Tzach, please provide more details about what you see as interactive and
how it should look like.

It's mainly about the NIC device choice in this case.

**Comment by tzach** [comment]
> Tzach, please provide more details about what you see as interactive and
how it should look like.

My suggestion below
```
# Network Setup 
# This setup step improve scylla performance by binding NIC IRQ to cores, banning NIC IRQs from being moved by irqbalance.
# The following interface are available on your server: (0) eth0 (1) eth1, ...
# which interface do you want to bind? 
# insert interface number, "m" to distribute NIC's IRQs among all CPUs, or X to skip this step
interface(default 0)> 0
# binding to eth0
```

**Comment by syuu1228** [comment]
interactive scylla_setup have been merged, so this can close.

**Comment by slivne** [comment]
commit 2d429e602a4ee0b11c8990ce7d52c3856154c397
Author: Takuya ASADA <syuu@scylladb.com>
Date:   Tue Feb 16 04:23:10 2016 +0900

    dist: interactive scylla_setup
    
    Signed-off-by: Takuya ASADA <syuu@scylladb.com>
