### ISSUE TITLE
Scylla Startup fails: perftune.py: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by ShlomiBalalis** [scylladb/scylla#8008]
*Installation details*
Scylla version (or git commit hash):4.5.dev-0.20210131.bb202db1f
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): Spread across the board between centos, ubuntu, debian 
, oel and amazon2 insallations

Most artifact tests fail during scylla installations with the following error when attempting to start scylla server:
```
Jan 31 23:42:31 artifacts-centos7-jenkins-db-node-0b6c855d-0-1 systemd[1]: Starting Scylla Server...
Jan 31 23:42:32 artifacts-centos7-jenkins-db-node-0b6c855d-0-1 scylla_prepare[4166]: Traceback (most recent call last):
Jan 31 23:42:32 artifacts-centos7-jenkins-db-node-0b6c855d-0-1 scylla_prepare[4166]: File "/opt/scylladb/scripts/libexec/perftune.py", line 1389, in <module>
Jan 31 23:42:32 artifacts-centos7-jenkins-db-node-0b6c855d-0-1 scylla_prepare[4166]: parse_options_file(args)
Jan 31 23:42:32 artifacts-centos7-jenkins-db-node-0b6c855d-0-1 scylla_prepare[4166]: File "/opt/scylladb/scripts/libexec/perftune.py", line 1334, in parse_options_file
Jan 31 23:42:32 artifacts-centos7-jenkins-db-node-0b6c855d-0-1 scylla_prepare[4166]: prog_args.nics = extend_and_unique(prog_args.nics, y['nic'])
Jan 31 23:42:32 artifacts-centos7-jenkins-db-node-0b6c855d-0-1 scylla_prepare[4166]: File "/opt/scylladb/scripts/libexec/perftune.py", line 1312, in extend_and_unique
Jan 31 23:42:32 artifacts-centos7-jenkins-db-node-0b6c855d-0-1 scylla_prepare[4166]: return list(set(orig_list))
Jan 31 23:42:32 artifacts-centos7-jenkins-db-node-0b6c855d-0-1 scylla_prepare[4166]: TypeError: 'NoneType' object is not iterable
Jan 31 23:42:32 artifacts-centos7-jenkins-db-node-0b6c855d-0-1 scylla_prepare[4166]: Exception occurred while creating perftune.yaml: Command '/opt/scylladb/scripts/perftune.py --tune disks --dir /var/lib/scylla/data --dir /var/lib/scylla/commitlog --dir /var/lib/scylla/hints --dir /var/lib/scylla/view_hints --options-file /etc/scylla.d/perftune.yaml' returned non-zero exit status 1.
Jan 31 23:42:32 artifacts-centos7-jenkins-db-node-0b6c855d-0-1 scylla_prepare[4166]: To fix the error, please re-run scylla_setup.
Jan 31 23:42:32 artifacts-centos7-jenkins-db-node-0b6c855d-0-1 systemd[1]: scylla-server.service: control process exited, code=exited status=1
```

The following artifact installations fail:
artifacts-centos7
artifacts-centos8
artifacts-debian9
artifacts-debian10
artifacts-ubuntu1604
artifacts-ubuntu1804
artifacts-ubuntu20.04
artifacts-oel76
artifacts-amazon2

Root offline installations:
artifact-centos7
artifact-centos8
artifact-debian10
artifact-ubuntu1804

It seems that nonroot offline installations, the docker and gce installations were not effected by this error.

Logs of centos 8 job:
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/92772101-58c2-4592-bf65-4e3a1eb800c3/20210131_234159/db-cluster-92772101.zip
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/92772101-58c2-4592-bf65-4e3a1eb800c3/20210131_234159/sct-runner-92772101.zip

**Comment by penberg** [comment]
@amoskong @tarzanek @dkropachev This breakage looks to be related to https://github.com/scylladb/seastar/pull/861, right?

**Comment by haaawk** [comment]
I find the "Scylla Startup fails ..." title a little disturbing. I hope this is not a prophecy ;)

**Comment by amoskong** [comment]
> @amoskong @tarzanek @dkropachev This breakage looks to be related to [scylladb/seastar#861](https://github.com/scylladb/seastar/pull/861), right?

Sorry, it's caused by https://github.com/scylladb/seastar/pull/854
I had posted a fix: https://github.com/scylladb/seastar/pull/863
