### ISSUE TITLE
meta setup script: scylla_setup_env.sh

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#801]
Set up a Scylla env currently require running a few steps beyond packages installation
```
/usr/lib/scylla/scylla_raid_setup -d /dev/sdb,/dev/sdc -u
/usr/lib/scylla/posix_net_conf.sh -mq
/usr/lib/scylla/scylla_ntp_setup
/usr/lib/scylla/scylla_bootparam_setup
/usr/lib/scylla/scylla_coredump_setup
```

A much improve process will be to bundle all of them in scylla_setup_env
Setup script should:
- run interactively, or slightly
- each script gives relevant info on what it is doing, prompt for relevant info
- can be safely run again with no affect

Example:
```
./script scylla_setup_env.sh
## Running Scylla environment setup script.
# Step 1: setup raid
# The following drives ware found on your machine:
# (1) /dev/hda, (2) /dev/hdb... 
# which drives do you want to install raid on (X to skip this step)
1,2
# installing raid0 on /dev/hda, /dev/hdb... 
# raid installation done 
# Step 2: setup network
....
```
See #800 and #799 for more on each step.

**Comment by syuu1228** [comment]
No it's not, we have /usr/lib/scylla/scylla_setup. It does everything slightly.
And it able to specify disks, NIC.
see: /usr/lib/scylla/scylla_setup -h

If we want interactive one, sure we need to implement it.

**Comment by syuu1228** [comment]
To making interactive interface based on scylla_setup, I think we can start asking disks and NIC.
Then maybe we can ask to launch each command (scylla_ntp_setup, scylla_bootparam_setop, scylla_raid_setup, scylla_coredump_setup).
Does it make sense?

**Comment by dorlaor** [comment]
It makes sense. Basically you can split the interactive part from the
actual logic.
The interactive part should prompt the user for data, for example, it can
suggest
the user a list of relevant disk and the user will pick from it.

After the data was collected, the standard machine script will run with the
data from above.
scylla_setup looks reasonable.  Worth even to simplify it further (to hide
AMI and other
details)

**Comment by dorlaor** [comment]
GCE has very clear and good example of an interactive script which is just great:
curl https://sdk.cloud.google.com | bash

**Comment by syuu1228** [comment]
interactive scylla_setup have been merged, so this can close.

**Comment by slivne** [comment]
commit 2d429e602a4ee0b11c8990ce7d52c3856154c397
Author: Takuya ASADA <syuu@scylladb.com>
Date:   Tue Feb 16 04:23:10 2016 +0900

    dist: interactive scylla_setup
    
    Signed-off-by: Takuya ASADA <syuu@scylladb.com>
