### ISSUE TITLE
scylla_setup "unwanted node exporter setup failed"

### ISSUE THREAD

**Issue by pveentjer** [scylladb/scylla#8017]
When the scylla_setup is run a second time and one agrees to install the node exporter again, then the following message is shown:

```
Yes - install node exporter. No - skip this  step.
[YES/no]y
node_exporter already installed, you can use `--force` to force reinstallation
node exporter setup failed. Press any key to continue...

Do you want to set the CPU scaling governor to Performance level on boot?
Yes - sets the CPU scaling governor to performance level. No - skip this step.
[YES/no]
```
It would be better if the script would detect that the node exporter is installed and then skip the installation and give the appropriate message. So something like:
```
Yes - install node exporter. No - skip this  step.
[YES/no]y
node_exporter already installed, you can use `--force` to force reinstallation
Press any key to continue...
```

Currently it initially looks like something went very wrong, but that isn't the case.

*Installation details*
Scylla version (or git commit hash): 2020.1.5-0.20201213.b041ee7ebd
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-02720bcdd160a5d8c us-east-2

**Comment by syuu1228** [comment]
Maybe we can fix it on previous versions, but on version 4.4 or later we dropped current node_exporter setup code and introduced .rpm/.deb package for node_exporter, so "node_exporter already installed" error doesn't exist anymore.
https://github.com/scylladb/scylla/commit/95197a09c91eb719c252abed847b8c035f5f9600

**Comment by tzach** [comment]
Closing, moving forward node-exporter is part of the dependencies, can be remove from scylla_setup
@syuu1228 please reopen if its not the case
