### ISSUE TITLE
consumer not at partition boundary

### ISSUE THREAD

**Issue by zooptwopointone** [scylladb/scylla#8023]
I have also run into something like this. Cluster info:
Scylla version 4.2.1-0.20201108.4fb8ebccff with build-id d19a95fd85a8e7df2928ccd8c729941f263e8adc
Cluster size: 4 Datacenters (3 x 3 nodes 1 x 7 nodes)
OS (RHEL/CentOS/Ubuntu/AWS AMI): 18.04.5 LTS (GNU/Linux 4.15.0-128-generic x86_64)

Platform (physical/VM/cloud instance type/docker): Physical
Hardware: sockets= 2 cores=8 hyperthreading= 32 memory= 128 GB
Disks: (SSD/HDD, count) 8 SSD

I need to run the command again, but this happens to me when running a repair or compact. I was just looking into it more to see what level of concern I should have for this. There are a few tables I have that seem to never be able to repair successfuly. but that is for another Issue.

This is the generic part of the log:
[shard 1] storage_proxy - Exception when communicating with 172.21.8.50, to read from keyspace.contact: std::runtime_error (consumer not at partition boundary in sstable /var/lib/scylla/data/.......

Let me know what other information I can provide.

Sorry originally posted this under a closed ticket which I think is related.
https://github.com/scylladb/scylla/issues/6529

**Comment by slivne** [comment]
@zooptwopointone
- are all nodes using the same smp count settings for scylla ?
- `ps -ef | grep scylla` on every node will revile this


We have some reports on mixed cluster smp having issues - and we are activly working to fix this - so as afirst step I would like to see if this is your case (not common) or rule this out.

**Comment by zooptwopointone** [comment]
That is correct not all nodes are the same across the entire cluster.

some DC's have all the same hardware and some have different hardware.  48 Cores vs 32 Cores.  And these are mixed inside the DC.

Looking into this I found something odd with the configuration.  I remember in the past we had set the -smp value, but it appears that it is not set now.  although the -cpuset is set.    And on one of the servers with 48 cores it is set the same way that it is set on the 32 core system.  I imagine this could cause some issues.   For this situation I will for now set the SMP value to allow it the 30 cores.   current CPU set is -cpuset 1-15,17-31 . I imagine this means that smp should be set to 30 if I remember right.

As for inter datacenter there is a larger difference in nodes, but while they are more consistant.  they are configured with 8 Cores currently in the other datacenter, and the keyspace is replicated over to that DC.

Let me know if you would like me to try anything else.

**Comment by zooptwopointone** [comment]
To be more exact.

dc1 = 3 total nodes 2x32 cores 1x48 cores.  
dc2 = 3 total ndoes 3x8 cores

Thinking about this more I seem to remember setting the SMP value to the lower value on the 48 core system in the past.  I am assuming it was after talking to support.   I think the upgrade processes (ours) probably had mutilated the config options along the way.

**Comment by slivne** [comment]
@bhalevy / @denesb - just to make  sure you have seen this - a user with non symetric deployment - running repairs and hitting errors.

**Comment by slivne** [comment]
@bhalevy / @denesb ping

**Comment by denesb** [comment]
I think this might be another symptom of #7552, which we recently fixed on master. This bug causes out-of-order partitions to be written to sstables, confusing the readers when reading these. This can lead to further complication down the line, in some cases leading to sstables with some missing partition end fragments produced, along with a corrupted index, see #7623.
I think you should wait for the fix to be rolled out, upgrade to the fixed version, then do a repair.

**Comment by zooptwopointone** [comment]
FYI I have upgraded to 4.3.1.  which big ID should I be looking in the change log.  I didn't see either of these IDs

**Comment by zooptwopointone** [comment]
Looks like this is still happening with 4.3.1

Feb 23 19:11:16 ID1889LA scylla[47724]:  [shard 4] storage_proxy - Exception when communicating with 172.21.8.51, to read from keyspace.table: std::runtime_error (consumer not at partition boundary, position: {position: clustered,, 0} in sstable /var/lib/scylla/data/keyspace/table-ce8ce90086f911e88919000000000000/mc-989775-big-Data.db)

**Comment by slivne** [comment]
We are still testing the fix for https://github.com/scylladb/scylla/issues/7552 - once backported we will spin a new release and update.

**Comment by slivne** [comment]
fixed in 4.2.4 , 4.3.2

closing this issue as its fixed
