### ISSUE TITLE
Alternator: support CORS (Cross-origin resource sharing)

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8025]
This issue was noted by @nukemberg - I'm not an expert on this so I'll continue editing this issue until I understand the actual details of what we need to do :-)

Although we usually think of Alternator being used in a three-tier application, where some middle layer communicates with Alternator, in some setups there is no middle layer and the user's browser, running Javascript code, wants to communicate directly with the database. However, for security reasons, by default Javascript loaded from domain X is not allowed to communicate with random domains Y. The CORS protocol (see explanation and examples in https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) is meant to allow this, and Alternator needs to participate in this protocol if it is to be used directly from Javascript in browsers.

For example, consider the following HTML page:

```html
<html>
<meta content="text/html;charset=utf-8" http-equiv="Content-Type">
<meta content="utf-8" http-equiv="encoding">
<script src="https://sdk.amazonaws.com/js/aws-sdk-2.1.14.min.js"></script>
<script>
  var dynamodb = new AWS.DynamoDB({
    accessKeyId:    'alternator',
    secretAccessKey:'secret_pass!',
    region:         'us-east-1',
    endpoint:       'http://localhost:8000',
    sslEnabled:     false,
    maxRetries:     5,
  });
  dynamodb.listTables(function(err, data) {
    console.log(data) // { TableNames: Array[0] }
  });
</script>
</html>
```

If we open this HTML file in a browser, we see nothing. But opening the Firefox Web Console, I see the following things transpiring:

1. The browser sends "OPTIONS http://localhost:8000/" and gets a 404 error.
2. This then causes the browser to complain that: **Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8000/. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).**

The expected behavior is that this should work, and whatever the Javascript tried to do (in this case, list the tables), should work.

**Comment by nukemberg** [comment]
My hacky workaround using nginx:
```
cat /etc/nginx/conf.d/alternator.conf
server {
	listen 8000;
	location / {
		if ($request_method = OPTIONS) {
			add_header Access-Control-Allow-Origin "$http_origin";
			add_header Access-Control-Allow-Headers *;
			return 204;
		}
		proxy_pass http://18.195.160.147:8000;
		add_header Vary Access-Control-Allow-Origin;
		add_header Access-Control-Allow-Origin "$http_origin";
		add_header Access-Control-Allow-Headers *;
	}
}
```
The headers returned in response to a `OPTIONS` by DynamoDB:
```
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: x-amzn-RequestId,x-amzn-ErrorType,x-amzn-ErrorMessage,Date
Access-Control-Max-Age: 172800
```

**Comment by psarna** [comment]
It looks like it's a matter of returning specific headers to the OPTIONS request (with Access-Control-Allow-Origin being most important, but I also saw Access-Control-Allow-Methods and Access-Control-Allow-Headers), then the fix is probably a couple of lines in the alternator server.

**Comment by nyh** [comment]
Patch available on the mailing list, titled "[PATCH] Alternator: add support for CORS protocol".
