### ISSUE TITLE
Make sure that all info printed by `large_xx` loggers could be found in corresponding `system.large_xxx` tables and vise versa

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#8026]
*Installation details*
HEAD: 873e732042aa88b8e84aed0431b6b02e640bbfab

*Description*
Today the data that is printed by the large_partition logger is not the one that can be found in the large_partition table: the former reports partitions that have more than `compaction_rows_count_warning_threshold` rows while the later has partitions which size is greater than the `compaction_large_partition_warning_threshold_mb`.

It makes little sense that people need to look at both the syslog and the table in order to get the full picture about large partitions situation in their data set.

It would make more sense to be able to get the full picture by looking at either source: syslog or system.large_xxx table.

**Comment by vladzcloudius** [comment]
@slivne FYI

**Comment by slivne** [comment]
@avikivity -do we still need the compaction_rows_count_warning_threshold - or should we set it to a very high value now that with binary search and with md format partitions with many rows are not an issue as they were. 

In any case vlad is correct this is confusing

**Comment by bhalevy** [comment]
@vladzcloudius looks like this issue can be closed with https://github.com/scylladb/scylla/pull/9577, right?

**Comment by vladzcloudius** [comment]
Oh, the patch is good - it's "subject" is AWFUL however ;)

Yes, we can close this one.
