### ISSUE TITLE
commitlog_test.test_allocation_failure fails rarely: Adding mutation of size {} succeeded unexpectedly

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8028]
I see spurious failures of commitlog_test in dev/release modes in my branch based on scylladb/scylla@873e73204:
```
unknown location(0): fatal error: in "test_allocation_failure": std::runtime_error: Got an unexpected exception from writing too large record: std::runtime_error (Adding mutation of size 16777203 succeeded unexpectedly)
```

@avikivity proposed the following:
> I think the real problem is that commitlog was changed to use 
> fragmented_temporary_buffer::ostream (db::commitlog::output). So if 
> there are discontiguous small memory blocks, they can be used to satisfy 
> an allocation even if no contiguous memory blocks are available.
> 
> So maybe we should allocate all 128k memory blocks, free a few (so that 
> we won't fail on allocating continuations), and move on.

**Comment by elcallio** [comment]
'tis a sad time when test of failure succeed. Maybe we should just drop the test? It is perhaps not the most important thing to validate?

**Comment by bhalevy** [comment]
This change seems to fix the issue:
```diff c++
index 92e731b92..7fd3093f7 100644
--- a/test/boost/commitlog_test.cc
+++ b/test/boost/commitlog_test.cc
@@ -580,7 +580,7 @@ SEASTAR_TEST_CASE(test_allocation_failure){
             // Use us loads of memory so we can OOM at the appropriate place
             try {
                 for (;;) {
-                    junk->emplace_back(new char[size]);
+                    junk->emplace_back(new char[fragmented_temporary_buffer::default_fragment_size]);
                 }
             } catch (std::bad_alloc&) {
             }
```

**Comment by bhalevy** [comment]
> 'tis a sad time when test of failure succeed. Maybe we should just drop the test? It is perhaps not the most important thing to validate?

Maybe it's not the most important, but it is important that verify scylla is resilient to allocation failures, so I think it's valuable to have this test.

**Comment by elcallio** [comment]
Fair enough, for what it is worth, I approve the change.

**Comment by bhalevy** [comment]
> Fair enough, for what it is worth, I approve the change.

Thanks.  I sent a slightly more sophisticated fix to the mailing list for your review...

**Comment by bhalevy** [comment]
Seen also https://jenkins.scylladb.com/view/scylla-4.4/job/scylla-4.4/job/next/163/testReport/junit/test_boost_commitlog_test/cc/test_allocation_failure/

Cc @scylladb/scylla-maint

**Comment by nyh** [comment]
@bhalevy thanks. This is already in 4.5. I'll backport now to the other live releases (4.4 and 4.3).

**Comment by nyh** [comment]
Backported to next-4.4 (35d89298da0d197401ed664dae91d1c41a36ec4b) and next-4.3 (709e934164113d3ef51f0b85fbbe07bb02f10007).
