### ISSUE TITLE
docker: need to add documentation on how to bypass running io-setup in docker

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#8034]
we are missing documentation for some of the additional docker flags https://github.com/scylladb/scylla/blob/master/docs/guides/docker-hub.md

specifically - need to document how to bypass io-setup and use a preset io_properties value
 
https://github.com/scylladb/scylla/issues/6587

**Comment by penberg** [comment]
@slivne The skipping part is documented here: https://github.com/scylladb/scylla/blob/master/docs/guides/docker-hub.md#--io-setup-enable (perhaps we did not upload it to Docker Hub -- will check?)

I/O properties override is indeed not documented. Is there an existing procedure that people use that we can document? The options are to override the `/etc/scylla.d/io_properties.yaml` file or specify the `--io-properties-file` command line options, I think.

**Comment by penberg** [comment]
Docker Hub was out of sync with the file. Updated.
