### ISSUE TITLE
Scylla upgrade from 4.2.3 to 4.3 yields errors when max_memory_for_unlimited_query parameter is updated to new parameters

### ISSUE THREAD

**Issue by jtnagashima** [scylladb/scylla#8035]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): **scylla-4.3.0-0.20210110.000585522.x86_64**
Cluster size: **5 nodes**
OS (RHEL/CentOS/Ubuntu/AWS AMI): **AWS AMI**

*Hardware details (for performance issues)*       
Platform (physical/VM/cloud instance type/docker): **i3.xlarge**

Error logs on scylla nodes running 4.2.3
```
Jan 29 00:54:08 node-3 scylla[10385]:  [shard 3] storage_proxy - Exception when communicating with node-5, to read from ks_1.tb_1: std::runtime_error (Memory usage of reversed read exceeds hard limit of 1048576 (configured via max_memory_for_unlimited_query_hard_limit), while reading partition 57:40:2021-01:cl_wins)
Jan 29 00:54:08 node-3 scylla[10385]:  [shard 3] storage_proxy - Exception when communicating with node-5, to read from ks_1.tb_2: std::runtime_error (Memory usage of reversed read exceeds hard limit of 1048576 (configured via max_memory_for_unlimited_query_hard_limit), while reading partition 54:2021-01:cl_kwh)
Jan 29 00:54:08 node-3 scylla[10385]:  [shard 0] storage_proxy - Exception when communicating with node-5, to read from ks_2.tb_2: std::runtime_error (Memory usage of reversed read exceeds hard limit of 1048576 (configured via max_memory_for_unlimited_query_hard_limit), while reading partition 61:2021-01:cl_kwh)
Jan 29 00:54:09 node-3 scylla[10385]:  [shard 3] storage_proxy - Exception when communicating with node-5, to read from ks_1.tb_2: std::runtime_error (Memory usage of reversed read exceeds hard limit of 1048576 (configured via max_memory_for_unlimited_query_hard_limit), while reading partition 51:2021-01:cl_kwh)
```
Corresponding (time wise) logs on Scylla node upgraded to 4.3:
```
Jan 29 00:54:08 node-5 scylla[15002]:  [shard 0] flat_mutation_reader - Memory usage of reversed read exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit), while reading partition 45:2021-01:cl_kwh
Jan 29 00:54:08 node-5 scylla[15002]:  [shard 3] flat_mutation_reader - Memory usage of reversed read exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit), while reading partition 48:2021-01:cl_kwh
Jan 29 00:54:08 node-5 scylla[15002]:  [shard 3] flat_mutation_reader - Memory usage of reversed read exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit), while reading partition 5:1:2021-01:cl_ebl
Jan 29 00:54:08 node-5 scylla[15002]:  [shard 0] flat_mutation_reader - Memory usage of reversed read exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit), while reading partition 58:2021-01:cl_kwh
Jan 29 00:54:08 node-5 scylla[15002]:  [shard 0] flat_mutation_reader - Memory usage of reversed read exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit), while reading partition 44:2021-01:cl_kwh
Jan 29 00:54:08 node-5 scylla[15002]:  [shard 2] flat_mutation_reader - Memory usage of reversed read exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit), while reading partition 14:1:2021-01:cl_ebl
Jan 29 00:54:08 node-5 scylla[15002]:  [shard 0] flat_mutation_reader - Memory usage of reversed read exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit), while reading partition 48:40:2021-01:cl_wins
```
scylla.yaml for 4.3 node:
```
cluster_name: devcluster
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "node-0"
listen_address: node-5
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 5000
endpoint_snitch: Ec2Snitch
rpc_address: 0.0.0.0
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
broadcast_rpc_address: node-5
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
murmur3_partitioner_ignore_msb_bits: 12
auto_bootstrap: true
enable_sstables_mc_format: true
max_memory_for_unlimited_query_soft_limit: 419430400
max_memory_for_unlimited_query_hard_limit: 536870912 
api_ui_dir: /opt/scylladb/swagger-ui/dist/
api_doc_dir: /opt/scylladb/api/api-doc/
```
scylla.yaml for a 4.2.3 node:
```
cluster_name: devcluster
num_tokens: 256
data_file_directories:
    - /var/lib/scylla/data
commitlog_directory: /var/lib/scylla/commitlog
commitlog_sync: periodic
commitlog_sync_period_in_ms: 10000
commitlog_segment_size_in_mb: 32
seed_provider:
    - class_name: org.apache.cassandra.locator.SimpleSeedProvider
      parameters:
          - seeds: "node-0"
listen_address: node-3
native_transport_port: 9042
read_request_timeout_in_ms: 5000
write_request_timeout_in_ms: 5000
endpoint_snitch: Ec2Snitch
rpc_address: 0.0.0.0
rpc_port: 9160
api_port: 10000
api_address: 127.0.0.1
batch_size_warn_threshold_in_kb: 5
batch_size_fail_threshold_in_kb: 50
broadcast_rpc_address: node-3
partitioner: org.apache.cassandra.dht.Murmur3Partitioner
commitlog_total_space_in_mb: -1
murmur3_partitioner_ignore_msb_bits: 12
auto_bootstrap: true
enable_keyspace_column_family_metrics: true
enable_sstables_mc_format: true
max_memory_for_unlimited_query: 536870912
api_ui_dir: /opt/scylladb/swagger-ui/dist/
api_doc_dir: /opt/scylladb/api/api-doc/
```
**Background**
We were performing a cluster upgrade from 4.2.3 to 4.3 following the [official upgrade instructions](https://docs.scylladb.com/upgrade/upgrade-opensource/upgrade-guide-from-4.2-to-4.3/upgrade-guide-from-4.2-to-4.3-rpm/). As the upgrade process for the first node was finishing up, we updated the scylla.yaml file with the new memory parameters: 
```
max_memory_for_unlimited_query_soft_limit: 419430400
max_memory_for_unlimited_query_hard_limit: 536870912 
```
Scylla service was then started up and the aforementioned errors appeared in the logs. Since this was a test cluster, we went ahead and upgraded the rest of the nodes with the soft and hard limit parameters and the issue subsided. The concern here is that when we move to upgrade the production cluster, the errors will appear and cause brief outages as queries are rejected.

**Comment by jtnagashima** [comment]
To note: we referenced this doc: https://docs.scylladb.com/troubleshooting/reverse-queries/ when we initially encountered the reverse querying issues.

**Comment by slivne** [comment]
@jtnagashima - please note 

```
Memory usage of reversed read exceeds soft limit of 1048576 (configured via max_memory_for_unlimited_query_soft_limit),
```


which is much lower then your soft-limit - I think the configuration change did not take effect

you can check scylla configuration used in runtime 


```
curl 127.0.0.1:10000/v2/config/max_memory_for_unlimited_query_soft_limit
```

**Comment by jtnagashima** [comment]
FWIW, I was able to recreate the outcome on a test cluster:

- deployed a 5 node scylla cluster running 4.2.3 with the query parameter set as follows `max_memory_for_unlimited_query: 536870912` and was able to run a reverse query without issue
- upgraded one node to 4.3 and swapped out `the max_memory_for_unlimited_query` config for `max_memory_for_unlimited_query_soft_limit: 419430400` and `max_memory_for_unlimited_query_hard_limit: 536870912` and restarted scylla-server
- verified that the configuration was accepted on the upgraded node:
```
$curl 127.0.0.1:10000/v2/config/max_memory_for_unlimited_query_soft_limit
419430400
$curl 127.0.0.1:10000/v2/config/max_memory_for_unlimited_query_hard_limit
536870912
```
- Ran the same reverse query from the node that's still running 4.2.3 and it returns the following error:
```
ReadFailure: Error from server: code=1300 [Replica(s) failed to execute read] message="Operation failed for ks.tb - received 0 responses and 2 failures from 1 CL=ONE." info={'failures': 2, 'received_responses': 0, 'required_responses': 1, 'consistency': 'ONE'}
```
The scylla logs show `Memory usage of reversed read exceeds hard limit of 1048576 (configured via max_memory_for_unlimited_query_hard_limit)`. On the upgraded node, no errors are present in the logs.

**Comment by jtnagashima** [comment]
... couple more observations:

- after upgrading the entire cluster and keeping the same soft/hard limits, the reverse query runs successfully from the same node
- the reverse query can be run from a node that has been upgraded to 4.3 without issue even when the cluster is a heterogenous mix of 4.2.3 and 4.3 nodes

**Comment by denesb** [comment]
@jtnagashima this issue is due to the way we handle mixed clusters in this feature. Since fea5067df the limit is sent by the coordinator to the replicas, to ensure either all participating replicas will bail out or none of them. In a mixed cluster it may happen that the coordinator is an old node which doesn't send this limit. In this case the replicas fall-back to the default limit for paged queries as the hard limit. This is the `1048576` you saw above. This is the reason you see this behaviour with an 4.2 node acting as coordinator, but not with a 4.3 node acting as one or in a fully upgraded cluster.

**Comment by denesb** [comment]
Maybe we should fall back to the replica-local settings instead.

**Comment by denesb** [comment]
@jtnagashima I prepared an RPM with the proposed fix, please test it on your test cluster and see if it makes the problem go away.
http://scratch.scylladb.com/scylla-8035/scylla-server-4.3.0-1.locallimit.20210205.d405089d8.x86_64.rpm

**Comment by jtnagashima** [comment]
@denesb Much better performance! There were just three initial memory errors showing up on an 4.2.3 node:
```
[shard 1] storage_proxy - Exception when communicating with node-4 (upgraded 4.3 node), to read from ks.tb: std::runtime_error (Memory usage of reversed read exceeds hard limit of 1048576 (configured via max_memory_for_unlimited_query_hard_limit), while reading partition 541_1583020800000_1585699200000
```
.. but it soon subsided and no amount of reverse queries from that node yielded any further complaints. I think this makes for a much smoother (ie less scary) upgrade process. 

Thank you!

**Comment by slivne** [comment]
@denesb please send the official we will need to backport this (I am not sure ifvalue should be rea locall allways or only in case the coordinator did not send something - but lets have others review this)

**Comment by denesb** [comment]
Patch on the list: [PATCH v1] query: use local limit for non-limited queries in mixed cluster

**Comment by slivne** [comment]
fixed by https://github.com/scylladb/scylla/commit/ba1ff70e3f6e4dc853d77fd01c2e8ba8d749872c

**Comment by avikivity** [comment]
Backported to 4.3, 4.4.
