### ISSUE TITLE
 Operation timed out - received only 0 responses.

### ISSUE THREAD

**Issue by vadimtk** [scylladb/scylla#804]
I am running my benchmark against ScyllaDB and often on batch insert I receive:
`Unable to connect: Operation timed out - received only 0 responses.`

I do not have this problem with Cassandra.

The code that inserts data is in this part
https://github.com/Percona-Lab/MetricBench/blob/master/src/CassandraDriver.cpp#L212

**Comment by gleb-cloudius** [comment]
Which version of scylla are you using? Do you use AMI? Do you have logs?

On Thu, Jan 14, 2016 at 09:23:01PM -0800, Vadim Tkachenko wrote:
> I am running my benchmark against ScyllaDB and often on batch insert I receive:
> Unable to connect: Operation timed out - received only 0 responses.
> 
> I do not have this problem with Cassandra.
> 
> The code that inserts data is in this part
> https://github.com/Percona-Lab/MetricBench/blob/master/src/CassandraDriver.cpp#L212
> 
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/scylladb/scylla/issues/804

--
			Gleb.

**Comment by vadimtk** [comment]
I am using 0.15 version installed from RPM on CentOS 7.

There is what I have in logs
`WARNING: exceptional future ignored of type 'exceptions::mutation_write_timeout_exception': Operation timed out - received only 0 responses.
WARNING: exceptional future ignored of type 'exceptions::mutation_write_timeout_exception'ERROR [shard 0] batchlog_manager - Exception in batch replay: exceptions::read_timeout_exception (Operation timed out - received only 0 responses.)
ERROR [shard 0] batchlog_manager - Exception in batch replay: exceptions::read_timeout_exception (Operation timed out - received only 0 responses.)`

**Comment by gleb-cloudius** [comment]
Can you describe your setup, schema and kind of batch queries you are
running?

On Fri, Jan 15, 2016 at 07:12:42AM -0800, Vadim Tkachenko wrote:
> I am using 0.15 version installed from RPM on CentOS 7.
> 
> There is what I have in logs
> `WARNING: exceptional future ignored of type 'exceptions::mutation_write_timeout_exception': Operation timed out - received only 0 responses.
> WARNING: exceptional future ignored of type 'exceptions::mutation_write_timeout_exception'ERROR [shard 0] batchlog_manager - Exception in batch replay: exceptions::read_timeout_exception (Operation timed out - received only 0 responses.)
> ERROR [shard 0] batchlog_manager - Exception in batch replay: exceptions::read_timeout_exception (Operation timed out - received only 0 responses.)`
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/scylladb/scylla/issues/804#issuecomment-171987454

--
			Gleb.

**Comment by vadimtk** [comment]
I am using a following schema

                  "CREATE KEYSPACE metricsdata2 WITH replication = { \
                  'class': 'SimpleStrategy', 'replication_factor': '3' };"

                  "CREATE TABLE metricsdata2.metrics ( \
		  device_id int, \
		  metric_id int, \
		  ts timestamp, \
		  cnt int, \
		  val double, \
		  PRIMARY KEY ((device_id, metric_id), ts));"

After that I use following queries to insert data

	    sql<< "INSERT INTO metricsdata2.metrics (" <<
		  "device_id, metric_id, ts, cnt, val) VALUES (" << 
            	  device_id << "," <<
            	  mc << "," <<
		  timestamp*1000 << "," <<
            	  cnf << "," <<
            	 v << ");";
	    CassStatement* statement = cass_statement_new(sql.str().c_str(),0);
	    cass_batch_add_statement(batch, statement);
	    cass_statement_free(statement);

There batch are execute in parallel in multiple threads.

**Comment by gleb-cloudius** [comment]
What is your disk configuration? Is it ssd or spinning disk?

**Comment by vadimtk** [comment]
I am using PCIe SSD, it is very fast.

On Mon, Jan 18, 2016 at 2:25 AM, Gleb Natapov <notifications@github.com>
wrote:

> What is your disk configuration? Is it ssd or spinning disk?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/804#issuecomment-172489970>.
>



-- 
Vadim Tkachenko, CTO, Percona
Phone +1-919-249-7483,  Skype: vadimtk153

**Comment by avikivity** [comment]
Is the disk formatted with the XFS filesystem?

What is the command line you use for MetricBench?  I will try to reproduce the problem.

**Comment by vadimtk** [comment]
It is XFS filesystem.

For my run I use
./MetricBench --mode=prepare --driver=cassandra --threads=32

Thanks,
Vadim


On Mon, Jan 18, 2016 at 8:13 AM, Avi Kivity <notifications@github.com>
wrote:

> Is the disk formatted with the XFS filesystem?
>
> What is the command line you use for MetricBench? I will try to reproduce
> the problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/804#issuecomment-172573673>.
>



-- 
Vadim Tkachenko, CTO, Percona
Phone +1-919-249-7483,  Skype: vadimtk153

**Comment by tgrabiec** [comment]
Should be fixed by 8ba474f1c963a43d571d33a2cf7fbb54f108b7b2

**Comment by penberg** [comment]
@gleb-cloudius reported that https://github.com/scylladb/scylla/commit/8ba474f1c963a43d571d33a2cf7fbb54f108b7b2 indeed fixes the issue. Closing.
