### ISSUE TITLE
Restart one node of Cluster failed 

### ISSUE THREAD

**Issue by JKeyZ** [scylladb/scylla#8042]
When restart the one node of scylla cluster ,  occur error and service brok down :
Feb 06 16:54:54 scylla2 scylla[25650]:  [shard 7] compaction - Compacted 2 sstables to [/data2/scylla/data/system/truncated-38c19fd0fb863310a4b70d0cc66628aa/mc-11959-big-Data.db:level=0, ]. 91kB to 86kB (~94% of original) in 9ms = 9MB/s. ~2
**Feb 06 16:54:54 scylla2 scylla[25650]:  [shard 4] view - start failed: boost::wrapexcept<boost::bad_lexical_cast> (bad lexical cast: source type value could not be interpreted as target)
Feb 06 16:54:54 scylla2 scylla[25650]:  [shard 8] view - start failed: boost::wrapexcept<boost::bad_lexical_cast> (bad lexical cast: source type value could not be interpreted as target)
Feb 06 16:54:54 scylla2 scylla[25650]:  [shard 9] view - start failed: boost::wrapexcept<boost::bad_lexical_cast> (bad lexical cast: source type value could not be interpreted as target)
Feb 06 16:54:54 scylla2 scylla[25650]:  [shard 3] view - start failed: boost::wrapexcept<boost::bad_lexical_cast> (bad lexical cast: source type value could not be interpreted as target)
Feb 06 16:54:54 scylla2 scylla[25650]:  [shard 7] view - start failed: boost::wrapexcept<boost::bad_lexical_cast> (bad lexical cast: source type value could not be interpreted as target)
Feb 06 16:54:54 scylla2 scylla[25650]:  [shard 2] view - start failed: boost::wrapexcept<boost::bad_lexical_cast> (bad lexical cast: source type value could not be interpreted as target)
Feb 06 16:54:54 scylla2 scylla[25650]:  [shard 6] view - start failed: boost::wrapexcept<boost::bad_lexical_cast> (bad lexical cast: source type value could not be interpreted as target)
Feb 06 16:54:54 scylla2 scylla[25650]:  [shard 1] view - start failed: boost::wrapexcept<boost::bad_lexical_cast> (bad lexical cast: source type value could not be interpreted as target)**
Feb 06 16:54:54 scylla2 scylla[25650]:  [shard 0] cql_server_controller - Starting listening for CQL clients on 0.0.0.0:9042 (unencrypted)
**Feb 06 16:54:54 scylla2 scylla[25650]:  [shard 0] view - start failed: boost::wrapexcept<boost::bad_lexical_cast> (bad lexical cast: source type value could not be interpreted as target)**
Feb 06 16:54:54 scylla2 scylla[25650]:  [shard 15] seastar_memory - oversized allocation: 46886912 bytes. This is non-fatal, but could lead to latency and/or fragmentation issues. Please report: at    0x334961d
                                          0x3349930
                                          0x3349db9
                                          0x2e405d3
                                          0x2e44c5b
                                          0xd42645
                                          0x18b52f0
                                          0x18b6199
                                          0x1bd7e01
                                          0x1b756df
                                          0x1b75b9a
                                          0x2e8fab7
                                          0x2e8fe2e
                                          0x2ec6f0d
                                          0x2ed690a
                                          0x2e5ab8d
                                          /opt/scylladb/libreloc/libpthread.so.0+0x9431
                                          /opt/scylladb/libreloc/libc.so.6+0x101912
                                          --------
                                          seastar::continuation<seastar::internal::promise_base_with_type<std::vector<db::system_keyspace::view_build_progress, std::allocator<db::system_keyspace::view_build_progress> > >, db::system_keyspac
                                          --------
                                          seastar::(anonymous namespace)::thread_wake_task
                                          --------
                                          N7seastar12continuationINS_8internal22promise_base_with_typeIJEEEZNS_5asyncIZZN2db4view12view_builder5startERN7service17migration_managerEENKUlRNS7_23view_builder_init_stateEE_clESC_EUlvE_JEEENS_8fu
                                          --------
                                          N7seastar12continuationINS_8internal22promise_base_with_typeIJEEENS_6futureIJEE12finally_bodyIZNS_5asyncIZZN2db4view12view_builder5startERN7service17migration_managerEENKUlRNSA_23view_builder_init_s
                                          --------
                                          seastar::continuation<seastar::internal::promise_base_with_type<>, db::view::view_builder::start(service::migration_manager&)::{lambda(db::view::view_builder::view_builder_init_state&)#1}::operator(
                                          --------
                                          seastar::continuation<seastar::internal::promise_base_with_type<>, db::view::view_builder::start(service::migration_manager&)::{lambda(db::view::view_builder::view_builder_init_state&)#1}::operator(
                                          --------
                                          seastar::continuation<seastar::internal::promise_base_with_type<>, db::view::view_builder::start(service::migration_manager&)::{lambda(db::view::view_builder::view_builder_init_state&)#1}::operator(
                                          --------
                                          seastar::internal::do_with_state<std::tuple<db::view::view_builder::view_builder_init_state>, seastar::future<> >
                                          --------
                                          seastar::continuation<seastar::internal::promise_base_with_type<>, seastar::future<>::handle_exception<db::view::view_builder::start(service::migration_manager&)::{lambda(std::__exception_ptr::excep

Scylla versoin: 4.2
OS version: centos 7

**Comment by slivne** [comment]
@nyh 

The backtrace provided has ```db::system_keyspace::view_build_progress,std::allocatordb::system_keyspace::view_build_progress``` - which is pointing at MV/SI - please have a look - you my want to decode this again.

**Comment by slivne** [comment]
@JKeyZ can you pleas provide the full scylla version 4.2.X what is X and what OS  are you running on.

If you can share your schema it may also help

**Comment by slivne** [comment]
@nyh / @eliransin  ping

**Comment by slivne** [comment]
@nyh / @eliransin ping

**Comment by nyh** [comment]
@slivne I'll take a look now. Since you already assigned the issue to me I can't assign it to myself a sign I'm working on it...

**Comment by nyh** [comment]
I am thinking that perhaps it is the same problem of https://github.com/scylladb/scylla/issues/6934, which was fixed in Scylla 4.3 but never backported to 4.2. @JKeyZ if you are considering to upgrade to the 4.3 branch, Scylla might be able to boot for you.

Also, if you can please run `sstabledump` on the `system.scylla_views_builds_in_progress` system table on the faulty node and show us the result, maybe we can figure out if this is really bad content in this system table (which keeps track of view builds in progress) - and why this happens.

**Comment by eliransin** [comment]
@JKeyZ if you could do the sstabledump as asked by @nyh it will be great because it can confirm our suspicion of what the 
problem is and we will be able to help you with workaround or a fix.
Thanks,

**Comment by slivne** [comment]
Closing this issue as its stale, @JKeyZ - if you can provide the information, we will be happy to reopen and work with you to reolve / workaround the issue.
