### ISSUE TITLE
stream_session::prepare is missing a string format argument

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8067]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release-parallel/23/artifact/logs-release.007/1613023693780_materialized_views_test.TestMaterializedViews.mv_populating_from_existing_data_during_node_decommission_test/node1.log
```
ERROR 2021-02-11 06:01:32,804 [shard 0] stream_session - failed to log message: fmt::v7::format_error (argument not found)
```

Apparently this is caused by:
https://github.com/scylladb/scylla/blob/9cbbf40710f0b46056cac18d256e0886d1d62dfc/streaming/stream_session.cc#L383

This was introduced long ago, in 860c7aff37a0118d4d4f43890f32542c4cbb9aa1
hence it needs backporting to all living releases.

**Comment by avikivity** [comment]
Backported to 4.2, 4.3, 4.4.
