### ISSUE TITLE
large allocations in canonical_mutation

### ISSUE THREAD

**Issue by wmitros** [scylladb/scylla#8074]
As detected in #6376, the `bytes` field in the `canonical_mutation` class can be initialized with a large value, causing an allocation of over 1MB, for example in `convert_schema_to_mutations` (line 776) https://github.com/scylladb/scylla/blob/718976e794790253c4b24e2c78208e11f24e7502/db/schema_tables.cc#L757-L777 which is used during migrations

**Comment by avikivity** [comment]
Not a regression, so not backporting.
