### ISSUE TITLE
Wrong maximum blob size

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#808]
From limit.py test.

    ERROR: max_column_value_size_test (limits.TestLimits)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/benoit/scylla-dtest/dtest.py", line 594, in tearDown
        raise AssertionError('Unexpected error in %s node log: %s' % (node.name, errors))
    AssertionError: Unexpected error in node1 node log: ['ERROR [shard 0] storage_proxy - exception during mutation write to 127.0.0.1: std::invalid_argument (Mutation of 16777318 bytes is too large for the maxiumum size of 16777216)\nERROR [shard 0] storage_proxy - exception during mutation write to 127.0.0.1: std::invalid_argument (Mutation of 16777318 bytes is too large for the maxiumum size of 16777216)\nERROR [shard 0] storage_proxy - exception during mutation write to 127.0.0.1: std::invalid_argument (Mutation of 16777318 bytes is too large for the maxiumum size of 16777216)\nERROR [shard 0] storage_proxy - exception during mutation write to 127.0.0.1: std::invalid_argument (Mutation of 16777318 bytes is too large for the maxiumum size of 16777216)\nERROR [shard 0] storage_proxy - exception during mutation write to 127.0.0.1: std::invalid_argument (Mutation of 16777318 bytes is too large for the maxiumum size of 16777216)\nERROR [shard 0] storage_proxy - exception during mutation write to 127.0.0.1: std::invalid_argument (Mutation of 16777318 bytes is too large for the maxiumum size of 16777216)']

current known limit: 8388607 (known power of 2)

should be: 2G

crash: no, catches exception

extract of scylla output:

    INFO  [shard 0] compaction - Compacted 4 sstables to [/home/benoit/.dtest/dtest-SgBm7t/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-65-Data.db:level=0, ]. 14320 bytes to 14191 (~99% of original) in 183ms = 0.0735786MB/s. ~1024 total partitions merged to 1.
    ERROR [shard 0] storage_proxy - exception during mutation write to 127.0.0.1: std::invalid_argument (Mutation of 16777318 bytes is too large for the maxiumum size of 16777216)
    ERROR [shard 0] storage_proxy - exception during mutation write to 127.0.0.1: std::invalid_argument (Mutation of 16777318 bytes is too large for the maxiumum size of 16777216)
    ERROR [shard 0] storage_proxy - exception during mutation write to 127.0.0.1: std::invalid_argument (Mutation of 16777318 bytes is too large for the maxiumum size of 16777216)
    ERROR [shard 0] storage_proxy - exception during mutation write to 127.0.0.1: std::invalid_argument (Mutation of 16777318 bytes is too large for the maxiumum size of 16777216)
    ERROR [shard 0] storage_proxy - exception during mutation write to 127.0.0.1: std::invalid_argument (Mutation of 16777318 bytes is too large for the maxiumum size of 16777216)
    ERROR [shard 0] storage_proxy - exception during mutation write to 127.0.0.1: std::invalid_argument (Mutation of 16777318 bytes is too large for the maxiumum size of 16777216)

**Comment by slivne** [comment]
@benoit-canet can you try this on cassandra and see what you get there

**Comment by avikivity** [comment]
Please try it with the heap limited to 1GB as well.

**Comment by benoit-canet** [comment]
@slivne: I got the same limit on cassandra

**Comment by benoit-canet** [comment]
same limit as cassandra. closing the bug

**Comment by penberg** [comment]
@benoit-canet Can you please fix the failing dtest?
