### ISSUE TITLE
cql-pytest should recognize Scylla is down and not report hundreds of tests failing

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8080]
Currently, if Scylla crashes in the middle of a `test/cql-pytest/run`, the log and Jenkins will report all the individual tests following the crashing test as failing. When you see a list of a hundred tests failing, it's harder to understand what really failed.
An example is https://jenkins.scylladb.com/job/scylla-master/job/next/3186//consoleText, which has:
```
[2021-02-14T22:09:39.429Z] test_json.py ........xx..xx.xxxxxxxxx                                    [ 25%]
[2021-02-14T22:09:39.429Z] test_keyspace.py FFFFFxFFFFxFF                                           [ 33%]
[2021-02-14T22:09:39.429Z] test_large_cells_rows.py F                                               [ 33%]
[2021-02-14T22:09:39.429Z] test_minmax.py F                                                         [ 34%]
[2021-02-14T22:09:39.429Z] test_null.py Ex                                                          [ 35%]
```
In this example, the last test in test_json.py was the one that crashed Scylla. We actually expected this test to fail (xfail)  but then all the following tests failed. The log shows that all these failures come from Scylla indeed being down:
```
[2021-02-14T22:09:39.430Z] E           cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {})
2021-02-14T22:09:39.430Z] /usr/local/lib64/python3.9/site-packages/cassandra/cluster.py:4877: NoHostAvailable
```

But it's still annoying to figure out which test was the real failure. Especially in the Jenkins UI (https://jenkins.scylladb.com/job/scylla-master/job/next/3186/testReport/) where it isn't clear which was the real first test to fail (we see the one after it).

It would have been ideal if pytest could tell us which specific test really caused Scylla to crash and mark it as a failure, and mark all the rest as "E" (i.e., an error to set up the test - not a failure in the actual test). 

Maybe we could do the following:
1. End each test with a trivial "ping" to Scylla. If it fails, mark the test failed or otherwise make it very visible where this happened.
2. It's important to do this even for tests that were marked xfailed.
3. All the following tests should know that Scylla is already down, and report an "E" (failure to set up), not an "F".

I don't know how to implement this in practice, given that the "cql" fixture is marked per-session, not per function. If we can't run per-function code on per-session fixtures (?), one option is to make cql a per-function fixture, which uses a per-session fixture to do the real cql connection, and also have per-function setup and teardown code.

**Comment by nyh** [comment]
The patch
```patch
diff --git a/test/cql-pytest/conftest.py b/test/cql-pytest/conftest.py
index 28150ecc6..1e05788a8 100644
--- a/test/cql-pytest/conftest.py
+++ b/test/cql-pytest/conftest.py
@@ -64,6 +64,17 @@ def cql(request):
     )
     return cluster.connect()
 
+# A function-scoped autouse=True fixture allows us to test after every test
+# that the CQL connection is still alive - and if not report the test which
+# crashed Scylla and stop running any more tests.
+@pytest.fixture(scope="function", autouse=True)
+def cql_test_connection(cql, request):
+    yield
+    try:
+        cql.execute("use system")
+    except:
+        pytest.exit(f"Scylla appears to have crashed in test {request.node.parent.name}::{request.node.name}")
+
 # "test_keyspace" fixture: Creates and returns a temporary keyspace to be
 # used in tests that need a keyspace. The keyspace is created with RF=1,
 # and automatically deleted at the end. We use scope="session" so that all
```

Tries to run a do-nothing CQL command (unfortunately I couldn't find anything less than "use system"...) after every test, and if it fails, reports the test which crashed Scylla and exits so we won't get a hundred more failures. Output now looks like this:
```
test_frozen_collection.py xx.....                                        [ 13%]
test_json.py F
! _pytest.outcomes.Exit: Scylla appears to have crashed in test test/cql-pytest/test_json.py::test_failed_json_parsing_unprepared !
...
Scylla tests failure
```

There are still things which bother me about this solution:
1. If the test crashing Scylla was xfail, we will still see the exit message implicating it, but the test itself will still not be reported as failing, so it's not obvious how to see this in Jenkins without manually finding the exit message in the full log. I don't know how to "convert" the xfailing test to an official fail.
2. I wish we had a real do-nothing CQL command, not "use system". An empty command doesn't work in Scylla. Any reason why it shouldn't? Is it also forbidden in Cassandra?

**Comment by avikivity** [comment]
No production impact, not backporting.
