### ISSUE TITLE
Scylla assert on returning result when max column size is overflow

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#809]
New test in limits.py wrongly written caused a CQL error show below:

kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk, type=org.apache.cassandra.db.marshal.Int32Type, kind=PARTITION_KEY, componentIndex=0, indexName=null, indexType=null}],compactionStrategyClass=class org.apache.cassandra.db.compaction.SizeTieredCompactionStrategy,compactionStrategyOptions={},compressionParameters={sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor},bloomFilterFpChance=0.01,memtableFlushPeriod=0,caching={"keys":"ALL","rows_per_partition":"ALL"},defaultTimeToLive=0,minIndexInterval=128,maxIndexInterval=2048,speculativeRetry=99.0PERCENTILE,droppedColumns={},triggers=[],isDense=false]
INFO  [shard 0] compaction - Compacting [/home/benoit/.dtest/dtest-lPODHk/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-1-Data.db:level=0, /home/benoit/.dtest/dtest-lPODHk/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-2-Data.db:level=0, /home/benoit/.dtest/dtest-lPODHk/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-3-Data.db:level=0, /home/benoit/.dtest/dtest-lPODHk/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-4-Data.db:level=0, ]
INFO  [shard 0] compaction - Compacted 4 sstables to [/home/benoit/.dtest/dtest-lPODHk/test/node1/data/system/local-7ad54392bcdd35a684174e047860b377/system-local-ka-5-Data.db:level=0, ]. 12729 bytes to 12516 (~98% of original) in 71ms = 0.167566MB/s. ~1024 total partitions merged to 1.
scylla: transport/server.cc:1281: void transport::cql_server::response::write_string(const sstring&): Assertion `s.size() < std::numeric_limits<int16_t>::max()' failed.
[benoit@localhost scylla]$

**Comment by benoit-canet** [comment]
@slivne : origin policy is to let the user tweak the jvm memory size in the launch shell script
                Should I do the same ?

**Comment by slivne** [comment]
1) We should not assert and crash the server - we need to decide what we
should do - but assert is the wrong action in my view.

So this is a good test.

2) Lets try tweaking the startup script and see where we get to .... (we
need to see if a user that has twiked cassandra to get this working can
twik scylla as well)

**Comment by penberg** [comment]
@benoit-canet @slivne Why is this issue closed?

**Comment by slivne** [comment]
it should not be closed ...

**Comment by benoit-canet** [comment]
The bug report is real but the test was wrong.

So this bug really triggers when a huge CQL query is wrongly formated
and the server need to answer something.

**Comment by benoit-canet** [comment]
I will rename this issue

**Comment by slivne** [comment]
@benoit-canet  does this crash scylla - if not I'll update it to high

**Comment by benoit-canet** [comment]
@slivne: I will write a specific test for this asap and tell you.

**Comment by benoit-canet** [comment]
@slivne I sent you the malformed PR to reproduce this

**Comment by benoit-canet** [comment]
dtest produce no coredump at all but I think the test case I provided make it easy to reproduce this bug.

**Comment by slivne** [comment]
@benoit-canet dtest does not block core creation

if you set ulimit -c unlimited (not that its really needed as scylla is limited to 512M) then a core file will be created.

**Comment by slivne** [comment]
@benoit-canet lets enable the dtest
