### ISSUE TITLE
Add a way of determining if the client is batch or interactive

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#8095]
Batch (OLAP) and interactive (OLTP) clients have different needs with regard to timeouts and overload prevention. With batch clients, it's preferred to let the query linger for a long time until completion, while interactive workloads generally prefer failing the request faster so that it can be retried. As for preventing overload, batch clients can usually be successfully throttled by delaying the responses, due to the fact that their concurrency is fixed. Preventing overloads from interactive clients boils down to shedding the requests as soon as possible, since their concurrency is assumed to be unbounded and thus delaying responses will only unnecessarily hold resources.
Since it's not easy to determine the workload type from requests themselves, we can allow the users to explicitly declare what type of workload they expect - e.g. by configuring a matching workload type to a service level and then attaching this service level to appropriate roles. 

Spin-off from https://github.com/scylladb/scylla/pull/7867/

**Comment by slivne** [comment]
@psarna can we close this - I think you added a way to mark if workloads are one or the other

**Comment by psarna** [comment]
Yup; closed by 578543603d5aa42afcfa44b9c880754e60331332
