### ISSUE TITLE
Add overload protection mechanisms specific for interactive clients

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#8097]
Assuming that the client declared the current workload type (https://github.com/scylladb/scylla/issues/8095) as interactive (OLTP), there could be a specific path for overload protection just for this workload type. Namely, since client's concurrency is assumed to be unbounded, there's pretty much nothing else to do than shedding the requests as soon as first overload symptoms (e.g. latencies larger than the timeout threshold, large number of background operations, etc.) start to appear.

**Comment by slivne** [comment]
@psarna did we do this ?

**Comment by psarna** [comment]
Pretty much, here:
https://github.com/scylladb/scylla/blob/bae9c042c2b8e07c64cab49a4a099f815dbbf7f5/transport/server.cc#L581-L585

There are always ways to expand this mechanisms, but meanwhile I think it's safe to resolve this issue.
