### ISSUE TITLE
Select from system_schema.keyspaces failed

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#8110]
*Installation details*
Scylla version (or git commit hash): 4.4.rc1-0.20210131.fd868722d with build-id 81a1e1af8194f89648f0de52d16221ac170c539a
Cluster size: 6 nodes (i3.8xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-018aea1a9a4a9c867 (eu-west-1)

Test: `longevity-multi-keyspaces-60h-test`
Running Jenkins [job](https://jenkins.scylladb.com/view/scylla-4.4/job/scylla-4.4/job/longevity/job/longevity-multi-keyspaces-60h-test/2)

Test schema has 1000 keyspaces.
cqlsh command that select from `system_schema.keyspaces` from node1 failed without errors. Maybe by timeout

```
Command: 'cqlsh --no-color   --request-timeout=120 --connect-timeout=60  -e "select keyspace_name from system_schema.keyspaces" 10.0.1.62 9042'

Exit code: -1

Stdout:

Stderr:

```

No errors in the log

Test id: `d1acb699-673f-4cb1-82b1-1f6668d58450`

Get monitor:
```
hydra investigate show-monitor d1acb699-673f-4cb1-82b1-1f6668d58450
```

Logs upload failed. 
I trying to upload sct logs manually

**Comment by slivne** [comment]
We need more info we can't do anything with this info

**Comment by roydahan** [comment]
@juliayakovlev first we need logs.
@slivne what else do we need?

**Comment by juliayakovlev** [comment]
> @juliayakovlev first we need logs.
> @slivne what else do we need?

The logs were not uploaded due luck of space problem on the SCT runner. I copied SCT log to my laptop and try to upload it.

**Comment by juliayakovlev** [comment]
Unfortunately the logs archive is broken. So we have no logs.

**Comment by roydahan** [comment]
Let's close this issue.
We don't have the info and I also think it's not a real issue, it's just a
query that timed out.
