### ISSUE TITLE
After "DecommissionStreamingErr" nemesis all OPS drop to 0 

### ISSUE THREAD

**Issue by Orenef11** [scylladb/scylla#8115]
### Installation details
Scylla version (or git commit hash): `4.5.dev-0.20210211.718976e79 with build-id 4b8a664ea1165af17a0d8628323a57eb7d436534`
Cluster size: 6 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0f4dbf3c94e5ea5dc` (aws: eu-north-1)

Test: `longevity-alternator-3h-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-alternator-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/0d21beeb95740f69f66ef07af45df7d24a22b9d0/test-cases/longevity/longevity-alternator-3h.yaml)

## Issue Description

====================================
After the `DecommissionStreamingErr` nemesis is ran, all OPS operations drop to 0, and look like the cluster is stuck.

15 minutes after the nemesis is finished, the following errors are occurred (~100K errors):
* 2021-02-13 03:31:24.000: (DatabaseLogEvent Severity.ERROR): type=DATABASE_ERROR regex=Exception  line_number=105624 node=Node alternator-3h-master-db-node-d7e1ed6f-1 [13.53.122.51 | 10.0.0.185] (seed: True)
2021-02-13T03:31:24+00:00  alternator-3h-master-db-node-d7e1ed6f-1 !INFO    | scylla: [shard 7] rpc - client 10.0.1.213:58373 msg_id 1461876:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
* 2021-02-13 03:31:25.000: (DatabaseLogEvent Severity.ERROR): type=DATABASE_ERROR regex=Exception  line_number=105643 node=Node alternator-3h-master-db-node-d7e1ed6f-1 [13.53.122.51 | 10.0.0.185] (seed: True)
2021-02-13T03:31:25+00:00  alternator-3h-master-db-node-d7e1ed6f-1 !ERR     | scylla: [shard 7] paxos - CAS[178157] prune: failed exceptions::mutation_write_timeout_exception (Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE.)

The `DecommissionStreamingErr` steps:
* Wait until the streaming is started
* Execute hard reboot 
* Execute nodetool `decommission` command and wait for 60 seconds until is done
* Execute nodetool `status` command on `seed` node

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor d7e1ed6f-42eb-4ffd-aba2-9a3326acbead`
Show all stored logs command: `$ hydra investigate show-logs d7e1ed6f-42eb-4ffd-aba2-9a3326acbead`

Test id: `d7e1ed6f-42eb-4ffd-aba2-9a3326acbead`

### Logs
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/d7e1ed6f-42eb-4ffd-aba2-9a3326acbead/20210213_033142/grafana-screenshot-alternator-20210213_033815-alternator-3h-master-monitor-node-d7e1ed6f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/d7e1ed6f-42eb-4ffd-aba2-9a3326acbead/20210213_033142/grafana-screenshot-alternator-20210213_033815-alternator-3h-master-monitor-node-d7e1ed6f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/d7e1ed6f-42eb-4ffd-aba2-9a3326acbead/20210213_033142/grafana-screenshot-longevity-alternator-3h-test-scylla-per-server-metrics-nemesis-20210213_033531-alternator-3h-master-monitor-node-d7e1ed6f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/d7e1ed6f-42eb-4ffd-aba2-9a3326acbead/20210213_033142/grafana-screenshot-longevity-alternator-3h-test-scylla-per-server-metrics-nemesis-20210213_033531-alternator-3h-master-monitor-node-d7e1ed6f-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/d7e1ed6f-42eb-4ffd-aba2-9a3326acbead/20210213_033142/grafana-screenshot-overview-20210213_033142-alternator-3h-master-monitor-node-d7e1ed6f-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/d7e1ed6f-42eb-4ffd-aba2-9a3326acbead/20210213_033142/grafana-screenshot-overview-20210213_033142-alternator-3h-master-monitor-node-d7e1ed6f-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/d7e1ed6f-42eb-4ffd-aba2-9a3326acbead/20210213_071819/db-cluster-d7e1ed6f.zip](https://cloudius-jenkins-test.s3.amazonaws.com/d7e1ed6f-42eb-4ffd-aba2-9a3326acbead/20210213_071819/db-cluster-d7e1ed6f.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/d7e1ed6f-42eb-4ffd-aba2-9a3326acbead/20210213_071819/loader-set-d7e1ed6f.zip](https://cloudius-jenkins-test.s3.amazonaws.com/d7e1ed6f-42eb-4ffd-aba2-9a3326acbead/20210213_071819/loader-set-d7e1ed6f.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/d7e1ed6f-42eb-4ffd-aba2-9a3326acbead/20210213_071819/monitor-set-d7e1ed6f.zip](https://cloudius-jenkins-test.s3.amazonaws.com/d7e1ed6f-42eb-4ffd-aba2-9a3326acbead/20210213_071819/monitor-set-d7e1ed6f.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/d7e1ed6f-42eb-4ffd-aba2-9a3326acbead/20210213_071819/sct-runner-d7e1ed6f.zip](https://cloudius-jenkins-test.s3.amazonaws.com/d7e1ed6f-42eb-4ffd-aba2-9a3326acbead/20210213_071819/sct-runner-d7e1ed6f.zip)

### Snapshot
Per server metrics nemesis:
![grafana-screenshot-overview-20210213_033142-alternator-3h-master-monitor-node-d7e1ed6f-1](https://user-images.githubusercontent.com/11705430/108250792-5792c380-715f-11eb-8af7-3a9516de56e5.png)

Overview metrics
![grafana-screenshot-longevity-alternator-3h-test-scylla-per-server-metrics-nemesis-20210213_033531-alternator-3h-master-monitor-node-d7e1ed6f-1](https://user-images.githubusercontent.com/11705430/108250888-785b1900-715f-11eb-85e3-17ead432f22e.png)

Alternator metrics
![grafana-screenshot-alternator-20210213_033815-alternator-3h-master-monitor-node-d7e1ed6f-1](https://user-images.githubusercontent.com/11705430/108250911-81e48100-715f-11eb-8600-1a165b8b0373.png)

**Comment by Orenef11** [comment]
@fruch 
I know this is a known issue, but I could not find the bug number.

**Comment by Orenef11** [comment]
FYI @nyh

**Comment by fruch** [comment]
@Orenef11 why I he title says streams ? This doesn't sound like I has anything todo with alternator streams

**Comment by Orenef11** [comment]
> @Orenef11 why I he title says streams ? This doesn't sound like I has anything todo with alternator streams

Fixed.

**Comment by slivne** [comment]
@Orenef11 / @fruch 

What we are missing in the description is what clients are running

Do you have something pushing data into the cluster - what errors did it get - the client ?

Do you have an app reading the streams from the cluster - what errors did it get ?

It seems you have both CQL and Alternator traffic on the cluster - is that true ? (CQL metrics show reads and writes)

**Comment by fruch** [comment]
> @Orenef11 / @fruch
> 
> What we are missing in the description is what clients are running
in this test case we are doing both CQL and alternator at the same time
> 
> Do you have something pushing data into the cluster - what errors did it get - the client ?
I don't know yet which was before what, but the node was still in UJ (up joining) when that nemesis finished.
(my gut feeling would say it has nothing todo with alternator)
> 
> Do you have an app reading the streams from the cluster - what errors did it get ?
the title is misleading, it not related to alternator streams at all, it's part of @Orenef11 master duty
> 
> It seems you have both CQL and Alternator traffic on the cluster - is that true ? (CQL metrics show reads and writes)
yes that's correct for the test case.

**Comment by Orenef11** [comment]
> @Orenef11 / @fruch
> 
> What we are missing in the description is what clients are running

The test run CQL and YCSB stress commands
```
prepare_write_cmd:
  - >-
    bin/ycsb load dynamodb -P workloads/workloadc -threads 80 -p recordcount=6990500
    -p fieldcount=10 -p fieldlength=512 -p dataintegrity=true
    -p insertstart=0 -p insertcount=3495250
  - >-
    bin/ycsb load dynamodb -P workloads/workloadc -threads 80 -p recordcount=6990500
    -p fieldcount=10 -p fieldlength=512 -p dataintegrity=true
    -p insertstart=3495250 -p insertcount=3495250
  - >-
    bin/ycsb load dynamodb -P workloads/workloadc -threads 80 -p recordcount=6990500
    -p fieldcount=10 -p fieldlength=512 -p dataintegrity=true
    -p insertstart=0 -p insertcount=3495250 -p table=usertable_no_lwt
  - >-
    bin/ycsb load dynamodb -P workloads/workloadc -threads 80 -p recordcount=6990500
    -p fieldcount=10 -p fieldlength=512 -p dataintegrity=true
    -p insertstart=3495250 -p insertcount=3495250 -p table=usertable_no_lwt
  - cassandra-stress write cl=QUORUM n=6990500 -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=80 -pop seq=1..6990500 -col 'n=FIXED(10) size=FIXED(512)' -log interval=5

stress_cmd: [
  "cassandra-stress write cl=QUORUM duration=180m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=20 -pop seq=1..6990500 -col 'n=FIXED(10) size=FIXED(512)' -log interval=5",
  "cassandra-stress read  cl=QUORUM duration=180m -schema 'replication(factor=3) compaction(strategy=SizeTieredCompactionStrategy)' -port jmx=6868 -mode cql3 native -rate threads=20 -pop seq=1..6990500 -col 'n=FIXED(10) size=FIXED(512)' -log interval=5",
  # with lwt table
  "bin/ycsb run dynamodb -P workloads/workloadc -threads 20 -p readproportion=0.5 -p updateproportion=0.5 -p recordcount=6990500 -p fieldcount=10 -p fieldlength=512 -p operationcount=200200300 -p dataintegrity=true -p maxexecutiontime=10800",
  # no lwt table
  "bin/ycsb run dynamodb -P workloads/workloadc -threads 20 -p readproportion=0.5 -p updateproportion=0.5 -p recordcount=6990500 -p fieldcount=10 -p fieldlength=512 -p operationcount=200200300 -p dataintegrity=true -p table=usertable_no_lwt -p maxexecutiontime=10800",
]
```


> Do you have something pushing data into the cluster - what errors did it get - the client ?

After the `DecommissionStreamingErr` nemesis is finished, the node was still on `UJ` status, but after that I saw only YCSB errors...

> Do you have an app reading the streams from the cluster - what errors did it get ?

I think I was confused and the problem is not related to the stream.

I'm closing the bug, it's probably a problem of `SCT` and not of `Scylla`. 
I'm sorry for the confusion.
