### ISSUE TITLE
Repairing a table with TWCS potentially cause high number of parallel compaction

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#8124]
It was observed that after repairing a table with TWCS, tons of small sstables are created (data segregation makes it worse), and that caused a high number of parallel compactions. Turns out compaction manager is allowing many small jobs of varying sizes to proceed in parallel, potentially consuming lots of resources.

**Comment by raphaelsc** [comment]
Patch sent to mailing list, titled as "compaction_manager: Redefine weight for better control of parallel compactions"

**Comment by avikivity** [comment]
Already in 4.4. Since it's not a regression, will not backport further.

**Comment by gnumoreno** [comment]
@avikivity @raphaelsc @tzach 

This is in the release notes for 2020.1.8 

Can you confirm it made it into the 2020.1.8?

**Comment by avikivity** [comment]
We don't discuss scylla enterprise on this bug tracker.

**Comment by gnumoreno** [comment]
Well, it is in the enterprise release notes. I'm just asking for confirmation. 

https://www.scylladb.com/product/release-notes/scylla-enterprise-2020-1-8/

**Comment by avikivity** [comment]
We don't discuss scylla enterprise on this bug tracker.
