### ISSUE TITLE
Need to tune aio-max-nr based on the number of cpus

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8133]
Current aio-max-nr is set up statically to `1048576` in https://github.com/scylladb/scylla/blob/master/dist/common/sysctl.d/99-scylla-aio.conf
This is sufficient for most use cases (and an overkill for machines with few cpus), but falls short on larger machines such as `i3en.24xlarge` that has 96 vCPUs (See https://aws.amazon.com/ec2/instance-types/i3en/).

ATM, we allocate 11026 aio slots per shard (10000 + 1024 + 2, see https://github.com/scylladb/scylla-pkg/issues/1867).
So 96 vCPUs require at least 1058496 slots in max-aio-nr.

**Comment by bhalevy** [comment]
Cc @syuu1228 @penberg

**Comment by bhalevy** [comment]
@scylladb/scylla-maint Based on conversation on slack with @pveentjer, please backport.

**Comment by avikivity** [comment]
Backported, but don't we lose the configuration for iotune now?

**Comment by avikivity** [comment]
@bhalevy ping

**Comment by bhalevy** [comment]
> Backported, but don't we lose the configuration for iotune now?

@avikivity I didn't follow your line of thought.
Can you please explain why the changes here would cause losing the configuration for iotune?

**Comment by avikivity** [comment]
scylla_prepare works for scylla but not for iotune.
