### ISSUE TITLE
Node was overloaded: Too many in flight hints during Enospc nemesis

### ISSUE THREAD

**Issue by Orenef11** [scylladb/scylla#8137]
### Installation details
Scylla version (or git commit hash): `4.5.dev-0.20210216.2f3b265da with build-id 6a7412abfaf73ef877a8e6ae22759227e89cac13`
Cluster size: 4 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0208ab84477ace351` (aws: eu-north-1)

Test: `longevity-200gb-48h`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/162e8df658f9f31dbfac1463d9bf6e74dde3b88f/test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml)

### Issue description

The `Enospc` nemesis started `2021-02-19 06:43:27` until `2021-02-19 06:46:44` on `node2` (10.0.2.41)
Around `06:45:30`, the hint of `node1` (10.0.3.227) and `node3` (10.0.3.117) "jump" to 1.3M until 07:18:30.
Then, the hint value for node3 decreased.
But, the value for node1 kept "jumping" and growing until it reached 3.137M around 08:31:20 (also this time when the "write stress" is failed)

The nemesis that ran:
* HardRebootNode - Node longevity-200gb-48h-verify-limited--db-node-315b5d00-4 [13.53.173.63 \| 10.0.1.95] (seed: False) | 2021-02-19 06:07:54 | 2021-02-19 06:12:18  (264 seconds)
* Enospc - Node longevity-200gb-48h-verify-limited--db-node-315b5d00-2 [13.51.48.80 | 10.0.2.41] (seed: False)	2021-02-19 06:43:27	2021-02-19 06:46:44	(197 seconds)
* HardRebootNode - Node longevity-200gb-48h-verify-limited--db-node-315b5d00-3 [13.49.224.114 | 10.0.3.117] (seed: False)	2021-02-19 07:17:49	2021-02-19 07:22:31	(282 seconds)
* HardRebbotNemesis - Node longevity-200gb-48h-verify-limited--db-node-315b5d00-2 [13.51.48.80 | 10.0.2.41] (seed: False)	2021-02-19 07:53:32	2021-02-19 07:58:09	(276 seconds)
* Drainer - Node longevity-200gb-48h-verify-limited--db-node-315b5d00-3 [13.49.224.114 | 10.0.3.117] (seed: False)	2021-02-19 08:29:23	2021-02-19 08:31:50	(147 seconds)
* Drainer - Node longevity-200gb-48h-verify-limited--db-node-315b5d00-2 [13.51.48.80 | 10.0.2.41] (seed: False)	2021-02-19 09:35:33	2021-02-19 09:37:49	(136 seconds)
* StopStartService - Node longevity-200gb-48h-verify-limited--db-node-315b5d00-4 [13.53.173.63 | 10.0.1.95] (seed: False)	2021-02-19 09:02:29	2021-02-19 09:04:54	(144 seconds)

![image](https://user-images.githubusercontent.com/11705430/108713864-79a29200-7521-11eb-97c2-1ed00ec37509.png)
====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 315b5d00-8a9b-4c2d-b6df-ab90742baeef`
Show all stored logs command: `$ hydra investigate show-logs 315b5d00-8a9b-4c2d-b6df-ab90742baeef`

Test id: `315b5d00-8a9b-4c2d-b6df-ab90742baeef`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/315b5d00-8a9b-4c2d-b6df-ab90742baeef/20210221_054627/grafana-screenshot-longevity-200gb-48h-scylla-per-server-metrics-nemesis-20210221_055010-longevity-200gb-48h-verify-limited--monitor-node-315b5d00-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/315b5d00-8a9b-4c2d-b6df-ab90742baeef/20210221_054627/grafana-screenshot-longevity-200gb-48h-scylla-per-server-metrics-nemesis-20210221_055010-longevity-200gb-48h-verify-limited--monitor-node-315b5d00-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/315b5d00-8a9b-4c2d-b6df-ab90742baeef/20210221_054627/grafana-screenshot-overview-20210221_054627-longevity-200gb-48h-verify-limited--monitor-node-315b5d00-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/315b5d00-8a9b-4c2d-b6df-ab90742baeef/20210221_054627/grafana-screenshot-overview-20210221_054627-longevity-200gb-48h-verify-limited--monitor-node-315b5d00-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/315b5d00-8a9b-4c2d-b6df-ab90742baeef/20210221_055510/db-cluster-315b5d00.zip](https://cloudius-jenkins-test.s3.amazonaws.com/315b5d00-8a9b-4c2d-b6df-ab90742baeef/20210221_055510/db-cluster-315b5d00.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/315b5d00-8a9b-4c2d-b6df-ab90742baeef/20210221_055510/loader-set-315b5d00.zip](https://cloudius-jenkins-test.s3.amazonaws.com/315b5d00-8a9b-4c2d-b6df-ab90742baeef/20210221_055510/loader-set-315b5d00.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/315b5d00-8a9b-4c2d-b6df-ab90742baeef/20210221_055510/monitor-set-315b5d00.zip](https://cloudius-jenkins-test.s3.amazonaws.com/315b5d00-8a9b-4c2d-b6df-ab90742baeef/20210221_055510/monitor-set-315b5d00.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/315b5d00-8a9b-4c2d-b6df-ab90742baeef/20210221_055510/sct-runner-315b5d00.zip](https://cloudius-jenkins-test.s3.amazonaws.com/315b5d00-8a9b-4c2d-b6df-ab90742baeef/20210221_055510/sct-runner-315b5d00.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-200gb-48h/102/)
Last events by severity

ERROR - [2]
2021-02-19 08:30:04.354: (CassandraStressLogEvent Severity.ERROR): type=IOException regex=java\.io\.IOException line_number=10127 node=Node longevity-200gb-48h-verify-limited--loader-node-315b5d00-1 [13.53.122.97 | 10.0.1.87] (seed: False)
java.io.IOException: Operation x10 on key(s) [3238384b503733303731]: Error executing: (OverloadedException): Queried host (10.0.2.41/10.0.2.41:9042) was overloaded: Too many in flight hints: 10486980

Links:
Build URL
Download "Per server metrics nemesis" Grafana Screenshot
Download "Overview metrics" Grafana Screenshot
Grafana Screenshots:

**Comment by roydahan** [comment]
@piodul can you please help us investigate this issue.
What information will help to understand the cause of it?
It's the first time we see this issue in this test.

**Comment by roydahan** [comment]
I don't think it's related to ENOSPC nemesis.
I'm seeing the same behaviour in the write throughput test.

I think this behaviour started between these commits:

git lg e1261d10f..d8345c67d
* d8345c67d - Consolidate system and non system keyspace creation (13 days ago) <Gleb Natapov>
* 51037e94e - lwt: handle an error during prune operation (13 days ago) <Gleb Natapov>
*   3dd9c5596 - Merge 'Minor tweaks to the failure detector interface' from Piotr Sarna (13 days ago) <Tomasz Grabiec>
|\
| * faca59efa - failure_detector: add getting last update time point (2 weeks ago) <Piotr Sarna>
| * d23584c8f - failure_detector: return arrival samples by const reference (2 weeks ago) <Piotr Sarna>
| * 445e6e44f - failure_detector: remove unimplemented is_alive method (2 weeks ago) <Piotr Sarna>
*   4acc6fecf - Merge 'locator: Check DC names in NetworkTopologyStrategy' from Juliusz Stasiewicz (13 days ago) <Piotr Sarna>
|\
| * 97bb15b2f - tests: Adjusted tests for DC checking in NTS (13 days ago) <Juliusz Stasiewicz>
| * b6fb5ee91 - locator: Check DC names in NTS (13 days ago) <Juliusz Stasiewicz>
* 3d001b558 - query: use local limit for non-limited queries in mixed cluster (13 days ago) <Botond Dénes>
* 2f50bf202 - Update seastar submodule (13 days ago) <Avi Kivity>
* 37b41d776 - test: add missing #include <fstream> (13 days ago) <Avi Kivity>
* c16e4a042 - migration_manager: Propagate schema changes with reads like we do on writes (2 weeks ago) <Tomasz Grabiec>
*   4082f57ed - Merge 'Make commitlog disk limit a hard limit.' from Calle Wilund (2 weeks ago) <Avi Kivity>
|\
| * 4be718ebf - commitlog: Force earlier cycle/flush iff segment reserve is empty (6 weeks ago) <Calle Wilund>
| * be8c359a6 - commitlog: Make segment allocation wait iff disk usage > max (6 weeks ago) <Calle Wilund>
| * ab55a1b4e - commitlog: Do partial (memtable) flushing based on threshold (6 weeks ago) <Calle Wilund>
| * 7c84b16cd - commitlog: Make flush threshold configurable (7 weeks ago) <Calle Wilund>
| * c3d95811d - table: Add a flush RP mark to table, and shortcut if not above (7 weeks ago) <Calle Wilund>
* af2d1fa0d - Update abseil submodule (2 weeks ago) <Avi Kivity>
* b9a5aff7a - distributed_loader: drop execute_futures function (2 weeks ago) <Gleb Natapov>
* a05adb853 - database: Remove global storage proxy reference (2 weeks ago) <Pavel Emelyanov>
* 8490c9ff6 - transport: Remove global storage service reference (2 weeks ago) <Pavel Emelyanov>
* 4498bb0a4 - API: Fix aggregation in column_familiy (2 weeks ago) <Amnon Heiman>

**Comment by roydahan** [comment]
It also happened on longevity-50gb-3d and short longevities.

**Comment by piodul** [comment]
@roydahan `OverloadedException` usually indicates that the node does not keep up with saving hints to disk. When Scylla waits while it flushes hints to disk, it dismisses all writes which could generate more hints with `OverloadedException` (in this case - most writes when one of the nodes is down or unresponsive). Due to the way cassandra-stress reacts to this exception, there is a small chance on every exception received that it will stop with an error - just like what happened here.

The situation should improve when https://github.com/scylladb/scylla/issues/8139 gets implemented - we will start applying throttling before returning an exception. Cassandra-stress should no longer stop with error during this test, but the performance might drop because hints are a bottleneck.

**Comment by piodul** [comment]
The "Make commitlog disk limit a hard limit." PR might also have had an effect here - hinted handoff use the commitlog framework to save hints to disk.

**Comment by roydahan** [comment]
@piodul the thing is that something regressed in Scylla in the last two weeks and now we hit this OverloadedException on all our tests after 20210205.

**Comment by slivne** [comment]
@piodul we will do a bisect.

**Comment by piodul** [comment]
I think it is caused by the commit I mentioned in my previous comment.

When the commitlog reaches its size limit, it now blocks and waits until some segments are freed. Hinted handoff does not free segments at all, instead it re-creates the commitlog every 10 seconds. On each re-creation the new commitlog is set to have max size of 128MB / shard_count, which now effectively limits hint writing speed to 12.8MB/s, _on all shards in total_ per node. Previously, the limit was soft so we could go over it.

I can make the size limit larger, in a smart way (we measure the size of the commitlog segments left on disk, so we can set it to `(space limit for hints) - (size of segments left by previous instances of the commitlog)`). In the long term, though, I think we should create a separate class for storing hints - we had a discussion about it on the mailing list some time ago. I'll create an issue.

cc: @haaawk @vladzcloudius @elcallio

**Comment by vladzcloudius** [comment]
> I think it is caused by the commit I mentioned in my previous comment.
> 
> When the commitlog reaches its size limit, it now blocks and waits until some segments are freed. Hinted handoff does not free segments at all, instead it re-creates the commitlog every 10 seconds. On each re-creation the new commitlog is set to have max size of 128MB / shard_count, which now effectively limits hint writing speed to 12.8MB/s, _on all shards in total_ per node. Previously, the limit was soft so we could go over it.
> 
> I can make the size limit larger, in a smart way (we measure the size of the commitlog segments left on disk, so we can set it to `(space limit for hints) - (size of segments left by previous instances of the commitlog)`). 

That would make sense if it's a hard limit now.

**Comment by slivne** [comment]
So we are doing the bisect 

roy ran a test with 4082f57ed  (commit log change) and it showed bad results

We will run the test with the previous commit just to double check ...

**Comment by roydahan** [comment]
4082f57ed is the suspected commit that caused the regression.

The result for af2d1fa0d is a good result.

**Comment by slivne** [comment]
Ok we have a confirmation that the commitlog size hard limit is the cause, can we have this "flexible limit" / "hard limit" configurable:
- HH using flexible
- commitlog using the hard

**Comment by piodul** [comment]
Sent a patch.

Actually, the problem was more serious: when hints commitlog gets filled up, the logic responsible for recreating the hints commitlog gets stuck in a deadlock (hints waiting to be written hold `file_update_mutex` in shared mode, and commitlog recreation logic needs to acquire it in exclusive mode). No more hints are admitted and the node soon rejects all writes which would generate a hint with an OverloadedException, because the `hints_in_progress` metric is not decreased for hints which are stuck.

Additionally, if a hints queue gets stuck like this, stopping hints manager will also get stuck and the node won't be able to shut down.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
