### ISSUE TITLE
Print key scylla metrics to log

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#814]
On many cases, in particular on testing and evaluation, one (me in this case) does not want to run a dedicate monitoring service like [scylla-monitoring](https://github.com/scylladb/scylla-monitoring)
Still, knowing the key metrics is very useful to understand the system status, and useful when a user report an issue.
I suggest to write each of the following value to log every 10 sec.

Key Metric list:
- reactor.gauge-load
- transport.total_requests-requests_served
- storage_proxy.total_operations-write.timeouts
- storage_proxy.total_operations-read.timeouts
- disk-sda.disk_octets.read
- disk-sda.disk_ops.read
- netlink-int0.if_octets.tx
- netlink-int0.if_octets.rx
- cache.total_operations-hits
- cache.total_operations-misses

**Comment by tgrabiec** [comment]
If we had an API to query collectd counters, this functionality could be covered by an external script. Advantage of having an external script is that it gives you more flexibility and can be changed independently than a built-in code in scylla.

**Comment by tzach** [comment]
> If we had an API to query collectd counters, this functionality could be covered by an external script. 

Both API and script will be useful, but not a necessarily a replacement.
Are you suggesting running the second it on every Scylla machine?
Its yet another moving part which is not always there.

**Comment by amnonh** [comment]
we do have an api for collectd

**Comment by avikivity** [comment]
We have an API, it's called collectd.

It can be as simple as running a collectd server on the node, and defaulting scylla to point the collectd address at the node itself, and configuring the period to 10 seconds.

**Comment by tgrabiec** [comment]
@avikivity Yes, but it requires a lot of not-so-obvious configuration and starting additional daemons. For ad-hoc snooping, firing up `scylla-top.py` is easier.

**Comment by tzach** [comment]
> ad-hoc snooping, firing up scylla-top.py is easier.

Yes, such scylla-top.py  will be super useful. It does not require to change scylla option or restart the process.
Logging key metric to journal every 10 sec is also useful for postmortem.

**Comment by avikivity** [comment]
We can drop a /etc/collectd.d/scylla.conf as part of our packaging.  scylla-top can then be a wrapper around collectdctl.

**Comment by tzach** [comment]
@avikivity why adding yet another moving part? in addition to have one more process to maintain, scylla will need to report to two collectd server, one internal and one for system wide.

**Comment by avikivity** [comment]
It already exists.  We don't need two collectd addresses, if the user provides their own we don't set up ours.

We can have a scylla-collectd package that pulls in collectd and configures it (and also configures scylla to talk to it).

**Comment by tzach** [comment]
> It already exists. We don't need two collectd addresses, if the user provides their own we don't set up ours.

This is limiting. Why stopping the reports to a global collectd for investigating locally?

> We can have a scylla-collectd package that pulls in collectd and configures it (and also configures scylla to talk to it).

Updating the configuration to local and than back to global once you are done? look error prune to me.

**Comment by avikivity** [comment]
If you have a global collector, use it.  If not use the local collector.  No need to stop anything to switch configuration.

**Comment by avikivity** [comment]
Another option is to provide a [pcp](http://pcp.io) interface instead of collectd (or maybe together).  That provides a gui and is pull-based instead of push.

**Comment by tzach** [comment]
> If you have a global collector, use it. If not use the local collector. No need to stop anything to switch configuration.

You are posing an unnecessary restriction without a good reason. User may need to run both, I know I did when I lost metrics on the monitoring system.
Pull base bypass thous issues. 
Between scylla-top.py or pcp I prefer the first because it is simpler, and does not require open an extra port for HTTP, or have a public IP.

**Comment by dorlaor** [comment]
AFAIK collectd can run as a local daemon and can forward it to an external
one.
In this mode, Scylla will *always* send metrics to a local daemon which
scylla-top.py
can pull the data and in addition, anyone who wants to send the metrics
outside to graphite
will configure the local, standard collectd to forward

**Comment by avikivity** [comment]
A scylla-top.py will require some interface to Scylla, it can't guess the values.

We already have a metrics interface, we can use it without a lot of effort, it's just configuration files and systemd dependencies.

**Comment by avikivity** [comment]
@dorlaor good idea

**Comment by tgrabiec** [comment]
Does collectd expose a pull interface?

One problem with relying on pulling from collectd is that the pull period passed to scylla-top would be out of sync with the age of metrics. Eg. scylla may be configured to send all metrics once every 10 seconds, but I wont to snoop some metric once every second.

**Comment by avikivity** [comment]
I don't think so, but does why do you care if scylla-top polls once a second?

**Comment by tgrabiec** [comment]
The more accuracy the better. If you poll once every 10 seconds, you don't see how the workload changed in those 10 seconds. The metrics could change steadily or have spikes, it's useful information.

I think it's also important for scylla-top user to know what's the actual refresh period for the data and when data is refreshed (from scylla, not just from intermediary). If it shows 0 tps/s for 10 seconds, I need to know if the server really has been idle for 10 seconds or it's just been showing me stale data.

**Comment by avikivity** [comment]
There is no way to do this with collectd.  It comes for free with pcp (it is a pull model).

We could add an extra statistics API, but if we do, we should use an existing one, not add an ad-hoc API.

**Comment by slivne** [comment]
We have the solution of sending info to local collected and having scylla-top to provide info of that - we can extract the info of interval update from scylla config / command line if needed - lets start with a default 1 or 3 seconds and see if this is informative enough.

**Comment by avikivity** [comment]
We can configure rrd as well.

**Comment by avikivity** [comment]
Making the log behave like a metrics database will make it unusable for its original purpose. Suggest closing.

**Comment by amnonh** [comment]
I suggest statd instead

**Comment by avikivity** [comment]
The log is already overused, closing.
