### ISSUE TITLE
protocols.md: need to document shard-aware native transport

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8146]
The `docs/design-notes/protocols.md` contains extensive documentation on all the different ports that Scylla opens and protocols it uses over them, and how these ports can be changed or disabled. In the "CQL client protocol" section we neglected to mention the existence of shard-aware clients, which use a different port (see commit 1c11d8f4c40067c95f8ddea42b0d41e40d40fe97) and can be disabled `enable_shard_aware_drivers` (see commit 5f94bc902a255ec4f31046b9205d2148c6cb39d4).

Some of the details of the shard-awareness extension to CQL probably belong in `protocol-extensions.md`, but at least the gits and the different configuration options and default port numbers definitely belong in `protocols.md`.

**Comment by avikivity** [comment]
Documentation only; not backporting.
