### ISSUE TITLE
row_cache_test: fatal error: in "test_random_partition_population": Mutations differ

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8151]
Stumbled upon this and reproduced with scylla version fb1d3fe2cf41a72190846dde85e3ebd00e6eb4b3
and `random-seed=4038378822`

Command used:
```
build/release/test/boost/row_cache_test --catch_system_errors=no --color_output=false -- -c2 -m2G --overprovisioned --unsafe-bypass-fsync 1 --blocked-reactor-notify-ms 2000000 --collectd 0 --default-log-level=warn --random-seed=4038378822
```
It looks like we get unexpected range_tombstones.

```diff
bhalevy@dt scylla$ diff -u /tmp/{expected,got}
--- /tmp/expected	2021-02-24 16:17:14.237387038 +0200
+++ /tmp/got	2021-02-24 16:17:57.397774893 +0200
@@ -1,3 +1,6 @@
+ ...but got:
+ {table: 'ks.cf', key: {'pk': 1806000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000, token: -9205109811216406580}, mutation_partition: {
+  range_tombstones: {
     {range_tombstone: start={bound: prefix=ckp{00800001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000}, kind=incl start}, end={bound: prefix=ckp{008004070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080b500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000}, kind=excl end}, {tombstone: timestamp=-9223372036854775807, deletion_time=0}},
     {range_tombstone: start={bound: prefix=ckp{008004070000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080b500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000}, kind=incl start}, end={bound: prefix=ckp{00800d06000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000}, kind=excl end}, {tombstone: timestamp=-9223372036854775806, deletion_time=0}},
     {range_tombstone: start={bound: prefix=ckp{00800d06000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000}, kind=incl start}, end={bound: prefix=ckp{0080ed01000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000}, kind=incl end}, {tombstone: timestamp=-9223372036854775805, deletion_time=2}},
@@ -1376,3 +1379,4 @@
   ]
 }
 }
+test/boost/row_cache_test.cc(0): Leaving test case "test_random_partition_population"; testing time: 9823us
```

full log: [row_cache_test.log.gz](https://github.com/scylladb/scylla/files/6036579/row_cache_test.log.gz)

**Comment by xemul** [comment]
Started failing somewhere between 71398f3fb4ea44cccd49c3a6e295b055062ec2c5 & bc64ee54103a7c043f3dba64117909a7e64ad451 . Will bisect.

**Comment by xemul** [comment]
eb861e68e9eab94b29a95037b01ee52a8d77aa51 is the first bad commit
commit eb861e68e9eab94b29a95037b01ee52a8d77aa51
Author: Avi Kivity <avi@scylladb.com>
Date:   Mon Nov 2 11:31:39 2020 +0200

    build: switch to clang as the default compiler
    
    Clang brings us working support for coroutines, which are
    needed for Raft and for code simplification.
    
    perf_simple_query as well as full system tests show no
    significant performance regression.
    
    Test: unit(dev, release, debug)
    
    Closes #7531

 configure.py | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

**Comment by xemul** [comment]
To reproduce I applied

````
diff --git a/test/lib/mutation_source_test.cc b/test/lib/mutation_source_test.cc
index a0023479c..68b54f997 100644
--- a/test/lib/mutation_source_test.cc
+++ b/test/lib/mutation_source_test.cc
@@ -1692,7 +1692,7 @@ class random_mutation_generator::impl {
     generate_uncompactable _uncompactable;
     const size_t _external_blob_size = 128; // Should be enough to force use of external bytes storage
     const size_t n_blobs = 1024;
-    const column_id column_count = row::max_vector_size * 2;
+    const column_id column_count = 64;
     std::mt19937 _gen;
     schema_ptr _schema;
     std::vector<bytes> _blobs;
@@ -1733,7 +1733,7 @@ class random_mutation_generator::impl {
     explicit impl(generate_counters counters, local_shard_only lso = local_shard_only::yes,
             generate_uncompactable uc = generate_uncompactable::no) : _generate_counters(counters), _local_shard_only(lso), _uncompactable(uc) {
         // In case of errors, reproduce using the --random-seed command line option with the test_runner seed.
-        auto seed = tests::random::get_int<uint32_t>();
+        auto seed = 3549727099;//tests::random::get_int<uint32_t>();
         std::cout << "random_mutation_generator seed: " << seed << "\n";
         _gen = std::mt19937(seed);
````

and checked the `./build/dev/test/boost/row_cache_test -t test_random_partition_population  -- -c1 -m2G  --blocked-reactor-notify-ms 2000000`

**Comment by xemul** [comment]
Confirmed. When on commit eb861e6 compiling with clang makes the test fail, compiling with g++ makes the test pass.

**Comment by bhalevy** [comment]
Interesting.  And debug mode doesn't come up with any ASAN issue either.

By the way, I investigated a dtest issue, where we run out of lsa memory, and bisected it, *in dev mode* to 4fd5ef92ae61e234090779ced46f0dae8346eb28.  I presumed it's related to difference in memory layout, but now I wonder if it could be caused by code generation.

**Comment by xemul** [comment]
It's even more intererting. I now see that at the given commit the inequality operator for mutations reports true (mutations not equal), while printing them both shows no difference! However at some further commit the difference actually shows up -- one of the row's tombstone is lost in the output. But I haven't yet bisected where exactly it gets lost.

**Comment by psarna** [comment]
@xemul maybe related? https://github.com/scylladb/scylla/issues/8221#issuecomment-791337591

**Comment by xemul** [comment]
@psarna , yes. The 2nd issue is exactly this -- missing tombstone printing. Now I have 1 left: why changing the compiler makes the test pass.

**Comment by psarna** [comment]
@xemul that's a long shot, but could you also try clang++ with reduced inline-threshold (in configure.py)? Avi and I experienced bugs like that already, it was a coroutine miscompilation both times. In my case, lowering the inline-threshold to 50 made the code work.

**Comment by xemul** [comment]
@psarna , AFAIS the inline threshold applies only to release builds, while I'm seeing this on dev.

**Comment by denesb** [comment]
> @psarna , yes. The 2nd issue is exactly this -- missing tombstone printing. Now I have 1 left: why changing the compiler makes the test pass.

Fixed in debaae41f.

**Comment by xemul** [comment]
OK, compiler-changing mystery solved.

Gcc vs Clang may evaluate values for a single expression in different order. This becomes critical when values are results of pseudo-random generator calls -- two comlied binaries effectively work with different data.

E.g., if doing call like `foo(random(), random(), random())`, then two different compilations will result in `foo` called with arguments in different (reversed) order. Eventualy this will produce two different mutation sets.

The exact symthoms of failure with the given seed (on clang) match those from #8221, so I propose closing this one as duplicate.

**Comment by bhalevy** [comment]
Duplicate of #8221
