### ISSUE TITLE
scylla_setup: set XFS block size to 1k

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#8156]
fScylla commit log writes are aligned to the filesystem block size. This has to be done for XFS because of poor XFS concurrency for sub-block-size writes in direct io mode, see https://www.spinics.net/lists/linux-fsdevel/msg186825.html 

This defaults to commit log write size being at least 4k. If commit log is used in sync mode, e.g. for LWT, this leads to significant write amplification, when most of the written block contents is zero bytes. Significant write amplification, in turn, leads to excessive recycle of commit log segments, and, since the commit log size in a typical Scylla set up is limited with total available RAM size, it also leads to excessive work on flushing memtables (to be able to reuse commit log segments quickly) and compaction.

The suggestion is to reduce the default XFS block size to 1kb if disk sector size is less or equal to that (a typical sector size nowadays is 512 bytes) when preparing the disk for Scylla.

The write amplification measurements show that this can lead to 25% reduction in total writes for the classical cassandra-stress LWT benchmark.

The impact to non-LWT workload should be negligible, but must be measured.

See also: 

https://github.com/scylladb/scylla/issues/7663
https://github.com/scylladb/scylla/issues/7664

**Comment by raphaelsc** [comment]
@kostja  after XFS gets rid of serialization for sub-block write on written extent, it seems to me write amplification will be reduced even further. correct? looks like this behavior will be supported on kernels >= 5.12

**Comment by kostja** [comment]
Yes, but we will see kernels >= 5.12 only in a year or two, and we will also need to patch commit log code to support 512-byte block size.

**Comment by raphaelsc** [comment]
> Yes, but we will see kernels >= 5.12 only in a year or two, and we will also need to patch commit log code to support 512-byte block size.

Avi worked on seastar patch "file: expose disk offset alignment for overwrites", which introduces an alignment that can be used in commitlog. for kernels >= 5.12, it will be 512 bytes. so in a couple of months, users, who are fast adopters or really need it so they'll accept the risk, will benefit quickly from the change.

**Comment by avikivity** [comment]
> The suggestion is to reduce the default XFS block size to 1kb if disk segment size is less or equal to that (a typical segment size nowadays is 512 bytes) when preparing the disk for Scylla.

s/segment/sector/

Can be found in /sys/dev/block/{major}:{minor}/queue/logical_block_size.

**Comment by kostja** [comment]
Updated. Or with fdisk -l

**Comment by avikivity** [comment]
Not a bug; not backporting.
