### ISSUE TITLE
Wrong maximum number of batched statement

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#816]
From limit.py test.

    ======================================================================
    ERROR: max_batch_size_test (limits.TestLimits)
    ^Z----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/benoit/scylla-dtest/limits.py", line 198, in max_batch_size_test
        session.execute(c)
      File "cassandra/cluster.py", line 1602, in cassandra.cluster.Session.execute (cassandra/cluster.c:27334)
        result = future.result()
      File "cassandra/cluster.py", line 3347, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:65206)
        raise self._final_exception
    InvalidRequest: code=2200 [Invalid query] message="Batch too large"
    -------------------- >> begin captured logging << --------------------
    dtest: DEBUG: cluster ccm directory: /home/benoit/.dtest/dtest-alU7gq
    --------------------- >> end captured logging << ---------------------

    ======================================================================
    ERROR: max_batch_size_test (limits.TestLimits)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/benoit/scylla-dtest/dtest.py", line 594, in tearDown
        raise AssertionError('Unexpected error in %s node log: %s' % (node.name, errors))
    AssertionError: Unexpected error in node1 node log: ['ERROR [shard 0] BatchStatement - Batch of prepared statements for ks.stuff is of size 65535, exceeding specified threshold of 2000 by 63535. (see batch_size_fail_threshold_in_kb)']
    -------------------- >> begin captured logging << --------------------
    dtest: DEBUG: cluster ccm directory: /home/benoit/.dtest/dtest-alU7gq
    --------------------- >> end captured logging << ---------------------

current limit: 2k

should be:  63535

crash: no

**Comment by benoit-canet** [comment]
Update: max batch size is now 4095 with in bonus a new dtest error message.

    max_batch_size_test (limits.TestLimits) ... Testing max batch size for size=1
    Testing max batch size for size=3
    Testing max batch size for size=7
    Testing max batch size for size=15
    Testing max batch size for size=31
    Testing max batch size for size=63
    Testing max batch size for size=127
    Testing max batch size for size=255
    Testing max batch size for size=511
    Testing max batch size for size=1023
    Testing max batch size for size=2047
    Testing max batch size for size=4095
    Testing max batch size for size=8191
    ERROR

    ======================================================================
    ERROR: max_batch_size_test (limits.TestLimits)
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/home/benoit/scylla-dtest/limits.py", line 244, in max_batch_size_test
        self._do_test_max_batch_size(session, node, size - 1)
      File "/home/benoit/scylla-dtest/limits.py", line 229, in _do_test_max_batch_size
        self.assertEqual(len(res), count)
    TypeError: object of type 'PagedResult' has no len()
    -------------------- >> begin captured logging << --------------------
    dtest: DEBUG: cluster ccm directory: /home/benoit/.dtest/dtest-qK5NJw
    --------------------- >> end captured logging << ---------------------

    ----------------------------------------------------------------------
    Ran 1 test in 19.051s

    FAILED (errors=1)

**Comment by slivne** [comment]
@benoit-canet  why did you close this - does the test pass ?

For future reference can you include in an issue the git ref the issue was found on and the ref/commit the issue was closed

**Comment by benoit-canet** [comment]
The test now pass.

Either it was fixed in scylla or I used a too old version of scylla when
opening the issue.

**Comment by benoit-canet** [comment]
It has been fixed in 6a5f075107cb300ce71d2ca969375301876b3fae
