### ISSUE TITLE
multishard_reader: on_partition_range_change() pushes tokens for all shards unconditionally

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#8161]
`on_partition_range_change()` prepares the `_shard_selection_min_heap` according to the new partition range. `_shard_selection_min_heap` should contain the next token each shard is expected to produce data for in the given range. This is used to select the next shard to read from when the current shard runs out of data. When moving to a new partition range, the first partition a given shard will produce is not known, so the code speculatively selects the first token the shard owns in the given range as a substitute. However this algorithm is too eager and doesn't check if said token even belongs to the current read range. This can result in a tiny range consisting of a single token to scan all shards, when only a single one will have data.

**Comment by avikivity** [comment]
This is only a performance problem for queries that are unlikely to happen in production (but likely to happen when debugging), so not backporting.
