### ISSUE TITLE
unpaged query is terminated silently if it reaches global limit first

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#8162]
The `result_memory_accounter` terminates a query if it reaches either the global or shard-local limit. This used to be so only for paged queries, unpaged ones could grow indefinitely (until the node OOM'd). This was changed in fea5067df which checks the memory consumption of the query in `result_memory_accounter::check_local_limit()`. However this left a loophole in the code:
https://github.com/scylladb/scylla/blob/7bf0744d361e5e9186fa5591ea3f9f10a36e2b95/query-result.hh#L200-L210
If the hard limit in `check_local_limit()` is not tripped, there is a chance for the global limit to be tripped in the if, in which case the query is silently terminated, as if in the case of a paged query, except it will not contain all results, which is what the user expects in the case of an unpaged query.

**Comment by avikivity** [comment]
Backported to 4.3, 4.4. 4.2 was not vulnerable (@denesb please confirm).

**Comment by denesb** [comment]
> Backported to 4.3, 4.4. 4.2 was not vulnerable (@denesb please confirm).

Yes, 4.2 is not vulnerable.
