### ISSUE TITLE
False 1 second latency reported in I/O queue delay metrics

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#8166]
Some I/O queue delays are reported as 1 second, even though no such delay exists.

![image](https://user-images.githubusercontent.com/1017210/109171370-65150280-778a-11eb-9a53-7f55abe19b02.png)

**Comment by slivne** [comment]
@avikivity we need this backport to 4.4 - it suffers from this as well

**Comment by avikivity** [comment]
Backported to 4.2, 4.3, 4.4.
