### ISSUE TITLE
Potential data resurrection due to lack of synchronization in cleanup compaction

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#8168]
Data resurrection can happen if table T on node A still has non-owned data after cleanup finished, and that same node A regains ownership of that data in table T.

Node A, in the example above, can be left with non-owned data because:
1) memtable is not flushed prior to cleanup, so whatever non-owned data is in a memtable will eventually be flushed into an sstable (#1239).
2) cleanup doesn't wait for regular compaction, so it may miss any candidate containing non-owned data being currently compacted.

To fix them, we need to, respectively:
1) make sure memtable is flushed for a given table before starting cleanup on it (#1239)
2) wait for regular compaction(s) completion before finding candidates for cleanup, then these candidates will be marked as compacting by compaction manager and cannot be later picked as candidates by regular compaction.

**Comment by slivne** [comment]
Seems a dup of https://github.com/scylladb/scylla/issues/1239

**Comment by raphaelsc** [comment]
> Seems a dup of #1239

#1239 only covers the memtable part. this issue also asks for synchronization between cleanup and regular compaction, i'll reword the issue to reflect that. #8155 is now only limited to the regression in compaction manager.

**Comment by slivne** [comment]
We need to decide if we are aborting compaction or letting them end - some compactions can be very long (major compaction) - so aborting existing compactions maybe the less optimal but more correct thing todo

@avikivity please comment - so @raphaelsc can send a patch to fix this

**Comment by raphaelsc** [comment]
> We need to decide if we are aborting compaction or letting them end - some compactions can be very long (major compaction) - so aborting existing compactions maybe the less optimal but more correct thing todo
> 
> @avikivity please comment - so @raphaelsc can send a patch to fix this

ping

**Comment by slivne** [comment]
@raphaelsc / @bhalevy is this fixed ?

**Comment by raphaelsc** [comment]
> @raphaelsc / @bhalevy is this fixed ?

a couple of preparatory changes were done in compaction layer, i'll send a patch to fix this issue this week.

**Comment by slivne** [comment]
@raphaelsc ping

**Comment by avikivity** [comment]
@raphaelsc please prepare a backport for 4.6.

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
