### ISSUE TITLE
compact_sstables() is using steady clock's epoch to update compacted_at field of system.compaction_history

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#817]
The type of the column is `timestamp`, so we should use system clock's epoch (`db_clock`).

**Comment by tzach** [comment]
@tgrabiec what is the affect of this bug? what the worse scenario it can cause?

**Comment by tgrabiec** [comment]
@tzach The effect would be that timestamps in compaction history would appear incorrect. I am not sure if tools strongly depend on it or is it just informational to the user. @raphaelsc ?

**Comment by raphaelsc** [comment]
@tgrabiec: At the moment, it's only used as information to the user, which requests it via compaction history of nodetool. I will look at what else place C* uses it. Thanks for noticing the problem.
