### ISSUE TITLE
Improve the verbosity of errors coming from the view builder/updater

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#8177]
*Installation details*
HEAD: 0e0282cdf1b57c23354a3e356016bf33b6a8788a

*Description*
We need to improve the verbosity of errors like these:

```
[shard 17] view - Error applying view update to 10.10.5.59: std::invalid_argument (Mutation of 68781501 bytes is too large for the maximum size of 16777216)
```

It would really help to know which view is being updated and if possible some more info about the base partition(s) and the destination view partition(s) involved.

**Comment by vladzcloudius** [comment]
@psarna @nyh FYI

**Comment by psarna** [comment]
I posted a patch - providing partition information is significantly more complicated for a quick weekend patch, so this one only adds keyspace+view table name information. It would also create some more overhead which we should consider - e.g. a pair of potentially large partition keys (up to 64kb according to the docs) would need to be copied around in case it's needed for an error message, and it's also not clear how to print them (hex?). In any case, it can be considered in a follow-up.

**Comment by vladzcloudius** [comment]
> I posted a patch - providing partition information is significantly more complicated for a quick weekend patch, so this one only adds keyspace+view table name information. It would also create some more overhead which we should consider - e.g. a pair of potentially large partition keys (up to 64kb according to the docs) would need to be copied around in case it's needed for an error message, and it's also not clear how to print them (hex?). In any case, it can be considered in a follow-up.

Thanks, @psarna 
Posting a token instead of a key would already be very useful.

**Comment by vladzcloudius** [comment]
Thanks a lot, @psarna. 
And thanks @avikivity for a stellar merge!
