### ISSUE TITLE
node rebuild is slow

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla#818]
Syclla Configuration:
- 3 x Rackspace OnMetal IO v1 (10Gbps network)
- Repo using version branch-0.16/52

Test Configuration:
- Create Keyspace with RF=3
- Stopped the third server
- Wrote 100M keys (each 5 columns of 2048 bytes) using 5 stress servers with CL=TWO
- Writing with stress took around 24 minutes
- After writing each of the first 2 nodes had 970GB of data
- Started the third server, and ran nodetool rebuild

While writing 100M keys to the two servers took 24 minutes, the rebuild took around 120 minutes, which is much much slower.

**Comment by tzach** [comment]
@slivne do we have a test for this?

**Comment by slivne** [comment]
We do not have a test for on metal

We have test on AWS using @lmr framework

We are going to change all the tests to be "more demanding" (e.g. work with
a higher data set before executing the command etc.)

Benoit has shown that if he uses the same test but changes the amount of
data the cluster is populated with then we are not able to complete the
procedures

**Comment by tzach** [comment]
> We are going to change all the tests to be "more demanding" (e.g. work with
a higher data set before executing the command etc.)

+1
Even more tests should be under load

**Comment by avikivity** [comment]
Stale bug, rebuild has changed many times over the years. Please retest with a new version.
