### ISSUE TITLE
Request are not entirely read during shedding

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#8193]
Through code inspection, it looks like when requests are shed (e.g. due to being too large or exceeding the max number of concurrent requests per shard), they are erroneously ignored right after parsing their headers - while their body still waits in the socket and will be read by the server, which expects to find a CQL header in there.

It's quite late so I don't have any automatic tests that support this claim, but manual tests suggest that that's what indeed happens. The fix is simple - seastar streams are capable of skipping bytes, so before the error is returned, the body of the shed request should be skipped.

**Comment by avikivity** [comment]
Backported to 4.4. 4.3 isn't vulnerable AFAICT, @psarna please confirm.

**Comment by psarna** [comment]
4.3 looks just as vulnerable as 4.4, I'll backport now.

**Comment by psarna** [comment]
I backported to 4.3 here: https://github.com/psarna/scylla/tree/4.3_backport_shedding , but I'm unable to compile with 4.3 dbuild due to some rapidjson errors... can somebody verify and apply?

**Comment by psarna** [comment]
(alternatively, the /next job could simply verify for me)

**Comment by psarna** [comment]
queued to next-4.3

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
