### ISSUE TITLE
Very long timeout, and exception ignored, in repair when slave dies

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#820]
As shown in https://github.com/cloudius-systems/scylla-dtest/issues/124, when we start a repair and kill a slave node in the middle of streaming (see the dtest repair_kill_2_test reproducing this often), we can get as part of the output also

```
WARNING: exceptional future ignored of type 'std::runtime_error': Checksum or sync of partial range failed
```

This shouldn't have been - we should not ignore exceptions. Perhaps we're using when_all or parallel_for_each which has this problem. This warning is annoying, but not a real concern because one of the other exceptions _is_ used and causes the repair to stop.

A second problem is that not only does streaming retry many times taking a VERY long time, after it stops retrying, in then just hangs for no reason for another (?) 600 seconds until it finally prints:

```
INFO  [shard 0] stream_session - The session is idle for 600 seconds, the peer 127.0.0.2 is probably gone, close it
```

This last wait is annoying - if we gave up retrying, what are we waiting for?

**Comment by tzach** [comment]
@nyh @slivne its a bug for sure, but does not look like High  to me
AFAIU, the end results are two error messages when a slave node fail during streaming, with no operation affect.
Is this the case?

**Comment by nyh** [comment]
Yes, it's a not-very-useful messages, and a long delay in admitting to the user that the repair failed. But no other ill-effect (it doesn't waste CPU, doesn't crash, or anything like that).

**Comment by tzach** [comment]
Thanks @nyh, demoting this issue for now

**Comment by asias** [comment]
@nyh As we discussed, the 600 seconds time wait  is a feature not a bug.  See c971fad61846a0c3de553fec694917d8e969ab0b.

**Comment by slivne** [comment]
we increased the 600 seconds in some cases - we need to fix this.

**Comment by nyh** [comment]
The repair code is very different from what it was 6 years ago, it is unlikely that the specifics in this issue are relevant today. So closing this issue.
