### ISSUE TITLE
Regression in cdc generation query for alternator

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#8210]
With the update to CDC generation management, the way we retrieve and process these changed.
One very bad bug slipped through though; the code for getting versioned streams did not take into
account the late-in-pr change to make clustering of CDC gen timestamps reversed. So our alternator
shard info became quite rump-stumped, leading to more or less no data depending on when generations
changed w.r. data.

The versioned streams query need to take reverse clustering into account.

**Comment by nyh** [comment]
@elcallio you said this is a regression; Can you please help me figure out to which branches (Only 4.4? Also 4.3?) we will need to backport the fix for this issue? Thanks.

**Comment by elcallio** [comment]
Branches that received /scylladb/scylla/pull/8018, esp. be18f626ec8bffedce5c0abd0332548293163dad

**Comment by slivne** [comment]
@avikivity we need a backport to 4.4 - since we have a backport of 4b7319a87090ba81ee4321a3c1f4994db6bc0e8a to 4.4

**Comment by nyh** [comment]
@avikivity already backported this to 4.4.
4.3 did not include the change that this patch is fixing, so no need to backport to 4.3.
