### ISSUE TITLE
I can't install 4.4.rc2 on ubuntu/debian

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla#8214]
Installation on all ubuntu/debian of 4.4.rc2 fail:
```
Unpacking scylla (4.4~rc2-0.20210224.49cd0b87f-1) ...
Selecting previously unselected package sntp.
Preparing to unpack .../52-sntp_1%3a4.2.8p12+dfsg-4_amd64.deb ...
Unpacking sntp (1:4.2.8p12+dfsg-4) ...
Errors were encountered while processing:
 /tmp/apt-dpkg-install-lAKNcL/50-scylla-node-exporter_4.4~rc2-0.20210224.49cd0b87f-1_amd64.deb
[91mE: Sub-process /usr/bin/dpkg returned an error code (1)
[0mThe command '/bin/sh -c apt-get install $SCYLLA_PRODUCT_NAME -y -qq' returned a non-zero code: 100
```
Please see full log attached.
You can also see other installation docker logs on https://jenkins.scylladb.com/view/nexts/job/scylla-4.4/job/promote-release/31/

@penberg: The same file /etc/default/scylla-node-exporter in two packages, could be a packaging bug.

CentOS is OK.

**Comment by hagitsegev** [comment]
[debian10_4.4.c2_installation.log](https://github.com/scylladb/scylla/files/6083223/debian10_4.4.c2_installation.log)

**Comment by penberg** [comment]
@syuu1228 Looks like a packaging but introduced with the new node exporter package because now that configuration file is in two packages?

**Comment by syuu1228** [comment]
I think It's same bug as #8163, and the patch backported at 4days ago: 
https://github.com/scylladb/scylla/commits/branch-4.4/dist/debian

This build looks like older than backported date.

**Comment by hagitsegev** [comment]
4.4.rc3 installation tests were OK. Can close it.

**Comment by penberg** [comment]
Thanks, @syuu1228 and @hagitsegev!
