### ISSUE TITLE
scylla_raid_setup says 'mdX is already using' even it's unused

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#8219]
On Ubuntu 20.04 AMI, scylla_raid_setup --raiddev /dev/md0 causes
'/dev/md0 is already using' (issue #7627).
So we merged the patch to find free mdX 587b909c5ce35c74458650faffdc1fa464a338b9.

However, look into /proc/mdstat of the AMI, it actually says no active md device available:
```
ubuntu@ip-10-0-0-43:~$ cat /proc/mdstat 
Personalities : 
unused devices: <none>
```

We currently decide mdX is used when `os.path.exists('/sys/block/mdX/md/array_state')  == True`,
but according to kernel doc, the file may available even array is STOPPED:
```
    clear

        No devices, no size, no level
        Writing is equivalent to STOP_ARRAY ioctl
```
https://www.kernel.org/doc/html/v4.15/admin-guide/md.html

So I think we fixed #7627 in wrong way, on Ubuntu 20.04 AMI we can use /dev/md0 to construct RAID volume.
Note that no need to revert 587b909c5ce35c74458650faffdc1fa464a338b9, since auto-detect mode is always useful.

**Comment by avikivity** [comment]
Backported to 4.4.

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
