### ISSUE TITLE
 sstableloader doesn't work with Alternator tables if "-nx" option is used

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8230]
In #8229 we fixed an earlier problem with `sstableloader` with Alternator tables. @psarna discovered that it now works fine with the default options, but if the `-nx` option (no prepared statements) is given without `-nb` (_no batching_), it fails.

The new problem is that Alternator tables have a column name `:attrs`, which begins with a colon, and this confuses sstableloader when batching is enabled but prepared statements are not, which thinks that this column name - which is quoted in CQL - is actually an unquoted reference to a prepared-statement value, and replaces the column name `":attrs"`in the CQL command  by a nonsensical quoted question-mark: `"?"`.  

The relevant sstableloader issues are https://github.com/scylladb/scylla-tools-java/issues/230 and https://github.com/scylladb/scylla-tools-java/issues/241.
When that issue is fixed, we need to update the `tools/java` submodule in Scylla.

**Comment by nyh** [comment]
Interestingly, the sstableloder test written by @Orenef11 in https://github.com/scylladb/scylla-dtest/pull/2019 did not reproduce this bug - it works even without "no batching". My (unproven) guess is that in that test the table schema has just a partition key, and maybe we need both a partition key and sort key to reproduce this bug. But this is just a guess - maybe @psarna remembers how he reproduced this bug.

**Comment by psarna** [comment]
I'm pretty sure that the schema I used was from the `test_table_s` fixture from alternator/test/conftest.py: https://github.com/scylladb/scylla/blob/a9835ec1286ce6960cf41b5f9e527f84ab1738c3/test/alternator/conftest.py#L141

My investigation went like this:
1. Run a single local node
2. Modify the fixture above to **not** drop the table after it's created
3. Run the alternator test suite to get some filled alternator tables
4. Flush the node with `nodetool flush`
5. Use the generated sstables as a source for sstableloader

**Comment by psarna** [comment]
And, `test_table_s`'s schema uses only a partition key, no clustering key at all. But I guess it's best to just modify *all* the fixtures to not drop tables, then run all tests and then flush the sstables. That should give us a variety of schemas and rows, and hopefully one of them would trigger the bug.

**Comment by psarna** [comment]
@nyh @Orenef11 Ok, managed to reproduce. I failed to provide one very vital piece of information to the sstableloader issue and I'll update it now.

First of all, this error **only manifests with -nx**, which stands for "don't use prepared statements". And secondly, in order to actually have batches, one must have more than 1 mutation present in the sstable - which means that either a row has to be inserted and then updated later (without compaction), or a partition needs to have more than 1 row, which is only possible with clustering keys, as @nyh suggested. But the most important thing is that this bug is only triggered with `-nx` flag.

**Comment by elcallio** [comment]
It is because of the regex match on line 807 of bulkloader. It gets confused and thinks this is a variable.
Need to add word boundary match.

**Comment by elcallio** [comment]
See /scylladb/scylla-tools-java/pull/242

**Comment by nyh** [comment]
See also https://github.com/scylladb/scylla-tools-java/issues/241

**Comment by nyh** [comment]
Updated this issue's title and description to match our new understanding that the bug happens just with "-nx" (no prepared statements).

**Comment by nyh** [comment]
This bug can be encountered by Alternator users who use sstableloader and for some weird reason decide to use its "-nx" option, so I'll backport. The backport to branch-4.5 is especially necessary because we already have a dtest testing this feature.

Backported fix into the tools/java submodule, in branches:
* next-4.5 (d881d539f370f15288e133e7393274da0d3b7275)
* next-4.4 (ebd2c9bab0bbfdc215da21a688248e2478f7808e)
* next-4.3 (d01ce491c015afadb17a7fedd4f15f399f55f9dd)
