### ISSUE TITLE
Query from the index will fail during upgrading from 3.1.2 to 4.1.11

### ISSUE THREAD

**Issue by page4** [scylladb/scylla#8246]
*Installation details*
Scylla version (or git commit hash): 3.1.2 -> 4.1.2
Cluster size:  2
OS (RHEL/CentOS/Ubuntu/AWS AMI):

First, I execulate following cql statements,
```
CREATE KEYSPACE ks WITH replication = {'class': 'NetworkTopologyStrategy', 'dc': 2};
CREATE TABLE ks.cf ( k bigint PRIMARY KEY , v bigint );
CREATE INDEX icf ON ks.cf (v) ;
INSERT INTO ks.cf (k , v ) VALUES ( 1, 2);

CONSISTENCY ALL ;
SELECT * FROM ks.icf_index WHERE v=2;
```

Then, upgrade a node from 3.1.2 to 4.1.11.
during the bootup,  an error message  ` database - Skipping: ks. Exception occurred when loading system table views: Can't find a column family with UUID d56efa50-8157-11eb-ac92-000000000001` occurs.
```
 init - loading system sstables
 init - loading non-system sstables
 migration_manager - Update view 'ks.icf_index' From org.apache.cassandra.config.CFMetaData@0x61900923d180[cfId=d56efa50-8157-11eb-ac92-000000000001,ksName=ks,cfName=ic
 schema_tables - Altering ks.cf id=c508fad0-8157-11eb-ac92-000000000001 version=c3edefbc-cbee-3b5b-872f-e682f4b7ff8c
 schema_tables - Altering ks.icf_index id=d56efa50-8157-11eb-ac92-000000000001 version=b738893b-a78f-359e-be17-f7cdbc3165df
 query_processor - Column definitions for ks.cf changed, invalidating related prepared statements
 database - Skipping: ks. Exception occurred when loading system table views: Can't find a column family with UUID d56efa50-8157-11eb-ac92-000000000001
 database - Populating Keyspace ks
 database - Keyspace ks: Reading CF icf_index id=d56efa50-8157-11eb-ac92-000000000001 version=b738893b-a78f-359e-be17-f7cdbc3165df
 database - Keyspace ks: Reading CF cf id=c508fad0-8157-11eb-ac92-000000000001 version=c3edefbc-cbee-3b5b-872f-e682f4b7ff8c
 database - Populating Keyspace system_distributed
```

I suspend it is caused by https://github.com/scylladb/scylla/blob/baf5d05631491792c0809f6ea657f9aa60ad0cd2/database.cc#L851

I guess `maybe_update_legacy_secondary_index_mv_schema`  may announce a view update to some shards that have not parse the view schema.

Finally, query from the index will fail on the old node,
```
CONSISTENCY ALL ;
SELECT * FROM ks.icf_index WHERE v=2;
```
I get some error messages.
```
 paging - Query of d56efa50-8157-11eb-ac92-000000000001, page_size=100, limit=4294967295 requires paging
 paging - Fetching d56efa50-8157-11eb-ac92-000000000001, page size=100, max_rows=100
 storage_proxy - Schema version request for fc9f831f-ba8c-3429-9153-9aaeb709254c
 storage_proxy - Exception when communicating with 10.67.56.77: std::runtime_error (Tried to perform a view query which is base info dependant without initializing it
```

**Comment by slivne** [comment]
Its not allowed to upgrade from 3.1 to 4.1

The upgrade path is 3.1->3.2->3.3->4.0->4.1

The 4.1 is EOL - you should upgrade to 4.2

There is an issue related to computed columns
https://github.com/scylladb/scylla/issues/7515 that is related to secondary
indexes.

Yet in any case - you are using an unsupported upgrade path

**Comment by page4** [comment]
Thanks. After the whole cluster is upgraded,  we can query from index !

**Comment by slivne** [comment]
@page4 if you are running on 4.1 you are using an unsupported version please upgrade - closing the issue
