### ISSUE TITLE
Regression on cleanup compaction's space requirement due to unlimited parallelism

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#8247]
Prior to 463d0ab37c33684c5b658221b16198b14757e35f, only one table could be cleaned up at a time on a given shard. Since then, all tables belonging to a given keyspace are cleaned up in parallel. Cleanup serialization on each shard was enforced with a semaphore, which was incorrectly removed by the patch aforementioned.

So space requirement for cleanup to succeed can be up to the size of keyspace, potentially making the node run out of space.

Node could also run out of memory if there are tons of tables in the keyspace being cleaned up. Mem. requirement is at least #_of_tables * 128k (not taking into account write behind, etc). With 5k tables, it's ~0.64G per shard.

Potentially all versions since 4.1 are affected.

@slivne @bhalevy this also explains some of the cleanup performance issues we've had

/CC @slivne @bhalevy @avikivity

**Comment by bhalevy** [comment]
Good catch

**Comment by raphaelsc** [comment]
please let's backport this to 4.2, 4.3 and 4.4

**Comment by avikivity** [comment]
Backported to 4.2, 4.3, 4.4.
