### ISSUE TITLE
nodetool cfstats and compactionstats were run from 3 different nodes and stuck, not return

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#8262]
*Installation details*
Scylla version (or git commit hash): 4.4.rc3-0.20210304.c2d924757 with build-id 1d0929cbdc3fd39b79157e974cd8d08cd2610afb
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0242812f1bd719d03 (eu-west-1)

Test: `longevity-lwt-basic-24h-1dis-2nondis`
Running [Jenkins job](https://jenkins.scylladb.com/view/scylla-4.4/job/scylla-4.4/job/longevity/job/longevity-lwt-24h-1dis-2nondis-test/2/console)

The test runs LWT load with parallel nemesis: 1 disruptive and 2 non-disruptive

From different nemesises 3 nodetool commands were run on the 3 nodes (one command on each node).

The flow:

**(1)** 2021-03-10 20:00:47.253 start `NoCorruptRepair` nemesis, on node 2 (run repair)
```
2021-03-10 20:00:47.253: (DisruptionEvent Severity.NORMAL): type=NoCorruptRepair subtype=start node=Node longevity-lwt-24h-parallel-nemesis--db-node-1b657b1e-2 [54.171.219.113 | 10.0.2.218] (seed: False) duration=None
```
||
**(2)** 2021-03-10 20:07:48.808 start `RestartNodeWithResharding` on node 5 (restart Scylla and change murmur3 cause to resharding)
```
2021-03-10 20:07:48.808: (DisruptionEvent Severity.NORMAL): type=RestartNodeWithResharding subtype=start node=Node longevity-lwt-24h-parallel-nemesis--db-node-1b657b1e-5 [34.240.7.198 | 10.0.2.163] (seed: False) duration=None
```
||
**(3)** 2021-03-10 20:21:04.840 start `ShowTopPartitions` on node 3 
```
2021-03-10 20:21:04.840: (DisruptionEvent Severity.NORMAL): type=ShowTopPartitions subtype=start node=Node longevity-lwt-24h-parallel-nemesis--db-node-1b657b1e-3 [18.202.224.37 | 10.0.0.79] (seed: False) duration=None
```
||
**(4)** 2021-03-10 20:21:06,650 node 3 - run cfstats before toppartition (during **(3)** )
```
< t:2021-03-10 20:21:06,650 f:remote_base.py  l:520  c:RemoteCmdRunner      p:DEBUG > Running command "/usr/bin/nodetool  cfstats "...
```
||
**(5)** 2021-03-10 20:22:24 resharding (during step **(2)**) on the node 5 finished 
```
Reshard on node 5 finish - Mar 10 20:22:24 longevity-lwt-24h-parallel-nemesis--db-node-1b657b1e-5 scylla[23353]:  [shard 0] database - Resharded 1GB in 22.88 seconds, 73MB/s
```
||
**(6)** 2021-03-10 20:23:43,156 Executing CQL 'DROP TABLE drop_table_during_repair_ks_0.standard1' (during **(1)**)
```
< t:2021-03-10 20:23:43,156 f:common.py       l:1177 c:utils                p:DEBUG > Executing CQL 'DROP TABLE drop_table_during_repair_ks_0.standard1'...
```
||
**(7)** 2021-03-10 20:23:52,477 cfstats failed (during **(4)**) - not found `drop_table_during_repair_ks_0.standard1` - it's **OK**
```
< t:2021-03-10 20:23:52,477 f:file_logger.py  l:78   c:sdcm.sct_events.file_logger p:INFO  > nodetool: Scylla API server HTTP GET to URL '/column_family/metrics/live_ss_table_count/drop_table_during_repair_ks_0:standard1' failed: Column family 'drop_table_during_repair_ks_0:standard1' not found
```
||
**(8)** 2021-03-10 20:23:52.475 finish `ShowTopPartitions` on node 3  (**(3)**)
```
2021-03-10 20:23:52.475: (DisruptionEvent Severity.ERROR): type=ShowTopPartitions subtype=end node=Node longevity-lwt-24h-parallel-nemesis--db-node-1b657b1e-3 [18.202.224.37 | 10.0.0.79] (seed: False) duration=171 error=Encountered a bad command exit code!
```
||
**(9)** 2021-03-10 20:24:01,604 node 5 - run `nodetool  compactionstats` (during **(2)**) - **STUCK**
```
STUCK on node 5 - didn't finish < t:2021-03-10 20:24:01,604 f:remote_base.py  l:520  c:RemoteCmdRunner      p:DEBUG > Running command "/usr/bin/nodetool  compactionstats "...
```
process on the node 5:
```scyllaa+ 24270  1395  0 Mar10 ?        00:00:00 /bin/sh /opt/scylladb/share/cassandra/bin/nodetool compactionstats```
||
**(10)** 2021-03-10 20:29:06.379 start `ShowTopPartitions` on node 3
```
2021-03-10 20:29:06.379: (DisruptionEvent Severity.NORMAL): type=ShowTopPartitions subtype=start node=Node longevity-lwt-24h-parallel-nemesis--db-node-1b657b1e-3 [18.202.224.37 | 10.0.0.79] (seed: False) duration=None
```
||
**(11)** 2021-03-10 20:29:08,131 node 3 - run cfstats (during **(10)**) - **STUCK**
```
STUCK node3 - < t:2021-03-10 20:29:08,131 f:remote_base.py  l:520  c:RemoteCmdRunner      p:DEBUG > Running command "/usr/bin/nodetool  cfstats "...
```
process on the node 3
```scyllaa+ 17318  1446  0 Mar10 ?        00:00:00 /bin/sh /opt/scylladb/share/cassandra/bin/nodetool cfstats```
||
**(12)**  2021-03-10 20:53:13.682 finish `NoCorruptRepair` on the node 2
```
2021-03-10 20:53:13.682: (DisruptionEvent Severity.NORMAL): type=NoCorruptRepair subtype=end node=Node longevity-lwt-24h-parallel-nemesis--db-node-1b657b1e-2 [54.171.219.113 | 10.0.2.218] (seed: False) duration=3213
```
||
**(13)**  2021-03-10 20:58:20.283 start `Refresh` nemesis on the node 2
```
2021-03-10 20:58:20.283: (DisruptionEvent Severity.NORMAL): type=Refresh subtype=start node=Node longevity-lwt-24h-parallel-nemesis--db-node-1b657b1e-2 [54.171.219.113 | 10.0.2.218] (seed: False) duration=None
```
||
**(14)**  2021-03-10 20:59:38,581 node 2  - run cfstats (during **(13)**) - **STUCK**
```
STUCK node2 - < t:2021-03-10 20:59:38,581 f:remote_base.py  l:520  c:RemoteCmdRunner      p:DEBUG > Running command "/usr/bin/nodetool  cfstats keyspace1.standard1"...
```
process on the node 2:
```scyllaa+ 11704  9141  0 Mar10 ?        00:00:00 /bin/sh /opt/scylladb/share/cassandra/bin/nodetool cfstats keyspace1.standard1```

Nodes:
```
longevity-lwt-24h-parallel-nemesis--db-node-1b657b1e-2 [54.171.219.113 | 10.0.2.218]
longevity-lwt-24h-parallel-nemesis--db-node-1b657b1e-3 [18.202.224.37 | 10.0.0.79]
longevity-lwt-24h-parallel-nemesis--db-node-1b657b1e-5 [34.240.7.198 | 10.0.2.163]
```

Load continue to run:
![Screenshot from 2021-03-11 15-36-38](https://user-images.githubusercontent.com/34435448/110795583-af64ac00-827f-11eb-9ec7-30c397809aa1.png)

3 nemesises are stuck:
![Screenshot from 2021-03-11 15-36-26](https://user-images.githubusercontent.com/34435448/110795592-b2f83300-827f-11eb-82a3-2107ae20d1b2.png)

Cluster is alive

[Monitor](http://34.252.246.33:3000/d/4H2kS18Mk/longevity-lwt-24h-1dis-2nondis-test-scylla-per-server-metrics-nemesis-master?orgId=1&from=1615393092000&to=now&var-by=instance&var-cluster=&var-dc=All&var-node=All&var-shard=All&var-sct_tags=CassandraStressEvent&refresh=30s)

test_id: `1b657b1e-7b79-4152-bb6f-d5c7f4da26e7`

**Comment by slivne** [comment]
I am not sure the fix for scylla-jmx that's related to nodetool getting stuck at times made it to 4.4.rc3 - I  think it may be only in 4.4.rc4 - please check

**Comment by slivne** [comment]
the fix for JMX is only in rc4
