### ISSUE TITLE
Cleanup fail with wrap-around range

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#827]
Shlomi shared the following:
DEBUG [shard 0] commitlog - Created new reserve segment CommitLog-1-1712320.log
INFO  [shard 0] compaction - Cleaning [/home/shlomi/scylla/tmp/keyspace1/standard1-479a0070bef811e5927b000000000000/keyspace1-standard1-ka-1-Data.db:level=0, ]
DEBUG [shard 0] sstable - Writing TOC file /home/shlomi/scylla/tmp/keyspace1/standard1-479a0070bef811e5927b000000000000/keyspace1-standard1-ka-2-TOC.txt.tmp 
scylla: ./range.hh:121: bool range<T>::after(const T&, Comparator&&) const [with Comparator = dht::token_comparator; T = dht::token]: Assertion `!is_wrap_around(cmp)' failed.

We probably need to extend range<T>::after to work with a wrap-around range.

**Comment by slivne** [comment]
Head
shlomi@localhost~/scylla (master)$ git log -1
commit d7cb88e0af4546c73bc922d16ab28f56e226e426
Merge: de9f930 7c97089
Author: Tomasz Grabiec <tgrabiec@scylladb.com>
Date:   Tue Jan 19 13:22:10 2016 +0100

    Merge branch 'pdziepak/fixes-for-alter-table/v1'
   
    From Paweł:
   
    "This series contains some more fixes for issues related to alter table,
    namely: incorrect parsing of collection information in comparator, missing
    schema::_raw._collections in equality check, missing compatibility
    information for utf8->blob, ascii->blob and ascii->utf8 casts."


running scylla single node

1. ~/cassandra/tools/bin/cassandra-stress write n=10000 -mode cql3 native

2. flush from the api

3. cleanup from the api

**Comment by slivne** [comment]
@tgrabiec  should you handle it ?

**Comment by tgrabiec** [comment]
I think the problem is that we try to do binary search with wrap around ranges during cleanup, that's not going to work. We should fix that instead.

**Comment by raphaelsc** [comment]
INFO  [shard 0] compaction - Cleaning [/data/data/keyspace1/standard1-65523650c19611e58adb000000000000/keyspace1-standard1-ka-34-Data.db:level=0, ]
INFO  [shard 0] compaction - Cleaning [/data/data/keyspace1/standard1-65523650c19611e58adb000000000000/keyspace1-standard1-ka-112-Data.db:level=0, ]
INFO  [shard 0] compaction - Cleaning [/data/data/keyspace1/standard1-65523650c19611e58adb000000000000/keyspace1-standard1-ka-126-Data.db:level=0, ]
INFO  [shard 0] compaction - Cleaning [/data/data/keyspace1/standard1-65523650c19611e58adb000000000000/keyspace1-standard1-ka-128-Data.db:level=0, ]
INFO  [shard 0] compaction - Cleaning [/data/data/keyspace1/standard1-65523650c19611e58adb000000000000/keyspace1-standard1-ka-133-Data.db:level=0, ]
INFO  [shard 0] compaction - Cleaned 1 sstables to [/data/data/keyspace1/standard1-65523650c19611e58adb000000000000/keyspace1-standard1-ka-137-Data.db:level=0, ]. 62864196 bytes to 62864196 (~100% of original) in 10211ms = 5.87107MB/s. ~223872 total partitions merged to 223716.
INFO  [shard 0] compaction - Cleaned 1 sstables to [/data/data/keyspace1/standard1-65523650c19611e58adb000000000000/keyspace1-standard1-ka-134-Data.db:level=0, ]. 279149615 bytes to 279149615 (~100% of original) in 54692ms = 4.86754MB/s. ~993664 total partitions merged to 993415.
INFO  [shard 0] compaction - Cleaned 1 sstables to [/data/data/keyspace1/standard1-65523650c19611e58adb000000000000/keyspace1-standard1-ka-136-Data.db:level=0, ]. 323763704 bytes to 323763704 (~100% of original) in 64959ms = 4.75321MB/s. ~1152384 total partitions merged to 1152184.
INFO  [shard 0] compaction - Cleaned 1 sstables to [/data/data/keyspace1/standard1-65523650c19611e58adb000000000000/keyspace1-standard1-ka-135-Data.db:level=0, ]. 576314421 bytes to 576314421 (~100% of original) in 94342ms = 5.82577MB/s. ~2051072 total partitions merged to 2050941.
INFO  [shard 0] compaction - Cleaned 1 sstables to [/data/data/keyspace1/standard1-65523650c19611e58adb000000000000/keyspace1-standard1-ka-138-Data.db:level=0, ]. 639352275 bytes to 639352275 (~100% of original) in 98098ms = 6.21551MB/s. ~2275456 total partitions merged to 2275275.


Working now (after commit: d54c77d5d0)

**Comment by avikivity** [comment]
bot got confused, removing backport candidate label.
