### ISSUE TITLE
The LWT stress is stopped during the prepare phase

### ISSUE THREAD

**Issue by Orenef11** [scylladb/scylla#8270]
### Installation Details
Kernel version: `5.11.3-1.el7.elrepo.x86_64`
Scylla version (or git commit hash): `4.5.dev-0.20210307.2d9feaace with build-id d779669835c747cc193d97d16b2e84c7cf05177a`
Cluster size: 4 nodes (i3.2xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0291a3585729c627b` (aws: eu-north-1)

Test: `longevity-lwt-3h-test`
Test name: `longevity_lwt_test.LWTLongevityTest.test_lwt_longevity`
Test config file(s):
- [longevity-lwt-basic-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/bddb74c85d77db6901179aa9b244456cf7aca521/test-cases/longevity/longevity-lwt-basic-3h.yaml)

### Issue Description ###
====================================
The test failed because of the following errors:
```
2021-03-08 04:58:37.000: (DatabaseLogEvent Severity.ERROR): type=DATABASE_ERROR regex=Exception  line_number=51623 node=Node longevity-lwt-3h-master-db-node-7e933d87-2 [13.49.21.145 | 10.0.2.141] (seed: False)
2021-03-08T04:58:37+00:00  longevity-lwt-3h-master-db-node-7e933d87-2 !INFO    | scylla: [shard 7] rpc - client 10.0.2.99:56439 msg_id 510415:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
2021-03-08 04:58:29.000: (DatabaseLogEvent Severity.ERROR): type=DATABASE_ERROR regex=Exception  line_number=26965 node=Node longevity-lwt-3h-master-db-node-7e933d87-4 [13.49.75.237 | 10.0.1.67] (seed: False)
2021-03-08T04:58:29+00:00  longevity-lwt-3h-master-db-node-7e933d87-4 !ERR     | scylla: [shard 7] paxos - CAS[164690] prune: failed exceptions::mutation_write_timeout_exception (Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE.)
```

The last time the test was passed was on `07-Feb-2021 03:21:36` ([JOB#186](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-lwt-3h-test/186/console))

All commits that were merged between the runs [JOB#186](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-lwt-3h-test/186) - [JOB#187](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-lwt-3h-test/187)
```
03:18 roy@Roees-MacBook-Pro ~/git/scylla/scylla ( (master)) $ git lg e1261d10f..d8345c67d
* d8345c67d - Consolidate system and non system keyspace creation (4 weeks ago) <Gleb Natapov>
* 51037e94e - lwt: handle an error during prune operation (4 weeks ago) <Gleb Natapov>
*   3dd9c5596 - Merge 'Minor tweaks to the failure detector interface' from Piotr Sarna (4 weeks ago) <Tomasz Grabiec>
|\
| * faca59efa - failure_detector: add getting last update time point (4 weeks ago) <Piotr Sarna>
| * d23584c8f - failure_detector: return arrival samples by const reference (5 weeks ago) <Piotr Sarna>
| * 445e6e44f - failure_detector: remove unimplemented is_alive method (5 weeks ago) <Piotr Sarna>
*   4acc6fecf - Merge 'locator: Check DC names in NetworkTopologyStrategy' from Juliusz Stasiewicz (4 weeks ago) <Piotr Sarna>
|\
| * 97bb15b2f - tests: Adjusted tests for DC checking in NTS (4 weeks ago) <Juliusz Stasiewicz>
| * b6fb5ee91 - locator: Check DC names in NTS (4 weeks ago) <Juliusz Stasiewicz>
* 3d001b558 - query: use local limit for non-limited queries in mixed cluster (4 weeks ago) <Botond Dénes>
* 2f50bf202 - Update seastar submodule (4 weeks ago) <Avi Kivity>
* 37b41d776 - test: add missing #include <fstream> (4 weeks ago) <Avi Kivity>
* c16e4a042 - migration_manager: Propagate schema changes with reads like we do on writes (4 weeks ago) <Tomasz Grabiec>
*   4082f57ed - Merge 'Make commitlog disk limit a hard limit.' from Calle Wilund (4 weeks ago) <Avi Kivity>
|\
| * 4be718ebf - commitlog: Force earlier cycle/flush iff segment reserve is empty (9 weeks ago) <Calle Wilund>
| * be8c359a6 - commitlog: Make segment allocation wait iff disk usage > max (9 weeks ago) <Calle Wilund>
| * ab55a1b4e - commitlog: Do partial (memtable) flushing based on threshold (9 weeks ago) <Calle Wilund>
| * 7c84b16cd - commitlog: Make flush threshold configurable (9 weeks ago) <Calle Wilund>
| * c3d95811d - table: Add a flush RP mark to table, and shortcut if not above (9 weeks ago) <Calle Wilund>
* af2d1fa0d - Update abseil submodule (5 weeks ago) <Avi Kivity>
* b9a5aff7a - distributed_loader: drop execute_futures function (5 weeks ago) <Gleb Natapov>
* a05adb853 - database: Remove global storage proxy reference (5 weeks ago) <Pavel Emelyanov>
* 8490c9ff6 - transport: Remove global storage service reference (5 weeks ago) <Pavel Emelyanov>
* 4498bb0a4 - API: Fix aggregation in column_familiy (5 weeks ago) <Amnon Heiman>
```
Apparently, the test failed due to the commit  `51037e94e - lwt: handle an error during prune operation (4 weeks ago) <Gleb Natapov>`.
@gleb-cloudius  Can you check it out?

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 7e933d87-b67b-440f-b144-343ae967a978`
Show all stored logs command: `$ hydra investigate show-logs 7e933d87-b67b-440f-b144-343ae967a978`

Test id: `7e933d87-b67b-440f-b144-343ae967a978`

### Logs ###
**grafana** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e933d87-b67b-440f-b144-343ae967a978/20210308_060437/grafana-screenshot-longevity-lwt-3h-test-scylla-per-server-metrics-nemesis-20210308_060822-longevity-lwt-3h-master-monitor-node-7e933d87-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7e933d87-b67b-440f-b144-343ae967a978/20210308_060437/grafana-screenshot-longevity-lwt-3h-test-scylla-per-server-metrics-nemesis-20210308_060822-longevity-lwt-3h-master-monitor-node-7e933d87-1.png)
**grafana** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e933d87-b67b-440f-b144-343ae967a978/20210308_060437/grafana-screenshot-overview-20210308_060437-longevity-lwt-3h-master-monitor-node-7e933d87-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/7e933d87-b67b-440f-b144-343ae967a978/20210308_060437/grafana-screenshot-overview-20210308_060437-longevity-lwt-3h-master-monitor-node-7e933d87-1.png)
**db-cluster** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e933d87-b67b-440f-b144-343ae967a978/20210308_061303/db-cluster-7e933d87.zip](https://cloudius-jenkins-test.s3.amazonaws.com/7e933d87-b67b-440f-b144-343ae967a978/20210308_061303/db-cluster-7e933d87.zip)
**loader-set** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e933d87-b67b-440f-b144-343ae967a978/20210308_061303/loader-set-7e933d87.zip](https://cloudius-jenkins-test.s3.amazonaws.com/7e933d87-b67b-440f-b144-343ae967a978/20210308_061303/loader-set-7e933d87.zip)
**monitor-set** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e933d87-b67b-440f-b144-343ae967a978/20210308_061303/monitor-set-7e933d87.zip](https://cloudius-jenkins-test.s3.amazonaws.com/7e933d87-b67b-440f-b144-343ae967a978/20210308_061303/monitor-set-7e933d87.zip)
**sct-runner** - [https://cloudius-jenkins-test.s3.amazonaws.com/7e933d87-b67b-440f-b144-343ae967a978/20210308_061303/sct-runner-7e933d87.zip](https://cloudius-jenkins-test.s3.amazonaws.com/7e933d87-b67b-440f-b144-343ae967a978/20210308_061303/sct-runner-7e933d87.zip)

### Links
* [Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-lwt-3h-test/197/)
* [Download "Per server metrics nemesis" Grafana Screenshot](https://cloudius-jenkins-test.s3.amazonaws.com/7e933d87-b67b-440f-b144-343ae967a978/20210308_060437/grafana-screenshot-overview-20210308_060437-longevity-lwt-3h-master-monitor-node-7e933d87-1.png)
* [Download "Overview metrics" Grafana Screenshot](https://cloudius-jenkins-test.s3.amazonaws.com/7e933d87-b67b-440f-b144-343ae967a978/20210308_060437/grafana-screenshot-longevity-lwt-3h-test-scylla-per-server-metrics-nemesis-20210308_060822-longevity-lwt-3h-master-monitor-node-7e933d87-1.pngt)

### Snapshots
![image](https://user-images.githubusercontent.com/11705430/111061450-22526a80-84ac-11eb-8fcb-08446b2d422c.png)

![image](https://user-images.githubusercontent.com/11705430/111061453-28e0e200-84ac-11eb-8c8f-0bc027a8c3ff.png)

**Comment by gleb-cloudius** [comment]
On Sun, Mar 14, 2021 at 03:23:20AM -0700, Oren Efraimov wrote:
> Apparently, the test failed due to the commit  `51037e94e - lwt: handle an error during prune operation (4 weeks ago) <Gleb Natapov>`.
> @gleb-cloudius  Can you check it out?
> 
Well, before the patch the error was ignored, now it is printed.

--
			Gleb.

**Comment by Orenef11** [comment]
> On Sun, Mar 14, 2021 at 03:23:20AM -0700, Oren Efraimov wrote: Apparently, the test failed due to the commit `51037e94e - lwt: handle an error during prune operation (4 weeks ago) <Gleb Natapov>`. @gleb-cloudius Can you check it out?
> Well, before the patch the error was ignored, now it is printed.
> […](#)
> -- Gleb.

@roydahan 
Do you want me to ignore this error, and run the JOB again?

**Comment by roydahan** [comment]
1. We don’t know if it’s this specific commit that caused the regression.
2. It’s not related to the specific error -change the subject.

The main issue is the fact that the LWT stress is STOPPED during the prepare phase.
These errors may be the cause or a symptom but the stress failing is the main problem.

**Comment by slivne** [comment]
Lets start with the bisect the suspected part if the hard limit of the commitlog
- lets run again with the hard limit of commitlog commit and see if it reproduces
- if it does lets run with the commit before it - to prove its the commitlog change.

**Comment by slivne** [comment]
@slivne please provide the download place for the artifacts

**Comment by slivne** [comment]
@roydahan this are the commits to test:

*   4082f57ed - Merge 'Make commitlog disk limit a hard limit.' from Calle Wilund (2 weeks ago) <Avi Kivity>
    * s3://roy-rpms/perf2_1/scylla_perf_4082f57ed.tar.gz
* af2d1fa0d - Update abseil submodule (2 weeks ago) <Avi Kivity>
    * s3://roy-rpms/perf2_3/scylla_perf_af2d1fa0d.tar.gz 


taken from (https://docs.google.com/document/d/12u0l5b-H5QldV7GKgbq0CYU8vo0Wo0w5367cRasezfE/edit)

**Comment by fgelcer** [comment]
seeing this issue again:

*Installation details*
Kernel version: `5.11.11-1.el7.elrepo.x86_64`
Scylla version (or git commit hash): `4.5.dev-0.20210401.bb9a109c1 with build-id e083563e4f7ffef955a0820a479b4d9f5bb67ab3`
Cluster size: 4 nodes (i3.2xlarge)
Scylla running with shards number (live nodes):
   longevity-lwt-3h-master-db-node-e8457bad-1 (13.53.182.59 | 10.0.3.217): 8 shards
   longevity-lwt-3h-master-db-node-e8457bad-2 (13.48.106.117 | 10.0.1.249): 8 shards
   longevity-lwt-3h-master-db-node-e8457bad-3 (13.51.86.148 | 10.0.0.227): 8 shards
   longevity-lwt-3h-master-db-node-e8457bad-4 (13.49.226.118 | 10.0.1.153): 8 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0f6856044b4bc285d` (aws: eu-north-1)


Test: `longevity-lwt-3h-test`
Test name: `longevity_lwt_test.LWTLongevityTest.test_lwt_longevity`
Test config file(s):
- [longevity-lwt-basic-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/bddb74c85d77db6901179aa9b244456cf7aca521/test-cases/longevity/longevity-lwt-basic-3h.yaml)


**Issue description**

====================================

PUT ISSUE DESCRIPTION HERE


====================================






Restore Monitor Stack command: `$ hydra investigate show-monitor e8457bad-f86a-4dbc-81b0-1195191bfa14`
Show all stored logs command: `$ hydra investigate show-logs e8457bad-f86a-4dbc-81b0-1195191bfa14`

Test id: `e8457bad-f86a-4dbc-81b0-1195191bfa14`


Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/e8457bad-f86a-4dbc-81b0-1195191bfa14/20210402_045237/grafana-screenshot-longevity-lwt-3h-test-scylla-per-server-metrics-nemesis-20210402_045616-longevity-lwt-3h-master-monitor-node-e8457bad-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/e8457bad-f86a-4dbc-81b0-1195191bfa14/20210402_045237/grafana-screenshot-longevity-lwt-3h-test-scylla-per-server-metrics-nemesis-20210402_045616-longevity-lwt-3h-master-monitor-node-e8457bad-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/e8457bad-f86a-4dbc-81b0-1195191bfa14/20210402_045237/grafana-screenshot-overview-20210402_045237-longevity-lwt-3h-master-monitor-node-e8457bad-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/e8457bad-f86a-4dbc-81b0-1195191bfa14/20210402_045237/grafana-screenshot-overview-20210402_045237-longevity-lwt-3h-master-monitor-node-e8457bad-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/e8457bad-f86a-4dbc-81b0-1195191bfa14/20210402_050111/db-cluster-e8457bad.zip](https://cloudius-jenkins-test.s3.amazonaws.com/e8457bad-f86a-4dbc-81b0-1195191bfa14/20210402_050111/db-cluster-e8457bad.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/e8457bad-f86a-4dbc-81b0-1195191bfa14/20210402_050111/loader-set-e8457bad.zip](https://cloudius-jenkins-test.s3.amazonaws.com/e8457bad-f86a-4dbc-81b0-1195191bfa14/20210402_050111/loader-set-e8457bad.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/e8457bad-f86a-4dbc-81b0-1195191bfa14/20210402_050111/monitor-set-e8457bad.zip](https://cloudius-jenkins-test.s3.amazonaws.com/e8457bad-f86a-4dbc-81b0-1195191bfa14/20210402_050111/monitor-set-e8457bad.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/e8457bad-f86a-4dbc-81b0-1195191bfa14/20210402_050111/sct-runner-e8457bad.zip](https://cloudius-jenkins-test.s3.amazonaws.com/e8457bad-f86a-4dbc-81b0-1195191bfa14/20210402_050111/sct-runner-e8457bad.zip)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-lwt-3h-test/215/)

**Comment by roydahan** [comment]
> @roydahan this are the commits to test:
> 
> * [4082f57](https://github.com/scylladb/scylla/commit/4082f57edc3e7764e11e9e858a0a8059981c6309) - Merge 'Make commitlog disk limit a hard limit.' from Calle Wilund (2 weeks ago) 
>   
>   * s3://roy-rpms/perf2_1/scylla_perf_4082f57ed.tar.gz
> * [af2d1fa](https://github.com/scylladb/scylla/commit/af2d1fa0dee7a6a3fb7e75e97f658300c4bf0b08) - Update abseil submodule (2 weeks ago) 
>   
With these rpms it still fails.
>   * s3://roy-rpms/perf2_3/scylla_perf_af2d1fa0d.tar.gz
> 
Running now.
> taken from (https://docs.google.com/document/d/12u0l5b-H5QldV7GKgbq0CYU8vo0Wo0w5367cRasezfE/edit)

**Comment by slivne** [comment]
@elcallio / @slivne / @kostja this is a regression with the commitlog hard limit (QA did the bisect) need to be double check this is the cause and then figure out what todo.

**Comment by slivne** [comment]
potentially fixed by 8e808a56d2a9b12638b454005b95c88957f70b28

**Comment by ShlomiBalalis** [comment]
The issue reoccurred in the latest longevity-lwt-3h run in scylla master:
```
2021-04-25 04:41:10.000: (DatabaseLogEvent Severity.ERROR): type=DATABASE_ERROR regex=Exception  line_number=242259 node=Node longevity-lwt-3h-master-db-node-5176f0f0-3 [13.53.35.211 | 10.0.0.220] (seed: False)
2021-04-25T04:41:10+00:00  longevity-lwt-3h-master-db-node-5176f0f0-3 !ERR     | scylla:  [shard 5] paxos - CAS[187330] prune: failed exceptions::mutation_write_timeout_exception (Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE.)
2021-04-25 04:41:10.000: (DatabaseLogEvent Severity.ERROR): type=DATABASE_ERROR regex=Exception  line_number=242260 node=Node longevity-lwt-3h-master-db-node-5176f0f0-3 [13.53.35.211 | 10.0.0.220] (seed: False)
2021-04-25T04:41:10+00:00  longevity-lwt-3h-master-db-node-5176f0f0-3 !INFO    | scylla:  [shard 4] rpc - client 10.0.2.15:53428 msg_id 468264:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored
```

Scylla version: `4.6.dev-0.20210424.f7e00e781c2 with build-id cf643cfd81b2c4b5b659b84a6ba411aa1939581c`

Logs:
```
+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                                      Log links for testrun with test id 5176f0f0-34b6-4f4a-95f2-f294cdc7b154                                                                                                       |
+-----------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Date            | Log type    | Link                                                                                                                                                                                                                                               |
+-----------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 20210425_044155 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/5176f0f0-34b6-4f4a-95f2-f294cdc7b154/20210425_044155/grafana-screenshot-longevity-lwt-3h-test-scylla-per-server-metrics-nemesis-20210425_044320-longevity-lwt-3h-master-monitor-node-5176f0f0-1.png |
| 20210425_044155 | grafana     | https://cloudius-jenkins-test.s3.amazonaws.com/5176f0f0-34b6-4f4a-95f2-f294cdc7b154/20210425_044155/grafana-screenshot-overview-20210425_044155-longevity-lwt-3h-master-monitor-node-5176f0f0-1.png                                                |
| 20210425_044514 | db-cluster  | https://cloudius-jenkins-test.s3.amazonaws.com/5176f0f0-34b6-4f4a-95f2-f294cdc7b154/20210425_044514/db-cluster-5176f0f0.zip                                                                                                                        |
| 20210425_044514 | loader-set  | https://cloudius-jenkins-test.s3.amazonaws.com/5176f0f0-34b6-4f4a-95f2-f294cdc7b154/20210425_044514/loader-set-5176f0f0.zip                                                                                                                        |
| 20210425_044514 | monitor-set | https://cloudius-jenkins-test.s3.amazonaws.com/5176f0f0-34b6-4f4a-95f2-f294cdc7b154/20210425_044514/monitor-set-5176f0f0.zip                                                                                                                       |
| 20210425_044514 | sct-runner  | https://cloudius-jenkins-test.s3.amazonaws.com/5176f0f0-34b6-4f4a-95f2-f294cdc7b154/20210425_044514/sct-runner-5176f0f0.zip                                                                                                                        |
+-----------------+-------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
```

**Comment by elcallio** [comment]
It would probably help to up the log level for commitlog to at DEBUG iff we think that this is caused by said subsystem.

**Comment by slivne** [comment]
@elcallio  - We did a bisect - we found its in this commit - the regression what do we do now ?

OK - lets do that - @ShlomiBalalis - can you please have a run with DEBUG enabled for commitlog and collect the info so Calle can look at it - alternativly provide a staging job so calle can run whatever he wants.

**Comment by elcallio** [comment]
@slivne as far as I can tell, this was run with the verified deadlock fix applied. But the logs do not show any sign of things "stopping". So I would as usual suggest trying to find a smaller reproducer. Or at the very least more info - i.e. CL debug logs.

**Comment by elcallio** [comment]
Note that the cluster seems to be hung up on the first node, `longevity-lwt-3h-master-db-node-5176f0f0-1` - `10.0.2.15`. This however does not even mention any streaming/lwt related stuff. It just seems to be very busy doing repair and compaction.

One suggestion for these tests & logs: Provide a scylla log that is not from system log source. The problem is that once piped through systemd or whatever, all _level_ info is gone. So there is no nifty "info, debug, warn, error" hinting at which parts are more suspicious. 

Note that obviously your test running is regex:ing from a different source, as levels are in the quoted parts above...

**Comment by slivne** [comment]
@ShlomiBalalis is this happening in the populate phase or in a different phase - if this is happening post the populate phase and we can reproduce it - please create a different issue provide the reproducer - staging job and we can check it.

**Comment by aleksbykov** [comment]
Issue reproduced.
Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.6.dev-0.20210429.0e8818f6a`
Cluster size: 4 nodes (i3.2xlarge)
Scylla running with shards number (live nodes):
   longevity-lwt-3h-master-db-node-fe6df809-1 (13.48.55.111 | 10.0.3.235): 8 shards
   longevity-lwt-3h-master-db-node-fe6df809-2 (13.49.246.169 | 10.0.0.94): 8 shards
   longevity-lwt-3h-master-db-node-fe6df809-3 (13.49.224.6 | 10.0.3.42): 8 shards
   longevity-lwt-3h-master-db-node-fe6df809-4 (13.51.64.176 | 10.0.0.120): 8 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-030b85e78a28f3d3e` (aws: eu-north-1)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/fe6df809-f943-4f1c-9470-1d02573fdd9d/20210430_065605/db-cluster-fe6df809.zip](https://cloudius-jenkins-test.s3.amazonaws.com/fe6df809-f943-4f1c-9470-1d02573fdd9d/20210430_065605/db-cluster-fe6df809.zip)
[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-lwt-3h-test/227/)

**Comment by elcallio** [comment]
This log is borderline identical to the previous one. But it has not a single word about commit log. So I am given to assume that noone changed the log levels as I requested.

**Comment by roydahan** [comment]
@juliayakovlev can you please run a reproducer of this issue with commitlog set to debug level? 
Please work directly with @elcallio when you have the info.

It should be very easy to reproduce, just to run the longevity-lwt-3h and the stress will fail during populate phase.

**Comment by slivne** [comment]
@juliayakovlev / @roydahan ping

**Comment by elcallio** [comment]
Finally got a repro with proper commitlog info. Yes, we are hitting an apparent deadlock due to waiting for segments to be free. Which never happens for some shards, because we never ask to flush things. My initial guess here is that we've created a bunch of segments but did not really fill them, which breaks the condition for flushing in the timer callback.

**Comment by juliayakovlev** [comment]
@elcallio can I terminate the cluster?

**Comment by elcallio** [comment]
Can you archive all the db node logs first?

**Comment by juliayakovlev** [comment]
@elcallio yes, the logs will be collected in the end of test. If you need cluster I can keep it. And monitor

**Comment by juliayakovlev** [comment]
@elcallio 

Restore Monitor Stack command: $ hydra investigate show-monitor 2109d278-2ad0-433c-a004-53271d0dd7bf
Show all stored logs command: $ hydra investigate show-logs 2109d278-2ad0-433c-a004-53271d0dd7bf

Logs:
db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/2109d278-2ad0-433c-a004-53271d0dd7bf/20210519_122426/db-cluster-2109d278.zip
sct-runner - https://cloudius-jenkins-test.s3.amazonaws.com/2109d278-2ad0-433c-a004-53271d0dd7bf/20210519_122426/sct-runner-2109d278.zip

**Comment by elcallio** [comment]
So, I can't 100% tell from prometheus if my theory that we've managed to hit a corner case of usage visavi disk footprint or not, but I'd like to make a patch to

a.) Count "wasted space" - i.e. pre-allocated disk that did _not_ get data written, but remain in closed segments when determining flush or not
b.) increase the eagerness to flush to include "someone needs segments". 

@juliayakovlev can you re-run this (or tell me how to run and verify) with a patch applied?

**Comment by juliayakovlev** [comment]
> So, I can't 100% tell from prometheus if my theory that we've managed to hit a corner case of usage visavi disk footprint or not, but I'd like to make a patch to
> 
> a.) Count "wasted space" - i.e. pre-allocated disk that did _not_ get data written, but remain in closed segments when determining flush or not
> b.) increase the eagerness to flush to include "someone needs segments".
> 
> @juliayakovlev can you re-run this (or tell me how to run and verify) with a patch applied?

When you will apply the patch and create new ami, I can re-run the test, or you can do it, as you wish

**Comment by elcallio** [comment]
I have no idea on how to create an AMI. I was more thinking in the line of "check out code, apply patch, compile, run"...

**Comment by fgelcer** [comment]
> I have no idea on how to create an AMI. I was more thinking in the line of "check out code, apply patch, compile, run"...

if you can provide executables (RPMs or DEBs) in a S3 bucket, we can easily run it, or prepare a staging job for you, so you can only set your executables URL and that's it...

**Comment by elcallio** [comment]
Aha. How about providing a git repo + branch and hope there is some sort of automation for generating said things to said places? While I can build rpms, you kindof lost me at s3 bucket... :-)

**Comment by fgelcer** [comment]
> Aha. How about providing a git repo + branch and hope there is some sort of automation for generating said things to said places? While I can build rpms, you kindof lost me at s3 bucket... :-)

OK, create the RPMs, i will send you a S3 bucket you can use (you should install awscli in your machine, and then use a command as simple as `aws s3 cp <files_names> <s3_bucket_url>`)

**Comment by elcallio** [comment]
Right, what I sincerely hope is a patched version should now be in the bucket mentioned. Would be great to get the same test run, but using this build.

**Comment by fgelcer** [comment]
> Right, what I sincerely hope is a patched version should now be in the bucket mentioned. Would be great to get the same test run, but using this build.

@juliayakovlev is able to run a job with your RPMs, let's wait for results now

**Comment by fgelcer** [comment]
@elcallio , could you please provide us DEB files instead RPMs?
our tests are now running on the default base image (that is Ubuntu), so RPMs are not working for us...

**Comment by yarongilor** [comment]
according to Gleb, this issue is possibly reproduced in this Dtest:

https://jenkins.scylladb.com/job/scylla-master/job/byo/job/dtest-byo/539/consoleFull
```
17:34:07  Exception in thread Thread-6:
17:34:07  Traceback (most recent call last):
17:34:07    File "/usr/lib64/python3.7/threading.py", line 926, in _bootstrap_inner
17:34:07      self.run()
17:34:07    File "/usr/lib64/python3.7/threading.py", line 870, in run
17:34:07      self._target(*self._args, **self._kwargs)
17:34:07    File "/jenkins/workspace/scylla-master/byo/dtest-byo/scylla-dtest/alternator_tests.py", line 712, in writes
17:34:07      'v2': 'cat'})
17:34:07    File "/usr/local/lib/python3.7/site-packages/boto3/resources/factory.py", line 520, in do_action
17:34:07      response = action(self, *args, **kwargs)
17:34:07    File "/usr/local/lib/python3.7/site-packages/boto3/resources/action.py", line 83, in __call__
17:34:07      response = getattr(parent.meta.client, operation_name)(**params)
17:34:07    File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 276, in _api_call
17:34:07      return self._make_api_call(operation_name, kwargs)
17:34:07    File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 586, in _make_api_call
17:34:07      raise error_class(parsed_response, operation_name)
17:34:07  botocore.errorfactory.InternalServerError: An error occurred (InternalServerError) when calling the PutItem operation (reached max retries: 0): Internal server error: exceptions::mutation_write_timeout_exception (Operation timed out for alternator_test_putitem_contention_table.test_putitem_contention_table - received only 0 responses from 1 CL=LOCAL_SERIAL.)
17:34:07  
17:34:39  test_putitem_contention (alternator_tests.AlternatorTest) ... FAIL
```

**Comment by roydahan** [comment]
> @elcallio , could you please provide us DEB files instead RPMs?
> our tests are now running on the default base image (that is Ubuntu), so RPMs are not working for us...

@fgelcer / @juliayakovlev you can find in master also an AMI that is CentOS based.

**Comment by fgelcer** [comment]
> > @elcallio , could you please provide us DEB files instead RPMs?
> > our tests are now running on the default base image (that is Ubuntu), so RPMs are not working for us...
> 
> @fgelcer / @juliayakovlev you can find in master also an AMI that is CentOS based.

is SCT still succeed to run a longevity with a CentOS based AMI?

**Comment by roydahan** [comment]
Yes

**Comment by juliayakovlev** [comment]
Running the test with CentosOS ami: `ami-0d02c1bca2bcceb0b`

[Monitor](http://13.51.167.249:3000/d/A7GZJSqGk/longevity-lwt-3h-repr-8270-scylla-per-server-metrics-nemesis-master?orgId=1&from=1621510404000&to=now&refresh=30s)

[Job](https://jenkins.scylladb.com/view/master/job/scylla-master/job/reproducers/job/longevity-lwt-3h-repr-8270/7/console)

**Comment by juliayakovlev** [comment]
> Running the test with CentosOS ami: `ami-0d02c1bca2bcceb0b` and @elcallio rpms
> 
> [Monitor](http://13.51.167.249:3000/d/A7GZJSqGk/longevity-lwt-3h-repr-8270-scylla-per-server-metrics-nemesis-master?orgId=1&from=1621510404000&to=now&refresh=30s)
> 
> [Job](https://jenkins.scylladb.com/view/master/job/scylla-master/job/reproducers/job/longevity-lwt-3h-repr-8270/7/console)
> 
> Stress load is not stopped

The test with patch succeeded. Cluster and monitor are alive.
@elcallio do you need the cluster or I can terminate it?

**Comment by elcallio** [comment]
Is there any way to access the log files for the db nodes? I can't quite see where they are from the jenkins job...

**Comment by juliayakovlev** [comment]
@elcallio You can down all logs:

db-cluster - https://cloudius-jenkins-test.s3.amazonaws.com/3f9d2ac4-a7f9-48dd-80a6-2ba7a11ce0f6/20210520_150933/db-cluster-3f9d2ac4.zip

Also the cluster and all nodes are alive

**Comment by elcallio** [comment]
Ok, log more or less verifies my assumptions. You can kill the cluster. I will send a proper PR.

**Comment by avikivity** [comment]
Fix was reverted (d3e5b370591f443124c9cb1b304348869555cf71), reopening.

**Comment by slivne** [comment]
@avikivity please backport to 4.5 its blocking the release

**Comment by avikivity** [comment]
Backported to 4.5.

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
