### ISSUE TITLE
 Ubuntu package - Scylla service not available after 'cassandra-stress write'

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#829]
We got a problem during the daily testing of the scylla ubuntu packages. The scylla-service seems to be unavailable after a successful execution of cassandra-stress write.

How to reproduce:

1) Start cassandra-stress in write mode:

	18:41:26 process          L0272 INFO | Running '/usr/bin/cassandra-stress write n=1000000 -mode cql3 native'
	18:41:27 process          L0359 DEBUG| [stdout] INFO  23:41:27 Found Netty's native epoll transport in the classpath, using it
	18:41:27 process          L0359 DEBUG| [stdout] INFO  23:41:27 Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
	18:41:27 process          L0359 DEBUG| [stdout] INFO  23:41:27 New Cassandra host localhost/127.0.0.1:9042 added
	18:41:27 process          L0359 DEBUG| [stdout] Connected to cluster: Test Cluster
	18:41:27 process          L0359 DEBUG| [stdout] Datatacenter: datacenter1; Host: localhost/127.0.0.1; Rack: rack1
	18:41:30 process          L0359 DEBUG| [stdout] Created keyspaces. Sleeping 1s for propagation.
	18:41:31 process          L0359 DEBUG| [stdout] Sleeping 2s...
	18:41:33 process          L0359 DEBUG| [stdout] Warming up WRITE with 50000 iterations...
	18:41:41 process          L0359 DEBUG| [stdout] Running WRITE with 200 threads for 1000000 iteration
	18:41:41 process          L0359 DEBUG| [stdout] type,      total ops,    op/s,    pk/s,   row/s,    mean,     med,     .95,     .99,    .999,     max,   time,   stderr, errors,  gc: #,  max ms,  sum ms,  sdv ms,      mb
	18:41:43 process          L0359 DEBUG| [stdout] total,          9004,    9004,    9004,    9004,    21.8,    19.3,    38.7,    51.1,    60.1,   264.2,    1.0,  0.00000,      0,      2,      24,      41,       4,      24
	18:41:44 process          L0359 DEBUG| [stdout] total,         23861,   14484,   14484,   14484,    13.8,    12.7,    21.9,    64.7,    71.2,   121.4,    2.0,  0.18394,      0,      0,       0,       0,       0,       0
	18:41:45 process          L0359 DEBUG| [stdout] total,         44719,   20459,   20459,   20459,     9.8,     9.2,    16.1,    20.1,    22.1,    36.8,    3.0,  0.18115,      0,      0,       0,       0,       0,       0
	18:41:46 process          L0359 DEBUG| [stdout] total,         69062,   24050,   24050,   24050,     8.2,     7.7,    14.7,    27.6,    48.4,    61.6,    4.1,  0.16446,      0,      0,       0,       0,       0,       0
	18:41:47 process          L0359 DEBUG| [stdout] total,         92487,   21296,   21296,   21296,     9.4,     8.2,    18.2,    27.0,    50.0,    65.4,    5.2,  0.13198,      0,      0,       0,       0,       0,       0
	18:41:48 process          L0359 DEBUG| [stdout] total,        111674,   17344,   17344,   17344,    11.5,    10.1,    23.2,    28.7,    33.4,    51.6,    6.3,  0.11084,      0,      1,      45,      45,       0,      12
	18:41:49 process          L0359 DEBUG| [stdout] total,        130016,   17910,   17910,   17910,    11.2,    10.4,    20.3,    26.7,    34.2,    34.5,    7.3,  0.09501,      0,      0,       0,       0,       0,       0
	18:41:50 process          L0359 DEBUG| [stdout] total,        149718,   19349,   19349,   19349,    10.3,     9.7,    17.9,    23.1,    31.8,    33.2,    8.3,  0.08283,      0,      1,      33,      33,       0,      12
	18:41:51 process          L0359 DEBUG| [stdout] total,        169091,   18559,   18559,   18559,    10.7,     9.2,    23.0,    29.0,    39.4,    47.3,    9.3,  0.07346,      0,      0,       0,       0,       0,       0
	18:41:52 process          L0359 DEBUG| [stdout] total,        189740,   20065,   20065,   20065,    10.0,     9.2,    17.6,    23.7,    33.2,    39.8,   10.4,  0.06618,      0,      0,       0,       0,       0,       0
	18:41:53 process          L0359 DEBUG| [stdout] total,        206475,   16463,   16463,   16463,    12.2,    10.9,    25.4,    33.4,    35.3,    39.5,   11.4,  0.06138,      0,      1,      49,      49,       0,      12
	18:41:54 process          L0359 DEBUG| [stdout] total,        227211,   20194,   20194,   20194,     9.9,     9.2,    17.3,    22.0,    25.3,    25.7,   12.4,  0.05644,      0,      0,       0,       0,       0,       0
	18:41:55 process          L0359 DEBUG| [stdout] total,        247114,   19536,   19536,   19536,    10.2,     9.2,    18.1,    25.6,    33.2,    39.9,   13.4,  0.05206,      0,      0,       0,       0,       0,       0
	18:41:56 process          L0359 DEBUG| [stdout] total,        266874,   19339,   19339,   19339,    10.3,     9.9,    17.6,    23.2,    29.3,    38.0,   14.5,  0.04829,      0,      0,       0,       0,       0,       0
	18:41:57 process          L0359 DEBUG| [stdout] total,        286929,   19739,   19739,   19739,    10.2,     9.8,    17.0,    20.4,    24.8,    26.6,   15.5,  0.04508,      0,      0,       0,       0,       0,       0
	18:41:58 process          L0359 DEBUG| [stdout] total,        303897,   16596,   16596,   16596,    12.1,    11.1,    23.8,    28.1,    33.3,    33.6,   16.5,  0.04304,      0,      1,      31,      31,       0,      12
	18:41:59 process          L0359 DEBUG| [stdout] total,        322111,   17850,   17850,   17850,    11.2,    10.5,    20.8,    28.9,    44.2,    44.4,   17.5,  0.04062,      0,      2,     117,     149,      43,      43
	18:42:01 process          L0359 DEBUG| [stdout] total,        339858,   17233,   17233,   17233,    11.5,    10.8,    21.7,    31.7,    37.2,    37.5,   18.6,  0.03866,      0,      0,       0,       0,       0,       0
	18:42:02 process          L0359 DEBUG| [stdout] total,        360538,   20132,   20132,   20132,    10.0,     9.1,    17.1,    25.0,    30.6,    36.7,   19.6,  0.03678,      0,      0,       0,       0,       0,       0
	18:42:03 process          L0359 DEBUG| [stdout] total,        376174,   15342,   15342,   15342,    12.9,    10.7,    24.4,   101.8,   104.1,   105.1,   20.6,  0.03619,      0,      0,       0,       0,       0,       0
	18:42:04 process          L0359 DEBUG| [stdout] total,        395053,   18373,   18373,   18373,    11.0,     9.9,    22.2,    30.1,    35.8,    40.9,   21.6,  0.03446,      0,      1,      24,      24,       0,      12
	18:42:05 process          L0359 DEBUG| [stdout] total,        415487,   20038,   20038,   20038,    10.0,     9.4,    17.8,    21.6,    25.6,    33.0,   22.6,  0.03302,      0,      0,       0,       0,       0,       0
	18:42:06 process          L0359 DEBUG| [stdout] total,        435331,   19365,   19365,   19365,    10.3,     9.6,    19.3,    28.9,    41.8,    42.8,   23.7,  0.03167,      0,      0,       0,       0,       0,       0
	18:42:07 process          L0359 DEBUG| [stdout] total,        455844,   20220,   20220,   20220,     9.9,     9.5,    17.6,    22.4,    26.3,    28.6,   24.7,  0.03048,      0,      1,      38,      38,       0,      12
	18:42:08 process          L0359 DEBUG| [stdout] total,        475629,   19417,   19417,   19417,    10.3,     9.4,    18.3,    24.4,    30.5,    35.5,   25.7,  0.02927,      0,      0,       0,       0,       0,       0
	18:42:09 process          L0359 DEBUG| [stdout] total,        497050,   20252,   20252,   20252,     9.9,     9.5,    16.7,    23.2,    27.6,    37.0,   26.8,  0.02825,      0,      1,      38,      38,       0,      12
	18:42:10 process          L0359 DEBUG| [stdout] total,        517229,   19842,   19842,   19842,    10.0,     9.3,    17.1,    21.5,    24.3,    31.5,   27.8,  0.02725,      0,      0,       0,       0,       0,       0
	18:42:11 process          L0359 DEBUG| [stdout] total,        538013,   20606,   20606,   20606,     9.7,     9.7,    16.6,    20.0,    23.8,    26.3,   28.8,  0.02643,      0,      0,       0,       0,       0,       0
	18:42:12 process          L0359 DEBUG| [stdout] total,        559335,   20816,   20816,   20816,     9.6,     9.1,    17.0,    21.9,    25.3,    28.4,   29.8,  0.02570,      0,      0,       0,       0,       0,       0
	18:42:13 process          L0359 DEBUG| [stdout] total,        578128,   18530,   18530,   18530,    10.8,     9.7,    20.1,    24.6,    31.2,    34.5,   30.8,  0.02486,      0,      1,      37,      37,       0,      12
	18:42:14 process          L0359 DEBUG| [stdout] total,        599030,   20403,   20403,   20403,     9.8,     9.4,    16.5,    21.7,    26.0,    32.5,   31.8,  0.02414,      0,      0,       0,       0,       0,       0
	18:42:15 process          L0359 DEBUG| [stdout] total,        620095,   20591,   20591,   20591,     9.7,     9.1,    17.0,    20.2,    24.5,    30.7,   32.9,  0.02349,      0,      0,       0,       0,       0,       0
	18:42:16 process          L0359 DEBUG| [stdout] total,        641218,   20532,   20532,   20532,     9.7,     9.0,    17.8,    23.9,    28.6,    28.9,   33.9,  0.02286,      0,      1,      30,      30,       0,      12
	18:42:17 process          L0359 DEBUG| [stdout] total,        661984,   20424,   20424,   20424,     9.7,     9.2,    16.5,    20.7,    23.4,    24.1,   34.9,  0.02226,      0,      0,       0,       0,       0,       0
	18:42:18 process          L0359 DEBUG| [stdout] total,        679872,   17334,   17334,   17334,    11.5,    10.7,    22.1,    29.6,    32.6,    36.3,   36.0,  0.02181,      0,      1,      90,      90,       0,      12
	18:42:19 process          L0359 DEBUG| [stdout] total,        696860,   16533,   16533,   16533,    12.1,    11.8,    23.1,    29.3,    37.4,    45.8,   37.0,  0.02157,      0,      0,       0,       0,       0,       0
	18:42:20 process          L0359 DEBUG| [stdout] total,        717938,   20784,   20784,   20784,     9.7,     9.2,    15.8,    21.4,    24.8,    27.9,   38.0,  0.02110,      0,      0,       0,       0,       0,       0
	18:42:21 process          L0359 DEBUG| [stdout] total,        739211,   20693,   20693,   20693,     9.7,     9.5,    15.8,    20.4,    26.8,    28.9,   39.0,  0.02064,      0,      0,       0,       0,       0,       0
	18:42:22 process          L0359 DEBUG| [stdout] total,        759967,   20376,   20376,   20376,     9.8,     9.4,    16.3,    20.6,    32.7,    33.3,   40.0,  0.02015,      0,      0,       0,       0,       0,       0
	18:42:23 process          L0359 DEBUG| [stdout] total,        778456,   17866,   17866,   17866,    11.2,    10.6,    21.7,    28.4,    33.9,    52.0,   41.1,  0.01974,      0,      2,     123,     147,      50,      44
	18:42:24 process          L0359 DEBUG| [stdout] total,        797753,   18969,   18969,   18969,    10.5,     9.8,    18.4,    26.6,    32.4,    34.1,   42.1,  0.01926,      0,      1,      22,      22,       0,      12
	18:42:25 process          L0359 DEBUG| [stdout] total,        819217,   20198,   20198,   20198,     9.9,     9.1,    16.6,    24.3,    28.4,    29.1,   43.2,  0.01883,      0,      0,       0,       0,       0,       0
	18:42:26 process          L0359 DEBUG| [stdout] total,        839594,   19181,   19181,   19181,    10.4,     9.3,    19.6,    34.3,    37.7,    39.3,   44.2,  0.01840,      0,      0,       0,       0,       0,       0
	18:42:27 process          L0359 DEBUG| [stdout] total,        860512,   20457,   20457,   20457,     9.8,     9.3,    16.1,    22.3,    26.7,    27.3,   45.2,  0.01803,      0,      0,       0,       0,       0,       0
	18:42:28 process          L0359 DEBUG| [stdout] total,        877363,   16203,   16203,   16203,    12.4,     9.6,    21.2,   156.6,   160.5,   173.2,   46.3,  0.01763,      0,      1,      32,      32,       0,      12
	18:42:29 process          L0359 DEBUG| [stdout] total,        897743,   19725,   19725,   19725,    10.1,     9.3,    17.8,    28.6,    42.8,    43.2,   47.3,  0.01725,      0,      0,       0,       0,       0,       0
	18:42:30 process          L0359 DEBUG| [stdout] total,        918195,   19637,   19637,   19637,    10.2,     9.5,    18.8,    22.8,    36.2,    36.6,   48.4,  0.01689,      0,      0,       0,       0,       0,       0
	18:42:31 process          L0359 DEBUG| [stdout] total,        939281,   20556,   20556,   20556,     9.7,     9.3,    16.2,    22.5,    27.1,    29.0,   49.4,  0.01658,      0,      0,       0,       0,       0,       0
	18:42:32 process          L0359 DEBUG| [stdout] total,        959544,   19258,   19258,   19258,    10.3,     9.7,    18.3,    25.1,    31.5,    32.1,   50.4,  0.01624,      0,      1,      36,      36,       0,      12
	18:42:33 process          L0359 DEBUG| [stdout] total,        978135,   17325,   17325,   17325,    11.6,     9.9,    23.2,    42.1,    52.1,    59.2,   51.5,  0.01606,      0,      1,      34,      34,       0,      12
	18:42:35 process          L0359 DEBUG| [stdout] total,        998687,   20107,   20107,   20107,     9.9,     9.3,    17.6,    21.9,    28.8,    32.6,   52.5,  0.01576,      0,      0,       0,       0,       0,       0
	18:42:35 process          L0359 DEBUG| [stdout] total,       1000000,   17077,   17077,   17077,    11.5,    11.4,    18.6,    22.5,    23.2,    23.2,   52.6,  0.01562,      0,      0,       0,       0,       0,       0
	18:42:35 process          L0359 DEBUG| [stdout] 
	18:42:35 process          L0359 DEBUG| [stdout] 
	18:42:35 process          L0359 DEBUG| [stdout] Results:
	18:42:35 process          L0359 DEBUG| [stdout] op rate                   : 19010 [WRITE:19010]
	18:42:35 process          L0359 DEBUG| [stdout] partition rate            : 19010 [WRITE:19010]
	18:42:35 process          L0359 DEBUG| [stdout] row rate                  : 19010 [WRITE:19010]
	18:42:35 process          L0359 DEBUG| [stdout] latency mean              : 10.5 [WRITE:10.5]
	18:42:35 process          L0359 DEBUG| [stdout] latency median            : 9.5 [WRITE:9.5]
	18:42:35 process          L0359 DEBUG| [stdout] latency 95th percentile   : 18.5 [WRITE:18.5]
	18:42:35 process          L0359 DEBUG| [stdout] latency 99th percentile   : 25.2 [WRITE:25.2]
	18:42:35 process          L0359 DEBUG| [stdout] latency 99.9th percentile : 41.1 [WRITE:41.1]
	18:42:35 process          L0359 DEBUG| [stdout] latency max               : 264.2 [WRITE:264.2]
	18:42:35 process          L0359 DEBUG| [stdout] Total partitions          : 1000000 [WRITE:1000000]
	18:42:35 process          L0359 DEBUG| [stdout] Total errors              : 0 [WRITE:0]
	18:42:35 process          L0359 DEBUG| [stdout] total gc count            : 20
	18:42:35 process          L0359 DEBUG| [stdout] total gc mb               : 280
	18:42:35 process          L0359 DEBUG| [stdout] total gc time (s)         : 1
	18:42:35 process          L0359 DEBUG| [stdout] avg gc time(ms)           : 44
	18:42:35 process          L0359 DEBUG| [stdout] stdev gc time(ms)         : 29
	18:42:35 process          L0359 DEBUG| [stdout] Total operation time      : 00:00:52
	18:42:35 process          L0359 DEBUG| [stdout] END

2) Run cassandra-stress in mixed mode. This will yield an execution with loads of NoHostAvailableException thrown by cassandra-stress:

	18:42:37 process          L0272 INFO | Running '/usr/bin/cassandra-stress mixed duration=2m -mode cql3 native -rate threads=100'
	18:42:38 process          L0359 DEBUG| [stdout] Sleeping 2s...
	18:42:40 process          L0359 DEBUG| [stdout] Warming up READ with 50000 iterations...
	18:42:40 process          L0359 DEBUG| [stdout] INFO  23:42:40 Found Netty's native epoll transport in the classpath, using it
	18:42:41 process          L0359 DEBUG| [stdout] INFO  23:42:41 Using data-center name 'datacenter1' for DCAwareRoundRobinPolicy (if this is incorrect, please provide the correct datacenter name with DCAwareRoundRobinPolicy constructor)
	18:42:41 process          L0359 DEBUG| [stdout] INFO  23:42:41 New Cassandra host localhost/127.0.0.1:9042 added
	18:42:41 process          L0359 DEBUG| [stdout] Connected to cluster: Test Cluster
	18:42:41 process          L0359 DEBUG| [stdout] Datatacenter: datacenter1; Host: localhost/127.0.0.1; Rack: rack1
	18:42:55 process          L0359 DEBUG| [stderr] com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.OperationTimedOutException: [localhost/127.0.0.1:9042] Operation timed out))
	18:42:55 process          L0359 DEBUG| [stderr] com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.OperationTimedOutException: [localhost/127.0.0.1:9042] Operation timed out))
	18:42:55 process          L0359 DEBUG| [stderr] com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.OperationTimedOutException: [localhost/127.0.0.1:9042] Operation timed out))
	18:42:55 process          L0359 DEBUG| [stderr] com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.OperationTimedOutException: [localhost/127.0.0.1:9042] Operation timed out))
    ...

The root cause is unclear - It's like the scylla services died and never came back after the write() workload is executed.

Additional info:

The services appear to be up, but the actual services in port 7199 (JMX) and 9042 (Scylla) are not up.

	18:49:51 process          L0272 INFO | Running 'service scylla-server status'
	18:49:51 process          L0359 DEBUG| [stdout] scylla-server start/running, process 7322
	18:49:51 service          L0562 DEBUG| Setting ignore_status to True.
	18:49:51 process          L0272 INFO | Running 'service scylla-jmx status'
	18:49:51 process          L0359 DEBUG| [stdout] scylla-jmx stop/waiting
	18:49:51 process          L0272 INFO | Running '/usr/bin/nodetool status'
	18:49:53 process          L0359 DEBUG| [stderr] nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused'.

Scylla Ubuntu package version:

Repository: https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/ubuntu/master/60/scylla.list
Packages:

	18:40:49 process          L0359 DEBUG| [stdout] Get:1 http://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/ubuntu/master/60/ trusty/scylladb/multiverse libthrift0 amd64 0.9.1-ubuntu1 [211 kB]
	18:40:50 process          L0359 DEBUG| [stdout] Get:2 http://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/ubuntu/master/60/ trusty/scylladb/multiverse scylla-server amd64 666.development-20160119.bd34adc-ubuntu1 [5,914 kB]
	18:40:58 process          L0359 DEBUG| [stdout] Get:1 http://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/ubuntu/master/60/ trusty/scylladb/multiverse scylla-jmx all 666.development-20160119.b6d55f0-ubuntu1 [5,508 kB]
	18:41:15 process          L0359 DEBUG| [stdout] Get:1 http://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/ubuntu/master/60/ trusty/scylladb/multiverse scylla-tools all 0.10-20160119.7e5bd9e-ubuntu1 [19.8 MB]

**Comment by lmr** [comment]
@slivne @syuu1228, FYI

**Comment by avikivity** [comment]
Anything in the server logs?

**Comment by lmr** [comment]
@avikivity, Today's build is back to normal, the problem mysteriously disappeared. 

I guess I need to start storing the server logs in the artifacts test. Sorry about the omission.

**Comment by lmr** [comment]
So I'm closing this one, as the problem is gone in build 61.
