### ISSUE TITLE
gdb crashes on centos

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#831]
```
# gdb /usr/bin/scylla core.scylla 
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-80.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/bin/scylla...Reading symbols from /usr/lib/debug/usr/bin/scylla.debug...Segmentation fault (core dumped)
```

this is a known gdb bug which was already fixed upstream and in Fedora 23, but that doesn't help someone who debugs on centos.  We need a scylla-gdb package (like we have scylla-gcc) so we can debug properly.

**Comment by avikivity** [comment]
@syuu1228

**Comment by avikivity** [comment]
@syuu1228 the package isn't in the repository, where can I find it?

**Comment by syuu1228** [comment]
There was bug which doesn't able to build scylla-gdb on clean VM, I sent a
patch to fix it by adding missing dependencies, so I think jenkins now able
to build new one

**Comment by tgrabiec** [comment]
@syuu1228 Is it possible to install `scylla-gdb` already?

**Comment by slivne** [comment]
yes it is

if you use our repo files then simply install scylla-gdb

**Comment by tgrabiec** [comment]
@slivne I tried but it doesn't find the package (I have 0.16 installed):

```
$ sudo yum install scylla-gdb
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.kernel.org
 * elrepo: ftp.osuosl.org
 * epel: s3-mirror-us-west-2.fedoraproject.org
 * extras: mirrors.syringanetworks.net
 * updates: mirror.hmc.edu
No package scylla-gdb available.
```

I followed http://www.scylladb.com/doc/getting-started-rpm/#rhel-7centos-7 and tried `sudo wget -O /etc/yum.repos.d/scylla.repo http://downloads.scylladb.com/rpm/unstable/centos/master/latest/scylla.repo`. 

Do I have to run some extra commands?

**Comment by slivne** [comment]
just to make sure after the repo install, you did the sudo yum install
scylla-gdb ?


did you install epel-release ?

in any case here is the direct link
https://s3.amazonaws.com/downloads.scylladb.com/rpm/unstable/centos/master/latest/3rdparty/7/x86_64/scylla-gdb-7.10.1-30.el7.centos.x86_64.rpm

I installed from the repo today and it worked for me will test it again
tomorrow

**Comment by tgrabiec** [comment]
@slivne Yes, I tried to install after repo install. I also did install epel-release. I can't test it now because the machine is not gone. Thanks for help.
