### ISSUE TITLE
lwt_test: read_linearizability_test: failed assert ret[0].applied == False

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8331]
Regression seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/747/testReport/lwt_test/LwtReadLinearizabilityTest/read_linearizability_test/
Scylla version 35a14ab22b0e983e5d21cf203b1aa0e80103aa69
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/lwt_test.py", line 724, in read_linearizability_test
    assert ret[0].applied == False
AssertionError
```

**Comment by bhalevy** [comment]
@kostja please look into this

**Comment by bhalevy** [comment]
Failed exactly the same in https://jenkins.scylladb.com/view/nexts/job/scylla-4.4/job/dtest-debug/41/testReport/
scylla-4.4 version dffbcabbb1c1198810a2603bdecb08524d033374
Passed in the previous run at ff585e083456909fa761adb66df1bd7939b3e02a

**Comment by kostja** [comment]
Looks like another manifestation of #8332, the assertion follows a statement which should fail on injection, and it doesn't.

**Comment by bhalevy** [comment]
Duplicate of #8332
