### ISSUE TITLE
All paxos dtests failed with AssertionError: WriteFailure not raised

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8332]
Regression seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/747/testReport/paxos_tests/TestPaxos/
Scylla version 35a14ab22b0e983e5d21cf203b1aa0e80103aa69
scylladb/scylla-dtest@ef37a9d993a84ef55b031cc92d473bfe3b9d7fb6
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/paxos_tests.py", line 420, in schema_mismatch_cache_test
    self._schema_mismatch_tpl(clear_schema_cache=False)
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/paxos_tests.py", line 414, in _schema_mismatch_tpl
    verify_results_action=check_schema_mismatch_exc
  File "/jenkins/workspace/scylla-master/dtest-debug/scylla-dtest/paxos_tests.py", line 351, in _base_schema_mismatch_test_tpl
    insert_action(session, key)
  File "/usr/lib64/python3.7/unittest/case.py", line 220, in __exit__
    self._raiseFailure("{} not raised".format(exc_name))
  File "/usr/lib64/python3.7/unittest/case.py", line 136, in _raiseFailure
    raise self.test_case.failureException(msg)
AssertionError: WriteFailure not raised
```

I see no error injected in the node log (expected to see `Enabling injection`).
I suspected 29a504798297876f2c831b30f4d3bf5b6cce8ebb at first, but this test injects `paxos_error_after_save_proposal`
which uses the `get_local_injector().enter`, not `inject`, so the above change shouldn't effect it at all.

Last passed in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/744/testReport/paxos_tests/TestPaxos/
scylla version f2ecb4617e479c9803e589ffd1b1e92abc47f472
scylladb/scylla-dtest@87768db5fd4da774a64cb5a4aa27e32dd3171c0a

**Comment by bhalevy** [comment]
@kostja / @alecco please look into this

**Comment by bhalevy** [comment]
Failed exactly the same in https://jenkins.scylladb.com/view/nexts/job/scylla-4.4/job/dtest-debug/41/testReport/
scylla-4.4 version dffbcabbb1c1198810a2603bdecb08524d033374
Passed in the previous run at ff585e083456909fa761adb66df1bd7939b3e02a

**Comment by kostja** [comment]
The test itself looks correct, and one possible explanation could be that the build used did not have error injections enabled. Have there been other failures since Mar 22?

**Comment by kostja** [comment]
Apart from using a release build in an error-injection based test, I fail to find an explanation for this failure. The test works fine locally when using dev or debug builds. The only commit into error injection code was from Avi, on March 21: https://github.com/scylladb/scylla/pull/8322/commits/8f0eef5dae5f716fad5a468d8f50285d823ac152 which could be the potential trigger of the problem.
I fail, however, to find a connection between this connect and a sporadic failure of the test.
I suggest we revisit this issue when it is reproduced again, then revert Avi's commit and see if it has any impact. 
In future, to speed up research of flaky failures like these, it is necessary to preserve the virtual build environment in which the test failed.

**Comment by bhalevy** [comment]
These test failed on jenkins every time since job number 747.
See https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/747/testReport/paxos_tests/TestPaxos/history/

**Comment by bhalevy** [comment]
@yaronkaikov / @hagitsegev  it looks like dtest-debug is using the release reloc package rather than the debug one.
See https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/764/artifact/logs-all.debug.2/1618030643922_paxos_tests.TestPaxos.schema_mismatch_cache_test/node1.log
```
Scylla version 4.6.dev-0.20210409.305372820 with build-id 70181ea1adfaecb18f767dcdd6f960e96f147402 starting ...
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-debug/764/artifact/00-Build.txt
```
scylla-BuildID[sha1]: 70181ea1adfaecb18f767dcdd6f960e96f147402
scylla-debug-BuildID[sha1]: 5b682d6e00ac895cc85537b8dbaa4cc5a1866f35
```

**Comment by yaronkaikov** [comment]
@bhalevy Found the problem. looks like we are downloading from S3 (since we are using spot) the wrong reloc file. 
Will send a patch to fix soon
