### ISSUE TITLE
Do not enable the Thrift server by default

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#8336]
Currently, the Thrift port (default: 9160) is always open when Scylla starts, but it's not clear if anyone actually uses it. Since this layer, while functional, is not tested and maintained as actively as CQL, it should be off by default.

**Comment by tzach** [comment]
Dup of (closed) #205

**Comment by nyh** [comment]
@tzach, that issue was closed 6 years (!) ago, but evidentally at some point it came back?!  
See also #3811, which is about deprecating and removing Thift completely. The first step to doing it should indeed be this issue - making it off by default.

**Comment by psarna** [comment]
It's not a dup of #205 . It was about not enabling a partial implementation by default, and it was later enabled:
```
commit aff8cf319d1911ea2b8b3a842d868f27ea3d6793
Author: Pekka Enberg <penberg@scylladb.com>
Date:   Wed Jul 20 11:06:40 2016 +0300

    db/config: Start Thrift server by default
    
    We have Thrift support now so start the server by default.
    Message-Id: <1469002000-26767-1-git-send-email-penberg@scylladb.com>
```

This issue is about not enabling it due to being old, which is slightly different :)

**Comment by tzach** [comment]
Fair enough, not a dup

**Comment by avikivity** [comment]
Defaults change, not backporting.
