### ISSUE TITLE
scylla_ntp_setup: Use systemd-timesyncd instead of chrony when it's installed by default

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#8339]
systemd added NTP client since systemd 213, called systemd-timesyncd.
Seems like RHEL8/CentOS8 disabling it, but on Ubuntu it's the default installed NTP client.
To skip installing unnecessary package, and follow distribution default configuration, use systemd-timesyncd instead of chrony on Ubuntu.

See: https://ubuntu.com/server/docs/network-ntp

It says:

_Since Ubuntu 16.04 timedatectl / timesyncd (which are part of systemd) replace most of ntpdate / ntp.
timesyncd is available by default and replaces not only ntpdate, but also the client portion of chrony (or formerly ntpd)._

**Comment by syuu1228** [comment]
Seems like Debian is same.
Probably most of the distribution except RHEL7/8 variants does support this by default, since this is part of systemd.

**Comment by avikivity** [comment]
Enhancement, not backporting.
