### ISSUE TITLE
AMI ami-ac4f69c6 (Scylla 0.16): When stop/start instance, scylla fails to start

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#834]
Running the cluster tests, I've noticed that when you:

1) Create a scylla DB cluster
2) Start a cassandra-stress load on the cluster
3) Pick one of the nodes, stop it on AWS
4) Start the previously stopped node on AWS

This will cause the node to never start back their scylla services. I spent time observing that behavior, and could trace it back to the fact that the scylla init scripts run again, including the reflector service scripts:

	Jan 20 23:47:07 ip-172-30-0-95.ec2.internal systemd[1]: Starting Scylla Server...
	Jan 20 23:47:08 ip-172-30-0-95.ec2.internal sudo[747]:   scylla : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/lib/scylla/scylla_prepare
	Jan 20 23:47:08 ip-172-30-0-95.ec2.internal sudo[747]: RAID does not constructed, going to initialize...
	Jan 20 23:47:10 ip-172-30-0-95.ec2.internal sudo[747]: Loaded plugins: fastestmirror, langpacks
	Jan 20 23:47:10 ip-172-30-0-95.ec2.internal sudo[747]: Loading mirror speeds from cached hostfile
	Jan 20 23:47:10 ip-172-30-0-95.ec2.internal sudo[747]: * base: mirror.cc.columbia.edu
	Jan 20 23:47:10 ip-172-30-0-95.ec2.internal sudo[747]: * elrepo: reflector.westga.edu
	Jan 20 23:47:10 ip-172-30-0-95.ec2.internal sudo[747]: * epel: s3-mirror-us-east-1.fedoraproject.org
	Jan 20 23:47:10 ip-172-30-0-95.ec2.internal sudo[747]: * extras: mirror.atlanticmetro.net
	Jan 20 23:47:10 ip-172-30-0-95.ec2.internal sudo[747]: * updates: mirror.solarvps.com
	Jan 20 23:47:13 ip-172-30-0-95.ec2.internal sudo[747]: No packages marked for update
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: Waiting for cloud-init to finish...
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] Started with user data set to:
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] --clustername scylla-db-cluster-d6abf6ba --totalnodes 6
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] Using user data:
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] --clustername scylla-db-cluster-d6abf6ba --totalnodes 6
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] Using instance type: m3.large
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] meta-data:instance-type: m3.large
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] meta-data:local-ipv4: 172.30.0.95
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] meta-data:public-hostname: <same as local-ipv4>
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] meta-data:ami-launch-index: 5
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] meta-data:reservation-id: r-2f6ef587
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] Using cluster name: scylla-db-cluster-d6abf6ba
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] Using cluster size: 6
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] Using seed indexes: [0, 6, 6]
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] Reflector loop...
	Jan 20 23:49:47 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] 01/20/16-23:47:23 Reflector: Received 0 of 1 responses from: []
	...
	Jan 20 23:55:40 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] 01/20/16-23:55:37 Reflector: Received 0 of 1 responses from: []
	Jan 20 23:57:24 ip-172-30-0-95.ec2.internal python[1948]: detected unhandled Python exception in '/usr/lib/scylla/scylla-ami/ds2_configure.py'
	Jan 20 23:57:24 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] 01/20/16-23:55:40 Reflector: Received 0 of 1 responses from: []
	...
	Jan 20 23:57:24 ip-172-30-0-95.ec2.internal sudo[747]: [INFO] 01/20/16-23:57:22 Reflector: Received 0 of 1 responses from: []
	Jan 20 23:57:24 ip-172-30-0-95.ec2.internal sudo[747]: [ERROR] EC2 is experiencing some issues and has not allocated all of the resources in under 10 minutes.
	Jan 20 23:57:24 ip-172-30-0-95.ec2.internal sudo[747]: Aborting the clustering of this reservation. Please try again.
	Jan 20 23:57:24 ip-172-30-0-95.ec2.internal sudo[747]: Traceback (most recent call last):
	Jan 20 23:57:24 ip-172-30-0-95.ec2.internal sudo[747]: File "/usr/lib/scylla/scylla-ami/ds2_configure.py", line 479, in <module>
	Jan 20 23:57:24 ip-172-30-0-95.ec2.internal systemd[1]: scylla-server.service: control process exited, code=exited status=1
	Jan 20 23:57:24 ip-172-30-0-95.ec2.internal systemd[1]: Failed to start Scylla Server.
	Jan 20 23:57:24 ip-172-30-0-95.ec2.internal systemd[1]: Unit scylla-server.service entered failed state.
	Jan 20 23:57:24 ip-172-30-0-95.ec2.internal systemd[1]: scylla-server.service failed.

So as you can see by the log, it runs once again the init scripts with the previously passed parameters `--clustername scylla-db-cluster-d6abf6ba --totalnodes 6`. Either I'm missing something, or we have a bug in the init scripts. They should detect that node was already initialized and skip that script.

**Comment by lmr** [comment]
@slivne @syuu1228, what do you say?

**Comment by lmr** [comment]
I tried to repeat the test with Cassandra nodes, but turns out their AMI can't actually be stopped:

**Comment by lmr** [comment]
22:59:49 output           L0332 DEBUG| ClientError: An error occurred (UnsupportedOperation) when calling the StopInstances operation: The instance 'i-f3a5b172' does not have an 'ebs' root device type and cannot be stopped.

**Comment by lmr** [comment]
Instance type is `m3.large`.

**Comment by syuu1228** [comment]
Right now ds2_configure.py runs at every scylla-server.service startup, if this is bug when do we run it?
Only once, even beyond instance shutdown/restart? Or once on every instance startup?

**Comment by dorlaor** [comment]
On Thu, Jan 21, 2016 at 2:22 PM, Takuya ASADA <notifications@github.com>
wrote:

> Right now ds2_configure.py runs at every scylla-server.service startup, if
> this is bug when do we run it?
> Only once, even beyond instance shutdown/restart? Or once on every
> instance startup?
>

Probably just once is needed. Otherwise files will change under our feet.

**Comment by avikivity** [comment]
I think we should run it only once, and it should be a separate service, that scylla-server depends on.

**Comment by syuu1228** [comment]
Patch sent for this.

**Comment by slivne** [comment]
scylla-ami@e284bcd361cee3293ad5fcb0b5e0dc0323401846
