### ISSUE TITLE
Add infrastructure for virtual tables

### ISSUE THREAD

**Issue by jul-stas** [scylladb/scylla#8343]
Cut out the relevant parts from https://github.com/scylladb/scylla-dev/tree/call, add tests and upstream it.
Possibly also apply the fixes listed here: https://www.scylladb.com/2020/12/29/scylladb-developer-hackathon-managing-scylla-using-cql/

**Comment by raphaelsc** [comment]
this will open very interesting opportunities, like retrieving sstable layout per table per shard.

**Comment by avikivity** [comment]
Not a bug, not backporting.
