### ISSUE TITLE
Significant write amplification when reshaping level 0 in a LCS table

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#8345]
Reshape for LCS table has significant write amplification because data in L0 is recompacted, in a major compaction like approach, until L0 contains less than a target amount of sstables.

**Comment by raphaelsc** [comment]
@avikivity can we please backport this?

**Comment by avikivity** [comment]
Does it fix a regression? relative to what version?

**Comment by raphaelsc** [comment]
it's a problem since reshape was introduced. I think it's worth backporting this as LCS users may suffer with a terribly long reshape on boot.

**Comment by raphaelsc** [comment]
commit 3c254dd49d

**Comment by avikivity** [comment]
Backported to 4.3, 4.4. 4.5 already had it.

**Comment by raphaelsc** [comment]
thanks a lot, Avi.
