### ISSUE TITLE
install-dependencies.sh fails on A64FX, Fedora 33 

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [scylladb/scylla#8346]
It has to run with 'sudo', however: 

(base) [jw@cn05 scylladb]$ sudo ./install-dependencies.sh 
...
  perl-Want-0.29-16.fc33.aarch64                                 perl-strictures-2.000006-9.fc33.noarch
  po-debconf-1.0.21-4.fc33.noarch                                python-rpm-macros-3.9-14.fc33.noarch
  python2-rpm-macros-3.9-14.fc33.noarch                          python3-boto3-1.16.63-1.fc33.noarch
  python3-botocore-1.19.63-1.fc33.noarch                         python3-colorama-0.4.3-3.fc33.noarch
  python3-file-magic-5.39-3.fc33.noarch                          python3-iniconfig-1.0.0-2.fc33.noarch
  python3-jmespath-0.9.4-6.fc33.noarch                           python3-more-itertools-8.4.0-1.fc33.noarch
  python3-packaging-20.4-2.fc33.noarch                           python3-pluggy-0.13.1-2.fc33.noarch
  python3-py-1.10.0-1.fc33.noarch                                python3-pytest-6.0.2-1.fc33.noarch
  python3-pyudev-0.22.0-3.fc33.noarch                            python3-redis-3.5.3-1.fc33.noarch
  python3-rpm-generators-11-11.fc33.noarch                       python3-rpm-macros-3.9-14.fc33.noarch
  python3-s3transfer-0.3.4-1.fc33.noarch                         python3-urwid-2.1.2-1.fc33.aarch64
  rapidjson-devel-1.1.0-15.fc33.aarch64                          rpm-build-4.16.1.2-1.fc33.aarch64
  sensible-utils-0.0.12-6.fc33.noarch                            stringtemplate4-4.3.1-4.fc33.noarch
  systemd-devel-246.10-1.fc33.aarch64                            xxhash-devel-0.8.0-1.fc33.aarch64
  xz-lzma-compat-5.2.5-4.fc33.aarch64                            zstd-1.4.9-1.fc33.aarch64

Complete!
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff8d01b460>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/cassandra-driver/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff8d01b6a0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/cassandra-driver/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffff8d01b160>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/cassandra-driver/
^CERROR: Operation cancelled by user
(base) [jw@cn05 scylladb]$ clear
(base) [jw@cn05 scylladb]$ (base) [jw@cn05 scylladb]$ sudo ./install-dependencies.sh
Last metadata expiration check: 0:18:25 ago on Mon Mar 22 16:06:54 2021.
Package hwloc-devel-2.2.0-1.fc33.aarch64 is already installed.
Package numactl-devel-2.0.14-1.fc33.aarch64 is already installed.
Package libpciaccess-devel-0.16-3.fc33.aarch64 is already installed.
Package cryptopp-devel-8.2.0-4.fc33.aarch64 is already installed.
Package libxml2-devel-2.9.10-8.fc33.aarch64 is already installed.
Package xfsprogs-devel-5.7.0-1.fc33.aarch64 is already installed.
Package gnutls-devel-3.6.15-1.fc33.aarch64 is already installed.
Package lksctp-tools-devel-1.0.18-6.fc33.aarch64 is already installed.
Package lz4-devel-1.9.1-3.fc33.aarch64 is already installed.
Package gcc-10.2.1-9.fc33.aarch64 is already installed.
Package make-1:4.3-2.fc33.aarch64 is already installed.
Package protobuf-devel-3.12.4-1.fc33.aarch64 is already installed.
Package protobuf-compiler-3.12.4-1.fc33.aarch64 is already installed.
Package python3-3.9.2-1.fc33.aarch64 is already installed.
Package systemtap-sdt-devel-4.4-3.fc33.aarch64 is already installed.
Package libtool-2.4.6-36.fc33.aarch64 is already installed.
Package cmake-3.18.4-2.fc33.aarch64 is already installed.
Package yaml-cpp-devel-0.6.3-3.fc33.aarch64 is already installed.
Package c-ares-devel-1.17.0-1.fc33.aarch64 is already installed.
Package stow-2.3.1-3.fc33.noarch is already installed.
Package diffutils-3.7-7.fc33.aarch64 is already installed.
Package doxygen-1:1.8.20-4.fc33.aarch64 is already installed.
Package openssl-1:1.1.1i-3.fc33.aarch64 is already installed.
Package fmt-devel-7.0.3-1.fc33.aarch64 is already installed.
Package boost-devel-1.73.0-9.fc33.aarch64 is already installed.
Package valgrind-devel-1:3.16.1-18.fc33.aarch64 is already installed.
Package libtool-ltdl-devel-2.4.6-36.fc33.aarch64 is already installed.
Package trousers-devel-0.3.14-4.fc33.aarch64 is already installed.
Package libidn2-devel-2.3.0-4.fc33.aarch64 is already installed.
Package libunistring-devel-0.9.10-9.fc33.aarch64 is already installed.
Package gcc-c++-10.2.1-9.fc33.aarch64 is already installed.
Package ninja-build-1.10.2-1.fc33.aarch64 is already installed.
Package ragel-7.0.0.12-4.fc33.aarch64 is already installed.
Package libubsan-10.2.1-9.fc33.aarch64 is already installed.
Package libasan-10.2.1-9.fc33.aarch64 is already installed.
Package libatomic-10.2.1-9.fc33.aarch64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 0:18:36 ago on Mon Mar 22 16:06:54 2021.
Package maven-1:3.6.3-5.fc33.noarch is already installed.
Package java-1.8.0-openjdk-devel-1:1.8.0.282.b08-0.fc33.aarch64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 0:18:46 ago on Mon Mar 22 16:06:54 2021.
Package ant-1.10.9-1.fc33.noarch is already installed.
Package java-1.8.0-openjdk-devel-1:1.8.0.282.b08-0.fc33.aarch64 is already installed.
Package python-unversioned-command-3.9.2-1.fc33.noarch is already installed.
Package ant-junit-1.10.9-1.fc33.noarch is already installed.
Package fakeroot-1.25.2-1.fc33.aarch64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 0:18:57 ago on Mon Mar 22 16:06:54 2021.
Package clang-11.0.0-2.fc33.aarch64 is already installed.
Package lua-devel-5.4.2-1.fc33.aarch64 is already installed.
Package yaml-cpp-devel-0.6.3-3.fc33.aarch64 is already installed.
Package thrift-devel-0.13.0-6.fc33.aarch64 is already installed.
Package antlr3-tool-1:3.5.2-30.fc33.noarch is already installed.
Package antlr3-C++-devel-1:3.5.2-30.fc33.aarch64 is already installed.
Package jsoncpp-devel-1.9.4-2.fc33.aarch64 is already installed.
Package rapidjson-devel-1.1.0-15.fc33.aarch64 is already installed.
Package snappy-devel-1.1.8-4.fc33.aarch64 is already installed.
Package systemd-devel-246.10-1.fc33.aarch64 is already installed.
Package git-2.29.2-3.fc33.aarch64 is already installed.
Package python-unversioned-command-3.9.2-1.fc33.noarch is already installed.
Package sudo-1.9.5p2-1.fc33.aarch64 is already installed.
Package java-1.8.0-openjdk-headless-1:1.8.0.282.b08-0.fc33.aarch64 is already installed.
Package java-1.8.0-openjdk-devel-1:1.8.0.282.b08-0.fc33.aarch64 is already installed.
Package ant-1.10.9-1.fc33.noarch is already installed.
Package ant-junit-1.10.9-1.fc33.noarch is already installed.
Package maven-1:3.6.3-5.fc33.noarch is already installed.
Package patchelf-0.12-1.fc33.aarch64 is already installed.
Package python3-3.9.2-1.fc33.aarch64 is already installed.
Package python3-pip-20.2.2-1.fc33.noarch is already installed.
Package python3-file-magic-5.39-3.fc33.noarch is already installed.
Package python3-colorama-0.4.3-3.fc33.noarch is already installed.
Package python3-boto3-1.16.63-1.fc33.noarch is already installed.
Package python3-pytest-6.0.2-1.fc33.noarch is already installed.
Package python3-redis-3.5.3-1.fc33.noarch is already installed.
Package dnf-utils-4.0.18-1.fc33.noarch is already installed.
Package pigz-2.4-7.fc33.aarch64 is already installed.
Package net-tools-2.0-0.58.20160912git.fc33.aarch64 is already installed.
Package tar-2:1.32-6.fc33.aarch64 is already installed.
Package gzip-1.10-3.fc33.aarch64 is already installed.
Package gawk-5.1.0-2.fc33.aarch64 is already installed.
Package util-linux-2.36.1-1.fc33.aarch64 is already installed.
Package ethtool-2:5.10-1.fc33.aarch64 is already installed.
Package hwloc-2.2.0-1.fc33.aarch64 is already installed.
Package glibc-langpack-en-2.32-4.fc33.aarch64 is already installed.
Package lld-11.0.0-1.fc33.aarch64 is already installed.
Package xxhash-devel-0.8.0-1.fc33.aarch64 is already installed.
Package makeself-2.4.2-2.fc33.noarch is already installed.
Package libzstd-static-1.4.9-1.fc33.aarch64 is already installed.
Package libzstd-devel-1.4.9-1.fc33.aarch64 is already installed.
Package rpm-build-4.16.1.2-1.fc33.aarch64 is already installed.
Package devscripts-2.20.4-2.fc33.aarch64 is already installed.
Package debhelper-12.7.3-6.fc33.noarch is already installed.
Package fakeroot-1.25.2-1.fc33.aarch64 is already installed.
Package file-5.39-3.fc33.aarch64 is already installed.
Package dpkg-dev-1.19.7-7.fc33.noarch is already installed.
Package curl-7.71.1-8.fc33.aarch64 is already installed.
Package python3-pyyaml-5.4.1-1.fc33.aarch64 is already installed.
Package python3-urwid-2.1.2-1.fc33.aarch64 is already installed.
Package python3-pyparsing-2.4.7-4.fc33.noarch is already installed.
Package python3-requests-2.24.0-3.fc33.noarch is already installed.
Package python3-pyudev-0.22.0-3.fc33.noarch is already installed.
Package python3-setuptools-49.1.3-1.fc33.noarch is already installed.
Package python3-psutil-5.7.2-2.fc33.aarch64 is already installed.
Package python3-distro-1.5.0-4.fc33.noarch is already installed.
Dependencies resolved.
Nothing to do.
Complete!
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip3 install --user` instead.
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffa35beb50>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/cassandra-driver/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffa35be8e0>: Failed to establish a new connection: [Errno -2] Name or service not known')': /simple/cassandra-driver/
^CERROR: Operation cancelled by user
(base) [jw@cn05 scylladb]$

**Comment by LutzWeischerFujitsu** [comment]
Thanks. Yes, it turned out to be related to that, in the way your software works. I get now: 

(base) [jw@cn06 scylladb]$ ninja-build build
...
[54/84] Building CXX object CMakeFiles/seastar.dir/src/net/config.cc.o
FAILED: CMakeFiles/seastar.dir/src/net/config.cc.o
/usr/bin/clang++ -DFMT_LOCALE -DFMT_SHARED -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEBUG -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_HAS_MEMBARRIER -DSEASTAR_HAVE_ASAN_FIBER_SUPPORT -DSEASTAR_HAVE_HWLOC -DSEASTAR_HAVE_LZ4_COMPRESS_DEFAULT -DSEASTAR_HAVE_NUMA -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_THREAD_STACK_GUARDS -DSEASTAR_TYPE_ERASE_MORE -I/data/jw/scylladb/seastar/include -Igen/include -I/data/jw/scylladb/seastar/src -Igen/src -g -std=gnu++20 -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Werror=unused-result "-Wno-error=#warnings" -fstack-clash-protection -fvisibility=hidden -UNDEBUG -Wall -Werror -Wno-array-bounds -Wno-error=deprecated-declarations -gz -ffile-prefix-map=/data/jw/scylladb=. -march=armv8-a+crc+crypto -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -std=gnu++20 -MD -MT CMakeFiles/seastar.dir/src/net/config.cc.o -MF CMakeFiles/seastar.dir/src/net/config.cc.o.d -o CMakeFiles/seastar.dir/src/net/config.cc.o -c /data/jw/scylladb/seastar/src/net/config.cc
clang-11: error: argument unused during compilation: '-fstack-clash-protection' [-Werror,-Wunused-command-line-argument]
ninja: build stopped: subcommand failed.
[120/3400] CXX build/debug/gen/Cassandra.o
ninja: build stopped: subcommand failed.
(base) [jw@cn06 scylladb]$ 

Using --verbose I get: 

...
[70/3281] clang++ -MD -MT build/debug/gen/cql3/CqlParser.o -MF build/debug/gen/cql3/CqlParser.o.d -I/data/jw/scylladb/seastar/include -I/data/jw/scylladb/build/debug/seastar/gen/include -std=gnu++20 -U_FORTIFY_SOURCE -DSEASTAR_SSTRING -Werror=unused-result -fstack-clash-protection -fsanitize=address -fsanitize=undefined -fno-sanitize=vptr -DSEASTAR_API_LEVEL=6 -DSEASTAR_DEBUG -DSEASTAR_DEFAULT_ALLOCATOR -DSEASTAR_SHUFFLE_TASK_QUEUE -DSEASTAR_DEBUG_SHARED_PTR -DSEASTAR_TYPE_ERASE_MORE -DFMT_LOCALE -DFMT_SHARED -I/usr/include/p11-kit-1  -DDEBUG -DSANITIZE -DDEBUG_LSA_SANITIZER -DSCYLLA_ENABLE_ERROR_INJECTION -Og -g -gz -iquote. -iquote build/debug/gen --std=gnu++20  -ffile-prefix-map=/data/jw/scylladb=.  -march=armv8-a+crc+crypto -DBOOST_TEST_DYN_LINK  -I abseil -fvisibility=hidden -Wall -Werror -Wno-mismatched-tags -Wno-tautological-compare -Wno-parentheses-equality -Wno-c++11-narrowing -Wno-c++1z-extensions -Wno-sometimes-uninitialized -Wno-return-stack-address -Wno-missing-braces -Wno-unused-lambda-capture -Wno-misleading-indentation -Wno-overflow -Wno-noexcept-type -Wno-error=cpp -Wno-ignored-attributes -Wno-overloaded-virtual -Wno-unused-command-line-argument -Wno-inconsistent-missing-override -Wno-defaulted-function-deleted -Wno-redeclared-class-member -Wno-pessimizing-move -Wno-redundant-move -Wno-gnu-designator -Wno-instantiation-after-specialization -Wno-unused-private-field -Wno-unsupported-friend -Wno-unused-variable -Wno-return-std-move -Wno-delete-non-abstract-non-virtual-dtor -Wno-unknown-attributes -Wno-braced-scalar-init -Wno-range-loop-construct -Wno-unused-function -Wno-implicit-int-float-conversion -Wno-delete-abstract-non-virtual-dtor -Wno-uninitialized-const-reference -Wno-psabi -Wno-error=deprecated-declarations -DXXH_PRIVATE_API -DSEASTAR_TESTING_MAIN -DHAVE_LZ4_COMPRESS_DEFAULT -O1 -fno-sanitize-address-use-after-scope -c -o build/debug/gen/cql3/CqlParser.o build/debug/gen/cql3/CqlParser.cpp
ninja: build stopped: subcommand failed.

**Comment by avikivity** [comment]
build problem fixed by eeaceb4bff95916a5099f58ada8b04a03990740e.

**Comment by avikivity** [comment]
(you may need to wipe the build directory as cmake might cache the result of the check).

**Comment by LutzWeischerFujitsu** [comment]
'ninja-build build' now finally finishes. Is there a step left to actually install 'scylla'? 'test.py' only reports 'FAIL's.

**Comment by avikivity** [comment]
You can run from the build directory: `./build/release/scylla --developer-mode 1 -m 1G --smp 2`.

You can create packages with `ninja-release` and then install them.

**Comment by LutzWeischerFujitsu** [comment]
:-)
