### ISSUE TITLE
AMI ami-ac4f69c6 (Scylla 0.16): Scylla service fails to restart upon scylla processes killed and user data removed

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#835]
While running cluster tests, I've noticed that when you:

1) Create a scylla DB cluster
2) Start a cassandra-stress load on the cluster
3) Pick one of the nodes, delete user data and kill all scylla services

Scylla fails to restart. I've investigated the issue and found out that the scylla service is restarting the first boot init scripts all over again:

	Jan 21 03:03:48 ip-172-30-0-120.ec2.internal systemd[1]: Starting Scylla Server...
	Jan 21 03:03:48 ip-172-30-0-120.ec2.internal sudo[744]:   scylla : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/lib/scylla/scylla_prepare
	Jan 21 03:03:49 ip-172-30-0-120.ec2.internal sudo[744]: RAID does not constructed, going to initialize...
	Jan 21 03:03:53 ip-172-30-0-184 sudo[744]: Loaded plugins: fastestmirror, langpacks
	Jan 21 03:03:55 ip-172-30-0-184 sudo[744]: Loading mirror speeds from cached hostfile
	Jan 21 03:03:55 ip-172-30-0-184 sudo[744]: * base: mirror.cc.columbia.edu
	Jan 21 03:03:55 ip-172-30-0-184 sudo[744]: * elrepo: reflector.westga.edu
	Jan 21 03:03:55 ip-172-30-0-184 sudo[744]: * epel: s3-mirror-us-east-1.fedoraproject.org
	Jan 21 03:03:55 ip-172-30-0-184 sudo[744]: * extras: mirror.atlanticmetro.net
	Jan 21 03:03:55 ip-172-30-0-184 sudo[744]: * updates: mirror.solarvps.com
	Jan 21 03:04:06 ip-172-30-0-184 sudo[744]: No packages marked for update
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: Waiting for cloud-init to finish...
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] Started with user data set to:
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] --clustername scylla-db-cluster-051f7179 --totalnodes 6
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] Using user data:
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] --clustername scylla-db-cluster-051f7179 --totalnodes 6
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] Using instance type: m3.large
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] meta-data:instance-type: m3.large
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] meta-data:local-ipv4: 172.30.0.184
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] meta-data:public-hostname: <same as local-ipv4>
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] meta-data:ami-launch-index: 2
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] meta-data:reservation-id: r-ad51cb05
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] Using cluster name: scylla-db-cluster-051f7179
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] Using cluster size: 6
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] Using seed indexes: [0, 6, 6]
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] Reflector loop...
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] 01/21/16-03:04:16 Reflector: Received 1 of 1 responses from: [u'172.30.0.183']
	Jan 21 03:04:16 ip-172-30-0-184 sudo[744]: [INFO] scylla.yaml configured.
	Jan 21 03:04:21 ip-172-30-0-184 scylla_run[1999]: EAL: Detected lcore 0 as core 0 on socket 0
	Jan 21 03:04:21 ip-172-30-0-184 scylla_run[1999]: EAL: Detected lcore 1 as core 0 on socket 0
	Jan 21 03:04:21 ip-172-30-0-184 scylla_run[1999]: EAL: Support maximum 128 logical core(s) by configuration.
	Jan 21 03:04:21 ip-172-30-0-184 scylla_run[1999]: EAL: Detected 2 lcore(s)
	Jan 21 03:04:21 ip-172-30-0-184 scylla_run[1999]: EAL: VFIO modules not all loaded, skip VFIO support...
	Jan 21 03:04:21 ip-172-30-0-184 scylla_run[1999]: EAL: Setting up physically contiguous memory...
	Jan 21 03:04:22 ip-172-30-0-184 scylla_run[1999]: EAL: TSC frequency is ~2500109 KHz
	Jan 21 03:04:22 ip-172-30-0-184 scylla[1999]: EAL: TSC frequency is ~2500109 KHz
	Jan 21 03:04:22 ip-172-30-0-184 scylla[1999]: EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
	Jan 21 03:04:22 ip-172-30-0-184 scylla_run[1999]: EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
	Jan 21 03:04:22 ip-172-30-0-184 scylla_run[1999]: EAL: Master lcore 0 is ready (tid=3f72e580;cpuset=[0])
	Jan 21 03:04:22 ip-172-30-0-184 scylla[1999]: EAL: Master lcore 0 is ready (tid=3f72e580;cpuset=[0])
	Jan 21 03:04:22 ip-172-30-0-184 scylla_run[1999]: EAL: lcore 1 is ready (tid=32b05700;cpuset=[1])
	Jan 21 03:04:22 ip-172-30-0-184 scylla[1999]: EAL: lcore 1 is ready (tid=32b05700;cpuset=[1])
	Jan 21 03:04:22 ip-172-30-0-184 scylla_run[1999]: Scylla version 0.16-20160120.e10588e starting ...
	Jan 21 03:04:22 ip-172-30-0-184 scylla[1999]:  [shard 0] config - Option partitioner is not (yet) used.
	Jan 21 03:04:22 ip-172-30-0-184 scylla[1999]:  [shard 0] database - Row: max_vector_size: 32, internal_count: 5
	Jan 21 03:04:22 ip-172-30-0-184 scylla[1999]:  [shard 1] database - Row: max_vector_size: 32, internal_count: 5
	Jan 21 03:04:22 ip-172-30-0-184 scylla[1999]:  [shard 0] database - Populating Keyspace system
	Jan 21 03:04:23 ip-172-30-0-184 scylla[1999]:  [shard 1] database - Populating Keyspace system
	Jan 21 03:04:23 ip-172-30-0-184 scylla[1999]:  [shard 0] storage_service - Loading persisted ring state
	Jan 21 03:04:23 ip-172-30-0-184 scylla[1999]:  [shard 0] storage_service - Starting up server gossip
	Jan 21 03:04:23 ip-172-30-0-184 scylla[1999]:  [shard 0] storage_service - Generated random tokens. tokens are {5008275290944452782, -185045118960031477, 443495043986811523, 
	Jan 21 03:04:23 ip-172-30-0-184 scylla[1999]:  [shard 0] storage_service - Node 172.30.0.184 state jump to normal
	Jan 21 03:04:24 ip-172-30-0-184 scylla[1999]:  [shard 0] storage_service - NORMAL: node is now in normal status
	Jan 21 03:04:24 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - Waiting for gossip to settle before accepting client requests...
	Jan 21 03:04:24 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - Node 172.30.0.183 is now part of the cluster
	Jan 21 03:04:24 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - InetAddress 172.30.0.183 is now UP
	Jan 21 03:04:24 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - Node 172.30.0.185 is now part of the cluster
	Jan 21 03:04:24 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - InetAddress 172.30.0.185 is now UP
	Jan 21 03:04:25 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 172.30.0.183
	Jan 21 03:04:26 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 172.30.0.185
	Jan 21 03:04:28 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - Node 172.30.0.190 is now part of the cluster
	Jan 21 03:04:28 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - InetAddress 172.30.0.190 is now UP
	Jan 21 03:04:28 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 172.30.0.190
	Jan 21 03:04:28 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - Node 172.30.0.188 is now part of the cluster
	Jan 21 03:04:28 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - InetAddress 172.30.0.188 is now UP
	Jan 21 03:04:29 ip-172-30-0-184 scylla[1999]:  [shard 1] compaction - Compacting [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-3-Data.db
	Jan 21 03:04:29 ip-172-30-0-184 scylla[1999]:  [shard 1] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers
	Jan 21 03:04:29 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 172.30.0.188
	Jan 21 03:04:32 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - No gossip backlog; proceeding
	Jan 21 03:04:32 ip-172-30-0-184 scylla_run[1999]: Starting listening for CQL clients on 0.0.0.0:9042...
	Jan 21 03:04:32 ip-172-30-0-184 scylla_run[1999]: Scylla API server listening on 127.0.0.1:10000 ...
	Jan 21 03:04:32 ip-172-30-0-184 systemd[1]: Started Scylla Server.
	Jan 21 03:04:54 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - Node 172.30.0.189 is now part of the cluster
	Jan 21 03:04:54 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - InetAddress 172.30.0.189 is now UP
	Jan 21 03:04:54 ip-172-30-0-184 scylla[1999]:  [shard 0] compaction - Compacting [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers-ka-2-Data.db
	Jan 21 03:04:54 ip-172-30-0-184 scylla[1999]:  [shard 0] compaction - Compacted 4 sstables to [/var/lib/scylla/data/system/peers-37f71aca7dc2383ba70672528af04d4f/system-peers
	Jan 21 03:04:55 ip-172-30-0-184 scylla[1999]:  [shard 0] gossip - do_gossip_to_live_member: Favor newly added node 172.30.0.189
	Jan 21 03:07:51 ip-172-30-0-184 scylla[1999]:  [shard 0] migration_manager - Create new ColumnFamily: org.apache.cassandra.config.CFMetaData@0x600000073880[cfId=286eb840-bfec
	Jan 21 03:12:50 ip-172-30-0-184 systemd[1]: scylla-server.service: main process exited, code=killed, status=9/KILL
	Jan 21 03:12:50 ip-172-30-0-184 sudo[2215]:   scylla : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/lib/scylla/scylla_stop
	Jan 21 03:12:50 ip-172-30-0-184 systemd[1]: Unit scylla-server.service entered failed state.
	Jan 21 03:12:50 ip-172-30-0-184 systemd[1]: scylla-server.service failed.

So the process exited because we killed it. Nice, let's see what happens next...

	Jan 21 03:12:51 ip-172-30-0-184 systemd[1]: Starting Scylla Server...
	Jan 21 03:12:51 ip-172-30-0-184 sudo[2221]:   scylla : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/lib/scylla/scylla_prepare
	Jan 21 03:12:51 ip-172-30-0-184 sudo[2221]: RAID does not constructed, going to initialize...
	Jan 21 03:12:51 ip-172-30-0-184 sudo[2221]: Loaded plugins: fastestmirror, langpacks
	Jan 21 03:12:51 ip-172-30-0-184 sudo[2221]: Loading mirror speeds from cached hostfile
	Jan 21 03:12:51 ip-172-30-0-184 sudo[2221]: * base: mirror.cc.columbia.edu
	Jan 21 03:12:51 ip-172-30-0-184 sudo[2221]: * elrepo: reflector.westga.edu
	Jan 21 03:12:51 ip-172-30-0-184 sudo[2221]: * epel: s3-mirror-us-east-1.fedoraproject.org
	Jan 21 03:12:51 ip-172-30-0-184 sudo[2221]: * extras: mirror.atlanticmetro.net
	Jan 21 03:12:51 ip-172-30-0-184 sudo[2221]: * updates: mirror.solarvps.com
	Jan 21 03:12:51 ip-172-30-0-184 sudo[2221]: No packages marked for update
	Jan 21 03:13:02 ip-172-30-0-184 sudo[2221]: Waiting for cloud-init to finish...
	Jan 21 03:13:02 ip-172-30-0-184 sudo[2221]: [INFO] Started with user data set to:
	Jan 21 03:13:02 ip-172-30-0-184 sudo[2221]: [INFO] --clustername scylla-db-cluster-051f7179 --totalnodes 6
	Jan 21 03:13:02 ip-172-30-0-184 sudo[2221]: [INFO] Using user data:
	Jan 21 03:13:02 ip-172-30-0-184 sudo[2221]: [INFO] --clustername scylla-db-cluster-051f7179 --totalnodes 6
	Jan 21 03:13:02 ip-172-30-0-184 sudo[2221]: [INFO] Using instance type: m3.large
	Jan 21 03:13:02 ip-172-30-0-184 sudo[2221]: [INFO] meta-data:instance-type: m3.large
	Jan 21 03:13:02 ip-172-30-0-184 sudo[2221]: [INFO] meta-data:local-ipv4: 172.30.0.184
	Jan 21 03:13:02 ip-172-30-0-184 sudo[2221]: [INFO] meta-data:public-hostname: <same as local-ipv4>
	Jan 21 03:13:02 ip-172-30-0-184 sudo[2221]: [INFO] meta-data:ami-launch-index: 2
	Jan 21 03:13:02 ip-172-30-0-184 sudo[2221]: [INFO] meta-data:reservation-id: r-ad51cb05
	Jan 21 03:13:02 ip-172-30-0-184 sudo[2221]: [INFO] Using cluster name: scylla-db-cluster-051f7179
	Jan 21 03:13:02 ip-172-30-0-184 sudo[2221]: [INFO] Using cluster size: 6
	Jan 21 03:13:02 ip-172-30-0-184 scylla_run[2446]: EAL: Detected lcore 0 as core 0 on socket 0
	Jan 21 03:13:02 ip-172-30-0-184 scylla_run[2446]: EAL: Detected lcore 1 as core 0 on socket 0
	Jan 21 03:13:02 ip-172-30-0-184 scylla_run[2446]: EAL: Support maximum 128 logical core(s) by configuration.
	Jan 21 03:13:02 ip-172-30-0-184 scylla_run[2446]: EAL: Detected 2 lcore(s)
	Jan 21 03:13:02 ip-172-30-0-184 scylla_run[2446]: EAL: VFIO modules not all loaded, skip VFIO support...
	Jan 21 03:13:02 ip-172-30-0-184 scylla_run[2446]: EAL: Setting up physically contiguous memory...
	Jan 21 03:13:02 ip-172-30-0-184 scylla_run[2446]: EAL: TSC frequency is ~2499890 KHz
	Jan 21 03:13:02 ip-172-30-0-184 scylla[2446]: EAL: TSC frequency is ~2499890 KHz
	Jan 21 03:13:02 ip-172-30-0-184 scylla[2446]: EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
	Jan 21 03:13:02 ip-172-30-0-184 scylla_run[2446]: EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
	Jan 21 03:13:02 ip-172-30-0-184 scylla[2446]: EAL: Master lcore 0 is ready (tid=76fc2580;cpuset=[0])
	Jan 21 03:13:02 ip-172-30-0-184 scylla_run[2446]: EAL: Master lcore 0 is ready (tid=76fc2580;cpuset=[0])
	Jan 21 03:13:02 ip-172-30-0-184 scylla_run[2446]: EAL: lcore 1 is ready (tid=6a399700;cpuset=[1])
	Jan 21 03:13:02 ip-172-30-0-184 scylla[2446]: EAL: lcore 1 is ready (tid=6a399700;cpuset=[1])
	Jan 21 03:13:02 ip-172-30-0-184 scylla_run[2446]: Scylla version 0.16-20160120.e10588e starting ...
	Jan 21 03:13:02 ip-172-30-0-184 scylla[2446]:  [shard 0] config - Option partitioner is not (yet) used.
	Jan 21 03:13:02 ip-172-30-0-184 scylla[2446]:  [shard 0] database - Row: max_vector_size: 32, internal_count: 5
	Jan 21 03:13:02 ip-172-30-0-184 scylla[2446]:  [shard 1] database - Row: max_vector_size: 32, internal_count: 5
	Jan 21 03:13:03 ip-172-30-0-184 scylla[2446]:  [shard 0] database - Populating Keyspace system
	Jan 21 03:13:03 ip-172-30-0-184 scylla[2446]:  [shard 0] database - Keyspace /var/lib/scylla/data/system: Reading CF size_estimates
	Jan 21 03:13:03 ip-172-30-0-184 scylla[2446]:  [shard 0] database - Keyspace /var/lib/scylla/data/system: Reading CF compaction_history
	Jan 21 03:13:03 ip-172-30-0-184 scylla[2446]:  [shard 0] database - Keyspace /var/lib/scylla/data/system: Reading CF compactions_in_progress
	Jan 21 03:13:03 ip-172-30-0-184 scylla[2446]:  [shard 0] database - Keyspace /var/lib/scylla/data/system: Reading CF range_xfers
	Jan 21 03:13:03 ip-172-30-0-184 scylla[2446]:  [shard 0] database - Keyspace /var/lib/scylla/data/system: Reading CF sstable_activity
	Jan 21 03:13:03 ip-172-30-0-184 scylla[2446]:  [shard 0] database - Keyspace /var/lib/scylla/data/system: Reading CF peers
	Jan 21 03:13:03 ip-172-30-0-184 scylla_run[2446]: WARNING: exceptional future ignored of type 'std::system_error': Error system:17 (File exists)
	Jan 21 03:13:03 ip-172-30-0-184 scylla_run[2446]: WARNING: exceptional future ignored of type 'std::system_error': Error system:17 (File exists)
	Jan 21 03:13:03 ip-172-30-0-184 scylla_run[2446]: WARNING: exceptional future ignored of type 'std::system_error': Error system:17 (File exists)
	Jan 21 03:13:03 ip-172-30-0-184 scylla[2446]:  [shard 0] database - failed to write sstable: std::system_error (error system:17, File exists)
	Jan 21 03:13:03 ip-172-30-0-184 scylla[2446]:  [shard 0] database - failed to write sstable: std::system_error (error system:17, File exists)
	Jan 21 03:13:03 ip-172-30-0-184 scylla[2446]:  [shard 0] database - failed to write sstable: std::system_error (error system:17, File exists)
	Jan 21 03:14:33 ip-172-30-0-184 systemd[1]: scylla-server.service stop-sigterm timed out. Killing.
	Jan 21 03:14:33 ip-172-30-0-184 systemd[1]: scylla-server.service: main process exited, code=killed, status=11/SEGV
	Jan 21 03:14:33 ip-172-30-0-184 sudo[2501]:   scylla : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/lib/scylla/scylla_stop
	Jan 21 03:14:33 ip-172-30-0-184 systemd[1]: Unit scylla-server.service entered failed state.
	Jan 21 03:14:33 ip-172-30-0-184 systemd[1]: scylla-server.service failed.

So now systemd has to kill scylla service. It tries to restart it again...

	Jan 21 03:14:33 ip-172-30-0-184 systemd[1]: Starting Scylla Server...
	Jan 21 03:14:33 ip-172-30-0-184 sudo[2507]:   scylla : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/lib/scylla/scylla_prepare
	Jan 21 03:14:33 ip-172-30-0-184 sudo[2507]: RAID does not constructed, going to initialize...
	Jan 21 03:14:33 ip-172-30-0-184 sudo[2507]: Loaded plugins: fastestmirror, langpacks
	Jan 21 03:14:33 ip-172-30-0-184 sudo[2507]: Loading mirror speeds from cached hostfile
	Jan 21 03:14:33 ip-172-30-0-184 sudo[2507]: * base: mirror.cc.columbia.edu
	Jan 21 03:14:33 ip-172-30-0-184 sudo[2507]: * elrepo: reflector.westga.edu
	Jan 21 03:14:33 ip-172-30-0-184 sudo[2507]: * epel: s3-mirror-us-east-1.fedoraproject.org
	Jan 21 03:14:33 ip-172-30-0-184 sudo[2507]: * extras: mirror.atlanticmetro.net
	Jan 21 03:14:33 ip-172-30-0-184 sudo[2507]: * updates: mirror.solarvps.com
	Jan 21 03:14:34 ip-172-30-0-184 sudo[2507]: No packages marked for update
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: Waiting for cloud-init to finish...
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: [INFO] Started with user data set to:
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: [INFO] --clustername scylla-db-cluster-051f7179 --totalnodes 6
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: [INFO] Using user data:
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: [INFO] --clustername scylla-db-cluster-051f7179 --totalnodes 6
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: [INFO] Using instance type: m3.large
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: [INFO] meta-data:instance-type: m3.large
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: [INFO] meta-data:local-ipv4: 172.30.0.184
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: [INFO] meta-data:public-hostname: <same as local-ipv4>
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: [INFO] meta-data:ami-launch-index: 2
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: [INFO] meta-data:reservation-id: r-ad51cb05
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: [INFO] Using cluster name: scylla-db-cluster-051f7179
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: [INFO] Using cluster size: 6
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: [INFO] Using seed indexes: [0, 6, 6]
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: [INFO] Reflector loop...
	Jan 21 03:17:14 ip-172-30-0-184 sudo[2507]: [INFO] 01/21/16-03:14:45 Reflector: Received 0 of 1 responses from: []
	...

So, systemctl restart scylla-daemon.service will time out, and the scylla service will never get back online, because it's executing the entire talk to reflector sequence again. I still need to take a look at the init scripts, but I'm assuming this is not the way the scylla service is supposed to work.

**Comment by lmr** [comment]
This problem in the init scripts also seems to be the root cause for #834 as well.

**Comment by lmr** [comment]
Instance type is `m3.large`.

**Comment by syuu1228** [comment]
Could you explain full operation(commands, userdata..) of whole cluster setup to reproduce this

**Comment by lmr** [comment]
1) Create a cluster of 6 nodes with user data

    --clustername scylla-abadc --totalnodes 6

2) Create a loader node, install cassandra-stress in it
3) Run cassandra-stress using the cluster:

    cassandra-stress write cl=QUORUM duration={}m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=4 -node ip1,ip2,ip3,ip4,ip5,ip6

4) Pick one of these nodes at random, then kill all scylla processes in it `pkill -9 scylla`
5) Try to restart the scylla processes `systemctl restart scylla-server.service`

**Comment by lmr** [comment]
After a conversation with Shlomi, I realized the description is not good enough, I had to mention that user data was removed and scylla processes were killed. Also, the description above misses, between 3) and 4):

* Run the following script:

    #!/bin/bash

    DELETE_COUNT=5

    ls /var/lib/scylla|sort -R |tail -$DELETE_COUNT |while read file; do
        rm -rf $file
    done

I'm sorry I did not add this (very important) information before.

**Comment by slivne** [comment]
Ok I think I found it - there is a mixup of running ds2_configure and raid setup

Current scylla_prepare code is this:

```
if [ "$AMI" = "yes" ]; then
    RAIDCNT=`grep xvdb /proc/mdstat | wc -l`
    RAIDDEV=`grep xvdb /proc/mdstat | awk '{print $1}'`

    if [ $RAIDCNT -ge 1 ]; then
        echo "RAID already constructed."
        if [ "`mount|grep /var/lib/scylla`" = "" ]; then
            mount -o noatime /dev/$RAIDDEV /var/lib/scylla
        fi
    else
        echo "RAID does not constructed, going to initialize..."

        if [ "$AMI_KEEP_VERSION" != "yes" ]; then
            yum update -y
        fi

        DISKS=""
        for i in /dev/xvd{b..z}; do
            if [ -b $i ];then
                echo "Found disk $i"
                if [ "$DISKS" = "" ]; then
                    DISKS=$i
                else
                    DISKS="$DISKS,$i"
                fi
            fi
        done

        if [ "$DISKS" != "" ]; then
            /usr/lib/scylla/scylla_raid_setup -d $DISKS
        fi

        /usr/lib/scylla/scylla-ami/ds2_configure.py
    fi
fi
```

So it ties identifying if ds2_configure should be executed with raid being up or down and this is not correct.

In @lmr case I think he ran a c3.large without any attached drives and this caused on every boot to run ds2_configure as his logs show
```
Jan 21 03:12:51 ip-172-30-0-184 sudo[2221]: RAID does not constructed, going to initialize...
```

scylla_prepare is tightly coupled with scylla_stop

So I think the following should be done - scylla_prepare should remain as is not extracted to another service.

if we want we can have ds2_configure.py - seperated - yet I think we can construct an if to set when it should be run.

ds2_configure should be run only once on an instance - no matter what
- stopped and started
- machine was rebooted (init 6)
- machine was stopped and then started back up (this is a real issue as the node ip changes  - maybe we should disallow this - like datastax).

raid setup should be run if there are attached disks and they are not formatted and mounted,
- first boot
- machine that was stooped and then started (if it has ephemeral drives)

networking setup should be done on need basis
- if its virtio - every time (as we delete the setup on scylla_stop)
- if its dpdk - (is once enough on every machine boot ?)
- it its posix - safer we do it on every run - to make sure nothing was changed.

@syuu1228 this is also related to some patches that you sent on the list.

@avikivity any other input ?

**Comment by avikivity** [comment]
Only what I mentioned before -- those services should be disaggregated at the systemd level.  This way there is visibility if something fails.

We could even separate network setup from storage setup, so a '`systemctl status` shows you immediately if one or the other failed.

**Comment by slivne** [comment]
related to #834
