### ISSUE TITLE
Commitlog can get stuck after reaching disk size limit, causing writes to time out

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla#8363]
## Problem

Scylla commit used to reproduce: c1daf2bb24a43d398a5f209e052102afea6eb7de

Recently, the commitlog disk limit became a hard limit (4082f57edc3e7764e11e9e858a0a8059981c6309). After that change, a race became possible which would prevent the commitlog from accepting any further writes. The shard on which the commitlog gets stuck becomes unresponsive to writes.

## Description of the race

The race is as follows:

1. The commitlog goes over disk space limit (`totals.totals.total_size_on_disk > max_disk_size`). Both "recycled" and "reserve" pools are empty.
1. Reserve replenisher (an asynchronous process in the commitlog) wakes up because the reserve segments pool is empty. It calls `allocate_segment`, and decides to wait until there are some `_recycled_segments`:

    https://github.com/scylladb/scylla/blob/ef06a939c4f51e6f01f0de44f5572f3aeab089c5/db/commitlog/commitlog.cc#L1511-L1517

1. A different commitlog background process (`on_timer`) is run, it sees that disk usage is over limit and decides to "flush" some segments so that the disk usage goes below half of the disk limit (`disk_usage_threshold`):

	https://github.com/scylladb/scylla/blob/ef06a939c4f51e6f01f0de44f5572f3aeab089c5/db/commitlog/commitlog.cc#L1832-L1841

	This causes some memtables to be saved as sstables (`flush_segments`), in turn this causes those commitlog segments whose all mutations are backed by sstables to be moved from `_segments` to `_segments_to_delete`. Those segments are then handled by `delete_segments` (called indirectly by `do_pending_deletes`), and each of them can either be deleted from disk, or moved to `_recycled_segments`:

	https://github.com/scylladb/scylla/blob/ef06a939c4f51e6f01f0de44f5572f3aeab089c5/db/commitlog/commitlog.cc#L1747-L1778

	Now here is a problem: even if there are multiple segments to delete and we don't need to delete all of them to go below disk size limit, it might still happen that __all__ segments are deleted by that function. It's because segments are handled in parallel. For each segment, we:

	1. Decide if we should delete the file, or rename and move to reserve - the decision is based on the `totals.total_size_on_disk` metric,
	2. Proceed with deletion or rename/movement,
	3. Update the `totals.total_size_on_disk` metric.
	
	Because there is a defer point during 2), it might happen that we do the step 1) for all segments in the list before we do step 3) for any of the segments. Because of that, it is probable that commitlog will decide to delete all segments from the list. As a result, `_recycled_segments` is still empty.

	The fact that segments are deleted can clearly be seen in metrics:

	![8301-commitlog-used-bytes-on-disk](https://user-images.githubusercontent.com/4950936/112658865-1d9a9880-8e54-11eb-922b-e5b5bc87fc43.png)

1. Now, commitlog becomes stuck:

	- New writes will get stuck because they will be waiting for segments to appear in the reserve,
	- Reserve replenisher is stuck because it waits for recycled segments to appear,
	- No more segments will be freed - the last `do_pending_deletes` reduced disk usage below `disk_usage_threshold`, so no more flushes will be issued and no segments will be recycled.

	This will cause all attempts to write anything to the commitlog to time out.

	Curiously, `nodetool flush` can cause the node to become unstuck. If there are some unflushed memtables, then there are also some commitlog segments which will be moved to the recycled pool after memtables are flushed.

## How to reproduce

1. Start a single-node cluster with a single shard and a small commitlog disk limit (I used 257MB - for some reason it's important that the limit isn't a multiple of segment size),
1. Start writing with cassandra-stress or scylla-bench,
1. Wait some time until the commitlog fills up, commitlog triggers memtable flush and the race described here reproduces,
1. Observe that suddenly all writes from c-s or s-b start to time out.

----

/cc: @elcallio

**Comment by piodul** [comment]
This bug also prevents from establishing new connections to the shard which is stuck (e.g. `cqlsh` times out), although I don't know why.

**Comment by piodul** [comment]
...and this bug also prevents Scylla from shutting down itself :( it gets stuck:

```
INFO  2021-03-26 17:31:56,405 [shard 0] init - Signal received; shutting down
INFO  2021-03-26 17:31:56,405 [shard 0] init - Shutting down redis service
INFO  2021-03-26 17:31:56,405 [shard 0] init - Shutting down redis service was successful
INFO  2021-03-26 17:31:56,405 [shard 0] init - Shutting down view builder
INFO  2021-03-26 17:31:56,405 [shard 0] view - Stopping view builder
INFO  2021-03-26 17:31:56,406 [shard 0] init - Shutting down view builder was successful
INFO  2021-03-26 17:31:56,406 [shard 0] init - Shutting down local storage
INFO  2021-03-26 17:31:56,406 [shard 0] storage_service - Drain on shutdown: starts
INFO  2021-03-26 17:31:56,406 [shard 0] storage_service - Stop transport: starts
INFO  2021-03-26 17:31:56,406 [shard 0] storage_service - Shutting down native transport
INFO  2021-03-26 17:31:56,955 [shard 0] cql_server_controller - CQL server stopped
INFO  2021-03-26 17:31:56,955 [shard 0] storage_service - Shutting down native transport was successful
INFO  2021-03-26 17:31:56,955 [shard 0] storage_service - Shutting down rpc server
INFO  2021-03-26 17:31:56,955 [shard 0] thrift_controller - Thrift server stopped
INFO  2021-03-26 17:31:56,955 [shard 0] storage_service - Shutting down rpc server was successful
INFO  2021-03-26 17:31:56,955 [shard 0] storage_service - Stop transport: shutdown rpc and cql server done
INFO  2021-03-26 17:31:56,955 [shard 0] gossip - My status = NORMAL
INFO  2021-03-26 17:31:56,955 [shard 0] gossip - Announcing shutdown
INFO  2021-03-26 17:31:56,956 [shard 0] storage_service - Node 127.0.0.1 state jump to normal
... nothing more happens ...
```

**Comment by kbr-** [comment]
> This bug also prevents from establishing new connections to the shard which is stuck (e.g. cqlsh times out), although I don't know why.

Probably because when a connection is established, Scylla performs a write to `system.clients` (synchronously - so the establishing doesn't finish if the write doesn't finish).

> ...and this bug also prevents Scylla from shutting down itself :(

Probably the same reason, there must be some write.
Scylla also writes to `system.clients` when connections are dropped AFAIK - perhaps it tries to remove these connections on shutdown and hence gets stuck.
