### ISSUE TITLE
Spelling mistakes on wiki: Gossip 

### ISSUE THREAD

**Issue by chaoaero** [scylladb/scylla#837]
"and call failure_detector::report(endpoint) to update failure detector's arriavl sample."

I think there is a spelling mistake for *arrival* here.

**Comment by tzach** [comment]
Thanks for letting us know!
Fixed
https://github.com/scylladb/scylla/wiki/Gossip/_compare/41f54a5ddfadbeb28d0ed4024f5762f938c863b1...234edc42c1f4d3ec678531b581a711f406320e17
