### ISSUE TITLE
Failure detector fails to mark nodes as DN when all packets are dropped

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#8377]
1. start a 2-node distributed cluster (e.g. on AWS). Let ip1 be the IP address of the first node.
2. `sudo iptables -A INPUT -s ip1 -j DROP` on the second node, `sudo iptables -A INPUT -s ip2 -j DROP` on the first.
3. `nodetool status` on second node. node1 remains in `UN` indefinitely. (and vice-versa)

Now this does not make any sense to me and has some stupid consequences. For example, on node2 I can't sometimes perform CL=ONE queries of RF=2 tables for some reason - some queries are routed to node1 and node2 does not attempt to query itself. For large enough paged queries they always hang on one of the pages which gets routed to node1. This is weird on its own (there should be some speculative retry performed by node2 on node2 when it can't contact node1) but it would not happen if node2 eventually marked node1 as down, which it doesn't do.

How useful is a failure detector that must actually receive a packet to mark a node down?

**Comment by asias** [comment]
>     1. start a 2-node distributed cluster (e.g. on AWS). Let ip1 be the IP address of the first node.
> 
>     2. `sudo iptables -A INPUT -s ip1 -j DROP` on the second node, `sudo iptables -A INPUT -s ip2 -j DROP` on the first.
> 
>     3. `nodetool status` on second node. node1 remains in `UN` indefinitely. (and vice-versa)

Does heartbeat version increase from  `nodetool gossipino`? If it is increasing, I suspect the iptables rule does not block all the traffic for some reason, e.g., public / private ip address. 

Can you try locally?

> 
> 
> Now this does not make any sense to me and has some stupid consequences. For example, on node2 I can't sometimes perform CL=ONE queries of RF=2 tables for some reason - some queries are routed to node1 and node2 does not attempt to query itself. For large enough paged queries they always hang on one of the pages which gets routed to node1. This is weird on its own (there should be some speculative retry performed by node2 on node2 when it can't contact node1) but it would not happen if node2 eventually marked node1 as down, which it doesn't do.
> 
> How useful is a failure detector that must actually receive a packet to mark a node down?

Why do you think so?

**Comment by slivne** [comment]
@kbr- ping

**Comment by asias** [comment]
I am closing this. Since now failure detector uses a direct echo message. With all the packets dropped, the echo message will not be delivered, the peer node will be marked as DOWN with no exception.
