### ISSUE TITLE
Collectd - default to point to collectd target on the local host

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#838]
```
SCYLLA_ARGS="--collectd-address=127.0.0.1:25826 --collectd=1
--collectd-hostname={{ config.hostname }} --collectd-poll-period 3000"
```

With --collectd-address=127.0.0.1  *always* as our default parameters. When we'll wish, we'll run a local collectd and have a scylla-top.py , when we'll want, we'll configure collectd to forward the data to a remote collector.

**Comment by syuu1228** [comment]
'--collectd-hostname={{ config.hostname }}' doesn't works for me.
It says
```
scylla_run[28947]: error: too many positional options have been specified on the command line
scylla_run[28947]: Try --help.
```
Without collectd-hostname option it able to startup.

**Comment by dorlaor** [comment]
You shouldn't use the curly bracts like this: '{{ config.hostname }}''
but just take the hostname from the system.

**Comment by syuu1228** [comment]
I referenced collectd code on seastar, I found that --collectd-hostname can
get node's hostname by calling gethostname() when the option not passed:
https://github.com/scylladb/seastar/blob/master/core/scollectd.cc#L470

So I think we don't need this by default.
