### ISSUE TITLE
listen-address flag description saying `Never specify 0.0.0.0; it is always wrong.` is wrong

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla#8381]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.4.0

`--listen-address` flag description says `Never specify 0.0.0.0; it is always wrong.` which isn't true as using `0.0.0.0` is valid when using explicit `--broadcast-address`.

There is also a similar comment in `/etc/scylla/scylla.yaml`
```
# Setting listen_address to 0.0.0.0 is always wrong.
listen_address: localhost
```
@avikivity said the comment predates broadcast_address.

**Comment by avikivity** [comment]
Documentation-only, and minor; not backporting.
