### ISSUE TITLE
Tracing can remain not shut down if start is aborted

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla#8382]
Recent unification of drain and drain_on_shutdown left tracing started until drain_on_shutdown is scheduled. This causes assertion failure on tracing destruction.

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please backport to 4.5

Seen on master in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/779/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/simple_add_new_node_while_adding_info_1_test/

then, the test continues to fail in 4.5 that doesn't have this fix:

https://jenkins.scylladb.com/view/scylla-4.5/job/scylla-4.5/job/dtest-release/9/testReport/update_cluster_layout_tests/TestUpdateClusterLayout/simple_add_new_node_while_adding_info_1_test/:
```
Critical errors found: [('node4', ['Aborting on shard 0.'])]
Other errors: [('node4', ['ERROR 2021-04-27 02:03:45,299 [shard 0] init - Unexpected error shutting down tracing: std::logic_error (tracing: stop() called before shutdown())'])]
```

Reproduced locally.
`simple_add_new_node_while_adding_info_1_test` fails against c9eaf9575, passes with 887a1b0d3 applied.

**Comment by bhalevy** [comment]
@scylladb/scylla-maint ping backport

**Comment by avikivity** [comment]
Backported to 4.5. Is 4.4 safe?

**Comment by bhalevy** [comment]
> Backported to 4.5. Is 4.4 safe?

@xemul what say you?

**Comment by xemul** [comment]
The 887a1b0 is only needed after 6035fd05, so 4.4 is not affected
