### ISSUE TITLE
sstableloader: partition with old deletion and new data handled incorrectly

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8390]
https://github.com/scylladb/scylla-tools-java/issues/238 is a bug in sstableloader which causes it to incorrectly handle partitions which have both a partition tombstone and data - the data is ignored. Among other things this breaks sstableloader on an Alternator table without a sort key where items were written with `PutItem` (such items have a partition tombstone at time `t-1` and data at time `t`).

Creating here an issue in the main Scylla repository for updating the scylla-tools-java submodule, and for considering backports.

**Comment by nyh** [comment]
@avikivity already updated the scylla-tools-java submodule, so closing and leaving "Backport candidate" tag to consider backporting the scylla-tools-java fix.

**Comment by avikivity** [comment]
Will be fixed by bfed9c15d573b0b69a71ed6e24df6566962849de

**Comment by nyh** [comment]
Backported the scylla-tools patch:
In next-4.3 commit 76642eb00d414bebeca79303501cd8c5907d2f62, in submodule's branch-4.3 commit 2bedecd3a76db4875d821a455c18a57e9a75dc4c.
In next-4.4 commit , in submodule's branch-4.4 commit a3e010ee4fd406946d0db2f259c6cf55dccd1056.
