### ISSUE TITLE
Infinite loop in write_fragmented for empty fragments in non-empty views

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylla#8398]
The copying and comparing utilities for FragmentedView are not prepared to
deal with empty fragments in non-empty views, and will fall into an infinite
loop in such case.
But data coming in result_row_view can contain such fragments, so we need to
fix that.

This is what caused the dtest failure in https://jenkins.scylladb.com/job/scylla-master/job/next/3362/.

**Comment by avikivity** [comment]
Backported to 4.4, 4.5 (4.6 has it).
