### ISSUE TITLE
setting compiler=clang++ fails

### ISSUE THREAD

**Issue by erichkeane** [scylladb/scylla#840]
I'm running clang++ 3.7.0 (tags/RELEASE_370/final) on fedora.  I've been able to get g++ to compile fine, but in an effort to run some clang-based tools I figured I'd try to get clang to compile Scylla first!

I submitted this patch: https://groups.google.com/forum/#!topic/scylladb-dev/V5R91lAzGw0 which is a prerequisite to get clang to attempt to compile the code, and the following warnings would need to be disabled or fixed.  Either way, I'm willing to do this and submit a patch, I'd just like some guidance as to which I should do in each case.  

I'll note that many appear in seastar, so I can contribute those separately as well (I know the same company runs both, so I figured a single bug report would be acceptable).  Note that each is just an example of the error, not an exhaustive list.

1:

```
./core/future-util.hh:103:32: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
                state.ex = std::move(std::current_exception());
```

Essentially, the std::move call prevents copy-in-place for Return Value Optimization.  I would say that since RVO is more performant that removing the move would be prudent.

2-

```
/mnt/500gbdisk/scylla/seastar/net/packet.hh:136:24: error: redundant move in return statement [-Werror,-Wredundant-move]
            return std::move(old);
```

Essentially, the compiler is sure it should do a move anyway (in this case because 'old' is a unique_ptr).  I suspect that disabling this one is preferential.

3-

```
http/reply.cc:96:12: error: unused variable 'name_value_separator' [-Werror,-Wunused-const-variable]
const char name_value_separator[] = { ':', ' ' };

core/fair_queue.hh:93:14: error: private field '_capacity' is not used [-Werror,-Wunused-private-field]
unsigned _capacity;

rpc/rpc_impl.hh:159:13: error: unused variable 'ignore' [-Werror,-Wunused-variable]
ignorer ignore{(marshall_one(serializer, out, args), 1)...};
```

Quite a few unused variables around, though unless something is including the .cc file in this case, they ought to be just removed?  Additionally, there are a few spots where private variables are unused, which seems like an error.

4-

```
./net/api.hh:258:138: error: suggest braces around initialization of subobject [-Werror,-Wmissing-braces]
virtual future<connected_socket> connect(socket_address sa, socket_address local = socket_address(::sockaddr_in{AF_INET, INADDR_ANY, 0})) = 0;
```

The arrow points at the 0 used for the sin_addr field.  I suggest that this is a situation where zeroing out the sub-struct correctly would be more readable.

5-

```
./core/file.hh:126:20: error: 'write_dma' overrides a member function but is not marked 'override' [-Werror,-Winconsistent-missing-override]
future<size_t> write_dma(uint64_t pos, const void* buffer, size_t len, const io_priority_class& pc);
```

C++11 adds the 'override' value for overriding virtual functions.  it is a really nice feature IMO, and wouldn't be a bad thing to start enforcing.

6- This one actually results in an error:

```
http/httpd.hh:217:49: error: no matching function for call to 'to_sstring'
        _resp->_headers["Content-Length"] = to_sstring(
                                            ^~~~~~~~~~
./core/sstring.hh:662:20: note: candidate template ignored: couldn't infer template argument 'string_type'
inline string_type to_sstring(T value) {
                   ^
1 error generated.
```

I'm able to fix this by specifying the default-string_type value in the definition in addition to the forward declaration.  Seems to be a difference in spec-interpretation by the GCC and Clang folks.

7- 

```
rpc/rpc_impl.hh:844:49: error: absolute value function 'abs' given an argument of type 'int64_t' (aka 'long') but has parameter of type 'int' which may cause truncation of value [-Werror,-Wabsolute-value]
                auto it = _outstanding.find(::abs(msg_id));
                                            ^
rpc/rpc_impl.hh:844:49: note: use function 'std::abs' instead
                auto it = _outstanding.find(::abs(msg_id));
                                            ^~~~~
                                            std::abs
```

I'd suggest just fixing this one rather than ignoring it.  Minimizing usage of C functions ought to be minimized if possible anyway, and this would prevent a nasty truncation bug.

8-

```
rpc/rpc_impl.hh:247:27: error: 'static' function 'unmarshal_exception' declared in header file should be declared 'static inline' [-Werror,-Wunneeded-internal-declaration]
static std::exception_ptr unmarshal_exception(temporary_buffer<char>& data) {
```

I don't really see the value here, it IS in a HEADER so adding inline could prevent the ODR violation in the future, but I also am pretty against inline.  I'd almost say move the implementation to a .cc file instead.

9-  This one seems like a pretty serious issue.  We either should specifially delete or use the other function:

```
./types.hh:722:18: error: 'collection_type_impl::serialize' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
virtual void serialize(const void* value, bytes::iterator& out, serialization_format sf) const = 0;
             ^
./types.hh:363:18: note: hidden overloaded virtual function 'abstract_type::serialize' declared here: different number of parameters (2 vs 3)
virtual void serialize(const void* value, bytes::iterator& out) const = 0;
             ^
./types.hh:723:24: error: 'collection_type_impl::deserialize' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
virtual data_value deserialize(bytes_view v, serialization_format sf) const = 0;
                   ^
./types.hh:388:24: note: hidden overloaded virtual function 'abstract_type::deserialize' declared here: different number of parameters (1 vs 2)
virtual data_value deserialize(bytes_view v) const = 0;
```

I'd suggest overriding the base-class version and deleting it, or explicitly including it.            

10-

```
core/memory.cc:1072:3: error: unknown attribute 'externally_visible' ignored [-Werror,-Wunknown-attributes]
[[gnu::externally_visible]]
```

I suspect this was to get around a warning or something?  I think we could likely just ignore this one unless we can find an equivalent for clang.

11- Another actual error:

```
net/tls.cc:104:36: error: default initialization of an object of const type 'const gnutls_error_category' without a user-provided default constructor
static const gnutls_error_category glts_errorc;
```

Nothing is specified in this type so I understand that GCC would auto-generate the constructor, however I'd have to read the spec closer to see which is correct.  Ether way, adding:

```
 gnutls_error_category(){};
```

to the type seems like an easy enough fix.  Interesting to note that =default doesn't satisfy this?

12- Again, an actual error:

```
./utils/managed_vector.hh:52:19: error: constexpr union constructor does not initialize any member
    constexpr maybe_constructed() { }
```

I don't really get the purpose here of having a union with only 1 object, though perhaps I'm not reading deep enough into the managed_vector class.  Either way, making the ctor:

```
constexpr maybe_constructed():T{} {}
```

should be easy enough.

13- This one happens a lot:

```
build/debug/gen/cql3/CqlParser.cpp:22139:33: error: case value evaluates to -1, which cannot be narrowed to type 'ANTLR_UINT32' (aka 'unsigned int') [-Wc++11-narrowing]
                                    case EOF:
                                         ^
/usr/include/libio.h:62:14: note: expanded from macro 'EOF'
```
# define EOF (-1)

These all look like they are in generated code, so I am surprised that this happens.  It IS ignorable, but these sort of issues always give me the willies.  On one side, should this be generating with ANTLR_INT32 instead of UINT32?  

14- This one isn't seastar/scylla related, but seems to be related to the standard library.  Oddly, clang reports the following in optional:

```
In file included from ./types.hh:24:
/usr/bin/../lib/gcc/x86_64-redhat-linux/5.3.1/../../../../include/c++/5.3.1/experimental/optional:570:16: error: call to '__constexpr_addressof' is ambiguous
  { return __constexpr_addressof(this->_M_get()); }
           ^~~~~~~~~~~~~~~~~~~~~
./query-request.hh:53:48: note: in instantiation of member function 'std::experimental::fundamentals_v1::optional<range_bound<dht::ring_position> >::operator->' requested here
return range.is_singular() && range.start()->value().has_key();
                                           ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/5.3.1/../../../../include/c++/5.3.1/experimental/optional:167:20: note: candidate function [with _Tp = const range_bound<dht::ring_position>, $1 = <>]
constexpr _Tp* __constexpr_addressof(_Tp& __t)
               ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/5.3.1/../../../../include/c++/5.3.1/experimental/optional:174:17: note: candidate function [with _Tp = const range_bound<dht::ring_position>, $1 = <>]
inline _Tp* __constexpr_addressof(_Tp& __t)
```

What is curious here is that these two options have opposite enable_if_t specifications, so I don't really understand how it can be ambiguous.  Attempts to compile with -stdlib=libc++ failed due to linking issues (also, perhaps a feature request to do those?).  Sadly, this means I cannot dig further into the error list until I figure out one or the other.

```
/**
  * @brief An overload that attempts to take the address of an lvalue as a
  * constant expression. Falls back to __addressof in the presence of an
  * overloaded addressof operator (unary operator&), in which case the call
  * will not be a constant expression.
  */
template<typename _Tp, enable_if_t<!_Has_addressof<_Tp>::value, int>...>
  constexpr _Tp* __constexpr_addressof(_Tp& __t)
  { return &__t; }

/**
  * @brief Fallback overload that defers to __addressof.
  */
template<typename _Tp, enable_if_t<_Has_addressof<_Tp>::value, int>...>
  inline _Tp* __constexpr_addressof(_Tp& __t)
  { return std::__addressof(__t); }
```

As mentioned, sadly 14 above and the issue I'm having with linking libstdc++ seems to have stopped more progress.  Additionally, the ability to configure the lib version would also be helpful I believe!

**Comment by gleb-cloudius** [comment]
On Mon, Jan 25, 2016 at 11:38:49AM -0800, Erich Keane wrote:
> I'm running clang++ 3.7.0 (tags/RELEASE_370/final) on fedora.  I've been able to get g++ to compile fine, but in an effort to run some clang-based tools I figured I'd try to get clang to compile Scylla first!
> 
> I submitted this patch: https://groups.google.com/forum/#!topic/scylladb-dev/V5R91lAzGw0 which is a prerequisite to get clang to attempt to compile the code, and the following warnings would need to be disabled or fixed.  Either way, I'm willing to do this and submit a patch, I'd just like some guidance as to which I should do in each case.  
> 
> I'll note that many appear in seastar, so I can contribute those separately as well (I know the same company runs both, so I figured a single bug report would be acceptable).  Note that each is just an example of the error, not an exhaustive list.
> 
> 1:
> 
>     ./core/future-util.hh:103:32: error: moving a temporary object prevents copy elision [-Werror,-Wpessimizing-move]
>                     state.ex = std::move(std::current_exception());
> 
> Essentially, the std::move call prevents copy-in-place for Return Value Optimization.  I would say that since RVO is more performant that removing the move would be prudent.
> 
Yes, move is not needed here and actually harmful.

> 2-
> 
>     /mnt/500gbdisk/scylla/seastar/net/packet.hh:136:24: error: redundant move in return statement [-Werror,-Wredundant-move]
>                 return std::move(old);
> 
> Essentially, the compiler is sure it should do a move anyway (in this case because 'old' is a unique_ptr).  I suspect that disabling this one is preferential.
Hmm why 'old' been unique_ptr matters to a compiler? Compiler moves
local variable automatically on return IIRC.

> 
> 3-
> 
>     http/reply.cc:96:12: error: unused variable 'name_value_separator' [-Werror,-Wunused-const-variable]
>     const char name_value_separator[] = { ':', ' ' };
> 
>     core/fair_queue.hh:93:14: error: private field '_capacity' is not used [-Werror,-Wunused-private-field]
>     unsigned _capacity;
>     
>     rpc/rpc_impl.hh:159:13: error: unused variable 'ignore' [-Werror,-Wunused-variable]
>     ignorer ignore{(marshall_one(serializer, out, args), 1)...};
> 
The last one is clang been silly. The variable is needed for a side
effect. We can rewrite it as a function "void ignore(...)" instead.

> I'm able to fix this by specifying the default-string_type value in the definition in addition to the forward declaration.  Seems to be a difference in spec-interpretation by the GCC and Clang folks.
> 
> 7- 
> 
>     rpc/rpc_impl.hh:844:49: error: absolute value function 'abs' given an argument of type 'int64_t' (aka 'long') but has parameter of type 'int' which may cause truncation of value [-Werror,-Wabsolute-value]
>                     auto it = _outstanding.find(::abs(msg_id));
>                                                 ^
>     rpc/rpc_impl.hh:844:49: note: use function 'std::abs' instead
>                     auto it = _outstanding.find(::abs(msg_id));
>                                                 ^~~~~
>                                                 std::abs
> 
> I'd suggest just fixing this one rather than ignoring it.  Minimizing usage of C functions ought to be minimized if possible anyway, and this would prevent a nasty truncation bug.
> 
Agree.

> 8-
> 
>     rpc/rpc_impl.hh:247:27: error: 'static' function 'unmarshal_exception' declared in header file should be declared 'static inline' [-Werror,-Wunneeded-internal-declaration]
>     static std::exception_ptr unmarshal_exception(temporary_buffer<char>& data) {
> 
> I don't really see the value here, it IS in a HEADER so adding inline could prevent the ODR violation in the future, but I also am pretty against inline.  I'd almost say move the implementation to a .cc file instead.
> 
I would just add inline there and keep the whole implementation in one
file. The file is .hh because most of the code there is templated.

--
			Gleb.

**Comment by avikivity** [comment]
On 01/25/2016 09:38 PM, Erich Keane wrote:
>
> I'm running clang++ 3.7.0 (tags/RELEASE_370/final) on fedora. I've 
> been able to get g++ to compile fine, but in an effort to run some 
> clang-based tools I figured I'd try to get clang to compile Scylla first!
>
> I submitted this patch: 
> https://groups.google.com/forum/#!topic/scylladb-dev/V5R91lAzGw0 
> <https://groups.google.com/forum/#%21topic/scylladb-dev/V5R91lAzGw0> 
> which is a prerequisite to get clang to attempt to compile the code, 
> and the following warnings would need to be disabled or fixed. Either 
> way, I'm willing to do this and submit a patch, I'd just like some 
> guidance as to which I should do in each case.
>

Probably the best way forward is to use a brute force approach to get 
things to compile (i.e. disable warnings indiscriminately), commit that, 
and then incrementally re-enable warnings and fix them up, because some 
of them are valuable.

We will enable a continuous integration job with clang so we don't regress.

> I'll note that many appear in seastar, so I can contribute those 
> separately as well (I know the same company runs both, so I figured a 
> single bug report would be acceptable). Note that each is just an 
> example of the error, not an exhaustive list.
>
> 1:
>
> |./core/future-util.hh:103:32: error: moving a temporary object 
> prevents copy elision [-Werror,-Wpessimizing-move] state.ex = 
> std::move(std::current_exception()); |
>
> Essentially, the std::move call prevents copy-in-place for Return 
> Value Optimization. I would say that since RVO is more performant that 
> removing the move would be prudent.
>

Agree, move(function_call()) is almost always incorrect (counterexample 
is when function_call() returns a mutable reference by design, but in 
this specific use case you don't care about the original value).

> 2-
>
> |/mnt/500gbdisk/scylla/seastar/net/packet.hh:136:24: error: redundant 
> move in return statement [-Werror,-Wredundant-move] return 
> std::move(old); |
>
> Essentially, the compiler is sure it should do a move anyway (in this 
> case because 'old' is a unique_ptr). I suspect that disabling this one 
> is preferential.
>
> 3-
>
> |http/reply.cc:96:12: error: unused variable 'name_value_separator' 
> [-Werror,-Wunused-const-variable] const char name_value_separator[] = 
> { ':', ' ' }; core/fair_queue.hh:93:14: error: private field 
> '_capacity' is not used [-Werror,-Wunused-private-field] unsigned 
> _capacity; rpc/rpc_impl.hh:159:13: error: unused variable 'ignore' 
> [-Werror,-Wunused-variable] ignorer ignore{(marshall_one(serializer, 
> out, args), 1)...}; |
>
> Quite a few unused variables around, though unless something is 
> including the .cc file in this case, they ought to be just removed? 
> Additionally, there are a few spots where private variables are 
> unused, which seems like an error.
>

Yeah they should be removed, but this can be done lazily (after clang is 
working).

> 4-
>
> |./net/api.hh:258:138: error: suggest braces around initialization of 
> subobject [-Werror,-Wmissing-braces] virtual future<connected_socket> 
> connect(socket_address sa, socket_address local = 
> socket_address(::sockaddr_in{AF_INET, INADDR_ANY, 0})) = 0; |
>
> The arrow points at the 0 used for the sin_addr field. I suggest that 
> this is a situation where zeroing out the sub-struct correctly would 
> be more readable.
>

Right.

> 5-
>
> |./core/file.hh:126:20: error: 'write_dma' overrides a member function 
> but is not marked 'override' [-Werror,-Winconsistent-missing-override] 
> future<size_t> write_dma(uint64_t pos, const void* buffer, size_t len, 
> const io_priority_class& pc); |
>
> C++11 adds the 'override' value for overriding virtual functions. it 
> is a really nice feature IMO, and wouldn't be a bad thing to start 
> enforcing.
>

Definitely.

> 6- This one actually results in an error:
>
> |http/httpd.hh:217:49: error: no matching function for call to 
> 'to_sstring' _resp->_headers["Content-Length"] = to_sstring( 
> ^~~~~~~~~~ ./core/sstring.hh:662:20: note: candidate template ignored: 
> couldn't infer template argument 'string_type' inline string_type 
> to_sstring(T value) { ^ 1 error generated.|

I think that's a bug in clang, though it seems we'd trip over this in 
many places.  We have

   template <typename string_type = sstring, typename T>
   inline string_type to_sstring(T value);

so string_type has a default.


> ||
>
> I'm able to fix this by specifying the default-string_type value in 
> the definition in addition to the forward declaration. Seems to be a 
> difference in spec-interpretation by the GCC and Clang folks.
>
> 7-
>
> |rpc/rpc_impl.hh:844:49: error: absolute value function 'abs' given an 
> argument of type 'int64_t' (aka 'long') but has parameter of type 
> 'int' which may cause truncation of value [-Werror,-Wabsolute-value] 
> auto it = _outstanding.find(::abs(msg_id)); ^ rpc/rpc_impl.hh:844:49: 
> note: use function 'std::abs' instead auto it = 
> _outstanding.find(::abs(msg_id)); ^~~~~ std::abs |
>
> I'd suggest just fixing this one rather than ignoring it. Minimizing 
> usage of C functions ought to be minimized if possible anyway, and 
> this would prevent a nasty truncation bug.
>

Definitely, a serious bug.

> 8-
>
> |rpc/rpc_impl.hh:247:27: error: 'static' function 'unmarshal_exception' 
> declared in header file should be declared 'static inline' 
> [-Werror,-Wunneeded-internal-declaration] static std::exception_ptr 
> unmarshal_exception(temporary_buffer<char>& data) { |
>
> I don't really see the value here, it IS in a HEADER so adding inline 
> could prevent the ODR violation in the future, but I also am pretty 
> against inline. I'd almost say move the implementation to a .cc file 
> instead.
>

As it's an exceptional case, sure.

> 9- This one seems like a pretty serious issue. We either should 
> specifially delete or use the other function:
>
> |./types.hh:722:18: error: 'collection_type_impl::serialize' hides 
> overloaded virtual function [-Werror,-Woverloaded-virtual] virtual 
> void serialize(const void* value, bytes::iterator& out, 
> serialization_format sf) const = 0; ^ ./types.hh:363:18: note: hidden 
> overloaded virtual function 'abstract_type::serialize' declared here: 
> different number of parameters (2 vs 3) virtual void serialize(const 
> void* value, bytes::iterator& out) const = 0; ^ ./types.hh:723:24: 
> error: 'collection_type_impl::deserialize' hides overloaded virtual 
> function [-Werror,-Woverloaded-virtual] virtual data_value 
> deserialize(bytes_view v, serialization_format sf) const = 0; ^ 
> ./types.hh:388:24: note: hidden overloaded virtual function 
> 'abstract_type::deserialize' declared here: different number of 
> parameters (1 vs 2) virtual data_value deserialize(bytes_view v) const 
> = 0; |
>
> I'd suggest overriding the base-class version and deleting it, or 
> explicitly including it.
>

Those are by design, though probably bad design, but the code works.  
The serialize() family that accepts serialization_format should be renamed.

A little more involved fix is to unify the two families by adding the 
serialization_format parameter to abstract_type::serialize() and all its 
descendants, defaulting it to serialization_format::internal.  Then 
thunks like

   void
   set_type_impl::serialize(const void* value, bytes::iterator& out) const {
     return serialize(value, out, serialization_format::internal());
   }

simply disappear.

> 10-
>
> |core/memory.cc:1072:3: error: unknown attribute 'externally_visible' 
> ignored [-Werror,-Wunknown-attributes] [[gnu::externally_visible]] |
>
> I suspect this was to get around a warning or something? I think we 
> could likely just ignore this one unless we can find an equivalent for 
> clang.
>

Needed for link-time optimization, or the compiler can disappear these 
functions, but when some library calls them, it calls the wrong 
(standard) version.

> 11- Another actual error:
>
> |net/tls.cc:104:36: error: default initialization of an object of const 
> type 'const gnutls_error_category' without a user-provided default 
> constructor static const gnutls_error_category glts_errorc; |
>
> Nothing is specified in this type so I understand that GCC would 
> auto-generate the constructor, however I'd have to read the spec 
> closer to see which is correct. Ether way, adding:
>
> |gnutls_error_category(){}; |
>
> to the type seems like an easy enough fix. Interesting to note that 
> =default doesn't satisfy this?
>

Again this smells like a compiler bug, but so trivial, I have a hard 
time believing it.

What does std::error_category look like on your system?  Are you using 
libstdc++ or libc++?

> 12- Again, an actual error:
>
> |./utils/managed_vector.hh:52:19: error: constexpr union constructor 
> does not initialize any member constexpr maybe_constructed() { } |
>
> I don't really get the purpose here of having a union with only 1 
> object, though perhaps I'm not reading deep enough into the 
> managed_vector class.
>

The object can be either constructed or not constructed.  clang is 
simply not respecting our artisitic freedom.

> Either way, making the ctor:
>
> |constexpr maybe_constructed():T{} {}|

But it's wrong, now the object is constructed when it ought not to be.

> ||
>
> should be easy enough.
>
> 13- This one happens a lot:
>
> |build/debug/gen/cql3/CqlParser.cpp:22139:33: error: case value 
> evaluates to -1, which cannot be narrowed to type 'ANTLR_UINT32' (aka 
> 'unsigned int') [-Wc++11-narrowing] case EOF: ^ 
> /usr/include/libio.h:62:14: note: expanded from macro 'EOF'|

Generated code, nothing we can do about it (except maybe sed it away 
during code generation).

> ||
>
>
>   define EOF (-1)
>
> These all look like they are in generated code, so I am surprised that 
> this happens. It IS ignorable, but these sort of issues always give me 
> the willies. On one side, should this be generating with ANTLR_INT32 
> instead of UINT32?
>
> 14- This one isn't seastar/scylla related, but seems to be related to 
> the standard library. Oddly, clang reports the following in optional:
>
> |In file included from ./types.hh:24: 
> /usr/bin/../lib/gcc/x86_64-redhat-linux/5.3.1/../../../../include/c++/5.3.1/experimental/optional:570:16: 
> error: call to '__constexpr_addressof' is ambiguous { return 
> __constexpr_addressof(this->_M_get()); } ^~~~~~~~~~~~~~~~~~~~~ 
> ./query-request.hh:53:48: note: in instantiation of member function 
> 'std::experimental::fundamentals_v1::optional<range_bound<dht::ring_position> 
> >::operator->' requested here return range.is_singular() && 
> range.start()->value().has_key(); ^ 
> /usr/bin/../lib/gcc/x86_64-redhat-linux/5.3.1/../../../../include/c++/5.3.1/experimental/optional:167:20: 
> note: candidate function [with _Tp = const 
> range_bound<dht::ring_position>, $1 = <>] constexpr _Tp* 
> __constexpr_addressof(_Tp& __t) ^ 
> /usr/bin/../lib/gcc/x86_64-redhat-linux/5.3.1/../../../../include/c++/5.3.1/experimental/optional:174:17: 
> note: candidate function [with _Tp = const 
> range_bound<dht::ring_position>, $1 = <>] inline _Tp* 
> __constexpr_addressof(_Tp& __t) |
>
> What is curious here is that these two options have opposite 
> enable_if_t specifications, so I don't really understand how it can be 
> ambiguous. Attempts to compile with -stdlib=libc++ failed due to 
> linking issues (also, perhaps a feature request to do those?). Sadly, 
> this means I cannot dig further into the error list until I figure out 
> one or the other.
>
> |/** * @brief An overload that attempts to take the address of an 
> lvalue as a * constant expression. Falls back to __addressof in the 
> presence of an * overloaded addressof operator (unary operator&), in 
> which case the call * will not be a constant expression. */ 
> template<typename _Tp, enable_if_t<!_Has_addressof<_Tp>::value, 
> int>...> constexpr _Tp* __constexpr_addressof(_Tp& __t) { return &__t; 
> } /** * @brief Fallback overload that defers to __addressof. */ 
> template<typename _Tp, enable_if_t<_Has_addressof<_Tp>::value, 
> int>...> inline _Tp* __constexpr_addressof(_Tp& __t) { return 
> std::__addressof(__t); }|

Maybe _Has_addressof doesn't compile, so both _Has_addressof and 
!_Has_addressof are represented internally by the same "compilation 
error" object, and now the thing really is ambiguous.  See if there are 
later complaints.

> ||
>
> As mentioned, sadly 14 above and the issue I'm having with linking 
> libstdc++ seems to have stopped more progress. Additionally, the 
> ability to configure the lib version would also be helpful I believe!
>
>

Surely clang provides an option to specify the C++ library?

**Comment by pdziepak** [comment]
On 26 January 2016 at 09:31, Avi Kivity <notifications@github.com> wrote:

>
>
> On 01/25/2016 09:38 PM, Erich Keane wrote:
> > 12- Again, an actual error:
> >
> > |./utils/managed_vector.hh:52:19: error: constexpr union constructor
> > does not initialize any member constexpr maybe_constructed() { } |
> >
> > I don't really get the purpose here of having a union with only 1
> > object, though perhaps I'm not reading deep enough into the
> > managed_vector class.
> >
>
> The object can be either constructed or not constructed. clang is
> simply not respecting our artisitic freedom.
>
> I think it is actually the C++ standard limiting our freedom here. Anyway,
dropping constexpr should solve the problem.

**Comment by erichkeane** [comment]
I hope the formatting ends up being alright, lots to reply to on this one :) 

> Hmm why 'old' been unique_ptr matters to a compiler? Compiler moves local variable automatically on return IIRC.

In many cases, it could RVO instead, however it cannot in this case because it is a unique_ptr coming from the parameter.  I suspect in retrospect that it still COULD use RVO but I seem to remember this code having a branch.

> The last one is clang been silly. The variable is needed for a side effect. We can rewrite it as a function "void ignore(...)" instead.

Ah!  In that case, check out Eric Niebler's For-Each-Parameter!  He faces the same unused-variable problem, and solves it by using an initializer list cast to a void.  It is a super pretty function anyway :)  The existing way is subject to reordering (since they are parameters) as well as potential optimizing, though the compiler should know that the marshal-one function has side effects and still execute them.  See Niebler's for-each-arg:

    template<class F, class...Ts>
    F for_each_arg(F f, Ts&&...a) {
      return (void)initializer_list<int>{(ref(f)((Ts&&)a),0)...}, f;
    }

> I would just add inline there and keep the whole implementation in one file. The file is .hh because most of the code there is templated.

Fair enough!

> Probably the best way forward is to use a brute force approach to get things to compile (i.e. disable warnings indiscriminately), commit that, and then incrementally re-enable warnings and fix them up, because some of them are valuable. We will enable a continuous integration job with clang so we don't regress.

Alright, sounds good!  I'm facing a few other issues with clang (the libstdc++ optional doesn't seem to compile with it, and using libc++ seems to have some issues with my configuration.  I'll keep working on it to see if I can get that setup correctly.

> I think that's a bug in clang, though it seems we'd trip over this in many places. We have template <typename string_type = sstring, typename T> inline string_type to_sstring(T value); so string_type has a default.

This was actually the only case where this showed up!  I was speaking with a friend who is a bit more in-tune with the standard, and he seems to believe that forward-declarations being able to set default parameters might be ambiguous in the standard.  I haven't had the time to dig through it yet, but can definitely do that next time I have that chance.  In the meantime, re-setting the default in the implementation was enough to silence the compiler.



> Needed for link-time optimization, or the compiler can disappear these functions, but when some library calls them, it calls the wrong (standard) version.

Ah!  Then we shouldn't ignore this.  It seems that it is a case where we need to find the clang equivalent and add that as well. 

> Again this smells like a compiler bug, but so trivial, I have a hard time believing it. What does std::error_category look like on your system? Are you using libstdc++ or libc++?

I'm using libstdc++.  I suspect that the default constructor of std::error_category is not being picked up by clang, or clang is being more strict in this case.  I see that the constexpr default ctor was added in C++14, so I wonder if clang is treating --std=gnu1y as c++11?  I can try to see if switching that to --std=c++14 might help (assuming no other extensions are being used).

> The object can be either constructed or not constructed. clang is simply not respecting our artisitic freedom.

Now that you say that, I definitely see its purpose!  It should have been obvious based on the name, but I clearly missed it!  In this case, I am concerned that clang is enforcing the standard more correctly and this will bite us when GCC hits 6.0 or something.  If I get a chance (or if someone beats me to it!), looking at optional/variant might give some hints as to how to implement this better (or perhaps changing this out with an optional?).

> Generated code, nothing we can do about it (except maybe sed it away during code generation).

Easy enough to just ignore that one, figured we might have control of the generated types some how else.

> Maybe _Has_addressof doesn't compile, so both _Has_addressof and !_Has_addressof are represented internally by the same "compilation error" object, and now the thing really is ambiguous. See if there are later complaints.

Good call!  I'll have to give that a try.  I didn't see any later, related complaints, but I can extract the _Has_addressof and give it a try in a smaller test.



> Surely clang provides an option to specify the C++ library?

It does, but sadly that doesn't compile either for me (it says it cannot find <algorithm>).  I suspect strongly that I just have it configured oddly on my system somewhere, so I'll keep at it.

**Comment by erichkeane** [comment]
> The last one is clang been silly. The variable is needed for a side effect. We can rewrite it as a function "void ignore(...)" instead.
> 
> Ah! In that case, check out Eric Niebler's For-Each-Parameter! He faces the same unused-variable problem, and solves it by using an initializer list cast to a void. It is a super pretty function anyway :) The existing way is subject to reordering (since they are parameters) as well as potential optimizing, though the compiler should know that the marshal-one function has side effects and still execute them.

Just looked at this one a bit closer (interesting to see some of the tricks you guys are doing in this code base!) and see that you comment on the order.  I wasn't aware that brace initialization guarantees execution order, cool!

That said, I think that the Niebler version quoted above is a bit more terse (since it doesn't require a separate type, it just re-uses initializer_list) and is the same thing.  Could get the same behavior (fixing the warning) by just doing the void-cast as was mentioned above.

**Comment by avikivity** [comment]
Now works with latest clang.
