### ISSUE TITLE
Installation of unified-deb fails sporadically: Unable to fetch some archives

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla#8402]
I added a simple installation test to the unified-deb job.
A significant number of them fail:

> Step 16/16 : RUN apt-get install $SCYLLA_PRODUCT_NAME -y -qq
>  ---> Running in 631b12f08b6b
>  [91mE: Failed to fetch http://downloads.scylladb.com/unstable/scylla/master/deb/unified/2021-03-25T09:24:07Z/scylladb-master/pool/main/s/scylla-server/scylla-node-exporter_4.5.dev-0.20210325.c1daf2bb24-1_amd64.deb  500  Internal Server Error [IP: 52.216.86.202 80]
> E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
>  [0mThe command '/bin/sh -c apt-get install $SCYLLA_PRODUCT_NAME -y -qq' returned a non-zero code: 100
>
>
Looks like an AWS server failure:
500  Internal Server Error [IP: 52.216.86.202 80]

@penberg: Not sure how to work around this. Perhaps we can retry the:
"apt update" command few times.

Please look on the logs on https://jenkins.scylladb.com/job/scylla-master/job/releng-testing/job/unified-deb/408/artifact/
I ran 11 installations, 4 failes, 7 passed:
Warning: Installation tests for some distributions on mode release failed: |ubuntu20.04, ubuntu18.04, | and for some passed: |ubuntu16.04, debian10, debian9, |
Warning: Installation tests for some distributions on mode debug failed: |debian9, | and for some passed: |debian10, ubuntu18.04, ubuntu16.04, ubuntu20.04, |
Warning: Installation tests for all distributions on mode release on latest repo failed: |ubuntu20.04, | passed: ||
This is just an example. Similar failures happen on most of the runs.

**Comment by yaronkaikov** [comment]
@hagitsegev once you start the docker, are you performing the command `apt update` ?

**Comment by hagitsegev** [comment]
Yes, I have:
apt update -y -qq

**Comment by hagitsegev** [comment]
Still happens.

**Comment by avikivity** [comment]
Use apt-get instead of apt in scripts, apt can change its syntax while apt-get is stable.

Looks like you can add `-o Acquire::Retries=3`  (https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1876035) and get to retry automatically.

**Comment by hagitsegev** [comment]
I added some retries upon @avikivity suggestion on https://github.com/scylladb/scylla-pkg/pull/2178
I didn't see this failure again after that, so I'm closing.
