### ISSUE TITLE
Reject replacing a node that has left the ring

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#8419]
Consider:

1) start n1, n2, n3

2) decommission n3

3) remove /var/lib/scylla for n3

4) start n4 with the same ip address to replace n3

5) replace will be successful

If a node has left the ring, we should reject the replace operation.
****

**Comment by eliransin** [comment]
Can we backport this to 4.3?

**Comment by avikivity** [comment]
We don't backport to specific branches; instead we backport to all versions above some release stream.

Why do you think this should be backported?

**Comment by eliransin** [comment]
> Why do you think this should be backported?

scylladb/scylla-enterprise#1690
