### ISSUE TITLE
`clustering_order_reader_merger` may immediately return end-of-stream if some (but not necessarily all) underlying readers are empty

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#8445]
And this could happen in places where it's used (namely `time_series_sstable_set::create_single_key_sstable_reader`) if we opened an sstable which did not have the queried partition but passed all the filters (specifically, the bloom filter returned a false positive for this sstable).

**Comment by kbr-** [comment]
Depends on #8432 (already in master but for backporting purposes).

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
