### ISSUE TITLE
Avoid two compaction passes when reshaping STCS table for repair-based operations

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#8449]
Currently, input data is compacted twice because max threshold of 32 is respected by STCS reshape.

However, repair-based operation produces disjoint sstables, so we can avoid two compaction passes on the input data **(therefore reducing writeamp by 1)** by compacting all the data in a single compaction job. That requires changing reshape compaction to always use partitioned_sstable_set (forcing it to put everything in interval map), so resource usage is limited by the fact that the sstables can be incrementally compacted (one by one) given their disjointness.

**Comment by raphaelsc** [comment]
Refs #5226.

**Comment by slivne** [comment]
I don;t think this is true for all repair based operations - its true for bootstrap - unless I am missing something - please clarify,

Lets first get the tests passing without this oprimization

**Comment by raphaelsc** [comment]
On Sat, Apr 10, 2021, 5:56 AM Shlomi Livne ***@***.***> wrote:

> I don;t think this is true for all repair based operations - its true for
> bootstrap - unless I am missing something - please clarify,
>
From my understanding, for all repair-based ops, there will be only one
sstable per vnode range, so sstables are disjoint. @Asias He
***@***.***> please confirm this.


Lets first get the tests passing without this oprimization

**Comment by asias** [comment]
> On Sat, Apr 10, 2021, 5:56 AM Shlomi Livne ***@***.***> wrote: I don;t think this is true for all repair based operations - its true for bootstrap - unless I am missing something - please clarify,
> From my understanding, for all repair-based ops, there will be only one sstable per vnode range, so sstables are disjoint. @asias, please confirm this.

Yes, repair generates at most one sstable per vnode range per shard.

**Comment by bhalevy** [comment]
> Yes, repair generates at most one sstable per vnode range per shard.

@asias is it true also with TWCS?
Isn't at one sstable per vnode range per shard per time-window bucket?

**Comment by raphaelsc** [comment]
> > Yes, repair generates at most one sstable per vnode range per shard.
> 
> @asias is it true also with TWCS?
> Isn't at one sstable per vnode range per shard per time-window bucket?

with TWCS, we'll segregate, so yes, one sst for each window in each vnode range. not relevant for this issue though.

**Comment by bhalevy** [comment]
> with TWCS, we'll segregate, so yes, one sst for each window in each vnode range. not relevant for this issue though.

Why isn't it relevant? Don't we basically run STCS in each bucket?
If we have more than 32 sstables in a single bucket that are disjoint in the token-range dimension we can also take advantage of that and compact all of them together in a single pass.

**Comment by raphaelsc** [comment]
> > with TWCS, we'll segregate, so yes, one sst for each window in each vnode range. not relevant for this issue though.
> 
> Why isn't it relevant? Don't we basically run STCS in each bucket?
> If we have more than 32 sstables in a single bucket that are disjoint in the token-range dimension we can also take advantage of that and compact all of them together in a single pass.

we don't run STCS in each bucket. but you're right. jobs spanning single window are trimmed to max threshold. Somehow I assumed we didn't trim and thus TWCS wasn't affected. thanks!
