### ISSUE TITLE
'nodetool enablebackup' neither returns an error nor enables incremental backups

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#845]
scylla HEAD:  
```
commit b5833e8002f4d47b1638984b119374b488397b31
Merge: 5e953b5 de3bb01
Author: Pekka Enberg <penberg@scylladb.com>
Date:   Thu Jan 21 18:52:07 2016 +0200

    Merge "Enable incremental backups option" from Vlad
```
Running `nodetool enablebackup` doesn't enable incremental backups, while command line `--incremental-backups 1` does.

**Comment by amnonh** [comment]
Are you sure it's not working?
See the following nodetool command
$ nodetool  statusbackup
not running
$ nodetool  enablebackup
$ nodetool  statusbackup
running

**Comment by amnonh** [comment]
@vladzcloudius can you verify this?

**Comment by slivne** [comment]
reassigining vlad this is not for GA - so its the last in your queue

**Comment by vladzcloudius** [comment]
On 03/03/2016 05:00 PM, slivne wrote:
>
> reassigining vlad this is not for GA - so its the last in your queue
>

Got it.

**Comment by vladzcloudius** [comment]
@amnonh The issue was caused by the fact that the corresponding API code was not updating the `incremental_backups` configuration value (how could it!) but only the configuration of the existing keyspaces and column families. As a result the newly created objects (e.g. keyspaces) were still using the original configuration for .yaml or a command line parameter.

I've sent a patch series with the fix on a scyllladb-dev list.
