### ISSUE TITLE
mislicensed source files

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#8465]
A few sources files have the proprietray license instead of AGPL, by accident.

**Comment by nyh** [comment]
By the way a different kind of mistake is code which is 100% Scylla but has Cassandra's ASF copyright and "Modified by ScyllaDB".
The first example of this I found is cdc/generation_service.hh but a grep of "Modified by ScyllaDB" yields a few other suspects.

**Comment by avikivity** [comment]
We can remove this "Modified by ScyllaDB". I learned that out copyright suffices for the requirement that a prominent notice of modification be present.

**Comment by nyh** [comment]
> We can remove this "Modified by ScyllaDB". I learned that out copyright suffices for the requirement that a prominent notice of modification be present.

Yes. I pointed to the "Modified by ScyllaDB" just as a grep aid. But you can also directly grep -w ASF to look for these source files which we attribute to the ASF, but might have nothing to do with them.
