### ISSUE TITLE
Upgrade issues from  4.3 to 4.4

### ISSUE THREAD

**Issue by praveenkhatra** [scylladb/scylla#8467]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
I was running scylla 4.3 without any issues and started to perform the upgrade  from 4.3 to 4.4 using https://docs.scylladb.com/upgrade/upgrade-opensource/upgrade-guide-from-4.3-to-4.4/upgrade-guide-from-4.3-to-4.4-ubuntu-20-04/ 

1. First of all I didn't understand why we are forced to upgrade other non-scylla components with this installation like docker-ce docker-ce-cli docker-ce-rootless-extras ?
2. why scylla-kernel-conf is picking the default value instead of the value configured in sysctl.conf?
3. The restore option is incomplete. I tried to perform restore using the snashot for System and system_schema. I only got two  files in the   snapshot directory as schema.cql and manifest.json . I checked the other working cluster member and they don't have these files. I don't see how the copy of these files work   in original path?
Scylla version (or git commit hash):
Cluster size: 3 node
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04

Platform (physical/VM/cloud instance type/docker): Physical
Hardware: sockets= cores= hyperthreading= memory= 230GB/ 128 Core with HT
Disks: (SSD/HDD, count): SSD 5 TB with RAID 0

**Comment by praveenkhatra** [comment]
/opt/scylladb/scripts/perftune.py --tune disks --dir /scylla_data/scylla/data --dir /scylla_data/scylla/commitlog --dir /scylla_data/scylla/hints --dir /scylla_data/scylla/view_hints --tune net --nic bond0 --get-cpu-mask
ERROR: 'bond0'. Your system can't be tuned until the issue is fixed.

**Comment by avikivity** [comment]
Are you using bonded NICs?

**Comment by praveenkhatra** [comment]
Yes. I am using Bonded NIC and it was working fine with 4.3 and it seems the  rollback is also not possible.
/opt/scylladb/scripts/scylla_prepare
ERROR: unhashable type: 'list'. Your system can't be tuned until the issue is fixed.
Exception occurred while creating perftune.yaml: Command '['/opt/scylladb/scripts/perftune.py', '--tune', 'disks', '--dir', '/scylla_data/scylla/data', '--dir', '/scylla_data/scylla/commitlog', '--dir', '/scylla_data/scylla/hints', '--dir', '/scylla_data/scylla/view_hints', '--options-file', '/etc/scylla.d/perftune.yaml']' returned non-zero exit status 1.
To fix the error, please re-run scylla_setup.

I have executed the scylla_setup 4-5 times but nothing is working and getting the same error again. Also there is no perftune.yaml file created after executed the scylla_setup.

**Comment by avikivity** [comment]
We have this in 4.4:

commit e81f4caf677c6ad3816128fbb60cbe104414a03c
Author: Pekka Enberg <penberg@scylladb.com>
Date:   Thu Jan 7 09:34:56 2021 +0200

    Update seastar submodule
    
    * seastar a2fc9d72...56cfe179 (1):
      > perftune.py: Fix nic_is_bond_iface() and other function signatures
    Refs #6266

**Comment by avikivity** [comment]
Which points to scylladb/seastar@56cfe17970f3798321a36e73ab212ca2be015d14

**Comment by avikivity** [comment]
Which in turn blames scylladb/seastar@a2fc9d72c31b97840bc75ae49dbd6f4b6d394e25 for the regression.

**Comment by avikivity** [comment]
Well, 4.4 isn't missing backports that I can see.

**Comment by avikivity** [comment]
Ah, I see this `ERROR: unhashable type: 'list'.`. Please run perftune.py manually and obtain a backtrace.

**Comment by avikivity** [comment]
> 
> 1. First of all I didn't understand why we are forced to upgrade other non-scylla components with this installation like docker-ce docker-ce-cli docker-ce-rootless-extras ?

You aren't forced. If you don't want to upgrade them, don't upgrade them.

> 2. why scylla-kernel-conf is picking the default value instead of the value configured in sysctl.conf?

It needs those values to perform well.

**Comment by praveenkhatra** [comment]
1. We are forced to upgrade these components when we used the command "sudo apt-get dist-upgrade scylla"
2.  The value is configured in sysctl.conf is higher than the  default value that it set by scylla in /proc/sys/fs/aio-max-nr so this should pick from  sysctl.conf. If not configured in sysctl.conf then it should set the recommended value.
3. I executed this command on Version 4.3 which was failing on 4.4 and now the  node is  up with version 4.3.
/opt/scylladb/scripts/perftune.py --tune disks --dir /scylla_data/scylla/data --dir /scylla_data/scylla/commitlog --dir /scylla_data/scylla/hints --dir /scylla_data/scylla/view_hints --tune net --nic bond0 --get-cpu-mask

**Comment by avikivity** [comment]
> 1. We are forced to upgrade these components when we used the command "sudo apt-get dist-upgrade scylla"

I am not an apt expert. Scylla doesn't mention docker-ce in any way. If apt thought it has to upgrade, please ask the apt maintainers why it works this way.

> 2. The value is configured in sysctl.conf is higher than the  default value that it set by scylla in /proc/sys/fs/aio-max-nr so this should pick from  sysctl.conf. If not configured in sysctl.conf then it should set the recommended value.

You can choose not to install scylla-kernel-conf (by not installing the scylla superpackage) if you want to configure things on your own (but then you are responsible for getting the values correct).

> 3. I executed this command on Version 4.3 which was failing on 4.4 and now the  node is  up with version 4.3.
>    /opt/scylladb/scripts/perftune.py --tune disks --dir /scylla_data/scylla/data --dir /scylla_data/scylla/commitlog --dir /scylla_data/scylla/hints --dir /scylla_data/scylla/view_hints --tune net --nic bond0 --get-cpu-mask

Please execute it on 4.4 so we get more information on the failure.

**Comment by praveenkhatra** [comment]
can we change the log file location and file name of scylla-server log from /var/log/syslog  in Ubuntu 20.04 ? Reason is that it occupying the space very much.

**Comment by praveenkhatra** [comment]
/opt/scylladb/scripts/perftune.py --tune disks --dir /scylla_data/scylla/data --dir /scylla_data/scylla/commitlog --dir /scylla_data/scylla/hints --dir /scylla_data/scylla/view_hints --tune net --nic bond0 --get-cpu-mask
ERROR: 'bond0'. Your system can't be tuned until the issue is fixed.

Executed earlier on 4.4

**Comment by praveenkhatra** [comment]
HI @avikivity . Thanks for your help. I will keep this issue open as I will perform an upgrade of 4.4.1  tomorrow as a recent release.

**Comment by thirstycrow** [comment]
Got the same issue with 4.4.1. It seems fixed by https://github.com/scylladb/seastar/commit/5e6f9a8af2bf8549f567e0f67c35ff24d5e63e19

**Comment by avikivity** [comment]
@vladzcloudius please confirm

**Comment by vladzcloudius** [comment]
> @vladzcloudius please confirm

@avikivity bonding configuration is broken without scylladb/seastar@5e6f9a8 in 4.4.1

**Comment by praveenkhatra** [comment]
@vladzcloudius @avikivity . Thanks for your help. The issue was with the seaster code and that was fixed by @vladzcloudius . Now the issue is resolved as after this I was able to perform the upgrade successfully.
