### ISSUE TITLE
Need to sign on our Ubuntu and Debian package

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#848]
Need to sign on our Ubuntu package, otherwise user will get alert on apt-get like this:

```
WARNING: The following packages cannot be authenticated!
  scylla-tools
Install these packages without verification? [y/N] 
```

**Comment by avikivity** [comment]
Does this require a pgp key?

**Comment by syuu1228** [comment]
I think so.
I found an instruction on Ubuntu site: https://help.ubuntu.com/community/CreateAuthenticatedRepository

**Comment by syuu1228** [comment]
Started to build Ubuntu 16.04 signed nightly build.
Can be test by following command on Ubuntu 16.04:
```
curl https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/scylladb.gpg.pubkey|sudo apt-key add -
cd /etc/apt/sources.list.d/
sudo curl -O https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/xenial/master/6/scylla.list
sudo apt update
sudo apt install scylla
```

**Comment by syuu1228** [comment]
15.10 as well

```
curl https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/scylladb.gpg.pubkey|sudo apt-key add -
cd /etc/apt/sources.list.d/
sudo curl -O https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/wily/master/2/scylla.list
sudo apt update
sudo apt install scylla
```

**Comment by syuu1228** [comment]
14.04 too
```
curl https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/scylladb.gpg.pubkey|sudo apt-key add -
cd /etc/apt/sources.list.d/
sudo curl -O https://s3.amazonaws.com/downloads.scylladb.com/deb/unstable/ubuntu/master/10/scylla.list
sudo apt update
sudo apt install scylla
```

**Comment by tzach** [comment]
@syuu1228 is it part of 1.2?

**Comment by tzach** [comment]
Confusing innocent users 
https://twitter.com/loweschmidt/status/797006359694872576

**Comment by burdandrei** [comment]
@tzach  @slivne  Guys, you need any help with it?

**Comment by avikivity** [comment]
A pointer to best practices maybe. Where to store the signing keys?

**Comment by burdandrei** [comment]
How do you guys build packages? 
I had jenkins job building and signing it.

**Comment by avikivity** [comment]
We have a Jenkins job, but I'm wary of giving it the keys.  It needs to be secure, or the signature is meaningless.

**Comment by burdandrei** [comment]
it's scary, but it's your build system =)
this worked to me: https://wiki.jenkins-ci.org/display/JENKINS/Debian+Package+Builder+Plugin

**Comment by avikivity** [comment]
Haha, I thought accepted practice might be to give your keys to some machine and hope.

I guess we'll have to do that.

**Comment by burdandrei** [comment]
@avikivity  great!
You do that and we'll do chef cookbook for you!
Any time estimations?

**Comment by caizixian** [comment]
+1 for CentOS/RHEL Packages.

**Comment by burdandrei** [comment]
hey @avikivity  how's going? 
just wanted to say that i remembered another great option for packages - Launchpad PPA!
What do you say? cause it's nightmare to install scylla with unsigned package.
Cheers!

**Comment by caizixian** [comment]
+1 for PPA

**Comment by tzach** [comment]
@avikivity @syuu1228 any progress on this?

**Comment by mdevan** [comment]
+1

[aptly](https://www.aptly.info) makes it easy to maintain and publish your repo. You can run it from RHEL/CentOS too.

With any tool/approach you'll need to gpg-sign files, so having a passphrase-protected GPG private key on a server is probably the best you can aim for.

Also, with recent Debian/Ubuntu versions, you'll need to use SHA-256 for the gpg signature, so add this to ~/.gnupg/gpg.conf:

```
cert-digest-algo SHA256
digest-algo SHA256
```

**Comment by syuu1228** [comment]
@slivne I already created signed package generation script on Jenkins years a go, can I enable it (perhaps only on 1.8?)

**Comment by syuu1228** [comment]
@slivne ping

**Comment by slivne** [comment]
@syuu1228 we need to make sure:
- we know how to promote these packages (previous simple attempt failed).
-  be able to rebuild them when we need to add minor versions fixes
- verify the key is good.

- I suggest we start with the non signed repo change and verify its good and then move and sign

**Comment by syuu1228** [comment]
On Wed, May 10, 2017 at 1:06 AM, Shlomi Livne <notifications@github.com>
wrote:

> @syuu1228 <https://github.com/syuu1228> we need to make sure:
>
>    -
>
>    we know how to promote these packages (previous simple attempt failed).
>    -
>
>    be able to rebuild them when we need to add minor versions fixes
>    -
>
>    verify the key is good.
>    -
>
>    I suggest we start with the non signed repo change and verify its good
>    and then move and sign
>
>
Does it means we will switch to aptly, but with non-signed repo?

Where can we start with, maybe test it on master?

**Comment by tchemineau** [comment]
I am currently trying to install scylladb on a fresh Debian 8, and have this message when installing via `apt-get`:

```
WARNING: The following packages cannot be authenticated!
  scylla-conf scylla-server scylla-jmx scylla-tools scylla-kernel-conf scylla
Install these packages without verification? [y/N]
```

Are your packages signed? Is there a way to retrieve the key to add it via `apt-key`?

**Comment by tzach** [comment]
@syuu1228 any update on this issue?

**Comment by tzach** [comment]
@syuu1228 ping

**Comment by crow50** [comment]
Still an issue.

**Comment by slivne** [comment]
In 2.1 the debian8 and ubuntu16.04 artifacts are signed - closing this issue
