### ISSUE TITLE
Add option to limit concurrent compactions (for HDDs)

### ISSUE THREAD

**Issue by horschi** [scylladb/scylla#8485]
As discussed on the mailing list: It would be nice if the number of concurrent compactions could be limited in scylla.

Perhaps the concurrent_compactors option from Cassandra can be used for this?

**Comment by raphaelsc** [comment]
More details can be found in: https://groups.google.com/g/scylladb-users/c/2dj4uQGo7jk

**Comment by raphaelsc** [comment]
The direction to solve this problem overlaps with https://github.com/scylladb/scylla/issues/6420, so I am closing this one as the latter has more details.
