### ISSUE TITLE
Decommission not fully utilizing hardware

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla#849]
Specification:
Scylla Servers: 3 x Rackspace OnMetal IO v1, Scylla 0.16
Keyspace: RF = 2

- Wrote 150M keys, each 10KB in size
- Each node has 1TB of data
- When decommission one of the 3 servers, network utilization was on only 1gbs instead of 10gbs available on the machine.
- Load on the cpu was very low, at around 5%
- Also disk were hardly utilized at 10% of full capacity.

**Comment by tzach** [comment]
> Load on the cpu was very low, at around 5%
> Also disk were hardly utilized at 10% of full capacity.

Is this only on the decommissioned node or on all nodes?
It make sense for streaming to be slow if other nodes are busy.

**Comment by tgrabiec** [comment]
@asias Could it be due to streaming's mutation_send_limiter limiting in-flight mutation could to only 10? If mutations are small, that's very low and we'd be limited by network latency.

**Comment by asias** [comment]
On Thu, Jan 28, 2016 at 6:27 PM, Tomasz Grabiec <notifications@github.com>
wrote:

> @asias <https://github.com/asias> Could it be due to streaming's
> mutation_send_limiter limiting in-flight mutation could to only 10? If
> mutations are small, that's very low and we'd be limited by network latency.
>

The idea behind the 10  stream_mutations per core limitation is to avoid
streaming overwhelm the tcp connection and starve normal cql verbs if the
streaming mutations are big and takes long time to complete.

@avikivity I think we can make the streaming use a standalone tcp
connection and increase the in-flight mutation.



> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/849#issuecomment-176111368>.
>



-- 
Asias

**Comment by slivne** [comment]
Decommission was running without traffic. So the cluster was only doing
decommission
בתאריך 28 בינו' 2016 12:27,‏ "Tomasz Grabiec" <notifications@github.com>
כתב:

**Comment by avikivity** [comment]
@asias agree.  When we have rpc-domains we can also support a separate SLA for streaming.

**Comment by slivne** [comment]
So currently, are we postponing this post GA - till we have a way to limit
streaming ?

**Comment by asias** [comment]
The change should be trivial. We can get it for GA.

On Sun, Jan 31, 2016 at 6:39 PM, slivne <notifications@github.com> wrote:

> So currently, are we postponing this post GA - till we have a way to limit
> streaming ?
>
> On Sun, Jan 31, 2016 at 12:33 PM, Avi Kivity <notifications@github.com>
> wrote:
>
> > @asias <https://github.com/asias> agree. When we have rpc-domains we can
> > also support a separate SLA for streaming.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/scylladb/scylla/issues/849#issuecomment-177460868>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/849#issuecomment-177462339>.
>



-- 
Asias

**Comment by dorlaor** [comment]
@noamha, should be nice to retest, I bet origin will be much slower
