### ISSUE TITLE
reader_concurrency_semaphore: readmission leaks resources

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#8493]
This is yet another case (after https://github.com/scylladb/scylla/issues/8258) of a bad interaction with 4c8ab10, this time its badly interacting with 70fa543. The result of this bad interaction is that when readmitting a previously admitted read (because it was evicted), all resources that it owns at that point are leaked.

**Comment by slivne** [comment]
@denesb which versions are suspect to this ?

**Comment by avikivity** [comment]
@denesb please check which release streams are vulnerable

**Comment by avikivity** [comment]
@penberg why didn't the promoter mark it closed? Is it confused by "Fixes:" vs "Fixes"?

**Comment by avikivity** [comment]
Or maybe, it didn't get merged at all.

**Comment by avikivity** [comment]
(i.e. dequeued)

**Comment by denesb** [comment]
The affected branches are 4.3 and 4.4.

**Comment by denesb** [comment]
It was dequeued on the 21st by @psarna because the unit test added by the fix failed on the build machines. I force pushed a fix and he said he'll re-queue soon

**Comment by psarna** [comment]
I'm requeueing, just waiting for a recompilation to finish, since there was a minor conflict.

**Comment by psarna** [comment]
done

**Comment by avikivity** [comment]
> The affected branches are 4.3 and 4.4.

And 4.5!

**Comment by psarna** [comment]
dequeued again - one of the tests failed to compile due to a (trivial) conflict

**Comment by slivne** [comment]
@psarna are you chasing this - do you need botond to send a new version - lets make it clear when we dequeue

**Comment by denesb** [comment]
I need to rebase on top of @bhalevy's close flat mutation readers series, with which I now have conflicts with. I'm working on it.

**Comment by denesb** [comment]
I will send a new version because I found and fixed a bug in the close readers code.

**Comment by denesb** [comment]
New version on the list: [PATCH v2 0/5] reader_permit: always forward resources to the semaphore

**Comment by avikivity** [comment]
@denesb can the call to close_reader() be dropped when backporting to 4.5 and below?

**Comment by denesb** [comment]
Yes, you furthermore have to drop all the deferred semaphore drops from the unit tests, but that should be it.

**Comment by avikivity** [comment]
Apparently not enough, please provide a backport to 4.5.

**Comment by denesb** [comment]
An additional backport is needed. Good thing I wrote a deadlock detector test which found out that we'd deadlock with just this series.

**Comment by denesb** [comment]
@avikivity: https://github.com/scylladb/scylla/pull/8558

**Comment by denesb** [comment]
Hold on backporting because I think this might be the cause for multishard query test timing out.

**Comment by denesb** [comment]
Turned out to be a test-only issue, fix on the list: [PATCH v1] test: multishard_mutation_query_test: fuzzy-test: don't consume resource up-front

**Comment by avikivity** [comment]
How far back should I backport d600be211b922d1df76204021903da9d14dc954b?

**Comment by denesb** [comment]
It has to be ported everywhere https://github.com/scylladb/scylla/pull/8558 is. I can include it in the latter to make it easier.

**Comment by avikivity** [comment]
@denesb I'll need help with 4.4 too.

**Comment by denesb** [comment]
> @denesb I'll need help with 4.4 too.

Here you go: https://github.com/scylladb/scylla/pull/8571
