### ISSUE TITLE
nodetool stuck while running another operation

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla#850]
Scylla version 0.16

I started running nodetool removenode on a node, while the command is till running I've opened another ssh console and tried running nodetool status, the second command was stuck and even after 20 minutes didn't return any feed back.

**Comment by tzach** [comment]
@noamha can you reproduce on Cassandra?
Trying to understand if the problem is in nodetool or the DB.

If the second, could it be scylla-jmx problem, not scylla? @amnonh ?

**Comment by amnonh** [comment]
After further investigation, the problem is because the call to
 service::get_local_storage_service().get_load_map while removenode is running stuck.

probably because it uses run_with_read_api_lock

To reproduce create a cluster with multiple nodes, kill a node and remove it with nodetool removenode.

While the removenode is running call:
curl -X GET "http://localhost:10000/storage_service/load_map"

**Comment by amnonh** [comment]
See my comment.

The problem is with locks in scylla.
@slivne should decide who should handle it.

**Comment by tzach** [comment]
@amnonh what are the affects of run_with_read_api_lock?
does it limit the nodetool for one parallel operation?

**Comment by amnonh** [comment]
On Sun, Feb 28, 2016 at 12:55 PM, Tzach Livyatan <notifications@github.com>
wrote:

> @amnonh <https://github.com/amnonh> what are the affects of
> run_with_read_api_lock?
> does it limit the nodetool for one parallel operation?
>
I'm not sure what the root cause, I didn't fully checked it, I just note
what API calls are involved.

**Comment by slivne** [comment]
@asias I think you added the function run_with_* - is there a limitation in origin on storage_service to limit the operations  - I tried to check cassandra code - in rebuild there is a limitation but others do not seem to have such a limitation.

In some cases the operations maybe very short so ordering them may be suboptimal but something we can get by (at least for now) but others are long.

**Comment by asias** [comment]
The api lock is introduce to serialize nodetool management operations. For this storage_service::get_load_map() which used by nodetool status, we should not block it while an operations which might take a long time to complete, e.g. decommission, removenode. It is safe to call get_load_map() even if operations are in-flight. 

@slivne C* does not have such api lock.

**Comment by slivne** [comment]
@asias

Why do we need to serialize the commands if in Cassandra there is no such
need ?

Did we have a bug that forced us to introduce this ?

My concern is that we are serializing api commands while many should run in
parallel - or can run in parallel - is there a real need to serialize ?


   - All the stats commands (cfstats, cfhistogram, netstats, status, ring,
   info, etc.) should probably run in parallel to anything.


   - There are some enable/disable commands for example that may run in
   parallel I guess


   - Some other examples - repair is a command that is run in many cases in
   the background - I am not sure it should block many commands (flush,
   compact, stats).

**Comment by avikivity** [comment]
We need locking because our state is distributed across multiple shards.

For long running operations, separate start/poll into separate operations (each running under lock).

**Comment by asias** [comment]
@avikivity Let's take decommission for example. 

"nodetool decommission" takes a long time to complete, when the cmd returns the decommission completes, and this is what user expects (though, I think this is a bad cmd operation design)

The current http api returns only when decommission completes. 

So what you suggested is we introduce another http api 

1) starts the decommission 
2) poll the status of the decommission

In scylla-jmx we use 1) and 2) to emulate the old nodetool decommission behavior.

**Comment by avikivity** [comment]
Right, this is what I suggest.

**Comment by avikivity** [comment]
We could also do this with the existing API; just limit the scope of the lock to when the operation is started, and add extra checks to prevent related operations from happening in parallel.

**Comment by avikivity** [comment]
(we would need the extra checks in any case, because the lock no longer protects us)

**Comment by asias** [comment]
@avikivity "We need locking because our state is distributed across multiple shards". The state is on cpu-zero only.  We replicate some of the states to other cores. The lock is mainly for making two operations not happen at the same time, e.g, admin issues drain() then issue decommission()

**Comment by asias** [comment]
I think we can do something like this: Before we do some time consuming operation, we set a flag. When admin issue another operation, we abort the second operation immediately, saying "xxx operation is in progress, try later".

**Comment by avikivity** [comment]
Right, but note, those flags can quickly become very complicated, because with N operation types, you have O(N^2) choices to make whether operation type I can run in parallel with operation type J.

**Comment by asias** [comment]
On 2/29/16 21:03, Avi Kivity wrote:
>
> Right, but note, those flags can quickly become very complicated, 
> because with N operation types, you have O(N^2) choices to make 
> whether operation type I can run in parallel with operation type J.
>

I would start with coarse control

1) converting the run_with_write_api_lock operations:

     join_ring, start_gossiping, stop_gossiping, start_rpc_server, 
stop_rpc_server, start_native_transport, stop_native_transport, 
decommission, remove_node, drain, move, rebuild

to something like below:

    sstring _current_operation;

    some_operation() {

        if (!_current_opearation.empty()) {
             throw std::runtime_error(sprint("%s operation is in
        progress, please retry later", _current_operation));
        }
        _current_opearation = sstring("some_operation")

        do some operation

        _current_opearation = sstring("");

    }

2) converting the run_with_read_api_lock to use no lock.






> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/scylladb/scylla/issues/850#issuecomment-190201596>.
>

-- 
asias

**Comment by avikivity** [comment]
On 02/29/2016 03:29 PM, Asias He wrote:
>
>
> On 2/29/16 21:03, Avi Kivity wrote:
> >
> > Right, but note, those flags can quickly become very complicated,
> > because with N operation types, you have O(N^2) choices to make
> > whether operation type I can run in parallel with operation type J.
> >
>
> I would start with coarse control
>
> 1) converting the run_with_write_api_lock operations:
>
> join_ring, start_gossiping, stop_gossiping, start_rpc_server,
> stop_rpc_server, start_native_transport, stop_native_transport,
> decommission, remove_node, drain, move, rebuild
>
> to something like below:
>
> sstring _current_operation;
>
> some_operation() {
>
> if (!_current_opearation.empty()) {
> throw std::runtime_error(sprint("%s operation is in
> progress, please retry later", _current_operation));
> }
> _current_opearation = sstring("some_operation")
>
> do some operation
>
> _current_opearation = sstring("");
>
> }
>

This is equivalent to converting it from lock to try_lock.

We will need to add support for waiting until an operation is complete, 
so an admin can script nodetool operations.


> 2) converting the run_with_read_api_lock to use no lock.

If you audit that it is safe, sure.

**Comment by asias** [comment]
On 2/29/16 21:49, Avi Kivity wrote:
>
>
> On 02/29/2016 03:29 PM, Asias He wrote:
> >
> >
> > On 2/29/16 21:03, Avi Kivity wrote:
> > >
> > > Right, but note, those flags can quickly become very complicated,
> > > because with N operation types, you have O(N^2) choices to make
> > > whether operation type I can run in parallel with operation type J.
> > >
> >
> > I would start with coarse control
> >
> > 1) converting the run_with_write_api_lock operations:
> >
> > join_ring, start_gossiping, stop_gossiping, start_rpc_server,
> > stop_rpc_server, start_native_transport, stop_native_transport,
> > decommission, remove_node, drain, move, rebuild
> >
> > to something like below:
> >
> > sstring _current_operation;
> >
> > some_operation() {
> >
> > if (!_current_opearation.empty()) {
> > throw std::runtime_error(sprint("%s operation is in
> > progress, please retry later", _current_operation));
> > }
> > _current_opearation = sstring("some_operation")
> >
> > do some operation
> >
> > _current_opearation = sstring("");
> >
> > }
> >
>
> This is equivalent to converting it from lock to try_lock.

But we need to remember which operation is in progress anyway. IMO, It 
is better to eliminate the lock completely.
>
> We will need to add support for waiting until an operation is complete,
> so an admin can script nodetool operations.

If the node operation does not return "try again", it will return after 
the operation is done.

Admin can script
do
ret = nodetool foo
while (ret == "try again")

>
>
> > 2) converting the run_with_read_api_lock to use no lock.
>
> If you audit that it is safe, sure.
>
> >
> >
> >
> >
> >
> >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > 
> <https://github.com/scylladb/scylla/issues/850#issuecomment-190201596>.
> > >
> >
> > --
> > asias
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/scylladb/scylla/issues/850#issuecomment-190211502>.
> >
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/scylladb/scylla/issues/850#issuecomment-190218805>.
>

-- 
asias
