### ISSUE TITLE
Requesting scylladb on civo's opensource marketplace

### ISSUE THREAD

**Issue by DoNnMyTh** [scylladb/scylla#8502]
As our customer requested for scylla on my marketplace, Can I reach out a maintainer who is willing to submit application to out one click marketplace. I'll help you all along the way.

we only allow the maintainers to maintain and make changes to app that they have submitted. as we have strict rules around it. even if someone else want to make a change with a PR he needs approval of the maintainers.

https://github.com/civo/kubernetes-marketplace is link for our marketplace.

it's super simple to submit app either you can use app.yaml or install.sh

https://github.com/civo/kubernetes-marketplace/blob/master/falco/install.sh

this is a example of app with install.sh

**Comment by nyh** [comment]
Hi,
We have a separate repository, https://github.com/scylladb/scylla-operator, for Scylla's Kubernetes operator. That other repository is where all of Scylla's Kubernetes experts like @zimnx hang out. I suggest that you close this issue in this repository (which is Scylla's core software) and instead open an issue on that Kubernetes-specific repository.

**Comment by DoNnMyTh** [comment]
Thank you so much @nyh
