### ISSUE TITLE
bootstrap_with_repair badly formatted exception: expected 1 node losing range but found more nodes={}

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8503]
As seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/3414/artifact/logs-gating.release.2/1618586526989_replace_address_test.TestReplaceAddress_rbo_enabled.replace_active_node_test/node2.log
```
ERROR 2021-04-16 15:22:05,952 [shard 0] init - Startup failed: std::runtime_error (bootstrap_with_repair: keyspace=system_distributed_everywhere, range=(9163005485582434440, 9188926636396914056], expected 1 node losing range but found more nodes={})
```

`nodes` is not formatted into the exception string.

Introduced in 9c67389cc8d77c6eb60234c96cc5ffbaae2771a6 (4.0)

**Comment by asias** [comment]
```

**Comment by bhalevy** [comment]
> The code logged the nodes correctly.

Would an empty nodes list be printed as `nodes={}`?

**Comment by asias** [comment]
> > The code logged the nodes correctly.
> 
> Would an empty nodes list be printed as `nodes={}`?

Yes, but what's wrong with this? This is how we print a container.

zero node:

nodes={}

1 node:

nodes={127.0.0.1}

2 nodes:
nodes={127.0.0.1, 127.0.0.2}

 What do you think  is best to print in this case?

**Comment by bhalevy** [comment]
> > > The code logged the nodes correctly.
> > 
> > 
> > Would an empty nodes list be printed as `nodes={}`?
> 
> Yes, but what's wrong with this? This is how we print a container.
> 
> zero node:
> 
> nodes={}
> 
> 1 node:
> 
> nodes={127.0.0.1}
> 
> 2 nodes:
> nodes={127.0.0.1, 127.0.0.2}
> 
> What do you think is best to print in this case?

It's ok, just got me confused.
It would help if you also print `nodes.size()` and then it would be clear to see something like:
```
bootstrap_with_repair: keyspace=system_distributed_everywhere, range=(9163005485582434440, 9188926636396914056], expected 1 node losing range but found 0 nodes ({})
```
