### ISSUE TITLE
database::get_reader_concurrency_semaphore() uses system semaphore as the catch-all semaphore

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#8508]
We try to match the current scheduling group first to the statement group, then to the streaming group and fall back to the system one if that fails. This means that the system semaphore is used as a catch-all for all scheduling groups that this method doesn't know about. This is incompatible with the recent forward-porting of the service-level infrastructure as it means that all service level related scheduling groups will fall back to the system scheduling group, which causes two problems:
* They will experience much limited concurrency, as the system semaphore is assigned much less count units, to match the much more limited internal traffic.
* They compete with internal reads, severely impacting the respective internal processes, potentially causing extreme slowdown, or even deadlock in the case of an internal query executed on behalf of a user query being blocked on the latter.

Even if we don't have any custom service level scheduling groups at the moment, it is better to change this such that unknown scheduling groups fall-back to using the user semaphore. We don't expect any new internal scheduling group to pop up any time soon (and if they do we can adjust `get_reader_concurrency_semaphore()` accordingly), but we *do* expect user scheduling groups to be created, even dynamically.

**Comment by avikivity** [comment]
This was just building for the future, not fixing a bug. So not backporting.
