### ISSUE TITLE
Trouble joining/bootstrapping a new node to replace a dead seed node

### ISSUE THREAD

**Issue by veramine** [scylladb/scylla#8516]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.1.9-0.20201026.b80dab6d58
Cluster size: 2
OS (RHEL/CentOS/Ubuntu/AWS AMI):  CentOS 7

*Hardware details (for performance issues)*        
Platform (physical/VM/cloud instance type/docker): AWS i3en.xlarge

I have a two node cluster with 1.5TB data RF=2 running on two i3en.xlarge AWS instances.  This has been running for months.  One node was seed and the other was not in the seed node list.  The seed node died.  AWS shut it down and told me it was dead. No problem because I have RF=2.  I changed the working node scylla.yaml to point to itself as seed node and did not restart the working node.  It is still serving all requests.

I have twice attempted to add an additional node to the cluster to replace teh busted node.  I have had a lot of trouble.  

FIRST ATTEMPT:

I installed the same version of scylla on a new i3en.xlarge instance and pointed to the working node as seed and used the replace_address_first_boot trick.  It started bootstrapping and copying all data.  It ran for a couple days before scylla exhausted system memory and there was no swap configured and scylla had locked memory so the instance was inaccessible.  I had to reboot from AWS.  I then set --reserve-memory 2G and it ran again for two days before dying again in same way.  I then set --reserve-memory 8G and removed the lock memory flag and it ran for two more days before it shut itself down with this error:

Apr 19 20:27:23 ip-172-31-26-40.us-west-2.compute.internal scylla[11084]:  [shard 0] init - Startup failed: std::runtime_error (Cannot replace token -9104640237226732752 which does not exist!)

I tried wiping out the data directory and commitlog but got back to the same state.

SECOND ATTEMPT:

I thought maybe there was some confused state with that instance so I spun up another new instance the same way and when I start up that node in teh same way I get this error on the working node:

Apr 19 20:55:46 scylla2 scylla[17075]:  [shard 0] rpc - client 172.31.24.20:7000: unknown verb exception 6 ignored

172.31.24.20 in this case is the second attempt new node.  This error comes before data copying begins.

All these instances are still up so I would be happy to provide any logs from any of them.  But if there is something obvious I can do to make this work, let me know.  I am hesitant to restart the working node because it is important to us that requests from this cluster continue to be serviced.  Thanks!

**Comment by avikivity** [comment]
@asias please help

**Comment by asias** [comment]
Run nodetool gossipinfo and nodetool status on the working node, so we can know what is the status of the cluster. 

Try scylla-4.4.1 which has the fix for "shard 0] init - Startup failed: std::runtime_error (Cannot replace token -9104640237226732752 which does not exist!)".


It is best that you can find a window to rolling restart the working node to 4.4.1.

So, we can try this:
1) use 4.4.1 for second node, with replace_address_first_boot to replace the dead node

2) if 1) does not not, upgrade the second node then try replace.

**Comment by veramine** [comment]
Okay I upgraded the new node to 4.4.1.  This is the node that has not yet joined the cluster.  This is the node where I am using the replace_address_first_boot.  So far so good.  The working node is streaming data to it.  I had been cautious to use the same version but this seems so far to be working fine.  After this new node comes fully online and is able to service requests as the second node in RF=2, then I will upgrade the working node (the seed) to 4.4.1.  It will be great to no longer worry about seeds.  Thanks!!

**Comment by veramine** [comment]
Everything looking good so far.  1.5TB streamed so far overnight.  No errors yet. 🤞

**Comment by veramine** [comment]
The 4.4.1 node finished streaming all the data and successfully joined the cluster.  The AWS instance itself subsequently became unreachable.  I'm not sure why.  I suspect resource consumption but not sure.  I rebooted the instance via the AWS console and when the node restarted the "reshaping" feature kicked in and now the new node seems to be reshaping all the data.  This might be the cost of taking 4.1.9 data and upgrading straight to 4.4.1.  Not sure how long this will go.  I'll let you know if/when it finishes.

**Comment by veramine** [comment]
I ended up migrating to a two node cluster both nodes running 4.4.1.  replace_address_first_boot  worked fine.  Thanks for the help!
