### ISSUE TITLE
[Packaging fail]how can i build RPM package for scylla 4.4.0?

### ISSUE THREAD

**Issue by edisonqkj** [scylladb/scylla#8520]
Hi @avikivity ,
I have built scylla 4.4.0 from sources and tested it in debug mode in docker-based environment. Now, i want to package scylla in rpm to distribute it into CentOS servers.
However, I found **reloc/build_reloc.sh** was missing which scylla 3.1.2 had. Also, this link (https://github.com/scylladb/scylla/blob/scylla-4.4.0/docs/building.md) returned 404. 
Finally, i tried the methods mentioned in this link(https://scylla.docs.scylladb.com/master/guides/building.html#packaging) using following commands in **Packaging** section but errors returned
```
bash-5.0# ./tools/toolchain/dbuild ninja dist
./tools/toolchain/dbuild: line 12: die: command not found
./tools/toolchain/dbuild: line 136: --help: command not found
./tools/toolchain/dbuild: line 206: run: command not found
./tools/toolchain/dbuild: line 217: logs: command not found
```
Any help to build RPM package for scylla 4.4.0? thanks!

**Comment by avikivity** [comment]
You need docker or podman installed to run dbuild.
