### ISSUE TITLE
Alternator should stream JSON response object - not convert it to a contiguous string

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8522]
This is a spinoff from https://github.com/scylladb/scylla/issues/7926#issuecomment-823222738 and #8515:

Currently, Alternator's request handlers return the response as a JSON-formatted string. As noticed in issue #8515, this string can be very big, it requires a contiguous allocation - and worse - the rapidjson implementation crashes if it can't allocate the big contiguous allocation.

So instead of returning a string response, Alternator should write its response to an output stream.

This should hopefully be fairly easy to fix. Alternator's requests already don't really return a string - they return a `request_return_type` which is basically Seastar's `json_return_type`. This struct has a member `sstring _res` where a full response can be stored, but alternatively also has a member std::function<future<>(output_stream<char>&&)> _body_writer which can be used to return a function that writes a non-continguous rapidjson `value` object to the stream. Alternator uses Seastar's jsonable utility class to build this` json_return_type`, and this class also also has both features, but I still need to figure out how to use it.

**Comment by nyh** [comment]
> This should hopefully be fairly easy to fix. Alternator's requests already don't really return a string - they return a `request_return_type` which is basically Seastar's `json_return_type`. This struct has a member `sstring _res` where a full response can be stored, but alternatively also has a member std::function<future<>(output_stream&&)> _body_writer which can be used to return a function that writes a non-continguous rapidjson `value` object to the stream.

It turns out to be significantly harder than I hoped. Actually the part described above - getting the HTTP server to take the response from an output stream instead of a contiguous string - was the easy part... The harder part was getting rapidjson use an output stream as its serialization output. Rapidjson does have an outputstream-like concept, but it's not _futurized_: there is no way for the driver serialization loop to wait until it can write to the stream. The easiest around this problem is to do the printing in a `seastar::thread`, so our handler can just use `get()` to wait. But I hesitate to force an `seastar::thread` on reading.

Perhaps the solution is to have a pool of `seastar::thread`s to do JSON serialization, like we have for JSON parsing. But unfortunately here it's less clear that we can do with only a few of those threads, however :-( In the worst case, we may need to write responses to 100 slow sockets, and it's not a great idea not to start writing to the 100th because there are 99 other serialization calls which couldn't finish because of their slow output socket.

 Alternator uses Seastar's jsonable utility class to build this` json_return_type`, and this class also also has both features, but I still need to figure out how to use it.

**Comment by psarna** [comment]
One important thing with the threaded solution we have for parsing jsons is that they are only used for requests larger than a threshold. If a threshold is well balanced, small requests should be able to be executed without the additional queueing, and at the same time not cause reactor stalls, because they're small.

On the other hand - perhaps we should reconsider forking rapidjson (or just copying the whole code to scylla, especially that it's header-only) and rewriting the interesting parts with future<>s. We managed to hack our way through so far, but perhaps it's better to just rewrite some parts of rapidjson instead of trying to hack one more aspect of it. E.g. if we just rewrite rapidjson parsing to future<>s, we can also get rid of these parsing threads altogether. Now that we have coroutines, the rewriting part might actually be very simple and boil down to changing some function declarations and sprinkling a couple of co_awaits in the right places.

/cc @avikivity

**Comment by nyh** [comment]
> On the other hand - perhaps we should reconsider forking rapidjson (or just copying the whole code to scylla, especially that it's header-only) and rewriting the interesting parts with future<>s. 

I started to think of perhaps doing this for the **printing** part won't be too hard. E.g., it's not that hard to print a JSON array by printing `[`, then the individual items separate by commas, and finally `]`.

However, to do this efficiently might not be very easy. It is probably inefficient to use a future-based `output_stream::write()` every tiny piece of the JSON object. The more efficient approach is perhaps to have a write buffer of some size (e.g., 4KB), and only when we reach the end of this buffer, use a future. We did something similar for sstable reads in the past, and writing is simpler because we don't have to handle buffer crossing (if the next item doesn't fit the buffer, just wait and don't write it).

**Comment by psarna** [comment]
I agree, it sounds like a good low-hanging fruit to take as a first step.

**Comment by nyh** [comment]
Created a test, `test_batch.py::test_batch_get_item_large`, to reproduce the oversized allocation warning from within the JSON writer:
```
      WARN ... seastar_memory - oversized allocation: 2281472 bytes.

```
Note that this is the second oversized allocation warning produced in this test - the first one is unrelated - it is due to #8183 and has a different stack trace.

**Comment by nyh** [comment]
> I agree, it sounds like a good low-hanging fruit to take as a first step.

Frustratingly, this fruit hangs higher than I had hoped :-( Seastar's HTTP server can only take an "sstring" (not anything similar -  an actual sstring) or a function, and while the former always has a known length and uses `Content-Length`, the latter always - unfortunately - assumes the length is not know and uses chunked encoding and a complex wrapper stream. What I would like to have - a function that knows its output's length and can write directly to the original stream - is not available.
That being said, maybe using chunked encoding is not a bad compromise. In the final implementation with real streaming, we will need it anyway. So perhaps we might as well use it now even though we do know the size.

**Comment by nyh** [comment]
https://github.com/scylladb/scylla/pull/9713 by @elcallio added a feature of writing a large JSON response without converting it to a contiguous string, but does not completely solve this issue because it is only used for Streams and Scan/Query - not for BatchGetItem that was the original motivation of this issue and tested by
```
test/alternator/run test_batch.py::test_batch_get_item_large
```
(the last "oversized allocation" comes from the serialization to a contiguous string - the first one comes from the unrelated #8183).

Note that BatchGetItem was more important to fix than Scan, because the former can return up to 16MB according to the DynamoDB documentation (and even more in Alternator - see #5944), while the latter is anyway limited to our page size of 1MB. 1MB is perhaps still a large allocation, but 16MB and more is worse.

So we still need to fix `BatchGetItem` to use the new streamed response API from https://github.com/scylladb/scylla/pull/9713 for large batched responses.

**Comment by elcallio** [comment]
BatchGetItem is tricky, since it creates a bunch of sub-json results. Either we assume each result is small enough (probably false...?), or we need to actually store all the query results and stream them individually once we have the full batch. Problem with that is of course that these could be clunky-big as well... Which approach is preferred?

**Comment by elcallio** [comment]
Otoh, it is _large_ allocs we care about, so each json tree should be ok as it is.

**Comment by nyh** [comment]
> Otoh, it is _large_ allocs we care about, so each json tree should be ok as it is.

Right - this issue is just about contiguous allocations. Each JSON in a BatchGetItem may indeed be pretty large, but the problem we're addressing here is the total size of the response - which can be up to 16MB (or even more in practice, because we never limited it - this is #5944). There's a separate issue on why do we even need to collect all these results in memory at the same time, but I'm not trying to solve this right now - just the **contiguous** allocation problem.

I'm working on this issue now.

**Comment by nyh** [comment]
@elcallio, I sent a patch to the mailing list titled "alternator: avoid large contigous allocation in BatchGetItem" to also use streamed output for large BatchGetItem - and then I think we can mark this issue fixed. Can you please review it? Thanks.

**Comment by psarna** [comment]
Hello - dequeued due to stack-use-after-return in debug mode, reported by Jenkins and investigated by @bhalevy

**Comment by bhalevy** [comment]
Apparently comes from the new `print` function

From https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4422/artifact/testlog/x86_64_debug/run.2.log:
```
Address 0x7faf894b0830 is located in stack of thread T0 at offset 48 in frame
    #0 0x1427c88f  (/jenkins/workspace/scylla-master/next/scylla/build/debug/scylla+0x1427c88f)

  This frame has 2 object(s):
    [32, 88) 'osb' (line 296) <== Memory access at offset 48 is inside this variable
    [128, 208) 'writer' (line 298)
```

```
+    os_buffer osb{ os };
+    using streamer = rapidjson::Writer<os_buffer, encoding, encoding, allocator>;
+    guarded_yieldable_json_handler<streamer, false, os_buffer> writer(osb, max_nested_level);
+    value.Accept(writer);
+    return std::move(osb).finish();
```

osb's life need to be extended post finish(), right?

**Comment by nyh** [comment]
Thanks @psarna and @bhalevy.
@elcallio https://jenkins.scylladb.com/job/scylla-master/job/next/4422/ shows that you can reproduce the failure in **debug** build mode, running
```
test/alternator/run test_batch.py::test_batch_write_item_large
```
Scylla will crash on an ASAN error during this test. 
Please note that although this test is named after BatchWriteItem, it actually ends in a Query (to check the success of the BatchWriteItem), and this is what you modifies in your patch and fails.

**Comment by nyh** [comment]
(note for posterity: the above three comments belong in https://github.com/scylladb/scylla/pull/9713, not here)

**Comment by elcallio** [comment]
Weird, I ran this in debug and got no errors. Will re-run. 
@bhalevy - no, not really. The future execution just needs to ensure all it touches is alive, i.e. kept alive by the execution itself, or by caller contract.

**Comment by nyh** [comment]
@elcallio I think Benny is right... you start `osb.finish()`, which doesn't do anything immediately (it sets to write the buffer when some previous future finishes), but then immediately destroy osb.  The fact that `finish()` execute doesn't hold the osb object alive.

**Comment by elcallio** [comment]
To quote/paraphrase the other PR/issue, the idea is that it does not need to. It should have loaded and kept alive anything it requires (i.e. buf + state). Out stream is callers responsibility.
