### ISSUE TITLE
NoHostAvailable system_distributed_everywhere.cdc_generation_descriptions_v2

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#8533]
Start one node in the clsuter
Do query after the node is up
```
cqlsh> CONSISTENCY ONE 
Consistency level set to ONE.
cqlsh> SELECT  * from system_distributed_everywhere.cdc_generation_descriptions_v2 ;
NoHostAvailable: 
```

Commit:

https://github.com/asias/scylla/tree/cdc_everywhere_v2

**Comment by kbr-** [comment]
What build? Some special node config parameters? How is Scylla started? I can't reproduce.

**Comment by asias** [comment]
> What build? Some special node config parameters? How is Scylla started? I can't reproduce.

https://github.com/asias/scylla/tree/cdc_everywhere_v2. No special config.

**Comment by kbr-** [comment]
I think we can continue on #8536 and close this issue.
