### ISSUE TITLE
[FileError]scylla_blocktune.py and scylla-blocktune are given the wrong names?

### ISSUE THREAD

**Issue by edisonqkj** [scylladb/scylla#8535]
Hi @avikivity,
I have built the unified packages with this shell(scylla_4.4.0/unified/build_unified.sh).
And installing on Centos7
````
sudo ./install.sh --housekeeping
sudo scylla_setup
````
When running **scylla_setup** steps, error as following occurred: 
![image](https://user-images.githubusercontent.com/5396193/115691621-cf17e580-a390-11eb-9771-a39868175c6d.png)

i checked /opt/scylladb/scripts/**scylla_blocktune.py** which was a shell rather than a python file.
![image](https://user-images.githubusercontent.com/5396193/115698495-42bcf100-a397-11eb-9132-b135b44cd3c4.png)

in the directory /opt/scylladb/scripts/, i found **scylla-blocktune** which was a python file.

![image](https://user-images.githubusercontent.com/5396193/115691748-ea82f080-a390-11eb-977a-e2f2cdb1b5d5.png)
![image](https://user-images.githubusercontent.com/5396193/115699357-2a010b00-a398-11eb-9afc-02c517378f31.png)

I think this is the reason to the above error that these two files(**scylla-blocktune/scylla_blocktune.py**) have been given the wrong names. Am i right?

**Comment by slivne** [comment]
there is a python called scylla-blocktune its located at ```./dist/common/scripts/scylla-blocktune```

it imports "./dist/common/scripts/scylla_blocktune.py" which actually does the tunning

I am not sure what's the issue you are facing - we did not have anyone report a problem with the packages we build

The "correct" way to build scylla is documented  https://github.com/scylladb/scylla/blob/branch-4.4/docs/guides/building.md 

Please note that AFAIK everyone uses the binaries we build.
