### ISSUE TITLE
Scylla-JMX service is not working on the latest master (reference commit 490201fd1)

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#854]
This problem was originally reported on the mailing list by @raphaelsc.

The symptom of this problem can be seen on the execution of `nodetool status`:

    22:05:44 process          L0275 INFO | Running '/bin/nodetool status'
    22:05:46 process          L0362 DEBUG| [stderr] error: Not found
    22:05:46 process          L0362 DEBUG| [stderr] -- StackTrace --
    22:05:46 process          L0362 DEBUG| [stderr] java.lang.RuntimeException: Not found
    22:05:46 process          L0362 DEBUG| [stderr] 	at com.scylladb.jmx.api.APIClient.getException(APIClient.java:115)
    22:05:46 process          L0362 DEBUG| [stderr] 	at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:158)
    22:05:46 process          L0362 DEBUG| [stderr] 	at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:169)
    22:05:46 process          L0362 DEBUG| [stderr] 	at com.scylladb.jmx.api.APIClient.getReader(APIClient.java:196)
    22:05:46 process          L0362 DEBUG| [stderr] 	at com.scylladb.jmx.api.APIClient.getListStrValue(APIClient.java:228)
    22:05:46 process          L0362 DEBUG| [stderr] 	at com.scylladb.jmx.api.APIClient.getListStrValue(APIClient.java:240)
    22:05:46 process          L0362 DEBUG| [stderr] 	at org.apache.cassandra.service.StorageService.getLiveNodes(StorageService.java:107)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    22:05:46 process          L0362 DEBUG| [stderr] 	at java.lang.reflect.Method.invoke(Method.java:497)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.reflect.misc.Trampoline.invoke(MethodUtil.java:71)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    22:05:46 process          L0362 DEBUG| [stderr] 	at java.lang.reflect.Method.invoke(Method.java:497)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.reflect.misc.MethodUtil.invoke(MethodUtil.java:275)
    22:05:46 process          L0362 DEBUG| [stderr] 	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:112)
    22:05:46 process          L0362 DEBUG| [stderr] 	at com.sun.jmx.mbeanserver.StandardMBeanIntrospector.invokeM2(StandardMBeanIntrospector.java:46)
    22:05:46 process          L0362 DEBUG| [stderr] 	at com.sun.jmx.mbeanserver.MBeanIntrospector.invokeM(MBeanIntrospector.java:237)
    22:05:46 process          L0362 DEBUG| [stderr] 	at com.sun.jmx.mbeanserver.PerInterface.getAttribute(PerInterface.java:83)
    22:05:46 process          L0362 DEBUG| [stderr] 	at com.sun.jmx.mbeanserver.MBeanSupport.getAttribute(MBeanSupport.java:206)
    22:05:46 process          L0362 DEBUG| [stderr] 	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:647)
    22:05:46 process          L0362 DEBUG| [stderr] 	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
    22:05:46 process          L0362 DEBUG| [stderr] 	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1445)
    22:05:46 process          L0362 DEBUG| [stderr] 	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
    22:05:46 process          L0362 DEBUG| [stderr] 	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
    22:05:46 process          L0362 DEBUG| [stderr] 	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
    22:05:46 process          L0362 DEBUG| [stderr] 	at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:639)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    22:05:46 process          L0362 DEBUG| [stderr] 	at java.lang.reflect.Method.invoke(Method.java:497)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.rmi.transport.Transport$1.run(Transport.java:200)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.rmi.transport.Transport$1.run(Transport.java:197)
    22:05:46 process          L0362 DEBUG| [stderr] 	at java.security.AccessController.doPrivileged(Native Method)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$93(TCPTransport.java:683)
    22:05:46 process          L0362 DEBUG| [stderr] 	at java.security.AccessController.doPrivileged(Native Method)
    22:05:46 process          L0362 DEBUG| [stderr] 	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
    22:05:46 process          L0362 DEBUG| [stderr] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    22:05:46 process          L0362 DEBUG| [stderr] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    22:05:46 process          L0362 DEBUG| [stderr] 	at java.lang.Thread.run(Thread.java:745)
    22:05:46 process          L0362 DEBUG| [stderr] 

Scylla-JMX logs show:

    22:05:46 process          L0275 INFO | Running '/bin/journalctl --unit scylla-jmx.service'
    22:05:46 process          L0362 DEBUG| [stdout] -- Logs begin at Wed 2015-12-30 00:13:04 EST, end at Tue 2016-01-26 22:05:46 EST. --
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:44 localhost.localdomain systemd[1]: Started Scylla JMX.
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:44 localhost.localdomain systemd[1]: Starting Scylla JMX...
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:45 localhost.localdomain scylla-jmx[11538]: Using config file: /etc/scylla/scylla.yaml
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:45 localhost.localdomain scylla-jmx[11538]: Connecting to http://127.0.0.1:10000
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:45 localhost.localdomain scylla-jmx[11538]: Starting the JMX server
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:46 localhost.localdomain scylla-jmx[11538]: Exception in thread "Dropped messages" java.lang.RuntimeException: Not found
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:46 localhost.localdomain scylla-jmx[11538]: at com.scylladb.jmx.api.APIClient.getException(APIClient.java:115)
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:46 localhost.localdomain scylla-jmx[11538]: at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:158)
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:46 localhost.localdomain scylla-jmx[11538]: at com.scylladb.jmx.api.APIClient.getRawValue(APIClient.java:169)
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:46 localhost.localdomain scylla-jmx[11538]: at com.scylladb.jmx.api.APIClient.getReader(APIClient.java:196)
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:46 localhost.localdomain scylla-jmx[11538]: at com.scylladb.jmx.api.APIClient.getJsonArray(APIClient.java:600)
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:46 localhost.localdomain scylla-jmx[11538]: at com.scylladb.jmx.api.APIClient.getJsonArray(APIClient.java:607)
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:46 localhost.localdomain scylla-jmx[11538]: at org.apache.cassandra.net.MessagingService.getDroppedMessages(MessagingService.java:190)
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:46 localhost.localdomain scylla-jmx[11538]: at org.apache.cassandra.net.MessagingService$CheckDroppedMessages.run(MessagingService.java:129)
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:46 localhost.localdomain scylla-jmx[11538]: at java.util.TimerThread.mainLoop(Timer.java:555)
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:46 localhost.localdomain scylla-jmx[11538]: at java.util.TimerThread.run(Timer.java:505)

Scylla Server logs:

    22:05:46 process          L0362 DEBUG| [stdout] -- Logs begin at Wed 2015-12-30 00:13:04 EST, end at Tue 2016-01-26 22:05:46 EST. --
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:35 localhost.localdomain systemd[1]: Starting Scylla Server...
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:35 localhost.localdomain sudo[11524]:   scylla : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/lib/scylla/scylla_prepare
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:35 localhost.localdomain scylla_run[11526]: EAL: Detected lcore 0 as core 0 on socket 0
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:35 localhost.localdomain scylla_run[11526]: EAL: Support maximum 128 logical core(s) by configuration.
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:35 localhost.localdomain scylla_run[11526]: EAL: Detected 1 lcore(s)
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:35 localhost.localdomain scylla_run[11526]: EAL: VFIO modules not all loaded, skip VFIO support...
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:35 localhost.localdomain scylla_run[11526]: EAL: Setting up physically contiguous memory...
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla[11526]: EAL: TSC frequency is ~3392144 KHz
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla[11526]: EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla[11526]: EAL: Master lcore 0 is ready (tid=b47d85c0;cpuset=[0])
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla_run[11526]: EAL: TSC frequency is ~3392144 KHz
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla_run[11526]: EAL: WARNING: cpu flags constant_tsc=yes nonstop_tsc=no -> using unreliable clock cycles !
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla_run[11526]: EAL: Master lcore 0 is ready (tid=b47d85c0;cpuset=[0])
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla_run[11526]: Scylla version 666.development-20160127.490201f starting ...
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla[11526]:  [shard 0] config - Option partitioner is not (yet) used.
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla[11526]:  [shard 0] database - Row: max_vector_size: 32, internal_count: 5
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla_run[11526]: Scylla API server listening on 127.0.0.1:10000 ...
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla[11526]:  [shard 0] database - Populating Keyspace system
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla[11526]:  [shard 0] storage_service - Loading persisted ring state
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla[11526]:  [shard 0] storage_service - Starting up server gossip
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla[11526]:  [shard 0] storage_service - This node will not auto bootstrap because it is configured to be a seed node.
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla[11526]:  [shard 0] storage_service - Generated random tokens. tokens are {-694821471637465540, 1290671014729458243, -3637176138636539098, -1757342749048871134, -7650671591515797069, 271479042205717763, 7848134685534106431, 5285463643494845217, -8136209495276306391, 4602945908480753088, 4256829186641174575, -9012195339952973261, -4406941841302799127, 4246725783276811422, 8343758009490185484, -4822664640624555071, 2780957782226179507, 8336919328657194082, -4472086250368550331, -1065412981261305997, -6087918980313499705, -1214484353755997933, 7333476654154114337, 3253661065776026780, -8402481757275871459, 2035834795437121469, -3033354646510184963, -7908284377915669342, -3601524497911393391, 4737434071405829608, 3890902898411715208, 3450024766264590750, 2024426025332316424, 4019657915884555596, -1459800393646202414, 7428306535366103734, -2957712434884374891, 7529005211043943460, 8407556970867023198, 4724575362682586258, 6734066967631168221, -2601393492447088430, 5738505192438495703, -6251268381088397616, 2728753811455911927, 5912838503976043980, -8370237123872111471, -948600720618444981, -6140442451906163719, 472783479806797717, -7726126530364603276, -4671930737704080095, 1746783351881071409, -6868492612522771303, 1937526912686253820, -4664324946086721692, 1301690022092011988, -7454488285360302811, 4628738269398065389, 7930015862721368607, -4702890431391707127, 2162797204086722895, -8385957102069104203, 5291155176830786761, -6112526213040716777, 1707319294403988125, -9210235989185378519, -7280410092581570028, -8250574129392723491, -2766218724253403273, -6688906532056869336, 8343157926996068723, -748135642159472307, -7321232491340269808, -5679011046044711394, -4852479078763031338, -2475605861035381966, -5722956640612412060, 9069871577820665009, -8015369975493671513, -8288681516343542713, 660673882247441727, 8989040339374930387, 52736877302714048, 6627143480567378920, -3946866504667500830, 3721321887264416718, -8175995825998887738, 8521593084659124458, 8478044930147777761, 1459987041500843351, -4502784125095931703, 2410606923650602683, 4914847405403271659, -5090555153738079578, 3809569840650091746, -3140363700729540855, 6937060135163574621, -4678234720989247227, -4108689674722850352, 4907101650443888981, 531200626805543712, -7792865954589395653, -4190746940504773975, -5783898112116331284, -4674207517684485143, -5593560038051700233, 5550767696325106199, 1126683052547326717, -301453619452705345, 4954079466258900094, -4878679956544034181, 3288943460978265955, -9083924616773142185, -2379687033883603111, -7755672011251328111, -4983742578630169562, 6803538605142486492, 5702292585939984630, -2270671582875894395, -5577912338277470928, 4784462057126423707, -3040780846959643076, -3515496561774149715, -125772581728279751, -3738629220486065877, 4576674807434937145, 7132210147853535722, 4679331552550952190, -4533590223108642010, 7100168698057669488, -7181692627806787148, -3917825237559669930, -5622550158141242032, 4997160374064150798, 301793643937216801, 4064598460297201104, 3538500421270814627, 657509712129797601, -7239265493592404393, -7908743960192631772, 965795840499444515, -415271624508781307, 8165529903083305744, 5719484980642657218, 822686371647760435, -3875391088170881942, 5729037511485784105, 8586099140625169182, 2694449920540148520, 8416377779585748071, -5088533967114090137, 820350266967324456, 4906480692097868607, 1032021591205864298, 7806377174883084201, -6250157820556565519, -4667467802262386599, 4331599017010428392, 6675382959341112922, 4064002187468887965, 7945906837789431917, -7087750074454506886, 3394769669800541770, -8683572957822277301, 1505591721903634057, 7536603140662143430, 5132842100561068317, -475659253498320960, -1269363410005707089, 6720414920700542187, 3036762435522021275, 6440548280747515947, 8871547778506014442, -4980140172390049020, -4892281547951516980, 2267552482350509469, 6789811382810985934, -7192761036269761705, 4907079389454193183, 4251347363166986646, -5366576026257133151, 6487980473298408224, -7053759375004825805, 2111436707069430543, -7291745723115946799, 1450271300623288464, -1267670642773512197, -3315153414095897475, 254657791416368965, 6347909032535242697, -3865844162303937385, 2601819489964752094, 5213308607529815, -1691419757251349809, -4956813885028105518, -2362009791561138548, 6575338861128885285, 2072441760328836456, -5125657828922391283, 2619820738565580291, 4709608351831977069, -2520658288074128321, 6918047572764349722, 6484785647611780717, 4156781837113277902, 3681783710956698592, 3342305177160302142, 5856399335892156260, 5019843306797849589, -2765767079138098325, -7472212590155211675, -5156015966930573990, -62198624711405112, -1002247077248040859, -1189045823603357337, 6881020393573959895, -8341754619202197965, 8085780616168385159, 8847676539281583595, -75353686349678815, -1784557979341394868, 427433312567711565, 5102686514795612570, -7447264714463604772, -2800343455648857443, 2335673801641903652, 645892713938551511, -4627026217611533662, -8966486606710733346, -142806001267400849, 2185075474720027472, -6499655866321686589, 3211470294761111347, 1689925129148736663, 7825749782913291786, -4608699824557084934, 4392715776091306482, -8869820694216328521, -1200200840759618190, -4539868324718349586, 917433146739719185, 8425754507451790566, 3050454262751055487, -5698267723410447421, -7008133129402502879, 2794122331521454564, -1742661130270996992, 4974749931220465430, 7221060262513782821, -3438872661118675270, 3831960034712022583, -7381295521341320799, 1537484654863171717, -990435562760762935, 6517397217975460262}
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla[11526]:  [shard 0] storage_service - Node 127.0.0.1 state jump to normal
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla[11526]:  [shard 0] storage_service - NORMAL: node is now in normal status
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:36 localhost.localdomain scylla[11526]:  [shard 0] gossip - Waiting for gossip to settle before accepting client requests...
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:44 localhost.localdomain scylla[11526]:  [shard 0] gossip - No gossip backlog; proceeding
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:44 localhost.localdomain scylla_run[11526]: Starting listening for CQL clients on localhost:9042...
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:44 localhost.localdomain systemd[1]: Started Scylla Server.
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:45 localhost.localdomain scylla_run[11526]: Failed with /column_family/ {"message": "Not found", "code": 404}
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:45 localhost.localdomain scylla_run[11526]: Failed with /stream_manager/ {"message": "Not found", "code": 404}
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:46 localhost.localdomain scylla_run[11526]: Failed with /messaging_service/messages/dropped_by_ver {"message": "Not found", "code": 404}
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:46 localhost.localdomain scylla_run[11526]: Failed with /column_family/ {"message": "Not found", "code": 404}
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:46 localhost.localdomain scylla_run[11526]: Failed with /stream_manager/ {"message": "Not found", "code": 404}
    22:05:46 process          L0362 DEBUG| [stdout] Jan 26 22:05:46 localhost.localdomain scylla_run[11526]: Failed with /gossiper/endpoint/live {"message": "Not found", "code": 404}

The logs above were extracted from one of our package tests (all of them reported the same problem).

Steps to reproduce:

1) Start scylla server
2) Start JMX server
3) Try to execute `nodetool status`

**Comment by lmr** [comment]
@amnonh reported he has patches to resolve this bug. Let's wait on his patches being merged to close this.

**Comment by slivne** [comment]
@lmr 
Amnon sent a patch before you openned the issue scylla@fd94009d0ed7184ca32cb072b2c9b282ebb79826 - can you check it works for you as well

**Comment by lmr** [comment]
I just checked the latest Ubuntu package test - it contains the patch and the test passed.

Solved with fd94009.
