### ISSUE TITLE
logalloc: reclaim_from_evictable evicts up to 3(N^2) segments when asked to reclaim N segments

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylla#8542]
https://github.com/scylladb/scylla/blob/f7e00e781c21fbaa6cb11b88f026be7d57f92c07/utils/logalloc.cc#L1912-L1947

When asked to reclaim n bytes, `reclaim_from_evictable` first evicts n bytes,
then it compacts a segment, and then the function restarts from the
beginning, with n reduced by the memory freed during that compaction.

Since the maximum occupancy of compactible segments is 85%, it takes up to 6
compactions to free a segment. Therefore, the sequence of actions taken by
`reclaim_from_evictable` is as follows:
- evict n bytes and compact a segment (repeats 1-6 times, depending on which compaction frees a segment)
- evict n-128k bytes and compact a segment (x1-6)
- evict n-256k bytes and compact a segment (x1-6)
- ...and so on, until the number goes down to 0, or reclaim is preempted.

This is not a pessimistic example: `reclaim_from_evictable` requested to reclaim N segments worth of memory
will always evict between 0.5(N^2) and 3(N^2) segments worth of memory, unless it's preempted or there is
nothing to evict.
(Of course, it may evict more than 3(N^2) – up to 15% of all memory – when the occupancy is so high that there
are no compactible segments, but that's not relevant here.)

Quadratic eviction seems like unintended behaviour to me. Correct me if I'm wrong.

Possible cause of https://github.com/scylladb/scylla/issues/8248.
`refill_emergency_reserve` calls `reclaim_from_evictable` without preemption,
so it evicts a quadratic amount of memory w.r.t. to the reserve deficit.
Refilling a reserve of 4MB may cause evictions up to 384MB.

CC @avikivity @tgrabiec @bhalevy. Please confirm whether this is a bug or known behaviour.

Reproducer in https://github.com/michoecho/scylla/commit/e536f5785ed6e0338fb227a5379273f9102c0e1d
Run with
`build/release/test/boost/logalloc_test -t quadratic_eviction -- --logger-log-level=lsa=debug -c1 -m4G`
and observe the eviction logs.

**Comment by michoecho** [comment]
Excerpt from the logs of the reproducer:
```
DEBUG 2021-04-24 20:49:22,066 [shard 0] lsa - Evicting 20127744 bytes from region 0, occupancy=92.62%, 3737325069 / 4035313664 [B]
DEBUG 2021-04-24 20:49:22,069 [shard 0] lsa - Compacting after evicting 20127834 bytes
DEBUG 2021-04-24 20:49:22,069 [shard 0] lsa - Compacting segment 0x6010182a0000 from region 0, 84.81%, 111159 / 131072 [B]
DEBUG 2021-04-24 20:49:22,069 [shard 0] lsa - Evicting 20127744 bytes from region 0, occupancy=92.12%, 3717197235 / 4035313664 [B]
DEBUG 2021-04-24 20:49:22,072 [shard 0] lsa - Compacting after evicting 20127834 bytes
DEBUG 2021-04-24 20:49:22,072 [shard 0] lsa - Compacting segment 0x601026aa0000 from region 0, 83.99%, 110085 / 131072 [B]
DEBUG 2021-04-24 20:49:22,072 [shard 0] lsa - Evicting 20127744 bytes from region 0, occupancy=91.62%, 3697069401 / 4035313664 [B]
DEBUG 2021-04-24 20:49:22,076 [shard 0] lsa - Compacting after evicting 20127834 bytes
DEBUG 2021-04-24 20:49:22,076 [shard 0] lsa - Compacting segment 0x6010be600000 from region 0, 83.58%, 109548 / 131072 [B]
DEBUG 2021-04-24 20:49:22,076 [shard 0] lsa - Evicting 20127744 bytes from region 0, occupancy=91.12%, 3676941567 / 4035313664 [B]
DEBUG 2021-04-24 20:49:22,079 [shard 0] lsa - Compacting after evicting 20127834 bytes
DEBUG 2021-04-24 20:49:22,079 [shard 0] lsa - Compacting segment 0x6010bbec0000 from region 0, 82.76%, 108474 / 131072 [B]
DEBUG 2021-04-24 20:49:22,079 [shard 0] lsa - Evicting 20127744 bytes from region 0, occupancy=90.62%, 3656813733 / 4035313664 [B]
DEBUG 2021-04-24 20:49:22,083 [shard 0] lsa - Compacting after evicting 20127834 bytes
DEBUG 2021-04-24 20:49:22,083 [shard 0] lsa - Compacting segment 0x6010769c0000 from region 0, 81.94%, 107400 / 131072 [B]
DEBUG 2021-04-24 20:49:22,083 [shard 0] lsa - Evicting 20127744 bytes from region 0, occupancy=90.12%, 3636685899 / 4035313664 [B]
DEBUG 2021-04-24 20:49:22,086 [shard 0] lsa - Compacting after evicting 20127834 bytes
DEBUG 2021-04-24 20:49:22,086 [shard 0] lsa - Compacting segment 0x601075fc0000 from region 0, 81.94%, 107400 / 131072 [B]
DEBUG 2021-04-24 20:49:22,086 [shard 0] lsa - Evicting 19996672 bytes from region 0, occupancy=89.63%, 3616558065 / 4035182592 [B]
DEBUG 2021-04-24 20:49:22,090 [shard 0] lsa - Compacting after evicting 19996806 bytes
DEBUG 2021-04-24 20:49:22,090 [shard 0] lsa - Compacting segment 0x601065d00000 from region 0, 80.71%, 105789 / 131072 [B]
[...]
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Evicting 598016 bytes from region 0, occupancy=19.80%, 795219672 / 4015783936 [B]
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Compacting after evicting 598218 bytes
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Compacting segment 0x6010cf060000 from region 0, 15.98%, 20943 / 131072 [B]
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Evicting 466944 bytes from region 0, occupancy=19.79%, 794621454 / 4015652864 [B]
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Compacting after evicting 467190 bytes
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Compacting segment 0x60105b0c0000 from region 0, 15.98%, 20943 / 131072 [B]
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Evicting 466944 bytes from region 0, occupancy=19.78%, 794154264 / 4015652864 [B]
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Compacting after evicting 467190 bytes
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Compacting segment 0x601040540000 from region 0, 15.98%, 20943 / 131072 [B]
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Evicting 335872 bytes from region 0, occupancy=19.77%, 793687074 / 4015521792 [B]
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Compacting after evicting 336162 bytes
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Compacting segment 0x6010c0340000 from region 0, 15.98%, 20943 / 131072 [B]
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Evicting 204800 bytes from region 0, occupancy=19.76%, 793350912 / 4015390720 [B]
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Compacting after evicting 205134 bytes
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Compacting segment 0x601087400000 from region 0, 15.98%, 20943 / 131072 [B]
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Evicting 73728 bytes from region 0, occupancy=19.75%, 793145778 / 4015259648 [B]
DEBUG 2021-04-24 20:49:22,603 [shard 0] lsa - Target met after evicting 537 bytes
```

**Comment by avikivity** [comment]
Wasn't known to me. I always assumed reclaim tried to first evict enough memory so that later compaction could free the required memory without further eviction, but never checked that assumption.

**Comment by tgrabiec** [comment]
This is not an intended behavior, we should evict the deficit once per reclaim_from_evictable(). Still, we should evict inside the loop like today until segments are compactible.

**Comment by slivne** [comment]
@michoecho / @avikivity is one of you working on a fix ?

**Comment by avikivity** [comment]
I'm not working on it. @michoecho please review my proposal, you can also suggest other ideas.

**Comment by michoecho** [comment]
The proposal in https://github.com/scylladb/scylla/pull/8483#issuecomment-829106877 and the surrounding discussion are only tangentially related to this issue. This bug is a programmer error, not a bad heuristic, and the fix is simple, see #8611. But the discussion was needed to confirm what we expect from reclaim.

As for https://github.com/scylladb/scylla/pull/8483#issuecomment-829106877, it's not great that we evict rows in advance even if it won't contribute to the reclaim, but it doesn't seem like a significant problem either, because:

1. The work spend on eviction itself is amortized by the compaction that takes place after it (at least after #8542) is fixed.
2. Eviction is only called when the region occupancy is higher than 85%, so it won't bring the utilization below this point.

**Comment by avikivity** [comment]
Will keep the backport candidate label so we can revisit it later.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
