### ISSUE TITLE
Issue building scylla on Ubuntu

### ISSUE THREAD

**Issue by niklas-ng** [scylladb/scylla#855]
Hi all,

I am building Scylla on Ubuntu 15.04. After installing all the dependencies, I built and got an error as below:

> ~/scylla/git/scylla $ g++ --version
> g++ (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
> Copyright (C) 2015 Free Software Foundation, Inc.
> This is free software; see the source for copying conditions.  There is NO
> warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
> 
> ~/scylla/git/scylla $ ninja build/release/scylla -j2
> [36/234] NINJA seastar/build/release/libseastar.a
> ninja: Entering directory `seastar'
> [1/1] AR build/release/libseastar.a
> [37/234] GEN seastar/http/request_parser.hh
> ninja: Entering directory`seastar'
> ninja: no work to do.
> [234/234] LINK build/release/scylla
> FAILED: g++  -I. -I build/release/gen -I seastar -I seastar/build/release/gen   -L/home/niklas/scylladb/git/scylla/seastar/build/release -Wl,--whole-archive,-lseastar,--no-whole-archive -g -Wl,--no-as-needed   -fvisibility=hidden -pthread   -laio -lboost_program_options -lboost_system -lboost_filesystem -lstdc++ -lm -lboost_unit_test_framework -lboost_thread -lcryptopp -lrt -lgnutls -lgnutlsxx -lhwloc -lnuma -lpciaccess -lxml2 -lz -o <<<list of object files .o skipped>>> seastar/build/release/libseastar.a -lthrift -lboost_system -lyaml-cpp -llz4 -lz -lsnappy -ljsoncpp -lboost_filesystem -lcrypt -lsystemd 
> build/release/db/config.o: In function `YAML::Node::Scalar[abi:cxx11]() const':
> /usr/include/yaml-cpp/node/impl.h:158: undefined reference to`YAML::detail::node_data::empty_scalar[abi:cxx11]'
> collect2: error: ld returned 1 exit status
> ninja: build stopped: subcommand failed.

Please help me. Thank a lot

**Comment by avikivity** [comment]
Where did you get yaml-cpp from?  was it part of 15.04, or did you build it yourself?

**Comment by niklas-ng** [comment]
I install it from apt repo with sudo apt-get install libyaml-cpp-dev

**Comment by avikivity** [comment]
It looks like your g++ 5.2.1 was compiled with `_GLIBCXX_USE_CXX11_ABI=1`, while the libraries on 15.04 were compiled with g++-4.9 (equivalent to `_GLIBCXX_USE_CXX11_ABI=0`).  See https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html for details.

To get this to work, you need g++-5.21 compiled with `_GLIBCXX_USE_CXX11_ABI=0`, or just use the default g++-4.9 instead.

**Comment by dioptre** [comment]
If you follow this using clang instead of g++ that fixes it

**Comment by slivne** [comment]
we support 16.04
