### ISSUE TITLE
materialized views: pulled old schemas are not fixed

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla#8554]
The is another breach in the schema registry through which a materialized view with a non-writable base link can
be created. This can happen when a node pulls schema to fulfill a write/read request. When a node actively pulls a schema
of a materialized view with computed columns, if the schema is an old secondary index one, it is not fixed as it should be.
The reason for not encountering this is that in order to activate the internal error, the view must have been created in an old version (3.1 or lower) and in addition to this, a write or read is performed while the cluster is in a mixed mode.

**Comment by eliransin** [comment]
Fixed by #8509

**Comment by avikivity** [comment]
Backported to 4.3, 4.4, 4.5.
