### ISSUE TITLE
[<=4.4] reader_concurrency_semaphore: inactive reads  can block shutdown

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#8561]
Pre 4.5, `inactive_read_handle` is a pure weak reference to the inactive read. Destroying the handle leaves the associated inactive read in the semaphore. As inactive reads have no TTL of their own, these can sit there indefinitely. If one is unlucky, some inactive reads might be left in the semaphore during shutdown. As the messaging service is stopped before the database, this means nobody is coming for these reads. But if they are disk reads, they hold on to sstable references, which prevents `sstables::sstable_manager::close()` from finishing, blocking in turn `database::stop()`. This is a deadlock.

**Comment by denesb** [comment]
One thing that is not clear is how these inactive reads are left in the semaphore. The querier cache is supposed to clean up after itself.

**Comment by bhalevy** [comment]
@denesb what's the earliest version exposed to this issue?

**Comment by denesb** [comment]
The sstables manager was introduced in 3.1, so I guess 3.1, which basically means all currently supported OSS releases.

**Comment by avikivity** [comment]
Fixed in 4.3, 4.4.
