### ISSUE TITLE
repeated message: service_level_controller - service level default was deleted

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#8567]
scylla commit: 6c168ee0eb8df1ab509ab193a79a9973836ef31c

The message is showed every 10 seconds repeatedly. Is this expected? Why is it useful?

```
INFO  2021-04-29 12:49:21,478 [shard 0] service_level_controller - service level "default" was deleted.
INFO  2021-04-29 12:49:31,485 [shard 0] service_level_controller - service level "default" was deleted.
INFO  2021-04-29 12:49:41,491 [shard 0] service_level_controller - service level "default" was deleted.
INFO  2021-04-29 12:49:51,499 [shard 0] service_level_controller - service level "default" was deleted.
INFO  2021-04-29 12:50:01,502 [shard 0] service_level_controller - service level "default" was deleted.
INFO  2021-04-29 12:50:11,504 [shard 0] service_level_controller - service level "default" was deleted.
```

**Comment by denesb** [comment]
I'm also seeing this and it is annoying.

**Comment by psarna** [comment]
@eliransin perhaps something was not forward-ported properly? I'll be out until Tuesday due to a holiday period in Poland, so I won't be able to take a look soon.

**Comment by psarna** [comment]
Meanwhile, if somebody wants to volunteer, the solution is to simply downgrade the logging level from `service_level_controller.cc` messages from `info` to `debug`. Here's one of the culprits:
https://github.com/scylladb/scylla/blob/0e8818f6aca35c7481192fb517ef2a0a81e5421f/service/qos/service_level_controller.cc#L163
, but generally all these messages can be moved from `info` to a lesser logging level.
