### ISSUE TITLE
TWCS: sometimes SSTables are not compacted together when time window finishes

### ISSUE THREAD

**Issue by laurovenancio** [scylladb/scylla#8569]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.3.2
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

After altering the compaction strategy from STCS to TWCS, the scylla server compacts the sstables in the current window but does not compact them together when the time window finishes. If I restart scylla, everything starts to work fine.

When I enabled the debug messages, I noticed that there is garbage in the now timestamp:

`Abr 29 14:18:46 ip-10-0-11-38.ec2.internal scylla[1301]:  [shard 0] compaction - No compaction necessary for bucket size 2 , key 1619668800000000, now 7526485165035381348`

It seems this issue is caused by the use of an uninitialized variable: _highest_window_seen
https://github.com/scylladb/scylla/blob/master/sstables/time_window_compaction_strategy.hh#L104

**Comment by raphaelsc** [comment]
Thanks for the detailed report. I will investigate it soon.

**Comment by laurovenancio** [comment]
I could confirm that this issue is caused by the missing initialization of _highest_window_seen. I will send a patch.

**Comment by avikivity** [comment]
Backported to 4.3, 4.4, 4.5.
