### ISSUE TITLE
AMI does not set the SCYLLA_ARGS

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#857]
AMI does not set the SCYLLA_ARGS

Using AMI : scylla_2016-01-20T15-55-38Z (ami-ac4f69c6)

Starting an instance of c3.8xlarge 

scylla is run with 

```
/usr/bin/scylla --log-to-syslog 1 --log-to-stdout 0 --default-log-level info --network-stack posix
```

```
[centos@ip-10-146-75-221 ~]$ cat /etc/sysconfig/scylla-server 
# choose following mode: virtio, dpdk, posix
NETWORK_MODE=posix

# tap device name(virtio)
TAP=tap0

# bridge device name (virtio)
BRIDGE=virbr0

# ethernet device name
IFNAME=eth0

# setup NIC's interrupts, RPS, XPS (posix)
SET_NIC=no

# ethernet device driver (dpdk)
ETHDRV=

# ethernet device PCI ID (dpdk)
ETHPCIID=

# number of hugepages
NR_HUGEPAGES=64

# user for process (must be root for dpdk)
USER=scylla

# group for process
GROUP=scylla

# scylla home dir
SCYLLA_HOME=/var/lib/scylla

# scylla config dir
SCYLLA_CONF=/etc/scylla

# additional arguments
SCYLLA_ARGS=

# setup as AMI instance
AMI=yes

# do not upgrade Scylla packages on AMI startup
AMI_KEEP_VERSION=no
```

I think the issue is that the dist/common/scripts/scylla_sysconfig_setup is run at rpm installation - which is when the AMI is created and not when the machine is booted up.

So the script uses the env (cpu info etc.) in which the AMI is created to set the /etc/sysconfig/scylla.server and does not use the env in which scylla is running in

**Comment by slivne** [comment]
This is tightly coupled to the decision of when we install scylla on the ami and if the ami is generic and downloads the rpms on boot.

We need a quick fix for the current issue - yet lets aftre that impl the firection we will have in GA.

**Comment by syuu1228** [comment]
Fixed on recently submitted scylla-ami-setup.service patchset
