### ISSUE TITLE
Building on Ubuntu 14.04.3: other._row_tombstones.comp(), has no member named 'comp'

### ISSUE THREAD

**Issue by kirillsc** [scylladb/scylla#858]
Hi,
I am trying to compile Scylla on Ubuntu 14.04, after fixing some of the issues outlines in this forum, I came across problem that I am not sure how to fix. I have encountered compilation error after calling `ninja build/release/scylla -j2`

>  g++ -MMD -MT build/release/gen/cql3/CqlParser.o -MF build/release/gen/cql3/CqlParser.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I/home/kirillb/projects/scylla/seastar -I/home/kirillb/projects/scylla/seastar/build/release/gen  -march=nehalem -Wno-overloaded-virtual -DHAVE_HWLOC -DHAVE_NUMA  -O2 -I/usr/include/jsoncpp -Wno-maybe-uninitialized  -I. -I build/release/gen -I seastar -I seastar/build/release/gen -c -o build/release/gen/cql3/CqlParser.o build/release/gen/cql3/CqlParser.cpp
In file included from ./mutation.hh:26:0,
                 from ./database.hh:61,
                 from ./service/storage_proxy.hh:44,
                 from ./db/schema_tables.hh:43,
                 from ./db/system_keyspace.hh:46,
                 from ./cql3/functions/function_name.hh:45,
                 from ./cql3/selection/selectable.hh:48,
                 from ./cql3/selection/writetime_or_ttl.hh:45,
                 from build/release/gen/cql3/CqlParser.hpp:63,
                 from build/release/gen/cql3/CqlParser.cpp:44:
./mutation_partition.hh: In constructor 'mutation_partition::mutation_partition(mutation_partition&, mutation_partition::copy_comparators_only)':
./mutation_partition.hh:596:29: error: 'using rows_type = class boost::intrusive::set<rows_entry, boost::intrusive::member_hook<rows_entry, boost::intrusive::set_member_hook<>, &rows_entry::_link>, boost::intrusive::compare<rows_entry::compare> >' has no member named 'comp'
         : _rows(other._rows.comp())
                             ^
./mutation_partition.hh:597:49: error: 'using row_tombstones_type = class boost::intrusive::set<row_tombstones_entry, boost::intrusive::member_hook<row_tombstones_entry, boost::intrusive::set_member_hook<>, &row_tombstones_entry::_link>, boost::intrusive::compare<row_tombstones_entry::compare> >' has no member named 'comp'
         , _row_tombstones(other._row_tombstones.comp())

Could you please advise on how I can address this problem?
Thank you!

**Comment by avikivity** [comment]
We probably ought to be using `key_comp()` instead of `comp()` here.  Can you check whether making that change helps?

**Comment by kirillsc** [comment]
Thank you, this solved the problem. I have changed `comp()` to `key_comp()` in mutation_partition.hh and compilation moved forward. 

FYI, I have came across another error, which I passed by commenting the line out

> FAILED: g++ -MMD -MT build/release/api/column_family.o -MF build/release/api/column_family.o.d -std=gnu++1y -g  -Wall -Werror -fvisibility=hidden -pthread -I/home/kirillb/projects/scylla/seastar -I/home/kirillb/projects/scylla/seastar/build/release/gen  -march=nehalem -Wno-overloaded-virtual -DHAVE_HWLOC -DHAVE_NUMA  -O2 -I/usr/include/jsoncpp -Wno-maybe-uninitialized  -I. -I build/release/gen -I seastar -I seastar/build/release/gen -c -o build/release/api/column_family.o api/column_family.cc
In file included from /home/kirillb/projects/scylla/seastar/core/future-util.hh:29:0,
                 from /home/kirillb/projects/scylla/seastar/http/handlers.hh:28,
                 from /home/kirillb/projects/scylla/seastar/http/matchrules.hh:25,
                 from /home/kirillb/projects/scylla/seastar/http/routes.hh:25,
                 from /home/kirillb/projects/scylla/seastar/http/json_path.hh:30,
                 from build/release/gen/api/api-doc/utils.json.hh:16,
                 from api/api.hh:28,
                 from api/column_family.hh:24,
                 from api/column_family.cc:22:
/home/kirillb/projects/scylla/seastar/core/future.hh: In instantiation of 'struct future_state<utils::ihistogram>':
/home/kirillb/projects/scylla/seastar/core/future.hh:660:24:   required from 'class future<utils::ihistogram>'
api/column_family.cc:114:26:   required from here
/home/kirillb/projects/scylla/seastar/core/future.hh:134:5: error: static assertion failed: Types must be no-throw move constructible
     static_assert(std::is_nothrow_move_constructible<std::tuple<T...>>::value,
     ^
[169/234] CXX build/release/message/messaging_service.o
ninja: build stopped: subcommand failed.

After this I managed to successfully compile the project.
Thank you!
