### ISSUE TITLE
STCS get_buckets insertion algorithm may break the bucket invariant

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8584]
Currently (9cc45fe5c91bc72359021108e2f032f20d7177e2), as we insert increasingly larger sstables into a bucket, its average size drifts up and eventually this may break the bucket invariant that all sstables in the bucket should be within the `(bucket_low, bucket_high)` range relative to the bucket average.

For example, here's a simulation run of the algorithm for these sstable sizes:
`[21, 123, 252, 363, 379, 394, 407, 428, 463, 467, 470, 523, 752, 774]`

the simulated compaction strategy options are:
```
min_sstable_size = 4
bucket_low = 0.66667
bucket_high = 1.5
``` 

For each bucket, the following is printed: (avg * bucket_low) avg (avg * bucket_high)
```    
buckets={
    (  14.0)   21.0 (  31.5): [21]
    (  82.0)  123.0 ( 184.5): [123]
    ( 276.4)  414.6 ( 621.9): [252, 363, 379, 394, 407, 428, 463, 467, 470, 523]
    ( 508.7)  763.0 (1144.5): [752, 774]
}
```

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
