### ISSUE TITLE
STCS: Scylla uses uncompressed data size while Cassandra uses on-disk data size for min_sstable_size parameter

### ISSUE THREAD

**Issue by laurovenancio** [scylladb/scylla#8588]
*Installation details*
Scylla version (or git commit hash): 4.4.1
Cluster size: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): AWS AMI

As Scylla uses the uncompressed data size from generating the sstable buckets, the min_sstable_size behavior differs from Cassandra. It is also not documented the use of uncompressed size for the min_sstable_size parameter.

**Comment by slivne** [comment]
@raphaelsc can you please comment

**Comment by raphaelsc** [comment]
STCS achieves low write amplification by compacting together similar-sized data and allowing their accumulation. Compaction is performed on input data after decompressed, so it's natural that the strategy makes decisions using the uncompressed size. If compressed size were used instead,  sstables with different compression ratio could be considered similar-sized even though they aren't, which could lead to a decrease in compaction efficiency. So I'd say I would rather not change this.

**Comment by raphaelsc** [comment]
Agreed this should be documented at least.

**Comment by raphaelsc** [comment]
I am closing this as it's a doc issue. i'll make sure docs are properly updated.
