### ISSUE TITLE
Unified Installer: Incorrect file security context cause scylla_setup to fail

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylla#8589]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.4.1-0.20210406.00da6b5e9
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 8
Unified package: http://downloads.scylladb.com/downloads/scylla/relocatable/scylladb-4.4/scylla-unified-package-4.4.1.0.20210406.00da6b5e9.tar.gz

# How to reproduce
This has been tested and reproduced under **CentOS 8** with **SELinux enabled**.

When installing Scylla as root via the Unified Installer method, it will set-up the following two files with incorrect security contexts:
> -rw-r--r--. 1 root root system_u:object_r:default_t:s0 98 May  4 17:51 /etc/systemd/system/scylla-node-exporter.service.d/dependencies.conf
> -rw-r--r--. 1 root root system_u:object_r:default_t:s0 98 May  4 17:51 /etc/systemd/system/scylla-server.service.d/dependencies.conf

Due to that, **scylla_setup** will fail with the following stacktrace:
> $ scylla_setup 
>ntp setup is disabled by default, since the installation is offline mode.
>
>Skip any of the following steps by answering 'no'
>Do you want to run check your kernel version?
>Yes - runs a  script to verify that the kernel for this instance qualifies to run Scylla. No - skips the kernel check.
>[YES/no]YES
>WARN  2021-05-04 17:52:47,717 [shard 0] seastar - Unable to set SCHED_FIFO scheduling policy for timer thread; latency impact possible. Try adding CAP_SYS_NICE
>WARN  2021-05-04 17:52:47,820 [shard 0] iotune - Available space on filesystem at /var/tmp/mnt: 121 MB: is less than recommended: 10 GB
>INFO  2021-05-04 17:52:47,820 [shard 0] iotune - /var/tmp/mnt passed sanity checks
>This is a supported kernel version.
>Do you want to verify the ScyllaDB packages are installed?
>Yes - runs a script to confirm that ScyllaDB is installed. No - skips the installation check.
>[YES/no]YES
>Do you want the Scylla server service to automatically start when the Scylla node boots?
>Yes - Scylla server service automatically starts on Scylla node boot. No - skips this step. Note you will have to start the Scylla Server service manually.
>[YES/no]YES
>Failed to enable unit: Access denied
>Traceback (most recent call last):
>  File "/opt/scylladb/scripts/libexec/scylla_setup", line 358, in <module>
>   systemd_unit('scylla-server.service').enable()
>  File "/opt/scylladb/scripts/scylla_util.py", line 789, in enable
>    return run('systemctl {} enable {}'.format(self.ctlparam, self._unit), shell=True, check=True)
>  File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
>    raise CalledProcessError(retcode, process.args,
>subprocess.CalledProcessError: Command 'systemctl  enable scylla-server.service' returned non-zero exit status 1.

Similarly, manually running systemctl will also fail:
> $ systemctl enable scylla-server.service
> Failed to enable unit: Access denied

# Workaround
Set the file contexts to `systemd_unit_file_t`, for example, via the `restorecon` command:
> $ restorecon -Rv /etc/systemd/system/scylla-node-exporter.service.d/dependencies.conf
> Relabeled /etc/systemd/system/scylla-node-exporter.service.d/dependencies.conf from system_u:object_r:default_t:s0 to system_u:object_r:systemd_unit_file_t:s0
> $ restorecon -Rv /etc/systemd/system/scylla-server.service.d/dependencies.conf
> Relabeled /etc/systemd/system/scylla-server.service.d/dependencies.conf from system_u:object_r:default_t:s0 to system_u:object_r:systemd_unit_file_t:s0

# Suggested fix
In addition to adjusting the correct file context during installation, it is worth to mention that this problem would not have happened should the `/opt/scylladb/scripts/libexec/scylla_selinux_setup` invocation as part of `scylla_setup` had been done earlier, in such a way that adjusting the `scylla_setup` ordering should be considered to avoid such cenarios like these in the future.

**Comment by syuu1228** [comment]
@slivne @penberg I think we haven't tested on SELinux enforcing mode environment enough since our recommendation is disabling SELinux for performance reason.
This bug probably able to fix easily, but if we want to keep supporting such environment, we should add a test to setup & run Scylla in SELinux enforcing mode.
And it should be not only Unified Installer, also with RPM installation.

BTW, to fix the problem we should setup SELinux file contexts correctly on install.sh, by running `chcon` or `restorecon`.
And it should run only when --packaging option is not specified, because we don't need it when building rpm/deb.

**Comment by syuu1228** [comment]
Ah, there is a option to apply default file context on /usr/bin/install, we don't need to `restorecon`, correct context can apply on copying time:
```
       -Z     set SELinux security context of destination file and each
              created directory to default type
```
https://man7.org/linux/man-pages/man1/install.1.html

**Comment by avikivity** [comment]
Backported to 4.3, 4.4, 4.5.
