### ISSUE TITLE
Compaction only deletes TOC file for some sstables

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla#860]
Configuration: Version 0.17, Rack 3 x Rackspace OnMetal IO v1, Replication 2, 150M keys each 10KB in size

After a random standard compaction completed, for some sstables Scylla only deleted the TOC files.
Unfortunately at this point I don't know how to recreate the  bug.

Start of compaction from log:
```
Feb 01 10:49:10 noam-server-03.localdomain scylla[12860]:  [shard 27] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-2987-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-3067-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-3187-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-3347-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-3507-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-3667-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-3747-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-3827-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-3907-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-3987-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-4227-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-4307-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-4387-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-4467-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-4547-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-4627-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-4707-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-4787-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-4867-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-4947-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-5027-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-5107-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-5187-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-5267-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-5347-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-5427-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-5507-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-5587-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-5667-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-5747-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-5827-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-5907-Data.db:level=0, ]
```

Compaction complete from log:
```
Feb 01 10:53:35 noam-server-03.localdomain scylla[12860]:  [shard 27] compaction - Compacted 32 sstables to [/var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-6027-Data.db:level=0, ]. 2162137582 bytes to 2162137582 (~100% of original) in 264926ms = 7.78318MB/s. ~214912 total partitions merged to 208882.
```

After this the shard immediately started a new compaction:
```
Feb 01 10:53:35 noam-server-03.localdomain scylla[12860]:  [shard 27] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-2907-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-3267-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-3427-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-3587-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-4067-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-4147-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-5987-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-6107-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-6187-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-6267-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-6347-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-6427-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-6507-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-6587-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-6667-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-6747-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-6827-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-6907-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-6987-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-7067-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-7147-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-7227-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-7307-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-7387-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-7467-Data.db:level=0, /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002/keyspace1-standard1-ka-7547-Data.db:level=0, ]
```

The service was stopped after around 10 minutes, in which there were no new messages from shard 27

**Comment by slivne** [comment]
noam can you please add the specific cassandra-stress command

**Comment by noamha** [comment]
Sure, running from 5 separate stress servers:
```
time cassandra-stress write cl=TWO n=30000000 -mode native cql3 -rate threads=700 -node $SERVERS -pop seq=1..30000000 -col 'size=FIXED(2048) n=FIXED(5)'
time cassandra-stress write cl=TWO n=30000000 -mode native cql3 -rate threads=700 -node $SERVERS -pop seq=30000000..60000000 -col 'size=FIXED(2048) n=FIXED(5)'
time cassandra-stress write cl=TWO n=30000000 -mode native cql3 -rate threads=700 -node $SERVERS -pop seq=60000000..90000000 -col 'size=FIXED(2048) n=FIXED(5)'
time cassandra-stress write cl=TWO n=30000000 -mode native cql3 -rate threads=700 -node $SERVERS -pop seq=90000000..120000000 -col 'size=FIXED(2048) n=FIXED(5)'
time cassandra-stress write cl=TWO n=30000000 -mode native cql3 -rate threads=700 -node $SERVERS -pop seq=120000000..150000000 -col 'size=FIXED(2048) n=FIXED(5)'
```

**Comment by raphaelsc** [comment]
@noamha is the server still alive? It would be nice to peak into data directory. Do you remember which SSTables Scylla deleted only TOC component? Were the ones selected for compaction? Because when a new sstable is created, it will miss a TOC until it's completely generated, so if you stopped Scylla in between, that sstable will indeed miss a TOC file.

**Comment by raphaelsc** [comment]
@noamha, @slivne: I was able to reproduce this issue, and I found something very interesting. When stopping the service, journalctl reports the following:

Feb 01 17:53:59 noam-server-02.localdomain systemd[1]: scylla-server.service stop-sigterm timed out. Killing.
Feb 01 17:53:59 noam-server-02.localdomain systemd[1]: scylla-server.service: main process exited, code=killed, status=9/KILL

Trying to start service again, we have:

Feb 01 17:59:02 noam-server-02.localdomain scylla[39664]: WARNING: exceptional future ignored of type 'sstables::malformed_sstable_exception': At directory: /var/lib/scylla/data/keyspace1/standard1-2188b120c8cf11e59e5e000000000002: no TOC found for SSTable with generation 19135!. Refusing to boot

I think that's the problem. 'service scylla stop' is timing out and scylla is being killed abruptly. As a result, we end up with some partial deletions. Scylla really takes time to be stopped because it waits for compaction and other activities to finish. I wonder why the timeout. Is it a parameter or something that we can get rid of? 

Am I missing something?

**Comment by lmr** [comment]
@raphaelsc I guess the timeouts are there to avoid a buggy service to take forever to stop. There must be some systemd-fu that will allow us to use a more relaxed timeout setting.

**Comment by slivne** [comment]
Raphael that may be an additional issue but its unrelates to the specific case that noam reported the compaction ended on the shard

The shard started another compaction

The server wss still up for another 10 minutes before it was shutdown ....

In noam's case i think this is not the explenation, or if it is why does it take 10 minutes to compkete removing the files

**Comment by raphaelsc** [comment]
@slivne Noam's case is the following: He loads Scylla, and eventually stops a random server. That server may now contain a sstable missing a TOC. The thing is that 'service stop' times out and kills Scylla abruptly.

**Comment by penberg** [comment]
How long can it take for Scylla to stop? Perhaps we need to increase DefaultTimeoutStopSec in the systemd service configuration? @avikivity

**Comment by avikivity** [comment]
It can take forever if compacting a 1TB file on a slow disk.  We need to abort compactions, not wait for them.

**Comment by slivne** [comment]
That not the issue in my view.

check what noam reported

- a compaction finished at 10:53 

- only 10 minutes after it completed was the server shutdown.

Why didn't we delete the files in the 10 minute window prior to compaction - we only deleted the TOC ?

**Comment by avikivity** [comment]
Where are the logs?

**Comment by slivne** [comment]
noam extracted the oneliners - he did not download them all - Raphael has
access to the machines.

**Comment by avikivity** [comment]
I can't comment on logs I can't see.

**Comment by slivne** [comment]
@raphaelsc can you please download from noam-server-03 the complete logs starting from "Feb 01 10:49" - "Feb 01 11:00"

**Comment by slivne** [comment]
I reproduces the issue on a smaller setup

  * single server running 0.17
  * 3 loaders (running the write commands from above)
  * wait till there are large compactions (sudo journalctl | grep "Compacted 3" )
  * run service scylla-server stop

   * try booting up scylla - it does not start with the reported exception

I verified this is a regression

  * Installed another server with 0.16
  * ran the load
  * waited for large compactions
  * service scylla-server stop
  * started scylla back up - without any problem.

In both cases scylla-server stop timedout

```
Feb 02 11:14:36 sl-test-16.localdomain systemd[1]: Stopping Scylla Server...
Feb 02 11:14:36 sl-test-16.localdomain kernel: scylla[13435]: segfault at f90 ip 00000000004c76f3 sp 00007f47e26f2a78 error 6 in scylla[400000+174a000]
Feb 02 11:16:06 sl-test-16.localdomain systemd[1]: scylla-server.service stop-sigterm timed out. Killing.
Feb 02 11:16:07 sl-test-16.localdomain systemd[1]: scylla-server.service: main process exited, code=killed, status=11/SEGV
Feb 02 11:16:07 sl-test-16.localdomain sudo[36784]:   scylla : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/usr/lib/scylla/scylla_stop
```

I have done the tests with 0.16 twice - and it did not reproduce, with 0.17 - first attempt reproduced the issue - so it seems a regression.

**Comment by avikivity** [comment]
Looks like messaging_service doesn't shut down.

```
Feb 02 10:20:03 sl-test.localdomain systemd[1]: Stopping Scylla Server...
Feb 02 10:20:03 sl-test.localdomain scylla[37499]:  [shard 0] storage_service - Drain on shutdown: starts
Feb 02 10:20:03 sl-test.localdomain scylla[37499]:  [shard 0] gossip - Announcing shutdown
Feb 02 10:20:03 sl-test.localdomain scylla[37499]:  [shard 0] storage_service - Node 10.184.10.186 state jump to normal
Feb 02 10:20:05 sl-test.localdomain scylla[37499]:  [shard 0] storage_service - Drain on shutdown: stop_gossiping done
Feb 02 10:20:08 sl-test.localdomain scylla[37499]:  [shard 22] compaction - Compacted 6 sstables to [/var/lib/scylla/data/keyspace1/standard1-cf6b9d60c99311e5a649000000000000/keyspace1-standard
Feb 02 10:20:08 sl-test.localdomain scylla[37499]:  [shard 22] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-cf6b9d60c99311e5a649000000000000/keyspace1-standard1-ka-6942-Dat
Feb 02 10:20:12 sl-test.localdomain scylla[37499]:  [shard 35] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-cf6b9d60c99311e5a649000000000000/keyspace1-standard
Feb 02 10:20:12 sl-test.localdomain scylla[37499]:  [shard 35] compaction - Compacting
```

Regardless, we should stop compaction during shutdown.

**Comment by raphaelsc** [comment]
@avikivity, New compaction shouldn't start after compaction manager was asked to stop. Yes, we don't stop ongoing compaction at the moment, but we prevent new ones from starting. I added a print at database::stop() and the function isn't called. I suppose that it's a regression. 

I will work on the patch to stop ongoing compaction during shutdown.

**Comment by avikivity** [comment]
Your stop is not called because messaging_service did not stop, and we stop sequentially.

Stopping ongoing compaction will help in other cases so it's worthwhile.

**Comment by raphaelsc** [comment]
Do you know how to fix this: 'Your stop is not called because messaging_service did not stop'? I'm not familiar with it. Why isn't it stopped?

**Comment by avikivity** [comment]
Only @asias knows.

**Comment by raphaelsc** [comment]
@asias: Sometimes shutdown works, sometimes it doesn't.

When it works:

^CINFO  [shard 0] storage_service - Drain on shutdown: starts
INFO  [shard 0] gossip - Announcing shutdown
INFO  [shard 0] storage_service - Node 127.0.0.1 state jump to normal
INFO  [shard 0] storage_service - Drain on shutdown: stop_gossiping done
INFO  [shard 0] storage_service - CQL server stopped
INFO  [shard 0] storage_service - Drain on shutdown: shutdown rpc and cql server done
INFO  [shard 0] storage_service - Drain on shutdown: shutdown messaging_service done
INFO  [shard 0] storage_service - Drain on shutdown: flush column_families done
INFO  [shard 0] storage_service - Drain on shutdown: shutdown commitlog done
INFO  [shard 0] storage_service - Drain on shutdown: done

When it doesn't:
^CINFO  [shard 0] storage_service - Drain on shutdown: starts
INFO  [shard 0] gossip - Announcing shutdown
INFO  [shard 0] storage_service - Node 127.0.0.1 state jump to normal
INFO  [shard 0] storage_service - Drain on shutdown: stop_gossiping done

**Comment by raphaelsc** [comment]
I'm not seeing this shutdown issue anymore after reverting:
46c392eb17c1a5b4d13006bedf43fca477579b7c
b2f2c1c28c7004caae464fcd4dcde12bb5c8c387

**Comment by asias** [comment]
@raphaelsc If you revert

46c392e
b2f2c1c

there is no other shutdown hooked at all if you press ^C, except the db.stop.

'''
  0                 supervisor_notify("starting per-shard database core");
  1                 // Note: changed from using a move here, because we want the config object intact.
  2                 return db.start(std::ref(*cfg)).then([&db] {
  3                     engine().at_exit([&db] {
  4
  5                         // #293 - do not stop anything - not even db (for real)
  6                         //return db.stop();
  7                         // call stop on each db instance, but leave the shareded<database> pointers alive.
  8                         return db.invoke_on_all([](auto& db) {
  9                             return db.stop();
 10                         }).then([] {
 11                             ::_exit(0);
 12                         });
 13                     });
'''

We should have a single at_exit hook to stop all the services.

**Comment by asias** [comment]
@gleb-cloudius @avikivity 

messaging_service is

    class messaging_service : public seastar::async_sharded_service<messaging_service>

we take a reference when sending a verb by

     ms = ms->shared_from_this()

During shutdown, we call messaging_service::stop()

```
  0 future<> messaging_service::stop() {
  1     _stopping = true;
  2     return when_all(
  3         _server->stop(),
  4         parallel_for_each(_clients, [] (auto& m) {
  5             return parallel_for_each(m, [] (std::pair<const msg_addr, shard_info>& c) {
  6                 return c.second.rpc_client->stop();
  7             });
  8         })
  9     ).discard_result();
 10 }
```
which is supposed to abort both rpc server and client.  

Any pending send_message_* would abort and the reference to ms = shared_from_this() would go away.

I don't understand why messaging_service::stop() would block forever. 

@gleb-cloudius What about the the rpc client which is not connected yet. Do we abort them or we wait for them to timeout which might take a long time.

**Comment by asias** [comment]
@avikivity  The log you posted in previous comment, it actually says we stuck at ss.shutdown_client_servers().get(), not at stopping message service!

The shutdown_client_servers is problematic for a long time.

'''
Feb 02 10:20:03 sl-test.localdomain systemd[1]: Stopping Scylla Server...
Feb 02 10:20:03 sl-test.localdomain scylla[37499]:  [shard 0] storage_service - Drain on shutdown: starts
Feb 02 10:20:03 sl-test.localdomain scylla[37499]:  [shard 0] gossip - Announcing shutdown
Feb 02 10:20:03 sl-test.localdomain scylla[37499]:  [shard 0] storage_service - Node 10.184.10.186 state jump to normal
Feb 02 10:20:05 sl-test.localdomain scylla[37499]:  [shard 0] storage_service - Drain on shutdown: stop_gossiping done
Feb 02 10:20:08 sl-test.localdomain scylla[37499]:  [shard 22] compaction - Compacted 6 sstables to [/var/lib/scylla/data/keyspace1/standard1-cf6b9d60c99311e5a649000000000000/keyspace1-standard
Feb 02 10:20:08 sl-test.localdomain scylla[37499]:  [shard 22] compaction - Compacting [/var/lib/scylla/data/keyspace1/standard1-cf6b9d60c99311e5a649000000000000/keyspace1-standard1-ka-6942-Dat
Feb 02 10:20:12 sl-test.localdomain scylla[37499]:  [shard 35] compaction - Compacted 4 sstables to [/var/lib/scylla/data/keyspace1/standard1-cf6b9d60c99311e5a649000000000000/keyspace1-standard
Feb 02 10:20:12 sl-test.localdomain scylla[37499]:  [shard 35] compaction - Compacting
'''

**Comment by asias** [comment]
From @raphaelsc,  load single node scylla with c-s, then press ^C, we fail to shutdown one of the cql connections, it hangs forever. 

cql_server experts please take a look. @penberg @pdziepak 

The original issue is here:
https://github.com/scylladb/scylla/issues/690


'''
^CINFO  [shard 0] storage_service - Drain on shutdown: starts
INFO  [shard 0] gossip - Announcing shutdown
INFO  [shard 0] storage_service - Node 127.0.0.1 state jump to normal
INFO  [shard 0] storage_service - Drain on shutdown: stop_gossiping done
DEBUG [shard 0] cql_server - cql_server: abort accept nr_total=1
DEBUG [shard 0] cql_server - cql_server: abort accept 1 out of 1 done
DEBUG [shard 0] cql_server - cql_server: shutdown connection nr_total=2
DEBUG [shard 0] cql_server - cql_server: shutdown connection 1 out of 2 done
'''

**Comment by slivne** [comment]
Another thing we should do is change the delete of sstables so that it will
do the rename ... instead of removing the toc in the first step.

So the code would do

rename toc to tmp toc
delete all files (except for tmp toc)
delete tmp toc

If we are interrupted in the middle it will not cause an issue:
- before starting rename a normal sstable
- after removing some files and before removing tmp_toc

Tzach suggested this today - and I think we also discussed this previously,
we still need to chase the current issue yet at least we will not have the
current regression and be able to boot scylla after a shutdown (and be able
to release 0.17)
