### ISSUE TITLE
IndexInfo system table lists MV name instead of index name

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8600]
Cassandra has a system table `system."IndexInfo"` (note the capitalized table name) which lists built indexes using a somewhat strange schema - the `table_name` column lists the keyspace name (_not_ the table name!), and `index_name` is the index name.

Scylla has a bug where if the index name is xyz, it puts **`xyz_index`** in `index_name`. This `xyz_index` string is the materialized view backing the index - not the index's name.

This bug can confuse applications which use this system table to wait for an index to be built. Several tests translated from Cassandra's unit tests, in `cassandra_tests/validation/entities/secondary_index_test.py` fail in `wait_for_index()` because of this incompatibility.

**Comment by nyh** [comment]
Note that there is an interesting question here. If we fix the IndexInfo table, it will fix its compatibility with Cassandra, but break compatibility with earlier versions of Scylla. So if someone wrote code using this IndexInfo table especially for Scylla, this code will break. I doubt much (or any...) such code actually exists in the wild, so I prefer to fix compatibility with Cassandra, but it's still a concern...

**Comment by nyh** [comment]
Note that it appears that we have unit tests **and** dtests, which enshrine the broken behavior. It saddens me every time how we spent time to write tests, but instead of writing tests that will help us catch bugs (differences from the Cassandra API we intended to copy), we wrote tests that make it difficult to fix them :-(

**Comment by nyh** [comment]
Just to update my progress on this issue: I have an implementation which fixes the virtual reader enough to make the Cassandra unit tests' `wait_for_index()` work. The virtual reader removes the "_index" from the view names to generate the list of index names. But this implementation is not good enough to make a different test pass. The problem is that the other test case adds a slice to the WHERE to skip to a specific index - and we need to translate this slice into a view-name slice by adding "_index", and doing this manipulation of slices was too complicated for me :-( And after I do this, in theory I also need to implement fast_forward_to because it might be used in certain queries. This is all extremely frustrating. We have built layers upon layers of classes and to do just trivial things in a virtual readers (like string manipulation adding "_index") requires understanding all those layers, and working around private and incomplete  interfaces in all those layers. Has anyone ever managed to build a correct virtual reader that was actually tested thoroughly?

**Comment by avikivity** [comment]
Using memtables for virtual readers is much more tractable.

**Comment by nyh** [comment]
> Using memtables for virtual readers is much more tractable.

Incredibly, the more I look into this issue, the more I'm starting to feel like this is indeed the only realistic option, and that the existing IndexInfo implementation needs to be dumped, rather than fixed.

What the existing code does today after I tried to fix it is to take a table with rows that list materialized view names (e.g, `a_index`, `b_index`) and generate a virtual reader which returns just the index names, without the "_index" suffixes (e.g., `a`, `b`). Beyond all the problems (which I solved) of translating the data and the request ranges, there is another even darker problem: sort order.

Consider the two index names, `a` and `a1`. This is their desired order. However, in the view name domain, the view names are `a_index` and `a1_index`. Here, `a1_index` would be listed _before_ `a_index`, because in ASCII the underscore comes before the 1. So if the virtual reader reads the list of indexes, and strips out the "_index", the resulting sort order is wrong.

I can't reproduce any actual test that fails because of the wrong sort order (I'm not sure why I can't), but it's still wrong.

**Comment by nyh** [comment]
Patch on mailing list, titled "[PATCH] secondary index: fix index name in IndexInfo system table".
It still has the problem described in the previous comment. Fixing this problem will require completely rewriting the virtual table, and if my patch is committed, I'll open a new issue on the need to do this.
