### ISSUE TITLE
Overlapping range tombstones can lead to very slow reads and OOMs

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#8625]
When compacting a mutation fragment stream (e.g. for sstable compaction, data query, repair), the compactor needs to accumulate range tombstones which are relevant for the yet-to-be-processed range. See `range_tombstone_accumulator`.

When encountering a new mutation fragment, irrelevant range tombstones are dropped. This operation needs to compute the current range tombstone, which is currently O(N) in the number of active tombstones. Currently, we do the calculation even if no range tombstone was dropped (see `range_tombstone_accumulator::drop_unneeded_tombstones`). This can lead to significant CPU overhead per fragment (per row, per range tombstone) if the number of active range tombstones is large.

Adding a new range tombstone is O(N) in the number of currently active tombstones. This means that adding N overlapping tombstones will require O(N^2) of computation time.

In addition to that, it has O(N) memory footprint where N is the max number of tombstones overlapping for any given key. This can lead to OOMs or reduced read concurrency due to admission control.

**Solutions**

A trivial improvement would be to avoid the computation if no tombstone was dropped. That won't help with memory footprint, but will help with CPU overhead for cases where nothing changes for many fragments.

[**Solution A**]: A broader fix for the computational complexity would be to keep the tombstones in the accumulator in deoverlaped form. That will give us O(1) per-fragment processing cost. Adding a new range tombstone will be O(log N) where N is the overlap count. 

We still need to accumulate range tombstones in their original form. The querier saving mechanism which dismantles the compaction state needs that. It pushes active range tombstones back to the reader they came from so that compaction state can be recreated when the querier is resumed. We cannot push-back the deoverlapped tombstones because deoverlaping may produce range tombstones with positions which are greater than any of the positions accumulated so far, which may violate key monotonicity with later fragments in the stream. This will not be a problem with solution B. With solution A, we could maintain both the original tombstone set and the deoverlapped one. The original set would not be used to compute the current tombstone, so we wouldn't be prone to the computation complexity problem, but memory footprint would be doubled.

Memory footprint problem is not solved by solution A.

[**Solution B**]: Even better fix would be to get rid of the overlap in the mutation fragment stream. That will solve both computational complexity and memory footprint problems. Getting rid of the overlap requires system-wide changes. We would have to add separate mutation fragments for the range tombstone start and end bound, deoverlap in the combined reader accordingly. Generating such a stream from the current single-fragment model requires accumulating, so the problem of accumulation is pushed to the lower layers. We have to switch all producers, including storage format, to get rid of the problem completely. The stable mc format is already switched. Memtables and cache store range tombstones deoverlapped already, although due to MVCC we may still get overlap across MVCC versions. Readers of older sstable formats (ka/la) will have to accumulate.

The sstable writer for ka and la formats would have to split range tombstones (e.g. around every few rows) because the end bound is not known when the range tombstone start is consumed, and we can't accumulate all fragments until the end bound fragment is encountered in memory. Maybe we could drop support for ka/la writers before implementing this solution, it would simplify the effort.

**Comment by avikivity** [comment]
I'm in favor of B. mc+ is unconditional already (57c7964d6ca), so we can drop the ka/la writer.

**Comment by haaawk** [comment]
> I'm in favor of B. mc+ is unconditional already ([57c7964](https://github.com/scylladb/scylla/commit/57c7964d6ca7809ae4864f889c91e42ed41f1c79)), so we can drop the ka/la writer.

I'm working on it -> https://github.com/scylladb/scylla/issues/8352. I have a patch ready just need to fix gazillion tests that fail after switching them from LA to MC.

**Comment by slivne** [comment]
the patch doesn't fix the issue it only lays the foundation to fix the issue

**Comment by tgrabiec** [comment]
We implemented Solution B by introducing flat_mutation_reader_v2.
