### ISSUE TITLE
repair: Consider memory bloat when calculate repair parallelism

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#8641]
The repair parallelism is calculated by the number of memory allocated to
repair and memory usage per repair instance. Currently, it does not
consider memory bloat issues (e.g., issue #8640) which cause repair to
use more memory and cause std::bad_alloc.

Be more conservative when calculating the parallelism to avoid repair
using too much memory.

**Comment by avikivity** [comment]
@asias I think this should be backported, do you agree?

**Comment by asias** [comment]
Yes.
