### ISSUE TITLE
Abort restore_replica_count when node is removed from the cluster

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#8651]
Consider the following procedure:
 ```
 - n1, n2, n3
 - n3 is down
 - n1 runs nodetool removenode uuid_of_n3 to removenode from n3 the
   cluster
 - n1 is down in the middle of removenode operation
 ```
 Node n1 will set n3 to removing gossip status during removenode
 operation. Whenever existing nodes learn a node is in removing gossip
 status, they will call restore_replica_count to stream data from other
 nodes for the ranges n3 loses if n3 was removed from the cluster. If
 the streaming fails, the streaming will sleep and retry. The current
 max number of retry attempts is 5. The sleep interval starts at 60
 seconds and increases 1.5 times per sleep.
 
 This can leave the cluster in a bad state. For example, nodes can go
 out of disk space if the streaming continues.  We need a way to abort
 such streaming attempts.
 
 To abort the removenode operation and forcely remove the node, users
 can run `nodetool removenode force` on any existing nodes to move the
 node from removing gossip status to removed gossip status. However,
 the restore_replica_count will not be aborted.

**Comment by avikivity** [comment]
@asias should this be backported? (is this a response to a problem in the field?)

**Comment by asias** [comment]
> @asias should this be backported? (is this a response to a problem in the field?)

Yes. I will send a PR for 2020.1 backport. Let's discuss there.

**Comment by avikivity** [comment]
Backported to 4.4, 4.5.
