### ISSUE TITLE
Exceptions in resharding and reshaping are being incorrectly swallowed

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#8657]
Scylla version (or git commit hash): 68f69671b5cec493b
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI):

With exceptions being swallowed, it could happen that a failure is interpreted as success in the upper layer. In resharding for example, shared sstables could be propagated to table which would lead to an abort as table no longer accept shared sst.

**Comment by slivne** [comment]
@raphaelsc please clarify which versions are suspect to this

**Comment by avikivity** [comment]
Backported to 4.3, 4.4, 4.5.
