### ISSUE TITLE
nonroot installation broken at 4.5.rc1

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#8663]
Tested with scylla-unified-package-4.5.rc1.0.20210418.4a78d6403.tar.gz on Vagrant CentOS7 VM, 

It seems like install command did not create target directory:
```
[vagrant@localhost unified]$ ./install.sh --nonroot
install: failed to access ‘/home/vagrant/.config/systemd/user’: No such file or directory
```
Once created ~/.config/systemd/user, install failed on next directory:
```
[vagrant@localhost unified]$ mkdir -p ~/.config/systemd/user
[vagrant@localhost unified]$ ./install.sh --nonroot
install: failed to access ‘/home/vagrant/scylladb//etc/sysconfig’: No such file or directory
```

I guess recent changes causing install command behavior, or we mistakenly changed option to pass install command.

**Comment by syuu1228** [comment]
Ah, this is happens because we have added scylla-node-exporter top of the install script, but haven't moved `install -d -m755 "$rsystemd"` and `install -d -m755 "$rsysconfdir"`.
So probably the bug introduced at https://github.com/scylladb/scylla/commit/95197a09c91eb719c252abed847b8c035f5f9600, may affect Scylla 4.4, 4.5 and master.

**Comment by syuu1228** [comment]
Verified the bug caused on Scylla 4.4.1:
``
[vagrant@localhost ~]$ cd unified/
[vagrant@localhost unified]$ tar xpf ~/scylla-unified-package-4.4.1.0.20210406.00da6b5e9.tar.gz
[vagrant@localhost unified]$ ./install.sh --nonroot
install: failed to access ‘/home/vagrant/.config/systemd/user’: No such file or directory
```

**Comment by syuu1228** [comment]
@amoskong I think you added unified installer testcase, did it happen on the test?

**Comment by syuu1228** [comment]
Ah, testing on CentOS7 was incorrect since this is about nonroot, but it won't be different on CentOS8 since it is bash script logic problem.

**Comment by amoskong** [comment]
> @amoskong I think you added unified installer testcase, did it happen on the test?

We didn't test nonroot offline installation of centos7  (unsupported), there is a problem of systemd
centos8 works well: https://jenkins.scylladb.com/job/scylla-4.5/job/artifacts-offline-install/job/artifacts-centos8-nonroot-test/

**Comment by avikivity** [comment]
Backported to 4.4, 4.5. 4.3 is okay since it predates the node_exporter change.
