### ISSUE TITLE
Support IDEs

### ISSUE THREAD

**Issue by jkozlowski** [scylladb/scylla#867]
I was wondering if you could support generating IDE project files (Visual Studio/Eclipse etc.), as opposed to just Ninja? From my quick research, tools like https://gyp.gsrc.io/ or maybe even http://www.biicode.com/ could be used to describe the build, from which you could generate a nija or IDE specific build files. Could you also comment on what does your team use for development?

I think this could seriously improve your contributor story for quickly getting started. We have thought about evaluating scylladb as an alternative to Cassandra, but not being able to quickly jump into source code when something goes wrong would make me worried about suggesting scylladb.

**Comment by avikivity** [comment]
I am using Eclipse and configuring it manually.  Auto-generated IDE configuration would be very welcome.

**Comment by jkozlowski** [comment]
Thanks for a quick reply. Would you mind providing some instructions (they could go onto your README.md maybe?), or maybe commit them to the repo in some non-critical place?

**Comment by nyh** [comment]
I don't think the IDE problem is how to **compile** the system, it's not that bad to edit the project in Eclipse but then compile it by running "ninja".

But I do agree we have a big problem with configuring Eclipse to properly **edit** (not compile) Seastar and Scylla. Eclipse is really bad out-of-the-box on editing C++11 code, and even worse for C++14 code: @avikivity has some private Eclipse patches to fix some of these problems, but they don't fix everything, haven't been taken upstream, and still require a lot of non-trivial configuration.

I think we should start with a document explaining how to edit Scylla in Eclipse, and/or configuration files which can be imported into Eclipse. In the OSv project, we had such a document: https://github.com/cloudius-systems/osv/wiki/Working-With-Eclipse-CDT but sadly the configuration for Seastar/Scylla is even more complex, and I myself have never been able to fully configure it, and I just got used to see a lot of red lines on perfectly correct code :-(

**Comment by jkozlowski** [comment]
I would love to help out, but I am mostly a Java dev, just starting out with C++. With as large a project as scylladb I can't imagine not having an IDE with jump-to declaration, find usages etc.: navigating the code without it would be prohibitively expensive. I would really appreciate if someone from the team could provide some instructions and in general try to make the experience as smooth as possible.

We use Cassandra in production and the ability of any team member to be able to jump into the code quickly if we hit some weird edge case is invaluable.

**Comment by avikivity** [comment]
We do use IDEs, but we haven't automated project file generation.  Are there tools that help with this?

**Comment by gleb-cloudius** [comment]
On Tue, Feb 02, 2016 at 03:34:10AM -0800, nyh wrote:
> I think we should start with a document explaining how to edit Scylla in Eclipse, and/or configuration files which can be imported into Eclipse. In the OSv project, we had such a document: https://github.com/cloudius-systems/osv/wiki/Working-With-Eclipse-CDT but sadly the configuration for Seastar/Scylla is even more complex, and I myself have never been able to fully configure it, and I just got used to see a lot of red lines on perfectly correct code :-(
> 
No amount of configuration can overcome missing Eclipse features and
unfortunately it has quite a bit (templated lambdas, captures with
initializers, etc).

--
			Gleb.

**Comment by jkozlowski** [comment]
I have mentioned gyp (I think chromium uses it: I looked at it because they use ninja as well), but I don't know how good it is. biicode is interesting, because it also handles installing dependencies.

**Comment by nyh** [comment]
It's pretty easy to get to the state where you can open Scylla in Eclipse and jump to specific functions, because Eclipse doesn't need to understand all the latest C++14 trickery to do this properly. You can just open a new project, tell it the Scylla source directory, and hopefully, everything will work for you.

But it's a whole other ball-game if you want to Eclipse's support to be "perfect", i.e., every line of code is recognized, no syntax errors are shown where they don't exist, etc. @avikivity has mastered the ability to do this, but I think the closest thing we have to a document on how to do this is https://github.com/cloudius-systems/osv/wiki/Working-With-Eclipse-CDT - which is outdated, and referred to a simpler (no C++14) project.

In any case, like Gleb said, Eclipse CDT has some annoying holes in its C++14 support, and it doesn't seem (as far as I know) that anybody is working on fixing these holes, or making it easier to edit C++14 (or even C++11) out of the box in Eclipse, which is sad. Apparently, the big market for Eclipse is for Java developers, not C++ developers :-(

**Comment by tgrabiec** [comment]
I use CLion. It's far from perfect. It also doesn't support C++14 yet, so I get a lot of false positives from the syntax checker. But it's bearable.

If anyone's interested, here's my CMakeLists.txt: https://gist.github.com/tgrabiec/3d923ec8c1f970860615

**Comment by erichkeane** [comment]
It would be cool to have a .ycm_extra_conf.py file available too!  I haven't had a chance yet, but one of those would make my development a heck of a lot easier.

YouCompleteMe + Fugitive + vim is a pretty solid dev environment if you're willing to use the vim keybindings.  

That said, I hear really good things about CodeBlocks as well for C++14 support.  Finally, perhaps consider Qt Creator?  The config files are a bit of a pain, but the IDE is likely the most advanced available for the Linux C++ platform.

**Comment by jkozlowski** [comment]
Finally got time to read some code, @tgrabiec thanks for the CMakeLists.txt works fairly well, I am able to browse the code now.

**Comment by benoit-canet** [comment]
On Tue, Feb 2, 2016 at 5:14 PM, Erich Keane <notifications@github.com>
wrote:

> It would be cool to have a .ycm_extra_conf.py file available too! I
> haven't had a chance yet, but one of those would make my development a heck
> of a lot easier.
>
> YouCompleteMe + Fugitive + vim is a pretty solid dev environment if you're
> willing to use the vim keybindings.
>
Thanks for the tip YouCompleteMe is nice. I think I finally reached year 2k
;)

**Comment by avikivity** [comment]
With `CMakeLists.txt` IDEs are supported now.
