### ISSUE TITLE
Ninja build feature request: Set packages to be created with architecture name

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla#8675]
As we want to support both Arm and existing x86, we will have a package for each architecture. Such as 
- scylla-package.tar.gz
- scylla-unified-package-4.6.dev.0.20210513.68f69671b5.tar.gz
- scylla-debug-package.tar.gz
- scylla-debug-unified-package-4.6.dev.0.20210513.68f69671b5.tar.gz
- scylla-python3-package.tar.gz

We need to know which package is for which architecture.

Please set the package name to contain the architecture, such as
- scylla-architecture-package.tar.gz
- scylla-architecture-unified-package-4.6.dev.0.20210513.68f69671b5.tar.gz
- scylla-debug-architecture-package.tar.gz
- scylla-debug-architecture-unified-package-4.6.dev.0.20210513.68f69671b5.tar.gz
- scylla-python3-architecture-package.tar.gz

For now, I do it as a rename on pkg. Need to coordinate when this is done, so I'll remove the renames.
Also, need to set relocatable-package-based processes to take the needed architecture.

**Comment by syuu1228** [comment]
I agree we need this.
BTW. how about to add architecture name to the tail of the filename, such as <package name - version>.x86_64.tar.gz, it would be similar to .rpm, and easier to handle in shell (ex: ls *.x86_64.tar.gz).

**Comment by syuu1228** [comment]
Does frozen toolchain already enabled aarch64? Seems like at least fedora-33-20201027 has support it, but not sure on latest version (on latest master we use fedora-33-20201214 but strangely hub.docker.com does not shows up supported architecture on the version).
https://hub.docker.com/r/scylladb/scylla-toolchain/tags?page=1&ordering=last_updated

**Comment by syuu1228** [comment]
> Does frozen toolchain already enabled aarch64? Seems like at least fedora-33-20201027 has support it, but not sure on latest version (on latest master we use fedora-33-20201214 but strangely hub.docker.com does not shows up supported architecture on the version).
> https://hub.docker.com/r/scylladb/scylla-toolchain/tags?page=1&ordering=last_updated

I verified frozen toolchain works with aarch64.
It verified during Arm AMI building test, just succeed to run `./tools/toolchain/dbuild ninja-build` to produce .deb packages for the AMI.
 https://github.com/scylladb/scylla-machine-image/issues/137#issuecomment-860597890

**Comment by psarna** [comment]
Dequeued due to next failing

**Comment by avikivity** [comment]
Build only, not backporting.

**Comment by avikivity** [comment]
It means I'm not backporting the change to older branches.
