### ISSUE TITLE
Alternator's health-check request doesn't work properly with HTTPS

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8691]
When Alternator is configured to listen to HTTPS, the health-check service should work with HTTPS as well. This works in Amazon DynamoDB:
```
$ curl https://dynamodb.us-east-1.amazonaws.com
healthy: dynamodb.us-east-1.amazonaws.com
```
We have a unit test for this, but to run the test in HTTPS mode we need to do it explicitly, and we don't do it in Jenkins, so this appears to be a regression: `test/alternator/run --https test_health.py` now fails.  When running all tests on https (`test/alternator/run --https`), most pass, but we have all `test_health.py` tests fail, and also `test_cors.py` tests fail and `test_scylla.py`. We need to fix all of those!

Also noticed by @bhalevy in dtests: https://github.com/scylladb/scylla-dtest/pull/2138.

**Comment by nyh** [comment]
This is most likely a recent regression - the test test/alternator/run --https test_health.py passes on scylla-4.4.1. I'll do a git bisect now.

**Comment by nyh** [comment]
Bisection shows that the offending commit is f41dac2a3ae0b631b7381072dfc7d7fd03b3f1fb (by me):
```
commit f41dac2a3ae0b631b7381072dfc7d7fd03b3f1fb
Author: Nadav Har'El <nyh@scylladb.com>
Date:   Wed Mar 10 00:25:25 2021 +0200

    alternator: avoid large contiguous allocation for request body
```

**Comment by nyh** [comment]
It turns out that two Seastar bugs conspire to create this problem (@wmitros who's the expert in that new Seastar code):
1. Seastar's new "request body streaming" feature (https://github.com/scylladb/seastar/commit/4fa0e4b4394b6293555af197b1835418df80398a) recognizes when the application's request handler did not fully read its request's body, and marks the connection for closing as it can no longer be reused. However, in this case, we're talking about the health check which is a GET request with an **empty** body. Because our handler expects no body, it doesn't even try to read it. For some reason with normal HTTP, not reading the zero-length body was fine and the EOF was recognized, but with the HTTPS layer, the server doesn't know the unread body is already at the EOF. The handler would need to do a read to get that EOF on the content-length stream.
2. Although Scylla _can_ easily `skip_entire_stream()` in the health handler and fix this problem (I verified), and perhaps should, things should have worked even without it (except the unfortunate disconnection) - our response should have still be sent. I saw that we are setting up a response `_content`, but it is simply not sent to the client before the disconnection. This appears to be a Seastar bug.

Note that although we can circumvent both Seastar bugs in Scylla by simply using `skip_entire_stream()` in all Scylla's requests that don't care about the request body (including health check and error messages), I think it is still important to fix these two bugs in Seastar. The second is a straight bug, and the first is a performance problem - it causes an HTTPS server which only cares about GET and no bodies and never has anything in its body to not reuse connections - when it could (and would only need to close the connection if the client unexpectedly sends a body and the server doesn't read it).

**Comment by nyh** [comment]
I analyzed the second issue listed above and opened a Seastar issue https://github.com/scylladb/seastar/issues/906.

Note that although fixing that Seastar bug will solve **this** issue, fixing that issue alone is not enough. The test will start working, but we won't notice that the connection got closed without reason. To fix that remaining problem we must do one or two of the following (and if we do them, it circumvents https://github.com/scylladb/seastar/issues/906):
1. Scylla can do a `skip_entire_stream()` when it doesn't care about the body. This includes healthcheck, as well as error messages. If we do this, it will also solve another longstanding issue -  #8195.
2. We can fix Seastar's other issue (the first issue mentioned above) so that not reading an empty request body will be fine (if the request body is not empty, the connection will still be closed).

The fix for Seastar's `httpd.cc` other issue is easy - just change
```c++
                         if (!content_stream.eof()) {
                             _done = true;
                         }
```
to
```c++
                        return content_stream.read().then([this] (temporary_buffer<char> buf) {
                            if (!buf.empty()) {
                                _done = true;
                            }
                        });
```

**Comment by nyh** [comment]
I sent a patch to the Seastar mailing list, titled "httpd: allow handler to not read an empty content", fixing Seastar issue 907 and making all the broken HTTPS tests involving empty request bodies to work again.

**Comment by nyh** [comment]
I confirmed that the Alternator tests with HTTPS work on master now. Thanks @avikivity for the commits.
As I mentioned above, we still need to backport the Seastar patch to 4.5, but not to earlier branches (since this is a recent regression).

**Comment by avikivity** [comment]
Backported to 4.5.

**Comment by nyh** [comment]
Thanks @avikivity !
