### ISSUE TITLE
CQL Drop Keyspace / CQL Drop Table

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#87]

**Comment by penberg** [comment]
DROP TABLE is implemented in commit bc1d159c1b20a846b1ae81256676b42232527feb.

**Comment by slivne** [comment]
@penberg - I think you sent patches for DROP KEYSPACE as well - can you please update the issue and specify if we can close it

**Comment by penberg** [comment]
DROP KEYSPACE was added in commit 75dd123d01b7817ea5a7a0b42ad45c4537300a6b. I'm closing this issue.
