### ISSUE TITLE
repairing table with TWCS makes compaction a lot

### ISSUE THREAD

**Issue by 0xF0D0** [scylladb/scylla#8710]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.4.2
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): docker image(centos)

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory=
Disks: (SSD/HDD, count)

I'm using Scylla opensource 4.4.2

I ran `nodetool repair -pr` on one node and suddenly Compaction went so high and I had to force stop it.
![image](https://user-images.githubusercontent.com/7742751/119645799-64f3d400-be59-11eb-8104-67f9a9ff1803.png)

Here is some log when repair was in progress
```
 2021-05-26 07:32:51,341 [shard 3] storage_proxy - Exception when communicating with 10.15.49.178, to read from x.x_scylla_cdc_log: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
ERROR 2021-05-26 07:32:51,341 [shard 3] storage_proxy - Exception when communicating with 10.15.49.178, to read from x.x_scylla_cdc_log: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
ERROR 2021-05-26 07:32:51,341 [shard 3] storage_proxy - Exception when communicating with 10.15.49.178, to read from x.x_scylla_cdc_log: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
ERROR 2021-05-26 07:32:51,342 [shard 3] storage_proxy - Exception when communicating with 10.15.49.178, to read from x.x_scylla_cdc_log: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
ERROR 2021-05-26 07:32:51,342 [shard 3] storage_proxy - Exception when communicating with 10.15.49.178, to read from x.x_scylla_cdc_log: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
ERROR 2021-05-26 07:32:51,342 [shard 3] storage_proxy - Exception when communicating with 10.15.49.178, to read from x.x_scylla_cdc_log: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
ERROR 2021-05-26 07:32:51,342 [shard 3] storage_proxy - Exception when communicating with 10.15.49.178, to read from x.x_scylla_cdc_log: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
ERROR 2021-05-26 07:32:51,342 [shard 3] storage_proxy - Exception when communicating with 10.15.49.178, to read from x.x_scylla_cdc_log: seastar::named_semaphore_timed_out (Semaphore timed out: _read_concurrency_sem)
ERROR 2021-05-26 07:32:51,343 [shard 3] storage_proxy - Exception when communicating with 10.15.49.178, to read from ```

one weird thing is that `10.15.49.178` this IP indicates the node itself trying to run repair

**Comment by bhalevy** [comment]
@raphaelsc @asias please look into this

**Comment by raphaelsc** [comment]
@0xF0D0 what's the number of cores and tables? please share schema. please also share that same graph but the whole one instead.

**Comment by raphaelsc** [comment]
@0xF0D0 please upload the logs from the moment you scylla was initialized.

**Comment by raphaelsc** [comment]
@0xF0D0 i can't see in the graph the amount of compactions. please send it again without cutting the edges.

**Comment by 0xF0D0** [comment]
here's the full log
[problem_log.log](https://github.com/scylladb/scylla/files/6551286/problem_log.log)

**Comment by 0xF0D0** [comment]
here's compaction graph
![image](https://user-images.githubusercontent.com/7742751/119770904-ce2a2480-bef7-11eb-98c1-9e4424c207bc.png)

**Comment by raphaelsc** [comment]
found the problem, patch sent: https://groups.google.com/g/scylladb-dev/c/wZtK6ZxhJQU

**Comment by slivne** [comment]
@raphaelsc it seems that the referenced patch  55a8b6e is in  scylla > 4.1.0 - please confirm its needed for all versions that have this patch

**Comment by avikivity** [comment]
I'd like to backport, but we need some QA feedback that it doesn't cause regressions.

**Comment by raphaelsc** [comment]
> @raphaelsc it seems that the referenced patch [55a8b6e](https://github.com/scylladb/scylla/commit/55a8b6e3c9b35e248b5d9b668b49697777b8882d) is in scylla > 4.1.0 - please confirm its needed for all versions that have this patch

confirmed.

**Comment by raphaelsc** [comment]
> I'd like to backport, but we need some QA feedback that it doesn't cause regressions.

@roydahan please help us with this.

**Comment by avikivity** [comment]
@raphaelsc what's the impact? Sure, those deletions happen in parallel, but aren't they lightweight and quick?

**Comment by raphaelsc** [comment]
On Mon, Jun 7, 2021 at 4:50 AM Avi Kivity ***@***.***> wrote:
>
> @raphaelsc what's the impact? Sure, those deletions happen in parallel, but aren't they lightweight and quick?

I am more worried about the impact of parallel sstable list rebuilds
on older versions (<= 4.3) which can suffer with stalls there (the fix
for stalls in sst list rebuild is more dangerous than this fix
itself), so latency can be significantly impacted. The impact is
minimized though by the fact that rebuild is serialized through cache
invalidation procedure. However, if the user has many tables, the
impact wouldn't be minimized.

**Comment by avikivity** [comment]
@roydahan ping

**Comment by roydahan** [comment]
On master we didn't saw any regressions in this area.
(However FWIW, our test couldn't reproduce the original issue).

**Comment by avikivity** [comment]
I'm mostly interested in not hurting other loads.

**Comment by avikivity** [comment]
Backported to 4.3, 4.4, 4.5.
