### ISSUE TITLE
decommissioned_wiped_node_can_join_test: Missing: ['127.0.66.4 is now (dead|DOWN)']

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8712]
The dtest started failing in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/824/testReport/bootstrap_test/TestBootstrap/decommissioned_wiped_node_can_join_test/
Scylla version 948e2c0b36fa35c4c471ba01b00babb6ed2550fd
```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/bootstrap_test.py", line 484, in decommissioned_wiped_node_can_join_test
    node4.stop(wait_other_notice=True)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 844, in stop
    self.wait_until_stopped(wait_seconds, marks, dump_core=gently)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/scylla_node.py", line 813, in wait_until_stopped
    node.watch_log_for_death(self, from_mark=mark)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 509, in watch_log_for_death
    self.watch_log_for(tofind, from_mark=from_mark, timeout=timeout, filename=filename)
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-ccm/ccmlib/node.py", line 483, in watch_log_for
    [e.pattern for e in tofind]) + ":\n" + reads[:50] + ".....\nSee {} for remainder".format(filename))
ccmlib.node.TimeoutError: 24 May 2021 22:37:36 [node1] Missing: ['127.0.66.4 is now (dead|DOWN)']:
```

I guess it could have been caused by 425e3b11827ab5db6d68024134233e85064c7f74

@asias please look into this

**Comment by bhalevy** [comment]
Please also analyse the following failures that start at the same run to see if they have the same root cause:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/824/testReport/replace_address_test/

Only 3 of them failed in the next run:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/825/testReport/replace_address_test/

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/825/testReport/replace_address_test/TestReplaceAddress_rbo_disabled/replace_first_boot_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/825/testReport/replace_address_test/TestReplaceAddress_rbo_disabled/replace_stopped_node_test/
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/825/testReport/replace_address_test/TestReplaceAddress_rbo_enabled/replace_stopped_node_test/

**Comment by asias** [comment]
I will take a look.

**Comment by asias** [comment]
> Please also analyse the following failures that start at the same run to see if they have the same root cause:
> 
> https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/824/testReport/replace_address_test/
> 
> Only 3 of them failed in the next run:
> 
> https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/825/testReport/replace_address_test/
> 
> https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/825/testReport/replace_address_test/TestReplaceAddress_rbo_disabled/replace_first_boot_test/
> https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/825/testReport/replace_address_test/TestReplaceAddress_rbo_disabled/replace_stopped_node_test/
> https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/825/testReport/replace_address_test/TestReplaceAddress_rbo_enabled/replace_stopped_node_test/

The replace issues above are dtest issue. With the fix https://github.com/scylladb/scylla-dtest/pull/2160 here. The test passes for me.

**Comment by asias** [comment]
dtest fix:  https://github.com/scylladb/scylla-dtest/pull/2165
scylla fix: https://github.com/scylladb/scylla/pull/8770
