### ISSUE TITLE
Wrong error message when attempting index of UDT column with a duration

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8724]
It is forbidden to create a secondary index of a column which includes in any way the "duration" type. This includes a tuple of duration, and a UDT which including duration.

The code in `create_index_statement::validate` attempts to print useful error messages explaining what bad type the user used, but when it sees a UDT including a duration, it incorrectly reports "Secondary indexes are not supported on tuples containing durations". Cassandra reports the correct error message in this case: "Secondary indexes are not supported on UDTs containing durations".

This minor annoyance was discovered by the translated Cassandra unit test `cassandra_tests/validation/entities/secondary_index_test.py::testIndexOnDurationColumn `.

**Comment by avikivity** [comment]
Minor error message fix, not backporting.
