### ISSUE TITLE
Adapt the "waiting until hints are replayed before repair" feature into an HTTP API

### ISSUE THREAD

**Issue by piodul** [scylladb/scylla#8727]
In PR #8452, a feature was introduced which causes repairs to wait until hints between nodes participating in repair are replayed. Now, each repair operation requires (if an option in the configuration is set to true - which is the default) all hints to be sent between repaired nodes.

However, the problem with that design is that hints are aggregated per endpoint, but repair is more granular than that. Each repair operation on the Scylla side works on a single keyspace, and can be refined even further with user options to work only on a subset of tables from that keyspace and/or a particular set of token ranges. Ideally, we would prioritize sending hints belonging to those keyspaces/tables/ranges, but it would require hints to be stored in a significantly different way and this reorganization may require a lot of effort.

Instead, we can expose the hint waiting functionality as a new HTTP API. While it does not fully solve the issues described above, it has the following benefits:

- It makes it easier to choose for users if they want hints to be replayed or not before repair. Now, the `wait_for_hint_replay_before_repair` configuration option needs to be changed and reloaded in order to achieve this, which can be cumbersome.
- It can be used in contexts outside repair, e.g. @vladzcloudius mentioned that it would be useful for flushing hints before increasing `gc_grace_seconds`.
- It still would be possible to trigger it automatically when `nodetool repair` is used - for example, when repair of all keyspaces was requested. It would be better from what we have now because `nodetool repair` issues a separate repair operation for each requested keyspace, and now we wait for hints to be replayed before every such operation (although subsequent wait operations after the first should usually finish very quickly).

The idea was originally suggested by @asias and discussed under the PR which introduced waiting before repair ([link](https://github.com/scylladb/scylla/pull/8452#issuecomment-833160267))

**Comment by avikivity** [comment]
Feature, not bug, so not backporting.
