### ISSUE TITLE
replace nodes are (at times) left in system.peers table - they need to be removed

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#8729]
We have seen two cases in which replaced nodes are left in the system.peers table of other nodes in the cluster.

This causes issues later as they effect the outcome of the supported features in the cluster - and may cause other issues as well.

In the specific case we had the issue was that feature flags were computed incorrectly and as such the schema could not be synched.

Need to find the source and remove them.

**Comment by slivne** [comment]
One possibility is to add an asssert and see if we can catch this in our testing that QA run.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
