### ISSUE TITLE
LWT prepare,write step failed, two nodes failed to write for a long time.

### ISSUE THREAD

**Issue by shoshan** [scylladb/scylla#8731]
*Installation details*
Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.5.rc2-0.20210525.44f85d2ba`
Cluster size: 4 nodes (i3.2xlarge)
Scylla running with shards number (live nodes):
   longevity-lwt-3h-4-5-db-node-057dc0fd-1 (13.51.176.39 | 10.0.0.160): 8 shards
   longevity-lwt-3h-4-5-db-node-057dc0fd-2 (13.53.74.133 | 10.0.3.22): 8 shards
   longevity-lwt-3h-4-5-db-node-057dc0fd-3 (13.48.24.112 | 10.0.0.72): 8 shards
   longevity-lwt-3h-4-5-db-node-057dc0fd-4 (13.51.234.223 | 10.0.1.54): 8 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0e8308f9060d1b303` (aws: eu-north-1)

Test: `longevity-lwt-3h-test`
Test name: `longevity_lwt_test.LWTLongevityTest.test_lwt_longevity`
Test config file(s):
- [longevity-lwt-basic-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/bddb74c85d77db6901179aa9b244456cf7aca521/test-cases/longevity/longevity-lwt-basic-3h.yaml)

LWT prepare,write step failed, two nodes failed to write for a long time.

====================================
write failure report by loader log 
```
02:27:43.860 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.0.160:9042-1, inFlight=0, closed=false] was inactive for 30 seconds, sending heartbeat
02:27:43.861 [cluster1-nio-worker-0] DEBUG com.datastax.driver.core.Connection - Connection[/10.0.0.160:9042-1, inFlight=0, closed=false] heartbeat query succeeded
total,        118484,    6559,    6559,    6559,     4.5,     3.7,     7.2,    17.5,    83.1,   116.7,   19.0,  0.02253,      0,      0,       0,       0,       0,       0
total,        125447,    6963,    6963,    6963,     4.2,     3.9,     7.0,     9.1,    17.8,    23.4,   20.0,  0.02143,      0,      0,       0,       0,       0,       0
com.datastax.driver.core.exceptions.WriteTimeoutException: Cassandra timeout during CAS write query at consistency SERIAL (2 replica were required but only 1 acknowledged the write)

```

Node 1 reports on write failure
```
May 26 02:40:07 longevity-lwt-3h-4-5-db-node-057dc0fd-1 scylla[9001]:  [shard 7] storage_proxy - Failed to apply mutation from 10.0.3.22#7: exceptions::mutation_write_timeout_exception (Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE.) 
```

Node 2 report on write failure
```
May 26 02:40:25 longevity-lwt-3h-4-5-db-node-057dc0fd-2 scylla[10428]:  [shard 4] rpc - client 10.0.0.160:61540 msg_id 453457:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored                                                                       
May 26 02:40:25 longevity-lwt-3h-4-5-db-node-057dc0fd-2 scylla[10428]:  [shard 4] rpc - client 10.0.0.72:60684 msg_id 438097:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored                                                                        
May 26 02:40:25 longevity-lwt-3h-4-5-db-node-057dc0fd-2 scylla[10428]:  [shard 4] rpc - client 10.0.0.72:60684 msg_id 438101:  exception "Operation timed out for system.paxos - received only 0 responses from 1 CL=ONE." in no_wait handler ignored 

```

I did not find suspicious log lines from node 3 log. 

====================================

Restore Monitor Stack command: `$ hydra investigate show-monitor 057dc0fd-0510-4a06-a862-d709c53fa2fb`
Show all stored logs command: `$ hydra investigate show-logs 057dc0fd-0510-4a06-a862-d709c53fa2fb`

Test id: `057dc0fd-0510-4a06-a862-d709c53fa2fb`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/057dc0fd-0510-4a06-a862-d709c53fa2fb/20210526_070054/grafana-screenshot-longevity-lwt-3h-test-scylla-per-server-metrics-nemesis-20210526_070503-longevity-lwt-3h-4-5-monitor-node-057dc0fd-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/057dc0fd-0510-4a06-a862-d709c53fa2fb/20210526_070054/grafana-screenshot-longevity-lwt-3h-test-scylla-per-server-metrics-nemesis-20210526_070503-longevity-lwt-3h-4-5-monitor-node-057dc0fd-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/057dc0fd-0510-4a06-a862-d709c53fa2fb/20210526_070909/db-cluster-057dc0fd.zip](https://cloudius-jenkins-test.s3.amazonaws.com/057dc0fd-0510-4a06-a862-d709c53fa2fb/20210526_070909/db-cluster-057dc0fd.zip)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/057dc0fd-0510-4a06-a862-d709c53fa2fb/20210526_070909/loader-set-057dc0fd.zip](https://cloudius-jenkins-test.s3.amazonaws.com/057dc0fd-0510-4a06-a862-d709c53fa2fb/20210526_070909/loader-set-057dc0fd.zip)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/057dc0fd-0510-4a06-a862-d709c53fa2fb/20210526_070909/monitor-set-057dc0fd.zip](https://cloudius-jenkins-test.s3.amazonaws.com/057dc0fd-0510-4a06-a862-d709c53fa2fb/20210526_070909/monitor-set-057dc0fd.zip)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/057dc0fd-0510-4a06-a862-d709c53fa2fb/20210526_070909/sct-runner-057dc0fd.zip](https://cloudius-jenkins-test.s3.amazonaws.com/057dc0fd-0510-4a06-a862-d709c53fa2fb/20210526_070909/sct-runner-057dc0fd.zip)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.5/job/longevity/job/longevity-lwt-3h-test/15/)

**Comment by roydahan** [comment]
Dup of #8270
