### ISSUE TITLE
dist: ubuntu setup of network 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#874]
on ubuntu 14.04 on rackspace (baremetal)

using scylla 0.16

Running a load from another server

I am seeing

```
Feb  4 14:32:56 sl-ubuntu-14 /usr/sbin/irqbalance: irq 198 affinity_hint subset empty
Feb  4 14:32:56 sl-ubuntu-14 /usr/sbin/irqbalance: irq 199 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 129 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 130 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 131 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 132 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 133 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 134 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 135 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 136 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 137 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 138 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 149 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 150 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 151 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 152 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 153 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 154 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 155 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 156 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 157 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 158 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 170 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 171 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 172 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 173 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 174 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 175 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 176 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 177 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 178 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 179 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 190 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 191 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 192 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 193 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 194 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 195 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 196 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 197 affinity_hint subset empty
Feb  4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 198 affinity_hint subset empty
```

Tried running posix_net_conf.sh bond0.401 -mq (although its not packaged on ubuntu) hoping it "fix" this yet it did not "fix" it.

**Comment by vladzcloudius** [comment]
On 02/04/2016 04:36 PM, slivne wrote:
>
> on ubuntu 14.04 on rackspace (baremetal)
>
> using scylla 0.16
>
> Running a load from another server
>
> I am seeing
>
> |Feb 4 14:32:56 sl-ubuntu-14 /usr/sbin/irqbalance: irq 198 
> affinity_hint subset empty Feb 4 14:32:56 sl-ubuntu-14 
> /usr/sbin/irqbalance: irq 199 affinity_hint subset empty Feb 4 
> 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 129 affinity_hint 
> subset empty Feb 4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 130 
> affinity_hint subset empty Feb 4 14:33:06 sl-ubuntu-14 
> /usr/sbin/irqbalance: irq 131 affinity_hint subset empty Feb 4 
> 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 132 affinity_hint 
> subset empty Feb 4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 133 
> affinity_hint subset empty Feb 4 14:33:06 sl-ubuntu-14 
> /usr/sbin/irqbalance: irq 134 affinity_hint subset empty Feb 4 
> 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 135 affinity_hint 
> subset empty Feb 4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 136 
> affinity_hint subset empty Feb 4 14:33:06 sl-ubuntu-14 
> /usr/sbin/irqbalance: irq 137 affinity_hint subset empty Feb 4 
> 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 138 affinity_hint 
> subset empty Feb 4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 149 
> affinity_hint subset empty Feb 4 14:33:06 sl-ubuntu-14 
> /usr/sbin/irqbalance: irq 150 affinity_hint subset empty Feb 4 
> 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 151 affinity_hint 
> subset empty Feb 4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 152 
> affinity_hint subset empty Feb 4 14:33:06 sl-ubuntu-14 
> /usr/sbin/irqbalance: irq 153 affinity_hint subset empty Feb 4 
> 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 154 affinity_hint 
> subset empty Feb 4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 155 
> affinity_hint subset empty Feb 4 14:33:06 sl-ubuntu-14 
> /usr/sbin/irqbalance: irq 156 affinity_hint subset empty Feb 4 
> 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 157 affinity_hint 
> subset empty Feb 4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 158 
> affinity_hint subset empty Feb 4 14:33:06 sl-ubuntu-14 
> /usr/sbin/irqbalance: irq 170 affinity_hint subset empty Feb 4 
> 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 171 affinity_hint 
> subset empty Feb 4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 172 
> affinity_hint subset empty Feb 4 14:33:06 sl-ubuntu-14 
> /usr/sbin/irqbalance: irq 173 affinity_hint subset empty Feb 4 
> 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 174 affinity_hint 
> subset empty Feb 4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 175 
> affinity_hint subset empty Feb 4 14:33:06 sl-ubuntu-14 
> /usr/sbin/irqbalance: irq 176 affinity_hint subset empty Feb 4 
> 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 177 affinity_hint 
> subset empty Feb 4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 178 
> affinity_hint subset empty Feb 4 14:33:06 sl-ubuntu-14 
> /usr/sbin/irqbalance: irq 179 affinity_hint subset empty Feb 4 
> 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 190 affinity_hint 
> subset empty Feb 4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 191 
> affinity_hint subset empty Feb 4 14:33:06 sl-ubuntu-14 
> /usr/sbin/irqbalance: irq 192 affinity_hint subset empty Feb 4 
> 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 193 affinity_hint 
> subset empty Feb 4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 194 
> affinity_hint subset empty Feb 4 14:33:06 sl-ubuntu-14 
> /usr/sbin/irqbalance: irq 195 affinity_hint subset empty Feb 4 
> 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 196 affinity_hint 
> subset empty Feb 4 14:33:06 sl-ubuntu-14 /usr/sbin/irqbalance: irq 197 
> affinity_hint subset empty Feb 4 14:33:06 sl-ubuntu-14 
> /usr/sbin/irqbalance: irq 198 affinity_hint subset empty |
>
> Tried running posix_net_conf.sh bond0.401 -mq (although its not 
> packaged on ubuntu) hoping it "fix" this yet it did not "fix" it.
>

Note that the interface u r using is a bonding interface. As far as I 
know bonding interfaces don't have their own "IRQ"'s therefore running 
the script above for the bonding interface is pointless.
Secondly, the above message comes from irqbalance script which is a part 
of a Linux distribution. And the first link in the google search for 
"|affinity_hint subset empty|" 
(https://bugs.launchpad.net/ubuntu/+source/irqbalance/+bug/1321425) has 
a temporary fix for this issue.

I propose we ignore this and close this issue.

**Comment by slivne** [comment]
Ok
