### ISSUE TITLE
Default scylla.yaml should be consistent on which address it listens on

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8757]
Running Scylla with the default scylla.yaml results with the following listens:
```
tcp        0      0 127.0.0.1:19042
tcp        0      0 127.0.0.1:10000
tcp        0      0 127.0.0.1:9042
tcp        0      0 127.0.0.1:7000
tcp        0      0 0.0.0.0:9180
```
It doesn't make sense that all ports are open just on localhost by default except the metrics (port 9180). It should also default to localhost like all the rest - not to INADDR_ANY.

For me, the biggest annoyance with this default is that while you run Scylla with this default, you cannot run `test/cql-pytest/run` in parallel - because it tries to open port 9180 on a random IP address and can't because the running Scylla took this port on _all_ IP addresses.

@amnonh is there a deliberate reason why the metrics port is differently set up in the developer's scylla.yaml, or it's just historical accident?
CC @avikivity this is the problem that bothers you with running cql-pytest.

**Comment by nyh** [comment]
I see this unique default of the prometheus port is documented in scylla.yaml:
```
# prometheus address
# By default, Scylla binds all interfaces to the prometheus API
# It is possible to restrict the listening address to a specific one
# prometheus_address: 0.0.0.0
```
My question is whether these is some deliberate reason why the Prometheus service has a different default listening address from all others, or this is some historical mistake that I can correct now?

Another question is why scylla.yaml actively sets `listen_address`, `rpc_address`, `api_address` and all to localhost or 127.0.0.1 (yes, it's weirdly inconsistent) - but the setting of `prometheus_address` is commented out. Maybe this should be considered the mistake and this address too should be specified explicitly. On the other hand, I don't understand why we have scylla.yaml overriding one set of defaults (in the code) by a different set of defaults :-(

**Comment by nyh** [comment]
I sent already in May the following _one-line_ patch to the mailing list, titled "conf/scylla.yaml: change default Prometheus listen address". My patch deliberately fixed only `scylla.yaml` and not the defaults in the code, to guarantee that a user upgrading and keeping his existing `scylla.yaml` will not see anything changing. But still, some fears were raised in the discussion - https://groups.google.com/g/scylladb-dev/c/6CsoZIq_KBs/m/PQE0TCVuAwAJ - that other projects, notably Scylla Operator, might be generating a `scylla.yaml` by textually modifying Scylla's default one instead of generating one from scratch, and in this case, it's behavior will change. Because of this, my patch was not committed.

However, the problem was already fixed in Scylla Operator - see https://github.com/scylladb/scylla-operator/issues/622 - it now explicitly sets the IP addresses which it didn't instead of relying on Scylla's development `scylla.yaml`.

Since then more developers, including @kostja, have been hitting this annoyance when running Scylla manually and then trying to run tests (e.g., test/cql-pytest/run) in parallel.
Let's fix it once and for all.

```patch
Developers often run Scylla with the default conf/scylla.yaml provided
with the source distribution. The existing default listens for all ports
but one (19042, 10000, 9042, 7000) on the *localhost* IP address (127.0.0.1).
But just one port - 9180 (Prometheus metrics) - is listened on 0.0.0.0.
This patch changes the default to be 127.0.0.1 for port 9180 as well.

Note that this just changes the default scylla.yaml - users can still
choose whatever listening address they want by changing scylla.yaml
and/or passing command line parameters.

The benefits of this patch are:
1. More consistent.
2. Better security for developers (don't open ports on external
   addresses while testing).
3. Allow test/cql-pytest/run to run in parallel with a default run of
   Scylla (currently, it fails to run Scylla on a random IP address,
   because the default run of Scylla already took port 9180 on all IP
   addresses.

The third benefit is what led me to write this patch. Fixes #8757.

Signed-off-by: Nadav Har'El <nyh@scylladb.com>
---
 conf/scylla.yaml | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/conf/scylla.yaml b/conf/scylla.yaml
index 4750cd90e..d53d2c2c2 100644
--- a/conf/scylla.yaml
+++ b/conf/scylla.yaml
@@ -492,7 +492,7 @@ commitlog_total_space_in_mb: -1
 # prometheus address
 # By default, Scylla binds all interfaces to the prometheus API
 # It is possible to restrict the listening address to a specific one
-# prometheus_address: 0.0.0.0
+prometheus_address: localhost

 # Distribution of data among cores (shards) within a node
 #
```

**Comment by amnonh** [comment]
@nyh have you tested this? it seems that you moved the address from the default to force it to localhost, e.g. bye-bye metrics collection

While things like API should be restricted by default to the local host for security reasons, stopping the metrics collection is a huge change that I doubt many will appriciate.
maybe it works differently by taken the address from command line, if not, the future is not great

**Comment by nyh** [comment]
I don't think there's a reason to backport this patch, which was aimed at developers who use the default configuration.
Note that if anyone still considers backporting the patch for this, don't forget to also backport the followup patch for issue #9701.
