### ISSUE TITLE
Block decommission if there is no available disk space to complete it

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#8758]
*Installation details*
Scylla version (or git commit hash): 4.x

When a user initiates a downscale using [ndoetool decommission](https://docs.scylladb.com/operating-scylla/nodetool-commands/decommission/), he needs first to check if there is enough disk space on the other nodes to allow such action. This is already documented on the decommission page:

"WARNING
Review current disk space utilization on existing nodes and make sure the amount of data streamed from the node being removed can fit into the disk space available on the remaining nodes. If there is not enough disk space on the remaining nodes, the removal of a node will fail. Add more storage to remaining nodes before starting the removal procedure."

This enchantment request is to automate this test as part of the nodetool operation.
As nodetool (and the API) have the full info on all node disk usage, it can evaluate and block an operation known to fail.
We can add a --force option for users brave enough to bypass this protection.

**Comment by amnonh** [comment]
#8748

**Comment by tzach** [comment]
Aha! closing this ticket, and copy the info there.
