### ISSUE TITLE
Unimplement grant/list/revoke does not return an explicit error message

### ISSUE THREAD

**Issue by benoit-canet** [scylladb/scylla#876]
The CQL parse error returned can be confusing for the user a proper
message should be returned.

How to reproduce: Use the dtest cql_additional_test that will be merged soon

**Comment by slivne** [comment]
@hakuch after we finish roles lets clear this one out

**Comment by hakuch** [comment]
This may be fixed in the large roles series that will land soon, but I'm not sure because I don't understand the bug itself. @benoit-canet, would you plain explain exactly what the problem is?

**Comment by hakuch** [comment]
@slivne, in the absence of additional information, can we close this?

**Comment by eliransin** [comment]
cql_additional_test is running for a long time now. We also implemented the roles interface.
closing.
