### ISSUE TITLE
Backlog of a Compacting SSTable isn't reduced properly, making compaction more aggressive

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#8768]
It was observed that as compaction progresses the backlog of compacting SSTables is being reduced very slowly, which causes shares to be higher than needed, and consequently compaction acts much more aggressively than it has to.

![backlog_out](https://user-images.githubusercontent.com/1409139/120237819-93dfc080-c232-11eb-9042-68114e285ea0.png)

The graph above shows the amount of backlog that is reduced from a SSTable being compacted. The red line denotes the total backlog of the SSTable, before it's selected for compaction. The expectation is that the more a SSTable is compacted the more backlog will be reduced from it. However, in the current implementation, it can be seen that the backlog to be reduced, from the SSTable being compacted, starts being inversely proportional to the amount of data already compacted.

**Comment by raphaelsc** [comment]
This problem clearly happens due to a bug in how the backlog formula for a given sstable is being implemented. I think I already found the root cause. I'll work on a fix.

**Comment by raphaelsc** [comment]
Backlog for a sstable is defined as:
```
Bi = Ei * log (T / Ei)

where Ei = Si - Ci (bytes left to be compacted)
    and Si = size of SStable
    and Ci = total bytes compacted
    and T = total size of table
```

by rewriting the formula as:
`    Bi = Ei * log (T) - Ei * log (Ei)`

the second term Ei * log (Ei) can be rewritten as:
```
    = (Si - Ci) * log (Ei)
    = Si * log (Ei) - Ci * log (Ei)
```

however, reading the code, I realized we're implemented the second term as:
`    = Si * log (Si) - Ci * log (Ei)`

given that Si > Ei, for a SSTable being compacted, the backlog will be higher than it should. we need to make sure implementation respects the formula for the problem to be fixed.

**Comment by raphaelsc** [comment]
the following table shows how the backlog of a SSTable being compacted behaves

```
sstable backlog (backlog before compaction starts): 332.193
%		current		fixed
1		328.878		328.871
2		325.578		325.549
3		322.293		322.227
4		319.023		318.905
5		315.768		315.583
6		312.529		312.261
7		309.306		308.939
8		306.099		305.617
9		302.908		302.295
10		299.734		298.974
11		296.576		295.652
12		293.436		292.33
13		290.314		289.008
14		287.209		285.686
15		284.122		282.364
16		281.054		279.042
17		278.005		275.72
18		274.975		272.398
19		271.964		269.076
20		268.974		265.754
21		266.003		262.432
23		260.125		255.788
25		254.333		249.145
27		248.63		242.501
29		243.021		235.857
31		237.511		229.213
33		232.102		222.569
35		226.801		215.925
37		221.613		209.281
39		216.543		202.638
41		211.599		195.994
44		204.431		186.028
47		197.587		176.062
50		191.096		166.096
53		184.996		156.131
56		179.329		146.165
59		174.145		136.199
62		169.507		126.233
66		164.307		112.946
70		160.452		99.6578
74		158.277		86.3701
78		158.275		73.0824
82		161.226		59.7947
87		171.224		43.1851
92		194.193		26.5754
97		255.322		9.96578

first column denotes compaction progress
```

can be clearly seen that backlog behaves as described above. with my fix, backlog of compacting sstable will behave exactly as we expect it to.

**Comment by raphaelsc** [comment]
The fix is a bit complex, but it was the best one I could come up up which will be easy to backport, find it below:

```
diff --git a/sstables/compaction_strategy.cc b/sstables/compaction_strategy.cc
index 7ec5554a5..61e705705 100644
--- a/sstables/compaction_strategy.cc
+++ b/sstables/compaction_strategy.cc
@@ -136,9 +136,19 @@ size_tiered_backlog_tracker::compacted_backlog(const compaction_backlog_tracker:
     inflight_component in;
     for (auto const& crp : ongoing_compactions) {
         auto compacted = crp.second->compacted();
-        auto effective_size = crp.first->data_size() - compacted;
+        auto si = crp.first->data_size();
+        auto ei = crp.first->data_size() - compacted;
         in.total_bytes += compacted;
-        in.contribution += compacted * log4(effective_size);
+        if (ei > 0) {
+            // When a sstable is added to tracker, it contributes a backlog of: Si * log(Si) (see add_sstable()).
+            // Given that sstable's backlog formula is Bi=(Si - Ci) * log(Ei), where Ei = Si - Ci,
+            // we need to subtract (Si * log(Si / (Si - Ci))) from (Si * log(Si)), to produce (Si * log(Si - Ci)) = Si * log(Ei).
+            // So by doing: Si * log(Si) - (Si * log(Si / Ei) + Ci * log(Ei)), we achieve Bi=(Si - Ci) * log(Ei).
+            in.contribution += (si * log4(double(si) / ei)) + compacted * log4(ei);
+        } else {
+            // If compacted = Si, let's subtract compacted * log(Si) from the sstable's backlog, such that its effective backlog is zero.
+            in.contribution += compacted * log4(si);
+        }
     }
     return in;
 }
```

A simpler fix would be about removing input SSTables from the backlog tracker in the beginning of compaction, so size_tiered_backlog_tracker would be instead patched as follow:
```
diff --git a/sstables/compaction_strategy.cc b/sstables/compaction_strategy.cc
index 7ec5554a5..f2b636f29 100644
--- a/sstables/compaction_strategy.cc
+++ b/sstables/compaction_strategy.cc
@@ -136,9 +136,13 @@ size_tiered_backlog_tracker::compacted_backlog(const compaction_backlog_tracker:
     inflight_component in;
     for (auto const& crp : ongoing_compactions) {
         auto compacted = crp.second->compacted();
-        auto effective_size = crp.first->data_size() - compacted;
-        in.total_bytes += compacted;
-        in.contribution += compacted * log4(effective_size);
+        auto si = crp.first->data_size();
+        auto ei = crp.first->data_size() - compacted;
+        if (ei > 0) {
+            in.total_bytes += compacted;
+            // As compacting sstables are removed from tracker in the beginning of compaction, their backlog (Bi = (Si - Ci) * log(Ei)) can be all implemented here.
+            in.contribution += (si - compacted) * log4(ei);
+        }
     }
     return in;
 }
@@ -147,11 +151,11 @@ double size_tiered_backlog_tracker::backlog(const compaction_backlog_tracker::on
     inflight_component partial = partial_backlog(ow);
     inflight_component compacted = compacted_backlog(oc);
 
-    auto effective_total_size = _total_bytes + partial.total_bytes - compacted.total_bytes;
+    auto effective_total_size = _total_bytes + partial.total_bytes + compacted.total_bytes;
     if ((effective_total_size <= 0)) {
         return 0;
     }
-    auto sstables_contribution = _sstables_backlog_contribution + partial.contribution - compacted.contribution;
+    auto sstables_contribution = _sstables_backlog_contribution + partial.contribution + compacted.contribution;
     auto b = (effective_total_size * log4(effective_total_size)) - sstables_contribution;
     return b > 0 ? b : 0;
 }
```

But please note that compaction.cc would have to be patched too to remove input sstables from tracker in the beginning, and readd them on failure. on success, we'd only tell tracker that sstable was successfully compacted, so it can be removed from list of compacting sstables. so this simpler fix perhaps is not interesting for backport as we want the fix to touch as little critical code as possible.

Tomorrow I'll send a formal patch to the mailing list.

**Comment by raphaelsc** [comment]
This bug can be clearly contributing to those recent user reports in which shares were unexpectedly high. Not the root cause though.

**Comment by raphaelsc** [comment]
![out](https://user-images.githubusercontent.com/1409139/120254044-4d548b00-c25f-11eb-8da3-8c204b7d00b5.png)

Generated a graph showing that backlog behavior is fixed with the patch above. Those sudden decreases in the current (broken)'s backlog is due to a bug (also fixed in the patch above) in the calculation at the exact moment input sstable is fully compacted, so log4(0) is called which produces -inf. Backlog doesn't go negative because 0 is the minimum allowed.

**Comment by bhalevy** [comment]
we can first apply the safer fix that can be backported and then follow up with the simplification.

**Comment by raphaelsc** [comment]
> we can first apply the safer fix that can be backported and then follow up with the simplification.

agreed.

**Comment by slivne** [comment]
this is not a regression AFAICT

**Comment by raphaelsc** [comment]
The graph below shows the benefits of switching the formula back into Ei * log (T / Si)

![backlog_out2](https://user-images.githubusercontent.com/1409139/123495186-06a54700-d5f9-11eb-9386-3fcf4dd8e4d3.png)

![backlog_out](https://user-images.githubusercontent.com/1409139/123495185-060cb080-d5f9-11eb-89f7-ed445729702a.png)

**Comment by avikivity** [comment]
More of a policy change than a bug fix, so not backporting.
