### ISSUE TITLE
scylla_setup error "Cannot allocate memory"

### ISSUE THREAD

**Issue by ecerichter** [scylladb/scylla#8769]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.4.2-0.20210520.93457807b
Cluster size: 1 node (for dev)
OS (RHEL/CentOS/Ubuntu/AWS AMI): either Centos 7 x64 and OEL 7 x64

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): VmWare 6.7U2
Hardware: (virtual) sockets=1 cores=4 hyperthreading=false memory=8GB
Disks: (SSD/HDD, count) Virtual disk, 

Running as root or as non root gives same error:

[root@dev-server ~]# scylla_setup
Skip any of the following steps by answering 'no'
Do you want to run check your kernel version?
Yes - runs a  script to verify that the kernel for this instance qualifies to run Scylla. No - skips the kernel check.
[YES/no]
ERROR 2021-05-31 20:21:18,260 seastar - : Cannot allocate memory
Please upgrade to a newer kernel version.
 see https://docs.scylladb.com/troubleshooting/error_messages/kb_fs_not_qualified_aio/ for details
Traceback (most recent call last):
  File "/opt/scylladb/scripts/libexec/scylla_setup", line 347, in <module>
    run('{}/scylla_kernel_check'.format(scriptsdir()), shell=True, check=True)
  File "/opt/scylladb/python3/lib64/python3.9/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '/opt/scylladb/scripts/scylla_kernel_check' returned non-zero exit status 1.
[root@dev-server ~]#
[root@dev-server ~]# scylla --version
4.4.2-0.20210520.93457807b

Kernel:
[root@dev-server ~]# uname -a
Linux dev-server 5.4.17-2102.201.3.el7uek.x86_64 #2 SMP Fri Apr 23 09:05:55 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux

Memory:
[root@dev-server ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:           7953        1053        5548           8        1351        6668
Swap:          2047           0        2047
[root@dev-server ~]#

Disk space:
[root@dev-server ~]# df -h
Sist. Arq.               Tam. Usado Disp. Uso% Montado em
devtmpfs                 3,9G     0  3,9G   0% /dev
tmpfs                    3,9G     0  3,9G   0% /dev/shm
tmpfs                    3,9G  9,0M  3,9G   1% /run
tmpfs                    3,9G     0  3,9G   0% /sys/fs/cgroup
/dev/mapper/centos-root   92G  9,3G   83G  11% /
/dev/mapper/centos-home  5,0G  124M  4,9G   3% /home
/dev/sda1               1014M  262M  753M  26% /boot
tmpfs                    796M     0  796M   0% /run/user/0

**Comment by avikivity** [comment]
Please run `strace -f -o /tmp/trace.txt /opt/scylladb/scripts/scylla_kernel_check` and attach `/tmp/trace.txt` here.

**Comment by slivne** [comment]
@ecerichter any update - I am closing this issue - if there is additional information please post and we will be happy to reopen and  work on this.

**Comment by ecerichter** [comment]
> Please run `strace -f -o /tmp/trace.txt /opt/scylladb/scripts/scylla_kernel_check` and attach `/tmp/trace.txt` here.

(see attached)

Disk:
[root@sc0b03db ~]# df -h
Sist. Arq.            Tam. Usado Disp. Uso% Montado em
devtmpfs               12G     0   12G   0% /dev
tmpfs                  12G  1,3M   12G   1% /dev/shm
tmpfs                  12G  1,2G   11G  11% /run
tmpfs                  12G     0   12G   0% /sys/fs/cgroup
/dev/mapper/ol-root    10G  545M  9,5G   6% /
/dev/mapper/ol-usr     10G  2,5G  7,6G  25% /usr
/dev/mapper/ol-dados  1,8T  582G  1,2T  34% /dados
/dev/sda1            1014M  298M  717M  30% /boot
/dev/mapper/ol-var     10G  4,2G  5,9G  42% /var
tmpfs                 2,4G     0  2,4G   0% /run/user/1000

(all using XFS filesystem, being /dados a database partition with 0.5 TB available)

Memory:
[root@sc0b03db ~]# free -m
              total        used        free      shared  buff/cache   available
Mem:          24091        2309         441       12423       21339        8948
Swap:         12095          15       12080

Kernel version:

[root@sc0b03db ~]# uname -a
Linux sc0b03db.simfrete.com 5.4.17-2102.201.3.el7uek.x86_64 #2 SMP Fri Apr 23 09:05:55 PDT 2021 x86_64 x86_64 x86_64 GNU/Linux

OS Version:
[root@sc0b03db ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)
[root@sc0b03db ~]# cat /etc/oracle-release
Oracle Linux Server release 7.9


Scylla version:

[root@sc0b03db ~]# yum info scylla
Plugins carregados: ulninfo
Pacotes instalados
Nome        : scylla
Arquitetura        : x86_64
Versão     : 4.4.3
Lançamento     : 0.20210609.bfafb8456
Tamanho        : 0.0
Repo        : installed
Do repositório   : scylla-4.4
Sumário     : Scylla is a highly scalable, eventually consistent, distributed, partitioned row DB.
URL         : http://www.scylladb.com/
Licença     : AGPLv3
Descrição : Scylla is a highly scalable, eventually consistent, distributed,
          : partitioned row DB.
          : This package installs all required packages for ScyllaDB,  including
          : scylla-server, scylla-jmx, scylla-tools, scylla-tools-core scylla-node-exporter.


Virtual machine running on VMWare 7.0U2 (Dell custom image w/drivers)
Hardware: Dell R440, 2 xeon, 128GB ram, 4 x 960 SSD enterprise on Raid 5 w/ Perc730p

Any additional info necessary, please let me know.

[trace.txt](https://github.com/scylladb/scylla/files/6781181/trace.txt)

**Comment by avikivity** [comment]
What's the value of `/proc/sys/vm/overcommit_memory`?

Is anything else running on that VM?

**Comment by ecerichter** [comment]
> What's the value of `/proc/sys/vm/overcommit_memory`?

vm.overcommit_ratio=85
vm.overcommit_memory=2

vm.swappiness=1

> 
> Is anything else running on that VM?

Yes, couple of PostgreSQL 13 databases.
Very low traffic and consume.

**Comment by ecerichter** [comment]
May be needed another ticket for this: your query bring me a question: does Scylla require/recomends kernel parameters (sysctl.conf/limits.conf - ex: for small, medium, and large installations)?

**Comment by ecerichter** [comment]
Reviewing requirements in page https://docs.scylladb.com/getting-started/system-configuration/#system-configuration-files-and-scripts

**Comment by ecerichter** [comment]
I've setup another VM for testing, and configured "overcommit_memory=1" (IMHO, which seems risky for database servers), and I confirm that kernel check pass without error.
I suppose this needs to be fixed or clarified on docs.
