### ISSUE TITLE
Extensions cannot remove themselves (regression)

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#8773]
In aa72a1c556d80ab8552769ca4e0f3ccbc38b0a88, when modifying extension handling in `cf_prop_defs` for cdc handling, the ability for an extension to _remove_ itself by returning null from create/parse function was lost, as existing extensions are always preserved. 

This breaks enterprise features. Fixed by filtering existing extensions by property keywords.

**Comment by avikivity** [comment]
Not fixing a user-visible bug, so not backporting.
