### ISSUE TITLE
Running Scylla from xfs on ram disk

### ISSUE THREAD

**Issue by kirillsc** [scylladb/scylla#878]
Hi, 

I was trying to test performance of Scylla by replacing SSDs with mounted ram partition. I was wondering if I am doing something wrong. This is what I do:

1. `sudo mount -t tmpfs -o sync -o size=10000m xfs /mnt/ram/`

2. After running `df` I can that the file system is XFS

> Filesystem       Size  Used Avail Use% Mounted on
> ...
> xfs              9.8G     0  9.8G   0% /mnt/ram

3. Now, after configuring Scylla to work in /mnt/ram and restarting it I am seeing the following error in logs: 

> Feb  5 15:11:50 *** scylla[39292]:  [shard 0] init - /mnt/ram/data is not on XFS. This is a non-supported setup, and performance is expected to be very bad.#012For better performance, placing your data on XFS-formatted directories is strongly recommended

Followed by another error

> Feb  5 15:11:52 *** scylla[39292]:  [shard 1] database - failed to write sstable: std::system_error (error system:22, Invalid argument)

Could you please advise if I am missing something in my setup.

Thank you.

**Comment by avikivity** [comment]
Duplicate #871, fixed yesterday.

**Comment by avikivity** [comment]
Maybe not an exact duplicate, need to verify

**Comment by avikivity** [comment]
Ok, it's not really xfs. `-t tmpfs` means the filesystem type is tmpfs.  It should work with the fixes from yesterday, but it's not xfs.
