### ISSUE TITLE
version page Copyright is out of date

### ISSUE THREAD

**Issue by lauranovich** [scylladb/scylla#8781]
In https://github.com/scylladb/scylla/blob/master/version.hh

it states

/*
 * Copyright (C) 2015 ScyllaDB
 */

Needs to be changed to 2021 and should be updated once a year.

**Comment by nyh** [comment]
Our tradition has always been that a source file gets the copyright date when it's first created, and then it is never updated.

I tend to think that this tradition is good enough (who cares about this year anyway?), and that updating all the files once a year is nothing more than a chore - although it can be automated with a script (with various degrees of sophistication - a simple script will just use this year, a sophisticated script can look at exactly which years this file was modified in git, and generate something like "Copyright (C) 2015-2018, 2020-2021").

Do you think it's important? Can you please explain why? Or do you have a reference to some style guide / lawer / whatever, recommending to update the copyright line?

**Comment by avikivity** [comment]
It's not important. We can adopt a new practice of using 2021-present. Perhaps we should update everything, since people usually copy copyright blurbs from other files.

**Comment by avikivity** [comment]
I queued a patch fixing all such occurances.
