### ISSUE TITLE
Requests with bogus request sizes may cause Scylla to hang

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#8798]
@piodul reported that a subtle bug in the Rust driver, which encodes the request size with wrong endianness, causes Scylla to hang - not only the particular session, but also makes it impossible to shut Scylla down gracefully. I'll investigate further and I'm creating this issue as a reminder to do so. Here's a patch which causes our Rust driver to become an attack tool:
```diff
diff --git a/scylla/src/frame/mod.rs b/scylla/src/frame/mod.rs
index 386e507..9dbd40c 100644
--- a/scylla/src/frame/mod.rs
+++ b/scylla/src/frame/mod.rs
@@ -65,7 +65,7 @@ impl SerializedRequest {
         data[4] = R::OPCODE as u8;
         let req_size = (data.len() - HEADER_SIZE) as u32;
-        data[5..9].copy_from_slice(&req_size.to_be_bytes());
+        data[5..9].copy_from_slice(&req_size.to_le_bytes());
         Ok(Self { data })
     }
```
<strike>Note: the bug is reported to occur more often with higher smp counts, >= 4.</strike> nvm, it reproduces just fine with smp==1.

**Comment by psarna** [comment]
Note: this code is reported to work fine on Scylla 4.3, but hang on 4.4

**Comment by psarna** [comment]
This bug is indirectly caused by the fact that refusing too large requests was fixed some time ago. In 4.3, only the header of the message was ignored, which ruined the stream for this session, because the rest of the bytes from this too-large request were interpreted as if they were new headers. This behavior was fixed, and now the whole request is (attempted to be) skipped. From logs it looks like Scylla fails to shut down gracefully after the CQL server tries  to skip a huge number of bytes - in this case, e.g. 922746880 - which is a bogus number, since it was sent with wrong endianness, and it's not followed by 922746880 valid bytes. I'll investigate further, since shutting down Scylla in the middle of skipping a huge amount of bytes should be possible, and right now it looks like it's not.

**Comment by nyh** [comment]
@psarna beyond the specific problem of the very large skip here, I think you discovered a general bug (that, if true, deserves a new issue) - that shutdown and also request-handling in general (why???) can hang if any of the request is stuck in the middle of a `skip()`.

In the case of this issue, this was a huge `skip()` so it's obvious why it may never finish. But I think that skip, even a small one, will not finish if the client (maliciously or accidentally) stops sending data in the middle of the skip.

The correct behavior is for `skip()` to notice when the stream is closed while it's waiting, and fail at that point. Shutting down Scylla should somehow close all its sockets so all the skip()s would be interrupted.

We also need to check that `read_exactly()` and similar functions don't have exactly the same problem... Scylla may be doing `read_exactly(8)` but the client only sends 7 bytes and then we will have the same hang problems?

**Comment by psarna** [comment]
Yes, this problem is general to `skip`, which is built on top of seastar's `read_some`. I haven't figured out **why** closing the socket does not cause `skip` to fail though... shouldn't it be realized during polling that the socket is no longer open and return `EBADF` or a similar error?

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
