### ISSUE TITLE
index_with_paging_test: querying an indexed columns issues one read per row

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#8799]
I observed this while investigating a timeout in debug mode in said test, after removing the execution stage from the read path (which somehow makes this test time out -- still investigating why).
While investigating the source of the timeout I noticed that this test causes a huge amount of reads to be issued. This is the test:
https://github.com/scylladb/scylla/blob/b0c22f2e39c0a09eca2ddb7462958f4970895aef/test/boost/index_with_paging_test.cc#L27-L50

It writes 64k rows into an indexed table, then does two queries, one with a limit of 4321 and another one with no limit. After adding the following patch:
```diff
 SEASTAR_TEST_CASE(test_index_with_paging) {
@@ -35,6 +36,11 @@ SEASTAR_TEST_CASE(test_index_with_paging) {
             e.execute_cql(format("INSERT INTO tab (pk, ck, v, v2, v3) VALUES ({}, 'hello{}', 1, {}, '{}')", i % 3, i, i, big_string)).get();
         }
 
+        e.db().invoke_on_all([] (database& db) {
+            auto& sem = db.get_reader_concurrency_semaphore();
+            testlog.info("MARK1: reads={}", sem.get_stats().total_successful_reads);
+        }).get();
+
         eventually([&] {
             auto qo = std::make_unique<cql3::query_options>(db::consistency_level::LOCAL_ONE, std::vector<cql3::raw_value>{},
                     cql3::query_options::specific_options{4321, nullptr, {}, api::new_timestamp()});
@@ -42,9 +48,19 @@ SEASTAR_TEST_CASE(test_index_with_paging) {
             assert_that(res).is_rows().with_size(4321);
         });
 
+        e.db().invoke_on_all([] (database& db) {
+            auto& sem = db.get_reader_concurrency_semaphore();
+            testlog.info("MARK2: reads={}", sem.get_stats().total_successful_reads);
+        }).get();
+
         eventually([&] {
             auto res = e.execute_cql("SELECT * FROM tab WHERE v = 1").get0();
             assert_that(res).is_rows().with_size(64 * 1024);
         });
+
+        e.db().invoke_on_all([] (database& db) {
+            auto& sem = db.get_reader_concurrency_semaphore();
+            testlog.info("MARK3: reads={}", sem.get_stats().total_successful_reads);
+        }).get();
     });
 }
```
And running the test I get:
```
INFO  2021-06-04 14:11:17,941 [shard 0] testlog - MARK1: reads=57
INFO  2021-06-04 14:11:18,037 [shard 0] testlog - MARK2: reads=4379
INFO  2021-06-04 14:11:19,428 [shard 0] testlog - MARK3: reads=69916
```
This looks very wrong to me. I still don't understand fully what this test is testing exactly and how the underlying index-based read works, but as it stands we'd be better off just reading the partition and filtering instead. We should coalesce based on partition key, or limit parallelism because as it it is this causes a huge load spike which in debug mode the server cannot take.

**Comment by denesb** [comment]
After thinking about this some more I now realize that one read per row makes sense: in the index table `v` is part of the key and as `v=1` in all base table rows, the index partition for `v=1` will contain a row for each base table row.
However my point about parallelism still stands. What I observed when investigating the timeout is that the reader concurrency semaphore started shedding reads because its queue would fill up, after 20k+ queued reads. This means that all those reads are issued at once. So at the very least this parallelism should be limited because although this test is quite an extreme case, nothing guarantees that a user won't have a similar data layout. We could also try to coalesce reads against the same partition after reading a page from the index. Note that I have very limited understanding of how this works, so my coalescing suggestion might not makes sense at all.
For the curious: the reason why this test is timing out after removing the execution stage and adding up-front admission is because the execution stage doesn't time out so it can accumulate any number of reads, unlike the semaphore, which also has a cap on its queue size.

**Comment by psarna** [comment]
I vaguely remember that some kind of limit for parallelism already exists for indexed statements, but I'll need to browse the code to verify that (or debunk).

**Comment by psarna** [comment]
It looks like we only kind-of do. There are two paths for fetching indexed data, one operates on key ranges, and another one (the least efficient one) operates on single rows - that's only when a part of compound clustering key is indexed. In any case, the flow is as follows:
1. Fetch a list of ranges/keys from the secondary index
2. Start by querying a single key/range from the base table
3.
    - If (2) resulted in a short read (a read which contains less results than required, e.g. because the read operation hit replica-side limits), then the page of data is returned to the user
    - Otherwise, ask for 2x more ranges/keys than before
  

We keep asking for exponentially more ranges/keys each time, so I can imagine the number of operations skyrocketing, but on the other hand, shouldn't it stop quite soon, given that replicas would return a short read after having to send more than 10MB of data?

It would be quite easy to modify Scylla to cap max concurrency here - perhaps the best thing to do is to patch it locally and try whether it helps. There are two implementations of `indexed_table_select_statement::do_execute_base_query`, one for ranges and one for keys, and both of which increase the number of concurrently fetched ranges/rows exponentially - that's where a limit could be hardcoded and tested.

Ref:
https://github.com/scylladb/scylla/blob/b0c22f2e39c0a09eca2ddb7462958f4970895aef/cql3/statements/select_statement.cc#L544-L545
https://github.com/scylladb/scylla/blob/b0c22f2e39c0a09eca2ddb7462958f4970895aef/cql3/statements/select_statement.cc#L637-L638

**Comment by denesb** [comment]
Since we are reading one row at a time, we won't ever run into a short read, so we keep doubling concurrency until we issue 32k reads at once.

**Comment by psarna** [comment]
ouch

**Comment by psarna** [comment]
@denesb I'm in the middle of 3 things already and I don't have spare cycles to get preempted one more time at the moment - could you verify if this patch works around the problem?
```diff
diff --git a/cql3/statements/select_statement.cc b/cql3/statements/select_statement.cc
index b83309f83..c52379531 100644
--- a/cql3/statements/select_statement.cc
+++ b/cql3/statements/select_statement.cc
@@ -574,7 +574,9 @@ indexed_table_select_statement::do_execute_base_query(
                     command->slice.set_range(*_schema, base_pk, row_ranges);
                 }
             }
-            concurrency *= 2;
+            if (concurrency < 256) {
+                concurrency *= 2;
+            }
             return proxy.query(_schema, command, std::move(prange), options.get_consistency(), {timeout, state.get_permit(), state.get_client_state(), state.get_trace_state()})
             .then([&ranges_to_vnodes, &merger] (service::storage_proxy::coordinator_query_result qr) {
                 auto is_short_read = qr.query_result->is_short_read();
@@ -638,7 +640,7 @@ indexed_table_select_statement::do_execute_base_query(
             // we continue exponentially, asking for 2x more key than before
             auto already_done = std::distance(keys.begin(), key_it);
             auto next_iteration = already_done + 1;
-            next_iteration = std::min<size_t>(next_iteration, keys.size() - already_done);
+            next_iteration = std::min<size_t>({next_iteration, keys.size() - already_done, 256ULL});
             auto key_it_end = key_it + next_iteration;
             auto command = ::make_lw_shared<query::read_command>(*cmd);
 
```

**Comment by denesb** [comment]
I found a workaround to get the test passing so it is not that urgent to get this fixed right now.

**Comment by psarna** [comment]
I assigned myself in order to keep this one in my queue - it sounds like a potential root cause for various problems in clusters which use secondary indexing. I'll do some manual tests later and try to figure out a solution (hardcoding a limit sounds like a good start to avoid unbounded concurrency).

**Comment by psarna** [comment]
> Since we are reading one row at a time, we won't ever run into a short read, so we keep doubling concurrency until we issue 32k reads at once.

This statement is so true... by increasing the numbers in `test_index_with_paging` it's possible to observe concurrency so high that the merged result would exceed 10MB even if every single row would return less than a single byte, which is unlikely. I'm working on fixing this unfortunate unbounded concurrency.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
