### ISSUE TITLE
Heat-Weighted Load Balancing: change almost-identical-hit-ratio logic

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8815]
In my design of Heat-Weighted Load Balancing (HWLB; https://docs.google.com/document/d/1M-gRlPDPvqB8mWKBV1ix3AX29JCOX11zgVrtO2bf--E/edit#) I theorized about the following potential problem:

Consider two nodes with almost-100% cache hit ratio, but not exactly 100%: one has 99.9% cache hits, the second 99.8%. Normally in HWLB we want to equalize the **miss rate** in both nodes. So we send the first node twice the number of requests we send to the second. But unless the disks are extremely limited, this doesn't make sense: As a numeric example, consider that we send 2000 requests to the first node and 1000 to the second, just so the number of misses will be the same - 2 (0.1% and 0.2% misses, respectively). At such low miss numbers, the assumption that the disk reads are the slowest part of the operation is wrong, so trying to equalize only this part is wrong. 

So our code has the following check whether to do the HWLB calculations:
```c++
        if (!old_node && ht_max - ht_min > 0.01) {
              ... do the HWLB algorithm
```
In the above example, the difference between 0.999 and 0.998 is indeed less than 0.01 so the HWLB algorithm is avoided.

However, in a real user's workload we saw that this code is **not** avoiding the problem it was meant to avoid.  In the graph below, the yellow and blue replicas had nearly-complete caches (the working set fits in memory) and the green one had almost empty cache (the green node was just rebooted). But there was a small difference between the hit ratio in the yellow and blue replicas, which resulted in the yellow node getting almost twice the amount of replica reads as the blue node. 

![b](https://user-images.githubusercontent.com/584227/121028184-445c4000-c7b0-11eb-98c9-7edea3f6478d.png)

There are two problems in the above `if()` which can cause this problem:
1. First, 0.01 might not be enough. We just made this number 0.01 up. It suggests that if we have slightly more than 1 miss per 100 requests, the one miss takes more resources than the 99 requests from cache. I don't think this is the case modern machines with modern disks. I don't know how to decide what number to change this to, however... 0.1? Something else?
2. Even more importantly, in this example we have three nodes, so although two of the nodes have almost the same hit ratios, the third one (the green) has a low hit ratio, so the `if()` decides to do the HWLB algorithm anyway. Which it should - but only after setting both highest hit ratios to the same value.

There is another problem in the existing logic: the `if()` we saw doesn't deal at all with another potential problem - the problem of huge hit-ratio difference: Consider one node having hit ratio 0.1% and the other having 99.9%. We would be sending the second node 1000 times as many requests as the first node. The result will be that the first node's cache will warm very very slowly.... We have a sort-of-solution for this case in the code:
```c++
            constexpr float max_hit_rate = 0.999;
```
But again the 0.999 is arbitrary and probably too high.

I propose that we solve **both** the above problems with the same simple logic: 

**cut off hit_ratio at 0.9** (or any other constant).
In other words, if the hit_ratio is higher than 0.9, set it to 0.9. 

My proposal will solve both problems mentioned above:
1. If two nodes have slightly-different hit ratios above 0.9, both will use the same 0.9. It doesn't matter if the third node has a much lower hit ratio (as in the user's example) - the two other nodes will still get the same number.
2. The inverse miss ratio of 0.9 is 1/(1-0.9)=10, the inverse miss ratio of a completely cold node is 1/(1-0)=1. so that the coldest node will get at least 1/10th the traffic. Not 1/1000th. 

Of course we can change the number 0.9 to anything else, even to 0.99. Note that 0.99 in my proposed logic will actually work, unlike the 0.99 in the current code which (as I explained above) doesn't work when there is a third node, and doesn't apply to the coldest node issue (where a different constant 0.999 applies).

P.S. the solution I propose here is the same one I originally proposed in the design document (the "We (over)simplied by looking only at cache misses" section). I don't remember why we went with a different implementation in the code.

CC @gleb-cloudius

**Comment by slivne** [comment]
@gleb-cloudius please review the above and approve

**Comment by gleb-cloudius** [comment]
On Mon, Jun 07, 2021 at 07:37:43AM -0700, nyh wrote:
> There are two problems in the above `if()` which can cause this problem:
> 1. First, 0.01 might not be enough. We just made this number 0.01 up. It suggests that if we have slightly more than 1 miss per 100 requests, the one miss takes more resources than the 99 requests from cache. I don't think this is the case modern machines with modern disks. I don't know how to decide what number to change this to, however... 0.1? Something else?
Any value will be a guess. Current one is probably to small.

> 2. Even more importantly, in this example we have three nodes, so although two of the nodes have almost the same hit ratios, the third one (the green) has a low hit ratio, so the `if()` decides to do the HWLB algorithm anyway. Which it should - but only after setting both highest hit ratios to the same value.
> 
I do not understand what that means.

> There is another problem in the existing logic: the `if()` we saw doesn't deal at all with another potential problem - the problem of huge hit-ratio difference: Consider one node having hit ratio 0.1% and the other having 99.9%. We would be sending the second node 1000 times as many requests as the first node. The result will be that the first node's cache will warm very very slowly.... We have a sort-of-solution for this case in the code:
> ```c++
>             constexpr float max_hit_rate = 0.999;
> ```
> But again the 0.999 is arbitrary and probably too high.
> 
It is suppose to be the highest possible value. It means that the
probability to send a request to the node with low hitrate will be
almost 1. I do not see any problem here. The arbitrary value is one that
decides that a value is old. May be 1 second is too harsh.

> I propose that we solve **both** the above problems with the same simple logic: 
> 
> **cut off hit_ratio at 0.9** (or any other constant).
> In other words, if the hit_ratio is higher than 0.9, set it to 0.9. 
> 
> My proposal will solve both problems mentioned above:
> 1. If two nodes have slightly-different hit ratios above 0.9, both will use the same 0.9. It doesn't matter if the third node has a much lower hit ratio (as in the user's example) - the two other nodes will still get the same number.
> 2. The inverse miss ratio of 0.9 is 1/(1-0.9)=10, the inverse miss ratio of a completely cold node is 1/(1-0)=1. so that the coldest node will get at least 1/10th the traffic. Not 1/1000th. 
> 
> Of course we can change the number 0.9 to anything else, even to 0.99. Note that 0.99 in my proposed logic will actually work, unlike the 0.99 in the current code which (as I explained above) doesn't work when there is a third node, and doesn't apply to the coldest node issue (where a different constant 0.999 applies).
> 
> P.S. the solution I propose here is the same one I originally proposed in the design document (the "We (over)simplied by looking only at cache misses" section). I don't remember why we went with a different implementation in the code.
I do not see any difference. The cut of is 0.999 in the code.

--
			Gleb.

**Comment by nyh** [comment]
> 2. Even more importantly, in this example we have three nodes, so although two of the nodes have almost the same hit ratios, the third one (the green) has a low hit ratio, so the `if()` decides to do the HWLB algorithm anyway. Which it should - but only after setting both highest hit ratios to the same value.
> I do not understand what that means.

The problem is that the logic comparing the highest and lowest hit ratio doesn't make sense when you have **three** nodes and one of them is rebooted, In that case, one node has near-zero hit ratio so although the other two needs have almost the same hit ratio, the `if()` doesn't apply because the highest and lowest hit ratio among the three (not two) nodes are very different. I showed above an example taken from an actual user - where before one node was reboot all nodes got nearly equal load, but after node A rebooted, suddenly node B got twice the load as node C - even though nothing changed in B or C - it's just that the `if()` condition was no longer true.

> There is another problem in the existing logic: the `if()` we saw doesn't deal at all with another potential problem - the problem of huge hit-ratio difference: Consider one node having hit ratio 0.1% and the other having 99.9%. We would be sending the second node 1000 times as many requests as the first node. The result will be that the first node's cache will warm very very slowly.... We have a sort-of-solution for this case in the code: ```c++ constexpr float max_hit_rate = 0.999; ``` But again the 0.999 is arbitrary and probably too high.
> It is suppose to be the highest possible value. It means that the probability to send a request to the node with low hitrate will be almost 1. I do not see any problem here.

The problem is that if we _almost always_ send a the request to the hot node, the cold node will get very very few requests - possibly much fewer than it can handle (after all, we have NVMes, not antique spinning disks) and get hotter very very slowly. 0.999 is probably much too much.

> I propose that we solve **both** the above problems with the same simple logic: **cut off hit_ratio at 0.9** (or any other constant). In other words, if the hit_ratio is higher than 0.9, set it to 0.9. My proposal will solve both problems mentioned above: 1. If two nodes have slightly-different hit ratios above 0.9, both will use the same 0.9. It doesn't matter if the third node has a much lower hit ratio (as in the user's example) - the two other nodes will still get the same number. 2. The inverse miss ratio of 0.9 is 1/(1-0.9)=10, the inverse miss ratio of a completely cold node is 1/(1-0)=1. so that the coldest node will get at least 1/10th the traffic. Not 1/1000th. Of course we can change the number 0.9 to anything else, even to 0.99. Note that 0.99 in my proposed logic will actually work, unlike the 0.99 in the current code which (as I explained above) doesn't work when there is a third node, and doesn't apply to the coldest node issue (where a different constant 0.999 applies). P.S. the solution I propose here is the same one I originally proposed in the design document (the "We (over)simplied by looking only at cache misses" section). I don't remember why we went with a different implementation in the code.
> I do not see any difference. The cut of is 0.999 in the code.

Exactly. My proposal is that we don't need to have a cutoff of 0.999 and _also_ some other logic with 0.99. We should have **just** the cutoff, but not make it 0.999 but something much further than 1. E.g., 0.95 (the 0.999 number is unlikely to be reached in practice). We don't even need to add new code for this - just remove the max-min if, and change the 0.999 constant. What I tried to explain above is why having a reasonable cutoff constant (not 0.999) makes the max-min code unnecessary, and even better (because the max-min code couldn't even do what it was designed to do.

**Comment by gleb-cloudius** [comment]
On Tue, Jun 15, 2021 at 08:27:04AM -0700, nyh wrote:
> > 2. Even more importantly, in this example we have three nodes, so although two of the nodes have almost the same hit ratios, the third one (the green) has a low hit ratio, so the `if()` decides to do the HWLB algorithm anyway. Which it should - but only after setting both highest hit ratios to the same value.
> > I do not understand what that means.
> 
> The problem is that the logic comparing the highest and lowest hit ratio doesn't make sense when you have **three** nodes and one of them is rebooted, In that case, one node has near-zero hit ratio so although the other two needs have almost the same hit ratio, the `if()` doesn't apply because the highest and lowest hit ratio among the three (not two) nodes are very different. I showed above an example taken from an actual user - where before one node was reboot all nodes got nearly equal load, but after node A rebooted, suddenly node B got twice the load as node C - even though nothing changed in B or C - it's just that the `if()` condition was no longer true.
>
The if() is there to avoid calculations when there is no substantial
different is hit levels, not to cut off a hit rate of a single node. In
the scenario you describe we very much do not want to avoid calculations,
so the if() works as intended.
 
> > There is another problem in the existing logic: the `if()` we saw doesn't deal at all with another potential problem - the problem of huge hit-ratio difference: Consider one node having hit ratio 0.1% and the other having 99.9%. We would be sending the second node 1000 times as many requests as the first node. The result will be that the first node's cache will warm very very slowly.... We have a sort-of-solution for this case in the code: ```c++ constexpr float max_hit_rate = 0.999; ``` But again the 0.999 is arbitrary and probably too high.
> > It is suppose to be the highest possible value. It means that the probability to send a request to the node with low hitrate will be almost 1. I do not see any problem here.
> 
> The problem is that if we _almost always_ send a the request to the hot node, the cold node will get very very few requests - possibly much fewer than it can handle (after all, we have NVMes, not antique spinning disks) and get hotter very very slowly. 0.999 is probably much too much.
The 0.999 here does not determine how often we send to a cold node.
milliseconds(1000) does. Once in a second cold node gets highest hit
rate value (0.999 in our case), so that the logic will send traffic to
it. 

> 
> > I propose that we solve **both** the above problems with the same simple logic: **cut off hit_ratio at 0.9** (or any other constant). In other words, if the hit_ratio is higher than 0.9, set it to 0.9. My proposal will solve both problems mentioned above: 1. If two nodes have slightly-different hit ratios above 0.9, both will use the same 0.9. It doesn't matter if the third node has a much lower hit ratio (as in the user's example) - the two other nodes will still get the same number. 2. The inverse miss ratio of 0.9 is 1/(1-0.9)=10, the inverse miss ratio of a completely cold node is 1/(1-0)=1. so that the coldest node will get at least 1/10th the traffic. Not 1/1000th. Of course we can change the number 0.9 to anything else, even to 0.99. Note that 0.99 in my proposed logic will actually work, unlike the 0.99 in the current code which (as I explained above) doesn't work when there is a third node, and doesn't apply to the coldest node issue (where a different constant 0.999 applies). P.S. the solution I propose here is the same one I originally proposed in the design document (the "We (over)simplied by looking only at cache misses" section). I don't remember why we went with a different implementation in the code.
> > I do not see any difference. The cut of is 0.999 in the code.
> 
> Exactly. My proposal is that we don't need to have a cutoff of 0.999 and _also_ some other logic with 0.99. We should have **just** the cutoff, but not make it 0.999 but something much further than 1. E.g., 0.95 (the 0.999 number is unlikely to be reached in practice). We don't even need to add new code for this - just remove the max-min if, and change the 0.999 constant. What I tried to explain above is why having a reasonable cutoff constant (not 0.999) makes the max-min code unnecessary, and even better (because the max-min code couldn't even do what it was designed to do.
> 
0.999 is the cutoff we chose back then. It may be too small indeed. No
matter what it will be there always be a threshold at which nodes
suddenly will start to get different load seemingly without any reason.

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Thu, Sep 02, 2021 at 06:09:58AM -0700, nyh wrote:
> In https://github.com/scylladb/scylla/issues/9053#issuecomment-911656661 I noted another possible problem with the "max_hit_rate=0.999" constant we had before this patch and it's interaction with another constant, 0.01, we have in the same file (`db/consistency_level.cc`).
> 
> We should consider backporting this issue to older releases. @gleb-cloudius what do you think?
> 
I am not sure that the issue is so serious that it warrants backporting.
OTOH the backport should be easy and safe.

--
			Gleb.

**Comment by nyh** [comment]
The patch for this issue is already in all supported open-source branches (all releases since 4.6), so removing the "backport candidate" tag.
