### ISSUE TITLE
Uninformative error messages when client connects with wrong TLS version

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8827]
This is a spin-off from issue #6971.
When answering encrypted CQL connections, Scylla supports (by default) TLS version 1.2 but not earlier versions. The problem is that the failure in this case is very mysterious: The client just gets an EOF, and the server logs the unhelpful message "GNUTLS:-10, The specified session has been invalidated for some reason".

https://github.com/scylladb/seastar/issues/911 is a Seastar fix that should fix the second part. I'm opening this issue as a request to update the seastar module and verify that it fixes the problem (and later think whether a backport is desired).

Can we also fix the first problem, i.e., provide a more helpful error message to the user? I'm not sure it's even possible.

**Comment by nyh** [comment]
I am hoping that it would be possible to fix the first problem. For example, the site `https://tls-v1-1.badssl.com:1011/` only supports TLS v1.1 and earlier, and if we try to connect to it with v1.2 we get:
```
curl: (35) error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol
```
So clearly the SSL protocol is capable of reporting an error and not just EOF.

**Comment by nyh** [comment]
By the way, I can confirm that scylladb/seastar#911 did fix the second problem - the log message in Scylla's logs. It now looks like:
```
INFO  2021-06-09 10:15:51,696 [shard 0] cql_server - exception while processing connection: std::system_error (error GnuTLS:-8, A packet with illegal or unsupported version was received.)
```

**Comment by nyh** [comment]
@elcallio I need your help with this please. 
I suspect the problem is that when the handshake encounters the GnuTLS error -8 (GNUTLS_E_UNSUPPORTED_VERSION_PACKET) besides returning the error code to the caller - which we turn into a throw - it probably also writes a response to the client that the version is unsupported.
I suspect that either we're not waiting for this write before closing the connection (like in the problem you fixed a few years ago, https://github.com/scylladb/seastar/commit/6c04862a78dd5c6212e7ac2f00aa3f548e6cf6ee), or, alternatively, the gnu_tls code doesn't actively write a response and we need to build it in our code. I'm not familiar with this code so I don't know which is the right explanation.

Here is a working test for this (put it in test/cql-pytest, run with `test/cql-pytest/run --ssl testname`). It is expected to fail, but look at the error message in the failure and see the "EOF occurred in violation of protocol" instead of the correct error message. If you don't want to fix this now, maybe you can just give me hints on where the problem might be.
```python
import pytest
import ssl
import cassandra.cluster
# Test that TLS 1.2 is supported (because this is what "cqlsh --ssl" uses
# by default), and that other TLS version are either supported or if
# disallowed, result in the expected sort of failure.
def test_tls_versions(cql):
    # To reduce code duplication, we let conftest.py set up 'cql', and then
    # learn from it whether SSL is supported in this run, and if so which
    # contact points, ports, and other parameters, we should use here.
    if not cql.cluster.ssl_context:
        pytest.skip("SSL-specific tests are skipped without the '--ssl' option")
    # TLS v1.2 must be supported, because this is the default version that
    # "cqlsh --ssl" uses. If this fact changes in the future, we may need
    # to reconsider this test.
    try_connect(cql.cluster, ssl.PROTOCOL_TLSv1_2)
    for ssl_version in [ssl.PROTOCOL_TLSv1_1]:
        try_connect(cql.cluster, ssl_version)

def try_connect(orig_cluster, ssl_version):
    cluster = cassandra.cluster.Cluster(
        contact_points=orig_cluster.contact_points,
        port=orig_cluster.port,
        protocol_version=orig_cluster.protocol_version,
        auth_provider=orig_cluster.auth_provider,
        ssl_context=ssl.SSLContext(ssl_version))
    cluster.connect()
    cluster.shutdown()
```

Sorry for being picky on this seemingly unimportant issue, but it may also be the tip of the iceberg of a bigger issue where all sort of SSL errors are not reported correctly to the client and instead they get mysterious  EOF.

**Comment by elcallio** [comment]
With the seastar patch I sent yesterday applied, I get:
```
cql_server - exception while processing connection: std::system_error (error GnuTLS:-8, A packet with illegal or unsupported version was received.)
```
That seems about right, does it not?

**Comment by nyh** [comment]
@elcallio yes, as I said there were two problems: One is the response that the client gets, and the second is the message which Scylla writes in its log. You solved the second problem. But the first problem still exists - the client gets an EOF (causing Python, for example, to report "EOF occurred in violation of protocol"), instead of getting an actual SSL error response (which would cause Python to say "[SSL: WRONG_SSL_VERSION] wrong ssl version". I gave above actual examples of how Scylla responds and how some other correct site responds.

My test above demonstrates the first problem, but I think you should also be able to reproduce it trivially with `curl --tlsv1.2 https://ip:9042' - it needs to report an actual error in the version, not an unexpected EOF.

**Comment by elcallio** [comment]
Need to re-read the spec and check the gnutls source/docs. I am unsure if there is any sort of reply in this case. We only get a failure from the gnutls layer. If it chooses not to send a reply packet, I don't think we can make it.

**Comment by elcallio** [comment]
Maybe, if it returns with output still pending, but that is kinda weird.

**Comment by nyh** [comment]
> Maybe, if it returns with output still pending, but that is kinda weird.

You're right, there is no pending output. The bad version doesn't produce output, just a return code of the function. The caller is supposed to use `gnutls_alert_send()` to send back the error if it wants to. And it seems our code doesn't use this function anywhere, for anything. I'll see if I can figure out how to use it...

**Comment by nyh** [comment]
I got this to work :-) Basically, we need to change the code in `do_handshake()` to replace
```c++
return make_exception_future<>(std::system_error(res, glts_errorc));
```
by
```c++
gnutls_alert_send(*this, GNUTLS_AL_FATAL,
    gnutls_alert_description_t(gnutls_error_to_alert(res, NULL)));
return wait_for_output().then([res] {
    return make_exception_future<>(std::system_error(res, glts_errorc));
});
```

The gnutls function `gnutls_error_to_alert()` automatically converts the error to its choice of alert, which I'm not completely sure is the best message. In our case, after this change, the Python code trying to connect with 1.1 shows:
> E   cassandra.cluster.NoHostAvailable: ('Unable to connect to any servers', {'127.26.11.44:9042': PermissionError(1, "Tried connecting to [('127.26.11.44', 9042)]. Last error: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:1129)")})

This much better than the old "EOF", and accodring to the TLS RFC, "Alert protocol_version" is indeed the right name. Note that there are other errors we could have used, including the WRONG_SSL_VERSION which the random site I looked at above returns, but I think the one chosen by gnutls is fine.

**Comment by nyh** [comment]
Opened https://github.com/scylladb/seastar/issues/912 on the second Seastar issue. I will send a patch for it soon.

**Comment by nyh** [comment]
By the way, @elcallio, I noticed in my tests that although the older PROTOCOL_TLSv1_1, and ssl.PROTOCOL_TLSv1 are forbidden (and this issue is about doing the error message appropriately), the even older PROTOCOL_SSLv23 **is allowed** by default. Is this deliberate?

**Comment by elcallio** [comment]
No, I think that is an omission.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
