### ISSUE TITLE
RPM packaging: multiple dependency issues related to python3 relocatable rpm

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla#8829]
There are 2 dependency problems involving scylla-python3 package:
1. The scylla metapackage is not dependent upon scylla-python3
2. The scylla-server package is dependent upon python-3 but it is not versioned.

Whenever upgrading from 2 versions that has an incompatible python version by installing the metapackage (and not by doing `yum update` for example scylla or some of it's scripts can break because of incompatible python version.

**Comment by eliransin** [comment]
I work on a patch.

**Comment by eliransin** [comment]
The following shows that we are most likely we won't be able to do something like the following if we don't fix if:
`yum update scylla` and we will have to do `yum update scylla*` or similar thing which seams strange.

It is indeed a problem, taking as an example 4.5, python3 is not mentioned:
```
rpm -qpR scylla-4.5.rc2-0.20210602.d92a26636.x86_64.rpm 
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
scylla-conf = 4.5.rc2
scylla-jmx = 4.5.rc2
scylla-kernel-conf = 4.5.rc2
scylla-node-exporter = 4.5.rc2
scylla-server = 4.5.rc2
scylla-tools = 4.5.rc2
scylla-tools-core = 4.5.rc2
```
Moreover, no specific python3 version is dependant:
```
rpm -qpR scylla-server-4.5.rc2-0.20210602.d92a26636.x86_64.rpm 
/bin/sh
/bin/sh
/bin/sh
/bin/sh
/bin/sh
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
scylla-conf
scylla-python3
```

**Comment by avikivity** [comment]
Backported to 4.3, 4.4, 4.5.
