### ISSUE TITLE
queue_reader_handle move constructor does not move the other exception

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8833]
Currently, queue_reader_handle move constructor ignores `_ex`:

https://github.com/scylladb/scylla/blob/fa29b79c200d81de6e35685c5b70ff6ae278d12a/mutation_reader.cc#L2096
This means that is a queue_reader_handle is moved after it was aborted, the exception will be missing in the moved-to copy.

It doesn't seem to ever happen in the present codebase though, so a backport does not seem to be strictly required.

**Comment by avikivity** [comment]
No production issue, removing backport candidate label.
