### ISSUE TITLE
If older TLS versions are not supported, neither should the even older SSL

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8837]
During my tests for #8827, I noticed that Python's `ssl.PROTOCOL_TLSv1_2` is allowed, but the older `ssl.PROTOCOL_TLSv1_1` and `ssl.PROTOCOL_TLSv1` are not allowed. I assume this is for security reasons - the older protocols are considered less secure, and should not be used.
This is why I was surprised to see that  `ssl.PROTOCOL_SSLv23` **is** allowed. If this is a mistake, we shouldn't allow it.

My test `test/cql-pytest/run --ssl -vs test_ssl.py::test_tls_versions` can be used to print which versions are allowed and which are not in a default enabling of TLS without choosing any specific priority string. 

The problem is probably the default "priority string" defined in db/config.cc:
```c++
const sstring db::config::default_tls_priority("SECURE128:-VERS-TLS1.0");
```
This was added in commit ba6a8ef35b95637e49b955bcbf646a31ab00fe3e (by @elcallio), with the express purpose of "avoid deprecated protocol versions" - so we should probably disable the ancient SSL as well.

**Comment by nyh** [comment]
Note that I expect that if we disallow `ssl.PROTOCOL_SSLv23`, the test `test_ssl.py::test_tls_versions` will need to be revised: The specific error we expect to see in this test when a protocol is not supported ("protocol version") was new to TLS, and I don't know what the ancient SSL error looked like.

**Comment by elcallio** [comment]
This is very strange. Are you sure that ssl2.3 connection actually works, and more to the point that it actually uses ssl2.3 protocol?
Testing our prio string
```
$ gnutls-cli --priority SECURE128:-VERS-TLS1.0 -l
Cipher suites for SECURE128:-VERS-TLS1.0
TLS_AES_256_GCM_SHA384                                  0x13, 0x02      TLS1.3
TLS_CHACHA20_POLY1305_SHA256                            0x13, 0x03      TLS1.3
TLS_AES_128_GCM_SHA256                                  0x13, 0x01      TLS1.3
TLS_AES_128_CCM_SHA256                                  0x13, 0x04      TLS1.3
TLS_ECDHE_ECDSA_AES_256_GCM_SHA384                      0xc0, 0x2c      TLS1.2
TLS_ECDHE_ECDSA_CHACHA20_POLY1305                       0xcc, 0xa9      TLS1.2
TLS_ECDHE_ECDSA_AES_256_CBC_SHA1                        0xc0, 0x0a      TLS1.0
TLS_ECDHE_ECDSA_AES_256_CCM                             0xc0, 0xad      TLS1.2
TLS_ECDHE_ECDSA_AES_128_GCM_SHA256                      0xc0, 0x2b      TLS1.2
TLS_ECDHE_ECDSA_AES_128_CBC_SHA1                        0xc0, 0x09      TLS1.0
TLS_ECDHE_ECDSA_AES_128_CCM                             0xc0, 0xac      TLS1.2
TLS_ECDHE_RSA_AES_256_GCM_SHA384                        0xc0, 0x30      TLS1.2
TLS_ECDHE_RSA_CHACHA20_POLY1305                         0xcc, 0xa8      TLS1.2
TLS_ECDHE_RSA_AES_256_CBC_SHA1                          0xc0, 0x14      TLS1.0
TLS_ECDHE_RSA_AES_128_GCM_SHA256                        0xc0, 0x2f      TLS1.2
TLS_ECDHE_RSA_AES_128_CBC_SHA1                          0xc0, 0x13      TLS1.0
TLS_RSA_AES_256_GCM_SHA384                              0x00, 0x9d      TLS1.2
TLS_RSA_AES_256_CBC_SHA1                                0x00, 0x35      TLS1.0
TLS_RSA_AES_256_CCM                                     0xc0, 0x9d      TLS1.2
TLS_RSA_AES_128_GCM_SHA256                              0x00, 0x9c      TLS1.2
TLS_RSA_AES_128_CBC_SHA1                                0x00, 0x2f      TLS1.0
TLS_RSA_AES_128_CCM                                     0xc0, 0x9c      TLS1.2
TLS_DHE_RSA_AES_256_GCM_SHA384                          0x00, 0x9f      TLS1.2
TLS_DHE_RSA_CHACHA20_POLY1305                           0xcc, 0xaa      TLS1.2
TLS_DHE_RSA_AES_256_CBC_SHA1                            0x00, 0x39      TLS1.0
TLS_DHE_RSA_AES_256_CCM                                 0xc0, 0x9f      TLS1.2
TLS_DHE_RSA_AES_128_GCM_SHA256                          0x00, 0x9e      TLS1.2
TLS_DHE_RSA_AES_128_CBC_SHA1                            0x00, 0x33      TLS1.0
TLS_DHE_RSA_AES_128_CCM                                 0xc0, 0x9e      TLS1.2

Protocols: VERS-TLS1.3, VERS-TLS1.2, VERS-DTLS1.2
Ciphers: AES-256-GCM, CHACHA20-POLY1305, AES-256-CBC, AES-256-CCM, AES-128-GCM, AES-128-CBC, AES-128-CCM
MACs: SHA1, AEAD
Key Exchange Algorithms: ECDHE-ECDSA, ECDHE-RSA, RSA, DHE-RSA
Groups: GROUP-SECP256R1, GROUP-SECP384R1, GROUP-SECP521R1, GROUP-X25519, GROUP-X448, GROUP-FFDHE2048, GROUP-FFDHE3072, GROUP-FFDHE4096, GROUP-FFDHE6144, GROUP-FFDHE8192
PK-signatures: SIGN-RSA-SHA256, SIGN-RSA-PSS-SHA256, SIGN-RSA-PSS-RSAE-SHA256, SIGN-ECDSA-SHA256, SIGN-ECDSA-SECP256R1-SHA256, SIGN-EdDSA-Ed25519, SIGN-RSA-SHA384, SIGN-RSA-PSS-SHA384, SIGN-RSA-PSS-RSAE-SHA384, SIGN-ECDSA-SHA384, SIGN-ECDSA-SECP384R1-SHA384, SIGN-EdDSA-Ed448, SIGN-RSA-SHA512, SIGN-RSA-PSS-SHA512, SIGN-RSA-PSS-RSAE-SHA512, SIGN-ECDSA-SHA512, SIGN-ECDSA-SECP521R1-SHA512
```
would indicate that only TLS1.3, TLS1.2 and DTLS1.2 are accepted.

**Comment by nyh** [comment]
Very good question... Take a look at `test/cql-pytest/run --runxfail -vs --ssl test_ssl.py` (reorder the protocol versions to try PROTOCOL_SSLv23 first) - it really does succeed with PROTOCOL_SSLv23, but maybe Python is just lying? I tried wireshark but got confusing results so I'm not sure what's going on :-(

**Comment by nyh** [comment]
@elcallio you are right. It turns out that in Python's SSL implementation - see https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS - PROTOCOL_SSLv23 is nothing more than a deprecated alias to PROTOCOL_TLS, which in turn means "Selects the highest protocol version that both the client and server support." - so it's not surprising that it works, and has nothing to do with SSL.
So it seems I can't really check the old SSL protocol with modern Python and OpenSSL, and I trust your check of gnutls-cli to tell the real story. So this is not an issue, and I'm closing it.

**Comment by nyh** [comment]
I sent a patch to the mailing list titled "[PATCH] cql-pytest: improve test for SSL/TLS versions" which verifies that SSL is, in fact, correctly rejected.
