### ISSUE TITLE
Setup failed on newly installed scylla 4.4.2 node

### ISSUE THREAD

**Issue by thirstycrow** [scylladb/scylla#8842]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.4.2
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS 7.6

`scylla_setup` failed on newly installed scylla 4.4.2 node with error message like the following, but it works on nodes upgraded from 4.4.1 with the same kernel.
```
ERROR 2021-06-10 20:35:31,713 [shard 0] seastar - Exiting on unhandled exception: std::system_error (error system:11, io_setup: Resource temporarily unavailable)
Please upgrade to a newer kernel version.
 see https://docs.scylladb.com/troubleshooting/error_messages/kb_fs_not_qualified_aio/ for details
```

It turns out that 4.4.2 does not modify `fs.aio-max-nr`, which is 65536 by default on our nodes, to 1048576 during installation as 4.4.1 do, and cause the failure.

**Comment by avikivity** [comment]
It's fixed by 36a4eba22e6ee6491a7c8a4e0ee997fe04b9e2ba, which will be in 4.4.3.
