### ISSUE TITLE
timeout is ignored when consuming readers

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8846]
a timeout time_point argument is passed to flat_mutation_reader consume methods such as:
`operator()`, `consume, `consume_pausable`, and `consume_in_thread` and it is passed down the chain
to the reader implementation `fill_buffer` and friends, but it is ignored, and no timeout is generated when e.g. reading from a sstable.

A timeout error is required to release active readers resource when a query times out by closing them, making use of the close() infrastructure laid out in #1076 triggering read request cancel via scylladb/seastar#811 + scylladb/seastar#859.

**Comment by tgrabiec** [comment]
Is this a subset of https://github.com/scylladb/scylla/issues/2927?

**Comment by bhalevy** [comment]
Yes, I'd say it's the part in https://github.com/scylladb/scylla/issues/2927#issuecomment-785969297 and https://github.com/scylladb/scylla/issues/2927#issuecomment-786080784

**Comment by bhalevy** [comment]
Change 9bbe7b14823c1ca48e6659014f7edc235b3df10a implements the timeout in `mx_sstable_mutation_reader`.

**Comment by bhalevy** [comment]
Can be closed with acf8da2bcef47168376e876e2fdc37fc26ebc82e

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
