### ISSUE TITLE
Bad performance on default CentOS/RHEL 7.0 kernel

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#885]
Good xfs append support was introduces in 3.10.0-257.el7:

> * Thu May 28 2015 Rafael Aquini <aquini@redhat.com> [3.10.0-257.el7]
> - [fs] xfs: allow appending aio writes (Eric Sandeen) [1053615]

We need to ensure, that if running on RHEL or CentOS, the kernel is at least that version.

**Comment by avikivity** [comment]
|OS|Variant|Kernel|Good?|
|----|---------|--------|---------|
|7.0|Release|3.10.0-123.el7.x86_64| No |
|     |Updates|3.10.0-123.1.2.el7| No |
|7.1|Release|3.10.0-229.el7| No |
|     |Updates|3.10.0-229.20.1.el7| No |
|7.2|Release|3.10.0-327.el7| Yes |

**Comment by avikivity** [comment]
Conclusion, 7.2 is the minimum supported version.

**Comment by tzach** [comment]
@avikivity whats the status of Ubuntu 14.04 with XFS?

**Comment by avikivity** [comment]
Not yet known.  I see that 14.04 ships about 2,665 kernel, hopefully at least one will have good support.
