### ISSUE TITLE
Can't select only a static column in a query using a secondary index

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8869]
If a table has a static column `s` and indexed column `v`, the query
```
SELECT s FROM tab WHERE v = 1
```

Is supported by Cassandra - it returns the static column `s` for every matching row (so if multiple rows in the same partition have `v = 1`, we get the same `s` value multiple times).

Scylla doesn't support this query - and gives the error:
```
Queries using 2ndary indexes don't support selecting only static columns
```

Looking at the code we see this was done deliberately, because of the thinking that this is not a useful query:
```c++
void statement_restrictions::validate_secondary_index_selections(bool selects_only_static_columns) {
    ...
    // When the user only select static columns, the intent is that we don't query the whole partition but just
    // the static parts. But 1) we don't have an easy way to do that with 2i and 2) since we don't support index on
    // static columns
    // so far, 2i means that you've restricted a non static column, so the query is somewhat non-sensical.
    if (selects_only_static_columns) {
        throw exceptions::invalid_request_exception(
            "Queries using 2ndary indexes don't support selecting only static columns");
    }
}
```

Nevertheless, Cassandra supports this query so we should too.

This bug is reproduced by the translated Cassandra unit test in cql-pytest:
* `cassandra_tests/validation/entities/static_column_test.py`::`testStaticColumnsWithSecondaryIndex`

Note that this issue is _not_ related to indexing of static columns (that would be issue #2963) - here we just have a static column but index a different column.

**Comment by nyh** [comment]
> If a table has a static column `s` and indexed column `v`, the query
> 
> ```
> SELECT s FROM tab WHERE v = 1
> ```
> 
> Is supported by Cassandra - it returns the static column `s` for every matching row (so if multiple rows in the same partition have `v = 1`, we get the same `s` value multiple times).
> 
> Scylla doesn't support this query - and gives the error:
> 
> ```
> Queries using 2ndary indexes don't support selecting only static columns
> ```
> 
> Looking at the code we see this was done deliberately, because of the thinking that this is not a useful query:
> 
> ```c++
> void statement_restrictions::validate_secondary_index_selections(bool selects_only_static_columns) {
>     ...
>     // When the user only select static columns, the intent is that we don't query the whole partition but just
>     // the static parts. But 1) we don't have an easy way to do that with 2i and 2) since we don't support index on
>     // static columns
>     // so far, 2i means that you've restricted a non static column, so the query is somewhat non-sensical.
>     if (selects_only_static_columns) {
>         throw exceptions::invalid_request_exception(
>             "Queries using 2ndary indexes don't support selecting only static columns");
>     }
> }
> ```
> 
> Nevertheless, Cassandra supports this query so we should too.
> 
> This bug is reproduced by the translated Cassandra unit test in cql-pytest:
> 
>     * `cassandra_tests/validation/entities/static_column_test.py`::`testStaticColumnsWithSecondaryIndex`
> 
> 
> Note that this issue is _not_ related to indexing of static columns (that would be issue #2963) - here we just have a static column but index a different column.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
