### ISSUE TITLE
Use I/O priority classes for repair and for compaction

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#887]
We want disk I/O in repair to be a separate priority class (likely to solve issue #861), and similarly, disk access in compaction to be a separate priority class.

While in compaction both reads and writes (to sstables) can be identified and tagged with the right priority class, in repair the situation is slightly more hairy: The reads can be tagged, but the writes happen through streaming and are written to memtables - and only later these memtables are flushed to disk, and we don't know they are part of a repair. I believe that In most repairs this issue will not be important because there will be far fewer writes than reads anyway (assuming that only a small part of the data needs repair). 

In today's call, Dor asked that this work be assigned to me (@nyh). With the lovely limitations of github issue tracker, I can't do it myself...

**Comment by nyh** [comment]
@dorlar, Glauber has already added a compaction priority class, in commit b63611e1485668377a5d5c511b72ca7c21eec6ed. The way he did it appears to be correct.

So the only thing that's left is to do this for repair.

**Comment by dorlaor** [comment]
Ok, can you please verify that #861 is solved by this?

**Comment by nyh** [comment]
On Tue, Feb 9, 2016 at 5:51 PM, Dor Laor <notifications@github.com> wrote:

> Ok, can you please verify that #861 is solved by this?
>

I just wrote a comment in #861 asking whomever knows to reproduce this run
to verify this.

Although I think that in general, we need this patch - why leave repair as
the only thing
without its own priority class? What harm can be caused by having one?
