### ISSUE TITLE
Do not cache system.large_* tables

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8874]
This issue follows up on https://github.com/scylladb/scylla/issues/7668#issuecomment-862478345

@slivne said:
> in the case a customer has large partitions - we are going to create a real issue for him (and us) with generating range tombstones that can't be evicted out of the cache and only accumulate - those range tombstones are going to keep pilling up since a compaction of such a table ends up usually with another table that has a large partition as well ...
>
> I think we need to mark the system_large* tables as tables that should not be cached to make sure we do not cause an issue and once we have range tombstones handling made better (and we are working on that) consider removing that.

**Comment by bhalevy** [comment]
More about the motivation for this issue:

We generate much less range tombstones with
https://github.com/scylladb/scylla/issues/7668 fixed.
But we still generate range tombstones for sstables
that do hold large_ data.

They accumulate in the cache as per:
https://github.com/scylladb/scylla/issues/7750

and they need to be evicted gradually, as per:
https://github.com/scylladb/scylla/issues/3288

So this is a workaround until the above is fixed.
Please add a FIXME comment to undo it when the root cause is fixed.

**Comment by avikivity** [comment]
Not backporting, since #7668 (which was backported) is likely sufficient.
