### ISSUE TITLE
Reconsider a common prefix for "safe mode" options, instead of "restrict".

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8879]
I called the first "safe mode" configuration option that we have: `--restrict-replication-simplestrategy`.
My plan was that the "--restrict" part will be a common prefix for all "safe mode" options.
My rationale was that "safe mode" is all about **restricting** (or allowing with a warning) the use of various options, operations, patterns, etc., which have hitherto been allowed in Scylla but we now wish to restrict.

@slivne and @eliransin suggested that the word "restrict" is not general enough and we may have safe-mode-related options which perhaps are not about "restricting" anything. My problem is that I don't know of any example of such options, so I don't know how to choose a  better prefix. @tzach @slivne @eliransin - any suggestion for a better prefix?

By the way, I admit that already "restrict" might not be the most fitting word if we choose the "warn" setting - e.g., `--restrict-replication-simplestrategy warn` doesn't actually restrict anything, it just warns. Nevertheless I thought it's clear enough even with the word "restrict". The question now is what better word I can use.

@eliransin suggested the prefix "production-mode". So we will have, for example, `--production-mode-replication-simplestrategy warn` - and because of the lack of the word 'restrict', the setting "true" and "false" will need to change to something like "forbid" and "allow".

@tzach @slivne do you also like the prefix "production-mode"? Or do you have any other suggestion?

**Comment by nyh** [comment]
Another thought on whether we even want a "common prefix":

In issue #8891 we raised the idea of a minimum allowed RF, which is a feature proposed in Cassandra (https://issues.apache.org/jira/browse/CASSANDRA-14557) under the name of `minimum_keyspace_rf`. If we want to be compatible with them (anticipating that they will eventually accept this name), we may want to use the same name.

In another issue, #8882, I noted that two configuration options we already have, `max_partition_key_restrictions_per_query` and `max_clustering_key_restrictions_per_query`, are also kind of related to "safe mode" but also don't share the common prefix.

So one possibility is to forget the idea of a common prefix. Find a way to **list** all these options together, but they won't have a common prefix.

The second possibility is to insist on a common prefix, and **rename** these old option names. A "rename" should probably living behind an alias for backward-compatibility purposes, but these aliases will not be listed by "scylla --help".

@tzach @slivne so given these examples of pre-existing (or Cassandra-compatible) options, what's your opinion on this "common prefix" thing - necessary, or counter-productive?

**Comment by tzach** [comment]
An easy way to present and update all the "safe mode" options would be nice, at least as good as a common prefix.

**Comment by nyh** [comment]
> An easy way to present and update all the "safe mode" options would be nice, at least as good as a common prefix.

I tried today to put all these options together under one heading in "scylla --help" (as you can see there are several Seastar-defined headings there already, but no Scylla subheadings), but it's frustratingly hard.

Another option is to forget about "scylla --help" and document everything in scylla.yaml. This can also allow a syntax where the options aren't separate, like Shlomi originally preferred.

**Comment by tzach** [comment]
This is a variant, or enchantment of #6708 #8428

**Comment by eliransin** [comment]
> I tried today to put all these options together under one heading in "scylla --help" (as you can see there are several Seastar-defined headings there already, but no Scylla subheadings), but it's frustratingly hard.

@nyh this is not accurate (the part on scylla not adding subheadings of it's own not about the frustrating :smile: ):
Here is one section that comes from scylla:
```
Deprecated options - ignored:
  --background-writer-scheduling-quota arg
  --auto-adjust-flush-quota arg
```

It is originated here:
https://github.com/scylladb/scylla/blob/499357fb431c6074e2f385562c3e67a8006b3081/main.cc#L455-L459

With that said I don't mind to consider the other options, I think making Scylla more usable by first considering the 
documentation of all of the CLI option is a good and desired side effect.

SCT uses some idea of this and it has a special function and a command line for generating a ".md" file for all of their supported
parameters.

**Comment by nyh** [comment]
> > I tried today to put all these options together under one heading in "scylla --help" (as you can see there are several Seastar-defined headings there already, but no Scylla subheadings), but it's frustratingly hard.
> 
> @nyh this is not accurate (the part on scylla not adding subheadings of it's own not about the frustrating smile ):
> Here is one section that comes from scylla:
> 
> ```
> Deprecated options - ignored:

Right, I saw that, but those are not coming from db/config.cc. db/config.cc has many layers of machinary which I'm just discovering now, and I would need to change some of those to allow different options to go into different headings. The ad-hoc approach of adding "deprecated options" in main.cc doesn't help me directly (although it is a good example of how to add a separate heading).

**Comment by nyh** [comment]
I'm closing this issue - there is no agreement that we need or want a common prefix for the "safe mode" options. There is agreement, however, that we want to be able to know (e.g. in "scylla --help", but in the future perhaps more than that) which options are considered "safe mode" options. I'll open a new issue saying that.
