### ISSUE TITLE
Building on debian/ubuntu

### ISSUE THREAD

**Issue by dioptre** [scylladb/scylla#888]
I'm getting this for 0.16 on ubuntu 15.10

FAILED: g++ -MMD -MT build/release/sstables/sstables.o -MF build/release/sstables/sstables.o.d -std=gnu++1y -g  -Wall -fvisibility=hidden -pthread -I/home/a/scylla/seastar -I/home/a/scylla/seastar/build/release/gen -I/usr/include -Iantlr3/runtime/Cpp/include -march=nehalem -Wno-overloaded-virtual -DHAVE_HWLOC -DHAVE_NUMA -DHAVE_SYS_MEMBARRIER  -O2 -I/usr/include -Iantlr3/runtime/Cpp/include -I/usr/include/jsoncpp  -Wno-maybe-uninitialized -DHAVE_LIBSYSTEMD=1 -I. -I build/release/gen -I seastar -I seastar/build/release/gen -c -o build/release/sstables/sstables.o sstables/sstables.cc
sstables/sstables.cc: In member function ‘virtual input_stream<char> sstables::file_random_access_reader::open_at(uint64_t)’:
sstables/sstables.cc:80:63: error: no matching function for call to ‘make_file_input_stream(file&, uint64_t&, size_t&)’
         return make_file_input_stream(_file, pos, _buffer_size);
                                                               ^
In file included from sstables/sstables.cc:29:0:
/home/a/scylla/seastar/core/fstream.hh:46:20: note: candidate: input_stream<char> make_file_input_stream(file, uint64_t, file_input_stream_options)
 input_stream<char> make_file_input_stream(
                    ^
/home/a/scylla/seastar/core/fstream.hh:46:20: note:   no known conversion for argument 3 from ‘size_t {aka long unsigned int}’ to ‘file_input_stream_options’
/home/a/scylla/seastar/core/fstream.hh:52:20: note: candidate: input_stream<char> make_file_input_stream(file, file_input_stream_options)
 input_stream<char> make_file_input_stream(
                    ^
/home/a/scylla/seastar/core/fstream.hh:52:20: note:   candidate expects 2 arguments, 3 provided
sstables/sstables.cc: In lambda function:
sstables/sstables.cc:811:89: error: no matching function for call to ‘make_file_input_stream(file&, const uint64_t&, const uint64_t&)’
         auto stream = make_file_input_stream(this->_index_file, position, estimated_size);
                                                                                         ^
In file included from sstables/sstables.cc:29:0:
/home/a/scylla/seastar/core/fstream.hh:46:20: note: candidate: input_stream<char> make_file_input_stream(file, uint64_t, file_input_stream_options)
 input_stream<char> make_file_input_stream(
                    ^
/home/a/scylla/seastar/core/fstream.hh:46:20: note:   no known conversion for argument 3 from ‘const uint64_t {aka const long unsigned int}’ to ‘file_input_stream_options’
/home/a/scylla/seastar/core/fstream.hh:52:20: note: candidate: input_stream<char> make_file_input_stream(file, file_input_stream_options)
 input_stream<char> make_file_input_stream(
                    ^
/home/a/scylla/seastar/core/fstream.hh:52:20: note:   candidate expects 2 arguments, 3 provided
In file included from /home/a/scylla/seastar/core/future-util.hh:31:0,
                 from sstables/sstables.cc:27:
/home/a/scylla/seastar/core/do_with.hh: In instantiation of ‘auto do_with(T&&, F&&) [with T = sstables::index_consumer; F = sstables::sstable::read_indexes(uint64_t)::<lambda(sstables::index_consumer&)>]’:
sstables/sstables.cc:816:6:   required from here
/home/a/scylla/seastar/core/do_with.hh:55:22: error: ‘void fut’ has incomplete type
     auto fut = f(_obj);
                      ^
sstables/sstables.cc: In member function ‘future<std::vector<sstables::index_entry, std::allocator<sstables::index_entry> > > sstables::sstable::read_indexes(uint64_t)’:
sstables/sstables.cc:810:19: error: could not convert ‘do_with<sstables::index_consumer, sstables::sstable::read_indexes(uint64_t)::<lambda(sstables::index_consumer&)> >(sstables::index_consumer(quantity), <lambda closure object>sstables::sstable::read_indexes(uint64_t)::<lambda(sstables::index_consumer&)>{((sstables::sstable_)this), position, estimated_size})’ from ‘void’ to ‘future<std::vector<sstables::index_entry, std::allocator<sstables::index_entry> > >’
     return do_with(index_consumer(quantity), [this, position, estimated_size](index_consumer& ic) {
                   ^
sstables/sstables.cc: In member function ‘input_stream<char> sstables::sstable::data_stream_at(uint64_t, uint64_t)’:
sstables/sstables.cc:1530:64: error: no matching function for call to ‘make_file_input_stream(file&, uint64_t&, uint64_t&)’
         return make_file_input_stream(_data_file, pos, buf_size);
                                                                ^
In file included from sstables/sstables.cc:29:0:
/home/a/scylla/seastar/core/fstream.hh:46:20: note: candidate: input_stream<char> make_file_input_stream(file, uint64_t, file_input_stream_options)
 input_stream<char> make_file_input_stream(
                    ^
/home/a/scylla/seastar/core/fstream.hh:46:20: note:   no known conversion for argument 3 from ‘uint64_t {aka long unsigned int}’ to ‘file_input_stream_options’
/home/a/scylla/seastar/core/fstream.hh:52:20: note: candidate: input_stream<char> make_file_input_stream(file, file_input_stream_options)
 input_stream<char> make_file_input_stream(
                    ^
/home/a/scylla/seastar/core/fstream.hh:52:20: note:   candidate expects 2 arguments, 3 provided
[4/6] CXX build/release/locator/ec2_snitch.o
ninja: build stopped: subcommand failed.

**Comment by avikivity** [comment]
Are your git submodules synchronized?

`git submodule update --init --recursive`

**Comment by syuu1228** [comment]
Also please try dist/ubuntu/build_deb.sh if you are on Ubuntu 15.10/14.04 LTS.
It resolves dependencies to build on Ubuntu.
Other versions of Ubuntu(and Debians) may need to modify the build script to support it.

**Comment by dioptre** [comment]
@syuu1228  thanks for the suggestion, but the install overwrote a lot of my critical dependencies and ##$$$ my machine. I'd avoid using this for other ppl having issues. Will get back to this hopefully in a bit.

**Comment by avikivity** [comment]
@syuu1228 we need to provide PPAs for various versions of ubuntu.  Maybe we can just use the Ubuntu build service for them.

**Comment by dioptre** [comment]
It would be nice if it could be built from source, dependency hell will always exist with binaries...

Do you guys know what this is referring to?

return make_file_input_stream(_file, pos, _buffer_size);

**Comment by benoit-canet** [comment]
It build an object that scylla uses to read data from disk.

The file make_file_input_stream object and the file_input_stream object
lives in seastar the
library scylla is built upon.

Maybe your version of seastar is out of sync with what scylla expect.

Maybe you could try git submodule update and a new build afterward.

**Comment by dioptre** [comment]
I tried that sorry :(

**Comment by slivne** [comment]
we support 16.04
