### ISSUE TITLE
ALTERing a keyspace with NetworkTopologyStrategy doesn't verify replication_factor

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8880]
When doing
```
CREATE KEYSPACE name WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 1 }
ALTER KEYSPACE name WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'replication_factor' : 'foo' }
```
The ALTER fails as expected, saying:
```
Replication factor must be numeric and non-negative, found 'foo'
```
However, if the keyspace originally had NetworkTopologyStrategy, the verification of the `replication_factor` isn't done. The following operations silently succeed:
```
CREATE KEYSPACE name WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'replication_factor' : 1 }
ALTER KEYSPACE name WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'replication_factor' : 'foo' }
```

I suspect that the `replication_factor` is deliberately ignored on previously-existing DCs for "safety" reasons explained in https://docs.scylladb.com/getting-started/ddl/ and with which I don't really agree. Nevertheless, if the option is malformed, maybe we can at least complain about that? 

Discovered by the cql-pytest `test_keyspace.py::test_alter_keyspace_invalid` when changing it to use NetworkTopologyStrategy instead of SimpleStrategy (for #8638).

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
