### ISSUE TITLE
Missing rpms for Fedora 23

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#889]
We don't have rpms for Fedora 23 on our repo, following error happens because of it:
```
$ sudo wget -O /etc/yum.repos.d/scylla.repo http://downloads.scylladb.com/rpm/fedora/scylla.repo
$ sudo dnf search scylla
Failed to synchronize cache for repo 'scylla-generic' from 'https://s3.amazonaws.com/downloads.scylladb.com/rpm/fedora/23/noarch/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
Failed to synchronize cache for repo 'scylla' from 'https://s3.amazonaws.com/downloads.scylladb.com/rpm/fedora/23/x86_64/': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried, disabling.
```

We can keep 22 repo, but shouldn't we build for 23 as well?

**Comment by avikivity** [comment]
I think we should.

**Comment by tzach** [comment]
More people are asking for Ubuntu 15 packages #609
AFAIK, no one asked for F23 yet.
If we can do one, I vote for 609

**Comment by avikivity** [comment]
F23 is quite easy, just duplicating a jenkins job.

U15 is harder, but on the other hand important, because it prepares us for 16.04 LTS.

**Comment by syuu1228** [comment]
I guess U15 is not so hard, since we already have 14.04 LTS jenkins job, and we are unofficially supported 15.10(sometimes broken since we don't have CI for it yet though).

**Comment by slivne** [comment]
Lets try and focus on the other issues before adding distributions

When adding distribution its not only enabeling it on jenkins it requires
also to have a santiy tester avilable.

With regards to 15.10 - Takuya you have openned a bug on a unitest that
does not pass on 15.10 - we need all the unitests to pass not only to be
able to compile scylla.

**Comment by jeunetoujour** [comment]
I would like a build for F23 if it can be made available easily with just a jenkins job.

**Comment by syuu1228** [comment]
From build 8, scylla-master-fedora-rpm(nightly build) supported Fedora 23.
https://s3.amazonaws.com/downloads.scylladb.com/rpm/unstable/fedora/master/8/scylla.repo

**Comment by dorlaor** [comment]
I checked the s3 directory on amazon directly and there are only fedora 22
images.
Are you sure it works w/ F23?

**Comment by syuu1228** [comment]
Latest directory is s3://downloads.scylladb.com/rpm/unstable/fedora/master/9/.
latest link looks like broken for fedora unstable.

**Comment by dorlaor** [comment]
Shouldn't @slivne take a look?

**Comment by slivne** [comment]
I will tomorrow ...
