### ISSUE TITLE
evictable_reader: self validation triggers when a partition dissapears after eviction

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#8893]
If the partition the reader was reading when paused dissapears until the reader is re-created, the evictable reader's self validation triggers and a big scary error is generated and the read is terminated. The mutation_source the evictable reader stores doesn't pin a certain version of the data, in other words there is no snapshot isolation. The data can change (new writes can appear and old writes can be compacted away) between two invokations of the same mutation source. We have the concept of a snapshot source but this only works for sstables, we cannot use it for reading through cache and memtables. I think the only way out is to relax the self validation to accept any later partition too.

**Comment by avikivity** [comment]
Backported to 4.5, 4.4, 4.3.
