### ISSUE TITLE
Retire DateTieredCompactionStrategy (DTCS)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8914]
DTCS usage is discouraged already for a long time and customers using DTCS are advised to move to TWCS.
DTCS itself is not well tested and not really maintained so we should deprecate it and later disallow using it at the CQL level.

**Comment by bhalevy** [comment]
We already have 628dd165199a748b7e39400349b6e72f1955c138 since 4.0.
so I think we can return an error at the CQL level when creating or altering a table.

Cc @eliransin @nyh @raphaelsc

**Comment by nyh** [comment]
@bhalevy we can make forbidding DTCS optional (a "safe mode" option, like the one to forbid SimpleStrategy) - and make this option the default (or not yet the default).
Alternatively, we can also decide to prohibit DTCS unconditionally - and not even provide a way to override this prohibition.
So which way shall we go?

**Comment by dorlaor** [comment]
I think that there is no value in DTCS over TWCS and we should push users
to just convert. In such a case it may be better to just disable it. I
don't have
a strong opinion here

**Comment by nyh** [comment]
The nice thing about having an option "--restrict-dtcs" and turning it on by default (to prevent dtcs from being used) is that someone who feels very strongly about using DTCS still can, by disabling this option. We're not planning to remove the support for DTCS in the code anyway (since existing clusters may be using this compaction strategy).

**Comment by bhalevy** [comment]
> So which way shall we go?

Summoning @tzach too

**Comment by tzach** [comment]
I doubt anyone is using DTCS
@nyh suggestion make sense: 
- Disable DTCS by default 
- Remove DTCS in the next major release (2022.1, 5.0) 
- Announce both clearly in release notes and upgrade guide

**Comment by raphaelsc** [comment]
> The nice thing about having an option "--restrict-dtcs" and turning it on by default (to prevent dtcs from being used) is that someone who feels very strongly about using DTCS still can, by disabling this option. We're not planning to remove the support for DTCS in the code anyway (since existing clusters may be using this compaction strategy).

I thinks step 2 should restrict creation of new DTCS tables, but allow existing tables to still be used with warning asking for a switch because DTCS support will soon be removed. Then on step 3, we'd remove DTCS from codebase and users who refused to switch will have DTCS falling back to STCS, like it happens now if any unsupported strategy is used.

**Comment by bhalevy** [comment]
> > The nice thing about having an option "--restrict-dtcs" and turning it on by default (to prevent dtcs from being used) is that someone who feels very strongly about using DTCS still can, by disabling this option. We're not planning to remove the support for DTCS in the code anyway (since existing clusters may be using this compaction strategy).
> 
> Don't think that option is needed. I thinks step 2 should restrict creation of new DTCS tables, but allow existing tables to still be used with warning asking for a switch because DTCS support will soon be removed. Then on step 3, we'd remove DTCS from codebase and users who refused to switch will have DTCS falling back to STCS, like it happens now if any unsupported strategy is used.

@raphaelsc fwiw, the warning is printed since 4.0 (628dd16).
I doubt users actually take any action on log warnings if otherwise everything else seems to work.
Unless we refuse to start and allow starting only with a new option acknowledging and allowing DTCS we can't be sure that the user is aware of DTCS's deprecation.

**Comment by raphaelsc** [comment]
> > > The nice thing about having an option "--restrict-dtcs" and turning it on by default (to prevent dtcs from being used) is that someone who feels very strongly about using DTCS still can, by disabling this option. We're not planning to remove the support for DTCS in the code anyway (since existing clusters may be using this compaction strategy).
> > 
> > 
> > Don't think that option is needed. I thinks step 2 should restrict creation of new DTCS tables, but allow existing tables to still be used with warning asking for a switch because DTCS support will soon be removed. Then on step 3, we'd remove DTCS from codebase and users who refused to switch will have DTCS falling back to STCS, like it happens now if any unsupported strategy is used.
> 
> @raphaelsc fwiw, the warning is printed since 4.0 ([628dd16](https://github.com/scylladb/scylla/commit/628dd165199a748b7e39400349b6e72f1955c138)).
> I doubt users actually take any action on log warnings if otherwise everything else seems to work.
> Unless we refuse to start and allow starting only with a new option acknowledging and allowing DTCS we can't be sure that the user is aware of DTCS's deprecation.

makes sense. thanks for the explanation.

**Comment by bhalevy** [comment]
@nyh what about existing tables that the user may have that use DTCS?
I think scylla should refuse to start with such tables if `restrict_dtcs=enabled`. Otherwise, the user might not realize they have them.

**Comment by nyh** [comment]
@bhalevy my original thinking was that these options are meant to prevent users from doing certain operations (in this case creating a new table) - not preventing users from booting after an upgrade, which is a rather serious problem. Although we *could* do what you are suggesting too...
My personal belief (but I hope that @tzach or @slivne will chime in with some advice) is that we should have an external tool to check for pre-existing problems like DTCS tables and suggest to the user what to do in this case. I don't think that Scylla itself needs to contain this logic.

**Comment by bhalevy** [comment]
> @bhalevy my original thinking was that these options are meant to prevent users from doing certain operations (in this case creating a new table) - not preventing users from booting after an upgrade, which is a rather serious problem. Although we _could_ do what you are suggesting too...

I'm afraid user might stay unaware of the fact they have preexisting tables with DTCS and will be very surprised when we stop supporting them.  The surprise is quite similar to scylla refusing to start, but in this heads-up scenario the users will have more time, to temporarily allow DTCS, and then to convert to TWCS in their own pace.

> My personal belief (but I hope that @tzach or @slivne will chime in with some advice) is that we should have an external tool to check for pre-existing problems like DTCS tables and suggest to the user what to do in this case. I don't think that Scylla itself needs to contain this logic.

That sounds good too.  If there's agreement around such a tool
we should track it more officially and plan around it.

**Comment by eliransin** [comment]
> is that we should have an external tool to check for pre-existing problems like DTCS tables and suggest to the user what to do in this case. I don't think that Scylla itself needs to contain this logic.

The scylla-health-check was mentioned several times in that context. Today it only collects data but it can be easily adapted to do some analysis too. The only question with such tool is do you run the most recent version prior to installation or after the installation.

**Comment by avikivity** [comment]
Not a bug, not backporting.
