### ISSUE TITLE
Read-before-write for materialized view updates can overload user reads

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#8919]
Materialized view updates may need to perform read-before-write. These reads are generally executed with the same priority as regular user reads, which means that a write-intensive workload on a table with materialized views may cause problems when reading from this table. Namely, read-before-write ops can take all the resources of a given replica (semaphore units required to create a reader, etc), which would cause all user reads to time out on the replicas.

The situation is exacerbated by the fact that read-before-write ops have an extremely long timeout:
https://github.com/scylladb/scylla/blob/a60e73fe14912de50de9567f26022aaceb734d76/service/storage_proxy.cc#L2529-L2533
The rationale for this 5 minute timeout was to prevent the replica from writing too many hints when reads start timing out, which makes sense on its own, but it also means that once the reading queues gets full, these read-before-write operations are likely to pile up and overload the readers altogether. That, in turn, will mean that regular user reads would start failing.

There are at least two distinct problems causing the overload:
 1. Read-before-write ops are currently treated with the same priority as user reads, which is problematic. It's possible to reach a state when user writes are not yet subject to backpressure, but user reads already start failing because read-before-write ops took all the resources. It should be revised whether read-before-write should have the same priority as user reads, or perhaps have lower priority. With lower priority, user writes should start getting backpressure **before** user reads start failing, which is preferred.
 2. The 5 minute timeout does its job by delaying the process of writing too many hints, but contributes to piling up the existing requests. Once a replica gets overloaded with read-before-write ops, it's pretty much guaranteed to keep being overloaded for a very long time, because each of these ops have a 5 minute timeout. During that time, many more writes can arrive, which would produce even more read-before-write ops, which would overload the queues even more.

/cc @slivne

**Comment by psarna** [comment]
By the way - the 5 minute timeout is bad, **but** if we had a separate read concurrency semaphore for read-before-writes, the issue would get solved on its own anyway - user reads would be able to proceed because they would have their own pool of resources, while read-before-write ops would get stuck, which means they would induce write backpressure and things should go back to normal (assuming the write concurrency is bounded, but that's a preexisting assumption).

**Comment by psarna** [comment]
As a quick visualisation of the problem, here's a sample cql-pytest code which currently fails, because our read concurrency semaphore for user reads is hardcoded to 100 units. The test runs a thread with read concurrency == 85, and a separate write workload which induces some read-before-write ops from materialized view updates. It can be observed that write backpressure does not happen (because writes itself succeed), but user reads are already affected. Code:
```python
import threading
def test_read_concurrency(cql, test_keyspace):
    schema = 'p int, c1 int, c2 int, v int, primary key (p,c1,c2)'
    with new_test_table(cql, test_keyspace, schema) as table:
        cql.execute(f"CREATE INDEX ON {table}(c1)")
        prep = cql.prepare(f"INSERT INTO {table}(p,c1,c2) VALUES (1, ?, 1)")

        def read_stuff():
            import time
            time.sleep(3)
            futs = []
            prep = cql.prepare(f"SELECT * FROM {table}")
            for i in range(100000):
                if i % 85 == 0:
                    print("r", i)
                    for fut in futs:
                        fut.result()
                    futs = []
                fut = cql.execute_async(prep, [])
                futs.append(fut)

        reader = threading.Thread(target=read_stuff)
        reader.start()
        futs = []
        for k in range(10):
            print("k", k)
            for i in range(100000):
                if i % 10000 == 0:
                    print("w", i)
                    for fut in futs:
                        fut.result()
                    futs = []
                fut = cql.execute_async(prep, [i])
                futs.append(fut)
            cql.execute(f"DELETE FROM {table} using timeout 10h WHERE p = 1")
        reader.join()
        res = [row for row in cql.execute(f"SELECT * FROM {table}_c1_idx_index")]
        assert len(res) == 0
```

After applying this simple patch which makes all read-before-write ops use the streaming semaphore (which is most likely **not** desired, because then write backpressure can fire too soon with other streaming ops happening at the same time), the test no longer fails, because read-before-write no longer steals resources from user reads:
```diff
diff --git a/table.cc b/table.cc
index 4733c7321..9937ce3c6 100644
--- a/table.cc
+++ b/table.cc
@@ -2252,7 +2252,7 @@ future<row_locker::lock_holder> table::do_push_view_replica_updates(schema_ptr s
 future<row_locker::lock_holder> table::push_view_replica_updates(const schema_ptr& s, mutation&& m, db::timeout_clock::time_point timeout,
         tracing::trace_state_ptr tr_state, reader_concurrency_semaphore& sem) const {
     return do_push_view_replica_updates(s, std::move(m), timeout, as_mutation_source(),
-            std::move(tr_state), sem, service::get_local_sstable_query_read_priority(), {});
+            std::move(tr_state), *_config.streaming_read_concurrency_semaphore, service::get_local_sstable_query_read_priority(), {});
 }
 
 future<row_locker::lock_holder>
``` 

The above patch is not a recommended solution, but perhaps we should consider a similar mechanism? Yet another semaphore perhaps? Opinions welcome.

@vladzcloudius fyi

**Comment by psarna** [comment]
Grafana screenshot from 2 runs of the cql-pytest above - the first one on current scylla master, in which user reads start returning semaphore errors, and then the second one aftr the patch above applied. All the read-before-write pressure is moved from user reads to another semaphore. Again, using the existing streaming semaphore has its disadvantages, so perhaps another specialized semaphore is in order.

![user_vs_streaming](https://user-images.githubusercontent.com/10433047/123121888-d23d5980-d445-11eb-912f-66947776a0ad.png)

**Comment by nyh** [comment]
@psarna is this issue a dup of #8873 which I opened a few days ago?

**Comment by psarna** [comment]
Hm, looks like it is. Tomorrow when in front of my pc I'll close this one and transfer the comments with the test case and monitoring screenshots

**Comment by psarna** [comment]
dup of #8873
