### ISSUE TITLE
evictable_reader: _drop_static_row can drop of the static row from an unintended partition

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#8923]
When the evictable reader recreates in underlying reader, it does it such that it continues from the exact mutation fragment the read was left off from. There are however two special mutation fragments, the partition start and static row that are unconditionally re-emitted at the start of a new read. To work around this, when stopping at either of these fragments the evictable reader sets two flags `_drop_partition_start` and `_drop_static_row` to drop the unneeded fragments (that were already emitted by it) from the underlying reader. These flags are then reset when the respective fragment is dropped. `_drop_static_row` has a vulnerability though: the partition doesn't necessarily have a static row and if it doesn't the flag is currently not cleared and can stay set until the fill buffer call, which might not want to drop the static row at all, but will still do because the flag is set. This can cause the static row to be missing from some partitions.

**Comment by slivne** [comment]
Which branches does this apply to ...

**Comment by denesb** [comment]
> Which branches does this apply to ...

The commit introducing the bug is 394918991.
```
$ git branch --contains 394918991 | grep branch-
  branch-3.2
  branch-3.3
  branch-4.0
  branch-4.1
  branch-4.2
  branch-4.3
  branch-4.4
  branch-4.5
```

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
