### ISSUE TITLE
nodetool status - Owns data is missing

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#893]
`nodetool status` Owns parameter present  **?** in Scylla, actual percent in Cassandra
Testing with Scylla 0.17, Cassandra 2.1

**scylla**
```
$ nodetool status
Datacenter: us-west-2
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens  Owns    Host ID                               Rack
UN  54.201.206.206  71.77 KB   256     ?       3acc23cf-bbfe-47c0-8b43-380baefe41ae  2b
UN  54.191.208.128  72.27 KB   256     ?       c560fc63-6941-4c2f-b7a8-e681c8f0421e  2b
Datacenter: us-east
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens  Owns    Host ID                               Rack
UN  52.87.239.229   72.27 KB   256     ?       17e62f7f-9b2a-41ba-9cf7-60489f21e7c9  1b
UN  52.87.247.79    72.27 KB   256     ?       434266fb-e09e-4f86-a44d-ab9c8394cb1a  1b
Datacenter: us-west
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens  Owns    Host ID                               Rack
UN  52.53.255.236   72.02 KB   256     ?       07045a4f-c615-4ac5-8a50-4a6b27f1a800  1a
UN  52.53.226.233   72.02 KB   256     ?       8513b473-5dd4-4814-9889-69ceaa8e3836  1a
```

**Cassandra**
```
~$ nodetool status
Datacenter: us-west-2
=====================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens  Owns (effective)  Host ID                               Rack
UN  54.191.120.163  196.32 KB  256     34.8%             acbab769-879e-4903-9076-290fe193d3eb  2b
UN  54.201.210.229  196.54 KB  256     31.4%             d1a21c2d-f949-4bd9-8f90-29a934f9b7f2  2b
Datacenter: us-west
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens  Owns (effective)  Host ID                               Rack
UN  54.183.150.40   196.82 KB  256     35.4%             e6a2d764-1d44-4658-9bf4-2b7b7cb431c2  1a
UN  54.183.152.214  200.49 KB  256     32.2%             1d8c9f18-dc3b-4b9a-9471-b6e064ab3dc0  1a
Datacenter: us-east
===================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address         Load       Tokens  Owns (effective)  Host ID                               Rack
UN  52.91.72.186    200.88 KB  256     32.7%             6fb939ba-f7c0-48b1-9ed5-0bbe681effb7  1b
UN  52.90.4.157     196.01 KB  256     33.6%             7e536878-9568-4d24-a1c7-1a0b47220f7e  1b

```

**Comment by amnonh** [comment]
Could be related to #928

**Comment by asias** [comment]
@amnonh With #928 fixed, I still saw below in a clean cluster.  Note the last line "Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless". We don't have non-system keyspace at all.

What http APIs does nodetool status use ?

```
$ nodetool status
Datacenter: dc1
===============
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens  Owns    Host ID                               Rack
UN  127.0.0.1  49.77 KB   256     ?       bf6ca61e-27fa-4ff1-a0d8-02a9780a48c0  rack1
UN  127.0.0.2  16.81 KB   256     ?       5cf9bb32-e0a8-42f2-9f0d-17c10d82d1c6  rack1
UN  127.0.0.3  50.04 KB   256     ?       fe8ff512-2e85-4acb-a24a-fcb50b7768d6  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless
```

**Comment by amnonh** [comment]
On Wed, Mar 9, 2016 at 9:25 AM, Asias He <notifications@github.com> wrote:

> @amnonh <https://github.com/amnonh> With #928
> <https://github.com/scylladb/scylla/issues/928> fixed, I still saw below
> in a clean cluster. Note the last line "Note: Non-system keyspaces don't
> have the same replication settings, effective ownership information is
> meaningless". We don't have non-system keyspace at all.
>
> What http APIs does nodetool status use ?
>
It depends if it is used with a keyspace or without (does it work in
Cassandra without a keyspace?)
With keyspace it's :
 get_effective_ownership
/storage_service/ownership/{keyspace}
Without it's
get_ownership
/storage_service/ownership/

$ nodetool status

**Comment by asias** [comment]
On Wed, Mar 9, 2016 at 3:47 PM, Amnon Heiman <notifications@github.com>
wrote:

> On Wed, Mar 9, 2016 at 9:25 AM, Asias He <notifications@github.com> wrote:
>
> > @amnonh <https://github.com/amnonh> With #928
> > <https://github.com/scylladb/scylla/issues/928> fixed, I still saw below
> > in a clean cluster. Note the last line "Note: Non-system keyspaces don't
> > have the same replication settings, effective ownership information is
> > meaningless". We don't have non-system keyspace at all.
> >
> > What http APIs does nodetool status use ?
> >
> It depends if it is used with a keyspace or without (does it work in
> Cassandra without a keyspace?)
>

Yes. See the example in the bug report.


> With keyspace it's :
> get_effective_ownership
> /storage_service/ownership/{keyspace}
> Without it's
> get_ownership
> /storage_service/ownership/
>

I do not find any problem in our get_ownership implementation.

How does nodetool decide if there are any non-system keyspace (with which
http API)? Since get_ownership get the correct number. I suspect we might
have an issue in the jmx or nodetool.

```
With a clean cluster:

$ curl -X GET "http://localhost:10000/storage_service/ownership"
[{"value": "0.344980061", "key": "127.0.0.1"},{"value": "0.33628872",
"key": "127.0.0.2"},{"value": "0.318731278", "key": "127.0.0.3"}]

$ curl -X GET "http://localhost:10000/storage_service/ownership/keyspace1"
{"message": "Keyspace keyspace1 Does not exist", "code": 400

Create keyspace

$ curl -X GET "http://localhost:10000/storage_service/ownership"
[{"value": "0.344980061", "key": "127.0.0.1"},{"value": "0.33628872",
"key": "127.0.0.2"},{"value": "0.318731278", "key": "127.0.0.3"}]

$ curl -X GET "http://localhost:10000/storage_service/ownership/keyspace1"
[{"value": "0.344980061", "key": "127.0.0.1"},{"value": "0.33628872",
"key": "127.0.0.2"},{"value": "0.318731278", "key": "127.0.0.3"}]
```



> $ nodetool status
> > Datacenter: dc1
> > ===============
> > Status=Up/Down
> > |/ State=Normal/Leaving/Joining/Moving
> > -- Address Load Tokens Owns Host ID Rack
> > UN 127.0.0.1 49.77 KB 256 ? bf6ca61e-27fa-4ff1-a0d8-02a9780a48c0 rack1
> > UN 127.0.0.2 16.81 KB 256 ? 5cf9bb32-e0a8-42f2-9f0d-17c10d82d1c6 rack1
> > UN 127.0.0.3 50.04 KB 256 ? fe8ff512-2e85-4acb-a24a-fcb50b7768d6 rack1
> >
> > Note: Non-system keyspaces don't have the same replication settings,
> effective ownership information is meaningless
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/scylladb/scylla/issues/893#issuecomment-194150932>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/893#issuecomment-194164268>.
>



-- 
Asias

**Comment by amnonh** [comment]
The api that fail is:
curl -X GET "http://localhost:10000/storage_service/ownership/null"
{"message": "Can't find a keyspace system_traces", "code": 400}

The API actually runs:
storage_service::effective_ownership with keyspace == ""

I'll compare it to origin

**Comment by amnonh** [comment]
Ok, here's the deal, it's not working in origin also.
When you check effective_ownership for an empty cluster, you actually check the system_traces (which we don't have)

In origin
For empty cluster it's true that you get:
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens  Owns (effective)  Host ID                               Rack
UN  127.0.0.1  51.59 KB   256     100.0%            a6d66826-23a0-4f7a-833e-ed060d26d4e3  rack1
UN  127.0.0.2  51.59 KB   256     100.0%            01ac4b54-1a6f-4db0-8bdc-f54f68dbc4d2  rack1

But for non empty cluster:
Datacenter: datacenter1
=======================
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address    Load       Tokens  Owns    Host ID                               Rack
UN  127.0.0.1  144.76 MB  256     ?       89c38ff3-9ac2-4e15-8ff8-d3a085d30f85  rack1
UN  127.0.0.2  30.97 MB   256     ?       b4964644-a83f-4cbf-a6b0-903b02b71152  rack1

Note: Non-system keyspaces don't have the same replication settings, effective ownership information is meaningless

**Comment by tzach** [comment]
Thanks @amnonh if Scylla and C* have the same functionality, we can leave it be
