### ISSUE TITLE
skiplist vs btree

### ISSUE THREAD

**Issue by chinese20201103** [scylladb/scylla#8930]
apache-cassandra-3.11.6:
public class Memtable implements Comparable<Memtable> {
	private final ConcurrentNavigableMap<PartitionPosition, AtomicBTreePartition> partitions = new ConcurrentSkipListMap<>();
}
scylla-scylla-4.6.dev:
class memtable final : public enable_lw_shared_from_this<memtable>, private logalloc::region {
	using partitions_type = double_decker<int64_t, memtable_entry,
                            dht::raw_token_less_comparator, dht::ring_position_comparator,
                            16, bplus::key_search::linear>;
        partitions_type partitions;
}
It seems that skiplist is more efficient than btree.

**Comment by avikivity** [comment]
Please use the mailing list for development discussions and the issue tracker to report bugs.
