### ISSUE TITLE
Scylla systemd service should always configure a proper clock source

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#8936]
*Installation details*
HEAD: 373fa3fa07d366ea5a8632f0ddffae6f226f64c3

*Description*
Scylla `systemd` scripts should always configure clock source using the corresponding perftune.py mode:

```
perftune.py --tune system --tune-clock
```

When the clock source is set to something like `xen` like on Ubuntu 20 AWS AMI (which translates to pv-clock) the performance is going to be suboptimal.

**Comment by vladzcloudius** [comment]
@slivne @penberg FYI

**Comment by slivne** [comment]
@syuu1228 please also validate that the setting is correct for the GCE images

**Comment by syuu1228** [comment]
Can we close this too since https://github.com/scylladb/scylla-enterprise/issues/1830 closed?
Or is it different problem?

**Comment by slivne** [comment]
Turns out they were not using the AMI ....

**Comment by vladzcloudius** [comment]
> Turns out they were not using the AMI ....

Right. Sorry, forgot about the OSS issue.
