### ISSUE TITLE
named_semaphore_timed_out triggers cql read failure error rather than a read timeout

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#8958]
The storage_proxy `abstract_read_resolver` implements logic to intentionally swallow timeout errors from replicas and let the query timeout and be reported as a read timeout error to the client.
See https://github.com/scylladb/scylla/blob/029991bfc236f0a3dfc1e8205b1930c85ae98b09/service/storage_proxy.cc#L2812-L2820

The `named_semaphore_timed_out` error returned from https://github.com/scylladb/scylla/blob/029991bfc236f0a3dfc1e8205b1930c85ae98b09/reader_concurrency_semaphore.cc#L357-L361
When a read times out in the admission queue may be wrongly propagated as a read error.

On Wed, 2021-06-30 at 10:45 +0300, @denesb wrote:
> > > Shouldn't reader concurrency semaphores also throw this timeout
> > > error? 
> > > So far they have been caught by the clause below, now we will have
> > > two 
> > > different ways of reporting timeouts.
> > > 
> > 
> > That's a good point.
> > 
> > Currently they set a named_semaphore_timed_out exception when a read
> > expires on the admission queue.
> > 
> > Since we currently rely on the description of this exception to
> > analyze overload issue
> > we can either print a warning there and throw a timed_out_error, or
> > catch named_semaphore_timed_out
> > here, print a warning and handle it the same way as the other
> > timeouts.
> 
> We also have the diagnostics dump which already logs detailed
> diagnostics on timeout and queue overflow.

so let's return a generic `timed_out_error` instead.

**Comment by bhalevy** [comment]
The issue was renamed to indicate the problem, not a solution.
It turns out that throwing a timed_out_error from the r_c_s expiry_handler is higher risk than just handling the `semaphore_timed_out` error in the same way as `timed_out_error`, as there are already several places that would break if the named_semaphore_timed_out exception changes.

**Comment by bhalevy** [comment]
Refs #8846

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
