### ISSUE TITLE
dist:ami - scylla is not installed and not starting

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#897]
using: ami-b53218df

which is built using: seastar-dev (shlomi/unstable_ami)

which is using unstable/master/latest

I updated packer url as the current download link is bad

**Comment by syuu1228** [comment]
Packer URL need to fix, but without the problem, I able to build AMI that works finely.
On CentOS7 VM, git clone latest master -> apply packer url fix patch -> copy variables.json to dist/ami ->  ./dist/ami/build_ami_local.sh
AMI id is us-east-1: ami-57351f3d

**Comment by slivne** [comment]
Only doing this changes work because you are not using the repo of unstable
that is using head   rpms

you are using instead repo of latest (0.17)  that does not have all the
changes

Check the branch i memtioned on seastar-dev
