### ISSUE TITLE
Feature: commitlog compression

### ISSUE THREAD

**Issue by amoskong** [scylladb/scylla#8972]
### Description

Scylla doesn't support commitlog compression.

Quote from https://cassandra.apache.org/doc/latest/architecture/storage_engine.html:

`commitlog_compression`: Compression to apply to the commitlog. If omitted, the commit log will be written uncompressed. LZ4, Snappy, Deflate and Zstd compressors are supported.

```
(Default Value: (complex option):

#   - class_name: LZ4Compressor
#     parameters:
#         -
```

Related issue: https://github.com/scylladb/scylla/issues/1638

### Question

@tzach @slivne @elcallio Do we have plan to add the feature?

**Comment by slivne** [comment]
we are against that

**Comment by slivne** [comment]
https://github.com/scylladb/scylla/issues/24
