### ISSUE TITLE
Incorrect token values for varint and decimal types.

### ISSUE THREAD

**Issue by pdziepak** [scylladb/scylla#898]
...incorrect meaning "different from Cassandra" here.

Since dadd097f9c888af275f5a64f658fe84f1c62f23a "do not use boost::multiprecision::msb()" our serialized form of varint and decimal may have some additionaly leading zeros which do not affect deserialization but do affect token computation.

With data like this:
```
create table foo (a decimal primary key, b int);
insert into foo (a, b) values (12.0, 5);
insert into foo (a, b) values (12, 6);
```

Scylla:
```
select token(a), a, b from foo;

 system.token(a)      | a    | b
----------------------+------+---
 -8694400474557728617 | 12.0 | 5
  7967282806546469360 |   12 | 6

```

Cassandra and Scylla with dadd097f9c888af275f5a64f658fe84f1c62f23a reverted:
```
select token(a), a, b from foo;

 token(a)             | a    | b
----------------------+------+---
 -4103090167237467071 |   12 | 6
  6008283563146703107 | 12.0 | 5
```

Do we still need to support Boost versions older than 1.55?

**Comment by avikivity** [comment]
Ubuntu 14.04 ships with 1.54.

**Comment by avikivity** [comment]
But, doing

    apt-get update
    apt-cache search boost1.55

I do get results.

@tgrabiec can you verify that it works?  And add checks and magic in configure.py to verify we have the right package and that -I points to it?

**Comment by tgrabiec** [comment]
@avikivity Would it be enough to check `BOOST_VERSION` [1] from units which depend on it? Python magic sounds more complicated.

[1] http://www.boost.org/doc/libs/1_44_0/libs/config/doc/html/boost_config/boost_macro_reference.html#boost_config.boost_macro_reference.boost_informational_macros

**Comment by avikivity** [comment]
BOOST_VERSION is enough.  I thought we'd need to divert the -I, but I now see the libboost1.55-dev installs to /usr/include/boost, not some other location.

Since no debian magic is needed, I can do it.

**Comment by nyh** [comment]
On Thu, Feb 11, 2016 at 1:40 PM, Avi Kivity <notifications@github.com>
wrote:

> BOOST_VERSION is enough. I thought we'd need to divert the -I, but I now
> see the libboost1.55-dev installs to /usr/include/boost, not some other
> location.
>

I checked, and "apt-get upgrade" on Ubuntu 14.04 does *not* upgrade to 1.55
- it leaves 1.54.

So 1.55 exists, but it's a completely separate set of packages, and
overwrites stuff from the normal boost packages?
Weird. Oh, well....

**Comment by tgrabiec** [comment]
@avikivity A patch to configure.py is on the list

**Comment by slivne** [comment]
now that we require boost 1.55 do we need to revert dadd097f9c888af275f5a64f658fe84f1c62f23a to close this ?
