### ISSUE TITLE
Some of appending_hash<> instantiations have throwing operator()

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla#8983]
The `::feed_hash()` and the visitor lambda in `digester::feed_hash()` are marked noexcept (since 5adb8e5) but they call potentially throwing `appending_hash<T>()::operator()`.

**Comment by bhalevy** [comment]
Need to backport starting from 4.3 (that has 19ffc9455de30012666de5c2f71c4095bc5034d6)

**Comment by avikivity** [comment]
Backported to 4.3, 4.4, 4.5.
