### ISSUE TITLE
runtime_exception thrown from a compation flow during jepsen :slow-network tests

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#899]
When scylla is stopped (`killall scylla` at the end of jepsen't `:slow-network` tests scylla thrown the exception below: 

```
ERROR [shard 0] compaction_manager - compaction failed: read exception: std::runtime_error (Compaction for system/local was deliberately stopped.)
```
The exception should not go all the way up to a user and should be caught before and handled/ignored as appropriate. Some warning message is welcome however.

**Comment by nyh** [comment]
@raphaelsc sent yesterday a patch titled "[PATCH v3] sstables: make compaction stop report user-friendly" which I think should have fixed exactly this problem.
Can you please test this patch and review it (if it wasn't already committed by now?)

**Comment by vladzcloudius** [comment]
On 02/10/2016 11:39 PM, nyh wrote:
>
> @raphaelsc <https://github.com/raphaelsc> sent yesterday a patch 
> titled "[PATCH v3] sstables: make compaction stop report 
> user-friendly" which I think should have fixed exactly this problem.
> Can you please test this patch and review it (if it wasn't already 
> committed by now?)
>

@nyh sure. I'll pick it and check the run. Thanks.

**Comment by slivne** [comment]
@vladzcloudius ping

**Comment by vladzcloudius** [comment]
@slivne The issue didn't reproduce. The issue may be closed.
