### ISSUE TITLE
cql-pytest tests are now failing on Cassandra 3

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#8990]
After commit 76227fafad655933d679dc3218a65f22bd3f40c7 ("cql-pytest: use NetworkTopologyStrategy, not SimpleStrategy|), the cql-pytest tests now `NetworkTopologyStrategy` instead of `SimpleStrategy` in the test keyspaces. The tests continue to use the `replication_factor` option, which is also supported by `NetworkTopologyStrategy`. This is a recently added ability, which is called "auto expand".

However, although Cassandra has also had this "auto expand" feature for more than two years now (see https://issues.apache.org/jira/browse/CASSANDRA-14303), it was only added to Cassandra 4, and never reached any Cassandra 3 release. This means that running cql-pytest against Cassandra (i.e., `test/cql-pytest/run-cassandra`) now fails for anyone who happens to have Cassandra 3 installed.

While users can easily work around this problem by testing with Cassandra 4, it would be even better if developers could develop cql-pytest tests (and check them on Cassandra) without insisting on any specific Cassandra version. Moreover, in the future we might want to deliberately run cql-pytest tests on different Cassandra versions (e.g., to see how a specific feature changed across Cassandra feature), and we don't want to be bothered by irrelevant breakages like this one. 

The solution to this issue is easy: don't use `replication_factor` in the tests (except where the intention of the test is to check that feature) and instead list the single dc's name, using the classic NetworkTopologyStrategy syntax.

This problem was discovered by @psarna.

**Comment by avikivity** [comment]
No production issue, not backporting.
