### ISSUE TITLE
Provide support/workaround for thrif.cql3_prepare_stamenets

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#9]
cassandra-stress user profile supports multiple modes (thrift,cql3)

As a simple workaround, I had to change cassandra-stress as it creates thrift and cql3 connection and then depending on the transport decides to use or the other - our thrift support is lacking

shlomi@localhost~/cassandra/tools/stress (pekka_unitests)$ git diff src/org/apache/cassandra/stress/StressProfile.java
diff --git a/tools/stress/src/org/apache/cassandra/stress/StressProfile.java b/tools/stress/src/org/apache/cassandra/stress/StressProfile.java
index e223fbd..f744c21 100644
--- a/tools/stress/src/org/apache/cassandra/stress/StressProfile.java
+++ b/tools/stress/src/org/apache/cassandra/stress/StressProfile.java
@@ -365,6 +365,7 @@ public class StressProfile implements Serializable

```
                 JavaDriverClient client = settings.getJavaDriverClient();
                 String query = sb.toString();
```

+/*
                     try
                     {
                         thriftInsertId = settings.getThriftClient().prepare_cql3_query(query, Compression.NONE);
@@ -373,6 +374,8 @@ public class StressProfile implements Serializable
                     {
                         throw new RuntimeException(e);
                     }
+*/
-                    thriftInsertId = 0;
                   insertStatement = client.prepare(query);
               }
           }

We need to provide a better workaround as we cannot change cassandra-stress

**Comment by duarten** [comment]
We now support this and can even use c-s to test through the thrift api :)
