### ISSUE TITLE
main: service_level_controller needs to be stopped both right after it starts and before storage_proxy drain_on_shutdown

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9014]
As per 32bcbe59ad9, the sl_controller is stopped after set_distributed_data_accessor is called.
However if scylla shuts down before that happens, the sl_controller still needs to be stopped, right after https://github.com/scylladb/scylla/blob/3fda13e20e10f431d8dbfa735958c697c1f1c7e0/main.cc#L837

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
