### ISSUE TITLE
[AMI 0.17] Scylla-JMX is issuing a java.lang.NullPointerException in the thread "Dropped messages"

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#902]
Issue: 

Context:

1) Start with a scylla cluster (instance type  t2micro, but it reproduces with other sizes, such as c4.xlarge)
2) Run cassandra-stress on that cluster
3) After 15 minutes of c-s, stop the AWS instance of one of the nodes. Other nodes gossip reports node down:

    15:57:57 DEBUG| [54.183.195.134] [stdout] Feb 10 17:57:57 ip-172-31-18-112 scylla[2108]: INFO  [shard 0] gossip - InetAddress 172.31.18.111 is now DOWN
    15:57:57 DEBUG| [54.183.193.208] [stdout] Feb 10 17:57:57 ip-172-31-18-113 scylla[2114]: INFO  [shard 0] gossip - InetAddress 172.31.18.111 is now DOWN
    15:57:57 DEBUG| [54.193.37.222] [stdout] Feb 10 17:57:57 ip-172-31-18-114 scylla[2098]: INFO  [shard 0] gossip - InetAddress 172.31.18.111 is now DOWN
    15:57:57 DEBUG| [54.193.61.5] [stdout] Feb 10 17:57:57 ip-172-31-18-110 scylla[2107]: INFO  [shard 0] gossip - InetAddress 172.31.18.111 is now DOWN
    15:57:57 DEBUG| [54.183.240.195] [stdout] Feb 10 17:57:57 ip-172-31-18-109 scylla[2103]: INFO  [shard 0] gossip - InetAddress 172.31.18.111 is now DOWN

shortly after:

    15:58:02 DEBUG| [54.183.240.195] [stdout] Feb 10 17:58:02 ip-172-31-18-109 scylla[2103]: INFO  [shard 0] rpc - client 172.31.18.111: client connection dropped: read: Connection reset by peer
    15:58:02 DEBUG| [54.193.37.222] [stdout] Feb 10 17:58:02 ip-172-31-18-114 scylla[2098]: INFO  [shard 0] rpc - client 172.31.18.111: client connection dropped: read: Connection reset by peer
    15:58:02 DEBUG| [54.193.61.5] [stdout] Feb 10 17:58:02 ip-172-31-18-110 scylla[2107]: INFO  [shard 0] rpc - client 172.31.18.111: client connection dropped: read: Connection reset by peer
    15:58:02 DEBUG| [54.183.193.208] [stdout] Feb 10 17:58:02 ip-172-31-18-113 scylla[2114]: INFO  [shard 0] rpc - client 172.31.18.111: client connection dropped: read: Connection reset by peer

4) Start the instance again. After a while, it gets a new IP:

    15:58:59 DEBUG| Node lmr-scylla-db-node-88c994d5-3 [54.193.37.181 | 172.31.18.111] (seed: None): Got new public IP 54.67.92.86

5) Nodes notice its missing buddy is back to life:

    15:59:51 DEBUG| [54.193.37.222] [stdout] Feb 10 17:59:51 ip-172-31-18-114 scylla[2098]: INFO  [shard 0] gossip - Node 172.31.18.111 has restarted, now UP
    15:59:52 DEBUG| [54.183.240.195] [stdout] Feb 10 17:59:52 ip-172-31-18-109 scylla[2103]: INFO  [shard 0] gossip - Node 172.31.18.111 has restarted, now UP
    15:59:53 DEBUG| [54.193.61.5] [stdout] Feb 10 17:59:53 ip-172-31-18-110 scylla[2107]: INFO  [shard 0] gossip - Node 172.31.18.111 has restarted, now UP
    15:59:54 DEBUG| [54.183.195.134] [stdout] Feb 10 17:59:54 ip-172-31-18-112 scylla[2108]: INFO  [shard 0] gossip - Node 172.31.18.111 has restarted, now UP

6) Then things get weird. Nodes start logging things like:

    16:00:11 DEBUG| [54.183.240.195] [stdout] Feb 10 18:00:11 ip-172-31-18-109 scylla[2103]: INFO  [shard 0] rpc - client 172.31.18.111: client connection dropped: Connection timed out
    16:00:11 DEBUG| [54.183.240.195] [stdout] Feb 10 18:00:11 ip-172-31-18-109 scylla[2103]: WARN  [shard 0] gossip - Fail to send EchoMessage to 172.31.18.111:0: rpc::timeout_error (rpc call timed out)
    16:00:11 DEBUG| [54.183.240.195] [stdout] Feb 10 18:00:11 ip-172-31-18-109 scylla[2103]: WARN  [shard 0] failure_detector - Not marking nodes down due to local pause of 128294 > 5000 (milliseconds)
    16:00:11 DEBUG| [54.183.240.195] [stdout] Feb 10 18:00:11 ip-172-31-18-109 scylla[2103]: INFO  [shard 0] storage_service - Node 172.31.18.111 state jump to normal
    16:00:11 DEBUG| [54.183.240.195] [stdout] Feb 10 18:00:11 ip-172-31-18-109 scylla[2103]: WARN  [shard 0] gossip - Fail to send EchoMessage to 172.31.18.111:0: rpc::timeout_error (rpc call timed out)
    16:00:11 DEBUG| [54.183.240.195] [stdout] Feb 10 18:00:11 ip-172-31-18-109 scylla[2103]: WARN  [shard 0] gossip - Fail to send EchoMessage to 172.31.18.111:0: rpc::timeout_error (rpc call timed out)
    16:00:11 DEBUG| [54.183.240.195] [stdout] Feb 10 18:00:11 ip-172-31-18-109 scylla[2103]: WARN  [shard 0] gossip - Fail to send EchoMessage to 172.31.18.111:0: rpc::timeout_error (rpc call timed out)
    16:00:11 DEBUG| [54.183.240.195] [stdout] Feb 10 18:00:11 ip-172-31-18-109 scylla[2103]: WARN  [shard 0] gossip - Fail to send EchoMessage to 172.31.18.111:0: rpc::timeout_error (rpc call timed out)
    16:00:11 DEBUG| [54.183.240.195] [stdout] Feb 10 18:00:11 ip-172-31-18-109 scylla[2103]: WARN  [shard 0] gossip - Fail to send EchoMessage to 172.31.18.111:0: rpc::timeout_error (rpc call timed out)

And then scylla-jmx reports:

    16:00:11 DEBUG| [54.183.240.195] [stdout] Feb 10 18:00:11 ip-172-31-18-109 scylla-jmx[2115]: Exception in thread "Dropped messages" java.lang.NullPointerException
    16:00:11 DEBUG| [54.183.240.195] [stdout] Feb 10 18:00:11 ip-172-31-18-109 scylla-jmx[2115]: at org.apache.cassandra.net.MessagingService$CheckDroppedMessages.run(MessagingService.java:131)
    16:00:11 DEBUG| [54.183.240.195] [stdout] Feb 10 18:00:11 ip-172-31-18-109 scylla-jmx[2115]: at java.util.TimerThread.mainLoop(Timer.java:555)
    16:00:11 DEBUG| [54.183.240.195] [stdout] Feb 10 18:00:11 ip-172-31-18-109 scylla-jmx[2115]: at java.util.TimerThread.run(Timer.java:505)

Regardless of whether the message:

    [shard 0] gossip - Fail to send EchoMessage to 172.31.18.111:0: rpc::timeout_error (rpc call timed out)

Is normal or not, we still shouldn't have that java exception on scylla-jmx.

**Comment by lmr** [comment]
@amnonh, you might want to take a look at this issue.

**Comment by slivne** [comment]
@lmr aside from this error are other nodetool commands working 

If nothing in nodetool is working this is a showstopper

If everything else is working and only this exception is thrown then its high
