### ISSUE TITLE
continuous_data_consumer: the consumer can't be fast-forwarded after skipping bytes at the end

### ISSUE THREAD

**Issue by wmitros** [scylladb/scylla#9024]
If the state processor that we're using returns a `skip_bytes` object after consuming a data buffer, and the number of skipped bytes is higher than the number of remaining bytes in the current range, we return the empty buffer as a consumption_result, which does not force the underlying input stream to skip any bytes.
As a result, `_stream_position.position` is not consistent with the position of the input stream.
https://github.com/scylladb/scylla/blob/1ff1c3735b2694d44b7f6641db1ef6e8e9d80927/sstables/consumer.hh#L582-L596

The solution is either returning a `skip_bytes` object with `_remaining` bytes to skip, or perhaps shortening the current range without skipping any bytes in the input stream, by setting `_remaining = 0`, but not changing the value of `_stream_position.position`.

**Comment by avikivity** [comment]
Is there practical impact? Or is it an internals problem that could have practical impact after a later change?

**Comment by wmitros** [comment]
It looks like this problem does not appear currently - we only return skip_bytes in 2 cases:
-  in `index_consume_entry_context` we skip the promoted index, but we use each `index_consume_entry_context` only once and never skip afterwards <- I'm changing this, and that's how I found this issue
-  in `data_consume_rows_context_m` we return skip_bytes only if `mp_row_consumer_m::consume_row_start()` returns `row_processing_result::skip_row`, so only if we got `!_mf_filter->out_of_range()` applying the position of the current row to `_mf_filter`.
  
  I haven't read exactly when `out_of_range()` becomes true, but if it does just what it's name suggests (the range end has been reached already), the question becomes, whether the `_mf_filter` range may end farther than the associated `data_consume_rows_context_m`'s range.

  The `_mf_filter`'s range is basically the range containing all "subranges" in a vector of clustering_ranges , so if I understand correctly, it only filters clustering rows in one partition. The `data_consume_rows_context_m` is always forwarded entire partitions, so our problem should not occur.

**Comment by nyh** [comment]
@wmitros if it's too difficult to write a system test for this because this code is never used from normal CQL requests, it might still be easier to write a unit test in C++ for this. But if that is too difficult too, please just say a few words on how you tested that the new version isn't as broken as the previous version - e.g., you have another feature you are working on, which failed before this fix and now works properly?

**Comment by wmitros** [comment]
@nyh it wasn't actually that difficult to add a test for it, I just got busy with something else yesterday.
I've just added the test to the PR

**Comment by avikivity** [comment]
No impact, not backporting.
