### ISSUE TITLE
Create a tool similar to sstabledump to decode commitlog files

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#9027]
*Installation details*
HEAD: 373fa3fa07d366ea5a8632f0ddffae6f226f64c3

*Description*
Sometimes we need to decode the content of commitlog files, e.g. when debugging hinted handoff related issues.

It would be very helpful to have a tool that would print us the info about the content of a given commitlog file similar to how `sstabledump` prints an info about the SSTable content.

**Comment by vladzcloudius** [comment]
@eliransin @elcallio @slivne @harel-z FYI

**Comment by slivne** [comment]
I am not aware of any such tool for origin (cassandra)  https://issues.apache.org/jira/browse/CASSANDRA-15813

There is a workaround for this:
- start a single server
- create the schema
- copy commitlogs to that server
- boot the node and allow commitlogs to be replaid
- dump the resulting sstables and you have the delta that this commitlogs will try to apply to the data.

**Comment by raphaelsc** [comment]
On Tue, Jul 13, 2021 at 5:28 PM Shlomi Livne ***@***.***>
wrote:

> I am not aware of any such tool for origin (cassandra)
> https://issues.apache.org/jira/browse/CASSANDRA-15813
>
> There is a workaround for this:
>
>    - start a single server
>    - create the schema
>    - copy commitlogs to that server
>    - boot the node and allow commitlogs to be replaid
>    - dump the resulting sstables and you have the delta that this
>    commitlogs will try to apply to the data.
>
>
nice workaround :-)

**Comment by vladzcloudius** [comment]
> I am not aware of any such tool for origin (cassandra) https://issues.apache.org/jira/browse/CASSANDRA-15813

Are we going to wait till Cassandra implements every new feature we are going to add to Scylla from now on?
This approach is going to lead us nowhere, @slivne.

Luckily we haven't done this so far. Otherwise we wouldn't have ICS, Scylla Manager, row level repair and other cool things Cassandra doesn't have.

**Comment by vladzcloudius** [comment]
> There is a workaround for this:

When I opened this GH issue I wasn't looking for a workaround.

**Comment by vladzcloudius** [comment]
Moved to scylla-tools-java: https://github.com/scylladb/scylla-tools-java/issues/266
