### ISSUE TITLE
sstabledump: add support for encrypted SSTables

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#9033]
*Installation details*
HEAD: 373fa3fa07d366ea5a8632f0ddffae6f226f64c3

*Description*
We need to be able to dump SSTables with encryption enabled. Today there is no such ability and `sstabledump` is a very powerful tool that is very useful in the field (e.g. when one needs to debug tombstones related issues).

**Comment by vladzcloudius** [comment]
@eliransin @raphaelsc @slivne FYI

**Comment by raphaelsc** [comment]
better to open an issue at https://github.com/scylladb/scylla-tools-java, which is where sstabledump lives.

**Comment by vladzcloudius** [comment]
Done: https://github.com/scylladb/scylla-tools-java/issues/265
Closing this one.
