### ISSUE TITLE
[AMI 0.17] Failure to add new node to a cluster due to seed node unavailable

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#904]
Running cluster tests on a 0.17 DB cluster revealed a bug on the addition of a new node. The cluster tests create a DB cluster (in this case, 6 nodes using t2.micro instances. The AMI is ami-4431d024, AWS region us-west-2:

    01:03:16 cluster          L0602 INFO | Cluster decommission_monkey-scylla-db-cluster-a23f4061 (AMI: ami-4431d024 Type: t2.micro): (6/6) DB nodes ready. Time elapsed: 681 s

The clusters have a nemesis on them, causing disruption operation. In this case, we had a decomission nemesis going.

The decommission nemesis does a node decommission, verify that the decommissioned node is not on the cluster anymore, then we add a new node to the cluster. We appear to have hit a bug on the addition of the new node. The time line is:

New node is added:

    01:38:19 cluster          L0156 DEBUG| Node decommission_monkey-scylla-db-node-a23f4061-6 [54.191.128.20 | 172.31.33.96] (seed: None): SSH access -> 'ssh -i /var/tmp/decommission_monkey-longevity-test-9c05e28c.pem centos@54.191.128.20'

Its peers recognize it:

    01:39:51 remote           L0182 DEBUG| [54.213.251.193] [stdout] Feb 12 01:39:51 ip-172-31-45-7 scylla[2066]: INFO  [shard 0] gossip - Node 172.31.33.96 is now part of the cluster

New node fails to bootstrap:

    01:40:54 remote           L0182 DEBUG| [54.191.128.20] [stdout] Feb 12 01:40:54 ip-172-31-33-96 scylla[2095]: INFO  [shard 0] storage_service - JOINING: Starting to bootstrap...
    01:40:54 remote           L0182 DEBUG| [54.191.128.20] [stdout] Feb 12 01:40:54 ip-172-31-33-96 scylla[2095]: Exiting on unhandled exception of type 'std::runtime_error': A node required to move the data consistently is down (172.31.45.7).  If you wish to move the data from a potentially inconsistent replica, restart the node with -Dcassandra.consistent.rangemovement=false
    01:40:54 remote           L0182 DEBUG| [54.191.128.20] [stdout] Feb 12 01:40:54 ip-172-31-33-96 scylla[2095]: INFO  [shard 0] compaction_manager - compaction task handler stopped due to shutdown
    01:40:54 remote           L0182 DEBUG| [54.191.128.20] [stdout] Feb 12 01:40:54 ip-172-31-33-96 scylla[2095]: INFO  [shard 0] compaction_manager - compaction task handler stopped due to shutdown

The new node can't see the seed node, then it fails to start. Investigating further, the seed node was missing in action for a few occasions:

    01:40:23 remote           L0182 DEBUG| [54.201.120.99] [stdout] Feb 12 01:40:23 ip-172-31-45-12 scylla[2262]: INFO  [shard 0] gossip - InetAddress 172.31.45.7 is now DOWN
    01:40:50 remote           L0182 DEBUG| [54.191.128.20] [stdout] Feb 12 01:40:50 ip-172-31-33-96 scylla[2095]: INFO  [shard 0] gossip - InetAddress 172.31.45.7 is now DOWN
    01:40:52 remote           L0182 DEBUG| [54.191.137.31] [stdout] Feb 12 01:40:52 ip-172-31-45-11 scylla[2035]: INFO  [shard 0] gossip - InetAddress 172.31.45.7 is now DOWN
    01:40:53 remote           L0182 DEBUG| [54.213.165.80] [stdout] Feb 12 01:40:53 ip-172-31-45-9 scylla[2075]: INFO  [shard 0] gossip - InetAddress 172.31.45.7 is now DOWN
    01:40:53 remote           L0182 DEBUG| [54.201.120.99] [stdout] Feb 12 01:40:53 ip-172-31-45-12 scylla[2262]: INFO  [shard 0] gossip - InetAddress 172.31.45.7 is now DOWN
    01:40:54 remote           L0182 DEBUG| [54.213.154.77] [stdout] Feb 12 01:40:55 ip-172-31-45-8 scylla[2064]: INFO  [shard 0] gossip - InetAddress 172.31.45.7 is now DOWN
    01:41:25 remote           L0182 DEBUG| [54.191.137.31] [stdout] Feb 12 01:41:26 ip-172-31-45-11 scylla[2035]: INFO  [shard 0] gossip - InetAddress 172.31.45.7 is now DOWN
    01:41:25 remote           L0182 DEBUG| [54.213.154.77] [stdout] Feb 12 01:41:26 ip-172-31-45-8 scylla[2064]: INFO  [shard 0] gossip - InetAddress 172.31.45.7 is now DOWN
    01:41:26 remote           L0182 DEBUG| [54.213.165.80] [stdout] Feb 12 01:41:26 ip-172-31-45-9 scylla[2075]: INFO  [shard 0] gossip - InetAddress 172.31.45.7 is now DOWN
    01:41:28 remote           L0182 DEBUG| [54.201.120.99] [stdout] Feb 12 01:41:28 ip-172-31-45-12 scylla[2262]: INFO  [shard 0] gossip - InetAddress 172.31.45.7 is now DOWN
    01:42:27 remote           L0182 DEBUG| [54.191.137.31] [stdout] Feb 12 01:42:27 ip-172-31-45-11 scylla[2035]: INFO  [shard 0] gossip - InetAddress 172.31.45.7 is now DOWN
    01:42:30 remote           L0182 DEBUG| [54.213.154.77] [stdout] Feb 12 01:42:30 ip-172-31-45-8 scylla[2064]: INFO  [shard 0] gossip - InetAddress 172.31.45.7 is now DOWN
    01:42:30 remote           L0182 DEBUG| [54.201.120.99] [stdout] Feb 12 01:42:30 ip-172-31-45-12 scylla[2262]: INFO  [shard 0] gossip - InetAddress 172.31.45.7 is now DOWN
    01:42:31 remote           L0182 DEBUG| [54.213.165.80] [stdout] Feb 12 01:42:31 ip-172-31-45-9 scylla[2075]: INFO  [shard 0] gossip - InetAddress 172.31.45.7 is now DOWN

One of the timestamps coincide with the time the new node tried to bootstrap and failed:

    01:40:54 remote           L0182 DEBUG| [54.213.154.77] [stdout] Feb 12 01:40:55 ip-172-31-45-8 scylla[2064]: INFO  [shard 0] gossip - InetAddress 172.31.45.7 is now DOWN

With the seed node down at the time the new node tried to start, the new node fails to start. Then the other nodes obviously can't connect with it:

    01:42:40 remote           L0182 DEBUG| [54.213.251.193] [stdout] Feb 12 01:42:40 ip-172-31-45-7 scylla[2066]: INFO  [shard 0] rpc - client 172.31.33.96: client connection dropped: Connection refused

Until the rest of the cluster gives up on it. This is a message coming from the seed node (the very node that caused the failure by being out):

    01:42:40 remote           L0182 DEBUG| [54.213.251.193] [stdout] Feb 12 01:42:40 ip-172-31-45-7 scylla[2066]: INFO  [shard 0] gossip - FatClient 172.31.33.96 has been silent for 30000ms, removing from gossip

This seems to be a single point of failure to me (if the seed node is out at that right moment, new nodes will fail to start).

**Comment by lmr** [comment]
I think this traces back to the fact that `scylla-server.service` is not restarting upon failure. I remember that it used to be the case, any reason why we changed that?

**Comment by slivne** [comment]
Scylla and Cassandra support multiple seed nodes in the config - eliminating the single point of failure case.

If I recall correctly we do not restart currently the seed node and leave it running in sdcm - in such a case this seems to be a networking issue.

What RF is used across the cluster ?, if the RF=1 then adding a node when one node is down maybe be blocked because streaming of data may not be possible @asias 

If this is reproducible - can we do a ping test in parallel to see if this is a general networking issue - or something else 

Does this happen with larger instances (not t2.micro ?)

**Comment by asias** [comment]
@lmr what is the RF in the cluster in your test. If it is RF=1, when a node is down in the cluster, we can not add a new node since it could not stream data from existing nodes, i.e. some data will be missing.

**Comment by slivne** [comment]
@lmr can you please provide answers to the above questions - if the RF=3 and  3 nodes were down then that may also explain it.

**Comment by lmr** [comment]
@slivne and @asias, RF=3. Only a single node is down at a time.
