### ISSUE TITLE
Scylla aborts when sstable mutation reader is fast forwarding

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#9049]
Only Scylla < 4.5 is affected. After commit c232d71fc82a from series 7f3083739f (present in 4.5), problem cannot happen anymore.

Problem is triggered when sstable_mutation_reader::fast_forward_to() calls index_reader to advance to next summary entry and index_reader fails to properly close readers for promoted index, so Scylla fails with:
```
 ./seastar/src/core/fstream.cc:172: virtual seastar::file_data_source_impl::~file_data_source_impl():
Assertion `_reads_in_progress == 0' failed.
```

**Comment by avikivity** [comment]
Fixed by 9dce1e4b2b4d576ac31fadd7678b91f37914ab02 on 4.4. Backported to 4.3.
