### ISSUE TITLE
Serializers generated by IDL compiler do not respect type names specified in the IDL

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#905]
Given a schema like this:

```c++
class specific_ranges {
    partition_key pk();
    std::vector<range<clustering_key_prefix>> ranges();
};
```

The IDL compiler will generate the following serializer:

```c++
template<typename Output>
void serialize(Output& buf, const query::specific_ranges& obj) {
  set_size(buf, obj);
  serialize(buf, obj.pk());
  serialize(buf, obj.ranges());
}
```

The format of `pk` and `ranges` is determined not by the types specified in the schema but by effective return type of `pk()` and `ranges()` methods. So types specified in the IDL are effectively ignored.

**Comment by gleb-cloudius** [comment]
On Fri, Feb 12, 2016 at 09:13:15AM -0800, Tomasz Grabiec wrote:
> Given a schema like this:
> 
> ```c++
> class specific_ranges {
>     partition_key pk();
>     std::vector<range<clustering_key_prefix>> ranges();
> };
> ```
> 
> The IDL compiler will generate the following serializer:
> 
> ```c++
> template<typename Output>
> void serialize(Output& buf, const query::specific_ranges& obj) {
>   set_size(buf, obj);
>   serialize(buf, obj.pk());
>   serialize(buf, obj.ranges());
> }
> ```
> 
> The format of `pk` and `ranges` is determined not by the types specified in the schema but by effective return type of `pk()` and `ranges()` methods. So types specified in the IDL are effectively ignored.
> 
We can add static_assert(is_same<idl_type, result_of_t<obj.pk()>>::value, "wrong type")
into generated code.

--
			Gleb.

**Comment by amnonh** [comment]
The type that is define in the idl is used when deserializing object, (it is passed as a boost::type parameter).

I see a benefit of not imposing a type on the serializer, so in practice on specific cases two different types can be used.

I think this issue should be closed

**Comment by avikivity** [comment]
Suppose we have

    struct foo {
        int64_t x();
    };

but the real `x()` returns `long`.  That will work in testing but can break on other systems where long is 32-bit.

**Comment by amnonh** [comment]
it's a valid point, I'll add it.

**Comment by amnonh** [comment]
After adding static assert (accepted types are the type or const reference to it) some of the idl fails:
there are multiple cases where the declare type is view and the actuall type is bytes_view.

frozen_mutation.idl.hh
representation is both view and bytes_view
frozen_schema.idl.hh
representation is both view and bytes_view
token.idl.hh
_data is both view and bytes_view

**Comment by avikivity** [comment]
You mean both bytes and bytes_view.

    template <typename T, typename U>
    struct is_equivalent : std::false_type {
    };

    template <typename T>
    struct is_equivalent<T, T> : std::true_type {
    };

    template <>
    struct is_equivalent<bytes, bytes_view> : std::true_type {
    };

    template <>
    struct is_equivalent<bytes_view, bytes> : std::true_type {
    };

**Comment by gleb-cloudius** [comment]
On Tue, Feb 16, 2016 at 03:25:45AM -0800, Amnon Heiman wrote:
> After adding static assert (accepted types are the type or const reference to it) some of the idl fails:
> there are multiple cases where the declare type is view and the actuall type is bytes_view.
> 
Two solutions: 
1. Change accessors to return "const bytes" instead of bytes_view.
2. use is_convertible instead of is_same and cast while calling serializer.

Second likely will produce unneeded copy for bytes_view.

Other ideas?

--
			Gleb.

**Comment by gleb-cloudius** [comment]
On Tue, Feb 16, 2016 at 03:31:43AM -0800, Avi Kivity wrote:
> You mean both bytes and bytes_view.
> 
>     template <typename T, typename U>
>     struct is_equivalent : std::false_type {
>     };
> 
>     template <typename T>
>     struct is_equivalent<T, T> : std::true_type {
>     };
> 
Good idea! But why not:

template <typename T, typename U>
struct is_equivalent : is_same<T, U> {
}

>     template <>
>     struct is_equivalent<bytes, bytes_view> : std::true_type {
>     };
> 
>     template <>
>     struct is_equivalent<bytes_view, bytes> : std::true_type {
>     };
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/scylladb/scylla/issues/905#issuecomment-184643249

--
			Gleb.

**Comment by avikivity** [comment]
Could work too.

Even better

    template <typename T>
    struct normalize {
          using type = T;
    };

    template <>
    struct normalize<bytes_view> {
         using type = bytes;
    };

    template <typename T, typename U>
    struct is_equivalent : std::is_same<typename normalize<T>::type, typename normalize<U>::type> {
    };

**Comment by amnonh** [comment]
This can be close by commit 62e96de48a1063d2ee787328034036549152783c
