### ISSUE TITLE
scylla_setup - add optional RAID5 setup 

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#9076]
*Installation details*
Scylla version (or git commit hash): 4.6
OS (RHEL/CentOS/Ubuntu/AWS AMI): GCP

In some cases, like we recommended using RAID5 is a way to mitigate lost sector Issue.
It would be useful if this will be part of scylla_setup. 

https://github.com/scylladb/scylla-docs/issues/3563

**Comment by bhalevy** [comment]
Cc @xemul

**Comment by vladzcloudius** [comment]
I wonder if @xemul has approved this?

**Comment by xemul** [comment]
> I wonder if @xemul has approved this?

I didn't

> Haven't we seen that both RAID1 and RAID5(6) are very dangerous and significantly degrading performance?

Yes we have. There was a whole lot of issues with RAID1(EBS, RAID5(NVME0, ..., NVMEn)) setup coming ftom both -- RAID5 and RAID1. We had a recommendation how to tune up RAID1 for acceptable behavior, but for RAID5 the recommendation was -- use something else
