### ISSUE TITLE
Multi column restrictions ignored on indexed queries

### ISSUE THREAD

**Issue by cvybhu** [scylladb/scylla#9085]
Multi column restrictions seem to be ignored on queries that use an index:

```cql
DROP KEYSPACE IF EXISTS ks;
CREATE KEYSPACE IF NOT EXISTS ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};
CREATE TABLE IF NOT EXISTS ks.t (p int, c1 int, c2 int, c3 int, r1 int, r2 int, primary key (p, c1, c2, c3));
INSERT INTO ks.t (p, c1, c2, c3, r1, r2) VALUES (0, 0, 0, 0, 0, 0);
INSERT INTO ks.t (p, c1, c2, c3, r1, r2) VALUES (0, 1, 0, 0, 0, 0);
INSERT INTO ks.t (p, c1, c2, c3, r1, r2) VALUES (0, 2, 2, 0, 0, 0);
INSERT INTO ks.t (p, c1, c2, c3, r1, r2) VALUES (0, 0, 1, 0, 0, 1);
INSERT INTO ks.t (p, c1, c2, c3, r1, r2) VALUES (0, 1, 1, 0, 0, 1);
INSERT INTO ks.t (p, c1, c2, c3, r1, r2) VALUES (0, 3, 3, 0, 0, 1);

-- Uncomment for a global index:
CREATE INDEX IF NOT EXISTS ON ks.t(r2);

-- Uncomment for a local index:
-- CREATE INDEX IF NOT EXISTS ON ks.t((p), r2);
SELECT * FROM ks.t WHERE p = 0 and (c1, c2) < (1, 0) and r2 = 0;
```
Prints out:
```cql
 p | c1 | c2 | c3 | r1 | r2
---+----+----+----+----+----
 0 |  0 |  0 |  0 |  0 |  0
 0 |  1 |  0 |  0 |  0 |  0
 0 |  2 |  2 |  0 |  0 |  0
```
(Sometimes the index doesn't build in time and the query returns empty rows. In that case just perform the `SELECT` one more time)

This is wrong - `(1, 0)` and `(2, 2)` are not less than `(1, 0)`

### Versions
* `master` (aaf35b5ac273afd01a73c93c09f27179bdea17b5) - broken
* `Docker Scylla version 4.4.3-0.20210609.bfafb8456` - broken
* `Docker Scylla version 4.3.5-0.20210614.690a96ff5` - works, but requires `ALLOW FILTERING`

**Comment by dekimir** [comment]
For the record, this is different from #6200.  Index is used (despite #7699).

**Comment by dekimir** [comment]
> `Docker Scylla version 4.3.5-0.20210614.690a96ff5` - works, but requires `ALLOW FILTERING`

I think this is correct behaviour.  We agreed not to use indexing on multi-column restrictions.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
