### ISSUE TITLE
API uses incorrect plus<int> to sum up cf.active_memtable().partition_count()

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#9090]
`f.active_memtable().partition_count()` returns size_t but the API uses plus<int> to sum them up. This compiles but probably does not work as the code is expected to work. For example `plus<int>(2147483648LL, 1LL) = -2147483647` while the code would probably want 2147483649.

**Comment by avikivity** [comment]
Backported to 4.3, 4.4, 4.5.
