### ISSUE TITLE
Streaming - Performance - stream from each shard

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#91]
Instead of streaming from a single shard - lets stream from all shards in parallel

**Comment by slivne** [comment]
@asias this is old - so the bug may not be relevant - do we stream from a single shard ?

**Comment by asias** [comment]
Yes, on the sender side, we still stream from a single shard. However, on the receiver side, the mutation is dispatched to the shard it belongs and applied.

It is not trivial to support sending on multiple shard in parallel. I doubt we have time for it in GA.

After GA, Let's first see if this is really a bottleneck and optimize if so.

**Comment by slivne** [comment]
@asias Is it allways shard 0 that sends / receives - or is it random ?

**Comment by asias** [comment]
On Dec 27, 2015 6:20 PM, "slivne" <notifications@github.com> wrote:
>
> @asias Is it allways shard 0 that sends / receives - or is it random ?

Any shard can send or receive.

**Comment by asias** [comment]
Fixed by: d146045bc5f9e0de969184aa8954443750d076a3 31d439213c82040152d375c89e9786b9336e8375
