### ISSUE TITLE
Extend the startup time for scylla 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#910]
@avikivity currently 

scylla-server startup time is 15 minutes (TimeoutStartSec=900)
scylla-ami does not have one and I think it default to 90 seconds

What values do you want both to have

**Comment by slivne** [comment]
we need to extend scylla-server.service timeout as well

base on #833 - when bootstrapping a new node streaming will take time - depending on the amount of data so in this case the timeout must be significantly increased to allow for streaming to complete.

**Comment by syuu1228** [comment]
How long should it be? Maybe 30min?

**Comment by slivne** [comment]
@tzach please provide input if we should signal scylla is up prior to finishing streaming

**Comment by tzach** [comment]
Data streaming on boot can take long hours in case TB of data are streamed.
It is not reasonable to wait in the CLI for a few hours, so the service start should return before bootstrap is complete.
A good candidate can be after commit-log replay.
