### ISSUE TITLE
cdc/log.cc compare confusion

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#9103]
cdc's log.cc has a maybe_back_insert_iterator (that does what?):

```c++
template<typename Container, typename T>
class maybe_back_insert_iterator : public std::back_insert_iterator<Container> {
    const abstract_type& _type;
    collection_iterator<T> _s, _e;
public:
    using value_type = typename Container::value_type;
    maybe_back_insert_iterator(Container& c, const abstract_type& type, collection_iterator<T> s)
        : std::back_insert_iterator<Container>(c)
        , _type(type)
        , _s(s)
    {}
    maybe_back_insert_iterator& operator*() {
        return *this;
    }
    maybe_back_insert_iterator& operator=(const value_type& v) {
        if (!find(v)) {
            std::back_insert_iterator<Container>::operator=(v);
        }
        return *this;
    }
    maybe_back_insert_iterator& operator=(value_type&& v) {
        if (!find(v)) {
            std::back_insert_iterator<Container>::operator=(std::move(v));
        }
        return *this;
    }
private:
    bool find(const value_type& v) {
       // cheating - reducing search span, because we know we only append unique values (see below).
       while (_s != _e) {
           auto n = compare(*_s, v);
           if (n <= 0) {
               ++_s;
           }
           if (n == 0) {
               return true;
           }
           if (n > 0) {
               break;
           }
       }
       return false;
    }
    bool compare(const T&, const value_type& v);
};
```

find() calls compare (which returns a bool) and compares it as if it was an int from a tri-compare. This can't be right.

ref #1449

**Comment by elcallio** [comment]
Funky. The return types of `compare` are obviously wrong, since the whole idea is to get to _type.compare and similar, which are tri-comp. I am guessing this sort-of-works just due to register widths and bool being awfully similar to ints there.

**Comment by avikivity** [comment]
The compiler will happily cast an int to bool, but is it doing the right thing?

**Comment by avikivity** [comment]
(and it will convert -1 to true, not keep it as -1).

**Comment by elcallio** [comment]
Well, if you feel adventurous  you can check the generated code. I am guessing it just lets return reg be unmolested, otherwise this should not work at all (or our tests are too easy!)

**Comment by avikivity** [comment]
https://godbolt.org/z/hqhn45PzE

**Comment by elcallio** [comment]
https://godbolt.org/z/eb5PYTGce

**Comment by avikivity** [comment]
This proves that it doesn't work. The compiler eliminated nils, even though apa could have returned a negative value.

**Comment by elcallio** [comment]
For this cmp, yes. But it also treated eax as "pass-through", which means that we're back to "could have gone either way". Though I am of course likely to belive it at the very least generated broken code. Though, in the routine, checking == 0 is the most important part, and as long as it pass-throughs it might sort-of-work...

**Comment by avikivity** [comment]
Credit: #1449

**Comment by elcallio** [comment]
My people have a saying: woho.

**Comment by avikivity** [comment]
It's not pass through. It converts != to true and == to false. Meanwhile the caller does this:

```c++
           auto n = compare(*_s, v);
           if (n <= 0) {
               ++_s;
           }
           if (n == 0) {
               return true;
           }
```

Since n is bool, there's no difference between n <= 0 and n == 0, even though the code thinks there should be.

**Comment by elcallio** [comment]
Well, it will only touch the lower 8 bits (setne al), so if the reg was 0xffffffff, it should come out 0xffffff01, no?

**Comment by elcallio** [comment]
But the compiler should still treat the < 0 as impossible (since type == bool), so the only comparison done is really == 0. Which is ok-ish. It just means we are a lot slower for large collections.

**Comment by avikivity** [comment]
> Well, it will only touch the lower 8 bits (setne al), so if the reg was 0xffffffff, it should come out 0xffffff01, no?

The caller will only look at al since it was bool (and widen with movzx if needed).

**Comment by elcallio** [comment]
I would say the example I sent previously might indicate otherwise... While I agree it should, I think it might not, even when dest is auto var. See again https://godbolt.org/z/sEsqfPehx
The caller test is on unmodified eax (no mov or sx). He bypasses any notion of it ever being < 0, but still does 32-bit cmp. The effect is of course the same, but still worth noting.

**Comment by avikivity** [comment]
The test is on the result of apa(), which is an int. In gris() there is no setne instruction, it's all optimized away. If you remove -O3 you will see movzx.

**Comment by elcallio** [comment]
That is what the offending code in this issue does: calls an external (virtual) and just forwards its value, but with the wrong return type. The generated code should be rather similar.

**Comment by elcallio** [comment]
(the changes_things was inlined away, but the call is just that)

**Comment by avikivity** [comment]
Backported to 4.4, 4.5 (even though it ends up just performance). 4.6 has it.
