### ISSUE TITLE
storage_proxy::new_read_repair_decision() is inefficient on clang with libstdc++

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylla#9107]
`new_read_repair_decision()` generates a `double` in [0, 1), and compares it with read_repair_chance.
In libstdc++, this random number generation is done with `std::generate_canonical()`, which uses `std::log<long double>(long double)` in its implementation. gcc computes this `std::log` at compile time, but clang recomputes it every time. (It seems that clang in general doesn't simplify constant floating-point expressions, like std::log(), unless the standard says they are constexpr). 

On x86_64, this is not too bad. But on aarch64 this is terrible, because `long double` arithmetic is handled with software emulation there: https://godbolt.org/z/9bsGnM95G

For a aarch64 Scylla throughput benchmark on a small (in-cache) dataset, recomputing this constant adds up to a whopping 6.5% of the total work, so it has to be fixed.

We can work around this by precomputing the constants manually: https://godbolt.org/z/sEbvaGW69

**Comment by gleb-cloudius** [comment]
Or we can fix it by dropping support for probabilistic read repair all
together. The default value is 0 anyway, so we can also skip
calculations in that case.

--
			Gleb.

**Comment by nyh** [comment]
> Or we can fix it by dropping support for probabilistic read repair all together.

This is #3502. But as long as we don't do it, we can fix this bug.

> The default value is 0 anyway, so we can also skip calculations in that case.

Right, if the read repair chance is 0, we can return NONE immediately, and don't need to generate a random number at all!

**Comment by avikivity** [comment]
Performance only, and only on ARM, so not backporting.
