### ISSUE TITLE
Is there a way to log all queries including insert succeed or failed?

### ISSUE THREAD

**Issue by soyoeml** [scylladb/scylla#9112]
Hi,

Is there a way to log all queries including insert succeed or failed? I need to see the result of every insert. 

Thanks

**Comment by nyh** [comment]
This is a bug tracker, for reporting bugs or suggesting features (that you believe are missing). Please ask questions on the scylladb-users mailing list in googlegroups.com, or on the slack channel.

**Comment by soyoeml** [comment]
If somebody knows, please reply. That will be helpful.
