### ISSUE TITLE
Scylla crashes if parameter markers are supplied to an MVs SELECT statement

### ISSUE THREAD

**Issue by ManManson** [scylladb/scylla#9117]
The issue is with `create_view_statement::announce_migration()` incorrectly checking for empty bound variables list:

```c++
    if (!_prepare_ctx.empty()) {
        throw exceptions::invalid_request_exception(format("Cannot use query parameters in CREATE MATERIALIZED VIEW statements"));
    }
```

`cql3::prepare_context::empty()` returns a `lw_shared_ptr<prepare_context>` to a newly created empty instance instead of checking the current instance that it doesn't have any bound variables set.
Hence, the above check always evaluates to `false`.

*Installation details*
Scylla version (or git commit hash): https://github.com/scylladb/scylla/commit/3089558f8d15808aa03194df133a147be36b0a10

**Comment by nyh** [comment]
Already in branch 4.6 (18d9ad1d78609d8bd74d8e9adf4038408519a065).
I tried to backport to next-4.5 but it's not automatic, and some of the conflicts (e.g., in create_view_statement) I didnd't understand. @ManManson could you please do the backport to branch-4.5 and branch-4.4, unless you also think it's too complicated and we should reconsider? Thanks.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
