### ISSUE TITLE
reader is not closed in load_and_stream

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#9146]
We did not adjust the reader in load_and_stream in  [PATCH v4 00/94] Close flat mutation readers series. 
We have to close the reader before we destruct it.

**Comment by slivne** [comment]
@asias do we need to backport this to 4.5 ?

**Comment by asias** [comment]
> @asias do we need to backport this to 4.5 ?

No. 4.5 does not have flat mutation reader close series.
