### ISSUE TITLE
Nodetool: ConnectException: 'Connection refused'.

### ISSUE THREAD

**Issue by kirillsc** [scylladb/scylla#915]
Hi, 

A simple question, I am failing to connect to Scylla via nodetool, I am getting this error:

> $nodetool  status
> Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
> nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused'.

Or when I specify the IP address of the machine according to my configuration: 

> $nodetool -h 192.168.1.6  status
> Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8
> nodetool: Failed to connect to '192.168.1.6:7199' - ConnectException: 'Connection refused'.

When I check with netstat I see that Scylla does not listen on 7199 port and I am not seeing any errors in the syslog either:

> $sudo netstat -anp  | grep scyl
> tcp        0      0 192.168.1.6:10000       0.0.0.0:*               LISTEN      76791/scylla 
> tcp        0      0 192.168.1.6:9042        0.0.0.0:*               LISTEN      76791/scylla 
> tcp        0      0 192.168.1.6:7000        0.0.0.0:*               LISTEN      76791/scylla

It is probably something simple that I am missing.
Thanks!

**Comment by kirillsc** [comment]
I do have scylla-jmx installed.

**Comment by tzach** [comment]
@kirillsc can you test if scylla-jmx is running?
Take a look at https://github.com/scylladb/scylla/wiki/troubleshooting:-nodetool-does-not-work

**Comment by kirillsc** [comment]
Yes, it was down, sorry I didn't see that document before. 
Everything is working now, thanks!

**Comment by tzach** [comment]
@kirillsc can you please share the OS and how you installed Scylla?
We would like scylla-jmx service to start automatically to avoid this issue
See #504 and #726

**Comment by avikivity** [comment]
@tzach Need a scylla service which starts both scylla-server and scylla-jmx

Or else have scylla-server add an After dependency for scylla-jmx

**Comment by kirillsc** [comment]
I am using Ubuntu 14.04.3 LTS, with kernel 3.14.0.
That was the RPM installation from nightly builds.
I just verified that jmx does not starts automatically when you install Scylla that way.

Also I am starting scylla manually like this `sudo /usr/bin/scylla --options-file /etc/scylla/scylla.yaml` instead starting a service, perhaps that also makes a difference.
