### ISSUE TITLE
master build: ARM debug unittest fail: raft/raft_sys_table_storage_test

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla#9178]
Unittest on debug only, on ARM only fails:
raft/raft_sys_table_storage_test

Details: https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/build/700/artifact/output_test_aarch64_debug.txt/*view*/

This fails the build, so auto calling chain of packages can't run (I can run them manually).

**Comment by slivne** [comment]
@kostja ping

**Comment by hagitsegev** [comment]
https://jenkins.scylladb.com/job/scylla-master/job/build/710/ passed unittests.

**Comment by avikivity** [comment]
ARM-only, and raft-only, so not backporting.
