### ISSUE TITLE
Small difference between Scylla and Cassandra with CREATE INDEX IF NOT EXISTS

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#9182]
What should
```
CREATE INDEX xyz ON table(a)
CREATE INDEX IF NOT EXIST xyz ON table(b)
```
Do? Should the second command print an error, or not? There are arguments both ways:
1. The index with the name `xyz` exists, so the command should do nothing.
2. The index on `table(b)` does _not_ exist, so the command should try to create it and visibly fail.

Currently, Cassandra went with choice 1, Scylla went with choice 2.

If we can explain why choice 2 is better, we can declare this a Cassandra bug and not be compatible with it. But is choice 2 better? Should we perhaps switch to choice 1?

@eliransin @psarna any thoughts?

A cql-pytest for this:
```python
def test_create_index_if_not_exists2(cql, test_keyspace):
    with new_test_table(cql, test_keyspace, 'p int primary key, v1 int, v2 int') as table:
        index_name = unique_name()
        cql.execute(f"CREATE INDEX {index_name} ON {table}(v1)")
        cql.execute(f"CREATE INDEX IF NOT EXISTS {index_name} ON {table}(v2)")
```

**Comment by psarna** [comment]
(1.) makes more sense to me. IF NOT EXISTS is designed to make the query idempotent so that external automation tools can use it without having to deal with errors, so we should avoid failing as long as we leave the schema in a consistent state, which we do.

**Comment by nyh** [comment]
Yes, but "idempotent" only makes sense if you try the same request again. Here the user didn't - he wanted to create a different index of a different column. It's just that the chosen name was already in use. I honestly don't know which is better, but maybe the "safer" option if we can't decide is just to do the same thing as Cassandra did...

**Comment by avikivity** [comment]
Not a bug, not backporting.
