### ISSUE TITLE
Test for PasswordAuthenticator with CassandraAuthorizer

### ISSUE THREAD

**Issue by dmarti** [scylladb/scylla#919]
One user is planning to run with the following options set:

```
authenticator: PasswordAuthenticator
authorizer: CassandraAuthorizer 
```

and use ALTER USER to manage users/passwords. Need a test for this configuration.

**Comment by slivne** [comment]
We do not support CREATE/ALTER user at this point

**Comment by dmarti** [comment]
ALTER USER is part of https://github.com/scylladb/scylla/issues/1121 planned for Yellowfin (1.1).

**Comment by slivne** [comment]
@roydahan can we close this ?

**Comment by roydahan** [comment]
Yes.
