### ISSUE TITLE
This computer doesn't supported CPU scaling configuration.

### ISSUE THREAD

**Issue by tarzanek** [scylladb/scylla#9191]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [X] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): 4.0 (2020.1.8)
Cluster size: 3
OS (RHEL/CentOS/Ubuntu/AWS AMI): CEntos 7.7

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker):
Hardware: sockets= cores= hyperthreading= memory= 
Disks: (SSD/HDD, count) HDD

**Comment by tarzanek** [comment]
In some cases the check in https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_cpuscaling_setup#L49
is not ideal

e.g.:
```
[root@xxx ~]# uname -a
Linux xxx 3.10.0-1062.1.1.el7.x86_64 #1 SMP Fri Sep 13 22:55:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[root@xxx ~]# cat /etc/centos-release
CentOS Linux release 7.7.1908 (Core)

[root@xxx ~]# ls -la /sys/devices/system/cpu/cpufreq/policy0/scaling_governor
ls: cannot access /sys/devices/system/cpu/cpufreq/policy0/scaling_governor: No such file or directory

[root@xxx ~]# ls -la /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor
-rw-r--r-- 1 root root 4096 Jun  1 13:45 /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
-rw-r--r-- 1 root root 4096 Jun  1 13:45 /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
...
```

So above cpus could still be set to performance with:
```
for i in `ls /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor`; do echo "Tuning $i"; echo "performance" > $i; done
```

Can that check be enhanced?

**Comment by tarzanek** [comment]
resp. does this governor depend on some kernel version?
if yes, we should mandate newer kernel then

**Comment by tarzanek** [comment]
above cpus are
```
[root@xxx ~]# lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                40
On-line CPU(s) list:   0-39
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
Stepping:              4
CPU MHz:               2800.000
CPU max MHz:           2800.0000
CPU min MHz:           1200.0000
BogoMIPS:              5586.54
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              25600K
NUMA node0 CPU(s):     0-9,20-29
NUMA node1 CPU(s):     10-19,30-39
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm epb intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear spec_ctrl intel_stibp flush_l1d
```
servers themselves are HP ProLiant DL360p Gen8, BIOS P71 05/24/2019

**Comment by syuu1228** [comment]
@tarzanek Seems like /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor is available on the environment which has /sys/devices/system/cpu/cpufreq/policy0/scaling_governor, so I think we should switch to /sys/devices/system/cpu/cpufreq/policy0/scaling_governor. (PR sent)

**Comment by avikivity** [comment]
Backported to 4.3, 4.4, 4.5.
