### ISSUE TITLE
Index-based queries yield less data than they should if base queries are short-reads 

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#9198]
Indexed queries are using paging over the materialized view table. Results of the view read are then used to issue reads of the
base table. If base table reads are short reads, the page is returned to the user and paging state is adjusted accordingly so that when paging is resumed it will query the view starting from the row corresponding to the next row in the base which was not yet
returned. However, paging state's "remaining" count was not reset, so if the view read was exhausted the reading will stop even though the base table read was short.

As a result, the query will yield less data than it should.

Example:
```
cqlsh> select count(*) from ks.t where v = 0;

 count
-------
     2

(1 rows)
cqlsh> select  * from ks.ii_index ;

 v | idx_token            | pk | ck
---+----------------------+----+---------
 0 | -4069959284402364209 |  1 |       1
 0 | -3485513579396041028 |  0 | 1000000
 0 | -3248873570005575792 |  2 |       1

(3 rows)

```

\cc @bhalevy @psarna @wmitros @avelanarius

**Comment by psarna** [comment]
Is it specific to aggregate queries? From the description it sounds like even regular results could get truncated.

**Comment by tgrabiec** [comment]
On a closer look, it seems to me that map_reduce() does not reorder. So the problem is somewhere else. I did not observe regular reads to suffer from this.

**Comment by tgrabiec** [comment]
I think the problem is that `generate_view_paging_state_from_base_query_results()` doesn't reset `remaining` on short read. If the index read was exhausted, we'll stop fetching pages.

**Comment by psarna** [comment]
I don't follow - if the index read was exhausted, why should we keep fetching pages, and where from? I also tried to quickly reproduce the issue and failed - could you post more details, including this table's schema, what was the replication factor and how many nodes were there?

**Comment by tgrabiec** [comment]
Not all entries we fetched from the index may have been read form the base due to memory limits. In this case, even though we exhausted the index, we should go back to some of the entries we still haven't read from the base.

**Comment by tgrabiec** [comment]
I posted a patch on the mailing list

**Comment by tgrabiec** [comment]
Reproduces with non-aggregates too.

**Comment by bhalevy** [comment]
@tgrabiec ping. What happend with 3da302c?

**Comment by tgrabiec** [comment]
@bhalevy No idea what happened here, @avikivity? I think the patch can be committed.

**Comment by tgrabiec** [comment]
Well, no, 3da302c is an old version of the patch, it got dequed.

**Comment by tgrabiec** [comment]
The patch mentioned by Shlomi is the latest: "[scylladb-dev] [PATCH v4] cql: Fix missing data in indexed queries with base table short reads"

**Comment by nyh** [comment]
I'll review it now.

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
