### ISSUE TITLE
View is not filled with data when run 'refresh` with `--load_and_stream' parameter

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#9205]
*Installation details*
Scylla version (or git commit hash): 4.6.dev-0.20210808.31dcb0d1d with build-id 183c531ab85f2b1ee8010bfa7f29c19cda9098ec
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): dtest uses relocatable packages unstable/master:2021-08-08T16:56:08Z

When run `nodetool refresh` for the table with view (materialized view or secondary index), the view is updated automatically, as @psarna explained (and I verified with test) - https://github.com/scylladb/scylla-doc-issues/issues/784#issuecomment-899254360.

But when run `refresh` with parameter `--load_and_stream`, it doesn't happen. The view remains empty.

Scenario:
1. CREATE COLUMNFAMILY standard1 (key varchar PRIMARY KEY, c1 text, c2 text) WITH comment='test cf' 
2. Insert few rows and flush. Copy the sstables from all nodes and save them
3. Re-create the table.
4. CREATE INDEX c2_ind ON standard1 (c2)
5. Copy sstables to the `upload` folder
6. Run `refresh --load_and_stream`
7. Select base table rows - it's passed
8. Select view row - the view is empty

**Comment by asias** [comment]
Yes, in the code of load and stream, view will be not updated because the streaming reason is set to be streaming::stream_reason::rebuild. Only streaming with the reason streaming::stream_reason::repair will trigger view update.

It is pretty easy to make the load_and_stream to trigger view update but I am not sure it is efficient this way.

Consider RF = 3, sst1, sst2, sst3 from the older cluster. When sst1 is loaded, it streams to 3 replica nodes, if we genreate view updates, we will have 3 view updates for this replica (each of the peer nodes finds its peer and wrties the view update to peer). After loading sst2 and sst3, we will have 9 view updates in total for a single partition.

If we create the view after the load and stream process, we will only have 3 view update for a single partition.

**Comment by juliayakovlev** [comment]
> Yes, in the code of load and stream, view will be not updated because the streaming reason is set to be streaming::stream_reason::rebuild. Only streaming with the reason streaming::stream_reason::repair will trigger view update.
> 
> It is pretty easy to make the load_and_stream to trigger view update but I am not sure it is efficient this way.
> 
> Consider RF = 3, sst1, sst2, sst3 from the older cluster. When sst1 is loaded, it streams to 3 replica nodes, if we genreate view updates, we will have 3 view updates for this replica (each of the peer nodes finds its peer and wrties the view update to peer). After loading sst2 and sst3, we will have 9 view updates in total for a single partition.
> 
> If we create the view after the load and stream process, we will only have 3 view update for a single partition.

We need decision about that. @slivne Do we want to support view automatically update or not in case `load_and_stream`?

**Comment by avikivity** [comment]
I think we do. Otherwise we force the user to drop and recreate the view.

If the user wants efficiency, they can drop the view before load_and_stream and create it after it completes.

**Comment by asias** [comment]
> 
> 
> I think we do. Otherwise we force the user to drop and recreate the view.
> 
> If the user wants efficiency, they can drop the view before load_and_stream and create it after it completes.

Yes, this make sense.

**Comment by asias** [comment]
PR sent. I verfied view is created after this patch.

**Comment by juliayakovlev** [comment]
I added new tests for view testing after `load-and-stream`. Here the results

**Test 1**:
- Test data was created on the 2-nodes cluster, keyspace RF=2
- New cluster is 4-nodes, keyspace RF=3

Result: test **succeeded**: Row count in the table and index view as expected
```
Starting a cluster of 4 node(s)...
CREATE COLUMNFAMILY standard1 (key varchar PRIMARY KEY, c1 text, c2 text) WITH comment='test cf' AND compression = {}
Create index: CREATE INDEX c2_ind ON standard1 (c2)
Copy sstables of node1 to node4
Running load and stream on the node node4 for keyspace1.standard1'
Send load_and_stream api: http://127.0.52.4:10000/storage_service/sstables/keyspace1?cf=standard1&load_and_stream=true&primary_replica_only=False
Copy sstables of node2 to node1
Running load and stream on the node node1 for keyspace1.standard1'
Send load_and_stream api: http://127.0.52.1:10000/storage_service/sstables/keyspace1?cf=standard1&load_and_stream=true&primary_replica_only=False
Waiting for view keyspace1.c2_ind_index to finish building...
Checking rows on node1, keyspace1.standard1... - Passed
Checking rows on node1, keyspace1.c2_ind_index... - Passed
Checking rows on node2, keyspace1.standard1... - Passed
Checking rows on node2, keyspace1.c2_ind_index... - Passed
Checking rows on node3, keyspace1.standard1... - Passed
Checking rows on node3, keyspace1.c2_ind_index... - Passed
Checking rows on node4, keyspace1.standard1... - Passed
Checking rows on node4, keyspace1.c2_ind_index... - Passed
```

**Test 2**
- Test data was created on the 4-nodes, keyspace RF=3
- New cluster has 2-nodes cluster, keyspace RF=2

Result: test **failed**. Row count in the index view less then expected, in the table - as expected

```
Starting a cluster of 2 node(s)...
CREATE COLUMNFAMILY standard1 (key varchar PRIMARY KEY, c1 text, c2 text) WITH comment='test cf' AND compression = {}
Create index: CREATE INDEX c2_ind ON standard1 (c2)
Copy sstables of node1 to node1
Send load_and_stream api: http://127.0.48.1:10000/storage_service/sstables/keyspace1?cf=standard1&load_and_stream=true&primary_replica_only=False
Copy sstables of node2 to node1
Send load_and_stream api: http://127.0.48.1:10000/storage_service/sstables/keyspace1?cf=standard1&load_and_stream=true&primary_replica_only=False
Copy sstables of node3 to node2
Send load_and_stream api: http://127.0.48.2:10000/storage_service/sstables/keyspace1?cf=standard1&load_and_stream=true&primary_replica_only=False
Copy sstables of node4 to node2
Send load_and_stream api: http://127.0.48.2:10000/storage_service/sstables/keyspace1?cf=standard1&load_and_stream=true&primary_replica_only=False
Waiting for view keyspace1.c2_ind_index to finish building...
Checking rows on node1, keyspace1.standard1...
Passed
Checking rows on node1, keyspace1.c2_ind_index...
Count failed: 478 != 1000 : Expected 1000 rows in keyspace1.c2_ind_index on node1. Got 478
```

@psarna @asias @nyh @avikivity Can you advise, please

**Comment by asias** [comment]
> > > The base table is fully loaded and contains all the data. It is strange how the view table only contains part of the rows. This suggests the view update is triggered when the base table received.
> > > I modified the test to add 5m delay before the check to rule out the view is not completely finished. With the delay, the view table is partial too.
> > > @psarna @nyh Any ideas?
> > 
> > 
> > Sounds like we might have a bug in the post-"staging" view-building - could it be stopping in the middle for some reason (hanging) - or perhaps it starts too early when only part of the staging sstables are available, and when more come in we forget to do the view building again, or something?
> > Anyway, @asias @juliayakovlev if you have a reproducible scenario where this happens, please open a new issue about it explaining this scenario. Even better if you have an actual dtest to reproduce it - then I can start debugging the problem.
> 
> @nyh Here is the reproducer from Julia
> 
> ```
>     repo: https://github.com/juliayakovlev/scylla-dtest.git
>     branch: load_and_stream
>     Failed test:
> 
>     migration_test.TestLoadAndStream.load_and_stream_decrease_cluster_with_index_view_test
>     migration_test.TestLoadAndStream.load_and_stream_decrease_cluster_with_mv_test
> ```

Hello @nyh, could you please take a look?

**Comment by asias** [comment]
> > > > The base table is fully loaded and contains all the data. It is strange how the view table only contains part of the rows. This suggests the view update is triggered when the base table received.
> > > > I modified the test to add 5m delay before the check to rule out the view is not completely finished. With the delay, the view table is partial too.
> > > > @psarna @nyh Any ideas?
> > > 
> > > 
> > > Sounds like we might have a bug in the post-"staging" view-building - could it be stopping in the middle for some reason (hanging) - or perhaps it starts too early when only part of the staging sstables are available, and when more come in we forget to do the view building again, or something?
> > > Anyway, @asias @juliayakovlev if you have a reproducible scenario where this happens, please open a new issue about it explaining this scenario. Even better if you have an actual dtest to reproduce it - then I can start debugging the problem.
> > 
> > 
> > @nyh Here is the reproducer from Julia
> > ```
> >     repo: https://github.com/juliayakovlev/scylla-dtest.git
> >     branch: load_and_stream
> >     Failed test:
> > 
> >     migration_test.TestLoadAndStream.load_and_stream_decrease_cluster_with_index_view_test
> >     migration_test.TestLoadAndStream.load_and_stream_decrease_cluster_with_mv_test
> > ```
> 
> Hello @nyh, could you please take a look?

@nyh Ping. Any chances to take a look?

**Comment by juliayakovlev** [comment]
I found that this issue is reproduced when run the test using API. If run refresh with nodetool it's passed

**Comment by asias** [comment]
@juliayakovlev Do we still have the issue?

**Comment by juliayakovlev** [comment]
@asias 
All tests are passed on master
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1146/testReport/migration_test/TestLoadAndStream_with_3_0_md/

**Comment by asias** [comment]
Thanks. If that is the case, can we close this issue now?

**Comment by juliayakovlev** [comment]
> Thanks. If that is the case, can we close this issue now?

@asias I think, yes

**Comment by asias** [comment]
OK. Closing.

**Comment by avikivity** [comment]
Was something fixed? do we need to backport anything?

**Comment by asias** [comment]
The patch eaf4d2afb47d0c921931297581bfcd70b6e4a509 is in 4.6 branch. It is not in 4.5 branch. I think we need to backport to 4.5 branch.

**Comment by avikivity** [comment]
Backported to 4.5.
