### ISSUE TITLE
Prepared statements are not invalidated when UDT is altered

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#9210]
*Installation details*
HEAD: cb190481863cdd4d90e8aae1e1b0f976a4a7f9c3

*Description*
When `ALTER TYPE` is triggered we should invalidate corresponding prepared statements similarly to `ALTER KEYSPACE/TABLE`. 

Since we we are missing the corresponding code we don't do that and users get errors like the following:

```
User Defined Type value contained too many fields (expected 5, got 6)
```

after the 6th field was added to the type with 5 fields.

**Comment by vladzcloudius** [comment]
I see that with `cb19048` prepared statements of a table that uses the UDT that is being altered get properly invalidated.

**Comment by tgrabiec** [comment]
Some explanation on why this is not a bug: Altering a type also alters tables which depend on those types, and prepared statements get invalidated in response to those tables being altered.

**Comment by vladzcloudius** [comment]
> Some explanation on why this is not a bug: Altering a type also alters tables which depend on those types, and prepared statements get invalidated in response to those tables being altered.

You are describing how it is supposed to behave. But it has nothing to do with why this issue has been closed.
It expected behavior could have been broken (this is what I suspected) but luckily it wasn't.

**Comment by tgrabiec** [comment]
The description of the issue has this: "Since we we are missing the corresponding code". I wanted to point out that we are not missing code which is supposed to invalidate the statements.

**Comment by vladzcloudius** [comment]
I updated the opening message to make it less "stating" and more "suspecting". I believe that should make clearer now. 

I created this GH issue based on a user report and then I went and checked it myself. 

Note that if it would have turned out to be broken it would be me who would go and fix it since I wrote the code that invalidates prepared statements on KS/TABLE change.

**Comment by eliransin** [comment]
@vladzcloudius after going over the code I would like to add to what @tgrabiec already wrote:
The UDT alter statement also updates the tables that uses the UDT with a new column definition, this in turn causes
to those tables to be updated which in turns invalidates the prepared statements.
Is there something else that should happen and according to your suspicion doesn't happen?

**Comment by vladzcloudius** [comment]
> @vladzcloudius after going over the code I would like to add to what @tgrabiec already wrote: The UDT alter statement also updates the tables that uses the UDT with a new column definition, this in turn causes to those tables to be updated which in turns invalidates the prepared statements. Is there something else that should happen and according to your suspicion doesn't happen?

Guys, you both are not telling me anything I didn't already know before I closed this issue in the first place.

Thanks for trying to help but as an author of corresponding scylla code I'm well aware of how it is supposed to work (and it worked that way when I implemented prepared caches).
And as I have already explained to Tomek before, @eliransin, I suspected that something got broken. But verified it and it turned out to work as expected - all this before your first comment on this issue.

Again, thanks for all your comments but I knew everything I needed before Tomek's first comment on already closed issue.

**Comment by tgrabiec** [comment]
On Mon, Feb 21, 2022 at 9:25 PM Vladislav Zolotarov <
***@***.***> wrote:

> @vladzcloudius <https://github.com/vladzcloudius> after going over the
> code I would like to add to what @tgrabiec <https://github.com/tgrabiec>
> already wrote: The UDT alter statement also updates the tables that uses
> the UDT with a new column definition, this in turn causes to those tables
> to be updated which in turns invalidates the prepared statements. Is there
> something else that should happen and according to your suspicion doesn't
> happen?
>
> Guys, you both are not telling me anything I didn't already know before I
> closed this issue in the first place.
>
> Thanks for trying to help but as an author of corresponding scylla code
> I'm well aware of how it is supposed to work (and it worked that way when I
> implemented prepared caches).
> And as I have already explained to Tomek before, @eliransin
> <https://github.com/eliransin>, I suspected that something got broken.
> But verified it and it turned out to work as expected - all this before
> your first comment on this issue.
>
> Again, thanks for all your comments but I knew everything I needed before
> Tomek's first comment on already closed issue.
>

The comment was for other people who end up here by following references
from other issues (like I did). There was no explanation there why this
issue is not a problem, so I added one after figuring it out myself.
