### ISSUE TITLE
iotune fails on CentOS7 because fs.aio-max-nr is too small

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#922]
On CentOS7, I got following error when running iotune. It won't happen on Fedora:
```
$ ./build/release/iotune --evaluation-directory ~/tmp1Generating evaluation file...iotune: apps/iotune/iotune.cc:451: void test_file::generate(): Assertion `r >= 0' failed.
Aborted (core dumped)
```

Here's strace output. io_setup returns EAGAIN
```
io_setup(81920, 0x7fff13155df0)         = -1 EAGAIN (Resource temporarily unavailable)
write(2, "iotune: apps/iotune/iotune.cc:45"..., 90iotune: apps/iotune/iotune.cc:451: void test_file::generate(): Assertion `r >= 0' failed.
) = 90
```

So it's requesting 81920 events, but fs.aio-max-nr is less than that
```
$ cat /proc/sys/fs/aio-max-nr 
65536
```

On Fedora it's more bigger:
```
$ cat /proc/sys/fs/aio-max-nr 
1048576
```

The problem has gone when I increase the parameter:
```
[root@centos7-1 ~]# echo 1048576 > /proc/sys/fs/aio-max-nr
```

We should increase it on our .rpm, using /etc/sysctl.d/99-scylla.conf just like what we did on coredump handler settings.

**Comment by avikivity** [comment]
It's better not to spew zillions of parallel I/O requests like that and instead have a limited concurrency.

**Comment by slivne** [comment]
@avikivity can we close this ?
