### ISSUE TITLE
perftune.py fails on bond NICs

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#9225]
perftune fails with

`ERROR: 'method' object is not iterable. Your system can't be tuned until the issue is fixed.`

**Comment by avikivity** [comment]
Fixed by 9d018b5f40c0090be4ace6d14fbf887ec9753c54 (scylladb/seastar#888)

**Comment by avikivity** [comment]
Backported to 4.4, 4.5. @vladzcloudius I think 4.3 is not vulnerable, please verify.

**Comment by vladzcloudius** [comment]
> Backported to 4.4, 4.5. @vladzcloudius I think 4.3 is not vulnerable, please verify.

You are right. 4.3 doesn't have the patch that introduced the regression.
