### ISSUE TITLE
dist/redhat/build_rpm.sh fails on newly created CentOS7 instance

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#923]
It fails because idl-compiler.py requires /usr/bin/python3, but epel python3 package provides /usr/bin/python3.4.
```
+ ninja-build -j2
[8/240] IDL compiler build/release/gen/idl/streaming.dist.hh
FAILED: ./idl-compiler.py --ns ser -f idl/streaming.idl.hh -o build/release/gen/idl/streaming.dist.hh
/bin/sh: ./idl-compiler.py: /usr/bin/python3: bad interpreter: No such file or directory
```

On dist/redhat/centos_dep/build_dependency.sh, we are symlinking /usr/bin/python3.4 to /usr/bin/python3, but now it doesn't executed by default because we uses prebuilt binary from yum repository.

**Comment by avikivity** [comment]
I think we can add ./configure.py --with-python3= to fix this
