### ISSUE TITLE
Introduce experimental flag for raft features

### ISSUE THREAD

**Issue by ManManson** [scylladb/scylla#9239]
There is no experimental flag for Raft-related features yet. We would definitely need it to hide any raft work until it matures enough.

Let's introduce a `raft` database configuration switch for that.

The option should be enabled only when explicitly asked to do so (i.e. don't enable when `--experimental=true`, but only when a distinct `--experimental-features=raft` option is supplied.

There would also be a bunch of other more specialized flags in the future. This option will act as a main switch to control all other flags.

**Comment by slivne** [comment]
@ManManson can we close this

**Comment by ManManson** [comment]
Yes, will close now.
