### ISSUE TITLE
[tools] scylla-sstable

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#9241]
When investigating problems with sstables we often need to check the content of the sstables and extract information from it and then aggregate or process it in various ways. The only tool we have currently is `sstabledump` which have various problems. First off it is awkward and painful to use. It is based on the C* java codebase so the average Scylla C++ developer is not familiar with its code and how to use it. Furthermore, it just dumps everything into the standard output either in JSON or in its own format. If we want to check sstables on customer sites we have to provide them with shell scripting that tries to extract the required information from the output. And shell scripts are notoriously fragile when doing data aggregation and processing.

As an alternative I'd like to propose `scylla-sstable-crawler`, which would be built on scylla's C++ codebase to crawl over the sstable content, feeding it to a user-provided Lua script, which can extract the required information and aggregate, process or just print it as needed. The script could write a file output if it wants to. Note that this allows for a trivial implementation of `sstabledump` functionality as a simple lua script as well.
The tool would provide Lua bindings for all the building blocks of a mutation-fragment-stream: From `mutation_fragment` down to the cell level. We could have some standard scripts (like `sstabledump`) shipped with the tool, while still having the opportunity to provide custom scripts to the user/customer whose sstables we want to run some diagnosis on.

**Comment by raphaelsc** [comment]
+1

**Comment by haaawk** [comment]
Why Lua? Isn't it even less familiar to everyone than Java?

**Comment by denesb** [comment]
cc @bhalevy

**Comment by denesb** [comment]
> Why Lua? Isn't it even less familiar to everyone than Java?

Two reasons: it is embeddable and it is already embedded into scylla. So I can easily add Lua bindings to the mutation fragment objects and then the tool can load and execute embedded Lua scripts.

**Comment by eliransin** [comment]
In the future we might be able to do assembly too , then IIUC it will be useful for any (or almost any) LLVM based language :slightly_smiling_face: 
/cc @psarna

**Comment by avikivity** [comment]
With the ka-style consumer we could even crawl unprocessed strings, and inspect things below the fragment level. But for m+ formats that's not possible, they're to tightly coupled with mutation fragments.

**Comment by denesb** [comment]
TODO
- [ ] JSON output for dump.
- [ ] A simple way of generating schema.cql for any schema, other than copying it from snapshots, or copying from cqlsh. None of these generate a complete output.
- [ ] Relax sstable path checks, so sstables can be loaded from any path.
- [ ] Add scripting support (Lua), allowing custom operations to be written in a scripting language.

**Comment by bhalevy** [comment]
I'd like to add also reverse JSON - i.e. writing a sstable from JSON input.

**Comment by denesb** [comment]
I am closing this unclosable umbrella issue and opening individual issues for features discussed here:
* https://github.com/scylladb/scylla/issues/9678
* https://github.com/scylladb/scylla/issues/9679
* https://github.com/scylladb/scylla/issues/9680
* https://github.com/scylladb/scylla/issues/9681
