### ISSUE TITLE
Split range_tombstone_entry from range_tombstone

### ISSUE THREAD

**Issue by xemul** [scylladb/scylla#9243]
The `range_tombstone` contains both -- the range tombstone data (bounds and the tombstone itself) and the linkage to the `range_tombstone_tree`'s data structure used to keep them (a `boost::intrusive::set`). This is quite bug-prone because the move-constructor of the `range_tombstone` also moves the linkage between the entries. So every "mover" must be very careful not to move a range tombstone that sits in some list without properly maintaining the consequences (e.g. like #9207).

There's a `without_link` option to move-construct a range tombstone but it's still not nice. The correct fix is to remove the list linkage from `range_tombstone` and intruduce a new `range_tombstone_entry`, probably private to `range_tombstone_list`, that will tie together the range tombstone itself and the linkage to the proper tree.

**Comment by avikivity** [comment]
Not a bug, not backporting.
