### ISSUE TITLE
[AMI 0.18] Longevity test failure: (DrainerMonkey) Node runs out of space

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#925]
We hit a situation where a node runs out of space during the 24 hour Nemesis test run, while other nemesis ran until the end with no disk space issues.

The test logs show a typical c-s execution, that goes fine until at about 11 hours of execution, where the Drainer Monkey executes hits a problem:

The error:

    01:48:43 INFO | [54.183.192.210] Running '/bin/ssh -a -x  -o ControlPath=/var/tmp/ssh-masteruwvtQI/socket -o StrictHostKeyChecking=no -o UserKnownHostsFile=/var/tmp/tmpu4knUv -o Batc
    hMode=yes -o ConnectTimeout=300 -o ServerAliveInterval=300 -l centos -p 22 -i /var/tmp/drainer_monkey-longevity-test-e6f50ce1.pem 54.183.192.210 "nodetool -h localhost drain"'
    01:48:44 DEBUG| [54.183.192.210] [stderr] cp: error writing ‘/tmp/tmp.JzJ4KotfPy/ami.conf’: No space left on device
    01:48:44 DEBUG| [54.183.192.210] [stderr] cp: failed to extend ‘/tmp/tmp.JzJ4KotfPy/ami.conf’: No space left on device
    01:48:44 DEBUG| [54.183.192.210] [stderr] cp: error writing ‘/tmp/tmp.JzJ4KotfPy/cassandra/cassandra-env.sh’: No space left on device
    01:48:44 DEBUG| [54.183.192.210] [stderr] cp: failed to extend ‘/tmp/tmp.JzJ4KotfPy/cassandra/cassandra-env.sh’: No space left on device
    01:48:44 DEBUG| [54.183.192.210] [stderr] cp: error writing ‘/tmp/tmp.JzJ4KotfPy/cassandra/logback.xml’: No space left on device
    01:48:44 DEBUG| [54.183.192.210] [stderr] cp: failed to extend ‘/tmp/tmp.JzJ4KotfPy/cassandra/logback.xml’: No space left on device
    01:48:44 DEBUG| [54.183.192.210] [stdout] Feb 20 01:48:44 ip-172-31-19-194.us-west-1.compute.internal scylla[1074]: ERROR [shard 1] database - failed to write sstable: std::system_er
    ror (error system:28, No space left on device)
    01:48:44 DEBUG| [54.183.192.210] [stderr] cp: error writing ‘/tmp/tmp.JzJ4KotfPy/cassandra-rackdc.properties’: No space left on device
    01:48:44 DEBUG| [54.183.192.210] [stderr] cp: failed to extend ‘/tmp/tmp.JzJ4KotfPy/cassandra-rackdc.properties’: No space left on device
    01:48:44 DEBUG| [54.183.192.210] [stderr] cp: error writing ‘/tmp/tmp.JzJ4KotfPy/scylla.yaml’: No space left on device
    01:48:44 DEBUG| [54.183.192.210] [stderr] cp: failed to extend ‘/tmp/tmp.JzJ4KotfPy/scylla.yaml’: No space left on device
    01:48:44 DEBUG| [54.193.17.24] [stdout] Feb 20 01:48:44 ip-172-31-19-195.us-west-1.compute.internal scylla[806]: ERROR [shard 1] database - failed to write sstable: std::system_error
     (error system:28, No space left on device)
    01:48:44 DEBUG| [54.193.17.24] [stdout] Feb 20 01:48:44 ip-172-31-19-195.us-west-1.compute.internal scylla[806]: ERROR [shard 0] database - failed to write sstable: std::system_error
     (error system:28, No space left on device)
    01:48:44 DEBUG| [54.193.17.24] [stdout] Feb 20 01:48:44 ip-172-31-19-195.us-west-1.compute.internal scylla[806]: ERROR [shard 0] database - failed to write sstable: std::system_error
     (error system:28, No space left on device)
    01:48:44 DEBUG| [54.193.17.24] [stdout] Feb 20 01:48:44 ip-172-31-19-195.us-west-1.compute.internal scylla[806]: ERROR [shard 0] database - failed to write sstable: std::system_error
     (error system:28, No space left on device)
    01:48:44 DEBUG| [54.183.192.210] [stdout] Feb 20 01:48:44 ip-172-31-19-194.us-west-1.compute.internal scylla[1074]: ERROR [shard 0] database - failed to write sstable: std::system_er
    ror (error system:28, No space left on device)
    01:48:44 DEBUG| [54.183.192.210] [stderr] Traceback (most recent call last):
    01:48:44 DEBUG| [54.183.192.210] [stderr]   File "/usr/bin/filter_cassandra_attributes.py", line 14, in <module>
    01:48:44 DEBUG| [54.183.192.210] [stderr]     main()
    01:48:44 DEBUG| [54.183.192.210] [stderr]   File "/usr/bin/filter_cassandra_attributes.py", line 10, in main
    01:48:44 DEBUG| [54.183.192.210] [stderr]     attributes.update(load(open(sys.argv[i], 'r')))
    01:48:44 DEBUG| [54.183.192.210] [stderr] TypeError: 'NoneType' object is not iterable
    01:48:44 DEBUG| [54.183.192.210] [stderr] cp: error writing ‘/tmp/tmp.JzJ4KotfPy/logback.xml’: No space left on device
    01:48:44 DEBUG| [54.183.192.210] [stderr] cp: failed to extend ‘/tmp/tmp.JzJ4KotfPy/logback.xml’: No space left on device
    01:48:44 DEBUG| [54.183.192.210] [stderr] cp: cannot create regular file ‘/tmp/tmp.JzJ4KotfPy/cassandra-env.sh’: No space left on device
    01:48:44 DEBUG| [54.193.17.24] [stdout] Feb 20 01:48:44 ip-172-31-19-195.us-west-1.compute.internal scylla[806]: ERROR [shard 1] database - failed to write sstable: std::system_error
     (error system:28, No space left on device)
    01:48:45 DEBUG| [54.183.192.210] [stderr] OpenJDK 64-Bit Server VM warning: Insufficient space for shared memory file:
    01:48:45 DEBUG| [54.183.192.210] [stderr]    9056
    01:48:45 DEBUG| [54.183.192.210] [stderr] Try using the -Djava.io.tmpdir= option to select an alternate temp location.
    01:48:45 DEBUG| [54.183.192.210] [stderr] 
    01:48:45 DEBUG| [54.193.17.24] [stdout] Feb 20 01:48:45 ip-172-31-19-195.us-west-1.compute.internal scylla[806]: ERROR [shard 1] database - failed to write sstable: std::system_error
     (error system:28, No space left on device)
    01:48:45 DEBUG| [54.193.17.24] [stdout] Feb 20 01:48:45 ip-172-31-19-195.us-west-1.compute.internal scylla[806]: ERROR [shard 0] database - failed to write sstable: std::system_error
     (error system:28, No space left on device)
    01:48:45 DEBUG| [54.183.192.210] [stdout] nodetool: Found unexpected parameters: [localhost, drain]
    01:48:45 DEBUG| [54.183.192.210] [stdout] See 'nodetool help' or 'nodetool help <command>'.

The Node size is `c3 large`. Looking at the logs, we see that space problems happen earlier, around 23:10:

    23:10:55 DEBUG| [54.183.192.210] [stdout] Feb 19 23:10:55 ip-172-31-19-194.us-west-1.compute.internal scylla[1074]: ERROR [shard 0] compaction_manager - compaction failed: read exception: seastar::broken_pipe_exception (Broken pipe), write_exception: std::system_error (error system:28, No space left on device)

Digging a little further, we discover this node was drained and then restarted, about 15 minutes earlier:

    22:55:39 DEBUG| Node drainer_monkey-scylla-db-node-cdba6fe9-2 [54.193.36.30 | 172.31.19.194] (seed: None): Got new public IP 54.183.192.210

That's suspicious, given that other nemesis ran for 24 hours with no space issues on nodes. I looked at the timeline, looking for messages pointing out to a glaring error, but couldn't find anything. Still, the fact remains that space wasn't an issue with other nodes, suggesting that the drain/restart procedure is causing the run out of space issue.

What the test does
------------------

The workflow of a longevity test is:

1. Create a scylla cluster (referred as DB cluster from now on) with number of nodes (default size is 6) and node size (default is t2.micro, the bug report is using c3.large) defined by the user on a config file
2. Create a number of loader nodes, that will stress the DB cluster, typically by running cassandra stress on it
3. The cluster object hosts a Nemesis (that terminology was borrowed from Jepsen), a thread that randomly picks a non-seed node and disrupt it in some way.
4. Nemesis will sleep for a specified time interval, then execute the disruption function, then sleep again, rinse and repeat.
5. Cassandra-stress starts. The default command line looks like:

    `cassandra-stress write cl=QUORUM duration=1440m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=4 -node 172.31.27.192`

6. At all times, we have at least initial cluster size - 1 (6 -1 = 5) nodes active, which should be enough to keep c-s going. The disruption functions operate on a single node, and operations that actually remove a node permanently from the cluster will add a new node to compensate the one that was removed.
7. Given all that, we do expect that c-s survives until the specified time period (the report is using 24 hours). If it doesn't, chances are that we have a bug.

What the nemesis does
---------------------

1. Execute the following command in the target node:

    `nodetool -h localhost drain`

2. Stop the AWS instance of the target node.
3. Start the AWS instance of the target node.
4. Wait until the DB services are up (port 9042 occuppied)

**Comment by dorlaor** [comment]
What was the size of the /data directory and how big is the local disk of
this small image (.xlarge is small too)?

**Comment by avikivity** [comment]
/tmp is likely to be tmpfs, so it looks like the test framework exhausted RAM/swap.

**Comment by lmr** [comment]
@avikivity, I thought about the tmpfs comment you made. I can't think of anything special that the test suite does other than keeping one ssh connection open for the log thread/executing commands in the node.

I'm thinking about disabling tmp on tmpfs (`systemctl mask tmp.mount`), but maybe that's a bad idea, since it would mask issues that users could potentially have.

**Comment by avikivity** [comment]
@lmr how about logging into such a machine and running `df`?

At least that `cp` process was writing to `/tmp`, maybe it isn't cleaned up afterwards?

**Comment by lmr** [comment]
@slivne I have repeated the test, with a smaller time interval between nemesis executions (5 minutes), using the latest released AMI `ami-be84f5de`, and I couldn't reproduce this specific issue. In this new run, c-s dies after about an hour of execution.

    07:27:58 remote           L0773 DEBUG| Remote [centos@54.193.31.255]: Running 'cassandra-stress write cl=QUORUM duration=1440m -schema 'replication(factor=3)' -port jmx=6868 -mode cq

    ...

    08:32:36 remote           L0182 DEBUG| [54.193.31.255] [stdout] java.io.IOException: Operation x10 on key(s) [4d4d32344e31364b3031]: Error executing: (UnavailableException): Not enou
    gh replicas available for query at consistency QUORUM (2 required but only 1 alive)

**Comment by lmr** [comment]
This problem doesn't reproduce anymore as of the latest 1.0-rc1 AMI (ami-c25e51a8). I'm closing this issue.
