### ISSUE TITLE
Scrub compaction filters out sstables that are being compacted

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9256]
Currently, scrub compaction calls `get_candidates` both in validate mode:
https://github.com/scylladb/scylla/blob/7f44736939eca788100287e7ff2150ce55e64483/compaction/compaction_manager.cc#L758
and other modes:
https://github.com/scylladb/scylla/blob/7f44736939eca788100287e7ff2150ce55e64483/compaction/compaction_manager.cc#L891

get_candidate then filters out sstables that are being compacted:
https://github.com/scylladb/scylla/blob/7f44736939eca788100287e7ff2150ce55e64483/compaction/compaction_manager.cc#L185-L194

Since we want scrub, in all modes, to examine all sstables in the table for corruption, as @raphaelsc said:
> we should likely stop all ongoing compactions and then proceed with
> scrub (segregate or skip), to prevent ongoing compactions from
> propagating the corruption once scrub is finished, as one expects no
> corruption left in the table thereafter.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
