### ISSUE TITLE
[AMI 0.18] Longevity test failure: Cassandra-stress doesn't survive stop/start monkey

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#926]
Running the longevity test for 24 hour with our stop/start monkey revealed failures in cassandra-stress to survive until the end. The stresser stays up for about 6.5 hours:

    22:47:51 remote           L0773 DEBUG| Remote [centos@54.183.232.21]: Running 'cassandra-stress write cl=QUORUM duration=1440m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=4 -node 172.31.27.192'
    ...
    05:32:10 remote           L0182 DEBUG| [54.183.232.21] [stdout] java.io.IOException: Operation x10 on key(s) [50364f364d34314f4e30]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)

Other than an error message already reported on bug #900 (samples follow):

    22:31:29 remote           L0182 DEBUG| [54.183.212.72] [stdout] Feb 19 22:31:29 ip-172-31-27-193.us-west-1.compute.internal scylla[894]: WARN  [shard 0] failure_detector - Not marking nodes down due to local pause of 128281 > 5000 (milliseconds)
    22:31:35 remote           L0182 DEBUG| [52.53.231.216] [stdout] Feb 19 22:31:35 ip-172-31-27-194.us-west-1.compute.internal scylla[924]: WARN  [shard 0] failure_detector - Not marking nodes down due to local pause of 128325 > 5000 (milliseconds)
    22:31:40 remote           L0182 DEBUG| [54.193.93.33] [stdout] Feb 19 22:31:41 ip-172-31-27-196.us-west-1.compute.internal scylla[903]: WARN  [shard 0] failure_detector - Not marking nodes down due to local pause of 128232 > 5000 (milliseconds)
    22:31:47 remote           L0182 DEBUG| [54.183.181.107] [stdout] Feb 19 22:31:47 ip-172-31-27-197.us-west-1.compute.internal scylla[1180]: WARN  [shard 0] failure_detector - Not marking nodes down due to local pause of 128291 > 5000 (milliseconds)

And the one already reported on bug #902 (samples follow):

    22:31:35 remote           L0182 DEBUG| [52.53.231.216] [stdout] Feb 19 22:31:36 ip-172-31-27-194.us-west-1.compute.internal scylla-jmx[1971]: Exception in thread "Dropped messages" java.lang.NullPointerException

There were no other suspicious error messages to report.

What the test does
------------------

The workflow of a longevity test is:

1. Create a scylla cluster (referred as DB cluster from now on) with number of nodes (default size is 6) and node size (default is t2.micro, the bug report is using c3.large) defined by the user on a config file
2. Create a number of loader nodes, that will stress the DB cluster, typically by running cassandra stress on it
3. The cluster object hosts a Nemesis (that terminology was borrowed from Jepsen), a thread that randomly picks a non-seed node and disrupt it in some way.
4. Nemesis will sleep for a specified time interval, then execute the disruption function, then sleep again, rinse and repeat.
5. Cassandra-stress starts. The default command line looks like:

    `cassandra-stress write cl=QUORUM duration=1440m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=4 -node 172.31.27.192`

6. At all times, we have at least initial cluster size - 1 (6 -1 = 5) nodes active, which should be enough to keep c-s going. The disruption functions operate on a single node, and operations that actually remove a node permanently from the cluster will add a new node to compensate the one that was removed.
7. Given all that, we do expect that c-s survives until the specified time period (the report is using 24 hours). If it doesn't, chances are that we have a bug.

What the nemesis does
---------------------

1. Stop the AWS instance of the target node.
2. Start the AWS instance of the target node.
3. Wait until the DB services are up (port 9042 occuppied)

**Comment by slivne** [comment]
We may need todo in such cases is todo nodetool status on all the nodes to see what the membership of the nodes in the cluster 

Another option dor raised is to add a mega debug function thats dumps the server status - and that we will be able to activate it if we need to debug the status

**Comment by lmr** [comment]
This test was repeated with a shorter nemesis interval, and the result was the same, only the stresser survived for less time (now ~2.5 hours):

    07:28:21 remote           L0773 DEBUG| Remote [centos@54.67.8.166]: Running 'cassandra-stress write cl=QUORUM duration=1440m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3
     native -rate threads=4 -node 172.31.25.176'

    ...

    09:40:25 remote           L0182 DEBUG| [54.67.8.166] [stdout] java.io.IOException: Operation x10 on key(s) [32363238324b314b3130]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)

**Comment by slivne** [comment]
Do we support already the option to leave the cluster up and allow access once that happens

**Comment by lmr** [comment]
@slivne no, will resume work on this...

**Comment by slivne** [comment]
@lmr - did we pass this test opn c3.large - with 1.0 AMI - if so please close

**Comment by lmr** [comment]
@slivne yes, it does pass. I'm closing this issue.
