### ISSUE TITLE
"ninja dev" doesn't just build dev mode as expected

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#9260]
One would expect that `ninja dev` only build dev-mode outputs.
However, it doesn't - it appears to build release-mode and debug-mode Seastar and Scylla source files.

Please note that I always run "configure.py" without a mode parameter, so all build modes exist in `ninja.build`. That shouldn't be a problem, and isn't a problem for `ninja build/dev/scylla` which I normally use and builds only dev mode - but apparently `ninja dev` doesn't do the right thing.

**Comment by avikivity** [comment]
Maybe it's building iotune?

I fixed similar problem in 4d48e1e9e1d532bc0e170b6c6ceeb7fdd2310fe6, apparently not enough.

**Comment by nyh** [comment]
Going down the rabbit hole:

1. "ninja dev" is an alias for "ninja build-dev" and "ninja dist-dev".
    * The "build-dev" target is correct - it only builds only dev-mode files.
    * It is "ninja dist-dev" which is broken and builds stuff from other modes.

2. "ninja dist-dev" builds a bunch of targets, it is "ninja dist-server-dev" which builds other modes.

3. dist-server-dev as usual builds a bunch of targets, only one of them builds other modes: "ninja dist-server-compat".

`dist-server-compat` is the bug... It asks to build a tar in three modes. Which is silly - dist-server-dev should only build dev modes, not all modes.

**Comment by nyh** [comment]
This bug was introduced in commit edd54a946350689a5032395cbdd799d21481ec39 by @syuu1228 - all build mode depends on the same target "dist-server-compat" instread of having different versions of this target for each build mode.

I can't say I understand anything about what this "dist-server-compat" target was trying to solve, but I'll try to see if I can fix it without understanding :-)

**Comment by nyh** [comment]
>     2. "ninja dist-dev" builds a bunch of targets, it is "ninja dist-server-dev" which builds other modes.

Correction - although "ninja dist-server-dev" is buggy (see my previous comment on what was wrong, and I already have a patch), "ninja dist-unified-dev" is **also** buggy and builds all modes. Again the problem is a mode-less "dist-unified-compat". I'll fix it too.
