### ISSUE TITLE
"ninja dev" fails on Fedora 34

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#9261]
When I run "ninja dev" (to build everything in dev mode, supposedly), it ends with
```
ninja: build stopped: subcommand failed.
```
which isn't clear what caused it. The log shows two different errors:
```
 dpkg-source -b .
dpkg-source: warning: no source format specified in debian/source/format, see 
dpkg-source(1)
dpkg-source: warning: source directory 'scylla-python3-package' is not <source
package>-<upstreamversion> 'scylla-python3-4.6.dev-0.20210829.4009d8b06'
dpkg-source: warning: .orig directory name scylla-python3-package.orig is not 
<package>-<upstreamversion> (wanted scylla-python3-4.6.dev-0.20210829.4009d8b0
6.orig)
dpkg-source: error: orig directory 'scylla-python3-package.orig' already exists, not overwriting, giving up; use -sA, -sK or -sP to override
dpkg-source: info: using source format '1.0'
dpkg-source: info: building scylla-python3 using existing scylla-python3_4.6.dev-0.20210829.4009d8b06.orig.tar.gz
dpkg-buildpackage: error: dpkg-source -b . subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -rfakeroot -us -uc -ui failed
```
and
```
/home/nyh/scylla/tools/java/build.xml:959: The following error occurred while executing this line:
/home/nyh/scylla/tools/java/build.xml:930: Error running ${env.JAVA8_HOME}/bin/javac compiler
```

Yes, I know the usual mantra is "use dbuild". I shouldn't have to for master :-( If our build needs specifically Java 8 and can't run with Java 11 (which is the default on Fedora 34), it should at least make a minimal effort to find it on common distributions - and not rely on environment variables that the developers are unlikely to have set. And I don't even understand the first error :-(

**Comment by avikivity** [comment]
I routinely build on Fedora 34 (and dbuild is just Fedora 34 now).

I think the problem is that the the build directory can become poisoned by a previous build. The command (warning: dangeous)

     git clean -fdx && git submodule foreach --recursive git clean -fdx

will remove the poison (and also any good files you may have lying around) and allow the build to succeed.

I suspect it's caused by something like `cp -r a/b c`. With a clean tree, it causes the creation of `c/b`. With a dirty tree, it can cause the creation of `c/b/b` instead.

**Comment by nyh** [comment]
I had an empty directory `tools/python3/build/debian/scylla-python3-package.orig`. 
Removing it seems to have fixed the problem.
I could close this issue as having a workaround (and I already sent a patch to fix the Java 8 issue), but I still think this issue is valid - this script is buggy if it left such a directory behind (I didn't create it myself, but it's possible I ran a failed build or even interrupted one in the past...) or if it can't handle the case where it exists.

**Comment by avikivity** [comment]
It is valid. I encounter it too from time to time.

**Comment by nyh** [comment]
I'll close this issue and open a new one instead (which isn't specific to Fedora 34).
