### ISSUE TITLE
dist/docker/debian/README.md is wrong

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#9263]
Almost all steps in the instructions in `dist/docker/debian/README.md` are wrong or misleading:

1. Build your own Scylla in whatever build mode you prefer, e.g., dev.
2. Run ninja dist-deb
3. Run /dist/docker/debian/build_docker.sh
4. Finally, run docker build -t <image-name> .

Step 2 is wrong because it builds all modes again. Should be "dist-dev" (which unfortunately not only builds the deb target, but at least doesn't build all modes! at least not after I sent a patch to fix a bug in that area).

Step 3 is missing "--mode dev" (so uses release mode by default).

Step 4 assumes there is a Dockerfile in the Scylla main source directory, but there isn't. Step 4 probably needs to be replaced by entirely different command, but I can't yet figure out by what and need help.

**Comment by nyh** [comment]
CC @yaronkaikov @syuu1228

**Comment by yaronkaikov** [comment]
@nyh Thanks for openning the issue, i will send a patch soon

**Comment by nyh** [comment]
@yaronkaikov please note that I assigned this to myself because I almost have a patch for it myself - I'm just missing a solution for step 4. Can you please try it yourself and see what is the correct step 4?

**Comment by nyh** [comment]
As @avikivity noted on the mailing list, step 4 became outdated with commit e96ff3d82d48c41f428e6fb2f622454da0c36cdf. As that commit suggests that the output of step 3 is just a file, which "can be uploaded into a repository or made available locally with skopeo.". Now I just need to figure out what this sentence means, and how to explain it in the document.

**Comment by avikivity** [comment]
@nyh it's my fault for not supplying a good README, I can send something.

**Comment by nyh** [comment]
If you can even write a few lines, I'll complete the text and test it. Right have a file `build/dev/dist/docker/scylla-4.6.dev-0.20210829.4009d8b06` but have no idea how to run it with docker. I couldn't yet figure out how to use "skopeo" (or why do I even want to use it). Any hints you can give me would save me a lot of time scratching my head and Googling.

**Comment by nyh** [comment]
@avikivity I couldn't figure out how to use skopeo to run such an archive in docker, or how to run it directly in docker. It seems podman supports it out-of-the-box, though:
```
podman run oci-archive:build/dev/dist/docker/scylla-4.6.dev-0.20210829.4009d8b06
```
Seems to work. Do you know to run it in docker instead of podman?

**Comment by avikivity** [comment]
I haven't run docker in a while, I expect `docker import` will import it into local storage.

**Comment by yaronkaikov** [comment]
> @avikivity I couldn't figure out how to use skopeo to run such an archive in docker, or how to run it directly in docker. It seems podman supports it out-of-the-box, though:
> 
> ```
> podman run oci-archive:build/dev/dist/docker/scylla-4.6.dev-0.20210829.4009d8b06
> ```
> 
> Seems to work. Do you know to run it in docker instead of podman?

@nyh Same command with `docker` is working as well , just verified it locally

**Comment by nyh** [comment]
> @nyh Same command with `docker` is working as well , just verified it locally

It doesn't work for me - it tells me "docker: invalid reference format.". It works well in podman. My docker version is 20.10.7.

**Comment by yaronkaikov** [comment]
> > @nyh Same command with `docker` is working as well , just verified it locally
> 
> It doesn't work for me - it tells me "docker: invalid reference format.". It works well in podman. My docker version is 20.10.7.

So it's not working for me either (docker command was an alias for podman). Since we are using `buildah` for build process we can't really run it with docker. The only way is to actually publish the image to docker hub and then pull it again with docker. although it doesn't make sense for me at least :-)

**Comment by avikivity** [comment]
Developer documentation, so not backporting.
