### ISSUE TITLE
"ninja dist" fails when some empty directory somehow stayed behind

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#9264]
This is a spin-off from issue #9261.
I tried to build the distribution atrifacts (`ninja dist`), and got the following error:

```
 dpkg-source -b .
dpkg-source: warning: no source format specified in debian/source/format, see 
dpkg-source(1)
dpkg-source: warning: source directory 'scylla-python3-package' is not <source
package>-<upstreamversion> 'scylla-python3-4.6.dev-0.20210829.4009d8b06'
dpkg-source: warning: .orig directory name scylla-python3-package.orig is not 
<package>-<upstreamversion> (wanted scylla-python3-4.6.dev-0.20210829.4009d8b0
6.orig)
dpkg-source: error: orig directory 'scylla-python3-package.orig' already exists, not overwriting, giving up; use -sA, -sK or -sP to override
dpkg-source: info: using source format '1.0'
dpkg-source: info: building scylla-python3 using existing scylla-python3_4.6.dev-0.20210829.4009d8b06.orig.tar.gz
dpkg-buildpackage: error: dpkg-source -b . subprocess returned exit status 2
debuild: fatal error at line 1182:
dpkg-buildpackage -rfakeroot -us -uc -ui failed
```

As the error message suggests, a directory `tools/python3/build/debian/scylla-python3-package.orig` did exist - it was an empty directory. Removing it fixed the problem.

I don't know why this empty directory existed - it is quite possible that an earlier build either failed or was interrupted and left this empty directory behind. So, if it is important that this directory must not stay behind the build must make sure to delete it when exiting. Alternatively, if it is fine to overwrite an old directory, the build should either delete it or use the options suggested by the error message.

**Comment by syuu1228** [comment]
I didn't know this error, but I confirmed `scylla-python3-package.orig` is temporary directory that dpkg-buildpackage automatically create it while building, and also reproduced the error by creating the directory manually.
I will send a fix for this, not only python3 but all deb packages.

**Comment by syuu1228** [comment]
I find out it only occurs on scylla-python3. Sent a PR to fix: https://github.com/scylladb/scylla-python3/pull/23
