### ISSUE TITLE
toppartition is lost support of --ks-filter and --cf-filter (new api) from commit scylladb/scylla: c1daf2b

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#9268]
*Installation details*
Scylla version (or git commit hash): 4.5.rc6-0.20210817.88314fedf

During job: https://jenkins.scylladb.com/view/scylla-4.5/job/scylla-4.5/job/longevity/job/longevity-alternator-200gb-48h-test/3
command `nodetool toppartitions` was called  with parameters presented in commit: https://github.com/scylladb/scylla/commit/c1daf2bb24a43d398a5f209e052102afea6eb7de
and the command failed with next error:
```
'/usr/bin/nodetool -u cassandra -pw cassandra  toppartitions --ks-filters alternator_usertable,system_schema,system,system_auth,system_distributed --cf-filters system:cdc_local,system_distributed:cdc_streams_descriptions_v2,system:paxos,alternator_usertable:usertable,system:scylla_table_schema_history,system_auth:roles,system_schema:scylla_tables,system:compaction_history,system:scylla_table_schema_history -s 144 -k 6 -a writes -d 1893'
Exit code: 1
Stdout:
nodetool: toppartitions requires keyspace, column family name, and duration
See 'nodetool help' or 'nodetool help <command>'.
```

`nodetool help toppartitions` also return old result:
```
scyllaadm@alternator-48h-4-5-db-node-57b93461-1:~$ nodetool help toppartitions
NAME
        nodetool toppartitions - Sample and print the most active partitions for
        a given column family

SYNOPSIS
        nodetool [(-h <host> | --host <host>)] [(-p <port> | --port <port>)]
                [(-pw <password> | --password <password>)]
                [(-pwf <passwordFilePath> | --password-file <passwordFilePath>)]
                [(-u <username> | --username <username>)] toppartitions [-a <samplers>]
                [-k <topCount>] [-s <size>] [--] <keyspace> <cfname> <duration>

OPTIONS
        -a <samplers>
            Comma separated list of samplers to use (Default: all)

        -h <host>, --host <host>
            Node hostname or ip address

        -k <topCount>
            Number of the top partitions to list (Default: 10)

        -p <port>, --port <port>
            Remote jmx agent port number

        -pw <password>, --password <password>
            Remote jmx agent password

        -pwf <passwordFilePath>, --password-file <passwordFilePath>
            Path to the JMX password file

        -s <size>
            Capacity of stream summary, closer to the actual cardinality of
            partitions will yield more accurate results (Default: 256)

        -u <username>, --username <username>
            Remote jmx agent username

        --
            This option can be used to separate command-line options from the
            list of argument, (useful when arguments might be mistaken for
            command-line options

        <keyspace> <cfname> <duration>
            The keyspace, column family name, and duration in milliseconds

```

It seems that this functionality was removed from 4.5

**Comment by nyh** [comment]
Interesting, our documentation https://docs.scylladb.com/operating-scylla/nodetool-commands/toppartitions/ claims that this ks-filter and cf-filter thing was **added** in 4.5,  not removed in this version :-(

We should have a dtest for "nodetool toppartition" and all its different command-line parameters, so we wouldn't need to find such a regression in the "longevity" test.

**Comment by aleksbykov** [comment]
We have them on master, i am not sure, whether they backported to 4.5

**Comment by nyh** [comment]
The commit you mentioned, https://github.com/scylladb/scylla/commit/c1daf2bb24a43d398a5f209e052102afea6eb7de, *is* in 4.5 Scylla (since 4.5-rc1). So perhaps the **nodetool** or **JMX** changes aren't in 4.5's nodetool? I didn't check.
Your commit message says that this support was "lost" or "removed". Do you know that it ever existed in 4.5? Maybe it never did.

**Comment by roydahan** [comment]
@slivne this is missing from 4.5.
What do we do we this?

**Comment by slivne** [comment]
to late in the cycle to backport to 4.5 - we are not going to backport - this will be releases as part pf 4.6

**Comment by nyh** [comment]
> to late in the cycle to backport to 4.5 - we are not going to backport - this will be releases as part pf 4.6

Please remember to change the documentation - which today claims that this feature was added in 4.5 - accordingly. CC @lauranovich @tzach. I'll open a doc issue about that.

Also, I think we should have a specific dtest to check this feature, instead of relying on the longevity run to find it by accident. CC @aleksbykov

**Comment by roydahan** [comment]
I think there is a dtest for it (https://github.com/scylladb/scylla-dtest/pull/2147) but for some reason (probably human error) it wasn't backported to 4.5.

**Comment by nyh** [comment]
> I think there is a dtest for it ([scylladb/scylla-dtest#2147](https://github.com/scylladb/scylla-dtest/pull/2147)) but for some reason (probably human error) it wasn't backported to 4.5.

Thanks, makes sense. But isn't that ironic - a bug that was caused by forgetting to backport a feature, wasn't caught because we also forgot to backport the test :-)

**Comment by roydahan** [comment]
> > I think there is a dtest for it ([scylladb/scylla-dtest#2147](https://github.com/scylladb/scylla-dtest/pull/2147)) but for some reason (probably human error) it wasn't backported to 4.5.
> 
> Thanks, makes sense. But isn't that ironic - a bug that was caused by forgetting to backport a feature, wasn't caught because we also forgot to backport the test :-)

Yep, our process with these type of things isn't great.
