### ISSUE TITLE
mutation fragment stream validator doesn't print the partition key for invalid rows/range tombstones

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9269]
For example:
```
flat_mutation_reader - [validator 0x6020009c97e0 for compacting_sstable_writer /home/bhalevy/.dtest/dtest-4h7glxn5/test/node2/data/ks/cf-96a006900a3f11ec889c000000000001/mc-1349-big-Data.db (ks.cf 96a00690-0a3f-11ec-889c-000000000001)] Unexpected mutation fragment: previous clustering row:{position: clustered,ckp{},0}, current clustering row:{position: clustered,ckp{},0}
```

The partition key is readily available as we keep track of the last key for partition_key validation.

**Comment by bhalevy** [comment]
@cmm, this is a simple change to get acquainted with this area of the code.
Can you please look into it?

**Comment by bhalevy** [comment]
Note: rows in the context of this issue include both static rows and clustering rows.
Bottom-line, let's scrub the code and print the partition_key anywhere it's missing and would be useful.

**Comment by avikivity** [comment]
Cosmetic/debug, not backporting.
