### ISSUE TITLE
docs: Invalid path `dist/docker/redhat/README.md` in README.md

### ISSUE THREAD

**Issue by Rjerk** [scylladb/scylla#9276]
The path `[Docker image build documentation](dist/docker/redhat/README.md)` in README.md (https://github.com/scylladb/scylla#building-scylla) is invalid.

It looks like the RedHat document has been removed.

------------

This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

**Comment by nyh** [comment]
Indeed. I just noticed this a few days ago. The replacement is dist/docker/debian/README.md, and it used to contain inaccurate or outdated information until I improved it a couple of days ago.

I'll prepare a patch to README.md.
