### ISSUE TITLE
Deleting a row with a null clustering key is forbidden in Cassandra, ignored in Scylla

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#9290]
Pull request #9286 by @dekimir fixed an earlier issue #7852 where attempting to insert a row with a null key appeared to succeed (while doing nothing), but should have resulted in an error.

After that fix, a similar problem remains in `DELETE` statements: The statement
```
DELETE FROM table1 WHERE p='p' AND c=null
```
results in an error in Cassandra, but is silently ignored in Scylla. It is only ignored in the clustering key `c` case. For the partition-key case - `WHERE p=null` - Scylla does produce an error as expected.

The reason why I'm marking this issue "low" is that I am not convinced that Scylla's behavior in this case isn't the more correct one (although there's also value in being compatible with Cassandra unless there is a _compelling_ reason not to):

The thing is, unlike the restriction on the partition key which must be an equality to one value, the `WHERE` restriction on the clustering can a general expression, and may be one that is never true, such as `DELETE WHERE p='p' AND c>0 and c<0`. So one might say that `WHERE ... c=null` isn't any different - it's just a condition that can never be true, and should be allowed. This is very different from an `INSERT`, which always writes a row, so must produce an error if it doesn't.

If we do decide to fix this difference from Cassandra, the relevant code is in `cql3/statements/modification_statement.cc`,  commented by a TODO.

We have two tests related to this issue:
* `test/cql-pytest/test_null.py`::`test_delete_null_key` testing `DELETE ... WHERE p='p' AND c=null` and currently xfails (fails on Scylla, passes on Cassandra). This test also confirms that a null equality for the partition key (`WHERE p=null`) is forbidden, also in Scylla.
* `test/cql-pytest/test_null.py`::`test_delete_impossible_clustering_range` shows that other always-false restrictions on the clustering key are allowed, also on Cassandra.

**Comment by dekimir** [comment]
I believe this only applies to clustering columns. Partition-column nulls are rejected by both Scylla and Cassandra.

**Comment by nyh** [comment]
> I believe this only applies to clustering columns. Partition-column nulls are rejected by both Scylla and Cassandra.

Thanks. I'll write a test to confirm this and update the issue text above.

**Comment by dekimir** [comment]
There already is a test in #9286, see the xfail comment.

**Comment by nyh** [comment]
Thanks. I edited the issue text and title above to correct it for the fact that the problem is just for null clustering key, not partition key.
