### ISSUE TITLE
No possibility to audit DML, DDL logs for all keyspaces.

### ISSUE THREAD

**Issue by karol-kokoszka** [scylladb/scylla#9297]
In scylla-cloud, we would like to monitor, what exactly the end user is doing during his/her free-trial period. We want to  answer the question, whether the 3 hours that we give customers to work with free-trial clusters, is enough. 

To achieve that goal, we think about observing scylla-audit logs in one of our log observation tools - Logzio.
There is one piece of the puzzles missing that stops us from implementing this solution tough.
According to https://docs.scylladb.com/operating-scylla/security/auditing/, the only logs that we can observe without knowing what keyspaces are going to be used on a cluster, are DCL, AUTH and ADMIN categories `You can use DCL, AUTH, and ADMIN audit categories without including any keyspace or table.`

Can we add some wildcard to the required `audit_keyspaces`, that will let us to observe DDL, DML from every keyspaces on the cluster ?
Linked issue https://app.zenhub.com/workspaces/scylla-cloud-5d13d401e0945f63bfe3168b/issues/scylladb/siren/5886

**Comment by tzach** [comment]
Audit is a Scylla Enterprise feature.
