### ISSUE TITLE
Scylla should not create row markers in tables with compact storage

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#931]
In cqlsh:
```
create keyspace ks with replication = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 };
create table ks.cf2 (key int PRIMARY KEY, c1 text, c2 text) with compact storage;
insert into ks.cf2 (key) values (8);
select c1 from ks.cf2;
```

C* 2.1.9:
```
cqlsh> select c1 from ks.cf2;

 key | c1 | c2
-----+----+----

(0 rows)
```

Scylla:
```

 c1
------
 null

(1 rows)
```

**Comment by tzach** [comment]
@tgrabiec why is Scylla wrong here?
Its look like a C* bug to me

**Comment by tgrabiec** [comment]
@tzach C* is pretty explicit about inserting markers only in cql3 tables. Note that the table is created with `compact storage`, which is a thrift compatibility mode. Perhaps they can't just piggy back on some cell names to represent the row marker because those names might be used by existing thrift code for something else.
