### ISSUE TITLE
disable_auto_compaction doesn't stop ongoing compactions

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9313]
The api call disables new regular compaction jobs from starting but it doesn't wait for ongoing compaction to stop and so it's much less useful.

Returning after stopping regular compaction jobs and waiting for them to stop guarantees that no regular compactions job are running when `nodetool disableautocompaction` returns successfully.

**Comment by raphaelsc** [comment]
good catch. without waiting for ongoing compactions, it could happen that compactions will only cease once the underlying strategy is satisfied.

**Comment by bhalevy** [comment]
@raphaelsc I sent a couple patches to the mailing list:
```
[PATCH 1/2] compaction: stop_ongoing_compactions: add optional compaction_type
[PATCH 2/2] table: disable_auto_compaction: stop ongoing compaction
```

**Comment by avikivity** [comment]
Reopened by 8e8dc2c930f5541531c3326127f012e7bc6292ef

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please consider e6fe9cc683f49f4176ef8e7ee2b584b127a97036 for backport to 5.0

**Comment by avikivity** [comment]
I think it's not a regression in 5.0, so it's better to reduce 5.0 risk by not backporting i.t

**Comment by bhalevy** [comment]
> I think it's not a regression in 5.0, so it's better to reduce 5.0 risk by not backporting i.t

The problem is that dtests (and possibly naive users too) are now expecting this when disabling auto compaction.
I'm afraid that not backporting it could create noise in testing.

**Comment by avikivity** [comment]
@bhalevy I missed your comment. Do you still think a backport is needed?

**Comment by bhalevy** [comment]
> @bhalevy I missed your comment. Do you still think a backport is needed?

No, eventually it seems like there are no particular issues that require backport.

**Comment by avikivity** [comment]
Removing label.
