### ISSUE TITLE
Package scylla-top.py in scylla-tools

### ISSUE THREAD

**Issue by dorlaor** [scylladb/scylla#933]
We need it and also its dependencies (collectd plus configuration)

**Comment by syuu1228** [comment]
If we want to package scylla-top.py in scylla-tools, we have to move scylla-top.py codes to scylla-tools repository.
Otherwise, we can create scylla-top package in scylla-server repository.

**Comment by avikivity** [comment]
We can have a scylla-top repository.

**Comment by syuu1228** [comment]
Maybe 'git clone https://github.com/scylladb/scylla-top.git' in scylla-tools-java's package build script?

**Comment by syuu1228** [comment]
Or submodule

**Comment by slivne** [comment]
I don't understand why a different repo - we are going to potentially have many tools - each will have its own repo ?

**Comment by avikivity** [comment]
scylla-tools-java is for cassandra-derived tooling, let's not push more stuff there.

**Comment by avikivity** [comment]
We can have a scylla-tools.git that has scylla-tools-java as a submodule, but we don't really need to add submodules here

**Comment by syuu1228** [comment]
Maybe we can create scylla-tools repo, for new stuff + packaging script,
scylla-tools-java can refer as submodule from here

2016年2月24日水曜日、Avi Kivity<notifications@github.com>さんは書きました:

**Comment by avikivity** [comment]
Let's just package it in scylla-server for now.

**Comment by syuu1228** [comment]
Looks like it depends on collectd, and requires configuration on /etc/collectd.conf.
Probably add another script to configure collectd.conf on scylla_setup?
