### ISSUE TITLE
utils/small_vector.hh: copy constructor is marked `noexcept` even though it does allocations

### ISSUE THREAD

**Issue by enedil** [scylladb/scylla#9337]
Here, the copy constructor is marked noexcept:
```cpp
    small_vector(const small_vector& other) noexcept : small_vector() {
        reserve(other.size());
        _end = std::uninitialized_copy(other.begin(), other.end(), _end);
    }
```

https://github.com/scylladb/scylla/blob/1fd701e709e9fcfd608ae925634401ba3626614a/utils/small_vector.hh#L195

This is done even though later there is a `reserve` call which does allocations. This causes issues for instance with tests using `alloc_failure_injector`.

**Comment by slivne** [comment]
fixed by 7c8b89528524a461b1041d2f1456ea99bfe282a0
