### ISSUE TITLE
column_family::discard_sstables crashes after running scylla for a while

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#934]
Jason Wang reported the following: "
Hi, I keep getting this error when experimenting with Scylla locally by running my application test suit against it. 
Can anyone shed some light on what could be causing this failure?

The test suite consistently runs for around 30min and then scylla crashes with the following error. 

scylla: database.cc:2278: future<db::replay_position> column_family::discard_sstables(db_clock::time_point): Assertion `_stats.pending_compactions == 0' failed."

As I explained in the mailing list, _stats.pending_compactions should probably not be used if the intention is to check that there is no ongoing compaction on the current column family. _stats.pending_compactions only stores the number of pending compaction requests, i.e. requests that weren't handled by compaction manager yet. 

I think this assert can be removed completely. column_family::discard_sstables() runs in callback passed to run_with_compaction_disabled(), which guarantees that there is no ongoing compaction for the calling column family.

**Comment by raphaelsc** [comment]
@elcallio thoughts?

**Comment by elcallio** [comment]
You are correct about the intent. And looking at the (current) code, it seems you are right about the mistaken meaning of the field as well. However, it could be noted, since run_with_compaction exists, and can remove a column_family from the compaction_manager, it would seem we could end up with _pending_compaction set to > 0 forever, if we inc, add, then run suddenly remove it before compaction manager calls run_compaction. 

Me thinks run_with_compaction_disabled should zero the counter once the CF is removed from compaction queue.

**Comment by raphaelsc** [comment]
@elcallio Agreed. Feel free to send the patch.

**Comment by elcallio** [comment]
Will do.

**Comment by elcallio** [comment]
Actually, @raphaelsc, it looks to me that pending_compactions is broken in other ways as well. 
If we call trigger_compaction, the counter is incremented, andthen we call compaction_manager::submit, which adds it to the queue (setting the flag in cf). 
But if we call it trigger_compaction again, before the queue is processed, it will not be re-added, and thus run_compaction is only run once -> counter will be left > 0. 
Why does the counter even exist? It would seem that the compaction_manager_queued() attribute provides pretty much the info needed?
In any case, just resetting the counter in run_with_compaction_disabled will not really work, as continuation rescheduling could then cause us to decrement 0 -> very high values. 
I'm now leaning towards that it should be the compaction manager that manages these counters.

**Comment by raphaelsc** [comment]
@elcallio: Sorry for the confusion, but column_family will be kept queued by compaction manager as long as _pending_compactions > 0. In case of run_with_compaction_disabled(), column family be removed from compaction manager even if _pending_compactions > 0. By the way, compaction manager decision to re-schedule a compaction for a column family is based on _pending_compactions. If _pending_compactions == 0, there is no-reschedule and column_family::compaction_manager_queued() will now return false. _pending_compactions is increased every time that column family submits a compaction request to compaction manager, and it's decreased every time that compaction manager starts a compaction for that column family.

**Comment by slivne** [comment]
@elcallio @raphaelsc  - who is working on creating a patch for this ?

**Comment by elcallio** [comment]
I am. I'll send it asap. 
I'm taking the liberty of cleaning up the semantics/usage of the counter a little, plus adding some comments.

**Comment by penberg** [comment]
The commit was reverted because it broke ``sstable_test``, reopening the issue:

https://github.com/scylladb/scylla/commit/a4d92750ebdf94f8635504f27688e8072ebac18e

**Comment by penberg** [comment]
The problem was in test code and was fixed by @raphaelsc:

https://github.com/scylladb/scylla/commit/7f0371129c3addc65c91ede28eb9c777408e3133

The revert was reverted by:

https://github.com/scylladb/scylla/commit/fc4cbcde72cc3c51a70bd7102f22022651b4e639

**Comment by raphaelsc** [comment]
On Fri, Feb 26, 2016 at 4:57 AM, Pekka Enberg <notifications@github.com>
wrote:

> The problem was in test code and was fixed by @raphaelsc
> <https://github.com/raphaelsc>:
>
> 7f03711
> <https://github.com/scylladb/scylla/commit/7f0371129c3addc65c91ede28eb9c777408e3133>
>
> The revert was reverted by:
>
> fc4cbcd
> <https://github.com/scylladb/scylla/commit/fc4cbcde72cc3c51a70bd7102f22022651b4e639>
>

Thanks @penberg!

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/934#issuecomment-189153043>.
>



-- 
Raphael S. Carvalho
