### ISSUE TITLE
Exceptions in commitlog::segment_manager::delete_segments could cause footprint counters to loose track

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#9348]
If we get errors/exceptions in `delete_segments` we can (and probably will) loose track of disk footprint counters. This can in turn, if using hard limits, cause us to block indefinitely on segment allocation since we might think we have larger footprint than we actually do. 

Of course, if we actually fail deleting a segment, it is 100% true that we still technically hold this disk footprint (now unreachable), but for cases where for example outside forces (or wacky tests) delete a file behind our backs, this might not be true. One could also argue that our footprint is the segments and file names we keep track of, and the rest is exterior sludge. 

In any case, if we have any exceptions in `delete_segments`, we should recalculate disk footprint based on current state, and restart all `new_segment` paths etc.

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please backport to 4.6 to help investigate https://github.com/scylladb/scylla/issues/9152

@elcallio does this need backport also to 4.5?

**Comment by elcallio** [comment]
@bhalevy - should not be needed in 4.5.

**Comment by denesb** [comment]
I get conflicts when attempting to backport, @elcallio please prepare a PR with the backport against branch-4.6.

**Comment by bhalevy** [comment]
> I get conflicts when attempting to backport, @elcallio please prepare a PR with the backport against branch-4.6.

ping @elcallio

**Comment by elcallio** [comment]
#9702
