### ISSUE TITLE
commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#935]
I saw the following  with latest master:

commit 79bcb5a616fb3fc1b9b02bcb497f4a5fe6123cab
Author: Tomasz Grabiec <tgrabiec@scylladb.com>
Date:   Tue Feb 23 19:12:54 2016 +0100

    tests: Fix build of memory_footprint 

in update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_decommission_node_2_test dtest.

```
INFO  [shard 0] database - Keyspace /home/asias/.dtest/dtest-VXcPEl/test/node2/data/system: Reading CF paxos
INFO  [shard 0] database - Keyspace /home/asias/.dtest/dtest-VXcPEl/test/node2/data/system: Reading CF IndexInfo
INFO  [shard 0] database - Populating Keyspace ks
INFO  [shard 0] database - Keyspace /home/asias/.dtest/dtest-VXcPEl/test/node2/data/ks: Reading CF cf
INFO  [shard 0] commitlog_replayer - Replaying /home/asias/.dtest/dtest-VXcPEl/test/node2/commitlogs/CommitLog-1-677249.log, /home/asias/.dtest/dtest-VXcPEl/test/node2/commitlogs/CommitLog-1-677250.log
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
WARN  [shard 0] commitlog_replayer - error replaying: std::out_of_range (deserialization buffer underflow)
```

The test fails now. Any changes in commitlog recently?

**Comment by penberg** [comment]
This commit changed the format of commitlog:

https://github.com/scylladb/scylla/commit/f72fd9eefd356fc5e6fff36b6839a1fa69cf9677

I am guessing it's not backwards compatible. Ping @tgrabiec

**Comment by asias** [comment]
On Wed, Feb 24, 2016 at 2:21 PM, Pekka Enberg <notifications@github.com>
wrote:

> This commit changed the format of commitlog:
>
> f72fd9e
> <https://github.com/scylladb/scylla/commit/f72fd9eefd356fc5e6fff36b6839a1fa69cf9677>
>
> I am guessing it's not backwards compatible. Ping @tgrabiec
> <https://github.com/tgrabiec>
>
I deleted all the data before the test. No old data should exist.

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scylladb/scylla/issues/935#issuecomment-188099139>.
>



-- 
Asias

**Comment by tgrabiec** [comment]
That's right, there was a backwards incompatible change of commit log data.

**Comment by slivne** [comment]
To make it clearer

The test itself does not use "old" format of commitlogs - if any commitlog
files are created they are created at runitme and are replayed because a
node was shutdown in the test and then started back up.

As such the issue is in the same code base we are creating commitlogs and
are not able to replay them for some reason.

It may a change in flushing as well I guess

One item to check is if we have incomplete records if it is handled
correctly - the previous code could handle it (I think) - calle ?

**Comment by elcallio** [comment]
The IDL for "commitlog_entry" uses std::experimental::optional<column_mapping> in the idl type. 
A wild guess might be that the serialization/deserialization of this lacks in symmetry?

**Comment by amnonh** [comment]
On Wed, Feb 24, 2016 at 11:09 AM, Calle Wilund <notifications@github.com>
wrote:

> The IDL for "commitlog_entry" uses std::experimental::optional in the idl
> type.
> A wild guess might be that the serialization/deserialization of this lacks
> in symmetry?
>
Could be, for writer and reader optional support is not merged yet and was
fully tested. but for serialization/deserialization it's being there
for some time.

I'm trying to create a test for it to see if there are problem with
serialization.

**Comment by elcallio** [comment]
I could repro this just fine. 
The out-of-bounds happens after commitlog_entry has been deserialized, when the code is actually trying to use frozen_mutation::column_family_id(), which in turn uses the generated mutation_view partial deserialization. 
Whether or not there is an actual error there, or if simply the frozen_mutation is corrupted in itself, I have not been able to determine yet.

**Comment by elcallio** [comment]
Update, seems the frozen_mutation part of the commitlog_entry contains only zeroes, which would be why we get an underflow (skip<read_int> - sizeof(int) -> skip <0-4> -> skip <high number>)

**Comment by amnonh** [comment]
Do you know if the all zero buffer is in the writing or the reading?

**Comment by elcallio** [comment]
Only gotten so far as to see its what it manages to deserialize after a while.
