### ISSUE TITLE
recent regression: our docker image doesn't work if no command-line paramters are passed

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#9355]
Commit ed7106ebd7234574c38c7c1a7eaba2d170da7803 fixed #9247, whereby our docker image ignored its command line parameters, but caused a new regression - which was first reported by @benipeled in https://github.com/scylladb/scylla-pkg/issues/2395.

The problem is that although this commit fixed the case where command line parameters **are** passed to the image - these command line parameters are now correctly appended to the "entry point" - it broke the case where command-line parameters **aren't** passed - for example while
```
podman run --name scylla -d -p 8000:8000 oci-archive:... --alternator-port=8000 --alternator-write-isolation=always
```
works (and starts Scylla with the command-line parameters needed for Alternator), the command
```
podman run --name scylla -d -p 8000:8000 oci-archive:...
```
without any added command line parameters does *not* work, and produces a weird error about the word "bash" at the end of the Scylla command line:
```
parsed command line options: [log-to-syslog: 1, log-to-stdout: 0, default-log-level: info, network-stack: posix, developer-mode: 1, overprovisioned, listen-address: 10.0.2.100, rpc-address: 10.0.2.100, seed-provider-parameters: seeds=10.0.2.100, blocked-reactor-notify-ms: 999999999, (positional) bash]
error: too many positional options have been specified on the command line
```

The problem is that a docker image has a "cmd" setting separate from the "entry point" setting. The "entry point" is always used and if no command-line parameters are passed to the docker run, "cmd" is passed as the default parameters. Because our docker image doesn't specify a "cmd", we inherit one from Ubuntu's image, which turned out to be "bash" (!). We need our image's "cmd", i.e., default command-line parameters to the entry point, to be empty.

**Comment by nyh** [comment]
No need to backport the fix to this issue - it fixes a recent regression (https://github.com/scylladb/scylla/commit/ed7106ebd7234574c38c7c1a7eaba2d170da7803) which never reached any version branch and will never reach one because it itself was a fix to an earlier regression which also never reached a version branch.

**Comment by avikivity** [comment]
Not backporting per @nyh assessment.
