### ISSUE TITLE
Support BTRFS (was: Support bind-mounted data volumes in docker container)

### ISSUE THREAD

**Issue by gwicke** [scylladb/scylla#936]
It would be useful to be able to use bind-mounted data directories for somewhat more realistic performance evaluations. However, when starting the docker container with bind-mounted /var/lib/scylla (with config or without), startup does not finish:

``` bash
# docker run -it -v /tmp/scylla:/var/lib/scylla -p 127.0.0.1:9042:9042 scylladb/scylla 
WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.
EAL: Detected lcore 0 as core 0 on socket 0
EAL: Detected lcore 1 as core 0 on socket 0
EAL: Detected lcore 2 as core 1 on socket 0
EAL: Detected lcore 3 as core 1 on socket 0
EAL: Support maximum 128 logical core(s) by configuration.
EAL: Detected 4 lcore(s)
EAL: VFIO modules not all loaded, skip VFIO support...
EAL: Setting up physically contiguous memory...
EAL: TSC frequency is ~2693769 KHz
EAL: Master lcore 0 is ready (tid=275265c0;cpuset=[0])
EAL: lcore 3 is ready (tid=19d58700;cpuset=[3])
EAL: lcore 1 is ready (tid=1ad5a700;cpuset=[1])
EAL: lcore 2 is ready (tid=1a559700;cpuset=[2])
Scylla version 0.18-20160216.b532919 starting ...
Scylla API server listening on 127.0.0.1:10000 ...
```

It just sits there, and never reaches:

``` bash
Starting listening for CQL clients on 172.17.0.20:9042...
```

**Comment by avikivity** [comment]
Is /tmp/scylla on tmpfs? If so, try xfs. tmpfs has strange behavior with aio.

**Comment by gwicke** [comment]
/tmp/scylla is on btrfs in this case.

**Comment by dorlaor** [comment]
btrfs is also unfriendly towards aio which will ruin performance (thought
it should work).
XFS is the only proper path towards performance.

**Comment by penberg** [comment]
@gwicke @dorlaor, I am running btrfs on my development machine and it is not just unfriendly towards AIO/DIO, it's totally unusable I am afraid.

**Comment by avikivity** [comment]
Still doesn't explain why it doesn't start up. @gwicke please attach an strace -fF -ttT

**Comment by gwicke** [comment]
`strace -fF -ttT` as root:
[strace.txt](https://github.com/scylladb/scylla/files/151958/strace.txt)

**Comment by slivne** [comment]
we can reconsider this if/when btrfs will have better AIO support

**Comment by nyh** [comment]
Not critical, but It would still be nice to get some sort of error message that AIO is not functional (or whatever) instead of  a mysterious hang.

**Comment by penberg** [comment]
@nyh The report is from February 2016. We should have an error message stating that the filesystem is not supported now.

**Comment by avikivity** [comment]
It should not hang on btrfs (just be extremely slow).
