### ISSUE TITLE
collection_serialization_with_protocol_v2_test fails with: marshaling error: read_simple_bytes - not enough bytes (requested 1627390306, got 3)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9360]
Regression seen since https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/930/testReport/junit/cql_additional_tests/TestCQL/collection_serialization_with_protocol_v2_test/

Scylla version 08042c16888cf3f0614c50d788c7d2e2105de682

```
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/case.py", line 60, in testPartExecutor
    yield
  File "/usr/lib64/python3.7/unittest/case.py", line 645, in run
    testMethod()
  File "/jenkins/workspace/scylla-master/dtest-release/scylla-dtest/cql_additional_tests.py", line 2117, in collection_serialization_with_protocol_v2_test
    session.execute(update_q % "tags = tags + [ 'a', 'b', 'c' ]")
  File "cassandra/cluster.py", line 2611, in cassandra.cluster.Session.execute
  File "cassandra/cluster.py", line 4829, in cassandra.cluster.ResponseFuture.result
cassandra.cluster.NoHostAvailable: ('Unable to complete the operation against any hosts', {<Host: 127.0.11.1:9042 datacenter1>: <Error from server: code=0000 [Server error] message="marshaling error: read_simple_bytes - not enough bytes (requested 1627390306, got 3) Backtrace: 0x411fa8e 0x411ff80 0x4120288 0x10eea5c 0x10ee6f4 0x1bc8c4b 0x2007930 0x1c21be1 0x1bf83c1 0x1bfb901 0x1d7d1b2 0x1d7d96a 0x1d52d36 0x1d4fa75 0x1d585e1 0x1d552fe 0x1d62ba7 0x1d62bec 0x1d5ff44 0x3d45c05 0x3d8f7cf 0x3d90ba7 0x3dadc15 0x3d6882a 
```

**Comment by bhalevy** [comment]
git bisect points at a0ec2113ae5c318d31e2bfacd4a1c17819d4db7a

@avikivity I suggest we revert the whole series (a0ec2113ae5c318d31e2bfacd4a1c17819d4db7a)
and fix the issue out of tree.

**Comment by cvybhu** [comment]
Oops, I will look into it

**Comment by psarna** [comment]
@cvybhu if you look at the number of bytes that were seemingly requested, it's 1627390306, which is 61000162 in hex, which translates to `a\x00\x01b` in ascii. The elements of the collection in this test case are strings `a`, `b` and `c`, which doesn't sound like a coincidence. Looks like some offset is messed up when trying to deserialize a collection, or perhaps it's a dangling view, which could cause similar symptoms.

**Comment by cvybhu** [comment]
The issue was with old v2 CQL protocol, I should have changed the `get()` of collections to return a collection serialized with the internal cql serialization format, but instead they were serialized with query cql serialization format :/
It's an easy fix, but I'm just trying to run `cql_additional_tests.py` locally before opening a PR, to make sure everything will pass this time.
https://github.com/cvybhu/scylla/blob/fd98d40b75add164263411be67b7a8e6fe358335/cql3/lists.cc#L72-L76

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
