### ISSUE TITLE
Commitlog counters don't really show allocation pressure iff limiting factor is disk

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#9367]
The CL counters `pending_allocations` and `requests_blocked_memory` are exposed in graphana (etc) and often referred to as metrics on whether we are blocking on commit log. But they don't really show this, as they only measure whether or not we are blocked on the _memory_ bandwidth semaphore that provides rate back pressure (fixed num bytes/s - sortof). 

However, actual tasks in allocation or segment wait is not exposed, so if we are blocked on disk IO or waiting for segments to become available, we have no visible metrics. 

While the "old" counters certainly are valid, I have yet to ever see them be non-zero in modern life.

**Comment by avikivity** [comment]
Minor, not backporting.
