### ISSUE TITLE
Snapshow for truncation broken

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#937]
When fixing #884, the logic guarding the snapshot sync logic was broken as well, causing a truncate snapshot to never finish. 
The problem is that snapshot uses the snapshot name as key for synchronizing all shards (quite reasonable), but the truncation logic now uses per-shard time stamps -> slightly different "names" (snapshot-<time>).

**Comment by slivne** [comment]
Lets add a test as well - this should fail in regression

**Comment by elcallio** [comment]
Note that the APIs and function in use for truncate and
snapshot are at best slightly misleading, since they give
the impression of being ordinary instance methods, yes require
caller to ensure they are invoked on all (active) shards. 
A better approach would probably be to have database and 
column_family static truncate/snapshow methods that accept
a distributed<type> as parameter instead, and hide the 
nitty gritty. But all in due time. I will send a fix for the immediate problem.
