### ISSUE TITLE
Database::apply commitlog write failures should add more verbose info on mutation that failed

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#9408]
While it is rare, some customer issues have shown that we can run into cases where commit log apply (writing mutations to it) fails badly. In the known cases, due to oversized mutations. While these should have been caught earlier in the call chain really, it would probably help both end users and us (trying to figure out how they got so big and how they got so far) iff we actually added some info on which mutation actually was in play (ks, cf, mutation content). 

Note that this needs to be done in database, since at lower levels, we don't really know any of this.

**Comment by avikivity** [comment]
Not a bug, not backporting.
