### ISSUE TITLE
"Keep local_host_id in local_cache" apparently broke gossip logic for replace

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9425]
We have a bunch of dtest regressions in replace address tests:
https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/946/testReport/replace_address_test/

git bisect of replace_address_test.py:TestReplaceAddress_rbo_enabled.replace_node_diff_ip_test
pointed me at 9f5fd8b5c0 system_keyspace: Keep local_host_id on local_cache

@xemul please look into this.

Cc @asias

**Comment by xemul** [comment]
What I see from test is that the test waits for the "has been silent for" message in other nodes' logs about node5 shutdown, while in logs I see that node5 left the cluster "regularly" with the help of shutdown message.

**Comment by bhalevy** [comment]
> What I see from test is that the test waits for the "has been silent for" message in other nodes' logs about node5 shutdown, while in logs I see that node5 left the cluster "regularly" with the help of shutdown message.

@xemul I think that in https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/946/artifact/logs-all.release.2/1633311960254_replace_address_test.TestReplaceAddress_rbo_enabled.replace_node_diff_ip_test/node4.log
```
ERROR 2021-10-04 01:35:40,870 [shard 0] rpc - client 127.0.31.5:7000: fail to connect: Connection refused
et al.
```

Are errors due to gossip sending ack rpcs to the AWOL node.
I think that the "FatClient has been silent for" message is where gossip forgets about it entirely.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
