### ISSUE TITLE
Repair is chocking the disk

### ISSUE THREAD

**Issue by noamha** [scylladb/scylla#944]
Configuration:
- 4 nodes x Rackspace OnMetal IO v1 CentOS 7.0
- Scylla 0.18 Head

Steps:
- Started a 3 nodes cluster
- Init Keyspace on all 3 servers
```
cassandra-stress write n=1 cl=ALL -schema "replication(factor=3)" -mode native cql3 -node $SERVERS
```
- Populate with 5M keys
time cassandra-stress write cl=TWO n=5000000 -mode native cql3 -rate threads=700 -node $SERVERS -pop seq=1..5000000 -col 'size=FIXED(2048) n=FIXED(5)'

- Write a constant very low stress
time cassandra-stress write cl=TWO n=50000000 -mode native cql3 -rate threads=10 -node $SERVERS -pop seq=5000000..1000000000 -col 'size=FIXED(2048) n=FIXED(5)'

- Stop node3
- Delete sstables from node3
- Start node3
- Run nodetool repair

When load running without streaming:
```
Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00     0.00  151.50  794.00 18958.00 78210.00   205.54     0.24    0.26    0.47    0.21   0.21  20.20
sdc               0.00     0.00  148.00  845.50 18820.00 78600.00   196.11     0.25    0.26    0.50    0.21   0.20  19.95
md0               0.00     0.00  299.50 1640.00 37778.00 156810.00   200.66     0.00    0.00    0.00    0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          17.86    0.00    5.73    0.00    0.00   76.42

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00     0.00  344.50 1125.50 43302.00 120498.00   222.86     0.39    0.26    0.43    0.22   0.21  31.35
sdc               0.00     0.00  345.00 1178.50 43272.00 119812.00   214.09     0.42    0.28    0.40    0.24   0.22  33.45
md0               0.00     0.00  689.50 2304.50 86574.00 240310.00   218.36     0.00    0.00    0.00    0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          15.83    0.00    5.34    0.00    0.00   78.83

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.50    0.00    1.00     0.00     6.00    12.00     0.00    0.50    0.00    0.50   0.50   0.05
sdb               0.00    52.00    0.00  573.00     0.00 42946.00   149.90     0.12    0.22    0.00    0.22   0.17   9.75
sdc               0.00    45.00    0.00  601.50     0.00 43373.75   144.22     0.14    0.24    0.00    0.24   0.17  10.10
md0               0.00     0.00    0.00 1271.50     0.00 86319.75   135.78     0.00    0.00    0.00    0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          17.53    0.00    5.81    0.00    0.00   76.66

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00     0.00  426.00 1321.00 53722.00 145974.00   228.62     0.52    0.30    0.50    0.23   0.22  38.85
sdc               0.00     0.00  426.50 1383.00 53848.00 145490.00   220.32     0.55    0.30    0.54    0.23   0.22  40.00
md0               0.00     0.00  853.00 2706.00 107634.00 291530.00   224.31     0.00    0.00    0.00    0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          16.96    0.00    5.45    0.00    0.00   77.59

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    1.00     0.00     8.00    16.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00     0.00  108.00  978.50 12834.00 101240.00   209.98     0.27    0.25    0.51    0.22   0.20  21.50
sdc               0.00     0.00  106.50 1026.00 12762.00 101062.00   201.01     0.27    0.24    0.53    0.21   0.19  21.15
md0               0.00     0.00  214.00 2003.00 25532.00 202236.00   205.47     0.00    0.00    0.00    0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          17.00    0.00    5.58    0.01    0.00   77.41

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     0.00    0.00    0.00     0.00     0.00     0.00     0.00    0.00    0.00    0.00   0.00   0.00
sdb               0.00     0.00    6.50  818.00    26.00 80112.00   194.39     0.18    0.22    0.00    0.22   0.20  16.45
sdc               0.00     0.00    5.00  862.00    20.00 80382.00   185.47     0.20    0.23    0.00    0.23   0.19  16.90
md0               0.00     0.00   11.50 1680.00    46.00 160494.00   189.82     0.00    0.00    0.00    0.00   0.00   0.00
```

And then with streaming:
```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          91.08    0.00    8.01    0.92    0.00    0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     2.40    7.40    7.80   947.20  2763.20   488.21     0.56   36.95    2.08   70.03   4.12   6.26
sdb            6828.40     4.40 16285.00  541.40 1391047.10 64697.20   173.03    83.40    4.95    5.03    2.77   0.06  99.74
sdc            6835.80     5.80 16239.00  543.00 1389381.80 64641.00   173.28    89.07    5.30    5.38    2.91   0.06 100.00
md0               0.00     0.00 39107.40 1095.60 2780217.20 129389.40   144.75     0.00    0.00    0.00    0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          90.33    0.00    8.25    1.42    0.00    0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     3.60    7.20    1.20   921.60    20.80   224.38     0.01    0.62    0.58    0.83   0.62   0.52
sdb            6721.80     0.40 16320.20  566.20 1367960.50 68045.60   170.08    76.34    4.52    4.59    2.47   0.06  99.92
sdc            6739.80     0.20 16242.60  561.80 1366457.60 67780.00   170.70    91.82    5.46    5.55    2.73   0.06 100.00
md0               0.00     0.00 39057.80 1128.80 2734830.30 135800.00   142.87     0.00    0.00    0.00    0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          90.66    0.00    8.04    1.31    0.00    0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     1.20    7.00    0.60   896.00     8.00   237.89     0.00    0.50    0.49    0.67   0.50   0.38
sdb            6954.40     0.00 16688.60  474.40 1407675.60 55935.20   170.55    74.86    4.36    4.41    2.51   0.06  99.92
sdc            6976.80     0.20 16660.20  470.40 1409578.40 55828.80   171.09    95.25    5.56    5.63    2.95   0.06  99.90
md0               0.00     0.00 40068.00  945.80 2817365.30 111840.00   142.84     0.00    0.00    0.00    0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          90.32    0.00    8.36    1.33    0.00    0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     1.20    7.40    7.80   947.20  2734.40   484.42     0.80   52.84    4.76   98.46   4.17   6.34
sdb            6794.60     0.00 16445.20  540.20 1379517.40 63631.20   169.93    67.19    3.96    4.01    2.34   0.06  99.92
sdc            6816.80     0.80 16379.00  532.60 1377293.80 63286.40   170.37   101.63    6.00    6.10    2.96   0.06  99.82
md0               0.00     0.00 39390.40 1074.00 2756860.60 126918.40   142.53     0.00    0.00    0.00    0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          88.75    0.00    8.65    2.60    0.00    0.00

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     3.80    7.80    1.20   998.40    21.60   226.67     0.00    0.51    0.44    1.00   0.51   0.46
sdb            6128.40     0.40 15120.80  762.60 1263690.00 92049.60   170.71    65.10    4.09    4.19    2.28   0.06  99.64
sdc            6140.60     0.80 15070.40  759.00 1263606.10 92077.60   171.29   102.57    6.47    6.65    3.04   0.06  99.74
md0               0.00     0.00 36108.00 1523.20 2527288.30 184072.00   144.10     0.00    0.00    0.00    0.00   0.00   0.00

avg-cpu:  %user   %nice %system %iowait  %steal   %idle
          89.70    0.00    8.38    1.92    0.00    0.01

Device:         rrqm/s   wrqm/s     r/s     w/s    rkB/s    wkB/s avgrq-sz avgqu-sz   await r_await w_await  svctm  %util
sda               0.00     1.20    8.00    0.60  1024.00     8.00   240.00     0.01    0.63    0.60    1.00   0.60   0.52
sdb            6631.60     0.20 16053.00  560.20 1361785.10 67208.00   172.03    71.24    4.28    4.35    2.39   0.06  99.82
sdc            6648.80     0.00 16021.00  561.80 1364759.00 67152.00   172.70    96.96    5.85    5.95    2.89   0.06  99.70
md0               0.00     0.00 38477.80 1122.00 2726136.10 134338.40   144.47     0.00    0.00    0.00    0.00   0.00   0.00
```
- As you can see read is at ~1300MB / 16000 which is around 80kb
- Read request is at 16,000 while write request is at 500
- Bandwidth for read is 1.3GB while write is 60MB
- Load stress was operating at 10,000 op/s and with repair is around 2,000 op/s

![with-streaming](https://cloud.githubusercontent.com/assets/2642373/13292652/440697cc-db25-11e5-871c-2825b6486afa.png)

![without-streaming](https://cloud.githubusercontent.com/assets/2642373/13292511/b570a5e8-db24-11e5-82cd-3e590343db95.png)

**Comment by glommer** [comment]
Hi @noamha. Please clarify two things for me:

* from which node you took those iostat figures from.
* at which point in time was the node taken down and up again. Since the x axis in the graphs are time-annotated, that will help me correlate.

What I can tell from these graphs in an initial look, is that it seems to me that the streaming class is not properly annotated. Gleb seem to be seeing the same problem with the CQL reads, and they both use the make_reader infrastructure. This is indeed the part I tested the least, and at this point I suspect a bug in there.

**Comment by glommer** [comment]
Also @noamha , can you post the I/O queue configuration for those machines?

**Comment by glommer** [comment]
I stand corrected about my first comment: the streaming class is empty in one of the figures, but it is active in another. It seems to me now that the one of them represents the state of the cluster before the node is stopped, and the other represents the state of the cluster after the node is stopped (around 16:27). If that is the case, that's not the problem.

**Comment by slivne** [comment]
io configuration was 160 requests 40 queues

with regards to the graphs 

the bottom was taken while the clustrer was running with 3 nodes under the same stress and in synch prior to removing files and doing repair

The upper graph has the stop of the node3, removal of files, start of node3, run repair on node3 

with regards to iostat extraction I am not sure on which machine we ran that.

Two general comments:

@nyh  our streaming sends mutations - they go through the commitlog - origin sends files they do not go through the commitlog - should we work around that (even post GA) 

@nyh - I recall vaguley that the first part of computing checksum is not accounted for in any class - is that correct ? @glommer items that do not have a priority class are they automatically associated to a default class or do they bypass the allocation mechanism all together ?

**Comment by slivne** [comment]
I think that  it also explains why streaming is effecting a write workload so much - we are streaming mutations that enter commitlog and memtables we have a new "heavy" consumer of bandwidth added to the same pool that is taking a large part - if we would account for them differently then we could associate them to the streaming class and make sure we are capping  streaming "correctly"

**Comment by glommer** [comment]
If mutations enter the normal commitlog and memtable path, it will be impossible to separate them  in the I/O queue level. One memtable may contain requests that are from repair and CQL at the same time, and it will be impossible for us to differentiate them.

If that is a goal, we will have to change that first somehow

**Comment by nyh** [comment]
On Thu, Feb 25, 2016 at 11:03 AM, slivne <notifications@github.com> wrote:

> @nyh <https://github.com/nyh> our streaming sends mutations - they go
> through the commitlog - origin sends files they do not go through the
> commitlog - should we work around that (even post GA)


Yes, I mentioned this earlier, actually, *reception* of a stream writes
just like normal writes, resulting in commitlog writes and memtable flushes
which are indistinguishable from normal writes.

The question is what harm this can cause -

1. For bootstrap streaming to a new node, as far as I understand the new
node *only* receives the stream, and does not receive ordinary write
requests. So for this case, we're fine - the stream reception cannot
overwhelm anything.

2. For *repair*, the assumption is that usually, we'd expect only small
pieces of the data to be streamed - for ranges which don't match up in
checksum. Did the use case involve a real need for repair? Did you expect
repair to have to send huge parts of the data?

But when the problem does exist, i.e., repair does need to send a lot, and
in the same time the user does write a lot, then indeed the io classes will
not do anything to control the percentage of bandwidth given to each...

> @nyh <https://github.com/nyh> - I recall vaguley that the first part of
> computing checksum is not accounted for in any class - is that correct ?
>
This first part is a read, and it uses the "streaming" io class (we decided
not to add a new "repair" class but to reuse the existing "streaming"
class).

**Comment by glommer** [comment]
On Thu, Feb 25, 2016 at 11:22 AM, nyh <notifications@github.com> wrote:

> On Thu, Feb 25, 2016 at 11:03 AM, slivne <notifications@github.com> wrote:
>
> > @nyh <https://github.com/nyh> our streaming sends mutations - they go
> > through the commitlog - origin sends files they do not go through the
> > commitlog - should we work around that (even post GA)
>
>
> Yes, I mentioned this earlier, actually, *reception* of a stream writes
> just like normal writes, resulting in commitlog writes and memtable flushes
> which are indistinguishable from normal writes.
>
> The question is what harm this can cause -
>
> 1. For bootstrap streaming to a new node, as far as I understand the new
> node *only* receives the stream, and does not receive ordinary write
> requests. So for this case, we're fine - the stream reception cannot
> overwhelm anything.
>
> 2. For *repair*, the assumption is that usually, we'd expect only small
> pieces of the data to be streamed - for ranges which don't match up in
> checksum. Did the use case involve a real need for repair? Did you expect
> repair to have to send huge parts of the data?
>
> But when the problem does exist, i.e., repair does need to send a lot, and
> in the same time the user does write a lot, then indeed the io classes will
> not do anything to control the percentage of bandwidth given to each...
>
> > @nyh <https://github.com/nyh> - I recall vaguley that the first part of
> > computing checksum is not accounted for in any class - is that correct ?
> >
> This first part is a read, and it uses the "streaming" io class (we decided
> not to add a new "repair" class but to reuse the existing "streaming"
> class).
>
>
Well, @noah is deleting all SSTables from a node that has been up for some
10 minutes.
So I definitely expect that to be a lot of data.

**Comment by avikivity** [comment]
We had a little brainstorm about this, and came up with this:

 - instead of streaming into commitlog/memtable, stream into a new writer
 - the new writer distributes to the correct shard, where it is then appended to dedicated sstable, and the cache is updated if needed
 - since we don't write through commitlog, we have to acknowledge the repair/streaming only after the dedicated sstables (on all shards) are closed

This is somewhat similar to C* copying files, but takes sharding into account by streaming mutations and not bytes, and makes sure that cache is still updated (needed for correctness).
