### ISSUE TITLE
Load shedding should respond with an overloaded exception in order not to leak stream ids on the driver

### ISSUE THREAD

**Issue by psarna** [scylladb/scylla#9442]
Our current mechanism of load shedding simply declines to respond on a connection when shedding is enabled. That may be problematic for drivers, which usually reserve stream ids (of which there can only be 16k of unique values) and do not reuse until a response comes. If Scylla never responds, the pool of ids would eventually get depleted (unless the driver simply decides to kill the connection, which is what e.g. Java does).

A simple solution to the problem is to start responding - with an overloaded exception. It's slightly more expensive than doing nothing, but it's more gentle towards the drivers, which is an advantage.

The issue is not particularly critical, because we only enable shedding if a client explicitly specifies their workload type as `interactive` by modifying their service level, but it can nonetheless happen.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
