### ISSUE TITLE
DPDK: Panic in rte_eal_init() Cannot init memory

### ISSUE THREAD

**Issue by chb2mn** [scylladb/scylla#947]
I am using the yum-provided install of scylla 0.18. And when running `systemctl start scylla-server` after trying to set to DPDK mode (for which there is next to no documentation) I get the following dump:

I would really like help on this because running scylla with dpdk seems to be something that many people have done, but nobody has documentation for.

```
 scylla[35891]: EAL: Support maximum 128 logical core(s) by configuration.
  scylla[35891]: EAL: Detected 40 lcore(s)
  scylla[35891]: EAL: No free hugepages reported in hugepages-1048576kB
  scylla[35891]: EAL: VFIO modules not all loaded, skip VFIO support...
  scylla[35891]: EAL: Setting up physically contiguous memory...
  scylla[35891]: EAL: map_all_hugepages(): open failed: Permission denied
  scylla[35891]: EAL: Failed to mmap 2 MB hugepages
  scylla[35891]: PANIC in rte_eal_init():
  scylla[35891]: Cannot init memory
  kernel: type=1701 audit(1456426553.174:786411): auid=4294967295 uid=239 gid=1013 ses=4294967295 sub    j=system_u:system_r:unconfined_service_t:s0 pid=35891 comm="scylla" reason="memory violation" sig=6
  scylla[35891]: 9: [/usr/bin/scylla() [0x4c6571]]
  scylla[35891]: 8: [/lib64/libc.so.6(__libc_start_main+0xf5) [0x7f02eb2efb15]]
  scylla[35891]: 7: [/usr/bin/scylla() [0x47043b]]
  scylla[35891]: 6: [/usr/bin/scylla() [0x56a9bc]]
  scylla[35891]: 5: [/usr/bin/scylla() [0x51751f]]
  scylla[35891]: 4: [/usr/bin/scylla() [0x57190b]]
  scylla[35891]: 3: [/usr/bin/scylla() [0x6bfb9d]]
  scylla[35891]: 2: [/usr/bin/scylla() [0x469f3a]]
  scylla[35891]: 1: [/usr/bin/scylla() [0x6c5b28]]
```

```
[chb2mn@Centos7 ~]$ cat /etc/sysconfig/scylla-server
# choose following mode: virtio, dpdk, posix
NETWORK_MODE=dpdk

# tap device name(virtio)
TAP=tap0

# bridge device name (virtio)
BRIDGE=virbr0

# ethernet device name
IFNAME=$IFNAME

# setup NIC's interrupts, RPS, XPS (posix)
SET_NIC=no

# ethernet device driver (dpdk)
ETHDRV=uio_pci_generic

# ethernet device PCI ID (dpdk)
ETHPCIID=$PCIID

# number of hugepages
NR_HUGEPAGES=64

# user for process (must be root for dpdk)
USER=root

# group for process
GROUP=scylla

# scylla home dir
SCYLLA_HOME=/var/lib/scylla

# scylla config dir
SCYLLA_CONF=/etc/scylla

# scylla arguments (for posix mode)
#SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 --default-log-level info --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack posix"

## scylla arguments (for dpdk mode)
SCYLLA_ARGS="--log-to-syslog 1 --log-to-stdout 0 -m80G --default-log-level debug --collectd-address=127.0.0.1:25826 --collectd=1 --collectd-poll-period 3000 --network-stack native --dpdk-pmd"

# scylla io
SCYLLA_IO=

# setup as AMI instance
AMI=no
```

**Comment by chb2mn** [comment]
the problems seems to be that /usr/bin/scylla is not being run with `sudo` even thought I thought that is what `USER=root` in /etc/sysconfig/scylla-server was supposed to do

**Comment by chb2mn** [comment]
Solution: Systemd in /usr/lib/systemd/system/scylla-server.service resets the $USER field set in /etc/sysconfig/scylla to scylla. I'm still not 100% there on setting up scylla with DPDK, and still retain that there needs to be ~more~ better documentation on setting scylla up with DPDK (although I understand other development needs take priority)

**Comment by avikivity** [comment]
@chb2mn to make good use of DPDK we need to support connection load balancing with Flow Director.  Right now, if your have a small number of clients, you might get unbalanced shards.

**Comment by vladzcloudius** [comment]
@chb2mn There are some issues with our `systemd` scripts at the moment and they are unable to load `scylladb` with DPDK. I've opened an issue for that (issue #951). Meanwhile I've verified that `scylladb` is able to work with DPDK (see my post in the same issue above). Therefore, until we fix our scripts you may load `scylladb` on top of DPDK manually. If you have any questions on "how", please, let me know and I will try to help you.

**Comment by chb2mn** [comment]
@vladzcloudius I read your issue, sorry I haven't gotten back in a few days, were you able to run with DPDK on "ixgbe" drivers? I have scylla "working" from running it from command line, but that was on "igb" drivers on an interface that isn't fast enough. I have faster (ixgbe) interfaces available, but they can't connect and I get `Link Down` when scylla checks the speed of the Interface.

**Comment by chb2mn** [comment]
Wait- just got it to work on that Interface, it's likely a DPDK version incompatibility ( I downloaded 2.2 and installed as opposed to using whatever the kernel was loading)

**Comment by vladzcloudius** [comment]
@chb2mn Yes, I was using ixgbevf interfaces (this is what you get on AWS). Pls., not that I was using a DPDK clone from our github (located in a `seastar` submodule). I suggest using this clone since we have some important patches there that are still missing (the last time I checked) in the main DPDK tree.
