### ISSUE TITLE
nodetool netstats shows incorrect streaming progress info

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#948]
1) Start 3 nodes

2) Insert some data

```
$ cassandra-stress write no-warmup n=100000 -schema 'replication(factor=1)' "keyspace=ks1" -rate threads=10
$ cassandra-stress write no-warmup n=100000 -schema 'replication(factor=1)' "keyspace=ks2" -rate threads=10
```

3) Decommission node 3
nodetool -p 7300 decommission

4) Check nodetool -p 7200 netstats and http api on node2

```
$ nodetool -p 7200 netstats

Mode: NORMAL
Unbootstrap eae51470-dc64-11e5-a25d-000000000000
    /127.0.0.3
        Receiving 1 files, 0 bytes total. Already received 0 files, 0 bytes total
Read Repair Statistics:
Attempted: 10
Mismatch (Blocking): 0
Mismatch (Background): 0
Pool Name                    Active   Pending      Completed
Commands                        n/a         0             94
Responses                       n/a         0              1

$ curl -X GET --silent --header "Accept: application/json" "http://127.0.0.2:10000/stream_manager/";echo

[{"plan_id": "eae51470-dc64-11e5-a25d-000000000000", "description": "Unbootstrap", "sessions": [{"receiving_files": [{"value": {"direction": "IN", "file_name": "rxnofile", "session_index": 0, "total_bytes": 1571736, "peer": "127.0.0.3", "current_bytes": 1571736}, "key": "rxnofile"}], "receiving_summaries": [{"files": 1, "total_size": 0, "cf_id": "d82b8800-dc64-11e5-a25d-000000000000"}], "session_index": 0, "state": "PREPARING", "connecting": "127.0.0.3", "peer": "127.0.0.3"}]}]
```

The http api shows current_bytes (1571736) received, however, nodetool does not show it.

Note,  total_size in "receiving_summaries" is 0. This is expected since we can not know in advance how many bytes the stream_session will send or receive.

**Comment by amnonh** [comment]
@slivne please assign to me

**Comment by amnonh** [comment]
Please note that receiving_summaries in the example 0 for total bytes:

            "receiving_summaries":[  
               {  
                  "files":1,
                  "total_size":0,
                  "cf_id":"d82b8800-dc64-11e5-a25d-000000000000"
               }
            ],

**Comment by asias** [comment]
@amnonh yes, it is zero as I explained in the first comment of this issue. I manually changed this to non-zero number. The nodetool netstats output does not change.
