### ISSUE TITLE
`stopwaitsecs` missing from scylla-server supervisord config

### ISSUE THREAD

**Issue by rzetelskik** [scylladb/scylla#9485]
scylla-server should have a `stopwaitsecs` defined in its supervisord config. Currently no value is set explicitly (https://github.com/scylladb/scylla/blob/master/dist/docker/etc/supervisord.conf.d/scylla-server.conf), resulting in using the default value of 10s. As per supervisord documentation:

```
stopwaitsecs

The number of seconds to wait for the OS to return a SIGCHLD to supervisord after the program has been sent a stopsignal. If this number of seconds elapses before supervisord receives a SIGCHLD from the process, supervisord will attempt to kill it with a final SIGKILL.

Default: 10

Required: No.

Introduced: 3.0
```

To make it concise, `stopwaitsecs` should most likely be set to the same value systemd's `TimeoutStopSec` is https://github.com/scylladb/scylla/blob/4f3b8f38e24b1ca78c356dd4fb70365bb3cdfded/dist/common/systemd/scylla-server.service#L21

This change is necessary to ensure graceful termination when using Scylla Docker image. For more details see https://github.com/scylladb/scylla-operator/issues/805.

**Comment by tnozicka** [comment]
Ideally these 2 settings shouldn't get out of sync. One option is to setup the container image with systemd. I've heard that someone tried in the past and it didn't work. I personally don't see a reason it wouldn't as the container runs its process as `#1` and e.g. [RedHat seems to provide a freely redistributable base image with systemd presetup](https://catalog.redhat.com/software/containers/ubi8/ubi-init/5c359b97d70cc534b3a378c8).

That said, it can be delivered separately as the simple change is more acceptible for the backports.

**Comment by avikivity** [comment]
Backported to 4.4, 4.5. 4.6 had it.
