### ISSUE TITLE
Scans using reversed clustering order should use the same page size limit as forward reads 

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#9487]
Currently, the coordinator sets a higher limit for page size for reversed reads:

```c++
query::max_result_size storage_proxy::get_max_result_size(const query::partition_slice& slice) const {
    // Unpaged and reverse queries.
    // FIXME: some reversed queries are no longer unlimited.
    // To filter these out we need to know if it's a single partition query.
    // Take the partition key range as a parameter? This would require changing many call sites
    // where the partition key range is not immediately available.
    // For now we ignore the issue, return the 'wrong' limit for some reversed queries, and wait until all reversed queries are fixed.
    if (!slice.options.contains<query::partition_slice::option::allow_short_read>() || slice.options.contains<query::partition_slice::option::reversed>()) {
        return _db.local().get_unlimited_query_max_result_size();
    } else {
        return query::max_result_size(query::result_memory_limiter::maximum_result_size);
    }
}
```

The default for `get_unlimited_query_max_result_size()` is 100MB (adjustable through config), whereas `query::result_memory_limiter::maximum_result_size` is 1MB (hard coded, should be enough for everybody)

This limit is then used by the replica to decide when to break pages and, in case of reversed clustering order reads, when to fail the read when accumulated data crosses the threshold. The latter behavior stems from the fact that reversed reads had to accumulate all the data (read in forward order) before they can reverse it and return the result. Reverse reads thus need a higher limit so that they have a higher chance of succeeding.

Most readers are now supporting reading in reverse natively, and only reversing wrappers (make_reversing_reader()) inserted on top of ka/la sstable readers need to accumulate all the data. In other cases, we could break pages sooner. This should lead to better stability (less memory usage) and performance (lower page build latency, higher read concurrency due to less memory footprint).

Implementation-wise, I think we should do the following. We split the limit into "regular" and "unlimited". This adds a new "unlimited" limit to read_command. This "unlimited" query limit will be picked by `make_reversing_reader()` implementation. In addition to that, we introduce a new feature flag to signal that reverse reads are natively supported. When all nodes in the cluster have this feature, coordinators will stop putting "unlimited" limit into the "regular" limit.

The reason to split the limits is that all replicas contacted by coordinator will use the same limits, even during rolling upgrade. This is the same reason why we have the limit decided by the coordinator and put in read_command. This will yield better stability. 

@denesb @kbr- @avikivity @haaawk

**Comment by nyh** [comment]
I have a reproducing test for this issue in the Alternator context, you can run it with
```
test/alternator/run --runveryslow --runxfail test_query.py::test_query_reverse_long
```
The `--runxfail` is needed to show the failure of the test we know to fail, and `--runveryslow` is needed because it's a slow test ("slow" is relative - it takes just a few seconds) so I didn't want it to run by default.

The test fails when it tries to do (with Alternator) a **paged** reverse query on a 100 MB partition, and fails to allocate memory because the default test runner only gives Scylla 1GB of memory. If you edit the test-running code `test/cql-pytest/run.py` and modify `1G` to `3G`,  the query will finally succeeds, but the test fails when it notices that the returned page contains the entire partition (10,000 rows) - which is the bug we're trying to reproduce.

**Comment by nyh** [comment]
I don't want to nag, but please note that this is the only issue remaining before we can declare Alternator's reverse-query feature (#7586) complete and its test will pass.

**Comment by haaawk** [comment]
@tgrabiec @denesb do we want both hard and soft limit for the new unlimited limit?

**Comment by denesb** [comment]
Yes.

**Comment by haaawk** [comment]
One more question. When max_result_size is not sent in the command then I assume it's ok to use the old behaviour that applies old max_memory_for_unlimited_query_*_limit from config, right @tgrabiec @denesb? https://github.com/scylladb/scylla/blob/master/service/storage_proxy.cc#L5107

**Comment by tgrabiec** [comment]
> One more question. When max_result_size is not sent in the command then I assume it's ok to use the old behaviour that applies old max_memory_for_unlimited_query_*_limit from config, right @tgrabiec @denesb? https://github.com/scylladb/scylla/blob/master/service/storage_proxy.cc#L5107

Yes

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
