### ISSUE TITLE
replication_test in debug mode exited with code -9

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9501]
Seen in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4084/artifact/testlog/x86_64_debug/replication_test.521.log

Scylla next version 4271c4edcd8dcee35b3f69622a81fdabbccc6df6
Based on scylla master version 22061831c1d91cd09c0f8fdba06298bb1bfb1893
(but I see no reason 4271c4edcd8dcee35b3f69622a81fdabbccc6df6 (sstables: Fix metric currently_open_for_writing) would be causing this issue)

https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4084/artifact/testlog/x86_64_debug/replication_test.521.log
```
test/raft/replication_test.cc(0): Entering test case "rpc_configuration_truncate_restore_from_log"
Electing first leader 0
Processing updates
=== TEST.PY SUMMARY START ===
Test exited with code -9
```

FWIW, can this be related to EBADF?
```
#define	EBADF		 9	/* Bad file number */
```

/Cc @kostja

**Comment by alecco** [comment]
@bhalevy is this still happening?

**Comment by bhalevy** [comment]
> @bhalevy is this still happening?

No, AFAIK it doesn't reproduce.
Let's close until it is.
