### ISSUE TITLE
Promote too_many_rows events to be first class large_data members

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9506]
As of today (scylla 4.6.dev 7c35d4769), we only report partitions with too many rows on the log but we do not store them in a `system.large_*` table as we do for large partitions/rows/cells.

I think that it was presumed that a partition with too many rows is also likely to be large and therefore it will be recorded in `system.large_partitions`. However, if it contains many *small* rows, it won't.

The log report is also lacking the sstable filename so we can't correlate it with a particular sstable and respectively to compaction events that may shrink the number of rows due to deletions coming from other sstables or ttl expiration.

This issue calls for promoting too_many_rows to be a first-class citizen in the large_* family of badness and keep it in e.g. `system.large_partitions_with_many_rows`.  With that, extend the handling of too_many_rows to be similar to other large_* types.

Refrences:
https://github.com/scylladb/scylla/blob/7c35d476909b7c556f3364bb935beae53cad35d2/db/large_data_handler.hh#L81-L87

https://github.com/scylladb/scylla/blob/7c35d476909b7c556f3364bb935beae53cad35d2/db/large_data_handler.cc#L49-L60

Also, don't forget to delete it in https://github.com/scylladb/scylla/blob/7c35d476909b7c556f3364bb935beae53cad35d2/db/large_data_handler.cc#L180-L190

**Comment by vladzcloudius** [comment]
@bhalevy Thanks for jumping on this.
Do you really think that adding another table is justified? Why not adding a number of rows as an additional column to `system.large_partitions`? 

Not only it would keep things simpler (less tables) but it would also make it easier to use the information because you would have both the number of rows and the size of a partition in the same row which would allow you to reason about the average size of a row.

**Comment by bhalevy** [comment]
> @bhalevy Thanks for jumping on this. Do you really think that adding another table is justified? Why not adding a number of rows as an additional column to `system.large_partitions`?
> 
> Not only it would keep things simpler (less tables) but it would also make it easier to use this information because you would have both the number of rows and the size of a partition in the same `system.large_partitions` row which would allow you to reason about the average size of a row in that partition.

This works well for the single case of too_many_rows, but what if we add other "too many" entities, like too many range_tombstones?  Should we keep adding columns to large_partitions table?
I'm not sure that scaling "horizontally" this way is the right thing to do.

Given the table's schema:
```
CREATE TABLE system.large_partitions (
    keyspace_name text,
    table_name text,
    sstable_name text,
    partition_size bigint,
    partition_key text,
    compaction_time timestamp,
    PRIMARY KEY ((keyspace_name, table_name), sstable_name, partition_size, partition_key)
) WITH CLUSTERING ORDER BY (sstable_name ASC, partition_size DESC, partition_key ASC);
```
We can extend the `partition_key` column to hold the partition_key followed by and indication of the "too many" entity and then store the count in `partition_size`.  For example for a key value of "foo", we can store "foo[rows]".
This way we can have multiple rows associated with the same partition in the sstable indicating both the partition_size, if it's big, number of rows if too many, number of range_tombstones, etc.

**Comment by cmm** [comment]
@vladzcloudius I have some naive questions, if I may.

- what is the normal use case of `system.large_partitions`?  do you go looking in it with a problematic keyspace/table name already in hand (i.e. you know which table is misbehaving on which node), or do you trawl it blindly, looking for large partitions or any other red flags (if the latter, then maybe there should be a general "red flags" system table or something)?
- what are the compatibility constraints here?

**Comment by vladzcloudius** [comment]
> > @bhalevy Thanks for jumping on this. Do you really think that adding another table is justified? Why not adding a number of rows as an additional column to `system.large_partitions`?
> > Not only it would keep things simpler (less tables) but it would also make it easier to use this information because you would have both the number of rows and the size of a partition in the same `system.large_partitions` row which would allow you to reason about the average size of a row in that partition.
> 
> This works well for the single case of too_many_rows, but what if we add other "too many" entities, like too many range_tombstones? Should we keep adding columns to large_partitions table? I'm not sure that scaling "horizontally" this way is the right thing to do.
> 
> Given the table's schema:
> 
> ```
> CREATE TABLE system.large_partitions (
>     keyspace_name text,
>     table_name text,
>     sstable_name text,
>     partition_size bigint,
>     partition_key text,
>     compaction_time timestamp,
>     PRIMARY KEY ((keyspace_name, table_name), sstable_name, partition_size, partition_key)
> ) WITH CLUSTERING ORDER BY (sstable_name ASC, partition_size DESC, partition_key ASC);
> ```
> 
> We can extend the `partition_key` column to hold the partition_key followed by and indication of the "too many" entity and then store the count in `partition_size`. For example for a key value of "foo", we can store "foo[rows]". This way we can have multiple rows associated with the same partition in the sstable indicating both the partition_size, if it's big, number of rows if too many, number of range_tombstones, etc.

@bhalevy Scylla/Cassandra data model natively supports adding more columns and tables in question have a LONG way to go before the number of columns would begin being any kind of an issue.

Scylla works with tables of multiple 10s of columns at our customers without any glitch.

Scylla/Cassandra natively support filtering the output by selecting only the columns that are needed.

On the other hand Scylla/Cassadnra unlike SQL *does not* support joins. Therefore selecting all the data for a given partition is going to become a matter of post processing and having to sent multiple queries - which is way much more complicated than needed.

As a note: the direction of adding a table every time you are going to add another large_xx statistics is going to amplify disk usage because you are going to duplicate the PK part. This feels especially wrong considering the fact that you want to see all `large_xxx` data for the relevant partition most of the time (I haven't filtered columns when I read from those tables even once).

**Comment by vladzcloudius** [comment]
> @vladzcloudius I have some naive questions, if I may.
> 
>     * what is the normal use case of `system.large_partitions`?  do you go looking in it with a problematic keyspace/table name already in hand (i.e. you know which table is misbehaving on which node), or do you trawl it blindly, looking for large partitions or any other red flags (if the latter, then maybe there should be a general "red flags" system table or something)?

@cmm 

It's mostly the later. I can't remember any occasion when we/customer would do anything but `"select * from system.large_xxx`.

That's exactly the reason why I don't want to have multiple tables having the information about the same item (partition in this case). 
I want to fetch the data once and if there is something - I want to have it all right away and not have to post process it: e.g. I don't want to have to start matching partitions with many rows and partitions with many bytes - I want to have it all in the same line right away.

> 
>     * what are the compatibility constraints here?

There are no compatibility constraints here at all as far as I'm aware of. There are not tools that reply on a specific layout of those tables (again - AFAIK).

**Comment by tarzanek** [comment]
just a side note - cardinality of the partition might get too high
so you might end up with lots of rows with PK of just (keyspace_name, table_name)
would it make sense to add sstable_name to PK ?

**Comment by vladzcloudius** [comment]
> just a side note - cardinality of the partition might get too high so you might end up with lots of rows with PK of just (keyspace_name, table_name) would it make sense to add sstable_name to PK ?

That's a valid point.
And all it takes is to set a threshold low enough (e.g. by mistake) to have all partitions of a given table logged.
And then BUM! - all corresponding rows in `system.large_partitions` are going to end up in the same partition. 

@bhalevy That's definitely something to take a look at.

**Comment by cmm** [comment]
at least system tables don't report on themselves, because that would be awkward

**Comment by vladzcloudius** [comment]
> at least system tables don't report on themselves, because that would be awkward

Are you sure, @cmm? :D

**Comment by cmm** [comment]
@vladzcloudius I definitely see the code that makes sure that system tables have dummy "large data" handling (dating to March 2019), but beyond that I cannot really say!

**Comment by bhalevy** [comment]
Yes, there were a number of fixes in this area to make sure we use the nop large data handler for system tables

**Comment by bhalevy** [comment]
Regarding adding more columns, I'm not worried about supporting that in the cql path, but rather in the need to change the schema of the system table.
Maybe a good compromise would be to add a new "too many" column which is a map holding `<entity, count>` tuples, so we can use it to count various entities in the partition.

**Comment by bhalevy** [comment]
> just a side note - cardinality of the partition might get too high so you might end up with lots of rows with PK of just (keyspace_name, table_name) would it make sense to add sstable_name to PK ?

Sounds like a good idea.
It would also be more efficient to delete the whole partition when the sstable is deleted (by compaction) turning range deletion onto partition deletion.

**Comment by bhalevy** [comment]
@tarzanek can you please open an issue about the carfinality problem?

**Comment by vladzcloudius** [comment]
> Regarding adding more columns, I'm not worried about supporting that in the cql path, but rather in the need to change the schema of the system table. Maybe a good compromise would be to add a new "too many" column which is a map holding `<entity, count>` tuples, so we can use it to count various entities in the partition.

@bhalevy Any direction, both adding a new column to an existing system table and using a composite column are rather trivial to implement and maintain - but this discussion is not about a technical part of of the implementation (I'm sure you'll be able to handle any of this). - It's about a user interface and having a separate column is a more user friendly option because it's much easier to work with both compared to a new table and compared to a composite column.

**Comment by cmm** [comment]
maybe just define a "problem" ("entity"?) column (included in ck), change the "partition_size" or whatever column to be generic "count", and just add rows for every found threshold violation -- this way you just need one table and it's simple to query and self-explanatory.

and expand the pk to include the sstable name and maybe even the offending partition key (could it happen that a threshold-violating cf is all in one sstable and all or most of its partitions are problematic?  doesn't seem impossible)

**Comment by avikivity** [comment]
> > @bhalevy Thanks for jumping on this. Do you really think that adding another table is justified? Why not adding a number of rows as an additional column to `system.large_partitions`?
> > Not only it would keep things simpler (less tables) but it would also make it easier to use this information because you would have both the number of rows and the size of a partition in the same `system.large_partitions` row which would allow you to reason about the average size of a row in that partition.
> 
> This works well for the single case of too_many_rows, but what if we add other "too many" entities, like too many range_tombstones? Should we keep adding columns to large_partitions table? I'm not sure that scaling "horizontally" this way is the right thing to do.
> 
> Given the table's schema:
> 
> ```
> CREATE TABLE system.large_partitions (
>     keyspace_name text,
>     table_name text,
>     sstable_name text,
>     partition_size bigint,
>     partition_key text,
>     compaction_time timestamp,
>     PRIMARY KEY ((keyspace_name, table_name), sstable_name, partition_size, partition_key)
> ) WITH CLUSTERING ORDER BY (sstable_name ASC, partition_size DESC, partition_key ASC);
> ```
> 
> We can extend the `partition_key` column to hold the partition_key followed by and indication of the "too many" entity and then store the count in `partition_size`. For example for a key value of "foo", we can store "foo[rows]". This way we can have multiple rows associated with the same partition in the sstable indicating both the partition_size, if it's big, number of rows if too many, number of range_tombstones, etc.

We can add a row_count column and store both partition_size and row_count if one of them exceeds the threshold.

**Comment by vladzcloudius** [comment]
> > > @bhalevy Thanks for jumping on this. Do you really think that adding another table is justified? Why not adding a number of rows as an additional column to `system.large_partitions`?
> > > Not only it would keep things simpler (less tables) but it would also make it easier to use this information because you would have both the number of rows and the size of a partition in the same `system.large_partitions` row which would allow you to reason about the average size of a row in that partition.
> > 
> > 
> > This works well for the single case of too_many_rows, but what if we add other "too many" entities, like too many range_tombstones? Should we keep adding columns to large_partitions table? I'm not sure that scaling "horizontally" this way is the right thing to do.
> > Given the table's schema:
> > ```
> > CREATE TABLE system.large_partitions (
> >     keyspace_name text,
> >     table_name text,
> >     sstable_name text,
> >     partition_size bigint,
> >     partition_key text,
> >     compaction_time timestamp,
> >     PRIMARY KEY ((keyspace_name, table_name), sstable_name, partition_size, partition_key)
> > ) WITH CLUSTERING ORDER BY (sstable_name ASC, partition_size DESC, partition_key ASC);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > We can extend the `partition_key` column to hold the partition_key followed by and indication of the "too many" entity and then store the count in `partition_size`. For example for a key value of "foo", we can store "foo[rows]". This way we can have multiple rows associated with the same partition in the sstable indicating both the partition_size, if it's big, number of rows if too many, number of range_tombstones, etc.
> 
> We can add a row_count column and store both partition_size and row_count if one of them exceeds the threshold.

That's exactly what I asked here: https://github.com/scylladb/scylla/issues/9506#issuecomment-956527083
Your version is both shorter and simpler to understand however.
Thanks, @avikivity.
