### ISSUE TITLE
TWCS: expired sstables are not evicted long after they have expired when system is under a heavy load

### ISSUE THREAD

**Issue by vladzcloudius** [scylladb/scylla#9533]
*Installation details*
Scylla version: a21b1fbb2f481671c80560d96a8acc1cf916b468
Cluster size: 1

*Description*
If system is under a heavy load, in particular such that creates a lot of compaction work, it may take a very long time for completely expired sstable to get evicted.

![image](https://user-images.githubusercontent.com/6103981/139176695-4ea1fd13-d818-48a0-bc63-d3534ee5d349.png)

schema:
```
cqlsh> DESC keyspace1.standard1

CREATE TABLE keyspace1.standard1 (
    key blob PRIMARY KEY,
    "C0" blob,
    "C1" blob,
    "C2" blob,
    "C3" blob,
    "C4" blob
) WITH bloom_filter_fp_chance = 0.01
    AND caching = {'keys': 'ALL', 'rows_per_partition': 'ALL'}
    AND comment = ''
    AND compaction = {'class': 'TimeWindowCompactionStrategy', 'compaction_window_size': '1', 'compaction_window_unit': 'MINUTES', 'expired_sstable_check_frequency_seconds': '30'}
    AND compression = {}
    AND crc_check_chance = 1.0
    AND dclocal_read_repair_chance = 0.0
    AND default_time_to_live = 300
    AND gc_grace_seconds = 0
    AND max_index_interval = 2048
    AND memtable_flush_period_in_ms = 0
    AND min_index_interval = 128
    AND read_repair_chance = 0.0
    AND speculative_retry = '99.0PERCENTILE';
```

How to reproduce:

* Provision a single shard single node scylla and allocate 1GB or ram using --memory 1G parameter.
* Run cassandra-stress:

```
cassandra-stress write n=1000000000 no-warmup -rate threads=300  -mode native cql3 -pop seq=1..1000000000
```

* Wait for five minutes and start observing how completely expired sstables are not evicted from disk (as on the screenshot above).

* Stop c-s stress and see how those expired sstable get evicted virtually immediately.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
