### ISSUE TITLE
scrub/validate compaction should run in maintenance scheduling group

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9537]
We need to have a back-pressure mechanism so that scrub will slow down as it produces output sstables (that could be in the thousands) while compaction shares should increase based on the backlog controller.

Cc @raphaelsc

**Comment by denesb** [comment]
@bhalevy should we close this issue? Looking at the title I think we should (we have what it asks for). The description however talks about a "backpressure mechanism" which I'm not sure exists as described there:
1) compaction doesn't learn about the scrub-produced sstables when they are produced, it only learns about them *after* scrubbing the input sstable is finished;
2) point (1) means that compaction shares are not adjusted and therefore there is no backpressure currently;

**Comment by bhalevy** [comment]
> @bhalevy should we close this issue? Looking at the title I think we should (we have what it asks for).

Yes, we can.

> The description however talks about a "backpressure mechanism" which I'm not sure exists as described there:
> 
> 1. compaction doesn't learn about the scrub-produced sstables when they are produced, it only learns about them _after_ scrubbing the input sstable is finished;
> 2. point (1) means that compaction shares are not adjusted and therefore there is no backpressure currently;

Let's open a new issue about that.
I think that scrub needs to run with compaction disabled only briefly, for selecting the sstables to scrub.
At this point, they should be registered using `compaction_manager::register_compacting_sstables` and then they will be fenced off from regular compaction while they are scrubbed.

With that, we should be able to reenable regular compaction during scrub, meaning new sstables, either from memtable flush or those which are created by scrub can be compacted using regular compaction.

This will require a change in scrub compaction though to add the output sstables as they are sealed rather than wait until scrub finished compacting the input sstable(s).

**Comment by denesb** [comment]
Opened https://github.com/scylladb/scylla/issues/9562 for the backpressure issue, closing this.
