### ISSUE TITLE
pre-release image tags are not semantic versions

### ISSUE THREAD

**Issue by tnozicka** [scylladb/scylla#9543]
We are not using semantic versioning for our pre-releases, like `4.5.rc.6`. The correct semantic version would be `4.5.0-rc.6`. This breaks the conventions and scylla-operator trying to parse the scylla version from the tag.

Stems from https://github.com/scylladb/scylla-operator/issues/180

cc @slivne

**Comment by slivne** [comment]
@yaronkaikov - I am ok to check if we can publish rcs on dockerhub with this change

**Comment by yaronkaikov** [comment]
@slivne Do we want to do this change all over or only to our docker images?  what about official release? should it stay as is or we should add another digit (for example: 4.5.1 vs 4.5.1.0)

**Comment by slivne** [comment]
@avikivity - I do not think we should change things outside of docker, please provide your view

**Comment by avikivity** [comment]
We should have just one convention.

deb/rpm conventions favor ~ for denoting release candidates. We can choose one of

4.5.0~rc0 .. 4.5.0~rc1 .. 4.5.0

or

4.5~rc0 .. 4.5~rc1 .. 4.5.0


The first choice allows us to have release candidates for patch releases too. The second choice is more in line with existing practice. Both should sort correctly according to rpm/deb conventions.

**Comment by yaronkaikov** [comment]
@avikivity i think we should go with the first option `4.5.0~rc0` . Then we can remove all tweaks we are doing in case we have `rc` release

**Comment by vponomaryov** [comment]
This bug blocks testing of the Scylla release candidates on operator.
Affected all the tests which depend on the Scylla pod rollout mechanism, it just doesn't happen due to this bug.

**Comment by avikivity** [comment]
@yaronkaikov please prioritize

**Comment by vponomaryov** [comment]
![2022_07_04--scylla-non-semver-image-tags](https://user-images.githubusercontent.com/3796058/177109108-a1c6387c-551d-4000-b997-f1cf3764b725.png)

**Comment by yaronkaikov** [comment]
@DoronArazii This will be part of 5.1 and not 5.0 since it's already out 
@vponomaryov FYI, this is not backported to 5.0 and it's not needed since it's officially released

**Comment by vponomaryov** [comment]
> @DoronArazii This will be part of 5.1 and not 5.0 since it's already out @vponomaryov FYI, this is not backported to 5.0 and it's not needed since it's officially released

Actually, we need all the tags be semver-like not only `pre-release` ones. We are going to run not only pre-release Scylla versions using scylla-operator.
So, it means that even `scylla-nightly` must comply with the semver approach.
