### ISSUE TITLE
master: core during backup

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla#9544]
*Installation details*
Scylla version (or git commit hash): 4.6.dev-0.20211020.7c35d4769 with build-id d68c5ffd74a881391b779a1fed1b662bcc0af6c3
Cluster size: 4
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0274c0b59406f2141

Platform (physical/VM/cloud instance type/docker): AWS
Disks: 3 nvme

db-logs: https://cloudius-jenkins-test.s3.amazonaws.com/f178c1cd-07ad-43cb-a337-880dabed634a/20211024_074603/db-cluster-f178c1cd.tar.gz
job: url: https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-200gb-48h/145/
core: http://upload.scylladb.com/core.scylla.113.04f97e5360c74e9e8a36338ebefc011f.11795.1634897392000000000000/core.scylla.113.04f97e5360c74e9e8a36338ebefc011f.11795.1634897392000000000000.gz

Core time: `2021-10-22 10:13:53.859` 
Nemesis logs:

```
< t:2021-10-22 04:42:26,304 f:nemesis.py      l:1084 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method nodetool_cleanup
< t:2021-10-22 04:58:02,414 f:nemesis.py      l:1094 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method nodetool_cleanup
< t:2021-10-22 05:28:02,415 f:nemesis.py      l:1084 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method stop_start_scylla_server
< t:2021-10-22 05:31:44,357 f:nemesis.py      l:1094 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method stop_start_scylla_server
< t:2021-10-22 06:01:44,364 f:nemesis.py      l:1084 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method disable_enable_ldap_authorization
< t:2021-10-22 06:02:48,401 f:nemesis.py      l:1094 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method disable_enable_ldap_authorization
< t:2021-10-22 06:32:48,402 f:nemesis.py      l:1084 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method mgmt_backup
< t:2021-10-22 21:34:25,819 f:nemesis.py      l:1094 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method mgmt_backup
< t:2021-10-22 22:04:25,832 f:nemesis.py      l:1084 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method ldap_connection_toggle
< t:2021-10-22 22:05:26,743 f:nemesis.py      l:1094 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method ldap_connection_toggle
< t:2021-10-22 22:35:26,750 f:nemesis.py      l:1084 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method truncate
< t:2021-10-22 22:38:25,150 f:nemesis.py      l:1094 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method truncate
< t:2021-10-22 23:08:25,182 f:nemesis.py      l:1084 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method hard_reboot_node
< t:2021-10-22 23:14:29,350 f:nemesis.py      l:1094 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method hard_reboot_node
< t:2021-10-22 23:44:29,352 f:nemesis.py      l:1084 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method mgmt_backup
< t:2021-10-23 14:45:56,529 f:nemesis.py      l:1094 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method mgmt_backup
< t:2021-10-23 15:15:56,536 f:nemesis.py      l:1084 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: >>>>>>>>>>>>>Started random_disrupt_method mgmt_backup
< t:2021-10-24 06:17:05,035 f:nemesis.py      l:1094 c:sdcm.nemesis         p:INFO  > sdcm.nemesis.LimitedChaosMonkey: <<<<<<<<<<<<<Finished random_disrupt_method mgmt_backup
```

**Comment by fgelcer** [comment]
most likely dup of #9192

**Comment by slivne** [comment]
@bhalevy / @tgrabiec please note in both cases this was recorded there was a manager backup - manager backup - takes a snapshot (that enforces a flush) - and creates hard links - and I expect some compactions and after that "steals" bandwidth for reading the files and uploading them.

So maybe this can help in some manner

**Comment by enaydanov** [comment]
Got repro


**Installation details**

Kernel version: `5.4.0-1035-aws`
Scylla version (or git commit hash): `4.7.dev-0.20211121.f3d5b2b2b with build-id d19eea51f4dfd0928fdacf8044f771ad30413e12`
Cluster size: 4 nodes (i3.4xlarge)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-059d6e0d0e34d037a` (aws: eu-north-1)

Test: `longevity-200gb-48h`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/d1ae0d0636d6781d168fc6fc1a6932f0638c3827/test-cases/longevity/longevity-200GB-48h-verifier-LimitedMonkey-tls.yaml)

Restore Monitor Stack command: `$ hydra investigate show-monitor 96d8965a-dbd5-4e65-ad8a-ad4cc48aa956`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=96d8965a-dbd5-4e65-ad8a-ad4cc48aa956)
Show all stored logs command: `$ hydra investigate show-logs 96d8965a-dbd5-4e65-ad8a-ad4cc48aa956`

Test id: `96d8965a-dbd5-4e65-ad8a-ad4cc48aa956`

**Logs:**

grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/96d8965a-dbd5-4e65-ad8a-ad4cc48aa956/20211127_122908/grafana-screenshot-longevity-200gb-48h-scylla-per-server-metrics-nemesis-20211127_123202-longevity-200gb-48h-verify-limited--monitor-node-96d8965a-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/96d8965a-dbd5-4e65-ad8a-ad4cc48aa956/20211127_122908/grafana-screenshot-longevity-200gb-48h-scylla-per-server-metrics-nemesis-20211127_123202-longevity-200gb-48h-verify-limited--monitor-node-96d8965a-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/96d8965a-dbd5-4e65-ad8a-ad4cc48aa956/20211127_122908/grafana-screenshot-overview-20211127_122908-longevity-200gb-48h-verify-limited--monitor-node-96d8965a-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/96d8965a-dbd5-4e65-ad8a-ad4cc48aa956/20211127_122908/grafana-screenshot-overview-20211127_122908-longevity-200gb-48h-verify-limited--monitor-node-96d8965a-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/96d8965a-dbd5-4e65-ad8a-ad4cc48aa956/20211127_154719/db-cluster-96d8965a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/96d8965a-dbd5-4e65-ad8a-ad4cc48aa956/20211127_154719/db-cluster-96d8965a.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/96d8965a-dbd5-4e65-ad8a-ad4cc48aa956/20211127_154719/loader-set-96d8965a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/96d8965a-dbd5-4e65-ad8a-ad4cc48aa956/20211127_154719/loader-set-96d8965a.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/96d8965a-dbd5-4e65-ad8a-ad4cc48aa956/20211127_154719/monitor-set-96d8965a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/96d8965a-dbd5-4e65-ad8a-ad4cc48aa956/20211127_154719/monitor-set-96d8965a.tar.gz)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/96d8965a-dbd5-4e65-ad8a-ad4cc48aa956/20211127_154719/sct-runner-96d8965a.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/96d8965a-dbd5-4e65-ad8a-ad4cc48aa956/20211127_154719/sct-runner-96d8965a.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-200gb-48h/151/)

**Comment by tgrabiec** [comment]
The crash is in the same place. This version includes the extra sanity checks: bf6898a5a009261574e30ef22f70e26e7c2961ae and 4d627affc33b6b384315dadf21ee2800cc52fca6

@enaydanov Do you have the core?

**Comment by enaydanov** [comment]
Sure, it's here: gs://upload.scylladb.com/core.scylla.113.b01eff426209425db3d340d7920593c2.13767.1637846515000000000000/core.scylla.113.b01eff426209425db3d340d7920593c2.13767.1637846515000000000000.gz

**Comment by bhalevy** [comment]
> The crash is in the same place. This version includes the extra sanity checks: [bf6898a](https://github.com/scylladb/scylla/commit/bf6898a5a009261574e30ef22f70e26e7c2961ae) and [4d627af](https://github.com/scylladb/scylla/commit/4d627affc33b6b384315dadf21ee2800cc52fca6)
> 
> @enaydanov Do you have the core?

@tgrabiec: yes, f3d5b2b2b includes bf6898a5a009261574e30ef22f70e26e7c2961ae and 4d627affc33b6b384315dadf21ee2800cc52fca6

**Comment by bhalevy** [comment]
@tgrabiec any updates on the core analysis?

**Comment by tgrabiec** [comment]
Looks similar to previous ones.

The segment is not linked in _segment_descs. There are 23 lsa_buffers in the segment. All looks consistent, they point to the owning descriptor. Free space in the segment is 32KB, matches expected occupancy.

Cached bucket is 109, which is not corresponding to empty segments (this is new evidence).

free space in _closed_occupancy at the entry of free_buf() matches the sum of free space in all segments linked in _segment_descs. Same about total space.

**Comment by slivne** [comment]
@tgrabiec so did the asserts that we added help ?

If not what can we do next to catch this.

**Comment by tgrabiec** [comment]
@slivne No, the asserts did not catch anything. I'm coming up with new ideas.

**Comment by avikivity** [comment]
Already backported.
