### ISSUE TITLE
`future<> raft::server_impl::add_entry_internal(T, raft::wait_type) [T = bytes_ostream]: Assertion 'inserted' failed`

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#9549]
When adding a new entry to its log, a Raft server creates a promise-future pair. It returns the future to the client who caused the entry to be added (i.e. the caller of `add_entry` or `set_configuration`) and stores the promise in a container, either `_awaited_commits` or `_awaited_applies`. When the entry is committed or applied, the promise is extracted from the container and `set_value()` is called. This is called "notifying waiters".

This is the definition of `_awaited_commits` and `_awaited_applies`:
```cpp
    struct op_status {
        term_t term; // term the entry was added with
        promise<> done; // notify when done here
    };

    // Entries that have a waiter that needs to be notified when the
    // respective entry is known to be committed.
    std::map<index_t, op_status> _awaited_commits;

    // Entries that have a waiter that needs to be notified after
    // the respective entry is applied.
    std::map<index_t, op_status> _awaited_applies;
```

This is the code that adds an entry and stores the promise:
```cpp
future<> server_impl::add_entry_internal(T command, wait_type type) {
    logger.trace("An entry is submitted on a leader");

    // Wait for a new slot to become available
    co_await _fsm->wait_max_log_size();

    logger.trace("An entry proceeds after wait");

    const log_entry& e = _fsm->add_entry(std::move(command));

    auto& container = type == wait_type::committed ? _awaited_commits : _awaited_applies;

    // This will track the commit/apply status of the entry
    auto [it, inserted] = container.emplace(e.idx, op_status{e.term, promise<>()});
    assert(inserted);
```

so we see that when an entry `e` is added, we place the promise under the key `e.idx`, the entry's index.
We assume that no waiter existed at this index before (`assert(inserted)`). But it can sometimes happen that an entry on a given index is dropped and replaced with an entry with a higher term, in presence of leader changes and reconfigurations. There are some places in the code where entries are removed from these containers for such scenarios, by calling the `drop_waiters()` function. But not everything is covered.

Example scenario that causes the assertion to fail:
- servers {A, B, C}, A is the leader, logs are in sync, say the last index is `10`
- A appends log entries with indexes `11`, `12`, creating promises in `_awaited_commits` at indexes `11`, `12`
- B becomes a leader after getting a vote from C (both their logs are of length `10`)
- B appends an entry with index `11`
- A receives `11` the entry from B, which causes its log to first be truncated to `10`, then the new entry at `11` is appended (but the old waiters at `11` and `12` are still there)
- A becomes a leader
- A appends a new entry at `12` and tries to insert a promise to `_awaited_commits`, hitting the assertion failure

We should probably remove waiters appropriately when truncating the log to prevent this. But it's not clear how to do that, since truncating the log happens in `raft::fsm` when it receives an append_entries message, while waiters are managed by `raft::server_impl`; the code which inserts new waiters (`add_entry_internal`) is not synchronized with the code which receives and append_entry message (`fsm::append_entries`).
Or we could simply assume that waiters may be replaced (e.g. use `insert_or_assign` instead of `emplace` in `add_entry_internal`).

**Comment by kostja** [comment]
Closing as this series is merged.
