### ISSUE TITLE
Docker example: does not support protocol version V4 but V3

### ISSUE THREAD

**Issue by FGRibreau** [scylladb/scylla#955]
Hello!

I wanted to try scylla using docker, instead of

```bash
docker pull scylladb/scylla:0.17
docker run -p $(hostname -i):9042:9042 -i -t scylladb/scylla
./tools/bin/cassandra-stress write -mode cql3 native
```

I used:

```bash
docker pull scylladb/scylla:0.17
docker run -p $(hostname -i):9042:9042 -i -t --name=scylla scylladb/scylla
# in another terminal
docker run -it --link scylla --rm cassandra bash
cassandra-stress write -mode cql3 native -node 172.17.0.2
```

but even if the node is available I got this exception from cassandra-stress:

```
java.lang.RuntimeException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /172.17.0.2:9042 (com.datastax.driver.core.UnsupportedProtocolVersionException: [/172.17.0.2:9042] Host /172.17.0.2:9042 does not support protocol version V4 but V3))
```

I tried another version of cassandra (v2.x) but still the same issue, what am I doing wrong?

**Comment by slivne** [comment]
Hi Francois

Please install scylla-tools - it provides a cassandra-stress that is ONLY
using cql3 to with CQL binary v3.

Cassandra 2.X cassandra-stress all use thrift to create the default tables
(the fact that you specified -mode cql3 is used only in the data population
not in creating the schema).

Shlomi

**Comment by penberg** [comment]
If there's no package to install (e.g. you're on OS X), you can build it yourself from:

https://github.com/scylladb/scylla-tools-java

Just run ``ant jar`` and `` ./tools/bin/cassandra-stress`` will work.

**Comment by FGRibreau** [comment]
@slivne Ok, I simply followed the getting started guide and it used `-mode sql3` http://www.scylladb.com/doc/getting-started/

Ok, so I was finally able to run tests http://blog.fgribreau.com/2016/02/give-try-and-bench-scylladb-cassandra.html

thanks!

**Comment by penberg** [comment]
@FGRibreau, awesome! Please remember that the Docker image is not optimized so performance isn't all that great. That's because Scylla needs a filesystem that supports AIO/DIO properly and the only one to do that is XFS at the moment.

**Comment by FGRibreau** [comment]
@penberg yes, I specified the docker performance issue in the blog post but I will add your AIO/DIO comment :)

**Comment by penberg** [comment]
@FGRibreau I have not tried it myself but Docker's ``VOLUME`` should allow by-passing the copy-on-write storage layer and point Scylla directly to a XFS-formatted filesystem. You'll pay some performance penalty from Docker's NAT networking but insanely much.
