### ISSUE TITLE
I can't install Scylla on debian and Ubuntu (master)

### ISSUE THREAD

**Issue by hagitsegev** [scylladb/scylla#9563]
Installing from
http://downloads.scylladb.com/unstable/scylla/master/deb/unified/2021-11-01T01:01:32Z/scylladb-master/
On all supported debian OSes: Ubuntu 16.04, 18.04, 20.04, Debian 9,10.

Error:
STEP 11: RUN apt-get -o Acquire::Retries=3 update -y -qq
--> bfa169f568f
STEP 12: RUN DEBIAN_FRONTEND=noninteractive apt-get install $SCYLLA_PRODUCT_NAME -y -qq
E: Unable to correct problems, you have held broken packages.

You can see the full log on https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/unified-deb/690/artifact/x86_installation_logs/

Installation from yesterday's artifact: http://downloads.scylladb.com/unstable/scylla/master/deb/unified/2021-10-31T01:01:02Z/scylladb-master/ is OK.

**Comment by yaronkaikov** [comment]
when trying to install locally we get
```
root@dc40eab92bbd:/#  curl -o /etc/apt/sources.list.d/scylla.list -L http://downloads.scylladb.com/unstable/scylla/master/deb/unified/2021-10-31T01:01:02Z/scylladb-master/scylla.list
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   137  100   137    0     0    276      0 --:--:-- --:--:-- --:--:--   276
root@dc40eab92bbd:/# apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease             
Hit:3 http://archive.ubuntu.com/ubuntu focal-backports InRelease           
Hit:4 http://security.ubuntu.com/ubuntu focal-security InRelease
Get:5 http://downloads.scylladb.com/unstable/scylla/master/deb/unified/2021-10-31T01:01:02Z/scylladb-master stable InRelease [7204 B]
Get:6 http://downloads.scylladb.com/unstable/scylla/master/deb/unified/2021-10-31T01:01:02Z/scylladb-master stable/main arm64 Packages [3820 B]
Get:7 http://downloads.scylladb.com/unstable/scylla/master/deb/unified/2021-10-31T01:01:02Z/scylladb-master stable/main amd64 Packages [3842 B]
Fetched 14.9 kB in 1s (13.1 kB/s)   
Reading package lists... Done
root@dc40eab92bbd:/# apt-get install scylla
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 scylla : Depends: scylla-jmx (= 4.6.dev-0.20211031.c9499230c-1) but 4.6.dev-0.20211101.c9499230c-1 is to be installed
          Depends: scylla-tools (= 4.6.dev-0.20211031.c9499230c-1) but 4.6.dev-0.20211101.c9499230c-1 is to be installed
          Depends: scylla-tools-core (= 4.6.dev-0.20211031.c9499230c-1) but 4.6.dev-0.20211101.c9499230c-1 is to be installed
E: Unable to correct problems, you have held broken packages.
root@dc40eab92bbd:/# 
```

**Comment by hagitsegev** [comment]
I removed the -qq from the installation tests, so we will have a log similar to what Yaron added above. 
https://github.com/scylladb/scylla-pkg/pull/2480

**Comment by avikivity** [comment]
It looks like we had a build around midnight and some of the packages got named 20211101 and some 0.20211031.

**Comment by slivne** [comment]
I think it happens more then once ...

The issue is that we are building twice once for ARM and once for x86 and
because of that we endup with two instances of tools and jmx and then
upload them both.

If the build crosses a date boundary we will have the issue with duplicate
artifacts.

Usually its not an issue - I found other cases like this - hacing said that
in this case it was

We can try and drop the duplicates yet I found the complete versions
embedded in the dependencies in the repo Packages file for some reason - I
am not sure when this dependency is computed and how.

I'll try to look a bit more

**Comment by hagitsegev** [comment]
The good news is that the next run (based on build 802) didn't have this problem, and installation went OK.

master/daily is set to start on 12:55 AM.
https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/build/801/ that created the packages started on 12:58 AM.
It is after midnight.
I think that the issue comes from the end of DST (moving to "winter clock") that happened around this time in EU.
https://www.timeanddate.com/news/time/europe-dst-end-2021.html

Connected to https://github.com/scylladb/scylla-pkg/issues/2481

**Comment by avikivity** [comment]
We should create the build timestamp once and propagate it to all subpackages.

**Comment by hagitsegev** [comment]
So it means to run ninja just to create the timestamp, and after that call it again (on ARM and X86) with the values that was created?
Clock moves happen twice a year, and cause issues to computers, that assume the time is moving forward consecutively.

**Comment by hagitsegev** [comment]
Happened again on 
https://jenkins.scylladb.com/view/nexts/job/scylla-master/job/build/808/artifact/00-Build.txt/*view*/
I can suspect that maybe there is a time difference between the machines armatrading and FleetCloud-next i-0c9ac51482a567761
The build starts on 00:58. So if one of the machines is an hour late, we can' get this issue.
As a "fast - solution - that puts things under the rug" I can set the build to start a bit later.

**Comment by avikivity** [comment]
Why would a machine be late?

Let's make sure we are using UTC for time.

**Comment by hagitsegev** [comment]
As it happened again, I re-open the issue.

**Comment by avikivity** [comment]
Note the workaround I queued.
