### ISSUE TITLE
Bloom filter memory consumption can be increased with segregation on memtable flush

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#9581]
With segregation on flush, partition estimation for each new sstable may be inaccurate, unnecessarily increasing memory consumption for bloom filter. Only TWCS tables are affected. Note though that this is a transient problem as regular compactions will eventually adjust estimation, taking segregation into account.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
