### ISSUE TITLE
db/schema_tables: merge_tables_and_views(): views are always matched against new/after base tables

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#9586]
HEAD: 4950ce539c06be61ff31f0c46602850ac7a60826

For altered tables, `merge_tables_and_views()` creates schema objects representing before/after (old/new) table states. In case of views, there is a matching mechanism to set the base table field of the view to the appropriate base table object. This works by iterating over the list of altered tables and selecting the "new_schema" field of the first instance matching the keyspace/name of the base-table. This ends up pairing the after/old version of the base table to both the before and after version of the view. This means the base attached to the view is possibly incompatible with the view it is attached to.

Relevant code:
https://github.com/scylladb/scylla/blob/4950ce539c06be61ff31f0c46602850ac7a60826/db/schema_tables.cc#L1226-L1231

I discovered this after making changes to `global_schema_ptr` (used in the schema_diff structure), which called `base_schema()` in the global schema ptr constructor, uncovering the mismatching view-table pair. I don't know how this didn't cause any problems before, I guess the schema objects created here are discarded after the change is announced
and the announcing triggers the creation of different schema objects which are matched up correctly.

**Comment by avikivity** [comment]
@denesb should we backport this, or is it only an internal inconsistency?

**Comment by denesb** [comment]
This was a landmine that no one stepped into yet. As older branches won't see active development anyway, it is not likely anyone will step into it on them. In other, non-mine related words, I don't think this is worth backporting.
