### ISSUE TITLE
docker: scylla_bashrc does not apply on login prompt

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#9588]
Seems like /etc/bashrc filename is different in Ubuntu.
We currently doing `run bash -ec "cat /scylla_bashrc >> /etc/bashrc"` while building container, I'm sure this was correct on CentOS7 but doesn't work for Ubuntu 20.04.
Correct filename is /etc/bash.bashrc.

**Comment by avikivity** [comment]
Backported to 4.6. Earlier branches did not use Ubuntu.
