### ISSUE TITLE
Scylla doesn't use column index in sstables

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#959]
Cassandra writes an index of cell names within partition every `column_index_size_in_kb` of written data. This allows it to avoid scanning through the whole partition when looking for a particular CQL row. Scylla doesn't write such index. It also doesn't use it, even though it is read (as `index_entry::_promoted_index`).

This will impact performance of reads with large partitions.

**Comment by tgrabiec** [comment]
Depends on https://github.com/scylladb/scylla/issues/656

**Comment by nyh** [comment]
I documented in detail the sstable index file, including the "promoted index",
here: https://github.com/scylladb/scylla/wiki/SSTables-Index-File

This documentation explains what we'll need to read and write from the sstable, how to use the so-called "promoted index" to skip inside very long partitions, and where the relevant Cassandra code lives.
