### ISSUE TITLE
Persist state of discovery

### ISSUE THREAD

**Issue by kostja** [scylladb/scylla#9593]
During boot, we use a special "discovery" protocol to establish initial Raft Group. We should persist the state of this protocol, otherwise two clusters may form if one of the nodes restarts during discovery and the timing is right:
Seed configuration:
node 1 points to node 2 as its seed. Node 2 seed list is empty.

Event flow
1 contacts 2 before 2 decides to become a leader
1 becomes a leader
2 restarts
2 becomes a leader

**Comment by kostja** [comment]
Queued in the master branch.

**Comment by kbr-** [comment]
7719f4cd91b06d2c825178274b6c4fe046352495
