### ISSUE TITLE
memtable: use after move

### ISSUE THREAD

**Issue by enedil** [scylladb/scylla#9605]
In `memtable.cc` there's a line:
``` 
       return make_partition_snapshot_flat_reader<false, partition_snapshot_read_accounter>(snp->schema(), std::move(permit), std::move(dk), std::move(crr), std::move(snp), digest_requested, region, read_section, pointer_to_container, fwd, memtable);
```
If `snp->schema()` is evaluated after `std::move(snp)`, there is use after move which triggers a segfault. This is not the case on clang, as it evaluates arguments from left to right, however affects gcc.

**Comment by avikivity** [comment]
Backported to 4.6. Older branches not vulnerable.
