### ISSUE TITLE
pull request docs/* check runs "make -C docs test", which always fails

### ISSUE THREAD

**Issue by cmm** [scylladb/scylla#9612]
Since ff56b7e43, any change under docs/ in a PR branch causes "make -C docs test" to run.
The command always fails.
It is not nice to put an action that always fails, regardless of specific changes that trigger it, in an automatic pipeline.

@dgarcia360

**Comment by dgarcia360** [comment]
@cmm The workflow seems to be working as expected. 

>Builds the docs when the default branch receives a new pull request or when the pull request receives new commits. The purpose of this workflow is to make sure pull requests do not break the default branch after being merged.

The workflow raised the first error when https://github.com/scylladb/scylla/pull/9517 was submitted:

![image](https://user-images.githubusercontent.com/9107969/141162215-2fe91b0f-ed05-4a2e-b431-ec04791aaf46.png)

Most likely, this PR was merged although the GitHub Bot posted this message:

![image](https://user-images.githubusercontent.com/9107969/141162683-ba73ce93-a4d5-476c-b608-cc8786fb5081.png)

Reviewing the logs, it has to do with using an unknown lexer:

![image](https://user-images.githubusercontent.com/9107969/141162932-cde059f9-5ec2-4316-bd61-eb13c0bc257b.png)

I've fixed the warning in the next PR https://github.com/scylladb/scylla/pull/9613

**Comment by dgarcia360** [comment]
> It is not nice to put an action that always fails, regardless of specific changes that trigger it, in an automatic pipeline.

Suppose a project runs a collection of tests every time there is a new pull-request. If someone merges a PR with an error, all the subsequent pull-requests with new additions will not pass the tests neither. This workflows does the same, but with docs instead than with code.

**Comment by cmm** [comment]
@dgarcia360 I stand corrected, thank you.
