### ISSUE TITLE
Scylla HTTP API can't parse logger levels with a space on it

### ISSUE THREAD

**Issue by fee-mendes** [scylladb/scylla#9614]
*Installation details*
Scylla version (or git commit hash): 4.5.1-0.20211024.4c0eac049
Cluster size: 1
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS

It turns out that Scylla `/system/logger` API reports a logger type with a space :
```shell
# curl http://localhost:10000/system/logger/ 2>/dev/null | jq  | egrep '[a-z] [a-z]'
  "query result log",
```

Other than updating this logger level via the traditional `SCYLLA_ARGS=` mechanism, there is virtually no way to dynamically tune (or at least we couldn't find one ;-) this parameter:

nodetool:
```shell
nodetool setlogginglevel 'query result log' error
/opt/scylladb/share/cassandra/bin/nodetool: line 62: [: result: binary operator expected
error: Scylla API server HTTP POST to URL '/system/logger/query' failed: Missing mandatory parameter 'level'
-- StackTrace --
java.lang.IllegalStateException: Scylla API server HTTP POST to URL '/system/logger/query' failed: Missing mandatory parameter 'level'
```

curl:
```shell
$ curl 'http://localhost:10000/system/logger/\"query result log\"'; echo
Can't parse the request

$ curl 'http://localhost:10000/system/logger/query result log'; echo
Can't parse the request

$ curl 'http://localhost:10000/system/logger/query+result+log'; echo
{"message": "Unknown logger name query+result+log", "code": 400}

$ curl 'http://localhost:10000/system/logger/query%20result%20log'; echo
{"message": "Unknown logger name query%20result%20log", "code": 400}
```

It sounds much more intuitive to avoid creating loggers with spaces or other special characters on it :-)

**Comment by slivne** [comment]
lets change the logger name all the others are using "_"

**Comment by eliransin** [comment]
Sure, however maybe we can also future proof it in nodetool (maybe encoding space as %20 can do the trick).
I will pursue both options.

**Comment by nyh** [comment]
This is a long-standing bug in Seastar's HTTP, which doesn't decode URLs as it should. See https://github.com/scylladb/seastar/issues/725.
Let's fix it and not come up with weird workarounds.

**Comment by nyh** [comment]
I agree with @eliransin since this is probably the only logger with a space in its name, and all others use underscore, let's just change its name to use underscore too. I don't think we need to be backward-compatible in these logger names, right?
