### ISSUE TITLE
dist/docker/debian/build_docker.sh: Searching for wrong file pattern in `rc` release

### ISSUE THREAD

**Issue by yaronkaikov** [scylladb/scylla#9616]
during build process in 4.6 docker build failed with the following error message:
```
"/jenkins/workspace/scylla-4.6/build/scylla/build/dist/release/debian/scylla_4.6.rc0-0.20211110.ea89eff95-1_arm64.deb": no such file or directory
```
This is due to the fact that `SCYLLA-VERSION-GEN` is configured with `4.6.rc0` while deb package is being built with `4.6~rc0`

**Comment by yaronkaikov** [comment]
@avikivity can you please backport this to 4.6?

**Comment by avikivity** [comment]
Backported to 4.6, older versions were not ubuntu based and so not vulnerable.
