### ISSUE TITLE
Scylla prometheus client fails during writing data to DB

### ISSUE THREAD

**Issue by IlyaOrlov** [scylladb/scylla#9618]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

*Installation details*
Scylla version (or git commit hash): Scylla version 4.3.0-0.20210110.000585522 with build-id 7fab6c35a5d403f3416292b37c9a9aa94fe4db1f
Cluster size: 5
OS (RHEL/CentOS/Ubuntu/AWS AMI): CentOS Linux release 7.9.2009 (Core)

*Hardware details (for performance issues)*          Delete if unneeded
Platform (physical/VM/cloud instance type/docker): physical
Hardware: sockets=2 cores=64 hyperthreading=True memory=376Gb
Disks: (SSD/HDD, count) - HDD - 59Tb on each node

[Backtrace #0]
google::protobuf::internal::ArenaStringPtr::CreateInstance(google::protobuf::Arena*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const*) at metrics2.pb.cc:?
io::prometheus::client::Counter* google::protobuf::Arena::CreateMaybeMessage<io::prometheus::client::Counter>(google::protobuf::Arena*) at metrics2.pb.cc:?
 (inlined by) io::prometheus::client::Counter* google::protobuf::Arena::CreateMaybeMessage<io::prometheus::client::Counter>(google::protobuf::Arena*) at ./build/release/seastar/gen/src/proto/metrics2.pb.cc:3121
io::prometheus::client::Summary::_InternalParse(char const*, google::protobuf::internal::ParseContext*) at metrics2.pb.cc:?
 (inlined by) char const* google::protobuf::internal::VarintParse<unsigned long>(char const*, unsigned long*) at /usr/include/google/protobuf/parse_context.h:488
 (inlined by) google::protobuf::internal::ReadVarint(char const**) at /usr/include/google/protobuf/parse_context.h:584
 (inlined by) io::prometheus::client::Summary::_InternalParse(char const*, google::protobuf::internal::ParseContext*) at ./build/release/seastar/gen/src/proto/metrics2.pb.cc:1411
io::prometheus::client::Histogram::_InternalParse(char const*, google::protobuf::internal::ParseContext*) at metrics2.pb.cc:?
 (inlined by) io::prometheus::client::Histogram::_InternalParse(char const*, google::protobuf::internal::ParseContext*) at ./build/release/seastar/gen/src/proto/metrics2.pb.cc:1871

**See full backtrace in the attached trace_decoded.txt**
[trace_decoded.txt](https://github.com/scylladb/scylla/files/7520606/trace_decoded.txt)

**Comment by slivne** [comment]
@IlyaOrlov 4.3.0 is very old and not supported please upgrade - we may have fixed this issue and you are hitting it since you are on an old version - following the upgrade you can update here if you are still hitting the issue.

Please note currently we only maintain 4.4.X / 4.5.X releases and fix bugs users hit on those release.

**Comment by slivne** [comment]
closing the issue - not further comment
