### ISSUE TITLE
Alternator HTTP server should disable Nagle's algorithm (TCP_NODELAY) like other servers

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#9619]
A user reported that while most Alternator requests are answered in less than 2ms, some of them are answered in 40ms. 
This number 40ms should be familiar to some of us - it is a telltale sign of the infamous interaction between Nagle's algorithm on one machine and Delayed Ack on the other machine (on Linux, delayed ack defaults to exactly 40ms).
I think what is happening is the following:

1. The Alternator **server** wishes to send a response that is slightly longer than one MSS (TCP maximum segment size). It sends the first packet, but then will not send the second, small, packet until receiving an ACK for the first one. That is Nagle's algorithm - the idea is that the OS hopes (without foundation) that the application will have more data to send so it can send it in the same packet.
2. The client, a Linux machine, receives the first packet but Linux does not ACK it yet. This is the Delayed Ack feature (in the client's OS, not related to any library they're using) - Linux doesn't ACK a single packet for 40ms, hoping it can piggy-back the ACK on a message it will need to send anyway soon - or ACK more than one packet in a single ACK.

To solve this problem, the server needs to disable Nagle's algorithm while sending responses. The classic way to do it is to enable TCP_NODELAY on the socket (on the server's side). This will cause every write to the socket to be immediately flushed to the network - even if it generates very small frames.
An alternative and more "elaborate" approach is to use TCP_CORK - which should be enabled when the server starts to send a response and disabled when the response completes. This way, even if the response is written in multiple writes (e.g., headers and data separately), the data will still be collected to full packets - until the last small packet, that is also sent out immediately.

It turns out that our CQL server implementation uses the code in `generic_server.cc` which does
```c++
            fd.set_nodelay(true);
```
on every accepted connection. So this sets TCP_NODELAY so it fixes the problem as explained above.

Alternator should probably do the same, but doesn't: Alternator actually uses Seastar's HTTP server, and that code is missing any calls to `fd.set_nodelay(true)` (or alternatively any use of TCP_CORK).

We need to fix this in the Seastar level. The fix is trivial, but we need to decide how to configure this (should set_nodelay() be done always by Seastar's http server or be an option that Alternator will enable? will we use set_nodelay() or the harder-to-use TCP_CORK ?). It's not trivial to test this problem.

@psarna would you mind looking into this issue?
CC @amnonh @eliransin

**Comment by nyh** [comment]
Opened a Seastar issue https://github.com/scylladb/seastar/issues/968 - because we need to solve this in Seastar.

**Comment by psarna** [comment]
> A user reported that while most Alternator requests are answered in less than 2ms, some of them are answered in 40ms. This number 40ms should be familiar to some of us - it is a telltale sign of the infamous interaction between Nagle's algorithm on one machine and Delayed Ack on the other machine (on Linux, delayed ack defaults to exactly 40ms). I think what is happening is the following:
> 
> 1. The Alternator **server** wishes to send a response that is slightly longer than one MSS (TCP maximum segment size). It sends the first packet, but then will not send the second, small, packet until receiving an ACK for the first one. That is Nagle's algorithm - the idea is that the OS hopes (without foundation) that the application will have more data to send so it can send it in the same packet.
> 2. The client, a Linux machine, receives the first packet but Linux does not ACK it yet. This is the Delayed Ack feature (in the client's OS, not related to any library they're using) - Linux doesn't ACK a single packet for 40ms, hoping it can piggy-back the ACK on a message it will need to send anyway soon - or ACK more than one packet in a single ACK.
> 
> To solve this problem, the server needs to disable Nagle's algorithm while sending responses. The classic way to do it is to enable TCP_NODELAY on the socket (on the server's side). This will cause every write to the socket to be immediately flushed to the network - even if it generates very small frames. An alternative and more "elaborate" approach is to use TCP_CORK - which should be enabled when the server starts to send a response and disabled when the response completes. This way, even if the response is written in multiple writes (e.g., headers and data separately), the data will still be collected to full packets - until the last small packet, that is also sent out immediately.
> 
> It turns out that our CQL server implementation uses the code in `generic_server.cc` which does
> 
> ```c++
>             fd.set_nodelay(true);
> ```
> 
> on every accepted connection. So this sets TCP_NODELAY so it fixes the problem as explained above.
> 
> Alternator should probably do the same, but doesn't: Alternator actually uses Seastar's HTTP server, and that code is missing any calls to `fd.set_nodelay(true)` (or alternatively any use of TCP_CORK).
> 
> We need to fix this in the Seastar level. The fix is trivial, but we need to decide how to configure this (should set_nodelay() be done always by Seastar's http server or be an option that Alternator will enable? will we use set_nodelay() or the harder-to-use TCP_CORK ?). It's not trivial to test this problem.
> 
> @psarna would you mind looking into this issue? CC @amnonh @eliransin

Sure, I'll send a patch which expresses my viewpoint. I think that tcp_nodelay should be unconditional for HTTP (at least until some user insists that they need it to be configurable), but I'll let the discussion continue on the Seastar bug tracker.

**Comment by nyh** [comment]
The fix was a Seastar patch, so if we want to backport it it will require a backport in Seastar. The fix unfortunately didn't reach branch 4.6, so it will need to be backported to 4.6 too (and we don't have a 4.6 Seastar branch yet).

**Comment by avikivity** [comment]
I think it's okay to keep it in 5.0+ only, since it isn't a regression.
