### ISSUE TITLE
[AMI 0.18] Longevity test failure: (DrainerMonkey) - cassandra-stress does not survive

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#962]
The execution of the drainer monkey on the most recent AMI, now with 5 minutes of nemesis interval, causes cassandra-stress to fail in about 15 minutes:

    03:19:45 remote           L0773 DEBUG| Remote [centos@54.193.83.106]: Running 'cassandra-stress write cl=QUORUM duration=1440m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=4 -node 172.31.30.65'
    ...
    03:34:44 remote           L0182 DEBUG| [54.193.83.106] [stdout] java.io.IOException: Operation x10 on key(s) [36324f4e33304b313231]: Error executing: (UnavailableException): Not enough replicas available for query at consistency QUORUM (2 required but only 1 alive)

Unlike the previous issue found with this nemesis, #925, the nodes don't seem to be running out of space.

What the test does
------------------

The workflow of a longevity test is:

1. Create a scylla cluster (referred as DB cluster from now on) with number of nodes (default size is 6) and node size (default is t2.micro, the bug report is using c3.large) defined by the user on a config file
2. Create a number of loader nodes, that will stress the DB cluster, typically by running cassandra stress on it
3. The cluster object hosts a Nemesis (that terminology was borrowed from Jepsen), a thread that randomly picks a non-seed node and disrupt it in some way.
4. Nemesis will sleep for a specified time interval, then execute the disruption function, then sleep again, rinse and repeat.
5. Cassandra-stress starts. The default command line looks like:

    `cassandra-stress write cl=QUORUM duration=1440m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=4 -node 172.31.27.192`

6. At all times, we have at least initial cluster size - 1 (6 -1 = 5) nodes active, which should be enough to keep c-s going. The disruption functions operate on a single node, and operations that actually remove a node permanently from the cluster will add a new node to compensate the one that was removed.
7. Given all that, we do expect that c-s survives until the specified time period (the report is using 24 hours). If it doesn't, chances are that we have a bug.

What the nemesis does
---------------------

1. Execute the following command in the target node:

    `nodetool -h localhost drain`

2. Stop the AWS instance of the target node.
3. Start the AWS instance of the target node.
4. Wait until the DB services are up (port 9042 occuppied)

**Comment by lmr** [comment]
Scylla package versions:

    scylla-boost-filesystem-1.58.0-11.el7.centos.x86_64
    scylla-boost-program-options-1.58.0-11.el7.centos.x86_64
    scylla-boost-system-1.58.0-11.el7.centos.x86_64
    scylla-boost-test-1.58.0-11.el7.centos.x86_64
    scylla-boost-thread-1.58.0-11.el7.centos.x86_64
    scylla-env-1.0-1.el7.centos.noarch
    scylla-gdb-7.10.1-30.el7.centos.x86_64
    scylla-jmx-0.18-20160216.4b88457.el7.centos.noarch
    scylla-server-0.18-20160216.b532919.el7.centos.x86_64
    scylla-server-debuginfo-0.18-20160216.b532919.el7.centos.x86_64
    scylla-tools-0.17-20160216.afadea3.el7.centos.noarch

**Comment by penberg** [comment]
@gleb-cloudius, is this perhaps already fixed by f59415b3c6ebdd8f85b72f5658767ac676493845? In the test scenario, one node is killed and then restarted while cassandra-stress is running.

**Comment by gleb-cloudius** [comment]
On Wed, Mar 09, 2016 at 03:45:12AM -0800, Pekka Enberg wrote:
> @gleb-cloudius, is this perhaps already fixed by f59415b3c6ebdd8f85b72f5658767ac676493845? In the test scenario, one node is killed and then restarted while cassandra-stress is running.
> 
No, the test does not test bootstrapping, just regular node up/down.

--
			Gleb.

**Comment by penberg** [comment]
I think we actually have a dtest that also triggers the problem. The following failure doesn't happen for _every_ run but it usually doesn't take very long time to hit it:

```
======================================================================
ERROR: simple_removenode_1_test (update_cluster_layout_tests.TestUpdateClusterLayout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/penberg/scylla-dtest/update_cluster_layout_tests.py", line 921, in simple_removenode_1_test
    result = session.execute(query)
  File "cassandra/cluster.py", line 1602, in cassandra.cluster.Session.execute (cassandra/cluster.c:26565)
    result = future.result()
  File "cassandra/cluster.py", line 3347, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:62845)
    raise self._final_exception
Unavailable: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl TWO. Requires 2, alive 1" info={'required_replicas': 2, 'alive_replicas': 1, 'consistency': 'TWO'}
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/penberg/.dtest/dtest-Sy9uHQ
cassandra.cluster: WARNING: Host 127.0.0.2 has been marked down
cassandra.cluster: WARNING: Host 127.0.0.2 has been marked down
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 2.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 8.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 16.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 32.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
dtest: DEBUG: Retrying request after UE. Attempt #0
dtest: DEBUG: Retrying request after UE. Attempt #1
dtest: DEBUG: Retrying request after UE. Attempt #2
dtest: DEBUG: Retrying request after UE. Attempt #3
dtest: DEBUG: Retrying request after UE. Attempt #4
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 68.800s

FAILED (errors=1)
FAILURE
```

**Comment by penberg** [comment]
Looks similar to this issue: https://github.com/scylladb/scylla/issues/894

Ping @asias

**Comment by penberg** [comment]
This is not a recent regression -- the bug is reproducible in the 0.18 branch.

**Comment by asias** [comment]
I will take a look.

**Comment by asias** [comment]
@penberg can you reproduce locally. I tried 20 runs of 
update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_removenode_1_test
I did not reproduce with current master 16135c2084decd94e76c26706ddb2ecafa9d0043

**Comment by asias** [comment]
@penberg I did another 60 runs with no problem.

**Comment by penberg** [comment]
@asias Yes, I am able to reproduce locally but I forgot to mention that I am testing with ``--smp 2``:

```
[penberg@nero scylla-dtest]$ export SCYLLA_EXT_OPTS="--smp 2"
[penberg@nero scylla-dtest]$ nosetests -v -s update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_removenode_1_test
simple_removenode_1_test (update_cluster_layout_tests.TestUpdateClusterLayout) ... ERROR

======================================================================
ERROR: simple_removenode_1_test (update_cluster_layout_tests.TestUpdateClusterLayout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/penberg/scylla-dtest/update_cluster_layout_tests.py", line 921, in simple_removenode_1_test
    result = session.execute(query)
  File "cassandra/cluster.py", line 1602, in cassandra.cluster.Session.execute (cassandra/cluster.c:26565)
    result = future.result()
  File "cassandra/cluster.py", line 3347, in cassandra.cluster.ResponseFuture.result (cassandra/cluster.c:62845)
    raise self._final_exception
Unavailable: code=1000 [Unavailable exception] message="Cannot achieve consistency level for cl TWO. Requires 2, alive 1" info={'required_replicas': 2, 'alive_replicas': 1, 'consistency': 'TWO'}
-------------------- >> begin captured logging << --------------------
dtest: DEBUG: cluster ccm directory: /home/penberg/.dtest/dtest-naltDA
cassandra.cluster: WARNING: Host 127.0.0.2 has been marked down
cassandra.cluster: WARNING: Host 127.0.0.2 has been marked down
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 2.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 4.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 8.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 16.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
cassandra.pool: WARNING: Error attempting to reconnect to 127.0.0.2, scheduling retry in 32.0 seconds: [Errno 111] Tried connecting to [('127.0.0.2', 9042)]. Last error: Connection refused
dtest: DEBUG: Retrying request after UE. Attempt #0
dtest: DEBUG: Retrying request after UE. Attempt #1
dtest: DEBUG: Retrying request after UE. Attempt #2
dtest: DEBUG: Retrying request after UE. Attempt #3
dtest: DEBUG: Retrying request after UE. Attempt #4
--------------------- >> end captured logging << ---------------------

----------------------------------------------------------------------
Ran 1 test in 69.151s

FAILED (errors=1)
FAILURE
```

**Comment by asias** [comment]
@penberg Thanks. Managed to reproduce with --smp 2 + current master f747df2aff2b3a39bacfc0c8e21c13074e3ab70d

**Comment by lmr** [comment]
I still observe this using the latest 1.0-rc1 AMI

    18:29:36 remote           L0773 DEBUG| Remote [centos@54.191.177.102]: Running 'cassandra-stress write cl=QUORUM duration=1440m -schema 'replication(factor=3)' -port jmx=6868 -mode cql3 native -rate threads=1000 -node 172.31.42.50'
    ...
    23:44:07 remote           L0182 DEBUG| [54.191.177.102] [stdout] java.io.IOException: Operation x10 on key(s) [304b384f32364d4c4f30]: Error executing: (WriteTimeoutException): Cassandra timeout during write query at consistency QUORUM (2 replica were required but only 1 acknowledged the write)

**Comment by slivne** [comment]
@gleb-cloudius can you have a look at this as well 

Drain is different then remove node as it does not change the token ownership - so although the removenode issue may have been fixed - I doubt that any of the patches that asias has sent are related

**Comment by gleb-cloudius** [comment]
I believe there may be a problem with a test scenario (as in result we are getting is expected). Suppose we have three nodes: A B C.
1. A is stopped.
2. write to B & C is started
3. A is started
4. B is stopped
5. write that was started at 2 will timeout

The problem is aggravated by the fact that we do not wait for all ongoing messages to complete before shutting does messaging service during drain which makes race window larger (but it does exists in any case).

**Comment by slivne** [comment]
Two comments:

   - The test does executed drain before stopping the node - doesn't drain
   wait for all the current commands to finish
   - The nemesis waits for the next cycle so there are 5 minutes between 3
   and 4 (@lmr is that the current interval in your test)

updating your example:

1. A is stopped.
2. write to B & C is started
3. A is started
4. Wait 5 minutes
5. B is drained, B is then stopped

**Comment by gleb-cloudius** [comment]
OTOH first message has UnavailableException which cannot be explained by the race, but both errors can be caused by test not detecting that node is alive correctly or by a node failing to join the cluster back, but still opening  cql port. What nodetool says about the cluster when it fails?

**Comment by slivne** [comment]
The first messages is from an AMI on older version - the new WriteTimeout
is on an updated ami

**Comment by slivne** [comment]
@lmr do we pass this test on c3.larg with the AMI from 1.0 ? - if so please close

**Comment by lmr** [comment]
@slivne yes, it does pass. I'm closing this issue.
