### ISSUE TITLE
scylla_util.py: unable to get correct state from systemd_unit.is_active() since we change return value to bool

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#9627]
We can get systemd unit status by "systemctl status" as follows:
```
$ systemctl status sshd --no-pager
● sshd.service - OpenSSH server daemon
     Loaded: loaded (/usr/lib/systemd/system/sshd.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-11-15 17:46:03 JST; 1h 7min ago
...
```
But this output is not scripting friendly, there are also simpler output one:
```
$ systemctl is-active sshd
active
```

On scylla_unit.py, we provide `systemd_unit.is_active()` to return `systemctl is-active` output.
When we introduced systemd_unit class, we just returned `systemctl is-active` output as string, but we changed the return value to bool after that (2545d7fd438338263d0cc52eb8e7433fb61afee7).
This was because `if unit.is_active():` always becomes True even it returns "failed" or "inactive", to avoid such scripting bug.
However, probably this was mistake.
Because systemd unit state is not 2 state, like "start" / "stop", there are many state.
Accoring to systemd source code, there are following state:
```
typedef enum UnitActiveState {
        UNIT_ACTIVE,
        UNIT_RELOADING,
        UNIT_INACTIVE,
        UNIT_FAILED,
        UNIT_ACTIVATING,
        UNIT_DEACTIVATING,
        UNIT_MAINTENANCE,
        _UNIT_ACTIVE_STATE_MAX,
        _UNIT_ACTIVE_STATE_INVALID = -EINVAL,
} UnitActiveState;
```
https://github.com/systemd/systemd/blob/main/src/basic/unit-def.h#L42

And we already using multiple unit state ("activating", "failed", "inactive", "active") in our Cloud image login prompt:
https://github.com/scylladb/scylla-machine-image/blob/next/common/scylla_login#L135
After we merged 2545d7fd438338263d0cc52eb8e7433fb61afee7, the login prompt is broken, because it does not return string as script expected (https://github.com/scylladb/scylla-machine-image/issues/241).

I think we should revert 2545d7fd438338263d0cc52eb8e7433fb61afee7, it should return exactly same value as `systemctl is-active` says.

**Comment by avikivity** [comment]
Backported to 4.6, the only vulnerable branch.
