### ISSUE TITLE
sstable index/data reader over-reads

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#964]
Right now, we use a fixed block size of 8192 for the index, which means we usually over-read.

We should instead provide (offset, len) for the index block, and use a block size of 128k.  input_stream will automatically narrow the block size to avoid over-reads, taking into account the minimum dma read alignment.

Same for the data.

**Comment by nyh** [comment]
Avi, what kind of use case were you thinking about here? Reading of one specific partition? Iterating through a range of partitions? Iterating through *all* the partitions (probably not)? Is compression enabled?

I'm guessing that for the data part, the code which bothered you is sstable::data_consume_rows(). This isn't used for every case (e.g., when reading a single partition, we *don't* use this function), but this is what you wanted fixed, right? (and also the index part)

**Comment by nyh** [comment]
Ok, I think I have a pretty good idea of what you meant should be fixed. I'll prepare a patch and let you review that instead of continuing to discuss it over the bug tracker.

**Comment by nyh** [comment]
Words of wisdom from Avi on the mailing list on this topic:

**"Parameters to input_stream are (offset, len), block size, read ahead.  The stream won't read more than len, and won't read more than block_size * read_ahead ahead.
Right now we don't provide len, and instead play with block size.  Fixing that should be enough."**
