### ISSUE TITLE
Major compaction isn't able to compact data across different time windows

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#9662]
Even with major compaction on a TWCS table, data from different windows cannot be compacted together. That's a limitation in compaction code where mutation compactor happens inside each consumer, and not in the producer before the data is feeded into the interposer consumer for segregation.

This is important if TWCS user performed a bulk of deletions and want to remove shadowed data through compaction

**Comment by slivne** [comment]
> now that interposer consumer can be enabled with incremental
compaction, this series will have to be reworked.

**Comment by avikivity** [comment]
Not a regression, and not trivial, so not backporting.
