### ISSUE TITLE
scylla-4.5 - degradation of ~20% in test throughput

### ISSUE THREAD

**Issue by fgelcer** [scylladb/scylla#9665]
*Installation details*
Kernel version: `5.11.0-1021-gcp`
Scylla version (or git commit hash): `4.5.2-0.20211114.26aca7b9f`
Cluster size: 6 nodes (n1-highmem-16)
Scylla running with shards number (live nodes):
   longevity-10gb-3h-4-5-db-node-84909090-0-1 (34.74.24.174 | 10.142.0.28): 16 shards
   longevity-10gb-3h-4-5-db-node-84909090-0-3 (35.237.239.177 | 10.142.0.30): 16 shards
   longevity-10gb-3h-4-5-db-node-84909090-0-5 (35.196.54.153 | 10.142.0.32): 16 shards
   longevity-10gb-3h-4-5-db-node-84909090-0-7 (35.185.59.219 | 10.142.0.55): 16 shards
   longevity-10gb-3h-4-5-db-node-84909090-0-8 (34.139.136.14 | 10.142.0.66): 16 shards
   longevity-10gb-3h-4-5-db-node-84909090-0-9 (34.138.73.216 | 10.142.0.89): 16 shards
   longevity-10gb-3h-4-5-db-node-84909090-0-10 (35.196.224.8 | 10.142.0.91): 16 shards
Scylla running with shards number (terminated nodes):
   longevity-10gb-3h-4-5-db-node-84909090-0-4 (34.139.136.253 | 10.142.0.31): 16 shards
   longevity-10gb-3h-4-5-db-node-84909090-0-2 (35.237.93.110 | 10.142.0.29): 16 shards
   longevity-10gb-3h-4-5-db-node-84909090-0-6 (35.231.75.14 | 10.142.0.45): 16 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `-` (gce: eu-west-1)

Test: `longevity-10gb-3h-gce-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4a1f9acd7e33a68d3562626d77b35bcb55822dc7/test-cases/longevity/longevity-10gb-3h.yaml)

**Issue description**

comparing with runs against `4.5.1-0.20211030.84025f6ce0` there is a clear degradation in the test's throughput

here is the last test that passed (`4.5.1-0.20211030.84025f6ce0`):
![Screenshot from 2021-11-21 23-04-02](https://user-images.githubusercontent.com/32832995/142829015-26faf1d1-fa81-4a36-a72f-b4c4b778b800.png)
to recreate this monitor, please click [this link](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=a928bb47-7d28-406a-abb6-6178ead8f775)

and here is the last test (the one mentioned in the details above):
![Screenshot from 2021-11-21 23-00-51](https://user-images.githubusercontent.com/32832995/142829117-bea99138-4945-4055-bcf1-e87b7d0d84b8.png)
to recreate this monitor, please click [this link](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=84909090-1f52-4a01-8f89-a3a054eb502f)

from build 57 (last that passed) to build 62, there were other few builds that all failed, so i will try to recreate their monitors to confirm where the degradation started...
in parallel, i will re-run the test with 4.5.1 to see the difference between.

Restore Monitor Stack command: `$ hydra investigate show-monitor 84909090-1f52-4a01-8f89-a3a054eb502f`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=84909090-1f52-4a01-8f89-a3a054eb502f)
Show all stored logs command: `$ hydra investigate show-logs 84909090-1f52-4a01-8f89-a3a054eb502f`

Test id: `84909090-1f52-4a01-8f89-a3a054eb502f`

Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/84909090-1f52-4a01-8f89-a3a054eb502f/20211115_124047/db-cluster-84909090.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/84909090-1f52-4a01-8f89-a3a054eb502f/20211115_124047/db-cluster-84909090.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/84909090-1f52-4a01-8f89-a3a054eb502f/20211115_124047/loader-set-84909090.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/84909090-1f52-4a01-8f89-a3a054eb502f/20211115_124047/loader-set-84909090.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/84909090-1f52-4a01-8f89-a3a054eb502f/20211115_124047/monitor-set-84909090.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/84909090-1f52-4a01-8f89-a3a054eb502f/20211115_124047/monitor-set-84909090.tar.gz)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/84909090-1f52-4a01-8f89-a3a054eb502f/20211115_124047/sct-runner-84909090.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/84909090-1f52-4a01-8f89-a3a054eb502f/20211115_124047/sct-runner-84909090.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.5/job/longevity/job/longevity-10gb-3h-gce-test/62/)

**Comment by slivne** [comment]
this i the diff between the versions

```
 git shortlog 84025f6ce0..26aca7b9f7d8b9b4f9cc0e535c15a786db1fef8f
Asias He (1):
      storage_service: Abort restore_replica_count when node is removed from the cluster

Avi Kivity (1):
      build: clobber user/group info from node_exporter tarball

Hagit Segev (1):
      release: prepare for 4.5.2

Nadav Har'El (1):
      alternator: fix bug in ReturnValues=ALL_NEW
```

nothing seems like a reason that will cause 1% degradation - this doesn't make any sense

nadav's changes are only in alternator related code 

Asias's change is in storage service @asias (/cc @eliransin ) - can you double check that is limited to the specific case in the commit message - and did not change something hot path

**Comment by slivne** [comment]
@roydahan / @fgelcer can uelase doube check that not thing else changed - rerun 4.5.1 and 4.5.2 on the same exact SCT commit.

**Comment by avikivity** [comment]
Notice the utilization is way below 100% in both cases. It's a test or environment change. What is that test doing?

Agree with @slivne that there's no way that those commits are responsible.

**Comment by fgelcer** [comment]
i have re-created a monitor stack for the 1st build after last success, and it already has a little degradation:
![Screenshot from 2021-11-22 11-08-32](https://user-images.githubusercontent.com/32832995/142833836-ff93ee62-341e-427a-bcef-5c13db654814.png)

i'm running (in parallel) same SCT code, 2 different jobs in Jenkins, last successful image and last image that run:
[last successful image](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/4.5/job/longevity-3h-gce-4.5.1/2/)
[last created image](https://jenkins.scylladb.com/view/staging/job/scylla-staging/job/fabio/job/4.5/job/longevity-3h-gce-4.5.2/)


test details are here of the monitor above:
*Installation details*
Kernel version: `5.11.0-1020-gcp`
Scylla version (or git commit hash): `4.5.1-0.20211031.84025f6ce`
Cluster size: 6 nodes (n1-highmem-16)
Scylla running with shards number (live nodes):
   longevity-10gb-3h-4-5-db-node-53fcf983-0-1 (35.185.105.11 | 10.142.0.162): 14 shards
   longevity-10gb-3h-4-5-db-node-53fcf983-0-3 (34.75.142.31 | 10.142.0.173): 14 shards
   longevity-10gb-3h-4-5-db-node-53fcf983-0-4 (34.74.142.142 | 10.142.0.174): 14 shards
   longevity-10gb-3h-4-5-db-node-53fcf983-0-7 (35.196.3.43 | 10.142.0.179): 14 shards
   longevity-10gb-3h-4-5-db-node-53fcf983-0-8 (34.139.79.110 | 10.142.0.4): 14 shards
   longevity-10gb-3h-4-5-db-node-53fcf983-0-9 (34.74.148.59 | 10.142.0.8): 14 shards
   longevity-10gb-3h-4-5-db-node-53fcf983-0-10 (34.139.221.56 | 10.142.0.11): 14 shards
Scylla running with shards number (terminated nodes):
   longevity-10gb-3h-4-5-db-node-53fcf983-0-2 (34.74.231.200 | 10.142.0.171): 14 shards
   longevity-10gb-3h-4-5-db-node-53fcf983-0-6 (34.138.82.87 | 10.142.0.176): 14 shards
   longevity-10gb-3h-4-5-db-node-53fcf983-0-5 (34.75.208.96 | 10.142.0.175): 14 shards
![Screenshot from 2021-11-22 11-08-32](https://user-images.githubusercontent.com/32832995/142833758-244fcedc-70dd-4100-9efd-fb033522c1fb.png)
OS (RHEL/CentOS/Ubuntu/AWS AMI): `-` (gce: eu-west-1)


Test: `longevity-10gb-3h-gce-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-10gb-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/9c05a112686c84edddf5fb3617188b8f67abcbbd/test-cases/longevity/longevity-10gb-3h.yaml)


Restore Monitor Stack command: `$ hydra investigate show-monitor 53fcf983-5c34-4e1d-8854-25575835706c`
Show all stored logs command: `$ hydra investigate show-logs 53fcf983-5c34-4e1d-8854-25575835706c`

Test id: `53fcf983-5c34-4e1d-8854-25575835706c`


Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/53fcf983-5c34-4e1d-8854-25575835706c/20211101_081326/db-cluster-53fcf983.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/53fcf983-5c34-4e1d-8854-25575835706c/20211101_081326/db-cluster-53fcf983.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/53fcf983-5c34-4e1d-8854-25575835706c/20211101_081326/loader-set-53fcf983.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/53fcf983-5c34-4e1d-8854-25575835706c/20211101_081326/loader-set-53fcf983.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/53fcf983-5c34-4e1d-8854-25575835706c/20211101_081326/monitor-set-53fcf983.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/53fcf983-5c34-4e1d-8854-25575835706c/20211101_081326/monitor-set-53fcf983.tar.gz)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/53fcf983-5c34-4e1d-8854-25575835706c/20211101_081326/sct-runner-53fcf983.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/53fcf983-5c34-4e1d-8854-25575835706c/20211101_081326/sct-runner-53fcf983.tar.gz)


[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-4.5/job/longevity/job/longevity-10gb-3h-gce-test/58/)

**Comment by asias** [comment]
> this i the diff between the versions
> 
> ```
>  git shortlog 84025f6ce0..26aca7b9f7d8b9b4f9cc0e535c15a786db1fef8f
> Asias He (1):
>       storage_service: Abort restore_replica_count when node is removed from the cluster
> 
> Avi Kivity (1):
>       build: clobber user/group info from node_exporter tarball
> 
> Hagit Segev (1):
>       release: prepare for 4.5.2
> 
> Nadav Har'El (1):
>       alternator: fix bug in ReturnValues=ALL_NEW
> ```
> 
> nothing seems like a reason that will cause 1% degradation - this doesn't make any sense
> 
> nadav's changes are only in alternator related code
> 
> Asias's change is in storage service @asias (/cc @eliransin ) - can you double check that is limited to the specific case in the commit message - and did not change something hot path

The patch does not change anything in hot path. I do not think it could cause perf regression.

**Comment by slivne** [comment]
@roydahan / @fgelcer ping we did additional runs whats the conclusion

**Comment by fgelcer** [comment]
running with `4.5.1-0.20211030.84025f6ce0` and `4.5.2-0.20211114.26aca7b9f`, with SCT `branch-4.5`, and got 2 very similar results:
`test_id: 81f9ea07-f047-4f95-8606-be520a6568d1` run - 4.5.1:
![Screenshot from 2021-11-24 15-57-47](https://user-images.githubusercontent.com/32832995/143251966-1619e1f1-ffdb-42fd-89b2-ece26dc72d94.png)

`test_id: 3ed63eb5-f55e-4df9-8c46-35d4f2363cc4` run - 4.5.2:
![Screenshot from 2021-11-24 15-59-37](https://user-images.githubusercontent.com/32832995/143252244-a6446d02-9cdf-4078-b9a4-3302f82c4028.png)


in this case, i'm closing this issue, as it seems to be related to environment or SCT changes...

**Comment by fgelcer** [comment]
if someone wants to look into these live monitors, they are live right now:
[4.5.1-0.20211030.84025f6ce0](http://3.235.196.179:3000/d/ylbzUKtnk/longevity-3h-gce-4-5-1-scylla-per-server-metrics-nemesis-master?orgId=1&from=1637575219320&to=1637586371346)

[4.5.2-0.20211114.26aca7b9f](http://3.238.79.12:3000/d/lp7dUKt7z/longevity-3h-gce-4-5-2-scylla-per-server-metrics-nemesis-master?orgId=1&from=1637575070759&to=1637586291954)

**Comment by fgelcer** [comment]
@slivne ^^^
