### ISSUE TITLE
CQL UPDATE of frozen collection column of  non-existing row does not insert value

### ISSUE THREAD

**Issue by elcallio** [scylladb/scylla#967]
CQL UPDATE should, if applied on a non-existing row, create said row. Scylla however does not seem to apply this when performed on a frozen list. 

Repro (cqlsh)

```
create keyspace ks WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 };
create table ks.test2 ( key int primary key, val1 text, val2 frozen<list<int>> );
update ks.test2 set val2=[1, 2] where key = 1;
select * from ks.test2;

key | val1 | val2
-----+------+------

(0 rows)
```

**Comment by slivne** [comment]
copying from email from Calle

Tomek,
Could you have a look at #967? (And Shlomi, I think maybe this bug should be upgraded). I would love to hear that I am doing something wrong here, but I am not so sure about that.

The apparent error is that doing a update insert of a frozen list does not work.

create keyspace ks WITH REPLICATION = { 'class' : 'SimpleStrategy', 'replication_factor' : 3 };
create table ks.test2 ( key int primary key, val1 text, val2 frozen<list<int>> );
update ks.test2 set val2=[1, 2] where key = 1;
select * from ks.test2;

key | val1 | val2
-----+------+------

(0 rows)


I've been trying to figure out where it goes wrong, and as far as I can see there is some sort of mismatch
between the definition of atomic_cell_or_collection and atomic_cell going on here.

In lists.cc:347, for a frozen collection, we serialize it to a format

<list len>, <<elem byte len>, <elem bytes>>[len]

which is then turned into an atomic_cell_or_collection, an operation which is equivalent of taking this very bytes above
and keeping them.
mutation.set_cell will then just move this atomic_cell_or_collection into the appropriate rows _storage.vector.

Later on, in storage proxy, when we freeze the mutation, we will end up in
mutation_partition_serializer::write_row_cells which will as cell.as_atomic_cell() of the above atomic_cell_or_collection.
This in turn will just return an atomic_cell_view of the same data as above. Then we ask "is_live()" on this cell view, which will apply atomic_cell_type::is_live on the data. Which checks if the first byte is not zero (DEAD_FLAGS). But the first byte here will be the high word of the list elem count (big endian), and quite zero.
We then promptly serialize a "dead cell", and lo, the update has become a delete.

This does not seem right.

**Comment by elcallio** [comment]
Actually, looking at set, map etc. it seems that line 347 should be a "params.make_cell", not a "atomic_cell_or_collection::from_collection_mutation". Seems to have this way for ages though...

Changing this makes my case work anyway. I'll test a little more, then send a patch.
