### ISSUE TITLE
In some cases, trying to assign an UNSET value into part of a UDT is not detected

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#9671]
When we have a user-defined type `(x int, y int)`, and the prepared statement `INSERT INTO tab (k, v) VALUES (10, {x:?, y:?})`, passing UNSET_VALUE (see https://github.com/scylladb/scylla/commit/9fb2f31616dd08bfc6e76bf7323b05a3ecca72a7)  as a value for (for example) y is forbidden, and results in an error:
```
Invalid unset value for field 'y' of user defined type
```
However, when the UDT is nested, e.g.,  `(a frozen<previoustype>)`, this situation is not detected as it should:
```
INSERT INTO tab (k, z) VALUES (10, {a:{x: ?, y: ?}})
```
Fails to report an error when UNSET_VALUE is passed for y.
Cassandra does report this error correctly.

This bug is reproduced by the translated Cassandra test:
* `cassandra_tests/validation/entities/user_types_test.py`:: `testUDTWithUnsetValues`

**Comment by cvybhu** [comment]
I ran into it in #9353, but didn't change it to limit changes introduced by the PR.

We could throw an exception here:
https://github.com/scylladb/scylla/blob/337906bc1c2bc6e9c8680f5cc4558a2e92109855/cql3/expr/expression.cc#L1682

**Comment by avikivity** [comment]
Minor (requires misuse of an obscure feature), not backporting.
