### ISSUE TITLE
reverse range scans are broken since the reversing effort

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#9673]
Reverse range scans are broken since 41facb32706982612dfd44f58e414ec3f44ba437, broken by the recent reverse query work and have gone unnoticed because we have no tests for reverse queries and CQL, our most tested client protocol doesn't allow for it.

**Comment by slivne** [comment]
It may be a regression and then we need to backport to 4.6 as well

**Comment by haaawk** [comment]
@denesb do I recall correctly that you have sent a fix for this already?

**Comment by denesb** [comment]
Yes, it is on the list: [PATCH v1 0/8] reverse range scans: use the correct schema for result building
It is waiting for merge.

**Comment by haaawk** [comment]
Please close this issue once the fix is merged @denesb

**Comment by denesb** [comment]
Will do.

**Comment by avikivity** [comment]
Not backporting. Reverse range scans are probably nonexistent in practice. 5.0 is already safe.
