### ISSUE TITLE
scylla-gdb fails in compaction-tasks when run locally with 

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9677]
@xemul:
> It fails the same way even if ran prior to b58403fb6329196c2f564311004beecdeffb5910 where I tossed the debug::db variable. It must be smth related to python-gdb linkage. I did fixed scylla-gdb test back then (because it failed on not finding the debug::db variable).

Reproducer at 44f4ea38c5

```
$ ninja build/release/scylla && test/scylla-gdb/run
...
Thread 1 "test-gdb-scylla" hit Breakpoint 1, sstables::compact_sstables (descriptor=..., cdata=..., table_s=...) at compaction/compaction.cc:1698
1698        if (descriptor.sstables.empty()) {


*** CMD: scylla features

"UDA": true
"ALTERNATOR_STREAMS": false
"UDF": false
"CDC_GENERATIONS_V2": true
"MD_SSTABLE_FORMAT": true
"VIEW_VIRTUAL_COLUMNS": true
"CORRECT_IDX_TOKEN_IN_SECONDARY_INDEX": true
"DIGEST_INSENSITIVE_TO_EXPIRY": true
"ALTERNATOR_TTL": false
"COMPUTED_COLUMNS": true
"CDC": true
"HINTED_HANDOFF_SEPARATE_CONNECTION": true
"PER_TABLE_CACHING": true
"RANGE_SCAN_DATA_VARIANT": true
"NONFROZEN_UDTS": true
"LWT": true
"DIGEST_FOR_NULL_VALUES": true
"PER_TABLE_PARTITIONERS": true


*** CMD: scylla compaction-tasks

Traceback (most recent call last):
  File "/local/home/bhalevy/dev/scylla/scylla-gdb.py", line 4198, in invoke
    cm = std_unique_ptr(db['_compaction_manager']).get().dereference()
gdb.error: Attempt to take contents of a non-pointer value.
Traceback (most recent call last):
  File "/local/home/bhalevy/dev/scylla/test/scylla-gdb/test.py", line 37, in <module>
    dos('compaction-tasks')
  File "/local/home/bhalevy/dev/scylla/test/scylla-gdb/test.py", line 19, in dos
    return do('scylla ' + cmd, known_broken, loudly=True)
  File "/local/home/bhalevy/dev/scylla/test/scylla-gdb/test.py", line 9, in do
    ret = gdb.execute(cmd)
gdb.error: Error occurred in Python: Attempt to take contents of a non-pointer value.
=== TEST.PY SUMMARY START ===
Test exited with code 255
```

**Comment by raphaelsc** [comment]
@denesb do you know how to workaround this?

**Comment by denesb** [comment]
What is the context? Is there a patch causing this? Or is this happening sporadically on local dev environments?

**Comment by denesb** [comment]
Note that `std_unique_ptr` and friends rely on the internals of the libstdc++ in use by scylla, which can change without notice and indeed have several times in the past, forcing us to adjust the code accordingly. Looks like `std_unique_ptr(...).get()` does not return a pointer type anymore, possibly because of some refactoring in `std::unique_ptr<>`'s implementation in `libstdc++`.

**Comment by raphaelsc** [comment]
On Thu, Dec 2, 2021, 12:13 PM Botond Dénes ***@***.***> wrote:

> What is the context? Is there a patch causing this? Or is this happening
> sporadically on local dev environments?
>
Seems like the latter. Not a regression as it seems. I assumed you could
have bumped into this before. Maybe it's a regression or perhaps an issue
with local environment

**Comment by raphaelsc** [comment]
On Thu, Dec 2, 2021, 12:15 PM Botond Dénes ***@***.***> wrote:

> Note that std_unique_ptr and friends rely on the internals of the
> libstdc++ in use by scylla, which can change without notice and indeed have
> several times in the past, forcing us to adjust the code accordingly. Looks
> like std_unique_ptr(...).get() does not return a pointer type anymore,
> possibly because of some refactoring in std::unique_ptr<>'s
> implementation in libstdc++.
>
Looks like a fun exercise :) will try to fix it

**Comment by denesb** [comment]
Maybe we should have separate tests for these common infrastructure classes, so we can spot such changes easily.

**Comment by bhalevy** [comment]
> Maybe we should have separate tests for these common infrastructure classes, so we can spot such changes easily.

Sounds like a good idea
