### ISSUE TITLE
Wrong permissions for scylla-housekeeping related files

### ISSUE THREAD

**Issue by ilya-rarov** [scylladb/scylla#9683]
*Installation details*
**Scylla version (or git commit hash):** 4.6.rc0-0.20211119.8b5b1b8af with build-id 5f641c83c55020b6aa2abbb53aae92000f32fc6f
**ScyllaDB repo:** https://s3.amazonaws.com/downloads.scylladb.com/unstable/scylla/branch-4.6/rpm/centos/2021-11-19T15:23:51Z/scylla.repo
**Cluster size:** 1 (i3.large)
**OS (RHEL/CentOS/Ubuntu/AWS AMI):** ami-0e883e67243efea62 (eu-west-1)

We introduced a housekeeping test in master. During the artifacts test job for Oracle Linux Server release 8.1 https://jenkins.scylladb.com/job/scylla-master/job/artifacts/job/artifacts-oel81-test/120/ we got the following error:
```
Command: 'cat /var/lib/scylla-housekeeping/housekeeping.uuid'
Exit code: 1
Stdout:
Stderr:
/etc/bashrc: line 99: TMOUT: readonly variable
/etc/bashrc: line 100: TMOUT: readonly variable
cat: /var/lib/scylla-housekeeping/housekeeping.uuid: Permission denied
```

We reproduced the problem [here](https://jenkins.scylladb.com/job/scylla-staging/job/yulia/job/yulia-artifacts-oel81-test/4/) and found the following error related to the housekeeping service in journalctl on the node
```
Nov 24 15:12:45 artifacts-oel81-jenkins-db-node-54d69e33-1 systemd[1]: Started Run Scylla Housekeeping daily mode.
Nov 24 15:12:45 artifacts-oel81-jenkins-db-node-54d69e33-1 systemd[1]: Started Run Scylla Housekeeping restart mode.
......
Nov 24 15:12:50 artifacts-oel81-jenkins-db-node-54d69e33-1 scylla-housekeeping[10720]: /opt/scylladb/scripts/libexec/scylla-housekeeping:195: DeprecationWarning: The SafeConfigParser class has been renamed to C>
Nov 24 15:12:50 artifacts-oel81-jenkins-db-node-54d69e33-1 scylla-housekeeping[10720]:   config = configparser.SafeConfigParser()
Nov 24 15:12:50 artifacts-oel81-jenkins-db-node-54d69e33-1 scylla-housekeeping[10720]: Traceback (most recent call last):
Nov 24 15:12:50 artifacts-oel81-jenkins-db-node-54d69e33-1 scylla-housekeeping[10720]:   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 207, in <module>
Nov 24 15:12:50 artifacts-oel81-jenkins-db-node-54d69e33-1 scylla-housekeeping[10720]:     repo_type, repo_id = get_repo_file(args.repo_files)
Nov 24 15:12:50 artifacts-oel81-jenkins-db-node-54d69e33-1 scylla-housekeeping[10720]:   File "/opt/scylladb/scripts/libexec/scylla-housekeeping", line 120, in get_repo_file
Nov 24 15:12:50 artifacts-oel81-jenkins-db-node-54d69e33-1 scylla-housekeeping[10720]:     with open(name, 'r') as myfile:
Nov 24 15:12:50 artifacts-oel81-jenkins-db-node-54d69e33-1 scylla-housekeeping[10720]: PermissionError: [Errno 13] Permission denied: '/etc/yum.repos.d/scylla-manager.repo'
Nov 24 15:12:50 artifacts-oel81-jenkins-db-node-54d69e33-1 systemd[1]: scylla-housekeeping-restart.service: Main process exited, code=exited, status=1/FAILURE
Nov 24 15:12:50 artifacts-oel81-jenkins-db-node-54d69e33-1 systemd[1]: scylla-housekeeping-restart.service: Failed with result 'exit-code'.
```
The housekeeping service couldn't send the status after restart.
We also checked the permissions of the affected files, and they all have `600` permissions.
```
[ec2-user@artifacts-oel81-jenkins-db-node-54d69e33-1 ~]$ ll /etc/yum.repos.d/
total 32
-rw-r--r--. 1 root root  252 Mar 19  2021 oracle-epel-ol8.repo
-rw-r--r--. 1 root root  233 Mar 18  2020 oraclelinux-developer-ol8.repo
-rw-r--r--. 1 root root 1339 Mar 18  2020 oracle-linux-ol8.repo
-rw-r--r--. 1 root root 2472 Nov 10 15:29 oracle-linux-ol8.repo.rpmnew
-rw-------. 1 root root  206 Nov 24 15:12 scylla-manager.repo
-rw-r--r--. 1 root root  379 Nov 24 15:06 scylla.repo
-rw-r--r--. 1 root root  470 Nov 10 20:25 uek-ol8.repo
-rw-r--r--. 1 root root  243 Nov 10 20:25 virt-ol8.repo
```
```
[ec2-user@artifacts-oel81-jenkins-db-node-54d69e33-1 ~]$ ll /var/lib/scylla-housekeeping/
total 4
-rw-------. 1 scylla-manager scylla 37 Nov 24 15:08 housekeeping.uuid
-rw-------. 1 scylla-manager scylla  0 Nov 24 15:13 housekeeping.uuid.marked
```
[system_oel81.log](https://github.com/scylladb/scylla/files/7602821/system_oel81.log)

This problem seems very similar to this one: https://github.com/scylladb/scylla/issues/8049

**Comment by syuu1228** [comment]
Same as #8049, this is because AMI image is modified.
The detail is here:
https://github.com/scylladb/scylla/issues/8049#issuecomment-778597917
So it modified umask settings to 077, all files created on this image become 600 (-rw-------).

Just like f96ea8e01182865e05bf189bfb0c2f4e287d4320, I think we need to fixup permission on the repo file before running scylla-housekeeping, if umask is not default mode.

**Comment by yaronkaikov** [comment]
@avikivity Can you please backport this to 4.6?

**Comment by avikivity** [comment]
Backported to 4.6. @syuu1228 does it need to be backported to 4.4, 4.5? I see it backports cleanly, why did we not have failures there?

**Comment by bentsi** [comment]
PR #9739 doesn't fix the issue and actually cause a bug (see comments in the PR)

**Comment by bentsi** [comment]
@avikivity need to reopen this

**Comment by avikivity** [comment]
Should I revert it? @syuu1228 please advise

**Comment by yaronkaikov** [comment]
@avikivity https://github.com/scylladb/scylla/pull/9802 should fix it. can you please review ?

**Comment by avikivity** [comment]
Backported to 4.6. Backporting to 4.5 depends on whether we want to backport ea20f89c5615db7c4456243a9c572357bc0d5d66.
