### ISSUE TITLE
raft: server: race between `wait_for_entry` and `abort` causes `broken_promise`

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#9688]
`abort()` sets `stopped_error` for everyone who waits on an entry to be applied or committed:
```
    for (auto& ac: _awaited_commits) {
        ac.second.done.set_exception(stopped_error());
    }
    for (auto& aa: _awaited_applies) {
        aa.second.done.set_exception(stopped_error());
    }
    _awaited_commits.clear();
    _awaited_applies.clear();
```

it may happen however that `wait_for_entry` is called after `abort`, causing a new waiter to be created.
This waiter's promise will be destroyed when `server_impl` is destroyed, giving a `broken_promise` exception to the waiter.

This `broken_promise` then propagates to external APIs such as `set_configuration` or `add_entry`.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
