### ISSUE TITLE
system.raft should use the regular dirty memory space

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#9692]
By default, tables in the system keyspace use the system dirty memory space. This space has a 10MB cap on capacity. This means that memtables cannot accumulate more than 5MB before they are flushed to sstables. This can impact performance under load.

I suggest that raft log is added to the regular dirty memory space, shared with user tables. This is controlled with `maybe_write_in_user_memory()` in system_keyspace.cc. For example, `system.paxos` is already there.

\cc @kostja @gleb-cloudius

**Comment by avikivity** [comment]
I think this should be reverted for group 0. Otherwise group0 will compete with user writes and may lose, under heavy load.

broadcast tables and user tables should keep it.
