### ISSUE TITLE
Overlapping is being introduced in level 1 of LCS during regular write activity

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#9693]
INFO  2021-11-27 16:42:28,546 [shard 0] LeveledManifest - Leveled compaction strategy is restoring invariant of level 1 by compacting 30 sstables on behalf of ks.standard1

That seems to be a regression introduced by commit 1f5b17fdc5, so no release is affected.

**Comment by avikivity** [comment]
No vulnerable branches, not backporting.
