### ISSUE TITLE
stop_compaction should wait for ongoing compactions to stop

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9695]
Similar to #9313, stop_compaction should also reuse the `stop_ongoing_comapctions()` infrastructure and wait on ongoing compactions of the given type to stop.

**Comment by bhalevy** [comment]
Captured also in https://github.com/scylladb/scylla/blob/1e2ecd282aa5467538b1e9814a2183038cf7776b/compaction/compaction_manager.cc#L1080 (see 4ce745e0b606463255b6f693bd6b4c79b84e8fea)

**Comment by bhalevy** [comment]
The reason I'd like to reuse `stop_ongoing_compactions` rather than `stop_tasks` is to reuse its filtering and logging logic and then to extend the `stop_compaction` api to get additional keyspace / table name options ().

**Comment by avikivity** [comment]
Not a bug, not backporting.
