### ISSUE TITLE
mutation_source::bool() is always false with flat_mutation_reader_v2 factories

### ISSUE THREAD

**Issue by cmm** [scylladb/scylla#9697]
because it only checks if it has a v1 factory

**Comment by cmm** [comment]
impact: I have a patch series in the works that, among other things, changes `memtable::as_data_source()` to return a `mution_source` with a v2 flat reader factory inside. that change broke at least one unit test because of this bug.  I don't know what this means re: back-ports -- if the plan is to back-port v1->v2 work to 4.6, then this should be back-ported too

**Comment by avikivity** [comment]
No plan to backport. But I ended up needing the patch too: https://github.com/scylladb/scylla/pull/9707
