### ISSUE TITLE
[CQL] Scylla is not erroring out a create table with repeated column definition

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#970]
I was checking the results of our version of cassandra-unit-tests, and found this error:

    Failed tests:   testTable(org.apache.cassandra.cql3.validation.operations.CreateTest): Query should be invalid but no error was thrown. Query is: CREATE TABLE table_1456860091400 (k int PRIMARY KEY, c int, k text)

This is a relatively new regression, introduced on build 82, Feb 26, 2016 10:55 PM.

**Comment by lmr** [comment]
Strangely, I can't reproduce it on my laptop's recently updated/compiled scylla tree, so this might have been just fixed with build 87 (waiting on confirmation).

**Comment by lmr** [comment]
Turns out my previous comment (which I deleted) was wrong, I was using another branch of the unit tests that had the offender test disabled. Re-running the tests shows the failure:

    Failed tests:   testTable(org.apache.cassandra.cql3.validation.operations.CreateTest): Query should be invalid but no error was thrown. Query is: CREATE TABLE table_1456873585882 (k int PRIMARY KEY, c int, k text)

**Comment by penberg** [comment]
Broken by https://github.com/scylladb/scylla/commit/8e2c924de3077f664c347333884999ee5f725c9c.

Fixed by https://github.com/scylladb/scylla/commit/3a6d43c784a65e400a372560cba933de7b647a3d.
