### ISSUE TITLE
Extend the compaction_manager/stop_compaction api with optional keyspace / table(s)

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9700]
For stopping a given compaction type (e.g. reshape) on particular keyspaces or tables.

Depends on #9699

**Comment by bhalevy** [comment]
This would be useful if one wants to stop a particular compaction type like RESHAPE on particular keyspaces/tables rather than on all and let it complete on others.

**Comment by avikivity** [comment]
Not a bug, not backporting.
