### ISSUE TITLE
Reconsider prometheus-protocol listening address in scylla.yaml

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#9701]
In the very recent commit 3c0e7037beb47028c5d539809e5c950dfde1c7a8, fixing issue #8757, we changed the default `prometheus_address` setting in `scylla.yaml` to _localhost_, to match the default setting of `rpc_address` (which affects the CQL and Thrift servers, but not the metrics server).

This is convenient for developers (this was #8757) but @tzach rightly pointed out that it also means that now actual users will need to remember to change both `rpc_address` and `prometheus_address` from their default, or their metrics will not be visible to their off-node monitoring. The problem is that our documentation mentions the need to set `rpc_address` in `scylla.yaml`, but **does not** mention the need to set `prometheus_address`. Our documents on `scylla.yaml`, such as https://docs.scylladb.com/operating-scylla/scylla-yaml/, don't even mention the existence of a the `prometheus_address` configuration option.

Here is an alternative, which would fix #8757 but not require updating documentation:

1.  Remove (comment out) the `prometheus_address` assignment from `scylla.yaml`.
2.  Change `main.cc` to set `prometheus_address` to the same as `rpc_address` if only the latter is set (in `scylla.yaml`).

This approach both fixes #8757 and avoids documentation changes or backward-incompatible behavior changes, because:

1. Users with existing configuration files will not see any change (their old `scylla.yaml` has `prometheus_address` set, so main will not override it).
2. Developers who use our unmodified `scylla.yaml` will have `rpc_address` set to `localhost` (this is what our `scylla.yaml` has) and therefore `prometheus_address` will be set to `localhost` too. This fixes #8757.
3. Real users who follow our documentation - take our `scylla.yaml` and modify just `rpc_address` to a real IP address (as suggested by the documentation), will also get `prometheus_address` set to the same thing - this is what a typical user would want (for the metrics to be visible).

CC @tzach @amnonh  @avikivity

**Comment by nyh** [comment]
Correction: The name `rpc_address` is very confusing and misleading - it has nothing to do with Scylla intra-node "RPC", but rather was named after the old Thrift protocol (whose original nickname in Cassandra) and now this configuration applies to **external** protocols - Thrift and CQL.
For Prometheus we should perhaps consider defaulting to `listen_address`, not to `rpc_address`. The `listen_address` is the address used for internal (intra-node) communication. It also defaults in `scylla.yaml` to `localhost`, but users have to set if for  proper functioning. In a setup where there is one network between the Scylla nodes and a different network between the Scylla nodes and the application - the monitoring node will most likely want to use the former, not latter, network.

So I think `prometheus_address` should copy `listen_address` (if set). Not `rpc_address`.

**Comment by amnonh** [comment]
> 
> So I think `prometheus_address` should copy `listen_address` (if set). Not `rpc_address`.

I agree to that, the `yml` file and the documentation should state that, though it's a reasonable behaviour, it may not be intuitive

**Comment by nyh** [comment]
No need to backport this fix if the previous fix in #8757 isn't backported - this was just a followup to that previous fix that came just a few days earlier.
