### ISSUE TITLE
testlib: sstable_test class read_indexes causes race condition after index reader fix

### ISSUE THREAD

**Issue by eliransin** [scylladb/scylla#9704]
Commit 9dce1e4b2b4d576ac31fadd7678b91f37914ab02 caused to some potential flakiness in `sstable_datafile_test` and specifically it was observed in `check_read_indexes`.
The problem is that some records can be left around while the index reader is destructed causing an assertion failure in this destructor.
The cause is that the `index_reader` is not closed before destructed.
As mentioned in the aforementioned commit only versions below 4.5 are volunerable.

**Comment by bhalevy** [comment]
ddd7248b3b6ff732b3d0e867b6dc3c5213ef969e landed in master and needs backport down to 4.4

Shouldn't the issue be closed and marked as Backport candidate?

Cc @eliransin @psarna

**Comment by avikivity** [comment]
How can an open issue be a backport candidate?

**Comment by eliransin** [comment]
The issue is open since the actual race happens only on 4.4 and earlier versions.
The fix for this issue is backporting ddd7248 (which will actually turn into an entirely different code but with the same concept).
I will prepare a backport PR that fixes this issue.

**Comment by eliransin** [comment]
fixed by 5375b8f (PR #9717 )

**Comment by avikivity** [comment]
@eliransin please confirm nothing is left to do. I removed the backport candidate label.
