### ISSUE TITLE
Request to add support for new AWS Im4gn/Is4gen instance types for Scylla setup

### ISSUE THREAD

**Issue by A-Posthuman** [scylladb/scylla#9711]
This is Scylla's bug tracker, to be used for reporting bugs only.
If you have a question about Scylla, and not a bug, please ask it in
our mailing-list at scylladb-dev@googlegroups.com or in our slack channel.

- [x] I have read the disclaimer above, and I am reporting a suspected malfunction in Scylla.

Hi, I'm requesting to add these new instance types for the setup/config process, thanks!

**Comment by slivne** [comment]
https://github.com/scylladb/scylla-machine-image/issues/258
