### ISSUE TITLE
multishard_mutation_query: stateful multi-range reads drop data

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#9718]
HEAD: 03755b362af07cc0c89ece61b3998a378cc518d0

During a stateful multishard read, individual shard readers are saved at the end of the page, so the next page can pick them up and continue from where it left off. The multishard combining reader -- the reader combining the output of the individual shard readers -- is not saved. Instead it is disassembled: its buffer is extracted and fragments are pushed back to the shard reader they originate from. This process has a major bug in it when multiple ranges are involved. When this happens, the multishard reader is wrapped in a multi-range reader, which fast-forwards it between the ranges. The above buffer extraction mechanism then fails because only the buffer of the top-level reader is extracted, which for multi-range reads is the multi-range reader. The data in the underlying multishard reader's buffer is discarded. This leaves a whole in the data, which completely confuses the reading logic, causing anything from data being left out, to data being repeated.
This code path is not used nor tested currently hence the reason it could go undetected until now. Found while writing an exploratory unit-test for a related multi-range multishard read issue (#6716).

**Comment by denesb** [comment]
Further confusion of the reading logic is caused by the fact that the multi-range reader seamlessly crosses between ranges, sometimes yielding buffers, which are from two consecutive ranges. If the page happens to be cut at this point, just right, we will push back data to the shard readers that is outside of their read range because they are fast-forwarded past the range that yielded the pushed-back data.

**Comment by avikivity** [comment]
@denesb does this need to be backported to 4.6?

**Comment by denesb** [comment]
I checked the two users of this buggy code I knew about: ttl and distributed aggregate queries and neither exists in 4.6. AFAIK there is no user of this code pre 5.0 which is the reason the bug could hide for so long (and which is the reason we shouldn't really have unused features in the code - they just rot).

**Comment by avikivity** [comment]
Removed backport candidate label.
