### ISSUE TITLE
Compile so slowly

### ISSUE THREAD

**Issue by EricYT** [scylladb/scylla#972]
When I modify the database.cc or database.hh, it will spend a long long time to build again. Is there a way to reduce the time? Because so many templates be used ?
Thanks.

**Comment by nyh** [comment]
This is a duplicate of issue #1 :-)

**Comment by avikivity** [comment]
We hope that C++17 modules will help in reducing compile time.

See http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2015/n4465.pdf.
