### ISSUE TITLE
ARM64 build is broken: `redefinition of 'scalar_function'`

### ISSUE THREAD

**Issue by athre0z** [scylladb/scylla#9726]
I'm running a Debian Testing VM on my M1 MacBook, attempting to build latest master (4a02e312f6b932aa371b05c7f662a9ca268a6715) from source using the instructions in the README:

```console
$ git submodule update --init --force --recursive
$ ./tools/toolchain/dbuild ./configure.py
$ ./tools/toolchain/dbuild ninja build/release/scylla
```

It's failing with:

```
In file included from cql3/functions/functions.cc:36:
In file included from cql3/functions/as_json_function.hh:45:
./cql3/functions/scalar_function.hh:52:7: error: redefinition of 'scalar_function'
class scalar_function : public virtual function {
      ^
cql3/functions/scalar_function.hh:52:7: note: previous definition is here
class scalar_function : public virtual function {
      ^
1 error generated.
```

Executing the same instructions on an AMD64 machine works just fine.

**Comment by avikivity** [comment]
That is odd. scalar_function.hh has `#pragma once` which should prevent the error.

**Comment by avikivity** [comment]
Doesn't reproduce for me. Please check that ./cql3/functions/scalar_function.hh line 42 has `#pragma once`, maybe the file was corrupted.

**Comment by athre0z** [comment]
Ok -- turns out it was related to the source living on a network share. For some reason, this rendered clang unable to detect that the same file was included twice. Thanks for taking and look and sorry for the noise!
