### ISSUE TITLE
lsa-timing reports bad units

### ISSUE THREAD

**Issue by avikivity** [scylladb/scylla#9733]
```
lsa-timing - Reclamation cycle took 8000021 ms, trying to release 0.756 MiB preemptibly
```

The time is actually in nanoseconds (so it's 8ms).

**Comment by bhalevy** [comment]
Cc @cmm

**Comment by bhalevy** [comment]
Refs https://github.com/scylladb/scylla/issues/4186

**Comment by avikivity** [comment]
Already backported to all vulnerable branches, removing "Backport candidate" label.
