### ISSUE TITLE
Add metrics for operations between nodes and between DCs

### ISSUE THREAD

**Issue by tzach** [scylladb/scylla#974]
Scylla already report metrics for CQL operations and local storage.
It will be useful to count operations between nodes and between DCs. 
The separation between the two is relevant, as cross DC connections are slower, and have different cost (for example between EC2 regions)

**Comment by slivne** [comment]
additional info in "metrics for throughput between nodes and DC"

**Comment by vladzcloudius** [comment]
This issue is fixed by a commit f6da9bc92bdbd93980101939628ccc2488c4eb97
@tzach could u close it please.
