### ISSUE TITLE
Convert test/redis/run to Python and avoid code duplication

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#9748]
The shell script `test/redis/run` started as a copy of the scripts `test/alternator/run` and `test/cql-pytest/run`, but since then the latter two evolved to be Python (instead of shell) and have the main Scylla-starting logic only in one place - `test/cql-pytest/run.py`.

We should do the same for `test/redis/run` - like `test/alternator/run` it should import the `run.py` library and use it to start Scylla with some additional redis-specific parameters.

FYI @bhalevy

**Comment by avikivity** [comment]
Not a bug, not backporting.
