### ISSUE TITLE
un-nest no_such_keyspace and no_such_column_family in database::find_* functions

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9753]
See https://github.com/scylladb/scylla/issues/9747#issuecomment-987773533

The the nested exception were introduced back in d3fe0c5
but they don't make sense.

Cc @elcallio who authored the original patch.
Cc @nyh (https://github.com/scylladb/scylla/issues/9747#issuecomment-987780201).

**Comment by avikivity** [comment]
Not a bug, not backporting.
