### ISSUE TITLE
api/storage_service: not-found tables should throw bad_param_exception

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9754]
Currently, we don't validate table names passed to the storage_service api calls.
Non-existing table names end up in db.find_column_family that throws (nested, see #9753) `no_such_column_family` exceptions
and those turn into `internal_server_error` http response status codes.

Instead, we need to validate the `cf` query param value and throw a `bad_param_exception` similar to the one thrown in `validate_keyspace()` that is derived from `bad_request_exception` and yields the correct `reply::status_type::bad_request`.

See https://github.com/scylladb/scylla/issues/9747#issuecomment-987811038

The difference between them is that `bad_request` indicates a problem with the request itself and shouldn't be retried, while `internal_server_error` indicates a problem on the server side and can/should be retried.

For example, after validating the table names, we could fail to find a table via its uuid if, for example, it was deleted mid-way.
That would correctly indicate an internal server error, so hitting no_such_column_family after the validation point *should* be translated to `internal_server_error` status code.

**Comment by bhalevy** [comment]
Cc @nyh

**Comment by avikivity** [comment]
Minor, and not a regression, not backporting.
