### ISSUE TITLE
Logs are spammed with a lot of error messages when table is dropped during streaming

### ISSUE THREAD

**Issue by tgrabiec** [scylladb/scylla#976]
I think the expected behavior is to log a failure and abort streaming as soon as this is detected.

This can be reproduced using dtest `update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_add_new_node_while_schema_changes_test`. 

I increased the number of written partitions from 4000 to 400000 to make the condition trigger with higher probability.

Excerpt from logs:
```
INFO  2016-03-02 13:18:34,976 [shard 0] stream_session - [Stream #e1b34790-e070-11e5-9311-000000000000] remote node 127.0.0.4:0 does not have 
the cf_id = 0fec1fc0-e070-11e5-ad1a-000000000000
INFO  2016-03-02 13:18:34,977 [shard 0] stream_session - [Stream #e1b34790-e070-11e5-9311-000000000000] remote node 127.0.0.4:0 does not have 
the cf_id = 0fec1fc0-e070-11e5-ad1a-000000000000
INFO  2016-03-02 13:18:34,977 [shard 0] stream_session - [Stream #e1b34790-e070-11e5-9311-000000000000] remote node 127.0.0.4:0 does not have 
the cf_id = 0fec1fc0-e070-11e5-ad1a-000000000000
INFO  2016-03-02 13:18:34,977 [shard 0] stream_session - [Stream #e1b34790-e070-11e5-9311-000000000000] remote node 127.0.0.4:0 does not have 
the cf_id = 0fec1fc0-e070-11e5-ad1a-000000000000
INFO  2016-03-02 13:18:34,977 [shard 0] stream_session - [Stream #e1b34790-e070-11e5-9311-000000000000] remote node 127.0.0.4:0 does not have 
the cf_id = 0fec1fc0-e070-11e5-ad1a-000000000000
INFO  2016-03-02 13:18:34,977 [shard 0] stream_session - [Stream #e1b34790-e070-11e5-9311-000000000000] remote node 127.0.0.4:0 does not have 
the cf_id = 0fec1fc0-e070-11e5-ad1a-000000000000
```

**Comment by penberg** [comment]
ping @asias

**Comment by asias** [comment]
@tgrabiec if a cf is dropped after the streaming starts, I think it is fine to ignore the fact the remote peer does not have the cf anymore and continue the streaming, since the cf is deleted anyway, we can skip sending the missing cf.

**Comment by tgrabiec** [comment]
@asias Yes. But we should make sure we distinguish the case where the table is deleted after streaming starts from the case where the table is not deleted but the remote node is missing for some reason the fact that it exists.

**Comment by asias** [comment]
@tgrabiec in the prepare phase of streaming, we check that remote node has all the cf_id which are needed for the entire streaming, both the cf_id which local node will send to remote node and wise versa. 

So, at later time, if the cf_is is missing, it must be that the cf_id is deleted.

**Comment by slivne** [comment]
@asias / @tgrabiec  aside from excessive logging - is there a side effect - if not we may defer this to yellowfin (we have other items with "higher priority).

In any case I suggest to add a test to cover this so we will have such a case in regression (if one does not exist). @asias you have added add_table while streaming can you add tests for this as well.

**Comment by asias** [comment]
Patches are sent.
