### ISSUE TITLE
storage_service: Future from seastar::get_units is not waited in node_ops_update_heartbeat and friends

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#9767]
We need to wait for the futures returned from seastar::get_units.

**Comment by asias** [comment]
We need to backport the fix to 4.5 and 4.6.

**Comment by asias** [comment]
Fix is sent: https://github.com/scylladb/scylla/pull/9768

**Comment by avikivity** [comment]
I'll backport, but please update the description with impact. We can't tell a user they need to upgrade because we didn't wait for a future, it means nothing to them.

**Comment by avikivity** [comment]
Backported to 4.5, 4.6.

**Comment by asias** [comment]
> I'll backport, but please update the description with impact. We can't tell a user they need to upgrade because we didn't wait for a future, it means nothing to them.

Without waiting for the get_units for the semaphore, storage_service::node_ops_abort operation is not serialized. As a result, the same node operation can be aborted more than once which can cause undefined behavior.

**Comment by denesb** [comment]
Forgotten label, removing.
