### ISSUE TITLE
commitlog uses get_units() without waiting for it

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#9770]
In commit dcc73c5d4e2dc25948055365cb80c859f0b7a2d1 (by @elcallio), the following code was introduced in two places to db/commitlog/commitlog.cc:

```c++
            auto guard = get_units(_reserve_recalculation_guard, 1);
```

`get_units()` returns a future - this code never waits for the units to become available, so its goal of guaranteeing that only one fiber does this recalculation in parallel is not achieved.

The trivial fix is probably to add "co_await".

Please note that the same alleged mistake appears **in two places** in the code.

**Comment by nyh** [comment]
@elcallio the fix is trivial, and I can easily send a patch myself, but I want to also understand what this bug might have caused if not fixed (this will be useful, among other things, if want to mention this in a change-log or something). And this I don't know how to do which is why I prefer that you do it. Thanks.

**Comment by slivne** [comment]
@avikivity / @nyh I think we need this backported to 4.6 as well - the original commit by calle was backported to 4.6 here 11bb03e46d1d2a6f400bd74b08a523853df24468,

**Comment by avikivity** [comment]
Good catch. Backported to 4.6.

**Comment by elcallio** [comment]
Yeah, red face. The first is copy error on my part, the second brain-dead copy-paste. No excuse. Please commit and backport.
