### ISSUE TITLE
nodetool checkAndRepairCdcStreams shouldn't fail when there are nodes in LEFT state

### ISSUE THREAD

**Issue by haaawk** [scylladb/scylla#9771]
At the moment, `nodetool checkAndRepairCdcStreams` expects all nodes to be in NORMAL state. That means it fails if run shortly after a node is decommissioned. Let's make `nodetool checkAndRepairCdcStreams` work when all nodes are in either NORMAL or LEFT state.

Example error:
```
# nodetool checkAndRepairCdcStreams 
Using /etc/scylla/scylla.yaml as the config file

nodetool: Scylla API server HTTP POST to URL '/storage_service/cdc_streams_check_and_repair' failed: std::runtime_error (All nodes must be in NORMAL state while performing check_and_repair_cdc_streams (172.17.0.5 is in state LEFT))
See 'nodetool help' or 'nodetool help <command>'.
```

**Comment by avikivity** [comment]
Backported to 4.6 (5.0, 5.1 have it).
