### ISSUE TITLE
build: dist-deb target failing (in Fedora 34) after a recent update of debhelper

### ISSUE THREAD

**Issue by michoecho** [scylladb/scylla#9781]
With the most recent version of debhelper on Fedora, the `debuild` step fails with `error: maintainer script 'postinst' has bad permissions 1363`.
The problem is not present in debhelper 13.3.4, which is the version used in the current version of the frozen toolchain.

I have found another account of a similar problem here: https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1814310.html

This might be a debhelper issue rather than a Scylla issue, but I'm recording it here for reference.

**Comment by avikivity** [comment]
It appears to be fixed in a patch (but not the main repo):

https://www.mail-archive.com/debian-devel-changes@lists.debian.org/msg704723.html

**Comment by avikivity** [comment]
I filed https://bugzilla.redhat.com/show_bug.cgi?id=2031534.

**Comment by avikivity** [comment]
Fixed, updated packages in the updates-testing repository and should hit updates in about a week.
