### ISSUE TITLE
Issue in page Repair based node operations

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#9786]
I would like to report an issue in page https://scylla.docs.scylladb.com/master/design-notes/repair_based_node_ops

### Problem

Maybe small typo here:

```
Rebuild operation

It is used to get all the data this node owns form other existing nodes. It pulls data from only one of the replicas which might not be the latest copy.
```

###  Suggest a fix
"node owns `form` other existing nodes." - > "node owns `from` other existing nodes."

**Comment by tzach** [comment]
Look like  doc issue. Please reopen in https://github.com/scylladb/scylla-docs

**Comment by juliayakovlev** [comment]
@tzach 
I used "Report a doc issue" to open this one and didn't pay attention that it opened in scylla, not in the doc. So we have GUI issue. Where can I open it?

**Comment by juliayakovlev** [comment]
Opened: https://github.com/scylladb/scylla-docs/issues/3843

**Comment by tzach** [comment]
The issue is in the right project! 
You are pointing to an in-tree design doc. Sorry for misleading you.
