### ISSUE TITLE
Scylla failed to start with --enable-repair-based-node-ops option, error: unrecognised option 

### ISSUE THREAD

**Issue by juliayakovlev** [scylladb/scylla#9792]
*Installation details*
Scylla version (or git commit hash): 4.7.dev-0.20211213.b0a8c153f with build-id d1ede34a76252641bc065ab876b36fefb9e5c8fc
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): s3://downloads.scylladb.com/unstable/scylla/master/relocatable/2021-12-13T23:12:07Z/

Try to start the node with command args:
```
/home/juliaj/.dtest/dtest-bbrgwts_/test/node1/bin/scylla --options-file /home/juliaj/.dtest/dtest-bbrgwts_/test/node1/conf/scylla.yaml --log-to-stdout 1 --enable-repair-based-node-ops false --api-address 127.0.71.1 --collectd-hostname juliaj-scylladb.node1 --developer-mode true --smp 1 --memory 512M --default-log-level info --collectd 0 --overprovisioned --prometheus-address 127.0.71.1 --unsafe-bypass-fsync 1 --kernel-page-cache 1 --max-networking-io-control-blocks 1000
```

The node failed to start with error:
```
error: unrecognised option '--enable-repair-based-node-ops false'
```

But if I don't set argument for the option `--enable-repair-based-node-ops`, like:
```
scylla --options-file conf/scylla.yaml --log-to-stdout 1 --enable-repair-based-node-ops --api-address 127.0.71.1 --collectd-hostname juliaj-scylladb.node1 --developer-mode true --smp 1 --memory 512M --default-log-level info --collectd 0 --overprovisioned --prometheus-address 127.0.71.1 --unsafe-bypass-fsync 1 --kernel-page-cache 1 --max-networking-io-control-blocks 1000
```

I get exception:
```
FATAL: Exception during startup, aborting: boost::wrapexcept<boost::program_options::invalid_bool_value> (the argument ('--api-address') for option '--enable-repair-based-node-ops' is invalid. Valid choices are 'on|off', 'yes|no', '1|0' and 'true|false')
```

So the option `enable-repair-based-node-ops` is known, but from some reason it failed to recognoze it. 
This option is not in the scylla.yaml template. Maybe this is the problem?

**Comment by bhalevy** [comment]
> _Installation details_ Scylla version (or git commit hash): 4.7.dev-0.20211213.b0a8c153f with build-id d1ede34a76252641bc065ab876b36fefb9e5c8fc Cluster size: OS (RHEL/CentOS/Ubuntu/AWS AMI): s3://downloads.scylladb.com/unstable/scylla/master/relocatable/2021-12-13T23:12:07Z/
> 
> Try to start the node with command args:
> 
> ```
> /home/juliaj/.dtest/dtest-bbrgwts_/test/node1/bin/scylla --options-file /home/juliaj/.dtest/dtest-bbrgwts_/test/node1/conf/scylla.yaml --log-to-stdout 1 --enable-repair-based-node-ops false --api-address 127.0.71.1 --collectd-hostname juliaj-scylladb.node1 --developer-mode true --smp 1 --memory 512M --default-log-level info --collectd 0 --overprovisioned --prometheus-address 127.0.71.1 --unsafe-bypass-fsync 1 --kernel-page-cache 1 --max-networking-io-control-blocks 1000
> ```
> 
> The node failed to start with error:
> 
> ```
> error: unrecognised option '--enable-repair-based-node-ops false'
> ```

@juliayakovlev the issue seems like on the test side, not scylla's.
The error indicates that the option and its argument are parsed as a single option that ends with ` false`.
Please check how you quote your options since they were glued together.

**Comment by juliayakovlev** [comment]
> > _Installation details_ Scylla version (or git commit hash): 4.7.dev-0.20211213.b0a8c153f with build-id d1ede34a76252641bc065ab876b36fefb9e5c8fc Cluster size: OS (RHEL/CentOS/Ubuntu/AWS AMI): s3://downloads.scylladb.com/unstable/scylla/master/relocatable/2021-12-13T23:12:07Z/
> > Try to start the node with command args:
> > ```
> > /home/juliaj/.dtest/dtest-bbrgwts_/test/node1/bin/scylla --options-file /home/juliaj/.dtest/dtest-bbrgwts_/test/node1/conf/scylla.yaml --log-to-stdout 1 --enable-repair-based-node-ops false --api-address 127.0.71.1 --collectd-hostname juliaj-scylladb.node1 --developer-mode true --smp 1 --memory 512M --default-log-level info --collectd 0 --overprovisioned --prometheus-address 127.0.71.1 --unsafe-bypass-fsync 1 --kernel-page-cache 1 --max-networking-io-control-blocks 1000
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The node failed to start with error:
> > ```
> > error: unrecognised option '--enable-repair-based-node-ops false'
> > ```
> 
> @juliayakovlev the issue seems like on the test side, not scylla's. The error indicates that the option and its argument are parsed as a single option that ends with ` false`. Please check how you quote your options since they were glued together.

Yes, it's test issue. Please, close it
