### ISSUE TITLE
Scylla started reporting 'commitlog - Could not delete segment' during end of space test

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla#9798]
We have nemesis called `EnospcMonkey` which is drives one node (or all nodes, but it is not this case) to the end of space state
We had it for a long time without a change, but on 4.7 it started reporting error that we not seen before:

```
2021-12-09T14:35:14+00:00 gemini-1tb-10h-master-db-node-fa0623fd-3 !     ERR |  [shard 6] commitlog - Could not delete segment /var/lib/scylla/hints/6/10.0.1.133/HintsLog-2-108086391068481510.log: std::filesystem::__cxx11::filesystem_error (error system:2, filesystem error: stat failed: No such file or directory [/var/lib/scylla/hints/6/10.0.1.133/HintsLog-2-108086391068481510.log])
```

This issue is to confirm weather it is expected error in given context or we stumbled at something unexpected.

*Installation details*
Scylla version (or git commit hash): v4.7.dev-0.20211126.44f4ea38c with build-id a88083cca1208179dd36a3847af403f77ad794f0 (ami-0238a987fdfc50310)
Cluster size: 6
OS (RHEL/CentOS/Ubuntu/AWS AMI): ami-0238a987fdfc50310
Disks: NVMe

**Comment by elcallio** [comment]
This is a sort-of benign error caused by the `commit_error_handler` (i.e. `default_io_error_handler`) swallowing everything that is `std::system_error`. This is probably not what we want when failing to allocate a segment. We need to grab the error pointer in both cases in `allocate_segment_ex`.

**Comment by slivne** [comment]
based on @elcallio request we need to backport this for https://github.com/scylladb/scylla/issues/9152

**Comment by slivne** [comment]
@avikivity ^^

**Comment by avikivity** [comment]
Backported to 4.6, only vulnerable branch.
