### ISSUE TITLE
reloc: rename the package to align arch convention 

### ISSUE THREAD

**Issue by benipeled** [scylladb/scylla#9799]
`arch` was added to the package name as part of https://github.com/scylladb/scylla/pull/8709 but the convention
is weird and not-common - `scylla-aarch64-package.tar.gz`,

We should align the convention to other package conventions when the arch is a suffix
before the dot, ex. <arch>.rpm <arch>.tar.gz, which means in this case - `scylla-package-aarch64.tar.gz`

**Comment by benipeled** [comment]
@syuu1228 @avikivity please review https://github.com/scylladb/scylla-python3/pull/24 and  https://github.com/scylladb/scylla/pull/9813,

If no problem with these changes - please approve and **wait with the merge** - I'll prepare the required changes on pkg pipelines,

@fruch AFAIK you've recently made a few changes around package names on SCT - please take this change into account.

**Comment by syuu1228** [comment]
When we introduced arch name in relocatable package, I suggested ${package name}-package.${arch}.tar.gz in the beginning but we choosed ${package name}-${arch}-package.tar.gz:
https://github.com/scylladb/scylla/pull/8709

@avikivity What do you think?

**Comment by benipeled** [comment]
@syuu1228 I tried to avoid mentioning that discussion but if you've already raised it :) - your suggestion of
`${package name}-package.${arch}.tar.gz` makes a lot more sense,

AFAIU, the decision was made following the MINGW project which for some reason uses a different
convention,

It's not the most priority change but IMO we should change it before the 4.6 GA release.

**Comment by syuu1228** [comment]
@avikivity Please comment on this, do we want change the package filename or keep current one.

**Comment by avikivity** [comment]
I guess `.` makes more sense, rpm and deb use it too.

We should also put the version string in there. So scylla-{release}-{version}.{arch}.tar.gz (we can drop "package"). This should be for the unified package.
