### ISSUE TITLE
[RPM test] Latest built RPM fails to start scylla service

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#980]
With the latest Fedora RPM, we have the following result when trying to start scylla.service:

    15:55:31 process          L0362 DEBUG| [stderr] A dependency job for scylla-server.service failed. See 'journalctl -xe' for details.
    15:55:31 service          L0369 DEBUG| Command: systemctl start scylla-server.service
    Exit status: 1
    Duration: 12.6856069565
    Stdout:

    Stderr:
    A dependency job for scylla-server.service failed. See 'journalctl -xe' for details.

The relevant scylla package versions:

    15:53:15 process          L0362 DEBUG| [stdout]  scylla-server  x86_64   666.development-20160301.4279ab4.fc22
    15:53:36 process          L0362 DEBUG| [stdout]  scylla-jmx     noarch   666.development-20160301.00a62ca.fc22    
    15:53:54 process          L0362 DEBUG| [stdout]  scylla-tools   noarch   0.10-20160301.1a32d9f.fc22

**Comment by lmr** [comment]
Unfortunately, I did not forsee the need of journalctl -xe in the test, so I need to add that to the test suite.

**Comment by slivne** [comment]
I am rebuilding the fedora RPMS after avi's fix bec30ccf2504d01f6957faeca55787e01f08e10e
If successful - It will start a sanity test - will update once done

**Comment by lmr** [comment]
I found out that iotune is dumping core, filling up the vm disk, then making the service unable to build.

I'll have to do some manual testing here to retrieve the core dump.

**Comment by lmr** [comment]
Mar 03 14:10:48 atest-guest scylla_io_setup[1257]: Generating evaluation file...terminate called after throwing an instance of 'std::system_error'
    Mar 03 14:10:48 atest-guest scylla_io_setup[1257]: what():  No space left on device
    Mar 03 14:10:48 atest-guest audit[1265]: <audit-1701> auid=4294967295 uid=0 gid=0 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 pid=1265 comm="iotune" exe="/usr/bin/i
    Mar 03 14:10:48 atest-guest auditd[493]: Audit daemon is low on disk space for logging
    Mar 03 14:10:48 atest-guest auditd[493]: Audit daemon is suspending logging due to low disk space.
    Mar 03 14:10:48 atest-guest systemd-coredump[1278]: Failed to create coredump file /var/lib/systemd/coredump/.#core.iotune.0.c39c764333404bc9a9af7aa87c048d7c.1265.14570322480000009c8
    Mar 03 14:10:48 atest-guest systemd-coredump[1278]: Process 1265 (iotune) of user 0 dumped core.
    -- Subject: Process 1265 (iotune) dumped core
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- Documentation: man:core(5)
    -- 
    -- Process 1265 (iotune) crashed and dumped core.
    -- 
    -- This usually indicates a programming error in the crashing program and
    -- should be reported to its vendor as a bug.
    Mar 03 14:10:48 atest-guest systemd[1]: scylla-io-setup.service: main process exited, code=exited, status=134/n/a
    Mar 03 14:10:48 atest-guest systemd[1]: Failed to start Scylla IO Setup.
    -- Subject: Unit scylla-io-setup.service has failed
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit scylla-io-setup.service has failed.
    -- 
    -- The result is failed.
    Mar 03 14:10:48 atest-guest systemd[1]: Dependency failed for Scylla Server.
    -- Subject: Unit scylla-server.service has failed
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit scylla-server.service has failed.

Trying to execute iotune manually:

    iotune --evaluation-directory /var/lib/scylla --format envfile --options-file /etc/scylla.d/io.conf
    Generating evaluation file...terminate called after throwing an instance of 'std::system_error'
      what():  No space left on device
    Aborted (core dumped)

**Comment by slivne** [comment]
@lmr what is the soze of the disl of the vm and how much free space does it have

**Comment by lmr** [comment]
9 GB. I'm looking into resizing the disk.

**Comment by slivne** [comment]
How much free space i think the file size iotune generates is 1G @glommer ?

Maybe iotune should check the free space and not use more then 50% of it

**Comment by syuu1228** [comment]
I've got same result when I tested iotune on AWS, when instance size was
8GB (10GB was okay).
It should output error & exit when disk size is not enough, instead of
trying to write data to test dir.

**Comment by lmr** [comment]
After well over 1 hour of reading things and banging my head against the wall, I finally was able to resize the partition on the fedora vm:

    Filesystem                            Size  Used Avail Use% Mounted on
    devtmpfs                              2.1G     0  2.1G   0% /dev
    tmpfs                                 2.1G     0  2.1G   0% /dev/shm
    tmpfs                                 2.1G  472k  2.1G   1% /run
    tmpfs                                 2.1G     0  2.1G   0% /sys/fs/cgroup
    /dev/mapper/fedora_atest--guest-root   42G  1.3G   41G   4% /
    /dev/vda1                             500M  126M  344M  27% /boot
    tmpfs                                 415M     0  415M   0% /run/user/0

Now I'm going to create a snapshot and re-test it. If all goes well, I'll do the same with the CentOS VM. Yay.

**Comment by lmr** [comment]
OK, that was the problem (lack of space for iotune to work its magic). 

As @syuu1228 mentioned, iotune should check available space before trying to write files, and error instead of trying to straight out write to disk. At least now we have a root cause, and a possible solution (better error handling). @glommer, please take a look at this issue.

I guess with Ubuntu I was lucky enough to create the disk slightly bigger so it didn't hit the problem. I'm going to resize the centos disk image and re-run the tests when all is done.

**Comment by glommer** [comment]
On Thu, Mar 3, 2016 at 4:15 PM, Lucas Meneghel Rodrigues <
notifications@github.com> wrote:

> OK, that was the problem (lack of space for iotune to work its magic).
>
> As @syuu1228 <https://github.com/syuu1228> mentioned, iotune should check
> available space before trying to write files, and error instead of trying
> to straight out write to disk. At least now we have a root cause, and a
> possible solution (better error handling). @glommer
> <https://github.com/glommer>, please take a look at this issue.
>

Can you open a bug and have Shlomi assign it to me?

When I'm in debug mode like I am now it is unfortunately too easy for me to
remember to look at stuff =(

**Comment by glommer** [comment]
On Thu, Mar 3, 2016 at 4:17 PM, Glauber Costa <glauber@scylladb.com> wrote:

>
>
> On Thu, Mar 3, 2016 at 4:15 PM, Lucas Meneghel Rodrigues <
> notifications@github.com> wrote:
>
>> OK, that was the problem (lack of space for iotune to work its magic).
>>
>> As @syuu1228 <https://github.com/syuu1228> mentioned, iotune should
>> check available space before trying to write files, and error instead of
>> trying to straight out write to disk. At least now we have a root cause,
>> and a possible solution (better error handling). @glommer
>> <https://github.com/glommer>, please take a look at this issue.
>>
>
> Can you open a bug and have Shlomi assign it to me?
>
> When I'm in debug mode like I am now it is unfortunately too easy for me
> to remember to look at stuff =(
>

But one more thing:

Please note that iotune is supposed to be ran in the actual data partition
the data will end up at.

Is that really less than 10G in space??

**Comment by lmr** [comment]
It was less than 10G, mainly because it's a smoke test and worked so far. About where iotune runs, that's on the service scripts, so we'd either need @syuu1228, or I can take a look afterwards. Right now I am fixing the test setup.

**Comment by lmr** [comment]
@glommer, I've opened a bug as you requested, #986.

**Comment by slivne** [comment]
In case there is no 10GB of free space we need to decide what do we do:
 - do we use a smaller file 
- do we provide a preset low value
- do we force the user to select either a small value or enabling developer-mode

**Comment by slivne** [comment]
There are patches on the mailing list that need to be merged

**Comment by lmr** [comment]
This problem was fixed as of the latest 1.0-rc1 rpms, so I'm closing this issue.
