### ISSUE TITLE
Better repair memory usage tracking and oom protection

### ISSUE THREAD

**Issue by asias** [scylladb/scylla#9817]
Currently, the repair parallelism is calculated by the number of memory
allocated to repair and memory usage per repair instance. However, the
memory usage per repair instance does not take the max possible memory
usage caused by repair followers.

As a result, when repairing a table with more replication factors, e.g.,
3 DCs, each has 3 replicas, the repair master node would use 9X repair
buffer size in worse cases. This would cause OOM when the system is
under pressure.

**Comment by bhalevy** [comment]
@slivne according to FE this issue should be high priority and be fixed in the nearest release (and backported)

**Comment by avikivity** [comment]
Not a regression, not backporting.
