### ISSUE TITLE
iotune link against libstdc++.so.6 even --static-stdc++ specifiied to configure.py

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#982]
Because we uses seastar's configure.py to build iotune, --static-stdc++ does not affect for iotune.
This breaks Ubuntu package (become impossible to install on Ubuntu 14.04LTS, since we are using different version of libstdc++ to build scylla/seastar, to use newer g++ package).

**Comment by penberg** [comment]
@slivne Do we want this for 0.18?

**Comment by slivne** [comment]
I don't think iotune is part of 0.18
