### ISSUE TITLE
systemd-coredump@.service should be tuned to not failed due to timeout 

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#9837]
### What environment are you running on?

Production

### Does the issue always reproduce?

Yes

### What steps will reproduce the problem?

1. Scylla failed for some reason
2. systemd-coredump failed to save coredump due to timeout
```
support@ip-1:~$ sudo journalctl -u systemd-coredump@4-1253335-0.service
-- Logs begin at Wed 2021-12-08 17:51:54 UTC, end at Tue 2021-12-21 21:20:25 UTC. --
Dec 21 07:07:49 ip-1 systemd[1]: Started Process Core Dump (PID 1253335/UID 0).
Dec 21 07:12:49 ip-1 systemd[1]: systemd-coredump@4-1253335-0.service: Service reached runtime time limit. Stopping.
Dec 21 07:12:53 ip-1 systemd[1]: systemd-coredump@4-1253335-0.service: Failed with result 'timeout'.
```

### What is the expected result?
core dump should be created

### What happens instead?
systemd-coredump failed due to timeout

### Additional information

I think we can fix like this:
- sudo mkdir -p /etc/systemd/system/systemd-coredump@.service.d/
- echo -e "[Service]\nTimeoutStartSec=20m" | sudo cat > /etc/systemd/system/systemd-coredump@.service.d/override.conf
- sudo systemctl daemon-reload

###

**Comment by slivne** [comment]
@syuu1228 is this a change dur to the moved from centos7 to ubuntu20.04 - its strange we are hitting this only now

**Comment by syuu1228** [comment]
> @syuu1228 is this a change dur to the moved from centos7 to ubuntu20.04 - its strange we are hitting this only now

On CentOS7, systemd-coredump does not have systemd unit file, it just executed by kernel when the process creashed:
```
[vagrant@localhost ~]$ rpm -ql systemd|grep coredump
/etc/systemd/coredump.conf
/usr/bin/coredumpctl
/usr/bin/systemd-coredumpctl
/usr/lib/systemd/systemd-coredump
/usr/share/bash-completion/completions/coredumpctl
/usr/share/man/man1/coredumpctl.1.gz
/usr/share/man/man5/coredump.conf.5.gz
/usr/share/man/man5/coredump.conf.d.5.gz
/usr/share/man/man8/systemd-coredump.8.gz
/usr/share/zsh/site-functions/_coredumpctl
/var/lib/systemd/coredump
```

But on Ubuntu 20.04 it has systemd unit for systemd-coredump:
```
vagrant@vagrant:~$ dpkg -L systemd-coredump|grep /lib/systemd
/lib/systemd
/lib/systemd/system
/lib/systemd/system/sockets.target.wants
/lib/systemd/system/systemd-coredump.socket
/lib/systemd/system/systemd-coredump@.service
/lib/systemd/systemd-coredump
/lib/systemd/system/sockets.target.wants/systemd-coredump.socket
```
Probably the difference comes from systemd version, since CentOS7 uses very old version.

**Comment by syuu1228** [comment]
I will send a fix for this.
