### ISSUE TITLE
Implement ordered partitions

### ISSUE THREAD

**Issue by ddorian** [scylladb/scylla#984]
Implement ordered partitions that cassandra has but hopefully more efficient/scalable.
From https://groups.google.com/forum/#!topic/scylladb-users/e4ffDPwU6hQ

**Comment by tzach** [comment]
Fixed by 9c27b5c.
Duplication of #1378

**Comment by ddorian** [comment]
But whats committed is still the 'old unrecommended way' right ?

**Comment by ddorian** [comment]
This was fixed (kinda wrong fix since cassandra had already suggesting to not use it) and then was depreciated. 

So open again ?

**Comment by ddorian** [comment]
It's the bigtable/hbase usecases.
Unbounded partitions (+ efficient scans on them and better compression compared to scattering the rows)

Better range scans on unbounded partitions. Better range-scans on secondary-indexes/materialized-views.
etc

**Comment by avikivity** [comment]
Better in what way?

We have plans to make range scans token aware by sending each page query to a coordinator that is also a replica. So maybe that suffices.

**Comment by ddorian** [comment]
Doing a price-comparison/crawling service.

You store the pages ordered by url so they compress better + faster range-queries on primary_key (since it knows which partition to hit).

Cases when some partitions may grow too big (so they auto split) and still want to keep the efficient range_query on primary_key (compared to manually splitting and scanning x partitions).

**Comment by avikivity** [comment]
What's the baseline you're comparing to? Store the domain name in the partition key and the rest of the URL in the clustering key?

You don't really need ordering by domain name, do you?

**Comment by ddorian** [comment]
Storing by (tld, domain, subdomain, path, request_args, hash).
Compression is better from left-to-right.
Wanting to scan usually subdomains or domains in full.

Another usecase is: Keeping items for tenants: (partitions may grow alot, ids aren't incremental, though they may be in cases where throughtput isn't very big)::
Storing by (tenant_id, type, id) and doing (tenant) scan, (tenant,type) scan, tenant+type+id single-select.

Both these cases have better compression and faster range-scan. 
Of course, you can get write bottlenecks, but that can be fixed by rate-limiting on the client or on the server (scylla already does when it's getting too many requests).

They can even have versioning, but that is easier to do in a separate `revision` table (depending on how you need to read them, versioning increases the amount of data per-partition)
