### ISSUE TITLE
Command nodetool decommission failed on node with raft

### ISSUE THREAD

**Issue by aleksbykov** [scylladb/scylla#9845]
*Installation details*
Kernel version: `5.11.0-1022-aws`
Scylla version (or git commit hash): `4.7.dev-0.20211215.3ac622bdd with build-id c19c7740f10f82f554c1b67da69f82fc48f9386f`
Cluster size: 4 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   raft-topologychanges-100gb-3h-maste-db-node-60514257-1 (13.51.234.224 | 10.0.2.184): 14 shards
   raft-topologychanges-100gb-3h-maste-db-node-60514257-2 (13.49.246.129 | 10.0.1.209): 14 shards
   raft-topologychanges-100gb-3h-maste-db-node-60514257-3 (13.48.177.90 | 10.0.0.68): 14 shards
   raft-topologychanges-100gb-3h-maste-db-node-60514257-4 (16.170.214.248 | 10.0.1.181): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-045cd00d68f3af143` (aws: eu-north-1)

Test: `BYO-abykov-staging`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [raft-topology-changes-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/4f3b7c24bd6dbe976d6249cf6517ad01edb47e88/test-cases/raft/raft-topology-changes-3h.yaml)

**Issue description**

Raft experimental feature was enabled in scylla.yaml. According to log, Raft service was started.
```
2021-12-20T03:52:08+00:00 raft-topologychanges-100gb-3h-maste-db-node-60514257-1 !    INFO |  [shard 0] init - starting Raft Group Registry service
```

After cluster was configured, the first nemesis is Decommission. `nodetool decommission` was started on node1
```
2021-12-20T04:19:35+00:00 raft-topologychanges-100gb-3h-maste-db-node-60514257-1 !    INFO |  [shard 0] storage_service - DECOMMISSIONING: starts
2021-12-20T04:19:35+00:00 raft-topologychanges-100gb-3h-maste-db-node-60514257-1 !    INFO |  [shard 0] storage_service - decommission[cd287ffa-99f0-47c8-9553-62fbf723fd16]: Started decommission operation, removing node=10.0.2.184, sync_nodes=[10.0.1.181, 10.0.0.68, 10.0.1.209, 10.0.2.184], ignore_nodes=[]
2021-12-20T04:19:35+00:00 raft-topologychanges-100gb-3h-maste-db-node-60514257-1 !    INFO |  [shard 0] storage_service - decommission[cd287ffa-99f0-47c8-9553-62fbf723fd16]: Added node=10.0.2.184 as leaving node, coordinator=10.0.2.184
2021-12-20T04:19:36+00:00 raft-topologychanges-100gb-3h-maste-db-node-60514257-1 !    INFO |  [shard 0] storage_service - decommission[cd287ffa-99f0-47c8-9553-62fbf723fd16]: Started heartbeat_updater
```
According to log, decommission was finished successfull:
```
2021-12-20T04:22:08+00:00 raft-topologychanges-100gb-3h-maste-db-node-60514257-1 !    INFO |  [shard 0] storage_service - DECOMMISSIONING: stopped transport
2021-12-20T04:22:08+00:00 raft-topologychanges-100gb-3h-maste-db-node-60514257-1 !    INFO |  [shard 0] storage_service - DECOMMISSIONING: stop batchlog_manager done
2021-12-20T04:22:09+00:00 raft-topologychanges-100gb-3h-maste-db-node-60514257-1 !    INFO |  [shard 7] compaction - [Compact keyspace1.standard1 3d462a20-614c-11ec-a1f1-4d47719ea3ef] Compacted 2 sstables to [/var/lib/scylla/data/keyspace1/standard1-3d5e8990614b11eca07c4d46719ea3ef/md-189-big-Data.db:level=0]. 2GB to 1GB (~81% of original) in 67799ms = 27MB/s. ~434432 total partitions merged to 353063.
```

But command was failed with error:
```
Command: '/usr/bin/nodetool  decommission '

Exit code: 1

Stdout:

nodetool: Scylla API server HTTP POST to URL '/storage_service/decommission' failed: seastar::rpc::closed_error (connection is closed)
See 'nodetool help' or 'nodetool help <command>'.

Stderr:
```

Possible steps to reproduce:
1. Create cluster with raft from 4 nodes
2. Run workload with c-s stress commands
3. Run `nodetool decommission` on node1 ( which is could be a seed)

Restore Monitor Stack command: `$ hydra investigate show-monitor 60514257-411a-46a7-9198-30f9c674a888`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=60514257-411a-46a7-9198-30f9c674a888)
Show all stored logs command: `$ hydra investigate show-logs 60514257-411a-46a7-9198-30f9c674a888`

Test id: `60514257-411a-46a7-9198-30f9c674a888`

Logs:
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/60514257-411a-46a7-9198-30f9c674a888/20211220_042442/grafana-screenshot-byo-abykov-staging-scylla-per-server-metrics-nemesis-20211220_042632-raft-topologychanges-100gb-3h-maste-monitor-node-60514257-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/60514257-411a-46a7-9198-30f9c674a888/20211220_042442/grafana-screenshot-byo-abykov-staging-scylla-per-server-metrics-nemesis-20211220_042632-raft-topologychanges-100gb-3h-maste-monitor-node-60514257-1.png)
grafana - [https://cloudius-jenkins-test.s3.amazonaws.com/60514257-411a-46a7-9198-30f9c674a888/20211220_042442/grafana-screenshot-overview-20211220_042442-raft-topologychanges-100gb-3h-maste-monitor-node-60514257-1.png](https://cloudius-jenkins-test.s3.amazonaws.com/60514257-411a-46a7-9198-30f9c674a888/20211220_042442/grafana-screenshot-overview-20211220_042442-raft-topologychanges-100gb-3h-maste-monitor-node-60514257-1.png)
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/60514257-411a-46a7-9198-30f9c674a888/20211220_043047/db-cluster-60514257.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/60514257-411a-46a7-9198-30f9c674a888/20211220_043047/db-cluster-60514257.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/60514257-411a-46a7-9198-30f9c674a888/20211220_043047/loader-set-60514257.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/60514257-411a-46a7-9198-30f9c674a888/20211220_043047/loader-set-60514257.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/60514257-411a-46a7-9198-30f9c674a888/20211220_043047/monitor-set-60514257.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/60514257-411a-46a7-9198-30f9c674a888/20211220_043047/monitor-set-60514257.tar.gz)
sct-runner - [https://cloudius-jenkins-test.s3.amazonaws.com/60514257-411a-46a7-9198-30f9c674a888/20211220_043047/sct-runner-60514257.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/60514257-411a-46a7-9198-30f9c674a888/20211220_043047/sct-runner-60514257.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-staging/job/abykov/job/BYO-abykov-staging/91/)

**Comment by kbr-** [comment]
Full decommissioning log with raft disabled:
```
INFO  2022-01-27 11:50:09,872 [shard 0] storage_service - DECOMMISSIONING: stopped transport
INFO  2022-01-27 11:50:09,872 [shard 0] storage_service - DECOMMISSIONING: stop batchlog_manager done
INFO  2022-01-27 11:50:09,891 [shard 0] storage_service - DECOMMISSIONING: set_bootstrap_state done
INFO  2022-01-27 11:50:09,891 [shard 0] storage_service - DECOMMISSIONED: 
INFO  2022-01-27 11:50:09,891 [shard 0] storage_service - DECOMMISSIONING: done
```

Decommissioning log with raft enabled:
```
INFO  2022-01-27 11:53:01,502 [shard 0] storage_service - DECOMMISSIONING: stopped transport
INFO  2022-01-27 11:53:01,503 [shard 0] storage_service - DECOMMISSIONING: stop batchlog_manager done
```

we're missing some final messages.

`storage_service::decommission()`:
```cpp
            slogger.info("DECOMMISSIONING: stop batchlog_manager done");
            // Leave Raft group 0
            ss._group0->leave_group0().get();
            // StageManager.shutdownNow();
            db::system_keyspace::set_bootstrap_state(db::system_keyspace::bootstrap_state::DECOMMISSIONED).get();
            slogger.info("DECOMMISSIONING: set_bootstrap_state done");
            ss.set_mode(mode::DECOMMISSIONED, true);
            slogger.info("DECOMMISSIONING: done");
```

apparently `leave_group0()` throws or crashes the process.

**Comment by kbr-** [comment]
`leave_group0()` throws `seastar::rpc::closed_error (connection is closed)`.

**Comment by kbr-** [comment]
By the way, other nodes still try to contact the decommissioned node, even though it was removed from gossip.
```
INFO  2022-01-27 11:58:35,921 [shard 0] gossip - Node 127.0.0.1 will be removed from gossip at [2022-01-30 11:58:35]:
...
ERROR 2022-01-27 11:59:34,996 [shard 0] rpc - client 127.0.0.1:7000: fail to connect: Connection refused
INFO  2022-01-27 11:59:35,928 [shard 0] gossip - 60000 ms elapsed, 127.0.0.1 gossip quarantine over
ERROR 2022-01-27 11:59:36,398 [shard 0] rpc - client 127.0.0.1:7000: fail to connect: Connection refused
...

I'm guessing it comes from the raft server.
BTW. those "fail to connect" messages are kinda useless. They should tell where do they come from (who's trying to perform the rpc).

**Comment by kbr-** [comment]
Well, it shouldn't be surprising that we cannot leave group 0, since we shutdown messaging service before that.
```
INFO  2022-01-27 12:06:07,817 [shard 0] storage_service - messaging_service stopped
INFO  2022-01-27 12:06:07,818 [shard 0] storage_service - Stop transport: shutdown messaging_service done
INFO  2022-01-27 12:06:07,818 [shard 0] storage_service - Stop transport: shutdown stream_manager done
INFO  2022-01-27 12:06:07,818 [shard 0] storage_service - Stop transport: done
INFO  2022-01-27 12:06:07,818 [shard 0] storage_service - DECOMMISSIONING: stopped transport
INFO  2022-01-27 12:06:07,818 [shard 0] storage_service - DECOMMISSIONING: stop batchlog_manager done
```

Moving `leave_group0.get()` call before `ss.stop_transport()` (in `decommission()`) stops the rpc error from appearing, but... it causes decommission to hang. `co_await _raft_gr.group0().modify_config({}, del_set);` in `leave_group0` does not finish.

**Comment by aleksbykov** [comment]
The issue reproduced on 5.0.rc3
