### ISSUE TITLE
SELECT COUNT() doesn't obey PER PARTITION LIMIT

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9856]
`COUNT()` always returns the total number of rows, disregarding the PER PARTITION LIMIT.

Reproduce with f7b8b809d

```
[cqlsh 5.0.1 | Cassandra 3.0.8 | CQL spec 3.3.1 | Native protocol v4]
Use HELP for help.
cqlsh> create keyspace ks WITH replication = {'class': 'SimpleStrategy', 'replication_factor': 1};

cqlsh> create table ks.t ( k text, ck int, v text, PRIMARY KEY(k, ck) );

cqlsh> insert INTO ks.t (k, ck, v) VALUES ('k1', 1, 'v1');
cqlsh> insert INTO ks.t (k, ck, v) VALUES ('k1', 2, 'v2');
cqlsh> insert INTO ks.t (k, ck, v) VALUES ('k2', 1, 'v3');
cqlsh> insert INTO ks.t (k, ck, v) VALUES ('k2', 2, 'v4');

cqlsh> SELECT * FROM ks.t;

 k  | ck | v
----+----+----
 k1 |  1 | v1
 k1 |  2 | v2
 k2 |  1 | v3
 k2 |  2 | v4

(4 rows)
cqlsh> SELECT * FROM ks.t PER PARTITION LIMIT 1;

 k  | ck | v
----+----+----
 k1 |  1 | v1
 k2 |  1 | v3

---MORE---
(2 rows)

cqlsh> SELECT count(*) FROM ks.t PER PARTITION LIMIT 1;

 count
-------
     4

(1 rows)
```

**Comment by avikivity** [comment]
I guess the question is: is PER PARTITION LIMIT applied before counting, of after counting?

**Comment by avikivity** [comment]
I ran this on postgres:

```sql
create table t ( k text, ck int, v text );
insert into t (k, v) values ('a', 'a');
insert into t (k, v) values ('b', 'b');
select count(*) from t LIMIT 1;
```

and got 1 row with the value 2. So it looks like the behavior is correct (it's reasonable to assume that PER PARTITION LIMIT and LIMIT apply at the same stage in the pipeline)

**Comment by bhalevy** [comment]
https://docs.scylladb.com/getting-started/functions/ defines aggregate functions as operating on the results of the query, but I agree we should consider adhering to what other databases do too.

**Comment by bhalevy** [comment]
My intuition is the the PER PARTITION LIMIT is akin to a WHERE clause and the aggregate function should be performed over this result set.

Otherwise, it doesn't make sense to apply LIMIT or PER PARTITION LIMIT on the result of COUNT since it is singular.

**Comment by bhalevy** [comment]
See https://docs.microsoft.com/en-us/sql/t-sql/functions/count-transact-sql?view=sql-server-ver15 use of OVER for example.

**Comment by bhalevy** [comment]
https://www.postgresqltutorial.com/postgresql-count-function/
```
The COUNT(*) function returns the number of rows returned by a  SELECT statement, including NULL and duplicates.
```

So if the SELECT statement in our case is restricted by PER PARTITION LIMIT, count should return the count of that.

I.e. the limit is on the input of COUNT, not on its output.

**Comment by bhalevy** [comment]
https://stackoverflow.com/questions/17020842/mysql-count-with-limit

**Comment by avikivity** [comment]
Closing as invalid.

**Comment by bhalevy** [comment]
@tzach this needs to be documented somehow in https://docs.scylladb.com/getting-started/dml/ and https://docs.scylladb.com/getting-started/functions/#aggregate-functions

(though in my personal opinion, although it might be correct to define it this way, it is useless and doesn't make a lot of sense. It could be much more useful if the per partition limit applied at the filtering stage in the pipeline and then the aggregate functions could operate on the resulting rows, exactly like they do when a WHERE clause is applied in each partition)

**Comment by tzach** [comment]
@bhalevy can you please open a doc issue with a rewording suggestion

**Comment by tzach** [comment]
Apache Cassandra 3.11 response with an error for this case, which makes more sense than Scylla invalid value

```
cqlsh> SELECT count(*) FROM ks.t PER PARTITION LIMIT 1;
InvalidRequest: Error from server: code=2200 [Invalid query] message="PER PARTITION LIMIT is not allowed with aggregate queries."
```
