### ISSUE TITLE
[0.19] iotune is not checking available space before creating files, causing crashes

### ISSUE THREAD

**Issue by lmr** [scylladb/scylla#986]
This one is related to #980. When the service `scylla-io-setup` runs, it won't check the available space, causing the following error:

    iotune --evaluation-directory /var/lib/scylla --format envfile --options-file /etc/scylla.d/io.conf
    Generating evaluation file...terminate called after throwing an instance of 'std::system_error'
      what():  No space left on device
    Aborted (core dumped)

The actual logs from systemd look like:

    Mar 03 14:10:48 atest-guest scylla_io_setup[1257]: Generating evaluation file...terminate called after throwing an instance of 'std::system_error'
    Mar 03 14:10:48 atest-guest scylla_io_setup[1257]: what():  No space left on device
    Mar 03 14:10:48 atest-guest audit[1265]: <audit-1701> auid=4294967295 uid=0 gid=0 ses=4294967295 subj=system_u:system_r:unconfined_service_t:s0 pid=1265 comm="iotune" exe="/usr/bin/i
    Mar 03 14:10:48 atest-guest auditd[493]: Audit daemon is low on disk space for logging
    Mar 03 14:10:48 atest-guest auditd[493]: Audit daemon is suspending logging due to low disk space.
    Mar 03 14:10:48 atest-guest systemd-coredump[1278]: Failed to create coredump file /var/lib/systemd/coredump/.#core.iotune.0.c39c764333404bc9a9af7aa87c048d7c.1265.14570322480000009c8
    Mar 03 14:10:48 atest-guest systemd-coredump[1278]: Process 1265 (iotune) of user 0 dumped core.
    -- Subject: Process 1265 (iotune) dumped core
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- Documentation: man:core(5)
    -- 
    -- Process 1265 (iotune) crashed and dumped core.
    -- 
    -- This usually indicates a programming error in the crashing program and
    -- should be reported to its vendor as a bug.
    Mar 03 14:10:48 atest-guest systemd[1]: scylla-io-setup.service: main process exited, code=exited, status=134/n/a
    Mar 03 14:10:48 atest-guest systemd[1]: Failed to start Scylla IO Setup.
    -- Subject: Unit scylla-io-setup.service has failed
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit scylla-io-setup.service has failed.
    -- 
    -- The result is failed.
    Mar 03 14:10:48 atest-guest systemd[1]: Dependency failed for Scylla Server.
    -- Subject: Unit scylla-server.service has failed
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit scylla-server.service has failed.

The problem in question reproduced on a virtual machine dedicated to do smoke testing of the scylla rpm packages, with total disk size of 10GB (leaving 9 GB of space for root, scylla and whatnot).

I'm not claiming this setup was satisfactory (although I had no way to know that beforehand), and the disk space issue was already fixed (VM disks were resized). However, there are other occasions where a user might run out of space and have an error that is difficult to debug.

**Comment by lmr** [comment]
@slivne, please assign this to @glommer.

**Comment by slivne** [comment]
@glommer we need to resolve this to spin 0.19

**Comment by dorlaor** [comment]
He sent a patch

**Comment by glommer** [comment]
@slivne  Guys, can we close this one?

**Comment by slivne** [comment]
its not merged AFAIK

**Comment by glommer** [comment]
you mean the seastar patch?

Why??

**Comment by penberg** [comment]
This is fixed by the following seastar merge: https://github.com/scylladb/scylla/commit/7ae2298081fe3117e26c33502542c590ad5b90ec
