### ISSUE TITLE
test/scylla-gdb reorganization

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#9864]
test/scylla-gdb/run is a shell-script, which did not benefit from the gradual improvements of `test/{cql-pytest,alternator,redis}/run`  which are written in Python and use comment code from **test/cql-pytest/run.py**, and also has a bunch of other problems. Here are some of the problems in test/scylla-gdb/run:
1. @kostja reported that it cannot be killed (by test.py) and leaves a gdb process consuming 100% cpu forever.
2. It always runs build/release/scylla, unrelated to which build mode is available or requested. If you try to run it without release build having been built or the SCYLLA variable set, it fails - but without an error message.
3. The tests are in a single Python test file (test/scylla-gdb/test.py) not using any test framework such as test.py. This means there is no clear indication of which many subtests failed, nor an ability to run only a specific test. It also encourages all tests to only check failure, not correct results, because of lack of "assert" features. It's also inconvenient to add more tests (e.g., see some ideas for new tests in #9741 by @bhalevy) as we need to put all the tests in the same file.
4. The test starts Scylla from within gdb and uses a breakpoint at compact_sstables() to let it "run for some time". It's not obvious that this "some time" is "enough". It's also slow to start Scylla this way.
5. If scylla-gdb.py cannot be sourced (in my installation, it fails with "gdb.error: No type named size_t"), test/scylla-gdb/run simply continues, and will later fail when some of the features in scylla-gdb.py is not available. The test should fail immediately at that point, instead of continuing.
6. Trying to run `SCYLLA=`pwd`/build/dev/scylla test/scylla-gdb/run 2>&1 | less` fails - the process is somehow "stopped". Interestingly without the `2>&1`, or if it's redirected to a file, not to less (`.. >somefile 2>&1`), it's fine. I don't know why.

I think it would be better to switch the scylla-gdb tests to be more like the rest of the Python-based tests (alternator, cql-pytest, redis, etc.):

1. Use the same mechanisms from `test/cql-pytest/run.py` to start Scylla and wait until it's fully up.
2. Only then, "attach" to it with gdb. This way, the run script knows the process id of both gdb and Scylla, and can kill both with SIGKILL when shutting down.
3. Move the tests to use pytest. This will require just a bit of code reorganization in `test/scylla-gdb/test.py`, but not changes to the actual tests.

**Comment by bhalevy** [comment]
Cc @tgrabiec @denesb @cmm @xemul as the authors of the existing scylla-gdb

**Comment by nyh** [comment]
This is easier said than done... Running pytest *inside* gdb is non-trivial but I'm still working on it - if it becomes too ugly I may switch to driving a gdb process from pytest using the user-oriented textual protocol, not Python.

Another problem in my optimism above is that this test needs Scylla to have debugging symbols. It doesn't work on "dev" mode which is the only mode to not be compiled with "-g" :-(

**Comment by nyh** [comment]
> This is easier said than done... Running pytest _inside_ gdb is non-trivial but I'm still working on it

I already have it working nicely :-) I'll send an RFC patch for review shortly.

**Comment by cmm** [comment]
I'm, uhh, not exactly proud of the gdb test as it stands, but doing this properly is indeed non-trivial.
Apart from the overall "who drives who" question, there is another possible complication: if you want every `do` therein to become a proper sub-test (which, if I understand correctly, means that you'll want to run a fresh scylla/gdb pair for each such sub-test?), you may find that there are implicit dependencies on earlier commands.
(And, yes, the test is restricted to the "release" mode because of debug symbols)

**Comment by nyh** [comment]
> If you want every `do` therein to become a proper sub-test (which, if I understand correctly, means that you'll want to run a fresh scylla/gdb pair for each such sub-test?)

No. What I ended up doing is to run Scylla once, then run gdb once and attach to Scylla, and then have gdb (which has a full-fledged Python interpreter) run "pytest" (which is itself a Python program), and it can run multiple tests which all can call the "gdb" commands to interact with the gdb they live in. It's working nicely for all the basic tests in test.py that just run some command and watch it not-fail.

> you may find that there are implicit dependencies on earlier commands

There are a few tests I still need to translate to the new framework which may have this problem. I may need to write them in a way that ensures they do not break each other - just like the Alternator/CQL tests need to use a random table name or a random key so two tests using the same database don't conflict.

**Comment by nyh** [comment]
Sent a patch to the mailing list, titled "[PATCH v1] test/scylla-gdb: a rewrite, using pytest".

It is almost complete, but I ran into one snag: The test for "scylla fiber" needs a task object. The new test framework attaches gdb to an idle Scylla, so `get_local_tasks()` no longer finds any task. I need to find a way to find a task - either by adding a breakpoint as in the original implementation (I'm not thrilled about that) or by finding another task somewhere in Scylla that exists even while Scylla is idle (?).

**Comment by avikivity** [comment]
Refactoring, not backporting.
