### ISSUE TITLE
shard_reader close stops short after read_ahead error

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9865]
Since 13d7806b622919b76011d2b24f4ad180a041cac7, an error returned by the `_read_ahead` future
will cause co_await to throw, before the evictable_reader in `_reader` is destroyed and closed.

The issue exists in the coroutine in branch-4.6.

**Comment by bhalevy** [comment]
`[PATCH 1/1] shard_reader: Continue after read_ahead error` fixes this issue, sent to the scylladb-dev mailing list.

**Comment by avikivity** [comment]
Please try to word issues in a way that can be understood by users.

**Comment by bhalevy** [comment]
@scylladb/scylla-maint please backport d7a993043de250f39c3881017b83fbb1e789e6fb and #9923 (fixed by d7a993043de250f39c3881017b83fbb1e789e6fb) to 4.6

Refs #10029

**Comment by denesb** [comment]
> @scylladb/scylla-maint please backport [fc729a8](https://github.com/scylladb/scylla/commit/fc729a804b5ae9fa8bd8de33ef63aeae4dd3ccf9) and #9923 (fixed by [d7a9930](https://github.com/scylladb/scylla/commit/d7a993043de250f39c3881017b83fbb1e789e6fb)) to 4.6

Done.
