### ISSUE TITLE
Alternator: CreateTable + GSI/LSI creation should be atomic

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#9868]
This issue is related to the known issue #6391, and it is likely that the same fix would fix them both.

The `CreateTable` operation has parameters to create GSIs or LSIs, i.e., _materialized views_, on the newly created table. However, the way we do this today is as several separate operations: First the table is created, then the materialized views are added. It is, at least in theory, possible for the table creation to succeed but then the view creation to fail - and the result is that the operation will seem to fail but still leave behind a new table, missing its views.
If the view-creation fails we should probably delete the newly-created table. Or even better, we should find a way to atomically create a table and its views and not as multiple independent operations.

Ideally with the new Raft-based schema changes we should be able to implement this as a single CAS (read-modify-write) operation: This atomic operation (serialized with other schema operations) would:
1. Read the current schema and _verify_ that the operation is allowed
2. Create the schema-modifying mutations - all of them.
3. Apply these mutations.

**Comment by gleb-cloudius** [comment]
The issue of not been able to create single `std::vector<mutation>` before announcing is not raft related and can be fixed without the raft. Without fixing it though even with raft there will be no linearizability.

**Comment by avikivity** [comment]
Minor - this will rarely cause problems in production deployments since these don't try to create tables concurrently. Not backporting.

**Comment by nyh** [comment]
Yet another case where we finished the backport decision, removed the backport candidate tag, and it was wrongly re-added. So removing it again.
