### ISSUE TITLE
Scylla doesn't support the me sstable version

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9869]
Split off of #9676.

According to https://github.com/apache/cassandra/blob/11952fae774d51d4e268dae506803fef874c8c50/src/java/org/apache/cassandra/io/sstable/format/big/BigFormat.java#L123

The `me` format added hostId of the node from which the sstable originated.

For reference, the `UUID originatingHostId` member was added to `StatsMetadata` in apache/cassandra@d84c6e98106e7b0c205f019ee24d416d0bb65f37

This issue should cover the support in Scylla for the `me` sstable version, including unit testing and documentation in the scylla repo.
Public scylla documentation should be updated respectively once this issue is resolved.

A cluster feature is required so that ne sstables will be written by default only when all nodes in the cluster are upgraded to support, to facilitate roolback in case rolling upgrade failed.

Unit test should be added to tests that the originating_host_id is written and read correctly.

A `me` sstable written by Cassandra should be loaded successfully as well.

**Comment by bhalevy** [comment]
@cmm I assigned you tentatively so it will be on your queue...

**Comment by bhalevy** [comment]
@cmm, can this issue be closed with 948bc359c23c86a97f34987017edc30143c03c74?

**Comment by cmm** [comment]
all the fallout seems to be outside Scylla proper, so yes

**Comment by jmaixl** [comment]
> all the fallout seems to be outside Scylla proper, so yes

Thanks for adding support to ME sstables! Will this be backported to 4.6 or 4.5 in a bugfix release, or added to a major/minor version release?

**Comment by bhalevy** [comment]
> > all the fallout seems to be outside Scylla proper, so yes
> 
> Thanks for adding support to ME sstables! Will this be backported to 4.6 or 4.5 in a bugfix release, or added to a major/minor version release?

It will be considered for backport to 5.0 and maybe to 4.6.x (since we're preparing 4.6.0 for release).
4.5 won't get it, since it is a feature, not a bug fix.

**Comment by jmaixl** [comment]
> It will be considered for backport to 5.0 and maybe to 4.6.x (since we're preparing 4.6.0 for release). 4.5 won't get it, since it is a feature, not a bug fix.

Forgot to reply to this when I saw this, but thanks for the reply. we will eagerly and hopefully await 4.6.x.

**Comment by jmaixl** [comment]
Hi, just following up on this @bhalevy, will we see this in 4.6.x or 5.0? It's the main addition to allow us to migrate to Scylla easily. Thanks!

**Comment by avikivity** [comment]
It will be in 5.1.

**Comment by avikivity** [comment]
Not a bug, not backporting.
