### ISSUE TITLE
Segfault during repair start on aarch64

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9881]
Seen since https://jenkins.scylladb.com/job/scylla-master/job/build/876/
Scylla version 9a1fdb06358da52051e1191bf9bb7a1f16e7fc67

That includes:
25b036f35 repair: Improve memory usage tracking and oom protection
a8ad385ec repair: Get rid of the gc_grace_seconds

https://jenkins.scylladb.com/job/scylla-master/job/build/876/artifact/output_test_aarch64_release.txt
```
[271/2211] alternator release [ FAIL ] run.279 1.59s
[273/2211] cql-pytest release [ FAIL ] run.278 1.76s
[275/2211] rest_api release [ FAIL ] run.277 1.81s
```

For example,
https://jenkins.scylladb.com/job/scylla-master/job/build/876/artifact/testlog/aarch64_release/run.277.log
```
INFO  2022-01-05 02:31:45,820 [shard 0] repair - Setting max_repair_memory=53687091, max_repair_memory_per_range=33554432, max_repair_ranges_in_parallel=1
INFO  2022-01-05 02:31:45,820 [shard 0] repair - Loading repair history for keyspace=system, table=config, table_uuid=3e9372bc-f440-3892-899e-7377c6584b44
INFO  2022-01-05 02:31:45,821 [shard 1] repair - Loading repair history for keyspace=system, table=runtime_info, table_uuid=c999823b-87bc-36d9-a378-a90ffab08f00
INFO  2022-01-05 02:31:45,821 [shard 1] repair - Loading repair history for keyspace=system, table=versions, table_uuid=8b5611ad-b90c-3883-855a-bcc6ddc54f33
Segmentation fault on shard 1.
Backtrace:
  0x2875927
  0x28a110f
  linux-vdso.so.1+0x5af
  0xe010000064bf
```

The decoded backtrace doesn't seem to be very useful, but here it is anyway:
```
[Backtrace #0]
void seastar::backtrace(seastar::backtrace_buffer::append_backtrace()::{lambda(seastar::frame)#1}&&) at ./build/release/seastar/./seastar/include/seastar/util/backtrace.hh:59
 (inlined by) seastar::backtrace_buffer::append_backtrace() at ./build/release/seastar/./seastar/src/core/reactor.cc:764
 (inlined by) seastar::print_with_backtrace(seastar::backtrace_buffer&, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:794
seastar::print_with_backtrace(char const*, bool) at ./build/release/seastar/./seastar/src/core/reactor.cc:806
 (inlined by) seastar::sigsegv_action() at ./build/release/seastar/./seastar/src/core/reactor.cc:3675
 (inlined by) operator() at ./build/release/seastar/./seastar/src/core/reactor.cc:3661
 (inlined by) __invoke at ./build/release/seastar/./seastar/src/core/reactor.cc:3657
linux-vdso.so.1 0x5af 
?? ??:0
```

**Comment by asias** [comment]
Does this happen on aarch64 only? Can you share the cmd to reproduce?

**Comment by bhalevy** [comment]
> Does this happen on aarch64 only?

yes, and apparently only in release mode (not dev nor debug)

> Can you share the cmd to reproduce?

on a aarch64 machine I believe you can simply run `ninja build/release/scylla && ./test.py --mode=release rest_api`

**Comment by asias** [comment]
I suspect it is a compiler issue with coroutine on aarch64. 

I do not have access to aarch64 box.

**Comment by slivne** [comment]
everyone has access to aarch64 box - spin one on AWS if need be.

**Comment by asias** [comment]
> everyone has access to aarch64 box - spin one on AWS if need be.

Any recommended arm instance to build scylla?

**Comment by bhalevy** [comment]
t4g.nano and up I think

**Comment by bhalevy** [comment]
@yaronkaikov ?

**Comment by yaronkaikov** [comment]
@asias @bhalevy use `c6gd.xlarge`

**Comment by avikivity** [comment]
It's a8ad385ec

**Comment by asias** [comment]
> @asias @bhalevy use `c6gd.xlarge`

Avi shared a arm box so I do not have to start a aws instance. 

I am wondering how the release team build and run tests for arm64. Running ubuntu 20.04 on a arm64 box, then run dbuild with fedora 34 as the build os,  then run the testing on ubuntu 20.04 OS?

**Comment by bhalevy** [comment]
> I am wondering how the release team build and run tests for arm64. Running ubuntu 20.04 on a arm64 box, then run dbuild with fedora 34 as the build os, then run the testing on ubuntu 20.04 OS?

Tests should run in the dbuild environment too.

**Comment by avikivity** [comment]
This is in 5.0 that saw the regression, so not backporting.
