### ISSUE TITLE
sstables/partition_index_cache: get_or_load() error handling triggers assert

### ISSUE THREAD

**Issue by denesb** [scylladb/scylla#9887]
If the loader fails the error handling erases the cache entry to clean up. However the entry ptr is still live when this happens and so the cache entry will have non-zero reference count, triggering an assert in its destructor. This effectively converts an exception into a crash.

**Comment by denesb** [comment]
Merged as 92727ac36c311e09adf8bcf0946637e35c7d0994.

**Comment by avikivity** [comment]
Already backported to 4.6, earlier branches do not have that code.
