### ISSUE TITLE
Stopping or killing a node early before gossip is settled leaves it in limbo on other nodes.

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9894]
This was seen in #9759 by, e.g, materialized_views_test.py::TestInterruptBuildProcess::interrupt_build_process_and_resharding_half_to_low_test.

When a node is stopped or forcibly killed during resharding (that's started in distributed_loader::init_non_system_keyspaces),
other nodes don't recognize it as down and keeping printing errors to reach it at the rpc layer.

I'm splitting off this issue so it could be tested and fixed independently of #9759.

To reproduce, `s/wait_other_notice=False/wait_other_notice=True/` in https://github.com/scylladb/scylla-dtest/blob/1a284d4af278b01deee5b36ceddc2b59f33b908b/materialized_views_test.py#L4255

The issue seems to be with gossip, @asias please confirm.

**Comment by asias** [comment]
When a node is killed forcefully, other nodes will not get the shutdown message, so they will wait for the failure_detector_timeout_in_ms to be sure the node is down and mark it is down.

**Comment by nyh** [comment]
I don't know if this is related, but I want to point out that I saw something which is perhaps similar in https://github.com/scylladb/scylla-dtest/pull/2455 - this is a 5-node cluster where the 5th node was killed **gently** (the process was sent SIGTERM, not SIGKILL, and was allowed to shut down cleanly) but early, and the result was sometimes (rarely) that the other nodes got confused about the token ownership of that 5th node.

**Comment by bhalevy** [comment]
> When a node is killed forcefully, other nodes will not get the shutdown message, so they will wait for the failure_detector_timeout_in_ms to be sure the node is down and mark it is down.

The test waits for 10 minutes but the node is still not marked DOWN.
See https://github.com/scylladb/scylla-ccm/blob/65424bf75130ed82f9680d571f33e7212684a4c4/ccmlib/node.py#L500

**Comment by asias** [comment]
Benny are you using ccm  65424bf75130ed82f9680d571f33e7212684a4c4 and dtest 1a284d4af278b01deee5b36ceddc2b59f33b908b? We really should put ccm under dtest.

**Comment by asias** [comment]
```
245         logger.debug("Restart the cluster with shards {}".format(smp_after))
4246         for node in self.cluster.nodelist():
4247             logger.debug("Starting node " + node.name)
4248             jvm_args = ['--smp', str(smp_after),
4249                         '--memory', self.set_memory_param(smp_after)]
4250             if interrupt_resharding:
4251                 mark = node.mark_log()
4252                 node.start(jvm_args=jvm_args, no_wait=True)
4253                 node.watch_log_for(r"Reshard ks", from_mark=mark)
4254                 logger.debug(f"Stopping node {node.name} during resharding")
4255                 node.stop(gently=False, wait_other_notice=True)
4256                 time.sleep(5)
4257                 logger.debug(f"Restarting node {node.name}")
4258             node.start(jvm_args=jvm_args)
```

When node2 ran line 4255, node2 stopped too fast in the boot up process, node2 even did not  start gossip fully, as a result, node 1 did not mark node2 was UP.  In turn, node 1 will not log node2 was DOWN in the log.  But node1 will treat node2 as DOWN because before a node marks another node as UP, it is treated as DOWN. 

In the log, it is expected to see node1 have rpc messges to node2, because gossip will attempt to talk to DOWN node on purpose. 

I do not see a real problem here.

**Comment by bhalevy** [comment]
Agreed. I tried reproducing this with a targeted test and I think the bug might be invalid (i.e. the bug was on the test side of things).
If the node is stopped/killed before it is marked as UP on the other nodes they won't notice it going DOWN
and `node.stop(wait_for_others=True)` will time out.
If we wait until the node is marked UP and the other nodes and only then stop the node early, they correctly notice it went DOWN in both scenario: orderly and unorderly stop.
I'll submit the tests in any case so we can keep them for regression testing.
