### ISSUE TITLE
snapshot_ctl::true_snapshots_size counts shared snapshots dirs on all shards

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9897]
As noted by @kbr- in https://github.com/scylladb/scylla/pull/9884#discussion_r781378240
snapshot_ctl uses map_reduce over all database shards, each counting the size of the snapshots directory, which is shared, not per-shard, so the total live size returned by it is multiples by the number of shards.

Note that although `snapshot_ctl::get_snapshot_details` also needlessly uses map_reduce, it relies on the std:;unordered_map insertion uniqueness so that only one shard will populate the result per-table.

**Comment by avikivity** [comment]
Fix present on all active branches, not backporting.
