### ISSUE TITLE
snapshot sizes are computed using file sizes rather than allocated blocks 

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9898]
The file size does not accurately reflect the space occupied by the files in the snapshot directory.
Although no holes are expected, the size of the file may be off in half a block-size on average due to the last block in the file, plus there is metadata overhead that may be attributed to the file, like the space for its inode and block-allocation map.

The discrepancy of "partial blocks" could be relatively large for small files (and some of the sstable files are small), where the file system can allocate e.g. 8KB for a file that logically holds only a single byte (4KB inode + 4KB block).

[Edit] Note: the directory holding the snapshot is also occupying space that is not accounted for.
It might be non-negligible for directories holding many (e.g. 100,000) files, but by convention it was never counted.
Changing that might require modifying tests that rely on it.

**Comment by avikivity** [comment]
Minor, not backporting.
