### ISSUE TITLE
dist: ubuntu 14.04 on AWS fails to start scylla-server with an unclear info

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#991]
1. start an 14.04 aws image (yes I know the root disk is not xfs)
2. install our repo file (last night)
3. try to install scylla

you will fail with a non informative manner

```
E: Sub-process /usr/bin/dpkg returned an error code (1)
ubuntu@ip-10-156-42-135:~$ cat /var/log/upstart/scylla-server.log 
cat: /var/log/upstart/scylla-server.log: Permission denied
ubuntu@ip-10-156-42-135:~$ sudo cat /var/log/upstart/scylla-server.log 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    12  100    12    0     0  12435      0 --:--:-- --:--:-- --:--:-- 12000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9  100     9    0     0  11015      0 --:--:-- --:--:-- --:--:--  9000
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    30  100    30    0     0  34443      0 --:--:-- --:--:-- --:--:-- 30000
/usr/lib/scylla/scylla_io_setup: 50: /usr/lib/scylla/scylla_io_setup: cannot create /etc/scylla.d/io.conf: Directory nonexistent
```

The other issue is that because of the changes we have done for the test is_ami - we validate that we are on AWS not by checking that we are using our AMI but by checking other items

    if [ "`dmidecode --string system-version | grep \.amazon`" != "" ] && \
       [ "`curl http://169.254.169.254/latest/meta-data/ami-id | grep ami-`" != "" ]; then

this effectivly causes us to "allow" running scylla on AMIs that are not ours - and we will not validate fs (and xfs version) using io_tune - I thinkwe need to change this.

Only our AMI should work around io_tune everything else should use io_tune.

**Comment by syuu1228** [comment]
"/usr/lib/scylla/scylla_io_setup: cannot create /etc/scylla.d/io.conf: Directory nonexistent" is ubuntu packaging bug. (The directory should exist in scylla-server package)

And yes, the script does not supported to install on AWS official AMIs.
Will fix them.

**Comment by penberg** [comment]
@slivne Do we need to backport this into 0.18 or 0.19?

**Comment by slivne** [comment]
in 0.18 this is not present its a change introduced post 0.18 - so no need
to backport

for 0.19 we do need it

**Comment by penberg** [comment]
@slivne Backported to 0.19.
