### ISSUE TITLE
More efficient read of compressed data file

### ISSUE THREAD

**Issue by nyh** [scylladb/scylla#992]
This issue is related to #964, but specifically about a compressed data file.

Unlike the code in fstream.cc, the code in sstable/compress.cc doesn't do any readaheads - when data is needed, it reads the next compressed chunk, exactly. This is optimal a small reads (which are included in one chunk), but for large reads, it might make sense to use read-ahead and/or read a large buffer, for the same reason that fstream.cc does these things.

We can add read-ahead logic to compress.cc, but it's possible that now that the fstream.cc code is much more advanced than it used to be (and in particular supports both a start and end position), we could actually build the compressed input stream code on top of a regular file input stream - so that latter will take care of all the read-ahead logic. Another advantage this approach will have for very large reads is that we won't need to read the begin and end sector of each chunk twice.

**Comment by nyh** [comment]
Note also (see rationale in #964) that make_compressed_file_input_stream() should take the len of the stream, not just its starting position - and this end position will be translated to the end-position of its chunk when the file input stream is created. And sstable::data_stream() should pass len to make_compressed_file_input_stream().

**Comment by slivne** [comment]
@nyh - how much work (in hours) is this ?

**Comment by nyh** [comment]
@slivne this shouldn't take long (definitely less than a day), but I'm more worried about how to check that the result is actually better: The issue is that my plan is basically to reverse a previous decision - we previously decided (based on Avi's suggestion) that compressed_file_input_stream should *not* use file_input_stream and should read from disk directly, but my suggestion here is to go back to build compressed_file_input_stream on file_input_stream.

Shomi, do you know if in our performance tests we use compressed sstables? As far as I know, in CQL, compression defaults to being enabled unless you explicitly disable it, but I don't know whether our cassandra-stress or other tests we run actually have compression enabled.

**Comment by slivne** [comment]
cassandra-stress disables compression by default - you can enable it

**Comment by nyh** [comment]
On Sun, Mar 6, 2016 at 11:58 AM, slivne <notifications@github.com> wrote:

> cassandra-stress disables compression by default - you can enable it
>

If our actual users will using compression (because, again, I believe
compression is enabled by default unless you deliberately disable it in
your CQL commands to create the table), then we should probably test and
benchmark performance with compression enabled. I can do limited
benchmarking on my own laptop, to test that a patch I propose doesn't
seriously botch things up, but I really don't have any good setup for any
sort of a serious regression benchmark.

Anyway, I just saw that by coincidence (?) Tzach created earlier today two
issues, in the scylla-dtest and scylla-enterprise repositories, on exactly
this issue, of testing and benchmarking compression. Good.

**Comment by slivne** [comment]
Agree,

You can use AWS for this and I can provide you access to Rackspace if you
prefer baremetal.

On other note: as previous read issues have shown - strace can come a long
way to show what we request from the disk vs what we think we request from
the disk - so a test with strace is a good start in any case.
