### ISSUE TITLE
commitlog: timed out, during decommission of node

### ISSUE THREAD

**Issue by fruch** [scylladb/scylla#9922]
*Installation details*
Kernel version: `5.11.0-1022-aws`
Scylla version (or git commit hash): `4.7.dev-0.20220114.8bcd23fa0 with build-id 991662b202244e747b247a64fa0ddefaab6b53af`
Cluster size: 6 nodes (i3.4xlarge)
Scylla running with shards number (live nodes):
   longevity-100gb-4h-master-db-node-1b686888-1 (54.216.114.122 | 10.0.0.56): 14 shards
   longevity-100gb-4h-master-db-node-1b686888-3 (3.250.14.181 | 10.0.2.117): 14 shards
   longevity-100gb-4h-master-db-node-1b686888-4 (34.250.230.215 | 10.0.0.103): 14 shards
   longevity-100gb-4h-master-db-node-1b686888-5 (63.32.112.153 | 10.0.2.160): 14 shards
   longevity-100gb-4h-master-db-node-1b686888-6 (34.242.73.20 | 10.0.3.107): 14 shards
   longevity-100gb-4h-master-db-node-1b686888-7 (34.247.194.100 | 10.0.2.135): 14 shards
Scylla running with shards number (terminated nodes):
   longevity-100gb-4h-master-db-node-1b686888-2 (3.250.172.53 | 10.0.1.227): 14 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0bf3b97eca8f38134` (aws: eu-west-1)

Test: `longevity-100gb-4h-test`
Test name: `longevity_test.LongevityTest.test_custom_time`
Test config file(s):
- [longevity-100gb-4h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/8584390cb25ea782b18acef4a6d77099be58b0bc/test-cases/longevity/longevity-100gb-4h.yaml)

**Issue description**
During decommission nemesis (taking place on node2), node4 started printing those errors and warnings (820624 of them):

```
2022-01-16T07:43:21+00:00 longevity-100gb-4h-master-db-node-1b686888-4 !     ERR |  [shard 5] storage_proxy - exception during mutation write to 10.0.0.103: std::_Nested_exception<std::runtime_error> (Could not write mutation keyspace1:standard1 (pk{000a3535503450334d383531}) to commitlog): db::commitlog::segment_manager::request_controller_timeout_exception_factory::request_controller_timed_out_error (commitlog: timed out)
...
2022-01-16T07:43:21+00:00 longevity-100gb-4h-master-db-node-1b686888-4 ! WARNING |  [shard 5] storage_proxy - Failed to apply mutation from 10.0.2.135#5: std::_Nested_exception<std::runtime_error> (Could not write mutation keyspace1:standard1 (pk{000a32374d30314f304c5030}) to commitlog): db::commitlog::segment_manager::request_controller_timeout_exception_factory::request_controller_timed_out_error (commitlog: timed out)
```

Restore Monitor Stack command: `$ hydra investigate show-monitor 1b686888-292c-4d17-a4b5-97344b39937f`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=1b686888-292c-4d17-a4b5-97344b39937f)
Show all stored logs command: `$ hydra investigate show-logs 1b686888-292c-4d17-a4b5-97344b39937f`

Test id: `1b686888-292c-4d17-a4b5-97344b39937f`

Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/1b686888-292c-4d17-a4b5-97344b39937f/20220116_090328/db-cluster-1b686888.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1b686888-292c-4d17-a4b5-97344b39937f/20220116_090328/db-cluster-1b686888.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/1b686888-292c-4d17-a4b5-97344b39937f/20220116_090328/loader-set-1b686888.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1b686888-292c-4d17-a4b5-97344b39937f/20220116_090328/loader-set-1b686888.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/1b686888-292c-4d17-a4b5-97344b39937f/20220116_090328/monitor-set-1b686888.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1b686888-292c-4d17-a4b5-97344b39937f/20220116_090328/monitor-set-1b686888.tar.gz)
97344b39937f/20220116_090328/output-1b686888.log.tar.gz)
sct - [https://cloudius-jenkins-test.s3.amazonaws.com/1b686888-292c-4d17-a4b5-97344b39937f/20220116_090328/sct-1b686888.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1b686888-292c-4d17-a4b5-97344b39937f/20220116_090328/sct-1b686888.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-100gb-4h-test/438/)

**Comment by fruch** [comment]
Similar print happens also on:

*Installation details*
Kernel version: `5.11.0-1022-aws`
Scylla version (or git commit hash): `4.7.dev-0.20220114.8bcd23fa0 with build-id 991662b202244e747b247a64fa0ddefaab6b53af`
Cluster size: 4 nodes (i3.2xlarge)
Scylla running with shards number (live nodes):
   longevity-lwt-3h-master-db-node-1549e9bd-1 (54.195.178.15 | 10.0.0.17): 8 shards
   longevity-lwt-3h-master-db-node-1549e9bd-2 (54.73.38.75 | 10.0.3.147): 8 shards
   longevity-lwt-3h-master-db-node-1549e9bd-3 (3.250.169.221 | 10.0.2.156): 8 shards
   longevity-lwt-3h-master-db-node-1549e9bd-4 (52.211.195.219 | 10.0.0.245): 8 shards
OS (RHEL/CentOS/Ubuntu/AWS AMI): `ami-0bf3b97eca8f38134` (aws: eu-west-1)


Test: `longevity-lwt-3h-test`
Test name: `longevity_lwt_test.LWTLongevityTest.test_lwt_longevity`
Test config file(s):
- [longevity-lwt-basic-3h.yaml](https://github.com/scylladb/scylla-cluster-tests/blob/8584390cb25ea782b18acef4a6d77099be58b0bc/test-cases/longevity/longevity-lwt-basic-3h.yaml)


**Issue description**
one node3, we can see 806525 occurrences of this error:
```
2022-01-16T07:49:47+00:00 longevity-lwt-3h-master-db-node-1549e9bd-3 !     ERR |  [shard 2] storage_proxy - exception during mutation write to 10.0.2.156: std::_Nested_exception<std::runtime_error> (Could not write mutation system:paxos (pk{00040058340e}) to commitlog): seastar::timed_out_error (timedout)
```

Restore Monitor Stack command: `$ hydra investigate show-monitor 1549e9bd-62d5-4920-91db-718024d9ced8`
Restore monitor on AWS instance using [Jenkins job](https://jenkins.scylladb.com/view/QA/job/QA-tools/job/hydra-show-monitor/parambuild/?test_id=1549e9bd-62d5-4920-91db-718024d9ced8)
Show all stored logs command: `$ hydra investigate show-logs 1549e9bd-62d5-4920-91db-718024d9ced8`

Test id: `1549e9bd-62d5-4920-91db-718024d9ced8`

Logs:
db-cluster - [https://cloudius-jenkins-test.s3.amazonaws.com/1549e9bd-62d5-4920-91db-718024d9ced8/20220116_100943/db-cluster-1549e9bd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1549e9bd-62d5-4920-91db-718024d9ced8/20220116_100943/db-cluster-1549e9bd.tar.gz)
loader-set - [https://cloudius-jenkins-test.s3.amazonaws.com/1549e9bd-62d5-4920-91db-718024d9ced8/20220116_100943/loader-set-1549e9bd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1549e9bd-62d5-4920-91db-718024d9ced8/20220116_100943/loader-set-1549e9bd.tar.gz)
monitor-set - [https://cloudius-jenkins-test.s3.amazonaws.com/1549e9bd-62d5-4920-91db-718024d9ced8/20220116_100943/monitor-set-1549e9bd.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1549e9bd-62d5-4920-91db-718024d9ced8/20220116_100943/monitor-set-1549e9bd.tar.gz)
sct - [https://cloudius-jenkins-test.s3.amazonaws.com/1549e9bd-62d5-4920-91db-718024d9ced8/20220116_100943/sct-1549e9bd.log.tar.gz](https://cloudius-jenkins-test.s3.amazonaws.com/1549e9bd-62d5-4920-91db-718024d9ced8/20220116_100943/sct-1549e9bd.log.tar.gz)

[Jenkins job URL](https://jenkins.scylladb.com/job/scylla-master/job/longevity/job/longevity-lwt-3h-test/322/)

**Comment by elcallio** [comment]
Only first run has log for the failing node, but looking at the second at least, we get timeouts _very_ early. Noteworthy though is that we have not a single commitlog message in the mix. Which makes me think that there at least is nothing noteworthy happening error-wise there...
The message itself is due to  a6202ae079b44da44f402f50001bd2df1cb49673, which adds additional info to exceptions from mutation write path. Previously you would only have seen the `seastar::timed_out_error`. I wonder if this is paxos/storage_proxy checks for `is_timeout_exception` that fails and cause wrong code path being taken...

**Comment by avikivity** [comment]
5.0 was the only vulnerable version, so no backports needed.
