### ISSUE TITLE
Moving thrift to raft broke system keyspace operations over thrift

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9927]
Since 8bcd23fa02ae9d99f6839e12a72bc5a9aa6066cb the following two dtests fail consistently as follows:

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1066/testReport/thrift_tests/TestMutations/test_invalid_strategy_class/
```
thrift.Thrift.TApplicationException: TException - service has thrown: NotFoundException()
```

https://jenkins.scylladb.com/view/master/job/scylla-master/job/dtest-release/1066/testReport/thrift_tests/TestMutations/test_system_keyspace_operations/
```
thrift.Thrift.TApplicationException: TException - service has thrown: NotFoundException()
```

I bisected the failures to change d9c315891a55694b699698807632ab93ba02e66b

Cc @slivne @avikivity @kostja @tgrabiec

**Comment by gleb-cloudius** [comment]
Well duh!

diff --git a/thrift/handler.cc b/thrift/handler.cc
index 91f3e1d893..a6ab5d72a1 100644
--- a/thrift/handler.cc
+++ b/thrift/handler.cc
@@ -971,7 +971,7 @@ class thrift_handler : public CassandraCobSvIf {
             co_await t._query_state.get_client_state().has_keyspace_access(t._db.real_database(), ks_def.name, auth::permission::ALTER);
 
             co_return co_await t.execute_schema_command([&ks_def] (service::migration_manager& mm, data_dictionary::database db) -> future<std::vector<mutation>> {
-                if (db.has_keyspace(ks_def.name)) {
+                if (!db.has_keyspace(ks_def.name)) {
                     throw NotFoundException();
                 }
                 if (!ks_def.cf_defs.empty()) {

--
			Gleb.

**Comment by avikivity** [comment]
No vulnerable branches.
