### ISSUE TITLE
memory misacounting can lead to database hanging

### ISSUE THREAD

**Issue by glommer** [scylladb/scylla#993]
When running scylla without the row cache, the database can hang.

My command line is as follows:

```
CPU=$1
IP="127.0.0.$(($CPU+1))"
SEED="127.0.0.1"
$GDB ./build/release/scylla --enable-cache 0 --collectd 0 --smp 1 --cpuset $CPU -m 512M --api-address $IP --rpc-address $IP --listen-address $IP --seed-provider-parameters seeds=$SEED --datadir /var/lib/scylla/data/$CPU --commitlog-directory /var/lib/scylla/commitlog/$CPU --max-io-requests 10 | tee /tmp/log.$IP.txt
```
The following load is then applied:

```
cassandra-stress write cl=ONE n=1000000 -rate threads=10  -node 127.0.0.1 -pop seq=1..1000000 -col 'size=FIXED(64) n=FIXED(5)'; 
```

The database hangs on database::throttle(), and when it does so, I can verify that `_dirty_memory_region_group.memory_used()` is negative (therefore converted to a large number).

Because this is a hard condition to verify, I have sprinkled some assertions in the logalloc to try to catch the moment where a region counter goes negative. It always seem to happen at the memtable destructor.

### Conditions affecting this issue:

- When running the cache, this issue doesn't show. The first step update_cache takes is to merge the memtable region's with its own. That step is the only step necessary to hide the problem - indicating that it is indeed an accounting bug. It is probably just hiding the issue, though. The cache region being bigger, it can hold a negative new region without going negative itself.

- Giving the shard more memory makes the issue harder to reproduce. Giving the shard less memory makes the issue easier to reproduce. That made me suspect region compaction, but I have seen no region compactions taking place. Most likely, less memory just makes memtables getting flushed more often.

**Comment by glommer** [comment]
@slivne Since this is a condition (potentially) affecting our memory accounting, I consider this a showstopper at least until we are able to understand what is going on.

This blocks my progress at Issue #944 . The patchset I have for that issue works well, but the database stalls eventually. Until this issue is resolved, I can't really determine why (if this is the cause, or if there is another). Worse yet, the trigger for that bug is running without the cache, which is relatively rare. Once my fix for #944 is applied, the trigger becomes running a repair - which is a lot more common.

**Comment by glommer** [comment]
@avikivity @tgrabiec You are probably the ones that know logalloc code the better, so insight here is appreciated. Reproducing it is fairly easy and described in the initial comment.

**Comment by slivne** [comment]
@pdziepak take a stab at this on monday morning prior to the daily and then we can discuss this with tomek.
