### ISSUE TITLE
table::snapshot does not handle errors from seal_snapshot

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9936]
table::snapshot is written to ignore errors after all sstables are linked to the snapshot directory.
However, if the call to seal_snapshot fails in https://github.com/scylladb/scylla/blob/985403ab99b097f64c280e201edd541f636b4368/replica/table.cc#L1476-L1479
`manifest_write` isn't signaled, causing waiters in https://github.com/scylladb/scylla/blob/985403ab99b097f64c280e201edd541f636b4368/replica/table.cc#L1484
to block forever.

This issue exists since version 3.1

**Comment by mykaul** [comment]
Fixed in 5.0, older releases are not supported anymore.
