### ISSUE TITLE
TWCS reshape can be very inefficient when a time bucket contains tons of files

### ISSUE THREAD

**Issue by raphaelsc** [scylladb/scylla#9938]
TWCS reshape can have huge write amplification when reshaping a time bucket that contains tons of files

Let's say user suddenly increases time window, meaning that files from different buckets will now belong to a single one. On restart, reshape will compact all those files together, 32 at a time.

The problem is that TWCS isn't using similar-sized policy, available in STCS reshape heuristics. So a huge file can be potentially compacted with a tiny one, making the whole process very inefficient, so reshape will take much longer to complete.

A good solution for this is to call STCS reshape logic whenever a time bucket contains more than a threshold value, which is defined according to the reshape mode.

**Comment by avikivity** [comment]
Performance, not backporting.
