### ISSUE TITLE
Not enough replicas of data is stored with multi-dc + EACH_QUORUM writes if bootstraping node is present

### ISSUE THREAD

**Issue by gleb-cloudius** [scylladb/scylla#994]

**Comment by slivne** [comment]
Add a test 

export CASSANDRA_DIR=~/scylla/build/release; pkill -9 scylla; pkill -9 java; rm -Rf core.*; KEEP_TEST_DIR=true  REUSE_CLUSTER=false DEBUG=true PRINT_DEBUG=true nosetests -v -s update_cluster_layout_tests.py:TestUpdateClusterLayout.simple_kill_new_node_while_bootstrapping_with_parallel_writes_in_multidc_test


not merged in scylla_tests - may need update after code fix
