### ISSUE TITLE
sstables bytes_on_disk accumulates logical file size rather than allocated size

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9941]
bytes_on_disk is intended to reflect the bytes allocated for the sstable files on disk.
But https://github.com/scylladb/scylla/blob/985403ab99b097f64c280e201edd541f636b4368/sstables/sstables.cc#L1310-L1321
accumulated `file_size`, which returns the files' logical size.

Instead, it should call `file_stat` and accumulate `stats_data.allocated_size`.

This causes a discrepancy between information retrieved over the `storage_service/sstables_info` api, like `nodetool status` or `nodetool cfstats` and command line tools like `df -H /var/lib/scylla`.

**Comment by avikivity** [comment]
Minor, not backporting.
