### ISSUE TITLE
Scylla failes to run on c3.2xlarge AMI with 'Invalid number of IO queues. Asked for 8. Minimum value is 1, maximum 7' 

### ISSUE THREAD

**Issue by syuu1228** [scylladb/scylla#996]
Scylla fails to run on c3.2xlarge AMI with following errors:
```
Mar 07 09:04:05 ip-10-13-184-229.ec2.internal scylla[2395]: terminate called after throwing an instance of 'std::runtime_error'
Mar 07 09:04:05 ip-10-13-184-229.ec2.internal scylla[2395]: what():  Invalid number of IO queues. Asked for 8. Minimum value is 1, maximum 7
```

Probably because of NR_CPU=8 and SET_NIC=yes,
The script for AMI is not shrinking NR_SHARDS when SET_NIC=yes:
https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_io_setup#L36

**Comment by syuu1228** [comment]
I checked shellscript on dist/common/scripts/scylla_io_setup, but it seems fine.
Problem is cpus.size() at https://github.com/scylladb/seastar/blob/b25a958e8d67af56eebc4be81e86e29a73faa18e/core/resource.cc#L191 is 7, not 8. Even "cat /proc/cpuinfo" has 8 cpus.

I found hwloc_get_nbobjs_by_type(topology, HWLOC_OBJ_PU) returns 7 (line is https://github.com/scylladb/seastar/blob/master/core/resource.cc#L272).

It's not always like that, on t2.micro hwloc_get_nbobjs_by_type(topology, HWLOC_OBJ_PU) returns 1, and my i7-4790K box (has 8 cpus) hwloc_get_nbobjs_by_type(topology, HWLOC_OBJ_PU) returns 8.

**Comment by syuu1228** [comment]
It seems we are disabling cpu0 on scylla_sysconfig_setup, when NR_CPU >= 8 and SET_NIC == no: https://github.com/scylladb/scylla/blob/master/dist/common/scripts/scylla_sysconfig_setup#L79

(BTW, is this code can be used for generic environment, or it meant for AWS only??)

So scylla_io_setup should parse $SCYLLA_ARGS and get actual number of cpus assigned for scylla.

**Comment by syuu1228** [comment]
Doing --smp $((CPU_NR - 1 )) was copied from dist/ami/files/scylla-setup.sh, so I think running it on non-AWS environment is bug. https://github.com/scylladb/scylla/commit/89dcc5dfb3f3c4c867b4b1d6a8b9dae917454524#diff-60739d0e2ff01fb16ba6c5151dfd47aaL43

**Comment by slivne** [comment]
This is meant for AWS - we dedicate a core - and actually we need to dedicate the core and its associated hyperthread for networking

So if we are doing it in non aws envs its a bug lets fix it.

What is the fix for the hwloc issue - its really strange we are running into this ?

If we have an issue with hwloc - it needs to be resolved we rely on it 

@avikivity any idea

@syuu1228  is we are doing this outside of AWS please open a bug and fix it

**Comment by avikivity** [comment]
@glommer 

I don't think we dedicate a core on all instance sizes.  Maybe there is a mismatch between the ways we calculate whether to dedicate a core or not.

**Comment by glommer** [comment]
I have just reviewed our invocation of iotune in the script, and it is wrong:
It reads:
```
        iotune --evaluation-directory /var/lib/scylla --format envfile --options-file /etc/scylla.d/io.conf
```

On EC2, we use a `--cpuset` parameter for some machines. iotune is supposed to be ran with the same `--cpuset` parameters as the expected invocation.

Changing the script to include the right `--cpuset` will fix this.

**Comment by slivne** [comment]
c3.2x is not running io_tune - it is computed via  a formula you provided a while back.

Yet the update to use cpuset seems correct for all other cases.  @syuu1228 please handle this as well

**Comment by slivne** [comment]
c3.2x is not running io_tune - it is computed via  a formula you provided a
while back.

Yet the update to use cpuset seems correct for all other cases.
