### ISSUE TITLE
cql_repl prints junk into the log

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9962]
Seen e.g. in https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4471/artifact/testlog/x86_64_release/cassandra_batch_test.5821.log
and https://jenkins.scylladb.com/view/master/job/scylla-master/job/next/4471/artifact/testlog/x86_64_release/list_test.5866.log

There are 1300+ null characters in the beginning of the log files.

Can be reproduced by e.g. `./test.py --mode=dev -s list_test` at version 188cedd53.

**Comment by bhalevy** [comment]
Cc @kostja

**Comment by kostja** [comment]
This bisects as far as 2500 commits back (year 2000).
Obviously the problem wasn't there when the patch was introduced.
cql_repl resets C++ cin/cout to redirect them to a log file, the bug may have something to do with some subsystem writing directly into fd 1,2 or libc's stdout.

**Comment by slivne** [comment]
Given that this is not new - at least from sometime in 2020 - then removing master/high

**Comment by avikivity** [comment]
I recommend not playing with cin/cout and instead using dup2(), or better performing the redirection from outside.

**Comment by kostja** [comment]
* Avi Kivity ***@***.***> [22/01/31 20:01]:
> I recommend not playing with cin/cout and instead using dup2(), or better performing the redirection from outside.

When writing this I hoped C++ had its way for dup2() which
actually works. I'll switch to dup2.

-- 
Konstantin Osipov, Moscow, Russia

**Comment by avikivity** [comment]
Test-only, not backporting.
