### ISSUE TITLE
raft: follower may mark obsolete entries committed, causing inconsistency

### ISSUE THREAD

**Issue by kbr-** [scylladb/scylla#9965]
Trace:
[commit-obsolete-entries-1.txt](https://github.com/scylladb/scylla/files/7935293/commit-obsolete-entries-1.txt)
Reproduced using https://github.com/kbr-/scylla/tree/nemesis-random-v0.1

In this trace we observe the following scenario:
1. leader `1` replicates entries up to index 25 term 2 to follower `4`
2. leader `1` manages to commit entries up to index 11
3. in the meantime, `2` becomes a leader in term 3
4. `2` manages to commit entries up to index 20 without `4` and takes a snapshot at this index
5. `2` commits more entries, up to index 30. The entries at indexes <=25 are different than the ones `4` had (they have term 3, `4` has old entries from term 2 that `1` did not manage to commit)
6. `2` tries to append a few entries to `4` at smaller and smaller indexes, failing because of mismatching entries:
```
TRACE 2022-01-25 15:48:24,989 [shard 0] raft - append_entries[00000000-0000-0000-0000-000000000004] received ct=3, prev idx=17 prev term=3 commit idx=26, idx=18 num entries=1
TRACE 2022-01-25 15:48:24,989 [shard 0] raft - append_entries[00000000-0000-0000-0000-000000000004]: no matching term at position 17: expected 3, found 2
...
TRACE 2022-01-25 15:48:24,990 [shard 0] raft - append_entries[00000000-0000-0000-0000-000000000004] received ct=3, prev idx=16 prev term=3 commit idx=26, idx=17 num entries=1
TRACE 2022-01-25 15:48:24,990 [shard 0] raft - append_entries[00000000-0000-0000-0000-000000000004]: no matching term at position 16: expected 3, found 2
```
7. eventually `4` receives the snapshot at index 20 from `2` and applies it:
```
TRACE 2022-01-25 15:48:24,991 [shard 0] raft - apply_snapshot[00000000-0000-0000-0000-000000000004]: current term: 3, term: 3, idx: 20, id: 14725bfd-5e25-482d-9633-7f8fe1cc9552, local: false
```
8. `4` receives a stray append entries request from `2` and... uses it to mark all entries up to index 25 as committed!
```
TRACE 2022-01-25 15:48:24,991 [shard 0] raft - append_entries[00000000-0000-0000-0000-000000000004] received ct=3, prev idx=16 prev term=3 commit idx=26, idx=17 num entries=1
TRACE 2022-01-25 15:48:24,991 [shard 0] raft - append_entries: skipping entry with idx 17 less than log start 21
TRACE 2022-01-25 15:48:24,991 [shard 0] raft - advance_commit_idx[00000000-0000-0000-0000-000000000004]: leader_commit_idx=26, new_commit_idx=25
TRACE 2022-01-25 15:48:24,991 [shard 0] raft - advance_commit_idx[00000000-0000-0000-0000-000000000004]: signal apply_entries: committed: 25
```
9. eventually, 4 becomes a leader, and we detect inconsistency

```
DEBUG 2022-01-25 15:48:24,996 [shard 0] randomized_nemesis_test - completion x: 45 prev digest: 501
ERROR 2022-01-25 15:48:24,996 [shard 0] randomized_nemesis_test - inconsistency: already completed but prev.digest() != seq[idx - 1].digest
x 44
idx 24
prev.digest 457
prev_x 43
prev_prev seq({0, 1, 2, 3, 4, 5, 6, 8, 7, 20, 21, 23, 25, 24, 29, 31, 19, 22, 27, 26, 28, 41, 42} _end 23)
seq[idx - 1].digest 511
seq[:idx] {0, 1, 2, 3, 4, 5, 6, 8, 7, 20, 21, 23, 25, 24, 29, 31, 32, 33, 34, 37, 40, 41, 42, 43}

mismatch at idx 16 prev[i] 19 seq[i].elem 32
mismatch at idx 17 prev[i] 22 seq[i].elem 33
mismatch at idx 18 prev[i] 27 seq[i].elem 34
mismatch at idx 19 prev[i] 26 seq[i].elem 37
mismatch at idx 20 prev[i] 28 seq[i].elem 40
when completing
x 45
prev seq({0, 1, 2, 3, 4, 5, 6, 8, 7, 20, 21, 23, 25, 24, 29, 31, 19, 22, 27, 26, 28, 41, 42, 43, 44} _end 25)
seq {0, 1, 2, 3, 4, 5, 6, 8, 7, 20, 21, 23, 25, 24, 29, 31, 32, 33, 34, 37, 40, 41, 42, 43, 44}
INFO  2022-01-25 15:48:24,996 [shard 0] randomized_nemesis_test - server 00000000-0000-0000-0000-00000000000a state machine state: seq({0} _end 1)
INFO  2022-01-25 15:48:24,996 [shard 0] randomized_nemesis_test - server 00000000-0000-0000-0000-000000000009 state machine state: seq({0} _end 1)
INFO  2022-01-25 15:48:24,996 [shard 0] randomized_nemesis_test - server 00000000-0000-0000-0000-000000000008 state machine state: seq({0} _end 1)
INFO  2022-01-25 15:48:24,996 [shard 0] randomized_nemesis_test - server 00000000-0000-0000-0000-000000000007 state machine state: seq({0, 1, 2, 3, 4, 5, 6, 8, 7, 20, 21, 23, 25, 24, 29, 31, 32, 33, 34, 37, 40, 41, 42, 43, 44} _end 25)
INFO  2022-01-25 15:48:24,996 [shard 0] randomized_nemesis_test - server 00000000-0000-0000-0000-000000000006 state machine state: seq({0, 1, 2, 3, 4, 5, 6, 8, 7, 20, 21, 23, 25, 24, 29, 31, 32, 33, 34, 37, 40, 41, 42, 43, 44, 45} _end 26)
INFO  2022-01-25 15:48:24,996 [shard 0] randomized_nemesis_test - server 00000000-0000-0000-0000-000000000005 state machine state: seq({0, 1, 2, 3, 4, 5, 6, 8, 7, 20, 21, 23, 25, 24, 29, 31, 32, 33, 34, 37, 40, 41} _end 22)
INFO  2022-01-25 15:48:24,996 [shard 0] randomized_nemesis_test - server 00000000-0000-0000-0000-000000000004 state machine state: seq({0, 1, 2, 3, 4, 5, 6, 8, 7, 20, 21, 23, 25, 24, 29, 31, 19, 22, 27, 26, 28, 41, 42, 43, 44, 45} _end 26)
INFO  2022-01-25 15:48:24,996 [shard 0] randomized_nemesis_test - server 00000000-0000-0000-0000-000000000003 state machine state: seq({0, 1, 2, 3, 4, 5, 6, 8, 7, 20, 21, 23, 25, 24, 29, 31, 32, 33, 34, 37, 40, 41} _end 22)
INFO  2022-01-25 15:48:24,996 [shard 0] randomized_nemesis_test - server 00000000-0000-0000-0000-000000000002 state machine state: seq({0, 1, 2, 3, 4, 5, 6, 8, 7, 20, 21, 23, 25, 24, 29, 31, 32, 33, 34, 37, 40, 41, 42, 43, 44} _end 25)
INFO  2022-01-25 15:48:24,996 [shard 0] randomized_nemesis_test - server 00000000-0000-0000-0000-000000000001 state machine state: seq({0, 1, 2, 3, 4, 5, 6, 8, 7, 20, 21, 23, 25, 24, 29, 31} _end 16)

```

---

It seems that the following happened: when `4` received the append entry after applying the snapshot, it did not enter this branch in `fsm::append_entries`:

```cpp
    // Ensure log matching property, even if we append no entries.
    // 3.5
    // Until the leader has discovered where it and the
    // follower’s logs match, the leader can send
    // AppendEntries with no entries (like heartbeats) to save
    // bandwidth.
    auto [match, term] = _log.match_term(request.prev_log_idx, request.prev_log_term);
    if (!match) {
        logger.trace("append_entries[{}]: no matching term at position {}: expected {}, found {}",
                _my_id, request.prev_log_idx, request.prev_log_term, term);
        // Reply false if log doesn't contain an entry at
        // prevLogIndex whose term matches prevLogTerm (§5.3).
        send_to(from, append_reply{_current_term, _commit_idx, append_reply::rejected{request.prev_log_idx, _log.last_idx()}});
        return;
    }
```
that's because the log was truncated due to the snapshot, so we couldn't detect the term mismatch and reject the request.

Instead, we went further:
```cpp
    // If there are no entries it means that the leader wants
    // to ensure forward progress. Reply with the last index
    // that matches.
    index_t last_new_idx = request.prev_log_idx;

    if (!request.entries.empty()) {
        last_new_idx = _log.maybe_append(std::move(request.entries));
    }

    advance_commit_idx(request.leader_commit_idx);
```

`_log.maybe_append(...)` didn't succeed:
```
TRACE 2022-01-25 15:48:24,991 [shard 0] raft - append_entries: skipping entry with idx 17 less than log start 21
```
but we went to `advance_commit_idx` anyway, unconditionally marking everything we had - even obsolete entries past the snapshot - as committed.

---

BTW. I checked the Raft TLA+ spec looking for clues. And I noticed that in the spec, the commit index sent by leaders is never greater than the last entry in the append_entries request: https://github.com/ongardie/raft.tla/blob/master/raft.tla#L222
Perhaps this would solve this problem.

cc @kostja @gleb-cloudius

**Comment by kbr-** [comment]
Other observations:
the Raft PhD in its description of InstallSnapshot RPC proposes that the snapshot index and term are compared to the term of the entry at the snapshot index at the receiver. If the term is different, it tells to truncate all entries beyond the snapshot index. We don't seem to do that.

However, I wonder if that's enough. Even if the term matches there - nothing guarantees that later entries match as well, no?

**Comment by gleb-cloudius** [comment]
On Tue, Jan 25, 2022 at 08:59:55AM -0800, Kamil Braun wrote:
> Other observations:
> the Raft PhD in its description of InstallSnapshot RPC proposes that the snapshot index and term are compared to the term of the entry at the snapshot index at the receiver. If the term is different, it tells to truncate all entries beyond the snapshot index. We don't seem to do that.
> 
Don't we do it?

> However, I wonder if that's enough. Even if the term matches there - nothing guarantees that later entries match as well, no?
> 
We need to advance commit index to the min(request.leader_commit_idx, matched_idx), not just request.leader_commit_idx.

--
			Gleb.

**Comment by kostja** [comment]
Log matching rule is obviously violated. We can't advance the commit index in this case. We can only trust commit index from the AppendEntries message for which the log matching rule has passed.

**Comment by gleb-cloudius** [comment]
On Tue, Jan 25, 2022 at 12:35:55PM -0800, Konstantin Osipov wrote:
> Log matching rule is obviously violated. We can't advance the commit index in this case. We can only trust commit index from the AppendEntries message for which the log matching rule has passed.
> 
The mach rule has passed. But the commit index is higher then the
matched index.

--
			Gleb.

**Comment by kostja** [comment]
Log matching rule for the commit index hasn't passed as it wasn't checked. We talk about the same thing. I'm inclined though to support Kamil's proposal that the leader shouldn't send AppendEntries with commit index higher than append_entries index, as in step 8:

> TRACE 2022-01-25 15:48:24,991 [shard 0] raft - append_entries[00000000-0000-0000-0000-000000000004] received ct=3, prev idx=16 prev term=3 commit idx=26, idx=17 num entries=1

here commit idx should not contain 26.

**Comment by kostja** [comment]
> On Tue, Jan 25, 2022 at 08:59:55AM -0800, Kamil Braun wrote: Other observations: the Raft PhD in its description of InstallSnapshot RPC proposes that the snapshot index and term are compared to the term of the entry at the snapshot index at the receiver. If the term is different, it tells to truncate all entries beyond the snapshot index. We don't seem to do that.
> Don't we do it?

I remember we do it because it was a bug and we fixed it.

**Comment by gleb-cloudius** [comment]
On Tue, Jan 25, 2022 at 11:13:13PM -0800, Konstantin Osipov wrote:
> Log matching rule for the commit index hasn't passed as it wasn't checked.
There is no such think is matching a commit index.

>  We talk about the same thing.
May be.

> I'm inclined though to support Kamil's proposal that the leader shouldn't send AppendEntries with commit index higher than append_entries index, as in step 8:
> 
Doing it either on a sender or a receiver amounts to the same thing. We
already restrict commit index on a receiver in advance_commit_idx by
log.last_idx(). We can also restrict it last_new_idx as well. Something
like:

diff --git a/raft/fsm.cc b/raft/fsm.cc
index 7cbf181155..8d72e4f8bd 100644
--- a/raft/fsm.cc
+++ b/raft/fsm.cc
@@ -607,7 +607,7 @@ void fsm::append_entries(server_id from, append_request&& request) {
         last_new_idx = _log.maybe_append(std::move(request.entries));
     }
 
-    advance_commit_idx(request.leader_commit_idx);
+    advance_commit_idx(std::min(request.leader_commit_idx, last_new_idx));
 
     send_to(from, append_reply{_current_term, _commit_idx, append_reply::accepted{last_new_idx}});
 }

If the patch to do it on a sender is as small I am fine with it as well.

--
			Gleb.

**Comment by kbr-** [comment]
Doing it on receiver may be different if we consider empty append_entries. Then we don't have last_new_idx. (? I may be wrong) On the other hand, the leader always has the tracker and knows what the matched entry is, so can calculate the `min`. But AFAIK we don't do empty append_entries.

**Comment by gleb-cloudius** [comment]
On Wed, Jan 26, 2022 at 01:38:10AM -0800, Kamil Braun wrote:
> Doing it on receiver may be different if we consider empty append_entries. Then we don't have last_new_idx. (? I may be wrong) On the other hand, the leader always has the tracker and knows what the matched entry is, so can calculate the `min`. But AFAIK we don't do empty append_entries.
> 
We do, but IIRC only if there is no entries to propagate any more and commit
index is lagging. In such situation commit index cannot be larger than
matched index.

--
			Gleb.

**Comment by kbr-** [comment]
The patch proposed by Gleb stops the problem from reproducing.
It also works for empty append entries - in that case the commit index will be `min`ed with `request.prev_log_idx`, which is what we want.
I sent a patchset to the ML.

**Comment by avikivity** [comment]
Raft is still experimental, not backporting.
