### ISSUE TITLE
seastar: librarify iotune

### ISSUE THREAD

**Issue by slivne** [scylladb/scylla#997]
avi wrote ...

I think it is a good suggestion.  We can librarify iotune (but the working bits in libseastar.a) and scylla --verify-environment can call them.
For example, commitlog and each data_file_directory may be on separate disks, and we will need to iotune and qualify each separately (and seastar will need an ioqueue set for each disk).

**Comment by glommer** [comment]
We should probably close this. We haven't done this, but I don't see a push for us to do it.
iotune has been working well as a standalone application.

**Comment by avikivity** [comment]
I think it's still useful. Some applications might not want a separate install step but instead run iotune when starting up for the first time.

**Comment by avikivity** [comment]
Closing, since it's a Seastar issue, not Scylla.
