### ISSUE TITLE
scylla_sstables_index_page_cache_hits is not ticking

### ISSUE THREAD

**Issue by dkropachev** [scylladb/scylla#9973]
Because of https://github.com/scylladb/scylla/issues/9968, scylla is triggering index cache on table when cache on it is disabled by table configuration.

But by some reason when cache is triggered `scylla_sstables_index_page_cache_hits` is not ticking, while other metrics are ticking properly `scylla_sstables_index_page_cache_misses`, `scylla_sstables_index_page_cache_populations`.

Scylla version: `4.6.rc2`

**Steps to reproduce**
1. Deploy 1 node
2. Create table: `CREATE COLUMNFAMILY bypass_cache.user_events (key varchar PRIMARY KEY, c1 text, c2 text) WITH comment='test cf' AND compaction = {'class': 'SizeTieredCompactionStrategy', 'enabled': 'true'} AND compression = {} AND caching = {'enabled':false}`
3. Insert some data: `INSERT INTO bypass_cache.user_events (key, c1, c2) VALUES (?, 'value1', 'value2')`
4. Get metrics before query: `curl http://{node_ip}:9180/metrics`
5. Run query 10 times: ` SELECT * FROM bypass_cache.user_events`
6. Get metrics after query: `curl http://{node_ip}:9180/metrics`
7. Compare `scylla_sstables_index_page_cache_misses`, `scylla_sstables_index_page_cache_populations` and `scylla_sstables_index_page_cache_hits`

**Actual results**
`scylla_sstables_index_page_cache_misses`, `scylla_sstables_index_page_cache_populations` are increased by 1, while `scylla_sstables_index_page_cache_hits` is not

**Expected results**
Expected to see all metrics increased by 1

**Comment by tgrabiec** [comment]
`scylla_sstables_index_page_cache_hits` is not ticking because the summary page is in the partition index page cache (not to be confused with sstable index file page cache) and `scylla_sstables_index_page_hits` is ticking instead.
