### ISSUE TITLE
compaction_manager active_tasks bookkeeping may go out of sync when tasks are stopped

### ISSUE THREAD

**Issue by bhalevy** [scylladb/scylla#9974]
For example, after 07fba4ab5d24385392a8631dcf5fa16c2754386e, in `run_custom_job`,
`_stats.active_tasks` is incremented only if `!task->stopping` but it is decremented unconditionally.

See https://github.com/scylladb/scylla/blob/ba6c02b38a8cb3c837a2110aeb8a5680ec515cda/compaction/compaction_manager.cc#L324-L340

To a lesser extent even the pre-existing code isn't 100% error-safe since active_tasks is incremented inside `with_lock` (that might theoretically fail) while it's decremented unconditionally in the `then_wrapped` continuation.

**Comment by avikivity** [comment]
@bhalevy does this merit a backport? though it's so big it's not backportable.

**Comment by bhalevy** [comment]
> @bhalevy does this merit a backport? though it's so big it's not backportable.

No it doesn't merit a backport.  The issue is about metrics going out of sync.
I don't think it has any functional implications.
FWIW, the fix is present in 5.1 / 2022.1
