### ISSUE TITLE
how to run multiple Scylla instances on the same host?

### ISSUE THREAD

**Issue by Nurlan199206** [scylladb/scylla#9975]
i'm trying to up two scylla containers with different ports but `cqlsh` connection fails for second container.

`docker run --name scylla-reader -p 9042:9042 -v /home/ubuntu/scylla-reader/scylla.yaml:/etc/scylla/scylla.yaml --hostname scylla -d scylladb/scylla:4.5.0`

`docker run --name scylla-writer -p 9041:9041 -v /home/ubuntu/scylla-writer/scylla.yaml:/etc/scylla/scylla.yaml --hostname scylla -d scylladb/scylla:4.5.0 --smp 2`

```
docker exec -it scylla-writer cqlsh 10.130.0.31 9041

Connection error: ('Unable to connect to any servers', {'10.130.0.31': error(None, "Tried connecting to [('10.130.0.31', 9041)]. Last error: timed out")})
```

for second container i'm changed in `scylla.yaml`: 
`listen_address: 10.130.0.31`
`rpc_address: 10.130.0.31`
`native_transport_port: 9041`

```
docker ps | grep scylla
40d569d766bd        scylladb/scylla:4.5.0                                                      "/docker-entrypoint.…"   5 minutes ago       Up 5 minutes        22/tcp, 7000-7001/tcp, 9042/tcp, 9160/tcp, 9180/tcp, 10000/tcp, 0.0.0.0:9041->9041/tcp                        scylla-writer
832fb0683a18        scylladb/scylla:4.5.0                                                      "/docker-entrypoint.…"   18 hours ago        Up 18 hours         22/tcp, 7000-7001/tcp, 9160/tcp, 9180/tcp, 10000/tcp, 0.0.0.0:9042->9042/tcp                                  scylla-reader
```

*Installation details*
Scylla version (or git commit hash): scylla:4.5.0
Cluster size:
OS (RHEL/CentOS/Ubuntu/AWS AMI): Ubuntu 20.04.1 LTS

**Comment by psarna** [comment]
I can't reproduce this problem, but I see at least two things to try:
1. I see that both images specify the same hostname (scylla), perhaps it would be better if each had its own hostname?
2. I don't really know what's your intention with port forwarding and is `10.130.0.31` the address of your host or of the docker, but I'd suggest the following, assuming that it's the host address:
    * remove the custom listen_address, rpc_address and native_transport_port config values altogether and let the docker use the default 9042 port
    * when port forwarding, simply forward the container's default CQL port (9042) to host's 9041, like this: `-p 9041:9042`

Maybe it will work as you intend? I suspect that when you configure Scylla via scylla.yaml to use the host's IP address (10.130.0.31), it can't really use the address from the container so it fails to boot. And what you probably want is simply to be able to contact two separate Scylla nodes via different host port.

**Comment by Nurlan199206** [comment]
My fail hahahaha :)

it's works

`docker run --name scylla-writer -p 9042:9042 --hostname scylla-writer -d scylladb/scylla:4.5.0 --smp 2`

`docker run --name scylla-reader -p 9041:9042 --hostname scylla-reader -d scylladb/scylla:4.5.0`
